### ISSUE TITLE
Number of decimals missing in Prestashop 1.7.7

### ISSUE THREAD

**Issue by aruneaskan** [PrestaShop/PrestaShop#22617] opened 2020-12-29 11:21 UTC
#### Describe the bug

A number of decimals field is missing in Shop Parameters -> General -> Number of Decimals. This field is helping me to round off the price while including tax.

What is the alternative way for this? I tried by changing International -> Localization -> Currencies -> Decimals to 0. But in the cart and checkout, the prices are varying.

![image](https://user-images.githubusercontent.com/39294418/103280297-08999f00-49f6-11eb-8759-6fa280a293b3.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2020-12-29 14:50
Hello @aruneaskan 

It's not missing, it's just we replace it under BO>IMPROVE>International>Localization>Currencies> edit your currency: 

![image](https://user-images.githubusercontent.com/23308427/103292153-8b6a2c00-49ed-11eb-816b-00c57b8895c3.png)

> But in the cart and checkout, the prices are varying.

What do you mean by the prices are varying?

Please check and feedback.
Thanks!

**Comment by aruneaskan** [comment] 2020-12-29 15:00
In Prestashop 1.7.7. I would like to have rounded decimals to 2nd decimal place. Current status is:

Prices are rounded up to full numbers so a product with price 12.10 or 12.49 is visible in front office as 12.00. Prices above 12.50 are visible as 13.00.
I can change the rounding but it always works to full numbers and not decimals
International/localization is set to 2 decimals
After adding to cart the unit price is correct with decimals
I'd like the customer to see a price of 12.49 if it's 12.49 and not 12.00 How can I change this to have the rounding to decimals and not to full numbers?
![image](https://user-images.githubusercontent.com/39294418/103292828-a13f1780-4a14-11eb-95bb-cde3a318f6d8.png)

**Comment by Hlavtox** [comment] 2020-12-30 08:40
@aruneaskan Some module is influecing your prices, your you have something wrong in the CLDR data, it works fine in clean 1.7.7. ;-)

as @hibatallahAouadni said, you just set 2 decimals in the currency settings and it shows 2 decimal places everywhere and it rounds everything to 2 decimals.

**Comment by aruneaskan** [comment] 2020-12-30 08:46
@Hlavtox In debug mode I set "Disable all overrides" to "Yes" and "Disable non-PrestaShop modules" to Yes. Still the same issue as above screenshot

**Comment by Hlavtox** [comment] 2020-12-30 08:49
@aruneaskan Try this: https://github.com/PrestaShop/PrestaShop/issues/22508#issuecomment-748686016 and tell me what it shows.

**Comment by aruneaskan** [comment] 2020-12-30 08:55
![image](https://user-images.githubusercontent.com/39294418/103340633-8c14c800-4aaa-11eb-9917-cc95faab700a.png)
![image](https://user-images.githubusercontent.com/39294418/103340730-d138fa00-4aaa-11eb-8015-4d86100f8fe0.png)
As per your comment I added. Please refer above screenshots

**Comment by Hlavtox** [comment] 2020-12-30 09:21
@aruneaskan OK, try this:
- open /src/Core/Localization/Number
- find $this->numberSpecification = $specification; on line 103
- put dump($specification); after it
- go to cart page and send screenshot of the output

It should be like this:
  #maxFractionDigits: 2
  #minFractionDigits: 2

**Comment by aruneaskan** [comment] 2020-12-30 09:32
![image](https://user-images.githubusercontent.com/39294418/103342598-ebc1a200-4aaf-11eb-9f19-68b100c904ba.png)
@Hlavtox .. Please check above screenshot

**Comment by hibatallahAouadni** [comment] 2020-12-31 16:13
Hello @aruneaskan 

I believe your problem is not with **Number of decimals missing in PrestaShop 1.7.7** it's about rounding.
If so, we already have an Epic for the rounding problems, check it out #19445

Thanks!

**Comment by aruneaskan** [comment] 2021-01-02 05:04
HI @hibatallahAouadni .. Please let me know what I need to do to resolve this issue. I couldn't understand what is explained on this link #19445. Please help me out here itself.

Thanks

**Comment by aruneaskan** [comment] 2021-01-04 11:14
@hibatallahAouadni any update for me. For better understanding please refer to my below screenshots
![image](https://user-images.githubusercontent.com/39294418/103529465-bf40c800-4eab-11eb-8659-9e95f22e35e5.png)

![image](https://user-images.githubusercontent.com/39294418/103529653-0929ae00-4eac-11eb-9f84-cb7a07cb2bf2.png)

Please do the needful asap.

**Comment by hibatallahAouadni** [comment] 2021-01-04 11:24
Hello @aruneaskan 

If the product price is : 13.80 => it should display: 14.00
If the product price is: 13.20 => it should display: 13.00

That's what you want?

**Comment by aruneaskan** [comment] 2021-01-04 11:25
Yes @hibatallahAouadni you are right. It should reflect in all areas like BO, email, invoices pdf etc.,

Thanks

**Comment by Hlavtox** [comment] 2021-01-04 11:33
@aruneaskan Why do you want to display decimal places, if you round everything to 0? Set your product prices correctly to whole numbers and everything will be fine.

I think Prestashop in the current version does not allow this. Number of decimals displayed = number of decimals used for rounding.

**Comment by hibatallahAouadni** [comment] 2021-01-04 11:37
Hello @aruneaskan 

That was a bug with the old version and it has been fixed with PS1.7.7.0
You should set **Number of decimals** to 0.

I close this issue cause it's not a bug :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-04 11:37 UTC
Labels: Bug, BO, International, Localization, Currencies, No change required, 1.7.7.0

**Comment by aruneaskan** [comment] 2021-01-04 11:43
Hi @Hlavtox those prices are showing including tax. 
For example - product price - Rs. 72.00 + tax 18% = Rs.84.96 - it is showing like this. So it should be rounded to Rs.85.00.
It's not happening now. I saw that this issue is closed. My bad.
