### ISSUE TITLE
Re-Open issue #27160

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#27167] opened 2022-01-02 03:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Issue https://github.com/PrestaShop/PrestaShop/issues/27160 was closed as "duplicate" of https://github.com/PrestaShop/PrestaShop/issues/9947

As stated, this issue doesn't happen on v. 1.7.8.2 (with a migrated store, so exactly same data).

If this is really a "duplicate", kindly inform what might have solved it on that version so, maybe, we can derive the fix to 1.7.7.8.

With version 1.7.8.2, Brands & Suppliers open within little seconds.

### Steps to reproduce

As stated on original issue

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.2.24

**Comment by hibatallahAouadni** [comment] 2022-01-03 13:41
Hello @seederp2p 

You said that you didn't encounter the issue with PS1782, did you mean that on shop version 1.7.8.2 with arround 13800 products and 780 brands, the Brands page load in secondes?
Cause as you can see the original issue #9947 is still open.
Waiting for your feedback.

Thanks!

**Comment by seederp2p** [comment] 2022-01-03 13:45
Yes. The exact same store (upgraded). No problems with 1.7.8.2 and with problems with 1.7.7.8

The issue that you're referring to talks about 1.7.4 (!).

**Comment by hibatallahAouadni** [comment] 2022-01-03 13:51
@seederp2p so the problem has been fixed with PS1782 :tada:  and why you open this issue?

**Comment by seederp2p** [comment] 2022-01-03 13:58
Well, IF it was fixed, where's the fix so we can adapt and apply to version 1.7.7.8? I don't see anything on the change logs.

As you understand not all the people can upgrade their stores every single time and every single version due to the need of assuring the existing modules compatibility.

So the goal here is simple:
1 - Is there an issue or not?
2 - If there's an issue, and it was fixed, where's the fix / reference?

Did you managed to reproduce the issue in your lab? Did you ask any dev about this to doublecheck if the team knows this issue?

Cheers.

**Comment by hibatallahAouadni** [comment] 2022-01-03 14:18
Hello @seederp2p 

> Is there an issue or not?

Yes, there is an issue #9947 

> If there's an issue, and it was fixed, where's the fix / reference?
> Did you managed to reproduce the issue in your lab? Did you ask any dev about this to doublecheck if the team knows this issue?

AFAIK, this issue is not fixed yet and that's why I asked the maintainers to check if the issue has been fixed on their shops in this [comment](https://github.com/PrestaShop/PrestaShop/issues/9947#issuecomment-1004107623).

So, I'm closing this issue as duplicate to this one #9947 
Please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-03 14:18
Duplicate of #9947

**Closed as completed by hibatallahAouadni** 2022-01-03 14:18 UTC
Labels: Bug, BO, Duplicate, Brands, Performance, 1.7.7.8, Invalid
