### ISSUE TITLE
In module configuration pages, the "Activate module for this shop context" checkbox does not work

### ISSUE THREAD

**Issue by IcarusSosie** [PrestaShop/PrestaShop#24354] opened 2021-05-05 13:34 UTC
#### Describe the bug

When the multistore option is activated and at least two shops have been created, a new panel is displayed at the bottom of module configuration pages, containing a checkbox labeled "Activate module for this shop context". Checking/unchecking this checkbox is supposed to enable/disable the current module for the current shop context.

This does not currently work. Accessing a module's configuration page from a context where it is disabled and clicking  the checkbox to activate it just reloads the page, leaving the module deactivated and reseting the checkbox to its unchecked state.

#### Expected behavior

Checking the box should systematically enable the module for the current context, and unchecking it should disable it.

#### Steps to Reproduce

1. Activate the multistore feature if disabled, in Parameters > General > Enable Multistore
2. Access Multistore in Advanced Parameters and create one if only one exists
3. Install a module that has a configuration page, like the Contact form module for example
4. Access its configuration page from the context of a shop where it's enabled, and then swap to the new shop
5. It will show as disabled by default. Check the "Activate module for this shop context" box.
6. The page reloads showing the checkbox unchecked, and the module is still disabled in this context

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.27

**Comment by hibatallahAouadni** [comment] 2021-05-06 06:09
Hello @IcarusSosie 

I reproduce the issue with PS1.7.7.3, 1.7.8.x and develop, see the attached screen reocrd below:

https://www.awesomescreenshot.com/video/3641601?key=0c0e5bd67011c9f23f057638e5b9e048

This issue is a regression, cause I couldn't reproduce it with PS1.7.6.7.
I’ll add this to the debug backlog, thanks for your PR :rocket: 

Thank you

**Comment by Progi1984** [comment] 2021-05-07 12:03
Fixed by @IcarusSosie in #24353

**Closed as completed by Progi1984** 2021-05-07 12:03 UTC
Labels: Bug, develop, Minor, BO, Multistore, Regression, Fixed, Module manager, PR available, 1.7.7.3, 1.7.8.x
