### ISSUE TITLE
PS 1.7.5.2 - Cart refreshing problem

### ISSUE THREAD

**Issue by msornin** [PrestaShop/PrestaShop#18693] opened 2020-04-17 14:23 UTC
Hello,

Prestashop 1.7.5.2 site, classic theme, hosted by o2switch, Version php 7.1.
For some time now, the add to basket popup has not been displayed, the basket icon with the number of items has not automatically refreshed and in the Basket window, the "Continue shopping" button does not appear more next to the "Order" button it is displayed just as a link below the basket detail on the left. I do not remember having made changes before this problem except for module updates.
I searched the forums, checked the recommended settings, I activated the debub mode in the file "define.inc.ph", not successful.
I returned the original theme, deactivated all the modules one by one, emptied the caches correctly each time, deleted the contents of the cache folder located in the var folder, without success.

Here is a copy of the "Basket" screen. While I have disabled all modules (except ps_mainmenu, ps_newproducts, ps_shoppingcart).
![copie-ecran-panier](https://user-images.githubusercontent.com/63857678/79579306-b1ea7000-80c7-11ea-850a-41fb0a75ba49.png)

I'm coming to you because I don't know what to do?

I apologize for my language, I translated with google, I don't know enough english.

Thank you for the help that you will give me.

Michelle

**Comment by florine2623** [comment] 2020-04-17 14:50
Hi @msornin ,
You need to go to Modules > Modules Manager > Shopping Cart and activate ajax : 
![Capture d’écran 2020-04-17 à 16 49 43](https://user-images.githubusercontent.com/16019289/79582055-8b2e3880-80cb-11ea-99b5-56e52767f67b.png)
Please check and let me know !

**Comment by msornin** [comment] 2020-04-17 15:18
Thank you florine for your answer, yes the ajax function on the cart is activated. 
See you other thing, please

**Comment by florine2623** [comment] 2020-04-17 15:32
Do you have any error in the console when adding a product to the cart ?

**Comment by msornin** [comment] 2020-04-17 15:39
No, I have no error.

**Comment by florine2623** [comment] 2020-04-17 15:41
Comment the override folder like so ```override```becomes ```_override```.
Maybe one of the modules you have is overriding this feature.
Please check and let me know !

**Comment by msornin** [comment] 2020-04-17 15:55
I commented on the override folder in _override. Empty all the caches and repeat the tests, nothing changes.
Do you want me to give you the site url?

**Comment by msornin** [comment] 2020-04-18 11:17
is there someone available on weekends?

**Comment by khouloudbelguith** [comment] 2020-04-20 14:49
Hi @msornin,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17633 to fix the issue.
Your ticket is a duplicate of #16665
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-20 14:50
Duplicate of #16665

**Closed as completed by khouloudbelguith** 2020-04-20 14:49 UTC
Labels: FO, Duplicate, ps_shoppingcart, 1.7.5.2
