### ISSUE TITLE
Mail themes cache

### ISSUE THREAD

**Issue by NKoonen** [PrestaShop/PrestaShop#21104] opened 2020-09-22 11:59 UTC
#### Describe the bug

When editing a mail theme the recently made edits won't be visible until a cache clear.
Even when cache is globally disabled in the store, and after regenerating mails, you still need to refresh cache.

#### Expected behavior

When cache is disabled have the theme edits after regenerating the templates visible.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by sarahdib** [comment] 2020-09-22 13:23
@PrestaShop/product-team Could you check this ? 

The cache option seems to be apply only to the template not email.

**Comment by LouiseBonnard** [comment] 2020-09-22 13:47
@sarahdib, is it not a bug?

**Comment by sarahdib** [comment] 2020-09-29 12:42
@LouiseBonnard no it's an improvement I think

**Comment by NKoonen** [comment] 2020-09-29 12:56
> @LouiseBonnard no it's an improvement I think

If people disable cache, you can't expect people to still clear cache.
Because if the cache was really disabled, there is nothing to clear.

**Comment by NKoonen** [comment] 2020-10-20 12:03
Any news on this issue?
It's weird, when all of Prestahop's cache is disabled it still uses (smarty) cache.

**Comment by MatShir** [comment] 2021-01-13 00:29
It is weird, could @PrestaShop/prestashop-core-developers have a look ? 😄 
It should be directly visible, WDYT ?

**Comment by PierreRambaud** [comment] 2021-01-14 15:14
I agree, if we disable the Cache, we should have no cache, it's a bug, not an improvement :thinking:

**Comment by hibatallahAouadni** [comment] 2023-09-13 15:46
Closing this issue in favor of #22968 (more details)

**Comment by hibatallahAouadni** [comment] 2023-09-13 15:46
Duplicate of #22968

**Closed as completed by hibatallahAouadni** 2023-09-13 15:46 UTC
Labels: Bug, CO, Duplicate, Email, Email theme, 1.7.7.1
