### ISSUE TITLE
[Modules optimization] Do not install development dependencies on production and use main vendor folder

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#27314] opened 2022-01-11 18:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

All new prestashop modules have their own `vendor` folder nowadays, but they often duplicate main `/vendor` packages and install a lot of development dependencies useless on production site. For example I installed *ps_emailalerts* module from addons marketplace through my shop's BO and it has ie. php-cs-fixer (couple different versions), php_codesniffer, prestashop dev-tools and config-standard, several symfony packages, etc.
I think it would be better to redesign this behaviour for all modules.

### Expected behavior

1. When I install a module from addons marketplace in shop's BO I want to have only production dependencies installed with it.
2. Modules need to use main `/vendor` folder for their dependencies whenever possible. They're not a standalone applications, but require Prestashop installation so they should share resources to avoid duplications.

### Steps to reproduce

1. Check `vendor` folder in several prestashop modules installed on the shop eg. `ps_emailalerts`, `ps_facebook`, `ps_metrics`, etc.

### PrestaShop version(s) where the bug happened

1.7

**Comment by hibatallahAouadni** [comment] 2022-01-12 10:56
Hello @SharakPL 

Thanks for reporting this issue!
It looks more like an improvement than a bug. So, I'm going to ping the dev team to check it :wink:

Ping @PrestaShop/prestashop-core-developers  do you think this is the expected behavior or not?
Thanks in advance :pray:

**Comment by SharakPL** [comment] 2022-01-12 15:22
You're right it's more a feature request than a bug. I've been sick lately so I blame not using correct issue type on that 😅

**Comment by hibatallahAouadni** [comment] 2022-01-12 16:54
> I've been sick lately

Hope you'll get better soon :pray:

**Comment by kpodemski** [comment] 2023-07-26 13:59
I'm closing this issue since it must've been a mistake in the release process, normally, there's a `composer install --no-dev` and it should be all good.

**Closed as completed by kpodemski** 2023-07-26 13:59 UTC
Labels: Feature, CO, Modules, No change required, Module
