### ISSUE TITLE
Admin crash after 1-click Upgrade 1.7.8.7 to 1.7.8.8

### ISSUE THREAD

**Issue by BazerIsBack** [PrestaShop/PrestaShop#31368] opened 2023-02-15 08:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As mentioned, i did upgrade from 1.7.8.7 to 1.7.8.8 via 1 clickupgrade and cant acess admin page.

By activating debug mode i get:

(3/3)                                     DriverException                                                                  An exception occurred in driver: SQLSTATE[HY000] [2026] SSL connection error: SSL_CTX_set_default_verify_paths failed
--
in AbstractMySQLDriver.php line 106
at AbstractMySQLDriver->convertException('An exception occurred in driver: SQLSTATE[HY000] [2026] SSL connection error: SSL_CTX_set_default_verify_paths failed', object(PDOException))in DBALException.php line 169
at DBALException::wrapException(object(Driver), object(PDOException), 'An exception occurred in driver: SQLSTATE[HY000] [2026] SSL connection error: SSL_CTX_set_default_verify_paths failed')in DBALException.php line 155
at DBALException::driverException(object(Driver), object(PDOException))in Driver.php line 28
at Driver->connect(array('driver'  => 'pdo_mysql', 'host' => 'lhcp3294.webapps.net', 'port' =>  '', 'dbname' => 'j62tvw6u_pitchprint', 'user' => 'j62tvw6u_pp',  'password' => '********', 'charset' => 'UTF8',  'driverOptions' => array('SET sql_mode=(SELECT REPLACE(@@sql_mode,\'ONLY_FULL_GROUP_BY\',\'\'))', false), 'serverVersion' => 5.7, 'defaultTableOptions' => array()), 'j62tvw6u_pp', '********', array('SET sql_mode=(SELECT REPLACE(@@sql_mode,\'ONLY_FULL_GROUP_BY\',\'\'))', false))in Connection.php line 356
at Connection->connect()in Connection.php line 891
at Connection->executeQuery('SELECT  t0.id_lang AS id_lang_1, t0.name AS name_2, t0.active AS active_3,  t0.iso_code AS iso_code_4, t0.language_code AS language_code_5,  t0.locale AS locale_6, t0.date_format_lite AS date_format_lite_7,  t0.date_format_full AS date_format_full_8, t0.is_rtl AS is_rtl_9 FROM  ps_lang t0 WHERE t0.locale = ? LIMIT 1', array('fr-FR'), array('string'))in BasicEntityPersister.php line 726
at BasicEntityPersister->load(array('locale' => 'fr-FR'), null, null, array(), null, 1, null)in EntityRepository.php line 193
at EntityRepository->findOneBy(array('locale' => 'fr-FR'))in DatabaseTranslationLoader.php line 72
at DatabaseTranslationLoader->load('AdminActions.fr-FR.db', 'fr-FR', 'AdminActions')in Translator.php line 385
at Translator->doLoadCatalogue('fr-FR')in Translator.php line 277
at Translator->initializeCatalogue('fr-FR')in Translator.php line 128
at Translator->initializeCatalogue('fr-FR')in Translator.php line 314
at Translator->dumpCatalogue('fr-FR', object(ResourceCheckerConfigCache))in Translator.php line 299
at Translator->Symfony\Component\Translation\{closure}(object(ResourceCheckerConfigCache))in ResourceCheckerConfigCacheFactory.php line 43
at ResourceCheckerConfigCacheFactory->cache('/home/j62tvw6u/pitchprint.icones.fr/var/cache/dev/translations/catalogue.fr-FR.L8dqxxF.php', object(Closure))in Translator.php line 300
at Translator->initializeCacheCatalogue('fr-FR')in Translator.php line 265
at Translator->loadCatalogue('fr-FR')in Translator.php line 241
at Translator->getCatalogue('fr-FR')in Translator.php line 198
at Translator->trans('Successful deletion.', array(), 'AdminNotificationsSuccess', null)in PrestaShopTranslatorTrait.php line 61
at Translator->trans('Successful deletion.', array(), 'AdminNotificationsSuccess', null)in LoggingTranslator.php line 47
at LoggingTranslator->trans('Successful deletion.', array(), 'AdminNotificationsSuccess', null)in DataCollectorTranslator.php line 50
at DataCollectorTranslator->trans('Successful deletion.', array(), 'AdminNotificationsSuccess', null)in PrestaShopTranslatorTrait.php line 61
at DataCollectorTranslator->trans('Successful deletion.', array(), 'Admin.Notifications.Success', null)in Controller.php line 338
at ControllerCore->trans('Successful deletion.', array('legacy' => 'htmlspecialchars'), 'Admin.Notifications.Success')in AdminController.php line 481
at AdminControllerCore->__construct()in LegacyContext.php line 86
at LegacyContext->getContext()in UserLocaleListener.php line 39
at UserLocaleListener->__construct(object(LegacyContext))in appDevDebugProjectContainer.php line 4123
at appDevDebugProjectContainer->getPrestashop_UserLocale_ListenerService()in appDevDebugProjectContainer.php line 4652
at appDevDebugProjectContainer->ContainerXnpnwlw\{closure}()in EventDispatcher.php line 231
at EventDispatcher->sortListeners('kernel.request')in EventDispatcher.php line 61
at EventDispatcher->getListeners('kernel.request')in ContainerAwareEventDispatcher.php line 129
at ContainerAwareEventDispatcher->getListeners('kernel.request')in TraceableEventDispatcher.php line 259
at TraceableEventDispatcher->preProcess('kernel.request')in TraceableEventDispatcher.php line 137
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)in index.php line 82

</div>
</body>
</html>

### Expected behavior

this topic https://github.com/PrestaShop/PrestaShop/issues/30937

talk about the first part of my problem but now i have the actual log.
but mention that is probably not about the presta Core but server conf ?
 i'm lost..

Thank you by advance

### Steps to reproduce

when i try to reach the store admin, it's completely blank (firefox), error 500 on chrome.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by hibatallahAouadni** [comment] 2023-02-16 02:37
Hello @BazerIsBack 

Unfortunately, as I mentioned in the other issue it seems a server configuration problem cause we can't reproduce the issue.
I have to close the issue cause we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Closed as completed by hibatallahAouadni** 2023-02-16 02:37 UTC
Labels: Bug, Invalid
