### ISSUE TITLE
I want to upgrade my theme easily

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29192] opened 2022-07-28 09:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As a merchant, when I want to upgrade my theme, I have to replace my theme and  then lose all my configuration.

If you have theme A installed and you try to install a newer version of theme A, you shouldn't have the theme installed twice; the previous theme should be updated
A theme that is not compatible with the current core version should be rejected during the installation.

from this [comment](https://github.com/PrestaShop/classic-theme/pull/36)

### Describe the solution you'd like

Be able to upgrade my theme. If some contributors have an idea of the best way to perform this action, your ideas are welcomed.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by HanaRebaiQA** [comment] 2022-07-28 10:15
Hello @MatShir

Thanks for your suggestion.
Is this ticket similar to yours [#10056](https://github.com/PrestaShop/PrestaShop/issues/10056) ?

Thank you!

**Comment by hibatallahAouadni** [comment] 2022-08-19 16:45
Hello @MatShir 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10056. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-19 16:45
Duplicate of #10056

**Closed as completed by hibatallahAouadni** 2022-08-19 16:45 UTC
Labels: Feature, BO, Duplicate, Design, Theme & logo, Invalid
