### ISSUE TITLE
No carrier available when using voucher

### ISSUE THREAD

**Issue by hejmi** [PrestaShop/PrestaShop#25444] opened 2021-07-28 06:31 UTC
#### Describe the bug

Carrier is not available when using voucher on checkout.
Using 1 carrier and 1 voucher, if voucher is disabled in BO everything works as it supposed to, enabling it in BO the carrier is not available in checkout.
If steps to reproduce is followed and the voucher is inactivated in BO afterwards, the checkout process will work fine again.

#### Expected behavior

Checkout process success with option to use voucher and select carrier.

#### Steps to Reproduce

1a. Add carrier, total price setting, intervall 0-500 = 69, 500-100000 = 0)
1b. Add carrier, total weight setting, intervall 0-100kg = 69 and settings for shipping "free shipping starts at" = 500
2. Add voucher, available for everyone, discount 30%, Valid on order (without shipping)
3. Add items to cart (total under 500)
4. Goto checkout
5. Activate voucher code in checkout
6. Increase items in cart to get total over 500
7. No carrier available

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-07-28 09:34
Hello @hejmi 

Thanks for the detailed issue :clap: 
Your issue seems related to these issues #9688 & #15458, could you please check it and feedback.

Thanks!

**Comment by hejmi** [comment] 2021-07-28 09:53
Hi @hibatallahAouadni, thank you for your response!

I'm sorry but I can't find the similarity, maybe I'm missing something..?
I don't have the option to set Shipping Restriction as shown in #9688, maybe this option is removed in ps 1.7.7.5? 

The behavior of the checkout is so weird, after the message for "no carrier available, please select another payment method" is shown in checkout, there is NO other way to get it working except:
1. disabling the voucher 
2. clear browser history
3. Pray

If I try to lower cart value under 500 again or removing the voucher from the cart, doesn't solve it either!
It must be disabled in BO... 😔

Kind regards, Michael

**Comment by khouloudbelguith** [comment] 2021-07-30 09:42
Hi @hejmi,

Thanks for your feedback.
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10903
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2021-07-30 09:42
Duplicate of #10903

**Comment by hejmi** [comment] 2021-07-30 10:16
Hi @khouloudbelguith!
Well not really a duplicate since my checkout is working as long as the voucher code is not given. 

I think it's a really easy fix just if one knows in which controller to look. 
There must be some code connected to voucher that clears or sets a faulty value for shipping, making the payment module think delivery is to a not activated country or something like that. 

I'm using the same module for payment (Klarna checkout) one-page checkout, in another shop with ps 1.7.5.2 without any problems at all in checkout and with same voucher.
So something must have happen between 1.7.5 and 1.7.7. It can't be 3 years ago 1.7.5?
And if it's really been a problem in 3 years, why is there even an option to add vouchers if it can't be used?

**Comment by khouloudbelguith** [comment] 2021-07-30 11:31
@hejmi, thanks for your feedback.
I will re-open the issue.
I attached a screen record with PS1775.
https://drive.google.com/file/d/14IKQ5_kTVkSYklUS1bxZUSp0x_SlHyXu/view?usp=sharing

Thanks to check and feedback.

**Comment by hejmi** [comment] 2021-07-30 11:47
@khouloudbelguith, thank you!
 I don't use a minimum amount in cart rules, don't know if that will make any difference though.. 
 I also have taxes enabled (25%) on carrier.
 I've spoken to the developer team of Klarna Checkout as well, answer from them:
_The Klarna Payments module simply adds Klarna payment methods to your checkout. We would recommend looking into your shipping options and vouchers, and how those interact with each other. We have not previously encountered issues with vouchers and shipping options as it relates to our module._

BUT After an update of the klarna module it seems to work so far! 
There must be some kind of changes from ps 1.7.5 to 1.7.7 that is not compatible with the previous version of klarna checkout.

Well, it's working for now, so maybe close the issue again, sorry!

**Comment by khouloudbelguith** [comment] 2021-07-30 11:55
@hejmi, great news!
Thanks so it is not a core issue.
I'm closing the issue, feel free to create a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2021-07-30 11:55 UTC
Labels: Bug, FO, Discounts, Carriers, Cart rules, No change required, Checkout, 1.7.7.5
