### ISSUE TITLE
Prestashop 1.7.4.3 - Product combinations not loading 

### ISSUE THREAD

**Issue by bartes1987** [PrestaShop/PrestaShop#12257] opened 2019-01-22 10:53 UTC
Sometimes when I enter any product with combinations in back office the combinations aren't loading. When it happens in console I got error 500 (below is the screenshot). If the combinations won't load I can't save the product (screen 2). Sometimes the combinations load all right, the problem is not happening every time.    

![screen1](https://user-images.githubusercontent.com/31964938/51530899-4706a680-1e3c-11e9-8181-c058ea6aea78.png)
![screen2](https://user-images.githubusercontent.com/31964938/51530900-479f3d00-1e3c-11e9-86c2-6b3c86a2b684.png)

PrestaShop version: 1.7.4.3
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-01-22 10:56
Hi @bartes1987,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by bartes1987** [comment] 2019-01-22 11:10
![screen3](https://user-images.githubusercontent.com/31964938/51531584-263f5080-1e3e-11e9-84bd-b973f3754719.png)

[CMD_SHOW_LOG.txt](https://github.com/PrestaShop/PrestaShop/files/2782470/CMD_SHOW_LOG.txt)

**Comment by khouloudbelguith** [comment] 2019-01-22 11:17
@bartes1987, I think that the file attached, it a server log, you have some issue permissions  `[ACL] Access to context [/] is denied!`.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong. If you don't have it, you should ask your hosting provider.
THanks!

**Comment by bartes1987** [comment] 2019-01-22 11:53
In debug mode in some cases I have two kind of error pages when entering product edit but it seems like it doesn't depend on the fact if the combinations loaded or not. Sometimes combinations aren't loaded but there are no error in debug mode. 
[debug.pdf](https://github.com/PrestaShop/PrestaShop/files/2782621/debug.pdf)
[debug1.pdf](https://github.com/PrestaShop/PrestaShop/files/2782622/debug1.pdf)

**Comment by khouloudbelguith** [comment] 2019-01-22 13:16
@bartes1987, probably the problem is that you have only a handful connection allowed and when your class tries to get a new connection you have this error.

This is not a programming problem, just the quantity of resources available. And any other script that uses this class is subject to have the error.

You have to configure more connections on MySQL config file on the server. If you don't have this access, ask the support to do it or change for a hosting company with more connections allowed!
Thanks to check with your host & feedback.

**Comment by bartes1987** [comment] 2019-01-22 17:57
Is it possible that the problem with loading combinations was caused by the gamification module? I noticed that sometimes some of the errors in console referred to that module (like on the screenshots below). I turned that module off and I haven't encountered the problem till now.  
![gamification](https://user-images.githubusercontent.com/31964938/51555257-86061d80-1e77-11e9-930b-4cf5d85e8d11.jpg)
![gamification2](https://user-images.githubusercontent.com/31964938/51555258-86061d80-1e77-11e9-8afa-ec68288616de.jpg)

**Comment by khouloudbelguith** [comment] 2019-01-23 09:26
Hi @bartes1987,

What is the exact version of the gamification module did you use?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-22 07:42
Hi @bartes1987,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-02-22 07:42 UTC
Labels: Bug, Combinations, No change required, 1.7.4.3

**Comment by peskajan** [comment] 2020-12-11 19:49
I have the same issue in 1.7.3.1 - I create a simple combination (two) for a product and everything works in the shop, but when I go to that product again combinations are not loaded and I get 500 in the console
![image](https://user-images.githubusercontent.com/3920837/101948300-137cc300-3bf2-11eb-976a-e316bdf567a3.png)

Here is my setup info:
![image](https://user-images.githubusercontent.com/3920837/101948442-5048ba00-3bf2-11eb-9617-4db20c49b0b5.png)

**Comment by peskajan** [comment] 2020-12-11 19:54
As I was not able to open this issue, I created a new one - https://github.com/PrestaShop/PrestaShop/issues/22381
