### ISSUE TITLE
[BO] [Orders] Adding order with new customer impossible - error

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20895] opened 2020-09-08 12:54 UTC
#### Describe the bug

In the BO, I add a new order with a new customer, after I created the customer, I choose the new customer to initiate new order but I get an error

#### Expected behavior

Being able to initiate order in the BO with new customer

#### Steps to Reproduce

1. Go to orders
2. Click on new order and create a new customer
3. After creating the customer, add a new order

**Screenshots**

https://drive.google.com/file/d/1mJ6W8ZsvCg4mWgS48inh2yYtQdryzPSu/view

![Capture d’écran 2020-09-08 à 14 55 29](https://user-images.githubusercontent.com/69145330/92479059-5a1de400-f1e3-11ea-9fb4-dfa36dbfcc11.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-09-08 13:27
Hi @ngodefroy,

This issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/20643
I think it will be fixed when 177x is merged into develop.
https://github.com/PrestaShop/PrestaShop/pull/20898
Ping @atomiix what do you think?

Thanks!

**Comment by atomiix** [comment] 2020-09-09 08:23
@khouloudbelguith I you're right, this should be fixed after 177x is merged into develop.

**Comment by khouloudbelguith** [comment] 2020-09-09 08:49
Duplicate of #20643

**Closed as completed by khouloudbelguith** 2020-09-09 08:49 UTC
Labels: Bug, develop, Major, BO, Duplicate, Order, Regression
