### ISSUE TITLE
Deleting an image throw webservice give a HTTP 500 error

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#33503] opened 2023-07-31 10:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When i try to delete an image throw webservice, image is deleted but a php error occurs with a HTTP error 500:

```
Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/prestashop/classes/Image.php:642
Stack trace:
#0 /var/www/prestashop/classes/Image.php(210): ImageCore->deleteImage()
#1 /var/www/prestashop/classes/webservice/WebserviceSpecificManagementImages.php(822): ImageCore->delete()
#2 /var/www/prestashop/classes/webservice/WebserviceSpecificManagementImages.php(625): WebserviceSpecificManagementImagesCore->manageDeclinatedImagesCRUD()
#3 /var/www/prestashop/classes/webservice/WebserviceSpecificManagementImages.php(650): WebserviceSpecificManagementImagesCore->manageEntityDeclinatedImages()
#4 /var/www/prestashop/classes/webservice/WebserviceSpecificManagementImages.php(656): WebserviceSpecificManagementImagesCore->manageDeclinatedImages()
#5 /var/www/prestashop/classes/webservice/WebserviceSpecificManagementImages.php(315): WebserviceSpecificManagementImagesCore->manageProductImages()
#6 /var/www/prestashop/classes/webservice/WebserviceSpecificManagementImages.php(184): WebserviceSpecificManagementI in /var/www/prestashop/classes/Image.php on line 642
```

### Expected behavior

No php error and no http error.
Image still must be deleted.

### Steps to reproduce

1. Add a product with an image
2. Enable webservice, with all rights
3. Do an HTTP DELETE request onto this added image
4. Check HTTP response => you'll see 500
5. Check PHP error log => you'll see the php error ;)

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4 + 8.1

**Comment by Max84** [comment] 2023-07-31 10:05
It seems to be Prestashop 8.1 regression.

**Comment by kpodemski** [comment] 2023-07-31 21:39
Yes, it is. It is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/32897, so I'm closing this issue.

This PR has a possible fix: https://github.com/PrestaShop/PrestaShop/pull/33226, although it requires some more work.

**Closed as completed by kpodemski** 2023-07-31 21:39 UTC
Labels: Bug, Duplicate

**Comment by hibatallahAouadni** [comment] 2023-08-01 06:17
Duplicate of #32897

**Comment by Max84** [comment] 2023-08-01 06:52
I'm sorry, i didn't find this issue 😓
