### ISSUE TITLE
Combination tab disappeared as well as "save" buttons on BO product page

### ISSUE THREAD

**Issue by LSClaire** [PrestaShop/PrestaShop#14511] opened 2019-07-06 02:23 UTC
**Describe the bug**
Prestashop 1.7.5.1 site working for months without troubles. But for a couple of days (not sure exactly when it started) the combination tab in BO product pages doesn't appear anymore, making it impossible to manage the combinations, and the buttons at the bottom of the page (to save, duplicate, cancel, put on or offline, etc...) have disappeared.

**To Reproduce**
I don't know

**Screenshots**
<img width="1060" alt="Capture d’écran 2019-07-06 à 04 16 00" src="https://user-images.githubusercontent.com/43815115/60750211-8ddcf880-9fa5-11e9-95d4-7abbfd74cbbb.png">
<img width="1060" alt="Capture d’écran 2019-07-06 à 04 15 52" src="https://user-images.githubusercontent.com/43815115/60750212-8e758f00-9fa5-11e9-819a-7ff2cb7e0746.png">

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2019-07-08 07:48
Hi @LSClaire,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-07 07:48
Hi @LSClaire,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

THanks!

**Closed as completed by khouloudbelguith** 2019-08-07 07:48 UTC
Labels: Bug, BO, Combinations, No change required, 1.7.5.1
