### ISSUE TITLE
add page selector and number of products to display on the stocks page

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23201] opened 2021-02-10 01:01 UTC
#### Is your feature request related to a problem?

it is very difficult to increase the stocks in group if you have several product pages

#### Describe the solution you'd like

be able to view all the products in order to edit all the stock at the same time

#### Additional context

![image](https://user-images.githubusercontent.com/62474824/107449821-8a77fe80-6b44-11eb-9aeb-3a4a0a9ac8a3.png)
![image](https://user-images.githubusercontent.com/62474824/107449655-3bca6480-6b44-11eb-9e32-f3d6ebaa69c1.png)

**Comment by hibatallahAouadni** [comment] 2021-02-10 10:04
Hello @alfonsolr09 

So, you're suggesting that we need to change the stocks pagination like the products pagination is that so?
If so, could you please check this issue #12381 cause it seems similar to yours.

Thanks!

**Comment by alfonsolr09** [comment] 2021-02-13 01:08
yes, same "problem"

**Comment by hibatallahAouadni** [comment] 2021-02-15 22:23
Hello @alfonsolr09 

Thanks for your feedback!
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12381. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-15 22:23
Duplicate of #12381

**Closed as completed by hibatallahAouadni** 2021-02-15 22:23 UTC
Labels: Improvement, BO, Duplicate, Stocks
