### ISSUE TITLE
Can't save product with multiple combinations on every tab

### ISSUE THREAD

**Issue by idzczakp** [PrestaShop/PrestaShop#18648] opened 2020-04-15 14:45 UTC
Prestashop 1.7.6.3
PHP Version: 7.3.15 
Memory Limit: 512M 
Maximum execution time: 180 
Max upload file size: 128M 

Hey. 
I have issue with product page. I read few bugs reported here and nothing looks like mine issue - at least It wasn't solved.

I have store with a lot of products and every products has about 200 combinations.
On beginning, when I added first products it was easy, everything was saved perfectly but after few products it became slow and sometimes it was impossible to save product.

I don't add every product separately or generate every combination. I have few empty products with template of description and generated combinations, because it's just faster and I couldn't generate those combinations because of issues.

Now when I click save, loading animation on bottom bar keeps rolling and do nothing, after few minutes I get error in upper right corner "Can't save settings".
Some time ago in this cases I used Online/Offline switch to save product but now it's not working.

Error appears on product page, no matter if I'm working on description, SEO tab or combinations. In most cases I just can't save my product.

**What did I try to solve issue?**

- Clear cache
- Clear cache manually inside var folder
- Change PHP settings
- Even turned off cache

And nothing...

Only thing i saw in console was this after I get Can't save settings error message:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON dataform.js:703:23
    error https://storename.pl/3myvtn7zxkj9arez/themes/default/js/bundle/product/form.js?1.7.6.3:703
    u https://storename.pl/3myvtn7zxkj9arez/themes/new-theme/public/main.bundle.js:253
    fireWith https://storename.pl/3myvtn7zxkj9arez/themes/new-theme/public/main.bundle.js:253
    n https://storename.pl/3myvtn7zxkj9arez/themes/new-theme/public/main.bundle.js:253
    t https://storename.pl/3myvtn7zxkj9arez/themes/new-theme/public/main.bundle.js:253
```

**Comment by marionf** [comment] 2020-04-15 14:59
Hello @idzczakp Your issue is a duplicate of #9809
Please follow and comment on this issue

**Comment by marionf** [comment] 2020-04-15 14:59
Duplicate of #9809

**Closed as completed by marionf** 2020-04-15 14:59 UTC
Labels: Duplicate
