### ISSUE TITLE
statsorigin module doesn't show data

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#17587] opened 2020-02-10 15:05 UTC
Hi
I've seen that the statsorigin module on 8 websites works only on one website, the others it is not present any data in the order pages (below there is an image of the website where it works well)
on prestashop 1.6.x it worked well always, now just in one site

can you check on some sites that you can get the accesses?
thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/74161058-a9387200-4c1e-11ea-9c45-f752870ffc28.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2
Module version: 2.0.2

**Comment by khouloudbelguith** [comment] 2020-02-10 16:23
Hi @maofree,

Thanks for your report.
Sorry but we don't need the access, we must first try to reproduce your issue.

The screenshot provided is from the BO => stats page?

Thanks!

**Comment by Maofree** [comment] 2020-02-10 16:29
hi
the above image is from an order page, instead below it is from the statistic page
![2](https://user-images.githubusercontent.com/653230/74168832-9f1c7080-4c2a-11ea-9757-7aa584e7ec78.png)

instead from the other websites there are no data
![3](https://user-images.githubusercontent.com/653230/74168972-d68b1d00-4c2a-11ea-9c69-b22103c17825.png)

**Comment by khouloudbelguith** [comment] 2020-02-10 16:36
@maofree, in my case, I did not manage to reproduce the issue with PS1.7.6.3 & PS1.7.6.2 and the `statsorigin` module 2.0.2.
![image](https://user-images.githubusercontent.com/16067358/74169559-c9baf900-4c2b-11ea-83fc-cde9ca9ddb89.png)
![image](https://user-images.githubusercontent.com/16067358/74169567-ccb5e980-4c2b-11ea-9a6e-03d93e7af3b6.png)
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Maofree** [comment] 2020-02-12 09:57
hi
I think in that log there are any informations about this module, it is installed on 10 sites and only in 1 it works, that module has a table in DB and it adds info from customers and then put them in that table. That website has the same theme, modules and php and prestashop's version of the others,
I can give you the access of one site to understand why it does not load the information into the database. The problem is not the absence of the graph but the absence of data in its table

**Comment by khouloudbelguith** [comment] 2020-02-12 11:25
@maofree, thanks for your feedback.

>I can give you the access of one site to understand why it does not load the information into the database.

I will invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

But in my case, I need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Thanks!

**Comment by Maofree** [comment] 2020-02-12 11:42
trust me all those data are not necessary
to check why this module on the 1.7 has problem it is necessary to stay in front of the site and check if the module log the sources. The module has little code
check on other websites not in your demo site

**Comment by khouloudbelguith** [comment] 2020-02-12 11:59
@maofree, I tried with three different servers & it is OK
I attached a screen record
https://drive.google.com/file/d/1yWcbMzbTUSattoKZv0DFPHAgldD6jcfK/view

Thanks to check & feedback.

**Comment by Maofree** [comment] 2020-02-12 12:55
can you see inside any real websites?

**Comment by khouloudbelguith** [comment] 2020-02-12 13:17
@maofree, you can check with this shop also

BO: https://unable-waste.machine-shuffle.prestashop.net/admin-dev
`email=demo@prestashop.com `& `password=prestashop_demo`

tHANKS!

**Comment by Maofree** [comment] 2020-02-12 14:12
also this one is not a real website
however when I find some time I'll check by myself
the module is simple, it must only to check the sources and add them in the db, so which kind of php code or javascript errors should I need to see in a log?
those websites are on different hostings
I thought it was easier to verify

**Comment by khouloudbelguith** [comment] 2020-02-12 14:25
@maofree, you should have PHP errors in the logs, for example, fatal errors or critical errors.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-16 08:13
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-16 08:13 UTC
Labels: Bug, BO, Stats, No change required, 1.7.6.2
