### ISSUE TITLE
Exported translations are not working properly

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#26549] opened 2021-11-08 11:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you export translations for the custom theme, and the language different than English, in International -> Translations translations are exported with mixed English and custom language. This is because of some core translations like Shop.Theme.Global, etc., are being exported in English, and only custom translations are in Polish.

### Expected behavior

When we export, let's say, French translations for a custom theme, all translations should be in French. Default ones (from the default catalog that were not modified) and custom ones.

The translations to export should be loaded and overridden in this order (the last one being the one that "wins" if it exists):

1. default catalogue (untranslated)
2. core xlf (translated)
3. database translation (no theme)
4. theme xlf (translated)
5. database translation (theme)

### Steps to reproduce

1. You need to have at least two languages.
2. You need to have a custom theme installed. It could even be a duplicate of the classic with a different name.
3. Now export translations for your theme and for the language different than English
4. Open the downloaded package, and see that in the package, you have `.xlf` files with English translations instead of translations in your exported language.

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by florine2623** [comment] 2021-11-09 16:34
Hello @kpodemski ,

I was able to reproduce the issue with PrestaShop versions 1.7.7.7 and 1.7.8.0, so I can confirm that this behavior is indeed a bug.

The translation export is in French, but in the file the content is in English :
<img width="676" alt="Screenshot 2021-11-09 at 17 28 22" src="https://user-images.githubusercontent.com/16019289/140964638-efbd5cc6-d3a7-4fbd-8f87-4f3c8e6ea4e2.png">
[ShopFormsHelp.fr-FR.xlf.zip](https://github.com/PrestaShop/PrestaShop/files/7506467/ShopFormsHelp.fr-FR.xlf.zip)

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by eternoendless** [comment] 2021-11-10 09:28
A little more context from the discussion on slack:

> this is probably due to the fact that you can specify different translations for core wordings when in the theme’s context, but [the spec](https://build.prestashop.com/prestashop-specs/1.7/back-office/international/translations/translations.html#front-office-translations) doesn’t clearly state that the core translations should be loaded if the theme doesn’t have xlf files.
>
> by order of preference, this would be:
> 1. database translation (theme)
> 2. theme xlf (translated)
> 3. database translation (no theme)
> 4. core xlf (translated)
> 5. default catalogue (untranslated)

The spec might need to be updated accordingly

**Closed as completed** 2022-08-02 08:12 UTC
Labels: Bug, Minor, CO, Theme & logo, Translations, Fixed, PR available, Verified
