### ISSUE TITLE
BO - Bad display In some modals

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27266] opened 2022-01-07 15:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO, we have a bad display of some modals
![image](https://user-images.githubusercontent.com/16067358/148561349-ac61f5d3-990b-41f4-a352-b850da10e62e.png)
**1782** => ok
![image](https://user-images.githubusercontent.com/16067358/148561404-4c866151-edff-4d8e-8a56-f76f860ba0cf.png)

I found this issue in different pages
1. Go to BO > Orders > Add new Order 
2. Click Add new customer
3. See error

----------------------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Details for Carts & Orders
![image](https://user-images.githubusercontent.com/16067358/148562219-c2134a66-44a0-4034-afa2-8cac628ebb3d.png)

---------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Add new customer

-------------------------
1. Go to BO > Orders > View an old order
2. EDit the shipping address & the invoice address
3. See error
 

### Steps to reproduce

I found this issue in different pages
1. Go to BO > Orders > Add new Order 
2. Click Add new customer
3. See error

----------------------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Details for Carts & Orders
![image](https://user-images.githubusercontent.com/16067358/148562219-c2134a66-44a0-4034-afa2-8cac628ebb3d.png)

---------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Add new customer

-------------------------
1. Go to BO > Orders > View an old order
2. EDit the shipping address & the invoice address
3. See error
 

### PrestaShop version(s) where the bug happened

1.7.8.3build1

### PHP version(s) where the bug happened
7.2

**Comment by NeOMakinG** [comment] 2022-01-07 15:11
Probably due to the header calculation removed...

**Comment by Hlavtox** [comment] 2022-01-07 16:11
@NeOMakinG Easiest would be to not render these 4 divs at all. Aaaand I missed that useless row/col in my cleaning.
![Výstřižek](https://user-images.githubusercontent.com/6097524/148572189-c60ddcc1-1b13-4e25-b0a5-e88ffa5d078b.JPG)

**Comment by hibatallahAouadni** [comment] 2022-01-11 21:37
@khouloudbelguith the first issue is duplicate of #27058

**Comment by Progi1984** [comment] 2022-01-28 20:48
Fixed by @NeOMakinG in #27296 & tested by @hibatallahAouadni

**Closed as completed by Progi1984** 2022-01-28 20:48 UTC
Labels: Bug, Minor, BO, Regression, Fixed, Front-end, PR available, 1.7.8.x, Verified
