### ISSUE TITLE
MultiShop product list v2 bugs

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#29709] opened 2022-09-20 15:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

These issues have been identified while testing this PR https://github.com/PrestaShop/PrestaShop/pull/29039
Since 8.0 doesn't include full multishop support for the new product page they ill be handled separately during the 8.1 development phase

**Issue1**
I followed this spec: https://build.prestashop.com/prestashop-specs/1.7/back-office/catalog/products/listing-v2.html#multistore

If the product row has more than one shop in the Store(s) column, the preview button `should not be displayed` in `All shops / Groups shops`
![image](https://user-images.githubusercontent.com/16067358/180035851-4957124e-bc6c-41d0-b2cc-4883e35c0bf9.png)
![image](https://user-images.githubusercontent.com/16067358/180036085-0a0a9687-4906-4610-81ed-342529015448.png)

### Expected behavior

To be defined with @MatShir I think this could be improved with the refacto of the product list in multishop (li,e having a preview button for each shop when the multishop panel is opened)

Also when the list is in single shop context, I think we could keep this button

### Steps to reproduce

1. Install a multishop 
2. Go to product page v2
3. Select All shops, or Group shop
4. The preview button is still visible in the list, it should be removed in the global row (we can't know which shop to show in this case)
5. Go to single shop context, I can preview a product and it is previewed in the context of the shop I selected in the BO

### PrestaShop version(s) where the bug happened

8.0.0 and 8.1.0

**Comment by sallemiines** [comment] 2022-09-20 16:40
Hello @jolelievre 

I can't reproduce your issue with **PS8.0.x**, see the attached screen record below



https://user-images.githubusercontent.com/31663369/191315664-a593994f-e7f4-48b9-af2e-db8144eaed59.mp4

Please check & feedback.
Thank you !

**Comment by hibatallahAouadni** [comment] 2022-10-10 17:41
Hello @jolelievre & @khouloudbelguith 

I didn't manage to reproduce the issue with PS80x neither with develop :disappointed: 
Closing the issue as it seems to be invalid :sweat_smile: 

Thanks!

**Comment by jolelievre** [comment] 2022-10-25 19:40
This issue as reproduced by @khouloudbelguith (see this comment https://github.com/PrestaShop/PrestaShop/pull/29039#pullrequestreview-1155166168)

So I don't think the issue should be closed yet, especially since we didn't start working on the product list in multishop (a PR is WIP) so this feature isn't handled yet and the specs need to be redefined anyway because the UX has changed.

The preview action was only added in this PR for now #29039 that's why you can't reproduce it on 8.0.x or develop for the moment. But it contains a bug in multishop that will be fixed in 8.1 hence the need of this issue.

**Comment by AureRita** [comment] 2022-11-03 13:48
Because this issue isn't present currently and will come when the PR will be released, I put it in blocked until we validate the issue

**Comment by MatShir** [comment] 2022-12-29 16:04
Duplicate of #29986

**Closed as completed by MatShir** 2022-12-29 16:04 UTC
Labels: Bug, 8.0.x, BO, Duplicate, Multistore, Invalid
