### ISSUE TITLE
Can't create new product

### ISSUE THREAD

**Issue by consochris** [PrestaShop/PrestaShop#11790] opened 2018-12-17 12:02 UTC
**Describe the bug**
I cannot create a new product, i can duplicate products but when on Catalog > Products and clicking the button "+ New product" nothing happens.

![2018-12-17_13-01-40](https://user-images.githubusercontent.com/11958854/50085962-f0ce9400-01fb-11e9-92e1-0357c8b335f8.png)
**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2018-12-17 12:51
Hi @consochris,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by consochris** [comment] 2018-12-17 16:55
OVH
Linux Php7.1

**Comment by khouloudbelguith** [comment] 2018-12-17 16:56
@consochris, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

**Comment by consochris** [comment] 2018-12-17 17:07
Host: OVH
Server: Linux 
[prod.log](https://github.com/PrestaShop/PrestaShop/files/2687070/prod.log)

**Comment by consochris** [comment] 2018-12-18 08:01
![2018-12-18_09-01-13](https://user-images.githubusercontent.com/11958854/50139982-8a9d4c00-02a3-11e9-9fab-71c34ab07dce.png)
it shows this error in the console

**Comment by khouloudbelguith** [comment] 2018-12-18 09:47
Hi @consochris,

For the errors in the console, it is a different issue, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10684 to fix the issue, it is fixed in the last version PS1.7.5.0.
In your file, prod.log I found that you are adding an attachment with a title more than 32 chars, could you please check & feedback, it could be a problem.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-29 16:05
Hi @consochris,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-29 16:05 UTC
Labels: Bug, BO, No change required
