### ISSUE TITLE
Adding both texture and hex color to attribute does not work

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#12504] opened 2019-02-08 07:49 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Catalog -> Attribute'
2. Add an tribute type of "Color or texture"
3. Add hex value, save
4. Go back to list, edit this attribute, try to add texture image
5. failure

as you would see, this does not work, it's regression when it comes to comparison between 1.6 and 1.7, you need to remove hex color in order to add a texture

i think that it should work like in 1.6, just add an information that in default theme texture will have higher priority

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: N/A

**Comment by dennispw** [comment] 2019-02-08 08:02
Related https://github.com/PrestaShop/PrestaShop/issues/10596

**Comment by khouloudbelguith** [comment] 2019-02-08 08:21
Hi @kpodemski,

It is the same issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/10596#issuecomment-425130337?
is it?
Thanks!

**Comment by kpodemski** [comment] 2019-02-08 08:54
Hi @khouloudbelguith 

seems like this is a same issue, but it's definitely not an improvement, it's regression from 1.6 and below

**Comment by khouloudbelguith** [comment] 2019-02-08 09:36
@kpodemski, If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Your ticket is a duplicate of #10596
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-08 09:36
Duplicate of #10596

**Closed as completed by khouloudbelguith** 2019-02-08 09:36 UTC
Labels: Duplicate, Attributes
