### ISSUE TITLE
Failed Upgrade from 8.0.4 to 8.1.1

### ISSUE THREAD

**Issue by DaniellaMonet** [PrestaShop/PrestaShop#33985] opened 2023-09-19 22:59 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

- Updating from fresh 8.0.4 install to 8.1.1
- Rollback is impossible in mid field and gives a permanent error 500 without possibility to come back.
- Hosted website (OVH)
- The Installation is under a subdomain
- Using a theme other than prestashop default theme
- Using latest version of autoupgrade module 4.16.4
- php 7.4
-------------------------
[INTERNAL] /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php line 54 - Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "api_private_key". #0 /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #1 /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true) #2 /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true) #3 /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #4 /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #5 /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #6 /home/daniellawebsite/dan/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #7 /home/daniellawebsite/dan/app/AppKernel.php(96): Symfony\Component\HttpKernel\Kernel->boot() #8 /home/daniellawebsite/dan/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #9 /home/daniellawebsite/dan/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(45): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /home/daniellawebsite/dan/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(88): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #11 /home/daniellawebsite/dan/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /home/daniellawebsite/dan/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade() #13 /home/daniellawebsite/dan/Pharmashop/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #14 {main}

### Expected behavior

There should be no errors at the end of the update.

### Steps to reproduce

Simple upgrade like any shop using 1 click upgrade module

### PrestaShop version(s) where the bug happened

8.0.4 to 8.1.1

### PHP version(s) where the bug happened

7.4

**Comment by matks** [comment] 2023-09-20 07:51
Looks similar to https://github.com/PrestaShop/PrestaShop/issues/33504

**Comment by DaniellaMonet** [comment] 2023-09-20 10:37
> Looks similar to #33504 

@matks 
My question, if i leave this new upgrade with these errors, there will be no problem in future? because the store seems to work without problems but I'm afraid if I let it.

**Comment by matks** [comment] 2023-09-21 07:42
I think it's safer to rollback to the snapshot that was created at the beginning of your upgrade process

**Comment by DaniellaMonet** [comment] 2023-09-21 08:07
@matks 
> I think it's safer to rollback to the snapshot that was created at the beginning of your upgrade process

Thank you  , the problem was resolved by one from your community it's similar to #33504 witch you mentioned , so  it's a bug on 8.0.4 in itself , not in 8.1.x , thanks to all community.

**Comment by xga91** [comment] 2023-09-21 13:09
What was the solution to fix it ?

**Comment by aniszr** [comment] 2023-09-21 14:13
Duplicate of [#33504](https://github.com/PrestaShop/PrestaShop/issues/33504)

**Closed as not planned by aniszr** 2023-09-21 14:13 UTC
Labels: Bug, Duplicate, Autoupgrade, Invalid, 8.0.4

**Comment by DaniellaMonet** [comment] 2023-09-22 17:09
@aniszr It's not a duplicate of #33504 it's similar but not identical.
