### ISSUE TITLE
The Category description goes under the category cover

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12797] opened 2019-03-05 14:33 UTC
**Describe the bug**
The Category description goes under the category cover

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Category in Catalog
2. Edit on Category
3. Write more than 108 characters in the Description field

**Proposed solution**
Resized the description field depending of image size.

**Screenshots**
![image](https://user-images.githubusercontent.com/43613217/53812312-80faba80-3f5b-11e9-9688-aab3733e319d.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-03-05 14:58
Hi @MatShir,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11495 to fix the issue.
It is fixed in the PS1.7.6.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-05 14:59
Duplicate of #9979

**Closed as completed by khouloudbelguith** 2019-03-05 14:59 UTC
Labels: Bug, Trivial, FO, Duplicate, Categories, Front-end
