### ISSUE TITLE
Standard Refund PS Back Office: Quantity available to be refunded doesn't get updated in the UI unlike Partial refund.

### ISSUE THREAD

**Issue by confusedatma9** [PrestaShop/PrestaShop#21193] opened 2020-09-29 03:43 UTC
**Expected behaviour:**
Should have shown as "0/7" quantity available to be refunded under the Standard refund.
But it still shown as "0/10" even after 3 item being already refunded, where in case of Partial refund the behaviour seems right one.

**Standard refund:** In case of Standard refund, after refunding 3 quantity, quantity available to be refunded is "0/10".
<img width="980" alt="Screen Shot 1942-07-07 at 8 46 24 AM" src="https://user-images.githubusercontent.com/71811239/94508792-64eef600-0230-11eb-8a95-39f00637c447.png">

**Partial refund:** In case of Partial refund, after refunding 3 quantity, quantity available to be refunded is "0/7"
<img width="1134" alt="Screen Shot 1942-07-07 at 8 52 45 AM" src="https://user-images.githubusercontent.com/71811239/94509165-476e5c00-0231-11eb-8e07-bb0441d592fa.png">

**Steps to Reproduce:**
Place an order in the back with status payment accepted.
Click **Standard refund** button at the top of order page. It will scroll to the refund section of the order.
Select the checkbox against each item and enter the quantity to be refunded.
Click **Refund products** and refund is successful.
Now,
Click **Standard refund** and we can see the behaviour shown in the first screenshot.
Click **Partial refund** and we can see the behaviour shown in the second screenshot.

**Additional Information:**
PrestaShop version: 1.7.6.7
PHP version: 7.1.33

**Comment by khouloudbelguith** [comment] 2020-09-29 08:10
Hi @confusedatma9,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/94530640-a933c380-023b-11eb-9a22-ddd68d920f86.png)
But it is fixed in the next release 1.7.7.0.
![image](https://user-images.githubusercontent.com/16067358/94530715-c8325580-023b-11eb-92ca-b05fa7ea9de1.png)
https://drive.google.com/file/d/1jq92NsrNE4-I6wUM6GBnaIFHG0AwDAjC/view?usp=sharing
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-09-29 08:10 UTC
Labels: BO, Order, Fixed, 1.7.6.8
