### ISSUE TITLE
When you are in all shop context all categories are not displayed in product page

### ISSUE THREAD

**Issue by sitte** [PrestaShop/PrestaShop#15274] opened 2019-08-27 11:08 UTC
**Describe the bug**
I have multisore, each store has it's own category branch, all stores has the same products.
When editing product in "all shops" context, category assigment block shows categories only from one store. In Prestashop 1.5.4.1 I see all category branches from all shops.

After saving it overrides main category in all shops. 

**To Reproduce**
1. Activate multistore, make 2 stores A and B
2. Make 2 categories CatA and CatB
3. Assign CatA to Store A and Cat B to Store B
4. Ad one product to CatA and CatB
5. Try to edit this product in "all shops context" and check what categories You see.
6. Try to save the product and check what is stored in ps_product_shop.id_category_default for this product

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-27 11:38
Hi @sitte,

Thanks for your report.
Following these steps:
1. Activate multistore, make 2 stores A and B
2. Make 2 categories CatA and CatB
3. Assign CatA to Store A and Cat B to Store B
4. All shops context is selected => Add new product => CatB is not displayed in the list of categories
=> It is not the same behavior as PS1.7.5.2

PS1.7.6.0/PS1.7.6.1:

![image](https://user-images.githubusercontent.com/16067358/63768023-0a65c680-c8c7-11e9-8baf-a7f61df0c35b.png)
PS1.7.5:
![image](https://user-images.githubusercontent.com/16067358/63768089-341eed80-c8c7-11e9-92d2-5af2dac7603b.png)

This is a regression.

>Try to save the product and check what is stored in ps_product_shop.id_category_default for this product

I have the same behavior as PS1.7.5 & PS1.7.6
Because when All shops context is selected => We have only a default category is selected.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by sitte** [comment] 2019-08-27 12:34
I see 2 problems:
1. in "all shops" context we should see all category branches from all stores, not from default store. 
2. in "all shops" context there should be main category per shop not per multistore

I can try to fix 1. Can You point me in direction where are functions that load category structure, it would speed up the process?

I think that 2 needs not only change of loaded data but in addition change of interface - not one radio button but one for each store.

**Comment by khouloudbelguith** [comment] 2019-08-27 12:38
@sitte, we should ask developers: @PrestaShop/prestashop-core-developers

**Comment by matks** [comment] 2019-10-10 13:24
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15621#event-2702690573

**Closed as completed by matks** 2019-10-10 13:24 UTC
Labels: Bug, Minor, BO, Categories, Multistore, Regression, Fixed, 1.7.6.0, 1.7.6.1
