### ISSUE TITLE
Faceted search links to categories lost after upgrade to 3.0.2 

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#13995] opened 2019-05-28 08:39 UTC
Prestashop 1.7.5.2 
Faceted search 3.0.2.

After update Faceted search to V3.0.2., links to categories are lost.

Server error message is below.

After update Faceted search module error warning: could not update module

[Tue May 28 09:49:44.938370 2019] [lsapi:error] [pid 3326002:tid 140427134969600] [client xxx.xxx.xxx.] [host www.derks-wielersport.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Tools' not found in /home/deb111111/domains/derks-wielersport.nl/public_html/classes/db/Db.php:794\nStack trace:\n#0 /home/deb111111/domains/derks-wielersport.nl/public_html/config/alias.php(48): DbCore->escape('configuration', false)\n#1 /home/deb111111/domains/derks-wielersport.nl/public_html/config/alias.php(53): pSQL('configuration')\n#2 /home/deb111111/domains/derks-wielersport.nl/public_html/classes/Configuration.php(155): bqSQL('configuration')\n#3 /home/deb11111/domains/derks-wielersport.nl/public_html/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()\n#4 /home/deb11111/domains/derks-wielersport.nl/public_html/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...')\n#5 /home/deb11111/domains/derks-wielersport.nl/public_html/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()\n#6 [internal function]: PrestaShopAutoload->load('Tools')\n#7 /home/deb111111/domains/derks-wielersport.nl/public_html/config/config.inc.php(85) in /home/deb111111/domains/derks-wielersport.nl/public_html/classes/db/Db.php on line 794\n, referer: https://www.derks-wielersport.nl/cccccccccc/index.php/improve/modules/updates?_token=F8FRzyqL0UI9ipo_3_CFcwQzMMSWEJyzXbBZkQZEmEs

**Comment by khouloudbelguith** [comment] 2019-05-28 08:45
Hi @Peter4661,

After the upgrade of the ps_facetedsearch module, could please try to follow these steps:

1. Go to BO => Module Manager page => configure the ps_facetedsearch module
2. Click on `Rebuild entire price index`, `Build attribute index` & `Clear cache`
3. Edit your template => Categories used for this template: you will found that all categories are not selected in your case?

Thanks!

**Comment by Peter4661** [comment] 2019-05-28 11:11
Hi khouloudbelguith,

Thank you for your tips.

Rebuiling the entire price index and build attribute index restored the links to categories. 

However, filters for categories do not show up with all categgiets with filters  .  This is realy wierd. No error warning in server error log.

Visiting and editing filter template, making sure category is selected, rebuilding price index, build attribute index and cleared cache did not solve the problem :(.

**Comment by khouloudbelguith** [comment] 2019-05-28 11:22
@Peter4661, thanks for your feedback.
In the configuration page of the ps_facetedsearch module, the `Show products from subcategories`
 option is enabled?
Thanks!

**Comment by goombaylabs** [comment] 2019-06-07 14:47
Hi

I'm having the same issue as well. None of my categories are working in my front office. I've rebuilt my whole category tree over and still no luck.

The error that I get is:

![image](https://user-images.githubusercontent.com/51277054/59112690-216ccc00-8909-11e9-9e6f-050c5452b700.png)

I tried the suggestions but nothing is working.

**Comment by khouloudbelguith** [comment] 2019-06-10 15:34
Hi @goombaylabs,

In the configuration page of the ps_facetedsearch module, the option `Show products from subcategories` is enabled or not?
Thanks!

**Comment by joaocosta-azores** [comment] 2019-06-28 12:29
Hello,
I've updated my prestashop from 1.5.7.0 to 1.5.7.2 using prestashop module 1-click upgrade.
Upgrade was successful, but faceted search filters not showing up in frontend. 1-click upgrade has updated faceted_search from version 2.1.1 to 3.0.5 and I've already rebuild prices index and attributes and features indexes. Also cleared cache. Faceted is in hook displayLeftColumn as supposed Not getting any error . 
Any suggestion?

<img width="490" alt="Screenshot 2019-06-28 at 12 20 47" src="https://user-images.githubusercontent.com/2188826/60341791-31734b00-999f-11e9-9ab9-260419c37e17.png">

**Comment by joaocosta-azores** [comment] 2019-06-28 12:43
> Hello,
> I've updated my prestashop from 1.5.7.0 to 1.5.7.2 using prestashop module 1-click upgrade.
> Upgrade was successful, but faceted search filters not showing up in frontend. 1-click upgrade has updated faceted_search from version 2.1.1 to 3.0.5 and I've already rebuild prices index and attributes and features indexes. Also cleared cache. Faceted is in hook displayLeftColumn as supposed Not getting any error .
> Any suggestion?
> 
> <img alt="Screenshot 2019-06-28 at 12 20 47" width="490" src="https://user-images.githubusercontent.com/2188826/60341791-31734b00-999f-11e9-9ab9-260419c37e17.png">

After checking again, for some reason, faceted search model was reset. I've checked everything again and now it shows sliders, but not showing dropdowns, check buttons, radio buttons and colors..
<img width="300" alt="Screenshot 2019-06-28 at 12 40 24" src="https://user-images.githubusercontent.com/2188826/60342908-41405e80-99a2-11e9-977f-d1f41b1f2d57.png">

**Comment by khouloudbelguith** [comment] 2019-06-28 13:04
Hi @Peter4661,

Any news about your issue?

Thanks!

**Comment by marionf** [comment] 2019-08-01 08:02
Hello,

Despite our several trials, we could not reproduce your issue with the provided informations.
Since we have no news for more than 30 days, I close this issue.
Feel free to open a new one if needed.

Best regards.

**Closed as completed by marionf** 2019-08-01 08:02 UTC
Labels: BO, Can't reproduce, Faceted search, 1.7.5.2
