### ISSUE TITLE
500 Error while installing back to English and switching admin panel to it via profile

### ISSUE THREAD

**Issue by juslintek** [PrestaShop/PrestaShop#12579] opened 2019-02-14 18:22 UTC
I'm using 1.7.5.0 Prestashop, 
my main language is Lithuanian removed all other, then I decided to switch admin panel back to English because I'm struggling navigating in my native language admin panel, so I've imported locale and bam. Here is what I get in apache error log:

```bash
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\Translation\\Exception\\InvalidResourceException: Invalid resource provided: "1.2"; Errors: [ERROR 1877] Element '{urn:oasis:names:tc:xliff:document:1.2}trans-unit': Duplicate key-sequence ['b6d4223e60986fa4c9af77ee5f7149c5'] in key identity-constraint '{urn:oasis:names:tc:xliff:document:1.2}K_unit_id'. (in /home/user/domains/websites.test/public_html/shop/admin/ - line 241, column 0) in /home/user/domains/websites.test/public_html/shop/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php:200\nStack trace:\n#0 /home/user/domains/websites.test/public_html/shop/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php(60): Symfony\\Component\\Translation\\Loader\\XliffFileLoader->validateSchema('1.2', Object(DOMDocument), '<?xml version="...')\n#1 /home/user/domains/websites.test/public_html/shop/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php(42): Symfony\\C...\n', referer: http://shop.website.test/admin/index.php?controller=AdminEmployees&token=bd94759f0c4e447a2d67bfb629cf8082&id_employee=1&updateemployee
```

To reproduce:
1. Run Debian 7, with php 7.0, apache 2.4 with mod_ruid2 and mod_php and mariadb 10.2.
.htaccess
```
php_value post_max_size 128M
php_value post_max_size 128M
php_value max_input_vars 50000 #for translations

.... rest is auto generated rules
```
2. Install Prestashop 1.7.5.0, enable all default plugins install demo data with products.
3. Import Lithuanian language via International -> Localization
4. Set Lithuanian language as default.
5. Set Admin language as Lithuanian via your profile.
6. Remove English and all other languages, but Lithuanian.
7. Import back English locale.
8. Deactivate English language
9. Set English language in Profile Settings as admin language.

**Comment by juslintek** [comment] 2019-02-14 18:31
Okay sorted this out, forgot to mention that you need to export languages .xlf files to theme translations directory under `themes/themename/translations/lt-LT` subdirectory. Deleted those and it started working. It was probably conflicting. I still do not understand where translations from admin interface are kept. As well some translations are not picked up for some reason.

**Comment by khouloudbelguith** [comment] 2019-02-15 08:22
Hi @juslintek,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1NgI1YzoIq-iaCEzdo58aIzUj8nBp5o-U/view
About the steps that you just make it, those steps are used in the case that you are creating new strings in files that already exist in the default theme as described in the link: http://build.prestashop.com/howtos/translation/how-to-translate-your-theme/#case-2:-you-are-creating-new-strings-in-files-that-already-exist-in-the-default-theme

Since it is fixed, can I close the issue?
Thanks!

**Comment by juslintek** [comment] 2019-02-24 19:24
It because you skilled the comment https://github.com/PrestaShop/PrestaShop/issues/12579#issuecomment-463738706 You need to export languages to themes languages directory as .xlf files then this produces conflict. It allows to handle translations only through database.

**Comment by khouloudbelguith** [comment] 2019-02-25 16:05
@juslintek,

After removing the all other languages, I navigated to International => Translations => Exported the "Lietuvių kalba (Lithuanian)" language for the classic theme & I moved the "lt-LT" folder into /themes/classic/translations, then I imported the "English", I disabled it, I set English language in Profile Settings as admin language => OK 
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-02 07:39
Hi @juslintek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-02 07:39 UTC
Labels: BO, Can't reproduce, International, 1.7.5.0
