### ISSUE TITLE
The server returned a "500 Internal Server Error" after update to 1.7.5.2

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#14250] opened 2019-06-17 13:40 UTC
**Describe the bug**
After updating to 1.7.5.2 The server returned a "500 Internal Server Error" in the BO Modules manager->warnings and upadets

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/50954519/59608673-8781fc00-911e-11e9-9bf1-99a54f944903.png)

![image](https://user-images.githubusercontent.com/50954519/59608726-ab454200-911e-11e9-86f1-c2804b88038c.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 5.6.4

**Comment by khouloudbelguith** [comment] 2019-06-17 13:44
Hi @photinia73,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by photinia73** [comment] 2019-06-17 14:32
And one else. I changed the domain from test.te.com.ua to te.com.ua this is my working domain.
I saw in parent directory strange files with old test.te.com.ua, like .viminfo:
27  0  ~/test.te.com.ua.sveta.legacy/config/defines.inc.php
-'  28  0  ~/test.te.com.ua.sveta.legacy/config/defines.inc.php
-'  71  56  ~/test.te.com.ua.sveta.legacy/config/defines.inc.php
-'  34  4  ~/test.te.com.ua.sveta.legacy/config/defines.inc.php
It seems that some modules end others trying to handle to the old domain. In the BO I made change in the SEO, where write the site URL te.com.ua.
May be it will be better you check my site in the BO and FTP?




Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
• server setup and configuration
• PrestaShop version (source)
• debug mode report
• PHP error logs
• apache error log
• javascript console log
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-17 14:36
@photinia73, Could you please try to regenerate the file .htaccess

1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL

Thanks to check and feedback

**Comment by photinia73** [comment] 2019-06-17 14:48
Done. New .htacces was generated but the error still appear and some modules undefined

**Comment by photinia73** [comment] 2019-06-17 14:49
[error.txt](https://github.com/PrestaShop/PrestaShop/files/3297528/error.txt)

**Comment by khouloudbelguith** [comment] 2019-06-17 14:49
@photinia73, could you please provide me the exact exception displayed when debug mode is enabled.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-17 14:54
@photinia73, 

List of modules causing this issue is:
- ht_fbchat
- ht_scrolltop

Thanks!

**Comment by photinia73** [comment] 2019-06-17 14:56
and others from HT
I cant to restet them or turn on, nothing, they are undefined after changing the domain
Here the debug mode
![image](https://user-images.githubusercontent.com/50954519/59614325-375c6700-9129-11e9-9839-ef982c8a5a2e.png)

**Comment by photinia73** [comment] 2019-06-17 14:56
![image](https://user-images.githubusercontent.com/50954519/59614357-493e0a00-9129-11e9-9334-cb7fb549cd9f.png)

**Comment by khouloudbelguith** [comment] 2019-06-17 14:58
@photinia73, did you tried to re-install them after changing the domain?

Thanks!

**Comment by photinia73** [comment] 2019-06-17 15:00
I did not< becouse in the test.te.com.ua we work for a long time with Hiddentechies to fix all bugs, and now there is a working site, if I reinstal theese modules all will broken

**Comment by khouloudbelguith** [comment] 2019-06-17 15:07
@photinia73, in my case, with your shop `te.com.ua/` domain => it is OK.
I attached a video record 
https://drive.google.com/file/d/1mOkxGaYx6bYRr3dGdo9XIWl5PHXMj8yb/view
Thanks!

**Comment by photinia73** [comment] 2019-06-17 15:16
but this error is still here
![image](https://user-images.githubusercontent.com/50954519/59615925-16e1dc00-912c-11e9-8b6d-4196a695b214.png)

**Comment by photinia73** [comment] 2019-06-17 15:19
All the modules became undefined, even PS

**Comment by khouloudbelguith** [comment] 2019-06-17 15:21
@photinia73, it could be a cache issue.
Because your shop in my browser is well working!
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
try to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks!

**Comment by photinia73** [comment] 2019-06-17 15:25
what do this button? I turned it OFF and some modules start work
![image](https://user-images.githubusercontent.com/50954519/59616504-3af1ed00-912d-11e9-9149-951a4ef5aea4.png)

**Comment by khouloudbelguith** [comment] 2019-06-17 16:07
@photinia73, this button disable all classes & controllers overrides.
If after disabling this button, some module start work, so it is not a PrestaShop core issue & it is compatibility issue of some overrides in your case.

Thanks!

**Comment by photinia73** [comment] 2019-06-17 16:17
very strange, because start to work not only NON PS modules, but such as 
![image](https://user-images.githubusercontent.com/50954519/59620004-75ab5380-9134-11e9-960c-7db1e0385f8f.png)
this is PS modules as I understand....

**Comment by khouloudbelguith** [comment] 2019-06-17 16:19
@photinia73, yes, those modules are provided by PrestaShop.

Thanks!

**Comment by photinia73** [comment] 2019-06-20 09:42
Hello!

Can you check the next problem?

When I updated the faceted search it stoped index prices and the FO not looking good. This problem left after updating PS to 1.7.5.2

Thank you

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: понедельник, 17 июня 2019 г. в 19:19
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] The server returned a "500 InternalServer Error" after update to 1.7.5.2 (#14250)

@photinia73, yes, those modules are provided by PrestaShop.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-20 09:46
@photinia73, this issue is fixed in the release of ps_facetedsearch v3.0.4.
Here's the PR: https://github.com/PrestaShop/ps_facetedsearch/pull/90 to fix the issue.
Thanks to check & feedback.

**Comment by photinia73** [comment] 2019-06-20 17:47
As I understood I have to make changing in the file ps_facetedsearch.php like in the right column below in the picture?



З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: четверг, 20 июня 2019 г. в 12:47
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] The server returned a "500 InternalServer Error" after update to 1.7.5.2 (#14250)

@photinia73, this issue is fixed in the release of ps_facetedsearch v3.0.4.
Here's the PR: PrestaShop/ps_facetedsearch#90 to fix the issue.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-06-21 08:52
@photinia73, you need just to upgrade your module ps_facetedsearch to the latest version 3.0.5, after the upgrade click on:

1. Rebuild entire price index
2. Build attributes and features indexes
3. Clear cache

Thanks to check & feedback.

**Comment by photinia73** [comment] 2019-06-21 14:44
After I returned to the old version I can`t update the module.  The update search find nothing (((

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: пятница, 21 июня 2019 г. в 11:52
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] The server returned a "500 InternalServer Error" after update to 1.7.5.2 (#14250)

@photinia73, you need just to upgrade your module ps_facetedsearch to the latest version 3.0.5, after the upgrade click on:
1. Rebuild entire price index
2. Build attributes and features indexes
3. Clear cache
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-06-21 15:34
@photinia73, In your BO => Advanced Parameters page => the option "Disable all overrides" is enabled or disabled?

Thanks!

**Comment by photinia73** [comment] 2019-06-21 18:08
Below my parameters. If I put it in the tern On the modules stop to work


З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: пятница, 21 июня 2019 г. в 18:34
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] The server returned a "500 InternalServer Error" after update to 1.7.5.2 (#14250)

@photinia73, In your BO => Advanced Parameters page => the option "Disable all overrides" is enabled or disabled?
Thanks!

**Comment by photinia73** [comment] 2019-06-21 18:10
And else my BO find the updates for others modules but not for facetedsearch…. Before this I updated it but there was a problem with index and I rolled back. And now the update is not proposed

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: пятница, 21 июня 2019 г. в 18:34
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] The server returned a "500 InternalServer Error" after update to 1.7.5.2 (#14250)

@photinia73, In your BO => Advanced Parameters page => the option "Disable all overrides" is enabled or disabled?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-24 09:19
Hi @photinia73,

>If I put it in the tern On the modules stop to work

Your issue is not a PrestaShop core, you have some overrides which are not compatible.
About the faceted search module, try to uninstall this previous version & install the latest one from the Catalog module page.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-07-24 07:13
Hi @photinia73,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-24 07:13 UTC
Labels: Bug, BO, No change required, Module manager, 1.7.5.2
