### ISSUE TITLE
[ps_contactinfo]Can't disable the display of the email in FO 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#20294] opened 2020-07-23 09:58 UTC
#### Describe the bug

In the last version of the module ps_contactinfo I can't disable the display of the email address 

#### Steps to Reproduce

1. Go to back office-> modules-> modules manager
2. Click on upgrade and then configure
3. Switch off the option "display email address"
4. Go to FO 
4. See the email is still displayed in the footer and in the contact form page

**Screenshots**

<img width="1280" alt="Capture d’écran 2020-07-23 à 11 54 42" src="https://user-images.githubusercontent.com/3034677/88274272-b8e2d900-ccdb-11ea-8aec-329e2060f25d.png">
<img width="1273" alt="Capture d’écran 2020-07-23 à 11 55 50" src="https://user-images.githubusercontent.com/3034677/88274281-bbddc980-ccdb-11ea-9cd3-68c775198006.png">
<img width="1251" alt="Capture d’écran 2020-07-23 à 11 57 00" src="https://user-images.githubusercontent.com/3034677/88274282-bc766000-ccdb-11ea-8c8a-46b2af9db69a.png">

#### Additional information

Issue with PS1.7.6.7 and ps_contactinfo v3.3.0.
Working with PS1.7.7.0 and ps_contactinfo v3.3.0.

**Comment by marionf** [comment] 2020-07-23 12:37
@sarahdib What is your version of ps_contactinfo ?
It's working with the previous version of the module ?

**Comment by Sinepel** [comment] 2020-07-27 11:27
I have just tested, while updating the module, the module templates in the theme folder are not replaced and therefore do not contain the variable $display_email.

But the template files in the module itself are correct.

**Comment by Sinepel** [comment] 2020-07-27 11:28
TPLs are correct on develop branch

**Comment by khouloudbelguith** [comment] 2020-07-27 14:38
Hi @sarahdib, @marionf,

I did not manage to reproduce the issue with 1.7.7.x branch and the `ps_contactinfo` v3.2.0 & v3.3.0.
I attached a screen record
https://drive.google.com/file/d/1KXv4mOyGIskQJIssdA6PPdYCludKnKOa/view?usp=sharing

Thanks!

**Comment by marionf** [comment] 2020-07-28 08:00
Same for me, I can't reproduce

**Comment by khouloudbelguith** [comment] 2020-08-10 09:11
Hi @sarahdib, @marionf,

This issue is reproduced with PS1.7.6.7. and contactinfo module v3.3.0.
It is ok with Develop branch and 1.7.7.x branch.
I think we should re-open the issue, is it?

Thanks!

**Comment by marionf** [comment] 2020-08-10 09:14
@khouloudbelguith 

Could you check if it's working with ps_contactinfo 3.2.0 and PS 1.7.6.7 ?

**Comment by khouloudbelguith** [comment] 2020-08-10 11:26
@marionf, yes it is ok with PS1.7.6.7 and ps_contactinfo v3.2.0.
https://drive.google.com/file/d/19jF5drZbJ1zK81s6ywGzGalh2fYkcOsp/view?usp=sharing
Thanks!

**Comment by marionf** [comment] 2020-08-10 12:27
Thank you @khouloudbelguith 
So, I reopen this issue, it should be fixed in the next release of the module

**Comment by NeOMakinG** [comment] 2020-10-26 15:34
@marionf it's not linked to the module, it's because on the 1.7.6.x branch the condition is not inside modules tpl.

**Comment by marionf** [comment] 2020-10-26 15:39
As it's not to fix in the module and fixed in 1.7.7, I close the issue

**Closed as completed by marionf** 2020-10-26 15:39 UTC
Labels: Bug, Minor, FO, Regression, Fixed, Front-end, Contactinfo, 1.7.6.7
