### ISSUE TITLE
Bug with CDN, css and js files are not downloaded from the cdn's servers just images

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#17055] opened 2020-01-07 19:06 UTC
Hi
I'm using a new cdn named bunnycdn, all is ok for the images, they are downloaded correctly from their servers, but the css and js compressed files are downloaded from the original server
you can test it from here
https://www.mondialshop.it/

I've tested it already on a demo site with default theme and I get the same issue

can you fix it? 

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/71921224-bd550380-3188-11ea-8c36-74f0ac32760a.png)
![2](https://user-images.githubusercontent.com/653230/71921225-bd550380-3188-11ea-967b-7ca367bcf7ea.png)
![11](https://user-images.githubusercontent.com/653230/71921259-ce9e1000-3188-11ea-9691-aa90f3c82c53.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-01-08 08:14
Hi @maofree,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16180 to fix the issue.
It is fixed in the next version PS1.7.7.0.
Your ticket is a duplicate of #9890
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-01-08 08:14
Duplicate of #9890

**Closed as completed by khouloudbelguith** 2020-01-08 08:14 UTC
Labels: Duplicate

**Comment by Maofree** [comment] 2020-01-08 08:48
ok
thanks
