### ISSUE TITLE
1.7.6 sort by price - low to high white page

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15721] opened 2019-09-26 21:03 UTC
When sorting price from low too high a white page appears with no results.

The problems is caused by FacetedSearch.

By editing this file:  lines 332-336 in modules/ps_facetedsearch/src/Adapter/MySQL.php

Replacing line 332-336 will solve this issue.

) {
            $joinMapping = $filterToTableMapping[$orderField];
            $orderField = $joinMapping['tableAlias'] . '.' . (isset($joinMapping['fieldName']) ? $joinMapping['fieldName'] : $orderField);
            if ($orderField === 'price') {
           $orderField = $this->getOrderDirection() === 'asc' ? 'price_min' : 'price_max';
       }

![Screenshot 2019-09-26 at 22 09 06](https://user-images.githubusercontent.com/46492443/65725338-4b115500-e0aa-11e9-9947-231118493ed6.png)

After changing file, you need to clear browser history and cache from backoffice. 

This fix does not work for multistore. Help is here needed!

**Comment by khouloudbelguith** [comment] 2019-09-30 09:11
Hi @01park,

I did not manage to reproduce the issue with PS1.7.6.1 & ps_facetedesarch v3.3.0.
In the ps_facetedesarch configuration page, could you please try to click on the "Index all missing prices" & "Rebuild entire price index" & "Clear cache" buttons, check & feedback.
https://drive.google.com/file/d/1DjNzmYQaXTAzfkPlpgNfQ1Q7YclBFqNc/view
What is the exact version PrestaShop did you use?
What is the exact version of the module ps_facetedesrach did you use?

Thanks!

**Comment by 01park** [comment] 2019-10-24 12:06
Hi,

I tried this again and read on the forum that more people are having this issue with the multistore. The main store is filtering good, but the others don't. Can you please check this from your side. When filtering from low to high price, no result

**Comment by khouloudbelguith** [comment] 2019-10-24 14:36
@01park, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.1 & ps_facetedsearch v3.4.0.
https://drive.google.com/file/d/1tD2kJXRy3W-pxfvkohTQk4yL9nIbHY4Q/view

Thanks to check the screen record & feedback.

**Comment by khouloudbelguith** [comment] 2019-11-25 07:36
Hi @01park,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-25 07:36 UTC
Labels: Bug, FO, Faceted search, No change required
