### ISSUE TITLE
BO - Create an Order - display the company name while selecting a customer

### ISSUE THREAD

**Issue by jpgilberg** [PrestaShop/PrestaShop#27666] opened 2022-02-14 15:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I am looking to modify the BO New Order search results to show the Company name. This is necessary for a shop with a large number of customers where search results can be numerous. Prestashop 1,7.8 now uses customer.html.twig to display this information. According to the documentation there is no hook available therefore a module can't be created to modify the search results display. I have contacted several developers and they have not been able to provide a solution.
 
![bo-new-order-customer-search](https://user-images.githubusercontent.com/94985719/153895691-abfe52e7-7fff-455b-bdc1-3ac2fc0ce347.jpg)

### Describe the solution you'd like

A hook added to the BO New Order process or an alternate solution to modify the search display results. 

It would also be nice to be able to limit the search to just one customer field. Example search just Company Name, email or last name. Currently a search of "Jones" will result in a list of customers that have "Jones" contained in any of the customer fields (first name, last name, customer name, email address).

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment] 2022-02-14 17:00
Hello @jpgilberg 

This issue is partially duplicate of #23116 (the Customer Group part is already implemented on develop).
So, I'm editing this feature description and title :wink: 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by Hlavtox** [comment] 2022-02-15 07:18
Hello, this was already implemented in https://github.com/PrestaShop/PrestaShop/pull/23889 by @Kaudaj.

@hibatallahAouadni You can close this. :-)

**Comment by hibatallahAouadni** [comment] 2022-02-15 09:03
Hello @Hlavtox 

Thanks for the tip :wink: 
I've been seraching for this issue #22643 and I remember that you created but I couldn't find, so thanks :sweat_smile: 
@jpgilberg this issue is a duplicate of #22643 and it's already implemented in the next major version 8.0.0 :tada: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-02-15 09:03
Duplicate of #22643

**Closed as completed by hibatallahAouadni** 2022-02-15 09:03 UTC
Labels: Feature, BO, Duplicate, Order, Customer, Hook, Invalid

**Comment by jpgilberg** [comment] 2022-02-15 16:12
Hello,

 

After reading the information in link you sent, this featured was added (corrected) in PS 8.0. We look forward to its release.

 

Thank you, 

 



Jack Gilberg

Cell: 419-234-3355

Email: ***@***.***
