### ISSUE TITLE
Discount includes tax and shows up inconsitently in product and in checkout

### ISSUE THREAD

**Issue by kodarco** [PrestaShop/PrestaShop#11226] opened 2018-11-01 16:48 UTC
In the example on the screenshot below, discount is created in amount of $15 tax excl. 
For non-logged in customers the discount on the product listing shows "SAVE $15.90" Why???
Why is discount showing with tax included for non-logged in customers?

Also, when you add item to the shopping cart, the stricken through price shows $50.88 which is a product price with the tax. Why does it show like that when the normal, non-discounted product below shows without tax ($9.00)?

To reproduce this error go to: https://www.poppersbymail.com/test/liquids/13272-pwd-rush-poppers.html and add this item to the shopping cart.

This is for Prestashop 1.7.4.3
![listing](https://user-images.githubusercontent.com/43558067/47866154-4b539280-ddfe-11e8-930d-2de0e926e128.JPG)
![cart](https://user-images.githubusercontent.com/43558067/47866156-4d1d5600-ddfe-11e8-998f-a227d2aae74b.JPG)
![info](https://user-images.githubusercontent.com/43558067/47866160-4e4e8300-ddfe-11e8-9e27-d299b1eb40fc.JPG)

**Comment by khouloudbelguith** [comment] 2018-11-01 17:16
Hi @kodarco,

Thanks to navigate to the BO => Shop Parameters => Customer Settings => Groups Tab => Edit the "Visitor" group and check the Price display method.
It should be "Tax included".
Also, this is an issue fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/11103
Your ticket is a duplicate of #9696
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-01 17:17
Duplicate of #9696

**Closed as completed by khouloudbelguith** 2018-11-01 17:16 UTC
Labels: Duplicate
