### ISSUE TITLE
B2B option is disabled but company field still apparead

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#25748] opened 2021-08-31 03:32 UTC
Hello

I'm using on PS 1.7.7.7 and i disabled the **B2B** option but the company and vat fields still there 

so I need your help please to know if this is normal or it's a bug , so if it's normal the how can I remove those fields from the theme instead removing theme from **Zones géographiques** because i have 40 countries to edit

![image](https://user-images.githubusercontent.com/11594433/131437274-edf74c1b-9022-41c6-82ee-1739d1eeb8b1.png)
![image](https://user-images.githubusercontent.com/11594433/131437304-4c38d319-b7f6-4a7e-bc22-3213cebc89a4.png)

Regards

#### Additional information
Version de PrestaShop : 1.7.7.7
Version de PHP : 7.2.34
Limite de mémoire : 80128M
Temps maximal d'exécution : 72000
Taille max. pour envoi de fichiers : 5G

**Comment by florine2623** [comment] 2021-08-31 08:19
Hello @go-sudo ,

I can't reproduce your issue on PS 1.7.7.7.

When B2B is enabled, I have these 2 fields :
![Screenshot 2021-08-31 at 10 16 11](https://user-images.githubusercontent.com/16019289/131467891-6e6453c4-f243-4d49-b6ab-6902351a0055.png)
![Screenshot 2021-08-31 at 10 16 06](https://user-images.githubusercontent.com/16019289/131467832-70a20908-74cf-4af8-bec5-3c7cb5aec655.png)

Once B2B option is disabled, here's what I have :
![Screenshot 2021-08-31 at 10 18 25](https://user-images.githubusercontent.com/16019289/131467919-d7dfd2fd-9a1d-48b4-a826-811299a26f9b.png)
![Screenshot 2021-08-31 at 10 15 25](https://user-images.githubusercontent.com/16019289/131467880-847bc35e-e2d2-4bdc-8544-476425089ce1.png)

Please make sure you have no overrides on that form.

As I can't reproduce this issue, I'll close it.
Thanks

**Closed as completed by florine2623** 2021-08-31 08:19 UTC
Labels: Can't reproduce

**Comment by go-sudo** [comment] 2021-08-31 10:37
Hello @florine2623 

Im talking about order page when a new client will buy and subscribe 

![image](https://user-images.githubusercontent.com/11594433/131487996-7706ea05-7670-41fc-b7d7-bc5ee9677418.png)

![image](https://user-images.githubusercontent.com/11594433/131488448-55b7945c-2a0c-4c7d-96f2-48d44a28f1e3.png)

Regards
