### ISSUE TITLE
Can't save SEO info; description and title, counters not working

### ISSUE THREAD

**Issue by noguystav** [PrestaShop/PrestaShop#35213] opened 2024-01-30 10:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

While editing a product, I can't save the title and description into the database. It says the title/description is too long. But same title and description has been pulled from the databse and it has been stored there as it is. 

Also no characters-counters are not really counting up or down.

I think this is the new product page.

### Expected behavior

I checked the database specifications for the product description and title. We should be able to save the same data, that was retrieved from the database. No change was made. Even if it is longer than 75/160 characters.

### Steps to reproduce

1. Go to edit a product
2. Gp to SEO tab
3. if your title is below 70 and description is over 160, just increase it some and you see counter don't work and also you can't save the product information. (in my case the title/description is already slighly longer, since it has previously been stored that way).

### PrestaShop version(s) where the bug happened

PrestaShop 8.1.3

**Comment by AureRita** [comment] 2024-01-30 14:29
Hi @noguystav 

Thank you for your report, this issue seems to be like this one : 
#34925

Are you agree with that ? 

Waiting for your feedback

**Comment by florine2623** [comment] 2024-02-12 08:47
As @AureRita said, the issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/34925.
So I'm closing it to avoid clogging the backlog.

**Closed as completed by florine2623** 2024-02-12 08:47 UTC
Labels: Bug, BO, Duplicate, SEO & URLs, 8.1.x, Products Page
