### ISSUE TITLE
Combination change in prices is not refreshing in frontoffice..

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#19875] opened 2020-06-19 16:44 UTC
Hi there..

After i created a new product today that had a color/size combination i noticed that when choosing / changing combination in frontoffice the price is not refreshing. Despite that if i add to cart the price in cart is the right one.

When turning on debug i get the following..
-------------------------------------------------

(1/1)                                     ContextErrorException                                                                  Notice: Undefined index: medium_default
--
in ab78f8c8f8f941a231f6eb727d07d151a3efcbc2_2.module.productcommentsviewstempl.php line 235
at Block_8708511055edbd170097f81_77173104->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_8708511055edbd170097f81_77173104), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_8708511055edbd170097f81_77173104))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_8708511055edbd170097f81_77173104', 'product_cover')in ab78f8c8f8f941a231f6eb727d07d151a3efcbc2_2.module.productcommentsviewstempl.php line 58
at content_5edbd1700a0f11_86224961(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('module:productcomments/views/templates/hook/post-comment-modal.tpl', null, null, null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('module:productcomments/views/templates/hook/post-comment-modal.tpl')in productcomments.php line 922
at ProductComments->renderProductCommentModal(object(ProductLazyArray))in productcomments.php line 862
at ProductComments->hookDisplayFooterProduct(array('product' => object(ProductLazyArray), 'category' => object(Category), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 970
at HookCore::coreCallHook(object(ProductComments), 'hookdisplayFooterProduct', array('product' => object(ProductLazyArray), 'category' => object(Category), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 355
at HookCore::callHookOn(object(ProductComments), 'displayFooterProduct', array('product' => object(ProductLazyArray), 'category' => object(Category), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 907
at HookCore::exec('displayFooterProduct', array('product' => object(ProductLazyArray), 'category' => object(Category), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1), null)in smarty.config.inc.php line 167
at smartyHook(array('h' => 'displayFooterProduct', 'product' => object(ProductLazyArray), 'category' => object(Category)), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayFooterProduct', 'product' => object(ProductLazyArray), 'category' => object(Category)), object(SmartyDevTemplate)))in cf62f943982cd873dc7d86165bfbc744b4f6793b_2.file.product.tpl.php line 653
at Block_3390969485edbd16fc3b0b6_16430816->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_3390969485edbd16fc3b0b6_16430816), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_3390969485edbd16fc3b0b6_16430816))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_3390969485edbd16fc3b0b6_16430816', 'product_footer', 0)in cf62f943982cd873dc7d86165bfbc744b4f6793b_2.file.product.tpl.php line 878
at Block_2358257455edbd16fc040e8_28132041->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_2358257455edbd16fc040e8_28132041), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_2358257455edbd16fc040e8_28132041), object(Block_20504562455edbd16fc4d0a4_25797048))in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_20504562455edbd16fc4d0a4_25797048))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_20504562455edbd16fc4d0a4_25797048', 'content', 1)in 5c9d5bed5f9ab45ff6c0743a3875d3d2274bc9ad_2.file.layout-full-width.tpl.php line 101
at Block_5087366865edbd16fc4c4d6_45400904->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_5087366865edbd16fc4c4d6_45400904), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_5087366865edbd16fc4c4d6_45400904), object(Block_15605599485edbd16fc5b034_26406081))in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_15605599485edbd16fc5b034_26406081))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_15605599485edbd16fc5b034_26406081', 'content_wrapper')in 52b98f6938e9a20bdf490b7c70ffd5c99b5e3595_2.file.layout-both-columns.tpl.php line 104
at content_5edbd16fc62062_50778480(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 116
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in 5c9d5bed5f9ab45ff6c0743a3875d3d2274bc9ad_2.file.layout-full-width.tpl.php line 42
at content_5edbd16fc4e047_25611657(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 116
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in cf62f943982cd873dc7d86165bfbc744b4f6793b_2.file.product.tpl.php line 54
at content_5edbd16fc3dcf2_78321766(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent('catalog/product.tpl')in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 312
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28
-------------------------------------------------------

**Comment by PierreRambaud** [comment] 2020-06-22 08:43
Hello @Stampa-Stampa , 

Since the provided information isn't sufficient to reproduce the issue, we are closing it. Feel free to open a new one with all the requested information. 

Thank you

**Closed as completed by PierreRambaud** 2020-06-22 08:43 UTC
