### ISSUE TITLE
Position of module - hooks - can't unhook

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#13371] opened 2019-04-11 16:09 UTC
Hooks sometimes? are broken and can't be unhook. After unhook for the first reload of page it's correctly gone but after second reload its coming back.

**To Reproduce**
1. Go to  position and unhook module like featured products from homepage
3. Reload homepage - hook is gone
4. Reload homepage again - featured products come back

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1 

I've tried to removing it from theme.yml (from theme files), module hooks itself (php files) and removing cache from BO and manualy - nothing helped.

Correlative issue reported here: https://www.prestashop.com/forums/topic/652917-cant-unhook-reviews-module/
Solved by reinstallation of theme.
Correlative topic on github: https://github.com/PrestaShop/PrestaShop/issues/12933

**Comment by khouloudbelguith** [comment] 2019-04-12 08:48
Hi @slupostrupek,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1S2XeAQmVrv-hrPZdqlT3NWld2b5HyAOB/view

Did you use the template by default of Prestashop?

**Comment by slupostrupek** [comment] 2019-04-14 20:23
was build on default of prestashop, but i don't think thats related issue.
index.tpl
`
{extends file='page.tpl'}
    {block name='page_content_container'}
      <section id="content" class="page-home">
        {block name='page_content_top'}{/block}
        {block name='page_content'}
          {block name='hook_home'}
            {$HOOK_HOME nofilter}
          {/block}
        {/block}
      </section>
    {/block}
`

**Comment by khouloudbelguith** [comment] 2019-04-15 10:50
Hi @slupostrupek,

Did you use the template by default of Prestashop?

Thanks!

**Comment by jf-viguier** [comment] 2019-05-10 09:58
I've found something that could explain this in Google Analytics module, issue here :
https://github.com/PrestaShop/ps_googleanalytics/issues/33

**Comment by khouloudbelguith** [comment] 2019-05-10 10:48
Hi @jf-viguier,

Thanks a lot for your feedback.
Yes, after installing the ps_googleanalytics module v3.1.3.
In the position page, when I try to unhook the ps_featuredproducts module from the displayHome hook => it doesn't work=> if I reload the home page=> the hook remains . reproduced with PS1.7.5.2 & PS1.7.5.1
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by jf-viguier** [comment] 2019-05-10 12:47
I can't fix it because I really don't know why this code is there, you should ask the author ?

**Comment by leemyongpakvn** [comment] 2022-07-02 02:00
@hibatallahAouadni It looks like this issue has been solved by https://github.com/PrestaShop/ps_googleanalytics/pull/73 since ps_googleanalytics v4.1.0

**Comment by HanaRebaiQA** [comment] 2022-07-07 09:39
Hello @leemyongpakvn 

I checked this issue using `ps_googleanalytics v4.1.2` module on PS1786 and 8.0.x, it's fixed.

**PS1786** : :heavy_check_mark: 


https://user-images.githubusercontent.com/92912932/177743160-7455e0ca-9ec2-4589-a9e4-e0bdc2fc2f25.mp4


**8.0.x** : :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/177743217-0d2d8538-56cf-42f1-992c-bf11e1688cd6.mp4

So, i'll close this issue as it's fixed.


Thank You!

**Closed as completed by HanaRebaiQA** 2022-07-07 09:39 UTC
Labels: Bug, Minor, FO, Design, Positions, Fixed, Google Analytics, 1.7.5.2, Module
