### ISSUE TITLE
Category Product Page Not Responsive -- Front Office

### ISSUE THREAD

**Issue by diksha-cedcoss** [PrestaShop/PrestaShop#25377] opened 2021-07-19 14:59 UTC
#### Describe the bug

I have raised the issue previously : [https://github.com/PrestaShop/PrestaShop/issues/25132](url)

#### Expected behavior

As in previous versions, it displays the category name along with its description & then products in 2 rows with less space in between

#### Steps to Reproduce

1. Go to the 'PS 1.7.8 shop/website'
2. Click on 'Inspect' to enable mobile view
3. Set it to 'Surface Duo' at 100% fit
4. Scroll down to 'Product Lists'
5. See error

**Screenshots**

I have added expected behavior as in PS1.7.7.5 so it should work in new version as well

![prestashop_fo_category_page](https://user-images.githubusercontent.com/40261082/126181098-c0d45065-794c-4bd3-baba-5a1a5e7065e9.png)

![prestashop_1775_fo_category_product](https://user-images.githubusercontent.com/40261082/126181032-19be9086-da68-4ad1-9056-783375d76c7c.png)

#### Additional information

* PrestaShop version: 1.7.8.0 beta version
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-07-19 16:03
Hello @diksha-cedcoss 

Thanks for reporting the issue!
I reproduce the issue with PS1780 but we need to check if this is the expected behavior or not.

Ping @PrestaShop/ux-team wdyt? Is it a regression or the expected behavior?

Thanks!

**Comment by diksha-cedcoss** [comment] 2021-07-20 04:23
Hello @hibatallahAouadni & @PrestaShop/ux-team

It is the expected behaviour, above screenshot shared is from PS 1774

Let me know if any further information needed

Thanks

**Comment by prestascott** [comment] 2021-07-20 15:00
Hello everyone,

Thanks @diksha-cedcoss for your request!

Yes, the expected behaviour is to have at least 2 products in a row on mobile devices.

Here was my design proposition:

![Category page - clothes (1)](https://user-images.githubusercontent.com/54888056/126347068-f256c919-a30f-47c1-a33a-a3fd37fafba5.png)

Wdyt?

**Comment by hibatallahAouadni** [comment] 2021-08-09 07:26
Hello @diksha-cedcoss 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-09 07:26 UTC
Labels: Bug, UX ✔️, FO, No change required, Front-end, Responsive, 1.7.8.0
