### ISSUE TITLE
Shipping part empty in BO when the order contains a virtual product

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#13782] opened 2019-05-14 10:51 UTC
**Describe the bug**
I created two Carriers and set them to Free Shipping.
Carrier 1
Carrier 2

When I create a manual order, I choose Carrier 2 in "Delivery option" of Shipping part.

After created, in the order page, the wrong carrier is selected, Carrier 1.
If I want "Edit shipping details", the carrier list is empty.

I already check zone/country selected for the carrier.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-14 11:12
Hi @BenTen,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.beta1.
Steps to reproduce the issue:
1. In the BO => Orders page => I created order from the BO with a **virtual product** => I selected any carrier
2. The Shipping block is empty

![image](https://user-images.githubusercontent.com/16067358/57693594-80f4f600-7641-11e9-9aa0-23a46bc2529f.png)
https://drive.google.com/file/d/1Xd50E_pZ15eCeJELvSKznLmXalfayfbP/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2019-05-27 14:17
@khouloudbelguith I can't reproduce this issue with 1.7.6.x branch

https://drive.google.com/file/d/1-B9GOxlRkTZ1zxH1oyjwgJ4sGHBmKfSS/view?usp=sharing

**Comment by khouloudbelguith** [comment] 2019-05-27 15:01
Hi @marionf,

I manage to reproduce this issue with PS1.7.5.2 / PS1.7.6.0 / 1.7.6.x when we add to the order a virtual product.

Thanks!

**Comment by marionf** [comment] 2019-05-27 15:23
It's the same issue when you have a carrier not free and it happens only if the order contains virtual products, I updated your comment @khouloudbelguith

**Comment by BenTen** [comment] 2019-05-27 21:42
@marionf In your video, we can see there is the carrier but if you try to click on "Edit" button to add a tracking number, do you have carrier list?

Btw, You didn't activate "Free Shipping" option when you create your order.

**Comment by marionf** [comment] 2019-05-28 07:23
@BenTen it's not necessary to activate free shipping to reproduce the issue
Once the order is created, there isn't the edit button as there is no carrier displayed

![capture d'écran_1607](https://user-images.githubusercontent.com/13449658/58458669-12786380-812a-11e9-8194-dbd5c2b43ff3.png)

**Comment by BenTen** [comment] 2019-05-28 07:34
In virtual it seems there is no button.

But with normal product, the button is displayed.
If we click on "Edit" button to write a tracking number we can't select carrier.

![deb480fbec49a22e4d5f2df26d03a99d.png](https://tof.cx/images/2019/05/28/deb480fbec49a22e4d5f2df26d03a99d.png)

PS 1.7.5.0

**Comment by khouloudbelguith** [comment] 2019-05-28 08:10
Hi @BenTen,

This is a different issue & in my case, it is OK
![image](https://user-images.githubusercontent.com/16067358/58461770-58ccc300-8128-11e9-911a-773c12bfb620.png)

Thanks!

**Comment by marionf** [comment] 2020-01-16 09:28
@khouloudbelguith Could you check if it's fixed with the migrated page on 1.7.7.x branch ?

**Comment by khouloudbelguith** [comment] 2020-01-16 10:20
Hi @marionf,

It is OK with PS1.7.7.x
![image](https://user-images.githubusercontent.com/16067358/72516521-193b1e80-3852-11ea-8b1c-dff770c78244.png)
Since it is fixed, I will close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-16 10:20 UTC
Labels: Bug, Minor, BO, Order, Virtual, Fixed, 1.7.5.0, 1.7.5.2, 1.7.6.0

**Comment by marionf** [comment] 2020-01-16 10:54
Thank you @khouloudbelguith !
