### ISSUE TITLE
Back office: catalog is empty

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#27499] opened 2022-01-27 18:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

Since today, the catalogue is no longer displayed with the products. However, I still see my products on the front of my site.
And you can also see that in my screen, there is the total of my products.

![image](https://user-images.githubusercontent.com/25744417/151424147-8d511fbc-6ea4-49c3-a874-4ac20ad340b4.png)

Can you help me please ?

Thanks

### Steps to reproduce

1. Go to catalog

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.2

**Comment by khouloudbelguith** [comment] 2022-01-28 14:22
Hi @ShaimyWinda,

I did not manage to reproduce the issue with PS1783 & PS1778.
![image](https://user-images.githubusercontent.com/16067358/151563014-70e22b6d-550d-4169-b66c-333bec055859.png)
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ShaimyWinda** [comment] 2022-01-28 19:31
Hello @khouloudbelguith

I tested my concerns by putting the debug mode on and I see a 500 error on the page. 
I looked at the PHP logs and I see this:
```
[28-Jan-2022 20:29:26 Europe/Paris] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 180224 bytes) in /data/www/gti/gti-moondream/ps17/vendor/twig/twig/src/Profiler/Profile.php on line 163
[28-Jan-2022 20:29:26 Europe/Paris] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 52021592 bytes) in Unknown on line 0
```

**Comment by ShaimyWinda** [comment] 2022-01-31 19:29
Hello @khouloudbelguith,

I tried again with the debug mode, and I see this error.
Do you have any idea how to fix this?
Thanks 

![image](https://user-images.githubusercontent.com/25744417/151859620-85aac851-9889-42e9-828d-4441c1c5e0ff.png)

**Comment by HanaRebaiQA** [comment] 2022-02-04 11:48
Hello @ShaimyWinda 

I tried with PS1777, but i was not able to reproduce your issue with debug mode on and off !
Could you please provide us more informations about your shop configuration ?

https://user-images.githubusercontent.com/92912932/152524030-83017f84-afda-44dd-a1f3-622aa2f5f3f6.mp4


Thank you!

**Comment by hibatallahAouadni** [comment] 2022-02-23 09:38
Hello @ShaimyWinda 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-02-23 09:38 UTC
Labels: Bug, BO, Catalog, Multistore, 1.7.7.2, Invalid
