### ISSUE TITLE
HTML tags visible in the order-conf email

### ISSUE THREAD

**Issue by benbine** [PrestaShop/PrestaShop#23028] opened 2021-01-27 21:22 UTC
Hello,

#### Describe the bug

On my 1.7.7.1 shop when someone orders products with customization the order_conf email includes html tags that can bee seen by the customer.
I installed a fresh version of prestashop and reproduced the issue.

#### Expected behavior

No html tags are visible by the customer

#### Steps to Reproduce

Order a product with customization (for example the  Customizable mug that comes with the prestashop installation) 
Open the order confirmation email
There is tags in the product column

**Screenshots**

![image](https://user-images.githubusercontent.com/78113193/106055684-02c6d480-60ee-11eb-97f9-1b2f219c78e3.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-28 10:11
Hello @benbine 

I didn't manage to reproduce your issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1UiJ92up-B07-29gXZ42qjwAGrEY7ahLE/view

Invoice sent by mail:

![image](https://user-images.githubusercontent.com/23308427/106123503-49521880-615a-11eb-8a07-44c58ecd8db0.png)

Please check and feedback.
Thanks!

**Comment by benbine** [comment] 2021-01-28 10:19
Hello,
Can you look inside the email your did received for that order (order confirmed) ? I have the problem in the body of the email and not in the invoice.
Regards

**Comment by khouloudbelguith** [comment] 2021-01-28 10:25
Hi @benbine,
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #22330
To be informed when it's fixed, please subscribe to the issue mentioned above.

So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-01-28 10:25
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22330

**Closed as completed by khouloudbelguith** 2021-01-28 10:25 UTC
Labels: Bug, FO, Duplicate, Order, Invoices, Product customization, 1.7.7.1
