### ISSUE TITLE
[Violation] Permissions policy violation: Synchronous requests are disabled by permissions policy.

### ISSUE THREAD

**Issue by fos016** [PrestaShop/PrestaShop#35770] opened 2024-03-28 11:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Javascript async calls still executing in admin area

https://www.w3.org/TR/permissions-policy/

For example  carrier_wizard.js,

Giving this error

![image](https://github.com/PrestaShop/PrestaShop/assets/10567881/665b5bbb-4afd-4007-9e51-c25b5a6e6fae)

This is solved by changing async: false to async:true

### Steps to reproduce

Version 123.0.6312.86 (Official Build) (arm64)
Version 123.0.6312.86 (Official Build) (arm64)
Create new carrier
Select next

### PrestaShop version(s) where the bug happened

1.7.8

**Comment by AureRita** [comment] 2024-03-28 14:50
Hi @fos016 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(159).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/cdb4b863-2bd6-44fa-a866-eba1078fe9bd)

FYI : We have to test our new issue on the last release (8.1.x) 

Did I miss something on the steps to reproduce ? 

Waiting for feedback

**Comment by fos016** [comment] 2024-03-28 14:57
Could you try it in Chrome? 
Version 123.0.6312.86 (Official Build) (arm64)

**Comment by florine2623** [comment] 2024-04-04 14:53
Hello @fos016 ,

Please clear your cache and try again.

The issue is fixed, there's more infirmation here : https://github.com/PrestaShop/PrestaShop/issues/12577

So I will close the issue.

**Closed as completed by florine2623** 2024-04-04 14:53 UTC
Labels: Bug, BO, Carriers, 8.1.x
