### ISSUE TITLE
Action buttons in Modules Manager rows disappear when permissions are modified

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16338] opened 2019-11-08 17:16 UTC
**Describe the bug**
The actions buttons in the rows on the Module Manager page disappear if the permissions of the page are disabled, then enabled.
It is normal they disappear when a user only has the view permission, but they should be visible again when other permissions are re-enabled.

The user can only use the bulk actions dropdown to act on modules.

**To Reproduce**
1. Go to Module Manager > Module, see the button on each module row, on the right side of each row (configure + dropdown)
2. Go to Permissions, uncheck add, edit, delete permissions for Module Manager > Modules  
3. Go back to Modules Manager > Modules, see buttons are not visible anymore
4. Go back to permission and re-enable all permissions for the page
5. Go to Module Manager > Modules, buttons are not visible

**video**

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-11-11 09:07
Hi @samuel-pires,

The buttons will be displayed if the Modules permissions are checked
![image](https://user-images.githubusercontent.com/16067358/68574763-eac45000-046a-11ea-8e07-af487154e5aa.png)
There is is a conflict.
Your ticket is a duplicate of #9786
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-11 09:07
Duplicate of #9786

**Closed as completed by khouloudbelguith** 2019-11-11 09:07 UTC
Labels: Duplicate, Permissions
