### ISSUE TITLE
Issues with Add to Cart, Checkout, Payment Preferences, Symfony Update & Translation

### ISSUE THREAD

**Issue by Prometheus19** [PrestaShop/PrestaShop#15907] opened 2019-10-11 03:56 UTC
Hello,
I am new user of PrestaShop software for its eCommerce application. Very recently, I have encountered some issues after installing and configuration store setup with it. 

I am using PrestaShop v. 1.7.5.2 with its Classic (default) theme for the shop. The store was fully functional and many of its features were enabled for this store. The display of products, add to cart, checkout, and delivery options were working seamlessly until early part of this week (~10-9-19)  when I checked its various features for operational integrity. 

Three major issues are occurring right now:
1) The add to cart function works, but no products are visibly added to the cart, the checkout icon works, but there is no form for customer checkout, no payment options, and cart is empty with no products being added despite the add button on products working with confirmation page;

2) For payment preferences, the store was using PayPal standard and Braintree payments. There was major update to PayPal and Braintree modules (~9-1-19), when I tried to update them with uninstalling the older versions, I am unable to remove them completely and receive error messages;

3) The store is receiving errors of translation messages in AdminAdvparametersFeature and couple of User Deprecated errors in AdminMarketing and "sensio_framework-extra.router.annotations" and stating to use Symfony\Component\Routing\Annotation\Router

Further technical information can be provided upon review and any help to resolve these issues would be great. See attached JPG files (8)

![Prstshp_Inquiry(1)](https://user-images.githubusercontent.com/56378345/66623319-b41bc100-ebb0-11e9-888f-155ac40455a4.JPG)
![Prstshp_Inquiry(2)](https://user-images.githubusercontent.com/56378345/66623322-b847de80-ebb0-11e9-92e2-8ac485e71da1.JPG)
![Prstshp_Inquiry(3)](https://user-images.githubusercontent.com/56378345/66623329-bed65600-ebb0-11e9-8807-65ce289844c3.JPG)
![Prstshp_Inquiry(4)](https://user-images.githubusercontent.com/56378345/66623341-ce559f00-ebb0-11e9-847e-b4d623e0fc8a.JPG)
![Prstshp_Inquiry(5)](https://user-images.githubusercontent.com/56378345/66623344-d1e92600-ebb0-11e9-8422-02ec0e05ecb3.JPG)
![Prstshp_Inquiry(6)](https://user-images.githubusercontent.com/56378345/66623349-d57cad00-ebb0-11e9-8036-db7ddbd1f716.JPG)

![PrestaShop_Inquiry(1)](https://user-images.githubusercontent.com/56378345/66623302-a403e180-ebb0-11e9-8617-6cb8848b462e.JPG)
![PrestaShop_Inquiry(2)](https://user-images.githubusercontent.com/56378345/66623314-ac5c1c80-ebb0-11e9-97f7-cd410a36c320.JPG)

**Comment by khouloudbelguith** [comment] 2019-10-11 07:54
Hi @Prometheus19,

You have issues with two modules: the PayPal module & the AmzPayments modules.
![image](https://user-images.githubusercontent.com/16067358/66634152-bca1e500-ec0c-11e9-86bf-123b6302991c.png)
![image](https://user-images.githubusercontent.com/16067358/66634181-cdeaf180-ec0c-11e9-96bb-5c3155e0ff4c.png)
They are not provided by Prestashop, we can't do anything with this. 
You should contact the module's author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback

**Comment by Prometheus19** [comment] 2019-10-11 15:52
Hello khouloudbelguith,
Thank you for your follow up and input. 
Sure, some of PrestaShop modules (like payment modules) are subject to modules' developers or authors. However, the installation and configuration of payment modules fall within purview of how they are handled via core elements of PrestaShop's operating system. Not only are PayPal and Amazon payments subject to Internal Server Error (500 error), but other payment processing also have same issues. See additional JPG files attached herein. Also, as you may know PayPal module (standard PayPal) is PrestaShop's product. See list of payment modules @ PrestaShop_Inquiry(5)

As you can see from attached data, various coding issues are detected in core PrestaShop within its classes/module/Module.php, classes/Payment/Module.php, ControllerCore, DispatcherCore, AdminModulesControllerCore.php See attached JPG file of Internal Server Error for Skrill payment processor @ PrestaShop_Inquiry(4)

![PrestaShop_Inquiry(3)](https://user-images.githubusercontent.com/56378345/66664626-7b143880-ec12-11e9-9505-d7eaf72dc8cd.JPG)
![PrestaShop_Inquiry(4)](https://user-images.githubusercontent.com/56378345/66664645-87989100-ec12-11e9-98ae-85d7c70b1677.JPG)
![PrestaShop_Inquiry(5)](https://user-images.githubusercontent.com/56378345/66664658-8c5d4500-ec12-11e9-9cc9-09ec5644a6ce.JPG)

Hence, some coding errors or execution of scripts within core PrestaShop can lead to above issues. 
How to fix them is requested. 
Thanks.

**Comment by khouloudbelguith** [comment] 2019-10-11 16:01
@Prometheus19, but those exceptions are related to those modules
![image](https://user-images.githubusercontent.com/16067358/66666380-c4837880-ec50-11e9-97e2-b5d0cd913973.png)
The class ViaBill is provided by the module
The class Krill is provided by the module also
![image](https://user-images.githubusercontent.com/16067358/66666426-e3820a80-ec50-11e9-9c04-13cd99043438.png)

No, the PayPal module is not provided by PrestaShop core, it is provided by a partner of PrestaShop.
You contact the module author via this link
https://addons.prestashop.com/en/contact-us?id_product=1748

Thanks!

**Comment by Prometheus19** [comment] 2019-10-11 21:29
@khouloudbelguith 
Well, many modules or addons may not part of core, but the actions of "adding product to cart, viewing contents of cart, (with added products or items), guest or account checkout page, payment options (once enabled), and confirmation of order" are part of PrestaShop's core functions, right? After all, it is eCommerce software to setup online store right out-of-the-box. 

None of these functions are currently working on properly installed and configured PrestaShop v.1.7.5.2. They were working just fine until last week. Not sure what sort of software glitches have occurred. I have checked my server settings and webhosting environment, and they are correctly working so the Internal Server Errors (500 errors) are not due to such issues. 

I checked the PayPal module in root directories for the URL and have included PayPal.php file that shows PrestaShop as its author. See PayPal module directory and its contents of folders and files for this directory from @PayPal(1-4) and actual code of PayPal.php @PayPal.php (1-3). 

Nonetheless, PrestaShop has final responsibility over its core software, modules, extensions, and addons since they must meet certain standards, coding parameters, work together, and be reliable and not get broken down once store or shop is configured per its installations. 

![PayPal(1)](https://user-images.githubusercontent.com/56378345/66685962-892e7d00-ec43-11e9-8280-468f7f90b9c1.JPG)
![PayPal(2)](https://user-images.githubusercontent.com/56378345/66685970-8d5a9a80-ec43-11e9-94cf-7a7a0e1de032.JPG)
![PayPal(3)](https://user-images.githubusercontent.com/56378345/66685976-90ee2180-ec43-11e9-93ad-01353c21b20d.JPG)
![PayPal(4)](https://user-images.githubusercontent.com/56378345/66685987-95b2d580-ec43-11e9-8182-c1f4da70cc78.JPG)
![PayPal php(1)](https://user-images.githubusercontent.com/56378345/66685990-9b102000-ec43-11e9-851a-f434df5c0e7f.JPG)
![PayPal php(2)](https://user-images.githubusercontent.com/56378345/66685993-9ea3a700-ec43-11e9-8d37-d652518b35b5.JPG)
![PayPal php(3)](https://user-images.githubusercontent.com/56378345/66685997-a2372e00-ec43-11e9-8ab6-dbb397c6b35d.JPG)

**Comment by matks** [comment] 2019-10-14 10:06
> @khouloudbelguith
> Well, many modules or addons may not part of core, but the actions of "adding product to cart, viewing contents of cart, (with added products or items), guest or account checkout page, payment options (once enabled), and confirmation of order" are part of PrestaShop's core functions, right? 

Hi, indeed if the behavior or code fort this core action has some weaknesses, this falls into the scope of the Core and can be fixed.

The line "Attempted to call undefined function uninstallTabs" indicates an issue, I have created a dedicated issue for this: https://github.com/PrestaShop/PrestaShop/issues/15927
However if you check the code, you can see this is only called at line 397 of the file Module.php, and is triggered when **PrestaShop fails to install a module**. So the root cause here is that their was a module which could not be installed, and the error message is a side-effect of that.

> None of these functions are currently working on properly installed and configured PrestaShop v.1.7.5.2. They were working just fine until last week. Not sure what sort of software glitches have occurred. I have checked my server settings and webhosting environment, and they are correctly working so the Internal Server Errors (500 errors) are not due to such issues.

I'm afraid a statement like "it worked fine until last week, now it's broken" is not something accurate enough for us to help you. Something must have happened, and only you can find out. As you said, code was working fine until recently so it seems the code is not the root cause of the problem.

> I checked the PayPal module in root directories for the URL and have included PayPal.php file that shows PrestaShop as its author. See PayPal module directory and its contents of folders and files for this directory from @paypal(1-4) and actual code of PayPal.php @PayPal.php (1-3).

As said by @khouloudbelguith , the PayPal module is developed by a partner of PrestaShop, and consequently errors must be reported to them. We have no control on this module, even if we knew the mistake, it would be useless to talk to us 😄 as we would not be able to patch it. Please contact the module developers.

> Nonetheless, PrestaShop has final responsibility over its core software, modules, extensions, and addons since they must meet certain standards, coding parameters, work together, and be reliable and not get broken down once store or shop is configured per its installations.

No. I'm sorry, PrestaShop has responsibilities that are described in the LICENSE file attached to the project: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/licences/LICENSE.txt . 

This is an opensource project that you can use and install on your server. You can customize the code, install themes and modules, we are not responsible for what usage you do with the server. We add securities, tests, standards, checks to optimize and increase as much as possible quality and reliability of the software but we cannot guarantee the outcome if you use 3rd party software with prestashop.

Also there are thousand of people using Paypal module, so I think if there was an obvious weakness in it, it would have been found a long time ago. So please double-check the issue does not come from your server/shop. We cannot exclude a mistake in Paypal module, but once again it would be strange that nobody noticed it so far ?

**Comment by khouloudbelguith** [comment] 2019-11-12 07:49
Hi @Prometheus19,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-12 07:49 UTC
Labels: Bug, Payment methods, No change required, 1.7.5.2
