### ISSUE TITLE
Partial Refund PS Back Office: Partial refund accepts refund amount more than the ordered amount and also gets reflected in UI.

### ISSUE THREAD

**Issue by confusedatma9** [PrestaShop/PrestaShop#21194] opened 2020-09-29 06:06 UTC
**Describe the bug:**
When we trigger Partial refund in the Back Office it accepts refund amount more than the ordered amount and also gets reflected in the UI as shown in the below screenshot.

<img width="1171" alt="Screen Shot 1942-07-07 at 11 12 57 AM" src="https://user-images.githubusercontent.com/71811239/94519267-e900a800-0247-11eb-8856-75934cffc404.png">

**Expected behaviour:** Should not have accepted refund amount more than the ordered amount and should have thrown some error message like other invalid refund scenario.

**Steps to Reproduce:**
Place an order in the back with status payment accepted.
Click **Partial refund** button at the top of order page. It will scroll to the refund section of the order.
Enter the quantity and the amount more than the ordered quantity and amount.
Click **Partial refund** and we can see the behaviour as shown in the above screenshot.

**Additional Information:**
PrestaShop version: 1.7.6.7
PHP version: 7.1.33

**Comment by khouloudbelguith** [comment] 2020-09-29 08:36
Hi @confusedatma9,

Thanks for your report.
>Enter the **quantity** more than the ordered quantity

I did not manage to reproduce the issue with PS1.7.7.0beta2
![image](https://user-images.githubusercontent.com/16067358/94532558-51e32280-023e-11eb-9be6-9857456afc64.png)
PS: with PS1.7.6.8, I have an exception
![image](https://user-images.githubusercontent.com/16067358/94532806-a2f31680-023e-11eb-8f9e-f5ef418be836.png)
Not reproduced with PS1770beta2.

>Enter the **amount** more than the ordered amount.

PS1768 => reproduced
![image](https://user-images.githubusercontent.com/16067358/94533346-4e9c6680-023f-11eb-80df-16ed5e3bf97f.png)
PS1770beta2 => Not reproduced
I attached a screen record
https://drive.google.com/file/d/1EyjJDtpbUYl8GBZNLU5Wns6ZV6eGF8so/view?usp=sharing
Thanks to check and feedback.

**Comment by confusedatma9** [comment] 2020-09-29 08:48
So for PS1768 do we need to handle this invalid scenario?

**Comment by khouloudbelguith** [comment] 2020-09-29 09:07
@confusedatma9, in fact, since it is not reproduced with PS1.7.7.0beta2, the issue is fixed in the next release.
So that we can close the ticket?

Thanks!

**Comment by confusedatma9** [comment] 2020-09-29 09:39
Could you please explain how to handle this issue for the PS1768 version, when we are utilising this UI for refund service.
I am using **actionOrderSlipAdd** hook and from this hook I didn't find a way to control this scenario.

**Comment by khouloudbelguith** [comment] 2020-09-29 09:47
@confusedatma9, sorry this issue is fixed during **migration**.
There is no PR to fix the issue.
You can wait for the 1770 stable release to make an upgrade.
Or 
You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Can I close the issue?

Thanks!

**Comment by confusedatma9** [comment] 2020-09-29 10:01
Thanks. you can close the issue.

**Closed as completed** 2020-09-29 10:03 UTC
Labels: Bug, BO, Order, Fixed, 1.7.6.7
