### ISSUE TITLE
Delivered status sent with invoice delivery box activated does not add store logo in PDF

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#28055] opened 2022-03-28 20:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I identify in Multistore, when activating the PDF invoice delivery box, when changing to this status in the order, the email arrives with the pdf of the invoice but the invoice does not show the store logo.

![image](https://user-images.githubusercontent.com/12537826/160480422-5ee25030-97fe-4df2-9970-24c1440903f4.png)

![image](https://user-images.githubusercontent.com/12537826/160480477-fbabc8b1-6984-42d2-8251-388b2060a7a8.png)

In the order confirmation state, the invoices are created correctly with the Multi store.

![image](https://user-images.githubusercontent.com/12537826/160480817-ffd526db-78d5-4542-869e-fcc78b1581dc.png)

### Expected behavior

You should send the invoice in PDF with the logo of the corresponding store.

### Steps to reproduce

Activate the box to send invoice on delivery
create order
Change the order to delivered
The email arrives with the PDF but the PDF arrives without the store logo in Multi store.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment] 2022-03-29 09:41
Hello @ocio87,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/22581. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment] 2022-03-29 09:41
Duplicated of https://github.com/PrestaShop/PrestaShop/issues/22581

**Closed as completed by marwachelly** 2022-03-29 09:41 UTC
Labels: Bug, Duplicate, Invalid
