### ISSUE TITLE
Cover image "to illustrate all possibilities" never shown at first with combinations.

### ISSUE THREAD

**Issue by Ybeske** [PrestaShop/PrestaShop#12429] opened 2019-02-04 21:04 UTC
Hi there!

First of all: I'm using version 1.7.5.

Situation: I create a combination product with 6 combinations and - for example - 4 images: the cover image to illustrate all possibilities, the image of combination 1+4, the image of combination 2+5 and the image of combination 3+6. However, the cover image to illustrate all possibilities is never shown...

![2115885513_coverimagemaininfo thumb png 48b6557443924fd3fbf4caaad3babe6a](https://user-images.githubusercontent.com/43880279/52236833-39cfca00-28c8-11e9-97d2-52b49b4fa2f1.png)

All combinations are only linked to the correct image of that combination to improve the interpretation.

![1984060490_combinationswithassociatedimage thumb png c82b12547f4f88a13bcc018e55274b07](https://user-images.githubusercontent.com/43880279/52236836-3d635100-28c8-11e9-899a-98db29db59da.png)

As one of the combinations is (always?) set as the default combination (for example combination 6), the image of combination 6 is always shown in the product list at the front end.

How can I force the cover image of the main information to be shown instead of the default combination image in the product list as a useful trigger to understand all possible combinations?

![311868179_howtoshowcoverimageonresultapage thumb png 26821752ab07f0e6657eb74b14b705e0](https://user-images.githubusercontent.com/43880279/52236876-5a981f80-28c8-11e9-87f7-b63c62343db0.png)

Thanks is advance!

**Comment by khouloudbelguith** [comment] 2019-02-05 07:57
Hi @Ybeske,

For this combination 6, you need to select the cover image in addition to the custom image,
![image](https://user-images.githubusercontent.com/16067358/52259461-18e89280-2923-11e9-9595-604d1f3c5e48.png)
 it is the possibility now to be shown when you navigate to the Fo > product page.
If you think there should be display Product with cover image which is only for reference image of product and once customer select any of attribute then related combination image should be shown and only combination can be allow for order.
We have already added the iprovement issue to our bug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!”
Your ticket is a duplicate of #12241
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-02-05 07:57
Duplicate of #12241

**Closed as completed by khouloudbelguith** 2019-02-05 07:57 UTC
Labels: Duplicate
