### ISSUE TITLE
Upgrade Guzzle to v6

### ISSUE THREAD

**Issue by N-Wouda** [PrestaShop/PrestaShop#10929] opened 2018-10-09 08:30 UTC
**Is your feature request related to a problem? Please describe.**
Mostly development: the current version of Guzzle used (v5) is a bit older, does not yet use Psr-7, and blocks the use of other libraries that rely on v6.

**Describe the solution you'd like**
Upgrade the dependency on Guzzle to use the v6 branch.

**Describe alternatives you've considered**
There is none: conflicting namespaces cannot be resolved in an elegant way.

**Additional context**
I've been attempting to implement an Exact Online module, using [Picqer's Exact API client](https://github.com/picqer/exact-php-client), but I cannot use the latest version due to the incompatible Guzzle versions.

**Comment by khouloudbelguith** [comment] 2018-10-09 08:59
Hi @N-Wouda,

Thanks for your report.
![image](https://user-images.githubusercontent.com/16067358/46658144-4eb67e00-cbb2-11e8-81e0-5747c8f89e50.png)
@eternoendless @PrestaShop/prestashop-core-developers what do you think about his suggestion?
Thanks!

**Comment by matks** [comment] 2018-10-09 11:39
[Upgrade from guzzle 5 to 6](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#50-to-60)

**Comment by matks** [comment] 2018-10-09 11:47
This should be done along an upgrade of [csa/guzzle-bundle](https://packagist.org/packages/csa/guzzle-bundle) however:
- v2.2.2 is compatible php5.6-php7.1
- v3.1.0 is compatible >php7.1

**Comment by Matt75** [comment] 2020-06-09 11:01
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/17351

**Comment by mvorisek** [comment] 2020-08-19 10:13
> 
> 
> This should be done along an upgrade of [csa/guzzle-bundle](https://packagist.org/packages/csa/guzzle-bundle) however:
> 
>     * v2.2.2 is compatible php5.6-php7.1
> 
>     * v3.1.0 is compatible >php7.1

@matks then we are ready, right?

**Comment by PierreRambaud** [comment] 2020-08-19 10:14
I'm closing this because we will not update this dependency.
Kind regards

**Closed as completed by PierreRambaud** 2020-08-19 10:14 UTC
Labels: Improvement, CO

**Comment by mvorisek** [comment] 2020-08-19 10:21
> I'm closing this because we will not update this dependency.

@PierreRambaud please reopen, current Guzzle is EOL and it is not even receiving security updates and we should update asap

**Comment by eternoendless** [comment] 2020-08-19 13:50
Unfortunately updating it will break everything (including circuit breaker and an unknown but probably high number of modules). We can't do this until the next major.

**Comment by mvorisek** [comment] 2020-08-19 19:14
> Unfortunately updating it will break everything (including circuit breaker and an unknown but probably high number of modules). We can't do this until the next major.

When is next major expected? Can we upgrade and polyfill Guzzle 5?

**Comment by eternoendless** [comment] 2020-08-20 10:13
> When is next major expected?

My best guess is 2022 (1.7.9 is due in 2021).

> Can we upgrade and polyfill Guzzle 5?

I don't think it's possible, but if you manage to update Guzzle AND provide a polyfill that manages to maintain existing code working without touching it, I will take my hat off and merge your PR. This of course includes working out the dependency hell, because external dependencies are locked to Guzzle 5.
