### ISSUE TITLE
BO - Multistore - Error when editing a product 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26859] opened 2021-12-03 13:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error when changing the quantity of a product  in case of multistore and when the option all shops is selected.
https://watch.screencastify.com/v/Y99Ysq8WP2pTXiJ8DzzU

### Steps to reproduce

1. Enable Multistore & Create a new shop
1. All shops selected > Go to BO> product> Edit product >quantity
2. Edit the quantity
3. click on save 
4. see error

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2024-01-19 13:02
Hello @marwachelly ,


Tested with the old product page and the new product page: I can't reproduce the issue.
This issue is no longer present on 8.1.x and develop. Now we have to select a shop in particular to change the quantity.

https://github.com/PrestaShop/PrestaShop/assets/16019289/d4dd6768-ff91-4cbd-9ba1-27034d88a40f

I'm closing the issue as it has been fixed ^^
Thanks!

**Closed as completed by florine2623** 2024-01-19 13:02 UTC
Labels: Bug, Major, BO, Needs Specs, Multistore, 1.7.7.8, Verified
