### ISSUE TITLE
Do not send emails from Cyrillic.

### ISSUE THREAD

**Issue by wokcy** [PrestaShop/PrestaShop#11462] opened 2018-11-21 13:49 UTC
**Describe the bug**
Installed the module "ps_emailalerts", indicated the mail in partially Cyrillic "sales@ариза.рф". Then I place an order, after selecting the payment, an error 500 appears. A test message is also not sent to the mail in Cyrillic "sales@ариза.рф". But if you specify the mail completely in Latin, then the checkout and the test message also work.

Error after choosing payment:
Property Mail-> recipient is invalid
at line 954 in file classes / ObjectModel.php

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.20

**Comment by khouloudbelguith** [comment] 2018-11-21 13:54
Hi @wokcy,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9638
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-21 13:54
Duplicate of #9638

**Closed as completed by khouloudbelguith** 2018-11-21 13:54 UTC
Labels: Duplicate
