### ISSUE TITLE
Error 'Price specification not found for currency: ""'  clicking on a customer thread after upgrade PS 1.6 => PS 1.7.6.5

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#20155] opened 2020-07-13 08:21 UTC
Prestashop version: **1.7.6.5**

Whenever clicking on any  customer thread 

controller=AdminCustomerThreads&token=3a936177a1b3025eec314bb412f3213f

getting error 

The same error also occurring when editing a single customer data

**_Price specification not found for currency: ""_**

**#### Expected behavior**

Normally when we click on single thread then that thread will display complete details

#### Steps to Reproduce

1) Go to admin click on left side customer service

2)  open any customer thread.

http://i.imgur.com/dFxHIYS.png

* PrestaShop version: N/A
* PHP version: N/A

**Comment by matks** [comment] 2020-07-13 08:57
Hi !
Your issue seems to be a duplicate of following issues:
- https://github.com/PrestaShop/PrestaShop/issues/19834
- https://github.com/PrestaShop/PrestaShop/issues/18467

Could you try the solutions provided in these 2 issues and tell me if it works for you:

1. check your PHP version matches 1.7.6.5 requirements: php5.6 to php7.2 (so php7.3 is not supported)
2. check whether the customer orders related to the threads you try to open have `id_currency = 1` - the `id_currency` might be empty when orders were created following an unusual process

**Comment by matks** [comment] 2020-07-13 09:17
I cannot reproduce the issue on PS 1.7.6.5 on a standard setup. Waiting for more infos

**Comment by pks891618** [comment] 2020-07-13 09:46
@matks i have updated my earlier version from Prestashop 1,6 to 1.7.6.5

PHP version is  7.2.31-

**Comment by pks891618** [comment] 2020-07-13 09:56
i have change id_currency to my active currency and it works
it works for customer thread but not working when we opening a single customer

**Comment by matks** [comment] 2020-07-13 21:16
> it works for customer thread but not working when we opening a single customer

There must be some data related to customers (orders ? adresses ? profile data ?) that has an empty currency too 🤔

**Comment by matks** [comment] 2020-07-21 21:27
Hi, I think this topic does not need further exchanges ... for now 😄 so I close the issue.

This does not mean this discussion is over 😉 if you find some more infos we might understand what's going on and maybe reopen the issue if we find a way to reproduce your usecase. But "open" issues are "things that we know what need to do / what we need to fix" and this issue does not meet this definition

**Closed as completed by matks** 2020-07-21 21:27 UTC
Labels: 1.7.6.5

**Comment by pks891618** [comment] 2020-07-22 09:48
ok thanks
