### ISSUE TITLE
Impossible to save changes in carriers

### ISSUE THREAD

**Issue by sextoysunivers1964** [PrestaShop/PrestaShop#24621] opened 2021-05-22 13:23 UTC
Hi all,
I hope you can help me with this.
#### Describe the bug

It's impossible to save changes in carriers, every time I try I got this error : 

```
TECHNICAL ERROR:
Details:
Error thrown: [object Object]
Text status: error
```

After reading other post regarding the same issue, I have increased the max_input_var to 70000 but still I have the same error.
However after inspecting it seems that the problem still comes from the controller admin carrier wizard. 

In other post from 2020 there is a solution for that controller for the same problem that seems to be already applied by default in the recent prestashop versions. That's why I'm lost.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to '...'  Transporters
2. Click on '....'  Your transporter
3. Scroll down to '....'  Save changes

**Screenshots**

<img width="900" alt="Capture carrier" src="https://user-images.githubusercontent.com/84627578/119228091-a01c9d00-bb11-11eb-8825-8d9cc5ed41e6.PNG">

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version:  7.3

If you could help with this would be great.

Best regards,
Juan Carlos

**Comment by hibatallahAouadni** [comment] 2021-05-24 09:03
Hello @sextoysunivers1964 

Despite our efforts, we were not able to reproduce your issue with the provided information, see the attached screen record below:

https://drive.google.com/file/d/1CHhmFoHz7HpWDLZObsEQiLNDzn3uQNFD/view

It seems that your issue is not a PrestaShop core bug but most likely a module problem.
We will close this issue.

Thanks!

**Closed by hibatallahAouadni** 2021-05-24 09:03 UTC

**Comment by sextoysunivers1964** [comment] 2021-05-24 09:10
Hello hibatallahAouadni,

Thank you very much for your answer. I will find that module.

Best regards,
Juan Carlos
