### ISSUE TITLE
Contact form does send mail alert to the person who did contact and translations/placeholders not working

### ISSUE THREAD

**Issue by darylstone** [PrestaShop/PrestaShop#16286] opened 2019-11-05 21:48 UTC
**Describe the bug**
If a customer does a request using the contact form, the mail: You have received a new message from contact form (translated from german) is sent to the customer instead to the admin. Besides that if I open the mail, it does display: Hello, {firstname} {lastname}. But on the contact form is not a input field for firstname or lastname if you are not logged in.

**To Reproduce**
1. Go to contact form
2. Fill the form as a guest or logged in 
3. Check mails

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version:1.7.6.1
PHP version: 7.2.24

![contacform](https://user-images.githubusercontent.com/33138271/68249173-85adcc00-001e-11ea-8c9f-42201e6128b0.png)

**Comment by khouloudbelguith** [comment] 2019-11-06 08:06
Hi @darylstone,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13386
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-06 08:06
Duplicate of #13386

**Closed as completed by khouloudbelguith** 2019-11-06 08:06 UTC
Labels: Duplicate
