### ISSUE TITLE
Issue with total tax calculation

### ISSUE THREAD

**Issue by sandra2n** [PrestaShop/PrestaShop#28334] opened 2022-04-26 09:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Round mode: Round up away from zero, when it is half way there (recommended)
Round type: Round on each item

In cart (and then in invoice) the total tax calculation is incorrect. This is what is calculated:
Product price:
Tax excl.: 121.02
Tax incl.: 145.224
Tax : 20%

The customer group has 30% of discount:
Tax excl.: 84.71
Tax incl.: 101.66

The product quantity is 3:
Tax excl.: 254.13
Tax incl.: 304.98

The taxes are then calculated this way:
304.98 - 254.13 = 50.85

But, if we calculated the tax incl. of 254.13 we found 304.956 and so the taxes should be 50.826
![Sans titre](https://user-images.githubusercontent.com/24668239/165264359-b114eca7-19ca-4e63-b940-71a2f1ec2ebd.jpg)

### Expected behavior

The expected behavior is for the total tax calculation to be correct when calculating the total tax incl. from the total tax excl.

### Steps to reproduce

1. Create a product with price tax excl. 121.02, 20% tax and so 145.224 tax incl.
2. Create a 30% discount for the customer group in catalog price Rules
3. Add a quantity of 3 of this product
4. Go to your cart (or check the invoice after ordering)
![product_price](https://user-images.githubusercontent.com/24668239/165268237-91046f5a-7f7a-4d29-8c1d-e4ce45b106b5.jpg)
![discount](https://user-images.githubusercontent.com/24668239/165268253-f19a0d74-6055-4e5f-a35f-3444694f758c.jpg)
![cart](https://user-images.githubusercontent.com/24668239/165268260-4ede8959-a1a7-4879-9a28-04e34550737c.jpg)
![Sans titre](https://user-images.githubusercontent.com/24668239/165268296-65f56534-d1b7-4eb8-b6fa-beabc45e8b4f.jpg)

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment] 2022-04-26 13:54
Hello,

It seems that your issue is the same as https://github.com/PrestaShop/PrestaShop/issues/17161 which is related to https://github.com/PrestaShop/PrestaShop/issues/9779#issuecomment-415125166.
Could you please check?

Thanks,

**Comment by hibatallahAouadni** [comment] 2022-04-27 11:31
Hello @sandra2n 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9779. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-04-27 11:31
Duplicate of #9779

**Closed as completed by hibatallahAouadni** 2022-04-27 11:31 UTC
Labels: Bug, BO, Duplicate, Order, Discounts, Taxes and Prices, Invalid

**Comment by sandra2n** [comment] 2022-04-28 08:39
Ok, thanks

**Comment by sandra2n** [comment] 2022-04-29 10:32
Hi,

I found a sort of solution that works if all products have the same taxes (which is my case here).

In an override of the Cart class I did added:

```
public function getOrderTotal(
        $withTaxes = true,
        $type = Cart::BOTH,
        $products = null,
        $id_carrier = null,
        $use_cache = false,
        bool $keepOrderPrices = false
    ) {
        if (Tax::excludeTaxeOption()) {
            $withTaxes = false;
        }

        if ($withTaxes) {
            $computePrecision = Context::getContext()->getComputingPrecision();
            $amount_tax_excl = parent::getOrderTotal(false, $type, $products, $id_carrier, $use_cache, $keepOrderPrices);

            // filter products
            if (null === $products) {
                $products = $this->getProducts(false, false, null, true, $keepOrderPrices);
            }

            if (isset($products[0]['rate'])) {
                $value = $amount_tax_excl + ($amount_tax_excl * $products[0]['rate'] / 100);
                return Tools::ps_round($value, $computePrecision);
            }
        }

        return parent::getOrderTotal($withTaxes, $type, $products, $id_carrier, $use_cache, $keepOrderPrices);
    }
```
