### ISSUE TITLE
Impossible to change position of products

### ISSUE THREAD

**Issue by tjorgensborg** [PrestaShop/PrestaShop#13949] opened 2019-05-23 17:45 UTC
**Describe the bug**

**Describe the bug**
If you dont enable show products from subcategory products in main category is not show. IF you enable the show products from subcategory is not possible to rearrange products in main category. It take the first products from each subcategory and the secound from each subcategory and so on
 
<img width="477" alt="Skärmavbild 2019-05-23 kl  19 36 56" src="https://user-images.githubusercontent.com/50947207/58274038-45b99c00-7d92-11e9-9446-debca1cef030.png">
<img width="1245" alt="Skärmavbild 2019-05-23 kl  19 36 38" src="https://user-images.githubusercontent.com/50947207/58274040-45b99c00-7d92-11e9-9cf6-6166457ec062.png">
<img width="1173" alt="Skärmavbild 2019-05-23 kl  19 34 11" src="https://user-images.githubusercontent.com/50947207/58274041-46523280-7d92-11e9-8164-3505c0e3e27d.png">
<img width="1264" alt="Skärmavbild 2019-05-23 kl  19 33 09" src="https://user-images.githubusercontent.com/50947207/58274042-46523280-7d92-11e9-9573-eebb82ece31a.png">

**Additionnal information**
Prestashop version 1.7.4.2
PHP version: 7.2
Faceted version 3.X

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-05-24 10:16
Hi @tjorgensborg,

1. If `Show products from subcategories` is disabled 
=> in the FO => products are only shown in the main category
https://drive.google.com/file/d/1QulARfVXfdgLyQV4fbebTa-9lvTcEOiC/view

2. If `Show products from subcategories` is enabled

Reorder product doesn't work.
Yes, I manage to reproduce the issue with PS1.7.6.0beta1 & ps_facetedsearch v3.0.2
Same issue with PS1.7.5.2 & ps_factredseach v3.0.1.
 https://drive.google.com/file/d/1ehFUUmCgDPmDODKSi76NDeBa6VmL-ma0/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

@marionf, @PierreRambaud this issue https://github.com/PrestaShop/PrestaShop/issues/11152 is not fixed.
Thanks!

**Comment by marionf** [comment] 2019-05-24 12:31
@khouloudbelguith 

I can't reproduce the issue, product are correctly reordered even if faceted search & Show products from subcategories are enabled

https://drive.google.com/open?id=1TWribqWgCQPixUdt7aEFWJQoGttaZth-

**Comment by PierreRambaud** [comment] 2019-05-24 12:58
I don't understand what facetedsearch do here? :thinking:

**Comment by khouloudbelguith** [comment] 2019-05-24 13:04
@marionf what is the exact browser did you use? PHP v?
I tried with PS1.7.6.0beta1 & the same issue.
https://drive.google.com/file/d/1X3-o4pUquS5Mod6WCfjYfOrOkkW9bWEK/view
Thanks!

**Comment by Thinkup** [comment] 2019-05-25 19:44
same issue here... follow

**Comment by PierreRambaud** [comment] 2019-05-26 08:09
@khouloudbelguith on google chrome, latest version, php php 7.2 & 7.3, could not reproduce, with or without facetedsearch.

**Comment by Thinkup** [comment] 2019-05-26 08:17
I have the latest version of chrome, prestashop 1.7.5.0 - php 7.2 - facetedsearch 3.0.2
the issues has come after upgrade facetedsearch.

**Comment by tjorgensborg** [comment] 2019-05-26 08:38
Hello,
So there is no confusion about the bug. 
1. If you disable the **Show products from subcategories** you will have "there is no products" even if the are products in the category. This apply on main category and main categories with sub categories. This is even on categories where faceted search is not applied.
<img width="1238" alt="Skärmavbild 2019-05-26 kl  10 24 08" src="https://user-images.githubusercontent.com/50947207/58379166-77a04d80-7fa0-11e9-8f4b-e3b4e365f95d.png">
<img width="935" alt="Skärmavbild 2019-05-26 kl  10 21 02" src="https://user-images.githubusercontent.com/50947207/58379167-7e2ec500-7fa0-11e9-8d0a-afca17ffecdf.png">

2. If you enabled the **Show products from subcategories** you can see products in categories. You can reorder products in a main category without any problem if you dont have any subcategories. So this works.

3. If you enabled the **Show products from subcategories** you can see products in categories. If you have a main and subcategories you see the products and its showing all the products, main+sub. If you try to rearrange the products it take position 1 products from main or subcat then postion 1 from main or sub and then pos 1 from main or sub. Then pos2 from main or sub, post 2 main or sub etc etc.
There is maybe no other way to do this if you want to show all products from subcategories?.

The biggest problem is #1

I have tried faceted search 3.01 and 3.02 and same result. I am using PS 1.7.4.2 and 1.7.5.1 and same result. We are using php 7.2

**Comment by tjorgensborg** [comment] 2019-05-26 08:48
I tried **Show products from subcategories** on version 2.2.1 of faceted search and it seems to work there in the right way. If its disabled I can still see products.

**Comment by PierreRambaud** [comment] 2019-05-27 08:03
@tjorgensborg If you disable `Show products from subcategories` you must be on the subcategory to see your products:
![image](https://user-images.githubusercontent.com/1462701/58404917-910bcd00-8066-11e9-8f7a-e28019778eaa.png)

Or set the main category:
![image](https://user-images.githubusercontent.com/1462701/58404969-ada80500-8066-11e9-81f8-8e7a8d5298fc.png)

![image](https://user-images.githubusercontent.com/1462701/58404984-b39de600-8066-11e9-9f1b-e45fdff54f16.png)


This is how the button works :thinking:

**Comment by khouloudbelguith** [comment] 2019-05-27 08:23
Hi @tjorgensborg,

After a discussion with our developer, the sort of the products has no effect with the ps_factedsearch module.
In fact, if we uninstall the ps_factedsearch module, we are always able to change the order of positions of the products successfully.

So, we can confirm, that there is no relation between re-order products & the ps_factedseach module.

Thanks for your understanding!

**Comment by tjorgensborg** [comment] 2019-05-27 08:44
Hi, @khouloudbelguith and @PierreRambaud 

I think I understand but as It tried to explain in the post above. When I disable the **"****show products from subcategories"** No products are shown, 

When I tried now on a new installation with english and default theme it seems to work as it should.

T

**Comment by khouloudbelguith** [comment] 2019-05-27 10:19
Hi @tjorgensborg,

Thanks for your feedback.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-27 10:19 UTC
Labels: Bug, Minor, BO, Can't reproduce, Faceted search, 1.7.5.2, 1.7.6.0
