### ISSUE TITLE
Google sitemap 4.2 does not work correct with Multistore 1.7.8. - only main language is being created

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#26701] opened 2021-11-22 13:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When upgrading to 4.2 Google sitemap the module only creates a sitemap for the main language. Other languages are being ignored

<img width="1585" alt="Screenshot 2021-11-22 at 13 40 56" src="https://user-images.githubusercontent.com/46492443/142871940-337d313e-e5f3-47a2-8b45-b784669565f3.png">
.

### Expected behavior

That a sitemap is created for every single language per store

<img width="1531" alt="Screenshot 2021-11-22 at 13 43 18" src="https://user-images.githubusercontent.com/46492443/142872024-308abdee-cfba-41cf-a311-feba10fa749d.png">

Second thing I noticed. In version 4.1 ( a working version ) the sitemaps are 4 to 5 times smaller.

### Steps to reproduce

Install google sitemap

Run it 

Run it with a cron job

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

4.2 Google sitemap

**Comment by hibatallahAouadni** [comment] 2021-11-22 13:50
Hello @01park 

Thanks for reporting the issue but you already report it here #20264
And it is already in our debug backlog. This issue is a duplicate of #20264.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-22 13:51
Duplicate of #20264

**Closed as completed by hibatallahAouadni** 2021-11-22 13:50 UTC
Labels: Bug, Duplicate, Invalid

**Comment by 01park** [comment] 2021-11-22 14:18
Hi @hibatallahAouadni 

The reason I reopened this, is because it never got fixed and was already closed.

The problem still remains after 2 years

For Multishop users this is a must to have right.
