### ISSUE TITLE
Wrong subcategories list

### ISSUE THREAD

**Issue by aem34** [PrestaShop/PrestaShop#28376] opened 2022-04-29 09:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The category id 8 have 6 subcategories (10,11,12,13,14,82).

In a module code, when i call : 
$subcategoriesAccessoiresObj = Category::getNestedCategories(8, $id_lang, true, null, true, '', 'ORDER BY c.`position` ASC');
instead of : 
$subcategoriesAccessoiresObj = Category::getNestedCategories(8, $id_lang);

the order of the categories after the sql request results are : 
1,12,13,8,14,82,10 which is correct following the position order.

after the sort loop with the $buff array, what i got in $categories array is:
14,82,10 and the subcategories before the "8" in the sql request results are ignored.

instead one must use:
$subcategoriesAccessoiresObj = Category::getNestedCategories(8, $id_lang, true, null, true, '', 'ORDER BY c.`level_depth` ASC, c.`position` ASC');

is it possible to correct the loop sort algorithm in order please ?

### Expected behavior

When i want to have another sort order for the subcategories,
i just want to have them all.

### Steps to reproduce

1. Create subcategories;
2. reorder them;
3. in a module code, get that list by their main category id in a specific order (position, for example);
4. you don't have them all.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2022-04-29 13:54
Hello @aem34 

Thanks for your report.

Could you please provide us more info about the module used and a screen-record to can clearly reproduce your issue?

Waiting for your feedback.
Thank you!

**Comment by hibatallahAouadni** [comment] 2022-05-19 08:42
Hello @aem34 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-05-19 08:42 UTC
Labels: Bug, Categories, SQL Manager, Invalid, Module
