### ISSUE TITLE
Impossible to affect payment method to a shipping method that have the same name of already configured shipping method

### ISSUE THREAD

**Issue by kermito** [PrestaShop/PrestaShop#20128] opened 2020-07-09 19:03 UTC
#### Describe the bug

It's impossible to affect payment method with new shipping method that has the same name of a previously configured shipping method. So there's no possibility to affect payment method to that new shipping method, and it's impossible to order with it.

#### Expected behavior

This should list 3 lines, one for each shipping method even if they have the same name

#### Steps to Reproduce

1. Update the name of all your shipping method with the same name
2. Create a new shipping method that has the same name
3. Go to "Payment -> Preferences"
4. Scroll down to 'Carrier restrictions '
5. There is only 2 shipping method

![image](https://user-images.githubusercontent.com/6475579/87079594-93a79280-c226-11ea-90ea-4a12008dfbfe.png)
![image](https://user-images.githubusercontent.com/6475579/87079563-84c0e000-c226-11ea-9eea-dcfa7f7dde75.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.30

**Comment by florine2623** [comment] 2020-07-10 07:22
Hi @kermito ,

Here's the PR: #12379 to fix the issue.
It is fixed in the next major release PS 1.7.7.
Your ticket is a duplicate of #16094

So I'll close the issue.

**Closed as completed by florine2623** 2020-07-10 07:22 UTC
Labels: Carriers, No change required
