### ISSUE TITLE
Import Export Arabic Issue

### ISSUE THREAD

**Issue by shift4world** [PrestaShop/PrestaShop#28733] opened 2022-06-12 15:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Prestashop 1.7.8.6 .. Arabic versions
When import products appear as the photo arabic be symbols also when import be symbols

![FB_IMG_1654960801395](https://user-images.githubusercontent.com/77565671/173241292-25048a94-adaf-49fa-b8c2-a2c86edb89cd.jpg)
![FB_IMG_1654960804777](https://user-images.githubusercontent.com/77565671/173241298-9f2d6e02-44c7-492e-8dc2-92d06f4e72dd.jpg)
![FB_IMG_1654960811049](https://user-images.githubusercontent.com/77565671/173241301-8bc06b0e-cc1f-44af-b01d-542c812918ac.jpg)

### Expected behavior

Arabic appears as right symbols

### Steps to reproduce

I don't know I am not developer

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Import and export

**Comment by AureRita** [comment] 2022-06-13 10:15
Hi @shift4world 

Thank you for your issue ! 
Currently, we haven't enought details to reproduce your issue, I see on your second picture that you are showing something that works. 
To help us, can you add on your description some symbols that doesn't works during the exportation ? 
For the "Steps to reproduce" section, it's not related to developers, in this section, write, step by step, what you did to get this result. 

Thanks

**Comment by florine2623** [comment] 2022-07-01 12:32
Hello @shift4world ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

If that's the case, please create another issue with screenshots that are easier to read and as much info as you can.

Thank you

**Closed as completed by florine2623** 2022-07-01 12:32 UTC
Labels: Bug, Minor, BO, Import / Export, Invalid, 1.7.8.6
