### ISSUE TITLE
Can't import multilang feature programmaticaly

### ISSUE THREAD

**Issue by amerigeau** [PrestaShop/PrestaShop#25837] opened 2021-09-09 22:29 UTC
#### Describe the bug

Want to import feature value with multilang using FeatureValue::addFeatureValueImport().
But it creates one feature value per lang instead of one feature value multilang.
Need to create the feature value in one language first, then UPDATE db with sql request.

$color_value => array of feature values
$id_feature => is supposed to be defined before
id_lang 2 is hardcoded before sql request for this example

```
$langs = Language::getLanguages();
$feature_val_name = array();
foreach($langs as $k => $lang){
	$feature_val_name[$k] = $color_value($lang['id_lang']);
}
// $this->debugd($feature_val_name);
foreach($langs as $k => $lang){
	if ($lang['id_lang'] == 1){
		$id_feature_value = (int)FeatureValue::addFeatureValueImport( 
		  $id_feature,
		  $feature_val_name[$k],
		  (int)$id_product,
		  $lang['id_lang'],
		  0 // $custom
		);
	}elseif ($lang['id_lang'] == 2){
		Db::getInstance()->execute('UPDATE `' . _DB_PREFIX_ . 'feature_value_lang` SET `id_feature_value` = ' . $id_feature_value . ',`value` = "' . $feature_val_name[$k] . '",`id_lang` = ' . $lang['id_lang'] . ' WHERE id_feature_value = ' . $id_feature_value . ' AND id_lang = ' . $lang['id_lang']);
	}
}
Product::addFeatureProductImport($id_product, $id_feature, $id_feature_value);
```

#### Expected behavior

Want to import feature value with multilang using FeatureValue::addFeatureValueImport().

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.2.24

**Comment by florine2623** [comment] 2021-09-10 08:49
Hello @amerigeau ,

Where are you adding this piece of code ?
Is it in a module / specific development ? Could you send the file so our dev team can take a look at our request ?

Thanks!

**Comment by amerigeau** [comment] 2021-09-10 13:31
Hello @florine2623,

It's a part of a module.
I can't paste the entire code as it's a large project but the issue is focused on : `FeatureValue::addFeatureValueImport()`

This function can't create multilang feature values as said.

Best regards

**Comment by hibatallahAouadni** [comment] 2021-09-13 16:41
Hello @amerigeau 

Could you please provide a test module to reproduce the issue.

Thanks in advance!

**Comment by amerigeau** [comment] 2021-09-14 13:45
Hi @hibatallahAouadni,

Here is the test module : it just provides a cron link to create a new feature value multilang to an existing feature and links this feature value to an existing product.

Module : https://github.com/amerigeau/amtestimportfeature

Hope it helps.

**Comment by florine2623** [comment] 2021-09-14 15:44
Hello @amerigeau ,

Thanks for the link, however the module can't be installed on PS 1.7.7.x, PHP 7.2.
Here's my error : 
<img width="657" alt="Screenshot 2021-09-14 at 17 43 24" src="https://user-images.githubusercontent.com/16019289/133290006-de0eeff8-f703-452b-bd58-01d375f86182.png">

Could you check please ?
Thanks!

**Comment by amerigeau** [comment] 2021-09-21 21:46
Hi @florine2623,
I just test it, I clone the repo in my modules directory and install it without any error.
PS 1.7.7.8
PHP 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-09-22 16:59
Hello @amerigeau 

Glad to hear :tada: 
Thanks for your feedback!
Closing the issue :wink:

**Comment by amerigeau** [comment] 2021-09-22 18:47
Hi @hibatallahAouadni,
The issue isn't closed as `FeatureValue::addFeatureValueImport()` doesn't work yet.
Please reopen the issue so :)

**Comment by hibatallahAouadni** [comment] 2021-12-16 15:21
Hello @amerigeau 

Thanks for your patience :pray: 
I install your module, then I click on the cron link, a new feature value has been created:

![image](https://user-images.githubusercontent.com/23308427/146398481-05e04e63-7495-49a2-ada6-fc9ae75ba5a2.png)

So what should I do? Could you please provide the next steps to reproduce the issue :pray: 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-05 16:41
Hello @amerigeau 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-05 16:41 UTC
Labels: Bug, CO, Features, Languages, Invalid
