### ISSUE TITLE
Migration de prestashop 1.7.8.11 vers 8.1.5 via autoupgrade module. Erreur sql webservice

### ISSUE THREAD

**Issue by mgrr** [PrestaShop/PrestaShop#35791] opened 2024-04-01 07:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Lors de la migration de prestashop de la version 1.7.11 vers 8.1.5, via le module autoupgrade, une erreur sql a été levée:

SQL 8.0.0 1146 in ALTER TABLE XXXX_webservice_permission MODIFY COLUMN method ENUM( 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD' ) NOT NULL: Table 'xxxx_test.xxxx_webservice_permission' doesn't exist 

Les xxx sont pour masquer le vrai nom de la base.

Ensuite dans paramètres avancées, webservice:
An exception occurred while executing 'SELECT wa.`id_webservice_account`, wa.`key`, wa.`description`, wa.`active` FROM xxx_webservice_account wa INNER JOIN xxx_webservice_account_shop was ON was.`id_webservice_account` = wa.`id_webservice_account` WHERE was.`id_shop` IN (?) GROUP BY wa.`id_webservice_account` ORDER BY wa.id_webservice_account asc LIMIT 50' with params [1]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.yyy_webservice_account' doesn't exist

[Doctrine\DBAL\Exception\TableNotFoundException 0]

### Expected behavior

L'application est fonctionnel sauf la partie webservice qui renvoie vers une erreur 500.

### Steps to reproduce

Installation via le module autoupgrade 1-click upgrade de prestashop.

Une fois installé, dans paramètres avancées, webservice

### PrestaShop version(s) where the bug happened

1.7.8.11

### Your company or customer's name goes here (if applicable).

bijouxindiens.net

**Comment by bambinounos** [comment] 2024-04-01 21:26
Log found
*ERROR* 	v1.7.8.11	2024/03/31 - 21:09:01: Shop not found at line 422 in file classes/shop/Shop.php

**Comment by AureRita** [comment] 2024-04-02 15:22
Hi @mgrr 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(170).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/822aee89-3c48-4f4f-83b3-0601ca75dbae)

Did I miss something ? 

Waiting for feedback

**Comment by mgrr** [comment] 2024-04-04 09:07
Hi, i looked on the production website and i had already the error in the version 1.7.8.11. I think that it was an error when an old migration who had not repair.

![erreur_webservice](https://github.com/PrestaShop/PrestaShop/assets/5494848/9442deb7-a75d-485c-bbca-e1abfa140056)
How i can fix this problem ?

**Comment by AureRita** [comment] 2024-04-04 10:09
Hi @mgrr 

Thank for your details, This issue is too technical for me because it's about the Database, something have maybe broke your Database. ping @PrestaShop/tech-council , can someone please reproduce this issue ? 

Thanks

**Comment by Quetzacoalt91** [comment] 2024-04-10 11:25
These database tables have been present in the code for a very long time, even before PrestaShop 1.6. You can find their definition in [the first commit on this repository](https://github.com/PrestaShop/PrestaShop/commit/fcab98bd23762eb6c0f3cb791c2f96575146fcb5#diff-e98d435095567c145b49744715fd575eaab7050328c211b33aa9a37158421ff4R1887). If both the upgrade process and reaching the webswervice fail, I would recommend manually recreate these table.

This issue is coming from a external action and cannot be solved either on the PrestaShop or the autoupgrade projects. Detecting this kind of error should be solved by https://github.com/PrestaShop/PrestaShop/issues/35084 though, where a comparison of the current database structure will be made against the original one.

**Comment by AureRita** [comment] 2024-04-10 12:46
Hi @mgrr 

As @Quetzacoalt91 said it, It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by AureRita** 2024-04-10 12:46 UTC
Labels: Bug, BO, Webservice, Autoupgrade, 1.7.8.x, Invalid, Module
