### ISSUE TITLE
Maintenance mode error on 1.7.8.7

### ISSUE THREAD

**Issue by adponelove** [PrestaShop/PrestaShop#31415] opened 2023-02-17 09:43 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop 1.7.8.7

1 click upgrade version: v4.15.0

Module don't see that maintence mode are activeted. 

I've seen that if i active maintence mode ps put "null" in ps_shop_enabled but it works correctly. I test to put 0 and any change are made. Maintence mode works correctly and 1-click don't see it.

I just test with debug view but any error does appear

I have delete cookie and  var cache prod too

any   suggest?`
![Screenshot_15](https://user-images.githubusercontent.com/125649844/219609659-fe27e0ac-6f44-4e87-8bd8-0aaa4bbca66e.jpg)

### Expected behavior

a solution to reset maintence mode system or debug the module

### Steps to reproduce

install 1 click upgrade

view maintence mode error

enable it

reload the page 

error continued.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-click-upgrade

**Comment by sallemiines** [comment] 2023-02-17 09:54
Duplicate of #[30680](https://github.com/PrestaShop/PrestaShop/issues/30680)

**Comment by sallemiines** [comment] 2023-02-17 09:56
Hello @adponelove 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #[30680](https://github.com/PrestaShop/PrestaShop/issues/30680).

I think that All you need is to add your IP address in your maintennace config 

Thank you

**Closed as completed** 2023-02-17 09:56 UTC
Labels: Bug, Duplicate, Invalid

**Comment by adponelove** [comment] 2023-02-17 14:34
I make your solution but when i put ip adress and reload page it doesn't load. 
the loading wheel keeps spinning for several minutes without the page working. If I remove the ip from the field, the module starts loading normally.
