### ISSUE TITLE
Hook displayOverrideTemplate is not working since PS1.7.8.4

### ISSUE THREAD

**Issue by gajendrasingh681** [PrestaShop/PrestaShop#28071] opened 2022-03-30 05:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We are using hook **displayOverrideTemplate** in our custom module but it is not calling.

### Steps to reproduce

Use hook displayOverrideTemplate in custom module

### PrestaShop version(s) where the bug happened

1.7.8.4 and 1.7.8.5

**Comment by matks** [comment] 2022-03-30 07:37
Please check https://github.com/PrestaShop/PrestaShop/issues/11241 and https://github.com/PrestaShop/PrestaShop/issues/27854

**Comment by gajendrasingh681** [comment] 2022-03-30 07:51
Yes, it is the same issue #27854 but I have checked in PS1.7.8.5 and it's not working.

**Comment by hibatallahAouadni** [comment] 2022-03-30 10:55
Hello @gajendrasingh681 

Could you please provide a screen record (recording all the steps to reproduce the issue).
Cause I didn't reproduce the issue with PS1785.
Waiting for your feedback.

PS: thanks @matks for your quick replies :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-04-18 10:15
Hello @gajendrasingh681 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27854. 
Please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-04-18 10:15
Duplicate of #27854

**Closed as completed by hibatallahAouadni** 2022-04-18 10:15 UTC
Labels: Bug, CO, Duplicate, Modules, Hook, Invalid

**Comment by cdigruttola** [comment] 2023-04-01 13:35
Hi,
I'm not sure if it's the same problem. I have two modules that do the same hookDisplayOverrideTemplate, and this error occurs:

`Unable to load template 'file:modules/optimizationseo/views/templates/hook/catalog/listing/category.tplmodules/cdigruttolafaq/views/templates/hook/catalog/listing/category.tpl'`

Both modules have this function for hook:
`    public function hookDisplayOverrideTemplate($params)
    {
        if (isset($params['template_file']) && $params['template_file'] == 'catalog/listing/category') {
            return $this->getTemplatePath('catalog/listing/category.tpl');
        }
    }`

Is it possible to manage the same hookDisplayOverrideTemplate for two modules?
