### ISSUE TITLE
Customer reassurance module doesn't show before footer in front-office classical theme

### ISSUE THREAD

**Issue by silverlayer** [PrestaShop/PrestaShop#26846] opened 2021-12-03 00:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when we set the customer reassurance position above footer on all pages, the module doesn't show the reassurance block on front office.

This bug occurs on default classical theme

below is the settings on module manager:

![Screenshot_2021-12-02 Module Manager • lojademo](https://user-images.githubusercontent.com/52291477/144522993-91320daf-5dd9-48b8-929e-c8072e1b5af1.png)

And, this is the result at front office:

![Screenshot_2021-12-02 lojademo](https://user-images.githubusercontent.com/52291477/144523329-2c72c387-2c12-4f0d-aeb9-0d0719e55ac1.png)

### Expected behavior

The expected result should look something like this:

![Screenshot_2021-12-02 lojademo(1)](https://user-images.githubusercontent.com/52291477/144523428-4f247d3f-2fa7-4f8d-8ef7-3348cab03f29.png)

### Steps to reproduce

On Back office, go to module manager > Customer Reassurance [Configure] > Display > Global settings
At **footer position on all pages**, select **above footer**.

Then, go to front office and the reassurance block will not be there.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

customer reassurance v5.0.0

**Comment by hibatallahAouadni** [comment] 2021-12-06 10:49
Hello @klvnsa 

I reproduce the issue with PS1780 and PS1781, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/144833139-adae2a0e-c98c-4439-9af7-480087a9f5a5.png)

It seems that the Newsletter bloc overlaps the Customer Reassurance block :disappointed: 
It's a **regression** on PS1.7.8.0, cause I didn't manage to reproduce the issue with PS1778, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/144833278-df7bb637-e601-4172-8c0c-4924e2b45e26.png)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-12-14 12:33
Fixed by @hibatallahAouadni in #26887 and tested by @HanaRebaiQA

**Closed as completed by Progi1984** 2021-12-14 12:33 UTC
Labels: Bug, Minor, FO, Regression, Blocknewsletter, Fixed, Front-end, Blockreassurance, PR available, 1.7.8.0, Verified
