### ISSUE TITLE
Remove shop logo as attachment in email

### ISSUE THREAD

**Issue by abcreationIT** [PrestaShop/PrestaShop#15781] opened 2019-10-01 15:17 UTC
**Describe the bug**
When Prestashop send an email, the shop's logo is also attached.
Normally other emails (like Amazon) have logos and images but are not attached to the email.
Just to clarify, I want the logo of my shop in the mail, but I don't want it to be sent as an attachment

**To Reproduce**
1. place an order or an action that causes an e-mail to be sent
2. check the email
3. see the attachment symbol (for example in the Mail app on macOS)

**Screenshots**
As you can see only the e-mail sent from my site has an attachment.
<img width="54" alt="Mail" src="https://user-images.githubusercontent.com/33608547/65974690-a9a14f00-e46d-11e9-9f80-faf9efd6fd66.png">

**Code of the problem (I think)**
classes/Mail.php  |  line: ~501

`$templateVars['{shop_logo}'] = $message->embed(\Swift_Image::fromPath($logo));`

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.20

**Comment by khouloudbelguith** [comment] 2019-10-01 17:05
Hi @abcreationIT,

I did not manage to reproduce the issue with PS1.7.6.1.
I have only the invoice displayed
![image](https://user-images.githubusercontent.com/16067358/65983680-ff79f500-e475-11e9-9bd5-0427c8731085.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-10-31 07:38
Hi @abcreationIT,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-31 07:38 UTC
Labels: Theme & logo, Email, No change required

**Comment by sharkooon** [comment] 2020-02-13 12:52
Well i think there should be an option to disable embed images when emails are sending.
