### ISSUE TITLE
No category name in search results

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#10351] opened 2018-09-08 12:47 UTC
**Describe the bug**
In ps_searchbar module, the category name is no longer displayed for instant search results.
**To Reproduce**
Search for a product using the search bar. There is no category name listed in front of the product name.
In ps_searchbar.js, there is the code to display (`.append($("<span>").html(product.category_name).addClass("category"))`) it but it no longer works.

**Screenshots**
![image](https://user-images.githubusercontent.com/12268701/45254270-3f0f0400-b37e-11e8-9a76-6d9035353ba2.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-09-10 08:03
Hi @

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9767
So, I close it.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-10 08:04
Duplicate of #9767

**Closed as completed by khouloudbelguith** 2018-09-10 08:03 UTC
Labels: Duplicate
