### ISSUE TITLE
BO - ps_linklist module change position of list item by drag and drop Error in PS 8.0

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#29414] opened 2022-08-23 08:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Module ps_linklist in PS 8.0 has an error when using drag and drop to change list item position in Back-Office. 
![ps_linklist_Configure_Position_DragDrop_Bug_in_PS8 0 x_Rect](https://user-images.githubusercontent.com/3759923/186106716-64f23d0c-e602-4bbe-b05c-4506395e55c7.png)
Note: if you try to change path of `ModuleRepository` class following https://github.com/PrestaShop/PrestaShop/pull/27632/files, you will get other error with `moduleRepository->getInstanceByName` function

### Expected behavior

Position change by drag and drop in PS 8.0 go smoothly like it does in PS 1.7.8 

### Steps to reproduce

1. Go to Back Office > IMPROVE > Modules > Module Manager > Link List > Configure 
2. Use Drag and Drop feature to change list item position and see the error with path of `ModuleRepository` class

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

PHP 7.3

### If your bug is related to a module, specify its name and its version

ps_linklist v5.0.4

**Comment by hibatallahAouadni** [comment] 2022-08-23 09:36
Hello @leemyongpakvn 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28120. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: the issue has been fixed with this PR https://github.com/PrestaShop/ps_linklist/pull/147 but the new version of module is not released yet

Thanks!

**Closed as completed by hibatallahAouadni** 2022-08-23 09:36 UTC
Labels: Bug, Duplicate, Invalid

**Comment by hibatallahAouadni** [comment] 2022-08-23 09:42
Duplicate of #28120

**Comment by leemyongpakvn** [comment] 2022-08-23 09:59
@hibatallahAouadni The same error but in another use case :)

**Comment by hibatallahAouadni** [comment] 2022-08-23 14:34
@leemyongpakvn yes I know and it will be fixed in each use case :wink:
