### ISSUE TITLE
Presto Change bug

### ISSUE THREAD

**Issue by nateBitworks** [PrestaShop/PrestaShop#23556] opened 2021-03-05 14:43 UTC
#### Describe the bug
When a customer orders certain products the Presto Changeo UPS module configures the wrong price, almost 2/3 what the UPS charges.
A clear and concise description of what went wrong.

#### Expected behavior
Charge correct shipping
Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to centrevilletrailer.com
2. Search for product # BHM-BK-349-PVC-P
3. Add to cart and order as a guest
4. for an address put in the following 2169 Hester Rd, Creedmoor, NC, USA 27522
5. Select UPS ground
6. The shipping should be $71, you will notice shipping is 29.71

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

- PrestaShop version: 1.7.6
- PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment] 2021-03-08 11:06
Hello @nateBitworks 

Thanks for your issue :clap: 

Well, it seems your issue related to the **Presto Changeo UPS** module, and AFAIK this module is not native.
So, you need to contact the module developer to fix your issue.

And you have already opened this issue #23532 and we have already told you that you need help with your store.
I close this issue cause it's not related to PS Core.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-08 11:06
Duplicate of #23532

**Closed as completed by hibatallahAouadni** 2021-03-08 11:06 UTC
Labels: Duplicate
