### ISSUE TITLE
Update an order with postman. Error with id_address_delivery

### ISSUE THREAD

**Issue by jlbrd** [PrestaShop/PrestaShop#26899] opened 2021-12-06 16:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Same issue as https://github.com/PrestaShop/PrestaShop/issues/16201#issue-514419736 not solved

### Steps to reproduce

In postman I get an order then paste xml content in PUT tab in postman: 
 
![image](https://user-images.githubusercontent.com/11737691/144883728-6aca1fba-8df8-4fc1-b65c-801d992e2d75.png)

I have an error with id_address_delivery is not valid. The value is correct.
If id_address_delivery is not present in XML th error is <![CDATA[parameter "id_address_delivery" required]]> 

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

postman

**Comment by marwachelly** [comment] 2021-12-07 10:18
Hello @shakaran,

Could you please provide me the exact xml sent in your case?

Thanks!

**Comment by unlocomqx** [comment] 2021-12-08 13:01
It looks like the value is not "trimmed" properly

<img width="863" alt="2021-12-08 at 1 50 PM" src="https://user-images.githubusercontent.com/793712/145211261-928d91bc-65e2-48e9-8960-2de0b7bff249.png">

```xml
<id_address_delivery xlink:href="http://localhost/prestashop/develop/api/addresses/1">
  <![CDATA[1]]>
</id_address_delivery>
```

is read roughly as 
```txt
\n  1  \n  
```

Which means that the content is not trimmed to `CDATA` which I think it should

Workarounds for now (remove spaces and new lines)
```xml
<id_address_delivery xlink:href="http://localhost/prestashop/develop/api/addresses/1">1</id_address_delivery>
```

**Comment by jlbrd** [comment] 2021-12-08 14:12
Thank you @unlocomqx . Yes you are probably right because since my request I tested with your solution and it works.

**Comment by unlocomqx** [comment] 2021-12-08 21:40
I don't think this is a bug.
What I think would be better is, when the API returns an int value, it returns it without CDATA.
CDATA is only needed when the node content could potentially be interpreted as XML code (thus it could break the document)
i'll raise a separate issue regarding this.

**Comment by hibatallahAouadni** [comment] 2021-12-16 11:37
Hello @jlbrd 

@marwachelly asked you to proivde the xml that you use as request body, so I'm asking you again to provide the body request that you use to reproduce the issue :pray: 
Please check and feedback.

Thanks!

**Comment by jlbrd** [comment] 2021-12-17 07:42
Sorry, I thought the solution was given by @unlocomqx. A problem with new lines and spaces. So here is the content:

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <order>
        <id>
            <![CDATA[6]]>
        </id>
        <id_address_delivery xlink:href="https://localhost/api/addresses/2">
            <![CDATA[2]]>
        </id_address_delivery>
        <id_address_invoice xlink:href="https://localhost/api/addresses/2">
            <![CDATA[2]]>
        </id_address_invoice>
        <id_cart>
            <![CDATA[0]]>
        </id_cart>
        <id_currency xlink:href="https://localhost/api/currencies/1">
            <![CDATA[1]]>
        </id_currency>
        <id_lang xlink:href="https://localhost/api/languages/1">
            <![CDATA[1]]>
        </id_lang>
        <id_customer xlink:href="https://localhost/api/customers/2">
            <![CDATA[2]]>
        </id_customer>
        <id_carrier>
            <![CDATA[1]]>
        </id_carrier>
        <id_shop_group>
            <![CDATA[1]]>
        </id_shop_group>
        <id_shop>
            <![CDATA[1]]>
        </id_shop>
        <module>
            <![CDATA[0]]>
        </module>
        <payment>
            <![CDATA[0]]>
        </payment>
        <conversion_rate>
            <![CDATA[0.000000]]>
        </conversion_rate>
        <total_paid>
            <![CDATA[0.000000]]>
        </total_paid>
        <total_paid_real>
            <![CDATA[0.000000]]>
        </total_paid_real>
        <total_products>
            <![CDATA[0.000000]]>
        </total_products>
        <total_products_wt>
            <![CDATA[0.000000]]>
        </total_products_wt>
    </order>
</prestashop>
```
The error 400 Bad request: 
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <errors>
        <error>
            <code>
                <![CDATA[85]]>
            </code>
            <message>
                <![CDATA[Validation error: "La propriété Order->id_address_delivery n'est pas valide."]]>
            </message>
        </error>
    </errors>
</prestashop>
```

**Comment by jlbrd** [comment] 2021-12-17 07:47
In addition, the same body without the carriage returns and spaces:
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <order>
        <id><![CDATA[6]]></id>
        <id_address_delivery xlink:href="https://localhost/api/addresses/2"><![CDATA[2]]></id_address_delivery>
        <id_address_invoice xlink:href="https://localhost/api/addresses/2"><![CDATA[2]]></id_address_invoice>
        <id_cart><![CDATA[0]]></id_cart>
        <id_currency xlink:href="https://localhost/api/currencies/1"><![CDATA[1]]></id_currency>
        <id_lang xlink:href="https://localhost/api/languages/1"><![CDATA[1]]></id_lang>
        <id_customer xlink:href="https://localhost/api/customers/2"><![CDATA[2]]></id_customer>
        <id_carrier><![CDATA[1]]></id_carrier>
        <id_shop_group><![CDATA[1]]></id_shop_group>
        <id_shop><![CDATA[1]]></id_shop>
        <module><![CDATA[0]]></module>
        <payment><![CDATA[0]]></payment>
        <conversion_rate><![CDATA[0.000000]]></conversion_rate>
        <total_paid><![CDATA[0.000000]]></total_paid>
        <total_paid_real><![CDATA[0.000000]]></total_paid_real>
        <total_products><![CDATA[0.000000]]></total_products>
        <total_products_wt><![CDATA[0.000000]]></total_products_wt>
    </order>
</prestashop>
```

No error: 200 OK

**Comment by hibatallahAouadni** [comment] 2021-12-27 12:27
Hello @jlbrd 

In the body request, you shouldn't use the CDATA tags.
Please follow this issue #26920. This issue is a duplicate of #26920. 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-27 12:27
Duplicate of #26920

**Closed as completed by hibatallahAouadni** 2021-12-27 12:27 UTC
Labels: Bug, WS, Duplicate, Order, Addresses, Webservice, 1.7.8.0, Invalid
