### ISSUE TITLE
Recovert cart with e-mail link not log-in user automatically (PS 1.7.6.7)

### ISSUE THREAD

**Issue by jul-m** [PrestaShop/PrestaShop#21350] opened 2020-10-07 21:15 UTC
#### Describe the bug

Since PrestShop 1.7.6.7, in the "Cookie" class, the "isSessionAlive()" function checks that the customer's token exists so that this one is connected. This token is not created when creating an order from the back office by sending a payment link by email to the customer.

#### Expected behavior

The customer must be logged in automatically when he clicks on the link in his e-mail.

#### Steps to Reproduce

Create an order from the back office, and click on the button "Send a link by e-mail to the customer to make a payment".
Click on the link, the customer is no longer automatically logged in from PrestaShop 1.7.6.7.

#### Additional information

I fixed the bug by adding the line "$this->context->cookie->registerSession(new CustomerSession());" above "return $id_cart;" in the function "recovertCart()" in the file "classes/controller/FrontController.php"

* PrestaShop version: 1.7.6.7 + 1.7.6.8
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-10-08 15:33
Hi @jul-m ,
Your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/20977
So I'll close this issue, you can follow the progress directly there : https://github.com/PrestaShop/PrestaShop/issues/20977
Thanks!

**Comment by florine2623** [comment] 2020-10-08 15:33
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/20977

**Closed as completed** 2020-10-08 15:33 UTC
Labels: FO, Duplicate, Checkout
