### ISSUE TITLE
Import produit prestashop

### ISSUE THREAD

**Issue by union-des-vignerons** [PrestaShop/PrestaShop#13754] opened 2019-05-10 15:12 UTC
Le fichier d'import "produit" ne fonctionne pas. Il y a un beug provenant du fichier.

**Comment by khouloudbelguith** [comment] 2019-05-13 07:39
Hi @union-des-vignerons,

I did not manage to reproduce the issue with PS1.7.5.2.
https://drive.google.com/file/d/13LASmXksKc6TVsSqXW1NdI2szzgL1dJk/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ghost** [comment] 2019-05-31 17:02
Hello @union-des-vignerons,

Thanks for opening an issue 👍 

Can you give us more information please? Right now we don't know where to look for.

We use English on Github to make easier to everyone to follow issues. You can tell us what is the problem in French if you prefer, I'll translate it later.

**Comment by khouloudbelguith** [comment] 2019-07-01 11:32
Hi @union-des-vignerons,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-01 11:32 UTC
Labels: BO, Import / Export, No change required
