### ISSUE TITLE
Product page v2 combination bulk actions button disabled when selecting all results

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30958] opened 2023-01-19 15:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Product page v2 combinations list the bulk actions button is disabled when selecting all results (note it seems to not work only when seleting all results. Other cases like "all in page" works well).
<img width="405" alt="Screenshot 2023-01-19 at 17 44 47" src="https://user-images.githubusercontent.com/31609858/213487940-8654b10f-662e-4797-94c2-c93fdcfb3463.png">

### Expected behavior

when all results are selecte (same as with any result selected) the bulk action should be active.

### Steps to reproduce

1. go to product page v2 edit product with combinations
2. Go to combinations tab and see the list
3. In upper left corner there is a dropdown arrow which allows select option "select all results()", click it
4. See error - the "bulk actions" button above is still disabled.

You can try to select any other column one by one or "select all in page" option and you will see that the button is activated

### PrestaShop version(s) where the bug happened

develop

**Comment by zuk3975** [comment] 2023-01-19 16:08
it was actually related to typo in getCombinationIdsAction controlle annotation 😅 
<img width="945" alt="Screenshot 2023-01-19 at 18 06 18" src="https://user-images.githubusercontent.com/31609858/213493231-a0a1cf2d-d097-43d5-9d14-03d7755c2e6b.png">

**Comment by HanaRebaiQA** [comment] 2023-01-19 16:24
Hello @zuk3975 

Thanks for your report!
I was able to reproduce your issue on develop with product V2

**Develop with Product V2 : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/213494957-60e519e9-0c25-46b0-9732-99f40fd7489f.png)

**Develop with Product V1 : OK** :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/92912932/213495178-ee22c332-0f91-4964-94ff-d66cebc5e55e.png)

**8.0.1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/213496966-91d37881-95e9-4c0f-a33d-67837d3172f0.png)


Indeed, it's a regression!

I'll add this to the debug backlog so that it's fixed.

Thanks for your PR.

**Comment by HanaRebaiQA** [comment] 2023-01-20 08:21
Hello @zuk3975 

Sorry, your issue it's a duplicate of this one #30882 
So, I'll close this issue.

**Comment by HanaRebaiQA** [comment] 2023-01-20 08:21
Duplicate of #30882

**Closed as completed by HanaRebaiQA** 2023-01-20 08:21 UTC
Labels: Bug, develop, Minor, BO, Duplicate, Combinations, PR available, Invalid
