### ISSUE TITLE
Invalid VAT when settings is round on total. (1cent difference)

### ISSUE THREAD

**Issue by fif10** [PrestaShop/PrestaShop#11195] opened 2018-10-30 15:45 UTC
**Describe the bug**

The total of vat on the bill is done with the sum of the product VAT, and the shipping, and not on the total of the order, (even when the rouding is set to 'total' in settings)
This lead to  small difference (1cent) on order total, (and cause more important issue in accounting)

**To Reproduce**
1. Set the rounding on backoffice to
Round mode : Round down toward zero when it is half way there" / Round type : round on total / Number of decimals : 2
2. Set a carrier with price 3€50 shipping and 21%  VAT 
3. Set a product  with price 35€80 and 21%  VAT 
(in the detail below I have also a discount of 5.70 set, but it should not have any impact on the bug)
4. Do an order with one product add the shipping. (and apply discount if needed)

I get as total / billing :
Total product  41,50 €
Total Discount - 5,70 €
Shipping 3,50 €
Total (VAT excl.) 39,30 €
Taxe vat 8,24 €
Total 47,54 €

So vat is calculated on sum of product and shipping  (7.51 + 0.73) => 8.24
And not on total (vat excl) : 39,30 x 1.21 => 47,553

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 5.2
Bug reported here : https://www.prestashop.com/forums/topic/907942-cacul-tva-prestashop-17/#comment-3005728

**Comment by khouloudbelguith** [comment] 2018-10-30 15:55
Hi @fif10,

We have a different rounding problem, it is an issue that should be specified & fixed by our developers.
We are aware of this issue.
Your ticket is a duplicate of #9779
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-30 15:56
Duplicate of #9779

**Closed as completed by khouloudbelguith** 2018-10-30 15:55 UTC
Labels: Duplicate
