### ISSUE TITLE
Dashboard forecast not working

### ISSUE THREAD

**Issue by COM1BOUTIK** [PrestaShop/PrestaShop#12309] opened 2019-01-25 12:47 UTC
**Description**
The configuration data set is not displayed into the graphic, moreover the configuration data is lost after reloading dashboard page. 

**To Reproduce**
1. fresh install of PrestaShop 1.7.4.4
2. open dashboard page
3. click "configure" icon of the forecast section,
4. fill the field for January (for exemple : 10000 visits, 3% for conversion and 50 as cart average)
5. click save button
6. the chart is flat (like no data),
7. click  the "configure" icon again > the filled data are still visible,
8. click save button again > the chart is still flat

Here is the first issue : no graphic displayed.

9. reload dashboard page,
10. click "configure" icon of the forecast section > the data presviouly saved is lost

Here is the second issue

**Screencast**
https://ps17.maisonferrero.com/dashboard-forcast.mp4

**Additional information**
PrestaShop version: 1.7.4.4
PHP version: 7.1.26

**Comment by khouloudbelguith** [comment] 2019-01-25 13:37
Hi @COM1BOUTIK,

We manage to reproduce the issue with the "Dashboard Goals" module v2.0.2, it is added to our debug roadmap.
Your ticket is a duplicate of #9662
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-25 13:37
Duplicate of #9662

**Closed as completed by khouloudbelguith** 2019-01-25 13:37 UTC
Labels: Duplicate
