### ISSUE TITLE
Errors in the Entities Mapping when editing product. 

### ISSUE THREAD

**Issue by duongductuan** [PrestaShop/PrestaShop#27498] opened 2022-01-27 18:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Ps 1.7.8.3
When I go to the product edit page there is a problem. Someone please show me how to fix it, thanks for the help!
![image](https://user-images.githubusercontent.com/87248592/151417534-9974a427-6086-4da6-ab07-5cbb0b79d6e2.png)

### Steps to reproduce

1. Enable debug mode
2. Edit a product
3. In the Symfony toolbar & go to Doctrine
![image](https://user-images.githubusercontent.com/87248592/151418057-01795d86-1a6c-4842-bdca-1bf7f7ca3ec2.png)

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by khouloudbelguith** [comment] 2022-01-28 12:03
Hi @duongductuan,

I manage to reproduce the issue with PS1780 & PS1783 when editing a product V1. 
![image](https://user-images.githubusercontent.com/16067358/151542975-8db10ec0-28a3-4a1c-996b-15b33abc4332.png)
In PS17778 => ok
![image](https://user-images.githubusercontent.com/16067358/151543128-85aee703-9958-439f-8ce7-53d6b94ef4d3.png)

I tried to edit a product V2 (1783 & develop) => there are no errors about `PrestaShopBundle\Entity\AttributeGroup` & `PrestaShopBundle\Entity\Shop` & `PrestaShopBundle\Entity\ShopGroup`.
![image](https://user-images.githubusercontent.com/16067358/151543190-d41f1b48-feec-4d41-a431-c4162588add2.png)

Could you please check this issue: https://github.com/PrestaShop/PrestaShop/issues/27218?
I think it is similar to this ticket.

Thanks to check and feedback.

**Comment by duongductuan** [comment] 2022-01-28 14:05
> Hi @duongductuan,
> 
> I manage to reproduce the issue with PS1780 & PS1783 when editing a product V1. ![image](https://user-images.githubusercontent.com/16067358/151542975-8db10ec0-28a3-4a1c-996b-15b33abc4332.png) In PS17778 => ok ![image](https://user-images.githubusercontent.com/16067358/151543128-85aee703-9958-439f-8ce7-53d6b94ef4d3.png)
> 
> I tried to edit a product V2 (1783 & develop) => there are no errors about `PrestaShopBundle\Entity\AttributeGroup` & `PrestaShopBundle\Entity\Shop` & `PrestaShopBundle\Entity\ShopGroup`. ![image](https://user-images.githubusercontent.com/16067358/151543190-d41f1b48-feec-4d41-a431-c4162588add2.png)
> 
> Could you please check this issue: #27218? I think it is similar to this ticket.
> 
> Thanks to check and feedback.

I have some questions.. in update to 1.7.8.4 will fix it? thanks for your feedback.

**Comment by khouloudbelguith** [comment] 2022-01-28 15:13
Hi @duongductuan,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #27218
I updated the other issue with your steps also :slightly_smiling_face: 
So, I close it.

Thanks!

**Comment by khouloudbelguith** [comment] 2022-01-28 15:13
Duplicate of #27218

**Closed as completed by khouloudbelguith** 2022-01-28 15:13 UTC
Labels: Bug, BO, Duplicate, Catalog, Regression, 1.7.8.0, Invalid
