### ISSUE TITLE
Modules positions not works for pages with dash in url

### ISSUE THREAD

**Issue by rtvt** [PrestaShop/PrestaShop#12518] opened 2019-02-08 20:10 UTC
It seems like module position stopped work for me in Prestahop 1.7.5, but only for pages with 2 or more words in url, like "new-products".

**To Reproduce**
Install clean Prestashop 1.7.5
Go to Design - Positions - take for example Newsletter subscription module in FooterBefore hook - click Edit - in list we can select "newproducts" - save.
Now go to new products page - module still there: https://gyazo.com/8bf46714cda5fa09b0c65f8928c982a6

Back to list of exceptions for this module, and type "new-products" (with dash):
https://gyazo.com/b1637c5c9065ceeeae9783be0fd3af76

Save, go to page - now module is hidden, as it should be.
https://gyazo.com/17ba7e660155e2215c34d6ff7e0d972f

By the way, it works for pages with one word urls, like "index" or "contact".

Also I have another 1.7.4.3, and it works normal with all pages.

**Comment by khouloudbelguith** [comment] 2019-02-11 07:55
Hi @rtvt,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1StVeYA7X5iMWr9bNbBV3-Bn2WTCFtvlU/view
Thanks to check & feedback.

**Comment by rtvt** [comment] 2019-02-11 17:00
Hi @khouloudbelguith 
Thank you for answer, but I think you understand me not correct.

I tried to type "new-products" by hands to show, that it works, but default "newproducts" not works. Also you checked homepage on video, but we test new products page.

So what's the problem:

1) You have clean 1.7.5.0
2) Newsletter subscription module shows on every page in FooterBefore hook by default.
3) You want to hide this module on New products page.
4) So for it you go to Design - Positions - displayFooterBefore - Newsletter subscription - Edit - Select "newproducts" from the list of existing pages - Save.
5) Now you go to Front office - go to New products page (for example by using default link to new products in the footer) - and you can see that module still visible.

**Comment by khouloudbelguith** [comment] 2019-02-11 17:38
@rtvt, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.5.0.
When I go to Front office => New products page and the module still visible.
I tried with the machine shuffle (PS1.7.5.0 => NOK.
With PS1.7.4.4 => OK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2019-02-12 09:45
I tried with featured products on display home for index page and it's well not displayed
I tried with blocknewsletter on displayfooterbefore for index page and it's well not displayed

I tried with blocksearch on displpaytop for the following pages and it's still displayed : 
- new product
- my account
- order slip
- best sales
- prices drop
- order detail

**Comment by khouloudbelguith** [comment] 2019-02-12 11:56
Hi @marionf,

I tried with blocksearch on the "displayTop" hook for the "New products", "Prices drop", "Best Sales" page, it is displayed => NOK, I tried with cart page => it is not displayed => OK.
I think that the problem related to the pages with dash in URL(prices-drop, new-products, best-sales)
Thanks!

**Comment by kpodemski** [comment] 2019-02-12 21:18
@marionf @khouloudbelguith 

this should fix it:
https://github.com/PrestaShop/PrestaShop/pull/12547

**Comment by rtvt** [comment] 2019-02-13 09:42
@kpodemski Thanks! It works

**Comment by khouloudbelguith** [comment] 2020-10-08 14:59
Hi!
Fixed by https://github.com/PrestaShop/PrestaShop/pull/21168

Thanks!

**Comment by khouloudbelguith** [comment] 2020-10-08 14:59
Duplicate of #19226

**Closed as completed by khouloudbelguith** 2020-10-08 14:59 UTC
Labels: Bug, Minor, FO, Duplicate, Positions, Regression, 1.7.5.0, 1.7.6.0, PR available
