### ISSUE TITLE
[PrestaShopDatabaseException] Unknown column 'psi.id_country' in 'on clause'

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#14097] opened 2019-06-06 09:44 UTC
**Describe the bug**
Create a category. add a product inside. Try to open the cateogry page on FO:

[PrestaShopDatabaseException]
Unknown column 'psi.id_country' in 'on clause'

No log on web server log.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: 7.0

**Comment by matteolavaggi** [comment] 2019-06-06 11:56
is a default facets module bug (LOL). 

You need to upgrade to last version and run the index for the first time for sure. i will check if this happen on every new category before the index is launched. Not good, developer fix the default module installation so it will create the index table and avoid this error.

**Comment by mariem-abid** [comment] 2019-06-07 14:32
Hi @matteolavaggi,

Does your problem is solved?

Thanks

**Comment by matteolavaggi** [comment] 2019-06-07 15:00
Yes, but dev must fix this in the installation routine of the shop

**Comment by khouloudbelguith** [comment] 2019-06-10 15:48
Hi @matteolavaggi,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record.
https://drive.google.com/file/d/1PJ0DssaDpDw6gS8st18kQ6xd_8tl3PTj/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-10 07:39
Hi @matteolavaggi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-10 07:39 UTC
Labels: Bug, FO, Categories, No change required
