### ISSUE TITLE
FO - Product images are blurry after upgrade from 1.6.1.24 to 1.7.8.0

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#25618] opened 2021-08-16 15:33 UTC
#### Describe the bug

After upgrade from 1.6.1.24 to 1.7.8.0 RC1 Build 2, the images of products on FO are blurry : The thumbnails are used instead of the large product pictures.

If I switch to another image of this product, the image is displayed OK. If I go back to the first image, it's also displayed OK now.

If i refresh the page, the image is blurry again.

#### Expected behavior

Image should always be displayed OK.

#### Steps to Reproduce

1. Upgrade from 1.6.1.24 to 1.7.8.0 RC1 B2
2. Go to FO

**Screenshots**

https://drive.google.com/file/d/1fY6xS7FoSDp20cATlGN4fvz-_qDMwwkn/view?usp=sharing

![image](https://user-images.githubusercontent.com/55688534/129589402-217bf5a0-5a26-4651-9653-6704838cfe4c.png)

#### Additional information

* PrestaShop version: 1.7.8.0 RC1 B2
* PHP version: N/A

**Comment by kpodemski** [comment] 2021-08-16 15:36
Hello @Robin-Fischer-PS 

Have you tried to regenerate the images again?

**Comment by Robin-Fischer-PS** [comment] 2021-08-17 08:03
Hi @kpodemski ! Yes, even after regenerating it's KO, I'm checking with others QA if they reproduce it !

**Comment by matthieu-rolland** [comment] 2021-08-19 16:29
As seen with @Robin-Fischer-PS and @MatShir

This is not actually a bug:

### What happened

Default image sizes for product thumbnails are different in 1.6.1 and 1.7.8, we would not see these blurry images before because the largest image was always displayed on FO, which was bad for SEO. But now that we fixed that and load the thumbnail at appropriate sizes, the issue is obvious.

It's the same kind of issue someone would meet when changing FO theme and setting new image sizes.

### What can be done:

This can be fixed easily by re-generating images in the BO, there is a feature for that. @Robin-Fischer-PS made sure this feature is working with user-uploaded images, it's all good 👍 

We can close this issue.

**Closed as completed** 2021-08-19 16:32 UTC
Labels: Bug, Minor, FO, Won't fix, Regression, 1.7.8.x
