### ISSUE TITLE
Product quick actions menu & displayAdminProductsExtra

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#36046] opened 2024-04-29 10:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a module implements the "displayAdminProductsExtra" it is capable of displaying additional module content under the menu tab when editing a product in the back office.

However, since Prestashop 8.1, if the modules makes any ajax requests via JS, the items in the product quick actions menu become disabled.  It seems Prestashop 8.1 has implemented an event handler for ajax requests somewhere and disabled the items and never reenables them.

![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/04256d2b-4cf8-4395-aeac-d3a2aa983806)

### Steps to reproduce

Create a new blank module which implements the displayAdminProductsExtra hook
The hook should perform an ajax requests to any valid url via JS
The menu items show in the attachment are now disabled when you hover over them or try to click them.

### PrestaShop version(s) where the bug happened

8.1.x

**Comment by florine2623** [comment] 2024-05-13 13:26
Hello,

Could you send an example module ?
I can't reproduce your issue.

Thanks!

**Comment by paulnoelcholot** [comment] 2024-06-11 08:48
Hello @musaffarpatel,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-06-11 08:48 UTC
Labels: Bug, Hook, Invalid, 8.1.x
