### ISSUE TITLE
Prestashop 1.7.5 product page - module tab -  not working

### ISSUE THREAD

**Issue by norby1** [PrestaShop/PrestaShop#12569] opened 2019-02-14 12:30 UTC
**Describe the bug**
Can't configure modules on product page tab, when I click configure nothing happens.

**To Reproduce**
1. Go to 'Products Catalog'
2. Click on 'Product then on Module '
3. If you have a product on this hook click configure
4. Nothing happens.

Err from console:
Uncaught Error: Syntax error, unrecognized expression: Product name
    at Function.t.error (main.bundle.js:275)
    at t.tokenize (main.bundle.js:275)
    at t.select (main.bundle.js:275)
    at Function.t [as find] (main.bundle.js:275)
    at De.fn.init.find (main.bundle.js:275)
    at new De.fn.init (main.bundle.js:275)
    at De (main.bundle.js:275)
    at i (main.bundle.js:275)
    at e.value (main.bundle.js:275)
    at new e (main.bundle.js:275)

Unchecked runtime.lastError: The message port closed before a response was received.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0.33
![screenshot 32](https://user-images.githubusercontent.com/191257/52786959-1b569500-3065-11e9-820c-de19dabffd96.png)

**Comment by khouloudbelguith** [comment] 2019-02-14 12:41
Hi @norby1,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11923 to solve the issue.
It is fixed in the next release PS1.7.5.1.
Your ticket is a duplicate of #11911
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-14 12:41
Duplicate of #11911

**Closed as completed by khouloudbelguith** 2019-02-14 12:41 UTC
Labels: Duplicate
