### ISSUE TITLE
Can not access backoffice: Error found : CData section not finished 

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#22507] opened 2020-12-19 13:11 UTC
#### Describe the bug

Getting error, see screenshot

#### Expected behaviour

to be able to access backoffice

#### Steps to Reproduce

<img width="855" alt="Screenshot 2020-12-19 at 12 46 50" src="https://user-images.githubusercontent.com/46492443/102690191-a2459d00-41fb-11eb-9deb-17f684165cce.png">

#### Additional information

I have tried to delete the files in config folder and clean cache, but once I remove they are being downloaded again. 

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by SimonGrn** [comment] 2020-12-19 15:59
Hello @01park 

I'm sorry but we need more context here. Did you do something special ? When does it started happening ? When you say "I have tried to delete the files in config folder" are you talking about the `must_have_module_list.xml` file ?
A fresh install of 1.7.6.5 doesn't have any trouble so we need to rule out a problem in your own environment.

Thank you.

**Comment by 01park** [comment] 2020-12-19 16:52
[default_country_modules_list-2.xml.zip](https://github.com/PrestaShop/PrestaShop/files/5719844/default_country_modules_list-2.xml.zip)

Hi,

No, this just happend out of the blue.

After Googling I found some solutions on Github from PS support where they advised to remove some files. So I removed the one in the config xlm folder. Once removed I noticed after refreshing the files got downloaded again. 

What I did now is this: 

in classes tools change this

protected static $is_addons_up = false;

I also removed default_country_modules_list.xml 

This gave me access again to the back office

But I assume the files in this folder get updated for a reason.

<img width="636" alt="Screenshot 2020-12-19 at 13 44 58" src="https://user-images.githubusercontent.com/46492443/102694721-d1b7d200-421a-11eb-856e-53e778600f64.png">

And additional thing I noticed now is that all modules that needed to be updated, are no longer showing to update and when I select 1 click upgrade it won't open this module. Error 500 shows


I downloaded the file and also this starts of with an error. Looks like the file coming form PS is not correct with my version.

**Comment by stefanieelling** [comment] 2020-12-19 17:40
What do you do to get started with PrestaShop? As in what steps did you take to debug and find issues in the code?

**Comment by 01park** [comment] 2020-12-19 17:43
Hi @stefanieelling 

Are you having the same issues?

**Comment by SimonGrn** [comment] 2020-12-19 18:18
@01park,
these files are downloaded automatically from Addons, but they seem to be corrupted for you for some reason. They are used to get the last version of modules.
Can you give us the file `must_have_module_list.xml` that seems to be problematic ?
Also could you try to disconnect from Addons then reconnect in your backoffice ?

@stefanieelling,
hello, this repository is aimed at bugs and features of the Core project of PrestaShop. If you're interested in discussing with other users, I can link you to the [community forums](https://www.prestashop.com/forums/), or the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack). If you're looking for documentation, you can go to the [devdocs](https://devdocs.prestashop.com/) (for developers) or the [docs](https://doc.prestashop.com/display/PS17/Getting+started) (for end users).

**Comment by 01park** [comment] 2020-12-19 18:50
[xml.zip](https://github.com/PrestaShop/PrestaShop/files/5719993/xml.zip)


I have attache the  file


We are not connected to Addons

**Comment by hibatallahAouadni** [comment] 2020-12-21 10:09
Hello @01park 

Could you please confirm these steps to reproduce the issue, cause I didn't manage to reproduce it even when I put your files into my shop>config>xml:

1. BO>IMPROVE>Modules>Module Manager, connect to Addons at least once
2. Then disconnect
3. From nowhere, while trying to access to your BO, this error occurred
 
Is that so? **We need the steps to reproduce the issue**.

Thanks!

**Comment by 01park** [comment] 2020-12-21 10:14
Hi,

I connected to add-ons. Disconnected and edit the tools file.

I now am able to log in again without any errors. 

Thank you!

**Comment by hibatallahAouadni** [comment] 2020-12-21 11:56
Hello @01park 

Thanks for your confirmation! Unfortunately, I didn't manage to reproduce it but glad to hear that your issue is resolved :tada: 
So, I close this issue. Feel free to open a new one if you encounter any other problem.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-21 11:56 UTC
Labels: Bug, BO, Modules, No change required, 1.7.6.5
