### ISSUE TITLE
[ORDER PAGE] Partial Refund - 3/11

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15820] opened 2019-10-04 08:30 UTC
Part of the order page migration and redesign project.

**User Story**

As a merchant, when I check an order, I need to be able refund my client.

**Detailed specification**
Specs on the repo prestashop-specs
[Order Action Specs](https://github.com/PrestaShop/prestashop-specs/blob/cc476f1fc0c71c63bd3ba4879131f5163fca05e7/Order%20Page%20View.md#i-action-panel)

**Comment by MatShir** [comment] 2019-11-05 10:28
An interesting bug about the partial refund #15522

**Comment by MatShir** [comment] 2020-01-17 17:46
- The total of the refund should be limited by the total of the order. 
- Refund a product is limited to the total of the product multiplied by the quantity selected

Legal advice required to see if when you refund with a voucher, you have to generate a credit slip. Also, if it is allowed to refund with a voucher?

**Comment by jolelievre** [comment] 2020-01-20 13:20
Update about this feature, as discussed with @MatShir
- restock checbox is always displayed but is preselected (checked when order is delivered)
- prefill amount inputs in partial refund (empty at start, filled when the quantity is changed, it takes into account the product price and the max allowed amount)
- manage a max amount of refunding on server side (if you post 1000euros, but the price of the product is 2 * 10euros, then the refund will have a max value of 20euros), no error returned just the value is fixed on server side
- the checkbox for credit slip and voucher is always displayed (even on partial refund), this behaviour may be changes later with input from the legal services (is it allowed to refund someone without a credit slip? is it normal to generate a voucher AND a credit slip?)

**Comment by jolelievre** [comment] 2020-01-20 13:22
Technical update:

Since the credit slip is optional we may refund procucts but no OrderSlip will be generated, the problem is that this table/object is used to determine the refunded amount, so without credit slip we don't have this information

The OrderDetail contains all the refund informations except for the amount, so a new column refunded_amount should be added

**Comment by jolelievre** [comment] 2020-02-11 14:30
Closed by https://github.com/PrestaShop/PrestaShop/pull/17211

**Closed as completed by jolelievre** 2020-02-11 14:30 UTC
Labels: Feature, Order, migration, Must-have
