### ISSUE TITLE
Refund partial with reduction -> Trouble not the good amount

### ISSUE THREAD

**Issue by aurelienharinck** [PrestaShop/PrestaShop#14092] opened 2019-06-05 21:28 UTC
**Describe the bug**
This bug occurs when we create a refund on an order that have a discount. 

**To Reproduce**
Follow this steps :

**Screenshots**
<img width="1222" alt="Capture d’écran 2019-06-05 à 22 04 11" src="https://user-images.githubusercontent.com/12425454/58988684-7b26a680-87e2-11e9-9e62-ae25db3f76e6.png">

We refund 99.18€ for products and 8.40€ for delivery. 
So the total of the refund is 107.58€ the same price of this order. 

<img width="713" alt="Capture d’écran 2019-06-05 à 22 06 15" src="https://user-images.githubusercontent.com/12425454/58988687-7e219700-87e2-11e9-81d9-a1c0a0bacbf6.png">

But in the documents, I'm surprised that PrestaShop display this amount 112.80€.

I suppose that the refund didn't care on the discount.
Because 112.80€ - 107.58€ = 5.22€ 

**Additionnal information**
PrestaShop version: 1.7.6

Can anyone help me understand what the problem is, please ? And how to fix it ? 

Thank you !

**Comment by mariem-abid** [comment] 2019-06-07 15:49
Hi @Harincka,

We'll first try to reproduce it and we'll come back to you if we need more information.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-10 09:24
Hi @Harincka,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.0beta1.
I attached a video record.
https://drive.google.com/file/d/1sw1ooypmbbk3vY8xKUmxXoED3A7JCBUR/view
Thanks to check & feedback.

**Comment by aurelienharinck** [comment] 2019-06-11 20:18
Hi @khouloudbelguith, 

This issue appear with this functionnality : 

The video will be more explicit :) 
https://youtu.be/tJBNdzS6wDc

Thank for your answer.

**Comment by khouloudbelguith** [comment] 2019-06-12 08:32
@Harincka, thanks for your feedback.
Is it the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/9854?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-12 07:41
Hi @Harincka,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-12 07:41 UTC
Labels: BO, Order, Merchandise returns, No change required, 1.7.6.0

**Comment by gabrieleligetta** [comment] 2021-12-14 14:01
Hi,
if i'm not too late i would try to spread light over this issue:
the incriminated piece of code that don't let prestashop subtract discount code from total product refund is this one:

![image](https://user-images.githubusercontent.com/58666051/146012222-80c27ddf-2fc9-4aa9-8f07-9ea62c24e67c.png)

if i change the field "order_slip_type" from 2 to 1 inside the prestashop database table "ps_order_slip" the pdf of the credit note is printed with the total price minus the import of the discount code.

**Comment by gabrieleligetta** [comment] 2021-12-14 14:02
Hi, if i'm not too late i would try to spread light over this issue: the incriminated piece of code that don't let prestashop subtract discount code from total product refund is this one:
 
 ![image](https://user-images.githubusercontent.com/58666051/146012222-80c27ddf-2fc9-4aa9-8f07-9ea62c24e67c.png)
 
 if i change the field "order_slip_type" from 2 to 1 inside the prestashop database table "ps_order_slip" the pdf of the credit note is printed with the total price minus the import of the discount code.

The path of the piece of code is: src/Adapter/Order/Refund/OrderSlipCreator.php

This is because during the refund calculation there is this condition:

![image](https://user-images.githubusercontent.com/58666051/146013524-155e7849-6ce6-4d6b-a7b0-ccf8e3b2fe81.png)

So if slip_type is one prestashop subtract discount code, else no.

This condition can be found in src/Adapter/Order/Refund/OrderRefundCalculator.php

I Hope this can help devs solving this issue.

**Comment by Marquis7373** [comment] 2022-07-14 05:39
Same problem, please reopen this issue
