### ISSUE TITLE
Some css backoffice issues

### ISSUE THREAD

**Issue by MockoB** [PrestaShop/PrestaShop#33072] opened 2023-07-03 07:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are many CSS issues with the back office on mobile and desktop. I won't be able to upload all of those but here are some of them:

https://ibb.co/PMZPGwY

https://ibb.co/yfD66yn

https://ibb.co/6BSLn9c

https://ibb.co/s5VVVp0

https://ibb.co/p4PH726

https://ibb.co/6HRT4bp

https://ibb.co/gtyHDb6

### Expected behavior

I suppose the back office shouldn't be broken.

### Steps to reproduce

Just use your phone in the back office.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2023-07-03 08:08
Some of the issues will be solved by https://github.com/PrestaShop/PrestaShop/discussions/32280

**Comment by MockoB** [comment] 2023-07-03 08:53
It’s opened two years ago?!?!
That’s why I’m still on PS 1.5.6 … :)

**Comment by AureRita** [comment] 2023-07-03 14:07
Hi @MockoB 

Thank you for your report, Can you said us in with tab are you ? because, even with the screenshot, I can see where the issue come, your issue can come from your language and it can be in you web bowser. 

Can you provide us more information 

Moreover, you can put some of them not treated in the discussion that @Hlavtox send to you, this one help our team to improve prestashop 

Waiting for your feedback

**Comment by MockoB** [comment] 2023-07-03 15:08
Ok, I’ll be more detailed. 
Those screenshots are from my smart phone and the browser is safari. The language is Bulgarian. 
Actually I just checked it with developer tools in Google chrome with some of the phones available there. The result is the same on iPhone 12pro for example and not just with it. The language there is English. Here are some more screenshots.

1. It is random order opened. You could clearly see that the order status is over the “Update Status” button, which makes it impossible to click the button.
<a href="https://ibb.co/qdLxKLR"><img src="https://i.ibb.co/qdLxKLR/1.jpg" alt="1" border="0"></a>

2. It’s customer information page, still in English and in developer tools in Google chrome. If you scroll down you could see more of those fields misaligned.
<a href="https://ibb.co/fphkXS5"><img src="https://i.ibb.co/fphkXS5/2.png" alt="2" border="0"></a>

3. Random product/stocks.
<a href="https://ibb.co/nBPPsFc"><img src="https://i.ibb.co/nBPPsFc/3.jpg" alt="3" border="0"></a>

4. From my phone, in Bulgarian, product/pricing 
<a href="https://ibb.co/pj2q78T"><img src="https://i.ibb.co/pj2q78T/4.jpg" alt="4" border="0"></a>

5. It’s the stats menu, scroll it down, there are plenty of those.
<a href="https://ibb.co/z7WTM7V"><img src="https://i.ibb.co/z7WTM7V/5.jpg" alt="5" border="0"></a>


If I continue I’ll find more. That’s where I started with the translations and so far found those. There are some translations with %something% that are not translatable also, but the main show stopper I found so far is I can’t add tax to the products, I already opened bug report about it.

**Comment by aniszr** [comment] 2023-07-07 13:59
Hello @MockoB 

As @Hlavtox mentioned above this issue is duplicate and will be fixed by #32280
Closing the issue in favor of #32280

Thanks for your understanding :pray:

**Comment by aniszr** [comment] 2023-07-07 14:00
Duplicate of #32280

**Closed as not planned** 2023-07-07 14:00 UTC
Labels: Bug, BO, Duplicate, Order, Invalid, 8.1.x
