### ISSUE TITLE
Problem entering customer address in your order.

### ISSUE THREAD

**Issue by clubedovapor** [PrestaShop/PrestaShop#14940] opened 2019-07-31 15:33 UTC
**Describe the bug**
I can't enter the customer's address in their order.

When I click the "Add New Address" button on the customer order, the address form opens, I enter the information, click save, and the address does not appear on the customer order.

I got in touch with the topic, but they said this problem is a prestashop bug.

**To Reproduce**
1. Go to orders
2. Click on 'add new order'
3. Select a customer
3. Scroll down and click 'Add a new adress'
4. I enter the address, click save, and nothing happens.

**Screenshots**
https://www.loom.com/share/24b2384c23c946e9b5927dd08e016be6

**Additional information**
PrestaShop version: 1.7.5.1

**Comment by clubedovapor** [comment] 2019-07-31 15:35
Ps. I already cleaned the caches and it didn't work.

**Comment by clubedovapor** [comment] 2019-07-31 15:36
I got in touch with the topic, but they said this problem is a prestashop bug.

Sorry: i got in touch with the theme*

**Comment by khouloudbelguith** [comment] 2019-07-31 15:55
Hi @clubedovapor,

I did not manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.1.
I attached a screen record
https://drive.google.com/file/d/1jqy9HginDcI9MSdWVGP-3ylEl0grU-bm/view
Thanks to check & feedback.

**Comment by clubedovapor** [comment] 2019-07-31 16:49
Hi

OMG! I'm lost!

I already got in touch with two modules and also with the theme and nobody can help me.

Thank you very much.

**Comment by khouloudbelguith** [comment] 2019-08-01 10:57
@clubedovapor, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-02 07:14
Hi @clubedovapor, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-02 07:14 UTC
Labels: Bug, BO, Order, Addresses, No change required, 1.7.5.1
