### ISSUE TITLE
PHP Warning: Undefined array key 1 in dispatcher.php

### ISSUE THREAD

**Issue by maxadp** [PrestaShop/PrestaShop#34932] opened 2023-12-29 10:19 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

ello everyone, I would like to bring to everyone's attention a PHP Warning present in the log, precisely two:

PHP Warning: Undefined array key 1 in /home//public_html/webservice/dispatcher.php on line 44
PHP Warning: Undefined array key 1 in /home//public_html/webservice/dispatcher.php on line 50

The Prestashop version is 8.1.1 with PHP 8.1. I also attach a screen.

<img width="792" alt="Screenshot 2023-12-29 alle 10 12 47" src="https://github.com/PrestaShop/PrestaShop/assets/47750947/21ef1c8d-0465-4141-a2c4-7335d07fe010">

### Steps to reproduce

Check error_log_php in your root and you will see the errors.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Max - MDP

**Comment by paulnoelcholot** [comment] 2024-01-02 10:24
Hello @maxadp,

I tried to reproduce your issue but I can't, can you give me more information to reproduce this bug?

Thanks for your feedback!

**Comment by maxadp** [comment] 2024-01-02 13:56
Hi, bug appears on error_php_log if you got 8.1 php version and got webservice enabled.

I think that the problem is php 8.1, cause when I switch to 7.4 php, the error disappeared. I notice also that with 7.4 php, many warning and dreprecation alert all gone away. My final thought that Prestashop 8.1, theme and most of the module avaible now, works better with php 7.4

**Comment by florine2623** [comment] 2024-01-03 14:25
Can you provide the exact path to the file ?

**Comment by florine2623** [comment] 2024-01-19 08:40
Hello,

Since we had no news from you for, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2024-01-19 08:40 UTC
Labels: Bug, CO, Logs, Webservice, 8.1.x
