### ISSUE TITLE
Unable to edit email subjects

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#11431] opened 2018-11-19 09:41 UTC
**Describe the bug**
It is not possible to edit and customize majority of email subjects.

**To Reproduce**
1. Go to Intl/Translations/Email translations/Body/ core or classic
2. Click on Core emails - any email - No Subject was found for account in the database.
3. Scroll down to module emails, select ps_emailalerts for example, any email -> subject is displayed ->try to edit and save -> impossible - still the same subject is displayed
You may want to try edit email subjects in Intl/Translations/Email translations/Subject/ BUT - 
a/ you have no idea what email you're editing
b/ there are 24 expressions - PS uses 34 core emails

Is it just not possible to support HTML <meta> Tag <title>any email subject</title> from email html file with support of variables such as {shop_name} or {order_name}?

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.30

**Comment by khouloudbelguith** [comment] 2018-11-19 09:52
Hi @mrabsinthe,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9599
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-19 09:52
Duplicate of #9599

**Closed as completed by khouloudbelguith** 2018-11-19 09:52 UTC
Labels: Duplicate
