### ISSUE TITLE
Problem With Geolocation 

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#17950] opened 2020-03-03 15:05 UTC
Hello everyone, 

I use PS 1.7.5 and I would like to block some countries because I think they are bot. 
I went into Geolocation to active Geolocation via IP but it give me error : Geolocation database not available.
I tried also to download the file and it does't open with this link : https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz

Could you please help me?

**Comment by khouloudbelguith** [comment] 2020-03-03 15:13
Hi @morghy1992,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17413 to fix the issue.
Your ticket is a duplicate of #17174
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-03 15:13
Duplicate of #17174

**Comment by khouloudbelguith** [comment] 2020-03-03 15:13
Here's an improvement about modifying the way users access MaxMind GeoIP service
https://github.com/PrestaShop/PrestaShop/issues/17193

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-03 15:13 UTC
Labels: Duplicate

**Comment by morghy1992** [comment] 2020-03-03 15:17
@khouloudbelguith  Thank you for your reply. I don't understand how to fix the problem. Sorry I am not very use to it . Could you please help me?

**Comment by khouloudbelguith** [comment] 2020-03-03 15:44
@morghy1992, Since December 30, 2019, you need to register for a MaxMind account to get a license key to be able to download the geolocation data. Once downloaded, extract the data using Winrar or Gzip into the /app/Resources/geoip/ directory.
https://dev.maxmind.com/geoip/geoip2/geolite2

Thanks!
