### ISSUE TITLE
PPV2 - Prices in Arabic are not displayed correctly (always show 0.000000)

### ISSUE THREAD

**Issue by ghadazoubi** [PrestaShop/PrestaShop#33871] opened 2023-09-07 11:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have problem in Admin panel in prestashop 8 in Products page 
if I change the admin page to arabic and enter to the products all prices will appear as zeroes in the price field 
when I open the consol and see what is the value of the price it shown as arabic or indian number : 
![image](https://github.com/PrestaShop/PrestaShop/assets/73945317/75c4ee5f-68db-486e-96a3-7587e6298ea8)

if I save the file without change the price it will convert it to zero and that conflect the client that edit some feature without rewrite the price again 

how can I fixed it??

### Expected behavior

I think the number will shown as english number to be right

### Steps to reproduce

1. Add arabic language to your prestashop admin
2. change the admin language from your account profile to arabic
3. go to any product and edit it 
4. go to the price and see the value of it

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.2

**Comment by hibatallahAouadni** [comment] 2023-09-10 16:12
Hello @ghadazoubi 

Could you please downgrade your PHP version to 8.1 cause PS8 is not compatible with PHP 8.2 🙏 
Please check our system requirement [here](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart) and feedback.

Thanks!

**Comment by mikajaxxx** [comment] 2023-09-16 16:17
@hibatallahAouadni  Same problem with persian language! i have php 8.1 so the problem is not because of php version . it might be related to utf8 for price field

**Comment by ghadazoubi** [comment] 2023-09-17 10:36
any one can help plz??

**Comment by florine2623** [comment] 2023-09-20 14:19
Hello @ghadazoubi , 
I have reproduced your issue 8.1.x :
<img width="1439" alt="Screenshot 2023-09-20 at 16 13 57" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ad6076b8-16ae-4ecd-bc3b-0f2a8ab54b48">

When I change my language back to English or French, the issue disappears.

On develop, the issue is not present.

@PrestaShop/product-council , what should be done with this issue as it is not present on future version `develop` ?

**Comment by MatShir** [comment] 2023-09-20 14:23
Keep it opened see if someone wants to fix it on the 8

**Comment by ghadazoubi** [comment] 2023-09-21 07:33
Hello [florine2623](https://github.com/florine2623)
Please note that the problem just in Arabic
I downgrade the PHP version to 8.1 and the same issue with Arabic language, also I think it with Persian language 
the problem in the number format, we need to keep it as English and French format, the number only

**Comment by mikajaxxx** [comment] 2023-09-30 11:38
Hello
this is a critical bug. Anyone could provide a temperorary fix ?

**Comment by boherm** [comment] 2023-10-13 08:38
Hi everyone!
Unfortunately, It's pretty difficult to simply fix this in a clean way.

After some research on this, this weird number format is relative to a Estearn arabic locale.
On Western arabic locale, we have numbers as we know in other world locales.

For instance, if you force the locale to `ar_TN` (for tunisia) in `src/PrestaShopBundle/EventListener/UserLocaleListener.php` file, you will see the right format for numbers.

I'm searching for a good solution now...

**Comment by ghadazoubi** [comment] 2023-10-13 18:07
Hello @boherm 
I opened the file that you mention but I didnt know where I have to change ?!
can you please explain in details 

many thankx

**Comment by mikajaxxx** [comment] 2023-10-19 11:53
@boherm 
we have the same problem on persian fa-IR ! 
anyone have a temperoray solution?

**Comment by RosaBenouamer** [comment] 2023-10-20 09:14
@boherm is working on a PR and will probably submit it today. If will be available to test it it could be great :-)

**Comment by boherm** [comment] 2023-10-20 15:40
Guys, I've just submitted a [PR](https://github.com/PrestaShop/PrestaShop/pull/34356) to fix this behaviour.

**Comment by mikajaxxx** [comment] 2023-10-28 14:40
OK! We have same issue on ps 17.8.10 if i add product combination in fa-IR we can't save product! so i should change langauge back to english to be able saving products!
![save-product](https://github.com/PrestaShop/PrestaShop/assets/5157272/254ed5d4-5e28-4ee4-8d89-109ccf978095)
browser console log:

response:


`XHRPOST
https://prj.webroof.ir/qamari/adminn/index.php/sell/catalog/products/11?_token=K7t4cKXGmzq697nBFJ65ef6zYScck1tojy3oe6dNd8M#tab-step1
[HTTP/2 400  1810ms]

	
combination_22_attribute_price	[ "This value is not valid." ]
0	"This value is not valid."
combination_23_attribute_price	[ "This value is not valid." ]
0	"This value is not valid."`
PS: it seems the main problem is because of decimal! i removed decimal from combination's price and product save


debug mode:
`<html><body>


children[combination_22].children[attribute_price] | این مقدار معتبر نمی باشد. | "‎-2802000.000000" | ConstraintViolation {#6873 ▼   -message: "این مقدار معتبر نمی باشد."   -messageTemplate: "This value is not valid."   -parameters: [▶]   -plural: null   -root: Form {#2691 ▶}   -propertyPath: "children[combination_22].children[attribute_price]"   -invalidValue: "‎-2802000.000000"   -constraint: Form {#6861 …}   -code: "1dafa156-89e1-4736-b832-419c2e501fca"   -cause: TransformationFailedException {#5281 …} }
-- | -- | -- | --
children[combination_23].children[attribute_price] | این مقدار معتبر نمی باشد. | "‎-15643000.000000" | ConstraintViolation {#6879 ▼   -message: "این مقدار معتبر نمی باشد."   -messageTemplate: "This value is not valid."   -parameters: [▼     "{{ value }}" => "‎-15643000.000000"   ]   -plural: null   -root: Form {#2691 ▶}   -propertyPath: "children[combination_23].children[attribute_price]"   -invalidValue: "‎-15643000.000000"   -constraint: Form {#6884 …}   -code: "1dafa156-89e1-4736-b832-419c2e501fca"   -cause: TransformationFailedException {#5544 …} }


</body>
</html>

`

**Comment by matks** [comment] 2023-12-07 08:11
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34356

**Closed as completed by matks** 2023-12-07 08:11 UTC
Labels: Bug, Minor, BO, Languages, PR available, Verified, 8.1.x, Products Page
