### ISSUE TITLE
Allowed memory size of 256M exhausted when displaying a product page

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#22679] opened 2021-01-05 17:15 UTC
#### Describe the bug

When I try to display a product in the backoffice (Menu Catalogue - Products, click on *Edit* for any product, I get an error 500 due to *Allowed memory size of 256M exhausted*.
When I raise the memory limit to 1G, the page displays, but the peak memory usage is at 700M.

#### Expected behavior

That much memory just to display a single product seems excessive to me. The limit of 256M seems more reasonable to me.

#### Steps to Reproduce

1. Go to 'Menu Catalogue - Products,'
2. Click on 'Edit' for any product

I have 34k products, maybe this is related to the problem.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by matks** [comment] 2021-01-05 17:22
Hi @lmeyer1 I agree this consumption of memory is excessive but this is not a bug report that we can use to move forward 😢 . Too much memory can come from a lot of settings: installed modules, database size (products? categories? combinations?), images... this is too broad.

We can only do something if bug report is more accurate like "when regular product has image with size X then memory  doubles". Right now there are hundred of possible settings that can be responsible for memory peak.

**Comment by lmeyer1** [comment] 2021-01-06 07:37
You are right. Here is the stacktrace, maybe this gives already some insight. What we can be sure for now is:
 The problem is related to building the form.

Maybe cachegrind may give even more insight. 

The problem is that drilling down such a problem requires *alot* of time.

```
PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 172032 bytes) in Unknown on line 0
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() (...)/lpadmin/index.php:0
PHP message: PHP   2. AppKernel->handle() (...)admin/index.php:82
PHP message: PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle() (...)/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200
PHP message: PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() (...)/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
PHP message: PHP   5. PrestaShopBundle\\Controller\\Admin\\ProductController->formAction() (...)/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151
PHP message: PHP   6. PrestaShopBundle\\Controller\\Admin\\ProductController->createProductForm() (...)/src/PrestaShopBundle/Controller/Admin/ProductController.php:457
PHP message: PHP   7. Symfony\\Component\\Form\\FormBuilder->getForm() (...)/src/PrestaShopBundle/Controller/Admin/ProductController.php:709
PHP message: PHP   8. Symfony\\Component\\Form\\FormBuilder->getForm() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:205
PHP message: PHP   9. Symfony\\Component\\Form\\FormBuilder->resolveChildren() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:199
PHP message: PHP  10. Symfony\\Component\\Form\\FormBuilder->create() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:252
PHP message: PHP  11. Symfony\\Component\\Form\\FormFactory->createNamedBuilder() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:98
PHP message: PHP  12. Symfony\\Component\\Form\\Extension\\DataCollector\\Proxy\\ResolvedTypeDataCollectorProxy->buildForm() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:80
PHP message: PHP  13. Symfony\\Component\\Form\\ResolvedFormType->buildForm() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php:95
PHP message: PHP  14. Symfony\\Component\\Form\\Extension\\Core\\Type\\CollectionType->buildForm() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:126
PHP message: PHP  15. Symfony\\Component\\Form\\FormBuilder->create() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php:39
PHP message: PHP  16. Symfony\\Component\\Form\\FormFactory->createNamedBuilder() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:98
PHP message: PHP  17. Symfony\\Component\\Form\\Extension\\DataCollector\\Proxy\\ResolvedTypeDataCollectorProxy->buildForm() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:80
PHP message: PHP  18. Symfony\\Component\\Form\\ResolvedFormType->buildForm() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php:95
PHP message: PHP  19. PrestaShopBundle\\Form\\Admin\\Product\\ProductSupplierCombination->buildForm() (...)/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:126
PHP message: PHP  20. PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider->getCurrencies() (...)/src/PrestaShopBundle/Form/Admin/Product/ProductSupplierCombination.php:89
PHP message: PHP  21. CurrencyCore::getCurrencies() (...)/src/Adapter/Currency/CurrencyDataProvider.php:68
PHP message: PHP  22. CurrencyCore::addCldrDatasToCurrency() (...)/classes/Currency.php:656
PHP message: PHP  23. Sentry\\ErrorHandler->handleFatalError() (...)/vendor/sentry/sentry/src/ErrorHandler.php:0
PHP message: PHP  24. spl_autoload_call() (...)/vendor/sentry/sentry/src/ErrorHandler.php:304
PHP message: PHP  25. Symfony\\Component\\Debug\\DebugClassLoader->loadClass() (...)/vendor/sentry/sentry/src/ErrorHandler.php:304
', referer: https://fr.test1.ps.sbgmb.net/lpadmin/index.php/sell/catalog/products?_token=Sx_5aCPAkRI9RPYZH8suHMyAjkBp6G-lJ0gkR7FM9LM
```

**Comment by hibatallahAouadni** [comment] 2021-01-06 08:12
Hello @lmeyer1 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #13698. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-06 08:12
Duplicate of #13698

**Closed as completed by hibatallahAouadni** 2021-01-06 08:12 UTC
Labels: Duplicate

**Comment by lmeyer1** [comment] 2021-01-06 09:34
@hibatallahAouadni I'm not sure it is a real duplicate. #13698 is talking about loops and other irregularities in category tree, isn't it ?

**Comment by hibatallahAouadni** [comment] 2021-01-06 09:36
@lmeyer1 This bug occurs when you had a lot of products / categories / features / attributes to load :sweat:
