### ISSUE TITLE
FO - Account - Voucher is not displayed in voucher list if created by a partial refund

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#25237] opened 2021-07-05 13:42 UTC
#### Describe the bug

If during a partial refund we create a voucher instead of a credit slip, the voucher is not displayed in FO in account voucher list

#### Expected behavior

Every voucher available for the customer should be displayed 

#### Steps to Reproduce

1. Go to FO and create an order
2. Go on BO and go to the previously created order detail page
3. Set the status of the order to delivered
4. Make a partial refund for this order
5. During the partial refund creation uncheck the "generate credit slip" option and check the "generate reduction code" option
6. Go to FO / account / voucher list
7. See error => the voucher is not visible ( also not visible in BO in customer detail page but visible in BO in voucher list)

#### Additional information

* PrestaShop version: 178RC1, 177x, 176x
* PHP version: 7.4, 7.3, 7.2, 7.1

**Comment by hibatallahAouadni** [comment] 2021-07-08 08:46
Related to #21556

**Comment by saulaski** [comment] 2022-01-06 15:06
Cannot reproduce the issue in hotfix branch 1.7.8.X.

FO -Vouchers list is OK
![image](https://user-images.githubusercontent.com/97030953/148403232-6f5babbc-6059-4780-bcc0-1aa5a7f7d282.png)

BO - Client vouchers are visible
![image](https://user-images.githubusercontent.com/97030953/148403791-c1a6d4ec-f15f-4623-9630-f6eb9389fefe.png)

BO - Vouchers list is OK
![image](https://user-images.githubusercontent.com/97030953/148403485-a9b7046c-c342-4806-8a9f-1bdef4103f6c.png)

**Comment by saulaski** [comment] 2022-01-06 16:38
Cannot reproduce either in develop and 1.7.7.x

**Comment by hibatallahAouadni** [comment] 2022-01-06 16:56
Hello @saulaski 

Thanks for your testing :pray: 
It seems the issue has been fixed cause I didn't manage to reproduce on PS1778.
Closing the issue :tada: 

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-06 16:56 UTC
Labels: Bug, FO, Discounts, Cart rules, Fixed, 1.7.6.x
