### ISSUE TITLE
getCategories returns a category many times in the multishop context

### ISSUE THREAD

**Issue by guirou62** [PrestaShop/PrestaShop#16787] opened 2019-12-12 10:52 UTC
**Describe the bug**
I needed to use getCategories in a module I created but when I used getCategories, some categories appeared between 1 and 4 times (I'm working on a multishop). To not have this problem and to select only one time categories in my actual shop, I just needed to add a condition : cl.id_shop (because, thanks to LEFT JOIN you made, you can select the language but you can't select the shop if you have the same category on many shops, this categories appears many times)

Maybe, we can make it better by putting shop_id as parameter :)

I created a pull request some weeks ago : https://github.com/PrestaShop/PrestaShop/pull/16035

**Additional information**
PrestaShop version: 1.7.x
PHP version: 7.2.11

**Comment by khouloudbelguith** [comment] 2019-12-12 11:24
Hi @guirou62,

Thanks for your report.
Could you please add steps to reproduce the issue in a new comment.
Is it similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/9821#issuecomment-517601039?

Thanks!

**Comment by guirou62** [comment] 2019-12-12 12:41
Hi @khouloudbelguith 

You're welcome.
Honestly, I don't have any step because I used this function directly in a module I have created. (I wanted a list of every categories in a shop => `$categories = Shop::getCategories($id_shop,false);`)
I think my patch can correct the issue you mentionned

**Comment by khouloudbelguith** [comment] 2019-12-12 12:45
@guirou62, Could you please provide me your custom module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-12 15:34
@guirou62, I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-12 15:43
@guirou62, I don't have duplicated categories for example "clothes"
https://drive.google.com/file/d/1vj5dwMUbwwfmc7zU5VQGyeHmz6r-vjJ6/view

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-13 08:05
Hi @guirou62,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-13 08:05 UTC
Labels: Bug, BO, Categories, Multistore, No change required
