### ISSUE TITLE
ps_customersignin show other customer name in header bar (privacy problem)

### ISSUE THREAD

**Issue by juanjointera5** [PrestaShop/PrestaShop#29685] opened 2022-09-19 10:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

(sorry for my bad english) 

When a customer log in into his account, the header bar created by ps_customersignin show the name of other customer.

We already tried to disable overrides and non native modules, but the problem is not solved.

The only solution is to disable Smarty cache, then things works as expected.

Any idea ?

Thanks and best regards,
Juanjo.

### Expected behavior

Show the current customer name

### Steps to reproduce

1. Create a new account with this data:
-- First name: first
-- Last name: account first
-- email: any email

2. After account creation, the header bar show the correct name: 
![imagen](https://user-images.githubusercontent.com/2895226/191000715-507c3194-ea0c-428a-a907-177de587ed1a.png)

3. Then, logout and create a second account:
-- First name: second
-- Last name: account second
-- email: any other email

4. After account creation, the header bar show the correct name:
![Captura](https://user-images.githubusercontent.com/2895226/191001103-b36fc349-8943-4b3c-ad67-1d1535307e91.JPG)

5. Then, logout, and login in with the *first account*, the header bar display incorrectly the second customer name:
![Captura](https://user-images.githubusercontent.com/2895226/191002269-fa2c9970-711a-4e06-b2ff-cda5df1a526e.JPG)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_customersignin

**Comment by kpodemski** [comment] 2022-09-19 12:47
Do you use any additional cache module, or cache on your server?

**Comment by juanjointera5** [comment] 2022-09-19 12:56
@kpodemski We don't use any additional cache module in the setup.

Looking at the server, I see this extensions installed:
- php74-opcache
- php74-pecl-APCu

which I think are for cache, but I think that we have this type of cache disabled in PS:
![Captura](https://user-images.githubusercontent.com/2895226/191022113-0ba1c11c-d986-440b-afaa-d95bfa1099de.JPG)

Do you think that this extensions are doing an incorrect cache ?

Thanks.

**Comment by hibatallahAouadni** [comment] 2022-09-19 14:19
Hello @juanjointera5 

Could you please disable the cache following the attached screen record below:

https://user-images.githubusercontent.com/23308427/191039414-360bdbfa-b320-4264-9ac9-bc1664b8991a.mp4

Waiting for your feedback.

PS: thanks @kpodemski for your quick reply :rocket: 

Thanks!

**Comment by juanjointera5** [comment] 2022-09-19 14:54
Hello @hibatallahAouadni 

Thanks for your reply (and thanks @kpodemski too!).

Yes, disabling Cache with force recompilation, make all things works as expected.

But, enabling it again, make the glitch appears again, even leaving the "force recompilation" option selected.

We even tried to clean /var/cache directory.

Please, note that disabling the cache makes the correct name to appears when the page is reloaded. Then, enable the cache, reload the page and the wrong name appears again. For some reason, the cache is persistent and never really cleared ?

So, we leave cache disabled for now. Didn't noticed a great performance hit (for now).

Thanks!!

**Comment by hibatallahAouadni** [comment] 2022-09-20 11:12
Hello @juanjointera5 

Unfortunately, I can't hel you anymore cause I couldn't reproduce the issue :disappointed: 
And as you said you can keep the cache disbaled till you find the source of your problem.
Closing the issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-09-20 11:12 UTC
Labels: Bug, FO, Performance, ps_customersignin, Invalid, Module, 1.7.8.7
