### ISSUE TITLE
Orders incorrectly counted in Stats dashboard, wrong payment distribution

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#19708] opened 2020-06-11 06:36 UTC
#### Describe the bug

There are two parts of this issue:
1/ placed orders are recorded based on the latest status change (shipped) instead of on date of order. If you do not ship daily, this will make a mess in your order statistics. Lets say you have two orders per day and your shipping day is Monday. When you select "Time frame" - Daily, you will not see any orders for Tuesday - Sunday, but you'll have 14 orders on the following Monday. Same goes for Monthly time frame, if Monday is the 1st.
The current logic is very unfortunate and no way accurate.

2/ there is a bug related  to currency. As you can see from the printscreen, our total revenue is almost 78K. However on Payment Distribution breakdown, PayPal show 400K which doesn't make sense. The reason being is the fact that some of our customers pay by PayPal in their own currency and the stats module doesn't take that into consideration. The difference can be huge as you can see, especially if customers are in Japan and they pay in Yens. 
We use PayPal by PrestaShop module.

![Stats](https://user-images.githubusercontent.com/31688689/84352582-e5281780-abbd-11ea-9489-231aee5cbf56.png)
![Stats 1](https://user-images.githubusercontent.com/31688689/84352590-e9543500-abbd-11ea-8240-dbb01cec58ba.png)

#### Expected behavior

Orders must be based on date of order + status == shipped.

Exchange PayPal or bank wire transfer payments into local currency.

#### Steps to Reproduce

Described above already.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.31

**Comment by florine2623** [comment] 2020-06-11 15:52
Hi @mrabsinthe ,

1) When last updated Order status is Payment Accepted and/or Shipped, the order is marked as placed. That is the case because, when a customer buys a product from you and uses bank wire payment for example, you won't receive the payment nor send the product until you get the payment from the customer. So that order can't be considered as placed yet.

2) I couldn't reproduce your issue using native payment methods.
In my shop I used JPY and EURO.
_**JPY currency exchange :**_
![Capture d’écran 2020-06-11 à 17 47 28](https://user-images.githubusercontent.com/16019289/84407861-b20c7500-ac0b-11ea-9b19-20df17b31974.png)
**_Price of order in JPY : 4379 JPY_**
![Capture d’écran 2020-06-11 à 17 38 03](https://user-images.githubusercontent.com/16019289/84407891-b9338300-ac0b-11ea-920e-eca5cebc3e3f.png)
**_Results in my sales boards :_**
![Capture d’écran 2020-06-11 à 17 37 38](https://user-images.githubusercontent.com/16019289/84407914-c3ee1800-ac0b-11ea-8466-ca82ac079d7b.png)
![Capture d’écran 2020-06-11 à 17 37 45](https://user-images.githubusercontent.com/16019289/84407934-ca7c8f80-ac0b-11ea-994b-732c48d1fe65.png)

4379 / 121.625541 = **36.00**
40.62 + **36.66** = 76.62

Please check with the developer of the module PayPal. This is not a PrestaShop core issue, so I'll close this issue.

**Closed as completed by florine2623** 2020-06-11 15:52 UTC
Labels: No change required
