### ISSUE TITLE
Cannot get employee from context in consol mode

### ISSUE THREAD

**Issue by ma0dubois** [PrestaShop/PrestaShop#11443] opened 2018-11-20 11:02 UTC
**Cannot get employee from context in consol mode**
When using the Symfony console, I try to install a module from the command: `php bin / console prestashop:module install MYMODULE`

But an error occurs, there is no employee in the context in console mode.
So suddenly in the method "getAdminTokenLite", there is an error.

**To Reproduce**
1. Go to in console mode with: `php bin / console`
2. Use the module install command: `php bin / console prestashop:module install MYMODULE`
4. See error:

![screenshot](https://i.imgur.com/ptP686A.png)

**Screenshots**
![screenshot](https://i.imgur.com/uSouzQO.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1.23

**Comment by khouloudbelguith** [comment] 2018-11-21 08:34
HI @ma0dubois,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1te6El6r2aU-2PP-EtwlChoBsf39KT6jC/view
You can follow this [documentation](https://devdocs.prestashop.com/1.7/modules/testing/)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2018-12-21 14:02
Hi @ma0dubois,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-21 14:02 UTC
Labels: Modules, No change required, 1.7.4.3
