### ISSUE TITLE
 prestashop communication problem with email, and store via contact us also does not communicate with prestashop

### ISSUE THREAD

**Issue by alexweissweiss** [PrestaShop/PrestaShop#17899] opened 2020-02-29 15:13 UTC
#### Describe the bug

when i open the page talk to us, and i need to send a message to the support or webmaster, this process is not finalized due to an error.
The message is not sent. It does not appear in the back office. On the other hand, through the back office, I can't send a message or email to my client either. It doesn’t reach him on the website under my account tab, much less in his email.
There is no communication between these sectors.

imap settings don't work because my server (Umbler) doesn't have them.
Smtp are configured but still have no effect and prestashop is unable to receive or send emails.

#### Expected behavior

The message was to go from contact us from the store to the prestashop back-office. And the answer is to leave the back-office and arrive at the customer both in his email and at the website store.

#### Steps to Reproduce

1. Go to 'end of the page click on contact us. Note: language is Brazil'
2. Click on '
describe a "test" problem and click send message.'
3. Scroll up to '
a message will appear in red above that the action cannot be completed
'

**Screenshots**

![suporte3](https://user-images.githubusercontent.com/61602988/75609975-fd32ca00-5aeb-11ea-927e-ef70a4c519aa.JPG)
![suporte1](https://user-images.githubusercontent.com/61602988/75609981-0cb21300-5aec-11ea-8a7d-f29d305257e2.JPG)
![suporte2](https://user-images.githubusercontent.com/61602988/75609982-0fad0380-5aec-11ea-9c5e-a0ea15d755c7.JPG)

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version:  7.0.16

**Comment by alexweissweiss** [comment] 2020-02-29 15:19
site:  https://www.shoppingdoestudante.com

**Comment by khouloudbelguith** [comment] 2020-03-02 08:24
Hi @alexweissweiss,

Your ticket is a duplicate of #9566
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-02 08:24
Duplicate of #9566

**Closed as completed by khouloudbelguith** 2020-03-02 08:24 UTC
Labels: Duplicate
