### ISSUE TITLE
BO - Shipping - Toggle button of Add handling costs is not well displayed

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26694] opened 2021-11-21 13:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Toggle button of Add handling costs is not displayed when it is disabled in the step shipping location and costs on the branch develop , 1.7.8.0
![image](https://user-images.githubusercontent.com/89604350/142763766-3936548e-8969-44a7-b9f3-354fa38dce02.png)
https://watch.screencastify.com/v/FCr9t3ftvN6dpbf8ycH3
For 1.7.7.8 the button toggle button was  displayed correctly
![image](https://user-images.githubusercontent.com/89604350/142763829-330e7f2b-8d59-4de5-8bf2-3ca6b06bbc80.png)

### Expected behavior

Toggle button of Add handling costs should be displayed correctly.

### Steps to reproduce

1. GO to BO > shipping > carriers > Add new carrier
2. set a Carrier name and transit time > next
3. In the step shipping locations and costs set free shipping to yes
4. the toggle button of Add handling costs is not displayed anymore

### PrestaShop version(s) where the bug happened

develop/1.7.8.0

### PHP version(s) where the bug happened

7.3/7.2

**Comment by Progi1984** [comment] 2022-01-06 16:29
@marwachelly It seems it's not a bug anymore. As discussed with @NeOMakinG, it has been redesigned in version 1780 with the style of the UI Kit : https://build.prestashop.com/prestashop-ui-kit/?path=/story/forms--switch-story.

**Comment by PierreRambaud** [comment] 2022-01-21 09:24
ping @marwachelly

**Comment by MatShir** [comment] 2022-01-21 18:50
That is right, you can't add additional cost if the carrier is set as free. I'm closing this issue, don't hesitate to open it again if needed ;)

**Closed as completed by MatShir** 2022-01-21 18:50 UTC
Labels: Bug, Trivial, FO, Shipping, Regression, Front-end, 1.7.8.0, Invalid
