### ISSUE TITLE
Allow to select modules to install during store installation

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26589] opened 2021-11-12 12:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The problem is every new shop installs modules I don't need and I'm forced to uninstall them after store installation is complete. Examples of such modules would be Gamification (which is useless to me and my clients) and Cheque (which is not used in my country).

### Describe the solution you'd like

It would be best to allow module selection during store installation, just like it was with theme activation on Prestashop 1.6, where you could pick modules to install/uninstall/enable/disable. Although it never worked 100% as expected :p

![obraz](https://user-images.githubusercontent.com/5007456/141469650-4a4f9f60-ef0e-4c5c-847a-d08a1d6b4112.png)

**Comment by hibatallahAouadni** [comment] 2021-11-12 16:31
Hello @SharakPL 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by PierreRambaud** [comment] 2021-11-24 15:10
Duplicate of #24644

**Comment by hibatallahAouadni** [comment] 2021-11-24 15:54
Hello @SharakPL 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24644. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @PierreRambaud :superhero: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-11-24 15:54 UTC
Labels: Feature, IN, Duplicate, Modules, Invalid
