### ISSUE TITLE
Filtering products with color combination should show search results with default color combination image

### ISSUE THREAD

**Issue by grigorevlad** [PrestaShop/PrestaShop#12932] opened 2019-03-15 07:38 UTC
**Is your feature request related to a problem? Please describe.**

When filtering through products using color combination, if i select color "BLUE" for example the filtered products should show default  image for that combination. 

Right now if the default image of a product is for "RED" color combination, but it also has "BLUE" combination available with different combination pictures, when i select color "BLUE" from product list filter then i still see the default red combination pictures in search results. 

![Untitled](https://user-images.githubusercontent.com/8983330/54415718-ca8a9880-4705-11e9-8993-a69e7851869d.jpg)

It is a bit confusing for customer to select a color for products. The search results should show the default image for filtered products.

PS 1.7.5.1

**Comment by khouloudbelguith** [comment] 2019-03-15 07:46
Hi @grigorevlad,

Your ticket is a duplicate of #12501
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-15 07:46
Duplicate of #12501

**Closed as completed by khouloudbelguith** 2019-03-15 07:46 UTC
Labels: Duplicate
