### ISSUE TITLE
Problem module mail alert

### ISSUE THREAD

**Issue by 2TEND** [PrestaShop/PrestaShop#11778] opened 2018-12-14 10:08 UTC
Je ne recois plus aucun mail d alerte de commande du jour au lendemain sans avoir rien toucher

**Comment by khouloudbelguith** [comment] 2018-12-14 10:19
Hi @2TEND,

Thanks for your report.
Could you please try to navigate to your BO => CONFIGURE => Advanced Parameters => E-mail => TEST YOUR EMAIL CONFIGURATION by sending a test email.
What is the exact version PrestaShop did you use & what the exact version of the mailalert did you installed?
Thanks to check and feedback.

**Comment by 2TEND** [comment] 2018-12-14 11:59
I receipt The Mail Test when i do this. But not when a customers make an
order.



Le ven. 14 déc. 2018 à 11:19, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2018-12-14 13:45
@2TEND, in your configuration page of the mailalert module, the "New order" option is enabled?
If yes, could you please try to unistall the mailalert module, remove the mailalert folder from your Project_Folder/modules/mailalert path, try to install it again, check & feedback.

**Comment by 2TEND** [comment] 2018-12-14 13:49
Yes i already do mal this. Uninstall and install. Configuration or module
is good. I just disable for out of stock.

Le ven. 14 déc. 2018 à 14:45, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2018-12-14 13:57
@2TEND, with Mail alerts v2.1.0 - by PrestaShop, I disabled "out of stock" option & I enabled the "New order" option, & it is ok, I receive an email when new order created.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-21 10:34
Hi @2TEND,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by 2TEND** [comment] 2019-01-21 10:35
Never working...

Le 21 janv. 2019 11:35 AM, "khouloudbelguith" <notifications@github.com> a
écrit :

Closed #11778 <https://github.com/PrestaShop/PrestaShop/issues/11778>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PrestaShop/PrestaShop/issues/11778#event-2086023074>,
or mute the thread

**Comment by khouloudbelguith** [comment] 2019-01-21 10:38
Hi @2TEND,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-19 07:49
Hi @2TEND,

Without more information, I will close your issue soon.
So, any news? We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks for your understanding!

**Comment by 2TEND** [comment] 2019-02-19 07:53
I've maiking all that you are say. And the module don't working..

**Comment by khouloudbelguith** [comment] 2019-02-19 07:55
@2TEND, did you sent me an email? with this informations?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-21 07:49
Hi @2TEND,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-21 07:49 UTC
Labels: No change required, ps_emailalerts
