### ISSUE TITLE
Error 500 Regenerate images multi-store

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#16544] opened 2019-11-26 10:51 UTC
I get an error 500 when I am trying to regenerate images even after activated debug mod, I am unable to check where the error comes from. Mult-store is activated and this is probably the cause.

1. Enable Multi-store
2. Try to regenerate all the images

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.1 (I am using Smartblog module so I cannot upgrade PHP)

**Comment by khouloudbelguith** [comment] 2019-11-26 11:01
Hi @Dupflo,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Dupflo** [comment] 2019-11-26 19:58
![image](https://user-images.githubusercontent.com/39828779/69667998-545d7480-108f-11ea-88c7-9541ccc6b4bf.png)
![image](https://user-images.githubusercontent.com/39828779/69668051-6ccd8f00-108f-11ea-819f-94a32529185a.png)

**Comment by khouloudbelguith** [comment] 2019-11-27 08:33
@Dupflo, the memory_limit in your case is -1, this is invalid.
The `memory_limit` must be to a minimum of 256M.
Thanks to increase it in the PHP's config, check & feedback.

**Comment by Dupflo** [comment] 2019-11-28 10:06
@khouloudbelguith unfortunately it did not work

**Comment by khouloudbelguith** [comment] 2019-11-28 10:07
@Dupflo, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Dupflo** [comment] 2019-11-28 11:00
@khouloudbelguith problem is I still have Error 500 even on debug mod

**Comment by khouloudbelguith** [comment] 2019-11-28 11:05
@Dupflo, 
In my case, it is Ok.
https://drive.google.com/file/d/1VR_Fmc9TlC6xlkJxf6QqrH96csSIw9Io/view

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.

Any errors in your file log?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-31 07:50
Hi @Dupflo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-31 07:50 UTC
Labels: Bug, BO, Image, Multistore, No change required, 1.7.6.1
