### ISSUE TITLE
Product listed as "New" but without flag

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#27737] opened 2022-02-19 08:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

New products in `/new-products` front controller appears without "NEW" flag:

![image](https://user-images.githubusercontent.com/15104724/154793417-7cb1f4ae-6af6-4018-8f45-5fa532377370.png)

### Expected behavior

All "new products" should appear with "NEW" flag

### Steps to reproduce

1. Open `https://domain/new-products`
2. Check that all products have "NEW" flag
3. Edit `date_add` from table `ps_product_shop` from some product, and set a date 20 days before today. For example, from 19/02 to 30/01.
4. Refresh `https://domain/new-products`
5. Check that the product edited in step 3 is listed but wihtout "NEW" flag

_* If the product edited in step 3 doesn't appear, set the following day. If the product is listed with "NEW" flag, set a previous day. There's only one day difference to reproduce the issue._

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment] 2022-02-19 09:26
You need to also edit ps_product, just to be sure to not produce any incosistencies.

**Comment by hibatallahAouadni** [comment] 2022-02-21 09:50
Hello @idnovate 

I reproduce the issue with PS1783, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/154926582-638fc486-d946-462e-a055-1f70a6bfd5fe.png)

I have products created on 01-02-2022 that are listed in the `/new-products` list but without a flag:

![image](https://user-images.githubusercontent.com/23308427/154926756-59b9c77c-4775-49c4-b08c-9009e6d80373.png)

While with PS1778, these products are not displayed in the list:

![image](https://user-images.githubusercontent.com/23308427/154930245-f4e506cb-27b4-4064-baa5-07d96b73a555.png)

![image](https://user-images.githubusercontent.com/23308427/154929584-ccd41930-b57f-48f6-93da-72ef2ada2656.png)

So, it's a regression! ’ll add this to the debug backlog so that it’s fixed.
And thanks for your PR :rocket: 

Thank you

**Comment by hibatallahAouadni** [comment] 2022-02-21 10:25
PS: I have a weird behavior with PS1780, same process but not same result:

![image](https://user-images.githubusercontent.com/23308427/154936297-8ed5d90e-e1c2-4313-a488-ddaf2899edb3.png)

![image](https://user-images.githubusercontent.com/23308427/154936267-52cc3f09-0e3b-4b3f-aba4-1a53d90f43a4.png)

It looks like this was not completely fixed with PS1783 :sweat_smile:

**Comment by MatShir** [comment] 2022-02-21 16:42
I'm not sure of the bug:
- Is the product not supposed to be displayed in the FO if we compare to the previous versions ?
or
- Is  the flag forgotten ?

**Comment by Hlavtox** [comment] 2022-02-21 16:45
@MatShir The bug is just that the **condition to display the New flag itself** versus the **condition to show product on that page** are not the same. Somebody didn't check the edge cases.

**Comment by matks** [comment] 2022-05-12 12:46
Fixed

**Closed as completed by matks** 2022-05-12 12:46 UTC
Labels: Bug, Minor, FO, Regression, Fixed, PR available, Verified, 1.7.8.3
