### ISSUE TITLE
Problem with category positions

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#15539] opened 2019-09-14 11:37 UTC
Hello, I have problems setting the correct position of the subcategories. When I set the position in BO and enter the category the subcategories are in random positions. I have problems to move them to the position I like. Please, take a look at this video: https://drive.google.com/file/d/1R26lFnVCErDmtoJfaGEQfTbZ611P8iLV/view

When I made that video the problem occured only on main shop but in most cases (when there are more subcategories) the problem occurs in all shops. Is there a way to solve it? I have PS 1.7.6.0.

**Comment by mariem-abid** [comment] 2019-09-16 09:21
Hi @banan44,

I did not manage to reproduce the issue with PS:1.7.6.1.
I attached a video record.
https://drive.google.com/file/d/1ppWLCRjHvi-vIKuxUC7VZ7xMhIhZYD32/view

Thanks for check and feedback.

**Comment by banan44** [comment] 2019-09-27 22:05
Hi @mariem-abid no change after update. I have notice I have this problem only with categories where the position of subcategories does not start with 1. Check the screenshot below. The first subcategory starts with 3 instead of 1. Once I move one subcategory, the numbers refresh and when I refresh the page, the positions are correct, start with number 1 and when I move any subcategory to a different place it stays there. I do not know why some subcategories start with number 2 or 3 instead of 1. 

![Bez tytułu](https://user-images.githubusercontent.com/48493952/65804755-42408200-e183-11e9-85dd-048c56ecf47a.png)

**Comment by khouloudbelguith** [comment] 2019-09-30 14:37
Hi @banan44,

The problem of the positions is fixed in the PS1.7.7.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14529 to fix the issue.
Your ticket is a duplicate of #14504
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-30 14:37
Duplicate of #14504

**Closed as completed by khouloudbelguith** 2019-09-30 14:37 UTC
Labels: Duplicate, Categories, Multistore, 1.7.6.0
