### ISSUE TITLE
Changing method signature breaks override

### ISSUE THREAD

**Issue by BrunoJunior** [PrestaShop/PrestaShop#25074] opened 2021-06-22 08:44 UTC
#### Describe the bug
Since 1.7.5.5, the method «checkValidity» in «CartRule« has a new parameter.
In PHP, overrides HAS TO respect the parent signature.
If I have a module which override the method PHP, I get a ContextErrorException …
This problem is fully technical...

#### Expected behavior
I thought changing signatures is unauthorized between two minor version (1.7.7.4 -> 1.7.7.5)
It should be another method with new parameter and the old one call the new one with a default value …

#### Steps to Reproduce
Create a simple module wich override the method checkValidity with the 1.7.7.4 signature.
When product is added to a cart, this method should be called (with an error, in 1.7.7.5)

**Screenshots**

![image](https://user-images.githubusercontent.com/4368255/122892948-26f9ab00-d346-11eb-9f22-b48243fe4a40.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3.27

**Comment by florine2623** [comment] 2021-06-22 08:58
Hello @BrunoJunior ,

Could you send a module example so we can reproduce the issue on our end ?
Thanks!

**Comment by matks** [comment] 2021-06-22 08:59
Hi @BrunoJunior this is very interesting

> I thought changing signatures is unauthorized between two minor version (1.7.7.4 -> 1.7.7.5)

This is not right. What is forbidden between 2 patch versions (and minor versions theoretically) is to introduce backward incompatible changes. In this topic, the new parameter has been added with a default value
```
public function checkValidity(Context $context, $alreadyInCart = false, $display_error = true, $check_carrier = true, $useOrderPrices = false)
```
So in 1.7.7.5 it's possible to run a php statement `$myRule->checkValidity($context, false, true, true);` without errors thanks to the `$useOrderPrices` default value. This is a backward-compatible change and is authorized.

This works when you _use_ the php code provided by PrestaShop, our public API, which is under contract by SemVer. But here what you do is _override_ the php code and this is a concept specific to PrestaShop and unknown by SemVer.

To be fair this is the very first time someone mentions this issue and it's great 😄  it opens the question "Should PrestaShop guarantee overrides continuous behavior in patch and minor versions"?

I'm afraid however the answer will be no because this would freeze our capability to change too much* but I can't decide alone. wdyt @PrestaShop/prestashop-maintainers 

*Freezing our capacity to change is dangerous because change is needed for new features, bug fixes, refactoring.

**Comment by kpodemski** [comment] 2021-06-22 10:34
Unfortunately, this is one of many downsides when you use overrides, and I'm afraid versioning has nothing to do with it. 

If you have modules using overrides I suggest creating a mechanism where you can create a specific override file, for a specific version of PrestaShop, I have something like this:

![image](https://user-images.githubusercontent.com/2137763/122909665-b65a8a80-d355-11eb-8ae2-9d8ab802274e.png)

as you can see there's a `base` override for `Cart.php`, and one specific file when a user is using `PrestaShop >= 1.7.7.1`

In my `Module::install()` method I'm moving a proper file to the `override/` folder to make sure it's installed.

Of course the problem is when a user is updating PrestaShop from 1.7.6 to for example 1.7.7.5, in that case, there are two options I see:
- checking installed overrides in `__construct()`
- checking installed overrides on demand

**Comment by BrunoJunior** [comment] 2021-06-23 11:01
I understand all technical answers.
Even if I'm the developper of the module, I can't know when my module will break except to test it for each new PrestaShop version. (and I don't have enough time for that, and I have not any automated tests. Because I do not know how to implement such tests when I develop PrestaShop module …)
Another question though, if I define, in my module, a compatibility with v1.7.7.4 max. What does it happen when the seller try to update its PrestaShop ? Does PrestaShop updater refuses to upgrade because of the module incompatibility ?
My first idea was to do 2 differents branches of my module …
1 compatible until 1.7.7.4 (incl.)
1 compatible since 1.7.7.5.

What do you think of this approach ?

**Comment by BrunoJunior** [comment] 2021-06-23 13:54
I would like to add a complementary comment.
The role of my override is to add a hook before the validity checking …
To potentially avoid the activation of the cart rule in certain conditions.
A cool workaround will be to have a PrestaShop hook in the original method …

**Comment by kpodemski** [comment] 2021-06-24 07:22
@BrunoJunior feel free to submit PR with a hook you'd like to see in this method 👍 

More details: https://devdocs.prestashop.com/1.7/contribute/

> Another question though, if I define, in my module, a compatibility with v1.7.7.4 max. What does it happen when the seller try to update its PrestaShop ? Does PrestaShop updater refuses to upgrade because of the module incompatibility ?

It's something for you to test, but I'm pretty sure it's not working this way, it's for an installation process

> Even if I'm the developper of the module, I can't know when my module will break except to test it for each new PrestaShop version. (and I don't have enough time for that, and I have not any automated tests. Because I do not know how to implement such tests when I develop PrestaShop module …)

It all depends if your modules are paid ones, or free. If paid, our job as module developers is to make sure that our module is working properly. 

It's really hard for PrestaShop to think about every single scenario. I understand that it's sometimes frustrating to update the module from version to version, but these changes are related to some bugs that needed to be fixed.

**Comment by hibatallahAouadni** [comment] 2021-07-14 10:16
Hello @BrunoJunior 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: keep in mind that we can always reopen the issue :wink: so when you provide a simple module to reproduce the issue or you provide a PR, ping me :slightly_smiling_face: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-14 10:16 UTC
Labels: Bug, CO, Cart rules, No change required, Developer Feature, 1.7.7.4, 1.7.7.5
