### ISSUE TITLE
Bug when set other delivery option in order via admin panel

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#23389] opened 2021-02-24 14:14 UTC
#### Describe the bug

I started changing the delivery in the order through the admin panel and noticed that the delivery price was calculated incorrectly

#### Steps to Reproduce

1. Make carrier with range 0 to 100 price 50, range 100 to 100500 price 0
2. Make product with combination, price product 20, impact of price + 200 for example
3. Add product in cart, to make order
4. Go to admin panel in maked order, change delivery option on other method and now need back to old delivery option.
5. Now you can to look, what price stay 50 instead 0

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-24 15:33
Hello @dariusakafest 

I didn't manage to reproduce your issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1Zkr20WfVYZ8VoTfUuXl7GI4s14ngNFyX/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-16 17:11
Hello @dariusakafest ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-16 17:11 UTC
Labels: Bug, BO, Order, Carriers, No change required, PR available, 1.7.6.5, 1.7.7.2
