### ISSUE TITLE
Inifnity loop after changed shop_url

### ISSUE THREAD

**Issue by tdzierza** [PrestaShop/PrestaShop#27906] opened 2022-03-15 09:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

$ wget example.com
--2022-03-15 10:06:52--  http://example.com/
Translacja example.com (example.com)... x.x.x.x
Łączenie się z example.com (example.com)|x.x.x.x|:80... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 301 Moved Permanently
Lokalizacja: https://example.com/ [podążanie]
--2022-03-15 10:06:52--  https://example.com/
Łączenie się z example.coml (example.com)|x.x.x.x|:443... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 301 Moved Permanently
Lokalizacja: http://example.com/ [podążanie]

At the beginning prestashop was installed in localhost.
After changed ps_shop_url infinity loop appearing. 
From http to https and https to http
After ps_shop_url changed also .htaccess was updated from localhost to source domain

Back office working well - I can change configuration without issue
What I did:
1. Turn off all caching
2. Clear temporary files
3. Set SSL to on - cetificate works ok, also let encrypt run witkout issues
4. Turn on mulitstore - thought that somehow update files inside prestashop
5. Turn off inside SEO & web option Move 302 - after this change website loading without redirection but aldo without styles

### Steps to reproduce

Run website

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by marwachelly** [comment] 2022-03-15 13:54
Hello,

Thank you for your report. Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/17095? If not could you please provide a screen record to reproduce the issue. Waiting for your feedback.

Thanks,

**Comment by hibatallahAouadni** [comment] 2022-04-04 11:15
Hello @tdzierza 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-04-04 11:15 UTC
Labels: Bug, BO, Multistore, SEO & URLs, Invalid
