### ISSUE TITLE
Wrong discount on total cart

### ISSUE THREAD

**Issue by TristanPapillon** [PrestaShop/PrestaShop#18274] opened 2020-03-23 16:09 UTC
#### Describe the bug

The subtraction of the discount is incorrect on the total of the cart.
There is a difference of 1 centime on total if amount discount is more than 2 decimals and end by '5' (and maybe other cases).

I think it's *just* a rounded problem.

#### Expected behavior

18,90 - 2,84 = 16,06

#### Steps to Reproduce

1. BO: Create a new product :
Quantity : 1
Unit price with taxes : 18,90
Enable and save it

2. BO: Create a new cart rule :
15% discount on whole cart

3. FO: Add this product to cart
4. FO: Add discount code

**Screenshots**

![screenshot-cart](https://user-images.githubusercontent.com/5691529/77333103-3ba25a00-6d23-11ea-98a0-e310b2e19519.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29

#### Fix suggested

Round the calculated amount from percent in

src/Core/Cart/CartRow.php

```
    public function applyPercentageDiscount($percent)
    {
        $tools = new Tools();
        $percent = (float) $percent;
        if ($percent < 0 || $percent > 100) {
            throw new \Exception('Invalid percentage discount given: ' . $percent);
        }
        $discountTaxIncluded = $tools->round($this->finalTotalPrice->getTaxIncluded() * $percent / 100, $this->precision);
        $discountTaxExcluded = $tools->round($this->finalTotalPrice->getTaxExcluded() * $percent / 100, $this->precision);
        $amount = new AmountImmutable($discountTaxIncluded, $discountTaxExcluded);
        $this->applyFlatDiscount($amount);

        return $amount;
    }
```

![screeshort-cart-fix](https://user-images.githubusercontent.com/5691529/77337125-c20d6a80-6d28-11ea-9e09-6541fe70ad0a.png)

I'm not a PrestaShop expert..., i don't known if it's the best solution but it seems working on tests environment.

**Comment by khouloudbelguith** [comment] 2020-03-23 16:18
Hi @TristanPapillon,

We are aware of the Rounding issue.
Your ticket is a duplicate of #9779
You can also follow these issues: #9981 & #9815 & #17045 & https://github.com/PrestaShop/PrestaShop/issues/17161
So, I close it.

PS: 
 If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-23 16:18
Duplicate of #9779

**Closed as completed by khouloudbelguith** 2020-03-23 16:18 UTC
Labels: Duplicate
