### ISSUE TITLE
No access to Prestashop back office

### ISSUE THREAD

**Issue by DCL34** [PrestaShop/PrestaShop#13523] opened 2019-04-23 09:36 UTC
Hi, 

I have no access to the back office of my shop (error 500) since I changed the access password to the database. I made no change in the database.  

I wrote the new password in the app/config/parameters.php but it still failed.

Anyone have an idea ? 

Best Regards, 

DCL34. 

PrestaShop version: 1.7.5.1

**Comment by khouloudbelguith** [comment] 2019-04-23 09:43
Hi @DCL34,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matks** [comment] 2019-04-23 09:56
Hi @DCL34 parameters such as database passwords are put in a cache file, as you can see in https://github.com/PrestaShop/PrestaShop/blob/develop/config/bootstrap.php#L73

Check your cache file is up-to-date.

**Comment by DCL34** [comment] 2019-04-23 14:07
Thank you for your feedback ! Sorry, I don't understand how to get this informations you want.

**Comment by khouloudbelguith** [comment] 2019-04-23 14:09
@DCL34, if you don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-23 07:52
Hi @DCL34,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-23 07:52 UTC
Labels: BO, No change required, 1.7.5.1
