### ISSUE TITLE
Manufacturer BO error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'position' in 'order clause'

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#15058] opened 2019-08-09 14:46 UTC
Hi Gitters :)

I've done a manual migration from Prestashop 1.7.5.1 to 1.7.6.0 by the best of my knowledge. After migrating selected tables according to procedure by avoiding theses tables (ps_access, ps_configuration, ps_currency, ps_lang, ps_module_access, ps_tab and ps_tab_lang), i import the databases tables on a fresh 1.7.6 store with the same modules and employees configurations, same languages, default language, etc.

Everything was working has expeted except with another error which i fix [with this fix on post](https://github.com/PrestaShop/PrestaShop/issues/14617#issuecomment-511737940).

Now, i check each Back Office links to be sure that everything works, and i found that issue when i click on Manufactuer & Supplier section.

`An exception occurred while executing 'SELECT m.`id_manufacturer`, m.`name`, m.`active`, COUNT(p.`id_product`) AS `products_count`, (SELECT COUNT(a.`id_manufacturer`) AS `addresses_count` FROM ps_address a WHERE (m.`id_manufacturer` = a.`id_manufacturer`) AND (a.`deleted` = 0) GROUP BY a.`id_manufacturer`) AS addresses_count FROM ps_manufacturer m INNER JOIN ps_manufacturer_shop ms ON ms.`id_manufacturer` = m.`id_manufacturer` LEFT JOIN ps_product p ON m.`id_manufacturer` = p.`id_manufacturer` WHERE ms.`id_shop` IN (?) GROUP BY m.`id_manufacturer` ORDER BY position asc LIMIT 50 OFFSET 0' with params [1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'position' in 'order clause'`

See also screenshots:
![2019-08-09_10h32_45](https://user-images.githubusercontent.com/16780421/62787391-9f2c8f80-ba92-11e9-8806-43e28e18a100.png)

![2019-08-09_10h44_28](https://user-images.githubusercontent.com/16780421/62787414-aa7fbb00-ba92-11e9-9376-5a4bc50e281b.png)

**Additional information**
PrestaShop version: 1.7.6 migrated from 1.7.5.1
PHP version: 7.2.21

Please, also if other tables are differents on the version 1.7.6 compare to 1.7.5.1 i will need also the fixes too. Im pretty sure i will find other back office url that will need updates.

Thanks,
8ternity, because we don't have the eternity to fix it.

**Comment by khouloudbelguith** [comment] 2019-08-09 16:13
Hi @8ternity,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14620 to fix the issue.
Your ticket is a duplicate of #14617
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-09 16:13
Duplicate of #14617

**Closed as completed by khouloudbelguith** 2019-08-09 16:13 UTC
Labels: Duplicate

**Comment by 8ternity** [comment] 2019-08-09 17:24
No it's not a dipplicate, i already made this fix #14617. I already apply this fix.

> Everything was working has expeted except with another error which i fix with this fix on post.

**Comment by khouloudbelguith** [comment] 2019-08-22 12:36
@8ternity, did you create a release from the PR? then did  you make an upgrade?

Thanks!
