### ISSUE TITLE
BO - We can create a new customer successfully without setting required field "Partner offers"

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17817] opened 2020-02-25 10:28 UTC
**Describe the bug**
We can create from the BO a new customer successfully without setting required field "Partner offers"
![image](https://user-images.githubusercontent.com/16067358/75238651-a82c4680-57c1-11ea-8180-88faf3dd824f.png)

**To Reproduce**
1. Go to BO => Customers => Click on  Set required fields for this section
2. Check the "Partner offers" option
3. Save
4. Create a new customer from BO without enabling Partner offers => the customer is successfully saved => NOK
We should have a red alert like in the last previous version PrestaShop
 
![image](https://user-images.githubusercontent.com/16067358/75238496-60a5ba80-57c1-11ea-8220-ed556383f67d.png)

**Additionnal information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-02-25 10:31
This issue is fixed previously in the PS1.7.6.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/13887

It is ok with PS1.7.6.0 and PS1.7.6.1 and PS1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-02-25 10:33
Ping @nesrineabdmouleh

**Comment by colinegin** [comment] 2020-02-26 10:10
We need to check what happened in 1763 which introduced this bug again.

**Comment by matks** [comment] 2020-02-26 10:21
It seems this is because of PR https://github.com/PrestaShop/PrestaShop/pull/16648 which fixed issue https://github.com/PrestaShop/PrestaShop/issues/16509 (milestone 1.7.6.3)

**Comment by matks** [comment] 2020-02-26 16:24
@colinegin There is a misunderstanding here.

**When I look into the code**, I can see that, when we create a customer, **we check whether or not in the form the "required field"s have been given to the BO admin** and indeed it works.

**Setting a field to "required" means "we require the BO admin to fill this field".**

There is a misunderstanding on "what is a required field".
- 1st version: "A required field must be filled in by the user" (so the opposite is an optional field). For example "birthday" input, on customer form, is optional. You can fill it with a date or leave it blank.
- 2nd version: "A required field must be provided with a valid value" (= for a checkbox, it must be checked).

In the legacy code from the BO I can see the check `ObjectModel::validateFieldsRequiredDatabase()` and it uses 1st version. So when we submit customer form, it sees the checkbox and consider that leaving it empty is valid. A checkbox is always filled in, it's either checked or unchecked. It's not like a text input (= you need to fill it) or a dropdown (=you need to select a choice).

This issue description considers that a "required" field is rather the 2nd version, and then it seems to be different from legacy behavior (according to the code).

**Comment by colinegin** [comment] 2020-02-28 10:14
As I can see, there is a different meaning in what "required fields" means between the address page and the customer page. When looking at the [user documentation](http://doc.prestashop.com/display/PS17/your+customers)(1.6 and 1.7), it seems that putting an optin as required means that it has to be checked to be able to create a customer account. 

> Below the customers table is the "Set required fields for this section" button. It opens a form where you can indicate if a database field is necessary or not by checking the appropriate boxes: this way, you can make it so fields such "partner offers" are mandatory when a visitor is creating a customer account on your shop.

So I would recommend to go for option 2 in the customer page and keep the legacy behaviour in the address page. Is this ok for you @matks ?

**Comment by colinegin** [comment] 2020-02-28 13:35
Hello @khouloudbelguith ,

After investigation, it seems that it is actually the expected behaviour that we decided on 1763 as you can see in my comment here : https://github.com/PrestaShop/PrestaShop/issues/16509#issuecomment-561768934. 

Although the field is required we want to give the possibility to the merchant to create or edit an account and leave the optin unchecked. 

So we won't fix this issue, and we need to update automated tests accordingly. 
ping @boubkerbribri @SimonGrn

**Closed as completed by colinegin** 2020-02-28 13:35 UTC
Labels: Bug, Minor, BO, Won't fix, Customer, Regression, migration, Detected by TE, 1.7.6.3
