### ISSUE TITLE
Problem with ps_facetedsearch checkbox when click more than one

### ISSUE THREAD

**Issue by Jess-87** [PrestaShop/PrestaShop#36654] opened 2024-08-01 10:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I am experiencing a problem with the ps_facetedsearch module on my PrestaShop 8.0.1 store. Specifically, when using the size filters, the checkboxes are not functioning as expected. If I select one size and then select another, the first selection gets canceled, leaving only the last one selected.

I have reviewed the module settings, but I could not find any options to change this behavior. Additionally, I checked the error logs and found nothing relevant. Could you please assist me in resolving this issue?

Thank you,

### Steps to reproduce

Go to category page in the web and If I select one size and then select another, the first selection gets canceled, leaving only the last one selected.

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.28

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.16.1

**Comment by paulnoelcholot** [comment] 2024-08-07 08:17
Hello @Jess-87,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

![image](https://github.com/user-attachments/assets/cb252e39-ce1b-446b-8c85-b0f750e75239)

**Closed as completed by paulnoelcholot** 2024-08-07 08:17 UTC
Labels: Bug, Can't reproduce
