### ISSUE TITLE
Variable severityMessage / error 500 in Back Office Log 

### ISSUE THREAD

**Issue by BertiauxM** [PrestaShop/PrestaShop#24507] opened 2021-05-14 14:51 UTC
Hello
I have a 500 error when I want to access my back office
in debug mode I can go anywhere except on the "log" where I have this error message 

**Screenshots**
![image](https://user-images.githubusercontent.com/84187107/118288240-82798300-b4d4-11eb-9dcd-ae3fecc240ad.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by matks** [comment] 2021-05-14 15:10
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/23588 and fixed in https://github.com/PrestaShop/PrestaShop/pull/23856 for 1.7.8.0

**Comment by florine2623** [comment] 2021-05-14 15:35
Hello @BertiauxM ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23588.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by florine2623** [comment] 2021-05-14 15:36
Duplicate of #23588

**Closed as completed by florine2623** 2021-05-14 15:36 UTC
Labels: Duplicate
