### ISSUE TITLE
1.7.5.1 to 1.7.6.4  SmartyException

### ISSUE THREAD

**Issue by LGx0** [PrestaShop/PrestaShop#18059] opened 2020-03-09 13:55 UTC
#### Describe the bug

(1/1) SmartyException0():Missing '$template' parameter
--
in smarty_internal_templatebase.php line 177
at Smarty_Internal_TemplateBase->_execute(null, null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch(null, null, 'layouts/layout-full-width.tpl')in FrontController.php line 683
at FrontControllerCore->smartyOutputContent(null)in FrontController.php line 667
at FrontControllerCore->display()in Controller.php line 312
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

No matter which version of php I use, the error remains
7.1, or 7.2, or 7.3

#### Expected behavior

Working

#### Additional information

* PrestaShop version: 1.7.6.4
Server information Linux #1139549 SMP Mon Mar 2 08:31:47 UTC 2020 x86_64
Server software version: Apache/2.4.25 (Debian)
PHP version: 7.2.28-4+0~20200224.38+debian9~1.gbp1ca010
Memory limit: 2048M
Max execution time: 50000
Upload Max File size: 64M

MySQL version: 10.1.44-MariaDB-0+deb9u1
MySQL engine: InnoDB
MySQL driver: DbPDO

Required parameters: OK
Optional parameters: OK

**Comment by khouloudbelguith** [comment] 2020-03-09 14:16
Hi @LGx0,

First PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Second, have you any errors during the upgrade?
This issue occurs in which page? in the FO?
Did you use custom modules? custom theme? have you any overrides?

Thanks!

**Comment by LGx0** [comment] 2020-03-09 15:12
![Prestashop](https://user-images.githubusercontent.com/17854088/76228247-c31aa400-6220-11ea-9405-4033b833bdfe.PNG)

**Comment by LGx0** [comment] 2020-03-09 15:13
Second, have you any errors during the upgrade?
- No
This issue occurs in which page? in the FO?
- Front page

**Comment by khouloudbelguith** [comment] 2020-03-09 15:37
@LGx0,

those two options don't work in Prestashop as reported here:

- https://github.com/PrestaShop/PrestaShop/issues/9965
- https://github.com/PrestaShop/PrestaShop/issues/14596

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by LGx0** [comment] 2020-03-09 15:51
Nothing. remove var/cache

**Comment by khouloudbelguith** [comment] 2020-03-09 16:24
@LGx0, could you please check if you have a custom module having the same function as reported here: https://github.com/PrestaShop/psgdpr/pull/75/files which fixes https://github.com/PrestaShop/psgdpr/issues/57

Thanks!

**Comment by LGx0** [comment] 2020-03-09 19:05
> 
> 
> @LGx0, could you please check if you have a custom module having the same function as reported here: https://github.com/PrestaShop/psgdpr/pull/75/files which fixes [PrestaShop/psgdpr#57](https://github.com/PrestaShop/psgdpr/issues/57)
> 
> Thanks!

I did it but it doesn't work

**Comment by khouloudbelguith** [comment] 2020-03-10 08:05
@LGx0, did you tried to disable non-native module manually? because as I said here: 

> @LGx0,
> 
> those two options don't work in Prestashop as reported here:
> 
> * #9965
> * #14596
> 

Thanks to check & feedback.

**Comment by LGx0** [comment] 2020-03-17 07:50
the problem could not be resolved.
I installed a new prestashop on a new server.

**Comment by khouloudbelguith** [comment] 2020-03-17 10:53
@LGx0, so the issue is not reproduced again? is it?
Can we close the issue?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-16 07:24
Hi @LGx0,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-16 07:24 UTC
Labels: Bug, Autoupgrade, No change required, 1.7.6.4
