### ISSUE TITLE
API Rest : Update an order by PUT : Several fields required

### ISSUE THREAD

**Issue by jlbrd** [PrestaShop/PrestaShop#26920] opened 2021-12-08 14:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When updating an order with PUT, several fields are required even if we do not want to modify them :

id, id_address_delivery, id_address_invoice, id_cart, id_currency, id_lang, id_customer, id_carrier, module, payment, total_paid, total_paid_real, total_products, total_products_wt, conversion_rate, reference, id_shop_group and id_shop

ID : required but it is in the url. What happens with 1 in url and 2 in data?

As we do not know the value for most fields, we have to read the command by GET, retrieve the values ​​to put in the PUT command. This generates two requests instead of one and generates risk of error.

### Steps to reproduce

 Update an order with rest API by PUT command

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by hibatallahAouadni** [comment] 2021-12-08 17:20
Hello @jlbrd 

Could you please provide the request body that you use to update an order.
Waiting for your feedback.

Thanks!

**Comment by jlbrd** [comment] 2021-12-09 07:53
Hello @hibatallahAouadni,

I send my put request by:
`https://localhost/api/orders/7?ws_key=XXXXXXXXXXRTK3TML2TUG5BL55SHQG&display=full`

The body is:
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <order>
        <id>7</id>
        <id_address_delivery>4</id_address_delivery>
        <id_address_invoice>4</id_address_invoice>
        <id_cart>7</id_cart>
        <id_currency>1</id_currency>
        <id_lang>1</id_lang>
        <id_customer>4</id_customer>
        <id_carrier>3</id_carrier>
        <module>ps_checkpayment</module>
        <payment>Chèque</payment>
        <total_paid>27.380000</total_paid>
        <total_paid_real>0.000000</total_paid_real>
        <total_products>9.920000</total_products>
        <total_products_wt>11.900000</total_products_wt>
        <conversion_rate>1.000000</conversion_rate>
        <reference>NGDWTYRKM</reference>
        <id_shop_group>1</id_shop_group>
        <id_shop>1</id_shop>
    </order>
</prestashop>

```
If one of these parameters is missing, the code error is "400 : Bad request" with message parameter required. Example without id_address_delivery in body:
![image](https://user-images.githubusercontent.com/11737691/145355918-8051d1a9-fc68-4a3b-b045-6c6ad48b3527.png)

**Comment by jlbrd** [comment] 2021-12-09 07:56
And as says before, ID is required in body but present in URL. Hum, it's currious, no ?

**Comment by jlbrd** [comment] 2021-12-09 07:58
Seeing this behavior, I tell myself that the rules are the same as for POST. No ?

**Comment by hibatallahAouadni** [comment] 2021-12-27 10:24
Hello @jlbrd 

Thanks for your patience and your feedback :pray: 
I Just followed your steps and here's the result:

![image](https://user-images.githubusercontent.com/23308427/147462423-2428ccf1-005e-4cf4-8b40-698eaaea9770.png)

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <order>
        <id>
            <![CDATA[7]]>
        </id>
        <id_address_delivery xlink:href="http://prestashop/prestashop_1.7.8.2/api/addresses/4">
            <![CDATA[4]]>
        </id_address_delivery>
        <id_address_invoice xlink:href="http://prestashop/prestashop_1.7.8.2/api/addresses/4">
            <![CDATA[4]]>
        </id_address_invoice>
        <id_cart xlink:href="http://prestashop/prestashop_1.7.8.2/api/carts/7">
            <![CDATA[7]]>
        </id_cart>
        <id_currency xlink:href="http://prestashop/prestashop_1.7.8.2/api/currencies/1">
            <![CDATA[1]]>
        </id_currency>
        <id_lang xlink:href="http://prestashop/prestashop_1.7.8.2/api/languages/1">
            <![CDATA[1]]>
        </id_lang>
        <id_customer xlink:href="http://prestashop/prestashop_1.7.8.2/api/customers/3">
            <![CDATA[3]]>
        </id_customer>
        <id_carrier xlink:href="http://prestashop/prestashop_1.7.8.2/api/carriers/2">
            <![CDATA[2]]>
        </id_carrier>
        <current_state xlink:href="http://prestashop/prestashop_1.7.8.2/api/order_states/">
            <![CDATA[]]>
        </current_state>
        <module>
            <![CDATA[ps_checkpayment]]>
        </module>
        <invoice_number>
            <![CDATA[]]>
        </invoice_number>
        <invoice_date>
            <![CDATA[]]>
        </invoice_date>
        <delivery_number>
            <![CDATA[]]>
        </delivery_number>
        <delivery_date>
            <![CDATA[]]>
        </delivery_date>
        <valid>
            <![CDATA[]]>
        </valid>
        <date_add>
            <![CDATA[2021-12-27 11:20:52]]>
        </date_add>
        <date_upd>
            <![CDATA[2021-12-27 11:20:52]]>
        </date_upd>
        <shipping_number notFilterable="true">
            <![CDATA[]]>
        </shipping_number>
        <note>
            <![CDATA[]]>
        </note>
        <id_shop_group>
            <![CDATA[1]]>
        </id_shop_group>
        <id_shop>
            <![CDATA[1]]>
        </id_shop>
        <secure_key>
            <![CDATA[]]>
        </secure_key>
        <payment>
            <![CDATA[Chèque]]>
        </payment>
        <recyclable>
            <![CDATA[]]>
        </recyclable>
        <gift>
            <![CDATA[]]>
        </gift>
        <gift_message>
            <![CDATA[]]>
        </gift_message>
        <mobile_theme>
            <![CDATA[]]>
        </mobile_theme>
        <total_discounts>
            <![CDATA[]]>
        </total_discounts>
        <total_discounts_tax_incl>
            <![CDATA[]]>
        </total_discounts_tax_incl>
        <total_discounts_tax_excl>
            <![CDATA[]]>
        </total_discounts_tax_excl>
        <total_paid>
            <![CDATA[27.380000]]>
        </total_paid>
        <total_paid_tax_incl>
            <![CDATA[]]>
        </total_paid_tax_incl>
        <total_paid_tax_excl>
            <![CDATA[]]>
        </total_paid_tax_excl>
        <total_paid_real>
            <![CDATA[0.000000]]>
        </total_paid_real>
        <total_products>
            <![CDATA[9.920000]]>
        </total_products>
        <total_products_wt>
            <![CDATA[11.900000]]>
        </total_products_wt>
        <total_shipping>
            <![CDATA[]]>
        </total_shipping>
        <total_shipping_tax_incl>
            <![CDATA[]]>
        </total_shipping_tax_incl>
        <total_shipping_tax_excl>
            <![CDATA[]]>
        </total_shipping_tax_excl>
        <carrier_tax_rate>
            <![CDATA[]]>
        </carrier_tax_rate>
        <total_wrapping>
            <![CDATA[]]>
        </total_wrapping>
        <total_wrapping_tax_incl>
            <![CDATA[]]>
        </total_wrapping_tax_incl>
        <total_wrapping_tax_excl>
            <![CDATA[]]>
        </total_wrapping_tax_excl>
        <round_mode>
            <![CDATA[]]>
        </round_mode>
        <round_type>
            <![CDATA[]]>
        </round_type>
        <conversion_rate>
            <![CDATA[1.000000]]>
        </conversion_rate>
        <reference>
            <![CDATA[FDTWLQHQW]]>
        </reference>
        <associations>
            <order_rows nodeType="order_row" virtualEntity="true">
                <order_row>
                    <id>
                        <![CDATA[9]]>
                    </id>
                    <product_id xlink:href="http://prestashop/prestashop_1.7.8.2/api/products/6">
                        <![CDATA[6]]>
                    </product_id>
                    <product_attribute_id>
                        <![CDATA[0]]>
                    </product_attribute_id>
                    <product_quantity>
                        <![CDATA[5]]>
                    </product_quantity>
                    <product_name>
                        <![CDATA[Mug The best is yet to come]]>
                    </product_name>
                    <product_reference>
                        <![CDATA[demo_11]]>
                    </product_reference>
                    <product_ean13>
                        <![CDATA[]]>
                    </product_ean13>
                    <product_isbn>
                        <![CDATA[]]>
                    </product_isbn>
                    <product_upc>
                        <![CDATA[]]>
                    </product_upc>
                    <product_price>
                        <![CDATA[11.900000]]>
                    </product_price>
                    <id_customization xlink:href="http://prestashop/prestashop_1.7.8.2/api/customizations/0">
                        <![CDATA[0]]>
                    </id_customization>
                    <unit_price_tax_incl>
                        <![CDATA[14.280000]]>
                    </unit_price_tax_incl>
                    <unit_price_tax_excl>
                        <![CDATA[11.900000]]>
                    </unit_price_tax_excl>
                </order_row>
            </order_rows>
        </associations>
    </order>
</prestashop>
```

Is there a missing steps? cause I didn't manage to reproduce the issue :confused: 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-17 12:10
Hello @jlbrd 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-17 12:10 UTC
Labels: Bug, WS, Order, Webservice, 1.7.8.0, Invalid
