### ISSUE TITLE
Wrong scope in Link Widget

### ISSUE THREAD

**Issue by ruchus** [PrestaShop/PrestaShop#23666] opened 2021-03-16 16:35 UTC
#### Describe the bug

When i check or uncheck content pages as "About us" or "Legal notice" from the Link Widget in a Shop scope (Store2 in this example).... it affect to all stores and always the same link pages are shown on footer for all stores.

![imagen](https://user-images.githubusercontent.com/6729380/111345505-a445bd80-867d-11eb-8f0a-48b09bb746a2.png)

#### Expected behavior

The pages checked in a specific store should show only in the own store.

![imagen](https://user-images.githubusercontent.com/6729380/111345470-9d1eaf80-867d-11eb-9cbd-570991596efe.png)

#### Steps to Reproduce

1. Go to Admin -> Link Widget -> Select a specific store scope.
2. Change the checkbox options for some pages
3. Go to frontend to a different store scope from step 1 and scoll down to see the footer.
4. You see always the same link pages.

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-03-17 10:05
Hello @ruchus 

It seems your issue is similar to this one #9795 (please check this [comment](https://github.com/PrestaShop/PrestaShop/issues/9795#issuecomment-438300155))
Please check abd feedback.

Thanks!

**Comment by ruchus** [comment] 2021-03-17 16:13
Hello @hibatallahAouadni 

Yes is the same. Sorry.

Thanks,

**Comment by hibatallahAouadni** [comment] 2021-03-17 16:29
Hello @ruchus 

Thanks for your feedback!
So, I close this issue cause it is already in our debug backlog. This issue is a duplicate of #9795. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-17 16:29
Duplicate of #9795

**Closed as completed by hibatallahAouadni** 2021-03-17 16:29 UTC
Labels: Bug, FO, Duplicate, Link widget, Multistore, 1.7.7.0
