### ISSUE TITLE
Prestashop 1.7.6.4 New Installation Password Chanhing Problem

### ISSUE THREAD

**Issue by shnslmz** [PrestaShop/PrestaShop#18302] opened 2020-03-25 09:52 UTC
After Prestashop 1.7.6.4 new installation on server I got this error:
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user
..
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(942): Doctrine\DBAL\Connection->connect() #4 /var/www/vhost in mydomain.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
```

Before installation is started I check DB, it was okay, then setup was finished as successful.

**Somehow PS changed/set (as wrong) DB password** for  /app/config/parameters.php
After this error, I checked parameters.php then, I discovered that the password was diffrent my current DB password.

Excl. alphanumeric chars, password had these chars: **#-%-!**
let's say master password was: **alk#f329%874y3rg!jEG**
When I checked: the password was: **alk#f329**%%**874y3rg!jEG**

The first time that it happened yesterday for me. I thought that, it was my mistake. But today, I tried again and understood, it is a BUG.

#### **Expected behavior**

It should be started without any error.

#### Steps to Reproduce

Classic installation:
1. Upload zip, unzip file, install
2. Delete install folder
3. White page, open the debug mode,
4. See the error

**Screenshots**
Not necessary.

#### Solution:
Re-set your current/main DB password, it will be okay.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.17
* Server, Apache & MySQL 5.5.x

**Comment by khouloudbelguith** [comment] 2020-03-25 10:00
Hi @shnslmz,

We are awre of this issue, it is added to our debug roadmap.
The problem is the Database password, it contains a % symbol => it will be doubled.
Your ticket is a duplicate of #12556
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-25 10:00
Duplicate of #12556

**Closed as completed by khouloudbelguith** 2020-03-25 10:00 UTC
Labels: Duplicate
