### ISSUE TITLE
No bank payment validation after upgrade 1.7.5.2 -> 1.7.6.0

### ISSUE THREAD

**Issue by flyman30** [PrestaShop/PrestaShop#14813] opened 2019-07-22 15:08 UTC
**Describe the bug**

After the update version 1.7.5.2 -> 1.7.6.0 problems of bank modules appeared.
A beginning of solution has been published: https://github.com/PrestaShop/PrestaShop/issues/14608
But there are still problems!
The E-transaction bank module in my case but also the cmcicpayment module normally connects to the bank but the return of the bank's response does not return to PrestShop, so no payment validation or emails sent to the customer and the merchant .

`Une erreur est levée lors de l'appel à ToolsCore::displayPrice => ToolsCore::getContextLocale(Object(Context))

 ﻿

[Mon Jul 22 11:03:34.953382 2019] [php7:error] [pid 1792] [client XX.XX.XX.XX:37428] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in 
/xxxxxxxxxxxx/public_html/classes/Tools.php:801\nStack trace:\n#0 
/xxxxxxxxxxxx/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 
/xxxxxxxxxxxx/public_html/classes/Notification.php(133): ToolsCore::displayPrice(31.35, Object(Currency), false)\n#2 
/xxxxxxxxxxxx/public_html/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '20821')\n#3 
/xxxxxxxxxxxx/public_html/zzzzzzz/ajax.php(125): NotificationCore->getLastElements()\n#4
 {main}\n  thrown in /xxxxxxxxxxxx/public_html/classes/Tools.php on line 801, referer: https://www.yyyyyyyyyy.com/zzzzzzz/index.php?controller=AdminStats&token=2cf9909b77f74d62ff078e389febe409

[...]

[Mon Jul 22 11:09:31.457138 2019] [php7:error] [pid 10243] [client XX.XX.XX.XX:43994] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in 
﻿/xxxxxxxxxxxx/public_html/classes/Tools.php:801\nStack trace:\n#0 
/xxxxxxxxxxxx/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 
/xxxxxxxxxxxx/public_html/classes/PaymentModule.php(421): ToolsCore::displayPrice(4.9, Object(Currency), false)\n#2 
/xxxxxxxxxxxx/public_html/modules/cmcicpaiement/validation.php(123): PaymentModuleCore->validateOrder(123246, '2', '9.60', 'CM-CIC P@iement', 'TPE: 6600893<br...', NULL, 1, true, 'd67985d7118f76f...')\n#3
{main}\n  thrown in /xxxxxxxxxxxx/public_html/classes/Tools.php on line 801
﻿﻿
[﻿Mon Jul 22 11:09:33.208743 2019] [php7:error] [pid 10205] [client XX.XX.XX.XX:43996] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in 
/xxxxxxxxxxxx/public_html/classes/Tools.php:801\nStack trace:\n#0 
/xxxxxxxxxxxx/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))\n#1 
/xxxxxxxxxxxx/public_html/classes/order/OrderHistory.php(513): ToolsCore::displayPrice(9.6, Object(Currency), false)\n#2 
/xxxxxxxxxxxx/public_html/classes/﻿order/OrderHistory.php(468): OrderHistoryCore->sendEmail(Object(Order), Array)\n#3
/xxxxxxxxxxxx/public_html/modules/cmcicpaiement/validatio﻿n.php(109): OrderHistoryCore->addWithemail(true, Array)\n#4 
{main}\n  thrown in﻿ /xxxxxxxxxxxx/public_html/classes/Tools.php on line 801﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿`
 

Like
 Citer
flyman30
 Répondre à ce sujet…

**Comment by khouloudbelguith** [comment] 2019-07-22 15:31
Hi @flyman30,

This issue should be fixed in the PS1.7.6.1.
Your ticket is a duplicate of #14648
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-22 15:31
Duplicate of #14648

**Closed as completed by khouloudbelguith** 2019-07-22 15:31 UTC
Labels: Duplicate
