### ISSUE TITLE
Remove cache on module ps_sharebuttons

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#19151] opened 2020-05-14 20:41 UTC
Please remove cache from this module. This is useless:

https://github.com/PrestaShop/ps_sharebuttons/blob/master/ps_sharebuttons.php#L145

There is nothing to cache, and because of complexity of cache key we have thousands more files of cache worth nothing...

**Comment by florine2623** [comment] 2020-05-15 10:05
Hi @PrestaShop/prestashop-core-developers ,

Could you take a look at @kpodemski 's request ?
Is it relevant ?

Thanks!

**Comment by kpodemski** [comment] 2020-05-15 12:19
@sam-pires all issues, even those related to modules should be created in main repo?

**Comment by Progi1984** [comment] 2020-05-15 12:27
@kpodemski Affirmative

**Comment by sam-pires** [comment] 2020-05-15 12:28
@kpodemski, yes it is better.
We still have some issues related to modules, in the modules' repos. But to be able to manage the issues in the development boards/kanban, they have to be on the main repo.

So we are progressively disabling issues submission on all modules repos and transfering existing issues to the main repo. As @Progi1984 did this morning with this one 🙂 

Instead of having the issues in a module's repo, we use the yellow labels to indicate which module the issue is about

**Comment by kpodemski** [comment] 2020-05-15 12:29
@sam-pires good choice, i remember my frustration with issues (and PRs) open in modules for years ;)

**Comment by kpodemski** [comment] 2020-05-15 12:31
@Progi1984 for the record, few weeks ago i cleaned cache folder from over 2GB of cache files for sharebuttons module :P

in getWidgetVariables we're not doing anything "heavy", Configuration is cached by default etc.

**Comment by matks** [comment] 2020-06-19 09:28
Will be fixed by https://github.com/PrestaShop/ps_sharebuttons/pull/40

**Comment by Progi1984** [comment] 2020-06-22 09:07
Fixed by PrestaShop/ps_sharebuttons#40

**Closed as completed by Progi1984** 2020-06-22 09:07 UTC
Labels: Improvement, CO, Socialsharing, Fixed
