### ISSUE TITLE
PS_WIREPAYMENT order validation fatal error

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#19771] opened 2020-06-16 06:47 UTC
[PrestaShopException]
Errore fatale
at line 1174 in file classes/Tools.php

1169.                 ->getTranslator()
1170.                 ->trans('Fatal error', [], 'Admin.Notifications.Error');
1171.         }
1172. 
1173.         if (_PS_MODE_DEV_) {
1174.             throw new PrestaShopException($errorMessage);
1175.         }
1176. 
1177.         return $errorMessage;
1178.     }
1179. 
ToolsCore::displayError - [line 255 - classes/PaymentModule.php]
PaymentModuleCore->validateOrder - [line 64 - modules/ps_wirepayment/controllers/front/validation.php] - [9 Arguments]
Ps_WirepaymentValidationModuleFrontController->postProcess - [line 280 - classes/controller/Controller.php]
ControllerCore->run - [line 387 - override/classes/Dispatcher.php]
Dispatcher->dispatch - [line 28 - index.php]

![image](https://user-images.githubusercontent.com/24798703/84740538-dc648680-afad-11ea-87b4-7e4b19062399.png)

PS 1.7.6
PHP 7.2

When try to complete order with bank wire get this error.

**Comment by matteolavaggi** [comment] 2020-06-16 06:49
![image](https://user-images.githubusercontent.com/24798703/84740798-55fc7480-afae-11ea-8ad3-33516f5ee1b4.png)

**Comment by matteolavaggi** [comment] 2020-06-16 07:02
IT's something related to cloudflare, any idea or suggestions how to improve?

**Comment by sarahdib** [comment] 2020-06-16 14:51
Hello @matteolavaggi 

Could you give us more information : 
- Steps to reproduce
- the exact prestashop version

**Comment by sarahdib** [comment] 2020-07-07 11:57
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Closed as completed by sarahdib** 2020-07-07 11:57 UTC
Labels: No change required, 1.7.6.0
