### ISSUE TITLE
can't add product on prestashop 1.7.4.1

### ISSUE THREAD

**Issue by akorsonsky** [PrestaShop/PrestaShop#11047] opened 2018-10-17 10:23 UTC
I'm anable to add product from yesterday. i don't do something on my prestashop. i can't find the problem

When i add the product in the back office i save it, he say me ok in green then i can't see the product in the product list.

I check the index and reindex and he say me ok 72/72

but in my table i have 73 lines.

The product i added is in the database, the reference is not stored as i give it. if i put manually the reference in the database and reindex, always 72/72... how i can see my 73 product and continue to add another ? 

thanks for your help

**Comment by khouloudbelguith** [comment] 2018-10-17 10:29
Hi @akorsonsky,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Lakhan79** [comment] 2018-10-17 16:59
Hello There,

I also have the same issue, please resolve it.

here are the error details


(1/1) ContextErrorExceptionNotice: Undefined index: category
--
in c9007e0447135bf7dfaa041510852672170c35d6_2.file.product.tpl.php line 635
at Block_21441199925bc769578cdaf4_25128392->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_21441199925bc769578cdaf4_25128392), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_21441199925bc769578cdaf4_25128392))in smarty_internal_runtime_inheritance.php line 157
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_21441199925bc769578cdaf4_25128392', 'product_footer', 0)in c9007e0447135bf7dfaa041510852672170c35d6_2.file.product.tpl.php line 885
at Block_11670100305bc769578529f9_46390475->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_11670100305bc769578529f9_46390475), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_11670100305bc769578529f9_46390475),object(Block_4899125965bc769578eaa16_13605780))in smarty_internal_runtime_inheritance.php line 185
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_4899125965bc769578eaa16_13605780))in smarty_internal_runtime_inheritance.php line 157
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_4899125965bc769578eaa16_13605780', 'content', 1)in c9cd47ec470e09c20fcaa920763dfa3915dbb88e_2.file.layout-full-width.tpl.php line 135
at Block_17510882535bc769578e9534_02993300->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_17510882535bc769578e9534_02993300), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_17510882535bc769578e9534_02993300),object(Block_7409573755bc76957908b03_31154604))in smarty_internal_runtime_inheritance.php line 185
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_7409573755bc76957908b03_31154604))in smarty_internal_runtime_inheritance.php line 157
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_7409573755bc76957908b03_31154604', 'content_wrapper')in 433758494b688da16acdc4259e847c6b7d69ee8e_2.file.layout-both-columns.tpl.php line 91
at content_5bc76957925835_11603793(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in c9cd47ec470e09c20fcaa920763dfa3915dbb88e_2.file.layout-full-width.tpl.php line 50
at content_5bc769578ec7e3_91907086(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in c9007e0447135bf7dfaa041510852672170c35d6_2.file.product.tpl.php line 64
at content_5bc769578d35e5_06226284(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 41
at SmartyDev->fetch('catalog/product.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 679
at FrontControllerCore->smartyOutputContent('catalog/product.tpl')in FrontController.php line 663
at FrontControllerCore->display()in Controller.php line 275
at ControllerCore->run()in Dispatcher.php line 428
at DispatcherCore->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment] 2018-10-17 17:26
Hi @Lakhan79, 

What is the exact version PrestaShop did you use?
Did you use the default theme provided by Prestashop?
Thanks!

**Comment by akorsonsky** [comment] 2018-10-18 15:42
it's a fresh installation i use and all was ok and yesterday all block here is the video of the problem i explain

https://www.youtube.com/watch?v=VP-BytvRfTc

**Comment by khouloudbelguith** [comment] 2018-10-18 15:59
Hi @akorsonsky,

For the second issue, [I check the index and reindex and he says me ok 72/72 => but in my table, i have 73 lines.]: your product is disabled that's why is not indexed => you need to enable it to be indexed.
For the first issue, in the product details page, if you select the Home category, in the category list, the issue will be solved? the product will be displayed in the list page?
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-22 15:10
Hi @akorsonsky,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-22 15:10 UTC
Labels: Bug, FO, Blockcart, No change required, 1.7.4.1
