### ISSUE TITLE
BO > Add new order > Newly created carriers are not displayed

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35206] opened 2024-01-29 12:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I create a new carrier, when I add an order from the BO, the carrier is not displayed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/1dd87911-4933-43df-bc9d-1b50878fa979

### Expected behavior

My carriers should be displayed in the dropdown

### Steps to reproduce

1. Go to BO > Shipping > Carriers > Add new carrier
2. Add Carrier name, transit time, enable Free shipping > Finish creation of carrier
3. Go to BO > Orders > Add new order > Choose Customer > Add product to cart
4. In block Shipping > Delivery option : See your newly created carrier is not displayed :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2024-01-29 15:09
@florine2623 You did not enable the carrier for any zone, that's why it's not visible. 👍

**Comment by AureRita** [comment] 2024-01-30 13:24
Hi @florine2623 

Thank you for your report, currently I reproduce the issue on develop as you can see : 

[recording(82).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/8150139a-dc7f-4e94-8610-8891066e2bb2)

But as said Hlavtox, it's because you don't enable any zone ( you can see on the video, when I enable some zone, I find my new carrier ) 

If you want, you can ask to create a new feature (in a new discussion) wich require some zone enabled on a creation of a carrier. 

Because this one is not an issue, I'll close it 

Thank you

**Closed as completed by AureRita** 2024-01-30 13:24 UTC
Labels: Bug, Invalid
