### ISSUE TITLE
Error with ps_emailalerts

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#17259] opened 2020-01-20 19:14 UTC
Hi
it is necessary to edit the line 205 in ps_emailalerts.php

it is necessary to remove the condition count($email) > 0

so this line
} elseif (!empty($email) && count($email) > 0) {
becomes
} elseif (!empty($email)) {

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/72751908-1d07d180-3bc1-11ea-9ef1-2e539220d08c.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.26
Module version: 2.1.1

**Comment by sarahdib** [comment] 2020-01-21 08:22
Hello @maofree 

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

Thank you!

**Comment by Maofree** [comment] 2020-01-23 18:10
hi
I've done some tests and to solve this problem it is necessary to remove the count(..)

**Comment by khouloudbelguith** [comment] 2020-01-24 09:56
Hi @maofree,

Also, Here's the PR: PrestaShop/ps_emailalerts#18 to fix the issue.
Your ticket is a duplicate of PrestaShop/ps_emailalerts#16
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-24 09:56
Duplicate of https://github.com/PrestaShop/ps_emailalerts/pull/18

**Closed as completed by khouloudbelguith** 2020-01-24 09:56 UTC
Labels: Bug, BO, Duplicate, 1.7.6.1, ps_emailalerts
