### ISSUE TITLE
Combination issue while trying to change different attributes on a product page

### ISSUE THREAD

**Issue by djonez** [PrestaShop/PrestaShop#11003] opened 2018-10-13 20:26 UTC
**Describe the bug**
When choosing a product with more attributes, you get the error, "An error occurred while processing your request" when changing value from one attribute that don't have same attribute in secondary attribute. I made an video to describe it better.

**To Reproduce**
1. Go to "Catelog" => "Attributes & Features". Choose secondary Attribute (for combinations". Create one called "Size" and one called "Amount". Create 3 Sizes and 4 different Amounts. 
2. Go to "Catelog" => "Products". Create a new product and choose "Product with combinations". Create 5 combinations. 2 with one Size and 2 different Amounts. 1 with another Size and one Amount, one of the same as the first Size. And a 3rd with the last Size and the 2 Amounts not used with the other 2 Sizes. Save Product.
3. Choose the Product you created on the Customer page. Try switch between different Sizes and Amounts. The last Size you made will not have the option of choosing the rigth Amount. The option will not appear. The second Size you create can be chosen, but the error will appear and the Amount be the only one to choose when you select the right one.

**Screenshots**
I attached screenrecordig of my problem. 

**Additionnal information**
PrestaShop version: 1.7.4.2, 1.7.4.3
PHP version: 7.0.32
Current theme in use: classic
Browser: Latest version of Firefox, Chrome, Internet Explore and Edge.
[http://smugkig.nu/prestashop_1.7.4.3_combination_issue.mp4](http://smugkig.nu/prestashop_1.7.4.3_combination_issue.mp4)

**Comment by khouloudbelguith** [comment] 2018-10-15 08:26
Hi @djonez,

Thanks for your report.
When applying the fix patch, did you follow the instruction described by ttoine: https://github.com/PrestaShop/PrestaShop/pull/9390#issuecomment-416876095 ?
If yes, your server setup and configuration is nginx?
Thanks!

**Comment by djonez** [comment] 2018-10-15 16:49
Hi khouloudbelguith,

Yes i did follow the instructions, but it didn't help.
No, it's on Apache.

---
Med venlig hilsen / Best regards

Joen Seider
Tlf. 51800600

man. 15. okt. 2018 10.27 skrev khouloudbelguith <notifications@github.com>:

**Comment by khouloudbelguith** [comment] 2018-10-15 16:52
@djonez, after applying the patch, could you please try to clear cache from the shop & the browser.
You need to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by djonez** [comment] 2018-10-15 19:39
Hi

No, sorry. My mistake. I have applied some other fix in the thread but not
seen the response from ttoine.
Looks like it worked. Sorry to bother you with an issue which was already
solved.

Thank you very much for you help. I'm glad to know that there is suck
competent people working on Prestashop.

Again thank you all.


Med venlig hilsen/Best Regards

Joen Seider
Tlf. 51800600


Den man. 15. okt. 2018 kl. 18.52 skrev khouloudbelguith <
notifications@github.com>:

**Comment by khouloudbelguith** [comment] 2018-10-16 09:10
Hi @djonez,

Thanks for your feedback.
You are welcome.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-16 09:10
Duplicate of #9390

**Closed as completed by khouloudbelguith** 2018-10-16 09:10 UTC
Labels: Bug, FO, Duplicate, Combinations, 1.7.4.3
