### ISSUE TITLE
Invoice address different from billing address

### ISSUE THREAD

**Issue by fedeanimation** [PrestaShop/PrestaShop#23291] opened 2021-02-17 14:40 UTC
#### Describe the bug

When I change the invoice address it change also the shipping address. I set Spain in the shipping address than when I select in the invoice another nation different from Spain it change also the shipping address.

#### Expected behavior

The client can choose if the invoice addresse should be different from shipping address.

#### Steps to Reproduce

1. Go to 'checkout'
2. Click on 'address step and fill up the form chosing one nation'
3. Scroll down to 'invoice form address and chose a different nation'

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.26

**Comment by hibatallahAouadni** [comment] 2021-02-17 16:14
Hello @fedeanimation 

> 4. See error

Do you mean that the page refresh and you found only the first address saved, is that so?
If not, please try again cause I didn't manage to reproduce the issue, see the attached screen record below:

https://drive.google.com/file/d/1ub5xuzgbLY7Tn6orzJWbAtA999fTVAs7/view

Please check and feedback.
Thanks!

**Comment by fedeanimation** [comment] 2021-02-18 08:33
Hello @hibatallahAouadni thanks for reply.

Here the screen record of the issue.
[https://drive.google.com/file/d/1URzZkkXtzxEBb7cIL9kXrWAYtHrbgGZT/view?usp=sharing](https://drive.google.com/file/d/1URzZkkXtzxEBb7cIL9kXrWAYtHrbgGZT/view?usp=sharing)

**Comment by hibatallahAouadni** [comment] 2021-02-22 08:06
Hello @fedeanimation 

Up that step when you stop recording, yes I manage to reproduce the issue. But if you continue saving the address, you will see that the shipping address is well saved and the bug is just Front-end JS refresh.

https://drive.google.com/file/d/1JPdK1-eevxLRbg4U9ABfaJbKzUymWgo1/view

Please check and feedback.
Thanks!

**Comment by fedeanimation** [comment] 2021-03-13 12:57
Hi @hibatallahAouadni 

I tried to deactivate the theme and setup the default, but the problem si still there. 

I don't know I to solve ti front-end problem

**Comment by hibatallahAouadni** [comment] 2021-03-14 11:36
Hello @fedeanimation 

I think it's just a cache problem :confused: did you try to refresh the page?
Please check and feedback.

Thanks!

**Comment by fedeanimation** [comment] 2021-03-14 21:49
Try to clear cache, incognito and new browser I still have the problem

**Comment by hibatallahAouadni** [comment] 2021-03-14 22:00
Hello @fedeanimation 

Could you please make a screen record following my steps (shown in my screen record above).

Thanks!

**Comment by fedeanimation** [comment] 2021-03-15 08:14
Hello @hibatallahAouadni 

here the screen record [screenrecord](https://drive.google.com/file/d/10jggMqJfzJIxvNQ1OuMnbi__D7zwbPpo/view?usp=sharing)

**Comment by hibatallahAouadni** [comment] 2021-03-16 16:19
Hello @fedeanimation 

It seems I don't have access to view your screen record :sweat_smile: I just sent you a request access.
Please accept it :pray: 

Thanks!

**Comment by fedeanimation** [comment] 2021-03-18 08:57
Hi @hibatallahAouadni 
Sorry sorry  🙏 You have the access now

**Comment by hibatallahAouadni** [comment] 2021-03-19 15:09
Hello @fedeanimation 

I didn't see any error in your screen record, it works like a charm!

![image](https://user-images.githubusercontent.com/23308427/111801584-63dc7e80-88cd-11eb-8ee7-77abb7d196fe.png)

So, where's the problem???
Please check and feedback.

Thanks!

**Comment by florine2623** [comment] 2021-04-07 09:58
Hello @fedeanimation ,
since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-04-07 09:58 UTC
Labels: Bug, FO, Addresses, No change required, Checkout, 1.7.7.1
