### ISSUE TITLE
Error 500 when selecting combination values that do not exist

### ISSUE THREAD

**Issue by demperador** [PrestaShop/PrestaShop#10336] opened 2018-09-07 10:13 UTC
**Describe the bug**
When a product has more than one attribute associated with it and some combinations do not exist, the user 

**To Reproduce**
1. Go to https://centrobell.com/esmaltes/865-2160-cnd-vinylux.html#/505-cantidad_del_envase-15_ml/586-grupo_de_colores-rojos/772-colores_de_esmaltes-244_mambo_beat
2. Select on any other "Tonos" value besides the default option.
3. Error attached to this message is thrown.

**Screenshots**
[errorShellac.pdf](https://github.com/PrestaShop/PrestaShop/files/2360590/errorShellac.pdf)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.31

**Comment by khouloudbelguith** [comment] 2018-09-07 10:23
Hi @demperador,

The issue is fixed in the next version 1.7.5.0.
Here's the PR: #9390 to solve the issue.
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-07 10:24
Duplicate of #9390

**Closed as completed by khouloudbelguith** 2018-09-07 10:23 UTC
Labels: Duplicate
