### ISSUE TITLE
Not possible to translate/change the same words in classic translation

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#16358] opened 2019-11-11 16:49 UTC
**Describe the bug**

**To Reproduce**
1. Go to  index.php/improve/international/translations/?lang=en&type=themes&locale=en-US&selected=classic (theme translations, english, classic theme)
2. Search for 'stores'
3. Scroll down to 'navigation'
4. Replace stores with store (in case someone only has one store, I guess most people) on both accounts, press save 
It will show 'Translations successfully updated' but when you refresh one on of the 2 is updated.
because the theme/key combination is the same from the start. So either there should only be one mention of stores in navigation or the way it is stored needs to change.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7

**Comment by khouloudbelguith** [comment] 2019-11-12 08:05
Hi @sickboards,

Here's the PR: #15511 to fix the issue.
It is fixed in the next version PS1.7.7.0.
Your ticket is a duplicate of #10701
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-11-12 08:05 UTC
Labels: Duplicate
