### ISSUE TITLE
1 Click Upgrade Module - > Error 500 When i try to acces module

### ISSUE THREAD

**Issue by Bahwaimongars** [PrestaShop/PrestaShop#20232] opened 2020-07-19 12:40 UTC
Hi, I noticed there was a bug when I tried to access : One click on the module:

1- Click on : 1-Click Upgrade button in the 'Details' menu.
2- A few seconds (30/40 seconds) later, I get an error of 500

I'm trying: 
- Change php version
- Check the php configuration (screen below)
- Debug mode: ON
- All caches disable

![FireShot Capture 051 - PHP PrestaShop Info - mygolftour fr](https://user-images.githubusercontent.com/62238066/87874888-bfb4d780-c9cd-11ea-8fbe-a03eb17c997a.png)

* PrestaShop version: 1.7.5.2
* PHP version: 7.2

-----

Thanks for your help :)

**Comment by sarahdib** [comment] 2020-07-20 14:28
Hello,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- PrestaShop version (source)
- module version 
- a screenshot of your error

Thank you!

**Comment by Bahwaimongars** [comment] 2020-07-20 14:38
Hello,

Prestashop version source : 1.7.5.2
Module version : 4.10.1
![image](https://user-images.githubusercontent.com/62238066/87950315-6de08000-caa7-11ea-9dd8-139d0e1aff6d.png)

thx :)

**Comment by Bahwaimongars** [comment] 2020-07-22 10:40
Hello, 

Any ideas ? :/

**Comment by florine2623** [comment] 2020-07-23 10:24
Can you enable your debug mode ?

Advanced Parameters > Performance > Activate debug mode

Or in FTP, change line in file config/define.inc.php :
`define('_PS_MODE_DEV_', false);`
to
`define('_PS_MODE_DEV_', true);`

**Comment by Bahwaimongars** [comment] 2020-07-23 11:56
Hello, Debug mode is already activate, in Back office & in define.inc.php, but nothing appear, just this error.

I have : 

Set permissions to 755 foldes / 644 files too, nothing

**Comment by Bahwaimongars** [comment] 2020-07-23 12:34
I have try to install a fresh version of the module in version : 
4.10.1 & 4.10.0 and now after install complete i got this error when i click on configure : 
![myg-error-v4 10 1](https://user-images.githubusercontent.com/62238066/88286700-72987480-ccf1-11ea-8ae4-dea86c4e60ab.jpg)

**Comment by florine2623** [comment] 2020-07-23 16:25
Can you delete all cache from your server ?
In /var/cache/prod and /var/cache/dev

**Comment by Bahwaimongars** [comment] 2020-07-24 13:09
All caches deleted 3 / 4 times same result :/

**Comment by florine2623** [comment] 2020-07-24 14:33
Can you comment gamification module and see the result ?

**Comment by Bahwaimongars** [comment] 2020-07-24 14:55
Folder gamification commented to __gamification = Same result.

I received an alert from my host, telling me that the memory was exceeded once (I have 512 mo). The alert appeared only once on my 30+ attempts, so I don't think it's from there.

**Comment by florine2623** [comment] 2020-07-24 15:08
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
You can contact our support team here : https://addons.prestashop.com/en/388-support
We will close this issue.

**Closed as completed by florine2623** 2020-07-24 15:08 UTC
Labels: Autoupgrade, No change required
