### ISSUE TITLE
After upgrade to 4.2.0 comments not displayed and Fatal Error

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/PrestaShop#22072] opened 2020-11-24 12:59 UTC
#### Describe the bug

After upgrade to 4.2.0 module "productcomments", comments are not displayed and a popup says that we can't post new comment.

#### Steps to Reproduce

1. Upgrade module productcomments on 4.2.0
2. Go to the front office product view
3. Try to post a comment or try to read comments

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

Fatal error:

```[Tue Nov 24 12:40:53.715045 2020] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to ProductCommentsPostCommentModuleFrontController::addCommentGrades() must be of the type array, boolean given, called in .../www/modules/productcomments/controllers/front/PostComment.php on line 87 and defined in .../www/modules/productcomments/controllers/front/PostComment.php:113
[Tue Nov 24 12:40:53.715045 2020] Stack trace:
[Tue Nov 24 12:40:53.715045 2020] #0 .../www/modules/productcomments/controllers/front/PostComment.php(87): ProductCommentsPostCommentModuleFrontController->addCommentGrades(Object(PrestaShop\\Module\\ProductComment\\Entity\\ProductComment), false)
```

**Comment by hibatallahAouadni** [comment] 2020-11-24 13:23
Hello @bm-services 

I didn't manage to reproduce your issue with PS1.7.6.3, see the attached screen record below:

https://drive.google.com/file/d/1-acdq6HwPa0UwMMbkCrF_VE5Li-175ch/view

As you can see in the screen record the ProductComment module was v4.1.0 and I upgrade it to v4.2.0 [time: **2:00**], and everything works perfectly.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-14 15:39
Hello @bm-services,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-14 15:39 UTC
Labels: Bug, BO, Modules, No change required, Productcomments, 1.7.6.3
