### ISSUE TITLE
Price error when changing declination

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#13718] opened 2019-05-08 16:31 UTC
**Describe the bug**
When a product has several declinations, if we decide to have different prices on each declination either as a specific price per quantity or as a specific reduction, when changing the declination, the price will always be calculated according to the desired quantity before it is delivered to the minimum quantity, or most of the time 1.

**Screenshots**
https://vimeo.com/334939336/7699b6e426

**Additionnal information**
PrestaShop version: 1.7.5.0 / 1.7.5.2
PHP version: 7.0, 7.1, 7.2

**Comment by marionf** [comment] 2019-05-09 07:39
@jeckyl I can't reproduce it with 1.7.6.x branch, it seems already fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/11645
https://drive.google.com/file/d/1nWMvvgYMnz2GgfWEeubBhj11ARzeBWvl/view?usp=sharing

**Closed as completed by marionf** 2019-05-09 07:39 UTC
Labels: FO, Combinations, Fixed, 1.7.5.0, 1.7.5.1, 1.7.5.2
