### ISSUE TITLE
Orders are placed on "On Backorder (paid)" with 1 item in stock

### ISSUE THREAD

**Issue by remagalot** [PrestaShop/PrestaShop#10923] opened 2018-10-09 03:24 UTC
**Describe the bug**
When stock item is 1, and order is placed, instead of fulfilling order, order is placed On Back order (Paid)

**To Reproduce**
1. Place order for item with 1 stock
2. Order is marked at Delivered
3. Order is marked as On Backorder(paid)

**Additionnal information**
PrestaShop version:  1.7.4.2

**Comment by khouloudbelguith** [comment] 2018-10-09 07:50
@remagalot, this issue is fixed in the PS 1.7.4.0, Here's the PR https://github.com/PrestaShop/PrestaShop/pull/8985 to solve the problem.
What is the exact version PrestaShop did you use?

**Comment by remagalot** [comment] 2018-10-09 12:58
info_outline Server information

Server information Linux #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64

Server software version: Apache

PHP version: 7.0.32-0ubuntu0.16.04.1

Memory limit: 386M

Max execution time: 300

Upload Max File size: 25M

 info_outline Store information

Prestashop version: 1.7.4.2

**Comment by khouloudbelguith** [comment] 2018-10-09 13:06
@remagalot, I did not manage to reproduce the issue with PS1.7.4.2
I attached a video record.
https://drive.google.com/file/d/1lBvsmV7Zt8SPkgAsKB6Hve2oBGUlW63D/view
Thanks to check & feedback.

**Comment by remagalot** [comment] 2018-10-09 13:23
I have items with combinations and low stock alerts set to 0.  I did validate I have 1 item in stock prior to ordering it for testing

1. Customer places order
2. I receive email:
Shoe Size - 11, Shoe Width - EE is nearly out of stock.
The remaining stock is now less than the specified minimum of 0.
Remaining stock: 0
3.  Customer receives email "Order Confirmation"
3. Order is changed from "delivered" to On Backorder (paid).
4. If you view order, you see product listed as Qty 1, Returned 0, Available 0
5. If you check Stock Management Item shows as Physical 1, Reserved 1, Available 0

![image](https://user-images.githubusercontent.com/4564055/46672268-929e8880-cb9c-11e8-9088-06df73d6c1ca.png)

![image](https://user-images.githubusercontent.com/4564055/46672293-a6e28580-cb9c-11e8-8dc1-312c463cbf40.png)

![image](https://user-images.githubusercontent.com/4564055/46672432-05a7ff00-cb9d-11e8-89ba-6d69ff26021b.png)

**Comment by khouloudbelguith** [comment] 2018-10-09 13:26
@remagalot, could you please check the fix: https://github.com/PrestaShop/PrestaShop/pull/8985/files in your project.

**Comment by remagalot** [comment] 2018-10-09 13:29
@khouloudbelguith I can confirm I see this fix in PaymentModule.php

![image](https://user-images.githubusercontent.com/4564055/46672630-8f57cc80-cb9d-11e8-9b45-de721d078999.png)

**Comment by khouloudbelguith** [comment] 2018-10-09 13:46
@remagalot, What is the exact payment method module did you use?
What is the type of products did you ordered?

**Comment by remagalot** [comment] 2018-10-09 14:03
@khouloudbelguith I use Authorize.Net AIM module to process credit card transactions.  I don't believe I have any "payment methords" installed though

**Comment by khouloudbelguith** [comment] 2018-10-09 14:47
@remagalot, if you use another payment method module (for example pay by check) the issue occurs?

**Comment by remagalot** [comment] 2018-10-09 15:01
I dont have any payment module's installed / configured.  I use RockPOS for handling instore transactions.

This only started happening after upgrading to 1.7.4

**Comment by khouloudbelguith** [comment] 2018-10-09 15:03
@remagalot, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by remagalot** [comment] 2018-10-09 15:05
What about files inside cache/dev cache/prod?

**Comment by khouloudbelguith** [comment] 2018-10-09 15:12
@remagalot, you need to delete the folders dev/ & prod/

**Comment by remagalot** [comment] 2018-10-09 15:21
@khouloudbelguith 
OK.  Deleted both folders.  Reloaded browser
Same result 
![image](https://user-images.githubusercontent.com/4564055/46679601-f9c43900-cbac-11e8-8bf9-75c2489b9042.png)
![image](https://user-images.githubusercontent.com/4564055/46679621-05176480-cbad-11e8-9372-572af55c48b1.png)
![image](https://user-images.githubusercontent.com/4564055/46679640-0c3e7280-cbad-11e8-9ba8-96e57e3c1c4c.png)

**Comment by remagalot** [comment] 2018-10-09 15:23
I will try to process from FO instead of using RockPOS Module

**Comment by remagalot** [comment] 2018-10-09 15:34
![image](https://user-images.githubusercontent.com/4564055/46680490-d7cbb600-cbae-11e8-95da-692ab11f78a6.png)

**Comment by khouloudbelguith** [comment] 2018-10-09 15:36
@remagalot,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by remagalot** [comment] 2018-10-09 17:41
@khouloudbelguith firstly thank you for the support.

I have the logs requested with exception to "debug mode report"

What exactly is this?

**Comment by khouloudbelguith** [comment] 2018-10-10 08:17
@remagalot, you need to enable the debug mode and paste the error that you get.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-13 11:35
Hi @remagalot,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-13 11:35 UTC
Labels: BO, Order, Stocks, Order statuses, No change required

**Comment by kandiaga** [comment] 2019-06-25 21:06
This issue is still not  fixed.

**Comment by khouloudbelguith** [comment] 2019-06-26 08:56
@kandiaga, issue reported here: #14370
