### ISSUE TITLE
Unable to uninstall native module ps_dataprivacy

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26869] opened 2021-12-03 21:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Unable to uninstall native module ps_dataprivacy

I have this problem even having version 2.0.1

Prestasop 1.7.7.3
https://www.awesomescreenshot.com/video/6280974?key=3a7c0711685e27352f2c10e0273e8822

Prestasop 1.7.8.0
https://www.awesomescreenshot.com/video/6281019?key=8bd2711d6efa9e2d1c7caabba93e6bdf

### Expected behavior

Be able to uninstall native module ps_dataprivacy

### Steps to reproduce

Go to Module Manager
Click on Uninstall module ps_dataprivacy
See erro

### PrestaShop version(s) where the bug happened

1.7.7.3 - 1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_dataprivacy

**Comment by hibatallahAouadni** [comment] 2021-12-06 08:53
Hello @alfonsolr09 

I reproduce the issue with PS1781, I'm unable to uninstall the module on PS1781, see the attached screen record below:

https://watch.screencastify.com/v/Iw48UY0K8Ecie6BrYPhj

And I encounter another problem, I'm unable to unistall the module in PS1767, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/144816129-79c6d46c-2b7f-4953-9ee4-744261c1b08f.png)

Thanks for reporting the issue! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by revori** [comment] 2021-12-16 13:06
Hi. I had the same issue. For the uninstall function a wrong hook name is used. Instead of 'actionSubmitAccountBefore' 'actionBeforeSubmitAccount' is used. If you change that the uninstall works.

**Comment by alfonsolr09** [comment] 2021-12-17 01:19
https://github.com/PrestaShop/ps_dataprivacy/pull/34

**Comment by PierreRambaud** [comment] 2021-12-20 07:45
Duplicates of #23708
Already fixed in https://github.com/PrestaShop/ps_dataprivacy/pull/21

**Comment by hibatallahAouadni** [comment] 2021-12-20 11:26
Ping @PierreRambaud it's not a duplicate cause that PR was merged in 2.0.1:

![image](https://user-images.githubusercontent.com/23308427/146760120-ec7cafe0-d1f1-42c1-b50c-aa8b7efc3a40.png)

And as you can see in my comment above, I reproduce the issue with DataPrivacy v2.0.1:

![image](https://user-images.githubusercontent.com/23308427/146760289-a53bbb0d-a4cc-45dc-8857-0d7082e78e07.png)

Thanks!

**Comment by PierreRambaud** [comment] 2021-12-20 13:08
It targeted the wrong milestone, the fix is not released yet

**Comment by hibatallahAouadni** [comment] 2021-12-21 08:32
Hello everyone,

@PierreRambaud Thanks for the correction and clarification :pray: 
@alfonsolr09 Sorry but I have to close the issue. This issue is a duplicate of #23708. 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-21 08:32
Duplicate of #23708

**Closed as completed by hibatallahAouadni** 2021-12-21 08:32 UTC
Labels: Bug, BO, Duplicate, Dataprivacy, Module manager, 1.7.6.7, Invalid

**Comment by alfonsolr09** [comment] 2021-12-21 08:34
> It targeted the wrong milestone, the fix is not released yet

when will the correction be released?

**Comment by hibatallahAouadni** [comment] 2021-12-21 08:40
@alfonsolr09 v2.0.2

![image](https://user-images.githubusercontent.com/23308427/146898650-dd11efde-6e17-4879-a05a-39858706d760.png)

**Comment by alfonsolr09** [comment] 2021-12-24 21:11
but when will it be released?
