### ISSUE TITLE
Restricted payment method got selected by buyer

### ISSUE THREAD

**Issue by joaolago1113** [PrestaShop/PrestaShop#23190] opened 2021-02-09 12:11 UTC
#### Describe the bug

Somehow one client was able to select a payment method that is not available for the shipping method he choose.
I have the payment method disabled in "Carrier restrictions"  in Payment > Preferences , I've checked this multiple times. There isn't a carrier with the same name.
This is the first time it happened. No other client was able to do this, and I assume they would have choose this shipping x payment methods had they been able to because it's a cheaper combination.

#### Expected behavior

This payment method should not have been shown for the selected shipping carrier.

#### Steps to Reproduce

The main problem is here, I can't reproduce the problem. I've tried purchasing the same product the client did, choosing the same carrier and I'm never shown the incorrect payment method chosen by this specific client. I've tried multiple ways, going back and selecting a different carrier and then selecting again the carrier in question, and other things.

1. Add product to cart;
2. Checkout up until the payment step;
3. Go back to your cart;
4. Remove the product from your cart;
5. Go to the products page;
6. Add again the same product to the cart;
7. Finalize checkout;
8. You're taken directly to the fourth payment step WITH ALL THE PAYMENT OPTIONS AVAILABLE.

**Screenshots**

__Carrier method chosen is "CTT económico max. 2kg" and payment method is MBWAY (ifthenpay module):__

![1](https://user-images.githubusercontent.com/22820692/107361702-b4dba480-6acf-11eb-8a5f-7f7a2fd69a74.png)
![2](https://user-images.githubusercontent.com/22820692/107361703-b5743b00-6acf-11eb-91d0-f2011042b843.png)

__Shipping method ("CTT económico max. 2kg") is disabled for the ifthenpay module, which includes MBWAY:__

![3](https://user-images.githubusercontent.com/22820692/107361716-b9a05880-6acf-11eb-88d3-abaa970c98a1.png)
![4](https://user-images.githubusercontent.com/22820692/107361833-e2285280-6acf-11eb-9ab1-46881569c153.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.26

Payment module used is a paid module, not made by Prestashop. I know the problem could come from this module, but since I am never able to reproduce/encounter the same problem as did my client, perhaps the problem is related to Prestashop.

**Comment by hibatallahAouadni** [comment] 2021-02-09 14:42
Hello @joaolago1113 

I didn't manage to reproduce the issue with PS1.7.7.1. As you said, it may be related to the payment module.

Even, the customer try to maniplate the code, the system will not accept the selected payement method and we will change it to the right one, see the attached screen record below:

https://drive.google.com/file/d/1Wk5IkfxHphcAhYdD0RinJr3jHhu7KIMu/view

Well, I'm sorry but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one
of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by joaolago1113** [comment] 2021-02-09 18:14
I FOUND HOW TO REPRODUCE THE BUG!    Works with any payment method.

**Steps to Reproduce:**

1. Add product to cart;
2. Checkout up until the payment step;
3. Go back to your cart;
4. Remove the product from your cart;
5. Go to the products page;
6. Add again the same product to the cart;
7. Finalize checkout;
8. You're taken directly to the fourth payment step WITH ALL THE PAYMENT OPTIONS AVAILABLE.

Also, removing abandoned carts from back office solves this up until the client makes and abandons another cart.

Please re-open this issue @hibatallahAouadni

**Comment by joaolago1113** [comment] 2021-02-10 12:39
I'm almost positive there might be some other way for people to choose any payment. Perhaps using an abandoned cart.
I'm getting a lot of wrongful orders.

**Comment by florine2623** [comment] 2021-03-18 15:59
Hello @joaolago1113 ,

I reproduced your issue with the steps provided in PS 1.7.7.1, 1.7.6.9 and 1.7.5.2.

I am taken directly to the step 4 payment method yes. But I don't see any link between the cart issue and the _payment method selected twice by buyer_.
Could you explain ?

**Comment by florine2623** [comment] 2021-04-07 07:54
Hello,
Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.
Thanks!

**Closed as completed by florine2623** 2021-04-07 07:54 UTC
Labels: Bug, FO, Carriers, Payment methods, No change required, Checkout, 1.7.7.1

**Comment by joaolago1113** [comment] 2021-04-25 14:02
> Hello @joaolago1113 ,
> 
> I reproduced your issue with the steps provided in PS 1.7.7.1, 1.7.6.9 and 1.7.5.2.
> 
> I am taken directly to the step 4 payment method yes. But I don't see any link between the cart issue and the _payment method selected twice by buyer_.
> Could you explain ?

When you're taken to the step 4 payment method, all payment options are enabled to choose from, even the options which should not appear due to the selected shipping method.
