### ISSUE TITLE
re-sending email with status change, account data are empty

### ISSUE THREAD

**Issue by Majusek** [PrestaShop/PrestaShop#18074] opened 2020-03-10 11:38 UTC
#### Describe the bug

Variables related with emails are not displayed in an email bankwire's template. The same situation as like here:
https://github.com/PrestaShop/PrestaShop/issues/16346

#### To Reproduce

1. Go to order details in back office.
2. Click button "resend an email".

#### Additional information

* PrestaShop version: 1.7.4.0

**Comment by khouloudbelguith** [comment] 2020-03-10 12:04
Hi @Majusek,

As you can see in this [comment](https://github.com/PrestaShop/PrestaShop/issues/16346#issuecomment-552403707)
It is not a PrestaShop core issue, it is related to a custom module or an override.
Did you check all your non-native module?

Thanks!

**Comment by Majusek** [comment] 2020-03-10 12:08
Hi @khouloudbelguith 

I disabled overrides and external modules and nothing change. 
My PrestaShop is 1.7.4.0 version. Maybe something was repair in 1.7.6.0?

Could you tell me which codes I should check at first?

**Comment by khouloudbelguith** [comment] 2020-03-10 12:14
@Majusek,

Those options do not work.
![image](https://user-images.githubusercontent.com/16067358/72447578-e3485c80-37b5-11ea-90b5-37fe4a22a963.png)
as reported here:
https://github.com/PrestaShop/PrestaShop/issues/14596
https://github.com/PrestaShop/PrestaShop/issues/9965

Thanks!

**Comment by Majusek** [comment] 2020-03-10 12:45
@khouloudbelguith those issues are still open.

Maybe have You got more advise how to resolve the problem?

**Comment by khouloudbelguith** [comment] 2020-03-10 13:01
@Majusek, you need to check your module as commented [here](https://github.com/PrestaShop/PrestaShop/issues/16346#issuecomment-552403707) but manually.

Thanks!

**Comment by Majusek** [comment] 2020-03-10 14:06
@khouloudbelguith I disabled all externall modules and overrides. Nothing change.

**Comment by khouloudbelguith** [comment] 2020-03-10 15:22
@Majusek, I did not manage to reproduce the issue.
I attached a screen record
https://drive.google.com/file/d/1uC7KWqi1p_UEC0FI0trl2Izo0QlUJpVe/view
The Email address in uppercase? is it similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/13386?

Thanks!

**Comment by marionf** [comment] 2020-04-08 13:27
Hello,
Since we had no news from you for more than 25 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Closed as completed by marionf** 2020-04-08 13:27 UTC
Labels: Bug, BO, Order, 1.7.4.0, Email, No change required
