### ISSUE TITLE
Email subject incorrectly uses entities for a shop name

### ISSUE THREAD

**Issue by rmilecki** [PrestaShop/PrestaShop#17182] opened 2020-01-15 13:45 UTC
**Describe the bug**
If `PS_SHOP_NAME` contains some special characters they get incorrectly (unnecessarily) encoded into entities in email subject.

**To Reproduce**
1. Set `PS_SHOP_NAME` to `My śhóp / Geschäft`
2. Send e-mail

**Screenshots**
![emails](https://user-images.githubusercontent.com/452972/72438545-539ab200-37a5-11ea-8db0-e4cf07704dcd.png)
![gmail](https://user-images.githubusercontent.com/452972/72438700-ae340e00-37a5-11ea-8c1d-d27453fb583c.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.1.33

**Comment by rmilecki** [comment] 2020-01-15 13:46
I think that `send()` in `Mail.php` should use `strip_tags()` instead of `Tools::safeOutput`.

**Comment by khouloudbelguith** [comment] 2020-01-15 14:05
Hi @rmilecki,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16847
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-01-15 14:05
Duplicate of #16847

**Closed as completed by khouloudbelguith** 2020-01-15 14:05 UTC
Labels: Duplicate
