### ISSUE TITLE
Undefined offset error, In Post method of Web-services of Prestashop

### ISSUE THREAD

**Issue by amansrivastava8355** [PrestaShop/PrestaShop#11871] opened 2018-12-20 08:26 UTC
Undefined offset error, In Post method of Web-service of Prestashop, while using **output_format JSON**
[Error Screnshot](https://prnt.sc/lxc5nz)

**Comment by khouloudbelguith** [comment] 2018-12-20 08:29
Hi @amansrivastava8355,

Thanks for your report.
Heres' a fix https://github.com/PrestaShop/PrestaShop/issues/11840#issuecomment-448635878 to solve your issue.
Your ticket is a duplicate of #11840
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-20 08:30
Duplicate of #11840

**Closed as completed by khouloudbelguith** 2018-12-20 08:29 UTC
Labels: Duplicate
