### ISSUE TITLE
Autoupgrade - BO - Impossible to upgrade the linklist module after an upgrade from 1.7 to 8.0

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29700] opened 2022-09-20 09:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is reported here in this [comment](https://github.com/PrestaShop/autoupgrade/pull/504#pullrequestreview-1107809323) (Issue1).

Impossible to ugragde the linklist module after an upgrade from 1.7.7.8 to 8.0 and 1.7.8.7 to 8.0

When add a new block on a linklist, there is an exception. It's the same of this fixed [issue](https://github.com/PrestaShop/PrestaShop/issues/28120)  on 5.0.5 released version.
When i want to upgrade the linklist module, the option to upgrade is not displayed. (With this [PR](https://github.com/PrestaShop/autoupgrade/pull/504))

https://user-images.githubusercontent.com/92912932/191219156-a6e4a47c-4f38-4c9a-8b86-b686c5f2c20f.mp4

![image](https://user-images.githubusercontent.com/92912932/191219067-28f20934-7823-43a2-9b83-89dbd24c60b6.png)

> Edit by @HanaRebaiQA 

 Since this  [PR](https://github.com/PrestaShop/autoupgrade/pull/504) is merged, so the alert of inactive will not displayed (only the issue mentioned above will be displayed)

> Without this [PR](https://github.com/PrestaShop/autoupgrade/pull/504), there is an alert `ps_linklist ` is inactive

![image](https://user-images.githubusercontent.com/92912932/191301784-0b65b119-170a-42a0-b06f-6b5c0399673a.png)

https://user-images.githubusercontent.com/92912932/191301720-d584a877-78db-4f12-92f6-6003146495f9.mp4

 
### Expected behavior

The option to upgrade should be displayed to can upgrade to linklist module

### Steps to reproduce

1. Install PS1778 OR PS1787
2. Uninstall problematic modules (welcome, ps_mbo, pd_metrics, facebook, psxmarketingwithgoogle)
3. Install the autoupgrade v4.15 module from dev branch
4. Install a new 8.0.x branch
5. Create a release from 8.0.0
6. Configure the autoupgrade module
7. Upgrade to 8.0.0 branch
8. Check the 8.0.0 is well upgraded
9. Go to BO > IMPROVE > Design > Link list > Add new block 
10. See error > This [issue](https://github.com/PrestaShop/PrestaShop/issues/28120) is displayed which is already fixed on 5.0.5 released version
11. GO to BO > Module manager > Search for link list module 
12. See error > The option to upgrade is not displayed! (When the new autoupgrade module will released with this [PR](https://github.com/PrestaShop/autoupgrade/pull/504))

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Autoupgrade v4.15.0 from dev branch

**Comment by hibatallahAouadni** [comment] 2022-09-27 14:54
Hello @HanaRebaiQA 

As you can see I can reproduce only the first issue but it seems related to the issue that ou're already mentioned above:

https://user-images.githubusercontent.com/23308427/192484590-bdd136b6-361b-4795-9bf9-0439a5aaee8a.mp4

AFAIK, this regression has been fixed on Linklist v5.0.5, so I tried to uninstall the linklist v5.0.4 cause I can't upgrade it (caused by this issue #29594, and Install the linklist v5.0.5, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/192560344-886265c0-4662-4173-b376-97af31fb9166.mp4

I found another regression on the module linklist v5.0.5 only when we disbaled the debug mode :disappointed: 
Ping @Progi1984 could you please check this behavior cause it seems that you fixed this issue #28120 by this PR https://github.com/PrestaShop/ps_linklist/pull/147

@HanaRebaiQA should we remove the 2 last steps cause I didn't manage to reproduce :relaxed: 

Thanks!

**Comment by RosaBenouamer** [comment] 2023-05-15 14:36
@AureRita : does this issue exist fro fresh install 8.0 ?

**Comment by gericfo** [comment] 2024-05-07 09:12
@AureRita could you try to reproduce it on a fresh install like suggested @RosaBenouamer ? Thanks!

**Comment by AureRita** [comment] 2024-07-15 10:06
Hi @gericfo 

Currently this issue isn't on 8.0.1 fresh install, but if I do an upgrade from 1.7.7.8 to a major (here 8.1.7) I have this : 

[recording(255).webm](https://github.com/user-attachments/assets/25bd2182-d595-467a-a61a-eeb3d72e9759)

But I can upgrade the module linklist, 
After the upgrade of it, I didn't have the issue 

So I think we can close this issue ( indeed we can do the upgrade of the module )

**Closed as completed** 2024-07-15 10:06 UTC
Labels: Bug, 8.0.x, Minor, BO, Design, Regression, Autoupgrade, Linklist, Verified, Module, Backlog SUE
