### ISSUE TITLE
GPDR module or Customer comments  dont show GPDR check

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#23709] opened 2021-03-19 22:58 UTC
#### Describe the bug

When you write a coment of one product prestashop with GPDR module installed dont show the checkbox with message of data privacy to the client

#### Steps to Reproduce

1. Install GPDR module and configure the messages
2. Install customer comments 
3. (This two modules are installed per default in prestashop 1.7.7.2
4. Click in a product
5. Write a review (logued in an account or not)
6. this won't show the checkbox to accept the data privacy and capture the intention from the client

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-03-22 10:48
Hello @TecnoHands 

Did you mean by Customer Comment the Module **ProductComment**:

![image](https://user-images.githubusercontent.com/23308427/111978262-054d1580-8b04-11eb-85d4-c987cf6acd36.png)

If so, we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16505. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-22 10:48
Duplicate of #16505

**Closed as completed by hibatallahAouadni** 2021-03-22 10:48 UTC
Labels: Duplicate
