### ISSUE TITLE
BO - The module manager page and Positions page are NOK - Error 500

### ISSUE THREAD

**Issue by Out24-ad** [PrestaShop/PrestaShop#20345] opened 2020-07-25 12:20 UTC
When trying to access the module manager or ap page builder hook manager. I get the following error

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
A clear and concise description of what went wrong.

#### Expected behavior

the links are supposedto direct me to my modules installed

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-07-27 08:10
Hi @Out24-ad,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-29 07:50
Hi @Out24-ad,

On this github repository there is no software support. This is an open-source project.
Our team created a few templates to help you provide the information that’s typically needed to reproduce an issue.
Thanks to follow the exact template when creating an issue.

You can find help

1. on PrestaShop forums https://www.prestashop.com/forums/
2. or by purchasing software support plan from https://www.prestashop.com/en/support

I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-07-29 07:50 UTC
Labels: Bug, BO, No change required, Module manager
