### ISSUE TITLE
Cache problem prestashop 1.7

### ISSUE THREAD

**Issue by itsoftgroup01** [PrestaShop/PrestaShop#22566] opened 2020-12-23 15:07 UTC
Hello,

So I don't know what site to write on.
I'll explain the problem first.
I have an online store and integrated in it I have a feed that updates my prices every day. After the price update, the change is not seen in chrome, only on incognito. If I enter chrome normally and delete the cache, it shows the good prices after the first refresh, but if I give it another refresh, it shows me the old prices.
Please, I left posts all the internet sites and forums for this. What plugin do I need or do I need a script on cron jobs to delete my cache in my site.

My theme is AngarTheme, buyed from prestashop.com

If there is here someone to know a script that can be added in cron jobs (in cpanel) and can be run automatically to delete cache from site..

Site: http://www.macoshop.ro

Maybe I didn't post where I should and I apologize a thousand times for that.

in cache mode is set compile when changes

I have add and php script like this

 

<?php

require(dirname(__FILE__).'/config/config.inc.php');

//change 'abc123' to any value you wish to use
$token = Tools::getValue('token');
if (!$token || $token != 'pasword')
     die();

Tools::clearSmartyCache();
Tools::clearXMLCache();
Media::clearCache();
PrestaShopAutoload::getInstance()->generateIndex();
echo "Cache cleared";

?>

but in product when i click on product on quick view, i see another price than the principal price

I thank you from the bottom of my heart.

**Comment by Hlavtox** [comment] 2020-12-23 15:34
@itsoftgroup01 There must be some kind of module or external proxy cache enabled. I see you are using Cloudflare, maybe that's the issue.

If the prices change when opening the page from different browser, the issue is not in Prestashop itself.

______________

PS: If you are changing prices by external script, it would be good to implement a logic, that flushes faceted search cache, if the price changed.

**Comment by hibatallahAouadni** [comment] 2020-12-23 15:58
Hello @itsoftgroup01 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

@Hlavtox Thanks for your quick reply :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-12 17:40
Hello @itsoftgroup01 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-12 17:40 UTC
Labels: Bug, 1.7.x, CO, Performance, No change required
