### ISSUE TITLE
Wrong conversion when adding a product in BO in a different currency

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#16937] opened 2019-12-27 11:17 UTC
**Describe the bug**
In BO, when adding a product to an order which was made in a different currency from the default one, the "Total" price is wrong, probably because the price is converted twice.

**To Reproduce**
1. Install PS in Euro (Country : France for example)
2. On BO, add a country with another currency with localization pack (for example, Algeria)
3. On FO, make an order with this new currency (in my case, DZD) 
4. On BO, add a product to this order, still with the new currency
5. In the "bottom" block which recap the whole order, "Products" and "Total" are wrong, so is the currency sign
6. Change status of the order to "Payment accepted", consult the invoice : The sums in the invoice are wrong too (but currency sign is OK)

What happens here, IMHO, is that the product is converted from Euro to DZD a first time for display in the product list when adding the product, and a second time when clicking the "add" button, and the "Total" sums are recalculated...

**Screenshots**
Wrong sum at the bottom of the order
![Add product Currency wrong](https://user-images.githubusercontent.com/55688534/71515112-f3010f00-28a1-11ea-864c-ce08b23c0ffa.png)

Wrong invoice
![Add product Currency wrong invoice](https://user-images.githubusercontent.com/55688534/71515115-f6949600-28a1-11ea-9f3f-9a52f8a7509b.png)

**Additional information**
PrestaShop version: 1.7.5 to develop at least
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-12-30 08:30
Hi @Robin-Fischer-PS,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12521
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-30 08:30
Duplicate of #12521

**Closed as completed by khouloudbelguith** 2019-12-30 08:30 UTC
Labels: Duplicate
