### ISSUE TITLE
Products in orders are shown in reverse order (from last to first product)

### ISSUE THREAD

**Issue by Kerami82** [PrestaShop/PrestaShop#22853] opened 2021-01-15 13:45 UTC
When I update my shop to 1.7.7.1 products in orders are shown in reverse order. This is problem becouse when I download them to an external inventory management, the order is different.

How to check this:
As client add to cart product 1, then product 2. Make order. Go to this order in BO. Product 2 is on first place, and product 1 on second place. In order confirmation email order of products is OK - product 1, then product 2.

**Comment by Kerami82** [comment] 2021-01-15 14:00
<img width="957" alt="shoping cart" src="https://user-images.githubusercontent.com/37613614/104735808-588c9b80-5742-11eb-8074-421c29662a4b.png">
<img width="948" alt="order" src="https://user-images.githubusercontent.com/37613614/104735811-59bdc880-5742-11eb-94a9-afb794c00764.png">

**Comment by florine2623** [comment] 2021-01-15 14:04
Hello @Kerami82 ,

I was able to reproduce the issue with PrestaShop version 1.7.7.1. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

In shopping cart, the product reference is the name of the product instead of the product reference.

![Capture d’écran 2021-01-15 à 15 02 24](https://user-images.githubusercontent.com/16019289/104736157-d781d400-5742-11eb-89b8-2c7aac32bc3a.png)
![Capture d’écran 2021-01-15 à 15 02 15](https://user-images.githubusercontent.com/16019289/104736167-d9e42e00-5742-11eb-9967-1c4a0831b488.png)

Thank you

**Comment by florine2623** [comment] 2021-01-15 14:16
Hello @Kerami82 ,

I was able to reproduce the issue with PrestaShop version 1.7.7.1. It's a regression, 1.7.7.0 didn't have this issue.
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by MatShir** [comment] 2021-06-07 12:58
Hi @Kerami82, 
Thanks for the issue. I would like to understand how does it impact your process (or the process of your client).
Could share with us why and how this new sort impacts your inventory management ?

**Comment by hibatallahAouadni** [comment] 2022-04-18 14:19
Hello @Kerami82 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-04-18 14:19 UTC
Labels: Bug, PM ✔️, Trivial, BO, Order, Regression, PR available, 1.7.7.1, Invalid
