### ISSUE TITLE
Faceted search not working in multilanguage store

### ISSUE THREAD

**Issue by ricardo-lobo** [PrestaShop/PrestaShop#11173] opened 2018-10-29 10:08 UTC
Faceted search does not work when using more than one language. Maybe there's something that is need to setup, but documentation is not clear.

When filtering using English, everything works as expected. When the second language is selected (Eg. Portuguese) an ajax request is fired but the same products are returned in the response. It's like the request params are ignored. 

1. Add a second language other than english to store
2. Try to filter a category
3. If english is picked, everything works fine. If portuguese is picked, nothing happens when a filter is selected.

PrestaShop version: 1.7.4.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-10-29 10:18
Hi @ricardo-lobo,

I did not manage to reproduce your issue.
I attached a video record.
https://drive.google.com/file/d/1KWO4XWZO9wjg0JEgNVTVivCXnoutprzT/view
What is the exact version of the ps_facetedsearch module did you use?
Thanks!

**Comment by ricardo-lobo** [comment] 2018-10-29 12:53
@khouloudbelguith 

I'm using ps_facetedsearch v2.2.1
Strangely this was solved when I activated friendly urls in SEO.

If I disable friendly urls, the problem comes back again.

**Comment by khouloudbelguith** [comment] 2018-10-29 13:10
Hi @ricardo-lobo,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9639
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-29 13:10
Duplicate of #9639

**Closed as completed by khouloudbelguith** 2018-10-29 13:10 UTC
Labels: FO, Duplicate, International, Faceted search, 1.7.4.3
