### ISSUE TITLE
Price per Unit should be calculated instead of set manually

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#23206] opened 2021-02-10 12:29 UTC
Price per unit is now to be filled out in the "pricing" tab, manually by adding the price and the unit.
But, it is completely independent from price changes by any kind of discounts, or even changes of the main selling price, therefore it needs to be updated manually each time the price is changing or a discount rule is applied, which is not practicable.

![grafik](https://user-images.githubusercontent.com/31710761/107510245-f3db2a00-6ba3-11eb-900d-72934cb50600.png)

Better would be to just have the possibility to choose if the price per unit is based on kg, ml, ... and also how many ml are included in the full price and how many ml should be shown and calculated, for example:
Price of product is 75,- - the price per unit should be shown as per 100 ml, would be just necessary to have defined then how many ml are included in the 75,- as with that information the calculation of 1 ml can be done and then for 100 ml as well.

Prestashop 1.7.7.1

**Comment by hibatallahAouadni** [comment] 2021-02-10 13:39
Hello @tom75 

Could you please **respect and follow the provided template to submit a complete bug report**.
We provide this template to resolve your issue as soon as possible, you need to fill all the blocks (describe the bug, expected behavior, steps to reproduce, php version, ...).
Please edit your issue :wink: 

Thanks!

**Comment by Hlavtox** [comment] 2021-02-22 19:10
@tom75 This is how it works - the unit price is just a ratio in a database. However, this ratio is recalculated every time you change product price, which sucks... So you have to always manually recalculate it whenever you change price of the product.

For example, you set product price to 100. You set unit price to 1000, per kg. `10` is saved to database. 
Then when you open BO product page or the product in FO, you see correct price per Kg.
But, when you change product price to 200, the unit price is not recalculated to 2000, but stays 1000 and it saves ratio of 5 to database.

**Comment by Hlavtox** [comment] 2021-02-22 19:17
So, the real problem is, that the field is not recalculated, when you change the price on the left. The data is good. :-)

**Comment by hibatallahAouadni** [comment] 2021-03-12 09:50
Hello @tom75 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-12 09:50 UTC
Labels: Bug, BO, Taxes and Prices, No change required, 1.7.7.1
