### ISSUE TITLE
New products on PrestaShop's demo website

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#14289] opened 2019-06-19 15:14 UTC
**Describe the bug**
On [PS demo site](http://fo.demo.prestashop.com/en/), we can see all products are new. But the [new products page](http://fo.demo.prestashop.com/en/new-products) is empty.

On BO, the "Number of days for which the product is considered 'new"" is set to 20 days. So if products are newer, why new products page is empty? Or if products are older, why do they have the "new" tag? Thanks for help.

Subsidiary question: do you have planned to update the demo PS demo version ([v1.7.4.2 released about a year ago](http://build.prestashop.com/news/prestashop-1-7-4-2-maintenance-release/))?

**Screenshots**
![really-new-products](https://user-images.githubusercontent.com/7419525/59777073-3572df00-92b4-11e9-9a14-e50d4253464f.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.37

**Comment by matks** [comment] 2019-06-19 15:18
> Subsidiary question: do you have planned to update the demo PS demo version ([v1.7.4.2 released about a year ago](http://build.prestashop.com/news/prestashop-1-7-4-2-maintenance-release/))?

Yes, but we also are modifying how the PS Demo works : we replace the previous demo system with a new one. This new system will offer advanced demo capabilities to people and when it's shipped in production will have the 1.7.5 version or even 1.7.6.

So indeed demo is outdated, but the reason why it's outdated is because we are updating the whole demo system, not just the shop 😉

**Comment by khouloudbelguith** [comment] 2019-06-19 15:23
Hi @Klemart3D,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1

This issue occurs only on the demo PrestaShop (old version)
https://drive.google.com/file/d/1QBiOzKKaSwpDRY_ke3ApHLsmydxrylEf/view
@matks said it will be updated to the last version.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-19 15:23 UTC
Labels: Can't reproduce
