### ISSUE TITLE
Wrong Cart Calculation (not depends on decimal round)

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#21071] opened 2020-09-19 11:15 UTC
#### Describe the bug

I still continue to receive errors on calculation where there are presents discounts using vouchers.
A typical order that make wrong calculation is like the following picture.

![image](https://user-images.githubusercontent.com/16102074/93665565-b56b9400-fa77-11ea-93ce-4b850bd5e24d.png)

I thought was a decimal round problem but errors are not on decimal but on unity, even in some case over 2€

Store is located in Italy with 22% tax fee
Customer is in Europe, Hungary, and is a private customer so the 22% tax must be applied.

I've extracted the values from xx_orders table and make a calculation on excel.

![image](https://user-images.githubusercontent.com/16102074/93665615-f2378b00-fa77-11ea-8e37-159dda24e41e.png)

All the value in xx_orders are right, is Prestashop that is not able to make a sum and a difference!

Prestashop calculate 96,20€ as total order, but if i take any single values directly from the database table and recalculate the total in excel, keeping same decimal present on database the right result is 95.21€ (tax included)

I've also make another way to calculate the total keep the values w/o tax and multiply for 1.22 (22% tax fee) and recalculate every value with a slight 0.013400 € difference and anyway the total obtained is not 96,20€.

#### Expected behavior

Using values directly from the xx_orders table and make a SUM the total must be 95.21€ not 96.20€ (diff: 0,99€)

#### Steps to Reproduce

I have included in a zip file all tables and row involved in the order in CSV format so anyone can take a look.

[csv_export.zip](https://github.com/PrestaShop/PrestaShop/files/5249737/csv_export.zip)

I was not able to understand why Perstashop is unable to do a simple calculation iof all the number are right!
I've opened soem days ago another ticket about calculation thinking of a round problem: https://github.com/PrestaShop/PrestaShop/issues/20889

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33

**Comment by sarahdib** [comment] 2020-09-21 08:22
Hello @HartLarsson 
Is your issue relate to : [#9981](https://github.com/PrestaShop/PrestaShop/issues/9981) ?
Thanks!

**Comment by HartLarsson** [comment] 2020-09-21 10:49
> Hello @HartLarsson
> Is your issue relate to : [#9981](https://github.com/PrestaShop/PrestaShop/issues/9981) ?
> Thanks!

Hi Sara, no the round calculation is perfect. Seems prestashop make a wrong sum and difference. Is why i included all CSV of the related table of the order where there are all the right values.

**Comment by taniacr** [comment] 2020-09-21 15:31
Any feedback on this issue?
We're using 1.7.6.7 with the same problem

**Comment by khouloudbelguith** [comment] 2020-09-28 14:13
@HartLarsson, you just created another issue, I'm trying to reproduce it.
Is it similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/20981?

Thanks!

**Comment by HartLarsson** [comment] 2020-09-29 17:07
> @HartLarsson, you just created another issue, I'm trying to reproduce it.
> Is it similar to this ticket: #20981?
> 
> Thanks!

hi, this time the values in the DB are right, is only prestashop that not calculate the right sum and difference.

**Comment by khouloudbelguith** [comment] 2020-10-05 09:36
@HartLarsson, as commented here: https://github.com/PrestaShop/PrestaShop/issues/20981#issuecomment-703517288
This issue is related to your module.
>is only prestashop that not calculate the right sum and difference.

About this issue, it similar to this: https://github.com/PrestaShop/PrestaShop/issues/9779#issuecomment-415125166
Can I close the issue? it is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9779.

Thanks!

**Comment by HartLarsson** [comment] 2020-10-05 10:04
> @HartLarsson, as commented here: [#20981 (comment)](https://github.com/PrestaShop/PrestaShop/issues/20981#issuecomment-703517288)
> This issue is related to your module.
> 
> > is only prestashop that not calculate the right sum and difference.
> 
> About this issue, it similar to this: [#9779 (comment)](https://github.com/PrestaShop/PrestaShop/issues/9779#issuecomment-415125166)
> Can I close the issue? it is a duplicate of #9779.
> 
> Thanks!

I've verified that is not caused by any module.

Is not similar to #9779 because in the database all parts aer calculated right. Is only the final calculation (product total + shipping - discount) that is not calculated right,

Is not a problem of decimal rounding.
I've included the db table export you can see inside that all parts are calculated in the right way.

**Comment by khouloudbelguith** [comment] 2020-10-05 13:28
@HartLarsson, O I tried with PS1.7.6.8 and 1770rc1 without any custom plugins and the total is OK
Order_deatil
![image](https://user-images.githubusercontent.com/16067358/95081563-033ff780-071a-11eb-9767-1fe1dfeb9e88.png)
Product list page
![image](https://user-images.githubusercontent.com/16067358/95081549-ff13da00-0719-11eb-8cd6-f88205b717ef.png)
ps_orders table
![image](https://user-images.githubusercontent.com/16067358/95081874-7ea1a900-071a-11eb-913f-796eef159d93.png)

Thanks to check and feedback.

**Comment by HartLarsson** [comment] 2020-10-09 08:36
i've disabled Smarty cache and for now i've not received other calculation problem.
Now we need to understand why with smarty cache enabled the calculation was wrong.

**Comment by khouloudbelguith** [comment] 2020-10-12 11:46
@HartLarsson,

Can you please provide me the exact configuration in the Smarty Cache?
In my case, I'm disabling the cache, setting the option "Template compilation" to Force compilation.
![image](https://user-images.githubusercontent.com/16067358/95742853-00e91a80-0c91-11eb-9ecc-e35160c66f0c.png)
It is ok
![image](https://user-images.githubusercontent.com/16067358/95742993-460d4c80-0c91-11eb-9086-206dba064db4.png)


Thanks!

**Comment by HartLarsson** [comment] 2020-10-15 20:33
i had problems with this configuration:

![image](https://user-images.githubusercontent.com/16102074/96182950-7d505780-0f36-11eb-987d-e4dbf45f4861.png)

**Comment by khouloudbelguith** [comment] 2020-10-19 08:52
Hi @HartLarsson,

I attached a new screen record
https://drive.google.com/file/d/1wDKc7PZ62BR2XKoUVviBXdEPd8zuAKkR/view?usp=sharing
It is ok with this configuration.

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment] 2020-11-04 11:25
Hello @HartLarsson 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-04 11:25 UTC
Labels: Bug, Discounts, Taxes and Prices, No change required, 1.7.6.7
