### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#35628] opened 2024-03-12 14:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When installing Prestashop 8.1.4 I get the following error:
Warning: rename([]index.php.tmp,[]index.php): Access denied (code:5) in index.php on line 1338 ("error":false,"numfiles":28574,"lastId":29000)
![access denied](https://github.com/PrestaShop/PrestaShop/assets/13930107/83f4aa5a-22a3-4342-866b-ac81aae1fdd2)

This is rather strange as some time ago I installed PS 8.1.1 without problems under PHP 7.4. That is the same install file. So there must be something strange with PHP 8.1.

Following that I rename the file manually and then I start /install/index.php. This starts the proper installation.

Unfortunately this installation only goes until 56%. Then I get a rather vague message:
1: HTTP 500 - error - {"success":true,"message":""}
![install56](https://github.com/PrestaShop/PrestaShop/assets/13930107/e3302371-0977-4199-a40b-a97a6c347711)

When I look in the error log of the server I an error about Swiftmailer: PHP Fatal error:  Uncaught Error: Failed opening required 'D:\\xampp814\\htdocs\\_ps814\\var\\cache\\prod\\ContainerHxgZQPu\\getSwiftmailer_EmailSender_ListenerService.php' 

When I check this "ContainerHxgZQPu" no longer exists. The complete error message is very long. What is happening here?

> [Tue Mar 12 14:32:32.251574 2024] [php:error] [pid 36576:tid 1956] [client ::1:59935] PHP Fatal error:  Uncaught Error: Failed opening required 'D:\\xampp81\\htdocs\\_ps814\\var\\cache\\prod\\ContainerHxgZQPu\\getSwiftmailer_EmailSender_ListenerService.php' (include_path='D:\\xampp81\\htdocs\\_ps814\\vendor/pear/pear_exception;D:\\xampp81\\htdocs\\_ps814\\vendor/pear/console_getopt;D:\\xampp81\\htdocs\\_ps814\\vendor/pear/pear-core-minimal/src;D:\\xampp81\\htdocs\\_ps814\\vendor/pear/archive_tar;D:\\xampp81\\php\\PEAR') in D:\\xampp81\\htdocs\\_ps814\\var\\cache\\prod\\ContainerHxgZQPu\\appAppKernelProdContainer.php:2224\nStack trace:\n#0 D:\\xampp81\\htdocs\\_ps814\\var\\cache\\prod\\ContainerHxgZQPu\\appAppKernelProdContainer.php(2631): ContainerHxgZQPu\\appAppKernelProdContainer->load('getSwiftmailer_...')\n#1 D:\\xampp81\\htdocs\\_ps814\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\EventDispatcher\\EventDispatcher.php(301): ContainerHxgZQPu\\appAppKernelProdContainer->ContainerHxgZQPu\\{closure}()\n#2 D:\\xampp81\\htdocs\\_ps814\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\EventDispatcher\\EventDispatcher.php(264): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}(Object(Symfony\\Component\\Console\\Event\\ConsoleErrorEvent), 'console.error', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#3 D:\\xampp81\\htdocs\\_ps814\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\EventDispatcher\\EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'console.error', Object(Symfony\\Component\\Console\\Event\\ConsoleErrorEvent))\n#4 D:\\xampp81\\htdocs\\_ps814\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\EventDispatcher\\EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'console.error', Object(Symfony\\Component\\Console\\Event\\ConsoleErrorEvent))\n#5 D:\\xampp81\\htdocs\\_ps814\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php(242): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\Console\\Event\\ConsoleErrorEvent), 'console.error')\n#6 D:\\xampp81\\htdocs\\_ps814\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Console\\Application.php(83): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\NullOutput))\n#7 D:\\xampp81\\htdocs\\_ps814\\src\\Adapter\\Cache\\Clearer\\SymfonyCacheClearer.php(103): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\NullOutput))\n#8 [internal function]: PrestaShop\\PrestaShop\\Adapter\\Cache\\Clearer\\SymfonyCacheClearer->PrestaShop\\PrestaShop\\Adapter\\Cache\\Clearer\\{closure}()\n#9 {main}\n  thrown in D:\\xampp81\\htdocs\\_ps814\\var\\cache\\prod\\ContainerHxgZQPu\\appAppKernelProdContainer.php on line 2224, referer: http://localhost/_ps814/install/index.php

### Expected behavior

correct installation

### Steps to reproduce

Install under Windows and Xampp with PHP 8.1.

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2024-03-12 19:53
Yes, I can confirm this. It's impossible to install Prestashop under Windows now. Sad.

**Comment by florine2623** [comment] 2024-03-13 08:49
Hello @musicpanda , 

You issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/35044

I'm closing it to avoid clogging the backlog !
Thanks!

**Closed as completed by florine2623** 2024-03-13 08:49 UTC
Labels: Bug, Duplicate

**Comment by musicpanda** [comment] 2024-03-13 10:02
I mentioned two problems. The Swiftmailer problem is discussed in #35044 . But the rename problem isn't.

**Comment by Hlavtox** [comment] 2024-03-13 11:32
@musicpanda It's the same issue, it's some problem with cache locking or something, it tries to load something from a container that is no longer there.

**Comment by musicpanda** [comment] 2024-03-13 11:37
@Hlavtox No, it is not the same. This problem happens already in 8.1.2. The other problem starts in 8.1.3.

**Comment by jumat-dt** [comment] 2024-04-19 06:39
> @Hlavtox No, it is not the same. This problem happens already in 8.1.2. The other problem starts in 8.1.3.

Try install 8.0.4 and then update to 8.1.5.

**Comment by jumat-dt** [comment] 2024-04-19 06:40
Try install 8.0.4 and upgrade to 8.1.5

**Comment by musicpanda** [comment] 2024-04-24 18:01
Correction: the Swiftmailer problem is not discussed in #35044. 

It is a problem that only happens when you restart the installation. And in that case it already happens with 0%. There must be something in the filesystem that triggers this. But emptying the cache and the database was not enough to get rid of it.

**Comment by Zudjo** [comment] 2024-05-26 22:33
I'm having this problem on linux with prestashop 8.1.6, can't understand why, maybe the aruba hosting?

I'm leaving the logs if someone is willing to help me.

```
FIRST TRY

27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "[27-May-2024 00:11:46 Europe/Rome] PHP Warning: filemtime(): stat failed for /web/htdocs/mypath/var/cache/prod/ContainerESVfqis/appAppKernelProdContainer.php in /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 109"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "[27-May-2024 00:11:46 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerESVfqis/getConsole_Command_CacheWarmupService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerESVfqis/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "[27-May-2024 00:11:46 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerESVfqis/getConsole_Command_CacheWarmupService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerESVfqis/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "[27-May-2024 00:11:46 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerESVfqis/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerESVfqis/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "[27-May-2024 00:11:46 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerESVfqis/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerESVfqis/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "[27-May-2024 00:11:46 Europe/Rome] PHP Fatal error: Uncaught Error: Failed opening required '/web/htdocs/mypath/var/cache/prod/ContainerESVfqis/getSwiftmailer_EmailSender_ListenerService.php' (include_path='/web/htdocs/mypath/vendor/pear/pear_exception:/web/htdocs/mypath/vendor/pear/console_getopt:/web/htdocs/mypath/vendor/pear/pear-core-minimal/src:/web/htdocs/mypath/vendor/pear/archive_tar:.:/php8.1/lib/php') in /web/htdocs/mypath/var/cache/prod/ContainerESVfqis/appAppKernelProdContainer.php:2256"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "Stack trace:"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#0 /web/htdocs/mypath/var/cache/prod/ContainerESVfqis/appAppKernelProdContainer.php(2670): ContainerESVfqis\appAppKernelProdContainer->load()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#1 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(301): ContainerESVfqis\appAppKernelProdContainer->ContainerESVfqis\{closure}()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#2 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#3 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#4 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#5 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#6 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#7 /web/htdocs/mypath/src/Adapter/Cache/Clearer/SymfonyCacheClearer.php(103): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()"
27/05/2024 00:11:46 	WARNING: [pool mydomain] child 63 said into stderr: "#8 [internal function]: PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer->PrestaShop\PrestaShop\Adapter\Cache\Clearer\{closure}()" 

SECOND TRY

27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: filemtime(): stat failed for /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php in /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 109"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getThemeEnablerCommandService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getThemeEnablerCommandService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getConsole_Command_CacheWarmupService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getConsole_Command_CacheWarmupService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Fatal error: Uncaught Error: Failed opening required '/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getSwiftmailer_EmailSender_ListenerService.php' (include_path='/web/htdocs/mypath/vendor/pear/pear_exception:/web/htdocs/mypath/vendor/pear/console_getopt:/web/htdocs/mypath/vendor/pear/pear-core-minimal/src:/web/htdocs/mypath/vendor/pear/archive_tar:.:/php8.1/lib/php') in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php:2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "Stack trace:"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#0 /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php(2670): ContainerZLmtFjX\appAppKernelProdContainer->load()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#1 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(301): ContainerZLmtFjX\appAppKernelProdContainer->ContainerZLmtFjX\{closure}()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#2 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#3 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#4 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#5 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#6 /web/htdocs/mypath/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#7 /web/htdocs/mypath/src/Adapter/Cache/Clearer/SymfonyCacheClearer.php(103): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#8 [internal function]: PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer->PrestaShop\PrestaShop\Adapter\Cache\Clearer\{closure}()"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: "#9 {main}"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 81 said into stderr: " thrown in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 80 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getPrestashop_Translation_TranslatorLanguageLoaderService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256"
27/05/2024 00:20:13 	WARNING: [pool mydomain] child 80 said into stderr: "[27-May-2024 00:20:13 Europe/Rome] PHP Warning: require(/web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/getPrestashop_Translation_TranslatorLanguageLoaderService.php): Failed to open stream: No such file or directory in /web/htdocs/mypath/var/cache/prod/ContainerZLmtFjX/appAppKernelProdContainer.php on line 2256" 
```
