### ISSUE TITLE
Price specification not found for currency: ""

### ISSUE THREAD

**Issue by presciak** [PrestaShop/PrestaShop#18127] opened 2020-03-12 21:43 UTC
I have a problem updating my store

My store is a multistore.
The store has 5 subdomains. Each domain is a different language or currency.
Before the upgrade, all additional modules (couriers, payments, etc.) were disabled - (removed from ftp).
Before updating the cash has been cleared from the panel presty
For the upgrade I used the 1-Click upgrade version v4.10.1
Unlocked PHP exec function
WAF (firewall) has been disabled
PrestaShop version: 1.7.5.2 -> 1.7.6.4

**configuration**

![cong2](https://user-images.githubusercontent.com/53096552/76567912-10f90b80-64b0-11ea-9a9b-a14abba5ad85.jpg)

During the upgrade, there were no problems

![update2](https://user-images.githubusercontent.com/53096552/76568106-7d740a80-64b0-11ea-9ddb-e0c68b6f5e04.jpg)

After the update is a management panel to which you can not log in

![back-office2](https://user-images.githubusercontent.com/53096552/76568329-eb203680-64b0-11ea-8c92-b710274791fd.jpg)

When you try to log in to the store panel shows the error 500

![error500](https://user-images.githubusercontent.com/53096552/76568398-0f7c1300-64b1-11ea-97b7-5eab53735779.jpg)

After you turn on debug mode

![dev-mod1](https://user-images.githubusercontent.com/53096552/76568555-5b2ebc80-64b1-11ea-9c52-783e726541db.jpg)

![dev-mod2a](https://user-images.githubusercontent.com/53096552/76568576-67b31500-64b1-11ea-805a-a35d42792987.jpg)

![dev-mod3a](https://user-images.githubusercontent.com/53096552/76568593-713c7d00-64b1-11ea-825a-5a769ea176fc.jpg)

Xxx – admin
Zzz – domena

**Update logs**

[log_presta.txt](https://github.com/PrestaShop/PrestaShop/files/4326735/log_presta.txt)

Anyone have an idea to solve the problem?

**Comment by khouloudbelguith** [comment] 2020-03-16 11:31
Hi @presciak,

I did not manage to reproduce the issue with PS1.7.6.4 after an upgrade from PS1.7.5.2 using the 1-click upgrade v4.10.1.
I have 5 shops, each shop has a different language and a different currency.
I attached a screen record
https://drive.google.com/file/d/1LqrgDTZq3002U1k-dydjk3eR4tUGAXs9/view
We have similar issues fixed in the last version:
https://github.com/PrestaShop/PrestaShop/issues/15486 fixed by https://github.com/PrestaShop/PrestaShop/pull/15643 in PS1.7.6.2
https://github.com/PrestaShop/PrestaShop/issues/15376 fixed by https://github.com/PrestaShop/PrestaShop/pull/15643 in PS1.7.6.2.
https://github.com/PrestaShop/PrestaShop/issues/15144 fixed by https://github.com/PrestaShop/PrestaShop/pull/15173 in PS1.7.6.1
https://github.com/PrestaShop/PrestaShop/issues/14608 fixed by https://github.com/PrestaShop/PrestaShop/pull/14664 in PS1.7.6.1.
https://github.com/PrestaShop/PrestaShop/issues/14595 fixed by https://github.com/PrestaShop/PrestaShop/pull/15173 in PS1.7.6.1.

Thanks to check a nd feedback.

**Comment by sarahdib** [comment] 2020-04-15 16:02
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-04-15 16:02 UTC
Labels: Bug, BO, Multistore, Currencies, Autoupgrade, No change required, 1.7.6.4
