### ISSUE TITLE
Bug with Transfer a insident in Client atention

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#29076] opened 2022-07-14 01:05 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you try transfer the issue to another member of team
The message don't transfer.
![image](https://user-images.githubusercontent.com/16818257/178862402-c2ee1075-5ebe-4ada-8fd5-d07dec5cb0b1.png)

and if you respond a message from "webmaster = webmaster@domain" and the IMAP configuration is with "atclient@domain.com" the mail don't send to the client, but if you send a response from "atclient = atclient@domain.com" yes send it.

In previous version of prestashop inclusive ihave my configuration:
SMTP config with a mail account "sender@domain.com" without receiving mails active, only permited send from this.
IMAP has atclient@domain.com
And the config works, in this version don't

The Prestashop Log shows:
Error (3) | Swift Error: Expected response code 354 but got code \"503\", with message \"503-All RCPT commands were rejected with this error:\r\n503-Sender verify failed\r\n503 Valid RCPT command must precede DATA\r\n\"

Another problem in the same section of prestashop, I have No delete mails in the IMAP configuration, anyway Prestashop delete it from server....

I send from gmail a test mail trying if the problem is the hosting, but I receive the mails without problems

Log say:
*DEBUG* 	v1.7.8.6	2022/07/14 - 05:23:37: ERROR Expected response code 250 but got code "550", with message "550-Your FROM address ( mail1 , Servicio al cliente
550-<mail1> ) must match your authenticated email user (
550 mail2 ). Treating this as a spoofed email.

### Steps to reproduce

install a clean prestashop
Config two email accounts in the server
config SMTP and IMAP without mail deletion in server
If you config account 1 in smtp and imap send from contact form a message to account 2 
see your email account email don't show in server
Try to transfer the message to another member team (the other email account) message don't transfer to the other member
try to respond from prestashop
Response never send.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

1.7.4.3

**Comment by TecnoHands** [comment] 2022-07-14 03:35
Solved with this code

https://github.com/PrestaShop/PrestaShop/pull/11995/files

**Comment by TecnoHands** [comment] 2022-07-14 23:52
Prestashop has the same account mail in SMTP, Mail of the store and IMAP
But I receive this Message


Swift Error: Expected response code 250 but got code \"550\", with message \"550-Your FROM address ( soporte@ , Gabriel \r\n550- ) must match your authenticated email user (\r\n550 atcliente@ ). Treating this as a spoofed email.\r\n\"

--

IMAP sync fine in the two mails account receiving the contact form (webmaster and service client)
But only can response one of the two accounts and transfer betwen don't working

**Comment by AureRita** [comment] 2022-07-15 15:19
Hi @TecnoHands, 

Thank you for your reporting, I tried to reproduce your issue but currently I haven't problems about the mails, as you can see on this video : 

https://user-images.githubusercontent.com/100699445/179253893-56951477-3d81-43d6-997b-b678a999a0df.mp4

If there is something that I missed, can you say it please ? 

Waiting for your feedback

**Comment by letwang** [comment] 2022-07-17 12:26
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/3644168/179398233-234ac8c8-c700-4203-ab5c-7da39b31f844.png">
In this way, it is convenient to debug the cause of the SMTP error and facilitate debugging.

**Comment by letwang** [comment] 2022-07-19 01:00
I actually express 3 questions above:
1. The built-in function MAIL in PHP cannot be used, so many users cannot use PrestaShop products normally, which affects the reputation of PrestaShop. PrestaShop forum so many mail question posts is a good proof, and the world-renowned WordPress has not abandoned the PHP built-in function MAIL. (It is recommended to add support for MAIL)
2. The provided sendmail method is equivalent to no effect for the virtual host user, because the virtual host company will not open the command line execution permission for the user, and it is unbelievable to expect the user to develop the MAIL by himself. You want to change all the users. Are you a repairman? (It is recommended to add support for MAIL)
3. It is easy to report errors after SMTP configuration. I found the solution in the above picture. It only needs to return the error report to the front end, which is convenient for users to check the SMTP error report, and finally improves the success rate of SMTP configuration mail. Unfortunately, the official website turns a blind eye to the exception thrown error, so that the user does not know why the SMTP error is reported, and eventually the email cannot be sent. (It is recommended to optimize the error message and return the error to the user to let the user know the error)

![image](https://user-images.githubusercontent.com/3644168/179641230-81dce14b-a222-421c-9e04-a7d1d8732139.png)

**Comment by letwang** [comment] 2022-07-23 03:05
https://blog.presta-modules-addons.com/prestashop/tutorial-consultation/prestashop-smtp-sending-failed-improve-the-smtp-configuration-success-rate-display-the-reason-for-the-failure-to-send-emails/

I deliberately spent a lot of time writing out the solution with pictures and texts, and I hope it will be useful to you.

**Comment by TecnoHands** [comment] 2022-07-28 19:19
> Hi @TecnoHands,
> 
> Thank you for your reporting, I tried to reproduce your issue but currently I haven't problems about the mails, as you can see on this video :
> 
>  Untitled_.Jul.15.2022.5_15.PM.mp4 
> If there is something that I missed, can you say it please ?
> 
> Waiting for your feedback

Hi, I don't see your config, In my case with First option "using SendMail" prestashop works fine, the problem I have when Config with SMTP, Prestashop only works with 1 mail account, the configurated in SMTP Per example, if I config the account noreply@myserv.com in SMTP and IMAP with client@myserv.com Mails sync fine in IMAP, but mail client@myserv.com can't derivate message to support@myserv (another user of prestashop) and support@myserv can't response the message to the client too and mails don't outgoing

**Comment by hibatallahAouadni** [comment] 2022-07-29 16:54
Hello @TecnoHands 

Thanks for your feedback.
Could you please provide a screen record to understand better the issue.
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-19 16:49
Hello @TecnoHands 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-08-19 16:49 UTC
Labels: Bug, BO, Customer service, Email, Invalid, 1.7.8.6
