### ISSUE TITLE
Attribute change *An error occurred while processing your request* with FRIENDLY URL on

### ISSUE THREAD

**Issue by Tominjsh** [PrestaShop/PrestaShop#10575] opened 2018-09-20 21:14 UTC
Still have problem with this error on product page with FRIENDLY URL ON after fixes available below. 
Problem disappears when not using friendly url. 

**Additionnal information**
PrestaShop version: Fresh 1.7.4.2 with https://github.com/PrestaShop/PrestaShop/pull/9390 fixes

using this nginx config https://github.com/PrestaShop/PrestaShop/blob/bffb73a2f893f8e3caf613ba51d2f8f2d5c7c8e5/docs/server_config/nginx.conf.dist

**Comment by khouloudbelguith** [comment] 2018-09-21 07:40
Hi @Tominjsh,

Your ticket is a duplicate of #10178
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-21 07:40
Duplicate of #10178

**Closed as completed by khouloudbelguith** 2018-09-21 07:40 UTC
Labels: Duplicate
