### ISSUE TITLE
Wrong prices for groups without tax

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#12199] opened 2019-01-17 17:22 UTC
Hi
I've found an important error when a customer group is set without taxes
if a product has a discount like of 10€ tax excluded
in the product page in the front-office the save price will include the tax and it become 12,20€ with 22% of tax

in the cart summary there are 2 errors:
- the save prices because they sow prices with tax included
- the original prices will also include the taxes

this problem happens also with percentage discount in the cart summary with the wrong original prices
in the category pages and homepage I don't see errors

**To Reproduce**
- go in the visitor group and set tax excluded
- go in the product with id = 1 and set 10€ with tax excluded
- look at its product page and in the cart summary

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/51336111-0eee1500-1a84-11e9-8f3b-2ef6ea2e7801.png)
![2](https://user-images.githubusercontent.com/653230/51336112-0eee1500-1a84-11e9-91db-91d674290f6b.png)
![3](https://user-images.githubusercontent.com/653230/51336115-0f86ab80-1a84-11e9-9d18-80b3c85d260d.png)
![4](https://user-images.githubusercontent.com/653230/51336116-0f86ab80-1a84-11e9-9f45-4d465216954d.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

bye thanks

**Comment by khouloudbelguith** [comment] 2019-01-18 07:14
Hi @maofree,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9856
So, I close it.
In the PS1.7.6, we are planned to fix prices issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-18 07:14
Duplicate of #9856

**Closed as completed by khouloudbelguith** 2019-01-18 07:14 UTC
Labels: Duplicate
