### ISSUE TITLE
Backoffice 500 error after upgrading modules

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#31922] opened 2023-03-25 09:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When entering the modules tabs in backoffice after a clean 8.0.1 install, i noticed there were 42 module updates available.
I clicked upgrade all but after some time and before finishing , the backoffice crashed with the following error :

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Since this unable to enter the module manager, this will result in above error.

### Expected behavior

Being able to work with the modules.

### Steps to reproduce

Clean install prestashop 8.0.1
Log in in backoffice
enter module manger
upgrade all modules under "module updates"tab
see if backoiffice crashes
try to enter module manager again
see same error

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by FactoryBike** [comment] 2023-03-25 16:06
¿Did you clean cache manually?. In 1.7.8 versión erase all files and directories in var/cache/dev and var/cache/prod

**Comment by paulnoelcholot** [comment] 2023-03-28 10:50
Hello @loetje88,

I have tested your issues and I can't to reproduce the bug, as you can see : 

https://watch.screencastify.com/v/IM4HUxDZ9Zyb9te2fuL6

Am I missing something?

Thanks!

**Comment by sudo-do** [comment] 2023-03-31 10:39
do you have any unoffical module installed?

**Comment by hibatallahAouadni** [comment] 2023-04-12 11:16
Hello @loetje88 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-04-12 11:16 UTC
Labels: Bug, BO, Modules, Invalid, 8.0.1

**Comment by mauricecec** [comment] 2023-06-05 13:54
Dear Sirs 

 i would like to ask if someone get my same prob.

Prestashop 1.7.8.9 Php 7.4 

Shop Work fine , but if i change in Php cgi  7.4 or 7.3 cgi 

i will get Internal Error only in backoffice (Internal Error) , while in frontoffice Work

Kindly ask if someone have suggestion about this issue

Thanks
Regards
