### ISSUE TITLE
Uncaught PHP Exception ICanBoogie\CLDR\NoTerritoryData

### ISSUE THREAD

**Issue by zhoudin** [PrestaShop/PrestaShop#13204] opened 2019-04-04 13:48 UTC
**Describe the bug**
Uncaught PHP Exception ICanBoogie\CLDR\NoTerritoryData: "Territory data is missing."

**To Reproduce**
    1,Background Management 
    2,Localization 
    3,currency 
    4,Adding currency 
    5,"500"" errors in adding currency

**Screenshots**
CRITICAL21:03:23 | request | Uncaught PHP Exception ICanBoogie\CLDR\NoTerritoryData: "Territory data is missing." at

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: 7.3.20

**Comment by khouloudbelguith** [comment] 2019-04-04 14:39
Hi @zhoudin,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-07 07:28
Hi @zhoudin,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-07 07:28 UTC
Labels: BO, Currencies, No change required
