### ISSUE TITLE
Symfony services loaded even if module is disabled

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#28700] opened 2022-06-08 13:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am creating a PrestaShop module, and it looks like the the services from the module are loaded even if the module is disabled.

For example, I created a module with an event subscriber.
The event is triggered even if the module is disabled.

### Expected behavior

Only the `services.yml` from the enabled modules should be loaded.

### Steps to reproduce

1. Create a module
2. Create a Symfony service, for example [an event subscriber](https://symfony.com/doc/3.4/event_dispatcher.html#creating-an-event-subscriber)
3. Install your module
4. Disable it
5. See that the event is triggered even if the module is disabled => this means `services.yml` from disabled module are loaded

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-06-08 16:02
Hello @Seb33300 

Could you please provide a module that contain this service :pray: to reproduce the issue, please :pray: 
Waiting for your module :sweat_smile: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-06-28 15:41
Hello @Seb33300 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-06-28 15:41 UTC
Labels: Bug, CO, Modules, Invalid

**Comment by Seb33300** [comment] 2022-06-29 03:55
Hello @hibatallahAouadni, sorry for the late reply.

Please find an example module using a symfony event subscriber: [sfeventsubscriber.zip](https://github.com/PrestaShop/PrestaShop/files/9007103/sfeventsubscriber.zip)

After installing this module, you will see a message displayed on top of each symfony page (for example, modules or orders pages are using Symfony)

![image](https://user-images.githubusercontent.com/915273/176347980-c50f39ee-0360-4f39-a884-38b334432a4b.png)

If you disable the module, you will see that this message is still displayed.

**Comment by Seb33300** [comment] 2022-06-29 03:57
I did not check how PrestaShop works yet, but I guess the issue is that PrestaShop load the `services.yml` file of the module even if the module is not enabled.
It should load `services.yml` file only if the module is enabled.

**Comment by Seb33300** [comment] 2022-06-29 04:39
The check for enabled module is wrong.
It checks `ps_module.active` field instead of `ps_module_shop` table.

https://github.com/PrestaShop/PrestaShop/blob/742017150438979b7a053288a165111feb52e968/src/PrestaShopBundle/DependencyInjection/Compiler/LoadServicesFromModulesPass.php#L65-L74

But maybe this bug is already fixed in PrestaShop 8? 
Because I see that the code related to this check changed.
