### ISSUE TITLE
Bug in the discount

### ISSUE THREAD

**Issue by AdriCruz** [PrestaShop/PrestaShop#13405] opened 2019-04-15 10:51 UTC
Hello, when I enter a discount coupon in the cart does not show the discount. The discount is applied to the total price but I have to refresh the page so that the discount amount appears. The same thing happens when I delete the discount, I have to refresh the page so that it is permanently deleted. How can it be done automatically?

It happens exactly in the original theme, I have deleted cookies and caches from both my browser and prestashop!

Version PS:  1.7.5.1

![1](https://user-images.githubusercontent.com/43041205/56127278-1175e300-5f7d-11e9-867c-7de26b6b206f.JPG)

**Comment by khouloudbelguith** [comment] 2019-04-15 13:05
Hi @AdriCruz,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1diiYyA5ItZ4biqPNq6dhkRYROaiU1ySt/view  

Thanks for check and feedback.

**Comment by AdriCruz** [comment] 2019-04-15 15:16
It fails me in both places, by chance you know where it is hosted, in what file does that automatic change function? To know where I have the exact fault!

**Comment by khouloudbelguith** [comment] 2019-04-15 15:35
@AdriCruz, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-15 07:25
Hi @AdriCruz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-15 07:25 UTC
Labels: FO, Discounts, No change required
