### ISSUE TITLE
Webservice Api Prestashop 1.6 The field "date_upd" is dynamic. It is not possible to filter GET query with this field.

### ISSUE THREAD

**Issue by ayladt** [PrestaShop/PrestaShop#14606] opened 2019-07-12 08:14 UTC
A customer of us has a prestashop 1.6 ecommerce, and doesn't want migrate to Prestashop 1.7 (I know that the support ends soon) by the moment  .
When using Prestashop Api, two errors occur:
The first error occurs filtering orders / api / orders /? Filter [current_state] = 2 " The field "current_state" is dynamic. It is not possible to filter GET query with this field."

    It's solved modifying WebserverRequest.php class
        //                         if (isset($this->resourceConfiguration['fields'][$field]['getter']))
                                    if (!isset($this->resourceConfiguration['fields'][$field]['getter']))

         

Same error occurs filtering products

    api/products/?filter[date_upd]=%3E[2019-07-09%2011:54:51.193]&date=1: The field "date_upd" is dynamic. It is not possible to filter GET query with this field.

I would appreciate any help you could give me.
Thank you.

**Comment by khouloudbelguith** [comment] 2019-07-12 08:50
Hi @ayladt,

I did not manage to reproduce the issue with PS1.6.1.24 & PS1.7.6.0.
I used those filters:
1. http://shop.com/api/orders/?display=full&filter[current_state]=6
2. http://shop.com/api/products/?display=full&filter[date_upd]=[2019-07-10,2019-07-11]&date=1

Thanks to check & feedback.

**Comment by mariem-abid** [comment] 2019-08-13 07:44
Hi @ayladt,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by mariem-abid** 2019-08-13 07:44 UTC
Labels: WS, Can't reproduce
