### ISSUE TITLE
Wrong format of sample product file

### ISSUE THREAD

**Issue by atulgarg22** [PrestaShop/PrestaShop#12034] opened 2019-01-05 09:33 UTC
**Describe the bug**
Downloadable sample files for product import (CSV) is not having right fields as required by prestashop 1.7.5. Some of fields like "Delivery time of in-stock products" and "Delivery time of out-of-stock products with allowed orders" are missing and some are extra. Which is causing issue in field mapping while product upload.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-01-07 07:45
Hi @atulgarg22,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9764
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-07 07:45
Duplicate of #9764

**Closed as completed by khouloudbelguith** 2019-01-07 07:45 UTC
Labels: Duplicate
