### ISSUE TITLE
PS 1.7.6.7 + GDPR 1.2.1 = No more translations

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#22789] opened 2021-01-12 14:32 UTC
#### Describe the bug

I've updated to 1.2.1 version but i notice now that in My Account page customers see all the GDPR part in english only,

#### Expected behavior

Usually when customer change languafge also the gdpr menu language change.
All translations are present and correct, but the module psgdpr continue to show only the english languageeven if we have 2 language installed.

#### Steps to Reproduce

i simply updated the GDPR module to 1.2.1 version

**Screenshots**

![image](https://user-images.githubusercontent.com/16102074/104327672-5086ee80-54eb-11eb-914c-a132229c82de.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-12 16:13
Hello @HartLarsson 

It's not a bug, it's just missing translations as you can see the attached screen record below:

https://drive.google.com/file/d/1_pvwAKnEPYhY8LDmIk4TSCL8evHAbJxa/view

I close this issue :wink: 
Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-12 16:13 UTC
Labels: No change required

**Comment by HartLarsson** [comment] 2021-01-12 16:30
please reopen because all translation are present!

![image](https://user-images.githubusercontent.com/16102074/104343094-d317aa00-54fb-11eb-9437-94bc4040faec.png)

i've already checked!!!
The GDPR modules come alerady with many translation:

![image](https://user-images.githubusercontent.com/16102074/104343689-897b8f00-54fc-11eb-8f58-cc8291023248.png)

the problem is the other language !=en are not loaded!
