### ISSUE TITLE
Menu not work on PS 1.7.6.9 multistore frontend (only work on default store) 

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#22498] opened 2020-12-18 14:19 UTC
#### Describe the bug

This bug was closed 3 times with all the 3 times wrong conclusion / supposition , so if youi need more information, ask, before close. Theme is classic theme. I've ask 3 times to check the bug in multidomain env, but for now no luck ^^ i've only obtained a bug close without the test i've ask.  So let's see if for the last time in a polite way someone handles this request with respect and competence.

Menu not work on PS 1.7.6.9 multistore frontend (only work on default store

#### Expected behavior

Menù must be shown on all multistore frontend

#### Steps to Reproduce

Configure a ne 
PS 1.7.6.9 fresh install with these exactly configuration:

Theme is default theme.

Create a Mulstistore setup
![image](https://user-images.githubusercontent.com/24798703/102349338-7c25c000-3fa3-11eb-9d9f-4e9020efb329.png)

Check module Menu module position setup
![image](https://user-images.githubusercontent.com/24798703/102349381-8a73dc00-3fa3-11eb-8896-75d1d9d20901.png)

Configure Default store module menu setup:
![image](https://user-images.githubusercontent.com/24798703/102349440-9fe90600-3fa3-11eb-8e27-6741fcb46874.png)

Configure Second store module menu setup:
![image](https://user-images.githubusercontent.com/24798703/102349522-be4f0180-3fa3-11eb-83c1-75e149b801ba.png)

Open frontend store and check for menù

Default store (psmultistore) front end show module menu
![image](https://user-images.githubusercontent.com/24798703/102349561-d1fa6800-3fa3-11eb-85b2-7c89a64da96f.png)

Secondo store front end does not show module menu
![image](https://user-images.githubusercontent.com/24798703/102349582-db83d000-3fa3-11eb-89f2-f45d8d2a2bcf.png)

Cache disabled
![image](https://user-images.githubusercontent.com/24798703/102349604-e3dc0b00-3fa3-11eb-8aa7-4978e00a83aa.png)

PS 1.7.6.9
PHP 7.2

**Comment by hibatallahAouadni** [comment] 2020-12-21 08:37
Hello @matteolavaggi 

I didn't manage to reproduce the issue with PS1.7.6.9, MainMenu v2.1.1 and PHP v7.2, see the attached screen record below:

https://drive.google.com/file/d/17WDyQeKMZIRVt5pui-ZPgCD36CWnUny6/view

In your default shop, I noticed that your search bar is customized, do you use another module for the seatch bar? 
![image](https://user-images.githubusercontent.com/23308427/102756340-038e7d00-4370-11eb-889b-f2bcb1a881de.png)


Please check and feedback.
Thanks!

**Comment by matteolavaggi** [comment] 2020-12-21 09:27
I only use extra css to customize theme. Search was done (in production)
with external javascript layer so is complete independent from theme.


Il giorno lun 21 dic 2020 alle ore 09:38 Hibatallah Aouadni <
notifications@github.com> ha scritto:

**Comment by hibatallahAouadni** [comment] 2020-12-21 11:59
Hello @matteolavaggi 

I'm really sorry but I didn't manage to reproduce it :confused: 
If you're sure that the problem is not from the theme, so could you please provide more details to reproduce your issue.

Thanks!

**Comment by matteolavaggi** [comment] 2020-12-21 13:23
Have you try with multidomain multiple store instead subfolder one? Can
this be related?


Il giorno lun 21 dic 2020 alle ore 12:59 Hibatallah Aouadni <
notifications@github.com> ha scritto:

**Comment by hibatallahAouadni** [comment] 2020-12-25 15:05
Hello @matteolavaggi 

Yes, I have tried and still failed to reproduce the issue, see the attached screen record below:

https://drive.google.com/file/d/1622JiXSG0jRo0NgmWRsbhSceTymsbGTE/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-14 11:53
Hello @matteolavaggi ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-14 11:53 UTC
Labels: Bug, FO, Multistore, Mainmenu, No change required, 1.7.6.9
