### ISSUE TITLE
BUG Duplication uncorrect Features in product page 1.7.6.7

### ISSUE THREAD

**Issue by maxime18dev** [PrestaShop/PrestaShop#23274] opened 2021-02-16 13:45 UTC
#### Describe the bug

In catalogue => product => any product. When you add a feature by filling in only the "custom value" field and save afterwards. The feature remains and each time you save and then refresh the product page, it will duplicate the feature by two. 

#### Expected behavior

It is not possible to save a feature that only has the "custom value" field filled in.

#### Steps to Reproduce

1. Go to 'catalogue => product => any product'
2. Click on 'add a feature => fill in the "personalised value" field then save the product page'
3. Then save and refresh the product page
4. See error : Each time you will do step 3, you will see the number of features multiplied by two

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

![bug1_feature](https://user-images.githubusercontent.com/71233149/108070582-f981b580-7064-11eb-8625-7211ecc6e2a8.png)

![bug2_feature](https://user-images.githubusercontent.com/71233149/108070585-fa1a4c00-7064-11eb-9613-392d19d611f1.png)

![bug3_feature](https://user-images.githubusercontent.com/71233149/108070588-fab2e280-7064-11eb-8a1e-76fe069a0e1e.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3.21

**Comment by hibatallahAouadni** [comment] 2021-02-16 14:33
Hello @maxime18dev 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16306. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: you should downgrade your PHP version to 7.2 cause PS1.7.6.7 is not compatible with PHP7.3 (see [our system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements))

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-16 14:33
Duplicate of #16306

**Closed as completed by hibatallahAouadni** 2021-02-16 14:33 UTC
Labels: Duplicate
