### ISSUE TITLE
BO - Order page - The total price excluding taxes is displayed instead of the total price including taxes

### ISSUE THREAD

**Issue by Bow460** [PrestaShop/PrestaShop#23957] opened 2021-04-09 04:24 UTC
#### Describe the bug

In the BO, within an order, the total price shown in the title row and in the order total block, is shown without taxes instead of the price with taxes, this happens when selecting "show prices: taxes excluded" for a group of clients.

#### Expected behavior

Here are two parts:

1. When you enter in 
the order, the total price of the title and the info block are shown excluding taxes instead of taxes included. (it should be 2.56 Euro)

2. When you click on modify the product, under the column "Total taxes excluded", the price is shown including taxes. When you leave the edition the price returns to being tax excluded

#### Steps to Reproduce

Customer X is in the default group of Customers.

1. Create a product A with a price without taxes of € 2,116 (2.56 with taxes).

2. Go to Store parameters> Customer settings> Groups and modify the Customers group

3. In the section Price display method, change to Tax excluded.

4. In the FO, Customer X places an order with product A and checks that the prices with taxes excluded (€ 2.12) and taxes included (€ 2.56) are displayed in the cart.

5. In the BO, go to Orders> Orders and see the order with Product A. Here the employee sees the total price with taxes included of the order placed (€ 2.56).

6. Enter within the order

7. The employee sees the total price taxes excluded wrongly.

https://user-images.githubusercontent.com/82192606/114123658-07c8b100-98f3-11eb-9999-8e770b8a93f8.mp4

**Screenshots**

![1](https://user-images.githubusercontent.com/82192606/114128020-b670ef80-98fb-11eb-9c84-958c68947d73.png)
![2](https://user-images.githubusercontent.com/82192606/114128021-b7a21c80-98fb-11eb-8ec9-600ac3d4bdbc.png)
![3](https://user-images.githubusercontent.com/82192606/114128024-ba047680-98fb-11eb-9a01-e0bdf8d8058f.png)
![4](https://user-images.githubusercontent.com/82192606/114128026-bb35a380-98fb-11eb-8fef-e025c89bddc5.png)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.27

**Comment by florine2623** [comment] 2021-04-09 12:34
Hello @Bow460 ,

Thanks for the report, I managed to reproduce the bug in PS 1.7.7.0 to 1.7.7.3 :
![Capture d’écran 2021-04-09 à 14 33 47](https://user-images.githubusercontent.com/16019289/114180596-ac251480-9940-11eb-9435-6bc8f29af0b8.png)
![Capture d’écran 2021-04-09 à 14 28 43](https://user-images.githubusercontent.com/16019289/114180527-93b4fa00-9940-11eb-8984-7cd8339b81cc.png)

In PS 1.7.6, the display is different :
![Capture d’écran 2021-04-09 à 14 27 04](https://user-images.githubusercontent.com/16019289/114180612-b3e4b900-9940-11eb-8515-7d5e9b6605e6.png)
![Capture d’écran 2021-04-09 à 14 30 00](https://user-images.githubusercontent.com/16019289/114180626-b7784000-9940-11eb-8502-f8985ac12df5.png)


I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](url_here) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by marionf** [comment] 2021-04-12 12:35
@florine2623 Is it a regression of the 1.7.7.0 ?

**Comment by florine2623** [comment] 2021-04-14 13:30
Hello @marionf ,
After the change of Order Page in 1.7.7, the display is different.
I don't know if this is considered a regression of a new bug.

**Comment by marionf** [comment] 2021-04-14 13:34
@MatShir Could you check if it's a wanted behavior of a regression of the new order page ?

**Comment by MatShir** [comment] 2021-04-23 07:25
It is definitely a bug. 
The order view page should display the Total as Product Price tax excluded. + the Taxes. The display on the order list is correct. 
And when editing the product, the total should remain tax excluded.

**Comment by Progi1984** [comment] 2021-07-08 10:26
Fixed in #24324 by @Progi1984

**Closed as completed by Progi1984** 2021-07-08 10:26 UTC
Labels: Bug, Minor, BO, Order, Customer groups, Taxes and Prices, Regression, Fixed, PR available, 1.7.7.x
