### ISSUE TITLE
Product::addFeatureProductImport - will never update again $id_feature_value values

### ISSUE THREAD

**Issue by dmartinez-softdil** [PrestaShop/PrestaShop#25234] opened 2021-07-05 12:16 UTC
#### Describe the bug

![image](https://user-images.githubusercontent.com/86963330/124470635-23c9da80-dd9c-11eb-9881-4a1167855210.png)

![image](https://user-images.githubusercontent.com/86963330/124470993-a05cb900-dd9c-11eb-88c3-3d5963ba80c7.png)

We use this funcion in previous versions to update feature_value values of a feature. In 1.7 version, ps_feature_value keys changed in order to allow multivaluated features. I think now it is impossible to trigger the "ON DUPLICATE KEY", only whet ir is really not needed.

The current behaviour is that this function no more update values, just duplicate new values

#### Expected behavior

 I think it could be good idea evaluate if this function should only add values, so the query should be change or if it should keep updating funcion.

#### Additional information

* PrestaShop version: 1.7
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-07-05 14:52
Hello @dmartinez-softdil 

Thanks for your issue!
Could you please provide steps to reproduce the issue, cause I need to reproduce the bug to fix it :wink: 
And could you please specify your PS version.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-26 14:46
Hello @dmartinez-softdil 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-26 14:46 UTC
Labels: Bug, 1.7.x, CO, Features, No change required
