### ISSUE TITLE
"Quantity per user" is not considered for guests orders

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#16370] opened 2019-11-12 11:53 UTC
**Describe the bug**
If you create a cart rule with a limit of 1 use per customer, guests customers can use it unlimited

**To Reproduce**
1. Create a cart rule

![image](https://user-images.githubusercontent.com/15104724/68669630-4c5beb80-054b-11ea-9a89-37a0c90c4418.png)

2. Make an order **as a guest**. Voucher is applied.
3. Create a new order as a guest, **using the same email address**. Voucher is applied again.

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by idnovate** [comment] 2019-11-12 12:01
Problem is in this code:

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/CartRule.php#L648-L660

What about adding a validation where there is not an ID customer, to check if this rule has been used by the email address?

```
if ($context->cart->id_customer) {
 // code
} else {
    $quantityUsed = Db::getInstance()->getValue('
    SELECT count(*)
    FROM ' . _DB_PREFIX_ . 'orders o
    LEFT JOIN `"._DB_PREFIX_."customer` c ON o.`id_customer` = c.`id_customer`
    LEFT JOIN ' . _DB_PREFIX_ . 'order_cart_rule od ON o.id_order = od.id_order
    WHERE c.`email` = '".$this->context->customer->email."'
    AND od.id_cart_rule = ' . (int) $this->id . '
    AND ' . (int) Configuration::get('PS_OS_ERROR') . ' != o.current_state
    ');
    if ($quantityUsed + 1 > $this->quantity_per_user) {
        return (!$display_error) ? false : $this->trans('You cannot use this voucher anymore (usage limit reached)', array(), 'Shop.Notifications.Error');
    }
}
```

**Comment by khouloudbelguith** [comment] 2019-11-12 13:08
Hi @idnovate,

The problem is that the guest account is not transformed into a customer account, it creates a second account.

_So, The problem is that the guest account is not transformed into a customer account, it creates a second account => there is no alert => visitors can do multiple orders with the same mail address => this is the whole issue => it needs to be specified by our developers._

We are aware of this issue.
Your ticket is a duplicate of #10122
Please follow #10122.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-12 13:08
Duplicate of #10122

**Closed as completed by khouloudbelguith** 2019-11-12 13:08 UTC
Labels: Duplicate

**Comment by pelechano** [comment] 2024-09-26 14:31
This is not duplicate, in 1.7.8.9 the bug is still available. 
Every guest customer can use the same email but  they have different customer id so the quantity_per_user is always one  for each new order

**Comment by idnovate** [comment] 2024-09-26 16:59
> This is not duplicate, in 1.7.8.9 the bug is still available. Every guest customer can use the same email but they have different customer id so the quantity_per_user is always one for each new order

The issue is duplicated with #10122, but the other issue is not closed yet, so the bug probably remains.

**Comment by pelechano** [comment] 2024-09-26 17:25
> > This is not duplicate, in 1.7.8.9 the bug is still available. Every guest customer can use the same email but they have different customer id so the quantity_per_user is always one for each new order
> 
> The issue is duplicated with #10122, but the other issue is not closed yet, so the bug probably remains.


Is closely related, but the other is about repeating the email every time a guest checks out, which maybe is necessary, but I think it should be controlled regarding this "cart rule business rule". 

If it's not possible to reuse the same guest client (and not repeat the email), maybe using the email to verify the counting in the CartRule should do the trick 
I've change this in CartRule and in my case it works fine, but it's a quick fix.


  ```
      if ($cart->id_customer) {
            $customer=new Customer($cart->id_customer);
            $customer_email=$customer->email;//mod se supone que el email es único , los guest account por cada pedido son clientes nuevos con el mismo email..

            $quantityUsed = Db::getInstance()->getValue('
			SELECT count(*)
			FROM `' . _DB_PREFIX_ . 'orders` o
			LEFT JOIN `' . _DB_PREFIX_ . 'order_cart_rule` ocr ON o.`id_order` = ocr.`id_order`
			JOIN  `' . _DB_PREFIX_ . 'customer` c ON o.`id_customer` = c.`id_customer`
			WHERE c.`email` = "' . pSQL($customer_email) . '" AND c.deleted=0
			AND ocr.`deleted` = 0
			AND ocr.`id_cart_rule` = ' . (int) $this->id . '
			AND ' . (int) Configuration::get('PS_OS_ERROR') . ' != o.`current_state`
			');`
```
