### ISSUE TITLE
[BO] Invalid product footer position in RTL

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#24926] opened 2021-06-11 14:28 UTC
Hello,

#### Describe the bug

Position of product footer is not fixed correctly for **RTL** layout in BO.

#### Expected behavior

.../adminxxx/themes/new-theme/public/product.css (Line: 664)
Need to change (right: 0; left: 13.13rem) to  (left: 0; right: 13.13rem)

#### Steps to Reproduce

1. Go to Catalog
2. Add new product

![Screenshot 2021-06-11 184752](https://user-images.githubusercontent.com/85633460/121701597-4f7fda80-cae6-11eb-936d-1209652dd14e.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by florine2623** [comment] 2021-06-11 14:56
Hello @mparvazi ,

I was able to reproduce the issue with PrestaShop version 1.7.8.x, so I can confirm that this behavior is indeed a bug.

<img width="1418" alt="Screenshot 2021-06-11 at 16 53 31" src="https://user-images.githubusercontent.com/16019289/121706412-e42e0c80-cad5-11eb-8430-3fc0fe1c0f18.png">
Should be like this :
<img width="1116" alt="Screenshot 2021-06-11 at 16 55 38" src="https://user-images.githubusercontent.com/16019289/121706440-eb551a80-cad5-11eb-8b42-ebe79c1414b3.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-06-16 14:43
Ping @NeOMakinG

**Comment by Progi1984** [comment] 2021-06-23 14:14
Fixed by @NeOMakinG in #25035

**Closed as completed by Progi1984** 2021-06-23 14:14 UTC
Labels: Bug, develop, Minor, BO, Regression, Fixed, Front-end, PR available, 1.7.8.x
