### ISSUE TITLE
"File not found" when going on Products list with multistore activated on 1.7.2.0

### ISSUE THREAD

**Issue by hellodracon** [PrestaShop/PrestaShop#21191] opened 2020-09-28 16:36 UTC
On PS 1.7.2.0, I've activated the multistore. Since then, when in the backoffice I click on a menu item to go on the page, the directory of the multistore I'm working on (let's call it **store2**) appears in the url : 
https://www.mysite.com/store2/admin_directory/index.php?controller=AdminOrders&token=xxx

It's not a problem at all except when the directory is in the url and I'm trying to go to the products list (Catalogue > Products), the site shows a blank page with "File not found" written on.

This is the only page that has a problem. If i edit manually the URL, it works :
- #1 (doesn't work) : https://www.mysite.com/store2/admin_directory/index.php/product/catalog?_token=xxx
- #2 (works) : https://www.mysite.com/admin_directory/index.php/product/catalog?_token=xxx

#1 is the URL it generates if I'm coming from a page that has **store2** in its url. #2 is the url I get if I'm coming from the dashboard without the store specified in the url.

It looks like a problem with the url_rewrite. But all the other pages work great. I can go anywhere in the backoffice, change the store I'm working on, sometimes **store2** appears, sometimes not, but I know the only page that doesn't "accept" it is the products list. 

I guess that has been corrected since but can't find the fix. Thanks``

**Comment by khouloudbelguith** [comment] 2020-09-29 08:42
Hi @hellodracon,

Thanks for your report.
Is it your issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/11364?
Thanks to check this fix: https://github.com/PrestaShop/PrestaShop/pull/11478 and feedback.

Please in the next time, you must follow the GitHub's issue template.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

Thank you!

**Comment by hellodracon** [comment] 2020-09-29 09:23
Hi @khouloudbelguith 
I've tried it but that's not the same thing apparently. In #11364 they are talking about the subdomain that appears twice in the backoffice URL, I'm talking about the new store's subdirectory that appears in the URL which is not a problem for most of the pages except the Products list page. 

I found out that all backoffice URLs go to something like "/subdirectory/admin_directory/index.php?Controller=" but not the products list that itself goes to "/subdirectory/admin_directory/index.php/product/catalog?_"

**Comment by khouloudbelguith** [comment] 2020-09-29 09:33
@hellodracon, you are using an old version.
Some fixes have indeed been made for multi-shop URLs, for example:
https://github.com/PrestaShop/PrestaShop/pull/9450

Could you please provide the exact configuration related to your multishop context?
1. Are they in the same Group?
2. Different Physical URL?
3. Different Virtual URLs?
4. Different Domain?

![image](https://user-images.githubusercontent.com/16067358/94541195-958e5a00-0247-11eb-9d7f-fcb1c854bf04.png)


Thanks!

**Comment by hellodracon** [comment] 2020-09-29 09:35
Ho @khouloudbelguith  I'm really sorry, I didn't read #11364 entirely but tried  #11478 fix.
After reading all #11364 and applied the fix, it worked great. Really sorry about this. You can close it

**Comment by khouloudbelguith** [comment] 2020-09-29 09:38
@hellodracon, Great!
Your ticket is a duplicate of #11364
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-29 09:38
Duplicate of #11364

**Closed as completed by khouloudbelguith** 2020-09-29 09:38 UTC
Labels: Bug, BO, Duplicate, Multistore
