### ISSUE TITLE
Error in sending email when the store name has more than 22 characters

### ISSUE THREAD

**Issue by josemariagomezroncero** [PrestaShop/PrestaShop#23418] opened 2021-02-25 21:09 UTC
#### Describe the bug

Error in sending email when the store name has more than 22 characters

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Write Shop name width greater 22 charters. Example: Rincón Home, mobiliario para el hogar y oficina al mejor precio.
2. Go to admin order
3. Send email to customer
4. Fail send email.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.x
* PHP 7.2

**Comment by florine2623** [comment] 2021-02-26 08:31
Hi @josemariagomezroncero ,

I followed your steps but I can reproduce your issue. I'm using PS 1.7.7.2, tested with PHP 7.2 and PHP 7.3.
Please check : https://drive.google.com/file/d/1OJQz93UI7TSgAxx3XsBG3JX5qS_kZfzK/view

Am i missing something ?

Thanks

**Comment by sowbiba** [comment] 2021-02-26 13:31
Please take a look at https://github.com/PrestaShop/PrestaShop/pull/23417#issuecomment-786642535
Thanks

**Comment by florine2623** [comment] 2021-03-18 10:24
Hi @josemariagomezroncero ,
Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-03-18 10:24 UTC
Labels: 1.7.x, BO, Can't reproduce, Order, Email, PR available
