### ISSUE TITLE
New Multistore header missing on Add/Edit Product page

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24065] opened 2021-04-15 09:24 UTC
#### Describe the bug

On the Add/Edit Product pages (V1 and Experimental), the new Multistore header is not displayed (and the old one isn't displayed either).

It is however displayed in the product list page.

#### Expected behavior

The new Multistore header should be displayed, in order to allow the user to know on which context he is, and if necessary, swtich to a different context.

If possible, it should also be displayed on the Experimental "Product V2" Add and Edit pages.

#### Steps to Reproduce

0. Have multistore enabled with at least 2 different shops configured
1. Go to Catalog > Products page : The new multistore header is displayed on list page
2. Click on a product to edit it, or click on "+ New Product" to see the Add page
4. The Multistore Header is not displayed

**Screenshots**

![no multistore header on edit product page](https://user-images.githubusercontent.com/55688534/114846157-b16cde00-9ddc-11eb-9246-612d1d1acf99.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by marionf** [comment] 2021-04-15 13:34
Duplicate of #23937

**Closed as completed by marionf** 2021-04-15 13:34 UTC
Labels: Bug, develop, Minor, Duplicate, Multistore, Regression
