### ISSUE TITLE
Products created from the api do not show up in the front office

### ISSUE THREAD

**Issue by QueeNFrisk** [PrestaShop/PrestaShop#28409] opened 2022-05-03 20:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I create products from the api, they are inserted into prestashop and I can see them inside the back office, but in the front office they are not displayed. I have to enter each product and click save to make them appear in the front office.
Here is my code:
```PHP
     $ws = new PrestaShopWebservice('https://www.shop.com', 'APIKEY', false);
      $bx = $ws->get(['url' => 'https://www.ferreteriaferrol.com/api/products?schema=blank']);
      $cf = $bx->product->children();
      $cf->id_manufacturer = $productInfo['brand'];
      $cf->new = $productInfo['isNew'];
      $cf->state = $productInfo['state'];
      $cf->id_category_default = $productInfo['idCategory'];
      $cf->active = $productInfo['active'];
      $cf->advanced_stock_management = $productInfo['stockManagment'];
      $cf->reference = $productInfo['reference'];
      $cf->name = $productInfo['name'];
      $cf->price = $productInfo['price'];
      $cf->id_shop_default = 1;
      $cf->low_stock_alert = 1;
      $cf->show_price = $productInfo['showPrice'];
      $cf->minimal_quantity = 1;
      $cf->available_for_order = 1;
      $cf->supplier_reference = $productInfo['supplierReference'];
      $cf->ean13 = $productInfo['ean'];
      $cf->upc = $productInfo['upc'];
      $cf->is_virtual = 0;
      $cf->on_sale = 0;
      $cf->online_only = 1;
      $cf->wholesale_price = $productInfo['wholesalePrice'];
      $cf->uploadable_files = 0;
      $cf->show_condition = 0;
      $cf->show_price = $productInfo['showPrice'];
      $cf->indexed = $productInfo['indexed'];
      $cf->visibility = 'both';
      $cf->meta_description = $productInfo['metaDescription'];
      $cf->meta_keywords = $productInfo['metaKeywords'];
      $cf->meta_title = $productInfo['metaTitle'];
      $cf->description = $productInfo['description'];
      $cf->description_short = $productInfo['shortDescription'];

      unset($cf->position_in_category);
      unset($cf->associations->categories->category->id);
      unset($cf->link_rewrite);

      $cx = $ws->add([
        'resource' => 'products',
        'postXml' => $bx->asXML(),
        'output_format' => 'JSON'
      ]);
      $ncpf = $cx->product->children();
```

The output does not show any errors. They are inserted correctly, only they are not displayed in the front office.
I have already checked:

- [x] product->new = 1
- [x] product->state = 1
- [x] product->active = 1
- [x] product->indexed = 1
- [x] product->visibility = 'both'
- [x] product->id_category_default = 2
- [x] No module interferes with the visibility of the products in the store.
- [x] I have added the missing products to the index.
- [x] I have reconstructed the index.
- [x] I have solved language problems.

After checking this list it still does not show the products

### Steps to reproduce

1.- install prestashop
2.- enable webservices
3.- insert product with the above code
4.- try to see it in front office

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.28

**Comment by hibatallahAouadni** [comment] 2022-05-04 14:46
Hello @QueeNFrisk 

I think you made mistake while creating this code :wink: 
First of all, you need to encapsulate the code by the `try` and `catch` condition.
Then, you need to add `array` to this second line:
` $xml = $webService->get(array('url' => PS_SHOP_PATH.'/api/products?schema=blank'));`
Finally, you need to check if you have multi languages, if so you need to add `langauge` while setting the name and description:
```
$product->name->language[0][0] = "Produit webservice test";
$product->description->language[0][0] = "Description produit webservice";
```
You can check this [comment](https://github.com/PrestaShop/PrestaShop/issues/11628#issuecomment-444822625), it may help you to fix your issue :wink: 
Waiting for your feedback.

Thanks!

**Comment by QueeNFrisk** [comment] 2022-05-05 22:50
Hello, good morning/afternoon/evening, thank you for attending my ticket.
Regarding the fact that it needs to be encapsulated, it is already encapsulated. I didn't think it was necessary to put it in the code.
About the array inside get->() it is already inside an array as you could verify in the code above ([]).
As soon as the language as I mentioned in the checklist of my issue solves the language problems, I currently have only one language.
Regarding the comment, the people issue directly could not insert products in the api. The problem I have is that the products 
**are inserted**, that is; I can see them in the back office but they are not shown in the front office/storefront,

**Comment by hibatallahAouadni** [comment] 2022-05-09 14:32
Hello @QueeNFrisk 

I didn't manage to reproduce the issue with the provided infos :disappointed: 
Could you please provide a screen record :pray: 

PS: could you please check if your product is enbaled in BO

Thanks in advance!

**Comment by QueeNFrisk** [comment] 2022-05-09 22:01
Here is a video showing the newly inserted products. These products are shown active in BO but are not shown in FO.
To show them in FO I need to go to each product to save it, otherwise it will be shown in FO, otherwise not.
https://drive.google.com/file/d/17wMCW8vtUESVlXrtMrIBxTazJFPOGtKW/view

**Comment by marwachelly** [comment] 2022-05-10 09:52
Hello @QueeNFrisk,

Could you please check the following steps:

1. Go to BO> catalog> Products>product page
2. Go to the tab option then check that the visibility of the product is Everywhere

Also could you please check the following steps:

1. Go to BO> shop parameters> Search
2. check that the option indexing is set to yes

https://user-images.githubusercontent.com/89604350/167601500-aa732ca1-a568-4b3d-84a5-06dcbfd748f0.mp4




Could you please check and feedback.

Thanks,

**Comment by hibatallahAouadni** [comment] 2022-05-25 11:25
Hello @QueeNFrisk 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28586. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-05-25 11:25
Duplicate of #28586

**Closed as completed by hibatallahAouadni** 2022-05-25 11:25 UTC
Labels: Bug, WS, Duplicate, Invalid
