### ISSUE TITLE
No more default tax rule when creating new product 

### ISSUE THREAD

**Issue by Danilo8024** [PrestaShop/PrestaShop#35594] opened 2024-03-09 09:43 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

connected to the closed signal https://github.com/PrestaShop/PrestaShop/issues/29982

### Expected behavior

Hi, I'm having the same problem on a prestashop where the taxes have been changed, @hibatallahAouadni answer doesn't give a solution, prestashop can't have a constraint (id_tax = 1) which we can't even modify by code to solve the problem. therefore, marking it as closed is not a solution. It would be nice to understand when creating a product which class assigns this (id_tax = 1 fixed), so that those who have this problem can solve it, without having to reinstall a new prestashop.

Personally, I have been trying to resolve this problem for days by restoring all the tax tables but the problem persists.

I hope someone can give comprehensive information on how to solve the problem.

Thanks for the support

video sent by @hibatallahAouadni 

### Steps to reproduce

https://private-user-images.githubusercontent.com/100699445/195567908-94bffd04-7925-464c-b717-d60a10465ac2.webm?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Nzc2OTMsIm5iZiI6MTcwOTk3NzM5MywicGF0aCI6Ii8xMDA2OTk0NDUvMTk1NTY3OTA4LTk0YmZmZDA0LTc5MjUtNDY0Yy1iNzE3LWQ2MGExMDQ2NWFjMi53ZWJtP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMDk0MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBmNGIyMTBmYzhmMTMzMDcyYThmY2FiZWFiMGUxNjkyYjkyY2U4NTNmNzRmMDNkM2Q5OTcwY2JjZWJiMzAxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GL4ExC2EIjEYLs0ontcjO5q5deoaddIMVARsVVA4eEU

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.0.30

**Comment by Misty-94** [comment] 2024-03-11 03:08
Hi Danilo, is it the same as https://github.com/PrestaShop/PrestaShop/pull/35495 ?
It will be fixed in 8.1.5 but no release date yet

**Comment by Danilo8024** [comment] 2024-03-11 07:19
Hi @Misty-94, yes I had already read it, I wanted to know if I can solve it momentarily from code, so as not to create a trigger in the DB and do something cleaner.

Thank you

**Comment by Danilo8024** [comment] 2024-03-11 07:44
For all those who are in the same condition as me and want to temporarily solve the problem and have only one fee I can make two triggers like these

```
DELIMITER //
CREATE TRIGGER tb_product_add_fix_tax
BEFORE INSERT ON ps_product FOR EACH ROW
BEGIN
    SET NEW.id_tax_rules_group = /* YOU TAX ID */;
END
//
DELIMITER ;


DELIMITER //
CREATE TRIGGER tb_product_shop_add_fix_tax
BEFORE INSERT ON ps_product_shop FOR EACH ROW
BEGIN
    SET NEW.id_tax_rules_group =  /* YOU TAX ID */;
END
//
DELIMITER ;
```

I know it's not very elegant but it seems to work.

Other ideas are welcome!

**Comment by paulnoelcholot** [comment] 2024-03-11 08:33
Hello @Danilo8024,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #35495 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment] 2024-03-11 08:33
Duplicate of #35495

**Closed as completed by paulnoelcholot** 2024-03-11 08:33 UTC
Labels: Bug, Duplicate
