### ISSUE TITLE
Problem with managing the quantity of a simple product

### ISSUE THREAD

**Issue by bapa92** [PrestaShop/PrestaShop#13090] opened 2019-03-28 12:30 UTC
Good morning,

I have been trying to run a prestashop for several weeks and there are still problems with the setting.

In the catalog, the product entered the quantity, delivery and all other settings as in other products and still shows that it is unavailable.

I am not interested in the solution that despite the lack of stock you can order because the message SOLD OUT appears.

I attach a link to the page.

I am asking for a reaction.

https://daxmeble.pl/narozniki-i-sofy/52-amaro.html

**Comment by khouloudbelguith** [comment] 2019-03-28 13:19
Hi @bapa92,

What is the exact version of PS did you installed?

Thanks!

**Comment by bapa92** [comment] 2019-03-28 16:32
1.7.5.1

**Comment by khouloudbelguith** [comment] 2019-03-29 08:59
Hi @bapa92,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by bapa92** [comment] 2019-03-29 14:59
Hi.

Version 1.7.5.1.
No logs and 0 errors
PHP 7.2
This ja simply produkt without combinations.
Other configuration is ok.

https://ibb.co/gFwBwGx

**Comment by khouloudbelguith** [comment] 2019-03-29 15:25
@bapa92, did you use the template by default of Prestashop?

**Comment by bapa92** [comment] 2019-03-29 15:28
No. I use interio

**Comment by bapa92** [comment] 2019-03-29 15:30
But  on classic theme has the same bug

**Comment by khouloudbelguith** [comment] 2019-03-29 16:03
@bapa92, do you have the same problem in the Back Office that the product quantity is equal to 0?

**Comment by bapa92** [comment] 2019-03-31 13:36
in the Back Office the  quantity is equal 100

**Comment by khouloudbelguith** [comment] 2019-04-01 10:21
Hi @bapa92,

Thanks to check with this PR: #12655 .

**Comment by khouloudbelguith** [comment] 2019-05-02 07:31
Hi @bapa92,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-02 07:31 UTC
Labels: FO, No change required
