### ISSUE TITLE
Gateway timeout status while extending admin twig template

### ISSUE THREAD

**Issue by adviva** [PrestaShop/PrestaShop#29827] opened 2022-09-30 15:02 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The problem is about the extends of admin template twig from a module in ps 8.0, i think any root template. 

When a module extends an admin template twig, this page get infinite loading or a gateway timeout status.

The extend works in previous ps 1.7.8 like this:
{% extends 'PrestaShopBundle:Admin/Product/ProductPage:product.html.twig' %}

Now i have changed the above using bundle name syntax, as described in the notable-changes of the doc:
{% extends '@PrestaShop/Admin/Product/ProductPage/product.html.twig' %}

This single line breaks the page loading.

### Expected behavior

Template twig override from a module works and admin page is loaded

### Steps to reproduce

1. Extends an admin template Twig from a module
for example: 
- @PrestaShop/Admin/Product/CatalogPage/catalog.html.twig
- @PrestaShop/Admin/Product/ProductPage/product.html.twig
2. Open the relative admin page

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4

**Comment by MhiriFaten** [comment] 2022-09-30 16:02
Hello @adviva ,

I didn't manage to reproduce the issue with the provided informations.
Could you please provide some screenshots or a screen record of the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by adviva** [comment] 2022-10-03 14:58
Hello @MhiriFaten, 

I attach a test module that extends Admin Product template. 
What happen in my case is an infinite loading while opening product page and i have to restart php process.
Let me know if you are able to open the admin product detail after have installed the test module.

Thanks!
[pcomtest.zip](https://github.com/PrestaShop/PrestaShop/files/9698578/pcomtest.zip)

**Comment by AureRita** [comment] 2022-10-03 15:35
Hello @adviva, 

I reproduced your issue as we can see on this video : 

[Untitled_ Oct 3, 2022 5_27 PM.webm](https://user-images.githubusercontent.com/100699445/193617730-100dda07-fbfb-455f-84ff-45610bc83ca8.webm)

@PrestaShop/prestashop-maintainers, can you check it if it's not due to the module ? 

waiting for your feedback

**Comment by matks** [comment] 2022-10-10 08:25
Hello @adviva in the documentation https://devdocs.prestashop-project.org/8/modules/concepts/templating/admin-views/

the extend should be:
```
{% extends '@!PrestaShop/Admin/Product/CatalogPage/catalog.html.twig' %}
```

please notice the `!` can you try this?

**Comment by adviva** [comment] 2022-10-11 10:05
Hi @matks 
many thanks for your suggestion! It was a really small change to do in our code. 

Both the solution with the new namespace @PrestaShopCore and with @!PrestaShop works fine for me

**Comment by atomiix** [comment] 2022-10-11 12:05
I think we can close this issue then! :)

**Closed as completed by atomiix** 2022-10-11 12:05 UTC
Labels: Bug, 8.0.x, CO, Catalog, Invalid
