### ISSUE TITLE
Specific "available later" message for product don't show on category listing

### ISSUE THREAD

**Issue by ioniks** [PrestaShop/PrestaShop#23838] opened 2021-03-31 11:32 UTC
#### Describe the bug
On category listing, product avalaible_message don't match the product available_later message when no stock but orderable.
The message is the shop avalaible message. On product detail, the avalaible message is good.

#### Expected behavior
The product avalaible later message in the product available_message

#### Steps to Reproduce

1. Modify product miniature to show the avalaible messsage
add `{$product.availability_message}` in `templates/catalog/_partials/miniatures/product.tpl`
2. Modify a product or create one
3. Set 0 to quantity
4. Set orderable when no stock avalaible
5. Set a avalaible later text
6. Go to category listing and show the available later message.

#### Additional information

* PrestaShop version: 1.7.7.1+
* PHP version: 7.2+

I have check and on `src/Adapter/Presenter/Product/ProductLazyArray.php` and for same product : 

- on home or product detail : `$product['allow_oosp'] = 1` 
- on category list for all product  `$product['allow_oosp'] = 0`

**Comment by florine2623** [comment] 2021-03-31 13:10
Hello @ioniks ,
Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/21477 ?

Can you check and feedback ?
Thanks!

**Comment by ioniks** [comment] 2021-03-31 13:20
Hi @florine2623,

The bug is similar but not the same.

The bug is only on the category list, i can't add to cart the product on the category list too, but from the home (new product module) or from the detail page i can.

I have tested on 1.7.7.1, 1.7.7.2 and 1.7.7.3 same problem.
I have already tested on classic template same problem.

**Comment by jf-viguier** [comment] 2021-03-31 13:34
I don't have this bug in 1.7.6 with classic. It's a regression I guess

**Comment by ioniks** [comment] 2021-04-01 13:10
Update :
the bug is with facetedsearch 3.7.1
The avalaible_later product message is not good when ps_layered_filter_show_out_of_stock_last_on is set to No, when set to Yes is good.

**Comment by hibatallahAouadni** [comment] 2021-04-01 15:29
Hello @ioniks 

I couldn't manage to reproduce your issue with PS1.7.7.3 and FactedSearch v3.7.1, see the attached screen record below:

https://drive.google.com/file/d/1TRJGQyisK5yZL9L4VQFvtmBlL245RHUp/view

Please check and feedback.
Thanks!

**Comment by ioniks** [comment] 2021-04-06 11:22
Hi @hibatallahAouadni 

What is the option for ps_layered_filter_show_out_of_stock_last_on  in ps_layered configuration ?

My prestashop install is mulit shop activated and it is the first shop

**Comment by florine2623** [comment] 2021-04-08 13:41
Hello @ioniks ,

In PS 1.7.7.1, here are the tables containing the word "layered", there's no `ps_layered` of `ps_layered_configuration` : 
![Capture d’écran 2021-04-08 à 15 39 44](https://user-images.githubusercontent.com/16019289/114036947-c7c8e600-9880-11eb-8efe-8898fdfc650d.png)

I don't see `ps_layered_filter_show_out_of_stock_last_on`

**Comment by ioniks** [comment] 2021-04-08 13:45
Hello @florine2623 

I talk about plugin configuration field.

![image](https://user-images.githubusercontent.com/11200935/114037508-59385800-9881-11eb-8c8e-d4026391f45b.png)

in url /admin710mmbzfr/index.php?controller=AdminModules&configure=ps_facetedsearch

**Comment by florine2623** [comment] 2021-04-08 13:59
In PS 1.7.7.1, multistore, this is the result : 
![Capture d’écran 2021-04-08 à 15 54 47](https://user-images.githubusercontent.com/16019289/114039278-e7f9a480-9882-11eb-8084-2f9e1776f937.png)
The product with 0 stock will be shown last on the category page.
![Capture d’écran 2021-04-08 à 15 57 28](https://user-images.githubusercontent.com/16019289/114039582-298a4f80-9883-11eb-9082-7029ac0b1c2b.png)

When the option is disabled :
![Capture d’écran 2021-04-08 à 15 57 16](https://user-images.githubusercontent.com/16019289/114039631-33ac4e00-9883-11eb-8568-fcb41cb6c844.png)

Do I answer your question ?

**Comment by ioniks** [comment] 2021-04-08 14:10
No, this is not the problem

To view the problem :
Modify product miniature to show the avalaible messsage
add {$product.availability_message} in templates/catalog/_partials/miniatures/product.tpl
Modify a product or create one
Set 0 to quantity
Set orderable when no stock avalaible
Set a avalaible later text
Go to category listing and show the available later message.

And set the option in FactedSearch i have surrounded to no.

And you show the website avalaible later text, not the avalaible_later product text and you can"t order the product on the category listing

**Comment by florine2623** [comment] 2021-04-23 13:51
Hello @ioniks ,

Sorry for the late response.

Where exactly do you add  {$product.availability_message} in the file templates/catalog/_partials/miniatures/product.tpl.
Is there a specific line ?

**Comment by ioniks** [comment] 2021-05-12 10:18
Hi,

It is a line for have the message on list yes

**Comment by florine2623** [comment] 2021-05-14 10:38
Can you specify the line on the file ?
Or add a screenshot of it ?

**Comment by hibatallahAouadni** [comment] 2021-06-03 09:01
Hello @ioniks ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-03 09:01 UTC
Labels: Bug, FO, Categories, Faceted search, No change required, 1.7.7.1
