### ISSUE TITLE
Wrong Categoriy- nleft, nright in Multishop

### ISSUE THREAD

**Issue by novallis** [PrestaShop/PrestaShop#11349] opened 2018-11-10 20:54 UTC
Nleft and nright values are wrong created in Multishop 

Set all nleft and nrigth values to 0. Open Prestashop -> Shop 1 -> categories. Add new Category. Check values for nleft, nright in database. They are created for Shop 2. Do the same for Shop 2 -> nleft, nright are created for Shop 1.

I think because off this also Breadcrumps are displayed with a mix of categories from Shop 1 and Shop 2

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0, 7.2

**Comment by novallis** [comment] 2018-11-10 21:19
If you add (in the database) the highest nright value from shop 1 to nleft and  nright in Shop 2 all works as expected.

**Comment by khouloudbelguith** [comment] 2018-11-12 10:17
Hi @novallis,

How did you set all nleft and nrigth values to 0?
Manually from the Database?
Thanks!

**Comment by novallis** [comment] 2018-11-12 13:33
Yes, because breadcrumbs displayed incorrectly (mix form 2 Shops) and i try to recreate nleft, nright

**Comment by khouloudbelguith** [comment] 2018-11-12 14:46
@novallis, without changing all nleft and nrigth values to 0 from the Database, I did not manage to reproduce the issue with the last version 1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1WPP__OOYZC5VcjMTKpWZDgL4tLyJ2uwH/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2018-12-14 15:27
Hi @novallis,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-14 15:27 UTC
Labels: BO, Categories, No change required
