### ISSUE TITLE
Preview email templates on order status not working

### ISSUE THREAD

**Issue by pluscom-kevin** [PrestaShop/PrestaShop#28365] opened 2022-04-28 13:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After a fresh install of Prestashop 1.7.8.5, I'm trying the native functionalities, the first one to bug is the Preview on orders status.
I tried on many empty website with differents hostings, I always get an error.
o2switch :
![Capture d’écran 2022-04-28 152611](https://user-images.githubusercontent.com/68845619/165763910-fa31fa31-6a47-436c-af2b-f0fad7aa62c4.png)
ovh and/or local wamp server :
![Capture d’écran 2022-04-28 153439](https://user-images.githubusercontent.com/68845619/165764345-37ac7298-12e7-4b28-8545-4f3a44ff47a5.png)

### Expected behavior

I want, like it was working on Prestashop 1.6, to see the preview of the email template.
![Capture d’écran 2022-04-28 153703-2](https://user-images.githubusercontent.com/68845619/165765773-e7965435-c2e1-4d03-b262-dd3cab3d35ea.png)

### Steps to reproduce

1. Fresh install of Prestashop 1.7.8.5
2. Got to Params > Orders > Orders statuses.
3. Chose a random status to edit.
4. Click on Preview in front of template model.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2022-04-29 08:20
Hello @pluscom-kevin 

Thanks for your report.
I was able to reproduce the issue with 1785 and 1778 even when the e-mail is configured.

![image](https://user-images.githubusercontent.com/92912932/165908829-fb117825-987d-4c12-bf0f-ab900f8ef723.png)

https://user-images.githubusercontent.com/92912932/165908806-06d097c7-e0b5-4063-9b9f-2b2475f6dbb8.mp4



I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by pluscom-kevin** [comment] 2022-04-29 08:40
Hi [HanaRebaiQA](https://github.com/HanaRebaiQA),

Thanks for taking the time.
I was able to "correct" this issue by going to International > Translations > e-mails translations / body message / my theme / my language.
Just by doing that, now the "preview" on order statuses redirect to the theme folder and it's working.
![image](https://user-images.githubusercontent.com/68845619/165912106-48d88b94-ad7c-4193-9a07-f560e6ad4047.png)

But yeah by default the /mails folder prompt this error.
I just let this message in case someone have the same error and can't wait for a fix !

Have a nice day.

**Comment by HanaRebaiQA** [comment] 2022-04-29 08:59
Hello @pluscom-kevin 

Thanks for your feedback.
Yes! The problem is fixed when Do this : International > Translations > Modify Translations > Choose Email translation 

https://user-images.githubusercontent.com/92912932/165914718-ecf043aa-8492-4e78-aff1-62365124f82f.mp4


This issue is a duplicate of[ #17759](https://github.com/PrestaShop/PrestaShop/issues/17759)

So, i'll close the issue.

Thank you!

**Comment by HanaRebaiQA** [comment] 2022-04-29 08:59
Duplicate of[ #17759](https://github.com/PrestaShop/PrestaShop/issues/17759)

**Closed as completed by HanaRebaiQA** 2022-04-29 08:59 UTC
Labels: Bug, Minor, BO, Duplicate, Order statuses
