### ISSUE TITLE
Cannot change prestashop language/ order status

### ISSUE THREAD

**Issue by Laquepinta** [PrestaShop/PrestaShop#14997] opened 2019-08-06 06:36 UTC
hi!
I updated my prestashop no newest version and now I cannot not change order status neither language of my dashoard.

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-08-06 07:49
Hi @Laquepinta,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Laquepinta** [comment] 2019-08-07 08:03
Thank you so much for your quick answer!
I updated prestashop from 1.6.1. 24 to 1.7.6.
I was using an old template and changed to a ew one.
The responsible person for the template is helping me a lot adapting my shop with the new template, but told me that something happened to my prestashop and it shows a little errors.
When I try to change order status this message happens to me: "you don't have permission to do that".
I am superadmin of my shop and the only one in dashboard.

host: laquepinta.com/tienda

server setup and configuration: 


PrestaShop version (source): 1.7.6

debug mode report: no error  


PHP error logs: 
[07-Aug-2019 04:16:12 Europe/Madrid] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot use object of type Symfony\Component\HttpFoundation\ParameterBag as array in /usr/home/laquepinta.com/web/tienda/src/Adapter/Security/Admin.php:91
Stack trace:
#0 /usr/home/laquepinta.com/web/tienda/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): PrestaShop\PrestaShop\Adapter\Security\Admin->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#1 /usr/home/laquepinta.com/web/tienda/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#2 /usr/home/laquepinta.com/web/tienda/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('ker in /usr/home/laquepinta.com/web/tienda/src/Adapter/Security/Admin.php on line 91


apache error log:
[Wed Aug 07 06:09:55.739819 2019] [authz_core:error] [pid 5081:tid 140719288596224] [client 54.36.148.205:34556] AH01630: client denied by server configuration: /home/laquepinta.com/web/tienda/img/p/2/1/8/5
[Wed Aug 07 06:57:36.912770 2019] [authz_core:error] [pid 29535:tid 140719288596224] [client 54.36.150.76:41304] AH01630: client denied by server configuration: /home/laquepinta.com/web/tienda/img/p/2/2/5/0
[Wed Aug 07 08:18:02.231808 2019] [authz_core:error] [pid 1607:tid 140719246632704] [client 66.249.64.218:54565] AH01630: client denied by server configuration: /home/laquepinta.com/web/tienda/img/p/2/2/2/5


javascript console log
white50.png:1 Failed to load resource: the server responded with a status of 404 ()
2blank.gif:1 Failed to load resource: the server responded with a status of 404 ()
white50.png:1 Failed to load resource: the server responded with a status of 404 ()
core.js:39 GET https://laquepinta.com/tienda/modules/leoslideshow/img/blank.gif 404
Le @ core.js:39
css @ core.js:39
G @ core.js:39
m.Animation.m.extend.prefilters @ core.js:39
Ke @ core.js:39
a @ core.js:39
dequeue @ core.js:39
(anonymous) @ core.js:39
each @ core.js:28
each @ core.js:28
queue @ core.js:39
animate @ core.js:39
runTransition @ iview.js:1246
goTo @ iview.js:1626
timerCall @ iview.js:1467
(anonymous) @ iview.js:887
setInterval (async)
transitionEnd @ iview.js:886
(anonymous) @ iview.js:1220
i.complete @ core.js:39
u @ core.js:39
fireWith @ core.js:39
u @ core.js:39
m.fx.tick @ core.js:39
setInterval (async)
m.fx.start @ core.js:39
m.fx.timer @ core.js:39
Ke @ core.js:39
a @ core.js:39
dequeue @ core.js:39
(anonymous) @ core.js:39
each @ core.js:28
each @ core.js:28
queue @ core.js:39
animate @ core.js:39
goTo @ iview.js:1497
timerCall @ iview.js:1467
(anonymous) @ iview.js:1475

**Comment by khouloudbelguith** [comment] 2019-08-07 08:48
@Laquepinta, 

To fix this issue you need to replace the `ps_access ` table in DB with the one from clean PS1.7 installation.
You can, for example, install PrestaShop separately, copy & paste the table ps_access to your shop.
Or you can follow this solution in this comment to solve your issue https://github.com/PrestaShop/PrestaShop/issues/9513#issuecomment-415011961
Before any modification, you can make a backup of your old database.
Your ticket is a duplicate of https://github.com/PrestaShop/autoupgrade/issues/100
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-07 08:48
Duplicate of https://github.com/PrestaShop/autoupgrade/issues/100

**Closed as completed by khouloudbelguith** 2019-08-07 08:48 UTC
Labels: Duplicate, Order, 1.7.6.0
