### ISSUE TITLE
An exception has been thrown during the rendering of a template (“Content template for column type ”custom_text“ was not found”)

### ISSUE THREAD

**Issue by laradev43** [PrestaShop/PrestaShop#25055] opened 2021-06-21 11:44 UTC
Hello,

I'm writing a custom plugin for Prestashop 1.7 for adding a new column in OrderList and I can't solve this issue.

In the local environment, it works but not on the production site.

Version Prestashop : 1.7.7.4 Php : 7.3.28

The difference between dev and production is the OS. Windows on dev machine and Debian on production.

I have tested my code with Prestashop 1.7.7.3 and 1.7.7.4.

My hook :
```
Path: /modules/mymodule/mymodule.php

/**
 * @param array $params
 */
public function hookActionOrderGridDefinitionModifier(array $params)
{
    /** @var GridDefinitionInterface $definition */
    $definition = $params['definition'];

    $definition
        ->getColumns()
        ->addAfter(
            'country_name',
            (new HtmlTypeColumn('ldDeliveryDate'))
                ->setName($this->l('Date de livraison'))
                ->setOptions([
                    'ModuleClass' => new MyModule(),
                    'ldDeliveryDate' => "Aujourd'hui"
                ])
        )
    ;
}
```

My class : 
```
Path : /modules/mymodule/src/Grid/Columns/HtmlTypeColumn.php


final class HtmlTypeColumn extends AbstractColumn {
    public function getType() {
        return 'custom_text';
    }
    protected function configureOptions(OptionsResolver $resolver) 
        $resolver
            ->setRequired([
                'ModuleClass',
                'ldDeliveryDate'
            ])
            ->setAllowedTypes('ModuleClass', 'object')
            ->setAllowedTypes('ldDeliveryDate', 'string');
    }
}
```

The error : 
`An exception has been thrown during the rendering of a template ("Content template for column type "custom_text" was not found").`

1. Create a module
2. Use the hook : hookActionOrderGridDefinitionModifier
3. Create a custom class to add new column type

* PrestaShop version: 1.7.7.3, 1.7.7.4, 1.7.8
* PHP version: 7.3

[EDIT} To test I placed my "custom_text.html.twig" file in the folder: "/ src / PrestaShopBundle / Resources / views / Admin / Common / Grid / Columns / Content" of prestashop. And everything works. I am still looking for a permanent solution. If you have a solution, I'm interested.

**Comment by hibatallahAouadni** [comment] 2021-06-21 18:58
Hello @laradev43 

Could you please provide a test module to reproduce the issue.
Or you can just ask for help in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by hibatallahAouadni** [comment] 2021-07-12 08:25
Hello @laradev43 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-12 08:25 UTC
Labels: Bug, CO, Order, Modules, No change required, PR available, Hook, 1.7.8.x, 1.7.7.4
