### ISSUE TITLE
Module Faceted Search in PrestaShop 1.7.7.0, when enabled, products shows only up in the Main category checked but not in any of the other checked categories for that actual Product

### ISSUE THREAD

**Issue by VidarPc** [PrestaShop/PrestaShop#22239] opened 2020-12-04 09:18 UTC
#### Describe the bug

I upgraded yesterday my shop using one-click-upgrade to 1.7.7.0. After the upgrade, I had to disable the faceted search module as items were only displayed in the main category of the product in my shop catalog. All other categories for the actual product checked, did not show up in that specific category.

#### Expected behavior

I was expecting that when using the faceted search module as in earlier versions, the actual products should be listed in all categories that are checked.

#### Steps to Reproduce

Enable the module faceted search, and the problem will appear with seeing the listing of the actual product only under the main category checked.
Choose a product category that is not the main category but a checked category for the actual product from your shop's homepage. You will see that you only get listed your product in the main category, but not any of the others checked in your product catalog for that specific product.

1. Go to 'Modules' and look for the module "Faceted Search"
2. Click on 'Faceted Search'
3. Scroll down to 'enable'

**Screenshots**

See Screenshot below.

The shop shows only this item in the category "Tools", but not "Home", "Care" or "Velj. Wahlsten OY" even they are checked.

![2020-12-04](https://user-images.githubusercontent.com/18537770/101145204-21df4380-3622-11eb-84b6-64d8695cc8a2.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by florine2623** [comment] 2020-12-04 09:42
Hello @VidarPc ,
What version did you upgrade to PS 1.7.7.0 ?
Did you use one-click upgrade by PrestaShop, or another module to upgrade your shop ?
What PHP version are you using ?

Make sure you are using latest version of faceted_search v3.6.0.

Thanks.

**Comment by VidarPc** [comment] 2020-12-04 10:25
I used a one-click upgrade module latest version available at my admin-panel and made an upgrade to 1.7.7.0. My shop is hosted by SiteGround and I have can see from PhpMyadmin that they are using PHP version 5.6.30. Faceted_search module is v3.6.0 - by PrestaShop.

**Comment by florine2623** [comment] 2020-12-04 15:53
PHP 5.6 is not compatible with PS 1.7.7.0.
You can check out this documentation : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please upgrade your PHP version to match PS version.

**Comment by VidarPc** [comment] 2020-12-04 16:37
Hi, I changed to PHP 7.3, but nothing changed. Problem with not showing other categories than the "Main category" remains!

**Comment by hibatallahAouadni** [comment] 2020-12-25 12:54
Hello @VidarPc 

Sorry Sir for the late response. But this issue is already in our debug backlog #22485
This issue is not just about the Faceted Search module, it's about all modules :confused: 
Sorry again for the inconvenience, but your issue is a duplicate to  #22485
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-25 12:55
Duplicate of #22485

**Closed as completed by hibatallahAouadni** 2020-12-25 12:54 UTC
Labels: Bug, BO, Duplicate, Faceted search, Autoupgrade, 1.7.7.0
