### ISSUE TITLE
Step carrier ranges empty

### ISSUE THREAD

**Issue by stefbiper** [PrestaShop/PrestaShop#26970] opened 2021-12-13 18:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After update ps from 1.7.7.1 to ps 1.7.8.2, the step 2 of existing or new carrier in admin is empty.

![image](https://user-images.githubusercontent.com/16206943/145867360-4e15bf3a-475c-41d5-96bd-e79c48b693f7.png)

### Steps to reproduce

1- Disable all override
2- Go to shipping / carriers  
3- Edit any carrier or add a new one
4- Step 2 : Shipping locations and costs
5- Ranges form is empty

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2021-12-14 09:43
Hello @stefbiper ,

I can't reproduce your issue, here are the steps I followed :
- I installed 1-click upgrade v4.13.0
- Upgraded my shop from 1.7.7.1 to 1.7.8.2
- Upgrade went well
- <img width="808" alt="Screenshot 2021-12-14 at 10 42 23" src="https://user-images.githubusercontent.com/16019289/145973298-9fdbe6ed-8eec-4a41-9448-0c05b013e594.png">
- Go to Carriers - Step 2, no error
- <img width="1208" alt="Screenshot 2021-12-14 at 10 43 13" src="https://user-images.githubusercontent.com/16019289/145973452-fc7d4647-7117-4323-a15b-0fa908bc7a21.png">

Do you have any error in the console ? Does this happen for all carriers ?

Thanks!

**Comment by stefbiper** [comment] 2021-12-14 09:47
Hello 
Thanks for your feedback
Do you have any error in the console ?

No errors in console

Does this happen for all carriers ?

Yes this happen for all carriers

**Comment by florine2623** [comment] 2021-12-14 09:55
Thanks for the details !

Do you have any error on your log file ? 
Did you encounter an error during the upgrade process ?
What version oh PHP are you using ?

**Comment by stefbiper** [comment] 2021-12-14 09:59
Do you have any error on your log file ?

I got warning in debug mode

`[2021-12-14 10:57:19] translation.WARNING: Translation not found. {"id":"Configuration du blog","domain":"messages","locale":"en-US"} []
[2021-12-14 10:57:19] translation.WARNING: Translation not found. {"id":"Configuration des pages maisons","domain":"messages","locale":"en-US"} []
[2021-12-14 10:57:19] translation.WARNING: Translation not found. {"id":"FAQ","domain":"messages","locale":"en-US"} []
[2021-12-14 10:57:19] php.INFO: User Deprecated: AdminCarrierWizard is a deprecated tab since version 1.7.0 and "Default" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. {"exception":"[object] (ErrorException(code: 0): User Deprecated: AdminCarrierWizard is a deprecated tab since version 1.7.0 and \"Default\" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. at C:\\wamp64\\www\\dev\\classes\\Tab.php:387)"} []
[2021-12-14 10:57:19] php.INFO: User Deprecated: AdminCarrierWizard is a deprecated tab since version 1.7.0 and "Default" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. {"exception":"[object] (ErrorException(code: 0): User Deprecated: AdminCarrierWizard is a deprecated tab since version 1.7.0 and \"Default\" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. at C:\\wamp64\\www\\dev\\classes\\Tab.php:387)"} []`

Did you encounter an error during the upgrade process ?

No error

What version oh PHP are you using ?

php 7.4.26

**Comment by florine2623** [comment] 2021-12-14 11:09
This warning issue should not have any impact on the carrier page.
PHP version is compatible with your version pf PrestaShop.

As I can't reproduce your error, if you have any questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I will close this issue.
Thank you

**Closed as completed by florine2623** 2021-12-14 11:09 UTC
Labels: Bug, BO, Carriers, Autoupgrade, Invalid
