### ISSUE TITLE
Bug In Congigurable Product

### ISSUE THREAD

**Issue by virani06** [PrestaShop/PrestaShop#13025] opened 2019-03-23 15:56 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by virani06** [comment] 2019-03-23 16:00
Describe the bug

After change the color popup display old images.

To Reproduce
Steps to reproduce the behavior:
go to product page of prestashop : https://swissoptik.ro/magazin/ochelari-de-soare/34-48-ochelari-de-soare-soglass-so1901.html#/27-culoare-bleu
2) click on pink color
3) now click on popup image so it was display base image in popup.

**Comment by khouloudbelguith** [comment] 2019-03-25 08:57
Hi @virani06,

I did not manage to reproduce the issue with the PS: 1.7.5.1
I attached a video record.
https://drive.google.com/file/d/1HRHil194x_rAfUrk8G9-6z2_p3gkS5qw/view
Did you use the template by default of PrestaShop ?
What is the exact version did you use?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-24 08:27
Hi @virani06,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-24 08:27 UTC
Labels: Bug, FO, Image, No change required
