### ISSUE TITLE
Infinite crawl loop on module ps_currencyselector due to repetition of "SubmitCurrency=..&id_currency=.."

### ISSUE THREAD

**Issue by 123monsite-regis** [PrestaShop/PrestaShop#16377] opened 2019-11-12 17:05 UTC
**Describe the bug**
Links to other currencies on front office Home Page can lead to infinite crawl loop from search-engines as they generate new urls re-adding : "SubmitCurrency=..&id_currency=.." infinitly.

**To Reproduce**
1. Install a french shop , whith at less 2 currencies activated and ps_currencyselector activated
Your shop looks like the screen below :
![bug-currency-1](https://user-images.githubusercontent.com/3170104/68692687-30217400-0576-11ea-8994-3971a54d3807.png)

2. Go on home page Front office and click to change currency 
The urls of currencies are :
![bug-currency-2](https://user-images.githubusercontent.com/3170104/68692715-3adc0900-0576-11ea-9217-95175ea49863.png)

3. click again and you have again parameters repetead:
![bug-currency-3](https://user-images.githubusercontent.com/3170104/68693012-cbb2e480-0576-11ea-850d-10992e989783.png)

4. Try the pull request as a correction.

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-11-13 08:08
Hi @123monsite-regis,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9481
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-13 08:08
Duplicate of #9481

**Closed as completed by khouloudbelguith** 2019-11-13 08:08 UTC
Labels: Duplicate
