### ISSUE TITLE
Module statsdata does not detect plugins for PS 1.7

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#13979] opened 2019-05-27 09:25 UTC
Bug reported by user PrestaPlugins on [twitter](https://twitter.com/PrestaPlugins/status/1131869421432168448)

Module statsdata is supposed to be able to detect customer browser plugins. It does not work on PS 1.7.

**To Reproduce**
1. Go to "statsdata" module configuration page, enable "detect plugins"
2. Visit front-office
3. No data gathered

According to reporter, issues are:
- JS is broken on FO because there are missing JS files that should be added through hookDisplayBeforeBodyClosingTag
- JS attempts to call an URL that is missing in 1.7

See https://twitter.com/PrestaPlugins/status/1131869421432168448 (in French)

**Comment by khouloudbelguith** [comment] 2019-05-27 12:57
Hi,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2 & the statsdata module v2.0.0.
I enabled the `Plugins detection` option, but I don't have any error js.

I tried to transplant the module statsdata to the diplayHeader but it is not possible

![image](https://user-images.githubusercontent.com/16067358/58421190-43538c80-8087-11e9-8718-8e0bae4a162a.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-26 07:58
Hi @matks,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-26 07:58 UTC
Labels: No change required, 1.7.5.2
