### ISSUE TITLE
Critical bug: Black screen when add to cart fast

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#11845] opened 2018-12-19 12:32 UTC
**Describe the bug**
Add a product to cart multiple times fast. Then the screen get black and the modal box can't be closed.

**To Reproduce**
Watch video.

[double click overlay issue.zip](https://github.com/PrestaShop/PrestaShop/files/2694827/double.click.overlay.issue.zip)
[black screen with muliitiple click cant close.zip](https://github.com/PrestaShop/PrestaShop/files/2694829/black.screen.with.muliitiple.click.cant.close.zip)

**Additionnal information**
PrestaShop version: 1.7.5 final
PHP version: 7.2.x

**Comment by khouloudbelguith** [comment] 2018-12-19 13:27
HI @MathiasReker,

Thanks for your report.
We are aware of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #9634
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-19 13:27
Duplicate of #9634

**Closed as completed by khouloudbelguith** 2018-12-19 13:27 UTC
Labels: Duplicate
