### ISSUE TITLE
Translation in overriden templates are not taken in account in the old system

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#24372] opened 2021-05-06 11:05 UTC
#### Describe the bug

I override a template from a module in my theme, I add some new strings to translate in that template.
That module still use the old translation system (maybe the issue is also concerning the new system, I don't know).
When I go to the translation tool in the back-end, I can't find my new strings. Only those from the original template are displayed, the ones from the overriden template are not proposed.

#### Expected behavior

Being able to translate everything from the overriden templates.

#### Steps to Reproduce

1. Create an override of a template for a module which is still using the old system.
2. Add some new strings in that template using {l s='your new string' mod='module name'}
3. Access the translation tool in admin, choose module +your module + your language
4. Search for the new strings, you won't find them

#### Additional information

* PrestaShop version: 1.7.7.3

**Comment by matks** [comment] 2021-05-06 11:24
Hello @Prestaplugins I have 1 question

> Add some new strings in that template using {l s='your new string' mod='module name'}

You override a module template in your theme. Which means the file which contains the translation wordings is in your theme.

Then ... the wordings should be in the Theme, not in the Module? It's a file of the theme, it should be in the "Theme" area?

**Comment by Prestaplugins** [comment] 2021-05-06 11:53
When you override some module templates in a theme, you put them in /themes/your_theme/modules/your_module/...
The existing translations (which are both in the original and overridden file) have always been done choosing "modules" in the translation tools.
In the old Prestashop version, you also had to choose your theme in the option instead of "core" to create a specific translation for that module and your theme.
Here the issue is with new sentences that don't exist in the original file. For me the process should remain exactly the same, the translation tool should also parse the overridden templates to search for differences in the translated sentences. For me, there's no reason to access that translations by choosing "theme" instead of "modules", that's not what we are used to.

**Comment by hibatallahAouadni** [comment] 2021-05-06 12:45
Hello @Prestaplugins 

Could you please check this issue #15072 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Prestaplugins** [comment] 2021-05-06 12:56
Hello @hibatallahAouadni

That issue is absolutely not similar to mine. It's talking about translation into admin template, not using override, and not using the old translation system.
Mine is about modules translation, in templates overriden into the theme used by the shop.

**Comment by hibatallahAouadni** [comment] 2021-05-11 04:18
Hello @Prestaplugins 

Thanks for your feedback.
> Mine is about modules translation, in templates overriden into the theme used by the shop.

So your issue is a duplicate to this one #13392, could you please confirm it.

Thanks!

**Comment by Prestaplugins** [comment] 2021-05-11 08:19
Yes, it seems quite similar if I read the 1st post of that issue, talking about some new labels into the override that doesn't exist in the original file.
Then, no one talks anymore about new labels... they just talk about existing labels... so I don't know...

**Comment by hibatallahAouadni** [comment] 2021-05-11 12:04
Hello @Prestaplugins 

Thanks for your feedback!
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #13392. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: could you please add your comment (your thoughts) in that issue, so the Core Dev get notified :pray: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-11 12:04
Duplicate of #13392

**Closed as completed by hibatallahAouadni** 2021-05-11 12:04 UTC
Labels: Bug, BO, Duplicate, Modules, Translations, 1.7.7.3
