### ISSUE TITLE
new string tanslation in custom theme

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#12632] opened 2019-02-20 03:52 UTC
I have new string in my theme in the file "mytheme\modules\ps_shoppingcart.tpl" file.
Code in this file is as below:
`<p class="no-item">{l s='There is no item in your cart' d='Shop.Mytheme'}</p>`

I have exported theme in polish language and copy all .xlf file to the mytheme/translations/pl-PL/ folder but still I'm not able to find this string and domain Mytheme in back-office.

I'm using 1.7.5.0 version.

**Comment by khouloudbelguith** [comment] 2019-02-20 10:13
Hi @Akashvastarpara,

I did not manage to reproduce the issue with PS1.7.5.0 & with this custom theme
[mytheme.zip](https://github.com/PrestaShop/PrestaShop/files/2884084/mytheme.zip)
In the file mytheme\modules\ps_shoppingcart.tpl" file.
I added this code
`<p class="no-item">{l s='There is no item in your cart' d='Shop.Mytheme'}</p>`
And I folowed these steps
http://build.prestashop.com/howtos/translation/how-to-translate-your-theme/#case-2:-you-are-creating-new-strings-in-files-that-already-exist-in-the-default-theme
& now the new string is successfully added.
I attached a video record.
https://drive.google.com/file/d/1TuB8RXxT2A9M_qmxxtSkIic50YKEVUVZ/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-03-22 07:41
Hi @Akashvastarpara 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-22 07:41 UTC
Labels: BO, Translations, Modules & Themes, No change required, 1.7.5.0
