### ISSUE TITLE
Exception thrown after an upgrade from 8.0.4 to 8.1.0 when using Cash on Delivery module

### ISSUE THREAD

**Issue by markoopapa** [PrestaShop/PrestaShop#33047] opened 2023-06-29 12:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I make update from PS 8.0.4 to PS 8.1 and now when i make order with COD i rteceive this error: error 500
Details (With debug mode)
![image](https://github.com/PrestaShop/PrestaShop/assets/20978213/e2fa35d7-a6aa-4b5a-b598-00aec595fb90)

All othe payment mode are working this problem presist only at COD
I try to disable all non prestashop modules but is the same problem

### Steps to reproduce

1. update from 8.0.4 to 8.1 
2. Place an order with COD

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_cashondelivery 2.0.1

### Your company or customer's name goes here (if applicable).

Mark

**Comment by florine2623** [comment] 2023-06-29 12:59
Hello @markoopapa ,

I can't reproduce your issue after doing an upgrade from 8.0.4 to 8.1.0.

Made an order from FO:

https://github.com/PrestaShop/PrestaShop/assets/16019289/f4ca0a50-5a63-4407-a571-a5dbc6c665bb


Made an order from BO:

https://github.com/PrestaShop/PrestaShop/assets/16019289/a2e7b7f1-6f4a-4596-aef3-e4d18ee4d2b0

I'm using Cash on delivery (COD) `v2.0.1` and 1-Click Upgrade `v4.16.0`

No exception is displayed.

**Comment by markoopapa** [comment] 2023-06-29 13:07
Ok, i see result. Can i solve this problem?

**Comment by markoopapa** [comment] 2023-06-29 13:09
@florine2623  i try from backofficve and i receive this error:

Failed to add order. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_employee' in 'field list'

**Comment by markoopapa** [comment] 2023-06-29 13:10
All other payment tipe work

**Comment by Tobbewik** [comment] 2023-06-29 13:20
I had the same problem with another payment module. 
I added the column id_employee in ps_order_payment.
Then it worked fine.
Good luck

**Comment by markoopapa** [comment] 2023-06-29 13:22
@Tobbewik Can you plz tell me more exactly where you added the column?

**Comment by Tobbewik** [comment] 2023-06-29 13:24
In the database table ps_order_payment

**Comment by Tobbewik** [comment] 2023-06-29 13:29
It has to be null enabled

**Comment by markoopapa** [comment] 2023-06-29 13:31
@Tobbewik like this?
![image](https://github.com/PrestaShop/PrestaShop/assets/20978213/2744a146-782b-42ea-bada-ce21238b3b23)

**Comment by markoopapa** [comment] 2023-06-29 13:32
i change fron none to NULL

**Comment by Tobbewik** [comment] 2023-06-29 13:32
It has to be null enabled

**Comment by markoopapa** [comment] 2023-06-29 13:34
THX a loot @Tobbewik That work. Now is ok

**Comment by Tobbewik** [comment] 2023-06-29 13:35
Perfect! 
:=)

**Comment by florine2623** [comment] 2023-06-29 15:21
Thanks @Tobbewik and @markoopapa 🙏 
You rock.

I'm closing this issue as it is fixed !

**Closed as completed by florine2623** 2023-06-29 15:21 UTC
Labels: Bug, Order, Autoupgrade, Fixed, ps_cashondelivery, Module, 8.1.x

**Comment by Johnnyx2010** [comment] 2023-07-04 15:08
Hi I'm opening this as I'm unsure is this is fixed because the user manually added the column or the dev team have updated some code.. As if I upgrade from 1.7.8.9 and compare to a clean install of PS 8 the column is missing from ps_order_payment. Surely the upgrade script should be adding this column to the table

**Comment by Hlavtox** [comment] 2023-07-15 11:06
Issue will be resolved after release of new version of autoupgrade module.
For existing upgrades, you can fix the issue permanently by running this SQL.

```sql
ALTER TABLE `ps_order_payment` ADD `id_employee` INT NULL AFTER `date_add`;
```
