### ISSUE TITLE
When you edit a specific price in BO and you close the modal with ESC, you cannot scroll anymore in the product form

### ISSUE THREAD

**Issue by mowcixo** [PrestaShop/PrestaShop#12911] opened 2019-03-13 16:10 UTC
**Describe the bug**
When you edit a specific price in BO and you close the modal, you cannot scroll anymore in the product form.

**To Reproduce**
1. Go to a product form that has specific prices.
2. Click on any specific price edit button.
3. Close the modal.
4. You will not be able to scroll anymore in the product form.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-03-14 07:46
Hi @mowcixo,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1UHKd--M1pMMaBy0Zqa4O2nuB5IbD1CKo/view
Thanks to check & feedback.

**Comment by mowcixo** [comment] 2019-03-14 07:55
Hi @khouloudbelguith, sorry for the leak of details. It only happens when you click on the modal's overlay or press ESC key, not when you click any button on the modal.

**Comment by khouloudbelguith** [comment] 2019-03-14 08:36
@mowcixo, thanks for these clarifications.
Yes, when I click on "ESC" key from the keyboard, I cannot scroll anymore in the product form.
Issue reproduced with PS1.7.5.0 & PS1.7.5.1
https://drive.google.com/file/d/1ZERU0BO8OTDTwFXrnOidtP2HHPIxNTyA/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
ping @matks what do you think?
Thanks!

**Comment by davidglezz** [comment] 2020-03-09 21:42
Currently a modal is no longer used. So this bug no longer exists, right?

**Comment by hibatallahAouadni** [comment] 2021-11-01 13:40
Reproduced on 1.7.8.0

**Comment by MatShir** [comment] 2023-07-04 16:51
It seems to be fixed on the new product page on PS 8.1 :)

**Closed as completed by MatShir** 2023-07-04 16:51 UTC
Labels: Bug, Trivial, BO, Fixed, 1.7.5.0
