### ISSUE TITLE
Module Dashproducts PHP 7.2 Warning in Server Log

### ISSUE THREAD

**Issue by Alcpaone** [PrestaShop/PrestaShop#20770] opened 2020-08-28 13:18 UTC
[php7:warn] PHP Warning:  Invalid argument supplied for foreach() in /XXXXXX/prestashop/modules/dashproducts/dashproducts.php on line 219

#### Describe the bug

Warning in Serverlog.

#### Expected behavior
No Warning in the Serverlog.

#### Steps to Reproduce

Nothing special known.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-08-28 14:01
Hi @Alcpaone,

I did not manage to reproduce the issue with PS1.7.6.7.
I used PHP 7.2.22
I attached a screen record
https://drive.google.com/file/d/1qIgtg8z7rt8iPD9A0nYVLmuV4syvYw2y/view?usp=sharing
In the Prestashop_folder/var/logs/ there is no error about  `dashproducts` module.
Thanks to check and feedback.

**Comment by sarahdib** [comment] 2020-09-21 09:48
Hello

Since we had no news from, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Closed as completed by sarahdib** 2020-09-21 09:48 UTC
Labels: Bug, BO, Dashproducts, No change required, 1.7.6.5

**Comment by jaxtheking** [comment] 2021-02-11 18:10
Hi @khouloudbelguith,
I'd like this ticket to be re-opened as I can confirm the issue is still occurring as of 1.7.7.1 on PHP 7.2 and 7.3.

Note that the error (a PHP Warning actually) will not show up in var/logs but in the server's error_log file.
This is due to PHP7 raising a warning when using foreach loops on anything other than countables (array or object).

Around line 219 of modules/dashproducts/dashproducts.php the code looks like this:
```
$body = array();
foreach ($products as $product) {
    ...
}

return array('header' => $header, 'body' => $body);
```
If the SQL query for bestseller products returns no products (like in my case), then the `$products` variable is a boolen therefore not loopable. No warning is raised if the query returns an array of products instead.

The solution is easy - actually already implemented in the same scripts for all other foreach loops other than line 116 (orders):
```
$body = array();
if (is_array($products)) {
  foreach ($products as $product) {
    ...
  }
}

return array('header' => $header, 'body' => $body);
```

Hope that helps,
Luca

**Comment by demperador** [comment] 2021-09-09 10:04
Hello,

I am having this same exact warning in version 1.7.7.6 and PHP 7.3.23 and mariadb 10.2.36

Regards.
