### ISSUE TITLE
Deleting a product with customization 

### ISSUE THREAD

**Issue by carlosul** [PrestaShop/PrestaShop#19178] opened 2020-05-18 08:44 UTC
When deleting a product with a customization it only deletes de customization in the first try, leaving the product in the cart but without the customization. The client needs to delete the product two times to fully remove it from the cart.

The customization in the product is mandatory and the product shouldn't be able to be added without it.

#### Expected behavior

When a client deletes a product with customization the product should be fully removed.

#### Steps to Reproduce

1. Add product with customization to cart
2. Remove product with customization from cart
3. See error

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.0

**Comment by florine2623** [comment] 2020-05-18 09:27
Hi @carlosul,
I couldn't manage to reproduce your issue, please check my screen record :
https://drive.google.com/file/d/1M4gt3Dn2me9a1xLdkM8cL8hrTIn_8HBf/view
Are you using any modules for the cart ?
If yes, please deactivate the overrides and try again
Thanks!

**Comment by carlosul** [comment] 2020-05-18 09:48
Hi! I'm using Prestashop's cart module.
I think that you are using a combination. My problem occurs with customizations from "Options" of the product page. I have a text customization.

Thanks!

**Comment by florine2623** [comment] 2020-05-18 10:13
Sorry, my bad. Here's another screen record : https://drive.google.com/file/d/12OBQmBWVkqtGBFvjk_pFaVGp3C-izc2Z/view
I can't reproduce your issue in neither PS 1.7.6.4 or PS 1.7.7.0.
Can you check the overrides folder please ?

**Comment by carlosul** [comment] 2020-05-18 23:22
Sorry I was using a custom code for adding the customization to the cart automatically.
There was a bug with this implementation, now it's fixed thanks!

p.d. It would be nice to be able to add customizations automatically to cart. I think this is a big UX flaw.

**Comment by LouiseBonnard** [comment] 2020-05-20 09:36
Hi @carlosul, since it is fixed, I close this issue. Feel free to reopen if need be, thanks!

**Closed as completed by LouiseBonnard** 2020-05-20 09:36 UTC
Labels: FO, Combinations, Blockcart, Fixed, 1.7.6.4
