### ISSUE TITLE
Cannot upgrade to Prestashop 1.7.6.3

### ISSUE THREAD

**Issue by simontingkamlee** [PrestaShop/PrestaShop#17815] opened 2020-02-25 06:49 UTC
Hi,
I am using PrestaShop 1.7.6.2 and try to upgrade to Prestashop 1.7.6.3 using 1-click-upgrade v4.10.1. All the requirements checklist are ok. But when it is at upgrading the Addons modules, it stopped and started rolling backing.
Here's what was displayed in the Activity Log:
...
All files upgraded. Now upgrading database...
Database upgraded. Now upgrading your Addons modules...

And in the box below "Activity Log"
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File dev removed
[CLEANING CACHE] File prod removed
Migrating old setting file...
parameters file already exists!
Finished...
[OK] PHP 1.7.6.3:/*PHP:ps_1763_update_tabs();*/
Database upgrade OK
Warning detected during upgrade.
[DEV] ajax request: upgradeModules

At this point, it stopped and started the rollback.
I have using a theme that are purchased.
Please advise what is wrong or where I can find the log to see why it stopped. Thanks.

Regards,
Simon

**Comment by khouloudbelguith** [comment] 2020-02-25 08:36
Hi @simontingkamlee,

Thanks for your report.
In the 1-Click Upgrade configuration page, the `Disable non-native modules` is enabled or not.
Try to enable it, save and try to make a new upgrade.
![image](https://user-images.githubusercontent.com/16067358/75229499-4d3f2300-57b2-11ea-9099-f122724288c8.png)

Thanks to check & feedback.

**Comment by simontingkamlee** [comment] 2020-02-25 10:29
I tried as you suggest. Still no luck. Please see screen shot before rollback.

**Comment by khouloudbelguith** [comment] 2020-02-25 10:36
@simontingkamlee, there is no screenshot attached.
You should log in to GitHub and upload your picture here.
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by simontingkamlee** [comment] 2020-02-25 11:04
Thank you for following up. Here’s the log file.

 

https://www.dropbox.com/s/prfu6qwkn1lud5k/log.txt?dl=0

 

Regards,

Simon

**Comment by simontingkamlee** [comment] 2020-02-25 11:35
Here's the screen shot before the roll back.
[https://www.dropbox.com/s/zz6ypqzex2unxx1/ps_error.jpg?dl=0](https://www.dropbox.com/s/zz6ypqzex2unxx1/ps_error.jpg?dl=0)
Regards,
Simon

**Comment by khouloudbelguith** [comment] 2020-02-25 11:49
@simontingkamlee, could you please provide the list of modules installed in your case
![image](https://user-images.githubusercontent.com/16067358/75244990-1e827600-57cd-11ea-9feb-f327bd91058c.png)

I think it is related to module which brokes the upgrade.

THanks!

**Comment by simontingkamlee** [comment] 2020-02-25 13:12
Please use the following FTP to log on and access the files.

>Edited by Khouloud

Thanks.

Simon

----- Original Message -----
From: "PrestaShop/PrestaShop"
<reply@reply.github.com>
To:"PrestaShop/PrestaShop" <PrestaShop@noreply.github.com>
Cc:"simontingkamlee" <simonlee@hago-group.com>, "Mention"
<mention@noreply.github.com>
Sent:Tue, 25 Feb 2020 03:49:01 -0800
Subject:Re: [PrestaShop/PrestaShop] Cannot upgrade to Prestashop
1.7.6.3 (#17815)

	@simontingkamlee [1], could you please provide the list of modules
installed in your case
 [2] 

	I think it is related to module which brokes the upgrade. 

	THanks! 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [3], or unsubscribe
[4]. 

Links:
------
[1] https://github.com/simontingkamlee
[2]
https://user-images.githubusercontent.com/16067358/75244990-1e827600-57cd-11ea-9feb-f327bd91058c.png
[3]
https://github.com/PrestaShop/PrestaShop/issues/17815?email_source=notifications&amp;email_token=AM4OEICUOYBB3PBQPWCVA6DREUAS3A5CNFSM4K263DHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM3VG2I#issuecomment-590828393
[4]

**Comment by khouloudbelguith** [comment] 2020-02-25 13:21
@simontingkamlee,

This is a public space.
I removed the credentials
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-25 13:42
@simontingkamlee, I tried with the credentials sent by I have an error
`Error: Unable to establish a connection to the server`.

Thanks!

**Comment by simontingkamlee** [comment] 2020-02-25 14:25
What is a good way to send you the files to see?

Do you have a personal email?

Regards,
Simon

----- Original Message -----
From: "PrestaShop/PrestaShop"
<reply@reply.github.com>
To:"PrestaShop/PrestaShop" <PrestaShop@noreply.github.com>
Cc:"simontingkamlee" <simonlee@hago-group.com>, "Mention"
<mention@noreply.github.com>
Sent:Tue, 25 Feb 2020 05:42:57 -0800
Subject:Re: [PrestaShop/PrestaShop] Cannot upgrade to Prestashop
1.7.6.3 (#17815)

	@simontingkamlee [1], I tried with the credentials sent by I have an
error
 Error: Unable to establish a connection to the server. 

	Thanks! 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3]. 

Links:
------
[1] https://github.com/simontingkamlee
[2]
https://github.com/PrestaShop/PrestaShop/issues/17815?email_source=notifications&amp;email_token=AM4OEIB3GSU3RY3H6Z24OD3REUN6DA5CNFSM4K263DHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM4ADZQ#issuecomment-590873062
[3]

**Comment by simontingkamlee** [comment] 2020-02-26 08:25
Please let me know your private email so that I can share a way to get the files on my server to you. Thanks.

 

Regards,

Simon

**Comment by khouloudbelguith** [comment] 2020-02-26 08:35
@simontingkamlee,
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-27 16:43
@simontingkamlee, your upgrade was stopped after the upgrade of the `graphnvd3` module.
So, it could be related to the `gridhtml` module or it is a space issue on your server, you don't have a large space, so the upgrade was stopped.

Thanks to check & feedback.

**Comment by simontingkamlee** [comment] 2020-02-28 02:57
Thank you for the follow up. May I ask

1.	When you mean not enough space, do you mean RAM or hard disk space? Currently the server has 2048 MB RAM and 55GB Hard Disk? How much space would you recommend?
2.	Can you let me know where I should look to troubleshoot issue like this? How do you locate the problem like in this case? Just want to know more about the internal working of Prestashop. Thanks.

 

Regards,

Simon

**Comment by simontingkamlee** [comment] 2020-02-28 10:48
Hi,

 

I cleared some of the space on the server and retry. This time there’s an error message. Please see enclosed. Is it still a space issue?

 

The Chinese text on the error means “The language pack cannot be used”.

 

Thanks.

 

Regards,

Simon

**Comment by khouloudbelguith** [comment] 2020-02-28 11:16
@simontingkamlee,

>Can you let me know where I should look to troubleshoot issue like this? How do you locate the problem like in this case? Just want to know more about the internal working of Prestashop

In your log file, I found this
1. All files upgraded. Now upgrading database => upgrade of your files was done successfully
2. Database upgrade OK => upgrade of your database was done successfully
3. Database upgraded. Now upgrading your Addons modules...
4. The files of module graphnvd3 have been upgraded. => the last module upgraded was graphnvd3
5. 62 modules left to upgrade. => at this step the upgrade was stopped
=> there is no information about the cause.

After upgrading the `graphnvd3` module, we pass to the upgrade to `gridhtml` module if it is not stopped.

That's why I think it could be related to the `gridhtml` module or it is a space issue on your server.


>[2020-02-28 10:44:32] Download of the language pack en failed. 語言包不可用。 http://i18n.prestashop.com/translations/1.7.6.3/en-US/en-US.zip

It could be a problem of a network which is not available, as described in this issue: #10456 Thanks to check again & feedback.

**Comment by simontingkamlee** [comment] 2020-02-28 16:49
Hi,

I tried upgrade my server to double the space (80G) and RAM (4G) but
still the same error. Please see the error log as enclosed. Any
suggestion? Thanks.

Regards,
Simon

----- Original Message -----
From: "PrestaShop/PrestaShop"
<reply@reply.github.com>
To:"PrestaShop/PrestaShop" <PrestaShop@noreply.github.com>
Cc:"simontingkamlee" <simonlee@hago-group.com>, "Mention"
<mention@noreply.github.com>
Sent:Fri, 28 Feb 2020 03:16:11 -0800
Subject:Re: [PrestaShop/PrestaShop] Cannot upgrade to Prestashop
1.7.6.3 (#17815)

	@simontingkamlee [1],  

	Can you let me know where I should look to troubleshoot issue like
this? How do you locate the problem like in this case? Just want to
know more about the internal working of Prestashop  

	In your log file, I found this 

 	* All files upgraded. Now upgrading database => upgrade of your
files was done successfully
 	* Database upgrade OK => upgrade of your database was done
successfully
 	* Database upgraded. Now upgrading your Addons modules...
 	* The files of module graphnvd3 have been upgraded. => the last
module upgraded was graphnvd3

	* 62 modules left to upgrade. => at this step the upgrade was stopped
 => there is no information about the cause. 

	After upgrading the graphnvd3 module, we pass to the upgrade to
gridhtml module if it is not stopped. 

	That's why I think it could be related to the gridhtml module or it
is a space issue on your server.  

	[2020-02-28 10:44:32] Download of the language pack en failed.
語言包不可用。
http://i18n.prestashop.com/translations/1.7.6.3/en-US/en-US.zip [2]  

	It could be a problem of a network which is not available, as
described in this issue: #10456 [3] Thanks to check again & feedback. 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [4], or unsubscribe
[5]. 

Links:
------
[1] https://github.com/simontingkamlee
[2] http://i18n.prestashop.com/translations/1.7.6.3/en-US/en-US.zip
[3] https://github.com/PrestaShop/PrestaShop/issues/10456
[4]
https://github.com/PrestaShop/PrestaShop/issues/17815?email_source=notifications&amp;email_token=AM4OEIDZJLFWZD6FT7H3RULRFDW7XA5CNFSM4K263DHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENIFXQY#issuecomment-592468931
[5]

**Comment by khouloudbelguith** [comment] 2020-03-02 13:50
I tried with the credentials sent by I have an error
`Error: Unable to establish a connection to the server`.
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by simontingkamlee** [comment] 2020-03-03 03:11
Sorry, I changed something on the FTP access but now I changed it back. It should work now with the credentials. Thanks!

 

Regards,

Simon

**Comment by khouloudbelguith** [comment] 2020-03-03 09:52
@simontingkamlee, could you please follow this link: https://github.com/PrestaShop/php-ps-info 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
Or simply download this file
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4280558/phppsinfo.php.zip)

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by simontingkamlee** [comment] 2020-03-04 07:14
Done. You can access by http://45.32.14.214/phppsinfo.php

 

Regards,

Simon

**Comment by khouloudbelguith** [comment] 2020-03-04 08:41
@simontingkamlee, you are using PHP7.3.
![image](https://user-images.githubusercontent.com/16067358/75860530-43de3800-5dfc-11ea-9869-ad79b05027e4.png)
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-04-03 07:15
Hi @simontingkamlee, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-03 07:15 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.6.2

**Comment by FredPeng** [comment] 2020-05-21 20:39
> @simontingkamlee, could you please follow this link: https://github.com/PrestaShop/php-ps-info
> phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
> Or simply download this file
> [phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4280558/phppsinfo.php.zip)
> 
> 1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
> 2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
> 3. Now you can view all of the information about PHP for your server for that particular directory.
>    ![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
> 
> Thanks to check and feedback.

This method helped me. Thanks. After I changed the inconformities and it start to install modules.
