### ISSUE TITLE
CSV import error (contact stores) PS 1.7.4.2

### ISSUE THREAD

**Issue by hellodracon** [PrestaShop/PrestaShop#10437] opened 2018-09-14 13:12 UTC
**Describe the bug**
Hi,

I'm trying to import stores contacts via a CSV file using the import page from Prestashop 1.7.4.2 but I have an error I really can't understand.

I'm loading the csv file, force IDs, skip row 1, select the columns and click on load but I have an error that tells me names' fields are invalid.

I even tried with the downloadable file from Prestashop that gives an example on how the CSV file should looks like and I got the same error.
If you wanna try, just ignore the "state" column while configuring the import.

Thanks in advance

**Screenshots**
![capture d ecran 2018-09-14 a 12 04 51](https://user-images.githubusercontent.com/5995162/45552139-43c93180-b830-11e8-8520-441dfa05a2a2.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.30

**Comment by khouloudbelguith** [comment] 2018-09-14 13:22
Hi @hellodracon 

Thanks for your report.
This issue is fixed in the next release 1.7.5.0
It will be released in October.
https://drive.google.com/file/d/1tX_hpLP8kfJ7AsYBUjbvgFP1alElge64/view

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-14 13:23
Duplicate of #10418

**Closed as completed by khouloudbelguith** 2018-09-14 13:22 UTC
Labels: Duplicate

**Comment by hellodracon** [comment] 2018-09-14 13:28
Hi and thank you for your answer @khouloudbelguith  but is there a file I can download or something I can change please ? The site that needs it should be online in a few days and this is the final thing we have to do (I'm talking 100+ shops, can't do it manually).

Thank you  !

**Comment by khouloudbelguith** [comment] 2018-09-14 13:35
Hi @hellodracon,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9235 to solve the issue.

Best regards, Khouloud

**Comment by hellodracon** [comment] 2018-09-14 13:39
Thanks a lot @khouloudbelguith
