### ISSUE TITLE
BO - dataprivacy module - Bad display of Customer data privacy block when changing the language

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27153] opened 2021-12-30 15:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad display of Customer data privacy block when changing the language
![image](https://user-images.githubusercontent.com/89604350/147762881-eaa76251-149f-44ef-ac32-1eb8a2222e57.png)
![image](https://user-images.githubusercontent.com/89604350/147762903-0e6ca08e-23f2-4d89-9b52-475ff0178b78.png)

###  Screen record
https://watch.screencastify.com/v/KUbrLDY6mvm6kHHk84pR

### Steps to reproduce

1- Go to BO> International > Translations > Add / Update a language more than 2 language
2- Go to Module manager> Configure  the module Customer data privacy block
3- resize the screen
4- change the language many times 
5- the page will be bad displayed
This issue maybe caused by this PR
https://github.com/PrestaShop/ps_dataprivacy/pull/32

### PrestaShop version(s) where the bug happened

1.7.8.2 / develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_dataprivacy  v2.0.1

**Comment by florine2623** [comment] 2023-12-27 10:51
I can't reproduce this issue on PS 8.1.x.


https://github.com/PrestaShop/PrestaShop/assets/16019289/a3b30b8f-c28e-4a64-9ade-bf4012c6cc7b



So I'm closing it.

**Closed as completed by florine2623** 2023-12-27 10:51 UTC
Labels: Bug, Trivial, Dataprivacy, Responsive, Verified, Module
