### ISSUE TITLE
Create Account on Order Confirmation not work

### ISSUE THREAD

**Issue by MassimoGS3** [PrestaShop/PrestaShop#22994] opened 2021-01-26 09:41 UTC
#### Describe the bug

After complete an order like a guest i've try to register an account on confirmation order page by reg. form.
The page do a postback without register the user and redirect to /login?back=history.

In BO i see on customer list the guest of the previous order but not the registred user.

#### Expected behavior

I excpect a new user registred account

#### Steps to Reproduce

1. Complete an order like a guest.
2. On confirmation page use the form to register an account.
3. Go to BO, in Customer list. You don't find the last registred user

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2 / 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-26 10:24
Hello @MassimoGS3 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #14414. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-26 10:24
Duplicate of #14414

**Closed as completed by hibatallahAouadni** 2021-01-26 10:24 UTC
Labels: Duplicate
