### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#11259] opened 2018-11-05 09:11 UTC
Apparently still not working
https://github.com/PrestaShop/PrestaShop/issues/9684
0 of 15 tasks complete from August :(

Guys c'mon. This is crucial FO bug. We can't promote 1.7 version for any clothes/shoe etc. web stores...
"Oh. Sorry about that parametric search. It dont work since not resolved bug since august. August? We have November.... Yep. We have November..."

**Comment by khouloudbelguith** [comment] 2018-11-05 09:20
Hi @PrestaShark,

All this issue are added to our bug roadmap.
There are some major issues to solve before.
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.
It wasn't necessary to create a new one.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-05 09:20
Duplicate of #9684

**Closed as completed by khouloudbelguith** 2018-11-05 09:20 UTC
Labels: Duplicate
