### ISSUE TITLE
Fail to send mail on Order State update through webservice

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#20315] opened 2020-07-24 10:12 UTC
#### Describe the bug

When you update order's state through webservice AND you ask to send the email notification, you get an HTTP error 500.

#### Expected behavior

Order's status must be update, email sent and no HTTP 500 error.

#### Steps to Reproduce

1. You can use my test file (attached here) [add_order_state_ps15.zip](https://github.com/PrestaShop/PrestaShop/files/4971415/add_order_state_ps15.zip)
2. Take care to use the "?sendmail=1" parameter in order to ask to send email. Run it
3. See HTTP error exception

#### Additional information
It seems to be a Prestashop 1.7.6 regression. I don't have this bug previously.

* PrestaShop version: 1.7.6.0, 1.7.6.1, 1.7.7.0 beta 1

**Comment by sowbiba** [comment] 2020-07-27 09:49
Thanks @Max84 for the report. And a great thanks for the script, it is very helpful

But I dont reproduce your issue. I tried to update an order which status was 2 (waiting for payment = En attente de virement bancaire) to (In preparation = En cours de préparation). And it works fine
PS version = 1.7.6.7
Do I miss something ? Have you configure well the permissions for your webservice key ?

I'm trying with 1.7.6.0 and 1.7.7 beta ...

**Comment by sowbiba** [comment] 2020-07-27 11:42
Ok, I reproduce it in one version

On 1.7.6.0, I got 
Fatal error: Uncaught Error: Call to a member function get() on null in /home/xxx/workspace/PrestaShop176/classes/Tools.php on line 801

On other versions, when Emailing is not well configured, we have 

 Error.<br />Unable to save resource in /home/xxx/Téléchargements/add_order_state_ps15.php:258

The error is in OrderHistory->addWS when sendemail is true

When Email configuration is OK, I have no error

Tested on 
1.7.6.1
1.7.6.3
1.7.6.5
1.7.6.6
1.7.6.7
and 1.7.7 beta

**Comment by khouloudbelguith** [comment] 2020-07-27 14:45
Hi @Max84, @sowbiba,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14899 to fix the issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/14842
It is fixed in PS1.7.6.1.

@Max84, thanks to check and feedback.

**Comment by Max84** [comment] 2020-07-27 14:47
Thanks 👍

**Comment by khouloudbelguith** [comment] 2020-07-27 14:48
@Max84,

Your ticket is a duplicate of #14842
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-27 14:48
Duplicate of #14842

**Closed as completed by khouloudbelguith** 2020-07-27 14:48 UTC
Labels: Bug, WS, Duplicate, Order, 1.7.6.0
