### ISSUE TITLE
Error 500 when I try to save the legend of image products. Image->id_product is empty

### ISSUE THREAD

**Issue by tiche** [PrestaShop/PrestaShop#18406] opened 2020-04-01 06:52 UTC
When I try to save the legend of image products, It doesn´t work, doesn´t save anything. If I see the log, it throws an exception, and it says that the property Image->id_product is empty. 

![image png 55d90008cf1b46fc05a82ca08f6b7b74](https://user-images.githubusercontent.com/43927784/78107078-1a153280-73f5-11ea-9be4-9f9b9ce13550.png)

![image thumb png 2bbec143fd60be024157ae7f85c8014c](https://user-images.githubusercontent.com/43927784/78107201-4c269480-73f5-11ea-900f-704261b18ab4.png)

Someone know how I can to fix this bug? The prestashop version is 1.7.5.2

**Comment by khouloudbelguith** [comment] 2020-04-01 09:17
Hi @tiche,

I did not manage to reproduce the issue with PS1.7.5.2 and PS1.7.6.4.
https://drive.google.com/file/d/1Kv7Td-hVhIuJaZeCD2L_SPinVNdvAONr/view?usp=sharing
Did you use any custom module or do you have any override related to the images?

Thanks!

**Comment by sarahdib** [comment] 2020-05-05 12:12
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 12:12 UTC
Labels: Bug, BO, Image, No change required, 1.7.5.2
