### ISSUE TITLE
Prestashop installation error at 67%

### ISSUE THREAD

**Issue by amiralkgb** [PrestaShop/PrestaShop#21192] opened 2020-09-28 18:38 UTC
Hi,

I'm using online hosting from hostinger.com and when trying to install Prestashop 1.7.7.0 beta 2,  got error at 67%:

An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

"1: An exception occurred while executing 'SELECT t0.id_tab AS id_tab_1, t0.id_parent AS id_parent_2, t0.position AS position_3, t0.module AS module_4, t0.class_name AS class_name_5, t0.route_name AS route_name_6, t0.active AS active_7, t0.enabled AS enabled_8, t0.hide_host_mode AS hide_host_mode_9, t0.icon AS icon_10 FROM ps_tab t0 WHERE t0.class_name = ? LIMIT 1' with params ["AdminGamification"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" 

Print below:
<a href="https://ibb.co/GW84Qyw"><img src="https://i.ibb.co/D9vHfhX/Prestashop-error.jpg" alt="Prestashop-error" border="0"></a>

* PrestaShop version: 1.7.7.0 beta 2
* PHP version: 7.3

I can't figure out why do I get this error as if I install 1.7.6 version, everything goes alright.

Thank you

**Comment by khouloudbelguith** [comment] 2020-09-29 07:57
Hi @amiralkgb,

Thanks for your report.
I did not manage to reproduce the issue with PS1770beta2.
Here's my configuration
![image](https://user-images.githubusercontent.com/16067358/94529428-02025c80-023a-11eb-8ea9-0c40707b5c61.png)
Thanks to follow this [link](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#how-to-verify-your-server-meets-prestashops-requirements) and check if all configuration is ok and feedback.

Thanks!

**Comment by SimonGrn** [comment] 2020-09-29 09:51
`General error: 2006 MySQL server has gone away` is a generic error that occurs when your MySQL server shutted down because of too much load. Your server is not powerful enough.
This is something you may want to check with your hosting provider.

I close this issue as it's not a core PrestaShop issue. Feel free to open a new one if you have new information related to the core or natives modules.
Thank you for your understanding.

**Closed as completed by SimonGrn** 2020-09-29 09:51 UTC
Labels: Bug, IN, No change required, 1.7.7.x
