### ISSUE TITLE
versions 1.7.7 & 1.7.8 : defined() in error because of missed quotes

### ISSUE THREAD

**Issue by cy-altern** [PrestaShop/PrestaShop#26795] opened 2021-11-29 13:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

`_PS_ENV_` whitout quote L64 on file `src/Adapter/Environnement.php` :
```
if (defined(_PS_ENV_)) {
```
=> warning

same problem L56 for `_PS_MODE_DEV_` :
```
$this->isDebug = defined(_PS_MODE_DEV_) ? _PS_MODE_DEV_ : true;
```

This 2 problems seems to be corrected on develop branch.

### Steps to reproduce

1.  set `_PS_MODE_DEV_` on true in `config/defines.inc.php`
2. open any page in the shop to get a warning because of the `_PS_ENV_` whitout quote on L64 form file `src/Adapter/Environnement.php`

### PrestaShop version(s) where the bug happened

1.7.7* et 1.7.8*

### PHP version(s) where the bug happened

all

**Comment by hibatallahAouadni** [comment] 2021-11-29 14:54
Hello @cy-altern 

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by cy-altern** [comment] 2021-11-29 15:33
done : could you re-open the issue please ?

**Comment by hibatallahAouadni** [comment] 2021-11-30 18:18
Hello @cy-altern 

I didn't manage to reproduce the issue with PS1778 and PS1781, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/144104857-5f2b9a68-9898-4d38-b42e-351e069e1e97.png)

Please check and feedback.
Thanks!

**Comment by cy-altern** [comment] 2021-12-01 17:12
due to this problem I had rollup back my 1.7.8 installation to 1.7.6 but by the way the code *is* buggy : it missed quote around the constant's name on the 2 lines of src/Adapter/Environnement.php (56 and 64)
=> see the develop branch : this 2 bugs are corrected
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Environment.php

**Comment by marwachelly** [comment] 2021-12-07 13:32
Hi @cy-altern,

I did not manage to reproduce the issue with PS1781.
I attached a screen record
https://watch.screencastify.com/v/E6TX2Lb2fcRhi5E2IZN3

What is the exact php version did you use?

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-27 08:14
Hello @cy-altern 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-27 08:14 UTC
Labels: Bug, BO, Performance, 1.7.7.8, Invalid
