### ISSUE TITLE
Customer details not reachable. Customer ID 0

### ISSUE THREAD

**Issue by feyll** [PrestaShop/PrestaShop#12297] opened 2019-01-24 17:26 UTC
Hello, for some time when a customer is registered on my site this is not assigned any ID number and when I click on the customer this gives me an error page saying that the customer's details are not available.
I went into the ps_customer table, I downloaded and modified the values 0 and set the correct values after which I loaded the new modified table, I returned to the FO and now the customer details are reachable. But if I create a new customer the problem is repeated and this is not assigned ID number.
From debug mode I can not get any errors that are due to this, even in the log files I can not find something for this.
Would anyone kindly suggest to me how to investigate the problem when debugging does not provide solutions?
Someone found himself before me with this problem?
PS: sorry for my english.
![screenshot 10](https://user-images.githubusercontent.com/27018255/51696316-82a09c80-2005-11e9-847d-b1a4c8271d09.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-01-25 09:13
Hi @feyll,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by feyll** [comment] 2019-01-25 11:54
@khouloudbelguith  Hi

![screenshot 11](https://user-images.githubusercontent.com/27018255/51744078-fba00280-209e-11e9-862c-ec44851e9baa.png)
![screenshot 13](https://user-images.githubusercontent.com/27018255/51744080-fba00280-209e-11e9-83c1-b860cba56615.png)
![screenshot 14](https://user-images.githubusercontent.com/27018255/51744083-fba00280-209e-11e9-9136-4d3ed052c60c.png)

From debug mode on BO in the customers section, when I click on customer with ID 0 I have no error response
![screenshot 16](https://user-images.githubusercontent.com/27018255/51744264-8a148400-209f-11e9-9d08-d0087cdf025f.png)

Here are some log files attached.
I hope they are the right files, because from the link you gave me the directions are not correct to have all the log files

[error.log.20190120.gz](https://github.com/PrestaShop/PrestaShop/files/2795924/error.log.20190120.gz)
[error.log.20190122.gz](https://github.com/PrestaShop/PrestaShop/files/2795925/error.log.20190122.gz)
[error.log.20190123.gz](https://github.com/PrestaShop/PrestaShop/files/2795926/error.log.20190123.gz)
[error.log.20190124.gz](https://github.com/PrestaShop/PrestaShop/files/2795927/error.log.20190124.gz)

From the google chrome console I do not get any java errors
see also https://www.canapath.it/ingrosso-canapa-light

**Comment by khouloudbelguith** [comment] 2019-01-25 14:34
Hi @feyll,

Did you a module named "socialmetadata" in your shop?
Thanks!

**Comment by feyll** [comment] 2019-01-25 15:03
@khouloudbelguith Yes, I have this module installed, but inside another store.
My shop1 is canapath.it and inside its root I created a folder named wholesale-hemp-light and here I have a new installation of prestashop to have a second store for companies. My theme does not support the business, so I had to opt for a new installation in the subfolder.
That said, the social module is installed only in store1, the log files come from the root directory so you can also see store errors1.
Sorry for the confusion, but my english is not good.

**Comment by khouloudbelguith** [comment] 2019-01-25 15:33
@feyll, sorry I need to check this errors "error.log.20190120.gz"?
Thanks!

**Comment by feyll** [comment] 2019-01-25 16:04
@khouloudbelguith I checked, I can not interpret the log file, can you please share with me a link where I show you how to correctly interpret the log file?

I do not understand why these files are missing and I do not understand where the call comes from for these files.
Excuse me but I still have a few debugging skills :(

**Comment by khouloudbelguith** [comment] 2019-01-25 16:08
Hi @feyll,

There are several different log data that you can add as a file to your ticket:

1. Server log:
1.1 Apache: /var/log/apache/apache_error.log
1.2 Nginx: /var/log/nginx/nginx_error.log
1.3 IIS: %SystemDrive%\inetpub\logs\LogFiles
2. PHP error log:
2.1 Apache: /var/log/apache/php_error.log
2.2 Nginx: /var/log/php-fpm/default/error.log
2.3 IIS: %SystemDrive%\inetpub\logs\LogFiles
3. Console log:
3.1 Firefox and Chrome: press Ctrl+Shit+J or Cmd+Shift+J.
3.2 Internet Explorer and Edge: press F12 then go to the Console tab.

If you don't have it, you should ask to your hosting provider.
Thanks!

**Comment by feyll** [comment] 2019-01-26 19:11
@khouloudbelguith Hi :)
I'm waiting for an answer from my provider, maybe I have to add some directives to the .htaccess file to record php errors.

In the meantime I'm waiting for this, I wanted to ask if you have any links to share where it shows how to set up smarty directives for the compilation of customer ID.
I assume there is some error or conflict in the smarty directive for filling out the customer ID value.
Which file can I investigate to check this specific directive?

**Comment by khouloudbelguith** [comment] 2019-01-28 13:50
Hi @feyll,

Ok, Thanks!
In the meantime, could you please check your database schema & compare it with the full schema for 1.7.4.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql
Thanks!

**Comment by feyll** [comment] 2019-01-30 09:39
Hi @khouloudbelguith I could not trace the nature of the problem, the fact is that I saw that the ps_customer table had lost various configurations and id_customer was not set as primary key and had no AUTO_INCREMENT active
I tried in many ways to insert AUTO_INCREMENT but without success, so I took the table ps_customer table of another store of mine and I copied the configuration in the table of my interest.
Now it works, in any case I do not understand how I managed to lose the configuration, very strange.

HOLD configuration ps_customer

`-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: dedi2704.your-server.de
-- Creato il: Gen 30, 2019 alle 09:38
-- Versione del server: 5.7.25-1
-- Versione PHP: 7.1.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `canaph_db`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `ps_customer`
--

CREATE TABLE `ps_customer` (
  `id_customer` int(10) UNSIGNED NOT NULL,
  `id_shop_group` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `id_shop` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `id_gender` int(10) UNSIGNED NOT NULL,
  `id_default_group` int(10) UNSIGNED NOT NULL DEFAULT '1',
  `id_lang` int(10) UNSIGNED DEFAULT NULL,
  `id_risk` int(10) UNSIGNED NOT NULL DEFAULT '1',
  `company` varchar(255) DEFAULT NULL,
  `siret` varchar(14) DEFAULT NULL,
  `ape` varchar(5) DEFAULT NULL,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `passwd` varchar(255) NOT NULL,
  `last_passwd_gen` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `birthday` date DEFAULT NULL,
  `newsletter` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `ip_registration_newsletter` varchar(15) DEFAULT NULL,
  `newsletter_date_add` datetime DEFAULT NULL,
  `optin` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `website` varchar(128) DEFAULT NULL,
  `outstanding_allow_amount` decimal(20,6) NOT NULL DEFAULT '0.000000',
  `show_public_prices` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `max_payment_days` int(10) UNSIGNED NOT NULL DEFAULT '60',
  `secure_key` varchar(32) NOT NULL DEFAULT '-1',
  `note` text,
  `active` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `is_guest` tinyint(1) NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `date_add` datetime NOT NULL,
  `date_upd` datetime NOT NULL,
  `reset_password_token` varchar(40) DEFAULT NULL,
  `reset_password_validity` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dump dei dati per la tabella `ps_customer`
--

INSERT INTO `ps_customer` (`id_customer`, `id_shop_group`, `id_shop`, `id_gender`, `id_default_group`, `id_lang`, `id_risk`, `company`, `siret`, `ape`, `firstname`, `lastname`, `email`, `passwd`, `last_passwd_gen`, `birthday`, `newsletter`, `ip_registration_newsletter`, `newsletter_date_add`, `optin`, `website`, `outstanding_allow_amount`, `show_public_prices`, `max_payment_days`, `secure_key`, `note`, `active`, `is_guest`, `deleted`, `date_add`, `date_upd`, `reset_password_token`, `reset_password_validity`) VALUES


--
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
`
New configuration

``-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: dedi2704.your-server.de
-- Creato il: Gen 30, 2019 alle 09:38
-- Versione del server: 5.7.25-1
-- Versione PHP: 7.1.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `canaph_db`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `ps_customer`
--

CREATE TABLE `ps_customer` (
  `id_customer` int(10) UNSIGNED NOT NULL,
  `id_shop_group` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `id_shop` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `id_gender` int(10) UNSIGNED NOT NULL,
  `id_default_group` int(10) UNSIGNED NOT NULL DEFAULT '1',
  `id_lang` int(10) UNSIGNED DEFAULT NULL,
  `id_risk` int(10) UNSIGNED NOT NULL DEFAULT '1',
  `company` varchar(255) DEFAULT NULL,
  `siret` varchar(14) DEFAULT NULL,
  `ape` varchar(5) DEFAULT NULL,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `passwd` varchar(255) NOT NULL,
  `last_passwd_gen` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `birthday` date DEFAULT NULL,
  `newsletter` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `ip_registration_newsletter` varchar(15) DEFAULT NULL,
  `newsletter_date_add` datetime DEFAULT NULL,
  `optin` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `website` varchar(128) DEFAULT NULL,
  `outstanding_allow_amount` decimal(20,6) NOT NULL DEFAULT '0.000000',
  `show_public_prices` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `max_payment_days` int(10) UNSIGNED NOT NULL DEFAULT '60',
  `secure_key` varchar(32) NOT NULL DEFAULT '-1',
  `note` text,
  `active` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `is_guest` tinyint(1) NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `date_add` datetime NOT NULL,
  `date_upd` datetime NOT NULL,
  `reset_password_token` varchar(40) DEFAULT NULL,
  `reset_password_validity` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dump dei dati per la tabella `ps_customer`
--

INSERT INTO `ps_customer` (`id_customer`, `id_shop_group`, `id_shop`, `id_gender`, `id_default_group`, `id_lang`, `id_risk`, `company`, `siret`, `ape`, `firstname`, `lastname`, `email`, `passwd`, `last_passwd_gen`, `birthday`, `newsletter`, `ip_registration_newsletter`, `newsletter_date_add`, `optin`, `website`, `outstanding_allow_amount`, `show_public_prices`, `max_payment_days`, `secure_key`, `note`, `active`, `is_guest`, `deleted`, `date_add`, `date_upd`, `reset_password_token`, `reset_password_validity`) VALUES


--
**-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `ps_customer`
--
ALTER TABLE `ps_customer`
  ADD PRIMARY KEY (`id_customer`),
  ADD KEY `customer_email` (`email`),
  ADD KEY `customer_login` (`email`,`passwd`),
  ADD KEY `id_customer_passwd` (`id_customer`,`passwd`),
  ADD KEY `id_gender` (`id_gender`),
  ADD KEY `id_shop_group` (`id_shop_group`),
  ADD KEY `id_shop` (`id_shop`,`date_add`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT per la tabella `ps_customer`
--
ALTER TABLE `ps_customer`
  MODIFY `id_customer` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=116;**
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
``

**Comment by khouloudbelguith** [comment] 2019-01-30 10:23
Hi @feyll,

Thanks for your feedback.
In my case with PS1.7.4.2 & PS1.7.5.0, I did not manage to reproduce the issue, all the customers created have an auto-increment id created automatically.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Since it fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-30 10:23 UTC
Labels: Bug, Can't reproduce, Customer, 1.7.4.2
