### ISSUE TITLE
Increase quantity more than availlable stock change prodcut

### ISSUE THREAD

**Issue by Rizzen59** [PrestaShop/PrestaShop#11637] opened 2018-12-06 10:44 UTC
Hi, again :)

I have a bug on product page, when i increase product quantity and this quantity are bigger than stock availlable, the product change. 

**To Reproduce**
1. Go to a product page
2. Click on quantity picker to increase product
3. when quantity are bigger than stock, product change

**Screenshots**
Video with differents articles : https://drive.google.com/file/d/1cZKkOhTP-uKkrsFgF1nQQrRLwhjY0B5a/view

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment] 2018-12-06 11:17
Hi @Rizzen59,

I did not manage to reproduce the issue with PS1.7.4.4 / PS1.7.5.0rc1
I attached a video record
https://drive.google.com/file/d/1sd6v0w4DpX8ntXzHG7V0B_rv1iPWEA3V/view
It could be a custom problem, due to a custom module or your custom theme
Thanks to check & feedback.

**Comment by Rizzen59** [comment] 2018-12-06 14:38
I will regret to buy template T_T,

I will check if i found a solution

**Comment by khouloudbelguith** [comment] 2018-12-06 14:43
@Rizzen59, enabling the debug mode in Shop Parameters => Performance page, could help you to find the exact bug.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-09 16:13
Hi @Rizzen59,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-09 16:13 UTC
Labels: Bug, FO, No change required
