### ISSUE TITLE
Order of products is not the same in Backoffice and Shop

### ISSUE THREAD

**Issue by robi-bobi** [PrestaShop/PrestaShop#15931] opened 2019-10-14 12:37 UTC
**Describe the bug**
Order of products is not the same in Backoffice and Shop

**To Reproduce**

PrestaShop: 1.7.5 AND 1.7.6
In Backoffice: 
Default order by: Position in category, Ascending
I have categories within categories, ex:

catA is within Home
catB and catC are within catA

I want to specify exact product order for catA as well

I did this by reordering products in Backoffice and they show there correctly.
However in the shop the product list does not match what I have in Backoffice.

**Screenshots**
BackOffice:
https://my.pcloud.com/publink/show?code=XZHGY4kZCtqtQ7BatdJPpLPwt33nXzIgRJFX

Shop:
https://my.pcloud.com/publink/show?code=XZKGY4kZnQfjhTiUTP74tAwn7GEGJFOXh1J7

**Additional information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-14 13:11
Hi @robi-bobi,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15291
Partially, it is fixed with this: https://github.com/PrestaShop/PrestaShop/pull/14879 which fixes this issue: https://github.com/PrestaShop/PrestaShop/issues/14616
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-14 13:11
Duplicate of #15291

**Closed as completed by khouloudbelguith** 2019-10-14 13:11 UTC
Labels: Duplicate
