### ISSUE TITLE
Faceted search check boxes issue: ticks and x's not showing

### ISSUE THREAD

**Issue by symphonytech111** [PrestaShop/PrestaShop#16441] opened 2019-11-15 21:09 UTC
Since upgrading the Faceted Search module in Prestashop, the little ticks in the check boxes are not displayed. Furthermore, the little crosses next to the summary of selected filters (allowing them to be de-selected) is also not showing.

This means that, whilst the faceted filtering is working, it is very confusing to identify what filters are active, and how to de-select them.

Depending on the browser, it either shows a little grey box, or sometimes nothing at all.

PS 1.7.4.3
Php 7.3.11

![Screenshot_20191115-210729_Firefox](https://user-images.githubusercontent.com/57814453/68975744-feb1de00-07eb-11ea-8d53-2686aec22803.jpg)

![Screenshot_20191115-210818_Firefox](https://user-images.githubusercontent.com/57814453/68975782-15f0cb80-07ec-11ea-90aa-8e93498a9bb5.jpg)

**Comment by khouloudbelguith** [comment] 2019-11-18 08:03
Hi @symphonytech111,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.
In my case, I did not manage to reproduce the issue with PS1.7.6.1 & ps_facetedsearch v3.4.0.
![image](https://user-images.githubusercontent.com/16067358/69034772-4a2ddd00-09e2-11ea-9c7a-11ea738ae270.png)

Thanks to downgrade your PHP version, check & feedback.

**Comment by symphonytech111** [comment] 2019-11-18 21:09
Many thanks for your reply.

 

I have downgraded to 7.2; the issue remains.

 

Best wishes,


Dave

**Comment by symphonytech111** [comment] 2019-11-18 21:25
You can also see the issue in action at www.symphonymusic.co.uk

As earlier, I have downgraded to php 7.2 and the issue remains

**Comment by khouloudbelguith** [comment] 2019-11-19 08:15
@symphonytech111, you are not using the default theme Classic provided by PrestaShop.
Have you tried to contact the theme author about this issue?

Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-19 07:46
Hi @symphonytech111,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-19 07:46 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.4.3
