### ISSUE TITLE
Cannot enter in the products section nor in the Modules Mannager

### ISSUE THREAD

**Issue by CondeCrapula** [PrestaShop/PrestaShop#15997] opened 2019-10-17 08:00 UTC
I cannot access within the products section nor in the Modules Mannager section.

When I click on it, I get the following message:

Oops! An Error Occurred
The server returned to "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment] 2019-10-17 08:42
Hi @CondeCrapula,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-18 07:38
Hi @CondeCrapula,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-18 07:38 UTC
Labels: Bug, No change required, Module manager
