### ISSUE TITLE
[BO] Bad display of header itmes in medium screen

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27385] opened 2022-01-18 12:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

- **768px < width < 1039px**
The header items (quick access, search box, shop name, notification icon) in legacy theme pages are misaligned vertically at medium screen width. => **`Regression on 1.7.8.0`**

![image](https://user-images.githubusercontent.com/23308427/150107741-dd1aa23e-f2b7-4a62-88f4-45f0cc6cb037.png)

- **1024px < width < 1039px**
The header title and the shop version are misaligned => **`reproduced on 1.7.7.8`**
The Order page is not full width => **`reproduced on 1.7.7.8`**

![image](https://user-images.githubusercontent.com/23308427/150111538-ac67ca8a-ef59-4904-b10a-afbc93f3d8e9.png)

### Expected behavior
Header items center align vertically and header height as like as new theme.

![Screenshot 2022-01-18 at 12-14-03 Dashboard • sidebar](https://user-images.githubusercontent.com/85633460/149935838-ea561ec7-7c5a-4302-af80-94918e7b5d20.png)

### Steps to reproduce

Go to BO > Dashboard

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by marwachelly** [comment] 2022-01-18 16:14
Hello,
Thank you for your report. I was able to reproduce the issue with PrestaShop version 1.7.8.0 .
https://watch.screencastify.com/v/kyjOq5HIz61yfElagzrZ
The issue is not reproducible with PS 1.7.7.8 it is a regression.
I'll add this to the debug backlog so that it's fixed. Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider hiring a specialist to help you.

If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks,

**Comment by Progi1984** [comment] 2022-04-04 10:39
Fixed by @NeOMakinG in #27615 and tested by @HanaRebaiQA

**Closed as completed by Progi1984** 2022-04-04 10:39 UTC
Labels: Bug, Trivial, BO, Regression, Fixed, Front-end, PR available, Responsive, 1.7.8.0, Verified
