### ISSUE TITLE
Prestashop 1.7.6 module menù entry miss for manage

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#15386] opened 2019-09-03 13:52 UTC
**Describe the bug**
Left menù Module > Manage link point to updates url.

Updates module page has no entry on top menù for manage.

Result impossible to manage module without direct url access.

![image](https://user-images.githubusercontent.com/24798703/64178943-99905280-ce62-11e9-843e-8115151c53f5.png)

Result in this url called:
/index.php/improve/modules/updates

And this page load

![image](https://user-images.githubusercontent.com/24798703/64178987-a90f9b80-ce62-11e9-9e85-a1c0c6239003.png)

Miss the top menù "manage"

![image](https://user-images.githubusercontent.com/24798703/64179005-b167d680-ce62-11e9-95a9-f18a88b0074f.png)

Using direct url access, the manage page complete miss the TOP menù:

/index.php/improve/modules/manage

![image](https://user-images.githubusercontent.com/24798703/64179058-c93f5a80-ce62-11e9-80c9-8b5d08d27068.png)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-09-03 13:59
Hi @matteolavaggi,

I did not manage to reproduce the issue with PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/64179664-74e4ac80-ce5b-11e9-85dc-9067869de37f.png)

What is the exact version PS1.7.6 did you use?
Is it a fresh installation or an upgrade from a previous version?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matteolavaggi** [comment] 2019-09-03 14:07
PS 1.7.6 (the exact one i've write), its a fresh installation. There is no php error entry on log and the debug mode enabled show this page:

![image](https://user-images.githubusercontent.com/24798703/64180352-ed9c3680-ce64-11e9-918a-49b9fe343b82.png)

**Comment by khouloudbelguith** [comment] 2019-09-03 14:13
@matteolavaggi, is it PS1.7.6.1 or PS1.7.6.0?
What is the exact language/country did you used during the install?

Thanks!

**Comment by matteolavaggi** [comment] 2019-09-03 14:49
ita/ita

**Comment by khouloudbelguith** [comment] 2019-09-03 14:53
@matteolavaggi, is it 1.7.6.1 or 1.7.6.0?, I will try to install a shop withis settings.
Thanks!

**Comment by matteolavaggi** [comment] 2019-09-03 15:10
1.7.6.0

**Comment by khouloudbelguith** [comment] 2019-09-03 15:55
@matteolavaggi, in my case, it is OK
https://drive.google.com/file/d/1UBwrwMs4ZfhFd3c0szC5KOLegjcfUk9h/view
Did you installed specific module before this issue occurs?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-03 08:16
Hi @matteolavaggi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-03 08:16 UTC
Labels: Bug, BO, No change required, Module manager
