### ISSUE TITLE
[FO][HOMEPAGE] Error with productcomment module

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20839] opened 2020-09-03 09:21 UTC
#### Describe the bug

On FO, go to "mystore" with inspector open, you will see an error 500

#### Expected behavior

Productcomment module working fine

#### Steps to Reproduce

1. Click on "mystore" with your inspector open
2. See error

**Screenshots**

<img width="1421" alt="Capture d’écran 2020-09-03 à 11 20 21" src="https://user-images.githubusercontent.com/69145330/92096677-75e64c00-edd7-11ea-927d-0a25d809304d.png">

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-09-03 09:26
Same issue in the develop branch
![image](https://user-images.githubusercontent.com/16067358/92097423-5865b200-edd8-11ea-84f5-3129ad2c7d3e.png)

**Comment by atomiix** [comment] 2021-04-29 16:03
@khouloudbelguith I'm unable to reproduce this issue, can you check if you still can reproduce it on your side?

**Comment by khouloudbelguith** [comment] 2021-05-05 14:53
Hi @atomiix,

Sorry for the delay.
Yes, I did not manage to reproduce the issue with the 178x branch & the develop branch using the `productcomments` module v4.2.1.
https://drive.google.com/file/d/1Z_Sd0lkaqhzOSMps8i_AznZrW2uIIahx/view?usp=sharing
I close the issue.

Thank you!

**Closed as completed by khouloudbelguith** 2021-05-05 14:53 UTC
Labels: Bug, develop, Minor, FO, Can't reproduce, Regression, Productcomments
