### ISSUE TITLE
htmlspecialchars expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by ZamperSPA** [PrestaShop/PrestaShop#16929] opened 2019-12-26 14:45 UTC
update the  module: Faceted Search and website stops responding

**To Reproduce**
1. Update module faceted from 3.0.6 to 3.4 
2. open any category

**Screenshots**
![imagen](https://user-images.githubusercontent.com/40174130/71479111-e57c5400-27d1-11ea-8df6-b03e3cdf67b9.png)
Log: [https://pastebin.com/BiamYGyC](https://pastebin.com/BiamYGyC)
![imagen](https://user-images.githubusercontent.com/40174130/71478440-6cc7c880-27ce-11ea-9445-bcb4e9247553.png)

**Additional information**

PrestaShop version: 1.7.6.2
PHP version: 7.2.26

**Comment by khouloudbelguith** [comment] 2019-12-26 16:51
Hi @ZamperSPA,

I did not manage to reproduce the issue with PS1.7.6.2& ps_facetedsearch v3.4.0.
I attached a screen record
https://drive.google.com/file/d/1o22P1iBW_crTHD2nsIdhVudm7ypDM2mQ/view
In the ps_facetedesarch configuration page, could you please try to click on the "Index all missing prices" & "Rebuild entire price index" & "Clear cache" buttons, check & feedback.

**Comment by khouloudbelguith** [comment] 2020-01-27 08:03
Hi @ZamperSPA,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-27 08:03 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.6.2

**Comment by simobenso** [comment] 2020-06-14 20:26
Hello @khouloudbelguith, I'm facing the same error : 

The error concerns the product page : 
`PHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in var/cache/prod/smarty/compile/layouts_layout_left_column_tpl/84/9f/0d/849f0d8a7512ed672487a06a045d302b9e5e7c31_2.file.product-style-02.tpl.php on line 40'`

Here is the concerned line on the compiled template : 
`<meta itemprop="brand" content="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['product']->value['manufacturer_name'], ENT_QUOTES, 'UTF-8');?>`

PS version : 1.7.6.4
PHP version : 7.3
