### ISSUE TITLE
Translation problem, does not translate

### ISSUE THREAD

**Issue by yenbrand** [PrestaShop/PrestaShop#17854] opened 2020-02-26 17:48 UTC
Hello, how many months can not fix, me there are several problems with the translation there are a few words that do not appear in the admin panel, there are a few words that I will write the translation, and I save. when I refresh the page, the translation will disappear

I turned off English , my site default language is Armenian, other language Russian all languages ​​have the same problem

Shop > Theme > Actions > "edit" ,
Shop > Theme > Actions > "Back to login" ,

I added them through phpmyadmin ps_translation  but through the admin panel, doesn't the change

and there are modules their translation does not change but I translated them all, i cleared the all cache. 

PrestaShop 1.7.6.3
PHP version 7.3.13
Server - Linux / Apache

![Screenshot_2](https://user-images.githubusercontent.com/61514250/75375831-592d0100-58e8-11ea-8ef6-8c29b88241e5.png)
![Screenshot_3](https://user-images.githubusercontent.com/61514250/75371803-dce2ef80-58e0-11ea-8a34-0986af23f1b0.png)
![Screenshot_4](https://user-images.githubusercontent.com/61514250/75371804-de141c80-58e0-11ea-9bc0-62fd174ad1d1.png)
![Screenshot_5](https://user-images.githubusercontent.com/61514250/75371814-e2d8d080-58e0-11ea-8d1b-26bb32135fd2.png)
![Screenshot_1](https://user-images.githubusercontent.com/61514250/75371863-f6843700-58e0-11ea-958c-be8bcb1bf3eb.png)

**Comment by khouloudbelguith** [comment] 2020-02-27 08:10
Hi @yenbrand,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check & feedback.

**Comment by yenbrand** [comment] 2020-02-27 17:46
i change php version to 7.2 but problems remain   in default theme ShopFormsHelp  other places did not check
 
![Screenshot_1](https://user-images.githubusercontent.com/61514250/75470508-39f6a800-59aa-11ea-8b05-7d81a237de25.png)

ShopPdf   and please pay attention to absent -3
![Screenshot_2](https://user-images.githubusercontent.com/61514250/75474120-dc655a00-59af-11ea-81e3-2e4e189afe27.png)

**Comment by Gipielle** [comment] 2020-02-27 22:42
Same problem with prestashop  1.7.6.2 and PHP 7.2

**Comment by yenbrand** [comment] 2020-02-28 05:07
What should I do? how to fix these problems

**Comment by khouloudbelguith** [comment] 2020-02-28 11:38
@yenbrand,

>Shop > Theme > Actions > "edit" ,

![image](https://user-images.githubusercontent.com/16067358/75545296-356fd500-5a26-11ea-9b01-0e1df4e84017.png)
Shop > Theme > Actions > "Back to login" ,

![image](https://user-images.githubusercontent.com/16067358/75545320-47517800-5a26-11ea-8a2e-4c05aef10637.png)

=> the issue is "Translation BO doesn't handle properly same translation with different cases" => fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/15511 in the PS1.7.7.0.

About other expressions, I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1i3x1__WfBoDXIeV9VXFQYOqapL7aJhvJ/view

Thanks to check & feedback.

**Comment by yenbrand** [comment] 2020-02-28 12:39
please  watch the video.  if necessary I can give access to my site so you can see the mistakes yourself
https://files.fm/u/cr94rgsb#/view/bandicam+2020-02-28+16-29-25-808.mp4;play

**Comment by khouloudbelguith** [comment] 2020-02-28 13:56
Hi @yenbrand,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16168
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-28 13:56
Duplicate of #16168

**Closed as completed by khouloudbelguith** 2020-02-28 13:56 UTC
Labels: Bug, BO, Duplicate, Translations, Modules & Themes, 1.7.6.3

**Comment by yenbrand** [comment] 2020-02-28 18:31
How to solve this problem? in  ShopPdf,ShopThemeCatalog also not saved as on video can you tell me how can I fix this 

ShopPdf
------
Total (Tax excl.)
Order date

ShopThemeCatalog
------
Including %amount% for ecotax

**Comment by khouloudbelguith** [comment] 2020-03-02 13:44
@yenbrand, sorry this issue not fixed yet.
Please follow: https://github.com/PrestaShop/PrestaShop/issues/16168

**Comment by LuigiMdg** [comment] 2023-07-06 17:59
3 years later, the problem persists.
