### ISSUE TITLE
Theme classic code discount form not showing

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#16950] opened 2019-12-29 09:48 UTC
**Describe the bug**
After an upgrade to 1.7.6.2 with classic theme update activated (autoupgrade module), on the frontend cart view, link to add a discount code is not working anymore. The form is not showing.

**To Reproduce**
1. Go to cart view (add a product and a code discount before)
2. Click on "add a discount code"
3. Nothing happend

Seems that some code has been removed :
Before update : 
`<a class="collapse-button promo-code-button collapsed" data-toggle="collapse" href="#promo-code" aria-expanded="false" aria-controls="promo-code">
            Vous avez un code promo ?
          </a>`
after : 
`<p class="promo-code-button display-promo">
          <a class="collapse-button" href="#promo-code">
            Vous avez un code promo ?
          </a>
        </p>`

Why ????

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-12-30 11:16
Hi @rflorent,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.2 fresh install & PS1.7.6.2 after an upgrade from PS1.7.5.2 using the 1-click upgrade v4.10.0. (Upgrade the default theme is enabled)
https://drive.google.com/file/d/1Ke7D5Rk8jnJvV9n8Rs7EMe3QVsL-fJVI/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source): old version before the upgrade
 - What is the exact version of the 1-click upgrade did you use?
 - Have you any errors during the upgrade?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-29 07:40
Hi @rflorent,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2020-01-29 07:40 UTC
Labels: Bug, FO, Discounts, Autoupgrade, No change required, ps_shoppingcart, Shopping carts FO, 1.7.6.2
