### ISSUE TITLE
Unable to update Prestashop to minor and major versions - "error " errorThrown:" " jqXHR: " undefined"

### ISSUE THREAD

**Issue by MatthFo** [PrestaShop/PrestaShop#35760] opened 2024-03-27 15:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

For some time it has been impossible to update stores (v1.7 to v8 and v8.1.x to v8.1.x ) with the "1-Click Upgrade" module v5.0.1.

The error messages displayed during the attempts are :
- [Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: " undefined"
- **OR** [Ajax / Server Error for action unzip] textStatus: "error " errorThrown:" " jqXHR: " undefined"
- **OR** [Ajax / Server Error for action _**XXX**_] textStatus: "error " errorThrown:" " jqXHR: " undefined"

There are no error logs in "var/logs/*" and "admin/autoupgrade/tmp/log.txt" and no server-side error logs. The requests stop suddenly (all requests have the http code 200).

Last logs of the last attempt in /admin/autoupgrade/tmp/log.txt :
[2024-03-27 15:10:37] modules/colissimo/lib/xml/track.xml added to archive. 37074 files left.
[2024-03-27 15:10:37] modules/colissimo/logo.gif added to archive. 37073 files left.
[2024-03-27 15:10:37] modules/colissimo/logo.png added to archive. 37072 files left.
[2024-03-27 15:10:37] modules/colissimo/logs/xxxx.log added to archive. 37071 files left.

According to the hosting service there are no server-side configuration errors.

max_execution_time : 165s

### Expected behavior

Upgrade to latest minor and major Prestashop versions.

### Steps to reproduce

- All modules are updated
- Maintenance mode
- Disable and clear cache
- Disable all overrides
- Disable non-native modules
- Disable "CCC" in the "performance" tab / Apache optimization
- Disable child theme
- Restart SQL server on the host side + maintenance mode on all other stores
- Without autoupgrade backup images / files / databases
- Minor and major channel

### PrestaShop version(s) where the bug happened

17.8.11 AND 8.1.2

### PHP version(s) where the bug happened

7.4 AND 8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1

**Comment by AureRita** [comment] 2024-03-28 16:21
Hi @MatthFo 

Thank you for your report, Despite my effort I can't reproduce it as you can see : 

[recording(161).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/8049d20a-0117-4f32-b07d-99b1ee9bfbaf)

Did I miss something ? 

Can you provide us a screen or a video about your issue ? 

Waiting for feedback

**Comment by MatthFo** [comment] 2024-04-05 08:47
Thank you for your response and sorry for the delay.

Yes that's right. I just carried out a test on a new installation and it worked correctly.
I will test and record on the store that is causing the problem.

Regards

**Comment by AureRita** [comment] 2024-04-08 15:20
Thank you for your answer, waiting for your record

**Comment by florine2623** [comment] 2024-04-22 09:36
friendly reminder @MatthFo

**Comment by MatthFo** [comment] 2024-04-24 20:23
Sorry for the late response.

I successfully updated 8.1.2 to 8.1.5 on a fresh install without any issues.

So I made the updates on the shops (8.1.2 to 8.1.5 and 1.7.8.11 to 8.1.5), without issues either.

For the last store (1.7.8.11), when attempting a backup I noticed disconnections (through SFTP and SSH). Could the problem come from there ? I'm waiting for a reply from my web hosting service.

Regards.

**Comment by paulnoelcholot** [comment] 2024-05-02 08:20
Hello @MatthFo,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-05-02 08:20 UTC
Labels: Bug, BO, Can't reproduce, Autoupgrade, 1.7.8.x, Module

**Comment by kenjapy** [comment] 2024-10-07 11:22
Good morning !
I tried to follow the steps described but I still can't update...
![presta](https://github.com/user-attachments/assets/508fe7d1-6791-4419-b393-2a8f689ecfab)
