### ISSUE TITLE
[BO] Bad display of the Edit quantity field in Stock page

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26796] opened 2021-11-29 13:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is a CSS rule for replacing native up and down arrows in Edit quantity field. But the native arrows doesn't hide and when user hover mouse pointer upon field, both of them will be shown.

**Blur mode:**
<img src="https://user-images.githubusercontent.com/85633460/143879458-edc9f3e1-0e80-4f7e-a1ed-874f7ddb87f7.png" width="250"/>

**Hover mode:**
<img src="https://user-images.githubusercontent.com/85633460/143879497-8c5d72dd-58f8-44a6-bade-cb367781a7c2.png" width="250"/>

### Expected behavior

**Blur mode:**
<img src="https://user-images.githubusercontent.com/85633460/143879565-8a5cec80-eafe-46de-bbf9-45b123255167.png" width="250"/>

**Hover mode:**
<img src="https://user-images.githubusercontent.com/85633460/143879593-6e5f756b-0ea0-4e89-b3af-5bc1f74ca68c.png" width="250"/>

### Steps to reproduce

Go to BO > Catalog > Stock

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment] 2021-11-29 15:59
Hello @mparvazi 

I didn't manage to reproduce the issue with develop (PS8.0.0), see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/143900849-5c893e82-3a70-490f-9b6b-dd9ff7907735.png)

Please check and feedback.
Thanks!

**Comment by mparvazi** [comment] 2021-11-29 16:01
Hello @hibatallahAouadni 

I tested with Firefox.

**Comment by hibatallahAouadni** [comment] 2021-11-30 18:02
Hello @mparvazi 

Yes! I reproduce the issue with PS1.7.8.0, PS1.7.8.1 and develop only with Firefox, see the attached screen record below:

https://www.awesomescreenshot.com/video/6227289?key=57944246f7fb2b369a379b1721d8cd2f

It's a regression on 1.7.8.0! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.
If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mparvazi** [comment] 2021-11-30 18:15
@hibatallahAouadni 

Just happens in Firefox desktop!
I tested in mobile with Firefox, Safari, Chrome and there was no problem.

As you tagged, this is really Trivial :)

**Comment by Progi1984** [comment] 2022-01-06 16:35
@NeOMakinG Could you check this issue ?

**Comment by Hlavtox** [comment] 2022-01-07 12:52
@NeOMakinG @mparvazi Cannot we dump the aftermarket spinner and just use pure HTML number input? It will be better adapted to every device/OS and unified with the system.

**Comment by mparvazi** [comment] 2022-01-07 12:59
@Hlavtox 
I didn't know about that trick, can you please make an example?

**Comment by Hlavtox** [comment] 2022-01-07 13:03
It's no trick, but just do simple `<input type="number">`. Why add another arrows and try to hide the originals by CSS hacks?

https://codepen.io/hlavtox/pen/dyVjdLx

**Comment by NeOMakinG** [comment] 2022-01-07 13:10
@jolelievre What's the reason behind the number component?

**Comment by mparvazi** [comment] 2022-01-07 13:36
@Hlavtox

IMO the purpose of using CSS to redesign elements is to have the same appearance across devices/OS. 
As like as Checkbox, Button, ...

In Firefox spin buttons will be displayed always (Blur, Focus, Hover)
In Chrome just will be displayed in Focus and Hover.

**Comment by NeOMakinG** [comment] 2022-01-07 13:38
Yeah but I think it would be more maintainable to have default component used on such fields, without bugs, but maybe there is another reason behind this component that we aren't aware of, this is why I asked to @jolelievre

**Comment by mparvazi** [comment] 2022-01-07 13:52
OK, as a tip:
Safari doesn't display spin buttons by default, forces the user to enter number manually.

**Comment by jolelievre** [comment] 2022-01-07 14:00
I don't know it's on the stock page I didn't work on this one

That said we encountered a similar bug with the delta quantity input on the new product page (only the one in the list since it's the only one which has this submit button). All I did was adding an offset to the arrows so that they are not displayed behind the button.

https://github.com/PrestaShop/PrestaShop/blob/542a991f647372fb061195b32e3b2d313b06ccde/admin-dev/themes/new-theme/scss/components/_submittable_input.scss#L37-l41

Using an `<input type="number" />` here makes sense since it's an integer, and **it is what we are using** in the product page.

But it seems like in stock Vue component there is a custom `ps-number` component, I guess the problem comes from this one. Maybe at the time it as not handled natively, or they didn't know how to use it. You could replace it with a native input type, you just need to specify `step=1` I believe.

**Comment by Progi1984** [comment] 2022-01-27 10:21
Fixed by @mparvazi in # 27257 & validated by @florine2623

**Closed as completed by Progi1984** 2022-01-27 10:21 UTC
Labels: Bug, Trivial, BO, Stocks, Regression, Fixed, Front-end, PR available, 1.7.8.0, Verified
