### ISSUE TITLE
1.7.7.2 - Specific Carriers for each product leads to wrong behavior at check out

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#23738] opened 2021-03-23 14:32 UTC
To reproduce:

If we add in cart (order is important):

Product 1 (which has an available carrier Carrier1)
Product 2 (which has an available carrier Carrier2, Carrier3, Carrier 4)
=> In the order checkout STEP 3 it only shows 1 carrier (example: Carrier2) but cart still has 2 products.
It allows to conclude the order and make the payment. At the backoffice you'll see a split order.

If you invert the order where you insert the product in cart like:

Product 2 (which has an available carrier Carrier2, Carrier3, Carrier 4)
Product 1 (which has an available carrier Carrier1)
=> In the order checkout STEP 3 it only shows 1 carrier without name but cart still has 2 products.
It allows to conclude the order and make the payment. At the backoffice you'll see a split order.

This is very severe because if you don't allow Product1 for a specific country, you still end up the order and the customer makes the payment.

Don't know if it's related with #9594

**Comment by hibatallahAouadni** [comment] 2021-03-23 16:49
Hello @seederp2p 

As you mentioned :wink: it's not just related it's the same issue.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9594. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: If you think you fixed it, please do send us a pull request!

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-23 16:49
Duplicate of #9594

**Closed as completed by hibatallahAouadni** 2021-03-23 16:49 UTC
Labels: Duplicate
