### ISSUE TITLE
Redirection problem in Prestashop version 1.7.5.2 - for color attributes

### ISSUE THREAD

**Issue by jitendra-cygnet** [PrestaShop/PrestaShop#15149] opened 2019-08-19 05:50 UTC
**Describe the bug**

From product listing page - if you click on any of color it will automatically redirect to default. but if you can do inspect element or right click and open link in new tab  then it goes to exact color link. so can you please tell us solution for same

it makes an ajax call to /cart and then made a page refresh with ajax by requesting the current page with quantity_wanted=1. Although in core.js the URL contained a hash tag followed by the attribute value (blabla.html?#/33-quantity_weight-100_grams), the browser has actually stripped off the hash. I thought it was useful but it wasn't. Then I noticed that when I accessed a product via the URL

If id_product_attribute is not the default attribute, then the product controller used canonical Redirection to redirect back to the URL with the default id_product_attribute. That was the issue here, it did the same thing with an ajax call. Hence when you change to a non default attribute value, it redirects back to a default value and returns the data for that default attribute.

Look like its bug in controller of this version. please check and suggest solutions

**To Reproduce**
1. Go to '...' https://bgirl-dev.visibilis.co.uk/34-new-arrivals
2. Click on '....' product color attributes
3. next '....' - it goes to default color attributes url every time instead of selected color 
4. Bug - if you can check in inspect element, controller or ajax event or right click on any attribute and open link it will work fine. but on same page it's redirecting to default color combination url

**Screenshots**
https://ibb.co/KyhT5CM

**Additional information**
PrestaShop version: 1.7.5.2

PHP version: 7.2.21

Server information Linux #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64

Server software version: Apache

Memory limit: 1536M

Max execution time: 3600

Upload Max File size: 1024M

Other Details

MySQL version: 5.7.27

Tables prefix: ps_

MySQL engine: InnoDB

MySQL driver: DbPDO

**Comment by khouloudbelguith** [comment] 2019-08-19 10:02
Hi @jitendra-cygnet,

I did not manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2.
I used the default theme Classic
I attached a screen record
https://drive.google.com/file/d/1Yr3hhJjCC53MO7LSXi1fRyTYEllXUOR9/view
Have you tried to contact the theme author about this issue?
Thanks to check with them & feedback.

**Comment by jitendra-cygnet** [comment] 2019-08-19 10:12
@khouloudbelguith  Thanks for your try, regarding theme i am using default theme with modification in design

**Comment by khouloudbelguith** [comment] 2019-08-19 10:15
@jitendra-cygnet, those modifications are not related to your issue?

Thanks!

**Comment by jitendra-cygnet** [comment] 2019-08-19 10:35
@khouloudbelguith nope we did modification in design perspective only, you can check my above comment its completely functional error. There is some ajax call is taking place and after that its redirecting to default combination.
Weird thing is, in product details page if you take a look on selected for you section and click on color combination over there then its working fine and redirecting to correct combination. You can review it on following link : https://bgirl-dev.visibilis.co.uk/scarves/9589-30067-tie-dye-with-foil-spots-scarf.html#/160-size-one_size/167-ratio-1_piece/203-colour-coral
So my clear doubt on product listing page controller and ajax call.

**Comment by khouloudbelguith** [comment] 2019-08-19 10:41
@jitendra-cygnet, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

PS: you can check in our demo shop, it is OK: http://sordid-toy.demo-ms.production.prestashop.com/en/

**Comment by jitendra-cygnet** [comment] 2019-08-19 10:54
hi @khouloudbelguith 

[todays-errro-log.txt](https://github.com/PrestaShop/PrestaShop/files/3515468/todays-errro-log.txt)

Please check today's error log.

Thanks

**Comment by khouloudbelguith** [comment] 2019-08-19 11:18
@jitendra-cygnet, in this log file, you have some errors related to the cache.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Also, you have tis error
>[Mon Aug 19 10:20:14.921021 2019] [cgi:error] [pid 125104] [client 118.185.107.222:40216] AH01215:   thrown in /home/bgirldev/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180: /usr/local/cpanel/cgi-sys/ea-php72,

It is related to your server.

Thanks to check with your host & feedback.

**Comment by jitendra-cygnet** [comment] 2019-08-19 11:25
Thanks for your effort :)

I will remove cache and contact hosting provider and then get back to you

**Comment by khouloudbelguith** [comment] 2019-08-19 11:30
@jitendra-cygnet, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-09-18 07:35
Hi @jitendra-cygnet,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-18 07:35 UTC
Labels: FO, Combinations, No change required, 1.7.5.2

**Comment by LuigiMdg** [comment] 2020-12-10 16:55
I've the same problem, I don't have classic theme, my version is 1.7.6.2.
I've tryed this on 2 servers.
The attributes products links are corrects but when the page is loading PrestaShop will redirect to default attribute's url with js or controller (route)..!
Please solve this problem, this is a very common bug in version 1.7

Best Regards,
Luigi Donato
