### ISSUE TITLE
Link widget duplication of pages

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#11615] opened 2018-12-05 08:03 UTC
Please refer to screenshot below. Not sure how to reproduce this issue as it just appeared. All I can say is that I have multistore on with 3 stores. I made some amendments to the pages associated with each store separately. I also created my own page.

![image](https://user-images.githubusercontent.com/26452178/49498760-8cb7e180-f885-11e8-8989-d89d23b0556a.png)

**Additional information**
PrestaShop version: 1.7.4.4

**Comment by nrcjea001** [comment] 2018-12-05 08:11
Basically this results in 3 by 3 = 9 duplications of each page.

Tried resetting the link widget module and it didn't help

**Comment by khouloudbelguith** [comment] 2018-12-05 08:19
Hi @nrcjea001,

The issue when I enable multistore, whatever if I select a specific shop or "all shop", I have as many links as shops and as many "Content pages" is solved by https://github.com/PrestaShop/ps_linklist/pull/48
A second related issue still not fixed yet, but it is added to our bug roadmap.
Your ticket is a duplicate of #9795
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-05 08:20
Duplicate of #9795

**Closed as completed by khouloudbelguith** 2018-12-05 08:19 UTC
Labels: Duplicate
