### ISSUE TITLE
Media server is not working for CSS and Javascript

### ISSUE THREAD

**Issue by ets-soft** [PrestaShop/PrestaShop#18170] opened 2020-03-17 04:25 UTC
#### Describe the bug

Media server option is not to be fully working on Prestashop 1.7. I entered CDN domain  but it only works for images not CSS or Javasscript. The URL of css and javascript files remain original domain (not replaced by CND domain) even when I have turned on CSS (minification)

#### Expected behavior

CND domain should replace original domain when the CDN domain is entered (via media server input fields)

#### Steps to Reproduce

1. Go to 'Advanced parameters/Performance/Media servers (use only with CCC)'
2. Enter media server domains
3.  Go to BO and see CSS and Javascript URL, they don't change to the CND domain

#### Additional information

* PrestaShop version: 1.7

**Comment by khouloudbelguith** [comment] 2020-03-17 08:19
Hi @ets-soft,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16180 to fix the issue.
It is fixed in the next version PS1.7.7.0.
Your ticket is a duplicate of #9890
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-17 08:20
Duplicate of #9890

**Closed as completed by khouloudbelguith** 2020-03-17 08:19 UTC
Labels: Duplicate

**Comment by ets-soft** [comment] 2020-03-20 10:31
That's ok. you can closed this.
thanks
