### ISSUE TITLE
Prestashop don't work without Internet

### ISSUE THREAD

**Issue by ricardopxlcl** [PrestaShop/PrestaShop#29218] opened 2022-08-01 16:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm using Prestashop 1.7.6.9, how a POS (Point of Sale). In this location i don't have Internet available and I can't  use Prestashop without Internet. Because when i need Generate Caché, the system die.

- ¿How Can I use Prestashop without Internet?
- I disabled/delete all modules and the problem continue.
- I don't have overrides.

Screenshot error 503, for timeout php.
https://tinyurl.com/29qnasr3

Error log:
`[Mon Aug 01 10:45:13.610675 2022] [proxy_fcgi:error] [pid 20996:tid 139951442228992] (70007)The timeout specified has expired: [client 172.XX.XXX.XX:64126] AH01075: Error dispatching request to :`

Access log:
```
172.XX.XXX.XX - - [01/Aug/2022:10:44:22 -0400] "GET /admin-bt/index.php?controller=AdminLogin&token=c40ac4f20d5b5a74ac33a61f26e1e93e HTTP/1.1" 503 299
172.XX.XXX.XX - - [01/Aug/2022:10:44:43 -0400] "GET /admin-bt/index.php?controller=AdminLogin&token=c40ac4f20d5b5a74ac33a61f26e1e93e HTTP/1.1" 503 299
```

I think the problem is in generation of Cache, if I connect the POS to Internet, work correctly. After delete caché, die.

### Expected behavior

I would like Prestashop work witout Internet.

### Steps to reproduce

1. Install prestashop
2. Configure Prestashop
3. Disconect Internet
4. Delete caché
5. Backoffices is die

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2.34

**Comment by hibatallahAouadni** [comment] 2022-08-01 17:23
Hello @ricardopxlcl 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27541. 
To be informed when it's fixed, please subscribe to this issue #26427.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-01 17:23
Duplicate of #27541

**Closed as completed by hibatallahAouadni** 2022-08-01 17:23 UTC
Labels: Bug, Duplicate, Invalid

**Comment by NeOMakinG** [comment] 2022-08-02 07:14
@hibatallahAouadni I guess this is a real problem unrelated to #27541

**Comment by matks** [comment] 2022-08-02 07:19
Hello, I am sorry but I think using PrestaShop without internet is simply impossible today 🤔 . For me this is not a bug: it is a simple choice.

To make prestashop be able to run without Internet would require multiple improvements. These improvements mean investing time and money. Is this time money well invested when 99.99% users have a Internet connection? Moreover PrestaShop is supposed to be a `e-commerce` platform: something done on Internet, not a POS 😅

**Comment by ricardopxlcl** [comment] 2022-08-03 17:01
@matks because Prestashop is a excelente CMS :) Know you how to prevent regenerate core cache ? Or disabled regenerate core cache? Or can disabled cache?

Regards
