### ISSUE TITLE
Error if an Order State is missing

### ISSUE THREAD

**Issue by dcaciula** [PrestaShop/PrestaShop#27342] opened 2022-01-13 11:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you have orders with a deleted Order State, you cannot access Order details in BO.
![image](https://user-images.githubusercontent.com/86823567/149319111-28645775-5026-4b20-b4ff-b58ae531fc86.png)

### Steps to reproduce

1. Go to Orders and click on Order in BO
2. If that Order have a deleted Order State, an error will appear.

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment] 2022-01-13 12:29
Hello @dcaciula 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19098. 
And it's already fixed with this PS1780, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/149330201-dcd4859f-7e1e-4bf0-b67f-84fa86c21fa9.png)

Even on develop, I didn't reproduce the issue, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/149505348-bb9bbaae-ce33-4c64-bb0d-6937bb08ca52.png)

PS: please downgrade your PHP version to 7.3 cause PS1771 is not compatible with PHP8.0 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-13 12:29
Duplicate of #19098

**Closed as completed by hibatallahAouadni** 2022-01-13 12:29 UTC
Labels: Bug, Duplicate, PR available, Invalid
