### ISSUE TITLE
Manual upgrade - 1.7.8.2 -> 1.7.8.3 - action result="error" id="32"

### ISSUE THREAD

**Issue by bhocde** [PrestaShop/PrestaShop#27656] opened 2022-02-13 12:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am upgrading PrestaShop from `1.7.8.2` to `1.7.8.3` with the Manual upgrade intructions. 

At the `Database upgrade` step, the command fail with this message :
```
sudo -u www-data php install/upgrade/upgrade.php
<?xml version="1.0" encoding="UTF-8"?><action result="error" id="32" />
```
Same result by the web server way : https://site/install/upgrade/upgrade.php

I find this log to help you
```
cat var/logs/prod/20220213_upgrade.log
*ERROR* 	v1.7.8.3	2022/02/13 - 12:55:34: No upgrade is possible.
```

### Expected behavior

The upgrade ends fine

### Steps to reproduce

```
sudo -u www-data php install/upgrade/upgrade.php
```

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3.27, 7.4.27

**Comment by hibatallahAouadni** [comment] 2022-02-14 12:16
Hello @bhocde 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25977. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-02-14 12:16
Duplicate of #25977

**Closed as completed by hibatallahAouadni** 2022-02-14 12:16 UTC
Labels: Bug, Duplicate, Invalid
