### ISSUE TITLE
BO - An error is displayed when edit in tags page while enable and disable the product status

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28187] opened 2022-04-08 14:19 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error is displayed when edit in tags page while enable and disable the product status : `The object cannot be loaded (or found)`

PS1778 :x: 
![image](https://user-images.githubusercontent.com/92912932/162451997-efd24b9a-758c-4311-bce0-2433717c7d13.png)

develop :x: 

Uploading issue tag.mp4…

This issue is present in product page V2 and V1

### Expected behavior

No error is displayed

### Steps to reproduce

Case 1 :

1. Create a product V2 (with this PR ) or a product V1
2. Create a dedicated tag
3. Disable the product and Save
4. GO to > Shop parameters > Search > Tags
5. Edit the created tag
6. Enable the product
7. Come back to the tag page and refresh
8. See error > `The object cannot be loaded (or found)` is displayed

Case 2 :

1. Create a product V2 (with this PR ) or a product V1
2. Create a dedicated tag
3. Disable the product and Save
4. GO to > Shop parameters > Search > Tags
5. Check the created tag
6. Come back to the product and Enable the product and Save
7. In tags page > edit the created tag
8. See error > `The object cannot be loaded (or found)` is displayed

### PrestaShop version(s) where the bug happened

develop, 1.7.7.8, 1.7.8.x

### PHP version(s) where the bug happened

7.4, 7.2

**Comment by florine2623** [comment] 2023-12-27 14:25
I can't reproduce this issue on 8.1.x. So I'm closing it.


https://github.com/PrestaShop/PrestaShop/assets/16019289/70b39ef2-4ca7-4e22-9bb8-b2bd80ad2351

**Closed as completed by florine2623** 2023-12-27 14:25 UTC
Labels: Bug, Minor, BO, Search, Fixed, 1.7.7.8, Verified
