### ISSUE TITLE
Meta title and Meta description in the category pages have different limit values

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#12875] opened 2019-03-11 18:42 UTC
hi
why the size of Meta title and Meta description of categories are different from those of products?
I think the right size are those of products, the classic 70 and 160
all pages have the same rules so there are no differences between categories or products or homepage

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/54148848-44d0c980-4435-11e9-8254-6352bfcbca87.png)
![2](https://user-images.githubusercontent.com/653230/54148849-44d0c980-4435-11e9-8a9d-aa54dd277c79.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-03-12 09:32
Hi @maofree,

The Title tag and especially the Meta Description are two important elements for the SEO.
Now, the recommended the maximum size for the meta description was often between 150 and 160 characters max.
On computers, Title tags will now display on up to 70-71 characters where we could now add between 50 and 60 characters for full display in Google results.
So, on the product page, it is OK.
For the categories page, @matks, what do you think, we will consider the recommended maximum length for the meta title & meta description for a category during the migration: #10194?
Thanks!

**Comment by Maofree** [comment] 2019-03-12 11:04
hi
yes I know that, but in the category pages it is written 255 and 512

**Comment by khouloudbelguith** [comment] 2019-03-12 11:08
@maofree, yes.
I pinged our develop @matks to check if we will consider the recommended maximum length for the meta title & meta description for a category during the migration: #10194.
Thanks!

**Comment by matks** [comment] 2019-03-13 12:45
Hi @khouloudbelguith, yes, modifying the length of the fields is very easy and can be done when we migrate the page. However it would be good to double-check the impact on this field as SEO remains a shady area. For me, I know I'm bad at it 😛.

I consequently add this item to the issue todo-list for the page.

**Comment by khouloudbelguith** [comment] 2019-03-14 10:10
Hi @matks,

Thanks for your feedback.
@maofree, your issue will be fixed, it is added in this ticket: #10194.
I close this issue, please follow #10194.
Thanks!

**Closed as completed by khouloudbelguith** 2019-03-14 10:10 UTC
Labels: Improvement, BO, Duplicate, Categories, SEO & URLs, 1.7.5.1

**Comment by khouloudbelguith** [comment] 2020-10-08 09:38
Duplicate of #10194
