### ISSUE TITLE
The option "Enable Multistore" is enabled when a shop is selected in the general page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10116] opened 2018-08-24 10:54 UTC
**Describe the bug**
Since the version PS 1.7.4, the General page is migrated to Symfony.
After enabling the multistore context & creating two shops ShopA, ShopB.
In the general page, ShopA is selected => the "Enable Multistore" option is enabled, it shouldn't.
![image](https://user-images.githubusercontent.com/16067358/44580971-4b029f80-a79c-11e8-8704-60408f0f7ea5.png)
In the 1.7.3.4 is OK
![image](https://user-images.githubusercontent.com/16067358/44581092-afbdfa00-a79c-11e8-933a-0e05062d0f75.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by marionf** [comment] 2018-08-24 11:51
Hello @khouloudbelguith 
I manage to reproduce the issue in 1.7.4.0, so it's not a regression of 1.7.4.2
Your issue is a duplicate of #9548

**Closed as completed** 2018-08-24 11:55 UTC
Labels: Bug, Minor, Duplicate, 1.7.4.2
