### ISSUE TITLE
Related Products problem

### ISSUE THREAD

**Issue by Ortezjan** [PrestaShop/PrestaShop#13531] opened 2019-04-23 14:19 UTC
**Describe the bug**
When I save related products to product all working fine. But when I refresh product page I get an error. I mean that "ref" in the related product. I receive that information from my template support: 

"Sorry, I really don't know this problem. When I disable the friendly URL option on your site, it works, see the attachment. I think it is related to the UTF-8 character code in your site, because I see you have some product title with non-UTF-8 characters. But I don't know how to check this problem."

**To Reproduce**
1. Go to 'product page'
2. Click on 'product'
3. Scroll down to 'add related products'

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/49912771/56588174-24269280-65e3-11e9-9f6b-218648b27afd.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-04-23 14:58
Hi @Ortezjan,

I did not manage to reproduce the issue with PS1.7.5.1.
![image](https://user-images.githubusercontent.com/16067358/56591324-70bc9e80-65e0-11e9-867c-99d826096dcf.png)
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks to check & feedback.

**Comment by Ortezjan** [comment] 2019-04-23 15:10
I have no idea i doing good but:
![Screenshot_2](https://user-images.githubusercontent.com/49912771/56592274-a36b9480-65ea-11e9-9ae5-803c10f8b58e.png)
![Screenshot_3](https://user-images.githubusercontent.com/49912771/56592280-a797b200-65ea-11e9-8e74-ce99c4f3991f.png)

**Comment by Ortezjan** [comment] 2019-04-23 15:20
This error showing when i refresh the product page. I have no idea i doing good but:
![Screenshot_2](https://user-images.githubusercontent.com/49912771/56593074-10335e80-65ec-11e9-8f8f-eb1d95ad1d1e.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/49912771/56593122-14f81280-65ec-11e9-978c-292ac3e15ba4.jpg)

**Comment by khouloudbelguith** [comment] 2019-04-23 15:57
@Ortezjan, in your second screenshot, could you please try to click on the error, you should see the error message in "Response" or "Preview" tab
Thanks!

**Comment by Ortezjan** [comment] 2019-04-23 16:02
I can't click on that. 
![Screenshot_2](https://user-images.githubusercontent.com/49912771/56597013-ec731700-65f1-11e9-9e33-16408dadaeff.png)

**Comment by khouloudbelguith** [comment] 2019-04-23 16:19
@Ortezjan, you should click on the error as described in this screenshot
![image](https://user-images.githubusercontent.com/16067358/56598080-b03cb800-65eb-11e9-8e49-2f38ad8375bb.png)
thanks to check & feedback

**Comment by Ortezjan** [comment] 2019-04-23 16:37
In text file is all information from response.
(https://github.com/PrestaShop/PrestaShop/files/3108668/Nowy.dokument.tekstowy.txt)

**Comment by Ortezjan** [comment] 2019-04-23 16:39
And on FO related products display normally:
![Screenshot_3](https://user-images.githubusercontent.com/49912771/56599558-17ac3500-65f7-11e9-95f4-8fc076a06656.png)

**Comment by khouloudbelguith** [comment] 2019-04-23 16:49
@Ortezjan, no, your file doesn't contain the errors.
Could you please navigate to you BO => Design => Image Settings => Click on the "Regenerate thumbnails" button
Thanks to check & feedback.

**Comment by Ortezjan** [comment] 2019-04-23 17:50
Same thing.

**Comment by Ortezjan** [comment] 2019-04-23 17:55
Only when I change URL settings these related products show up. 
<img width="716" alt="5cbf0ea71d2cc" src="https://user-images.githubusercontent.com/49912771/56604217-c6ee0980-6601-11e9-9f1b-0eed3fbe0ad3.png">

**Comment by khouloudbelguith** [comment] 2019-04-24 09:57
@Ortezjan,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by Ortezjan** [comment] 2019-04-24 10:35
Done but same thing.

**Comment by khouloudbelguith** [comment] 2019-04-24 10:41
@Ortezjan, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Ortezjan** [comment] 2019-04-24 12:26
I turn on PHP error: 

Parse error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /home/barnmobleg/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 201

**Comment by Ortezjan** [comment] 2019-04-24 12:32
I have it shared hosting in OVH company and I don't have access to PHP logs and server logs.

**Comment by khouloudbelguith** [comment] 2019-04-24 13:12
@Ortezjan,
Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by Ortezjan** [comment] 2019-04-24 13:21
I upload this file and go to https://www.barn-mobler.se/phppsinfo.php and I try to login with default login and password but I can't. Nothing happened.

**Comment by Ortezjan** [comment] 2019-04-24 13:21
I should upload just "phppsinfo.php" file?

**Comment by Ortezjan** [comment] 2019-04-24 13:23
![Screenshot_1](https://user-images.githubusercontent.com/49912771/56662745-f43fc380-66a4-11e9-8eb7-a99376fc15b7.png)

**Comment by khouloudbelguith** [comment] 2019-04-24 13:57
@Ortezjan, Thanks to check with this file a feedback
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/3112586/phppsinfo.php.zip)

**Comment by Ortezjan** [comment] 2019-04-24 14:02
![Screenshot_3](https://user-images.githubusercontent.com/49912771/56665468-66ff6d80-66aa-11e9-8601-27a6c45391c6.png)
![Screenshot_4](https://user-images.githubusercontent.com/49912771/56665475-6961c780-66aa-11e9-835e-e427037f4ce8.png)

**Comment by khouloudbelguith** [comment] 2019-04-24 14:14
@Ortezjan, the error "Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE)" ... happens when you have a PHP older than 5.5 which is not your case.
Hav you any feedbacks from your hosting?
Thanks!

**Comment by Ortezjan** [comment] 2019-04-24 14:42
Nope. I have no idea about what I should ask them.

**Comment by khouloudbelguith** [comment] 2019-04-24 14:49
@Ortezjan, that's ok, you can ask them about your error displayed.
If you put php -v in your terminal what is the exact information provided?
Thanks!

**Comment by Ortezjan** [comment] 2019-04-24 14:53
I don't have a possibility to open terminal.

**Comment by khouloudbelguith** [comment] 2019-04-24 15:08
@Ortezjan, could you please check that the `mbstring` is installed on your server.
![image](https://user-images.githubusercontent.com/16067358/56670645-23593380-66ab-11e9-9449-8d28cc25c41a.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-27 07:33
Hi @Ortezjan,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-27 07:33 UTC
Labels: BO, No change required, 1.7.5.1

**Comment by kazzo** [comment] 2019-12-13 11:01
I Have exactly the same issue.
So I see the broblem isn't solved, decide to continue thread.

when I disable friendly URLs related products show up.

In phppsinfo got all green except yellow PHP version, mine is 5.6.38 but it shouldn't matter cause required is 5.6 (Ortezjan got 7.2 and problem also occurred).
I have in phpinfo mbstring set as above except oniguruma version it not appears in mine.

I have no access to PHP log but in Apache error log I have:
AH01071: Got error 'Primary script unknown\n', referer: https://admirsklep.pl/admin516ncnsa4/index.php/sell/catalog/products/1?_token=TOjqsgkbEghAGWICydVkBAx6QzciwWrUL_41eqOJRKU

PHP version 5.6.38
Presta Shop version: 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-12-19 09:00
@kazzo, the issue created here: #16799

**Comment by Nerque** [comment] 2020-02-09 21:06
I have the same problem.
I read that it might be a server problem, but it doesn't make sense.
PHP version 7.2.27
Prestashop 1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-02-10 11:09
Hi @Nerque,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by Nerque** [comment] 2020-02-22 08:32
https://github.com/PrestaShop/PrestaShop/issues/17781
