### ISSUE TITLE
Unexpected redirection on checkout

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#14486] opened 2019-07-04 14:20 UTC
**Describe the bug**
On the checkout page, when we choose a shipping method or check gift wrapping, we are redirected to the last checkout step.

This behavior is not an issue sometimes but when there are for example a pickup point or a gift message to input, this redirection is unexpected.

**To Reproduce**
1. Fill a cart
2. Complete checkout information until the last step (payment)
3. Go back to shipping step
4. Choose another shipping method or check gift wrapper

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.15

**Analyze**
I've analyzed the issue, and it appears on this line:
https://github.com/PrestaShop/PrestaShop/blob/8d3e985c093c656ef210d122c3dac0ecd9cd85af/themes/core.js#L64

This line appears to be:
https://github.com/PrestaShop/PrestaShop/blob/8d3e985c093c656ef210d122c3dac0ecd9cd85af/themes/_core/js/common.js#L57-L75

It is called from:
https://github.com/PrestaShop/PrestaShop/blob/8d3e985c093c656ef210d122c3dac0ecd9cd85af/themes/_core/js/checkout-delivery.js#L46-L50

And this line seems to cause the issue:
https://github.com/PrestaShop/PrestaShop/blob/8d3e985c093c656ef210d122c3dac0ecd9cd85af/themes/classic/templates/checkout/_partials/steps/payment.tpl#L8

**Comment by khouloudbelguith** [comment] 2019-07-04 14:51
Hi @yannicka,

This issue is fixed in the Ps1.7.6.0 version.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13106 to fix the issue.
Your ticket is a duplicate of #11750
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-04 14:51
Duplicate of #11750

**Closed as completed by khouloudbelguith** 2019-07-04 14:51 UTC
Labels: Duplicate
