### ISSUE TITLE
Product tags validation - isGenericName or isTagList

### ISSUE THREAD

**Issue by BrunoJunior** [PrestaShop/PrestaShop#15558] opened 2019-09-16 10:22 UTC
**Describe the bug**
In the ProductCore definition, the information «meta_keywords» has to be a generic name (Validate::isGenericName).
In the TagCore definition, the information «name» has to be a generic name (Validate::isGenericName).
In the AdminProductController, when data are checked, the tag list has to respect the isTagsList validation. This validation is only made when data come from the back office.
If a webservice send some tags, a «100% whool» is a valid one.
But after that, if I would like to change some data of the product in the PrestaShop B.O. I can't do it because tag list is not valid …
Why the tag list validity is more restrictive than tag names ?

**To Reproduce**
1. Create a tag «100% whool» via webservice
2. Attach this tag to the product via webservice
3. Go to the product page on the B.O.
4. Change something in the product (name or whatever …)
5. Save
6. See error

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by mariem-abid** [comment] 2019-09-16 10:54
Hi @BrunoJunior,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

**Comment by khouloudbelguith** [comment] 2019-09-17 11:17
Hi @BrunoJunior,

>Attach this tag to the product via Webservice

What is the exact script did you use in this case?

In my, I used this script this script to add a tag via webservice
```
>html><head><title>pUT DATA</title></head><body>
<?php

// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://prestashop.local/1761');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$psXML = <<<XML
<prestashop>
<tag>
  <id/>
  <id_lang>2</id_lang>
  <name>"100% whool"</name>
</tag>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
$opt = array( 'resource' => 'tags' );
$opt['postXml'] = $xml->asXML();
$xml = $webService->add( $opt );
?>
```
For your information: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-17 07:47
Hi @BrunoJunior,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-17 07:47 UTC
Labels: Bug, Webservice, No change required, 1.7.6.1
