### ISSUE TITLE
Product combinations not working on 1.7.5.2

### ISSUE THREAD

**Issue by silviu25** [PrestaShop/PrestaShop#13947] opened 2019-05-23 16:14 UTC
have a issue with product combinations, I created 2 attributes: sizes and material

if I go to one product and configure everything, then hit Generate, then config the combinations with sesired prices and options and etc on product page are displayen only few of them or all of them but when I select for example a size and another material the price is not changing. Or sometimes they are simply not displayed on product page.

I;m using the default theme and no other extra module installed

**Comment by khouloudbelguith** [comment] 2019-05-24 08:34
Hi @silviu25,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-24 07:30
Hi @silviu25,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-24 07:30 UTC
Labels: Bug, BO, Combinations, No change required, 1.7.5.2
