### ISSUE TITLE
Locale::formatPrice() gives error for currency id.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#21688] opened 2020-10-30 13:13 UTC
#### Describe the bug

In a module, using  `$this->context->currentLocale->formatPrice("21.986", Configuration::get('PS_CURRENCY_DEFAULT') );` gives an error:
![image](https://user-images.githubusercontent.com/24461669/97708660-6f174500-1ab9-11eb-8d77-634d4afdab78.png)

#### Expected behavior

I have only one currency, and it is active and working, after using Locale::formatPrice() with Configuration::get('PS_CURENCY_DEFAULT') it should be just working, or explain the error clearly.
Why does the error say such unclear message? What is wrong?

#### Steps to Reproduce

In a module use:
`$this->context->currentLocale->formatPrice("21.986", Configuration::get('PS_CURRENCY_DEFAULT') );`

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.18

**Comment by florine2623** [comment] 2020-10-30 14:26
Hi @grzegorzgit ,
Could you send me an example of the module using `$this->context->currentLocale->formatPrice("21.986", Configuration::get('PS_CURRENCY_DEFAULT') );` please ?
With that, we will be able to reproduce the error and tell you what to do.
Thanks!

**Comment by kpodemski** [comment] 2020-10-30 14:28
Hey @grzegorzgit 

![image](https://user-images.githubusercontent.com/2137763/97716983-8f003600-1ac4-11eb-9a5d-8f424bbd7728.png)

Second parameter should be currency code, for example "EUR"

**Comment by hibatallahAouadni** [comment] 2020-11-19 09:58
Hello @grzegorzgit ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-19 09:58 UTC
Labels: Currencies, No change required, 1.7.6.7
