### ISSUE TITLE
description short not save more 400 characters 

### ISSUE THREAD

**Issue by corsik** [PrestaShop/PrestaShop#10831] opened 2018-10-03 12:38 UTC
In the description short it is not possible to save more than 400 characters, after the update, no save is accepted.
http://prntscr.com/l1ohav

**Comment by khouloudbelguith** [comment] 2018-10-03 12:49
Hi @corsik,
 
I did not manage to reproduce the issue with PS1.7.4.2.
I attached a video record.
https://drive.google.com/file/d/1_MyPLBprcpEDix5PwyFUm-Yo4HemXTzw/view
Thanks to check & feedback.

**Comment by corsik** [comment] 2018-10-03 13:07
I checked it myself, if the value 0 is set in the product settings, the description shows the maximum 800 characters, and saves only 400
http://prntscr.com/l1oy9u
http://prntscr.com/l1oyh7

**Comment by khouloudbelguith** [comment] 2018-10-03 13:22
Hi @corsik,

When I try to set the Max size of short description option to **0**, an alert is displayed => Invalid size.
![image](https://user-images.githubusercontent.com/16067358/46412852-f4d03700-c71f-11e8-9c68-94b0476928a5.png)
How did you save this value 0 in this option?

**Comment by corsik** [comment] 2018-10-03 13:27
@khouloudbelguith, strange i had the "Max size short description" value 0

**Comment by corsik** [comment] 2018-10-03 13:27
@khouloudbelguith Then the question is closed

**Comment by khouloudbelguith** [comment] 2018-10-03 13:28
@corsik, what is the exact version of Prestashop did you use?

**Comment by corsik** [comment] 2018-10-03 13:51
@khouloudbelguith, At the moment, 1.7.4.2, but initially it was installed 1.7.0 and then updated using the autoupdate module.

**Comment by khouloudbelguith** [comment] 2018-10-03 13:59
@corsik could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-08 11:49
Duplicate of #11164

**Closed as completed by khouloudbelguith** 2018-11-08 11:49 UTC
Labels: BO, Duplicate, Product settings
