### ISSUE TITLE
Contact Form 4.3.0 Agreement Checkbox in Frontend has broken translation

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#22116] opened 2020-11-25 19:55 UTC
#### Describe the bug

Fresh installed PS 1.7.6.9, with Contact Form Updated to 4.3.0 and Contact Information 3.3.0

The standard Translation for the Contact Form Checkbox is wrong in german.
The Checkbox text has no sense in german, but it looks not like a fake dummy text - or does it :D ?

> _Enim quis fugiat consequat elit minim nisi eu occaecat occaecat deserunt aliquip nisi ex deserunt._

![ps_contact_form_issue_german_translation_frontend](https://user-images.githubusercontent.com/64662500/100275653-91896a80-2f60-11eb-854a-3acb471a624a.png)

If you look for the translation files of the Contact Form Module, everything seems proper and nothing is missing.
But if you check the Contact Information module, there is 1 expression missing - but it is not shown in the configuration, so there is no way to set it.
I dont know if these are 2 seperate behaviours, or if they are one issue.

See Screenshot for the prompt of 1 missing expression, but you only see 2 listed

![ps_contact_form_issue_german_translation](https://user-images.githubusercontent.com/64662500/100275331-0a3bf700-2f60-11eb-9570-c39d94b1d544.png)

#### Expected behavior

- Translation Box for the missing expression working
- proper translation of the checkbox in the shop frontend of the german translation with the Contact Form 

#### Steps to Reproduce

1. Install PS 1.7.6.9 with German translation activated
2. Upgrade Contact Form to 4.3.0 and Contact Information to 3.3.0
3. See Frontend of the shop in German translation
4. See Backend Translation Menu

**Comment by hibatallahAouadni** [comment] 2020-11-26 09:45
Hello @6xthFNGR 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20526. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: you can change the content in the GDPR module, see the attached screenshot below (follow the steps):

![image](https://user-images.githubusercontent.com/23308427/100334699-6b051700-2fd4-11eb-85c3-40dac27b9a8f.png)

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-26 09:45
Duplicate of #20526

**Closed as completed by hibatallahAouadni** 2020-11-26 09:45 UTC
Labels: Duplicate
