### ISSUE TITLE
Product combination form not displaying in admin

### ISSUE THREAD

**Issue by sandra2n** [PrestaShop/PrestaShop#14114] opened 2019-06-07 15:13 UTC
Hello,

There is an issue in Prestashop 1.7.5.2, with the display of product combination form in admin if the shop ID 1 or the lang ID 1 do not exist.

The issue is from variables value directly written in file \src\PrestaShopBundle\Controller\Admin\ProductController.php at the line 613

"$attributeGroups = $doctrine->getRepository('PrestaShopBundle:Attribute')->findByLangAndShop(1, 1);"

Thanks for the help in fixing that!

**Comment by mariem-abid** [comment] 2019-06-07 15:45
Hi @sandra2n,

Could you please add steps to reproduce the issue in a new comment.

Thanks

**Comment by sandra2n** [comment] 2019-06-11 06:41
Hi,
Delete your lang ID 1 for exemple (or activate multishop, create new shop and delete shop ID 1). Then go in a product (in the admin) and in the combination tab. No attributes are displayed in the column at the right of the page, so no combination can be created.

As you can see in my previous messages the attributeGroups variable is filled based on lang ID 1 and shop ID 1 (findByLangAndShop(1, 1)), so if they do not exists, attributeGroups stay empty.

Thanks

**Comment by khouloudbelguith** [comment] 2019-06-11 12:19
Hi @sandra2n,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10924 to fix the issue.
It is fixed in the PS1.7.6.0.
Your ticket is a duplicate of #9627
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-11 12:19
Duplicate of #9627

**Closed as completed by khouloudbelguith** 2019-06-11 12:19 UTC
Labels: Duplicate, Combinations
