### ISSUE TITLE
Ps_Emailsubscription isNewsletterRegistered failure

### ISSUE THREAD

**Issue by princeofnaxos** [PrestaShop/PrestaShop#21003] opened 2020-09-16 05:53 UTC
#### Describe the bug

The function does not report existing email correctly.

#### Expected behavior

The function should report existing email.

#### Steps to Reproduce

1. Register for the newsletter with an email address
2. Refresh the page
3. Register for the newsletter again with the same email address
4. The email address will be registered again (green message)

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

The SQL command uses escaped single qoutes around the email address. For some reason, this results in an empty dataset. Replacing the \' with " (double qoutes) solves the issue.

**Comment by sarahdib** [comment] 2020-09-16 08:01
Hello @princeofnaxos 

Despite our efforts, we were not able to reproduce your issue with the provided information.
https://drive.google.com/file/d/1kVm-oohrKN_FWTPh8AiPpsKozzdCAyYp/view

Did you use the last version of the module ?

Thank you!

**Comment by khouloudbelguith** [comment] 2020-10-12 11:58
Hi @princeofnaxos,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-12 11:58 UTC
Labels: Emailsubscription, No change required
