### ISSUE TITLE
Bug error in sizes and color selection

### ISSUE THREAD

**Issue by JuanHidalgoM** [PrestaShop/PrestaShop#10978] opened 2018-10-11 19:53 UTC
**Describe the bug**
Hello, I have a serious problem, I have installed Prestashop 1.7.4.3 I'm making a new store and everything was fine until the product was selected, and select between the sizes, second sizes and colors and appear an error when are updated the size options as the case,

For example, the product in blue has sizes X, XX and XXX and the orange color has sizes X and XX.

If you select the blue color in size XXX (Orange does not have it) and if it changes to blue color an error appears. Append photo,

I hope to have explained correctly.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2.10
![newerror](https://user-images.githubusercontent.com/44071004/46829928-d04e0d80-cd64-11e8-8263-3458b0248637.png)

**Comment by khouloudbelguith** [comment] 2018-10-12 07:42
Hi @JuanHidalgoM,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9390 to solve the issue.
It is fixed in the next release 1.7.5.0.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-12 07:42
Duplicate of #9390

**Closed as completed by khouloudbelguith** 2018-10-12 07:42 UTC
Labels: Duplicate

**Comment by JuanHidalgoM** [comment] 2018-10-16 14:09
Do you have date for update 1.7.5 ?

And this version correct the problem?

Thank you and good day

**Comment by khouloudbelguith** [comment] 2018-10-16 14:13
@JuanHidalgoM, code freeze should be in this month, and then, beta will be released for debugging.
