### ISSUE TITLE
Remove unnecessary restrictions on the data format during importing.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#21724] opened 2020-11-03 08:38 UTC
#### Describe the bug

Importing data means that you most likely import it from some other system. <- Does this make sense?
Other systems DO NOT HAVE TO HAVE the same format requirements as PrestaShop. 
The format of imported data therefore cannot be UNNECESSARY strict. It should have only the minimal limitations.

During import of customers form WooCommerce, some of my customers were with Dr.med. before their name (because this is what people with degree do - this is nothing unusual).

Prestashop import of customers breaks at this point.

Please don't close this ticket, this requires modification. This is an issue regardless of if "Dr.med." is a valid part of a name, this has to be fixed.

#### Expected behavior

PrestaShop should be flexible enough to proceed import without UNNECESSARY restrictions. People from different parts of the world may have different names and the way they write their degree. 

#### Steps to Reproduce

Try to import csv with a customer that has a name:  Dr.med. Gregory House, with a "Dr.med. Gregory" in the first name field.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version:  1.7.6.7

**Comment by SimonGrn** [comment] 2020-11-03 09:04
Hello @grzegorzgit 
This is a duplicate of #21713 which was closed and answered.
I close this ticket.

Thank you for your understanding.

**Closed as completed by SimonGrn** 2020-11-03 09:04 UTC
