### ISSUE TITLE
PS_GDPR v2.0.0 - homepage items

### ISSUE THREAD

**Issue by PrestaPierre** [PrestaShop/PrestaShop#31877] opened 2023-03-22 12:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

these items are not functional, no redirect
![Capture d’écran 2023-03-22 à 13 23 53](https://user-images.githubusercontent.com/112935373/226904534-1d5fe12a-3b89-4da5-843a-2846878402cc.png)

### Expected behavior

When I click on one of the three items, I must be redirected to the associated page

### Steps to reproduce

Go to module ps_gdpr
And i click on "Manage" or "Customize" or "keep track"
And nothing happen

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.9

### If your bug is related to a module, specify its name and its version

ps_gdpr

**Comment by paulnoelcholot** [comment] 2023-03-22 16:19
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2023-03-22 16:19 UTC
Labels: Bug, Invalid
