### ISSUE TITLE
Display error (text wrongly encoded) in the payment page 1.7

### ISSUE THREAD

**Issue by LaureMatou** [PrestaShop/PrestaShop#22272] opened 2020-12-07 13:44 UTC
In PrestaShop 1.7, in the payment page, the text seems wrongly encoded.
Example with Revolut:
![image](https://user-images.githubusercontent.com/33054143/101357621-fb2b4200-3899-11eb-9b90-9c27304a91a1.png)
" you & # 3 9 ; l l  be able " (I'm separing the characters otherwise GitHub is encoding the text correctly to "you'll be able")

The test was done with Machine Shuffle 1.7.7.0
The text is correctly displayed in the module Catalog (1.7 and 1.6) and in the 1.6 payment section
![image](https://user-images.githubusercontent.com/33054143/101357845-4f362680-389a-11eb-9407-83e532afdb3c.png)
![image](https://user-images.githubusercontent.com/33054143/101357857-52c9ad80-389a-11eb-9571-23954a123315.png)
![image](https://user-images.githubusercontent.com/33054143/101357918-69700480-389a-11eb-8a08-9e36a15a1c2c.png)

#### Steps to Reproduce

1. Go to Machine Shuffle
2. Open a 1.7 shop
3. Click on Payment > Payment Methods
4. See module Revolut Short desc with a display error

**Comment by hibatallahAouadni** [comment] 2020-12-07 14:29
Hello @LaureMatou 

I managed to reproduce the issue with PS1.7.6.7, PS1.7.6.9 and PS1.7.7.0, see the attached screenshots below:

**PS 1.7.7.0**

![image](https://user-images.githubusercontent.com/23308427/101362094-f23d6f00-389f-11eb-8319-6dbc6e4ed648.png)

**PS1.6.1.20**, I didn't manage to reproduce it:

![image](https://user-images.githubusercontent.com/23308427/101362932-0afa5480-38a1-11eb-882e-947060d39ef5.png)

It was already in the debug backlog and it has been marked as fixed #21298
That's odd!

Thanks!

**Comment by PierreRambaud** [comment] 2020-12-07 14:37
Hi and thanks for your report.

Isn't a duplicate from #21298 ? Shouldn't be fixed in the MBO module? :)

**Comment by hibatallahAouadni** [comment] 2020-12-07 14:38
@PierreRambaud exactly !! 
@atomiix this should be fixed, so what's happen?

**Comment by hibatallahAouadni** [comment] 2020-12-08 11:42
Hello @LaureMatou 

This issue has been fixed with this [PR](https://github.com/PrestaShopCorp/ps_mbo/pull/101), we will encounter this problem until the module has a new release that contains this fix.

This issue is a duplicate of #21298. So, I close it.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-08 11:42
Duplicate of #21298

**Closed as completed by hibatallahAouadni** 2020-12-08 11:42 UTC
Labels: Bug, Trivial, BO, Duplicate, Payment methods, Regression, MBO, 1.7.7.0, 1.7.6.7, 1.7.6.9
