### ISSUE TITLE
Could not find the product in cart, meaning Order and Cart are out of sync

### ISSUE THREAD

**Issue by z72diego** [PrestaShop/PrestaShop#23782] opened 2021-03-26 03:46 UTC
After upgrading with 1-click upgrade (and finished with 0 errors) from 1.7.6.x to 1.7.7.2, an Error 500 it's displayed when trying to edit some old orders (not all of them). Post-upgrade orders do not appear to have this problem.

ie. 1) delete a discount already applied in an order, or add a new one.
ie. 2) return products.
ie. 3) partial refund.

In all cases, this error 500 it's triggered:

Uncaught Exception: Could not find the product in cart, meaning Order and Cart are out of sync
--
Uncaught PHP Exception PrestaShop\PrestaShop\Core\Domain\Order\Exception\OrderException: "Could not find the product in cart, meaning Order and Cart are out of sync" at /var/www/vhosts/distribuidorademafer.com.ar/httpdocs/src/Adapter/Order/OrderAmountUpdater.php line 303
--

Any help?

Thanks.

PHP Ver. 7.2.34
FPM App served by nginx

**Comment by florine2623** [comment] 2021-03-26 08:56
Hello @z72diego ,

After a successful upgrade from 1.7.6.9 to 1.7.7.2, I didn't reproduce your issue.
![Capture d’écran 2021-03-25 à 10 21 31](https://user-images.githubusercontent.com/16019289/112604037-06d55100-8e16-11eb-8dbe-c244088cb2b4.png)

Please check below.
https://drive.google.com/file/d/1noAirlTjHFTbEGkR8znTlVgQgfuFdGSb/view
https://drive.google.com/file/d/1IlQ8X7ie9S94uYIkgzI_x7iS9lN17Cvb/view
![Capture d’écran 2021-03-26 à 09 47 42](https://user-images.githubusercontent.com/16019289/112606182-5fa5e900-8e18-11eb-92d6-f0308436ccde.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thanks

**Closed as completed by florine2623** 2021-03-26 08:56 UTC
Labels: Can't reproduce

**Comment by z72diego** [comment] 2021-03-26 09:13
Please, can you try if the error appears after using the PrestaShop Cleaning Module?

![image](https://user-images.githubusercontent.com/4184726/112609510-5c036980-8dfa-11eb-8b50-01c116d762be.png)
