### ISSUE TITLE
2x thumbnail is not generated when changing/adding category image from BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20373] opened 2020-07-29 08:38 UTC
1. Enable High-DPI images in Images settings.
2. Make a new category and add an image to it.
3. Go to img/c/ and find the category ID.
4. Only regular images are generated, no 2x formats.

**Thumbnails are generated ONLY IF you go to Image settings, select regenerate categories, and you select DELETE PREVIOUS IMAGES.**

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2
* This PR does not fix it: https://github.com/PrestaShop/PrestaShop/pull/16097

**Comment by khouloudbelguith** [comment] 2020-07-29 08:51
Hi @Hlavtox,

You just create an issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/20218 which is duplicate of #19798, is it?

Thanks!

**Comment by Hlavtox** [comment] 2020-07-29 15:53
@khouloudbelguith The other case was when the image was missing, this is a behavior when making an order.

I will check both cases with the PR you mentioned and let you know.

**Comment by khouloudbelguith** [comment] 2020-07-29 15:54
@Hlavtox, thanks!
Waiting for your feedback.

**Comment by Hlavtox** [comment] 2020-07-30 10:51
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/19965

**Comment by khouloudbelguith** [comment] 2020-08-03 13:31
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19798

**Closed as completed** 2020-08-03 13:31 UTC
Labels: Bug, BO, Duplicate, Image, 1.7.6.2
