### ISSUE TITLE
BO - Brands & Suppliers take 2 minutes to open. 1.7.7.8

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#27160] opened 2021-12-31 15:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

My PS is 1.7.7.8 version.

All the backoffice works just fine.

However in this version, Brands & Suppliers take me 2 minutes to load.

I've a dev environment where I upgraded to 1.7.8.2 and it loads in seconds.

Is there a known issue?

### Expected behavior

Should open Brands & Suppliers in seconds

### Steps to reproduce

Go to Brands & Suppliers at backoffice. I've no "suppliers" but I have 780 brands and it takes 2 minutes to load.
If a apply a specific filter like a brand name it opens in seconds

Store with arround 13800 products and 780 brands.

Dedicated server with 32GB of RAM:

Server information Linux #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64

Server software version: Apache
PHP version: 7.2.24-0ubuntu0.18.04.10
Memory limit: 512M
Max execution time: 600
Upload Max File size: 128M

MySQL version: 5.7.36-0ubuntu0.18.04.1
Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPDO

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.2.24

**Comment by hibatallahAouadni** [comment] 2021-12-31 16:28
Hello @seederp2p 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9947. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-31 16:28
Duplicate of #9947

**Closed as completed by hibatallahAouadni** 2021-12-31 16:28 UTC
Labels: Bug, Duplicate, Invalid
