### ISSUE TITLE
Translation Credit Slip : Don't take locale language

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#16326] opened 2019-11-08 08:56 UTC
Hello !

I have a problem with the translations of the credit slip.
Invoices have the right translation (the language of the shop)
On the other hand, for the slip credits, they are all in French even if I download a credit note from an order in the German shop.

And in the translations, it is well translated into German. But if I change the translation in the FR shop, it changes well for the FR credit slip but also for the other shops

Can you help me pls ?

Thanks!

**Screenshots**
![credit-slip-de](https://user-images.githubusercontent.com/25744417/68465935-b4d95e80-0213-11ea-8bcb-fa9d996f2f0d.JPG)

![translation-de](https://user-images.githubusercontent.com/25744417/68462934-e8b18580-020d-11ea-8599-39baec16c73d.JPG)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.4

**Comment by khouloudbelguith** [comment] 2019-11-08 09:40
Hi @ShaimyWinda,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/16rVPZN2C6vnEFml02N9dPwocwNLmDnrp/view
PrestaShop is not compatible with PHP 5.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

Thanks to check & feedback.

**Comment by ShaimyWinda** [comment] 2019-11-08 10:23
Hi @khouloudbelguith 

Do you speak french ?
It's easier for me.

Sorry, My Php version is 5.6
Do you have a multi-shop website?
In fact, the basic language of my shop is French. And we have other shops like Germany, or Spain

Thanks

**Comment by khouloudbelguith** [comment] 2019-11-08 10:32
@ShaimyWinda, yes, I speak French, but English is the norm on GitHub.
No, did you use the Multishop context?
The employee language is Deutch?

Thanks!

**Comment by ShaimyWinda** [comment] 2019-11-08 10:41
@khouloudbelguith 
No, we all speak French. Just we're in the multi national. 

We have a total of 14 countries. 
The weird thing is that the problem comes only from the credit slip.
On invoices or delivery notes, if the order is in German, the invoice will be in German. Logically if you make a credit note of an order that has been ordered in the German shop, and refund it, it should be in German.

But I don't know why the assets take only the translations fr

**Comment by khouloudbelguith** [comment] 2019-11-08 10:53
@ShaimyWinda, what is the exact employee language did you use when generating the Credit slips, because we have already an issue about the document's language, they are printed in the employee language reported here: https://github.com/PrestaShop/PrestaShop/issues/10258.

Thanks!

**Comment by ShaimyWinda** [comment] 2019-11-08 11:17
@khouloudbelguith The exact employee language is French

**Comment by khouloudbelguith** [comment] 2019-11-08 13:39
@ShaimyWinda, As I said before, we are aware of this issue "the document's language, they are printed in the employee language" reported here: #10258.
Your ticket is a duplicate of #10258
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-08 13:40
Duplicate of #10258

**Closed as completed by khouloudbelguith** 2019-11-08 13:39 UTC
Labels: Bug, Duplicate, Credit notes, Translations, 1.7.6.0
