### ISSUE TITLE
Webservice tax_rules listing is KO with multishop feature

### ISSUE THREAD

**Issue by sb-collection** [PrestaShop/PrestaShop#14270] opened 2019-06-18 13:55 UTC
A webservice request in order to get all id_tax_rules_group give unavailable ids.

To Reproduce

Add a new shop with multishop feature
Add a new tax rule group onto the second shop only. Get the new id.
Do a webservice request like this one onto the first shop: api/tax_rules?display=[id,id_tax_rules_group,id_tax]&filter[id_country]=8
You'll see the mistake: you will see the id on item 2. You shouldn't.
Additionnal information
PrestaShop version: 1.7.5

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-18 13:57
Hi @sb-collection,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14212
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-18 13:57
Duplicate of #14212

**Comment by sb-collection** [comment] 2019-06-18 14:49
Do you have a lead time?

**Comment by khouloudbelguith** [comment] 2019-06-18 14:52
@sb-collection, Sorry not yet.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks for your understanding!

**Closed as completed by khouloudbelguith** 2019-06-18 14:52 UTC
Labels: Duplicate
