### ISSUE TITLE
ContextErrorException Notice: Trying to get property 'precision' of non-object

### ISSUE THREAD

**Issue by nelero** [PrestaShop/PrestaShop#34960] opened 2024-01-03 16:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Sometimes, when a customer logs in back, with a non empty cart, an error occurs about precision.
Here are the details

```
<!--StartFragment-->
(1/1) ContextErrorExceptionNotice: Trying to get property 'precision' of non-object
--
in Context.php line 498
at ContextCore->getComputingPrecision()
in Product.php line 5685
at ProductCore::getProductProperties(2, array('id_product_attribute' => 0, 'id_product' => '7779', 'cart_quantity' => '2', 'id_shop' => '1', 'id_customization' => null, 'name' => 'Product n° 12', 'is_virtual' => '0', 'description_short' => '<ul><li>point of description d\'ifferent".</li></ul>', 'available_now' => '', 'available_later' => '', 'id_category_default' => '21225', 'id_supplier' => '4', 'id_manufacturer' => '3', 'manufacturer_name' => 'Amazon', 'on_sale' => '1', 'ecotax' => '0.000000', 'additional_shipping_cost' => '0.000000', 'available_for_order' => '1', 'show_price' => '1', 'price' => '600.320000', 'active' => '1', 'unity' => '', 'unit_price_ratio' => '0.000000', 'quantity_available' => '7', 'width' => '38.000000', 'height' => '43.000000', 'depth' => '22.000000', 'out_of_stock' => '2', 'weight' => '21.000000', 'available_date' => '0000-00-00', 'date_add' => '2022-12-16 12:10:15', 'date_upd' => '2023-12-19 00:52:24', 'quantity' => '7', 'link_rewrite' => 'product-n-12', 'category' => 'best-sellers', 'unique_id' => '0000007679000000000084120', 'id_address_delivery' => '8412', 'advanced_stock_management' => '1', 'supplier_reference' => 'VX18', 'customization_quantity' => null, 'price_attribute' => null, 'ecotax_attr' => null, 'reference' => 'VX18', 'weight_attribute' => null, 'ean13' => '', 'isbn' => '', 'upc' => '', 'mpn' => '', 'minimal_quantity' => '1', 'wholesale_price' => '0.000000', 'id_image' => '3641471', 'legend' => 'Product n° 12', 'reduction_type' => 'percentage', 'is_gift' => false, 'cust_attri' => 'test 2', 'stocks_details' => array(array(array('id_warehouse' => '1', 'physical_quantity' => '7', 'name' => 'Amazon FR', 'delivery_time' => '', 'location' => '', 'id_address' => '13', 'country' => 'France', 'available_quantity' => 6, 'reserved_quantity' => 0), array('id_warehouse' => '2', 'physical_quantity' => '0', 'name' => 'Amazon BE', 'delivery_time' => '', 'location' => '', 'id_address' => '14', 'country' => 'Belgique', 'available_quantity' => 0, 'reserved_quantity' => 0))), 'stock_be' => 0, 'stock_fr' => 6, 'allow_oosp' => 1, 'cover_image_id' => '3641471', 'category_name' => 'Best sellers', 'link' => 'https://www.mywebsite.com/best-sellers/product-n-12-7779.html', 'attribute_price' => 0, 'price_tax_exc' => 497.541758))


<!--EndFragment-->
```
It doesn't happen with all customers or with the same products in cart.
How can i fix it ?

### Expected behavior

No error for the customer after log in back.

### Steps to reproduce

1. log in to customer account
2. add some products with decimal in price (with VAT ok)
3. leave the session ending by itself
4. log in back to the website

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

**Comment by nelero** [comment] 2024-01-03 16:29
After debugging it's $this->currency->precision in function getComputingPrecision() from ContextCore class which is null
could it be a bug when sometimes, context refreshed after customer log in is not complete ?

**Comment by Hlavtox** [comment] 2024-01-03 16:35
99% caused by a module hooked to `actionCartSave`. It's doing something with the cart, when the currency is not yet initialized.
Should be fixed in 8.1.3.

**Comment by florine2623** [comment] 2024-01-03 16:40
Hello @nelero 

Is the error displaying on the FO when the customer tries to log back into his account ? Or is it from the merchant side ?
Could you send a screenshot of the error please ?

**Comment by nelero** [comment] 2024-01-03 17:15
Yes only on frontend, a Woops page.
i patched in dirty mode to have a default precision if $this->currency is null
my function is now :
```
public function getComputingPrecision()
    {
        if ($this->priceComputingPrecision === null) {
            $computingPrecision = new ComputingPrecision();
            if($this->currency===null){
                $this->priceComputingPrecision = 2;
            }
            else{
                $this->priceComputingPrecision = $computingPrecision->getPrecision($this->currency->precision);
            }
        }

        return $this->priceComputingPrecision;
    }
```
and it solved my problem for now.

**Comment by Hlavtox** [comment] 2024-01-03 19:42
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33954

**Closed as completed by Hlavtox** 2024-01-03 19:42 UTC
Labels: Bug, FO, Hook, 1.7.8.10
