### ISSUE TITLE
BO > Categories : Can't add category empty shop install

### ISSUE THREAD

**Issue by ytilotti** [PrestaShop/PrestaShop#37311] opened 2024-11-04 08:06 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

BO > Categories : Can't add category empty shop install

### Expected behavior

Add categories on a new shop

### Steps to reproduce

1. Install PS 8.2.0 (with no demo datas)
2. Go to BO
3. Go to Catalog > Categories
4. No add button

![Image](https://github.com/user-attachments/assets/ee1b689b-b76a-4b29-ac3e-34e9cee84390)

### PrestaShop version(s) where the bug happened

8.2.0

**Comment by florine2623** [comment] 2024-11-04 10:33
Hello @ytilotti ,

I can't reproduce your issue with a fresh install of PS 8.2.0.

![Image](https://github.com/user-attachments/assets/e0945f7e-4e34-469d-a4da-82b395d7b8be)

Please try to reinstall your shop with a version of PHP compatible with 8.2.0 : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart

I'm closing your issue as it seems to be an issue on your shop exclusively.
Thanks!

**Closed as completed by florine2623** 2024-11-04 10:33 UTC
Labels: Bug

**Comment by ytilotti** [comment] 2024-11-05 09:59
I found why.

In configuration the ids are 1 for root and 2 for home but in categories the id are 2 and 4.
Maybe due to a transaction sql.

I think there is something to check.

**Comment by ytilotti** [comment] 2024-11-06 15:29
Duplicate of #20050
