### ISSUE TITLE
500 Server Error Oops, something went wrong.

### ISSUE THREAD

**Issue by storygram** [PrestaShop/PrestaShop#17692] opened 2020-02-17 12:21 UTC
Hi,
when I want to make a new account, or create an account during orders, I get the error ''500 Server Error Oops, something went wrong.
Try to refresh this page or feel free to contact us if the problem persists.''

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by storygram** [comment] 2020-02-17 13:06
another problem, I would like to change the theme and receive

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment] 2020-02-17 14:21
Hi @storygram,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots

You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-18 07:53
Hi @storygram, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-18 07:53 UTC
Labels: Bug, FO, Customer, No change required
