### ISSUE TITLE
Upgrade problem to Prestashop 1.7.7.1 Cannot declare class PrestaShopBundle\Entity\Tab

### ISSUE THREAD

**Issue by Art3c** [PrestaShop/PrestaShop#22775] opened 2021-01-11 19:47 UTC
Hi,

#### Describe the bug
i did a updateto the new 1.7.7.1 from 1.7.6.9. I did a full backup of the DB and files on the server. When 1-click upgrade started to updaet it shows me this error. Please help! The problem is the same as in #22248. The problem #22248 was closed because the bug should not be on PS 1.7.7.1

These time also the rollback was not ok and i had to do a manual restore.

`
[INTERNAL] /home/shopmo97/public_html/src/PrestaShopBundle/Entity/Tab.php line 37 - Cannot declare class PrestaShopBundle\Entity\Tab, because the name is already in use.
`

The BO stops working :( The FO was online butt without the pictures.
#### Steps to Reproduce

1. Go to 1-Click upgrade
2. Did the check list and full server backup
3. Clicked upgrade
4. After upgrading all the files it writes upgrading DB and the the error message is displayed.

#### Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/75488263/104231144-ca1ccf00-544e-11eb-8a2d-0e66f4263a79.png)
![Screenshot_3](https://user-images.githubusercontent.com/75488263/104230741-406d0180-544e-11eb-859d-561c27746e1b.png)

#### Additional informations
PS version: 1.7.7.1
PHP version:

**Comment by Art3c** [comment] 2021-01-11 19:52
@hibatallahAouadni same problem with 1.7.71 :(

**Comment by hibatallahAouadni** [comment] 2021-01-12 14:50
Hello @Art3c 

I just upgraded my shop 1.7.6.9 to 1.7.7.1 with **1-Click Upgrade** module **v4.11.0** and I didn't encounter this problem, the upgrade process finsihed with success. The only bug that I encountred is in BO>Orders page :sweat: see the attached screen record below:

https://drive.google.com/file/d/1mCwxRT6QGjzULrLWAw8zUR35I1NhGe5a/view

Please check and feedback.
Thanks!

**Comment by Art3c** [comment] 2021-01-12 14:55
> Hello @Art3c
> 
> I just upgraded my shop 1.7.6.9 to 1.7.7.1 with **1-Click Upgrade** module **v4.11.0** and I didn't encounter this problem, the upgrade process finsihed with success. The only bug that I encountred is in BO>Orders page 😓 see the attached screen record below:
> 
> https://drive.google.com/file/d/1mCwxRT6QGjzULrLWAw8zUR35I1NhGe5a/view
> 
> Please check and feedback.
> Thanks!

What means this error?

[INTERNAL] /home/shopmo97/public_html/src/PrestaShopBundle/Entity/Tab.php line 37 - Cannot declare class PrestaShopBundle\Entity\Tab, because the name is already in use.


Is there a way to maual upgrade the DB?

**Comment by hibatallahAouadni** [comment] 2021-01-17 13:06
Hello @Art3c 

It's weird :confused: you encountered the same issue while upgrading your shop to 1.7.7.0 (#22248)
This issue has been fixed with 1.7.7.1, and even I didn't encounter it :confounded: 

Well, could you please check my comment in your old issue [here](https://github.com/PrestaShop/PrestaShop/issues/22248#issuecomment-751258880) and follow my steps to resolve the problem manually.
Sorry for the inconvenience :sweat: 

I will ping the Developers Team to take a deep look in this issue.
Ping @PrestaShop/prestashop-core-developers I believe this issue has been fixed, but it seems that there's some other conf could trigger the issue again :confounded: could you please check it out.

Thanks in advance.

**Comment by PierreRambaud** [comment] 2021-01-20 15:40
This error means the class has already been loaded, it's maybe because of a module, or opcache :thinking: 
If we are not able to reproduce we can't do anything :sweat:

**Comment by Art3c** [comment] 2021-01-20 16:16
@PierreRambaud How can i help you to reproduce the error? I have tried to disable all modules and loaded the default theme. No luck :( My huntch is that it is a problem in the DB. Do you have a tool to test the DB. I dont want to lose all the data :(

**Comment by Art3c** [comment] 2021-01-20 16:48
> Hello @Art3c
> 
> It's weird 😕 you encountered the same issue while upgrading your shop to 1.7.7.0 (#22248)
> This issue has been fixed with 1.7.7.1, and even I didn't encounter it 😖
> 
> Well, could you please check my comment in your old issue [here](https://github.com/PrestaShop/PrestaShop/issues/22248#issuecomment-751258880) and follow my steps to resolve the problem manually.
> Sorry for the inconvenience 😓
> 
> I will ping the Developers Team to take a deep look in this issue.
> Ping @PrestaShop/prestashop-core-developers I believe this issue has been fixed, but it seems that there's some other conf could trigger the issue again 😖 could you please check it out.
> 
> Thanks in advance.
@hibatallahAouadni 
No luck on manually upgrading. How to solve? :(

**Comment by hibatallahAouadni** [comment] 2021-01-20 17:01
@Art3c could you please provide your log file, you can find it under your source project **admin**>**autoupgrade**>**tmp**>**log.txt**

**Comment by Art3c** [comment] 2021-01-20 17:21
> 
> 
> @Art3c could you please provide your log file, you can find it under your source project **admin**>**autoupgrade**>**tmp**>**log.txt**

[log.txt](https://github.com/PrestaShop/PrestaShop/files/5844106/log.txt)
@hibatallahAouadni This is the last log. If you want the log from 1.7.7.1 i need to upgrade again. It has been lost on restoring from backup.

**Comment by hibatallahAouadni** [comment] 2021-01-21 09:12
@Art3c ok thanks :wink: (don't upgrade again :stuck_out_tongue: )

Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers could please someone check the log file :pray: 

Thanks in advance :wink:

**Comment by PierreRambaud** [comment] 2021-01-21 09:56
I don't understand what happened, I see nothing relevant in logs.

**Comment by Art3c** [comment] 2021-01-21 10:16
@PierreRambaud @hibatallahAouadni any sugestions? I can send you a full backup of the server if it helps.

**Comment by hibatallahAouadni** [comment] 2021-01-21 10:20
Hello @Art3c 

Well we can't reproduce and nothing in logs :confounded: 
Really sorry but I think you may need help with your shop/configuration, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: I had to close this issue cause I can't help anymore, we tried our best but it seems your problem not related to Core PS :confused: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-21 10:20 UTC
Labels: Bug, BO, Can't reproduce, Autoupgrade, 1.7.7.1

**Comment by Art3c** [comment] 2021-01-21 14:20
@hibatallahAouadni can you help me migrate without loosing data?

**Comment by hibatallahAouadni** [comment] 2021-01-21 15:22
Hello @Art3c 

Unfortunally I can't :confused: you may follow this documentation to apply a perfect backup before upgrading your shop:

https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/backup/

As mentionned before, we only handle issues related to the Core and the natives modules on Github. If you want specific help, you have a few choices:
* the [community forums](https://www.prestashop.com/forums/) 
* the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack)
* the [official PrestaShop support](https://www.prestashop.com/support)

Thanks!
