### ISSUE TITLE
[IMPROVEMENT] Backoffice language improvements/bugs

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17521] opened 2020-02-05 23:47 UTC
**Scenario**
I have a store which sells only in different country or language. To be specific, we are a Czech company having a separate store on Slovak domain, for Slovakia market.

The language of the store is Slovak, the language of BO is set to Czech.
To do this, I have both Czech and Slovak languages installed, but only Slovak is active.

![Výstřižek](https://user-images.githubusercontent.com/6097524/73893237-5d31aa00-4879-11ea-9cb5-a230e4fa3948.JPG)

**PROBLEM 1**
I see the Czech versions of _lang entries of the data. In case there are no Czech versions, the BO is unusable.
What if we add an option to select, in which language we want to see the _lang entries by default?
Why the data is not shown in the default language of the store?
I do not want to set Slovak as a global language for the BO. Employees would have the admin in different language.

See the screenshot, when editing cart rules.
![Výstřižek](https://user-images.githubusercontent.com/6097524/73893378-b699d900-4879-11ea-82ec-82444af27e09.JPG)

**PROBLEM 2**
Why there are language selectors, if only one language is active?
![Výstřižek](https://user-images.githubusercontent.com/6097524/73893459-04164600-487a-11ea-86b0-e07e8630d7f1.JPG)

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-02-06 08:30
Hi @Hlavtox,

Thanks for your report.
Isn't the same issue reported here: 
https://github.com/PrestaShop/PrestaShop/issues/16626#issuecomment-560309227?

Thanks to check & feedback.

**Comment by Hlavtox** [comment] 2020-02-21 11:00
@khouloudbelguith The issue you referenced seems to be the same as the PROBLEM 1.

Do you think there is an issue for PROBLEM 2? I think there should not be the language selector, if there is only 1 active language.

Or mayyyyybe. What if you want to add second language to your store, but you want to prepare the texts first, before you activate it in FO. I think there should be maybe option for this?

**Comment by khouloudbelguith** [comment] 2020-02-21 11:05
Hi @Hlavtox,

Thanks for your feedback and for your suggestions.
Our product team should specify these cases.
Since this issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/16626#issuecomment-560309227, I will close it.
Please follow https://github.com/PrestaShop/PrestaShop/issues/16626 and you can add your suggestions.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-21 11:05 UTC
Labels: Improvement, BO, Duplicate, Languages, 1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-02-21 11:09
Duplicate of #16626
