### ISSUE TITLE
special characters and accents are not displayed correctly when placing an order

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23369] opened 2021-02-24 00:44 UTC
#### Describe the bug

special characters and accents are not displayed correctly when placing an order

#### Steps to Reproduce

1. make an order
2. write a comment (include accents or characters like º, #, @ etc...)
3. click on save
4. click on modify to see the comment

**Screenshots**

write this 
![image](https://user-images.githubusercontent.com/62474824/108927953-a8b02500-7641-11eb-8d8b-242e4036cbe6.png)

after saving
![image](https://user-images.githubusercontent.com/62474824/108927969-b1086000-7641-11eb-9cb5-fbcceaf4d5bd.png)

#### Additional information

* PrestaShop version: 1.7.6.4 (Can´t reproduce on 1.7.7.1 and 1.7.8.0)
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-24 08:32
Hello @alfonsolr09 

If the issue is fixed with PS1.7.7.1 and 1.7.8.0, it should be closed :wink: 

Thanks!

**Comment by alfonsolr09** [comment] 2021-02-24 08:33
Where is the PR ??? @hibatallahAouadni

**Closed as completed by hibatallahAouadni** 2021-02-24 08:32 UTC
Labels: Duplicate

**Comment by hibatallahAouadni** [comment] 2021-02-24 08:34
Duplicate of #9726

**Comment by hibatallahAouadni** [comment] 2021-02-24 08:34
@alfonsolr09 here's the PR #15840
