### ISSUE TITLE
Always showing mobile menu on v1.7.6.3

### ISSUE THREAD

**Issue by josedvd123** [PrestaShop/PrestaShop#17403] opened 2020-01-29 11:54 UTC
**Describe the bug**
I've just installed a new PrestaShop Store and when I got to the admin panel the mobile menu is always shown, even on a desktop and with fullscreen. My screen resolution is 1920 x 1080.

**To Reproduce**
1. Go to admin panel
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/24190668/73354367-d6d40180-4295-11ea-86b0-0ee418c98684.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-01-29 13:48
Hi @josedvd123,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & PS1.7.6.1 & PS1.7.6.2 & PS1.7.6.3.
I tried with Ipad4 & Ipad Mini 2
1. In the Dashboard Page, Orders page (not migrated page)
The menu mobile is always displayed & when we click on it => nothing happens (it should display or not the menu)
![image](https://user-images.githubusercontent.com/16067358/73360962-4a7d0b00-42a4-11ea-86f4-dbe71c47a491.png)
with PS1.7.5.2 => OK
![image](https://user-images.githubusercontent.com/16067358/73361381-253ccc80-42a5-11ea-9cfe-b3ea71633ed3.png)
2. In the products page (Migrated page) the menu is not well displayed => some items cannot be selected.
![image](https://user-images.githubusercontent.com/16067358/73361175-b65f7380-42a4-11ea-8d4e-f9c8a72ec772.png)

with PS1.7.5.2 => OK
![image](https://user-images.githubusercontent.com/16067358/73361452-43a2c800-42a5-11ea-8d52-d536b64070b7.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by josedvd123** [comment] 2020-01-29 14:12
Sorry, it was a conflict with a Chrome extension called "Letyshops". 
I just disabled the extension and now all is fine.
Thanks

**Comment by khouloudbelguith** [comment] 2020-01-29 14:20
@josedvd123, I will re-open the issue.
Issue reproduced with Ipad4 & Ipad Mini 2 using the https://www.browserstack.com.
https://drive.google.com/file/d/1z8xIZDZbpOcwK0A8UCdzUE0S1LmvkZ-T/view
Using the same device with PS1.7.5.2 => OK.
https://drive.google.com/file/d/1kDnofITgc-7CowHaWHNkv2-eewC-BHtg/view

Thanks!

**Comment by NeOMakinG** [comment] 2020-01-31 10:05
@khouloudbelguith , we follow Boostrap browser support (https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/) it means iOS7 is not supported as Safari on this iOS doesnt support css flex feature and more, it's not a bug, peoples using an iPad 4 or mini 2 should be on iOS 9 mini to be compatible, which is not even the latest version supported on these devices

(tested on ios 9 and it looks fine)

**Comment by khouloudbelguith** [comment] 2020-01-31 11:15
Hi,

As discussed with @NeOMakinG.
1. When using iOS7 => issue reproduced only with PS1.7.6
![image](https://user-images.githubusercontent.com/16067358/73534917-a66d9e00-4422-11ea-83bc-b49c3bb3f4a2.png)
With PS1.7.5.2 => Ok (regression)
![image](https://user-images.githubusercontent.com/16067358/73639555-e88a2000-466c-11ea-9d2e-917da9f72c47.png)

2. When using iOS9 => issue reproduced also with PS1.7.5.2 & PS1.7.6 (not a regression)
![image](https://user-images.githubusercontent.com/16067358/73534941-b7b6aa80-4422-11ea-8a26-79bdf9b01b8d.png)
![image](https://user-images.githubusercontent.com/16067358/73639730-330b9c80-466d-11ea-9af2-6acc2d917b40.png)

3. When using iOS10 => issue not reproduced
![image](https://user-images.githubusercontent.com/16067358/73535052-f8162880-4422-11ea-9631-625dcdde5f8f.png)
4. When using iOS10 => other bug reported fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/17459

![image](https://user-images.githubusercontent.com/16067358/73535130-1f6cf580-4423-11ea-8b37-bcab68a9dc97.png)

`Bootstrap supports the latest, stable releases of all major browsers and platforms. On Windows, we support Internet Explorer 10-11 / Microsoft Edge.
`

Ping @PrestaShop/prestashop-product-team @PrestaShop/prestashop-core-developers what do you think of this issue.
Do we need to support only iOS10 minimum?

Thanks!

**Comment by PierreRambaud** [comment] 2020-01-31 14:08
IHMO, we should ignore old browsers

**Comment by Progi1984** [comment] 2020-02-03 08:25
What is an old browser ?

Bootstrap support  the latest, stable release of browser... but which version ? Now ? or at the release date of the version of Bootstrap ?

**Comment by PierreRambaud** [comment] 2020-02-03 08:33
Depending on the bootstrap release we used.

**Comment by colinegin** [comment] 2020-02-03 15:27
I quite agree with other comments, i'm not in favor of working on it as it represents very very very few users (0,70% worldwide for ios10 and previous versions). But i'm still wondering why this used to be working on ios 7 with PS 1.7.5.2, do you guys have any idea ? @PrestaShop/prestashop-core-developers

**Comment by NeOMakinG** [comment] 2020-02-03 16:16
I just checked on 1.7.5.x, it's buggy too due to the use of display flex which is supported on the safari version of ios 10

![image](https://user-images.githubusercontent.com/14963751/73670023-ca421580-46a8-11ea-8881-0727458a0769.png)

There is no regression between 1.7.5.x and 1.7.6.x+

And we should not support browsers that are not supporting display flex (browsers < 2015 except IE11)

**Comment by khouloudbelguith** [comment] 2020-02-03 16:29
Hi @NeOMakinG,

I tried with iOSv7 & PS1.7.5.2 & it is OK
https://drive.google.com/file/d/1WMPM6S97WFiA7QzFMpuxIIePOPhlBjoN/view
Using the same device with PS1.7.6 => NOK
https://drive.google.com/file/d/1rnFEVRGx5t5r4Abf8W85S7mQ1dlFnYU_/view
I think this is a regression.

Thanks!

**Comment by NeOMakinG** [comment] 2020-02-03 16:53
My bad I was testing wrong, but I should reinstall prestashop on this branch to test, anyway it's also buggy on 1.7.7.x so I see what's wrong and it's flex support and more, which is something used everywhere, we need to support it, browsers not supporting it are way too outdated

**Closed as completed** 2020-02-10 13:08 UTC
Labels: Bug, Minor, BO, Won't fix, Regression, 1.7.6.0, 1.7.6.1, 1.7.6.2, 1.7.6.3
