### ISSUE TITLE
Missing menu icon only in back office dashboard

### ISSUE THREAD

**Issue by abcreationIT** [PrestaShop/PrestaShop#24450] opened 2021-05-11 11:14 UTC
#### Describe the bug

The icon to access the menu from mobile seems to be missing, only from the dashboard
As you can see in the official PrestaShop Live Demo, selecting the mobile view

[Official PrestaShop Live Demo for 1.7.7.4](https://demo.prestashop.com/#/en/back)

#### Expected behavior

I expect to see the icon for the mobile menu

#### Steps to Reproduce

Open the back office dashboard from a phone.
(I tried both from a computer with Safari's responsive design by setting an iPhone 8 and from my iPhone 12) 

**Screenshots**

From PrestaShop Live Demo but identical to any other mobile device:

Dashboard with missing icon menu
<img width="380" alt="Schermata 2021-05-11 alle 13 10 47" src="https://user-images.githubusercontent.com/33608547/117806300-6ec2e800-b25a-11eb-8b1b-344bc81cff78.png">

Other page (like Orders page) with the icon menu
<img width="376" alt="Schermata 2021-05-11 alle 13 11 07" src="https://user-images.githubusercontent.com/33608547/117806357-8ac68980-b25a-11eb-8b82-6fde3cda8bba.png">

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.28

**Comment by hibatallahAouadni** [comment] 2021-05-12 07:30
Hello @abcreationIT 

I was able to reproduce the issue with PrestaShop versions: 

- 1.7.7.4
- 1.7.7.3
- 1.7.7.2
- develop
- 1.7.8.x

But, I couldn't reproduce it with:

- 1.7.7.1
- 1.7.7.0
- 1.7.6.7
- 1.7.7.1 upgraded to 1.7.7.4 (magic :exploding_head: ) 

So, it's a regression! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by NeOMakinG** [comment] 2021-05-12 08:53
This issue is related to PSMetrics

**Comment by MatShir** [comment] 2021-05-24 16:10
Hi, 
The issue is transferred to the developers of the module PSMetrics. Thanks for the feedback, but the issue is not related to the project PrestaShop, so I will close the issue.

**Closed as completed by MatShir** 2021-05-24 16:10 UTC
Labels: Bug, develop, Minor, BO, Regression, Fixed, Front-end, Responsive, 1.7.7.2, 1.7.7.3, 1.7.8.x, 1.7.7.4
