### ISSUE TITLE
BlockReassurance missing alt-text for Icons. SEO / Google Problem

### ISSUE THREAD

**Issue by re-elko** [PrestaShop/PrestaShop#30650] opened 2022-12-22 13:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

All SEO Tools and also Google himself complaining, that the Icons of the BlockReassurance Module don't have alt-texts (only Title and description).

### Expected behavior

Maybe its possible to deposit an alt-text guilty for all Icons everywhere in the Module? Maybe here:

```
/modules/blockreassurance/classes/ReassuranceActivity.php

/**
* @param int $id_shop
*
* @return array
*
* @throws PrestaShopDatabaseException
*/
public static function getAllBlockByShop($id_shop = 1)
{
$result = [];

    $sql = 'SELECT * FROM `' . _DB_PREFIX_ . 'psreassurance` pr
        LEFT JOIN ' . _DB_PREFIX_ . 'psreassurance_lang prl ON (pr.id_psreassurance = prl.id_psreassurance)
        WHERE prl.id_shop = "' . (int) $id_shop . '"
        GROUP BY prl.id_lang, pr.id_psreassurance
        ORDER BY pr.position';

    $dbResult = Db::getInstance()->executeS($sql);

    foreach ($dbResult as $key => $value) {
        $result[$value['id_lang']][$value['id_psreassurance']]['title'] = $value['title'];
        $result[$value['id_lang']][$value['id_psreassurance']]['description'] = $value['description'];
        $result[$value['id_lang']][$value['id_psreassurance']]['url'] = $value['link'];
    }

    return $result;
}

```

### Steps to reproduce

1. Go to a product > Scroll to bloc reassurance
2. Inspect element
3. See that there's no `alt` nor `title`

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

block_reassurance v5.1.1

**Comment by florine2623** [comment] 2022-12-22 13:24
Hello @re-elko,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/24133.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed by florine2623** 2022-12-22 13:24 UTC
Labels: Bug, Duplicate, Invalid
