### ISSUE TITLE
Stock management - filter by supplier works only if selected default supplier for the product

### ISSUE THREAD

**Issue by diyan1234** [PrestaShop/PrestaShop#16269] opened 2019-11-04 21:58 UTC
Stock management can filter products by supplier only if selected default supplier for the products. It is not working if for any product is selected just "Choose the suppliers associated with this product" 

For example I have product A which I buy from supplier 1 and supplier 2. I associated it with both suppliers but if I didn't choose "Default supplier" then it will not be visible if I use Stock management filter by supplier.

This is observed in all Prestashop 1.7.x versions

**Comment by khouloudbelguith** [comment] 2019-11-05 08:08
HI @diyan1234,

Thanks for your report.
Yes, I have the same behavior as PS1.7.6.1 & PS1.7.5.2.
If a product doesn't have a supplier by default selected => filter doesn't work.
For example, I have a Test product with 2 suppliers ( there is no default supplier)
 
![image](https://user-images.githubusercontent.com/16067358/68189483-a5f07300-ffab-11e9-8160-c472fb91f672.png)
In the stocks page => no product found when we search with those suppliers 
![image](https://user-images.githubusercontent.com/16067358/68189517-c02a5100-ffab-11e9-9af5-207445e0e7a4.png)

Ping @PrestaShop/prestashop-product-team what do you think?
Can we change this behavior?

Thanks!

**Comment by marionf** [comment] 2019-11-05 08:30
Hello @diyan1234 

Your issue is a duplicate of #9580
Please follow this issue.

Regards

**Closed as completed by marionf** 2019-11-05 08:30 UTC
Labels: Improvement, BO, Duplicate, Stocks, Suppliers, 1.7.5.2, 1.7.6.1
