### ISSUE TITLE
Rounding errors - totally incorrectly calculated prices in the cart

### ISSUE THREAD

**Issue by futurowebpl** [PrestaShop/PrestaShop#25788] opened 2021-09-03 19:41 UTC
#### Describe the bug

Complete nonsense about calculating the prices in the cart.

This is the case with discount prices.

#### Expected behavior

400*0.19 = 76.00

Prestashop Calculation:

400*0.19 = 76.80

#### Steps to Reproduce

1. Add new example product and set a price of 0.24 for it and then you set a discount for the start price of 20% (percent discount) - its. 0.19 after discount.
2. Go to product page and add 400 pcs to the cart.
3. We have 76.80 in the cart instead of 76.00.
4. See screen.

Round mode and Round type its default settings.

Round mode = Round up away from zero, when it is half way there (recommended)
Round type = Round each line

**Every other type of rounding shows different nonsense** 

Round on each item - Then it is 76.00 for products - **but with this setting it shows omplete nonsense total with tax.**

**Screenshots**

![image](https://user-images.githubusercontent.com/43948137/132058092-52ba0f5c-0096-4c80-bbe7-63fd9c673285.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-09-06 08:59
Hello @futurowebpl 

Could you please check this issue #9779 it seems related to yours.
Please check and feedback.

Thanks!

**Comment by futurowebpl** [comment] 2021-09-06 11:16
Hello @hibatallahAouadni 

It's probably similar, this bug is still in 1.7.7. I have not tested this issue with 1.7.8 beta.

**Comment by hibatallahAouadni** [comment] 2021-09-08 17:20
Hello @futurowebpl 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9779. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-08 17:20
Duplicate of #9779

**Closed as completed by hibatallahAouadni** 2021-09-08 17:20 UTC
Labels: Bug, FO, Duplicate, Taxes and Prices, Shopping carts FO, 1.7.7.x
