### ISSUE TITLE
Problem with the order of Subcategories filters

### ISSUE THREAD

**Issue by chrisV92** [PrestaShop/PrestaShop#20910] opened 2020-09-09 06:15 UTC
Hello, I have a problem with the order of subcategories. It suppose to show subcategories filters by position but instead it shows random order. Also, When i Change language a category for example were 2nd in En it is 1st in the other language. At least tell me how to make order By    name ASC or DESC or how to make working by the positioning of categories. 

Thanks!

EDIT: ps_facetsearch modules I mean

**Comment by khouloudbelguith** [comment] 2020-09-09 08:42
Hi @chrisV92,

The problem is fixed if we use the icon in the position column. The product is selected and we can change the position and saved and all changes is validated.
Here's the PR: #14879 to fix the issue.
It is fixed in the PS1.7.7.0.
Since this PR correct the problem it's OK a New issue was created for the second issue: #15291
Your ticket is a duplicate of #14616
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-09 08:42
Duplicate of #14616

**Closed as completed by khouloudbelguith** 2020-09-09 08:42 UTC
Labels: Duplicate

**Comment by SimonGrn** [comment] 2020-09-09 08:45
Hello,

please think about using the template @chrisV92 , you deleted everything. For example, we don't know your PS version, your PHP version, or even the faceted search module version.
This does not help us **at all**.

Thank you.

**Comment by chrisV92** [comment] 2020-09-09 09:05
It is Something specific I Am saying I din't say in genera @khouloudbelguith . I said it doesnt work only on Filters. on Menu shows order correctly. 

My version is  1.7.6.5. I didn't delete everything @SimonGrn. Because I Tested without the override of ps_facetsearch and looks the same . ps_facetsearch is the latest 3.6.0 but it was 3.5.0 and because not worked i upgrade it to see if fix the problem.

I know about the ordering and how to order categories. Ps Facetsearch filters not showing at this ORDER.

**Comment by khouloudbelguith** [comment] 2020-09-09 09:08
@chrisV92,

>My version is 1.7.6.5. I didn't delete everything @SimonGrn.

You deleted the template of creating an issue on GitHub.
You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!

**Comment by chrisV92** [comment] 2020-09-09 09:11
Aaah Sorry I didn't understand it ok thank you
