### ISSUE TITLE
Prices in products combinations administration

### ISSUE THREAD

**Issue by dreammeup** [PrestaShop/PrestaShop#12147] opened 2019-01-14 13:30 UTC
Hi,

On PrestaShop 1.7.4.4, there is something strange about the prices in the combinations.

![combinations1](https://user-images.githubusercontent.com/4540601/51115527-d0005b00-1808-11e9-9bcc-86a7b3f99a3d.png)

In the combinations list, you only have the final price HT, but merchants may prefer to have the price TTC ?

![combinations2](https://user-images.githubusercontent.com/4540601/51115525-d0005b00-1808-11e9-82d8-09a3dc5110c3.png)

In the modification, it is hard for a merchant to know what will be the price displayed TTC, there is only the HT.

And they don't have the original price of the product display, the final price is not updated in real time.

Best regards,

**Comment by khouloudbelguith** [comment] 2019-01-15 10:42
Hi @dreammeup,

In the next release PS1.7.6, price with TAX will be displayed on the backend product list.
Here's the PR: #11484 to add this feature.
Your ticket is a duplicate of #11479
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-15 10:42
Duplicate of #11479

**Closed as completed by khouloudbelguith** 2019-01-15 10:42 UTC
Labels: Duplicate
