### ISSUE TITLE
ID column is too large

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#24915] opened 2021-06-11 06:56 UTC
#### Describe the bug

Hello,

I noticed not long ago that the ID column has been changed even though I haven't touched anything. Do you know why?

Thanks

**Screenshots**

![image](https://user-images.githubusercontent.com/25744417/121644042-d1deaf00-ca92-11eb-92fd-f639cc96b9cb.png)

#### Additional information

* PrestaShop version: 1.7.6 and 1.7.7
* PHP version: 5.6

**Comment by hibatallahAouadni** [comment] 2021-06-11 07:19
Hello @ShaimyWinda 

Could you please upgrade your PHP version to 7.2 cause PS1.7.7 is not compatible with PHP5.6 (see our [system requirement](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
I encountred this issue but after clearing cache of PrestaShop and the browser, it's gone :slightly_smiling_face: 
So, please clear your cache.

Please check and feedback.
Thanks!

**Comment by ShaimyWinda** [comment] 2021-06-11 07:36
Hello @hibatallahAouadni 

I am not yet at version 1.7.7 of Prestashop but at 1.7.6.
I'm going to upgrade soon and at the same time, change the version of Php

I deleted the cache but nothing happens 
Thanks!

**Comment by MatShir** [comment] 2021-06-11 08:06
The bug seems to be fixed in the 1.7.8. @hibatallahAouadni could you confirm ? :)

**Comment by hibatallahAouadni** [comment] 2021-06-11 10:40
Hello,

@MatShir I didn't manage to reproduce the issue neither with 1.7.6 nor 1.7.7 nor 1.7.8 :disappointed: 
@Robin-Fischer-PS reproduced it once but when he cleared cache, the issue is gone
The only one still reproduce the issue is @boubkerbribri 
So @boubkerbribri could you please confirm if you still encounter this issue on 1.7.8

Thanks in advance :pray:

**Comment by boubkerbribri** [comment] 2021-06-11 12:08
I confirm that I still have the issue, but it seems that it's a Chrome problem.
Chrome version: 91.0.4472.77

**Comment by hibatallahAouadni** [comment] 2021-06-11 12:31
@boubkerbribri indeed it's a Chrome regression :sweat_smile: 
I didn't encounter the issue cause my Chrome version is 89.0.4389.82
Changing the issue status to **`TBS`** as @NeOMakinG still investigate it :wink:

**Comment by jpcoke** [comment] 2021-06-12 15:12
Hi
I have PHP: 7.2.34, and in both 1.7.7.3 and 1.7.7.4 have the same issue in chrome.

I´ve just updated to Chrome  91.0.4472.101, but remains the same...

**Comment by NeOMakinG** [comment] 2021-06-14 08:58
I did reproduce even on develop, so I provided a PR

https://github.com/PrestaShop/PrestaShop/pull/24952

**Closed as completed** 2021-06-18 10:01 UTC
Labels: Bug, develop, Minor, BO, Fixed, Front-end, 1.7.6.x, PR available, 1.7.7.x

**Comment by RubenMartins** [comment] 2021-07-15 15:35
Can this be backported to all 1.7 versions and not just 1.7.9.x?

**Comment by matks** [comment] 2021-07-15 16:08
> Can this be backported to all 1.7 versions and not just 1.7.9.x?

Unfortunately no, that would be against our backport strategy. You can do it on your shop but we will not do it on the official 1.7 releases.

**Comment by RubenMartins** [comment] 2021-07-15 16:13
When I say backported I mean to a new latest version for each supported subversion for example: 1.7.7.6 and 1.7.6.10, and of course the 1.7.8.0?
Or this will only apply to 1.7.9.x?

**Comment by matks** [comment] 2021-07-15 16:18
> When I say backported I mean to a new latest version for each supported subversion for example: 1.7.7.6 and 1.7.6.10, and of course the 1.7.8.0?
> Or this will only apply to 1.7.9.x?

I confirm this bug will not be backported to 1.7.7.6 or 1.7.6.10 and even 1.7.8.0 .
We have tried this in the past, and backporting a bugfix has been proven sometimes a risky move, when the code being modified is not identical between versions. Moreover the backport is considered like a new change which means it is reviewed and tested just like any change. So it would "consume" three times the same amount of time and energy it took - for the validation part - that for this bugfix.

We hope to have a better backport strategy in the future, but given our current resources and scope we cannot go this far 😞  .
