### ISSUE TITLE
PrestaShop 1.7.6.2 was not fully compatible with PHP 7.2

### ISSUE THREAD

**Issue by sadlig** [PrestaShop/PrestaShop#16701] opened 2019-12-05 11:32 UTC
**Describe the bug**
As mentioned [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements) it's recommended to use PHP 7.2 for PrestaShop versions 1.7.5 ~ 1.7.6.

Unfortunately the Console component is not compatible with this version.

**To Reproduce**
1. Open Terminal
2. Place yourself in the PrestaShop directory `cd /path/to/prestashop.1.7.6.2`
3. Execute this command `php bin/console`
4. See error : `PrestaShopException in /path/to/prestashop.1.7.6.2/classes/db/Db.php line 302
`

**Screenshots**
My PHP version : 
![Capture du 2019-12-05 12-16-15](https://user-images.githubusercontent.com/710603/70230654-116b6300-1759-11ea-9c8f-753c277eb123.png)

Command result with PHP7.2 : 
![Capture du 2019-12-05 12-18-15 (1)](https://user-images.githubusercontent.com/710603/70231365-7bd0d300-175a-11ea-84fc-9ec89ff1dc98.png)
:-1: 

Command result with PHP7.1 : 
![Capture du 2019-12-05 12-27-45 (1)](https://user-images.githubusercontent.com/710603/70231545-d2d6a800-175a-11ea-9dd5-739faa0e9d74.png)
:+1: 

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by matks** [comment] 2019-12-05 13:15
@sadlig I just tried, and there is no issue on my 1.7.6.2 install 😮. Can you tell us from php logs what exact Exception is being thrown ? Is it a fresh 1.7.6.2 install or a shop that underwent some modifications ?

I'm using php7.2.10

**Comment by khouloudbelguith** [comment] 2019-12-05 13:21
Hi @sadlig, @matks,

It is ok also, in my side
![image](https://user-images.githubusercontent.com/16067358/70238790-4cc25d80-176a-11ea-8418-b38337e10af8.png)
I'm using PHP 7.2.10
It is OK with PHP 7.2.22 also.

Thanks!

**Comment by sadlig** [comment] 2019-12-05 13:25
@matks This is not a new installation, it's a store I upgraded from 1.7.5 to 1.7.6.2

**Comment by khouloudbelguith** [comment] 2019-12-05 13:27
@sadlig, what is the exact version did you use before the upgrade?
What is the exact version of the 1-click upgrade did you use?
Have you any errors during the upgrade?

Thanks!

**Comment by sadlig** [comment] 2019-12-05 13:32
@khouloudbelguith No error during upgrade. My previous PrestaShop version was 1.7.5.2 and I'm using 1-Click upgrade v4.10.0

**Comment by khouloudbelguith** [comment] 2019-12-05 14:02
@sadlig, I did not manage to reproduce the issue with PS1.7.5.2 & with PS1.7.6.2 after an upgrade from a previous version
I attached a screen record
https://drive.google.com/file/d/16Q_CzlfqL07jwaC0X-7NeY7wA8HG2hqD/view
Thanks to check & feedback.

**Comment by sadlig** [comment] 2019-12-05 14:21
@khouloudbelguith thanks for your screencast, I've just tested on a fresh install, it works fine.
I will investigate why it does not work for my shop. Is it possible that a module causes an error at this level?

**Comment by khouloudbelguith** [comment] 2019-12-05 14:22
@sadlig, you need to check your PHP logs to find the exact Exception.

Thanks!

**Comment by matks** [comment] 2019-12-05 14:45
> @khouloudbelguith thanks for your screencast, I've just tested on a fresh install, it works fine.
> I will investigate why it does not work for my shop. Is it possible that a module causes an error at this level?

Your screenshot indicates an exception thrown from class `Db` at line 302. This line is:
```
/**
     * Returns the best child layer database class.
     *
     * @return string
     */
    public static function getClass()
    {
        $class = '';
        if (PHP_VERSION_ID >= 50200 && extension_loaded('pdo_mysql')) {
            $class = 'DbPDO';
        } elseif (extension_loaded('mysqli')) {
            $class = 'DbMySQLi';
        }

        if (empty($class)) {
            throw new PrestaShopException('Cannot select any valid SQL engine.');
        }

        return $class;
    }
```

So it seems your shop was unable to find out the php extensions needed to connect to mysql.
Maybe check your php.ini for php7.2 ?

**Comment by khouloudbelguith** [comment] 2020-01-06 07:49
Hi @sadlig,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-06 07:49 UTC
Labels: Bug, No change required, 1.7.6.2
