### ISSUE TITLE
Update shipping fees after selecting a carrier

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#20706] opened 2020-08-25 10:43 UTC
#### Describe the bug

The shipping fees don't have the same behaviour depending on the actions you take. They don't display the same amount always. When you update the page the shipping rates change.

#### Expected behavior

Display the correct amount always. Refresh shipping rates when a new carrier is selected.

#### Steps to Reproduce

1. Create a cart rule with carrier restriction and free shipping:

![image](https://user-images.githubusercontent.com/15104724/91164858-0cc45180-e6d0-11ea-9100-a3a49329ddd1.png)
_Don't select default carrier to check bug better_

![image](https://user-images.githubusercontent.com/15104724/91164373-37fa7100-e6cf-11ea-8301-6c48ea9feeb7.png)

2. Add a product to the cart and proceed to checkout
3. Change carrier to Carrier 2. Rule is applied but shipping rate is not updated:
![image](https://user-images.githubusercontent.com/15104724/91165011-45642b00-e6d0-11ea-83c3-445ee1ce536b.png)

4. Update page. Shipping rate is updated:
![image](https://user-images.githubusercontent.com/15104724/91165041-52811a00-e6d0-11ea-8f4c-2c91d1ba3c87.png)

5. Change carrier. Rule is removed but shipping rates not updated:
![image](https://user-images.githubusercontent.com/15104724/91165077-62006300-e6d0-11ea-91d6-2781b60e7ebf.png)

6. Refresh page:
![image](https://user-images.githubusercontent.com/15104724/91165214-996f0f80-e6d0-11ea-9c0e-d49eda548f3b.png)

**Comment by khouloudbelguith** [comment] 2020-08-25 11:01
Hi @idnovate,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15458#issuecomment-529451147
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-25 11:01
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/15458#issuecomment-529451147

**Comment by khouloudbelguith** [comment] 2020-08-25 11:02
Hi @idnovate,

You can follow this epic for more details: https://github.com/PrestaShop/PrestaShop/issues/13823

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-25 11:01 UTC
Labels: Duplicate
