### ISSUE TITLE
Installation of module in Carriers page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11388] opened 2018-11-14 14:26 UTC
**Describe the bug**
Try to install Mondial relay or Chronopost in Carrier page
The module isn't installed and you are redirected to Module Catalog page because errors are not displayed in legacy pages
Should be solved when the carrier page will be migrated

**To Reproduce**
1. Go to Delivery > Carriers 
2. Click on install for Mondial Relay or Chronopost
3. You are redirected to module catalog page without any message

**Additionnal information**
PrestaShop version: 1.7.2, 1.7.5
PHP version: N/A

**Comment by marionf** [comment] 2018-11-14 14:28
This issue happens because Mondial Relay and Chronopost can't be installed

![capture d ecran_619](https://user-images.githubusercontent.com/13449658/48489245-e5660280-e822-11e8-9492-54e57cb7c780.png)

![capture d ecran_618](https://user-images.githubusercontent.com/13449658/48489246-e5660280-e822-11e8-9cd1-d977afc88e3e.png)

The error should be displayed on Carrier page and I shouldn't be redirected to Module Catalog page

**Comment by gumballerss** [comment] 2019-04-29 09:12
I've the same issue with the last version of Chronopost.

**Comment by khouloudbelguith** [comment] 2019-04-29 12:52
Hi @stan-smith,

This issue is added to our bug roadmap so that it’s fixed.
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.
Thanks!

**Comment by colinegin** [comment] 2019-09-25 16:30
I can't reproduce this issue. Instead I have a error 500, but then if I refresh i am actually in the configuration page of the module. Do you have the same behaviour @khouloudbelguith ?

**Comment by khouloudbelguith** [comment] 2019-09-26 09:26
Hi @colinegin,

No, In fact, I have the same behavior reported by @marionf: redirection to module catalog page without any message
https://drive.google.com/file/d/1OqU0sBZ8jZrnb0GQgHUSdxDw-gCNSQ8D/view

https://user-images.githubusercontent.com/1533248/154445002-3c722b6c-d489-4a82-840f-540e3d4808e5.mp4



Thanks!

**Comment by MatShir** [comment] 2020-06-10 10:27
Hey @Matt75,
Do you know if this issue is related to MBO ?

**Comment by Matt75** [comment] 2020-06-10 10:44
This issue occur when MBO is not installed so it’s a Core issue 👌🚪

**Comment by Progi1984** [comment] 2022-02-15 14:40
@MatShir I think this issue should be sent to the MBO repository. 

Ping @intraordinaire.

**Comment by intraordinaire** [comment] 2022-02-17 12:36
We tried to reproduce on a 1.7.6.8 version with @sowbiba.
The module Chronopost installation does not work, but, we are not redirected, and the error is displayed correctly in the Carriers page.

**Comment by MatShir** [comment] 2022-02-17 12:59
@intraordinaire Maybe check on the 1.7.8.3 to be sure ? 
In any case, I'm closing the issue. It is not related to the core. Feel free to copy it for the MBO repo :)

**Closed as completed by MatShir** 2022-02-17 12:59 UTC
Labels: Bug, Trivial, BO, 1.7.5.0, MBO, 1.7.6.0, 1.7.6.1, Invalid
