### ISSUE TITLE
Error when trying to delete a product

### ISSUE THREAD

**Issue by jsuarez** [PrestaShop/PrestaShop#12606] opened 2019-02-18 02:30 UTC
When i try to delete some product, the screen locks and the product is not deleted

**To Reproduce**
1. Go to 'catalog->products'
2. Click on 'the action dots at the right of the product list' and then delete (or selecting all the products through the "select all" checkbox and then making a masive delete)
3. And nothing occurs and the screen not working anymore (to scroll, click or nothing), and into the console is not showing anithing

I'm working on a test subdomain: latijera.mydesign.com.ar

PrestaShop version: 1.7.5.0
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment] 2019-02-18 07:45
Hi @jsuarez,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-19 13:55
Hi @jsuarez,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-19 13:55 UTC
Labels: BO, No change required, 1.7.5.0
