### ISSUE TITLE
SEO error ItemList position product list

### ISSUE THREAD

**Issue by mark-app** [PrestaShop/PrestaShop#27725] opened 2022-02-18 10:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Prestashop template file themes/classic/templates/_partials/microdata/product-list-jsonld.tpl the position is wrong. Position should always start with 1 not 0.

### Expected behavior

First item should have position 1.

### Steps to reproduce

1. Go to FO to a category page with products.
2. Show the source code
3. Search for @type": "ItemList
4. First item will have the "position": 0,

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

classic theme

**Comment by mark-app** [comment] 2022-02-18 10:58
The Problem can be fixed.

Go to the theme file themes/classic/templates/_partials/microdata/product-list-jsonld.tpl

Change this:

"position": {$position},

To:

"position": {$smarty.foreach.productsForJsonLd.iteration},

**Comment by HanaRebaiQA** [comment] 2022-02-18 11:50
Hello @mark-app 

Thanks for your report!
Could your please provide us a screen-shot/screen-record to be able to find the exact element location of `@type": "ItemList` ? 

Thank you!

**Comment by mark-app** [comment] 2022-02-18 12:20
<img width="994" alt="Schermafbeelding 2022-02-18 om 13 19 13" src="https://user-images.githubusercontent.com/6554157/154681937-e14af239-123e-444b-8c27-fc0d7701fd28.png">

url : https://mydomain.com/3-clothes

**Comment by florine2623** [comment] 2022-02-18 16:10
Hello @mark-app ,

I have reproduced your issue in PS 1.7.8.3 and on develop branch, so I can confirm that this behavior is indeed a bug.

<img width="871" alt="Screenshot 2022-02-18 at 17 06 22" src="https://user-images.githubusercontent.com/16019289/154718755-9552e04d-1205-4921-b3c5-637c05e3cb04.png">

It should be like the `"@ type": "BreadcrumbList"` above.

Could you create a PR as you know how to fix the issue ? ^^

Thank you

**Comment by hibatallahAouadni** [comment] 2022-02-21 19:24
Hello @mark-app 

Your issue is similar to this one #15554 
Could you please check it and feedback.

Thanks!

**Comment by mark-app** [comment] 2022-03-01 13:42
@hibatallahAouadni  No it isn't. This one is only about the first item with position 0 for the item list. This should be 1 instead of 0.

**Comment by HanaRebaiQA** [comment] 2022-03-03 10:32
Hello @mark-app 

I was able to reproduce your issue with **PS1783**.

https://user-images.githubusercontent.com/92912932/156546521-a80b05cf-b77f-45c6-91db-e93130680ea1.mp4


But, i did not reproduce it with **PS1778**. 

https://user-images.githubusercontent.com/92912932/156546592-04b0403c-0017-4be2-88be-fcabdbf647bd.mp4


This issue is caused by this [PR](https://github.com/PrestaShop/PrestaShop/pull/23151) which is merged on PS1780
The problem is exactly in this line : 
![image](https://user-images.githubusercontent.com/92912932/156546306-9317ac46-67be-4c04-ba0e-150fbfb779b3.png)

So, **it's a regression on PS1780**.
We will come back to you with QA feedback as soon since the available PR is on Waiting for QA now.

Thanks!

**Comment by Progi1984** [comment] 2022-03-14 10:53
Fixed by me in #27814 and tested by @khouloudbelguith

**Closed as completed by Progi1984** 2022-03-14 10:53 UTC
Labels: Bug, Minor, FO, Categories, SEO & URLs, Regression, Fixed, PR available, Verified, 1.7.8.3
