### ISSUE TITLE
Credit slip total tab in HTML Template doesn't use the right data for display

### ISSUE THREAD

**Issue by Gstieven** [PrestaShop/PrestaShop#19214] opened 2020-05-19 16:08 UTC
#### Describe the bug

My problem seems to be linked to #16826 and #18319

Credit slip PDF generation seems to be pretty messy. It uses both order and order slip data to generate PDF in HTML Template. More specifically, in the total tab, the total is based on the order total (total_paid_tax_incl), which is not just read in database but recomputed dynamically in the HTMLTemplateOrderSlipCore class.

In most cases the result is fine, but when initial order includes a voucher, and when a back office user choose to fully refund an order, this discount code is not taken in account in the credit slip PDF (only), total seems to be okay in the order slip table.

There is some code in HTMLTemplateOrderSlipCore planned to handle cart rule but it isn't used since order_slip_type = 2 in this case. It only handles order slips with order_slip_type = 1. I'm not sure to well understand difference between this two types.

Actually, order slip "total_products_tax_incl" could be used since it take in account a possible voucher and the back office user choice to include it or not in the credit slip.

#### Expected behavior

Display a correct total price in credit slip PDF handling voucher and back office user choice.

#### Steps to Reproduce

1. Create an order from Front Office using a voucher that reduce the whole order price (payment module involved doesn't matter).
2. Update order state to "Payment accepted" in Back office if needed.
3. Click on "Standard refund".
4. Scroll down and select all products in list to include them in credit slip.
5. Check "Generate a credit slip", "Repay shipping costs" and "Exclude amount of initial voucher" (I think this last radio button should be the default choice by the way since you shouldn't refund more than you got).
6. Click on "Refund products"
7. Download corresponding credit slip PDF.
8. Total amount doesn't include voucher (but order slip line in database does)

**Screenshots**

Total order (45.80 €) with voucher and refund option selected :
![order_slip](https://user-images.githubusercontent.com/25683672/82348202-d1dbbf00-99f8-11ea-9dc8-590d03b9711c.png)

Credit slip PDF content, total doesn't handle voucher like it should (49.39 €) :
![order_slip_pdf](https://user-images.githubusercontent.com/25683672/82348371-0f404c80-99f9-11ea-9f3a-d2de0dc42fb5.png)

User choice is well stored in database in order slip table (41.31 € + shipping cost = 45.80 € , it's okay) :
![order_slip_db](https://user-images.githubusercontent.com/25683672/82349111-00a66500-99fa-11ea-8b62-8fecccba4928.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by LouiseBonnard** [comment] 2020-05-20 16:47
Dear @Gstieven, thank you for creating this issue! We can reproduce it but we still need some information: could you please let us know what is the difference with PR #18319? Or is it a duplicate? Thanks in advance!

**Comment by Gstieven** [comment] 2020-05-25 09:52
I'm not sure since the ticket indicates that the bug occurs from 2 articles
and involves other aspects. But yes it seems basically very linked.

Le mer. 20 mai 2020 à 18:47, LouiseBonnard <notifications@github.com> a
écrit :

**Comment by Gstieven** [comment] 2020-05-25 10:01
I'm not sure since the ticket indicates that the bug occurs from 2 articles and involves other aspects. But yes it seems basically very linked.

**Comment by florine2623** [comment] 2020-05-29 12:58
Hi @Gstieven ,
I would advise you to keep an eye on https://github.com/PrestaShop/PrestaShop/issues/18319. That issue is already in our roadmap. Once it is fixed, your issue will certainly be fixed as well.
For now, i will close your issue as it is a duplicate.
Thanks!

**Comment by florine2623** [comment] 2020-05-29 12:58
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/18319

**Closed as completed by florine2623** 2020-05-29 12:58 UTC
Labels: Bug, BO, Duplicate, Order, Credit notes, Discounts, No change required
