### ISSUE TITLE
When Home category is not displayed, you can't edit child categories

### ISSUE THREAD

**Issue by Jeremy-VERNET** [PrestaShop/PrestaShop#15040] opened 2019-08-08 14:27 UTC
**Describe the bug**
When you make the Home category not displayed (so it is not shown in breadcrumb or menus), you can't change a child category name, it triggers CategoryConstraintException number 6 (when invalid parent id is supplied).

Indeed, the dropdown "Parent category" appears empty.

It is not a major issue but to avoid this, you have to make every changes in your categories and make the Home category not displayed at the end of your process.

**Additional information**
PrestaShop version: 1.7.7.0
PHP version: 7.2.4

**Comment by khouloudbelguith** [comment] 2019-08-08 14:34
Hi @Jeremy-VERNET,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15030 to fix the issue.
Your ticket is a duplicate of #14790
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-08 14:34
Duplicate of #14790

**Closed as completed by khouloudbelguith** 2019-08-08 14:34 UTC
Labels: Duplicate, Categories
