### ISSUE TITLE
Error 500 on Accessing Logs in Advanced Settings [PS 1.7.5.1]

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#15860] opened 2019-10-07 20:18 UTC
**Describe the bug**
I get an error 500 on accessing Advanced Settings > Logs to see employee logs on store changes.

**To Reproduce**
- Go to Advanced Settings;
- Click on Logs

**Screenshots**
![2019-10-07_16h14_43](https://user-images.githubusercontent.com/16780421/66345242-adc1e680-e91d-11e9-870b-8f91eeb3c2f8.png)

**Additional information**
PrestaShop version: 1.7.5.1 (updated 7 months ago with 1-click-update from v1.7.5.0
PHP version: 7.2.23

I do clear cache; deleted var\cache\prod and var\cache\dev, same results.

Here Log's from Symphony after debug "on"
`An exception occurred while executing 'SELECT l.*, e.email, CONCAT(e.firstname, ' ', e.lastname) as employee FROM ps_log l LEFT JOIN ps_employee e ON l.id_employee = e.id_employee WHERE (e.lastname LIKE :employee OR e.firstname LIKE :employee) AND (l.date_add BETWEEN :date_from AND :date_to) ORDER BY id_log desc LIMIT 10 OFFSET 0' with params ["2019\/10\/01", "2019\/10\/07"]:`

`Value for :employee not found in params array. Params array key should be "employee"`

`in vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php (line 131)`

`if ($driver instanceof ExceptionConverterDriver && $driverEx instanceof DriverException) {            return $driver->convertException($msg, $driverEx);        }        return new self($msg, 0, $driverEx);    }    /**     * @param \Doctrine\DBAL\Driver     $driver     * @param \Exception $driverEx
`

Thanks

**Comment by khouloudbelguith** [comment] 2019-10-08 08:07
Hi @8ternity,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14926 to fix the issue.
Your ticket is a duplicate of #14785
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-08 08:07
Duplicate of #14785

**Closed as completed by khouloudbelguith** 2019-10-08 08:07 UTC
Labels: Duplicate, Logs

**Comment by 8ternity** [comment] 2019-10-08 12:47
The fix already applied (see attachment):

![image](https://user-images.githubusercontent.com/16780421/66396618-19509600-e9a8-11e9-8c77-0019f813326e.png)

It's happen on selecting date, but after review your fix, the fix already applied on the updated 1.7.5.1.

**Comment by khouloudbelguith** [comment] 2019-10-08 12:51
@8ternity, the issue is fixed in the PS1.7.6.1.
You can find the fix file here: https://github.com/PrestaShop/PrestaShop/pull/14926/files
No, it is different, there is no array.

```
 $qb->setParameters(array(
       'date_from' => $filterValue['from'],
        'date_to' => $filterValue['to'],
));
```

changed to 

```
$qb->setParameter('date_from', $filterValue['from']);
$qb->setParameter('date_to', $filterValue['to']);
```

Thanks!

**Comment by 8ternity** [comment] 2019-10-08 14:07
Resolved with fix. Thanks
