### ISSUE TITLE
[DOM] Found 2 elements with non-unique id

### ISSUE THREAD

**Issue by GutImedia** [PrestaShop/PrestaShop#10785] opened 2018-10-01 08:31 UTC
My backoffice is very long when I go on products (Catalog > Product)
I have these errors in my search console (only in backoffice):

See attached file

Prestashop 1.7.4.2
![searchconseil-backoffice-prestashop1 7 4 2](https://user-images.githubusercontent.com/43534581/46277988-38327600-c565-11e8-9c1f-acff9ac08f14.jpg)

Informations sur votre serveur Linux #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.0.30-0+deb9u1
Limite de mémoire : 256M
Temps maximal d'exécution : 90
Taille max. pour envoi de fichiers : 200M

**Comment by khouloudbelguith** [comment] 2018-10-01 08:43
Hi @GutImedia,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10469
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 08:44
Duplicate of #10469

**Closed as completed by khouloudbelguith** 2018-10-01 08:44 UTC
Labels: Duplicate
