### ISSUE TITLE
BO product-list V2 (both single and multistore) - final price with tax missing applied special prices

### ISSUE THREAD

**Issue by darkWolf-PR** [PrestaShop/PrestaShop#35072] opened 2024-01-17 15:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Product list (using V2 product page) n BO does not show final (selling) price with tax.
Same problem also in multistore(in actual 8.1.3).

Made few screens (PS 8.1.2)-sorry, it´s in czech, only lang installed.

Product list - all prices are the same, the last one should be different
![product_list_price](https://github.com/PrestaShop/PrestaShop/assets/17412966/ab74f8bf-8ba2-468d-be49-32bed7f3778d)

This is that last product config with added special price, you can see it is applied on everything and without time limitation:
![product_price_setup](https://github.com/PrestaShop/PrestaShop/assets/17412966/d1bfef10-6509-4191-b19a-687a0f28348d)

And here is price how it is shown in FO
![front_office_product_price](https://github.com/PrestaShop/PrestaShop/assets/17412966/329f6b6f-db90-44fb-98e0-0f4e027e1b47)

There is this pull: https://github.com/PrestaShop/PrestaShop/pull/11484
It states as solved, but it is actually not. Just like the last comment in there says - https://github.com/PrestaShop/PrestaShop/pull/11484#issuecomment-1407725230

### Expected behavior

The price with tax should be showing the final, actual, selling price of the product. Like it did in old PS 1.6. Price with tax, that is not actual selling price of that product is completely useless.

### Steps to reproduce

1. Go to product-list (V2)
2. Set up new product, set tax, add price with tax(let PS count tax excluded price) and save
3. Add some special price applied to everyone and everywhere
4. Check product-list in BO

### PrestaShop version(s) where the bug happened

8.1.2, 8.1.3

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by florine2623** [comment] 2024-01-18 09:47
Hello @darkWolf-PR ,

This is not a bug.
The BO > Product listing will not show the specific price. But the Retail price.
Imagine if you have 5 specific prices, it wouldn't be possible to choose what price to display.

In the BO, the price displayed in the retail price.
<img width="1023" alt="Screenshot 2024-01-18 at 10 45 27" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7bfd0671-21dd-401e-b80f-d9ea6d56f6ae">
<img width="1202" alt="Screenshot 2024-01-18 at 10 45 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d0db59d9-6b4f-4cac-8ae0-0a089ffdf516">

In FO the product price is correct too :
<img width="943" alt="Screenshot 2024-01-18 at 10 46 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b18721ed-2c7c-4a46-b75a-725913004ce3">

I'm closing the issue as it is not a bug.

**Closed as completed by florine2623** 2024-01-18 09:47 UTC
Labels: Bug

**Comment by darkWolf-PR** [comment] 2024-01-18 12:19
@florine2623 so, in PS 1.6, it was possible, it was not a custom change and it worked - so whats actual upgrade of PS 8? 

Our shop stuff needs to see the real actual selling prices. You probably never used that eshop in real environment, but this price that it is showing now is completely useless. Because it´s not the real selling price. That price means nothing, than column can pretty much be removed, nothing will change.

**Comment by HelixMartin** [comment] 2025-04-16 07:41
So bascailly it is different that it was in 1.6 and 1.7?

How exacly are admin suppose to check prices, having an overview over the products if the price in the back is not listed as current? Pretty much useless behaviour.

So to check current price of a product in BO, admin should 
- look up the product,
- take the retail price,
- look up which specific price is active and subtract it from the retail price?

I mean who have the time?

Why did this change from the 1.7 behaviour? It does not make sense ....

**Comment by HelixMartin** [comment] 2025-04-16 08:11
How come do search for the products, give the current price in the back end, but not catalog listing?
