### ISSUE TITLE
Could not download remote file (installation and localization pack file) when upgrade or install new fresh Prestashop

### ISSUE THREAD

**Issue by ets-soft** [PrestaShop/PrestaShop#18336] opened 2020-03-27 01:10 UTC
#### Describe the bug

Cannot upgrade to new version because not able to download Prestashop installation file.
Function **public function copy($originFile, $targetFile, $overwriteNewerFiles = false)** is not working!
The problem started to happens (not always but very often) when the 1.7.6.4 was released, looks like there is a problem with remote server, it's not stable, sometimes it happens (many of our clients complaint about this issue, and it happens to us always), please check the stability of the remote server where you store Prestashop installation file. 
We also see the download is also not working for localization package when installing a new fresh Prestashop website.

#### Expected behavior

The remote server should always return download file when the copy function is called.

#### Steps to Reproduce

Try to upgrade an old Prrestashop website to Prestashosp 1.7.6.4, you may be stopped at downloading Prestashop installation file step.

#### Additional information

* PrestaShop version: 1.7.6.3

**Comment by sarahdib** [comment] 2020-03-27 11:49
Hello @ets-soft 

Thank you for your feedback !

I didn't reproduce the problem. The upgrade is OK and localization pack is OK.

Can you give us more detail about the issue and provide us some screenshot ?

Thank you

**Comment by matks** [comment] 2020-03-27 13:54
@ets-soft You can see the monitoring of PrestaShop webservices here http://status.prestashop.com/

There is not a lot of outages ... however there is something we noticed. Sometimes we have longer response times because of huge traffic, and your server or PrestaShop may timeout because the response time is longer.

In Europe we are fine but **depending on your country location**, the additional network delay may make your server timeout and/or PrestaShop timeout; considering the resource to be unreacheable.

**Comment by sarahdib** [comment] 2020-04-28 09:34
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-04-28 09:34 UTC
Labels: Bug, BO, Localization, Autoupgrade, No change required, 1.7.6.3
