### ISSUE TITLE
Notice-message while doing an order refund

### ISSUE THREAD

**Issue by Ned201** [PrestaShop/PrestaShop#12455] opened 2019-02-06 12:06 UTC
**Describe the bug**
While doing a order refund, the next notice-message occurs:
Notice on line 1029 in file ../controllers/admin/AdminOrdersController.php [8] Undefined variable: voucher

**To Reproduce**
1. Enable PrestaShop Debug
2. Enable returns under 'Customer service' --> 'Merchandise Returns'
3. Select an order and if not yet done, change the order-status to 'Delivered'
4. Select  'Return products' and select one or more products to return.
5.. Enable checkbox 'Generate a credit note'
6. Click 'Return products'

**Screenshots**
![image](https://user-images.githubusercontent.com/43873766/52340345-d2249680-2a0f-11e9-9e76-ba1450d524fe.png)

**Additionnal information**
PrestaShop version: 1.7.4.2  and 1.7.5.0
PHP version:  7.0.32

**Comment by khouloudbelguith** [comment] 2019-02-06 12:56
Hi @Ned201,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/15E3uyNT1JutAWErCPAGFw2cKllFeSAUW/view
Thanks to check & feedback

**Comment by khouloudbelguith** [comment] 2019-03-08 08:13
Hi @Ned201,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-08 08:13 UTC
Labels: BO, Order, No change required, 1.7.5.0
