### ISSUE TITLE
Geolocation doesn't retrieve the visitor's country

### ISSUE THREAD

**Issue by olecorre** [PrestaShop/PrestaShop#33709] opened 2023-08-24 08:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Activate geolocation Configure a carrier specific to this country with its own zone. Use a VPN to simulate a visit to the site from this country (other than your own country) add a product to the basket, you will need to have the shipping costs for the country in question and not those for the default country.

When you activate geolocation, before entering an address, the system displays the delivery costs from the default country. The purpose of geolocation is to retrieve the visitor's country. You therefore need to display the delivery charges according to this country.

### Expected behavior

On a customer site, I have a specific carrier for France that offers free postage. But for other European countries, shipping is charged. The European countries have been added to a different zone than France.
If a visitor from Germany visits the site, adds a product to the basket, they see "Free shipping", but this should be a charge.
Geolocation has been implemented but they still see "Free shipping".
After analysis, the core lists the carriers in the shop's default country, i.e. France. It does not take into account the country detected by the geolocation.

### Steps to reproduce

- Activate geolocation
- Configure a country in a zone other than the default country.
- Configure a carrier for this country (zone) with delivery charges.
- Use a VPN to simulate a connection from this country
- Without the correction, you will see in the basket the shipping costs for the default country.
- With the correction, you will see in the basket the delivery charges linked to the country detected by the geolocation.

Translated with www.DeepL.com/Translator (free version)

### PrestaShop version(s) where the bug happened

All version

### PHP version(s) where the bug happened

All version

### Your company or customer's name goes here (if applicable).

OHweb

**Comment by hibatallahAouadni** [comment] 2023-08-28 16:16
Hello @olecorre 

Could you please provide a screen record to help me reproduce the issue 🙏 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-18 07:42
Hello @olecorre 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-18 07:42 UTC
Labels: Bug, BO, Geolocation, PR available, Invalid, 8.1.x
