### ISSUE TITLE
Customer Reassurance Module, v4.1.1, "Title" and "Description" fields are missing in edit form when main BO langage is disabled

### ISSUE THREAD

**Issue by globox91** [PrestaShop/PrestaShop#16400] opened 2019-11-13 13:44 UTC
**Describe the bug**

"Title" and "Description" fields are missing while editing any of the reassurance blocks.
They are hidden because they have html class "inactive".
And that class is added because my selected language for BO is not among my "active" languages (I need this language only for BO, not in FO, so I deactivated it).

Seems like I need to translate my BO to some of the FO languages in order to be able to edit those title and description. Imho, that's weird :)

**To Reproduce**

1. Install two or more languages
2. Deactivate one of them (e.g. "lang 2")
3. Go to your admin profile and set your language to "lang 2"
4. Try to edit any reassurance block
5. See that no "Title" nor "Description" are present

**Screenshots**

![изображение](https://user-images.githubusercontent.com/56883311/68768842-5d345c00-0634-11ea-92e5-4619ed440250.png)
![изображение](https://user-images.githubusercontent.com/56883311/68768972-979df900-0634-11ea-855b-b27e5a1f6484.png)

**Additional information**

PrestaShop version: 1.7.6.1
PHP version: 5.6
Module version: 4.1.1

**Comment by khouloudbelguith** [comment] 2019-11-13 13:50
Hi @globox91,

I did not manage to reproduce the issue with PS1.7.6.1 & block reassurance v4.1.1.
https://drive.google.com/file/d/1gaEefcQTCou8uuJtKrzBW0dCfCKJ4iod/view
Your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/16152
But we cannot reproduce the problem so, we closed it.
Thanks to check & feedback.

**Comment by globox91** [comment] 2019-11-13 13:59
0:10-0:14 - You forgot to deactivate your current BO-language (in this case, German) :)
That's the whole point :)

**Comment by khouloudbelguith** [comment] 2019-11-13 14:08
@globox91, yes!
That's the whole issue.
I manage to reproduce the issue with PS1.7.6.1 & the `blockreassurance` v4.1.1.
![image](https://user-images.githubusercontent.com/16067358/68770756-0b390980-0627-11ea-893a-7f80f4867c0a.png)
With `blockreassurance` v3.0.1 => OK
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-13 14:14
Ping @Progi1984

**Closed as completed** 2022-02-17 20:04 UTC
Labels: Bug, Minor, BO, Regression, Blockreassurance, 1.7.6.0, 1.7.6.1, Module
