### ISSUE TITLE
remove a button from ps_customtext

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11278] opened 2018-11-06 11:27 UTC
Hi
in the configuration page of the module ps_customtext you should remove that button "return to the list"
it is not necessary on this module
Also the name "Blocco CMS" should be replaced by "Text Block"

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/48061457-4d7f6d80-e1bf-11e8-8456-36b43c43a69f.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0
ps_customtext version: 4.1.0

**Comment by khouloudbelguith** [comment] 2018-11-06 11:43
Hi @maofree,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.3 & the ps_customtext v4.1.0 - by PrestaShop.
The button "return to the list" just refresh the page.
We will see how to fix it.
Thanks!

Related to: #10848

**Comment by khouloudbelguith** [comment] 2019-02-12 10:07
Hi @maofree,

This issue is added to our debug roadmap.
Your ticket is a duplicate of #9902
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-12 10:07
Duplicate of #9902

**Closed as completed by khouloudbelguith** 2019-02-12 10:07 UTC
Labels: Bug, Minor, Duplicate, Customtext, 1.7.4.3
