### ISSUE TITLE
Invalid token when reaching the Back Office

### ISSUE THREAD

**Issue by Kumo-Innocent** [PrestaShop/PrestaShop#18820] opened 2020-04-25 13:25 UTC
Hello,

I have a problem on Prestashop,

I search for a long time on Google and nothing change the problem,

When I'm on the admin panel, I have a message that tell me: "Jeton (token) invalide" and I have 2 buttons "Continue and accept the risks" and "Keep me safe"

I can't do anything on the panel: I can't add a product, change settings, or when I can there is after 3 or 4 try...

I search for a long time on Google, and all solutions that I test ( = a lot ) doesn't work...
So please help me because that is very disturbing.

This problem appeared without any action by myself, I tried to contact the OVH support, I wait for a reply... ( With my research, I found that this problem can be due to OVH )

I use **Prestashop 1.7.6.5** ( No documentation, no support.... )
I use **PHP 7.2** ( I tried to change the version, but the problem is still here )

Please help me and fix this problem for future versions because I'm not first to have this error

Thanks,

Innocent1.

**Comment by PierreRambaud** [comment] 2020-04-27 09:21
HI @EyesGammer 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
 ...

You don't know how to get this information? Please read the following article:

http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by marionf** [comment] 2020-05-27 08:00
Hello,
Since we had no news from you for more than 30 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Closed as completed by marionf** 2020-05-27 08:00 UTC
Labels: Bug, BO, Can't reproduce
