### ISSUE TITLE
Stock error when doing a merchandise return

### ISSUE THREAD

**Issue by ivanfelicite** [PrestaShop/PrestaShop#21088] opened 2020-09-21 11:27 UTC
#### Describe the bug
When a return is made from an order on a product with combinations, the "main" stock (that is to say the one whose product_attribute ID is 0) is also replenished, however, this should not happen and only be done on the corresponding ID attribute.

#### Expected behavior

Onlye the corresponding ID attribut should be replenished when a return is done, and not the whole ID attribute.

#### Steps to Reproduce

1. Go to 'Order' => Choose an order hat you wish to made a return
2. Made the return on the desired product
3. Check in database the stock when comparing to the ID stock attribute

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by sarahdib** [comment] 2020-09-21 14:00
Hello @ivanfelicite 

Could you indicate which table we should check and which column ?

Could you also give us some screenshot?

Thank you!

**Comment by ivanfelicite** [comment] 2020-09-21 16:50
Hello @sarahdib !
Yes, the table to check is ps_stock_available.
To help you, I'm actually using this SQL query to correct the product stock when I made a merchandise return.

For example, if it concern the product ID 3251 : 
UPDATE 'ps_stock_available' SET 'quantity" = '0'
WHERE 'ps_stock_available'.'id_product'=3251;

I'm doing this query, because the whole quantity of each attribute of the concerned ID product are replensished, so the stock are incorrect!
I then adjust the stock of the desired attribute trough the back office.

Thank you!

**Comment by sarahdib** [comment] 2020-09-22 09:03
@PrestaShop/prestashop-core-developers could you check this?

**Comment by atomiix** [comment] 2020-09-28 09:32
@ivanfelicite @sarahdib from what I can see that's the expected behavior. The stock quantity of the `id_product_attribute` 0 is equal to the sum of every combination. So, if one of the combination is updated, the total should be too.

**Comment by hibatallahAouadni** [comment] 2020-12-21 10:55
Hello @ivanfelicite ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-21 10:55 UTC
Labels: Stocks, Merchandise returns, No change required, 1.7.6.7
