### ISSUE TITLE
payment prestashop 1.7.5.0

### ISSUE THREAD

**Issue by web-centre** [PrestaShop/PrestaShop#12609] opened 2019-02-18 11:37 UTC
Hello,
I recently installed the 1.7.5.0 version of prestashop, but I'm having several problems:
1) at the time of payment of an order, it appears that there are no payment methods available, despite having activated and configured the paypal module (screen attached)
2) from the back office I can not access different menu items that issue me the error 500 (screen attached)
the items that give me problems are:
ordini-> orders
orders-> shopping cart
catalogo-> Categories
customers -> customers
customer service -> customer service

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-02-18 11:41
Hi @web-centre,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by web-centre** [comment] 2019-02-18 12:01
![errore debug](https://user-images.githubusercontent.com/43772147/52949620-1f442900-337d-11e9-8d3b-3cf58d348ab0.JPG)
![errore debug2](https://user-images.githubusercontent.com/43772147/52949622-1f442900-337d-11e9-843c-438f37555c3c.JPG)
![errore debug3](https://user-images.githubusercontent.com/43772147/52949623-1f442900-337d-11e9-8771-47c0c3b0af6d.JPG)
![errore debug4](https://user-images.githubusercontent.com/43772147/52949624-1fdcbf80-337d-11e9-9764-29fecaf1c133.JPG)
![errore debug5](https://user-images.githubusercontent.com/43772147/52949627-1fdcbf80-337d-11e9-9dd0-0bf58340fd23.JPG)
![errore debug6](https://user-images.githubusercontent.com/43772147/52949630-210dec80-337d-11e9-9735-96d4491b44f3.JPG)
![info prestashop](https://user-images.githubusercontent.com/43772147/52949657-384cda00-337d-11e9-8bd8-1c43ae9efd92.JPG)

**Comment by khouloudbelguith** [comment] 2019-02-18 13:13
Hi @web-centre,

About the first screenshot, you need to enable the `php_mbstring`, this issue is added to our bug roadmap in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9583
About the second screenshot, there is an issue with the `whatsapp` module, as it's not provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
For a temporary fix, you can disable this module.
Thanks to check & feedback.

**Comment by web-centre** [comment] 2019-02-18 13:42
I do not understand how to enable `php_mbstring`,

**Comment by khouloudbelguith** [comment] 2019-02-18 13:46
@web-centre, you should contact your host about that, or you can uncomment this line `extension=php_mbstring.dll` in your php.ini file
Thanks!

**Comment by web-centre** [comment] 2019-02-18 15:35
risolto

**Comment by khouloudbelguith** [comment] 2019-02-18 15:38
@web-centre, since it is fixed.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-18 15:38 UTC
Labels: Bug, No change required, 1.7.5.0
