### ISSUE TITLE
Shopping cart issues

### ISSUE THREAD

**Issue by bbgjyb** [PrestaShop/PrestaShop#12418] opened 2019-02-03 19:55 UTC
**Describe the bug**
I use Prestashop 1.7.4.2. I have a problem with my shopping cart: it worked fine until I tried to integrate an electronic payment system (G2A). I uninstalled the module, cleaned the cache, but the problem persists.
Everything works well until payment when we click on "quick view". By contrast, when you click on the image of the product or on an attribute (color for example when available), the answer is systematically: "There are no more items in your cart".
**To Reproduce**
1. Go to 'https://africshop.com'
2. Click on 'any product picture or attribute if available'
3. Product's page loads: click on 'add to cart'
4. See error: "There are no more items in your cart"
5. Click on 'Quick view of the same product' and add to the cart. It says 'Product successfully added to your shopping cart'. Then you are invited to "proceed to checkout" or "continue shopping" 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.33
If you needed any other information please let me know.
Thanks for your help

**Comment by khouloudbelguith** [comment] 2019-02-04 08:21
Hi @bbgjyb,

I tried with your shop when we click on the product page, you have an error 500, 
```
Request URL: https://africshop.com/index.php?id_product=60&id_product_attribute=0&rewrite=robe-de-cocktail-numoco&controller=product&id_lang=2
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 91.234.194.249:443
Referrer Policy: no-referrer-when-downgrade
```
Also, you have a strange thing, the arrow to increase & decrease the quantity is not displayed on the product page.
![image](https://user-images.githubusercontent.com/16067358/52196937-08221900-285e-11e9-9531-bdef7241eccb.png)
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-06 11:28
Hi @bbgjyb,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by bbgjyb** [comment] 2019-04-08 21:37
Hello,
Sorry. I'm back now. No solution since that time. I'm so disappointed...
I would like you to get an eye directly in my system.

**Comment by khouloudbelguith** [comment] 2019-04-09 08:25
Hi @bbgjyb,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-09 07:13
Hi @bbgjyb, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-09 07:13 UTC
Labels: Bug, FO, No change required, 1.7.4.2

**Comment by KGabson** [comment] 2020-01-21 08:10
Hello, 
After I had the same issue. I tryied with DEV mode "on" and i have this php error : 

```
UndefinedMethodExceptionAttempted to call an undefined method named "getDefaultCountryId" of class "Country".
--
in Carrier.php line 735
at CarrierCore::getCarriersForOrder(0, array(3), object(Cart), array(0))in Carrier.php line 1555

```

I have checked files on github. Indeed I don't see any method called getDefaultCountryId in my files. Any idea ?
