### ISSUE TITLE
Prestashop - Url after change product status

### ISSUE THREAD

**Issue by PaoloDalVecchio** [PrestaShop/PrestaShop#30139] opened 2022-10-28 06:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Good morning
when i deactivate a product on the second or greater page of the catalog, the first page loads.

### Steps to reproduce

1. Go to catalog
2. go to second page
3. deactivate 1 prodoct
4. back to the first page of the catalog (the issue)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-10-28 18:27
Hello @PaoloDalVecchio 

I didn't manage to reproduce the issue with the provided infos, could you please provide a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by HanaRebaiQA** [comment] 2022-11-17 08:12
Hello @PaoloDalVecchio 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank You!

**Closed as completed by HanaRebaiQA** 2022-11-17 08:12 UTC
Labels: Bug, BO, Categories, Invalid, 1.7.8.7
