### ISSUE TITLE
The icon "Add new Credit slip" has no affects, it will refresh the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10112] opened 2018-08-24 07:46 UTC
**Describe the bug**
In the BO => SELL => Orders => Credit Slips => the icon Add a new credit slip is displayed, but it has no effect.
![image](https://user-images.githubusercontent.com/16067358/44571659-ad9a7200-a781-11e8-9799-4bcc2eea9fc8.png)
In the help documentation, the credit slip must be created from the order's page.
So it is necessary to remove this icon.

**To Reproduce**
1. Go to BO => SELL => Orders => Credit Slips page
2. Click on 'ADD NEW' button => the page will be refreshed.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.19

**Comment by marionf** [comment] 2019-04-19 08:59
Duplicate of #9962

**Closed as completed by marionf** 2019-04-19 08:59 UTC
Labels: Bug, Minor, Duplicate, Order, Credit notes, 1.7.4.2
