### ISSUE TITLE
Category group access is reset after saving programmatically

### ISSUE THREAD

**Issue by Amazzing** [PrestaShop/PrestaShop#23268] opened 2021-02-15 18:08 UTC
#### Describe the bug
Category group access is reset after saving object programmatically, like `$category_obj->save();`

#### Expected behavior
Group access options shouldn't be reset if category object is saved programmatically

#### Steps to Reproduce
1. Open any category sheet for editing, _for example category ID 5_
2. Set specific group access for that category, _for example make it available only for group **Customer**_
3. Create a new category object programmatically: `$category_obj = new Category(5);`
4. Save category object: `$category_obj->save();`
5. Go to category sheet and check group access. It will be reset to default: **Visitor, Guest, Customer** 

#### Additional information
* PrestaShop version: 1.6, 1.7

**Comment by hibatallahAouadni** [comment] 2021-02-16 11:02
Hello @Amazzing 

Could you please check after executing this line `$category_obj = new Category(5);` the group access of `$category_obj` by method `get` (before the save line `$category_obj->save();`).
Please check and feedback.

Thanks!

**Comment by Amazzing** [comment] 2021-02-16 11:40
Hi @hibatallahAouadni 
Do you mean this? `$category_obj->getGroups();`
Yes, it returns real groups of `$category_obj` before saving. 

Actually the following workaround can be used to save category properly, but it requires extra manipulations with `groupBox` property: 
```
$category_obj = new Category(5);
// fill groupBox before saving, otherwise it is empty
if (empty($category_obj->groupBox) && method_exists($category_obj, 'getGroups')) {
    $category_obj->groupBox = $category_obj->getGroups();
}
$category_obj->save();
```
If `$category_obj->groupBox` is not specified additionally, then it is empty, and when category is saved, groups are reset to default. Please check` public function updateGroup($list)` in **/classes/Category.php**

**Comment by hibatallahAouadni** [comment] 2021-02-17 12:35
Hello @Amazzing 

Thanks for your feedback.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17449. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-17 12:35
Duplicate of #17449

**Closed as completed by hibatallahAouadni** 2021-02-17 12:35 UTC
Labels: Bug, 1.7.x, CO, Duplicate, Categories, Customer groups
