### ISSUE TITLE
[PrestaShop 1.7.7.0] I can't reset password in the frontoffice

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#22374] opened 2020-12-11 16:42 UTC
#### Describe the bug

In PrestaShop 1.7.7.0 when, I try to reset a customer password I see the error "An error occurred while sending the email."
To be sure that this is not a server problem I tested it on the same server with the same settings in PrestaShop 1.7.6.8 and everything is ok in this version, so this problem only occurs in version 1.7.7.0
I tested this with the "classic" theme in a clean PrestaShop installation.

#### Steps to Reproduce

1. Click "Sign in" at the top.
2. Click on 'Forgot your password?'
3. Paste email in the field "Email address" and click the button "Send reset link".
4. See error: "An error occurred while sending the email."

**Screenshots**

Screenshot from PrestaShop 1.7.7.0:
https://prnt.sc/w0lyt3

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by florine2623** [comment] 2020-12-11 16:48
Hello @Angar90 ,
I can't reproduce your issue :
![Capture d’écran 2020-12-11 à 17 46 52](https://user-images.githubusercontent.com/16019289/101930768-deb04200-3bd8-11eb-964d-665f6e1e119f.png)

Please check in Advanced Parameters > Email and check your configuration to see if emails can be sent :
![Capture d’écran 2020-12-11 à 17 47 35](https://user-images.githubusercontent.com/16019289/101930863-ff789780-3bd8-11eb-9905-52113cc5cf6c.png)

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thanks!

**Closed as completed by florine2623** 2020-12-11 16:48 UTC
Labels: Can't reproduce
