### ISSUE TITLE
Dashboard forecast report

### ISSUE THREAD

**Issue by imartin1983** [PrestaShop/PrestaShop#12988] opened 2019-03-21 00:29 UTC

**Comment by imartin1983** [comment] 2019-03-21 00:36
Hello,

I noticed a bug (?) in the DB of PS (1.7.5.1 / 1.7.4.2). 
1) The forecast dashboard is not loading and not displaying any data. If you type data manually, it won't save them.

2) There are some weird values in the DB in ps_configuration_kpi. Defined as Traffic = 600, Conversions = 2 and Cart Value = 80. I don't know where, but there was a post from a member mentioning these exact values that he was using for testing the same issue. It almost seems someone from PS team has forgotten to delete them while testing before the new PS release. Sounds dumb, but most likely somehow linked to a test.

Regards,
Martin

**Comment by khouloudbelguith** [comment] 2019-03-21 08:09
Hi @imartin1983,

We are aware of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #9662
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-21 08:09
Duplicate of #9662

**Closed as completed by khouloudbelguith** 2019-03-21 08:09 UTC
Labels: Duplicate
