### ISSUE TITLE
Cart recovery set is_logged at true

### ISSUE THREAD

**Issue by paul-jolimoi** [PrestaShop/PrestaShop#27033] opened 2021-12-20 15:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we recover a cart through the FrontController::recoverCart() method (by setting a recover_cart and token_cart in the URL that calls orderController), there will be two case : 

- if the customer has a session, it will recover its cart and log him.
- if the customer hasn't a session, it will recover its cart and not log him, but the is_logged will be set at true.

We were thinking it wasn't something wanted, because this boolean should be used to show features for logged customer.

Is there a reason for this behaviour ?

### Expected behavior

When we recover a cart through the FrontController::recoverCart() method (by setting a recover_cart and token_cart in the URL that calls orderController), there will be two case : 

- if the customer has a session, it will recover its cart and log him.
- if the customer hasn't a session, it will recover its cart and not log him, and the is_logged will be set at false.

### Steps to reproduce

Go to an url like : http://your_prestashop_server.com/order?step=1&recover_cart=_[id_recover_cart]_&token_cart=_[token_cart]_

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.3

**Comment by marwachelly** [comment] 2021-12-21 16:01
Hello,

Could you please provide me with a screen record to reproduce the issue.

Many thanks,

**Comment by paul-jolimoi** [comment] 2021-12-23 16:36
![image](https://user-images.githubusercontent.com/78373471/147267632-c4df57a6-f7f2-46db-b167-11121838de07.png)

You can easily reproduce if you have a recover cart link and if you open it in a new tab (maybe use a private tab to avoid having previous cookie loading), you will see that your user will not be connected and you will see the logging form below your order summary as in the picture above.

The question was more about those line : 
https://github.com/PrestaShop/PrestaShop/blob/f40d3d5b1b1f6e092f98bbb38d404a3d448ecb77/classes/controller/FrontController.php#L1269
https://github.com/PrestaShop/PrestaShop/blob/f40d3d5b1b1f6e092f98bbb38d404a3d448ecb77/classes/controller/FrontController.php#L1274

Isn't that a problem to set **logged** to true while having no session ?

**Comment by marwachelly** [comment] 2021-12-28 15:30
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10996.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Closed as completed by marwachelly** 2021-12-28 15:30 UTC
Labels: Bug, FO, Duplicate, Customer, Shopping carts FO, Invalid

**Comment by hibatallahAouadni** [comment] 2021-12-28 15:40
Duplicate of #10996
