### ISSUE TITLE
BO pages using new theme have wrong jQuery version and no jQuery migrate

### ISSUE THREAD

**Issue by MarkALeonard** [PrestaShop/PrestaShop#22572] opened 2020-12-23 17:32 UTC
**Describe the bug**

When using BO pages that use the new theme and load bundle.js the jQuery version is 3.3.1, jQuery Migrate is also unavailable.

BO pages that load js files individually have jQuery 3.4.1 and jQuery Migrate 3.1.0

In my particular case a module relying on jQuery UI does not function because of missing jQuery Migrate.

**Expected behavior**

jQuery version and jQuery Migrate should be consistent across the BO.

**Steps to Reproduce**

1. Open BO Dashboard page.
2. In console run $().jquery and $.migrateVersion (versions 3.4.1 and 3.1.0 are returned).
3. Open BO Orders page.
4. In console run $().jquery and $.migrateVersion (versions 3.3.1 and undefined are returned).

**Additional information**

* PrestaShop version: 1.7.7.0

**Comment by matks** [comment] 2020-12-23 21:35
Hi @MarkALeonard,

On BO Orders page (and other migrated pages), jQuery Migrate is not loaded because these pages have always been running jQuery3. We have upgraded jQuery version in BO pages using old theme and in FO, and we wanted to provide a layer of compatibility which is why we used jQuery Migrate. On pages where jQuery has always been running version 3, I don't understand the need for jQuery Migrate.

That being said, I agree we should try to have the same jQuery version on both old and new BO theme.
I checked PS 1.7.8 (branch `develop`) and jQuery on new theme has been updated from v3.3 to v3.5 . I'm not sure whether it's possible to update old BO theme jQuery too, there is a lot of old code to support. Better ask our expert @NeOMakinG for this 😄 .

> In my particular case a module relying on jQuery UI does not function because of missing jQuery Migrate.

I dont understand why jQuery UI cannot be used on pages using new BO theme ? jQuery Migrate is not providing plugin capabilities, it's rather providing a layer of backward compatibility for JS code relying on jQuery 1 or 2 ?

**Comment by matks** [comment] 2020-12-23 21:37
For details
- https://github.com/PrestaShop/PrestaShop/pull/15245
- https://github.com/PrestaShop/PrestaShop/pull/15750

**Comment by hibatallahAouadni** [comment] 2020-12-24 09:39
Hello @MarkALeonard 

Thanks for your issue! I believe what you're asking for is an improvement :wink: 

> I'm not sure whether it's possible to update old BO theme jQuery too, there is a lot of old code to support. Better ask our expert @NeOMakinG for this 

Ping @NeOMakinG do you think that jQuery Migrate should be consistent across the BO? 

Thanks!

**Comment by MarkALeonard** [comment] 2020-12-24 09:56
Hi @matks,

Thank you for your prompt response. 

I agree, adding jQuery migrate does not make much sense but adding it stopped the errors I was receiving. The module in question is using jQuery UI and an error appears when it is used. It seems jQuery UI and 1.10.3 and jQuery 3 have some compatibility issues.

However as you mention new theme BO pages have always used jQuery 3 so this shouldn't be an issue that is only just appearing.

I am trying to debug a module that worked in 1.7.6 but does not in 1.7.7, looking at the Order pages in 1.7.6 they seem to load separate JS files for jQuery as well as bundle.js. I tested this on a fresh install of 1.7.6.7, order page scripts shown below:

![Screenshot 2020-12-24 095027](https://user-images.githubusercontent.com/33283565/103080313-7ba5ae80-45cd-11eb-9d76-d065fb99097c.png)

I assume this is something that was not meant to happen and has been corrected in the most recent update. Can anyone shed some light on this?

For my particular case I can add jQuery migrate to resolve the problem but I agree with your suggestion that jQuery version should be consistent across the BO if possible.

**Comment by NeOMakinG** [comment] 2020-12-24 10:01
@matks the problem is that on 1.7.0.0, it was jQuery 2.2, when the upgrade to 3.0 has been done, it would have required to add jquery-migrate to for module compatibility!

Having a small differences like 3.4.1 on default and 3.5 on new-theme is not that critical, but not having jQuery migrate seems to be an error to me when the team update to v3 on new-theme.

@MarkALeonard I think on 1.7.6, the order page was on the legacy layout right ? So it completely changed, it's now relying on new-theme, so the bundle is now different !

And jquery is now inside the UIKit, so we've no way of bundling it separately and I doubt this would be useful anyway.

I'll probably add jQuery migrate to the UIKit because this is an issue to me. wdyt?

**Comment by MarkALeonard** [comment] 2020-12-24 10:58
@NeOMakinG After some investigation, yes the order pages have been migrated between versions 1.7.6 and 1.7.7 so that is the root of my problem. Thanks for suggesting that.

If adding jQuery migrate to the UIKit will include it in the migrated pages then that seems like a sensible option to me.

**Comment by NeOMakinG** [comment] 2021-01-20 16:05
Assigned to me, to add migrate on the UIKit

**Closed as completed** 2021-02-04 07:51 UTC
Labels: Improvement, BO, CO, Fixed, UI Kit, 1.7.7.0
