### ISSUE TITLE
Translate action not working

### ISSUE THREAD

**Issue by josejecas** [PrestaShop/PrestaShop#14277] opened 2019-06-18 20:08 UTC
Look at the next video, I'm trying to translate a field manually and I can not.
Is there a solution?

https://drive.google.com/file/d/10n0WjnP2hZ0WRodWmoIQQWz_Wb3kjSzJ/view

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-19 09:02
Hi @josejecas,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1 & a different theme.
The translation is successfully updated
https://drive.google.com/file/d/12PyYACN4An-E8TabHfcjvFo3Z4uQVh6o/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by netraagal** [comment] 2019-06-27 13:10
Did you try to delete your cache in advanced parameters > performance ?
There is a file cache which is storing translations, and I don't know if it deleted when modifying a translation

**Comment by khouloudbelguith** [comment] 2019-06-28 07:57
@josejecas, you can clear cache manually the cache by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-29 06:28
Hi @josejecas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-29 06:28 UTC
Labels: Bug, FO, Translations, No change required, 1.7.5.1
