### ISSUE TITLE
Prestashop 1.7.5.1 : Can't remove id_product_attribute from URL Format of products

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#13685] opened 2019-05-06 15:25 UTC
Hello everybdoy,

On a test server, I migrated a Prestashop 1.6.1.5 site to Prestashop 1.7.5.1 thanks to a module developed by Migration Pro (module that I recommend).

Thanks to this module, I was able, in particular, to keep the different IDs (product IDs, categories, customers ...)

However, I notice a difference between the URLs between Prestashop 1.6.1.5 and Prestashop 1.7.5.1 even after being in B.O> Shop Settings> Traffic and SEO and after enabling Simplified URL in the URL configuration section.

For example :

URL of a product on the site with version 1.6.1.5 of Prestashop:
www.sitename.fr/8-product-name.html

URL of the same product on the site with version 1.7.5.1 of Prestashop:
dev2.sitename.fr/category-name/8-545-product-name.html#/14-black-color

with:

- _8-_ (id_product)
- _product-name.html_
what is identical

and :
- **category-name/**
- **545-**(id_product_attribute)
- **#/14-black-color**

what is added

On the same page (B.O> Shop Settings> Traffic and SEO), a little further down, there is the _URL Format_ section.

In this part, for the product URL, I have:

{Category: / {id}} {-: id_product_attribute} - {{rewrite} -: ean13} .html

From what I understood, I can remove:
- Category
- ean13
but I CAN NOT remove :
- id [product]
- id_product_attribute
- rewrite

because they are required, but I want to delete _id_product_attribute_. **How can I do to have the same URL for a product on Prestashop 1.7 as on Prestashop 1.6?**

Because if not, I will have big SEO concerns if / when I go to Prestashop 1.7.x.x

In addition, why id_product_attribute appeared in the URL with Prestashop 1.7 while it was not in Prestashop 1.6? And why is it required under Prestashop 1.7? This is to prevent the migration of a Prestashop 1.6 shop to 1.7 ?!

Thanks in advance

Have a good day

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-07 10:58
Hi @wikao2,

Recently we have made some modifications related to the SEO OPTIMIZATION in the product page.
You can follow those links: #9463, #9456
About the bad URL when the product has combinations, we have also this issue #9784, it is added to our bug roadmap, so that will be fixed.
Your ticket is a duplicate of #9784
So, I close it.
Thanks!

**Closed by khouloudbelguith** 2019-05-07 10:58 UTC

**Comment by wikao2** [comment] 2019-05-09 12:46
euh... As I understand it, it's been since the end of August 2018 (maybe even before) that you know that there is a URL problem for products that have a combination and that it's added to your bug roadmap ? (Excuse my question) Why is it so long to correct this issue ? This is not a priority bug? We already wondered if we had to switch to Prestashop 1.7 ... There, we ask more the question.
(Sorry to say it, but) Your response, your willingness and your speed to tackle this problem is far from reassuring and does not push to migrate to Prestashop 1.7

**Comment by khouloudbelguith** [comment] 2019-05-09 12:57
@wikao2, thanks for your feedback. Unfortunately, it's not easy to move from one URL format to another during minor versions as there are risks to break things down when upgrading.

We will be rethinking the URL format for the next major version.
Thanks!

**Comment by wikao2** [comment] 2019-05-09 14:07
What do you call "_next major version_" ? Prestashop 1.7.**6**.x or outright Prestashop 1.**8** ?

**Comment by khouloudbelguith** [comment] 2019-05-09 14:33
@wikao2, no it is not for PS1.7.6.x.
The version PS1.7.6.0 will be released soon.
Thanks!

**Comment by alessiolovecchio** [comment] 2019-06-01 21:06
It seems this causing the impossibility for a product with combinations to be indexed by Google.

The URL contains the ID of the product and the ID of the default combination. Something like this: _/453-567-product-name.html_

But it has the rel canonical to _/453-product-name.htm_l that has only the ID of the product (not the combination one).

The serious problem is that _/453-product-name.html_ has a 301 redirect to _/453-567-product-name.html_ which is not indexable due to the rel canonical.

What a bad loop.

Am I right?

**Comment by khouloudbelguith** [comment] 2019-06-03 09:35
Hi @alessiolovecchio,

>The serious problem is that /453-product-name.html has a 301 redirect to /453-567-product-name.html

This issue is fixed in the PS1.7.6.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13009 to fix the problem.

Thanks!
