### ISSUE TITLE
Carrier selection on dimensions not working 1.7.7.1

### ISSUE THREAD

**Issue by qualityangel** [PrestaShop/PrestaShop#23167] opened 2021-02-07 09:08 UTC
#### Describe the bug

When setting the maximum dimensions in the carrier tab, it shows on order even out of range.
It looks like it is not checking if dimensions are exceeding the carrier maximum.

#### Expected behavior

Expectation is, that when a customer orders some item with dimensions like: 10.5x10x3.5 and the carrier maximum size is 10x10x3 it does not have to show this carrier option to customer, but now it does.
We have 3 carrier options
Postnl - Mailbox package -> This one keeps showing up even when limits are exceeding.
DHL - max 10kg
DPD - 0 - 25kg

#### Steps to Reproduce

1. Go to 'Carrier tab'
2. Click on 'the carrier you need the max dimensions for'
3. Fill in 'The maximum dimensions for the carrier'
4. Go the the front office and try to order some product that exceed the dimensions of the carrier.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by qualityangel** [comment] 2021-02-07 09:19
Ok it looks like it does cannot handle decimals in the product page. when i use whole numbers it is working. This is an issue for small packages. and real dimensions calculation.

**Comment by hibatallahAouadni** [comment] 2021-02-08 16:35
Hello @qualityangel 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22877. 
It's fixed with our futur release 1.7.8.0, please subscribe to the issue mentioned above.
And here's the PR #22884 that fixed the problem :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-08 16:35
Duplicate of #22877

**Closed as completed by hibatallahAouadni** 2021-02-08 16:35 UTC
Labels: Duplicate
