### ISSUE TITLE
Disconnection after validation of the "Menu" module

### ISSUE THREAD

**Issue by Philippe-M** [PrestaShop/PrestaShop#29724] opened 2022-09-22 13:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

In the "Menu" module, when I transfer an item from the "Available items" list to the "Selected items" list and click on "Save", I am redirected to the administration login form and my modifications do not are not taken into account.

![image](https://user-images.githubusercontent.com/4558101/191765375-e78ecc8d-b3b6-489e-94dd-8b19ea0d0d12.png)

### Expected behavior

Disconnection after validation of the "Menu" module

### Steps to reproduce

1: Go to "Modules"
2: search : menu
3: click on "Configure"
4: Select an item from the "Available items" list
5: Click on Add
6: Click on Save

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3.32

### If your bug is related to a module, specify its name and its version

ps_mainmenu 2.3.1

**Comment by matks** [comment] 2022-09-22 14:20
Hello @Philippe-M 😄 nice bug report 👍

**Comment by AureRita** [comment] 2022-09-22 15:07
Hi @Philippe-M 

Thank you for your report ! I tried to reproduce your issue as you can see : 

https://user-images.githubusercontent.com/100699445/191783615-7ea19a82-f7cf-4a59-aead-5afa19a9b9ce.mp4

but I, currently, can't reproduce it. Did you have other details after a fresh install of a shop in 1.7.8.7 ? 

Thank you for all your details you give ! 

Waiting for your feedback

**Comment by Philippe-M** [comment] 2022-09-23 09:11
Hello,

Could be a line of research.

In the "action" parameter http is forced

`<form id="module_form" class="defaultForm form-horizontal" action="http://monsite/test-cata/admin510bejiyv/index.php?controller=AdminModules&amp;configure=ps_mainmenu&amp;tab_module=front_office_features&amp;module_name= ps_mainmenu&amp;token=928b13a73114fd7dc3e7a81a2f062303" method="post" enctype="multipart/form-data" novalidate="">`

Whereas if I take the example of the ps_customtext module the "action" parameter does not force the http

`<form id="configuration_form" class="defaultForm form-horizontal ps_customtext" action="index.php?controller=AdminModules&amp;configure=ps_customtext&amp;token=928b13a73114fd7dc3e7a81a2f06`

Complément :
I just tested by removing the http://mysite from the action parameter directly from the firefox debugger and it worked.

**Comment by hibatallahAouadni** [comment] 2022-09-26 13:54
Hello @Philippe-M 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-09-26 13:54 UTC
Labels: Bug, BO, Mainmenu, Module manager, Invalid, Module
