### ISSUE TITLE
I can't upload a new form

### ISSUE THREAD

**Issue by grafica3B** [PrestaShop/PrestaShop#27610] opened 2022-02-07 09:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi, i would like to upload a new form but i can't, because when i click to "Upload a form", nothing happens.
I try to login with another browsers, i try to log out and log in and i try to click several times, but nothing happens

![Cattura](https://user-images.githubusercontent.com/99173363/152762425-21dbd8da-467c-4ba3-be83-08be38e2157e.JPG)

i think it is a bug, but i'm a beginner and i don't know how to solve this problem. 
Could you help me?

### Steps to reproduce

1. I login into prestashop site
2. i click on Form Management
3. i click on Upload A Form

### PrestaShop version(s) where the bug happened

1.7.7.1

**Comment by hibatallahAouadni** [comment] 2022-02-07 13:43
Hello @grafica3B 

I didn't manage to reproduce the issue with PS1778 and PS1783, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/152799291-62ed59e3-da66-422a-9ba3-fb216a6c8769.png)

Could you please enable the debug mode and try again to upload a module :pray: 
If there's an error displayed, please make a screenshot and share it with us :wink: 
If not, open your console and check if there's an error displayed and share it with us.
Waiting for your feedback.

Thanks!

**Comment by grafica3B** [comment] 2022-02-07 14:05
> Hello @grafica3B
> 
> I didn't manage to reproduce the issue with PS1778 and PS1783, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/152799291-62ed59e3-da66-422a-9ba3-fb216a6c8769.png)
> 
> Could you please enable the debug mode and try again to upload a module pray If there's an error displayed, please make a screenshot and share it with us wink If not, open your console and check if there's an error displayed and share it with us. Waiting for your feedback.
> 
> Thanks!

Hi! I try another time with debug mode but i can't do anything :( the button don't work.

**Comment by grafica3B** [comment] 2022-02-07 14:16
> Hello @grafica3B
> 
> I didn't manage to reproduce the issue with PS1778 and PS1783, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/152799291-62ed59e3-da66-422a-9ba3-fb216a6c8769.png)
> 
> Could you please enable the debug mode and try again to upload a module pray If there's an error displayed, please make a screenshot and share it with us wink If not, open your console and check if there's an error displayed and share it with us. Waiting for your feedback.
> 
> Thanks!

![Cattura2](https://user-images.githubusercontent.com/99173363/152804592-9897a164-d98d-4e76-9f0a-d651c4f7d592.JPG)



I try to enable the debug mode on prestashop site, but it opened this page.

**Comment by florine2623** [comment] 2022-02-09 10:52
Hello @grafica3B ,

I can't reproduce your issue either.

https://user-images.githubusercontent.com/16019289/153183617-6c2ce119-fab4-4384-ba00-cdc392c24282.mov

You need to make sure your PHP version is compatible with your PS version : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

As your issue can't be reproduced, I will close it.

**Closed as completed by florine2623** 2022-02-09 10:52 UTC
Labels: Bug, BO, Modules, Module manager, 1.7.7.1, Invalid
