### ISSUE TITLE
AdminDashboard

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#14124] opened 2019-06-09 15:12 UTC
**Describe the bug**
The value in the DashBoard left column are in the uploading status all the time without result
**To Reproduce**
1. Go to 'Dashboard'
3. Scroll down to 'all the left column points'
4. See error No value, only "upload wheels" the internet connection is stable

**Screenshots**
![image](https://user-images.githubusercontent.com/50954519/59160719-c2ae7a80-8ae1-11e9-9dde-7014d36c3388.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 5.6.4

**Comment by khouloudbelguith** [comment] 2019-06-10 08:53
Hi @photinia73,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1.
I attached a video record.
https://drive.google.com/file/d/1PWZJKTLL4oW8KS5avcvEVu2bhDLAqmY_/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by photinia73** [comment] 2019-06-12 10:09
server info
![image](https://user-images.githubusercontent.com/50954519/59342858-4b602d00-8d13-11e9-854f-ab096323e59a.png)

**Comment by khouloudbelguith** [comment] 2019-06-12 10:11
@photinia73, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by photinia73** [comment] 2019-06-12 10:13
*ERROR* 	v1.7.5.1	2019/06/11 - 22:17:50: Post not found at line 1109 in file classes/Tools.php
*ERROR* 	v1.7.5.1	2019/06/11 - 22:18:55: Post not found at line 1109 in file classes/Tools.php

**Comment by photinia73** [comment] 2019-06-12 10:14
how can I get php log, your video don`t work ((

**Comment by photinia73** [comment] 2019-06-12 10:15
I think I know
now will try

**Comment by khouloudbelguith** [comment] 2019-06-12 10:16
@photinia73, the screen record is oK.
https://drive.google.com/file/d/1d14xIW38Yp1QptZAgTlXidtzvD0Ak3R3/view
Waiting for your feedback!

**Comment by photinia73** [comment] 2019-06-12 10:26
accept such log file 
[log](www.test.te.com.ua/error_log.1)

**Comment by photinia73** [comment] 2019-06-12 10:26
www.test.te.com.ua/error_log.1

**Comment by khouloudbelguith** [comment] 2019-06-12 10:38
@photinia73, you have the same error described in this issue https://github.com/PrestaShop/PrestaShop/issues/14136
It is related to your theme
```
[Mon Jun 10 15:00:25.635512 2019] [autoindex:error] [pid 27872] [client 49.44.122.38:0] AH01276: Cannot serve directory /var/www/testmW/test.te.com.ua/themes/pixtronpro/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm,index.php,index.html,index.htm,index.xhtml,index.cgi,index.pl) found, and server-generated directory index forbidden by Options directive
[Mon Jun 10 15:18:36.864407 2019] [authz_core:error] [pid 28027] [client 176.223.58.133:0] AH01630: client denied by server configuration: /var/www/testmW/test.te.com.ua/classes/Language.php
```

Thanks!

**Comment by photinia73** [comment] 2019-06-12 10:46
there is no my ip address

**Comment by photinia73** [comment] 2019-06-12 10:52
if there is a tool to clear the log and old unusefull info in PS?

**Comment by photinia73** [comment] 2019-06-12 10:53
can I give you the access you can found the problem?

**Comment by khouloudbelguith** [comment] 2019-06-12 10:55
@photinia73, you need to clear cache?

THanks!

**Comment by photinia73** [comment] 2019-06-12 11:22
ftp
host: ef1203.mirohost.net
U: testqd
P: GPX5O8QUxw8e


BackOffice 
U: khouloudbelguith
P: 12345678

Only ask don`t reinstall anithing or do something with modules ant themes. Just let me know about Error. Because the theme, modules don`t work stable enough, after some changes the hooks cancel or happen some else trouble (((

--

**Comment by photinia73** [comment] 2019-06-12 11:25
I hope you will find the problems, because Hiddentechies resolved a lot of issue but I feel there still a bugs...

**Comment by photinia73** [comment] 2019-06-12 11:40
About clear cache. I know about tool in the Back office. I mean such big files in the /var/logs/dev.log, etc because they grow up...

**Comment by khouloudbelguith** [comment] 2019-06-12 12:08
@photinia73, if you delete files into /var/logs/, they will be automatically created with new logs.

Thanks!

**Comment by photinia73** [comment] 2019-06-12 12:29
I forgot give the address of back office
https://test.te.com.ua/admin137buzkbm
Can you enter and found what happen with my site?

**Comment by khouloudbelguith** [comment] 2019-06-12 12:32
@photinia73, this is a public space.
You can provide me the credentials of your shop by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by photinia73** [comment] 2019-06-12 12:35
ok

**Comment by Quetzacoalt91** [comment] 2019-06-12 12:45
@photinia73 please take some time to update your credentials **as soon as possible**. We removed them but everybody was able to see them, which makes them compromised.

**Comment by photinia73** [comment] 2019-06-12 12:55
done

**Comment by khouloudbelguith** [comment] 2019-06-12 13:06
@photinia73, I just received the email.
I will check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-12 14:19
@photinia73, I tried to reset the `dashactivity` module, re-installing it, but always the same issue.
Only, I have an error in the console
![image](https://user-images.githubusercontent.com/16067358/59358924-5e7bf880-8d25-11e9-9b53-7e989dee52fa.png)

Have any new errors in your log file?

Thanks!

**Comment by photinia73** [comment] 2019-06-12 15:42
About payparts - this is the Ukrainian payment midule. If the problem in
it, I can write to the develop company. But let me know, about what the
error I have to describe

ср, 12 черв. 2019, 16:07 користувач khouloudbelguith <
notifications@github.com> пише:

**Comment by khouloudbelguith** [comment] 2019-06-12 15:45
@photinia73, No, I don't think that this module is related to the dashboard issue.
But, you can contact them about this error in the console, you can tell them that you have an error on the console.

Thanks!

**Comment by photinia73** [comment] 2019-06-12 15:47
I will, thanks

ср, 12 черв. 2019, 18:45 користувач khouloudbelguith <
notifications@github.com> пише:

**Comment by khouloudbelguith** [comment] 2019-06-12 15:50
@photinia73, thanks!

Waiting for your feedback.

**Comment by photinia73** [comment] 2019-06-12 15:58
A new error log file 


З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: среда, 12 июня 2019 г. в 17:19
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] AdminDashboard (#14124)

@photinia73, I tried to reset the dashactivity module, re-installing it, but always the same issue.
Only, I have an error in the console

Have any new errors in your log file?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-12 16:11
@photinia73, you need to login into GitHub & upload the new log file.

Thanks!

**Comment by photinia73** [comment] 2019-06-12 18:25
www.test.te.com.ua/error_log.12.Jun (1).2019

**Comment by photinia73** [comment] 2019-06-12 18:25
here is the new log file

**Comment by photinia73** [comment] 2019-06-12 18:44
About PayParts. Did found theits error in BO?

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: среда, 12 июня 2019 г. в 19:12
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] AdminDashboard (#14124)

@photinia73, you need to login into GitHub & upload the new log file.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-13 08:52
@photinia73, thanks for your report.
In your new log file, you have an issue related to the cache

`PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Filesystem\\Exception\\IOException' with message 'Failed to remove directory "/var/www/testmW/test.te.com.ua/var/cache/dev/": rmdir(/var/www/testmW/test.te.com.ua/var/cache/dev/): Directory not empty.'`

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

PS: about the PayParts module, in your BO, I have only an error in the console
![image](https://user-images.githubusercontent.com/16067358/59418414-e95e0100-8dc0-11e9-8a64-56146289b76d.png)

Thanks!

**Comment by photinia73** [comment] 2019-06-13 10:27
Do you mean to delete all folders (or content from existing folders) and files from var/cache/ (prod & dev)?

**Comment by khouloudbelguith** [comment] 2019-06-13 10:31
@photinia73, you need to delete all folders into /var/cache/ directory, you can find for example dev, prod.

Thanks!

**Comment by photinia73** [comment] 2019-06-13 12:28
Done, but nothing changed/ And here the new log file
[error_log.13.Jun_2019.txt](https://github.com/PrestaShop/PrestaShop/files/3285954/error_log.13.Jun_2019.txt)

**Comment by khouloudbelguith** [comment] 2019-06-13 12:46
@photinia73,

`AH01630: client denied by server configuration`
This error occurs especially if you update your server apache to version 2.4 without modifying the configuration file beforehand.
Could you please contact your host to configure it.
Thanks to check with them & feedback.

**Comment by photinia73** [comment] 2019-06-13 12:59
What file exactly I have to configure?

**Comment by khouloudbelguith** [comment] 2019-06-13 13:03
@photinia73, You have to check allow and deny rules

Check out http://httpd.apache.org/docs/2.4/upgrading.html#access

Thanks!

**Comment by photinia73** [comment] 2019-06-13 13:27
Even if write 
Require all granted nothing changed! And the 2.4.Apache was here from the begining and all worked properly. I stasted only month ago

**Comment by photinia73** [comment] 2019-06-13 13:28
the right on the folders 0755 for all
New log file
[error_log.13.Jun (1).txt](https://github.com/PrestaShop/PrestaShop/files/3286278/error_log.13.Jun.1.txt)

**Comment by khouloudbelguith** [comment] 2019-06-13 13:53
@photinia73, The best way to have the write and read access is:

`$ chown -hR www-data:www-data ./Project_Folder_name`

Thanks to check & feedback.

**Comment by photinia73** [comment] 2019-06-13 14:23
I have no linux or etc just far for ftp.... I can watch the permissions for folders via ctrl+A
I am not a developer....

**Comment by khouloudbelguith** [comment] 2019-06-13 14:25
@photinia73, could you please try to edit the permissions of the var/cache folder 777.
Thanks!

**Comment by photinia73** [comment] 2019-06-13 14:26
to cache yes, done, but not for dev (( denied

**Comment by khouloudbelguith** [comment] 2019-06-13 14:28
@photinia73, why dev is denied? it is a cache folder.

Thanks!

**Comment by photinia73** [comment] 2019-06-13 14:29
![image](https://user-images.githubusercontent.com/50954519/59441157-d0754000-8e00-11e9-92a1-8f61aa6b2110.png)

**Comment by photinia73** [comment] 2019-06-13 14:30
now will call to the hostmaster

**Comment by khouloudbelguith** [comment] 2019-06-13 14:33
@photinia73, it is a good idea to call the host.
Waiting for your feedback.

**Comment by photinia73** [comment] 2019-06-13 14:36
done

**Comment by photinia73** [comment] 2019-06-13 14:37
all from var to dev are 0777

**Comment by photinia73** [comment] 2019-06-13 14:38
now I deleting all in the dev again

**Comment by khouloudbelguith** [comment] 2019-06-13 14:38
@photinia73, now try to navigate to the dashboard again & provide me the error log again.

Thanks!

**Comment by photinia73** [comment] 2019-06-13 14:48
don`t work, the wheels rounding and thats all ((

**Comment by photinia73** [comment] 2019-06-13 14:49
And not new log file

**Comment by khouloudbelguith** [comment] 2019-06-13 14:51
@photinia73, Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by photinia73** [comment] 2019-06-13 21:53
I find the similar error with module=statsorigin 


З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: среда, 12 июня 2019 г. в 19:12
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] AdminDashboard (#14124)

@photinia73, you need to login into GitHub & upload the new log file.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-14 08:22
@photinia73, it is OK in my case.
![image](https://user-images.githubusercontent.com/16067358/59494833-ef69e580-8e85-11e9-821b-1fe7b3967d4d.png)

Thanks!

**Comment by photinia73** [comment] 2019-06-14 10:10
But this is not my web site…. 

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: пятница, 14 июня 2019 г. в 11:23
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] AdminDashboard (#14124)

@photinia73, it is OK in my case.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-14 10:17
@photinia73, yes, this my website.
I'm trying to reproduce your issue.

Thanks!

**Comment by photinia73** [comment] 2019-06-14 10:23
I see such errors in the Console, but I never did anything with stats modules
index.php?controller=AdminStats&token=a432814c5b77f5d342a5db3cedfaf140&module=statsorigin:1190 Uncaught ReferenceError: nv is not defined
    at Object.success (index.php?controller=AdminStats&token=a432814c5b77f5d342a5db3cedfaf140&module=statsorigin:1190)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at x (jquery-1.11.0.min.js:4)
    at XMLHttpRequest.b (jquery-1.11.0.min.js:4)
/admin137buzkbm/ajax.php?rand=1560507412499:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by photinia73** [comment] 2019-06-14 10:27
One thing I did, that add second language, and installed some non PS modules Payparts, SmartBlog (but this problem with BO appered before SmartBlog)

**Comment by photinia73** [comment] 2019-06-14 10:30
and this are the rrors with Browіукі and OS
![image](https://user-images.githubusercontent.com/50954519/59503251-8b0c4d80-8ea8-11e9-8e05-a7c148098864.png)

**Comment by photinia73** [comment] 2019-06-14 10:32
All items about catalog content are Ok, but the items with oursource information are with errors

**Comment by khouloudbelguith** [comment] 2019-06-14 10:36
@photinia73,
In your dev tools

1. go to Network tab
2. refresh this page: "Browsers and operating systems" tab
3. wait for an error, you should see red request information in Network tab
4. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by photinia73** [comment] 2019-06-14 10:49
I can see such picture,
![image](https://user-images.githubusercontent.com/50954519/59504137-ef301100-8eaa-11e9-8f7c-a79f9301b772.png)

**Comment by photinia73** [comment] 2019-06-14 10:52
and below in the text in the rad field, if I understood you correct.... I refreshed, stay in the Netwirk tab and look at the errors

**Comment by khouloudbelguith** [comment] 2019-06-14 10:55
@photinia73, here's a screenshot for example to see Preview Tab
![image](https://user-images.githubusercontent.com/16067358/59504669-59d95080-8e9b-11e9-800a-e8ee24d0e947.png)

Thanks!

**Comment by photinia73** [comment] 2019-06-14 11:17
![image](https://user-images.githubusercontent.com/50954519/59505801-2c969d80-8eaf-11e9-8a1f-a2991884ef58.png)

**Comment by photinia73** [comment] 2019-06-14 11:18
What I looking for?

**Comment by khouloudbelguith** [comment] 2019-06-14 11:19
@photinia73, did you delete my user account in your shop?, I needed it to check it.

Thanks!

**Comment by photinia73** [comment] 2019-06-14 11:20
I checked the work without anybody else with supear admin rigth. Just a sec

**Comment by khouloudbelguith** [comment] 2019-06-14 11:21
@photinia73, thanks!
Waiting for your feedback.

**Comment by photinia73** [comment] 2019-06-14 11:26
chech pls your email

**Comment by khouloudbelguith** [comment] 2019-06-14 11:28
@photinia73, just received the email.
I will check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-14 11:50
@photinia73, 
In your Projetc_Folder, you have this script

```
<script>
			$.ajax({
			url: "drawer.php?type=pie&option=wb&layers=1&width=100%25&height=270&render=graphnvd3&module=statsequipment&id_employee=4&id_lang=1",
			dataType: "json",
			type: "GET",
			cache: false,
			headers: {"cache-control": "no-cache"},
			success: function(jsonData){
				nv.addGraph(function(){
					var chart = 
				nv.models.pieChart()
					.x(function(d) { return d.label; })
					.y(function(d) { return d.value; })
					.showLabels(true)
					.showLegend(false);

					if (jsonData.axisLabels.xAxis != null)
						chart.xAxis.axisLabel(jsonData.axisLabels.xAxis);
					if (jsonData.axisLabels.yAxis != null)
						chart.yAxis.axisLabel(jsonData.axisLabels.yAxis);

					d3.select("#nvd3_chart_1 svg")
						.datum(jsonData.data)
						.transition().duration(500)
						.call(chart);

					nv.utils.windowResize(chart.update);

					return chart;
				});
			}
		});
		</script>
```
Could you please check this script is introduced in which file in your project.

Thanks!

**Comment by photinia73** [comment] 2019-06-14 12:31
now will try

**Comment by photinia73** [comment] 2019-06-14 12:45
it seems here prestashop\modules\dashactivity\views\js\dashactivity.js

**Comment by khouloudbelguith** [comment] 2019-06-14 13:09
@photinia73, thanks for your feedback.
I tried to uninstall the `dashactivity` module & removing it, clear cache.
In the BO => Stats => Browsers and operating systems Tab => the same error displayed, but the module `dashactivity`, is not installed.

Thanks to check & feedback.

**Comment by photinia73** [comment] 2019-06-14 13:18
the similar script in the dashtrends and dashgoals

**Comment by photinia73** [comment] 2019-06-14 13:29
Don`t work evething where is drawing have to be

**Comment by khouloudbelguith** [comment] 2019-06-14 13:32
@photinia73, 
>Don`t work evething where is drawing have to be

sorry what is the exact problem?
Thanks!

**Comment by photinia73** [comment] 2019-06-14 13:37
I mean that data in the numers is avalible, but the graphic reproducing are unavalible....

**Comment by photinia73** [comment] 2019-06-14 13:42
![image](https://user-images.githubusercontent.com/50954519/59513324-4d68ee00-8ec3-11e9-91cd-d572c03f3c36.png)

**Comment by photinia73** [comment] 2019-06-14 13:43
![image](https://user-images.githubusercontent.com/50954519/59513459-8bfea880-8ec3-11e9-9af1-d640e6571701.png)

**Comment by photinia73** [comment] 2019-06-14 13:44
And the same situation in all items of Dashboard where is graphic object

**Comment by khouloudbelguith** [comment] 2019-06-14 16:08
@photinia73, I tried with PS1.7.5.2 & PS1.7.6.0beta but I did not manage to reproduce the issue, all stats are well displayed.
@sarahdib could you please try to reproduce the issue?, have you the same issue with PS1.7.5.2 or PS1.7.6.0beta1.

Thanks!

**Comment by photinia73** [comment] 2019-06-14 19:44
After updating to 1.7.5.2 the problem disappeared. Thank you!!!

**Comment by photinia73** [comment] 2019-06-14 19:54
and the old theme. The problem is resolved only in dashboard.
And still is in the stats modules.
the dashboard
![image](https://user-images.githubusercontent.com/50954519/59534573-5a9fd000-8ef7-11e9-8dbb-a3d0431b5038.png)

**Comment by photinia73** [comment] 2019-06-14 19:57
and the stats modules
![image](https://user-images.githubusercontent.com/50954519/59534698-bc603a00-8ef7-11e9-9c1d-c3d6b5c4705d.png)

**Comment by khouloudbelguith** [comment] 2019-06-17 08:35
@photinia73, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-17 08:35 UTC
Labels: Bug, BO, Dashboard, Stats, No change required, 1.7.5.1
