### ISSUE TITLE
[FO] - Cross selling practically impossible with current Classic theme setup

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26660] opened 2021-11-17 22:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

Featured products are hooked (besides `displayHome`) only to `displayCrossSellingShoppingCart` inside **cart-empty.tpl**
https://github.com/PrestaShop/PrestaShop/blob/50b0b86d86cb34fdcde04502fdc774bce8176ac5/themes/classic/templates/checkout/cart-empty.tpl#L28
which practically is never loaded (only way to open this page is to refresh the cart after you remove all the products - noone does that),
or to `displayOrderConfirmation2` inside **order-confirmation.tpl**
https://github.com/PrestaShop/PrestaShop/blob/50b0b86d86cb34fdcde04502fdc774bce8176ac5/themes/classic/templates/checkout/order-confirmation.tpl#L111
which loads only after the order has just been placed. It seems pointless at this stage as it forces the client, if interested in any of these products, to place another order and go through whole proccess again.

There's also **Cross selling** module available but this is hooked only to `displayFooterProduct` on main product page.

### Describe the solution you'd like

When a client adds a product to the cart or checks out cart later, then featured and/or crossselling products should be also loaded to provide possible new items for the cart, before the order is placed.

### Alternatives you've considered

![csps](https://user-images.githubusercontent.com/5007456/142290505-bd1ec1e3-2094-4676-955c-042fdd9dcce8.gif)

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by Hlavtox** [comment] 2021-11-18 06:57
I will have a look on it and fix it. All crosselling hooks should be fine, I added one more recently, so we can display crosselling in cart modal:

https://github.com/PrestaShop/PrestaShop/blob/50b0b86d86cb34fdcde04502fdc774bce8176ac5/themes/classic/modules/ps_shoppingcart/modal.tpl#L98

**Comment by khouloudbelguith** [comment] 2021-11-18 08:54
Hi @SharakPL,

I manage to reproduce the issue with PS1769, PS1778, and PS1781 using Cross-selling v2.0.1 & Featured products v2.1.0.
https://watch.screencastify.com/v/CjeZTQHvdLT0Y6khuFA7

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by SharakPL** [comment] 2021-11-18 09:40
Since add-to-cart modal is already going to have crossselling products for the one just added, only feature missing is on Cart page. Featured products and/or crossselling products for all products in the cart would be great.

**Comment by Hlavtox** [comment] 2021-11-18 09:49
@SharakPL @khouloudbelguith Will be fixed with https://github.com/PrestaShop/PrestaShop/pull/26663

**Comment by SharakPL** [comment] 2021-11-18 11:24
Thank you @Hlavtox  :)

**Comment by khouloudbelguith** [comment] 2021-11-18 11:54
@SharakPL, we can close this issue when the PR is merged.
I will re-open the ticket.

Thanks!

**Comment by SharakPL** [comment] 2021-11-18 12:54
I'll remember that :) Sorry @khouloudbelguith

**Comment by khouloudbelguith** [comment] 2021-11-23 08:42
Hi @SharakPL, @Hlavtox,

After a discussion about this issue with @marionf.
We will change the issue template from a bug to a feature.

The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you!

**Closed as completed** 2021-12-21 11:29 UTC
Labels: Bug, Minor, FO, Modules, Cross selling, Fixed, Shopping carts FO, PR available, Featured products, Hook, 1.7.6.9
