### ISSUE TITLE
Missing Module Catalog menu

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#30026] opened 2022-10-17 02:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I made a fresh install of 8.0.0-rc1 and I can't find Module Catalog menu in admin.

![image](https://user-images.githubusercontent.com/19739263/196078952-61439b58-2f26-454c-a2f9-cfbd0962150d.png)

### Steps to reproduce

1. Made a fresh install of PrestaShop 8.0.0-rc1 in Brazilian Portuguese. Got no errors.
2. Logged in to admin area and couldn't find the Module Catalog menu.

### PrestaShop version(s) where the bug happened

8.0.0-rc1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2022-10-17 08:17
Hi @rblaurin, module catalog was removed from standard Prestashop, modules can now be installed from module manager like in 1.6.

If you want to have Prestashop Addons Catalog back, install ps_mbo module https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v2.0.2

**Comment by sallemiines** [comment] 2022-10-17 08:22
Hello @rblaurin ! 

Thanks for reporting the issue.
I reproduce the issue with  **PS 178X** **PS 800** , see the attached screen shot 

![Painel • test](https://user-images.githubusercontent.com/31663369/196120948-543df948-3105-4272-a6dd-9af5f23eef3c.png)

Thank you !

**Comment by zuk3975** [comment] 2022-10-17 08:54
As @Hlavtox mentioned, this is not a bug. As stated in https://build.prestashop-project.org/news/prestashop-8-0-beta-release/#modules--module-management since v8.0 **The PrestaShop project is now free of commercial products and services, so it no longer includes the Addons Marketplace by default**, so there is no module catalog by default anymore

**Comment by hibatallahAouadni** [comment] 2022-10-17 10:02
Hello @rblaurin 

As @Hlavtox and @zuk3975 mentioned above this is the expected behavior!
Closing the issue as it's not a bug.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-10-17 10:02 UTC
Labels: Bug, BO, Modules catalog, Invalid, 1.7.8.7

**Comment by rblaurin** [comment] 2022-10-17 12:02
Thanks for the clarification. So, from now on, the default way to install a new module (unless I install ps_mbo) is downloading it from PrestaShop Addons and then uploading it through module manager?

**Comment by matks** [comment] 2022-10-17 15:27
@rblaurin Yes 👍  if you use PrestaShop 8.0.0 open source (this GitHub repository contains the source code for PrestaShop open source project)

I think PrestaShop SA will also publish a PrestaShop 8.0.0 version that embeds the Module Manager that allows downloading modules from Addons, but that is now outside of the scope of this OSS organization :)

**Comment by tardiz17** [comment] 2023-01-25 11:31
> Hi @rblaurin, module catalog was removed from standard Prestashop, modules can now be installed from module manager like in 1.6.
> 
> If you want to have Prestashop Addons Catalog back, install ps_mbo module https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v2.0.2

Hello, I'm new in the community and with Prestashop too. I uploaded the "ps_mbo.zip" but as soon the intall finished I received this error and I can't login anymore:
![500Error](https://user-images.githubusercontent.com/123554245/214552622-41927e49-fce8-4442-86d8-662bb8c379d3.png)
