### ISSUE TITLE
Unable to install prestashop 1.7.6.0

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#15226] opened 2019-08-23 06:37 UTC
**Describe the bug**
Install prcedure freeze on 3rd step, there is no log on server, console, pfp, web server.
I think that the install procedure DOES not send compiled data to web server because insert a wrong verification password in the user creation fields does not return error.

Test on

OVH host nginx + apache
GANDI host varnish + apache

Both of the env above run with no problem many installation of prestashop.

**To Reproduce**
![image](https://user-images.githubusercontent.com/24798703/63571702-3f99ae00-c581-11e9-98df-e97d812c581b.png)

BUG seem to be related to this chrome version
Google Chrome è aggiornato
Versione 76.0.3809.100 (Build ufficiale) (a 64 bit)

i've also try to installa PS 1.7.5.X with no luck

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-23 08:33
Hi @matteolavaggi,

I did not manage to reproduce the issue with PS1.7.6.0.
I tried with Web server => Nginx & the chrome browser Version 76.0.3809.87 (Official Build) (64-bit)
I attached a screen record
https://drive.google.com/file/d/1yeD4PNheZoLIq-n2C5CrtipylGZEB4Bd/view
Did you try to enable debug mode before the new install?

Thanks!

**Comment by matteolavaggi** [comment] 2019-08-23 08:45
Hi, there is no debug entry at all, the script not send post request to the server, ajax call or any other kind of actio to send form entry. The strange is that i've reset chrome setting and try with different chrome account on the same chrome setup to avoid plugin or extension problem.

I've try to use internet exploer and i'm able to proceed with no problem in installation.

I will make some other test

**Comment by khouloudbelguith** [comment] 2019-08-23 08:58
@matteolavaggi, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-09-23 07:32
Hi @matteolavaggi, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-23 07:32 UTC
Labels: Bug, IN, No change required, 1.7.6.0
