### ISSUE TITLE
It's not possible to translate the city of a store

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#31308] opened 2023-02-10 15:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you manage stores, you are able to translate somes parts but not the city, as seen on this screen :

![Capture d’écran 2023-02-10 à 16 33 00](https://user-images.githubusercontent.com/2631425/218131353-11c0d85e-e345-45b3-9290-7fb8c91377e2.png)

### Steps to reproduce

1. Go to contact
2. Edit a store
3. See that the field is not translatable

### PrestaShop version(s) where the bug happened

1.7.8.x, 8.0.1

**Comment by hibatallahAouadni** [comment] 2023-02-13 21:14
Hello @PrestaEdit 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #30934. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-02-13 21:14
Duplicate of #30934

**Closed as completed by hibatallahAouadni** 2023-02-13 21:14 UTC
Labels: Bug, Duplicate, Invalid
