### ISSUE TITLE
Error Warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object on 1.7.4.2

### ISSUE THREAD

**Issue by PoLun-Wang** [PrestaShop/PrestaShop#12691] opened 2019-02-24 12:28 UTC
### Describe the bug
I can't upgrade any module.
When I click "upgrade" button, it will pop up an error message with "Exception thrown by module topbanner on upgrade. Warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object".
In addition, I found out it does not increase any error log after clicking "upgrade" button.

### Additionnal information
**Video:** [https://youtu.be/jNkODHMyoV0](https://youtu.be/jNkODHMyoV0)

**OS:** CentOS 7

**PrestaShop version:** 1.7.4.2

**PHP version:** 7.2.15
Name        : php
Arch        : x86_64
Version     : 7.2.15
Release     : 1.el7.remi

**PHP Modules:**
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

**Comment by khouloudbelguith** [comment] 2019-02-25 10:51
Hi @PoLun-Wang,

We are aware of this issue, it is added to our debug roadmap.
You are not logged in to the "Addons Market place" from your BO.
Your ticket is a duplicate of #11450
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-25 10:51
Duplicate of #11450

**Closed as completed by khouloudbelguith** 2019-02-25 10:51 UTC
Labels: Duplicate

**Comment by PoLun-Wang** [comment] 2019-02-25 13:02
> Hi @PoLun-Wang,
> 
> We are aware of this issue, it is added to our debug roadmap.
> You are not logged in to the "Addons Market place" from your BO.
> Your ticket is a duplicate of #11450
> So, I close it.
> Thanks!

Ok, I got it. Thank you.
