### ISSUE TITLE
bug since update facetedsearch 3.0.2

### ISSUE THREAD

**Issue by cherma1972** [PrestaShop/PrestaShop#14090] opened 2019-06-05 17:29 UTC
since the 3.0.2 update the formatting is not working anymore.
Characteristics exceed checkbox mode and in drop-down mode nothing is displayed normally
in case mode, everything is ticked in advance and decalled by one line.
the titles of the characteristics are shortened and do not appear completely.
everything is in bold

 
before  without update, module v2.2.1 
![Capture20](https://user-images.githubusercontent.com/51416502/58976575-12323500-87c8-11e9-836f-1c4372822684.PNG)
after : with update module 3.0.2
![Capture21](https://user-images.githubusercontent.com/51416502/58976599-26763200-87c8-11e9-97f4-0da8f0c90f93.PNG)

i don't understand ...
thank you
prestashop version : 1.7.2
php 7.1
sql 5.6

**Comment by Tomskor** [comment] 2019-06-06 08:45
Had this same problem, you can change one line in CSS files in module cataloge, but first try it out on your theme.

Find line: #search_filters .facet .facet-label a
and: width: calc(90% - 30px);
and try change % and test responsivity

**Comment by PierreRambaud** [comment] 2019-06-06 08:46
Hey, thanks @Tomskor is this problem general to any themes?
Want to create a pull request and help us improve this? :)

**Comment by Tomskor** [comment] 2019-06-06 09:01
@PierreRambaud I think is might be a general problem, but I am not sure this incloude every theme. I test this only on our official site, maybe I will have access to stores with other themes so can check this out with version 3.0.2.
Can you explain what you mean exactly with that? I am not a specialist. Just fixing up to date some small issues  on our store :)

**Comment by PierreRambaud** [comment] 2019-06-06 09:25
You can help us to improve the css here https://github.com/PrestaShop/ps_facetedsearch/blob/master/_dev/front/facet.scss
You can read how to contribute here if you think it's relevant: https://github.com/PrestaShop/ps_facetedsearch#contributing
And of course if you need help, we're here :smile:

**Comment by PierreRambaud** [comment] 2019-06-11 08:41
@Tomskor Can you send me a link of your website to try to find what's exactly broken?

**Comment by Tomskor** [comment] 2019-06-11 09:02
@PierreRambaud for example https://tomskor.pl/17-kurtki

but like I said before, we fixed that, changing one line:  width: calc(100% - 30px);on  width: calc(90% - 30px);

you can try use devtools and restore that line on 100% and try changing windows size and look at left column.

**Comment by cherma1972** [comment] 2019-06-11 12:19
hello : https://apy-groupe.com/fr/fr/12-stations-de-travail-sur-mesure

**Comment by cherma1972** [comment] 2019-06-11 12:52
hello, don't work 
no change, since the update of this weekend I have in addition a new error, I have all the attributes in duplicate
![Capture1106](https://user-images.githubusercontent.com/51416502/59273423-7d608900-8c58-11e9-912c-b6e5dd6ffba8.PNG)

**Comment by PierreRambaud** [comment] 2019-06-11 14:56
Hi @cherma1972 I'm not able to reproduce or maybe you fixed it?
![image](https://user-images.githubusercontent.com/1462701/59282804-c8cf6300-8c69-11e9-8ecd-09679a84dd87.png)

**Comment by cherma1972** [comment] 2019-06-11 15:26
yes , i fixed , but I don't arrive as before to have the complete titles, now, the attributes are cut by "..."

**Comment by PierreRambaud** [comment] 2019-06-11 16:07
@cherma1972 If you want to remove `...` 
just remove these lines: 
![image](https://user-images.githubusercontent.com/1462701/59288271-b3f7cd00-8c73-11e9-8147-c01c29e71385.png)

**Comment by PierreRambaud** [comment] 2019-06-19 11:40
@khouloudbelguith As I know, issues are fixed or depend on custom themes :thinking:

**Comment by khouloudbelguith** [comment] 2019-06-19 11:55
@PierreRambaud, with the classic theme, this issue is not reproduced.
![image](https://user-images.githubusercontent.com/16067358/59763414-70afe680-9291-11e9-991f-f959d534e9a4.png)

Thanks!

**Comment by marionf** [comment] 2019-07-02 09:55
@khouloudbelguith This issue can be closed if you don't reproduce it ?

**Comment by khouloudbelguith** [comment] 2019-07-02 10:03
Hi, @marionf,

Yes, in my case, I did not manage to reproduce the issue with PS1.7.6.0rc1 & ps_facetedsearch v3.0.5.
![image](https://user-images.githubusercontent.com/16067358/60504182-08adc700-9cb9-11e9-939c-8e34cde386d1.png)

I will close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-02 10:03 UTC
Labels: Bug, Can't reproduce, Faceted search
