### ISSUE TITLE
Cannot add a root category for multishop

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#27790] opened 2022-02-24 13:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
On an existing shop, I wish to create a new shop group with a new shop with different root category. But I cannot.
On a copy of the website, I had to add it by the database. Now, if I try to add a shop group with a new shop, when I click on the link to add a root category, the right page is displayed and I can add a new root category. But it's not very good. A simple user of Prestahop cannot do that !

I see I'm not the first to have this issue. It's possible to add it manually by the database. But I wish to understand why it doesn't work with the previous link.

Thanks for your help !

### Expected behavior

Create e new root category for my new shop in multishop without passing by the database

### Steps to reproduce

1. Add a new shop group.
2. Add a new shop in this group.
3. Click on the link to add a new root category
![image](https://user-images.githubusercontent.com/11886689/155533543-7757317c-0a96-41cb-866c-d8b8f7733c98.png)
4. The opened page is the classic page to add a category

### PrestaShop version(s) where the bug happened

1.7.6.4

**Comment by hibatallahAouadni** [comment] 2022-02-24 22:08
Hello @sirius82 

Your issue seems duplicate of #10942 
Could you please check it and feedback.

Thanks!

**Comment by sirius82** [comment] 2022-02-26 20:39
hello @hibatallahAouadni 
Thanks for your reply.
No, I don't think it's the same issue because I whished to create a new root category, not to change an existing to be root.
When I clicked on the link to add a category, it was the normal category page opened. If I created a new category, I could only  associate it with Home.
After to have created this root category in the database (for shop group 2), I can create a new shop group (shop group 3) with a new shop. The link to create a new category root works fine.
Thanks

**Comment by marwachelly** [comment] 2022-03-01 16:40
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/21180. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment] 2022-03-01 16:40
duplicated of https://github.com/PrestaShop/PrestaShop/issues/21180

**Closed as completed by marwachelly** 2022-03-01 16:40 UTC
Labels: Bug, BO, Duplicate, Multistore, 1.7.6.4, Invalid
