### ISSUE TITLE
Automatic actions in modules triggering by hooks and issue with employe accounts without access to the module

### ISSUE THREAD

**Issue by tvorgul** [PrestaShop/PrestaShop#22516] opened 2020-12-21 11:34 UTC
An employe is using a BackOffice account with limited permissions (ex : "Logistician" profile) and its profile does not have access to the modules. Anyway he can update the order status or do some changes in the product sheet (e.g. update the number of products in stock).
As this employe does not have access to the modules, all actions done with this account do not trigger any actions in the modules. Ex : 
- a payment module allows to update the order status to "refunded" and automatically update the status of transaction in its system.  -> The update of the order status to "refunded" (done by an employe without access to the modules) does not trigger any hook and, by consequence, does not trigger any automatic update of the transaction status, despite the module is hooked on the "actionOrderStatusUpdate".
- a marketplace module allows the real time synchronisation of stocks. -> If an employe with limited permissions updates the number of product in stock or any other information in the product sheet, this update will not trigger any hook using by the marketplace module (e.g : actionProductUpdate or actionProductSave..).

There are no problem if you do the same changes with an account that has access to the modules that are using the native hooks for triggering automatic actions.

#### Expected behavior

If an employe does some updates that can trigger some actions via a hook, this hook should be executed even if it is using by a module restricted for this employe

#### Steps to Reproduce

1. Go to 'Team-Persmissions : Logisticien' and check its permissions access (disabled for the modules).
2. Create an employe with "Logisticien" profile.
3. Install and configure any module of marketplace that has the real time synchronization features or a payment module that allows to trigger an automatic refund or a carrier module that allows the generate the labels once an order status is changed...
4. Try to do some changes in the orders or in the product using the BO account with restricted permissions and the SuperAdmin account.

#### Additional information

* PrestaShop version: any
* PHP version: any

If requested, we can provide you with some exact examples of the module but you can reproduce this issue with any module because it is a commun issue.

**Comment by hibatallahAouadni** [comment] 2020-12-21 17:22
Hello @tvorgul 

Alright, let's keep it easy :sweat_smile: 
What do you want is that the employee with **Logisticien** profile doesn't even have the right to change the order status cause it triggers the payment module, is that so?

Thanks!

**Comment by tvorgul** [comment] 2020-12-21 17:37
Hello, 


Thank you for your message.
No. The issue is that any actions done my an employe without permissions to access to some module does not trigger the automatic actions in modules via hooks.
And this is an important issue for different kind of modules, as explained in my examples.
The hooks are not executed if some changes are done by this kind of employees and this is wrong. The system should take into account the changes done by any employee and trigger the required hooks.

An additional example for another type of module : 
The carrier module generates the tracking number once the order is passed to "Processing" status. 
- If you the superadmin updates the order status it will trigger the actions in the carrier module and the tracking number will be added to the order details.
- If an employee with "Logisticien" profile change the order status, it does not trigger any actions in the module and so the tracking number is not automatically added.

There can be multiple use cases for different kind of module.


Best regards,
Tetiana Vorgul

**Comment by hibatallahAouadni** [comment] 2020-12-25 11:49
Hello @tvorgul 

What you're saying is toally correct but the problem is that I didn't manage to reproduce your issue :sweat_smile: 

1. FO, I made an order
2. I login to BO as an employee with the "Logisticien" profile
3. Change the order status to Delivered and edit the tracking number 
4. All saved without any error

See the attached screen record below:

https://drive.google.com/file/d/16cFrCNbbDsaXjlN897MzOIvMx5eB7eDt/view

> Install and configure any module of marketplace that has the real time synchronization features or a payment module that allows to trigger an automatic refund or a carrier module that allows the generate the labels once an order status is changed

=> I know that you will said these are the default modules, so there's no issue with it. But they're modules :woman_shrugging: 
_**PS: if there's any detail that I missed please tell me**_ :wink: 

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-14 11:50
Hello @tvorgul ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-14 11:50 UTC
Labels: Bug, BO, Advanced parameters, Team, No change required, 1.7.7.0
