### ISSUE TITLE
Can't upgrade faceted_search module to latest version

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#32692] opened 2023-05-24 17:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I upgraded faceted_search to the latest version [v3.12.1](https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.12.1), and I have this error message on category pages : 

Fatal error: Uncaught Error: Call to undefined method Context::getCurrentLocale() in /modules/ps_facetedsearch/src/Product/SearchProvider.php:435 Stack trace: #0 /modules/ps_facetedsearch/src/Product/SearchProvider.php(210): PrestaShop\Module\FacetedSearch\Product\SearchProvider->labelRangeFilters(Array) #1 /classes/controller/ProductListingFrontController.php(311): PrestaShop\Module\FacetedSearch\Product\SearchProvider->runQuery(Object(Context), Object(PrestaShop\PrestaShop\Core\Product\Search\ProductSearchQuery)) #2 /classes/controller/ProductListingFrontController.php(545): ProductListingFrontControllerCore->getProductSearchVariables() #3 /controllers/front/listing/CategoryController.php(137): ProductListingFrontControllerCore->doProductSearch('catalog/listing...', Array) #4 /classes/controller/Controller.php(281): CategoryControllerCore->initContent() #5 /var in /modules/ps_facetedsearch/src/Product/SearchProvider.php on line 435

### Steps to reproduce

1. Install ps_faceted_search 3.12.1
2. Go to a category page
3. See the error 500, or fatal error in debug mode

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_faceted_search 3.12.1

**Comment by hibatallahAouadni** [comment] 2023-05-26 16:55
Hello @guigplt 

I didn't manage to reproduce the issue with PS1788 nor with PS804.
Could you please upgrade your shop and check if you still encounter the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-06-12 10:26
Hello @guigplt 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-06-12 10:26 UTC
Labels: Bug, FO, Faceted search, 1.7.5.1, Invalid, Module
