### ISSUE TITLE
Order Confirmation Table data broken when buying a product with customization

### ISSUE THREAD

**Issue by angelocipullo** [PrestaShop/PrestaShop#35582] opened 2024-03-07 21:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 
This is the bug -> if you buy a product with customization and combinations, and then you go to check the history of that order or the order confirmation, the row total it's broken.

- Product should be: with combinations and customization.

![Screenshot 2024-03-07 alle 22 45 30](https://github.com/PrestaShop/PrestaShop/assets/23438992/f090ca62-65af-41e2-b388-5df20274f467)

### Expected behavior

Total should be 3.00 instead of 1.00 ( 1.00 it's the original price of the product, 2.00 it's the impact of the combination)

### Steps to reproduce

1. Buy product with combination and customization.
2. Go to checkout, complete the order
3. Here's the order summary that is broken.

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

7.1

**Comment by florine2623** [comment] 2024-03-08 08:24
Hello @angelocipullo ,

I can't reproduce your issue.

Could you send the parameters of your product ?
<img width="1118" alt="Screenshot 2024-03-08 at 09 23 23" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b019787b-b330-4627-b997-2465493027da">

Waiting for your feedback.
Thanks

**Comment by angelocipullo** [comment] 2024-03-08 08:31
Hi @florine2623,

This is the product that i've used to open the issue (http://boxdeliverydevelop.live-website.com/it/home/1-1-test.html#/1-taglia-l/3-colorec-rosso)

Try to:
- Create a product with a base price
- Create more than 1 combination with impact on price
- Buy a combination that has impact on price

**Comment by florine2623** [comment] 2024-03-08 08:50
I see no issue with that config.

<img width="701" alt="Screenshot 2024-03-08 at 09 34 50" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/15745c26-0be4-4dec-8207-a5b175d66f30">

<img width="1201" alt="Screenshot 2024-03-08 at 09 34 43" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d062bbff-ae16-4b27-a333-31d9201d19ff">

**Comment by angelocipullo** [comment] 2024-03-08 08:53
Mhh that's so strange, i replicated this issue in 2 different prestashop istances.

This is my product config
![image](https://github.com/PrestaShop/PrestaShop/assets/23438992/cdbce455-ea44-4c97-ac23-7db3c1a36626)

Last thing you can try is to add more than 1 attribute, and try to buy a combination with 2 attributes.

**Comment by florine2623** [comment] 2024-03-08 08:58
I followed your configuration :

<img width="1340" alt="Screenshot 2024-03-08 at 09 58 02" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5b18959f-20c5-403f-b364-fd8cc44deedd">

And here's the result :
<img width="1114" alt="Screenshot 2024-03-08 at 09 57 24" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5b1c0042-116f-4336-96ac-e92c9878842a">

**Comment by angelocipullo** [comment] 2024-03-08 09:18
Mhh really don't know what to say, this sound so strange to me.
This is the order confirmation: http://boxdeliverydevelop.live-website.com/en/order-confirmation?id_cart=3&id_module=29&id_order=3&key=59f7a2839c64d6252b5bf01af62f6f66

What you see in the order confirmation table?

**Comment by florine2623** [comment] 2024-03-08 09:27
I see the same thing as you sent earlier

**Comment by florine2623** [comment] 2024-03-26 14:03
Hello,

Since we had no news from you for, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2024-03-26 14:03 UTC
Labels: Bug, FO, Combinations, Product customization, 8.1.x
