### ISSUE TITLE
"Write your review" button is displayed only if you change combination or quantity in product preview modal 

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29008] opened 2022-07-08 09:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![scrnli_7_8_2022_9-37-10 AM](https://user-images.githubusercontent.com/90208051/177958686-32cbf21e-e004-4084-8c4c-57f434a4d422.png)
![scrnli_7_8_2022_9-37-30 AM](https://user-images.githubusercontent.com/90208051/177958684-3fe18a16-c4a1-40c0-8d90-d973de239a56.png)

See video:

https://user-images.githubusercontent.com/90208051/177958785-bcfc051c-247c-48c9-8888-f89cb5d0b98d.mp4

### Expected behavior

"Write your review" button is displayed then you open the modal

### Steps to reproduce

1. Open FO page
2. Open preview product modal 
3. Check "Write your review" button is not displayed
4. Change combination or quantity  
5. Check "Write your review" button is displayed now

### PrestaShop version(s) where the bug happened

1.7.7.0 - 8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_productcomments

**Comment by hibatallahAouadni** [comment] 2023-03-06 09:52
Duplicate of #29863

**Closed as completed by hibatallahAouadni** 2023-03-06 09:52 UTC
Labels: Bug, Duplicate, Front-end, Productcomments, 1.7.7.0, Module
