### ISSUE TITLE
Error in ty change the language

### ISSUE THREAD

**Issue by juank2808** [PrestaShop/PrestaShop#12736] opened 2019-02-27 10:37 UTC
hi again, i have a proble with the spanish translations, first a message comes out that said, that the folder didn't exist now, in mas test version i have the folder and I have copied and pasted the folder in the same site now i have this error; do you know the solution?
__An exception occurred while executing 'SELECT p0_.id_translation AS id_translation_0, p0_.`key` AS key_1, p0_.translation AS translation_2, p0_.domain AS domain_3, p0_.theme AS theme_4, p0_.id_lang AS id_lang_5 FROM ps_translation p0_ WHERE p0_.id_lang = ? AND p0_.theme IS NULL AND (p0_.domain REGEXP ?) = 1' with params [1, "^Admin_"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smsportnutrition1_0.ps_translation' doesn't exist_*

**Comment by khouloudbelguith** [comment] 2019-02-27 10:40
Hi @juank2808,

After copying the folder, did you cleared cache manually? you need to delete it.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by juank2808** [comment] 2019-02-27 10:56
now i cant access to the side menu cause **500 Internal Server Error** now i'm blocked

**Comment by khouloudbelguith** [comment] 2019-02-27 11:02
@juank2808, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by juank2808** [comment] 2019-02-27 11:11
hi again i dont know if the correct site to see errors but and i dont know if is useful, but i found this in */var/log/prod.log
**[2019-02-27 12:05:28] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT p0_.id_translation AS id_translation_0, p0_.`key` AS key_1, p0_.translation AS translation_2, p0_.domain AS domain_3, p0_.theme AS theme_4, p0_.id_lang AS id_lang_5 FROM ps_translation p0_ WHERE p0_.id_lang = ? AND p0_.theme IS NULL AND (p0_.domain REGEXP ?) = 1' with params [1, "AdminActions"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smsportnutrition1_0.ps_translation' doesn't exist" at /var/www/vhosts/smsportnutrition.com/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT p0_.id_translation AS id_translation_0, p0_.`key` AS key_1, p0_.translation AS translation_2, p0_.domain AS domain_3, p0_.theme AS theme_4, p0_.id_lang AS id_lang_5 FROM ps_translation p0_ WHERE p0_.id_lang = ? AND p0_.theme IS NULL AND (p0_.domain REGEXP ?) = 1' with params [1, \"AdminActions\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'smsportnutrition1_0.ps_translation' doesn't exist at /var/www/vhosts/smsportnutrition.com/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smsportnutrition1_0.ps_translation' doesn't exist at /var/www/vhosts/smsportnutrition.com/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smsportnutrition1_0.ps_translation' doesn't exist at /var/www/vhosts/smsportnutrition.com/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []**

**[2019-02-27 12:05:28] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []**

**Comment by khouloudbelguith** [comment] 2019-02-27 11:15
@juank2808, I need some other informations to unterstand how to reproduce the issue:
* server setup and configuration
* PrestaShop version (source)

Thanks!

**Comment by juank2808** [comment] 2019-02-27 11:19
the server configuration is
memory_limit **512M**
max_execution_time **30**
max_input_time  **60**
post_max_size **8M**
upload_max_filesize  **2M**
the restashop version is the **1.7.5.1** before i had the 1.6.1.23 version

**Comment by khouloudbelguith** [comment] 2019-02-27 11:24
@juank2808, for the post_max_size, the value required minimum 16MB.
About the upload_max_filesize, the required minimum value is 4MB.
Thanks to check & feedback

**Comment by juank2808** [comment] 2019-02-27 11:27
but do you think that this can solution my **500 Internal Server Error** ?

**Comment by khouloudbelguith** [comment] 2019-02-27 11:29
@juank2808, no, but it is required.
It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.1.
You can find the full schema for 1.7.5.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by juank2808** [comment] 2019-02-27 11:37
@khouloudbelguith what do I do with that, I have important data and I have to copy and paste the SQL is likely to show an error?

**Comment by khouloudbelguith** [comment] 2019-02-27 13:14
@juank2808,

> I have to copy and paste the SQL is likely to show an error?

Sorry, I did not understand you, I just told you to check your database if there are missing tables.
Thanks!

**Comment by juank2808** [comment] 2019-02-27 15:25
ok mi english is bad sorry, o have this error 
**Table 'smsportnutrition1_0.ps_translation' doesn't exist<br /><br /><pre>
SELECT `key`, `translation`, `domain`
FROM `ps_translation`
WHERE `id_lang` = 1**

**Comment by khouloudbelguith** [comment] 2019-02-27 15:45
@juank2808, the table ps_translation doesn't exist in your Database
in my case when I run this SQL command 

`Select * from ps_translation` I have this table
![image](https://user-images.githubusercontent.com/16067358/53502766-05a68e00-3aaf-11e9-8128-5f41d94aafb3.png)

Thanks!

**Comment by juank2808** [comment] 2019-02-27 15:47
ok, and now what is the solution?

**Comment by khouloudbelguith** [comment] 2019-02-27 15:51
@juank2808, The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.5.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/install-dev/data/db_structure.sql
Thanks!

**Comment by juank2808** [comment] 2019-02-27 15:55
ok but in this SQL dont exist this table, i have the table structure in my test table and i will try, pls dont clise the issue

**Comment by khouloudbelguith** [comment] 2019-02-27 15:57
@juank2808, did you use a theme different from the provided by PrestaShop?
Thanks!

**Comment by juank2808** [comment] 2019-02-27 16:02
no, i have the 1.7.5 version, now i have other error with the data base, 
![imagen](https://user-images.githubusercontent.com/14195668/53503954-5919db80-3ab1-11e9-86f3-2faaeb632966.png)

**Comment by juank2808** [comment] 2019-02-27 16:15
hi again, i have a small error, the SQL is solved, but now i have error with a module forlder in this case is eBay  @khouloudbelguith 
![imagen](https://user-images.githubusercontent.com/14195668/53505004-5324fa00-3ab3-11e9-9c10-277e33cf62ee.png)

**Comment by khouloudbelguith** [comment] 2019-02-27 16:26
@juank2808, as it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by juank2808** [comment] 2019-02-27 16:30
ok no problem, an thanks but now, I do not have any module but the folders of the modules if it exists, is it safe to delete them if I do not have any module installed?

**Comment by khouloudbelguith** [comment] 2019-02-27 16:34
@juank2808, if you need to disable a module, you can just rename the folder module from `mymodule` to `mymodule_old`.
Thanks!

**Comment by juank2808** [comment] 2019-02-27 16:36
ok thanks again! now you can close the issue, thank you so much!

**Comment by khouloudbelguith** [comment] 2019-02-27 16:37
@juank2808, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-27 16:37 UTC
Labels: Translations, No change required
