### ISSUE TITLE
Issue when marque(brand) and feature value have same name

### ISSUE THREAD

**Issue by openpresta** [PrestaShop/PrestaShop#32172] opened 2023-04-14 22:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when you create a marque (brand) with a name for example 'X' 
and you create a feature and attribute a value named 'X' , 
module  ps_facetedsearch  not work and it return with empty products when you filter by brand.

### Steps to reproduce

1. create marque X 
2. create feature Y and put a X as feature value
3. associate a product to this marque 
4. generate a filter with ps_facetedsearch
5. check in front office

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

ps_facetedsearch

**Comment by Hlavtox** [comment] 2023-04-17 13:13
Hi @openpresta, this is the same issue as this - https://github.com/PrestaShop/PrestaShop/issues/15635.
I will try to fix it in some future version of ps_facetedsearch.

We will need to change the URLs faceted search generates, because the module doesn't know if it's a brand, attribute or feature.

**Comment by hibatallahAouadni** [comment] 2023-04-18 08:21
Hello @openpresta 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15635. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @Hlavtox for your quick reply 🚀 

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-04-18 08:22
Duplicate of #15635

**Closed as completed by hibatallahAouadni** 2023-04-18 08:21 UTC
Labels: Bug, Duplicate, Invalid
