### ISSUE TITLE
Partial Refund

### ISSUE THREAD

**Issue by aurelienljd** [PrestaShop/PrestaShop#32538] opened 2023-05-11 13:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On Prestashop 1.7.8.7,
I try to do a partial refund and sometimes I've got an error :  [PrestaShop\PrestaShop\Core\Domain\Shop\Exception\ShopException code 0]
Sometimes it's because "shopId must be greater than 0".

The error occurs on both monostore and multistore installation, but not on all orders.

I've tried from a fresh install (but using theme and db of websites which have the issue) and the error still occur

### Steps to reproduce

Go to an order, and do a partial refund

### PrestaShop version(s) where the bug happened

17.8.7

### PHP version(s) where the bug happened

both 7.2 or 7.3

**Comment by AureRita** [comment] 2023-05-11 14:33
Hi @aurelienljd 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ May 11, 2023 4_32 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1cff7ce1-3d84-48f7-b0a1-96f572d8873c)

But I currently can't reproduce your issue, did I miss something ? 
Did you have more details about this issue ? 

Waiting for your feedback

**Comment by aurelienljd** [comment] 2023-05-11 14:38
Hello @AureRita 
It seems the issue is really hard to reproduce.
You can see issues #30572 and #32165 which seems to be the same problem.

**Comment by djoelleuch** [comment] 2023-05-18 16:10
Hello @aurelienljd ,

Despite our efforts, we were not able to reproduce your issue with the provided information. 

[Untitled_ May 18 2023 6_09 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/a90069ab-f17b-4285-b2af-bdec8fb5b022)



We will close this issue.
Thank you !

**Closed as not planned by djoelleuch** 2023-05-18 16:10 UTC
Labels: Bug, BO, Order, Invalid, 1.7.8.7
