### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by Ayman4** [PrestaShop/PrestaShop#11950] opened 2018-12-29 15:43 UTC
I installed prestashop on godaddy shared hosting with php 5.6 

each time i login to admin page i got an error for catalogue 
"No input file specified."

Any help, please

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-12-31 08:39
Hi @Ayman4 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks, 
Khouloud

**Comment by khouloudbelguith** [comment] 2019-02-01 16:48
Hi @Ayman4,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-01 16:48 UTC
Labels: Catalog, No change required
