### ISSUE TITLE
Add order from backoffice

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#16380] opened 2019-11-12 17:53 UTC
**Describe the bug**
I am unable to add order from Back Office

**To Reproduce**
1. Go to 'Sales / Orders'
2. Click on 'Add new order'
3. Select customer
4. Search for product
5. No response - in developers tools I can see error 500

**Stacktrace**

```
PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException:
Price specification not found for currency: ""
  at src/Core/Localization/Locale.php:171
  at PrestaShop\PrestaShop\Core\Localization\Locale->getPriceSpecification('')
     (src/Core/Localization/Locale.php:155)
  at PrestaShop\PrestaShop\Core\Localization\Locale->formatPrice(34.9, null)
     (classes/Tools.php:776)
  at ToolsCore::displayPrice(34.9, object(Currency))
     (controllers/admin/AdminOrdersController.php:1965)
  at AdminOrdersControllerCore->ajaxProcessSearchProducts()
     (classes/controller/AdminController.php:944)
  at AdminControllerCore->postProcess()
     (controllers/admin/AdminOrdersController.php:1629)
  at AdminOrdersControllerCore->postProcess()
     (classes/controller/Controller.php:281)
  at ControllerCore->run()
     (classes/Dispatcher.php:515)
  at DispatcherCore->dispatch()
     (adminVnkKyquMHj3XtuMVhSY2U8ra/index.php:97)
```

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

Related to #15269

**Comment by khouloudbelguith** [comment] 2019-11-13 07:56
Hi @Flower7C3,

The issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/15643
It is fixed in the PS1.7.6.2.
Your ticket is a duplicate of #15376
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-13 07:56
Duplicate of #15376

**Closed as completed by khouloudbelguith** 2019-11-13 07:56 UTC
Labels: Duplicate
