### ISSUE TITLE
Product discounts based on quantity showing incorrect prices

### ISSUE THREAD

**Issue by krasnycz** [PrestaShop/PrestaShop#10707] opened 2018-09-25 15:51 UTC
When you set discounts on the product based on quantity, wrong prices are showing on the product page however correct price is used in the shopping price and catalog.

1. Ensure you have set to show discounted price to YES at settings > products > page of the product
2. On the product page in the BO set special price for the product from 1 pcs  e.g. -100 USD.
3. Set other special price for same product from 2 pcs e.g. -150 USD.
4. Now check the product page. Lets say base product price is 1000 USD. There will be automatic discount showing on the product page to 900 USD. And table indicating that there is different price for 2 and more pcs. It should say price from 2 pcs is 850 USD but it will display 750 USD instead. Because it will deduct discount for 1 pcs and then discount for 2 pcs. If you add product to the cart it will use correct price of 900 USD.

PrestaShop version: 1.7.4.2

**Comment by khouloudbelguith** [comment] 2018-09-25 16:04
Hi @krasnycz,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9872
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-25 16:04
Duplicate of #9872

**Closed as completed by khouloudbelguith** 2018-09-25 16:04 UTC
Labels: Duplicate

**Comment by krasnycz** [comment] 2018-09-25 16:45
#9872 is about not updating % discount of the price depending on quantity. This ticket identifies a bug related to displaying quantity based discounts in currency not % discount. This issue/case is not covered in #9872.

**Comment by khouloudbelguith** [comment] 2018-09-26 10:06
Hi @krasnycz,

Done.
