### ISSUE TITLE
Product features without a feature ID duplicate on their own

### ISSUE THREAD

**Issue by mrl22** [PrestaShop/PrestaShop#22352] opened 2020-12-10 23:42 UTC
#### Describe the bug

If you add feature to a product and do not select a feature from the "choose a feature" list, it will save fine. Every time you save the product going forward it will duplicate that feature over and over. You can not edit or remove these duplicated features and the only way to fix is to delete the product and start again. Tested with all modules and overrides off.

#### Expected behavior

When you save a product, it should check if any of the product features do not have a feature selected. It should error and not save.

#### Steps to Reproduce

1. Go to edit a product.
2. Add a new feature but do not select a feature from the drop down, leave it on "select a feature", add custom value.
3. Save the page multiple times.
4. Refresh the page and you will see multiple features that shouldn't be there.
5. If you now save the page with multiple features with "choose a feature" selected, it will duplicate them all. For example 5 becomes 10.

Video: [https://www.youtube.com/watch?v=AQPvBwdYeu0](https://www.youtube.com/watch?v=AQPvBwdYeu0)

#### Additional information

* PrestaShop version: Tested on 1.7.4.1 and 1.7.7.0
* PHP version: 7.1

**Comment by mrl22** [comment] 2020-12-11 00:18
My quick hack for this:

I added the following code to the top of `ProductCore::addFeaturesToDB` function:

`if ($id_feature < 1) {`
`    $features = FeatureCore::getFeatures(2);`
`    $id_feature = $features[0]['id_feature'];`
`}`

This forcing any saved features that have no feature selected to use the first dropdown feature in the database. Not the perfect solution, but something needed to be done as my client is having to delete their products when they come across this issue.

I think that when a feature is not selected from the dropdown, it should be calling the `addFeaturesCustomToDB` function inside `AdminProductsControllerCore::processFeatures`, but its actually calling `addFeaturesToDB` as the data posted is not formatted correctly.

**Comment by mrl22** [comment] 2020-12-11 00:49
On further investigation to fix this properly. When adding a feature without a selected feature from the dropdown (id_feature), `AdminProductsControllerCore::processFeatures` > `ProductCore::addFeaturesToDB` adds a value of 0 to the `id_feature` column in the `ps_feature_value` table.

The problem with this is that the `getFeature`, `getFeatures` and I guess other functions throughout the platform runs an SQL query which left joins the `ps_feature_shop` on `ps_feature_value.id_feature = ps_feature_shop.id_feature` with a where statement on `ps_feature_shop.shop_id = 1`. If id_feature is 0 then it has nothing to left join in the `ps_feature_shop` table.

When saving a product, `ProductCore::deleteFeatures` is trying to get a list of all features to delete them before re-adding them. As `id_feature` = 0 on the features with no selected feature from the dropdown, they are not returned in the SQL query to be deleted. So they get left in the database and get added again and again on every save.

**Comment by florine2623** [comment] 2020-12-11 08:25
Hi @mrl22 ,

Thanks for the report.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16306.
To be informed when it's fixed, please subscribe to the issue mentioned above.
If you have the solution, you could create a PR, and I'll link it to the original issue.

Thanks!

**Closed as completed by florine2623** 2020-12-11 08:25 UTC
Labels: Duplicate, Features, 1.7.7.0

**Comment by florine2623** [comment] 2020-12-11 08:50
Duplicate of #16306
