### ISSUE TITLE
Impossible to show product in different categories

### ISSUE THREAD

**Issue by francct** [PrestaShop/PrestaShop#16925] opened 2019-12-26 12:49 UTC
**Describe the bug**
Hi,
I have only selected one subcategory on several products, but they are also visible on the mother category page. How can I show the products only in the categories I have selected (even multiple)?

I tried to deactivate "show products from subcategories" through the "Faceted search" module, but in this case the product is only visible in the default category. I want to show it in different categories but not automatically in the mother category.

How can i resolve?

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.26

**Comment by khouloudbelguith** [comment] 2019-12-26 13:15
Hi @francct,

The button "Show products from subcategories" is here to only display products that are in the "Main category" not the latest one.
Otherwise where it should be displayed if you have this:
![image](https://user-images.githubusercontent.com/1462701/58570390-2dd19480-8238-11e9-8d30-98d955a13485.png)
![image](https://user-images.githubusercontent.com/1462701/59031604-70145a80-8864-11e9-9255-bb486e3fbd50.png)
As you can see on the top right corner, it's written `Main category` not `Default category`.

In my situation, and if I take your definitions.
- `Clothes` is the main category for `Women` but not for `Men` and is not a subcategory of `Home`
- `Men` is the `Main category` for `Awesome subcategory` and not a subcategory for `Men`
- `Women` is a subcategory for `Clothes`

Thanks to check & feedback.

**Comment by francct** [comment] 2019-12-26 13:54
Hi @khouloudbelguith, thanks for your reply!
I'm sorry, I misspelled "default category" instead of "main category"

Anyway this is the situation:
I have two products setted in this way
![t-shirt](https://user-images.githubusercontent.com/59253436/71478102-1c606300-27ee-11ea-8351-2bb8d7ed5778.png)
![sweater](https://user-images.githubusercontent.com/59253436/71478101-1c606300-27ee-11ea-8f5b-4f01ac6cf09e.png)

I want to show "t-shirt" on both "men and clothes categories".
Instead I want to show "sweater" only on "women category".

Unfortunately "clothes" category shows both products
![Clothes](https://user-images.githubusercontent.com/59253436/71478099-1bc7cc80-27ee-11ea-80f8-511b547bcf45.png)

**Comment by khouloudbelguith** [comment] 2019-12-26 14:24
@francct, 

Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14003#issuecomment-499420416
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-26 14:24
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/14003

**Closed as completed by khouloudbelguith** 2019-12-26 14:24 UTC
Labels: Bug, FO, Duplicate, Categories, Faceted search, 1.7.6.2
