### ISSUE TITLE
How to remove id_product_attribute from product links?

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#17879] opened 2020-02-27 19:26 UTC
Hello there.

Is there a way to remove id_product_attribute from {category:/}{id}-{rewrite}{id_product_attribute}{-:ean13}.html

So links doesnt look a bit strange.

I.e instead of https://mywebsite.pl/strona-glowna/1407-legginsy-adidas-essentials-3-stripes-fm6991.html#/195-rozmiar-164

I would love to see it like https://mywebsite.pl/strona-glowna/1407-legginsy-adidas-essentials-3-stripes-fm6991.html

A lot of this issues in old google guides but its not working.

Using version: 1.7.6.3 ( also tried on 1.7.5.1 )

**Comment by Gipielle** [comment] 2020-02-27 22:44
This problem is present since 2014 :-)
Wait ...

**Comment by khouloudbelguith** [comment] 2020-02-28 10:42
Hi @GTriber,

Recently we have made some modifications related to the SEO OPTIMIZATION in the product page.
You can follow those links: #9463, #9456
About the bad URL when the product has combinations, we have also this issue #9784, it is added to our bug roadmap, so that will be fixed.
Your ticket is a duplicate of #9784
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-28 10:42
Duplicate of #9784

**Closed as completed by khouloudbelguith** 2020-02-28 10:42 UTC
Labels: Duplicate
