### ISSUE TITLE
Product search by ref in the stock page doesn't work (while in the stock movements works)

### ISSUE THREAD

**Issue by Mauretta88** [PrestaShop/PrestaShop#26545] opened 2021-11-07 23:22 UTC
#### Describe the bug 

I have products with combinations. The product itself and each one of the combination have a ref code.
If i search a product by it's ref, in the stock page i'm only able to find the original product, not the combinations.
In the stock movement page, i'm able to make it work.

#### Expected behavior and what happen

Example: i have a product named "slippers" with a ref code "abc". There are 4 combinations for this product: 1: n°36 (ref code "1"), 2: n°37 (ref code "2"), 3: n°38 (ref code "3"), 4: n°39 (ref code "4").

In the stock page, if i search for "abc", i find all the combinations. If i search for "1" i find no results. Idem if i search for "abc 1".

In the stock movement page i have these results: for "abc" i find all the combinations. for "1" i find the combination "n°36", same result if i search for "abc 1".

Why the stock page search doesn't work like the stock movement one?

#### Steps to reproduce 

1. ![1](https://user-images.githubusercontent.com/93884102/140665598-8c7cfa31-e515-4475-bfcc-384cdd925d1b.png)

2. ![2](https://user-images.githubusercontent.com/93884102/140665605-ccfdeda0-b7e5-4455-8d1c-e9f429de7109.JPG)
3. ![3](https://user-images.githubusercontent.com/93884102/140665609-d10420f2-5854-4017-9be7-974128370b62.JPG)
4. ![4](https://user-images.githubusercontent.com/93884102/140665631-cbaf103f-2f9d-44bd-a550-003810084129.JPG)
5. ![5](https://user-images.githubusercontent.com/93884102/140665632-cec10816-f78f-455f-9b1f-d22e1da21744.JPG)
6. ![6](https://user-images.githubusercontent.com/93884102/140665636-7bf3580d-7cf2-44a9-9450-6dc0eda3a068.JPG)
7. ![12](https://user-images.githubusercontent.com/93884102/140665641-ac721fe9-f9f8-4d61-8f88-71878bfa8548.JPG)
8. ![7](https://user-images.githubusercontent.com/93884102/140665642-7f5e61a0-396d-4a2d-8899-1b7392f3ab55.JPG)
9. ![8](https://user-images.githubusercontent.com/93884102/140665645-616dd767-e8e2-4c6b-a91b-510581f3f560.JPG)
10. ![9](https://user-images.githubusercontent.com/93884102/140665646-ddf68835-53eb-4c4a-8edc-312f990f7f4e.JPG)
11. ![10](https://user-images.githubusercontent.com/93884102/140665647-f9c5ac17-52b0-4eb2-9022-f6b7a79b2908.JPG)
12. ![11](https://user-images.githubusercontent.com/93884102/140665649-e5d277c7-57c5-4d85-aaf9-e7c01364c917.JPG)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3.26
* I'm using XAMPP

**Comment by hibatallahAouadni** [comment] 2021-11-09 08:25
Hello @Mauretta88 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9727. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-09 08:25
Duplicate of #9727

**Closed as completed by hibatallahAouadni** 2021-11-09 08:25 UTC
Labels: Duplicate, Invalid
