### ISSUE TITLE
Translation problem on product create page

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#25455] opened 2021-07-28 19:40 UTC
#### Describe the bug

This term is not french
![image](https://user-images.githubusercontent.com/4645967/127385346-97cbac4b-bfbb-43c5-9a98-e45e0d2f906b.png)

#### Expected behavior

Explain what you expected to happen instead.
"Ce champs ne peut pas être vide"

#### Steps to Reproduce

1. Go to product list
2. Go to add new product
3. Create a product without title
4. Look at this translation problem

**Screenshots**

![image](https://user-images.githubusercontent.com/4645967/127385346-97cbac4b-bfbb-43c5-9a98-e45e0d2f906b.png)

#### Additional information

* PrestaShop version: 1.7.7.4

**Comment by hibatallahAouadni** [comment] 2021-07-29 12:02
Hello @henri9813 

I reproduce the issue with PS1767, PS1775, PS178x and develop, See the attached screenshot: 

![image](https://user-images.githubusercontent.com/23308427/127487956-c4839208-1570-40c0-b41c-7baf985e6acc.png)

On develop, it's getting worst, the new error message is duplicated (New Regression on develop):

![image](https://user-images.githubusercontent.com/23308427/127488158-1f4c8ff1-9778-43a8-abb9-2c2139f56596.png)

And, in BO>International>Translaions, I searched this sentence to translate it but I didn't find it:

![image](https://user-images.githubusercontent.com/23308427/127488746-8df41e26-3457-4132-af79-4adfa6cc731b.png)

So, thanks again for your report! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: I searched everywhere but I didn't find the original issue. So, @khouloudbelguith if you find the original one please close this one as a duplicate :wink: 

Thank you

**Comment by matks** [comment] 2023-09-21 10:02
Hello in PrestaShop 8.1.0 the product page has been reworked and I just verified: the bug is fixed on the new product page 🎉

**Closed as completed by matks** 2023-09-21 10:02 UTC
Labels: Bug, Minor, BO, Translations, Fixed, 1.7.6.7, Verified
