### ISSUE TITLE
Seo preview only change with first language

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18278] opened 2020-03-23 23:38 UTC
Go in product, seo tab
change language to a different form the default 
change meta title o meta description.
Nothing change in seo preview 

Primary language is ok - (Maybe backoffice lang)

* PrestaShop version: 1.7.6.3
* PHP version: 7.2
<img width="1191" alt="Schermata 2020-03-24 alle 00 36 35" src="https://user-images.githubusercontent.com/5024055/77373131-a9707500-6d67-11ea-8eb6-cc1c43682fcd.png">
<img width="1206" alt="Schermata 2020-03-24 alle 00 36 13" src="https://user-images.githubusercontent.com/5024055/77373135-abd2cf00-6d67-11ea-9599-0d549be50944.png">

Italian ok
English no

**Comment by khouloudbelguith** [comment] 2020-03-24 08:02
Hi @Betafer,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #17688
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-24 08:02
Duplicate of #17688

**Closed as completed by khouloudbelguith** 2020-03-24 08:02 UTC
Labels: Duplicate

**Comment by Betafer** [comment] 2020-03-24 08:05
Ok thanks !
