### ISSUE TITLE
1 click upgrade from Prestashop 8.0.4 to 8.1.0 fails

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33513] opened 2023-07-31 21:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

1 click upgrade from Prestaashop 8.0.3 to 8.1.0 produces the following error:

One CLick upgrade fails from Pres
23:09:20 CRITICAL [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "There is no active transaction" ["exception" => PDOException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => "There is no active transaction"]
In Connection.php line 1854:
There is no active transaction
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]

### Steps to reproduce

Use the 1 click upgrade module to update a Prestashop 8.0.3 install to Prestashop 8.1.0

### PrestaShop version(s) where the bug happened

8.0.4

**Comment by musaffarpatel** [comment] 2023-07-31 21:28
The same error occurs both locally and on my live host, therefore not an isolated issue

**Comment by kpodemski** [comment] 2023-07-31 21:38
I confirm this issue. It is a duplicate, but you're not the first person reporting it.

cc @Hlavtox 

QA: no need to re-test it, it is not easily reproducible.

**Comment by musaffarpatel** [comment] 2023-07-31 21:42
@kpodemski Thanks, do you think there will be a fix to this anytime soon?  We need to decide whether to hold fire on our project or not depending on whether or not we can upgrade

**Comment by kpodemski** [comment] 2023-07-31 21:46
@musaffarpatel hard to tell, we couldn't reproduce this issue - it is not a global issue, it is related to the environment configuration

@Hlavtox had more details, so let's wait for him to share more infos

**Comment by musaffarpatel** [comment] 2023-07-31 21:49
@kpodemski if it helps I can give @Hlavtox access to my hosting where the error occurs

**Comment by kpodemski** [comment] 2023-07-31 21:52
@musaffarpatel, no need, it won't guarantee any faster fix, etc.

**Comment by sallemiines** [comment] 2023-08-01 09:40
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of [#32547](https://github.com/PrestaShop/PrestaShop/issues/32547).
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed by sallemiines** 2023-08-01 09:40 UTC
Labels: Bug, Duplicate, Invalid

**Comment by rbuelund** [comment] 2023-09-07 17:57
I get the same error when trying to update with the 1-click module from 8.0.2 to 8.05 - is this the same problem ?

**Comment by musaffarpatel** [comment] 2023-09-07 18:02
@rbuelund You can try disabling / removing the GPDR module before upgrading, which is what worked for me.

**Comment by rbuelund** [comment] 2023-09-07 18:23
Is it then possible to add/activate it afterwards again ?

**Comment by rbuelund** [comment] 2023-09-18 18:51
Is there a fix on the way for this problem ??

**Comment by matks** [comment] 2023-09-18 20:21
> Is it then possible to add/activate it afterwards again ?

Yes. You can do this
1. Disable the GDPR module
2. Process to the upgrade of your shop
3. Open your shop after upgrade, re-enable the GDPR module

> Is there a fix on the way for this problem ??

The root cause is this https://github.com/PrestaShop/PrestaShop/issues/33874

Yes it will be fixed but it will take quite a lot of time as the problem has huge impacts.

But a small fix, just for GDPR module, has been submitted and merged https://github.com/PrestaShop/psgdpr/pull/214 and will be released this week with GDPR module 2.0.2

**Comment by rbuelund** [comment] 2023-10-05 04:24
My GDPR module is still 1.4.2 - has this fix been released ??
