### ISSUE TITLE
Attribute list not displaying in backoffice

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#11568] opened 2018-11-29 23:56 UTC
**Describe the bug**
I can't see the attribute list in the backoffice althought the attributes are created.

**To Reproduce**
Updated from 1.7 to 1.7.4.4 with 1click autoupgrade. This is extremely odd since i hadn't any error while upgrading and everything is working properly, but the div is empty???? Where should I start to check if the file is broken???

**Screenshots**
![capture](https://user-images.githubusercontent.com/7015860/49259667-a34fda00-f43a-11e8-8cce-72b01fa24225.PNG)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

As always thank you for the support.

**Comment by dineshbadrukhiya** [comment] 2018-11-30 04:42
Hello @ChineseNorris 
It's seems like [https://github.com/PrestaShop/PrestaShop/issues/9627](https://github.com/PrestaShop/PrestaShop/issues/9627)
Here is PR to fix it: [https://github.com/PrestaShop/PrestaShop/pull/10924](https://github.com/PrestaShop/PrestaShop/pull/10924)

**Comment by khouloudbelguith** [comment] 2018-11-30 08:06
Hi @ChineseNorris,

This issue occurs when you delete the language with id_language=1.
@dineshbadrukhiya said it is fixed in the next release 1.7.6.0 with this [PR](https://github.com/PrestaShop/PrestaShop/issues/9627)
Your ticket is a duplicate of #9627
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-30 08:06 UTC
Labels: Duplicate

**Comment by ChineseNorris** [comment] 2018-11-30 11:40
Thanks for the fix @dineshbadrukhiya you are the man!
