### ISSUE TITLE
Can't create new or save exiting product 

### ISSUE THREAD

**Issue by nazimgel** [PrestaShop/PrestaShop#14928] opened 2019-07-31 08:37 UTC
**Describe the bug**
I can not create new or save exiting product anymore.

**To Reproduce**
1. Go to 'Catalog / Products'
2. Click on 'New Product' or 'Existing product'
3. Click on 'Save'
4. See error 'Unable to update settings'

**Screenshots**
https://drive.google.com/file/d/1pjAG93ybYhiQoFYJpNqdYPgXF0DVkdrL/view
![local-image-2019-07-31_11_28](https://user-images.githubusercontent.com/5391796/62196883-7cf68b80-b387-11e9-8b93-36fe3989a9c9.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment] 2019-07-31 08:40
Hi @nazimgel,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - debug mode report
 - PHP error logs
 - apache error log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-30 07:19
Hi @nazimgel, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-30 07:19 UTC
Labels: Bug, BO, No change required, 1.7.6.0
