### ISSUE TITLE
[1.7.3.3] HTTP ERROR 500 when I access to catalog or module menu items without debug mode

### ISSUE THREAD

**Issue by pollat** [PrestaShop/PrestaShop#23501] opened 2021-03-03 16:05 UTC
I just migrate my website on the new hosting and all frontoffice is ok, but on the backoffice if I try to access on some menu items, I get HTTP 500 ERROR: if I active debug mode all backoffice menu items work without errors. 
On debug mode I doesn't get any error. 

#### Additional information

* PrestaShop version: 1.7.3.3
* PHP version:7.1

**Comment by hibatallahAouadni** [comment] 2021-03-03 16:10
Hello @pollat 

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-23 08:29
Hello @pollat ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-23 08:29 UTC
Labels: Bug, BO, Performance, No change required
