### ISSUE TITLE
prestashop 1.7.7.5 admin order messages not showing

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#25381] opened 2021-07-19 20:59 UTC
prestashop 1.7.7.5 admin order messages not showing when selected
![prestashop-message-](https://user-images.githubusercontent.com/22105014/126226503-659c8559-6957-4de2-b3ac-1741bff09316.png)

**Comment by florine2623** [comment] 2021-07-20 08:02
Hello @gray-b ,

I can't reproduce your issue in PS 1.7.7.5 :
<img width="392" alt="Screenshot 2021-07-20 at 10 01 10" src="https://user-images.githubusercontent.com/16019289/126284228-fc939df5-c3a1-4566-a0bd-f2c6c23f14fa.png">
<img width="577" alt="Screenshot 2021-07-20 at 10 01 17" src="https://user-images.githubusercontent.com/16019289/126284233-4c1710c3-ce45-4d0c-98a2-b28879ac6bd0.png">

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2021-07-20 08:02 UTC
Labels: Can't reproduce
