### ISSUE TITLE
Product search issue with capital letters

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#24293] opened 2021-05-01 09:48 UTC
#### Describe the bug

When I search for a product in the product list in admin, I find my products if I put a capital letter to the search work, like it is in the product name, but I don't if I put a small letter.

I's the same problem when I search for the product with the search field at the top of the admin.

#### Expected behavior

We should find the products whatever the way the work is written.

#### Steps to Reproduce

1. Go to Admin > Catalog > Products.
2. Search for a product with a word in small letter and where it is written in the product name with a capital letter.
3. See error: the product is not found with a small letter but found with a capital letter.

**Screenshots**

See screenshots

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

![Screen Shot 2021-05-01 at 10 40 11](https://user-images.githubusercontent.com/71735/116778595-b1bad980-aa6a-11eb-88b0-706632828889.png)
![Screen Shot 2021-05-01 at 10 39 58](https://user-images.githubusercontent.com/71735/116778596-b2537000-aa6a-11eb-868d-0e3c77dd6990.png)

![Screen Shot 2021-05-01 at 10 41 47](https://user-images.githubusercontent.com/71735/116778594-aff11600-aa6a-11eb-8f22-a9ffc5862fd0.png)
![Screen Shot 2021-05-01 at 10 48 50](https://user-images.githubusercontent.com/71735/116778620-eaf34980-aa6a-11eb-849d-215b7dc3b246.png)

**Comment by hibatallahAouadni** [comment] 2021-05-03 12:46
Hello @ced--ced 

I didn't manage to reproduce your issue with PS1.7.6.7 and PS1.7.7.3, check my screen record below:

https://www.awesomescreenshot.com/video/3603475?key=5a37282e231c8ecb7aa49762fd4f23f7

Please check and feedback.
Thanks!

**Comment by roncarino** [comment] 2021-05-06 11:05
Hi @ced--ced,

I can't reproduce either with Prestashop 1.7.7.2

Regards,
Loris

**Comment by hibatallahAouadni** [comment] 2021-05-10 10:16
Hello @ced--ced 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.
We will close this issue.

PS: @roncarino thanks for confirming :rocket: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-10 10:16 UTC
Labels: Bug, BO, Can't reproduce, Search, 1.7.7.2
