### ISSUE TITLE
Changing order status from payment accepted to cancelled leads to product out of stock

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#13400] opened 2019-04-15 03:54 UTC
1. Make a purchase via bank transfer or bank wire.
2. Change order status to payment accepted.
3. Change order status to cancelled.

You will receive an email stating that "unknown" product is out of stock.

**Additional information**
PrestaShop version: 1.7.5.1

**Screenshot**
![Untitled](https://user-images.githubusercontent.com/26452178/56106672-6b61b300-5f53-11e9-8358-2f3250cc552a.png)

**Comment by khouloudbelguith** [comment] 2019-04-15 09:51
Hi @nrcjea001,

Your ticket is a duplicate of #9641
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-15 09:52
Duplicate of #9641

**Closed as completed by khouloudbelguith** 2019-04-15 09:51 UTC
Labels: Duplicate
