### ISSUE TITLE
Emails sent in reverse order

### ISSUE THREAD

**Issue by ddevigne** [PrestaShop/PrestaShop#17332] opened 2020-01-23 16:18 UTC
**Describe the bug**
In my module, in `hookActionOrderHistoryAddAfter()`, when the current status is `payment accepted`, I need to change it to a custom status (`license generated`) by calling `OrderHistory::addWithemail()`.
When I do so, the status history is correct (in right order) but the emails associated to each of these statuses are sent in reverse order.

This is due to a core issue:
`OrderHistory::addWithemail()` calls `$this->add()` and then calls `$this->sendEmail()`.
But `OrderHistory::add()` calls the hook again before sending the email.

This leads to this trace:
```
OrderHistory::addWithemail PAYMENT_ACCEPTED
    OrderHistory::add PAYMENT_ACCEPTED
        MyModule::hookActionOrderHistoryAddAfter PAYMENT_ACCEPTED
            OrderHistory::addWithemail LICENSE_GENERATED
                OrderHistory::add LICENSE_GENERATED
                    MyModule::hookActionOrderHistoryAddAfter LICENSE_GENERATED
                        (do nothing)
                OrderHistory::sendEmail LICENSE_GENERATED
    OrderHistory::sendEmail PAYMENT_ACCEPTED
```

**Solution**
In `OrderHistory::addWithemail()`, `hookActionOrderHistoryAddAfter()` should not be called between `add()` and `sendEmail()`.

`OrderHistory::addWithemail()` should call `$this->add()` with an additionnal parameter preventing it to call `hookActionOrderHistoryAddAfter()`, then call `$this->sendEmail()` and finally call `hookActionOrderHistoryAddAfter()`.

**Additional information**
PrestaShop version: 1.7.6.0

**Comment by khouloudbelguith** [comment] 2020-01-23 16:20
Hi @ddevigne,

Could you please provide me your custom module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by ddevigne** [comment] 2020-01-24 13:47
Hi @khouloudbelguith

Thanks for your reply.

I made a small module showing the bug.

[custom_status.zip](https://github.com/PrestaShop/PrestaShop/files/4108673/custom_status.zip)

To reproduce the bug :
- install the module
- buy one article
- see `/log/custom_status.log` under project root dir

In the admin, the statuses are OK :

<img width="582" alt="Capture d’écran 2020-01-24 à 14 43 21" src="https://user-images.githubusercontent.com/15214819/73073558-e3ccab80-3eb7-11ea-9eae-b18ccfac441b.png">

The emails are sent in reverse order :

<img width="1069" alt="Capture d’écran 2020-01-24 à 14 44 04" src="https://user-images.githubusercontent.com/15214819/73073626-fe9f2000-3eb7-11ea-9ad0-762923cd4b23.png">

You can see the calls to `sendEmail()` in reverse order in the log :

<img width="643" alt="Capture d’écran 2020-01-24 à 14 44 52" src="https://user-images.githubusercontent.com/15214819/73073658-15de0d80-3eb8-11ea-950e-f70fc1eccc40.png">

Note : In the module, one would normally call `$orderHistory->addWithemail()`. I replaced this call by a call to $orderHistory->add() and $orderHistory->sendEmail() for logging purpose.
Of course the bug also exists without this modification.

I hope my explanations are clear...

**Comment by khouloudbelguith** [comment] 2020-01-24 14:36
@ddevigne, this module cannot be installed
https://drive.google.com/file/d/1FlhiC9CWrdgjCfU95Mnotepb9_JaEYhq/view
The page is blocked in the install step.

Thanks to check & feedback.

**Comment by ddevigne** [comment] 2020-01-27 16:09
Hi @khouloudbelguith,

There is a way to reproduce the bug without my module.

Steps to reproduce :
- (in BO) install the integrated module "ps_wirepayment"
- (in FO) place an order
- (in FO)choose "Pay by bank wire"
- (in FO)validate your order
- (in BO) , the statuses are in right order (`Order confirmation` and then `Awaiting bank wire payment`)
- in your mailbox, the statuses are in reverse order (`Awaiting bank wire payment` and then `Order confirmation`)

**Comment by khouloudbelguith** [comment] 2020-01-27 16:15
Hi @ddevigne,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #17346
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-27 16:15
Duplicate of #17346

**Closed as completed by khouloudbelguith** 2020-01-27 16:15 UTC
Labels: Bug, Duplicate, Order, Email, 1.7.6.0
