### ISSUE TITLE
Countries & Carriers Restrictions - Payment preferences 

### ISSUE THREAD

**Issue by mdacweb** [PrestaShop/PrestaShop#16743] opened 2019-12-09 10:55 UTC
**Describe the bug**
Countries and carriers restrictions in payment preferences don't work. Prestashop doesn't save changes. No error messages are displayed.

**To Reproduce**
1. Go to "Payment" and "preferences"
2. Check countries and/or carrier restrictions
3. Save settings
4. Setting are not applied

Since all payments are disable for every carriers, there aren't payments methods on checkout.

**Screenshots**
![screen-sc-1](https://user-images.githubusercontent.com/58687689/70430029-2ce8ad80-1a7a-11ea-82bc-f872fce3d056.png)
![screen-sc-2](https://user-images.githubusercontent.com/58687689/70430041-3245f800-1a7a-11ea-9c71-4e47f087d81c.png)
![screen-sc-3](https://user-images.githubusercontent.com/58687689/70430125-63262d00-1a7a-11ea-88fc-c8a23f3d659b.png)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.1
Bank transfer + COD With fee + PayPal + Satispay + Login and Pay With Amazon + XPay

**Comment by khouloudbelguith** [comment] 2019-12-09 11:07
Hi @mdacweb,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/16a6CpCcC0YxvYmlPeQsPSacjLEbndYI1/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-08 07:48
Hi @mdacweb,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-08 07:48 UTC
Labels: Bug, BO, Payment preferences, No change required, 1.7.5.1

**Comment by chamber1** [comment] 2020-04-13 10:41
try to change max_input_vars in your php.ini to max_input_vars =10000
it was helpful for me
