### ISSUE TITLE
Payment fees

### ISSUE THREAD

**Issue by margud** [PrestaShop/PrestaShop#18473] opened 2020-04-06 05:41 UTC
#### Is your feature request related to a problem?

More and more merchants want to add payment fees for their payment methods but now it's really hard to do it even with modules. We need to do all kinds of workarounds for it to work.

#### Describe the solution you'd like

We want PrestaShop to add an option for the payment method to have fees just like carriers do.
The fee should be displayed next to the payment method and when selected it should be added to the total price.

#### Additional context

![image](https://user-images.githubusercontent.com/51944825/78526304-4f00fb00-77e2-11ea-8bac-8c1441a51650.png)

**Comment by khouloudbelguith** [comment] 2020-04-06 08:31
Hi @margud,

Your ticket is a duplicate of #13170
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-06 08:31
Duplicate of #13170

**Closed as completed by khouloudbelguith** 2020-04-06 08:31 UTC
Labels: Duplicate
