### ISSUE TITLE
Mail Alert: Product name is missing if combination

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#19839] opened 2020-06-18 09:51 UTC
#### Describe the bug

When getting mail alert "Product out of stock", the product name is missing for products with combination. It is working fine for product without combination

#### Expected behavior

The product name and combination name should appear in the email

#### Steps to Reproduce

1. Edit a product with combination in the backoffice
2. Change the quantity to have less than the alert level
3. See the email Product out of stock

**Screenshots**
![Capture d’écran 2020-06-18 à 11 46 44](https://user-images.githubusercontent.com/1193727/85006037-e6c38380-b159-11ea-8208-74b3524bf2c5.jpg)

#### Additional information

* PrestaShop version: 1.7.6.5
* Mail alert version: v2.2.0 (but the issue was in previous version as well)
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-06-18 11:21
Hi @arirangz ,
I can't reproduce your issue in PS 1.7.6.5 with ps_emailalerts v2.2.0.
Here's a screenshot :
![Capture d’écran 2020-06-18 à 13 17 52](https://user-images.githubusercontent.com/16019289/85014302-49228100-b166-11ea-857d-bf2319a51690.png)
Sorry it's in French, but what's underlined is `the name of the product : the name of the combination`.

In the product page in the BO, all the info is present ?
Thanks!

**Comment by arirangz** [comment] 2020-06-18 13:29
No problem I am french too :)

Yes the product has a name and combinations:
![Capture d’écran 2020-06-18 à 15 02 19](https://user-images.githubusercontent.com/1193727/85023279-cbb23d00-b174-11ea-9a4e-4f23ee213373.jpg)

I checked the template as I have an override in my theme but the code seems to use the good:
{product} is almost out of stock.

**Comment by kpodemski** [comment] 2020-06-18 13:40
@arirangz are you using some import tool for your store? importing from xml, csv or something?

**Comment by arirangz** [comment] 2020-06-18 13:43
no we don't have any importing modules and we never imported products from csv

**Comment by arirangz** [comment] 2020-06-18 13:54
I don't think this is related but I can see the productcoverage.txt and productoutofstock.txt and not matching with the html. Is this already reported?

**Comment by florine2623** [comment] 2020-06-18 16:05
In International > Translation > Email Translations > ps_emailalerts, do you see the variable {product} ?
![Capture d’écran 2020-06-18 à 18 03 59](https://user-images.githubusercontent.com/16019289/85044619-2ad07b80-b18e-11ea-87ab-eff96e9b2bce.png)

Can you send me `productoutofstock.txt` and `productoutofstock.html` in .zip format ? I will take a look.

**Comment by arirangz** [comment] 2020-06-18 16:14
Yes I have it under my child theme:
![Capture d’écran 2020-06-18 à 18 13 22](https://user-images.githubusercontent.com/1193727/85045623-7e8f9480-b18f-11ea-8ad9-49851dfda530.jpg)

**Comment by florine2623** [comment] 2020-06-19 08:43
Could you regenerate your emails here : Improve > Design > Email Theme > Generate Emails ?
Thanks!

**Comment by florine2623** [comment] 2020-07-09 09:17
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-07-09 09:17 UTC
Labels: No change required, 1.7.6.5, ps_emailalerts

**Comment by arirangz** [comment] 2020-07-10 10:39
Hello,

I could fixed the issue.

It was related to different encoding between attribute table and product table causing a sql error :
Illegal mix of collations (utf8_bin,NONE) and (utf8_general_ci,IMPLICIT) for operation 'ifnull'

The issue has been already posted but I don't think it has been solved:
https://github.com/PrestaShop/PrestaShop/issues/9545

Changing the encoding fixed the issue.

Thanks
