### ISSUE TITLE
slow backoffice TypeaheadProductCollectionType.php

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#15451] opened 2019-09-06 15:33 UTC
we experienced slow backoffice when editing product with options.

In debug mode:

in src/PrestaShopBundle/Form/Admin/Type/TypeaheadProductCollectionType.php (line 96)

                        default:
                            $product = $this->productAdapter->getProduct($id);
                            $collection[] = [
                                'id' => $id,
                                'name' => reset($product->name) . ' (ref:' . $product->reference . ')',
                                'image' => $product->image,
                            ];
                            break;
                    }

CRITICAL 16:58:45 	php 	Uncaught Warning: reset() expects parameter 1 to be array, null given
CRITICAL 16:58:45 	request 	Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: reset() expects parameter 1 to be array, null given" at /home/debxxx/domains/xxxx.nl/public_html/src/PrestaShopBundle/Form/Admin/Type/TypeaheadProductCollectionType.php line 96

**Comment by khouloudbelguith** [comment] 2019-09-06 15:39
Hi @Peter4661,

Is it is the same reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9809?
Do you try to edit a product with a large number of combinations?

Thanks!

**Comment by Peter4661** [comment] 2019-09-06 15:48
The item has 48 combinations.

Prestashop 1.7.6
Server softwareversie: Apache
PHP-versie: 7.2.21
Geheugenlimiet: 1024M
Maximale uitvoeringstijd: 300
Maximale bestandsgrootte voor uploads: 128M

**Comment by khouloudbelguith** [comment] 2019-09-06 15:57
@Peter4661, this issue will be fixed in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9809
You can follow this ticket also for more details about all issues that will be fixed related to a product with combinations: https://github.com/PrestaShop/PrestaShop/issues/14773
It should be fixed in the PS1.7.7.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-06 15:57
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2019-09-06 15:57 UTC
Labels: BO, Duplicate, Combinations

**Comment by ang3lx** [comment] 2024-07-12 10:34
I've the same error... but product has only 1 combination (PS 8.1.6)

**Comment by ang3lx** [comment] 2024-07-12 14:57
Ok, i've debugged and... 
I discovered that this product was a 301 redirect product pointing to another product.
The problem is that the product he was aiming for no longer existed
And not only that, the backoffice didn't open the affected product, but tried to open the product id with 301 (which shouldn't happen in the backoffice)

this should happen in the frontend, but not in the backend
