### ISSUE TITLE
Number display allows all characters (Brand list module)

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28453] opened 2022-05-10 14:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The module "Brand list" has an input for "Number of elements to display", it should allow only numbers, but any character can be saved without any errors.

<img width="1218" alt="Screenshot 2022-05-10 at 16 47 55" src="https://user-images.githubusercontent.com/16019289/167656937-e07b2bf9-524b-4f51-bd80-adcd01141f25.png">

### Expected behavior

Inputting any other characters, not numbers should result in an error when saving.

### Steps to reproduce

1. Go to Module catalog
2. Install module "Brand list"
3. Go to the configuration of the module
4. In the field "Number of elements to display" input random characters
5. Press "Save"

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

Brand list v1.0.3

**Comment by florine2623** [comment] 2022-05-10 14:49
Hello @Saimis777 ,

I reproduce the issue with PrestaShop version 1.7.8.x and develop branch using brand list module v1.0.3, I'll add this to the backlog so it can be fixed.

Although, this is a trivial bug because once you leave the page and try to configure the module again, the letters are not shown :

https://user-images.githubusercontent.com/16019289/167658304-c6283ba6-ead0-4851-b0c3-a01629c8727d.mov



Thank you

**Comment by Progi1984** [comment] 2022-06-22 12:01
Fixed by PrestaShop/ps_brandlist#15

**Closed as completed by Progi1984** 2022-06-22 12:01 UTC
Labels: Bug, Trivial, BO, Brand list, Good first issue, 1.7.7.8, Verified, Module
