### ISSUE TITLE
New combination

### ISSUE THREAD

**Issue by stamatisbreezer** [PrestaShop/PrestaShop#22533] opened 2020-12-21 23:19 UTC
Adding a new color-size combination in a product. From the product page, when I select color-size and click Generate. The isn't any checkbox with the available product pictures. So the new color-size combination has a random picture and not the picture I have uploaded and there isn't any way to select it.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2020-12-22 10:26
Hello @stamatisbreezer 

Please next time **follow the template to submit a complete bug report**.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Now, follow my steps to change the picture for every combinations that you create:

1. BO>SELL>Catalog>Products>edit product
2. In the Basic settings upload all photos of combinations
3. Save
4. Go to Combinations tab
5. Click on the pencil icon to edit a combination
6. Scroll down to Images section
7. click the desired photo for this combination
8. Save
9. Scroll up and click on Back to product button
10. Then redo the steps from 5 to 9 till you set all the combinations photos

See the attached screen record below to understand better :wink: 

https://drive.google.com/file/d/1ZuOnWdYOucGSZIGYLPOwwTAP1vX8M-kd/view

So, I close this issue cause it's not a bug. 
Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-22 10:26 UTC
Labels: No change required

**Comment by stamatisbreezer** [comment] 2020-12-24 08:21
Yes, I do know how to edit the product. The problem is that prestashop don't create the product correctly. Is a bug to create 20 combinations false and then need to go to each blue-red-yellow-black combinations and change picture. Finaly editing each 20 one by one. This isn't correct work flow. Making a product false and then start editing?

**Comment by hibatallahAouadni** [comment] 2020-12-25 09:03
Hello @stamatisbreezer 

What you suggest is an improvement and it's a good idea :wink: 
Could you please open a new issue **following the template to submit a complete feature report**.
And we will be glad to study your suggestion and approve it.

Thanks!
