### ISSUE TITLE
Multistore mode issues

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#12255] opened 2019-01-22 08:47 UTC
I have created 5 different shops . Now if i trying to disable all website by selecting the "All shops " the website still enable.

For disabling all shops i need to select each shops and disable the shop(put the website in maintance mode).

Please let me know what exactly issue is this

**Comment by khouloudbelguith** [comment] 2019-01-22 09:06
Hi @pks891618,

We manage to reproduce the issue.
Your ticket is a duplicate of #9548
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-22 09:06
Duplicate of #9548

**Closed as completed by khouloudbelguith** 2019-01-22 09:06 UTC
Labels: Duplicate

**Comment by pks891618** [comment] 2019-01-22 09:13
Sorry but i cant the fixes for this issue on the url https://github.com/PrestaShop/PrestaShop/issues/9548

**Comment by khouloudbelguith** [comment] 2019-01-22 09:26
@pks891618, sorry it is not fixed yet.
Thanks!

**Comment by pks891618** [comment] 2019-01-22 09:28
@khouloudbelguith  so this issue is not fixed in 1.7.4.2 , we can use the latest version for prestashop 1.7.5

**Comment by khouloudbelguith** [comment] 2019-01-22 09:39
@pks891618, sorry it is not fixed from 1.7.4.0 to PS1.7.5.0
