### ISSUE TITLE
Error on ps_emailalerts with php 7.3.10-1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#16056] opened 2019-10-21 17:39 UTC
Hi
try to go in the configuration page of ps_emailalerts module and push on the save button. With php 7.3 I get this error
try to set the line like this one to solve the problem:
`} elseif (!empty($email) && $email) {`

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/67228752-39696600-f43a-11e9-8c7e-972855fcf9cb.png)
![3](https://user-images.githubusercontent.com/653230/67228753-39696600-f43a-11e9-93b4-fbfd94a7d762.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3.10-1
Module version: 2.1.1

**Comment by khouloudbelguith** [comment] 2019-10-22 07:51
Hi @maofree,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP.
Also, Here's the PR: https://github.com/PrestaShop/ps_emailalerts/pull/18 to fix the issue.
Your ticket is a duplicate of https://github.com/PrestaShop/ps_emailalerts/issues/16
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-22 07:52
Duplicate of https://github.com/PrestaShop/ps_emailalerts/issues/16

**Closed as completed by khouloudbelguith** 2019-10-22 07:51 UTC
Labels: Duplicate
