### ISSUE TITLE
[PrestaShopException] vat number

### ISSUE THREAD

**Issue by simonedidio** [PrestaShop/PrestaShop#12937] opened 2019-03-15 11:38 UTC
During order (in address tab) users that use old browser view error 500 on monitor.
`[PrestaShopException]

La proprietà Address->vat_number è vuota.
at line 944 in file classes/ObjectModel.php

939. }
940. 
941. $message = $this->validateField($field, $this->$field);
942. if ($message !== true) {
943. if ($die) {
944. throw new PrestaShopException($message);
945. }
946. return $error_return ? $message : false;
947. }
948. }
949. 

ObjectModelCore->validateFields - [line 272 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 518 - classes/ObjectModel.php]
ObjectModelCore->add - [line 174 - classes/Address.php] - [2 Arguments]
AddressCore->add - [line 476 - classes/ObjectModel.php] - [2 Arguments]
ObjectModelCore->save - [line 76 - classes/form/CustomerAddressPersister.php]
CustomerAddressPersisterCore->save - [line 145 - classes/form/CustomerAddressForm.php] - [2 Arguments]
CustomerAddressFormCore->submit - [line 111 - classes/checkout/CheckoutAddressesStep.php]
CheckoutAddressesStepCore->handleRequest - [line 57 - classes/checkout/CheckoutProcess.php] - [1 Arguments]
CheckoutProcessCore->handleRequest - [line 202 - controllers/front/OrderController.php] - [1 Arguments]
OrderControllerCore->initContent - [line 205 - classes/controller/Controller.php]
ControllerCore->run - [line 369 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]`

**Additionnal information**
PrestaShop version: 1.7.1.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-03-15 12:36
Hi @simonedidio,

Here is the PR: https://github.com/PrestaShop/PrestaShop/pull/8435 to solve the problem.
It is fixed in the previous version 1.7.3.0.
You can follow this ticket: [BOOM-2989](http://forge.prestashop.com/browse/BOOM-2989).
Your ticket is a duplicate of #8435
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-15 12:37
Duplicate of #8435

**Closed as completed by khouloudbelguith** 2019-03-15 12:36 UTC
Labels: Duplicate
