### ISSUE TITLE
PHP Notice Product Class

### ISSUE THREAD

**Issue by Veiss** [PrestaShop/PrestaShop#19038] opened 2020-05-07 15:56 UTC
#### PHP Notice on Product class

Hi! I check in new PS versions since 1.7.5 that in line 4889 there is a sentence that allways report me a PHP Notice:
NOTICE: PHP message: PHP Notice:  Undefined index: unit_price_ratio in /shared/httpd/novaut/classes/Product.php on line 4889

$row['unit_price'] = ($row['unit_price_ratio'] != 0 ? $row['price'] / $row['unit_price_ratio'] : 0);

#### Expected behavior
Is not an error of parenthesis clousure ?
The correct sentence will be 
$row['unit_price'] = (isset($row['unit_price_ratio']) && $row['unit_price_ratio' ] != 0) ? $row['price'] / $row['unit_price_ratio'] : 0;

Sorry if not an error ;)

Thanks a lot

#### Additional information

* PrestaShop version: 1.7.5 - 1.7.6
* PHP version: 7.2

**Comment by atomiix** [comment] 2020-05-11 09:03
Hi @Veiss 

Thanks for your feedbacks, could give us more information on how to reproduce you issue and some screenshots of you error? Thanks

**Comment by florine2623** [comment] 2020-06-05 13:24
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-05 13:24 UTC
Labels: Fixed

**Comment by matks** [comment] 2020-06-15 08:17
@Veiss fixed in https://github.com/PrestaShop/PrestaShop/pull/19601 😉

**Comment by LuigiMdg** [comment] 2021-06-18 10:56
I also have the same problem at line 5130!

Version 1.7.7.2

**Comment by lelovitis** [comment] 2022-02-06 23:41
Prestashop version:  1.7.6.5 
PHP version:  7.2.34. 

In DEBUG mode we are experiencing the following: 

-----------[ starts here ]-------------------------------------
**(1/1) ContextErrorExceptionNotice: Undefined index: unit_price_ratio**
--
**in Product.php line 4955**
**at ProductCore::getProductProperties**(1, array('id_product' => '395', 'id_product_attribute' => 0, 'link_rewrite' => 'darphin-aromatic-cleansing-balm-with-rosewood', 'name' => 'DARPHIN Aromatic Cleansing Balm With Rosewood - Αρωματικό Balm Καθαρισμού με Ροδόξυλο 40ml', 'description_short' => '<p><strong>Aromatic cleansing balm with rosewood</strong></p><p><b>Αρωματικό Balm Καθαρισμού με Ροδόξυλο 40ml</b></p><p>ΒΑΘΥΣ ΚΑΘΑΡΙΣΜΟΣ ΓΙΑ ΜΙΑ ΕΠΙΔΕΡΜΙΔΑ ΠΟΥ ΑΚΤΙΝΟΒΟΛΕΙ ΑΠΟ ΥΓΕΙΑ</p><p>Περιεχόμενο: 40ml</p><p></p><p></p><p>Αυτό το balm που μοιάζει με μέλι καθαρίζει απαλά την επιδερμίδα. Με έκχυση από αιθέρια έλαια, συμβάλει στην εύκολη διάλυση της λιπαρότητας, στη ρύθμιση της και στην καθαριότητα των πόρων, χωρίς να ερεθίζει. Όταν αναμιγνύεται με νερό, μετατρέπεται σε υδαρό γαλάκτωμα που απομακρύνει τις ακαθαρσίες και το make up αφήνοντας την επιδερμίδα ελαστική, απαλή, ενυδατωμένη και λαμπερή.</p><p></p>', 'id_category_default' => '145', 'id_image' => '395-758', 'legend' => '', 'sales' => '2', 'ean13' => '882381054441', 'upc' => '', 'category' => 'darphin-professional-care', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => 2, 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null, 'allow_oosp' => 0, 'category_name' => 'ΕΠΑΓΓΕΛΜΑΤΙΚΗ ΠΕΡΙΠΟΙΗΣΗ', 'link' => 'https://pharmart.gr/kz/el/darphin-professional-care/395-darphin-aromatic-cleansing-balm-with-rosewood-882381054441.html', 'attribute_price' => 0, 'price_tax_exc' => 21.959678, 'price' => 27.23, 'price_without_reduction' => 38.9, 'price_without_reduction_without_tax' => 31.370968, 'reduction' => 11.67, 'reduction_without_tax' => 9.41129, 'specific_prices' => array('id_specific_price' => '360', 'id_specific_price_rule' => '0', 'id_cart' => '0', 'id_product' => '395', 'id_shop' => '1', 'id_shop_group' => '0', 'id_currency' => '0', 'id_country' => '0', 'id_group' => '0', 'id_customer' => '0', 'id_product_attribute' => '0', 'price' => '-1.000000', 'from_quantity' => '1', 'reduction' => '0.300000', 'reduction_tax' => '1', 'reduction_type' => 'percentage', 'from' => '0000-00-00 00:00:00', 'to' => '0000-00-00 00:00:00', 'score' => '16'), 'quantity_all_versions' => 2, 'features' => array(array('name' => 'ΔΡΑΣΗ', 'value' => 'ΛΑΜΨΗ - ΑΝΤΙΓΗΡΑΝΣΗ', 'id_feature' => '3', 'position' => '2'), array('name' => 'ΔΡΑΣΗ', 'value' => 'ΚΑΘΑΡΙΣΜΟΣ', 'id_feature' => '3', 'position' => '2'), array('name' => 'ΔΡΑΣΗ', 'value' => 'ΑΝΑΖΩΟΓΟΝΗΣΗ', 'id_feature' => '3', 'position' => '2'), array('name' => 'ΧΡΗΣΗ', 'value' => 'ΓΥΝΑΙΚΕΣ', 'id_feature' => '4', 'position' => '3'), array('name' => 'ΧΡΗΣΗ', 'value' => 'ΕΝΗΛΙΚΕΣ', 'id_feature' => '4', 'position' => '3'), array('name' => 'ΕΦΑΡΜΟΓΗ', 'value' => 'ΠΡΟΣΩΠΟ', 'id_feature' => '5', 'position' => '4'), array('name' => 'ΤΥΠΟΣ', 'value' => 'BALM', 'id_feature' => '6', 'position' => '5'), array('name' => 'ΔΕΡΜΑ', 'value' => 'ΚΑΘΕ ΤΥΠΟΥ', 'id_feature' => '7', 'position' => '6'), array('name' => 'BRANDS', 'value' => 'DARPHIN', 'id_feature' => '8', 'position' => '7')), 'attachments' => array(), 'virtual' => 1, 'pack' => false, 'packItems' => array(), 'nopackprice' => 0, 'customization_required' => false, 'rate' => 24.0, 'tax_name' => 'ΦΠΑ GR 24%', 'ecotax_rate' => 0.0)) 

**in Product.php line 4990**
**at ProductCore::getProductsProperties**(1, array(array('id_product' => '395', 'id_product_attribute' => '0', 'link_rewrite' => 'darphin-aromatic-cleansing-balm-with-rosewood', 'name' => 'DARPHIN Aromatic Cleansing Balm With Rosewood - Αρωματικό Balm Καθαρισμού με Ροδόξυλο 40ml', 'description_short' => '<p><strong>Aromatic cleansing balm with rosewood</strong></p><p><b>Αρωματικό Balm Καθαρισμού με Ροδόξυλο 40ml</b></p><p>ΒΑΘΥΣ ΚΑΘΑΡΙΣΜΟΣ ΓΙΑ ΜΙΑ ΕΠΙΔΕΡΜΙΔΑ ΠΟΥ ΑΚΤΙΝΟΒΟΛΕΙ ΑΠΟ ΥΓΕΙΑ</p><p>Περιεχόμενο: 40ml</p><p></p><p></p><p>Αυτό το balm που μοιάζει με μέλι καθαρίζει απαλά την επιδερμίδα. Με έκχυση από αιθέρια έλαια, συμβάλει στην εύκολη διάλυση της λιπαρότητας, στη ρύθμιση της και στην καθαριότητα των πόρων, χωρίς να ερεθίζει. Όταν αναμιγνύεται με νερό, μετατρέπεται σε υδαρό γαλάκτωμα που απομακρύνει τις ακαθαρσίες και το make up αφήνοντας την επιδερμίδα ελαστική, απαλή, ενυδατωμένη και λαμπερή.</p><p></p>', 'id_category_default' => '145', 'id_image' => '758', 'legend' => '', 'sales' => '2', 'ean13' => '882381054441', 'upc' => '', 'category' => 'darphin-professional-care', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '2', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '435', 'id_product_attribute' => '0', 'link_rewrite' => 'frezyderm-sensitive-red-skin-facial-cream', 'name' => 'FREZYDERM SENSITIVE RED SKIN FACIAL CREAM Κρέμα για Ευαίσθητο Δέρμα - Ροδόχρου Νόσο 50ml', 'description_short' => '<p><strong>SENSITIVE RED SKIN FACIAL CREAM </strong></p><p><strong>Κρέμα για Ευαίσθητο Δέρμα - Ροδόχρου Νόσο</strong></p><p>Περιεχόμενο: 50ml</p><p>75% μείωση αλλεργικής προδιάθεσης. Υποαλλαεργικό προϊόν.</p><p>Χωρίς parabens και άρωμα</p><p></p>', 'id_category_default' => '156', 'id_image' => '841', 'legend' => '', 'sales' => '1', 'ean13' => '5202888271724', 'upc' => '', 'category' => 'frezyderm-face-sensitive-skin', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '0', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '436', 'id_product_attribute' => '0', 'link_rewrite' => 'frezyderm-sensitive-red-skin-tinted-SPF30-cream', 'name' => 'FREZYDERM SENSITIVE RED SKIN TINTED SPF 30 CREAM Έγχρωμη Κρέμα για Ευαίσθητο Δέρμα 30ml', 'description_short' => '<p><strong>SENSITIVE RED SKIN TINTED SPF 30 CREAM </strong></p><p><strong>Έγχρωμη Κρέμα για Ευαίσθητο Δέρμα</strong></p><p><strong>CC Cream</strong></p><p>Περιεχόμενο:30ml<br /><br />Δείκτης Προστασίας: SPF 30</p><p>74% μείωση μικροκυκλοφορίας. Υποαλλαεργικό προϊόν.</p><p>Χωρίς parabens και άρωμα </p><p></p>', 'id_category_default' => '156', 'id_image' => '843', 'legend' => '', 'sales' => '1', 'ean13' => '5202888271649', 'upc' => '', 'category' => 'frezyderm-face-sensitive-skin', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '1', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '695', 'id_product_attribute' => '0', 'link_rewrite' => 'avogel-atrosan', 'name' => 'A.VOGEL Atrosan Για την Καλή Λειτουργία των Αρθρώσεων και του Μυοσκελετικού Συστήματος 60 Ταμπλέτες', 'description_short' => '<p><strong>A.VOGEL Atrosan</strong><br /><strong></strong></p><p><strong>Ταμπλέτες από ρίζα αρπαγόφυτου</strong><br /><strong>Για την καλή λειτουργία των αρθρώσεων και του μυοσκελετικού συστήματος</strong><br /><br /></p><p>Περιεχόμενο: 60 Ταμπλέτες</p>', 'id_category_default' => '275', 'id_image' => '1210', 'legend' => '', 'sales' => '1', 'ean13' => '7610313394029', 'upc' => '', 'category' => 'avogel-phytotherapy', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '4', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '919', 'id_product_attribute' => '0', 'link_rewrite' => 'lamberts-aminoacids-bcaa', 'name' => 'LAMBERTS BCAA – Branch Chain Amino Acids 180 Κάψουλες', 'description_short' => '<p><strong>BCAA – Branch Chain Amino Acids</strong><br /><i>Ελεύθερης Μορφής</i><br /><br /><strong>Gluten Free, Dairy Free</strong><br /><br /></p><p>Tο προϊόν αυτό παρέχει τρία απαραίτητα αμινοξέα, την λευκίνη, την ισολευκίνη και την βαλίνη, συνδυαζόμενα σε ποσοστό 2:1:1 που εκτιμάται ότι αποτελεί την βέλτιστη αναλογία για αυτά τα τρία αμινοξέα. Όπως και με τα υπόλοιπα αμινοξέα της Lamberts, έτσι και τα συγκεκριμένα, είναι στην ‘ελεύθερη μορφή’ τους που σημαίνει ότι είναι έτοιμα να απορροφηθούν και να χρησιμοποιηθούν από τον οργανισμό.<strong></strong></p><p></p><p>Περιεχόμενο: 180 Κάψουλες</p>', 'id_category_default' => '246', 'id_image' => '1434', 'legend' => '', 'sales' => '1', 'ean13' => '5055148411015', 'upc' => '', 'category' => 'lamberts-aminoacids', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '20', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '1417', 'id_product_attribute' => '0', 'link_rewrite' => 'avene-cold-cream-40ml', 'name' => 'Avene Cold Cream Κρέμα για Ευαίσθητο & Ξηρό Δέρμα 40ml', 'description_short' => '<p><strong>Cold Cream Κρέμα για Ευαίσθητο &amp; Ξηρό Δέρμα</strong><br /><strong></strong></p><p>Περιεχόμενο: 40ml<br /><br />Η Avène Cold Cream Κρέμα θρέφει, ενυδατώνει και προστατεύει το δέρμα σας από τις εξωτερικές επιθέσεις. Mε την πλούσια υφή της προσφέρει εξαιρετική άνεση στο δέρμα σας αμέσως. Επίσης περιέχει Ιαματικό Νερό της Avène, που είναι καταπραϋντικό και αντι-ερεθιστικό, προσφέροντας στο δέρμα σας άμεσο αίσθημα άνεσης.<br /><br /></p>', 'id_category_default' => '329', 'id_image' => '2026', 'legend' => '', 'sales' => '1', 'ean13' => '3282779002738', 'upc' => '', 'category' => 'avene-cold-cream', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '2', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '1734', 'id_product_attribute' => '0', 'link_rewrite' => 'freshline-freshbar-body-milks-mojito-lime', 'name' => 'FRESH LINE ΜΟΧΙΤΟ & ΛΑΙΜ Γαλάκτωμα Σώματος 200ml', 'description_short' => '<p><b>FRESH LINE ΜΟΧΙΤΟ &amp; ΛΑΙΜ  Γαλάκτωμα Σώματος 200ml</b><br /><br />Εμπλουτισμένο με έλαιο από αβοκάντο και αμύγδαλο<br /><br /></p><p>Περιεχόμενο: 200ml</p>', 'id_category_default' => '356', 'id_image' => '2359', 'legend' => '', 'sales' => '1', 'ean13' => '5204989121359', 'upc' => '', 'category' => 'freshline-freshbar-body-milk', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '3', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '1737', 'id_product_attribute' => '0', 'link_rewrite' => 'freshline-freshbar-body-milks-strawberry-milk', 'name' => 'FRESH LINE ΦΡΑΟΥΛΑ & ΓΑΛΑ Γαλάκτωμα Σώματος 200ml', 'description_short' => '<p><b>FRESH LINE ΦΡΑΟΥΛΑ &amp; ΓΑΛΑ  Γαλάκτωμα Σώματος 200ml</b><br /><br />Εμπλουτισμένο με έλαιο από αβοκάντο και αμύγδαλο<br /><br /></p><p>Περιεχόμενο: 200ml</p>', 'id_category_default' => '356', 'id_image' => '2362', 'legend' => '', 'sales' => '1', 'ean13' => '5204989121465', 'upc' => '', 'category' => 'freshline-freshbar-body-milk', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '0', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null)))in ProductSale.php line 230

--------[ the error report continues down to DispatcherCore->dispatch() in index.php line 28 ]------------- 

### After disabling product id 395 the problem repeats for product id 435 

--------------------------[ starts here ]--------------------
**(1/1) ContextErrorExceptionNotice: Undefined index: unit_price_ratio**
--
**in Product.php line 4955**
at ProductCore::getProductProperties(1, array('id_product' => '435', 'id_product_attribute' => 0, 'link_rewrite' => 'frezyderm-sensitive-red-skin-facial-cream', 'name' => 'FREZYDERM SENSITIVE RED SKIN FACIAL CREAM Κρέμα για Ευαίσθητο Δέρμα - Ροδόχρου Νόσο 50ml', 'description_short' => '<p><strong>SENSITIVE RED SKIN FACIAL CREAM </strong></p><p><strong>Κρέμα για Ευαίσθητο Δέρμα - Ροδόχρου Νόσο</strong></p><p>Περιεχόμενο: 50ml</p><p>75% μείωση αλλεργικής προδιάθεσης. Υποαλλαεργικό προϊόν.</p><p>Χωρίς parabens και άρωμα</p><p></p>', 'id_category_default' => '156', 'id_image' => '435-841', 'legend' => '', 'sales' => '1', 'ean13' => '5202888271724', 'upc' => '', 'category' => 'frezyderm-face-sensitive-skin', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => 0, 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null, 'allow_oosp' => 0, 'category_name' => 'Ευαίσθητο δέρμα', 'link' => 'https://pharmart.gr/kz/el/frezyderm-face-sensitive-skin/435-frezyderm-sensitive-red-skin-facial-cream-5202888271724.html', 'attribute_price' => 0, 'price_tax_exc' => 14.294, 'price' => 17.72, 'price_without_reduction' => 25.3208, 'price_without_reduction_without_tax' => 20.42, 'reduction' => 7.59624, 'reduction_without_tax' => 6.126, 'specific_prices' => array('id_specific_price' => '567', 'id_specific_price_rule' => '0', 'id_cart' => '0', 'id_product' => '435', 'id_shop' => '1', 'id_shop_group' => '0', 'id_currency' => '0', 'id_country' => '0', 'id_group' => '0', 'id_customer' => '0', 'id_product_attribute' => '0', 'price' => '-1.000000', 'from_quantity' => '1', 'reduction' => '0.300000', 'reduction_tax' => '1', 'reduction_type' => 'percentage', 'from' => '0000-00-00 00:00:00', 'to' => '0000-00-00 00:00:00', 'score' => '16'), 'quantity_all_versions' => 0, 'features' => array(array('name' => 'ΔΡΑΣΗ', 'value' => 'ΑΤΕΛΕΙΕΣ - ΔΙΟΡΘΩΣΗ', 'id_feature' => '3', 'position' => '2'), array('name' => 'ΔΡΑΣΗ', 'value' => 'ΕΥΑΙΣΘΗΣΙΑ - ΞΗΡΟΤΗΤΑ ', 'id_feature' => '3', 'position' => '2'), array('name' => 'ΧΡΗΣΗ', 'value' => 'ΕΝΗΛΙΚΕΣ', 'id_feature' => '4', 'position' => '3'), array('name' => 'ΧΡΗΣΗ', 'value' => 'ΓΥΝΑΙΚΕΣ', 'id_feature' => '4', 'position' => '3'), array('name' => 'ΕΦΑΡΜΟΓΗ', 'value' => 'ΠΡΟΣΩΠΟ', 'id_feature' => '5', 'position' => '4'), array('name' => 'ΤΥΠΟΣ', 'value' => 'ΚΡΕΜΑ', 'id_feature' => '6', 'position' => '5'), array('name' => 'ΔΕΡΜΑ', 'value' => 'ΚΑΘΕ ΤΥΠΟΥ', 'id_feature' => '7', 'position' => '6'), array('name' => 'BRANDS', 'value' => 'FREZYDERM', 'id_feature' => '8', 'position' => '7')), 'attachments' => array(), 'virtual' => 1, 'pack' => false, 'packItems' => array(), 'nopackprice' => 0, 'customization_required' => false, 'rate' => 24.0, 'tax_name' => 'ΦΠΑ GR 24%', 'ecotax_rate' => 0.0)) 

**in Product.php line 4990
at ProductCore::getProductsProperties**(1, array(array('id_product' => '435', 'id_product_attribute' => '0', 'link_rewrite' => 'frezyderm-sensitive-red-skin-facial-cream', 'name' => 'FREZYDERM SENSITIVE RED SKIN FACIAL CREAM Κρέμα για Ευαίσθητο Δέρμα - Ροδόχρου Νόσο 50ml', 'description_short' => '<p><strong>SENSITIVE RED SKIN FACIAL CREAM </strong></p><p><strong>Κρέμα για Ευαίσθητο Δέρμα - Ροδόχρου Νόσο</strong></p><p>Περιεχόμενο: 50ml</p><p>75% μείωση αλλεργικής προδιάθεσης. Υποαλλαεργικό προϊόν.</p><p>Χωρίς parabens και άρωμα</p><p></p>', 'id_category_default' => '156', 'id_image' => '841', 'legend' => '', 'sales' => '1', 'ean13' => '5202888271724', 'upc' => '', 'category' => 'frezyderm-face-sensitive-skin', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '0', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '436', 'id_product_attribute' => '0', 'link_rewrite' => 'frezyderm-sensitive-red-skin-tinted-SPF30-cream', 'name' => 'FREZYDERM SENSITIVE RED SKIN TINTED SPF 30 CREAM Έγχρωμη Κρέμα για Ευαίσθητο Δέρμα 30ml', 'description_short' => '<p><strong>SENSITIVE RED SKIN TINTED SPF 30 CREAM </strong></p><p><strong>Έγχρωμη Κρέμα για Ευαίσθητο Δέρμα</strong></p><p><strong>CC Cream</strong></p><p>Περιεχόμενο:30ml<br /><br />Δείκτης Προστασίας: SPF 30</p><p>74% μείωση μικροκυκλοφορίας. Υποαλλαεργικό προϊόν.</p><p>Χωρίς parabens και άρωμα </p><p></p>', 'id_category_default' => '156', 'id_image' => '843', 'legend' => '', 'sales' => '1', 'ean13' => '5202888271649', 'upc' => '', 'category' => 'frezyderm-face-sensitive-skin', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '1', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '695', 'id_product_attribute' => '0', 'link_rewrite' => 'avogel-atrosan', 'name' => 'A.VOGEL Atrosan Για την Καλή Λειτουργία των Αρθρώσεων και του Μυοσκελετικού Συστήματος 60 Ταμπλέτες', 'description_short' => '<p><strong>A.VOGEL Atrosan</strong><br /><strong></strong></p><p><strong>Ταμπλέτες από ρίζα αρπαγόφυτου</strong><br /><strong>Για την καλή λειτουργία των αρθρώσεων και του μυοσκελετικού συστήματος</strong><br /><br /></p><p>Περιεχόμενο: 60 Ταμπλέτες</p>', 'id_category_default' => '275', 'id_image' => '1210', 'legend' => '', 'sales' => '1', 'ean13' => '7610313394029', 'upc' => '', 'category' => 'avogel-phytotherapy', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '4', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '919', 'id_product_attribute' => '0', 'link_rewrite' => 'lamberts-aminoacids-bcaa', 'name' => 'LAMBERTS BCAA – Branch Chain Amino Acids 180 Κάψουλες', 'description_short' => '<p><strong>BCAA – Branch Chain Amino Acids</strong><br /><i>Ελεύθερης Μορφής</i><br /><br /><strong>Gluten Free, Dairy Free</strong><br /><br /></p><p>Tο προϊόν αυτό παρέχει τρία απαραίτητα αμινοξέα, την λευκίνη, την ισολευκίνη και την βαλίνη, συνδυαζόμενα σε ποσοστό 2:1:1 που εκτιμάται ότι αποτελεί την βέλτιστη αναλογία για αυτά τα τρία αμινοξέα. Όπως και με τα υπόλοιπα αμινοξέα της Lamberts, έτσι και τα συγκεκριμένα, είναι στην ‘ελεύθερη μορφή’ τους που σημαίνει ότι είναι έτοιμα να απορροφηθούν και να χρησιμοποιηθούν από τον οργανισμό.<strong></strong></p><p></p><p>Περιεχόμενο: 180 Κάψουλες</p>', 'id_category_default' => '246', 'id_image' => '1434', 'legend' => '', 'sales' => '1', 'ean13' => '5055148411015', 'upc' => '', 'category' => 'lamberts-aminoacids', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '20', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '1417', 'id_product_attribute' => '0', 'link_rewrite' => 'avene-cold-cream-40ml', 'name' => 'Avene Cold Cream Κρέμα για Ευαίσθητο & Ξηρό Δέρμα 40ml', 'description_short' => '<p><strong>Cold Cream Κρέμα για Ευαίσθητο &amp; Ξηρό Δέρμα</strong><br /><strong></strong></p><p>Περιεχόμενο: 40ml<br /><br />Η Avène Cold Cream Κρέμα θρέφει, ενυδατώνει και προστατεύει το δέρμα σας από τις εξωτερικές επιθέσεις. Mε την πλούσια υφή της προσφέρει εξαιρετική άνεση στο δέρμα σας αμέσως. Επίσης περιέχει Ιαματικό Νερό της Avène, που είναι καταπραϋντικό και αντι-ερεθιστικό, προσφέροντας στο δέρμα σας άμεσο αίσθημα άνεσης.<br /><br /></p>', 'id_category_default' => '329', 'id_image' => '2026', 'legend' => '', 'sales' => '1', 'ean13' => '3282779002738', 'upc' => '', 'category' => 'avene-cold-cream', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '2', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '1734', 'id_product_attribute' => '0', 'link_rewrite' => 'freshline-freshbar-body-milks-mojito-lime', 'name' => 'FRESH LINE ΜΟΧΙΤΟ & ΛΑΙΜ Γαλάκτωμα Σώματος 200ml', 'description_short' => '<p><b>FRESH LINE ΜΟΧΙΤΟ &amp; ΛΑΙΜ  Γαλάκτωμα Σώματος 200ml</b><br /><br />Εμπλουτισμένο με έλαιο από αβοκάντο και αμύγδαλο<br /><br /></p><p>Περιεχόμενο: 200ml</p>', 'id_category_default' => '356', 'id_image' => '2359', 'legend' => '', 'sales' => '1', 'ean13' => '5204989121359', 'upc' => '', 'category' => 'freshline-freshbar-body-milk', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '3', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '1737', 'id_product_attribute' => '0', 'link_rewrite' => 'freshline-freshbar-body-milks-strawberry-milk', 'name' => 'FRESH LINE ΦΡΑΟΥΛΑ & ΓΑΛΑ Γαλάκτωμα Σώματος 200ml', 'description_short' => '<p><b>FRESH LINE ΦΡΑΟΥΛΑ &amp; ΓΑΛΑ  Γαλάκτωμα Σώματος 200ml</b><br /><br />Εμπλουτισμένο με έλαιο από αβοκάντο και αμύγδαλο<br /><br /></p><p>Περιεχόμενο: 200ml</p>', 'id_category_default' => '356', 'id_image' => '2362', 'legend' => '', 'sales' => '1', 'ean13' => '5204989121465', 'upc' => '', 'category' => 'freshline-freshbar-body-milk', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '0', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null), array('id_product' => '1784', 'id_product_attribute' => '0', 'link_rewrite' => 'korres-argan-oil-advanced-colorant-73-', 'name' => 'KORRES ARGAN OIL ADVANCED COLORANT 7.3 ΞΑΝΘΟ ΧΡΥΣΟ/ΜΕΛΙ', 'description_short' => '<p><strong>ARGAN OIL ADVANCED COLORANT</strong></p><p><strong>Μόνιμη Βαφή Μαλλιών </strong></p><p>Τεχνολογία Pigment-lock που Κλειδώνει το Χρώμα</p><p></p><p>Περιεχόμενο: 145ml</p><p>100% Kάλυψη Λευκών &amp; Γκρίζων</p><p>Μεγάλη Διάρκεια</p><p>Λαμπερό Χρώμα</p><p>Προστασία από φθορά</p><p></p><p>Χωρίς: Αμμωνία, PPD, Parabens, Σιλικόνες, Mineral oil, Ρεζορκίνη</p>', 'id_category_default' => '365', 'id_image' => '2445', 'legend' => '', 'sales' => '1', 'ean13' => '5203069054723', 'upc' => '', 'category' => 'korres-hair-color-set', 'show_price' => '1', 'available_for_order' => '1', 'quantity' => '11', 'customizable' => '0', 'minimal_quantity' => '1', 'out_of_stock' => '2', 'new' => '0', 'on_sale' => '0', 'product_attribute_minimal_quantity' => null)))in ProductSale.php line 230

-------------------------------[call stack goes on down to DispatcherCore->dispatch()]-------------------------

We cannot exactly pinpoint the moment the problem appeared. **It emerges in debug mode only so far** ... But up to a certain date in the near past the problem did not exist (because we had used debug mode to check another condition caused by an add-on).   In non-debug mode the store runs without problem. 

What is the cause of this discrepancy? 

Thank you
