### ISSUE TITLE
1.7.6.8 Backend products buttons do not work when filtering because CSS not found

### ISSUE THREAD

**Issue by amvidalrc** [PrestaShop/PrestaShop#21442] opened 2020-10-14 12:15 UTC
#### Describe the bug

When connected to the backend > catalog > products we can use this buttons without problem (Filtering buttons and grouped actions buttons)

![image](https://user-images.githubusercontent.com/8987957/95986812-d8932480-0e26-11eb-8ca4-2da93d990214.png)

When filtering some category, we can not use the buttons anymore. 
Here we filtered, and the button are not working anymore. The grouped actions if we choose some items, also doesnt work.

![image](https://user-images.githubusercontent.com/8987957/95986967-12fcc180-0e27-11eb-8cd8-ed65715f5a88.png)

The URL is loading index.php/sell/catalog/products/0/20/id_product/desc:

![image](https://user-images.githubusercontent.com/8987957/95987024-2871eb80-0e27-11eb-97b7-238b07f759c7.png)

The console show this error:

![image](https://user-images.githubusercontent.com/8987957/95987080-3aec2500-0e27-11eb-9d39-6b55c97405bc.png)

And its because Presta is calling bad this CSS when filtering, adding a slash on source:

![image](https://user-images.githubusercontent.com/8987957/95987179-59eab700-0e27-11eb-8b12-ba893a10302c.png)

#### Expected behavior

I want the buttons working in all situations.

#### Steps to Reproduce

1. Go to catalog > products
2. Click on filter by category and choose some one
3. When filtered try to use both buttons. nothing happens.

**Screenshots**

Added on the description.

#### Additional information

* PrestaShop version: Versión de PrestaShop: 1.7.6.8
* PHP version: Versión PHP: 7.1.33-18+0~20201008.40+debian9~1.gbp1abd52

Tried: PHP 7.2, PHP 7.3, disabling cache, enabling cache, removing cache manually, etc. nothing happens. Reinstalled and same behaviour.

**Comment by SimonGrn** [comment] 2020-10-14 13:42
Hello,

I don't reproduce your issue with the default theme for PrestaShop 1.7.6.8:
![image](https://user-images.githubusercontent.com/49909275/95997020-9e7c4f80-0e33-11eb-9cf9-ba4fb108905e.png)

My selector works properly as you can see here : 
![image](https://user-images.githubusercontent.com/49909275/95997261-e7340880-0e33-11eb-923f-a68e96e03949.png)


You seem to be using another theme (`default`) instead of `new-theme`.
We cannot help you if you're using a third-party theme or an old non-supported theme, sadly.

You left your admin url in your screenshots, if it's your production shop I highly advise you to change it and remove the url from the images above.

Please check the BO theme you're using.

**Comment by amvidalrc** [comment] 2020-10-14 13:47
Hello SimonGrn!

Thanks for the information. I'm not using any other admin theme, i'm using the default admin theme, i have not installed another theme for BO. As you can see my pictures are the same as you posted. 

I have reinstalled a fresh clean prestashop and i'm having the same behaviour. Can you tell me where is the admin theme switch to see that point?

In your repository you have "default" and "new-theme":

![image](https://user-images.githubusercontent.com/8987957/95997776-6a555e80-0e34-11eb-838e-39e8994ecc14.png)

So i'm using the defaults, my folder is like the repsitory one:

![image](https://user-images.githubusercontent.com/8987957/95997905-9375ef00-0e34-11eb-8641-7b844b292a29.png)

Thanks

Edit 1: In your screenshot if you click again on "Filter by categories" work? Me not and I get that console css error.

**Comment by SimonGrn** [comment] 2020-10-14 14:06
> Edit 1: In your screenshot if you click again on "Filter by categories" work? Me not and I get that console css error.

No problem on my end.

You said you reinstalled, is that true ? Because a fresh installation of `1.7.6.8` always target the `new-theme` for the BO, the `default` theme is actually the old BO theme, not used anymore.
Is this an upgraded shop ? If yes, what was the original version ?

**Comment by amvidalrc** [comment] 2020-10-14 14:39
Yes, it's true. It's not a upgraded shop. I a Prestashop + Spanish Language.  How can I fully disable the "default" theme? Who is calling href="//admin94 in the desc page?

This is my BO, I think its the new:
![image](https://user-images.githubusercontent.com/8987957/96003549-9ecc1900-0e3a-11eb-9464-33382c6c8f39.png)

Take this in consideration:
index.php/sell/catalog/products/0/20/id_product/desc

desc debug:
[...]
```
<script type="text/javascript">
    var help_class_name = 'AdminProducts';
    var iso_user = 'es';
    var lang_is_rtl = '0';
    var full_language_code = 'es';
    var full_cldr_language_code = 'es-ES';
    var country_iso_code = 'ES';
    var _PS_VERSION_ = '1.7.6.8';
    var roundMode = 2;
```
[...]

```
      <link href="/modules/emarketing/views/css/menuTabIcon.css" rel="stylesheet" type="text/css"/>
      <link href="/admin946mfkjz3/themes/new-theme/public/theme.css" rel="stylesheet" type="text/css"/>
      <link href="/modules/revsliderprestashop/admin/assets/css/adminicon.css" rel="stylesheet" type="text/css"/>
      <link href="/modules/jscomposer/assets/css/adminjscomposericon.css" rel="stylesheet" type="text/css"/>
      <link href="/modules/jscomposer/assets/css/select2.css" rel="stylesheet" type="text/css"/>
      <link href="/modules/jscomposer/assets/css/select2-bootstrap.css" rel="stylesheet" type="text/css"/>
      <link href="//admin946mfkjz3/themes/default/public/theme.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/ui/themes/base/jquery.ui.core.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/ui/themes/base/jquery.ui.theme.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/ui/themes/base/jquery.ui.accordion.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/ui/themes/base/jquery.ui.tabs.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/ui/themes/base/jquery.ui.menu.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/ui/themes/base/jquery.ui.slider.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/plugins/autocomplete/jquery.autocomplete.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/plugins/chosen/jquery.chosen.css" rel="stylesheet" type="text/css"/>
      <link href="/admin946mfkjz3/themes/default/css/vendor/nv.d3.css" rel="stylesheet" type="text/css"/>
      <link href="/modules/gamification/views/css/gamification.css" rel="stylesheet" type="text/css"/>
      <link href="/js/jquery/plugins/fancybox/jquery.fancybox.css" rel="stylesheet" type="text/css"/>
      <link href="/modules/ps_mbo/views/css/recommended-modules.css" rel="stylesheet" type="text/css"/>
  
  <script type="text/javascript">
var ad = "\/admin946mfkjz3";
```
In the same page i have both css...

Who is calling the second with the double slash? Why the buttons stop working because this CSS not found?

It's very extrange...

**Comment by SimonGrn** [comment] 2020-10-14 14:50
I just reinstalled a shop in Spanish, country Spain.
As you can see here, I don't reproduce your issue with a base installation. You may have a special module or modified something in the database, because a fresh install redirects to the correct CSS/JS files.
https://drive.google.com/file/d/1VN-TsRVEnTXN1lGo71hBKwPjDIIRnIZb/view
I don't have any error in my console.
The URLs are correct:
![image](https://user-images.githubusercontent.com/49909275/96005907-39c5f280-0e3d-11eb-88ff-c046756c950e.png)

Your problem seems to lie in your own configuration. Since we're not able to reproduce it, I close the issue. You can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you for your understanding.

**Closed as completed by SimonGrn** 2020-10-14 14:50 UTC
Labels: No change required

**Comment by amvidalrc** [comment] 2020-10-14 15:58
Sorry, I noticed my team was enabling jscomposer module, and the jscomposer module is loading extrange js/jQuery modules that broke the buttons, also broke and load the old CSS.

modules/jscomposer/jscomposer.php (Line 1137)

```
		if (Tools::version_compare(_PS_VERSION_, '1.7.5.0', '>')){ 
			   $this->addCSS(__PS_BASE_URI__ . $this->context->controller->admin_webpath . '/themes/default/public/theme.css'); 
				echo "<style>#nav-sidebar{display:none;}</style>";
			}
```

I let that here for more people that must being having this issue with JSComposer module.

**Comment by SimonGrn** [comment] 2020-10-14 16:36
Thank you, glad you found the cause !
