### ISSUE TITLE
"homepage configuration" and "advanced customization" are not shown into the Theme & Logo > Theme

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#17500] opened 2020-02-04 19:40 UTC
**Describe the bug**
Hi,
after we update from 1.6.1.24 to 1.7.6.3, **homepage configuration** and **Advanced Customization** are not shown into the Theme & Logo > Theme
Instead, in a local clean installation there are.

**To Reproduce**

1. Click on Theme & Log

**Online**

<img width="1202" alt="Schermata 2020-02-04 alle 20 36 18" src="https://user-images.githubusercontent.com/28685316/73780076-1915ab00-478e-11ea-9c94-91f339fddd60.png">

**local site**

<img width="1233" alt="Schermata 2020-02-04 alle 20 37 10" src="https://user-images.githubusercontent.com/28685316/73780113-26329a00-478e-11ea-94bc-0f99bba2543e.png">

Thanks for any reply.

**Additional information**
Online PrestaShop version: 1.7.6.3
Local PrestaShop version: 1.7.6.3
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-02-05 07:55
Hi @ballashop,

You need to install the `ps_themecusto` module.
![image](https://user-images.githubusercontent.com/16067358/73821822-10a48b00-47f5-11ea-9ba4-5201f165b9e1.png)
https://drive.google.com/file/d/1oYMMKZiPDPag8gytVFgULeyEYLi-slnF/view
I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by ballashop** [comment] 2020-02-05 07:56
@khouloudbelguith 
thanks, I'll check soon and I'll let you know.

**Comment by ballashop** [comment] 2020-02-05 08:12
Hi, 
the module it was installed, I tried to uninstall but I've got the first problem:
the italian text say:
I don't have a permission to uninstall the ps_themecusto module:

<img width="271" alt="Schermata 2020-02-05 alle 08 58 14" src="https://user-images.githubusercontent.com/28685316/73822608-c1f7f080-47f6-11ea-9d1a-dd50327b97f5.png">

then I tried again:

<img width="298" alt="Schermata 2020-02-05 alle 09 01 23" src="https://user-images.githubusercontent.com/28685316/73822726-0aafa980-47f7-11ea-8e0d-2b113b776cd1.png">
INSERT INTO `pspc_authorization_role` (`slug`) VALUES ("ROLE_MOD_TAB_ADMINTHEMESPARENT_CREATE")

since the module was still installed, I tried to uninstall again.
i've got this error:

![errore](https://user-images.githubusercontent.com/28685316/73822547-a1c83180-47f6-11ea-8f35-85dd63e2f856.png)

I read here https://github.com/PrestaShop/PrestaShop/issues/11105 that I have to clear the cache in:
var/cache/edv
and
var/cache/prod
Can I do that?
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2020-02-05 08:18
@ballashop, you need to clear cache manually by deleting all the folder into var/cache (prod & dev).

Thanks!

**Comment by ballashop** [comment] 2020-02-05 08:27
Ok,
I did with the cache, I delete al content inside:
var/cache/dev
var/cache/prod

In module manage:

<img width="1156" alt="Schermata 2020-02-05 alle 09 24 19" src="https://user-images.githubusercontent.com/28685316/73823819-57947f80-47f9-11ea-96bc-992cd3007310.png">

Do I activate the module?
Or do you suggest me to uninstall and install again?
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2020-02-05 08:32
@ballashop, yes, you need to enable it.

Thanks!

**Comment by ballashop** [comment] 2020-02-05 08:38
@khouloudbelguith 
Ok, 
I delete the cache by BO, but "Theme & Logo" has disappeared from the menu:

![theme](https://user-images.githubusercontent.com/28685316/73824799-169d6a80-47fb-11ea-9ae4-28ab7645b0b3.gif)

I'm going to crazy!
Any suggestions to show it again?
Thanks for your support.

**Comment by khouloudbelguith** [comment] 2020-02-05 08:40
@ballashop, after deleting cache from the BO => Advanced Parameters => Performance page => theme & Logo is not displaying anymore in the menu?

Thanks!

**Comment by ballashop** [comment] 2020-02-05 08:43
@khouloudbelguith  
yes.
Now I tried to open information page in BO, but I've got this advice:
Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe.
Thanks for your support.

**Comment by khouloudbelguith** [comment] 2020-02-05 08:46
@ballashop, it could be a permission issue on your server.
Thanks to check the permission on your server.

**Comment by ballashop** [comment] 2020-02-05 08:46
I apologize, the problem is given by the folder renamed by the ISP, I did not know that they were working on the site, I had not been notified.
I'm so sorry.
I'll let you know.
Thanks a lot for your support.

**Comment by khouloudbelguith** [comment] 2020-02-05 08:47
@ballashop, thanks!
Waiting for your feedback.

**Comment by ballashop** [comment] 2020-02-05 09:14
Hi @khouloudbelguith 
Ok, now I can operate on the website.

> after deleting cache from the BO => Advanced Parameters => Performance page => theme & Logo is not displaying anymore in the menu?

Yes is not displaying!
Any suggestion?
Thanks for your support.

**Comment by khouloudbelguith** [comment] 2020-02-05 09:19
@ballashop, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ballashop** [comment] 2020-02-05 09:29
@khouloudbelguith 
ok I'm going to reed it, thanks a lot.
I'll let you know asap.

**Comment by khouloudbelguith** [comment] 2020-02-05 09:35
@ballashop, thanks!
Waiting for your feedback.

**Comment by ballashop** [comment] 2020-02-05 10:13
@khouloudbelguith 
ok, I've read the article, thanks a lot.
I sent a message to ISP about php error log, about the debug, at the moment it is always active.
What do I have to add here?
Thanks a lot for your support.

**Comment by khouloudbelguith** [comment] 2020-02-05 10:44
@ballashop, the debug mode report if there are exceptions & the PHP error log.

Thanks!

**Comment by ballashop** [comment] 2020-02-05 10:48
@khouloudbelguith 
Can I send you via email some images?
I don't know if there are some information that show sensible data.
Can I?
Thanks a lot.

**Comment by ballashop** [comment] 2020-02-05 10:55
@khouloudbelguith 
could be useful, thanks
![debug](https://user-images.githubusercontent.com/28685316/73835783-4c981a00-480e-11ea-9c5f-d16b7a300fd4.png)

**Comment by khouloudbelguith** [comment] 2020-02-05 11:01
@ballashop,

>Can I send you via email some images?

My address mail: khouloud.belguith@prestashop.com
Let's be safe!

>could be useful, thanks

No!, there is no information in the screenshot.

Thanks!

**Comment by ballashop** [comment] 2020-02-05 11:07
@khouloudbelguith 
I sent you two images, the php error log doesn't show error.
Thanks for your support.

**Comment by khouloudbelguith** [comment] 2020-02-05 11:10
@ballashop, I sent you an email.

Thanks!

**Comment by ballashop** [comment] 2020-02-05 13:52
@khouloudbelguith,
to make sense about this issue, I removed the site's sensitive path and copy the errors you reported to me :

1. [2020-02-04 22:42:08] php.CRITICAL: Fatal Compile Error: Container4xd1p04\appDevDebugProjectContainer::load(): Failed opening required '_projectPath/var/cache/dev/Container4xd1p04/getRouting_LoaderService.php' (include_path='_projectPath/vendor/pear/pear_exception:_projectPath/vendor/pear/console_getopt:_projectPath/vendor/pear/pear-core-minimal/src:_projectPath/vendor/pear/archive_tar:.:/php7.1/lib/php')

**I cleaned the cache as you suggest me.**

2. [2020-02-05 09:01:15] php.DEBUG: Warning: filemtime(): stat failed for _projectPath/modules/touchize/touchize.php {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"_projectPath/src/Core/Addon/Module/ModuleRepository.php\",\"line\":439,\"trace\":[{\"file\":\"_projectPath/src/Core/Addon/Module/ModuleRepository.php\",\"line\":385,\"function\":\"getModule\",\"class\":\"PrestaShop\\\\PrestaShop\\\\Core\\\\Addon\\\\Module\\\\ModuleRepository\",\"type\":\"->\"}],\"count\":1})"} []

**I didn't find this module "touchize" inside the modules folder
I believe it has never been installed I have to ask ISP**

3. [2020-02-05 09:01:15] php.DEBUG: Warning: filemtime(): stat failed for _projectPath/modules/alcarecategorize/alcarecategorize.php {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"_projectPath/src/Core/Addon/Module/ModuleRepository.php\",\"line\":439,\"trace\":[{\"file\":\"_projectPath/src/Core/Addon/Module/ModuleRepository.php\",\"line\":385,\"function\":\"getModule\",\"class\":\"PrestaShop\\\\PrestaShop\\\\Core\\\\Addon\\\\Module\\\\ModuleRepository\",\"type\":\"->\"}],\"count\":1})"} []

**alcarecategorize --> idem for this module, I didn't find it.**

4. [2020-01-31 12:15:39] php.CRITICAL: Class 'DimensionalWeightCarrierRule' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'DimensionalWeightCarrierRule' not found at _projectPath/override/classes/Cart.php:392)"} []
[2020-01-31 12:15:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "DimensionalWeightCarrierRule" from the global namespace. Did you forget a "use" statement?" at _projectPath/override/classes/Cart.php line 392 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"DimensionalWeightCarrierRule\" from the global namespace.\nDid you forget a \"use\" statement? at _projectPath/override/classes/Cart.php:392)"} []

**we have this one dimensionalweight --> I'm going to ask to the developer about this error.**
I'll let you know asap.
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2020-02-05 13:58
@ballashop, thanks!
Waiting for your feedback.

**Comment by ballashop** [comment] 2020-02-06 09:50
Hi @khouloudbelguith 
the ISP found a problem about menu item "Theme & Logo", they wrote:
"the problem was generated by the module ps theme custom uninstalling it the theme and logo items reappeared."
In fact the menu reappears but in an incorrect position!
In the photo, the right menu is a local test, the left one is the "no production" site test online![theme-e-logo](https://user-images.githubusercontent.com/28685316/73925266-17eb9780-48ce-11ea-85b1-ac81ac6d3689.jpg)
I'm waiting your kind response.
Thanks a lot for your support.

**Comment by khouloudbelguith** [comment] 2020-02-06 10:34
@ballashop, so can you confirm these steps to reproduce the issue:
1. Upgrade shop from ps1.6.1.24 to PS1.7.6.3 using the 1-click upgrade v4.10.1
2. Uninstall the ps_themecusto module
3. Install it again
 => check the menu?

Is it?

Thanks!

**Comment by ballashop** [comment] 2020-02-06 10:56
Hi @khouloudbelguith 
About your question, very close to what you wrote but honestly we have done many and many more operations I'm so sorry that I didn't explain all of them. 
Due to the many errors received, every action taken, it was to resolve them:
when the error concerned permissions, action was taken to resolve user's DB tables.
When the problem was about the theme we bought, we uninstalled it. 
About the ps_themecusto, so we tried to install it, we've got this warning:

<img width="394" alt="Schermata 2020-02-06 alle 11 49 59" src="https://user-images.githubusercontent.com/28685316/73930469-d4495b80-48d6-11ea-8925-c24686c3f979.png">

INSERT INTO `pspc_authorization_role` (`slug`) VALUES ("ROLE_MOD_MODULE_PS_THEMECUSTO_CREATE")
The we trie again, and we success to install the ps_themecusto:
![ps_themecusto](https://user-images.githubusercontent.com/28685316/73930769-65b8cd80-48d7-11ea-90ae-b8ba2974ac26.jpg)

We have the logs of all the problems, they are too many I think for using this upgrade to put the site in production mode.
I hope can be useful.
I'm waiting your kind response.
Thanks a lot @khouloudbelguith for your support.

**Comment by khouloudbelguith** [comment] 2020-02-06 11:10
@ballashop, in my case, I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.6.1.24 using the 1-click upgrade v4.10.1.
https://drive.google.com/file/d/1TXenju1vy-CKv1Oc-V83dTfUh7nGM_QE/view
After the upgrade, the ps_themecusto is well installed.
Did you try to re-install the ps_themecusto again & check if the issue is fixed?

Thanks!

**Comment by ballashop** [comment] 2020-02-06 11:19
@khouloudbelguith 
I tried to find it in module manage:

<img width="915" alt="Schermata 2020-02-06 alle 12 16 27" src="https://user-images.githubusercontent.com/28685316/73932408-8a627480-48da-11ea-8408-83bb43bca7db.png">

and in module catalogue:

<img width="911" alt="Schermata 2020-02-06 alle 12 16 08" src="https://user-images.githubusercontent.com/28685316/73932424-977f6380-48da-11ea-9aad-04f47a824e96.png">


but I didn't find it!
Can I find it online? Or into the PS marketplace?
Thanks for your support.

**Comment by ballashop** [comment] 2020-02-06 11:38
@khouloudbelguith 
really sorry, I found it, I forgot that I renamed the ps_themecusto folder.
I'm going to re-install it.
I'll let you know.
Thanks for your support.

**Comment by khouloudbelguith** [comment] 2020-02-06 11:40
@ballashop, thanks!

>Can I find it online? Or into the PS marketplace?

https://github.com/PrestaShop/ps_themecusto/releases
[ps_themecusto.zip](https://github.com/PrestaShop/PrestaShop/files/4164840/ps_themecusto.zip)

Waiting for your feedback.

**Comment by ballashop** [comment] 2020-02-06 11:46
Hi @khouloudbelguith 
I tried to install, I've got the same error:

<img width="278" alt="Schermata 2020-02-06 alle 12 44 40" src="https://user-images.githubusercontent.com/28685316/73934395-98b28f80-48de-11ea-9d79-609d25c1e5a0.png">

<img width="291" alt="Schermata 2020-02-06 alle 12 44 57" src="https://user-images.githubusercontent.com/28685316/73934374-8fc1be00-48de-11ea-9cbb-b7e8c394f141.png">


INSERT INTO `pspc_authorization_role` (`slug`) VALUES ("ROLE_MOD_TAB_ADMINPSTHEMECUSTOADVANCED_CREATE")

**Comment by ballashop** [comment] 2020-02-06 11:48
@khouloudbelguith  
When I tried to activate it, I've got this warning:

<img width="274" alt="Schermata 2020-02-06 alle 12 47 49" src="https://user-images.githubusercontent.com/28685316/73934551-f8109f80-48de-11ea-971c-7013652fa5c3.png">

**Comment by khouloudbelguith** [comment] 2020-02-06 11:54
@ballashop, could you please try to uninstall the ps_themecusto module with rmoving the folder module & try to install it by uploading this
[ps_themecusto.zip](https://github.com/PrestaShop/PrestaShop/files/4164914/ps_themecusto.zip)

Thanks!

**Comment by ballashop** [comment] 2020-02-06 12:00
@khouloudbelguith 
ok I'll let you know. 
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2020-02-06 12:03
@ballashop, waiting for your feedback.

Thanks!

**Comment by ballashop** [comment] 2020-02-06 12:20
@khouloudbelguith 
I downloaded the zip file from your link
I delete the ps_themecusto folder form modules one
I cleaned the cache inside PS
I uploaded the ps_themecusto.zip
I cleaned the cache inside PS
I logged out form BO
I cleaned the browser cache
I logged in BO
the arrangement of the menu items is as before, the only difference, the item has been added "advanced personalization"

<img width="195" alt="Schermata 2020-02-06 alle 13 15 10" src="https://user-images.githubusercontent.com/28685316/73936551-648d9d80-48e3-11ea-8f7f-e7345d55d4c1.png">

Can I delete the file inside:
var/cache/prod
var/cache/dev
?
Thanks a lot for your support.

**Comment by khouloudbelguith** [comment] 2020-02-06 12:22
@ballashop, Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by ballashop** [comment] 2020-02-06 12:31
@khouloudbelguith 
I' really sorry but I don't know how do that.
Can you please tell me how or show me a guide?
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2020-02-06 12:33
@ballashop, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by ballashop** [comment] 2020-02-06 12:54
@khouloudbelguith 
I did, nothing has changed :(
You have other suggestions?
Thanks for your support.

**Comment by khouloudbelguith** [comment] 2020-02-06 13:44
@ballashop, Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-06 13:44 UTC
Labels: Bug, Can't reproduce, Design, Theme & logo, Theme custo, 1.7.6.3

**Comment by ballashop** [comment] 2020-02-06 13:47
Ok @khouloudbelguith ,
thanks a lot for your support.
