### ISSUE TITLE
Create a cart rule excluding certain carriers PS 1.7.8.7 - OPEN

### ISSUE THREAD

**Issue by GuillaumeKoeglerSeiler** [PrestaShop/PrestaShop#36606] opened 2024-07-24 14:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I noticed a bug in a Prestashop 1.7.8.7, when creating a CartRule
I created a rule allowing customers, above a certain amount reached in the cart, to have free shipping, except for two carriers. The problem is that if I leave these carriers activated, the rule doesn't apply (even for the other carriers). Has anyone ever had this problem and knows the cause or solution?

### Steps to reproduce

1. Create a Cart Rule
2. set a minimum amount
3. select carriers and leave two unselected, but still active
4. set free delivery

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2024-07-25 13:27
Hello @GuillaumeKoeglerSeiler ,

Here's the cart rule :

https://github.com/user-attachments/assets/336f005e-a6ba-484a-9652-a4e984a54240

In my cart, the 2 carriers I've select are marked as Free :
<img width="1143" alt="Screenshot 2024-07-25 at 15 26 15" src="https://github.com/user-attachments/assets/96f2ae07-230e-4576-95cb-bd4050235a4f">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2024-07-25 13:27 UTC
Labels: Bug

**Comment by GuillaumeKoeglerSeiler** [comment] 2024-07-25 14:53
Hello @florine2623 thank you for you answer !
I know how to do this, and of course I did it before opening this ticket. Nevertheless, it works, then the system can't keep up because the promotion doesn't work after a while, for example clearing the cache

**Comment by EvKoh** [comment] 2025-04-20 08:34
We are experiencing the exact same issue described in #36641, confirmed on PrestaShop version 8.2.0.

🧾 Environment
PrestaShop version: 8.2.0 (official release, no core modifications)

PHP: 8.1.26-FPM

Web server: Nginx 1.24

MySQL: 8.0.36

Theme: Classic (no override)

Modules: No third-party checkout or carrier modules (no OPC, no carrier overrides)

Cache: Fully disabled (BO > Advanced Parameters > Performance)

🔁 Steps to reproduce
Create a cart rule in BO → Discounts → Cart rules:

Minimum amount: €20 (tax included, exclude shipping)

Action: Free shipping = YES

Country: France

Carrier restriction: Only “Mondial Relay France Relais” (ID: 516)

Code field: empty (auto-apply)

On Front Office:

Add 1 product costing €25 (TTC)

Proceed to checkout → carrier “Mondial Relay” is pre-selected

Expected: Free shipping

Actual: Shipping cost of €3.91 still displayed

When user manually switches to another carrier and then switches back to “Mondial Relay”, free shipping is applied correctly

⚠️ Root cause
This bug is already described in #31470 and fixed in PR #31475.
The issue is caused by CartRule::checkCarrierRestrictions() rejecting the rule because the cart's default id_carrier is the same as the restricted one, and PrestaShop skips the rule application silently.

❗Clarification regarding your test validation
The initial report was submitted for version 1.7.8.7,
but the video shared by your team as validation is based on version 9.0.0.

Our version is 8.2.0 – so your test environment does not cover the actual affected versions (8.0.x to 8.2.x).

Therefore, your conclusion is incorrect, and the issue is not resolved in the currently maintained LTS versions.

✅ Conclusion
The bug is still present in 8.2.0. Please reopen this issue or clone it under the 8.x milestone and consider merging PR #31475 or equivalent. This bug negatively affects UX and cart rule logic, especially for shops using single-carrier setups with auto-applied rules.
