### ISSUE TITLE
Problems with the friendly url in French in the cart

### ISSUE THREAD

**Issue by AltilloJoyeros** [PrestaShop/PrestaShop#13031] opened 2019-03-24 19:33 UTC
Good afternoon,

We are having problems with the web-friendly url in the French language, when we click on the go to buy button, it does not reach the cart, the web falls, this happens only in the French language. Can you take a look and see what happens?
altillojoyeros.com/fr

Thank you.

Greetings,

**Comment by khouloudbelguith** [comment] 2019-03-25 09:14
Hi @AltilloJoyeros,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-25 09:15
@AltilloJoyeros, did you use PrestaShop 1.6.1?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-24 08:23
Hi @AltilloJoyeros,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-24 08:23 UTC
Labels: Bug, FO, No change required
