### ISSUE TITLE
Customer e-mail address not validated when beeing changed in the profile / frontend

### ISSUE THREAD

**Issue by dannyqwertz** [PrestaShop/PrestaShop#20351] opened 2020-07-27 09:05 UTC
#### Describe the bug

When a logged in customer changes its mail-address under **Your Account / Information** the mail-address is not validated.
This can cause further problems (like we had with our 1.7.5.2 - installation, this installation in combination with JTL-connector got stuck in a mail-loop and kept sending out mails to customers because of 1 invalid mail-address and an unhandled exception in JTL-connector)

#### Expected behavior

Mail-address needs to validated first (just like when registering or if changed in the backend)
and frontend needs to display a corresponding error message without changing profile to invalid mail-address.

#### Steps to Reproduce

1. Create a customer-account in Prestahop live-demo:
https://demo.prestashop.com
2. Go to your Profile -> Information
3. Change mail address to something invalid, e.g. `test.@testdomain.com.123`
This does not display a error message and updates profile to invalid mailaddress.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3381961/88523371-1fc40300-cff8-11ea-8086-a54e058ca468.png)

#### Additional information

* PrestaShop version: 1.7.5.2 upwards (?)

**Comment by khouloudbelguith** [comment] 2020-07-27 10:07
Hi @dannyqwertz,

I have the same behavior with PS1.7.5.1, PS1.7.6.7 and 1.7.7.x branch.
I think this is an improvement.
Ping @PrestaShop/prestashop-product-team what do you think?

It is reproduced from the FO and the BO.
Related to: https://github.com/PrestaShop/PrestaShop/issues/17809

Thanks!

**Comment by LouiseBonnard** [comment] 2020-07-28 10:14
Hi there, I cannot reproduce this behavior when I test it with Machine Shuffle, did I miss something? 🤔

See screenshots below for more information:

![Capture d’écran 2020-07-28 à 12 10 23](https://user-images.githubusercontent.com/32565890/88652893-ac8bc100-d0cb-11ea-8098-624f8dbf625f.png)

![Capture d’écran 2020-07-28 à 12 10 56](https://user-images.githubusercontent.com/32565890/88652896-adbcee00-d0cb-11ea-9a96-42401cb6c7bb.png)

**Comment by khouloudbelguith** [comment] 2020-07-28 10:20
Hi @LouiseBonnard,

Could you please check with this Address mail `test@testdomain.com.123`.
In your case there is a **`.`** before **`@`**, this is incorrect.

Thanks!

**Comment by LouiseBonnard** [comment] 2020-07-28 13:52
@khouloudbelguith, I've just tested with the suggested email and it works, you're right. But in the issue's example, the email address is `test.@testdomain.com.123`, not `test@testdomain.com.123`.

![Capture d’écran 2020-07-28 à 15 48 11](https://user-images.githubusercontent.com/32565890/88674620-50846500-d0ea-11ea-88f1-1d3dccf87cd1.png)

**Comment by khouloudbelguith** [comment] 2020-07-28 14:01
@LouiseBonnard, yes you are right!
![image](https://user-images.githubusercontent.com/16067358/88675424-38611580-d0eb-11ea-82a3-fc5a681526c3.png)
The address mail `test.@testdomain.com.123` not accepted => OK
The address mail `test@testdomain.com.123` accepted => NOK, I think this is the issue, @LouiseBonnard what do you think?
Ping @dannyqwertz waiting for your feedback.

**Comment by SimonGrn** [comment] 2020-07-28 14:05
Please keep in mind that there is NO REAL way to validate an email. Almost anything with an `@` is valid.
So `test.@domain.test.123` is "valid", as in "possible".
you can [read more here](https://medium.com/hackernoon/the-100-correct-way-to-validate-email-addresses-7c4818f24643) for example.

**Comment by PierreRambaud** [comment] 2020-07-28 14:12
There is an RFC about email format (https://tools.ietf.org/html/rfc8398).

The only "good" way to validate the email, is to send an email with a confirmation token, otherwise, whatever you write, it doesn't mean this email address can be reached.

**Comment by LouiseBonnard** [comment] 2020-07-28 16:01
Nice, thanks a lot for the feedback! If I understand well, there is no good quick solution? We could not add an extra validation parameter to check this field?

If no, **a possible solution would be to send the new address an email with a confirmation link** each time a user updates the email field: 1/ if the user confirms, the email address is updated in the personal account, 2/ if the user does not confirm, the field is not updated. And **the last solution would be to keep things as-is and plan a new way to deal with the email edition** for the next major version.

**Comment by jolelievre** [comment] 2020-07-28 16:23
I think the main issue here is not **how** we validate the email, but that we don't validate it the same way everywhere We must be consistent in our validation rules so that they are always the same
I believe @atomiix has worked on this validation rules recently (regarding the special cyrilic characters in email addresses)

**Comment by atomiix** [comment] 2020-07-29 08:07
I'm pretty sure we're consistent everywhere now. This issue seems to have been created for PrestaShop 1.7.5.2, and as @LouiseBonnard & @khouloudbelguith saw, the address `test.@testdomain.com.123` which was accepted in 1.7.5.2 is not accepted anymore in 1.7.6.x.
I'm gonna close this issue, feel free to reopen it if i'm missing something.

**Closed as completed by atomiix** 2020-07-29 08:07 UTC
Labels: Improvement, FO, Customer, No change required, 1.7.5.1, 1.7.7.x, 1.7.6.7

**Comment by dannyqwertz** [comment] 2020-08-05 11:46
Thank you all for your informations and checks!
addendum - as stated in my initial issue:
I again tried to change my mail-address (in demo.prestashop.com, should be `1.7.6.7` as of today) to exactly `test.@testdomain.com.123` (with the dot before the @) and this change took effect:

![grafik](https://user-images.githubusercontent.com/3381961/89408559-d9218780-d720-11ea-95e8-c5f477df2b62.png)

I actually didn't know that such a format would be possible but as stated by @jolelievre I cant register with this (or similar) mail-adress so there may still be some consistency-errors when validating these in user-profiles vs. in the registration process.
