### ISSUE TITLE
bad amount of tax with cart rule using percent 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#17045] opened 2020-01-07 14:16 UTC
**Describe the bug**
bad amount of tax with cart rule using percent  there is a 0,01 gap 

**To Reproduce**
1. Go to catalog -> discount 
2. Create a cart rule with percent discount (3% for example)
3. In international taxes -> enable taxes in cart
4. Go to the front and a product to the cart then the cart rule 

The amount of tax is not correct 

**Screenshots**
<img width="1199" alt="Capture d’écran 2020-01-07 à 14 50 41" src="https://user-images.githubusercontent.com/3034677/71901266-e57c3c80-315f-11ea-8db6-b8af7bac112b.png">

it should be 2.16 not 2.15 

Same error in the back office and the invoice
<img width="1275" alt="Capture d’écran 2020-01-07 à 14 59 18" src="https://user-images.githubusercontent.com/3034677/71901299-f462ef00-315f-11ea-8020-8dd6aa145948.png">
<img width="771" alt="Capture d’écran 2020-01-07 à 15 00 16" src="https://user-images.githubusercontent.com/3034677/71901397-2b390500-3160-11ea-87ec-96b9f46ef9f4.png">

**Additional information**
Bug on Develop
Ok with PS 176

**Comment by MatShir** [comment] 2020-01-27 13:47
@colinegin @atomiix  https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/price-calculation-rules.md this specs corresponds to this issue?

**Comment by atomiix** [comment] 2020-01-30 13:28
@MatShir yes

**Comment by colinegin** [comment] 2020-01-30 13:31
Yes @MatShir I was waiting for atomiix review before attaching it to this issue.
What do you think @atomiix ? Is it ok ?

**Comment by atomiix** [comment] 2020-01-30 14:52
@colinegin I really think we need more informations to better understand how price calculation should work. As we have options like "round on each row" or "round on total" it's probably because there is different use cases (that I'm not aware of ^^).
If you look at @eternoendless 's [comparison table](https://docs.google.com/spreadsheets/d/1NUIcZ63pofXwqdJaqHgplduNSMEK0KeQ_HEJkBiv20Q/edit#gid=0) on [his comment](https://github.com/PrestaShop/PrestaShop/issues/17161#issuecomment-574765444) you'll better understand what I'm talking about.

Also, there is other questions like: when dealing with discounts, should we calculate them before rounding or after rounding?
Maybe we should do a workshop with an accountant?

**Comment by colinegin** [comment] 2020-02-10 13:25
We cannot work on this for 1.7.7 as we lack deeper study. This needs to be studied and prioritized for 178.

**Comment by Hlavtox** [comment] 2020-03-23 16:16
@colinegin @sam-pires Do I understand correctly that new 1.7.7 will introduce important bug that you know about, and you guys just say, it needs to wait another year?

Maybe you should realise that this could lead to serious fines and problems for the merchants, if the taxes and amounts are not calculated correctly. 🙄

**Comment by colinegin** [comment] 2020-04-10 16:44
Hello @Hlavtox,

Thanks for warning us about this critical issue. You are correct, this can lead to big problems for some merchants. We have been discussing with the core team about it, we may have found a solution to fix this. Please follow the following issue for the fix we are going to provide : https://github.com/PrestaShop/PrestaShop/issues/18513.

Thanks again,

Coline

**Comment by colinegin** [comment] 2020-04-20 13:01
This issue is a duplicate of #18513, i close it but it should be fixed for 1.7.7

**Closed as completed by colinegin** 2020-04-20 13:01 UTC
Labels: Bug, PM ✔️, develop, Major, BO, FO, Duplicate, Discounts, Cart rules, Taxes and Prices, Regression, Broader topic
