### ISSUE TITLE
prestashop 1.7.8.2 does not change the language in admin

### ISSUE THREAD

**Issue by sitolab** [PrestaShop/PrestaShop#27523] opened 2022-01-29 08:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I installed prestashop directly from the official website I set the Italian language correctly throughout the course but some information such as the menu is in English img
![presta1](https://user-images.githubusercontent.com/35496189/151654305-5b1a8f6a-1e09-4d49-a89d-c41966e5074c.jpeg)
![presta2](https://user-images.githubusercontent.com/35496189/151654312-728f1475-2796-4e4c-a774-c27384af2ce1.jpeg)
![presta3](https://user-images.githubusercontent.com/35496189/151654315-9c476ac2-2646-433b-bd4f-67c908fa614b.jpeg)

in app / Resources / translations there is the it-IT folder

### Expected behavior

I would have expected the language to be in Italian

### Steps to reproduce

it is a clean installation of prestashop 1.7.8.2 I did not use any program loaded the zip file in the root and installed personally during the installation I selected the Italian language

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.2

**Comment by sitolab** [comment] 2022-01-29 09:57
I just updated to version 1.7.8.3 and the problem persists does not change the language

**Comment by hibatallahAouadni** [comment] 2022-01-31 11:24
Hello @sitolab 

Could you please update the language **BO**>**IMPROVE**>**International**>**Translations**, in the block **Add / Update a language**, update your Italian language and then check the menu: 

![image](https://user-images.githubusercontent.com/23308427/151785515-0ed91155-a3e4-4101-b3b3-48b762102395.png)

It works for me :wink: 
Waiting for your feedback.

Thanks!

**Comment by sitolab** [comment] 2022-01-31 14:53
thanks, this has already been tried and it doesn't work honestly I don't understand the problem, whatever it does the language doesn't change and everything is set correctly

**Comment by novashop** [comment] 2022-01-31 15:23
Hello,
same problem with Italian email content translations 
![Screenshot traduzioni Prestashop](https://user-images.githubusercontent.com/98758775/151820941-f9d94475-4cd7-4db8-b9b6-6812a04b25e9.jpg)

**Comment by novashop** [comment] 2022-01-31 15:25
I upgraded, but no results, no translations done.

**Comment by hibatallahAouadni** [comment] 2022-01-31 22:40
Hello @sitolab

Did you try to clear the navigator cache or to access the BO on incognito mode (browser)?
Cause it seems even @novashop doesn't encounter your issue.
Waiting for your feedback.

Thanks!

**Comment by sitolab** [comment] 2022-02-01 06:58
even browsing in incognito mode the problem persists, I attach videos

https://drive.google.com/file/d/1f3rJPGn0W-piAm8hmbQuwaaWIfLJZmct/view?usp=sharing

**Comment by novashop** [comment] 2022-02-01 09:03
Hello,
below I paste two screenshots of the email received from the Italian
customer and the BO part that does not translate the CMS:

![Screenshot traduzioni Prestashop-2](https://user-images.githubusercontent.com/98758775/151942240-5ebb7471-8fd6-46be-8671-d20638d2bfd5.jpg)
![Screenshot traduzioni Prestashop-1](https://user-images.githubusercontent.com/98758775/151942265-b8ec6fb1-afdc-4999-926a-2a2ac85290e3.jpg)

In addition to updating and disabling the English language, I tried to
clear the cache ... nothing to do, the problem remains.

I noticed a "strange" detail,
when in the BO I go to "Theme Email"> "Translate e-mails" and I perform the
translation in Italian, the translation is done well,


![Screenshot traduzioni Prestashop-3](https://user-images.githubusercontent.com/98758775/151942381-5a9da3ce-9266-4661-9a01-8a101b887f0f.jpg)

I click on "Save" but nothing happens, I do not get back the message of
successful saving or even an error.
Could this episode be related to the defect?


Il giorno mar 1 feb 2022 alle ore 07:58 sitolab ***@***.***>
ha scritto:

**Comment by novashop** [comment] 2022-02-01 09:18
![Screenshot traduzioni Prestashop-2](https://user-images.githubusercontent.com/98758775/151941767-1e3ac411-30a9-43dd-96f9-69c2980af895.jpg)
![Screenshot traduzioni Prestashop-1](https://user-images.githubusercontent.com/98758775/151941822-da2e244a-40bf-4eb8-9f5a-fe8825a7fa47.jpg)
![Screenshot traduzioni Prestashop-3](https://user-images.githubusercontent.com/98758775/151941846-6af9b0a7-c815-4c0d-abe2-5a1415edca2a.jpg)

**Comment by HanaRebaiQA** [comment] 2022-02-04 12:48
Hello @sitolab 

I was unable to reproduce your issue with PS1782 and PS1783 using theses cases : 
-Install shops with the italian language ==> BO is OK

https://user-images.githubusercontent.com/92912932/152531365-b1380dc7-b690-499f-b585-d27ec25d035f.mp4


-Install shops with the english language and update to italian ==> BO is OK

https://user-images.githubusercontent.com/92912932/152531866-052e92fc-5270-4fd7-bc7b-1575e01e9800.mp4


Just be sure that you clear all cache browser,  cache from BO (BO > CONFIGURE > Advanced Parameters > performance > Disable cache & change to Force compilation of Template compilation) and update language here
![image](https://user-images.githubusercontent.com/92912932/152531340-45756d75-db3e-4243-8179-513247d041ce.png)

So, i will close the issue!

Thank you!

**Closed as completed by HanaRebaiQA** 2022-02-04 12:48 UTC
Labels: Bug, BO, Translations, Invalid

**Comment by novashop** [comment] 2022-02-04 13:39
Hi Hana,
in fact I don't have the same problem as sitolab, I have the problem of the translations of the emails that PS sends to the customer in English, they should be in the Italian language.

I tried to perform all the possible solutions described by the post, but nothing, it doesn't work.

What should I do?

Thank you
Adriano

**Comment by HanaRebaiQA** [comment] 2022-02-04 13:56
Hello @novashop 

You should update the language in Italian in BO >Design>Email Theme 
![image](https://user-images.githubusercontent.com/92912932/152540718-ad3b5974-61da-4950-a9b0-5e2e706412e6.png)

If you still have the same problem, do not hesitate to create an issue to can investigate more on that.

Thank you!
