### ISSUE TITLE
Error in order checkout page prestashop 1.7.6.7

### ISSUE THREAD

**Issue by agricart** [PrestaShop/PrestaShop#21002] opened 2020-09-16 03:16 UTC
Facing issue in order checkout page
Multiple click on continue its reloading same page
Enabled debug mode
Found error as attached
![Screenshot_20200915-224312](https://user-images.githubusercontent.com/71344603/93288221-01f56c00-f7f9-11ea-9a62-e23b94568f6c.png)

**Comment by sarahdib** [comment] 2020-09-16 07:55
Hello @agricart,

since the provided information isn't sufficient to reproduce the issue, we are closing it. Feel free to open a new one with all the requested information. 

Thank you!

**Closed as completed by sarahdib** 2020-09-16 07:55 UTC
Labels: No change required
