### ISSUE TITLE
Issue with Tab::enablingForModule() while context language is not the default one

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#23654] opened 2021-03-15 15:13 UTC
#### Describe the bug

**Context**

- Language FR installed ;
- Language ES installed ;
- Language FR disabled ;
- Language ES as default ;
- Broswer in French; employee profile set with FR language.

**Needs**

- Add a Tab with an [] of names. No issues.
- Use of Tab::enablingForModule('module_name') to enable the tabs.

**Issues**

- The method enablingForModule() call the Tab::getCollectionFromodule('module'name'). The $idLang params is not given.
- As the $idLang is not given, it will be set as the contextual one. So, the profile employee (FR).
- This method returns a PrestaShopCollection of Tab construct with this $idLang.
- The update() inside the rest of the method failed.

**Reasons**

- The used $idLang is, in my case, the 1 (is the ID of the FR language on my shop). But, while calling the validateFieldsLang(), as the name property is not an array, it's transform to an array.
- After that, as the default language $idLang is missing inside this array, it's added as en ampty string.
- Of course, the Tools::isEmpty() test on it will trhow the "Tab->name is empty".

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-03-15 16:35
Hello @PrestaEdit 

Thanks for the provided details :clap: 
But could you please provide steps to reproduce :sweat_smile: 

Thanks!

**Comment by PrestaEdit** [comment] 2021-03-15 16:37
It’s need a module or some codes, you can do it, for sure. Really, it’s not possible to give specific steps, it’s more a deep issue with code.
It’s take already a lot of time for me to make the diagnostic, the bug report and change my working way, there.

**Comment by PierreRambaud** [comment] 2021-03-15 17:49
> It’s need a module or some codes, you can do it, for sure. Really, it’s not possible to give specific steps, it’s more a deep issue with code. It’s take already a lot of time for me to make the diagnostic, the bug report and change my working way, there. Le 15 mars 2021 à 17:35 +0100, Hibatallah Aouadni ***@***.***>, a écrit :
> […](#)
> Hello @PrestaEdit Thanks for the provided details  But could you please provide steps to reproduce  Thanks! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Could you please provide us a module as example.
We will not reverse-engineer something without a way to reproduce it easily.

**Comment by hibatallahAouadni** [comment] 2021-04-05 17:20
Hello @PrestaEdit ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-05 17:20 UTC
Labels: Bug, CO, Modules, Languages, No change required, 1.7.7.1
