### ISSUE TITLE
BO - Bad display of label in Email theme page

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26915] opened 2021-12-08 10:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad display of the two labels `Select your default email theme `and `Select the theme you want to overwrite` in front-end of Email Theme.
See the attached screen-shots : 
![image](https://user-images.githubusercontent.com/92912932/145192446-d5f66e2f-5d1d-4efe-9b00-1b212a7d6033.png)

### Expected behavior

The label must be well displayed like on PS1778 : 
![image](https://user-images.githubusercontent.com/92912932/145193276-cf73884e-aee3-4912-82dc-a5efda3e429f.png)

### Steps to reproduce

1. BO>Design>Email Theme
2. See Error >> The two labels `Select your default email theme `and `Select the theme you want to overwrite` are bad displayed

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

**Comment by unlocomqx** [comment] 2021-12-08 10:44
This seems to be fixed in a subsequent commit (https://github.com/PrestaShop/PrestaShop/commit/0f4853b021ab77875c5e97454d03f6d8270105f1) because it looks fine on 8.0.0
<img width="678" alt="2021-12-08 at 11 43 AM" src="https://user-images.githubusercontent.com/793712/145194864-5f6b49fb-8862-493a-b3fe-660e0a9f5903.png">

**Comment by hibatallahAouadni** [comment] 2021-12-08 10:45
@unlocomqx yes indeed

**Comment by hibatallahAouadni** [comment] 2021-12-08 11:07
Fixed on develop

**Comment by hibatallahAouadni** [comment] 2021-12-08 13:07
Ping @PrestaShop/product-team wdyt? should I close this issue as it's not reproducible on develop? or should we fix it on `1.7.8.x `branch?

**Comment by marionf** [comment] 2021-12-08 14:12
If it's a regression of the 1.7.8.0 it should be fixed on 1.7.8.X

**Comment by Progi1984** [comment] 2021-12-10 14:00
Fixed by @okom3pom in #26929 & tested by @florine2623

**Closed as completed by Progi1984** 2021-12-10 14:00 UTC
Labels: Bug, Trivial, BO, Regression, Fixed, Front-end, Email theme, PR available, 1.7.8.0, Verified
