### ISSUE TITLE
The URL rewrite (mod_rewrite) is not active on your server (is active)

### ISSUE THREAD

**Issue by Marcelozippo** [PrestaShop/PrestaShop#15861] opened 2019-10-07 21:52 UTC
Problem after moving my store, from Cloudways to cpanel. In cloudways I didn't have that problem
- * - * -
The URL rewrite (mod_rewrite) is not active on your server or it is not possible to check the server configuration. If you want to use friendly URLs you must activate this module.
- * - * -
The module is active on server. (mod_rewrite).
Cpanel 82.0.16
Centos 7
Apache
Ngnix (Engintron-Nginx-on-cPanel)
PHP Version: 7.3.10
MySQL Version: 10.3.18-MariaDB
PrestaShop version: 1.7.6.1
Current topic in use: warehouse
Traffic & SEO --SEO + URLs

**Comment by khouloudbelguith** [comment] 2019-10-08 08:14
Hi @Marcelozippo,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
Next version PrestaShop 1.7.7. will be compatible with PHP7.3.

For more details you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

Second, The `mod_rewrite` exists only for the apache environment. This is a wrong wording here if you are using Nginx. 
We have a similar issue about this warning, you can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/10178#issuecomment-458094643 for more details.
It is added to our bug roadmap.
Your ticket is a duplicate of #10178
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-08 08:14
Duplicate of #10178

**Closed as completed by khouloudbelguith** 2019-10-08 08:14 UTC
Labels: Duplicate
