### ISSUE TITLE
Missing options for credit note number

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#20340] opened 2020-07-24 20:19 UTC
#### Describe the bug
There is possible to configure format of invoice numbers. It is required to have the similar possibility also for credit note number. Otherwise it is not possible to use all invoice configuration possibilities because the invoice number and credit note number should have the similar format. 

#### Expected behavior
Add new configuration parameters for credit notes options:
- Add current year to credit note number 
- Reset sequential credit note number at the beginning of the year
- Position of the year date - After the sequential number or Before the sequential number
- Credit note number (the next credit note will begin with this number, and then increase with each additional credit note, set to 0 if you want to keep the current number)
- Legal free text
- Footer text 

#### Additional information
* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-07-27 08:35
Hi @juraj1000,

Thanks for your report.
Your ticket is a duplicate of #19707
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-07-27 08:35
Duplicate of #19707

**Closed as completed by khouloudbelguith** 2020-07-27 08:35 UTC
Labels: Duplicate, Credit notes
