### ISSUE TITLE
Module ps_googleanalytics Google Analytics (4.2.2) crash if products in category to display more than 20, with GA4 enabled

### ISSUE THREAD

**Issue by dnkhack** [PrestaShop/PrestaShop#32813] opened 2023-06-04 17:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Problem in ps_googleanalytics\classes\Wrapper\ProductWrapper.php
line 52
`        if (count($products) > 20) {
            $full = false;
        } else {
            $full = true;
        }`

When we are in category products. 
If in category set display products more than 20. Then in code the variable $full is altered in false we get a crash.

\ps_googleanalytics\classes\Hook\HookDisplayFooter.php
in the line 140 call 
`$products = $productWrapper->wrapProductList(isset($listing['products']) ? $listing['products'] : [], [], true);`

in this case, $products required FULL product wrap with all values of the product, like quantity.
But  $productWrapper->wrapProductList returned not full product information (array).
and then in line 171 this file addProductClick got the short product information (array).
$gaScripts .= $this->module->getTools()->addProductClick($products, $this->context->currency->iso_code);

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/168879f0-495d-47c2-b70d-f25f28c62a4d)

Whole IF block in line 52 ProductWrapper.php have to be removed. Or add a new variable to wrapProductList method to avoid this case.

### Steps to reproduce

1. Install modules on any version of PS 1.7 (however bug for any version of PS)
2. Enable Debug Mode
3. Go to Shop Parameters > Product Settings# Pagination -> Products per page = set to 24 or more
4. Go to ps_googleanalytics configuration, Set ID and enable GA4 features
5. Go to any category page where are products of more than 20! 
6. Get a crash

### PrestaShop version(s) where the bug happened

1.7.7-1.7.8 

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_googleanalytics 4.2.2

### Your company or customer's name goes here (if applicable).

DNK Soft

**Comment by sallemiines** [comment] 2023-06-05 11:53
Hello @dnkhack 

Following your steps I didn't manage to reproduce your issue  with PS 1789 , you can see the attached screen record 

https://github.com/PrestaShop/PrestaShop/assets/31663369/cf048b6f-c638-4ed6-8325-58b220220f1e


Did I miss smthg ? 
Please check and feedback ! 
Thank you !

**Comment by dnkhack** [comment] 2023-06-05 12:46
Hello @sallemiines 

I attached the video

https://prestashop.world/upload/ps_ga_bug.mp4

If you can't view the video in this video format I'll upload it to youtube!

**Comment by sallemiines** [comment] 2023-06-05 14:51
> Hello @sallemiines
> 
> I attached the video
> 
> https://prestashop.world/upload/ps_ga_bug.mp4
> 
> If you can't view the video in this video format I'll upload it to youtube!

Thank you for your feedback !
I re-check the issue with your updates 

Issue tested with 1788 , 1789 

![0-0-0-0-8074-1789-prestashop-en-6-accessories](https://github.com/PrestaShop/PrestaShop/assets/31663369/35a66d72-6b6a-40c4-9dbe-26ec606fdb68)

With PS804 

https://github.com/PrestaShop/PrestaShop/assets/31663369/9a5569e6-b592-4d2a-95e6-cf7a16e0e656

Thank you !

**Comment by Hlavtox** [comment] 2023-06-28 06:47
@sallemiines @dnkhack Hi, could you re-test it with current dev branch of google analytics? Should be fixed. Thank you!

**Comment by dnkhack** [comment] 2023-06-28 22:09
@sallemiines Hello. Tested! All work, without issue. 
Thank you. Have a good one 😉

**Comment by kpodemski** [comment] 2023-07-08 10:34
To be closed after new version of GA module release.

**Comment by micka-fdz** [comment] 2023-07-25 08:08
Hi @kpodemski, any news about this release?
We can't leave this notice in such an important module for merchants...

**Comment by Hlavtox** [comment] 2023-07-25 08:14
@micka-fdz It's already fixed, I am fixing some more things here, waiting for review currently - https://github.com/PrestaShop/ps_googleanalytics/pull/150

**Comment by kpodemski** [comment] 2023-07-25 08:17
@micka-fdz you could help us by reviewing changes from @Hlavtox PR :)

**Comment by Hlavtox** [comment] 2023-11-28 17:52
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/32813

**Closed as completed by Hlavtox** 2023-11-28 17:52 UTC
Labels: Bug, Major, BO, Google Analytics, 1.7.7.0, Verified, Module
