### ISSUE TITLE
Problem with the product edit view in the backoffice

### ISSUE THREAD

**Issue by psgpolska** [PrestaShop/PrestaShop#27000] opened 2021-12-15 17:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Issue with the product edition view in the backoffice after upgrading from 1.7.7.6 to 1.7.8.2. The product editing page is gone, as you can see on the screenshots, there is a problem with adding photos and category support

I was cleaning the browser memory of course, manually cleaning the prestashop cache, cloudflare. It did not hel
![2021-12-15_18h43_08](https://user-images.githubusercontent.com/82633277/146238818-1570ab19-03b6-48cf-968d-519d381f3bea.png)
![2021-12-15_18h43_59](https://user-images.githubusercontent.com/82633277/146238822-29158352-ccd3-4b57-874d-57112e3d9929.png)
![2021-12-15_18h45_19](https://user-images.githubusercontent.com/82633277/146238824-871b9873-b537-449a-a1a6-bf8b17d89484.png)
![2021-12-15_18h45_40](https://user-images.githubusercontent.com/82633277/146238827-63e81c59-04e7-429c-954b-87ac7f776df5.png)
![2021-12-15_18h47_46](https://user-images.githubusercontent.com/82633277/146238828-32b71b65-bd2e-4790-b27a-b8bcd6b21345.png)
p

### Expected behavior

How to restore product edit page to correct format?

### Steps to reproduce

1.log in to the prestashop panel
2. go to the product edition
3. The problem appears when adding / editing photos and when editing a product category

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment] 2021-12-16 09:41
Hello @psgpolska 

I didn't manage to reproduce the issue with PS1776 upgraded to PS1782, see the attached screen record below:

https://www.awesomescreenshot.com/video/6471213?key=e58c4085a39de331f79ab7c2ba88b8fd

The only issue I have encountered is #26543 which caused by Browser cache.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-05 16:43
Hello @psgpolska 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-05 16:43 UTC
Labels: Bug, BO, Autoupgrade, Invalid, Module
