### ISSUE TITLE
There are not enough in stock - after deleted the personalization field

### ISSUE THREAD

**Issue by jajarom** [PrestaShop/PrestaShop#18078] opened 2020-03-10 13:38 UTC
#### Describe the bug

After i deleted the personalization field, items cannot be added into the cart - There are not enough in stock (virtual product, stock 999 pcs).
If i add again a customization field, it's working.
This happened after i upgraded from 1.7.6.3 to 1.7.6.4

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to 'https://www.gpg.ro/activari-si-credite/activare-suport-1-an-nck-box-sau-nck-dongle'
2. Click on 'Adauga in cos'
3. Scroll down to 'right-up corner'

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-10 15:17
Hi @jajarom,

1. Your Product is a virtual product?
![image](https://user-images.githubusercontent.com/16067358/76327258-1573c780-62ea-11ea-8421-bdffa715f420.png)
2. Your Customization is required or not?
![image](https://user-images.githubusercontent.com/16067358/76327338-2de3e200-62ea-11ea-9a6a-bce852a71b5d.png)
3. >deleted the personalization field

How did you delete the personalized field?

Thanks!

**Comment by jajarom** [comment] 2020-03-10 15:19
1. Yes
2. Yes
3. From back Office

**Comment by khouloudbelguith** [comment] 2020-03-10 15:31
@jajarom, I did not manage to reproduce the issue with PS1.7.6.4 after an upgrade from PS1.7.6.3 using the 1-click upgrade v4.10.1.
I attached a screen record
https://drive.google.com/file/d/1rczSqYNRksg3fm3mI5w6qoiAbWNZMq_c/view
Thanks to check and feedback.

**Comment by jajarom** [comment] 2020-03-10 15:36
Your screen still point on Presta 1.7.6.4

**Comment by khouloudbelguith** [comment] 2020-03-10 15:39
@jajarom, yes, it is a shop 1764 upgraded from PS1763.
Isn't your case?

Thanks!

**Comment by jajarom** [comment] 2020-03-10 15:58
Yes...

**Comment by khouloudbelguith** [comment] 2020-03-10 16:03
@jajarom,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by jajarom** [comment] 2020-03-10 19:07
If I clone the product I see the customization field from the old product, even if I deleted it before doubling. Where can i fix this? Beacause i have some products...

**Comment by khouloudbelguith** [comment] 2020-03-11 09:07
@jajarom, about your first issue, isn't similar to this: https://github.com/PrestaShop/PrestaShop/issues/16260?
>If I clone the product I see the customization field from the old product, even if I deleted it before doubling

I created an issue about this bug, it added to our bug roadmap.
https://github.com/PrestaShop/PrestaShop/issues/18086
Thanks!

**Comment by jajarom** [comment] 2020-03-11 09:47
The problem is at Prestashop.
There is a quick fix if you have an editing module installed, here will appear the fields that Prestashop has not deleted. After deletion, everything is ok

**Comment by khouloudbelguith** [comment] 2020-03-11 10:12
>There is a quick fix if you have an editing module installed, here will appear the fields that Prestashop has not deleted. After deletion, everything is ok

The first issue: "There are not enough in stock - after deleted the personalization field" 
or this issue: https://github.com/PrestaShop/PrestaShop/issues/18086?

Thanks!

**Comment by jajarom** [comment] 2020-03-11 10:32
First issue

**Comment by khouloudbelguith** [comment] 2020-03-11 11:10
@jajarom,

>an editing module installed

Which exact module?
Following the same steps, I did not manage to reproduce the issue as recorded previously.

Thanks!

**Comment by marionf** [comment] 2020-04-08 13:30
Hello,
Since we had no news from you for more than 25 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Closed as completed by marionf** 2020-04-08 13:30 UTC
Labels: Bug, FO, Product customization, No change required, 1.7.6.4
