### ISSUE TITLE
Access to BO Products only in Debug Mode otherwise white page (WSOD)

### ISSUE THREAD

**Issue by estebanwoj** [PrestaShop/PrestaShop#17409] opened 2020-01-29 14:21 UTC
I can only access BO Products when I active debug mode otherwise I get a white page, with no errors and a code 200.

1. Remove cache (var/cache/*)
2. Go to BO products (v1.7.4 & 1.7.5 are concerned)

PrestaShop version: v1.7.4 & 1.7.5
PHP version: 7.x (i tried all of them)

Rights are 777, in local developpement (to avoid problems) with docker (tried on apache and nginx, it's the same result) and all different versions of PHP 7
I have spent a lot of time to find this :
- I find a way to get debug off and make it working by commenting ob_start() and ob_clean() in src/PrestaShopBundle/Twig/HookExtension.php, method renderHooksArray()... but why ? 

For sure, I've already try to renew cache if somethings was wrong.

Thank you for your help

**Comment by khouloudbelguith** [comment] 2020-01-29 14:43
Hi @estebanwoj,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.3
I attached a screen record
https://drive.google.com/file/d/1ipkxas-f9_Ef97vFjsC6-M8EEDbcQkq7/view
>I get a white page

It is such a vague error.

Did you use opcache?

>PHP version: 7.x (i tried all of them)

PrestaShop is not compatible with PHP 7.3 & PHP7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Thanks!

**Comment by estebanwoj** [comment] 2020-01-29 15:14
I agree, it is such a vague error.

There is no cache, and recompile templates on calls.

I can access Products list, but i can't edit them, sorry it was not clear.

It's not a fresh install, both case there was a manual migration.
In this case a 1.7.4 -> 1.7.5 by executing upgrade.php script.

Everything was fine, and after a cache refresh my Products couldn't be edited anymore without the debug mode.

I increase memory_limit up to 1024M and max_execution_time to 360
This problem is quite tricky...
I've got no errors to report a missing file or something else, so I'm a bit lost about this issue.

**Comment by khouloudbelguith** [comment] 2020-01-29 15:18
@estebanwoj, Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by estebanwoj** [comment] 2020-01-29 15:48
I really appreciate your reactivity, thank you.

root@c667a2726295:/var/www/html# rm -fR var/cache/*
root@c667a2726295:/var/www/html# php -d memory_limit=-1 ./bin/console cache:clear

 // Clearing the cache for the dev environment with debug true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


root@c667a2726295:/var/www/html# php -d memory_limit=-1 ./bin/console cache:clear --env=prod

 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


php_1            | 2020-01-29 15:33:26 "GET /adminXXXX/index.php/sell/catalog/products/661?_token=LnhxI3oTCxLyzxzzZDj2kxeSoLvA5y3slyI-EbhKvEY" 200 695.433ms

Sadly, always a white page.

The content of var/cache/prod :

root@c667a2726295:/var/www/html/var/cache/prod# ll
drwxr-xr-x  2 www-data www-data 4,0K janv. 29 16:45 cachefs
drwxr-xr-x  2 www-data www-data 112K janv. 29 16:45 Container5xmsozh
drwxr-xr-x  9 www-data www-data 4,0K janv. 29 16:45 doctrine
drwxr-xr-x  3 www-data www-data 4,0K janv. 29 16:45 localization
drwxr-xr-x  6 www-data www-data 4,0K janv. 29 16:45 pools
drwxr-xr-x  2 www-data www-data 4,0K janv. 29 16:45 purifier
drwxr-xr-x  2 www-data www-data 4,0K janv. 29 16:45 push
drwxr-xr-x  2 www-data www-data 4,0K janv. 29 16:45 sandbox
drwxrwx--x  3 www-data www-data 4,0K janv. 29 16:45 smarty
drwxr-xr-x  2 www-data www-data 4,0K janv. 29 16:45 tcpdf
drwxr-xr-x  2 www-data www-data 4,0K janv. 29 16:45 translations
drwxr-xr-x 36 www-data www-data 4,0K janv. 29 16:45 twig
drwxr-xr-x  2 www-data www-data 4,0K janv. 29 16:45 yaml
-rw-r--r--  1 www-data www-data  72K janv. 29 16:45 AdminContainer.php
-rw-r--r--  1 www-data www-data 1,6K janv. 29 16:45 AdminContainer.php.meta
-rw-r--r--  1 www-data www-data  165 janv. 29 16:45 annotations.map
-rw-r--r--  1 www-data www-data  910 janv. 29 16:45 appParameters.php
-rw-r--r--  1 www-data www-data  743 janv. 29 16:45 appProdProjectContainer.php
-rw-r--r--  1 www-data www-data  33K janv. 29 16:45 appProdProjectContainer.php.meta
-rw-r--r--  1 www-data www-data 183K janv. 29 16:45 appProdProjectContainerUrlGenerator.php
-rw-r--r--  1 www-data www-data  13K janv. 29 16:45 appProdProjectContainerUrlGenerator.php.meta
-rw-r--r--  1 www-data www-data 289K janv. 29 16:45 appProdProjectContainerUrlMatcher.php
-rw-r--r--  1 www-data www-data  13K janv. 29 16:45 appProdProjectContainerUrlMatcher.php.meta
-rw-r--r--  1 www-data www-data 219K janv. 29 16:45 cacert.pem
-rw-r--r--  1 www-data www-data  92K janv. 29 16:45 class_index.php
-rw-r--r--  1 www-data www-data  14K janv. 29 16:45 class_stub.php
-rw-r--r--  1 www-data www-data  76K janv. 29 16:45 FrontContainer.php
-rw-r--r--  1 www-data www-data 1,5K janv. 29 16:45 FrontContainer.php.meta
-rw-r--r--  1 www-data www-data  13K janv. 29 16:45 namespaced_class_stub.php

**Comment by khouloudbelguith** [comment] 2020-01-29 15:53
@estebanwoj, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-27 08:08
Hi @estebanwoj,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-27 08:08 UTC
Labels: Bug, BO, No change required, 1.7.5.2
