### ISSUE TITLE
Saving carrier Technical Error: Details: Error thrown: [object Object] Text status: error

### ISSUE THREAD

**Issue by cleocreations** [PrestaShop/PrestaShop#34937] opened 2023-12-29 17:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This is the bug, to save carrier data:

Prestashop Technical Error: Details: Error thrown: [object Object] Text status: error

When saving or attempting to save carriers, the system is bugged and the error mentioned above appears, although SSL is already active throughout the site and does not allow enabling SSL, this happens on one of the servers that was tested, on the other simply was forced to reproduce the error

I never save the carriers, now if I delete it and recreate it, it saves but when I start to put a lot of data it gets bugged.

### Steps to reproduce

1. Go to "Carriers"
2. Modify or create a carrier (put all informations: price, ranges,...)
3. Click "Save"

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

Cléo Créations

**Comment by kpodemski** [comment] 2024-01-02 10:56
Hello @cleocreations 

I don't think this has anything to do with SSL. The error you mention is just a generic message saying that the request to save the carrier failed. Still, we won't reproduce it because it is probably related to your specific settings and installation.

To debug this problem, you'd have to enable developer mode and see the Ajax request in the Network tab in your browser.

**Comment by paulnoelcholot** [comment] 2024-01-02 13:54
Hello @cleocreations,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://www.loom.com/share/1b2c10d459444762b436ac38d3e0461c?sid=50871d5e-8ee7-401a-934b-97c54dff8fa7

**Closed as completed by paulnoelcholot** 2024-01-02 13:54 UTC
Labels: Bug, Can't reproduce, Invalid
