### ISSUE TITLE
Can't upgrade prestashop ads module on 1.7.6.4

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23338] opened 2021-02-22 02:21 UTC
#### Describe the bug

I have PrestaShop Ads v 2.0.8 and i can't upgrade it. 

The error say this.
Error!  Could not perform action update for module undefined

#### Steps to Reproduce

1. Have PrestaShop 1.7.6.4
2. Click on upgrade the module
3. See error

**Screenshots**

![20210222_032056.jpg](https://user-images.githubusercontent.com/62474824/108649123-06ffcb00-74bd-11eb-897c-72bd48dec354.jpg)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-22 09:37
Hello @alfonsolr09 

I didn't manage to reproduce your issue with PS1.7.4.1, PS1.7.6.4 and PS1.7.7.1 and it seems the issue is related to the module, cause in my case when I fresh install PS1.7.6.4, I got Prestashop Ads v2.2.0 and I upgraded to v2.2.1.

It seems that your issue is not a PrestaShop core bug.
If your module is Prestashop Ads Official, please contact support team on Addons.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-22 09:37 UTC
Labels: No change required
