### ISSUE TITLE
Search function also doesn't work

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#17210] opened 2020-01-16 12:38 UTC
Version de PrestaShop : 1.7.6.2
Thème actif : classic

The search function also doesn't work

Please see image:

- my site: http://prntscr.com/qnyuy1 -> http://prntscr.com/qnyv2s
- This is Prestashop default: http://prntscr.com/qnyvgm -> http://prntscr.com/qnyvl3

I Re-build the entire index again and always the same issue 

the search function also doesn't work

Regards

**Comment by khouloudbelguith** [comment] 2020-01-16 12:56
Hi @go-sudo,

>This is Prestashop default: http://prntscr.com/qnyvgm -> http://prntscr.com/qnyvl3

About the search which returns extra results => we are awre of this issue, please follow this tikcet: https://github.com/PrestaShop/PrestaShop/issues/14350

>my site: http://prntscr.com/qnyuy1 -> http://prntscr.com/qnyv2s

In my case, I did not manage to reproduce the issue with PS1.7.6.2
https://drive.google.com/file/d/13Nt9XzwK3Q3IMo9EmGdke0J4KxVPzPoI/view
It could be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10530
But it is fixed in the PS1.7.6.0
Or similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/9663, not fixed in PS1.7.6.2 but, the fix is avalable in the next release PS1.7.7.0
Thanks to check & feedback.

**Comment by go-sudo** [comment] 2020-01-20 05:17
Hello

I let you know that on new website the function works correctly 

![image](https://user-images.githubusercontent.com/11594433/72700582-88fc2280-3b4c-11ea-852d-6e796675835d.png)

with same PS version

Regards

**Comment by khouloudbelguith** [comment] 2020-01-21 16:50
@go-sudo, so, can we close the issue?

Thanks!

**Comment by go-sudo** [comment] 2020-01-25 02:03
But I can't find why on the other website the function does not work on default prestashop theme

**Comment by go-sudo** [comment] 2020-01-26 01:43
Hi @khouloudbelguith I installed the PS 1.7.6.2 on the same website on folder and the function does not work 
how can I debug the website where I have the issue to find what's wrong 

regards

**Comment by khouloudbelguith** [comment] 2020-01-27 11:45
Hi @go-sudo,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-26 07:38
Hi @go-sudo, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-26 07:38 UTC
Labels: Bug, FO, Search, No change required, 1.7.6.2
