### ISSUE TITLE
problem declination

### ISSUE THREAD

**Issue by ComptoirCarrelage** [PrestaShop/PrestaShop#10721] opened 2018-09-26 14:37 UTC
Hello,
we have a problem on our site
when we change a declination on a product, the photos linked to the declination do not appear and this message appears under the add to cart line:
an error occured while processing your request
**To Reproduce**
1. Go to 'https://comptoircarrelage.com/carrelage-parquet-serie-more-20x80-20x120-30x120-#/114-format_castelvetro-20x80_boite_de_096m/544-coloris_life_more_absolute_always-more_bianco'
2. Click on 'coloris castelvetro'
3. Scroll down to 'more miele'

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.30
Informations sur votre serveur Linux #1 SMP Thu Feb 15 06:51:19 CET 2018 x86_64

Version du logiciel serveur : Apache

**Comment by khouloudbelguith** [comment] 2018-09-26 14:48
Hi @ComptoirCarrelage,

Here's the Pr: https://github.com/PrestaShop/PrestaShop/pull/9390 to solve the issue
Your ticket is a duplicate of #9390
So, I close it.
Thanks !

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-26 14:48
Duplicate of ##9390

**Closed as completed by khouloudbelguith** 2018-09-26 14:48 UTC
Labels: Duplicate
