### ISSUE TITLE
Admin->Design->Positions Error 404

### ISSUE THREAD

**Issue by xandenet** [PrestaShop/PrestaShop#16219] opened 2019-10-30 19:04 UTC
**Describe the bug**
The Design, Positions tab provides a 404, I don't know how to solve ...

**To Reproduce**
1. Go to 'Admin'
2. Scroll on 'Design.'
3. Click down to 'Positions'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-31 07:44
Hi @xandenet,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-02 07:59
Hi @xandenet,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-02 07:59 UTC
Labels: Bug, BO, Design, Positions, No change required

**Comment by mlokeshm** [comment] 2020-04-24 16:31
I am facing same issue. Not sure what is causing it...
I am providing details below

Server information Linux #1 SMP Fri Feb 2 00:27:48 EST 2018 x86_64
Server software version: Apache
PHP version: 7.2.29
Memory limit: 256M
Max execution time: 30
Upload Max File size: 40M
PrestaShop version: 1.7.6.4
Shop URL: http://ps17.eco365.in/
Current theme in use: classic

MySQL version: 5.7.29
MySQL server: 127.0.0.1
MySQL engine: InnoDB
MySQL driver: DbPDO

URL that causes 404 Error
https://ps17.eco365.in/admin828q6ki8q/index.php/improve/design/modules/positions/?_token=aVzWqPTgCTEk2475sRax3RcRB3mhUC9n--97PU7WNdQ

Javascript Console
GET https://ps17.eco365.in/admin828q6ki8q/index.php/improve/design/modules/positions/?_token=aVzWqPTgCTEk2475sRax3RcRB3mhUC9n--97PU7WNdQ 404 (Not Found)

PHP Error Log
No Error Logged

Screenshot attached
![404 error](https://user-images.githubusercontent.com/45247302/80235130-e7b6c800-8676-11ea-93c4-e63458a2abd0.png)
