### ISSUE TITLE
Dashboard trends module not working

### ISSUE THREAD

**Issue by rafaviana** [PrestaShop/PrestaShop#12386] opened 2019-01-31 15:10 UTC
Hi,
Since I upgraded my store to 1.7 dashboard trends module stopped working. It's not showing any data (no orders, no sales, etc). I already tried to reset it but no result…

There are no errors in the browser console and error_log as well

Take a look the these screenshots so you can understand:
<img width="1207" alt="screen shot 2019-01-31 at 4 09 34 pm" src="https://user-images.githubusercontent.com/5817213/52063300-48d21780-256a-11e9-91c2-aec84c9199bb.png">
<img width="719" alt="screen shot 2019-01-31 at 4 09 40 pm" src="https://user-images.githubusercontent.com/5817213/52063319-4e2f6200-256a-11e9-8485-ee8e41ce693d.png">

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-01-31 15:52
Hi @rafaviana,

You have created an [issue previously](https://github.com/PrestaShop/PrestaShop/issues/12027) about the same bug.
During this period "2019-01-01 2019-01-31" did you generated any new invoices?
In my case, I did not manage to reproduce the issue with 1.7.5.0 after upgrade from PS1.7.4.4 with the 1-click upgrade v4.5.1.
![image](https://user-images.githubusercontent.com/16067358/52066366-abcaab00-2578-11e9-81ff-2f994a208759.png)
Thanks!

**Comment by rafaviana** [comment] 2019-01-31 16:50
Hi @khouloudbelguith . Where can I switch on the setting to generate invoices in the upcoming orders?
Thanks

**Comment by khouloudbelguith** [comment] 2019-01-31 16:59
@rafaviana, you should follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/12027#issuecomment-451469159) to generate all invoice for the previous order.
In your case, you disabled the generation of invoices in your status => so the upcoming orders cannot have invoices.
Thanks!

**Comment by rafaviana** [comment] 2019-01-31 17:26
@khouloudbelguith I don't need to regenerate new invoices, thank you anyway. To enable the generations of invoices what do I need to do? 
Thanks

**Comment by khouloudbelguith** [comment] 2019-01-31 17:34
@rafaviana, the order created is it valid?
Thanks!

**Comment by rafaviana** [comment] 2019-01-31 17:42
@khouloudbelguith I'm sorry I didn't understand, what do you mean?

**Comment by khouloudbelguith** [comment] 2019-02-01 08:11
Hi @rafaviana,

For each order created, there are different `order statuses` enables you to easily manage your orders and returns, and keep your customers informed of the evolution of their purchase.
The variously available statuses are visible and editable in the "Statuses" page, under the "Order settings" menu.
In the Statuses page, there are different options:
1. Consider the associated order as validated. If enabled, this status marks all associated orders as "paid", and puts them in this same status.
2. Allow a customer to download and view PDF versions of their invoice. If disabled, you will have to send customers their invoice yourself.
3. Hide this state in all customer orders. This enables you to create internal statuses, for you and your team. Customers will never see this in their order status page.
4. Send an e-mail to customer when his/her order status has changed. When enabled, a drop-down menu appears to let you choose which mail template to use.
5. Attach invoice PDF to email. Send an email to the customer with the invoice in PDF format attached.
6. Attach delivery slip PDF to email. Send an email to the customer with the delivery slip in PDF format attached.
7. Set the order as shipped. Be careful: once an order is set as "shipped", it cannot be set back to the previous status.
8. Set the order as paid. Same here: once an order is set as "paid", it cannot be set back to the previous status.
9. Show delivery PDF. Displays the delivery PDF.

In conclusion, to enable the generations of invoices, in the order status you should have this option "Allow a customer to download and view PDF versions of his/her invoices." checked.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-04 07:15
Hi @rafaviana,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-04 07:15 UTC
Labels: BO, Dashboard, Order, Dashtrends, No change required, 1.7.5.0
