### ISSUE TITLE
Faceted Search not displaying products correctly when filtering by price

### ISSUE THREAD

**Issue by gorkau** [PrestaShop/PrestaShop#23771] opened 2021-03-25 07:43 UTC
#### Describe the bug

We have the prices set as follows:

- Product price is set to 0.
- Products have combinations. The price is set in the combination.
- Discounts are set using specific prices for the combinations.

The product listing price is set to display 12 products on each page.

When you filter by prices some of the pages display fewer than 12 products.

#### Expected behavior

12 products should be displayed in each page when filtering by price.

#### Steps to Reproduce

Go to admin:

Create a new product.
Set price to 0.
Set no taxes.
Create a combination.
Set price for that combination to 100.
Set an specific price with impact price -50.

Go to front:

Filter price to be higher than 50.
Results page will say there is a product but it won't be displayed.

#### Additional information

* This happens after upgrading to 1.7.7.2 from 1.7.5.1.
* PrestaShop version: 1.7.7
* Faceted Search version: 3.7.1.

We have discovered that modules/ps_facetedsearch/src/Filters/Products.php executes a query that returns 12 results for the page in:

$matchingProductList = $this->searchAdapter->execute();

But then, in modules/ps_facetedsearch/src/Product/SearchProvider.php there is a second filtration that removes some of these products:

        $productsAndCount = $filterProductSearch->getProductByFilters(
            $query->getResultsPerPage(),
            $query->getPage(),
            $orderBy,
            $orderWay,
            $facetedSearchFilters
        );

Here is where some of the products dissapear.

We suspect that the initial query has some kind of problem.

**Comment by florine2623** [comment] 2021-03-25 09:16
Hello @gorkau ,
I can't reproduce your issue in PS 1.7.7.2, using ps_faceted_search v3.7.1.

Product price is 0 and Specific Price is like the following :
![Capture d’écran 2021-03-25 à 10 06 12](https://user-images.githubusercontent.com/16019289/112447657-daf09780-8d51-11eb-90b9-3d03a28ddbe0.png)
![Capture d’écran 2021-03-25 à 10 09 51](https://user-images.githubusercontent.com/16019289/112448154-65d19200-8d52-11eb-8393-9903323542c0.png)


Among my other products in my test shop, here is the result after filtering product price higher than 50 € :
![Capture d’écran 2021-03-25 à 10 08 34](https://user-images.githubusercontent.com/16019289/112447931-286d0480-8d52-11eb-9e1b-dea3b66dfa58.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thanks!

**Closed as completed by florine2623** 2021-03-25 09:16 UTC
Labels: No change required

**Comment by gorkau** [comment] 2021-03-25 09:42
We have discovered that adding these lines to modules/ps_facetedsearch/src/Adapter at line 503 (in our version) fixes the problem in our case:

```
            if ($filterName == "price_max") {
                $filterName = "price_min";
            }
```

**Comment by gorkau** [comment] 2021-03-25 09:48
This ticket should not be closed **as the problem can be reproduced in your own demo**:

https://demo.prestashop.com/#/en/front

Go to chothes and filter "more than 27":

![imagen](https://user-images.githubusercontent.com/19814346/112453044-2ce3ee00-8d4f-11eb-912d-df8095026657.png)


You will see a product.
Now filter "less than 43" and the product dissapears:

![imagen](https://user-images.githubusercontent.com/19814346/112452963-15a50080-8d4f-11eb-8b82-669fb12cb220.png)
