### ISSUE TITLE
Critical bug at checkout

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#14457] opened 2019-07-02 20:00 UTC
**Describe the bug**
Payment modules is loading long time because of validation. Tested with both bankwire and check. Please check screenshots.

**To Reproduce**
1. Go to 'Checkout'
2. Click on 'Accept payment'
3. Wait 10-20 sec before the screen update
4. See error and loadtime in console

**Screenshots**
![3](https://user-images.githubusercontent.com/26626066/60542681-c9ad5f00-9d14-11e9-9927-2b0d87903efb.png)
![4](https://user-images.githubusercontent.com/26626066/60542682-c9ad5f00-9d14-11e9-83ae-25e4b8746b67.png)
![1](https://user-images.githubusercontent.com/26626066/60542683-c9ad5f00-9d14-11e9-89f3-c71426e70999.png)
![2](https://user-images.githubusercontent.com/26626066/60542684-c9ad5f00-9d14-11e9-80a3-875b3bb74915.png)

**Additionnal information**
PrestaShop version: 1.7.6.0RC1
Serverinformation Linux #1 SMP Wed Feb 13 08:24:50 EST 2019 x86_64
Serversoftwarens version: LiteSpeed
PHP-version: 7.2.19
Hukommelsesgrænse: 756M
Maks. udførelsestid: 30
Upload maks. filstørrelse: 2M
MySQL-version: 10.2.24-MariaDB-cll-lve
MySQL-maskine: InnoDB
MySQL-driver: DbPDO
Webbrowser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by MathiasReker** [comment] 2019-07-02 20:03
Payment modules is loading long time because of validation. Tested with both bankwire and check. Please check screenshots.

**Comment by MathiasReker** [comment] 2019-07-02 20:35
Solved. Sorry, it was due to bad server settings.

**Comment by MathiasReker** [comment] 2019-07-03 08:09
I just tried with another clean install. Same issue.

![image](https://user-images.githubusercontent.com/26626066/60574777-7ff75f80-9d7a-11e9-8530-b9684ac2df8f.png)
![image](https://user-images.githubusercontent.com/26626066/60574858-a917f000-9d7a-11e9-96c2-fd6f83717e9d.png)

**Comment by MathiasReker** [comment] 2019-07-03 09:10
I tried to debug the issue, but I am stock. On my production server (Linux / LiteSpeed) $total return 0.0? Maybe it is the problem?
![5](https://user-images.githubusercontent.com/26626066/60579155-d36dab80-9d82-11e9-8873-65d1fa5c21b4.png)

And on my localhost running Windows / Apache on laragon, the $total is returned correct.

I use exactly the same PrestaShop settings (clean install).

**Comment by khouloudbelguith** [comment] 2019-07-03 09:42
Hi @MathiasReker,

I did not manage to reproduce the issue with PS1.7.6.0rc1 & the bank wire module.
https://drive.google.com/file/d/1fI4A5wZfu5abk8xEMeOO7YlWab-KO6EH/view
I used:

- Server information Linux #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64
- Server software version: Apache/2.4.10 (Debian)
- PHP version: 7.0.33-1~dotdeb+8.1

I used also "Swedish Krona" currency & 	Svenska language & it is OK
https://drive.google.com/file/d/1bLW0wMbM-HlMGNbvd-M1xyMsvXCZWgjB/view

The products added to your cart are they virtual products? product with combinations?

Thanks!

**Comment by MathiasReker** [comment] 2019-07-03 09:48
I got the same issue on both bankwire and check module. I think it is a core related issue.

Can you please try here: http://reker.dk/PS/

You can try with any product. I did just try with default installed products.

I use danish language with currency DKK / kr.

**Comment by khouloudbelguith** [comment] 2019-07-03 09:53
@MathiasReker, I tried with your shop & it is OK.
https://drive.google.com/file/d/1lORjXPion4tdMREo1O-olBi76QroLzJ7/view
Thanks!

**Comment by MathiasReker** [comment] 2019-07-03 10:06
@khouloudbelguith in your video you can see the validation is loading 10 seconds. It should be less than 1 second.

If you double click on the validation request you will be redirected to the exception.

**Comment by khouloudbelguith** [comment] 2019-07-03 10:22
@MathiasReker, this PR: https://github.com/PrestaShop/PrestaShop/pull/9373 prevent users from double click on the Payment button.
So, I cannot click twice on this button.
https://drive.google.com/file/d/13mJEyEVhYAVgKgD6_2dp0hwufht-or-V/view

Thanks!

**Comment by MathiasReker** [comment] 2019-07-03 10:41
@khouloudbelguith Please check this video: http://reker.dk/validation.webm

**Comment by sarahdib** [comment] 2019-07-03 12:29
hello @MathiasReker 

Thank you for your feedback.

Did you reproduce this bug on PS 1.7.5.2 ?

**Comment by MathiasReker** [comment] 2019-07-03 13:04
@sarahdib I will create a 1.7.5.2 shop on the server, so I can compare. I be back with more info later.

**Comment by Quetzacoalt91** [comment] 2019-07-03 13:28
Hi @MathiasReker, what country and language did you chose when installing PrestaShop?

**Comment by MathiasReker** [comment] 2019-07-03 13:28
@sarahdib same issue on 1.7.5.2: http://reker.dk/1752

@Quetzacoalt91 Country: Denmark, language; Danish

**Comment by MathiasReker** [comment] 2019-07-03 13:30
@Quetzacoalt91 I can give you access to my live test-server if you need a litespeed server to test it on?

**Comment by Quetzacoalt91** [comment] 2019-07-03 13:37
That's really weird, I tried on your shop and everything went fine:

![image](https://user-images.githubusercontent.com/6768917/60596059-1c802880-9da0-11e9-8ae1-5d29919e31d7.png)

**Comment by PierreRambaud** [comment] 2019-07-03 13:38
Same for me 
![image](https://user-images.githubusercontent.com/1462701/60596094-92888d80-9da8-11e9-907a-cf2991fe689b.png)

Try to clear your browser cache, even for cookie ? :thinking:

**Comment by MathiasReker** [comment] 2019-07-03 13:41
Yes, it went fine. But did it took 10-20 sec for the validator request?

**Comment by sarahdib** [comment] 2019-07-03 13:46
The same for me 
![image](https://user-images.githubusercontent.com/3034677/60596557-949f1c00-9da9-11e9-84cb-a79fa9b02ad1.png)

**Comment by MathiasReker** [comment] 2019-07-03 13:47
@PierreRambaud @Quetzacoalt91 When I do exactly the same on localhost (windows / Apache) my loadtime is less than 1 second. Please check this video: http://reker.dk/localhost.webm
So I think it is weird that this request takes 10 second on the production server (linux / LiteSpeed enterprise), when everything else on the production server is running fast.

**Comment by MathiasReker** [comment] 2019-07-03 13:50
Just to clarify: The redirection to order confirmation works, but the validation is taking 10-20 seconds. The load-time is the issue.

**Comment by sarahdib** [comment] 2019-07-03 14:23
@MathiasReker 
It seems to be related to your production configuration since in local the loadtime is less than 1 second and 4 persons did not reproduce the bug we will close the issue.

**Closed as completed** 2019-07-03 14:23 UTC
Labels: Bug, FO, Can't reproduce, Bankwire, Checkout, 1.7.6.0
