### ISSUE TITLE
Webservice error onto product add method

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#29315] opened 2022-08-11 16:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A php error occur when i try to add a product with webservice.
Error is:
```

Fatal error: Uncaught InvalidArgumentException: "" cannot be interpreted as a number in /var/www/prestashop/vendor/prestashop/decimal/src/Builder.php:36
Stack trace:
#0 /var/www/prestashop/vendor/prestashop/decimal/src/DecimalNumber.php(73): PrestaShop\Decimal\Builder::parseNumber('')
#1 /var/www/prestashop/classes/Product.php(883): PrestaShop\Decimal\DecimalNumber->__construct('')
#2 /var/www/prestashop/classes/Product.php(849): ProductCore->fillUnitRatio(false)
#3 /var/www/prestashop/classes/Product.php(801): ProductCore->updateUnitRatio()
#4 /var/www/prestashop/classes/Product.php(7542): ProductCore->add(true, false)
#5 /var/www/prestashop/classes/webservice/WebserviceRequest.php(1668): ProductCore->addWs()
#6 /var/www/prestashop/classes/webservice/WebserviceRequest.php(1443): WebserviceRequestCore->saveEntityFromXml(201)
#7 /var/www/prestashop/classes/webservice/WebserviceRequest.php(578): WebserviceRequestCore->executeEntityPost()
#8 /var/www/prestashop/webservice/dispatcher.php(90): WebserviceRequestCore->fetch('H2S in /var/www/prestashop/vendor/prestashop/decimal/src/Builder.php on line 36

```
### Expected behavior

I must have an XML output instead of this php error, even invalid data are send.

### Steps to reproduce

1. Enable webservice and debug mode
2. Send a request like this one:

```

<?php
    error_reporting(-1);
    ini_set('display_errors', true);
    $ch = curl_init();
    curl_setopt($ch, 10002, 'http://vps-c364ee61.vps.ovh.net/api/products&ws_key=KEY');
    curl_setopt($ch, 42, '1');
    curl_setopt($ch, 19913, '1');
    curl_setopt($ch, 2, '1');
    curl_setopt($ch, 10018, 'browser');
    curl_setopt($ch, 107, '1');
    curl_setopt($ch, 10005, 'KEY:');
    curl_setopt($ch, 13, '300');
    curl_setopt($ch, 10023, unserialize('a:1:{i:0;s:7:"Expect:";}'));
    curl_setopt($ch, 10036, 'POST');
    curl_setopt($ch, 10015, 'xml=<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
	<id><![CDATA[]]></id>
	<id_manufacturer><![CDATA[]]></id_manufacturer>
	<id_supplier><![CDATA[]]></id_supplier>
	<id_category_default>2</id_category_default>
	<new><![CDATA[]]></new>
	<cache_default_attribute><![CDATA[]]></cache_default_attribute>
	<id_default_image><![CDATA[]]></id_default_image>
	<id_default_combination><![CDATA[]]></id_default_combination>
	<id_tax_rules_group><![CDATA[]]></id_tax_rules_group>
	
	
	<id_shop_default><![CDATA[]]></id_shop_default>
	<reference>REF459</reference>
	<supplier_reference><![CDATA[]]></supplier_reference>
	<location><![CDATA[]]></location>
	<width>5</width>
	<height>6</height>
	<depth>7</depth>
	<weight>5</weight>
	<quantity_discount><![CDATA[]]></quantity_discount>
	<ean13><![CDATA[]]></ean13>
	<isbn><![CDATA[]]></isbn>
	<upc><![CDATA[]]></upc>
	<mpn><![CDATA[]]></mpn>
	<cache_is_pack><![CDATA[]]></cache_is_pack>
	<cache_has_attachments><![CDATA[]]></cache_has_attachments>
	<is_virtual><![CDATA[]]></is_virtual>
	<state>1</state>
	<additional_delivery_times><![CDATA[]]></additional_delivery_times>
	<delivery_in_stock><language id="1"><![CDATA[]]></language></delivery_in_stock>
	<delivery_out_stock><language id="1"><![CDATA[]]></language></delivery_out_stock>
	<product_type><![CDATA[]]></product_type>
	<on_sale><![CDATA[]]></on_sale>
	<online_only><![CDATA[]]></online_only>
	<ecotax>10</ecotax>
	<minimal_quantity>1</minimal_quantity>
	<low_stock_threshold><![CDATA[]]></low_stock_threshold>
	<low_stock_alert><![CDATA[]]></low_stock_alert>
	<price>20.833333</price>
	<wholesale_price><![CDATA[]]></wholesale_price>
	<unity><![CDATA[]]></unity>
	<unit_price><![CDATA[]]></unit_price>
	<unit_price_ratio><![CDATA[]]></unit_price_ratio>
	<additional_shipping_cost><![CDATA[]]></additional_shipping_cost>
	<customizable><![CDATA[]]></customizable>
	<text_fields><![CDATA[]]></text_fields>
	<uploadable_files><![CDATA[]]></uploadable_files>
	<active>1</active>
	<redirect_type><![CDATA[]]></redirect_type>
	<id_type_redirected><![CDATA[]]></id_type_redirected>
	<available_for_order>1</available_for_order>
	<available_date><![CDATA[]]></available_date>
	<show_condition><![CDATA[]]></show_condition>
	<condition>new</condition>
	<show_price>1</show_price>
	<indexed><![CDATA[]]></indexed>
	<visibility><![CDATA[]]></visibility>
	<advanced_stock_management><![CDATA[]]></advanced_stock_management>
	<date_add><![CDATA[]]></date_add>
	<date_upd><![CDATA[]]></date_upd>
	<pack_stock_type><![CDATA[]]></pack_stock_type>
	<meta_description><language id="1"><![CDATA[]]><![CDATA[Livraison rapide. Le TESLA est un mod électronique simple d'utilisation à Volt et Watt variable.]]></language></meta_description>
	<meta_keywords><language id="1"><![CDATA[]]><![CDATA[]]></language></meta_keywords>
	<meta_title><language id="1"><![CDATA[]]><![CDATA[Tesla - Chrome : Mod électronique]]></language></meta_title>
	<link_rewrite><language id="1"><![CDATA[]]></language></link_rewrite>
	<name><language id="1"><![CDATA[]]><![CDATA[After 8 0 é U %toto ² machine]]></language></name>
	<description><language id="1"><![CDATA[]]><![CDATA[<div class="row-fluid">desc longue</div>]]></language></description>
	<description_short><language id="1"><![CDATA[]]><![CDATA[desc courte]]></language></description_short>
	<available_now><language id="1"><![CDATA[]]></language></available_now>
	<available_later><language id="1"><![CDATA[]]></language></available_later>
<associations>
<categories>
	<category>
	<id><![CDATA[]]></id>
	</category>
</categories>
<images>
	<image>
	<id><![CDATA[]]></id>
	</image>
</images>

<product_option_values>
	<product_option_value>
	<id><![CDATA[]]></id>
	</product_option_value>
</product_option_values>
<product_features>
	<product_feature>
	<id><![CDATA[]]></id>
	<id_feature_value><![CDATA[]]></id_feature_value>
	</product_feature>
</product_features>
<tags>
	<tag>
	<id><![CDATA[]]></id>
	</tag>
</tags>
<stock_availables>
	<stock_available>
	<id><![CDATA[]]></id>
	<id_product_attribute><![CDATA[]]></id_product_attribute>
	</stock_available>
</stock_availables>
<attachments>
	<attachment>
	<id><![CDATA[]]></id>
	</attachment>
</attachments>
<accessories>
	<product>
	<id><![CDATA[]]></id>
	</product>
</accessories>
<product_bundle>
	<product>
	<id><![CDATA[]]></id>
	<id_product_attribute><![CDATA[]]></id_product_attribute>
	<quantity><![CDATA[]]></quantity>
	</product>
</product_bundle>
</associations>
<out_of_stock>1</out_of_stock></product>
</prestashop>
');
    echo curl_exec($ch);
    curl_close($ch);
```

### PrestaShop version(s) where the bug happened

8.0.0 beta1

### PHP version(s) where the bug happened

7.2.34

**Comment by Max84** [comment] 2022-08-11 16:22
It's the test file, i can't edit my post and we can't see the script onto initial post.
[test.zip](https://github.com/PrestaShop/PrestaShop/files/9310192/test.zip)

**Comment by HanaRebaiQA** [comment] 2022-08-11 16:39
Hello @Max84 

Thanks for your report.
I tried to reproduce your issue using PS8.0.0x and php7.3. But, i was unable to reproduce it.
I used another product request with API and i have no PHP error.

Here is a screen-record : 

https://user-images.githubusercontent.com/92912932/184186125-9ac698df-ed7e-49cd-90c3-b6aa013c8818.mp4

Could you please check ? We are waiting for your feedback!

Thank You!

**Comment by Max84** [comment] 2022-08-12 06:46
Hi @HanaRebaiQA

You don't reproduce because you don't use my own data.
Please check "<unit_price>" into my XML data.
I set it empty like this: <unit_price><![CDATA[]]></unit_price>.
If i delete it, there is no problem.

Even my unit_price data could be false, data should be validated by Prestashop and we shouldn't get a php error, only an application error.

Do you get it?

Thanks.

**Comment by hibatallahAouadni** [comment] 2022-08-16 17:02
Hello @Max84 

Your issue seems related to this one #9922
Could you please check it and feedback.

THanks!

**Comment by Max84** [comment] 2022-08-17 08:18
Hello @hibatallahAouadni

I'm sorry, I didn't find this issue previously. I'm not sure if it's linked to #9922, but feel free to merge them if you think it's better.
But let's me explain why, it might me not related to it.

I think #9922 is fixed with this Prestashop 8.0.0 beta 1, because, if you try to set a value to unit_price_ratio, you can update it. Try 0 or 5 for example, it works on my side.
So, I think you can close #9922.

The problem onto this issue #29315 is when you're trying to send an empty string. It shouldn't do an unexpected php exception. So I suggest keeping this issue #29315 open.

I think there is a problem with the validate function. I tested yesterday a fix, and I am able to purpose a pull request, I just need a few free times to send it to you (and of course if you're agree keeping this issue opened!). Do you have a deadline in order to merge it before next release?

Thanks.

**Comment by hibatallahAouadni** [comment] 2022-08-19 16:43
Reminder: we need to check if #9922 has been fixed with 8.0.0 beta. If it's not fixed yet, we need to close this one as a duplicate of #9922

**Comment by HanaRebaiQA** [comment] 2022-12-21 10:51
Hello @Max84 

I have checked again your issue. Here is my feedback : 

- Check with **your own data** that you have communcated above [test.zip](https://github.com/PrestaShop/PrestaShop/files/10276977/test.zip), I have an error when using it 

![image](https://user-images.githubusercontent.com/92912932/208888642-a96662e9-9869-4a81-902f-43f7a9a750ca.png)

https://user-images.githubusercontent.com/92912932/208887523-26886eec-1ebc-457e-ae38-9c3b7df9ed79.mp4


- Check with **my own data** but in this time i have added the **empty** `<unit_price></unit_price> ` attribute : 

**On PS8.0.x** : NOK :x: I reproduced the same issue 

![image](https://user-images.githubusercontent.com/92912932/209088690-6622131b-5cbe-4545-b211-b3b6ad2b6c11.png)

https://user-images.githubusercontent.com/92912932/208887222-59a03cdb-eebc-4a9d-b11e-d58235503ff9.mp4


**On PS1788** : OK :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/208887741-e2e2a501-b811-4ae7-ac84-606bb4a24320.png)

https://user-images.githubusercontent.com/92912932/208887751-e1c927ee-7d63-4c2e-a063-7f74b05a3748.mp4


Indeed, it's a regression on 8.0.x!

And for this ticket [#9922](https://github.com/PrestaShop/PrestaShop/issues/9922), so you can confirm it's the same. 
If yes, i will close it

Thank You!

**Comment by Max84** [comment] 2022-12-21 15:57
Thanks @HanaRebaiQA

**Comment by mflasquin** [comment] 2023-04-12 07:23
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32044

**Closed as completed by mflasquin** 2023-04-12 07:23 UTC
Labels: Bug, 8.0.x, Minor, WS, Webservice, Taxes and Prices, Regression, Fixed, PR available, Verified
