### ISSUE TITLE
Print order error

### ISSUE THREAD

**Issue by Axboard** [PrestaShop/PrestaShop#9835] opened 2018-08-22 19:57 UTC
After printing, the document does not look right.
<img width="1437" alt="zrzut ekranu 2018-08-22 o 21 16 50" src="https://user-images.githubusercontent.com/42621417/44486519-171c6280-a654-11e8-824b-9f9394146765.png">

PrestaShop version: 1.7.4.2
PHP version: 7.1.14

**Comment by khouloudbelguith** [comment] 2018-08-23 11:16
Hi @Axboard 

Your issue is a duplicate of #9527, so I close it.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-08-23 11:16 UTC
Labels: Bug, Duplicate, 1.7.4.2

**Comment by YIChunyue** [comment] 2019-01-03 17:08
the same problem

**Comment by khouloudbelguith** [comment] 2019-01-04 08:36
Hi @YIChunyue,

Your issue is fixed in the last version PS1.7.5.0.
Heres' the PR: https://github.com/PrestaShop/PrestaShop/pull/10135 to solve the issue.
Thanks!

**Comment by strifefrosst** [comment] 2019-01-30 10:53
Why didnt work for me? :S
i replace the 4 lines of code of these files: https://github.com/PrestaShop/PrestaShop/pull/10135/files

Versión PHP: 7.2.14 
Versión de PrestaShop: 1.7.4.4
