### ISSUE TITLE
Bug combination 1.7.5.1

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#16115] opened 2019-10-24 15:20 UTC
Good evening to all,
there is a bug in deleting combinations in 1.7.5.1 If I delete a combination, then I go to the front end of the product in question and choose the combination that is no longer present, it gives me a completely random combination. How can I handle this change of combinations? Is there an ordinarily particular?

**Comment by khouloudbelguith** [comment] 2019-10-24 15:47
Hi @Webgaict,

Thanks for your report.
Yes, I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.1.
I attached a screen record
https://drive.google.com/file/d/1RVRp7ilmDbQlZyXlfPVXSOhdoUju8nbj/view
Thanks to check & feedback.

**Comment by Webgaict** [comment] 2019-10-25 08:05
Hi,
I manage 1400 combinations for a product and I deleted as many. In practice, if I try to change an attribute in the front end and the combination with another attribute no longer exists, the other attributes also change. In the attached video you should only change the "Lanterna led" attribute not even the "Ruote Gommate" and "Mensola Reclinabile"
https://drive.google.com/open?id=1umJhAi32u7dhMbqgctrnXILIKC4VkZAV
 What can I do?

**Comment by khouloudbelguith** [comment] 2019-10-25 08:52
@Webgaict, so in your case, the "Ruote Gommate" and "Mensola Reclinabile" do not exist anymore?
Could you please explain to me how many combinations do you have for the "Lanterna led" & "Ruote Gommate" and "Mensola Reclinabile" at first before the deletion.
After that, did you delete the "No" combination for the "Lanterna led" attribute?
Thanks to provide me all the steps to reproduce the issue.

Thanks!

**Comment by Webgaict** [comment] 2019-10-25 09:17
Hi,
the combinations that have been canceled are "Impianto illuminazione: con spina 220 and Lanterna led no" the rest of the attributes remain unchanged and possible as a combination.

**Comment by Webgaict** [comment] 2019-10-25 09:18
Is there an order in which the system takes the available combinations? If they have been canceled

Thanks for help!

**Comment by khouloudbelguith** [comment] 2019-10-25 09:52
@Webgaict, so did you delete the combination: `con spina 220` for the attribute `Impianto illuminazione` & the combination `No` for the attributes `Lanterna`?

But, if it is deleted, why it is displayed in the FO, it should not be available the `No`   when the `con spina220` is selected? is it? this is your problem?

**Comment by Webgaict** [comment] 2019-10-25 09:55
No it is something that is good for us, the fact is that other attributes change that should not be changed if I put "spina 220V"

**Comment by khouloudbelguith** [comment] 2019-10-25 10:10
@Webgaict,

>No it is something that is good for us

But it is not the behavior by default in PrestaShop.
For example:
I have those combinations by default
![image](https://user-images.githubusercontent.com/16067358/67562617-5c886400-f71f-11e9-9821-392f36a23757.png)
In the FO, when I select Size M, the Dimension - 60x90cm s displayed
![image](https://user-images.githubusercontent.com/16067358/67563014-27304600-f720-11e9-93b8-0bdc774c06b6.png)

When I delete this combination: Size - M, Dimension - 60x90cm
In the FO, when I select Size M => The Dimension - 60x90cm should not be displayed
 
![image](https://user-images.githubusercontent.com/16067358/67563119-5fd01f80-f720-11e9-8760-8df0a953b7d2.png)

Thanks to check & feedback.

**Comment by Webgaict** [comment] 2019-10-25 10:15
In fact it is not displayed, Lanterna led no change in Lanterna led yes when I put the "spina 220v" attribute, but some attributes are changed that should not be changed.
I attach the product link so you can do tests
Try to see directly on the product what happens when you put the"spina 220v" attribute.
https://www.egvisualshop.it/it/carretti/699-134901-carretto-in-legno-per-eventi-shabby-chic.html#/25-personalizzazione-neutro/90-ruote_gommate-no/92-tettoia-in_legno/93-lanterna_led-no/127-impianto_di_illuminazione-no/130-piano_di_lavoro-vasca_isotermica_30_l/133-verniciatura-trasparente_solo_top/181-coperchio-ermetico_piatto/212-lavabo-no/214-mensola_reclinabile-no

**Comment by Webgaict** [comment] 2019-10-25 10:20
Can you tell me why the other attributes are also changed and the combination does not change only for the "led lantern from no to yes"?

**Comment by khouloudbelguith** [comment] 2019-10-25 10:43
@Webgaict, so before changing, I have this
![image](https://user-images.githubusercontent.com/16067358/67564684-cdca1600-f723-11e9-8919-fa7986c76c0d.png)
When I select the `con spina 220`
I have this
![image](https://user-images.githubusercontent.com/16067358/67564732-e4706d00-f723-11e9-8d88-39cabbe3ceb8.png)
All the attributes are well displayed.
In fact, for the attribute "Ruote gommate" => there are two values displayed
"Yes" & "No"
It is changed => because the yes is the **first** value, the Yes value is created before the"No" value
 of the value 

![image](https://user-images.githubusercontent.com/16067358/67565137-f9013500-f724-11e9-8cb1-da7695970b7f.png)

Thanks to check & feedback.

**Comment by Webgaict** [comment] 2019-10-25 10:52
@khouloudbelguith Ho modificato l'ordinamento degli attributi ma non è cambiato niente.
![mensola](https://user-images.githubusercontent.com/56969939/67565659-403bf580-f726-11e9-9d1e-37c318c9dacd.png)
![ruote](https://user-images.githubusercontent.com/56969939/67565660-40d48c00-f726-11e9-8763-bddc0f866524.png)

**Comment by Webgaict** [comment] 2019-10-25 10:52
I changed the sorting of the attributes but nothing changed. *

**Comment by khouloudbelguith** [comment] 2019-10-25 11:03
@Webgaict, yes, because the change of position doesn't work, we are aware of the issue, it is added to our bug roadmap
It is reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9836
As you can see, the id of "Si" is 213 & id of "No" is 214, so that's why Si is displayed at first.
Thanks!

**Comment by Webgaict** [comment] 2019-10-25 11:19
However I need an imminent solution how can I do?

**Comment by Webgaict** [comment] 2019-10-25 11:25
However the display in the FO has changed the value no comes out as the first but if I put the attribute with "spina 220v" the attributes "ruote gommate" and "mensola reclinabile" are changed to yes

**Comment by Webgaict** [comment] 2019-10-25 11:37
Can I change ids from the database?

**Comment by khouloudbelguith** [comment] 2019-10-25 12:27
@Webgaict, no you cannot change it from the database, you need to switch between ids which is an action very risky.
The combination by default in your case is 
`Ruote gommate => No` & `Mensola Reclinabile => No`, that's why in first it is well displayed.
But if you change the `spina 220v` & you try to change it to No again, `Ruote gommate => Yes` & `Mensola Reclinabile => Yes`.
It is normal behavior, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-25 12:27 UTC
Labels: Bug, FO, Combinations, No change required, 1.7.5.1
