### ISSUE TITLE
faceted search 3.0.6 not work properly

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#14487] opened 2019-07-04 15:11 UTC

**Comment by khouloudbelguith** [comment] 2019-07-04 15:16
Hi @photinia73,

Could you please provide us with more info? We need more details & clear description to understand how we can reproduce your issue

Thanks!

**Comment by photinia73** [comment] 2019-07-04 15:19
![image](https://user-images.githubusercontent.com/50954519/60676429-8a534f80-9e87-11e9-83f4-84db638ceaf3.png)
1. Could not index prices
2. Аnd has a strange llok in the front office
![image](https://user-images.githubusercontent.com/50954519/60676575-e918c900-9e87-11e9-8f85-a586231a7f86.png)
3. And if you select one price range it`s unpossible to select other - the slider disappeare

**Comment by photinia73** [comment] 2019-07-04 15:20
about strange look - double items of filter

**Comment by khouloudbelguith** [comment] 2019-07-04 15:36
Hi @photinia73,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.0rc1 & PS1.7.5.2 & the ps_facetedsearch v3.0.6 after upgrade from v3.0.5.
I attached a screen record
https://drive.google.com/file/d/1Rg7swa-tiSLoe2qG3nQxnyQjQbcVJoaw/view
Could you please provide us with more info:

 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by photinia73** [comment] 2019-07-04 15:46
I have only apache error log, course I roll back to previous version. I need the working module
[error_log.04Jul.2019.txt](https://github.com/PrestaShop/PrestaShop/files/3359924/error_log.04Jul.2019.txt)

**Comment by photinia73** [comment] 2019-07-04 15:49
server info
![image](https://user-images.githubusercontent.com/50954519/60678182-621a1f80-9e8c-11e9-9a98-5d07c3d317b2.png)

**Comment by khouloudbelguith** [comment] 2019-07-04 16:11
@photinia73, you have a lot of errors related to your cache
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Also, you have this error
`PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 256087 bytes) in /var/www/tefold/te.com.ua/vendor/icanboogie/cldr/lib/FileProvider.php on line 69, referer: https://te.com.ua/admin137buzkbm/index.php?controller=AdminModules&configure=ps_facetedsearch&token=9222cbf7096ab633a12d18f4f3a04895`

In your php.ini file, Try to increase:

```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```

Thanks to check & feedback

**Comment by photinia73** [comment] 2019-07-04 17:10
I put the next value in the php.ini
![image](https://user-images.githubusercontent.com/50954519/60681331-8e876900-9e97-11e9-8754-39058fa2730e.png)
But will try to update, clear cache in the next time, because PS not propose me to update it again ((

**Comment by khouloudbelguith** [comment] 2019-07-05 09:09
@photinia73, after editing your PHP file, your issue is solved?

Thanks!

**Comment by photinia73** [comment] 2019-07-05 09:29
I can`t check, because rolled back to previous version... And now can`t upgrade - PS don`t propose me upgrade again (( May be you have the URL of the module 3.0.6?

**Comment by khouloudbelguith** [comment] 2019-07-05 09:34
@photinia73, you can find the release on our GitHub repository
https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.0.6
Or, after uninstalling the ps_facetedsearch previous version, when you navigate to the BO => Module Catalog page & search for this module => the last version 3.0.6 will be displayed.

Thanks to check & feedback.

**Comment by photinia73** [comment] 2019-07-05 09:36
Ок. Now will clear the var/ dev-prod and will update

**Comment by khouloudbelguith** [comment] 2019-07-05 09:37
@photinia73, thanks!

Waiting for your feedback.

**Comment by photinia73** [comment] 2019-07-05 10:50
Still clearning.....

**Comment by khouloudbelguith** [comment] 2019-07-05 10:54
@photinia73, I'm waiting for your feedback.

**Comment by photinia73** [comment] 2019-07-05 10:58
var/cache/prod/purifier can`t delete CSS and URI have no permission.... If it nesessary to clear them, I will call the provider

**Comment by photinia73** [comment] 2019-07-05 12:10
I can`t install the module
![image](https://user-images.githubusercontent.com/50954519/60721514-e75a0e80-9f36-11e9-9a96-b483c599d628.png)
"Not the real archive file"...

**Comment by khouloudbelguith** [comment] 2019-07-05 12:17
@photinia73, you need to clone the module from the GitHub repository, launch the composer install & zip the folder.
Thanks to check this zip file & feedback.
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3362642/ps_facetedsearch.zip)

Thanks!

**Comment by photinia73** [comment] 2019-07-05 12:33
in the url you gave was only zip file and I had get only download the zip file... What you mean launch the composer, give me printscreen please

**Comment by photinia73** [comment] 2019-07-05 12:35
I want to know this for the future? thanks

**Comment by khouloudbelguith** [comment] 2019-07-05 12:38
@photinia73, cloning from the GitHub repository
![image](https://user-images.githubusercontent.com/16067358/60722931-259d0100-9f2a-11e9-988b-921414985e3a.png)

Thanks!

**Comment by photinia73** [comment] 2019-07-05 12:43
I installed. Works, BUT!
![image](https://user-images.githubusercontent.com/50954519/60723069-533e7600-9f3b-11e9-921c-562117574eea.png)
In the FO double items in the filter menu
If once select price range, you need reload the page to show the price slider again

**Comment by khouloudbelguith** [comment] 2019-07-05 12:45
@photinia73, try to force a refresh of the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks!

**Comment by photinia73** [comment] 2019-07-05 12:49
Slider not disapper. Ok. But what to do with double items in the filter Бренд Бренд, Цена Цена?

**Comment by khouloudbelguith** [comment] 2019-07-05 12:52
@photinia73, what is the exact browser did you use?

Thanks!

**Comment by photinia73** [comment] 2019-07-05 12:52
Chrome

**Comment by khouloudbelguith** [comment] 2019-07-05 12:55
@photinia73, in the BO =>  Module manager page => ps_facetedsearch configuration page => when you edit the template, you have double filter enabled?

Thanks!

**Comment by photinia73** [comment] 2019-07-05 13:04
I have only 1 filter template 
![image](https://user-images.githubusercontent.com/50954519/60724105-36577200-9f3e-11e9-84ad-72448605ea23.png)

**Comment by khouloudbelguith** [comment] 2019-07-05 13:16
@photinia73, you need to check filters in your template as described in this screen record.
https://drive.google.com/file/d/10QnHyKxGNLGbNNh9wvR3H4V6X3TtaNP9/view
Thanks!

**Comment by photinia73** [comment] 2019-07-05 13:24
I have some othe view in the template

![image](https://user-images.githubusercontent.com/50954519/60725292-60f6fa00-9f41-11e9-9b86-179ac3cffa6b.png)

**Comment by photinia73** [comment] 2019-07-05 13:25
May be reset the module and configure again?

**Comment by khouloudbelguith** [comment] 2019-07-05 13:29
@photinia73, after resetting it, try to edit your template & save.
Thanks!

**Comment by photinia73** [comment] 2019-07-05 13:47
if comment in facets.tpl 
 {*     <p class="h6 facet-title hidden-sm-down">{$facet.label}</p>    *}
so there is no double labels in filter menu, but not orderly view is still

**Comment by photinia73** [comment] 2019-07-05 13:48
row 44
![image](https://user-images.githubusercontent.com/50954519/60726637-b254b880-9f44-11e9-8829-9915c95164e6.png)

**Comment by photinia73** [comment] 2019-07-05 13:59
But I am not sure, that this is correct way....

**Comment by photinia73** [comment] 2019-07-05 14:15
And why in your video 12 points in the template, and in the mine only 10?

**Comment by photinia73** [comment] 2019-07-05 14:23
I reseted the module. But if I uncomment the row 44 the double labels appear again ((
So l leave this row commented...

**Comment by photinia73** [comment] 2019-07-05 14:28
Please ask developer to resolve this query. In the mobile version all looking nice

**Comment by khouloudbelguith** [comment] 2019-07-05 14:30
@photinia73, in my case, I did not manage to reproduce the issue with ps_facetedsearch v3.0.6.
I don't have double labels.
You can check this link: http://proud-vacation.machine-shuffle.prestashop.net/en/2-home

Thanks!

**Comment by photinia73** [comment] 2019-07-05 14:31
You have absolutely another design in your filter....

**Comment by photinia73** [comment] 2019-07-05 14:38
your filter is already opened, mine is closed (before clicking) it seems that we have different modules

**Comment by photinia73** [comment] 2019-07-05 14:40
May be uninstall the module and the install again?

**Comment by khouloudbelguith** [comment] 2019-07-05 14:42
@photinia73, your theme is overriding the ps_afecetedsearch module?

Thanks!

**Comment by photinia73** [comment] 2019-07-05 14:45
ps_facetedsearsh realy is in my theme in folder modules....

**Comment by photinia73** [comment] 2019-07-05 14:46
![image](https://user-images.githubusercontent.com/50954519/60730005-c4d2f000-9f4c-11e9-9de2-c10926598177.png)

**Comment by khouloudbelguith** [comment] 2019-07-05 14:47
@photinia73, could you please check if you have the same issue when using the theme classic.

Thanks!

**Comment by photinia73** [comment] 2019-07-05 14:49
a cant change theme to classic, after this all configuration is lost

**Comment by khouloudbelguith** [comment] 2019-07-05 14:52
@photinia73, have you tried to contact your theme author?
Thanks to check with them & feedback.

**Comment by photinia73** [comment] 2019-07-05 14:53
Ok I will try

**Comment by khouloudbelguith** [comment] 2019-07-05 14:56
@photinia73, thanks!
Waiting for your feedback.

**Comment by photinia73** [comment] 2019-07-05 14:57
usually he do nothing ((

**Comment by khouloudbelguith** [comment] 2019-07-05 15:01
@photinia73, As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by photinia73** [comment] 2019-07-05 15:03
I find there version of faceteds.tpl. will learn

**Comment by photinia73** [comment] 2019-07-05 15:03
facets.tpl

**Comment by khouloudbelguith** [comment] 2019-07-05 15:06
@photinia73, sorry what do you mean by 
>I find there version of faceteds.tpl. will learn 

Thanks!

**Comment by photinia73** [comment] 2019-07-05 15:09
in the theme->pixtronpro->template->..... there are files active-filters.tpl and facets.tpl.....

**Comment by khouloudbelguith** [comment] 2019-07-05 15:12
@photinia73, as I said before, it's not the default theme, provided by Prestashop, we can't do anything with this. 
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
I close the issue, feel free to open a new when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-07-05 15:12 UTC
Labels: Bug, Can't reproduce, Faceted search

**Comment by photinia73** [comment] 2019-07-06 09:18
Hello!
I arranged the view like in the previous version. May this isnfo will be usefull for the next clients.
1. Comment line 44 in the file views->templates->front->catalog->facets.tpl
2. In the same file raw 52 "p class="h6 facet-title">{$facet.label}  changed tag "p" on "span"
So the whole view became more accurate
This changes didn`t influences on the filter work
![image](https://user-images.githubusercontent.com/50954519/60754310-12e90180-9fe8-11e9-9458-c93e85189a8c.png)

**Comment by photinia73** [comment] 2019-07-06 09:24
All changes I try in the files of Pixtrone themes didn`t have effect. What is rewrite in theme module file concerns mobile version (it look perfect)
