### ISSUE TITLE
How can I send notification after order to different adresses.

### ISSUE THREAD

**Issue by Sybrenb** [PrestaShop/PrestaShop#27248] opened 2022-01-06 14:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like

Is it possible to change the e-mail on which the notification arrives after the order when the user chooses to pick up or delivery?

I've downloaded the mail alerts plug-in but I can only add a line of e-mails to where the notifications will send after an order, but I want the system to send an email to (for example) test@test.com when the user chooses to pickup and example@example.com when he chooses for delivery.

Is this possible?

<img width="779" alt="Mail alerts" src="https://user-images.githubusercontent.com/21313464/148397133-69f9ff35-1adb-466a-9ea4-783e75a25d13.png">

<img width="1247" alt="pickup and delivery" src="https://user-images.githubusercontent.com/21313464/148397395-10aedf94-6046-4914-8c94-83b1a2b6f5c3.png">

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment] 2022-01-06 15:00
Hello @Sybrenb 

If you're asking to add new feature in PrestaShop, then your issue is duplicate of #23745
To be informed when it's fixed, please subscribe to the issue mentioned above.

Otherwise, ifyou have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-06 15:00 UTC
Labels: Feature, Invalid
