### ISSUE TITLE
Cart Rule and Invoice change

### ISSUE THREAD

**Issue by skyliners4** [PrestaShop/PrestaShop#35287] opened 2024-02-07 10:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When creating a Cart Rule for a specific category and applying it to an order, if the category of the product is later modified, and either the carrier or the delivery address of the order is changed, the discount is removed from the invoice, the invoice total is changed causing legal issues.

### Expected behavior

The invoice should never change once created.

### Steps to reproduce

1. Create a Cart Rule for a specific category (Category A).
2. Add a product from Category A to the cart.
3. Place an order with the Cart Rule applied.
4.. Generated the invoice if is not already yet
5. Modify the category of the product from Category A to other Category witch is not compatible with the Cart Rule.
6. Change the carrier or delivery address of the order.
7. Observe that the discount is removed from the invoice.

### PrestaShop version(s) where the bug happened

1.7.8.3  8.1.3

**Comment by AureRita** [comment] 2024-02-07 15:09
Hi @skyliners4 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(98).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a38a64d9-5d8a-4b2a-9c32-908bfd79d146)

Did I miss something ? 

Waiting for your feedback

**Comment by skyliners4** [comment] 2024-02-08 07:08
Hello, thanks for your return.
I'm sorry i was mistaken. Is not for Catalog Price Rule but for the Cart Rules.
If you make the test with a cart rule, you should have the problem.

**Comment by florine2623** [comment] 2024-02-09 08:48
Hello @skyliners4 ,

I can't reproduce your issue even when using a Cart Rule.

Could you specify the Cart rule and the Carrier configuration, as well as when you change the status of your order ?

Waiting for your feedback

**Comment by skyliners4** [comment] 2024-02-09 15:53
Hello @florine2623,

I installed a clean PrestaShop 8.1.3.
I created a cart rule for the Clothes category with a 5% discount.
I placed an order for an item in the Clothes category to take advantage of the 5% discount using the default carrier "Click and collect."
At this point, my order is marked as payment accepted, and the invoice is generated correctly.
Later, I went to the product page in the BackOffice, changed the product's category, and moved it to the Art category (which is not included in the cart rule).
Returning to the order, I changed the carrier and selected the default carrier 'Click and collect.'
The product is no longer eligible for the cart rule, the discount is removed from the order, and the invoice is recalculated.

Thanks in advance.

**Comment by florine2623** [comment] 2024-02-12 09:45
Hello @skyliners4 ,

This is normal behavior, because you changed the carrier and the carrier has a different price than the carrier the customer first selected.

Then once you change the carrier, the cart rule is no longer available for the current carrier. So the order is updated automatically.

I'm closing your issue as this is normal behavior.
Thanks

**Closed as completed by florine2623** 2024-02-12 09:45 UTC
Labels: Bug, BO, Order, Catalog price rules, 8.1.x

**Comment by skyliners4** [comment] 2024-02-12 12:27
Hello @florine2623,

Yes, but the invoice amount also changes. And if the invoice has already been included in the accounts, we end up with a gap.
In addition, the customer ends up with a different invoice amount between the time he ordered and now.

Thanks
