### ISSUE TITLE
Hook actionValidateOrder is executed in wrong moment

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#21395] opened 2020-10-12 07:43 UTC
#### Describe the bug
The hook actionValidateOrder is executed before the order is placed (validated), according to the documentation it supposed to be done after the order is placed. The problem is, that if I want to use in that hook a function that has access to the orders, it prints error and finishing validating (creating) the order without any status. For example if I need to know if the newly created order is a first order of a client, it is impossible using this (or any other) hook. Method Order::getCustomerOrders() will not work in this hook. It seems that accessing orders history in this hook is impossible.

#### Expected behavior
The hook should be executed after the order is placed, so there is full access to the methods accessing orders, orders history etc.

#### Steps to Reproduce

Create module that hooks into hook hookActionValidateOrder, then in this hook try to use for example method Order::getCustomerOrders($params['order'] -> id_customer) to count if this order is the first one.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/24461669/95718689-16e5e380-0c6f-11eb-92d5-706c7089eb56.png)

#### Additional information

* PrestaShop version:  1.7.6.7

* PHP version: 7.2.18

**Comment by kpodemski** [comment] 2020-10-12 08:42
Hey,

`hookActionValidateOrder` is executed the moment you placed order, you can see implementation here:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L542

It's not possible now to change a place of this hook because of BC Break. 

Of course you're right and `OrderState::getOrderStates` will return nothing if you're using this this method and it needs to be checked to prevent this Notice, but for your scenario you could use a bit different approach.

Let me know what you need to do and maybe I'll guide you for some workaround.

**Comment by khouloudbelguith** [comment] 2020-10-12 11:22
Hi @grzegorzgit,

I manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/95741017-cf228480-0c8d-11eb-9392-ee1582407c16.png)
I tried with this module https://addons.prestashop.com/en/collection-points-in-store-pick-up/1752-mondial-relay-official.html
I edited this
```php
 public function hookActionValidateOrder($params)
    {
        $cart = $params['cart'];
        $order = $params['order'];
Order::getCustomerOrders($params['order'] -> id_customer);
```
But, wit PS177x => ok no exception displayed.
Could you please check with PS1770beta1 is ok in your case and feedback.

Thanks!

**Comment by grzegorzgit** [comment] 2020-10-12 11:52
Thanks @kpodemski and @khouloudbelguith 
I have found a workaround solution to access database directly, for those who can also face the issue:
```
        $orders_count = 0;
        $id_customer = $params['order']->id_customer;
        if ($count = Db::getInstance()->executeS('SELECT `id_order` FROM `' . _DB_PREFIX_ . 'orders` WHERE `id_customer` = \''.$id_customer.'\'')) {
            $orders_count = count($count);
        }
```

I wasn't aware there's newer version of PrestaShop, I will try to update and post the answer here later.

But as an additional info I'd like to add, that if you create such exception in this hook, the order will be "invalid" and customer will see it in "my account -> orders history" cause the order history will not work any more, unless you change manually status of this order in back office.

**Comment by khouloudbelguith** [comment] 2020-10-12 11:55
@grzegorzgit, 

>I wasn't aware there's newer version of PrestaShop, I will try to update and post the answer here later.

It is a beta version, thanks to check it and feedback.

>cause the order history will not work any more

Yes, I manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/95743722-7d302d80-0c92-11eb-97ac-32669bfafacf.png)

But it is ok with 177x branch
![image](https://user-images.githubusercontent.com/16067358/95743793-9638de80-0c92-11eb-9063-8de4a77c0954.png)

Thanks to check it.

**Comment by hibatallahAouadni** [comment] 2020-11-02 10:30
Hello @grzegorzgit,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-02 10:30 UTC
Labels: Bug, CO, No change required, 1.7.6.8
