### ISSUE TITLE
module pages not found

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#14509] opened 2019-07-05 18:21 UTC
Prestashop 1.7.5.2
Module pages not found ver. 2.0 doesn't works for me: no pages are recorded.

**Comment by khouloudbelguith** [comment] 2019-07-08 07:47
Hi @centoasa,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by centoasa** [comment] 2019-07-08 14:55
apache php 7.2.20
10.1.40-MariaDB-0ubuntu0.18.04.1
my htaccess have (as default):
#If rewrite mod isn't enabled
ErrorDocument 404 /index.php?controller=404
many customers doesn't found products, so prestashop show a 404 page, but...
https://nimb.ws/A0UOWn
doesn't record any page!

**Comment by khouloudbelguith** [comment] 2019-07-08 15:02
@centoasa, we are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9656
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-07-08 15:02
Duplicate of #9656

**Closed as completed by khouloudbelguith** 2019-07-08 15:02 UTC
Labels: Bug, BO, Duplicate, Modules, 1.7.5.2
