### ISSUE TITLE
Re-open report #36611

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#36616] opened 2024-07-25 16:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The report wasn't correctly reproduced.

I attached evidence that you can in fact create a address with a wrong state.

https://github.com/PrestaShop/PrestaShop/issues/36611

### Expected behavior

Check https://github.com/PrestaShop/PrestaShop/issues/36611

### Steps to reproduce

https://github.com/PrestaShop/PrestaShop/issues/36611

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment] 2024-08-07 08:29
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #36611.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment] 2024-08-07 08:30
Duplicate of #36611

**Closed as completed by paulnoelcholot** 2024-08-07 08:29 UTC
Labels: Bug, Duplicate
