### ISSUE TITLE
Cannot remove product restrictions from Cart Rule

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#18560] opened 2020-04-10 07:19 UTC
#### Describe the bug

when I want to remove the product restriction from a Cart Rule the system don't accept it, it saves but when I come back instead of the product being gone, the same product is listed twice
![image](https://user-images.githubusercontent.com/3520123/78971397-c2b94580-7b0b-11ea-80ed-0be5151fbc2d.png)

#### Expected behavior

Remove the product restriction should result in exactly that.

#### Steps to Reproduce

1. Go to cart rules
2. Create a cart rule which only works for a specific product. Save
3. Go back to the rule and try to remove the product restricting by ticking the box product selection
4. Save and go back to the rule

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.1

**Comment by florine2623** [comment] 2020-04-10 08:42
Hi @sickboards ,
I couldn't reproduce your issue on PS 1.7.5.2 nor 1.7.6.4.
Here are a few things you can try : 
- Do the same steps with debug mode on
- Clear cache manually and from BO
- Check if you have a module that has an incidence on cart rules

Also, have you done a migration ? If yes which tool did you use ?

Please check ans let me know ! Thanks !

**Comment by sarahdib** [comment] 2020-05-05 16:03
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 16:03 UTC
Labels: BO, Cart rules, No change required, 1.7.5.2
