### ISSUE TITLE
Google Maps is not free anymore - need to be replaced in order pages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10393] opened 2018-09-12 08:15 UTC
Hi

**Describe the bug**
now google maps does not work (you can see it from the order pages), I think it is due because google has changed its strategy
I suggest you to use MapQuest, it is very nice and has a free plan
https://www.mapquest.com/

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/45411378-5d257e80-b674-11e8-84b4-35626720d3d4.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by MathiasReker** [comment] 2018-09-12 08:25
You need to add an API key.

**Comment by Maofree** [comment] 2018-09-12 08:29
I know but now the free plan can load only one time
so it is necessary an alternative

**Comment by MathiasReker** [comment] 2018-09-12 08:34
Can you link to the documentation of that?

**Comment by Maofree** [comment] 2018-09-12 08:37
about mapquest or google maps that now load a map only one time for a day?

**Comment by Maofree** [comment] 2018-09-12 08:39
![1](https://user-images.githubusercontent.com/653230/45412900-294c5800-b678-11e8-83c9-abdd17ef9f17.png)

**Comment by MathiasReker** [comment] 2018-09-12 08:48
You need a google API key: https://developers.google.com/maps/documentation/javascript/get-api-key

I have a website in production on free plan. I load they map hundreds of times per day.

**Comment by Maofree** [comment] 2018-09-12 08:50
read better
I've some api key but created some time ago with unlimited loads, but now from 11 june it is no more possible
try to create a new  Maps JavaScript API

**Comment by Maofree** [comment] 2018-09-12 08:52
https://stackoverflow.com/questions/51688148/google-maps-javascript-api-quota-is-set-to-1
Looks like you need to have billing enabled on the account now, tried with 2 gsuites account, limit is 1 without billing account attached and unlimited with billing account attached.

**Comment by MathiasReker** [comment] 2018-09-12 08:59
You are right: https://developers.google.com/maps/documentation/javascript/usage-and-billing

**Comment by Maofree** [comment] 2018-09-12 09:01
I won :)

**Comment by khouloudbelguith** [comment] 2018-09-12 09:30
Hi @maofree,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2
We will see how to fix it.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-13 07:36
Hi @maofree,

The issue is fixed, thanks to check and feedback.
![image](https://user-images.githubusercontent.com/16067358/45476846-55331080-b740-11e8-9407-04c655f413c2.png)

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-09-14 06:03
hi
can you show me how to fix it?

**Comment by khouloudbelguith** [comment] 2018-09-14 08:03
Hi @maofree,

Is not fixed for you?

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-09-14 08:04
yes
looking in a site now the google maps is without that alert

**Comment by khouloudbelguith** [comment] 2018-09-14 08:08
Hi @maofree,

Thanks!
I close the ticket, feel free to open a new one when needed.

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-09-25 08:01
Hi
today I see again this alert on the order pages

**Comment by khouloudbelguith** [comment] 2018-09-25 08:15
Hi @maofree,

Yes, you are right.
is back again.

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-10-03 18:06
Hi @khouloudbelguith
I continue to get this problem on the google api
on the 1.6.x using a google api a fix the problem, I set it in the preferences page
but on the 1.7.x where is the field to set it?

thanks

**Comment by khouloudbelguith** [comment] 2018-10-04 09:42
Hi @maofree,

We are aware of this issue, it is added to our debug roadmap.
Google map API missing in BO in the PS1.7.
Please follow: #9797
Thanks!

**Comment by Klemart3D** [comment] 2018-10-12 10:21
Reproduced on fresh install of last v1.7.5.0

![gmap-error](https://user-images.githubusercontent.com/7419525/46863885-ef0ddc00-ce18-11e8-89c2-abafecf5164d.png)

**Comment by khouloudbelguith** [comment] 2018-10-12 10:23
Hi @Klemart3D,

Sorry, but the issue is not fixed yet.
Thanks for your understanding!

**Comment by khouloudbelguith** [comment] 2019-01-24 11:57
Hi, we have an error in the console
![image](https://user-images.githubusercontent.com/16067358/51676654-96350e80-1fd7-11e9-840a-31cb82500323.png)
Thanks!

**Comment by tzak902** [comment] 2019-01-24 12:16
No body showed how to add a key, which file?

**Comment by matks** [comment] 2019-04-14 19:12
I have been searching for a while now and I'm afraid I've got bad news. I was looking for a replacement for Google Geocoding API, which would be "good enough" and - most importantly - could be used without a API Key. I could not find one.

I could find a great number of geocoding services with a free plan but that required a signup to work. This cannot work if we want to ship the feature like this because it would mean prestashop signs up for such a plan and requests are being made by the possible 270,000 shops we have in the world 😄the Free plan would vanish soon. This is a no-go.

I found some alternatives, but they cannot compete with Google Maps :( for example MapQuest, suggested by @maofree, seems to work quite good in the US but not in Europe. I did some geocoding requests, results were poor.

I think we will not find a suitable replacement for Google Geocoding Service. What we can do is enable people to input their own Google Maps API Key and be billed for the requests or remove the map (because as colinegin said, I'm not sure whether this is very useful 🤔, but I'd like to hear some feedback about that).

**Comment by marionf** [comment] 2019-06-26 10:10
Hello @maofree 
Could you tell us in which case you use the map ? Why a merchant need to see the location of his customer ?
Could it be ok for you if we add a link that display the address in google map in a new tab ?

**Comment by matks** [comment] 2019-08-20 09:35
Update: MapBox is getting traction
https://www.mapbox.com/

**Comment by colinegin** [comment] 2019-11-25 16:22
@MatShir is it still relevant with the new design ?

**Comment by MatShir** [comment] 2019-11-25 16:24
@colinegin 
The alternative option wasn't really satisfying, so It is not shipped for the next version.

**Comment by Betafer** [comment] 2020-03-13 14:20
Prestashop 1.7.6.3 in BO order got this error, i think is related to this post

2js?v=3.exp:55 Geocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key
_.kd @ js?v=3.exp:55
util.js:231 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
oz.o @ util.js:231
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map

**Comment by Hlavtox** [comment] 2020-05-07 10:17
@matks If a map will still be present in 1.7.7, what about OpenStreetMap? https://wiki.openstreetmap.org/wiki/API_v0.6

BTW: Is anybody actually using this? 😄 At least in our case, nobody gives a 💩 where the customers lives. Just invoice, change status, export shipping label, finished.

**Comment by Betafer** [comment] 2020-05-07 10:22
> @matks If a map will still be present in 1.7.7, what about OpenStreetMap? https://wiki.openstreetmap.org/wiki/API_v0.6
> 
> BTW: Is anybody actually using this? 😄 At least in our case, nobody gives a 💩 where the customers lives. Just invoice, change status, export shipping label, finished.

Right, and if you really want to put the function, it must work properly, otherwise remove it.

**Comment by matks** [comment] 2020-05-07 12:09
> @matks If a map will still be present in 1.7.7, what about OpenStreetMap? https://wiki.openstreetmap.org/wiki/API_v0.6

A long time ago I tried to find a replacement for Google Geocoding API, which would be "good enough" and - most importantly - could be used without a API Key. I could not find one at that time. I don't remember if I looked at OpenStreetMap.

For being a suitable replacement we need something:
- that works with accuracy in all countries (for example I could find a service that was good for US adresses but bad for Europe adresses)
- that works without an API key (so even if you can signup for free, it's not usable because we cannot create a PrestaShop account and have 300,000 shops our own API key) or any other authenticated system

If I'm not wrong, we have removed it in reworked Order page (coming for 1.7.7). As it's very easy to create a module to provide the feature and plug it inside Order page, I think indeed we dont need this in the Core.

**Comment by colinegin** [comment] 2020-05-07 15:45
Is it something that is actually useful for you ? In which situations do you need this feature ?

**Comment by Gipielle** [comment] 2020-05-29 07:13
Bug still present in prestashop 1.7.6.5

**Comment by matks** [comment] 2020-05-29 07:25
> Bug still present in prestashop 1.7.6.5

It's fixed in incoming version 1.7.7 because we removed the map 😄 

After checking thoroughly we could not find a good alternative to Google Maps. Moreover as @colinegin we are not sure this is widely used. Some people might find it useful if they deliver locally but then modules can easily hook themselves into one of the Order page hook to put this, and it solves the issue about the API key.

**Comment by Gipielle** [comment] 2020-05-29 07:30
How can i remove the map in prestashop 1.7.6 ?

**Comment by matks** [comment] 2020-05-29 07:39
Just delete the related code I think 🤔 is it harming your shop ?

**Comment by M-t-t-h** [comment] 2020-10-30 12:15
Hi everyone,
I get this problem on 1.7.6.7, and find **the** line on _AdminOrdersController.php_ (the 344) is :
 $this->addJS('https://maps.googleapis.com/maps/api/js?v=3.exp');
There is no place for get the api_key to send with GET method.

A proposition for 1.7.7:
if apikey exist => this->addJS('https://maps.googleapis.com/maps/api/js?v=3.exp&key=$VAR);
else, no add map...

**Comment by matks** [comment] 2020-10-30 13:32
Hi, in 1.7.7 Google maps has been removed because there was no relevant way to include it with the new rules of Google Maps. Modules can easily hook themselves into one of the Order page hook to put it back if needed.

1.7.6 is still using old GoogleMaps system so indeed it's not compliant with their rules anymore :/ but 1.7.6 will soon be EOL

**Closed as completed by matks** 2020-10-30 13:32 UTC
Labels: Bug, BO, Order, Fixed, 1.7.4.2, 1.7.6.0
