### ISSUE TITLE
1-click upgrade not possible when using Redis as PHP session backend

### ISSUE THREAD

**Issue by JanMiddelkoop** [PrestaShop/PrestaShop#30931] opened 2023-01-18 14:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since the latest version of the autoupgrade (1-click upgrade) module, there is an issue with the module (falsely) reporting it cannot open a PHP session, if you use Redis as a session backend.

The autoupgrade module runs the "ConfigurationTest::test_sessions" check. This function tests if the PHP session.save_path directory is writable. By default, session.save_path is set to "/var/lib/php/session/" and this path needs to be writable. So in that case the check works and produces valid results.

However, when you use Redis as a session backend (which is a good idea for performance), your PHP session.save_path is likely set to something like "tcp://127.0.0.1:6379/?prefix=prestashop". The is_writable() check is not suitable for this case, so the check fails and produces incorrect results.

Presumably the same would happen when using Memcached as session backend, or any other backend than the default (file-based) sessions.

### Expected behavior

I'd expect the session check during the 1-click upgrade to not fail when I have enabled a working session backend in the PHP configuration. One could argue if this check is even necessary, as I need to be logged in to the admin backend in order to do the upgrade to begin with, which is not possible without an active PHP session. So I'd probably even expect the 1-click upgrade module to not test PHP sessions.

Either way, the ConfigurationTest::test_sessions() function should account for other session backends. Easiest test would probably be to actually start a session and see if it fails.

### Steps to reproduce

1. Have PrestaShop installed and then configure Redis as a PHP session backend
2. Update the 1-click upgrade module to the latest version
3. Try to run a 1-click upgrade and see the PHP session test fail

### PrestaShop version(s) where the bug happened

1.7.8.7 and 8.0.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-Click upgrade 4.15.0

**Comment by JanMiddelkoop** [comment] 2023-01-18 14:42
I suspect some reports in issue #30658 might be caused by this problem, though the original issue seems to have a different cause. Which is why I opened a seperate, clean report.

**Comment by Hlavtox** [comment] 2023-01-18 15:51
Hi @JanMiddelkoop, yeah it has a common cause, that check needs to be improved in the core and removed from the module, so older cores can be upgraded. Ping @atomiix

**Comment by HanaRebaiQA** [comment] 2023-01-19 09:02
Hello @JanMiddelkoop 

Thanks for your report!
Could you please provide us a screenshot or a screen-record to can see exactly the problem? 
So, if I understand well, the issue is related to this one #30658 ? and it will be fixed when the original issue will be fixed?

**Comment by JanMiddelkoop** [comment] 2023-01-19 09:37
Hi @HanaRebaiQA.

Here is your screenshot. This is the problem visualised. Issue #30658 seems to be a different problem (I'm not using cPanel), however, some of the people reporting problems there are probably experiencing this issue instead.

![prestashop-1clickupgrade](https://user-images.githubusercontent.com/2273262/213406317-7f7dd6c6-570a-405d-89dc-01d1a06a1751.png)

I've included all details the developers should need in the first post. Short of writing a patch, there's not much else I can do. A screen record shouldn't help a developer to understand this issue better.

**Comment by HanaRebaiQA** [comment] 2023-01-19 11:05
Hello @JanMiddelkoop 

Thanks for your feedback.
It's the same issue mentioned here #30658 even without using cPanel. They are duplicated.

So, I'll close this one, and do not hesitate to subscribe to the other issue.

**Comment by HanaRebaiQA** [comment] 2023-01-19 11:05
Duplicate of #30658

**Closed as completed by HanaRebaiQA** 2023-01-19 11:05 UTC
Labels: Bug, BO, Duplicate, Autoupgrade, php, Invalid, Module, 1.7.8.7

**Comment by JanMiddelkoop** [comment] 2023-01-19 22:55
The symptoms are the same, but the cause is different. That issue discusses a PHP configuration where the session.save_path is a valid path yet not writable by PHP directly. This is about a PHP configuration where session.save_path is not actually a valid path at all, because a different session backend is used.

There is a chance that fixing that issue will also remedy this one, if the entire check is removed - short of that, this issue isn't going to go away. If the check isn't improved to take other session backends into account, then this issue isn't going to go away.
