### ISSUE TITLE
Faceted search doesn't work on mobile version

### ISSUE THREAD

**Issue by AlexHDsup** [PrestaShop/PrestaShop#31526] opened 2023-02-24 10:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Faceted module doesn't work on mobile version
It,s active, but on filters tab when you press it it is appearing an blank box

www.hdsupraveghere.ro

### Expected behavior

I expected to work

### Steps to reproduce

1. go on hdsupraveghere.ro on your phone
2. press on any product category
3. try "filtrare" on the bottom
4. The feauters is not appearing 

### PrestaShop version(s) where the bug happened

1.7.8

### If your bug is related to a module, specify its name and its version

Faceted  search module

**Comment by Hlavtox** [comment] 2023-02-24 12:24
Hi @AlexHDsup, this is a problem in your template. It works properly on classic or hummingbird themes.

**Comment by hibatallahAouadni** [comment] 2023-02-24 15:22
Hello @AlexHDsup 

Indeed the issue is related to your custom theme as @Hlavtox mentioned above.
Closing the issue as it's not Core bug.

PS: thanks @Hlavtox for your quick replies 💪 

Thanks!

**Closed as completed by hibatallahAouadni** 2023-02-24 15:22 UTC
Labels: Bug, Invalid
