### ISSUE TITLE
Stock page product name wrong when copied

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#14454] opened 2019-07-02 12:02 UTC
The list of products in the "stock" page uses the wrong name when the product is copied.

**To Reproduce**
1. Create a product A and save, then click duplicate
2. the product is named "copy of product A" : rename "Product B", enable and click on duplicate
3. same for "product C" until you're done, click on "go to catalog" : you can see the correct list (product A, B, C, etc..)
4. Go to "stocks" page : the names of the products use the "copy of Product A" instead of real name.

**Screenshots below (product page, stock page)**

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2
<img width="862" alt="Capture d’écran 2019-07-02 à 13 55 59" src="https://user-images.githubusercontent.com/32092528/60511331-f724e900-9cd1-11e9-9a1c-f560c55d5f0f.png">
<img width="1428" alt="Capture d’écran 2019-07-02 à 13 56 21" src="https://user-images.githubusercontent.com/32092528/60511332-f724e900-9cd1-11e9-8793-9c8e0b9d4d1e.png">

**Comment by khouloudbelguith** [comment] 2019-07-02 12:51
Hi @elmanu13,

I did not manage to reproduce the issue with PS1.7.6.0rc1 & PS1.7.5.2.
https://drive.google.com/file/d/10UVA6nxPa4qqVKw98RsWxdmtEWGTiie6/view
Did you use multilanguage?
Did you edit the product's name with the same language as the employee?
![image](https://user-images.githubusercontent.com/16067358/60513898-34887700-9cd0-11e9-864e-9f8e9f7aefc1.png)

Thanks!

**Comment by elmanu13** [comment] 2019-07-02 14:01
Hello,
Only one language configured : french
But one important stuff I didn't tell : it's a dematerialized product, not a classic or a pack

**Comment by khouloudbelguith** [comment] 2019-07-02 15:36
@elmanu13, thanks for your feedback.
I tried with a virtual product & it is OK.
https://drive.google.com/file/d/1u1wENxnfeDhB6StZvWk81dLqgrYlv5nN/view
Thanks!

**Comment by elmanu13** [comment] 2019-07-03 16:50
Can you have a try by using the "duplicate" button on the product page ?
https://drive.google.com/file/d/1zh9gKTKyAskm6TCj-JPhvluOeDzNj6HL/view

**Comment by khouloudbelguith** [comment] 2019-07-04 09:41
@elmanu13, it is OK.
https://drive.google.com/file/d/1GVq5kbK3OqhqHxcb47LIjpMYUrSRd_x9/view
I tried with one language => French => but I did not manage to reproduce the issue as you can see in my screen record.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-02 07:35
Hi @elmanu13,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-02 07:35 UTC
Labels: BO, Stocks, No change required, 1.7.5.1

**Comment by elmanu13** [comment] 2019-08-02 08:24
Hi @khouloudbelguith ,

It's still active in my side, but maybe linked to the multistore creation. I'll dig further when I'll have more time, thanks !
