### ISSUE TITLE
Reserved stock issue 

### ISSUE THREAD

**Issue by ibrahimfsasmaz** [PrestaShop/PrestaShop#22756] opened 2021-01-09 18:43 UTC
Hello,
#### Describe the bug
There are much more higher amount reserved product than real pre-orders amount.
Some of the actions  (I am not sure which one) takes the ordered item to "reserved" situation.

For example what I realized is that when you change an order status from "shipped" to "refunded" the item has added to "available" stock but at the same time to "reserved" stock. 
There is a logical problem here, if we refund the customer and take back the product to available stock why it is also added to reserved stock.

#### Expected behavior
My solution for that "refund status stock error" was to change the statuses like below;
shipped > refunded (added to stock+reserved) > cancelled (decreases from stock)

Anyway I am not sure which other action is taking the products to the reserved stock but we have hundreds of reserved items,  which is much more higher than real preorders.

It is like the sticked as reserved 
How can I fix that pls

#### Steps to reproduce

Create an order

1. **BO**>**Orders**>**Orders**
2. Edit the last order
3. Change its status to **shipped**
4. Then change its status to **refunded**
5. **BO**>**Catalog**>**Stocks**
6. ....

#### Additional infos
* PrestaShop version: 1.7.6.5
* PHP version:

**Comment by ibrahimfsasmaz** [comment] 2021-01-09 19:09
or maybe the abandoned charts stay at reserved stock ?

**Comment by hibatallahAouadni** [comment] 2021-01-11 09:09
Hello @ibrahimfsasmaz 

Please **follow the template to submit a complete bug report** and fill the blocks that we provided in the template (describe the bug, expected behavior, steps to reproduce, php version).

Please edit your issue :wink: 

Thanks!

**Comment by Hlavtox** [comment] 2021-01-11 11:30
@ibrahimfsasmaz Check your order statuses and their settings. Check if all statuses that orders end up with are set to "Consider order finished".

**Comment by ibrahimfsasmaz** [comment] 2021-01-16 22:11
> @ibrahimfsasmaz Check your order statuses and their settings. Check if all statuses that orders end up with are set to "Consider order finished".

there nothing like "Consider order finished"

**Comment by ibrahimfsasmaz** [comment] 2021-01-16 22:12
> Hello @ibrahimfsasmaz
> 
> Please **follow the template to submit a complete bug report** and fill the blocks that we provided in the template (describe the bug, expected behavior, steps to reproduce, php version).
> 
> Please edit your issue 😉
> 
> Thanks!

where can I create the bug report pls

**Comment by hibatallahAouadni** [comment] 2021-01-17 11:06
hello @ibrahimfsasmaz 

> where can I create the bug report pls

Just right here :wink: 
Edit your issue description and add these blocks:

- describe the bug
- expected behavior
- steps to reproduce
- php version

Then submit :tada: 

Thanks!

**Comment by ibrahimfsasmaz** [comment] 2021-01-18 20:04
> hello @ibrahimfsasmaz
> 
> > where can I create the bug report pls
> 
> Just right here 😉
> Edit your issue description and add these blocks:
> 
> * describe the bug
> * expected behavior
> * steps to reproduce
> * php version
> 
> Then submit 🎉
> 
> Thanks!



But I already explained above 



> Hello,
> 
> There are much more higher amount reserved product than real preorders amount.
> 
> Some of the actions (I am not sure which one) takes the ordered item to "reserved" situation.
> 
> For example what I realized is that when you change an order status from "shipped" to "refunded" the item has added to "available" stock but at the same time to "reserved" stock.
> There is a logical problem here, if we refund the customer and take back the product to available stock why it is also added to reserved stock.
> 
> My solution for that "refund status stock error" was to change the statuses like below;
> shipped > refunded (added to stock+reserved) > cancelled (decreases from stock)
> 
> Anyway I am not sure which other action is taking the products to the reserved stock but we have hundreds of reserved items, which is much more higher than real preorders.
> 
> It is like the sticked as reserved
> 
> How can I fix that pls
> 
> * PrestaShop version: 1.7.6.5

**Comment by Hlavtox** [comment] 2021-01-19 09:09
@ibrahimfsasmaz 

StockManager says this:
Put order product to reservations if order **is not shipped** AND **(is valid OR (not error AND not cancelled))**.

When you go to your order state settings and you open some order state, the third checkbox from bottom should say _something like_ "Consider this order shipped". Make sure this checkbox is set for all the states you use as the FINAL states. (Delivered, Shipped, Picked up etc.)

Link:
https://github.com/PrestaShop/PrestaShop/blob/287959a7ea6d3b68ff93d150195008a475490bff/src/Adapter/StockManager.php#L144

**Comment by hibatallahAouadni** [comment] 2021-01-19 09:44
Thanks @Hlavtox for help :superhero: 

@ibrahimfsasmaz I need clear steps to reproduce the issue :wink: 
So, could you please check your issue description cause I just edit it and complete the steps to reproduce.

Thanks in advance.

**Comment by ibrahimfsasmaz** [comment] 2021-01-26 23:26
> Thanks @Hlavtox for help 🦸
> 
> @ibrahimfsasmaz I need clear steps to reproduce the issue 😉
> So, could you please check your issue description cause I just edit it and complete the steps to reproduce.
> 
> Thanks in advance.

I do not know which causes the bug so how can I reproduce I have no idea..
Strangely something is increasing the number of reserved stocks but I do not know what

**Comment by ibrahimfsasmaz** [comment] 2021-01-26 23:27
> @ibrahimfsasmaz
> 
> StockManager says this:
> Put order product to reservations if order **is not shipped** AND **(is valid OR (not error AND not cancelled))**.
> 
> When you go to your order state settings and you open some order state, the third checkbox from bottom should say _something like_ "Consider this order shipped". Make sure this checkbox is set for all the states you use as the FINAL states. (Delivered, Shipped, Picked up etc.)
> 
> Link:
> 
> https://github.com/PrestaShop/PrestaShop/blob/287959a7ea6d3b68ff93d150195008a475490bff/src/Adapter/StockManager.php#L144

these are all correct

**Comment by Hlavtox** [comment] 2021-01-27 08:27
@ibrahimfsasmaz 
1. Go to your stocks page and find some problematic product.
2. Go to your PHPmyadmin or Adminer or DB tool in PS admin and run this query. Replace XXXXX by id of product that is problematic.
```
SELECT od.id_order_detail, od.id_order, os.shipped, o.valid, o.current_state  FROM ps_order_detail od
LEFT JOIN ps_orders o ON o.id_order = od.id_order
LEFT JOIN ps_order_state os ON os.id_order_state = o.current_state
WHERE product_id=XXXXX;
```
3. Send me a screenshot of that query.

**Comment by hibatallahAouadni** [comment] 2021-02-01 13:08
Hello @ibrahimfsasmaz 

Could you please check my [comment](https://github.com/PrestaShop/PrestaShop/issues/23013#issuecomment-770843719) in this issue #23013

Thanks!

**Comment by ibrahimfsasmaz** [comment] 2021-02-03 21:27
> @ibrahimfsasmaz
> 
> 1. Go to your stocks page and find some problematic product.
> 2. Go to your PHPmyadmin or Adminer or DB tool in PS admin and run this query. Replace XXXXX by id of product that is problematic.
> 
> ```
> SELECT od.id_order_detail, od.id_order, os.shipped, o.valid, o.current_state  FROM ps_order_detail od
> LEFT JOIN ps_orders o ON o.id_order = od.id_order
> LEFT JOIN ps_order_state os ON os.id_order_state = o.current_state
> WHERE product_id=XXXXX;
> ```
> 
> 1. Send me a screenshot of that query.

hi this is what I get 


id_order_detail | id_order | shipped | valid | current_state
-- | -- | -- | -- | --
16394 | 13976 | 1 | 1 | 4
16404 | 13986 | 1 | 1 | 4
16463 | 14036 | 0 | 0 | 6
16670 | 14206 | 1 | 1 | 4
16724 | 14256 | 0 | 0 | 6
16729 | 14260 | 0 | 0 | 6
16965 | 14448 | 1 | 1 | 4
17199 | 14637 | 1 | 1 | 4
17308 | 14729 | 1 | 1 | 4
17350 | 14763 | 1 | 1 | 4
17381 | 14787 | 1 | 1 | 4
17455 | 14845 | 1 | 1 | 4

**Comment by Hlavtox** [comment] 2021-02-04 08:08
@ibrahimfsasmaz Your product is reserved in orders below. All the orders have some custom status with ID 16 set. Check the settings of this order status, this problem does not happen in default prestashop. I think you can solve this problem by opening settings of that order status and checking "Set the order as shipped.".

Ping @hibatallahAouadni :-)

id_order_detail | id_order | shipped | valid | current_state | Reserved
-- | -- | -- | -- | -- | --
24187 | 20403 | 0 | 1 | 16 | Yes
24404 | 20593 | 0 | 1 | 16 | Yes
24411 | 20600 | 0 | 1 | 16 | Yes
24478 | 20660 | 0 | 1 | 16 | Yes
24560 | 20733 | 0 | 1 | 16 | Yes
24573 | 20746 | 0 | 1 | 16 | Yes
24577 | 20750 | 0 | 1 | 16 | Yes
24600 | 20770 | 0 | 1 | 16 | Yes
24657 | 20824 | 0 | 1 | 16 | Yes
24721 | 20883 | 0 | 1 | 16 | Yes
24742 | 20903 | 0 | 1 | 16 | Yes
24790 | 20945 | 0 | 1 | 16 | Yes
24834 | 20977 | 0 | 1 | 16 | Yes
24999 | 21117 | 0 | 1 | 16 | Yes
25050 | 21161 | 0 | 1 | 16 | Yes
25227 | 21327 | 0 | 1 | 16 | Yes
25273 | 21364 | 0 | 1 | 16 | Yes
25363 | 21441 | 0 | 1 | 16 | Yes
25441 | 21512 | 0 | 1 | 16 | Yes
25449 | 21520 | 0 | 1 | 16 | Yes
24258 | 20468 | 0 | 1 | 16 | Yes
24265 | 20474 | 0 | 1 | 16 | Yes
24398 | 20587 | 0 | 1 | 16 | Yes
24441 | 20627 | 0 | 1 | 16 | Yes
24582 | 20755 | 0 | 1 | 16 | Yes
24693 | 20857 | 0 | 1 | 16 | Yes
24765 | 20925 | 0 | 1 | 16 | Yes
24810 | 20964 | 0 | 1 | 16 | Yes
24986 | 21105 | 0 | 1 | 16 | Yes
25001 | 21119 | 0 | 1 | 16 | Yes
25014 | 21129 | 0 | 1 | 16 | Yes
25024 | 21136 | 0 | 1 | 16 | Yes
25063 | 21174 | 0 | 1 | 16 | Yes
25091 | 21201 | 0 | 1 | 16 | Yes
25121 | 21228 | 0 | 1 | 16 | Yes
25133 | 21239 | 0 | 1 | 16 | Yes
25167 | 21271 | 0 | 1 | 16 | Yes
25178 | 21279 | 0 | 1 | 16 | Yes
25206 | 21306 | 0 | 1 | 16 | Yes
25285 | 21375 | 0 | 1 | 16 | Yes
25324 | 21407 | 0 | 1 | 16 | Yes
25403 | 21478 | 0 | 1 | 16 | Yes
25642 | 21696 | 0 | 1 | 16 | Yes
24260 | 20470 | 0 | 1 | 16 | Yes
24307 | 20507 | 0 | 1 | 16 | Yes
24390 | 20579 | 0 | 1 | 16 | Yes
24511 | 20687 | 0 | 1 | 16 | Yes
24539 | 20714 | 0 | 1 | 16 | Yes
24579 | 20752 | 0 | 1 | 16 | Yes
24639 | 20806 | 0 | 1 | 16 | Yes
24671 | 20837 | 0 | 1 | 16 | Yes
24694 | 20858 | 0 | 1 | 16 | Yes
25009 | 21126 | 0 | 1 | 16 | Yes
25086 | 21196 | 0 | 1 | 16 | Yes
25272 | 21363 | 0 | 1 | 16 | Yes
25599 | 21661 | 0 | 1 | 16 | Yes
25635 | 21691 | 0 | 1 | 16 | Yes
24276 | 20480 | 0 | 1 | 16 | Yes
24320 | 20516 | 0 | 1 | 16 | Yes
24453 | 20637 | 0 | 1 | 16 | Yes
24516 | 20692 | 0 | 1 | 16 | Yes
24666 | 20832 | 0 | 1 | 16 | Yes
24691 | 20855 | 0 | 1 | 16 | Yes

**Comment by hibatallahAouadni** [comment] 2021-02-04 09:09
@ibrahimfsasmaz please next time do not paste your table/code (if it's extremely long) in comment, just put it in .txt file and attach it to your comment :wink: 
And could you please check this issue #23013 cause it seems similar to your 

@Hlavtox Thanks for helping :superhero_man: 

_PS: I just edit your comment cause it was extremely long_

**Comment by ibrahimfsasmaz** [comment] 2021-02-06 20:40
> @ibrahimfsasmaz Your product is reserved in orders below. All the orders have some custom status with ID 16 set. Check the settings of this order status, this problem does not happen in default prestashop. I think you can solve this problem by opening settings of that order status and checking "Set the order as shipped.".
> 
> Ping @hibatallahAouadni :-)
> 
> id_order_detail	id_order	shipped	valid	current_state	Reserved
> 24187	20403	0	1	16	Yes
> 24404	20593	0	1	16	Yes
> 24411	20600	0	1	16	Yes
> 24478	20660	0	1	16	Yes
> 24560	20733	0	1	16	Yes
> 24573	20746	0	1	16	Yes
> 24577	20750	0	1	16	Yes
> 24600	20770	0	1	16	Yes
> 24657	20824	0	1	16	Yes
> 24721	20883	0	1	16	Yes
> 24742	20903	0	1	16	Yes
> 24790	20945	0	1	16	Yes
> 24834	20977	0	1	16	Yes
> 24999	21117	0	1	16	Yes
> 25050	21161	0	1	16	Yes
> 25227	21327	0	1	16	Yes
> 25273	21364	0	1	16	Yes
> 25363	21441	0	1	16	Yes
> 25441	21512	0	1	16	Yes
> 25449	21520	0	1	16	Yes
> 24258	20468	0	1	16	Yes
> 24265	20474	0	1	16	Yes
> 24398	20587	0	1	16	Yes
> 24441	20627	0	1	16	Yes
> 24582	20755	0	1	16	Yes
> 24693	20857	0	1	16	Yes
> 24765	20925	0	1	16	Yes
> 24810	20964	0	1	16	Yes
> 24986	21105	0	1	16	Yes
> 25001	21119	0	1	16	Yes
> 25014	21129	0	1	16	Yes
> 25024	21136	0	1	16	Yes
> 25063	21174	0	1	16	Yes
> 25091	21201	0	1	16	Yes
> 25121	21228	0	1	16	Yes
> 25133	21239	0	1	16	Yes
> 25167	21271	0	1	16	Yes
> 25178	21279	0	1	16	Yes
> 25206	21306	0	1	16	Yes
> 25285	21375	0	1	16	Yes
> 25324	21407	0	1	16	Yes
> 25403	21478	0	1	16	Yes
> 25642	21696	0	1	16	Yes
> 24260	20470	0	1	16	Yes
> 24307	20507	0	1	16	Yes
> 24390	20579	0	1	16	Yes
> 24511	20687	0	1	16	Yes
> 24539	20714	0	1	16	Yes
> 24579	20752	0	1	16	Yes
> 24639	20806	0	1	16	Yes
> 24671	20837	0	1	16	Yes
> 24694	20858	0	1	16	Yes
> 25009	21126	0	1	16	Yes
> 25086	21196	0	1	16	Yes
> 25272	21363	0	1	16	Yes
> 25599	21661	0	1	16	Yes
> 25635	21691	0	1	16	Yes
> 24276	20480	0	1	16	Yes
> 24320	20516	0	1	16	Yes
> 24453	20637	0	1	16	Yes
> 24516	20692	0	1	16	Yes
> 24666	20832	0	1	16	Yes
> 24691	20855	0	1	16	Yes

Thanks a lot it is fixed 
I appreciate

**Comment by Hlavtox** [comment] 2021-02-06 20:47
@ibrahimfsasmaz Perfect!!! Can you explain what you use this status for and when do you use it? Maybe we can tweak the logic of reserving products better. :)

**Comment by hibatallahAouadni** [comment] 2021-02-08 17:17
Hello @ibrahimfsasmaz 

Could you please answer @Hlavtox question to understand better why you encounter this issue :wink: 

Thanks in advance.

**Comment by hibatallahAouadni** [comment] 2021-03-01 11:50
Hello @ibrahimfsasmaz ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-01 11:50 UTC
Labels: Bug, BO, Stocks, No change required, 1.7.6.5
