### ISSUE TITLE
Every time i go to dashboard PHP warning are created by dashproducts module

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#30480] opened 2022-12-04 02:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

i noticed recently that every time i go to dashboard, and on the daskboard is acrtive the module dashproducts for each order present in the table a warning message appear in error_log_php like:

`[04-Dec-2022 03:07:01 Europe/Rome] PHP Warning:  Illegal string offset 'id_category_default' in /home2/xxxx/public_html/modules/dashproducts/dashproducts.php on line 224`

seems the module cannot get the category 
![image](https://user-images.githubusercontent.com/16102074/205471142-57cb0f88-b366-4638-a8ca-d0b046ad3d60.png)

the dashproduct module is version v2.1.2

### Expected behavior

Going to dashboard must not create any php warning error

### Steps to reproduce

1) visit the dashboard
2) check the error_log_php
3) some warning message caused by dashproducts module appear in the list.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2 / 7.4

### If your bug is related to a module, specify its name and its version

dashproducts v2.1.2

**Comment by HartLarsson** [comment] 2022-12-05 18:44
i've resolved the php warning bringing back the 2.1.1 way of getting the default category.
This is the mod i did:

```
@dashproducts.php @line 224

-            $category = new Category($product_obj->getDefaultCategory()['id_category_default'], $this->context->language->id);
+            $category = new Category($product_obj->getDefaultCategory(), $this->context->language->id);
```

**Comment by hibatallahAouadni** [comment] 2022-12-06 13:53
Hello @HartLarsson 

I don't seem to understand your issue, I tried to reproduce it with PS1787 but I get nothing :disappointed: 
Could you please check the attached screen record below:

[issue_30480.webm](https://user-images.githubusercontent.com/23308427/205930471-ab4f32f7-6d7a-4fc9-9565-6692e7791cd1.webm)

Waiting for your feedback.

Thanks!

**Comment by HartLarsson** [comment] 2022-12-07 10:29
> Hello @HartLarsson
> 
> I don't seem to understand your issue, I tried to reproduce it with PS1787 but I get nothing 😞 Could you please check the attached screen record below:
> 
>  issue_30480.webm 
> Waiting for your feedback.
> 
> Thanks!

hi, please check in the dashboard the BEST SELLER tab and see if you get for each product the Category default name.
Pleae verify on error_log_php file that you dont' have the warning i posted there.

after my fix all category appears (before appear root or null)
![image](https://user-images.githubusercontent.com/16102074/206155309-95394f0c-990d-46cd-9ee1-ead1a1d25de4.png)

**Comment by sallemiines** [comment] 2022-12-07 14:11
Hello @HartLarsson 

Following your steps unfortunately I didn't manage to reproduce your issue , I even didn't understand it ! 
could you please provide us  more infos ? 

Thank you !

**Comment by HartLarsson** [comment] 2022-12-08 22:48
> Hello @HartLarsson
> 
> Following your steps unfortunately I didn't manage to reproduce your issue , I even didn't understand it ! could you please provide us more infos ?
> 
> Thank you !

i'm sorry if is not clear, more then post the pictures and the mod to the script i did to solve the problem... i've no other ideas :)

**Comment by AureRita** [comment] 2022-12-09 16:15
Hi @HartLarsson 

I tried to reproduce you issue as you can see : 

[Untitled_ Dec 9, 2022 5_12 PM.webm](https://user-images.githubusercontent.com/100699445/206744919-7fbaada7-d847-4c9a-a960-c1e344a1396d.webm)

I didn't reproduce your issue, I have many other but not yours. 

Did I miss something ? 

Waiting for your feedback

**Comment by HartLarsson** [comment] 2022-12-12 16:22
> Hi @HartLarsson
> 
> I tried to reproduce you issue as you can see :
> 
>  Untitled_.Dec.9.2022.5_12.PM.webm 
> I didn't reproduce your issue, I have many other but not yours.
> 
> Did I miss something ?
> 
> Waiting for your feedback

i don't know how to explain but i try again:

1) Error_log_php file containe php errors and is not the console error of the browser (f12 on chrome)
2) the error appear due to a problem to this line on module v2.1.2:

```
@dashproducts.php @line 224
 $category = new Category($product_obj->getDefaultCategory()['id_category_default'], $this->context->language->id);

```
the code ['id_category_default'] in that line give error on PS 1.7.8.7 PHP 7.4, don't know why but for me i solved removing that part like was in the module v2.1.1.

Please verify PHP errors NOT console errors!

thanks

**Comment by AureRita** [comment] 2022-12-13 15:08
Hi @HartLarsson 

I tried to create this document and check some files, I can't use this one so this issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

As you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by metacreo** [comment] 2023-01-16 09:33
confirm PHP 7.4.30 PS 1.7.8.8 php warning every time opening BO

```
        $this->name = 'dashproducts';
        $this->tab = 'administration';
        $this->version = '2.1.2';
        $this->author = 'PrestaShop';
```

Illegal string offset 'id_category_default' in ---/modules/dashproducts/dashproducts.php on line 224

```
            $category = new Category($product_obj->getDefaultCategory(), $this->context->language->id);
            //$category = new Category($product_obj->getDefaultCategory()['id_category_default'], $this->context->language->id);
```

solve warning issue

**Comment by hibatallahAouadni** [comment] 2023-09-01 07:29
Hello @HartLarsson 

Do you still encounter the issue with PS81x? Please check and feedback.

Thanks!

**Comment by paulnoelcholot** [comment] 2023-09-27 15:32
Hello @HartLarsson,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2023-09-27 15:32 UTC
Labels: Bug, BO, Dashboard, Dashproducts, Invalid, Module, 8.1.x

**Comment by metacreo** [comment] 2023-09-27 16:24
Invalid label invalid by invalid.
This is fixed here https://github.com/PrestaShop/dashproducts/pull/50
