### ISSUE TITLE
Module only Configure permission not possible in V1.7.5.0

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#12101] opened 2019-01-10 07:17 UTC
If I try to set only configure permission for demo users in back-office, and not to enable/disable the module. It is not possible. This is mandatory to give module edit permission, with the particular module configure permission.

**To Reproduce**
Just try to provide a module only configure permission, but not the module disable permission. It's not possible from Team -> Permissions tab in V1.7.5.0.

1. Go to 'Team' tab
2. Create a profile as "Demo User" by 'Profiles' Tab
3. Now create a user 'demo@demo.com' and give 'Demo User' profile to this user
4. Now go to 'Team->Permissions' tab.
5. Provide 'Modules Manager' tab view access
6. And now provide a module to 'configure'  permission only. See screenshot

Now if I give module tab 'edit' permission, demo user can now 'configure' the module, But now the demo user can also disable the module, which is not I want to allowed.

**Screenshots**
![module_permission](https://user-images.githubusercontent.com/19220745/50952243-c956a880-14d5-11e9-943b-89dfe5c8262e.png)
![module_tab_permission](https://user-images.githubusercontent.com/19220745/50952244-c956a880-14d5-11e9-89ee-971726062bdb.png)

**Additionnal information**
PrestaShop version: V1.7.5.0
PHP version: 7

**Comment by dheerajwebkul** [comment] 2019-01-10 07:18
I already reported these issue earlier in V1.6, which is merged:
https://github.com/PrestaShop/PrestaShop/pull/7455
https://github.com/PrestaShop/PrestaShop/pull/5532
The same issue is here now in V1.7 latest version

**Comment by khouloudbelguith** [comment] 2019-01-10 08:22
Hi @dheerajwebkul,

We manage to reproduce the issue, you just created a previous issue, it is added to our bug roadmap.
Your ticket is a duplicate of #9786
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-10 08:22
Duplicate of #9786

**Closed as completed by khouloudbelguith** 2019-01-10 08:22 UTC
Labels: Duplicate
