### ISSUE TITLE
Classic core theme translations not detected

### ISSUE THREAD

**Issue by Ecommerce-Manager** [PrestaShop/PrestaShop#36743] opened 2024-08-21 16:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Adding new string to the classic core theme does not show them in the backoffice translations interface.

### Steps to reproduce

1. Fresh install prestashop 8.1.7
2. Add string to any template of classic core theme
3. From backoffice go Translations > Modify translations > Front office translations > Core (no theme selected) > non-english-language
4. missing translations are not shown

### PrestaShop version(s) where the bug happened

8.1.7

**Comment by kpodemski** [comment] 2024-09-04 14:13
Hello @Ecommerce-Manager 

"It is not a bug, it is a feature"

You have to work on child-theme, or duplicate Classic.

**Comment by ingridusta** [comment] 2024-09-11 15:36
Hello @Ecommerce-Manager ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- example module in which you have modified a string

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you

**Comment by florine2623** [comment] 2024-11-13 11:09
I'm closing this issue as no answer was provided

**Closed as completed** 2024-11-13 11:09 UTC
Labels: Bug, BO, Theme & logo
