### ISSUE TITLE
Try update to the last minor release I've got this error: [Ajax / Server Error for action backupDb] textStatus: "error " errorThrown:" " jqXHR: " "

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#11225] opened 2018-11-01 16:19 UTC
**Describe the bug**
Dear staff,
after update the module, see issue #11224
I try to update to the Minor release, but I've got this error:
[Ajax / Server Error for action backupDb] textStatus: "error " errorThrown:" " jqXHR: " "
Before each operation I backed up the database and the entire site.

**To Reproduce**
1. Go to One Click Upgrade 
2. Choose the minor release (recommended) from 1.6.1.20 to 1.6.1.22
3. click on update
4. I've got the error: [Ajax / Server Error for action backupDb] textStatus: "error " errorThrown:" " jqXHR: " "

Before each operation I backed up the database and the entire site.

**Screenshots**
![errore-durante-aggiornamento](https://user-images.githubusercontent.com/28685316/47864216-5bb53e80-ddf9-11e8-944e-1f3b8b73d579.jpg)

**Additionnal information**
PrestaShop version: 1.6.1.20
PHP version: 5.5
1-Click Upgrade: 4.4.0

**Comment by khouloudbelguith** [comment] 2018-11-01 16:24
Hi @ballashop,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by ballashop** [comment] 2018-11-01 16:31
Hi @khouloudbelguith where I can find it?
Because, into the module/autoupgrade folder I didn't find a tmp folder
and I don't have any autoupgrade folder in the main domain path.
Thanks to your fast reply.

**Comment by khouloudbelguith** [comment] 2018-11-01 16:36
@ballashop, you can find it in the Project_Folder/Admin_folder/autoupgrade/tmp path.
Thanks!

**Comment by ballashop** [comment] 2018-11-01 16:44
Hi @khouloudbelguith there are sensitive data, can I send you in private way?

**Comment by khouloudbelguith** [comment] 2018-11-01 16:47
Hi @ballashop,

This is a public space.
You can provide me the log file by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by ballashop** [comment] 2018-11-01 16:50
I did, thanks

**Comment by khouloudbelguith** [comment] 2018-11-01 16:57
@ballashop, thanks.
I just received the e-mail.
I will check & feedback.

**Comment by ballashop** [comment] 2018-11-01 17:02
Ok, thank you.

**Comment by khouloudbelguith** [comment] 2018-11-01 17:10
@ballashop,

In your log file, I have this error (The same that you attached in the screenshot) =>  [INTERNAL] /XXXXXXXXXXXX/modules/autoupgrade/classes/UpgradeTools/Translator.php line 90 - sprintf(): Too few arguments.
@Quetzacoalt91 what do you think?
Thanks!

**Comment by ballashop** [comment] 2018-11-01 17:31
@khouloudbelguith @Quetzacoalt91 
does this error affect to the site?
now it's in the maintenance state, can I show it again?
Or should I restore the site and database backup?
Thanks for your support.

**Comment by ballashop** [comment] 2018-11-02 07:57
Hi @khouloudbelguith 
of course, I do immediately thanks

**Comment by Quetzacoalt91** [comment] 2018-11-02 08:57
@ballashop no need to restore anything. If the process failed at the step backupDb, nothing has been changed on the shop. You can directly disable the maintenance mode.

I'll have a look at this Translator issue, it could be related to the latest release.

**Comment by ballashop** [comment] 2018-11-02 09:23
@Quetzacoalt91 thanks for your reply.
Tomorrow, I will put the site under maintenance and try to update again.
I'm waiting your next kind response.
Thanks a lot.
Best regard

**Comment by Quetzacoalt91** [comment] 2018-11-02 14:14
The translation issue seems unrelated. You should check the server logs if you can access them. This error could be cause by a storage or memory issue, a rule by your hosting provider which prevents to use too many CPU, I/O resources...

Could you please have a look at your server logs? If the scripts stop without providing details, there is nothing I can do.

**Comment by ballashop** [comment] 2018-11-02 14:20
Hi @Quetzacoalt91,
I immediately ask to the hosting service to get more information.
I hope to receive assistance asap.
Thanks

**Comment by ballashop** [comment] 2018-11-06 14:58
Dear @khouloudbelguith @Quetzacoalt91 
the hosting service found this error:
Fatal error: Call to undefined method AdminSelfUpgrade::displayErrors() in xxAdminxxFolderxx/functions.php on line 281
They said that the one click module needs updating, so I clicked on reset (one click module) and I've got this warning:
2 errors
The module can not be installed.
This version of 1-click upgrade requires PHP 5.6 to work properly. Please upgrade your server configuration.
![aggiornare-modulo-one-click](https://user-images.githubusercontent.com/28685316/48072273-6fd3b400-e1dc-11e8-8ac0-516b7e27a62b.png)
In the fact we use a php 5.5 version.
So we asked to the hosting server if we can upgrade the php version.
Is it possible that these errors are due to the php version not adequate?
I'm waiting your kind response.
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2018-11-06 16:00
Hi @ballashop,

Just for your information, we recommend that you run your PrestaShop install on the latest version of PHP. PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 is [compatible with PHP 7.2.](https://github.com/PrestaShop/PrestaShop/pull/8246)
Thanks!

**Comment by ballashop** [comment] 2018-11-06 16:25
Hi @khouloudbelguith,
yes we know but at the moment we have decided to continue using version 1.6, until the update is available. 
Do you think it is enough to switch to the php 5.5 version?
The server assistance service told us that we can.
I'm waiting your kind response.
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2018-11-06 16:31
@Quetzacoalt91, what do think?
Thanks!

**Comment by ballashop** [comment] 2018-11-06 16:33
Hi @khouloudbelguith @Quetzacoalt91 
sorry, I meant the php version 5.6 and not the 5.5 that is currently in use.
Thank you so much.

**Comment by Quetzacoalt91** [comment] 2018-11-06 16:34
Yep, PHP 5.6 is the minimum version which allows you to use the upgrade module. Older versions are not compatible.

**Comment by ballashop** [comment] 2018-11-06 16:41
Hi @Quetzacoalt91 thanks, we upgrading the php to the 5.6 version.
do you think that the error as in this issue may depend on the obsolete version of PHP?
Thanks.

**Comment by Quetzacoalt91** [comment] 2018-11-06 17:01
It could be, yes. We check the version of PHP at the module installation since the v4.4.0.
I guess it was already installed on your shop, and upgrading the module to the version 4.4.0 made you miss the error. :)

**Comment by ballashop** [comment] 2018-11-07 14:58
Hi @khouloudbelguith @Quetzacoalt91,
I try to upgrade a php version but the server displayed a database connection error. I have forwarded this error to customer service on the server.
I will keep you updated, thanks.

**Comment by ballashop** [comment] 2018-11-09 10:27
Hi @khouloudbelguith @Quetzacoalt91 
the error is not there anymore but I have not had time to update yet, today there is a new 1.6.1.23.
I have meanwhile changed the php version to 5.6 and updated the one click module.
I hope to be able to backup and update to the latest release soon.
Thanks

**Comment by ballashop** [comment] 2018-11-11 08:13
Hi @khouloudbelguith @Quetzacoalt91 , unfortunately I still was not able to do the update, the error is similar:
[Ajax / Server Error for action backupFiles] textStatus: "error" errorThrown: "" jqXHR: ""
this time instead of **backupDb** is **backupFiles**.
I have also opened a ticket to the server customer service.
<img width="1452" alt="errore aggiornamento" src="https://user-images.githubusercontent.com/28685316/48310522-e849c480-e590-11e8-9bfe-b3f3a49506f3.png">
some info about the server

- Apache server software version
- PHP version 5.6.37
- Memory limit 512M
- Maximum execution time 300

Thanks for any reply.

**Comment by ballashop** [comment] 2018-11-11 09:23
Hi,
I tried to do the update again, this time the system came up to the backup of the DB tables, but it stopped for about 30 minutes on
Database backup: 234 tables left ...
displaying this error:
[Ajax / Server Error for action backupDb] textStatus: "error" errorThrown: "" jqXHR: ""
![errore-backupdb-02](https://user-images.githubusercontent.com/28685316/48311151-cdc91880-e59b-11e8-9096-bb8379b5d45b.png)

Thanks for any reply.

**Comment by ballashop** [comment] 2018-11-12 18:27
hi @khouloudbelguith @Quetzacoalt91,
we believe that the problem is of the server, the assistance advises us to make backups and update manually. I've always done everything via one click module, do you have any suggestions for that manual?
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-13 07:58
Hi @ballashop, you can follow this link: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/ for more details about to upgrade Prestashop.
Thanks!

**Comment by ballashop** [comment] 2018-11-13 20:45
Hi @khouloudbelguith,
sorry form my late, thanks a lot for the link.
I'm going to read.
Thanks again.

**Comment by khouloudbelguith** [comment] 2018-11-14 08:23
Hi @ballashop,

You are welcome!
So, can I close this issue?

**Comment by ballashop** [comment] 2018-11-14 09:33
Hi @khouloudbelguith,
can I re-open if I didn't find a solution?
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2018-11-14 09:34
@ballashop, that's ok, this issue is still open.
Waiting for your feedback.

**Comment by ballashop** [comment] 2018-11-14 09:40
Hi @khouloudbelguith,
thanks, about the link you wrote before, there is a paragraph that I didn't understand well.
I mean this: Note about `vendor` folder.
honestly I did not understand which folder refers to the "vendor" one.
I ask you the courtesy to give me directions please.
Thanks.

**Comment by khouloudbelguith** [comment] 2018-11-14 09:50
@ballashop, you can find the vendor folder under you Project_Folder/vendor.
![image](https://user-images.githubusercontent.com/16067358/48474568-1cc0b900-e7fb-11e8-8fb8-bd0c7bf2ddce.png)
Thanks!

**Comment by ballashop** [comment] 2018-11-14 10:04
Hi @khouloudbelguith 
I didn't find this folder, we don't have any "vendor" folder into the main project path.
Maybe is it in the update package?
I'm waiting your kind response.
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-14 10:18
@ballashop, yes, this folder exists only in the PSv1.7, it doesn't exist in the PS1.6.
Thanks!

**Comment by ballashop** [comment] 2018-11-14 10:32
Ok, thanks, but we need to update to a latest version of 1.6
from 1.6.1.20 to 1.6.1.23
WE are not ready to change to 1.7 sorry.
That paragraph is not useful for updating version 1.6, is'n it?
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-14 10:42
@ballashop, There are two ways to upgrade PrestaShop1.6:

- Automatic
- [Manual](http://doc.prestashop.com/display/PS16/Manual+update)

For more information you can follow this documentation: http://doc.prestashop.com/display/PS16/Updating+PrestaShop
Thanks!

**Comment by ballashop** [comment] 2018-11-14 10:45
Ok, but the link you wrote before:
https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/
is it just for 1.7?
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-14 10:53
ping @Quetzacoalt91

**Comment by Quetzacoalt91** [comment] 2018-11-14 10:56
Yes, these explanations are also valid on PrestaShop 1.6 and older versions.

**Comment by ballashop** [comment] 2018-11-14 10:59
hi, @Quetzacoalt91 @khouloudbelguith,
thanks I'm going to try.
I will contact you as soon as I have more info.
Thanks a lot

**Comment by khouloudbelguith** [comment] 2018-11-14 11:01
@ballashop, Thanks!
Waiting for your feedback.

**Comment by ballashop** [comment] 2018-11-14 11:06
the local upgrade test with MAMP was successful by one click module, which means that the problem lies with the online server.
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-14 11:13
@ballashop, so in your local, the issue is solved?

**Comment by ballashop** [comment] 2018-11-14 11:20
HI @khouloudbelguith @Quetzacoalt91,
at this point I think so.
thanks for your patience.

**Comment by khouloudbelguith** [comment] 2018-11-14 11:22
@ballashop, It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-14 11:22 UTC
Labels: Bug, Autoupgrade, No change required
