### ISSUE TITLE
Ecotax is unavailable for combinations

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#16462] opened 2019-11-19 11:01 UTC
**Describe the bug**
Ecotax is unavailable for combinations

By displaying the variable `$product` in the loop of the file `/themes/classic/templates/checkout/_partials/order-confirmation-table.tpl` (order confirmation page), the `ecotax` is `"0.000000"` for the combination.

`ecotax` seems to refer to the ecotax of the product and therefore seems to override the one of the combination.

The same problem occurs on the product page, where `ecotax` is also `0` (and so the ecotax is not displayed).

I know that this ticket is a duplicate of #9967 but I want to show that the problem is bigger: the data would be correctly displayed if it went up correctly.

**To Reproduce**
1. Enable ecotax
2. Create a product with combinations and ecotax in combinations
3. Display `$product` variable on the product page and on the order confirmation page

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-11-19 11:10
Hi @yannicka,

Since it is a duplicate, I need to close this issue.
But I will edit the oldest report.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-19 11:10
Duplicate of #9967

**Closed as completed by khouloudbelguith** 2019-11-19 11:10 UTC
Labels: Duplicate, Combinations
