### ISSUE TITLE
Problem on credit note

### ISSUE THREAD

**Issue by Gardella-Web** [PrestaShop/PrestaShop#28341] opened 2022-04-26 14:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi all
Problem on credit note
I create a credit note linked to an invoice made on a customer of a customer group with a 15% reduction.

https://github.com/PrestaShop/PrestaShop/issues/27880 (with a problem too)

I put the quantity => 9
it gives me the result corresponding to the invoice (bad) and when I validate the credit note.... everything changes

the credit note is 33.48 excl.vat
but incl.vat = ... 40.14 ... why ?

No coherence, there is a big problem, or I've missed something

![avoir](https://user-images.githubusercontent.com/71068367/163544442-949ba5fa-0949-421b-90dd-32e582656ab9.JPG)

### Steps to reproduce

1. Shop B2B
2. create invoice with 9 products x 4.38 UT excl.VAT
3. client within group -15% so = 4.38 x 0.85 (-15%) = 3.723 so 3.72 excl.VAT
4. 3.72 x 9 = 33.48 excl.VAT
5. 33.48 x 1.2 (+20%) = 40.176 so 40.18 incl.VAT
6. Now create a credit note linked to this invoice
7. the credit note is 33.48 excl.vat but = 40.14  incl.vat ... wrong

### PrestaShop version(s) where the bug happened

1.7.6.2 1.7.7.8

**Comment by hibatallahAouadni** [comment] 2022-04-27 11:31
Hello @Gardella-Web 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9779. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-04-27 11:32
Duplicate of #9779

**Closed as completed by hibatallahAouadni** 2022-04-27 11:31 UTC
Labels: Bug, Duplicate, Credit notes, Taxes and Prices, B2B, Invalid

**Comment by hibatallahAouadni** [comment] 2022-04-27 11:36
Related to #9994
