### ISSUE TITLE
trait AssetUrlGeneratorTrait is not handling Server Media 

### ISSUE THREAD

**Issue by Jacky75** [PrestaShop/PrestaShop#16064] opened 2019-10-22 11:01 UTC
**Describe the bug**
Compressed JS and CSS are not using the configured Server Media 

**To Reproduce**
1. In the platform backoffice setup a Server Media 
2. Enable CSS compressione and Javascript Compression
3. Open the website homepage.
4. Look at the static content urls. All images are using the Server Media, the compressed JS and CSS aren't using the Server Media
5. Looking at the code of trait AssetUrlGeneratorTrait, the method getFQDN() is not considering if the platform is using or not Server Media.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22

**Comment by khouloudbelguith** [comment] 2019-10-22 11:09
Hi @Jacky75,

We are aware of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9890
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-22 11:09
Duplicate of #9890

**Closed as completed by khouloudbelguith** 2019-10-22 11:09 UTC
Labels: Duplicate
