### ISSUE TITLE
ps_legalcompliance override $link helper

### ISSUE THREAD

**Issue by Nakira** [PrestaShop/PrestaShop#21938] opened 2020-11-16 16:09 UTC
#### Describe the bug

$link smarty helper is overriden by module making all calls to $link fail.

#### Expected behavior

Keep the helper sane

#### Steps to Reproduce

try to use $link helper after hookDisplayCartPrixe

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

Found this : https://www.prestashop.com/forums/topic/1025678-ps_legalcompliance-%C3%A9crase-lobjet-link/

**Comment by hibatallahAouadni** [comment] 2020-11-16 16:57
Hello @Nakira ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- Names of modules to be overrided or used
- steps to reproduce (more clearly)
- host
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by Nakira** [comment] 2020-11-16 17:37
the information is in the code,

```php

 public function hookDisplayCheckoutSubtotalDetails($param)

   {

       // Display "under conditions" when the shipping subtotal equals 0

       if ('shipping' === $param['subtotal']['type'] && 0 === $param['subtotal']['amount']) {

           $cms_role_repository = $this->entity_manager->getRepository('CMSRole');

           $cms_page_shipping_and_payment = $cms_role_repository->findOneByName(self::LEGAL_SHIP_PAY);

           $link = $this->context->link->getCMSLink((int)$cms_page_shipping_and_payment->id_cms);

           $this->context->smarty->assign(array('link' => $link)); // <-- This line override de $link helper

           return $this->display(__FILE__, 'hookDisplayCartPriceBlock_shipping_details.tpl');

       }

   }

```

This line ``` $this->context->smarty->assign(array('link' => $link));``` should not assign the link variable.

Here is my override  (2 files) :

/override/modules/ps_legalcompliance/ps_legalcompliance.php :

```php
<?php
/**
 * 2007-2017 PrestaShop.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to http://www.prestashop.com for more information.
 *
 * @author     PrestaShop SA <contact@prestashop.com>
 * @copyright  2007-2017 PrestaShop SA
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *  International Registered Trademark & Property of PrestaShop SA
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

/* Namespaces used in this module */
use PrestaShop\PrestaShop\Core\Foundation\Database\EntityManager;

class Ps_LegalComplianceOverride extends Ps_LegalCompliance
{


    public function hookDisplayCheckoutSubtotalDetails($param)
    {
        // Display "under conditions" when the shipping subtotal equals 0e

            $cms_role_repository = $this->entity_manager->getRepository('CMSRole');
            $cms_page_shipping_and_payment = $cms_role_repository->findOneByName(self::LEGAL_SHIP_PAY);
            $link = $this->context->link->getCMSLink((int) $cms_page_shipping_and_payment->id_cms);

            $this->context->smarty->assign(array('linke' => $link));
            return $this->display(__FILE__, 'hookDisplayCartPriceBlock_shipping_details.tpl');

    }

}

```

/override/modules/ps_legalcompliance/views/template/hook/hookDisplayCartPriceBlock_shipping_details.tpl :

```tpl
{**
 * 2007-2016 PrestaShop
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to http://www.prestashop.com for more information.
 *
 *  @author 	PrestaShop SA <contact@prestashop.com>
 *  @copyright  2007-2016 PrestaShop SA
 *  @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *  International Registered Trademark & Property of PrestaShop SA
 *}

 <a href="{$linke}" target="_blank">
    {l s='(Under conditions)' d='Modules.Legalcompliance.Shop'}
 </a>

```
This has been 2 case for at least 2 years : https://github.com/PrestaShop/ps_legalcompliance/blame/master/ps_legalcompliance.php#L997

Sorry but i passed an entire day finding the source. This is all you'll get from me ;-)

**Comment by hibatallahAouadni** [comment] 2020-11-17 10:11
Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers wdyt?

**Comment by PierreRambaud** [comment] 2020-11-20 10:37
@hibatallahAouadni If you're able to reproduce the problem it's a bug and the module needs to be improved.

@Nakira If you have the solution, feel free to open a pull request on the module. :)

**Comment by SimonGrn** [comment] 2020-11-25 10:03
Hello,

we don't have enough context. We need more guidance, and an example in the form of a module.
@Nakira we need more information from your side. 

Thank you.

**Comment by hibatallahAouadni** [comment] 2020-12-16 14:59
Hello @Nakira ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-16 14:59 UTC
Labels: Bug, CO, No change required, Hook, 1.7.6.8
