### ISSUE TITLE
Faceted search v306 can't update price reindex result: empty categories without products

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14471] opened 2019-07-03 17:21 UTC
<img width="486" alt="Schermafbeelding 2019-07-03 om 19 20 28" src="https://user-images.githubusercontent.com/2944981/60611919-c9ba6700-9dc7-11e9-9647-6e62149e0639.png">

PrestaShop 1.7.5.2

**Comment by khouloudbelguith** [comment] 2019-07-04 07:49
Hi @sdwebdesign,

I did not manage to reproduce the issue with PS1.7.5.2 / PS1.7.6.0rc1 & ps_facetedsearch v3.0.6.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by marionf** [comment] 2019-08-01 08:15
Hello,

Despite our several trials, we could not reproduce your issue with the provided informations.
Since we have no news for more than 25 days, I close this issue.
Feel free to open a new one if needed.

Best regards.

**Closed as completed by marionf** 2019-08-01 08:15 UTC
Labels: Bug, BO, Can't reproduce, Faceted search, 1.7.5.2
