### ISSUE TITLE
Order continue button issue

### ISSUE THREAD

**Issue by BudrysLP** [PrestaShop/PrestaShop#17113] opened 2020-01-11 12:28 UTC
**Describe the bug**

When I try to make some order and press continue button I am logout.
Please take a look on picture and button link.

**To Reproduce**

1. Login
2. Add producy to cart
3. Go to checkout
4. Put address
5. Press continue button and You will be logout

**Additional information**

PrestaShop version: 1.7.6.1
PHP version: 7.2

![PS2 jpg f5917fb04df6fcf0619bce3b94da319f (1)](https://user-images.githubusercontent.com/9719910/72204245-1e752380-3476-11ea-8a7c-f95c5c30b75c.jpg)

**Comment by khouloudbelguith** [comment] 2020-01-13 09:59
Hi @BudrysLP,

I did not manage to reproduce the issue with Ps1.7.6.2& PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1RIkZlu8zWk9m1pZYRCK0n0mLsKFqhfnE/view
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with the theme author & feedback.

**Comment by khouloudbelguith** [comment] 2020-02-10 07:53
Hi @BudrysLP,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-10 07:53 UTC
Labels: Bug, FO, No change required, Checkout, 1.7.6.1
