### ISSUE TITLE
Translations of controller not display from other theme than classic

### ISSUE THREAD

**Issue by alex4102** [PrestaShop/PrestaShop#13836] opened 2019-05-17 11:56 UTC
**Describe the bug**
When I want to edit translations from other theme than classic (not a child-theme). I only see translations from views, not controller.

**To Reproduce**
1. Go to Translation of other theme than classic
2. Search 'available at this time, please contact us' to see the translation in ShopNotificationsError.
3. Nothing appear, but if you make this search in translation of classic theme is woring.

**Screenshots**
Classic theme
<img width="1362" alt="Capture d’écran 2019-05-17 à 13 54 47" src="https://user-images.githubusercontent.com/10240758/57926402-72117c00-78ab-11e9-8547-b3da0ac20f64.png">

Other theme
<img width="1358" alt="Capture d’écran 2019-05-17 à 13 54 52" src="https://user-images.githubusercontent.com/10240758/57926403-72117c00-78ab-11e9-9f64-c2e52099b6c9.png">

**Additionnal information**
PrestaShop version: 1.7.5.1 (But for all 1.7 I think)
PHP version: 7.1

**Comment by kpodemski** [comment] 2019-05-17 12:00
This is known issue with Translations, i've reported this with preffered solution almost 2 years ago

https://gist.github.com/kpodemski/c21c8b0a7ca3793ce39a3bff1a3932bb

:/

**Comment by alex4102** [comment] 2019-05-17 12:04
2 years ago ... oh and without this fix we need to edit translation in classic theme option ?

**Comment by khouloudbelguith** [comment] 2019-05-17 12:06
Hi @alex4102,

Your ticket is a duplicate of #9818
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-17 12:06
Duplicate of #9818

**Closed as completed by khouloudbelguith** 2019-05-17 12:06 UTC
Labels: Duplicate

**Comment by alex4102** [comment] 2019-05-17 12:13
@kpodemski I tried to copy your solution on 1.7.5.1 and it's still not working :/

**Comment by alex4102** [comment] 2019-05-17 12:15
I see the translation now, but search and treeview not working well

**Comment by alex4102** [comment] 2019-05-17 12:17
@kpodemski I tried to copy your solution on 1.7.5.1 and it's still not working :/

I see the translation now, but search and treeview not working well

Treeview, number of strings and search now working.

Classic Theme
<img width="1366" alt="Capture d’écran 2019-05-17 à 14 16 24" src="https://user-images.githubusercontent.com/10240758/57927477-696e7500-78ae-11e9-97f1-b04a8960050a.png">

Custom Theme
<img width="1367" alt="Capture d’écran 2019-05-17 à 14 16 33" src="https://user-images.githubusercontent.com/10240758/57927478-6a070b80-78ae-11e9-96a5-42561fd16d5f.png">

Maybe fix the function listTreeAction is needed too
