### ISSUE TITLE
Total cart calculation error with vouchers

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#20889] opened 2020-09-08 08:11 UTC
#### Describe the bug

I've noticed a clear error in total cart calculation.

Prices are inserted Tax included (22% in italy) and the custoemr is from Canada, so all prices are Tax free, and seems Prestashop works good.
Decimal are 2 (setup in backoffice)

![image](https://user-images.githubusercontent.com/16102074/92451105-94c05600-f1bc-11ea-8001-067cde91d635.png)

In the customer order there is 1 product with 14 accessories for a total of 250,656€

![product list](https://user-images.githubusercontent.com/16102074/92449509-76f1f180-f1ba-11ea-93df-bf22839dad3a.png)

for each of the 14 accessories there is a 30% discount each
Every accessory cost 15.574€ with a discount od 30% each (4.672€)

![vouchers](https://user-images.githubusercontent.com/16102074/92449579-912bcf80-f1ba-11ea-8fa3-760adc54ebee.PNG)

Shipping is calculated in correct way and the ammount is 43.90€

the total cart calculation must be 185.246€ but instead PS calculate 236.48€, value that I've not idea where comes from.
there is a difference of 7.334€

![total cart](https://user-images.githubusercontent.com/16102074/92449701-b8829c80-f1ba-11ea-9b3e-a30622ca5e06.PNG)

#### Expected behavior

The calculation is wrong, must be 185,246€ (185,25€) instead of 236,48

I did on excel some calculation using 3 decimals to be more precise:

![image](https://user-images.githubusercontent.com/16102074/92454492-db17b400-f1c0-11ea-8bca-45408673a74d.png)

PAYMENT ERROR ON PAYPAL
When customer goes to pay with paypal paypal give back a payment error.
![image](https://user-images.githubusercontent.com/16102074/92451504-1912d900-f1bd-11ea-82de-d3648d7a1b65.png)

#### Steps to Reproduce

1. Create a main product with tax 22% with these prices:
![image](https://user-images.githubusercontent.com/16102074/92450093-49f20e80-f1bb-11ea-8f72-aaac34945605.png)

2. create 14 accessories with this price each:
![image](https://user-images.githubusercontent.com/16102074/92450215-6f7f1800-f1bb-11ea-88b8-d7ac9118898a.png)

3. create for each of the 14 pruducts accessories vouchers with 30% discount 

4. add all to the cart and the calculation will be wrong like in my case

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-09-08 08:37
Hi @HartLarsson,

Thanks for your report.
This is a rounding issue.
We are awre of this issue, it is added to our debug roadmap.
Your issue will be fixed in this Epic: https://github.com/PrestaShop/PrestaShop/issues/19445
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9779
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-08 08:37
Duplicate of #9779

**Closed as completed by khouloudbelguith** 2020-09-08 08:37 UTC
Labels: Duplicate

**Comment by HartLarsson** [comment] 2020-09-08 08:49
> Duplicate of #9779

the fix will be applied to 1.7.6.x branch too?

thanks

**Comment by khouloudbelguith** [comment] 2020-09-08 09:25
In the 176x branch, we add security patches and the fix for regressions.

Thanks!

**Comment by HartLarsson** [comment] 2020-09-08 11:23
i did a little test modify on ps_currency table the precision to 2 decimals and field name = Euro keep in BO the 2 decimals view.

![image](https://user-images.githubusercontent.com/16102074/92471845-e676d980-f1d8-11ea-8a28-6b5a351c830b.png)


calculating on excel:
![image](https://user-images.githubusercontent.com/16102074/92470163-52a40e00-f1d6-11ea-9eb2-960561cf2181.png)

the result on PS
![image](https://user-images.githubusercontent.com/16102074/92470201-651e4780-f1d6-11ea-80c9-72bd54b532cd.png)

seems matching.

Anyone made the test?

**Comment by khouloudbelguith** [comment] 2020-09-08 11:33
@HartLarsson, the currency precision will be fixed in the next 1700 version
BO
![image](https://user-images.githubusercontent.com/16067358/92470967-77e54c00-f1d7-11ea-9d70-ffeb1eb17832.png)

FO
![image](https://user-images.githubusercontent.com/16067358/92471156-c0046e80-f1d7-11ea-868e-6dd8443ef513.png)

Also, you can follow this PR: https://github.com/PrestaShop/PrestaShop/pull/20378

Thanks!

**Comment by HartLarsson** [comment] 2020-09-08 11:42
> @HartLarsson, the currency precision will be fixed in the next 1700 version
> BO
> ![image](https://user-images.githubusercontent.com/16067358/92470967-77e54c00-f1d7-11ea-9d70-ffeb1eb17832.png)
> 
> FO
> ![image](https://user-images.githubusercontent.com/16067358/92471156-c0046e80-f1d7-11ea-868e-6dd8443ef513.png)
> 
> Also, you can follow this PR: #20378
> 
> Thanks!

i re edited the post, i forgot i've made percision 2 and name= Euro as explained in other fix, but the error continue.
![image](https://user-images.githubusercontent.com/16102074/92732194-64bcb280-f376-11ea-909b-6fffac43daaa.png)

i think is not only a round calculation but how the core process all the calculation adding errors over errors with a final difference of many euros!

Seems that in FO there is a right calculation bt when order is saved in BO the differences are evident!

**Comment by HartLarsson** [comment] 2020-09-08 11:47
so the computing precision variable will be taken in next patch from ps_currency.precision field?

i see in the pr: #20378 the use of: Context::getContext()->getComputingPrecision());
