### ISSUE TITLE
dashtrends - after a partial refund, dashtrends module is not updated

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#28186] opened 2022-04-08 12:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Same issue as https://github.com/PrestaShop/PrestaShop/issues/16770

What I have in statssales module : OK
<img width="710" alt="statssales" src="https://user-images.githubusercontent.com/16019289/162438928-94d9fc35-7cf3-477b-8daf-4271f8978c9a.png">

What is reported in dashtrends module : NOK
<img width="714" alt="dashtrends" src="https://user-images.githubusercontent.com/16019289/162438942-0cde9725-0e46-4a04-ae3d-55830bf036d1.png">

Reported originally here : https://github.com/PrestaShop/statssales/pull/22#pullrequestreview-933184277

### Expected behavior

The sales field should be updated after a partial refund.
Sales = Order Sales - Refund Sales 

### Steps to reproduce

1. Create an Order
2. Make a partial refund
3. Go to Dashboard
4. See error > the refund is not taken into account

### PrestaShop version(s) where the bug happened

1.7.8.x, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

dashtrends v2.0.3

**Comment by hibatallahAouadni** [comment] 2022-05-09 09:20
Ping @PrestaShop/product-team @florine2623 @Progi1984 this issue has been fixed with this PR https://github.com/PrestaShop/dashtrends/pull/34
But the PR is merged in 2.1.0 version whose still not released yet :disappointed: 
So, should we close this one as a duplicate of #16770?

**Comment by hibatallahAouadni** [comment] 2022-05-26 11:28
Hello @florine2623 

This issue has been fixed with this PR https://github.com/PrestaShop/dashtrends/pull/34, I tried to reproduce the issue on dev branch of this module and I didn't reproduce it:

![image](https://user-images.githubusercontent.com/23308427/170477826-de66dee1-0582-4d9e-a0e3-e469c9d31bf9.png)

As you can see the shipped order has an amount: 208.7 (tax excl) when we subtracted the shipping amount 7 (tax excl) = 201.7 

Now, if we apply partial refund and we return one product of demo_5 which price is 29 (tax excl) which means 34.8 (tax incl):

![image](https://user-images.githubusercontent.com/23308427/170478501-a177f458-4a85-4699-9834-54c03d5e80b9.png)

Let's check the dashtrends: 201.7 - 29 = 172.7 (tax excl) :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/170478648-ee4f6f1b-1dfc-4f49-b451-b9a3ff492975.png)

Now sales: 208.7 - 29 = 179.7 (tax excl) :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/170478780-08549630-acb6-4efb-80bb-25d0e8ce0014.png)

Everything is OK :heavy_check_mark: we just need to wait the release of the new version 2.1.0 of dashtrends.
Closing the issue as a duplicate of this one #16770.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-05-26 11:28 UTC
Labels: Bug, BO, Duplicate, Dashboard, Order, Dashtrends, 1.7.7.8, Invalid, Module

**Comment by hibatallahAouadni** [comment] 2022-05-26 11:29
Duplicate of #16770
