### ISSUE TITLE
Can't update cache configuration in BO

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/PrestaShop#27445] opened 2022-01-24 14:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Prestashop can't update cache configuration 

### Expected behavior

Cache status should be updated after switching and sending the form.
For the moment you need to manually edit the configuration file: `app/config/parameters.php`
and change the line:
    'ps_cache_enable' => false,

This should be possible to merchants.only from BO 

### Steps to reproduce

1. Go to Advanced parameters > Performance > Cache
 ![image](https://user-images.githubusercontent.com/23559010/150805060-d893d270-b155-4a65-8e35-d6554a32e92f.png)
2. Try to change the status of cache between Enable and Disable and click save.
3. See no change happens.

### PrestaShop version(s) where the bug happened

1.7.7.5. 1.7.8.0

### PHP version(s) where the bug happened

7.2, 7.4

**Comment by florine2623** [comment] 2022-01-24 15:08
Hello @arouiadib ,

Is your issue related to https://github.com/PrestaShop/PrestaShop/issues/25211 ?

Could you check and let me know ?
Thanks!

**Comment by arouiadib** [comment] 2022-01-24 15:30
Hello @florine2623 and thanks for your time.
I have checked the issue you mentioned and I don't see that is related to this one.

**Comment by hibatallahAouadni** [comment] 2022-01-27 09:57
Hello @arouiadib 

That's because you're missing these extensions (`Memcache PECL extension`, `APC PECL extension`, `Xcache extension`), see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/151335757-4e2deff3-34a2-4740-97c7-5731aa862e2e.png)

To save the first option you need to install and enable this extension `Memcache PECL extension` and the same foreach option :wink: 
Closing the issue as it's not a Bug.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-27 09:57 UTC
Labels: Bug, BO, Performance, 1.7.8.0, Invalid
