### ISSUE TITLE
Theme Customization fails to upgrade

### ISSUE THREAD

**Issue by sts098** [PrestaShop/PrestaShop#33000] opened 2023-06-24 15:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Screenshot_139](https://github.com/PrestaShop/PrestaShop/assets/46849814/27eaf11c-d7e6-4ca4-acb5-587827206e3f)

Tring to upgrade module from v1.2.2    to  v1.2.3   .   I receive an error from addon store.  You may be not allowed to download this module.  

Module is free from PrestaShop and I am logged in and upgraded other purchased modules.  

### Expected behavior

Simply expected to download and install.  

### Steps to reproduce

go to modules
find module Theme Customization
click on upgrade

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_themecusto

**Comment by AureRita** [comment] 2023-06-26 14:47
Hi @sts098 

Thank you for your report, Currently I tried to reproduce your issue but I can't as you can see : 

[Untitled_ Jun 26, 2023 4_41 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/9bda8776-8939-4a3f-bfb4-14597e4a2958)

Did I miss soemehting ? 
In wich version of theme custo are you ? 
If you try many times to update it, did it update ? 
Waiting for your feedback

**Comment by aniszr** [comment] 2023-07-14 09:47
Hello @sts098 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by aniszr** 2023-07-14 09:47 UTC
Labels: Bug, BO, Theme custo, Invalid, Module, 1.7.8.9
