### ISSUE TITLE
BO - Product - Standart product - Features

### ISSUE THREAD

**Issue by DianaButkute** [PrestaShop/PrestaShop#19809] opened 2020-06-17 07:45 UTC
#### Describe the bug

I want to create some features, one `Customized value` and second two existing ones. And the `Customized value` after the existing ones saving duplicates. 
I just create the product then add some features, first of all selecting the feature and setting the`Customized value` of it. Then add the second feature and choose the value from existing ones. Then save the product, refresh page and tried to add the third feature from the existing and then refresh page. You will see that the `Customized value` are duplicated. 

#### Expected behavior

Expecting that the `Customized value` do not duplicate after another features saving.

#### Steps to Reproduce

1. Go to Product list
2. Click on Create product, fill the name of the product
3. Scroll down to features setting. Fill first feature with customized value, then add second one and choose from existing ones. Save the product. Then refresh the page and add the third feature from chosen ones. Then refresh page.
4. And you will see that the customized value of the feature are duplicated.

**Screenshots**

![image](https://user-images.githubusercontent.com/51438018/84868500-74816f00-b085-11ea-81f9-0fffb65fd4e3.png)
![image](https://user-images.githubusercontent.com/51438018/84868667-be6a5500-b085-11ea-92c7-ccf1ba6cf2eb.png)
![image](https://user-images.githubusercontent.com/51438018/84868576-9549c480-b085-11ea-9afe-0fda677314f2.png)

#### Additional information

* PrestaShop version: 1.7.6.5/1.7.6.4
* PHP version: 7.1

**Comment by colinegin** [comment] 2020-06-17 11:08
Hello @DianaButkute,

Thanks for your feedback.
Actually your issue is a duplicate of #9680, so I'll close this one so we can all focus on the same issue. Please follow #9680, it should be fixed in 178 !

Have a nice day

**Closed as completed by colinegin** 2020-06-17 11:08 UTC
Labels: Duplicate
