### ISSUE TITLE
BO responsivity - there should be more space on the bottom, if there is a floating button

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25423] opened 2021-07-26 08:39 UTC
#### Describe the bug
You are unable to save or send a form that is on the bottom of the page, because the floating plus button is shown over it.

#### Expected behavior
Button should be usable.

#### How to fix it
Add additional padding to content-div, if there is this button. The user will be to scroll more and click the button just fine.

#### Screenshots
![mobile](https://user-images.githubusercontent.com/6097524/126959772-2859cae1-50e5-4e6a-b7dd-d37ede10e997.jpg)

#### Additional information
* PrestaShop version: develop

**Comment by hibatallahAouadni** [comment] 2021-07-26 13:58
Hello @Hlavtox 

Even the **plus** button is displayed over the **Save** button, I can click on the **Save** button without any problem, see the attached screen record below:

https://drive.google.com/file/d/1u9tH7hsnU_vNry3WQ3LR0Zt5-RPx0hhK/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-27 13:07
Hello @Hlavtox 

After discussing the issue on Slack, the **plus** button need to be displayed just below the **div**, so the user can click and read the **Save** button. 

It's a **bug**! and as this button is a new feature on develop and 178x, so it's not a regression! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-08-05 14:12
Ping @NeOMakinG

**Comment by Progi1984** [comment] 2021-08-25 07:10
Fixed by @NeOMakinG in #25557

**Closed as completed by Progi1984** 2021-08-25 07:10 UTC
Labels: Bug, develop, Minor, BO, Fixed, Front-end, PR available, Responsive, 1.7.8.x
