### ISSUE TITLE
Backoffice language when multistore is on

### ISSUE THREAD

**Issue by kamilmc** [PrestaShop/PrestaShop#28080] opened 2022-03-30 12:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When multistore mode is on, most of the backoffice interface elements (such as tab menu, product list, order list) are displayed in a language other than the employee's default language. External modules are displayed in the correct language .

### Expected behavior

All backoffice interface in employee language, as in prestashop 1.7.7.x

### Steps to reproduce

The default language of the employee is Polish

There are two stores in the multistore:
SHOPA (id = 1) is using only English as a main and default language.
SHOPB (id = 2) is using only Polish as a main and default language.

For all shops contexts (All shops, group, SHOPA, SHOPB) the backoffice display language is the same as set for SHOPA, no matter which employee has the language set 

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-03-31 10:11
Hello @kamilmc 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27617. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-31 10:11
Duplicate of #27617

**Closed as completed by hibatallahAouadni** 2022-03-31 10:11 UTC
Labels: Bug, Duplicate, Invalid
