### ISSUE TITLE
Split order on two with same order reference

### ISSUE THREAD

**Issue by barbosatrix** [PrestaShop/PrestaShop#22017] opened 2020-11-19 15:19 UTC
#### 
Some orders split in two with the same ORDER ID

#### Expected behavior

Do not split the order.

#### Steps to Reproduce

1. It happens randomly. 
2. We do not use specific carriers by product

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/15943150/99680883-878cd680-2a4b-11eb-878c-a1860e801cec.jpg)

Pedido 775
![pedido775](https://user-images.githubusercontent.com/15943150/99681709-7395a480-2a4c-11eb-8c72-aa52f23bce96.jpg)

Pedido 776
![pedido776](https://user-images.githubusercontent.com/15943150/99681724-78f2ef00-2a4c-11eb-898d-2f8618074bbd.jpg)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.28

**Comment by hibatallahAouadni** [comment] 2020-11-19 15:45
Hello @barbosatrix 

This bug only happen when we use specific carriers by product. See bug #9594
> It happens randomly.

So, I can't reproduce it! Could you please try again to reproduce the issue and list clear steps.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-11-19 16:20
Hi @barbosatrix,

Thank you for your report.
We have an [Epic](https://github.com/PrestaShop/PrestaShop/issues/15491) about the multi carriers problem.
Could you please check if your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15304#issuecomment-526137500 also.

Thank you!

**Comment by Hlavtox** [comment] 2020-11-20 10:04
@barbosatrix change ORDER ID to ORDER REFERENCE in post title and body, this is confusing ;-)

**Comment by hibatallahAouadni** [comment] 2020-12-09 11:01
Hello @barbosatrix 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-09 11:01 UTC
Labels: Bug, BO, Order, Topwatchers, No change required, 1.7.6.5

**Comment by djbuch** [comment] 2021-02-27 23:56
This problem is real !! Not depending on carriers but on an other problem.

We are currently having this issue (random) with three web sites from our customers.

It appears after investigation that it seems to be linked with address changes, when a customer already has something in his cart and changes the delivery address after and adds some other products, it sometimes creates this bug...

Couldn't reproduce it myself but saw the happening more than 10 times on different web sites.

Regards,

**Comment by micka-fdz** [comment] 2021-03-05 10:03
Hi @hibatallahAouadni, can you reopen this issue?

I also have this random issue with several clients and I've found the same thing as @djbuch.

**Comment by hibatallahAouadni** [comment] 2021-03-05 13:33
Hello @djbuch & @micka-fdz 

This is not just random bug :wink: this bug is already in our debug backlog see this [comment](https://github.com/PrestaShop/PrestaShop/issues/15304#issuecomment-526137500).
We close this issue cause it's a duplicate.
Related to #9594

Please subscribe to the issue mentioned above.
Thanks!

**Comment by ComonSoft** [comment] 2022-06-20 16:55
This is not the same issue as #9594, because we have the same bug with orders that have all products without carrier restriction. It happends randomly. We just noticed like said @djbuch that it could be probably when the user change delivery address during order process.
PS 1.7.6.4
PHP 7.2.34

**Comment by Matt75** [comment] 2022-06-20 22:08
@ComonSoft can you check this comment: https://github.com/PrestaShop/prestashop-specs/issues/111#issuecomment-965411185
