### ISSUE TITLE
FO combination jumps bug, still here

### ISSUE THREAD

**Issue by zenerry** [PrestaShop/PrestaShop#11412] opened 2018-11-15 19:56 UTC
**It might be the same, of the old #9390 bug **
I've just installed PS 1.7.5.0 Beta 1 and tryed what I've been looking forward to, of this release and it still doesn't work properly.

The feature from "product configuration" panel:
[SPANISH] "Mostrar productos con atributos no disponibles en la página de producto "
I think it is in ENGLISH: "Display unavailable product attributes on the product page."

it doesn't do anything.

when you have some combinations of a product and some of them are out of stock, 

 1   Create 2 combinations for a product like
    1.1. Size S, Color: Green, - default (and stock)
    1.2. Size M, Color: Blue, (and no stock)
  2  Navigate to the FO: switch to Size M => it jumps to the default combination.

**Additionnal information**
With php 7.2.12 and FastCGI  ---> nothing happens
With php 7.2.11 and FPM Nginx  ----> it pops up an error message below add to cart button.
PrestaShop version: 1.7.5.0 beta1, 1.7.4.4, 1.7.3.4

**Comment by khouloudbelguith** [comment] 2018-11-16 07:43
Hi @zenerry,

This is a different issue.
This issue occurs because the "Display unavailable product attributes on the product page" option is disabled in the Shop Parameters / Product Settings page.
We are aware of this issue.
Your ticket is a duplicate of #9667
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-16 07:43
Duplicate of #9667

**Closed as completed by khouloudbelguith** 2018-11-16 07:43 UTC
Labels: Duplicate

**Comment by zenerry** [comment] 2018-11-16 23:06
You're right its the same issue of #9667 .
Is my other reply, you told me the solution may come earlier if I make a "pull request". I'm very new in gitHub, and I don't see clearly how to do it. I don't want to create a messy or confusing request.
Could you please help me?
Thanks.

**Comment by khouloudbelguith** [comment] 2018-11-19 10:00
Hi @zenerry,

You can follow this link: https://github.com/firstcontributions/first-contributions to help you.
Thank you.
