### ISSUE TITLE
Autoupgrade : ps_facetedsearch an exception in Fo > All products page when upgrade from 8.0.0 ~ 8.0.2 to 8.1.7 with any php version

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#36439] opened 2024-06-27 14:36 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After an upgrade 8.0.0 to 8.1.7 the ps_facetedsearch throw an exception in FO > All products page

![Capture d’écran de 2024-06-27 11-03-44](https://github.com/PrestaShop/PrestaShop/assets/24647495/2c41c4e1-f786-46d3-ae48-04f5f71497df)

### Expected behavior

No error

### Steps to reproduce

1- Install 8.0.0 on php 7.3 (for example)
2- Upgrade to 8.1.7
3- Go to FO > All products page
See the error

PS : I use the docker image of PS prestashop/prestashop:8.0.0-7.3-apache

https://www.awesomescreenshot.com/video/29035672?key=2084acf477d09c37411d4818056902c7

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.2 ~ 8.1

### If your bug is related to a module, specify its name and its version

autoupgrade dev

**Comment by Hlavtox** [comment] 2024-06-27 15:32
@nesrineabdmouleh Module upgrade file did not run for some reason, there is a column to be added.

What was the version of faceted search BEFORE and AFTER the upgrade?

**Comment by Quetzacoalt91** [comment] 2024-06-27 15:48
When I reproduced this issue, the files were upgraded from 3.8.0 to 3.16.0 but the migration files are not run.

Going on the module manager and upgrade ps_facetedsearch fixes the issues, but this should have been done during the upgrade.

**Comment by Hlavtox** [comment] 2024-06-28 06:46
@Quetzacoalt91 Yes, the upgrades just randomly fail for no reason, even in BO. 🤷‍♂️ No idea what is causing it.

I have about 25 stores to manage. When I upgraded from 1.7.6 to 8.1.5, on all of the shops many native modules wrote "failed to upgrade module xxx". Especially ps_facetedsearch failed on all of them, linklist also.

Or, when I upgrade some module manually by uploading a zip in backoffice, it just randomly fails on some of my stores, let's say 3/25. When I re-upload the zip or go to module updates tab and click upgrade again, it works fine. 

Maybe one of the reasons could be weird naming of the upgrade methods in some cases. It's called with one parameter `$item($this);`

- Is this type hint supported in all PHP versions? `function upgrade_module_3_0_0(Ps_Facetedsearch $module)`
- Can a method be called with an extra parameter like this? `function upgrade_module_5_0_0()`

**Comment by Quetzacoalt91** [comment] 2024-06-28 09:54
From my logs, the upgrade is not even attempted.

The logs lists changes on the ps_facetedsearch (Because the original version was the one pre-installed with PrestaShop)

```
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch already exists.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/img already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/img/cross.png.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/img/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/img/edit.gif.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/img/icon already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/img/icon/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/img/icon/more.gif.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/img/icon/less.gif.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/img/cogs.gif.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/webpack.config.js.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/config already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/config/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/config/services.yml.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/.bablerc.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/config.xml.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/composer.lock.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/ps_facetedsearch-attribute-indexer.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/index.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/upgrade already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.4.1.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.0.3.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.6.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.14.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.12.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.13.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.11.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.15.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.8.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.4.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.3.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.9.0.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/upgrade/upgrade-3.0.0.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/controllers created.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/controllers/front created.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/controllers/front/cron.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/_dev already exists.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/_dev/front already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/facet.scss.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/slider.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/urlparser.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/overlay.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/index.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/events.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/slider.scss.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/front/overlay.scss.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/_dev/cldr already exists.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/_dev/cldr/specifications already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/cldr/specifications/price.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/cldr/specifications/number.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/cldr/number-formatter.js.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/_dev/cldr/exception already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/cldr/exception/localization.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/cldr/index.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/cldr/number-symbol.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/index.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/_dev/back already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/back/blocklayered.scss.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/_dev/back/index.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/.htaccess.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/ps_facetedsearch.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/ps_facetedsearch-clear-cache.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/package-lock.json.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/URLSerializer.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Adapter already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Adapter/AbstractAdapter.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Adapter/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Adapter/MySQL.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Adapter/InterfaceAdapter.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Definition created.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Definition/Availability.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Definition/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/index.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Hook already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/FeatureValue.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/Design.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/SpecificPrice.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/Product.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/Category.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/Feature.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/AbstractHook.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/ProductSearch.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/Attribute.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/Configuration.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Hook/AttributeGroup.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/HookDispatcher.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Product already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Product/SearchProvider.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Product/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Product/Search.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Product/SearchFactory.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Product/CoreSearchBackport.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Filters already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Filters/DataAccessor.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Filters/Products.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Filters/Block.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Filters/Provider.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Filters/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Filters/Converter.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Form already exists.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Form/Attribute created.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/Attribute/FormModifier.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/Attribute/FormDataProvider.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Form/AttributeGroup created.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/AttributeGroup/FormModifier.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/AttributeGroup/FormDataProvider.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/index.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Form/Feature already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/Feature/FormModifier.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/Feature/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/Feature/FormDataProvider.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Form/FeatureValue created.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/FeatureValue/FormModifier.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/FeatureValue/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Form/FeatureValue/FormDataProvider.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/src/Constraint already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Constraint/UrlSegmentValidator.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Constraint/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/src/Constraint/UrlSegment.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/delete.gif.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/ps_facetedsearch.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/logo.png.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views already exists.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/templates already exists.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/templates/admin already exists.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/templates/admin/_functions already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_functions/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_functions/show_limit.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/manage.tpl.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/templates/admin/_partials already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_partials/footer.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_partials/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_partials/header.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_partials/messages.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_partials/shops.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_partials/controllers.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/_partials/categories-tree.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/view.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/admin/add.tpl.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/templates/front already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/front/index.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/templates/front/catalog already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/front/catalog/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/front/catalog/active-filters.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/index.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/templates/hook already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/hook/feature_value_form.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/hook/attribute_group_form.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/hook/feature_form.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/hook/index.php.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/templates/hook/attribute_form.tpl.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/index.php.
[2024-06-27 15:11:14] Directory /modules/ps_facetedsearch/views/dist already exists.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/dist/front.js.LICENSE.txt.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/dist/front.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/dist/front.css.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/dist/back.css.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/dist/back.js.
[2024-06-27 15:11:14] Copied /modules/ps_facetedsearch/views/dist/back.js.LICENSE.txt.
```

And on the "Upgrade Module" step, nothing is run:

```
[2024-06-27 15:11:29] Cleaning file cache
[2024-06-27 15:11:29] [SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[2024-06-27 15:11:29] [CLEANING CACHE] File prod removed
[2024-06-27 15:11:29] [SKIP] directory "/themes/classic/cache/" does not exist and cannot be emptied.
[2024-06-27 15:11:29] Running opcache_reset
[2024-06-27 15:11:29] Warning detected during upgrade.
[2024-06-27 15:11:29] Database upgraded. Now upgrading your Addons modules...
[2024-06-27 15:11:29] Addons modules files have been upgraded.
[2024-06-27 15:11:30] The database has been cleaned.
[2024-06-27 15:11:30] Upgrade process done, but some warnings have been found.
[2024-06-27 15:11:30] /var/www/html/**admin_folder**/autoupgrade/download/prestashop.zip removed
[2024-06-27 15:11:30] /var/www/html/**admin_folder**/autoupgrade/latest removed
```

We should add something to warn the files of XYZ module has been updated, so we can check there are migrations files to run.

**Comment by Quetzacoalt91** [comment] 2024-06-28 15:22
It appears `ps_facetedsearch` was not distributed by the marketplace for PrestaShop 8.1.7.

I modified the range of versions on which the module is distributed: 


```
Warning detected during upgrade.
Database upgraded. Now upgrading your Addons modules...
[DEV] ajax request : upgradeModules
1 modules will be upgraded.
[DEV] ajax request : upgradeModules
Upgrading module ps_facetedsearch...
Content of archive /var/www/html/**admin_folder**/autoupgrade/tmp/ps_facetedsearch.zip is extracted
The files of module ps_facetedsearch have been upgraded.
[DEV] ajax request : upgradeModules
Addons modules files have been upgraded.
[DEV] ajax request : cleanDatabase
The database has been cleaned.
[DEV] ajax request : upgradeComplete
Upgrade process done, but some warnings have been found.
/var/www/html/**admin_folder**/autoupgrade/download/prestashop.zip removed
/var/www/html/**admin_folder**/autoupgrade/latest removed
End of process
```

Now the module is updated during the process, and the issue does not appear anymore.

I'm closing this issue as this is fixes, but we absolutely have to rework this system:
* Rely on distribution API as well as Addons Marketplace API
* Make sure the upgrade process is safe when no API cannot distribute updates

**Comment by nesrineabdmouleh** [comment] 2024-07-02 08:56
Hello @Quetzacoalt91,

The problem is partially resolved, the exception still displayed when upgrade from PS 1.7.8.0 ~ 1.7.8.8 to 8.1.7 on PHP 7.2 ~ 7.4

**Comment by Quetzacoalt91** [comment] 2024-07-02 10:44
Seen with @nesrineabdmouleh, it appears on https://github.com/PrestaShop/autoupgrade/actions/runs/9757682113?pr=749 the upgrade process failed while upgrading the modules.

```
INFO - === Step upgradeModules
INFO - 3 modules will be upgraded.
INFO - === Step upgradeModules
PHP Fatal error:  Uncaught PrestaShopModuleException: Hook with the name displayHeader has been registered by Ps_checkout, but the corresponding method hookDisplayHeader has not been defined in the Module class. in /var/www/html/classes/Hook.php:558
Stack trace:
#0 /var/www/html/classes/module/Module.php(1061): HookCore::registerHook(Object(Ps_checkout), 'displayHeader', NULL)
#1 /var/www/html/modules/ps_checkout/upgrade/upgrade-8.3.3.0.php(41): ModuleCore->registerHook('displayHeader')
#2 /var/www/html/classes/module/Module.php(591): upgrade_module_8_3_3_0(Object(Ps_checkout))
#3 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(268): ModuleCore->runUpgradeModule()
#4 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(240): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->doUpgradeModule('ps_checkout')
#5 /var/www/html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(79): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(46347, 'ps_ch in /var/www/html/classes/Hook.php on line 558

Fatal error: Uncaught PrestaShopModuleException: Hook with the name displayHeader has been registered by Ps_checkout, but the corresponding method hookDisplayHeader has not been defined in the Module class. in /var/www/html/classes/Hook.php:558
Stack trace:
#0 /var/www/html/classes/module/Module.php(1061): HookCore::registerHook(Object(Ps_checkout), 'displayHeader', NULL)
#1 /var/www/html/modules/ps_checkout/upgrade/upgrade-8.3.3.0.php(41): ModuleCore->registerHook('displayHeader')
#2 /var/www/html/classes/module/Module.php(591): upgrade_module_8_3_3_0(Object(Ps_checkout))
#3 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(268): ModuleCore->runUpgradeModule()
#4 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(240): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->doUpgradeModule('ps_checkout')
#5 /var/www/html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(79): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(46347, 'ps_ch in /var/www/html/classes/Hook.php on line 558
```

From my understanding: 
* it starts with PS Checkout,
* fails with of an exception thrown about a hook registered but not implemented
* stops without trying the other modules (i.e Faceted Search)

The issue was reported a month ago and the Payment squad is aware of it (cc @Matt75).


I would not consider it related to Faceted Search at the moment. While PS Checkout is being fixed, we need to understand why the process has been running the UI tests while the upgrade process failed. The workflow should have immediately stopped.

**Closed as completed** 2024-07-29 08:12 UTC
Labels: Bug, Autoupgrade, Detected by TE, Backlog SUE
