### ISSUE TITLE
PrestaShop lots of mistakes 

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#24931] opened 2021-06-12 11:54 UTC
I have a lot of errors on this server configuration, presta is very unstable and throws errors every now and then. 

Screenshot:
https://www7.zippyshare.com/v/FkrEYbS9/file.html
https://www7.zippyshare.com/v/712KeNQl/file.html
https://www7.zippyshare.com/v/nsApuDLS/file.html

* PrestaShop version: 1.7.7.4
* PHP version: 7.2.26
* Server: Linux #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
* Apache

**Comment by arouiadib** [comment] 2021-06-12 12:39
Not sure about the "throws errors every now and then."

Did you tried to disable ps_metrics? this issue seems related to cache of this module.


what about deleting /var/cache?

**Comment by eveneme** [comment] 2021-06-12 16:11
i tried, problem occurs later with other things.

**Comment by kpodemski** [comment] 2021-06-12 16:18
All these issues have been fixed in latest release of ps_metrics, not sure if it's released to public yet but as for now you can just change `modules/ps_metrics` to `modules/ps_metrics_OFF` to fix it

**Comment by eveneme** [comment] 2021-06-12 16:28
Ok, what about the cache? When cleaning the cache in the admin panel, an error 500 crashes, Hosting hands says that it is prestashop fault and presta itself is not came

sob., 12 cze 2021, 18:18 użytkownik Krystian Podemski <
***@***.***> napisał:

**Comment by hibatallahAouadni** [comment] 2021-06-14 07:07
Hello @eveneme 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem or a server problem.

Could you please post your issue in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack), so the developers help you with your problem.

We will close this issue.

PS: @kpodemski @arouiadib thanks guys for your quick replies.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-14 07:07 UTC
Labels: Can't reproduce
