### ISSUE TITLE
Wrong tax breakdown with an offered product and different tax rates

### ISSUE THREAD

**Issue by RHermant** [PrestaShop/PrestaShop#23647] opened 2021-03-15 09:58 UTC
#### Describe the bug

The amount of the offered product is deducted proportionally from all the totals in the taxes details on the invoice, not only from the line of the corresponding tax rate. 

#### Expected behavior

The amount of the offered product should only be deducted from the corresponding tax rate line. 

**Screenshots**

<img width="669" alt="capture-2021-03-15-10 45 01-AM" src="https://user-images.githubusercontent.com/15588179/111134247-b63f3780-857b-11eb-9890-35eb1f5cd820.png">

Here the product "Peluche I love you" is offered, so the "20% tax rate" line total should be 0€, and the "5.5% tax rate" total should be 9,28€.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-03-15 10:56
Hello @RHermant 

Could you please provide steps to reproduce the issue.
Please notify me when you add the steps :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-04-05 17:21
Hello @RHermant ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-05 17:21 UTC
Labels: Bug, CO, Order, Invoices, Email, Taxes and Prices, No change required, 1.7.6.4
