### ISSUE TITLE
Product price_final on product_list.tpl PS 1.7.6

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#17356] opened 2020-01-25 14:47 UTC
**To Reproduce**
1. Go to BO -> Catalog -> Products
2. Check both price columns, are the same. First column must be price without discount and second column price with discount applied.

I've tried this but nothing:
https://www.webempresa.com/foro/administracion-prestashop/backoffice-catalogo-productos-visualizacion-precios-antes-y-despues-del-descuento

**Comment by rmilecki** [comment] 2020-01-25 21:50
> 2. First column must be price without discount and second column price with discount applied.

This isn't correct. The first price is without tax, the second one with it.

Discounts are completely different thing and they can't be presented in "Products" as they may depend on a lot of conditions and may vary.

**Comment by omar2886** [comment] 2020-01-25 22:50
Understood. But before upgrading to 1.7.6 I used to have 1st column as final price (tax inc) and 2nd  column as the final price with the special promo/discount that it's active at that moment for that particular product on the tab price (Final price - promotional discount). How can I do to have it back like it used to be?

**Comment by khouloudbelguith** [comment] 2020-01-27 09:06
Hi @omar2886,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14091 to fix the issue.
Your ticket is a duplicate of #13731
So, I close it.
PS: about the new feature "Add final price column in products list" => it is added by this PR: https://github.com/PrestaShop/PrestaShop/pull/11484 as reported: #11479
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-27 09:06
Duplicate of #13731

**Closed as completed by khouloudbelguith** 2020-01-27 09:06 UTC
Labels: Duplicate, Taxes and Prices

**Comment by omar2886** [comment] 2020-01-27 11:30
Unfortunately this is not the case I'm talking about. I've already checked those codes and doesn't work for me, I also cleared cache from BO and no changes.
Thanks

**Comment by khouloudbelguith** [comment] 2020-01-27 12:16
@omar2886, 
>Check both price columns, are the same

I did not manage to reproduce the issue with PS1.7.6.3
![image](https://user-images.githubusercontent.com/16067358/73174082-289a5180-4107-11ea-977c-7c33e92843da.png)
The first column is `Price (tax excl.)` & the second column is `Price (tax incl.)`.

Thanks!

**Comment by omar2886** [comment] 2020-01-27 16:15
Yes thanks, that may be right, but the thing is that it doesn't  take into consideration que discounts applied to that product.
What I need it our employees to be able to see in product-list the final price at that moment (Tax inc - discounts), so they don't have to use the FO to check the price of each product (also because they can't see the price tab in product.tpl on BO)

**Comment by khouloudbelguith** [comment] 2020-01-27 16:31
@omar2886, but this is the behavior specified by our Product team: "Do not use specific prices when displaying price with tax in BO product catalog".
If you remove this fix: https://github.com/PrestaShop/PrestaShop/pull/14091/files
The Price (tax incl.) in the BO => Product list page is displayed after applying a discount
Before:
![image](https://user-images.githubusercontent.com/16067358/73193369-c3f0ee00-412a-11ea-9303-5ad62f048e3e.png)
After:
![image](https://user-images.githubusercontent.com/16067358/73193391-cb17fc00-412a-11ea-8c8f-f50dab0a64ec.png)
FO
![image](https://user-images.githubusercontent.com/16067358/73193432-db2fdb80-412a-11ea-8c5d-5b97de64bc1e.png)

Thanks!

**Comment by omar2886** [comment] 2020-01-29 10:15
THANK YOU!!!
