### ISSUE TITLE
Cannot build a `Doctrine\DBAL\Connection` during module installation

### ISSUE THREAD

**Issue by fedetibaldo** [PrestaShop/PrestaShop#21112] opened 2020-09-23 08:26 UTC
#### Describe the bug

I tried in many ways, but everything boils down to the same issue: for some reason, when I instantiate the `Doctrine\ORM\EntityManager` service, the Prestashop `Container` throws a fatal error:

```
> PrestaShop\PrestaShop\Core\Foundation\IoC\Exception { …},"command" => "prestashop:module install mymodule","message" => "Cannot build a `Doctrine\DBAL\Connection`."]

In Container.php line 121:
                                              
  Cannot build a `Doctrine\DBAL\Connection`.  
                                              
```

#### Expected behavior

I expect to be able to use Doctrine's entity manager and repositories during installation. When asking the container for the EntityManager, I'd expect it to be readily available.

#### Steps to Reproduce

1. [Create a new module](https://devdocs.prestashop.com/1.7/modules/creation/)
2. In the install method, paste the following lines:
```php
<?php
$em = $this->get('doctrine.orm.entity_manager');
return $em; // false
```
Or do the following:
```php
<?php

// ...

use Doctrine\ORM\EntityManager;
use PrestaShop\PrestaShop\Core\Foundation\IoC\Container;

class MyModule extends Module
{
    /**
     * @var Container
    */
    private $container;

    public function __construct (
        Container $container
    ) {
        $this->container = $container;
        // ...
    }

    public function install()
    {
        $em = $this->container->make(EntityManager::class); // throws error
        // ...
    }

    // ...
}
```
Or even this:
```php
<?php

// ...

use Doctrine\ORM\EntityManager;

class MyModule extends Module
{
    /**
     * @var EntityManager
    */
    private $em;

    public function __construct (
        EntityManager $em // throws error
    ) {
        $this->em = $em;
        // ...
    }

    // ...
}
```
3. Install the module (`php bin/console prestashop:module install mymodule`)
4. See the error (cases 2 and 3) or watch it die (case 1)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2
* Symfony 3.4.26 (kernel: app, env: dev, debug: true)

**Comment by PululuK** [comment] 2020-09-23 08:36
Hi @fedetibaldo 

See https://github.com/PrestaShop/example-modules/blob/master/demodoctrine/demodoctrine.php If you want to use doctrine in a module, maybe this can help you !

Thanks !

**Comment by SimonGrn** [comment] 2020-09-23 09:18
Hello,
@PrestaShop/prestashop-maintainers could you take a look at this one ? Is this the normal behavior ?

Thanks

**Comment by fedetibaldo** [comment] 2020-09-23 11:57
@PululuK Your link does shine a new light on the issue. As it has been commented in the `PrestaShop\Module\DemoDoctrine\Database\QuoteInstaller` class, one can't use Doctrine entities on install because the mapping is not available yet.

Is a direct query the only viable option?

https://github.com/PrestaShop/example-modules/blob/51bf2833e3c363f433a6fc3bbecb08fa446de177/demodoctrine/src/Database/QuoteInstaller.php#L19

**Comment by PierreRambaud** [comment] 2020-09-23 12:28
Hi guys,

I agree with @fedetibaldo, the Doctrine container and how doctrine must be used to create tables is not available yet during the installation of the module.Currently, the "best" way to use doctrine in module is to check how the demodoctrine module works.

But anyway, @fedetibaldo can you provide us a little module to reproduce the problem and we will do our best to try to fix it :)

**Comment by fedetibaldo** [comment] 2020-09-24 08:08
Sure thing! I'll put something together over the course of the weekend.

**Comment by hibatallahAouadni** [comment] 2020-11-27 10:14
Hello @fedetibaldo 

Is there any news about your issue? 
if no, we need to close this ticket to avoid cluttering up the backlog.

Thanks!

**Comment by fedetibaldo** [comment] 2020-11-27 19:36
I don’t have much time lately, and I don’t think I’m going to use Prestashop anytime soon either. Nonetheless, this issue has been confirmed by one of your contributors and is quite extensively documented. The step-by-step description should confirm its validity.

If you’d rather close this issue because of a missing reproduction on my part, then go ahead. This won’t make it any less of a bug, though.

**Comment by hibatallahAouadni** [comment] 2020-11-30 08:46
Hello @fedetibaldo 

We won't close it.
>can you provide us a little module to reproduce the problem and we will do our best to try to fix it

We just need you to respond to @PierreRambaud request please, so we can fix it.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-21 10:48
Hello @PierreRambaud 

> Sure thing! I'll put something together over the course of the weekend.

I believe @fedetibaldo is still busy, so what we should do? close it? or change the label to TBR?

**Comment by hibatallahAouadni** [comment] 2021-12-16 15:04
Hello everyone,

Due to inactivity of this issue (it's been a year) I'm closing this issue.

Thanks for your understanding :pray:

**Closed as completed by hibatallahAouadni** 2021-12-16 15:04 UTC
Labels: Improvement, CO, 1.7.6.7, Invalid
