### ISSUE TITLE
After 1 click Update: Various backend Tabs not reachable - Errors

### ISSUE THREAD

**Issue by Leo-pold-02** [PrestaShop/PrestaShop#16282] opened 2019-11-05 15:40 UTC
**Describe the bug**
After a Upgrade using 1 click update from 1.6. to 1.7.1. i cant acsess the :
Orders/Orders tab 
International/Localisation 
Stats
Shop Paramerters/General
Shop Paramerters/Order settings
Shop Paramerters/Customer Settings/Titles
Advanced Parameters/Administration
in backend. 

**Errors:**
On Orders it displays Acsess denied

On Customers it display a redirect issue or sometimes an issue (screeshot)

On Localisation it just returned to Dashbord without an error. 

On Stats: Acsess Denied

On Shipping/Preferences: Back to dashboard or error message
"Notice on line 101 in file /www/htdocs/w012ad27/shop2019.neuvonfrisch.de/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php
[8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/tmp/phpfpmsessions/) failed: Permission denied (13)"

Shop Paramerters/General back to dashboard with no error

Shop Paramerters/Order settings back to dashboard with no error

Shop Paramerters/Customer Settings/Titles: Accsess denied

Advanced Parameters/Administration back to dashboard with no error

**To Reproduce**
1. Go to Backend
2. Click on Orders or Localisation

**Screenshots**
https://ibb.co/Wf4dzxR
This error happens once and a while and also at customers/Customers tab

**Additional information**
PrestaShop version: 1.7.6.1.
PHP version: 7.1.
All Modules Uptodate

Would realy appreciate your help. Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-05 15:46
Hi @Leo-pold-02,

For the access denied page => you need to remove 'ps_access' table and restore 'ps_access' from 'clean' DB to solve your issue.
About the Customer Tab issue, it is a permission issue => you need to check it with your host.
You can navigate to your BO => Advanced Parameters => Information => Check your configuration => Required parameters: OK/NOK.
Thanks to check & feedback.

**Comment by Leo-pold-02** [comment] 2019-11-05 16:20
Hi @khouloudbelguith  
Thanks for the quick answer! Amazing!

Could you help me with doing the database thing, im not a experienced database user, however i have a second copy with a clean PS 1.7. install in a diffretn subdomin runnig right now so shgould be easy to get teh clean DB files. 
What instructions should i folow so i dont break anything crutial?

Customer Tab, ok i can check with my host and see if they have an idea - is there seomthing i can show them? The screenshot should work right? 

So the localisation and other errors would be fixed with the clean DB import? 

Required and Optinal Parameters are both on OK.

Thanks!
Leo

**Comment by khouloudbelguith** [comment] 2019-11-05 16:30
@Leo-pold-02,
>Could you help me with doing the database thing

You need, for example, install new PrestaShop v1.7.6.1 with your same configuration.
Export the new ps_access table
Import it in the your Old Database
Please make a back up before these changes, let's be safe!
>Customer Tab, ok i can check with my host and see if they have an idea - is there seomthing i can show them? The screenshot should work right?

yes!

**Comment by Leo-pold-02** [comment] 2019-11-05 16:43
Thanks. 
1 I Exported a clean ps_Accsess database from a virgin build thr myPhp. 
2 Went in the current running database with the errors in my PHP, deleted "drop tabels" of the ps_Accsess.
3 importat the ps_accsess DB file thru my php in the database. 
4. ps_acsess is there again. but i cant acsess hte backend anymore 
:( - im very confused now. please help.
Error:
https://ibb.co/LQ1qWj8
DB in myPHP
https://ibb.co/8j8ww0p
Ps_Accsess Table (does not look right does it?)
https://ibb.co/JkJSNNg

**Comment by Leo-pold-02** [comment] 2019-11-05 16:50
btw: i had the virgin prestashop running at php 7.2. and the new one (with all my data that i try to fix at) php 7.1

**Comment by Leo-pold-02** [comment] 2019-11-05 16:58
i did a complete new presta instalation of 1.7.6.1. on a new subdomain again. 
This time something strange happend the database is not starting the tables wit ps_ but with r2gDF_ the r2gDF_accsess contain 756 tabels. The one i hab used before only 419 tabbles. This confuses me again. im sorry!

this is the new virgin database now:
https://ibb.co/kQXzBh2

**Comment by khouloudbelguith** [comment] 2019-11-06 08:33
@Leo-pold-02, you need to install the new version PS1.7.6.1 with same configuration ( same prefix with your old one)
![image](https://user-images.githubusercontent.com/16067358/68281601-5461ea00-0078-11ea-8897-49b28960ab7a.png)

Please make a back up before these changes, let's be safe!
In your old database without any changes thanks to Run a query on `ps_access` table > SQL
`INSERT INTO ps_access (id_profile, id_authorization_role) SELECT 1, id_authorization_role FROM ps_authorization_role;`


Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-06 11:51
@khouloudbelguith Thanks again for your answer! 

does the same configuration mean: just the prefix, or also the theme and all the modules etc? 

I will try again once i have the info what sam config means. 

Once i have the new clean database in my php admin: 
1. i export the ps_Acsess in the clean install database
2. i clean the ps_acsess table in the shop with errors
3. i import the clean ps_acsess table in the shop database with errors
4. done?

What is the query command for? When will i need to perform it? 
Really appreciate your help, thanks a lot!
Leo

**Comment by Leo-pold-02** [comment] 2019-11-06 13:01
My Backend is running again! Thanks a lot for your help @khouloudbelguith !

Would i still need to run that query and what will it do?

Best
Leo

**Comment by khouloudbelguith** [comment] 2019-11-06 13:16
@Leo-pold-02,
>Would i still need to run that query and what will it do?

No, it is a second solution.

Since it is fixed, I close the issue, Feel free to open a needed.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-06 13:17
Duplicate of #9513

**Comment by Leo-pold-02** [comment] 2019-11-06 13:28
@khouloudbelguith im sorry its me again. i realised that the modules that came with my theme are not accessible any more after the DB transfer. 
I get an Access denied all the time. 
Is there something i need to change in the virgin database so that does not happen?

Best
Leo

**Comment by khouloudbelguith** [comment] 2019-11-06 13:31
@Leo-pold-02, yes, the second solution is to run this SQL request on your first Database
`INSERT INTO ps_access (id_profile, id_authorization_role) SELECT 1, id_authorization_role FROM ps_authorization_role;`

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-06 13:51
Hello, 
Well at the moment the in old(updated) database the ps_accsess contained only 419 taels the new ps_acsess contains 756 Tabels. 
Why would this affect the backend modules and tools that came with my theme? Is there a way to fix that issue without returning to the old small database? 
Would i need to install the theme and all modules on the virgin build exactly the way i have it on my undated shop before i transfer the ps_Accsess?

**Comment by khouloudbelguith** [comment] 2019-11-06 13:58
@Leo-pold-02, so, you need to check the `ps_authorization_role` table, you have all `id_authorization_role` defined in the `ps_acsess` table.
So, I think, you have missing `id_authorization_role` in the table `ps_acsess` which are available in the `ps_authorization_role` table.

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-06 14:29
@khouloudbelguith  Thanks for the quick reply. 
In Ps Acsess i have the table ps_authorization_role and it seems like there is a value for each line.

https://ibb.co/M5Q6MzT

Or did i not understand you right? Sorry im really a noon in database stuff. Tanks aa lot for your help. Leo

**Comment by khouloudbelguith** [comment] 2019-11-06 15:43
@Leo-pold-02, what are the exact pages which you have access denied?

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 08:14
@khouloudbelguith 

Its only the backend tools and Modules that came with the thme that i need to configure the thme that are not acsessible right now.
The pages are Called: AP Page builder, Leo-Blogmanagement, and Leo-Thememanagement. 

Would it maybe help to swich back to the default theme, and than back to the at-oreo theme i want to use? Or would i need to correct the database for that?

Thanks!
Best
Leo

**Comment by khouloudbelguith** [comment] 2019-11-07 08:20
Hi @Leo-pold-02,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 08:22
OK such a bummer, everything looked fine until i wnated to work on the design again. 
Unfortunatly i uninstalled the default theme that came with the virgin PS build. Is there a way to get the default theme back? Where could i download it to reinstall it?

Do you think the issue accured cause in my cirgin prestashop build i hat the theme installed but not actiated/assigned? would it help to try to get another virgin prestashop build, install the theme on it and than export and replace the ps_accsess again? 
If i do so would i need to also install all modules i have at the moment on the virgin build before the export?

Best
Leo

**Comment by khouloudbelguith** [comment] 2019-11-07 08:30
@Leo-pold-02, here's a classic theme
[classic.zip](https://github.com/PrestaShop/PrestaShop/files/3818561/classic.zip)
Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 08:31
Thanks!
Do you think my approach could work? 
Best
leo

**Comment by Leo-pold-02** [comment] 2019-11-07 08:36
@khouloudbelguith 
Installation worked. But i tried swiching back to the default classic Theme but i cant it gives me a "you do not have persmision to do that" error.

https://ibb.co/BnDpgN4

Is there a way to fix that?

**Comment by khouloudbelguith** [comment] 2019-11-07 08:40
@Leo-pold-02,

>Do you think the issue accured cause in my cirgin prestashop build i hat the theme installed but not actiated/assigned? would it help to try to get another virgin prestashop build, install the theme on it and than export and replace the ps_accsess again?

Yes, it could help you with this solution.
Also, you can change the theme of your shop, in your table ps_shop, theme_name
![image](https://user-images.githubusercontent.com/16067358/68373161-96eff900-0142-11ea-97da-a5b4115541d3.png)

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 09:02
Thanks @khouloudbelguith 
What do you think is the best approach to get my shop with the theme i want back up and running?

1. Try to activate the default clasic theme, and after switch back to the theme i bought? 
(i cant install the classic theme for the you do not have persmision to do that" error. - would i avoid that error by switching the theme in the database like sugested? - do oyu think that could fix the issue i have with the theme?)

2. Try to set up a new virgin build with the theme i want. 
Export the ps_acsess of the cirgin shop to the DB of the shop i want to use. 
Would i need to exactly match the modules installed on both themes?
What else would neet to be matched? (SSL config, etc?)
Did i miss anything?

Appreciate your help!

**Comment by Leo-pold-02** [comment] 2019-11-07 09:27
I tried route nr.2. and imported the ps acsess again from a virgin PS build, this time i installed the theme of chice, and matched all the modules to be exactly the same.
But i still have the same issues: i cant switch the theme in backend and i cant scsess all the tools of my theme. 
I dont know what else to do :) please help me. thanks!

**Comment by khouloudbelguith** [comment] 2019-11-07 09:34
@Leo-pold-02, you are a super admin is it?
![image](https://user-images.githubusercontent.com/16067358/68377111-1df49f80-014a-11ea-9aa6-b5fb36708c0f.png)

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 09:38
yes.

![Bildschirmfoto 2019-11-07 um 10 37 23](https://user-images.githubusercontent.com/57262480/68377420-a1ae8c00-014a-11ea-893f-142e0249c797.jpg)

If i click on team/ employes / permsions i get this error:


i tried empty the cache in the backend. but it is the same error.

**Comment by khouloudbelguith** [comment] 2019-11-07 09:40
@Leo-pold-02, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by Leo-pold-02** [comment] 2019-11-07 09:48
did that now, still the same issue, if i acsess team/ employes / permsions i get this:



And i still cant change the theme in the backend under design / theme & logo.

**Comment by khouloudbelguith** [comment] 2019-11-07 09:51
@Leo-pold-02, thanks to follow this comment: https://github.com/PrestaShop/PrestaShop/issues/12126#issuecomment-454349802, I think, it is similar to your issue.

Thanks to check & feedback.

**Comment by Leo-pold-02** [comment] 2019-11-07 10:08
@khouloudbelguith i did contact my host they changed the file, but they said they would not recomend doing this ? is that somehow dangerous?

The file looks like this now:

```
# Apache 2.2
#<IfModule !mod_authz_core.c>
#    Order deny,allow
#    Deny from all
#</IfModule>

# Apache 2.4
#<IfModule mod_authz_core.c>
#    Require all denied
#</IfModule>
```

But the error is still the same, i cleaned cache manually again as well
Best
leo

**Comment by khouloudbelguith** [comment] 2019-11-07 10:25
@Leo-pold-02, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 10:31
sure:

[log.txt](https://github.com/PrestaShop/PrestaShop/files/3819091/log.txt)

**Comment by khouloudbelguith** [comment] 2019-11-07 10:36
@Leo-pold-02, just question, your theme is compatible with PS1.7?
Because the theme used in the PS1.6 is not used & compatible with PS1.7.
There is a huge difference.

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 10:43
@khouloudbelguith 

Yes, we bought a new theme(at-oreo by leo-themes) just for that that is compatible with the 1.7. PS version. I have it running on the virgin build with no issues. 
But i dont have our products, customers, orders, cariers and such in the virgin build. Thats why i want to use the updated shop.

In terms of the update: 

in 1.6.
On backup of the shop
Change theme to default
Upgrade php
Deactivate modules
Upgrade store to latest 1.6
Upgrade php
Upgrade store to 1.7
Check
Install theme
-
it worked fine until i ran into the issues i described in this case. 

Than i transfered the ps_accsess from the virgin build with the theme and modules installed. 
And now i cant acsess the theme modules anymore. Butr i also cant change the them in the backend and i cant delete the theme in the backend as well.

**Comment by khouloudbelguith** [comment] 2019-11-07 11:21
@Leo-pold-02, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 11:38
Sure its strange i cant find the required php error log under var/logs - there is only a dev.log and a prod.log file - no subfolders! 
I did read the article but it does not point out where i find the debug mode report. im sorry. could you please tell me where to find it.


Really appreciate your help! 

![Bildschirmfoto 2019-11-07 um 12 37 13](https://user-images.githubusercontent.com/57262480/68386042-7d0ee000-015b-11ea-932a-a09b392c9a4c.jpg)

**Comment by Leo-pold-02** [comment] 2019-11-07 11:44
Another question, and 2 creative aproaches to solve the issue.

1. maybe it would be easyer to transfer the images, products, carriers and so on over to the virgin build ? is that somehow possible or would this require a lot of manual work? Or could i just copy folders over?

2. Maybe there is a way to manually uninstall the at_oreo theme that i bought and its modules and reinstall it again so the modules of the thme will get installed and get new permissions. 

Just trying to offer idas for a creative approach. If there is an easyer way of just fixing the database i would be very happy too! 
Thanks again @khouloudbelguith you are a legend!

**Comment by khouloudbelguith** [comment] 2019-11-07 13:08
@Leo-pold-02, 

>I did read the article but it does not point out where i find the debug mode report. im sorry. could you please tell me where to find it.

You need to navigate to your BO => Advanced Parameters => Performance => Enable debug mode 
![image](https://user-images.githubusercontent.com/16067358/68391359-bc432e00-0167-11ea-8ed8-5968dea8bc70.png)

No, when you access to the theme & logo page => is there any exception displayed?

Retreiving the bug report & error log file, could help us to understand the exact issue & how to solve it.

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 13:17
Hey, im sorry the debug mode is activated since days. 
I have the debug bar in the browser at the bottom as well.

Acsessing theme&Logo isn o problem. 
Only if i want to change the theme it gives me "You do not have permission to edit this." 
Also the Homepage Configutation and Advanced customistation tabs under Theme are not accsessible. 
Still no pho error file in the var/logs.
Best
Leo

**Comment by khouloudbelguith** [comment] 2019-11-07 13:20
@Leo-pold-02, You need to enable debug mode in your store and debug request which is sent for theme change in your browser, using DevTools, so:

1. enable debug mode
2. go to the Theme & logo page
3. open up developer tools
4. go to Network tab
5. change the theme
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 13:32
thanks. About 3. by developer tools you mean the bar at the bottom of the page (symphony profiler)? 

In this i only find 3 issues:
![Bildschirmfoto 2019-11-07 um 14 30 22](https://user-images.githubusercontent.com/57262480/68393032-5eb0e080-016b-11ea-9525-8ffd5e58eda9.jpg)
![Bildschirmfoto 2019-11-07 um 14 30 16](https://user-images.githubusercontent.com/57262480/68393033-5f497700-016b-11ea-9106-b280a638d943.jpg)
![Bildschirmfoto 2019-11-07 um 14 29 59](https://user-images.githubusercontent.com/57262480/68393034-5f497700-016b-11ea-8b44-dbfba31a6bab.jpg)

**Comment by khouloudbelguith** [comment] 2019-11-07 13:37
@Leo-pold-02, open the console, you can follow this link to know how to open the console tab.
https://kb.mailster.co/how-can-i-open-the-browsers-console/

Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 13:40
ReferenceError: $ is not definedadmin.js:19:1
    <anonym> https://_shop.xxxx.de_/modules/amzpayments/views/js/admin.js:19

**Comment by khouloudbelguith** [comment] 2019-11-07 13:42
@Leo-pold-02, this error is related to the amzpayments module.
As it's not a module provided by Prestashop, we can't do anything with this.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Leo-pold-02** [comment] 2019-11-07 13:42
so i unstalled amazon pay plugin and now there is no error in the console but still the same issue

**Comment by Leo-pold-02** [comment] 2019-11-07 13:46
in the network anaytics tab i get this

![Bildschirmfoto 2019-11-07 um 14 44 44](https://user-images.githubusercontent.com/57262480/68393995-58236880-016d-11ea-8883-0ee63e4f3490.jpg)

**Comment by khouloudbelguith** [comment] 2019-11-07 13:50
@Leo-pold-02, the issue is related to the permission issue to your employee.
So, thanks to creat a new profile with all permissions (pages & modules)
Create a new employee with this new profile, check & feedback.

**Comment by Leo-pold-02** [comment] 2019-11-07 13:57
hey @khouloudbelguith 
BABÄM - i did a diffrent approach and copied teh ps_accsess and teh ps_autentification_role from the virgin database over to the existing one and so far that seems to have fixed teh issues! 
I want to thank you so mutch for helping me out and taking the time to fix this with me! 
a big hug to you! 

Fingers crossed that im not runnign into a new issue in 2 minutes :)

**Comment by khouloudbelguith** [comment] 2019-11-07 14:00
@Leo-pold-02, Great!
I'm happy that you solved the issue.
I close the ticket, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-07 14:00 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.6.1
