### ISSUE TITLE
Location field import/export

### ISSUE THREAD

**Issue by Ybeske** [PrestaShop/PrestaShop#10874] opened 2018-10-05 11:41 UTC
### Describe the bug
I'm very happy the product "Location" field finally got visible again for the first time since the last version of 1.6.
The only thing I miss to really enjoy this feature is to make the field possible with the import function.

In the right column of "Advanced Parameters / Import" the "Available fields" for Products are mentioned. The Location field is missing.

Can you please add it to the right column in the BO interface "Available fields" and to the possible merge fields during the import procedure (if not possible already - I cannot test it in the virtual environment)?

Maybe it's a good idea to also add the Location field to the "Sample Products file"... at the "Download sample csv files" area.

### Steps to reproduce

1. BO>COnfigure>Advanced parameters>Import
2. In the right column of "Available fields" for Products are mentioned :heavy_check_mark: 
3.  The Location field is missing :x: 

**Screenshots**
![location field missing](https://user-images.githubusercontent.com/43880279/46533260-3b4e9e80-c8a4-11e8-8241-d9c289e9f060.jpg)

### Additional infos

- PS version: 1.7.5.0 & 1.7.6.0 & 8.0.4
- PHP version: 7.2 & 8.0

**Comment by khouloudbelguith** [comment] 2018-10-08 09:32
Hi @Ybeske,

Thanks for your report.
We are aware of this issue, in fact, the download sample CSV files is not updated with the new fields.
Your ticket is a duplicate of #9764
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-08 09:32
Yes, you are right.
Stock location is back, but this field is not added to the list of import.
https://github.com/PrestaShop/PrestaShop/pull/10422
Related to #9764
We will see how to fix it.
Thanks!

**Closed as completed** 2024-11-22 10:41 UTC
Labels: Feature, BO, Import / Export
