### ISSUE TITLE
Swift Mailer Issue

### ISSUE THREAD

**Issue by simulbeni** [PrestaShop/PrestaShop#12154] opened 2019-01-14 17:42 UTC
![capture](https://user-images.githubusercontent.com/437314/51129919-bfc09e00-1851-11e9-97e0-29648354eeb9.PNG)
Prestashop 1.7.4.2 was working well and after upgrade shop 1.7.5.0 email issue started.

There is no know issue i can see in any kind of forum related to this 
Please help us out

**Comment by rdy4ever** [comment] 2019-01-15 08:41
Actually, there are. You just need to search for closed issues, as this issue is fixed by #11995 (merged in the next patch release - 1.7.5.1). Just replace `classes/Mail.php` with the one provided by the mentioned PR and your problem will be solved.

**Comment by khouloudbelguith** [comment] 2019-01-15 11:21
Hi @beniwal,

We manage to reproduce the issue.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11995 to fix the issue.
Your ticket is a duplicate of #11933
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-15 11:21
Duplicate of #11933

**Closed as completed by khouloudbelguith** 2019-01-15 11:21 UTC
Labels: Duplicate

**Comment by simulbeni** [comment] 2019-01-15 11:24
I found the solution before response from here but this is good that respose came so quick.

We must have php module "idn_to_ascii" or need to modify little bit Mail class "mail.php".

thanks for response.
