### ISSUE TITLE
PHP Fatal error:  Uncaught ICanBoogie\\CLDR\\ResourceNotFound: Path not defined

### ISSUE THREAD

**Issue by paugnu** [PrestaShop/PrestaShop#14341] opened 2019-06-24 10:23 UTC
**Describe the bug**
Install Prestashop 1.7.5.2. Enable the English language as a second optional language for the shop. My browser is in 'Catalan' language (locale: ca-ES). When I try to switch to English site, I get a 500 error, the problem is:

`[Mon Jun 24 11:57:40.245809 2019] [proxy_fcgi:error] [pid 16954:tid 140160054236928] [client 81.42.232.43:34213] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ICanBoogie\\CLDR\\ResourceNotFound: Path not defined: main/ca-CA/currencies. in /var/www/vhosts/powerymax.com/httpdocs/src/vendor/icanboogie/cldr/lib/WebProvider.php:77\nStack trace:\n#0 /var/www/vhosts/powerymax.com/httpdocs/src/vendor/icanboogie/cldr/lib/ProviderChainTrait.php(43): ICanBoogie\\CLDR\\WebProvider->provide('main/ca-CA/curr...')\n#1 /var/www/vhosts/powerymax.com/httpdocs/src/vendor/icanboogie/cldr/lib/ProviderChainTrait.php(43): ICanBoogie\\CLDR\\FileProvider->provide('main/ca-CA/curr...')\n#2 /var/www/vhosts/powerymax.com/httpdocs/src/vendor/icanboogie/cldr/lib/Repository.php(124): ICanBoogie\\CLDR\\RunTimeProvider->provide('main/ca-CA/curr...')\n#3 /var/www/vhosts/powerymax.com/httpdocs/src/vendor/icanboogie/cldr/lib/Locale.php(164): ICanBoogie\\CLDR\\Repository->fetch('main/ca-CA/curr...')\n#4 /var/www/vhosts/powerymax.com/httpdocs/src/vendor/icanboogie/cldr/lib/LocalizedCurrency.php(58): ICanBoogie\\CLDR\\Locale->offsetGet('currencies')\n#5 /var/www/vhosts/powerymax...\n'`

**To Reproduce**
1. Set the locale of your browser to Catalan (ca or ca-ES)
2. Enable the English localization in prestashop as a secondary language
3. Try to access to the English shop
4. Error 500 is thrown

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.1

After debugging, I see that the problem comes from the fact that Prestashop is setting my locale to 'ca-CA'. When it tries to retrieve de locale configuration for 'ca-CA', it fails. The locale for my browser should be ca-ES, not ca-CA. That's a wrong assumption from prestashop and we get the 500 error because of that.

**Comment by khouloudbelguith** [comment] 2019-06-24 12:47
Hi @PauGNU,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0.
I attached a video record
https://drive.google.com/file/d/1k6VEiRNshRgQ63tW4vXv-p-pYdNVjIO_/view
Could you please navigate to your BO => International => Translations => Update the Catalan language & the English language.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-07-24 07:15
Hi @PauGNU,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-24 07:15 UTC
Labels: Bug, FO, Languages, No change required, 1.7.5.2

**Comment by tipui** [comment] 2020-07-03 05:49
Same problem here.
I solved the problem doing this:

 **- Advanced Parameters -> Performance**
Template compilation -> Force compilation
Click Save

**- Clear cache**
Wait finish

**- International -> Localization -> Languages**
The ISO Code for the new language must be "iso 3166-1 alpha-2" two letters
Language code must be ISO639-1 two letters or 4 letters with hifen (ie: "en-us" or "en")
Click Save

**- International -> Localization -> Localization ->  ADVANCED**
Language identifier: The code must be ISO639-1 two letters
Country identifier: The code must be "iso 3166-1 alpha-2" two letters
Click Save

**- International -> Localization -> Localization ->  IMPORT A LOCALIZATION PACK**
1. Localization pack you want to import: choose the country of the language
2. Unselect all options
3. Select only "States" and "Languages"
Click "Import" and wait finish
*Repeat this last step if you have others languages

Clear cache again.

Now, the front office should work.

In my opinion, this is a critical bug. 
We are in 2020/07 and the problem still persists.
PrestaShop team should review this bug to avoid future problems.

**Comment by ramwebkul** [comment] 2021-09-09 14:14
I have faced the same issue at my end and found this solution is working for me:

In `/vendor/icanboogie/cldr/lib/WebProvider.php`,  `line:70` after this line:

    curl_setopt($connection, CURLOPT_URL, $this->origin . $path . '.json');

Add this line:

    curl_setopt($connection, CURLOPT_FOLLOWLOCATION, true);
