### ISSUE TITLE
An unexpected error occurred when you try to modify any customer information after the import

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#24583] opened 2021-05-20 13:27 UTC
#### Describe the bug

Error `An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0]: Customer contains invalid field values` when modify and save customer information in BO. 

Error arrive because of invalid value of field `date_add" = 0000-00-00 00:00:00`.  If change this value to real date directly in DB, error disappear.  When we import customers, **Registration date** is used for `date_add`, so autodate is `false`, and `date_upd` is `0000-00-00 00:00:00`. Why not to set `date_upd` => `date('Y-m-d H:i:s')`, in `self::$default_values` in AdminImportController.php ?

#### Expected behavior

No error when save customer information.

#### Steps to Reproduce

1. Go to **Advanced Parameters** - **Import** , and import **Customers**. You can use sample **csv** file. 
2. Go to **Customers** page, open Edit customer page.
3. Try to save customer information. Not necessary to modify something.
4. See error `An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0]: Customer contains invalid field values`.
If customer is created directly in **BO** or **FO**, there is no such error.

**Screenshots**

![image](https://user-images.githubusercontent.com/4932192/118986011-44baa580-b97f-11eb-9f28-740801d7d474.png)

![image](https://user-images.githubusercontent.com/4932192/118986636-d0343680-b97f-11eb-80ca-ae7b6449bdcf.png)

#### Additional information

* PrestaShop version: 1.7.7.5 And 1.7.8.0
* PHP version: 7.3
* DB : Maria BD 10

**Comment by florine2623** [comment] 2021-05-21 08:50
Hello @202-ecommerce ,

I was able to reproduce the issue with PrestaShop version 1.7.7.4 and develop, so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-05-22 08:32
I need to check it if it's regression or not

**Comment by 202-ecommerce** [comment] 2021-05-24 07:37
Hello @hibatallahAouadni ,

I had this issue also on 1.7.6.9.

**Comment by hibatallahAouadni** [comment] 2022-03-08 15:42
Hello @202-ecommerce & @florine2623 

Following the steps to reproduce, I didn't manage to reproduce the issue with PS1767, PS1778, PS1780 and develop. 
Check the attached screen record below:

https://user-images.githubusercontent.com/23308427/157272042-28def524-186d-4706-8400-c088c5454fee.mp4

Did I miss something? :pray: 
Please check and feedback.

Thanks!

**Comment by kgleizes** [comment] 2022-03-09 08:48
Hello,

Please consult the attached files to reproduce it. 

This bug only appears when customers are imported with the 'Registration date' information.
When this information is not selected to be imported, there is no bug to display

https://user-images.githubusercontent.com/98040531/157405673-365dfb00-02d0-4bfc-bb92-c68f0eee8800.mp4

[customer-import-test.csv](https://github.com/PrestaShop/PrestaShop/files/8213099/customer-import-test.csv)
.

**Comment by hibatallahAouadni** [comment] 2022-03-10 18:22
Hello @202-ecommerce & @kgleizes 

Thanks for the details :pray: 
I reproduce the issue with PS1778, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/157729318-6d3e3a0c-5ed7-4ed5-be00-b89a30386538.mp4

Even when I change the registration date from `dd-mm-yyyy hh:mm:ss` to `dd-mm-yyyy`, the issue always persist.
Thanks again for your PR :rocket: 

Thanks!

**Closed as completed** 2022-03-25 13:22 UTC
Labels: Bug, Major, BO, Customer, Import / Export, Fixed, PR available, 1.7.6.9, Verified
