### ISSUE TITLE
[BO][LEGACY][LIST] The status name is not visible in the listing when the colors field is empty.

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#21280] opened 2020-10-03 14:13 UTC
## Is your feature request related to a problem?

The status name is not visible in the listing when the colors field is empty.

## Describe the solution you'd like

Define a default color when the colors field is empty.

| Before      | After |
| ----------- | ----------- |
| ![94993029-64d35b00-058e-11eb-8940-c4c120b5a35d (1)](https://user-images.githubusercontent.com/16455155/94993104-eaefa180-058e-11eb-8aaa-f3633a58eaaf.png) | ![image](https://user-images.githubusercontent.com/16455155/94993156-46ba2a80-058f-11eb-9e10-d879c975e4dd.png)|

## Alternatives you've considered

The color field must be required in `OrderState` and `OrderReturnState` objects definition :

```php
'color' => [
 'type' => self::TYPE_STRING, 
 'validate' => 'isColor',
 'required' => true // Here
],
```
⚠️  This may introduce BC. Ex.: _imagine modules that create statuses without the color field_

### 🎥 [Click to see screen record](https://drive.google.com/file/d/1tcLhaUrs91xl4ylIsGH4G1gomwfD1up_/view)

**Comment by khouloudbelguith** [comment] 2020-10-05 08:09
Hi @PululuK,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/95054751-a2e98f80-06f2-11eb-9515-e08dd9dea077.png)
But this issue will be fixed in the next release 1780 during migration.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/20442 to fix the issue.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/20441
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-10-05 08:09
Duplicate of #20441

**Comment by PululuK** [comment] 2020-10-05 11:04
> Duplicate of #20441

Thank you so much @khouloudbelguith 
I don't think it's the same issue  ... @matks  can you confirm please ? (see the screen record please)

**Comment by khouloudbelguith** [comment] 2020-10-05 11:20
@PululuK, thanks for your feedback.
The Expected behavior provided by @matks 
`You should not be able to submit the form without providing a valid value for the "color" field.`
In this case, we cannot create an empty color => so the status can't be empty.

Thanks!

**Comment by PululuK** [comment] 2020-10-05 12:05
> @PululuK, thanks for your feedback.
> The Expected behavior provided by @matks
> `You should not be able to submit the form without providing a valid value for the "color" field.`
> In this case, we cannot create an empty color => so the status can't be empty.
> 
> Thanks!

OK, thanks ! But does this apply to legacy controllers too 🤔 ?

**Comment by matks** [comment] 2020-10-05 12:52
Hi !

I think @PululuK is right: these issues are slightly different.

My topic is about **refusing people to create new order states with a not-valid color value**. So it's a validation introduced in the form that prevents the form submission.

@PululuK is rather implementing a fallback mechanism where, if there is no color available, provides a relevant fallback color.

=> one topic is "prevent people from creating bad data"
=> second topic is "handle bad data display once it has been put inside database"

Since order states can be created by different channels (for exemple using Webservice) I think we can accept this topic.

**Comment by PululuK** [comment] 2020-10-05 12:56
Exactly ... Thanks @matks! 
@khouloudbelguith  I'm sorry, I wasn't very clear !

**Comment by khouloudbelguith** [comment] 2020-10-05 13:30
Thanks, @matks & @PululuK.
I manage to reproduce the issue with PS1.7.6.8 and 1770rc1.
I’ll add this to the debug roadmap.

Thanks!

**Comment by florine2623** [comment] 2024-01-24 16:11
This is fixed on the migrated page on develop :)

<img width="1192" alt="Screenshot 2024-01-24 at 17 10 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a8a25cb7-ae14-4f82-a8af-76f10a48bb5f">

I'm closing this issue. Thanks!

**Closed as completed by florine2623** 2024-01-24 16:11 UTC
Labels: Bug, Minor, BO, Order, Order statuses, Fixed, PR available, 1.7.6.8, Verified
