### ISSUE TITLE
Voucher not rounded correctly, if added from order admin

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17596] opened 2020-02-11 10:39 UTC
**Conditions**
Currency - Czech Koruna, Kč, precision 0. (Precision need to be set in the database).
Decimal places in PS settings - 0.

**Bug description**
Order something through FO, apply a 15% discount voucher. Everything is rounded to whole numbers.

Order something through FO, do not apply anything. Order will be rounded to whole numbers.
Go to backoffice, edit the order, add the 15% discount manually. **The voucher will not be rounded => the order will not be rounded.**

**Cause**
There are 2 decimals hardcoded in AdminOrdersController.
![Výstřižek](https://user-images.githubusercontent.com/6097524/74229627-0f76d080-4cc3-11ea-8892-e2c4b601bd6b.JPG)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-02-11 11:07
Hi @Hlavtox,

Thanks for your report.
The first part of feature #[10052](https://github.com/PrestaShop/PrestaShop/issues/10052) is almost done which the implementation of the CLDR (the data needed to manage a maximum of currencies), Check the PR #10455

It's planned to remove the number of the decimal parameter in Shop parameters > General, as you can see here: #12223
And it's also planned to add this feature in CLDR part 2: #11660

Thanks to check & feedback.

**Comment by Hlavtox** [comment] 2020-02-11 12:10
@khouloudbelguith Thank you, but I went through the PR's and there is nothing changed in the code.

The new Symfony order admin is also using the same, bad, code: https://github.com/PrestaShop/PrestaShop/blob/7633be8294d90148d2bdfe3fd1c2d403e72ec91b/src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php

I have searched PS's code for other usage of ps_round function, and you either use `_PS_PRICE_COMPUTE_PRECISION_` or `$context->currency->decimals * _PS_PRICE_COMPUTE_PRECISION_`, what is the correct way?

**Comment by khouloudbelguith** [comment] 2020-02-11 12:24
@Hlavtox, in the next major release, the Order page is migrated to Symfony.
https://github.com/PrestaShop/PrestaShop/projects/3
We are still working on it.

Thanks!

**Comment by Hlavtox** [comment] 2020-02-17 10:11
@khouloudbelguith Do you think it will be fixed during the page migration? I don't think so... The code was just copied to /src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php and the bug still remains. I think it will be the same on the migrated order page in 1.7.7.

**Comment by khouloudbelguith** [comment] 2020-02-17 16:48
@Hlavtox, as explained here #12223
The number of the decimal parameter in Shop parameters > General.
So, in the PS1.7.7.0, we cannot set the number of decimals
![image](https://user-images.githubusercontent.com/16067358/74672084-cd5efa80-51ac-11ea-9fe7-a93cd8749185.png)
In the BO => International => Localization => currencies => Decimals =0
![image](https://user-images.githubusercontent.com/16067358/74672198-04cda700-51ad-11ea-88b3-bf3282aab449.png)
When we add a discount => OK
https://drive.google.com/file/d/1bAYKaYCKDNSreJUiw8BqdlaseKxoIO8U/view

The issue is fixed in PS1.7.7.0.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-17 16:48
Duplicate of #12223

**Closed as completed by khouloudbelguith** 2020-02-17 16:48 UTC
Labels: Bug, BO, Duplicate, Order, Currencies, 1.7.6.2

**Comment by Hlavtox** [comment] 2020-02-18 08:25
@khouloudbelguith Can you go to database and tell me total_discounts, after modifying the order?

Is it 161.25 or 161.00?
Is total_paid rounded to whole number as it should be or not?

Why do you mark it as duplicate when the related issue does not have anything common with this?????? I am talking about totals not rounding and you say it's a duplicate of issue where you discuss removing of decimal point?

@matks @PierreRambaud Can somebody look at this, please? I am starting to loose my nerves again.

**Comment by khouloudbelguith** [comment] 2020-02-18 10:38
Hi @Hlavtox,

I tried with the branch 1.7.7.x.

In the BO => Shop Parameters => General page => the `Round mode` = `Round up away from zero, when it is half way there (recommended)`
![image](https://user-images.githubusercontent.com/16067358/74728400-f8942900-5242-11ea-8260-19fa5fa6c525.png)

1. I created another order
![image](https://user-images.githubusercontent.com/16067358/74728061-6db32e80-5242-11ea-86ce-ae8f52b0536b.png)
2. In table `ps_orders`, the `total discounts = 129.630000`.
![image](https://user-images.githubusercontent.com/16067358/74728183-963b2880-5242-11ea-9b26-a9ee8b2463dd.png)

Thanks!

**Comment by Hlavtox** [comment] 2020-02-18 10:59
@khouloudbelguith And thats wrong, if you order it through front office and apply the 15% voucher there, it will be rounded. Total paid will be 735.000000 and total discounts 130.000000.

On thing is what employee sees and the second thing is what gets sent to payment gateways. The customer pays **734.57** instead of **735.00** as it should be and it immediately creates differences between the payment and the invoice from the financial software. More manual labour, additional rouding and complications on invoices, VAT calculation differences etc. etc.

**Comment by khouloudbelguith** [comment] 2020-02-18 13:16
@Hlavtox, 
>And thats wrong, if you order it through front office and apply the 15% voucher there, it will be rounded. Total paid will be 735.000000 and total discounts 130.000000.

I tried to create the order from the FO and the 15% voucher is added in the FO.
In the BO => Orders => Order details page, I have the same results.
I attached a second screen record
https://drive.google.com/file/d/1BrY4FXVVpkx4N9A3TzICuedxSRMXHeh3/view

Thanks!
