### ISSUE TITLE
Same background for multiple colorpickers

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#25013] opened 2021-06-18 00:23 UTC
#### Describe the bug

Multiple color pickers will have the same background color even though they have different color values

#### Expected behavior

Each input must have a different background color
<img width="604" alt="2021-06-18 at 1 21 AM" src="https://user-images.githubusercontent.com/793712/122487563-7a30ce00-cfd3-11eb-93ca-c341e8945a90.png">

Actual

<img width="588" alt="2021-06-18 at 1 21 AM" src="https://user-images.githubusercontent.com/793712/122487602-8fa5f800-cfd3-11eb-8304-743e952d1055.png">

#### Steps to Reproduce

You will need a PrestaShop backoffice page which has multiple color pickers, I'm not aware of any page having that.
I discovered the bug on my module page

#### Additional information

* PrestaShop version: 1.7.8.0

**Comment by florine2623** [comment] 2021-06-18 07:08
Hello @unlocomqx ,

As we're not able to reproduce this issue on the core of PrestaShop, it cannot be fixed.
The only area where there is this color picker is in Multistore mode :
<img width="554" alt="Screenshot 2021-06-18 at 09 05 32" src="https://user-images.githubusercontent.com/16019289/122520844-6e193080-d014-11eb-89c0-89fe6040313b.png">
But the color code is not mentioned.

I suggest you contact the develop of the external module to fix this.

Thanks!

**Comment by unlocomqx** [comment] 2021-06-18 07:15
It's not an external module, it's my module. And it used to work on the previous PrestaShop version.
On the PrestaShop backoffice, there are a lot of pages where a color picker is displayed
For example, in the attribute page or the order statuses page.. but I couldn't find a page where two color pickers are displayed
Do you know any?

**Comment by kpodemski** [comment] 2021-06-18 07:17
@unlocomqx I think it's a valid bug/feature rquest report, you should be able to use as many color pickers as you want on modern pages

@florian-202 I'd suggest to tag it as a `developer feature`, not a regular bugfix :)

**Comment by unlocomqx** [comment] 2021-06-18 07:21
The same bug is present in the module "Order Notifications on the Favicon" (a PrestaShop official module) in the main configuration page

<img width="765" alt="2021-06-18 at 8 20 AM" src="https://user-images.githubusercontent.com/793712/122522605-0f50b880-d00e-11eb-87a4-c2144916ae90.png">

**Comment by unlocomqx** [comment] 2021-06-18 07:25
Here's the result after applying the fix

<img width="752" alt="2021-06-18 at 8 25 AM" src="https://user-images.githubusercontent.com/793712/122523271-c0575300-d00e-11eb-9df2-085647832c43.png">

**Comment by hibatallahAouadni** [comment] 2021-06-22 06:37
https://drive.google.com/file/d/1dDTfBFZQmSazGPT2J-kj5rukWcssBAQR/view

**Comment by hibatallahAouadni** [comment] 2021-12-15 13:33
Hello everyone,

Following @PrestaEdit & @kpodemski request, I only reproduce the issue on PS1.7.8.0 and PS1.7.8.2.
So, It's a regression on PS1.7.8.0 and it should be fixed on 1.7.8.x.

Thanks!

**Comment by Progi1984** [comment] 2021-12-28 13:28
@hibatallahAouadni Done in #27114

**Closed as completed** 2021-12-29 10:34 UTC
Labels: Bug, Minor, BO, Modules, Regression, Fixed, Developer Feature, PR available, 1.7.8.0
