### ISSUE TITLE
Invoice language

### ISSUE THREAD

**Issue by thecyberman1024** [PrestaShop/PrestaShop#33310] opened 2023-07-19 11:45 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I installed Prestashop 8.1 few days ago in French but all the PDF (invoice, delivery note,...) are in english.
And i just saw there is a bug in the note at the bottom : 

For more assistance, contact Support:
Tel: %s

### Expected behavior

The PDF in french

### Steps to reproduce

1- install prestashop in french
2- edit an invoice

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2023-07-19 15:23
Hello @thecyberman1024 ,

I can't reproduce your issue using 8.1.x :

https://github.com/PrestaShop/PrestaShop/assets/16019289/0e7747bc-27ce-4b52-a1f7-28d24d6ef96e

You can change the bottom page note in Orders > Invoices

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing your issue to avoid clogging the backlog.

Thank you

**Closed as completed by florine2623** 2023-07-19 15:23 UTC
Labels: Bug, Invalid
