### ISSUE TITLE
advertising Image not updated for advertising Block

### ISSUE THREAD

**Issue by yuxiayuzhou** [PrestaShop/PrestaShop#18667] opened 2020-04-16 12:21 UTC
#### Describe the bug

I tried to update a new advertising product image in backend's advertising module. Unfortunately it repeatedly comes out the old one. Cannot figure out the reason.

#### Expected behavior

Hope new product image can be updated

#### Steps to Reproduce

1. Go to 'advertising Block'
2. Click on 'Configure'
3. Click on 'add file'
4. See error - old image just pops out again...

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-04-16 12:52
Hi @yuxiayuzhou,

I did not manage to reproduce the issue with PS1.7.6.4 and ps_advertising v1.0.2.
I attached a screen record
https://drive.google.com/file/d/1j95DJxHPeuzxklC8Ixb-vmW04RGezYsj/view?usp=sharing
Thanks to check and feedback.

**Comment by yuxiayuzhou** [comment] 2020-04-16 22:53
> Hi @yuxiayuzhou,
> 
> I did not manage to reproduce the issue with PS1.7.6.4 and ps_advertising v1.0.2.
> I attached a screen record
> https://drive.google.com/file/d/1j95DJxHPeuzxklC8Ixb-vmW04RGezYsj/view?usp=sharing
> Thanks to check and feedback.

thanks a lot for checking this issue and even shoot a video for this. much appreciate and thanks. Yes, it looks having not a problem in the video, but it is annoying that it does happen in my case. Im sure whether it matters my version 1.7.6.2 or simple my own individual case. 

I found another one has exactly the same issue as mine, who raised the issue on prestashop forum, but seems nobody answered him. Here below is the link for the same question:

https://www.prestashop.com/forums/topic/645032-advertising-block-doesnt-work/

thanks again.

**Comment by florine2623** [comment] 2020-04-17 08:16
Hi @yuxiayuzhou ,
Do you have an error when you inspect the element while saving on ps_advertising?

**Comment by yuxiayuzhou** [comment] 2020-04-17 08:19
no, i did not see an error coming out when save the image. just the old one pops out. thanks for your response. @florine2623

**Comment by florine2623** [comment] 2020-04-17 08:30
Could you check the overrides and try again ?
You need to comment the override folder like so : ```override``` becomes ```_override```

**Comment by yuxiayuzhou** [comment] 2020-04-17 11:15
@florine2623  Thanks for the advice. I replaced the override folder name with _override (i simple copied yours) and _override respectively. I also cleared the cache. Unfortunately problem still exists. 
But i found a readme text in override folder:

Hello,

Please read the documentation before trying to override something here.
http://doc.prestashop.com/display/PS16/Overriding+default+behaviors

Frequently Asked Questions

Q: I added an override file but it seems to be ignored by PrestaShop
A: You need to trigger the regeneration of the /cache/class_index.php file. This is done simply by deleting the file. It is the same when manually removing an override: in order to reinstate the default behavior, you must delete the /cache/class_index.php file.

But it seems for 1.6 version not for 1.7 version im using. I cannot find cache/class_index.php in cathe folder. I only find index.php. Should i delete this file? or the whole cathe folder? Will it help?

**Comment by florine2623** [comment] 2020-04-17 14:04
I was simply asking you to comment the override module in case you had any overrides made by an external module ;)

If there aren't any, you can try these things : 
- clear cache /var/cache delete /dev and /prod
- regenerate .htaccess by going to Traffic & SEO and save without changing anything the following blocks : Set up URLs,  Set shop URL and Schema of URLs

Please check and let me know

**Comment by yuxiayuzhou** [comment] 2020-04-18 00:03
@florine2623 lol, forgive me. Im newbie:) I have changed the name back to override. and i can confirm there is nothing inside as im still using the classic module. 
I followed the advice to clear cache, but i dot know how to regenerate .htaccess. I did not touch much in Traffic&SEO. i have attached the screenshots as well. 
![1](https://user-images.githubusercontent.com/53670538/79622551-d5ff8d00-816b-11ea-83e5-da4036d66170.jpg)
![2](https://user-images.githubusercontent.com/53670538/79622552-d730ba00-816b-11ea-87aa-049b36dbb87c.jpg)

It looks clean to me. 

What else I did:
1. i cleared the cache and stoped memcache as well. and cleared again. seems not good luck.
2. I simple deleted the folder (ps_advertising) in FTP. I expected a reinstallation could help. 

Unfortunately, you may not belive it: i cannot find the advertising block installtion module right now. This is tricky to me. I tried all i can do listed in following ways:

1) i searched in my own backend module catagory, no advertising blok shows up;
2) i searched again on prestashop official website, still no such module.
3) i downloaded a new 1.7.6.4 full module and unzipped it. I cannot find ps_advertising module inside neither. 
4) i also checked the github's folder. It seems a statement saying happy new year 2020. It does not look like a module folder im looking for.

Could you indicate where to download the advertising block module? thank you. Then i can explore further.

**Comment by khouloudbelguith** [comment] 2020-04-23 11:18
Hi @yuxiayuzhou,

Sorry for the late response.
Could you please navigate to your BO => Modules => Module Catalog page => search for the `ps_advertising` module.
![image](https://user-images.githubusercontent.com/16067358/80092349-ee541b00-8562-11ea-866a-d44f85d4d69e.png)
You can find it the module on [GitHub](https://github.com/PrestaShop/ps_advertising/releases).
[ps_advertising.zip](https://github.com/PrestaShop/PrestaShop/files/4522099/ps_advertising.zip)

Thanks to check and feedback.

**Comment by sarahdib** [comment] 2020-05-19 11:43
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-19 11:43 UTC
Labels: Bug, BO, No change required, 1.7.6.2
