### ISSUE TITLE
ContextErrorException 

### ISSUE THREAD

**Issue by CodeWithLaura** [PrestaShop/PrestaShop#32145] opened 2023-04-13 08:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When activating the debug mode these messages appear:

(1/1) ContextErrorExceptionWarning: count(): Parameter must be an array or an object that implements Countable
--
in Cart.php line 62
at Cart->getPackageShippingCost(181, true, object(Country), null, 9)in Carrier.php line 747
at CarrierCore::getCarriersForOrder(9, array(1), object(Cart), array())in Carrier.php line 1539
at CarrierCore::getAvailableCarrierList(object(Product), 0, '5699', 1, object(Cart))in Cart.php line 2379
at CartCore->getPackageList(false)in Cart.php line 2592
at CartCore->getDeliveryOptionList(null)in Cart.php line 3147
at CartCore->getDeliveryOption(null, false, false)in Cart.php line 3216
at CartCore->getTotalShippingCost(null, true)in Fees.php line 81
at Fees->processCalculation(object(Cart), object(CartRowCollection), '2', null)in Calculator.php line 273
at Calculator->calculateFees('2')in Calculator.php line 123
at Calculator->processCalculation('2')in Cart.php line 1951
at CartCore->getOrderTotal(false)in CartPresenter.php line 323
at CartPresenter->present(object(Cart))in FrontController.php line 489
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 547
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 281
at ControllerCore->run()in Dispatcher.php line 509
at DispatcherCore->dispatch()in index.php line 28

### Expected behavior

I need to be able to delete all these messages

### Steps to reproduce

Visit home page

### PrestaShop version(s) where the bug happened

1.7.5.0

**Comment by AureRita** [comment] 2023-04-13 14:22
Hi @CodeWithLaura ,

Thank you for your report, could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- screenshots
- Some detailled step to reproduce (all you did to have this error)

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you

**Comment by hibatallahAouadni** [comment] 2023-05-09 07:06
Hello @CodeWithLaura 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-09 07:06 UTC
Labels: Bug, BO, Dashboard, 1.7.5.0, Invalid
