### ISSUE TITLE
Clicking "Add to cart" two times is causing problems

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10764] opened 2018-09-29 00:42 UTC
**Describe the bug**
Read below.

**To Reproduce**
1. Go to some product page.
2. Click on the 'Add to cart' button two times, quickly
3. You'll not be able to close overlay created by cart popup

My proposal:
Prevent dbl click on this button :)

And yes - some people do that, they're clicking quickly two times on some elements, probably because you're clicking two times on icons in MacOS/Windows... ;-)

**Additionnal information**
PrestaShop version: 1.7.0.0 to 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-01 08:10
Hi @kpodemski,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9634
So, I close it.
Thanks !

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 08:11
Duplicate of #9634

**Closed as completed by khouloudbelguith** 2018-10-01 08:11 UTC
Labels: Duplicate
