### ISSUE TITLE
Product unit_price_ratio is set to 0 on duplication

### ISSUE THREAD

**Issue by JulianEberius** [PrestaShop/PrestaShop#15142] opened 2019-08-16 23:09 UTC
**Describe the bug**
After duplicating a product, the new product will have a unit_price_ratio of 0, even if the original product had a different unit_price_ratio. 

I think this is related to https://github.com/PrestaShop/PrestaShop/pull/5352 , because I could fix it in a similar way. I made sure that the unit_price is set in the Product constructor, so that the calculation in Product::getFieldsShop() works correctly.

**To Reproduce**
1. Fresh install, or start latest Docker image.
2. Set a unit price on some product.
<img width="1012" alt="Bildschirmfoto 2019-08-17 um 01 04 48" src="https://user-images.githubusercontent.com/200639/63202669-28435800-c08b-11e9-8753-1e99fa6746ab.png">
3. Check the "copy of ..." product: the unit price is set to 0, the "unity" text next to it is copied correctly.
<img width="1007" alt="Bildschirmfoto 2019-08-17 um 01 05 05" src="https://user-images.githubusercontent.com/200639/63202701-4446f980-c08b-11e9-8dca-c949d5a5d128.png">

I could do a PR with my solution, but I have no idea what my change might break in other places. I simply moved the line setting the unit_price in the constructor outside the if ($full..) block, so that the unit_price is always initialized.

**Additional information**
PrestaShop version: used the latest Docker image to reproduce, but also happens on my "regular" 1.7.6.0 installation

**Comment by marionf** [comment] 2019-08-19 07:27
Hello @JulianEberius 

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/10792
Please follow this issue

Regards

**Closed as completed by marionf** 2019-08-19 07:27 UTC
Labels: Duplicate
