### ISSUE TITLE
Deactivate "display tax" for carrier

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#12080] opened 2019-01-09 00:38 UTC
Hello,

I deactivated **display tax** on my project by the BO and my theme.
Unfortunately, the tax label in the part "shipment method" during checkout is always display.

The only way to deactivate it, it's to totally deactivate tax.

I searched on the forum and fount the solution: https://www.prestashop.com/forums/topic/868605-solved-remove-tax-included-on-price-showed-on-carrier-selection-ps174/?do=findComment&comment=2929769

> (...)that part also omit the PS option about the tax label, this is a fail of PrestaShop definitely, anyways, you can change it in the file:
> 
> /classes/checkout/DeliveryOptionsFinder.php
> 
> Locate this text: '%price% tax incl.'
> And change for: '%price%'
> 
> And also...
> 
> Locate this text: '%price% tax excl.'
> And change for: '%price%'

Because it's a file of the core, maybe it's better to fix it. deactivate the label tax when we decide not display the tax label in cart.

Or maybe I didn't see an other option in the BO...

--
PS 1.7.5.0

**Comment by khouloudbelguith** [comment] 2019-01-09 08:19
Hi @BenTen,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9773
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-09 08:19
Duplicate of #9773

**Closed as completed by khouloudbelguith** 2019-01-09 08:19 UTC
Labels: Duplicate

**Comment by BenTen** [comment] 2019-01-09 08:34
my bad, I didn't found this topic when I searched it before create mine, maybe because it's in French, sorry.
