### ISSUE TITLE
1.7.6.x Discount voucher problem , The discount code applies to all products, even to discounted items.

### ISSUE THREAD

**Issue by ALTITUDEV** [PrestaShop/PrestaShop#13728] opened 2019-05-09 12:22 UTC
Hello,

Please excuse me in advance for my language, I have a bug with your version.

If an item on sale is added to a basket then it does not accept discount coupons (no worries at this level)

If an item is not on sale then the discount voucher applies (no worries too)

On the other hand, if the customer adds a promotional item + a non-commercial item to his basket, the discount voucher applies to the entire basket and not just the non-commercial item.

Screenshot
https://imgur.com/a/K16QFKh

1 product on sale
1 non-promotional product

The promo code is therefore set to not apply a promotion to another current promotion, except that the problem is that the promo code applies to the entire basket instead of only applying to the non-commercial item.

**Comment by khouloudbelguith** [comment] 2019-05-09 12:29
Hi @CryoDevFR,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10300
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-09 12:29
Duplicate of #10300

**Closed as completed by khouloudbelguith** 2019-05-09 12:29 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2019-05-09 12:30
@CryoDevFR, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13704 to fix the issue.
It should be fixed in the PS1.7.7.0
Thanks!

**Comment by ALTITUDEV** [comment] 2019-05-09 12:33
Thanks you so much !
