### ISSUE TITLE
idShops not countable 

### ISSUE THREAD

**Issue by kmergen** [PrestaShop/PrestaShop#10124] opened 2018-08-24 12:54 UTC
**Describe the bug**
In classes/webservice/WebserviceRequest on line 186 please change ``public static $shopIDs ;`` to ``public static $shopIDs = [];``

Because php 7.2 create a warning, see http://php.net/manual/de/function.count.php

I think there are more positions in core code where it occurs.

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: 7.2.4

**Comment by khouloudbelguith** [comment] 2018-08-24 13:18
Hi @kmergen,

Thanks for your report 
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/ps_legalcompliance
Thank you! 

Best regards, 
Khouloud

**Comment by MathiasReker** [comment] 2018-08-24 14:11
https://github.com/PrestaShop/PrestaShop/pull/10130

**Comment by Quetzacoalt91** [comment] 2018-08-24 14:16
Hi,

This change can already be found in the core: 
https://github.com/PrestaShop/PrestaShop/blob/b9bd063511ba3e33e290150887f13bb08ff1e23b/classes/webservice/WebserviceRequest.php#L212

That was fixed with https://github.com/PrestaShop/PrestaShop/pull/9439, to be released on PS 1.7.5.0.

I'm closing as the issue is fixed.
Regards

**Closed as completed by Quetzacoalt91** 2018-08-24 14:16 UTC
Labels: Improvement, WS, Duplicate, 1.7.4.2

**Comment by khouloudbelguith** [comment] 2020-10-08 09:27
Duplicate of #9439
