### ISSUE TITLE
Missing favicon in iPhone Safari browser

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#22530] opened 2020-12-21 20:05 UTC
#### Describe the bug
There is missing the eshop favicon in iPhone Safari browser if we use own PS theme. We created own theme as a child theme for default PS theme and also we changed the favicon in own theme. Own favicon was correctly created with the app "Favicon generator on PrestaShop Marketplace".
In Win 10 there is not any issue, the favicon is correctly displayed in Mozilla Firefox and Google Chrome. Also the favicon for default theme is displayed in iPhone Safari browser correctly.

#### Expected behavior
The eshop favicon should be also displayed also in iPhone Safari browser.

#### Steps to Reproduce
1. Create own theme as a child theme for PS default theme
2. Set the child theme as active theme in PS configuration
3. Change favicon in the child theme
3. Start eshop FO with the child theme in iPhone Safari browser 
2. Add the url to the Favourites in Safari browser
3. Display Favourites in Safari browser => the favicon is not displayed

#### Additional information
* PrestaShop version: 1.7.6.9
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment] 2020-12-22 09:24
Hello @juraj1000 

I didn't manage to reproduce your issue with PS1.7.6.9 and PS1.7.7.0, see the attached screenshot below: 

![image](https://user-images.githubusercontent.com/23308427/102871244-7a924700-443e-11eb-905b-24e2cb13ad2a.png)

While adding this URL to favorites you can see the favicon:

![image](https://user-images.githubusercontent.com/23308427/102871901-4a977380-443f-11eb-9da1-03d8eee15fba.png)

Displaying all favorites, you can see that all sites saved as favorite doesn't display the favicon (**that's the Safari issue not PrestaShop** :wink: ):

![image](https://user-images.githubusercontent.com/23308427/102872127-9ba76780-443f-11eb-9e69-bb2d732bdefe.png)

I have tested with iPhone11, iPhone12 and Safari 14.
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment] 2020-12-22 20:01
@juraj1000 Maybe safari is primarily looking for it's own iconset. Try to help it.

Open this page - https://realfavicongenerator.net/, upload your favicon in high resolution and it will automatically generate all the icons for all platforms. Then you just put them to your PS folder and add the piece of code to header.tpl.

**Comment by hibatallahAouadni** [comment] 2021-01-11 10:31
Hello @juraj1000 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-11 10:31 UTC
Labels: Bug, BO, Design, Theme & logo, No change required, 1.7.7.0, 1.7.6.9
