### ISSUE TITLE
Error on display details of order

### ISSUE THREAD

**Issue by misieq12** [PrestaShop/PrestaShop#30253] opened 2022-11-09 13:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

After update to PS. 1.7.8.7 i have problem with some orders: I cant see details of the order and I will get the below error:

Type error: Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderMessageForViewing::__construct() must be of the type string, null given, called in /home/ftshop/domains/MYDOMAIN/public_html/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 691

[Symfony\Component\Debug\Exception\FatalThrowableError 0]

When i turn On debug mode i got look attachment
![Schowek01](https://user-images.githubusercontent.com/42605128/200839999-615b784a-7efd-4126-bfbe-3752e2485708.jpg)
![Schowek02](https://user-images.githubusercontent.com/42605128/200840004-47e6c4fe-fb11-415f-b107-9d3c1feb901a.jpg)
![Schowek03](https://user-images.githubusercontent.com/42605128/200840006-2891d3c4-0582-4647-b97b-cae51a00b9ef.jpg)

### Steps to reproduce

1. Goto orders
2. Open new order

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment] 2022-11-09 13:38
Hello @misieq12 

Thanks for your report.
I was unable to reproduce your issue with PS1787 using the same steps to reproduce.

![image](https://user-images.githubusercontent.com/92912932/200844101-896ad0b2-fcc1-4826-b7e1-ea033e8186f7.png)

![image](https://user-images.githubusercontent.com/92912932/200844116-fd47adbc-b4c6-4702-bdb7-b928d734ee1e.png)


So, i'll close the issue.


Thanks!

**Closed as completed by HanaRebaiQA** 2022-11-09 13:38 UTC
Labels: Bug, Invalid

**Comment by elodie66000** [comment] 2024-05-01 09:35
bonjour je viens vers  vous car j'ai exactement le meme probleme ?
