### ISSUE TITLE
authentification ko on backoffice

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#14837] opened 2019-07-24 03:26 UTC
*Describe the bug**
Hello
After the update to the last PS 1.7.6.0, I can't acces to my backoffice anymore and I get this error message 

```
Il y a une erreur.
Ce compte employé n'existe pas, ou le mot de passe est erroné.

```

even when I try to reset my password I get an error msg : 

**`Ce compte n'existe pas`**

I checked my SQL and there is no issue there, I see clearly my account on employee table

How can I resolve this issue 
Regards,

**To Reproduce**
Update to 1.7.6.0

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: PHP Version 7.2.20

max_execution_time | 9000 | 9000
-- | -- | --
max_file_uploads | 20 | 20
max_input_nesting_level | 64 | 64
max_input_time | 6000 | 6000
max_input_vars | 6000 | 6000
memory_limit | 5140M | 5140M

**Comment by khouloudbelguith** [comment] 2019-07-24 07:20
Hi @go-sudo,

I did not manage to reproduce the issue with PS1.7.6.0 after upgrade from PS1.7.5.2 using the 1-click upgrade v4.9.0.
Here's the solution to rest the password in your PrestaShop project manually.
So before doing any changes to your live database, I would highly recommend making a backup, or maybe even two!

First, you need to find out your COOKIE KEY which is in a new position since PrestaShop 1.7. Use your file manager to navigate to the app/config folder. Open the file parameters.php and find the row as seen in the picture:
![image](https://user-images.githubusercontent.com/16067358/49854876-d788aa80-fdeb-11e8-8df8-752cf0c11ad3.png)
Switch to phpMyAdmin and navigate to your PrestaShop database. Find the table PREFIX_employee and click BROWSE.
PS: PREFIX is the prefix of your tables, t could be for example ps.
![image](https://user-images.githubusercontent.com/16067358/49855029-436b1300-fdec-11e8-9a46-b45400d44daf.png)
Click on the edit button at the first row.

Scroll down to the field labeled passwd and clear the field from your old encrypted password. Now paste the COOKIE KEY followed by your new password, in this example newpassword. The cookie key and the new password have to be pasted behind each other without any blanks or other unwanted characters!

Click on the dropdown and select MD5 as our function. Scroll down to the bottom and select GO.
![image](https://user-images.githubusercontent.com/16067358/49855053-57167980-fdec-11e8-9abe-f5c3f6581e22.png)

Thanks to check & feedback.

**Comment by go-sudo** [comment] 2019-07-24 11:59
Hello @khouloudbelguith 

I proceeded as you described but nothing works here a video shows you what I did.

https://drive.google.com/file/d/1sMEa8BrZiK_VJvAPBzOMqY2VhYcjrIR8/view

I want to add that one of colleagues is the only one who can log in, so we create a new employee and it works but the issue still the same for old user created before the update

Since I can log in now with a fresh user I notice that back office is very slow so i will create a new issue 



Regards

**Comment by khouloudbelguith** [comment] 2019-07-24 12:25
@go-sudo, I tried this solution & it is OK
I attached a screen record
https://drive.google.com/file/d/18NuYc4QFU0Bkebl0_mqr6cRIuVSE5DNp/view

Thanks!

**Comment by go-sudo** [comment] 2019-07-24 12:46
Hello @khouloudbelguith 
I did exactly step by step what you did but still same issue, i made a test on 2 computers and different browsers 
I want to add that one of colleagues is the only one who can log in, so we create a new employee and it works but the issue still the same for old user created before the update

Since I can log in now with a fresh user I notice that back office is very slow so i will create a new issue

Regards

**Comment by khouloudbelguith** [comment] 2019-07-24 13:34
@go-sudo, I tried the same steps with other employees & it is OK.
@go-sudo, have you tried to generate their passwords via email?

Thanks!

**Comment by go-sudo** [comment] 2019-07-25 00:27
Hello @khouloudbelguith 

I repeated again and it works, I can access again with my own mail

Thank you I appreciate, I will create an other issue as I said the back office is slow and generate an error every time I log on 

here is 2 videos 
https://drive.google.com/file/d/1LyuPn_icjh5emncLpLVRCgFk2G7G-OCu/view 
https://drive.google.com/file/d/1jziMu7kIZKAzDdcfCPWWfXy0JwcF3iVf/view

Regards

**Comment by khouloudbelguith** [comment] 2019-07-26 10:49
@go-sudo, thanks!
Since it is fixed; I close the issue.
Feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-26 10:49 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.6.0
