### ISSUE TITLE
Product default supplier reference is not updated

### ISSUE THREAD

**Issue by simondaigre** [PrestaShop/PrestaShop#19902] opened 2020-06-22 19:11 UTC
#### Describe the bug

Product default supplier is not updated since https://github.com/PrestaShop/PrestaShop/commit/29bda43a552316fb4a29c60f44ff287230bce62f#diff-7d7493bae4eba5d548b7f7f88d16d7ea - was fixed by https://github.com/PrestaShop/PrestaShop/pull/11175

#### Expected behavior

See https://github.com/PrestaShop/PrestaShop/pull/11175

#### Steps to Reproduce

See https://github.com/PrestaShop/PrestaShop/pull/11175

**Comment by sarahdib** [comment] 2020-06-23 08:56
Hello, 

since the provided information isn't sufficient to reproduce the issue, we are closing it. Feel free to open a new one with all the requested information. 

Thank you!

**Closed as completed by sarahdib** 2020-06-23 08:56 UTC
Labels: No change required

**Comment by simondaigre** [comment] 2020-06-23 09:05
@sarahdib you have all informations to reproduce it in https://github.com/PrestaShop/PrestaShop/pull/11175 - this fix is broken since the commit mentionned in this issue.

**Comment by matks** [comment] 2020-06-23 09:47
@sarahdib I think it means that PR https://github.com/PrestaShop/PrestaShop/pull/11175 meant to fix a bug (see the "How to test" of https://github.com/PrestaShop/PrestaShop/pull/11175), it was reviewed, approved by QA, but some code added later has broken it 😅

**Comment by simondaigre** [comment] 2020-06-30 19:40
@sarahdib Could you reopen this issue ?
