### ISSUE TITLE
Catalog page interface changed

### ISSUE THREAD

**Issue by nikospapadimitriou** [PrestaShop/PrestaShop#25880] opened 2021-09-14 16:26 UTC
Sudenly the interface of the catalog was changed, It is like a beta version of the program.
When i move to orders the interface works properly, it changes when i move to catalog.

![εικόνα](https://user-images.githubusercontent.com/90692677/133296687-4ff1fe25-194d-4924-aa44-1965b043a178.png)

**Comment by florine2623** [comment] 2021-09-15 07:36
Hello @nikospapadimitriou ,

Make sure your PHP version is compatible with your PS version.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

What did you do before it changed ?
Thanks

**Comment by NeOMakinG** [comment] 2021-09-15 07:44
Looks like Material Icons is not loaded, don't you have a connection problem? Maybe the google CDN was buggy...

**Comment by Hlavtox** [comment] 2021-09-15 10:33
Hit F12, open console and check if there are any errors. This could be caused by CORS problems. Is SSL set up properly and working in your store?

**Comment by hibatallahAouadni** [comment] 2021-09-16 09:36
Hello @nikospapadimitriou 

Please check your console and your connection cause it's definitely not a PS Core bug. 
Sorry, but I have to close the issue. 

PS: @NeOMakinG & @Hlavtox thanks guys for your quick replies

Thanks for understanding :pray:

**Closed as completed by hibatallahAouadni** 2021-09-16 09:36 UTC
Labels: Bug, BO, No change required, Front-end, 1.7.6.1

**Comment by nikospapadimitriou** [comment] 2021-09-16 09:55
Thanks a lot the problem is fixed
