### ISSUE TITLE
Some errors when debug mode enabled - invalid Entities Mapping

### ISSUE THREAD

**Issue by momo1240** [PrestaShop/PrestaShop#27218] opened 2022-01-05 13:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
After updating prestashop to the latest version (from 1.7.7.8) I have these 2 issues on Entities Mapping
 and  can't find any solution on prestahsop forums

thank you guys

![1 7 8](https://user-images.githubusercontent.com/3137613/148225989-96794653-447e-4acb-94c4-8ca08addc46d.PNG)

### Steps to reproduce

- Case1
1. updating prestashop from 1.7.7.8 to 1.7.8.2
2. Enable debug mode
3. Go to Symfony toolbar & see errors in the Docrine

- Case2
1. Enable debug mode
2. Edit a product
3. In the Symfony toolbar & go to Doctrine
![image](https://user-images.githubusercontent.com/87248592/151418057-01795d86-1a6c-4842-bdca-1bf7f7ca3ec2.png)

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-01-05 16:36
Hello @momo1240 

In which page did you enoucnter these errors? 
Please check and feedback.

Thanks!

**Comment by momo1240** [comment] 2022-01-05 17:18
Hello Hibatallah
thank you for your reply

these errors are displayed when I have debug mode activated
Errors are listed in Doctrine->Entites Mapping

thank you

**Comment by khouloudbelguith** [comment] 2022-01-07 16:45
Hi @momo1240,

I manage to reproduce the issue after an upgrade from PS1778 to PS1783build1
![image](https://user-images.githubusercontent.com/16067358/148576817-0d323720-563d-4bca-885e-077308f7f0e5.png)
It was fixed in the PS1780 with this issue: https://github.com/PrestaShop/PrestaShop/issues/21206
But not fixed after an upgrade
> Update by Khouloud

In fact, those issues are not similar 
It is not the same bug 
They are just related.

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by khouloudbelguith** [comment] 2022-01-28 15:13
I manage to reproduce the issue with PS1780 & PS1783 when editing a product V1. 
![image](https://user-images.githubusercontent.com/16067358/151542975-8db10ec0-28a3-4a1c-996b-15b33abc4332.png)
In PS17778 => ok
![image](https://user-images.githubusercontent.com/16067358/151543128-85aee703-9958-439f-8ce7-53d6b94ef4d3.png)

I tried to edit a product V2 (1783 & develop) => there are no errors about `PrestaShopBundle\Entity\AttributeGroup` & `PrestaShopBundle\Entity\Shop` & `PrestaShopBundle\Entity\ShopGroup`.
![image](https://user-images.githubusercontent.com/16067358/151543190-d41f1b48-feec-4d41-a431-c4162588add2.png)

Thanks!

**Comment by Progi1984** [comment] 2022-02-07 19:58
Fixed by @okom3pom in #27516 & tested by @khouloudbelguith

**Closed as completed by Progi1984** 2022-02-07 19:58 UTC
Labels: Bug, Minor, BO, CO, Regression, Autoupgrade, Fixed, Developer Feature, PR available, 1.7.8.0, Verified, Module
