### ISSUE TITLE
a 413 Request Entity Too Large error was encountered while trying to use an ErrorDocument to handle the request.

### ISSUE THREAD

**Issue by savoy6aus** [PrestaShop/PrestaShop#15026] opened 2019-08-07 17:01 UTC
Request Entity Too Large
The requested resource
/VMSDraft/admin123/index.php/improve/design/themes/import
does not allow request data with GET requests, or the amount of data provided in the request exceeds the capacity limit. 
Additionally, a 413 Request Entity Too Large error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by khouloudbelguith** [comment] 2019-08-08 07:40
Hi @savoy6aus,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-09 07:48
Hi @savoy6aus,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-09 07:48 UTC
Labels: Theme & logo, No change required
