### ISSUE TITLE
Problem pagination products prestashop 1.7.4.2

### ISSUE THREAD

**Issue by anto7880** [PrestaShop/PrestaShop#10108] opened 2018-08-23 16:18 UTC
Hello, I have configured the layout with (product quantity) because I want to show the products not available for ordering on the last page.
When I go to the category this does not work, the zero quantity products are shown on the first page.
I have attached screen
![pagination](https://user-images.githubusercontent.com/20085845/44538180-e5150a00-a700-11e8-88ca-b45828280c2b.jpg)
![outstock](https://user-images.githubusercontent.com/20085845/44538185-e8a89100-a700-11e8-9e1e-72c4d76e2ed4.png)

**Comment by khouloudbelguith** [comment] 2018-08-24 07:32
Hi @anto7880,

I manage to reproduce the issue with the last version 1.7.4.2. / 1.7.3.4.
The pagination doesn't work.
We will see how to fix it.

Best regards, Khouloud

**Comment by jolelievre** [comment] 2018-08-24 08:48
Hello, from what I see in your screenshot the default order is Ascending (so from 0 to +infinity), so it seems logical that your product with 0 quantity are displayed first
If you try to set a Descending order it should work as you expected

**Comment by anto7880** [comment] 2018-08-24 10:43
I've already tried.
I have configured (Ascending) and it does not work
I have configured (Descending) and it does not work

**Comment by jolelievre** [comment] 2018-08-24 11:03
Ok, I just wanted to be sure. We'll look into it!

**Comment by marionf** [comment] 2018-08-24 11:45
Hello @anto7880 

Your issue is a duplicate of #9956 so, I close it
Yous should follow this issue

Regards

**Closed as completed by marionf** 2018-08-24 11:45 UTC
Labels: Bug, Minor, FO, Duplicate, Product settings, 1.7.4.2
