### ISSUE TITLE
Autoupgrade : PSCheckout trigger an error with `1.7.7.0-7.1-apache` (and all 1.7.7.x)

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#36425] opened 2024-06-26 08:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After an upgrade (1.7.7.0 -> 1.7.7.8), the PS Checkout trigger an error after an upgrade

![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/eb706580-f61d-4335-8d40-749e17d853a7)

### Expected behavior

Guess... "No errors"... 

### Steps to reproduce

1. Install PrestaShop Open Source in France / English in 1.7.7.0 with PHP 7.1 with Docker and Apache image (`1.7.7.0-7.1-apache`)
2. The PSX Checkout is installed
3. Install module **autoupgrade** 
```
php -v bin/console prestashop:module install autoupgrade
```
4. Upgrade 
```
php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --channel=minor
```

### PrestaShop version(s) where the bug happened

1.7.7.0 => 1.7.7.8

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade dev

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by Hlavtox** [comment] 2024-06-26 09:54
@Progi1984 Not related to the open source project

**Comment by Progi1984** [comment] 2024-06-26 09:55
@Hlavtox It's now the case.

**Comment by Hlavtox** [comment] 2024-06-26 09:57
@Progi1984 ?

PSCheckout is not part of this project, nor a native module. Buggy module, as any of the third party ones.

**Comment by Progi1984** [comment] 2024-06-26 10:01
PSCheckout was embed in 1.7.7.0 so it locks the upgrade to the next version.

So it's a bug. 

And @gericfo will prioritize it.

**Comment by Hlavtox** [comment] 2024-06-26 10:07
There is no PScheckout in [1.7.7](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0)

![1 7 7](https://github.com/PrestaShop/PrestaShop/assets/6097524/c74862bb-2315-4671-8577-8c4da7a58903)

**Comment by kpodemski** [comment] 2024-06-26 10:20
@Progi1984 @gericfo I think it's something to be addressed by the PS Checkout team, am I right? If so, this should be directed to them, not added here to the Issues, because it hasn't been decided to handle PS Checkout issues here on GitHub :)

**Comment by gericfo** [comment] 2024-06-26 10:43
@kpodemski We wanted to keep track of these actions here (with transparency). But yes I'll hand this issue to the team in charge of the PS Checkout module.

**Comment by AureRita** [comment] 2024-07-01 09:32
Hi @Progi1984 ,

Thank you for your report, I reproduce the issue with PrestaShop version 1.7.6.7, as you can see : 

[recording(247).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/00ca8783-03b5-4c91-8133-4848e1d1bc68)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

FYI : I used the zip provided by the git hub repo.

Thanks

**Comment by AureRita** [comment] 2024-07-02 09:53
FYI : This issue is also reproduce from : 
- 1.7.8.0 
- 1.7.8.1
- 1.7.8.2
- 1.7.8.3
- 1.7.8.4
- 1.7.8.5
- 1.7.8.6 
- 1.7.8.7
- 1.7.8.8 

to 8.1.7 With the major release with php : 
- 7.2
- 7.3
- 7.4 

All are from fresh install from github. 

Kind regards

**Comment by Quetzacoalt91** [comment] 2024-09-23 10:22
After further investigation this morning, it appears this issue is caused by PS Metrics that includes dev dependencies with code compatible with PHP 7.2+.
I've contacted one member of the team that maintained this module, we can expect an update on the vendor contents in a future release.

**Comment by nesrineabdmouleh** [comment] 2024-10-16 07:59
Fixed in the release v4_0_7 of ps_metrics

**Closed as completed by nesrineabdmouleh** 2024-10-16 07:59 UTC
Labels: Bug, Major, BO, Autoupgrade, Detected by TE, 1.7.8.x, Verified
