### ISSUE TITLE
Unable to turn off maintenance mode on multistore

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#15266] opened 2019-08-26 18:50 UTC
**Describe the bug**
When I am in All shops mode turning off maintenance mode does not make any effect. I Have to switch to each shop and there disable maintenance mode. Problem is because `PS_SHOP_ENABLE` is set to `0` after enabling shop in all mode.

Related to #14696 

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-08-27 07:51
Hi @Flower7C3,

Thanks for your report.
This issue should be fixed with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9548

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-27 07:51
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9548

**Closed as completed by khouloudbelguith** 2019-08-27 07:51 UTC
Labels: Duplicate
