### ISSUE TITLE
Images aren't displayed in combinations - New product - BO

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10299] opened 2018-09-05 15:17 UTC
**Describe the bug**
https://github.com/PrestaShop/PrestaShop/pull/10169 is not fixed with a new product

**To Reproduce**

1. Create a new product
2. Add images
3. Click on combinations
4. Select attributes and click on Generate
5. Edit a combination
You have 0/0 images

**Screenshots**
https://drive.google.com/file/d/1oY1LFVmGESEB_4y7vhUnvzidzEUG8rxR/view

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by marionf** [comment] 2018-09-05 15:20
Duplicate of #9556

**Closed as completed by marionf** 2018-09-05 15:20 UTC
Labels: Duplicate
