### ISSUE TITLE
Maximum execution time of 45 seconds exceeded

### ISSUE THREAD

**Issue by Bredamcguigan** [PrestaShop/PrestaShop#17344] opened 2020-01-24 12:23 UTC
I am trying to upgrade from 1.7.4.3 to 1.7.6 using 1 click upgrade. I have tried this on other sites in the past and I always have problems. I have changed the folder permissions to those recommended. I get this error:
I have tried on many sites to get this working, I increased the max timeout on php.ini and I still get this error:
public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 101 - Maximum execution time of 45 seconds exceeded

I have changed the php.ini to max timeout 3600, max execution time to 3600 and memory limit to 1g
Does anyone have a solution to this?
thanks

**Additional information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-01-24 13:50
Hi @Bredamcguigan,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by Bredamcguigan** [comment] 2020-01-24 14:16
Thanks i tried that but when I try it in my browser it says:
requesting your username and password. The site says: “Authentification”
Not sure why.

**Comment by khouloudbelguith** [comment] 2020-01-24 14:19
@Bredamcguigan, thanks to try with this file, check & feedback.

[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4108869/phppsinfo.php.zip)

**Comment by Bredamcguigan** [comment] 2020-01-24 14:24
thanks that worked, I don;t see a timeout limit on this screen:
http://prntscr.com/qsblxe

**Comment by khouloudbelguith** [comment] 2020-01-24 14:28
@Bredamcguigan, thanks to increase your `memory_limit` to 256MB, check & feedback.

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 14:32
I did that and now I have a white screen on admin and front.

**Comment by khouloudbelguith** [comment] 2020-01-24 14:39
@Bredamcguigan, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 14:49
I can;t see those files in cpanel but i put debug on and I see this:
 Allowed memory size of 2097152 bytes exhausted (tried to allocate 1368064 bytes) in /home/birdcouk/public_html/vendor/composer/autoload_real.php on line 32

**Comment by khouloudbelguith** [comment] 2020-01-24 14:55
@Bredamcguigan, thanks to provide me a screenshot of the exact exception.

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 15:00
I changed the memory to 560M and it is loading some of the home but really slow: https://birdgard.co.uk/ slider is missing and products should be showing on the home page.
I'll contact the host company to check the settings. thanks

**Comment by khouloudbelguith** [comment] 2020-01-24 15:01
@Bredamcguigan, thanks!
Waiting for your feedback.

**Comment by Bredamcguigan** [comment] 2020-01-24 15:35
ok can to restore from a backup but now have the following:
 PHP version: 7.1.33

Memory limit: 2048M

Max execution time: 900

Upload Max File size: 2M 
I'm going to try to run the 1 click upgrade again. Hopefully it wil work this time.

**Comment by khouloudbelguith** [comment] 2020-01-24 15:37
@Bredamcguigan, great!
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
Since it is ok.
I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 15:46
sorry can I open this again as the upgrade is still not successful?

**Comment by khouloudbelguith** [comment] 2020-01-24 15:48
@Bredamcguigan, Yes!

**Comment by Bredamcguigan** [comment] 2020-01-24 15:49
sorry ok tried the upgrade again and this is as far it got:
http://prntscr.com/qsd1bg
here is the permissions on the file manger: http://prntscr.com/qsd1r2

**Comment by khouloudbelguith** [comment] 2020-01-24 15:54
@Bredamcguigan, what is the exact version of the 1-click upgrade did you use?

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 15:55
v4.10.1
thanks

**Comment by khouloudbelguith** [comment] 2020-01-24 16:00
@Bredamcguigan, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 16:01
yes no problem.
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4109375/log.txt)

**Comment by khouloudbelguith** [comment] 2020-01-24 16:18
@Bredamcguigan,
You have these errors:
>[2020-01-24 05:38:20] [INTERNAL] /home/birdcouk/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 86 - scandir(/home/birdcouk/public_html/oldsite/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/cache/smarty/cache/blockbanner/1/2/21/32/61/f0/): failed to open dir: Too many levels of symbolic links
[2020-01-24 05:38:20] [INTERNAL] /home/birdcouk/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 86 - scandir(): (errno 40): Too many levels of symbolic links
[2020-01-24 05:38:56] [INTERNAL] /home/birdcouk/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 101 - Maximum execution time of 45 seconds exceeded

Did you use the `blockbanner` module?
As non-native modules can experience some compatibility issues, we recommend to disable them by default.
Keeping them enabled might prevent you from loading the "Modules" page properly after the upgrade.

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 16:26
The theme I'm using came with IQITHTMLANDBANNERS, should I disable all non native beofre the upgrade and then turn them back on if it is sucessfull?
thanks
B

**Comment by khouloudbelguith** [comment] 2020-01-24 16:34
@Bredamcguigan, As non-native modules can experience some compatibility issues.
So, yes you need to check the compatibility of those modules.

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-24 16:59
thanks can you leave this open as I'll try again on Monday. Have a good weekend.

**Comment by khouloudbelguith** [comment] 2020-01-24 17:06
@Bredamcguigan, waiting for your feedback.

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-27 08:49
Hi Again,

I have disabled the non native modules and ran the 1 click upgrade and got an error again:

All sample files removed. Now backing up files.

[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:"Gateway Timeout " jqXHR: "

 

It shows a 500 gateway timeout. Is there anything else I can do?

Regards,

Breda

**Comment by khouloudbelguith** [comment] 2020-01-27 11:30
@Bredamcguigan, Misconfigurations at the client side can result in “504 gateway time-out error in Prestashop”, It can be due to various reasons like:

- Improper browser settings or browser cache.
- Temporary problems with the network devices such as modems, routers, etc.
- Incorrect proxy settings in the browser or application.
- Network issues.

Please contact your host about this error & feedback.

**Comment by Bredamcguigan** [comment] 2020-01-28 09:10
HI I am still back and forth with the host company. Can you tell me what should the max execution time should be? It is giving an error on it now.

**Comment by khouloudbelguith** [comment] 2020-01-28 09:20
@Bredamcguigan, as you can see [here](https://github.com/PrestaShop/PrestaShop/issues/16507): the memory_limit required is 256M.
Also, you can view all of the information about PHP for your server for that particular director as described [here](https://github.com/PrestaShop/PrestaShop/issues/17344#issuecomment-578137275).
This is our official [link](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/) to check the System requirements for PrestaShop 1.7
Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-28 11:00
Hi, I have the server requirements in place, in the log file I am seeing this error:
/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 86 - scandir(): (errno 40): Too many levels of symbolic links
Do you know what this means and how i can fix it? thanks.

**Comment by khouloudbelguith** [comment] 2020-01-28 11:16
@Bredamcguigan, could you please check if this file: `/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php` exists on your server.

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-28 11:23
Yes its there and has permission 0666.

**Comment by khouloudbelguith** [comment] 2020-01-28 11:58
@Bredamcguigan,
>the server requirements in place

When you try to make an upgrade again, it fails?

Thanks!

**Comment by Bredamcguigan** [comment] 2020-01-28 12:00
Yes the log file says: 
[2020-01-28 04:01:14] [INTERNAL] /home/birdcouk/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 86 - scandir(/home/birdcouk/public_html/oldsite/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/birdgard/cache/smarty/cache/blocktopmenu/1/2/26/cms/32/e5/a9/): failed to open dir: Too many levels of symbolic links
[2020-01-28 04:01:14] [INTERNAL] /home/birdcouk/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 86 - scandir(): (errno 40): Too many levels of symbolic links
[2020-01-28 04:01:52] [INTERNAL] /home/birdcouk/public_html/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 101 - Maximum execution time of 45 seconds exceeded

**Comment by khouloudbelguith** [comment] 2020-01-28 12:06
@Bredamcguigan,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-28 12:06 UTC
Labels: Bug, BO, Can't reproduce, Autoupgrade, 1.7.4.3
