### ISSUE TITLE
PayPal (official module) not showing anymore in checkout

### ISSUE THREAD

**Issue by IlPizza79** [PrestaShop/PrestaShop#15998] opened 2019-10-17 08:31 UTC
**Describe the bug**
PayPal module is active and fully configured but it's not showing in checkout. 

**To Reproduce**
1. Install, active anc configure official PayPal module.
2. Check if PayPal is showing in checkout
3. No go to Payment preferences page
4. Click any "Save" button
5. Now PayPal is not showing anymore in checkout

**Additional information**
PrestaShop version: 1.7.6.1
Official PayPal module version: 5.0.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-17 08:49
Hi @IlPizza79,

I did not manage to reproduce the issue with PS1.7.6.1 & the Paypal module v5.0.2.
I attached a screen record
https://drive.google.com/file/d/1OW148nPVodMkK5TN1FxDiZzvmZGQ57Ih/view
Are you well connected to your account? and did you check your "API USERNAME" if it is well set?

Thanks to check & feedback.

**Comment by IlPizza79** [comment] 2019-10-17 11:48
Sorry, I guess I should be more precise in my reports... 
I'm really sorry, I wrote my report in a hurry.

At point 3 and 4 of my report, I mean: 
_now go to "Dashboard >> Payment >> Prefences" page, do some changes and click save. 
For example, you can enable PayPal for all country and save._

After save in "Dashboard >> Payment >> Prefences" page, PayPal is not showing anymore in checkout. Can you please try this scenario?

Thanks in advance, and sorry again.

**Comment by IlPizza79** [comment] 2019-10-17 12:16
Ah, I forgot to say that I have to "reset" the PayPal module (and reconfigure and reconnect to my PayPal account) to make it visible again in checkout.
Thanks again.

**Comment by khouloudbelguith** [comment] 2019-10-17 12:49
@IlPizza79, thanks for these clarifications, but it is well working in my case
https://drive.google.com/file/d/1VPAVZSEOBjVo3rKo3U3Q-nWgBYGvLwMe/view
Thanks to upgrade your Paypal module to the next version v5.0.2.

Check & feedback.

**Comment by rdy4ever** [comment] 2019-10-18 09:23
@IlPizza79 maybe you shold give the new [Prestashop Checkout (with Paypal)](https://www.prestashop.com/en/prestashop-checkout) module a try and replace the old Paypal module.

**Comment by khouloudbelguith** [comment] 2019-11-18 07:40
Hi @IlPizza79,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-18 07:40 UTC
Labels: Bug, FO, Payment, No change required, Checkout, 1.7.6.1
