### ISSUE TITLE
Admin login redirect to admin login

### ISSUE THREAD

**Issue by qualityangel** [PrestaShop/PrestaShop#23378] opened 2021-02-24 09:43 UTC
#### Describe the bug

After update, the backoffice many times redirect back to login. Like the checkip issue that we all know of. But as usual, i have cleared the cache, disabled checkip on cookie, but even then i have been redirect back to login. When i clear my cache on chrome, the issue is over for about 10 minutes.

I have tried al the things i know for now, so does anybody can help me with this issue?

#### Expected behavior

Login normaly

* PrestaShop version: 1.7.7.2
* PHP version: 7.3.2.7 / FMP Apache
* Chrome, latest version

**Comment by matks** [comment] 2021-02-24 10:11
@qualityangel did you perform an upgrade recently?

**Comment by qualityangel** [comment] 2021-02-24 10:37
Yes i did, to 1.7.7.2 from 1.7.7.2

**Comment by matks** [comment] 2021-02-24 10:50
Then it might be the issue reported in https://github.com/PrestaShop/PrestaShop/issues/22300

Might be related to outdated ICU version of your PHP, see details in https://github.com/PrestaShop/PrestaShop/issues/22300

**Comment by hibatallahAouadni** [comment] 2021-02-24 10:59
Hello @qualityangel 

Could you please check this issue #22758 cause it seems similar to yours.
Please check and feedback.

PS: Thanks @matks for your quick replies :wink: 

Thanks!

**Comment by qualityangel** [comment] 2021-02-27 07:01
Both commented issues are not the same as mine. I do not have a black page, it is only redirecting to itself. when i remove the token, i'm loggend in, but when i am going to products etc. i have been redirect to login again. When i remove cookies in chrome it works for 10 minutes.

**Comment by hibatallahAouadni** [comment] 2021-03-01 19:37
Hello @qualityangel 

> Yes i did, to 1.7.7.2 from 1.7.7.2

Which was your previous version? cause you seems you mistyped :sweat_smile: 
Did you encounter any errors or warnings while upgrading?
Please check and feedback.

Thanks!

**Comment by qualityangel** [comment] 2021-03-02 11:52
> Hello @qualityangel
> 
> > Yes i did, to 1.7.7.2 from 1.7.7.2
> 
> Which was your previous version? cause you seems you mistyped 😅
> Did you encounter any errors or warnings while upgrading?
> Please check and feedback.
> 
> Thanks!

We have upgraded from 1.7.7.1 with no errors in the upgrade. It seems a caching problem. after same time this week, it seems more en more less that it happens.

**Comment by hibatallahAouadni** [comment] 2021-03-03 08:23
Hello @qualityangel 

>  It seems a caching problem. after same time this week, it seems more en more less that it happens.

Exactly, cause I upgraded my shop 1.7.7.1 to 1.7.7.2 and I didn't encounter this issue.
Well, it seems your issue is not related to PS Core. So, we need to close the issue :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-03 08:23 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.7.2

**Comment by fakihi** [comment] 2021-03-03 09:36
Hi,

I had the same issue when upgrading from 1.7.6.3 to 1.7.7.2. 
**Steps to reproduce:**
1. Upgrade Prestashop from 1.7.6.3 to 1.7.7.2
2. Open backoffice admin
3. Enter correct login and password
4. Click login button
**Result:** The user is redirected to the admin login page
**Expected result:** The user is redirected to the admin dashboard

Workaround: downgrade to a version prior to 1.7.7.2

Note: Issue reproduced on PHP 7.2, 7.3 and 7.4. Waiting on ICU information from hosting company but I also doubt the issue root cause is related to this.

**Comment by qualityangel** [comment] 2021-03-03 14:57
> Hi,
> 
> I had the same issue when upgrading from 1.7.6.3 to 1.7.7.2.
> **Steps to reproduce:**
> 
> 1. Upgrade Prestashop from 1.7.6.3 to 1.7.7.2
> 2. Open backoffice admin
> 3. Enter correct login and password
> 4. Click login button
>    **Result:** The user is redirected to the admin login page
>    **Expected result:** The user is redirected to the admin dashboard
> 
> Workaround: downgrade to a version prior to 1.7.7.2
> 
> Note: Issue reproduced on PHP 7.2, 7.3 and 7.4. Waiting on ICU information from hosting company but I also doubt the issue root cause is related to this.

Thanks Fakihi, this is the precise issue that we also have.

**Comment by fakihi** [comment] 2021-03-03 15:09
@matks @hibatallahAouadni I'd suggest reopening this issue. 
Not reproducing the issue in your specific environment does not mean that the issue does not exist. ;)

**Comment by qualityangel** [comment] 2021-03-03 15:16
> @matks @hibatallahAouadni I'd suggest reopening this issue.
> Not reproducing the issue in your specific environment does not mean that the issue does not exist. ;)

I agree! This issue is not from only the latest version, i have had it before.

**Comment by matks** [comment] 2021-03-03 15:21
@fakihi What is the point of reopening an issue that we cant reproduce?

Being able to reproduce an issue is the 1st step to debug it and fix it. If we reopen the issue but we cannot reproduce, then it will just stay forever open 😉  . It's useless.

We keep issues open when they are items we can work on. An issue we can reproduce is the 1st item we need to fix it. A feature idea we understand it the 1st item we need to implement it.

An issue open but we cant reproduce it is useless.

**Comment by fakihi** [comment] 2021-03-03 16:39
@matks,
I thought that the purpose of these bug reports was to give you user feedback from a wider set of environments and conditions, so that you can improve Prestashop. I must have been mistaken.
Thank you very much for your contribution Mathieu. :)

**Comment by wosin7** [comment] 2021-06-15 11:29
Same problem here
version 1.7.7.5
php 7.2 and 7.3 
sever litespeed

cant login on back office on various browsers:
FireFox works,
Chrome mobile works,
Chrome destkop is not working, and it is no cache, i checked on 3 different computers.

**Comment by hibatallahAouadni** [comment] 2021-06-15 11:56
@wosin7 what's your Chrome version?

**Comment by wosin7** [comment] 2021-06-15 12:28
> @wosin7 what's your Chrome version?

this could be it!
chrome desktop linux 91.0.4472 not working
chrome desktop windows 91.0.4472 not working
chrome desktop linux 91.0.4472 not working

but
old pc with chrome desktop linux 76 working great
i will try downgrade my chrome and check now

**Comment by hibatallahAouadni** [comment] 2021-06-15 12:52
@wosin7 It works with Chrome 89.0.4389.82
Kind of related to #24915

**Comment by wosin7** [comment] 2021-06-16 13:11
yes and its working with 90.0.4430.93 and bellow 
I am confused
presta 1.7.7.5 installed on 2 different servers, one from install package. second from git, and on both i cant login to admin  on chrome 91.0.4472
funy thing presta 1.7.7.4 works on chrome 91.0.4472 and other version
I have no idea if this is a bug of presta or chrome...

anyway, if you encounter such an error, please change your browser to a different one, or change your chrome version
