### ISSUE TITLE
Massive increase in unneccessary query count, when cookie is set

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22647] opened 2021-01-04 00:08 UTC
#### Describe the bug

I have approximately 15 active cart rules enabled. There is a massive difference in query count, depending on if you are a clean customer with no cookie, or you have a cookie (context) created. See screenshots.

#### Expected behavior

The behavior should be the same, if I am not logged in and I have an empty cart.
Whatever cart rule calculation should be stopped as soon as possible, if the cart is empty.

#### Steps to Reproduce

1. We have 25 active cart rules.
2. 10 rules activated by a code.
3. 15 rules that give a gift
4. Import 100 products
5. Set these cart rules so they are each limited to 5 products.

---
1. Go to https://www.trendo.cz/94-granitove-drezy?profiling#prestashop_profiling and see the number of queries.
2. Add something to cart. Go to cart and remove it again.
3. Go to https://www.trendo.cz/94-granitove-drezy?profiling#prestashop_profiling again and see that the query count has increased by hundreds, even though the situation is still the same.

**Screenshots**

![before](https://user-images.githubusercontent.com/6097524/103492149-3aad6580-4e29-11eb-980d-ee7b98a2210e.JPG)
![increase](https://user-images.githubusercontent.com/6097524/103492155-4305a080-4e29-11eb-807f-da46c73520d5.JPG)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-04 15:21
Hello @Hlavtox 

I followed your steps and here's what I get:

1. at first: **704 queries**
2. I added a product to cart: **1547 queries**
3. Then I remove the product: **1123 queries**

But I think this issue is similar to this one #20034 (that you created) and to this one #14935, is that so?

**Comment by Hlavtox** [comment] 2021-01-06 10:43
@hibatallahAouadni The other issue is simmilar in the topic, but has different cause. The queries in this issue are related to cart rules specifically. 405 extra queries is a loooot :-)

**Comment by hibatallahAouadni** [comment] 2021-01-06 11:44
@Hlavtox well then I found the original issue #16568 (created by you) :wink: 
And you didn't answer @khouloudbelguith [comment](https://github.com/PrestaShop/PrestaShop/issues/16568#issuecomment-561128239) :confused:

**Comment by Hlavtox** [comment] 2021-01-06 11:48
@hibatallahAouadni That is some ancient issue... 😄 The queries in the other issues are not easily fixable, but we can start from the easy stuff like this one.

**Comment by hibatallahAouadni** [comment] 2021-01-06 15:20
@Hlavtox could you please provide the code and in which file I should add it , so I can reproduce it on my shop :slightly_smiling_face: 
Thanks in advance.

**Comment by Hlavtox** [comment] 2021-01-21 16:18
@hibatallahAouadni Hi, there is nothing to edit. I can send you access to our store so you can check out our cart rules. Otherwise, it's standard. 
- We have 25 active cart rules.
- 10 rules activated by a code.
- 15 rules that give a gift, if a product and group conditions are met.

**Comment by hibatallahAouadni** [comment] 2021-01-26 22:53
Hello @Hlavtox 

Following your steps, that's what I got: 

https://drive.google.com/file/d/1wO1b9OwagNgrpyCxfpEIhxxU6WP6vEH3/view

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment] 2021-01-27 08:00
Hi @hibatallahAouadni!

1. Open config/defines.inc.php
2. Add this to the beginning of the file, before `/* Debug only */`
```
if (isset($_GET['profiling'])) {
    defined('_PS_DEBUG_PROFILING_') || define('_PS_DEBUG_PROFILING_', true);
}
```
3. Now clear cookies and open your homepage with **?profiling** parameter after the URL. Check amount of queries.
4. Add and delete something from cart.
5. Try it again, you should see an increase.

**Comment by hibatallahAouadni** [comment] 2021-01-27 10:11
Hello @Hlavtox 

Could you please check the screen record below:

https://drive.google.com/file/d/10d8s6zEQDpAn9vskNZQE9qTNamSJUrOE/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-15 22:30
Hello @Hlavtox,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Hlavtox** [comment] 2021-02-17 11:43
@hibatallahAouadni Hi, I can provide you with a database dump or whatever you need, but the problem is there. All the queries come from `CartRule->checkValidity` funtion.

When you have clear cookie, all the logic is returned at the start, in `CartRule->autoAddToCart`.

```
if (!CartRule::isFeatureActive() || !Validate::isLoadedObject($context->cart)) {
  return;
}
```
This should also happen if the cart is empty. This is is 550 extra queries that are slowing the page down.

![rules](https://user-images.githubusercontent.com/6097524/108199560-81c39180-711d-11eb-9ccf-6cc475b8b758.JPG)

**Comment by Hlavtox** [comment] 2021-02-17 13:32
Disabling one of 25 active cart rules brings the total query count down to 668. Each of the 135x queries are reduced to 126x queries.

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:43
Hello @Hlavtox 

Ping @PrestaShop/prestashop-core-developers could someone help me up to reproduce the issue :sweat_smile: 
Thanks in advance.

**Comment by PierreRambaud** [comment] 2021-02-17 14:00
Queries are cached in the Db class. The whole "Cart & Cart Rules models" have to be refactored. A lot of queries are malformed. This is something we are already aware of but we can't refactor these parts without breaking everything.
This task will be done when we will be able to refactor these parts.
I'm afraid of side effects if we touch something here. Like the `autoAddToCart` or `getProducts`, I tried once, was the worst month of my life :sweat_smile:

**Comment by Hlavtox** [comment] 2021-02-17 15:38
@PierreRambaud Why does it increase load time by 200%, if it's cached? 😄

Could it be fixed by adding something like `if cart empty` here?
```
if (!CartRule::isFeatureActive() || !Validate::isLoadedObject($context->cart)) {
  return;
}
```

Also, I think all of these these calculations are done 2 times - once when assigning generalpurposevariables and then in ps_shoppingcart module. Just by calculating the cart once, we can cut the queries in half.

**Comment by PierreRambaud** [comment] 2021-02-17 16:38
> @PierreRambaud Why does it increase load time by 200%, if it's cached? 
> 
> Could it be fixed by adding something like `if cart empty` here?
> 
> ```
> if (!CartRule::isFeatureActive() || !Validate::isLoadedObject($context->cart)) {
>   return;
> }
> ```
> 
> Also, I think all of these these calculations are done 2 times - once when assigning generalpurposevariables and then in ps_shoppingcart module. Just by calculating the cart once, we can cut the queries in half.

Feel free to create a pull request if you think your condition can improve performance :wink:

**Comment by kpodemski** [comment] 2023-07-26 12:40
@Hlavtox I know in general we need improvements there, but I think some of it has been improved recently.

**Closed as completed** 2024-04-11 05:42 UTC
Labels: Feature, FO, Performance, Cart rules
