### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by viosan** [PrestaShop/PrestaShop#18497] opened 2020-04-07 13:04 UTC
Hi, at the end of January I installed the "1-Click Upgrade" module, trying to go from v 1.7.5.0 to v 1.7.6.0. As you know, the modullo creates a backup, which I find on the server:
https://www.screencast.com/t/mHKMaFKe8o
https://www.screencast.com/t/R0HRnUvkKf
In these days I tried to go back to the old version, from v 1.7.5.6 to 1.7.5.0 through this module, but when I did it everything was blocked, the site and the admin is no longer accessible, it always gives me " erroe 500 ", and I don't know how to reactivate it.

Can you help me please.

**Comment by khouloudbelguith** [comment] 2020-04-07 14:18
Hi @viosan,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - 1-click upgrade module version
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - `v1.7.5.6` did you mean PS1.7.6.3 or PS1.7.6.0?

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sarahdib** [comment] 2020-05-05 15:39
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 15:39 UTC
Labels: Bug, BO, Autoupgrade, 1.7.5.0, 1.7.6.0
