### ISSUE TITLE
Index home without "language" /xx/ was downloaded by web server

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#14067] opened 2019-06-04 09:22 UTC
**Describe the bug**
Try to open home page root without adding the language selector result in download by web server instead open page. Problem on url rewrite

**To Reproduce**
Install PS 1.7.4

Setup this rewrite scheme:

Percorso ai prodotti 
{category:/}{id}{-:id_product_attribute}-{rewrite}.html
Parole chiave: id*, id_product_attribute*, rewrite*, ean13, category, categories, reference, meta_keywords, meta_title, manufacturer, supplier, price, tags
Percorso alla categoria 
{rewrite}
Parole chiave: id, rewrite*, categories, meta_keywords, meta_title
Indirizza alla categoria che ha l'attributo "filtro selezionato" per il modulo di "Navigazione a strati" (blocklayered) 
{id}-{rewrite}{/:selected_filters}
Parole chiave: id, selected_filters*, rewrite*, categories, meta_keywords, meta_title
Percorso al fornitore 
{id}__{rewrite}
Parole chiave: id, rewrite*, meta_keywords, meta_title
Percorso alla marca 
{rewrite}
Parole chiave: id, rewrite*, meta_keywords, meta_title
Percorso pagina 
{categories:/}{rewrite}
Parole chiave: id, rewrite*, categories, meta_keywords, meta_title
Percorso pagina categoria 
{rewrite}
Parole chiave: id, rewrite*, categories, meta_keywords, meta_title
Percorso ai moduli 
module/{module}{/:controller}
Parole chiave: module*, controller*

Setup advance friendly url to avoid omision of ID in the rewrite rule.

The problem occour also with default url scheme and module disabled when setup multilanguage

Opening the home page result in the download of the page instead that open it on browser

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-04 09:33
Hi @matteolavaggi,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.4.2, PS1.7.5.2 & PS1.7.6.0BETA1.
When we navigate to the FO without "language" in the URL, there is a redirection to the language by default.
You can the demo shop in this link: http://fo.demo.prestashop.com there is a redirection to http://fo.demo.prestashop.com/fr/

Thanks to check & feedback.

**Comment by matteolavaggi** [comment] 2019-06-04 10:53
Hi its a fresh ps 1.7.4 install, any suggestions how to debug ? Have you
try using our url scheme?

Il giorno Mar 4 Giu 2019, 11:33 khouloudbelguith <notifications@github.com>
ha scritto:

**Comment by khouloudbelguith** [comment] 2019-06-04 11:24
@matteolavaggi, in your Traffic & SEO page, thanks to change the "Route to category" from `{rewrite}` to  `{id}-{rewrite}`

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-04 08:22
Hi @matteolavaggi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-04 08:22 UTC
Labels: FO, SEO & URLs, No change required
