### ISSUE TITLE
Missing carrier in Carrier restrictions in BO

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19639] opened 2020-06-09 06:00 UTC
Hello,
I use 2 shipping carriers with the same name. The reason is there are different upper limits for Europe and non-Europe countries when out-of-range behavior disables the carrier. But in BO > Payment > Preferences > Carrier restrictions is displayed only one shipping carrier. There should be displayed both. But if there were displayed the same name it wouldn't be possible to identify them. Therefore I propose to display carrier name also with transit time in brackets in Carrier restrictions..

**Comment by TristanLDD** [comment] 2020-06-10 08:18
Hello @juraj1000, thanks for your report.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration - PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
...
You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by juraj1000** [comment] 2020-06-10 09:43
Here is the configuration
![image](https://user-images.githubusercontent.com/33311857/84252958-991e9980-ab0f-11ea-8125-c54ce53a89e8.png)

**Comment by florine2623** [comment] 2020-06-11 10:07
Hi @juraj1000 ,
Could you specify the characteristics of each carrier so I can try it on my shop ?

All of the carries should be displayed In BO > Payment > Preferences > Carrier restrictions as long as the carrier exists.

**Comment by juraj1000** [comment] 2020-06-12 09:47
Hello,

1. create 1st carrier: BO > Shipping > Carriers: 
Shipping name: Shipping ABC
Transit time: 7 days
Shipping location: Europe
Price: Allow range for 0 to 1000 € with shipping price 100 €
Out range of behavior: Disable carrier

1. create 2nd carrier: BO > Shipping > Carriers: 
Shipping name: Shipping ABC
Transit time: 45 days
Shipping location: Asia
Price: Allow range for 0 to 5000 € with shipping price 200 €
Out range of behavior: Disable carrier

1. see BO > Payment > Preferences > Carrier restrictions:
Error: only one carrier Shipping ABC is visible, there should be 2 carriers
Shipping ABC (7 days)
Shipping ABC (45 days)

Carrier with transit time is displayed also in other screens, e.g. BO > Sell > Orders > Detail info > see section Shipping > Carrier

**Comment by florine2623** [comment] 2020-06-12 15:01
Hi @juraj1000 ,

Here's the PR: #12379 to fix the issue.
It is fixed in the next major release PS1.7.7.0.
Your ticket is a duplicate of #16094

So I'll close the issue.

**Closed as completed by florine2623** 2020-06-12 15:01 UTC
Labels: Carriers, No change required
