### ISSUE TITLE
Problem : Update with module 1_click upgrade v 4.16 .2    prestashop from 8.1.0 to 8.1.1 

### ISSUE THREAD

**Issue by orvalvert** [PrestaShop/PrestaShop#33835] opened 2023-09-04 15:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, sorry I'm new to prestahop. I just installed prestashop 8.1.0 (only available in 8.1 with softaculous on o2switch . I launched the module 1-click upgrade V4.16.2 to update to version 8.1.1. I'm getting errors and can't access administration and products. However, I can access products if I'm in incognito mode and if I uncheck the back office token protection box. 
 I think it's a security token problem. 
Here are the errors displayed, 
autoload_real.php line 36 - Error Class "Composer\autoload\ComposerStaticinit722257398ed85eaa39d12bc29012c839" not found #0
autoload.php(25):ComposerAutolauderInit722257398ed85eaa39d12bc29012c839::getLoader()#1
UpgradeContainer.php(567): require_once('/home/...#2
UpgradeDB.php(87) UpgradeContainer->InitPrestashopAutoloader() #3
 ajax-upgradetap.php(52) UpgradeDB->init()#4{hand}
Does anyone have a clue?   
Thanks for your help

### Expected behavior

Update with module 1_click upgrade v 4.16 .2   
prestashop from 8.1.0 to 8.1.1 
should works and no error 

### Steps to reproduce

Install prestahop 8.1.0 with Softaculous on   site  O2switch : OK 
use 1 Click upgrade v 4.16.2 to upgrade on prestashop 8.1.1

### PrestaShop version(s) where the bug happened

Upgrading from prestashop 8.1.0 to 8.1.1

### PHP version(s) where the bug happened

PHP 8.1

### If your bug is related to a module, specify its name and its version

1_click upgrade v 4.16 .2

**Comment by sallemiines** [comment] 2023-09-04 16:11
Hello @orvalvert 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #33820.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by sallemiines** [comment] 2023-09-04 16:11
Duplicate of #33820

**Closed as completed by sallemiines** 2023-09-04 16:11 UTC
Labels: Bug, Duplicate
