### ISSUE TITLE
Faceted search module returns available for order OOS products as "In stock"

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#21398] opened 2020-10-12 12:30 UTC
#### Describe the bug

Faceted search module returns available for order OOS products as "In stock".

#### Expected behavior

Only real "in stock" products (with available quantity) should be shown when applying the "in stock" filter

#### Steps to Reproduce

1. Have out of stock products that allow orders when out of stock, OOS products that do not allow orders when out of stock and real in stock products (with available quantity).
2. In faceted search, have an "Availability" filter enabled for the category.
3. Go to that category and click to show only "in stock" products"
Result: both "real" in stock products and out of stock with "allow orders when out of stock" option are shown.

#### Solution
1. Only show real in stock products
or
2. Add a new option for "Preorder" (this would be better).
Availability: In stock, Preorder, Unavailable

* PrestaShop version: 1.7.6.8
* Faceted search version: <=3.6.0

**Comment by khouloudbelguith** [comment] 2020-10-12 13:56
Hi @rdy4ever,

We are aware of this issue.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14518#issuecomment-510891464
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-10-12 13:56
Duplicate of #14518

**Closed as completed by khouloudbelguith** 2020-10-12 13:56 UTC
Labels: Duplicate
