### ISSUE TITLE
Newsletter confirmation & voucher emails when subscribing from customer account are not sent

### ISSUE THREAD

**Issue by iDrums** [PrestaShop/PrestaShop#22774] opened 2021-01-11 19:46 UTC
#### Describe the bug
When I create a customer account without checking the newsletter subscription box, then try to subscribe to the newsletter from customer account settings form, I don't receive any confirmation email / voucher.

I do receive those emails when subscribing while signing up / through the email address form on the home page.

#### Expected behavior

Receive an email confirming subscription to the newsletter and the associated promotional code by checking the box in the customer account settings.

#### Steps to Reproduce

1. Configure ps_emailsubscription module and enable "Send a confirmation email" option
2. Create an account without subscribing to the newsletter
3. Go to customer account settings and check "Subscribe to the newsletter"

#### Screenshots

![Capture d’écran 2021-01-11 à 20 39 23](https://user-images.githubusercontent.com/54487078/104230465-ea985980-544d-11eb-9ace-13d2b3f53622.png)
![Capture d’écran 2021-01-11 à 20 39 59](https://user-images.githubusercontent.com/54487078/104230500-f4ba5800-544d-11eb-8405-f900424bef09.png)

#### Additional information

PrestaShop version: 1.7.6.2
ps_emailsubscription version: 2.3.0

**Comment by hibatallahAouadni** [comment] 2021-01-12 10:45
Hello @iDrums 

Could you please check this issue #17097 I think is similar to yours 
Please check and feedback.

Thanks!

**Comment by iDrums** [comment] 2021-01-12 18:06
> Hello @iDrums
> 
> Could you please check this issue #17097 I think is similar to yours
> Please check and feedback.
> 
> Thanks!

Hello @hibatallahAouadni 

I took a look at the issue #17097 but it's not similar to mine.
Newsletter confirmation and voucher emails are correctly sent when I create a new customer account and I check "Subscribe to our newsletter" from the FO.

Thank you

**Comment by iDrums** [comment] 2021-01-19 17:27
Hello,

I haven't heard from you in a week.
Would it be possible to get more information about how to solve my problem?

Thank you !

**Comment by hibatallahAouadni** [comment] 2021-01-19 18:30
Hello @iDrums 

Sorry for the late response, but I encountred an issue with email configuration :confused: 
@PrestaShop/qa-functional could someone please try to reproduce the issue.

Thanks in advance.

**Comment by hibatallahAouadni** [comment] 2021-01-20 13:57
Hello @iDrums 

I asked @SD1982 to reproduce the issue, and he tried to subscribe in Newsletter with two ways, and both of them works:

Subscribe to newsletter from homepage:
https://drive.google.com/file/d/1bpWGQI8T9N0r5qKNhFn3GwGUj22t01xE/view

Subscribe to newsletter from My Account:
https://drive.google.com/file/d/1EDd56RzwpcCuDMSvNFjGQjWjxaYndUzk/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-09 09:41
Hello @iDrums ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-09 09:41 UTC
Labels: Bug, FO, Customer, Email, Emailsubscription, No change required, 1.7.6.2

**Comment by iDrums** [comment] 2021-02-11 13:53
Hi @hibatallahAouadni ,

Sorry for the late reply.
Could you please try to do the same as the second video you sent above, without checking "Recevoir les offres de nos partenaires" ?

I've disabled this option and it is not displayed on my website.

Thank you !

**Comment by hibatallahAouadni** [comment] 2021-02-11 22:04
@iDrums could you please provide a screen record. Thanks!
