### ISSUE TITLE
Google Analytics - Enhanced Ecommerce reports - Shopping Behavior Analysis missing funnel data

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/PrestaShop#26619] opened 2021-11-15 15:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, I noticed that with the most recent versions of ps_googleanalytics the data seems not to be send to analytics, at least not at 100%.
In detail, I just noticed that with version 4.1 the steps in the mid are completely empy (0%) while at the beginning and at the end of the funnel we have data.
Am I the only one having this issue?

![funnel](https://user-images.githubusercontent.com/731916/141807552-55a1d0bd-4564-4b4a-b437-6babf57897b0.jpg)

ps_googleanalytics version is 4.1

### Expected behavior

The funnel in Analytics should show data more then 0 in all the steps.

### Steps to reproduce

1. install and configure ps_analytics,
2. wait a few days,
3. check analytics on "Enhanced Ecommerce reports" - "Shopping Behavior Analysis" and see if there is data.

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_googleanalytics

**Comment by hibatallahAouadni** [comment] 2021-11-16 10:51
Hello @masiorama 

Your issue is similar to this one (check this [comment](https://github.com/PrestaShop/PrestaShop/issues/26091#issuecomment-944216328)).
As you can see in the comment we weren't able to reproduce the issue.
Please check and feedback.

Thanks!

**Comment by masiorama** [comment] 2021-11-17 07:41
Hello @hibatallahAouadni 
Thank you but I don't think it is the same issue. I can actually track visits and get data. My main concern is as regards funnel data inside Analytics - Enhanced Ecommerce reports section (which I believe is not active by default when creating a property in analytics). Inside that report, I can only see what you can get from the image I attached in the previous comment, which is: I can get all the sessions, and I can track all sessions with transactions, but no details in the mid steps, which are add to cart, abandon cart, abandon during checkout.

Till May 2020, with the previous versions of PS and Analytics module (dunno the versions but I could dig deep inside my upgrades of one year ago if needed) I was able to track that data, which now is gone.

**Comment by khouloudbelguith** [comment] 2021-11-18 15:50
Hi @masiorama,

Thanks for your feedback.
We could not reproduce your issue with the provided information.
It will help us if you can attach a screen record.


Thank you!

**Comment by masiorama** [comment] 2021-11-20 10:12
Hello @khouloudbelguith
A screencast of what precisely?
Thank you!

**Comment by florine2623** [comment] 2021-11-22 08:41
Hello @masiorama ,

A screen record where the info of your BO would show up when on the module ps_googleanalytics it is empty.

**Comment by masiorama** [comment] 2021-11-22 09:02
Hello @florine2623,
I'm sorry but I don't understand what you are saying.
There is nothing wrong with the BO of Prestashop. The ps_googleanalytics if conrrectly configured with its tracking id, and the other settings you can see in the image attached.

![ps_analytics](https://user-images.githubusercontent.com/731916/142832218-c10582dd-5e6d-483d-9567-60f7dca2ebd9.jpg)

With these configuration I can correctly track on Google Analytics Dashboard, visualizations and conversions, but not the data of the funnel (as it is clear in the image attached on the first message of the issue). In my opinion there is something wrong with how analytics script sends data, but I don't get how I should "screen record" something like this to show it to you.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-22 16:58
Hello @masiorama 

Thanks for your feedback :pray: 
So, before upgrading the GoogleAnalytics module, it use to display all the data, but after the upgrade it doesn't show any data concern "Enhanced Ecommerce reports" - "Shopping Behavior Analysis". Is that so?
If so, what was your previous GoogleAnalytics version?
Please check and feedback.

Thanks!

**Comment by masiorama** [comment] 2021-11-22 18:37
Hi @hibatallahAouadni 
Almost.
Below you can see what was tracked last time I got data (May 2020):

![funnel-may-2020](https://user-images.githubusercontent.com/731916/142916073-fb605387-2f21-42fe-90dd-e948ea696adb.jpg)

Here you can see the situation today:

![funnel-now](https://user-images.githubusercontent.com/731916/142916125-87c97365-05fe-4346-abbe-c6124675f93a.jpg)

Only the data "in the middle" is missing.

From my git repo I cannot track anything related that far in the past, but I know I made an upgrade of ps_googleanalytics on September 2020 from version 3.2 to 4.0.

**Comment by hibatallahAouadni** [comment] 2021-12-01 15:05
Hello @masiorama 

I see, thanks for your feedback :pray: 
Ping @PrestaShop/prestashop-core-developers can someone please try to reproduce this issue :pray: 

Thanks!

**Comment by jf-viguier** [comment] 2021-12-01 15:15
I don't think that the funnel is covered by ps_googleanalytics module, it's a specific setting un Google Analytics.
Funnel analysis is usually set with url settings or custom data send in javascript so maybe you've changed this ?

**Comment by masiorama** [comment] 2021-12-06 18:04
@jf-viguier I don't get it: til mid 2020 it was covered by the same module... now it seems not to be supported? I didn't add any custom js script inside my template, I am leveraging only on the module functionality.

**Comment by masiorama** [comment] 2022-01-15 10:46
Hello, are there any further considerations to make about this or it is not worth the attention/context?
Just to know, thanks!

**Comment by Hlavtox** [comment] 2023-07-25 22:56
Universal analytics is dead and removed from the module, closing.

**Closed as completed by Hlavtox** 2023-07-25 22:56 UTC
Labels: Bug, BO, Google Analytics, 1.7.7.4, Invalid, Module
