### ISSUE TITLE
Remove Tools::addonsRequest on AdminPsThemeCustoConfiguration.php (line 534)

### ISSUE THREAD

**Issue by cdigruttola** [PrestaShop/PrestaShop#27432] opened 2022-01-21 16:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

HI,
I'm having the following problem when I try to use the Pages Configuration in BackOffice
![image](https://user-images.githubusercontent.com/9153905/150562067-3e52032c-f321-46fc-8ea0-59b18b5c9d61.png)

### Steps to reproduce

1. Go to BackOffice
2. Design
3. Themes & logo
4. Pages Configuration

### PrestaShop version(s) where the bug happened

8.0

**Comment by PrestaEdit** [comment] 2022-01-23 21:01
I think that this merged pull request solve this: https://github.com/PrestaShop/ps_themecusto/pull/47

**Comment by florine2623** [comment] 2022-01-24 08:38
Hello @cdigruttola ,

As @PrestaEdit said, the issue is fixed with this PR : [PrestaShop/ps_themecusto#47](https://github.com/PrestaShop/ps_themecusto/pull/47)

So I close this issue.
Thanks!

**Closed as completed by florine2623** 2022-01-24 08:38 UTC
Labels: Bug, Fixed
