### ISSUE TITLE
Wire payment Module - doesn't display order amount

### ISSUE THREAD

**Issue by annadumi** [PrestaShop/PrestaShop#30794] opened 2023-01-10 15:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I noticed that the wire payment module version 2.1.3 no longer displays the order value; I spoke on the prestashop support chat with a person who helped me with previous versions (2.1.2., 2.1.1 and 2.1.0) with the idea that maybe an older version works and still does not display the order value. I don't know if this module ever worked correctly, today a customer told us that he doesn't know how much he has to pay and so I noticed that the module doesn't display the payment amount.

Thank you

### Expected behavior

Display of order amount and payment details (account name, etc.). With the other details there is no problem, it displays them, only the order amount is not displayed

### Steps to reproduce

1. Place an order with a wire bank transfer option
2. On the order confirmation page a table with payment details is displayed. In this table, the order amount is not displayed

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

ps_wirepayment v2.1.3, ps_wirepayment v2.1.2, ps_wirepayment v2.1.1, ps_wirepayment v2.1.0

**Comment by paulnoelcholot** [comment] 2023-01-10 15:58
Hello @annadumi ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10912.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed by paulnoelcholot** 2023-01-10 15:58 UTC
Labels: Bug, Duplicate
