### ISSUE TITLE
Error on SitemapFrontController 

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#10657] opened 2018-09-24 07:25 UTC
**Describe the bug**
Undefined index $categories on sitemapfrontcontroller

**To Reproduce**
1. Go to sitemap front page

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![capture d ecran 2018-09-24 a 09 18 41](https://user-images.githubusercontent.com/4788787/45940744-14a68300-bfdb-11e8-85ca-5476f5a07ae1.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Fix**
Update SitemapController.php
change this method: 
``` 
public function initContent()
    {
        $this->context->smarty->assign(
            array(
                'our_offers' => $this->trans('Our Offers', array(), 'Shop.Theme.Global'),
                'categories' => $this->trans('Categories', array(), 'Shop.Theme.Catalog'),
                'your_account' => $this->trans('Your account', array(), 'Shop.Theme.Customeraccount'),
                'pages' => $this->trans('Pages', array(), 'Shop.Theme.Catalog'),
                'links' => array(
                    'offers' => $this->getOffersLinks(),
                    'pages' => $this->getPagesLinks(),
                    'user_account' => $this->getUserAccountLinks(),
                    'categories' => $this->getCategoriesLinks(),
                ),
            )
        );

        parent::initContent();
        $this->setTemplate('cms/sitemap');
    }
```

by:
```
 public function initContent()
    {
        parent::initContent();
        $this->context->smarty->assign(
            array(
                'our_offers' => $this->trans('Our Offers', array(), 'Shop.Theme.Global'),
                'categories' => $this->trans('Categories', array(), 'Shop.Theme.Catalog'),
                'your_account' => $this->trans('Your account', array(), 'Shop.Theme.Customeraccount'),
                'pages' => $this->trans('Pages', array(), 'Shop.Theme.Catalog'),
                'links' => array(
                    'offers' => $this->getOffersLinks(),
                    'pages' => $this->getPagesLinks(),
                    'user_account' => $this->getUserAccountLinks(),
                    'categories' => $this->getCategoriesLinks(),
                ),
            )
        );

        
        $this->setTemplate('cms/sitemap');
    }
```
put the
```
parent::initContent() 
```
before the assign 
And it's fixed ;)

**Comment by khouloudbelguith** [comment] 2018-09-24 09:16
Hi @PrestaSafe,

Thanks for your report.
I did not manage to reproduce your issue with the last version 1.7.4.2 without any changes.
I attached a video record.
https://drive.google.com/file/d/1xeHKrBiEQs_hZi6WQdzUNWQhWtQzi0s0/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by MathiasReker** [comment] 2018-09-24 09:17
PR: https://github.com/PrestaShop/PrestaShop/pull/10660

**Comment by MathiasReker** [comment] 2018-09-24 09:23
I closed my PR again, @PrestaSafe did you put some custom code eg.      `$this->setTemplate('module:mymodule/views/templates/front/display.tpl');` before `parent::initContent();` ?

**Comment by matks** [comment] 2018-09-24 09:47
Hi @PrestaSafe it's good to see you on prestashop github 😄 thanks for the bug report !

**Comment by PrestaSafe** [comment] 2018-09-24 15:35
No, it's really weird, i've made a clean install, and it's ok, but from an update it didn't works. 
I've tried with original template too, tried to change classes/ controllers/ src/ and app/ folder but not changing. If i move the parent::initContent() it's working fine... 

I've tried to disable modules of course and not changing too. 
If someone have an idea. I'll take it ! 

@Mreker no i've not putting some code before that.

**Comment by khouloudbelguith** [comment] 2018-09-24 15:56
Hi @PrestaSafe,

What is the exact version of the 1-click upgrade did you use?
What the previous version Prestashop did you use before the upgrade?

Best regards, Khouloud

**Comment by PrestaSafe** [comment] 2018-09-25 07:22
@khouloudbelguith I've used the V4.2.0 the previous was 1.7.3.0

**Comment by khouloudbelguith** [comment] 2018-09-25 07:38
Hi @PrestaSafe,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-25 10:48
Hi @PrestaSafe,

I did not manage to reproduce your issue, after upgrade from 1.7.3.0 to 1.7.4.2 using the 1-click upgrade v4.3.0: https://github.com/PrestaShop/autoupgrade/releases/tag/v4.3.0
The sitemap page is OK.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-25 16:54
Hi @PrestaSafe,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-25 16:54 UTC
Labels: Bug, FO, No change required, 1.7.4.2
