### ISSUE TITLE
Cart rule is  not removed from the cart when it expires

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#23933] opened 2021-04-08 09:43 UTC
#### Describe the bug

When a cart rule is applied in the cart and it expires, it is not removed from the cart. The customer can finish the order with the cart rule applied.

#### Steps to Reproduce

1. Create a cart rule that expires in 5 minutes (for example)
![image](https://user-images.githubusercontent.com/15104724/114001817-93dbc980-985c-11eb-9c64-165c166bfc7a.png)

2. Add a product to the cart and check that cart rule has been added automatically
![image](https://user-images.githubusercontent.com/15104724/114004455-f7ff8d00-985e-11eb-910f-dcb280efc592.png)

3. Wait for 5 minutes, until the cart rule expires

4. Finish the order. The cart rule is expired but it has been applied:
![image](https://user-images.githubusercontent.com/15104724/114005120-8bd15900-985f-11eb-9e89-db71fb1926ad.png)

#### Additional information

* PrestaShop version: 1.7.7.3

**Comment by florine2623** [comment] 2021-04-08 10:04
Hello @idnovate ,
Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/20009

Please check and feedback.
Thanks!

**Closed as completed** 2021-04-08 10:23 UTC
Labels: Discounts, Cart rules, 1.7.7.x

**Comment by idnovate** [comment] 2023-07-15 19:29
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19393 too
