### ISSUE TITLE
Faceted search Module - Price filter work only on gross price (no discounted)

### ISSUE THREAD

**Issue by Sg-nipe** [PrestaShop/PrestaShop#22621] opened 2020-12-29 17:02 UTC
#### Describe the bug

When we try to apply price filter this work only on gross price, no on discounted price (made on products page, pricing tabs, specific price session).

Try to enable/disable 

#### Steps to Reproduce

1. Generate a specific price for a product
2. Enable on Faceted search modules template the price filter
3. Try to filter

**Screenshots**
Before:
![2020-12-29 17_45_21-Window](https://user-images.githubusercontent.com/57758981/103300133-78138c80-49fe-11eb-87ad-1ce1dab2679b.png)

After (no more product of the first image):
![2020-12-29 17_45_57-Window](https://user-images.githubusercontent.com/57758981/103300138-7cd84080-49fe-11eb-9341-4388ed081044.png)

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.3.1
* Module Version: 3.7

**Comment by hibatallahAouadni** [comment] 2020-12-30 10:13
Hello @Sg-nipe 

Thanks for your issue :slightly_smiling_face: 
I reproduced your issue with PS1.7.6.9 and only with FacetedSearch v3.7, cause with FacetedSearch v3.5 I didn't manage to reproduce it, see the attached screen record below:

https://drive.google.com/file/d/15ESPLMQAZvrLbWqzZNZF1WsKCeXJfaqY/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

**PS: you need to downgrade your PHP version to 7.2 cause it's not compatible with PS version, see [our sysem requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements)**

Thank you

**Comment by PierreRambaud** [comment] 2020-12-30 14:31
Seems to be a duplicate of #16822 :thinking:

**Comment by hibatallahAouadni** [comment] 2020-12-30 15:04
Hello @PierreRambaud 

I didn't manage to reproduce it with FacetedSearch v3.5
While #16822 I reproduced it with v3.5 
So, I think it's related but not duplicated :wink: 
But, I will test your PR and see if it could fix both issues.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-01 16:05
Hello @PierreRambaud 

I tested your PR, I didn't encounter this issue neither #16822, see the attached screen record below:

https://drive.google.com/file/d/16I_06olq6KPyLzPJKUtnzjgW4Ncj9n5-/view

But, I encounter this problem, see the attached screen record below:

https://drive.google.com/file/d/152dmHzv-E9TpoMS0PAwdIqCE_Jbq0EJU/view

When I choose the price range from 1,251.000 to 1,500.000, I had no product displayed but the pagination indicates that there's a product and that's right cause the product should be displayed.

Could you please checked :slightly_smiling_face: 
Thanks!

**Comment by PierreRambaud** [comment] 2021-01-04 08:53
> Hello @PierreRambaud
> 
> I tested your PR, I didn't encounter this issue neither #16822, see the attached screen record below:
> 
> https://drive.google.com/file/d/16I_06olq6KPyLzPJKUtnzjgW4Ncj9n5-/view
> 
> But, I encounter this problem, see the attached screen record below:
> 
> https://drive.google.com/file/d/152dmHzv-E9TpoMS0PAwdIqCE_Jbq0EJU/view
> 
> When I choose the price range from 1,251.000 to 1,500.000, I had no product displayed but the pagination indicates that there's a product and that's right cause the product should be displayed.
> 
> Could you please checked 
> Thanks!

This is a known issue :+1:

**Comment by hibatallahAouadni** [comment] 2022-02-15 19:56
Hello everyone,

This issue has been fixed :tada: 

![image](https://user-images.githubusercontent.com/23308427/154138959-a96d4695-1db2-4b85-81f1-9ca468ef0020.png)

Thanks!

**Closed as completed by hibatallahAouadni** 2022-02-15 19:56 UTC
Labels: Bug, Minor, FO, Faceted search, Regression, Fixed, 1.7.6.9, Verified, Module
