### ISSUE TITLE
Price after saving 1.7.6.1

### ISSUE THREAD

**Issue by TamasFelix** [PrestaShop/PrestaShop#16738] opened 2019-12-09 05:23 UTC
Hi, After I added a product and set the price with taxes 205RON and wholesale price 31,49RON, I save the product.
![1](https://user-images.githubusercontent.com/50567469/70409121-4f1b0500-1a53-11ea-8d60-c8d4593f5653.JPG)
After saving, the price changes to, price with taxes 204.999999RON and wholesale price 31,490000.
![2](https://user-images.githubusercontent.com/50567469/70409202-a15c2600-1a53-11ea-8810-99f2c6e694c3.JPG)
I exported the products to csv.
![3](https://user-images.githubusercontent.com/50567469/70409422-673f5400-1a54-11ea-822e-de5462bb8abc.JPG)
The price price with taxes is 31490000 and wholesale price 204999999

How can I make it look price just 31.49 and 205?

Thanks

**Comment by khouloudbelguith** [comment] 2019-12-09 10:18
Hi @TamasFelix,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12078
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-09 10:19
Duplicate of #12078

**Closed as completed by khouloudbelguith** 2019-12-09 10:18 UTC
Labels: Duplicate
