### ISSUE TITLE
Unable to edit category

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#19967] opened 2020-06-26 19:30 UTC
#### Describe the bug

I am still unable to save shop category. After form submitting I can see error `PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryConstraintException code 6`:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/3767861/85894001-33f7c300-b7f4-11ea-9e00-666d74b52dd3.png">

Problem is because this radio button is disabled, so I am unable to select it:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/3767861/85893318-f3e41080-b7f2-11ea-9557-639d4e63999d.png">

When I manually enable it with development tools it works:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/3767861/85894039-4114b200-b7f4-11ea-90e4-9954d64d7242.png">

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2
* Related to:
- https://github.com/PrestaShop/PrestaShop/issues/15140
- https://github.com/PrestaShop/PrestaShop/issues/15174

**Comment by Progi1984** [comment] 2020-06-29 08:39
Could you please provide us with more info? 
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).Thank you!

**Comment by Flower7C3** [comment] 2020-06-29 17:18
There are no extra logs. This option is just set as disabled, so it is not send with post data.

**Comment by Progi1984** [comment] 2020-06-30 13:33
@Flower7C3 I need to a scenario for reproducing the issue ("Go on BO >  Page X", "Disable X", "Add X").

**Comment by Flower7C3** [comment] 2020-06-30 14:28
1. Go to BO > Catalogue > Categories
2. Click Edit at any category
3. In section "Parent category" the root category radio button is checked but disabled, so it will not be posted.

**Comment by Progi1984** [comment] 2020-06-30 14:54
In 1.7.7.x, I have no problem :

![image](https://user-images.githubusercontent.com/1533248/86140545-4114fa80-baf1-11ea-982e-62de5032b31a.png)

And 1.7.6.x, No problem too : 

![image](https://user-images.githubusercontent.com/1533248/86141284-28f1ab00-baf2-11ea-817d-185dbbed2bf6.png)

Which steps do it lack for reproducing your bug ?

**Comment by Flower7C3** [comment] 2020-06-30 15:33
I use multishop and I have some third party modules installed.

I was looking in source code and probably the problem is here: https://github.com/PrestaShop/PrestaShop/commit/77c5b5402b39b66d94013ecedddbd2cde1190401#diff-27526556d82b1fc61eb6c6151345c9d8R47, where root category is disabled. When I comment out line it works. I have no idea why it is there.

**Comment by matks** [comment] 2020-07-21 21:23
Despite multiple attempts we cannot reproduce this bug. It is very likely it does come from a specific setting/config on your side, it can be server side configuration, it can be 3rd party module, it can be custom code. I close this issue as we cannot fix something that we cannot reproduce.

This does not mean this discussion is over 😉 if you find some more infos we might understand what's going on and maybe reopen the issue if we find a way to reproduce your behavior. But "open" issues are "things that we know what need to do / what we need to fix" and this issue does not meet this definition

**Closed as completed by matks** 2020-07-21 21:23 UTC
Labels: Bug, BO, Categories, 1.7.6.5, Invalid

**Comment by Flower7C3** [comment] 2020-07-27 18:17
@matks thanks for debugging. I will back with info if I find any info about this problem.

**Comment by greenwebtester** [comment] 2020-12-18 04:33
Hi,
I have the same problem when upgrade from ps 1.6 to ps 1.7. and I find a solution to my problem.
![Screenshot_4](https://user-images.githubusercontent.com/76195041/102575042-d732f080-4124-11eb-8dfc-711a3db36449.png)

![Screenshot_3](https://user-images.githubusercontent.com/76195041/102574937-976c0900-4124-11eb-96d3-f00e24d6dce7.png)

Hope that helps someone already have upgraded

**Comment by Triloworld** [comment] 2023-08-17 16:06
Yes. We get same issue when migrating site. 
I confirm that @greenwebtester solution working. It happen on PS 1.7.8.8.
It wasn't module to update store.
Our scenario take 2 shop and Export production -> Import to shop when we clear DB from example data by removing it (when you remove categories your settings stay same and now you can MUST import ID that setting point to it)
Created scenario where you have two show, one on domain X and one on Y and use export with different category root setting than version where you import (production shop on default one).

We get:
PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryConstraintException code 0 (after import when I try to enable by removing "disabled" property on FE when editing root category to setup it)
PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryConstraintException code 6 (for doing 1 screen only when I miss "PS_ROOT_CATEGORY" entry change)

@hibatallahAouadni can you try our scenario to re-enable issue if that's true?
