### ISSUE TITLE
Subcategory template problems

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25850] opened 2021-09-11 09:29 UTC
#### Describe the bug

In prestashop 1.7.8 with recent changes to fix CLS, fixed values for width and heigh has been added to template. That causing problem when someone is adding images with different ratio than has been assumed.

#### Expected behavior

Category page subcategories - [this lines](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0-build/themes/classic/templates/catalog/_partials/subcategories.tpl#L36), value should be `$subcategory.image.large.width` and `$subcategory.image.large.height`.

We should also remove usage of `$link` inside [template](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0-build/themes/classic/templates/catalog/_partials/subcategories.tpl#L34), `$subcategory.url` is available. 

#### Steps to Reproduce

1. In BO go to Desing->Images settings.
2. Edit image `category_default` width and height to for example 280 height and 141 width. Save it. 
3. Scroll down to **Regenerate thumbnails**, check `Erase previous images` and click `Regenerate thumbnails` button. 
4. Go to front page and clear webpage cache to download latest images. 
5. Images should be bad displayed. 

**Screenshots**
<img width="251" alt="Zrzut ekranu 2021-09-11 o 11 28 36" src="https://user-images.githubusercontent.com/25306716/132943253-9fb4236c-26d9-4644-a905-ac69bd4ba5e9.png">

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by florine2623** [comment] 2021-09-14 09:23
Hello @Oksydan ,

I was able to reproduce the issue with PrestaShop version 1.7.8.x, so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2021-10-14 18:19 UTC
Labels: Bug, Minor, FO, Image, 1.7.4.2, PR available

**Comment by matks** [comment] 2021-10-21 16:27
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25856

I think @Hlavtox mentioned some bugs related to image recently. Is that this one?
