### ISSUE TITLE
Number of decimals in shop preferences has no impact to prices

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#14283] opened 2019-06-19 09:57 UTC
**Describe the bug**
Number of decimals in `Configure > Shop Parameters > General` does not impact any price - nor frontOffice products, nor any of backOffice price fields. In addition, the `number of decimals` form field allows to set infinite value, but what would make sense is to limit it to 6 as the field in database only has 6 decimals.

**To Reproduce**
1. Go to `Configure > Shop Parameters > General`
2. Change `Number of decimals` value and save. ( In this step you can also see, that it's possible to adjust the value to more than 6. Screenshot 1 - saved with value of 5000)
3. Check any page which contains price. For example Sell > Catalog > Products or FrontOffice landing page.
4. See that prices are not rounded based on configured decimal point.

**Screenshots**
1. ![Screenshot from 2019-06-19 12-47-20](https://user-images.githubusercontent.com/31609858/59755360-75c06600-9290-11e9-996a-bc52f9953088.png)
2.  ![Screenshot from 2019-06-19 12-49-55](https://user-images.githubusercontent.com/31609858/59755887-61c93400-9291-11e9-8f94-d280eed6b302.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-19 10:09
Hi @zuk3975,

It's planned to remove the number of decimal parameters in Shop parameters > General.
You can follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/12223
And it's also planned to add this feature in CLDR part 2: #11660

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-19 10:09
Duplicate of #12223

**Closed as completed by khouloudbelguith** 2019-06-19 10:09 UTC
Labels: Duplicate

**Comment by zuk3975** [comment] 2019-06-19 10:29
Oh sorry, didn't notice the issue. Okay, thanks.
