### ISSUE TITLE
BO - Employees - Exception when adding an avatar with wrong extension

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29627] opened 2022-09-13 16:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When adding an image with extension not allowed, there's an exception displayed : <img width="1208" alt="Screenshot 2022-09-13 at 18 19 38" src="https://user-images.githubusercontent.com/16019289/189954442-d2a39bf5-b937-4da2-8573-604bf2cd3ed6.png">

This is not a regression as 1.7.7.8 did not have the feature.

### Expected behavior

The message should be more explicit.
Something like : Image format "svg", not recognized, allowed formats are: gif, jpg, jpeg, jpe, png, webp

To confirm with @PrestaShop/product-team 

### Steps to reproduce

1. Go to BO > Advanced Parameters > Employees > Edit employee
2. Add avatar with extension .svg
3. Save
4. See error : An unexpected error occurred [PrestaShop\PrestaShop\Core\Image\Uploader\Exception\UploadedImageConstraintException code 2]: Image format "svg", not recognized, allowed formats are: gif, jpg, jpeg, jpe, png, webp

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.x, develop

### PHP version(s) where the bug happened

7.4

**Comment by leemyongpakvn** [comment] 2022-09-14 01:20
@florine2623 This error message is similar to the expected result of [PR 29022](https://github.com/PrestaShop/PrestaShop/pull/29022) for Product. I think it is Explicit enough, without UploadedImageConstraintException code it will be Implicit. 
Furthermore, this issue may be a duplicate of [issue 28985](https://github.com/PrestaShop/PrestaShop/issues/28985)

**Comment by hibatallahAouadni** [comment] 2022-09-14 15:08
Hello @florine2623 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28985. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @leemyongpakvn you rock :raised_hands: :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-09-14 15:08
Duplicate of #28985

**Closed as completed by hibatallahAouadni** 2022-09-14 15:08 UTC
Labels: Bug, BO, Duplicate, Employees, Profiles, Invalid, 1.7.8.7
