### ISSUE TITLE
How can I add an attribute (s) to one of the combination WITHOUT deleting / recreating this / these combinations?

### ISSUE THREAD

**Issue by wikao2** [PrestaShop/PrestaShop#14712] opened 2019-07-17 14:00 UTC
I have several products where I created product combinations with only one attribute (**Color** for example) :
T-shirt Color Blue
T-shirt Color Red

Today, I would like to add an attribute to my product combinations (**Size** attribute for example). Which would give:
T-shirt Color Blue **Size L**
T-shirt Color Red **Size L**

The only way I found (with Prestashop 1.7.5.1) is to **remove my existing product combinations** and **recreate these combinations by adding one or more attributes**.

On Prestashop 1.6.1.5 I could do it easily and intuitively, but not under Prestashop 1.7.5.1. On Prestashop 1.6.1.5, I went to **_Combinations_** tab, I selected combination where I wanted to add an attribute (or more), I clicked on attribute in the drop menu, I clicked on value I wanted to add and then, I clicked on **_Save_**. That was all. It was as simple as that.

On Prestashop 1.7.5.1, I've tried to check the combination that I want to edit. Then I click (on right) on the attribute(s) that I want to add. The attribute(s) in question is added in 1.
![add-attributes-to-combinations](https://user-images.githubusercontent.com/48359467/61379201-5aed0b80-a8a7-11e9-9f88-fefb666d88a7.jpg)

There, if I click **_Generate_**, **it creates a (new) combination** with the attributes checked, but **it does not edit the existing combination** by adding the selected attributes.
If (instead of clicking on **_Generate_**) I click **_Save_**, it refreshes the page, it unchecks the selected combination and that's all, nothing happens; **it does not add the selected attributes either**.

I also clicked the pencil, on right,on the same line as the combination I want to edit, but here I can not choose which attributes to add.
![edit-combination](https://user-images.githubusercontent.com/48359467/61379591-1f9f0c80-a8a8-11e9-80ae-3936acd3af90.jpg)

So, **how can I add an attribute (s) to one of the combinations WITHOUT deleting / recreating this / these combinations?**

Thank you in advance for your reply

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-17 14:06
Hi @wikao2,

We are aware of this improvement, it is added to our debug roadmap.
Your ticket is a duplicate of #11652
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-17 14:06
Duplicate of #11652

**Closed by khouloudbelguith** 2019-07-17 14:06 UTC
