### ISSUE TITLE
Image not rendering for multilanguage product

### ISSUE THREAD

**Issue by TVBZ** [PrestaShop/PrestaShop#20031] opened 2020-07-02 13:03 UTC
#### Describe the bug

In a multilanguage site, when adding a product in only default language, the title is copied to other languages.
But the images for the product don't render in front end, because the rendered <img> source has no name.
For example: `<img src="mysite.com/33-home_default/.jpg">`

The problem does not excist when the product title is entered in all languages.
It's a problem of the image name not inheriting product name from default language correctly.

#### Expected behavior

When adding a product in default language, without giving the product a different title in other languages, the images should get the product title from default language.

#### Steps to Reproduce

1. Install fresh PS using multiple languages. (English is default in my case, I added Dutch as second language)
2. Add a product but only give it a title in English
3. Save the product an go to front office.
4. The image is rendered in default language but  not in second language, because it has no name (for example ".../33-home_default/.jpg")

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-07-02 13:34
Hi @TVBZ ,
I cant' reproduce your issue in my PS 1.7.6.5 shop.
Please make sure you follow PrestaShop's system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by TVBZ** [comment] 2020-07-02 15:11
Hi @florine2623, 

Just downgraded to php 7.2. My system requirements are now up to par. 
But maybe my steps to reproduce were not detailed enough... I modified my original post.

The image renders fine in default language (English), but **not in secondary language** (in my case Dutch) the image is not rendered because the img src is calling the unnamed image.

**Comment by TVBZ** [comment] 2020-07-02 15:13
For now I have a simple workaround: I copy my product title to secondary language before save.

**Comment by florine2623** [comment] 2020-07-03 09:14
Ok @TVBZ 
Normally the titles are copied automatically in all languages if only one language has been filled.
You might have some deeper issues.
Can you check your log file to see if there are errors ? in /var/log

**Comment by TVBZ** [comment] 2020-07-03 16:19
Hi @florine2623. Indeed the title are copied to other languages when only 1 language has been filled.
That part works as expected.

The images that are added in first creation of the product don't render in the other languages, because the url is missing the filename. So my best guess is that the image name is created before the title is copied to the other language. (when title is still empty)

This was in a fresh PS 1.7.6.5 installation, starting with first products I created.

I will do some more testing on fresh install and check the logs after the weekend.
Thanks for the follow up.

**Comment by florine2623** [comment] 2020-07-09 12:14
Ok thanks for letting me know.

You can also check your log file.

**Comment by florine2623** [comment] 2020-07-24 10:16
Hi @TVBZ ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by florine2623** 2020-07-24 10:16 UTC
Labels: FO, Languages, No change required, 1.7.6.5
