### ISSUE TITLE
 Prestashop can not write to the TMP folder

### ISSUE THREAD

**Issue by AntonioManta** [PrestaShop/PrestaShop#12153] opened 2019-01-14 16:41 UTC
![errore](https://user-images.githubusercontent.com/46569923/51126499-9a1ca000-1823-11e9-9f34-f493ee3de18c.jpg)

**Comment by AntonioManta** [comment] 2019-01-14 16:44
![errore2](https://user-images.githubusercontent.com/46569923/51126654-faabdd00-1823-11e9-82cc-f6284bed6f04.jpg)

**Comment by marionf** [comment] 2019-01-15 08:21
Duplicate of #11939

**Closed as completed by marionf** 2019-01-15 08:21 UTC
Labels: Duplicate
