### ISSUE TITLE
The fields in the BO address form must be optional.

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17549] opened 2020-02-07 10:32 UTC
Customer address form in BO now should always render all fields as optional, only requiring the first name, last name, address1, country and city.

**Comment by zuk3975** [comment] 2020-02-12 11:19
https://github.com/PrestaShop/PrestaShop/pull/17526

**Comment by Progi1984** [comment] 2020-03-26 08:32
Fixed by #17526

**Comment by zuk3975** [comment] 2020-03-26 08:52
Just to note, the issue is not 100% solved as in description. To avoid issues in FO, I still had to leave some fields required by the country( which is checked dynamically through javascript) as it was made before. Anyway, as planned, everything else with addresses should be fixed in next versions.

**Comment by jolelievre** [comment] 2020-03-26 12:30
Ok, thank you @zuk3975 
As explained further improvement will be done in next versions, this epic covers all the expected improvement: https://github.com/PrestaShop/PrestaShop/issues/17550

**Closed as completed by jolelievre** 2020-03-26 12:30 UTC
Labels: Improvement, Addresses, Fixed, migration
