### ISSUE TITLE
docker-compose up fails due to issue with composer

### ISSUE THREAD

**Issue by bartoszbrozek** [PrestaShop/PrestaShop#25925] opened 2021-09-19 11:28 UTC
#### Describe the bug

Running docker-compose up fails due to this error:

`/var/www/html/vendor/composer does not exist and could not be created.`

#### Expected behavior

Running docker-compose up should create a working Presta environment.

#### Steps to Reproduce

1. Clone project (develop branch)
2. Follow these instructions: [readme](https://github.com/PrestaShop/PrestaShop#docker-compose)
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/9077176/133925751-8d0f1bb5-48d5-4c91-9cda-14eed434e658.png)

#### Additional information

* PrestaShop version: latest from develop branch
* PHP version: 7.4.23
* System: linux (ubuntu minimal 20)

**Comment by hibatallahAouadni** [comment] 2021-09-20 09:45
Hello @bartoszbrozek 

You're missing some steps that's why you gets some errors!
After git clone, you need to install the composer:
`composer install`
Then, you need to install the assets:
`make install`
Now, you can execute the :
`docker-compose up`
Please check and feedback.

Thanks!

**Comment by bartoszbrozek** [comment] 2021-09-20 11:14
Hello @hibatallahAouadni,

Thanks for your response, but method you provided causes the same errors and requires me to install php, composer, all required php extensions and "make" program on my server rather than the docker container itself, which is really bad.

The whole stack should run correctly using single `docker-compose up` command and without the need to have php and composer installed on host machine. These things should already be installed within docker webserver container.

**Comment by hibatallahAouadni** [comment] 2021-09-20 15:56
Hello @bartoszbrozek 

@SD1982 was able to reproduce the issue with develop. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks @SD1982 
Ping @PrestaShop/prestashop-core-developers wdyt? should we fix the issue in Docker or Core?

Thank you

**Comment by PierreRambaud** [comment] 2021-09-21 06:28
> Hello @hibatallahAouadni,
> 
> Thanks for your response, but method you provided causes the same errors and requires me to install php, composer, all required php extensions and "make" program on my server rather than the docker container itself, which is really bad.
> 
> The whole stack should run correctly using single `docker-compose up` command and without the need to have php and composer installed on host machine. These things should already be installed within docker webserver container.

Could you tell me if it's better with #25940? (You have to wait a lot for assets when using docker :( )

**Closed as completed** 2021-09-21 09:34 UTC
Labels: Bug, develop, Major, CO, Fixed, Developer Feature, PR available, Prerelease

**Comment by bartoszbrozek** [comment] 2021-09-21 10:26
@PierreRambaud 
Yes, I can confirm - it works now. Thank you very much for your effort.
