### ISSUE TITLE
Facet search URL Scheme doesn't work

### ISSUE THREAD

**Issue by Tehnikus** [PrestaShop/PrestaShop#21340] opened 2020-10-07 13:27 UTC
## Describe the bug

1. The options provided in **Shop Parameters -> Traffic and SEO** for filtered pages of doesn't take any effect.

2. Availability for indexing of faced filter pages by search engines doesn't take any effect

3. Also custom URLs and Meta Titles of Attributes and features doesn't take any effect as well.
See attached images for reference

#### Expected behavior

1. URL expected to match pattern stated in 
**Shop Parameters -> Traffic and SEO**
i.e.:
site.com/{id}-{rewrite}{/:selected_filters}
AND without GET options in request, so it should be

site.com/3-clothes-categories-men/
**instead**
en/3-clothes?q=Categories-Men

2. Meta titles expected to match those that are set in Attributes and Features
or at least provide some method to control meta titles of facet search pages

3. Indexing option of faced filter pages should work and take effect

4. Options to include or exclude pages from available for indexing

#### Steps to Reproduce

1. Use any filter in front office
2. See URL
3. See meta titles of page

**Screenshots**

![0](https://user-images.githubusercontent.com/53004226/95335777-78493380-08b8-11eb-940d-805f45c8580d.PNG)
![1](https://user-images.githubusercontent.com/53004226/95335783-797a6080-08b8-11eb-9622-759c4ff1fd9e.PNG)
![2](https://user-images.githubusercontent.com/53004226/95335786-7a12f700-08b8-11eb-92d0-c4558e5d5159.PNG)
![3](https://user-images.githubusercontent.com/53004226/95335787-7a12f700-08b8-11eb-91c7-f683d5cf8385.PNG)
![4](https://user-images.githubusercontent.com/53004226/95335789-7aab8d80-08b8-11eb-8fe3-8371cdb6436a.PNG)

#### Additional information

* PrestaShop version: 1.7
* PHP version: any

**Comment by sarahdib** [comment] 2020-10-07 16:25
Hello,

We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #16939.

Thank you!

**Comment by sarahdib** [comment] 2020-10-07 16:25
duplicate of #16939

**Closed as completed by sarahdib** 2020-10-07 16:25 UTC
