### ISSUE TITLE
Errors with Dashboard and orders amounts

### ISSUE THREAD

**Issue by Mel-meel** [PrestaShop/PrestaShop#37073] opened 2024-10-02 14:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everybody,

I have troubles in a shop, when i try to see statistics about orders, and first problem, i see two orders for a total amount 0€.

<img width="695" alt="Capture d’écran 2024-10-02 163642" src="https://github.com/user-attachments/assets/25482f99-4891-4b8e-8dcd-5ca4cf9809ce">

As you can see, my orders are not 0€.

<img width="798" alt="Capture d’écran 2024-10-02 163851" src="https://github.com/user-attachments/assets/6f0970e8-d65e-4262-a636-b64ac4c04dd3">

Second problem, amounts on the main dashboard are not like in orders.

<img width="797" alt="Capture d’écran 2024-10-02 163946" src="https://github.com/user-attachments/assets/d527f700-50f0-41d5-b306-4960911896fb">

I suppose the native module **statsforecast** is in trouble.

Thank you so much for help.

### Steps to reproduce

1. Order
2. Go in backoffice and see dashboard, you will see like in second attachment.
3. Go in statistics panel and module statsforecast

### PrestaShop version(s) where the bug happened

1.8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

statsforecast

**Comment by florine2623** [comment] 2024-10-02 15:08
Hello @Mel-meel ,

For your first issue, the order needs to be considered as paid to be displayed in the statistics.

For your second issue, the price are displayed tax incl. on the order section, and displayed tax excl. on the Dashboard, order section.

Closing your issue, as this is not a bug.
Thanks!

**Closed as completed by florine2623** 2024-10-02 15:08 UTC
Labels: Bug
