### ISSUE TITLE
Hook with the name registerGDPRConsent has been registered but has not been defined in the Module class.

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#30131] opened 2022-10-27 06:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Registered this 'registerGDPRConsent' in the module as per the psgdpr module guidelines,
https://build.prestashop-project.org/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/

But in Prestashop 8 there is a warning for the registered hook which is not defined on module installation. see screenshot
![download (1)](https://user-images.githubusercontent.com/19220745/198205216-96418818-0ce2-4fe9-8778-5127fb25b8e6.png)

if we removed this hook how the module will work with psgdpr module as we can see module is checking the hook here in latest psgdpr version
https://github.com/PrestaShop/psgdpr/blob/v1.4.2/psgdpr.php#L715

Please suggest a solution.

### Expected behavior

There will be no warning for registerGDPRConsent hook 

### Steps to reproduce

1. in a new  module register hook, 'registerGDPRConsent' as per the doc https://build.prestashop-project.org/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/
2. install the module on Prestashop 8 stable version
3. Make sure to turn on debug mode
4. you can see the warning on the module installation popup.

### PrestaShop version(s) where the bug happened

8.0.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

psgdpr

**Comment by PrestaEdit** [comment] 2022-10-27 07:05
Hi,

Your issue is coming from the third party module **wkonepagecheckout**.

PrestaShop 8, with debug mode enabled, will throw the error to allow developpers to remove unused hooks registeration.

It's not a bug of Prestashop, you need to contact the author of this module in order to make it compliant.

**Comment by dheerajwebkul** [comment] 2022-10-27 07:45
@PrestaEdit it's not related to only wkonepagecheckout its just an example, it's in any module that registered this registerGDPRConsent hook.
It's not a Prestashop bug, it's a PrestaShop official psgdpr module bug now which is conflicting with Prestashop 8.

To make compatible any module with the PrestaShop psgdpr module we need to only register this hook
See official doc:
https://build.prestashop-project.org/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/
Hook 1: Register your module into the GDPR module

Somehow explained the same here also: https://github.com/PrestaShop/PrestaShop/pull/27683

**Comment by hibatallahAouadni** [comment] 2022-10-28 14:12
Hello @dheerajwebkul 

Could you please provide a module that registre registerGDPRConsent hook to help reproducing the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by HanaRebaiQA** [comment] 2022-11-17 08:11
Hello @dheerajwebkul 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank You!

**Closed as completed by HanaRebaiQA** 2022-11-17 08:11 UTC
Labels: Bug, BO, Modules, Module manager, Hook, Invalid, 8.0.0

**Comment by dheerajwebkul** [comment] 2022-11-21 09:56
here is the solution in PrestaShop productcomments module 
https://github.com/PrestaShop/productcomments/blob/v5.0.2/productcomments.php#L1076

**Comment by dheerajwebkul** [comment] 2022-11-21 09:57
@hibatallahAouadni 

https://github.com/PrestaShop/productcomments/blob/v5.0.2/productcomments.php#L1076
/**
     * empty listener for registerGDPRConsent hook
     */
    public function hookRegisterGDPRConsent()
    {
        /* registerGDPRConsent is a special kind of hook that doesn't need a listener, see :
           https://build.prestashop.com/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/
          However since Prestashop 1.7.8, modules must implement a listener for all the hooks they register: a check is made
          at module installation.
        */
    }
