### ISSUE TITLE
Prestashop 1.7.6.3 Template change problem

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18316] opened 2020-03-26 10:33 UTC
By changing from a non default template to default and back all layout is messed up

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-26 11:08
Hi @Betafer,

Your ticket is a duplicate of #16838
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-03-26 11:08
Duplicate of #16838

**Closed as completed by khouloudbelguith** 2020-03-26 11:08 UTC
Labels: Duplicate
