### ISSUE TITLE
Slow product saving

### ISSUE THREAD

**Issue by Lndaw** [PrestaShop/PrestaShop#11363] opened 2018-11-13 09:26 UTC
**Describe the bug**
Saving the product is very slow, takes about 20s.
When the merchant save a product, the saving process is too long.

**To Reproduce**
1. Go to 'Product page'
2. Save the product

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.23

**Comment by khouloudbelguith** [comment] 2018-11-13 09:28
Hi @Lndaw,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-06 10:57
Hi @Lndaw,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-02-06 10:57 UTC
Labels: BO, Catalog, No change required, 1.7.4.2

**Comment by AlanReibel** [comment] 2022-08-08 11:28
I have the same problem, any news about this?

**Comment by partiid** [comment] 2024-01-04 14:07
Any news?
