### ISSUE TITLE
Login to BO in 1.7.6.7 does not work 

### ISSUE THREAD

**Issue by normannasty** [PrestaShop/PrestaShop#20391] opened 2020-07-30 08:41 UTC
Hi All, 

After upgrade to 1767 I cant login to BO. 
I tried those things which was in the Login to BO in 1.7.6.7 does not work #20079 ticket but they didnt helped. 
Has someone idea why I cannot login to bo. 

BrN

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment] 2020-07-30 09:06
Hi @normannasty ,

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/20079.
A conversation is already happening over there.
I'll close this issue.

**Comment by florine2623** [comment] 2020-07-30 09:07
Duplicate of #20079

**Closed as completed by florine2623** 2020-07-30 09:07 UTC
Labels: Duplicate
