### ISSUE TITLE
Admin url does no work

### ISSUE THREAD

**Issue by drqp1983** [PrestaShop/PrestaShop#20091] opened 2020-07-07 19:37 UTC
#### Describe the bug
It shows a blank screen when I go to my admin panel, I click on the link and just takes me to a blank screen (see screenshot).

#### Expected behavior
When I click a my admin panel link I should take me to the log in screen. 

#### Steps to Reproduce

Admin Panel:
1. Go to 'admin panel'
2. It shows a blank screen.

**Screenshots**

![1](https://user-images.githubusercontent.com/66806621/86833493-d31f8480-c056-11ea-817f-97bf6cd5b9dc.jpg)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.7

**Comment by rdy4ever** [comment] 2020-07-08 10:24
Hi @drqp1983 
You need to enable debug mode ([how](https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/)) and visit your admin url again in order to get some real error information displayed.

**Comment by marionf** [comment] 2020-07-08 11:50
Hello, 

We can't manage 2 problems in an issue, please create a new issue about the reassurance issue.

About the blanck screen, could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you!

**Comment by matks** [comment] 2020-07-08 14:17
@drqp1983 We are investigating the shop of someone who seems observe an issue that might be related to yours.

The root cause of him unable to log-in is because SQL tables ps_customer_session and ps_employee_session are missing in his database. These SQL tables are new since 1.7.6.6 and needed for security purposes. They should have been added to your database when upgrading to PS 1.7.6.6.

Could you tell us whether you see these SQL tables in your database ?

**Comment by khouloudbelguith** [comment] 2020-07-29 09:45
Hi @drqp1983,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-07-29 09:45 UTC
Labels: Bug, BO, No change required, 1.7.6.7
