### ISSUE TITLE
introduce the management of keywords in the product pages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#14514] opened 2019-07-06 11:30 UTC
Hi
you can see that now it is not possible to add keywords in the product pages, but in the front-office that tag is present and it is void.
For those sites upgraded from the previous versions it is present the past keywords, so if a shopkeeper change the content of a product in the front-office will be present the same past keywords.
I know that for you that tag is no more very important, but however it is already used. So I think google can understand by itself what are the important keywords in the pages, but until they are considered it is necessary to let the shopkeeper decide whether to use them again or not, in this way you would give them the possibility to make corrections and optimizations if he considers it necessary.

looking at this article
https://www.relevance.com/seo-best-practices-meta-keywords-ssl/

and it says

META Keywords Common Sense: The Top-Ranking Websites Still Use Them

For almost a decade, Google and Yahoo/Bing reps at popular search marketing conferences have touted “don’t use META keywords” –keywords infused in the HTML META code initially intended to direct search engines–saying they have no ranking factors whatsoever.

The reps also warn that though META keywords certainly can’t help, they can actually harm rankings if used wrong—such as using too many keyword phrases, too lengthy a list of phrases, or obvious keyword “stuffing”.  Because these tactics were once heavily abused, the strong recommendation in the SEO community was to completely abandon their use.

This news went viral, and of course all the SEO community immediately framed this as best practice, though most content management systems still support the feature in their SEO tools to this day, and the W3C (international consortium that manages html standards) have not deprecated or suspended use of the tags in the official HTML markup language. So, why would we argue with an ultimate source like Google?  Answering that question led us to do something so simple, that many fail to do it – actually analyze the usage of the META keyword tag on top ranking sites.

In fact, we’ve checked over 150 websites annually, and the top-ranking sites on the web are mostly all still using the META keywords tag. So, what gives?

If it can’t hurt, and you’re abiding by white hat SEO rules such as not keyword stuffing and keeping lengths to a minimum, then can it hurt to use META keywords? What is your logical, third-grade opinion given this data?

At Interact Marketing, we continue to recommend the use of META keywords for all of our clients, most which rank for dozens of phrases on page one of search results within their respective industries. That doesn’t seem to hurt, now does it?

Many competitors have even taken notice, and some have even tried rogue spamming to snipe Interact Marketing clients, claiming we are using outdated SEO tactics because so-called “established authorities” say the tags are useless. Nothing can garner client confidence more than justifying our decisions by attributing our reasoning not to just what the SEO community thinks as a whole, but what some of the top-ranking–and most profitable–businesses out there are actually doing – especially Google-owned properties.

We’ll certainly be open to re-consideration when we are challenged to “do as they do”, rather than blindly just “do as they say”.

-----------

I hope you will introduce again the management of the keywords from the product pages
thanks
 
![1](https://user-images.githubusercontent.com/653230/60755596-429d0700-9ff2-11e9-91c1-478683a4cd5b.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by Digitalfastmind** [comment] 2019-07-06 11:59
Indeed needed, as keywords are still content and can play an important role from a global seo perspective

**Comment by khouloudbelguith** [comment] 2019-07-08 10:53
Hi @maofree,

Google doesn't use the keywords in meta-keywords and also websites using meta-keywords don't get penalized.

So we are planned to remove them but it's not the priority on SEO for the moment.
Your ticket is a duplicate of #11144
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-08 10:53
Duplicate of #11144

**Closed as completed by khouloudbelguith** 2019-07-08 10:53 UTC
Labels: Duplicate
