### ISSUE TITLE
allow ordering out-of-stock

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#13447] opened 2019-04-17 09:15 UTC
Prestashop 1.7.5.1 on debian php 7.2.17
Please see here https://nimb.ws/nSykKN
Only with "allow ordering our-of-stock" YES (arrow 1) on product there are labels (arrows 2-3)
Instead, whe allow ordering is NO, there are no labels (arrows 2-3)
Thank you

**Comment by khouloudbelguith** [comment] 2019-04-17 10:42
@marionf, @colinegin, what do you think?

**Comment by marionf** [comment] 2019-04-17 12:01
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/12630

**Comment by marionf** [comment] 2019-04-17 12:04
Hello @centoasa 

Your issue is a duplicate, please follow the issue referenced.
This has been fixed for 1.7.6.0

**Closed as completed by marionf** 2019-04-17 12:04 UTC
Labels: Bug, BO, Duplicate, Shop parameters, Product settings, 1.7.5.1

**Comment by centoasa** [comment] 2019-04-17 13:10
Apply the fix, now works fine!
