### ISSUE TITLE
Faceted search price filter slider does not appear after upgrade from 1.7.5.2 to 1.7.6.1

### ISSUE THREAD

**Issue by dreamtheme** [PrestaShop/PrestaShop#15461] opened 2019-09-07 12:33 UTC
**Describe the bug**
Faceted search price slider range does not appear after upgrade from 1.7.5.2 to 1.7.6.1

**To Reproduce**
1. Upgrade from 1.7.5.2 to 1.7.6.1
2. Upgrade the faced search module to version 3.2.1 (the whole module does not appear at this step)
3. Edit the template (un-thick and re-thick random category - save) the module appears but no price filter.
4. Reset the module - price filter still does not appear (made sure the price filter is enabled in the template).
5. Uninstall and reinstall the module - price filter still does not appear.
6. Tried to clear/disable cache, rebuild indexes, used Prestashop cleaner module, no success with anything.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2
Server: Litespeed

**Comment by khouloudbelguith** [comment] 2019-09-09 10:38
Hi @dreamtheme,

I did not manage to reproduce the issue with PS1.7.6.1 after upgrade from PS1.7.5.2 using the 1-click upgrade v4.9.0 & the ps_facetedsearch v3.2.1 after an upgrade from v3.0.6.
I attached a screen record
https://drive.google.com/file/d/1pgoGdpjbcxSUFzKu3q2DA2r_gSMchRX7/view
Thanks to check & feedback.

**Comment by dreamtheme** [comment] 2019-09-09 11:54
@khouloudbelguith You guys hot fixed the module today without changing the module numbers?
Just compared the same module 3.2.1 from yesterday to today. 
![image](https://user-images.githubusercontent.com/17176009/64528239-a2749e80-d310-11e9-850f-9a65f46f2cc0.png)

**Comment by PierreRambaud** [comment] 2019-09-09 12:47
We didn't touch anything on the module.
It only depends if you download it from the addons marketplace / fresh install, or if you get it from ps_facetedsearch repository.

**Comment by khouloudbelguith** [comment] 2019-09-09 12:51
@dreamtheme, last version of the ps_facetedsearch is v3.2.1, it is released 10 days ago.
https://github.com/PrestaShop/ps_facetedsearch/releases

**Comment by dreamtheme** [comment] 2019-09-09 12:59
@khouloudbelguith Yes i have checked that, and you mean 3.2.1 :) So where is the difference coming from then? not proper module upgrade?, because i can 100% reproduce it on some installations, but not on all.

**Comment by khouloudbelguith** [comment] 2019-09-09 13:07
@dreamtheme, yes it is 3.2.1.
those modules are downloaded from the same place?
Do those folders have the same permissions?
Did you installed this module from the BO => Catalog Modules or cloned/downloaded from GitHub?

Thanks!

**Comment by dreamtheme** [comment] 2019-09-09 13:13
@khouloudbelguith The modules are all downloaded only via the "upgrade" button in the update section of PS admin, no github, and i have compared the folders of the modules between several installations. Its the same server with the same permissions yes. 
If i install PS 1.7.5.2 now, i can't reproduce the bug, but if i restore backed up older 1.7.5.2 installation, happens always, same server, same settings. Will try to narrow it down.

**Comment by khouloudbelguith** [comment] 2019-09-09 13:23
@dreamtheme, thanks!
Waiting for your feedback.

**Comment by dreamtheme** [comment] 2019-09-09 17:23
@khouloudbelguith 
Ok after a whole day of debugging, i have found the issue. In fact there are several issues.

Bug 1. The issue is when you have "Bulgarian" localization pack installed, and the products are using -> "BG Standard Rate (20%)" Tax rule in the product settings, the price filter disappear in 1.7.5.2 and in 1.7.6.1 with Faceted 3.2.1 (regardless of the display language and the currency of the store).
Changing the tax rule to US-AL 4% brings back the price filter.

Bug 2. Creating a new brand and assign it to products, i was unable to make it display as option in the faceted search front office, no matter what i do, and yes its properly configured.

**Comment by khouloudbelguith** [comment] 2019-09-10 09:16
@dreamtheme, I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0 & PS1.7.5.2 & ps_fecetedsearch v3.2.1.
I edit the template of the ps_factedsearch module & I Clicked on all the button to re-index the prices & attributes & I cleared the cache.
PS: the URL accentuated is enabled / disabled => OK
I attached a screen record
https://drive.google.com/file/d/1ID-Y799CP4T-FERpRGxS9tIcefqrMsFP/view
Thanks to check & feedback.

**Comment by dreamtheme** [comment] 2019-09-10 09:40
@khouloudbelguith 
Did you changed the tax rule on all products? because you need to change the tax rule to all products, and i suggest you to disable all products and leave only two and test with them. 
If you have changed the tax rule only on two products, only they won't appear in the search filter, but as the other products are on the other tax rule they will remain active and filter will be visible.
Also make sure to set force compile and no cache in performance settings.

**Comment by khouloudbelguith** [comment] 2019-09-10 09:55
@dreamtheme,
>because you need to change the tax rule to all products

What is the exact tax rule I need to use?

Thanks!

**Comment by dreamtheme** [comment] 2019-09-10 10:04
@khouloudbelguith I have already explained that, you need to use "BG Standard Rate (20%)" on all products.
I made a video here https://drive.google.com/file/d/1Cl7Z2KpaewXtxrvpIXH4ObkSw5Koffst/view

**Comment by dreamtheme** [comment] 2019-09-10 10:22
And here i have made another video on 1.7.6.1 and apparently the bug is alive in facet 3.0.6 and in 3.2.1, and as you can see brands don't appear at all for me. 
https://drive.google.com/file/d/1IMGC7G0ssYB7H6qz03r-TRqvf5g8ah0I/view

**Comment by khouloudbelguith** [comment] 2019-09-10 10:27
@dreamtheme, I tried with ps_facetedsearch v3.2.1 & it is OK.
https://drive.google.com/file/d/1_xg6CZ-VASzt2giTA6U3KHQEV68m3UkA/view
The cache is similar to yours.
Thanks!

**Comment by dreamtheme** [comment] 2019-09-10 10:34
@khouloudbelguith Well maybe its due to PHP version difference, i don't know, i can provide you with access to new installation for you to test, but so far this happens for me 100% on two different servers with different PHP versions, i don't know your test environment.

**Comment by dreamtheme** [comment] 2019-09-10 10:37
Here it is live, just set up this installation, https://demo.dreamtheme.eu/presta17test/, tell me where to send you access to it.

**Comment by khouloudbelguith** [comment] 2019-09-10 10:41
@dreamtheme,
This is a public space.
You can provide me the access by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by dreamtheme** [comment] 2019-09-10 10:45
@khouloudbelguith Ok e-mail send :)

**Comment by khouloudbelguith** [comment] 2019-09-10 10:47
@dreamtheme, thanks!
I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment] 2019-09-10 11:10
@dreamtheme,
I checked that your your default country is the United States.
In your Bo => International => Taxes => Tax Rules Tab => I edit the "BG Standard Rate (20%)" & I added a new tax rule with the country United States & now it is OK
![image](https://user-images.githubusercontent.com/16067358/64609042-e96f9c00-d3c3-11e9-8a7d-3a351e09e181.png)


Thanks to check & feedback.

**Comment by dreamtheme** [comment] 2019-09-10 11:14
@khouloudbelguith 
Thanks, but what about the brands?
And in older version worked without the need to change the tax rule country settings, and how is the users supposed to know that? :)

**Comment by dreamtheme** [comment] 2019-09-10 11:53
@khouloudbelguith 
Waiting your info on the brands too :)

**Comment by khouloudbelguith** [comment] 2019-09-10 12:28
@dreamtheme, about the brand, is not displayed, because you only one brand active => it is related to this issue: #11207
If you change

`$usefulFiltersCount > 1` to `$usefulFiltersCount >= 1` in the file `ps_facetedsearch/src/Product/SearchProvider.php` file, you can see the brands.

![image](https://user-images.githubusercontent.com/16067358/64613736-cd252c80-d3ce-11e9-9553-3769bb1d6218.png)

I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-10 12:28 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.6.1

**Comment by PierreRambaud** [comment] 2019-09-10 12:34
FYI: the latest issue will be fixed in the next Faceted search release.

**Comment by maperezr14** [comment] 2021-01-26 23:56
Hello, I have my store with prestashop version 1.7.5.2, the slider is shown but it does not work that is, when I move the controls for a price range the page updates but it still shows me the same order and quantity of products and furthermore the slider is reset.
