### ISSUE TITLE
[PHP Notice #8] Undefined index: value (classes/webservice/WebserviceOutputXML.php, line 128) 

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#12056] opened 2019-01-08 09:13 UTC
**Describe the bug**
On Prestashop webservice from 1.6.1.x to 1.7.5.x, when I'm requesting URL "/api/customers/2", I have the following warning:

>  [PHP Notice #8] Undefined index: value (classes/webservice/WebserviceOutputXML.php, line 128) 

Customer n°01 (default "John DOE" customer) is queryable successfully, but not others.

I'm not on a fresh install of Prestashop and I overrided some tables and classes, so I think you can't reproduce this error but, anyway, it's important to test if a variable exists before use it. 

**To Reproduce**
1. Request "shop-url.com/api/customers/2"
2. See error "[PHP Notice #8] Undefined index: value (classes/webservice/WebserviceOutputXML.php, line 128)"

**Screenshots**
Screenshot of error + relative source code 
![errror_webserviceoutputxml](https://user-images.githubusercontent.com/7419525/50820387-c7051a80-132c-11e9-8482-9565e40d1375.png)

**To Resolve**
Replace line 128:
`            if ($field['value'] != '') {`
By:
`            if (isset($field['value']) && $field['value'] != '') {`

**Additionnal information**
PrestaShop version: 1.6.1.23 (but same until 1.7.5.x)
PHP version: 5.6

**Comment by Klemart3D** [comment] 2019-01-08 09:17
PR: https://github.com/PrestaShop/PrestaShop/pull/12057

**Comment by khouloudbelguith** [comment] 2019-01-08 09:25
Hi @Klemart3D,

Thanks for your report & your fix.
But I did not manage to reproduce the issue with PS1.7.5.0 /PS1.6.1.23.
I attached a video record.
https://drive.google.com/file/d/1vGGKc2JQQHKhOVbDT8YP9Eq2vvhspQSU/view
What is the exact version PHP did you use?
Thanks!

**Comment by Klemart3D** [comment] 2019-01-08 10:50
Not the same for me. Customer 01 ("John Doe") is queryable by API but not others, see attach:

![api-error](https://user-images.githubusercontent.com/7419525/50826127-1e11ec00-133b-11e9-8f83-b564a7d07b3d.gif)

My PHP version is 5.6.38, all my PS config is OK:

![config-ps](https://user-images.githubusercontent.com/7419525/50826269-6fba7680-133b-11e9-878f-b3e3661878e8.png)

**Comment by khouloudbelguith** [comment] 2019-01-08 11:00
Hi @Klemart3D,

What are the exact details for this customer
- Social title
- First name
- Last name
- Email
- Birthdate
- Any other information?
Thanks!

**Comment by Klemart3D** [comment] 2019-01-08 11:09
Well, I found why. It's because in my database, unset values are set to 'NULL' for all my customers except for first default user "John DOE" unset values are empty. See attach:

![database-customer](https://user-images.githubusercontent.com/7419525/50827137-f40df900-133d-11e9-85ac-4d7ce7b0b5df.png)

It's better resource consumption to set a NULL value in place of empty value. I don't know why they are "NULL" in my case (may be a bad table declaration), but PrestaShop webservice have to consider this type and not to display a notice. Do not you think so?

**Comment by khouloudbelguith** [comment] 2019-01-08 11:25
@Klemart3D, did you enabled B2B option?
In my case, I just have an empty value for "company", "siret", "ape".
![image](https://user-images.githubusercontent.com/16067358/50828045-84e5d400-1340-11e9-864e-954ef425213c.png)
Thanks!

**Comment by Klemart3D** [comment] 2019-01-08 13:42
@khouloudbelguith Yes:
![b2b-mode](https://user-images.githubusercontent.com/7419525/50833739-87512980-1352-11e9-9b45-cc77dbba42d0.png)

**Comment by khouloudbelguith** [comment] 2019-01-08 13:45
@Klemart3D, I tried to enable the B2B option & I created a customer => but I did not have `null` in my database.
Yes, it could be a problem, with a fresh installation 1.7 / 1..6, I did not manage to reproduce the issue.
Thanks to remove this override, check & feedback.

**Comment by Klemart3D** [comment] 2019-01-08 14:03
I disabled all non Prestashop modules and all overrides but still the same. Each new Customer have 'NULL' values by default. I tried update some fields from customer account (like add a company name) then delete it and 'NULL' value is coming back.

I disabled B2B mode and redo same edits but still the same too. Cache cleaned. Debug mode enable/disabled. No core file modified.

**Comment by khouloudbelguith** [comment] 2019-01-08 14:08
@Klemart3D, after those modifications, if you create a new customer, the new fields will be `Null` also?
Thanks!

**Comment by Klemart3D** [comment] 2019-01-08 14:17
@khouloudbelguith Yes by default, for each new customer, all empty fields are set to 'NULL', also 'note', 'birthday' or 'ip_registration_newsletter'.

**Comment by khouloudbelguith** [comment] 2019-01-08 15:20
@Klemart3D, so the issue is not a PrestaShop's core bug but most likely a customization problem.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Klemart3D** [comment] 2019-01-08 16:48
That's not come from any module because I all disabled them, I disabled all overrides too but I continue to reproduce the issue.

**Comment by khouloudbelguith** [comment] 2019-01-08 16:51
@Klemart3D, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Klemart3D** [comment] 2019-01-18 14:07
This error occurs only when debug mode is set to "false", with debug mode enabled webservice is working and NULL fields are displayed like this:

```
<website/>
<telephone/>
<company/>
<siret/>
<ape/>
```

When debug mode is disabled and I request a customer info through API, PHP logs are:

```
[Fri Jan 18 14:24:52.062297 2019] [:error] [pid 4622] [client 192.16.1.90:60800] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.596486 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.596605 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.596671 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.596731 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.596791 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.596955 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.597021 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.597097 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
[Fri Jan 18 14:24:55.597156 2019] [:error] [pid 4621] [client 192.16.1.90:60804] [PHP Notice #8] Undefined index: value (/var/www/html/classes/webservice/WebserviceOutputXML.php, line 128)
```
My Pull Request is not really a Prestashop bug fix but a better practise to develop by testing every variable before using it in case of bad insertion into database (from external module by sample). And it's not always fixed in last Prestashop version so I created a new PR for PS1.7.5 : https://github.com/PrestaShop/PrestaShop/pull/12213

**Comment by khouloudbelguith** [comment] 2019-01-18 14:19
@Klemart3D, thanks for your feedback.
I created a new customer when debug mode is disabled, I checked my database there's no Null expression, also there is no error with `api/customers/`
https://drive.google.com/file/d/1Yfn84wFNfuklZQzWjcQFin0mmYIgyoK6/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-18 08:17
Hi @Klemart3D,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-18 08:17 UTC
Labels: Customer, Webservice, No change required, 1.7.5.0

**Comment by matks** [comment] 2020-04-21 09:55
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18006
