### ISSUE TITLE
 Message "There are not enough products in stock" Prestashop 1.7.5.0

### ISSUE THREAD

**Issue by viktor-abc** [PrestaShop/PrestaShop#12630] opened 2019-02-19 16:35 UTC
Hello, I think that in file ... \ src \ Adapter \ Presenter \ Product \ ProductLazyArray.php in line 766: 

elseif ($ product ['quantity_wanted']> 0 && $ product ['quantity']> = 0) 

was one Bug done. This condition always becomes true if $ product ['quantity'] = 0 because the desired amount always starts with 1. Due to this error, the message "There are not enough products in stock" always appears, regardless of whether the required quantity is not available or the item is not in stock.

I think this line must look like this:
elseif ($ product ['quantity_wanted']> 1 && $ product ['quantity']> = 0)

**Comment by khouloudbelguith** [comment] 2019-02-19 16:39
Hi @viktor-abc,

Could you please provide me steps to reproduce the issue in a new comment.
Thanks!

**Comment by viktor-abc** [comment] 2019-02-20 12:57
Hello, I have added 2 pictures that I think are self-explanatory.
![out_of_stock_1](https://user-images.githubusercontent.com/47788586/53093228-2a32c100-3517-11e9-895a-ddf1435e42c5.jpg)
![out_of_stock_2](https://user-images.githubusercontent.com/47788586/53093229-2acb5780-3517-11e9-93e9-f3b483481934.jpg)

**Comment by khouloudbelguith** [comment] 2019-02-20 14:28
Hi @viktor-abc,

Thanks for these clarifications.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.5.1 & PS1.7.4.4.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by mrabsinthe** [comment] 2019-02-20 15:37
I can confirm the bug on my installation of PS1.7.5.1 and the fix works fine! Well done @viktor-abc !

**Comment by MathiasReker** [comment] 2019-02-21 10:46
Fixed in this PR: https://github.com/PrestaShop/PrestaShop/pull/12655

**Comment by ntiepresta** [comment] 2019-02-21 14:57
Hi,
@khouloudbelguith , this issue doesn't exist on develop branch. Can close it be?
Thanks

**Comment by khouloudbelguith** [comment] 2019-02-21 15:25
Hi @ntiepresta,

Yes, I did not manage to reproduce the issue with develop branch.
https://drive.google.com/file/d/1ldXUoTox8Ixko7foCQs_sIJ3SCN3wWX0/view
Since it is fixed in the next release PS1.7.6.0, I will close the issue.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-21 15:25 UTC
Labels: Bug, Minor, FO, Product settings, Fixed, 1.7.5.0, 1.7.5.1
