### ISSUE TITLE
"No carriers available" : case detected

### ISSUE THREAD

**Issue by alx-web** [PrestaShop/PrestaShop#25300] opened 2021-07-09 12:18 UTC
#### Describe the bug
When we arrive in checkout page to list carriers, we have the message "Unfortunately, there are no carriers available for your delivery address." When we come back to choose address and change adresse, the result is the same. The problem is only for some customers.

A clear and concise description of what went wrong.

#### Expected behavior
Display the carriers

Explain what you expected to happen instead.

#### Steps to Reproduce

I understand why we have the problem and i think i have a solution for that:
- On ps_cart id_address_delivery was id 1
- But, on ps_cart_product, for each product the id_address_delivery was 2. And id_adresse 2 is for a deleted adress
- When we choose the address updateAddressId is called, but parameters are : updateAddressId(1, 1) this is why the id address is not updated on ps_cart_product

I think we should force edit updateAddressId function to update id_address_delivery if each id_address_delivery of the cart are the same and different from id_address_delivery on ps_cart.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2021-07-09 15:37
Hi @alx-web,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15399 to fix the issue.
It is fixed in PS1770.
Your ticket is a duplicate of #9932
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-07-09 15:38
Duplicate of #9932

**Closed as completed by khouloudbelguith** 2021-07-09 15:37 UTC
Labels: Duplicate
