### ISSUE TITLE
Issue when creating orders from the back office, the client list is not displayed

### ISSUE THREAD

**Issue by MiguelOlmos392** [PrestaShop/PrestaShop#12801] opened 2019-03-05 19:24 UTC
**Describe the bug**

After creating a new client from the back office, I tried to create a new order for that costumer, but when I open the window to create orders, the client search bar does not show any results, making it impossible to create a new order. The error occurred with PS 1.7.5.0, updated to 1.7.5.1 and the error continues.

**To Reproduce**
1. Go to Back Office
2. Click on Orders --> Orders -->Create New Order
3. Enter characters to show clients

**Screenshots**
![screenshot 2019-03-05 20 21 22](https://user-images.githubusercontent.com/48259009/53831237-a4862b00-3f84-11e9-9a9f-82b07d1cf099.png)

**Additionnal information**
PrestaShop version: 1.7.5.0- 1.7.5.1
PHP version: 7.3.0

**Comment by khouloudbelguith** [comment] 2019-03-06 07:28
Hi @MiguelOlmos392,

Thanks for your report.
First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP and feedback. 
Thanks!

**Comment by MiguelOlmos392** [comment] 2019-03-06 07:54
Hello, thanks for your answer, I have downloaded the PHP version to 7.2 as you suggested and the problem persists, also try PHP 7.1 but it still does not work.

**Comment by khouloudbelguith** [comment] 2019-03-06 08:00
@MiguelOlmos392, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1azlsi9HvbKnpeVVNMKQSJQ_5Bq-PBmOe/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by MiguelOlmos392** [comment] 2019-03-06 08:39
Hi, I send you all the information I have, I apologize but my knowledge in Prestashop is limited.
![cpanel - php selector _ extensions](https://user-images.githubusercontent.com/48259009/53867243-b94dd780-3ff3-11e9-819b-75064905be04.png)
![cpanel - server information](https://user-images.githubusercontent.com/48259009/53867255-beab2200-3ff3-11e9-9dc9-c8e424f58e7d.png)
[20190305_upgrade.log](https://github.com/PrestaShop/PrestaShop/files/2935158/20190305_upgrade.log)
[dev.log](https://github.com/PrestaShop/PrestaShop/files/2935159/dev.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/2935160/prod.log)
![informations cafe lihue](https://user-images.githubusercontent.com/48259009/53866714-7dfed900-3ff2-11e9-8ac2-f9f5c27b93c3.png)

**Comment by khouloudbelguith** [comment] 2019-03-06 09:30
@MiguelOlmos392,

First, you need to clear cache manually by deleting all the folder into var/cache (prod & dev).
When you enable the debug mode, are there any exceptions displayed in the Orders page when you create a new order.
Thanks!

**Comment by MiguelOlmos392** [comment] 2019-03-06 09:50
Hello, thank you very much for your patience, I deleted the files inside the var/cache folder, when I activate the debug mode it does not show any exception, I still can not create orders. I can rule out problems with my browser because I have tried with three computers with different operating systems and also from my Android, it does not work anywhere. Before that Orders failed, I did not make any major changes or install any module.

**Comment by khouloudbelguith** [comment] 2019-03-06 10:59
Hi @MiguelOlmos392,

Could you please provide me your credentials to test your shop.
This is a public space.
You can provide me the access by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by MiguelOlmos392** [comment] 2019-03-07 13:50
Hello, sorry for the delay, I just sent you the credentials by email, thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 13:54
@MiguelOlmos392, sorry, I didn't receive your email yet.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 14:32
@MiguelOlmos392, I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 15:07
Hi @MiguelOlmos392,

You have an error 404 on your console
![image](https://user-images.githubusercontent.com/16067358/53966169-ea610180-40f2-11e9-80f9-cdf3b2a62791.png)
Could you please check in your Project file that you have not an override of this controller `AdminCustomers`.
Thanks to check & feedback.

**Comment by MiguelOlmos392** [comment] 2019-03-07 15:45
Hello @khouloudbelguith , there is no override of that controller, but I did not find it in the controllers/admin folder, there were several files missing, I uploaded the missing ones from a Prestashop installer, now it does not show error 404 but the problem is not solved

**Comment by khouloudbelguith** [comment] 2019-03-07 15:51
@MiguelOlmos392, I think that there is still something missed.
Because the customer is found but not shown
![image](https://user-images.githubusercontent.com/16067358/53969512-38790380-40f9-11e9-8076-ee464682b45d.png)
Thanks!

**Comment by MiguelOlmos392** [comment] 2019-03-07 16:07
I'm trying to find out the problem, this problem is burning my brain...

**Comment by khouloudbelguith** [comment] 2019-03-07 16:09
@MiguelOlmos392, you can find some logs in your Project_Folder/var/logs
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-05 07:37
Hi @MiguelOlmos392,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-05 07:37 UTC
Labels: BO, Order, No change required
