### ISSUE TITLE
Custom shipping modules wrong price vat calculation in classes/Cart.php

### ISSUE THREAD

**Issue by nedvedvojtech** [PrestaShop/PrestaShop#32791] opened 2023-06-01 13:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When develiping custom shipping module also calculating the price of each package, Cart.php recognizes use of calculation via the module, although dosnt apply tax. In Cart->getPackageShippingCost it returns the price right away without considering the bool $use_tax param (which is used later in the function after the return). 

_This is the point from which other problems cascade - saved order in the DB has both total_shipping_tax_incl and total_shipping_tax_excl filled with the same price without tax, etc...

CURRENT CODE: 
public function getPackageShippingCost($id_carrier = null, $use_tax = true, Country $default_country = null, $product_list = null, $id_zone = null)

```
if ($orderTotalwithDiscounts >= (float) ($free_fees_price) && (float) ($free_fees_price) > 0) {
    $shipping_cost = $this->getPackageShippingCostFromModule($carrier, $shipping_cost, $products);
    Cache::store($cache_id, $shipping_cost);

    return $shipping_cost;
}

if (isset($configuration['PS_SHIPPING_FREE_WEIGHT'])
    && $this->getTotalWeight() >= (float) $configuration['PS_SHIPPING_FREE_WEIGHT']
    && (float) $configuration['PS_SHIPPING_FREE_WEIGHT'] > 0) {
    $shipping_cost = $this->getPackageShippingCostFromModule($carrier, $shipping_cost, $products);
    Cache::store($cache_id, $shipping_cost);

    return $shipping_cost;
}
```

FIXED by replacing with:

```
if ($orderTotalwithDiscounts >= (float) ($free_fees_price) && (float) ($free_fees_price) > 0) {
    $shipping_cost = $this->getPackageShippingCostFromModule($carrier, $shipping_cost, $products);
    if ($shipping_cost > 0 && $use_tax && isset($carrier_tax)) {
       $shipping_cost *= 1 + ($carrier_tax / 100);
    }
    Cache::store($cache_id, $shipping_cost);

    return $shipping_cost;
}

if (isset($configuration['PS_SHIPPING_FREE_WEIGHT'])
    && $this->getTotalWeight() >= (float) $configuration['PS_SHIPPING_FREE_WEIGHT']
    && (float) $configuration['PS_SHIPPING_FREE_WEIGHT'] > 0) {
    $shipping_cost = $this->getPackageShippingCostFromModule($carrier, $shipping_cost, $products);
    if ($shipping_cost > 0 && $use_tax && isset($carrier_tax)) {
       $shipping_cost *= 1 + ($carrier_tax / 100);
    }
    Cache::store($cache_id, $shipping_cost);

    return $shipping_cost;
}
```

### Steps to reproduce

1. make custom shipping module with external shipping calculation
2. make an order
3. check the new ps_orders table entry columns total_shipping_tax_incl and total_shipping_tax_excl

### PrestaShop version(s) where the bug happened

1.7.6 and furher

**Comment by AureRita** [comment] 2023-06-02 15:21
Hi @nedvedvojtech 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-maintainers, can someone please reproduce this issue ? 

Thanks

**Comment by hibatallahAouadni** [comment] 2023-09-01 15:50
Hello @nedvedvojtech 

Do you still encounter the issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-29 14:30
Hello @nedvedvojtech 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-29 14:30 UTC
Labels: Bug, CO, Shipping, Invalid, Module, 8.1.x
