### ISSUE TITLE
Product reference cannot be changed

### ISSUE THREAD

**Issue by cruftex** [PrestaShop/PrestaShop#31240] opened 2023-02-07 03:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Setting up a new shop with Prestashop 8. Our initial installation was 8.0.0 and we recently updated to 8.0.1.

It is not possible to change the reference of a product.

If we duplicate the product, then there are two products with the same reference, which cannot be changed.

### Expected behavior

The reference can be changed, or, if the reference is write once only, then the UI is not allowing a change.

When a product is copied, the reference can be changed.

There can be no products with identical non empty reference.

### Steps to reproduce

1. New Product
2. Add product name
3. Save
4. Click edit on same product
5. Enter reference
6. Result: Reference is still empty when displaying the catalog list

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-02-07 10:37
Hello @cruftex ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Tested with Product Page V1 and V2 with standard product and combination product.
<img width="1232" alt="Screenshot 2023-02-07 at 11 33 37" src="https://user-images.githubusercontent.com/16019289/217221543-302e895f-5833-4772-8313-43523aa4c444.png">
<img width="1239" alt="Screenshot 2023-02-07 at 11 31 53" src="https://user-images.githubusercontent.com/16019289/217221617-dc187404-b31b-49cf-af08-63a6c67d1d44.png">

https://user-images.githubusercontent.com/16019289/217221691-5c9a6fb5-7643-4061-97a6-4cd2c2476bd3.mov

<img width="553" alt="Screenshot 2023-02-07 at 11 36 39" src="https://user-images.githubusercontent.com/16019289/217221764-5297fc1b-87a8-4ba7-8860-e4dd41309320.png">



We will close this issue.

Thank you

**Closed as completed by florine2623** 2023-02-07 10:37 UTC
Labels: Bug, Invalid

**Comment by cruftex** [comment] 2023-02-08 06:58
@florine2623 Thanks for looking into the issue so quickly!

I double checked. The cause of the problem seems to be the multi store feature which is enabled at our site. I am able to reproduce the problem on a fresh PrestaShop docker instance.

Steps to reproduce:
- new docker setup with 8.0.1
- enable multi store
- add a second shop "shop2" with virtual URL "shop2" and import all data

Next, see screen recording:

https://user-images.githubusercontent.com/2668191/217457030-84396484-8f17-48ce-84b2-10809d1dff76.mp4

@florine2623 can you please reopen?
