### ISSUE TITLE
unit_price not setted with prestashop api or webservice

### ISSUE THREAD

**Issue by FrancescCommerce21** [PrestaShop/PrestaShop#20071] opened 2020-07-06 11:14 UTC
#### Describe the bug

When i try to add or modify an unit_price of a product whit prestashop api or prestashop webservice (setting unit_price_ratio), the unit price is not changed and its setted to 0.

#### Expected behavior

Change unit_price of a product.

#### Steps to Reproduce

Make a simply api call to create a product.

![image](https://user-images.githubusercontent.com/59697514/86587615-3c859180-bf8a-11ea-9913-466f4453ea94.png)

![image](https://user-images.githubusercontent.com/59697514/86587729-79518880-bf8a-11ea-93f5-7db3ad6b770a.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-07-06 12:58
Hi @FrancescCommerce21,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9922
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-06 12:58
Duplicate of #9922

**Closed as completed by khouloudbelguith** 2020-07-06 12:58 UTC
Labels: Duplicate
