### ISSUE TITLE
token expiration too fast

### ISSUE THREAD

**Issue by WWBBob** [PrestaShop/PrestaShop#34995] opened 2024-01-08 07:17 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After the admin background login is successful, and has entered the AdminDashboard page, re-refreshing will exit directly to the login page, request prompt 403
![image](https://github.com/PrestaShop/PrestaShop/assets/7887973/0f7fda09-8f3f-443e-92c4-7496e13732dd)
![image](https://github.com/PrestaShop/PrestaShop/assets/7887973/8fe36867-4c4a-4e1b-868e-f9c630ad6131)
![image](https://github.com/PrestaShop/PrestaShop/assets/7887973/d7ad5957-0ae4-4896-ac37-be5984effbcf)

### Expected behavior

After logging in to the administrator, I should not refresh again and exit. I hope I can use the system normally

### Steps to reproduce

1. Install nginx 1.24
2, Install php 7.4 (php8.0)
3. Install mysql 8
4. Install prestashop 8.1.3
5. Log in to prestashop admin and go to AdminDashboard
6. Exit to the login page after refreshing

### PrestaShop version(s) where the bug happened

8.1.3

**Comment by florine2623** [comment] 2024-01-08 09:33
Hello @WWBBob ,

I can't reproduce your issue, so I'm closing it.

For security reasons, please change your admin folder name. This is a public space.

**Closed as completed by florine2623** 2024-01-08 09:33 UTC
Labels: Bug
