### ISSUE TITLE
Error 500 in BO with ps_shoppingcart

### ISSUE THREAD

**Issue by LaureMatou** [PrestaShop/PrestaShop#15595] opened 2019-09-18 09:44 UTC
No access to Back-office with an error 500

The error is

> [2019-09-17 16:14:52] request.CRITICAL: Uncaught PHP Exception Exception: "CartPresenter can only present instance of Cart" at /presthost/core/src/Adapter/Presenter/Cart/CartPresenter.php line 309 {"exception":"[object] (Exception(code: 0): CartPresenter can only present instance of Cart at /presthost/core/src/Adapter/Presenter/Cart/CartPresenter.php:309)"} []

When uninstalling ps_shoppingcart and reinstalling it, BO becomes accessible again

**To Reproduce**
No real reproduction scheme 
But the issue seems to have happened before:

- https://www.prestashop.com/forums/topic/597034-exception-in-cartpresenterphp-line-273/
- https://www.prestashop.com/forums/topic/618791-cannot-access-my-dashboard/

**Additional information**
PrestaShop version: Ready on 1.7.5.2

**Comment by khouloudbelguith** [comment] 2019-09-18 10:04
Hi @LaureMatou,

Did you manage in your case to reproduce the issue with Ready shop?

Thanks!

**Comment by LaureMatou** [comment] 2019-09-18 10:07
Yes @khouloudbelguith , it was reproduced with a Ready shop in 1.7.5.2. 
We fixed the bug by uninstalling ps_shoppingcart and reinstalling it (no more error 500)

**Comment by khouloudbelguith** [comment] 2019-09-18 10:13
@LaureMatou, can you provide the steps that you did before this issue occurs.
Any cart rule created?
Any specific product added to the cart?

I need to reproduce the issue with PrestaShop Core.
@LaureMatou what is the exact version did you use of the ps_shoppingcart module before uninstalling it?

Thanks!

**Comment by tscharrm** [comment] 2019-09-19 07:28
@khouloudbelguith client said she tried to change the position of the shopping cart

**Comment by khouloudbelguith** [comment] 2019-09-19 08:24
@tscharrm, I tried to change the position of the module ps_shoppingcart module in the `displayNav2` & `Header`, but it is OK. with PS1.7.5.2.
What is the exact version did you use of the ps_shoppingcart module before uninstalling it?

Thanks!

**Comment by LaureMatou** [comment] 2019-09-19 09:10
@khouloudbelguith  I think it was v. 2.0.2

**Comment by khouloudbelguith** [comment] 2019-09-19 10:21
@LaureMatou, Thanks!
Same version, but it is OK after changing positions.
https://drive.google.com/file/d/1MA9P3wuO4R3YaY-dcwOLbkFHWUULzq6K/view
@tscharrm, any other information, could help me to reproduce the issue?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-21 08:21
Hi @LaureMatou,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
In my case, I did not manage to reproduce the issue with PrestaShop download v1.7.5.2.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-21 08:21 UTC
Labels: Bug, BO, No change required, ps_shoppingcart, 1.7.5.2

**Comment by Ludogo** [comment] 2020-04-15 12:05
Hello,
to reproduce this :  i want to add a hook to the cart module to be displayed. But i made a mistake while i add cart to this hook  "displayAdminAfterHeader"; then i was not possible to access backoffice anymore
