### ISSUE TITLE
Uninstall override files not working properly with multiline properties

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#22629] opened 2020-12-31 07:45 UTC
When uninstalling a module, the uninstall function will fails to properly uninstall an overridden class containing properties defined on multiple lines (for example when an array is assigned to the property).

Only the first line is removed.

For example:
``` php
<?php
class Customer extends CustomerCore
{
    /**
     * Property defined on a single line is properly uninstalled
     */
    /*
    * module: xxx
    * date: 2020-12-31 07:58:44
    * version: 1.0.0
    */
    public static $test;
    /**
     * Property defined on multiple lines will fails to uninstall properly
     */
    /*
    * module: xxx
    * date: 2020-12-31 07:58:44
    * version: 1.0.0
    */
    public static $definition = array(
        'table' => 'customer',
        'primary' => 'id_customer',
        // ...
        ),
    );
}
```

Result after uninstall:
``` php
<?php
class Customer extends CustomerCore
{
        'table' => 'customer',
        'primary' => 'id_customer',
        // ...
        ),
    );
}
```

This issue happens on Prestashop  1.7.6.9

**Comment by hibatallahAouadni** [comment] 2020-12-31 13:45
Hello @Seb33300 

Could you please check if your issue is similar to this one #20377

Thanks!

**Comment by Seb33300** [comment] 2021-01-01 11:10
Yes, same issue

**Comment by hibatallahAouadni** [comment] 2021-01-01 13:40
Hello @Seb33300 

Great, so that issue is already in our debug backlog. This issue is a duplicate of #20377. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-01 13:41
Duplicate of #20377

**Closed as completed by hibatallahAouadni** 2021-01-01 13:40 UTC
Labels: Bug, CO, Duplicate, Modules, 1.7.6.9
