### ISSUE TITLE
BO: Page header overlap modal windows

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#11254] opened 2018-11-04 09:45 UTC
**Describe the bug**
BO: Page header overlap modal windows on some pages. Please see the video to reproduce the bug.

**Video**
https://vimeo.com/298824399/853e595698

**Additionnal information**
PrestaShop version: PrestaShop 1.7.5.0 (nightly build 2018-10-30)
PHP version: 7.2.1

**Comment by khouloudbelguith** [comment] 2018-11-05 10:04
Hi @Caleydon,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11104 to fix the issue.
Your ticket is a duplicate of #11042
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-05 10:04
Duplicate of #11042

**Closed as completed by khouloudbelguith** 2018-11-05 10:04 UTC
Labels: Duplicate
