### ISSUE TITLE
Prestashop 1.7.7.4 Test Email Issue Error 220

### ISSUE THREAD

**Issue by OliveCodeTester** [PrestaShop/PrestaShop#24685] opened 2021-05-28 04:01 UTC
I am trying to send out test emails and got an error message that states:

> Error: Please check your configuration
> Expected response code 220 but got an empty response

#### Steps to Reproduce

1. Go to 'Advanced Parameters'
2. Click on 'E-mail'
3. Scroll down to 'Test your email configuration'
4. See error: Error: Please check your configuration
Expected response code 220 but got an empty response

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-05-28 07:40
Hello @OliveCodeTester ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a **server configuration** or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2021-05-28 07:40 UTC
Labels: No change required

**Comment by federicoprimomo** [comment] 2021-06-27 20:50
The problem is real, I changed php to show real error, this is the message : 
_**Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.**_
