### ISSUE TITLE
The PrestaShop 8.15 installation assistant failed to install the theme after entering MySQL information.

### ISSUE THREAD

**Issue by likeMJhappy** [PrestaShop/PrestaShop#35764] opened 2024-03-28 01:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The PrestaShop 8.15 installation assistant failed to install the theme after entering MySQL information.PrestaShop 8.15 version installation assistant, after entering the MySQL information, can not install the theme, retry many times can not, MySQL version is 5.7.44, looking forward to your reply, attached figure above.
![A4B4819E-E425-4C54-B050-4D871C7F8A0C](https://github.com/PrestaShop/PrestaShop/assets/141382486/2b6e8247-fbec-42a7-9929-f973c139c0b9)

### Steps to reproduce

1. Place the installation package in /var/www/html
2. Start nginx, automatically decompress, and configure the store information
3. Configure the database connection information and the connection is successful
4. Failed to install the store theme with error server500

### PrestaShop version(s) where the bug happened

8.1.4

**Comment by paulnoelcholot** [comment] 2024-03-28 08:12
Hello @likeMJhappy,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://www.loom.com/share/8806f5362f3447f29f88cbacf64c167d?sid=f9931bc1-6117-4aeb-b0ba-090d6eab467a

**Closed as completed by paulnoelcholot** 2024-03-28 08:12 UTC
Labels: Bug, Can't reproduce
