### ISSUE TITLE
known column 'shipping_number' in 'field list

### ISSUE THREAD

**Issue by forkyboy** [PrestaShop/PrestaShop#32349] opened 2023-04-26 14:15 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

at check out after selecting the payment method an error 500 is displaying with this :

[known column 'shipping_number' in 'field list](https://live.staticflickr.com/65535/52848206968_f2d7465a78_o.png)

i checked and the DB is up to date i am clueless

### Steps to reproduce

at check out after selecting the payment method an error 500 is displaying with this :

[known column 'shipping_number' in 'field list](https://live.staticflickr.com/65535/52848206968_f2d7465a78_o.png)

i checked and the DB is up to date i am clueless

### PrestaShop version(s) where the bug happened

17.8.8

### PHP version(s) where the bug happened

7.3

**Comment by djoelleuch** [comment] 2023-04-26 16:02
Hello @forkyboy ,
I  try to reproduce your issue, as you can see :

[Untitled_ Apr 26, 2023 5_47 PM.webm](https://user-images.githubusercontent.com/115152460/234634364-b32e7769-b4c4-460b-8321-7109ea2ea6d3.webm)


But currently I didn't reproduce your issue, did I miss something ?

Waiting for your feedback

**Comment by tesshsu** [comment] 2023-05-02 10:38
Hi @forkyboy 
There's some point you might need to clean out first before we dig into fixing the bug:
1. The Prestashop version you mentioned 17.8.8 is not exist, the lasted one is version 8
2. Form the error message: known column 'shipping_number' in 'field list, as Insert_INTO 'ps_orders'
You should first go to your phpMyAdmin in your localhost -> Navigate to the ps_orders table and click on the "Structure" tab ->Check if there is a column named shipping_number->If not, click on the "Add" button to add a new column to the table->Set the column name as shipping_number, and select the appropriate data type (e.g. INT, VARCHAR, etc.) depending on your requirements->Save the changes
3. Make sure you had clean-cache once your modification dedicated to the database
4. Test the checkout process again to ensure that the error has been resolved

If still not resolved, then you could please make sure your Prestashop version is first cause version 7 and version 8 had different structure

**Comment by hibatallahAouadni** [comment] 2023-05-16 00:00
Hello @forkyboy 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-16 00:00 UTC
Labels: Bug, FO, Checkout, Invalid, 1.7.8.8
