### ISSUE TITLE
File Not Found on order page 

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18310] opened 2020-03-25 14:17 UTC
File not found going to order page if url rewrite missing in SEO & URL

maybe this problem is caused by prestashop update, i don0t know

adding url rewrite all works fine.
<img width="1255" alt="Schermata 2020-03-25 alle 15 10 39" src="https://user-images.githubusercontent.com/5024055/77546171-c44c0200-6eab-11ea-908e-ea03270bfc20.png">
<img width="716" alt="Schermata 2020-03-25 alle 15 10 22" src="https://user-images.githubusercontent.com/5024055/77546182-c6ae5c00-6eab-11ea-9b50-c6bf7dfc56a9.png">
<img width="1252" alt="Schermata 2020-03-25 alle 15 08 26" src="https://user-images.githubusercontent.com/5024055/77546188-c7df8900-6eab-11ea-8ae3-0b7292a92a1f.png">
<img width="593" alt="Schermata 2020-03-25 alle 15 08 14" src="https://user-images.githubusercontent.com/5024055/77546191-c910b600-6eab-11ea-9d2c-16c7e415d04e.png">

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-03-25 14:29
Hi @Betafer ,
Despite our several trials, I could not reproduce your issue with the provided information.
Even when I deleted the order page from SEO & URL, the page still shows on front-office.
Did you do an upgrade ? If yes, what is your old PrestaShop version ? 
Thanks to check !

**Comment by Betafer** [comment] 2020-03-25 14:31
Yes, from 1.5.6.3

**Comment by florine2623** [comment] 2020-03-25 14:32
Did you use 1-click upgrade module ? or another tool ?

**Comment by Betafer** [comment] 2020-03-25 14:38
Yes 1 click upgrade to 1.6 the to 1.7  

i also notice the same error with search pages, but error did't solve by enter the page url like with order page ..

**Comment by florine2623** [comment] 2020-03-25 14:42
Thanks for the details,

Maybe the error comes from your .htaccess.
Could you try to : 
- Rename .htacess to .htaccess_old
- In SEO & URL, disable friendly URL and save
- Enable friendly URL and save again
- Check your order page

Thanks

**Comment by Betafer** [comment] 2020-03-25 14:52
But should it work if the url is empty?

**Comment by Betafer** [comment] 2020-03-25 15:00
> Thanks for the details,
> 
> Maybe the error comes from your .htaccess.
> Could you try to :
> 
> * Rename .htacess to .htaccess_old
> * In SEO & URL, disable friendly URL and save
> * Enable friendly URL and save again
> * Check your order page
> 
> Thanks

The url field is empty, I don't think your procedure works.
Regards

**Comment by florine2623** [comment] 2020-03-25 15:00
No the field is required (*), when you try to save it without filling the field, you get an error : 
![Capture d’écran 2020-03-25 à 15 59 23](https://user-images.githubusercontent.com/16019289/77550663-ad101300-6eb1-11ea-96c5-870dc72c10e2.png)

**Comment by Betafer** [comment] 2020-03-25 15:03
Ok, the update made this error, no way

**Comment by florine2623** [comment] 2020-03-25 15:10
So, it could be that something went wrong with your update and don't have some of the database columns that were added for 1.7.6.3
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.3 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.3/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by Betafer** [comment] 2020-03-25 15:42
Ok Thanks

**Comment by florine2623** [comment] 2020-03-25 15:43
Can we now close the issue ?

**Comment by Betafer** [comment] 2020-03-25 15:46
Yes

**Closed as completed** 2020-03-25 15:49 UTC
Labels: Bug, FO, Traffic & SEO, SEO & URLs, No change required, Checkout, 1.7.6.3
