### ISSUE TITLE
more than one H1 tag in the category pages - the errors are in category.tpl and active_filters.tpl

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10444] opened 2018-09-15 19:40 UTC
Hi

**Describe the bug**
in the category pages there are more than one H1 tag
the problems arein category.tpl and active_filters.tpl files

in active_filters.tpl this code (you need only to replace the h1 with a p tag)
`<h1 class="h6 {if $activeFilters|count}active-filter-title{else}hidden-xs-up{/if}">{l s='Active filters' d='Shop.Theme.Global'}</h1>`
should be
`<p class="h6 {if $activeFilters|count}active-filter-title{else}hidden-xs-up{/if}">{l s='Active filters' d='Shop.Theme.Global'}</p>`

instead in category.tpl file there are 2 H1 one for mobile and one for desktop but it is wrong because in the source code should be only one h1 tag

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/45589996-faf8a200-b92f-11e8-9f72-30e555551fd3.png)
![2](https://user-images.githubusercontent.com/653230/45589997-faf8a200-b92f-11e8-8056-f07d16a6297a.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by MathiasReker** [comment] 2018-09-16 18:26
PR : https://github.com/PrestaShop/PrestaShop/pull/10447

**Comment by khouloudbelguith** [comment] 2018-09-17 09:17
Hi @maofree,

Thanks for your report.
@Mreker, thanks for your fix

Best regards, Khouloud

**Comment by PierreRambaud** [comment] 2018-09-17 10:21
F.Y.I: We can have multiple h1 per section. Even google said it's ok to have multiple h1: 
 - https://www.youtube.com/watch?v=WsgrSxCmMbM
 - http://www.suvaance.com/microblog/how-google-considers-multiple-h1-tags-in-one-page/

And this is in the RFC https://tools.ietf.org/html/rfc1866#section-5.4 and google have at least 91% of the global search, and Bing 3.5% and I'm sure they are following the RFC ^^ (http://gs.statcounter.com/search-engine-market-share)

Don't forget we are in HTML5 now. I'm not in favor to change this behavior.

**Comment by Maofree** [comment] 2018-09-18 09:39
Hi Pierre
however for me has no sense to add 2 H1 just to set a h1 for the desktop and a h1 for mobile, it would make more sense to use only one h1 and then find changes with the css code

from that suvaance.com is written
 In HTML5, the semantic elements like header, footer, section etc, help representing the hierarchy perfectly and one can use one H1 tag in each such elements safely.

So, if you think different sections need separate H1 tag, don’t worry, feel free to use.

**Just don’t add the same text in every H1.**

so repeat the same test in the same section even if the div is different it is not a great idea

so those 2 category H1 are a seo bug also in html5

bye

**Comment by PierreRambaud** [comment] 2018-09-18 10:05
@maofree I understand why you mean for the first two H1, but the PR remove the third one :)

**Comment by Maofree** [comment] 2018-09-18 10:09
ok
I'll create a new ticket
thanks

**Comment by Maofree** [comment] 2018-09-18 10:14
done
https://github.com/PrestaShop/PrestaShop/issues/10470

**Comment by PierreRambaud** [comment] 2018-09-24 07:57
I close this one bacause it's a duplicate of #10470 . Thanks @maofree

**Closed as completed by PierreRambaud** 2018-09-24 07:57 UTC
Labels: FO, Duplicate, 1.7.4.2

**Comment by azitafomo** [comment] 2019-11-12 13:17
Hi

Multiple H1 tags in Hrefs Site audit is one error. It means all my categories and pages are showing one same word twice.

as an example:

tea maker category page [https://20bekhar.com/62-tea-maker] has two same H1: tea maker & tea maker that one of them is for mobile and one h1 for desktop.It is something that I can see in view page source:

<h1 class="shik-cat">tea maker</h1></div></div><div class="hidden-md-up"><h1 class="hrxmobile-view-category-title">tea maker</h1>

Could you help me about this item to fix this problem?

**Comment by azitafomo** [comment] 2019-11-13 09:57
> PR : #10447

I have same problem: 2 H1 just to set a h1 for the desktop and a h1 for mobile, please help me to fix this problem in the codes
could you tell me the exact work that I should do to solve?
