### ISSUE TITLE
Improve image management for product combination

### ISSUE THREAD

**Issue by tlhuillier** [PrestaShop/PrestaShop#12726] opened 2019-02-26 17:02 UTC
**Is your feature request related to a problem? Please describe.**
It is not possible to set the cover image of a product combination, nor reorder images for a product combination.
The only thing you can do is to select what images you want (from the base product images) to display a specific combination.

**Describe the solution you'd like**
I think images need a bit more love in Prestashop in general.
Nowadays, they have a huge impact in the customer decision making,
and it is especially important for e-commerce.
For every product combination, you should be able to :
- set which images you want to display for a specific combination (already possible)
- reorder images (todo)
- define a cover a image (todo)

**Additional context**
This is especially important UX wise because when a combination is added to the cart, 
the customer should be presented a thumbnail corresponding to the combination he picked (eg. pink shoes if he picked pink).

**Comment by khouloudbelguith** [comment] 2019-02-26 17:05
Hi @tlhuillier,

Thanks for your report.
@marionf, @colinegin what do you think?
Thanks!

**Comment by marionf** [comment] 2019-02-26 17:10
Duplicate of #12241

**Comment by marionf** [comment] 2019-02-26 17:12
@tlhuillier your improvement idea has already been reported here: #12241
You can follow this issue or add comments
Regards

**Closed as completed by marionf** 2019-02-26 17:12 UTC
Labels: Improvement, Duplicate, Image, Combinations
