### ISSUE TITLE
BO / some BO pages/links seems broken after upgrading from 1.6.1.24 to 1.7.7.2

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#23277] opened 2021-02-16 15:57 UTC
#### Describe the bug

After an upgrade, some links of the BO menu redirect to the dashboard ( with an exception in console)
Some page have an "access denied" message error

#### Expected behavior
All pages and links should work correctly

#### Steps to Reproduce

1. After an upgrade from 1.6.1.24 to 1.7.7.2
2. In the BO click on the Orders / orders link 
3. See error => redirection to the dashboard page and error in console
4. Try other page => some page are fully fonctionnal and some have "access denied" message error

PS : The problem does not appear in everyone for this outcome only @khouloudbelguith, @hibatallahAouadni and I have this issue

**Screenshots**
https://www.awesomescreenshot.com/video/2773013?key=c3c82435e9d2baed65748893f44ada41

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.1
* MYSQL version 5.7

**EDIT : This issue is also reproduced wtih an upgrade from 1.6.1.24 to 1.7.6.9 or 1.7.7.1**
Screen record from @khouloudbelguith 
https://drive.google.com/file/d/1_Wst2G92nnRen-Or84UCaKqRsHbkE01O/view?usp=sharing

**Comment by SD1982** [comment] 2021-02-16 15:58
@atomiix WDYT ?

**Comment by PierreRambaud** [comment] 2021-02-16 16:13
Isn't the same as #9513 ?

**Comment by SD1982** [comment] 2021-02-16 17:09
I don't think but there is some commons points and maybe the problem are related

**Comment by matks** [comment] 2021-04-15 13:36
Hi @SD1982 I see this issue is not reproduced by everyone.

Since the time you wrote this issue, did you find any way to accurately target what makes some people reproduce it and others do not reproduce it?

**Comment by atomiix** [comment] 2021-05-10 13:01
Hi everyone, I was able to reproduce the issue thanks to @Robin-Fischer-PS. The issue does not come from the autoupgrade process but from the state of the DB **before** the upgrade.

Before [this PR](https://github.com/PrestaShop/PrestaShop/pull/18451/files), `readdir()` was used leading to an unpredictable order of the file listed. This order had an impact on the entries in the DB and on the `ps_access` & `ps_module_access` in particular. This was not a problem for the 1.6 but after the migration to an 1.7, that lead to unauthorized access on certain pages of the BO.

I'm now looking for a way to fix this during the upgrade process.

**Comment by Progi1984** [comment] 2021-05-11 09:18
Fixed in #24443 by @atomiix

**Closed as completed by Progi1984** 2021-05-11 09:18 UTC
Labels: Bug, Major, BO, Autoupgrade, Fixed, 1.7.7.x
