### ISSUE TITLE
Related product missing name & image in product edit page

### ISSUE THREAD

**Issue by Renrhaf** [PrestaShop/PrestaShop#28269] opened 2022-04-15 12:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the edit page of a product, some related products does not have any name, reference, and image.
Thus it is difficult to know which product it is in reality without any visible information.

![image](https://user-images.githubusercontent.com/690629/163570252-bc296282-8569-4b3a-89f1-4c952d33864f.png)

### Expected behavior

We could at least display the product identifier if no reference is found, and it's name if possible.

### Steps to reproduce

1. Edit a product and remove it's reference
2. Go to an other product edit page
3. Add the product without reference in the "related product" field
4. See that the reference is missing.
5. Picture and name might be missing at the moment too in some specific cases.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3.33

**Comment by HanaRebaiQA** [comment] 2022-04-15 13:57
Hello @Renrhaf 

Thanks for reporting the issue.
I did reproduce the issue with Product V1 but it's fixed in Product V2 on develop with this [PR](https://github.com/PrestaShop/PrestaShop/pull/25920).

**Product V1** 
![image](https://user-images.githubusercontent.com/92912932/163579109-1a24cb04-63be-4497-aa76-4024704b1884.png)

**Product V2**
![image](https://user-images.githubusercontent.com/92912932/163579518-4fd5f7d0-96d0-458b-bc73-d84e6c898353.png)

https://user-images.githubusercontent.com/92912932/163579532-b45a3da7-f55d-4f02-9042-4ffe1634bccc.mp4

So, i'll close the issue since it's not present with product V2.

Thank you!

**Closed as completed by HanaRebaiQA** 2022-04-15 13:57 UTC
Labels: Bug, PR available, Invalid
