### ISSUE TITLE
Setup fails at "Configure shop information" - v1.7.6.9

### ISSUE THREAD

**Issue by steveking198** [PrestaShop/PrestaShop#21963] opened 2020-11-17 19:44 UTC
#### Describe the bug

On the installer I get as far as "Configure shop information" then it fails every time with the error

```
An error occurred during installation...

You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

    1: Unable to write into "en-US"" (data layer : "PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer")
```

I'm running nginx/php on the Ubuntu subsystem for Windows

I've ran the `phppsinfo` script and it all looks ok apart from a couple optional php extensions

#### Expected behavior

Setup to continue

#### Steps to Reproduce

Follow installation instructions on WSL/nginx

**Screenshots**

![Screenshot_2020-11-17 PrestaShop Installation Assistant](https://user-images.githubusercontent.com/1047124/99439221-d122d780-290c-11eb-961d-1f810d8c287a.png)

![Screenshot_2020-11-17 PHP PrestaShop Info](https://user-images.githubusercontent.com/1047124/99439253-d7b14f00-290c-11eb-8894-b6a6847e3860.png)

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2.34

**Comment by matks** [comment] 2020-11-17 22:22
Hi @steveking198 this issue has been reported before and it seems to be related to your setup
see https://github.com/PrestaShop/PrestaShop/issues/16529#issuecomment-575635077 😉

**Comment by hibatallahAouadni** [comment] 2020-11-18 07:48
Hello @steveking198 

As @matks mentioned above, we are aware of this issue. This issue is a duplicate of #16529 . 
Please check the issue mentioned above to find the solution of your problem.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-18 07:48
Duplicate of #16529

**Closed as completed by hibatallahAouadni** 2020-11-18 07:48 UTC
Labels: Duplicate
