### ISSUE TITLE
In Cart Rule, when Sending a free gift to a customer, it isn't mentioned on the order (BO & FO)

### ISSUE THREAD

**Issue by fanny300** [PrestaShop/PrestaShop#19593] opened 2020-06-05 10:26 UTC
Hello i'm french, i try to explain correctly the problem :

#### Describe the bug

I have a cart rule : for 3 product buy you have 1 product offer.
The price of the product gift is 0€ ( The price is not fixed, a different product gift is sent depending on stock )

I do an order with 3 products + 1 product gift, automaticaly add (with out code).
The order work but, no recording in the table order_cart_rule about this product gift.

Bug 1 : In backoffice, see the new order, there isn't a line about the produit offer
Bug 2: In frontoffce, go on history of order, click on re-order, in cart you got : 
3 product + 2 product gift.

The customer can make an order with 2 product offer instead of one.

The script which sorting the product gift not work because there no recording in the table order_cart_rule

#### Steps to Reproduce

Create a product at 0€ (call for example : 1 Product Offer for 3 product buy) I don't want make a price visible by customer for this product Gift.

Create a cart rule, in condition select : product gift and select the product at 0€

Create an order with the cart rule product gift at 0€.

Go to backoffice in the new order = no info about a gift offer
Go on frontoffice, in your account, history of order : click on re-order the next order.
In cart there on product gift in excess

####### Solution : 

I have override : override/classes/PaymentModule.php 
function createOrderCartRules
line : 1077 ( in classes/PaymentModule.php )

Replace : 
```
// If the reduction is not applicable to this order, then continue with the next one
            if (!$values['tax_excl']) {
                continue;
            }
```

By : 

```
// If the reduction is not applicable to this order, then continue with the next one
         if (!$values['tax_excl'] && empty($cartRule->gift_product)) {
                continue;
          }
```

* PrestaShop version: 1.7.6.4, 1.7.6.5
* PHP version: 7.0

**Comment by florine2623** [comment] 2020-06-05 12:58
Hi @fanny300 ,

Thanks for the report. I did reproduce your issue on PS 1.7.6.5 and PS 1.7.7.0 partially.
Regarding this : _Go on FO, in your account, history of order : click on re-order the next order.
In cart there on product gift in excess_
I did not reproduce it.

The exact steps I used to reproduce the issue :
- Create a 0€ product
- On tab "Options", uncheck "available for order"
- Create a Cart Rule -> Actions > Send a free gift to YES
- On FO, place an order, apply Discount, get your free gift
- As a client, you don't know what gift it is. It is not mentioned on the order/history order
- On BO, as a merchant, in the order, you don't know that a discount has been applied and that a free gift is supposed to be sent to the customer.

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Hlavtox** [comment] 2020-06-08 17:34
@florine2623 Free gifts do not display correctly for more than 3 years. https://github.com/PrestaShop/PrestaShop/issues/9757

Maybeeeeee it can be finally fixed? 🙏 @matks

**Comment by florine2623** [comment] 2020-06-26 09:29
Hi @fanny300 ,
This is a duplicate of #9757 as @Hlavtox said.
So I will close your issue, you can follow #9757 for more updates.

**Comment by florine2623** [comment] 2020-06-26 09:29
Duplicate of #9757

**Closed as completed by florine2623** 2020-06-26 09:29 UTC
Labels: Bug, Major, BO, FO, Duplicate, Order, Discounts, Cart rules, 1.7.7.0, 1.7.6.5
