### ISSUE TITLE
Refund Shipping after refund all products not working

### ISSUE THREAD

**Issue by beyondsagency** [PrestaShop/PrestaShop#19829] opened 2020-06-17 15:45 UTC
### Describe the bug

When we try to refund shipping cost after refund all products it's not working.

#### Expected behavior

We can refund shipping cost after refund all products in previous step.

#### Steps to Reproduce

1. Go to an order
2. Refund all products
3. Return to this order
4. Make a new refund with shipping cost
5. See error "The partial refund data is incorrect."

#### Idea to fix this issue

We can change the condition :
`if (Tools::isSubmit('partialRefundProduct') && ($refunds = Tools::getValue('partialRefundProduct')) && is_array($refunds))`

By : 
`if ((Tools::isSubmit('partialRefundProduct') && ($refunds = Tools::getValue('partialRefundProduct')) && is_array($refunds)) || Tools::getValue('partialRefundShippingCost') && Tools::getValue('partialRefundShippingCost') > 0)`

#### Additional information

* PrestaShop version: 1.7.6.X

**Comment by florine2623** [comment] 2020-06-18 09:12
Hi @beyondsagency ,

Indeed the issue is reproducible in PS 1.7.6.5. However this bug has been fixed in PS 1.7.7. I would advise you to wait for the update to take advantage of this feature.
You can follow PS 1.7.7 progress here : https://github.com/PrestaShop/PrestaShop/projects/7 

For now, I close your issue.
Thanks!

**Closed as completed by florine2623** 2020-06-18 09:12 UTC
Labels: No change required, Fixed
