### ISSUE TITLE
Issue with Product Comments module

### ISSUE THREAD

**Issue by templatin** [PrestaShop/PrestaShop#14827] opened 2019-07-23 13:14 UTC
I have installed Product Comments module (v4.0.0) on fresh installation of PS 1.7.6.0.
The contents of product comments module are not displayed.
After enabling debug mode, it shows below  error:
`Class PrestaShop\Module\ProductComment\Repository\ProductCommentRepository does not exist.`

**Comment by khouloudbelguith** [comment] 2019-07-23 13:29
Hi @templatin,

 I did not manage to reproduce the issue with PS1.7.6.0 & the product comments module v4.0.0.
I attached a screen record
https://drive.google.com/file/d/1BhvG0ZUftJzm746t3znOHfmVlClK8Pqi/view
Did you installed this module from the BO => Module Catalog page?

Thanks!

**Comment by templatin** [comment] 2019-07-23 13:44
@khouloudbelguith Thanks for prompt reply.
Yes, I did in the same way as yours. I'm working on localhost (wamp) and tested it twice with fresh PS and got same issue each time.

**Comment by khouloudbelguith** [comment] 2019-07-23 14:05
@templatin, could you please try with this module
[productcomments.zip](https://github.com/PrestaShop/PrestaShop/files/3422442/productcomments.zip)
check & feedback.

Thanks!

**Comment by templatin** [comment] 2019-07-23 15:22
It works with your zip!!
It has "vendor" folder which I didn't get in downloaded zip from github.

**Comment by khouloudbelguith** [comment] 2019-07-23 15:41
@templatin, it is normal behavior, if you cloned it from GitHub, you need to run `composer install`
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-23 15:41 UTC
Labels: Bug, BO, No change required, Productcomments, 1.7.6.0

**Comment by templatin** [comment] 2019-07-25 10:42
@khouloudbelguith I found another issue. The module displays reviews only on first instance of a product on homepage. Check screenshot.

To reproduce the issue, install Featured Products module and any other native module (New Products or Best sellers or Specials module) which will be hooked on home page.

Example: In Featured products module on homepage, reviews are displayed for product (Hummingbird shirt) which is fine. Now, if this same product is also available in New products module, then reviews are not displayed in it.

![module](https://user-images.githubusercontent.com/3615808/61867997-12ac9980-aef6-11e9-986d-391e2615fa01.jpg)

**Comment by khouloudbelguith** [comment] 2019-07-26 10:57
Hi @templatin, because you only an approved review for this product.
 I attached a screen record
https://drive.google.com/file/d/1qQtNjKtLMSM2ZR00KMqTXix-ABUtAdeQ/view

Thanks!

**Comment by templatin** [comment] 2019-07-26 15:19
@khouloudbelguith You didn't understand the issue.
The reviews are not displayed for a product if it appears multiple times in another module on same page.
As I can see in your recording, you already have Popular products module on homepage. Now install another native module (Example: Specials block (ps_specials)) and notice that reviews are not displayed for product "Hummingbird printed sweater".

![git](https://user-images.githubusercontent.com/3615808/61961868-ecfebd80-afe5-11e9-81a1-5c847662058f.jpg)

**Comment by khouloudbelguith** [comment] 2019-07-26 16:37
@templatin; thanks for these clarifications
Issue created here: #14878

Thanks!
