### ISSUE TITLE
Problem with vertical sliding in the product combination 1.7.6.2

### ISSUE THREAD

**Issue by Davidlleide** [PrestaShop/PrestaShop#16885] opened 2019-12-20 15:44 UTC
**Describe the bug**
Problem with vertical sliding in the product combination. When the color of a product changes in a combination. When you go to the product, the vertical sliding stops working.

**To Reproduce**
[Fallo-slider-vertical.zip](https://github.com/PrestaShop/PrestaShop/files/3988997/Fallo-slider-vertical.zip)

**Screenshots**
see video

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-12-20 15:48
Hi @Davidlleide,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16863 to fix the issue.
Your ticket is a duplicate of #12064
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-12-20 15:48
Duplicate of #12064

**Closed as completed by khouloudbelguith** 2019-12-20 15:48 UTC
Labels: Duplicate
