### ISSUE TITLE
Related products

### ISSUE THREAD

**Issue by mikitarra** [PrestaShop/PrestaShop#16878] opened 2019-12-20 09:33 UTC
When I looking for related products, do not show the main product related to the product sheet I am modifying.

**Comment by khouloudbelguith** [comment] 2019-12-20 09:37
Hi @mikitarra,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9617
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-12-20 09:38
Duplicate of #9617

**Closed as completed by khouloudbelguith** 2019-12-20 09:37 UTC
Labels: Duplicate
