### ISSUE TITLE
Error after installing in public server

### ISSUE THREAD

**Issue by techguydev** [PrestaShop/PrestaShop#19136] opened 2020-05-14 14:40 UTC
#### Describe the bug

I have followed the installation process as suggested, everything seems to work just fine, the process ends and then when I try to visit the front-end  it says:

```An error has occured:
Unzipping error - Unable to find the release zip file. Make sure that the prestashop.zip file has been uploaded and is located in the same directory as this dezipper```


Which does not make sense since the installation has already happened.

I have already deleted the /install folder.

Although I can not access the fronted I can access the backend.

Any thought?


A clear and concise description of what went wrong.

#### Expected behavior

Normal installation and use.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.3

**Comment by florine2623** [comment] 2020-05-15 08:20
Hi @lmatab ,
I can't reproduce your issue.
Is this a live shop or a localhost shop ? Make sure the URL you are looking into is correct.
Please add screenshot of the folders and the site, if there are any errors please send them.
Thanks!

**Comment by RomanD85** [comment] 2020-05-26 22:53
Hi,
I have the same problem as @lmatab .
Can you help me with that?

**Comment by florine2623** [comment] 2020-05-28 08:29
Hi @RomanD85 ,
Make sure you are using PHP 7.2 if you are installing PrestaShop 1.7.6.5.
Here's the compatibility check : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Also I can't reproduce the issue.
Please check with your host as the error might come from there.
Thanks!

**Comment by florine2623** [comment] 2020-06-11 08:07
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-11 08:07 UTC
Labels: IN, No change required, 1.7.6.5
