### ISSUE TITLE
Duplicate Entry - Module Block Reassurance for upgrade

### ISSUE THREAD

**Issue by PimpamCraveIt** [PrestaShop/PrestaShop#23014] opened 2021-01-27 13:59 UTC
#### Describe the bug

When trying to update, See error : "Exception retournée par le module blockreassurance pour upgrade (Exception returned by the BlockReassurance module for upgrade) . Duplicate entry 'ROLE_MOD_TAB_ADMINBLOCKLISTING_CREATE' for key 'slug' "

I think it is an SQL error but i don't know what is the tab in the database who has this error..? 
Or is it an issue about the files ? If it is, what are the files concerned by this error ? 

#### Expected behavior

Update the module Customer Reassurance from v 3.0.1 to 4.1.1

#### Steps to Reproduce

1. Go to 'Module Manager' --> Update
2. Click on 'Upgrade'
3. See error : "Exception retournée par le module blockreassurance pour upgrade (Exception returned by the BlockReassurance module for upgrade) . Duplicate entry 'ROLE_MOD_TAB_ADMINBLOCKLISTING_CREATE' for key 'slug' "

1. Go to 'Module catalog' --> Download the package
2. Upload the package in 'Module Manager'
3. See error : "Exception retournée par le module blockreassurance pour upgrade (Exception returned by the BlockReassurance module for upgrade) . Duplicate entry 'ROLE_MOD_TAB_ADMINBLOCKLISTING_CREATE' for key 'slug' "

**Screenshot**
https://drive.google.com/file/d/1ksx89e5Rtzbgk9Dn-_CjYOGhfbOoGAX8/view

#### Additional information

* PrestaShop version: 1.7.5.0
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-01-27 16:05
Hello @PimpamCraveIt 

I didn't manage to reproduce your issue with PS1.7.5.2 and PS1.7.7.1, see the attached screen record below:

**PS1.7.5.2: v3.0.1 -> v4.1.1**

https://drive.google.com/file/d/1XUne4w_UGjKnZI6cI0R1OI9pPQyyk6UL/view

**PS1.7.7.1: v3.0.1 -> v5.0.0**

https://drive.google.com/file/d/1Kc2Cnvasx-7JnM135-ZFF3BsgyKFrCtD/view

Please check and feedback.
Thanks!

**Comment by PimpamCraveIt** [comment] 2021-01-28 15:30
Hi, sorry for the explication @hibatallahAouadni , i didn't achieve to explain it very well 
There is the video for the apparition of the error 

https://drive.google.com/file/d/1ksx89e5Rtzbgk9Dn-_CjYOGhfbOoGAX8/view

**Comment by hibatallahAouadni** [comment] 2021-01-28 16:23
Hello @PimpamCraveIt 

I saw your screen record and I saw clearly the error but unfortunally I didn't manage to repdroduce as you can see in my screen record mentioned above.
Is there any detail that you forget to mention? maybe an override?

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:23
Hello @PimpamCraveIt ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-17 13:23 UTC
Labels: Bug, BO, No change required, Module manager, 1.7.5.0, Blockreassurance, 1.7.5.2, 1.7.7.1

**Comment by PimpamCraveIt** [comment] 2021-02-17 15:49
Solution : if you have this issue, you need to reinitialize the plugin then update it

**Comment by hibatallahAouadni** [comment] 2021-02-17 15:50
@PimpamCraveIt Thanks :wink:
