### ISSUE TITLE
Incorrect totals excluding tax in confirmation email

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#28230] opened 2022-04-12 08:15 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you setup your shop to show prices excluding taxes, in the confirmation email, all totals (except the products total) include taxes.

![image](https://user-images.githubusercontent.com/915273/162915879-9195e991-27de-4418-87ae-9931cc16b9b5.png)

### Expected behavior

All totals should be displayed without taxes:

![image](https://user-images.githubusercontent.com/915273/162915758-4ea28963-6fbf-4dd0-a7d9-1bd638cbff1a.png)

### Steps to reproduce

1. Setup your store to display prices excluding taxes (in customer group)
2. Enable gift wrapping option
3. Setup a shipping method (not free)
4. Setup a cart discount
5. Order a product with discount + shipping + gift wrapping
6. See totals including taxes in confirmation email

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment] 2022-04-12 08:57
Hello @Seb33300,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #[17764](https://github.com/PrestaShop/PrestaShop/issues/17764) 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment] 2022-04-12 08:57
Duplicate of #[17764](https://github.com/PrestaShop/PrestaShop/issues/17764)

**Closed as completed by marwachelly** 2022-04-12 08:57 UTC
Labels: Bug, Duplicate, Invalid
