### ISSUE TITLE
On click all products it show product from categories not assigned to visitor 

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#15351] opened 2019-09-01 20:33 UTC
Hi, we create a new group of users and assign a special category to them, so only selected client can see this products.

![image](https://user-images.githubusercontent.com/46203943/64081939-af244180-ccd5-11e9-92ad-7a94784a1c33.png)

when you click on the category it say you are not authorized and do not show any product as should be.

![image](https://user-images.githubusercontent.com/46203943/64081945-c95e1f80-ccd5-11e9-808b-e180efcf40c6.png)

but when you click on all products on home page it show all products and the products from this "hide" category.

![image](https://user-images.githubusercontent.com/46203943/64081952-eabf0b80-ccd5-11e9-8d9f-d13dbad7fa1d.png)

when you click on the product it say you are not authorized to see it but the client already saw the product description, image and price!

![image](https://user-images.githubusercontent.com/46203943/64081978-193ce680-ccd6-11e9-8aa2-1dc8f99e4e83.png)

PrestaShop version: 1.7.5.2
PHP version: 7.2.15

**Comment by khouloudbelguith** [comment] 2019-09-02 08:58
Hi @msautral,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9832
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-02 08:58
Duplicate of #9832

**Closed as completed by khouloudbelguith** 2019-09-02 08:58 UTC
Labels: FO, Duplicate, Customer, Categories
