### ISSUE TITLE
Shipping carrier name translation 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#17491] opened 2020-02-04 11:51 UTC
Hi,
By now we can't change translation of the shipping carrier name.
Only carrier "description" (delivery time).

It would be nice to translate also names like
UPS international shipping for EN
Dostawa międzynarodowa UPS for PL
UPS Internationaler Versand for DE

![translate-shipping](https://user-images.githubusercontent.com/8243273/73742387-9ddfd500-474c-11ea-9116-948720440023.jpg)

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-04 12:30
Hi @PrestaShark,

Your ticket is a duplicate of #12901
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-04 12:30
Duplicate of #12901

**Closed as completed by khouloudbelguith** 2020-02-04 12:30 UTC
Labels: Duplicate
