### ISSUE TITLE
Error in gift wrapping option in PS 1.7.2

### ISSUE THREAD

**Issue by Himanshu-bishtt** [PrestaShop/PrestaShop#14659] opened 2019-07-15 13:06 UTC
Hi,
I am using Prestashop 1.7.2 and PHP - 5.6.40

As you can see in the image when I am trying to enable gift wrapping, I am getting an error says "Assign a valid page if you want it to be read."
Why is this error happening?

Please help us,
Thanks

![Screenshot from 2019-07-15 18-27-07](https://user-images.githubusercontent.com/52812453/61218202-19395500-a72f-11e9-9899-ebb9ca3dbd36.png)
![Screenshot from 2019-07-15 18-27-10](https://user-images.githubusercontent.com/52812453/61218203-19d1eb80-a72f-11e9-9e05-f1ee89171446.png)

**Comment by mariem-abid** [comment] 2019-07-15 13:29
Hi @Himanshu-bishtt,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by mariem-abid** [comment] 2019-08-15 07:36
Hi @Himanshu-bishtt,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by mariem-abid** 2019-08-15 07:36 UTC
Labels: Bug, BO, Order settings, No change required
