### ISSUE TITLE
Product images are missing if enable www.

### ISSUE THREAD

**Issue by ets-soft** [PrestaShop/PrestaShop#18492] opened 2020-04-07 11:19 UTC
#### Describe the bug

all product images are missing if you enable www to your shop domain in shop url configuration

#### Expected behavior

All product images should display on the FO when www is added to shop domain url

#### Steps to Reproduce

add "www." to your shop domain configuration then reload FO, all product images are missing.

#### Additional information

* PrestaShop version: 1.7
* PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2020-04-07 11:25
Hi @ets-soft,

could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks!

**Comment by ets-soft** [comment] 2020-04-08 01:17
hi @khouloudbelguith 
I know the problem is in .htaccess file, the htaccess generating function generated image rewrite rules for both www and non-www domain, it should only generate the image rewrite rules for www domain only. To fix this manually we just need to delete the rewrite rules for non-www domain.
But if somehow merchant regenerate the .htaccess file the problem will happen again so it should be fixed in Prestashop image generating function

Thanks

**Comment by marionf** [comment] 2020-04-10 10:06
> But if somehow merchant regenerate the .htaccess file the problem will happen again so it should be fixed in Prestashop image generating function

@PrestaShop/prestashop-core-developers wdyt about this suggestion ?

**Comment by ets-soft** [comment] 2020-04-10 10:30
hi @khouloudbelguith 
so we just need to fix the image missing issue when www is enabled.
regards,

**Comment by PierreRambaud** [comment] 2020-11-25 09:51
Hi everyone, 
After several tries, I'm not able to reproduce, if I change the domain and use www, I'm still able to see images.

**Comment by ets-soft** [comment] 2020-11-25 10:21
hi @PierreRambaud I think the issue may has been fixed in later versions.

**Comment by PierreRambaud** [comment] 2020-11-25 10:31
So I'm closing the issue :)  Thanks @ets-soft

**Closed as completed by PierreRambaud** 2020-11-25 10:31 UTC
Labels: Bug, BO, Image, Fixed
