### ISSUE TITLE
Back Office issue with duplicate delivery Addresses on the order page

### ISSUE THREAD

**Issue by Frankie-IT** [PrestaShop/PrestaShop#19626] opened 2020-06-08 12:25 UTC
#### Describe the bug

In the Back Office on the customer order page when I change the shipping address, this is always duplicated.

Then if I add a customer note in (OTHER), it is duplicated in the order screen.

#### Expected behavior

I wish there is not a duplicate of the shipping address with each modification of the same.

#### Steps to Reproduce

1. Go to the order page in the Back Office.
2. Click EDIT in the (Delivery addresses) section (photo 1).
3. Make a change and click SAVE.
4. After the modification PS creates a duplicate of the same delivery address (photo 2).
5. If you add customer notes in OTHER, it is duplicated on the screen (photo 3)

**Screenshots**

Button used for editing:
<a href='https://postimg.cc/CRg9qKpK' target='_blank'><img src='https://i.postimg.cc/rw0T7dh5/s1.jpg' border='0' alt='s1'/></a>

Duplicate delivery addresses after each change:
<a href='https://postimg.cc/RJc1w4w7' target='_blank'><img src='https://i.postimg.cc/nrWdbLzP/s2.jpg' border='0' alt='s2'/></a>

Customer notes with dual display on the screen:
<a href='https://postimg.cc/ZCxFRYbZ' target='_blank'><img src='https://i.postimg.cc/4Nr8WnjK/s3.jpg' border='0' alt='s3'/></a>

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

**Comment by florine2623** [comment] 2020-06-08 16:14
Hi @Frankie-IT ,
I'm using PS 1.7.6.5 and couldn't reproduce your issue. Please check my screen record here : https://drive.google.com/file/d/1eX9zU3DvZpp-CdZiw7QIf52TtkkP4DYg/view
I stopped at step 3.

Do you use any module that has an override on that page ?
Please check and let me know!

**Comment by Frankie-IT** [comment] 2020-06-09 07:35
Hi @florine2623 ,
the modules currently connected to the PS order page are Paypal and Gest Pay for payments.

Two months ago I uninstalled a module called Packlink Shipping that automatically managed the status of orders via API, that is, it changed the status automatically from Shipped, In transit and Delivered. Unfortunately I uninstalled it because it didn't work perfectly.

So I currently use the native PS function.

What could I check as a script or in the database if everything is ok? all suggestions are accepted.

Thx!

**Comment by Frankie-IT** [comment] 2020-06-09 13:52
Hi @florine2623 ,
I found here in assistance another problem identical to mine of 6 January 2019 that seems not to be solved yet because it is still open https://github.com/PrestaShop/PrestaShop/issues/12170

**Comment by florine2623** [comment] 2020-06-12 09:04
Thanks @Frankie-IT ,
Indeed that issue is already in our debug roadmap. It has the **To Do** tag.
You can keep an eye on that issue.

I'll close yours as it is a duplicate.
Thanks!

**Comment by florine2623** [comment] 2020-06-12 09:04
Duplicate of #12170

**Closed as completed by florine2623** 2020-06-12 09:04 UTC
Labels: BO, Duplicate, Order, 1.7.6.5
