### ISSUE TITLE
Customer Reassurance module v5 crashes when used as widget with PS 1.7.6

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [PrestaShop/PrestaShop#20254] opened 2020-07-20 16:26 UTC
Checkout links not active due module Customer Reassurance issue.

Bug mode shows error:
Atempted to call an undefined method named "getMimeType" of class "ImageManager".
Did you mean to call "getMimeTypeByExtension"?
in ReassuranceActivity.php line 190

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by matks** [comment] 2020-07-20 16:35
Similar to https://github.com/PrestaShop/blockreassurance/pull/35#issuecomment-566556584 feedback

**Comment by matks** [comment] 2020-07-20 16:35
It seems `ImageManager::getMimeType()` is only inside the Core since PS 1.7.7 https://github.com/PrestaShop/PrestaShop/commit/c18d5f7fe78fc63e107a9be96316c011e081d6b6

**Comment by matks** [comment] 2020-07-20 16:40
@Laimonas-Mituzas it seems compatibility range on the module is wrong. v5.0.0 is only compatible with PS 1.7.7 and higher. The module should have been configured accordingly (but it's not there)

=> see https://github.com/PrestaShop/blockreassurance/pull/47#issuecomment-647456624

**Comment by matks** [comment] 2020-07-20 16:43
PR to fix https://github.com/PrestaShop/blockreassurance/pull/54

**Comment by matks** [comment] 2020-07-21 08:15
We might find another work-around to keep a compatibility range as wide as possible.

@Laimonas-Mituzas how did you observe the error ? When I use the module "in a standard way" I do not use its widget capabilities so the error does not appear. Do you use a custom theme where blockreassurance is a widget ?

**Comment by Laimonas-Mituzas** [comment] 2020-07-24 12:20
Yes, custom heme and blockreassurance is a widget.

**Comment by matks** [comment] 2020-07-30 16:35
I have built a reproductible how-to for QA here https://github.com/PrestaShop/blockreassurance/pull/55#issuecomment-666510451 so PR can be tested

**Comment by jonasburneika** [comment] 2020-08-19 09:46
Hello, @Matks @Laimonas-Mituzas here is my PR: https://github.com/PrestaShop/blockreassurance/pull/56 for backward compatibility. I needed this solution for my PS1.7.6.2 client.

**Comment by golenkova-ferrero** [comment] 2020-08-20 18:30
Hello! Does anyone have a solution for Prestashop 1.7.6.1? I had to switch the reassurance module off, because after an update it broke, half of the product page simply disappeared... Many thanks from Barcelona!

**Comment by matks** [comment] 2020-08-21 07:29
@golenkova-ferrero 2 pull requests with bug fixes have been submitted
- https://github.com/PrestaShop/blockreassurance/pull/56
- https://github.com/PrestaShop/blockreassurance/pull/55
They have not been validated yet though

**Comment by Progi1984** [comment] 2020-11-05 10:46
Fixed in PrestaShop/blockreassurance#55

Available in next release

**Closed as completed by Progi1984** 2020-11-05 10:46 UTC
Labels: Bug, Minor, Blockreassurance, PR available
