### ISSUE TITLE
[PSCSX-8239] Search index problem when a product is deleted

### ISSUE THREAD

**Issue by Casper-O** [PrestaShop/PrestaShop#10530] opened 2018-09-20 08:27 UTC
**Describe the bug**
When deleting one product, all products with similar names, have been deleted from the search index, even if, going to Prefences -> Search, all products seem to be correctly indexed, but on the front end if I search for a product with a similar names of that deleted product, no records has been found.

Re-building the entire search index fix the issue and all product are available for search again.

**To Reproduce**

Procuct 1 Name : Test product 1
Procuct 2 Name : Test product 2

Going on the frontend and searchig for "test" key, 2 records have been found

I delete Test Product 1

Going on the frontend and searchig for "test" key, no records have been found

Rebuilding the index and searching again for "test" , it display the product "test Product 2"

**Additionnal information**
PrestaShop version: 1.6 and 1.7

**Solution**
https://github.com/PrestaShop/PrestaShop/pull/8587 Suggested on **5 Dec 2017** for prestashop 1.6

**Comment by khouloudbelguith** [comment] 2018-09-20 08:59
Hi @Casper-O,

Thanks for your report.
I manage to reproduce the issue with PS1.6.1.20 & PS 1.7.4.2.
We will see how to fix it.
When you delete a product from the catalog (Catalog Products - Delete) all words indexed to this product are removed from the global index.

Best regards, Khouloud

**Comment by Casper-O** [comment] 2018-09-20 09:10
Hi @khouloudbelguith 

Solution has been around since december 2017 when I first found and solved the issue... please check PR #8587

**Comment by khouloudbelguith** [comment] 2018-09-20 12:46
fix solution for 1.7: #10536

**Comment by Casper-O** [comment] 2018-09-23 06:40
@khouloudbelguith you forgot to add the 1.6.1.20 label also....

**Comment by Casper-O** [comment] 2018-10-04 07:50
I do not see this as a "standard" bug - its a critical bug that destroys the FO search function, when a product is deleted.

Please reconsider this and make sure something happens regarding the PR for 1.6.1.X else i'm just going to close it and the issue report...

**Comment by Casper-O** [comment] 2018-10-04 09:26
@PierreRambaud Open it Again  it has not ben solved for 1.6.1.X where this issue is related to...

**Comment by PierreRambaud** [comment] 2018-10-04 09:37
Woot, it was closed automatically when I merged the pull request :)

**Comment by marionf** [comment] 2018-10-04 09:43
@Casper-O 
This one is for 1.7, for 1.6 it's http://forge.prestashop.com/browse/PSCSX-8239
So, this one can be closed

**Closed as completed by marionf** 2018-10-04 09:43 UTC
Labels: Bug, Search, Fixed, 1.7.4.2

**Comment by Casper-O** [comment] 2018-10-04 10:14
@marionf i made this one for 1.6.1.X not for 1.7.X

Solution PR is into PrestaShop:1.6.1.x - check https://github.com/PrestaShop/PrestaShop/pull/8587

Open it agian

**Comment by marionf** [comment] 2018-10-04 10:27
There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-8239
It wasn't necessary to create a new one.
This one is associated with 1.7 project and pull request.

**Comment by Casper-O** [comment] 2018-10-04 10:35
@marionf clearly Forge is closing, really... the Forge report was open for 10 months, tell me one more time it was not necessary to create a new Issue report to get your attentions..

Now open the issue report again or i make a new one - also Forge already had one for 1.7 also.. http://forge.prestashop.com/browse/BOOM-3965

**Comment by marionf** [comment] 2018-10-04 12:01
No, I will not reopen this one because as explained before it's for 1.7
Issue and fix already exists for 1.6
So, you can open a new issue, it will be closed for duplicate.

**Comment by Casper-O** [comment] 2018-10-04 12:13
Fine i wil close all my PR, im done with this....
