### ISSUE TITLE
ProductAssembler class assigns wrong product attributes in multistore website (from another shop) - have a solution

### ISSUE THREAD

**Issue by gwyneblaidd** [PrestaShop/PrestaShop#17573] opened 2020-02-08 19:47 UTC
Hi guys!

I have faced a problem with some module (not really important which - it utilizes PS function) when a shop in a multistore missed showing prices for some products (multistore website). Quick debug showed it's connected with the wrong product_attribute that belongs to the product from another shop (the same product, but another shop). The product is shared among shops but each shop has its combinations. I have found that problems occur in ProductAssemblerCore::addMissingProductFields() function. This function is not adapted for getting product attributes in connection to the store.

check this code from original PS file classes/ProductAssembler.php

```
private function addMissingProductFields(array $rawProduct)
    {
        $idShop = (int) $this->searchContext->getIdShop();
        $idLang = (int) $this->searchContext->getIdLang();
        $idProduct = (int) $rawProduct['id_product'];
        $prefix = _DB_PREFIX_;

        $nbDaysNewProduct = (int) Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
        if (!Validate::isUnsignedInt($nbDaysNewProduct)) {
            $nbDaysNewProduct = 20;
        }

        $now = date('Y-m-d').' 00:00:00';

         $sql = "SELECT
                    p.*,
                    pl.*,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_lang pl
                    ON pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa
	            ON sa.id_product = p.id_product 
		    AND sa.id_shop = $idShop
		WHERE p.id_product = $idProduct";

        $rows = Db::getInstance()->executeS($sql);
        if ($rows === false) {
            return $rawProduct;
        }

        return array_merge($rows[0], $rawProduct);
    }
```

You can see. that function returns columns from the product table, that have no association with a shop (like product_shop). This has a great problem with some essential data stored there. For example, _cache_default_attribute_ from the product table. _cache_default_attribute_ is different for each shop and proper value is stored in product_shop. So, if the script picks up this cache_default_attribute (like in my case) this _cache_default_attribute_ is taken randomly from the product table (it depends on which shop product was added at first so it keeps value connected to that store). If this product was added to shop1 (for example) at first it will contain product_attribute for this shop. If we add this product to another shop2 product table will not be changed (it will be saved in product_shop table). So, running ProductAssemblerCore::addMissingProductFields()  function in shop1 will return proper combination from (_cache_default_attribute_ ), but wrong for another shop2 (this combination still will be from shop1). If those combinations are not shared between shops PS will not return any associated with combination data (because this is restricted data from another shop). In my case, I am getting 0 prices in this case (my all prices depends on combinations).

I have a solution in my case for a problematic sql query. It is to join table product_shop that will give product data per shop, so it can fix many other parts in the PS core that uses that function. Check this changed code:|

```
$sql = "SELECT
                    p.*,
                    pl.*,
                    ps.cache_default_attribute,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_shop ps
                    ON ps.id_product = p.id_product
                    AND ps.id_shop = $idShop
                LEFT JOIN {$prefix}product_lang pl
                    ON pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa
			        ON sa.id_product = p.id_product 
			        AND sa.id_shop = $idShop
			    WHERE p.id_product = $idProduct";
```

In that modified code I am extracting additionally only one field **_ps.cache_default_attribute_** from shop associated table product_shop. But I think we can replace all fields from the product table and use product_shop instead, so it can be like **_ps.*_**.

**Comment by khouloudbelguith** [comment] 2020-02-10 10:06
Hi @gwyneblaidd,

Thanks for your report.
I think the issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/9664.
Is it?

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-02-10 10:09
Could be related to this: https://github.com/PrestaShop/PrestaShop/issues/9686

**Comment by gwyneblaidd** [comment] 2020-02-10 12:00
hi @khouloudbelguith!

I am not sure its similar to #9664, in my case it's rather taken wrong product shop-dependent data, but it can be linked to this via the wrong cache_attribute that is in that table, so script can take wrong default combination (from another store) and user can get an error cause we can't to have 2 default combinations per store. And every time it could try to set default combination only from one store. But its in case if product/attributes are determined from cache_attrib stored in product_table. We can fix this and check if that will fix #9664.

**Comment by khouloudbelguith** [comment] 2020-02-10 14:45
@gwyneblaidd, so can you confirm steps to reproduce the issue:
1. Enable Multistore context
2. Create a second shop
3. Create a product P1 in all shops
4. Create some combinations for P1 in the first shop
5. Create other combinations for P1 in the second shop

The problem occurs in this case because in ProductAssemblerCore::addMissingProductFields() function is not adapted for getting product attributes in connection to the store.

Is it?

Thanks!

**Comment by gwyneblaidd** [comment] 2020-02-10 18:22
@khouloudbelguith, I don't have some specific steps on how you can reproduce this problem. This problem I detected under developing some custom module (I am a developer) and faced the problem when ProductAssembler returns data for some product from another shop, so I was debugging why it happens. If you revise code I sent you will see that ProductAssembler gets lang product data and stock per shop, but the data for a product it takes from general product table with no association to shop. This is a bottleneck that can cause ambiguous issues in any part of the following code executed. 

If you want to check it in code.

Do in the backend:
1.Enable Multistore context
2.Create a second shop
3.Create a product P1 in the first shop
4.Create some combinations for P1 in the first shop
5.Create other combinations for P1 in the second shop
6. Put some additional price per each combination (different for each shop so it will be easier to check)


Then in code try to use this product_id in Product presenter :

```
$presenter = new ProductListingPresenter(
                new ImageRetriever(
                    $this->context->link
                ),
                $this->context->link,
                new PriceFormatter(),
                new ProductColorsRetriever(),
                $this->context->getTranslator()
            );

$presentationSettings = $presenterFactory->getPresentationSettings();
            $presenter = new ProductListingPresenter(
                new ImageRetriever(
                    $this->context->link
                ),
                $this->context->link,
                new PriceFormatter(),
                new ProductColorsRetriever(),
                $this->context->getTranslator()
            );


$productForTemplate = $presenter->present(
                        $presentationSettings,
                        $assembler->assembleProduct(array('id_product' => PRODUCT_ID_HERE_OF_THAT_CREATED_PRODUCT)),
                        $this->context->language
                    );

```
If you set shop1 or shop2 (ids) in a context before that code with presenter and assembler you will get the same product_data for a template with no association to shop. Also in this situation, you will get the wrong price  (it will be the same for each shop and it should be per shop  because we set a different price for combinations per shop) cause cache_product_attribute from a wrong shop and it will not get a correct price from product_attribute stored in the product table that is shared between shops.

Sorry if I do this is in no clear way, but just a look at that function gives an imagination it should retrieve data per shop, but instead, sql gets data from product tables that will break logic in multistore.

**Comment by khouloudbelguith** [comment] 2020-02-11 10:56
@gwyneblaidd, At the step5 => we have an exception as reported here: https://github.com/PrestaShop/PrestaShop/issues/9664
I added this code
```
$presenter = new ProductListingPresenter(
                    new ImageRetriever(
                        $this->context->link
                    ),
                    $this->context->link,
                    new PriceFormatter(),
                    new ProductColorsRetriever(),
                    $this->context->getTranslator()
                );
            $productForTemplate = $presenter->present(
                $presentationSettings,
                $assembler->assembleProduct(array('id_product' => PRODUCT_ID_HERE_OF_THAT_CREATED_PRODUCT)),
                $this->context->language
            );
```
after this line: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.3/controllers/front/ProductController.php#L315

In the FO, in the product details page, I have this exception
![image](https://user-images.githubusercontent.com/16067358/74230854-87de9100-4cc5-11ea-97fc-1425a959105a.png)

Thanks to check & feedback.

**Comment by gwyneblaidd** [comment] 2020-02-11 11:36
@khouloudbelguith 

instead of this - PRODUCT_ID_HERE_OF_THAT_CREATED_PRODUCT in the code put the real product id, you have created in the prev steps. 
 it should be smth like:

`$assembler->assembleProduct(array('id_product' => 123)),`

if the product you have created has id 123.


About exception it could be, I didn't have an exception as I created product attributes with a script, directly putting records in db. I have created a product in 2 shops programmatically so I have passed through step 5 with no exception. Still, I have an issue when trying to save the product in shops via backend (but no problem when with my custom script) - PS backend removes default tick from default attribute for 1 shop (so the shop has no default combination upon save). This save issue can indeed be part of issue #9664. I am trying to dig it up, so will tell if that will fix my issue and probably #9664. The original Issue i have posted here with assembler still not related to #9664. Assembler refers to product representation for a template rather than save to db. WIll post you if I will find smth on #9664.


Use this piece of code

create 1product for 2 shops not via backend but with excelimporter for example to overcome possible exceptions (if you have any).

in $order_products var put product_id, currently, i have put id 123, you need to change to what you have.

```
           $order_products = [123];
           $showPrice = true;

            $assembler = new ProductAssembler($this->context);

            $presenterFactory = new ProductPresenterFactory($this->context);
            $presentationSettings = $presenterFactory->getPresentationSettings();
            $presenter = new ProductListingPresenter(
                new ImageRetriever(
                    $this->context->link
                ),
                $this->context->link,
                new PriceFormatter(),
                new ProductColorsRetriever(),
                $this->context->getTranslator()
            );

            $productsForTemplate = array();

            $presentationSettings->showPrices = $showPrice;

            if (is_array($order_products)) {
                foreach ($order_products as $productId) {
                    $productsForTemplate[] = $presenter->present(
                        $presentationSettings,
                        $assembler->assembleProduct(array('id_product' => $productId['product_id'])),
                        $this->context->language
                    );
                }
            }

print_r($productsForTemplate);
```

**Comment by khouloudbelguith** [comment] 2020-02-11 16:06
@gwyneblaidd, after adding this code, I have a new exception in the FO
![image](https://user-images.githubusercontent.com/16067358/74254385-adcd5b00-4cf0-11ea-9571-51f4a3250857.png)

Thanks to check & feedback.

**Comment by gwyneblaidd** [comment] 2020-02-11 21:55
@khouloudbelguith 
what you are passing into  $order_products, it should contain product id. And from your exception message, it's empty or null.

**Comment by khouloudbelguith** [comment] 2020-02-12 11:50
@gwyneblaidd, I attached a screen record
https://drive.google.com/file/d/1d9x9lOkCiQFWwP9mK0koVUkCf417wlaJ/view

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-03-16 08:12
Hi @gwyneblaidd,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-16 08:12 UTC
Labels: Bug, Multistore, Combinations, No change required
