### ISSUE TITLE
PS 1.7.6.3 - special chars like "&" not correct displayed in email from [shop_name]

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17364] opened 2020-01-27 01:31 UTC
Hi, 

my shop name is like "Online & Shop" and if any mail is send the email header is shown as:

[Online &amp; Shop] Welcome! 

The "&" is not correct displayed. The output is 
![image](https://user-images.githubusercontent.com/44971218/73165201-a81e2580-40f3-11ea-9df8-3e14a4284dc2.png)

Shopname is correct displayed in FO and correct written in BO. And also correct in database. Only Email from header is not correct. 

Thanks for checking and answer ;-)

**Comment by khouloudbelguith** [comment] 2020-01-27 10:11
Hi @didi-2018,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/16847
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-27 10:11
Duplicate of #16847

**Closed as completed by khouloudbelguith** 2020-01-27 10:11 UTC
Labels: Duplicate

**Comment by didi-2018** [comment] 2020-01-27 10:32
@khouloudbelguith  
I used this fix: 
https://github.com/PrestaShop/PrestaShop/pull/17073/files/1ccb2d9d46a82648f74a352ae509ff548e16753b
and it works fine my case ;-)
