### ISSUE TITLE
When inserting a product to prestashop from web services it does not return id of the new product.

### ISSUE THREAD

**Issue by QueeNFrisk** [PrestaShop/PrestaShop#28410] opened 2022-05-03 21:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Inserting 7 products that do return an id, the 8th does not return an id, but still in the back office it shows the inserted product with the corresponding id but in the web services response it does not show it.

I show you my code:

```PHP
     $ws = new PrestaShopWebservice('https://www.shop.com', 'api_key', true);
      $bx = $ws->get(['url' => 'https://www.shop.com/api/products?schema=blank']);
      $cf = $bx->product->children();
      $cf->id_manufacturer = $productInfo['brand'];
      $cf->new = $productInfo['isNew'];
      $cf->state = $productInfo['state'];
      $cf->id_category_default = $productInfo['idCategory'];
      $cf->active = $productInfo['active'];
      $cf->advanced_stock_management = $productInfo['stockManagment'];
      $cf->reference = $productInfo['reference'];
      $cf->name = $productInfo['name'];
      $cf->price = $productInfo['price'];
      $cf->id_shop_default = 1;
      $cf->low_stock_alert = 1;
      $cf->show_price = $productInfo['showPrice'];
      $cf->minimal_quantity = 1;
      $cf->available_for_order = 1;
      $cf->supplier_reference = $productInfo['supplierReference'];
      $cf->ean13 = $productInfo['ean'];
      $cf->upc = $productInfo['upc'];
      $cf->is_virtual = 0;
      $cf->on_sale = 0;
      $cf->online_only = 1;
      $cf->wholesale_price = $productInfo['wholesalePrice'];
      $cf->uploadable_files = 0;
      $cf->show_condition = 0;
      $cf->show_price = $productInfo['showPrice'];
      $cf->indexed = $productInfo['indexed'];
      $cf->visibility = 'both';
      $cf->meta_description = $productInfo['metaDescription'];
      $cf->meta_keywords = $productInfo['metaKeywords'];
      $cf->meta_title = $productInfo['metaTitle'];
      $cf->description = $productInfo['description'];
      $cf->description_short = $productInfo['shortDescription'];

      unset($cf->position_in_category);
      unset($cf->associations->categories->category->id);
      unset($cf->link_rewrite);

      $cx = $ws->add([
        'resource' => 'products',
        'postXml' => $bx->asXML(),
        'output_format' => 'JSON'
      ]);
      $ncpf = $cx->product->children();
      var_dump($ncpf);
      return $ncpf->id;
```

And here is my response:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
   <product>
      <id />
      <id_manufacturer>2</id_manufacturer>
      <id_supplier />
      <id_category_default>2</id_category_default>
      <new>1</new>
      <cache_default_attribute />
      <id_default_image />
      <id_default_combination />
      <id_tax_rules_group />
      <type />
      <id_shop_default>1</id_shop_default>
      <reference>425-019-C</reference>
      <supplier_reference>11829</supplier_reference>
      <location />
      <width />
      <height />
      <depth />
      <weight />
      <quantity_discount />
      <ean13>7506240622680</ean13>
      <isbn />
      <upc />
      <mpn />
      <cache_is_pack />
      <cache_has_attachments />
      <is_virtual>0</is_virtual>
      <state>1</state>
      <additional_delivery_times />
      <delivery_in_stock>
         <language id="1" />
      </delivery_in_stock>
      <delivery_out_stock>
         <language id="1" />
      </delivery_out_stock>
      <product_type />
      <on_sale>0</on_sale>
      <online_only>1</online_only>
      <ecotax />
      <minimal_quantity>1</minimal_quantity>
      <low_stock_threshold />
      <low_stock_alert>1</low_stock_alert>
      <price>249</price>
      <wholesale_price>215</wholesale_price>
      <unity />
      <unit_price_ratio />
      <additional_shipping_cost />
      <customizable />
      <text_fields />
      <uploadable_files>0</uploadable_files>
      <active>1</active>
      <redirect_type />
      <id_type_redirected />
      <available_for_order>1</available_for_order>
      <available_date />
      <show_condition>0</show_condition>
      <condition />
      <show_price>1</show_price>
      <indexed>1</indexed>
      <visibility>both</visibility>
      <advanced_stock_management>1</advanced_stock_management>
      <date_add />
      <date_upd />
      <pack_stock_type />
      <meta_description>Cámara de presión con O ring completo para fumigadora 425</meta_description>
      <meta_keywords>refaccion para fumigador, repuesto de fumigador, para fumigador, reparar fumigador, arreglar fumigador, reparacion de fumigador, fumigador truper, fumigador fm-425 , fumigador , refacciones para fumigador , atomizador , jardineria</meta_keywords>
      <meta_title>Cámara de presión con O ring completo para fumigadora 425</meta_title>
      <name>Cámara de presión con O ring completo para fumigadora 425</name>
      <description>Cámara de presión con O ring completo para fumigadora 425</description>
      <description_short>&lt;p&gt;&lt;b&gt;-Cámara de presión fabricada en polipropileno&lt;br /&gt;-Refacción para fumigador FM-425 marca Truper®&lt;/p&gt;&lt;/b&gt;</description_short>
      <available_now>
         <language id="1" />
      </available_now>
      <available_later>
         <language id="1" />
      </available_later>
      <associations>
         <categories>
            <category />
         </categories>
         <images>
            <image>
               <id />
            </image>
         </images>
         <combinations>
            <combination>
               <id />
            </combination>
         </combinations>
         <product_option_values>
            <product_option_value>
               <id />
            </product_option_value>
         </product_option_values>
         <product_features>
            <product_feature>
               <id />
               <id_feature_value />
            </product_feature>
         </product_features>
         <tags>
            <tag>
               <id />
            </tag>
         </tags>
         <stock_availables>
            <stock_available>
               <id />
               <id_product_attribute />
            </stock_available>
         </stock_availables>
         <attachments>
            <attachment>
               <id />
            </attachment>
         </attachments>
         <accessories>
            <product>
               <id />
            </product>
         </accessories>
         <product_bundle>
            <product>
               <id />
               <id_product_attribute />
               <quantity />
            </product>
         </product_bundle>
      </associations>
   </product>
</prestashop>
```
```TEXT

HTTP RESPONSE HEADER
GET /api/products?schema=blank HTTP/2
Host: www.shop.com
authorization: Basic API_KEY
accept: */*

HTTP/2 201
date: Tue, 03 May 2022 20:47:23 GMT
content-type: text/xml;charset=utf-8
access-time: 1651610843
x-powered-by: PrestaShop Webservice
psws-version: 1.7.8.5
execution-time: 0.172
content-sha1: c5fc16446b81d09d2d42da1478f49c94fdca27df
vary: Accept-Encoding
host-header: c2hhcmVkLmJsdWVob3N0LmNvbQ==
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 705bd9f70cb9523b-MEXXML SENT
```
```XML
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
   <product>
      <id><![CDATA[16]]></id>
      <id_manufacturer xlink:href="https://www.shop.com/api/manufacturers/2"><![CDATA[2]]></id_manufacturer>
      <id_supplier />
      <id_category_default xlink:href="https://www.shop.com/api/categories/2"><![CDATA[2]]></id_category_default>
      <new><![CDATA[1]]></new>
      <cache_default_attribute><![CDATA[0]]></cache_default_attribute>
      <id_default_image notFilterable="true" />
      <id_default_combination notFilterable="true"><![CDATA[0]]></id_default_combination>
      <id_tax_rules_group />
      <position_in_category notFilterable="true" />
      <manufacturer_name notFilterable="true"><![CDATA[Truper]]></manufacturer_name>
      <quantity notFilterable="true" />
      <type notFilterable="true"><![CDATA[simple]]></type>
      <id_shop_default><![CDATA[1]]></id_shop_default>
      <reference><![CDATA[425-019-C]]></reference>
      <supplier_reference><![CDATA[11829]]></supplier_reference>
      <location />
      <width />
      <height />
      <depth />
      <weight />
      <quantity_discount />
      <ean13><![CDATA[7506240622680]]></ean13>
      <isbn />
      <upc />
      <mpn />
      <cache_is_pack />
      <cache_has_attachments />
      <is_virtual><![CDATA[0]]></is_virtual>
      <state><![CDATA[1]]></state>
      <additional_delivery_times />
      <delivery_in_stock>
         <language id="1" xlink:href="https://www.shop.com/api/languages/1" />
      </delivery_in_stock>
      <delivery_out_stock>
         <language id="1" xlink:href="https://www.shop.com/api/languages/1" />
      </delivery_out_stock>
      <product_type />
      <on_sale><![CDATA[0]]></on_sale>
      <online_only><![CDATA[1]]></online_only>
      <ecotax />
      <minimal_quantity><![CDATA[1]]></minimal_quantity>
      <low_stock_threshold />
      <low_stock_alert><![CDATA[1]]></low_stock_alert>
      <price><![CDATA[249]]></price>
      <wholesale_price><![CDATA[215]]></wholesale_price>
      <unity />
      <unit_price_ratio />
      <additional_shipping_cost />
      <customizable />
      <text_fields />
      <uploadable_files><![CDATA[0]]></uploadable_files>
      <active><![CDATA[1]]></active>
      <redirect_type />
      <id_type_redirected />
      <available_for_order><![CDATA[1]]></available_for_order>
      <available_date />
      <show_condition><![CDATA[0]]></show_condition>
      <condition><![CDATA[new]]></condition>
      <show_price><![CDATA[1]]></show_price>
      <indexed><![CDATA[1]]></indexed>
      <visibility><![CDATA[both]]></visibility>
      <advanced_stock_management><![CDATA[1]]></advanced_stock_management>
      <date_add><![CDATA[2022-05-03 15:47:22]]></date_add>
      <date_upd><![CDATA[2022-05-03 15:47:22]]></date_upd>
      <pack_stock_type />
      <meta_description>
         <language id="1" />
      </meta_description>
      <meta_keywords>
         <language id="1"><![CDATA[e]]></language>
      </meta_keywords>
      <meta_title>
         <language id="1" />
      </meta_title>
      <link_rewrite>
         <language id="1" xlink:href="https://www.shop.com/api/languages/1" />
      </link_rewrite>
      <name>
         <language id="1" />
      </name>
      <description>
         <language id="1" />
      </description>
      <description_short>
         <language id="1"><![CDATA[p]]></language>
      </description_short>
      <available_now>
         <language id="1" xlink:href="https://www.shop.com/api/languages/1" />
      </available_now>
      <available_later>
         <language id="1" xlink:href="https://www.shop.com/api/languages/1" />
      </available_later>
      <associations>
         <categories nodeType="category" api="categories" />
         <images nodeType="image" api="images" />
         <combinations nodeType="combination" api="combinations" />
         <product_option_values nodeType="product_option_value" api="product_option_values" />
         <product_features nodeType="product_feature" api="product_features">
            <product_feature xlink:href="https://www.shop.com/api/product_features/0">
               <id><![CDATA[0]]></id>
               <id_feature_value xlink:href="https://www.shop.com/api/product_feature_values/0"><![CDATA[0]]></id_feature_value>
            </product_feature>
         </product_features>
         <tags nodeType="tag" api="tags">
            <tag xlink:href="https://www.shop.com/api/tags/0">
               <id><![CDATA[0]]></id>
            </tag>
         </tags>
         <stock_availables nodeType="stock_available" api="stock_availables">
            <stock_available xlink:href="https://www.shop.com/api/stock_availables/34">
               <id><![CDATA[34]]></id>
               <id_product_attribute><![CDATA[0]]></id_product_attribute>
            </stock_available>
         </stock_availables>
         <attachments nodeType="attachment" api="attachments" />
         <accessories nodeType="product" api="products" />
         <product_bundle nodeType="product" api="products" />
      </associations>
   </product>
</prestashop>
```

### Expected behavior

Insert the product from the web services and return the corresponding product id.

### Steps to reproduce

1.- install prestashop
2.- enable webservices
3.- try to insert product with my code
4.- see response

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.28

**Comment by hibatallahAouadni** [comment] 2022-05-04 14:51
Hello @QueeNFrisk 

I think it's related to the same issue that you already reported here #28409
Closing this one as a duplicate :wink: try to fix your code, then you will not encounter these issues :relaxed: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-05-04 14:51
Duplicate of #28409

**Closed as completed by hibatallahAouadni** 2022-05-04 14:51 UTC
Labels: Bug, Duplicate, Invalid

**Comment by QueeNFrisk** [comment] 2022-05-05 22:58
Hola @hibatallahAouadni I appreciate you taking the time to check my tickets. Although it is the same code, it is not the same error. This error is that when I am inserting the products in a sequence of say, 100 products, the 8th one onwards does not return any id, the more it has been inserted, I mean; I can see it in the back office with its corresponding id which was not returned in the code, it returns null. 

(
```PHP
$ncpf = $cx->product->children();
var_dump($ncpf);
return $ncpf->id;
```
)
