### ISSUE TITLE
ps_categoryproducts installation fails

### ISSUE THREAD

**Issue by ACPKOR** [PrestaShop/PrestaShop#30254] opened 2022-11-09 15:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

we have the problem that I attach when installing the ps_categoryproducts module in prestashop 1.7.8.1
Does not install.
Capture attached.

can you help me?

Thank you,

![modulo](https://user-images.githubusercontent.com/117843410/200872939-6a94ed7d-6edf-4936-bc01-a3668f81b859.jpg)

### Steps to reproduce

install the module

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

ps_categoryproducts

**Comment by HanaRebaiQA** [comment] 2022-11-09 16:16
Hello @ACPKOR 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Also, i was unable to reproduce your issue using the `ps_categoryproducts module v1.0.4 `in PS1787.

https://user-images.githubusercontent.com/92912932/200883041-e65c13d6-38b0-47b0-8346-b248f94b524b.mp4


So, i'll close this issue.

Thank You!

**Closed as completed by HanaRebaiQA** 2022-11-09 16:16 UTC
Labels: Bug, Invalid
