### ISSUE TITLE
Customer can continue to checkout, if there are multiple unavailable products

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#24318] opened 2021-05-03 14:07 UTC
#### Steps to Reproduce

1. Create two products, set quantity to 5 to both of them, disable ordering of out of stock products for both of them.
2. Add 5 pieces of both of them to cart. Go to cart.
3. Go to BO, reduce stock of both of them to 1.
4. Go back to FO cart, refresh page.
5. Click minus sign on the first product, until you get to 1.

See error - **Error message disappears and you can continue to checkout.**

**Video**
https://drive.google.com/file/d/12QqB5k6eHmGIxJJX0zRqbaLWfhbEC8f9/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2
* Theme: https://github.com/prestarocket-agence/classic-rocket

**Comment by hibatallahAouadni** [comment] 2021-05-04 01:02
Hello @Hlavtox 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #18958. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-04 01:02
Duplicate of #18958

**Closed as completed by hibatallahAouadni** 2021-05-04 01:02 UTC
Labels: Duplicate
