### ISSUE TITLE
Install page - The definition of installing PrestaShop is always displayed in English

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#18715] opened 2020-04-20 11:19 UTC
#### Describe the bug

In the install page, the first step "Choose your language", the definition of installing PrestaShop is always displayed in English.
![image](https://user-images.githubusercontent.com/16067358/79745525-c8333e80-8308-11ea-9116-9ba27286ad29.png)

It is ok in the 1.7.7.x branch
#### Expected behavior

It should be displayed in the language selected

#### Steps to Reproduce

1. Git clone https://github.com/PrestaShop/PrestaShop.git
2. composer install
3. Try to install the develop branch
4. change the language
5. see the error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-04-20 11:20
Ping @LouiseBonnard

**Comment by LouiseBonnard** [comment] 2020-04-20 11:28
Hi @khouloudbelguith, in the 1.7.7 catalog on Crowdin I have [this string](https://crowdin.com/translate/prestashop-official/35718/en-ar#5824362) where the source text mentions 250,000 and the translation, to stay up-to-date, 300,000. But I don't know why it is not translated on the develop branch. :-(

**Comment by khouloudbelguith** [comment] 2020-04-20 14:36
Hi @LouiseBonnard,

In all languages, this description is displayed in English.

Thanks!

**Comment by sam-pires** [comment] 2020-05-20 09:36
@LouiseBonnard to be reproduced again, since 1.7.7 beta release it should work

**Comment by LouiseBonnard** [comment] 2020-10-05 16:33
Hi @khouloudbelguith, it might be fixed since I cannot reproduce it with PrestaShop 1.7.7 beta 2. See the screenshot below. Can you confirm as well? If yes, I will close this ticket and label it as fixed. :-)

<img width="988" alt="Capture d’écran 2020-10-05 à 18 25 38" src="https://user-images.githubusercontent.com/32565890/95106483-dfd87500-0738-11eb-9f6a-0b302033fff8.png">

**Comment by khouloudbelguith** [comment] 2020-10-06 09:09
Hi @LouiseBonnard,

Yes, it is ok with 1770rc1build1
![image](https://user-images.githubusercontent.com/16067358/95182049-64bca080-07c4-11eb-8280-69c42ab3e814.png)

But with develop branch(1780) => NOK
![image](https://user-images.githubusercontent.com/16067358/95182071-6d14db80-07c4-11eb-8870-a5e28ae25689.png)

Thanks!

**Comment by LouiseBonnard** [comment] 2020-10-06 09:17
Great, thanks a lot @khouloudbelguith! I close this ticket then.

**Comment by khouloudbelguith** [comment] 2021-04-12 10:23
Hi!

This issue still exists with PrestaShop v1.7.8.0 (develop branch).
![image](https://user-images.githubusercontent.com/16067358/114379981-d0276680-9b89-11eb-8c04-491605b149d8.png)
I will re-open the issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2021-04-14 07:58
Hi @Julievrz,

What do you think?
Is it a wording issue?

Thank you!

**Comment by Julievrz** [comment] 2021-04-20 08:29
I believe it has nothing to do with Crowdin as this string is translated and validated in Arabic on Crowdin for 1.7.7.

**Comment by atomiix** [comment] 2021-04-29 15:57
@khouloudbelguith @Julievrz The wording has been changed in #19819 to be able to change the number of merchants without changing the wording. That's why it's not translated once again. This will be solved when the new wording will be pushed on crowdin and translated.

Maybe we can close this issue?

**Comment by khouloudbelguith** [comment] 2021-05-04 11:00
Hi @atomiix,

Thank you @atomiix :slightly_smiling_face: 
I think yes we can close it.
Ping @Julievrz what do you think?

Thank you!

**Comment by Julievrz** [comment] 2021-05-04 12:22
Yes, that suits me fine thank you. 😊

**Closed as completed** 2021-05-04 12:22 UTC
Labels: Bug, develop, Minor, IN, Regression, Fixed
