### ISSUE TITLE
Prestashop 1.7.5.0 Product entry issues

### ISSUE THREAD

**Issue by sts098** [PrestaShop/PrestaShop#12242] opened 2019-01-21 15:00 UTC
**Describe the bug**
When I select a product to edit in BO.  The spinner continues to spin indefinitely.  I can edit the product and save the edits.  However the product is made inactive.  When enabled, the edits appear correctly

**To Reproduce**
Enter BO.  Go to catalog, products, select a product, click edit

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0.33
Linux: Debian 9
Apache version 2.4.25

**Comment by khouloudbelguith** [comment] 2019-01-21 15:04
Hi @sts098,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - Description of your issue
 - Steps to reproduce the issue
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by slupostrupek** [comment] 2019-01-23 00:23
i think i have similar issues. When i did upgrade from 1.7.4.X after saving product it goes inactive. Also display of buttons is wrong. But i didn't have this issue on production server where i have debian. Issue happend on windows xampp + 7.1 php

but on production i have diffrent issue, which is more complicated. When i am **creating product and adding combinations** i can't choose images for them, i need to refresh page and after that, i am able to choose images and edit price for them. if i will not refresh, page is selecting tab 6 (options) and error is displayed 'Can't update product' or smth like that

**Comment by khouloudbelguith** [comment] 2019-01-23 08:57
Hi @slupostrupek,

Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
You need also to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check & feedback.

**Comment by sts098** [comment] 2019-01-23 15:15
My issues also started on upgrade from 1.7.4 to 1.7.5

**Comment by khouloudbelguith** [comment] 2019-01-23 15:17
@sts098 did you have any errors during the upgrade?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!!

**Comment by sts098** [comment] 2019-01-23 15:52
Thanks for the help.  I will attempt the fixes you suggest over the weekend.  This is a live site and I do not wish to take it down during the week.  I do not believe there were any errors during the upgrade.  I will put it in debug mode over the weekend and see what happens.  Thanks for the help so far.

**Comment by khouloudbelguith** [comment] 2019-01-23 15:54
@sts098, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-02-22 07:44
Hi @sts098,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-02-22 07:44 UTC
Labels: No change required, 1.7.5.0

**Comment by slupostrupek** [comment] 2019-05-06 06:41
hello, clearing cache did not help

**Comment by khouloudbelguith** [comment] 2019-05-08 14:02
@slupostrupek, this issue is currently closed, can you open a new one with more information about your configuration.
Thanks!
