### ISSUE TITLE
It is impossible to change position of products into a category in the catalog > product page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11152] opened 2018-10-25 11:07 UTC
**Describe the bug**
It is impossible to change the position of products into the catalog => product page.
After Drag & drop => Click on "Save & Refresh" button => The green alert "Products successfully sorted." is not displayed.
The new positions of products are not saved.

**To Reproduce**

1. Go to Catalog > Products
2. Click on Filter by categories and select a category ( Art category)
3. Click on Reorder button
4. Drag & drop some products
5. Click on "Save & Refresh" button
6. "Products successfully sorted." is not displayed & The new positions of products are not saved.
![image](https://user-images.githubusercontent.com/16067358/47496197-6189ad80-d856-11e8-804c-76a900fd61d9.png)

PS: 1.7.5.0 beta1 build1 => OK.
**Screenshots**
https://drive.google.com/file/d/1lDPMf28BqLEVKG_evNMmQWvEuZAhTDTT/view

**Additionnal information**
PrestaShop version: 1.7.5.0 beta1 build2
PHP version: 7.1

**Comment by marionf** [comment] 2018-10-25 12:05
@khouloudbelguith 
It works well for me on 1.7.5.x branch, can you check it ?

**Comment by khouloudbelguith** [comment] 2018-10-25 12:33
Hi @marionf,

I checked the 1.7.5.x branch / 1.7.5.0build1 beta2, it is the same issue.
It doesn't work.
Thanks!

**Comment by marionf** [comment] 2018-10-25 12:40
@khouloudbelguith 

I just try on 1.7.5.x
https://drive.google.com/open?id=19TrvAScnFcIEOVQ-In8i1Pk9AqDrvYkX

What is your browser ?

**Comment by khouloudbelguith** [comment] 2018-10-25 12:43
@marionf, it is Google Chrome Version 69.0.3497.81 (Build officiel) (64 bits)
Branch 1.7.5.x is updated, fresh installation.

**Comment by Rolige** [comment] 2018-10-25 13:55
I tried this in the branch 1.7.5.x and works fine for me.

**Comment by khouloudbelguith** [comment] 2018-10-25 14:35
Hi @marionf,

I make tests on the machine shuffle, nightly Prestashop & I manage to reproduce the issue.
Thanks!

**Comment by marionf** [comment] 2018-10-25 17:03
I can reproduce it randomly on 1.7.5.x

**Comment by jolelievre** [comment] 2018-11-12 12:21
I tried a lot of times but could not reproduce it..

**Comment by khouloudbelguith** [comment] 2018-11-12 13:18
@jolelievre, you need to click on the "Reorder" button before Drag & drop some products.
Thanks!

**Comment by jolelievre** [comment] 2018-11-12 13:41
Yes I know, and I was able to reorder without issues.
Anyway there is an issue related to this feature as well https://github.com/PrestaShop/PrestaShop/issues/10345
Let's see when it will have been merged if you can still reproduce this bug

**Comment by PierreRambaud** [comment] 2018-11-21 12:46
@jolelievre I can reproduce the bug, I will investigate on this issue ;)

**Comment by jolelievre** [comment] 2018-11-21 15:21
ok @PierreRambaud but be aware that there is a pending PR on this subject as well https://github.com/PrestaShop/PrestaShop/pull/11279
Can you tell me when you find how to reproduce the bug and where the problem comes from please?

**Comment by PierreRambaud** [comment] 2018-11-21 21:00
I already notice your PR, I will rebase my changes :)
In fact, we found many problems with @marionf and the funny thing about the original bug is: only the first Reorder failed, I need to clear all my filters and session to reproduce :trollface: 
Currently don't know why but still investigate :D

**Closed as completed** 2018-11-26 10:10 UTC
Labels: Bug, BO, Catalog, Regression, Fixed, 1.7.5.0

**Comment by nsorosac** [comment] 2019-07-12 09:27
Hi @marionf 

This bug is not fixed, we can reproduce on 1.7.5.x and 1.7.6.x 

You can easily reproduce it on the official demo backoffice :-(
https://demo.prestashop.com/

**Comment by marionf** [comment] 2019-07-12 10:00
Hello @nsorosac 

I can't reproduce this issue with 1.7.6.0 as you can see in the screerecord below:

https://drive.google.com/file/d/1_hmxGAJnape7dh6ljUKSv94fuW7x04T8/view?usp=sharing

**Comment by khouloudbelguith** [comment] 2019-07-12 10:03
@nsorosac, @marionf, in my case, it is OK also
https://drive.google.com/file/d/1-f-3Mr9lnOr4CL7Bh6devuq_jNE-hSTL/view
Thanks!

**Comment by nsorosac** [comment] 2019-07-12 11:18
Not for me :-(

https://drive.google.com/file/d/1oT9FHMjdQOwaRowOsH3lZteIAvQ3BMJC/view

**Comment by nsorosac** [comment] 2019-07-12 11:25
I have new information about this:

- Bug with Google Chrome 75.0.3770.90 (with or without extensions)
- No bug with Firefox (without extensions)

**Comment by khouloudbelguith** [comment] 2019-07-12 12:16
@nsorosac, thanks for your feedback.
Issue created: https://github.com/PrestaShop/PrestaShop/issues/14616

Thanks!

**Comment by nsorosac** [comment] 2019-07-12 12:35
Thank you @khouloudbelguith !
