### ISSUE TITLE
[BO/FO][Shop Parameters] Best Sales  link appears while its disabled in BO 

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21021] opened 2020-09-16 14:29 UTC
#### Describe the bug

I have disabled the Best Sellers (which is "best sales" on FO - https://github.com/PrestaShop/PrestaShop/issues/19643) 
therefore, I should not see the link Best Sales on FO

#### Expected behavior

Not being able to see the link "best sales" if its deactivated in BO

#### Steps to Reproduce

1. Go to Best Sales at the end of HP 
2. See the link is present while it shouldn't 
https://drive.google.com/file/d/1ePfzbW4KLfmm2ydTYH6zPDFgxMksJ9WR/view

Also (but Im not too sure its an issue or a bad manipulation, I am never able to see the best sellers, I get a page saying "The page you are looking for was not found." while I have previously made an order:

![Capture d’écran 2020-09-16 à 16 25 42](https://user-images.githubusercontent.com/69145330/93350750-44d73400-f839-11ea-9732-fb5dbe8f7833.png)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7.x and 1.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-09-16 14:33
Hi @ngodefroy,

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/18028

Thanks!

**Closed as completed** 2020-09-16 14:34 UTC
Labels: Bug, 1.7.x, develop, Trivial, Duplicate, Best Sellers, 1.7.6.x

**Comment by khouloudbelguith** [comment] 2020-09-16 14:36
Duplicate of #18028
