### ISSUE TITLE
cant insert products and combinations by API in prestashop 1.7.5.0

### ISSUE THREAD

**Issue by RAEzTec** [PrestaShop/PrestaShop#11650] opened 2018-12-06 22:14 UTC
In new versions of prestashop 1.7.5.0 cant insert a product or combinations by webservice. the issue was in low_stock_alert was not required and when xml not have this try insert null but the database dont acept nulls in that column.
i send a video to explain better this issue.
hope this helps.
Congrats
[presta1744or1750.zip](https://github.com/PrestaShop/PrestaShop/files/2655142/presta1744or1750.zip)

**Comment by khouloudbelguith** [comment] 2018-12-07 07:45
Hi @RAEzTec,

Your issue is added to our bug roadmap: #11628
It is not necessary to create another one.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-07 07:46
Duplicate of #11628

**Closed as completed by khouloudbelguith** 2018-12-07 07:45 UTC
Labels: Duplicate
