### ISSUE TITLE
Faceted search nos showing filter options

### ISSUE THREAD

**Issue by NeoTrafy** [PrestaShop/PrestaShop#17820] opened 2020-02-25 12:02 UTC
**Describe the bug**
I have the attributes correctly configured as visible. The faceted search module configured to show all the filters and every category. But I only see the filter titles, nothing else. I checked with clean installation of PS 1.7.5.2 and it works correctly, but once the PS is 1.7.6 it fails. I checked too with the classic theme and still remains the error. 

**To Reproduce**
1. Check visible to attributes
2. Setup module and select all categories and attributes
3. Only titles showing there.

**Screenshots**
![filtro](https://user-images.githubusercontent.com/61459813/75245433-fe9f8200-57cd-11ea-9f8e-67f9d016c5ec.PNG)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2.24

I've been investigating this error for weeks during the time I was developing the rest of the shop but it's our only bug at this time and I need it to be solved ASAP. I'd even ready to pay the one that gives me the solution. Thanks in advance.

**Comment by khouloudbelguith** [comment] 2020-02-25 12:12
Hi @NeoTrafy,

I did not manage to reproduce the issue with PS1.7.6.3 and the ps_facetedsearch v3.4.1.
I attached a screen record
https://drive.google.com/file/d/1tDC9EauO8wcMSl7Yzx-VP6nQlCnaxQwU/view
What is the exact version of the ps_facetedsearch module did you use?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-26 08:13
Hi @NeoTrafy,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-26 08:13 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.6.3
