### ISSUE TITLE
Wrong reduction input suffix on change the input reduction type in product specific price form [BO]

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#18152] opened 2020-03-14 20:55 UTC
#### Describe the bug

Wrong reduction input suffix on change the input reduction type in product specific price form
#### Expected behavior

Display the correct reduction input suffix on change the input reduction type.
See : https://drive.google.com/file/d/1Jbe-YgcIYFmdfC7g6rUo-pwShlxyK_6E/view

#### Steps to Reproduce

1. Go to an product page in BO
2. Click on price tab
3. Scroll down to **add specific price boutton**
4. Change reduction type to percentage (%)
5. See the suffix in reduction input is (€)

**Screenshots**

https://drive.google.com/file/d/1BbTvB8JrXiyIb_DckF55YdB7znjTtBoD/view
#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-03-16 14:43
Hi @PululuK,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13382 to fix the issue.
It is fixed in the PS1.7.7.0.
Your ticket is a duplicate of #13382
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-03-16 14:43
Duplicate of #13382

**Closed as completed by khouloudbelguith** 2020-03-16 14:43 UTC
Labels: Duplicate, PR available

**Comment by PululuK** [comment] 2020-03-16 14:52
> Duplicate of #13382


Hi @khouloudbelguith 
Thank you !
Same issue I agree ... But it's not the same proposition, the two PRs are totally different ! 
He proposes to delete the icon field while I propose to leave it and update it according to the type of reduction chosen.
WDYF ?

**Comment by khouloudbelguith** [comment] 2020-03-16 14:55
@PululuK, but the issue is fixed with PS1.7.7.0.
https://drive.google.com/file/d/12pwnBdJ32I_v6DdNvWpZWsiY_rvqozM5/view

Thanks!

**Comment by PululuK** [comment] 2020-03-16 14:59
Thank you @khouloudbelguith  ! In this case, we can effectively close my PR. Sorry!
