### ISSUE TITLE
PS 1.7 - Invoice access -Expected argument of type "object, array or empty", "string" given

### ISSUE THREAD

**Issue by nuevoenesto** [PrestaShop/PrestaShop#11916] opened 2018-12-24 00:38 UTC
Error when try to Access to ORDERS/INVOICE
Ps. 1.7.5.0

Symfony\Component\Form\Exception\ UnexpectedTypeException
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 41)
PropertyPathMapper->mapDataToForms('#IN', object(RecursiveIteratorIterator)) in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData('#IN') in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 49)
PropertyPathMapper->mapDataToForms(array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false), object(RecursiveIteratorIterator)) in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData(array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false)) in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 49)
PropertyPathMapper->mapDataToForms(array('invoice_options' => array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false)), object(RecursiveIteratorIterator)) in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData(array('invoice_options' => array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false))) in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 483)
Form->initialize() in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php (line 226)
FormBuilder->getForm() in src/Core/Form/FormHandler.php (line 114)
FormHandler->getForm() in src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php (line 57)
InvoicesController->indexAction(object(Request)) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 151)
HttpKernel->handleRaw(object(Request), 1) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 68)
HttpKernel->handle(object(Request), 1, false) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
Kernel->handle(object(Request), 1, false) in adminlabs/index.php (line 88)

**Comment by khouloudbelguith** [comment] 2018-12-24 07:51
Hi @nuevoenesto,

Your ticket is a duplicate of #11909
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-24 07:51
Duplicate of #11909

**Closed as completed by khouloudbelguith** 2018-12-24 07:51 UTC
Labels: Duplicate
