### ISSUE TITLE
Performance issue when loading front end

### ISSUE THREAD

**Issue by javierdelval** [PrestaShop/PrestaShop#25577] opened 2021-08-12 08:10 UTC
#### Crome web developer performance tool analysis

When we do a performance analysis on 1.7.6.8, shop starts rendering ok (1.jpg). At 2.jpg the page render seems to be restarted. In 3.jpg and 4.jpg we see the render ended. This issue worsens the load performance noticeably. We have noticed this effect in 1.7.6.1 and 1.7.6.5

#### Steps to Reproduce

1. Open Chrome DevTools 
2. Go to the performance tab
3. Make several recordings and you'll see the issue

**Screenshots**

![image](https://user-images.githubusercontent.com/6302025/129161620-3bcaab13-8e27-4015-9459-8a4c5a0a9b04.png)
**1.jpg**

![image](https://user-images.githubusercontent.com/6302025/129161709-6da0ca6b-b614-4d42-8b71-361a5cba111e.png)
**2.jpg**

![image](https://user-images.githubusercontent.com/6302025/129161801-ae836fc1-30b7-49bf-8b57-92c1526063b3.png)
**3.jpg**

![image](https://user-images.githubusercontent.com/6302025/129161906-0e1d7c4f-d366-4169-8f03-f491938412f4.png)
**4.jpg**

* PrestaShop version: 1.7.6.x
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-08-12 09:38
Hello @javierdelval 

Thanks for your issue!
Could you please downgrade your PHP version to 7.2 cause PS176x is not compatible with PHP 7.3 (see our [sysem requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
I know it may not related to your issue performance, but let's check :wink: 

Thanks!

**Comment by javierdelval** [comment] 2021-08-12 10:06
hi,

thanks for your quick answer. I've checked with php 7.2 version and I have the same effect. I configured 7.3 because my hosting provider has issues with imagick with 7.2.

regards, Javier

**Comment by hibatallahAouadni** [comment] 2021-08-17 15:26
Hello @javierdelval 

Thanks for your feedback.
> Make several recordings and you'll see the issue

Could you please explain it more, like in your screenshots add some circules to see better the issue :pray: 
Please check and feedback.

Thanks!

**Comment by javierdelval** [comment] 2021-09-02 12:49
Hello,

I've just come from holidays. Sorry.

At the beginning  the render seems okay. Template and images are rendered...

[image: image.png]

But a few *ms *later all the images are gone.

[image: image.png]

Then, all images begin to reload

[image: image.png]
After 300ms, all images are rendered.

[image: image.png]

This effect (from 900ms to 2200ms) worsens the render time and Page Speed
Insight marks. Any clue?

Regards

Javier

**Comment by hibatallahAouadni** [comment] 2021-09-02 12:58
Hello @javierdelval 

Could you please respond on GitHub. Cause when you reply by email, all the attached photos are not displayed:

![image](https://user-images.githubusercontent.com/23308427/131847709-520135ad-ac02-47ac-b106-9dec5876e68a.png)

Please check and feedback.
Thanks!

**Comment by javierdelval** [comment] 2021-09-03 12:47
Hello,

Sorry .-)

At the beginning  the render seems okay. Template and images are rendered...

![1](https://user-images.githubusercontent.com/6302025/132007342-add55893-e227-4702-a837-28fc3ef3e77f.jpg)

But a few ms later all the images are gone.

![2](https://user-images.githubusercontent.com/6302025/132007397-ddf2a2ea-aa4f-4501-a15e-1a86a6a3bf27.jpg)

Then, all images begin to reload

![3](https://user-images.githubusercontent.com/6302025/132007455-cf75fbd6-fdf4-44fd-8c03-7441ab51f664.jpg)

After 300ms, all images are rendered.

![4](https://user-images.githubusercontent.com/6302025/132007502-e9ba8784-72a2-44ca-ab66-6ceb7ccf35a3.jpg)

This effect (from 900ms to 2200ms) worsens the render time and Page Speed Insight marks. Any clue?

Regards

Javier

**Comment by khouloudbelguith** [comment] 2021-09-03 13:14
Hi @javierdelval,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.7.7.
I attached a screen record
https://drive.google.com/file/d/1CWIRQe0LzxS3APdSKunOqffo5mQzDl0j/view?usp=sharing

Thanks to check and feedback.

**Comment by javierdelval** [comment] 2021-09-04 06:10
Hello,

check this video please:

https://drive.google.com/file/d/1M2-xbsgahlA_GgunBfOXf0Cih2PkZW4-/view?usp=sharing

This is a brand new installation of Prestashop 1.7.7 with PHP 7.3. I've installed it in a different server to avoid possible problems of misconfiguration. You can check it here <https://demo.tallerw3.com/>. In the video, the effect is much softer, but I think this is the case because it doesn't have anything installed.

regards

Javir

**Comment by hibatallahAouadni** [comment] 2021-09-06 11:09
Hello @javierdelval 

Despite our efforts, we were not able to reproduce your issue with PS1767 and PS1777. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-06 11:09 UTC
Labels: Bug, FO, Performance, No change required, 1.7.6.8
