### ISSUE TITLE
When you deactivate a product from Catalog> Products it does not redirect 301 Table: ps_product. Field: redirect_type

### ISSUE THREAD

**Issue by Davidlleide** [PrestaShop/PrestaShop#20327] opened 2020-07-24 13:27 UTC
#### Describe the bug
When you deactivate a product from Catalog> Products it does not redirect 301
If, once the product has been deactivated, you enter its file and save, the corresponding redirect appears in the redirect_type field.
Table: ps_product. Field: redirect_type
If you deactivate the product from its template, redirection is activated.
If you disable many products at once, they are not redirected to 301.

#### Expected behavior

When you deactivate a product from Catalog> Products, the Field: redirect_type is not activated and is left blank.
On the contrary, if you do it from the product page, the field is activated.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 6.3

**Comment by florine2623** [comment] 2020-07-24 14:10
Hi @Davidlleide ,
I can't reproduce your issue on my test shop PS 1.7.6.7.
Please see the screenshots below.
I deactivated my product :
![Capture d’écran 2020-07-24 à 15 57 48](https://user-images.githubusercontent.com/16019289/88399963-ec029680-cdc7-11ea-9a69-9d9868e7df34.png)
The preview after disabling the product to my customers :
![Capture d’écran 2020-07-24 à 15 57 30](https://user-images.githubusercontent.com/16019289/88399975-ee64f080-cdc7-11ea-9da6-5067976ff7f3.png)
What the redirection is like in my database :
![Capture d’écran 2020-07-24 à 15 56 50](https://user-images.githubusercontent.com/16019289/88399986-f15fe100-cdc7-11ea-9815-b1a107e5796a.png)


Also, please state the steps to reproduce the issue, or add screenshot so that it is easier to understand.
Thanks!

**Comment by Davidlleide** [comment] 2020-07-24 14:48
Hello, I have already found the problem. It comes from loading products with a .csv file, which is not specified in the redirect_type field and is left blank.
If you create a new product, the program already fills in that field.
If I load it by .csv the product (maybe I do something wrong) does not update the redirect_type field and is blank. Then when deactivating it without entering the product file, that blank field (in ps_product and in ps_product_shop) causes the message "this product does not exist" to appear.

![Captura de pantalla de 2020-07-24 16-33-59](https://user-images.githubusercontent.com/59093179/88403876-671a7b80-cdcd-11ea-849f-046ca6b0e83e.png)
![Captura de pantalla de 2020-07-24 16-34-42](https://user-images.githubusercontent.com/59093179/88403879-67b31200-cdcd-11ea-8a98-4d1ec98ce324.png)
![Captura de pantalla de 2020-07-24 16-47-13](https://user-images.githubusercontent.com/59093179/88403887-697cd580-cdcd-11ea-81de-17fad9a7bd8c.png)

**Comment by khouloudbelguith** [comment] 2020-07-27 14:53
Hi @Davidlleide,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1hPfsgY0fTfEQqevQKkSYqbKKNIvVpT9Z/view?usp=sharing

Thanks to check and feedback.

**Comment by Davidlleide** [comment] 2020-07-31 21:10
Hi, after a lot of testing, I realized that the problem was with friendly urls activated. After testing more I checked that if I cleared the entire browser cache (F5 was not enough) the changes were shown. It was not a problem with friendly urls, only the browser cache.
I feel the confusion, thank you very much for everything.

**Comment by khouloudbelguith** [comment] 2020-08-03 13:29
@Davidlleide, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-03 13:29 UTC
Labels: Bug, Catalog, Import / Export, No change required, 1.7.6.7
