### ISSUE TITLE
Fatal error in module file

### ISSUE THREAD

**Issue by ColbellHHS** [PrestaShop/PrestaShop#22494] opened 2020-12-18 11:01 UTC
#### Describe the bug

From Dashboard Screen, I access the modules tab which brings out the options tab.
I click on Modules and a web page loads with the following error;

[PrestaShop] Fatal error in module file :/var/www/vhosts/hhands.co.uk/httpdocs/modules/autoupgrade/upgrade/install-4.9.0.php:
Call to private method Autoupgrade::registerHookAndSetToTop() from context ''

#### Expected behavior
On clicking the modules option, I would see a screen with a list of installed modules for my site.

#### Steps to Reproduce

1. Log on to Prestashop Dashboard.
2. In sidebar, choose Modules
3. Modules tab opens.
4. Choose Modules
5. Web page opens to blank screen with above error displayed.

This is reproducible 100% of attempts

**Screenshots**

![image](https://user-images.githubusercontent.com/76206528/102606197-4bb66100-411e-11eb-8d5f-6b8e2c152674.png)

![image](https://user-images.githubusercontent.com/76206528/102606965-748b2600-411f-11eb-9b48-aa45b9679c0f.png)

#### Additional information

* PrestaShop version: 1.6.1.10
* PHP version: 5.6.40

**Comment by PierreRambaud** [comment] 2020-12-18 11:19
Thank for your report.

It's a duplicate of #22399

**Closed as completed by PierreRambaud** 2020-12-18 11:19 UTC
Labels: Duplicate

**Comment by SimonGrn** [comment] 2020-12-18 22:52
Duplicate of #22399
