### ISSUE TITLE
Install language if under the proxy 

### ISSUE THREAD

**Issue by arthtux** [PrestaShop/PrestaShop#11218] opened 2018-11-01 12:18 UTC
**Describe the bug**
We can not install a language if under a proxy.

**To Reproduce**
1. Go to **'/webtools/index.php?controller=AdminTranslations'**

**Screenshots**
![capture d ecran le 2018-11-01 a 08 16 26](https://user-images.githubusercontent.com/5318898/47851279-89c16100-ddae-11e8-884c-d173eb52513a.png)

**Additionnal information**
PrestaShop version: 1.7.4.0
PHP version: not important

**Resolve this issue**
If i change the context for the file_get_contents with this option the request is good. 
line 204 in `controllers/admin/AdminTranslationsController.php`

```php
$arrayStreamContext = stream_context_create(array('http' => array('proxy'=> $proxy, 'method' => 'GET', 'timeout' => 8, 'request_fulluri' => True)));
```

**Comment by khouloudbelguith** [comment] 2018-11-01 13:23
Hi @arthtux,

I tried to add a language when the proxy is enabled, & it is OK.
I did not manage to reproduce the issue with 1.7.4.0.
I attached a video record.
https://drive.google.com/file/d/1KcukhHvrLU8IFXQ9DFYx9JOYRZ46t4Dt/view
If you enable the debug mode, is there any exception displayed?
Thanks!

**Comment by arthtux** [comment] 2018-11-01 14:09
Hi @khouloudbelguith, 

your instance have a proxy setup in your apache?

**Comment by khouloudbelguith** [comment] 2018-11-01 14:42
Hi @arthtux,

No, I just activated an extension proxy.
Thanks!

**Comment by arthtux** [comment] 2018-11-01 14:44
ok
But the `file_get_contents` is execute on the server and not in your browser.

**Comment by khouloudbelguith** [comment] 2018-11-01 15:52
@arthtux, to reproduce your issue, I need to activate the proxy module on apache?
Thanks!

**Comment by arthtux** [comment] 2018-11-01 16:17
yep. 
If you are in centos or Redhat. 
Close all output http traffic on your internet link. 
Open only traffic on the http proxy on your internet link.
Setup your apache proxy with your http_proxy and https_proxy env var (in /etc/sysconfig/httpd file on Centos)
After you restart apache and normaly after you see this error. 

If you have a trouble for this manipulation you can see your system administrator.

**Comment by khouloudbelguith** [comment] 2018-11-01 17:08
@arthtux,

Thanks for this clarifications.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-02 11:01
Hi @arthtux,

```
Server information Linux #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64
Server software version: Apache/2.4.25 (Debian)
PHP version: 7.1.19
```
 I defiened a proxy reverse https on http
![image](https://user-images.githubusercontent.com/16067358/47911728-83a6af80-de96-11e8-93cc-897ce498410a.png)
I activated the modules proxy & proxy_http
But I did not manage to reproduce the issue with PS 1.7.4.3
I attached a video record.
https://drive.google.com/file/d/1yAXVMYgfK5HvMu3tDV0rTbjdA1qlRQYx/view
Thanks to check & feedback.

**Comment by arthtux** [comment] 2018-11-05 12:59
Hi @khouloudbelguith, 
you do not understand :( if it is not in Apache Config but it is on the environment variable when you start Apache, that you configure your proxy.
and your instance have internet access directly.

**Comment by khouloudbelguith** [comment] 2018-11-05 16:19
Hi @arthtux, would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by khouloudbelguith** [comment] 2019-02-06 11:01
Hi @arthtux,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-06 11:01 UTC
Labels: BO, International, 1.7.4.0, Translations, No change required
