### ISSUE TITLE
price showing issue

### ISSUE THREAD

**Issue by aghaeian** [PrestaShop/PrestaShop#30019] opened 2022-10-15 11:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Products prices not show or show some. 
website: arsalan.com.tr/furniture

![Ekran Resmi 2022-10-15 14 00 49](https://user-images.githubusercontent.com/115875025/195983239-9e1516af-0fe8-4595-89de-95f361f0c87f.png)
![Ekran Resmi 2022-10-15 14 08 44](https://user-images.githubusercontent.com/115875025/195983271-9e3460ea-0afe-45bd-916a-06d47ddf0f9c.png)

### Steps to reproduce

home page.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by aghaeian** [comment] 2022-10-15 11:11
http://www.arsalan.com.tr/furniture

**Comment by Hlavtox** [comment] 2022-10-17 08:45
Hi @aghaeian, this is a problem with your template. The prices are correctly rendered, you have some CSS/JS issues.

![template](https://user-images.githubusercontent.com/6097524/196132219-5de5e3fd-ac68-42bd-bd30-62a50f4623ba.jpg)

**Comment by aghaeian** [comment] 2022-10-17 08:59
Hi @Hlavtox , Thank you for response. I try to find css/js issue but can't find it. Can you help me?
Best Regards.

**Comment by hibatallahAouadni** [comment] 2022-10-17 17:38
Hello @aghaeian 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely an override or a theme problem.

PS: thanks @Hlavtox for your quick replies :pray: :rocket: 

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-10-17 17:38 UTC
Labels: Bug, Invalid
