### ISSUE TITLE
[RE-order] No notification when an error occurs

### ISSUE THREAD

**Issue by Lionel-dev** [PrestaShop/PrestaShop#26804] opened 2021-11-30 08:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I noticed that when a customer wanted to reorder one of his orders, but one of the products was out of stock, he was redirected to the home without having the reason for this redirection. 

By diving into the code, I notice that the duplication of the basket fail due to the OOS of a product, this problem generates an error that is put in $this->errors, but it will not appear in front. 

### Expected behavior

If an error is generated during the duplication of the cart, we should be redirected to the home page with an error in front so that the customer is aware of the reason.

### Steps to reproduce

1. Create an order with multiple product
2. Set the quantity of one of the products to 0
3. Go to your order history as a customer
4. Click on "reorder". 

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment] 2021-11-30 16:27
Hello @Lionel-dev 

Thanks for reporting the issue!
I reproduce the issue with PS1765, PS1778 and PS1781, see the attached screen record below:

https://watch.screencastify.com/v/2GdzFZdWYc9LvDUsBbFC

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Lionel-dev** [comment] 2021-12-01 07:55
Hello @hibatallahAouadni,

I have created a [pull request](https://github.com/PrestaShop/PrestaShop/pull/26791) to fix this bug. I understood that I was obliged to create an exit so that my pull request is accepted. 

Thank you very much for this video which demonstrates the bug !

**Comment by hibatallahAouadni** [comment] 2021-12-01 08:51
@Lionel-dev thanks for your PR :rocket:

**Closed as completed** 2021-12-27 13:10 UTC
Labels: Bug, Minor, FO, Order, Fixed, PR available, 1.7.6.5, Verified
