### ISSUE TITLE
Visitor gets free shipping displayed in shopping cart, although price is lower than the value set for free shipping

### ISSUE THREAD

**Issue by nielsverhoeven84** [PrestaShop/PrestaShop#14830] opened 2019-07-23 14:12 UTC
For 1 of my multistore shops I always want to use a shipping cost, currently it shows free shipping, although it is filled at the shipping preferences.
 
**To Reproduce**
1. Go to https://www.cardinalrouge.fr/chardonnerets/631-394-chardonneret-major-classique.html#/65-sexe-male
2. Order the product
3. `Frais de port : gratuit` is displayed (`Shipping cost: free`) 

This is also displayed in the shopping cart.

![Schermafbeelding 2019-07-23 om 16 10 58](https://user-images.githubusercontent.com/52320806/61719055-7bfca300-ad64-11e9-9d59-58bc80eb572f.png)

**Additional information**
PrestaShop version: 1.7.5.2

**Comment by khouloudbelguith** [comment] 2019-07-23 14:17
Hi @nielsverhoeven84,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13517 to fix the issue.
It is added to the PS1.7.7.0 milestone.
Your ticket is a duplicate of #10739
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-23 14:17
Duplicate of #10739

**Closed as completed by khouloudbelguith** 2019-07-23 14:17 UTC
Labels: Duplicate

**Comment by nielsverhoeven84** [comment] 2019-07-24 09:51
If I make the changes my shop doesn't load the homepage anymore. are there diffences for PS 1.7.5.2?

**Comment by khouloudbelguith** [comment] 2019-07-24 09:57
@nielsverhoeven84, about this PR, it should be reviewed by our developers but it is not tested yet by our QA team.

Thanks!
