### ISSUE TITLE
displayError throws 500, why?

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18404] opened 2020-03-31 22:39 UTC
This PR: https://github.com/PrestaShop/PrestaShop/pull/13209 introduced a change in Tools::displayError that always throws error 500 and kills the page.

It creates a problem in official European VAT module, which uses this method, if the VAT does not validate.

![EBA3BBC6-950B-48DD-A131-FA72813EB4D9](https://user-images.githubusercontent.com/6097524/78081607-35f6e500-73b1-11ea-9981-81352b96bf09.png)

**I think, the store should not produce Fatal Error, if customer enters wrong VAT number... 😄** 

Commenting out `header('HTTP/1.1 500 Internal Server Error', true, 500);` in Tools fixed the error for me and seems to have no side effects for several months now.

#### Additional information
* PrestaShop version: 1.7.6
* vatnumber version: 2.1.0
* PHP version: 7.2
* I am using The Checkout OPC module https://addons.prestashop.com/en/express-checkout-process/42005-the-checkout.html

**Comment by matks** [comment] 2020-04-01 13:50
Hi @Hlavtox
I checked `Tools::displayError()` implementation (see https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Tools.php#L1161)

It seems that, most of the time, `Tools::displayError()` is used like this:
```
    // some code
    if ($thereIsAnError) {
        die(Tools::displayError());
    }
```

In this case, the fact it sends the right headers is a good thing as
- indeed it helps server software to understand this is an error page, not a correct page (and, among other things, this page should not be cached)
- it can be used by monitoring software to flag, track and notify when such page are displayed to user so the team in charge of the shop is aware of the issue
- some browsers will find it useful too

However in the snippet of code you are showing, `Tools::displayError()` is used to generate a meaningful message (and I dont expect a `die()` to be used later). **There** is the problem.

So if we consider `Tools::displayError()` job is to display an error message on the page (like in `die(Tools::displayError());` ), the PR https://github.com/PrestaShop/PrestaShop/pull/13209 was right.
If we consider `Tools::displayError()` job is to create the error message but let other components decide what to do with it (log it, display it, discard it ...), the PR https://github.com/PrestaShop/PrestaShop/pull/13209 was wrong.

Unfortunately when I check `Tools::displayError()` usage in the code it seems to be always a `die(Tools::displayError());` usage so it would be usecase 1.

Moreover there is this snippet of code inside `Tools::displayError()` :
```
        if (_PS_MODE_DEV_) {
            throw new PrestaShopException($errorMessage);
        }
```

This clears the possible misunderstanding : job is to display an error message on the page (this is exactly what it does in dev mode) and it was used wrong inside Checkout OPC module. The module needs to be updated.

However we could also consider this is a BC Break 🤔 wdyt @PierreRambaud ?

**Comment by khouloudbelguith** [comment] 2020-04-01 14:13
Hi @Hlavtox, @matks,

The `vatnumber` module is not available for 1.7 as reported here:
https://github.com/PrestaShop/PrestaShop/issues/9884
Here's the module from GitHub: https://github.com/PrestaShop/vatnumber

>I think, the store should not produce Fatal Error, if customer enters wrong VAT number... 

How can I reproduce the issue?

Thanks!

**Comment by Hlavtox** [comment] 2020-04-01 14:56
@matks Then it's the fault of vatnumber module. It hooks to hookActionValidateCustomerAddressForm and if it's wrong, it displays error.

OPC has “nothing to do with it”.

@khouloudbelguith I don't know about the official compatibility, but it works fine! :) There have been some PRs to make it compatible with 1.7.

Maybe we should ask @eternoendless if he can adapt the module, so it shows the error in 1.7-compatible way?

**Comment by khouloudbelguith** [comment] 2020-04-01 15:02
@Hlavtox,

>I think, the store should not produce Fatal Error, if customer enters wrong VAT number...

How can I reproduce the issue?

I followed these steps:
1. Install PS1.7.6.4
2. Install vatnumber module
2. Configure it with France
3. Go to FO => Add product to the cart => process to checkout
4. Choose a payment module by default 
5. Click "Place Order" => OK

Thanks!

**Comment by sarahdib** [comment] 2020-05-05 12:08
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 12:08 UTC
Labels: Bug, FO, No change required, Checkout, 1.7.6.0
