### ISSUE TITLE
Error in module selecction

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#11005] opened 2018-10-14 17:12 UTC
**Describe the bug**
The module read more get a error.

**To Reproduce**
1. Go to 'Modules'
2. Click on 'Selection and more info.'
3. See error

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/9163980/46919800-000b4880-cfe5-11e8-8830-b1eda7fdca1e.png)

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-10-15 08:13
Hi @LinkOfLight,

The issue is added to our debug roadmap.
Your ticket is a duplicate of #9722
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-15 08:13
Duplicate of #9722

**Closed as completed by khouloudbelguith** 2018-10-15 08:13 UTC
Labels: Duplicate
