### ISSUE TITLE
ajax posterror

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#15256] opened 2019-08-26 09:15 UTC
My customers are getting this error pop up on the site when they try and pay for items ajax posterror. I did use to have CoinGate and Stripe as well but they have both stopped working and no matter how many times I reset them or reinstall them after there reconfigured they don't even show up as an option pay, only PayPal shows as an option, I have removed PayPal and it made no difference the others still would not show.

I have also tried going from the new template to the free one to see if it would make any difference but it didn't, so I'm all out of ideas.

![ajax posterror](https://user-images.githubusercontent.com/52738920/63679773-6ad70400-c7f2-11e9-8c99-5738016baaa8.jpg)

**To Reproduce**
1. Go to 'https://allcom-international.com'
2. Click on 'Any product'
3. Scroll down to 'register an account or don't, it doesn't matter'
4. proceed to pay using PayPal Only option at this point

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1, 7.2, 7.3 % 7.4 Beta. I've tried them all, made no differance.

Any Ideas.

Thank you in advance.

**Comment by khouloudbelguith** [comment] 2019-08-26 09:40
Hi @Allthejam,

I did not manage to reproduce the issue with PS1.7.6.0 & Papal v4.5.0.
https://drive.google.com/file/d/1Dh4ThQHB7z2hMg3Q3iqa5fVR2A-0abQ3/view
![image](https://user-images.githubusercontent.com/16067358/63681538-df5b7400-c7ed-11e9-8391-e2ba40ccb4a8.png)
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
https://addons.prestashop.com/fr/contactez-nous?id_product=1748
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-26 09:41
@Allthejam, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

**Comment by Allthejam** [comment] 2019-08-26 09:51
Hi, Thank you for that info.

I think you might have missed my point, it's a Presta problem that occurs on my store, its not a PayPal issue because even after I uninstall PayPal the store won't show any payment methods, the only on that I can get to show is PayPal and that doesn't work because of the ajax posterror.

Ok, let's forget about PayPal, let's say I don't want or even have PayPal, let's imagine for a second that I have tried to install multiple payment methods on my store and NONE of them work, and by not work I mean they don't even show up in the Cart or anywhere else. What do I have to do to fix it?

I say Imagin it but in reality, I have tried this and nothing works, over 500 hits per day and not a single sale because of this problem.

Thank you

Allthejam

**Comment by khouloudbelguith** [comment] 2019-08-26 10:54
@Allthejam, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Allthejam** [comment] 2019-08-26 13:58
Ok, I put it into Debug mode and this happened straight away.
![2019-08-26_155107](https://user-images.githubusercontent.com/52738920/63696004-1d6e8d00-c81a-11e9-96da-ee24d01a29a7.jpg)
 Now I can't get into the back office at all, I'm completely shut out and have no clue what to do. 

I'm at my wit's end here, PLease, Any suggestions?

**Comment by khouloudbelguith** [comment] 2019-08-26 14:02
@Allthejam, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by Allthejam** [comment] 2019-08-26 14:07
I've cleared all the cache, I've tried logging in through different browsers, I can't get in, so I can't do anything, I've even tried a different PC and Laptop and the results are all the same.

Basically, I'm now shut out of the back office.

**Comment by khouloudbelguith** [comment] 2019-08-26 14:13
Could you please try to run those command lines to remove the cache:

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Because, the exaception attached recently is a cache issue.
As I said before, PrestaShop is not compatible with PHP 7.3 yet.
Thanks!

**Comment by Allthejam** [comment] 2019-08-26 14:19
I have been running PHP 7.2 as you suggested, 
Where should I run those commands? I can't get into my back office...

I can't run them in Command Prompt because: 'php' is not recognized as an internal or external command, operable program or batch file.

**Comment by khouloudbelguith** [comment] 2019-08-26 14:23
@Allthejam, with a terminal you can run those commands.
After cearing the manaully => BO is not accessible?
If, yes => it is a permission issue => you need to give the right permissions to your Folder.
Thanks!

**Comment by Allthejam** [comment] 2019-08-26 14:24
Sorry, I don't know what you're going on about, what terminal?

**Comment by khouloudbelguith** [comment] 2019-08-26 14:34
@Allthejam, If you are using OS linux you can follow this documentation: https://en.wikipedia.org/wiki/Linux_console
If you are using OS windows you can follow this documentation: https://en.wikipedia.org/wiki/Cmd.exe
>'php' is not recognized as an internal or external command, operable program or batch file.

You need to check your host about this error

Thanks!

**Comment by Allthejam** [comment] 2019-08-26 14:38
I ran those commands in cmd, I've cleared all the cache from my PC more than once, like I said I have even used a different pc and a laptop to try and log into my back office and I am getting the same results. This cant be a cache problem.

**Comment by khouloudbelguith** [comment] 2019-08-26 14:47
@Allthejam, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the creadentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by Allthejam** [comment] 2019-08-26 14:52
Done.

Thank you

**Comment by khouloudbelguith** [comment] 2019-08-26 15:20
@Allthejam, I cannot access to your shop 
![image](https://user-images.githubusercontent.com/16067358/63701601-24e36580-c81d-11e9-89be-391020ab5045.png)
![image](https://user-images.githubusercontent.com/16067358/63701685-4f352300-c81d-11e9-9d3a-8cc7681f7d20.png)
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by Allthejam** [comment] 2019-08-26 15:25
Done.

Cleared the folder

**Comment by khouloudbelguith** [comment] 2019-08-26 15:29
@Allthejam, now it is OK.
I will check & feedback

**Comment by Allthejam** [comment] 2019-08-26 15:30
Ok, I will have a good look around, Thank you.

**Comment by Allthejam** [comment] 2019-08-26 15:49
Thank you, I have Stripe and Coingate back working once again, you're a genius. 

Thank you

**Comment by khouloudbelguith** [comment] 2019-08-26 15:49
@Allthejam, Paypal is not installed in your case.
I found stripe
I tried to install the COD module & it is well displayed on the FO
But the stripe module is not displayed.
So, if you have only this module installed => that's why you don't have payments on the last checkout step.

Thanks!

**Comment by Allthejam** [comment] 2019-08-26 15:53
No, I deleted them and was going to reinstall it all but got locked out with that problem so I couldn't, I have them installed and they are working as they should be now, I have just run a test.

Once again. Thank you for all your support

**Comment by khouloudbelguith** [comment] 2019-08-26 16:01
@Allthejam, thanks!
Since it is fixed.
I close the issue, feel free to open a new one when needed.

**Closed as completed by khouloudbelguith** 2019-08-26 16:01 UTC
Labels: FO, Payment methods, No change required, 1.7.6.0
