### ISSUE TITLE
Errors in the Gsitemap Module of Prestashop 1.7.5.2

### ISSUE THREAD

**Issue by Ferreidea** [PrestaShop/PrestaShop#16988] opened 2019-06-26 15:02 UTC
Hi!

The Gsitemap Module is configured in my site in the version 4.1.0 in a 1.7.5.2 Prestashop Store

I have a cron task that generates the sitemap every night

My site has already 31.000 urls more or less, but the Gsitemap Module only generates 25.001 urls in the mastwer sitemap file and no matter how many produts or categories I add,The sitemap is blocked in 25.001 urls and do not generate any more.The weight of the sitemap has been frozen in 14,58 MB since 4 month ago, but my store continues to grow and having more urls...

Seem like the sitemap has reached a Wall and do not generate more than this 25.001 urls

Other issue I have is that the sitemap  when I run the Creation of the sitemap manually, (In de back office of prestashop) it generates other sitemap file that do not exist in my hosting,I explain:

Originally I have 2 sitemaps files in my server that generates the Gsitemap module by the cron task daily:
-https://mysite.com/1_index_sitemap.xml (The index of sitemaps)
-https://mysite.com/1_es_0_sitemap.xml (The master sitemap)

But When I Generate the sitemap manually in the module inside de Back end of prestashop,the module generates a new Master sitemap: https://mysite.com/1_es_1_sitemap.xml that only contains 3.000 urls (when my site has 31.000 urls).

So, I been stuck for so long with this 2 problems

Please,could you let me know what I have to do to fix this problems and the module Create a sitemap with all the correct urls of my site?

Ill wait your answer

**Comment by khouloudbelguith** [comment] 2020-01-02 11:30
Duplicate of #16991

**Closed as completed by khouloudbelguith** 2020-01-02 11:30 UTC
Labels: Duplicate, Google sitemap
