### ISSUE TITLE
the return url goes HTTP error 500 after payment complete

### ISSUE THREAD

**Issue by yuxiayuzhou** [PrestaShop/PrestaShop#18610] opened 2020-04-14 01:29 UTC
#### Describe the bug

we found a return url error happened after checking out (purchase complete). The error can be seen in attached screenshot. it says the trade not complete, but actually it goes smoothly and the owner can receive the money as well.

#### Expected behavior

It would be helpful to guide where to set up the url and remove the error page.

#### Steps to Reproduce

omay have to visit this specific website  in the screenshot and can replicate this issue.

**Screenshots**
![WechatIMG13](https://user-images.githubusercontent.com/53670538/79176077-72b3e900-7e53-11ea-935f-e597b5eb7746.jpeg)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: N/A

**Comment by sarahdib** [comment] 2020-04-14 12:20
Hello @yuxiayuzhou 

Could you give us more information, like which module did you use ? The steps to reproduce this behaviour.

Thank you

**Comment by yuxiayuzhou** [comment] 2020-04-14 23:47
> Hello @yuxiayuzhou
> 
> Could you give us more information, like which module did you use ? The steps to reproduce this behaviour.
> 
> Thank you

Sure. We are using Eway as credit card payment solution. you can simple buy 3-5$ stuff for test. After the purchase, it will go crash like above attached screenshot.  I can refund you the money back. 
Alternatively, may have to go with test mode. this will disable the function and give you the test credit card details. It is quite complicated. please let me know if any further i can do. thank you.

**Comment by sarahdib** [comment] 2020-04-15 14:23
@yuxiayuzhou 
It's a third part module you need to contact directly the developer of this module.

Since the problem is related to a module and not prestashop core I close this ticket.

Thank you

**Closed as completed by sarahdib** 2020-04-15 14:23 UTC
Labels: Bug, No change required, 1.7.6.2
