### ISSUE TITLE
MBO Filters in Module catalog page 

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#12567] opened 2019-02-14 10:15 UTC
**Describe the bug**

If you try using filter "sort by" and switch by "Popularity", "Decreasing" and so on you can observe a wrong behaviour as expected. Popularity criteria seems to be random, because if you reload the page you can see a different list each time (same behaviour for Increasing or Decreasing but it's well sorted by price)

**To Reproduce**
1. Go to 'Module Catalog'
2. Click on '- sort by -' button and choose Increasing for example
3. It works well but if you change by Popularity and switch again on Decreasing you can see some wrong list

**Screenshots**
https://drive.google.com/file/d/1JeiK_-gLDfFNujtLRmDFkd-CfI6wyk6o/view

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-02-14 10:38
Hi @mbadrani,

It is a regression.
I tried with PS1.7.5.0 & the ps_mbo module v1.1.1 => OK.
With PS1.7.5.1build1 & the ps_mbo module v1.1.1 => NOK.
I have the same issue.
Thanks!

**Comment by marionf** [comment] 2019-02-14 11:08
@khouloudbelguith 

I have the same behavior in 1.7.5.0 & 1.7.5.1
https://drive.google.com/open?id=1mwlgif-1xacK6F_CdR2Pa1eNi1BPErbl

In 1.7.5.1 filters by increase, decreasing prices and name are well working
https://drive.google.com/open?id=15cuxSsCN-mpiERCFozWx9om60GSFTkQk

The issue with popularity isn't new, if you choose popularity, you will have some modules displayed in a certain order.
If you refresh the page and choose again popularity, you will have the same modules displayed but in another order than the first time

**Comment by khouloudbelguith** [comment] 2019-02-14 11:50
@marionf, yes about the sorting with popularity filtering issue, is an old issue reported in this ticket: https://github.com/PrestaShop/ps_mbo/issues/83
Thanks!

**Comment by marionf** [comment] 2019-02-14 12:41
So, this issue is a duplicate of https://github.com/PrestaShop/ps_mbo/issues/83

**Comment by khouloudbelguith** [comment] 2019-02-14 13:08
@marionf, no I don't think that is the same as described by @mbadrani.
@mbadrani what do you think?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-14 13:31
@marion, yes I think, it is the same.
Thanks!

**Comment by marionf** [comment] 2019-02-14 14:05
Duplicate of https://github.com/PrestaShop/ps_mbo/issues/83

**Closed as completed by marionf** 2019-02-14 14:05 UTC
Labels: Bug, Minor, Duplicate, MBO, 1.7.5.1
