### ISSUE TITLE
Attributes sorting - not in modal used when creating combination

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33605] opened 2023-08-11 14:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On PrestaShop 8.1.0, when using attributes to create product combinations, I have changed the order/poistion of attribute values, but this order is not displayed in the modal when creating combinations:

[issue_33605.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/d33e7684-71b7-439e-a2c8-c9d3a7bd45c5)

### Expected behavior

As a user, I would expect the desired/configured sorting of the attribute values to be reflected everywhere, including the modal used for creating product combinations (as it was in Old Product Page, see the attached screenshot below):

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/99e9f268-f9d6-4a36-95a8-28f439e9d8df)

### Steps to reproduce

1. Open PrestaShop 8.1.0 and create some attribute values
2. Sort the attribute values in another order than the database-id
3. Create a product with combinations, and generate combinations for that product
4. Note how the attribute values are not sorted in the way you sorted them in step 2 above

### PrestaShop version(s) where the bug happened

8.1.x & 9.0.x

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment] 2023-08-11 14:55
Hello @LarsGMortensen 

I didn't manage to reproduce you issue with PS 810 


https://github.com/PrestaShop/PrestaShop/assets/31663369/7eaf8235-5c10-4011-949a-9fbdf7036031



Dis I miss smthng ? 
Please check and feedback !

**Comment by MatShir** [comment] 2023-08-11 15:28
The order of Attribute groups works but not the Attributes value from the video

**Comment by sallemiines** [comment] 2023-09-04 13:37
Hello @LarsGMortensen 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by MatShir** [comment] 2023-09-04 13:41
Could you check my comment 🙏 
We need to check the Attribut values order, not the Attribut group order

**Comment by MatShir** [comment] 2023-09-04 13:43
@LarsGMortensen no need for strong word, the team have 100 issue to check daily with updates comment and so on.
We will try to reproduce it ;)

**Comment by LarsGMortensen** [comment] 2023-09-04 13:50
> @LarsGMortensen no need for strong word, the team have 100 issue to check daily with updates comment and so on. We will try to reproduce it ;)

@MatShir Fine, I get what you are saying. Of course. But this is not the only time she has been unable to reproduce a simple error, even though others clearly could. And her responses clearly gives me the impression that she is not nearly thorough enough when reading these tickets, which is especially sad if she actually has the power to just close tickets - because then it is effectively hurting the product.

**Comment by Robin-Fischer-PS** [comment] 2023-09-04 14:39
Hi @LarsGMortensen :)
I understand your frustration, but as Mateus was saying, we deal with a lot of issues a day, mistakes and misunderstandings can happen, even if we work every day to reduce them as much as possible.
Anyway, we like your involvement in the project lately. Let's be civilized and improve the software together 😉

**Comment by sallemiines** [comment] 2023-09-06 09:38
Hello @LarsGMortensen 

Thanks for your patience and understanding :pray: 
Indeed the attributes values are ordered by id not position, see the attached screen record below:

[issue_33605.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/d33e7684-71b7-439e-a2c8-c9d3a7bd45c5)

It's a regression on New Product Page V2 as it works on old Product Page, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/99e9f268-f9d6-4a36-95a8-28f439e9d8df)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by LarsGMortensen** [comment] 2023-09-06 10:08
Hi @sallemiines 
Thank you for the update.
I will happily try to fix it if you can point me in the direction of which script that does the call/SQL-request? :)

**Comment by jolelievre** [comment] 2023-09-06 12:54
Hi @LarsGMortensen 

here's a PR with the fix and updated behat tests https://github.com/PrestaShop/PrestaShop/pull/33860
Next time try and remain more polite with the people who work on making the project better please ^^

**Closed as completed** 2023-09-08 09:15 UTC
Labels: Bug, Minor, BO, Attributes, Combinations, Verified, 8.1.x, Products Page
