### ISSUE TITLE
Prestashop1.7 facet/filter total product

### ISSUE THREAD

**Issue by julieLOM** [PrestaShop/PrestaShop#10255] opened 2018-09-03 12:52 UTC
Hello everybody,
Regarding the total products by filter (see screenshot)
When I select two filters the total between brackets of the other filters is incorrect 

One filter OK
![capture1](https://user-images.githubusercontent.com/35373960/44987808-caf0ec80-af88-11e8-95df-d3c0e4977cf3.png)

Two filters = incorrect total
![capture2](https://user-images.githubusercontent.com/35373960/44987826-df34e980-af88-11e8-8bce-8b7ed2840092.png)

thanks for your anwer

**Comment by khouloudbelguith** [comment] 2018-09-03 13:30
Hi @julieLOM,

We have just released a new version for the ps_facetedsearch.
https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v2.2.0
Thanks to check the issue with it & feedback.

Best regards, Khouloud

**Comment by julieLOM** [comment] 2018-09-03 16:50
Hello @Khouloud 
an exemple http://wit.kaiman.fr/2-accueil?q=Frame+Size-Lign%C3%A9-Tshirt
we can see "porcelaine(5)" but we have 4 products in total

thanks for your answer

**Comment by khouloudbelguith** [comment] 2018-09-03 16:55
Hi @julieLOM,

Using the porcelaine filter, we have 5 products in the total
![image](https://user-images.githubusercontent.com/16067358/44996901-d1905b80-afaa-11e8-9fe5-5781033c7616.png)


Best regards, Khouloud

**Comment by julieLOM** [comment] 2018-09-03 17:16
when I select a filter, others calculates the products quantity between the two bracket
example: when I select "laine" filter, the filter "porcelain" calculates the products quantity for it
http://wit.kaiman.fr/2-accueil?q=Frame+Size-Laine


but when i select two filters, the number between the bracket display the total of products without calcul
http://wit.kaiman.fr/2-accueil?q=Frame+Size-Laine-Lign%C3%A9

really really really sorry for my english
but thanks for your help

**Comment by khouloudbelguith** [comment] 2018-09-04 10:27
Hi @julieLOM,

Thanks for this clarifications.
I manage to reproduce this issue with the last version 1.7.4.2 & the Faceted search module v2.2.0 - by PrestaShop
The quantity of the total product is incorrect when we select two options from one filter.
https://drive.google.com/file/d/1i4-AVrNC4HpUKHzfRK3Fo_9q_1s-ZhJU/view
We will see how to fix it.

Best regards, Khouloud

**Comment by julieLOM** [comment] 2018-09-04 14:20
Hi @khouloudbelguith 

thanks for all
keep me posted

**Comment by ghost** [comment] 2018-09-12 13:49
Yep. Just notticed that bug. 
Also "Filter result limit" not working

**Comment by khouloudbelguith** [comment] 2018-09-12 13:53
Hi @PrestaShark,

This issue will be fixed in this ticket: #10160 

Best regards, Khouloud9813

**Comment by ghost** [comment] 2018-10-01 11:34
Hi. Any news on this issue?

**Comment by ghost** [comment] 2018-10-08 10:23
Module right now is completely unusable. Shows not available attributes, quantities...

**Comment by ghost** [comment] 2018-10-15 09:24
Bump? Any news? My customers are real pissed!

**Comment by khouloudbelguith** [comment] 2018-10-15 11:08
@PrestaShark, the issue is still in our bug roadmap, it is added to the **TO DO** list bug.

**Comment by marionf** [comment] 2019-05-28 15:56
Fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/72

**Closed as completed** 2019-06-07 14:11 UTC
Labels: Bug, Minor, FO, Modules, Faceted search, Fixed, 1.7.4.2
