### ISSUE TITLE
Bad logo position for invoices in RTL languages - 1.7.8.x

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#27500] opened 2022-01-27 21:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Screen Shot 2022-01-27 at 3 03 45 PM](https://user-images.githubusercontent.com/20775532/151443541-824f4c5b-3d48-4c90-a344-9d7e9b4677c6.png)

In RTL languages like Arabic, invoice logo is out of the view. May be a regression, I checked it's okay on 1.7.7.x. 

### Steps to reproduce

1- Add RTL lang to shop (like arabic)
2- place an order in RTL language to get email -  in BO change your panel's language to that RTL lang.
3- Download the invoice

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by khouloudbelguith** [comment] 2022-01-28 11:46
Hello @samberrry,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27265.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you!

**Comment by khouloudbelguith** [comment] 2022-01-28 11:46
Duplicate of #27265

**Closed as completed by khouloudbelguith** 2022-01-28 11:46 UTC
Labels: Bug, Duplicate, Invalid

**Comment by samberrry** [comment] 2022-01-28 15:37
@khouloudbelguith Hi, sorry I could not find it.
Thanks
