### ISSUE TITLE
Tax label always visible in shipping method and cart summary

### ISSUE THREAD

**Issue by fredoche1810** [PrestaShop/PrestaShop#24308] opened 2021-05-03 09:51 UTC
Hello,
I don't think this bug is only for the version 1.7.7.3 but also for the previous versions.
In B2C, when the customer is outside the European union, Prestashop don't show and apply the VAT on the products.
That's correct.
But when you have to select the shipping method, or on the cart summary on the right the label VAT included ("TTC") is visible or the taxes aren't included in the price ...
On the products, the label disappears due to the config of the country "Show label" YES/NO
![Capture](https://user-images.githubusercontent.com/13088049/116862789-90422500-ac05-11eb-8177-60dc2fb984b2.PNG)

So if I'm right, the label has to disappear also in the selection of the shipping method and in the summary of the cart.
Thanks in advance,

**Comment by hibatallahAouadni** [comment] 2021-05-03 10:44
Hello @fredoche1810 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23131 (#24257)
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-03 10:44
Duplicate of #23131

**Closed as completed by hibatallahAouadni** 2021-05-03 10:44 UTC
Labels: Duplicate
