### ISSUE TITLE
Errors and warnings from Google Search Console 

### ISSUE THREAD

**Issue by apero-zero** [PrestaShop/PrestaShop#19998] opened 2020-06-30 08:34 UTC
Google Search Console send me errors and warnings nearly every day. And my website is punished, it is at the end of the research, nobody can find me in the search engines.

**Screenshots**
![Captura](https://user-images.githubusercontent.com/67629635/86103624-48baac00-babd-11ea-933d-26e9eb1431d3.JPG)
![Captura1](https://user-images.githubusercontent.com/67629635/86103639-4ce6c980-babd-11ea-9e5f-fd7e8d0d562a.JPG)

**Comment by Progi1984** [comment] 2020-06-30 08:59
Dear @apero-zero ,Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. Read more about how we expect the issues to be handled: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.Thank you

**Comment by apero-zero** [comment] 2020-06-30 09:39
What else do you need to help me?

**Comment by SimonGrn** [comment] 2020-06-30 09:53
Hello @apero-zero,

your report is empty. Please follow the guidelines from @Progi1984 's comment.

Thank you for your understanding.

**Comment by colinegin** [comment] 2020-06-30 11:55
I reopen this issue as I was in contact with email with @apero-zero, he sent me some screenshots that I just added to the description.

@apero-zero please note that to ensure we are able to test and reproduce the errors you are facing we need a clear description of it, steps to reproduce, etc.

**Comment by colinegin** [comment] 2020-06-30 11:57
It's actually quite weird when I click on edit I see all the description, but when clicking on save I still have "no description provided"... I add all information here then :

****************************
Google Search Console send me errors and warnings nearly every day. And my website is punished, it is at the end of the research, nobody can find me in the search engines.

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
![Captura](https://user-images.githubusercontent.com/67629635/86103624-48baac00-babd-11ea-933d-26e9eb1431d3.JPG)
![Captura1](https://user-images.githubusercontent.com/67629635/86103639-4ce6c980-babd-11ea-9e5f-fd7e8d0d562a.JPG)



If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by rdy4ever** [comment] 2020-07-01 12:52
Hi @apero-zero 
You website is indexed in google, you can see indexed pages [here](https://www.google.com/search?biw=1920&bih=969&ei=I4b8XuuaNdHJrgTHsbrYDw&q=site%3Aapero-zero.com&oq=site%3Aapero-zero.com&gs_lcp=CgZwc3ktYWIQDFAAWABgoQ1oAHAAeACAAQCIAQCSAQCYAQCqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwiruMOui6zqAhXRpIsKHceYDvs4MhDh1QMIDA).
As you are using a custom theme, you should contact the theme's developer in order to fix the validation errors. However, SEO is a difficult domain and just fixing those errors doesn't mean you will rank higher in the search results. To improve your SEO, you need to hire a SEO expert to work on your site.

**Comment by apero-zero** [comment] 2020-07-01 16:44
I've already contacted the theme's developer but they told me that the errors comes from your classic theme...

**Comment by rdy4ever** [comment] 2020-07-02 08:45
> I've already contacted the theme's developer but they told me that the errors comes from your classic theme...

Your validation errors are related to Review snippets. Classic theme doesn't come with review functionality by default, so you must be using a module to implement reviews (either the [free one from Prestashop](https://github.com/PrestaShop/productcomments) or another one from addons). The problem is caused then by the review module you are using.
However, these validation errors shouldn't affect your Google ranking (position), but Google will not show rich results for your site if you don't fix them.  So, even if you fix them, there's no guarantee you will get better search ranking if you don't implement a healthy SEO strategy.

**Comment by SimonGrn** [comment] 2020-07-02 09:26
Thank you @rdy4ever and @apero-zero,

since the issues are not related to Classic Theme or the Core, we advise you to follow @rdy4ever 's suggestion and either contact the developer of the module or your theme developer with the information above.

I'll close this ticket, but note that you can always create a new one if further information pops up. Thank you!

**Closed as completed by SimonGrn** 2020-07-02 09:26 UTC
Labels: No change required
