### ISSUE TITLE
Constant error 500 localhost

### ISSUE THREAD

**Issue by marchspa** [PrestaShop/PrestaShop#12117] opened 2019-01-10 23:03 UTC
**Describe the bug**
While i try to install any module from module manager, both from marketplace and not official i get this error:

(1/1) ContextErrorExceptionWarning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
--
in UnitOfWork.php line 2636
at ErrorHandler->handleError(2, '"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?', 'C:\\xampp\\htdocs\\prestashop\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php', 2636, array('class' => 'Doctrine\\ORM\\UnitOfWork', 'e' => 32767, 'file' => 'C:\\xampp\\htdocs\\prestashop\\vendor\\composer/../doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php', 'wasCached' => false))in DebugClassLoader.php line 144
at require()in DebugClassLoader.php line 144
at DebugClassLoader->loadClass('Doctrine\\ORM\\UnitOfWork')
at spl_autoload_call('Doctrine\\ORM\\UnitOfWork')in EntityManager.php line 160
at EntityManager->__construct(object(Connection), object(Configuration), object(ContainerAwareEventManager))in EntityManager.php line 850
at EntityManager::create(object(Connection), object(Configuration))in appDevDebugProjectContainer.php line 1311
at appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()in Container.php line 306
at Container->get('doctrine.orm.default_entity_manager')in ManagerRegistry.php line 48
at ManagerRegistry->getService('doctrine.orm.default_entity_manager')in AbstractManagerRegistry.php line 231
at AbstractManagerRegistry->getManagers()in ProxyCacheWarmer.php line 49
at ProxyCacheWarmer->warmUp('C:\\xampp\\htdocs\\prestashop\\var\\cache\\dev')in CacheWarmerAggregate.php line 52
at CacheWarmerAggregate->warmUp('C:\\xampp\\htdocs\\prestashop\\var\\cache\\dev')in Kernel.php line 680
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request), 1, false)in index.php line 88

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: Apache/2.4.37 (Win32) OpenSSL/1.1.1a PHP/7.3.0
Versión del cliente de base de datos: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 401a40ebd5e281cf22215acdc170723a1519aaa9 $
extensión PHP: mysqliDocumentación curlDocumentación mbstringDocumentación
Versión de PHP: 7.3.0

**Comment by marchspa** [comment] 2019-01-10 23:03
And i get random error 500 at all times as well.

**Comment by khouloudbelguith** [comment] 2019-01-11 08:04
Hi @marchspa,

PrestaShop is not compatible with PHPv7.3.0.
We recommend that you run your PrestaShop install on the latest version of PHP. PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 to 1.7.5 is compatible with PHP 7.2.
Thanks to change the version of PHP, check & feedback.

**Comment by marchspa** [comment] 2019-01-11 11:01
Hi @khouloudbelguith My php version is now 7.2.13 , see screenshot below from my xampp

![image](https://user-images.githubusercontent.com/33666598/51030060-01fa8e80-1577-11e9-9e65-1c6f0b6eddc6.png)

I still get errors but now while i access to my backoffice

Please advice

**Comment by khouloudbelguith** [comment] 2019-01-11 11:05
@marchspa, could you please navigate to your BO => Advanced Parameters => Information & provide us your Sever information.
Thanks!

**Comment by marchspa** [comment] 2019-01-11 11:10
Here it is: 
![image](https://user-images.githubusercontent.com/33666598/51030503-62d69680-1578-11e9-9fdf-3841e332ce19.png)

I tried to install a module and no luck

**Comment by marchspa** [comment] 2019-01-11 11:30
@khouloudbelguith does this #12120 has something to do? because i see similarities, should i use ps 1.7.4 while 1.7.5 gets php compatibility fixed?

**Comment by khouloudbelguith** [comment] 2019-01-11 11:41
@marchspa, if you apply those fixes, your issue is fixed?
Thanks to check & feedback.

**Comment by marchspa** [comment] 2019-01-11 12:42
I shall try to apply it and will let you know

**Comment by khouloudbelguith** [comment] 2019-01-11 13:13
@marchspa, thanks!
Waiting for your feedback.

**Comment by marchspa** [comment] 2019-01-11 14:53
I applied the change, i was able to upload most of the modules i wanted but then when i try to install a non official module: 
![image](https://user-images.githubusercontent.com/33666598/51040942-80672880-1597-11e9-8b86-cb19214621ba.png)

**Comment by marchspa** [comment] 2019-01-11 14:54
at least it didn't break my entire enviroment xD

**Comment by khouloudbelguith** [comment] 2019-01-11 15:05
@marchspa, what is the exact name of the module did you tried to install it?
Have you tried to contact the module author about the issue?
Thanks!

**Comment by marchspa** [comment] 2019-01-11 15:15
All modules are from mypresta.eu

Captcha
European law cookies
html box 
products on cms
vertical block categories

I'll contact the author.

My guess is these modules aren't for ps 1.7.5 but could work for previous 1.7 versions

Official modules works just fine but now if i go to my frontpage:

![image](https://user-images.githubusercontent.com/33666598/51042240-8f030f00-159a-11e9-9228-b67c56fa28e2.png)

**Comment by khouloudbelguith** [comment] 2019-01-11 15:26
@marchspa, could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by marchspa** [comment] 2019-01-11 15:29
i restarted apache and seems to work now. I also installed the captcha module and allows me to configure it. I will continue to test everything.

My guess is this issue is resolved and the ticket i referenced helped a lot.

Thanks for your help @khouloudbelguith

**Comment by khouloudbelguith** [comment] 2019-01-11 16:20
@marchspa, could you please provide me the module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by marchspa** [comment] 2019-01-11 16:21
I'll share you the link via drive, is it ok?

**Comment by khouloudbelguith** [comment] 2019-01-11 16:24
@marchspa, ok.

**Comment by marchspa** [comment] 2019-01-11 16:26
sent

**Comment by khouloudbelguith** [comment] 2019-01-11 16:29
@marchspa, thanks for these modules.
I tried to install all those modules with PrestaShop 1.7.5.0 (fresh installation without any modifications) & PHP7.2 & all those modules are installed without issues.
![image](https://user-images.githubusercontent.com/16067358/51046488-79a3da00-15c6-11e9-96d2-f579c11130ac.png)
Thanks!

**Comment by marchspa** [comment] 2019-01-11 16:31
then what is wrong with my installation? i'm running xampp. Does it has anything to do?

**Comment by khouloudbelguith** [comment] 2019-01-11 16:36
@marchspa, could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks!

**Comment by marchspa** [comment] 2019-01-11 16:42
Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.

i'm running on local, i'll try anyway

**Comment by khouloudbelguith** [comment] 2019-01-11 16:45
@marchspa, ok!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-02-11 10:55
Hi @marchspa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-11 10:55 UTC
Labels: No change required, Module manager, 1.7.5.0
