### ISSUE TITLE
Amount paid is no longer validated when creating an order

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#15834] opened 2019-10-04 11:30 UTC
**Describe the bug**
When the amount paid sent in `validateOrder()` doesn't match with order total, order is created with state sent as a parameter (usually `Configuration::get('PS_OS_PAYMENT')`) instead of `Configuration::get('PS_OS_ERROR')` as in PS 1.7.5.2.

Since commit https://github.com/PrestaShop/PrestaShop/commit/57271b54b33503a31a103e95050f110f66c43dec#diff-0f162f4cf098397033f06b1cced01745, validation
```
// Amount paid by customer is not the right one -> Status = payment error	
// We don't use the following condition to avoid the float precision issues : http://www.php.net/manual/en/language.types.float.php	
// if ($order->total_paid != $order->total_paid_real)	
// We use number_format in order to compare two string	
if ($order_status->logable && number_format($cart_total_paid, _PS_PRICE_COMPUTE_PRECISION_) != number_format($amount_paid, _PS_PRICE_COMPUTE_PRECISION_)) {	
    $id_order_state = Configuration::get('PS_OS_ERROR');	
}
```

has been moved to `createOrderFromCart()`, so initial order state set in `validateOrder()` takes `$id_order_state` and is not changed to `Configuration::get('PS_OS_ERROR')`.

```
// Set the order status
$new_history = new OrderHistory();
$new_history->id_order = (int) $order->id;
$new_history->changeIdOrderState((int) $id_order_state, $order, true);
$new_history->addWithemail(true, $extra_vars);
```

**To Reproduce**
This can only be reproduced with an external payment method. Please contact me at info@idnovate.com or let me know your mail address so I can send you a module and credentials to test it.

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-10-04 11:34
Hi @idnovate,

Thanks for your report.
Thanks to follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/14648#issuecomment-515520400) of our lead developer about the payment module issues with PS1.7.6.
Thanks to check & feedback.

**Comment by idnovate** [comment] 2019-10-04 12:16
> Hi @idnovate,
> 
> Thanks for your report.
> Thanks to follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/14648#issuecomment-515520400) of our lead developer about the payment module issues with PS1.7.6.
> Thanks to check & feedback.

Not related.

1. Please install this module in PS 1.7.6.1: 
[redsysoficial.zip](https://github.com/PrestaShop/PrestaShop/files/3690435/redsysoficial.zip)


2. Configure it this way:
![image](https://user-images.githubusercontent.com/15104724/66206566-bcf02c80-e6b0-11e9-94d1-7aa72fdcf6ae.png)

_(copy-paste)
Commerce: 327234688
Key: sq7HjrUOBfKmC576ILgskD5srU870gJ7_

3. Open frontoffice and add a product
4. Open a **new window** and do the checkout, select `Payment by card` and push `Pay`
5. When you are about to pay with card and **before** you introduce the payment card,

![image](https://user-images.githubusercontent.com/15104724/66206664-00e33180-e6b1-11e9-9047-697097ee124d.png)


go to the first window and add a new product to the cart. Now you will have 2 products in the cart.

6. Now, pay with this card:
_4548812049400004
12/20
123
2nd code: 123456_

7. Payment accepted. Check your orders. You get a **validated order** and you have only paid for 1 product

![image](https://user-images.githubusercontent.com/15104724/66206852-954d9400-e6b1-11e9-92a4-500df28e4d3e.png)


This is because the issue detailed in first message. Until now any payment module take care of it as PrestaShop checks it.

**Comment by khouloudbelguith** [comment] 2019-10-04 12:43
@idnovate, I have an error on the FO
![image](https://user-images.githubusercontent.com/16067358/66208361-30943880-e6b5-11e9-912a-d82f12dd66b0.png)
Here's my configuration => similar to yours
![image](https://user-images.githubusercontent.com/16067358/66208428-53265180-e6b5-11e9-81eb-2f36c8e7072b.png)

Thanks to check & feedback.

**Comment by idnovate** [comment] 2019-10-04 12:47
This error appeared after you insert the card?

**Comment by idnovate** [comment] 2019-10-04 12:49
Please test it in a store accessible from the outside without maintenance mode to receive the payment confirmation.

**Comment by khouloudbelguith** [comment] 2019-10-04 12:56
@idnovate,
>This error appeared after you insert the card?

No, before
https://drive.google.com/file/d/1MkRDWCCc30tVH4ANzQh-2kHx9AoYrYJy/view
I tried with this shop also: http://optimal-scarf.machine-shuffle.prestashop.net/en/: store accessible from outside & without maintenance mode.
Same issue

Thanks!

**Comment by idnovate** [comment] 2019-10-04 13:00
Error SIS0063 is "Card not available". Why is it submitting empty card form? Do you have any extension doing so?

You should be able to introduce the card I sent you :) Who's submitting the form? This is the first time I see this.

**Comment by khouloudbelguith** [comment] 2019-10-04 13:02
@idnovate, no, I don't have any extension.
Did you try with the shop that I sent you?

Thanks!

**Comment by idnovate** [comment] 2019-10-04 13:04
Yes, and the form remains quiet until I introduce the card.

Could you try in private mode with Spanish VPN?

**Comment by khouloudbelguith** [comment] 2019-10-04 13:06
@idnovate, yes, in fact, I'm using a VPN while testing this shop.

Thanks!

**Comment by idnovate** [comment] 2019-10-07 08:05
Still same problem today?

**Comment by idnovate** [comment] 2019-10-07 08:12
You can also try with Paypal, same problem appears.

**Comment by khouloudbelguith** [comment] 2019-10-07 11:04
@idnovate, Yes, I tried today with the redsys module & the same issue.
With Paypal module v5.0.1, I did not manage to reproduce the issue.
I attached a screen record
https://drive.google.com/file/d/1C82pAX5eTVrJagLRsyslVhVS6L0Ex9Lh/view
Thanks!

**Comment by idnovate** [comment] 2019-10-07 11:13
_Please note that PayPal screen has not been recorded so I couldn't see all the process._

According with the data you sent me, you should have paid 43,20€ in PayPal but final **accepted** cart is 57,48€.

**Comment by khouloudbelguith** [comment] 2019-10-07 11:32
@idnovate, I added the second product with price =14.28 Euro.
https://drive.google.com/file/d/1NzffspHOOxMziUA0X8UB6fdTjEcMc1Kz/view
Thanks!

**Comment by idnovate** [comment] 2019-10-07 11:40
Is correct what you do and you have reproduced the issue.

You have only paid 34,80€ for a cart of 49,08€ because information to Paypal have been sent before you added the 2nd product. 
Please do the same test with PS 1.7.5.2 and order should be created with "Payment error" status.

**Comment by khouloudbelguith** [comment] 2019-10-07 11:57
@idnovate, no, it is the same with PS1.7.5.2.
I have two products in the order
![image](https://user-images.githubusercontent.com/16067358/66309385-d0e29b00-e909-11e9-9dc9-95498306a749.png)
https://drive.google.com/file/d/1la9Uf32yk28bQKD-8a62acS4_kRZz7Az/view
Thanks!

**Comment by idnovate** [comment] 2019-10-08 07:44
Can you give me access to a PS 1.7.6.1 store FO and BO?

**Comment by khouloudbelguith** [comment] 2019-10-08 09:05
@idnovate, Yes!
Link of the BO: http://beefy-machine.machine-shuffle.prestashop.net/admin-dev
Email address: test@prestashop.com
Password: 123456789
Link of the FO: http://beefy-machine.machine-shuffle.prestashop.net/en/
I tried with this shop with redsys: the same issue.
I tried with Paypal => OK, I have two products.

Thanks!

**Comment by idnovate** [comment] 2019-10-08 09:10
Thanks!

I have reproduced the issue with "Redsys". You are paying for one product but purchased 2 and any error appear.

Is it possible for you to check why Redsys is submitting the form automatically when it loads, before you introduce the card? I suspect is related with your environment/computer.

**Comment by khouloudbelguith** [comment] 2019-10-08 10:21
@idnovate, The previous shop is erased.
Can you please provide me a screen record with this shop(same credentials)
http://knowledgeable-hill.machine-shuffle.prestashop.net/admin-dev

Thanks!

**Comment by idnovate** [comment] 2019-10-08 10:33
Here:
[screencast-inmediashop.com-2019.10.02-15_31_45.zip](https://github.com/PrestaShop/PrestaShop/files/3701968/screencast-inmediashop.com-2019.10.02-15_31_45.zip)

**Comment by idnovate** [comment] 2019-10-08 10:33
If you want me to provide with a PS 1.7.5.2 I can test the same and you will see like order is created with "Payment error" status.

**Comment by khouloudbelguith** [comment] 2019-10-08 11:29
@idnovate, yes, it is the same as what I reproduce with PS1.7.5.2 & PS1.7.6.1 when using the Paypal module.
The payment is accepted with the correct amount & we have two products in the order.
Ps1.7.5.2 & PS1.7.6.1 => same behavior.

Thanks!

**Comment by idnovate** [comment] 2019-10-08 11:38
The payment is accepted but the information is incorrect, **you have only paid for 1 product**.

**Comment by khouloudbelguith** [comment] 2019-10-08 11:46
@idnovate, yes, but before submitting and validate the order, you added a product to your cart.
So, all the data are updated, the data sent to the payment method is updated & it is the same behavior that I manage to reproduce with PS1.7.5.2 also( there is no payment error).
>Please do the same test with PS 1.7.5.2 and order should be created with "Payment error" status.

It is OK with PS1.7.5.2, There is no payment error., as described in my last comment: https://github.com/PrestaShop/PrestaShop/issues/15834#issuecomment-538974443

Can you please provide a screen record with PS1.7.5.2.

Thanks

**Comment by idnovate** [comment] 2019-10-08 12:59
Is it easy and quick for you to create it for me? Just to have a fresh installation in your server, so we can test it in the same environment.

**Comment by khouloudbelguith** [comment] 2019-10-08 13:29
@idnovate, sorry but with this server, I'm allowed to create only shop v1.7.6 & 1.6.1.24.

Thanks for your understanding!

**Comment by idnovate** [comment] 2019-10-08 15:13
Done, with a fresh 1.7.5.2
[screencast-inmediashop.com-2019.10.02-15_31_45.zip](https://github.com/PrestaShop/PrestaShop/files/3703186/screencast-inmediashop.com-2019.10.02-15_31_45.zip)

**Comment by khouloudbelguith** [comment] 2019-10-08 15:32
@idnovate, thanks for your feedback.
The Paypal module, have you The Payment error also with PS1.7.5.2?

Thanks!

**Comment by idnovate** [comment] 2019-10-09 07:05
No, because Paypal use a custom `validateOrder()` function, not from `PaymentModule` class. So this issue would happen with any payment method that uses core `validateOrder()` function.

**Comment by khouloudbelguith** [comment] 2019-10-09 11:00
@idnovate, So your module builds a [FrontController](https://devdocs.prestashop.com/1.7/modules/concepts/controllers/front-controllers/) to handle validation instead of a custom endpoint like `validation.php`?
Thanks!

**Comment by idnovate** [comment] 2019-10-09 11:03
Yes

**Comment by eternoendless** [comment] 2019-10-09 16:05
If I got it right, before 1.7.6.0, this block in `validateOrder()` was able to change the value of `$id_order_state` in some circumstances: https://github.com/PrestaShop/PrestaShop/commit/57271b54b33503a31a103e95050f110f66c43dec#diff-0f162f4cf098397033f06b1cced01745L403-L405

This value is reused several lines later in `validateOrder()`: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L571

However, the aforementioned block has been extracted into a new method `createOrderFromCart()`, the `$id_order_state` is no longer changed in the context `validateOrder()`, which is a problem.

@idnovate could you please confirm?

**Comment by idnovate** [comment] 2019-10-10 07:03
@eternoendless Exactly. This is the code moved to another function https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/classes/PaymentModule.php#L396-L402

**Comment by Prestaworks** [comment] 2019-11-07 15:40
I can confirm this issue also, it's just as @eternoendless explains it. The issue is in 1.7.6.0 and 1.7.6.1. I think this needs to be fixed quickly as many merchants expects the payment error status to work.

**Comment by khouloudbelguith** [comment] 2019-11-07 15:47
Ping @eternoendless @colinegin @marionf, what do you think? this issue should be fixed in the next patch PS1.7.6.2?

Thanks!

**Closed as completed** 2019-11-12 14:56 UTC
Labels: Bug, Major, Payment methods, Regression, Fixed, 1.7.6.1
