### ISSUE TITLE
Can't finish upgrade from 1.7.4.4 to 1.7.5.0

### ISSUE THREAD

**Issue by sonGramz** [PrestaShop/PrestaShop#11960] opened 2018-12-31 06:13 UTC
**Describe the bug**
I am using bitnami cloud hosting, Prestashop 1.7.4.4

Everything was working fine. I tried to upgrade to 1.7.5.0 and now my installation doesn't work and is full of 500 HTTP errors, including front and back office (luckily I can still access the 1 click upgrade module).

Things I've tried: 
Changing the file permissions of the whole htdocs directory to 777 just to make sure it was not a problem related to file permissions. Same error appears.

Uploading the missing DoctrineQueryBuilderInterface.php file manually, but same error appears.

**To Reproduce**
0. Have version 1.7.4.4. Install 1-click-upgrade module.
1. Go to '1 click upgrade' module.
2. Click on 'Upgrade Prestashop'.
3. All upgraded files finish uploading (apparently). Last lines of lower text box:
Copied /webservice/dispatcher.php.
Copied /webservice/index.php.

4. See this error in the upper text box:

[OK] SQL 1.7.5.0 ALTER TABLE `ps_customer_thread`\n CHANGE `email` `email` varchar(255) NOT NULL<\/div>","\n 
\n [WARNING] SQL 1.7.5.0\n 1060 in ALTER TABLE `ps_stock_available`\n ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`: Duplicate column name 'location'<\/div>"],"nextErrors":["[INTERNAL] \/opt\/bitnami\/apps\/prestashop\/htdocs\/src\/PrestaShopBundle\/Entity\/Repository\/LogRepository.php line 39 - Interface 'PrestaShop\\PrestaShop\\Core\\Grid\\Query\\DoctrineQueryBuilderInterface' not found","[INTERNAL] \/opt\/bitnami\/apps\/prestashop\/htdocs\/src\/PrestaShopBundle\/Entity\/Repository\/LogRepository.php line 39 - Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load interface \"DoctrineQueryBuilderInterface\" from namespace \"PrestaShop\\PrestaShop\\Core\\Grid\\Query\".\nDid you forget a \"use\" statement for \"PrestaShop\\PrestaShop\\Core\\Grid\\Query\\DoctrineQueryBuilderInterface\"?\n#0 {main}"],"error":true,"next":"error"}"

5. Prestashop version still showing as 1.7.4.4-1 and now multiple 500 HTTP errors are present in the BO and frontend.

Server information Linux #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 
Server software version: Apache 
PHP version: 7.1.24 
Memory limit: 128M 
Max execution time: 300 
Upload Max File size: 100M 

MySQL version: 5.7.24 
MySQL engine: InnoDB 
MySQL driver: DbPDO 

Please help me! Please. I was confident the upgrade would work, and now my installation is unusable. I tried using the rollback function but the 500 HTTP errors remain! My shop is offline just because I wanted to upgrade and be able to move the position of products.

**Comment by khouloudbelguith** [comment] 2018-12-31 10:35
Hi @sonGramz,

What is the exact version of the module 1-click upgrade?

Thanks,
Khouloud

**Comment by sonGramz** [comment] 2018-12-31 11:21
1-Click Upgrade 
v4.5.1 - by PrestaShop 

Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-31 13:31
Hi @sonGramz,

I did not manage to reproduce the issue.
I have made an upgrade from PS 1.7.4.4 to PS 1.7.5.0 with the module 1-click upgarde V4.5.1 and is done successfully.
Thanks to check and feedback.

Thanks,
Khouloud

**Comment by cy-altern** [comment] 2018-12-31 14:50
I have the same problem with this error message:
"Error while copying file \app\.htaccess
Error when trying to upgrade file \app\.htaccess.
[INTERNAL] D:\applis_web\prestashop_174\modules\autoupgrade\classes\TaskRunner\Upgrade\UpgradeFiles.php line 192 - copy(D:\applis_web\prestashop_174\app\.htaccess): failed to open stream: Permission denied"
**Note that the all files and directorys are in RWX mode (666 / 2777)**

And, AS USUAL WITH THIS F***G AUTOUPGRADE MODULE, the "Restaure 1.7.4.4_..." command FAIL with the message:
"zip->extractTo(): unable to use D:\applis_web\prestashop_174 as extract destination.
[ERROR] D:/applis_web/prestashop_174/_install\sandbox\.htaccess has not been unzipped: write_error
Unable to extract file D:\applis_web\prestashop_174\console_krakatoa\autoupgrade\backup\auto-backupfiles_V1.7.4.4_20181231-144244-7446a576.zip into directory D:\applis_web\prestashop_174."

Technicals infos:
prestashop 1.7.4.4
autoupgrade module version: 4.5.1
PHP version 7.0 on windows 10 x64

**Comment by sonGramz** [comment] 2018-12-31 17:58
@khouloudbelguith Thanks I understand. But please, do you have any suggestions on how I may solve this problem? I have not made any modifications to the original code. :(

**Comment by khouloudbelguith** [comment] 2019-01-02 10:00
Hi @sonGramz,

It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.0
The solution is to add the missing columns to your database schema.
You can find the schema changes from 1.7.4.3 to 1.7.5.0 by looking at this file: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/install-dev/upgrade/sql/1.7.5.0.sql

You can find the full schema for 1.7.5.0 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by Quetzacoalt91** [comment] 2019-01-02 10:32
> [INTERNAL] D:\applis_web\prestashop_174\modules\autoupgrade\classes\TaskRunner\Upgrade\UpgradeFiles.php line 192 - copy(D:\applis_web\prestashop_174\app.htaccess): failed to open stream: Permission denied"

Interesting, it seems a anti slash has been escaped / forgotten. We'll dig into this. However ...

> And, AS USUAL WITH THIS F***G AUTOUPGRADE MODULE, [...]

As this kind of comment absolutely doesn't help, you may keep them for you.

**Comment by khouloudbelguith** [comment] 2019-02-05 09:47
Hi @sonGramz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-05 09:47 UTC
Labels: Autoupgrade, No change required
