### ISSUE TITLE
BO Cannot edit customer

### ISSUE THREAD

**Issue by metacreo** [PrestaShop/PrestaShop#29924] opened 2022-10-07 06:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

BO Customers. On click Edit page not opened.
In debug mode:

![ps_out_of_mem](https://user-images.githubusercontent.com/543458/194487176-3312fe3d-e027-4716-8cbf-43ae7aa7476e.png)

in debug log too many of:

`/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php:66)"} []
[2022-10-07 09:30:42] php.INFO: User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 at /www/src/Adapter/Configuration.php:418)"} []
[2022-10-07 09:30:42] php.INFO: User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 at /www/src/Adapter/Configuration.php:418)"} []
[2022-10-07 09:30:42] php.INFO: User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 at /www/src/Adapter/Configuration.php:418)"} []
[2022-10-07 09:30:42] php.INFO: User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 at /www/src/Adapter/Configuration.php:418)"} []
[2022-10-07 09:30:42] php.INFO: User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 at /www/src/Adapter/Configuration.php:418)"} []
[2022-10-07 09:30:42] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2022-10-07 09:30:42] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []`

### Expected behavior

Customer edit page may works.

### Steps to reproduce

Sign as customer.
Make 500+ orders with 1-5 product per order.
Login to BO.
Go to Customers and click edit on customer who make 500+ orders.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3 on dedicated server

### If your bug is related to a module, specify its name and its version

no modules, all stats modules disabled

**Comment by hibatallahAouadni** [comment] 2022-10-07 11:09
Hello @metacreo 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25683. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-10-07 11:09
Duplicate of #25683

**Closed as completed by hibatallahAouadni** 2022-10-07 11:09 UTC
Labels: Bug, Duplicate, Invalid
