### ISSUE TITLE
Myaccount page doesnt follow module hook position exceptions

### ISSUE THREAD

**Issue by psydomin** [PrestaShop/PrestaShop#22395] opened 2020-12-13 02:53 UTC
#### Describe the bug

If you hook a module and set the myaccount page as an exception (so that it doesnt show on myaccount page), that exception wont be respected and the module will still show. As far as I could check, this only happens on the myaccount page and happens on all the hooks I tried.

#### Expected behavior

Module should not show on the myaccount page if that page is set as an exception.

#### Steps to Reproduce

1. Hook a module to any hook that exists on the myaccount page
2. Set the myaccount page as an exception (so that the module doesnt show on that page) 
3. Go to the myaccount page
4. Module will still show (Even after clearing cache)

**Screenshots**

![image](https://user-images.githubusercontent.com/12779551/102001839-5328d500-3cee-11eb-959a-fe54a3b846d6.png)

#### Additional information

* PrestaShop version: 1.7.7.0

**Comment by khouloudbelguith** [comment] 2020-12-14 17:22
Hi @psydomin,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/21168 to fix the issue.
It is fixed in the next release 1780.
Your ticket is a duplicate of #19226
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-12-14 17:22
Duplicate of #19226

**Closed as completed by khouloudbelguith** 2020-12-14 17:22 UTC
Labels: Duplicate
