### ISSUE TITLE
Undefined offset notice for customizable product in invoice.product-tab.tpl

### ISSUE THREAD

**Issue by nico159** [PrestaShop/PrestaShop#18837] opened 2020-04-27 10:06 UTC
Hi,
The template invoice.product-tab.tpl is raising an Undefined offset notice when I try to checkout a product which has a customization field

Example of the error in debug mode when I try to checkout a product with a single customizable field of text type
![immagine](https://user-images.githubusercontent.com/152243/80360233-4d75a080-887f-11ea-9925-66b40bc3ce5a.png)

**Comment by PierreRambaud** [comment] 2020-04-27 14:34
Hi @nico159,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
 ...

You don't know how to get this information? Please read the following article:

http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by nico159** [comment] 2020-04-27 16:34
PrestaShop 1.7.6.4, running on php 7.1

**Comment by florine2623** [comment] 2020-04-30 12:24
Hi @nico159 ,
How do you get this error ? Is it when you try to download he invoice of the order from the BO ?
Do you use any modules that override the invoice ?
Thanks!

**Comment by pinkfabb** [comment] 2020-05-04 19:10
Hi,

I would like to save the customization fields when I click to add to cart button in prestashop.

Whenever customer saves his/her custom feild replies.I dont get to see that on my admin panel.

IT dissappears after adding it to the CART. CUstomisation field value doesnt get saved. 

I tried many ways, but I can not manage to find the solution.

Any help ?

Thanks

**Comment by Matt75** [comment] 2020-05-04 19:42
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18186 on develop branch
Lines in branch 1.7.6 are different

**Comment by NeOMakinG** [comment] 2020-08-12 08:49
@PrestaShop/prestashop-qa This should be tested since the smarty upgrade on 1.7.7 and develop branch, in order to close this issue!

**Comment by khouloudbelguith** [comment] 2020-08-12 09:48
Hi @nico159, @NeOMakinG,

It is fixed in the 1.7.7.x branch.
I attached a screen record
https://drive.google.com/file/d/1EYXmI4-AMWXEzU02LQamVqJIn6AVuBMi/view?usp=sharing
I will close the issue since it is fixed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-12 09:48 UTC
Labels: Bug, develop, FO, Product customization, Fixed, PR available, 1.7.6.4
