### ISSUE TITLE
Error when accessing dashboard with debug mode activated

### ISSUE THREAD

**Issue by consochris** [PrestaShop/PrestaShop#11774] opened 2018-12-14 07:43 UTC
**Describe the bug**
When trying to access dashboard, i see the following error when debug mode is activated

**To Reproduce**

**Screenshots**
![chrome_2018-12-14_08-39-36](https://user-images.githubusercontent.com/11958854/49989972-4bf25380-ff7c-11e8-8e1d-72f316ba1aea.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-12-14 08:05
HI @consochris,

You need to disable the option html_purifier on back-office of your shop. Seems that this library is not installed on your server.
How to diasble: BO -> Shop Parameters -> general -> Use HTML purifier library = NO
Thanks to check & feedback.

**Comment by consochris** [comment] 2018-12-14 08:07
I cannot access BO anymore, even with debug mode. How can i deactivate it please?

**Comment by khouloudbelguith** [comment] 2018-12-14 08:09
@consochris, If you can’t access your dashboard, you can still disable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', true);`

… and change it to:

`define('_PS_MODE_DEV_', false);`
Thanks!

**Comment by consochris** [comment] 2018-12-14 08:12
Thanks for your answer. this isn't what i mean. I have activated the debug mode through FTP but even with this, i cannot log in to the BO to change the HTML purifier settings. Can i do this through FTP too?

**Comment by khouloudbelguith** [comment] 2018-12-14 08:19
Hi @consochris,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by consochris** [comment] 2018-12-14 08:21
ok i will work on providing those. 
Can i change change HTML purifier settings using FTP?

**Comment by khouloudbelguith** [comment] 2018-12-14 08:28
@consochris, you need to access to your Database => ps_configuration, you need to search the column where id_configuration = 259, and change value from 1 to 0.
![image](https://user-images.githubusercontent.com/16067358/49991822-8a8b0c80-ff82-11e8-9044-eb9a3ee87ac5.png)
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-14 08:33
@consochris, thanks to disable the HTML purifier from your your Database as described in my last comment, check & feedback.
Also, you have problems with the revsliderprestashop module, thanks to rename this folder using an FTP client, you can find it into the path Project_Folder/modules/revsliderprestashop
Thanks!

**Comment by consochris** [comment] 2018-12-14 08:49
thanks, i have applied the database change and renames the module folder. the error has changed to the following:
![chrome_2018-12-14_09-49-04](https://user-images.githubusercontent.com/11958854/49992893-97f5c600-ff85-11e8-9b75-11c61249458a.png)

**Comment by consochris** [comment] 2018-12-14 09:00
I can access the BO again! though it only works with debug mode activated and not with debug mode off.
Do you know why?

**Comment by khouloudbelguith** [comment] 2018-12-14 09:06
@consochris, as described in your last screenshot, I think it is a problem on your server configuration.
Have you tried to contact your host about this issue?
Thanks to check with him & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-21 10:33
Hi @consochris,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-21 10:33 UTC
Labels: Bug, BO, Dashboard, No change required
