### ISSUE TITLE
FO - A warning "jQuery('#') is not a valid selector" is displayed in the console

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21228] opened 2020-09-30 13:13 UTC
#### Describe the bug

In the FO > When we click on the "Quick View" button, we have a warning

This warning is displayed when we close the popup or when we change Quantity, combinations, select an image
![image](https://user-images.githubusercontent.com/16067358/94689528-458ac280-032f-11eb-94e6-c0f3be137ed4.png)

#### Steps to Reproduce

1. Go to FO
2. Click on the "Quick View", change combinations, select image, change the quantity, close pop up
4. See an error

#### Additional information

* PrestaShop version: 1770rc1build1
* PHP version: 7.1

**Comment by NeOMakinG** [comment] 2020-10-01 13:39
@khouloudbelguith 

I'm completely unable to reproduce it, even by rebuilding every assets

@PrestaShop/prestashop-maintainers can someone try to reproduce too ?

**Comment by khouloudbelguith** [comment] 2020-10-01 13:45
@NeOMakinG, I'm using a docker environment
![image](https://user-images.githubusercontent.com/16067358/94817278-2490a300-03fd-11eb-935f-42211f42def4.png)

Thanks!

**Comment by PierreRambaud** [comment] 2020-10-01 14:10
> @khouloudbelguith
> 
> I'm completely unable to reproduce it, even by rebuilding every assets
> 
> @PrestaShop/prestashop-maintainers can someone try to reproduce too ?

I'm not able to reproduce too

**Comment by Robin-Fischer-PS** [comment] 2020-10-01 14:47
I'm reproducing the error, without using Docker, on RC1 build : 

![image](https://user-images.githubusercontent.com/55688534/94824883-c3b99880-0405-11eb-95cf-c8a8fccaf8ea.png)

**Comment by boubkerbribri** [comment] 2020-10-01 14:49
@PierreRambaud @NeOMakinG 
I was able to reproduce it in the 1.7.7.0 RC1 with php7.2 by clicking on any element that trigger a js script (click on language dropdown or currency dropdown, or carousel.

![image](https://user-images.githubusercontent.com/48441421/94824997-e9df3880-0405-11eb-80da-4d3dc9aabeb9.png)

**Comment by PierreRambaud** [comment] 2020-10-02 14:02
> @PierreRambaud @NeOMakinG
> I was able to reproduce it in the 1.7.7.0 RC1 with php7.2 by clicking on any element that trigger a js script (click on language dropdown or currency dropdown, or carousel.
> 
> ![image](https://user-images.githubusercontent.com/48441421/94824997-e9df3880-0405-11eb-80da-4d3dc9aabeb9.png)

I installed the 1.7.7.0 RC build  (zip file)  I'm still not able to reproduce the issue with or without the debug mode.

**Comment by marionf** [comment] 2020-10-05 12:11
Need more info to be able to reproduce it @SimonGrn

**Comment by Robin-Fischer-PS** [comment] 2020-10-05 12:53
I reproduce this bug with Chrome (Version 85.0.4183.102 (Build officiel) (64 bits)), after fresh install on RC1 build, with PHP 7.2.33.

**Comment by SimonGrn** [comment] 2020-10-05 13:05
I don't reproduce with a fresh install.
- PHP 7.2.33
- Firefox 81.0
- Chrome 85.0.4183.121

Cache emptied, even tried with incognito mode on both browsers.

Since this fantom issue doesn't really interfere with the normal behavior of the page (as far as we know), I suggest we drop it.

**Comment by NeOMakinG** [comment] 2020-10-05 13:16
Well, I was thinking about a chrome extension, but this looks like inside core.js...

**Comment by khouloudbelguith** [comment] 2020-10-05 13:57
Hi!

In my case after new re-install of the previous shop => Issue not reproduced
https://drive.google.com/file/d/1XnZ7G2qmnaRZpfVo9PUbzAPFA8VQ7IAo/view?usp=sharing

Thanks!

**Comment by SimonGrn** [comment] 2020-10-06 10:22
We're not able to reproduce it consistently and there's apparently no consequences so I close it.

**Comment by antoniodalessio** [comment] 2020-10-11 10:47
Check your jquery version with `console.log(jQuery.fn.jquery);` and compare it with a fresh prestashop installation. In 1.7.6 jquery right version is: 2.2.4 but for some reason my version was 3.5. 
I copied themes/Core.js from a fresh installation and work fine. No error displayed at time in any section

**Comment by theGera** [comment] 2021-03-28 02:32
data-target="#" 
is in 
`themes/classic/modules/ps_currencyselector/ps_currencyselector.tpl` 
delete data-target="#"  . working for me

**Comment by Progi1984** [comment] 2021-03-31 06:47
Fixed by #23802

**Closed as completed by Progi1984** 2021-03-31 06:47 UTC
Labels: Bug, Trivial, FO, Regression, Fixed, 1.7.7.x
