### ISSUE TITLE
Simple way to get product's price from product object.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#21686] opened 2020-10-30 11:49 UTC
There is $product -> name, $product -> description but why isn't there $product -> price?
I know there is actually $product -> price but if product has variations as in my case, it displays 0.0000
Product object should have an easy function to get it's minimal price (variation price) that is already formatted according to the store's currency. In past there was Tools:;formatPrice(), now it's removed with Locale::convertPrice() and this method requires to know the currency id, and you have to get somehow the variation price.

There are so many methods to get product's price, with tax, without, with discount, without, etc. but all not formatted. I believe many people would just appreciate to have formatted with currency default (minimal) price as easy as $product -> name.

**Comment by hibatallahAouadni** [comment] 2020-10-30 13:28
hi @grzegorzgit 

your issue is duplicated to this one #21688 and you are the author too. So I'm closing this one.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-10-30 13:28
Duplicate of #21688

**Comment by florine2623** [comment] 2020-10-30 14:32
Hi @grzegorzgit ,
I just need more details about your issue.
When you talk about _product has variations_, do you mean _combinations_ ?
![Capture d’écran 2020-10-30 à 15 30 49](https://user-images.githubusercontent.com/16019289/97717275-ea322880-1ac4-11eb-845a-978f10f6f758.png)

Or do you mean the _impact on price_ that would lead to a _price variation_ :
![Capture d’écran 2020-10-30 à 15 31 23](https://user-images.githubusercontent.com/16019289/97717375-046c0680-1ac5-11eb-85dd-7b38d46585c4.png)

Thanks

**Comment by hibatallahAouadni** [comment] 2020-11-19 10:00
Hello @grzegorzgit ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-19 10:00 UTC
Labels: CO, No change required
