### ISSUE TITLE
Themes without memory

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/PrestaShop#16838] opened 2019-12-17 12:15 UTC
**Is your feature request related to a problem? Please describe.**
When setting a new theme and then returning to the previous one, the positions of the modules and the modules that have been deactivated for the theme used are not recognized.

**Describe the solution you'd like**
I believe this can be solved by storing this preference in a dedicated table. In this way both the positions of the modules and their status would be automatically reset.

**Describe alternatives you've considered**
The alternative could be to let the user choose whether or not he wants to reset the previously set theme settings

I hope this suggestion is taken into consideration and that this useful feature be added soon. 
 
Thanks :wink:

**Comment by khouloudbelguith** [comment] 2019-12-17 12:51
Hi @kenlog,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by dennispw** [comment] 2019-12-17 13:31
Related: https://github.com/PrestaShop/PrestaShop/issues/12933

**Comment by Betafer** [comment] 2020-03-26 11:11
Thanks, for me this is bug not a feature request

**Comment by matks** [comment] 2020-03-27 14:48
It's a feature request though 😉

A bug is a a behavior in the software that is not working as it should. It means there should be a description of "what was expected", and when it was built, a mistake was made, which consequence is "what was expected" and "what was built" are different.

The themes management was never built with the idea of "remember previous preferences" although it's a nice user experience improvement. We could tell it's a limitation, but not a bug.

**Comment by Betafer** [comment] 2020-03-27 14:55
If I am working on a theme and I manage it, and I want to try another one, or put the default prestashop one to understand if there is any error in the theme, it is not that I can lose all the changes.

**Comment by marionf** [comment] 2020-11-05 17:09
Duplicate of #12933

**Closed as completed by marionf** 2020-11-05 17:09 UTC
Labels: Improvement, BO, Duplicate, Theme & logo
