### ISSUE TITLE
en_GB translation of 'Contact' is 'CMS page'

### ISSUE THREAD

**Issue by SeriousKen** [PrestaShop/PrestaShop#18952] opened 2020-05-03 14:19 UTC
When the admin is in en_US the menu for updating contacts is correctly labelled `Contact` but switching to en_GB it ends up labelled `CMS page`. I've tried changing this by editing the translation under `Admin > Navigation > Menu > Contact` but it doesn't change.

![Annotation 2020-05-03 151251](https://user-images.githubusercontent.com/29771532/80916564-5f5cb500-8d51-11ea-95e1-1dc785f5df50.png)

![Annotation 2020-05-03 151346](https://user-images.githubusercontent.com/29771532/80916574-6f749480-8d51-11ea-8830-0ae2055730df.png)

**Comment by Progi1984** [comment] 2020-05-04 07:07
Hi @SeriousKen 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
 ...

You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by SeriousKen** [comment] 2020-05-04 07:29
Prestashop 1.7.6.5 on Linux Ubuntu 18.04.4 LTS with PHP 7.3.17 on a dedicated virtual host installed from the downloaded from https://www.prestashop.com/en/download, there are no errors as the issue is an incorrect translation in the en_GB language file `sf_en_GB.zip` if you extract this file and look at `AdminNavigationMenu.en-GB.xlf` line 128 is

```
<trans-unit id="bbaff12800505b22a853e8b7f4eb6a22" approved="yes">
        <source>Contact</source>
        <target state="final">CMS page</target>
        <note>Line: 47</note>
</trans-unit>
```

and line 10 in `AdminNavigationFooter.en-GB.xlf`

```
<trans-unit id="bbaff12800505b22a853e8b7f4eb6a22" approved="yes">
        <source>Contact</source>
        <target state="final">CMS page</target>
        <note>Line: 57</note>
</trans-unit>
```

**Comment by TristanLDD** [comment] 2020-05-06 13:47
Hi @SeriousKen, thanks for the informations.

We'll have a look in the translations and see if we can correct that label. 
@LouiseBonnard WDYT?

**Comment by LouiseBonnard** [comment] 2020-05-06 16:14
Hello @SeriousKen, have you checked the translation on [Crowdin](https://crowdin.com/project/prestashop-official/en-GB)?

**Comment by hibatallahAouadni** [comment] 2021-02-23 23:05
Hello @SeriousKen ,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-23 23:05 UTC
Labels: Improvement, BO, No change required, 1.7.6.5
