### ISSUE TITLE
BO - Error in console in order page 

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#18776] opened 2020-04-23 10:29 UTC
#### Describe the bug

There is some error in the console when we go to order page.

#### Steps to Reproduce

1. Install 1.7.7.x
2. Open the console 
3. Go to back office > order
<img width="568" alt="Capture d’écran 2020-04-23 à 12 27 48" src="https://user-images.githubusercontent.com/3034677/80089236-e47be900-855d-11ea-96d2-d2752c651b2e.png">
5. Open an order
6. See error
<img width="1280" alt="Capture d’écran 2020-04-23 à 12 08 24" src="https://user-images.githubusercontent.com/3034677/80089072-b5657780-855d-11ea-9d94-b407542ee980.png">

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1

**Comment by Progi1984** [comment] 2020-04-27 12:56
Ping @NeOMakinG

**Comment by Progi1984** [comment] 2020-05-13 06:57
The problem is relative to GDPR module. (So the PrestaShopCorp organization)

**Comment by LouiseBonnard** [comment] 2020-05-18 12:14
@lolath-presta, can you please have a look at this issue?

**Comment by Darmona** [comment] 2020-05-20 09:56
Bogue Ticket in Performance Squad : http://forge.prestashop.com/browse/EPERF-47

**Comment by matks** [comment] 2020-09-21 15:49
Fixed by https://github.com/PrestaShopCorp/psgdpr/issues/103 on module, will be delivered with version 1.2.1

**Closed as completed by matks** 2020-09-21 15:49 UTC
Labels: Bug, Trivial, BO, Order, Regression, GDPR, 1.7.7.x
