### ISSUE TITLE
Can't hide my email - Contact information 3.3.0

### ISSUE THREAD

**Issue by Macrisu** [PrestaShop/PrestaShop#18598] opened 2020-04-12 22:13 UTC
#### Describe the bug

Prestashop 1.7.6.4
Contact information module 3.3.0 (latest now)

Contact information NO activated.

#### Expected behaviour

I still see in clear image address on the footer of the site and contact page

#### Steps to Reproduce

Steps to reproduce the behaviour
![Screenshot 2020-04-13 at 01 12 44](https://user-images.githubusercontent.com/16325429/79081213-01c1e380-7d24-11ea-854f-c171d1206668.jpg)
:

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

**Comment by MatShir** [comment] 2020-04-15 16:34
Even erasing the cache and with a hard reload, I was able to reproduce the issue with PrestaShop version 1.7.6.4.
I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thank you!

**Comment by marionf** [comment] 2020-04-15 16:50
@MatShir @Macrisu 

It seems to be fixed on 1.7.7.x, could you check ?

![capture d'écran_2518](https://user-images.githubusercontent.com/13449658/79364637-ecc69980-7f49-11ea-9a19-0c23241e957f.png)

![capture d'écran_2519](https://user-images.githubusercontent.com/13449658/79364845-2dbeae00-7f4a-11ea-829c-5d48bff85413.png)

**Comment by Macrisu** [comment] 2020-04-15 17:00
I've modified the template directly in my 1.7.6.4

@marionf I do not have 1.7.7.x
Is this final?

**Comment by marionf** [comment] 2020-04-15 17:11
> Is this final?

No, the 1.7.7.x is the branch currently in development, the 1.7.7.0 beta will be available in few weeks.

> I've modified the template directly in my 1.7.6.4

As you can see under the feature "your theme needs to be compatible with this feature", so maybe your theme isn't
If you don't use classic, you should contact the developer of your theme

**Comment by marionf** [comment] 2020-04-15 17:13
As we could not reproduce your issue with classic and 1.7.7.0 I close the issue.

**Closed as completed by marionf** 2020-04-15 17:13 UTC
Labels: Bug, Minor, FO, Can't reproduce, Contactinfo

**Comment by Macrisu** [comment] 2020-04-15 17:15
I use the classic theme, as my store is not now in production.
It's for testing and learning.

I've edited the templates in order to get rid of the clear text email.

Like here:
https://www.prestashop.com/forums/topic/950033-remove-hide-email-address-in-store-information-on-the-front-office/

**Comment by marionf** [comment] 2020-04-15 17:31
@Macrisu 

Here is the PR to fix the issue: https://github.com/PrestaShop/PrestaShop/pull/14539
You should apply these changes to your theme
