### ISSUE TITLE
Problem with quantity discounts in combination with product discount in %

### ISSUE THREAD

**Issue by wzzly** [PrestaShop/PrestaShop#24880] opened 2021-06-08 18:22 UTC
Hi,

when you use a discounted product price in % and also want to use quantity discount in %, the prices are not calculated correclty.

**Describe the bug**
When for example you have a product with the price of $10.
With the first discount you check "Leave initial price".
And then you apply discounts with the following settings:
![image](https://user-images.githubusercontent.com/35727938/121236307-181aef00-c896-11eb-8def-4e7f23064c7f.png)

Then the output is:
$10 -> $9
5units = $6,75 ----> this is 25% discount based on the $9 instead of the $10
15units = $4,50 ----> this is 50% discount based on the $9 instead of the $10

Output should be:
$10 -> $9
5units = $7,50 ----> 25% discount based on the $10
15units = $5 ----> 50% discount based on the $10

It doesn't make sense that it's not always based on the base retail price. Especially when you check "Leave initial price". When you uncheck it and fill in a fixed price for 1 quantity, then you can argue if all the other quantity discounts should be based on this price, but even then there should atleast be an option to choose.

Pretashop 1.7.7.4
PHP 7.3

**Comment by wzzly** [comment] 2021-06-08 20:11
Think this is fixed with pull #15100 , but why isn't it in 1.7.7.4 then?

**Comment by hibatallahAouadni** [comment] 2021-06-09 10:08
Hello @wzzly 

So you mean that your issue is the same as this one #16163?
Please check and feedback.

Thanks!

**Comment by wzzly** [comment] 2021-06-09 10:11
@hibatallahAouadni yes I think so.
I seems to be fixed with #15100 
What is the reason it's no already in 1.7.7.4 if that change is approved more than a year ago?

**Comment by hibatallahAouadni** [comment] 2021-06-16 11:02
Hello @wzzly 

That issue is fixed with PS1.7.8.0 and not with 1.7.7.4 :wink: 

![image](https://user-images.githubusercontent.com/23308427/122207669-abf64780-cea2-11eb-83ce-874b84146fba.png)

You can use this PR #15100 fix till 1.7.8.0 stable version is released.
So, as we are aware of this issue and it is already in our debug backlog. This issue is a duplicate of #16163. 
I close the issue.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-16 11:02
Duplicate of #16163

**Closed as completed by hibatallahAouadni** 2021-06-16 11:02 UTC
Labels: Bug, BO, Duplicate, Taxes and Prices, 1.7.7.4
