### ISSUE TITLE
Display error if the image of a custom product is too large

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#32714] opened 2023-05-25 13:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

if I upload a .MOV video, it is accepted (although it should not, and an error occurs if I validate

https://watch.screencastify.com/v/Ge5RGh1LimvQYww8UqfI

With debug mode : 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/dcbb1a9a-3578-4a2b-bf1f-d7cc100d6909)

On 8.1.x I can't save the customization, and I have no error or notification

### Expected behavior

Notification : Image is too large. Maximum allowed: 8192 kB
The rest of the page should display correctly

### Steps to reproduce

1. Go to BO > Catalog > Products > Customizable mug
2. Click on Details
3. Add a customization field > fill informations and choose file required
4. Save
5. Go to FO >customizable mug
6. Type your text
7. Add a .MOV file
8. Save customization
9. See error

### PrestaShop version(s) where the bug happened

8.1.0 RC1

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2023-05-29 17:28
Hello @paulnoelcholot 

> Add a .MOV file
Save customization
See error

It's normal to see error as the file input doesn't support a mov file, see the attached screenshot below:
![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/e0afd8e2-4836-40b3-aa00-4d1231c37743)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-05-30 09:39
Thanks for your feedback! I reproduce the issue with PS1789 & 804 & 810

**Comment by hibatallahAouadni** [comment] 2023-05-30 09:45
Related to #15183

**Comment by florine2623** [comment] 2024-03-18 11:21
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/35623

**Closed as completed by florine2623** 2024-03-18 11:21 UTC
Labels: Bug, Minor, FO, Product customization, Verified, 1.7.8.9
