### ISSUE TITLE
Orders are placed on "On Backorder (paid)" with 1 item in stock

### ISSUE THREAD

**Issue by kandiaga** [PrestaShop/PrestaShop#14370] opened 2019-06-25 21:12 UTC
**Describe the bug**
When stock item is 1, and order is placed, instead of fulfilling order, order is placed On Back order (Paid)

**To Reproduce**

Place order for item with 1 stock
Order is marked at Delivered
Order is marked as On Backorder(paid)
**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**

PrestaShop version: 1.7.4.2

**Comment by chrisrabkin** [comment] 2019-06-25 22:00
Hello,
All true in kandiaga's report but the version is 1.7.5.2. Experiencing when a product is in stock with a quantity of 1 and is purchased with backorder not permitted/denied - the product should go out of stock and not into a backorder status. No notifications should be sent out- and prrestashop should display out of stock on the product or whatever out of stock warning is setup.

This does not happen.  What does happen is the product with 1 quantity is purchased and paid for then the shop changes the status to backorder paid, which is the incorrect status.

**Comment by khouloudbelguith** [comment] 2019-06-26 08:53
Hi @kandiaga, @chrisrabkin,

I did not manage to reproduce the issue with PS1.7.4.2, PS1.7.5.2 & PS1.7.6.0rc1.
I attached a video record
https://drive.google.com/file/d/15D-9aueU44atolyzw3JEoQMruJ_FC3JR/view
This issue is fixed in the PS1.7.4.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/8985
Thanks to check & feedback.

**Comment by kandiaga** [comment] 2019-06-26 10:48
Hi  @khouloudbelguith 

No, the issue is not fixed with the 1.7.5.2. as  @chrisrabkin said.  
I wanted even to use a hack to make it work but it's not the right approach.

I will do more testings based on your video instructions and let you know if any change.


Thanks.

**Comment by khouloudbelguith** [comment] 2019-06-26 11:11
@kandiaga, thanks!
Waiting for your feedback.

**Comment by christophedupont** [comment] 2019-07-16 13:01
I confirm, I'm experiencing the same behaviour on 1.7.5.2.

**Comment by christophedupont** [comment] 2019-07-16 14:02
Okay so for me it was not prestashop's fault but mine.
I updated an existing prestashop to 1.7.5.2, and an old override of PaymentModule was still there with : 
```php
            if (Configuration::get('PS_STOCK_MANAGEMENT') &&
                            ($order_detail->getStockState() ||
                            $order_detail->product_quantity_in_stock <= 0)) { 
`

Changing the `<=0` to `<0` in my override to make it look like the new `/classes/PaymentModule.php` solved the issue.

**Comment by khouloudbelguith** [comment] 2019-07-16 14:25
@christophedupont, thanks for your feedback.
@kandiaga, any news about your issue?

Thanks!

**Comment by mariem-abid** [comment] 2019-08-16 07:32
Hi @kandiaga,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by mariem-abid** 2019-08-16 07:32 UTC
Labels: Bug, BO, Can't reproduce, Order, 1.7.4.2, 1.7.5.2
