### ISSUE TITLE
Faceted search not shown on displayLeftColumnProduct

### ISSUE THREAD

**Issue by Chebe2** [PrestaShop/PrestaShop#10226] opened 2018-08-31 12:27 UTC
Hello,
I had Faceted search module working properly on "displayLeftColumn" position. Then I hook it to "displayLeftColumnProduct" but nothing appears. The oder hooks are appear perfectly on this position.

The filter template is checked to appear in all the categories.
My prestashop version is 1.7.3.3
With the classic theme
And module version: v2.1.2

Thank you for your help.

**Comment by khouloudbelguith** [comment] 2018-08-31 12:58
Hi @Chebe2,

I manage to reproduce the issue with the last version  1.7.4.2 & ps_facetedsearch v2.0.1 - by PrestaShop.
We will see how to fix it.

Best regards, Khouloud

**Comment by colinegin** [comment] 2019-02-26 09:30
Hello,

We are currently reworking this module, could you explain us why you would like to display the faceted search on displayLeftColumnProduct ?

Thank you and have a nice day,

Coline

**Comment by khouloudbelguith** [comment] 2019-04-18 15:50
Hi @Chebe2,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-18 15:50 UTC
Labels: Bug, FO, Positions, Faceted search, No change required, 1.7.4.2, Front-end
