### ISSUE TITLE
Experimental Features does not enable default taxes on product creation. 8.1.x

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#33888] opened 2023-09-08 20:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When testing the creation of products, it is found that when I go to the price tab, in experimental functions it does not load by default the taxes that have been configured. Sample without tax by default.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/971c7668-37ee-4547-98fc-4bef0519b8cd)

### Expected behavior

It should load by default the taxes that have been configured as with the Prestashop version 1.7.

### Steps to reproduce

Activate experimental features.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/c0035688-f677-460f-8335-56b993b7b670)

Create a new order.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/ae52cc60-4eed-4ce0-b88a-13b23286d081)

Go to the price tab and verify that it does not charge taxes by default.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/e36be3dc-5c36-4a67-9c52-cd5dc0060041)

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/f4dada9c-e791-456a-941f-34a08b58bbd1)

Experimental functions are deactivated and a new product is created. This way it shows taxes by default.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/d5300eb6-b39f-4fd1-8711-645b4283b837)

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment] 2023-09-11 12:13
Hello @ocio87 

In you steps, the second one, I beleive you meant "create a new Product", is that so? 
I didn't manage to reproduce the issue with 81x, see the attached screen record below:

[issue_33888.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/cd638c76-3242-4359-b3f7-40890fe083af)

Please check and feedback.

Thanks!

**Comment by ocio87** [comment] 2023-09-11 12:21
What I mean is that when you have a tax configured in PrestaShop 1.7.8 when creating a product, the tax already appears to be selected, it should not be selected. With experimental functions, the tax must be chosen. It appears without taxes as default.

**Comment by MatShir** [comment] 2023-09-12 07:41
Second feedback about the tax rule on the product page https://github.com/PrestaShop/PrestaShop/discussions/33863

**Comment by sallemiines** [comment] 2023-09-13 16:16
@MatShir it seems what @ocio87 ask for a feature, is that so?

**Comment by florine2623** [comment] 2023-10-18 09:38
@MatShir Should this issue be closed in favor of the discussion https://github.com/PrestaShop/PrestaShop/discussions/33863 ?

**Comment by paulnoelcholot** [comment] 2023-11-02 10:43
Hello @ocio87,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed** 2023-12-26 17:32 UTC
Labels: Bug, Waiting for PM, BO, Multistore, Invalid, 8.1.x, Products Page
