### ISSUE TITLE
PHP 7.4: Notice: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#19477] opened 2020-05-31 08:53 UTC
![Screenshot_1](https://user-images.githubusercontent.com/6318282/83348437-e6607580-a36f-11ea-96d4-e0c6fc4f1bee.png)

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L2992

$ids return FALSE (bool)

**Comment by jolelievre** [comment] 2020-06-01 10:07
Hi @TemKaSD 

Thank you for your feedback, as explained in this comment https://github.com/PrestaShop/PrestaShop/issues/19463#issuecomment-636715107 The support for PHP 7.4 will be managed in PrestaShop 1.7.8, so this issue might be a duplicate of #16477 but without further information it's hard to tell.

I tried to reproduce your bug however but encountered many blocking issues related to PHP 7.4, so I guess you already fixed some of them to reproduce this issue? Could you detail the bug a little more because I'm not sure if it's purely related to PHP 7.4 or it's a "side effect" bug.

We need a detailed scenario of how a tester can reproduce the bug, like:
- go on front office
- install module ps_specials
- try to access a product page
- ...

Also please specify which PHP and PrestaShop version you use.

Thank you

**Comment by TemKaSD** [comment] 2020-06-01 19:34
1. Install PrestaShop
2. Advanced Parametrs > Performance
- Template compilation: Force
- Cache: No
- Debug mode: On
3. Modules > Module Catalog > Install ps_specials
4. Go to /index.php

![image](https://user-images.githubusercontent.com/6318282/83446793-aba32e00-a492-11ea-867d-9b97435dfb15.png)

**Comment by PierreRambaud** [comment] 2020-06-03 09:14
Duplicate of #16477

**Closed as completed by PierreRambaud** 2020-06-03 09:14 UTC
Labels: Duplicate, No change required, ps_specials

**Comment by nfacciolo** [comment] 2021-12-06 09:27
For information, I had this problem because I removed categories and result no default category was assigned for some product
