### ISSUE TITLE
Carrier Product list

### ISSUE THREAD

**Issue by higanjima** [PrestaShop/PrestaShop#19917] opened 2020-06-24 07:36 UTC
#### Describe the bug

If you have multiple carrier with same name and description (useful if you want the same carrier with different tax rules), only one of them has been shown in the product edition. 

Before : 

<img width="411" alt="Capture d’écran 2020-06-24 à 09 33 23" src="https://user-images.githubusercontent.com/45202815/85515824-d863e480-b5fd-11ea-9220-e1278e610bf7.png">

#### Expected behavior

Show all the carriers 

After : 

<img width="417" alt="Capture d’écran 2020-06-24 à 09 33 29" src="https://user-images.githubusercontent.com/45202815/85515869-e580d380-b5fd-11ea-9c55-c3ef058c541e.png">

#### Additional information

Solution edit /www/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php

Replace 

`foreach ($carriers as $carrier) {
            $this->carriersChoices[$carrier['name'] . ' (' . $carrier['delay'] . ')'] = $carrier['id_reference'];
        }`

By 

`foreach ($carriers as $carrier) {
            $this->carriersChoices[$carrier['id_reference'].' - '.$carrier['name'] . ' (' . $carrier['delay'] . ')'] = $carrier['id_reference'];
        }`
* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by prestascott** [comment] 2020-06-24 15:35
Hi @higanjima, thanks for your report!

How can you be sure to identify the right carrier depending on tax rules? It'll be too difficult to know all IDs by heart. 

Wdyt @PrestaShop/prestashop-product-team of this improvement?

**Comment by higanjima** [comment] 2020-06-24 15:54
I think the best way is to show the cart rule name after the name of the carrier @prestascott, but in my case i need a quickwin :) and i need all the carriers with all tax rules. I made an update in the cart class to choose the best carrier tax rules depending on the tax rule of the products in the cart.

**Comment by colinegin** [comment] 2020-07-10 09:15
ping @florine2623 i think we already have issues about carriers with the same name, right ?

**Comment by khouloudbelguith** [comment] 2020-07-10 09:26
Hi @higanjima, @colinegin, @florine2623,

Yes, we have a similar issue fixed in the next release177: https://github.com/PrestaShop/PrestaShop/issues/11379 with this PR: https://github.com/PrestaShop/PrestaShop/pull/12379

Thanks!

**Comment by colinegin** [comment] 2020-07-10 09:27
Thanks @khouloudbelguith !
Is this what you were looking for @higanjima ?

**Comment by marionf** [comment] 2020-07-23 09:11
Duplicate of #11379

**Closed as completed by marionf** 2020-07-23 09:11 UTC
Labels: Improvement, BO, Duplicate, Carriers, 1.7.6.0
