### ISSUE TITLE
 Displaying shipping costs with a promotional code did not update

### ISSUE THREAD

**Issue by jspanog** [PrestaShop/PrestaShop#21698] opened 2020-11-01 19:05 UTC
#### Describe the bug

When I have a promo code that offers free shipping and apply it in the cart, the shipping costs always appear. No indication to indicate to the customer that the shipping costs are free.

#### Expected behavior

When I apply the promotional code to have free shipping costs, I want to have entered the mention "Free" to clearly indicate that the shipping costs are free and to avoid any confusion.

#### Steps to Reproduce

1. Create a voucher code in back office and select "Free shipping" and price reduction
2. Save
3. On front office, add product in cart 
4. Apply a voucher code 
5. Shipping cost it's not free
 
**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

<img width="1499" alt="panier" src="https://user-images.githubusercontent.com/12716308/97811830-58b9e680-1c7d-11eb-956b-5c1f3bd2a817.png">
<img width="1383" alt="voucher-code" src="https://user-images.githubusercontent.com/12716308/97811839-653e3f00-1c7d-11eb-8135-0d159633e783.png">
<img width="578" alt="discount" src="https://user-images.githubusercontent.com/12716308/97811846-712a0100-1c7d-11eb-9619-ee2548c37598.png">

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2020-11-02 09:34
Hi @Spano30 

This issue is a duplicate of #18533 which has been already fixed by this PR #18884
So, I close it.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-02 09:35
Duplicate of #18533

**Closed as completed by hibatallahAouadni** 2020-11-02 09:34 UTC
Labels: Duplicate
