### ISSUE TITLE
Sending emails from module does not work in multishop setting

### ISSUE THREAD

**Issue by preoteasa** [PrestaShop/PrestaShop#18595] opened 2020-04-12 20:01 UTC
#### Describe the bug

I have set up a prestashop multi-shop with two shops: one is located at www.server_name.com/
and second at  www.server_name.com/second/

Using Mail::send(...) with custom template path '/modules/yourmodulename/mails' as suggested
in https://devdocs.prestashop.com/1.7/development/mail/#using-the-mail-send-method

does not work in hookActionObjectCustomerUpdateAfter when for example enabling the user.

This is no surprise looking at the core for dealing with the template path:

            // get templatePath
            if (preg_match('#' . $shop->physical_uri . 'modules/#', str_replace(DIRECTORY_SEPARATOR, '/', $templatePath)) &&
                preg_match('#modules/([a-z0-9_-]+)/#ui', str_replace(DIRECTORY_SEPARATOR, '/', $templatePath), $res)
            ) {
                $moduleName = $res[1];
            }

The "templatePath" is used only for finding the module name and nothing more in the entire send function. For the second shop  $shop->physical_uri results in "/second", and "/modules/yourmodulename/mails" does not match this. 
Using "dirname(__FILE__) . '/mails/'," for template path as in module Ps_Emailsubscription does not work either.

#### Expected behavior

Send emails from custom module in multi-shop setup.

#### Steps to Reproduce

1. Setup a multi-shop environment one shop on /, second shop on /second
2. enable "Would you like to send a verification email after subscription?" in module Ps_Emailsubscription for shop /second
3. go to second shop .../second, subscribe to newsletter
4. no email is sent.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-04-16 08:50
Hi @preoteasa,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.4 and the `ps_emailsubscription` v2.0.3 and v2.3.0.
I attached a screen record
https://drive.google.com/file/d/103ak5RIJgr6wNo7G2IPXwG1xoX8rexfi/view?usp=sharing

Thanks to check and feedback.

**Comment by preoteasa** [comment] 2020-04-16 16:40
Thank you for your test. I don't know how you set it up, but you can reproduce the problem here:

https://data.finlandquality.com/original/

This is a simple installation of prestashop, with  nothing else but the default. The emailsubscription module is setup to send verification and confirmation emails. You can register to the shop, and you will receive the notification email. You can subscribe to newsletter and no email is sent.

I have to stress it again, that comparing the code from "send" for the parameter  templatePath, and the code in emailsubscription one can see immediately that something is wrong. $shop->physical_uri returns the address of the shop on the web browser, while dirname(__FILE__) returns the physical path on the file system. If for some reason these do not match, then the module templates are not found.

Moreover, the parameter templatePath is used ONLY to deduce the name of the module, so why this complication? Why not introducing a parameter module which should contain the module name. There are many questions on the prestashop forum of how to send emails from a module. This should have a simple solution, but obviously it has not.

**Comment by khouloudbelguith** [comment] 2020-04-16 16:47
@preoteasa, 
What is the exact version of the email_subscription did you use?
Could you please navigate to your Back office => Advanced Parameters => E-mail, try to " Test your email configuration" by sending a test email in your second shop.
Thanks to check & feedback.

**Comment by preoteasa** [comment] 2020-04-16 16:48
Version v2.5.1, I installed the latest before testing. Prestashop 1.7.6.4

**Comment by preoteasa** [comment] 2020-04-16 16:51
The physical path of my installation is: /var/www/html/presta-original/. I think this causes the problem.

**Comment by preoteasa** [comment] 2020-04-16 16:53
Back office => Advanced Parameters => E-mail, try to " Test your email configuration" 
The email works. I installed and tested it. I use the smtp server that I use to send newsletter. So that is not an issue. That is why  I suggested to create an account. You will get the notification email.

**Comment by preoteasa** [comment] 2020-04-16 16:55
This is not even multi-shop anymore. It is a simple prestashop installation.

**Comment by khouloudbelguith** [comment] 2020-04-16 17:16
@preoteasa, 
>This is not even multi-shop anymore. It is a simple prestashop installation.

so you have only a problem when the multistore is enabled?
>The physical path of my installation is: /var/www/html/presta-original/. I think this causes the problem.

So, it is a custom problem, is it?


Thanks!

**Comment by preoteasa** [comment] 2020-04-16 17:22
The problem occurs also when there is no mutistore, but I noticed while working on a mutistore environment.

What do you mean "Custom"? The problem occurs on the installation that I have. The design of the code is wrong. What else should I say. In single shop installation, the problem can be avoided, but I don't think that it can be avoided on a multistore installation.

**Comment by preoteasa** [comment] 2020-04-16 17:44
Can you tell me the physical location on the file system of the emailsubscription module on the test that you performed?

**Comment by khouloudbelguith** [comment] 2020-04-23 10:47
Hi @preoteasa,

Sorry for the late answer.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sarahdib** [comment] 2020-05-19 11:42
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-19 11:42 UTC
Labels: Bug, Email, Multistore, Emailsubscription, No change required, 1.7.6.3
