### ISSUE TITLE
1-Click Upgrade fails from v.1.7.8.8 to 8.0.1

### ISSUE THREAD

**Issue by madibashop** [PrestaShop/PrestaShop#31433] opened 2023-02-17 22:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I try to upgrade from v 1.7.8.8 to 8.0.1 with 1-Click Upgrade v.4.15.0.
Theme: CLASSIC ver. 1.0.0

PHP version is 7.4
MySQL version is 5.7

I deactivate non native modules, overviews and cache.
Shop offline.
Upgrade process result in some errors:

************************************************************************
ERRORS
************************************************************************

```
[INTERNAL] 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/src/Core/Addon/Theme/ThemeManager.php line 384 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details. #0 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/src/Core/Addon/Theme/ThemeManager.php(245): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #1 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(113): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #2 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #3 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(662): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #4 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(119): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #5 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #6 
/homepages/43/**********/htdocs/**************/PrestaShop/**********/****************/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #7 {main}
```

**********************************************************************

After this errors the web page fails in some situations:
Back office: It's not possible to navigate from root category to subcategories: 500 Error.
Front office: Main menu only opens root category. The rest of the menu only shows white pages.

### Expected behavior

I expected upgrade without errors.

### Steps to reproduce

1. Go to advanced parameters - perfomance: cache off and clear cache.
2. Go to shop - configuration - maintenance: offline.
3. Go to 1-Click Upgrade v.4.15.0 deactivate non native modules and overviews. Only mail templates on.
4. Run upgrade.

Result: errors commented before.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v.4.15.0.

**Comment by hibatallahAouadni** [comment] 2023-02-21 06:19
Hello @madibashop 

> ThemeManager->enable('classic')

It seems you're using another theme 🤔 Could you please rollback and try to switch to CLASSIC theme and then try to upgrade and check if you still encounter the same issue.
Please check and feedback.

Thanks!

**Comment by madibashop** [comment] 2023-02-21 08:32
I am using CLASSIC module V.1.0.0

**Comment by madibashop** [comment] 2023-02-21 11:16
I have tried to upgrade now.
Same options:

Upgrade from v 1.7.8.8 to 8.0.1 with 1-Click Upgrade v.4.15.0.
Theme: CLASSIC ver. 1.0.0
PHP version is 7.4
MySQL version is 5.7
I deactivate non native modules, overviews and cache.
Shop offline.

Same result:
*********************
ERRORS
*********************
[INTERNAL] 
/homepages/43/***/htdocs/***/PrestaShop/***/src/Core/Addon/Theme/ThemeManager.php line 384 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details. #0 
/homepages/43/***/htdocs/***/PrestaShop/***/src/Core/Addon/Theme/ThemeManager.php(245): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #1 /homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(113): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #2 /homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #3 /homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(662): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #4 /homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(119): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #5 
/homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #6 /homepages/43/***/htdocs/***/PrestaShop/***/***ADMIN***/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #7 {main}

I do not know: Is it possible to upgrade from **v_1.7.8.8 to v_8.0.1** ?
Or I need to upgrade from **v_1.7.8.8 to v_8.0.0 first ?**

Thanks !

**Comment by madibashop** [comment] 2023-02-21 12:11
Result in Categories:

![Category](https://user-images.githubusercontent.com/125015630/220340581-b6bd3089-883e-4294-b9ea-c0ab61be13db.jpg)

and cliking in "Productos"
![Error_500](https://user-images.githubusercontent.com/125015630/220341171-e68ed505-c68c-4fbe-aa75-a94972965d51.jpg)

It is not possible to go to subcategories !

Thanks !

**Comment by florine2623** [comment] 2023-02-21 13:16
Hello @madibashop ,

> I do not know: Is it possible to upgrade from v_1.7.8.8 to v_8.0.1 ?
> Or I need to upgrade from v_1.7.8.8 to v_8.0.0 first ?

You can do 1.7.8.8 to 8.0.1 directly.

Can you Enable debug mode and go back to your products and subcategories ?
Advanced Parameters > Performances > Debug Mode enable
This will allow to see where the issu comes from.

Thanks!

**Comment by madibashop** [comment] 2023-02-23 10:33
I add more information in a new issue #31505

**Comment by HanaRebaiQA** [comment] 2023-02-23 16:37
Hello @madibashop 

I tried to reproduce your issue when **upgrading from PS1788 to PS8.0.1 with php7.4**. But I was unable to reproduce it.

![image](https://user-images.githubusercontent.com/92912932/220971294-df4ccbf3-1f40-46ce-b2ed-a55579abf843.png).

Despite our efforts, we were not able to reproduce your issue with the provided information. 
It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thank You!

**Closed as completed by HanaRebaiQA** 2023-02-23 16:37 UTC
Labels: Bug, BO, Autoupgrade, Invalid, Module, 1.7.8.8

**Comment by madibashop** [comment] 2023-03-04 22:52
I try upgrade another time.
Initial conditions are:
![Porta-retalls01](https://user-images.githubusercontent.com/125015630/222931902-569f9e1a-b9d6-41b3-b881-b5d315d3c1f0.jpg)
![Porta-retalls02](https://user-images.githubusercontent.com/125015630/222932016-bb3b4f28-e3e4-4f1b-aa3b-06e8f4ed8cc4.jpg)
![Porta-retalls03b](https://user-images.githubusercontent.com/125015630/222932084-44d710df-e625-41ac-8ca8-c72388d96be6.jpg)
![Porta-retalls04](https://user-images.githubusercontent.com/125015630/222932099-d10e9bea-b271-4534-b9a3-49added58f26.jpg)
![Porta-retalls05](https://user-images.githubusercontent.com/125015630/222932107-c37cdf50-c326-43ee-8123-4804de127d04.jpg)
![Porta-retalls06](https://user-images.githubusercontent.com/125015630/222932113-74aedb47-0045-4abf-84c1-6453d134db43.jpg)

And  the result of upgrade is:

![Error1](https://user-images.githubusercontent.com/125015630/222932152-5bf83f66-367d-4237-b3fe-47c5d0186d88.jpg)
![Error2](https://user-images.githubusercontent.com/125015630/222932156-93aa2114-d510-4aa6-81fc-100876e9878e.jpg)

What are my problem ?
How can I do for upgrade PS ?
Thanks!
