### ISSUE TITLE
Combination edit : very slow

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#12516] opened 2019-02-08 15:25 UTC
Hello,
I have a product with 150 combinations.
When trying to save changes in one combination, it take 2 minutes to get response.
I discover that the 150 combinaisons are sent in the ajax call, that's probably the reason why the call take so long. 

Can't we have a dedicated form / call for that ? 

Thanks

**Comment by khouloudbelguith** [comment] 2019-02-08 15:29
Hi @rflorent,

thanks for your report.
We are aware of this issue and we are working on it.
No, this issue is in progress, it is assigned to our developer Jocelyn Fournier, he is working on it.
Thanks for your patience
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-08 15:29
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2019-02-08 15:29 UTC
Labels: Duplicate
