### ISSUE TITLE
ERROR ADDING EMPLOYEES

### ISSUE THREAD

**Issue by asierarroita** [PrestaShop/PrestaShop#33003] opened 2023-06-26 07:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

CRITICAL                 09:23:44 | request | Uncaught PHP Exception Twig\Error\LoaderError: "Template   "PrestaShopBundle:Admin/Configure/AdvancedParameters/Employee/Blocks:form.html.twig"  is not defined in  "@PrestaShop/Admin/Configure/AdvancedParameters/Employee/Blocks/form.html.twig"  at line 20." at  /var/www/clients/client1/web8/web/vendor/twig/twig/src/Loader/ChainLoader.php  line 99                                {     "exception": {} }
-- | -- | --
CRITICAL                 09:23:44 | php | Uncaught Exception: Template  "PrestaShopBundle:Admin/Configure/AdvancedParameters/Employee/Blocks:form.html.twig"  is not defined in  "@PrestaShop/Admin/Configure/AdvancedParameters/Employee/Blocks/form.html.twig"  at line 20.                                {     "exception": {} }

### Steps to reproduce

1-Go to team
2-employees 
3- add new employee
4-
Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### PrestaShop version(s) where the bug happened

1.8.4

### PHP version(s) where the bug happened

8.0

**Comment by AureRita** [comment] 2023-06-26 13:45
Hi @asierarroita 

Thank you for your report, Currently we didn't have enought information to reproduce you issue because we didn't have version 1.8.4 of Presrashop. Moreover I tried to reproduce your issue on 8.0.4 (it's maybe your version of Presta) as you can see : 

![Untitled_ Jun 26, 2023 3_44 PM](https://github.com/PrestaShop/PrestaShop/assets/100699445/2c141563-0746-4f33-af05-2dafe3df9368)

Did I miss something ? 
Waiting for your feedback

**Comment by aniszr** [comment] 2023-07-14 09:55
Hello @asierarroita ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by aniszr** 2023-07-14 09:55 UTC
Labels: Bug, BO, Employees, Invalid, 8.0.4

**Comment by Yvesalghazi** [comment] 2025-05-20 20:01
Hi there, 
I have encountered the same error a while ago but none of my supports from business care (presta) found the issue: 

**Expected behavior**

No response

Steps to reproduce

1-Go to team
2-employees
3- add new employee (or edit)
4-The server returned a "500 Internal Server Error".

Failed to load resource: the server responded with a status of 500 ()? https://bebebold.eu/ne54jvgeb/index.php/configure/advanced/employees/20/edit?_token=uxARYIcUL81nztsjq9873jHJSj6zJjIHbQ
(I changed the token)

PrestaShop version(s) where the bug happened

8.2

PHP version(s) where the bug happened

7.4

If your bug is related to a module, specify its name and its version

Apparently it is due to the core 

Your company or customer's name goes here (if applicable).

Yves
