### ISSUE TITLE
When using friendly urls & nginx and adding a product to the cart an error "an error occurred while processing your request" is displayed

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#10178] opened 2018-08-29 08:01 UTC
Just change my vps from apache to nginx: all works well, a part of "an error occurred while processing your request" when I add a product to cart. The product goes on cart, but red alert show always.
Please see also https://www.prestashop.com/forums/topic/862800-about-product-problems-in-1740/
http://forge.prestashop.com/browse/BOOM-5971 and http://forge.prestashop.com/browse/BOOM-6113

----
#### Describe the bug

When using nginx and if friendly URLs are enabled, an error is displayed in FO when trying to add a product to the cart, changing the quantity or selecting a combination.

#### Expected behavior

No error or explaining the configuration to apply in the devdoc when using nginx

#### Steps to Reproduce

1. Use nginx
2. Enable friendly URLs in BO > Shop parameters > Traffic & SEO
3. Go an FO product page and try to select a combination, change the quantity and add the product to the cart

**Screenshots**

![capture d'écran_2816](https://user-images.githubusercontent.com/13449658/95975474-834f1700-0e16-11eb-8fa6-f2f4f094a3b4.png)

#### Additional information

* PrestaShop version: 1.7.5.0
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-08-29 08:19
Hi @centoasa,

Have you tried to check this fix: https://github.com/PrestaShop/PrestaShop/pull/9390
It will be fixed in the next version 1.7.5.0
Thanks to check and feedback.

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-29 10:17
Apply the little patch as say @ttoine on #9390 but nothing chage on my www.100asa.it

**Comment by khouloudbelguith** [comment] 2018-08-29 10:26
Hi @centoasa,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-29 11:15
host: Linux #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
![2018-08-29 1](https://user-images.githubusercontent.com/5500935/44784329-93033700-ab8d-11e8-9bbe-cf4cdd19277f.png)

server setup and configuration: nginx/1.13.8
PrestaShop version (source): 1.7.4.2
debug mode report: none
PHP error logs: none
apache error log: none
javascript console log
screenshots: attached

**Comment by khouloudbelguith** [comment] 2018-08-29 11:56
Hi @centoasa,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-30 07:20
976#0: *187845 FastCGI sent in stderr: "PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/smarty/compile/8b/7e/a7/8b7ea784ba480d401eb9189900d15dcefa28470d_2.module.leofeatureviewstemplatesf.php on line 233" while reading response header from upstream
--

is the only error I can see
debug mode doesn't show nothing on front office.

**Comment by centoasa** [comment] 2018-08-30 08:24
Please see also this thread to see problem us not mine
https://www.prestashop.com/forums/topic/862800-about-product-problems-in-1740/#comment-2958973

**Comment by MathiasReker** [comment] 2018-08-30 08:50
@centoasa you need to disable cache and reproduce the error before sending the error log

**Comment by khouloudbelguith** [comment] 2018-08-30 09:58
Hi @centoasa ,

Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-30 10:03
@khouloudbelguith  all done as you suggest ==>
976#0: *229661 FastCGI sent in stderr: "PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/smarty/compile/8b/7e/a7/8b7ea784ba480d401eb9189900d15dcefa28470d_2.module.leofeatureviewstemplatesf.php on line 233" while reading response header from upstream

**Comment by khouloudbelguith** [comment] 2018-08-30 10:05
H @centoasa,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

Best regards, Kouloud

**Comment by centoasa** [comment] 2018-08-30 10:07
@khouloudbelguith sorry but in the app folder I've only test/cache, but it's empty

**Comment by khouloudbelguith** [comment] 2018-08-30 10:08
Hi @centoasa,

Sorry, into var/cache folder.

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-30 10:14
@khouloudbelguith  deleted 2 folder into var/cache

2018-08-30 12:13:21 | Access | 79.7.101.116 | 200 | POST /it/index.php?controller=product?token=5df9472c9390e81f3d16d1b4399dad74&id_product=6915&id_customization=0&qty=1 HTTP/2.0 |   |   | 20 | Accesso SSL/TLS nginx
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-08-30 12:13:22 | Access | 79.7.101.116 | 200 | POST /modules/leofeature/psajax.php?rand=1535624002752 HTTP/2.0 |   |   | 6.67 K | Accesso SSL/TLS nginx
2018-08-30 12:13:22 | Warning | 79.7.101.116 |   | 976#0: *232026 FastCGI sent in stderr: "PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/100asa.it/httpdocs/var/cache/prod/smarty/compile/8b/7e/a7/8b7ea784ba480d401eb9189900d15dcefa28470d_2.module.leofeatureviewstemplatesf.php on line 233" while reading response header from upstream |   |   |   | Errore nginx
2018-08-30 12:13:22 | Access | 79.7.101.116 | 200 | GET /12689-small_default/eia-e-vision-light-imager-omnidirezionale-2d1d.jpg HTTP/1.0

**Comment by khouloudbelguith** [comment] 2018-08-30 10:18
Hi @centoasa,

Thanks for your feedback.
@PierreRambaud, do you think it is an issue related to the server configuration? this issue is fixed by #9390

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-30 10:43
@khouloudbelguith @PierreRambaud surely this issue is related to PHP+FPM served by nginx
because I've just swith to PHP+FPM served by Apache ==> issue disappear.

**Comment by khouloudbelguith** [comment] 2018-08-30 10:48
Hi @centoasa,

So your issue is not related to the Prestashop core? it is a server configuration issue.

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-30 10:51
@khouloudbelguith 
This problem is not just mine, as you could see from other users on the forum.
I believe the problem is the union nginx + prestahop that creates the problem, because I use other applications with nginx and they work very well

**Comment by khouloudbelguith** [comment] 2018-08-30 11:17
Hi @centoasa,

I checked your shop.
![image](https://user-images.githubusercontent.com/16067358/44848477-29e7f600-ac57-11e8-8538-ee5270f23c2d.png)
You can solve the 502 bad request problems by reducing the Cookie lifetime for back-office and front-office by setting them lower, after changing the setting, you need to clear all your browser sessions and cookie sessions and login again. This should solve for ever your 502 bad request problem. And when it appears again, you only need to clear your cookie sessions in the borowser. The 502 Problem is a client HTTP-request problem and it ist caused by the server not understanding what the browser ist sending and vice versa.

Best regards, Khouloud

**Comment by PierreRambaud** [comment] 2018-08-30 13:41
This is not a bug from Apache, Nginx, this is just a PHP version problem, even if it's PHP, maybe your Apache doesn't use the same PHP version as your Nginx (which is why I have 5 php versions for Apache and 4 different for Nginx on my server).
You need to have a check on your modules.
`module.leofeatureviewstemplatesf` is what a read from cache file name. Maybe you have a `leofeature` module which is not compatible with PHP 7.2.

**Comment by dineshbadrukhiya** [comment] 2018-09-11 05:17
I'm not using Nginx and any leofeaturemodule but still not fixed it.

**Comment by khouloudbelguith** [comment] 2018-09-13 11:05
Hi @dbadrukhiya,

After applying the patch: #9390, I did not manage to reproduce your issue.
Steps that I followed:
1. Create  2 combinations for a product like
1.1. Size S, Color: Green, - default
1.2. Size M, Color: Blue,
2. Navigate to the FO: switch to Size M => No errors

Best regards, Khouloud

**Comment by dineshbadrukhiya** [comment] 2018-09-14 13:03
Hello @khouloudbelguith ,
in classes/Product.php there is no code as in patch: #9390,  like :

`$sql_values[] = '(' . (int) $id . ', ' . (int) $this->id . ', ' . $pos . ')';
        }`

But, there is code like : 

` $sql_values[] = '(' . (int) $id . ', ' . (int) $this->id . ', ' . (int) $position . ')';`

Can it matters? I'm using PS1.7.4.2.

**Comment by khouloudbelguith** [comment] 2018-09-14 13:07
Hi @dbadrukhiya,

This patch is merged in the next release 1.7.5.0.
In the last version 1.7.4.2, the issue exists.

Best regards, Khouloud

**Comment by dineshbadrukhiya** [comment] 2018-09-14 13:18
Hi @khouloudbelguith 

Thanks for reply. I hope 1.7.5.0 will be available soon.

**Comment by Tominjsh** [comment] 2018-09-21 10:18
so, is there a solution before 1.7.5?

**Comment by khouloudbelguith** [comment] 2018-10-18 09:29
Hi @Tominjsh, this is the solution https://github.com/PrestaShop/PrestaShop/pull/9390 applied in the next release 1.7.5.0.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-21 13:50
Hi all,

PrestaShop 1.7.5.0 now is available.
In my case, after upgrade from PS1.7.4.4 to 1.7.5.0 with the 1-click upgrade v4.5.1, I did not manage to reproduce the issue.
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and **test** the upgrade on a separate machine from your production.
Thanks!

**Comment by idimash** [comment] 2019-01-28 09:53
This bug is reproduced in 1.7.5.0 when enabled URL rewriting.
But in my case, prestashop reports that the server does not support  URL rewriting.
![presta bug 2](https://user-images.githubusercontent.com/12410518/51827242-95f78480-22f1-11e9-90ae-1c8556ee89fa.png)
prestashop 1.7.5.0, nginx 1.15.8, php 7.2.14
[nginx config](https://github.com/PrestaShop/PrestaShop/files/2801919/vhost.txt)
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-28 11:29
Hi,

I tried with PS1.7.5.0.
As @idimash said, I tried to enable the "Friendly URL", it is enabled but I have a message "`URL rewriting (mod_rewrite) is not active on your server, or it is not possible to check your server configuration. If you want to use Friendly URLs, you must activate this mod`." => so this option should be disabled.
In the FO, URL rewriting is enabled, when I try to switch between combinations, I have an error:
`An error occurred while processing your request`
https://drive.google.com/file/d/1kNYmqfgWEi9O_i8Iwf85v1F593kYhXQh/view
ping @PierreRambaud nwhat do you think?
Thanks!

**Comment by PierreRambaud** [comment] 2019-01-29 09:34
The `mod_rewrite` exists only for apache environment. This is a wrong wording here if you are using Nginx. Otherwise make sur you enable the `mod_rewrite`.

**Comment by magiodev** [comment] 2019-02-08 08:38
Hi all!

I've updated to 1.7.5.0 but the error persists. Before the update the error was occurring in any kind of product. Now it only get error with product withOUT attributes & features.

No PHP errors with debug mode activated, apache2 error.log is empty too.

**Apache2 access.log:**
> 88.21.221.102 - - [08/Feb/2019:09:34:50 +0100] "POST /es/index.php?controller=product&token=1a264b0b89c1ace25725e7591ff71001&id_product=1898&id_customization=0&qty=2 HTTP/1.1" 500 10082 "https://cliclight.com/es/lamparas-led-de-techo/plafon-led/plafon-led-eye-18W" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"

**Comment by NicolasSmit** [comment] 2019-02-20 10:29
I'm also facing this issue on Prestashop 1.7.5. 
I've tried to disable and clear the cache, enable / disable friendly urls, but nothing changes. 
Here's a thing I've noticed in the console : 
![image](https://user-images.githubusercontent.com/18512733/53085238-b7b7e600-3502-11e9-9876-ef2c486c83e0.png)
Product id is different in the request done to the server !
Anyone has an idea ?

**Comment by khouloudbelguith** [comment] 2019-02-20 11:13
Hi @NicolasSmit,

No, I did not manage to reproduce the issue when a friendly URL is disabled.
https://drive.google.com/file/d/1tkGWrAd-3yqictvK3zD_zkqG47eUFn35/view
Thanks!

**Comment by NicolasSmit** [comment] 2019-02-20 15:49
Here's a demo : 
https://www.useloom.com/share/7db66519ab774e95b776a18b6dc615d2

**Comment by NicolasSmit** [comment] 2019-02-21 22:58
I fixed the issue by cleaning the cache once again.

**Comment by khouloudbelguith** [comment] 2019-02-22 08:04
@NicolasSmit, thanks for your feedback!

**Comment by davideapvd** [comment] 2019-03-06 13:10
Hello, 
with presashop 1.7.5.1 and nginx with friendly urls enabled the error "An error occurred while processing your request" appears when changing product size or colour, it doesn't when frienly urls are disabled, I think it could be related to the way the request is made, when clean urls are enabled the xhr request is performed at /it/index.php?controller=product&token=5bb1ef063e5b76dbeaaeedc5cae8dd73&id_product=19&id_customization=0&group%5B1%5D=2&group%5B2%5D=7&qty=1  (notice the language prefix).

please let me know if this could be resolved through some different nginx configuration.

` # Redirect 404 errors to prestashop
    error_page 404 /index.php?controller=404;
    # HSTS (Force clients to interact with your website using HTTPS only)
    # For enhanced security, register your site here: https://hstspreload.org/
    # WARNING: Don't use this if your site is not fully on HTTPS!
    # add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" preload; always;

    # Cloudflare / Max CDN fix
    location ~* \.(eot|otf|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
    }

    # Do not save logs for these
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /robots.txt {
        auth_basic off;
        allow all;
        log_not_found off;
        access_log off;
    }

    location / {
        # Redirect pretty urls to index.php
        try_files $uri $uri/ /index.php?$args;

        # Images
        rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
        rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
        rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
        rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
        rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
        # AlphaImageLoader for IE and fancybox
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

        # Web service API
        rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

        # Installation sandbox
        rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
    }

    # File security
    # .htaccess .DS_Store .htpasswd etc
    location ~ /\. {
        deny all;
    }
    # Source code directories
    location ~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor)/ {
        deny all;
    }
    # Prevent exposing other sensitive files
    location ~ \.(yml|log|tpl|twig|sass)$ {
        deny all;
    }

    # Prevent injection of php files
    location /upload {
        location ~ \.php$ {
            deny all;
        }
    }
    location /img {
        location ~ \.php$ {
            deny all;
        }
    }
    # PHP FPM part
    location ~ [^/]\.php(/|$) {
        # Verify that the file exists, redirect to index if not
        try_files $fastcgi_script_name /index.php$uri&$args;

        fastcgi_index  index.php;

        # Envirnoment variables for PHP
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        include       fastcgi_params;

        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # [REQUIRED EDIT] Connection to PHP-FPM - choose one
        # fastcgi_pass 127.0.0.1:9000;
        fastcgi_pass $phpsock;

        fastcgi_keep_conn on;
        fastcgi_read_timeout 320s;
        fastcgi_send_timeout 320s;

        # In case of long loading or 502 / 504 errors
        # fastcgi_buffer_size 256k;
        # fastcgi_buffers 256 16k;
        # fastcgi_busy_buffers_size 256k;
        client_max_body_size 10M;
    }
`

**Comment by khouloudbelguith** [comment] 2019-03-06 13:14
Hi @centoasa,

As said before if you are using Nginx make sure you enable the `mod_rewrite`.
This issue occurs when `mod_rewrite` is not enabled on your server.
Thanks!

**Comment by davideapvd** [comment] 2019-03-06 13:20
hi @khouloudbelguith 
mod_rewrite is an apache specific module, it has no sense for nginx. I saw that probably this modification to the nginx configuration solves the problem, it should be done for each supported language, put before the various locations (as suggested here https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist):

    # [REQUIRED EDIT IF MULTILANG]
     rewrite ^/it$ /it/ redirect;
     rewrite ^/it/(.*) /$1;
     rewrite ^/gb$ /gb/ redirect;
     rewrite ^/gb/(.*) /$1;
  

> Hi @centoasa,
> 
> As said before if you are using Nginx make sure you enable the `mod_rewrite`.
> This issue occurs when `mod_rewrite` is not enabled on your server.
> Thanks!

**Comment by davideapvd** [comment] 2019-03-06 13:23
hi @khouloudbelguith 
mod_rewrite is an apache specific module, it has no sense for nginx. I saw that probably this modification to the nginx configuration solves the problem, it should be done for each supported language, put before the various locations (as suggested here https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist):

    # [REQUIRED EDIT IF MULTILANG]
     rewrite ^/it$ /it/ redirect;
     rewrite ^/it/(.*) /$1;
     rewrite ^/gb$ /gb/ redirect;
     rewrite ^/gb/(.*) /$1;

**Comment by khouloudbelguith** [comment] 2019-03-06 13:31
@davideapvd,

Thanks for these clarifications.
About the `nginx.conf.dist` file, you need to write your own rules, as we do for Apache.
More because it's an example and you can customize this part by everything you want.
Thanks!

**Comment by ttoine** [comment] 2019-03-06 13:37
should we share some best practice configuration for nginx in the devdoc?

**Comment by davideapvd** [comment] 2019-03-06 13:44
> should we share some best practice configuration for nginx in the devdoc?

if I could add some feedback, I remember I had to change the [suggested](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist) configuration because various things broke,  is that a tested and valid config? For example the img rewrite block is different from what I'm currently using, and if I change it back to the docs config all products page are 404.

**Comment by matks** [comment] 2019-03-06 13:48
> > should we share some best practice configuration for nginx in the devdoc?
> 
> if I could add some feedback, I remember I had to change the [suggested](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist) configuration because various things broke, is that a tested and valid config? For example the img rewrite block is different from what I'm currently using, and if I change it back to the docs config all products page are 404.

It is a tested config though 🤔 but nothing is bug-free, we would be very happy to have your feedback 👍

**Comment by davideapvd** [comment] 2019-03-06 13:56
> > > should we share some best practice configuration for nginx in the devdoc?
> > 
> > 
> > if I could add some feedback, I remember I had to change the [suggested](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist) configuration because various things broke, is that a tested and valid config? For example the img rewrite block is different from what I'm currently using, and if I change it back to the docs config all products page are 404.
> 
> It is a tested config though thinking but nothing is bug-free, we would be very happy to have your feedback +1

please let me know if I could add something to my previous reply in order reproduce the error and test the config in a shared environment, do you use a docker image to test the config maybe? I should precise that my first config example is a live config we are using now in production, if in a staging server I change the first location / {} block that contains all the images rewrite rules I get 404 on all product pages, but I would like to confirm this in a clean environment.

**Comment by matks** [comment] 2019-03-07 09:40
> > > > should we share some best practice configuration for nginx in the devdoc?
> > > 
> > > 
> > > if I could add some feedback, I remember I had to change the [suggested](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist) configuration because various things broke, is that a tested and valid config? For example the img rewrite block is different from what I'm currently using, and if I change it back to the docs config all products page are 404.
> > 
> > 
> > It is a tested config though thinking but nothing is bug-free, we would be very happy to have your feedback +1
> 
> please let me know if I could add something to my previous reply in order reproduce the error and test the config in a shared environment, do you use a docker image to test the config maybe? I should precise that my first config example is a live config we are using now in production, if in a staging server I change the first location / {} block that contains all the images rewrite rules I get 404 on all product pages, but I would like to confirm this in a clean environment.

Hi ! I checked yesterday, for a FR shop being run inside a docker container ([official image](https://github.com/PrestaShop/docker)) I dont reproduce your issue, product pages are OK. Are you testing with another language (not FR) ? then you must update the [related config block](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist#L103): our config is a template that must be customized for your specific needs

**Comment by davideapvd** [comment] 2019-03-07 09:45
> > > > > should we share some best practice configuration for nginx in the devdoc?
> > > > 
> > > > 
> > > > if I could add some feedback, I remember I had to change the [suggested](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist) configuration because various things broke, is that a tested and valid config? For example the img rewrite block is different from what I'm currently using, and if I change it back to the docs config all products page are 404.
> > > 
> > > 
> > > It is a tested config though thinking but nothing is bug-free, we would be very happy to have your feedback +1
> > 
> > 
> > please let me know if I could add something to my previous reply in order reproduce the error and test the config in a shared environment, do you use a docker image to test the config maybe? I should precise that my first config example is a live config we are using now in production, if in a staging server I change the first location / {} block that contains all the images rewrite rules I get 404 on all product pages, but I would like to confirm this in a clean environment.
> 
> Hi ! I checked yesterday, for a FR shop being run inside a docker container ([official image](https://github.com/PrestaShop/docker)) I dont reproduce your issue, product pages are OK. Are you testing with another language (not FR) ? then you must update the [related config block](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist#L103): our config is a template that must be customized for your specific needs

Can you confirm pretty urls are enabled? Maybe next week I'll have more time to test this, thanks for now.

**Comment by lapitskiy** [comment] 2019-04-17 13:47
**i have same problem**
i see this error when try change quantity
_an error occurred while processing your request_
this issue #9390 did't help

cache off (set Force compilation)
cache clear (and var/cache)
cookie clear (test another browser)
url rewriting - off
combination - off
multilang - off

![Скриншот 2019-04-17 01_16_47](https://user-images.githubusercontent.com/7946611/56292676-47a79400-6130-11e9-98a0-eaa7b9b3308a.png)
![Скриншот 2019-04-17 00_41_12](https://user-images.githubusercontent.com/7946611/56292678-47a79400-6130-11e9-95f6-45ad327ccbd1.png)

link https://topremeshok.ru/index.php?controller=product&token=76cc4927857d9d0d7d8d799eba382add&id_product=866&id_customization=0&qty=2

**Additionnal information**
PrestaShop version: PS 1.7.5.1
Apache/2.4.7
PHP version: 5.6.40

**Comment by marionf** [comment] 2020-10-14 10:08
@matks @PierreRambaud 

It seems we didn't reproduced this issue. 
Do we need to update the devdoc to give some advices about the nginx configuration or try to reproduce this issue ?

**Comment by marionf** [comment] 2020-10-26 13:50
Hello everyone,

Unfortunely we tried to reproduce this issue many times but without success.
There is some informations / elements missing to be able to reproduce this issue.
If you have this problem please open a new issue with more details.
As you know, we are not able to fix an issue if we can't reproduce it.

Thank you for your help

**Closed as completed by marionf** 2020-10-26 13:50 UTC
Labels: Bug, Minor, FO, Can't reproduce, SEO & URLs, Topwatchers, Combinations, 1.7.5.0

**Comment by Fukitsune** [comment] 2022-02-28 14:28
Hello, Exactly same problem ;)
