### ISSUE TITLE
Export cart only on the displayed page, not all pages

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#19096] opened 2020-05-12 14:25 UTC
#### Describe the bug

In BO > Orders > Shopping Carts, when there is a lot of cart and pagination is active, when trying to export carts, only the displayed page of the pagination is exported, instead of all carts.

#### Expected behavior

All carts should be exported (all carts corresponding to the applied filters, if any).

#### Steps to Reproduce

1. Go to BO > Orders > Shopping Carts, with at least more than 20 carts
2. Set pagination to 20 carts per page, so you have more than one page
3. Export carts : Only the page displayed is exported (so 20 carts if you're on first page), instead of all carts

**Screenshots**

On this example, I have 50 carts : 
![export cart only page seen](https://user-images.githubusercontent.com/55688534/81703235-970fdf00-946c-11ea-8f72-6abbcbe8b64a.png)

When I export, I have this CSV, with only 20 carts instead of 50 : 
https://drive.google.com/file/d/17lPjCe1tQD97mWKKqgjFlIMJCQxtWCu4/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7 at least
* PHP version: N/A

**Comment by micka-fdz** [comment] 2020-05-18 15:59
Hello, I think the problem is not only about carts.

It seems that the following are impacted : customers, categories, manufacturers, suppliers, abandoned carts... See https://github.com/PrestaShop/PrestaShop/issues/16328

**Comment by khouloudbelguith** [comment] 2020-08-26 11:19
Ping @PrestaShop/prestashop-product-team what do you think? it is a Bug or a wanted behavior?

Thanks!

**Comment by marionf** [comment] 2020-08-26 15:58
Duplicate of #19527

**Closed as completed by marionf** 2020-08-26 15:58 UTC
Labels: Bug, Minor, BO, Duplicate, Shopping carts, 1.7.7.0, 1.7.6.4
