### ISSUE TITLE
500 server error website tab

### ISSUE THREAD

**Issue by osdijon** [PrestaShop/PrestaShop#30782] opened 2023-01-09 19:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After updating prestashop 8 and php 8 with ionos, my website displays "500 servor error" every time I click on any tab

### Expected behavior

When I click on a tab of my website, the page is displayed with the articles corresponding to the tab.

### Steps to reproduce

Go to a website, click on a tab for the page to display the content of the tab

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

8

**Comment by kpodemski** [comment] 2023-01-09 19:40
Hello @osdijon 

It's impossible to know what's going on because "500 internal server" error is just a generic way for the server to display that something went wrong. You should check your server error logs.

Also, the "Steps to reproduce" says:
>Go to a website, click on a tab for the page to display the content of the tab

You assume that somebody here has access to your website, and that's not the case. If you wish to provide project members with more details about the bug you encounter, you may want to create a new Issue but with all the necessary details:
- from which version you upgraded?
- what does the server's error log say?

I'm closing this Issue because it is invalid and irreproducible.

**Closed as not planned by kpodemski** 2023-01-09 19:40 UTC
Labels: Bug, Invalid
