### ISSUE TITLE
Product SEO Meta Description Javascript error when adding . (dot)

### ISSUE THREAD

**Issue by SharmPRO** [PrestaShop/PrestaShop#13933] opened 2019-05-23 08:43 UTC
**Describe the bug**
Javascript error when adding . (dot) to Product SEO Description preventing other function to work properly.

**To Reproduce**
1. Go to Product -> SEO
2. Add to SEO Description a . (dot) and console will show javascript error.
main.bundle.js:275 Uncaught Error: Syntax error, unrecognized expression: Le Gift Card o Carte Regalo rappresentano un modo pratico, veloce e di tendenza per effettuare graditissimi regali ad amici e parenti adatte a tutte le occasioni e disponibili in vari tagli per tutte le esigenze.
    at Function.t.error (main.bundle.js:275)
    at t.tokenize (main.bundle.js:275)
    at t.select (main.bundle.js:275)
    at Function.t [as find] (main.bundle.js:275)
    at De.fn.init.find (main.bundle.js:275)
    at new De.fn.init (main.bundle.js:275)
    at De (main.bundle.js:275)
    at HTMLTextAreaElement.i (main.bundle.js:275)
    at HTMLTextAreaElement.dispatch (main.bundle.js:275)
    at HTMLTextAreaElement.g.handle (main.bundle.js:275)

**Screenshots**
![screenshot-www cosmetolando it-2019 05 23-10-35-50](https://user-images.githubusercontent.com/5299863/58238018-b935bc00-7d46-11e9-8f3e-08e7bfe7a21d.jpg)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-23 09:15
Hi @SharmPRO,

The issue is fixed with this PR: #11923, it is fixed in PS1.7.5.1
Your ticket is a duplicate of #11911
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-23 09:15
Duplicate of #11911

**Closed as completed by khouloudbelguith** 2019-05-23 09:15 UTC
Labels: Duplicate
