### ISSUE TITLE
Default theme is built with an alpha version of bootstrap which make every theme on the market like this

### ISSUE THREAD

**Issue by groukx** [PrestaShop/PrestaShop#28142] opened 2022-04-05 16:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Sorry but every issue that report that problem is closed and it is still not fixed.
Bootstrap 4 alpha version has some weird behaviour, between the boostrap official doc for version 3 and 4.
There is no official bootstrap documentation that support this version and even a beta version should not be used on a production website.
What is the most downside is that most of the theme that is available on the market use that bootstrap broken version without providing the webpack feature to change it.

### Expected behavior

uptodate bootstrap RC version

### Steps to reproduce

just go to the theme folder

### PrestaShop version(s) where the bug happened

all 1.7

**Comment by Hlavtox** [comment] 2022-04-06 06:15
@groukx New theme built on Boostrap 5 is 75% done.

- https://github.com/PrestaShop/hummingbird
- https://build.prestashop.com/news/new-theme-announce/

**Comment by hibatallahAouadni** [comment] 2022-04-06 07:28
Hello @groukx 

As @Hlavtox mentioned above we will use Bootstrap 5 in the new major release 8.0.0.
So don't worry 😉 
@NeOMakinG could you please explain to @groukx more about the new theme 🙏 

Thanks!

**Comment by matks** [comment] 2022-04-06 08:42
> Sorry but every issue that report that problem is closed and it is still not fixed.

Yes because the solution is already being built

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14533 you can read all the pros and cons about this topic in https://github.com/PrestaShop/PrestaShop/issues/14533 .

The solution we chose is to build a new theme as mentioned by @Hlavtox . This is the path we have chose, opening multiple github issues about Classic theme is not going to help 😉 .

@hibatallahAouadni for me this is a duplicate

**Comment by hibatallahAouadni** [comment] 2022-04-06 10:37
Hello @groukx 

We are aware of this issue as @matks mentioned above and it's already fixed. 
So, this issue is a duplicate of #14533. 
Please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-04-06 10:37
Duplicate of #14533

**Closed as completed by hibatallahAouadni** 2022-04-06 10:37 UTC
Labels: Bug, CO, Duplicate, Front-end, Invalid

**Comment by groukx** [comment] 2022-04-08 14:58
I don't understand @hibatallahAouadni. Right now, If i build a new theme and sell it, it is not on the prestashop 8.0, It is with the last stable version which is 1.7.8.5 and implement bootstrap alpha version.
So for the ecosystem, most of the theme that are on the market is built on top of a buggy bootstrap since almost 4 years. It's a huge problem.
I have been flooded by theme that does not do what bootstrap 4 documentation tell. Of course because there is no documentation of the alpha.
So Template monster don't provide the webpack files so what the community do? Avoid buying a theme?

**Comment by Oksydan** [comment] 2022-04-08 16:19
@groukx you can build theme based on bootstrap 4.6. Just makes sure that you cover backwards compatibility.

**Comment by Hlavtox** [comment] 2022-04-08 16:34
@groukx I have a theme on 1.7.6 working perfectly fine with Boostrap 4.6. @Oksydan Also has a starter theme with bootstrap 4.6. So I don't really understand what you mean?

What you want us to do? New theme is under development for several months now and will be released soon.

**Comment by NeOMakinG** [comment] 2022-04-08 17:50
> I don't understand @hibatallahAouadni. Right now, If i build a new theme and sell it, it is not on the prestashop 8.0, It is with the last stable version which is 1.7.8.5 and implement bootstrap alpha version. So for the ecosystem, most of the theme that are on the market is built on top of a buggy bootstrap since almost 4 years. It's a huge problem. I have been flooded by theme that does not do what bootstrap 4 documentation tell. Of course because there is no documentation of the alpha. So Template monster don't provide the webpack files so what the community do? Avoid buying a theme?

You said it, most of the themes are based on a specific bootstrap version, if we update it, we break most of the themes because the API did change a lot between the alpha and the stable one. It's a choice from the past that we paid for many years.

But you are free to fork it, update it to 4.6 as @Hlavtox and @Oksydan said, and maintain it because we can't do it without having hundreds of problems related to this choice, we did the choice to start on a clean base, with the latest bootstrap version and we're working since many months on it, and it will be compatible with the latest 1.7 version, in case you are not aware of that point :)

**Comment by groukx** [comment] 2022-04-11 12:17
> 

@NeOMakinG Thanks for your response. I understand what you said. It's too late, the mistake was done and we pay for many years. Also, the 1.7 theme introduced the feature of compilation with webpack. It's a shame that themes for prestashop 1.7 is in sell without this feature. Maybe it's time to introduce a theme feature validator for the 8.0 realease Or a mechanism that tell clearly what feature is broken or not when you purchase a theme.
