### ISSUE TITLE
An error occurred while processing your request 1.7.5.0

### ISSUE THREAD

**Issue by idimash** [PrestaShop/PrestaShop#12325] opened 2019-01-28 07:50 UTC
Hi!
1. Go to product page in prestashop demo: .../men/1-1-hummingbird-printed-t-shirt.html#/1-razmer-s/8-cvet-belyj
2. Click on other color
3. See error "An error occurred while processing your request"
![presta bug](https://user-images.githubusercontent.com/12410518/51821149-d7336880-22e0-11e9-9adb-2dc2b6e94718.png)

prestashop 1.7.5.0, nginx 1.15.8, php 7.2.14

[nginx config](https://github.com/PrestaShop/PrestaShop/files/2801919/vhost.txt)

**Comment by khouloudbelguith** [comment] 2019-01-28 09:30
Hi @idimash,

I did not manage to reproduce the issue with PS1.7.5.0 & nginx/1.14.0.
I attached a video record.
https://drive.google.com/file/d/1_NYYV9CF8R73Bryyqb2xI6FgLx6ujxQG/view
here's my nginx configuration
```
server {
	listen   80; ## listen for ipv4; this line is default and implied
	listen   [::]:80 default ipv6only=on; ## listen for ipv6

	root /var/www/html;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name _;
	
	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

	# Add stdout logging
	# Add stdout logging
        error_log /var/log/nginx/error.log info;
        access_log /var/log/nginx/access.log;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;
        #set_real_ip_from 172.16.0.0/12;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
		try_files $uri $uri/ /1750/index.php?$args;
		# Images
                rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
                rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
                rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
                rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
		# AlphaImageLoader for IE and fancybox
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

        # Web service API
        rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

        # Installation sandbox
        rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
	}
	# Gzip Settings, convert all types.
        gzip on;
        gzip_vary on;
        gzip_proxied any;

        # Can be enhance to 5, but it can slow you server
        # gzip_comp_level    5;
        # gzip_min_length    256;

        gzip_types
            application/atom+xml
            application/javascript
            application/json
            application/ld+json
            application/manifest+json
            application/rss+xml
            application/vnd.geo+json
            application/vnd.ms-fontobject
            application/x-font-ttf
            application/x-web-app-manifest+json
            application/xhtml+xml
            application/xml
            font/opentype
            image/bmp
            image/svg+xml
            image/x-icon
            text/cache-manifest
            text/css
            text/plain
            text/vcard
            text/vnd.rim.location.xloc
            text/vtt
            text/x-component
            text/x-cross-domain-policy;

        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
	# Symfony controllers
        location /1750/admin-dev/ {                                  # [REQUIRED EDIT] the name of your admin directory
            if (!-e $request_filename) {
                rewrite ^/.*$ /1750/admin-dev/index.php last;   # [REQUIRED EDIT] the name of your admin directory
            }
        }

        # Cloudflare / Max CDN fix
        location ~* \.(eot|otf|ttf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin *;
        }

        # Do not save logs for these
        location = /1750/favicon.ico {
            log_not_found off;
            access_log off;
        }
        location = /1750/robots.txt {
            auth_basic off;
            allow all;
            log_not_found off;
            access_log off;
        }


	error_page 404 /1750/index.php?controller=404;

        location ^~ /sad.svg {
            alias /var/www/errors/sad.svg;
            access_log off;
        }
        location ^~ /twitter.svg {
            alias /var/www/errors/twitter.svg;
            access_log off;
        }
        location ^~ /gitlab.svg {
            alias /var/www/errors/gitlab.svg;
            access_log off;
        }

	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php$ {
                try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_index index.php;
		include fastcgi_params;
	}

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg)$ {
                expires           5d;
        }

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off; 
    		deny all;
	}
        
	location ^~ /.well-known {
                allow all;
                auth_basic off;
        }

}

```
Your ticket is a duplicate of #10178
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-28 09:30
Duplicate of #10178

**Closed as completed by khouloudbelguith** 2019-01-28 09:30 UTC
Labels: Duplicate

**Comment by idimash** [comment] 2019-01-28 09:43
This bug is reproduced when enabled URL rewriting.
But in my case, prestashop reports that the server does not support  URL rewriting.
![presta bug 2](https://user-images.githubusercontent.com/12410518/51827242-95f78480-22f1-11e9-90ae-1c8556ee89fa.png)
Thanks!

**Comment by AlexCrete** [comment] 2019-05-19 22:12
Hello, 
I have this error only if a product has some RELATED PRODUCTS, as here:
https://www.luzibiza.com/dressesjumpsuits/83-227-rio-dress.html#/1-sizes_for_clothes-s

But everything is all right if there is no related product as, for example here:
https://www.luzibiza.com/dressesjumpsuits/83-227-rio-dress.html#/1-sizes_for_clothes-s

Could you, please, have a look at this problem?

I've tried the solution you described up here but nothing chandged - it seems my case has nothing to do with nginx.

I use 1.7.5.0

Thank you in advance

**Comment by AlexCrete** [comment] 2019-05-19 22:15
Hello,

I have this error only if a product has some RELATED PRODUCTS, as here:
https://www.luzibiza.com/dressesjumpsuits/144-258-trapeze-dress.html#/1-sizes_for_clothes-s

But everything is all right if there is no related product as, for example here:
https://www.luzibiza.com/dressesjumpsuits/83-227-rio-dress.html#/1-sizes_for_clothes-s

Could you, please, have a look at this problem?

I've tried the solution you described up here but nothing chandged - it seems my case has nothing to do with nginx.

I use 1.7.5.0

Thank you in advance

**Comment by khouloudbelguith** [comment] 2019-05-20 10:37
@AlexCrete, 
This issue is currently closed, can you open a new one with more information about your configuration.
Thanks!

**Comment by AlexCrete** [comment] 2019-05-20 11:48
Hi,
I opened the new one:
An error occurred while processing your request for products with RELATED PRODUCTS #13874
