### ISSUE TITLE
Presta error 500 at 67% of installation.

### ISSUE THREAD

**Issue by admin123456789012** [PrestaShop/PrestaShop#25243] opened 2021-07-05 15:47 UTC
#### Describe the bug

Can't install presta there is error 500 at installation

1: HTTP 200 - parsererror -
Warning: include(/public_html/testpresta/var/cache/dev/ContainerVwxzgwc/appDevDebugProjectContainer.php): failed to open stream: No such file or directory in /public_html/testpresta/var/cache/dev/appDevDebugProjectContainer.php on line 7

Warning: include(): Failed opening '/public_html/testpresta/var/cache/dev/ContainerVwxzgwc/appDevDebugProjectContainer.php' for inclusion (include_path='/public_html/testpresta/vendor/pear/pear_exception:/public_html/testpresta/vendor/pear/console_getopt:/public_html/testpresta/vendor/pear/pear-core-minimal/src:/public_html/testpresta/vendor/pear/archive_tar:.:/usr/local/php73-fpm/lib/php') in //public_html/testpresta/var/cache/dev/appDevDebugProjectContainer.php on line 7

Fatal error: Uncaught Error: Call to a member function set() on null in //public_html/testpresta/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:667 Stack trace: #0 //public_html/testpresta/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #1 //public_html/testpresta/install/init.php(98): Symfony\Component\HttpKernel\Kernel->boot() #2 /public_html/testpresta/install/index.php(42): require_once('/home/platne/se...') #3 {main} thrown in /public_html/testpresta/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 667

I tested on 1.7.7.1 and 1.7.7.5. The 1.7.7.1 version worked weak ago now i'ts not working only can be installed by CLI. There were no changes on the server, I knowe because im hosting provider.

I wonder if this bug is connected with clear cache bug on php-fpm?

#### Expected behavior

Sucesfully installed presta by GUI.

#### Steps to Reproduce

Just clikc to install presta.

#### Additional information

* PrestaShop version: Tested from 1.7.7.1 to 1.7.7.5
* PHP version: Tested from 7.0 to 7.4 with apache and php-fpm

**Comment by hibatallahAouadni** [comment] 2021-07-05 16:14
Hello @admin123456789012 

We are aware of this issue, the Addons Team is already work on it. This issue is a duplicate of #25191. 
This issue is related to Addons API and not to PS Core.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-05 16:14
Duplicate of #25191

**Closed as completed by hibatallahAouadni** 2021-07-05 16:14 UTC
Labels: Duplicate
