### ISSUE TITLE
SMTP gmail not working

### ISSUE THREAD

**Issue by Macrisu** [PrestaShop/PrestaShop#18623] opened 2020-04-14 16:06 UTC
#### Describe the bug

After setting up the SMTP settings (app password), it does nothing.

#### Expected behavior

Send test mail

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

![smtp](https://user-images.githubusercontent.com/16325429/79247247-f3d6a480-7e82-11ea-9240-fec5f6b922f4.jpg)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-04-16 07:36
Hi @Macrisu,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.4.
![image](https://user-images.githubusercontent.com/16067358/79427919-b6c6fb00-7fc5-11ea-84f3-db143c00a790.png)

I attached a screen record
https://drive.google.com/file/d/1N0p9fRmLZ2Kjg0Rys-dZO2Xdo6i3ivSk/view?usp=sharing
The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks to check with your host & feedback.

**Comment by Macrisu** [comment] 2020-04-25 17:32
Hello!
I've upgraded to 1.7.6.5
Still not working, no error anywhere to look for!
When I press "Send test mail", I get a circle spinning slowly.

Using the debug console, when I press to send a test email, I get an error

I tried with Gmail or another SMTP, as my email is not on the same server.
Same symptoms.
How can I determine the errors?

**Comment by Macrisu** [comment] 2020-04-25 22:19
I've tried exactly your settings, I cannot send email

I tried to use the contact form from the site and I get this error on submit:

`
(1/1) UndefinedMethodExceptionAttempted to call an undefined method named "newInstance" of class "Swift_Message".
--
in Mail.php line 297

`

![Screenshot 2020-04-26 at 02 10 13](https://user-images.githubusercontent.com/16325429/80292913-2f1a8280-8763-11ea-9164-7c668d0e6022.jpg)
![Screenshot 2020-04-26 at 02 09 55](https://user-images.githubusercontent.com/16325429/80292916-33df3680-8763-11ea-8bd5-efee09b55e5f.jpg)


See this,please https://codereviewvideos.com/blog/swift-message-new-instance-not-found/

*** I did run _composer update_ on my Prestashop installation ***
Can this be the culprit?

**Comment by Macrisu** [comment] 2020-04-25 23:24
I think I found a problem.
Prestashop comes with Swiftmailer 5.4.12
composer update bumped the version to 6.2.2 (2019-11-12)

> 6.0.0 (2017-05-19)
------------------

 * added Swift_Transport::ping()
 * removed Swift_Mime_HeaderFactory, Swift_Mime_HeaderSet, Swift_Mime_Message, Swift_Mime_MimeEntity,
   and Swift_Mime_ParameterizedHeader interfaces
 * removed Swift_MailTransport and Swift_Transport_MailTransport
 * removed Swift_Encoding
 * removed the Swift_Transport_MailInvoker interface and Swift_Transport_SimpleMailInvoker class
 * removed the Swift_SignedMessage class
 * **removed newInstance() methods everywhere**

**Comment by Macrisu** [comment] 2020-04-26 00:25
I've made it!

1. I've put back the original, old files of Swiftmailer 5.4.12
2. Got error, but the main culprit now was SE_Linux (CentOS7)

`Permission denied #13 smtp`

fixed with 
`setsebool -P httpd_can_sendmail on`

**Comment by sarahdib** [comment] 2020-04-28 09:48
Hello @Macrisu 

Since you fixed the problem can we close the issue ?

Thank you

**Closed as completed** 2020-04-28 10:03 UTC
Labels: Bug, BO, Email, No change required, 1.7.6.4
