### ISSUE TITLE
Migration - Product block on order page bugs

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17089] opened 2020-01-09 15:24 UTC
**Describe the bug**
 Following the merge of https://github.com/PrestaShop/PrestaShop/pull/16150, here is the list of the remaining bugs on this page :

Adding several "small" discount with a total greater than the order total will raise another Symfony Exception, with a small difference : The last discount will still be added even if it raise an exception, but it will raise another exception when trying to delete it
* **Bug** :negative_squared_cross_mark: : I still have the exception when adding free shipping discount (it's now OK when adding only "amount" discounts) => This bug also exist in Legacy

* **New bug** :negative_squared_cross_mark: When there is a product which is out of stock, it is impossible to delete it from the order (this also happens in Legacy)
* **New bug** :negative_squared_cross_mark: When editing a product, if the quantity is set higher than available quantity, the field "available" should becomes red. Can you confirm @TristanLDD ? 
* **New bug** :negative_squared_cross_mark: It is not possible to edit a virtual product : https://drive.google.com/file/d/1QtMeLer98qEFD5jXEEO0kBUHswnr4Wcn/view?usp=sharing (this also happens in Legacy)
 * When adding a discount on an order on which at least one invoice has already been created, the user can choose the invoice on which the discount must apply. In the dropdown, in Legacy, each line is "[Invoice Number] - [Invoice Amount]. In migrated page, Invoice Amount is missing.
* A typo (in Legacy and migrated page) bug, on adding a discount popin, under "Apply to all invoices", in the help text :
"If you chooses to create this discount for all invoices, only one discount will be created per order invoice." should be "If you choose to create this discount for all invoices, only one discount will be created per order invoice." => This bug also exist in Legacy,.
* New bug : On pagination, when I have 8 product, if I add a 9th product, it will be added on the bottom of page 1, AND on page 2 (the sum below the product block is still OK). See screenshots : 
![pr16150 pagination 9e element](https://user-images.githubusercontent.com/55688534/72056147-56406780-32cc-11ea-8ab9-31e33bc53e02.png)
![pr16150 pagination 9e element 2](https://user-images.githubusercontent.com/55688534/72056160-5b9db200-32cc-11ea-8718-e03414624e17.png)
* When adding a product, if a new invoice is created, the "shipping block" displayed is not deleted after creating the invoice

Please note that there might still be some bugs out there...

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by zuk3975** [comment] 2020-01-16 11:54
* >  New bug negative_squared_cross_mark When editing a product, if the quantity is set higher than available quantity, the field "available" should becomes red. Can you confirm @TristanLDD ?

* > New bug negative_squared_cross_mark It is not possible to edit a virtual product : https://drive.google.com/file/d/1QtMeLer98qEFD5jXEEO0kBUHswnr4Wcn/view?usp=sharing (this also happens in Legacy)

* > When adding a discount on an order on which at least one invoice has already been created, the user can choose the invoice on which the discount must apply. In the dropdown, in Legacy, each line is "[Invoice Number] - [Invoice Amount]. In migrated page, Invoice Amount is missing.

* > A typo (in Legacy and migrated page) bug, on adding a discount popin, under "Apply to all invoices", in the help text :
"If you chooses to create this discount for all invoices, only one discount will be created per order invoice." should be "If you choose to create this discount for all invoices, only one discount will be created per order invoice." => This bug also exist in Legacy,.

* > New bug : On pagination, when I have 8 product, if I add a 9th product, it will be added on the bottom of page 1, AND on page 2 (the sum below the product block is still OK)

https://github.com/PrestaShop/PrestaShop/pull/17220

**Comment by atomiix** [comment] 2020-01-16 14:13
>New bug ❎ When there is a product which is out of stock, it is impossible to delete it from the order (this also happens in Legacy)

>Bug ❎ : I still have the exception when adding free shipping discount (it's now OK when adding only "amount" discounts) => This bug also exist in Legacy

@Robin-Fischer-PS I can't reproduce those ones

**Comment by zuk3975** [comment] 2020-01-17 08:52
> > New bug negative_squared_cross_mark When there is a product which is out of stock, it is impossible to delete it from the order (this also happens in Legacy)
> 
> > Bug negative_squared_cross_mark : I still have the exception when adding free shipping discount (it's now OK when adding only "amount" discounts) => This bug also exist in Legacy
> 
> @Robin-Fischer-PS I can't reproduce those ones

me too

**Comment by zuk3975** [comment] 2020-01-17 09:06
@Robin-Fischer-PS I guess the following is also a bug: 
- When adding the same product (identical to one that already exists in order) the quantity should be increased instead of adding new product row. (both- migrated and legacy page)

by the way could you please explain more detailed this:

> When adding a product, if a new invoice is created, the "shipping block" displayed is not deleted after creating the invoice

Why should the shipping block be deleted? It seems legacy is not doing so either

**Comment by Robin-Fischer-PS** [comment] 2020-01-17 09:31
@zuk3975 

For the first question, I agree with you, but it's more a question for product team, I'm going to check that with them.

For the second one, I expressed myself poorly : It's the highlighted shipping block in this screenshot that should not appear after creating a new invoice. But I checked with @atomiix , and he's already on it !
![create order shipping block](https://user-images.githubusercontent.com/55688534/72600465-fbce8900-3913-11ea-811b-564d3bc1a0d1.png)

**Comment by zuk3975** [comment] 2020-01-17 09:35
* > New bug : On pagination, when I have 8 product, if I add a 9th product, it will be added on the bottom of page 1, AND on page 2 (the sum below the product block is still OK)

https://github.com/PrestaShop/PrestaShop/pull/17220

**Comment by MatShir** [comment] 2020-01-17 09:38
> @Robin-Fischer-PS I guess the following is also a bug:
> 
> * When adding the same product (identical to one that already exists in order) the quantity should be increased instead of adding a new product row. (both- migrated and legacy page)

hey @zuk3975 @atomiix, it depends if it is the same development time. If it is then it would be great. It totally makes sense to add the quantity but it also considered to be a new feature since we want to feature freeze soon, we don't want any delays. Bc you need to check if the product has the same price, same combination and so on.

**Comment by TristanLDD** [comment] 2020-01-17 11:11
> * **New bug** ❎ When editing a product, if the quantity is set higher than available quantity, the field "available" should becomes red. Can you confirm @TristanLDD ?

Yes, confirmed!

**Comment by matks** [comment] 2020-02-12 16:56
So it seems that there is 3 bugs not done

> * **Bug** ❎ : I still have the exception when adding free shipping discount (it's now OK when adding only "amount" discounts) => This bug also exist in Legacy

🔴 **Not reproduced**

> * **New bug** ❎ When there is a product which is out of stock, it is impossible to delete it from the order (this also happens in Legacy)

🔴 **Not reproduced**

> * When adding a product, if a new invoice is created, the "shipping block" displayed is not deleted after creating the invoice

🔴 **Waiting for PM confirmation**

**Comment by matks** [comment] 2020-02-19 12:44
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17220

**Closed as completed by matks** 2020-02-19 12:44 UTC
Labels: Bug, develop, BO, Order, Regression, Fixed, migration, Must-have
