### ISSUE TITLE
Modules bug - error 500

### ISSUE THREAD

**Issue by francesco-arenaforge** [PrestaShop/PrestaShop#10458] opened 2018-09-17 11:00 UTC
I wanted to test a new Theme, I uploaded it but, during its installation, something went wrong and it showed me a page with this message: 

_**"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."**_

Now my website doesn't work anymore because some modules are not working properly. In fact, If I click on "Modules & Services" in my back office I have the same error page as above. The same error comes out if I try to do a search in my back office.

In the "information page", at the very bottom, there is the message: _"Changed/missing files have been detected: robots.txt"_ (See image below)

I have just started to use Prestashop and my site is still empty. The question is: there is a "RESET" to restart ALL and solve the problem?

Thank you in advance.
Frank

<img width="2039" alt="schermata 2018-09-17 alle 12 57 03" src="https://user-images.githubusercontent.com/43339086/45619362-4ec2d280-ba79-11e8-99b7-11be15d4149b.png">

PrestaShop version: 1.7.4.2
PHP version: 7.2.8
Current theme in use: classic (Default theme)

**Comment by khouloudbelguith** [comment] 2018-09-17 11:06
Hi @francesco-arenaforge,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

Best regards, Khouloud

**Comment by francesco-arenaforge** [comment] 2018-09-17 21:24
Hi Khouloud, 

I'm not so happy with your reply. 
Because I didn't ask you how to repair the new, not official, theme I tried to install but I asked you if there is a way to restore the default theme of Prestashop _(Quote: "The question is: there is a "RESET" to restart ALL and solve the problem?")_. Independently from the cause of the error, I think that Prestashop has a way to "reset" itself, but I don't know how.

In any case, I will cancel all the present installation and will install all again. I'm sure it will work.

Kind regards,
Frank

**Comment by khouloudbelguith** [comment] 2018-09-18 08:36
Hi @francesco-arenaforge,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by rdy4ever** [comment] 2018-09-18 13:39
Hi there. It looks like the theme you tried to install also installed some modules that may cause your problems. You should [enable debug mode](https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/) to see what modules cause problems and uninstall them.
Also, you could look in the 3rd party theme config file ([config/theme.yml](https://devdocs.prestashop.com/1.7/themes/getting-started/theme-yml/)) to see what modules it installed and uninstall them:
```
global_settings:
    modules:
      to_enable:
```

**Comment by francesco-arenaforge** [comment] 2018-09-18 22:23
I'm sorry, guys, too late. 
Since I had not made any other changes, I deleted and reinstalled everything. In any case, the theme that gave problems was the following: **Leo Trump Template 1723**. The malfunction was related to the main menu (which had disappeared) while the single pages could be loaded using the link "sitemap".

Thank you.
Kind regards,
Frank.

**Comment by khouloudbelguith** [comment] 2018-09-19 08:59
Hi @francesco-arenaforge,

Thanks for your feedback.
I could be a compatibility problem with 1.7.4.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-19 08:59 UTC
Labels: Theme & logo, No change required, 1.7.4.2
