### ISSUE TITLE
productcomments - Exception is thrown on develop when mode debug is enabled

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35846] opened 2024-04-05 13:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Only on branch develop of PS with mode debug enabled, I have an exception when I try to configure my productcomments module.
If I disable debug mode, it is OK.

<img width="1078" alt="Screenshot 2024-04-05 at 15 12 10" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d1186e92-ced1-4c6e-aad8-de906e27058f">

### Expected behavior

No exception should be displayed. The Configure page should be displayed correctly.

### Steps to reproduce

1. Go to BO > Advanced parameters > Enable Debug Mode
2. Go to Modules > Search productcomments
3. Click Configure :x:

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

productcomments v6.0.2, v6.0.3

**Comment by paulnoelcholot** [comment] 2024-04-08 05:34
Hello @florine2623,

I tried to reproduce your issue but I can't... @AureRita can you try to reproduce please?

**Comment by AureRita** [comment] 2024-04-09 08:40
Hi @florine2623 ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by AureRita** 2024-04-09 08:40 UTC
Labels: Bug, develop, BO, Modules, Productcomments, Invalid, Module
