### ISSUE TITLE
Registration form in Confirmation order page not working

### ISSUE THREAD

**Issue by dangelion** [PrestaShop/PrestaShop#19462] opened 2020-05-29 14:12 UTC
Hi, after placing an order I got the usual Confirmation order page with success message and so on. At the bottom of the page there's the registration form ("Save time on your next order, sign up now").

I've some questions and problems.

First of all: **the registration form doesn't work**, after submit the form it brings me to the login page without any messages of success or failure. Then I login with email and password given before but authentication failed. This happens also on the official Prestashop demo https://demo.prestashop.com/#/en/front Try it.

I searched online but found nothing. Please, someone knows how to solve?

Thanks

---

Also, some optimization questions:

1. Why the registration form asks again: first name, last name and email? Customer already gave them during the checkout process, it would be need just to ask the password
2. Asking again the email the user could give a different email from what he gave during the checkout. This causes to create a different account in which there isn't the placed order

**Comment by florine2623** [comment] 2020-05-29 14:30
Hi @dangelion ,

Thanks for the report. I managed to reproduce the issue on both PS 1.7.6.5 and PS 1.7.7.0.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

FYI - Steps to reproduce :
- Place an order as guest customer
- When order is complete, scroll down to Registration form
- Fill the Registration form
- User is being redirected to login page (no success or failure message)
- User can't log in with info provided in Registration form

Thanks!

**Comment by florine2623** [comment] 2020-05-29 14:39
Hi @PrestaShop/prestashop-product-team ,
Is it possible to get your knowledge on the 2 questions @dangelion asked regarding the optimization of the Registration Form ?

Thanks!

**Comment by dangelion** [comment] 2020-05-29 14:48
Thanks for answer @florine2623 Unfortunately I've not fixed that, I think it's a huge feature that needs to be solved and improved. Waiting for progress on this

**Comment by rdy4ever** [comment] 2020-06-03 13:27
Even more. If you do register an account after the order is placed, you will not have the order registered in your account.

**Comment by colinegin** [comment] 2020-06-03 15:13
Thanks @dangelion for warning us about this issue.
It was already listed here #14414, so your issue is a duplicate.
I'm closing it so that we can better focus on fixing it.
Do not hesitate to follow the EPIC #19543 if you want to add information.

Thanks !

**Closed as completed by colinegin** 2020-06-03 15:13 UTC
Labels: Bug, Minor, FO, Duplicate, 1.7.7.0, 1.7.6.5

**Comment by khouloudbelguith** [comment] 2020-10-08 10:00
Duplicate of #14414
