### ISSUE TITLE
Combination error after change color

### ISSUE THREAD

**Issue by malcek** [PrestaShop/PrestaShop#15801] opened 2019-10-02 19:17 UTC
I have found out that if you have 2 attribute
**color:**  black and red 
**size black:**  36, 38, 40, 42, 44
**size red:** 38,40,42,44
and if default combination is black/36 and if you change color to red you get an error, because red color doesen't have size 36. After that shop is freezing and until reload page you can't do anything

**To Reproduce**
see it on my site: https://trgovina-figura.si/si/zenske-string-hlacke-stella-s.html

**Screenshots**
![combination-error](https://user-images.githubusercontent.com/54998637/66074475-9075cc80-e559-11e9-98e9-89837f35b87c.PNG)
![combination-error2](https://user-images.githubusercontent.com/54998637/66074477-9075cc80-e559-11e9-87ec-8b074415cbfb.PNG)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-10-03 09:30
Hi @malcek,

This issue is fixed in the PS1.7.5.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9390 to fix the issue.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by malcek** [comment] 2019-10-03 10:23
Obviously it didn't fixed, because as you see I have version 1.7.5.2
We are running Cpanel + Cludlinux server + 10.3.18-MariaDB

**Comment by khouloudbelguith** [comment] 2019-10-03 11:38
@malcek, could you please navigate to your BO => Advanced Parameters => Information & provide us a screenshot about your configuration.
Also, you need to enable debug mode in your store and debug request which is sent for change of combinations on your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. change a combination
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by malcek** [comment] 2019-10-03 12:20
![image](https://user-images.githubusercontent.com/54998637/66125305-e3499580-e5e6-11e9-8444-90e398dace39.png)

as for the system information i can't get it, because I get after few minutes timeout with no results.

**Comment by khouloudbelguith** [comment] 2019-10-03 12:28
@malcek, you have an override of the ProductController.php
![image](https://user-images.githubusercontent.com/16067358/66126490-d4181700-e5e9-11e9-8254-371875535946.png)
You should edit it because it is not compatible with your PrestaShop version.
You need to contact the module author if it is added by a custom module.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-04 07:51
Hi @malcek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-04 07:51 UTC
Labels: Bug, FO, Combinations, No change required, 1.7.5.2

**Comment by malcek** [comment] 2019-11-04 08:02
Thank you for your help on that. After I contact developer od pretty url module he prepare fix for this error in two hour.
