### ISSUE TITLE
Doctrine Error in fresh install - Languague pt-PT

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#23161] opened 2021-02-05 20:02 UTC
Hello
#### Describe the bug
No demos installed - Fresh install in cPanel live server
Done modules updates
Debug mode on: Got this result

#### Steps to reproduce

1. install PrestaShop
2. Choose the Portugues as default language 
3. Choose Portugal as your country
4. After install, try to open BO
5. See error

**Screenshots**

Doctrine error
Class | Mapping errors
-- | --
PrestaShopBundle\Entity\AdminFilter | No errors.
PrestaShopBundle\Entity\Tab | The  association PrestaShopBundle\Entity\Tab#tabLangs refers to the owning  side field PrestaShopBundle\Entity\TabLang#tab which does not exist.

![1](https://user-images.githubusercontent.com/54105234/107083087-0a246700-67ed-11eb-9e0d-49e81ace3ea3.JPG)

![2](https://user-images.githubusercontent.com/54105234/107083088-0abcfd80-67ed-11eb-8fdf-49ea35d2393e.jpg)

#### Additional infos

- PS version: 1.7.7.1
- PHP version: 7.2.34

Configuration:
info_outline Informação do servidor
Informação do servidor Linux #1 SMP Mon May 18 02:16:06 EDT 2020 x86_64
Versão do software do servidor: Apache

Memory limit: 1G
Max execute time: 300
Max file size: 8M
Versão do MySQL: 5.7.33

**Comment by hibatallahAouadni** [comment] 2021-02-08 10:21
Hello @Borgas 

Could you please specify your PS version? when you installed your shop, which language and country you choose (I know you would say "I already mentioned is pt-PT" :sweat_smile: but coud you please specify it :pray: )

Thanks!

**Comment by Borgas** [comment] 2021-02-10 12:37
> 
> 
> Hello @Borgas
> 
> Could you please specify your PS version? when you installed your shop, which language and country you choose (I know you would say "I already mentioned is pt-PT" sweat_smile but coud you please specify it pray )
> 
> Thanks!

Hello i´m sorry

PS version: 1.7.7.1
Language Portugues (Portugal)

**Comment by hibatallahAouadni** [comment] 2021-02-10 14:32
Hello @Borgas 

Thanks for your feedback!
I just edit your issue, could you please check it and see if the **steps to reproduce** are correct. If no, please edit your issue.

Thanks!

**Comment by Borgas** [comment] 2021-02-10 14:39
> 
> 
> Hello @Borgas
> 
> Thanks for your feedback!
> I just edit your issue, could you please check it and see if the **steps to reproduce** are correct. If no, please edit your issue.
> 
> Thanks!

Hello

Yes, steps are correct.
Upload zip file for server
Language install in Portuguese Portugal (no demos installed)
Updated all modules in BO
Debug mode on - error in doctrine

**Comment by hibatallahAouadni** [comment] 2021-02-11 15:21
Hello @Borgas 

I didn't manage to reproduce your issue with PS1.7.7.1 install in Portuguese Portugal, see the attached screen record below:

https://drive.google.com/file/d/1ZM212uhTyohJH8zRItCwpPwxZ5BrciNo/view

Please check and feedback.
Thanks!

**Comment by Borgas** [comment] 2021-03-03 15:03
> 
> 
> Hello @Borgas
> 
> I didn't manage to reproduce your issue with PS1.7.7.1 install in Portuguese Portugal, see the attached screen record below:
> 
> https://drive.google.com/file/d/1ZM212uhTyohJH8zRItCwpPwxZ5BrciNo/view
> 
> Please check and feedback.
> Thanks!

I´m sorry for late reply

Error shows AFTER update CORE modules

**Comment by hibatallahAouadni** [comment] 2021-03-03 16:25
Hello @Borgas 

Even when I update all my native modules, I don't reproduce the issue, see the attached screen record below:

https://drive.google.com/file/d/1LkwmlJXHsdhbfOEfvIpNFuJAchGVHVxy/view

Please check and feedback.
Thanks!

**Comment by Borgas** [comment] 2021-03-03 16:33
@hibatallahAouadni 

Fresh Install in 1.7.7.2 - only one module to update (Link Widget)

See error:

![1](https://user-images.githubusercontent.com/54105234/109838666-473e1680-7c3e-11eb-855d-1b4dc8a0add8.JPG)
![2](https://user-images.githubusercontent.com/54105234/109838669-47d6ad00-7c3e-11eb-8c53-26127739f307.JPG)

**Comment by hibatallahAouadni** [comment] 2021-03-04 18:26
Hello @Borgas 

Could you please check this [comment](https://github.com/PrestaShop/PrestaShop/issues/23258#issuecomment-790416810) it may help you to resolve your issue.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-24 11:30
Hello @Borgas ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-24 11:30 UTC
Labels: Bug, BO, IN, Languages, No change required, 1.7.7.1
