### ISSUE TITLE
Bug with open "catalog - product page" 

### ISSUE THREAD

**Issue by wojcin1** [PrestaShop/PrestaShop#10920] opened 2018-10-08 16:36 UTC
Bug with open "catalog - product page" 

https://www.evernote.com/shard/s378/sh/fe2c479b-249c-4a2f-9565-1a7f861a46ba/119b69946951ce2db66b902d71bb21a4

Regarding continuation to ISSUE:  BOOM-6192 after again reinstall, even upgrade to 1.7.4.3 no helped.

**Comment by khouloudbelguith** [comment] 2018-10-08 16:54
@wojcin1,

Could you please add steps to reproduce the issue in a new comment.
What is the exact version of the module 1-click upgrade did you use?
Thanks!

**Comment by wojcin1** [comment] 2018-10-08 17:56
It is happening in my back office while i am trying to get into my Catalog Product Page.

**Comment by wojcin1** [comment] 2018-10-23 11:14
???

**Comment by khouloudbelguith** [comment] 2018-10-23 12:06
Hi @wojcin1,

Did you use the The Gift Card	Module ?
Thanks!

**Comment by moabsantos** [comment] 2018-11-05 08:07
Hi @khouloudbelguith ,

i have a same problem (Prestashop 1.7.4.3). When i click Catalog/Products, Catalog/Stock or Modules. The page not show. And the browser show error.

**Comment by khouloudbelguith** [comment] 2018-11-05 08:47
Hi @moabsantos,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by moabsantos** [comment] 2018-11-05 14:48
Hi @khouloudbelguith ,

My instalation , in final step, on addon modules, launcher error. And the error is in classes/db/Db.php line 746.

I think instalation state db in progress.

**Comment by khouloudbelguith** [comment] 2018-11-05 14:51
@moabsantos did make a new fresh installation 1.7.4.3 & it failed?

**Comment by moabsantos** [comment] 2018-11-05 14:55
@khouloudbelguith, I tried several times to finally. Always with error in addons Module

**Comment by khouloudbelguith** [comment] 2018-11-05 14:58
@moabsantos, we need to retrieve the exact error displayed?
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-11 16:15
Hi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-11 16:15 UTC
Labels: Bug, Autoupgrade, No change required, 1.7.4.3
