### ISSUE TITLE
CLOSED - [1.7.7] Error when changing currency decimals

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19954] opened 2020-06-26 11:17 UTC
#### Steps to Reproduce

1. Install 1.7.7 beta in czech language.
2. Go to currencies.
3. Open CZK.
4. Change decimal places from 2 to 0.
5. See error screen.

**Log**

```
[02-Sep-2020 11:12:49 Europe/Prague] PHP Warning:  require(/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getSecurity_Firewall_Map_Context_MainService.php): failed to open stream: No such file or directory in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:49 Europe/Prague] PHP Fatal error:  require(): Failed opening required '/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getSecurity_Firewall_Map_Context_MainService.php' (include_path='/srv/www/trendo.cz/public/beta/vendor/pear/pear_exception:/srv/www/trendo.cz/public/beta/vendor/pear/console_getopt:/srv/www/trendo.cz/public/beta/vendor/pear/pear-core-minimal/src:/srv/www/trendo.cz/public/beta/vendor/pear/archive_tar:.:/usr/share/php') in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:50 Europe/Prague] PHP Warning:  require(/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getPrestashop_Core_Foundation_VersionService.php): failed to open stream: No such file or directory in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:50 Europe/Prague] PHP Fatal error:  require(): Failed opening required '/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getPrestashop_Core_Foundation_VersionService.php' (include_path='/srv/www/trendo.cz/public/beta/vendor/pear/pear_exception:/srv/www/trendo.cz/public/beta/vendor/pear/console_getopt:/srv/www/trendo.cz/public/beta/vendor/pear/pear-core-minimal/src:/srv/www/trendo.cz/public/beta/vendor/pear/archive_tar:.:/usr/share/php') in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:50 Europe/Prague] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/srv/www/trendo.cz/public/beta/var/cache/prod/": rmdir(/srv/www/trendo.cz/public/beta/var/cache/prod/): Directory not empty. in /srv/www/trendo.cz/public/beta/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /srv/www/trendo.cz/public/beta/classes/Tools.php(3448): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /srv/www/trendo.cz/public/beta/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

#### Additional information

* PrestaShop version: 1.7.7 beta
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-06-26 13:30
Hi @Hlavtox ,
Thanks for the report, but I couldn't reproduce it. I changed this part, saved, no error came up :
![Capture d’écran 2020-06-26 à 15 29 36](https://user-images.githubusercontent.com/16019289/85862317-e4000880-b7c1-11ea-9a77-b8301ee556d2.png)
Is there something else to do ?
Thanks!

**Comment by Hlavtox** [comment] 2020-06-26 13:37
@florine2623 I think it could be connected to this: https://github.com/PrestaShop/PrestaShop/issues/11105

**Comment by florine2623** [comment] 2020-07-02 15:24
Indeed the issue you mentioned is reproducible in PS 1.7.7.0, I added 1.7.7.0 label.
After clicking twice on clear cache, I followed the steps in your first message, but I don't have any error coming up regarding the currency.

**Comment by Hlavtox** [comment] 2020-07-02 15:30
@florine2623 It's normal you can't reproduce it. Even for me, it happens only sometimes, maybe in half the times.

**Comment by florine2623** [comment] 2020-07-02 16:08
Hi @PrestaShop/prestashop-core-developers ,
@Hlavtox is having an issue that only happens sometimes. I can't reproduce it.
Maybe you are aware of errors in logs when changing the decimal numbers of a currency ?
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-28 11:45
Hi @Hlavtox,

I did not manage to reproduce the issue with PS1.7.7.0beta1.
I attached a screen record
[PrestaShop instalační asistent.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4988059/PrestaShop.instalacni.asistent.webm.zip)

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-08-17 08:29
Hi @Hlavtox,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-17 08:29 UTC
Labels: Bug, BO, International, Currencies, No change required, 1.7.7.0

**Comment by Hlavtox** [comment] 2020-09-02 09:15
@khouloudbelguith @florine2623 Just happened to me with beta 2, the same test scenario as the first one. Can you reopen this?
