### ISSUE TITLE
Error when accessing the administration with IPV6 enabled.

### ISSUE THREAD

**Issue by coriaweb** [PrestaShop/PrestaShop#12605] opened 2019-02-17 23:50 UTC
**Describe the bug**
We have noticed that when we activate IPv6 for the account in CPanel, prestashop ceases to access the administration area.

It writes the email and password and can not be accessed, shows no error, simply returns to the page to refill the data. Sometimes, insisting a lot we get access, but in the next step we leave again without access.

When we deactivate IPv6 in CPanel, it accesses with total normality.

Translated with www.DeepL.com/Translator

**To Reproduce**
Try logging in to the customer area.

**Video**
http://recordit.co/9C5xMzOXiV

I have the video that only sees what is important to protect privacy, but it looks correctly what I indicate. The whole problem starts when you activate ipv6.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2
CPanel

**Comment by khouloudbelguith** [comment] 2019-02-18 09:43
Hi @coriaweb,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.
Thanks!

**Comment by coriaweb** [comment] 2019-02-18 12:30
Perfect, if you want, we can enable a hosting with IPv6 to do the tests if you need.

Greetings!

**Comment by khouloudbelguith** [comment] 2019-02-18 13:44
@coriaweb, is that possible? 
Thanks a lot if you can provide me with a host with ipv6 enabled.
You can provide me it by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

In the meantime, I'm trying to enable the ipv6 in my server.
Thanks!

**Comment by coriaweb** [comment] 2019-02-18 14:59
Of course it's possible, it's the advantage of being a hosting provider. ;)

In a little while I'll send you the data.

Greetings!

**Comment by khouloudbelguith** [comment] 2019-02-18 15:39
@coriaweb, thanks!
Waiting for your feedback.

**Comment by coriaweb** [comment] 2019-02-18 16:13
I have already sent the data, I hope it will help you do the tests you need. 

Any help I can give you will indicate me.

**Comment by khouloudbelguith** [comment] 2019-02-18 16:39
@coriaweb, thanks a lot, but I didn't receive your email.
My address mail: [khouloud.belguith@prestashop.com](mailto:khouloud.belguith@prestashop.com)
Thanks to check & feedback.

**Comment by coriaweb** [comment] 2019-02-18 16:50
Okay, looking at the follow-up, I realized it's been blocked.

I sent it to you from a personal email.

Greetings!

**Comment by khouloudbelguith** [comment] 2019-02-18 17:04
@coriaweb, no, I don't get any mail yet.
My personal address mail is khouloud.belguiith@gmail.com
My professional address mail: khouloud.belguith@prestashop.com
Thanks!

**Comment by coriaweb** [comment] 2019-02-18 17:15
I've sent it from different sites, I think it's detecting it as spam by carrying strange data.

Check if it reaches the unwanted one.

**Comment by khouloudbelguith** [comment] 2019-02-18 17:22
@coriaweb, thanks!
I just received the email in spam.
I sent you an email.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-21 09:42
Hi @coriaweb,

I created an environment with docker that support IPv6 and have a network with Ipv6 enabled.
So, when I run this command: `ip  addr show`

```
6: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:a3:35:37:0d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:a3ff:fe35:370d/64 scope link
```

I created a docker-composer.yml which have only an address IPv6 & a network that enable IPv6
```
networks:
 app_net:
  driver: bridge
  enable_ipv6: true
  ipam:
   driver: default
   config:
   - subnet: 2002:0a01:2500::/64
     gateway: 2002:0a01:2500::1
```

So, when the container is created, when I run this command: `ip  addr show`

```
62: br-1fa6a9f2f201: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:0e:bf:96:f0 brd ff:ff:ff:ff:ff:ff
    inet 172.22.0.1/16 brd 172.22.255.255 scope global br-1fa6a9f2f201
       valid_lft forever preferred_lft forever
    inet6 fe80::42:eff:febf:96f0/64 scope link 
       valid_lft forever preferred_lft forever
```
In the maintenance page, I could check my Adress IP
![image](https://user-images.githubusercontent.com/16067358/53157847-ac2bf400-35c2-11e9-927e-7f9aa258a5c3.png)

Now, with IPv6 enabled, I tried to connect to BO & it is OK.
I tried with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1L_79opMJgP6jnQv0C3CmL_vJXzWAvy6F/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-25 07:54
Hi @coriaweb,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-25 07:54 UTC
Labels: BO, No change required, 1.7.5.0
