### ISSUE TITLE
Bad way of calculate final product price

### ISSUE THREAD

**Issue by shawe** [PrestaShop/PrestaShop#19750] opened 2020-06-15 11:43 UTC
#### Describe the bug

Error calculating price for a product, at least for Spain. Prestashop is doing this calc:

[(price+ecotax)-discount] + tax

But here must be calculated this way:

[(price-discount)+ecotax] + tax

Maybe is something with wrong configuration, but we can't found another way to do this.

#### Expected behavior

Is explained on description of the bug. Or must be selectable the way of calculate the final product price:
- [(price+ecotax)-discount] + tax
- [(price-discount)+ecotax] + tax

#### Steps to Reproduce

1. Fill in a product a tax and a ecotax
2. Compare if final price is based on:
2.1. [(price+ecotax)-discount] + tax
2.2. or [(price-discount)+ecotax] + tax

price: 100
discount: 20%
tax: 10%
ecotax = 3

PrestaShop is doing:
- [(price+ecotax)-discount] + tax = [(100+3)-20%] + 10% = 90.64
But at least spanish legislation require:
- [(price-discount)+ecotax] + tax = [(100-20%)+3] + 10% = 91.3

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1.33

**Comment by matthieu-rolland** [comment] 2020-06-15 14:17
We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #9855.

To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you!

**Comment by matthieu-rolland** [comment] 2020-06-15 14:17
Duplicate of #9855

**Closed as completed** 2020-06-15 14:17 UTC
Labels: Duplicate
