### ISSUE TITLE
html_entity_decode() expects parameter 1 to be string - 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17909] opened 2020-03-02 10:40 UTC
Hello, 

my error log file is full of this errors:

2020/03/02 11:07:48 [error] 25568#25568: *6286557 FastCGI sent in stderr: "PHP message: PHP Warning:  html_entity_decode() expects parameter 1 to be string, object given in /var/www/clients/client3844/web7777/web/prestafolder/classes/Tools.php on line 1795" while reading response header from upstream, client: 12.345.67.890, server: mydomain.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7777.sock:", host: "mydomain.com", referrer: "https://mydomain.com/"

I am thankful for any ideas of fixing this. 

PS 1.7.6.3
PHP 7.2.1
nginx/1.14.0

**Comment by khouloudbelguith** [comment] 2020-03-02 10:54
Hi @didi-2018,

Could you please add steps to reproduce the issue in a new comment?
You have an error related to this line: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.3/classes/Tools.php#L1795
Replacing by
`$str = html_entity_decode((string)$str, ENT_COMPAT, 'UTF-8');` could be a solution.

Thanks to check & feedback.

**Comment by didi-2018** [comment] 2020-03-02 11:15
@khouloudbelguith seems to be related to translations in BO

changing to: $str = html_entity_decode((string)$str, ENT_COMPAT, 'UTF-8'); breaks the layout of translations site in BO

**Comment by khouloudbelguith** [comment] 2020-03-02 11:20
@didi-2018, sorry, you need just to remove this suggestion.
Could you please add steps to reproduce the issue in a new comment?

Thanks!

**Comment by didi-2018** [comment] 2020-03-02 11:35
@khouloudbelguith I do not really know how to reproduce. I just have to find out. 

There are problems to open images with specialchars in the name like Ö

**Comment by khouloudbelguith** [comment] 2020-03-02 12:06
@didi-2018, I did not manage to reproduce the issue with PS1.7.6.3.
I uploaded an image with the name "ÖÖÖÖ.jpg"
I edited the caption ÖÖ 
![image](https://user-images.githubusercontent.com/16067358/75675003-8d0c7b80-5c86-11ea-92e3-a0015da45295.png)

No similar errors in log file.

What is the exact image uploaded in your case?

Thanks!

**Comment by didi-2018** [comment] 2020-03-02 12:59
@khouloudbelguith  my image is 'Belsira-Vintage-Größentabelle.jpg' 
and trying to get is 'Belsira-Vintage-Gr%C3%B6%C3%9Fentabelle.jpg' 

Problems with ö and ß

**Comment by khouloudbelguith** [comment] 2020-03-02 13:54
@didi-2018, I tried with the same name, but no errors in the dev.log file.
https://drive.google.com/file/d/1Gr_eNKrt2emWK__h41fElu131bQ_O86U/view

Thanks!

**Comment by didi-2018** [comment] 2020-03-02 14:05
@khouloudbelguith  error is in error log file from my host. Presta log files is nothing. Could you please check you host log files? That would be great ☺

**Comment by khouloudbelguith** [comment] 2020-03-02 14:19
@didi-2018, no errors found by the server.
https://drive.google.com/file/d/1ZQzu2KT8RXemek9JBIOFCjwzrfkUfMEm/view

Thanks!

**Comment by didi-2018** [comment] 2020-03-02 14:26
@khouloudbelguith  you are using apache not nginx?

**Comment by khouloudbelguith** [comment] 2020-03-02 14:31
@didi-2018, yes! apache

**Comment by didi-2018** [comment] 2020-03-02 15:44
@khouloudbelguith  this error comes by using some modules. I am using nginx/1.14.0 not apache.

**Comment by khouloudbelguith** [comment] 2020-03-02 15:47
@didi-2018,
>this error comes by using some modules

Modules provided by PrestaShop?

Thanks!

**Comment by didi-2018** [comment] 2020-03-02 15:52
@khouloudbelguith  it is really hard to find out. I try my best. Now I have this error in cart when customer wants to checkout. In 'cart-summary-product-line.tpl' on line 54 related to html specialchars

    <span class="product-quantity">x<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['product']->value['quantity'], ENT_QUOTES, 'UTF-8');?>
</span>

**Comment by didi-2018** [comment] 2020-03-02 15:55
@khouloudbelguith  only when smart cache is enabled.

**Comment by khouloudbelguith** [comment] 2020-03-02 16:57
@didi-2018, did you use a custom theme?

Thanks!

**Comment by didi-2018** [comment] 2020-03-02 17:34
@khouloudbelguith  I use a custom theme. Do you think this theme causes the problems? Then I can try to contact the theme´s developer.

**Comment by khouloudbelguith** [comment] 2020-03-03 09:55
@didi-2018,

As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them and feedback.

**Comment by khouloudbelguith** [comment] 2020-04-01 07:29
Hi @didi-2018,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-01 07:29 UTC
Labels: Bug, No change required, 1.7.6.3
