### ISSUE TITLE
BO > Customization > Themes Stop Working After importing a new theme, the theme page does not look as it should. And modal functions are not working #8.1.4 #Bug

### ISSUE THREAD

**Issue by PrestaConnect** [PrestaShop/PrestaShop#35664] opened 2024-03-17 14:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After importing a new theme, the theme page does not look as it should. And modal functions are not working (Activate theme, Delete theme, etc).

### Steps to reproduce

1. Go to backoffice Customization > Themes
2. Import new theme from computer
3. Enable new theme added from computer
4. Theme Page views changed and theme actions didn't work (Enable theme, delete theme, etc.)

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

PrestaConnect

**Comment by PrestaConnect** [comment] 2024-03-17 14:36
@florine2623 @khouloudbelguith @matks Friends, can you check the error?

**Comment by florine2623** [comment] 2024-03-18 09:04
Hello @PrestaConnect ,

I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/7df76efe-1006-41a9-872e-20a302ce668d

The button to enable/delete theme work as expeted.

I'm closing your issue as it is not a PS bug.
It probably comes from your theme itself.

**Closed as completed by florine2623** 2024-03-18 09:04 UTC
Labels: Bug

**Comment by PrestaConnect** [comment] 2024-03-19 07:23
Hello @florine2623,
The version you tested is 8.1.5, the version I reported the bug in is 8.1.4. I also noticed that in 8.1.4 the ps_editions_basic module is active. I think the problem is caused by the ps_editions_basic module.
