### ISSUE TITLE
Problem/Bug with Ajax + Prestashop 1.7.4.2 + "Enter" key + Cart

### ISSUE THREAD

**Issue by Suisso** [PrestaShop/PrestaShop#11079] opened 2018-10-19 10:15 UTC
Hello,

I have big bug / problem with Ajax + Prestashop 1.7.4.2 + "Enter" key when updating the quantity in the Cart (see video attached)!

PS: I already control the "core.js", disable ajax in the shopping cart module, and even check the module "ps_shoppingcart" and I also tried to block the action with the "Enter" button while doing a custom.js but still same problem!

 
[presta_final_cart.zip](https://github.com/PrestaShop/PrestaShop/files/2495397/presta_final_cart.zip)

Anyone know how to fix this problem ?

 
Thank you in advance,

Best regards

**Comment by khouloudbelguith** [comment] 2018-10-19 10:25
Hi @Suisso,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9405 to solve the issue.
It is fixed in the next release 1.7.5.0.
Your ticket is a duplicate of #9841
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-19 10:25
Duplicate of #9841

**Closed as completed by khouloudbelguith** 2018-10-19 10:25 UTC
Labels: Duplicate
