### ISSUE TITLE
Blank page after update

### ISSUE THREAD

**Issue by montecitofrance** [PrestaShop/PrestaShop#23910] opened 2021-04-06 18:30 UTC
Hello,

Following the update of prestashop on my site I have a big problem, my site is all white and I no longer have any functionality on the left side of my BO.

Can you help me please?

Thanks in advance,

**Comment by florine2623** [comment] 2021-04-07 08:19
Hello @montecitofrance ,
It seems like your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/23166

Please check this comment regarding your issue : https://github.com/PrestaShop/PrestaShop/issues/23166#issuecomment-783184675

I'll close your issue. Feel free to open a new one and follow the bug report template :
![Capture d’écran 2021-04-07 à 10 18 58](https://user-images.githubusercontent.com/16019289/113834064-ad144580-978a-11eb-8b82-2d1b5b449a7f.png)

Thanks!

**Closed as completed by florine2623** 2021-04-07 08:19 UTC
Labels: Duplicate
