### ISSUE TITLE
BO- Fix size Orders> Order on mobile mode

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#32726] opened 2023-05-26 14:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Order page is bad displayed on mobile mode

[Untitled_ May 26, 2023 4_31 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/67386404-f59b-4a79-91e3-ca51f1416146)

### Steps to reproduce

1. Go to BO> Orders> Order
2. Change dimensions to I Phone 12 Pro
3. See error :warning: : The page is bad displayed

### PrestaShop version(s) where the bug happened

8.1.0 RC

### PHP version(s) where the bug happened

7.4 & 8.1

**Comment by Hlavtox** [comment] 2023-05-29 05:25
@MhiriFaten Responsivity is not working in backoffice for several years, it's nothing new. :-)

I have made an issue about it with some design specs - https://github.com/PrestaShop/PrestaShop/issues/25313

**Comment by hibatallahAouadni** [comment] 2023-05-29 17:48
Duplicate of #25313

**Closed as completed by hibatallahAouadni** 2023-05-29 17:48 UTC
Labels: Bug, Duplicate
