### ISSUE TITLE
Cart rule gift free and accountant

### ISSUE THREAD

**Issue by higanjima** [PrestaShop/PrestaShop#13812] opened 2019-05-16 10:00 UTC
If you had a cart rule with gift product and order something, discount fields in database are not fill (total_discounts / incl / excl) same for order_invoice table. 

all accountant export are wrong can we find a solution for this ? 

**Additionnal information**
PrestaShop version: 1.7.X
PHP version: 7.X

**Comment by khouloudbelguith** [comment] 2019-05-16 10:22
Hi @higanjima,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0.
In table `ps_order_invoice`, the total_discounts(tax inclu / exclu) are null.
total_discounts
![image](https://user-images.githubusercontent.com/16067358/57846671-a6623b00-77cc-11e9-9a19-de514ed300ef.png)

![image](https://user-images.githubusercontent.com/16067358/57846737-c5f96380-77cc-11e9-85bc-aae70c4b0ccb.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Related to #13689
Thanks!

**Comment by higanjima** [comment] 2019-05-20 13:29
I can't send you a pull request but for fix it, in src/Core/Cart/CartRuleCalculator.php you have to switch ligne 95 / 96

// Free gift
$cartRow->applyFlatDiscount($cartRow->getFinalUnitPrice());  
$cartRuleData->addDiscountApplied($cartRow->getFinalUnitPrice());

TO 

// Free gift
$cartRuleData->addDiscountApplied($cartRow->getFinalUnitPrice());
$cartRow->applyFlatDiscount($cartRow->getFinalUnitPrice());

**Comment by khouloudbelguith** [comment] 2019-05-22 13:20
Hi,

The issue is fixed in the develop branch
![image](https://user-images.githubusercontent.com/16067358/58177658-b2526f00-7c9c-11e9-928f-7b240fddd27e.png)

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-22 13:20 UTC
Labels: Bug, Minor, BO, Order, Invoices, Discounts, Cart rules, Taxes and Prices, Fixed, 1.7.5.2, 1.7.6.0
