### ISSUE TITLE
PSGDPR 1.4.3 Tiny Editor (TinyMCE) is missing - Prestashop 8.0.5

### ISSUE THREAD

**Issue by Jonteep** [PrestaShop/PrestaShop#33614] opened 2023-08-13 12:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

On one of my websites, the TinyMCE Editor is missing from the PSGDPR 1.4.3 module.

It has been missing ever since the AutoUpgrade module updated the PSGDPR to 2.0.0 (when that version was available during updating from Prestashop 8.0.2 to 8.0.3, I think, or something like that).

If I use PSGDPR 2.0.0 or 2.0.1 (Pre-Release versions), the Editor is back, but I can't update Prestashop with those versions.

I now have PSGDPR 1.4.3, which is the latest stable version.

I am running Prestashop 8.0.5.

What could have happened in the database when it updated to 2.0.0? How may I resolve the issue so that PSGDPR 1.4.3 will show the Editor once again?

Thanks in advance.

Best regards,

### Expected behavior

To have the TinyMCE Editor working for the PSGDPR 1.4.3 module, when editing the information.

### Steps to reproduce

1. Install Prestashop 8.0.2
2. Update the PSGDPR to 2.0.0
3. Downgrade to 1.4.3 (so PS can update to Prestashop 8.0.5) and disable the module
4. Update PS to 8.0.5
5. Activate PSGDPR 1.4.3
6. Try to edit the text fields in PSGDPR 1.4.3, no editor will appear.

### PrestaShop version(s) where the bug happened

8.0.5 (and other previous versions)

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

Official GDPR Module 1.4.3

**Comment by sallemiines** [comment] 2023-08-16 13:59
Hello @Jonteep ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by hibatallahAouadni** [comment] 2023-08-17 14:40
Hello @Jonteep 

Could you please check this issue #33641 it seems similar to yours.
Waiting for your feedback.

Thanks!

**Comment by Jonteep** [comment] 2023-08-27 23:14
Hi @hibatallahAouadni , thanks.

It could be related, yes. I think some changes where made to the database when 2.0.0 was installed automatically back with the autoupgrade, when that version of PSGDPR was available. Now when I have downgraded to 1.4.3 it doesn't match with the database and the Tiny Editor won't show?

If I upgrade to 2.0.1 of PSGDPR, the editor shows again, but I can't update Prestashop if any new versions are released, without first downgrading and disable PSGDPR during the autoupgrade.

Thanks in advance.

Best regards,

**Comment by AureRita** [comment] 2023-10-27 12:55
Hi @Jonteep 

Thank you for your report, did you reproduce the issue with psgdpr 2.0.3 ? 

Waiting for your feedback

**Comment by paulnoelcholot** [comment] 2023-11-15 09:06
Hello @Jonteep,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2023-11-15 09:06 UTC
Labels: Bug, BO, GDPR, Invalid, Module, 8.1.x

**Comment by Jonteep** [comment] 2023-11-26 14:01
Hi @AureRita , I have searched for PS GDPR 2.0.3 but cannot seem to find a download for that release? Is it the 2.0.1 that is now 2.0.3, or am I missing something? Thanks in advance, Best regards
