### ISSUE TITLE
coupon code bug for newsletter /  create an account

### ISSUE THREAD

**Issue by xiaoyuan1998** [PrestaShop/PrestaShop#16057] opened 2019-10-21 18:37 UTC
**Describe the bug**
when a client subscribe newsletter in homepage newsletter block, he can get coupon code, 
![image](https://user-images.githubusercontent.com/7703076/67232490-c5cb5700-f441-11e9-9d44-420d4d01671d.png)
but if one clinet creat his account and choose susbcription newsletter at the same time, he can not get the coupon code (PS any send welcome mail but not the coupon code mail)
![image](https://user-images.githubusercontent.com/7703076/67232750-4427f900-f442-11e9-8a01-4290800d6582.png)

![image](https://user-images.githubusercontent.com/7703076/67232878-7f2a2c80-f442-11e9-882a-78dc51b9d2bb.png)

**Additional information**
PrestaShop version: 1,7.4

**Comment by khouloudbelguith** [comment] 2019-10-22 08:36
Hi @xiaoyuan1998,

I did not manage to reproduce the issue with PS1.7.6.1 & the ps_emailsubscription module v2.5.1.
![image](https://user-images.githubusercontent.com/16067358/67269847-bf77c200-f4b7-11e9-9fcd-81eec848daba.png)
What is the exact version of the ps_emailsubscription module did you use?

Thanks!

**Comment by xiaoyuan1998** [comment] 2019-10-22 14:09
Hi, @khouloudbelguith 
I chek the file in //web/modules/ps_emailsubscription
![image](https://user-images.githubusercontent.com/7703076/67294303-f238af00-f4e5-11e9-8973-55c56db58026.png)

the version is 2.3.1
![image](https://user-images.githubusercontent.com/7703076/67294353-01b7f800-f4e6-11e9-9aa8-9927a5d6ee4a.png)


i chek in the path: 

![image](https://user-images.githubusercontent.com/7703076/67294203-d1705980-f4e5-11e9-9a99-b93ca90b2394.png)

i dont have config.xml

a  small question, when we have the some "module" one in the theme file and one in the web file, which one will be used?

Best regards.

**Comment by khouloudbelguith** [comment] 2019-10-22 14:20
@xiaoyuan1998, The config.xml file is automatically generated by PrestaShop when the module is installed
https://devdocs.prestashop.com/1.7/modules/creation/module-file-structure/#cache-file-config-xml
You need to upgrade your module, the latest version is v2.5.1, as reported here: https://github.com/PrestaShop/PrestaShop/issues/9810

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-21 07:35
Hi @xiaoyuan1998,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-21 07:35 UTC
Labels: Bug, Emailsubscription, No change required
