### ISSUE TITLE
Can't delete texture image for an attribute with multistores

### ISSUE THREAD

**Issue by codeway** [PrestaShop/PrestaShop#30244] opened 2022-11-08 14:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Have an admin with many stores.
Go to an attribute group and an attribut.
Add a texture / save.
After that go to that attribute
Click below the texture to the delete image button
=> The message "The image was deleted" appear but the image is still here.

After research i found that this is "normal" for prestashop : 
Class ObjectModel / function deleteImage() : 

the test : $this->hasMultishopEntries() is true so the image could not be deleted.

I don't understand why ? because if we want to delete the texture after a bad upload in ex. we should be able to delete this image.

/**
 * Delete images associated with the object.
 *
 * @param bool $force_delete
 *
 * @return bool
 */
public function deleteImage($force_delete = false)
{
    if (!$this->id) {
        return false;
    }

    if ($force_delete || **!$this->hasMultishopEntries()**) {
        /* Deleting object images and thumbnails (cache) */

        [… image is deleted only if the attribute has no multishop entries}
  }
  

  Could you force delete to the attributes images ? 

### Expected behavior

Have an admin with many stores.
Go to an attribute group and an attribut.
Add a texture / save.
After that go to that attribute
Click below the texture to the delete image button
The image will be deleted

### Steps to reproduce

Have an admin with many stores.
Go to an attribute group and an attribut.
Add a texture / save.
After that go to that attribute
Click below the texture to the delete image button
=> The message "The image was deleted" appear but the image is still here.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7

**Comment by sallemiines** [comment] 2022-11-08 16:18
Hello @codeway !

Thanks for the issue! 
Following your steps, I can't manage to reproduce the issue (they are not clear enough) 
Could you please provide us with clear and concise steps to reproduce!

Please check and feedback ! 
Thank you !

**Comment by sallemiines** [comment] 2022-11-28 08:53
Hello @codeway ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by sallemiines** 2022-11-28 08:53 UTC
Labels: Bug, BO, Can't reproduce, Attributes, Multistore, Invalid, 1.7.8.7
