### ISSUE TITLE
Automatic indexing of products  not working 1.7.6.1

### ISSUE THREAD

**Issue by BudrysLP** [PrestaShop/PrestaShop#17778] opened 2020-02-21 16:18 UTC
I noticed that after saving or adding a productpage the automatic index for the search does not work. Its necessary to click on : Add missing products to the index

**Comment by khouloudbelguith** [comment] 2020-02-21 16:25
Hi @BudrysLP,

I did not manage to reproduce the issue with PS1.7.6.1 and PS1.7.6.3.
https://drive.google.com/file/d/1I3Nmcmf5XtLivftsKs1MgmGx3kj5bisE/view
But, it could be your issue similar to those problems:
1. https://github.com/PrestaShop/PrestaShop/issues/15640 not fixed yet.
2. https://github.com/PrestaShop/PrestaShop/issues/10530 fixed in the PS1.7.6.0.
3. https://github.com/PrestaShop/PrestaShop/issues/9663 fixed in the next version PS1.7.7.0.

Thanks to check & feedback.

**Comment by BudrysLP** [comment] 2020-02-25 17:42
So what to do now?

**Comment by florine2623** [comment] 2020-02-26 14:28
Hello @BudrysLP ,

Is the product not indexed when you deactivate the product or when it is created ?
Could you please attach a screen record of your case ?

And could you check these 3 issues to see if they are related your your issue :
1. #15640 not fixed yet.
2. #10530 fixed in the PS1.7.6.0.
3. #9663 fixed in the next version PS1.7.7.0.

Thanks to check & feedback.

**Comment by BudrysLP** [comment] 2020-02-26 15:45
I have that issue when I save product

**Comment by florine2623** [comment] 2020-02-26 15:54
Hello @BudrysLP ,

Could you please attach a screen record of your case ?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-27 16:33
Hi @BudrysLP,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-27 16:33 UTC
Labels: Bug, BO, Search, No change required, 1.7.6.1
