### ISSUE TITLE
[PS Installation] PrestaShop accounts (ps_accounts) module is not installed

### ISSUE THREAD

**Issue by addison74** [PrestaShop/PrestaShop#36541] opened 2024-07-12 19:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cannot install Prestashop v8.1.7 after downloading it from prestashop.com . An error occurres during installation.  This is the error message

1: PrestaShop accounts (ps_accounts) module is not installed, please install it.

![Screenshot 2024-07-12 223213](https://github.com/user-attachments/assets/46c5ec8f-d89a-43f8-ada6-a571874ce126)

### Expected behavior

I should be able to install all modules, including ps_accounts.

### Steps to reproduce

1. Download the official version from here https://prestashop.com/prestashop-offers/classic/#download.

2. Extract the files in test environment.

3. Open the website in the browser. Installation starts. Fill in all required information.

4. Installation fails at 67% when installing modules. It says "Prestashop accounts module is not install, please install it."

Pretty funny isn't it? How can I install it when I don't have any option?

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

ps_accounts

**Comment by matks** [comment] 2024-07-14 15:59
From the discussion here https://github.com/PrestaShop/PrestaShop/issues/26838 we can make the bug report more accurate
- ps_accounts is involved but real problem seems to come from PS Shipping module
- also but does not happen 100% of the time it's rando

About the "it's random" I have a theory:

During the installation process, the system simply installs every module that is present in the `modules` folder. In the folder, there are both PS Shipping module and PS Accounts. The installer fetches the list of all modules in `modules/` and installs them 1 by 1.

On some systems, the order of the list will put PS Accounts before PS Shipping and then there will be no bug, because PS Account was installed before PS Shipping.

On some other systems, the order of the list will put PS Shipping before PS Account and then there will is a bug, because PS Shipping needs PS Account to be installed.

The order of the list depends on the implementation of the system. My guess is that depending on OS you get different orders. But nevertheless **the success of the installation should not depend on whether or not user is lucky**. This is a bug to fix.

Also I think this issue only happens for new shop because PS Shipping actually implements a way to install PS Account before, but this one depends on PS MBO. Basically during its install process, PS Shipping asks PS MBO to install PS Account (PS MBO acts as package manager). I guess (to be confirmed) that is PS MBO is installed before PS Shipping, then it works (once again depends in luck). But if installer triggers PS Shipping install process before PS MBO and PS Accounts have been installed, we get the above error.

All of the above is a theory based on me reading the codebase. Next is verifying the software actually does what I described here.

**Comment by addison74** [comment] 2024-07-14 16:07
Thank you @matks for your post. In my case I am using (Docker + WSL + Ubuntu 20 + DDEV). The test environment is detailed here https://github.com/PrestaShop/PrestaShop/discussions/36536. 

In my case the reported issue is only happening with the downloaded version from prestashop.com. I did not get this error using the versions 8 and 9 from Git.

**Comment by matks** [comment] 2024-07-14 18:58
> In my case the reported issue is only happening with the downloaded version from prestashop.com. I did not get this error using the versions 8 and 9 from Git.

This is because the version from prestashop.com contains additional features, carried by these modules (PS Shipping, PS MBO...)

**Comment by matks** [comment] 2024-07-15 13:42
I got word from the PS Shipping team, a release is on its way to fix this 😉

**Comment by Nakahiru** [comment] 2024-07-15 15:16
The release was made 💪🏻 Just to let you know, dependencies are now handled after the installation, on the module page configuration and not during the installation process. I think there is some cache on the marketplace, so it will only be available from tomorrow if I am not mistaken.

We implement this library https://github.com/PrestaShopCorp/module-lib-mbo-installer

**Comment by matks** [comment] 2024-07-15 15:19
Thanks to @Nakahiru there will be no problem with PS Shipping latest release v1.0.9

The Zip available by download on prestashop.com will however not immediately be updated with PS Shipping v1.0.9 because more tests are needed. A little delay will be needed before the Zip on prestashop.com contains PS Shipping v1.0.9.

**Comment by DjPaul78** [comment] 2024-07-19 23:00
I had the exact same problem. After deleting the folders /ps_edition_basic and also /ps_mbo, the install went well. So there is something weird going on in one of these modules.

**Comment by mkvaghani** [comment] 2024-07-20 09:15
Make sure, your database has no tables before installing prestashop.
Use empty database works.

**Comment by DjPaul78** [comment] 2024-07-20 09:37
> Make sure, your database has no tables before installing prestashop. Use empty database works.

As far as I know, during a new install, the tables are deleted. So it doesn't matter if your database contains existing tables. 
The problem occurs  during the install of the shop. After about 65% you see 'Installing theme' and after that you see 'Installing modules'. After about 20 or 30 seconds the error shows that the ps_accounts must be installed.

**Comment by MarinusKlopper** [comment] 2024-07-29 17:00
I got around the issue by:

When installing, before connection to the database or after the automatic unzipping of the prestashop.zip file. I moved the psshopping module to the home directory. Then connected to the database. After all modules were installed I moved back the psshipping folder to the home/modules/ folder.

Installed the module from the backend.

**Comment by mkvaghani** [comment] 2024-07-30 03:14
> As far as I know, during a new install, the tables are deleted. So it doesn't matter if your database contains existing tables. The problem occurs during the install of the shop. After about 65% you see 'Installing theme' and after that you see 'Installing modules'. After about 20 or 30 seconds the error shows that the ps_accounts must be installed.

Right, but prestashop delete and create new tables as required and script runs parallel, this happen when script run before table created.  Those who are getting this error, try with empty database.

**Comment by spainbox** [comment] 2024-08-05 16:58
Disable Prestashop shipping to install PS 8.1.7 without problems, and later if you need install it from backend

**Comment by mkvaghani** [comment] 2024-08-07 14:50
You can delete those modules, that can be install later.
I have attached image of comparision.
![presta-modules](https://github.com/user-attachments/assets/eabf04e7-3f75-4e17-b8b7-2d823e5eeff6)

**Comment by Nakahiru** [comment] 2024-08-20 14:18
Do you still encounter the issue? It should be solved. I just make an another test and it's working properly.

![CleanShot 2024-08-20 at 16 17 10@2x](https://github.com/user-attachments/assets/b44f1608-3c17-47ae-9d48-f23ec3748e0e)

Otherwise, I think we can close the issue @matks 🤔

**Comment by mkvaghani** [comment] 2024-08-21 04:07
You can close @matks @Nakahiru

**Comment by matks** [comment] 2024-08-21 08:33
Thank you

**Closed as completed by matks** 2024-08-21 08:33 UTC
Labels: Bug
