### ISSUE TITLE
Wrong birthday date -> Error in front and back office

### ISSUE THREAD

**Issue by ptidav** [PrestaShop/PrestaShop#25971] opened 2021-09-22 19:37 UTC
#### Describe the bug
If a customer enter a birthday date with no valid year, ie 13/03/0000, he gets an error 500 in front office during checkout.
If you try to access his customer sheet from BO you get an error :
Invalid date 
[PrestaShopException 0]

#### Expected behavior

A check could be made when the customer enter his birthday date to avoid the record of date with wrong format.

#### Steps to Reproduce

Create a new customer from front office and enter a bad date : 12/04/0000.
Try to access customer sheet from BO or try a checkout from front office and you get an error 500

**Screenshots**
![Capture d’écran 2021-09-22 à 21 28 45](https://user-images.githubusercontent.com/49609556/134410104-fb7f9fe9-0a12-4b9c-96fa-4c1f77b6b657.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3

Thanks for your help
David

**Comment by hibatallahAouadni** [comment] 2021-09-23 10:06
Hello @ptidav 

I reproduce the issue with PS1767 & PS1778, see the attached screenshot below:
In BO:

![image](https://user-images.githubusercontent.com/23308427/134489174-e79f46b6-d536-450b-87ad-cb3b1e0a8acc.png)

In FO:

![image](https://user-images.githubusercontent.com/23308427/134489310-aa0ef30e-3a40-4ec7-acdb-3ecb7b31e42b.png)

Thank you

**Comment by hibatallahAouadni** [comment] 2021-09-23 10:18
Hello again!

This issue has been fixed with PS1780_rc1 :tada: 
And we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17341. 
Please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-23 10:18
Duplicate of #17341

**Closed as completed by hibatallahAouadni** 2021-09-23 10:18 UTC
Labels: Bug, BO, FO, Duplicate, Customer, 1.7.6.7
