### ISSUE TITLE
Unknown tag displayPrice in invoice.tax-tab.tpl template

### ISSUE THREAD

**Issue by TechhDan** [PrestaShop/PrestaShop#24514] opened 2021-05-16 05:21 UTC
#### Describe the bug

When calling the setCurrentState method on an Order object an exception is thrown. The exception is ```unknown tag 'displayPrice'``` relating to the ```pdf/invoice.tax-tab.tpl``` template file.

#### Expected behavior

This method should not throw an Exception for unknown tag on invoice template error.

#### Steps to Reproduce

1. $order = Order::getByCartId($cart->id)
2. $order->->setCurrentState((int) Configuration::get('PS_OS_PREPARATION'));

**Screenshots**

![dump](https://user-images.githubusercontent.com/11691784/118386237-0ff7c880-b5e4-11eb-8061-31565c91cd6b.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.28 (PrestaShop docker image)

**Comment by matks** [comment] 2021-05-16 12:15
> This method should not throw an Exception for unknown tag on invoice template error.

It depends.

If `setOrderState()` triggers a mail sending, and the mail has a PDF attachment, and the Smarty template used to compute the PDF is wrong, then it makes sense 😄 .

Then the question becomes "is it critical to be able to send this mail (then crashing is correct) or can it be ignored (and written in logs) because the failed sending of a mail should not prevent the order state modification"

**Comment by TechhDan** [comment] 2021-05-16 20:24
Smarty isn't registering the displayPrice tag as a function on the ```pdf/invoice.tax-tab.tpl``` template. 

```
// pdf/invoice.tax-tab.tpl
{if $display_tax_bases_in_breakdowns}
  <td class="right white">
    {if isset($is_order_slip) && $is_order_slip}- {/if}
    {displayPrice currency=$order->id_currency price=$line.total_tax_excl} <-- displayPrice tag unknown
  </td>
{/if}
```

**Comment by TechhDan** [comment] 2021-05-16 20:26
Or actually I don't know if displayPrice is an internal tag which is just not loading on this render? I'm a little lost but I think I'm just going to wrap my payment module's setOrderState method in a try block since I can't figure out how to pass whatever is missing in my payment module.

**Comment by hibatallahAouadni** [comment] 2021-05-17 09:44
Hello @TechhDan 

> 1. $order = Order::getByCartId($cart->id)
> 2. $order->->setCurrentState((int) Configuration::get('PS_OS_PREPARATION'));

Could you please specify if there's thrown exception without modifying the code. If so, could you please provide steps to reproduce.

Thanks!

**Comment by TechhDan** [comment] 2021-05-18 06:11
Hey @hibatallahAouadni ,

Yeah that's pretty much the code after validating order with payment module. Sure, I created a module that can reproduce the issue. Just check out with it and I've dumped the exception.

https://github.com/TechhDan/samplepay-prestashop-demo/tree/main

**Comment by hibatallahAouadni** [comment] 2021-05-25 10:42
Hello @TechhDan 

I think you misunderstood me, I'm asking: 

- where are these two lignes located (in which file) or should I add these two lignes in some file to reproduce the issue?
- after cloning your module under modules/ what I should do? ( there's no guide)
- please provide steps to reproduce or at least a screen record (recording all steps)

Please check and feedback.

Thanks!

**Comment by TechhDan** [comment] 2021-05-29 15:41
Hello @hibatallahAouadni ,

I apologize for not being very clear about this. 

- These two lines of code are not located anywhere in a default PrestaShop installation i believe. This is more for developers who are trying to make a payment module for PrestaShop. 
- The demo module is meant to be installed and used as a payment demo module. Just download it as a module and upload it to any default PrestaShop installation.
- Install the module on the latest PrestaShop release. Head over to checkout and use the demo payment module option. 

After order validation by PrestaShop I'm unable to change the state of that order without an exception warning. It's not a big deal as I can ignore the message but i wanted to bring it up in case. I hope it's not an error on my side. I was trying to debug the error it seemed it was coming from PrestaShop core. I'll send a screen recording later today.

**Comment by hibatallahAouadni** [comment] 2021-06-04 01:46
Hello @TechhDan 

> Just download it as a module and upload it to any default PrestaShop installation.

I encounter an issue while download the module, it seems not valid:

https://drive.google.com/file/d/166LpTAsN6QtEdl-vixVdHFRM5mwpWznb/view

Please check and feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-06-25 08:26
Hi @TechhDan,

I tried with PS17774 and PS1775, I have an issue on the FO > Order confirmation page
![image](https://user-images.githubusercontent.com/16067358/123394322-4f301680-d59f-11eb-8fb0-02e33c94ce47.png)

When I change the order status => OK, no error displayed

I attached a screen record
https://drive.google.com/file/d/1v5bW5-Id-hZL9bW9XlyQg8XI-DTfHR8C/view?usp=sharing

Your issue is not a PrestaShop core.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I will close the issue.

Thank you!

**Closed as completed by khouloudbelguith** 2021-06-25 08:26 UTC
Labels: Bug, CO, Invoices, Taxes and Prices, No change required, 1.7.7.4

**Comment by PrestaEdit** [comment] 2022-02-21 10:02
Today,

I'm having this issue again but it's related to a third party module (at the beginning of the error).
I will have a look about this in intern, and see what's happen there
<img width="862" alt="Capture d’écran 2022-02-21 à 11 01 07" src="https://user-images.githubusercontent.com/2631425/154932439-cdf5b8fa-ee0c-433f-a074-62696a874fc2.png">
.

**Comment by khouloudbelguith** [comment] 2022-02-21 11:19
Hi @PrestaEdit,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
