### ISSUE TITLE
Error reordering by dragging line (rather than placeholder handle)

### ISSUE THREAD

**Issue by jbeaven** [PrestaShop/PrestaShop#21035] opened 2020-09-17 10:48 UTC
https://github.com/PrestaShop/PrestaShop/blob/42833c4097071b46f37b76f6c347fb579447e3e1/admin-dev/themes/default/js/bundle/product/catalog.js#L75

On this line PS calculates the TR that is being moved, and marks the line as having been changed. Later this flag is used to determine what changes need to be saved after reordering (and clicking Save & refresh).

This works great when dragging by the placeholder handle (uppy downy arrows), but it is also possible to drag and drop the whole line to reorder the products. When dragging the whole line (i.e. the TR itself), PS fails to find the "parent TR", and so fails to mark the line as changed - this results in PS thinking there have been no changes and therefore nothing to save.

Steps to recreate:

1. Go to Products admin in the BO
2. Choose category in Filter by categories selector (to enter reorder mode)
3. Reorder a product by clicking down on the ID, moving to a new location and letting go - note the bulk_action_selected_products[] checkbox does not change state
4. > error - checkbox should change state
5. Click Save & refresh button, nothing happens (as PS thinks there is nothing to save)

For step 4, instead drag by the placeholder handle (⇅) - checkbox does set, and saving does store the reorder

L75 needs to be modified to take into account dragging the TR..

**Comment by florine2623** [comment] 2020-09-17 12:56
Hi @jbeaven ,

I managed to reproduce the issue in PS 1.7.6.5 and PS 1.7.7.0.
Clicking on the arrows (⇅) to reorder works, but clicking anywhere else on the product line does effect the reordering feature.

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15291. You can follow the progression there.
Thanks!

**Comment by florine2623** [comment] 2020-09-17 12:58
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/15291

**Closed as completed** 2020-09-17 12:59 UTC
Labels: BO, Duplicate
