### ISSUE TITLE
The button<add new product> stills in English whatever the language.

### ISSUE THREAD

**Issue by AchrafKchaou1991** [PrestaShop/PrestaShop#32428] opened 2023-05-03 15:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you change the langage to an other one , except English , the button `add new product`  appears also in English.
[Issue<Add new product>.webm](https://user-images.githubusercontent.com/131356155/235963816-4033d7fd-1af3-4c37-9b0b-14d69ff90ebf.webm)

### Expected behavior

The button `<add new product >` shall be appear in adequate language.

### Steps to reproduce

1-Select a langage different than English
2-Go to  Catalog > Products >  
3-See error > You find <add new product > in English 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2023-05-09 06:06
Hello @AchrafKchaou1991 

I reproduce the issue only with develop, so it's a regression! see the attached screen record below:

[issue_32428.webm](https://user-images.githubusercontent.com/23308427/237008237-0ca9ddb0-cee8-4cb7-bd73-c52fd1e887db.webm)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by l-delin** [comment] 2023-05-10 07:17
Hello, 
I think that’s because the CTA `new product` was changed to `Add new product` in [this PR](https://github.com/PrestaShop/PrestaShop/pull/31322) so the string isn’t available on Crowdin yet. 
It’ll be fixed soon once the [8.1.x catalog](https://github.com/PrestaShop/PrestaShop/pull/32147) is pushed to Crowdin for translation

That's why you have the same issue here:
![image](https://github.com/PrestaShop/PrestaShop/assets/113511191/70ffa595-7430-4baa-8c54-af179b45f868)

**Comment by l-delin** [comment] 2023-06-22 12:38
Hello, this has been fixed :-)

See: 

<img width="1418" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/c88062f1-88e1-4530-867b-c87865d1651a">

<img width="1418" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/a263faae-fdcc-4dc8-b742-0146b7877346">

<img width="1418" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/152290c3-1c9b-474c-866d-256ad0397b02">

etc.

Thanks!

**Closed as completed** 2023-07-06 09:57 UTC
Labels: Bug, develop, Minor, BO, Translations, Regression, Fixed, Verified, 8.1.x
