### ISSUE TITLE
No carriers available when it's an old customer account

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#17127] opened 2020-01-13 09:36 UTC
**Describe the bug**
Hello,

I saw there were several tickets already open for that.

I just wanted to see this problem with you in a different way.
A customer had already placed an order in 2017. Then we did a migration from 1.5 to 1.7.6.0 and the customer tried to recommend in 2020. But no carrier.
There were a lot of problems compared to the old customers.

Thanks to you

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6
https://github.com/PrestaShop/PrestaShop/issues/9932

**Comment by khouloudbelguith** [comment] 2020-01-13 10:48
Hi @ShaimyWinda,

If PrestaShop Carriers Are Not Available At Checkout, you need to check:

1. Carrier Is Inactive: PrestaShop carrier status is the first thing you should consider
Incorrect Zone Assign or Country Disabled: Zone association is among the first things to check if a created carrier does not show for a specific shopper. When configuring PrestaShop carrier you are supposed to assign it to zones, this very carrier can deliver parcels within. If a carrier is not assigned to the zone, customer address belongs to, then it will not show as a delivery method at the checkout.
2. Carrier Is Not Allowed for Customer Group: This detail might easily be skipped, since you can have hundreds and thousands of customers, belonging to various customer groups. If some customer belongs to the group that is not served by the current shipper, it will not be offered as a delivery method for this customer
3. Weight or Price Ranges Are Not Specified: Creating PrestaShop carrier you usually define billing cost for each by one of the criteria: order price or weight. Having selected a suitable method, you need to create ranges and set prices for them. In case ranges are not created, “The product selection cannot be delivered by the available carrier(s). Please amend your cart” message will display at shipping step for a customer.
4. Package Dimensions Are Out of Range: If all above listed settings are configured properly but still PrestaShop carrier does not display at the checkout, you have to compare package dimensions with maximum dimensions PrestaShop carrier can handle. If the package goes beyond these limits, the carrier can’t ship it and, respectively will not display as a delivery method.


- 1. This issue #9932 is reproduced folowing these steps:
- https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-561569640 & it is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/15399 in the next version PS1.7.7.0.
- 2. Also, there is another issue: https://github.com/PrestaShop/PrestaShop/issues/15703 fixed in the PS1.7.7.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/15710 & this PR: https://github.com/PrestaShop/PrestaShop/pull/16915
- 3. Maybe related to this issue: https://github.com/PrestaShop/PrestaShop/issues/10903#issuecomment-438573882, it is added to our bug roadmap => not fixed yet.

Thanks to check & feedback.

**Comment by ShaimyWinda** [comment] 2020-01-13 13:27
Hi @khouloudbelguith 
None of that. I fixed the code with the fixes you made and nothing works.
Thanks!

**Comment by jf-viguier** [comment] 2020-01-13 17:46
Hi @ShaimyWinda check that this customers have addresses. I had this bug too.

**Comment by ShaimyWinda** [comment] 2020-01-14 14:39
Hi @jf-viguier yes the customers have addresses.

The problem is since the migration from 1.5 to 1.7, all customers who ordered on our site in 1.5 now have this problem in 1.7, they have to redo an account @khouloudbelguith 

Thanks

**Comment by khouloudbelguith** [comment] 2020-01-14 15:27
@ShaimyWinda, what is the exact tool did you use to upgrade your shop?
 It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.6.0. 
Thanks to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.0 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.0/install-dev/data/db_structure.sql
Thanks!

**Comment by ShaimyWinda** [comment] 2020-01-14 15:44
@khouloudbelguith they used 1-Click Upgrade
Which table i have to check ?

Thanks

**Comment by khouloudbelguith** [comment] 2020-01-14 16:26
@ShaimyWinda, what is the exact version did you use of the 1-click upgrade did you use?
In fact, for the 1.5: you can use the 1-click upgrade v1.6.8, for PS1.6 => 1.7, you can use 1-click upgrade v4.10.1.
https://addons.prestashop.com/en/data-migration-backup/5496-.html

>Which table i have to check ?

You need to check your database.
Thanks!

**Comment by ShaimyWinda** [comment] 2020-01-15 10:10
Hi @khouloudbelguith !
It doesn't make sense, I made a copy of the prod and put it in preprod. everything works well in preprod, I log in as this customer and I can see the carriers.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-15 10:15
@ShaimyWinda, thanks for your feedback.
It could be a cache issue.
Since it is fixed, I will close the ticket, feel free to open a new one when needed.

Thanks!

**Comment by ShaimyWinda** [comment] 2020-01-15 10:18
But it's not working in prod ... @khouloudbelguith

**Comment by khouloudbelguith** [comment] 2020-01-15 10:19
@ShaimyWinda, Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by ShaimyWinda** [comment] 2020-01-15 10:28
@khouloudbelguith Nothing's changed  :/

**Comment by ShaimyWinda** [comment] 2020-01-15 10:34
I have other question. Prestashop sends auto mail with the php mail() function.  The problem is that some mails don't work properly. There are variables in the mail templates. A client has received the mail with the variables that have not changed. I tested with several emails (different domain name) and the variables are replaced by the value. Do you think it's related to the server or to Prestashop?

**Comment by khouloudbelguith** [comment] 2020-01-15 10:48
@ShaimyWinda,
> A client has received the mail with the variables that have not changed

It could be similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/13386
When the email address in uppercase, emails are not well working.
It is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16550 in the PS1.7.7.0.
Thanks to check & feedback.

**Comment by ShaimyWinda** [comment] 2020-01-15 11:12
@khouloudbelguith 
> It could be similar to this issue: #13386

That's got to be it, both clients have uppercase in their e-mail addresses. 
Thanks so much !!!

**Comment by ShaimyWinda** [comment] 2020-01-15 11:21
But i check commit ,I see you haven't changed anything

**Comment by khouloudbelguith** [comment] 2020-01-15 12:32
@ShaimyWinda,
>But i check commit ,I see you haven't changed anything

You need to make those changes
https://github.com/PrestaShop/PrestaShop/pull/16550/files

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-14 08:05
Hi @ShaimyWinda,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-14 08:05 UTC
Labels: Bug, FO, Customer, Carriers, No change required, Checkout, 1.7.6.0
