### ISSUE TITLE
Upgrade button is shown and does not behave correctly for composer-installed module

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#11450] opened 2018-11-20 15:45 UTC
**Bug reported by twitter (https://twitter.com/SebBareyre/status/1060570874552565760)**

**To Reproduce**
Here is the transcript from our discussion on Gitter
```
S: I've a seller account on addons.prestashop.com, I sell 2 modules. I also use this modules in our projects. I deploy this module using composer and a bitbucket private repository

M: So your customers install the module using Addons marketplace
But you also use this module for your projects, and this time you install it using composer
=> correct  ?

S: When I update my module with composer, an "upgrade" button appear in the PrestaShop BO, and when I click on it, the following error occurs
https://pbs.twimg.com/media/DrfnNqyWkAI1IO3.jpg:large
So, I don't understand the link between zip error and deployment via composer..

M: I think the bug is that this "upgrade" button appears for wrong reasons
and it is very strange, because in the screenshot you provided, I see the "login on addons marketplace" button
which means you are not logged in on the marketplace so you should not be able to perform any upgrade

S: I'm not logged in the addons marketplace
And usually, the upgrade button is displayed even if I am not identified in the marketplace for other developer modules

M: developer modules = modules you have created and installed by yourself ?

S: no, modules which belong to others developers

M: do you know if these other modules have been installed using Addons marketplace or by yourself (composer or drag-and-drop the ZIP archive) ?

S: I think, the "Upgrade" button could appear for my module but on click, it is necessary that it runs the latest Upgrade methods of module
(drag'n'drop with zip, but I receive alerts of newer version thanks to the "Upgrade" button)

M: but this Upgrade button
why do you need it for the modules on your project ?
because I guess the bitbucket version is the latest
Addons marketplace version is older, isn't it ?

S: To run upgrade methods no ?
or the simple visit of module page will run it ?
bitbutcket version and addons marketplace are quite the same, (just the delay of the technical validation)

M: I think I get it
with composer you update the files
but then you want to run the update() php function
so you click on "Upgrade" button
```

![drfnnqywkai1io3](https://user-images.githubusercontent.com/3830050/48784713-82bdac80-ece3-11e8-8b63-a6d1ae13586b.jpg)

So here are the things to do IMO:
- investigate why the "Upgrade" button is displayed although the user is not logged in Addons marketplace
- investigate what happens when we click on this button and why there is this error
- identify this usecase (module being sold on Addons marketplace but also being installed by Composer) and see how it is handled by PrestaShop project

**Comment by khouloudbelguith** [comment] 2018-11-21 11:24
Hi @matks,

I manage to reproduce the issue with PS1.7.4.4 & the blockyoutubevideos module.
1. The upgrade button is displayed in the two cases, when I'm logged & I'm not.
2. If I click on the upgrade button, I have a different issue
![image](https://user-images.githubusercontent.com/16067358/48838339-56a83700-ed88-11e8-94fd-3e788014ab27.png)
@marionf, what do you think?
Thanks!

**Comment by matks** [comment] 2018-12-05 09:17
This might be related to another issue we got with module ps_linklist (https://github.com/PrestaShop/PrestaShop/issues/11619)
The issue with ps_linklist is:
- when installed with Composer, vendor files and autoload file are merged within global `vendor` PrestaShop project (which is the standard behavior of Composer dependencies)
- when installed through Addons (or upgrade), vendor files and autoload file are packaged within the module in a dedicated `vendor` folder inside the module

So the autoload requirement is not the same.

**Comment by SebBareyre** [comment] 2019-01-03 09:20
Yes @matks but, in my case, I don't need `vendor` directory in my module..

**Comment by marionf** [comment] 2019-05-28 13:19
@khouloudbelguith Could you try to reproduce it with 1.7.6.0 ?

**Comment by khouloudbelguith** [comment] 2019-05-28 13:31
Hi @marionf,

The upgrade button is not displayed with PS1.7.6.0.
![image](https://user-images.githubusercontent.com/16067358/58481894-3a30f100-8155-11e9-81cb-83242893036b.png)

It could be because modules have not been updated yet for 1.7.6.
I tried with another module => the upgrade button is not displayed
![image](https://user-images.githubusercontent.com/16067358/58482268-fa1e3e00-8155-11e9-8e03-5ca173b6e374.png)

But we have another version on the marketplace
https://addons.prestashop.com/en/blog-forum-new/41015-blog-pro.html
@marionf what do you think?

Thanks!

**Comment by marionf** [comment] 2019-05-28 13:51
Yes, we need to wait the update of the modules to test it again :+1:

**Comment by khouloudbelguith** [comment] 2019-08-02 15:44
Hi @marionf,

I have the same issue with PS1.7.6.0.
https://drive.google.com/file/d/1boEu8Nf4df-PkJLPah7M00UcvVUQatsU/view
![image](https://user-images.githubusercontent.com/16067358/62382115-d2c46280-b544-11e9-80ec-5026bc51e9d6.png)

Thanks!

**Comment by Djolhan** [comment] 2019-11-25 08:09
I think this can be related to the licence status ? If licence is expired, and module update is major, then, the error is probably incorrect and must be, your licence don't allo you to update the module, Zen option is needed to extend updates status ?

**Comment by marionf** [comment] 2021-12-10 10:58
This issue is related to the upgrade of modules bought on the marketplace.
With the separation between the company and the OS project in the V8, the upgrade of the module bought on the marketplace will not be possible in one click like currently.
So, I close this issue.

**Closed as completed by marionf** 2021-12-10 10:58 UTC
Labels: Bug, Minor, Modules, Module manager, 1.7.6.0
