### ISSUE TITLE
ps_facetedsearch problem with subcategory filter

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#24881] opened 2021-06-08 20:02 UTC
Hello dear PrestaShop contributors ! I encounter a problem with the ps_facetedsearch module : The subcategories filters are not working 😔

Here is an example: 

I have a category named "Enfants" that have two subcategories: "Filles" and "Garçons".

<img width="1209" alt="Capture d’écran 2021-06-08 à 21 45 33" src="https://user-images.githubusercontent.com/167037/121247733-e197a100-c8a2-11eb-90fa-6b5cdada5437.png">

If I click on "Garçons" to filter the products and only display the products associated with the "Garçons" category the filter is not working and seems to display random results.

<img width="1256" alt="Capture d’écran 2021-06-08 à 22 00 40" src="https://user-images.githubusercontent.com/167037/121249666-202e5b00-c8a5-11eb-9e27-a764f0526208.png">

Maybe the problem comes from the fact that we have multiple (5) times the same category name (Garçon) but in another place in the category tree?

Module version is the last : v3.7.1
PrestaShop version is v1.7.6.3

Regards,

David.

**Comment by hibatallahAouadni** [comment] 2021-06-09 08:56
Hello @Daaaaad 

Could you please respect and **follow the provided template to submit a complete bug report**.
Please edit your issue description and notify me :wink: 

Thanks!

**Comment by Prestaworks** [comment] 2021-06-10 07:01
@hibatallahAouadni 
Same as this https://github.com/PrestaShop/PrestaShop/issues/24764

**Comment by hibatallahAouadni** [comment] 2021-06-15 15:34
Hello @Daaaaad 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24764. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @Prestaworks for the tip :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-15 15:34
Duplicate of #24764

**Closed as completed by hibatallahAouadni** 2021-06-15 15:34 UTC
Labels: Bug, FO, Duplicate, Faceted search, 1.7.6.3
