### ISSUE TITLE
after upgrade to 1.7.5.1 uploading image 500 error 

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#12807] opened 2019-03-06 16:03 UTC
After upgrading from PS 1.7.4.4 to 1.7.5.1 

500 error with attempt to upload jpg 800x800 46kB product image from back office

from server log: 500 error access denied img folder
img folder and file permission: 755

**Comment by khouloudbelguith** [comment] 2019-03-06 16:11
Hi @Peter4661,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Peter4661** [comment] 2019-03-06 20:37
Server setup & configurations
-----------------------------------------------------------------------------------------------------------------
Servergegevens Linux #1 SMP Wed May 2 07:43:19 EDT 2018 x86_64
Server softwareversie: Apache
PHP-versie: 7.2.15
Geheugenlimiet: 1024M
Maximale uitvoeringstijd: 300
Maximale bestandsgrootte voor uploads: 128M
info_outline Database informatie
MySQL versie: 10.0.37-MariaDB-cll-lve
MySQL-server: localhost
MySQL-naam: debxxxxx_ps1
MySQL-gebruiker: debxxxx_ps1

Tabellen voorvoegsel: ps_
MySQL-engine: InnoDB
MySQL-driver: DbPDO

fo_outline Winkel informatie

PrestaShop-versie: 1.7.5.1
Winkel-URL: http://www.derks-wielersport.nl/
Huidig gebruikte thema: classic

Verplichte parameters: Oké
Optionele parameters: Oké
-------------------------------------------------------------------------------------------------------
No errors in apache error log
--------------------------------------------------------------------------------------------------------

[screenshot_backoffice-500error-01.pdf](https://github.com/PrestaShop/PrestaShop/files/2938035/screenshot_backoffice-500error-01.pdf)
[screenshot_backoffice-500error-02.pdf](https://github.com/PrestaShop/PrestaShop/files/2938037/screenshot_backoffice-500error-02.pdf)
[screenshot_backoffice-500error-03.pdf](https://github.com/PrestaShop/PrestaShop/files/2938039/screenshot_backoffice-500error-03.pdf)
[screenshot_backoffice-500error-04.pdf](https://github.com/PrestaShop/PrestaShop/files/2938040/screenshot_backoffice-500error-04.pdf)

**Comment by Peter4661** [comment] 2019-03-07 08:37
some further research:

Now Apache server error warning after trying to upload product image from backoffice!

[Thu Mar 07 08:44:38.325755 2019] [hostinglimits:error] [pid 728444:tid 140708352616192] mod_hostinglimits: Error on LVE enter: LVE(657) HANDLER(application/x-httpd-lsphp) HOSTNAME(www.derks-wielersport.nl) URL(/index.php) TID(728504) errno (7) Read more: http://e.cloudlinux.com/MHL-E2BIG min_uid (500)

I checked http://e.cloudlinux.com/MHL-E2BIG for info, No suggestion related to 500 error

**Comment by khouloudbelguith** [comment] 2019-03-07 10:36
Hi @Peter4661,

Your ticket is a duplicate of #11939
You can follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/11939#issuecomment-455982698) to fix the issue.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 10:36
Duplicate of #11939

**Closed as completed by khouloudbelguith** 2019-03-07 10:36 UTC
Labels: Bug, Duplicate, Image, Autoupgrade, 1.7.5.1

**Comment by Peter4661** [comment] 2019-03-07 10:48
I found cause of the issue, 508 error / Smarty cache ( from Apache error log)

With all cache disabled ( Prestashop smarty, CSS, Java ) and caching module PageCache Ultimate, upload of image from backoffice was Oke.

With step by step enabling cache and checking image upload error, it turned out issue occurs with PageCache enabled.

I have forwarded this problem to the Pagecache Ultimate developer 

Thank you,

Peter

**Comment by khouloudbelguith** [comment] 2019-03-07 10:49
@Peter4661, you are welcome!
Feel free to open a new one when needed.
Thanks!
