### ISSUE TITLE
Remove anchor in URL for products

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#16413] opened 2019-11-14 14:33 UTC
Is this anchor needed?
https://github.com/PrestaShop/PrestaShop/blob/e136975bf809f89f35fdd59a785806e3e0bf8eab/classes/Link.php#L233

I've replaced this line by:

```php
$anchor = '';
```

And everything seems to be working fine.

This anchor generates a URL that seems longer than necessary. Perhaps this anchor should be removed or an option should be given to enable/disable it globally if necessary (as suggested in #11041)?

**Comment by khouloudbelguith** [comment] 2019-11-14 14:45
Hi @yannicka,

Thanks for your report.
@yannicka, Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

Ping @PrestaShop/prestashop-core-developers, @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by yannicka** [comment] 2019-11-14 14:47
I'm able to make a pull request with my suggestion, but I think it's too naive. It would be best to have a setting to enable/disable this.

**Comment by khouloudbelguith** [comment] 2020-02-28 08:30
Hi @yannicka,

Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/11041
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-28 08:30
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/11041

**Closed as completed by khouloudbelguith** 2020-02-28 08:30 UTC
Labels: Improvement, CO, Duplicate
