### ISSUE TITLE
1.7.8.2 - Wrong search box size - Backoffice (Spanish, Portuguese, etc.)

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#26965] opened 2021-12-13 12:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

You closed ticket https://github.com/PrestaShop/PrestaShop/issues/26955#issue-1077692876 incorrectly. Please read what I'm writing!

Visit your own demo and **go to orders**:

https://demo.prestashop.com/#/en/back

and now in spanish (**go to orders** also:

https://demo.prestashop.com/#/es/back

As you can see the search box is messing with the layout.

### Expected behavior

The search box must have the same size in all languages.

### Steps to reproduce

Visit your own demo and go to orders:

https://demo.prestashop.com/#/en/back

and now in spanish (go to orders also:

https://demo.prestashop.com/#/es/back

As you can see the search box is messing with the layout.

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by ocio87** [comment] 2021-12-13 13:36
Hello,

In my test environment it is also seen with the problem.

![image](https://user-images.githubusercontent.com/12537826/145822033-52848b49-b10b-41f0-b2b4-6a3ed4e607d1.png)

**Comment by hibatallahAouadni** [comment] 2021-12-13 15:57
Hello @seederp2p 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26635. 
It's already fixed with this PR #26691

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-13 15:58
Duplicate of #26635

**Closed as completed by hibatallahAouadni** 2021-12-13 15:57 UTC
Labels: Bug, Duplicate, Invalid
