### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data + form.js

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#12654] opened 2019-02-21 10:22 UTC
**Describe the bug**
Impossible to update product.
Error message : 
JSON.parse: unexpected character at line 1 column 1 of the JSON data + form.js
 form.js:703:16

    error /admin9-/themes/new-theme/public/main.bundle.js:313 fireWith /admin9-/themes/new-theme/public/main.bundle.js:313 i /admin9-/themes/new-theme/public/main.bundle.js:313 t /admin9-/themes/new-theme/public/main.bundle.js:313 

For some products, no errors.
But I don't find any difference.

I try with a produt empty, and I've the same error (copy from a product with problem).

**To Reproduce**
Just update a product

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-02-21 10:24
Hi @pppplus,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by pppplus** [comment] 2019-02-21 11:01
Hi
host : my own server
server : directadmin + php 7.2 + nginx

debug mode  : 
https://my url/admin9-/index.php/sell/catalog/products/5307?_token=naOl3dNbZvbmSYxdlx27lH2XfFUfn4DToL7vs7m4MnA

Method
    POST
HTTP Status
    500
IP
    my IP 
Profiled on
    Thu, 21 Feb 2019 11:50:40 +0100
Token
    939aa7


PHP logs : nothing
nginx logs : nothing
javascript console log : as written above

**Comment by pppplus** [comment] 2019-02-21 11:07
now, error 400
/admin9-/index.php/sell/catalog/products/4635?_token=ENdBxVtPO6-lCjejNq_hCWJypY7_vZDuPTunW9wt-QM

Method
    POST
HTTP Status
    400

Profiled on
    Thu, 21 Feb 2019 12:05:41 +0100
Token
    751d63

**Comment by khouloudbelguith** [comment] 2019-02-21 11:27
@pppplus, without PHP error log & the debug mode only display an error 500/400, cannot help us to understand the issue.
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

PS: I tried with nginx/1.14.0, I make an upgrade from PS1.7.5.0 to PS1.7.5.1 with 1-Click upgrade v4.6.0. & it is OK when updating a product.
Thanks!

**Comment by pppplus** [comment] 2019-02-21 11:27
The problem seems to be in tags.
I've a ° caracter in tags.
If I delete it, no more error.

**Comment by khouloudbelguith** [comment] 2019-02-21 11:28
@pppplus, this issue occurs with old products?
Thanks!

**Comment by pppplus** [comment] 2019-02-21 11:30
I think this bug was not present in 1.7.5.0
On 1.7.5.0, there was a bug in SEO tabs, with "special" caracters.
I suppose something has been changed to work in 1.7.5.0, and now bug is on tags.

**Comment by khouloudbelguith** [comment] 2019-02-21 11:39
@pppplus, I tried with PS1.7.5.0 fresh install & PS1.7.5.1 fresh install ( after upgrade), when I edit a product, in the options Tab, I add this "° c", an exception is displayed.
![image](https://user-images.githubusercontent.com/16067358/53166358-5ca2f380-35d5-11e9-9c17-f140478abe91.png)
You don't have this alert in your case when you click save?
Thanks!

**Comment by pppplus** [comment] 2019-02-21 11:39
@khouloudbelguith : what do you mean by old products ?
Yes, it's products on my store

**Comment by pppplus** [comment] 2019-02-21 11:44
nope, impossible for me, to add a tag with ° (french language for me)

**Comment by pppplus** [comment] 2019-02-21 12:18
sorry, I've readden your message too quickly.
about alert : no, I've nothing, just, a message on top right, 
"Impossible de mettre à jour les paramètres"

**Comment by khouloudbelguith** [comment] 2019-02-21 13:18
@pppplus, did you make an upgrade from PS1.7.5.0?
Before the upgrade, have you some products with tags which have special characters?
In fact, this issue is fixed in ps1.7.5.0: https://github.com/PrestaShop/PrestaShop/pull/10856
Thanks!

**Comment by pppplus** [comment] 2019-02-21 13:27
Hi
Yes, tags have been sent via import data, from csv files.

So, I suppose tags should not have been accepted, via import menu.

**Comment by khouloudbelguith** [comment] 2019-02-21 14:15
Hi @pppplus,

About the import which shouldn't accept tags with specials characters, we are aware of this issue, you can follow this ticket: #9677
About updating products with PS1.7.5.1 after an upgrade, I did not manage to reproduce the issue.
I attached a video record.
https://drive.google.com/file/d/1I63vy7mAe5wltyvWuugUOsyyC3TZWsmq/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-03-25 07:55
Hi @pppplus,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-25 07:55 UTC
Labels: Bug, BO, No change required, 1.7.5.1
