### ISSUE TITLE
AdminOrders generateInvoicePdf and generateDeliverySlipPdf should be in customer language, not employee language

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#15768] opened 2019-10-01 08:26 UTC
Today when you click the two buttons Invoice and Delivery-slip, PrestaShop generates a PDF in employee language.

**Issue:** 
Often a delivery slip is printed from AdminOrders and put into the customers package before shipping. If a customer speaks another language that what language is set in the current logged in employee/admin, he will get a delivery slip / invoice in a language he cannot understand.

**Solution:** 
Generate PDFs in customer context language, not employee.

**Alternative:**
Modify buttons to be dropdowns instead, with select options: 
- Customer language
- Employee language

as discussed on gitter with @matks

**Comment by khouloudbelguith** [comment] 2019-10-01 08:57
Hi @onklmaps,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10258
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-01 08:58
Duplicate of #10258

**Closed as completed by khouloudbelguith** 2019-10-01 08:57 UTC
Labels: Duplicate
