### ISSUE TITLE
Template evaluation reset state of some components

### ISSUE THREAD

**Issue by matix931** [PrestaShop/PrestaShop#12269] opened 2019-01-23 07:05 UTC
Description
Template evaluation reset state of some components. If you change value of spinner a then quicky open combobox, combobox will be closed instantly. It also occurs almost everywhere if you are clicking, scrolling or browsing page fast enough.

1. Use default template - classic (You can even go to demo page of PrestaShop)
2. Open some product
3. Change item amount by clicking spinner's up arrow
4. Quickly click on the photo to open modal window
5. Modal window will disappear immediately
6. You can't do nothing, have to refresh page

PrestaShop version: 1.7.5.0
PHP version: Any
Template: classic

**Comment by khouloudbelguith** [comment] 2019-01-23 08:00
Hi @matix931,

Have you the same issue reported in this ticket: #9634?
Thanks!

**Comment by matix931** [comment] 2019-01-23 08:51
Yes, i have also the same issue.
Page freezes after double click on "add to cart".

**Comment by khouloudbelguith** [comment] 2019-01-23 08:58
Hi @matix931,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9634
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-23 08:58
Duplicate of #9634

**Closed as completed by khouloudbelguith** 2019-01-23 08:58 UTC
Labels: FO, Duplicate, 1.7.5.0
