### ISSUE TITLE
Wholesale Price rounded on save (Product with combinations)

### ISSUE THREAD

**Issue by psydomin** [PrestaShop/PrestaShop#15839] opened 2019-10-04 15:07 UTC
**Describe the bug**
If you set the wholesale price of a combination to 1.11 and save. Reload the page and save again. The wholesale price of the combination will be rounded to 1.00000.
If after changeing the wholesale price and saving you open the combination, click the input field and save, it wont change the wholesale price.

As far as I could tell it only happens with wholesale price. 

**To Reproduce**
1. Go to combination and set a decimal wholesale price (ex: 1.11)
2. Save
3. Reload/Refresh page
4. Save
5. Open combination - the wholesale price will be set to 1.000000

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.22

**Comment by khouloudbelguith** [comment] 2019-10-04 15:12
Hi @psydomin,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9972
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-04 15:12
Duplicate of #9972

**Closed as completed by khouloudbelguith** 2019-10-04 15:12 UTC
Labels: Duplicate
