### ISSUE TITLE
Allows filtering products on manufacturer pages

### ISSUE THREAD

**Issue by titodevera** [PrestaShop/PrestaShop#27671] opened 2022-02-14 18:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Several of our clients have asked us to be able to filter products on the manufacturer pages of their stores, this situation forces us to purchase a third party module that offers this feature. I think it would be great if the official module would work in other pages that are not categories, my PR is a step forward to get to achieve this.
PR:  [#615](https://github.com/PrestaShop/ps_facetedsearch/pull/615)

### Describe the solution you'd like

Allow to filter/search products on the brand pages

### Alternatives you've considered

I think that this issue is related #15137 to this to

### Additional context

![filter](https://user-images.githubusercontent.com/11556124/153924091-3c66b477-5497-4be9-b615-bbeee213170b.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment] 2022-02-14 18:48
Hello @titodevera 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15137. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-02-14 18:48
Duplicate of #15137

**Closed as completed by hibatallahAouadni** 2022-02-14 18:48 UTC
Labels: Feature, Duplicate, Invalid

**Comment by daniweb78** [comment] 2023-06-06 08:46
How can I install and test the updated module?
