### ISSUE TITLE
Trash icon next to non-removable discounts in cart

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14015] opened 2019-05-29 12:44 UTC
**Describe the bug**
Trash icon/link is shown next to a voucher that can't be deleted. Can be confusing for a customer.

**To Reproduce**
1. Create automatic percentage discount on all orders and all customers.
2. Add some product to cart.
3. See a voucher.
4. Try to delete it.
5. Cart refreshes, voucher (obviously) doesn't get deleted.

**Additionnal information**
PrestaShop version: 1.7.6 beta

**Comment by khouloudbelguith** [comment] 2019-05-29 13:00
Hi @Hlavtox,

Yes, I have the same issue with PS1.7.5.2 & PS1.7.6.0beta.

- If we have a cart rule with a code, then customers can remove this cart rule from the FO
- If we have a cart rule with no code, then customers cannot remove this cart rule from the FO

I think it is normal behavior, because, a cart rule with no code is automatically applied to benefiting customers at checkout.

@marionf, what do you think?

Thanks!

**Comment by Hlavtox** [comment] 2019-05-29 13:02
Hi @khouloudbelguith,

the behavior is correct. Just hide the delete link/trash icon if the voucher is non-deletable and it will be fine. :-)

**Comment by khouloudbelguith** [comment] 2019-05-29 13:05
@Hlavtox, yes, it could be a good idea.
@colinegin, @marionf what do you think?

Thanks!

**Comment by colinegin** [comment] 2019-06-05 13:59
Hello @Hlavtox,

Thanks for your idea, you're right there should not be any trash icon ! 
@khouloudbelguith I think this is more a bug than an improvement, I'll change the label.

**Comment by marionf** [comment] 2019-06-07 14:53
Duplicate of #12608

**Closed as completed by marionf** 2019-06-07 14:53 UTC
Labels: Bug, PM ✔️, Trivial, FO, Duplicate, Cart rules, 1.7.5.2, 1.7.6.0
