### ISSUE TITLE
automatic index serch 

### ISSUE THREAD

**Issue by antondelrio** [PrestaShop/PrestaShop#15782] opened 2019-10-01 15:21 UTC
**Describe the bug**
Whenever you edit a product it dissapear from the search index.

**To Reproduce**
1. Go to any product.
2. Edit it.
3. Go to B.O -> Shop Parameters -> Search
4. the indexed products shows (x-1)/x

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.23

**Comment by khouloudbelguith** [comment] 2019-10-01 16:48
Hi @antondelrio,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1F600mL0i_fTonzebN9gKJD5BIWn8M1wB/view
Thanks to check & feedback.

**Comment by antondelrio** [comment] 2019-10-01 19:24
Hi khouloudbelguith,
that's really nice that you cannot reproduce the issue I am experience. But in fact the issue is happening to me (and as far as I see in the track list I am not the only one). So, any advice on how to report it or what to do to debug it, will be welcome, in order to find someone who can help me (us).
Thanks

**Comment by khouloudbelguith** [comment] 2019-10-02 08:52
@antondelrio, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JuanjoSCu** [comment] 2019-10-03 13:07
@antondelrio I think what I reported here https://github.com/PrestaShop/PrestaShop/issues/15640  happens to you

**Comment by khouloudbelguith** [comment] 2019-10-03 13:09
@antondelrio, are you assigning a supplier to a product ?

Thanks!

**Comment by antondelrio** [comment] 2019-10-03 21:13
Hi both,
first of all, thanks!

the problem happens with any change in the product. 

In the next video you can see it.
https://drive.google.com/open?id=1KFTV5tgw6RMMm5UI2_naeZQOERqqEuKJ

I attache the logs i can get. I don't know how to get the php an apache logs, and I asked them to the hosting provider. As soon as i get them i will post them.
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3688092/dev.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/3688093/prod.log)



[error_log.zip](https://github.com/PrestaShop/PrestaShop/files/3688100/error_log.zip)

**Comment by khouloudbelguith** [comment] 2019-10-04 08:18
@antondelrio, thanks for your feedback.
I found these errors:

>php.CRITICAL: Uncaught Exception: Price specification not found for currency: "" {"exception":"[object] (PrestaShop\\PrestaShop\\Core\\Localization\\Exception\\LocalizationException(code: 0): Price specification not found for currency: \"\" at /var/www/vhosts/nutribionatur.com/httpdocs/src/Core/Localization/Locale.php:171)"} []
[2019-08-19 14:57:49] request.CRITICAL: Uncaught PHP Exception PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException: "Price specification not found for currency: """ at /var/www/vhosts/nutribionatur.com/httpdocs/src/Core/Localization/Locale.php line 171 {"exception":"[object] (PrestaShop\\PrestaShop\\Core\\Localization\\Exception\\LocalizationException(code: 0): Price specification not found for currency: \"\" at /var/www/vhosts/nutribionatur.com/httpdocs/src/Core/Localization/Locale.php:171)"} []

Those are old errors, but did you delete any currency before?
>[2019-08-19 15:08:05] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Invalid argument supplied for foreach()" at /var/www/vhosts/nutribionatur.com/httpdocs/modules/stblogeditor/stblogeditor.php line 649 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /var/www/vhosts/nutribionatur.com/httpdocs/modules/stblogeditor/stblogeditor.php:649)"} []

You have an issue with the module stblogeditor, did you contact the module author about this error?

>[2019-10-03 22:41:06] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-10-03 22:41:06] php.DEBUG: Warning: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/composer.json) is not within the allowed path(s): (/var/www/vhosts/nutribionatur.com/:/tmp/) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/vhosts/nutribionatur.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":94,\"trace\":[{\"file\":\"/var/www/vhosts/nutribionatur.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":55,\"function\":\"getComposerRoot\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\LinkStub\",\"type\":\"->\"}],\"count\":1})"} []
[2019-10-03 22:41:06] php.DEBUG: Warning: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts) is not within the allowed path(s): (/var/www/vhosts/nutribionatur.com/:/tmp/) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/vhosts/nutribionatur.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":95,\"trace\":[{\"file\":\"/var/www/vhosts/nutribionatur.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":55,\"function\":\"getComposerRoot\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\LinkStub\",\"type\":\"->\"}],\"count\":1})"} []

Latest error => you need to modify the `open_basedir` settings in your PHP configuration.
The open_basedir setting is primarily used to prevent PHP scripts for a particular user from accessing files in another user's account. So usually, any files in your own account should be readable by your own scripts.

You need to check the issue with your host.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-04 07:53
Hi @antondelrio,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-04 07:53 UTC
Labels: BO, Search, No change required, 1.7.6.1
