### ISSUE TITLE
Hook displayAfterProductThumbs should give $product in the context

### ISSUE THREAD

**Issue by elburgl69** [PrestaShop/PrestaShop#19940] opened 2020-06-25 13:23 UTC
#### hook displayAfterProductThumbs has no product context

When I try to use the displayAfterProductThumbs hook in my module, I get no context of the product I am working with.

#### product-cover-thumbnails.tpl should add the product. 

The displayAfterProductThumbs hook should call the hook in product-cover-thumbnails.tpl like (last line):

```
{hook h='displayAfterProductThumbs' product=$product}
```
#### Alternatives you've considered

None

#### Additional context

None

**Comment by florine2623** [comment] 2020-06-25 14:02
Could you use the template to explain what the issue is ?
Send screenshots of exactly what you would like to see ?
Version of PS, etc

**Comment by elburgl69** [comment] 2020-06-25 14:28
Hook displayAfterProductThumbs is implemented in version 1.7.1.

I want to hook a module I am developing there. My module needs  to know which product it is operating on to construct the correct information. But the Product is not supplied in the $params when my module is called.

This is can be implemented by changing the last line in the classic template file:  
 /themes/classic/templates/catalog/_partials/product-cover-thumbnails.tpl

From:
```
{hook h='displayAfterProductThumbs'}
```
To:
```
{hook h='displayAfterProductThumbs' product=$product}
```

I want to publish my module in the module shop, but it  won't work fully if the template is not changed.

If you approve this request , I can make the change and create a pull request, if you want.

**Comment by florine2623** [comment] 2020-06-25 16:07
No PR will be approved for PS 1.7.1. It needs to be on version 1.7.6.5 or even better 1.7.7.0. Have you done the test on those 2 last versions ?

**Comment by elburgl69** [comment] 2020-06-25 19:35
Tested both, same  result.  Checked the development branch and the  implementation there is the same.

**Comment by Progi1984** [comment] 2020-06-30 15:10
@PrestaShop/prestashop-core-developers Do you think that the hook `displayAfterProductThumbs` can change by adding a parameter ?

**Comment by matks** [comment] 2020-07-09 15:54
I think it make sense. All hooks related to one product should pass the `$product` object to allow accurate customization from modules and themes.

**Comment by matks** [comment] 2020-07-09 15:55
@elburgl69 I can make the PR, it's very easy. Or do you want to do it ?

**Comment by elburgl69** [comment] 2020-07-10 07:37
If you have time, please do. Thnks.

**Comment by matks** [comment] 2020-07-10 08:23
Here it goes 😄  https://github.com/PrestaShop/PrestaShop/pull/20132

**Comment by matks** [comment] 2020-07-14 13:56
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20132

**Closed as completed** 2020-07-14 13:56 UTC
Labels: CO, Fixed, Developer Feature, PR available, Hook
