### ISSUE TITLE
Incorrect html lang

### ISSUE THREAD

**Issue by futurehousestore** [PrestaShop/PrestaShop#25042] opened 2021-06-19 20:25 UTC
#### Describe the bug

The HTML lang for the United Kingdom is GB which gives an error in SEO checks. The HTML lang should be en-GB

#### Expected behavior

The HTML lang value is the language code of the page's language.

#### Steps to Reproduce

1. Set English GB (English) as your website language (main or a second language)
2. In the front office open any of the GB pages 
3. Right click -> view page source
4. See that HTML lang is <html lang="gb">
5. Use any of the SEO online tools (Ahrefs, sitechecker, powermapper) to run an audit of the website
6. see the error HTML lang attribute invalid

**Screenshots**

![error1](https://user-images.githubusercontent.com/28427270/122654532-0e21a780-d144-11eb-97d8-5e0c14af6364.PNG)
![error2](https://user-images.githubusercontent.com/28427270/122654536-111c9800-d144-11eb-8888-492cda51015d.PNG)

#### Additional information

* PrestaShop version: all versions including 1.7.8.0

**Comment by hibatallahAouadni** [comment] 2021-06-21 09:09
Hello @futurehousestore 

Could you please check this issue #22962 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by futurehousestore** [comment] 2021-06-21 09:42
Thanks @hibatallahAouadni but issue #22962 is completely different and has nothing to do with my issue.

**Comment by florine2623** [comment] 2021-06-22 14:03
Hello @futurehousestore ,

Is this what you are referring to ?
![Screenshot 2021-06-22 at 16 01 54](https://user-images.githubusercontent.com/16019289/122938649-3c38fe80-d373-11eb-8374-f4cc6df0233b.png)

I used Google Chrome > Right Click > Inspect > Lighthouse > Launch audit.
Thanks!

**Comment by futurehousestore** [comment] 2021-06-22 14:14
Hi @florine2623 
I did not use your method but I used SEO website audit tools but it looks it is the same error.
html lang="gb"
which gives an error
to sort it out the html lang should look like that
html lang="en-gb"
Currently, it looks like this :
<img width="212" alt="Screenshot 2021-06-22 at 18 29 11" src="https://user-images.githubusercontent.com/16019289/122964635-c0957c80-d387-11eb-92d2-9a1a6755ae35.png">

**Comment by florine2623** [comment] 2021-06-22 16:31
ping @PrestaShop/product-team ,

Can the _html lang_ be changed to get a correct SEO ?

Thanks!

**Comment by futurehousestore** [comment] 2021-08-04 08:03
Hi, 
Any update on this issue? I would like to change the HTML lang manually to the correct one but there's no point if on the next Prestashop update it will still be gb instead of en-GB as it will cause more issues.
Thanks

**Comment by hibatallahAouadni** [comment] 2021-08-04 09:05
Hello @futurehousestore 

I tried with **powermapper** and it didn't display any error :confused: 
Could you please provide the link of SEO online tool that you used :pray: 

Thanks!

**Comment by futurehousestore** [comment] 2021-08-04 09:29
Hi @hibatallahAouadni have you used for your test a website with the United Kingdom English language set up?
I have done tests on the below tools
https://ahrefs.com/site-audit
https://freetools.seobility.net/
https://try.powermapper.com/ (the error is displayed in Accessibility)
https://sitechecker.pro/
all these tools display the error "HTML lang attribute invalid" there is no lang as "gb" it should be "en" or "en-us" or "en-gb" and for the United Kingdom it should be "en-gb"

**Comment by khouloudbelguith** [comment] 2021-08-06 10:28
Hi @futurehousestore,

I did not manage to reproduce the issue with PS1775.
I attached a screen record
https://drive.google.com/file/d/1Tgqn90L4sHxmVYYyRr14pDNW5ekagrP_/view?usp=sharing

Thanks to check and feedback

**Comment by futurehousestore** [comment] 2021-08-11 07:50
Thanks @khouloudbelguith but your testing is slightly different than mine. I use only the English GB language on my website and your test is done on a multilanguage website. Prestashop add a piece of code for multilanguage websites such as link rel="alternate" href="***" hreflang="en-gb" which I think fixes the issue found on SEO audit of a single language (GB) website. 
![7](https://user-images.githubusercontent.com/28427270/128990856-06544c40-ee1f-4c5b-adfc-dc027c39b191.PNG)
Can you test a website with a GB language only?
Thanks

**Comment by hibatallahAouadni** [comment] 2021-08-17 15:33
Ping @PrestaShop/product-team @Julievrz wdyt? should we change the value of lang attribute in html tag from **"gb"** to **"en-gb"**? or the value **"gb"** is the right one?

Thanks in advance :pray:

**Comment by MatShir** [comment] 2021-08-18 09:04
Indeed, there is a problem because "gb" is not part of the list of language tags (check link [here](http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)).
We can definitely use the language code defined by the IETF standard for the lang, like this we make sure that the language tag is the good one, and we won't have to worry about any other language

**Comment by NeOMakinG** [comment] 2021-08-18 09:26
Fixed here https://github.com/PrestaShop/PrestaShop/pull/25635

**Comment by eternoendless** [comment] 2021-08-20 14:21
Fixed by #25635

**Closed as completed by eternoendless** 2021-08-20 14:21 UTC
Labels: Bug, PM ✔️, Major, FO, SEO & URLs, Fixed, PR available, 1.7.8.0
