### ISSUE TITLE
Unable to save this image code 66

### ISSUE THREAD

**Issue by lewis2413** [PrestaShop/PrestaShop#12519] opened 2019-02-08 21:17 UTC
Hi

Im trying to save a image using  prestashop api, but i always get the 66 error code. The images are in my local machine into img directory, the only thing that i need is pass the url image and that the prestashop process associate it with product.

thanks

**Comment by khouloudbelguith** [comment] 2019-02-11 10:31
Hi @lewis2413,

I tried with this script:

```
<html><head><title>pUT DATA</title></head><body>
<?php

// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop');
define('PS_WS_AUTH_KEY', 'KEY');
require_once('PSWebServiceLibrary.php');
?>
<form enctype="multipart/form-data" method="POST" action="http://shop/api/images/products/14">
    <fieldset>
        <legend>Add image for products No 1</legend>
        <input type="file" name="image">
        <input type="submit" value="Execute">
    </fieldset>
</form>
<?php
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
$opt = array( 'resource' => 'images' );
$opt['postXml'] = $xml->asXML();
$xml = $webService->add( $opt );
?>
```
But I did not manage to reproduce your issue with PS1.7.5.0, thanks to check & feedback.

**Comment by lewis2413** [comment] 2019-02-11 13:39
Hi

Thanks for your response,  but i'm trying to create a new image using the
prestashop api non interface user....
*--*

*Saludos Cordiales*


*Ing. Jose Luis Idrogo*
Movil: +34 678 878385
Email: joseluis.idrogo@edisa.com
Web Site: http://www.edisa.com/
* <http://www.edisa.com/>*
*MADRID - BARCELONA - VIGO - OVIEDO - OURENSE - LAS PALMAS - MEXICO -
COLOMBIA - ECUADOR - REP. DOMINICANA - PANAMÁ*
*------------------------------CONFIDENCIALIDAD:* Este mensaje se dirige
exclusivamente a su destinatario y puede contener información privilegiada
o confidencial. Si no es vd. el destinatario indicado, queda notificado de
que la utilización, divulgación y/o copia sin autorización está prohibida
en virtud de la legislación vigente. Si ha recibido este mensaje por error,
le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda
a su destrucción.

Antes de imprimir este mensaje, asegúrate de que es necesario. Proteger el
medio ambiente está también en tu mano.

**Comment by khouloudbelguith** [comment] 2019-02-11 14:04
@lewis2413, yes, I'm adding an image using PrestaShop web service, I tried with a script & I used Postman also & it is OK.
https://drive.google.com/file/d/1LKUbQ89OF-1LlU6Y6TD3Uo8tgzoZzyft/view
You can follow this documentation:
http://doc.prestashop.com/display/PS16/Chapter+9+-+Image+management
Thanks to check & feedback.

**Comment by lewis2413** [comment] 2019-02-11 14:55
Hi

Can you send me the xml structure that you use?

Thanks

**Comment by khouloudbelguith** [comment] 2019-02-11 15:20
@lewis2413, as said before, I used this script

```
<html><head><title>pUT DATA</title></head><body>
<?php

// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop');
define('PS_WS_AUTH_KEY', 'KEY');
require_once('PSWebServiceLibrary.php');
?>
<form enctype="multipart/form-data" method="POST" action="http://shop/api/images/products/14">
    <fieldset>
        <legend>Add image for products No 1</legend>
        <input type="file" name="image">
        <input type="submit" value="Execute">
    </fieldset>
</form>
<?php
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
$opt = array( 'resource' => 'images' );
$opt['postXml'] = $xml->asXML();
$xml = $webService->add( $opt );
?>
```
When I used postman, in the Body, I selected form-data,
POST action: http://shop/api/images/products/id
For the second key, it is with type file.
![image](https://user-images.githubusercontent.com/16067358/52572819-fd94f000-2e18-11e9-8d2f-f6c87dd027fb.png)

Thanks!

**Comment by lewis2413** [comment] 2019-02-11 15:48
Ok perfect, let me check and i will come back to you

**Comment by khouloudbelguith** [comment] 2019-02-11 15:54
@lewis2413, thanks!
Waiting for your feedback.

**Comment by lewis2413** [comment] 2019-02-11 20:54
hi @khouloudbelguith 

i was checking your tips using the postman tool and i already send the image using the prestashop api, but when i send the request firstime, the image is inserted very good but i try change it again and the cover value is null....

thanks

**Comment by khouloudbelguith** [comment] 2019-02-12 07:51
Hi @lewis2413,

Thanks for your feedback.
I did not manage to reproduce your issue, I added more than one image via API & the cover image is well setted.
I attached a video record.
https://drive.google.com/file/d/1cPNBF7vZgpT2m82c0zzK5F4naNwN0dOJ/view
Thanks to check & feedback.

**Comment by lewis2413** [comment] 2019-02-12 08:49
Hi @khouloudbelguith 

When I send an image using the prestashop api, the image is associated correctly but when i try to change the image from the same product the image is not change.

**Comment by khouloudbelguith** [comment] 2019-02-12 10:04
@lewis2413, so you need to update an image.
To update an existing image, you can use this script

```
<html><head><title>pUT DATA</title></head><body>
<?php

// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop');
define('PS_WS_AUTH_KEY', 'KEY');
require_once('PSWebServiceLibrary.php');
?>

<form action="http://projet/1750/api/images/products/id_product/id_image" method="POST" enctype="multipart/form-data">
<fieldset>
    <legend>Update product image 1/2</legend>
    <input name="ps_method" value="PUT" type="hidden">
    <input name="image" type="file">
    <input value="Execute" type="submit">
</fieldset>
</form>
<?php
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
$opt = array( 'resource' => 'images' );
$opt['postXml'] = $xml->asXML();
$xml = $webService->add( $opt );
?>
```
as described in the documentation

```
<form action="http://eWURcnNJ6mbLUHB10EEIzTZsTShs33IX@myprestahop.com/api/images/products/1/2" method="POST" enctype="multipart/form-data">
<fieldset>
    <legend>Update product image 1/2</legend>
    <input name="ps_method" value="PUT" type="hidden">
    <input name="image" type="file">
    <input value="Execute" type="submit">
</fieldset>
</form>
```

With Postman, 
in the Body, I selected form-data,
POST action: http://shop/api/images/products/id_product/id_image
For the first key, it is with type file.
![image](https://user-images.githubusercontent.com/16067358/52627083-ed325300-2eb4-11e9-9fba-313c909bbb53.png)
https://drive.google.com/file/d/1fyJNEICwUMTHrIRD78ajTCxixrU0ytsy/view
Thanks!

**Comment by lewis2413** [comment] 2019-02-12 12:05
hi @khouloudbelguith 

Ok i understand, i have 2 questions.

1. Can I add the image path when I upload a product? 
2. The script that you´ve commented above, where do i must put it?

Thanks....

**Comment by khouloudbelguith** [comment] 2019-02-12 13:34
@lewis2413, I think no, it is not possible to add the image path when creating a product.
About the script, it is located in my project folder, you can follow this documentation, to get more information about webservice
http://doc.prestashop.com/display/PS16/Using+the+PrestaShop+Web+Service
All the example files can be found on our code repository: https://github.com/PrestaShop/PrestaShop-webservice-lib/tree/master/examples
Thanks!

**Comment by lewis2413** [comment] 2019-02-13 15:04
Hi @khouloudbelguith 

Ok, i will checking with my developers partners and back to you as soon as posible, by the last, we have a processs developed on PL/SQL, with this we connect to prestashop webservices using the api that you provide us.

**Comment by khouloudbelguith** [comment] 2019-02-13 15:07
@lewis2413,

Thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-07-16 10:09
Hi @lewis2413,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-16 10:09 UTC
Labels: Bug, WS, Image, No change required

**Comment by FrancescCommerce21** [comment] 2020-05-10 16:45
Hi @khouloudbelguith , i have a problem putting the legend/caption of an image and, as i'm seeing here, you add on postman a "legend" parameter but when i do it like you,  it don't works and the legend of the image added in prestashop is not setted.
So do you know how to set a legend to the image that i'm posting? 
Thanks in advance!

**Comment by FrancescCommerce21** [comment] 2020-05-14 11:53
solved here: https://www.prestashop.com/forums/topic/320713-update-image-legend-and-position-with-web-service/
