### ISSUE TITLE
Adding certain product combinations to the cart does not work

### ISSUE THREAD

**Issue by danielkauffman** [PrestaShop/PrestaShop#21602] opened 2020-10-25 04:30 UTC
In PrestaShop version 1.7.7.0 beta 2, I experienced what may be the same issue as #19554.

I created a product with combinations and attempted to add each combination to the cart. I was able to add two of three combinations to the cart, but was not able to add the third combination to the cart.

I then switched to the default theme and confirmed the above. When selecting the third combination, and clicking add to cart, the drop down would show correctly, but would not actually add to the cart. The first two combinations worked perfectly.

I then deleted all three combinations, regenerated the exact same combinations, and now am able to add all three combinations to the cart.

The issue may be related to the way I had originally created the combinations: I was testing the product combination feature, and had generated combinations one at a time, had deleted several combinations, and then generated more combinations, repeated several times, and several times had changed the relative positioning of the combinations using Catalog > Attributes & Features > Size > Positions > rearrange randomly.

Something about the third combination (perhaps the ids linking the products and attributes in the database) appears to have been corrupted, with the issue resolved by deleting and recreating the product combination.

**Comment by khouloudbelguith** [comment] 2020-10-26 09:03
Hi @danielkauffman,

Please in the next time, you need to follow GitHub's template.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

It could be a wrong way of combination's generate.
Can you provide me a screenshot from your product page > Combination Tab.

Thanks!

**Comment by danielkauffman** [comment] 2020-10-26 15:24
Hi @khouloudbelguith,

I don't see anything missing from my report... is there something specifically that you're wanting to see? I'm happy to add it.

Here's the screenshot of Catalog > Products > Combinations:

![product-combinations](https://user-images.githubusercontent.com/9503362/97191257-eff5da00-1763-11eb-9f05-5225ca05b62b.png)

And a screenshot of Catalog > Attributes & Features > Attributes > Size:

![size-attribute](https://user-images.githubusercontent.com/9503362/97191875-8de9a480-1764-11eb-955e-3d19f9ecb8ff.png)

**Comment by khouloudbelguith** [comment] 2020-10-26 15:40
@danielkauffman, I did not manage to reproduce the issue with 1770rc1build2.
I attached a screen record
https://drive.google.com/file/d/1Iz9csNcJfJ8oveg2SVFSKuV8Fy5VbtAT/view?usp=sharing
Also, in your case: BO > Shop Parameters > Product Settings page > "stock management" is disabled is it?

Thanks!

**Comment by danielkauffman** [comment] 2020-10-26 16:47
@khouloudbelguith Thank you for the screen record. As best I can tell, generating a complete set of combinations seems to work consistently. The issue seems to be related to creating combinations one at a time, then deleting one of more combinations (but leaving other combinations), and then recreating combinations. Also possibly related, during this process of adding/deleting/adding combinations, change the relative positioning of the combinations using Catalog > Attributes & Features > Size > Positions > rearrange randomly.

As best I can tell, some permutation of the above add/delete/rearrange/add/delete/rearrange gives rise to corruption in the product combination ids. Perhaps the id_attribute used by Add to Cart gets out of sync? The AJAX confirmation works, but the product is not actually added to the cart.

Hm, I'm wondering if there is some inconsistency between how the following ids are used by BO generate product combinations, BO rearrange attribute positions, FO templates for Add To Cart, FO AJAX confirmation page after adding to cart, and the FO add to cart controller:

- id_attribute_group
- id_attribute
- id_product
- id_product_attribute

When doing a {debug} on the product page, some of the above attributes are included multiple times, via:

- $attributesCombinations
- $groups
- $js_custom_vars

**Maybe the AJAX for the add to cart confirmation is using ids that originate from a different table than the add to cart form submission?**

And you are correct, stock management is disabled.

**Comment by khouloudbelguith** [comment] 2020-10-27 10:19
@danielkauffman,

>As best I can tell, some permutation of the above add/delete/rearrange/add/delete/rearrange gives rise to corruption in the product combination ids.

I tried random actions and it is ok with PS1770rc1build2.
I attached a screen record
https://drive.google.com/file/d/1pq-G8Xl08Xkg1KIn8oS2ts45NDIiZuAB/view?usp=sharing
Also, you can check this ticket: https://github.com/PrestaShop/PrestaShop/issues/19123, we re-working on the Product page - Combinations generator.

Thanks to check and feedback.

**Comment by danielkauffman** [comment] 2020-10-27 17:30
@khouloudbelguith the recording looks good, very similar to the steps I had taken that caused the issue. As far as I can tell, the only difference is different random permutations. But something that occurs to me, is that I am testing this on a low-powered server, and on a couple of occasions I've noticed it dropping packets. Dropping packets shouldn't be able to cause corruption to the database... but I wonder if maybe between the random changes to the combinations and attributes (similar to how you did in the video) PLUS maybe one of the connections dropped, that might be a factor? In any case, I'm continuing to watch and see if the issue recurs.

Thanks for the link to #19123. I added feedback on that issue, and hope it helps!

**Comment by hibatallahAouadni** [comment] 2020-10-28 07:52
Hi @danielkauffman 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem. We will close this issue.

Thank you!

**Closed as completed by hibatallahAouadni** 2020-10-28 07:52 UTC
Labels: Bug, BO, Can't reproduce, Combinations, Shopping carts FO, 1.7.7.x
