### ISSUE TITLE
Module Catalog Broken - Version 1.7.5.1

### ISSUE THREAD

**Issue by bestbuybargains** [PrestaShop/PrestaShop#13591] opened 2019-04-27 03:54 UTC
Hi.  When using PS 1.7.5.1, I run into various issues. This issue is regarding the Module Catalog. 

PrestaShop version: 1.7.5.1
PHP version: 7.0

1. Go to Modules > Module Catalog
2. See error

https://www.prestashop.com/forums/uploads/monthly_2019_04/1261342994_PrestaShop.thumb.JPG.12b7526d3fb7d2525fd2140f8b8e3003.JPG

**Comment by khouloudbelguith** [comment] 2019-04-29 09:33
Hi @bestbuybargains,

I did not manage to reproduce the issue with PS1.7.5.1
I attached a video record
https://drive.google.com/file/d/14ZpoGhNgZotZDMHeE-QsKf9YKZ-3ntk4/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
I think that your issue could be related to this 
https://github.com/PrestaShop/PrestaShop/issues/13590
Thanks to check & feedback

**Comment by bestbuybargains** [comment] 2019-04-29 19:17
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3128871/dev.log)

Logs are attached.

**Comment by khouloudbelguith** [comment] 2019-04-30 08:30
Hi @bestbuybargains,

Thanks for your feedback.
Wen debug mode is enabled, you don't have any exception displayed?
Thanks!

**Comment by bestbuybargains** [comment] 2019-04-30 17:58
https://drive.google.com/file/d/1nBy0mD2eYBmvoZqah33KnLqNiowzs-K9/view 

Here is a video of the issue.  Hope this helps. Updated logs are provided as well.

[dev.log](https://github.com/PrestaShop/PrestaShop/files/3132501/dev.log)

**Comment by bestbuybargains** [comment] 2019-05-01 00:27
Also, i noticed that this message randomly pops up.

![image](https://user-images.githubusercontent.com/50038176/57001384-070f3800-6b7e-11e9-8fe6-278892c70090.png)

**Comment by khouloudbelguith** [comment] 2019-05-02 08:57
Hi @bestbuybargains,

Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by bestbuybargains** [comment] 2019-05-02 17:08
Hello,
I have sent an email with the requested information. Please let me know if you need any assistance!

**Comment by khouloudbelguith** [comment] 2019-05-03 07:43
Hi @bestbuybargains,

I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-03 08:04
@bestbuybargains, it is OK.
https://drive.google.com/file/d/10JNVOFPw8uNV73xvxajWNsheIg-G85ec/view
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by peppoweb** [comment] 2019-05-10 09:11
Hi @khouloudbelguith  i have the same problem.
Can you explain me how to resolve?
Thanks! 
Regards

**Comment by khouloudbelguith** [comment] 2019-05-10 09:21
Hi @peppoweb,

No, I did not fix the problem, I just checked the shop of @bestbuybargains & I found that the bug doesn't exist anymore.
Thanks!

**Comment by peppoweb** [comment] 2019-05-10 09:41
I have the same problem into another shop.
When i click on Module Catalog link i see this attached screen.
![Schermata 2019-05-10 alle 11 40 57](https://user-images.githubusercontent.com/1136035/57518070-8805c680-7318-11e9-82dd-afece0e3afe2.png)

**Comment by khouloudbelguith** [comment] 2019-05-10 09:46
@peppoweb,
Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-10 10:01
@peppoweb, It is OK in your shop also.
I just sent you an email.
Thanks to check & feedback.

**Comment by bestbuybargains** [comment] 2019-05-10 11:51
To resolve your issue, please delete all of your browsing history, cache, and cookies. I had the same issue. 
-------- Original message --------From: peppoweb <notifications@github.com> Date: 5/10/19  4:42 AM  (GMT-06:00) To: PrestaShop/PrestaShop <PrestaShop@noreply.github.com> Cc: bestbuybargains <admin@bestbuybargins.com>, Mention <mention@noreply.github.com> Subject: Re: [PrestaShop/PrestaShop] Module Catalog Broken - Version 1.7.5.1
  (#13591) I have the same problem into another shop.
When i click on Module Catalog link i see this attached screen.


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PrestaShop/PrestaShop/issues/13591#issuecomment-491228246",
"url": "https://github.com/PrestaShop/PrestaShop/issues/13591#issuecomment-491228246",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khouloudbelguith** [comment] 2019-05-10 11:57
Hi,

I close the issue since I cannot reproduce the issue.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-10 11:57 UTC
Labels: BO, Can't reproduce, Modules catalog, 1.7.5.1
