### ISSUE TITLE
Multishop: product visible in search results in FO

### ISSUE THREAD

**Issue by taniacr** [PrestaShop/PrestaShop#13225] opened 2019-04-05 17:05 UTC
Despite the fact that the product is in a category that shoudn't be visible in a shop, It's presented in search results and, clicking in the breadcrum I can list all products from such category.

1. Activate Multistore and create Shop A and Shop B
2. Create Category in All Shops context
3. Create Product in All Shops context
4. Edit Category and deselect Store A
5. Go to Store A's Front Office.
6. The category is not visible on the faceted search module. Search for the product.
7. In the search result the product is there. In the product's detail page, if a breadcrum is set, the container category is present and clicking it lists all products from it.

PrestaShop version:  1.7.5.1
PHP version: 7.1.27
Cleared caches, regenerated search index.

Note: Not a native english speaker. Please let me know if I don't make myself clear.

**Comment by taniacr** [comment] 2019-04-05 17:24
Tried what's described in the documentation:

> 
Categories: A product can only appear in a given category of a shop if it has been associated with this category in that shop's context. In other words: if shop A and shop B have the C category in common, you can associate the P product to the C category for the A shop's context, and P will not appear in category C on shop B.
> 

Meaning, in Shop A context, removed the association to the category but the product is still visible in the FO.

**Comment by khouloudbelguith** [comment] 2019-04-08 08:38
Hi @taniacr,

Do you have the same problem as in #9940?

Thanks!

**Comment by taniacr** [comment] 2019-04-08 08:55
I'll try to reproduce the problem and let you know.

I realized that duplicating products also generates a few problems with the images. Do you want me to open a new thread about that or I can include in this one?

**Comment by khouloudbelguith** [comment] 2019-04-08 09:04
@taniacr, yes if it's another problem.

**Comment by taniacr** [comment] 2019-04-12 14:53
> 
> 
> Hi @taniacr,
> 
> Do you have the same problem as in #9940?
> 
> Thanks!

Hi @khouloudbelguith ,

Yes, I had the same problem. 
In my Shop A the product is a "product with combinations". When I switch to Shop B, stays as a "Simple Product" and i'm not able to change it.

**Comment by khouloudbelguith** [comment] 2019-04-12 14:56
Hi @taniacr,

Your ticket is a duplicate of #9940
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-12 14:56
Duplicate of #9940

**Closed by khouloudbelguith** 2019-04-12 14:56 UTC
Labels: Categories, FO, Multistore, NMI, Products

**Comment by taniacr** [comment] 2019-04-12 15:03
> 
> 
> Hi @taniacr,
> 
> Your ticket is a duplicate of #9940
> So, I close it.
> Thanks!

My issue is about the product being visible or not in the FO, not with the combinations that I assume it looks like a different problem.
They both happen in Multistore but how are they duplicate?

**Comment by khouloudbelguith** [comment] 2019-04-12 15:32
@taniacr, this issue is currently closed, can you open a new one with more information about your configuration.
Thanks!
