### ISSUE TITLE
Mailalerts not sending new order messages to merchant

### ISSUE THREAD

**Issue by lonoak** [PrestaShop/PrestaShop#34680] opened 2023-11-26 09:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This bug has been reported previously (see bug issue #31854 for instance) but it continues to happen, and even if I try the different workarounds seen so far, I have not been able to solve it yet. Since my environment is a little bit different than in previous bugs, I'm filling in a new issue with the details of my setup. 

I have tried so far:
- resetting it
- uninstalling and reinstalling it back again
- installing the latest tagged version from github: https://github.com/PrestaShop/ps_emailalerts
- resetting it back again
- installing 'es' mail templates

Nothing seems to work so far. If I check the php-fpm logs, I can't see any warnings or errors about what's going wrong.

I'm attaching my configuration.
![ps_emailalerts_mail_translations](https://github.com/PrestaShop/PrestaShop/assets/2891452/70e024ec-4de9-46e2-8355-fad02125a84c)
![ps_emailalets-translations](https://github.com/PrestaShop/PrestaShop/assets/2891452/b623f1df-5302-41d2-84ed-ebbdb9fbcf59)
![ps_emailalerts_config](https://github.com/PrestaShop/PrestaShop/assets/2891452/09ca4105-9094-4e5d-aff6-c2f74d0d8dc6)

I have to add that this shop was a new install, syncing from a previous shop (running 1.7) using the [migration pro](https://addons.prestashop.com/es/migracion-copias-de-seguridad/8934-actualizacion-de-prestashop-y-herramienta-de-migracion.html) addon. But since I have reinstalled ps_emailalerts, and reseted it, I don't think this could be the cause.

Thanks in advance for any help on this!

### Expected behavior

When a new order is triggered, a confirmation email should be sent to the configured merchant address.

### Steps to reproduce

1. Configure the module according to documentation
2. Create a new order.
3. After completing it, emails are sent to the customer but nor to the merchant.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

PHP 8.0.27

### If your bug is related to a module, specify its name and its version

ps_emailalerts v2.4.2

**Comment by lonoak** [comment] 2023-11-26 22:53
I found a solution. A user shared what worked for him in the Prestashop Forum, in [this comment](https://www.prestashop.com/forums/topic/1063538-error-en-el-env%C3%ADo-de-correos-con-el-m%C3%B3dulo-ps_emailalerts/?do=findComment&comment=3440872) (in Spanish). So basically, the solution was to get rid of the `modules/ps_emaialerts` folder in the overrides directory.

How this override appeared is something I don't know. As said, I made a clean install and synced from previous shop, but there was no problem in the previous shop with the module (although it was surely a different version), so I doubt it could be related.

Maybe this could be investigated, as other users might been hit by this bug, but feel free to close the issue.

**Comment by florine2623** [comment] 2023-11-29 09:56
Hello @lonoak ,

I'm closing the issue as you found a solution and I couldn't reproduce the issue.

The merchant email is well sent :
<img width="627" alt="Screenshot 2023-11-29 at 10 55 37" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/743ff0fa-c0a4-46a7-90f9-7c25564bdc6a">

Thanks!

**Closed as completed by florine2623** 2023-11-29 09:56 UTC
Labels: Bug, Invalid
