### ISSUE TITLE
Error "Cannot load country: 0"

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#29275] opened 2022-08-08 10:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
When i try to add a new lang / download lang pack i get this error "Cannot load country: 0"
If i enable debug mode i just get the same error "Cannot load country: 0" no more information.

How can one find the issue from this error code ? 
What does the code mean ?
![debuglang](https://user-images.githubusercontent.com/19774996/183395284-8a92041e-4313-4bb9-99cd-3518129c8ba3.PNG)

### Steps to reproduce

Don't know, it happens on 2 of my stores tho

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by FabienPapet** [comment] 2022-08-08 12:57
Hello, 

The error message is not explicit, but I could find it is related to the `ps_country` table. Can you please check if the country you are trying to add is in this table ? 

If not, can you please provide the country you're trying to add ?

Thank you

**Comment by hibatallahAouadni** [comment] 2022-08-08 16:03
Hello @thbl 

Could you please provide your PHP version :pray: did you check your internet connection?
Waiting for your feedback.

PS: don't forget to answer all @FabienPapet questions :wink: 

Thanks!

**Comment by thbl** [comment] 2022-08-11 11:00
@FabienPapet sorry late reply been out of office, i checked database and the country is not in tabel tried to add USA but get same errror for adding other countries too

**Comment by thbl** [comment] 2022-08-11 11:01
@hibatallahAouadni php 7.4.30

**Comment by thbl** [comment] 2022-08-11 11:08
@FabienPapet in ps_country tabel first country id starts with "1" so there is no country with id "0" could that be a issue ?

**Comment by hibatallahAouadni** [comment] 2022-08-11 16:41
Hello @thbl 

>  in ps_country tabel first country id starts with "1" so there is no country with id "0" could that be a issue ?

No, that's not true, cause the first id in ps_country table is 1.
So, did you check your internet connection? may be it's low! 
> Don't know, it happens on 2 of my stores tho

What do you mean? you only encounter this issue only in 2 shops and the others works perfectly?
Please provide steps to reproduce that can help us to reproduce the issue :pray: 
Otherwise, we can't help you, if we couldn't reproduce the issue :disappointed: 

Thanks!

**Comment by florine2623** [comment] 2022-08-30 08:13
Hello @thbl ,

Since we had no news from you for 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2022-08-30 08:13 UTC
Labels: Bug, BO, International, Localization, Invalid, 1.7.8.7
