### ISSUE TITLE
Menu not work on PS 1.7.6.9 multistore frontend (only work on default store) - just check before close thanks

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#22468] opened 2020-12-17 11:43 UTC
Hi, this is the third time i open these bug report. Please dont close it BEFORE have tested in the exact condition explained above, or close it if you prefer ^^ , iw ill not open another time and bug will stay there !

#### Describe the bug

Menu not work on PS 1.7.6.9 multistore frontend (only work on default store

#### Expected behavior

Menù must be shown on all multistore frontend

#### Steps to Reproduce

Configure a new PS 1.7.6.9 installation with these exactly configuration:

Create a Mulstistore setup in multidomain env (not subfolder)
![image](https://user-images.githubusercontent.com/24798703/102349338-7c25c000-3fa3-11eb-9d9f-4e9020efb329.png)

Check module Menu module position setup
![image](https://user-images.githubusercontent.com/24798703/102349381-8a73dc00-3fa3-11eb-8896-75d1d9d20901.png)

Configure Default store module menu setup:
![image](https://user-images.githubusercontent.com/24798703/102349440-9fe90600-3fa3-11eb-8e27-6741fcb46874.png)

Configure Second store module menu setup:
![image](https://user-images.githubusercontent.com/24798703/102349522-be4f0180-3fa3-11eb-83c1-75e149b801ba.png)

Open frontend store and check for menù

Default store (psmultistore) front end show module menu
![image](https://user-images.githubusercontent.com/24798703/102349561-d1fa6800-3fa3-11eb-85b2-7c89a64da96f.png)

Secondo store front end does not show module menu
![image](https://user-images.githubusercontent.com/24798703/102349582-db83d000-3fa3-11eb-89f2-f45d8d2a2bcf.png)

Cache disabled
![image](https://user-images.githubusercontent.com/24798703/102349604-e3dc0b00-3fa3-11eb-8aa7-4978e00a83aa.png)

PS 1.7.6.9
PHP 7.2

**Comment by florine2623** [comment] 2020-12-18 14:13
Hello @matteolavaggi ,

I can't reproduce your issue using PS 1.7.6.9 and module main menu v2.2.0
![Capture d’écran 2020-12-18 à 15 12 03](https://user-images.githubusercontent.com/16019289/102623842-69e28800-4143-11eb-8f1d-de0d1027d8ac.png)

Make sure this option is checked :
![Capture d’écran 2020-12-18 à 15 07 34](https://user-images.githubusercontent.com/16019289/102623870-7666e080-4143-11eb-941e-51ec6577726b.png)

Also it seems like you are not using classic theme, so the issue might come from a template that is not multistore friendly.

As this issue in not reproducible, I will close it.

**Closed as completed by florine2623** 2020-12-18 14:13 UTC
Labels: No change required

**Comment by matteolavaggi** [comment] 2020-12-18 14:16
Hi, why you write "i'm not using classic theme"? Template is classi theme by prestashop with only minor css adjustement. Have you check the bug in multidomain enviroment? You dont share with me any information in your reply, only the wrong assumption of "not using classi theme".
