### ISSUE TITLE
id_supplier = 0 throws error

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#37304] opened 2024-11-02 11:59 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

For some migrated products it throws an error when wanting to edit. 

The function checking it seems off:
in [src/Core/Domain/Supplier/ValueObject/SupplierId.php ] (line 68)
    private function assertIsIntegerGreaterThanZero(int $supplierId)    {        if (0 >= $supplierId) {            throw new SupplierException(sprintf('Invalid Supplier id: %s', var_export($supplierId, true)));        }    }

Why do is say 0>= $supplierId , this implies that it can't be zero. But a lot don't have a supplier. They are listed in ps_product_supplier with id_supplier = 0 

What is the correct behaviour here? Should products without a supplier not be listed in ps_product_supplier and/or should the function say: 0 > $supplierId or both

### Expected behavior

Accept a supplier id to be zero

### Steps to reproduce

Import a product without a supplier and make sure it is listed in ps_product_supplier as well.

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-11-04 10:51
Hello @sickboards ,

Could you send an example .csv file for the export you did ?

Waiting for your feedback.
Thanks!

**Comment by sickboards** [comment] 2024-11-04 11:08
Hello Florine,

Thank you for your reply, I only don't understand your request.
I imported the products from my live shop (using mySQL)
Some of these products are listed in the table ps_product_supplier with
id_supplier = 0
Editing/opening these products in the backoffice throws an error.

Easy to reproduce, just change the id_supplier to 0 in ps_product_supplier
(in phpMyAdmin) and try to edit it in the BO

As said, I think the issue is in the private function
assertIsIntegerGreaterThanZero
And the fix quite easy

Cheers
Martijn

**Comment by florine2623** [comment] 2024-11-04 11:36
I thought you used the feature in BO > Advanced parameters > Import > Import products ?
![Image](https://github.com/user-attachments/assets/18ce4d9b-14b0-4948-bd95-fc6a3c8ec86e)

I reproduce the issue with PrestaShop version 8.2.0, I'll add this to the backlog so it can be fixed.

https://github.com/user-attachments/assets/05c68e71-8d0c-429c-aeb8-f669671d5ff1


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment] 2024-11-12 14:29
Hello @sickboards ,

As discussed with @ibahloul-ps and @jolelievre , this is not a bug.

If you modify something on the database to trigger this specific error, it is not a bug.
In the BO, everything is done so that error does not occur by using the traditional way of configuring your shop.

I am closing this issue to avoid clogging the backlog.

Thanks!

**Closed as completed by florine2623** 2024-11-12 14:29 UTC
Labels: Bug, Minor, BO, Suppliers, Verified, Products Page, 8.2.x
