### ISSUE TITLE
Number of items is not updated in the cart

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21913] opened 2020-11-13 17:16 UTC
#### Describe the bug
If you're in the cart in FO and remove all items then number of items is not updated in the cart.

#### Expected behavior
The number should be immediately updated to zero if all items are removed from the cart.

#### Steps to Reproduce
1. Go to FO
2. Add one item to the cart
3. Press the button Proceed to checkout
4. Press the icon Delete and remove item from the cart
5. There is not updated number of items to 0 in small cart on right upper corner 

**Screenshots**
![image](https://user-images.githubusercontent.com/33311857/99100418-14fba100-25dc-11eb-80b6-54577c0c7c5c.png)

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32

**Comment by SimonGrn** [comment] 2020-11-13 18:03
Hello,

thank you for your issue. We are aware of this issue. 

I close this one as it's a duplicate.

Thank you.

**Comment by SimonGrn** [comment] 2020-11-13 18:03
Duplicate of #19733

**Closed as completed by SimonGrn** 2020-11-13 18:03 UTC
Labels: Duplicate
