### ISSUE TITLE
Error when selecting a carrier change when the order has been processed by editing the shipping options?

### ISSUE THREAD

**Issue by Luifer-dnk** [PrestaShop/PrestaShop#35035] opened 2024-01-12 09:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When the order has been processed and for some reason it needs to be picked up at the store, the following error is generated in the exchange.

PS 8.1.1
PHP 7.3

I attach a video with the generation of the error.

Thank you.

### Steps to reproduce

https://github.com/PrestaShop/PrestaShop/assets/31345705/74aa8c8f-9d48-402e-91b1-355798509e1f

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

**Comment by paulnoelcholot** [comment] 2024-01-15 13:20
Hello @Luifer-dnk,

I tried to reproduce your issue, but as you can see, I can't : https://www.loom.com/share/71de96e03be945e587eaac171859c7cf?sid=f669b8b8-9629-4ae8-86f3-218647b64bc1

Did I miss something?

Thanks for your feedback!

**Comment by florine2623** [comment] 2024-01-31 09:22
Hello,

Since we had no news from you for, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2024-01-31 09:22 UTC
Labels: Bug, BO, Order, 8.1.x
