### ISSUE TITLE
Bug 'Page content' in Design > Pages on iPad

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#15759] opened 2019-09-30 15:23 UTC
**Describe the bug**
Edition impossible on the content of the page.

**To Reproduce**
1. Go to 'Design'
2. Click on 'Pages'
3. Scroll down to '.Page Content'
4. No toolbar while editing content on iPad (Generation 3), Safari on this case

**Screenshots**
![9560F6C3-DF08-4F82-BE4D-CA0FDE2FCA12](https://user-images.githubusercontent.com/16019289/65892614-e3f3e900-e3a6-11e9-9176-4c5cd209d3fc.jpeg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22

**Comment by khouloudbelguith** [comment] 2019-09-30 15:33
Hi @florine2623,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15272
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-30 15:33
Duplicate of #15272

**Closed as completed by khouloudbelguith** 2019-09-30 15:33 UTC
Labels: Duplicate
