### ISSUE TITLE
Can't save any product when youtube video is embeded in description

### ISSUE THREAD

**Issue by acer1981** [PrestaShop/PrestaShop#16298] opened 2019-11-06 16:45 UTC
Can't save any product when youtube video is embeded in description. Console log - https://prnt.sc/ptc2e3

("Allow iframes on HTML fields" is enabled - https://prnt.sc/ptc41d)

**Comment by khouloudbelguith** [comment] 2019-11-07 07:52
Hi @acer1981,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1e2NvVvhkslLsrvWPesQI3MNeDhaV1fZ-/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by acer1981** [comment] 2019-11-13 16:11
We have found that our PHP is 5.6 version. We will recheck our problem with PHP 7.1 and will write to you.

  
>Четверг, 7 ноября 2019, 10:53 +03:00 от khouloudbelguith <notifications@github.com>:
> 
>Hi  @acer1981 ,
>I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
>I attached a screen record
>https://drive.google.com/file/d/1e2NvVvhkslLsrvWPesQI3MNeDhaV1fZ-/view
>Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
>*  server setup and configuration
>*  PrestaShop version (source)
>*  debug mode report
>*  PHP error logs
>*  apache error log
>Don't you know how to get this information? Please read the following article:
>http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
>Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Евгений Мехтиев

**Comment by khouloudbelguith** [comment] 2019-11-13 16:17
@acer1981, thanks!
Waiting for your feedback.

**Comment by acer1981** [comment] 2019-11-19 16:45
Hello,
 
We have updated our PHP to 7.1 version, but the problem still appears.
 
 
Here is our admin area logins:
 
Link:  https://www.hannu.pro/juvw5lnbhvzkuowu
Login:  vilnius@hannu-pro.com
Password: e19460820
 
Looking forward to hearing from you,
Kind Regards,
Eugene

  
>Среда, 13 ноября 2019, 19:11 +03:00 от Евгений Мехтиев <assasin1981@inbox.ru>:
> 
>We have found that our PHP is 5.6 version. We will recheck our problem with PHP 7.1 and will write to you.
>
> 
>>Четверг, 7 ноября 2019, 10:53 +03:00 от khouloudbelguith < notifications@github.com >:
>>  
>>Hi  @acer1981 ,
>>I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
>>I attached a screen record
>>https://drive.google.com/file/d/1e2NvVvhkslLsrvWPesQI3MNeDhaV1fZ-/view
>>Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
>>*  server setup and configuration
>>*  PrestaShop version (source)
>>*  debug mode report
>>*  PHP error logs
>>*  apache error log
>>Don't you know how to get this information? Please read the following article:
>>http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
>>Thanks!
>>—
>>You are receiving this because you were mentioned.
>>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
> 
> 
>--
>Евгений Мехтиев
>  
 
 
--
Евгений Мехтиев

**Comment by khouloudbelguith** [comment] 2019-11-19 17:11
Hi @acer1981,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by acer1981** [comment] 2019-11-20 16:12
PHP error log is empty.
 
Also I have set PHP back to 7.1 as 7.3 breaks debugger.
  
>Вторник, 19 ноября 2019, 20:11 +03:00 от khouloudbelguith <notifications@github.com>:
> 
>Hi  @acer1981 ,
>We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
>Don't you know how to get this information? Please read the following article:
>http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
>Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Евгений Мехтиев

**Comment by khouloudbelguith** [comment] 2019-11-20 16:16
@acer1981, your log file available in this directory `Project_Folder/var/logs/` is empty?

Thanks!

**Comment by acer1981** [comment] 2019-11-20 16:17
>Среда, 20 ноября 2019, 19:16 +03:00 от khouloudbelguith <notifications@github.com>:
> 
>@acer1981 , your log file available in this directory Project_Folder/var/logs/ is empty?
>Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Евгений Мехтиев

**Comment by acer1981** [comment] 2019-11-20 16:18
Do you mean these two files? I thought you have told about server PHP log file in the root directory.
  
>Среда, 20 ноября 2019, 19:16 +03:00 от khouloudbelguith <notifications@github.com>:
> 
>@acer1981 , your log file available in this directory Project_Folder/var/logs/ is empty?
>Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Евгений Мехтиев

**Comment by khouloudbelguith** [comment] 2019-11-20 16:20
@acer1981, there is no attached screenshot.
You need to sign in to GitHub & upload here your files & your screenshots.

Thanks!

**Comment by acer1981** [comment] 2019-11-20 16:22
Log files

[20190915_exception.log](https://github.com/PrestaShop/PrestaShop/files/3870221/20190915_exception.log)
[dev.log]
(https://github.com/PrestaShop/PrestaShop/files/3870222/dev.log)

**Comment by acer1981** [comment] 2019-11-20 16:22
Done

  
>Среда, 20 ноября 2019, 19:20 +03:00 от khouloudbelguith <notifications@github.com>:
> 
>@acer1981 , there is no attached screenshot.
>You need to sign in to GitHub & upload here your files & your screenshots.
>Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Евгений Мехтиев

**Comment by acer1981** [comment] 2019-11-20 16:32
Also I've uploaded "System requirements tool" to our server - it's available here - https://www.hannu.pro/php-ps-info-master/phppsinfo.php

**Comment by khouloudbelguith** [comment] 2019-11-20 16:33
@acer1981, you changed your version PHP from 7.3 to 7.1 at 2019-11-20 16:03:54, is it?
Since this date, you have only some warnings & notice PHP, there is no error.

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by acer1981** [comment] 2019-11-20 16:36
Yes I did, as I noticed that it breaks PS debugger. Now deleting those folders...give me couple minutes.

**Comment by acer1981** [comment] 2019-11-20 16:38
Done.

**Comment by acer1981** [comment] 2019-11-20 16:39
What's next?

**Comment by khouloudbelguith** [comment] 2019-11-20 16:40
@acer1981, the issue still occurs?

Thanks!

**Comment by acer1981** [comment] 2019-11-20 16:41
Yes.

**Comment by acer1981** [comment] 2019-11-20 16:43
Chrome console error:

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (form.js?1.7.5.2:703)
    at u (main.bundle.js:313)
    at Object.fireWith [as rejectWith] (main.bundle.js:313)
    at i (main.bundle.js:313)
    at XMLHttpRequest.<anonymous> (main.bundle.js:313)

**Comment by khouloudbelguith** [comment] 2019-11-20 16:44
@acer1981, 
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by acer1981** [comment] 2019-11-20 16:48
I know as I'm actually a freelancer :) but it just gives 404 with 404.tpl in response

![Screenshot_2]
(https://user-images.githubusercontent.com/43809060/69259089-5a061680-0bc6-11ea-9f68-a08113e505fd.png)
![Screenshot_3]
(https://user-images.githubusercontent.com/43809060/69259090-5a061680-0bc6-11ea-8496-e64cfc49f4a3.png)

**Comment by acer1981** [comment] 2019-11-20 16:56
As you see with no youtube embed code the response is 200. Once I've embedded it gives 404.

![Screenshot_4]
(https://user-images.githubusercontent.com/43809060/69259778-73f42900-0bc7-11ea-9eab-1495f5dff7b9.png)

**Comment by acer1981** [comment] 2019-11-20 16:58
Also server looks suitable.

![Screenshot_5]
(https://user-images.githubusercontent.com/43809060/69259945-bae21e80-0bc7-11ea-91c8-76dd89ccf770.png)

**Comment by acer1981** [comment] 2019-11-20 17:15
And it seems that it's not youtube, its iframe as I have the same result with any iframe:

Example: <iframe src="https://en.wikipedia.org/wiki/Main_Page" width="640" height="480">

"Allow iframes on HTML fields" is enabled.

![Screenshot_6]
(https://user-images.githubusercontent.com/43809060/69261365-157c7a00-0bca-11ea-9956-cfab7048f1f9.png)

**Comment by khouloudbelguith** [comment] 2019-11-21 11:04
@acer1981, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-21 15:48
@acer1981, I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment] 2019-11-21 15:59
@acer1981, this issue occurs before installing the video tab module?
Because I tried to use this module to add a video => similar issue => redirection to an error page.

Thanks!

**Comment by acer1981** [comment] 2019-11-21 16:03
Just deleted it. the problem still occurs.
  
>Четверг, 21 ноября 2019, 18:59 +03:00 от khouloudbelguith <notifications@github.com>:
> 
>@acer1981 , this issue occurs before installing the video tab module?
>Because I tried to use this module to add a video => similar issue => redirection to an error page.
>Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Евгений Мехтиев

**Comment by khouloudbelguith** [comment] 2019-11-21 16:09
@acer1981, module removed manually & not uninstalled? is it?
Because still, Modules Tab is displaying.
![image](https://user-images.githubusercontent.com/16067358/69355221-b8dc9600-0c81-11ea-98f1-da1a40e3aab1.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-23 08:03
Hi @acer1981,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-23 08:03 UTC
Labels: Bug, BO, No change required, 1.7.5.2
