### ISSUE TITLE
breadcrumb category name update in multistore config

### ISSUE THREAD

**Issue by sgr-fr** [PrestaShop/PrestaShop#27574] opened 2022-02-02 23:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For an instance with 2 shops.
I have some categories with several levels for only the second shop. 2 languages are defined, only 1 is activate.
When I update the root category's name, the breadcrumb of the second shop keep the previous name on pages for sub-category for deep levels.

With a "select * from ps_category_lang" I see 4 lines for one category, 2 lines for the second shop with the updated names, 2 lines for the first shop with the old name.

If I do a manual sql delete on the database for the 2 lines of the first shop, when I refresh the second shop page it's OK the updated name are displayed for the root category on breadcrumb.

It's a test instance I don't know if the root category was available previously for the first shop.

### Expected behavior

Update a category name of the second shop of multishop instance will change the breadcrumb labels.

### Steps to reproduce

1. Go on one product page, product of deep sub-category (at least 3e level)
2. Check the root category name.
3. Update the root category name.
4. Check if the updated name is displayed on product page.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.27

**Comment by sgr-fr** [comment] 2022-02-02 23:40
Perhaps similar issue #20946
edit : or #13468

**Comment by hibatallahAouadni** [comment] 2022-02-03 17:31
Hello @sgr-fr 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of ##13468. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks for the tip :wink: by the way before opening a new issue, you should check if there's a similar one :slightly_smiling_face: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-02-03 17:31
Duplicate of #13468

**Closed as completed by hibatallahAouadni** 2022-02-03 17:31 UTC
Labels: Bug, Duplicate, Invalid

**Comment by sgr-fr** [comment] 2022-02-04 13:57
Thanks I was not sure than the #13468 is exactly the same so I prefered to create a new one... 
Next time I will add a comment on the similar issue.
