### ISSUE TITLE
It is impossible to change the position of blocks in linklist module

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11404] opened 2018-11-15 12:14 UTC
**Describe the bug**
It is impossible to change the position of blocks in linklist module by drag & drop. The new positions of blocks are not saved.

**To Reproduce**
1. Go to Link List Module > Configure
2. Drag & drop blocks
3. Shows successfully updated.
4. After refreshing page changes will reverted.

**Additionnal information**
PrestaShop version: 1.7.4.3

**Comment by khouloudbelguith** [comment] 2018-11-15 13:07
Hi @dineshbadrukhiya,

Here's the PR: https://github.com/PrestaShop/ps_linklist/pull/48 to solve the issue.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9950
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-15 13:08
Duplicate of #9950

**Closed as completed by khouloudbelguith** 2018-11-15 13:07 UTC
Labels: Duplicate
