### ISSUE TITLE
Error when resetting module blockreassurance. 

### ISSUE THREAD

**Issue by tiagondelgado** [PrestaShop/PrestaShop#23442] opened 2021-02-26 19:22 UTC
#### Describe the bug
I cant reset or delete module blockreassurance, when i try reset or unistall, i get this error:

Exception thrown by module blockreassurance on reset. Error when resetting module blockreassurance. The hook id #19 does not exist in database

Why i want remove that? I can add\edit text (left fields)

#### Expected behavior

Delete or reset

#### Steps to Reproduce

1. Go to 'backoffice'
2. Click on 'module'
3. Search 'reassurance'

**Screenshots**
![image](https://user-images.githubusercontent.com/2129617/109345231-bb0ba800-7867-11eb-957e-83793c1db86b.png)
![image](https://i.ibb.co/JdXp9Nq/Screenshot-2021-02-26-at-19-23-15.png)

#### Additional information
* PrestaShop version: 1.7.7.2
* PHP version: 7.3.24

**Comment by hibatallahAouadni** [comment] 2021-03-01 09:14
Hello @tiagondelgado 

I didn't manage to reproduce your issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/18bmz6MusvgoKsLMFZWUe45wmR_njurZA/view

Your error displayed that you have a missing hook, did you override the module?
Please check and feedback.

Thanks!

**Comment by tiagondelgado** [comment] 2021-03-01 11:53
Hello, fix that using: 

- Open the file /ROOT/classes/Hook.php
- find the function "getNameById"
- add "return true;" before the line
$cache_id = 'hook_namebyid_' . $hook_id;

Now, the only problem is missing "Description field" (after reinstall again v5.0.0).

![image](https://user-images.githubusercontent.com/2129617/109493652-b839ce80-7a84-11eb-8529-3a1ae88a8ab3.png)

**Comment by hibatallahAouadni** [comment] 2021-03-01 12:13
Hello @tiagondelgado 

That's odd! I just uninstall and reinstall the module and the description field is well displayed:

![image](https://user-images.githubusercontent.com/23308427/109495505-a7db2100-7a8f-11eb-87cc-97b0039e14f3.png)

> Open the file /ROOT/classes/Hook.php
find the function `getNameById`
add `return true;` before the line `$cache_id = 'hook_namebyid_' . $hook_id;`

Did you undo your changes after installing the module?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-22 08:10
Hello @tiagondelgado ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-22 08:10 UTC
Labels: Bug, BO, Modules, No change required, Blockreassurance, 1.7.7.2
