### ISSUE TITLE
show errors from hookActionProductUpdate

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11126] opened 2018-10-23 11:06 UTC
Hi
how is possible to show/return an error from hookActionProductUpdate of a module?
I've tested
return array('error' => 'some error text');
but not work
with
$this->context->controller->errors[] = $this->l('Some descriptions are not correct');
is the same, nothing is shown in a red popup of the admin product page

in the 1.6.x I used this solution
$this->context->controller->errors[] = $this->l('Some descriptions are not correct');
but now it is not possible

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7

thanks

**Comment by khouloudbelguith** [comment] 2018-10-23 11:50
Hi @maofree,

Did you use it in the __construct() function?
Thanks!

**Comment by Maofree** [comment] 2018-10-23 11:52
no

![1](https://user-images.githubusercontent.com/653230/47358718-e051df80-d6ca-11e8-8f9a-3a38e3bb5780.png)

**Comment by khouloudbelguith** [comment] 2018-10-23 12:00
@maofree, you can use this method: `$this->context->controller->errors[] =Tools::displayError('Somme tiltles') `
You can follow this [link](http://build.prestashop.com/news/new-translation-system-prestashop-17/#calling-symfonys-translator) to get New Translation System For PrestaShop 1.7.

**Comment by Maofree** [comment] 2018-10-23 12:04
hi
tested now
it doesn't work inside hookActionProductUpdate
try to add this hook inside a module

**Comment by khouloudbelguith** [comment] 2018-10-23 13:23
Hi @maofree,

Could you please provide me a module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-23 14:42
@maofree,

I put incorrect title, description & video code, but always the "Settings updated" is displayed.
![image](https://user-images.githubusercontent.com/16067358/47368774-8b21c800-d6e2-11e8-8175-2fe2c59205c5.png)
What kind of data do I need to put to have errors?
Thanks to check & feedback.

**Comment by Maofree** [comment] 2018-10-23 14:48
it is necessary to go in maofreevideo.php in the hookActionProductUpdate section
and add a row at line 814 like this
$this->context->controller->errors[] = $this->l('Some descriptions are not correct');

but you will continue to get positive alert, these errors will not seen

**Comment by khouloudbelguith** [comment] 2018-10-24 16:57
Hi @maofree,

In your module hookActionProductUpdate not working.
I tried with `die();`

```
public function hookActionProductUpdate($params) {
     die();
    }
```

When I update a product => Settings updated is always displayed.
Thanks to check & feedback.

**Comment by Rolige** [comment] 2018-10-24 17:11
Hi @maofree @khouloudbelguith,

I must said that is not possible change the message in the danger/success alert, in this architecture there is no hook or way to do that, in fact, it’s a generic error, you will never see a different message, of course at least you translate it from the translations tab.
There is one way to create a error message in the session and this will be displayed in the next load of the page, which mean you will need to make a page reload/redirect, but this can be handled perfectly in the hook, cons, you will lost the POST info of your fields, but will keep all the rest because this hook is called after that PS finish the save process.


Regards!

**Comment by Maofree** [comment] 2018-10-24 17:34
hi @khouloudbelguith
reflect on it, it is not due from the module, because the problem is limited only on the hookActionProductUpdate. You can remove all code inside it and add just this row to see if it works

file_put_contents(dirname(__FILE__).'/test.txt', 'aaaaaa');

this editor remove the underscore near FILE

then push on the save button and you will get a file inside the module with aaaaaa
the problem is the code inside prestashop's core that no manage the returns

Hi @Rolige
I solved with an ajax solution, but I want to report this bug to use it on other modules

bye

**Comment by khouloudbelguith** [comment] 2018-10-25 08:58
Hi @maofree, @Rolige,

Thanks for your feedback.
Your issue is a duplicate of #9889
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-25 08:58
Duplicate of #9889

**Closed as completed by khouloudbelguith** 2018-10-25 08:58 UTC
Labels: CO, Duplicate

**Comment by 123monsite-regis** [comment] 2019-01-08 16:16
hi @khouloudbelguith ,
sorry according to me issue that you referenced here is not similar,

i use nowadays 
```
throw new PrestaShopException('Invalid field XX');
```
to rely errors from `hookActionProductUpdate` to new Symfony product controller, but it is not really a clean way.

@maofree maybe you found a proper way ?

**Comment by PetarFedorovsky** [comment] 2020-04-29 12:10
I can verify that this:
$this->context->controller->errors[] = $this->l('Some descriptions are not correct');
and
$this->context->controller->informations[] =$this->l('Some descriptions are not correct');(blue info box)
works on PS 1.7.6.2

**Comment by erickjrp** [comment] 2020-05-05 09:06
Impossible to return any error from **hookActionProductSave**. The only way to do it is as @123monsite-regis said:

throw new PrestaShopException('Invalid field XX');

But this:

$this->context->controller->errors[] = $this->l('Some error')

Does not work. 

PrestaShop 1.7.6.5

Is there something I'm missing or there is a bug in the implementation of this hook?

**Comment by gabriserra** [comment] 2021-04-05 17:43
Hi guys, sorry for replying this issue. 

I had the same identical trouble with displaying error messages during `hookActionOrderStatusUpdate`. None of the solutions provided worked for me. @erickjrp neither the `throw new PrestaShopException('Invalid field XX');` because it shown "Unhandled exception" without the customized error message.

I found the only way is to use the right domain Exception. In that case:
`throw new OrderException($this->l("Can't do something...."));`

Using the `l()` is also translation ready.

@khouloudbelguith I honestly think must be documented in some way.
