### ISSUE TITLE
PRoblem when you want to override a class using "use"

### ISSUE THREAD

**Issue by guirou62** [PrestaShop/PrestaShop#20259] opened 2020-07-21 10:04 UTC
#### Describe the bug

When a module wants to override some Prestashop classes function by putting the original function, if the original class have "use ...." at the beginning, the override don't use this "use" : If in the function, you needed to use this class, the shop says "This function doesn't exist"

#### Expected behavior

When you generate an override in folder "overrides", the class should be reconize, maybe add an use when the parent class have it.

#### Steps to Reproduce

1. Create a module with an override of PaymentModule
2. in this override, put the initial function validateOrder
3. Go to your shop after clear the cache to try an order
4. YOu should have an error with updatePhysicalProductQuantity

#### Additional information

* PrestaShop version: 1.7.5
* PHP version: 7.2

**Comment by matks** [comment] 2020-07-21 12:08
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/18592

**Closed as completed** 2020-07-21 12:17 UTC
Labels: Duplicate
