### ISSUE TITLE
Impact price doesn't save when the mode multi-shop is on

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#17698] opened 2020-02-17 15:46 UTC
Hi,

I'm using PS version 1.7.6.0. 
In the BO product page, when I save the impact price for combinations on all shops, the price is not saved. It only works when we select a specific shop but not in all shops mode.

![image](https://i.ibb.co/MZsWnfm/Capture.png)

Does anyone have a solution? 

Thanks,

**Comment by khouloudbelguith** [comment] 2020-02-17 15:52
Hi @Gaja-A,

I did not manage to reproduce the issue with PS1.7.6.0.
https://drive.google.com/file/d/15WN4g-bgOFYCP1yXwi00_IMS7IQhqB46/view
Your ticket is a duplicate of #17669
Please follow #17669. 
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-17 15:52
Duplicate of #17669

**Closed as completed by khouloudbelguith** 2020-02-17 15:52 UTC
Labels: Duplicate
