### ISSUE TITLE
Problem with messages from customer account

### ISSUE THREAD

**Issue by RogerComte** [PrestaShop/PrestaShop#16313] opened 2019-11-07 13:28 UTC
Hi there,

When a customer write a message from the order-detail form, the e-mail alert is sent to the shop's address and not the customer service address (just like the contact form).

If the shop's address is a noreply@xxx.com (in our case), we can't get any alert.

This kind of form should act like the contact form...

PrestaShop version: 1.7.3.3
PHP version: 7.1.3.3

**Comment by khouloudbelguith** [comment] 2019-11-07 14:30
Hi @RogerComte,

>When a customer write a message from the order-detail form

This type of message is sent to your shop address?
![image](https://user-images.githubusercontent.com/16067358/68397404-70968180-0173-11ea-9a3b-2f87a9133eeb.png)


Thanks!

**Comment by RogerComte** [comment] 2019-11-07 20:38
Hi @khouloudbelguith and thank you for your quick answer.
Yes, it's a "message from a customer" and it comes to noreply@xxx.com (the shop address).

**Comment by khouloudbelguith** [comment] 2019-11-08 11:14
@RogerComte, I did not manage to reproduce the issue with ps1.7.6.1.
I attached a screen record.
https://drive.google.com/file/d/1gUT2kHG29gyf4M4uJWkD3K_Vty9MFd3v/view
Thanks to check & feedback

**Comment by RogerComte** [comment] 2019-11-08 12:39
@khouloudbelguith, ok what you show is totally what i need ! 😸
The good and classic way could be to update the PS version but i would prefer to find a solution with this version... or just update the involved files... (?)

**Comment by khouloudbelguith** [comment] 2019-11-08 13:21
@RogerComte, there are a lot of updates added to the latest versions PrestaShop.
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-09 08:16
Hi @RogerComte,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-09 08:16 UTC
Labels: Order messages, Contact, No change required
