### ISSUE TITLE
Translation changes are not saved

### ISSUE THREAD

**Issue by iriarh** [PrestaShop/PrestaShop#16817] opened 2019-12-15 12:03 UTC
After the latest update i cannot do any translation to my theme or default theme..
When i change something and press save i get a message that it is saved/updated but when i refresh the field is empty again...
I have already contacted the theme developer and has confirmed that it is not a theme issue as the same happens with my default translations forntoffice or backoffice
Can this be a file/folder rights issue ? If yes any suggestions where translations are situated ?

Thank you in advance

**Comment by khouloudbelguith** [comment] 2019-12-16 08:08
Hi @iriarh,

Thanks for your report.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source): Prestashop version before upgrade & after upgrade
 - What is the exact version of the 1-click upgrade did you use?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Stone2021** [comment] 2019-12-21 12:21
I have same issue

New clean prestashop 1.7.6.2 install, and warehouse theme also try it with Leo theme and tryed it on 2 different servers, it is same error.

Just go to translate theme and to shop theme actions and translate all and save, and then 2 of them the first 2 go blank. 

I have make this issue to warehouse theme support, they said it is 100% not theme related.

![translateA](https://user-images.githubusercontent.com/59114429/71307726-ec325200-23f2-11ea-96b9-936a6d6f8306.jpg)

**Comment by khouloudbelguith** [comment] 2020-01-21 07:54
Hi @iriarh,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-21 07:54 UTC
Labels: Bug, BO, Translations, No change required
