### ISSUE TITLE
Problem with special letters in invoice

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#26653] opened 2021-11-17 14:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Same letters are not displayed in invoice, but ok in BackOffice

As you can see in pictures below, problem il also present in all EL and RU characters

both addresses and products name (correct screenshots are from BO, bad ones are from invoices)

<img width="508" alt="Schermata 2021-11-17 alle 12 37 17" src="https://user-images.githubusercontent.com/5024055/142217023-7a53656f-1e50-48e0-969d-8085198d1e84.png">
<img width="421" alt="Schermata 2021-11-17 alle 12 37 32" src="https://user-images.githubusercontent.com/5024055/142217030-f6cc9a5b-01ee-4d11-960b-ae7652953259.png">
<img width="885" alt="Schermata 2021-11-17 alle 15 17 27" src="https://user-images.githubusercontent.com/5024055/142217490-14836f92-afdb-478d-ae85-191d0dbb4b93.png">
<img width="853" alt="Schermata 2021-11-17 alle 15 17 21" src="https://user-images.githubusercontent.com/5024055/142217493-e4d1ed65-a5a1-4b97-8503-888aedf52362.png">
<img width="1749" alt="Schermata 2021-11-17 alle 15 17 06" src="https://user-images.githubusercontent.com/5024055/142217496-436987a4-9a90-47d4-9d3c-c518fca3fb93.png">
<img width="338" alt="Schermata 2021-11-17 alle 15 16 52" src="https://user-images.githubusercontent.com/5024055/142217499-c43f2e6a-256d-451d-85b4-e8b7aa80d5e9.png">

### Expected behavior

See correct characters in Invoice

### Steps to reproduce

Generate invoice

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.3.32

**Comment by khouloudbelguith** [comment] 2021-11-17 16:05
Hi @Betafer,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9817
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-11-17 16:05
Duplicate of #9817

**Closed as completed by khouloudbelguith** 2021-11-17 16:05 UTC
Labels: Bug, Duplicate, Invalid

**Comment by Betafer** [comment] 2021-11-17 16:09
I see, #9817 is from 2018, does it take more than 3 years to solve this problem?

**Comment by Hlavtox** [comment] 2021-11-17 16:10
@hibatallahAouadni This is the same problem as I had - https://github.com/PrestaShop/PrestaShop/issues/26233. And the original issue is from 2018 - https://github.com/PrestaShop/PrestaShop/issues/9817. Do you want to tell me that the team knows that it cannot display invoice in any other language than English and nobody fixed it in 3 years????

**Comment by Hlavtox** [comment] 2021-11-17 16:17
Fresh develop installed in english. Resulting invoice on my name:
![Výstřižek](https://user-images.githubusercontent.com/6097524/142238801-080923b4-30c4-4046-9e36-1b3a2313abaa.JPG)

**Comment by Betafer** [comment] 2021-11-17 16:20
> Fresh develop installed in english. Resulting invoice on my name: ![Výstřižek](https://user-images.githubusercontent.com/6097524/142238801-080923b4-30c4-4046-9e36-1b3a2313abaa.JPG)

I don't understand why the prestashop team doesn't group the functions, use 10 different functions to do the same thing, is it difficult to copy the BO function and put it in the invoices?

**Comment by matks** [comment] 2021-11-17 16:31
> I see, #9817 is from 2018, does it take more than 3 years to solve this problem?

Hello it looks like it is important for you that this bug is solved.

If you find that this issue is critical for you, and it's important to have it fixed soon, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

Please do not wait for us to do the work. This is an open source, community project, it works only if every user of the project invests in it (money and/or time). Don't expect us to do everything.

You might wonder: but what have we (we = the maintainer team) been doing for 3 years? Well, we have actually been adding hundred of new features, behaviors, options and obviously we have been fixing hundred of bugs. But we did not fix this one because we considered the other bugs were more important. Thing is: the most important bugs for you and the most important bugs for us are not the same. This is why if you find that this issue is critical for you, then you should _invest_ into having it done.

It reminds me of what Adam Wathan said on Twitter: https://twitter.com/adamwathan/status/1381275398646927362

"One of the most stressful parts of product development (especially open source) is when people are frustrated you haven’t made the improvement they want and automatically attribute it to complacency or ignoring the community instead of just being completely buried in work to do.

If something important takes two years to get worked on, it’s usually because there are two years worth of other fires to put out and work that’s necessary for pure survival. Things taking a long time is more stressful for me than it is for you, I promise. We’re on the same side."

This is exactly the same for us. We're buried in work to do. This is why things take years. And we still have a mountain of things to do so this issue will maybe wait for a few more years if nobody's willing to invest on it.

> I don't understand why the prestashop team doesn't group the functions, use 10 different functions to do the same thing, is it difficult to copy the BO function and put it in the invoices?

The prestashop team does not exist. There's just people who work on it. If you want the software to be improved, grab a seat and come help us make this project better 👍  .

**Comment by Hlavtox** [comment] 2021-11-17 16:34
@Betafer I opened a PR a while that will accidentaly fix this, so go check it out and lets get this done 😄 https://github.com/PrestaShop/PrestaShop/pull/26234
