### ISSUE TITLE
Override removal script breaks when multi-line propertie value is found.

### ISSUE THREAD

**Issue by dreanmer** [PrestaShop/PrestaShop#31901] opened 2023-03-23 17:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

if you try to uninstall any module that override some core class with a properties that value has more than a single line will give an error like this:

`syntax error, unexpected single-quoted string "objectsNodeName", expecting "function" or "const"`

because the script will try to eval a code broken by this script at `Module::removeOverride` method (classes/module/Module.php:3141):
```php
            // Remove properties from override file
            foreach ($module_class->getProperties() as $property) {
                if (!$override_class->hasProperty($property->getName())) {
                    continue;
                }

                // Replace the declaration line by #--remove--#
                foreach ($override_file as $line_number => &$line_content) {
                    if (preg_match('/(public|private|protected)\s+(static\s+)?(\$)?' . $property->getName() . '/i', $line_content)) {
                        if (preg_match('/\* module: (' . $this->name . ')/ism', $override_file[$line_number - 4])) {
                            $override_file[$line_number - 5] = $override_file[$line_number - 4] = $override_file[$line_number - 3] = $override_file[$line_number - 2] = $override_file[$line_number - 1] = '#--remove--#';
                        }
                        $line_content = '#--remove--#';

                        break;
                    }
                }
            }
```

So, if your override is like mine, and has multiline properties (as an array):
```php
<?php

class CustomerAddress extends CustomerAddressCore
{
    /**
     * @var string
     */
    public $number;

    /** @var array Web service parameters */
    protected $webserviceParameters = [
        'objectsNodeName' => 'addresses',
        'fields' => [
            'id_customer' => ['xlink_resource' => 'customers'],
            'id_manufacturer' => ['xlink_resource' => 'manufacturers'],
            'id_supplier' => ['xlink_resource' => 'suppliers'],
            'id_warehouse' => ['xlink_resource' => 'warehouse'],
            'id_country' => ['xlink_resource' => 'countries'],
            'id_state' => ['xlink_resource' => 'states'],
            'number' => [],
        ],
    ];

    public function __construct(
        $id = null,
        $idLang = null
    ) {
        parent::__construct($id, $idLang);
        self::$definition['fields']['number'] = ['type' => self::TYPE_STRING, 'validate' => 'isAddress', 'required' => true, 'size' => 10];
    }
}
```
it will break trying to eval anything like this:
```php
<?php
class CustomerAddress extends CustomerAddressCore
{
    /**
     * @var string
     */
#--remove--##--remove--##--remove--##--remove--##--remove--##--remove--#    
#--remove--##--remove--##--remove--##--remove--##--remove--##--remove--#        'objectsNodeName' => 'addresses',
        'fields' => [
            'id_customer' => ['xlink_resource' => 'customers'],
            'id_manufacturer' => ['xlink_resource' => 'manufacturers'],
            'id_supplier' => ['xlink_resource' => 'suppliers'],
            'id_warehouse' => ['xlink_resource' => 'warehouse'],
            'id_country' => ['xlink_resource' => 'countries'],
            'id_state' => ['xlink_resource' => 'states'],
            'number' => [],
        ],
    ];
#--remove--##--remove--##--remove--##--remove--##--remove--##--remove--##--remove--##--remove--##--remove--##--remove--##--remove--##--remove--#}

```

### Expected behavior

the script should identify that the property dont end in the first line, and should delete lines until a `;` was found at the end of the line.

### Steps to reproduce

1 - install a module that override any class with a multi-line property;
2 - try to uninstall it;

### PrestaShop version(s) where the bug happened

currently using 8.1.0 but it seems to be related to any version.

### PHP version(s) where the bug happened

8.1 but will reproduce in any php version

### If your bug is related to a module, specify its name and its version

no

**Comment by dreanmer** [comment] 2023-03-24 02:16
my temporary fix for this problem was just merge all lines in one, but now my module broke phpstan and phpcs

**Comment by florine2623** [comment] 2023-03-24 09:59
Hello @dreanmer ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by ChillCode** [comment] 2023-03-24 14:27
Hi @florine2623 and @dreanmer 

I think is the same issue:

https://github.com/PrestaShop/PrestaShop/issues/28474

If the class has a constructor (_construct) the other alternative is to populate the array:

```
<?php

class CustomerAddress extends CustomerAddressCore
{
    /**
     * @var string
     */
    public $number;

    /** @var array Web service parameters */
    protected $webserviceParameters;

    public function __construct(
        $id = null,
        $idLang = null
    ) {
        $this->webserviceParameters = [
            'objectsNodeName' => 'addresses',
            'fields' => [
                'id_customer' => ['xlink_resource' => 'customers'],
                'id_manufacturer' => ['xlink_resource' => 'manufacturers'],
                'id_supplier' => ['xlink_resource' => 'suppliers'],
                'id_warehouse' => ['xlink_resource' => 'warehouse'],
                'id_country' => ['xlink_resource' => 'countries'],
                'id_state' => ['xlink_resource' => 'states'],
                'number' => [],
            ],
        ];

        parent::__construct($id, $idLang);
        self::$definition['fields']['number'] = ['type' => self::TYPE_STRING, 'validate' => 'isAddress', 'required' => true, 'size' => 10];
    }
}

```

**Comment by hibatallahAouadni** [comment] 2023-09-01 08:29
Hello @dreanmer 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28474. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks @ChillCode for your reply :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-01 08:29
Duplicate of #28474

**Closed as completed by hibatallahAouadni** 2023-09-01 08:29 UTC
Labels: Bug, CO, Duplicate, Modules, Invalid, 8.1.x
