### ISSUE TITLE
Wrong Image Link generated in Admin -> Product -> Pack of products

### ISSUE THREAD

**Issue by Morpholetto** [PrestaShop/PrestaShop#18983] opened 2020-05-05 13:08 UTC
#### Describe the bug

When adding products to a pack of product, the generated image link is wrong, so you can't see the image correctly. You can see it on the attached screenshot

#### Steps to Reproduce

1. Create a Product Pack
2. Add a product
3. You can see that no images were loaded

**Screenshots**

[https://drive.google.com/file/d/1h_vTB60hYl5IqjP1Z-kg2cn8wHKmGtUS/view?usp=drivesdk](https://drive.google.com/file/d/1h_vTB60hYl5IqjP1Z-kg2cn8wHKmGtUS/view?usp=drivesdk)

#### Additional information

* PrestaShop version: 1.7.6.5 
* PHP version: 7.1

**Comment by TristanLDD** [comment] 2020-05-06 15:35
Hi @Morpholetto, thanks for the report 

Despite our several trials, we could not reproduce your issue with the provided information.
Product images seem to be correctly displayed when creating a product pack on version PS 1.7.6.5:
<img width="1412" alt="Capture d’écran 2020-05-06 à 17 29 38" src="https://user-images.githubusercontent.com/27484094/81196814-d0a19f80-8fbf-11ea-9987-c25317c3757b.png">
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem. 
I'm truly sorry that we can't help you more with that issue. 
Thank you

**Comment by frikiluser** [comment] 2020-05-06 23:31
I've seen that before.
I think it can be reproduced when adding an **article with combinations**.

Hope it helps!

**Comment by hibatallahAouadni** [comment] 2021-01-08 14:41
Hello @Morpholetto 

I didn't manage to reproduce the issue even if I add a product with combination like @frikiluser mentioned above.
See the attached screen record below:

https://drive.google.com/file/d/10ROqUconSs7e2FJsuocy_eXC8rAU7JkJ/view

I close this issue. Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-08 14:41 UTC
Labels: Bug, BO, Pack, No change required, 1.7.6.5
