### ISSUE TITLE
Email address in uppercase - contactform module

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16563] opened 2019-11-27 13:19 UTC
**Describe the bug**
When a customer has an email address in uppercase, the " Send confirmation email to your customers" email doesn't work as expected.

**To Reproduce**

First you must enable PrestaShop to send emails. For example use Gmail SMTP server (connected to your gmail account), configure it from the backoffice in Email page.

1. Go to BO => Module manager page => search the contactform module
2. Enable "Send confirmation email to your customers" & save
3. Go to FO => Contact us
4. Try with an address mail "PRESTOTESTS@OUTLOOK.COM"
5. See email => error

![image](https://user-images.githubusercontent.com/16067358/69725820-5ec74f00-111f-11ea-9157-5c9c67e6afe6.png)

With develop branch (1770, the body of the email is fixed)
![image](https://user-images.githubusercontent.com/16067358/69726147-2e33e500-1120-11ea-848b-7da307175251.png)
Fixed here: https://github.com/PrestaShop/PrestaShop/pull/16550

**Additional information**
PrestaShop version: 1.7.6.1, 1.7.5.2, develop
PHP version: 7.1
contactform v4.1.1

**Comment by matks** [comment] 2020-05-30 20:54
@PrestaShop/prestashop-qa  Hi ! it seems the PR associated to this issue has been merged. So can we close this issue ?

**Comment by Robin-Fischer-PS** [comment] 2020-05-31 20:28
@matks The PR https://github.com/PrestaShop/PrestaShop/pull/16550 fixes only the issue https://github.com/PrestaShop/PrestaShop/issues/13386.

This issue is for another bug, which is not fixed by the PR (according to this comment) : 

https://github.com/PrestaShop/PrestaShop/pull/16550#issuecomment-559074422

Just to be sure, I tested on develop branch, and the bug is still there.

**Comment by florine2623** [comment] 2023-12-27 13:32
The issue is fixed on PS 8.1.x using contactform v4.4.1

<img width="615" alt="Screenshot 2023-12-27 at 14 31 41" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6e5b3f2a-9505-49b6-8655-e3d4e4dfacc9">

**Closed as completed by florine2623** 2023-12-27 13:32 UTC
Labels: Bug, Minor, Email, Fixed, Contactform, 1.7.5.2, Verified, Module
