### ISSUE TITLE
Category bug

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#15881] opened 2019-10-09 12:20 UTC
Your latest release of PrestaShop definitely has a big bug.

When I try to manage my products' category, it return

```Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment] 2019-10-09 12:31
Hi @TomHsiung,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by TomHsiung** [comment] 2019-10-09 12:47
1) Host is an Ubuntu 18.04.3 LTS server, with apache2 be the web server.
2) Sever is setup via your installation script downloaded from your official site, and the version is 1.7.6.1

Currently, I could mange most of the function without issues. But when I try to mange my product categories I get this error.

<img width="1436" alt="Screen Shot 2019-10-09 at 8 46 44 PM" src="https://user-images.githubusercontent.com/6930263/66482620-f0c6ba00-ead5-11e9-9bad-cf8dde61ff64.png">

**Comment by khouloudbelguith** [comment] 2019-10-09 13:06
@TomHsiung, The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by legazpi23** [comment] 2019-10-13 17:46
Creo que tengo el mismo problema. He actualizado de la version 1.7.5.2 a la última versión 1.7.6.1.
Al añadir categoría nueva me surge el siguiente error:
throw new PrestaShopException('Invalid category vars'); en clases/link.php (línea 388)
He podido comprobar que desactivando las urls amigables el error desaparece.
Y que en trafico y seo, de parámetros de la tienda, en la configuración de ruta a las categorías si dejo la configuración, tal como la tenía en la versión 1.7.5.2 : {meta_title:/}{id}-{rewrite}, el error se produce.
tengo que dejarlo tal como sigue para que el error desaparezca: {rewrite}-{id}.
El problema surge ahora con la indexación de las urls en los buscadores.

Un saludo

**Comment by khouloudbelguith** [comment] 2019-10-14 08:57
Hi @legazpi23,

Please, send your request in English.
English is the norm on this bug tracker 
Thank you!

**Comment by legazpi23** [comment] 2019-10-14 09:19
I think I have the same problem. I updated version 1.7.5.2 to the latest version 1.7.6.1.
When adding a new category the following error arises:
"throw new PrestaShopException ('Invalid category vars');" in classes / link.php (line 388)
I have verified that deactivating the friendly urls the error disappears.
And that in traffic and SEO, from store parameters, in the route configuration to the categories if I leave the configuration, as I had in version 1.7.5.2: {meta_title: /} {id} - {rewrite}, the error occurs.
I have to leave it as follows so that the error disappears: {rewrite} - {id}.
The problem now arises with the indexing of urls in search engines.

Greetings.

**Comment by khouloudbelguith** [comment] 2019-10-14 09:41
@legazpi23, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by legazpi23** [comment] 2019-10-15 10:04
I pass you php error images and image of the debug report.
Hope this can help you.
Greetings
![errorcategoria](https://user-images.githubusercontent.com/56402669/66822118-e2e4bf00-ef43-11e9-8eb1-c2b8d7cecab9.jpg)
![errorphp](https://user-images.githubusercontent.com/56402669/66822121-e2e4bf00-ef43-11e9-9cc5-80fa747a1a31.jpg)

**Comment by khouloudbelguith** [comment] 2019-10-15 10:43
@legazpi23, did you use a custom theme?
Could you please provide us the whole exception in a pdf file?

Thanks!

**Comment by legazpi23** [comment] 2019-10-15 18:54
Yes, I use a themeforest template, "Warehouse".
Although I tried the Classic Theme and it gave me the same error.

Attached pdf of the complete exception.

Greetings
[prestashop exception.pdf](https://github.com/PrestaShop/PrestaShop/files/3730972/prestashop.exception.pdf)

**Comment by khouloudbelguith** [comment] 2019-10-16 08:42
@legazpi23, thanks for your feedback.
Did you use the mega menu module?
Thanks to provide me a screenshot about your "Schema of URLs"
![image](https://user-images.githubusercontent.com/16067358/66902844-ae373d00-f001-11e9-828f-298cfba1438d.png)

Thanks!

**Comment by legazpi23** [comment] 2019-10-17 09:40
Yes, using the template megamenu, the classic theme menu and even with the classic theme, without using the template, I get the error described.
attached url structure screens.

Thank you
![estructura url1](https://user-images.githubusercontent.com/56402669/66997541-f4100600-f0d2-11e9-8e51-5b951068b1ee.png)
![estructura url2](https://user-images.githubusercontent.com/56402669/66997542-f4100600-f0d2-11e9-9607-ec0068911a11.png)

**Comment by legazpi23** [comment] 2019-10-17 09:42
With this url structure, in version 1.7.5.2 I had no problems.

**Comment by khouloudbelguith** [comment] 2019-10-17 10:10
Hi @legazpi23,

Thanks for your feedback.
In fact, the category page is migrated to Symfony so the fields are changed with more specific fields.
You need to edit the route of your category to `{category_meta_title:/}{rewrite}-{id}`
![image](https://user-images.githubusercontent.com/16067358/66999861-0d1ab600-f0d7-11e9-8eee-2b10bd8f4ae4.png)
Thanks to check & feedback.

**Comment by legazpi23** [comment] 2019-10-17 11:18
Now he lets me add categories in the back, but in the front he can't find the categories, 404 error

**Comment by khouloudbelguith** [comment] 2019-10-17 11:28
@legazpi23, it is the same behavior with PS1.7.5.2 & PS1.7.6.1
PS1.7.5.2: {meta_tilte:/}{rewrite}-{id}
PS1.7.6.1: {category_meta_title:/}{rewrite}-{id}
Try to create a category with a meta title not empty => redirection to 404, because the redirection is incorrect, you should be careful when editing the shema of URLs

Thanks!

**Comment by legazpi23** [comment] 2019-10-17 11:50
I have created a new category and I still get 404 error on the front, when clicking on it.
As I mentioned earlier, the only option to let me add categories and not get 404 error in the front is with the following structure of url categories: {rewrite} - {id}

**Comment by khouloudbelguith** [comment] 2019-10-17 12:31
@legazpi23, because this the right condition for the categories URLs: `{rewrite}-{id}`.
Your first route is not correct.

Thanks!

**Comment by legazpi23** [comment] 2019-10-21 15:16
Excuse me for being late in answering.
So, in conclusion, for the version of prestashop 1.7.6.1 the only possible structure of the category url would be, as you indicate:
{rewrite} - {id}

Thank you

**Comment by khouloudbelguith** [comment] 2019-10-21 15:18
@TomHsiung, it is the same with PS1.7.5, if you use the inverse structure, it doesn't work correctly.

Thanks!

**Comment by legazpi23** [comment] 2019-10-21 15:34
Okay, we conclude the issue.

Thank you

Greetings

**Comment by khouloudbelguith** [comment] 2019-10-21 15:35
@TomHsiung, you are welcome!
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-21 15:35 UTC
Labels: Bug, BO, Categories, No change required
