### ISSUE TITLE
prestashop_1.7.6.4 fresh install fails when the database password contains percent (%) character

### ISSUE THREAD

**Issue by germain-italic** [PrestaShop/PrestaShop#18345] opened 2020-03-27 15:08 UTC
#### Describe the bug

prestashop_1.7.6.4 fresh install fails when the database password contains percent (%) character although the installation process goes to the end without error.

After inspection, it turns out that the installer will write ` %%` instead of `%` if the database password contains a single `%`, into `app/config/parameters.php` at the` 'database_password'`  key.

#### Expected behavior

The installer should write the password correctly into the configuration file.

#### Steps to Reproduce

1. Download prestashop_1.7.6.4
2. Install it on Linux Debian using PHP7.3-fpm and required extensions
3. Proceed to install wizard
4. Be amazed at the error message from your webserver log: ` Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'db_acdeco_ps17'@'localhost' (using password: YES) in...`

* PrestaShop version: 1.7.6.4
* PHP version: 7.3.16-1+0~20200320.56+debian9~1.gbp370a75
* MySQL version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

**Comment by khouloudbelguith** [comment] 2020-03-27 15:51
Hi @Germain-Italic,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12556
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-27 15:51
Duplicate of #12556

**Closed as completed by khouloudbelguith** 2020-03-27 15:51 UTC
Labels: Duplicate

**Comment by germain-italic** [comment] 2020-03-27 16:10
Sorry, I searched for install and percent but couldn't find #12556
