### ISSUE TITLE
Problem function lastNoneOrderedCart

### ISSUE THREAD

**Issue by BoutiquesInternet** [PrestaShop/PrestaShop#24390] opened 2021-05-07 09:31 UTC
#### Describe the bug

Between version 1.7.6.x and 1.7.7.x, the function lastNoneOrderedCart in classes/Cart.php has changed and it's cause a problem with restaured cart when a customer log in.
When a customer log in, their previous cart is lost.

Even if the value of PS_CART_FOLLOWING is true

#### Expected behavior

We expect to retrieve the last customer cart when log in.

#### Steps to Reproduce

1. create a customer account in FO
2. add a product to the cart
3. log out the customer
4. log in the same customer
5. see that the cart is empty

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

---
Between version 1.7.6.x and 1.7.7.x, the function lastNoneOrderedCart in classes/Cart.php has changed and it's cause a problem with restaured cart when a customer log in.
When a customer log in, their previous cart is lost.

Version 1.7.7.x
`public static function lastNoneOrderedCart($id_customer)
    {
        $sql = 'SELECT c.`id_cart`
                FROM ' . _DB_PREFIX_ . 'cart c
                WHERE NOT EXISTS (SELECT 1 FROM ' . _DB_PREFIX_ . 'orders o WHERE o.`id_cart` = c.`id_cart`
                                    AND o.`id_customer` = ' . (int) $id_customer . ')
                AND c.`id_customer` = ' . (int) $id_customer . '
                AND c.`id_guest` != 0
                    ' . Shop::addSqlRestriction(Shop::SHARE_ORDER, 'c') . '
                ORDER BY c.`date_upd` DESC';

        if (!$id_cart = Db::getInstance()->getValue($sql)) {
            return false;
        }

        return (int) $id_cart;
    }`

Version 1.7.6.x
`public static function lastNoneOrderedCart($id_customer)
    {
        $sql = 'SELECT c.`id_cart`
                FROM ' . _DB_PREFIX_ . 'cart c
                WHERE NOT EXISTS (SELECT 1 FROM ' . _DB_PREFIX_ . 'orders o WHERE o.`id_cart` = c.`id_cart`
                                    AND o.`id_customer` = ' . (int) $id_customer . ')
                AND c.`id_customer` = ' . (int) $id_customer . '
                    ' . Shop::addSqlRestriction(Shop::SHARE_ORDER, 'c') . '
                ORDER BY c.`date_upd` DESC';

        if (!$id_cart = Db::getInstance()->getValue($sql)) {
            return false;
        }

        return (int) $id_cart;
    }`

The portion of code `AND c.`id_guest` != 0` is the problem I think

**Comment by florine2623** [comment] 2021-05-07 09:38
Hello @BoutiquesInternet ,
Could you follow the bug template so we can test out the bug ?
![Capture d’écran 2021-05-07 à 10 17 10](https://user-images.githubusercontent.com/16019289/117430718-ac590580-af28-11eb-9bb7-82af2fefcc4e.png)
Thanks!

**Comment by BoutiquesInternet** [comment] 2021-05-07 09:42
Sorry

#### Describe the bug

Between version 1.7.6.x and 1.7.7.x, the function lastNoneOrderedCart in classes/Cart.php has changed and it's cause a problem with restaured cart when a customer log in.
When a customer log in, their previous cart is lost.

Even if the value of PS_CART_FOLLOWING is true

#### Expected behavior

We expect to retrieve the last customer cart when log in.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. create a customer account in FO
2. add a product to the cart
3. log out the customer
4. log in the same customer
5. see that the cart is empty

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-05-10 01:50
Hello @BoutiquesInternet 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10005. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-10 01:50
Duplicate of #10005

**Closed as completed by hibatallahAouadni** 2021-05-10 01:50 UTC
Labels: Bug, FO, Duplicate, Order, Shopping carts FO, 1.7.7.1
