### ISSUE TITLE
Traffic & SEO falls back to older UI in 1.7.5.0

### ISSUE THREAD

**Issue by hacchus** [PrestaShop/PrestaShop#11924] opened 2018-12-24 15:30 UTC
**Describe the bug**
While trying to edit the "Order" page in Traffic & SEO section. I get the error "Property Meta->url_rewrite is not valid". This is a known error from older versions. After the error though the UI seems to "fall back" on the older style, before 1.7.5.0 version. If I try to delete the page from there I get 405 error of method not found

**To Reproduce**
The shop has 2 languages English and Greek. I'm trying to change the Order page greek name "παραγγελία" for the "Rewritten URL" to English characters ("paraggelia");

1. Go to "Shop Parameters" -> "Traffic & SEO".
2. Click on "Order" page, switch the boxes to Greek language and change the "Rewritten URL" value to anything.
3. Try to save the page and this will give you the error "Property Meta->url_rewrite is not valid", and the page will fall back on the older UI (see image).
4. If I try to delete the page (in order to recreate it) from this older UI I get 405 error (see image).

**Screenshots**
![error](https://user-images.githubusercontent.com/5149317/50402709-331a4700-07a1-11e9-8f1d-16d8c987b64e.png)
![method-not-allowed](https://user-images.githubusercontent.com/5149317/50402723-3a415500-07a1-11e9-977e-957be6403fcb.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-12-24 15:48
Hi @hacchus,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1UsqjDGi8x56fSIv4C70xrFEWLmm4y8Hm/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by hacchus** [comment] 2018-12-24 17:00
It is a fresh installation of 1.7.5.0 on my local machine. I setup Cyprus as country during installation and English, Greek and Turkish languages are installed automatically.

In your screencast when you go to the "Order" page in Greek, the Rewritten URL value is "commande". In a fresh installation with Greek language the value is "παραγγελία". 

The error "Property Meta->url_rewrite is not valid" happens in 1.7.3, 1.7.4 and 1.7.5 Prestashop versions for the pages "Order" and "Sitemap".  In every new Prestashop installation I have to delete these two pages and recreate them in order to be able to modify and save them.

In 1.7.5.0 the same error happens, but it additionally creates the problem of falling back to the older UI.

**Comment by khouloudbelguith** [comment] 2018-12-24 17:08
@hacchus, I tried with another fresh installation PS1.7.5.0 & it is OK.
https://drive.google.com/file/d/1mPIIriA9yuezUjWHtWBJ65TRDcV1TRC6/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by hacchus** [comment] 2018-12-24 17:27
OK sorry I forgot to tell you that I always remove the Turkish language, from "International" -> "Localization" -> Languages.

I tried it again in a new installation without deleting Turkish language first and seems to work OK. If I remove Turkish language and try again, the problem appears.

**Comment by khouloudbelguith** [comment] 2018-12-25 09:58
Hi @hacchus,

Thanks for your feedback.
Very interesting.
I manage to reproduce the issue with PS1.7.5.0.
To reproduce the issue:
- Fresh installation with the Turkish language / France country
- Delete the Turkish language which id_language = 1
- Import the Greece pack
- Go to the BO => Shop Parameters => SEO & Traffic
- Edit the order page
- Switch the boxes to Greek language and change the "Rewritten URL" value to anything.
- Try to save the page and this will give you the error "Property Meta->url_rewrite is not valid", and the page will fall back on the older UI
![image](https://user-images.githubusercontent.com/16067358/50418632-c9477f00-082c-11e9-89d9-50b91908208a.png)
https://drive.google.com/file/d/1pD-bjJQ9wu2ySgVHx7VHqEQ0UiJYQJ9o/view

I tried with other languages during the installation => Nothing happens => OK.
Thanks!

**Comment by hacchus** [comment] 2018-12-26 08:32
Glad you could reproduce it. I checked in the database and there are many remnants of the deleted languages. Shouldn't they all be removed?

I ran an SQL command on the database and the problem gets fixed. This is the command: "DELETE FROM ps_meta_lang WHERE id_lang = 3" (Turkish language Id on my store is 3).

After this it's working properly.

**Comment by marionf** [comment] 2018-12-26 10:24
@khouloudbelguith Do you have the same error message "Property Meta->url_rewrite is not valid" on 1.7.4.4 ?

**Comment by khouloudbelguith** [comment] 2018-12-26 10:31
@marionf, PS1.7.4.4, I tried to save a page with empty Friendly URL, I have this alert
![image](https://user-images.githubusercontent.com/16067358/50443018-b652ae80-0901-11e9-92ae-408eaa7fc892.png)
Thanks!

**Comment by marionf** [comment] 2018-12-26 10:39
Why with empty friendly url ?
What happens if you try the same scenario below ?
- Fresh installation with the Turkish language / France country
- Delete the Turkish language which id_language = 1
- Import the Greece pack
- Go to the BO => Shop Parameters => SEO & Traffic
- Edit the order page
- Switch the boxes to Greek language and change the "Rewritten URL" value to anything.
- Try to save the page

**Comment by marionf** [comment] 2018-12-26 10:43
In fact the error "Property Meta->url_rewrite is not valid" happens with previous versions.

I think the fall back on the older legacy page is a "normal" behavior because the add/edit actions are not yet migrated @matks ?

**Comment by khouloudbelguith** [comment] 2018-12-26 11:02
@marionf, yes the same issue occurs with PS1.7.4.4.
https://drive.google.com/file/d/1JUi35nHOIed5WFpdQKd5UL2VDEzyTMzZ/view
Thanks!

**Comment by colinegin** [comment] 2019-06-07 15:16
Hello @khouloudbelguith do you reproduce this issue now that the page has been migrated ?

**Comment by khouloudbelguith** [comment] 2019-06-11 08:27
Hi @colinegin,

I did not manage to reproduce the issue with PS1.7.6.0beta1 => it is ok.
https://drive.google.com/file/d/1ZPb7mJAgtudqOrSyHR_CfGLT3SuG1JMU/view
I close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-11 08:27 UTC
Labels: Bug, Major, BO, Can't reproduce, International, SEO & URLs, 1.7.5.0
