### ISSUE TITLE
Price returned when doing a search when show price is disabled

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#16843] opened 2019-12-17 16:26 UTC
**Describe the bug**

**To Reproduce**
1. Disable `Show prices` for a customer group
![image](https://user-images.githubusercontent.com/15104724/71014527-5a74cd00-20f2-11ea-8fd2-bba0c19e1077.png)

2. Prices are not displayed in the frontoffice
![image](https://user-images.githubusercontent.com/15104724/71014412-30bba600-20f2-11ea-8e97-b57114394547.png)

3. Make a search and check network. `price` tag is returned.

![image](https://user-images.githubusercontent.com/15104724/71014698-a6277680-20f2-11ea-8e48-e886bd0c128b.png)

![image](https://user-images.githubusercontent.com/15104724/71014483-4630d000-20f2-11ea-8211-31b5494c42e6.png)

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment] 2019-12-17 16:37
Hi @idnovate,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/13354
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-17 16:37
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/13354

**Closed as completed by khouloudbelguith** 2019-12-17 16:37 UTC
Labels: Duplicate
