### ISSUE TITLE
Bug carrier in admin order creation

### ISSUE THREAD

**Issue by azralth** [PrestaShop/PrestaShop#16907] opened 2019-12-23 15:39 UTC
When i try to create order in admin area, sometimes carrier can be choose, and sometime i can't choose any carrier. 

**To Reproduce**
1. Go to admin -> order
2. Click on create order
3. choose customer
4. Add a product
5 .Try to select carrier
![carrier](https://user-images.githubusercontent.com/552339/71366524-7ec52380-25a2-11ea-868a-38d010eaf006.png)

Other bug, sometimes i can get the address (there is no address choice in address area) of customer and sometime the address is correctly show

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-12-23 15:45
Hi @azralth,

If PrestaShop Carriers Are Not Available, you need to check:

1. Carrier Is Inactive: PrestaShop carrier status is the first thing you should consider
Incorrect Zone Assign or Country Disabled: Zone association is among the first things to check if a created carrier does not show for a specific shopper. When configuring PrestaShop carrier you are supposed to assign it to zones, this very carrier can deliver parcels within. If a carrier is not assigned to the zone, customer address belongs to, then it will not show as a delivery method at the checkout.
2. Carrier Is Not Allowed for Customer Group: This detail might easily be skipped, since you can have hundreds and thousands of customers, belonging to various customer groups. If some customer belongs to the group that is not served by the current shipper, it will not be offered as a delivery method for this customer
3. Weight or Price Ranges Are Not Specified: Creating PrestaShop carrier you usually define billing cost for each by one of the criteria: order price or weight. Having selected a suitable method, you need to create ranges and set prices for them. In case ranges are not created, “The product selection cannot be delivered by the available carrier(s). Please amend your cart” message will display at shipping step for a customer.
4. Package Dimensions Are Out of Range: If all above listed settings are configured properly but still PrestaShop carrier does not display at the checkout, you have to compare package dimensions with maximum dimensions PrestaShop carrier can handle. If the package goes beyond these limits, the carrier can’t ship it and, respectively will not display as a delivery method.

Thanks to check & feedback.

**Comment by azralth** [comment] 2019-12-23 15:56
Hi,

Here more information : 

Go to admin -> order
Click on create order
choose customer
Add a product
Update unit price product ---> Then the carrier appear

But normally, the carrier should be appear right after i add product on cart. Not when i update the price ...

**Comment by khouloudbelguith** [comment] 2019-12-23 16:02
@azralth, I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1nUbYSvQjgj9SZJSwQvGxCSaUAWZY6ww5/view
Thanks to check & feedback.

**Comment by azralth** [comment] 2019-12-23 16:06
Ok, this is normal behavior. But in my case, right after had the product, i can't get my carrier appear. I have to update the unit price to get them. I am on 1.7.5.2 prestashop version.

Maybe if i update the shop i get the fix ...

**Comment by khouloudbelguith** [comment] 2019-12-23 16:09
@azralth, it is Ok with PS1.7.5.2 also
https://drive.google.com/file/d/1ESwZwrNGhopg_z1kHzw7sG1XBv77Myvf/view
Thanks!

**Comment by azralth** [comment] 2019-12-23 16:14
Ok so i have something wrong in my shop ...
[https://www.loom.com/share/b96f22549d014b799035cf1e428e0df6](https://www.loom.com/share/b96f22549d014b799035cf1e428e0df6)

**Comment by khouloudbelguith** [comment] 2019-12-23 16:18
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by azralth** [comment] 2019-12-23 16:32
I already get the debug mod enable. I check all query in network and no error. Same with js in console, no error reported.
Here are some information : 
![server](https://user-images.githubusercontent.com/552339/71369103-03677000-25aa-11ea-8c29-38a301f14aee.png)
I think first thing i have to do is update to the latest prestashop version and see if i can fix this problem.

**Comment by khouloudbelguith** [comment] 2019-12-23 16:40
@azralth, As always, you can use the 1-click update v4.10.0 to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-01-22 07:56
Hi @azralth,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-22 07:56 UTC
Labels: Bug, BO, Order, Carriers, No change required, 1.7.5.2
