### ISSUE TITLE
[EPIC] Listing Order Page redesign

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15248] opened 2019-08-23 16:11 UTC
## Features

- [x] #14736 - Right click "open in new tab" over the full width of order table line
- [x] #14741 - Dropdown next to the status of the command to modify it
- [x] #15230 - KPI header redesigned
- [x] #15231 - Client name clickable
- [x] #14732 - Order preview in Order page list

**Comment by colinegin** [comment] 2019-09-02 12:55
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/13890

**Closed as completed** 2019-09-02 12:54 UTC
Labels: BO, Duplicate, Order, Front-end, EPIC
