### ISSUE TITLE
Product price & quantities search field -- Back Office

### ISSUE THREAD

**Issue by diksha-cedcoss** [PrestaShop/PrestaShop#25135] opened 2021-06-26 10:50 UTC
#### Describe the bug

The length of the product's price & quantity's Min & Max button size is too clumsy that placeholder is not even visible

#### Expected behavior

Extend the lengths & make Min & max of price & quantity visible

#### Steps to Reproduce

1. Go to 'Prestashop Backoffice'
2. Click on 'Catalog > Product' Scetion
3. Look at 'Min & Max search fields' of price (tax excl.) & Quantity

**Screenshots**

![catalog_product_product_price_and_quantity_field](https://user-images.githubusercontent.com/40261082/123510650-5b4cce80-d69a-11eb-8bcb-a538c7cde96b.png)

#### Additional information

* PrestaShop version: 1.7.8.0 beta version
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-06-28 13:02
Hello @diksha-cedcoss 

I think what you're asking for is an improvement more than a bug :wink: 
If you could propose a solution (screenshot) it will perfect.

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by diksha-cedcoss** [comment] 2021-07-19 13:12
Hello @hibatallahAouadni 

First of all, Thank you for considering my point.

Actually, it's a bug because it is working in old versions but not in PS version 1.7.8.0 beta version i.e., why I have raised this query

Thank you

**Comment by hibatallahAouadni** [comment] 2021-07-24 08:02
Hello @diksha-cedcoss 

Could you please provide a screenshot of the expected behavior.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-29 08:46
Hello @diksha-cedcoss 

These two columns are so tiny cause the ID column is too large, which reminder me of this issue #24915
I think your Chrome version is v91, is that so?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-08-09 07:27
Hello @diksha-cedcoss 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-09 07:27 UTC
Labels: Bug, BO, No change required, Front-end, 1.7.8.0
