### ISSUE TITLE
dashproducts module 2.1.2 shows null/base category for bestsellers

### ISSUE THREAD

**Issue by lim3ra** [PrestaShop/PrestaShop#31321] opened 2023-02-12 15:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrade to 2.1.2, in dashboard you can see only null/base category name in dashboard. 

You have to downgrade to 2.1.1 to see actual category names again. 

![Screenshot 2023-02-12 155926](https://user-images.githubusercontent.com/26142543/218319730-cde7b129-bf3c-4482-979f-a625e62c9d44.png)

### Expected behavior

You should be able to see all category names as in 2.1.1

### Steps to reproduce

1. Upgrade dashproducts to 2.1.2 
2. Go to dashboard/best sellers
3. In "category" column you can see only "Base" or "null"
4. Uninstall module and install 2.1.1
5. Category names are visible again

### PrestaShop version(s) where the bug happened

1.7.X.X

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

dashproducts 2.1.2

**Comment by hibatallahAouadni** [comment] 2023-02-14 14:49
Hello @lim3ra 

Thanks for reporting the issue!
Indeed after upgrading the module dashproducts from 2.1.1 to 2.1.2 the column Category changed to Null.
See the attached screen record below:

[issue_31310.webm](https://user-images.githubusercontent.com/23308427/218772265-8c983c37-540b-4028-86a8-e74ea18361d4.webm)

It's a regression on module, I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2023-04-21 10:21 UTC
Labels: Bug, Minor, BO, Dashboard, Regression, Dashproducts, Fixed, Verified, Module, 1.7.8.8
