### ISSUE TITLE
Total amout of orders by client multiply by 1 000 000 in dashboard

### ISSUE THREAD

**Issue by Cedricdelcroix** [PrestaShop/PrestaShop#17519] opened 2020-02-05 18:37 UTC
Hello,
The total amount of orders by client is multiply by 1 000 000 in the dashboard.

![image](https://user-images.githubusercontent.com/6152553/73871837-dd8ee580-484e-11ea-9709-4654f9504b7e.png)

**Comment by khouloudbelguith** [comment] 2020-02-06 08:26
Hi @Cedricdelcroix,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Cedricdelcroix** [comment] 2020-02-08 10:33
Informations sur votre serveur Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux 

Version de PHP : 5.6.40 

Version de PrestaShop : 1.7.5.0 

host: 1and1

no php errors 
no apache errors
no javascript errors

**Comment by khouloudbelguith** [comment] 2020-02-10 11:07
@Cedricdelcroix, I did not manage to reproduce the issue with PS1.7.5.0 & PS1.7.6.3.
https://drive.google.com/file/d/1JdJ3yq64UzJIuz-Mc07wYXyLmxynFQ9X/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Cedricdelcroix** [comment] 2020-02-13 21:24
this is console log
![image](https://user-images.githubusercontent.com/6152553/74479304-3691f580-4eaf-11ea-8fd1-054ce5d40b63.png)

php errors : 
![image](https://user-images.githubusercontent.com/6152553/74479465-79ec6400-4eaf-11ea-9eeb-f08aa4553257.png)

acces log :
![image](https://user-images.githubusercontent.com/6152553/74479522-97213280-4eaf-11ea-974e-a61a90794d06.png)

we don't have apache log

**Comment by Cedricdelcroix** [comment] 2020-02-13 21:26
I can't give you more or tell me exactly how to do.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-14 11:25
@Cedricdelcroix, those logs cannot help us to understand what's wrong.
Is this issue occurs only with this customer?

If no, thanks to create from the first (debug mode must be enabled) a new customer & create order & try to change the status of this order.
Then try to provide us the debug mode report & file error log in the folder `/Project_Folder/var/logs/`

Thanks!

**Comment by Cedricdelcroix** [comment] 2020-02-24 23:03
Hello I've something can help.

I have add new order fom the backoffice. 
The price was directly wrong.

dev.log:
[dev.log](https://github.com/PrestaShop/PrestaShop/files/4247268/dev.log)

**Comment by khouloudbelguith** [comment] 2020-02-25 10:58
@Cedricdelcroix, tanks for your feedback.
Unfortunately, in your dev log, there is no error displayed.
Only some PHP info or some warnings related to the translations.

What is the exact payment method did you use during the checkout?
The debug mode is enabled in your case? there is no exception displayed?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-26 08:12
Hi @Cedricdelcroix,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-26 08:12 UTC
Labels: Bug, BO, Order, No change required, 1.7.5.0
