### ISSUE TITLE
Carrier IDs keep on changing

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#17424] opened 2020-01-30 09:35 UTC
Hi,
Why do the Carrier IDs keep on changing all together when modifying anything in one of them?
The problem is that I have a code on the carrier.tpl so in the BO we can see highlighted when a specific carrier is not selected, and I have to edit that code every time the Carriers ID change. Niot a bug, just a weird behavior.
Thanks

**Comment by khouloudbelguith** [comment] 2020-01-30 09:53
Hi @omar2886,

Your ticket is a duplicate of #9592
Please follow: https://github.com/PrestaShop/PrestaShop/issues/9592#issuecomment-533135677
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-30 09:53
Duplicate of #9592

**Closed as completed by khouloudbelguith** 2020-01-30 09:53 UTC
Labels: Duplicate
