### ISSUE TITLE
Re-stock products not working

### ISSUE THREAD

**Issue by alx-web** [PrestaShop/PrestaShop#19787] opened 2020-06-16 11:01 UTC
## Describe the bug

When i click on "Return products" or "Partial refund", i Don't check "Re-stock products", the stock of the product returned doing +1.

The "Re-stock product" checkbox works if the order status is "Delivered"

#### Expected behavior

When i check the box "Re-stock product", the product should doing +1 on the stock.
If i don't check this box the stock of the product should not move.

#### Steps to Reproduce

1/ Doing an order with Check payment or Cb payment (the same), the order will be in "Payment accepted status"
2/ Go on the order and click on Return product or Partial Refund
3/ Check the stock of the product returned. for exemple it could be 5.
4/ Don't check the checkbox "Re-Stock product"
5/ Confirm the return
6/ The product will have a stock of 6 instead of stay at 5

I could do a video if it's not enough clear.

#### Additional information

* PrestaShop version: Tested on 1.7.6 and in 1.6.11 same behaviour

**Comment by sarahdib** [comment] 2020-06-16 16:49
Duplicate of #16869

**Comment by sarahdib** [comment] 2020-06-16 16:50
Hello @alx-web 

Thank you for your feedback 

This is a duplicate of #16869

**Closed as completed by sarahdib** 2020-06-16 16:50 UTC
Labels: Duplicate
