### ISSUE TITLE
Product can't be updated / bad request from stock

### ISSUE THREAD

**Issue by dgtn-va** [PrestaShop/PrestaShop#12287] opened 2019-01-24 11:50 UTC
Products items and stocks no longer updatable since migration to OVH.
After Save, just can't update product (any value), or "bad request" when try to change a value from Stocks.

![From Products](https://i.imgur.com/r5PbjhP.jpg)
![From Stocks](https://i.imgur.com/U3pYzAs.jpg)

In debug mode: nothing
In dev log: nothing
In prod log: nothing
In Symfony profiler: nothing, except this (but provide no more information):
![Symfony profiler from Products](https://i.imgur.com/MLDMXT6.jpg)
![Symfony profiler from Stocks](https://i.imgur.com/GESBcD6.jpg)

To reproduce: migrate installation from yulpa.io (works properly) to ovh.com (not works properly now)...
I checked all FTP rights/permissions and DB has exported according to this parameters:

![Export parameters (part 1)](https://i.imgur.com/4bkumUT.jpg)
![Export parameters (part 2)](https://i.imgur.com/GikFmKG.jpg)
![Export parameters (part 3)](https://i.imgur.com/KfiXs7m.jpg)

And with Quick method too.

PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-01-24 11:59
Hi @fujitsuDev,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-25 07:36
Hi @fujitsuDev,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-02-25 07:36 UTC
Labels: Bug, BO, No change required
