### ISSUE TITLE
actionCartUpdateQuantityBefore

### ISSUE THREAD

**Issue by margud** [PrestaShop/PrestaShop#17888] opened 2020-02-28 13:41 UTC
**Describe the bug**
Using 1.7.6.3 PS i found out one issue with actionCartUpdateQuantityBefore hook.
In ps_hook_alias we can see that alias is actionBeforeCartUpdateQty and name is actionCartUpdateQuantityBefore. Looks all good but in ps_hook instead of using name and title as actionCartUpdateQuantityBefore there is only actionbeforecartupdateqty.
Because of this only actionbeforecartupdateqty hook works and actionCartUpdateQuantityBefore doesn't.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-02-28 13:58
Hi @margud,

Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/13518?

Thanks!

**Comment by margud** [comment] 2020-02-28 14:34
Yes it is.

**Comment by khouloudbelguith** [comment] 2020-02-28 15:36
@margud,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12578 to fix the issue.
Your ticket is a duplicate of #13518
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-02-28 15:36
Duplicate of #13518

**Closed as completed by khouloudbelguith** 2020-02-28 15:36 UTC
Labels: Bug, CO, Duplicate, 1.7.6.3
