### ISSUE TITLE
Export customer in admin - error email

### ISSUE THREAD

**Issue by ethercreation** [PrestaShop/PrestaShop#20621] opened 2020-08-18 10:02 UTC
#### Describe the bug

In the customer administration page, during the proposed export, it is the first name that arrives in the email box.

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

**Comment by ethercreation** [comment] 2020-08-18 10:04
Correction in  src/prestashopBundle/Controller/admin/sell/customer/customerController.php Line 662 replace firstname by email

**Comment by khouloudbelguith** [comment] 2020-08-18 11:13
Hi @ethercreation,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15880 to fix the issue.
Your ticket is a duplicate of #15875
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-18 11:13
Duplicate of #15875

**Closed as completed by khouloudbelguith** 2020-08-18 11:13 UTC
Labels: Duplicate
