### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by JoBICHE** [PrestaShop/PrestaShop#29879] opened 2022-10-05 11:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Issue displaying activity preview settings on dashboard on resolution width range 1200 to 1750 pixels.

<img width="304" alt="Screenshot 2022-10-05 at 13 37 33" src="https://user-images.githubusercontent.com/43602697/194052480-857d8881-98d8-426b-877b-2a27b09eeb40.png">

<img width="565" alt="Screenshot 2022-10-05 at 13 38 07" src="https://user-images.githubusercontent.com/43602697/194052539-dc2c784c-a39c-4905-a739-026f5944c82f.png">

### Expected behavior

Elements should not overlap.
Possible by adding a display: flex and a flex-direction: column on the form-group class and adding width: 100% and text-align: center on the control-label class.

<img width="823" alt="Screenshot 2022-10-05 at 13 46 03" src="https://user-images.githubusercontent.com/43602697/194053589-ab4b1e78-0bdb-4369-bffb-f5989caa914a.png">

<img width="801" alt="Screenshot 2022-10-05 at 13 46 16" src="https://user-images.githubusercontent.com/43602697/194053595-f6a01a0b-e309-4b1d-8dcc-919a626053e9.png">

### Steps to reproduce

1. Go to the back office.
2. Go to the dashboard.
3. On the ACTIVITY OVERVIEW block, click on the settings button
<img width="270" alt="Screenshot 2022-10-05 at 13 52 24" src="https://user-images.githubusercontent.com/43602697/194054149-44244024-4e62-457a-9990-c04e6d96f5f7.png">
4. Adjust the resolution to have a width between 1200 and 1750 pixels.

### PrestaShop version(s) where the bug happened

1.7.7.8 and 8.0

### PHP version(s) where the bug happened

7.3.1 and 7.4.30

**Comment by NeOMakinG** [comment] 2022-10-05 14:18
@JoBICHE do you want to try to contribute to fix it?

**Comment by JoBICHE** [comment] 2022-10-05 15:28
Yes, with pleasure !

**Comment by hibatallahAouadni** [comment] 2022-10-05 16:49
Hello @JoBICHE 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27602. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-10-05 16:49
Duplicate of #27602

**Closed as completed by hibatallahAouadni** 2022-10-05 16:49 UTC
Labels: Bug, Duplicate, Invalid
