### ISSUE TITLE
Admin keep send me to login

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#13720] opened 2019-05-09 06:20 UTC
Hello
I installed the new version on my website but I can't use it 

the assistant spinner keep loadin and if i click on later it send me to login page
i removed then reinstalled it again but same error

Regards

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-05-09 07:51
Hi @go-sudo,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ToyPerson** [comment] 2019-05-21 23:30
I'm experiencing the same issue. https://github.com/PrestaShop/PrestaShop/issues/13908

If anyone can provide a solution to this, please do so.

**Comment by khouloudbelguith** [comment] 2019-05-22 07:37
Hi @go-sudo, @ToyPerson,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by ToyPerson** [comment] 2019-05-22 23:30
Hi @khouloudbelguith

The thing is, I don't have access to the PHP. I experience the error from the point of view of a user.

**Comment by khouloudbelguith** [comment] 2019-05-23 08:35
@go-sudo, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by Adekonl** [comment] 2019-06-05 10:30
hi @go-sudo and @ToyPerson, are you both using google Chrome? 
It seems i have some issues with the token, regularly forcing me to the login page just seconds after login. These issues mostly occur on the most popular backend pages.

Also, when logging in, it is not redirecting me to the dashboard until i change the 'controller' in the url. When debugging i found that Chrome is taking the request url from the disk-cache, with the incorrect token (probably from earlier). 

@khouloudbelguith, i've made some screenshots, unfortunately how to accurately recreate this issue, it just occured and doesn't go away. This happends when i click 'Login':
![image](https://user-images.githubusercontent.com/20944577/58949655-3cb2cc80-878d-11e9-8552-e092e792f413.png)
And the second request (Notice the token is different):
![image](https://user-images.githubusercontent.com/20944577/58949744-6d930180-878d-11e9-8c03-d50f53a28273.png)

Hope this helps!

PHP7.3
Google chrome: Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by Adekonl** [comment] 2019-06-05 10:33
hi @go-sudo and @ToyPerson, are you both using google Chrome? 
It seems i have some issues with the token, regularly forcing me to the login page just seconds after login. These issues mostly occur on the most popular backend pages.

Also, when logging in, it is not redirecting me to the dashboard until i change the 'controller' in the url. When debugging i found that Chrome is taking the request url from the disk-cache, with the incorrect token (probably from earlier). 

@khouloudbelguith, i've made some screenshots, unfortunately cannot tell how to accurately recreate this issue, it just occured and doesn't go away. This happens when i click 'Login':
![image](https://user-images.githubusercontent.com/20944577/58949971-f7db6580-878d-11e9-87a3-98212def613a.png)
And the second request (Notice the token is different):
![image](https://user-images.githubusercontent.com/20944577/58949914-dbd7c400-878d-11e9-83f0-312bdf608dee.png)


Hope this helps!

PHP7.3
Google chrome: Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by ToyPerson** [comment] 2019-06-05 23:27
@Adekonl 

The issue exists across all browsers: Edge, IE, Firefox, Safari, Opera - I've tested them all.

The best way to solve this problem is to whitelist your working PC's IP address. This is how we are able to make it work. Make sure, though, that your IP address is static.

**Comment by go-sudo** [comment] 2019-06-06 00:25
Hi
For me the issue is resolved , it was a problem with DNS , my website wasnt lined to my IPv4 Adress 

Regards

**Comment by khouloudbelguith** [comment] 2019-06-11 14:36
Hi @go-sudo,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-11 14:36 UTC
Labels: Bug, BO, No change required
