### ISSUE TITLE
Major - Combination, price impact and price unit

### ISSUE THREAD

**Issue by hanuchin** [PrestaShop/PrestaShop#12453] opened 2019-02-06 11:03 UTC
**Describe the bug**
It is not possible, to insert the right impact price on unit for a shop owner.
To use the price unit display, it is necessary to define a product price, the unit and the price for the unit.

At the combinations, its possible, to set the impact on price, and get a right value. 
At the impact on price unit, its not possible, because there are some calculations, which no shop user can except. So its not possible to enter a right value.

**To Reproduce**
Create a product with 2 combinations.
Product: Price 5, unit price 2.5
Add Combination 1: no impact, because it is the default price.
Add Combination 2: Medium, contains 5 pieces: cost 10 euro, unit price would be 2 euro.
-> Impact on price 5 (thats okay)
-> Impact on unit -0.5 -> its a wrong calculated unit price: 4.5 (what PrestaShop does) vs 2 (Should be the price unit)

PrestaShop calculates a factor between the default price and price unit and its using this factor, to initialy calculate the price for the "medium" product. But the shop user cannot see this value, whats the base price on a combination to enter the correct "Impact on price unit".

We installed a pure basic PrestaShop 1.7.5
http://shop-v1-7-5.medani.at/en/home/1-2-test-product-combination.html
Change the size and you will see, that the price unit is not correct and its not easy possible for the shop user to set the correct price impact. It would be necessary to calculate all prices via for example excel, to manage it. But that is not how PrestaShop should work.

We have to display unit prices and for some shop owners it is a real pain, to get the right price unit.

BackOffice: http://shop-v1-7-5.medani.at/medani/
demo@demo.com / demodemo

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.x

**Comment by khouloudbelguith** [comment] 2019-02-06 11:46
Hi @hanuchin,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9901
So, I close it.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-06 11:46
Duplicate of #9901

**Closed as completed by khouloudbelguith** 2019-02-06 11:46 UTC
Labels: Duplicate
