### ISSUE TITLE
Issue Pagination

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#12692] opened 2019-02-24 15:01 UTC
**Describe the bug**
Hello
The paggination is not working on my 3 websites
when i click on next page i get this error on console 
with or without friendly url

on server side i get this apache error 
mod_fcgid: stderr: #4 /var/www/vhosts/playstore.ma/httpdocs/controllers/front/ in /var/www/vhosts/playstore.ma/httpdocs/src/Adapter/Presenter/AbstractLazyArray.php on line 370, referer: https://playstore.ma/227-jeux-video
```
GET https://playstore.ma/227-jeux-video?page=2&from-xhr 500
  | send | @ | core.js:39
-- | -- | -- | --
  | ajax | @ | core.js:39
  | m.(anonymous function) | @ | core.js:39
  | (anonymous) | @ | core.js:185
  | (anonymous) | @ | core.js:185
  | i.emit | @ | theme.js:1
  | (anonymous) | @ | theme.js:1
  | dispatch | @ | core.js:39
  | g.handle | @ | core.js:3

```

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: Plesk php 7.2.15 
Informations sur votre serveur Linux #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.2.15

Limite de mémoire : 6056M

Temps maximal d'exécution : 3000

Taille max. pour envoi de fichiers : 70M

**Comment by khouloudbelguith** [comment] 2019-02-25 09:04
Hi @go-sudo,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/16YZoCGf1MFAVOVOUR41CjQPQ7412kBQp/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by go-sudo** [comment] 2019-02-25 22:22
Hello

I appreciate your help and I provide you this video to explain more the issue 

https://drive.google.com/file/d/1AlG9Sm1QzWXXI494G6sCNUjjyzEK73Mg/view

Regards,

**Comment by khouloudbelguith** [comment] 2019-02-26 07:37
@go-sudo, you need to enable debug mode in your store and debug request which is sent for pagination in your browser, using DevTools, so:

1. enable debug mode
2. go to the page
3. open up developer tools
4. go to Network tab
5. Click on the pagination button
6. wait for an error, you should see red request information in Network tab ( error 500 in your screen record => click on it)
7. click on it, you should see the error message in "Preview" tab

Thanks!

**Comment by go-sudo** [comment] 2019-02-26 21:18
Hello
when i enable the debug mode the website display many errors 

https://drive.google.com/file/d/1pK-xOtmVAq8e8BdU-O3IE4KG8zFEH1bF/view

**Comment by khouloudbelguith** [comment] 2019-02-27 09:56
Hi @go-sudo,

Thanks for your feedback.
What is the exact version of the ps_legalcompilance did you use?
This module is overridden by your theme?
Could you please provide me the exact configuration for this module?
Thanks!

**Comment by go-sudo** [comment] 2019-02-27 22:25
Hi @khouloudbelguith 

the version is v3.0.1 I don't know how to export the configuration 

https://drive.google.com/file/d/1j4H3D6nKVT3-T0ElgeKRX0seH9unu7Wp/view

**Comment by khouloudbelguith** [comment] 2019-02-28 08:23
Hi @go-sudo,

Thanks for your feedback.
I tried with PS1.7.5.1 & the ps_legalcompilance module v3.0.1, but I did not manage to reproduce your issue.
Could you please check if your theme overrides the ps_legalcompilance or not.
You can check in your `Projet_folder/themes/your_theme/modules/ps_legalcompliance/views/templates/hook/hookDisplayFooter.tpl`
Thanks!

**Comment by go-sudo** [comment] 2019-02-28 23:14
Hi @khouloudbelguith 

we have this issue with also the default theme and here is the code of the file you ask for if you want login access please reach me on my email anami[at]playstore.ma

```
{* ----------------------------------------
 * PRESTASHOP THEME CREACOMPUTER
 * Copyright (c) Prestacrea
 * License See theme PDF documentation
 * ---------------------------------------- *}

<div class="block-links footer-block col-md-4 my-md-3 mx-3">

  <p class="h3 hidden-sm-down">{l s='Information' d='Shop.CreathemeModules'}</p>

  <div class="title clearfix hidden-md-up" data-target="#footer_eu_about_us_list" data-toggle="collapse">
    <span class="h3">{l s='Information' d='Shop.CreathemeModules'}</span>
    <span class="float-right">
      <span class="navbar-toggler collapse-icons">
        <i class="icon-arrow-drop-down add" aria-hidden="true"></i>
        <i class="icon-arrow-drop-up remove" aria-hidden="true"></i>
      </span>
    </span>
  </div>

  <ul id="footer_eu_about_us_list" class="list-unstyled list-arrows collapse">
    {foreach from=$cms_links item=cms_link}
      <li><a href="{$cms_link.link}" id="{$cms_link.id}" class="cms-page-link">{$cms_link.title}</a></li>
    {/foreach}
  </ul>

</div>

```

**Comment by khouloudbelguith** [comment] 2019-03-01 08:19
Hi @go-sudo,

Could you please try to uninstall the ps_legalcompilance with removing the folder & then try to install it again.
Thanks to check & feedback.

**Comment by go-sudo** [comment] 2019-03-03 01:15
Hi @khouloudbelguith 

I did uninstall the module and nothing change the issue still here,

https://www.youtube.com/watch?v=blsgVuT31Gs

**Comment by khouloudbelguith** [comment] 2019-03-04 14:41
@go-sudo, to be sure is not a module issue, if you try to disable the ps_legalcompilance module temporarily, the issue occurs again?
Thanks!

**Comment by go-sudo** [comment] 2019-03-04 16:56
Hi
The module is not enable and i did uninstall it and remove it from ftp
Yes the issue occurs.

**Comment by khouloudbelguith** [comment] 2019-03-04 17:01
@go-sudo, so the module is not the problem, you can install it again.
Have you tried to contact the theme author about this issue?
Because this issue is fixed in the PS1.7.5.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/9214/
Thanks!

**Comment by go-sudo** [comment] 2019-03-04 18:27
Hi
Tje issue occurs with the default theme also so I think it's matter of JS files. 
I will try this evening your link.
Regards

**Comment by khouloudbelguith** [comment] 2019-03-05 08:04
@go-sudo, We need to retrieve again the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by go-sudo** [comment] 2019-03-06 21:57
Hello @khouloudbelguith 

The module is already uninstall and here is the test and server details

https://drive.google.com/file/d/1DUMT5yDcDJ6yzWyUOgCI0Lxh50M7iwGY/view

Error with Apache 

> mod_fcgid: stderr: PHP Fatal error: Uncaught RuntimeException: Trying to unset the index id of the LazyArray PrestaShop\\PrestaShop\\Adapter\\Presenter\\Product\\ProductListingLazyArray already defined by a method is not allowed in /var/www/vhosts/playstore.ma/httpdocs/src/Adapter/Presenter/AbstractLazyArray.php:370, referer: https://playstore.ma/227-jeux-video	

	`
With NGNX
	

> AH01071: Got error 'PHP message: PHP Fatal error: Uncaught RuntimeException: Trying to unset the index id of the LazyArray PrestaShop\\PrestaShop\\Adapter\\Presenter\\Product\\ProductListingLazyArray already defined by a method is not allowed in /var/www/vhosts/playstore.ma/httpdocs/src/Adapter/Presenter/AbstractLazyArray.php:370\nStack trace:\n#0 /var/www/vhosts/playstore.ma/httpdocs/override/classes/controller/ProductListingFrontController.php(25): PrestaShop\\PrestaShop\\Adapter\\Presenter\\AbstractLazyArray->offsetUnset('id')\n#1 /var/www/vhosts/playstore.ma/httpdocs/classes/controller/ProductListingFrontController.php(506): ProductListingFrontController->prepareProductArrayForAjaxReturn(Array)\n#2 /var/www/vhosts/playstore.ma/httpdocs/controllers/front/listing/CategoryController.php(159): ProductListingFrontControllerCore->getAjaxProductSearchVariables()\n#3 /var/www/vhosts/playstore.ma/httpdocs/classes/controller/ProductListingFrontController.php(541): CategoryControllerCore->getAjaxProductSearchVariables()\n#4 /var/www/vhosts/plays...\n', referer: https://playstore.ma/227-jeux-video		
	

PHP INFO https://playstore.ma/phpinfo.php
PhpPsInfo https://playstore.ma/phpps.php 
Login: prestashop
Password: prestashop

Regards

**Comment by khouloudbelguith** [comment] 2019-03-07 09:46
@go-sudo, thanks for your feedback.
Issue found.

>/var/www/vhosts/playstore.ma/httpdocs/override/classes/controller/ProductListingFrontController.php(25): 

You have an override "ProductListingFrontController" which causing this issue.

You need to found this override is added with which module & check the module author about the issue or if it is a custom development you need to edit it because it causes a problem.
Your issue is not a PrestaShop's core bug but a customization problem, so I close the issue, feel free to open a new one when needed.
THanks!

**Closed as completed by khouloudbelguith** 2019-03-07 09:46 UTC
Labels: Bug, FO, Can't reproduce, Traffic & SEO, 1.7.5.1
