### ISSUE TITLE
"php composer.phar install" errors

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#18620] opened 2020-04-14 14:31 UTC
Hi

I wish to to install the dev version of Prestashop on my locahost, I am asked to run the command "php composer.phar install" to proceed with the install, so when I do, I get the following error:

--------------------
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - composer/installers is locked to version v1.7.0 and an update of this package was not requested.
    - composer/installers v1.7.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.

Use the option --with-all-dependencies to allow updates and removals for packages currently locked to specific versions.
You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-reqs, but this will also ignore your PHP version and may result in bigger problems down the line.
____________________________________

I am running the latest version of composer on Windows 10.

Kind Regards
Musaffar

**Comment by matks** [comment] 2020-04-14 15:52
@musaffar-patel it seems you are trying to install PrestaShop with Composer 2 which has been released very recently and ... it seems it's not possible 😅we might have some work to do to make it happen

If you use Composer 1 it should work.

@PrestaShop/prestashop-core-developers looks like we may not be compatible with Composer 2

**Comment by jolelievre** [comment] 2020-04-14 16:00
@PierreRambaud isn't it related to the problem you fixed on nightly build?
It was because of composer v2 dev no?

**Comment by musaffar-patel** [comment] 2020-04-14 16:38
Hi

Which version of composer should I be using?  My installed version is 1.10.5, should it work with this version?

**Comment by PierreRambaud** [comment] 2020-04-15 07:20
> @musaffar-patel it seems you are trying to install PrestaShop with Composer 2 which has been released very recently and ... it seems it's not possible we might have some work to do to make it happen
> 
> If you use Composer 1 it should work.
> 
> @PrestaShop/prestashop-core-developers looks like we may not be compatible with Composer 2

The version 2 isn't release yet, it's only a dev dependency
![image](https://user-images.githubusercontent.com/1462701/79309237-4010fb80-7efa-11ea-9c10-381d5e5df574.png)

I reproduce the problem with this dev version:
![image](https://user-images.githubusercontent.com/1462701/79309255-48693680-7efa-11ea-9a4f-302b5d5d8a4c.png)


Since it's a dev version we must wait a little more before updating our dependencies to make it compatible with composer 2.

**Comment by musaffar-patel** [comment] 2020-04-15 09:14
Hi

I'm not sure why the error states I am using COmposer 2.0 because I installed 1.10.5 and running compose diagnose also shows version 1.10.5.

Is there anything I can do in the mean time to install?

**Comment by PierreRambaud** [comment] 2020-04-16 08:47
Could you show us a screenshot with your composer version and then your composer install command please?

**Comment by musaffar-patel** [comment] 2020-04-17 10:14
Hi

Sure, attached is a screen shot of the output of composer diagnose command displaying the version as 1.10.5
![screenshot](https://user-images.githubusercontent.com/44204668/79558727-8900b580-809c-11ea-87de-1c5acb66c226.jpg)

**Comment by PierreRambaud** [comment] 2020-04-17 11:48
Could you do the same with the `composer install` command please?

**Comment by florine2623** [comment] 2020-05-18 10:17
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-05-18 10:17 UTC
Labels: Bug, No change required
