### ISSUE TITLE
Contact form not working correct with Chrome / GDPR module

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#24290] opened 2021-04-30 16:04 UTC
I notice after migrating to 1.7.7.3 from 1.7.6.5 that the contact form no longer works correct with Chrome.

It's not possible to send messages, simple because the GDPR check option does not appear.  When trying this in Chrome incognito, it does show and also when I try in Safari.

I cleared my browser history and removed all cache files. 

#### Expected behavior

To work with Chrome

#### Steps to Reproduce

Install 1.7.7.3, install GDRP module

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

**Comment by matks** [comment] 2021-04-30 20:25
Hello @01park if it works with Chrome Incognito mode, it is very likely there is no issue with GDPR module and Chrome.

Can you try from another device (another computer or a smartphone) and Chrome to confirm? I think something related to your session might create the issue.

**Comment by 01park** [comment] 2021-05-01 09:47
Hi,

Yes on my smartphone it is working. Just on my Mac its not.

**Comment by matks** [comment] 2021-05-01 20:49
@01park I think some people reported the issue that

1. They login to BO with a browser
2. They perform an upgrade
3. After upgrade they cannot do some things on FO with the browser used before to login in the BO

So this would indicate something inside the Cookie profile of the BO user can wrongly fails the some FO logic. (after an upgrade)

However this is very vague 🤷

**Comment by 01park** [comment] 2021-05-02 21:27
Is there anyway to delete these cookings or where are they stored?

**Comment by matks** [comment] 2021-05-03 08:17
@01park Yes, you can follow Chrome doc to clear the cookies
https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

I close the issue as it seems it's not a bug report 😉

**Closed as completed by matks** 2021-05-03 08:17 UTC
Labels: No change required
