### ISSUE TITLE
1.7.6.3 adding a .htaccess file to the vendor directory in module which prevents loading of libraries

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#17827] opened 2020-02-25 15:50 UTC
**Describe the bug**
When you install a module that contains a vendor directory, for third-party libraries, Prestashop is adding a .htaccess file that blocks access to the directory.  This is breaking the module for all customers.

**To Reproduce**
1. Check in attached module archive, only the index.php in the vendor directory
2. Install the module in 1.7.6.3
3. Check in the module vendor directory, you should see an htaccess file.
4. The permissions of this .htaccess file result in 403 errors for any requests to load a library from this directory.

NB.  The module isn't using any of the libraries in this directory, it's just there to show the issue.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by roja45** [comment] 2020-02-25 15:51
[testtranslation-master-1.0.0.zip](https://github.com/PrestaShop/PrestaShop/files/4250875/testtranslation-master-1.0.0.zip)

**Comment by roja45** [comment] 2020-02-25 15:52
Also, it adds this htaccess file when you upgrade the module as well.  I am getting a lot of support requests from customers upgrading the 1.7.6.3, and finding the module can no longer load the files it needs.

**Comment by khouloudbelguith** [comment] 2020-02-25 16:19
Hi @roja45,

Thanks for your report.
I have the same issue with PS1.7.6.3.
![image](https://user-images.githubusercontent.com/16067358/75266439-a29b2480-57f2-11ea-9316-c526ba86bef4.png)

It is Ok with PS1.7.5.2, PS1.7.6.0, PS1.7.6.1, and PS1.7.6.2.
Ping @PrestaShop/prestashop-core-developers what do you think? 
I think it is a regression.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-25 16:20
Maybe related to this issue: https://github.com/PrestaShop/PrestaShop/issues/17496

**Comment by eternoendless** [comment] 2020-02-25 17:06
@roja45 Why do you need the vendor directory to be accessible? Usually all requests should go though a module controller.

**Comment by roja45** [comment] 2020-02-25 17:15
`public function hookActionAdminControllerSetMedia($params)
    {
        if ($this->context->controller->controller_name == 'AdminModules' &&
            Tools::getValue('configure') == $this->name
        ) {
            $this->context->controller->addJS($this->_path . 'views/js/roja45moduleadmin.js');
            $this->context->controller->addJS($this->_path . 'vendor/riotjs/riot+compiler.min.js');
        }
    }`

broken.

**Comment by eternoendless** [comment] 2020-02-25 17:21
You shouldn't use composer to distribute javascript files, try NPM instead. The vendor directory is usually not supposed to be user accessible because it can represent a security threat.

**Comment by roja45** [comment] 2020-02-25 17:23
Not using composer.  Following Prestashop guidelines and using a vendor folder for required external libraries: https://devdocs.prestashop.com/1.7/modules/creation/module-file-structure/

**Comment by roja45** [comment] 2020-02-25 18:07
@eternoendless  A question on this then, as I assume this means that it was intentional, is it specifically the 'vendor' folder?  If I call this something else will I not have the htaccess file added?
Since this is breaking a lot of Prestashop user installations, it will probably be quicker to update the module, rather then wait for a fix.

**Comment by roja45** [comment] 2020-03-03 12:22
I think this also affects the /img directory, and compatibility with the tiny_mce rich text editor.  I load a mail template into the text editor, which includes a link to the shop logo, and I get a denied error for the logo.

**Comment by eternoendless** [comment] 2020-03-16 15:58
> Not using composer.

Avoid using a folder called `vendor` in the root of your module unless you're managing it through composer. This particular folder is intended to be managed by composer and used exclusively for PHP libraries.

> I think this also affects the /img directory, and compatibility with the tiny_mce rich text editor. I load a mail template into the text editor, which includes a link to the shop logo, and I get a denied error for the logo.

Please open a new issue describing that specific problem in detail.

I'm closing this one as the originally described behavior regarding htaccess is intentional, not a bug.

**Closed as completed by eternoendless** 2020-03-16 15:58 UTC
Labels: Bug, Minor, Won't fix, Modules, Regression, 1.7.6.3
