### ISSUE TITLE
BO -Bad link form displayed on Features page when Features option is disable

### ISSUE THREAD

**Issue by hrostyk** [PrestaShop/PrestaShop#31015] opened 2023-01-24 15:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

<img width="1101" alt="CleanShot 2023-01-24 at 17 41 11@2x" src="https://user-images.githubusercontent.com/7484618/214341221-ea5b9a71-299c-4280-9315-d49d24bea62c.png">

### Steps to reproduce

1. Go to BO
2. Advanced Parameters -> Performance
3. Disable Features
4. Attributes & Features -> Attributes
5. Features

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.34

**Comment by sallemiines** [comment] 2023-01-24 16:06
Hello @hrostyk 

 Thanx for reporting the issue.
 
 Following your steps I reproduce the issue with **PS801 and develop NOK** : you can see the attached screen record : 
 
 

https://user-images.githubusercontent.com/31663369/214343349-e267fff5-8156-4051-80c5-5027aa0b10a2.mp4

**With PS1787 , PS800 OK**  you can see the attached screen shot 

![Features-•-1787](https://user-images.githubusercontent.com/31663369/214343594-dd556bcf-d440-41af-9f72-109dec44acaa.png)

Nice Catch it's a regression ! 

Thank you

**Comment by MatShir** [comment] 2023-02-22 14:15
It seems to be fixed in 8.1.x

**Comment by florine2623** [comment] 2023-03-09 10:20
It is indeed fixed in PS 8.1.0.

<img width="1440" alt="Screenshot 2023-03-09 at 11 19 08" src="https://user-images.githubusercontent.com/16019289/223993746-156f9a5d-34c4-4ef2-a349-3ba60900d42f.png">

So I close the issue.
Thanks!

**Closed as completed by florine2623** 2023-03-09 10:20 UTC
Labels: Bug, Minor, BO, Features, Regression, Fixed, Verified, 8.0.1
