### ISSUE TITLE
Error 500 after upload autoupgrade module - back office is dead 

### ISSUE THREAD

**Issue by Tomskor** [PrestaShop/PrestaShop#10118] opened 2018-08-24 11:00 UTC
When I trying to upgrade autoupgrade module from back office with UPLOAD MODULE what I downloaded from github this error shows up:

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

Upgrade environment (please complete the following information):

Version you started from: 4.1 beta 2
Version you upgrade to: 4.1 final
Way of upgrade: Backoffice

Shop works but every time when I trying to enter to backoffice have error 500, trying to disable autoupgrade module from SQL but still this same, when I change name folder autoupgrade module still get error 500

Any idea what fix it? Please help

Dev log:

![asd](https://user-images.githubusercontent.com/42567245/44581254-4985a700-a79d-11e8-9abb-1bc28f4ef530.jpg)

Files from devlog its not modificated on the server.

**Comment by khouloudbelguith** [comment] 2018-08-24 11:30
Hi @Tomskor,

I did not manage to reproduce the issue with the last version 1.7.4.2 & the 1-click upgrade module v4.1.0.
https://drive.google.com/file/d/1Wv69X5EFgF1rXWVxl3esbMGk2x_kx2r0/view
Could you please try with this link: https://github.com/PrestaShop/autoupgrade/releases/download/v4.1.0/autoupgrade-v4.1.0.zip & feedback.

Best regards, Khouloud

**Comment by Tomskor** [comment] 2018-08-24 11:39
@khouloudbelguith when I trying to upload again on our mirror store module from your link everything works fine and when I delete module one click upgrade and install againt, still works ok. But like I said in the first time errors comes up but on second time its worked. 

Maybe try to install first some beta version 1 or 2 and then install on that (without deleteing) newest version.

**Comment by khouloudbelguith** [comment] 2018-08-24 12:26
Hi @Tomskor 

Is your problem solved?

Best regards, 
Khouloud

**Comment by Tomskor** [comment] 2018-08-27 06:08
@khouloudbelguith no, still is the problem, have permanet error 500 when try to enter to backoffice. We cant check customers orders...

**Comment by Tomskor** [comment] 2018-08-27 06:40
Ok, ITS WORKS

How? Find on polish forum solution - delete or change filename of VENDOR catalouge in ps_facatesearch

And now, how its cause so big error? And can you make it right?

**Comment by novanova77** [comment] 2018-08-27 09:35
Hi, I have had the same problem as you had. Ran the 1-click upgrade and can't access the backend. Get the 500 Error like you did. Am running Presta 1.6.
But I don't have too much knowledge on how to fix it. Do I replace the the autoupgrade directory on the server under 'modules' with the autoupgrade unzipped directory mentioned by khouloudbelguith above?
Otherwise where do I find the ps_facatesearch -  VENDOR catalogue file, to chnge or delete?
Any help appreciated.

**Comment by Tomskor** [comment] 2018-08-27 09:47
@novanova77 you find it on ftp: yourdomain/modules/ps_facetedsearch and there should be VENDOR and change name or delete it

**Comment by novanova77** [comment] 2018-08-27 10:21
Thanks khouloudbelguit for quick response.
Under... presta/admin1231/autoupgrade/tmp it says there are no files there. Says Empty directory listing.
There is another autoupgrade directory in the modules directorye  but it does not have a tmp directory.
Should I upload and replace the autoupgrade directory in the admin1231 directory with the unzipped one in your earlier link?

**Comment by novanova77** [comment] 2018-08-27 10:23
Also thanks Tomskor, but did a search of the modules directory and ps_facetedsearch doesn't come up at all. Are you on Presta 1.7?

**Comment by novanova77** [comment] 2018-08-27 10:33
Hi khouloudbelguith & Tomskor,

The site backend is back up!
I renamed /modules/autoupgrade to badautoupgrade and uploaded the new autoupgrade into modules. Nothing happened, maybe slow server? But working now. So thanks for the input and assistance. Hopefully it will stay working.
Regards,
Tony

**Comment by Tomskor** [comment] 2018-08-27 10:36
@novanova77  great! yes I am on presta 1.7 so I forget that on 1.6 there is some differences.

**Comment by khouloudbelguith** [comment] 2018-08-27 10:57
Hi @Tomskor,

Since it is fixed, can I close the issue?

Best regards, Khouloud

**Comment by Tomskor** [comment] 2018-08-27 10:59
@khouloudbelguith I think so.

**Comment by khouloudbelguith** [comment] 2018-08-27 14:08
Hi @Tomskor,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-08-27 14:09
Hi @Tomskor,

I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-08-27 14:09 UTC
Labels: Bug, Autoupgrade, No change required, 1.7.4.2

**Comment by Ingematic** [comment] 2018-10-08 20:41
Hi,
i have find the "Error 500 Internal Server Error" in the admin section, after uninstall the module 1-click upgrade ver 4.0.0
I have version PS 1.7.4.2
If i rename the /root/modules/ps_facetedsearch in other name, the error 500 not compare.
After if i restore the name of module ps_facetedsearch then i have the error 500.
Have you any idea?
Thank you
Michele

**Comment by yalefresne** [comment] 2019-01-17 13:44
Hi,
i have find the "Error 500 Internal Server Error" in the admin section too.
After exploring logs, i clean cache folder --> prestashop\var\cache\ and that solve my problem.

PS: Sorry for my english

**Comment by Ingematic** [comment] 2019-01-17 13:45
Il suo messaggio è stato correttamente recapitato al Supporto OnLine.
Risponderemo al più presto.

Grazie per averci contattato
Staff - INGEMATIC Web Management
