### ISSUE TITLE
3 Decimals not working correctly

### ISSUE THREAD

**Issue by fraizor** [PrestaShop/PrestaShop#22431] opened 2020-12-15 12:33 UTC
**Describe the bug**
### 2 decimals showing instead of 3

When using a 3 decimals currency (OMR)
It is showing only 2 decimals in front office (product page)
regardless of "Decimals" field value in backoffice -->localizations --> currencies 

Expected behavior
Showing 3 decimals for item price 
example: 5.500

**Steps to Reproduce**

1- Go to backoffice -->localizations --> currencies 
2- Select OMR from the dropdown menu
3- enable 
4- save
5- in front office navigate to a product page --> choose OMR currency from currency block
6- price is displayed 3 decimas only 

**Additional information**
PrestaShop version: 1.7.7
PHP version: 7.3.25

**Screenshots**
https://prnt.sc/w35zcj
https://prnt.sc/w35zz1

**Comment by hibatallahAouadni** [comment] 2020-12-15 15:27
Hello @fraizor 

This issue is already solved with PS1.7.7.0, follow these steps to use three digits after the comma with your currency:

1. BO > IMPROVE > International > Localization
2. Go to Currencies tab
3. Click on edit button of your currency OMR
4. Change the value of Decimals to 3
5. Save
6. Check FO > you will see all prices are displayed with three digits after the comma with your currency.

See attached screen record below:

https://drive.google.com/file/d/1GNej10v703es_H2_W188zVYjaFBwG5Yz/view

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-15 15:27
Duplicate of #22375

**Closed as completed by hibatallahAouadni** 2020-12-15 15:27 UTC
Labels: Duplicate

**Comment by fraizor** [comment] 2020-12-15 18:38
@hibatallahAouadni 
Dear hiba
The issue is not fixed in 1.7.7.0
I am using it and I confirm the issue is there.
In fact try to set the AED exchange rate to 1 and you will face the issue
