### ISSUE TITLE
Ps 1.7.7.8 does not create valid invoices

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#30111] opened 2022-10-25 07:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Invoices which are generated, are not complying with regulations. All store information (Name, adress, zip, vat, Coc, bank) has disappeared from the invoice tpl.

Looked up the /pdf/invoice.addresses-tab.tpl,  file used and noticed that for 1.7 the code has changed compared to 1.6.
Used the same code from 1.6 for 1.7, which resulted in a complete blank invoice with only the logo and invoice number (still no information, customer information was gone, products were gone and so on).

At this moment all invoices are not valid which can cause tremendous problems with the goverment, how to fix this asap???

### Expected behavior

generate working and valid invoices!

### Steps to reproduce

/pdf/invoice.addresses-tab.tpl

Norice difference in files between 1.6 and 1.7

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment] 2022-10-26 04:36
Hello @loetje88 

I didn't manage to reproduce the issue with the provided infos.
Did you upgrade your shop from 1.6 to 1.7.7.8? If so, which method you used to upgrade your shop? And did you encounter any issue while upgrading your shop?
Please check and feedback.

Thanks!

**Comment by loetje88** [comment] 2022-10-26 07:14
> Hello @loetje88
> 
> I didn't manage to reproduce the issue with the provided infos. Did you upgrade your shop from 1.6 to 1.7.7.8? If so, which method you used to upgrade your shop? And did you encounter any issue while upgrading your shop? Please check and feedback.
> 
> Thanks!

No, It was a fresh and new install with prestashop 1.7.7 and from there upgraded as provided.
To reproduce, see attached screenshot.
![QzpcVXNlcnNcdXNlclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNDQyNTc3MzczX3YyXEltYWdlRmlsZXNcMTU4MDQ3MzQ3ODc4-3OTZGMkY3QS0xMTlFLTQzMjMtQjM0Qy1GMUZERDRBNURGN0IucG5n thumb png 0c6514923dd660e2cf745e7](https://user-images.githubusercontent.com/31586907/197959197-e645f163-33c8-4a9d-a3df-20dfd982a1e7.png)

**Comment by loetje88** [comment] 2022-10-26 14:49
> Look at the bottom of the generated PDF, the info is there, or should be there.
> 
> Don't forget to fill all info in Contact->Stores
> 
> My customers didn't complain by now.
> 
> I tried to modify the template but the PDF look's bad so i keep that at the bottom.
> 
> PS; I had to create my own cache for all invoices and delivery sheets since invoices once created cannot be modified in any way, an PrestaShop recreates it every time you download.

Only the regular store information, not vatnumber, COC number and bank number.Also, not in the header section - which is required by law to be valid invoices. At this moment, the invoice does not show which company and with what registrered information is providing the invoice.

**Comment by florine2623** [comment] 2022-11-07 14:41
Hello @loetje88 ,

Are you talking about the following part at the bottom of the invoice:
<img width="335" alt="Screenshot 2022-11-07 at 15 40 54" src="https://user-images.githubusercontent.com/16019289/200337694-740c40ca-fc7b-4b49-a27c-3ee2fa429b34.png">

Waiting for your feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2022-11-22 16:08
Hello @loetje88 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-11-22 16:08 UTC
Labels: Bug, CO, Invoices, 1.7.7.8, Invalid
