### ISSUE TITLE
SEO preview on product page displays Description instead of Summary

### ISSUE THREAD

**Issue by ZioCan** [PrestaShop/PrestaShop#32296] opened 2023-04-23 19:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

SEO preview on product page displays the content of the **Description** field instead of the **Summary** field.
I have a product with both Summary and Description fields filled, the product has only one combination.
In the SEO tab, the preview shows title, link and meta description, title and link are ok, but the meta description shows the content of the **Description** field.
Looking at the source code of the page, instead i have the content of the **Summary** field in the meta description.
So what is shown in the SEO tab preview, is different from what is shown in the search engines.

### Steps to reproduce

BO: Look at the preview in the SEO tab of the product page
FO: Look at the source code of the product page

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2023-04-25 13:04
Hello @ZioCan ,

I have reproduced your issue in 1.7.8.9, 8.0.x, 8.1.x and develop branches. I'll add this to the backlog so it can be fixed.

<img width="1200" alt="Screenshot 2023-04-25 at 14 47 34" src="https://user-images.githubusercontent.com/16019289/234284199-c2c273fa-31cc-4c9f-9919-379ebadc9116.png">

<img width="1436" alt="Screenshot 2023-04-25 at 14 47 48" src="https://user-images.githubusercontent.com/16019289/234284483-e999b0a9-859c-4416-b491-cefcfed0b49b.png">

It should be changed to `name="summary"` or we should add another element `name="summary"`

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment] 2023-05-02 16:12
Hi @ZioCan and @florine2623 

So @M0rgan01 and I have been looking at this bug, and we believe there is no issue 😄 .

Let's break this down:

## Front-office

In the Front-office page, a `meta` tag is used like this: `<meta name="description" content="...">` .

The data being inserted in this tag is the content of the field "Summary" from the back-office and **this is intended**.  This is because Summary contains more information than Description. So I understand that the `name` attribute and the data location attribute mismatch, but this is more logical 👍 

> It should be changed to name="summary" or we should add another element name="summary"

We cannot modify like this meta tags, they are designed by authorities like Google, we cannot rename or add meta tags as we like: the rules are defined by Google, not us 😄 !

## Back-office

The SEO preview in the back-office product page works as expected from our tests. It outputs the content of the "summary" field, which matches the front-office behavior. I know @ZioCan you mentioned this is wrong but this is what we tested on the `develop` branch.

### One more thing 😄 

In database,
- description field is stored in database as field `description`
- summary field is stored in database as field `short_description` 🤯 

So this is adding to the confusion 😓 (and don't get me started about `meta_description`...)

## Conclusion

We believe that, on `develop` branch, the code behaves as it should and there is no bug to fix.

**Comment by ZioCan** [comment] 2023-05-02 18:35
Ok, the SEO preview in the back-office product page works as expected from your tests because you tested on the develop branch.
But this is about 1.7.8.x, i tested it on 1.7.8.6, and after upgrading to 1.7.8.9 i still see the same behaviour.

**Comment by Hlavtox** [comment] 2024-03-18 19:51
Nothing like this happens on 8.1.5

**Closed as completed by Hlavtox** 2024-03-18 19:51 UTC
Labels: Bug, Minor, FO, SEO & URLs, Fixed, Verified, 1.7.8.6
