### ISSUE TITLE
Stock Web Service 1.7.5.2

### ISSUE THREAD

**Issue by IsaacVe** [PrestaShop/PrestaShop#16858] opened 2019-12-18 20:11 UTC
What is the correct way to update the stock? via web services

Prestashop 1.7.5.2
Thank you in advance.

**Comment by khouloudbelguith** [comment] 2019-12-19 07:59
Hi @IsaacVe,

You can use this script to update stock available:
```
<html><head><title>CRUD Tutorial - Create example</title></head><body>
<?php
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'shop.com');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'shop.com',
    'key',
    false);
$id = 1; //ID order Here
$xml = $ws->get(array('resource' => 'stock_availables', 'id' => $id));
echo "BEFORE\n";
echo $xml->asXML();
$xml->stock_available->quantity = 1000;
$xml->stock_available->physical_quantity = 5;
$xml->stock_available->reserved_quantity = 4;
//$xml->order->shipping_number = 10;
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'stock_availables';
$xml = $ws->edit($opt);
$xml = $ws->get(array('resource' => 'stock_availables', 'id' => $id));
echo "AFTER\n";
echo $xml->asXML();
```
But the `physical_quantity` and `reserved_quantity` are not updated as reported here: https://github.com/PrestaShop/PrestaShop/issues/15976.
It is added to our bug roadmap.
Also, for more details you can follow our official documentation: http://doc.prestashop.com/display/PS16/Web+service+tutorial

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-19 07:59
Duplicate of #15976

**Closed as completed by khouloudbelguith** 2019-12-19 07:59 UTC
Labels: Duplicate

**Comment by papich06** [comment] 2023-01-09 15:50
Hello,
how can manage "Advanced stock management" in 1.7.8 ?

advanced stock management existed in 1.6 then was removed and put back in 1.7.2
https://docs.prestashop-project.org/1-6-documentation/english-documentation/user-guide/advanced-stock-management/presenting-the-stock-management-interface
