### ISSUE TITLE
Set minimum quantity for sale doesn't work

### ISSUE THREAD

**Issue by edensh89** [PrestaShop/PrestaShop#20470] opened 2020-08-05 15:23 UTC
#### Describe the bug
I have regular product without combination, I set to this product minimum quantity for sale and I still have the ability to buy less than the minimum quantity.

I expect to get an error message or to not allow me to add to the cart less than the set quantity.

#### Steps to Reproduce

1. Open - https://www.multi-i.at/en/bulk-jelly/881-bulk-jelly-22-blueberry.html 
2. Click on add to cart when the quantity is less than 50

* PrestaShop version: 1.7.3.0
* PHP version: 7.1
![Screen Shot 2020-08-05 at 18 19 59](https://user-images.githubusercontent.com/46376752/89431518-bc00af00-d748-11ea-8e4b-67cb3d7e9dc1.png)

**Comment by khouloudbelguith** [comment] 2020-08-05 15:51
Hi @edensh89,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10279 to fix the issue.
Your ticket is a duplicate of #10162
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-05 15:51
Duplicate of #10162

**Closed as completed by khouloudbelguith** 2020-08-05 15:51 UTC
Labels: Duplicate

**Comment by edensh89** [comment] 2020-08-06 09:36
Thanks for replying.
I added the code to handle but it still doesn't work.
