### ISSUE TITLE
ISO code at BO Localization/Languages should be ISO 3166-1 alpha-2 code not ISO_639-1_codes

### ISSUE THREAD

**Issue by NoZTurn** [PrestaShop/PrestaShop#26012] opened 2021-09-28 06:48 UTC
#### Describe the bug

When I add a language here: International - Localization-Languages -- Add new language in the BO, the second textarea is ISO code, follow the HELP popup it was explained as follows:
_ISO code. Enter the adequate 2-letter ISO 639-1 code. See http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes for more information.If you are importing a language pack, this code should exactly match the one of the pack._

but languages like zh-TW/ zh-CN en-US/en_GB and es, pt, ar such languages used in different contries and areas have the same the ISO 639-1, so if you fill ISO 639-1 code here, languages would NOT distinguish in the urls in FO when rewrite enabled, because the url in FO use this ISO 629-1 code in the url to distinguish languages.

So the right code fill here should be ISO 3166-1 alpha-2 code, in fact when I use International - Translations -Add / Update a language function in BO to add a new language, here you get the right code, and the ISO code here uses the ISO 3166-1 alpha-2 code which is right as I have illustrate above.

bellow, I scrapped a picture to show this:
the language zh-tw/zh-cn/en-gb which is added with the second method, so the ISO code the right as showed with RED rectangular box enclosed. if you add those language like the first method, there tw should be zh, cn also be zh, and gb should be  en, that obvious wrong.
![lang](https://user-images.githubusercontent.com/2842182/135035941-6c50f56f-57ca-4fbe-ae35-f945aea12d2a.jpg)

If what I said above was right, so another mistake should be corrected, that is ISO code for the language id 1 should be US not en,which shown in the picture as the green circle box enclosed.

#### Expected behavior

ISO code at BO Localization/Languages should be ISO 3166-1 alpha-2 code not ISO_639-1_codes.

#### Steps to Reproduce

**Screenshots**
.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by florine2623** [comment] 2021-09-28 07:06
Hello @NoZTurn ,

I'll ping Product team to have their opinion on this topic.
Please stay tuned. Thanks!

**Comment by florine2623** [comment] 2021-09-28 07:08
Ping @PrestaShop/product-team ,

Could you give @NoZTurn an explanation on why the ISO code and Language code are build this way ?
Thanks a lot

**Comment by NoZTurn** [comment] 2021-09-28 08:40
> Hello @NoZTurn ,
> 
> I'll ping Product team to have their opinion on this topic.
> Please stay tuned. Thanks!

thanks, and another suggestion is if we can change to use language code in the url in FO to distiguage different languages? for example: https://www.microsoft.com/en-us/locale.aspx .

**Comment by NoZTurn** [comment] 2021-09-28 09:04
I search a little, and I think this is not a new problem, here is a list of related issues:

https://github.com/PrestaShop/PrestaShop/issues/16070
https://github.com/PrestaShop/PrestaShop/issues/16029
https://github.com/PrestaShop/PrestaShop/issues/16004
https://github.com/PrestaShop/PrestaShop/issues/21483
https://github.com/PrestaShop/PrestaShop/issues/24254

**Comment by hibatallahAouadni** [comment] 2021-11-10 16:41
Hello @NoZTurn 

Thanks for your patience :pray: 
Could you please provide clear and concise steps to reproduce.

Thanks in advance.

**Comment by NoZTurn** [comment] 2021-11-14 16:06
> Hello @NoZTurn
> 
> Thanks for your patience 🙏 Could you please provide clear and concise steps to reproduce.
> 
> Thanks in advance.

BO - International - Localization-Languages -- Add new language(like zh-TW/ zh-CN en-US/en_GB and es, pt, ar such languages used in different contries and areas) in the BO, then you can see ISO code at BO Localization/Languages just added is ISO 3166-1 alpha-2 code not ISO_639-1_codes.

**Comment by NoZTurn** [comment] 2021-11-15 08:37
> Hello @NoZTurn
> 
> Thanks for your patience 🙏 Could you please provide clear and concise steps to reproduce.
> 
> Thanks in advance.

I see https://github.com/PrestaShop/PrestaShop/projects/6 here have Backloged the issue 16070: https://github.com/PrestaShop/PrestaShop/issues/16070 , so If I can think it means the offcial team have confirmed this issue?
![20211115163238](https://user-images.githubusercontent.com/2842182/141748931-b3856720-fe18-4e85-b1ee-4a898aa9a378.png)

**Comment by NoZTurn** [comment] 2021-11-15 08:39
@hibatallahAouadni sorry, I forget to at you, please see the above two reply.

**Comment by NoZTurn** [comment] 2021-11-15 08:39
@hibatallahAouadni sorry, I forget to at you, please see the above two reply.

**Comment by khouloudbelguith** [comment] 2021-11-18 15:08
@NoZTurn, thanks for your reply.
Can you confirm that this ticket is similar to this issue: #16070?
Can we close this issue as a duplicate?

Thanks!

**Comment by NoZTurn** [comment] 2021-11-19 09:26
> @NoZTurn, thanks for your reply. Can you confirm that this ticket is similar to this issue: #16070? Can we close this issue as a duplicate?
> 
> Thanks!

@khouloudbelguith , hello, thanks for you attention, this ticket is similiar to that issue, but to say duplicate is not so acurate, this issue is some more info to explain the issue https://github.com/PrestaShop/PrestaShop/issues/16070, and also gives an solution.

**Comment by khouloudbelguith** [comment] 2021-11-19 15:38
@NoZTurn, Can I close this issue as a duplicate of #16070 and I will update the other issue with your first comment.
Because it is the same issue.
Thanks!

**Comment by NoZTurn** [comment] 2021-11-20 04:42
> @NoZTurn, Can I close this issue as a duplicate of #16070 and I will update the other issue with your first comment. Because it is the same issue. Thanks!

@khouloudbelguith , OK, agree with you, thanks.

**Comment by hibatallahAouadni** [comment] 2021-11-22 11:36
Hello @NoZTurn 

Thanks for your feedback!
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16070. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-22 11:36
Duplicate of #16070

**Closed as completed by hibatallahAouadni** 2021-11-22 11:36 UTC
Labels: Bug, BO, Duplicate, Localization, Languages, 1.7.6.0, Invalid
