### ISSUE TITLE
An error occurred during installation... With MAMP

### ISSUE THREAD

**Issue by amroeldewiny** [PrestaShop/PrestaShop#16171] opened 2019-10-29 10:06 UTC
Before i post this installation issue i tried everything to enable all extension in php.ini file , but no use i'm still in the same point.
1- iam using MAMP
2- php 7.2.21 i can upgrade to 7.3.8 but still no use
3- MacOS 10.13
![Screen Shot 2019-10-29 at 11 03 36 AM](https://user-images.githubusercontent.com/25608813/67757361-f449c300-fa3b-11e9-865d-4610d7539e89.png)

**Comment by khouloudbelguith** [comment] 2019-10-29 10:25
Hi @amroeldewiny,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
What is you exact version PrestaShop did you use?

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1.Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2.Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3.Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by amroeldewiny** [comment] 2019-10-29 14:10
Hi khouloudbelguith,

Thank you for your answer. I'm using PrestaShop 1.7.6.1 - PHP 7.3.8
Everytime i try to make fresh installation i get error one time 2OO - one time 500

![Screen Shot 2019-10-29 at 2 57 41 PM](https://user-images.githubusercontent.com/25608813/67774303-654da280-fa5d-11e9-9448-69ed2838994c.png)

I know wordpress something else than PrestaShop but to test my MAMP i installed wordpress just for testing and everything looking great. I'M STILL IN THE SAME ISSUE.
I upload the phppsinfo.php file to see where is the problem but the file give me very white background without errors.

**Comment by khouloudbelguith** [comment] 2019-10-29 14:12
@amroeldewiny, Please downgrade your PHP version to PHP7.2, PrestaShop is not compatible with PHP7.3.

Thanks!

**Comment by amroeldewiny** [comment] 2019-10-29 17:38
I tried to install PrestaShop on my MacOs many many many times . 
WITH 
PHP 7.1.31
PHP 7.2.21
PHP 7.3.8
NO php version working at all.

**Comment by khouloudbelguith** [comment] 2019-10-30 09:29
@amroeldewiny,

>I upload the phppsinfo.php file to see where is the problem but the file give me very white background without errors.

There is no information displayed on your server?

Thanks to follow this link: https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page to create a PHP info file on your server.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by amroeldewiny** [comment] 2019-11-18 13:50
Thanks khouloudbelguith for helping me, i try many ways to install prestashop 1.7 on my macOS
i tried MAMP, Docker, terminal PHP - Mysql,  nothing form this tools working with me . So my last chance it was with
Bitnami MAMP Stack and everything working correctly.

**Comment by khouloudbelguith** [comment] 2019-11-18 13:52
@amroeldewiny, thanks for your feedback.
Since it is ok, I will close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-18 13:52 UTC
Labels: Bug, IN, No change required
