### ISSUE TITLE
Maintenance Mode Multistore Bug 1.7.5

### ISSUE THREAD

**Issue by Thobal51** [PrestaShop/PrestaShop#12342] opened 2019-01-29 10:42 UTC
**Describe the bug**
Since a prestashop update from version 1.6.1.20 to 1.7.5, I can't access the maintenance menu in the back office (Multistore). I have this error :
Uncaught Exception: Expected argument of type "object, array or empty", "string" given
Uncaught PHP Exception Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected argument of type "object, array or empty", "string" given" at /var/www/refonte/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 41

I have already seen this error on older version 1.7 but the solutions provided don't work on this version 1.7.5. Thanks for your help.

**Screenshots**
![capture](https://user-images.githubusercontent.com/47141264/51902142-9d826080-23b9-11e9-8f0d-d86d67a327fc.JPG)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2019-01-29 10:53
Hi @Thobal51,

In your Database table "ps_configuration_lang", could you please try to enter this SQL query.
`INSERT INTO `ps_configuration_lang` (`id_configuration`, `id_lang`, `value`, `date_upd`) VALUES ('277', '1', 'maintenance', '2018-11-12 00:00:00');`
![image](https://user-images.githubusercontent.com/16067358/48343270-3aaee200-e672-11e8-86c2-a112f9fc7c4a.png)
Thanks to check & feedback.

**Comment by Thobal51** [comment] 2019-01-29 11:21
Thank you for your help but it doesn't work. I have the same error message.

**Comment by khouloudbelguith** [comment] 2019-01-29 11:25
@Thobal51, could you please try to replace the table ps_configuration_lang by another one from fresh install PS1.7.5.0.
Thanks to check & feedback.

**Comment by Thobal51** [comment] 2019-01-29 16:36
It still doesn't work. Always the same error message ....

**Comment by khouloudbelguith** [comment] 2019-01-29 16:39
@Thobal51, if you try to replace the table ps_configuration also by another one from fresh install PS1.7.5.0, the issue is solved?
Thanks to check & feedback.

**Comment by Thobal51** [comment] 2019-01-30 07:53
It works if I replace the table ps_configuration by another one from fresh intall.

**Comment by khouloudbelguith** [comment] 2019-01-30 07:57
Hi @Thobal51,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-30 07:57 UTC
Labels: BO, Maintenance, Autoupgrade, No change required, 1.7.5.0
