### ISSUE TITLE
MANUAL STOCK UPDATE ERROR / REFUNDS

### ISSUE THREAD

**Issue by PBS7** [PrestaShop/PrestaShop#35823] opened 2024-04-04 10:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning 

In my prestashop page I have 2 errors that I can't figure out where it comes from:

1. When I modify the manual stock of a product and save it, the configuration appears updated, as if everything went well, but then I refresh the page and that information is deleted and there is no record in the logs. So the customer continues to see my product at 0.

2. When we make partial refunds or full refunds of orders we have observed that depending on the date it is recorded and goes to my ERP or not automatically I mean. The date is the only common link that we have been able to observe between the products that we wanted to refund.

The version of prestashop is 1.7.7.2

I look forward to hearing from you, thanks

Best regards

### Steps to reproduce

Steps for each error:

1. enter some product > combinations modify the quantity manually > save > save > "configuration updated" appears > we give to product preview > no change in quantities is seen the product appears out of stock.

2. enter the order to be refunded > partial refund > select the quantity and the amount to be refunded > deselect Re-enter products in stock > partial refund
As mentioned above, we have noticed that the ERP only generates the credit note after this action for the orders in due month, for example today 04/04 the orders of March no problem are recorded in logs but if the order is from 29/02 there is no record. 

Thanks

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.3.32

**Comment by florine2623** [comment] 2024-04-04 12:53
Hello @PBS7 ,

I can't reproduce your issue as you can see here :

1/

https://github.com/PrestaShop/PrestaShop/assets/16019289/cd60a9cd-8731-4acd-92b5-909421792b21

2/

https://github.com/PrestaShop/PrestaShop/assets/16019289/0884070a-3c6c-46a3-bd0e-88fe96d4aa14

<img width="1213" alt="Screenshot 2024-04-04 at 14 52 01" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/41996194-af09-4c8a-bdbe-fcaeca5f17c4">

I'm closing your issue as I can't reproduce it.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2024-04-04 12:53 UTC
Labels: Bug
