### ISSUE TITLE
Prestashop 1.7.6.1 - bug when i create or update an employee

### ISSUE THREAD

**Issue by charlybrown44** [PrestaShop/PrestaShop#18037] opened 2020-03-07 14:25 UTC
Good afternoon,

I have the following message when i am trying to create or update an employee:

Une erreur inattendue s'est produite. [PrestaShopException code 0]

I tried the debug mode and to see the logs but nothing.

Can you help me ?

Thanks a lot

**Comment by khouloudbelguith** [comment] 2020-03-09 08:12
Hi @charlybrown44,

I did not manage to reproduce the issue with PS1.7.6.1 and PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1MLmKUqUWaZuQiCh4SD2XbNql9CADZTrz/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by charlybrown44** [comment] 2020-03-18 09:44
Hi,

It seems that it is a problem with a field that i created in the database.
I fix it by adding "unnasigned" on this int field.

I am still looking to understand why it makes this error.

Sincerely.

**Comment by khouloudbelguith** [comment] 2020-03-18 10:03
@charlybrown44,

>It seems that it is a problem with a field that i created in the database.

This field is created manually in the database?

Thanks!

**Comment by sarahdib** [comment] 2020-04-21 15:06
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-04-21 15:06 UTC
Labels: Bug, BO, Team, Employees, No change required, migration, 1.7.6.1
