### ISSUE TITLE
Catalog Price Rules Issue

### ISSUE THREAD

**Issue by pablo9x** [PrestaShop/PrestaShop#25638] opened 2021-08-18 13:21 UTC
**Describe the bug**

I have a problem with the pricing rules. Everything configured correctly, rules enabled in preferences but the module does not show discounts. The application of promotions on a single product card works correctly. For verification, I installed a custom shop with the selected template and everything is correct there.

Module: Specials block v1.0.1

#### Expected behavior

I expect the promotions module to be displayed on the homepage and added promotions in the product group to be displayed correctly.

#### Steps to Reproduce

1. Go to 'Catalog' -> 'Discount' -> 'Catalog Price Rules' -> 'Add new'
2. I set it as below
![1](https://user-images.githubusercontent.com/89137161/130030942-9136852a-2a3d-429c-a0c6-3ee44c4b77ad.png)
3. In properties, I activate the display of discounted products
![2](https://user-images.githubusercontent.com/89137161/130031338-6fb04808-9337-4c87-b734-e99a091fa39a.png)

4. The promotions section is not displayed on the main page of the shop, and products to which a promotion was assigned do not display the promotion

5. Doing analogous steps on a clean custom shop everything displays correctly

**Screenshots**

#### Additional information
* PrestaShop version: 1.7.7.6
* PHP version: PHP 7.2
* Theme: Bentriz Version 1.0.6

**Comment by hibatallahAouadni** [comment] 2021-08-18 16:11
Hello @pablo9x 

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- expected behavior
- Steps to reproduce
- ...

> but the module does not show discounts

Which module you use? Please check and feedback.

If you don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by pablo9x** [comment] 2021-08-19 08:35
I have updated the information in the first post

**Comment by hibatallahAouadni** [comment] 2021-08-19 09:05
Hello @pablo9x 

Thanks for your feedback.
I didn't manage to reproduce the issue with PS1776, see the attached screen record below:

https://drive.google.com/file/d/11VKTLa8d6Mjq4RWP-tIhXs0iano0ungk/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-08 14:37
Hello @pablo9x 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-08 14:37 UTC
Labels: Bug, BO, Catalog price rules, No change required

**Comment by piotro9x** [comment] 2021-10-06 19:07
Hello, I am still unable to get the catalogue discount rules to work. I present the video. I previously had multistore running - currently inactive (not sure if this is relevant). 
[https://watch.screencastify.com/v/SWyGszx1dMLFB7cPcb7X?fbclid=IwAR1hpjAExSCEGOBfOXIAVY7ZuaP9isLc_NbNvHYPmZsQFPMEXvojqvS19_g](url)
