### ISSUE TITLE
Search returns too much products - revert Search.php changes from 1.6 times

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16019] opened 2019-10-18 13:34 UTC
**Describe the bug**
Hi guys, sometimes around 1.6.1.13 times, somebody changed Search.php and totally f***ed up the logic of search. I reverted the changes on our store back then, but I think I am not the only one that would find the original way better.

**The Search.php class stayed with us in the same form till 1.7.6.1.**

**How to Reproduce it - Preparation**
Make some products like this:
- Automobile red
- Automobile green
- Automobile blue
- Motorcycle red
- Motorcycle green
- Motorcycle blue
- Boat red
- Boat green
- Boat blue

**How to Reproduce it - Query**
Before the change, when you searched _Red Automobile_, it found, yes, red automobile.

But after that change - current condition. You search _Red automobile_ and **it returns all automobiles and all red things.**

**Changed lines**
LEFT - Current
RIGHT - Original, fixed
![changes](https://user-images.githubusercontent.com/6097524/67098788-1c742f00-f1bd-11e9-9160-890fad87a90d.png)

**Additional information**
PrestaShop version: 1.6.1.23 - 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-10-18 13:36
Hi @Hlavtox,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

Have you the same issue with PS1.7?

Thanks!

**Comment by Hlavtox** [comment] 2019-10-18 13:38
@khouloudbelguith Accidentaly pressed enter, now the bug report is finished :-D.

Yes, it is the same. Test it on 1.7.6.1.

**Comment by Hlavtox** [comment] 2019-10-18 13:45
@khouloudbelguith Real world example:

Searching "Black sink with a drainer".

**Currently, returns all black stuff, all sinks with drainer, even stainless ones.** - 300 products!!


**After my fix, how it should be. Returns all black sinks with a drainer** - 12 products
![fixed](https://user-images.githubusercontent.com/6097524/67099522-66114980-f1be-11e9-9372-fb3fbfcaa09a.JPG)

**Comment by khouloudbelguith** [comment] 2019-10-18 13:51
@Hlavtox, We are aware of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14350
So, I close it.
Thanks!

PS: we will improve the search mechanism as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14588

**Comment by khouloudbelguith** [comment] 2019-10-18 13:51
Duplicate of #14350

**Closed as completed by khouloudbelguith** 2019-10-18 13:51 UTC
Labels: Duplicate, Search, 1.7.6.1

**Comment by Hlavtox** [comment] 2019-10-18 13:58
@khouloudbelguith Ahhh I see. 

But, can you ping the core developers, because, maybe somebody can change this for the time being, until the search mechanism will be done?

I can provide you with the modified file so somebody can pull it.

**Comment by khouloudbelguith** [comment] 2019-10-18 14:00
@Hlavtox, About your code suggestion, would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by Hlavtox** [comment] 2019-10-18 14:20
@khouloudbelguith Made a PR #16023
