### ISSUE TITLE
the product is offline , the redirection page doesn't appear on FO 

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#33584] opened 2023-08-09 13:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when the product is offline , the redirection page doesn't appear on FO .

### Expected behavior

when the product is offline , on FO  the redirection page is well displayed  and not the product page . 

### Steps to reproduce

1. Go to Catalog > Products 

2. create a new product : 

> -  Product name : test 
> -  status : offline 
>   on SEO  : 
> -  Meta title : test-product
> - Meta description : test-product
> - Friendly URL : test-product

3. In block Redirection page > Use dropdown to choose "Permanent redirection to a category (301)" > Choose "Home accessories" for Target category > Save and publish > Preview ( SEE the product created page is well displayed and not the Redirection page !! ) 
4. same for the other options of  Redirection page  .

See the screen record : 

[Untitled_ Aug 9 2023 12_23 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/0fd6a63e-9f90-4d99-a356-4eeabc38e083)

### PrestaShop version(s) where the bug happened

8.1.1  , 8.0.5

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment] 2023-08-09 14:22
@djoelleuch You are not redirected because you are using the admin preview. Delete `?adtoken=d4e12a062a55e473203662dcaac9b2a5&id_employee=1&preview=1` from the URL to see it like a customer and you will get redirected.

This is expected behavior.

**Comment by MatShir** [comment] 2023-08-10 20:04
+1 from @Hlavtox comment
Otherwise, it won't possible to preview the product and work on it because you will always be redirected.

**Comment by aniszr** [comment] 2023-08-31 08:08
Hello @djoelleuch 

I couldn't reproduce this issue, since the expected behavior is totally correct as mentioned in previous comments!

By clicking on Preview button you are using admin preview which not allow the redirection!

See attached screenrecord :


https://github.com/PrestaShop/PrestaShop/assets/92626242/eda6cbc0-0bfa-417c-8788-fc520180b7ae


We will close this issue.

Thank you

**Closed as not planned by aniszr** 2023-08-31 08:08 UTC
Labels: Bug, FO, SEO & URLs, Invalid, 8.1.x, Products Page
