### ISSUE TITLE
Unexpected error in 'Design > link widget' page

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#32052] opened 2023-04-05 12:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An error appears in the page 'Design > link widget'

![Capture d’écran de 2023-04-03 16-26-42](https://user-images.githubusercontent.com/24647495/230086128-1b8120e5-f04f-47cb-bfd2-1ee570cd3c43.png)

PS : Should be tested in docker

### Expected behavior

The page should be displayed correctly

### Steps to reproduce

1- Go to 'Design > link widget' page
2- See the error

### PrestaShop version(s) where the bug happened

8.1.x , 8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by djoelleuch** [comment] 2023-04-06 11:43
Hi @nesrineabdmouleh  ,
I have tested your issue and I can't reproduce the bug as you can see here :
for PS 8.1.x : OK

[81X.webm](https://user-images.githubusercontent.com/115152460/230366757-2c950003-0c8a-4afa-a88d-01881bb64e02.webm)

for PS 8.0.x : OK

[80X.webm](https://user-images.githubusercontent.com/115152460/230366833-ad61b899-fb72-4832-8dbe-f261538654f3.webm)

Could you please check & feedback ^
Thank you !

**Comment by 0x346e3730** [comment] 2023-04-06 11:49
I cannot reproduce the issue either on 8.0.x

**Comment by 0x346e3730** [comment] 2023-04-06 12:07
And neither on 8.1.x 
![image](https://user-images.githubusercontent.com/28731165/230374267-b72db68d-35b1-4288-9d89-73c5c3d7ea62.png)

**Comment by Progi1984** [comment] 2023-04-11 13:52
Fixed by @jolelievre in #32112

**Closed as completed by Progi1984** 2023-04-11 13:52 UTC
Labels: Bug, 8.0.x, Regression, Fixed, PR available, Detected by TE, Docker
