### ISSUE TITLE
Inaccurate stock values for products with variations

### ISSUE THREAD

**Issue by jonpontet** [PrestaShop/PrestaShop#20531] opened 2020-08-11 07:33 UTC
#### Describe the bug

This issue only appears to pertain to products that have variations.

The consequence of such products is multiple lines in the stock_available table.

Thus, we have different stock values in every location in the dashboard: Product List, Product Details, Statistics,  Stock Management.

The values match each other on the Product Details and Stock Management -  and **these are correct**

The values match each other on the Product List and Statistics page -  but **these are NOT correct**

[Raised on Presta forum also](https://www.prestashop.com/forums/topic/1029297-inconsistent-product-stock-values/)

#### Expected behavior

I expect product stock to be accurate and consistent in all places in the backoffice

#### Steps to Reproduce

This is my un-tested assumption after our experience:

1) Create a normal product
2) Your product has stock, you make some sales
3) You then add a single variation to this product - so it is the same product but you will now have the variation select on the frontend (product page) e.g. a variation for weight or quantity
4) You make some more sales

In theory now you will have inconsistent stock values as per above

I will try to re-create this scenario to valid the steps

**Screenshots**

![Annotation 2020-08-07 121009](https://user-images.githubusercontent.com/20968408/89869661-f4731380-dbb4-11ea-8b2c-c191609c989f.png)

This shows a standard product without variations

![Annotation 2020-08-07 120845](https://user-images.githubusercontent.com/20968408/89869673-f76e0400-dbb4-11ea-8c90-1b9c7569a9ba.png)

This shows a product with variations and consequently multiple rows in stock_available table.

For us the correct value (for variations) is the row with the highest id_stock_available.

**So it could be that the solution is to match the id_product and retrieve the values from the row with the highest id_stock_available.**

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by ngodefroy** [comment] 2020-08-11 13:48
Hello @jonpontet ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12814.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed** 2020-08-11 14:03 UTC
Labels: Bug, Minor, BO, Duplicate, Stocks, 1.7.7.x, 1.7.6.5

**Comment by ngodefroy** [comment] 2020-08-11 14:05
Duplicate of #12814

**Comment by jonpontet** [comment] 2020-08-11 17:19
@ngodefroy ah sorry for the duplication - I did not find this bug when looking before submitting this.
