### ISSUE TITLE
Not Receiving email from Prestashop

### ISSUE THREAD

**Issue by kristelocampo** [PrestaShop/PrestaShop#30452] opened 2022-11-30 15:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I don't receive any email from PrestaShop Mail Alerts and also with the configuration in the advance parameters.
I change everything, trying to uninstall and install the module, change a personal email just to check and also tried the zip file from the GitHub itself. 

Our host is receiving emails from other person, but not with PrestaShop.

I hope you can fix the bug as soon as possible.

I have 2 websites with the version of 1.6.1.24 and 1.7.8.7.
Neither of the two are working.

Here are the websites:
hifi-video.fr
sono-visio.fr 

### Expected behavior

It usually sends email if there is a new order from the website.

### Steps to reproduce

Go to Advance Parameter → Email → Test configuration 
Press Send email Test : but no email has been sent

Modules → Mail alerts → Merchant Notification → all possible email address

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by HanaRebaiQA** [comment] 2022-11-30 15:38
Hello @kristelocampo 

Thanks for your report. 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/28014
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank You!

**Comment by HanaRebaiQA** [comment] 2022-11-30 15:39
Duplicate of [#28014 ](https://github.com/PrestaShop/PrestaShop/issues/28014)

**Closed as completed by HanaRebaiQA** 2022-11-30 15:38 UTC
Labels: Bug, Duplicate, Invalid
