### ISSUE TITLE
Faceted search modules slider got problem for high value price

### ISSUE THREAD

**Issue by wahono77** [PrestaShop/PrestaShop#19167] opened 2020-05-16 18:04 UTC
Faceted search modules slider got problem for high value price, it's maximum max slider range is 999999

After I change table ps_layered_price_index, it's OK
- price_min and price_max from DECIMAL (11, 9) to FLOAT

regards

**Comment by sowbiba** [comment] 2020-05-18 10:21
Thanks @wahono77 for your report

Please follow our bug report template https://github.com/PrestaShop/PrestaShop/issues/new?template=bug_report.md 

We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don’t know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

**Comment by florine2623** [comment] 2020-06-08 07:45
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-08 07:45 UTC
Labels: No change required
