### ISSUE TITLE
the weight does not stay in memory it works a few times,

### ISSUE THREAD

**Issue by jasonchemama** [PrestaShop/PrestaShop#10442] opened 2018-09-14 22:14 UTC
**Describe the bug**
the weight does not remain in memory it works a few times, and then after no, in the card produced in the declensions and so when there is a command is not good.
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.2.4
PHP version: 7.1.21

**Comment by khouloudbelguith** [comment] 2018-09-17 09:35
Hi @jasonchemama,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - steps to reproduce the issue in a new comment
 - screenshots

Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-18 09:27
Hi @jasonchemama,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2018-10-18 09:27 UTC
Labels: 1.7.2.4, No change required
