### ISSUE TITLE
PS 1.7.6 - Error on auto cart rule when free shipping is active

### ISSUE THREAD

**Issue by WorldSellers** [PrestaShop/PrestaShop#16076] opened 2019-10-23 09:17 UTC
**Describe the bug**

When you have 2 cart rules without code (automatic add on the cart) but with different priority and one of them have a free shipping a message with no carrier available for this address is displayed on the checkout on the carrier section yet there are carrier available.
This case is also reproducing when the cart rule with free shipping has a code.

**To Reproduce**

With a new PS 1.7.6 installation with demo products

1 - create 2 cart rule without code but with a priority 5 and 10 
     1.1 - the cart rule with priority 5 have a free shipping + gift
     1.1 - the cart rule with priority 5 have gift
2 - the both cart rules are incompatibles !!
3 - Add a product on your cart 
4 - when you check your cart you must have the  gift + free shipping => cart displaying is ok
5 - go to the checkout and on the section carrier you can't select one

=> when you have a free shipping on a cart rule but you have an auto cart rule you have always this bug ...

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: tested on 7.1 and 7.2

**Comment by khouloudbelguith** [comment] 2019-10-23 10:30
Hi @WorldSellers,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2
We are aware of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/11172
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-23 10:31
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/11172

**Closed as completed by khouloudbelguith** 2019-10-23 10:30 UTC
Labels: Duplicate
