### ISSUE TITLE
Bloc paiement

### ISSUE THREAD

**Issue by andreepi** [PrestaShop/PrestaShop#12979] opened 2019-03-20 13:07 UTC
**Describe the bug**

Bloc complètement inactif.
Réinitialisation faite sans succès

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![image](https://user-images.githubusercontent.com/48160466/54686410-82aaad80-4b19-11e9-891a-483b4c2ba9dc.png)

**Additionnal information**
PrestaShop version: 1.6.1.18
PHP version: N/A

**Comment by marionf** [comment] 2019-03-20 13:27
Hello @andreepi 

Your issue is a duplicate of #12978 so I close it.

Regards

**Closed as completed by marionf** 2019-03-20 13:27 UTC
Labels: Duplicate
