### ISSUE TITLE
Hook actionProductUpdate called multiple times in Admin Web GUI BO v2 Product page

### ISSUE THREAD

**Issue by panariga** [PrestaShop/PrestaShop#32204] opened 2023-04-19 07:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When saving changes to product from admin gui, hook 'actionProductUpdate' is called multiple times.
12 times for v2 Product page.
Moreover: 1st call contains old product data in $params, next calls contains new data.

when calling $product->update(); from php code, there is no issues: 1 call of hook, new data in $params.

I made counter in my module. Module object constructs only once during product update. But hook executed 12 times in v2 Product page.

### Expected behavior

1 call to hook, new data in $params.

### Steps to reproduce

Change product and save in BackOffice when using v2 Product page
Use counter in module that registered to hookActionProductUpdate

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

v2 Product page

**Comment by AureRita** [comment] 2023-04-20 10:40
Hi @panariga 

Thank you for your report, can you give us your module to test the number of time the hook is called ? 

Waiting for your answer

**Comment by panariga** [comment] 2023-04-20 11:06
you can check it on any module which registered this hook
my sample code:

```
use Symfony\Component\Filesystem\Filesystem;
    public function __construct() {
 $this->counter = 1;
```

```
public function hookActionProductUpdate($params) {
  $fs = new Filesystem();
  $fs->dumpFile(__DIR__.DIRECTORY_SEPARATOR .$this->counter.'-test.json', json_encode($params, 384));
  $this->counter ++;
     }
```


Then update any info in product via web admin and save it.
+12 dump files in module directory

**Comment by AureRita** [comment] 2023-05-04 10:15
Hi @panariga 

Thank you, I try to reproduce your issue with the provided information but I can't reproduce it as you can see : 

[Untitled_ May 4, 2023 11_00 AM.webm](https://user-images.githubusercontent.com/100699445/236159453-b77789d6-082c-41a9-9e5a-cf65ad63606d.webm)

Did I miss something ? 

Waiting for your feedback

**Comment by panariga** [comment] 2023-05-04 10:39
public function __construct should be inside Class.
Code that I have provided as example should be included in some module,
which instantiated during product update

**Comment by Matt75** [comment] 2023-05-04 10:54
This is a common behavior for hooks, not specific to product page.
Same for hook `actionCartSave` for example.

The common practice is to compute a checksum of fields that you want follow up to detect when changes require to push actions on your module.

**Comment by panariga** [comment] 2023-05-04 11:04
But there is no issues with old product page. So this is something
wrong. If it makes 12 request to server it overloads it without need.
Also such behavior overloads DB with writes and this also multiplies
server load if replication us used

**Comment by panariga** [comment] 2023-05-04 11:11
Also the first hook call provides outdated info - old product data,
without updates.
While it may be a useful feature - if a hook receives old and new
data, there may be internal logic if further action is really needed.
But such behavior must be documented and generalised - i.e. all
product updates should do this, not only called from BO gui.
For now it seems like a bug, not a feature

**Comment by hibatallahAouadni** [comment] 2023-05-09 06:58
Hello @panariga 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks @Matt75 for your quick reply 🙏 

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-09 06:58 UTC
Labels: Bug, BO, Hook, Invalid, 8.0.3
