### ISSUE TITLE
Incorrect message in BO if there are 2 payments with shipping fee

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21916] opened 2020-11-13 22:35 UTC
#### Describe the bug
There is one invoice with total amount 144.80 € with two payments, PayPal payment is 99,80 € and Bank transfer is 45,00 €. The order was fully refunded.
There is displayed incorrect total amount 135.00 € in more places in BO. The amount 135.00 € is price for goods and "missing" 9,80 € is price for shipping.

PS displays incorrect amounts in these cases: 

**1. BO >message in the section Payment**
![image](https://user-images.githubusercontent.com/33311857/99126280-222d8580-2606-11eb-95e3-315f683ecc24.png)

**2. BO > Total amount in order header**
![image](https://user-images.githubusercontent.com/33311857/99126949-7127ea80-2607-11eb-8c86-087206bd4d18.png)

**3. BO > Order list**
![image](https://user-images.githubusercontent.com/33311857/99127475-b3056080-2608-11eb-9a5e-a9c92790df77.png)

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment] 2020-11-16 09:15
Hello @juraj1000 

I didn't manage to reproduce your issue with PS1.7.6.8, see the attached screen record below:

https://drive.google.com/file/d/1FQ7OlIUcYOWSStzXrFB8dOHiPxbFX4K0/view

Could you please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-04 08:42
Hello @juraj1000 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-04 08:42 UTC
Labels: Bug, BO, Order, No change required, 1.7.6.8
