### ISSUE TITLE
Invisible products created with Webservice

### ISSUE THREAD

**Issue by Themiller12** [PrestaShop/PrestaShop#11682] opened 2018-12-09 23:02 UTC
Hello,

I made a software that synchronizes our inventory management software with Prestashop (1.7) via the Webservice with XML files.

The products are well imported, the stock also **but only in back office**. To be visible in Front Office I have to go to each product click on Save and it appears.

I saw in the database that during the save, the field "position_in_category" takes a value and that's why the product appears in Front Office.

Could you do something please ? Thank you very much !

___________

1. Send a XML products file to the Webservice (active)
2. You can see the products in your back office
3. You can't find it in front office
4. Just click in back office on one product and it will appears.

___________

PrestaShop version: 1.7.4.4
PHP version: 7

**Comment by khouloudbelguith** [comment] 2018-12-10 08:48
Hi @Themiller12,

Thanks for your report.
I did not manage to reproduce the issue with 1.7.5.0
I attached a video record
[webservice_Product.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2662285/webservice_Product.webm.zip)
I used this script

```
<html><head><title>CRUD Tutorial - Create example</title></head><body>
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 10/12/18
 * Time: 08:24
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop/');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');

try {

    $webService= new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
    $xml = $webService->get(array('url' => PS_SHOP_PATH.'/api/products?schema=blank'));

    $product = $xml->children()->children();
    $product->price = 99;
    $product->wholesale_price = 89;
    $product->active = '1';
    $product->advanced_stock_management = '1';
    $product->on_sale = 0;
    $product->show_price = 1;
    $product->available_for_order = 1;

    $product->name->language[0][0] = "Produit webservice test test 1750";
    $product->name->language[0][0]['id'] = 1;
    $product->name->language[0][0]['xlink:href'] = PS_SHOP_PATH . '/api/languages/' . 1;

    $product->description->language[0][0] = "Description produit webservice";
    $product->description->language[0][0]['id'] = 1;
    $product->description->language[0][0]['xlink:href'] = PS_SHOP_PATH . '/api/languages/' . 1;

    $product->description_short->language[0][0] = "Descr. courte";
    $product->description_short->language[0][0]['id'] = 1;
    $product->description_short->language[0][0]['xlink:href'] = PS_SHOP_PATH . '/api/languages/' . 1;
    $product->reference = "ref_product_webservice";
    $product->unit_price_ratio = 10.000000;
    $product->depends_on_stock = 0;

    $category_id = 2;
    $product->associations->categories->addChild('category')->addChild('id', $category_id);
    $product->id_category_default = $category_id;

    //
    $opt = array('resource' => 'products');
    $opt['postXml'] = $xml->asXML();
    $xml = $webService->add($opt);
}
catch (PrestaShopWebserviceException $ex) {
    echo "Error:<br>";
    echo  $ex->getMessage();
    exit(1);
}

?>
</body></html>
```

Thanks to check & feedback.

**Comment by Themiller12** [comment] 2018-12-10 18:44
Hello, 

Thank you for your answer ! I made a video to explain you : https://www.youtube.com/watch?v=qMBMHuhGVs0

I send a XML file like this : 

`<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <product>
    <id_category_default>21</id_category_default>
    <id_shop_default>/>
    <reference>03133</reference>    
    <ean13>2902711031336</ean13>
    <state>1</state>
    <minimal_quantity>1</minimal_quantity>
    <price>54.17</price>
    <wholesale_price>39<wholesale_price/>
    <active>1</active>
    <on_sale>0</on_sale>
    <redirect_type>404</redirect_type>
    <available_for_order>1</available_for_order>
    <show_price>1</show_price>
    <link_rewrite>
      <language id="1">routeur-wifi-linksys</language>
    </link_rewrite>
    <name>
      <language>Routeur Wifi 1200 Mbps LINKSYS EA6350 -Dual-Band</language>
    </name>
    <description_short>
      <language>Pour plus de renseignements, contactez-nous !</language>
    </description_short>
  </product>
</prestashop>
`
Thank you !

**Comment by khouloudbelguith** [comment] 2018-12-11 10:30
@Themiller12, you have an issue with your script with the XML SENT.
Have you tried with my script?
I did not manage to reproduce the issue, I attached a video record.
https://drive.google.com/file/d/1-1ty52eLvQJX1RtH-jhCDp40TwLBBBc9/view
You need to check your script.
Thanks!!

**Comment by Themiller12** [comment] 2018-12-11 11:28
> 
> 
> @Themiller12, you have an issue with your script with the XML SENT.
> Have you tried with my script?
> I did not manage to reproduce the issue, I attached a video record.
> https://drive.google.com/file/d/1-1ty52eLvQJX1RtH-jhCDp40TwLBBBc9/view
> You need to check your script.
> Thanks!!

Ok it works if I add associations/category in my XML... Thank you !
But I think devs should simplify this webservice, we have to set 2 times the category, for the stock we can't set it directly we have to send the product first, then get the ID and send an other XML to set the stock.. It's really hard if you can't use the PHP library (with XML POST/PUT). I managed to run my software by visiting at least 200 forums and after 2 months.

**Comment by khouloudbelguith** [comment] 2018-12-11 11:36
@Themiller12, we are glad that your issue is solved.
We have a lot of work with webservice issues, It is planned to fix [webservice](https://github.com/PrestaShop/PrestaShop/issues/10069) issues in PS 1.7.6.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-11 11:36 UTC
Labels: FO, Webservice, No change required
