### ISSUE TITLE
Error on generating invoice

### ISSUE THREAD

**Issue by maniot** [PrestaShop/PrestaShop#23724] opened 2021-03-22 12:30 UTC
#### Describe the bug

when an order contains a specific price Prestashop throws an error when trying to generate an invoice in BO order list.
error: Invalid $number parameter: "" cannot be interpreted as a number [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]

#### Expected behavior
When clicked on icon in order list Prestashop is supposed to generate an invoice pdf
For orders **without** product with specific prices, the invoice is generated normally.

#### Steps to Reproduce

1. create a product with a special price.
2. place an order containing this product
3. go to backoffice into orders --> order list and generate invoice pdf for this order

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-03-22 14:41
Hello @maniot 

I didn't manage to reproduce your issue with PS1.7.7.1 and PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1SkKnUbJxz6MTzk0T08h1SMgYCi5eE6Yv/view

Please check and feedback.
Thanks!

**Comment by maniot** [comment] 2021-03-22 22:15
In order to be able to print the invoice i edited the database ps_order_detail for this order and changed the amounts accordingly to orders that didn't have specific prices, after that i was able to generate the invoice correctly.
The site is in multistore. I used the icon in the orders list like in the attached screenshot.
Best regards,
Niek
![screenshot-the-dreamstore com-2021 03 22-23_08_27](https://user-images.githubusercontent.com/2451560/112065144-71f7fc80-8b64-11eb-9f76-2127c44c4a88.png)

**Comment by hibatallahAouadni** [comment] 2021-03-24 17:20
Hello @maniot 

Even when I enable the multistore and create an order with discounted product, generating the invoice and downloading it with the icon, still can't reproduce your issue.

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module or override problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-24 17:20 UTC
Labels: Bug, BO, Can't reproduce, Order, Invoices, Catalog price rules, 1.7.7.1
