### ISSUE TITLE
BO - Product comments module - An exception is displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23411] opened 2021-02-25 15:12 UTC
#### Describe the bug

When using PHP7.4, in the BO > Modules manager > Productcomments configuration page, an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/109173207-e321db00-7783-11eb-8827-5dc8e3d396ac.png)

#### Steps to Reproduce

1. Go to BO > Modules > Module Manager page
2. Search for the productcomments module v4.2.1 
3. Click on configure

![image](https://user-images.githubusercontent.com/16067358/109173415-1a908780-7784-11eb-87e7-1630a91fcc83.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.4

It is ok with PHP7.1

**Comment by PierreRambaud** [comment] 2021-02-25 16:54
It's a duplicate of #23403

When you fix it, it fixes it for all HelperList error (which occurs on line 705)

**Comment by PierreRambaud** [comment] 2021-02-25 17:14
Duplicate of #23403

**Closed as completed by PierreRambaud** 2021-02-25 17:14 UTC
Labels: Bug, develop, Minor, BO, Duplicate, Regression, Productcomments
