### ISSUE TITLE
Employee profile dropdown wrong position in migrated pages

### ISSUE THREAD

**Issue by rokaszygmantas** [PrestaShop/PrestaShop#12448] opened 2019-02-06 09:18 UTC
**Describe the bug**
Employee dropdown is positioned incorrectly in migrated pages

**To Reproduce**
1. Go to back office, go to any migrated page, e.g. `admin-dev/index.php/configure/shop/preferences/preferences`
2. Click on your profile picture in the top right
3. See that the account dropdown is almost not visible and positioned too much to the right.

**Screenshots**
https://prnt.sc/mhb01k

**Additionnal information**
PrestaShop version: 1.7.6, develop branch

**Comment by matks** [comment] 2019-02-06 09:25
@rokaszygmantas Is it a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12333 ?

**Comment by khouloudbelguith** [comment] 2019-02-06 09:34
@matks, yes, it is a duplicate.
It is the same issue reproduced in the develop branch (PS1.7.6.0).
@rokaszygmantas, we are aware of this issue, it is added to our debug roadmap.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request
Your ticket is a duplicate of #12333
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-06 09:34
Duplicate of #12333

**Closed as completed by khouloudbelguith** 2019-02-06 09:34 UTC
Labels: Duplicate

**Comment by rokaszygmantas** [comment] 2019-02-06 09:54
ah yes sorry, didn't notice it was already reported
