### ISSUE TITLE
Cannot update core modules

### ISSUE THREAD

**Issue by gpierinipg** [PrestaShop/PrestaShop#37602] opened 2024-12-07 09:10 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi everyone!

Prestashop Version: 8.2.0
Problem: cannot update core modules:

- alert by email
- tree link of categories
- contact modul
- search by aspects

As soon as I click on "update" button gof any of these modules in module manager, I get the error: **"Could not perform action update for module undefined"**

Thanks,
Giacomo

### Steps to reproduce

1. Login
2. go to module manager
3. updates
4. click on "update" button of each module.

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

 8.1.30

### Your company or customer's name goes here (if applicable).

Koala Viaggi srl

**Comment by kpodemski** [comment] 2024-12-07 11:33
Hello

You’d need to enable developer mode, and debug ajax request in order to see what really is an error under the hood. You should see something in red coming in the Network tab after you click the Update button. I didn’t have time to write a full instruction but I asked AI to write it. Here’s what you need to do:

1. Open Chrome Developer Tools

	•	Right-click on the web page and select Inspect, or press Ctrl+Shift+I (Windows/Linux) or Cmd+Opt+I (Mac).
	•	Navigate to the Network tab.

2. Filter for XHR Requests

	•	In the Network tab, click on the filter labeled XHR. This will display only AJAX (XMLHttpRequest or Fetch API) requests.
	•	If you don’t see this option, click the Filter icon (a funnel) and type XHR.

3. Trigger the AJAX Request

	•	Perform the action on the page that triggers the AJAX request (e.g., clicking a button or scrolling).
	•	Watch for new entries in the Network tab.

4. Inspect the Request

	•	Find the AJAX request in the list. Look for its Name or URL to identify it.
	•	Click on the request to view detailed information. The details are divided into several tabs:

Headers

	•	Check the Request URL to ensure it is correct.
	•	Verify the Request Method (e.g., GET, POST) is as expected.
	•	Confirm all necessary Headers (e.g., Content-Type, Authorization) are present.
	•	Review the Query Parameters (for GET requests) or Form Data/JSON Payload (for POST requests).

Payload

	•	For POST or PUT requests, review the payload (e.g., form data, JSON) under the Payload tab. Ensure the data being sent matches expectations.

Response

	•	Check the Response tab to see the server’s response. This will often show errors, such as missing data or an invalid format.
	•	If the response is not what you expected, debug the server-side code handling the request.

5. Check for Errors

	•	Look for a Status Code under the Headers tab:
	•	200: Success.
	•	400: Client-side error (e.g., bad request, invalid input).
	•	401: Unauthorized (check authentication tokens or credentials).
	•	404: Not found (check the URL).
	•	500: Server error (check server logs).
	•	If the request failed, Chrome will display an error message in red in the Network tab.

**Comment by gpierinipg** [comment] 2024-12-09 09:47
Hi!

When clicking on the update button I get a 403 error!

![Image](https://github.com/user-attachments/assets/08d84246-17f5-4e72-ae3c-53c27c199dbc)
![Image](https://github.com/user-attachments/assets/5ba4203a-fd3b-405f-bbe5-21ce57510103)
![Image](https://github.com/user-attachments/assets/e4f013a4-130c-41ff-9894-5332af74ec03)

**Comment by paulnoelcholot** [comment] 2024-12-10 10:54
Hello @gpierinipg 

I try to reproduce your issue but as you can see, I can't : https://www.loom.com/share/33db2c269090444db0f1852292ca388e?sid=33c38506-5edd-48aa-91ae-b2d48cfc446e

Did I miss something?

Thanks for your feedback

**Comment by gpierinipg** [comment] 2024-12-10 15:08
Hi!

thanks for your time! That’s the problem! One I day I could update modules… the following one I got this error… Don’t know why..

 

 

Giac

 

 

Il presente messaggio, inclusi gli eventuali allegati, ha natura aziendale e potrebbe contenere informazioni confidenziali e/o riservate. Chiunque lo ricevesse per errore, è pregato di avvisare tempestivamente il mittente e di cancellarlo.
E’ strettamente vietata qualsiasi forma di utilizzo, riproduzione o diffusione non autorizzata del contenuto di questo messaggio o di parte di esso.
Pur essendo state assunte le dovute precauzioni per ridurre al minimo il rischio di trasmissione di virus, si suggerisce di effettuare gli opportuni controlli sui documenti allegati al presente messaggio. Non si assume alcuna responsabilità per eventuali danni o perdite derivanti dalla presenza di virus.

***
This email (including any attachment) is a corporate message and may contain confidential and/or privileged and/or proprietary information. If you have received this email in error, please notify the sender immediately, do not use or share it and destroy this email. Any unauthorised use, copying or disclosure of the material in this email or of parts hereof (including reliance thereon) is strictly forbidden.
We have taken precautions to minimize the risk of transmitting software viruses but nevertheless advise you to carry out your own virus checks on any attachment of this message. We accept no liability for loss or damage caused by software viruses.
For the conduct of investment business in the UK, the Company is authorized by Bank of Italy and regulated by the Financial Services Authority.

 

 

 

Da: Paul-Noël ***@***.***>
Risposta: PrestaShop/PrestaShop ***@***.***>
Data: martedì 10 dicembre 2024 alle ore 11:54
A: PrestaShop/PrestaShop ***@***.***>
Cc: gpierinipg ***@***.***>, Mention ***@***.***>
Oggetto: Re: [PrestaShop/PrestaShop] Cannot update core modules (Issue #37602)

 

Hello @gpierinipg

I try to reproduce your issue but as you can see, I can't : https://www.loom.com/share/33db2c269090444db0f1852292ca388e?sid=33c38506-5edd-48aa-91ae-b2d48cfc446e

Did I miss something?

Thanks for your feedback

**Comment by paulnoelcholot** [comment] 2024-12-10 15:13
Hello @gpierinipg ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-12-10 15:13 UTC
Labels: Bug, Can't reproduce, Modules, Module manager, Module, 8.2.x
