### ISSUE TITLE
cms

### ISSUE THREAD

**Issue by valdemesio** [PrestaShop/PrestaShop#29401] opened 2022-08-20 14:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

no idioma portugues ,não da para editar o modulo cms

### Expected behavior

que ele pudesse ser editavel

### Steps to reproduce

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### PrestaShop version(s) where the bug happened

prestashop 8

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Lista de ligações

**Comment by PrestaEdit** [comment] 2022-08-21 09:16
Hi @valdemesio,

Please, do this in english. I was able to translate/understand your issue, but the main language to communicate on this project is the english.

Also, about your issue, you need to enable the debug mode in order to see the error behind the error 500.
Could you do a screeen capture of it, in order to allow us to determinate where is the issue ?

**Comment by hibatallahAouadni** [comment] 2022-08-22 08:00
Hello @valdemesio 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: thanks @PrestaEdit for your quick reply :pray: 
PS: @valdemesio your issue is a duplicate of #27603

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-22 08:01
Duplicate of #27603

**Closed as completed by hibatallahAouadni** 2022-08-22 08:00 UTC
Labels: Bug, Duplicate, Invalid

**Comment by valdemesio** [comment] 2022-08-23 12:13
can't edit the cms module of prestashop 8 in portuguese, it gives error

**Comment by PrestaEdit** [comment] 2022-08-23 12:14
> can't edit the cms module of prestashop 8 in portuguese, it gives error

You already say it, yes.

Could you add a screen capture of the error while having enabled the debug mode, please ?

**Comment by valdemesio** [comment] 2022-08-23 12:16
I had to uninstall prestashop 8, because on my hosting, it was showing the administrative area and not the front page

**Comment by valdemesio** [comment] 2022-08-23 12:18
esse é mais um erro que estava acontecendo, perdi o final de semana tentando consertar, voltei para 1.7.8

**Comment by valdemesio** [comment] 2022-08-23 12:19
I keep thinking, I'm building a whole structure on top of 1.7.8, but I realize that when I migrate I'm going to lose a lot

**Comment by valdemesio** [comment] 2022-08-23 12:21
joomla, usa akeeba, muito fácil, útil e sem perdas, o prestashop deveria pensar nisso

**Comment by valdemesio** [comment] 2022-08-23 12:22
Guys, from what I read on the forums, many give up prestashop, due to these changes, many lose their jobs for years

**Comment by PrestaEdit** [comment] 2022-08-23 12:24
Can I asking you to stop spamming this issue, as it's not a chat and it could notify every answer to each people trying helping you without having nothing from you to do it, maybe ?

Thanks a lot.

**Comment by valdemesio** [comment] 2022-08-23 12:26
thank
