### ISSUE TITLE
Multistore Inventory error with reserved product in two stores - Prestashop 8.1.1

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#33865] opened 2023-09-06 15:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It is found that when there is multistore configured in prestashop 8.1.1. The store does not correctly register reserved units with stores that share inventory.

Video: 

https://drive.google.com/file/d/1rDufnrdMA11yy4mEPRjPoRk9-8JpBdUT/view?usp=sharing

It's important that you review the following and don't close this bug lightly without reviewing the following.

It is found that the integrity of the information in the ps_stock_available table is being corrupted because it is not manipulating the physical_quantity column. He was left with the same units of inventory before and after placing the orders.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/42a6ffc7-d90f-43bf-943d-070993ebd46b)

### Expected behavior

It should correctly show reserved units.

Made proposed change to https://github.com/PrestaShop/PrestaShop/pull/32721 and reserved units are displayed correctly. Stock is also reduced, removed, and added correctly. It is recommended to continue with the proposal in that pull request to solve the inventory in multi-store.

See comment: https://github.com/PrestaShop/PrestaShop/pull/32721#issuecomment-1707318365

### Steps to reproduce

Product with combination and add 20 units.
Place an order in Store 1 with 5 units.
Place an order in Store 2 with 5 units.

Go to BackOffice to Catalog - Stock

Find the reference.
Available and physical units appear correctly but reserved units appear incorrectly.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment] 2023-09-07 16:07
Hello @ocio87 

Thanks for creating the PR and the issue :rocket: 
But why you create this issue while it's already reported here #13210 and you already knew about it?

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-26 09:57
Hello @ocio87 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #13210. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-26 09:57
Duplicate of #13210

**Closed as completed by hibatallahAouadni** 2023-09-26 09:57 UTC
Labels: Bug, BO, Duplicate, Stocks, Multistore, Invalid, 8.1.x
