### ISSUE TITLE
EntityMapper test for shop id uses the wrong table

### ISSUE THREAD

**Issue by sergiosgc** [PrestaShop/PrestaShop#36003] opened 2024-04-23 16:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Whenever a product translation is edited and the translation does not exist in the product_lang table, loading the Product object fails because EntityMapper is testing against the wrong table. The edit operation subsequently fails.

The offending code is here: https://github.com/PrestaShop/PrestaShop/blob/2ae8fe91cf0cf65470d9e301af3b6387f18fa39c/src/Adapter/EntityMapper.php#L64

A where clause is added against the product_lang table, which is left joined, so the column may be null. It'd be best to add the where clause against the table referred in this if clause code: https://github.com/PrestaShop/PrestaShop/blob/2ae8fe91cf0cf65470d9e301af3b6387f18fa39c/src/Adapter/EntityMapper.php#L70 when available. It is the product_shop table and, although also left-joined, it is more likely to be populated than the translation table.

Something like:
```
            // Get lang informations
            if ($id_lang && isset($entity_defs['multilang']) && $entity_defs['multilang']) {
                $sql->leftJoin($entity_defs['table'] . '_lang', 'b', 'a.`' . bqSQL($entity_defs['primary']) . '` = b.`' . bqSQL($entity_defs['primary']) . '` AND b.`id_lang` = ' . (int) $id_lang);
                if ($id_shop && !empty($entity_defs['multilang_shop']) && !Shop::isTableAssociated($entity_defs['table'])) {
                    $sql->where('b.`id_shop` = ' . (int) $id_shop);
                }
            }

            // Get shop informations
            if (Shop::isTableAssociated($entity_defs['table'])) {
                $sql->leftJoin($entity_defs['table'] . '_shop', 'c', 'a.`' . bqSQL($entity_defs['primary']) . '` = c.`' . bqSQL($entity_defs['primary']) . '` AND c.`id_shop` = ' . (int) $id_shop);
                if ($id_lang && isset($entity_defs['multilang']) && $entity_defs['multilang'] && $id_shop && !empty($entity_defs['multilang_shop'])) {
                    $sql->where('c.`id_shop` = ' . (int) $id_shop);
                }
            }
```

I'd write a pull request, but it is best this issue is tackled by someone more familiar with Prestashop's data model. For example, it may be best to move the shop id tests from the where clause to the join clauses. I do not have enough experience or knowledge over Prestashop to evaluate that.

### Expected behavior

Product translations should be editable even when the product is missing from the product_lang table.

### Steps to reproduce

Create a product, remove a translation from the database, try to edit the product in the language that you removed. Editing fails, the ajax request returns HTML instead of JSON.

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

Irrelevant

### If your bug is related to a module, specify its name and its version

Bug manifested in a site with IqitElementor, but the issue is a flaw in core Prestashop code.

### Your company or customer's name goes here (if applicable).

Irrelevant

**Comment by Hlavtox** [comment] 2024-04-24 10:06
Entry in the _lang table MUST always exist. If it doesn't, your database is corrupted and must be fixed.

**Comment by florine2623** [comment] 2024-04-24 12:30
Hello @sergiosgc ,

In which case the translation could be removed from the database ? Unless done manually ?

**Comment by sergiosgc** [comment] 2024-04-24 15:36
In my case, it happened when a new language was enabled.

**Comment by florine2623** [comment] 2024-04-24 15:44
I tried with some modified steps :

Create a product
Download a new language : Spanish
Edit the product in Spanish
Delete the language 
Edit the product again in initial language
-> No problem with the editing of the product ✅ 

Is there another way to reproduce your issue ?

**Comment by florine2623** [comment] 2024-05-13 09:49
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2024-05-13 09:49 UTC
Labels: Bug, CO, Translations, 1.7.8.0
