### ISSUE TITLE
AH01630: client denied by server configuration

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#13262] opened 2019-04-10 08:35 UTC
Prestashop 1.7.5.1 on debian 9.8 php 7.2.17, mod_pagespeed installed, memcached installed.
my error_log have many entries like: `[authz_core:error] [pid 2045:tid 140513881618176] [client 37.10.95.106:37306] AH01630: client denied by server configuration: uri /img/x100asait-logo-1534233635.jpg.pagespeed.ic.pU-Ok95SSs.webp, referer: https://www.100asa.it/it/armadi-rack/37186-patton-1001mp2mpe-staffa-per-montaggio-a-rack.html`
in htaccess on img folder I've add webp to files granted, but issue remain
attached my htaccess on img folder
[htaccess.txt](https://github.com/PrestaShop/PrestaShop/files/3062809/htaccess.txt)

**Comment by khouloudbelguith** [comment] 2019-04-10 09:38
Hi @centoasa,

Here's the PR: #10347 to solve the issue.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-10 09:38
Duplicate of #10347

**Comment by centoasa** [comment] 2019-04-10 09:47
I'm sorry but my /translation/cldr/ .htaccess ahev already 
`<IfModule mod_authz_core.c>
    Require all granted
</IfModule>`
but as said on #10352 it didn't solve for me

**Comment by khouloudbelguith** [comment] 2019-04-10 10:46
@centoasa, try with this solution: add a directory rule to your main apache config file "/etc/apache2/apache2.conf"
```
<Directory /path/to/my/sites>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>
```
Thanks to check and feedback

**Comment by centoasa** [comment] 2019-04-10 10:53
@khouloudbelguith thanks, but it already present!

**Comment by khouloudbelguith** [comment] 2019-04-10 10:58
@centoasa, could you please check with your host and feedback.

**Comment by centoasa** [comment] 2019-04-10 10:59
maybe similar to #11423?

**Comment by khouloudbelguith** [comment] 2019-04-10 13:44
@centoasa, try to disable the mod_pagespeed and check.

**Comment by centoasa** [comment] 2019-04-10 15:50
changed server, with ubuntu 18.4 (php 7.2.17) without mod_pagespeed and memcached: all seems without this error.

**Comment by khouloudbelguith** [comment] 2019-04-10 15:54
@marionf, what do you think?

**Comment by centoasa** [comment] 2019-04-11 08:33
sorry, but with this new server configuratio (ubuntu 18.4, php 7.2.17 without mod_pagespeed and memcached) back again this issue:
`[Thu Apr 11 10:29:06.645154 2019] [authz_core:error] [pid 44501:tid 139945368860416] [client 2.239.18.43:55998] AH01630: client denied by server configuration: /var/www/vhosts/100asa.it/httpdocs/img/yealink, referer: https://www.100asa.it/it/telefoni/863-yealink-t23g-gigabit-telefono-ip.html
`

**Comment by marionf** [comment] 2019-04-12 09:55
Don't know, let's ask to @PrestaShop/prestashop-core-developers

**Comment by PierreRambaud** [comment] 2019-04-12 13:53
What version of apache are you using?
Can you show us your apache and you virtualhost configuration?

**Comment by PierreRambaud** [comment] 2019-04-12 13:54
This can maybe help you to understand why it fails: https://linux.101hacks.com/unix/client-denied-by-server-configuration/

**Comment by centoasa** [comment] 2019-04-12 14:17
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2019-04-03T13:22:37
maybe I understood: the error refer to a folder that does not exist! I don't understand why Prestashop wants to save the images in that folder. In any case I have just created it, and it seems that the error has disappeared. I continue to monitor the situation, in case I let you know.

**Comment by sanctusmob** [comment] 2019-04-19 09:46
I have the same problem
Dedicated server with plesk
Server information Linux #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
PrestaShop version: 1.7.5.1 
Server software version: Apache
PHP version: 7.1.28 

I think the problem is that mod_pagespeed save files in /var/cache/mod_pagespeed/ and the vhost does not have access there or the rewrite rules for the images are not correct.

**Comment by sanctusmob** [comment] 2019-04-19 10:31
Same problem here.
Dedicated server with plesk
Server information Linux #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
PrestaShop version: 1.7.5.1 
Server software version: Apache
PHP version: 7.1.28 

I think the problem is that mod_pagespeed is using for cache the directory /var/cache/mod_pagespeed/ and the vhost does not have access there or the problem is on the rewrite rules for the images. 

`client denied by server configuration: uri /img/x100asait-logo-1534233635.jpg.pagespeed.ic.pU-Ok95SSs.webp`

this uri exists somewhere on the /var/cache/mod_pagespeed/ and not on the vhost home directory.

**Comment by sanctusmob** [comment] 2019-06-06 13:42
Thanks to #11423
I solve the problem with the log file by editing the /img/.htaccess

```
<IfModule mod_php5.c>
	php_flag engine off
</IfModule>

# Apache 2.2
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
    <Files ~ "(?i)^.*\.(jpg|jpeg|gif|png|bmp|tiff|svg|pdf|mov|mpeg|mp4|avi|mpg|wma|flv|webm|wepb|ico)$">
        Allow from all
    </Files>
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
	Require all granted
	# Deny everything NOT one of the following.
	<FilesMatch ^((?!\.(webp|jpg|jpeg|gif|png|bmp|tiff|svg|pdf|mov|mpeg|mp4|avi|mpg|wma|flv|webm|ico)).)*$>
	       Require all denied
	</FilesMatch>
</IfModule>
```

**Comment by marionf** [comment] 2019-06-06 14:19
@centoasa @sanctusmob this issue can be closed if it's fixed ?

**Comment by centoasa** [comment] 2019-06-06 14:21
for me you @marionf can close. After further investigation I'll let you know.

**Closed as completed** 2019-06-06 14:23 UTC
Labels: Performance, No change required, 1.7.5.1

**Comment by ilyassw** [comment] 2020-08-31 12:46
Hi i actually have the same issue as above but when replaced the .htaccess with the one here all the pictures disappear on my site .
This is the only issue so far i am facing , is there away to remedy it ? thanks

This is the issue i have : 

AH01630: client denied by server configuration: uri /img/tmp/cms/xreceived_1640904842744376.png.pagespeed.ic.RTR0pu8Rpf.webp, referer: https://mydomain.com/admin374xengp1/filemanager/dialog.php?type=1&descending=false&sort_by=&lang=en
--
