### ISSUE TITLE
Unknown locale code: fr-FR  [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0] - Update 1.7.5.1 -> 8.1

### ISSUE THREAD

**Issue by astragor** [PrestaShop/PrestaShop#35541] opened 2024-03-01 23:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello I have tried to Upgrade my shop with 1click Upgrade. And now i have the message when i try to connect to my admin
Unknown locale code: fr-FR
[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]

I have seen past (closed issue) but I haven't found any solution.

### Expected behavior

Connect to my admin

### Steps to reproduce

1-Go to 1click Upgrade
2-Made the upgrade from 1.7.5.1 to 8.1 using Major Version Chanel
3-Reconnect to my admin after Update.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

1 Click Upgrade

**Comment by AureRita** [comment] 2024-03-04 15:21
Hi @astragor 

Thank you for your report. Despite my effort, I can't reproduce your issue as you can see : 

[recording(125).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/0c9c5573-476b-4efa-b665-3bb55f56ffc4)

Even if I install it with my shop in french. 

Instead I have another issue @PrestaShop/tech-council. Did you know why I've this issue, 

Error message : 
[INTERNAL] /var/www/html/pr_autoup/modules/ps_linklist/upgrade/upgrade-3.0.php line 20 - Error: Call to undefined method Ps_Linklist::reset() #0 /var/www/html/pr_autoup/classes/module/Module.php(591): upgrade_module_3_0(Object(Ps_Linklist)) #1 /var/www/html/pr_autoup/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(279): ModuleCore->runUpgradeModule() #2 /var/www/html/pr_autoup/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(246): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->doUpgradeModule('ps_linklist') #3 /var/www/html/pr_autoup/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(75): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(24360, 'ps_linklist', false) #4 /var/www/html/pr_autoup/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run() #5 {main}

@astragor can you tell me if I do something wrong in my method to reproduce your issue ? 

Waiting for feedback

**Comment by paulnoelcholot** [comment] 2024-04-15 10:27
Hello @astragor,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-04-15 10:27 UTC
Labels: Bug, Waiting for author, BO, Autoupgrade, Waiting for dev, 1.7.5.1, Invalid, Module
