### ISSUE TITLE
1.7 AdminImportController::productImport() should be compatible

### ISSUE THREAD

**Issue by vincent-dp** [PrestaShop/PrestaShop#13220] opened 2019-04-05 12:47 UTC
After few imports of products, When I go into adminpanel/imports and I chose a file and then proceed, I go this warning (I'm in debug mode)

> Warning: Declaration of AdminImportController::productImport() should be compatible with AdminImportControllerCore::productImport($offset = false, $limit = false, &$crossStepsVariables = false, $validateOnly = false, $moreStep = 0)

Bellow that main warning I have those:

>  ErrorHandler->handleError(2, 'Declaration of AdminImportController::productImport() should be compatible with AdminImportControllerCore::productImport($offset = false, $limit = false, &$crossStepsVariables = false, $validateOnly = false, $moreStep = 0)', '/var/www/vhosts/presta-demo.decoplus-online.net/httpdocs/presta_demo/override/controllers/admin/AdminImportController.php', 0, array('className' => 'AdminImportController', 'classDir' => '/var/www/vhosts/presta-demo.decoplus-online.net/httpdocs/presta_demo/'))

> in classes/PrestaShopAutoload.php (line 152)
> 
> require_once()
> in classes/PrestaShopAutoload.php (line 152)
> 
> PrestaShopAutoload->load('AdminImportController')
> in vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php (line 151)
> 
> DebugClassLoader->loadClass('AdminImportController')
> spl_autoload_call('AdminImportController')
> in classes/controller/Controller.php (line 208)
> 
> ControllerCore::getController('AdminImportController')
> in classes/Dispatcher.php (line 501)
> 
> DispatcherCore->dispatch()
> in admin846vpgptn/index.php (line 99)

I really don't know how to reproduce it, but I'm stuck and can't import. Because if I turn off debug mode, it only import one product out of 4K at a time.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.16

**Comment by khouloudbelguith** [comment] 2019-04-05 13:36
Hi @vincent-dp,

Could you please check with your host and feedback.

Thanks!

**Comment by vincent-dp** [comment] 2019-04-05 13:39
What would you want me to check?

Edit:
The problem only occurs when I'm in 'All Shops' mode

**Comment by khouloudbelguith** [comment] 2019-04-05 14:44
@vincent-dp,

Could you please try the following steps:
1. check if the following file does exist,
YourStoreRoot/classes/controller/Controller.php
If it exists please try to rename it to Controller.php.del, maybe this file is not implemented correctly.
2. Clear cache.

**Comment by vincent-dp** [comment] 2019-04-08 07:51
Hello, Thank you for answering.
Now I have a 500 error. Weird thing is, if I set dev_mod to true, I can access both my front and back, if I set it to false, I get a 500 on both of them.
Now, I got this error : 
>Attempted to load class "Controller" from the global namespace.
 Did you forget a "use" statement for "Symfony\Bundle\FrameworkBundle\Controller\Controller"?

Even if I rename controller back to controller.php

**Comment by vincent-dp** [comment] 2019-04-08 07:53
I have cleared var/cache folder, now I can access my back office again. But still, if I remove the debug mode, I got a 500.. :(

**Comment by khouloudbelguith** [comment] 2019-04-08 09:37
Hi @vincent-dp,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-08 07:27
Hi @vincent-dp,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-08 07:27 UTC
Labels: BO, Advanced parameters, Import / Export, No change required
