### ISSUE TITLE
Forgotten block inside migrated Order page : Sources

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#18966] opened 2020-05-04 16:08 UTC
#### Describe the bug

When we migrated Order page, we forgot (because we did not it existed) the "Sources" block at the bottom of the page

#### Steps to Reproduce

1. Make an order on FO
2. See how it looks on legacy Order page (for example on 1.7.6), see the "sources" block at the bottom (attached is screenshot)
3. Compare to migrated page

**Screenshots**

<img width="1201" alt="Capture d’écran 2020-05-04 à 18 06 23" src="https://user-images.githubusercontent.com/3830050/80987312-2ba58c00-8e32-11ea-8cf0-9c193a1788cb.png">

**Comment by matks** [comment] 2020-05-04 16:08
Reported by @Robin-Fischer-PS

**Comment by Robin-Fischer-PS** [comment] 2020-05-04 16:23
Thanks @matks ! 

For those who, like me, cannot reproduce this that simply, try these reproduction steps : 

- Activate multistore
- Create a new shop group, which does not share nor customers, nor available quantities to sell
- Create a new shop in this group (importing datas from the main shop)
- Go to FO, make an order (without registering), there should be the "Sources" block on this order on BO now

**Comment by colinegin** [comment] 2020-06-08 08:32
ping @MatShir what should be done with this issue ?

**Comment by matks** [comment] 2020-06-08 09:37
> ping @MatShir what should be done with this issue ?

Fix it

We forgot about it, but I just assigned it to me and I will do it

**Comment by Progi1984** [comment] 2020-06-16 13:59
Fixed by #19697

**Closed as completed by Progi1984** 2020-06-16 13:59 UTC
Labels: Bug, Minor, Order, Regression, Fixed, migration, 1.7.7.0
