### ISSUE TITLE
One order with 2 product with same currier is misteriously split in 2 orders with same DHL currier

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#28611] opened 2022-05-27 09:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A customer have bought 2 different products, that have same curriers, and payed with stripe.
The cart is splitted in 2 orders misteriously.
There is no reason to split a single order in 2 orders if the product have same curriers.
The customer had to pay the shipping cost twice!

CART:
![image](https://user-images.githubusercontent.com/16102074/170673838-d806028c-0e6a-4fa4-8f02-9001f6c61980.png)

ORDER CREATED:
![image](https://user-images.githubusercontent.com/16102074/170673981-40221658-0857-46aa-8147-6fdd1f0f594f.png)

Order 1 details:
![image](https://user-images.githubusercontent.com/16102074/170675063-6b855d31-0d72-4856-99c9-b97dd405ae31.png)

Order 2 details:
![image](https://user-images.githubusercontent.com/16102074/170675209-5eed18e2-f408-494e-b792-8e19078997ae.png)

Item 1 curriers:
![image](https://user-images.githubusercontent.com/16102074/170674566-71113e8c-9b22-430f-aea2-4634f3905981.png)

Item 2 curriers:
![image](https://user-images.githubusercontent.com/16102074/170674712-6b1e0d1e-a3bd-4def-a311-17e04ae61f52.png)

### Expected behavior

When a customer order different product that can be send with same currier the order must be unique not splitted to avoid to pay the same shipping cost twice.

### Steps to reproduce

1) create a cart with different products that can be send with same currier (my case DHL)
2) pay the order and you will see a unique customer order

in this case misteriously it split the ordered 2 product is 2 connected orders make the customer pay the shipping cost twice

### PrestaShop version(s) where the bug happened

1.7.6.7

### PHP version(s) where the bug happened

7.2

**Comment by HanaRebaiQA** [comment] 2022-05-27 10:57
Hello @HartLarsson 

Thanks for your report.
I think that your issue is a duplicate of this one [#15304](https://github.com/PrestaShop/PrestaShop/issues/15304) and maybe so [#9594 ](https://github.com/PrestaShop/PrestaShop/issues/9594)

Could you confirm it ?

Thank you!

**Comment by sLorenzini** [comment] 2022-06-16 07:26
Hello @HartLarsson, 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by sLorenzini** 2022-06-16 07:26 UTC
Labels: Bug, BO, Order, Carriers, 1.7.6.7, Invalid
