### ISSUE TITLE
Button "activate taxes" and "use ecotaxe" not functional

### ISSUE THREAD

**Issue by Jerome08** [PrestaShop/PrestaShop#13771] opened 2019-05-13 12:35 UTC
when i want to activate button "activate taxes" and "use ecotaxe" 
I check the buttons and i save
but when i refresh the page, it is not activated 

**To Reproduce**
1. Go to  internation > taxes
2. Click on activate taxes and use ecotax
3. save
4. refresh the page

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-05-13 12:38
Hi @Jerome08,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/1DFmNERQ6dhR__9TwUvX-Z5MXGPqKfztW/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-12 07:32
Hi @Jerome08,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-12 07:32 UTC
Labels: Bug, BO, Taxes and Prices, No change required, 1.7.5.2
