### ISSUE TITLE
Error on clone website

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#12042] opened 2019-01-07 10:35 UTC
I have made clone website from my current website with (1.7.5.0). I.m not able to access backoffice as well fron-office on clone site.
Getting following error. Can anyone help me to fix it out?

Warning: require(/home/domain.com/public_html/vendor/composer/../symfony/polyfill-ctype/bootstrap.php): failed to open stream: No such file or directory in /home/domain.com/public_html/vendor/composer/autoload_real.php on line 61

Fatal error: require(): Failed opening required '/home/domain.com/public_html/vendor/composer/../symfony/polyfill-ctype/bootstrap.php' (include_path='/home/domain.com/public_html/vendor/pear/pear_exception:/home/domain.com/public_html/vendor/pear/console_getopt:/home/domain.com/public_html/vendor/pear/pear-core-minimal/src:/home/domain.com/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /home/domain.com/public_html/vendor/composer/autoload_real.php on line 61

**Comment by khouloudbelguith** [comment] 2019-01-07 10:49
Hi @Akashvastarpara,

How did you clone your shop?
Did you clone it from this repository https://github.com/PrestaShop/PrestaShop.git?
Thanks!

**Comment by Akashvastarpara** [comment] 2019-01-07 11:12
I have followed this tutorial : [https://www.prestashop.com/en/blog/how-to-migrate-prestashop-to-a-new-server](url)

I have upgraded my prestashop version from 1.7.3 to 1.7.5.0
Then I have tried to make clone of my site to new domain and now getting this error

**Comment by Akashvastarpara** [comment] 2019-01-07 11:18
Last time I was successful with the version 1.7.3 to move it to new domain. But after upgrading to 1.7.5.0 I have followed same procedure but getting error.

**Comment by khouloudbelguith** [comment] 2019-01-07 12:10
Hi @Akashvastarpara,

I did not manage to reproduce the issue with PS1.7.5.0 after upgrade from PS1.7.4.4.
I moved my Project to a new domain without errors.
1. I made a backup for my files & my database
2. I uploaded my store's files to your new server
3. I imported the old store's database to the new server
4. In file /app/config/parameters.php, I configured my PrestaShop site.
4.1. DB_SERVER: database's server;
4.2. DB_NAME: Name of the database from step 5;
4.3. DB_USER: User associated with the database;
4.4. DB_PASSWD: The user's password;
5. in the Table ps_shop_url, I changed with the 
5.1. domain => new domain
5.2. domain_ssl => new domain_ssl
5.3. physical_uri => new physical_uri
6. I cleared cache manually by deleting all the folder into var/cache (prod & dev).

=> OK => no problems.

**Comment by Akashvastarpara** [comment] 2019-01-07 12:37
I have followed same procedure with 1.7.3 two times also tried to full permission to all files and folders.

**Comment by khouloudbelguith** [comment] 2019-01-07 14:20
@Akashvastarpara, about this error
`Fatal error: require(): Failed opening required '/home/domain.com/public_html/vendor/composer/../symfony/polyfill-ctype/bootstrap.php' (include_path='/home/domain.com/public_html/vendor/pear/pear_exception:/home/domain.com/public_html/vendor/pear/console_getopt:/home/domain.com/public_html/vendor/pear/pear-core-minimal/src:/home/domain.com/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /home/domain.com/public_html/vendor/composer/autoload_real.php on line 61`, it looks like you moved one of your folders in your main shop to another location with your FTP client.
You need to check on your FTP client if you have moved any main folder into another folder.
Also, did you changed your mail URL from your shop at seo-traffice?
Thanks!

**Comment by Akashvastarpara** [comment] 2019-01-07 15:31
I will download public_html folder from the current ftp site and upload it on new ftp site.

**Comment by Akashvastarpara** [comment] 2019-01-07 15:33
I was not able to logon in back office so i have not changed mail url. I have changed the details as you have mentioned in steps 4&5

**Comment by khouloudbelguith** [comment] 2019-01-07 15:40
@Akashvastarpara, have you the same errors after these modifications?
Thanks!

**Comment by Akashvastarpara** [comment] 2019-01-08 04:38
I think you was right there will be moved folder into another folder by mistake. I have re-downloaded public_html folder and uploaded via ftp for new domain and followed further steps now new clone site is working.
Thanks for your time @khouloudbelguith

**Comment by khouloudbelguith** [comment] 2019-01-08 07:59
Hi @Akashvastarpara,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-08 07:59 UTC
Labels: BO, No change required, 1.7.5.0

**Comment by MartinxStefan** [comment] 2019-09-03 21:50
Hi, I have the same problem. 1-Click Upgrade stuck, the site is now down. Error:

> Warning: require(.../vendor/composer/../symfony/polyfill-ctype/bootstrap.php): failed to open stream: No such file or directory in .../vendor/composer/autoload_real.php on line 61
> 
> Warning: require(.../vendor/composer/../symfony/polyfill-ctype/bootstrap.php): failed to open stream: No such file or directory in .../vendor/composer/autoload_real.php on line 61
> 
> Fatal error: require(): Failed opening required '.../vendor/composer/../symfony/polyfill-ctype/bootstrap.php' (include_path='.../vendor/pear/pear_exception:.../vendor/pear/console_getopt:/data/web/virtuals/111137/.../vendor/pear/pear-core-minimal/src:.../vendor/pear/archive_tar:.:...') in /.../vendor/composer/autoload_real.php on line 61

Please help

**Comment by khouloudbelguith** [comment] 2019-09-04 10:37
Hi @MartinxStefan,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks!

**Comment by VegaRaveloOscar** [comment] 2020-05-26 17:41
> Hola, tengo el mismo problema. 1-Click Upgrade atascado, el sitio ahora está caído. Error:
> 
> > Advertencia: require (... / vendor / composer /../ symfony / polyfill-ctype / bootstrap.php): no se pudo abrir la secuencia: No existe dicho archivo o directorio en ... / vendor / composer / autoload_real.php en línea 61
> > Advertencia: require (... / vendor / composer /../ symfony / polyfill-ctype / bootstrap.php): no se pudo abrir la secuencia: No existe dicho archivo o directorio en ... / vendor / composer / autoload_real.php en línea 61
> > Error fatal: require (): Se requiere una apertura fallida '... / vendor / composer /../ symfony / polyfill-ctype / bootstrap.php' (include_path = '... / vendor / pear / pear_exception: ... / vendor / pear / console_getopt: / data / web / virtuals / 111137 /.../ vendor / pear / pear-core-minimal / src: ... / vendor / pear / archive_tar:.: ... ') en / ... / vendor / composer / autoload_real.php en la línea 61
> 
> Por favor ayuda

Buenas tardes, me ha pasado lo mismo al migrar mi tienda. ¿Pudiste solucionarlo? Gracias
