### ISSUE TITLE
Webpack error while using Docker

### ISSUE THREAD

**Issue by ks129** [PrestaShop/PrestaShop#20256] opened 2020-07-21 06:09 UTC
#### Describe the bug
When I use `docker-compose up`, then I get error:
```
prestashop-git_1  | > webpack --progress --colors --mode=production
prestashop-git_1  | 
prestashop-git_1  | /var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/bin/cli.js:93
prestashop-git_1  | 				throw err;
prestashop-git_1  | 				^
prestashop-git_1  | 
prestashop-git_1  | Error: Cannot find module 'atob'
prestashop-git_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
prestashop-git_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
prestashop-git_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
prestashop-git_1  |     at require (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
prestashop-git_1  |     at Object.<anonymous> (/var/www/html/admin-dev/themes/new-theme/node_modules/source-map-resolve/lib/source-map-resolve-node.js:6:26)
prestashop-git_1  |     at Module._compile (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
prestashop-git_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
prestashop-git_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
prestashop-git_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
prestashop-git_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
prestashop-git_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
prestashop-git_1  |     at require (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
prestashop-git_1  |     at Object.<anonymous> (/var/www/html/admin-dev/themes/new-theme/node_modules/snapdragon/lib/utils.js:9:28)
prestashop-git_1  |     at Module._compile (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
prestashop-git_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
prestashop-git_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
prestashop-git_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
prestashop-git_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
prestashop-git_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
prestashop-git_1  |     at require (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
prestashop-git_1  |     at Object.<anonymous> (/var/www/html/admin-dev/themes/new-theme/node_modules/snapdragon/lib/compiler.js:6:13)
prestashop-git_1  |     at Module._compile (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
prestashop-git_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
prestashop-git_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
prestashop-git_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
prestashop-git_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
prestashop-git_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
prestashop-git_1  |     at require (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
prestashop-git_1  |     at Object.<anonymous> (/var/www/html/admin-dev/themes/new-theme/node_modules/snapdragon/index.js:5:16)
prestashop-git_1  |     at Module._compile (/var/www/html/admin-dev/themes/new-theme/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
prestashop-git_1  | npm ERR! code ELIFECYCLE
prestashop-git_1  | npm ERR! errno 1
prestashop-git_1  | npm ERR! new-theme@1.0.0 build: `webpack --progress --colors --mode=production`
prestashop-git_1  | npm ERR! Exit status 1
prestashop-git_1  | npm ERR! 
prestashop-git_1  | npm ERR! Failed at the new-theme@1.0.0 build script.
prestashop-git_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
prestashop-git_1  | 
prestashop-git_1  | npm ERR! A complete log of this run can be found in:
prestashop-git_1  | npm ERR!     /var/www/.npm/_logs/2020-07-21T05_56_36_394Z-debug.log
prestashop-git_1  | make: *** [Makefile:7: assets] Error 1
```
This started happening after I made my develop branch up-to-date with PrestaShop develop branch.

#### Expected behavior
No error should be raised.

#### Steps to Reproduce
Use `docker-compose up` to run PrestaShop, then this should show this error.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8 (develop branch)
* PHP version: PHP7.3

**Comment by sarahdib** [comment] 2020-07-21 09:25
@PierreRambaud  could you check this ?

Thank you

**Comment by PierreRambaud** [comment] 2020-07-21 13:05
After several tries, I'm not able to reproduce. Could you tell us more about your containers versions, docker-compose & docker versions?

**Comment by khouloudbelguith** [comment] 2020-08-11 09:06
Hi @ks129,

Since we had no news from you more than 20days, I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-11 09:06 UTC
Labels: No change required
