### ISSUE TITLE
Combination

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#16151] opened 2019-10-28 12:16 UTC
Hi,
I can't manage 6000 combinations for a single product, what are the parameters I should increase?
Best regards

**Comment by khouloudbelguith** [comment] 2019-10-28 12:40
Hi @Webgaict,

In the BO => Catalog => Products page => when you try to edit a product with 6000 combinations => blank page is displayed?

THanks!

**Comment by Webgaict** [comment] 2019-10-28 12:52
Yes

**Comment by khouloudbelguith** [comment] 2019-10-28 12:57
@Webgaict,

We are working on the product page to fix all issues.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-28 12:57
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2019-10-28 12:57 UTC
Labels: Duplicate, Performance, Combinations
