### ISSUE TITLE
Empty shopping cart

### ISSUE THREAD

**Issue by feyzullahdemir** [PrestaShop/PrestaShop#32606] opened 2023-05-17 06:45 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello , 
When directly download prestashop version and install . When you add a product to the cart, it shows the cart as empty.A setting may be turned off by default.Since it is a new version, we need to develop a plugin suitable for its infrastructure.
Since the cart is empty, the payment step cannot be started.
<img width="1195" alt="Screen Shot 2023-05-17 at 9 40 16 AM" src="https://github.com/PrestaShop/PrestaShop/assets/101548542/a4686a21-7150-45e8-9c08-5823b33ff557">

### Steps to reproduce

New Verison PrestaShop download ,
Step 2 Prestashop İnstall and setup,
Add the product to the cart and see that the cart is empty 

### PrestaShop version(s) where the bug happened

8.0+

### PHP version(s) where the bug happened

8.0+

### Your company or customer's name goes here (if applicable).

iyzico

**Comment by paulnoelcholot** [comment] 2023-05-17 12:47
Hello @feyzullahdemir ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2023-05-17 12:47 UTC
Labels: Bug, Invalid
