### ISSUE TITLE
missing the content inside the div #product-images-form in the product page (admin side)

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#9695] opened 2018-08-22 15:37 UTC
Hi

**Describe the bug**
on a new site for one my customer it is not possible to remove images from the product page in admin.
from a clean installation I can remove images instead from the other site is missing the content of the div #product-images-form
if I click on the image I get a 500 error in the chrome dev tool.
I can give you the access to the admin panel (at this moment it is on my local server, but both are on it)
the products on this site are without combinations, but for the rest is the same as default prestashop.
the products were imported in prestashop with a csv from the default import page.
the last three products instead have been added manually but there is the same error

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/44473202-12de4e00-a630-11e8-94e6-0b20e8be10a0.png)
![2](https://user-images.githubusercontent.com/653230/44473205-1376e480-a630-11e8-80d6-9533e886a670.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: php 7.0

**Comment by khouloudbelguith** [comment] 2018-08-23 07:32
Hi @maofree ,

I did not manage to reproduce the issue with the last version 1.7.4.2.
All the image are successfully deleted.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- debug mode report
- PHP error logs
- apache error log

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-08-23 07:42
hi
I've solved it replacing these folders from another site:
js
tools
var
src

**Comment by khouloudbelguith** [comment] 2018-08-23 07:46
Hi @maofree 

Thanks for your feedback.
Since it is fixed, we will close this issue.
Feel free to open a new ticket when needed.

Best regards, Khouloud

**Comment by PierreRambaud** [comment] 2018-08-23 07:57
I close this issue if everything is ok for everyone =)

**Closed as completed by PierreRambaud** 2018-08-23 07:57 UTC
Labels: No change required
