### ISSUE TITLE
Bug adding product to cart

### ISSUE THREAD

**Issue by caotico25** [PrestaShop/PrestaShop#12823] opened 2019-03-07 13:26 UTC
**Describe the bug**
If you click fast several times on the button to add to the cart, the confirmation modal is displayed several times, along with the effect of darkening the page. From here there can be at least two cases: 

1- If you press a few times, when you press the button to continue buying the modal disappears but the effect of the darkened remains. 
2- If you press many times, neither the modal nor the darkening effect disappear. 

In both cases the page is blocked and no action can be taken unless you reload the page. Only the 'Proceed to checkout' button works, because it is reloading the page.

**To Reproduce**
1. Go to any product page on front office
2. Click on 'Add to cart product' several times quickly

**Screenshots**
![captura de pantalla 2019-03-07 a las 14 22 39](https://user-images.githubusercontent.com/6215402/53959642-82a3ba00-40e4-11e9-8c41-e23f89518a31.png)
Case 1

![captura de pantalla 2019-03-07 a las 14 22 19](https://user-images.githubusercontent.com/6215402/53959658-90593f80-40e4-11e9-9089-0dd44a5eed5f.png)
Case 2

**Additionnal information**
PrestaShop version: at least from 1.7.4 to 1.7.5.1

**Comment by khouloudbelguith** [comment] 2019-03-07 13:28
Hi @caotico25,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9634
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 13:28
Duplicate of #9634

**Closed as completed by khouloudbelguith** 2019-03-07 13:28 UTC
Labels: Duplicate
