### ISSUE TITLE
Google sitemap

### ISSUE THREAD

**Issue by charlykb** [PrestaShop/PrestaShop#18747] opened 2020-04-21 14:19 UTC
Bonjour, version Prestashop 1.6.1.23

Comme tous les autres sur les forums prestashop, je remonte ce bug sur le module Google Sitemap qui ne peut pas s'installer : 

2 erreurs
Une erreur est survenue pendant l'extraction du module (le fichier peut être corrompu).
Impossible de mettre à jour le module Google sitemap : erreur lors de l'extraction de la dernière version.

**Pouvez-vous nous donner une vraie solution s'il vous plait ?**

--V-UK--
Hello, Prestashop version 1.6.1.23

Like all the others on the prestashop forums, I report this bug on the Google Sitemap module which cannot be installed:

2 errors
An error occurred during the extraction of the module (the file may be corrupted).
Unable to update Google sitemap module: error while extracting the latest version.

** Can you give us a real solution please? **

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by charlykb** [comment] 2020-04-22 09:56
Merci de votre aide, j'attends :)
Thanks for your help, I wait :)

**Comment by sam-pires** [comment] 2020-04-23 07:28
Hello @charlykb,

The Google Sitemap latest version is compatible with versions =< PS 1.7.1.0
That seems to be the cause of the problem (I guess from the info you shared).

Friendly reminder 🙂 
Please follow the template when filling in a bug report. Without all info and steps to reproduce the bug, it takes way more time for us to investigate issues, and limit our capacity to answer to everyone quickly.

Moreover, as the problem seems to appear on PS 1.6, that we no longer support, I'll close this issue.
If the problem happens also on version > 1.7.1.0 please comment this issue again and ping me and we'll reopen it.

Have a good day,

**Closed as completed** 2020-04-23 07:29 UTC
Labels: No change required

**Comment by charlykb** [comment] 2020-04-25 17:03
Hi,

you said "The Google Sitemap latest version is compatible with versions =<
PS 1.7.1.0"
so, why it doesn't work on my website version 1.6 ?
I have the version 3.2.2

Thx

Le jeu. 23 avr. 2020 à 09:29, Samuel Pirès <notifications@github.com> a
écrit :

**Comment by sam-pires** [comment] 2020-04-27 08:23
Hi @charlykb my bad, made a mistake, I meant >= 1.7.1.0 - superior or equal to PS 1.7.1.0
