### ISSUE TITLE
Weird creation order for combinations PS 1.7.4.2

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10441] opened 2018-09-14 17:25 UTC
I have the feature
Output voltage 5V, 6V, 9V, 12V etc.
Voltage reference LM431, LM329

If I have the voltage first when I create one combination the order features varies without any comprehensible pattern.

If I generate all at once I'll get the same result.
![skarmavbild 2018-09-14 kl 19 23 42](https://user-images.githubusercontent.com/42907000/45565408-c9120d80-b853-11e8-8f6b-a1a2385afafd.png)
![skarmavbild 2018-09-14 kl 19 23 49](https://user-images.githubusercontent.com/42907000/45565409-c9120d80-b853-11e8-87a2-cc48bf0d2ef8.png)

 

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9

**Comment by khouloudbelguith** [comment] 2018-09-17 09:56
Hi @peranderssjostrom,

I did not manage to reproduce the issue with the last version PS 1.7.4.2.
![image](https://user-images.githubusercontent.com/16067358/45616692-88dba680-ba70-11e8-96ac-5bf95959d734.png)
I attached a screesnshot, thanks to check & feedback.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment] 2018-09-17 10:55
What happens if you start with output voltage and then the voltage reference? I could test this over at my place. I may have some problem connected to the migration to 1.7.4.2.

**Comment by khouloudbelguith** [comment] 2018-09-17 11:04
Hi @peranderssjostrom,

I attached a video record
https://drive.google.com/file/d/1-zR73o_jtHG1XpOek4wz8ojdp4mX5taJ/view
What is the exact version of the 1-click upgrade did you use?
What is the previous version of PrestaShop did you use?

Best regards, Khouloud

**Comment by peranderssjostrom** [comment] 2018-09-17 18:55
I used the migration tool Prestashop Migrator (from 1.6.1.20 to 1.7.4.2)

**Comment by peranderssjostrom** [comment] 2018-09-17 19:02
The problem is really weird. If I delete all variants and just choose 6 V + LM431 is the order I get LM431 first.  22

**Comment by peranderssjostrom** [comment] 2018-09-17 19:04
6 V and 22 V are the last added. Something is fishy. Could the ID have something to do with it?
![skarmavbild 2018-09-14 kl 19 23 49](https://user-images.githubusercontent.com/42907000/45644128-307ec600-babd-11e8-8fce-f578ad848b95.png)
![skarmavbild 2018-09-17 kl 20 58 58](https://user-images.githubusercontent.com/42907000/45644133-3379b680-babd-11e8-9f30-1cbf27bd688b.png)
![skarmavbild 2018-09-17 kl 20 59 16](https://user-images.githubusercontent.com/42907000/45644134-3379b680-babd-11e8-8e50-d63053db8886.png)

**Comment by khouloudbelguith** [comment] 2018-09-18 09:09
Hi @peranderssjostrom,

Yes, that's exactly the main issue.
All the attributes are ordered by id.
Sorting by positions doesn't work.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9836
So, I close it.
Thanks!
PS: For a quick fix, you need to recreate in order all these attributes.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-18 09:09
Duplicate of #9836

**Closed as completed by khouloudbelguith** 2018-09-18 09:09 UTC
Labels: BO, Duplicate, Combinations, 1.7.4.2
