### ISSUE TITLE
[Product > Specific Price] Icon on Discount don't change 

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#14442] opened 2019-07-01 13:57 UTC
**Describe the bug**
On the page Add/Edit product, on the tab Pricing, in the fieldset Specific price, if I change the type of the discount, the icon doesn't change

**To Reproduce**
1. Go to Add product, to the tab "Pricing", to the fieldset "Specific price"
2. Click on the select €/%
3. The icon "€" before the discount doesn't change

**Screenshots**
Icon "€" OK with the select
![image](https://user-images.githubusercontent.com/1533248/60442052-7eae2180-9c18-11e9-9255-b6c1f60bf652.png)

Icon KO
![image](https://user-images.githubusercontent.com/1533248/60442083-91285b00-9c18-11e9-921a-e1d8bdfdf46b.png)

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: 7.0.18

**Comment by khouloudbelguith** [comment] 2019-07-01 14:02
Hi @Progi1984,

Thanks for your report.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13382 to fix the issue.
It is added in the next major release PS1.7.7.
Your ticket is a duplicate of #12800
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-01 14:02
Duplicate of #12800

**Closed as completed by khouloudbelguith** 2019-07-01 14:02 UTC
Labels: Duplicate
