### ISSUE TITLE
Error when sending mail

### ISSUE THREAD

**Issue by Mondatr** [PrestaShop/PrestaShop#10415] opened 2018-09-13 07:49 UTC
After updating to the latest version for Prestashop (1.7.4.2), the opportunity to send a message to the administrator from the site was lost. 
When a user tries to send an email message from the "contact us" form after clicking the "SEND" button, an error occurs.
Text of error: "Fetching the "prestashop.core.filter.front_end_object.main" private service or alias is deprecated since Symfony 3.4 and will fail in 4.0. Make it public instead."

**To Reproduce**
1. Go to https:\\<domain_name>\contact-us
2. Fill the fields "Email address" and "Message". Press button "SEND"
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/43231907/45474511-a5ab6d80-b742-11e8-8c8d-bfc0644f2695.png)

**Additionnal information**
Text of error: "An error occurred while sending the message, please try again.". After modify file ...modules/contactform/contactform.php to be able to view the error, i can see the error message.
/*            
            $this->context->controller->errors[] = $this->trans(
                'An error occurred while sending the message, please try again.',
                [],
                'Modules.Contactform.Shop'
            );
*/      
$this->context->controller->errors[] = $errorMessage = error_get_last()['message'];
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-09-13 08:30
Hi @Mondatr,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9566
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-13 08:30
Duplicate of #9566

**Closed as completed by khouloudbelguith** 2018-09-13 08:30 UTC
Labels: Duplicate
