### ISSUE TITLE
Faceted filter never show results

### ISSUE THREAD

**Issue by Madstudiobcn** [PrestaShop/PrestaShop#17316] opened 2020-01-23 10:34 UTC
Hi, 
We have an issue with the prestashop 1.76.2 version and the faceted filter. 
When you click on a link on the faceted item link, the loader appears but never show the result page.
On the console only have this.
tp https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.xh-S9KbEGSE.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQc/rs=AGLTcCNaUSRWzhd71dAsiMVOstVE3KcJZw/cb=gapi.loaded_0:117

We contact with the theme developer and he said that there is no problem with the theme and in other server the theme work ok.

I am testing this site in a URL with a :8008 port, and I am not sure if this could be a problem for this.

On the pretashop logs there is no error, on the server log there is no error.

When we think that the problem is in the core.js, but we are unable to localize the exact origen to fix the problem.

Can any one give me a lead to solve this?

thanks for the help

**Comment by khouloudbelguith** [comment] 2020-01-23 10:41
Hi @Madstudiobcn,

I did not manage to reproduce the issue with PS1.7.6.2 & ps_facetedsearch v3.4.1.
I attached a screen record
https://drive.google.com/file/d/1_EsjhbwMiacqhVxqxYSL8_Ss6bhDLfBV/view
Could you please try to re-install the module by removing the old module during the uninstall & try to configure it by editing the template & rebuilding the entire price index & building attributes & features indexes & clearing the cache.

Thanks to check & feedback.

**Comment by Madstudiobcn** [comment] 2020-01-23 14:57
Hi @khouloudbelguith,
thanks for your answer, I already did that, I uninstall the module and downloaded the last one, created a new template for search, clean faceted cache, and also clean the prestashop cache.

I am share this screen record to illustrate the problem, in the video you can see that the result page not load, well you can leave this 24h, is endless.
The results link if you copy and paste open the correct url.
I got this error in the console but I have no clear that this can produce the faceted issue.

Thanks
<error>
uncaught exception: [object Object] cb=gapi.loaded_0:117:58
    tp https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.xh-S9KbEGSE.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQc/rs=AGLTcCNaUSRWzhd71dAsiMVOstVE3KcJZw/cb=gapi.loaded_0:117
</error>

Video:
https://www.dropbox.com/s/bfgukbw9wmv7ca7/Grabaci%C3%B3n%20de%20pantalla%202020-01-23%20a%20las%2014.02.08.mov?dl=0

**Comment by khouloudbelguith** [comment] 2020-01-23 15:15
@Madstudiobcn, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-24 08:16
Hi @Madstudiobcn,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-24 08:16 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.6.2
