### ISSUE TITLE
Module 1-Click Upgrade with proxy

### ISSUE THREAD

**Issue by nataliatebar** [PrestaShop/PrestaShop#19121] opened 2020-05-14 09:01 UTC
We try to run the module behind a proxy, but we have seen that the conection of the module is made directly by url, not pass through the proxy.

We use PrestaShop version 1.7.4.0, and we try to upgrade to version 1.7.6.5. We have PHP version 7.1.

**Comment by florine2623** [comment] 2020-05-14 09:11
Hi @nataliatebar ,
I don't think using a proxy is an issue for upgrading your website with 1-click upgrade module.
You might need to check the configuration of your proxy.

@PrestaShop/prestashop-core-developers 
Could you confirm my statement ?
Thanks!

**Comment by nataliatebar** [comment] 2020-05-14 12:10
Hi @florine2623, 
We use another modules and all connect without problems for update... We detect that the module 1-Click try to connect to the url directly, so I thought it was from the code snippet where you try to connect through the proxy.

Thanks in advance,

**Comment by LouiseBonnard** [comment] 2020-05-20 09:26
Hi @nataliatebar, thanks for your reply. @PrestaShop/prestashop-core-developers, what do you think?

**Comment by matks** [comment] 2021-03-22 21:34
Hi everybody I dont understand the issue here. I fail to see why the proxy would prevent the 1-click upgrade module to work 🤔 

@nataliatebar if I am not wrong you are reporting a bug. Could you please use the Bug Report template https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md to provide us steps we can follow to reproduce it? Without that it's a bit complex to understand what's going on.

**Comment by florine2623** [comment] 2021-04-14 13:26
Hello @nataliatebar ,
Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-04-14 13:26 UTC
Labels: Bug, BO, Autoupgrade
