### ISSUE TITLE
The theme compliancy/compatibility is not handled

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29059] opened 2022-07-12 20:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If in the config.theme.yml of a file you can choose a range of compatibility with PrestaShop versions (see example https://github.com/PrestaShop/hummingbird/blob/develop/config/theme.yml). It is not acknowledged. Even if you select a PS version that does not exist like 9.0.0, the theme can be enabled and used on the shop. Both the "from" and the "to" are not considered

### Steps to reproduce

1. Use this theme. [eni.zip](https://github.com/PrestaShop/PrestaShop/files/9096690/eni.zip)
2. Enable it
3. See that it's enable even if you choose a from/to that could not match the PrestaShop version.
 

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by matks** [comment] 2022-07-12 20:48
Hi Jonathan, do you think you could be a little more descriptive with your bug reports 😅 

> Once creating a shop with a compatibility from 9.0.0, it's enabled and used. It's not taken in consideration. (The from/to, is the same).

I think only people very familiar with themes and shop versions will understand. You and I, we understand. But I started onboarding new people on the project 2 days ago and I found quite often we write things in a manner that prevents them from helping because they are not (yet) familiar with the topics. So we put barriers to people trying to join the project and contribute (but we don't do this on purpose)

For example I suggest 😄 :

> If in the config.theme.yml of a file you can choose a range of compatibility with PrestaShop versions (see example https://github.com/PrestaShop/hummingbird/blob/develop/config/theme.yml). It is not acknowledged. Even if you select a PS version that does not exist like 9.0.0, the theme can be enabled and used on the shop. Both the "from" and the "to" are not considered.

**Comment by PrestaEdit** [comment] 2022-07-12 20:52
I can, yes. There, I write my reporting issues between a test and a functionial documentation writing. I'd rather prefer to create the issue before forgetting it and be able to update it's behavior as needed.

I change immediately my report with your suggestion, and I will try to take a little more time on my next report, hoping it's will be not for today :D

**Comment by florine2623** [comment] 2022-07-13 13:42
Hello @PrestaEdit ,

I'm not sure how to reproduce this bug 😅 
I added the eni template to my BO.
I tried to Use it, but I encounter the error your mentioned [here](https://github.com/PrestaShop/PrestaShop/issues/29058).

Could you send a screen record of the steps please ?
Thanks!

**Comment by matks** [comment] 2022-07-15 06:53
> I change immediately my report with your suggestion, and I will try to take a little more time on my next report, hoping it's will be not for today :D

Thanks !

I'm currently looking for nice topics that people with fresh little knowledge of prestashop can explore to grow their prestashop knowledge 😏 so if issues are very well described I can use them and assign manpower to it as part of their onboarding

**Comment by hibatallahAouadni** [comment] 2022-08-01 17:31
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-08-01 17:31 UTC
Labels: Bug, BO, Theme & logo, Invalid

**Comment by PrestaEdit** [comment] 2022-08-11 17:41
Hi @florine2623,

As the theme is not really valid, you will not be able to add it within the Back Office, you need to add it on the themes folder.

But what you can do is to duplicate the Classic theme and rename it (it's folder name and the name inside the config/theme.yml).

Once it's done, change the from property into the /config/theme.yml with 9.0.0 value, as example.
And try using this theme on your 8.0.x shop.
