### ISSUE TITLE
Currencies : The button "Restore default settings" doesn't work

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#31812] opened 2023-03-16 14:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After editing a currency format with a custom symbol, the button "Restore default settings" doesn't reset currency format

### Expected behavior

After editing a currency format with a custom symbol,  the button "Restore default settings" reset currency format

### Steps to reproduce

1. Go to Currencies page
2. Edit the EUR currency
3. Edit the symbol for English (English) language
4. Define with a custom symbol (`@`, for example)
5. Save the modal
6. The currency format example is up-to-date with `@`
7. Save the currency
8. :tada: The currency use the custom symbol
9. Edit the EUR currency
10. Click on the button "Restore default settings"
11. :red_circle: The currency format example is not up-to-date with `€`

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2023-03-17 10:45
Hello @Progi1984 ,

I reproduce the issue with PrestaShop version `8.1.x`, I'll add this to the backlog so it can be fixed.
It is a Regression as it worked well on `8.0.x`.

https://user-images.githubusercontent.com/16019289/225883184-6554752b-39a2-4e84-9f31-7396642dab0e.mov

---

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Zoefinders** [comment] 2023-03-24 09:52
@florine2623 I can't reproduce the 8.0.1 bug. Do we have the same behavior on the version 1.7.8.7 on the behave 8.0.0?
Thanks ! 

https://user-images.githubusercontent.com/99200820/227487072-7038f988-1b95-475e-8eac-3f65ba3e614a.mov

**Comment by Progi1984** [comment] 2023-03-24 09:59
@Zoefinders It's a 8.1.x bug, not 8.0.x bug ;)

**Comment by RosaBenouamer** [comment] 2023-04-03 14:29
This bug concern the "Restore default settings" button not the "Reset".

**Comment by RosaBenouamer** [comment] 2023-04-03 14:30
Linked with https://github.com/PrestaShop/PrestaShop/issues/31759 ?

**Closed as completed** 2023-04-20 12:22 UTC
Labels: Bug, Minor, BO, Currencies, Regression, PR available, Detected by TE, Verified, 8.1.x

**Comment by Progi1984** [comment] 2023-04-20 12:47
@mflasquin I will test it #32221
