### ISSUE TITLE
Upgrade problem to Prestashop 1.7.7.0 Cannot declare class PrestaShopBundle\Entity\Tab

### ISSUE THREAD

**Issue by Art3c** [PrestaShop/PrestaShop#22248] opened 2020-12-04 14:42 UTC
Hi,
 
i did a updateto the new 1.7.70 from 1.7.6.9. I did a full backup of the DB and files on the server. When 1-click upgrade started to updaet it shows me this error. Please help!

[INTERNAL] /home/shopmo97/public_html/src/PrestaShopBundle/Entity/Tab.php line 37 - Cannot declare class PrestaShopBundle\Entity\Tab, because the name is already in use.

The BO stops working :( The FO was online butt without the pictures.

#### Steps to Reproduce

1. Go to 1-Click upgrade
2. Did the check list and full server backup
3. Clicked upgrade
4. After upgrading all the files it writtes upgrading DB and the the error message is displayed.

![101176064-44835380-3646-11eb-9e9a-61c8514f3bbb 1](https://user-images.githubusercontent.com/75488263/101176483-d9864c80-3646-11eb-8f03-68da165a38b4.png)

Info of the server in the print screen
* PrestaShop version: 1.7.6.9
* PHP version: 7.2.34

**Comment by matks** [comment] 2020-12-04 15:00
Hi, how did you do the backup ? manually ? copy on another server ?
> I did a full backup of the DB and files on the server

**Comment by Art3c** [comment] 2020-12-04 15:33
> Hi, how did you do the backup ? manually ? copy on another server ?
> 
> > I did a full backup of the DB and files on the server

I did it over my cPanel. After the faild update a erased the public_html folder content and started a restor of the directory and the DB. I have a cron task for automatic backup for last 7 days

**Comment by matks** [comment] 2020-12-04 15:56
What version of the autoupgrade module have you used?

**Comment by Art3c** [comment] 2020-12-04 16:25
> What version of the autoupgrade module have you used?

v4.11.0 the latest version. I allways check the modules before i update.

**Comment by CJH297** [comment] 2020-12-05 12:16
I have a similar situation. Upgrade from 1.7.6.9 to 1.7.7.0, modules current, 1-click reports everything green. Upgrade forced on me to comply with php by hosting ...

```
Upgrade completed with errors reported (elided with xxxxxxxxx for path):

[INTERNAL] /xxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/xxxxxxxxxxxx/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/xxxxxxxxxxxxxxxx/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /homepages/36/d27743760/xxxxxxxxxxxxx/app/config/config.yml (which is being imported from "/xxxxxxxxxxx/app/config/config_prod.yml"). #0 

/xxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/homepages/36/d...', NULL, false, '/homepages/36/d...') #1 

/xxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/homepages/36/d...') #2 

/xxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/homepages/36/d...') #3 

/xxxxxxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/homepages/36/d...', NULL) #4

 /xxxxxxxxxxxxxxxxx/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/homepages/36/d...') #5 

/xxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 

/xxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 

/xxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 

/xxxxxxxxxxxxx/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 

/xxxxxxxxxxxxxxxxxxxxxxx/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 

/xxxxxxxxxxxxxxxxx/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 

/xxxxxxxxxxxxxxxxx/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 

/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}
```

After this, both back office and website show blank white pages. Deleting cache and var did not help. Unfortunately, a good backup (I am convinced absolutely that both backup and database are good) did not restore the site to working status. BO unattainable, website shows partial home page only, with no other pages and missing images. Something must be interfering with the restore (which was completed by ntbackup module that reported fully restored, but nothing runs). I don't know enough to do more with this so ideas are welcome. At present, it's screwed everything.

**Comment by CJH297** [comment] 2020-12-05 13:08
Transferred to new issue, as in retrospect this seemed more suitable

**Comment by Art3c** [comment] 2020-12-05 16:18
@matks Do you need more info on the server configuration?

**Comment by matks** [comment] 2020-12-07 08:18
Also reported on Build https://build.prestashop.com/news/prestashop-1-7-7-0-available/#comment-5175612840

**Comment by hibatallahAouadni** [comment] 2020-12-25 12:23
Hello @Art3c 

Sorry for the delay, but I didn't manage to reproduce your issue :confused: 
I upgrade my shop PS1.7.6.9 to PS1.7.7.0 with no error, see the attached screen record below:

https://drive.google.com/file/d/16ii_UDe3R7amfP2AnGnM0dQyki3M-c0Z/view

Just to make you sure, see my configuration in the screenshot below:

![image](https://user-images.githubusercontent.com/23308427/103134799-14aef500-46b4-11eb-804f-4b49e0018651.png)

I just received a warning about missing files that cannot affect the functionality of the store :wink: 

Please check and feedback.
Thanks!

**Comment by Art3c** [comment] 2020-12-25 13:14
@hibatallahAouadni  I tried again but it the same situation :( The file upgrade goes ok but the when it should start the DB upgrade it throws the error. The FO is working with a few glitches but in the BO the left side menu is not displayed. Is there a way to manually upgrade the DB?

I can record the upgrade process if it will help :(

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-25 14:47
Hello @Art3c 

> in the BO the left side menu is not displayed.

Your issue is a duplicate of #22250. To fix manually this problem, just execute these command on your database:

`select * from ps_tab;`

You will see that there's a column missing "enabled", so we need to add it:

`alter table ps_tab add enabled TINYINT(1) NOT NULL;`

And to make the menu displayed, execute this line:

`update ps_tab set enabled=1;`

You may encounter some issues with menu. So, you need to check if there's a menu (tab) should be disabled :wink: 
For exemple in my case:
```
update ps_tab set enabled=0 where id_tab=27;
update ps_tab set enabled=0 where id_tab=49;
update ps_tab set enabled=0 where id_tab=50;
update ps_tab set enabled=0 where id_tab=51;
update ps_tab set enabled=0 where id_tab=54;
update ps_tab set enabled=0 where id_tab=118;
update ps_tab set enabled=0 where id_tab=119;
```
The cause of problem is the **APCu bc** and the **ABCu**.
Well, the issue has been fixed with the new patch 1.7.7.1 and it will be released soon :wink: 
Please check and feedback.

Thanks!

**Comment by Art3c** [comment] 2020-12-25 16:58
@hibatallahAouadni thanks, so if i am correct it is better to wait for the 1.7.7.1 patch?

**Comment by hibatallahAouadni** [comment] 2020-12-25 17:02
@Art3c Yeeeesss :wink:

**Comment by Art3c** [comment] 2020-12-25 17:32
@hibatallahAouadni Thanks! :) it looked the #22250 problem but in my case i didn't had any errors on warning displayed. Just the menu was not there :/

**Comment by hibatallahAouadni** [comment] 2020-12-26 09:57
Hello @Art3c 

Well, I have to close this issue cause it is a duplicate of #22250 
And the problem already fixed with the next new release 1.7.7.1
Please stay tuned for our new release :wink:

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-26 09:57
Duplicate of #22250

**Closed as completed by hibatallahAouadni** 2020-12-26 09:57 UTC
Labels: Bug, BO, Duplicate, Autoupgrade, 1.7.7.0

**Comment by Art3c** [comment] 2020-12-26 10:09
@hibatallahAouadni thanks i will wait for the update. I am just not sure that the problem is the same. #22250 the DB update was made but not complete. In my case the first line of DB upgrade has throwen a error. I reopen if the 1.7.7.1 does not solve the problem.

Thanks for the help!

**Comment by Art3c** [comment] 2021-03-05 21:18
@hibatallahAouadni
hi, is this the problem of the update?

![slika](https://user-images.githubusercontent.com/75488263/110174627-aa77a680-7e00-11eb-8c63-12a700dcc04e.png)

**Comment by hibatallahAouadni** [comment] 2021-03-06 00:33
@Art3c could you please check this issue #21206 it may help you solving your problem

**Comment by Art3c** [comment] 2021-03-06 07:21
> @Art3c could you please check this issue #21206 it may help you solving your problem


@hibatallahAouadni 
No, it does help :( the problem is present in PHP 7.0 - 7.3. I tried it :(
