### ISSUE TITLE
Product attributes with ID product 0

### ISSUE THREAD

**Issue by oldmanxxxv** [PrestaShop/PrestaShop#25998] opened 2021-09-24 20:52 UTC
#### Describe the bug

We use a lot of master products with variants.
The problem appears when try to create product variants after a while of inactivity, probably a cookie or token is expired.
I have notice when I had some problems with my script that makes updates automatic from a feed, the ID 0 attributes where chosen first and left behind the real ones with assigned product ID.

#### Expected behavior

I would like to be warned about this problem when happens. Sometimes the security token warning appears, but not all the time.

#### Steps to Reproduce

It is hard to reproduce the error, because I have no idea when this happens, this issue is from 1.6 version. I was thinking will be solved in time, but is still there.

1 Try to create a product.
2. Select product with combinations
3. Create a combination
4. Wait 5 -10 minutes and go further to create another combinations
5. After that, check the three tables ps_product_attribute, ps_product_attribute_shop, ps_stock_available
6. If the error happened you'll find there entrances of attributes with ID Product 0, otherwise wait longer

**Screenshots**

https://www.bikenature.ro/presta-errors/product_attribute.JPG
https://www.bikenature.ro/presta-errors/product_attribute_shop.JPG
https://www.bikenature.ro/presta-errors/stock_available.JPG

I mention that this error is not created by some custom script that imports attributes, it is done by the admin interface

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.3 (it was tested 5.6, 7.1, 7.2, 7.3 in previous versions, same result)

**Comment by hibatallahAouadni** [comment] 2021-09-27 13:49
Hello @oldmanxxxv 

I didn't manage to reproduce the issue with PS1778 and PS1767, see the attached screenshots below:

Before creating the second combination:
![image](https://user-images.githubusercontent.com/23308427/134921488-9f71bd4c-cf91-470d-a39c-9e5012fd3a41.png)

After creating the second combination:
![image](https://user-images.githubusercontent.com/23308427/134921599-362de326-60ec-43bb-98e6-7ff9d63a9f0b.png)

![image](https://user-images.githubusercontent.com/23308427/134920916-c8cb69b0-ff6a-4b0b-b82c-f865b4863f84.png)

As you can see the id_product is still well saved.
Please check and feedback.

PS: by the way, PS1768 is compatible with PHP 5.6, 7.1, 7.2 and not 7.3 :wink: 

Thanks!

**Comment by oldmanxxxv** [comment] 2021-09-30 15:00
Hi there,
What do you mean by " is not compatible with 7.3"?
It runs very well I didn't notice any problems despite the fact it is not recommended.
Yes, it is a very tricky to get that situation, probably that is the reason why this bug is still present after so many years, nobody noticed, specially if not use the product combinations. I would recommend to insist, my screenshots don't lie.
As you could see, are 13 entries with the same reference. Now I have cleaned the database but I will repost next time when I get such error.

Thanks

**Comment by hibatallahAouadni** [comment] 2021-09-30 15:34
Hello @oldmanxxxv 

> What do you mean by " is not compatible with 7.3"?
It runs very well I didn't notice any problems despite the fact it is not recommended.

Check our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-10-20 16:52
Hello @oldmanxxxv 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-10-20 16:52 UTC
Labels: Bug, BO, Database, Combinations, No change required, 1.7.6.8

**Comment by oldmanxxxv** [comment] 2021-10-20 19:05
Hi there,
The only thing I can say is, two day ago I have erased from the three mentioned tables 57 entries with 0 product_id, each.
I would say to pay more attention with this bug because it is not something common, especially if someone doesn't use combinations. And is not visible from admin area.

Thank you.
