### ISSUE TITLE
BO - Bad display of Multistore when dropdown is open

### ISSUE THREAD

**Issue by thomasDelaporte** [PrestaShop/PrestaShop#29200] opened 2022-07-29 09:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you have a custom store and you open the dropdown carret it's not being displayed outside the panel due to the overflow auto and therefore we have the scrollbar showing.

![ps_issue](https://user-images.githubusercontent.com/55890466/181734040-0d6b8536-5d6d-4ee9-9e43-ff971a01ce23.png)

You can check the SCSS code of ".adminshop .bootstrap .table-responsive-row".

### Expected behavior

Dropdown on top of the content without the scrollbar showing.

### Steps to reproduce

- Enable multistore
- Create a new shop
- Go to multistore and select your new store on the left
- See error >> open the dropdown of your store

### PrestaShop version(s) where the bug happened

8.0.x, 8.0.0

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment] 2022-07-29 16:18
Hello @thomasDelaporte 

I was able to reproduce the issue with PrestaShop version 1.7.8.6 and 8.0.0. I didn't repoduce with 1.7.7.7, means it's a regression on 178x!
I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2023-03-13 08:52 UTC
Labels: Bug, Trivial, BO, Multistore, Fixed, Front-end, PR available, 1.7.8.0, Verified
