### ISSUE TITLE
When minimal quantity for sale set, then on product page not possible to enter quantity by keyboard

### ISSUE THREAD

**Issue by birzelv** [PrestaShop/PrestaShop#36245] opened 2024-05-27 12:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On backend, in product combination entered minimal quanity for sale: 50. Then, on frontend product page, tried to enter quantity by keyboard: 100 (or any value from 100 to 499), the quantity jumps back to 50.

### Expected behavior

The minimum quantity must not allow to enter quantity that is less than the minimum. In this example, must not allow to enter 0 - 49.

The problem is that it also does not allow to enter values from 100 to 499 BY KEYBOARD. It reverts to 50

### Steps to reproduce

1. Go to back office, create a product with combinations
2. Open combination, set minimal quanity for sale: 50.
3. Go to frontend product page.
4. In the quantity field, enter quantity 100 by keyboard (or any value from 100 to 499).
5. The quantity in the field goes back to 50.

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.3

**Comment by ComonSoft** [comment] 2024-05-28 09:40
Reproduced on 8.1.6. It happens when the user click outside up+/-down arrows. It's a duplicate of  #28531.
It seems the issue it situated in theme.js.

**Comment by AureRita** [comment] 2024-05-30 13:49
Hi @birzelv 

As said @ComonSoft, your issue is a dupplicate, so I have to close it because it's already in our backlog. 

You can continue to keep your discussion in this ticket if you want

**Comment by AureRita** [comment] 2024-05-30 13:49
Duplicate of #28531

**Closed as completed by AureRita** 2024-05-30 13:49 UTC
Labels: Bug, Duplicate
