### ISSUE TITLE
Could not crawl for translation files when translating template

### ISSUE THREAD

**Issue by ciekals11** [PrestaShop/PrestaShop#30218] opened 2022-11-04 14:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

```
Could not crawl for translation files: The "/<path>/var/cache/dev/themes/dekora/translations" directory does not exist.
```
error message when trying to translate template.

Not every time.
Once in a while some tabs loads correctly but most of the time I get error.
when I create this directory, presta deletes it

### Expected behavior

error doesn't show up

### Steps to reproduce

1. Install template template
2. Go to translation
3. Translate template
4. Select tab

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.2.33

**Comment by hibatallahAouadni** [comment] 2022-11-04 18:25
Hello @ciekals11 

> Not every time.
Once in a while some tabs loads correctly but most of the time I get error.

It's caused by your network connection or your server, so you need to check it :wink: 
Unfortunately, I have to close the issue cause we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Closed as completed by hibatallahAouadni** 2022-11-04 18:25 UTC
Labels: Bug, Invalid

**Comment by ciekals11** [comment] 2022-11-07 12:11
Well. I doubt that it is my connection or server problem.
Renaming template from `dekora` to `classic` resolved this problem but this is more of a hack than solution.

It seems to be a problem with cache

Update:

It did not work. Loaded more translations but still even when theme have been moved from `dekora` to `classic` directory for some reason prestashop still looks for `var/cache/dekora/translations` directory. (renamed name and display_name in `theme.yml`)
