### ISSUE TITLE
Issue upgrade from 1.7.6.9 to 1.7.7.2

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#23790] opened 2021-03-26 15:09 UTC
Hello

I need your help please to detect which module or plugin are causing this conflicts , i can't change from default theme to new one

- Disable All Modules : Done
- Disable CloudFlare : Done
- Switch to default theme : Done
- Disable Cache : Done
- Disable non PrestaShop modules YES
- Disable all overrides YES
- 1-Click Upgrade : upgraded to v4.12.0 - by PrestaShop

#### Describe the bug

```
jquery-3.4.1.min.js:2 Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (default.js?1.7.7.2:7)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
jquery-3.4.1.min.js:2 Uncaught TypeError: n(...).popover is not a function
    at HTMLDocument.<anonymous> (form_popover_error.bundle.js?1.7.7.2:25)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
jquery-3.4.1.min.js:2 Uncaught TypeError: o.dropzone is not a function
    at e.value (module.bundle.js?1.7.7.2:1)
    at new e (module.bundle.js?1.7.7.2:1)
    at HTMLDocument.<anonymous> (module.bundle.js?1.7.7.2:25)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)

```

Changed/missing files have been detected.

```
Missing files (6)
vendor/composer/installers/src/Composer/Installers/SyliusInstaller.php
vendor/composer/installers/src/Composer/Installers/KnownInstaller.php
vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
vendor/composer/installers/src/Composer/Installers/Redaxo5Installer.php
vendor/composer/installers/src/Composer/Installers/DframeInstaller.php
vendor/composer/installers/src/Composer/Installers/MantisBTInstaller.php
Updated files (10)
admin850sxbqm8500sxb/autoupgrade/index.php
admin850sxbqm8500sxb/autoupgrade/backup/index.php
vendor/composer/installers/src/Composer/Installers/DrupalInstaller.php
vendor/composer/installers/src/Composer/Installers/Plugin.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/WHMCSInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MicroweberInstaller.php
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11594433/112651944-2d62ae80-8e4d-11eb-81e2-c569297d9800.png)

![image](https://user-images.githubusercontent.com/11594433/112651963-32bff900-8e4d-11eb-8dee-652a3c7d9eda.png)

#### Additional information

- PHP version: 7.3.27
- Memory limit: 8090M
- Max execution time: 3000
- Upload Max File size: 900M
Regards

**Comment by florine2623** [comment] 2021-03-26 16:42
Hello @go-sudo ,
I can't reproduce your issue when I upgrade from 1.7.6.9 to 1.7.7.2.
https://github.com/PrestaShop/PrestaShop/issues/23770

PS 1.7.6.9 is not compatible with PHP 7.2. Please downgrade your version.

Are you using one language or more ?

**Comment by go-sudo** [comment] 2021-03-26 17:02
Hello @florine2623 

Ok I switched to 7.2 PHP version but still same errors
3 languages FR, EN,SP
![image](https://user-images.githubusercontent.com/11594433/112667286-6014a300-8e5d-11eb-9572-31ca94a4ddfd.png)

Thank you very much 

Regards

**Comment by go-sudo** [comment] 2021-03-26 19:24
Hello @florine2623 

I disabled and kept only French language but it still the same issue , do you think that there is a duplicate duplicate version of jQuery and where or how can i check this and in which file 

Regards

**Comment by hibatallahAouadni** [comment] 2021-03-30 18:02
Hello @go-sudo 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug :confounded:
 
It seems you need help with your shop, so please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-30 18:02 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.7.2

**Comment by go-sudo** [comment] 2021-03-30 18:17
Thank you very much. I will install new fresh one an migrate my database one by one.

**Comment by knut4github** [comment] 2021-08-13 19:54
I have exact the same issue. Have anyone solv this issue?

**Comment by go-sudo** [comment] 2021-08-13 20:02
> I have exact the same issue. Have anyone solv this issue?

Hello try please to disable all the modules
