### ISSUE TITLE
1.7.8.1 product id field backoffice to small - visual improvement needed

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#26620] opened 2021-11-15 19:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The product input field is too small. It is limited to two digits.

<img width="222" alt="Screenshot 2021-11-15 at 19 53 33" src="https://user-images.githubusercontent.com/46492443/141845597-84056fbf-464e-432a-b14a-ac8a1cb02214.png">

### Expected behavior

At least 5-6 digit visibility or  like pre 1.7.8 versions

<img width="164" alt="Screenshot 2021-11-15 at 19 53 58" src="https://user-images.githubusercontent.com/46492443/141845749-c61aa1ef-8ef5-4e40-bf31-7e39cc8b8983.png">

### Steps to reproduce

Go to back office and check the layout from the product id

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

**Comment by alfonsolr09** [comment] 2021-11-15 22:08
that's a regression, in version 1.7.7.3 that works perfectly

**Comment by mparvazi** [comment] 2021-11-16 10:10
This problem also exists in other tables for ID column.

```
table tr.column-filters td[data-column-id^="id_"] input:only-child {
    min-width: 6rem;
}
```

**Comment by hibatallahAouadni** [comment] 2021-11-16 10:54
Hello @01park 

You already report about this issue here #26192
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26192. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-16 10:54
Duplicate of #26192

**Closed as completed by hibatallahAouadni** 2021-11-16 10:54 UTC
Labels: Bug, Duplicate, Invalid
