### ISSUE TITLE
 Order confirmation email not sent to customers 

### ISSUE THREAD

**Issue by loran-a** [PrestaShop/PrestaShop#14050] opened 2019-06-03 07:47 UTC
Hello

I have a problem that  Order confirmation email not sent to clients after update to 1.7.5.2, i think so because before updating it works fine

I use paypal module and pay on pickup module.

Paypal sent the order invoice when a costumer make an order, but when the costumer choose pay on pickup, no mail confirmation receive.

Test email received just when i type email@mydomain.com, when I write another email for example hotmail or gmail, no email receive.
Email sitting is php not STMP

Sorry for my bad english

**Comment by khouloudbelguith** [comment] 2019-06-03 08:46
Hi @loran-a,

Thanks for your report.
>when the customer choose pay on pickup, no mail confirmation receive.

what is the exact status did you use in this case? The option "Send an email to the customer when his/her order status has changed." is checked in this status?
![image](https://user-images.githubusercontent.com/16067358/58788486-e5252d00-85e3-11e9-999a-8f6c6dfa838e.png)

>Test email received just when I type email@mydomain.com, when I write another email for example hotmail or gmail, no email receive.

Have you tried to contact your host about this issue?
if only emails from your domain is accepted, it could be a permission issue on your server, thanks to check with them & feedback.

**Comment by loran-a** [comment] 2019-06-03 09:34
> 
> 
> Hi @loran-a,
> 
> Thanks for your report.
> 
> > when the customer choose pay on pickup, no mail confirmation receive.
> 
> what is the exact status did you use in this case? The option "Send an email to the customer when his/her order status has changed." is checked in this status?
> ![image](https://user-images.githubusercontent.com/16067358/58788486-e5252d00-85e3-11e9-999a-8f6c6dfa838e.png)
> 
> > Test email received just when I type [email@mydomain.com](mailto:email@mydomain.com), when I write another email for example hotmail or gmail, no email receive.
> 
> Have you tried to contact your host about this issue?
> if only emails from your domain is accepted, it could be a permission issue on your server, thanks to check with them & feedback.




Hello khouloudbelguith, 
Where can I find the sitteing you have showed in the picture?

I dont thinks so the problem is form my server, because before the update to 1.75.2, it worked fine.

So maybe the problem is from paypal module? or what?

**Comment by khouloudbelguith** [comment] 2019-06-03 09:39
@loran-a, you have two issues:
1. the first issue: when the customer choose pay on pickup, no mail confirmation receive.

What is the exact name of the module did you use?
what is the exact status used in this case?

2. the second issue: Test email received just when I type email@mydomain.com, when I write another email for example hotmail or gmail, no email receive.

This issue it could be related to your server.

Thanks!

**Comment by loran-a** [comment] 2019-06-03 09:53
> 
> 
> @loran-a, you have two issues:
> 
>     1. the first issue: when the customer choose pay on pickup, no mail confirmation receive.
> 
> 
> What is the exact name of the module did you use?
> what is the exact status used in this case?
> 
>     1. the second issue: Test email received just when I type [email@mydomain.com](mailto:email@mydomain.com), when I write another email for example hotmail or gmail, no email receive.
> 
> 
> This issue it could be related to your server.
> 
> Thanks!

- What is the exact name of the module did you use?
Pickup in store
v1.0.0 - efter PrestaShark.eu 

- What is the exact status used in this case?
Processing in progress 

For the second issue i will try contact them

Thanks

**Comment by loran-a** [comment] 2019-06-03 10:10
Problem solved thanks alot after i choose send email for the order status

**Comment by khouloudbelguith** [comment] 2019-06-03 10:11
@loran-a, thanks for your feedback.
Can I close the issue?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-03 09:07
Hi @loran-a,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-03 09:07 UTC
Labels: Email, No change required, 1.7.5.2

**Comment by ernest98k** [comment] 2020-04-01 23:43
@khouloudbelguith i'm having the same issue, where do I find that option , send and email to the customer... the one you mentioned.

**Comment by khouloudbelguith** [comment] 2020-04-02 08:18
Hi @ernest98k,

You need to navigate to your BO => Shop Parameters => Order Settings page => Statuses Tab => Edit your exact status => You will be redirected to the Order status Edit page => Select the option  "Send an email to the customer when his/her order status has changed." and Save.
![image](https://user-images.githubusercontent.com/16067358/78225956-5024e600-74cb-11ea-919f-118241c63543.png)

Thanks!

**Comment by ernest98k** [comment] 2020-04-02 13:06
Thanks for that, the checkbox was unchecked , but i'm still unable to receive the email, any other advice ?

**Comment by khouloudbelguith** [comment] 2020-04-02 13:09
@ernest98k,
>Thanks for that, the checkbox was unchecked

It should be checked.

Thanks!

**Comment by ernest98k** [comment] 2020-04-02 13:27
It's checked now , but I don't receive emails yet.

**Comment by khouloudbelguith** [comment] 2020-04-02 13:29
@loran-a, you need to check if "Send test email" is well working.
![image](https://user-images.githubusercontent.com/16067358/78254780-aeb38980-74f6-11ea-9d2c-71907af4c4e3.png)

Thanks!

**Comment by ernest98k** [comment] 2020-04-02 13:57
![image](https://user-images.githubusercontent.com/46162454/78257858-537f9800-74f2-11ea-8323-8e07db87b9a0.png)

**Comment by khouloudbelguith** [comment] 2020-04-02 14:04
@loran-a, I did not manage to reproduce the issue with PS1.7.6.4
![image](https://user-images.githubusercontent.com/16067358/70325134-95911980-1831-11ea-85b7-c0cef3b3fe8e.png)

The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

You need to check with your host, it is a server issue.

Thanks!

**Comment by ernest98k** [comment] 2020-04-02 14:10
My mail domain name is missing,this field is empty,  might that be a issue ?
