### ISSUE TITLE
Order page: Change Address, shipping modified to 0

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#14474] opened 2019-07-03 22:52 UTC
Hi github team,

In Order page, there is shipping address part where we can see or change the address.

When I change the address of a customer (from his listing), the shipping cost of the order is modify to 0.

Please notice, the city, states and country are the same for each address.

--
php 7.2
ps 1.7.5.0

**Comment by khouloudbelguith** [comment] 2019-07-04 08:01
Hi @BenTen,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
I attached a screen record.
https://drive.google.com/file/d/11IEU4_c6WXYs9vZtLNpRmbxU7blS7imM/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-08-05 07:22
Hi @BenTen,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-05 07:22 UTC
Labels: Bug, BO, Order, Addresses, No change required, 1.7.5.0

**Comment by BenTen** [comment] 2019-09-20 05:27
@khouloudbelguith  I have always the bug, I changed the postal code (Mexico for this case) and the shipping became 0.

In your case, you changed an address by exactly the same. So there is no modification.

**Comment by khouloudbelguith** [comment] 2019-09-20 10:54
@BenTen, it is OK in my case also
https://drive.google.com/file/d/1QJ-8xStERray37r9H5R-22yDVc7pdcpx/view
Thanks!

**Comment by JirkaDeLucina** [comment] 2023-03-04 08:56
> @BenTen, it is OK in my case also https://drive.google.com/file/d/1QJ-8xStERray37r9H5R-22yDVc7pdcpx/view Thanks!

You have to EDIT the address, not try to change to another, then you will see the bug. Is there any fix for this? I have the same problem in my version 1.7.4. Thanx.
