### ISSUE TITLE
PRestashop 1.7.5.1 and ps_facetedsearch v. 3.3.0

### ISSUE THREAD

**Issue by copyact** [PrestaShop/PrestaShop#15837] opened 2019-10-04 14:30 UTC
**Describe the bug**
I have installed prestashop 1.7.5.1 with template and there was a ps_facetedsearch v.2.2.0 which was working fine. I upgraded this module to 3.3.0 and now the price slider is not working. It's hidden.

You can see that on screenshot or at https://gry-basanti.pl/184-gry-karciane

I don't know why but something adds display:none to the code:
<div id="slider-range_39140" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" aria-disabled="false" style="display: none;">

When I set by hand display:block I am able to move slider and product list is updated corectly.

I don't know why it's hidden.

I also get errors when trying to rebuild price or atribute index.
When I open http://gry-basanti.pl/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=XXXX
I got 403 error

**Screenshots**
![prestashop](https://user-images.githubusercontent.com/4846599/66214799-b1a5fc80-e6c2-11e9-8af9-f6e9dbaf794f.png)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2019-10-04 15:01
Hi @copyact,

I did not manage to reproduce the issue with PS1.7.6.1 & ps_facetedsearch module after upgrade from v3.0.6 to v3.3.0.
It is OK with PS1.7.5.1 & ps_facetedsearch module after upgrade from v2.2.0 to v3.3.0.
https://drive.google.com/file/d/1hwt-bDNPKnGz-vJxKc9xN0HKrAjIYPO1/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by copyact** [comment] 2019-10-07 12:07
It's very strange because it works on mobile. Some js is hiding the search slider on page load.

 Can you tell me for now how can I install  ps_facetedsearch v.2.2.0? I tried downloading sources from github but can't build them because they don't have package.json file and when I copied  ps_facetedsearch folder from clean prestashop download to my modules it is not showing in my module list.

**Comment by khouloudbelguith** [comment] 2019-10-07 12:51
@copyact, you can follow these steps:
1. git clone https://github.com/PrestaShop/ps_facetedsearch.git
2. cd ps_facetedsearch
3. git checkout tags/v2.2.0.
4. composer install
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3697295/ps_facetedsearch.zip)
Thanks!

**Comment by copyact** [comment] 2019-10-09 08:56
Thanks:)

**Comment by khouloudbelguith** [comment] 2019-10-09 09:27
@copyact, you are welcome!
so can I close the issue?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-08 07:53
Hi @copyact,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-08 07:53 UTC
Labels: Bug, Faceted search, No change required, 1.7.5.1
