### ISSUE TITLE
ContextErrorException when running from Docker

### ISSUE THREAD

**Issue by stelgenhof** [PrestaShop/PrestaShop#17740] opened 2020-02-19 12:57 UTC
**Describe the bug**
When running from Docker, I get a ContextErrorException error (See screenshot below).

**To Reproduce**
1. Clone the repository (develop branch)
2. Run `docker-compose up`
3. Navigate to `http://localhost:8001/`

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/529544/74836199-418ecf00-5362-11ea-9777-f174a365b1e2.png)

![image](https://user-images.githubusercontent.com/529544/74836418-ba8e2680-5362-11ea-81e0-93b855f5bcd8.png)

**Additional information**
PrestaShop version: (Develop branch)
PHP version: ? (Defined in Docker container)

**Comment by stelgenhof** [comment] 2020-02-19 12:58
Note: The same error also occurs with the `1.7.7.x` branch. I haven't tried any other branches.

**Comment by khouloudbelguith** [comment] 2020-02-19 13:05
Hi @stelgenhof,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #17725
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-19 13:05
Duplicate of #17725

**Closed as completed by khouloudbelguith** 2020-02-19 13:05 UTC
Labels: Duplicate
