### ISSUE TITLE
[ email stock alerts ] no works with combination products

### ISSUE THREAD

**Issue by joaquinpv** [PrestaShop/PrestaShop#10179] opened 2018-08-29 08:07 UTC
Hi,

We have a problem with the stock alert email. **The email does not print the name of a combination product.** 

Only works fine with "simple products".

Can you help me to solve this?

Thanks

**Comment by khouloudbelguith** [comment] 2018-08-29 08:27
Hi @joaquinpv 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9641
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-08-29 08:27
Duplicate of #9641

**Closed as completed by khouloudbelguith** 2018-08-29 08:27 UTC
Labels: Duplicate

**Comment by joaquinpv** [comment] 2018-08-29 08:31
Sorry but i think it is not the same problem...

**Comment by khouloudbelguith** [comment] 2018-08-29 08:59
Hi @joaquinpv,

No, it is the same.
The stock alert email does not print the name of a combination product, only the standard product name, that's why we have a mail alert stock duplicated, we need to add the combinations' name to the email.

Best regards, Khouloud
