### ISSUE TITLE
HSTS preload list submission

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#10687] opened 2018-09-25 08:16 UTC
I use prestashop 1.7.4.2
Apache+nginx
php 7.2.10
I'use cloudflare as cdn
I've enabled HSTS preload, but on this site https://hstspreload.org/?domain=100asa.it for my domain 100asa.it I've always this error message: Error: HTTP redirects to www first
`http://100asa.it` (HTTP) should immediately redirect to `https://100asa.it` (HTTPS) before adding the www subdomain. Right now, the first redirect is to `https://www.100asa.it/`. The extra redirect is required to ensure that any browser which supports HSTS will record the HSTS entry for the top level domain, not just the subdomain.
There is a way via htaccess to redirect http://www to https://www, and http:// to https:// ?

**Comment by khouloudbelguith** [comment] 2018-09-25 08:28
Hi @centoasa,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10482
So, I close it.
Thanks!

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-25 08:28 UTC
Labels: Duplicate

**Comment by YoavRheims** [comment] 2021-07-06 14:17
This is not solved: if the shop is installed with www subdomain, it is impossible to preload the site but if the bare domain is used, there is no issues at all. I'm using the current latest version of Prestashop wich is 1.7.7.5
