### ISSUE TITLE
Cat. select, delete, import...

### ISSUE THREAD

**Issue by benimrumuzum** [PrestaShop/PrestaShop#19104] opened 2020-05-13 09:18 UTC
nothing is working, check screenshots in attach
<img width="1250" alt="Schermafbeelding 2020-05-13 om 11 13 51" src="https://user-images.githubusercontent.com/65281695/81794637-5e731280-950b-11ea-974f-ea32a93cdea6.png">
<img width="1269" alt="Schermafbeelding 2020-05-13 om 11 15 57" src="https://user-images.githubusercontent.com/65281695/81794642-5fa43f80-950b-11ea-99d8-07dccd509012.png">

**Comment by colinegin** [comment] 2020-05-13 10:10
Hello @benimrumuzum ,

Unfortunately I cannot reproduce your problems, as you can see on my screenshots (tested on 1.7.6.5).

![image](https://user-images.githubusercontent.com/35263827/81800182-b3feed80-9512-11ea-8b64-16be4db57f83.png)

![image](https://user-images.githubusercontent.com/35263827/81800282-e6a8e600-9512-11ea-926a-b41bf9d356d2.png)

For this reason, I close the issue, but feel free to re-open it if you have more information to share with us.

Have a nice day,

Coline

**Closed as completed** 2020-05-13 10:15 UTC
Labels: Bug, BO, Categories, Import / Export, No change required, 1.7.6.5
