### ISSUE TITLE
Error while updating to 8.1.0

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#33364] opened 2023-07-25 06:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried 3 possible situations.

1.7.8.8 with PHP 7.4 -> 8.1.0
1.7.8.8 with PHP 7.4 -> 8.0.4, from 8.0.4 and PHP 7.4 to 8.1.0
1.7.8.8 with PHP 7.4 -> 8.0.4, from 8.0.4 and PHP 8.1 to 8.1.0

Autoupgrade 4.16.1 (it worked fine with Autoupgrade 4.16.0 by the way, only with the missing id_employee column as result in order_payment).

All the situations result in the error beneath.

Updating database schema...
Executing: CREATE TABLE ps_authorized_application (id_authorized_application INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_475B9BA55E237E06 (name), PRIMARY KEY(id_authorized_application)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
07:38:41 CRITICAL [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "An exception occurred while executing 'CREATE TABLE ps_authorized_application (id_authorized_application INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_475B9BA55E237E06 (name), PRIMARY KEY(id_authorized_application)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => """ An exception occurred while executing 'CREATE TABLE ps_authorized_application (id_authorized_application INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_475B9BA55E237E06 (name), PRIMARY KEY(id_authorized_application)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n \n SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes """]
In AbstractMySQLDriver.php line 128:An exception occurred while executing 'CREATE TABLE ps_authorized_application (id_authorized_application INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_475B9BA55E237E06 (name), PRIMARY KEY(id_authorized_application)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes In Exception.php line 18:SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes In PDOConnection.php line 141:SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] Errors

### Expected behavior

It should create the table with columns and possible content?

### Steps to reproduce

Normal upgrade procedure with the latest One Click Upgrade module.

### PrestaShop version(s) where the bug happened

1.7.8.8, 8.0.4

### PHP version(s) where the bug happened

7.4, 8.1

### If your bug is related to a module, specify its name and its version

autoupgrade 4.16.1

**Comment by Hlavtox** [comment] 2023-07-25 08:08
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/33021, will be fixed when 8.1.1 is released.

**Closed as completed** 2023-07-25 09:12 UTC
Labels: Bug, Duplicate

**Comment by venditdevs** [comment] 2023-07-25 09:14
Thank you @Hlavtox, i forgot to search in the closed issues.
