### ISSUE TITLE
[autoupgrade] backoffice with two langs after upgrade

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#36828] opened 2024-09-05 07:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

- install a 1.7.8 with english and french. French is the default language.
- Migrate 1.7.8 to 8.1.7 with autoupgrade
- The backoffice menu and parts of legacy controllers are in english.
![image_720](https://github.com/user-attachments/assets/5247d4a1-a123-4983-b093-62f6aa1750da)

### Expected behavior

All BO in french

### Steps to reproduce

- install a 1.7.8 with english and french. French is the default language.
- Migrate 1.7.8 to 8.1.7 with autoupgrade
- The backoffice menu and parts of legacy controllers are in english.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

autoupgrade V6.1

### Your company or customer's name goes here (if applicable).

Creabilis.com

**Comment by Hlavtox** [comment] 2024-09-05 08:20
I think it's a duplicate of https://github.com/PrestaShop/PrestaShop/issues/33321. It happened to me also when upgrading my clients from 1.7.6 to 8.1.5. You must go to languages and update the french language, then it will fix it.

For some magical reason, the tabs are not updated when the autoupgrade module downloads the language pack. I tried to fix it here - https://github.com/PrestaShop/autoupgrade/pull/600, but it did not work for some reason.

Ping @Quetzacoalt91

**Comment by Quetzacoalt91** [comment] 2024-09-05 08:40
The module uses the similar feature of the BO where we load the whole details about a country:

![Capture d’écran du 2024-09-05 09-38-00](https://github.com/user-attachments/assets/797b6a78-7fb3-4a53-8b57-e3920cea5858)

But it appears we should use this feature

![Capture d’écran du 2024-09-05 09-38-13](https://github.com/user-attachments/assets/c113e361-df5c-4875-b991-6a68976f4aa4)

I don't exactly what's under the hood, but only the second panel (**on the second try**) is able to fix the menu translations.

**Comment by jf-viguier** [comment] 2024-09-05 08:44
I've fixed it using the import pack, not the add / Update a language.
BTW it's a regression.

**Comment by Hlavtox** [comment] 2024-09-05 08:47
@Quetzacoalt91 The autoupgrade module is using some custom logic to update the language, but the call is probably missing. See my attempt - https://github.com/PrestaShop/autoupgrade/pull/600/files#diff-832d9a2884d5eeb5ec314fc7d0a4e72a082666d7dfe74dc5b17692415c406155

**Comment by jf-viguier** [comment] 2024-09-05 09:16
it's a duplicate of https://github.com/PrestaShop/PrestaShop/issues/33321 thanks @Hlavtox

**Comment by AureRita** [comment] 2024-09-18 09:47
Duplicate of #https://github.com/PrestaShop/PrestaShop/issues/33321

**Comment by AureRita** [comment] 2024-09-18 09:48
Thank you @Hlavtox

**Closed as completed by AureRita** 2024-09-18 09:47 UTC
Labels: Bug, Duplicate, Autoupgrade, Backlog SUE
