### ISSUE TITLE
Impossible to replace a feature value on import

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#18140] opened 2020-03-13 13:57 UTC
#### Describe the bug

It's impossible to distinguish during the import if we want to replace a feature value with a new feature value or if we want to add a new feature value.

#### Expected behavior

Some setting or import column to tell prestashop how to treat existing features in products - replace feature values or add new feature values.

#### Steps to Reproduce

1. Let's say we have a product with Composition:Cotton feature and we want to change it to Composition:Polyester using import functionality
2. Prepare a simple file to import:
ID;features
1;Composition:Polyester
3. Import the file
4. Instead of replacing Cotton with Polyester, a new value of Polyester gets added to the product, ending up with product having two values for the Composition feature

#### Additional information

* PrestaShop version: 1.7.6.4

**Comment by khouloudbelguith** [comment] 2020-03-17 09:51
Hi @daresh,

Thanks for your report.
Your ticket is a duplicate of #14305
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-17 09:51
Duplicate of #14305

**Closed as completed by khouloudbelguith** 2020-03-17 09:51 UTC
Labels: Duplicate
