### ISSUE TITLE
if a module is disabled it is not possible to see it from the module list - prestashop 8.1.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#33908] opened 2023-09-11 12:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
on prestashop 8.1.1 is not possible to read on the button if a module is disabled or not

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/95cfcf51-f550-49af-b8b4-c418d082cc95)

it is shown the voice "Configure" but should be "Disabled" and "configure" must be in the list with unistall, enable ... 

bye

### Steps to reproduce

1. Go in the module manager
2. disable a module
3. see that the voice report Configure instead of Disabled and Configure should be in the list together reset, unistall ...

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2023-09-11 14:26
Duplicate of https://github.com/PrestaShop/PrestaShop/discussions/33462, expected behavior.

**Comment by Maofree** [comment] 2023-09-11 14:38
Hi
it is not useful to show all configure voices in the modules list, it is not possible to understand what are the disabled modules, to find out I need to check one module at a time. I saw that in 8.1.2 you will go back to classic mode

**Comment by sallemiines** [comment] 2023-09-11 14:58
Duplicate of #33462

**Closed as completed by sallemiines** 2023-09-11 14:58 UTC
Labels: Bug, Duplicate

**Comment by MatShir** [comment] 2023-09-12 08:21
Agree with @maofree !
What is blocking your PR @Hlavtox ? :/

**Comment by Hlavtox** [comment] 2023-09-12 09:14
@MatShir The label doesnt change dynamically, it will need more work to make it. I will have a look. :-)
