### ISSUE TITLE
Shopping cart product increase / decrease is double

### ISSUE THREAD

**Issue by Marko-fin** [PrestaShop/PrestaShop#14759] opened 2019-07-18 23:34 UTC
**Describe the bug**
After products are added to shopping cart, and user navigates to shopping cart, user can still add / remove more same items with increase / decrease arrows.

The item counter has duplicate increase / decrease arrows, a smaller copy is inside item count, that is barely clickable by mouse, and it also hides item count when item count is more than one digit.

**To Reproduce**
1. Add any item to shopping cart
2. Go to shopping cart
3. Increase items in shopping cart by using "^" arrow for two digit amount -> item count is partly hide behind small "box"
4. notice also that inside item count is small "box" that is actually very small duplicate item increase / decrease arrows 

**Screenshots**
![prestashop-1-7-6-1](https://user-images.githubusercontent.com/52843932/61498870-54ed4c80-a9c5-11e9-9d5f-8960eb4a95fe.jpg)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6.40-0+deb8u4

**Comment by Marko-fin** [comment] 2019-07-18 23:36
With very accurate mouse control, you can increase / decrease item count with this small box inside item count

**Comment by khouloudbelguith** [comment] 2019-07-19 07:34
Hi @Marko-fin,

What is the exact browser did you use?
I did not manage to reproduce the issue with Chrome browser & it is fixed in the firefox browser in PS1.7.6.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/14395

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-19 07:47
Hi @Marko-fin,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-19 07:47 UTC
Labels: Bug, FO, No change required, Shopping carts FO, 1.7.6.0
