### ISSUE TITLE
Translations with variable are not updated

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15257] opened 2019-08-26 09:29 UTC
**Describe the bug**
Strings with variables inside (%name%) don't get saved on back office translation interface.

You can find the string, translate it, save it, it shows green confirmation message, but the string is not saved to the database.

You must use a custom theme and new custom string.

After manual insert to database and clearing the cache, the string gets loaded.

@eternoendless Seems like a different issue than the one we discussed before. In #15075, they don't get loaded at all. Here, it's just not saved.

See attached video:
https://drive.google.com/file/d/110cGhvMDoT14j2Dgn_ZJkGE4N2FYA3yd/view?usp=sharing
(watch in 1080p)

**Additional information**
PrestaShop version: 1.7.6

**Comment by khouloudbelguith** [comment] 2019-08-26 10:48
Hi @Hlavtox,

I did not maange to reproduce the issue with PS1.7.6.0 & PS1.7.6.1build1 & the 1.7.6.x branch.
I attached a screen record
https://drive.google.com/file/d/1GollkHJLek_-mo1Oz9_ktIkUK0S7R84j/view
In your BO => International => Translations => are you translating a custom module or a theme?

Thanks!

**Comment by Hlavtox** [comment] 2019-08-27 08:20
@khouloudbelguith 

Use custom theme, for example classic-rocket.

And you must create a new string in the template.

This normally works for all other custom new strings in TPLs, it even shows up, but from some reason, it doesn't get saved. After saving to database manually, the translation shows up. As in the video.

**Comment by khouloudbelguith** [comment] 2019-08-27 10:28
@Hlavtox, it is OK with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/168W_LsX30pT-4eiSfTemDZdsPrInSqGi/view
Thanks to check & feedback.

**Comment by Hlavtox** [comment] 2019-09-03 09:46
@khouloudbelguith I will try it with 1.7.6.1 and let you know :-)

**Comment by khouloudbelguith** [comment] 2019-09-03 09:49
@Hlavtox, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-10-03 08:13
Hi @Hlavtox,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-03 08:13 UTC
Labels: Bug, FO, Translations, No change required, 1.7.6.0
