### ISSUE TITLE
BO - Tax Rule is applied on product page V2 - It shouldn't because the default country is different from the country where the tax rule is applied

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27054] opened 2021-12-22 10:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

BO - Tax Rule is applied on product page V2 - It shouldn't because the default country is different from the country where the tax rule is applied

Specs: https://build.prestashop.com/prestashop-specs/1.7/back-office/catalog/products/add-edit-v2.html#retail-price
### Expected behavior

It will display the shop's country and its related tax rate. If there is none configured for this specific country, we will display 0%

![Capture d’écran 2022-01-24 à 18 09 32](https://user-images.githubusercontent.com/43613217/150830692-c3100e35-1877-497a-8773-1e6a8e6c12fb.png)

### Steps to reproduce

1. Go to BO > International > Localization & check that the `Default country = France` 
![image](https://user-images.githubusercontent.com/16067358/147078112-1511552e-aa7e-4837-91ba-0833e66144e7.png)
2. Go to BO > International > Taxes > Tax rules page & Create a Tax rule for Algeria  
![image](https://user-images.githubusercontent.com/16067358/147078258-80e6b4ce-c96a-42c0-92cc-f516ef46395a.png)
3. Go to BO > Catalog > Products V2 > Princing tab and change the tax rule to the last one created
4. See error => Tax rule is applied, it shouldn't 
![image](https://user-images.githubusercontent.com/16067358/147078443-3f8a26c6-596e-4420-b0a1-ab99822376a7.png)
5. If this PR https://github.com/PrestaShop/PrestaShop/pull/26762 is merged => same issue on the `Retail price per unit` 
![image](https://user-images.githubusercontent.com/16067358/147078644-df4ed4d7-b368-4bbb-a37d-57ea9b41201a.png)

In the Product V1 => ok 
![image](https://user-images.githubusercontent.com/16067358/147078727-4973a60f-5703-4015-9f85-3626265859bc.png)

> Edited by Khouloud

### Other Steps to reproduce a similar issue: 

reported previously here: https://github.com/PrestaShop/PrestaShop/pull/27233#pullrequestreview-916147184 and here: https://github.com/PrestaShop/PrestaShop/pull/27233#pullrequestreview-867695501 "Third issue"

The tax is updated with every refresh of the page when using theses configuration for the tax rule : 
1. Create a tax rule that uses different taxes for different Countries 
![image](https://user-images.githubusercontent.com/92912932/159333091-00a61ca6-b9f4-4a74-a2bd-08cb8de06fef.png)
2. Create a tax rule that uses a One by One Tax 
![image](https://user-images.githubusercontent.com/92912932/159333534-8f23a6dd-1c60-4193-bf04-c0bda626f003.png)

3. Create a tax rule that uses a tax with Combine 
![image](https://user-images.githubusercontent.com/92912932/159333381-22994e5f-b70d-425e-8a11-a65dc6f9be56.png)

4. Create a tax rule that uses different taxes for different States as described [here](https://github.com/PrestaShop/prestashop-specs/pull/316/files?diff=split&w=0#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R47)
5. Create for each tax rule product with different tax rules
6. Save
7. Refresh
8. See error => the tax rule is changed 

https://user-images.githubusercontent.com/92912932/159329718-3a369bba-f618-4337-b62f-6c289e612e6a.mp4
### PrestaShop version(s) where the bug happened

> Edited by Khouloud

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-986520326

1. Go to BO > Taxes > Taxes rule & create a tax rule with combine 10% + 20% = 30%
2. In the BO > Taxes > Enable ecotax with tax rule = combine de tax
3. Go to BO > Create a product V2 > In the pricing tab
4. The ecotax rate displayed = 20% => NOK / it should be 30%
5. also, if I add ecotax = 1 tax excluded => it is displayed 1.2 tax included  / it should be 1.3 tax included

https://user-images.githubusercontent.com/16067358/170534006-1a35ae67-a97a-4be6-a3b2-e8291217cd71.mp4

1.7.8.1, develop

### PHP version(s) where the bug happened

10.3

**Comment by jolelievre** [comment] 2021-12-22 11:41
Hmmm, I'm not sure it's really a bug on new page or a bug on former page 😅

It seems logical that the BO page applies the tax that was selected. It's another issue to see if it should be applied on FO depending on your country. The fact that the shop default country is France doesn't mean it will be the case for the customer so IMHO it would be more convenient for the merchant to edit his product with the tax he selected.

But that's something to discuss with @PrestaShop/product-team

**Comment by Hlavtox** [comment] 2021-12-22 12:57
@jolelievre The problem is that you can have different tax rates for every country, so what tax rate it should use in BO? 😁 Algerian, French or none?

I think the previous behavior (default shop country simulation in BO) was the only one that made some sense, otherwise the software would need a crystal ball to know what rate to use.

**Comment by jolelievre** [comment] 2021-12-22 13:49
Well to me you apply the tax that you selected... and that's it. The differences in the FO depend on the FO context anyway.

So if we follow the legacy logic:
- when you have French country as the default country only french taxes will be interpreted in the BO when the merchant edits his product
- but in the FO when someone selects another country then the taxes are not applied so there is a difference between BO and FO

If we follow the alternative logic (currently on new page):
- regardless of the shop country you can see the impact of the tax you selected
- in FO the tax may or maybe not be applied so there will be a difference

In both cases anyway, there will be differences. We can't avoid this since taxes are associated with the country from the context. But you can't guess it in the BO, so never displaying the value with tax is as incorrect as displaying always displaying it.

So since we are bound to have differences between BO and FO at least let's make the merchant's job a bit easier and let's let him edit his product with the tax he assigned to it.

Ideally, we would need a preview in the product page that allows you to select a country and see the price, but only as preview (and it would be a new feature). Or maybe even we should be able to edit the associated tax depending on the country. But all these are new features anyway so it would require a refacto and a new feature in a future version.

**Comment by Hlavtox** [comment] 2021-12-23 15:07
> regardless of the shop country you can see the impact of the tax you selected

You cannot do it unless you implement a preview feature where you select something like "Preview final tax for country XXX". If you want to preview a tax, it must be for the default country.

Imagine you have a tax rule called "Standard tax rule". It's set up like this:
- Algeria = 21%.
- Czech republic = 22%.
- France (default country) = 23%
- Belgium = 24%.

The current product page randomly applying Algerian coefficient of 21% is **definitely a bug**. So right now, it should be 23%, for the default country, or nothing, if the default country is not in the tax rule country set.

**Comment by MatShir** [comment] 2022-01-24 17:12
We will display the shop's country and its related tax rate. If there is none configured for this specific country, we will display 0%
![Capture d’écran 2022-01-24 à 18 09 32](https://user-images.githubusercontent.com/43613217/150830692-c3100e35-1877-497a-8773-1e6a8e6c12fb.png)
The list by country could be cool, but it is definitely a nice to have. I don't really see merchants checking the price for each country since he can really edit it. The killer feature would be to do fixed price with the tax incl for each country.

**Comment by Hlavtox** [comment] 2022-01-24 18:34
@MatShir Good!

Maybe we could try to think about it in a broader scope.
- Button called "Price preview", "Do you want to check what exact price will certain customer group or country see?"
- Modal opens, you select country, group, zone etc.
- Product::getPrice will get called with these parameters.
- "In this case, the product price will be XXX".

But maybe I am just dreaming and nobody would use it :D

**Comment by jolelievre** [comment] 2022-01-25 12:05
@Hlavtox I don't think we will have time to integrate this feature but it's a good idea

Besides, the new product page will integrate a small resume block so I guess we could use it to display this price preview We would need to add the selectors you mentioned and bind an ajax call to update the preview (maybe an additional dedicated preview block would be good to avoid messing with the current page resume).

But as I said our hands are already full on this page, but if you're motivated to do it feel free to open a PR.

But maybe wait until the new price display and resume are integrated into the page.

**Comment by MatShir** [comment] 2022-03-16 11:46
> **Fifth issue**
> 
> 1. Go to BO > International > Taxes > Tax rules page
> 2. Create a new tax rule with the behavior: Combine & One After Another
> 
> ```
> Behavior. Some customers might have an address that matches more than one of your tax rules. In that case, you can choose how this tax rule should behave:
> This Tax Only. Will apply only this tax, not any of the other matching taxes.
> Combine. Combine taxes. For instance: 100€ + (10% + 5% => 15%) => 115€.
> One After Another. Apply taxes one after another. For instance: 100€ + 10% => 110€ + 5% => 115.5€.
> ```
> 
> ![image](https://user-images.githubusercontent.com/16067358/158430736-254525bc-d1d4-4ba5-a7a9-d286a524ae4a.png) 3. Create a product V2 with this tax rule and save ![image](https://user-images.githubusercontent.com/16067358/158431403-c6129e39-f07d-4a60-8642-b9d887005017.png) 4. See an error in the header => ![image](https://user-images.githubusercontent.com/16067358/158431864-72a81d1f-c8df-4e6b-a063-3c17f859fa44.png)

Another use case to handle from https://github.com/PrestaShop/PrestaShop/pull/27233

**Comment by jolelievre** [comment] 2022-10-28 16:19
Closed by https://github.com/PrestaShop/PrestaShop/pull/29084

**Closed as completed by jolelievre** 2022-10-28 16:19 UTC
Labels: Bug, Minor, BO, Tax rules, Taxes and Prices, Regression, migration, Verified
