### ISSUE TITLE
In the BO order page, the export will always export the first page

### ISSUE THREAD

**Issue by chrisvanberg** [PrestaShop/PrestaShop#28182] opened 2022-04-08 10:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the back office on the orders page, when you try to export a page, it is always the orders on the first page that are exported.

### Expected behavior

The export should contain the commands of the active page.

### Steps to reproduce

1. Go to the order page
2. Navigate through the second page for example
3. Use the export function
4. Compare the orders listed on the BO and those in the .csv

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by khouloudbelguith** [comment] 2022-04-08 11:29
Hi @chrisvanberg,

We are aware of this issue, and it is added to our debug roadmap.
Your ticket is a duplicate of #19527
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2022-04-08 11:30
Duplicate of #19527

**Closed as completed by khouloudbelguith** 2022-04-08 11:29 UTC
Labels: Bug, Duplicate, Order, Import / Export, Invalid

**Comment by chrisvanberg** [comment] 2022-04-08 11:35
Hi @khouloudbelguith 

Oh, I'm sorry, I did not see that issue when I was looking if it was already reported.

Thanks
