### ISSUE TITLE
checkCreatePrivilege must check for priviledges for both InnoDB and MyISAM

### ISSUE THREAD

**Issue by bvellacott** [PrestaShop/PrestaShop#20676] opened 2020-08-22 18:04 UTC
Google Cloud SQL doesn't support MyISAM, so the create checks fail and installation is blocked.

Solution: Check for create privilege using InnoDB engine also in the methods at:

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/db/DbPDO.php#L362
and
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/db/DbMySQLi.php#L404

**Comment by khouloudbelguith** [comment] 2020-08-24 08:12
Hi @bvellacott,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14402 to fix the issue.
Your ticket is a duplicate of #12675
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-24 08:12
Duplicate of #12675

**Closed as completed by khouloudbelguith** 2020-08-24 08:12 UTC
Labels: Duplicate
