### ISSUE TITLE
Runtime Error upgrading blockwishlist module from 1.3.2 to 2.0.0

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/PrestaShop#24570] opened 2021-05-19 14:37 UTC
#### Describe the bug

I am on PS 1.7.6.7  (I plan to upgrade to 1.7.7.4 soon).
I tried to upgrade blockwishlist from 1.3.2 to 2.0 and the result is a red box with generic error message (something like "cannot install undefined module").
Refreshing the page (and navigating to any adm panel section result in a runtime error  `An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blockwishlist_configuration" as such route does not exist.").`

To recover from that I have to restore the updated files or rename the module folder to something else.

What is wrong with my approach?
Thanks in advance!

* PrestaShop version: 1.7.6.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-05-19 21:31
Hello @masiorama 

Your issue is a duplicate of this one #24321
But unfortunally the author doesn't respond me, so could you please answer my question in the other issue :pray: 

_PS: I close this one as a duplicate, so please subscribe to the issue mentioned above._

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-19 21:31
Duplicate of #24321

**Closed as completed by hibatallahAouadni** 2021-05-19 21:31 UTC
Labels: Duplicate
