### ISSUE TITLE
filter only attributes with available quantities (do not show attributes with zero quantities) - ps_facetedsearch v3.13.2 - prestashop 8.1.1

### ISSUE THREAD

**Issue by SALV-RM** [PrestaShop/PrestaShop#34340] opened 2023-10-19 10:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
I have a problem with my site (prestashop 8.1.1), with the search form for aspects:
- the problem is with the "product filter". I select size 43, but size 43 is not available (it has zero quantity); I would like only the sizes with available quantities to be "filtered".
SCREEN: 
https://drive.google.com/file/d/1j5GmP6dhHjvjJtcI4wNX96KEBlXlGdPq/view?usp=sharing
Regards

### Expected behavior

I would like only the sizes with available quantities to be "filtered".

### Steps to reproduce

1. go to category (man or woman) 
2. filter size 43
3. the product is displayed, but size 43 has zero quantity

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.24

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.13.2

**Comment by Hlavtox** [comment] 2023-10-19 11:40
Expected behavior, you didn't tell the filter you want to show just the sizes in stock.

**Comment by SALV-RM** [comment] 2023-10-19 15:32
HI,
Yes. If I add the "stock" section to the filter, the filter works. I would like the same result without selecting the "available" item in the stock section. 
Is this not possible with this module? 
Do I have to purchase a paid module on prestashop addons?
Thank you 
Regards

**Comment by AureRita** [comment] 2023-10-23 10:09
Hi @SALV-RM 

Thank you for your report, I tried to reproduce your issue and I reproduce it, as you can see : 

[Untitled_ Oct 23, 2023 12_02 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4b82b4c3-05d0-40e4-8af1-fb4d4d093b8e)

But, as said @Hlavtox and as you can see in the end of the video, you've a section to select only the "in stock" product. 
This is because if your customer wants to have an alert when the product returns, if you can't show them the possibility of having an alert on that product, then they won't be notified for the return of the product. 

Because this one is an expected behavior, I'll close it, 

Thank you

**Closed as completed** 2023-10-23 10:09 UTC
Labels: Bug, Invalid
