### ISSUE TITLE
button-autoupgrade - link dont work

### ISSUE THREAD

**Issue by forpaolo-hub** [PrestaShop/PrestaShop#36765] opened 2024-08-27 09:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

button-autoupgrade - link dont work

### Expected behavior

Simply when i click on link autoupgrade the download dont start.

### Steps to reproduce

-Click Upgrade
Checklist OK
UPDATE PRESTASHOP NOW
THE LINK DONT' WORK

### PrestaShop version(s) where the bug happened

8.1.4 >  (8.1.7)

### PHP version(s) where the bug happened

8.1.29

**Comment by AureRita** [comment] 2024-09-03 15:11
Hi @forpaolo-hub 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(280).webm](https://github.com/user-attachments/assets/333b7499-5461-465d-9618-aef6dea26ca8)

Can you provide more information like : 
- Provide us a video
- Provide us what the button send (thank to your inspector) 

Waiting for feedback

**Comment by forpaolo-hub** [comment] 2024-09-04 06:55
Now I have solved the problem by changing the default language of my superadmin account, setting it to English as soon as I start the update. In Italian language the updated button in the Click-Upgrade plugin does not work

**Comment by Quetzacoalt91** [comment] 2024-09-05 09:31
Hi @forpaolo-hub, the upgrade can start even though the language of the back-office is Italian.

[Capture vidéo du 2024-09-05 10-26-33.webm](https://github.com/user-attachments/assets/45fcde78-56c8-405f-b094-7d307eedf63f)

You probably had an issue on the HTTP request starting the upgrade process, it may happen sometimes and no error appears on the page in this case.
I'm closing the issue until you meet the error again. At that moment, check in your browser console the response of the last ajax request, in which you should see the reason of the error.

**Closed as not planned by Quetzacoalt91** 2024-09-05 09:31 UTC
Labels: Bug, Waiting for author, BO, Autoupgrade, Module, 8.1.x
