### ISSUE TITLE
Not possible to upgrade multiple modules at once

### ISSUE THREAD

**Issue by bullmade** [PrestaShop/PrestaShop#29671] opened 2022-09-16 21:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

it is not possible to upgrade multiple modules at once. This has been an issue since early versions of PS 1.7.

If you try, this is the result you will get.
![image](https://user-images.githubusercontent.com/16975198/190804947-ce215180-31e3-4614-bc6f-e7849e6f9981.png)

If it is a thing that is done on purpose, then atleast the "Upgrade" buttons should not be clickable while anothe upgrade is being performed.

### Expected behavior

Expects it to update, even when multiple upgrades are initiated.

### Steps to reproduce

1. Have atleast 2 modules that needs to be upgrade.
2. Click on "Upgrade" on both modules.

### PrestaShop version(s) where the bug happened

1.7+

### PHP version(s) where the bug happened

7.2,7.3,7.4

**Comment by paulnoelcholot** [comment] 2022-09-19 09:27
Hello @bullmade 

This issue is a duplicate of this one https://github.com/PrestaShop/PrestaShop/issues/14722 and as you can see we were not able to reproduce the issue.
And, we encounter the same on PS8.0.0 (see this issue https://github.com/PrestaShop/PrestaShop/issues/29517), fortunally the issue has been fixed with this PR https://github.com/PrestaShop/PrestaShop/pull/29512
So, closing the issue as not reproduced on PS1.7 and as Fixed on PS8.


Thanks!

**Comment by paulnoelcholot** [comment] 2022-09-19 09:28
Duplicate of #14722

**Closed as completed by paulnoelcholot** 2022-09-19 09:27 UTC
Labels: Bug, Duplicate, Invalid
