### ISSUE TITLE
Bankwire account details can be filled and saved with "blank"

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#30142] opened 2022-10-28 09:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When editing the account details, it is possible to "fill" every of the 3 form fields with just a space and save
And the form is validated with "blank" informations

https://user-images.githubusercontent.com/40635814/198550241-72f23151-9024-4712-bc08-45da0f47ad55.mp4

### Expected behavior

It should not be possible to have "blank" fields when save the form

### Steps to reproduce

1. Go to BO => module Manage => bank transfer module
2. In the account details form just fill all the field with a space
3. Try to save the form
4. See Error  => the form is validated with "blank" fields

### PrestaShop version(s) where the bug happened

develop && 8.0.x && 1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_wirepayment 2.1.3

**Comment by Hlavtox** [comment] 2022-10-28 09:42
Well, for example in our country, we only need to provide the account number, nothing else, so it's good that I can leave it blank I think. 🤷 Too bad the fields are displayed anyway, as empty, in frontoffice.

**Comment by hibatallahAouadni** [comment] 2022-10-28 16:33
Hello @SD1982 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28351. 
The issue has been fixed with this PR https://github.com/PrestaShop/ps_wirepayment/pull/77 (it will be released in v2.1.4). 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-10-28 16:34
Duplicate of #28351

**Closed as completed by hibatallahAouadni** 2022-10-28 16:33 UTC
Labels: Bug, BO, Duplicate, Bankwire, 1.7.7.0, Invalid, Module
