### ISSUE TITLE
Product Search doesn't work when adding new order in backoffice PS 1.7.8.8 - B2B mode enabled

### ISSUE THREAD

**Issue by FranckCapoweb** [PrestaShop/PrestaShop#31957] opened 2023-03-29 08:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

## PROBLEM
After upgrading to PS 1.7.8.8, when we try to add an order from backoffice, the product search field doesn't return any results and seem being stuck.

There is a 500 error code :
`Type error: Argument 6 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\FoundProduct::__construct() must be of the type float, null given, called in /src/Adapter/Product/QueryHandler/SearchProductsHandler.php on line 203`

After investigation, the problem seems to come to the fact that B2B mode return an NULL taxRate value and he expect a float.

## FIX 
We can make $taxRate nullable in `src/Core/Domain/Product/QueryResult/FoundProduct.php` at **line 108**:

- :x: `float $taxRate,`
- :heavy_check_mark: `?float $taxRate,`

And we need to do the same at **line 187** for the **getTaxRate()** function :

- :x: `public function getTaxRate(): float,`
- :heavy_check_mark: `public function getTaxRate(): ?float,`

### Expected behavior

Return product list when we start typing.

### Steps to reproduce

1. Your shop need to have B2B enabled
2. Go to BO and add a new order
3. Choose a customer account
4. Try to start typing in product search input

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3

**Comment by paulnoelcholot** [comment] 2023-03-29 09:25
Hello @FranckCapoweb 

I have tested your issue and I can't reproduce the bug as you can see here : 
https://watch.screencastify.com/v/vYyWy08AxVraEA8poUCd

From which version are you doing the autoupgrade?

Thanks

**Comment by FranckCapoweb** [comment] 2023-03-29 11:38
> Hello @FranckCapoweb
> 
> I have tested your issue and I can't reproduce the bug as you can see here : https://watch.screencastify.com/v/vYyWy08AxVraEA8poUCd
> 
> From which version are you doing the autoupgrade?
> 
> Thanks

Hello @paulnoelcholot
I upgraded from 1.7.6.9

**Comment by AureRita** [comment] 2023-04-04 12:18
Hi @FranckCapoweb 

I do an autoupgrade from 1.7.6.9 to 1.7.8.8 and I can use the search bar on the order, as you can see : 

[Untitled_ Apr 4, 2023 2_17 PM.webm](https://user-images.githubusercontent.com/100699445/229789085-0fa1df3c-5deb-4468-a52e-ff366931fbbc.webm)

Did I miss something ? 

Waiting for your feedback

**Comment by hibatallahAouadni** [comment] 2023-04-17 10:06
Hello @FranckCapoweb 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-04-17 10:06 UTC
Labels: Bug, BO, Order, Invalid, 1.7.8.8
