### ISSUE TITLE
Product is created when clicking save, even if missing required fields.

### ISSUE THREAD

**Issue by OneDotIT** [PrestaShop/PrestaShop#14265] opened 2019-06-18 11:46 UTC
**Describe the bug**
Whenever 'Save' is clicked, a new product is created, even if the required fields are empty and an error pop-up appear.
Afterwards, the product is visible as an empty box with no values at FO, and the product do not appear on the BO, not as active or as disabled.

**To Reproduce**
Steps to reproduce the behaviour:
1- Create a new product.
2- Click save.
3- Go back to FO, and check under 'Popular Products' section.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 5.6.40

Debugging the issue, each product has a corresponding 2 columns, 'active' and 'state', if the product is active '1', it must have a state of '1', if it not active '0', then the state must be set to '0'.
The issue is represented when we have an active statue of '1', and state of '0'.
Example:
+------------+----------+--------+-------+
| id_product | price    | active | state |
+------------+----------+--------+-------+
|         50 | 0.000000 |      0 |     0 |
|         54 | 0.000000 |      1 |     0 |
|         55 | 0.000000 |      1 |     0 |
|         56 | 0.000000 |      1 |     0 |
+------------+----------+--------+-------+
Products of id's: 54,55,56 are visible as empty black box in FO and not accessible in BO.

and to fix, I had to update the table 'state' to '1' and then delete the product from the BO.
The product shouldn't' have been created at the first place.
Use the following SQL statement to check if this issue is represented in your table:
`SELECT id_product, price, active, state FROM ps_product WHERE state=0 AND active=1;`

**Comment by Quetzacoalt91** [comment] 2019-06-18 11:49
Actually, the product is created in database as soon as you click on "New product". We are aware that's is not how it should work, but that was a "hack" to allow combinations, images an so on to to work immediately (= without refreshing the page).

**Comment by khouloudbelguith** [comment] 2019-06-18 12:23
Hi @OneDotIT,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9945
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-18 12:23
Duplicate of #9945

**Closed as completed by khouloudbelguith** 2019-06-18 12:23 UTC
Labels: Duplicate
