### ISSUE TITLE
Version number of upraded module does not change until refresh

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20725] opened 2020-08-26 11:25 UTC
#### Describe the bug

1. Go to modules page.
2. Click upgrade button on some module.
3. Version number does not change.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by matks** [comment] 2020-08-26 11:51
I could add to this bug:

1. Go to modules page.
2. Install some module.
3. After installation is complete, use search bar to "search" for this module you cant find it. You must refresh first.

Basically the page does not refresh upon action completion.

One easy and dirty way to fix it would be ... to force refresh 😅  😋

**Comment by Hlavtox** [comment] 2020-08-26 11:52
@matks That's what I was thinking, but you could have some bulk module actions in progress :-D

**Comment by khouloudbelguith** [comment] 2020-08-26 12:03
Hi @Hlavtox,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16066
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-26 12:04
Duplicate of #16066

**Closed as completed by khouloudbelguith** 2020-08-26 12:03 UTC
Labels: Duplicate
