### ISSUE TITLE
Free orders can't be placed when Terms and conditions is not shown

### ISSUE THREAD

**Issue by gvaianella** [PrestaShop/PrestaShop#21476] opened 2020-10-16 10:18 UTC
#### Describe the bug

When creating a free order (ie, total price = 0) there is an error since there is no payment option being shown.
The weird thing (what it does the bug probably very easy to fix) is that free orders can be placed if the configuration is set to show the Terms and conditions checkbox.

#### Expected behavior

Even though the shop doesn't show the Terms and conditions checkbox, it should allow to complete a free order.

#### Steps to Reproduce

1. Create a product with price 0.
2. Have the shop configured to not show Terms and conditions.
3. Try to complete an order adding just the free product added in step 1.

#### Additional information

* PrestaShop version: 1.7.x

**Comment by florine2623** [comment] 2020-10-16 11:30
Hi @gvaianella ,

Thanks for the report. I reproduced this in PS 1.7.6.8 and PS 1.7.7.0.
![Capture d’écran 2020-10-16 à 13 30 13](https://user-images.githubusercontent.com/16019289/96253374-c4306280-0fb3-11eb-8d8e-c6db48c22308.png)

 I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2020-10-16 12:37
Duplicate of #9927

**Closed as completed by marionf** 2020-10-16 12:37 UTC
Labels: Bug, Minor, FO, Duplicate, Order, Order settings, 1.7.7.0, 1.7.6.8
