### ISSUE TITLE
Blank page on Clear Cache Prestashop

### ISSUE THREAD

**Issue by hks27d** [PrestaShop/PrestaShop#21022] opened 2020-09-16 15:23 UTC
#### Describe the bug

I go to Advanced Parameters -> Performance -> Clear cache
The website then shows a blank page. Then if I go to AdminCP again, to Advanced Parameters -> Performance, Prestashop says: All caches cleared successfully
The issue the following one: I have a blank page everytime I clear cache.
I've tried on fresh new installations of Prestashop and it's the same.

#### Expected behavior

Explain what you expected to happen instead.
The function should funcion normal. It should show a refreshed page of AdminCP with the message: All caches cleared successfully.
Instead, the page just go BLANK (Full white background).

#### Steps to Reproduce

1. Go to 'Advanced Parameters -> Performance'
2. Click on 'Clear cache'
3. See blank page

**Screenshots**
There's no need for screenshots.

#### Additional information
Template compilation: Recompile the files if the files have been updated
Cache: Yes
Multi-front optimizations: Yes
Caching type: File System
Clear cache: Clear cache everytime something has beed modified

* PrestaShop version: 1.7.5.2 and 1.7.6.7. I've tried to replicate the issue on both versions. It's still there.
* PHP version: 7.2.33. I've tried other PHP versions too.
* MySQL version: 10.2.33-MariaDB-log 
* Browser: Mozilla. I've tried on Chrome too.
* Server software version: Apache

* Memory limit: 4G
* Max execution time: 300
* Upload Max File size: 512M

**Comment by Hlavtox** [comment] 2020-09-17 11:03
@hks27d Hi, this was a bug, if you had debug mode on, it would throw an error. (https://github.com/PrestaShop/PrestaShop/issues/11105) It is fixed in next versions of PS.

Try to apply this change and try to delete the cache, it will work. :-) https://github.com/PrestaShop/PrestaShop/pull/20689/files

**Comment by hks27d** [comment] 2020-09-17 18:02
Hello! Thanks a lot for your reply.

Then why the file is not updated with all the modifcations done?
Is PrestaShop 1.7.7.0 the same? Does it have the same issue where we have to fix it by ourselves?

Thank youf or your time!

**Comment by khouloudbelguith** [comment] 2020-09-25 08:58
Hi @hks27d,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/20689 to fix the issue.
It is fixed in 1780.
Your ticket is a duplicate of #11105
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-25 08:58
Duplicate of #11105

**Closed as completed by khouloudbelguith** 2020-09-25 08:58 UTC
Labels: Duplicate

**Comment by Hlavtox** [comment] 2020-09-25 14:05
@hks27d Because it was fixed last week, after 1.7.7 beta was released. It will be in some of the next official releases.
