### ISSUE TITLE
Activating / Deactivating Product from product listing resets unit_price_ratio to 0

### ISSUE THREAD

**Issue by artaban** [PrestaShop/PrestaShop#20679] opened 2020-08-23 18:12 UTC
#### Describe the bug

When the product is activated / deactivated from the product listing page, the `unit_price_ratio` is reset to 0

#### Expected behavior

The `unit_price_ratio` would be kept

#### Steps to Reproduce

1. Set unit price for a product to 10
2. Go to product listing page
2. Click on check / cross icon to activate / deactivate product
3. Navigate to product detail page Prices tab
4. The Unit price value is 0

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3.14

**Comment by khouloudbelguith** [comment] 2020-08-24 08:35
Hi @artaban,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10792
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-24 08:35
Duplicate of #10792

**Closed as completed by khouloudbelguith** 2020-08-24 08:35 UTC
Labels: Duplicate, Fixed
