### ISSUE TITLE
ps 1.7.6.3 "Kritik Hata: ISO kodu doğru değil"

### ISSUE THREAD

**Issue by ibrahimfsasmaz** [PrestaShop/PrestaShop#17380] opened 2020-01-28 09:42 UTC
When I first enter the site, at white screen I am having that error, When I try to enter second time it works. I am loosing all my customers coming from adds, I need urgent help pls.

To reproduce issue pls go to www.npopi.com , and to reproduce again pls clear cache and try again.

![Screen Shot 2020-01-28 at 12 01 20](https://user-images.githubusercontent.com/58822578/73252258-84c6a980-41cb-11ea-82aa-4e16c6645bb2.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2020-01-28 09:53
Hi @ibrahimfsasmaz,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-27 07:59
Hi @ibrahimfsasmaz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-27 07:59 UTC
Labels: Bug, FO, No change required, 1.7.6.3
