### ISSUE TITLE
Product Search doesn't work when adding new order or existing order in backoffice PS 1.7.8.9

### ISSUE THREAD

**Issue by buddystime8** [PrestaShop/PrestaShop#33269] opened 2023-07-16 08:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

i have installed prestashop latest version 1.7.8.9 and migrated data from old version 1.7.2.4 everything works well but only issue with backoffice order Product Search doesn't work when adding new order and adding products to existing orders  in backoffice PS 1.7.8.9
when debub it and on dev tools in Chrome show 500 error when i click on it so its show this error 
type error: argument 8 passed to prestashop\prestashop\core\domain\product\queryresult\productcombination::__construct() must be of the type string, null given, called in /home/avalonde/public_html/src/adapter/product/queryhandler/searchproductshandler.php on line 273

### Steps to reproduce

1. Go to backoffice 
2. Click on order section 
3. Try to add new order from backoffice and select customer and try to add product but its can't add product
4. or Go to existing order and try to add product to existing order its can't search products 
5. but on my old version 1.7.2.4 everything works well only issue in migrated version 

### PrestaShop version(s) where the bug happened

Migrated data from 1.7.2.4 to 1.7.8.9 version

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment] 2023-07-17 13:51
Hi @buddystime8 

Thank you for your report, but currently I can't reproduce your issue, 

can you give us the version of the module "1 clic upgade" you used ? 
Can you provide us some screen of video ? 

Thank you 
Waiting for your feedback

**Comment by buddystime8** [comment] 2023-07-17 14:18
i haven't upgraded my PrestaShop version i have installed prestashop latest version 1.7.8.9 and through Migration 4.0 module i have migrated my data from my old version1.7.2.4

**Comment by buddystime8** [comment] 2023-07-17 14:25
But i have fixed that issue temporarily by this command 
ps_product_attribute` SET `reference` = ''
and its fixed my issue now i will be able to add product to existing order or add product product to new backoffice order

**Comment by AureRita** [comment] 2023-07-17 14:47
It's a little bit strange, I didn't reproduce your issue with a new version of 1.7.8.9. I think this issue can be related to the module you use. 

Did you reproduce this issue with only a prestashop without this module ? 

Waiting for your feedback

**Comment by buddystime8** [comment] 2023-07-17 15:01
ofcourse i will reproduce this issue for you even i have installed latest version 1.7.8.9  i have tested it everything works fine but when i migrated my products from old shop to this new so it stopped working mean unable to add product to existing order especially facing this issue products with combinations

**Comment by florine2623** [comment] 2023-07-25 12:39
Hello @buddystime8 ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing the issue to avoid clogging the backlog.

Thank you

**Closed as completed by florine2623** 2023-07-25 12:39 UTC
Labels: Bug, BO, Order, Autoupgrade, Invalid, Module, 1.7.8.9
