### ISSUE TITLE
Can't install Prestashop 1.7.7.5 COMPOSER

### ISSUE THREAD

**Issue by thedarkknight197** [PrestaShop/PrestaShop#25352] opened 2021-07-14 14:52 UTC
Hi, i have downloaded prestashop with 

`git clone -b 1.7.7.5 https://github.com/PrestaShop/PrestaShop.git` .

after run `composer install` and go to my local site, after configuring all information about my store prestashop return an error at 23% of installation.

The error message is:

```
An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

1: HTTP 200 - parsererror -
Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/michele/Desktop/Lavori/Prestashop/hello-prestashop/src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/michele/Desktop/Lavori/Prestashop/hello-prestashop/src/Adapter/EntityMapper.php on line 99
{"success":false,"message":"file_get_contents_curl failed to download https:\/\/i18n.prestashop.com\/translations\/1.7.7.5\/it-IT\/it-IT.zip : (error code 28) Operation timed out after 5075 milliseconds with 0 out of 0 bytes received"}
```

What do to resolve it?

- PHP version: PHP 7.4.12 (cli) (built: Nov 30 2020 13:28:43) ( NTS )
- Copyright (c) The PHP Group
- Zend Engine v3.4.0, Copyright (c) Zend Technologies
- System: Mac OS X High Sierra 10.13.6

**Comment by hibatallahAouadni** [comment] 2021-07-14 15:19
Hello @thedarkknight197 

Well, when you execute this line:

`git clone -b 1.7.7.5 https://github.com/PrestaShop/PrestaShop.git`

You download the develop branch not the 1.7.7.5 (just for your information).
After execute this line:

`composer install`

You need to execute this line:

`make install`

Then, you can install your shop :wink: 

Please next time if you have a question ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

So, I'm closing this issue cause it's not related to the PS Core. But I can still answer all your questions about this issue (even it's closed).

PS: don't forget to respect and follow the provided template to submit a complete bug report (next time) :wink: 

Thank you

**Closed as completed by hibatallahAouadni** 2021-07-14 15:19 UTC
Labels: No change required

**Comment by matks** [comment] 2021-07-15 07:07
Hi @hibatallahAouadni I think the issue is rather this error line

```
{"success":false,"message":"file_get_contents_curl failed to download https:\/\/i18n.prestashop.com\/translations\/1.7.7.5\/it-IT\/it-IT.zip : (error code 28) Operation timed out after 5075 milliseconds with 0 out of 0 bytes received"}
```

@thedarkknight197 looks like you were not lucky, I check now and https://i18n.prestashop.com/translations/1.7.7.5/it-IT/it-IT.zip responds correctly. The i18n API was a little slow so the process timeouts. Please try again, API responses seem good now.
