### ISSUE TITLE
Multistore | Product quantity for all shops

### ISSUE THREAD

**Issue by ndldigitalsolutions** [PrestaShop/PrestaShop#11422] opened 2018-11-16 18:57 UTC
PrestaShop version: 1.7.5.0

To simulate the probem:

1. Enable multistore option 
2. Create two shops that share quantities in a group 
3. Create a product for All Shops 
4. Create combinations for this product  
5. Try to update quantities of all combination. 

Prestashop returns an error, changes only one combination at a time.
To change the quantities of all combinations, I have to click on save multiple times.

**Comment by ndldigitalsolutions** [comment] 2018-11-16 19:27
I solved the problem like this:

remove line 142 from /src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php 
and line 1029 from /classes/shop/Shop.php

I do not think it's the best way, but it's not a mistake anymore

**Comment by khouloudbelguith** [comment] 2018-11-19 07:46
Hi @ndldigitalsolutions 

We manage to reproduce the issue, it is fixed in the next release 1.7.5.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9145 to solve the issue.
So, I close it, please follow #9145 
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-19 07:46 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2018-11-19 07:48
Duplicate of #9145
