### ISSUE TITLE
"Invoices"-Link results in  HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#12737] opened 2019-02-27 12:57 UTC
Since upgrading to 1.7.5.0 - it is no longer possible to have the list of invoices, rest of prestashop is working fine, but, clicking on the link "invoices" (where it is possible to generate a pdf of all invoices from ie. last month) is just resulting in an "HTTP 500 Internal Server Error"
-> with debug on, it shows the following details:

Symfony\Component\Form\Exception\ 
UnexpectedTypeException 

![invoiceerror_](https://user-images.githubusercontent.com/31710761/53491772-7b9efb00-3a97-11e9-978a-3641c6d5d18e.jpg)
![invoiceerrorlog_](https://user-images.githubusercontent.com/31710761/53491792-86f22680-3a97-11e9-84f1-3a62ace1e25c.jpg)
![invoiceerror_stacktrace_](https://user-images.githubusercontent.com/31710761/53491804-8f4a6180-3a97-11e9-8877-349da394d668.jpg)

**Comment by khouloudbelguith** [comment] 2019-02-27 13:24
Hi @tom75,

Thanks to follow this comment: https://github.com/PrestaShop/PrestaShop/issues/12314#issuecomment-462410864 to fix your issue.
Your ticket is a duplicate of #12626, it is added to our bug roadmap.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-27 13:24
Duplicate of #12626

**Comment by Matt75** [comment] 2019-02-27 13:25
You can find a tutorial to fix this issue here : https://github.com/PrestaShop/PrestaShop/issues/12314#issuecomment-462410864

Moreover can you tell us how many languages are used in your shop and do you remember the PrestaShop version did you use on the beginning of your shop ?

**Closed as completed by khouloudbelguith** 2019-02-27 13:24 UTC

**Comment by decom-media** [comment] 2019-02-27 13:33
thanks for the link - will try that solution

Languages – I am having 7 languages: de, en, pl, pt, fr, es, nl

The first version…. I cannot tell for sure, as I did have quite many tests… is it possible to check it somewhere? And I am always asking myself if it would be possible to create a new installation with the latest prestashop version and import everything from my current installation – if that would be possible I would do that…

**Comment by decom-media** [comment] 2019-03-06 22:23
finally i had the time to check your suggestion with the solution #12314 - but, did not work for me - first quiery is not working because the subquery is returning more than just one result, so i tried the second one, which did return 0, but, then the insert did return also "not possible because the subquery did return more than just one result", so it seems there is still another problem in my installation

**Comment by Matt75** [comment] 2019-03-06 23:25
Can you give us the result of the subquery with multiple results ?
This one
```sql
SELECT `id_configuration` FROM `ps_configuration` WHERE `name` LIKE 'PS_INVOICE_LEGAL_FREE_TEXT'
```
And this one
```sql
SELECT `id_configuration` FROM `ps_configuration` WHERE `name` LIKE 'PS_INVOICE_FREE_TEXT'
```
You must have only one result for each key, if you find more of one result you have duplicate configuration key.

Don’t forget to do backup before INSERT/UPDATE/DELETE operations in ps_configuration

**Comment by decom-media** [comment] 2019-03-06 23:30
Result for the first one is
578
590

And for the second one is
591


So, the first one is then having duplication configuration key – what does it mean and how can I fix it?

Thanks
Thomas

**Comment by Matt75** [comment] 2019-03-06 23:42
You can compare value of each results

```sql
SELECT `name`, `value`, `id_shop`, `id_shop_group` FROM `ps_configuration` WHERE `id_configuration` IN (578, 590, 591)
```

If both are the same you can delete one of them.
If not same value, you have to choose witch one is more relevant and delete the other.
It can be interesting to know how that can happen, so if you can tell us the results it can be useful.

Don’t forget to do backup before INSERT/UPDATE/DELETE operations in ps_configuration

**Comment by decom-media** [comment] 2019-03-06 23:46
The result of this query is

[cid:image001.png@01D4D47F.2D0340B0]

Both are null – so, basically the same – what exactly is to do now?

**Comment by Matt75** [comment] 2019-03-06 23:46
Maybe you use multi shop ?
So it can be normal if id_shop are different

**Comment by decom-media** [comment] 2019-03-06 23:48
Yes I have multishop enabled

**Comment by Matt75** [comment] 2019-03-06 23:54
Can you give us the result of

```sql
SELECT `name`, `value`, `id_shop`, `id_shop_group` FROM `ps_configuration` WHERE `id_configuration` IN (578, 590)
```

And

```sql
SELECT `name`, `value`, `id_shop`, `id_shop_group` FROM `ps_configuration` WHERE `id_configuration` = 591
```

**Comment by decom-media** [comment] 2019-03-06 23:57
Of course.


1.       [cid:image001.png@01D4D480.A81F4130]

2.       [cid:image002.png@01D4D480.A81F4130]

**Comment by Matt75** [comment] 2019-03-06 23:58
We can’t see the image if you replied by mail so please export the result in text format and past it in your response.

**Comment by decom-media** [comment] 2019-03-07 00:04
1.
name<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

value<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

id_shop<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

id_shop_group<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

PS_INVOICE_LEGAL_FREE_TEXT

NULL

2

2

PS_INVOICE_LEGAL_FREE_TEXT

NULL

NULL

NULL





2.
name

value

id_shop

id_shop_group

PS_INVOICE_FREE_TEXT

NULL

NULL

NULL

**Comment by Matt75** [comment] 2019-03-07 00:08
Now the result of

```sql
SELECT `id_configuration`, `id_lang`, `value` FROM `ps_configuration_lang` WHERE `id_configuration` IN (578, 590, 591)
```

**Comment by decom-media** [comment] 2019-03-07 00:10
[Vollständige Texte]<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

id_configuration<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

id_lang<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

value<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>


<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

578

1

Sie haben das Recht, binnen vierzehn Tagen ohne An...


<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

578

3

Si no está satisfecho, tiene la posibilidad de dev...


<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

578

6

You have the right to revoke this contract within ...


<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

578

7

Mają Państwo prawo odstąpić od niniejszej umowy w ...


<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

578

8

U heeft het recht deze overeenkomst binnen veertie...


<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

578

9

You have the right to revoke this contract within ...


<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/tbl_change.php>

<https://w011f4e1.kasserver.com/mysqladmin/PMA4/sql.php>

578

10

You have the right to revoke this contract within ...

**Comment by Matt75** [comment] 2019-03-07 00:22
Sorry but this is not readable can you make a proper export of result of this query ?
You must have an option to export results so please use it to give us a readable information.

The problem is on your ps_configuration_lang where you must have one or more results for each `id_configuration` IN (578, 590, 591)

**Comment by Matt75** [comment] 2019-03-07 00:50
You have 7 languages so each of this queries must return 7 if all your shops use the same languages. (You use multi shop with 2 shops ?)

```sql
SELECT COUNT(*) FROM `ps_configuration_lang` WHERE `id_configuration` = 578
```

```sql
SELECT COUNT(*) FROM `ps_configuration_lang` WHERE `id_configuration` = 590
```

```sql
SELECT COUNT(*) FROM `ps_configuration_lang` WHERE `id_configuration` = 591
```

If not there is a problem

**Comment by decom-media** [comment] 2019-03-07 14:04
Hello Matt,

Yes, multishop and Multilanguage.

Here are the results of the queries:


SELECT `id_configuration`, `id_lang`, `value` FROM `ps_configuration_lang` WHERE `id_configuration` IN (578, 590, 591)

Tabellenstruktur für Tabelle ps_configuration_lang
Spalte

Typ

Null

Standard

Kommentare

id_configuration

int(10)

Nein





id_lang

int(10)

Nein





value

text

Ja

NULL



date_upd

datetime

Ja

NULL



Daten für Tabelle ps_configuration_lang
id_configuration

id_lang

value

578

1

Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. - Details dazu finden Sie unter folgender Adresse: http://www.altamoda.shop/de/content/2-rechtliche-hinweise

578

3

Si no está satisfecho, tiene la posibilidad de devolver la mercancía en un plazo de 14 días. Para más información, por favor visite: http://www.altamoda.shop/es/content/2-aviso-legal

578

6

You have the right to revoke this contract within fourteen days without giving any reasons. Details can be found at the following address: http://www.altamoda.shop/en/content/2-legal-notice

578

7

Mają Państwo prawo odstąpić od niniejszej umowy w ciągu czternastu dni bez podania przyczyny. Szczegółowe informacje można znaleźć pod następującym adresem: http://www.altamoda.shop/pl/content/2-rechtliche-hinweise

578

8

U heeft het recht deze overeenkomst binnen veertien dagen zonder opgaaf van redenen te herroepen. Details zijn te vinden op het volgende adres: http://www.altamoda.shop/nl/content/2-legal-notice

578

9

You have the right to revoke this contract within fourteen days without giving any reasons. Details can be found at the following address: http://www.altamoda.shop/en/content/2-legal-notice

578

10

You have the right to revoke this contract within fourteen days without giving any reasons. Details can be found at the following address: http://www.altamoda.shop/en/content/2-legal-notice




SELECT COUNT(*) FROM `ps_configuration_lang` WHERE `id_configuration` = 578

Tabellenstruktur für Tabelle ps_configuration_lang
Spalte

Typ

Null

Standard

Kommentare

id_configuration

int(10)

Nein





id_lang

int(10)

Nein





value

text

Ja

NULL



date_upd

datetime

Ja

NULL



Daten für Tabelle ps_configuration_lang
COUNT(*)

7



SELECT COUNT(*) FROM `ps_configuration_lang` WHERE `id_configuration` = 590

Tabellenstruktur für Tabelle ps_configuration_lang
Spalte

Typ

Null

Standard

Kommentare

id_configuration

int(10)

Nein





id_lang

int(10)

Nein





value

text

Ja

NULL



date_upd

datetime

Ja

NULL



Daten für Tabelle ps_configuration_lang
COUNT(*)

0




SELECT COUNT(*) FROM `ps_configuration_lang` WHERE `id_configuration` = 591

Tabellenstruktur für Tabelle ps_configuration_lang
Spalte

Typ

Null

Standard

Kommentare

id_configuration

int(10)

Nein





id_lang

int(10)

Nein





value

text

Ja

NULL



date_upd

datetime

Ja

NULL



Daten für Tabelle ps_configuration_lang
COUNT(*)

0

**Comment by Matt75** [comment] 2019-03-07 14:38
Ok, I made a little PrestaShop module last night who can help you to fix this problem.
You can download it here : https://github.com/Matt75/fixconfigurationlang/archive/1.0.0.zip
After download please rename the file `fixconfigurationlang-1.0.0.zip` to `fixconfigurationlang.zip`

After installation of the module, go to the configuration page of the module.
You will see this
![capture d ecran 2019-03-07 a 15 30 43](https://user-images.githubusercontent.com/5262628/53963703-16c64f00-40ee-11e9-990a-c93a168cff8e.png)
Here `PS_INVOICE_FREE_TEXT` has a problem

After click on Repare button, it will be fixed
![capture d ecran 2019-03-07 a 15 33 09](https://user-images.githubusercontent.com/5262628/53963839-5bea8100-40ee-11e9-80d8-fae3d1612603.png)
And now you can access to Invoices page

If you use multishop, maybe you have to do that on each you shop by switching between them
![capture d ecran 2019-03-07 a 15 35 52](https://user-images.githubusercontent.com/5262628/53964101-efbc4d00-40ee-11e9-8d10-6d4104feab69.png)

After using this module, you can uninstall and delete it.

**Comment by decom-media** [comment] 2019-03-08 13:24
Hi Matt,

Thanks for the module – would be really amazing work if this would fix my problem, but, cannot upload the module because of “wrong zip format of the module” – I even tried to unpack and repack it, but, same error.

Please let me know any suggestions.

Thanks
Thomas

**Comment by khouloudbelguith** [comment] 2019-03-08 13:38
Hi @tom75,

Thanks to check with this zip folder
[fixconfigurationlang.zip](https://github.com/PrestaShop/PrestaShop/files/2946000/fixconfigurationlang.zip)
I cloned it from GitHub & it is successfully installed.
Thanks!

**Comment by decom-media** [comment] 2019-03-08 13:47
Thanks- that module works, but, still the same error after repairing – I had the following which needed repair:

PS_INVOICE_LEGAL_FREE_TEXT
PS_INVOICE_FREE_TEXT

After clicking repair I did get the messages for each has been fixed, but, even after refreshing the module still shows that both are still on error and need to be fixed…

**Comment by Matt75** [comment] 2019-03-08 14:06
Humm interesting maybe due to multishop, I tested it by myself but I cannot reproduce the same corrupted database.
As you don't know how export correctly your data... (In sql format it will be more readable)

Did you try to fix on all your shops by switch between them as you can see on provided screenshot ?
Maybe I need to handle better multishop.

But now we know your problem come from `PS_INVOICE_LEGAL_FREE_TEXT` and `PS_INVOICE_FREE_TEXT`

It will be usefull if you can export the results of this queries in SQL format... Because you copy/paste is unreadable...

```sql
SELECT `id_configuration`, `id_shop_group`, `id_shop`, `name`, `value` FROM `ps_configuration` WHERE `name` IN ('PS_INVOICE_LEGAL_FREE_TEXT', 'PS_INVOICE_FREE_TEXT')
```
And
```sql
SELECT `id_configuration`, `id_lang`, `value` FROM `ps_configuration_lang` WHERE `id_configuration` IN (SELECT `id_configuration` FROM `ps_configuration` WHERE `name` IN ('PS_INVOICE_LEGAL_FREE_TEXT', 'PS_INVOICE_FREE_TEXT'))
```

![capture d ecran 2019-03-08 a 15 03 40](https://user-images.githubusercontent.com/5262628/54033101-b3065980-41b3-11e9-9117-38de6b3268b9.png)

![capture d ecran 2019-03-08 a 15 04 11](https://user-images.githubusercontent.com/5262628/54033042-8f431380-41b3-11e9-8373-e4b97f63858a.png)

**Comment by decom-media** [comment] 2019-03-08 14:24
Well, no problem to export as sql, just did not know that you want me to export as sql, also not sure now if the attached sql files will be available for you when I reply and include them by email, just let me know if I need to upload on git directly.

I did exactly as you mentioned, one shop, switching to the other one and same again

**Comment by Matt75** [comment] 2019-03-08 14:35
You have to it to us by Github because by email we don't receive attachment, screenshots etc
Thanks

**Comment by Matt75** [comment] 2019-03-08 15:36
I made a little update of the module to be sure missing lines will be added in ps_configuration_lang
[fixconfigurationlang.zip](https://github.com/PrestaShop/PrestaShop/files/2946402/fixconfigurationlang.zip)

**Comment by decom-media** [comment] 2019-03-09 12:22
The error is still the same – but, at least there is now just one problem left, the second seems to be fixed:

PS_INVOICE_LEGAL_FREE_TEXT – is still marked as having problem in your module, but, PS_INVOICE_FREE_TEXT is now fixed (as your module is telling me)

Should I upload now the sql files from before using your last module update or the current export – will upload them then on github

**Comment by Matt75** [comment] 2019-03-09 14:15
Yes please upload on Github the export results of theses queries 👍 


```sql
SELECT `id_configuration`, `id_shop_group`, `id_shop`, `name`, `value` FROM `ps_configuration` WHERE `name` IN ('PS_INVOICE_LEGAL_FREE_TEXT', 'PS_INVOICE_FREE_TEXT')
```

And

```sql
SELECT `id_configuration`, `id_lang`, `value` FROM `ps_configuration_lang` WHERE `id_configuration` IN (SELECT `id_configuration` FROM `ps_configuration` WHERE `name` IN ('PS_INVOICE_LEGAL_FREE_TEXT', 'PS_INVOICE_FREE_TEXT'))
```

It can be very useful to better understanding 👍

**Comment by decom-media** [comment] 2019-03-09 14:23
here are the results

[sqlexport.zip](https://github.com/PrestaShop/PrestaShop/files/2948463/sqlexport.zip)

**Comment by Matt75** [comment] 2019-03-09 14:32
Ok you can execute this query to fix it

```sql
DELETE FROM `ps_configuration` WHERE `id_configuration` IN (590, 591)
```

As the value is NULL and no lines are associated in ps_configuration_lang.

**Comment by decom-media** [comment] 2019-03-09 15:36
Fantastic, seems that the problem is solved, the link is working again, can create again an invoice pdf – looks fine ..

but, as I was checking now also the other links, I realized that there is another problem with the credit slips as well (did not have to use them since I updated), just clicking on the link results in following error message:

Bad SQL query
Column 'id_order' in where clause is ambiguous

Should I create another bug report for that?

Thanks again for fixing the problem so fast!

**Comment by Matt75** [comment] 2019-03-09 15:39
As the new problem seems different, you can create another issue. Please provide the details of the error with logs etc in order to help us to reproduce

**Comment by decom-media** [comment] 2019-03-09 16:26
Ok, thanks again!
