### ISSUE TITLE
ps_rssfeed image bug

### ISSUE THREAD

**Issue by maserman** [PrestaShop/PrestaShop#12994] opened 2019-03-21 14:42 UTC
On Prestashop 1.7.5 the ps_rssfeed module no longer displays images from feeds, making it pretty pointless.

The blockrss module from Prestashop1.6 that this replaces used to display images from feeds by default, is there going to be a fix for this anytime soon?

**Comment by khouloudbelguith** [comment] 2019-03-21 15:06
Hi @maserman,

What is the exact link did you used in the module?
I tried with `ps_rssfeed` module in PS1.7.5.1, I used this link http://news.google.com/?output=rss => in FO
![image](https://user-images.githubusercontent.com/16067358/54761740-f2409b80-4bf2-11e9-9a78-27e8634faecd.png)
I tried with `blockrss` module in PS1.6.1.23, I used the same link => in FO, I have 
![image](https://user-images.githubusercontent.com/16067358/54761856-36cc3700-4bf3-11e9-9246-d9b8708a4a65.png)
Thanks to check & feedback.

**Comment by maserman** [comment] 2019-03-21 15:20
Hi Khouloud
Thanks for the reply. I tried the rss feed link you gave - it shows the topics, but no images.
The 1.6.1.23 blockrss module v1.3.2 displays an image with the feed - it doesn't in the new 1.7 ps_rssfeed module :(
in blockrss.php:
`
			$rss_links = array();
			if ($url && ($contents = Tools::file_get_contents($url)))
				try
				{
					if (@$src = new XML_Feed_Parser($contents))
						for ($i = 0; $i < ($nb ? $nb : 5); $i++)
							if (@$item = $src->getEntryByOffset($i))
							{
								$xmlValues = array();
								foreach (self::$xmlFields as $xmlField)
									$xmlValues[$xmlField] = $item->__get($xmlField);
								$xmlValues['enclosure'] = $item->getEnclosure();

								// First image
								if (isset($xmlValues['content']) && $xmlValues['content'])
								{
									preg_match('/< *img[^>]*src *= *["\']?([^"\']*)/', $xmlValues['content'], $image);
									if (array_key_exists(1, $image) && $image[1])
									{
										if ($image[1][0] == '/')
											$image[1] = 'http:'.$image[1];
										// Try if distant image exist : timeout 0.3s
										$context = stream_context_create(array('http' => array('timeout' => 0.6)));
										if (file_get_contents($image[1], false, $context, -1, 1) !== false)
											$xmlValues['image'] = $image[1];
									}
								}

								// Compatibility
								$xmlValues['url'] = $xmlValues['link'];
								$rss_links[] = $xmlValues;
							}
				}
`

in blockrss.tpl:
`
<br />
<div id="rss_block_home" class="block">
	<h3 style="font-size:24px; text-transform:uppercase;" align="center"><a href="https://thermapenblog.com" target="_blank">Latest Posts from our Thermapen Blog</a></h3>
<br />
	<div class="block_content">
		{if $rss_links}
			<ul class="htmlcontent-home clearfix row">
				{foreach from=$rss_links item='rss_link'}
					<li class="htmlcontent-item-2 col-xs-12 col-sm-6 col-md-4"><a href="{$rss_link.url}" target="_blank"><img class="img-fluid" src="{$rss_link.image}"><br /><br /><span style="font-size:18px;">{$rss_link.title}</a></span><br />{$rss_link.description|truncate:142}<br /><br /></li>
				{/foreach}
			</ul>
		{else}
			<p>{l s='No RSS feed added' mod='blockrss'}</p>
		{/if}
	</div>
</div>
`

**Comment by maserman** [comment] 2019-03-21 15:23
To see the current live version of blockrss with images go here:
https://thermapen.co.uk

there appear under heading 'Latest posts from our Thermapen blog'

Best regards
Barry

**Comment by khouloudbelguith** [comment] 2019-03-21 15:27
@maserman, what is the exact link did you used in the module?
![image](https://user-images.githubusercontent.com/16067358/54763268-f9b57400-4bf5-11e9-9d00-4f58c6e76cc8.png)
Thanks!

**Comment by maserman** [comment] 2019-03-22 07:50
Hi Khouloud

Thanks for your responses - hope it will get fixed soon. There is one further issue. I just tried updating to use PHP 7.1.27 ( PHP 7.033 now outdated) on current version of Prestashop 1.6 - that 'loses' the images from blockrss too so had to revert to the older version of PHP to get the images displaying again :(

**Comment by Matt75** [comment] 2019-03-24 19:43
It's not a bug, this feature is no longer available on module for 1.7 because of the removal of the [Pear XML_Parser](https://pear.php.net/package/XML_Parser/) dependency witch is deprecated. The module now use [SimpleXMLElement](https://php.net/manual/fr/class.simplexmlelement.php) in replacement but this solution is really too simple to parse RSS Feed correctly. That's why this module use only `title` and `link`.

**Comment by khouloudbelguith** [comment] 2019-03-25 10:25
Hi @Matt75,

Thanks for your feedback.
@maserman, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-03-25 10:25 UTC
Labels: FO, Modules, No change required, 1.7.5.1

**Comment by maserman** [comment] 2019-03-26 15:08
Hi

I've managed to parse with a 'straight' php file using SimpleXML as below...

How can I use adapt this to use with Smarty Template??

`<?php
$html = "";
$url = "http://news.google.com/?output=rss";
$xml = simplexml_load_file($url);
for($i = 0; $i < 3; $i++){

    $image = $xml->channel->item[$i]->children('media', True)->content->attributes();
    $title = $xml->channel->item[$i]->title;
    $link = $xml->channel->item[$i]->link;
    $description = $xml->channel->item[$i]->description;
    $pubDate = $xml->channel->item[$i]->pubDate;

    $html .= "<img src='$image' alt='$title'>";
    $html .= "<a href='$link'><h3>$title</h3></a>";
    $html .= "$description";
    $html .= "<br />$pubDate<hr />";
}
echo $html;
?>`
