### ISSUE TITLE
Bug with physical_uri in module mail template

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#25453] opened 2021-07-28 15:02 UTC
#### Describe the bug
The shop physical_uri is matched against file path for email template in module here :
https://github.com/PrestaShop/PrestaShop/blob/69787a8dbe4231be553310c5629f8ead22a149e2/classes/Mail.php#L411

The physical uri can be different (apache allas, symlink, ...) : in this case module can't have email template loaded at all.

#### Expected behavior

Load email template in module.

#### Steps to reproduce

1. Create an apache alias (ex: monalias) 
2. Make sure the created alias is pointed on PrestaShop_folder/
3. Try to send an email (use the Mailalert module)
4. See error > impossible to send an email

#### Additional information

* PrestaShop version: All 1.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-07-29 14:55
Hello @jf-viguier 

I just edit your issue by adding the steps to reproduce as discussed on Slack.
Could you please confirm these steps :pray: 

Thanks in advance.

**Comment by hibatallahAouadni** [comment] 2021-08-18 12:52
Hello @jf-viguier 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-18 12:52 UTC
Labels: Bug, 1.7.x, CO, Modules, Email, SEO & URLs, No change required
