### ISSUE TITLE
issue when double click on add to cart 

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#18448] opened 2020-04-03 00:15 UTC
when the user double click on the add to cart button, it opens the modal summary, if you click on continue buying, the grey background remains and you can not navigate on the page.

![fondo](https://user-images.githubusercontent.com/46203943/78311305-d6bae100-7526-11ea-9e31-5bb562fa5a62.png)

* PrestaShop version: 1.7.6.4 Classic theme

**Comment by khouloudbelguith** [comment] 2020-04-03 07:13
Hi @msaustral, 

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9634
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-03 07:13
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9634

**Closed as completed by khouloudbelguith** 2020-04-03 07:13 UTC
Labels: Duplicate
