### ISSUE TITLE
Uncaught SyntaxError: Identifier 'moduleCardController' has already been declared - module_card.js?1.7.8.3

### ISSUE THREAD

**Issue by klaurenson** [PrestaShop/PrestaShop#27728] opened 2022-02-18 13:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

BO Product page is stuck because of duplicate entry of moduleCardController in admin theme (default & new-theme)
- You're will then be unable to perform few modifications like editing removing combination 
- I also work with this Module "Dynamic product" which allows us to add lots of fields & options
this JS error just prevent adding any options and other settings. 

### Steps to reproduce

1. Open BO and browser console
2. Go to Catalog
3. Open any product

You'll see the red flag duplicate entry of moduleCardController

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

dynamicproduct

**Comment by HanaRebaiQA** [comment] 2022-02-18 14:37
Hello @klaurenson 

Thanks for your report!
It's duplicate of https://github.com/PrestaShopCorp/ps_mbo/issues/109 

So, i'll close the issue

**Comment by HanaRebaiQA** [comment] 2022-02-18 14:38
Duplicate of [#109](https://github.com/PrestaShopCorp/ps_mbo/issues/109 )

**Closed as completed by HanaRebaiQA** 2022-02-18 14:37 UTC
Labels: Bug, Duplicate
