### ISSUE TITLE
Crash when using voucher with gift deleted

### ISSUE THREAD

**Issue by prestaforum** [PrestaShop/PrestaShop#20510] opened 2020-08-09 12:39 UTC
#### Describe the bug

I create a voucher, it gives product "petite pochette" as gift to customer who uses it. Then I delete from back office the "petite pochette". When customer uses the voucher the prestashop crashes.

#### Expected behavior

The prestashop should tell user the voucher is not valid.

#### Steps to Reproduce

1. Go to back office
2. Create voucher, dont fill in code
3. Configure voucher to add to cart a gift (= free product)
4. Delete the product that is used as gift
5. Create a cart as normal customer.
6. Add a product to cart: no result. No feedback. If you look in console you see ajax request returned as fatal error.
7. If you refresh the page, the product is in the cart.

#### Additional information

* PrestaShop version: 1.7.6.6
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-08-10 09:25
Hi @prestaforum,


Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1gY9jwIBAAfGsnqeCtPOZlndURW9Vmu1G/view?usp=sharing

Thanks to check and feedback.

**Comment by Hlavtox** [comment] 2020-08-11 09:24
@prestaforum @khouloudbelguith https://github.com/PrestaShop/PrestaShop/issues/15224

**Comment by khouloudbelguith** [comment] 2020-08-11 11:11
@Hlavtox, thanks!
@prestaforum, we aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15224
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-11 11:11
Duplicate of #15224

**Closed as completed by khouloudbelguith** 2020-08-11 11:11 UTC
Labels: Bug, Duplicate, Discounts
