### ISSUE TITLE
the tax did not appear at the time of the settlement.

### ISSUE THREAD

**Issue by startech-france** [PrestaShop/PrestaShop#11223] opened 2018-11-01 15:39 UTC
1- I am a professional supplier all my prices are to display free taxes on the site, my at the time of the payment the tax must be added, whereas in my case to me, it is displayed my does not add to the amount total. see the example below + screenshot attached.

Example:
the customer has to pay 272,03 €. the customer must pay the subtotal + delivery charges + taxes, while my site displays the tax but does not ask to pay it.

should display this.

Sub-total € 204.19
Shipping 27,00 €
Total (tax included) € 231.19
Taxes 40,84 €

Total (tax incl.) 272,03 € <------ missing box.
(see the capture situation in attachment "Capture payment").

**Screenshots**
![capture paiement](https://user-images.githubusercontent.com/43042604/47862123-b13b1c80-ddf4-11e8-932a-8f34c3e0b129.PNG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment] 2018-11-01 16:04
Hi @startech-france,

Your issue should be solved in this ticket: #9999
We have also a list of similar issues added to our bug roadmap: https://github.com/PrestaShop/PrestaShop/issues/9703
Your ticket is a duplicate of #9999
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-01 16:04
Duplicate of #9999

**Closed as completed by khouloudbelguith** 2018-11-01 16:04 UTC
Labels: Duplicate
