### ISSUE TITLE
HOOK_DISPLAY_PDF content cannot start from left side of the document

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#24956] opened 2021-06-14 12:14 UTC
#### Describe the bug

When implementing `displayPDFInvoice` and adding content to the invoice pdf document footer from a module the content always starts few cm from the left side of the page.

The reason is the colspan="2" here: https://github.com/PrestaShop/PrestaShop/blob/415667ce988738b91771bb6ec56e41369c3c0750/pdf/invoice.tpl#L135

#### Expected behavior

Let the extra content take up the full width of the page by removing the extra <td colspan="2">

#### Steps to Reproduce

1. Implement module with `displayPDFInvoice` and render some content into invoice footer with ti
2. Go to order and click 'View invoice'
3. Check the content. It does not start from the left side and cannot be made to start from there

![image](https://user-images.githubusercontent.com/1352132/121890371-ef29ac80-cd22-11eb-8629-e1141562cf62.png)

#### Additional information

* PrestaShop version: 1.7.7.2 (the extra colspan can still be seen in develop code also, see link above)
* PHP version: N/A

**Comment by florine2623** [comment] 2021-06-15 10:32
Hello,

I was able to reproduce the issue with PrestaShop version _1.7.7.x_, _1.7.8.x_ and _develop_, so I can confirm that this behavior is indeed a bug.
<img width="749" alt="Screenshot 2021-06-15 at 12 31 27" src="https://user-images.githubusercontent.com/16019289/122038280-b8f93500-cdd5-11eb-9d9b-5a6fb91a65dc.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by tswfi** [comment] 2021-06-15 10:44
@florine2623 did you notice that I already provided a pr also: https://github.com/PrestaShop/PrestaShop/pull/24958

**Comment by hibatallahAouadni** [comment] 2021-06-15 16:52
@tswfi sorry but it's an automatic message :smile:

**Comment by matks** [comment] 2021-06-17 16:18
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24958

**Closed as completed** 2021-06-17 16:18 UTC
Labels: Bug, Trivial, CO, Invoices, Fixed, Developer Feature, PR available, 1.7.7.2
