### ISSUE TITLE
PS 8.1.3 - Enable product image in Delivery slip/Invoices doesn't work anymore

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34835] opened 2023-12-14 13:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PS 8.1.3 build 1, enabling the product image option does not work in Delivery Slips and Invoices.

<img width="344" alt="Screenshot 2023-12-14 at 14 21 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/30860fd2-c1e0-42b7-aad8-a5f6d5df6c3b">

### Expected behavior

I should be able to see the product image in my delivery slip and invoice.

<img width="763" alt="Screenshot 2023-12-14 at 14 23 16" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9889b844-30ad-4537-b587-40777bbd65d5">
<img width="980" alt="Screenshot 2023-12-14 at 14 23 12" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3f45b9ec-c2fe-4c38-97c3-66d8f16d661a">

### Steps to reproduce

1. Go to BO > Invoices > Enable product image 
2. Go to BO > Orders > Change status of any order to Payment accepted
3. Click on the Invoice icon
4. See no product image displayed :x:
5. Go to BO > Delivery slips > Enable product image 
6. Go to BO > Orders > Change status of any order to Delivered
7. Click on the Delivery slip icon
8. See no product image displayed :x:

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment] 2023-12-19 17:07
Hello @florine2623 ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

FYI : @tleon @MatShir

**Closed as not planned** 2023-12-20 07:36 UTC
Labels: Bug, Minor, BO, Can't reproduce, Invoices, Delivery slip, Invalid, 8.1.x
