### ISSUE TITLE
Table product_carrier not cleaned

### ISSUE THREAD

**Issue by MarceldeR** [PrestaShop/PrestaShop#29205] opened 2022-07-29 16:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After deleting products the table product_carrier is not cleaned. The deleted product_id's are not removed.

### Expected behavior

That after deleting a product in the backoffice, the product_id is removed from the table product_carrier

### Steps to reproduce

1. Delete a product and remember the product_id
2. Check the table product_carrier with for example phpmyadmin.
3. Search and find the product_id. It is still there which it shouldnt.

### PrestaShop version(s) where the bug happened

1.7.8.7 and probably earlier versions

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment] 2022-08-01 16:54
Hello @MarceldeR 

I reproduce the issue with PS1767, PS1778 and PS1787, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/182202275-87bee870-ab66-4356-bb85-42ab91807e61.mp4

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2023-07-29 15:00 UTC
Labels: Bug, Minor, CO, Needs Specs, Performance, Fixed, PR available, 1.7.6.7, Verified
