### ISSUE TITLE
FO - Discounts - The discount detail is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24635] opened 2021-05-24 16:33 UTC
#### Describe the bug

In the FO > Shopping cart page and checkout page, when we apply two cart rule "Free shipping" + percent discount, the discount line s NOK, the discount = total product + shipping

#### Steps to Reproduce

1. Go to BO > Catalog >  Cart rules page
2. Create a cart rule Free shipping
3. Create another cart rule 10%
3. Go to FO, add a product to the cart
4. In the shipping method, you need to select **not a free shipping**
5. Apply discounts
![image](https://user-images.githubusercontent.com/16067358/119377834-d9920b80-bcbd-11eb-8e4f-3d5f39e391fa.png)

In the BO > Orders > Order details => ok
![image](https://user-images.githubusercontent.com/16067358/119378010-08a87d00-bcbe-11eb-8c12-0f44a7ae0c08.png)

With PS1769, we have this:
![image](https://user-images.githubusercontent.com/16067358/119378385-853b5b80-bcbe-11eb-87a2-979f4f093166.png)

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2, 7.4

**Comment by Progi1984** [comment] 2021-05-27 14:12
@PrestaShop/product-team I have a problem with this PR... 

Since this bugfix #18810 (ping @matthieu-rolland), cumulative reduction exists.

But like free shipping is not really free shipping, but a reduction of shipping : it enters in the field of cumulative reduction. Isn't it ?

**Comment by marionf** [comment] 2021-05-28 07:39
@Progi1984 

> But like free shipping is not really free shipping, but a reduction of shipping : it enters in the field of cumulative reduction. Isn't it ?

Yes, here the total of reductions (Discounts line) is correct => Free shipping (8,40€) + 10% (10€) = 18,40€ :heavy_check_mark: 

The problem is the 10% discount line, it should display 10€ here and not 9.16€ :negative_squared_cross_mark:

**Comment by Progi1984** [comment] 2021-05-28 07:46
@marionf So the free shipping doesn't enter in the field of cumulative reduction. Thanks.

**Comment by arouiadib** [comment] 2021-06-08 15:06
@Progi1984 , I believe Free Shipping is cumulative.

Let's please see this config:
- Product 1 with only one possible carrier 1 (specific carrier 1).
- Product 2 with only one possible carrier 2.
- Cart rule 1 with only  Free Shipping action restricted to carrier 1.
- Cart rule 2 with only  Free Shipping action restricted to product 2.
- Cart with product 1 and product 2.
Then Shipping discount = cost of carrier 1 + cost of carrier 2.

Could you please give some of you invaluable time reading my trial in specs, it contains some other scenarios not yet validated by other PrestaShop people.
https://github.com/PrestaShop/prestashop-specs/issues/107

Thanks a ton

**Comment by Progi1984** [comment] 2021-06-25 11:40
Fixed by @Progi1984 in #24754

**Closed as completed by Progi1984** 2021-06-25 11:40 UTC
Labels: Bug, Minor, FO, Discounts, Cart rules, Regression, Fixed, Shopping carts FO, Checkout, 1.7.7.x, 1.7.8.x
