### ISSUE TITLE
BO: product form V2 : Show inactive category in the category tree

### ISSUE THREAD

**Issue by e-gaulue** [PrestaShop/PrestaShop#25071] opened 2021-06-21 21:37 UTC
#### Describe the bug

In product Form V2 you can only associate categories to active categories. It was not the case before and it's really needful to be able to associate product to inactive categories.

#### Expected behavior

See inactive categories in the category tree and be able to interact with them.

#### Steps to Reproduce

1. Go to product form and associate the product with a category
2. Disable the category
3. Go back to the same product form V2
4. See strange rendering

#### Additional information

* PrestaShop version: 1.7.8.0-beta.1
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-06-22 08:32
Hello @e-gaulue 

I was able to reproduce the issue with PrestaShop version 1.7.8.0, so I can confirm that this behavior is indeed a bug.
Normal Product Page :
![Screenshot 2021-06-22 at 10 30 09](https://user-images.githubusercontent.com/16019289/122891779-1268e300-d345-11eb-86a9-ffe070c12673.png)

Experimental page :
![Screenshot 2021-06-22 at 10 30 33](https://user-images.githubusercontent.com/16019289/122891812-1b59b480-d345-11eb-8849-ae4fcb498b01.png)


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-06-24 00:01
Ping @marionf this bug occurs only with the new product page, so is it a regression or not?

**Comment by marionf** [comment] 2021-06-24 07:55
@hibatallahAouadni let's ask to @MatShir

**Closed as completed** 2021-06-28 07:29 UTC
Labels: Bug, develop, Minor, BO, Categories, Fixed, PR available, 1.7.8.x
