### ISSUE TITLE
Rounding problem with the product prices

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#18183] opened 2020-03-17 16:05 UTC
Hi,

I have a rounding issue with product prices. I have changed the rules in the back office but whatever rule I set, there is always an error.
For example: the price of a product is 149 € and when the customer ordered 2, it should be 298 (149+149), but it shows 297.99 with the rule (**Round up to infinity when halfway value (recommended)**). When we change the rule to **Rounding up to the nearest higher value** in BO, the price of the product is correct, but for certain products it shows 1 cent more.

Anyone has a solution ?

Thanks!

**Screenshots**

_With rule **Rounding up to the nearest higher value** :_

![3](https://user-images.githubusercontent.com/51961329/76875326-b75a5d80-6870-11ea-808e-1f296ccfd948.PNG)

![2](https://user-images.githubusercontent.com/51961329/76875606-10c28c80-6871-11ea-9ff8-d7150661d003.PNG)

![4](https://user-images.githubusercontent.com/51961329/76875654-246df300-6871-11ea-9d65-fdf4b775f6d0.PNG)

_With rule **Round up to infinity when halfway value (recommended)** :_

![5](https://user-images.githubusercontent.com/51961329/76875713-3780c300-6871-11ea-9f5f-5511742f3f8f.PNG)

![1](https://user-images.githubusercontent.com/51961329/76875375-c2ad8900-6870-11ea-94da-bcf00b6c21bf.PNG)

![6](https://user-images.githubusercontent.com/51961329/76875722-3b144a00-6871-11ea-8292-82f190d6c7c1.PNG)

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2020-03-17 16:13
Hi @Gaja-A,

We have a different rounding problem, it is an issue that should be specified & fixed by our developers.
We are aware of this issue.
Your ticket is a duplicate of #9779
Please follow: https://github.com/PrestaShop/PrestaShop/issues/9779 https://github.com/PrestaShop/PrestaShop/issues/9779#issuecomment-415125166
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-17 16:13
Duplicate of #9779

**Closed as completed by khouloudbelguith** 2020-03-17 16:13 UTC
Labels: Duplicate
