### ISSUE TITLE
Orderpage not available for admin

### ISSUE THREAD

**Issue by t0mmywalker** [PrestaShop/PrestaShop#14905] opened 2019-07-29 19:57 UTC
When I try to see my orders I land on a page which says:

"Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

**Comment by khouloudbelguith** [comment] 2019-07-30 10:51
Hi @t0mmywalker,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-29 07:18
Hi @t0mmywalker,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-29 07:18 UTC
Labels: Bug, BO, Order, No change required
