### ISSUE TITLE
'View My Shop' button is not working when ssl is active

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#12380] opened 2019-01-31 05:23 UTC
**Describe the bug**
'View My Shop' is not creating automatic https handling URL.
See this code:
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/classes/controller/AdminController.php#L1945

I have already raised issue here:
http://forge.prestashop.com/browse/BOOM-4348?filter=-2

Let me know if this is not duplicate of any PR. I can create a PR for this issue.
Thanks,

**To Reproduce**
- First https must be active for your site
- But this should not be an automatic redirect from http->https
1. Go to 'Backoffice'
2. Click on 'View My Shop' in top-right in BO
3. See error in FO

**Screenshots**
![download](https://user-images.githubusercontent.com/19220745/52032325-786f2880-2546-11e9-90ab-0780736242b3.png)
![download 48](https://user-images.githubusercontent.com/19220745/52032335-7c9b4600-2546-11e9-81ea-4df52a8eb4d1.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7

**Comment by khouloudbelguith** [comment] 2019-01-31 07:56
Hi @dheerajwebkul,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12253
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-31 07:57
Duplicate of #12253

**Closed as completed by khouloudbelguith** 2019-01-31 07:56 UTC
Labels: Duplicate

**Comment by dheerajwebkul** [comment] 2019-01-31 08:08
@khouloudbelguith Ok 
But I am not getting any warning regarding https in backoffice as in the issue #12253

**Comment by khouloudbelguith** [comment] 2019-01-31 08:30
@dheerajwebkul, yes, some warnings are disabled in some browser.
You can follow this [link](https://www.technipages.com/chrome-enabledisable-not-secure-warning) to enable “Not Secure” Warning.
After enabling this option, you can get warnings in the console
![image](https://user-images.githubusercontent.com/16067358/52041448-c4b46b80-253a-11e9-9c2d-f05a662d4a82.png)
Thanks!
