### ISSUE TITLE
Wrong cart rule amount in FO when "Exclude discounted products" is enabled

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/PrestaShop#19090] opened 2020-05-12 10:05 UTC
#### Describe the bug

When applying a cart rule with "exclude discounted products" enabled, the amount of the cart rule line isn't ok
It takes into account all products instead of only not discounted products
But the total and the discount line are OK

#### Steps to Reproduce

1. I created a cart rule of 10% and enabled "exclude discounted products"
2. I added two products in my cart: Hummingbird printed sweater, Size S (discounted) and Mug The best is yet to come (not discounted)
3. See the discount line is OK, the total is OK but the cart rule line isn't OK

![capture d'écran_2866](https://user-images.githubusercontent.com/13449658/99974498-4f65fa80-2da1-11eb-8d71-e50e092bed85.png)

#### Expected behavior

If you activate the rule "Exclude discounted products" I expect that discount will not be applied to products that are discounted, but **only to products without discount**.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-05-12 15:25
Hi @kenlog ,
Thanks for reporting this issue.
I managed to reproduce the issue on both PS 1.7.6.5 and PS 1.7.7.
I'll let our dev team know about it.
Please stay tuned, thanks !

**Comment by arouiadib** [comment] 2020-05-26 03:49
Hello guys,

In 1.7.7.x, the calculation is correct.
![image](https://user-images.githubusercontent.com/23559010/82858491-f14c7d80-9f0b-11ea-9e86-1a05e608cf82.png)

Thanks

**Comment by sarahdib** [comment] 2020-05-26 08:59
@kenlog Thank you for the report I manage to reproduce the issue 
You can see in my screenshot the value of the cart rule is not the same that the one in the cart. The total is correct only the display is not correct

<img width="1141" alt="Capture d’écran 2020-05-26 à 10 50 45" src="https://user-images.githubusercontent.com/3034677/82881252-bfeda500-9f3f-11ea-8e24-bd276fe81790.png">

**Comment by arouiadib** [comment] 2020-05-26 17:27
@sarahdib , thank you for your time. 
About the second part (your second red rectangle), the problem should theoretically be fixed today after the merge of #17502 (Although it is not the problem originally mentioned by @kenlog; as you can see from his original picture when still voucher were displayed as percent). I will test with current 1.7.7.x state and feedback.

I think @kenlog is talking about the first part (your first red rectangle). Then, there is no problem as you see :)  in your picture:

3.48 is 10% of 34.80, then the product which already discounted  (Pull imprime colibri) is not included in the overall discount calculcation.

I am of course talking about 1.7.7.x, so IMHO it is just a question of upgrading. 
Thanks.

**Comment by sarahdib** [comment] 2020-06-01 07:25
@arouiadib Thank you for those detail :)

@kenlog can you confirm ?

**Comment by kenlog** [comment] 2020-06-01 11:26
Hi @sarahdib I confirm the bug as I have exposed it. In addition, this is also reflected in the PayPal payment method which correctly charges the right price excluding the already discounted products. This obviously involves a difference in the total cart and the order total. :astonished:

![carrello](https://user-images.githubusercontent.com/11728231/83404468-ff6a3480-a40a-11ea-8d34-a67d12b8b21f.png)
![Ordine](https://user-images.githubusercontent.com/11728231/83404475-0133f800-a40b-11ea-958b-7a86bfb71fa6.png)


P.S. Other payment methods such as Stripe charges based on the total cart.

**Comment by ComonSoft** [comment] 2020-06-18 15:28
Hi,
This is a big issue, because invoices are false, and customer can complain. Is any fix available ?
To reproduce, add rule 10% all cart exclude products in promotion. The reduction is applied on all products. See screen shot enclosed.
PS 1.7.6.5 PHP 7.2
![screenshot](https://user-images.githubusercontent.com/13507563/85040458-1dfd5900-b189-11ea-975c-927ad771aad3.jpg)

Regards

**Comment by Damian-Rutkowski** [comment] 2020-06-30 10:39
Good afternoon,

is there an official patch that can also be imported for older versions (e.g. v1.7.6.5)? We have some customers and unfortunately we cannot update all of them.

**Comment by khouloudbelguith** [comment] 2020-08-25 11:36
Hi!

As commented [here](https://github.com/PrestaShop/PrestaShop/issues/19090#issuecomment-633900555), I have the same issue with PS1.7.7.0beta2build1
![image](https://user-images.githubusercontent.com/16067358/91169626-f7ebbc00-e6d7-11ea-84c8-e1199b477992.png)
![image](https://user-images.githubusercontent.com/16067358/91169656-01752400-e6d8-11ea-8e3e-5fd4e125adfb.png)

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-23 14:08
Hello,

This issue has been partially fixed with PS1.7.7.0-rc.1. I open a new issue for the minor problem that still persist #22057
So, I close this issue.

Thanks!

**Comment by marionf** [comment] 2020-11-23 14:22
@hibatallahAouadni 

Just tested on 1.7.7.x branch and this issue doesn't seems fixed

1. I created a cart rule of 10% and excluded discounted products
2. I added to products in my cart: Hummingbird printed sweater, Size S (discounted) and Mug The best is yet to come (not discounted)

![capture d'écran_2865](https://user-images.githubusercontent.com/13449658/99973140-bbdffa00-2d9f-11eb-848a-2b275881352b.png)

**Comment by hibatallahAouadni** [comment] 2020-11-23 14:27
Hello @marionf 

Could you please check the screen record attached below:

https://drive.google.com/file/d/1wzBKm-ltqVdo35Cihv34lgFMQSxHR8ha/view

Please check and feedback.
Thanks!

**Comment by marionf** [comment] 2020-11-23 14:32
That's another issue, you added a condition in the cart rule and selected a category: #22057
Here, there is still the issue described by @khouloudbelguith in [this comment](https://github.com/PrestaShop/PrestaShop/issues/19090#issuecomment-679971538) with a cart rule with "exclude discounted products" enabled and no conditions

**Comment by GIORGIOMARIO** [comment] 2020-12-02 09:58
Discount voucher problem: The discount code applies to all products, even to discounted items with the version 1.7.6.5.

When I apply the discount code on 1 item, the code does "exclude discounted products".
But when I apply it on more than 1 item (1 normal and 1 disounted product per example), the code apply reduction on all products.

![Problème code promo](https://user-images.githubusercontent.com/75362627/100857680-4950d780-348d-11eb-974a-33bed2fe5bf2.jpg)

**Comment by josearandac** [comment] 2021-05-13 09:09
Hello,

This solution work for me.

1) File /src/Core/Cart/CartRuleCalculator.php find the code block:

```        // Discount (%) on the selection of products
        if ($cartRule->reduction_percent && $cartRule->reduction_product == -2) {
            $selected_products = $cartRule->checkProductRestrictionsFromCart($cart, true);
            if (is_array($selected_products)) {
                foreach ($this->cartRows as $cartRow) {
                    $product = $cartRow->getRowData();
                    if (in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                        || in_array($product['id_product'] . '-0', $selected_products)
                           && (($cartRule->reduction_exclude_special && !$product['reduction_applies'])
                               || !$cartRule->reduction_exclude_special)) {
                        $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
                        $cartRuleData->addDiscountApplied($amount);
                    }
                }
            }
        }
```
2) We add a parenthesis:

```
        // Discount (%) on the selection of products
        if ($cartRule->reduction_percent && $cartRule->reduction_product == -2) {
            $selected_products = $cartRule->checkProductRestrictionsFromCart($cart, true);
            if (is_array($selected_products)) {
                foreach ($this->cartRows as $cartRow) {
                    $product = $cartRow->getRowData();
                    if ((in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                        || in_array($product['id_product'] . '-0', $selected_products))
                           && (($cartRule->reduction_exclude_special && !$product['reduction_applies'])
                               || !$cartRule->reduction_exclude_special)) {
                        $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
                        $cartRuleData->addDiscountApplied($amount);
                    }
                }
            }
        }
```
I hope it helps

**Comment by hibatallahAouadni** [comment] 2021-05-17 09:08
Hello @josearandac 

Could you please create a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). 
Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by josearandac** [comment] 2021-05-17 10:22
Hello @hibatallahAouadni ,

A pull request already exists:

[18144](https://github.com/PrestaShop/PrestaShop/pull/18144)

I just found it.

Thank you!

**Comment by khouloudbelguith** [comment] 2021-05-24 15:06
Hi @marionf,

As commented [here](https://github.com/PrestaShop/PrestaShop/issues/19090#issuecomment-732193568), the issue is fixed
![image](https://user-images.githubusercontent.com/16067358/119366531-5d91c680-bcb1-11eb-9bad-e4e4bf68248c.png)

177x (1775 => ok): https://drive.google.com/file/d/1wIIN_4lgP13CqVA0OSgcRkDS9yAXTEnH/view?usp=sharing
178x => ok

Thank you!

**Closed as completed by khouloudbelguith** 2021-05-24 15:06 UTC
Labels: Bug, Major, BO, FO, Discounts, Cart rules, Fixed, 1.7.7.0, 1.7.6.5
