### ISSUE TITLE
FATAL ERROR IN PRESTA 1.7.4.3 PAY DONT WORK

### ISSUE THREAD

**Issue by Leous88** [PrestaShop/PrestaShop#11114] opened 2018-10-23 02:17 UTC
**Describe the bug**
PAY OPTIONS DONT WORK
ANY OPTION WORK 

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7

**Comment by khouloudbelguith** [comment] 2018-10-23 08:39
Hi @Leous88,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-23 16:17
Hi @Leous88,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
THanks!

**Closed as completed by khouloudbelguith** 2018-11-23 16:17 UTC
Labels: Bug, BO, No change required, 1.7.4.3
