### ISSUE TITLE
Cancel Order For Customer

### ISSUE THREAD

**Issue by davidhardik** [PrestaShop/PrestaShop#19878] opened 2020-06-20 09:41 UTC
#### Is your feature request related to a problem?

Many customers asks us to cancel their order as they can't do it from their profile page. Giving them option till the package is not in delivery. This will help them to choose or cancel the wrong product selected and also will make them order the right package.

#### Describe the solution you'd like

A feature to allow the website owner to enable to disable the options to allow customers to have the cancel order button so that it becomes user friendly. 

#### Alternatives you've considered

It is a very important E-commerce feature and should be included in prestashop as well. The alternatives are plugins/modules that increases the load time of the website through js and css.

**Comment by PierreRambaud** [comment] 2020-06-22 09:07
Hi @davidhardik and thanks for your report.

@PrestaShop/prestashop-product-team  What do you think? Could be a nice improvement to allow users to cancel their commands if it's possible :thinking:

**Comment by colinegin** [comment] 2020-07-15 15:30
This issue is a duplicate of #20135 . I close this issue so that we can all comment on the same issue, please follow #20135 .

Thanks !

**Closed as completed by colinegin** 2020-07-15 15:30 UTC
Labels: Improvement, FO, Duplicate

**Comment by hibatallahAouadni** [comment] 2021-01-18 12:52
Duplicate of #20135
