### ISSUE TITLE
[1.7.7 beta 2] Error when changing currency decimals

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20820] opened 2020-09-02 09:44 UTC
#### Steps to Reproduce

1. Install 1.7.7 beta 2 in czech language.
2. Go to currencies.
3. Open CZK.
4. Change decimal places from 2 to 0.
5. See error screen.

The root cause of this issue is clearing the cache after changing the currency. https://github.com/PrestaShop/PrestaShop/issues/11105

**Log**

```
[02-Sep-2020 11:12:49 Europe/Prague] PHP Warning:  require(/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getSecurity_Firewall_Map_Context_MainService.php): failed to open stream: No such file or directory in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:49 Europe/Prague] PHP Fatal error:  require(): Failed opening required '/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getSecurity_Firewall_Map_Context_MainService.php' (include_path='/srv/www/trendo.cz/public/beta/vendor/pear/pear_exception:/srv/www/trendo.cz/public/beta/vendor/pear/console_getopt:/srv/www/trendo.cz/public/beta/vendor/pear/pear-core-minimal/src:/srv/www/trendo.cz/public/beta/vendor/pear/archive_tar:.:/usr/share/php') in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:50 Europe/Prague] PHP Warning:  require(/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getPrestashop_Core_Foundation_VersionService.php): failed to open stream: No such file or directory in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:50 Europe/Prague] PHP Fatal error:  require(): Failed opening required '/srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/getPrestashop_Core_Foundation_VersionService.php' (include_path='/srv/www/trendo.cz/public/beta/vendor/pear/pear_exception:/srv/www/trendo.cz/public/beta/vendor/pear/console_getopt:/srv/www/trendo.cz/public/beta/vendor/pear/pear-core-minimal/src:/srv/www/trendo.cz/public/beta/vendor/pear/archive_tar:.:/usr/share/php') in /srv/www/trendo.cz/public/beta/var/cache/prod/ContainerDdqbeec/appProdProjectContainer.php on line 2228
[02-Sep-2020 11:12:50 Europe/Prague] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/srv/www/trendo.cz/public/beta/var/cache/prod/": rmdir(/srv/www/trendo.cz/public/beta/var/cache/prod/): Directory not empty. in /srv/www/trendo.cz/public/beta/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /srv/www/trendo.cz/public/beta/classes/Tools.php(3448): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /srv/www/trendo.cz/public/beta/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

#### Additional information

* PrestaShop version: 1.7.7 beta 2
* PHP version: 7.2

**Comment by Hlavtox** [comment] 2020-09-02 10:06
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/20689

**Comment by sarahdib** [comment] 2020-09-02 12:26
@Hlavtox 
I try to reproduce but I couldn't : https://drive.google.com/file/d/1sUyd9q8xBcx2ohWVZ5QzYGMPWhB1tUh7/view
I can't find this error in dev.log

There is any other step to reproduce ?

Thank you

**Comment by Hlavtox** [comment] 2020-09-02 15:32
@sarahdib The issue is hard to reproduce, happens for some part of users. The issue will be fixed when #11105 is fixed, but keep it open please...

**Comment by khouloudbelguith** [comment] 2020-09-07 09:48
Hi @Hlavtox,

I tried with 1770beta2, PHP7.2, but I did not manage to reproduce the issue.
I attached a screen record
https://drive.google.com/file/d/1s2EUMe8gLXo2PpgJHBiiAO97lGJDtE37/view?usp=sharing
In the file /var/logs/dev.log, I couldn't find any error similar to this
```
Stack trace:
#0 /srv/www/trendo.cz/public/beta/classes/Tools.php(3448): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /srv/www/trendo.cz/public/beta/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

Thanks to check and feedback.

**Comment by jolelievre** [comment] 2020-09-10 09:34
Hello @Hlavtox,

since https://github.com/PrestaShop/PrestaShop/pull/20689 has been merged I guess we can close this issue since it was related to https://github.com/PrestaShop/PrestaShop/issues/11105

The bug is now fixed, it will only be integrated in 178 though.

**Comment by marionf** [comment] 2020-09-16 08:43
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20689

**Closed as completed by marionf** 2020-09-16 08:43 UTC
Labels: Bug, BO, Currencies, Fixed, 1.7.7.0
