### ISSUE TITLE
MyISAM is still default engine for DB connection test --> Azure MySQL connection fails

### ISSUE THREAD

**Issue by Fobe24** [PrestaShop/PrestaShop#12675] opened 2019-02-22 14:27 UTC
**Describe the bug**
When deploying Prestashop 1.7.5.1 (docker image) as a Web App in Microsoft Azure and using Azure Database for MySQL, the connection test at the installation setup will fail, because MyISAM is still used and not supported by Azure MySQL (or Google Cloud SQL).

"Got error 1 from storage engine" is returned as an error, which usually means, that MyISAM is used instead of InnoDB.

1. Deploy Prestashop as a container using the latest docker image from image hub
2. Use Azure Database for MySQL and try to connect at step 5 of the setup

**Additionnal information**
https://github.com/PrestaShop/PrestaShop/blob/master/classes/db/DbPDO.php Line 317
The engine should be InnoDB

**Comment by khouloudbelguith** [comment] 2019-02-22 14:41
Hi @Fobe24,

when using PS in our docker image, this is how we fix it: https://github.com/PrestaShop/docker#during-the-installation-prestashop-cannot-connect-to-mysql---bad-charset

Hope it helps!
Thanks to check & feedback

**Comment by philipp-hb** [comment] 2019-02-25 08:21
Hi,
I got the same problem: connect to the DB works fine, but the I get error 1
In the following serverfault thread, someone has the same problem and fixes it by changing the engine to InnoDB in the file @Fobe24 mentioned: https://serverfault.com/questions/862267/prestashop-google-cloud-sql

**Comment by khouloudbelguith** [comment] 2019-02-26 10:37
@Fobe24, any news about your issue?
Thanks!

**Comment by Fobe24** [comment] 2019-02-27 09:43
The problem still exists, it has nothing to do with the charset. The DB engine used for the connection test is not compatible with managed MySQL databases from cloud providers like Azure or AWS.

**Comment by khouloudbelguith** [comment] 2019-02-27 11:26
ping @Quetzacoalt91 @PierreRambaud is this a problem with the PrestaShop docker image?
What do you think?
Thanks!

**Comment by Quetzacoalt91** [comment] 2019-02-27 11:43
PrestaShop on docker only has the PHP server. Any SQL configuration issue is not caused by the image itself.
As said by @Fobe24 & @philipp-hb, this could be fixed by the changes suggested. This issue could be reproduced if we try to connect to a MySQL server with MyISAM disabled.

**Comment by khouloudbelguith** [comment] 2019-02-27 15:39
Hi @Quetzacoalt91,

Thanks for your feedback.
I added this line `disabled_storage_engines = "MyISAM"` to my file `/etc/mysql/my.cnf` & I restart the mysql container, in step 5 during the install, the database is well connected
![image](https://user-images.githubusercontent.com/16067358/53502394-3fc36000-3aae-11e9-8127-5ef9e4e5a786.png)
Thanks!

**Closed as completed** 2020-06-16 13:19 UTC
Labels: IN, Fixed, 1.7.5.1, PR available
