### ISSUE TITLE
Email previsualisation fail while you have no orders on your shop

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30289] opened 2022-11-14 13:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you have no orders on the shop and try to see an email, you get an error.

<img width="827" alt="Capture d’écran 2022-11-14 à 14 14 54" src="https://user-images.githubusercontent.com/2631425/201669635-74c7e29a-0b32-4e65-bd57-c884da7eb0e6.png">

### Steps to reproduce

1. Have no orders at all
2. Go to Apparence > Emails > Modern theme and click on the HTTP icon

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by hibatallahAouadni** [comment] 2022-11-15 09:14
Hello @PrestaEdit 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26919. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-11-15 09:14
Duplicate of #26919

**Closed as completed by hibatallahAouadni** 2022-11-15 09:14 UTC
Labels: Bug, Duplicate, Invalid

**Comment by PrestaEdit** [comment] 2022-11-15 09:15
Thanks and sorry, @hibatallahAouadni !
