### ISSUE TITLE
The modules tab doesn't appear in the product editor

### ISSUE THREAD

**Issue by Rolige** [PrestaShop/PrestaShop#19246] opened 2020-05-20 17:23 UTC
#### Describe the bug

After install a module using the hook "displayAdminProductsExtra" the module doesn't appear in the module tab in the product editor because the modules tab doesn't appear.

#### Expected behavior

The modules tab in the product editor should appear after install the module using the hook "displayAdminProductsExtra".

#### Steps to Reproduce

1. Install a module using the hook "displayAdminProductsExtra"
2. Edit any product
3. The Modules tab doesn't appear.

**Screenshots**

![Example without fix](https://user-images.githubusercontent.com/2866694/82364711-e30ed680-99cc-11ea-8999-1985ee81682a.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.31

**Comment by florine2623** [comment] 2020-05-22 15:07
Hi @PrestaShop/prestashop-core-developers ,

Can one of you try to reproduce the issue please ? :)
Thanks!

**Comment by colinegin** [comment] 2020-05-25 13:09
Hello @rolige, is your issue a regression of 177 or a bug that was already existing in previous versions of 1.7 ?

**Comment by Rolige** [comment] 2020-05-25 15:45
> Hello @Rolige, is your issue a regression of 177 or a bug that was already existing in previous versions of 1.7 ?

To be honest I’m not sure if it’s a regression or not, which is clear is that this bug didn’t exist in the previous stable release.

**Comment by PierreRambaud** [comment] 2020-05-27 15:07
It must be in the 1.7.7.x since it a regression, it was working on the previous version regarding #19403

**Comment by Matt75** [comment] 2020-05-27 15:25
Can be reproduced with https://github.com/Matt75/testhookdisplayadminproductsextra

**Comment by Progi1984** [comment] 2020-05-29 09:27
Fixed by #19452

**Closed as completed by Progi1984** 2020-05-29 09:27 UTC
Labels: Major, BO, Modules, Regression, Fixed, 1.7.7.0
