### ISSUE TITLE
Cart Rules: Checkout error with free shipping and carrier selection restriction

### ISSUE THREAD

**Issue by pantagru** [PrestaShop/PrestaShop#18482] opened 2020-04-06 16:32 UTC
#### Describe the bug

I have many manufacturers, each one with his own carriers.
I need to add a cart rule with free shipping for one specific carrier in a specific zone for a period.
I create a rule. I assign name and promo code. Under restriction I set only one zone (Nation), and only one carrier. Under actions I set free shipping.
When in FO I insert the code in the checkout (after the right carrier selection in  3 - Shipping Method step), nothing happens, if I continue to the step 4 - Payment, I get this error.
![immagine](https://user-images.githubusercontent.com/41157394/78581087-ab403b00-7833-11ea-866b-4a449354fd5c.png)
I have deactived no native modules in PrestaShop but nothing change.

#### Additional information

    PrestaShop version: 1.7.2.4
    PHP version: PHP 7.1.33

**Comment by khouloudbelguith** [comment] 2020-04-06 17:19
Hi @pantagru,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1y1FgRW9bmQYcr0g3M-py4NoPfubIuAhi/view?usp=sharing

Thanks to check and feedback.

**Comment by pantagru** [comment] 2020-04-07 09:28
Hi,
could you please tell me how is your getTotalShippingCost function in class cart.php from line 3138?

**Comment by khouloudbelguith** [comment] 2020-04-07 10:56
@pantagru, you can check the file [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/classes/Cart.php).

Thanks!

**Comment by pantagru** [comment] 2020-04-07 14:02
Hi, my PrestaShop version is not 1.7.6.4, but 1.7.2.4.
Can you try to reproduce the issue with my version 1.7.2.4?
I checked and your card.php version for 1.7.2.4 is the same of mine.
Thank you

**Comment by khouloudbelguith** [comment] 2020-04-07 17:19
@pantagru, Issue reproduced with PS1.7.2.4 but not reproduced in PS1.7.3.0.
https://drive.google.com/file/d/1zwYqZXST5LwN7u-Ey2djgaTK50I0kD2G/view?usp=sharing
So, it is fixed in PS1.7.3.0.
check with this PR:
https://github.com/PrestaShop/PrestaShop/pull/8402
https://github.com/PrestaShop/PrestaShop/pull/8083
The issue in PS 1.7.2.4 exists but it is fixed in PS 1.7.3.0.
You can check the changelog for PS1.7.3.0 [here](https://assets.prestashop2.com/fr/system/files/ps_releases/changelog_1.7.3.0.txt)

Since the issue is fixed previously, I will close the issue, feel free to open a new one when needed.

Thanks:

**Closed as completed by khouloudbelguith** 2020-04-07 17:19 UTC
Labels: Bug, FO, 1.7.2.4, Discounts, No change required, Checkout
