### ISSUE TITLE
Template order_conf email layout has a problem

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#24287] opened 2021-04-30 14:16 UTC
Hi,
I don't find the problem and I don't understand why this happens:
layout of the email template of the theme in use (test done on both the classic theme and the purchased theme)

<img width="406" alt="Schermata 2021-04-30 alle 16 00 54" src="https://user-images.githubusercontent.com/28685316/116706282-c4330580-a9cd-11eb-882d-060e1e2d567f.png">

I just entered a **x**:
<img width="406" alt="Schermata 2021-04-30 alle 16 01 18" src="https://user-images.githubusercontent.com/28685316/116706637-1d029e00-a9ce-11eb-8e54-5d0f0ef80cb0.png">

Orders placed within three minutes of each other!

steps performed

1 - International
2 -Translations
3 - Type of translation: email translations
4 - Select the type of email content: Body
5 - Select your theme: theme currently in use
6 - Select your language: language currently in use on the site
7 - Clicked on core emails
7 - Clicked on order_conf
8 - Putted x after the Payment words
9 - Save
10 - made an order

And the layout changed.
I didn't added html code or change something, I did this operation on multiple locally sites installed on MAMP, with different installed templates, it is always the same.
I tried to copy the code of the working model but it didn't qorks.
At this point I ran out my resources.
Thanks for any reply.
Balla

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by matks** [comment] 2021-04-30 20:28
Hello @ballashop you mean that
1. You introduce a very small change inside the mail theme layout
2. You observe a big change in how the mail is being displayed

**Comment by ballashop** [comment] 2021-05-01 07:46
Hi @matks, 
exact.
From what I understand, when you use a theme, the "operational" mails sent automatically to the system such as order_conf, are inside the theme folder in the following directory
root/themes/theme_in_use/mails/.
I have installed several PrestaShop sites in MAMP both with classic theme and with purchased theme.
All test order_config emails reported the same problem.
Now I'm testing sending emails in another language.
I let you know asap.
Thanks a lot for your answer.
Balla

**Comment by ballashop** [comment] 2021-05-01 08:58
Hi @matks,
the email in English works so I copied it in the folder of the language we use, I translated the texts and did the purchase tests.
Layout is ok now.
Bye.
Balla

ps. I also copied the file to the operating site so check if it also works online.

**Comment by hibatallahAouadni** [comment] 2021-05-03 08:37
Hello @ballashop 

I reproduce the issue with PS1.7.7.3, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/116856372-59671180-abfb-11eb-9220-85b376486997.png)

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #21630. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @matks for your quick reply :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-03 08:37
Duplicate of #21630

**Closed as completed by hibatallahAouadni** 2021-05-03 08:37 UTC
Labels: Duplicate

**Comment by ballashop** [comment] 2021-05-03 08:56
Ok @hibatallahAouadni thanks a lot.

> To be informed when it's fixed, please subscribe to the issue mentioned above.

I did.
Bye.
Balla

**Comment by lmarti91** [comment] 2022-02-22 09:44
Hi @ballashop 
I do the same thing that you did in this post:
_**the email in English works so I copied it in the folder of the language we use, I translated the texts and did the purchase tests.
Layout is ok now.**_
But in my case, it doesn't work. Colud you explain me how did you solve the problem? I update the template in FTP and Prestashop Translations. 
Thank you!

Here you can see my error: 
![image](https://user-images.githubusercontent.com/100197953/155106046-2010866a-0486-4288-821e-329da48cca59.png)
