### ISSUE TITLE
Search bar - the search_bar module is not well displayed with RTL language

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28462] opened 2022-05-11 11:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO, the search_bar module is not well displayed with RTL language

https://user-images.githubusercontent.com/89604350/167835863-9090ce64-60b3-46b0-acbb-2b867a992460.mp4

### Steps to reproduce

1. fresh install 1.7.8.5
2. Upgrade the module search bar to the version 2.1.2
3. Add an Arabic Language
4. Go to BO > Design > Theme & Logo page
5. Enable RTL and save
6. Go to FO
7. change language to Arabic
8. See error in the search bar

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3/7.2/7.4

### If your bug is related to a module, specify its name and its version

Search bar v2.1.2

**Comment by marwachelly** [comment] 2022-05-11 11:14
Related to https://github.com/PrestaShop/PrestaShop/issues/26569

**Comment by hibatallahAouadni** [comment] 2023-05-31 09:36
Duplicate of #26569

**Closed as completed by hibatallahAouadni** 2023-05-31 09:36 UTC
Labels: Bug, FO, Duplicate, Regression, Front-end, Search bar, Invalid, Module
