### ISSUE TITLE
Back office orders errors after upgrading to Prestashop 1.7.7.8

### ISSUE THREAD

**Issue by bsylwek** [PrestaShop/PrestaShop#25996] opened 2021-09-24 19:57 UTC
#### Describe the bug

I have problems after updating with autoupgrade to 1.7.7.8. All modules have been updated. How can this be fixed? However, should you restore from a backup?

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to 'back office.'
2. Click on 'orders and details'
3. See error

**Screenshots**
![obraz](https://user-images.githubusercontent.com/66308504/134874047-2e5200dc-b56d-4db4-b629-6921acb4f448.png)

![obraz](https://user-images.githubusercontent.com/66308504/134873972-6b0c172c-02c8-4668-8210-4001a0ec576c.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.2

**Comment by yo7hli** [comment] 2021-09-24 21:08
it's caused by the db schema changes, most likely because you have null fields in your ps_order_state and or ps_order_state_lang tables. 
run an sql update to change your null fields to an empty string and see if that fixes it.

**Comment by bsylwek** [comment] 2021-09-24 21:12
I have access to phpmyadmin. What does the command to fix this in phpmyadmin look like?

**Comment by yo7hli** [comment] 2021-09-24 21:32
supposing the `name` column in `ps_order_state_lang` is NULL for some rows, you should run an sql query that would look like
`UPDATE ps_order_state_lang SET name='' WHERE name IS NULL;`

if that's the case, you should at least get a different error message which should point out other fields that need to be updated.

also checkout this similar issues [22215](https://github.com/PrestaShop/PrestaShop/issues/22215) and [22386](https://github.com/PrestaShop/PrestaShop/issues/22386)

**Comment by bsylwek** [comment] 2021-09-24 21:43
I have the Prestashop autoupgrade module in the latest version. So if I understand correctly, he didn't change it during the update?

In these tables, I don't see NULL anywhere except Create table. Should I change that?
```
CREATE TABLE `ps_order_state` (
  `id_order_state` int(10) UNSIGNED NOT NULL,
  `invoice` tinyint(1) UNSIGNED DEFAULT '0',
  `send_email` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `module_name` varchar(255) DEFAULT NULL,
  `color` varchar(32) DEFAULT NULL,
  `unremovable` tinyint(1) UNSIGNED NOT NULL,
  `hidden` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `logable` tinyint(1) NOT NULL DEFAULT '0',
  `delivery` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `shipped` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `paid` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `pdf_invoice` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `pdf_delivery` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `deleted` tinyint(1) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

```
Zrzut danych tabeli `ps_order_state`
--
```

INSERT INTO `ps_order_state` (`id_order_state`, `invoice`, `send_email`, `module_name`, `color`, `unremovable`, `hidden`, `logable`, `delivery`, `shipped`, `paid`, `pdf_invoice`, `pdf_delivery`, `deleted`) VALUES
(1, 0, 1, 'ps_checkpayment', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(2, 1, 1, '', '#3498D8', 1, 0, 1, 0, 0, 1, 1, 0, 0),
(3, 1, 1, '', '#3498D8', 1, 0, 1, 1, 0, 1, 0, 0, 0),
(4, 1, 1, '', '#01b887', 1, 0, 1, 1, 1, 1, 0, 0, 0),
(5, 1, 0, '', '#01b887', 1, 0, 1, 1, 1, 1, 0, 0, 0),
(6, 0, 1, '', '#2C3E50', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(7, 1, 1, '', '#01b887', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(8, 0, 1, '', '#E74C3C', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(9, 1, 1, '', '#3498D8', 1, 0, 0, 0, 0, 1, 0, 0, 0),
(10, 0, 1, 'ps_wirepayment', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(11, 1, 1, '', '#3498D8', 1, 0, 1, 0, 0, 1, 0, 0, 0),
(12, 0, 1, '', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(13, 0, 0, 'ps_cashondelivery', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(14, 0, 0, '', 'Lightblue', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(15, 1, 0, '', '#3498D8', 1, 0, 0, 0, 0, 1, 0, 0, 0),
(16, 0, 0, 'bagsoffintegration', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(17, 1, 0, 'bagsoffintegration', '#3498D8', 1, 0, 1, 0, 0, 1, 1, 0, 0),
(18, 1, 0, 'bagsoffintegration', '#01b887', 1, 0, 1, 1, 1, 1, 0, 1, 0),
(19, 0, 0, 'przelewy24', 'Lightblue', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(20, 1, 0, 'przelewy24', '#3498D8', 1, 0, 0, 0, 0, 1, 0, 0, 0),
(21, 0, 0, 'paypal', '#34209E', 0, 0, 0, 0, 0, 0, 0, 0, 0),
(22, 0, 0, 'ps_checkout', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(23, 0, 0, 'ps_checkout', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(24, 0, 0, 'ps_checkout', '#34209E', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(25, 0, 0, 'ps_checkout', '#3498D8', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(26, 0, 0, 'ps_checkout', '#01B887', 1, 0, 0, 0, 0, 0, 0, 0, 0),
(27, 0, 0, 'ps_checkout', '#3498D8', 1, 0, 0, 0, 0, 0, 0, 0, 0);

```
-- --------------------------------------------------------

Struktura tabeli dla tabeli `ps_order_state_lang`
--
```

CREATE TABLE `ps_order_state_lang` (
  `id_order_state` int(10) UNSIGNED NOT NULL,
  `id_lang` int(10) UNSIGNED NOT NULL,
  `name` varchar(64) NOT NULL,
  `template` varchar(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

```
Zrzut danych tabeli `ps_order_state_lang`
--
```

INSERT INTO `ps_order_state_lang` (`id_order_state`, `id_lang`, `name`, `template`) VALUES
(1, 1, 'Oczekiwanie na płatność czekiem', 'cheque'),
(1, 2, 'Awaiting check payment', 'cheque'),
(2, 1, 'Płatność zaakceptowana', 'payment'),
(2, 2, 'Payment accepted', 'payment'),
(3, 1, 'Przygotowanie w toku', 'preparation'),
(3, 2, 'Processing in progress', 'preparation'),
(4, 1, 'Dostarczane', 'shipped'),
(4, 2, 'Shipped', 'shipped'),
(5, 1, 'Dostarczone', ''),
(5, 2, 'Delivered', ''),
(6, 1, 'Anulowane', 'order_canceled'),
(6, 2, 'Canceled', 'order_canceled'),
(7, 1, 'Zwróconych pieniędzy', 'refund'),
(7, 2, 'Refunded', 'refund'),
(8, 1, 'Błąd płatności', 'payment_error'),
(8, 2, 'Payment error', 'payment_error'),
(9, 1, 'Zamówienie oczekujące (opłacone)', 'outofstock'),
(9, 2, 'On backorder (paid)', 'outofstock'),
(10, 1, 'Oczekiwanie na płatność przelewem', 'bankwire'),
(10, 2, 'Awaiting bank wire payment', 'bankwire'),
(11, 1, 'Płatność przyjęta', 'payment'),
(11, 2, 'Remote payment accepted', 'payment'),
(12, 1, 'Zamówienie oczekujące (nieopłacone)', 'outofstock'),
(12, 2, 'On backorder (not paid)', 'outofstock'),
(13, 1, 'Oczekiwanie na płatność przy odbiorze', 'cashondelivery'),
(13, 2, 'Awaiting Cash On Delivery validation', 'cashondelivery'),
(14, 1, 'Oczekiwanie na płatność Przelewy24', ''),
(14, 2, 'Oczekiwanie na płatność Przelewy24', ''),
(15, 1, 'Płatność Przelewy24 przyjęta', 'payment'),
(15, 2, 'Płatność Przelewy24 przyjęta', 'payment'),
(16, 1, 'BagsOff oczekuje na płatność', ''),
(16, 2, 'BagsOff oczekuje na płatność', ''),
(17, 1, 'BagsOff opłacone', ''),
(17, 2, 'BagsOff opłacone', ''),
(18, 1, 'BagsOff wysłane', ''),
(18, 2, 'BagsOff wysłane', ''),
(19, 1, 'Oczekiwanie na płatność Przelewy24', ''),
(19, 2, 'Oczekiwanie na płatność Przelewy24', ''),
(20, 1, 'Płatność Przelewy24 przyjęta', 'payment'),
(20, 2, 'Płatność Przelewy24 przyjęta', 'payment'),
(21, 1, 'Awaiting for PayPal payment', ''),
(21, 2, 'Awaiting for PayPal payment', ''),
(22, 2, 'Waiting for PayPal payment', 'payment'),
(23, 2, 'Waiting for Credit Card Payment', 'payment'),
(24, 2, 'Waiting for Local Payment Method Payment', 'payment'),
(25, 2, 'Authorized. To be captured by merchant', 'payment'),
(26, 2, 'Partial refund', 'payment'),
(27, 2, 'Waiting capture', 'payment');

```
Indeksy dla zrzutów tabel
--

Indeksy dla tabeli `ps_order_state`
--
```
ALTER TABLE `ps_order_state`
  ADD PRIMARY KEY (`id_order_state`),
  ADD KEY `module_name` (`module_name`);
```
Indeksy dla tabeli `ps_order_state_lang`
--
```
ALTER TABLE `ps_order_state_lang`
  ADD PRIMARY KEY (`id_order_state`,`id_lang`);
```
AUTO_INCREMENT dla zrzuconych tabel
--

 AUTO_INCREMENT dla tabeli `ps_order_state`
--
```
ALTER TABLE `ps_order_state`
  MODIFY `id_order_state` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;
COMMIT;
```

**Comment by bsylwek** [comment] 2021-09-27 07:21
Is there any more idea why this error is showing up? I cannot find NULL in the indicated database table.

**Comment by hibatallahAouadni** [comment] 2021-09-27 08:09
Hello @bsylwek 

Could you please provide your previous PrestaShop version, the auto upgrade module version.
Please check and feedback.

PS: thanks @yo7hli for your quick replies 🚀 

Thanks!

**Comment by bsylwek** [comment] 2021-09-27 08:15
1-Click Upgrade v4.12.0 , previous version Prestashop 1.7.7.7

**Comment by bsylwek** [comment] 2021-09-27 08:25
I have already looked through the orders and this error appears only where there was a payment with PAYPAL. Where there is a bank transfer no error.
![obraz](https://user-images.githubusercontent.com/66308504/134871539-9ed3c01f-8d5b-47fc-bd92-f60cd68d6adc.png)
PayPal v5.4.5 
PrestaShop Checkout v2.0.6

**Comment by yo7hli** [comment] 2021-09-27 11:07
@bsylwek 
check if the `current_state` field in db table `ps_orders` corresponds to a valid `id_order_state` in `ps_order_state` and `ps_order_state_lang` for the id_order in question

e.g. the following query:
`SELECT sl.name FROM ps_orders AS o LEFT JOIN ps_order_state_lang sl ON (sl.id_order_state = o.current_state) WHERE o.id_order = id_order;` <- replace `id_order` here with an order id that triggers the error.
should return a non NULL value

**Comment by bsylwek** [comment] 2021-09-27 13:11
Do you have an order number with this error at the end?
`SELECT sl.name FROM ps_orders AS o LEFT JOIN ps_order_state_lang sl ON (sl.id_order_state = o.current_state) WHERE o.id_order = 5;`

I get this message in phpmyadmin after giving this command.
Rows 0 - 1 shown (2 total, The query took 0.0007 seconds to execute.)

**Comment by hibatallahAouadni** [comment] 2021-09-27 13:52
Hello @bsylwek 

Did you check with the Module Developer, cause I didn't manage to reproduce your issue :disappointed: 
Please check with Paypal module Developer and feedback.

Thanks!

**Comment by bsylwek** [comment] 2021-09-27 14:56
I wrote to the developer of the PAYPAL module.

**Comment by hibatallahAouadni** [comment] 2021-09-27 15:02
Great, let's wait for his feedback :wink:

**Comment by bsylwek** [comment] 2021-09-27 18:47
Most likely I solved the problem. After the update, only one language is added, e.g. 1 English. All languages ​​must be present if installed as there will be bugs. Below, for example, added for the language.

`INSERT INTO `ps_order_state_lang` (`id_order_state`, `id_lang`, `name`, `template`) VALUES
(22, 1, 'Waiting for PayPal payment', 'payment'),
(23, 1, 'Waiting for Credit Card Payment', 'payment'),
(24, 1, 'Waiting for Local Payment Method Payment', 'payment'),
(25, 1, 'Authorized. To be captured by merchant', 'payment'),
(26, 1, 'Partial refund', 'payment'),
(27, 1, 'Waiting capture', 'payment');`

**Comment by khouloudbelguith** [comment] 2021-10-01 09:18
Hi @bsylwek,

I did not manage to reproduce the issue following these steps:

1. Install PS1777 with two languages
2. Install the module Paypal 
3. Configure it with Sandbox 
4. Create an order with Paypal 
5. Upgrade to PS1778
6. Check the orders => ok
7. Add Español (Spanish) lanaguge
8. Change the employee language to Español (Spanish)
9. Check orders => ok

Did I miss something, can you help us with the exact steps to reproduce the issue?
Have you any feedback from the Paypal module Author?

Thanks!

**Comment by bsylwek** [comment] 2021-10-01 09:25
I solved the problem and it concerned the missing entries in the database in the table for the Polish language. An example of missing entries in the database is presented above.

**Comment by khouloudbelguith** [comment] 2021-10-01 11:47
> I solved the problem and it concerned the missing entries in the database in the table for the Polish language. An example of missing entries in the database is presented above.

The Polish language is added before the upgrade or after the upgrade?
The employee language is Polish?
The Order is created in the Polish language?

Thanks!

**Comment by bsylwek** [comment] 2021-10-01 12:01
The Polish language was added before the update to version 1.7.7.8. After that, there was no update of this language.
The order is made in English, the administration panel is in Polish and in English to choose from. The error with the orders was only in Polish in the administration panel. After completing those missing from the database, the error no longer appears.

**Comment by khouloudbelguith** [comment] 2021-10-01 16:13
@bsylwek, I did not manage to reproduce the issue following these steps:
1. Add the Polish language 
2. Change employee language to Polish
3. Create an order with English with Paypal sandbox
4. Upgrade to PS1778
5. Check Order => ok

I attached a screen record
https://watch.screencastify.com/v/ms9ivOdFNx7tJFoqmwB1

Thanks!

**Comment by bsylwek** [comment] 2021-10-01 16:44
Exactly the same. I had a error. Only when I added the missing entries in the database, the error disappeared.

**Comment by hibatallahAouadni** [comment] 2021-10-04 13:06
Hello @bsylwek 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-10-04 13:06 UTC
Labels: Bug, BO, Can't reproduce, Order, Autoupgrade, 1.7.7.8
