### ISSUE TITLE
Two different orders with the same invoice ID

### ISSUE THREAD

**Issue by s-friedli** [PrestaShop/PrestaShop#23025] opened 2021-01-27 17:25 UTC
#### Describe the bug

If two different orders are passed at the same time (for my case 3 seconds), the id of the invoice is the same for both orders.
 
I would like to specify that the orders passed before and after these two doesn't have any problem.

#### Expected behavior

The id of the invoice have to be incremented each time a new order is passed.

#### Steps to Reproduce

1. Pass two orders at the same time

**Screenshots**

**TIME :** 

![orders](https://user-images.githubusercontent.com/65656961/106028157-e619a500-60cb-11eb-8555-8ff0e4a56d02.PNG)

**ORDER 1:**
![order_1022](https://user-images.githubusercontent.com/65656961/106028171-e9149580-60cb-11eb-9b64-22b172c22965.PNG)

**ORDER 2:**

![order_1023](https://user-images.githubusercontent.com/65656961/106028175-eade5900-60cb-11eb-9566-5d551bae905f.PNG)

**PDF INVOICE 1 :** 

![pdf_order_1022](https://user-images.githubusercontent.com/65656961/106028186-eca81c80-60cb-11eb-89b5-4a6dec88bd40.PNG)

**PDF INVOICE 2:** 

![pdf_order_1023](https://user-images.githubusercontent.com/65656961/106028202-f03ba380-60cb-11eb-937e-106b060d3fa4.PNG)

#### Additional information

* PrestaShop version:  1.7.6.4
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-01-28 11:11
Hello @s-friedli 

I didn't manage to repdouce your issue with PS1.7.6.1 and PS1.7.7.1, see the attached screenshots below:

## 1.7.7.1

![image](https://user-images.githubusercontent.com/23308427/106129936-09dafa80-6161-11eb-83e9-a8a03be78483.png)

**Order 1:** 

![image](https://user-images.githubusercontent.com/23308427/106129982-1cedca80-6161-11eb-83a3-47bf85270dba.png)

![image](https://user-images.githubusercontent.com/23308427/106129993-2119e800-6161-11eb-8b82-d97a65b8a906.png)

**Order 2:**

![image](https://user-images.githubusercontent.com/23308427/106130025-2d05aa00-6161-11eb-8031-f7c2800f4818.png)

![image](https://user-images.githubusercontent.com/23308427/106130044-31ca5e00-6161-11eb-8445-28c6803c51c4.png)

## 1.7.6.1
**Order 1:** 

![image](https://user-images.githubusercontent.com/23308427/106130602-d8aefa00-6161-11eb-8f19-8a92d284e1dd.png)

![image](https://user-images.githubusercontent.com/23308427/106130622-dd73ae00-6161-11eb-8f69-bc701ebc010a.png)

**Order 2:**

![image](https://user-images.githubusercontent.com/23308427/106130645-e49abc00-6161-11eb-887b-277e3345ddf9.png)

![image](https://user-images.githubusercontent.com/23308427/106130653-e95f7000-6161-11eb-9b52-454d220af1f4.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:22
Hello @s-friedli ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-17 13:22 UTC
Labels: Bug, BO, Order, Invoices, No change required, 1.7.6.1

**Comment by SylvainSimonGPA** [comment] 2023-03-21 09:30
Hello i come with a way to reproduce easily ! 

From ANY version of Prestashop from 1.7.7.2 (mine) and 8.0.*

In method setLastInvoiceNumber in 
classes\order\Order.php

The request is following : 
"SELECT new_number FROM (SELECT (MAX(`number`) + 1) AS new_number"

Its atrocious way to find the last available number because this method don't lock any other process concurrent executing an order integration at the same time to get the SAME maximum number. 

For reproduce, you just can put here, before executing the insert request, a sleep juste before the "Db::getInstance()->execute($sql)". When you validate the first order the sleep start, and then, validate another order in same time. The two order validation get the same maximum number....

This case is occured in production for my company !

We patched our prestashop by overriding setLastInvoiceNumber with a request who select in a created separate sequence
CREATE SEQUENCE ps_sequence_invoice_number START WITH 100000;

AND get next number by 
SELECT NEXT VALUE FOR ps_sequence_invoice_number;

Any hope to see a fix of this kind in Prestashop base code ? 
A good system for locking invoice number...
