### ISSUE TITLE
Customizations are shared if no cookie are sent

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#29259] opened 2022-08-05 09:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the browser doesn't send cookies and you save a customization, if another browser that doesn't send cookie open the product detail page, it will see the customization.

https://user-images.githubusercontent.com/2168836/183050931-28a7ed7b-179a-49e3-8dde-13d237eb4635.mov

### Expected behavior

Customizations shouldn't be saved if the server doesn't receive the cookie

### Steps to reproduce

1. Disable the cookie in the settings of your browser (see on the screen record to know how to do it)
2. As a guest, save a customization for the customizable mug for instance
3. In a private session or another browser that have cookie disabled, visit the customizable mug detail page
4. See that the customization is here

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by hibatallahAouadni** [comment] 2022-08-05 16:01
Hello @atomiix 

I was able to reproduce the issue with PrestaShop version 1777, 1786 and 800. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. 
So, we're waiting for your PR :rocket: 

Thank you

**Comment by Prestaworks** [comment] 2022-11-09 09:27
This is not minor, customers personal information is shared openly with strangers.

**Comment by Hlavtox** [comment] 2024-02-28 08:57
Fixed by https://github.com/PrestaShop/PrestaShop/pull/30252

**Closed as completed by Hlavtox** 2024-02-28 08:57 UTC
Labels: Bug, Minor, FO, Needs Specs, Performance, Product customization, PR available, Verified
