### ISSUE TITLE
[Idea] Use org build and release workflow

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#32902] opened 2023-06-14 08:15 UTC
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/32901

<div type='discussions-op-text'>

<sup>Originally posted by **leemyongpakvn** June 14, 2023</sup>
### The problem

Current build-release.yml of some native modules are outdated, that caused warnings in recent PRs such as [autoupgrade Release 4.15.0](https://github.com/PrestaShop/autoupgrade/actions/runs/3739690872) or [ps_mainmenu Release 2.3.2](https://github.com/PrestaShop/ps_mainmenu/actions/runs/4056715254). Using [organization build and release workflow](https://github.com/PrestaShop/.github/blob/master/.github/workflows/build-release.yml) will solve it.
In fact, @atomiix created organization build and release workflow and used it for some native modules' build-release.yml in 2022. But he becomes less active this year, so I create this issue to track the progress of updating build-release.yml for the remaining native modules.

- [x] autoupgrade
- [x] blockreassurance
- [x] blockwishlist
- [x] contactform
- [x] dashactivity
- [x] dashgoals
- [x] dashproducts
- [x] dashtrends
- [x] graphnvd3
- [x] gridhtml
- [x] gsitemap
- [x] pagesnotfound
- [x] productcomments
- [x] ps_banner
- [x] ps_bestsellers
- [x] ps_brandlist
- [x] ps_cashondelivery
- [x] ps_categoryproducts
- [x] ps_categorytree
- [x] ps_checkpayment
- [x] ps_contactinfo
- [x] ps_crossselling
- [x] ps_currencyselector
- [x] ps_customeraccountlinks
- [x] ps_customersignin
- [x] ps_customtext
- [x] ps_dataprivacy
- [x] ps_distributionapiclient
- [x] ps_emailalerts
- [x] ps_emailsubscription
- [x] ps_facetedsearch
- [x] ps_faviconnotificationbo
- [x] ps_featuredproducts
- [x] ps_googleanalytics
- [x] ps_imageslider 
- [x] ps_languageselector
- [x] ps_linklist
- [x] ps_mainmenu
- [x] ps_newproducts
- [x] ps_searchbar.yml
- [x] ps_sharebuttons
- [x] ps_shoppingcart
- [x] ps_socialfollow
- [x] ps_specials
- [x] ps_supplierlist
- [x] ps_themecusto
- [x] ps_viewedproduct
- [x] ps_wirepayment
- [x] psgdpr
- [x] statsbestcategories
- [x] statsbestcustomers
- [x] statsbestmanufacturers
- [x] statsbestproducts
- [x] statsbestsuppliers
- [x] statsbestvouchers
- [x] statscarrier
- [x] statscatalog
- [x] statscheckup
- [x] statsdata
- [x] statsforecast
- [x] statsnewsletter
- [x] statspersonalinfos
- [x] statsproduct
- [x] statsregistrations
- [x] statssales
- [x] statssearch
- [x] statsstock

### The solution

Just copy the updated build-release.yml content and override the outdated one content to complete the tasklist.

### Do you plan to work on this subject?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.</div>

**Comment by leemyongpakvn** [comment] 2023-06-20 11:00
@kpodemski Maybe there are wrong settings for ps_customtext because [my recent commit on its' build-release.yml](https://github.com/PrestaShop/ps_customtext/commit/6ef925d022e37ddb0800c226d6394efdbc4c87ee) is merged without any PR or review.

**Closed as completed** 2023-06-20 21:10 UTC
Labels: Feature, BO, Module

**Comment by kpodemski** [comment] 2023-06-20 21:12
@leemyongpakvn you now have a write access to the repos and you sent a commit directly to the dev branch :D

**Comment by leemyongpakvn** [comment] 2023-06-21 03:47
@kpodemski The problem is I **only** have direct write access permission to **ps_customtext** repo, not other repos. For example, I made [a commit on ps_currencyselector](https://github.com/PrestaShop/ps_currencyselector/pull/35) on the dev branch, the system warned that I am writing to a protected <s>repo</s> branch, and it created a new branch in the same repo (it used to be my own repo before I became a committer). Then I must create a PR and wait for review.
![ps_currencyselector_protectedRepo](https://github.com/PrestaShop/PrestaShop/assets/3759923/3aac80f2-a1b3-49f9-9f26-9abf7638095f)
I don't think granting direct write access to dev branch for committer role is a right setting |:)

**Comment by kpodemski** [comment] 2023-06-21 05:26
@leemyongpakvn yes, you're right, I'll check the settings

**Comment by leemyongpakvn** [comment] 2023-06-22 03:46
@kpodemski The dev branch of ps_cashondelivery, ps_brandlist are not protected either.

**Comment by leemyongpakvn** [comment] 2023-06-30 00:09
Mission accomplished :)
