### ISSUE TITLE
Reorder product position has an error

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#31388] opened 2023-02-15 17:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've found and error presente on 1.7.8.8 but I think it is also present in the 8.X
llok at this video
https://watch.screencastify.com/v/xGdbNDrSRxWFk4MlRjJl

after the reorder of products in a category the "reorder" button will be hidden and the "save and reload" button continue to be present also after completing the reordering of the positions

at the first time, I can do this operation many times, but if you push on the "reorder" button and you go in another page and the return in this product page after the reorder the "reorder" button is hidden

I've tried to clean the browser cache and all cookies, but "reorder" button is hidden

![1](https://user-images.githubusercontent.com/653230/219103003-005bd549-2715-433c-ae49-dc7bc50ac0fd.png)

the button reappears using a new employee

### Steps to reproduce

1. go in the admin panel
2. go in the catalog -> products
3. select a category
4. push on the "reorder" button
5. change a position
6. if all is ok and the "reorder" button returns, try to push again on it and go to the dashboard, then return to the previous page and do a position change and look if the "reorder" button return to be visible

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2023-02-16 08:25
Hello @maofree ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15291.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed by florine2623** 2023-02-16 08:25 UTC
Labels: Bug, Duplicate, Invalid

**Comment by hibatallahAouadni** [comment] 2023-02-16 22:34
Duplicate of #15291
