### ISSUE TITLE
Faceted Search doesn't filter unavailable combinations

### ISSUE THREAD

**Issue by superskyman100** [PrestaShop/PrestaShop#19023] opened 2020-05-07 01:53 UTC
#### Describe the bug

Products P1, .... Pn   have size variants XS, S, M, L, XL
Product P4 : variant XL out of stock

When use filter on catalog page to see products size XL, the product P4 appears whereas it shouldn't show up cause XL variation is out of stock

#### Expected behavior

The product P4 which is out of stock for size XL shouldn't appear on filter results if i search for XL products

#### Steps to Reproduce

0. Faceted search : set 'show unavailable products => NO' + filter size
1. Create product P4 with size attribute S, M, L, XL and two color attributes
2. Put the XL combinations stock=0 / out of stock for all colors
3. Go www.mywebsite.com/catalog
4. Filter by size XL
5. See error : the product P4 appears whereas it shouldn't

**Screenshots**

![Untitled-3](https://user-images.githubusercontent.com/60083930/81245335-49980a00-9047-11ea-9372-80dd4657f9c5.png)

![Untitled-2](https://user-images.githubusercontent.com/60083930/81245359-5a488000-9047-11ea-9e0f-794aa5578a89.png)

![Untitled-1](https://user-images.githubusercontent.com/60083930/81245376-659bab80-9047-11ea-930d-3c7c368af19e.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.24-0ubuntu0.18.04.3
* Faceted search : 3.5.0

**Comment by florine2623** [comment] 2020-05-07 07:24
Hi @superskyman100 ,
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/16952.
So, I close it.
Thanks!

**Comment by florine2623** [comment] 2020-05-07 07:25
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16952

**Closed as completed by florine2623** 2020-05-07 07:24 UTC
Labels: Bug, FO, Duplicate, Faceted search
