### ISSUE TITLE
It doesn't save when I select all categories

### ISSUE THREAD

**Issue by felipeseo** [PrestaShop/PrestaShop#36253] opened 2024-05-28 08:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It doesn't save when I select all the categories.
When I enter the template and select all the categories and then click save it does not save the categories
https://somup.com/cZhujD5mwR 

### Expected behavior

It should save all the selected categories

### Steps to reproduce

1. I enter the squad
2. I select all the categories with the available tool
3 save

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

7.4, 8

### If your bug is related to a module, specify its name and its version

facetedsearch v3.15.1

**Comment by paulnoelcholot** [comment] 2024-05-28 10:09
Hello @felipeseo,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://www.loom.com/share/ad4e8e4c9cf2439686ea8fee441d9824?sid=e97ca5d2-64c3-4f01-afd5-0654a1d2c071

**Closed as completed by paulnoelcholot** 2024-05-28 10:09 UTC
Labels: Bug, Can't reproduce

**Comment by felipeseo** [comment] 2024-05-28 10:22
It seems that you can only reproduce this problem when you have large amounts of categories, as is my case, and as in the case of this thread.

https://github.com/PrestaShop/PrestaShop/issues/17227
