### ISSUE TITLE
1.7.8.4 broken blog module with a 404. 1.7.8.3 working nice. /classes/Hook.php related issue.

### ISSUE THREAD

**Issue by Djolhan1** [PrestaShop/PrestaShop#27872] opened 2022-03-10 08:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Since the update of prestashop to 1.7.8.4, i have a 404 on front office blog module page.

Searched what could be the issue with this version, because 1.7.8.3 was working correctly, i found the file related to this commit : [https://github.com/PrestaShop/PrestaShop/pull/26748/commits/8e4980aca659c1e0178de7d9eecc7d98781e0d86](url)
, I have test with two differents blog module that ends on a 404. and putted back the /classes/Hook.php file from version 1.7.8.3 and no more "page not found". 

### Steps to reproduce

1 - Install prestashop
2 - Install any blog module
3 - Test blog page, give a 404 header.
4 - Change class/hook.php from 1.7.8.3
5 - No more 404.

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by Hlavtox** [comment] 2022-03-10 08:35
Maybe related to https://github.com/PrestaShop/PrestaShop/issues/27854.

Can you check small/capital letters in your blog module hook function names?

**Comment by lmeyer1** [comment] 2022-03-10 08:35
> 2 - Install any blog module

What blog module? What version?

**Comment by Djolhan1** [comment] 2022-03-10 08:37
> > 2 - Install any blog module
> 
> What blog module? What version?

Any blog module... Leo blog (last version) for exemple, Prestablog (last version) for another exemple, i don't have much, but either have the same issue.

**Comment by Djolhan1** [comment] 2022-03-10 08:38
> Maybe related to #27854.
> 
> Can you check small/capital letters in your blog module hook function names?

Where could i check that ?

**Comment by Djolhan1** [comment] 2022-03-10 09:58
Ok, this fix is tested and working perfect for the two blogs tested. thanks @lmeyer1

**Comment by hibatallahAouadni** [comment] 2022-03-10 13:40
Hello @Djolhan1

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27854. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-10 13:41
Duplicate of #27854

**Closed as completed by hibatallahAouadni** 2022-03-10 13:40 UTC
Labels: Bug, Duplicate, Invalid

**Comment by matks** [comment] 2022-03-14 21:15
@Djolhan1 @Hlavtox @web-burn We are trying to find a usecase to reproduce the issue. This would help us build the fix. Could you help us? A clear list of "how to observe the bug on your shop"

**Comment by Djolhan1** [comment] 2022-03-15 08:21
> @Djolhan1 @Hlavtox @web-burn We are trying to find a usecase to reproduce the issue. This would help us build the fix. Could you help us? A clear list of "how to observe the bug on your shop"

Install a module blog, check the home page of this one, broken link. Add the fix, no more broken link. How could i help you more ?

**Comment by kpodemski** [comment] 2022-03-15 08:23
@Djolhan1 thanks, I created an example module here: https://github.com/PrestaShop/PrestaShop/issues/27854#issuecomment-1067679731 - that should do it
