### ISSUE TITLE
Module upload pop-up overlapping header(z-index) issue

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11333] opened 2018-11-09 09:24 UTC
**Module upload pop-up hiding with header**
Please check screenshot
Can not remove popup (modal) also, If click on the outer side of modal its not working,

**To Reproduce**
1. Go to 'Module -> Module Manager'
2. Click on 'Upload a Module' button
3. See error

**Screenshots**
![module-upload-ps1750-beta1](https://user-images.githubusercontent.com/19220745/48254199-570f0c80-e42f-11e8-8c5c-4383e4c9e391.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 Beta 1
PHP version: 7

**Comment by khouloudbelguith** [comment] 2018-11-09 09:37
Hi @dheerajwebkul,

Here's the PR: #11104 to fix the issue.
Your ticket is a duplicate of #11042
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-09 09:37
Duplicate of #11042

**Closed as completed by khouloudbelguith** 2018-11-09 09:37 UTC
Labels: Duplicate
