### ISSUE TITLE
After running the new PrestaShop 1.7.7.0 update, the sidebar on the left side has disappeared

### ISSUE THREAD

**Issue by Lui72** [PrestaShop/PrestaShop#22605] opened 2020-12-28 11:24 UTC
I ran the update command of the new version of PrestaShop from V.1.6.9 to version V.1.7.7.0

I was hoping everything worked according to each new update

Steps to Reproduce
I saw the possibility of a new version

Go to '...' PRESTASHOP UPDATES
Click on '....' 1-Click Upgrade module
Scroll down to '....'
See error
Screenshots
https://microscopilubi.it/admin123/index.php?controller=AdminDashboard&token=d535b97a70cb6008c6030624a85ea872

If applicable, add screenshots or screen recordings to help explain your problem.

Additional information
PrestaShop version: N / A 1.7.7.0
PHP version: N / A 7.0
27122020 1435 - Screen cutout.pdf
[23122020 2337 - Ritaglio di schermata.pdf](https://github.com/PrestaShop/PrestaShop/files/5747108/23122020.2337.-.Ritaglio.di.schermata.pdf)
[24122020 0039 - Ritaglio di schermata.pdf](https://github.com/PrestaShop/PrestaShop/files/5747109/24122020.0039.-.Ritaglio.di.schermata.pdf)
[24122020 0039 - Ritaglio di schermata1.pdf](https://github.com/PrestaShop/PrestaShop/files/5747110/24122020.0039.-.Ritaglio.di.schermata1.pdf)
[24122020 2224 - Ritaglio di schermata.pdf](https://github.com/PrestaShop/PrestaShop/files/5747112/24122020.2224.-.Ritaglio.di.schermata.pdf)
[25122020 2112 - Ritaglio di schermata.pdf](https://github.com/PrestaShop/PrestaShop/files/5747113/25122020.2112.-.Ritaglio.di.schermata.pdf)
[25122020 2114 - Ritaglio di schermata.pdf](https://github.com/PrestaShop/PrestaShop/files/5747115/25122020.2114.-.Ritaglio.di.schermata.pdf)
[27122020 1435 - Ritaglio di schermata.pdf](https://github.com/PrestaShop/PrestaShop/files/5747116/27122020.1435.-.Ritaglio.di.schermata.pdf)

**Comment by hibatallahAouadni** [comment] 2020-12-28 16:27
Hello @Lui72 

We are aware of this issue. This issue is a duplicate of #22250

This issue is already fixed in the next patch 1.7.7.1
Please subscribe to the issue mentioned above.

I close this issue.
Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-28 16:28
Duplicate of #22250

**Closed as completed** 2020-12-28 16:28 UTC
Labels: Duplicate
