### ISSUE TITLE
Edit reserved items in stock, not possible in PS 1.4.2.1

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10389] opened 2018-09-12 04:35 UTC
![skarmavbild 2018-09-11 kl 18 26 04](https://user-images.githubusercontent.com/42907000/45402329-681ce680-b655-11e8-9ac2-0ad7fd1a395e.png)

I don't know if there is a way to edit reserved items in the stock or if this is a bug. When I migrated from 1.6.1.20 a few items got this "reserved".

If you could tell me where to hack the database I'm satisfied but I wonder also how this reserved function works.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9

**Comment by khouloudbelguith** [comment] 2018-09-12 08:36
Hi @peranderssjostrom,

Reserved stock represents the quantity of products that are currently in an open customer order that has not been shipped yet. In other terms, these products are physically in your storage but are not available for sale anymore. You cannot change directly the reserved stock. The reserved stock only depends on customer orders.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment] 2018-09-12 16:25
The thing is that I don't have any undelivered items and no open carts.

**Comment by khouloudbelguith** [comment] 2018-09-13 14:08
Hi @peranderssjostrom,

From the BO, you cannot change directly the reserved stock.
But you can access the ps_stock_available table & try to change it directly.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment] 2018-09-13 15:45
I'm editing in the table stock_available but see no effect. reserved_quantity seems not to be the right field.

**Comment by khouloudbelguith** [comment] 2018-09-13 16:19
Hi @peranderssjostrom,

In the ps_stock_available table the physical_quantity = quantity + reserved_quantity
But the reserved_quantity represents the quantity of products that are currently in an open customer order => you need to update the "product_quatity" column in the "ps_order_detail" table.

Best regards, Khouloud

**Comment by peranderssjostrom** [comment] 2018-09-13 17:40
Do you have any hint what trigger this? I know the product but there are rather many lines and I don't know the pattern I should look for. It's one reserved item. I'll guess I should look for a certain combination in the lines.

**Comment by khouloudbelguith** [comment] 2018-09-14 07:38
Hi @peranderssjostrom,

It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.4.2
The solution is to add the missing columns to your database schema.
You can find the schema changes in the SQL by looking at this: https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/upgrade/sql
You can find the full schema for 1.7.4.2 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql

Best regards, Khouloud

**Comment by peranderssjostrom** [comment] 2018-09-14 16:14
It's correct that some things went wrong in the migration for instance that I got a couple of variants I don't had from the beginning. Is it possible to explain how the reserved amount is calculated? Which fields in which tables are involved?

**Comment by khouloudbelguith** [comment] 2018-09-14 16:19
Hi @peranderssjostrom,

You can find the full schema for 1.7.4.2 here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-18 09:27
Hi @peranderssjostrom,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2018-10-18 09:27 UTC
Labels: Can't reproduce, Stocks, 1.7.4.2

**Comment by peranderssjostrom** [comment] 2018-10-18 16:53
It seems that the table **PS_stock_available** and the field **reserved_quantity** is what I see in the listing but when I edit this field the original values are copied back when I do a refresh of the listing. I wonder where to edit? It's somewhere else I'll suppose.

**Comment by khouloudbelguith** [comment] 2018-10-18 16:56
Hi @peranderssjostrom,

You need to update the "product_quatity" column in the "ps_order_detail" table.
Thanks!

**Comment by peranderssjostrom** [comment] 2018-10-18 18:44
This was not the right place to edit I'm afraid. Something more is involved here.

**Comment by khouloudbelguith** [comment] 2018-10-19 11:00
Hi @peranderssjostrom,

Do you need to edit the `reserved` quantity of some products?
Thanks!

**Comment by peranderssjostrom** [comment] 2018-10-19 17:03
Yes, since all orders are delivered or canceled but I have still reserved parts. This happened at the migration. Something went wrong. It's not critical, only a bit irritating.

**Comment by khouloudbelguith** [comment] 2018-10-23 13:26
Hi @peranderssjostrom,

Despite our several trials, we could not reproduce your issue with the provided information.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
