### ISSUE TITLE
Products not correctly indexed for frontend search

### ISSUE THREAD

**Issue by damianobertuna** [PrestaShop/PrestaShop#22095] opened 2020-11-25 11:13 UTC
#### Describe the bug

If a product is created disabled and then you activate the product clicking in the right row of the products list, the product is not indexed by PrestaShop. While if you activate the product entering in the product edit page, it is correctly indexed by PrestaShop.

#### Expected behavior

Clicking on the "Active" link the product should be indexed.

#### Steps to Reproduce

1. Go to 'Catalog' -> 'Product'
2. Click on 'New product'
3. Save the product without activating it
4. Activate the product clicking on the correct icon in the products list
5. Going in the section 'Shop Parameters' -> 'Search' you will see the new product is not indexed

Video that shows the problem:
https://youtu.be/w3rdNw0EvOg

**Screenshots**

![prestashop_indexing_bug_1](https://user-images.githubusercontent.com/9989581/100219877-db4d6300-2f16-11eb-850f-d8e4550f9eab.png)
![prestashop_indexing_bug_2](https://user-images.githubusercontent.com/9989581/100219885-ddafbd00-2f16-11eb-990b-a8366a3ff974.png)
![prestashop_indexing_bug_3](https://user-images.githubusercontent.com/9989581/100219912-e6a08e80-2f16-11eb-9514-590869b3bc03.png)
![prestashop_indexing_bug_4](https://user-images.githubusercontent.com/9989581/100219922-e99b7f00-2f16-11eb-88c8-1a7d478a7ffb.png)
![prestashop_indexing_bug_5](https://user-images.githubusercontent.com/9989581/100219942-f029f680-2f16-11eb-8c21-61f228936748.png)
![prestashop_indexing_bug_6](https://user-images.githubusercontent.com/9989581/100219946-f3bd7d80-2f16-11eb-9050-efc50a74fdbe.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2020-11-25 11:23
Hello @damianobertuna 

We are aware of this issue, it is already fixed in the last patch PS1.7.7.0 rc1. 
This issue is a duplicate of #9663. 
To apply the PR that fixe the problem, please subscribe to the issue mentioned above.

Thanks!

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-25 11:23 UTC
Labels: Duplicate

**Comment by hibatallahAouadni** [comment] 2020-11-25 11:33
Duplicate of #9663
