### ISSUE TITLE
ps_featuredproducts makes my 1.7.5 crash

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#11843] opened 2018-12-19 11:12 UTC
Just upgraded my 1.7.4.4 to 1.7.5 using 1-click upgrade : the module Featured product makes the shop crash (all ok when it's desactivated)

Error message in debug mode : 
FatalThrowableError
Access to undeclared static property: Product::$producPropertiesCache
in Product.php line 352

at Product::getProductProperties(blabla) in Product.php line 4924

at ProductCore::getProductsProperties(blabla) in Category.php line 1021

at CategoryCore->getProducts(1, 1, 8, 'position', 'ASC', false)in CategoryProductSearchProvider.php line 88

at CategoryProductSearchProvider->getProductsOrCount(object(ProductSearchContext), object(ProductSearchQuery), 'products')in CategoryProductSearchProvider.php line 105

at CategoryProductSearchProvider->runQuery(object(ProductSearchContext), object(ProductSearchQuery))in ps_featuredproducts.php line 299

at Ps_FeaturedProducts->getProducts()in ps_featuredproducts.php line 257

at Ps_FeaturedProducts->getWidgetVariables('displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart)))in ps_featuredproducts.php line 243

at Ps_FeaturedProducts->renderWidget('displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 971

at HookCore::coreRenderWidget(object(Ps_FeaturedProducts), 'displayHome', array('cookie' => object(Cookie), 'cart' => object(Cart)))in Hook.php line 923

at HookCore::exec('displayHome')in IndexController.php line 39

at IndexControllerCore->initContent()in Controller.php line 281

at ControllerCore->run()in Dispatcher.php line 509

at DispatcherCore->dispatch()in index.php line 28

Thanks for your help !

**Comment by khouloudbelguith** [comment] 2018-12-19 11:22
Hi @elmanu13,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0 after upgrade from 1.7.4.4 with the 1-click upgrade v4.5.1.
The FO is ok & the list of popular products are well displayed in the central column of my homepage.
Could you please try to uninstall this module, remove the ps_featuredproducts folder from your Project_Folder/modules/ps_featuredproducts, try to clear cache manually by deleting all the folder into var/cache (prod & dev) & install the ps_featuredproducts again.
Thanks to check & feedback.

**Comment by elmanu13** [comment] 2018-12-19 11:29
Hey, thanks for this fast answer.

I did all the operation you listed before sending my report. Did it again, and still have the problem with same error messages.

I will ask my dev if he did modify some core files that could cause the problem and get back to you soon.

Thanks again !

**Comment by khouloudbelguith** [comment] 2018-12-19 11:30
@elmanu13, thanks!
Waiting for your feedback.

**Comment by elmanu13** [comment] 2018-12-19 12:13
Hi again,

Problem fixed, there was an overide on the products.php that caused the problem.

You can close the issue, thanks again for your reactivity !

Manuel

**Comment by khouloudbelguith** [comment] 2018-12-19 13:42
@elmanu13, you are welcome.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-19 13:42 UTC
Labels: Bug, FO, No change required, 1.7.5.0
