### ISSUE TITLE
Duplicate order in validateOrder

### ISSUE THREAD

**Issue by falehenrique** [PrestaShop/PrestaShop#11487] opened 2018-11-23 20:22 UTC
Hi, I am plugin development for Prestashop 1.6 and 1.7 and I have the same error with duplicate notification orders.
The error does happen when the payment module plugin receive the same notification two times in the same time, so both call execute the function **validateOrder** and because that the order are duplicated.

I saw this problem many forum, this error will be fixed? 

My source code:

```
if (!$cart->orderExists()) {
     $this->validateOrder(
        $cart->id,
        $payment_status,
        $total,
        $displayName,
        null,
        array(),
        (int)$cart->id_currency,
        false,
        $cart->secure_key
}
```

**Additionnal information**
PrestaShop version: 1.6 and 1.7
PHP version: 7.0

Thank you.

**Comment by khouloudbelguith** [comment] 2018-11-26 14:28
Hi @falehenrique,

I did not manage to reproduce the issue with PS1.6.1.23 & the PayPal module v3.11.6.
I created at the same time two orders with different customers, it is ok, I received two orders with different Ids & different reference.
![image](https://user-images.githubusercontent.com/16067358/49020063-dde21a00-f18f-11e8-9722-99ee4115ed14.png)
Also, with PS1.7.4.4, I did not manage to reproduce the issue, in the PS 1.7.5.0 we fixed an issue of double click on Payment button may be related https://github.com/PrestaShop/PrestaShop/pull/9373
Thanks to check & feedback.

**Comment by falehenrique** [comment] 2018-12-03 17:35
Hi, the problem is when the two notification came with the same payment_id. In your example the cart_id is different.

**Comment by khouloudbelguith** [comment] 2018-12-04 08:33
Hi @falehenrique,

Could you please provide me your custom module to test with it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-04 16:58
Hi @falehenrique,

Any news about your issue?
I did not receive any mail from your side.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-08 17:04
Duplicate of #12073

**Closed as completed by khouloudbelguith** 2019-01-08 17:04 UTC
Labels: Duplicate, Order, Payment methods
