### ISSUE TITLE
PS 1.7.5 database initialization fails with 504 Gateway Timeout error

### ISSUE THREAD

**Issue by ivordurham** [PrestaShop/PrestaShop#12599] opened 2019-02-15 22:40 UTC
**Describe the bug**
PS 1.7.5 installation fails with a 504 Gateway Timeout on Fedora 29, PHP 7.2.14, Apache 2.4.38, MariaDB 10.3.11

**To Reproduce**
Download prestashop_1.7.5.0.zip and unpack in HOME/new_shop
Visit https://x.x.x/HOME/new_shop
Follow steps through local database setup (127.0.0.1) and test database connection successfully.
Click Next.
Long delay stuck at 12% followed by 504 Gateway Timeout error. 

**Screenshots**
PS Error & phpMyAdmin configuration block:

![ps_gateway_timeout](https://user-images.githubusercontent.com/6593376/52886766-3fc87500-312a-11e9-80bc-cc2441b5ffe6.PNG)
![lamp_configuration](https://user-images.githubusercontent.com/6593376/52886772-48b94680-312a-11e9-87e8-c998e316cc80.PNG)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2.14
MariaDB version: 10.3.11

A total of 227 tables were created in the database (ps_access through ps_zone_shop), but all tables appear to be empty, including ps_configuration so I'm not sure it is even getting as far as loading sample product information.

I had previously initialized PS 1.7.5 successfully under Fedora 28 with PHP 7.2 and the latest MariaDB version, but recently upgraded to the latest Fedora release. Then I needed to start my PrestaShop installation over again in preparation for converting/re-implementing a PrestaShop 1.4 installation. This time I could not complete the installation. None of my previous MariaDB, Apache or php.ini files have been modified since before the upgrade from Fedora 28 to Fedora 29.

**Comment by ivordurham** [comment] 2019-02-16 23:29
My default Apache installation apparently uses the Fast CGI proxy. I have been able to evade the timeout issue by creating an Apache configuration file: /etc/httpd/conf.d/custom.conf which contains

```
<IfModule proxy_fcgi_module>
timeout 120
</IfModule>
```

This doubles the default timeout of 60s. I have not tried to narrow down how much extra time is actually needed.

However, anyone trying to install PrestaShop on a shared hosting package may not have the option of changing the timeout. It would be far better to evade this issue in the first place.

**Comment by khouloudbelguith** [comment] 2019-02-18 08:14
Hi @ivordurham,

Thanks for your report.
To install PrestaShop, we need to set memory_limit to "128M", it is required, you can follow this [link](https://www.prestashop.com/en/system-requirements).
Also, you can follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

About your issue, since it is fixed, can I close the issue?
Thanks!

**Comment by ivordurham** [comment] 2019-02-18 18:19
My installation meets all of the requires shown by phppsinfo.php.

 

The issue is the time that the installation takes. On my development system, the Fast CGI interface had a default execution time limit of 60 seconds although my PHP max_execution_time was 90 seconds. The Fast CGI timeout was the error reported. On a shared hosting package at, say, hostgator.com (where I managed multiple websites), it is possible to modify the php.ini file, but not the Apache/PHP interface timeout. So my concern is that the installation time may be exceeded for other users who are using shared hosting packages where they cannot increase the execution time limit of the web server/PHP interface.

 

Although I am able to engineer a workaround on my development system, others may not be able to do so. So the open issue, I think, is whether the installation is taking longer than expected and can that time be reduced so that installation on shared hosting packages is more likely to work. Until those questions have been answered, I’d recommend leaving the issue open, but at a low priority.

**Comment by khouloudbelguith** [comment] 2019-02-19 14:55
Hi @ivordurham,

Thanks for these clarifications.
I tried with nginx, I edited the file /etc/nginx/nginx.conf where I set `fastcgi_read_timeout 120;`
When I tried to install PS1751 for example, I have "504 Gateway Time-out"
![image](https://user-images.githubusercontent.com/16067358/53024071-a1584e80-345e-11e9-982e-ba3b1496a619.png)
But, if I edit the `fastcgi_read_timeout 120;` to `fastcgi_read_timeout 600;` => the shop is successfully installed
@marion what do you think?
Thanks!

**Comment by marionf** [comment] 2019-02-19 15:43
Let's ask to a dev @PrestaShop/prestashop-core-developers

**Comment by PierreRambaud** [comment] 2019-02-20 09:04
Yes, you need to change your `fastcgi_read_timeout` because this is specific to nginx.

**Comment by khouloudbelguith** [comment] 2019-02-21 09:46
In my case, yes I can confirm this when I use `fastcgi_read_timeout 600;` => the shop is successfully installed
Thanks!

**Closed as completed** 2019-02-21 09:51 UTC
Labels: Bug, Trivial, IN, No change required, 1.7.5.0

**Comment by ivordurham** [comment] 2019-02-21 15:43
Note: If a user tries to install on a **shared** hosting package, they will not have the option of changing the Fast CGI interface timeout because that will be set by the hosting company. I have to believe that the majority of installations will be on the least expensive hosting packages, which will be shared packages, so closing this because the minority of users can adjust the timeout seems like a mistake.

**Comment by jennyfromipasspay** [comment] 2019-09-04 05:56
i just use prestashop today, i meet the same issue, my environment is :

·MAMP Pro use nginx

·PHP 7.2.7

·MYSQL 5.7

i try to set nginx fastcgi_read_timeout to 1000;

like this:

fastcgi_connect_timeout     75;
fastcgi_read_timeout           1000;
fastcgi_send_timeout         1000;

![image](https://user-images.githubusercontent.com/46195579/64229187-b3da3700-cf1b-11e9-92f1-bd022a2a4988.png)

then it works！
