### ISSUE TITLE
Exchange Rate and Cronjobs Module Under 1.7.6.4

### ISSUE THREAD

**Issue by burakgit** [PrestaShop/PrestaShop#19055] opened 2020-05-10 12:46 UTC
#### Describe the bug

There is no cronjobs  module under 1.7.6.4

#### Expected behavior
But will you please look at localization -> currency exchange rates ?

#### Steps to Reproduce

it says that you need to enable cronjobs for live exchange rates.. where is cronjobs ? i couldnt find. So i dont know what it is ? Bug or not. 

#### Additional information

* PrestaShop version: : 1.7.6.4

**Comment by atomiix** [comment] 2020-05-11 11:31
Hi @burakgit 

Thanks for your feedbacks. Cronjobs are usually configurable on your server either by manually configuring them through CLI on a dedicated server or through your hosting provider interface (cpanel for instance).

I'll close this issue as it's not a bug.

**Closed as completed by atomiix** 2020-05-11 11:31 UTC
Labels: No change required

**Comment by idnovate** [comment] 2020-10-02 10:53
@atomiix 

The problem is that the only way to get the currency rates URL is by installing cronjobs module (https://github.com/PrestaShopCorp/cronjobs):

![image](https://user-images.githubusercontent.com/15104724/94915992-1b134380-04ae-11eb-92ba-875a67a1d1f4.png)

Once installed:

![image](https://user-images.githubusercontent.com/15104724/94916009-25354200-04ae-11eb-9dac-74360a0bfdcc.png)

![image](https://user-images.githubusercontent.com/15104724/94916053-3ed68980-04ae-11eb-9914-20cda49940a0.png)


Would it be possible to display the URL without installing cronjobs module?
