### ISSUE TITLE
Bulk action don't work inside States

### ISSUE THREAD

**Issue by protoxide** [PrestaShop/PrestaShop#15652] opened 2019-09-23 10:51 UTC
**Hi, when you are in backoffice isn't possible to change the bulk option (that work perfectly in Country section, sister page..) after selected states you want to change , always continue to ask same page, and don't permite to select any zone to move. 

**To Reproduce**
Hi, when you are in backoffice, you go to international>localization>states
select states you want to change the zone
2. Click on button assign new zone
3. On next page you have to go down and prestashop don't show the button to click to give new zone , but show same button.. (same thing work perfectly in COUNTRY page)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: N/A
Please let me know Tiziano

**Comment by khouloudbelguith** [comment] 2019-09-23 10:55
Hi @protoxide,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9971
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-23 10:55
Duplicate of #9971

**Closed as completed by khouloudbelguith** 2019-09-23 10:55 UTC
Labels: Duplicate, States
