### ISSUE TITLE
Faceted search does not show product when sorting by price.

### ISSUE THREAD

**Issue by shnslmz** [PrestaShop/PrestaShop#14144] opened 2019-06-10 14:46 UTC
Hello,

Faceted search module version is (updated) v3.0.3. 
Prestashop: 1.7.5.1
Theme is default.

In a category page, when we sort the products by name, there is no problem.
But, when we sort the products by price, (Price, low to high or Price, high to low), just a few products are shown. Products count are correct but pagination and also in the current page, there are just a few products. In next page, there is no any shown products.

![bug1](https://user-images.githubusercontent.com/13356931/59203351-0f0fbe00-8ba7-11e9-8f0b-09027dcb7b08.png)

Also, on the left sidebar, price (slider) range is not correct. For example: In that category, the highest product price is 60 but, price range max range is 50 on the price slider.

![bug2](https://user-images.githubusercontent.com/13356931/59203415-3797b800-8ba7-11e9-9f9c-cd93042df443.jpg)

As you can imagine, when we disable the module, sorting works correctly.

**Comment by khouloudbelguith** [comment] 2019-06-10 15:10
Hi @shnslmz,

Thanks to navigate to your BO => Module manager page => ps_facetedsearch configure page click on the button "Rebuild entire price index" & "clear cache".

Thanks to check & feedback.

**Comment by rdy4ever** [comment] 2019-06-10 15:49
Hi @khouloudbelguith I beleive this is the same issue as #14140

**Comment by khouloudbelguith** [comment] 2019-06-10 15:50
@shnslmz, yes, I think so.
But I need to confirm that with the author before closing this issue as a duplicate.

Thanks!

**Comment by shnslmz** [comment] 2019-06-11 11:28
Hi @khouloudbelguith ,
Thanks for your answer but it did not work.

**Comment by rdy4ever** [comment] 2019-06-11 11:40
> Hi @khouloudbelguith ,
> Thanks for your answer but it did not work.

Are your products set to **Tax rule: No tax**? Then, you have the same issue as #14140

**Comment by khouloudbelguith** [comment] 2019-06-11 11:45
@shnslmz, thanks to check if your active products have no tax as a tax rule or not.

Thanks!

**Comment by shnslmz** [comment] 2019-06-11 11:46
> 
> 
> > Hi @khouloudbelguith ,
> > Thanks for your answer but it did not work.
> 
> Are your products set to **Tax rule: No tax**? Then, you have the same issue as #14140


> 
> 
> @shnslmz, thanks to check if your active products have no tax as a tax rule or not.
> 
> Thanks!

Just some of them are set to no tax.

**Comment by khouloudbelguith** [comment] 2019-06-11 11:58
@shnslmz, yes, it is the same issue reported here: #14140.
> just a few products are shown

In your case, only products are displayed in which they have tax rules not set to no tax.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-11 11:59
Duplicate of #14140

**Closed as completed by khouloudbelguith** 2019-06-11 11:58 UTC
Labels: Bug, FO, Duplicate, Faceted search, 1.7.5.1
