### ISSUE TITLE
Wholesale price forced to zero for product number 1

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#30780] opened 2023-01-09 18:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

First product created with all parameters, when I come back on it the wholesale price is set to zero.
Change it and save it, no change, even in the database (table ps_product_shop)
Change it directly on the database, open it : zero displayed 
Save it : database changed to zero.

It happens only to the product ID 1, not the others (even if a lot of products has been reset to zero but I cannot reproduce it now)
<img width="1256" alt="Capture d’écran 2023-01-09 à 19 49 54" src="https://user-images.githubusercontent.com/32092528/211385021-6d23709f-da89-447a-a412-fd9b335a3694.png">

### Expected behavior

price should be recorded

### Steps to reproduce

go to Catalog, products : open product ID1
Go to price, set a wholesale price and save
Go back to catalog, open product : wholesale price is set to zero

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by paulnoelcholot** [comment] 2023-01-10 10:49
Hello @elmanu13 ,

Despite our efforts, we were not able to reproduce your issue with the provided information. 

Could you specify the step to reproduce a bit more?

https://watch.screencastify.com/v/fuxhcJjkVBiDLDFnesU8

Thank you

**Comment by elmanu13** [comment] 2023-01-10 12:01
Hello @paulnoelcholot 

Here it is : https://watch.screencastify.com/v/Yboi9Q3uA0KJLCqqCzy8

If I go directly to the database and force the price, as soon as I edit the product id1 and save, the price is set back to zero even in the database. Super strange.

**Comment by kpodemski** [comment] 2023-01-10 12:36
@elmanu13 it seems that some third-party solution may break this mechanism 🤔

**Comment by paulnoelcholot** [comment] 2023-01-10 14:54
@elmanu13,

I have tried several types of configuration but I cannot reproduce the problem. I'll let another tester investigate the problem.

**Comment by elmanu13** [comment] 2023-01-10 15:36
> @elmanu13 it seems that some third-party solution may break this mechanism 🤔

Looks like, yes. I use some modules, but all are officials from addons.
Where can I look (logs or whatever) to identify the guilty ?

**Comment by HanaRebaiQA** [comment] 2023-01-11 09:28
Hello @elmanu13 

I tried to reproduce your issue with PS1788 and php 7.4, but i was unable to reproduce it. 

https://user-images.githubusercontent.com/92912932/211768915-19e9e838-65b7-485d-9841-e4e530c192c2.mp4


Closing this issue as it's not a Core bug.
Otherwise, if you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank You!

**Closed as completed by HanaRebaiQA** 2023-01-11 09:28 UTC
Labels: Bug, BO, Invalid, 1.7.8.8

**Comment by elmanu13** [comment] 2023-01-12 20:18
Hello again ! For your information, I have found the guilty !
When Cache (**CacheApc**) is enabled, I have the problem.
Cache disabled (I don't know why but I have to do it 2 times before it's really disabled) : no problem
Cache MemCached enabled : no problem
