### ISSUE TITLE
Product names are wrong in admin/products

### ISSUE THREAD

**Issue by glegarand** [PrestaShop/PrestaShop#20458] opened 2020-08-04 15:54 UTC
Hello,

I set up my local Prestashop 1.7.6.7 installation with Japanese (default) and English languages. Installation was in French and French language was eventually disabled.

Product names display is wrong in admin :
![image](https://user-images.githubusercontent.com/5107273/89315631-601c2480-d67b-11ea-9040-a7c9845a23e9.png)

However, the display is right once you enter a product :
![image](https://user-images.githubusercontent.com/5107273/89315760-86da5b00-d67b-11ea-8b12-a566434a143f.png)

I also have issues with combinations, but I need to do some more tests.

**Comment by khouloudbelguith** [comment] 2020-08-05 07:52
Hi @glegarand,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19777
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-05 07:52
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19777

**Closed as completed by khouloudbelguith** 2020-08-05 07:52 UTC
Labels: Duplicate
