### ISSUE TITLE
1.7.6. subcategory not select when creating a new multistore

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15221] opened 2019-08-22 14:03 UTC
After creating a new multistore and copying all details from the main store, I noticed that the subcategories are not copy or selected once ready.  , I created a second store and same story. 

Just to make sure it wasn't a one time "error"  , I created a second store and same story.
<img width="927" alt="Screenshot 2019-08-22 at 15 01 37" src="https://user-images.githubusercontent.com/46492443/63521217-f0566d80-c4ed-11e9-9ae9-c5467ea7a340.png">

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-22 14:16
Hi @01park,

It is an issue with the Association categories when adding a new shop.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9701
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-08-22 14:16
Duplicate of #9701

**Closed as completed by khouloudbelguith** 2019-08-22 14:16 UTC
Labels: Duplicate

**Comment by 01park** [comment] 2019-08-22 14:22
@khouloudbelguith 

Yes this is the same issue. 

Still no solution after 12 months?

**Comment by khouloudbelguith** [comment] 2019-08-22 14:25
@01park, 
Sorry not yet.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by 01park** [comment] 2019-11-09 13:05
Hi,

Can you maybe update the labels for this issue. That it effects also later Prestashop versions. I think this might be the reason the problem is not resolved yet.

**Comment by khouloudbelguith** [comment] 2019-11-11 11:13
Hi @01park,

Please follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/9701
This issue is closed as a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9701

Thanks!
