### ISSUE TITLE
WebService is broken on php 7.2 with display_error=on

### ISSUE THREAD

**Issue by AJenbo** [PrestaShop/PrestaShop#11227] opened 2018-11-01 19:12 UTC
**Describe the bug**
WebService is broken recent versions with the API simply responding with an error message for all endpoints.

**To Reproduce**
1. Set up prestashop 1.7.4.3 on PHP 7.2.11 and make sure that display_error is on.
2. Enable WebService and generate a token
3. Go to /webservice/dispatcher.php and enter the token as you username (no password)
4. You should now see the following error message:
`[PHP Warning #2] count(): Parameter must be an array or an object that implements Countable (/home/redacted/public_html/classes/webservice/WebserviceRequest.php, line 800)`
HTTP status is 500.

**Screenshots**
![billede](https://user-images.githubusercontent.com/204594/47873706-35e86380-de12-11e8-9c8b-072d542d0aa4.png)

**Additionnal information**
PrestaShop version: 1.7.3.4 (oldest known version with the issue) - 1.7.4.3
PHP version: 7.2.11

At the moment we are seeing hundreds of customers unable to use our product because of this issue, many of them are unable to turn display_error off either because of technical known how, hosting solution or needing it for debugging other issues.

**Comment by AJenbo** [comment] 2018-11-01 19:20
It appears that this was fixed 3 months ago (https://github.com/PrestaShop/PrestaShop/commit/8662b3a50eae1ca7e6f6de02b419f123ba2ceee8) in 1.7.5.x but the issue is applicable to all other versions (1.6.1.x, 1.7.0.x-1.7.4.x), please cherry pick this fix for the 1.7.4.x branch as this version is reported as being php 7.2 compatible and 1.7.5.x is not released yet.

**Comment by khouloudbelguith** [comment] 2018-11-02 08:17
Hi @AJenbo,

The branch 1.7.4.x receives only security patches, it would like to avoid to merge anything else so as not to end up with surprise regressions.
The issue is fixed in the 1.7.5.0, it wasn't necessary to create a new one.
So, this one can be closed.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-02 08:17
Duplicate of #9439

**Closed as completed by khouloudbelguith** 2018-11-02 08:17 UTC
Labels: Duplicate
