### ISSUE TITLE
Duplicate name for Carrier and Payement -> preferences

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#21897] opened 2020-11-12 22:49 UTC
#### Describe the bug

Hi, if you give 2 same names for carrier, then only of both is available in Payment->preferences
#### Expected behavior

Here they have 2 different names
<img width="2274" alt="Capture d’écran 2020-11-12 à 23 44 19" src="https://user-images.githubusercontent.com/43704805/99005465-26439f80-2541-11eb-9134-8469784a14ba.png">

Then you can see both of them in Payement->preferences
<img width="1346" alt="Capture d’écran 2020-11-12 à 23 44 35" src="https://user-images.githubusercontent.com/43704805/99005551-4a9f7c00-2541-11eb-85cf-8cae91ba4eb2.png">

But if you give them same names :

<img width="2307" alt="Capture d’écran 2020-11-12 à 23 47 31" src="https://user-images.githubusercontent.com/43704805/99005665-7a4e8400-2541-11eb-90db-dd1f442f0ca0.png">

Then only one is displayed (and activated) :
<img width="1302" alt="Capture d’écran 2020-11-12 à 23 44 27" src="https://user-images.githubusercontent.com/43704805/99005696-89353680-2541-11eb-9bc0-52252fbb0771.png">

I probably lost tens of orders because of these... My customers had a message "No paiement method available"... 

-> Prestasop 1.7.6.8 and php 7.2

**Comment by hibatallahAouadni** [comment] 2020-11-13 07:53
Hello @passio777x 

We are aware of this issue, it is already fixed in PS1.7.7.0. See screenshot below:

![image](https://user-images.githubusercontent.com/23308427/99042781-a1cb3e00-258d-11eb-84da-fd210e32ebbf.png)

This issue is a duplicate of #16094. 
Here's the PR that fixed the problem #12379

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-13 07:53
Duplicate of #16094

**Closed as completed by hibatallahAouadni** 2020-11-13 07:53 UTC
Labels: Duplicate
