### ISSUE TITLE
Quantity in combination on Small Screen Phones

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#29456] opened 2022-08-26 14:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Admin Back Office -> Catalog -> Product (with combination) -> quantity looks like empty but there is not enough space to show number (css min-width is needed and paddings are to big)

i suggest to add this BUT ONLY ON SMALL SCREEN

.form-control {
    padding: 0.5rem 0.5rem;
    text-align: center;
    min-width: 3rem;
}

### Steps to reproduce

1. Admin Back OFfice Catalog
2. Product with combination

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment] 2022-08-26 15:45
Hello @slupostrupek 

This issue is a duplicate of #27589. And as you can see we can't reproduce the issue.
It seems related to your theme or some overrides.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-26 15:45
Duplicate of #27589

**Closed as completed by hibatallahAouadni** 2022-08-26 15:45 UTC
Labels: Bug, Duplicate, Invalid

**Comment by slupostrupek** [comment] 2022-08-27 08:23
#27589 is front office
this issues is about ADMIN BACK OFFICE

**Comment by slupostrupek** [comment] 2022-08-27 08:23
> Duplicate of #27589

Nope, this is front office i am talking about admin back office

**Comment by slupostrupek** [comment] 2022-08-27 17:00
i've created this issue again here: #29459
