### ISSUE TITLE
image file gets deleted when updating custom objects

### ISSUE THREAD

**Issue by ioweb-gr** [PrestaShop/PrestaShop#18111] opened 2020-03-12 09:03 UTC
#### Describe the bug

Try to add an image field to a custom object and create a new instance of the object from the admin panel by uploading an image file to the file input field. The image gets uploaded correctly. 

Afterwards try to update the object without reuploading the image and the image is lost

Updating by reupoading the image works. 

The AdminController is stripping the file during `copyfrompost()` effectively setting the original file input field value to "" because it's not defined in $_POST but for a file input field it should probably check the original value as well unless otherwise dictated. 

This used to work in prestashop 1.6.0.8 without removing the image but not in 1.7.5.2 but there doesn't seem to be any documentation regarding the change that's affecting this behaviour. 

#### Expected behavior

The image stays the same as before when editing the object and clicking save / save and stay.

#### Steps to Reproduce

- Create a module that adds a new object model with an image. In the object class define the field for the database. 
```
        public static $definition = array(
                'logo' => [
                    'type' => self::TYPE_STRING,
                    'lang' => false,
                    'validate' => null,
                    'size' => 255,
                ],
```

- In admin controller define the form

```
$this->fields_form = array(
                array(
                    'type' => 'file',
                    'label' => $this->l('logo'),
                    'name' => 'logo',
                    'display_image' => true,
                    'image' => $image_url ? $image_url : false,
                    'size' => $image_size,
                    'hint' => $this->l('Storefront picture.'),
                    'delete' => true, //false or true doesn't change the behaviour
                    'required' => false,
                ),
```

- Create the function that handles the image upload. 

- After that go to admin and create a new object using the form and add an image to it. Everything works as expected and the image is uploaded. 

- Go to edit the object
- Click on Save

The image gets removed. 

**Screenshots**

When entering edit page

![image](https://user-images.githubusercontent.com/20220341/76504400-51c13800-6450-11ea-9a13-9d3bbc8905a9.png)

After clicking on save without touching anything

![image](https://user-images.githubusercontent.com/20220341/76504504-87662100-6450-11ea-820e-5358d0855eab.png)

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.28

A small update, I was able to work around the issue by updating `$_POST['<fieldName>']` variable with the original value in the `childValidation` function if the file the user inputs is empty in `$_FILES['<fieldname>']['name']`, but it would be great if prestashop provided directions as to the recommended way to add a file input field in an object.

**Comment by khouloudbelguith** [comment] 2020-03-12 11:56
Hi @ioweb-gr,

Could you please provide me a demo module to test it.
I tried with this script
```
<?php

require dirname(__FILE__) . '/config/config.inc.php';
$gender = new Gender();
$gender->id = 4;

$gender->name = array((int)Configuration::get('PS_LANG_DEFAULT') => 'Art');
$gender->type =1;
$force_ids = true;
//this will force ObjectModel to use your ID
$gender->force_id = (bool)$force_ids;
$gender->save();
echo "Done, gender well updated";
```
To update the Gender object, but it is OK
![image](https://user-images.githubusercontent.com/16067358/76519235-e764c380-6460-11ea-9055-28b70168e151.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-12 11:57
Maybe related to this: https://github.com/PrestaShop/PrestaShop/issues/17449

**Comment by ioweb-gr** [comment] 2020-03-12 13:51
I will try to pack the module and upload it somewhere without the sensitive data in it, sure. I'll also remove the patch to retain the image so you can see the whole process.

**Comment by khouloudbelguith** [comment] 2020-03-12 13:54
@ioweb-gr, thanks!
Waiting for your feedback.

**Comment by ioweb-gr** [comment] 2020-03-12 15:48
Here is a package of what I have installed in the system. Let me know if you face any issues installing it because there might be files missing while removing the sensitive data and I'll try to send them too 

[ioweb_slocator.tar.gz](https://github.com/PrestaShop/PrestaShop/files/4325112/ioweb_slocator.tar.gz)

**Comment by khouloudbelguith** [comment] 2020-03-12 16:59
@ioweb-gr, thanks, it is well installed.
But I cannot configure this module.
![image](https://user-images.githubusercontent.com/16067358/76546114-3a537080-648b-11ea-8c56-9b89e61554c2.png)

Thanks!

**Comment by ioweb-gr** [comment] 2020-03-12 17:11
Ah there's no configuration. I think the admin tabs are not installed properly. As we had migrated our eshop from 1.6 to 1.7 there was no need to upgrade that part of the code on the module so I think it might be using invalid functions and not properly registering the tabs.

You should be seeing on the left side a panel

![image](https://user-images.githubusercontent.com/20220341/76546669-9373d200-6494-11ea-9cfc-8cc5f350384d.png)

I see these tabs in my database in table `ps_tab`

|id_tab|id_parent|position|module|class_name|active|hide_host_mode|icon|
|--- |--- |--- |--- |--- |--- |--- |--- |
|230|0|12|ioweb_slocator|IowebStoreLocator|1|0||
|231|230|1|ioweb_slocator|IowebStoreLocatorGroup|1|0||
|232|230|2|ioweb_slocator|IowebStoreLocatorStore|1|0||


Perhaps a query like this would help

```
INSERT INTO ps_tab (id_tab, id_parent, position, module, class_name, active, hide_host_mode, icon) VALUES (230, 0, 12, 'ioweb_slocator', 'IowebStoreLocator', 1, 0, '');
INSERT INTO ps_tab (id_tab, id_parent, position, module, class_name, active, hide_host_mode, icon) VALUES (231, 230, 1, 'ioweb_slocator', 'IowebStoreLocatorGroup', 1, 0, '');
INSERT INTO ps_tab (id_tab, id_parent, position, module, class_name, active, hide_host_mode, icon) VALUES (232, 230, 2, 'ioweb_slocator', 'IowebStoreLocatorStore', 1, 0, '');
```

**Comment by khouloudbelguith** [comment] 2020-03-12 17:16
@ioweb-gr, thanks, I will check and feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-17 17:07
@ioweb-gr, I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
[Store • 1764.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4344746/Store.1764.webm.zip)
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-04-16 07:26
Hi @ioweb-gr,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-16 07:26 UTC
Labels: Bug, BO, Modules, No change required, 1.7.5.2

**Comment by ioweb-gr** [comment] 2020-04-16 09:55
It seems if the same module didn't reproduce it, then the core issue must be fixed by some other pull request so I guess it's safe to close it.
