### ISSUE TITLE
padlock error only in one link

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23005] opened 2021-01-27 01:23 UTC
#### Describe the bug

I have no padlock on this route

http://MYWEBSITE/index.php?controller=cart

**Screenshots**

A form with the action of "http://MYWEBSITE/index.php?controller=cart" exists in the source code of the tested page.
This form needs to be updated to use "https://MYWEBSITE/index.php?controller=cart" or another secure URL for your padlock to return.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-27 09:35
Hello @alfonsolr09 

Could you please explain the problem in more detail, cause I tried to reproduce your issue with PS1.7.7.0 and the link always secure when I go to the cart page, see the attached screen record below:

https://drive.google.com/file/d/1OmKtBtZsWrzE-Tr184tX7T6P27odVpiJ/view

Please check and feedback.
Thanks!

**Comment by matks** [comment] 2021-01-27 09:39
@alfonsolr09 would it be possible to have a screenshot/excerpt of the source code, so we can find its location 😉  ?

**Comment by alfonsolr09** [comment] 2021-01-27 09:44
The page link is this, when you change the display order of products.

https://lamagrande.com/2-productos

When you displayed by name A-Z or by price, disappear the padlock. The rest of the website have it

**Comment by matks** [comment] 2021-01-27 10:16
I can see it.

1. Go on https://lamagrande.com/2-productos?order=product.sales.desc => padlock is on
2. Sort by "Nombre, Z a A" => new URL is https://lamagrande.com/2-productos?order=product.name.desc, padlock is off

Error message in console
```
Mixed Content: The page at 'https://lamagrande.com/2-productos?order=product.name.desc' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://www.lamagrande.com/index.php?controller=cart'. This endpoint should be made available over a secure connection.
```

The http endpoint appears here in this part
![Capture d’écran 2021-01-27 à 11 15 13](https://user-images.githubusercontent.com/3830050/105976899-05dfa780-6091-11eb-8591-8a6dfb444b0e.png)

```

<div class="product-detail" itemprop="description"><div id="short_description_block">
--
   <div id="short_description_content" class="rte align_justify">
   <p style="text-align:justify;">El ventilador de techo Habitex modelo VT...</p>
   <form id="buy_block" action="http://www.lamagrande.com/index.php?controller=cart" method="post">
   <div class="product_attributes"> </div>
   </form></div>
   </div></div>
```

**Comment by hibatallahAouadni** [comment] 2021-01-27 10:23
Hello @alfonsolr09 

I didn't manage to reproduce the issue even when I followed your steps:

1. FO> All products
2. Sort by: Name, A to Z / Price
3. The URL still secure

https://drive.google.com/file/d/1SvaspdOx9ybFJclTM1zZcIcbpTRG4XAN/view

As @matks metioned above the problem is with your shop not PrestaShop Core.
I'm really sorry, but I have to close this issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: thanks @matks for your quick replies :rocket: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-27 10:23 UTC
Labels: Bug, FO, Can't reproduce, Shop parameters, General, SEO & URLs, 1.7.7.0, 1.7.6.4

**Comment by matks** [comment] 2021-01-27 10:28
@alfonsolr09 it seems your shop uses "BigCart" theme. As said by @hibatallahAouadni it seems to be an issue on the theme as Classic Theme behavior is correct.

You need to reach out to BigCart developer / sales team 😉

**Comment by alfonsolr09** [comment] 2021-01-27 14:47
@matks the problem is that I argued with the developer because the template had a lot of bugs and he didn't want to fix them.  so I do not have your help or support and I must fix it.  Any idea what the problem may be or the file path?
@hibatallahAouadni 

Thank you so much.

Pd: I don't know why the route is related with shopping cart...

**Comment by hibatallahAouadni** [comment] 2021-01-27 15:04
Hello @alfonsolr09

you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
You're always welcome :wink: 

Thanks!

**Comment by alfonsolr09** [comment] 2021-01-28 00:39
![image](https://user-images.githubusercontent.com/62474824/106072908-55fa5080-6109-11eb-9892-3204e565fe06.png)

it was simply a wrong link in the product description
Thanks @matks and @hibatallahAouadni

**Comment by hibatallahAouadni** [comment] 2021-01-28 10:31
@alfonsolr09 Glad to hear :tada: with pleasure :wink:
