### ISSUE TITLE
PS_WIREPAYMENT order validation fatal error

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#25783] opened 2021-09-03 11:06 UTC
Hello
The page /module/ps_wirepayment/validation show message  **Fatal error** on checkout-payment-step 

I enabled the debug mode and this message appear 
![image](https://user-images.githubusercontent.com/11594433/131995043-ab29220c-4afc-4758-86b5-f627ab373dfb.png)

So I made a reset to this 2 modules
Mail alerts v2.3.0 - par PrestaShop
Transfert bancaire v2.1.0 - par PrestaShop

I deleted the folders from /var/cache and still getting the error 

The error message on log apache is 

Error	500	POST /en/module/ps_wirepayment/validation HTTP/1.0

![image](https://user-images.githubusercontent.com/11594433/131995771-f099aad5-4b99-4872-acd4-401e051834a9.png)

Version de PrestaShop : 1.7.7.7
Version du logiciel serveur : Apache
Version de PHP : 7.2.34
Limite de mémoire : 80128M
Temps maximal d'exécution : 72000
Taille max. pour envoi de fichiers : 5G

Regards

**Comment by khouloudbelguith** [comment] 2021-09-03 11:18
Hi @go-sudo,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.7.7 using the module ps_emailalert v2.3.0 & the module bank transfer v2.1.0.
I attached a screen record https://drive.google.com/file/d/1w8Mr_552SBhEJXh4HimKjCiOAzE3V2g_/view?usp=sharing

Thanks to check and feedback.

**Comment by go-sudo** [comment] 2021-09-03 11:40
Hello

Last action i did is this

UPDATE ps_address_format SET 
format = 'firstname lastname\r\naddress1\r\naddress2\r\npostcode city\r\nCountry:name\r\nphone';

Regards

**Comment by khouloudbelguith** [comment] 2021-09-03 11:54
@go-sudo,

so, did you update your table manually via database or from the BO > International > Countries page?
![image](https://user-images.githubusercontent.com/16067358/132001229-c0996f4e-68d0-484b-9dce-1ed94f372a8a.png)

Thanks!

**Comment by go-sudo** [comment] 2021-09-03 11:56
Hello

From PHPMYADMIN

Regards

**Comment by khouloudbelguith** [comment] 2021-09-03 13:19
@go-sudo,

You need to restore your shop before this modification because this is risky.
You can update the address format of your country from the BO > International > Location > Countries page.
![image](https://user-images.githubusercontent.com/16067358/132011301-290dbc35-1660-42c6-8236-a7ec07ab51ce.png)

We use GitHub issues only to discuss bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](prestashop.slack.com/messages).

I close the issue, feel free to create a new issue when needed.

Thanks for your understanding!

**Closed as completed by khouloudbelguith** 2021-09-03 13:19 UTC
Labels: Bug, FO, Bankwire, Wire payment, No change required, Checkout
