### ISSUE TITLE
Problem to insert the email inside the address

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15492] opened 2019-09-10 18:44 UTC
Hi
try to add
Customer:email
to the address fields of Italy
in the front-office will be added a customer selection with no items inside at the top of the address form. In this case the email should not be shown in that form like on 1.6
the email should be present just in the emails

bye

**Screenshots**
![2](https://user-images.githubusercontent.com/653230/64640920-55292780-d40b-11e9-8761-5be0c5891212.png)
![11](https://user-images.githubusercontent.com/653230/64640921-55292780-d40b-11e9-9d58-b4c82031a8c1.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-09-11 07:26
Hi @maofree,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11166
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-11 07:26
Duplicate of #11166

**Closed as completed by khouloudbelguith** 2019-09-11 07:26 UTC
Labels: Duplicate
