### ISSUE TITLE
Best customers stats empty

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#23825] opened 2021-03-30 16:28 UTC
#### Describe the bug

The stats modules are installed. They all show the shop stats except for the best customers which remains empty.

#### Expected behavior

For the page Best customers stats to show the statictics.

#### Steps to Reproduce

1. Install the module Best customers stats
2. Go to Stats > Best customers
3. The page remains with the message empty. No stats

**Screenshots**

https://prnt.sc/1101hzc

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-03-30 17:42
Hello @ced--ced 

I didn't manage to reproduce your issue with PS1.7.5.1, PS1.7.6.7 and PS1.7.7.2, see the attached screenshots below:

### 1.7.5.1
![image](https://user-images.githubusercontent.com/23308427/113032250-ef88c180-918f-11eb-86e2-0370453d0ec9.png)

### 1.7.6.7
![image](https://user-images.githubusercontent.com/23308427/113032277-f6afcf80-918f-11eb-9aeb-fcc2bdc6b11c.png)

Please check and feedback.
Thanks!

**Comment by florine2623** [comment] 2021-04-16 09:28
Hello @ced--ced ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-04-16 09:28 UTC
Labels: Bug, BO, Stats, No change required, 1.7.5.1, Best customers
