### ISSUE TITLE
BO - Could not perform action update for module undefined

### ISSUE THREAD

**Issue by omnimetro** [PrestaShop/PrestaShop#32346] opened 2023-04-26 10:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when I try to update modules I have this error : Could not perform action update for module undefined

i have 41 modules to update. some are natives, other are free or paid
![Screenshot 2023-04-26 at 09-46-48 Gestionnaire de modules • PRENDPOURTOI COM](https://user-images.githubusercontent.com/131869839/234550467-77359702-1075-4857-b2e9-90b69a729102.png)

### Expected behavior

I expect all my modules been updated

### Steps to reproduce

1 Connect to  admin interface
2 Modules > Module Manager
3 click on update button of a module
4 see the error

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment] 2023-04-28 12:27
Hello @omnimetro ,

Can you update native modules ? 
Can you update marketplace modules ?

DO you have the same error for both cases ?

**Comment by omnimetro** [comment] 2023-04-28 13:52
Yes I can't update free, paix or native modules

Le ven. 28 avr. 2023, 12:27, florine2623 ***@***.***> a
écrit :

**Comment by florine2623** [comment] 2023-04-28 14:18
Hello @omnimetro ,

I can't reproduce your issue.

https://user-images.githubusercontent.com/16019289/235172997-7a6374bb-5418-4118-b3d0-2b9097d201bd.mov



Do you have any log error ? or any error in the console ?

Thanks!

**Comment by omnimetro** [comment] 2023-04-28 14:39
Le ven. 28 avr. 2023 à 14:18, florine2623 ***@***.***> a
écrit :

> Hello @omnimetro <https://github.com/omnimetro> ,
>
> I can't reproduce your issue.
> [image: Screenshot 2023-04-28 at 16 08 06]
> <https://user-images.githubusercontent.com/16019289/235172836-cb3288ad-80a5-4a4b-87ef-908b2ec4be97.png>
>
> Do you have any log error ? or any error in the console ?
>
> Thanks!
>
these are the differents errors screenshots

**Comment by joecoolio66** [comment] 2023-05-01 14:27
I had the same issue and it was related to mod_security settings on my host.  Check your requests in debug or use the browser's inspection tools to narrow down the issue.  Also check the admin error log on the server

**Comment by hibatallahAouadni** [comment] 2023-05-23 14:48
Hello @omnimetro 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-23 14:48 UTC
Labels: Bug, BO, Module manager, Invalid, Module, 1.7.8.7

**Comment by Dar-us-Salam** [comment] 2025-03-05 21:10
Hello, I have the same problem with all modules not updating. It keeps saying 'Could not perform action update for module undefined'. When I reset the module (for the ones I can reset), it updates the version to the latest one (which it was supposed to be upgraded to). I have 3 Prestashop installs with 1 fresh v8.2 and all of them have the same problem which makes me to believe it is a hosting issue but I don't know what it could be. I don't have mod_security as I am running Litespeed Server so I don't know what else it could be. Any help would be appreciated.

In debug mode, I got this in the log:

![Image](https://github.com/user-attachments/assets/d4c8ca53-fb44-4023-b5a5-3e21e07af6aa)

![Image](https://github.com/user-attachments/assets/f4e170c7-4a24-46f1-a73f-cc40b819d202)

BO Information page:

![Image](https://github.com/user-attachments/assets/23768703-8056-4225-b030-2c4511fd3e59)

Thanks
Omar Waheed
