### ISSUE TITLE
BO performance issue / error backoffice.js

### ISSUE THREAD

**Issue by Klixa-Web** [PrestaShop/PrestaShop#10211] opened 2018-08-30 13:34 UTC
I have big problems with performance of BO in Prestashop 1.7.4.2 above all with editing categories.
I get "error" from backoffice.js in the browserconsole and changes cannot be saved.

**Comment by khouloudbelguith** [comment] 2018-08-30 13:37
Hi @Klixa-Web,

Thanks for your report.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!
ps: We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Best regards, Khouloud

**Comment by Klixa-Web** [comment] 2018-08-30 13:50
Host: ftp.klixa.ch

Serverdaten Linux #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64
Version der Server-Software Apache/2.4.18 (Ubuntu)
PHP-Version 7.0.30-0ubuntu0.16.04.1
Speichergrenze 1024M
max_execution_time: 3000
Upload (max. Dateigröße) 512M
PrestaShop-Version 1.7.4.2
Shop-URL https://www.geburtstagskarte.ch/
Template: warehousechild

MySQL-Version 5.7.23-0ubuntu0.16.04.1
MySQL-Server localhost
MySQL-Name 3350BH_www_geburtstagskarte_ch
MySQL-Anwender 3350BH_www_geb
Tabellen-Präfix: ps_
MySQL-Engine InnoDB
MySQL-Treiber DbPDO

**Comment by khouloudbelguith** [comment] 2018-08-30 13:51
Hi @Klixa-Web,

Thanks for your feedback.
As I said, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Best regards, Khouloud

**Comment by Klixa-Web** [comment] 2018-08-30 14:57
[ch_geburtstagskarte_www_error.log](https://github.com/PrestaShop/PrestaShop/files/2336669/ch_geburtstagskarte_www_error.log)
[ch_geburtstagskarte_www_access.log](https://github.com/PrestaShop/PrestaShop/files/2336670/ch_geburtstagskarte_www_access.log)

**Comment by Klixa-Web** [comment] 2018-08-30 14:58
I've set debug mode on, but don't get any report. Please tell me how to get it.

**Comment by khouloudbelguith** [comment] 2018-08-30 15:03
Hi @Klixa-Web,

In the error_log file, you have this error: [client denied by server configuration].
It is a server configuration, thanks to check your host and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-28 14:07
Hi @Klixa-Web,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-28 14:07 UTC
Labels: Bug, BO, Performance, No change required, 1.7.4.2
