### ISSUE TITLE
personal_information.html.twig cannot be overridden without blocks

### ISSUE THREAD

**Issue by reidlightning** [PrestaShop/PrestaShop#22377] opened 2020-12-11 17:49 UTC
#### Is your feature request related to a problem?
When attempting to use a module to override the twig:
src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig

Symfony complains that the file to be overridden must contain {% block %} elements.
personal_information.html.twig doesn't have any {% block %} elements to override. 

#### Describe the solution you'd like
I'd like to add  {% block %} elements to override the src file to get the desired result

#### Additional context
We are running 1.7.6.2

**Comment by hibatallahAouadni** [comment] 2020-12-14 09:45
Hello @reidlaitinen 

Please next time **follow the template to submit a complete feature report**.
We create this template to make it easy for you and for us to handle the issue.

Thanks for the suggestion, the Developper Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers , is it convenient to add these blocks to this twig?

**Comment by PierreRambaud** [comment] 2020-12-14 14:55
Hi,
I didn't manage to reproduce the issue:
![image](https://user-images.githubusercontent.com/1462701/102096108-a13ff480-3e24-11eb-815b-7431a9804444.png)

Here's the content of my file:
```
<div>
  This is my personal_information.html.twig file
</div>
```


located in my modules  `myModule/views/PrestaShop/Admin/Sell/Customer/Blocks/View`

**Comment by hibatallahAouadni** [comment] 2021-02-22 20:52
Hello @reidlaitinen,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-22 20:52 UTC
Labels: Improvement, CO, No change required, 1.7.6.2, 1.7.7.0
