### ISSUE TITLE
New vat rules Europe?

### ISSUE THREAD

**Issue by tajriba** [PrestaShop/PrestaShop#23906] opened 2021-04-06 15:00 UTC
https://ec.europa.eu/taxation_customs/business/vat/modernising-vat-cross-border-ecommerce_en

Any idea how to arrange the new EU vat rules in pretashop?
will there be a module for this to see if you sell more than 10.000 in a specific country ?

**Comment by matks** [comment] 2021-04-06 15:19
Hi @tajriba I know the product team has carefully studied the question so I ping them

**Comment by tajriba** [comment] 2021-04-20 09:58
@matks thank you! we are curious about this.

**Comment by hibatallahAouadni** [comment] 2021-04-21 09:00
Hello @tajriba 

I'm really sorry but I have to close this issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, you can also ask in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Like @matks mentioned above, the PM has been notified and they will answer your questions either here (even when the issue is closed) or in Slack.

Thanks for your understanding :relaxed:

**Closed as completed by hibatallahAouadni** 2021-04-21 09:00 UTC
Labels: VAT, Tax rules, No change required

**Comment by tajriba** [comment] 2021-05-07 12:18
https://www.prestashop.com/en/blog/european-union-vat
