### ISSUE TITLE
ps_emailalerts missing product name

### ISSUE THREAD

**Issue by Massi-X** [PrestaShop/PrestaShop#22628] opened 2020-12-30 18:09 UTC
#### Describe the bug

When you register your email to be alerted when a product is available again, no name will be present in the mail itself.
This also affects admin email, but I had no time to create a pull request for that too yet.
Please see [https://github.com/PrestaShop/ps_emailalerts/pull/74](https://github.com/PrestaShop/ps_emailalerts/pull/74)

#### Expected behavior

The mail include the name of the product.

#### Steps to Reproduce

1. Install module ps_emailalerts and setup as you wish
2. Create a product or use an existing one, set the availability to 0
3. Register for notification in the frontend with an user account
4. Set the availability back to 1 (or anything else)
5. Wait for the email informing you of the availability of the product, the name will be empty (subject too).

**Side note: If you look at the linked pull request the product object is assigned in the line before, I can't understand why is not used anyway as I've done!**

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.x

**Comment by hibatallahAouadni** [comment] 2020-12-31 10:33
Hello @Massi-X 

I managed to reproduce your issue **`the name is empty`** with PS1.7.6.9 and ps_emailalerts v2.2.1 but the subject is not empty, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/103404843-511b9e80-4b55-11eb-8cb0-124ee06c55ef.png)

I’ll add this to the debug backlog so that it’s fixed.
Thanks for your PR :wink: 

Thank you

**Comment by Massi-X** [comment] 2020-12-31 11:10
Hi thank you 😊
Yes I was wrong the subject was OK
I will make a PR or update that one also for the admin mails in some hours

**Comment by hibatallahAouadni** [comment] 2020-12-31 13:31
@Massi-X I just changed the issue title :wink: 
Could you please update your PR :slightly_smiling_face:

**Comment by Massi-X** [comment] 2020-12-31 13:58
hi @hibatallahAouadni I like your idea, but this is really a different issue. I didn't get deep inside the code because (as you can see in the PR) changing `Product::getProductName` to `$product->name` simply works, but thinking about it there may be some problem with the core function `Product::getProductName` because it returns an empty string.
I will narrow down the problem in the next days. For clarity i attach a screenshot showing the issue.
![Issue](https://user-images.githubusercontent.com/7504132/103413131-871e4a00-4b78-11eb-9029-f1ccf85411d1.png)

**Comment by hibatallahAouadni** [comment] 2020-12-31 15:31
Hello @Massi-X 

I just check it with another language and with the modern theme email and yet I can not reproduced it:

![image](https://user-images.githubusercontent.com/23308427/103416131-8b049900-4b85-11eb-8304-a9ece52305c5.png)

Could you please provide more infos to reproduce the issue.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-21 07:47
Hello @Massi-X ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-21 07:47 UTC
Labels: Bug, CO, No change required, PR available, 1.7.7.0, 1.7.6.9, ps_emailalerts

**Comment by Massi-X** [comment] 2021-03-17 20:38
I'm sorry but I didn't have time to check it (nor I have now). If I can I will try to find the clue
