### ISSUE TITLE
Multistore edit order

### ISSUE THREAD

**Issue by NKoonen** [PrestaShop/PrestaShop#21446] opened 2020-10-14 13:58 UTC
#### Describe the bug

In multistore context (all shops) you can't delete a product from an order. You first need to select the specific store where the order is placed to be able to remove a product. Currently there is a 500 error in the console: Shop context types other than "single shop" are not supported.

#### Expected behavior

Either a message that says "Please select a single store" or even better you can delete an product from an order when in multistore context.

#### Steps to Reproduce

1. Go to and existing order from a multistore shop and have "All shops" active
2. Click on a product from that order and with the dropdown try to remove
3. Nothing happens
4. See error in the console

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-10-15 09:16
Hi @NKoonen ,
This is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9609
I'll close your issue, you can follow the progress directly on https://github.com/PrestaShop/PrestaShop/issues/9609
Thanks!

**Comment by florine2623** [comment] 2020-10-15 09:16
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9609

**Closed as completed by florine2623** 2020-10-15 09:16 UTC
Labels: Duplicate, Order, Multistore, No change required
