### ISSUE TITLE
Stock movement list not respect DB records 

### ISSUE THREAD

**Issue by janekx** [PrestaShop/PrestaShop#34378] opened 2023-10-24 17:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After update from 1.6.1.23 to 1.7.8.10 and 8.1.2 there is serius issue with stock movment list 

last two records says 
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/ae7b94c3-babf-4935-9b4f-5f6a9d875f24)

 but DB says more items to show 
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/4cccbe7d-8ee0-49c0-b1a6-a89e3b66a4a6)

Product shown in BO list says ID 12 shows product ID 12 picture, name and reference what is not true the stock ID should be 266 as is stated in DB, so seems the list instad query id_stock query id_product

show from 1.6.1.23
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/ee946f0a-3086-47de-8b45-157ea0312ece)

### Expected behavior

List should be same as DB 

### Steps to reproduce

Catalog - stocks - movments. Check no filter assigned.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2023-10-25 08:23
Hello @janekx ,

Please give more details about your issue.

What are the exact steps to reproduce ? 
What is the problem and what should be result be instead ?
What should be checked in the db ?

**Comment by janekx** [comment] 2023-10-25 09:37
Hi, steps to reproduce is look what says DB and list. Problem is clear it not show what should. it is in my test site now i can offer access to check self to Ps devs

**Comment by florine2623** [comment] 2023-10-25 09:47
Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/34334 and https://github.com/PrestaShop/PrestaShop/issues/34337 ?

**Comment by janekx** [comment] 2023-10-25 10:07
No, i not use filters, easily the DB content is good and BO list stock movings shows partial bad items.

**Comment by florine2623** [comment] 2023-11-08 16:08
Are you talking about the fact that the ID in BO and the id_stock_mvt in the database do not match ?



<img width="1162" alt="Screenshot 2023-11-08 at 17 02 00" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/668aa1d3-9a87-4dbd-b94f-9b38084f2108">
<img width="1288" alt="Screenshot 2023-11-08 at 17 02 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e4ef282b-ae65-4b55-ab41-3c4895025b43">

**Comment by janekx** [comment] 2023-11-09 11:00
Item listedin BO is diferent then item in DB table mvt
these two items in DB 
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/4f2c9c5f-dff4-4292-bdba-df0b94bd4344)

are in 1.6.23 this items 
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/b43b78f6-8323-4d6e-b2c7-610e0013ce7e)

but in 8.1.2 says 
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/1490a7ac-ce2a-48db-8767-7324caffd9f6)

IMHO the list in 8.1.2 show not product id but take diferent product 

AS i told i have testing enviroment you can get access to look, write me private if want

**Comment by AureRita** [comment] 2023-11-09 14:40
Hi @janekx 

Thank you for your report, currently we don't understand how we can reproduce your issue, can you give us bigger steps to reproduce, where you writte what you do in each clic you did. 
Currently, because you screen is not in english (it's normal) we can't understand this legend : "are in 1.6.23 this items" does it mean you are in prestashop version 1.6.23 ? 

Waiting for your feedback

**Comment by janekx** [comment] 2023-11-10 09:25
1.6.23 is my working enviroment, i have make updates to 1.7 and to 8.1.2 on my test enviroment. 
Used DB is from working enviroment and was succesfully updated by 1click update on test envirmonet 

1.6.23 shows 
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/31747f37-3655-4222-8aad-3da86daa6e4c)

the 8.1.2 shows 
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/d4459ad4-af6c-4208-a829-69247f3bf37b)

DB in test enviroment shows the items well stock_mvt
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/87cf9709-22a6-46a0-9ee1-a5be1275f66c)

but list in BO 8.1.2 is bad 
first show only 2 tems from 4 in that same time, Why? no filter.
should show stock items ID_stock 266, 259, 64 and 137
what we see is item Id_stock 7 (id_product 12) and ID_stock 34 (id_product 43) 

![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/50bde862-85c6-4869-972c-f4ebc3200523)


![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/aca4939a-6e2c-4c57-b3bd-ef8e7780dc3b)

![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/1a7a79e7-4983-4022-be2d-3d47f43a9de6)

**Comment by hibatallahAouadni** [comment] 2023-11-22 13:21
Hello @janekx 

Thanks for your feedback and your patience.
Could you please provide screen record of 8.1 where you encountred the issue 🙏 
Cause despite all provided infos, I still don't manage to reprodcue the issue 😞 

Thanks!

**Comment by janekx** [comment] 2023-11-22 20:05
![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/df3bf5eb-8108-4dc1-8086-0cb123afee15)
yu mean this?

**Comment by janekx** [comment] 2023-11-22 20:10
1.6 same position chek dates and times 

![image](https://github.com/PrestaShop/PrestaShop/assets/2682800/cd706157-b0be-4313-b132-a8946a7581b2)

**Comment by florine2623** [comment] 2023-12-07 13:57
Hello @janekx ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2023-12-07 13:57 UTC
Labels: Bug, BO, Stocks, 8.1.x

**Comment by janekx** [comment] 2023-12-08 07:47
I report bug what seems to i can replicate severals install and you close it, why then use bug report if you cant react and spend 5min to check offered test enviroment to study the bug.
