### ISSUE TITLE
Categories not translate on module manager page in the BO

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11440] opened 2018-11-20 08:23 UTC
**Describe the bug**
I think this is wrong translation of "Natif" string on module manager page in the BO. If I'm not wrong "Natif" is french word, It should be "Native" in English language.

**To Reproduce**
1. Go to 'BO > Module Manager'
2. See the listed Category.

**Screenshots**
![natif](https://user-images.githubusercontent.com/40850057/48760228-5a29b880-eccb-11e8-83d8-6e5cb80f0256.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 Beta1

**Comment by khouloudbelguith** [comment] 2018-11-21 08:09
Hi @dineshbadrukhiya,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0beta1.
@LouiseBonnard what do you think? it could be fixed in Crowdin?
Thanks!

**Comment by marionf** [comment] 2018-11-21 08:35
The issue is categories are not translated

I use French and all categories are in English

![capture d ecran_644](https://user-images.githubusercontent.com/13449658/48828708-bbf02e00-ed70-11e8-94a3-62d23f734a44.png)

**Comment by marionf** [comment] 2018-11-21 08:36
@loutoma FYI

**Comment by LouiseBonnard** [comment] 2018-11-21 09:13
Dear all, I can't find the translation key corresponding to it within the Crowdin catalog, then I guess that I cannot be solved by changing the translation. Do you think that it is a bug?

**Comment by marionf** [comment] 2018-11-22 08:31
Same issue with MBO

![capture d ecran_649](https://user-images.githubusercontent.com/13449658/48890578-7481a480-ee39-11e8-9517-cf84b9d5f3c9.png)

**Comment by PierreRambaud** [comment] 2018-11-22 09:04
Hi @khouloudbelguith can you reproduce this on the branch 1.7.5.x? I can't reproduce.
F.Y.I someone delete translations key in xliff files, that's why translations are missing :)

**Comment by khouloudbelguith** [comment] 2018-11-22 09:17
Hi @PierreRambaud, with the branch 1.7.5.x, I did not manage to reproduce the issue, there is no category with the "Natif" name, this category doesn't exist anymore in the 1.7.5.x branch.
But the problem described by @marionf exists in the 1.7.5.x.

**Comment by dineshbadrukhiya** [comment] 2018-11-23 15:42
@PierreRambaud there is no category in the drop down list with the “Natif” or “Native”, But as I have shared screenshot, there is Contact Form module listed under “Natif” in 1.7.5.0 Beta 1 version.

**Comment by LouToma** [comment] 2018-11-23 15:53
@dineshbadrukhiya this module will be moved to the good category when the product sheet is ready, @LouiseBonnard have you had time to work on it ? Then, no module will appear in the category that will not be displayed

**Comment by LouiseBonnard** [comment] 2018-11-23 16:26
Yes, it should be okay soon. At least for the categories!

**Comment by marionf** [comment] 2018-11-23 16:27
Contact form appears in "Others" categories on 1.7.5.x
The issue here is the translation of categories in module manager and MBO pages, they are not translated

**Comment by marionf** [comment] 2018-11-30 09:10
Not fixed :(

**Comment by jolelievre** [comment] 2018-11-30 18:11
I can't reproduce the problem on the 1.7.5.x branch
Is there something specific to do to reproduce it? During the install process or something else?

Or maybe it has been fixed?

**Comment by marionf** [comment] 2018-12-03 10:07
@jolelievre 

I just tried an install in French on 1.7.5.x and categories are in English

![capture d ecran_707](https://user-images.githubusercontent.com/13449658/49367188-99083700-f6eb-11e8-91dd-31125588fd4f.png)

**Comment by jolelievre** [comment] 2018-12-03 10:52
Ok I managed to reproduce it. However I see the problem in the selection list but not in the display under. The titles of each category section is correctly translated. Do you have the same behavior?

**Comment by marionf** [comment] 2018-12-03 11:05
It's not translated for me

![capture d ecran_708](https://user-images.githubusercontent.com/13449658/49370190-c78a1000-f6f3-11e8-9b73-a3b55d3e962b.png)

**Closed as completed** 2018-12-05 14:40 UTC
Labels: Bug, Minor, BO, Fixed, Module manager, 1.7.5.0

**Comment by idnovate** [comment] 2019-02-13 15:02
> It's not translated for me
> 
> ![capture d ecran_708](https://user-images.githubusercontent.com/13449658/49370190-c78a1000-f6f3-11e8-9b73-a3b55d3e962b.png)

Same for me. And please note that due to this issue, modules are not sorted correctly inside their category but in "Others".

EDIT: Oh I didn't realize that this issue was closed. I still can reproduce the problem in PS 1.7.5.0.

**Comment by marionf** [comment] 2019-02-14 15:47
@idnovate I just tried a fresh 1.7.5.0 install, categories are translated and modules correctly soreted in their categories

![capture d ecran_1014](https://user-images.githubusercontent.com/13449658/52798416-2bc43b00-3078-11e9-8f81-19aeb8f459ae.png)

![capture d ecran_1015](https://user-images.githubusercontent.com/13449658/52798421-2e269500-3078-11e9-8279-2f4497de9702.png)

**Comment by idnovate** [comment] 2019-02-15 12:24
Just installed a fresh 1.7.5.0 in Spanish:

![image](https://user-images.githubusercontent.com/15104724/52856552-06413b00-3125-11e9-80b4-830ef10356e6.png)
