### ISSUE TITLE
PS 8.0.1. class/Customer.php function getSimpleAddressSql() generates incorrect SQL

### ISSUE THREAD

**Issue by mxmus** [PrestaShop/PrestaShop#30833] opened 2023-01-12 13:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In 8.0.1 was added ORDER BY expression to class/Customer.php function getSimpleAddressSql().
But it was not considered next optional adding expression for filtering by id_address.
Condition "AND a.`id_address` = xxx" ignored because of incorrect SQL statement "ORDER BY a.`alias` AND a.`id_address` = xxx":

```
SELECT DISTINCT
                      a.`id_address` AS `id`,
                      a.`alias`,
                      a.`firstname`,
                      a.`lastname`,
                      a.`company`,
                      a.`address1`,
                      a.`address2`,
                      a.`postcode`,
                      a.`city`,
                      a.`id_state`,
                      s.name AS state,
                      s.`iso_code` AS state_iso,
                      a.`id_country`,
                      cl.`name` AS country,
                      co.`iso_code` AS country_iso,
                      a.`other`,
                      a.`phone`,
                      a.`phone_mobile`,
                      a.`vat_number`,
                      a.`dni`
                    FROM `ps_address` a
                    LEFT JOIN `ps_country` co ON (a.`id_country` = co.`id_country`)
                    LEFT JOIN `ps_country_lang` cl ON (co.`id_country` = cl.`id_country`)
                    LEFT JOIN `ps_state` s ON (s.`id_state` = a.`id_state`)
                     INNER JOIN ps_country_shop country_shop
        ON (country_shop.id_country = co.id_country AND country_shop.id_shop = 1)
                    WHERE
                        `id_lang` = 1
                        AND `id_customer` = 2
                        AND a.`deleted` = 0
                        AND a.`active` = 1
                    ORDER BY a.`alias` AND a.`id_address` = 16663
```
And as result will be selected all the customer addresses, but not the one filtered by id_address. 

### Expected behavior

function getSimpleAddressSql() should return one selected address filtered by id_address. 
Correct generated SQL code should be the following:
```
SELECT DISTINCT
                      a.`id_address` AS `id`,
                      a.`alias`,
                      a.`firstname`,
                      a.`lastname`,
                      a.`company`,
                      a.`address1`,
                      a.`address2`,
                      a.`postcode`,
                      a.`city`,
                      a.`id_state`,
                      s.name AS state,
                      s.`iso_code` AS state_iso,
                      a.`id_country`,
                      cl.`name` AS country,
                      co.`iso_code` AS country_iso,
                      a.`other`,
                      a.`phone`,
                      a.`phone_mobile`,
                      a.`vat_number`,
                      a.`dni`
                    FROM `ps_address` a
                    LEFT JOIN `ps_country` co ON (a.`id_country` = co.`id_country`)
                    LEFT JOIN `ps_country_lang` cl ON (co.`id_country` = cl.`id_country`)
                    LEFT JOIN `ps_state` s ON (s.`id_state` = a.`id_state`)
                     INNER JOIN ps_country_shop country_shop
        ON (country_shop.id_country = co.id_country AND country_shop.id_shop = 1)
                    WHERE
                        `id_lang` = 1
                        AND `id_customer` = 2
                        AND a.`deleted` = 0
                        AND a.`active` = 1
                        AND a.`id_address` = 16663
                    ORDER BY a.`alias`
```
### Steps to reproduce

php call $customer->getSimpleAddress($id_address);

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.20

**Comment by lmeyer1** [comment] 2023-01-12 14:00
Great, you found this. I just found it yesterday

**Comment by AureRita** [comment] 2023-01-12 17:04
Hi @mxmus 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

and thanks @lmeyer1 for your PR :rocket: 

Thanks

**Comment by florine2623** [comment] 2023-01-13 10:15
ping @PrestaShop/prestashop-core-developers 
A [PR](https://github.com/PrestaShop/PrestaShop/pull/30834) is Waiting for QA but this issue is not approved yet. Could you check and confirm the issue is reproduced on your side ?

**Comment by MatShir** [comment] 2023-02-28 09:21
Fixed by https://github.com/PrestaShop/PrestaShop/pull/30834

**Closed as completed by MatShir** 2023-02-28 09:21 UTC
Labels: Bug, CO, SQL Manager, Fixed, PR available, 8.0.1
