### ISSUE TITLE
 non-existent Service "product_comment_repository" requested

### ISSUE THREAD

**Issue by jagunsow** [PrestaShop/PrestaShop#24079] opened 2021-04-15 18:09 UTC
#### Describe the bug

Productcomment v4.2.1

Comments wont list at product page

Details at:
https://www.prestashop.com/forums/topic/1043021-productcomments-servicenotfoundexception/

#### Expected behavior
Comments should be listed on product page

#### Steps to Reproduce

1. Access any page with 1 or more comments eg (https://torretecidos.com.br/tecido-suede/55500648-tecido-sued-amassada-cor-vermelha-.html)
or simply access
 https://torretecidos.com.br/module/productcomments/ListComments?id_product=55500648&page=1
that should not return error 500

2. scroll to the product bottom(#product-comments-list-header), no comment is listed

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![](https://www.prestashop.com/forums/uploads/monthly_2021_02/image.png.e88ebcc43c7d3500c40b3f2db4e878fb.png)

![](https://www.prestashop.com/forums/uploads/monthly_2021_02/image.png.74ec251c3b7a50a4adae844e2876388b.png)

![](https://www.prestashop.com/forums/uploads/monthly_2021_02/image.png.9c47f3a7e623e18d4eea760c91050d6e.png)

#### Additional information

* PrestaShop version: 1.7.7.1 
* PHP version:  7.2

**Comment by florine2623** [comment] 2021-04-16 08:03
Hello @jagunsow ,

I can't reproduce your issue on PS 1.7.7.1 using product-comment module v4.2.1 :
![Capture d’écran 2021-04-16 à 10 01 11](https://user-images.githubusercontent.com/16019289/114992181-c019ca80-9e9a-11eb-8141-73745d491f77.png)
![Capture d’écran 2021-04-16 à 09 59 38](https://user-images.githubusercontent.com/16019289/114992205-c8720580-9e9a-11eb-96a5-08dd3b2d25d5.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.
Thanks!

**Closed as completed by florine2623** 2021-04-16 08:03 UTC
Labels: Can't reproduce

**Comment by jagunsow** [comment] 2021-04-16 16:53
Just leaving the fix I had to do so others can save some time:
at file modules/productcomments/controllers/front/ListComments;php
around line 60 there is:
dateFormatter = new \IntlDateFormatter(
I swiched that to the date_format aproach, and it worked,

like that 
    /**$dateFormatter = new \IntlDateFormatter(
                $this->context->language->locale,
                \IntlDateFormatter::SHORT,
                \IntlDateFormatter::SHORT
            );
		 **/
            $productComment['customer_name'] = htmlentities($productComment['customer_name']);
            $productComment['title'] = htmlentities($productComment['title']);
            $productComment['content'] = htmlentities($productComment['content']);
            $productComment['date_add'] = date_format($dateAdd,"d/m/Y H:i:s");//$dateFormatter->format($dateAdd);

cheers!
