### ISSUE TITLE
Bug filter products backoffice MultiShop

### ISSUE THREAD

**Issue by Ericdev89** [PrestaShop/PrestaShop#23009] opened 2021-01-27 09:00 UTC
#### Describe the bug

Hello I have a prestashop 1.7.6.4 configured in multishop. ( 2 stores ) 

But when I want to filter products in the back office by putting me on the other store it displays all the products.

on the other hand on the store by default everything goes well

#### Expected behavior

when I choose a store the filter should show me only the products that match the filter in that store

#### Steps to Reproduce

1. Toggle to the second shop in BO
2. BO>Catalog>Products
3. Filter by (Reference OR Name OR ID )
4. See error ( All products of second store are displayed instead of those matching the filters)

**Screenshots**

![image](https://user-images.githubusercontent.com/44771382/105983341-de8cd880-6098-11eb-970c-20acef9c7101.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment] 2021-01-27 11:12
Hello @Ericdev89 

Could you please check the steps to reproduce that I just put it in your issue description if they are right?
Please check and feedback.

Thanks!

**Comment by Ericdev89** [comment] 2021-01-27 11:17
> Hello @Ericdev89
> 
> Could you please check the steps to reproduce that I just put it in your issue description if they are right?
> Please check and feedback.
> 
> Thanks!

hello @hibatallahAouadni  
yes i just updated steps 3 and 4 .
Thanks.

**Comment by hibatallahAouadni** [comment] 2021-01-27 11:29
Hello @Ericdev89 

Thanks for your feedback!
I didn't manage to reproduce your issue with PS1.7.6.4 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/13RTqNz2gWLgcf9vafIcymWAQqvcUQqSw/view

Please check and feedback.
Thanks!

**Comment by Ericdev89** [comment] 2021-01-27 12:28
thanks @hibatallahAouadni 

the sql where clause in File src/Adapter/Admin/AbstractAdminQueryBuilder.php ( compileSqlQuery function ) 
returns bad filter when on the second shop due to some bug i dont know. 
there are some empty values in the array where clauses and so the generated where filter fails !

BEFORE PATCH FILE
Array Of WHERE CLAUSES
(
    [0] => AND
    [1] => 1
    [2] => 
    [3] => p.`reference` LIKE '%PKMEB05TRI_EMBRO%'
    [4] => state = 1
    [5] => 
)
WHERE 1

---------------------------------------------------------------------------------------------------
AFTER  PATCH FILE
Array Of WHERE CLAUSES
(
    [0] => AND
    [1] => 1
    [3] => p.`reference` LIKE '%PKMEB05TRI_EMBRO%'
    [4] => state = 1
)
WHERE (1 AND p.`reference` LIKE '%PKMEB05TRI_EMBRO%' AND state = 1)

not the best choice to update the core file but don't know how to do it in a clean way

Thanks for give me help


![image](https://user-images.githubusercontent.com/44771382/105990687-24e73500-60a3-11eb-8598-323bf5368a39.png)

**Comment by hibatallahAouadni** [comment] 2021-01-27 15:07
Hello @Ericdev89 

I see what you mean but I need to reprpduce the issue on my side to fix it :wink: 
So, is there any detail that you miss? do you use another theme? did you make any override?
Please check and feedback.

Thanks!

**Comment by Ericdev89** [comment] 2021-01-28 08:47
hello @hibatallahAouadni 

i dont see any override that cause that.
i'll check further 

Thanks.

**Comment by hibatallahAouadni** [comment] 2021-01-28 13:11
@Ericdev89 Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:24
Hello @Ericdev89 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-17 13:24 UTC
Labels: Bug, BO, Categories, Multistore, No change required, 1.7.6.4
