### ISSUE TITLE
[bug: ps 1.7.6.7] When saving carrier info, it has auto increment id. This can have impact with the database performance

### ISSUE THREAD

**Issue by arafatx** [PrestaShop/PrestaShop#20283] opened 2020-07-22 23:26 UTC
Prestashop version 1.7.6.7

#### Describe the bug

I'm setting up a new store, when I edit carrier setting and save it (even without any modification), the new ID is generated and a new carrier record is inserted into the carrier table

#### Expected behavior

Clicking save button shouldn't generate new ID and add new record if no modification is done

I understand, this behavior is for historic purpose but, it should be updated instead of creating a new record and left the record un-used.  we can't even see at the backoffice or front end this historic data

This will make the database fill with unused records and it i will effect database performance. Let say a 10000 modification per week for one carrier, then we gonna have 10000 historic records. Who knows that somebody need this frequent modification.

Please take a look at this forum discussion for more information:

https://www.prestashop.com/forums/topic/353386-ps-15-carrier-id-change-increment-after-saving/?tab=comments#comment-3252658

**Comment by kpodemski** [comment] 2020-07-23 05:10
Thanks to indexes it's almost impossible to do any harm to this piece of the system. It's working like this for over 10 years now. I never had any issues because of this :)

**Comment by PululuK** [comment] 2020-07-23 05:59
@matks  maybe we should add that here : https://github.com/PrestaShop/PrestaShop/issues/20084 ?

**Comment by khouloudbelguith** [comment] 2020-07-27 14:56
Hi @arafatx,

Your ticket is a duplicate of #9592
Please follow: https://github.com/PrestaShop/PrestaShop/issues/9592#issuecomment-533135677
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-07-27 14:57
Duplicate of #9592

**Closed as completed by khouloudbelguith** 2020-07-27 14:56 UTC
Labels: BO, Duplicate, Carriers, 1.7.6.7

**Comment by arafatx** [comment] 2020-07-30 00:39
@khouloudbelguith Thank you so much. So it's a hidden feature ^_^
