### ISSUE TITLE
BUG in Customer Thread 

### ISSUE THREAD

**Issue by sybon** [PrestaShop/PrestaShop#11244] opened 2018-11-02 14:47 UTC
Dear Community,

IN PS 1.7.3 und ps 1.7.4, each time I want to read the customer threads in admin panel, click on SAV (CustomerThread) :
https://science-de-la-conscience-magazine.fr/admin792tnernx/index.php?controller=AdminCustomerThreads&id_customer_thread=12&viewcustomer_thread&token=c22d1e1cf564deae768926674a25fb38
I get this page with this error message in Firefox (see screenshot in attach):
« Erreur d’encodage de contenu ». 

In Chrome, I get this error on the same url : 
ERR_CONTENT_DECODING_FAILED

![ps174_customerthread_bug_err_content_decoding_failed](https://user-images.githubusercontent.com/18091380/47922013-4a7e3780-deb6-11e8-8388-3587ae6625bb.jpg)

Could you help me to fix this bug ?
Best regards,
Sylvain

**Comment by MathiasReker** [comment] 2018-11-02 14:51
Please enable debug mode

**Comment by sybon** [comment] 2018-11-02 15:01
Hi thanks for ur reply.
I have switched to debug mode but in this moode, i can t reproduce the problem : it work perfectly.
strange. Any explanation ?

**Comment by khouloudbelguith** [comment] 2018-11-02 15:08
Hi @sybon,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) for the PS 1.7.4 and the folder into app/cache (prod & dev) for the PS 1.7.3
Thanks to check and feedback.

**Comment by sybon** [comment] 2018-11-02 15:22
Hi khouloudbelguith, Thanks for ur replay. Is it safe to remove all these files in var/cache/prod and var/cache/dev ?

**Comment by khouloudbelguith** [comment] 2018-11-02 15:29
@sybon, they are cache files.

**Comment by sybon** [comment] 2018-11-02 15:33
ok, i have removed all of them... but the error remains the same. Thanks for ur help anyway

**Comment by khouloudbelguith** [comment] 2018-11-02 15:37
Hi @sybon,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sybon** [comment] 2018-11-02 15:44
Thank you for your support,

My ps 1.7.4 is on OVH server in France.
i have tried to get acess to php_error.log via ssh but i get the message : permission denied

**Comment by khouloudbelguith** [comment] 2018-11-02 16:03
@sybon, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
If you don't have it, you should ask to your hosting provider.

**Comment by khouloudbelguith** [comment] 2018-12-05 16:45
Hi @sybon,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-05 16:45 UTC
Labels: Bug, BO, Can't reproduce, 1.7.4.3
