### ISSUE TITLE
ImageManager should support webp images

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#23919] opened 2021-04-07 09:33 UTC
#### Is your feature request related to a problem?

Prestashop does not accept images in webp format, but this format is now widely used. It would be great for Prestashop to allow the import of webp images for products.
Since webp is not supported by all browsers, it would make sense to convert webp images to png.

#### Describe the solution you'd like

`ImageManager::create` should accept `IMAGETYPE_WEBP` as parameter. `ImageManager::MIME_TYPE_SUPPORTED` should include `image/webp`. `ImageManager::resize` should convert webp images to png and use transparent background.

#### Alternative

Currently one needs to convert webp images outside of Prestashop, before importing them.

#### Additional context

PHP supports webp format since version 5.4 (`getimagesize` and `imagecreatefromwebp`). PS 1.7 requires at least PHP 5.6. It would be time to add support for it.

**Comment by florine2623** [comment] 2021-04-07 15:23
Hello @lmeyer1 ,
Please stay tuned as I ping product-team for your suggestion !
Thanks!

**Comment by florine2623** [comment] 2021-04-07 15:24
Ping @PrestaShop/product-team ,

@lmeyer1 suggests to add a new format for images : WEBP.
Now GIF, PNG and JPG are accepted.
What do you think ?

Thanks!

**Comment by marionf** [comment] 2021-04-07 16:04
Hello,

This feature request has already been submited, please follow this issue: #10356

Thank you!

**Comment by marionf** [comment] 2021-04-07 16:04
Duplicate of #10356

**Closed as completed by marionf** 2021-04-07 16:04 UTC
Labels: Improvement, Duplicate, Design, Image, 1.7.7.x

**Comment by lmeyer1** [comment] 2021-04-07 16:09
@marionf  Thanks, I will look at the other thread in depth. Sure this is also related to <picture> tag and fallback to jpg.
I already implemented this in PS 1.6.1.1. I will share the code with a PR as I will migrate my solution to 1.7.7.3
