### ISSUE TITLE
Does the SEO keywords are taken into account on the Prestashop platform?

### ISSUE THREAD

**Issue by piupiu09** [PrestaShop/PrestaShop#12845] opened 2019-03-08 13:47 UTC
We are actually working on the SEO of our website, on the SEO tab of the the products, this means including keywords on the Title, description and keywords tags and I was informed, that apparently the Prestashop platform does not  take these modifications into account these, for improving the SEO of the website, therefore no need to add them then? Is this right?

Thank you for your help

**Comment by khouloudbelguith** [comment] 2019-03-08 14:17
Hi @piupiu09,

I attached a video record.
https://drive.google.com/file/d/1Z0YfqV9X2urgDPbyLJWolOiq4UmYAR2c/view
Thanks to check & feedback.

**Comment by rdy4ever** [comment] 2019-03-09 10:55
> and keywords tags

[Google does not use the keywords meta tag in web ranking](https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html) for over 10 years (and probably no other search engines).  So, yes, regarding the keywords field you really should not bother anymore.
However, title and meta description do work as intended (if the theme has no issues).

**Comment by khouloudbelguith** [comment] 2019-03-11 11:31
Hi,

@rdy4ever, thanks for your feedback.
@piupiu09, did you use the default theme PrestaShop?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-09 15:54
Hi @piupiu09,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-09 15:54 UTC
Labels: SEO & URLs, No change required, 1.7.5.1
