### ISSUE TITLE
MethodNotAllowedHttpException thrown after token issues with post requests

### ISSUE THREAD

**Issue by Nakahiru** [PrestaShop/PrestaShop#18003] opened 2020-03-05 16:45 UTC
#### Describe the bug

On PrestaShop 1.7.7.x, when the token is invalid and request is POST and we select "Continue, I understand the risk" a MethodNotAllowedHttpException is thrown.

#### Expected behavior

Redirect to the selected page.

#### Steps to Reproduce

1. Go to a migrated Symfony page in backoffice
2. In the url, change the token
3. Do an action that post a form with some data like making a partial refund on an order
4. MethodNotAllowedHttpException occurred

**Screenshots**

![image](https://user-images.githubusercontent.com/16980315/76002550-13cf8b80-5f07-11ea-8f52-0c5075bf0c46.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-05 17:09
Hi @v4lux,

I manage to reproduce the issue with the branch 1.7.7.x.
https://drive.google.com/file/d/1hhy9eTSfUTuiqztEAfAa3RkumEndj4L0/view
![image](https://user-images.githubusercontent.com/16067358/76006032-2ef0ca00-5f0c-11ea-9e54-556aaa1e5e91.png)

I’ll add this to the debug roadmap.

FYI @matks
Thanks!

**Comment by eternoendless** [comment] 2020-03-09 13:42
@v4lux Was there a specific reason to change the token or you just stumbled upon this bug?

**Comment by matks** [comment] 2020-03-09 13:46
> @v4lux Was there a specific reason to change the token or you just stumbled upon this bug?

I was next to him, we stumbled into the bug. Error page does not keep the http method.

**Comment by colinegin** [comment] 2020-03-09 17:56
@zalexki @Matt75 could you give us some details on why did @v4lux have to change the token in the URL ? Do you have any screenshot to provide ? 

@khouloudbelguith has tested the refund feature, it seems to be working correctly. It's only when changing the token (which should not be done) that this exception occurs. Here is a video : https://drive.google.com/file/d/1hhy9eTSfUTuiqztEAfAa3RkumEndj4L0/view

**Comment by Matt75** [comment] 2020-03-10 09:11
@colinegin We don't have more than this bug report but @matks saw @v4lux about this problem and was next to him during this test.

**Comment by zalexki** [comment] 2020-03-10 14:25
The token wasn't manually changed, i'm pretty sure the token was unvalidated too quickly on @v4lux dev environment which made pop this issue very frequently.

**Comment by colinegin** [comment] 2020-03-10 16:42
What do you think @PrestaShop/prestashop-core-developers ?

**Comment by matks** [comment] 2020-03-11 08:16
> @zalexki @Matt75 could you give us some details on why did @v4lux have to change the token in the URL ? Do you have any screenshot to provide ?

I believe some ps_checkout links were not using the token or using a wrong token. But the how does not really matter I think the issue is that the "warning" page does not handle POST requests correctly.

Possible solutions:
- allow "warning" page to handle POST (and probably DELETE, PUT, PATCH too) requests
- if request is not GET, then dont redirect after the warning page but rather send user back to previous page

**Comment by colinegin** [comment] 2020-03-11 10:23
Investigation needs to be done on the incorrect reason token. @matks

**Comment by matks** [comment] 2020-03-11 13:20
@Quetzacoalt91 @v4lux I might need your help to reproduce this bug. Actually we are not interested into this bug but rather the root cause: why you got an invalid token ?

**Comment by Quetzacoalt91** [comment] 2020-03-12 15:22
@v4lux is OOO and cannot answer at the moment.

It said that was randomly occurring on its shop. His shop was deployed from the docker image [`prestashop/prestashop:beta-7.3-apache`](https://github.com/PrestaShop/docker/blob/master/images/beta-7.3-apache/Dockerfile).

**Comment by matks** [comment] 2020-03-16 15:55
Could not see the issue 😐after testing PS Checkout ...
Maybe a specific environment or php version ?

**Comment by colinegin** [comment] 2020-04-17 09:03
What's the status of this issue ?

**Comment by colinegin** [comment] 2020-05-15 08:20
Any news @v4lux ?

**Comment by Matt75** [comment] 2020-05-15 13:55
Refund process on PrestaShop Checkout has been rewrite in v1.4.0
This issue will now not occur with our module.

**Comment by colinegin** [comment] 2020-06-01 08:51
ping @Matt75 @Darmona i close this issue as it no longer occurs on your module.
Feel free to reopen it if it happens again.

Thanks !

**Closed as completed by colinegin** 2020-06-01 08:51 UTC
Labels: Bug, Minor, BO, No change required, migration, 1.7.7.x
