### ISSUE TITLE
Undefined indexes in Product.php generating multiple warnings in error_log

### ISSUE THREAD

**Issue by agroundworld** [PrestaShop/PrestaShop#25810] opened 2021-09-08 02:33 UTC
#### Describe the bug
In doing routine maintenance on my website, I noticed that the error_log file was generating multiple warnings. Two warnings are being generated repeatedly due to undefined indexes in the Product.php file. The text of the errors are as follows:

`PHP Notice:  Undefined index: attribute_price in /home/soccerph/public_html/pshop/classes/Product.php on line 3418`

`PHP Notice:  Undefined index: attribute_ecotax in /home/soccerph/public_html/pshop/classes/Product.php on line 3419`

#### Expected behavior
No warnings written to the log file for undefined indexes.

#### Steps to Reproduce
Not sure how to replicate since I don't what what actions are generating those calls. 
I have been working on adding products

**Screenshots**
Attaching screenshot of some rows of log file:
![Undefined Index](https://user-images.githubusercontent.com/75636570/132437014-57d7c77c-c43d-4877-96cb-666f13f84ae1.jpg)

#### Additional information

- PrestaShop version: 1.7.7.7
- PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-09-08 09:51
Hello @agroundworld 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25782. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-08 09:51
Duplicate of #25782

**Closed as completed by hibatallahAouadni** 2021-09-08 09:51 UTC
Labels: Duplicate
