### ISSUE TITLE
You can not sort payment options when using different hooks 

### ISSUE THREAD

**Issue by hh-com** [PrestaShop/PrestaShop#12616] opened 2019-02-18 22:31 UTC
**Describe the bug**
Payment-modules sometimes call more than one payment hook - for example "displayPaymentEU" and "paymentOptions". 
In classes\checkout\PaymentOptionsFinder.php we first load displayPaymentEU then the rest of the paymentOptions. displayPaymentEU Payment Modules will always be on the top.

**To Reproduce**
1. Install a new PrestaShop.
2. Activate cheque- and bankwire payment.
3. Install the free Sofort/Klarna payment module.
https://addons.prestashop.com/de/zahlung-uberweisung/9176-sofort.html
4. Try to Change the order of your paymentOptions in the AdminModulesPositions.
5. Now you see that Sofort/Klarna payment will always be on the top. You have no chance to set Sofort/Klarna as the last payment option.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-02-19 07:26
Hi @hh-com,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9756
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-19 07:26
Duplicate of #9756

**Closed as completed by khouloudbelguith** 2019-02-19 07:26 UTC
Labels: Duplicate
