### ISSUE TITLE
PS 1.7.5.2 Free product. Order not possible

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#16251] opened 2019-11-02 14:09 UTC
Hello,
The shop has products with price but one of them is a free service. I create it as a virtual product. Customer can ask it by adding it in his cart. If he needs only this service without other products, the order is blocked because there is no payment method. 
The only way I found should be to activate cheque paiement only for free products and to rename it.

I didn't found any other idea.

How to reproduce :
- create a virtual product
- get the price at 0, no taxe
- add only this product in the cart
- validate the order
=> a message is displaying : don't forget to choose a payment method. 

In parameters, order is allowed from 0

PS 1.7.5.2 with Classic theme

Prestashop doesn't seem to like gratuitousness ??

Thanks a lot for your help

**Comment by khouloudbelguith** [comment] 2019-11-04 09:09
Hi @sirius82,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
I attached a screen record
https://drive.google.com/file/d/1shVbXt5FVAWSn0tkWBs-MqmvcJwGfC-B/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-04 07:58
Hi @sirius82,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-04 07:58 UTC
Labels: Bug, FO, Order, Virtual, No change required, 1.7.5.2, Checkout
