### ISSUE TITLE
Impossible to add combinaisons after delete them

### ISSUE THREAD

**Issue by yvesattias** [PrestaShop/PrestaShop#15728] opened 2019-09-27 09:25 UTC
**Describe the bug**
When I delete a combinaison product and I want to readd after some time the same combinaisons, the system refuse to do it.

I am on a multi-store website.

To resolve, I need to delete all combinaisons for every store, then go to AllStores, recreate all combinaisons and re-enter all prices,etc...

**To Reproduce**
1. Go to Combinaisons
2. Delete a combinaison
3. Try to re-add the same combinaison
4. The system don't want to add the combinaison

**Screenshots**
https://drive.google.com/file/d/1eoCdKTAlyuF1AcbDK6q6tboE-gEbxjad/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.5.2 / 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-09-30 10:28
Hi @yvesattias,

In your case, The UK shop selected is not the first shop? is it?
Your issue seems to be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/9664

Thanks to check & feedback.

**Comment by yvesattias** [comment] 2019-09-30 15:38
@khouloudbelguith 

UK is not my firstshop. I can add combinaisons on the 1st and 2nd stores but not on the 3rd and 4th stores.

Regards,
Lilian

**Comment by khouloudbelguith** [comment] 2019-09-30 15:43
@yvesattias, when debug mode is enabled, have you same exception as described in this screenshot?
![image](https://user-images.githubusercontent.com/16067358/65894316-75605c80-e3a1-11e9-8480-20b27153ccc9.png)

Thanks!

**Comment by yvesattias** [comment] 2019-09-30 16:12
@khouloudbelguith 

Yes I have the same error 
 http://prntscr.com/pcyznz

**Comment by khouloudbelguith** [comment] 2019-10-01 16:04
@yvesattias, 

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9664
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-01 16:04
Duplicate of #9664

**Closed as completed by khouloudbelguith** 2019-10-01 16:04 UTC
Labels: Duplicate, Multistore, Combinations, 1.7.5.2, 1.7.6.1
