### ISSUE TITLE
Error code 500 with specifically char

### ISSUE THREAD

**Issue by leo385** [PrestaShop/PrestaShop#31346] opened 2023-02-14 10:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In forms when we send char | before @ in mail field, we get error code 500.

### Steps to reproduce

1. Go to form with email field.
2. Type char | before @ 
3. After submit we get nothing due error code 500.

### PrestaShop version(s) where the bug happened

8.0.1

**Comment by hibatallahAouadni** [comment] 2023-02-15 11:31
Hello @leo385 

I didn't manage to reproduce the issue with PS8.0.1, see the attached screen record below:

[issue_31346.webm](https://user-images.githubusercontent.com/23308427/218986385-3d1f40f9-71b0-4a9a-825f-8e3e5dcb7f82.webm)

Please check and feedback.

Thanks!

**Comment by djoelleuch** [comment] 2023-03-07 10:14
Hello @leo385 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank you

**Closed as not planned by djoelleuch** 2023-03-07 10:14 UTC
Labels: Bug, FO, Contact, Invalid, 8.0.1
