### ISSUE TITLE
regenerating High definition images

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#16113] opened 2019-10-24 15:00 UTC
**Describe the bug**
If you decide to change the use of high definition images in the shop, there is no way to regenerate these without first deleting all other images and regenerate everything. If there is any issues during the highdefinition generating process there is also no way to re-generate just these images.

**To Reproduce**
1. Go to settings images
2. activate use of high definition images
3. regenerate images without delete old images first
4. no highdefinition images are generated.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.x

**Comment by khouloudbelguith** [comment] 2019-10-24 15:06
Hi @Prestaworks,

We are aware of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13957
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-24 15:06
Duplicate of #13957

**Closed as completed by khouloudbelguith** 2019-10-24 15:06 UTC
Labels: Duplicate

**Comment by Prestaworks** [comment] 2019-10-24 15:09
yes I just wrote it because I made a PR to solve it. And they wanted an issue.

**Comment by khouloudbelguith** [comment] 2019-10-24 15:10
@Prestaworks, yes, now it is required to create an issue for all PRs.
Thanks!
