### ISSUE TITLE
Cant login with credential after a ps 1.7.7.2 installation

### ISSUE THREAD

**Issue by pineappledev48** [PrestaShop/PrestaShop#23665] opened 2021-03-16 14:40 UTC
#### Describe the bug

After installation the credential provided during installation are not right to login in back office

#### Expected behavior

Expect to login in backoffice with credential provided during installation

#### Steps to Reproduce

1. Install PS 1.7.7.2 
2. Complete installation
3. Remove Install folder
4. Open backoffice page
5. Try to login with credential
6. Prestashop throw an invalid user / credential error

**Screenshots**

![image](https://user-images.githubusercontent.com/80770500/111327765-f41c8880-866d-11eb-91c1-6bba66811e8c.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3 fpm

**Comment by hibatallahAouadni** [comment] 2021-03-16 16:27
Hello @pineappledev48 

Did you use the same email that you submit while installing?
Please check and feedback.

Thanks!

**Comment by pineappledev48** [comment] 2021-03-16 19:23
Obviously dear, this is a code bug i can't figure out with PHP 7.3 an ps
1.7.7

Il Mar 16 Mar 2021, 17:27 Hibatallah Aouadni ***@***.***> ha
scritto:

**Comment by hibatallahAouadni** [comment] 2021-03-17 17:01
Hello @pineappledev48 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug. If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-17 17:01 UTC
Labels: Bug, BO, Employees, No change required, 1.7.7.2

**Comment by pineappledev48** [comment] 2021-03-17 21:15
O_o I'm 100% sure is an error related to some php extension miss that
prestahop are not smart enough to check ... Btw if you think is close :) go
on and close ^^ wo need to login on backoffice :)

Il Mer 17 Mar 2021, 18:01 Hibatallah Aouadni ***@***.***> ha
scritto:
