### ISSUE TITLE
VAT not charged on some orders

### ISSUE THREAD

**Issue by gosrl** [PrestaShop/PrestaShop#19120] opened 2020-05-14 08:26 UTC
#### Describe the bug

VAT is not charged on some orders. For what I know (from a customer feedback), the problem happens in the checkout phase, when choosing a payment method (indipendently from the payment method).

In fact, the customer landed on the product and the price was Incl. VAT (170,00 € - which should activate free shipping), but changed in the checkout phase to 158,34 €:

- Price of product: 139,34 € (which is the price of the product without 22% VAT)
- Shipping cost: 19,00 € (incl. VAT)

The problem has happened:
- when paying via Paypal
- when paying via Bank Transfer

TOTAL: 158,34 €

More infos:

- customer groups follow the same rules
- taxes are set corretly
- we only take orders from Italy (so, VAT is ALWAYS applied)
![PHP-configuration](https://user-images.githubusercontent.com/65334261/81911096-1c120a00-95cd-11ea-8300-95df576a5ee0.jpg)

#### Expected behavior

VAT should be charged to all orders.

#### Steps to Reproduce

At this moment, I've found no way to reproduce the issue.

**Screenshots**

Attached

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1

**Comment by florine2623** [comment] 2020-05-14 09:05
Hi @gosrl ,
Can you check your tax rules ?
International > Taxes > Tax rules
Maybe some tax rules are enabling **no tax** in certain countries.
Thanks!

**Comment by gosrl** [comment] 2020-05-14 10:58
Hello,
country is always Italy, we only accept orders from this country.

Now I've explicitly set VAT 22% for all provinces of Italy, and see if this solves the issue.

Also, in those cases when we had this error, VAT was not applied to shipping costs.

Strange thing is the VAT was properly applied on some orders and not applied on other orders. For sure, it has happened 2 times for orders to be shipped to the city of Naples.

So maybe apply VAT to all provinces of Italy is the solution.

I'll let you know.
Thank you

**Comment by florine2623** [comment] 2020-05-15 09:34
Hi @gosrl ,
If you want VAT to be applied in shipping cost, you need to set it in the carrier configuration :
![Capture d’écran 2020-05-15 à 11 33 26](https://user-images.githubusercontent.com/16019289/82035572-f73a9700-969f-11ea-8f8f-99f1b400e161.png)
Thanks!

**Comment by gosrl** [comment] 2020-05-15 09:47
Hello florine,
thank you for your answer.

The VAT has always been present in the carrier configuration:

![image](https://user-images.githubusercontent.com/65334261/82036394-256ca680-96a1-11ea-8a19-376acb7705a5.png)

Somehow VAT was removed in the checkout page. I asked to 2 of the customers and:
- the first one told me the price was already without VAT when he landed on the product page
- the second one told me the VAT was removed when he added the shipping address

I assume in the first case the user was already logged, and in the second case the user placed the order as a guest.

This problem happens just for some customers, so I think it must be related to the address of the customer.

A.

**Comment by florine2623** [comment] 2020-05-15 10:28
Thanks for the details.
- Can you check if the fisrt customer is in a customer group that display the tax ?
Shop Parameters > Customer Settings
![Capture d’écran 2020-05-15 à 12 26 23](https://user-images.githubusercontent.com/16019289/82040774-649df600-96a7-11ea-955d-47101e6364af.png)
- Regarding the second, the tax might not be activated for that customer in that province/state.

**Comment by gosrl** [comment] 2020-05-15 12:34
They are all Tax Incl.
Thank you

**Comment by florine2623** [comment] 2020-05-15 12:58
I still can't reproduce your issue with all the details.
You might need to look into the overrides.

**Comment by florine2623** [comment] 2020-06-08 07:41
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-08 07:41 UTC
Labels: BO, Tax rules, No change required, 1.7.6.3

**Comment by gosrl** [comment] 2020-07-07 16:06
Hello,
I open this again because the problem happened again and I've seen one more strange behaviour.

The customer arrived on the shop from Idealo as a visitor and he told me he found the product at 426,32 € instead of 520 € (which is the amount tax Incl). Of course, he became a guest after the order.

I tried to make the same steps he made and to insert the exactly same data both on Delivery Address and Billing Address.

I choose Paypal as a payment method and logged in with my account. The price of the product was still correct (520 €)

Then I tried to modify the order and some strange thing happened

These are the steps (you can see the video in the zip archive attached):
1. I open the order from the order Panel
2. I go to Products -> Modify (in the product row)
3. I try to change the Price (tax. incl) from 426.23 € to 520 €. The Price (tax. excl) also changes to 520 € **(as if the system is not able to calculate the amount of VAT)**
4. when I click on Cancel, then I see the 426.23 € in the unit price section, but I see 520,00 € on the Total (incl. taxes)

(I don't know if I was able to explain what happened, you will see it more clearly in the video attached.)

Then I moved to another order with same characteristics:
- made by a guest
- paid using paypal

In this case, when I changed the product price (tax incl.) the net price changed accordingly.

It may be a bug of the function managing VAT calculation?

Thank you

[2020-07-07 17-47-59.zip](https://github.com/PrestaShop/PrestaShop/files/4885837/2020-07-07.17-47-59.zip)
