### ISSUE TITLE
Zero price of customized products on Order Confirmation page

### ISSUE THREAD

**Issue by artemevsin** [PrestaShop/PrestaShop#28503] opened 2022-05-16 11:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On Order Confirmation page zero price is showing next to customized products

### Expected behavior

On Order Confirmation page there should be a product price next to product instead of zero price

### Steps to reproduce

1. Install Prestashop with demo products
2. Add product Customized Mug to cart with some custom text
3. Finish the order
4. On Order Confirmation page there is zero price next to the product

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment] 2022-05-16 15:01
Hello @artemevsin 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10912. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-05-16 15:01
Duplicate of #10912

**Closed as completed by hibatallahAouadni** 2022-05-16 15:01 UTC
Labels: Bug, Duplicate, PR available, Invalid
