### ISSUE TITLE
Customer:siret , Customer:birthday results in dropdown in Address form

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#30702] opened 2022-12-30 13:45 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you add  Customer:siret and /or Customer:birthday to a countries address form you'll get an dropdown like:
Customer: [Please Choose]
Instead of the fields :
Siret and/or Birthday
![prestashop_addressform](https://user-images.githubusercontent.com/14218917/210076188-71bbecd0-84e5-43a5-86d6-26af308007e2.png)
![addressfields](https://user-images.githubusercontent.com/14218917/210076197-4889d9af-96f9-4382-b8a1-b1aaaf23c338.png)

### Expected behavior

It should show the fields:
Birthday
Siret

### Steps to reproduce

1. Go to International --> Locations --> Countries --> Choose a country --> Edit 
2. Go to Address Format
3. Add the field Customer:siret manually or by clicking on the option on the right side
4. Save

5. Now go to the frontend of your store
6. Visit your profile page and choose 'ADD FIRST ADDRESS' or 'EDIT ADDRESS' when there is allready an address present
7. Now you see the 'Customer' dropdown

Same goes for the field Customer:birthday

### PrestaShop version(s) where the bug happened

Known in version 1.7.8.2 - 1.7.8.8 but could be present in eralier versions

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-12-30 15:02
Hello @venditdevs 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #11166. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks and happy new year 🎉

**Comment by hibatallahAouadni** [comment] 2022-12-30 15:02
Duplicate of #11166

**Closed as completed by hibatallahAouadni** 2022-12-30 15:02 UTC
Labels: Bug, Duplicate, Invalid
