### ISSUE TITLE
"an error occurred while processing your request" prestashop 1.7

### ISSUE THREAD

**Issue by lapitskiy** [PrestaShop/PrestaShop#13444] opened 2019-04-16 22:20 UTC
i see this error when try _change quantity_
![Скриншот 2019-04-17 00_41_12](https://user-images.githubusercontent.com/7946611/56247598-fce53800-60ad-11e9-87da-90ffcd56710d.png)
an error occurred while processing your request

cache off (set Force compilation)
cache clear (and var/cache)
cookie clear (test another browser)
url rewriting - off
combination - off
multilang - off

error network
![Скриншот 2019-04-17 01_16_47](https://user-images.githubusercontent.com/7946611/56247750-84cb4200-60ae-11e9-8d79-bb59f40cea47.png)
link https://topremeshok.ru/index.php?controller=product&token=76cc4927857d9d0d7d8d799eba382add&id_product=866&id_customization=0&qty=2

**Additionnal information**
PrestaShop version: PS 1.7.5.1
Apache/2.4.7
PHP version: 5.6.40

**Comment by khouloudbelguith** [comment] 2019-04-17 13:42
Hi @lapitskiy,

Your ticket is a duplicate of #10178
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-17 13:42
Duplicate of #10178

**Closed as completed by khouloudbelguith** 2019-04-17 13:42 UTC
Labels: Duplicate

**Comment by OleksiyPenkov** [comment] 2019-05-15 05:47
I've fixed it by adding into nginx.conf

```
	rewrite ^/ru/(.*) /$1;
	rewrite ^/en/(.*) /$1;
```

before the following section
```
    location / {
	
        # Redirect pretty urls to index.php
        try_files $uri $uri/ /index.php?$args;
```
