### ISSUE TITLE
Big number of combinations and slow response

### ISSUE THREAD

**Issue by ig0rig0r** [PrestaShop/PrestaShop#23279] opened 2021-02-16 18:14 UTC
I have 10.000 combinations in one product and I wait for 30 seconds every time when I want to see that page.

Is there any solution or the only way is to reduce the number of combinations?

Additional information:
PrestaShop version: 1.7.6.9
PHP version: 7.1
Performance/Smarty/Cache: YES
Performance/Smarty/Caching type: File system
Performance/Smarty/Clear cache: Clear cache every time something has been modified
Performance/CCC (Combine, Compress and Cache)/Smart cache for CSS: YES
Performance/CCC (Combine, Compress and Cache)/Smart cache for JavaScript: YES
Performance/CCC (Combine, Compress and Cache)/Apache optimization: YES
Performance/Caching/Use cache: NO

**Comment by hibatallahAouadni** [comment] 2021-02-17 09:17
Hello @ig0rig0r 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9809. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-17 09:17
Duplicate of #9809

**Closed as completed by hibatallahAouadni** 2021-02-17 09:17 UTC
Labels: Duplicate
