### ISSUE TITLE
Quick nav does not work anymore

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10758] opened 2018-09-28 23:55 UTC
**Describe the bug**
Read below

**To Reproduce**
1. Go to 'Catalog -> Product -> Edit'
2. Click on 'Product list' icon on your right
3. You'll see an error in devtools Network tab:
> You have requested a non-existent service "prestashop.adapter.filter_parameters_updater". Did you mean one of these: "prestashop.adapter.php_parameters", "prestashop.adapter.product.filter_parameters_updater"?

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-01 07:42
Hi @kpodemski,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10703
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 07:42
Duplicate of #10703

**Closed as completed by khouloudbelguith** 2018-10-01 07:42 UTC
Labels: Duplicate
