### ISSUE TITLE
Change Address Price equal 0

### ISSUE THREAD

**Issue by pruault** [PrestaShop/PrestaShop#22814] opened 2021-01-13 16:17 UTC
#### Describe the bug

When we change the delivery or billing address, all the prices of the products in the order go to zero

#### Expected behavior

When we change the shipping or billing address, all product prices must not change

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-13 17:24
Duplicate of #22816

**Closed as completed by hibatallahAouadni** 2021-01-13 17:24 UTC
Labels: Duplicate
