### ISSUE TITLE
Orders show taxes for customer groups without taxes

### ISSUE THREAD

**Issue by ricchiralt** [PrestaShop/PrestaShop#26742] opened 2021-11-24 19:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There seems to be a conflict between product specific pricing and customer group settings. I have a VK3 customer group configured to not apply any tax on products and all products in my store are configured with a general selling price (VK4) with tax and prices specific to the VK3 group.

Any VK3 user sees the prices without tax in the store, cart or checkout and when they checkout the total shown is without tax.

On the other hand, when they edit their order, although a warning is displayed in the order where it says that the customer sees the prices without taxes, the total of the order does have taxes.

![order](https://user-images.githubusercontent.com/29764404/143304511-dd4d7c97-374e-44bc-b8f7-492f01cc238b.png)

### Steps to reproduce

1. In Prestashop 1.7.6.9 create a group of customers configured not to use any tax.
2. Configure a product with a general price of 17 euros.
3. Add a specific price of 8.3 euros for the customer group that will not use any tax.
4. In the store, log in with a user that is configured for this group and place an order. The total displayed is without tax while the order total in the administrator is taxed.

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2021-11-25 10:25
Hello @ricchiralt 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23784. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: please donwgrade your PHP version to 7.2 (check our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-25 10:26
Duplicate of #23784

**Closed as completed by hibatallahAouadni** 2021-11-25 10:25 UTC
Labels: Bug, Duplicate, Invalid

**Comment by ricchiralt** [comment] 2021-11-25 18:26
Hi @hibatallahAouadni, I see, although it is considered a matter of "improvement" in Prestashop the user, who is in a group configured not to see taxes pays them and the taxes are calculated on the total of the order.

Is there no solution?
