### ISSUE TITLE
Faceted search | Stop the page from jumping to the top

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14740] opened 2019-07-18 12:50 UTC
**Whats wrong**
Every time you select a filter in faceted navigation. The page jumps to the top.
This is super annoying as user has to scroll down every time.

**Solution**
A) Make the page not scroll at all.
B) Make the page scroll to the top of the product list.

The best case would be a select box in the options of the module. With three options:
- Scroll to the top
- Scroll to beginning of product list
- Do not scroll

**Additional information**
PrestaShop version: 1.7.6
Faceted search version: 3.1.0

**Comment by khouloudbelguith** [comment] 2019-07-18 13:31
Hi @Hlavtox,

Thanks for your report.
Yes, I have the same behavior with PS1.7.6.0 & ps_facetedsearch v3.1.0
https://drive.google.com/file/d/1FDnFnITneBd19dCz-msir6CV2WLNVt3d/view
@colinegin, @marionf what do you think of his improvement?

Thanks!

**Comment by marionf** [comment] 2019-07-18 16:53
Hello @Hlavtox 

Your issue is a duplicate of #10993, so I close it

**Closed as completed by marionf** 2019-07-18 16:53 UTC
Labels: Improvement, FO, Duplicate, Faceted search, 1.7.6.0

**Comment by khouloudbelguith** [comment] 2019-07-18 16:56
@marionf, this PR: https://github.com/PrestaShop/PrestaShop/pull/11534 should be fixed in the PS1.7.6.0, but in my case, I have the same issue with PS1.7.6.0.
What do you think?

Thanks!

**Comment by Hlavtox** [comment] 2019-07-18 16:56
@marionf Do you consider this an user friendly behaviour?

**Comment by marionf** [comment] 2019-07-18 17:08
@khouloudbelguith @Hlavtox 

No, it's not supposed to be fixed in 1.7.6.0
Please see this [comment](https://github.com/PrestaShop/PrestaShop/pull/11534#issuecomment-442898509), the PR allow theme developer to choose to keep this scroll or not.

As you can see in the [duplicated issue](https://github.com/PrestaShop/PrestaShop/issues/10993#issuecomment-442858150) we will not change this behavior for the reasons explained
