### ISSUE TITLE
[Multistore] Cannot upload product image on duplicated product

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#24883] opened 2021-06-09 02:58 UTC
#### Describe the bug

When trying to upload an image to a duplicated product in a multistore context, the upload fails with this error:

> Error while creating additional image

#### Expected behavior

Image should be uploaded successfully.

#### Steps to Reproduce

1. Create a multistore shop
2. Select the 1st store in the top right dropdown
3. Create a new product with 2 images
4. Duplicate the product you just created
5. Remove all images
6. Upload a new image
7. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/915273/121285680-fc9cfc00-c908-11eb-94f3-f5ef99c4098e.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-06-09 10:30
Hello @Seb33300 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10137. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-09 10:30
Duplicate of #10137

**Closed as completed by hibatallahAouadni** 2021-06-09 10:30 UTC
Labels: Duplicate
