### ISSUE TITLE
Inbound customer service emails - failing on 'empty messages' and creating open threads not visible in UI

### ISSUE THREAD

**Issue by pcusteau** [PrestaShop/PrestaShop#27549] opened 2022-02-01 00:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, I recently setup the inbound Customer Service email functionality so that correspondance from customers responding to the customer service address would be captured within a thread in Prestashop.

All is working well now except that my customer has been complaining that the message count on the dashboard was getting real high while there were actually no open message threads.

Upon investigation I find that the inbound service will often stumble on messages it finds to be 'empty', it will then create an entry in the ps_customer_thread table attached to the actual customer and with a status of Open - However there is no corresponding content and the message is actually not deleted from the mail server so it will loop indefinitely.

I inspected the offending messages with multiple email readers and could not find any issues with them. Below is the source of one of those emails:

`Return-Path: <mariefleur24@hotmail.com>
Delivered-To: info@autrementetalors.com
Received: from nw67.fcomet.com
	by nw67.fcomet.com with LMTP
	id YOQdJeU78WGq+jgAO7F4wg
	(envelope-from <mariefleur24@hotmail.com>)
	for <info@autrementetalors.com>; Wed, 26 Jan 2022 07:17:41 -0500
Return-path: <mariefleur24@hotmail.com>
Envelope-to: info@autrementetalors.com
Delivery-date: Wed, 26 Jan 2022 07:17:41 -0500
Received: from mail-dm6nam11olkn2019.outbound.protection.outlook.com ([40.92.19.19]:38528 helo=NAM11-DM6-obe.outbound.protection.outlook.com)
	by nw67.fcomet.com with esmtps  (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	(Exim 4.94.2)
	(envelope-from <mariefleur24@hotmail.com>)
	id 1nChF8-00FfTA-HT
	for info@autrementetalors.com; Wed, 26 Jan 2022 07:17:41 -0500
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=gE7zgqtPpt5GJZVNV3EfUtQxs3q8CvpeYxIZygCsavjk4v5InViION5P4t7eVp4rRcW1CWsMzrPAaRebrhXxQTfpDCW4mYUgnur4X86AwuocrpQSVpTkKx1KQXNkPngx/luI1DTX4ljAOpncDuC7RgBDniM89gHpYY1o/BD04dxuUI1IShu37Blmyo0D0NAxShd66GhhMs8D4EZW1bt/oydmbgRnETi1ZnMuBgyVwNKEQy7ItV7SYE4DS9/n568BMV9YGMRKkMuJneXaYOcEGs1Mak2Nol3YDl4x9WwcJ+U9cVsYPFIZAyJe9HHRokGadH16GxtY3yvbMtyvBVJH6w==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=SzRZw2Ekr/4w21Fxj/mokMsM+S4FRtoQJo4eLyXC8ig=;
 b=j1P/afqbA8VFES+W5QK2Dcp8KfGmUZvgxxoVb8OkZ2WsPZQC6W8/qWivtgZmvAM+bt18XNug7Yuq4laX6BfNIYbxOoAh4AJeiuaaOv2Wy2AdCwPtXtJmmWM8BnGRb5A+rPmk+3Ica2CDpJxRLhf3JfS9xtL3PEdmLEGF1qrxbnNhYMQn33CUJnirY2+WjkqygCuVRPhzH3QqZrhd6nbwZzEm65Vs14IRA5tsD7mRPdOxdmfJBnl9uCnsh3jupET95eikpcdj+3HFX6vCKuWuIhdB0zxRO1BQUssfMBsvbyzoyIAqK/dqXjY9xn4MQXYtYTI1fvQjt08QdT6+aHFhnw==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=none; dmarc=none;
 dkim=none; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=hotmail.com;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=SzRZw2Ekr/4w21Fxj/mokMsM+S4FRtoQJo4eLyXC8ig=;
 b=OBBa7JA+bR8PFQbSSFvgYcVirHGTAjvYiXBHosWamfn28pPBhJ4u2ayz/XDSXZr2u+Jwy9SA4vv0ZWifVDANWpBL8Lxg+2G7jK/K/z5Nd/GtgMWUZTW7+YqMx7qTGe+LWayDWrePdyq+WQ2oFYMKvVFLrZi0AyXOrNxVsz0UWLALSypadVuo0pzZXIjYC5DI6ZVHlBiRCx7CeIUEUXwCetEspGAGa/qFjPL0tIpTZiZpHtWhiIhwDa5Sc/BdzUUnL4V73HCzw7Tv/WuGVRflLr2NSNdF1ZLQM9Fgexfr7RSs9E4bjodw4a+BHiTCNs8W7ifA5dhSq38RnlWmFdStiQ==
Received: from DM6PR13MB4445.namprd13.prod.outlook.com (2603:10b6:5:1b6::8) by
 BN7PR13MB2323.namprd13.prod.outlook.com (2603:10b6:406:b7::30) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.4951.5; Wed, 26 Jan 2022 12:16:58 +0000
Received: from DM6PR13MB4445.namprd13.prod.outlook.com
 ([fe80::1dd7:68bc:9d75:73]) by DM6PR13MB4445.namprd13.prod.outlook.com
 ([fe80::1dd7:68bc:9d75:73%3]) with mapi id 15.20.4930.015; Wed, 26 Jan 2022
 12:16:58 +0000
From: marie-helene raiche <mariefleur24@hotmail.com>
To: "info@autrementetalors.com" <info@autrementetalors.com>
Subject: =?iso-8859-1?Q?=C9change_d=FB_=E0_une_mauvaise_grandeur_?=
Thread-Topic: =?iso-8859-1?Q?=C9change_d=FB_=E0_une_mauvaise_grandeur_?=
Thread-Index: AQHYEq5vK7/mJKL5EUui4PIU0t5Vqg==
Date: Wed, 26 Jan 2022 12:16:58 +0000
Message-ID:
 <DM6PR13MB44458BC8C73CF499C3E9AAACD3209@DM6PR13MB4445.namprd13.prod.outlook.com>
Accept-Language: fr-CA, en-US
Content-Language: fr-CA
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-tmn: [Qn9WmjHsMnVDAbitxWXMCzSzkBfubRWO]
x-ms-publictraffictype: Email
x-ms-office365-filtering-correlation-id: b35f1730-b203-4d48-a349-08d9e0c5c026
x-ms-traffictypediagnostic: BN7PR13MB2323:EE_
x-microsoft-antispam: BCL:0;
x-microsoft-antispam-message-info:
 kkBFoPh47QNn+8l9Hh03KndWS1ti+0Pe3ITyiRtYfTV0OoGwUHZbHFnkaXlrxhiiUQhMgH21UUcc6gN5nII32+z38xtOxqlxgD8DLR/5eib9NDcOBA0gVhc1AseucrAwd5SegwWCAImmRN8y9HyWKZOMQRp+vfShRC9fgnEM+S1Hiiu/9Jz3B0/EFm8jc3TbnpAUhr0Z+XrCP8YdU2g+wi5gY8O5vIFozwItijsDa9Y9z+bXbcy4ur+ThZPSPeMvboLb8H+7tVHAdfv+CiuzLnxM680TU/tW13l+hmcvqoiHR5pavN76jZW13rNKtx6EPbA0yS2q33Is6w4PTztWdBtr8bRlySLMBhOcCY6+N+eibD7E3rKL1BJNzfVjbUKMGANoVmQvQ8zSHDuvxS+K2s+4LZent0sLihXEJ5PS/9U32jxVNG1THN48FlFhr/V6lRNIxm7LlPEHMjA2O0hJ+wH1yldW9NJDIWWwn/T1MqEl0rrrgt5+vBiDwmz37kGNQF7G8Ir4aEVpmGvx4BQVVw3/lSSqOsH+B20F6m8jkzI8cMp+NAm4YjrR3Yac6y+2slhnGK1uxGGnmWZ35tDD1IlbSgM/4sss97HXGywI1Gv3hm3eh30CeaJZNwi8PeYR
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 =?iso-8859-1?Q?2QeXbCMlQKKB68mCtTp6aWTOhFiaEvmwlnpzQR1q3Yuq3Qvibv7KYXXkyT?=
 =?iso-8859-1?Q?blujv5G7zFyS7YebPtBUtxrWsm0z1OP+rxCY0KGBWjo8TTBFCsiOqUhvKD?=
 =?iso-8859-1?Q?z+OBa42XvSPgUAIO2DYzLezihgDTFUsoXLmd35roFm8u/q2aWcJq0m0ioQ?=
 =?iso-8859-1?Q?I5PFrE8yjV+MGevoALS7bJ3YYaNsfMJdP8KRpOeWUmttSu2ni7UHbHwPyL?=
 =?iso-8859-1?Q?mLhbrWl5HH2Iyt02tQiqKLlvLFuRxMwm1NqqAYXAHaHHMNP2oMOHI17fBm?=
 =?iso-8859-1?Q?7QyWfhV0uBgra3qZNxgrrCDpZTZPcAZdjHDhyZojwSKJFY4fBNbt5YMhAD?=
 =?iso-8859-1?Q?YnsyTmmKu/go14egiaqWUjs1JO3296qfDxbdLTObYhDi06FSVumTRlWLX5?=
 =?iso-8859-1?Q?yoAxn9tMlyuRfuD93KOAT60wmnrdHlava2wCuA7zn1aXF7Fjb/hMR6rLkX?=
 =?iso-8859-1?Q?A2ncYuoKEo92JSMsb5NJDFmmpNJFe/NidJ30dFq2TRUoInQOT+aEZHUUhV?=
 =?iso-8859-1?Q?1ZnvaB52R+7aexJYRq1beGATAlPcgts1+1P3gTjfBr0INxZL6pGNnY17/x?=
 =?iso-8859-1?Q?qSHdlLxDkk6QdONBZ/YWAfA2k6YkX+kHfGSWY9MXLj/gPgAJlO7aPeRfRN?=
 =?iso-8859-1?Q?CVOEh07TJxwZ5dXKLEZ+BmO1ii7zY6vzpqMPXgnbY6e6tU+bS97nD/Z/VN?=
 =?iso-8859-1?Q?VubXj8UIwnQO2VXvMpasIdpEs+jXZf0Y//nrgw1AmkAcINxi+Lntt3kuiI?=
 =?iso-8859-1?Q?DnOlcKkoZd/gS0LzhuhygLkeLYEWkonNAgjfAChgfDepBdTMem/jwOTY2U?=
 =?iso-8859-1?Q?GCs4fzmo/4UHSDIhacfZgVLcaObdhZT1PW4KTbxpK0TBjSDZsAseWb0XPL?=
 =?iso-8859-1?Q?Ujcm9zk+AbglMS4Tpanpyj2RuxAQr9/SVSLn0WWxkniElhUC2RGWU2YFCs?=
 =?iso-8859-1?Q?1easkp5yubeaD9FZZRtUuZIoD+LS+rWgTjveFbSGpBWIjbs9iVrzpFL7cp?=
 =?iso-8859-1?Q?Zlyd3HSKfoBUAqMps=3D?=
Content-Type: multipart/alternative;
	boundary="_000_DM6PR13MB44458BC8C73CF499C3E9AAACD3209DM6PR13MB4445namp_"
MIME-Version: 1.0
X-OriginatorOrg: sct-15-20-4778-2-msonline-outlook-da780.templateTenant
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: DM6PR13MB4445.namprd13.prod.outlook.com
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-CrossTenant-Network-Message-Id: b35f1730-b203-4d48-a349-08d9e0c5c026
X-MS-Exchange-CrossTenant-originalarrivaltime: 26 Jan 2022 12:16:58.6103
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-rms-persistedconsumerorg: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BN7PR13MB2323
X-Spam-Status: No, score=-1.8
X-Spam-Score: -17
X-Spam-Bar: -
X-Ham-Report: Spam detection software, running on the system "nw67.fcomet.com",
 has NOT identified this incoming email as spam.  The original
 message has been attached to this so you can view it or label
 similar future email.  If you have any questions, see
 root\@localhost for details.
 Content preview:  Je sous changer la grandeur de 2 tuques reçus hier. Est ce
    que je dois fournir un papier ? Ou est ce que j'inscris le changement de
   grandeur? Télécharger Outlook pour Android<https://aka.ms/AAb9ysg> Je sous
    changer la grandeur de 2 tuques reÃ§us hier. Est ce que je dois fournir un
    papier ? 
 Content analysis details:   (-1.8 points, 5.0 required)
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0002]
 -0.0 SPF_HELO_PASS          SPF: HELO matches SPF record
  0.2 FREEMAIL_ENVFROM_END_DIGIT Envelope-from freemail username ends
                             in digit
                             [mariefleur24[at]hotmail.com]
  0.0 FREEMAIL_FROM          Sender email is commonly abused enduser mail
                             provider
                             [mariefleur24[at]hotmail.com]
 -0.0 SPF_PASS               SPF: sender matches SPF record
  0.0 HTML_MESSAGE           BODY: HTML included in message
 -0.1 DKIM_VALID             Message has at least one valid DKIM or DK signature
 -0.1 DKIM_VALID_EF          Message has a valid DKIM or DK signature from
                             envelope-from domain
  0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily
                             valid
 -0.1 DKIM_VALID_AU          Message has a valid DKIM or DK signature from
                             author's domain
  0.0 KAM_SHORT              Use of a URL Shortener for very short URL
X-Spam-Flag: NO

--_000_DM6PR13MB44458BC8C73CF499C3E9AAACD3209DM6PR13MB4445namp_
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Je sous changer la grandeur de 2 tuques re=E7us hier. Est ce que je dois fo=
urnir un papier ?
Ou est ce que j'inscris le changement de grandeur?

T=E9l=E9charger Outlook pour Android<https://aka.ms/AAb9ysg>

--_000_DM6PR13MB44458BC8C73CF499C3E9AAACD3209DM6PR13MB4445namp_
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
</head>
<body>
<div dir=3D"auto" style=3D"color: rgb(33, 33, 33); background-color: rgb(25=
5, 255, 255);">
Je sous changer la grandeur de 2 tuques re=E7us hier. Est ce que je dois fo=
urnir un papier ?&nbsp;&nbsp;</div>
<div dir=3D"auto" style=3D"color: rgb(33, 33, 33); background-color: rgb(25=
5, 255, 255);">
Ou est ce que j'inscris le changement de grandeur?</div>
<div id=3D"ms-outlook-mobile-signature" dir=3D"auto">
<div><br>
</div>
T=E9l=E9charger <a href=3D"https://aka.ms/AAb9ysg">Outlook pour Android</a>=
</div>
</body>
</html>

--_000_DM6PR13MB44458BC8C73CF499C3E9AAACD3209DM6PR13MB4445namp_--`

### Expected behavior

Email messages should be ingested and be readable in the Customer Service UI.
Erroneous messages should be discarded and not result in the creation of multiple 'shadow' threads or messages

### Steps to reproduce

Go to Customer Service
Enter credential to IMAP server
Set settings as per below (with your own server and creds)
[SCREENSHOT DELETED, PLEASE DO NOT SHARE YOUR CREDENTIALS]
Click on sync until it reads error with 'Empty Message'
Read content of ps_customer_thread and look for discrepancy in number of threads and open msg vs UI

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.2

**Comment by kpodemski** [comment] 2022-02-01 08:10
Hello @pcusteau 

I've deleted the screenshot from your message. Please do not share credentials to your email account :-)

Make sure to change the password to your inbox.

**Comment by pcusteau** [comment] 2022-02-01 12:02
Thanks - these had been changed prior to posting but I still should have obfuscated them.

**Comment by marwachelly** [comment] 2022-02-01 15:01
hello @pcusteau 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #[25860](https://github.com/PrestaShop/PrestaShop/issues/25860). 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment] 2022-02-01 15:02
Duplicate of #25860

**Closed as completed** 2022-02-01 15:02 UTC
Labels: Bug, Duplicate

**Comment by pcusteau** [comment] 2022-02-01 15:25
@marwachelly I fail to see the relationship between this issue and #25869 as you can clearly see there is a date field in the sample email that was causing my issue (in the bug description). Can you please elaborate on your reasoning and help me understand the connection?

**Comment by marwachelly** [comment] 2022-02-03 19:44
> @marwachelly I fail to see the relationship between this issue and #25869 as you can clearly see there is a date field in the sample email that was causing my issue (in the bug description). Can you please elaborate on your reasoning and help me understand the connection?

Could you please check https://github.com/PrestaShop/PrestaShop/issues/25860 ans not #25869. Following the steps to reproduce the bug It seems that it is the same issue.

**Comment by pcusteau** [comment] 2022-02-03 20:17
> > @marwachelly I fail to see the relationship between this issue and #25869 as you can clearly see there is a date field in the sample email that was causing my issue (in the bug description). Can you please elaborate on your reasoning and help me understand the connection?
> 
> Could you please check #25860 ans not #25869. Following the steps to reproduce the bug It seems that it is the same issue.

It is indeed #25860 I was referring to. The behavior is different as problematic emails do have a date in them and the error message is to the effect of empty email messages.
