### ISSUE TITLE
Out of stock  bug

### ISSUE THREAD

**Issue by xiaoyuan1998** [PrestaShop/PrestaShop#16092] opened 2019-10-23 15:43 UTC
when the product out of sotck, ps display well:

![image](https://user-images.githubusercontent.com/7703076/67410379-4f9f2f80-f5bc-11e9-90f2-6e445122f1dc.png)

https://maison-des-meches.fr/perruque-lisse/front-lace-wig-remy-100-cheveux-naturels-coupe-bob

when there is the last article,   ps display well: 
![image](https://user-images.githubusercontent.com/7703076/67409924-8f194c00-f5bb-11e9-9b13-cd26f99d2255.png)

https://maison-des-meches.fr/perruque-lisse/front-lace-wig-remy-100-cheveux-naturels-coupe-bob

but when there is the last article, we choose more than 1 article, there are nothing dispaly, i dont konw it is a bug or a new feature to add, but i think we should display the same message as produt out of stock

![image](https://user-images.githubusercontent.com/7703076/67410538-8aa16300-f5bc-11e9-9edb-a615f4781cdc.png)

**Additional information**
PrestaShop version: 1.7.4

**Comment by khouloudbelguith** [comment] 2019-10-23 15:51
Hi @xiaoyuan1998,

I did not manage to reproduce the issue with PS1.7.6.1.
>but when there is the last article, we choose more than 1 article, there are nothing dispaly, i dont konw it is a bug or a new feature to add, but i think we should display the same message as produt out of stock

The button "Add to cart" will be displayed & the message "There are not enough products in stock" should be displayed.
I attached a screen record
https://drive.google.com/file/d/1rRlxeh7GEYqVUiH8KxnL5x6esfqeK9v8/view

PS: in the BO => Shop Parameters => Product Settings => "Display remaining quantities when the quantity is lower than" = 3
![image](https://user-images.githubusercontent.com/16067358/67411290-afe2a100-f5bd-11e9-889f-e189b23f087f.png)


Thanks!

**Comment by xiaoyuan1998** [comment] 2019-10-24 09:58
@khouloudbelguith     hi, could you reshare the  screen record?  cause i cant open https://drive.google.com/file/d/1rRlxeh7GEYqVUiH8KxnL5x6esfqeK9v8/view

**Comment by khouloudbelguith** [comment] 2019-10-24 10:24
@xiaoyuan1998,
[product B.webm.zip](https://github.com/PrestaShop/PrestaShop/files/3767009/product.B.webm.zip)

Thanks!

**Comment by xiaoyuan1998** [comment] 2019-10-24 10:37
@khouloudbelguith   i see it,  merci :) 
my pb is with this configuration, the message will not display
could you test it?
![image](https://user-images.githubusercontent.com/7703076/67477630-cbe85000-f65a-11e9-84a9-24c9d8cc4b66.png)

**Comment by khouloudbelguith** [comment] 2019-10-24 10:49
@xiaoyuan1998, I did not manage to reproduce the issue with ps1.7.6.1.
I attached a screen record
[Untitled_ Oct 24, 2019 12_47 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/3767090/Untitled_.Oct.24.2019.12_47.PM.webm.zip)
Thanks to check & feedback.

**Comment by xiaoyuan1998** [comment] 2019-10-24 12:28
@khouloudbelguith   your disney produt is so cute :)
you did not do the right test that i mean, could you pls set the product as quantity 1, 
and then try to choose 3 product,  in this condition, the message do not display.

**Comment by khouloudbelguith** [comment] 2019-10-24 13:58
@xiaoyuan1998, it is OK in my side
https://drive.google.com/file/d/172kP2vTMe56kuPp3b_mP3pSKsjz3woAE/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-25 07:35
Hi @xiaoyuan1998,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-25 07:35 UTC
Labels: Bug, FO, No change required
