### ISSUE TITLE
Edit imported products

### ISSUE THREAD

**Issue by pedroideavity** [PrestaShop/PrestaShop#34460] opened 2023-11-03 12:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I create products through the csv import
Now i want to edit a product and add images and is not possible.

If i create a new product through the backoffice, i can do everything 

https://prnt.sc/b3YkGcEGY6DG

### Expected behavior

the possobiliy to edit the imported products

### Steps to reproduce

Import products through the csv importation
Try to edit and save a product modification (descriptions, summary, images,...)

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2023-11-03 13:03
@pedroideavity What does it mean "not possible"? Throws some error? If you press F12, are there any errors in console?

**Comment by pedroideavity** [comment] 2023-11-03 13:11
This is the error when i open the product to edit
![Captura de ecrã 2023-11-03 130751](https://github.com/PrestaShop/PrestaShop/assets/54036996/37e79a6b-e3ae-4377-b708-bcc879c45abd)

The button to save and cancel are inactive. The button to manage the images gives the same error above

There is an error only on the imported products

**Comment by Hlavtox** [comment] 2023-11-03 13:13
Oh, ok, so you get the same issue as here - https://github.com/PrestaShop/PrestaShop/issues/34347 and https://github.com/PrestaShop/PrestaShop/issues/34342

**Comment by pedroideavity** [comment] 2023-11-03 14:01
There is no solution yet?

**Comment by florine2623** [comment] 2023-11-03 14:06
No sorry. As your issue is a duplicate of those above, you can subscribe to them to see whenever a fix will be posted.
I'm closing your issue to avoid clogging the backlog.

**Closed as completed by florine2623** 2023-11-03 14:06 UTC
Labels: Bug, BO, Duplicate, Import / Export, 8.1.x
