### ISSUE TITLE
Incorrect "availability" for Schema markup tag when stock is not managed

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#28552] opened 2022-05-20 11:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It's displayed `"availability": "https://schema.org/PreOrder"` for a store where stock is not managed.

### Expected behavior

It should display `"availability": "https://schema.org/InStock"`.

### Steps to reproduce

1. Set `0` or negative stock for a product and enable out of stock orders.

2. Disable `Enable stock management` in `Shop Parameters -> Product Settings`.
![image](https://user-images.githubusercontent.com/15104724/169516610-fc16ef70-d258-4ec3-8806-05a86edbecf5.png)

3. Open this product in the FO and check the source code.
4. Search for `availability` markup.

The problem is from this function: https://github.com/PrestaShop/PrestaShop/blob/b60ade2af5fad9cef0c8dd0f248f72c4cd16761c/src/Adapter/Presenter/Product/ProductLazyArray.php#L389-L401

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by hibatallahAouadni** [comment] 2022-05-20 15:48
Hello @idnovate 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23534. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-05-20 15:48
Duplicate of #23534

**Closed as completed by hibatallahAouadni** 2022-05-20 15:48 UTC
Labels: Bug, Duplicate, Invalid
