### ISSUE TITLE
Notification area shows an HTML code instead of a link

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#31361] opened 2023-02-14 16:05 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have just installed a fresh PS 8.0.1 for testing. After installation I went to the back office and noticed a notification. The notification looks like this after opening. I think this message should be a bolded link instead of the HTML code. This bug appears on Microsoft Edge, Google Chrome and Mozilla Firefox.

![notification](https://user-images.githubusercontent.com/48493952/218791036-7aa03f67-93d6-4ce9-aca1-e9fc33c7ced3.jpg)

Here are my specs

Server information: Linux #1 SMP Mon Dec 12 07:06:14 EST 2022 x86_64
Server software version: Apache
PHP version: 8.1.13
Memory limit: 512M
Max execution time: 120
Upload Max File size: 200M
MySQL version: 10.4.27-MariaDB-cll-lve
PrestaShop version: 8.0.1

EDIT
I am just importing data using built-in Import section. It appears that the progress bar have the same issue

![image](https://user-images.githubusercontent.com/48493952/219097306-5db956f2-569d-4f37-885c-fe9c8e44eb52.png)

### Steps to reproduce

1. Install fresh PS 8.0.1
2. Go to the back office and open a notification on the right corner

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.13

**Comment by hibatallahAouadni** [comment] 2023-02-16 02:41
Hello @banan44 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #31268. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-02-16 02:41
Duplicate of #31268

**Closed as completed by hibatallahAouadni** 2023-02-16 02:41 UTC
Labels: Bug, Duplicate, Invalid
