### ISSUE TITLE
In invoice, '?' display instead of currency symbol when we choose different language and currency

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#12308] opened 2019-01-25 12:26 UTC
**Describe the bug**
When we select different language and currency (Like, select French as a language and INR as currency.) and do an order with bankwire module and we have enabled the invoice on bankwire then the invoice will be generated on awaiting bank buyer with '?' instead of symbols.  

**To Reproduce**
1. On awaiting bank wire order status enable invoice.
2. Go on the front end and choose French as a language and INR as a currency
3. Add any product to cart and do order with bankwire payment option.
4. Now open the mail and check the invoice.

**Screenshots**
![invoice](https://user-images.githubusercontent.com/39614089/51745918-6d417600-20ca-11e9-95a8-61c549b79b99.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-01-25 13:13
Hi @PeeyushAgrawalWebkul,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/51747969-47f13f80-20ab-11e9-8307-37fb350ef216.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Related to: #9817
Thanks!

**Comment by neonVoice** [comment] 2020-11-22 15:52
I encountered the same problem with 1.7.6.8 version, my russian currency symbol `₽` was displaying as an `empty box` or `box with question mark`, i tried all default fonts from tcpdf fonts folder `\vendor\tecnickcom\tcpdf\fonts` where you needed to change font name in `\classes\pdf\PDFGenerator.php` file in `$font_by_lang` variable for your ISO, howevery in my situation only this list of fonts displayed russian ruble symbol, but they also added extra space inbetween each character which wasnt satisfactory for me.

- cid0cs
- cid0ct
- cid0jp
- cid0kr
- hysmyeongjostdmedium
- kozgopromedium
- kozminproregular
- msungstdlight
- stsongstdlight

So i decided to dig a little deeper, and according to tcpdf manual, you can import ttf font programmatically using `addTTFFont` function, it will convert your font and place in into fonts folder automaticaly, however i didnt done it, because i also found this: `\vendor\tecnickcom\tcpdf\tools\tcpdf_addfont.php`. This is command line script specifically for the purpose of adding new font to the fonts folder.

I found font with russian ruble glyph, downloaded it, placed `.ttf` file near `tcpdf_addfont.php` file and executed command `php tcpdf_addfont.php -i <fontname>.ttf`. It successfully executed and imported my fresh font to fonts folder. I must mention that i already tried online converter at `https://www.xml-convert.com/en/convert-tff-font-to-afm-pfa-fpdf-tcpdf` with the same font but it didnt work. At the end when i tried to compare generated `<fontname>.php` files from site and this utility i noticed that site generates font as TrueType, but in my case utility generated it as TrueTypeUnicode.

**Comment by khouloudbelguith** [comment] 2020-11-25 14:25
Hi!

I manage to reproduce the issue with PS1.7.7.0finalbuild1
![image](https://user-images.githubusercontent.com/16067358/100240069-6f78f380-2f32-11eb-977c-3d372fd98ffe.png)

Thanks!

**Comment by florine2623** [comment] 2024-11-27 09:09
Hello ,

This issue is fixed on PS 9.0.0.

![Image](https://github.com/user-attachments/assets/fa319ae8-00b6-414d-8b6f-78d8383ca9d9)

So I'm closing your issue.
Thanks!

**Closed as completed by florine2623** 2024-11-27 09:09 UTC
Labels: Bug, Minor, International, Invoices, Translations, Fixed, 1.7.5.0, 1.7.6.0, 1.7.7.0

**Comment by calebrio02** [comment] 2025-04-02 00:33
I was having the same issue with colones. 

![Image](https://github.com/user-attachments/assets/6f1f8c96-98b5-4a75-ae38-478b8ddd9aa0)


As a workaround i found that changing the font of the pdf generator solve the issue

/var/www/html/classes/pdf/PDFGenerator.php

from: protected $font = 'helvetica';
 to: protected $font = 'freesans';

![Image](https://github.com/user-attachments/assets/c080d105-b7dd-463c-a889-589c6d7d2098)
