### ISSUE TITLE
wrong element direction in RTL back-office

### ISSUE THREAD

**Issue by shahin0x** [PrestaShop/PrestaShop#11403] opened 2018-11-15 12:13 UTC
**Describe the bug**
according to the images, direction of pointing element is not correct
1) arrow of popover box when click on help box
2) direction of arrow in stocks page when quantity is changing

**To Reproduce**
issue#1
1. Use RTL Language( e.g Persian) as BO language
2. Go to Catalog -> Products
3. Click on New Product
4. Click on one of help-box

issue#2
1. Use RTL Language( e.g Persian) as BO language
2. Go to Catalog -> Stocks
3. Try Edit quantity 

**Screenshots**
![screenshot 14](https://user-images.githubusercontent.com/45041106/48552020-77860d80-e8ec-11e8-9311-a25ca043e6c7.png)
![screenshot 15](https://user-images.githubusercontent.com/45041106/48552025-7c4ac180-e8ec-11e8-9bb4-4e57319ae5c7.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-11-15 13:29
Hi @shahin0x,

Thanks for your report.
I manage to reproduce issues with 1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/48555911-c4fd7d00-e8e2-11e8-968c-5e25ed143368.png)
![image](https://user-images.githubusercontent.com/16067358/48555919-c7f86d80-e8e2-11e8-908a-6f4cbf66eccb.png)
We will see how to fix it.
Thanks!

**Comment by shahin0x** [comment] 2018-11-15 16:36
I found two more problems @khouloudbelguith 
Check boxes are in Catalog -> Products
![catalog](https://user-images.githubusercontent.com/45041106/48567257-dca02a00-e911-11e8-99ca-5dbc85e00320.jpg)

**Comment by khouloudbelguith** [comment] 2018-11-15 16:38
@shahin0x, thanks!
I have the same issue with PS 1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/48567438-4eba4400-e8fd-11e8-9933-a6a9c9235a40.png)

**Comment by shahin0x** [comment] 2018-11-15 16:50
these will be fixed in next version of PS? @khouloudbelguith

**Comment by khouloudbelguith** [comment] 2018-11-15 16:54
Hi @shahin0x,

Our developer team should discuss & decide about the fix version.
Thanks for your understanding!

**Comment by shahin0x** [comment] 2018-11-15 16:57
> Hi @shahin0x,
> 
> Our developer team should discuss & decide about the fix version.
> Thanks for your understanding!

Thanks to you and to your developer team.

**Comment by jolelievre** [comment] 2019-01-30 18:20
Hi @shahin0x 
this PR fixes a few RTL linked bugs https://github.com/PrestaShop/PrestaShop/pull/12370
The popover is only partially fixed, seems like the problem is fixed in Bootstrap 4, but we use Bootstrap 3 which doesn't manage well the popover with RTL direction
The fix I proposed is more like a workaround:

<img width="1206" alt="capture d ecran 2019-01-30 a 19 16 06" src="https://user-images.githubusercontent.com/13801017/52003105-f9d1a700-24c3-11e9-9fa3-53485f9fce16.png">

It is far from perfect, but I think it's better than no visible popover at all.

**Closed as completed** 2019-02-04 10:21 UTC
Labels: Bug, Minor, BO, International, Fixed
