### ISSUE TITLE
Module manager empty when connected to Addons

### ISSUE THREAD

**Issue by BeReal86** [PrestaShop/PrestaShop#20506] opened 2020-08-08 15:16 UTC
Hi,
Prestashop version 1.7.6.7

When I enter the module management section, the locations of the modules are shown separately. But when I connect to the prestashaop market, most of the module categories do not seem to exist.

https://drive.google.com/file/d/1dpbTLiIOoR9mTUqDIup3W0hsA_qJbd1u/view

the same problem exists with updates. Updates are 0 when logged in Upon logout, existing updates come back.

https://drive.google.com/file/d/1p3tLva7bFZkQrmMA1criqyC7FLcCYJm6/view

**Comment by elboletaire** [comment] 2020-08-08 15:53
Is it a fresh install? You may need to upgrade the `ps_mbo` module.

Edit: Sorry I understood it wrong. I also had that issue on 1.7.6 and, after upgrading to 1.7.7 (and also upgrading ps_mbo module, which in part caused my confusion) now the problem is gone.

**Comment by Matt75** [comment] 2020-08-08 16:20
Not related to module `ps_mbo`, this module does not manage the Module Manager.
This module manage only Module Selection, Theme Catalog and recommended modules.

**Comment by elboletaire** [comment] 2020-08-08 17:22
> Not related to module ps_mbo, this module does not manage the Module Manager.

As said, was my mistake :upside_down_face:

**Comment by khouloudbelguith** [comment] 2020-08-10 08:31
Hi @elboletaire,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1KZ8YJK2gyrcrE7jmoI-1aw4MXaAKoZAx/view?usp=sharing
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by SimonGrn** [comment] 2020-08-10 09:06
Hello @BeReal86 

it seems connecting to Addons completely break the module manager. What is the account you're using in the video ? Does it happen with another account too ?

**Comment by BeReal86** [comment] 2020-08-10 09:47
Hello @SimonGrn @khouloudbelguith 

I'm experimenting in two different places. my first attempts on xampp then on a hosting site.
Server information Windows NT build 19041 (Windows 10) AMD64
Server software version: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.2.32
PHP version: 7.2.32 
MySQL version: 10.4.13-MariaDB 

<img width="531" alt="Screenshot_12" src="https://user-images.githubusercontent.com/16218107/89767697-22981b00-db03-11ea-9149-e6c6fd26bdcb.png">

only this problem happened during the installation. Other than that, the setup was provided and the same errors occurred. define ('_ PS_MODE_DEV_', false); And change it to:define ('_ PS_MODE_DEV_', true);
started working correctly after the operation. This time, it failed while logging into the market, and sometimes it provided fewer impressions instead of 9 updates.

XAMPP
<img width="993" alt="Screenshot_13" src="https://user-images.githubusercontent.com/16218107/89769124-4fe5c880-db05-11ea-8040-536b2322d753.png">
<img width="1896" alt="Screenshot_16" src="https://user-images.githubusercontent.com/16218107/89769199-68ee7980-db05-11ea-970a-969ca950dcc0.png">
<img width="1001" alt="Screenshot_17" src="https://user-images.githubusercontent.com/16218107/89769205-6b50d380-db05-11ea-8ad4-7bb8fa2b5923.png">
<img width="1020" alt="Screenshot_18" src="https://user-images.githubusercontent.com/16218107/89769207-6b50d380-db05-11ea-8c66-318604d93c23.png">
<img width="1908" alt="Screenshot_19" src="https://user-images.githubusercontent.com/16218107/89769209-6c820080-db05-11ea-8572-6bfd26295517.png">
[dev.log](https://github.com/PrestaShop/PrestaShop/files/5049994/dev.log)
[error.log](https://github.com/PrestaShop/PrestaShop/files/5050001/error.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/5050002/prod.log)



Hosting
<img width="723" alt="Screenshot_3 png 4fa4eca1089b7a6867dcd6fdba58408d" src="https://user-images.githubusercontent.com/16218107/89770577-a7853380-db07-11ea-9f7c-78fe7e4f76c2.png">
<img width="508" alt="Screenshot_1 png b062729dc6c4b0e0decd73584bff2c9c" src="https://user-images.githubusercontent.com/16218107/89770581-a81dca00-db07-11ea-88ec-5a547ed708b5.png">

<img width="497" alt="Screenshot_14" src="https://user-images.githubusercontent.com/16218107/89769722-4dd03980-db06-11ea-9ee7-b13023eab8b5.png">
<img width="1175" alt="Screenshot_15" src="https://user-images.githubusercontent.com/16218107/89769723-4e68d000-db06-11ea-8352-474bbbbecab2.png">

[dev.log](https://github.com/PrestaShop/PrestaShop/files/5050093/dev.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/5050095/prod.log)

[error_log.zip](https://github.com/PrestaShop/PrestaShop/files/5050094/error_log.zip)



I will clean install again for hosting.

I can share my information privately or you can connect to my computer and take a closer look at the problem.

**Comment by Matt75** [comment] 2020-08-10 09:56
@BeReal86 Caution, your password is visible on your screenshot in the url of Addons Webservices. ⚠️
Please change your password on this account and others accounts where you use same password.

**Comment by BeReal86** [comment] 2020-08-10 10:04
@Matt75  Thanks, I apologize for not being careful. I changed my password.

**Comment by khouloudbelguith** [comment] 2020-08-10 11:13
Hi @BeReal86,

About this error
`[2020-08-10 12:24:40] php.CRITICAL: Uncaught Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php72) failed: Permission denied (13) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php72) failed: Permission denied (13) at /home/cetinaau/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php:101)"} []`

This is a server issue, you need to check with your host.

>define ('_ PS_MODE_DEV_', false); And change it to:define ('_ PS_MODE_DEV_', true); started working correctly after the operation. 

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks to check and feedback.

**Comment by BeReal86** [comment] 2020-08-10 12:00
after a clean install and reset all everything
I mentioned before, I don't know why it stems. but after installation I chose Turkey as the country stands out in my installation white pages.
setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');  to do //setlocale(LC_CTYPE, $locale.'.UTF-8', $locale.'.utf8');
After changing the code, the problem is solved as in the video. Is this a problematic act?
I uploaded the Error Log file.
[error_log.zip](https://github.com/PrestaShop/PrestaShop/files/5050673/error_log.zip)


https://drive.google.com/file/d/1L9g0D2DkMzB__SXAJLgEWEnC2buZI_HR/view

As you can see in the video in the second part, there was a problem once, then I did not have any problems. no problem for now.

https://drive.google.com/file/d/1672TL2DFJInDVVEjGsrUpnohe8S783ZO/view

**Comment by sarahdib** [comment] 2020-08-10 12:04
Hello @BeReal86 

Thank you for your feedback. 

I close this issue feel free to open a new one!

Thanks!

**Closed as completed** 2020-08-10 12:05 UTC
Labels: Bug, BO, No change required, Module manager, 1.7.6.7
