### ISSUE TITLE
The close button is not working in the upload module modal

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#33629] opened 2023-08-16 09:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the upload module modal (for expl ps_facetedsearch module), the close button is not working

![Module-manager-•-PrestaShop](https://github.com/PrestaShop/PrestaShop/assets/24647495/01cf72b9-5541-49cb-beda-3e9b99c4f0be)

### Expected behavior

In the upload module modal (for expl ps_facetedsearch module), when we click on the the close button, the modal should be closed.

### Steps to reproduce

1. Download the module 'ps-facetedsearch' from here => 'https://github.com/PrestaShop/ps_facetedsearch/releases/download/v3.12.1/ps_facetedsearch.zip'
2. Go to 'Modules > Module manager' page
3. Uninstall and delete the module 'ps-facetedsearch'
4. Upload the downloaded module
5. Try to close the modal => See the error

=> See attached screenvideo
https://watch.screencastify.com/v/tVyAU2Yfa74gGMId7pWp

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment] 2023-08-16 09:24
Hello @nesrineabdmouleh 

Thank you for submitting this issue.
I reproduce the issue with develop 

https://github.com/PrestaShop/PrestaShop/assets/31663369/86d94b8c-243f-4940-9f84-0014c9af84f4


and with 81x 

https://github.com/PrestaShop/PrestaShop/assets/31663369/d4d787d2-5308-411d-b337-e194432cb323

Thank you !

**Comment by matks** [comment] 2023-08-16 13:21
I reproduce the issue. I have a JavaScript error `Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')`
![Capture d’écran 2023-08-16 à 15 20 43](https://github.com/PrestaShop/PrestaShop/assets/3830050/0a80d650-6405-4fcb-8c3a-5f7da8770e2b)

**Comment by matks** [comment] 2023-08-16 14:12
It seems `updateModuleStatus(event)` expects a full `event` module object with data like `name`, `id` ... but is only given a simple object `{'tech-name':'...'}`. Other parameters are missing.

I think the bad event content is being given by this code https://github.com/PrestaShop/PrestaShop/pull/31285/files#diff-e7328df916ab4f26f79b085040bfe2a0e1c5a4b9f1564365371b78df89ff17d2R741
so the bug would exist since PR https://github.com/PrestaShop/PrestaShop/pull/31285/

**Comment by matks** [comment] 2023-08-18 08:57
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33643

**Closed as completed by matks** 2023-08-18 08:57 UTC
Labels: Bug, BO, Modules, Regression, PR available, Detected by TE, Verified, 8.1.x
