### ISSUE TITLE
cumulative cart_rule shows faulty in order confirmation email and in the order backoffice

### ISSUE THREAD

**Issue by ebonit** [PrestaShop/PrestaShop#12353] opened 2019-01-29 17:04 UTC
**Describe the bug**
when I add cartrules with the 'from number of products settings' and I use precentage for the discount, then the 2nd, 3rd andsodorf cartrules are cumulative in the discount calculation.
1: 10% discount from 2 products shows 10% of the sub total
2: 10% discount from 5 products shows 10% discount from (subtotal - 1st discount)
3: 10% sidcount from 8 products shows 10% discount from (subtotal - 1st&2nd discounts)

so far so good. I would like to see 30% discount in total but since it is calculated cumulative I needed to be a bit creative with the 2nd and 3rd discount percentage. see below. It would be nice though to be able to check cumulative or not but okay, I can accept this. I have 'about' 30% discount
![schermafbeelding 2019-01-29 om 15 14 04](https://user-images.githubusercontent.com/13302588/51914913-3032f780-23da-11e9-8f01-84d7a3cec03a.png)

but then, when I do this, in the order backoffice the amounts that show are not calculated cumulative
![schermafbeelding 2019-01-29 om 15 16 03](https://user-images.githubusercontent.com/13302588/51915300-0e864000-23db-11e9-9429-63bd4a22362d.png)

and in the confirmation email, the amounts are not calculated cumulative either.
![schermafbeelding 2019-01-29 om 15 33 46](https://user-images.githubusercontent.com/13302588/51915435-5c9b4380-23db-11e9-8479-1d147776ba6d.png)

**To Reproduce**
1: Go to Catalugue->Discounts
2: create 2 more more discounts
![schermafbeelding 2019-01-29 om 15 37 17](https://user-images.githubusercontent.com/13302588/51915586-c7e51580-23db-11e9-9968-47e6010457ed.png)

3 set the conditions to product selection with each there own number of products
![schermafbeelding 2019-01-29 om 15 38 56](https://user-images.githubusercontent.com/13302588/51915823-4d68c580-23dc-11e9-900e-2c2d96d6fc4b.png)

4 under Action set the discount to percentage
![schermafbeelding 2019-01-29 om 15 42 16](https://user-images.githubusercontent.com/13302588/51915955-8dc84380-23dc-11e9-8cc2-22858b0ece25.png)

5 place an order with enough products so all the discounts are used.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-01-29 17:14
Hi @ebonit,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11722
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-29 17:14
Duplicate of #11722

**Closed as completed by khouloudbelguith** 2019-01-29 17:14 UTC
Labels: Duplicate
