### ISSUE TITLE
BO - Orders - Multi-invoices - The addProductNewInvoiceInfo is not displayed when creating new invoice

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24533] opened 2021-05-17 16:06 UTC
#### Describe the bug

In the BO > Orders > Order details page, when we add a product with creating a new invoice => the `addProductNewInvoiceInfo` is not displayed
![image](https://user-images.githubusercontent.com/16067358/118520304-40ea1180-b73a-11eb-8587-29385f6b4fe8.png)

#### Expected behavior

177x we have
![image](https://user-images.githubusercontent.com/16067358/118520521-7131b000-b73a-11eb-9b26-16dcdfedbca5.png)

#### Steps to Reproduce

1. Go to BO > Orders > Orders page
2. View any demo order
3. Change status to payment accepted or generate an invoice
4. Click "Add a product"
5. Choose a product and select "Create a new invoice"
6. See error

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

**Comment by khouloudbelguith** [comment] 2021-05-17 16:07
Related to https://github.com/PrestaShop/PrestaShop/issues/24532

**Comment by PierreRambaud** [comment] 2021-05-24 10:14
Hi @khouloudbelguith 
I'm not able to reproduce the issue, the only issue I have is a button's position problem.
![image](https://user-images.githubusercontent.com/1462701/119332895-81d9ad00-bc89-11eb-9044-29351f9c9019.png)
PIng @NeOMakinG

**Comment by khouloudbelguith** [comment] 2021-05-28 13:48
Hi @PierreRambaud,

When we click "add a product", we need to choose a product, then we select to "create new invoice" => so we have the issue
![image](https://user-images.githubusercontent.com/16067358/119993695-25012e00-bfcc-11eb-993e-05372cdf7800.png)

Thank you!

**Comment by PierreRambaud** [comment] 2021-05-31 13:22
> Hi @PierreRambaud,
> 
> When we click "add a product", we need to choose a product, then we select to "create new invoice" => so we have the issue
> ![image](https://user-images.githubusercontent.com/16067358/119993695-25012e00-bfcc-11eb-993e-05372cdf7800.png)
> 
> Thank you!

I finally manage to reproduce the issue, I create a pull request to fix it

**Comment by Progi1984** [comment] 2021-06-01 08:46
Fixed by @PierreRambaud in #24718

**Closed as completed by Progi1984** 2021-06-01 08:46 UTC
Labels: Bug, Major, BO, Order, Invoices, Regression, Fixed, 1.7.8.x
