### ISSUE TITLE
form_pagination_default_order_by does not work when faceted is enabled

### ISSUE THREAD

**Issue by joelprestaworks** [PrestaShop/PrestaShop#11260] opened 2018-11-05 09:56 UTC
**Describe the bug**
The function "form_pagination_default_order_by" is not working when sorting by product quantity together with faceted-search.

**To Reproduce**
1. Enable the faceted module
2. Go to Shop parameters -> Products
3. Change pre-defined sort order to Product quantity

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2018-11-05 10:00
Hi @joelprestaworks,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9956
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-05 10:00
Duplicate of #9956

**Closed as completed by khouloudbelguith** 2018-11-05 10:00 UTC
Labels: Duplicate
