### ISSUE TITLE
Create a new client

### ISSUE THREAD

**Issue by mhd6** [PrestaShop/PrestaShop#14918] opened 2019-07-30 14:17 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-07-30 14:20
Hi @mhd6,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by mhd6** [comment] 2019-07-30 14:23
Create a new client ! version Ps 1.7.6 on the page Manage your customers it is impossible to add a customer if you do not click yes (Partner offers): Error: This field is mandatory: optin. ? Why imposed on the customer to receive advertising ?
![Capture](https://user-images.githubusercontent.com/22761869/62137516-60564700-b2e6-11e9-9e4e-3685f1ce6171.JPG)

**Comment by khouloudbelguith** [comment] 2019-07-30 14:38
@mhd6, on the customer page, Click on the option "Set required fields for this section" and unselect the Partner offers option.
![image](https://user-images.githubusercontent.com/16067358/62138730-0a7ea080-b2e0-11e9-85cd-313a85a5704c.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-08-29 07:22
Hi @mhd6,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-29 07:22 UTC
Labels: Customer, No change required
