### ISSUE TITLE
Can,t post a product review

### ISSUE THREAD

**Issue by HolAzuanet** [PrestaShop/PrestaShop#32096] opened 2023-04-10 08:46 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When selected add review, the rating stars dosnt appear, so when i click on send i got this error:

<img width="538" alt="Captura de Pantalla 2023-04-10 a las 9 42 47" src="https://user-images.githubusercontent.com/128799603/230866509-91f069ea-ddef-42f1-9753-a8ec5b69a7ca.png">
<img width="786" alt="Captura de Pantalla 2023-04-10 a las 10 41 00" src="https://user-images.githubusercontent.com/128799603/230866517-47b12e4c-ef09-49bf-901f-8dee485efe47.png">

### Steps to reproduce

1. Go to product page
2. Click on add review
3. Notice that you can't add or view rating stars
4. You got an error and your review can't be sent

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

productcomments v5.0.3

### Your company or customer's name goes here (if applicable).

dimercos.com

**Comment by hibatallahAouadni** [comment] 2023-04-12 12:21
Hello @HolAzuanet 

I didn't manage to reproduce the issue with PS1788, see the attached screenshots below:

**BO**
![image](https://user-images.githubusercontent.com/23308427/231454872-95657337-50b7-4697-8de1-2bcf89954c14.png)

**FO**
![image](https://user-images.githubusercontent.com/23308427/231454827-3c3ba25d-0a26-4f51-a261-e9337f0fc4ea.png)

Please check and feedback.

Thanks!

**Comment by florine2623** [comment] 2023-05-03 07:45
Hello @HolAzuanet ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-05-03 07:45 UTC
Labels: Bug, FO, Fixed, Productcomments, Module, 1.7.8.8
