### ISSUE TITLE
Changing the order / arranging product images doesn't work

### ISSUE THREAD

**Issue by hannes01** [PrestaShop/PrestaShop#35226] opened 2024-01-31 07:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

New product page. Moving a product image to another position doesn't work, it ends up in the same position. Tried with production site 8.1.3 and demo site 8.0.4.

![Screenshot_1](https://github.com/PrestaShop/PrestaShop/assets/17709332/b95acf7f-501c-4bf9-912a-a58cc728fbd8)
![Screenshot_2](https://github.com/PrestaShop/PrestaShop/assets/17709332/45735898-be7b-40f1-8018-cc5a43ca3202)
![Screenshot_3](https://github.com/PrestaShop/PrestaShop/assets/17709332/09abc123-39ce-455d-bc1f-48925fba2900)

### Expected behavior

The product image ends up in the new position.

### Steps to reproduce

1. Go to the new product page
2. Upload some product images
3. Try to arrange them

### PrestaShop version(s) where the bug happened

8.0.4 and 8.1.3

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-01-31 08:40
Hello @hannes01 ,

I can't reproduce your issue on 8.1.3 so I'm closing it.

https://github.com/PrestaShop/PrestaShop/assets/16019289/a40e3db8-8efc-4077-9460-9aef073b18b5

**Closed as completed by florine2623** 2024-01-31 08:40 UTC
Labels: Bug
