### ISSUE TITLE
authentification error for search cron

### ISSUE THREAD

**Issue by WorldSellers** [PrestaShop/PrestaShop#16401] opened 2019-11-13 14:29 UTC
**Describe the bug**
when i test the url of the search engine cron https://www.mysiteweb.com/wsBaOprod/index.php?controller=AdminSearch&action=searchCron&ajax=1&full=1&token=MySuperToKENNN&id_shop=1 with wget or curl,  i have an authentification error. The url is redirected on adminlogin controller and my search engine index is not updated.

**To Reproduce**
try to access on the cron url with wget or curl command line

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-11-13 14:44
Hi @WorldSellers,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15855 to fix the issue.
It fixed in PS1.7.6.2.
Your ticket is a duplicate of #15725
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-13 14:44
Duplicate of #15725

**Closed as completed by khouloudbelguith** 2019-11-13 14:44 UTC
Labels: Duplicate
