### ISSUE TITLE
Prestashop 8.1.5 CLI Installation with custom theme bug

### ISSUE THREAD

**Issue by AdrienPlx** [PrestaShop/PrestaShop#35712] opened 2024-03-21 11:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to install prestashop with a custom theme with CLI command, I have a bug on the installation when the theme is loading informations from the theme.yml : 
![image](https://github.com/PrestaShop/PrestaShop/assets/43446598/3af948ad-806c-4d3f-a94c-e9c7c1ff6b8a)

It seems that one of the modules to enable in theme.yml is not valid. I tried to reset all of these modules in the BO but all is working well. I also tried to delete the "to_enable" part in theme.yml but I have the same error ...

So the installation blocks before installing image types and the result is an error 500 on front office.

### Steps to reproduce

1. Get a custom theme from your prestashop 8.1.5 basic folder /themes/
2. Launch composer install
3. Launch install cli with option "--theme=[your_theme]"

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.27

### Your company or customer's name goes here (if applicable).

BWA - Adrien Pleux

**Comment by florine2623** [comment] 2024-03-21 13:38
Hello @AdrienPlx ,

I have followed the instructions here : https://devdocs.prestashop-project.org/8/basics/installation/advanced/install-from-cli/

I'm using the zip file for 8.1.5 : https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.5

I can't reproduce your issue.
Here's the result I have :

<img width="817" alt="Screenshot 2024-03-21 at 14 37 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b5467900-6554-4f9b-b099-2a9f4066ccf8">

##
What command are you using ? and what theme are you using ?
With classic theme, it works as expected.

**Comment by AdrienPlx** [comment] 2024-03-21 14:54
Hello ! 

Thanks for your answer.

I'm using a custom theme from our agency. 
You didn't follow exactly my instructions to reproduce it :

1. Get a custom theme and add it to your prestashop 8.1.5 basic folder "/themes/"
2. Launch composer install
**_3. Launch install cli with option "--theme=[your_custom_theme_name]"_** 

With classic theme it's working but the real problem is when I install with our custom theme (didn't have this problem before with other versions of prestashop)

**Comment by AdrienPlx** [comment] 2024-03-21 14:59
Here is what I launch to install prestashop with our theme (after getting prestashop from git and composer install)
`system( '/usr/bin/php8.1 /home/' . $user . '/www/install-dev/index_cli.php --domain=' . $domaine . '.' . $temp_url . ' --db_server=localhost --db_name=' . $user . ' --db_user=' . $user . ' --db_password=' . $password_mysql . ' --theme=bwa --email=' . $email . ' --language=fr --firstname=BWA --lastname=admin --password=' . $password);`

**Comment by florine2623** [comment] 2024-03-21 15:09
I added the [theme](https://github.com/PrestaShop/hummingbird/releases/tag/v0.1.6) to the themes folder and relaunched my command :
`php index_cli.php --domain=ps815:8888 --db_server=localhost:8889 --db_name=ps815 --db_user=root --db_password=root --prefix=ps_ --email=demo@prestashop.com --password=prestashop --theme=hummingbird`


And it works as expected :
<img width="583" alt="Screenshot 2024-03-21 at 16 08 07" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a347cedf-d5c2-41a1-aad1-daa4b08d9e3b">

**Comment by AdrienPlx** [comment] 2024-03-21 15:36
I don't know why my theme is not installing well...
I give you the theme.yml that I have :
`name: bwa
display_name: Theme BWA
version: 2.0.0
author:
    name: "BWA"
    email: "contact@bwagence.fr"
    url: "https://www.business-web-agence.com/"

meta:
    compatibility:
        from: 1.7.2.0
        to: ~

    available_layouts:
        layout-full-width:
            name: Full Width
            description: No side columns, ideal for distraction-free pages such as product pages.
        layout-both-columns:
            name: Three Columns
            description: One large central column and 2 side columns.
        layout-left-column:
            name: Two Columns, small left column
            description: Two columns with a small left column
        layout-right-column:
            name: Two Columns, small right column
            description: Two columns with a small right column

global_settings:
    configuration:
        PS_IMAGE_QUALITY: png
        PS_ALLOW_HTML_IFRAME: 1
        PS_FINAL_SUMMARY_ENABLED: 1
        PS_GUEST_CHECKOUT_ENABLED: 0
        PS_QTY_DISCOUNT_ON_COMBINATION: 1
        PS_DISPLAY_QTIES: 0
        PS_ATTRIBUTE_CATEGORY_DISPLAY: 0
        PS_PACK_STOCK_TYPE: 2
        PS_CART_FOLLOWING: 1
        PS_DISPLAY_DISCOUNT_PRICE: 0
        PS_CUSTOMER_OPTIN: 0
        PS_SMARTY_FORCE_COMPILE: 1
        PS_PRODUCT_ATTRIBUTES_IN_TITLE: 1
        PS_MAIL_THEME: bwa-modern
    modules:
        to_disable:
            - blockreassurance
            - ps_imageslider
            - ps_banner
            - ps_customtext
            - welcome
            - ps_facetedsearch
            - ps_searchbar
            - ps_linklist
            - ps_customeraccountlinks
            - productcomments
            - ps_categorytree
            - ps_supplierlist
            - ps_brandlist
        to_enable:
            - amazzingfilter
            - ambjolisearch
            - bwa_config_theme
            - bwa_head_banner
            - bwa_menu
            - bwa_responsiveslider
            - pm_advancedcookiebanner
    hooks:
        custom_hooks:
            -   name: displayMainEnd
                title: displayMainEnd
                description: Add a widget area before main closing tag
        modules_to_hook:
            displayAfterBodyOpeningTag:
                - blockreassurance
            displayNavFullWidth:
                - blockreassurance
            displayAdminCustomers:
                - blockwishlist
            displayCustomerAccount:
                - blockwishlist
                - psgdpr
            displayMyAccountBlock:
                - blockwishlist
            displayNav1:
            displayHome:
            displayNav2:
                - ps_languageselector
                - ps_currencyselector
                - ps_customersignin
                - ps_shoppingcart
            displayTop:
                - ps_mainmenu
                - ps_searchbar
            displayFooterBefore:
                - ps_emailsubscription
                - ps_socialfollow
                - blockreassurance
            displayFooter:
                - ps_customeraccountlinks
                - ps_contactinfo
                - blockwishlist
            displayFooterAfter:
                - blockreassurance
            displayFooterProduct:
                - productcomments
            displayLeftColumn:
                - amazzingfilter
            displayContactLeftColumn:
                - ps_contactinfo
            displayContactRightColumn:
                - ps_contactinfo
            displayContactContent:
                - contactform
            displaySearch:
                - ambjolisearch
            displayProductAdditionalInfo:
                - ps_sharebuttons
                - productcomments
            displayProductListReviews:
                - productcomments
            displayReassurance:
                - blockreassurance
            displayOrderConfirmation2:
                - ps_featuredproducts
            displayProductActions:
                - blockwishlist

    image_types:
        small_default:
            width: 98
            height: 98
            scope: [ products, categories, manufacturers, suppliers ]
        medium_default:
            width: 452
            height: 452
            scope: [ products, manufacturers, suppliers ]
        large_default:
            width: 800
            height: 800
            scope: [ products, manufacturers, suppliers ]
        category_default:
            width: 141
            height: 180
            scope: [ categories ]
        stores_default:
            width: 170
            height: 115
            scope: [ stores ]
        cart_default:
            width: 125
            height: 125
            scope: [ products ]
        pdt_180:
            width: 180
            height: 180
            scope: [ products ]
        home_default:
            width: 250
            height: 250
            scope: [ products ]
        pdt_300:
            width: 300
            height: 300
            scope: [ products ]
        pdt_360:
            width: 360
            height: 360
            scope: [ products ]
        pdt_540:
            width: 540
            height: 540
            scope: [ products ]

#assets:
# If you're using this theme as child and you want to load
# the parent theme assets, uncomment this line.
#  use_parent_assets: true

# The following lines are showing how to load assets in your page
# Uncomment and change value to start loading css or js files
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#  js:
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js




theme_settings:
    default_layout: layout-full-width
    layouts:
        category: layout-left-column
        best-sales: layout-left-column
        new-products: layout-left-column
        prices-drop: layout-left-column
        contact: layout-left-column
        search: layout-left-column
        module-ambjolisearch-jolisearch: layout-left-column
`

Do you see any error ? even if I completely remove the modules "to_enable" part, the error is still popin : 
`PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Le module n'est pas val          ide et ne peut pas être chargé. in /home/testmodu/www/src/Core/Addon/Theme/ThemeManager.php:398
Stack trace:
#0 /home/testmodu/www/src/Core/Addon/Theme/ThemeManager.php(255): PrestaShop\PrestaShop\Core\Addon\Theme\Them          eManager->doEnableModules()
#1 /home/testmodu/www/src/PrestaShopBundle/Install/Install.php(1178): PrestaShop\PrestaShop\Core\Addon\Theme\          ThemeManager->enable()
#2 /home/testmodu/www/install-dev/controllers/console/process.php(330): PrestaShopBundle\Install\Install->ins          tallTheme()
#3 /home/testmodu/www/install-dev/controllers/console/process.php(165): InstallControllerConsoleProcess->proc          essInstallTheme()
#4 /home/testmodu/www/install-dev/classes/controllerConsole.php(139): InstallControllerConsoleProcess->proces          s()
#5 /home/testmodu/www/install-dev/index_cli.php(57): InstallControllerConsole::execute()
#6 {main}
`

**Comment by florine2623** [comment] 2024-03-21 15:55
I'm not sure what the issue is with your module, sorry.

You can try to install your theme afterwards directly from your BO.

I suggest contacting the support.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing the issue as it cannot be reproduced with the standard items.

Thank you

**Closed as completed by florine2623** 2024-03-21 15:55 UTC
Labels: Bug, IN, 8.1.x
