### ISSUE TITLE
Negative discount generates an error

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19863] opened 2020-06-18 21:01 UTC
#### Describe the bug
Negative discount (% or amount) created manually in BO generates the error:

500 Server Error
Oops, something went wrong.
Try to refresh this page or feel free to contact us if the problem persists.

#### Expected behavior
There should be some error message if something is wrong.

#### Steps to Reproduce
1. Go to BO > Orders > Orders > select order and display detail screen
2. Go to Products and press button Add a new discount
3. Enter values:
Name: any name
Type: Percent
Value: -5
4. Press button Add => PS generates the error

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by florine2623** [comment] 2020-06-19 08:31
Hi @juraj1000 ,
You issue might be a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19113
Here's the answer for you : https://github.com/PrestaShop/PrestaShop/issues/19113#issuecomment-629200129

You are not supposed to add negative discount. Discount can't be lower than 0.
![Capture d’écran 2020-06-19 à 10 31 25](https://user-images.githubusercontent.com/16019289/85113724-0b7e3080-b218-11ea-9d91-22f18a95afc1.png)

So I'll close this issue. Thanks!

**Closed as completed by florine2623** 2020-06-19 08:31 UTC
Labels: No change required
