### ISSUE TITLE
Product images are missing when print a multiple products order

### ISSUE THREAD

**Issue by mikeKstm** [PrestaShop/PrestaShop#20296] opened 2020-07-23 11:15 UTC
#20182 ## Describe the bug

PS 1.7.6.4

If I print an order when I'm in backoffice the product images dissapear.
I think that the problem appear when the order have multiple products. When products are just one or two the product shows with no problem.

#### Expected behavior

Print product images even if you have multiple products

#### Steps to Reproduce

1. Go to Orders > Edit an order
2. Click on 'Print order' 
3. See error

**Screenshots**

https://i.imgur.com/vyhAXse.jpg
https://i.imgur.com/kWvm5gt.jpg

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment] 2020-07-23 11:41
Hi @mikeKstm ,
I can't reproduce your issue :
![Capture d’écran 2020-07-23 à 13 39 27](https://user-images.githubusercontent.com/16019289/88282509-ffd7cb00-cce9-11ea-845f-949b1e7cc8ce.png)

Is there anything special about the order/product ?
Do the products have images ?
If the product have combinations, if you don't have an image for that specific combination, it won't appear on the printed order.
Thanks!

**Comment by mikeKstm** [comment] 2020-07-23 11:48
Thanks for response. Please, try with more diferent products (I tried it with 9).
Products are simple products (not combinations) and all have a images. In BO order review the images are showed in right way.

If I change print scale the images appears. I'm using Chrome but Firefox have same problem.

https://i.imgur.com/XDI0i9a.jpg
https://i.imgur.com/qr5ax8I.jpg
https://i.imgur.com/G2fHJiM.jpg
(all images are from the same order)

Thanks

**Comment by florine2623** [comment] 2020-07-23 16:22
I still can't reproduce the issue. I have the same number of columns as well.
![Capture d’écran 2020-07-23 à 18 20 06](https://user-images.githubusercontent.com/16019289/88311491-3b39c000-cd11-11ea-908e-fd188cdad237.png)

**Comment by SimonGrn** [comment] 2020-07-23 16:44
Hello,

despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thank you

**Closed as completed by SimonGrn** 2020-07-23 16:44 UTC
Labels: BO, Order, No change required, 1.7.6.4
