### ISSUE TITLE
HTML Tags <br><em> not working during account creation after 8.0.0 / 8.0.1 upgrade

### ISSUE THREAD

**Issue by doeselschnecke** [PrestaShop/PrestaShop#30757] opened 2023-01-06 17:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bug during checkout / Account Creation:
How it looks on PS 1.7.8.6:
<img width="502" alt="Screenshot_20230106_184916" src="https://user-images.githubusercontent.com/65049045/211069613-9836be7f-6263-4bf6-9b90-bc03445f0605.png">
How it looks after upgrade to 8.0.0 or 8.0.1:
<img width="486" alt="Screenshot_20230106_184945" src="https://user-images.githubusercontent.com/65049045/211069649-c7bd05e5-f46e-4636-aef9-cd78af0281c3.png">
It does not matter if the classic theme gets upgraded or not. The issue exists in both cases.

### Expected behavior

It should be displayed correctly, like on 1.7.8

### Steps to reproduce

1. Upgrade from 1.7.8.6 to 8.0.0 or 8.0.1
2. Go to checkout

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4 and 8.0

**Comment by doeselschnecke** [comment] 2023-01-06 18:36
Upgrading 1.7.8.6 to 1.7.8.8 does not create this bug.
Upgrading 1.7.8.8 to 8.0.1 create this bug as well.

**Comment by theGera** [comment] 2023-01-07 01:20
is smarty 3.x to 4.1

in file themes/classic/templates/_partials/form-fields.tpl

`{$field.label nofilter}`  **change to** `{$field.label|unescape: "html" nofilter}`

**Comment by doeselschnecke** [comment] 2023-01-07 01:23
> is smarty 3.x to 4.1
> 
> in file themes/classic/templates/_partials/form-fields.tpl
> 
> `{$field.label nofilter}` **to** `{$field.label|unescape: "html" nofilter}`

Thanks for the answer. Is this a known bug in the classic theme? I activated the setting to upgrade the theme but apparently in the 8.0.1 included classic theme this bug still exists. Will it be fixed in 8.1.0?

**Comment by theGera** [comment] 2023-01-07 01:27
> Thanks for the answer. Is this a known bug in the classic theme? I activated the setting to upgrade the theme but apparently in the 8.0.1 included classic theme this bug still exists. Will it be fixed in 8.1.0?

I don't know, let's hope they update it soon because it is an error for most of the themes that use this variable in this way `{$field.label nofilter}`

**Comment by hibatallahAouadni** [comment] 2023-01-09 10:01
Hello @TheGera 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #29940. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-01-09 10:01
Duplicate of #29940

**Closed as completed by hibatallahAouadni** 2023-01-09 10:01 UTC
Labels: Bug, Duplicate, Invalid
