### ISSUE TITLE
Critical error adding product pack into backoffice order

### ISSUE THREAD

**Issue by paolobattistella** [PrestaShop/PrestaShop#23141] opened 2021-02-04 15:51 UTC
#### Describe the bug
I'm trying to create an order into backoffice. I have added a product pack but the autocomplete search returns this error below.

I have resolved the issue adding cast to 7th argument creating the object FoundProduct.
See the wrong line of code.
https://github.com/PrestaShop/PrestaShop/blob/d53f819953eceac5e9c362a400110f50bcc7313d/src/Adapter/Product/QueryHandler/SearchProductsHandler.php#L199

#### Steps to reproduce

1. Go to BO>SELL>Products
2. Create a product
3. ...

**Screenshots**
`
Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 7 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\FoundProduct::__construct() must be of the type int, string given, called in /var/www/html/src/Adapter/Product/QueryHandler/SearchProductsHandler.php on line 177" at /var/www/html/src/Core/Domain/Product/QueryResult/FoundProduct.php line 102 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 7 passed to PrestaShop\\PrestaShop\\Core\\Domain\\Product\\QueryResult\\FoundProduct::__construct() must be of the type int, string given, called in /var/www/html/src/Adapter/Product/QueryHandler/SearchProductsHandler.php on line 177 at /var/www/html/src/Core/Domain/Product/QueryResult/FoundProduct.php:102)"} []
`
#### Additional infos

- Prestashop version: 1.7.7.0
- PHP version:

**Comment by hibatallahAouadni** [comment] 2021-02-04 17:23
Hello @paolobattistella 

could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- steps to reproduce
- PHP version
- did you upgrade your shop lately, if so what was your shop version
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by matks** [comment] 2021-02-04 17:29
@paolobattistella it is likely the issue only happens for specific kind of products. Our tests with "regular" pack products did not indicate issues but you might have found an edgecase. Can you describe as much as possible what kind of products you sell? Do you use attributes? Custom fields? Attachments?

**Comment by hibatallahAouadni** [comment] 2021-02-24 13:09
Hello @paolobattistella ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-24 13:09 UTC
Labels: Bug, BO, Pack, No change required, 1.7.7.0
