### ISSUE TITLE
Faceted Search Cannot rebuild price index

### ISSUE THREAD

**Issue by tromarek1** [PrestaShop/PrestaShop#25294] opened 2021-07-09 08:21 UTC
When I click on rebuild price:
![image](https://user-images.githubusercontent.com/5338931/125047244-12841500-e09f-11eb-94c3-6a191d622f6b.png)
module throws an error. When I go to CRON job link: ERROR 500.

1. Go to 'Modules > Faceted Search'
2. Click on 'Rebuild price index'
3. See error

PrestaShop version: 1.7.7.5
Faceted search version: 3.7.1

**Comment by khouloudbelguith** [comment] 2021-07-09 09:41
Hi @tromarek1,

Thanks for your issue.
I did not manage to reproduce the issue with PS1.7.7.5 and ps_facetesearch v3.7.1.
I attached a screen record
https://drive.google.com/file/d/1JIQgnLwGzQQ_Ocpyv5NDeighgxptii9d/view?usp=sharing
What is the exact version of the ps_facetedsearch module did you use?
What is the exact language & currency did you use in the BO?

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-29 08:33
Hello @tromarek1 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-29 08:33 UTC
Labels: Bug, BO, Faceted search, No change required, 1.7.7.5
