### ISSUE TITLE
Faceted search : Ordering + Filtering does not work

### ISSUE THREAD

**Issue by hugolin69** [PrestaShop/PrestaShop#25884] opened 2021-09-15 10:00 UTC
### Describe the bug
In the category page, If I add a filter **after** having changing the order, the filter does not applies.

### Expected behavior
I should have the order AND the filter working.

### Steps to Reproduce
If I try to filter with an option and after that change the order, it works. 
I got this URL : https://www.site.com/20-category?q=Largeur-60+cm&order=product.price.asc

If I try to first change the order (Order by price for example), and then filter, it does not work.
I got this URL : https://www.site.com/20-category?order=product.price.asc&amp%3Bq=Largeur-60+cm

I see it tries to convert the URL with the &amp%3B but I do not know where I can correct this.

### How to solve
Seems it comes from the $filter.nextEncodedFacetsURL in facets.tpl, that arrives already encoded.
I just changed it to {$filter.nextEncodedFacetsURL|unescape}, addind the unescape, to convert it to a real url and it seems to work.

### Additional information
Prestashop 1.7.6.9
Faceted search 3.7.1

**Comment by florine2623** [comment] 2021-09-15 13:01
Hello @hugolin69 ,

Is your issue related to : https://github.com/PrestaShop/PrestaShop/issues/19810 ?

Please edit your issue and follow the bug template :
<img width="636" alt="Screenshot 2021-09-15 at 15 01 17" src="https://user-images.githubusercontent.com/16019289/133438030-c4c9a742-70f1-42c9-8975-779527115809.png">
Thanks

**Comment by hugolin69** [comment] 2021-09-15 14:36
I thing I found the solution adding unescape to smarty variable {$filter.nextEncodedFacetsURL|unescape}
Nobody reached this problem ?

**Comment by florine2623** [comment] 2021-09-15 15:06
Hello @hugolin69 ,

Thanks for the update !

Have you checked issue #19810 ? It seems to be the same problem as yours. If that's the case you can create a PR in order to fix that issue !

**Comment by hugolin69** [comment] 2021-09-15 15:10
I do not think this is the same issue.
I solved my issue, but I would be happy to know if everybody reach the same problem, because it seems to be native and quite major.

**Comment by hibatallahAouadni** [comment] 2021-09-16 17:18
Hello @hugolin69 

> I solved my issue

How did you solve your issue? and did you clear the cache?
Please check and feedback.

Thanks!

**Comment by hugolin69** [comment] 2021-09-17 06:41
Just see in my first post, the part "How to solve"

**Comment by khouloudbelguith** [comment] 2021-09-17 10:13
Hi @hugolin69,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1778 and ps_facetedsearch v3.7.1.
I attached a screen record
https://drive.google.com/file/d/1TwX5EQ29MPb6BQ0BsN-yAjnk90L8UmOV/view?usp=sharing
I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2021-09-17 10:13 UTC
Labels: Bug, FO, Can't reproduce, Faceted search, 1.7.6.9

**Comment by hugolin69** [comment] 2021-09-17 16:19
I do not know what cause the URL in the TPL to be encode on my 1.7.6.9, but for people with the same problem, it could help.
Thank you.
