### ISSUE TITLE
Error after upgrade 1.7.6.9 to 1.7.7.0

### ISSUE THREAD

**Issue by idefax** [PrestaShop/PrestaShop#22753] opened 2021-01-09 11:56 UTC
#### Describtion:
PHP 7.2
PS 1.7.6.9
No 3rd party modules installed
Core Classic theme
1Click upgrade module 4.11.0
The pre Upgrade checklist is all green. 

After the upgrade I get these error messages:

```
[INTERNAL] path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "path-to-my-installation/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource 
"path-to-my-installation/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in path-to-my-installation/app/config/config.yml (which is being imported from "path-to-my-installation/app/config/config_prod.yml"). 

#0 path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/path-to-my-installation/...', NULL, false, '/path-to-my-installation/...') 

#1 path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/path-to-my-installation/...') 

#2 path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/path-to-my-installation/...') 

#3 path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/path-to-my-installation/...', NULL) 

#4 path-to-my-installation/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/path-to-my-installation/...') 

#5 path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) 

#6 path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() 

#7 path-to-my-installation/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() 

#8 path-to-my-installation/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() 

#9 path-to-my-installation/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() 

#10 path-to-my-installation/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() 

#11 path-to-my-installation/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 

#12 path-to-my-installation/mybackoffice/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 

#13 {main}
```

After upgrade the Backoffice is a blank page = not usable. Chrome shows me a 500 internal server error. Frontend shows offline message.

It's the same as issue #22141 
Should be solved regarding to #22146

#### Expected behavior
Upgrade runs through without errors
Backoffice is usable

#### Steps to Reproduce
Upgrade from 1.7.6.9 to 1.7.7.0 using 1Click upgrade 4.11.0

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by SimonGrn** [comment] 2021-01-09 13:22
Hello,

are you sure it's the same issue as #22141 ?

**Comment by SimonGrn** [comment] 2021-01-09 13:23
Hello,

thank you for your issue. Since it's the same as #22141, I close it. There's no need for a duplicate.

If you want to be informed when it's fixed, please subscribe to the issue mentionned above.

Thank you

**Comment by SimonGrn** [comment] 2021-01-09 13:23
Duplicate of #22141

**Closed as completed by SimonGrn** 2021-01-09 13:23 UTC
Labels: Duplicate
