### ISSUE TITLE
Dashboard metrics are inconsistent

### ISSUE THREAD

**Issue by DianaButkute** [PrestaShop/PrestaShop#20205] opened 2020-07-17 08:49 UTC
#### Describe the bug

There is a problem with the dashboard statistic page. The metrics are not correct. For example, I have some orders in my localhost PS1761 prestashop witch are displayed into the dashboard. As you can see my sales value is $240.64, but when I check it into the Stats -> Stats Dashboard I can see that Revenue is $284.64.

Why these metrics are not the same?

#### Expected behavior

I expect that into the main dashboard board will appear the $284.64 value.

#### Steps to Reproduce

1. Go to Dashboard
2. You will see the Sales value
3. Then go to Stats -> Stats Dashboard and you will see different Revenue value.

**Screenshots**

![image](https://user-images.githubusercontent.com/51438018/87767533-758ff280-c823-11ea-9d8d-1a65d2d451f1.png)

![image](https://user-images.githubusercontent.com/51438018/87767540-79bc1000-c823-11ea-9241-d79c76a7c23e.png)

#### Additional information

* PrestaShop version: 1761
* PHP version: 7.1

**Comment by florine2623** [comment] 2020-07-17 14:36
Hi @DianaButkute ,
On my test shop PS 1.7.6.7 and PS 1.7.7.0 I can't reproduce the issue.
Here are my screenshots:
![Capture d’écran 2020-07-17 à 16 27 03](https://user-images.githubusercontent.com/16019289/87797519-12b25180-c84b-11ea-8396-fb8818a9af21.png)
![Capture d’écran 2020-07-17 à 16 32 32](https://user-images.githubusercontent.com/16019289/87797641-48efd100-c84b-11ea-9184-477aa81f1f25.png)
![Capture d’écran 2020-07-17 à 16 33 18](https://user-images.githubusercontent.com/16019289/87797651-4beac180-c84b-11ea-9158-2f166fa8a433.png)
![Capture d’écran 2020-07-17 à 16 33 59](https://user-images.githubusercontent.com/16019289/87797674-55742980-c84b-11ea-9a14-8c99c0ce243c.png)

 The insights that you see in the dashboard page are about the sale of the product, if you have shipping costs it won't be counted
I hope it helps you understand more how the statistics are calculated.

**Comment by florine2623** [comment] 2020-08-06 15:26
Hi  @DianaButkute ,
Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2020-08-06 15:26 UTC
Labels: BO, Dashboard, No change required, 1.7.6.1
