### ISSUE TITLE
product combinations are not listed in sitemap.xml

### ISSUE THREAD

**Issue by mschiele** [PrestaShop/PrestaShop#16986] opened 2019-04-03 19:10 UTC
we can only find the link to a main product in our sitemap.xml. 
all product combinations/ variations, which have own urls in prestashop too, are not listed in sitemap.xml. not sure if this is an issue or should be a feature?

**Comment by khouloudbelguith** [comment] 2020-01-02 11:27
Duplicate of #16984

**Closed as completed** 2020-01-02 11:27 UTC
Labels: Duplicate, Google sitemap
