### ISSUE TITLE
Multiple commands on one line in upgrade file for 8.1.0

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33616] opened 2023-08-13 12:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I see the following error report: https://www.prestashop.com/forums/topic/1079161-prestashop-804-to-811-error/

When I look at the last executed command it is the line 

> ALTER TABLE `PREFIX_stock_mvt` CHANGE `employee_lastname` `employee_lastname` VARCHAR(255) DEFAULT NULL, CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT NULL;

It looks like a double command in the upgrade file (/modules/autoupgrade/upgrade/sql/8.1.0.sql) doesn't work.

### Expected behavior

Upgrade commands shouldn't contain multiple commands on one line.

### Steps to reproduce

Look into /modules/autoupgrade/upgrade/sql/8.1.0.sql

### PrestaShop version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2023-08-14 06:19
The issue on forums is caused by different thing - fixed here https://github.com/PrestaShop/PrestaShop/pull/33573.
The query you are mentioning works just fine, you can run it in PHP admin and see.

**Comment by sallemiines** [comment] 2023-09-04 08:17
Fixed by #33573

**Closed as completed by sallemiines** 2023-09-04 08:17 UTC
Labels: Bug, CO, Autoupgrade, Fixed, Module, 8.1.x
