### ISSUE TITLE
problem admin side with this option: "Do you need a tax identification number?"

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#18159] opened 2020-03-16 11:48 UTC
Hi
to reproduce this bug go in a country and disable the option "Do you need a tax identification number?"
then go into a customer address admin side, and you will not see the dni field, even if it is already present in the field of an address
now go to the front office, and go to see the customer address, there the dni field will be present

that option should set only the obligation to enter the dni code but this should always appear if the dni field is present in the address fields

bye

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/76755304-e9da5c80-6783-11ea-928d-ed88b915adf2.png)
![2](https://user-images.githubusercontent.com/653230/76755309-eb0b8980-6783-11ea-8dad-56f7f0cc228d.png)
![3](https://user-images.githubusercontent.com/653230/76755672-8dc40800-6784-11ea-80b9-bc6d0ec1d8e8.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-16 15:14
Hi @maofree,

This issue is fixed in the next release PS1.7.7.0.
https://drive.google.com/file/d/1Iz18CXEzj_gGwc0b0cKAe3-HGVZEIFyo/view
Your ticket is a duplicate of #17506
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-03-16 15:14
Duplicate of #17506

**Closed as completed by khouloudbelguith** 2020-03-16 15:14 UTC
Labels: Duplicate
