### ISSUE TITLE
Can not create new product, or get a product without image through web service API

### ISSUE THREAD

**Issue by rost9999** [PrestaShop/PrestaShop#29759] opened 2022-09-26 20:32 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On 1.7.8.3, Prestashop still can not create or get a product through web service if it doesn't have image.

https://user-images.githubusercontent.com/25079898/192374236-00124005-374f-4b71-9301-5f9a994948f8.mp4

### Steps to reproduce

1. BO>CONFIGURE>Advanced Parameters>Webservice
2. Enable PrestaShop's webservice
3. Add new webservice key
4. Generate a key and key desc
5. Check the products and save
6. Access the WS with this link http://your_shop/api/products?display=full
7. Fill the login and password by the key and key desc and connect
8. The list will be displayed

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-09-27 19:00
Hello @rost9999 

I didn't manage to reproduce the issue with PS1786 & PS1787, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/192612865-3874dba0-e3e0-48e6-a66a-b8f6bc782e00.mp4

Please check and feedback.

Thanks!

**Comment by rost9999** [comment] 2022-09-27 19:22
https://user-images.githubusercontent.com/25079898/192616922-de6757d5-133c-4a3e-af19-5a468055a307.mp4

**Comment by MhiriFaten** [comment] 2022-09-30 13:58
Hello @rost9999,

I followed your steps in your screen record, yet I didn't manage to reproduce the issue, see the attached screen record below:
Waiting for your feedback.

[Untitled_ Sep 30, 2022 3_16 PM.webm](https://user-images.githubusercontent.com/111756615/193285938-3625ea0a-a338-4d31-9d4c-894fc6251426.webm)

Waiting for your feedback.

Thank you.

**Comment by rost9999** [comment] 2022-10-05 10:49
If turn off PHP Notice, is work.
The error is can't take id_image from false.
/classes/Product.php, line 7170

**Comment by hibatallahAouadni** [comment] 2022-10-07 10:51
Hello @rost9999 

Thanks for your feedback and glad that you find a work arround :clap: 
Unfortunately, we have to close the issue as we were not able to reproduce your issue with the provided information.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-10-07 10:51 UTC
Labels: Bug, WS, Invalid, 1.7.8.6
