### ISSUE TITLE
The customer age is not correct in 'FO > Your account > GDPR - Personal data> PDF file'

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#29572] opened 2022-09-07 13:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Customer age is not correct  in 'FO > Your account > GDPR - Personal data> PDF file'
The default customer birthdate is 1970-01-15 => in the PDF file his age is 53 years old

![Capture d’écran de 2022-09-07 15-45-16](https://user-images.githubusercontent.com/24647495/188894083-62afeffb-4c36-4d70-8b0e-abac88e2cbe4.png)

### Expected behavior

The default customer birthdate is 1970-01-15 => He should have 52 years old

### Steps to reproduce

1 - Go to FO and connect with default customer
2 - Go to 'My account' page
3- Go to 'GDPR - Personal data' page
4- Click on 'GET MY DATA TO PDF'
5- Check the customer age

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2022-09-07 13:57
Hello @nesrineabdmouleh ,

It has been fixed by https://github.com/PrestaShop/psgdpr/pull/177.

So I close your issue ^^

**Comment by florine2623** [comment] 2022-09-07 13:58
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/29074

**Closed as completed** 2022-09-07 13:58 UTC
Labels: Bug, Minor, FO, Duplicate, GDPR, Fixed
