### ISSUE TITLE
Problem after upgrade to Prestashop 1.7.6.2.

### ISSUE THREAD

**Issue by shana0780** [PrestaShop/PrestaShop#16913] opened 2019-12-24 08:12 UTC
I have problems after the update

When I click on add an article to the cart, the cart is empty
Unable to click on the button "add a file" to change the image in the slider
Unable to add or remove something in the topmenu. The topmenu doesn't appear on the website.
When I try to change an url in SEO & URL, I have the following error Une erreur inattendue s'est produite. [PrestaShopException code 0]

**Comment by shana0780** [comment] 2019-12-24 08:13
![lovingscrap_cart](https://user-images.githubusercontent.com/59194234/71402619-b0370100-262d-11ea-9624-243c45142c48.jpg)
![lovingscrap_topmenu](https://user-images.githubusercontent.com/59194234/71402622-b0cf9780-262d-11ea-94ce-a835180e1614.jpg)

**Comment by khouloudbelguith** [comment] 2019-12-24 08:38
Hi @shana0780,

What is the exact previous version PrestaShop did you use before the upgrade?
What is the exact version of the 1-click upgrade did you use?
Have you any errors during the upgrade?

Thanks!

**Comment by shana0780** [comment] 2019-12-24 08:39
I was the version 1.6.1.8

**Comment by shana0780** [comment] 2019-12-24 08:40
During the upgrade, I have some error in yellow in the database.  I also have many errors on the website but I have corrected everything by changing some files.  

The version of 1-click upgrade, I don't know but I have made an upgrade before.

**Comment by khouloudbelguith** [comment] 2019-12-24 08:49
@shana0780, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks!

**Comment by shana0780** [comment] 2019-12-24 08:53
Already done, and many times. But still the same.

I also try the following
Disable all the modules and activate one by one to see if the problem is coming from one of them
Disable the ajax cart
I'm using the Classic theme
Change the PHP version, I'm in PHP 7.2 (I try with 7.1, 7.0)

**Comment by khouloudbelguith** [comment] 2019-12-24 09:07
@shana0780,

>Unable to add or remove something in the topmenu

You need to install the `blocktopmenu` (Module for PS 1.6) & install the `ps_mainmenu` (Module for PS 1.7)

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by shana0780** [comment] 2019-12-24 09:11
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3997794/log.txt)

I try to change the menu but I'm making a backup of the website with FTP.

**Comment by khouloudbelguith** [comment] 2019-12-24 09:23
@shana0780, there is no errors in the file.
Here are some things you can try :

1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
`if ($this->context->cookie->last_activity + 900 < time()) {`

By this:

`if ($this->context->cookie->last_activity + 3600 < time()) {`

Thanks to check & feedback.

**Comment by shana0780** [comment] 2019-12-24 09:52
Clear cache and cookies : OK
PS-SHOP I don't see such files in the database
Clear cache OK
Classes cookie.php ? where can i disable the IP check ?
Admincontroller OK change

and now I have an error when I try to open the website and the admin
![lovingscrap_error](https://user-images.githubusercontent.com/59194234/71407525-8a185d80-263b-11ea-92d3-8cb3a05fb86a.jpg)
![lovingscrap_table](https://user-images.githubusercontent.com/59194234/71407527-8a185d80-263b-11ea-8219-4acdceb3bea6.jpg)

**Comment by khouloudbelguith** [comment] 2019-12-24 09:54
@shana0780, this is a cache issue.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by shana0780** [comment] 2019-12-24 09:58
It's done, but now I can open the website but error on the admin

![lovingscrap_admin](https://user-images.githubusercontent.com/59194234/71407811-5c7fe400-263c-11ea-9a21-6cef024f89ec.jpg)
![lovingscrap_var](https://user-images.githubusercontent.com/59194234/71407812-5c7fe400-263c-11ea-988b-210a7b336f42.jpg)

**Comment by shana0780** [comment] 2019-12-24 10:15
If I change the AdminController by the first one, It's OK for the admin.

Now I have the topmenu, but the cart doesn't work.
The slider, it's OK now.

But I have another problem now.  I see the menu and when I click on a category in "Products" (I have translated the word Home), I have an error.

![lovingscrap_category](https://user-images.githubusercontent.com/59194234/71408477-b5e91280-263e-11ea-93a6-a307d373bfc8.jpg)

**Comment by khouloudbelguith** [comment] 2019-12-24 10:42
@shana0780, I checked your log file & all files are well copied
```
[2019-12-22 19:17:59] Copied /themes/classic/templates/cms/category.tpl.
[2019-12-22 19:17:58] Copied /themes/classic/templates/catalog/listing/category.tpl.[2019-12-22 19:17:58] Copied /themes/classic/templates/catalog/_partials/miniatures/category.tpl.
```

Thanks!

**Comment by shana0780** [comment] 2019-12-24 11:07
I have looked via FTP and all the files are OK but impossible to see the products in a category and the cart is still at 0 when I add a product in the cart :(

**Comment by shana0780** [comment] 2019-12-24 12:08
For the cart, I also try to replace ps_shoppingcart with the one I can find in the downloaded files of prestashop 1.7 but it doesn't work. Still at 0 when I try to add a product.

**Comment by khouloudbelguith** [comment] 2019-12-24 12:41
@shana0780, 
>Still at 0 when I try to add a product.

About this problem, it is a bookies issue.
Did you tried this solution
https://github.com/PrestaShop/PrestaShop/issues/16913#issuecomment-568704286
Thanks!

**Comment by shana0780** [comment] 2019-12-24 12:43
yes but for one I don't where I have to change

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

**Comment by shana0780** [comment] 2019-12-24 12:47
I find this text but i don't know what to change

            && (!isset($this->_content['remote_addr']) || $this->_content['remote_addr'] == ip2long(Tools::getRemoteAddr()) || !Configuration::get('PS_COOKIE_CHECKIP'));

**Comment by khouloudbelguith** [comment] 2019-12-24 13:00
@shana0780, you can disable it from the BO
![image](https://user-images.githubusercontent.com/16067358/71414093-a7f2bc00-2655-11ea-9021-2955cb535fca.png)

Thanks!

**Comment by shana0780** [comment] 2019-12-24 13:04
Done but still the same.
I also try to desactivate the debug mode, but nothing change.

But I also see that it's not possible to click on the cart button

**Comment by khouloudbelguith** [comment] 2019-12-24 13:26
@shana0780, could you please check if you have some override not compatible with your shop.

Thanks!

**Comment by shana0780** [comment] 2019-12-24 13:34
I delete the folder override to replace it with the folder find in the zip files of PS 1.7.6.2. Nothing change.

**Comment by shana0780** [comment] 2019-12-24 13:35
I have remove the maintenance mode so you can see the website https://www.lovingscrap.com/

**Comment by khouloudbelguith** [comment] 2019-12-24 13:42
@shana0780, The oddest thing is that “/themes/your_theme/category.tpl” is a file for PrestaShop1.6.
You are using Prestashop 1.7, but it seems there are some files for Prestashop 1.6 loaded.
Thanks!

**Comment by shana0780** [comment] 2019-12-24 14:15
yes that's what I have in the beginning. I have to replace some files to remove all the errors.  But here I don't which one I have to replace.
I'm looking for a solution on google but nothing for the moment.

**Comment by khouloudbelguith** [comment] 2019-12-24 14:23
@shana0780, this file /themes/your_theme/category.tpl doesn't exit in PrestaShop1.7: https://github.com/PrestaShop/PrestaShop/tree/1.7.6.2/themes/classic
try to rename this file in your case.

Thanks!

**Comment by shana0780** [comment] 2019-12-24 14:27
No it doesn't exist and I try to copy the file from my backup (PS 1.6) but nothing change.

**Comment by khouloudbelguith** [comment] 2019-12-24 14:35
@shana0780,
>But I have another problem now. I see the menu and when I click on a category in "Products" (I have translated the word Home), I have an error.

This error is displayed at the beginning or it is displayed after some modifications?

Thanks!

**Comment by shana0780** [comment] 2019-12-24 14:38
In the beginning, I don't have the menu on the homepage and it's impossible to do something (move or remove something.  The menu appears after the change I make today (the change you ask me to do).  And then I try to go to a category, and I have an error

**Comment by khouloudbelguith** [comment] 2019-12-24 14:45
@shana0780, 
>If I change the AdminController by the first one, It's OK for the admin.

As explained in this comment: https://github.com/PrestaShop/PrestaShop/issues/16913#issuecomment-568715421
The issue occurs
The AdminController is replaced by the original one (PS1.6) or from fresh install PS1.7.6.2?

Thanks!

**Comment by shana0780** [comment] 2019-12-24 14:49
No it's OK. I have seen my error (double i on if). Now it works.
![Sans titre-2](https://user-images.githubusercontent.com/59194234/71417316-f491c380-2664-11ea-92cc-b4ea5b6e0201.jpg)

**Comment by khouloudbelguith** [comment] 2019-12-24 14:53
@shana0780, so the issue is fixed?

Thanks!

**Comment by shana0780** [comment] 2019-12-24 14:53
no still cart 0 and error on category page.

**Comment by khouloudbelguith** [comment] 2019-12-24 14:58
@shana0780, about this error, We need more details to understand how we can reproduce your issue:
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log


Thanks!

**Comment by shana0780** [comment] 2019-12-24 15:08
![Sans titre-2](https://user-images.githubusercontent.com/59194234/71417803-a631f400-2667-11ea-83e7-d9aedf24f21d.jpg)

**Comment by shana0780** [comment] 2019-12-24 15:10
![Sans titre-2](https://user-images.githubusercontent.com/59194234/71417846-e5604500-2667-11ea-8bc2-3d25d729b895.jpg)

**Comment by shana0780** [comment] 2019-12-24 15:12
en some logs from var/logs

[dev.log](https://github.com/PrestaShop/PrestaShop/files/3998611/dev.log)
[20191222_exception.log](https://github.com/PrestaShop/PrestaShop/files/3998613/20191222_exception.log)
[20191224_exception.log](https://github.com/PrestaShop/PrestaShop/files/3998615/20191224_exception.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/3998616/prod.log)

**Comment by shana0780** [comment] 2019-12-24 15:25
For the Cart it's OK.
I say "No" to Geolocation and now the cart is working.

The last problem (I hope) to solve, the category

**Comment by khouloudbelguith** [comment] 2019-12-24 16:01
@shana0780, the category issue isn't solved in this comment:
https://github.com/PrestaShop/PrestaShop/issues/16913#issuecomment-568761223
Thanks!

**Comment by shana0780** [comment] 2019-12-24 16:01
unfortunately no, not resolved.

**Comment by khouloudbelguith** [comment] 2019-12-24 16:03
@shana0780, 
>If I change the AdminController by the first one, It's OK for the admin.

As explained in this comment: https://github.com/PrestaShop/PrestaShop/issues/16913#issuecomment-568715421
The issue occurs
The AdminController is replaced by the original one (PS1.6) or from fresh install PS1.7.6.2?

Thanks!

**Comment by shana0780** [comment] 2019-12-24 16:05
By the file from PS 1.7.6.2. and I have change the number 900 by 3600

**Comment by khouloudbelguith** [comment] 2019-12-24 16:33
@shana0780, I uploaded here, the default classic theme
[classic2.zip](https://github.com/PrestaShop/PrestaShop/files/3998728/classic2.zip)
I just rename it to be not a duplicate.
Thanks to upload it & use it.

**Comment by shana0780** [comment] 2019-12-24 17:09
I have the same error after downloading the theme.

**Comment by shana0780** [comment] 2019-12-24 18:19
Everything is OK now.
For the category, I delete in controllers/front the file CategoryController.php
Now it works.

Thank you very much for you help and have a Merry Christmas.

**Comment by khouloudbelguith** [comment] 2019-12-25 08:48
@shana0780, Great!
Since it is fixed, I will close the issue, feel free to open a new one when needed.

Thanks & Merry Christmas!

**Closed as completed by khouloudbelguith** 2019-12-25 08:48 UTC
Labels: Bug, Autoupgrade, No change required, 1.7.6.2

**Comment by davideapvd** [comment] 2020-02-12 11:29
to anyone reading this long issue and not figuring out the fix: either disable geolocation or download the geolite db into /app/Resources/geoip/GeoLite2-City.mmdb , recently maxmind changed this file distribution policies.
