### ISSUE TITLE
Cannot Save Changes on Products

### ISSUE THREAD

**Issue by AMIPET** [PrestaShop/PrestaShop#31164] opened 2023-02-02 12:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

Im trying to make some changes on my products, but once i try to save it gives me a message saying: "Is not possible to update the definitions". Does anyone now whats hapenning?

Thanks!
Miguel

### Expected behavior

Is anyone facing the same issue? If so, how did you solve it?

### Steps to reproduce

1. Go to the products list
2. Edit one product
3. Try to save it

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by HanaRebaiQA** [comment] 2023-02-02 15:33
Hello @AMIPET 

Thanks for your report.
I was unable to reproduce your issue using the same steps to reproduce with **Product V1** and **Product V2** on **PS8.0.0**
Could you please provide us with a clear and concise step to reproduce the bug and with a screenshot or screen record? 

https://user-images.githubusercontent.com/92912932/216368798-7c123df4-34a6-486e-bb22-78c66c63c79b.mp4

Thank you!

**Comment by florine2623** [comment] 2023-02-16 13:21
Hello @AMIPET ,

It seems like your issue a related to your configuration. You might be using a external module to edit your products.

I'll close your issue as we were not able to reproduce your issue with the provided information. 

We will close this issue.

Thank you

**Closed as completed by florine2623** 2023-02-16 13:21 UTC
Labels: Bug, BO, Invalid, 8.0.0
