### ISSUE TITLE
Block Cross selling shows products that have visibility set to "nowhere"

### ISSUE THREAD

**Issue by Skinperforator** [PrestaShop/PrestaShop#24784] opened 2021-06-03 08:57 UTC
#### Describe the bug

If a product is out of stock, yet still active but the visibility is set to "nowhere" it still will be displayed in the cross selling module if applicable.

#### Expected behavior

The product shouldn't be visible in the cross selling block aswell. (Or we could have an option to indicate this.)

#### Steps to Reproduce

1. Have two products (one with stock 1, one with more).
2. Have an order with both of them. (automatically or manually set out of stock products to visibility: nowhere)
3. Go to product page of the product still in stock (block cross selling active).
4. See the out of stock product marked sold out in the cross selling block.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2
* Theme: Transformer (ST Themes)

**Comment by hibatallahAouadni** [comment] 2021-06-03 11:11
Hello @Skinperforator 

> (automatically or manually set out of stock products to visibility: nowhere)

Could you please explain what do you mean by "nowhere", could you please provide some screenshots or screen record.
Please check and feedback.

Thanks!

**Comment by Skinperforator** [comment] 2021-06-03 12:38
Hi, 
in Catalog -> Products, if you select a product and go to the options tab you can select the visibility of the product (everywhere, catalog, search, nowhere).
![Screenshot 2021-06-03 14 23 49](https://user-images.githubusercontent.com/16818892/120645909-443f0600-c479-11eb-89da-b83c5fa54a01.png)
![Screenshot 2021-06-03 14 33 36](https://user-images.githubusercontent.com/16818892/120645912-44d79c80-c479-11eb-97bd-28e40ebaee80.png)

**Comment by hibatallahAouadni** [comment] 2021-06-09 22:57
Hello @Skinperforator ,

Thanks for your feedback.
I was able to reproduce the issue with PS1.7.7.4, see the attached screen record below:

https://drive.google.com/file/d/1lt1P0UBlRuJ2AHsSIC-V2qeaSMGTDwP0/view

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment] 2022-07-12 07:47
@FabienPapet takes it

**Closed as completed** 2022-08-01 15:03 UTC
Labels: Bug, Minor, FO, Cross selling, Fixed, PR available, 1.7.6.9, Verified, Module
