### ISSUE TITLE
Tax included price shows wrong price (excluded price)

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#11618] opened 2018-12-05 10:47 UTC
I have applied tax 21% on my shop. But on front office, tax is not applied. Even I have set tax included price to show from backofficec. Can anyone help me?
In the back office there is 24.586777 as tax excl. and 29.75 as tax incl. but it shows me 24.586777 as tax incl.

In the miniatures/product.tpl file there is source code as below:

`<div class="text_desc" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
                    <span class="price">{$product.price}</span>
                    <meta itemprop="price" content="{$product.price}"/>
                    <meta itemprop="priceCurrency" content="EUR" />
              </div>`

Prestashop version: 1.7.4.2

**Comment by khouloudbelguith** [comment] 2018-12-05 11:25
Hi @Akashvastarpara,

In the BO => Shop Parameters => Customer Settings => Groups Tab, which "Price display method" did you use for each group?
Did you use the vatnumber module?
Thanks to check & feedback

**Comment by Akashvastarpara** [comment] 2018-12-05 12:25
I'm using Tax Included method for eaach group.
I'm using "European VAT number" module. In this module there is country selected as Nedherlands and Enable checking of the VAT number with the web service is set as disable.

**Comment by massehbg11** [comment] 2018-12-05 12:43
I Aldo have tax issues, Swedish tax 25% make THE checkout to put 0% tax, something is wrong with tjat module! Also at 12% tax THE system count THE tax wrong!

**Comment by massehbg11** [comment] 2018-12-05 12:44
I have 1.7.4.4

**Comment by khouloudbelguith** [comment] 2018-12-05 14:07
@Akashvastarpara, in the FO, are you connected to a customer account which has a Nedherlands pays in his address?
Thanks!

@massehbg11, what the exact name of the `tjat` module, is it provided by PrestaShop?
Thanks!

**Comment by massehbg11** [comment] 2018-12-05 15:45
@khouloudbelguith in using the module that is provided by prestashop!

**Comment by khouloudbelguith** [comment] 2018-12-05 15:58
@massehbg11, is it the same issue report here: #9928
Thanks to check & feedback.

**Comment by LucaMozzo** [comment] 2018-12-14 23:30
I'm running 1.7.3.3 and all of a sudden I started getting that error. I tried debugging in several ways, [here's my post](https://www.prestashop.com/forums/topic/945891-wrong-price-shown-on-the-front-store/)

I'm not using the module mentioned above

**Comment by Akashvastarpara** [comment] 2018-12-15 14:48
@khouloudbelguith I have disabled geolocation and it's working fine for now.

**Comment by khouloudbelguith** [comment] 2018-12-17 09:39
Hi all,

We have some issues with prices.
You can follow this ticket https://github.com/PrestaShop/PrestaShop/issues/9703
https://github.com/PrestaShop/PrestaShop/issues/9700 for more details, we have planned to fix those issues in PS1.7.6.
@LucaMozzo, in your BO => Shop Parameters => Customers => Groups Tab, you need to edit for
Visitor& Guests group, the "Price display method" to "tax included", 
https://drive.google.com/file/d/1eUESqgcD9jWFbB7tHogkudDxdPJt8SFm/view
if, it is Ok, have you tried to contact the module author, it could be an issue with the theme?
Thanks!

@Akashvastarpara, so now the issue is solved, can I close this ticket? Thanks!

**Comment by Akashvastarpara** [comment] 2018-12-18 08:39
@khouloudbelguith Yes.

**Comment by khouloudbelguith** [comment] 2018-12-18 08:42
@Akashvastarpara, thanks!
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-18 08:42 UTC
Labels: Bug, FO, Taxes and Prices, Fixed, 1.7.4.2

**Comment by LucaMozzo** [comment] 2018-12-18 23:47
@khouloudbelguith  I have all the groups set to "display tax included" but the price I get on the front office is tax excluded with the label "tax included". I'm currently double-checking with my theme creator, if it's still an issue I'll open another issue. Thanks

**Comment by khouloudbelguith** [comment] 2018-12-19 08:09
@LucaMozzo, ok!
Thanks!
