### ISSUE TITLE
remove postcode city crash the adding address 

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17575] opened 2020-02-08 21:36 UTC
hello 
my trying to edit my site to remove many address fields  and add another ..
when i remove postcode city  i cant add any address do the users 
![image](https://user-images.githubusercontent.com/1392266/74092338-f1df1680-4aca-11ea-8671-6d8b21c63cc5.png)

try it buy your self 

![image](https://user-images.githubusercontent.com/1392266/74092341-04f1e680-4acb-11ea-915f-efb874f1ea66.png)

**Comment by khouloudbelguith** [comment] 2020-02-10 08:55
Hi @khalidzuhd,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15428 to fix the issue.
It is fixed in the PS1.7.7.0.
Your ticket is a duplicate of #9812
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-10 08:55
Duplicate of #9812

**Closed as completed by khouloudbelguith** 2020-02-10 08:55 UTC
Labels: Duplicate
