### ISSUE TITLE
Free gift displayed in detail cart

### ISSUE THREAD

**Issue by jdo17** [PrestaShop/PrestaShop#14523] opened 2019-07-08 08:28 UTC
**Is your feature request related to a problem? Please describe.**
when you create a basket discount rule granting a free product, it is well versed in the basket detail but without the mention "free" as on version 1.6.

Event it is weel applied in the side applied discount, it is impossible to relay it to the product (excluding price correlation).

At the first sight, what the customer sees is before a product that is added to him and he likens it to forced selling. It doesn't take a look to the right side.
Problem found on several sites with a very clear cart abandonment. A given equivalence the retail basket of "power boutique" performs more than 20% in this case!

**Describe the solution you'd like**
It would only be necessary to display the mention "Free"

**Additional context**
![6282880832241664-3](https://user-images.githubusercontent.com/29708024/60794746-b4985c00-a16a-11e9-96be-7bd9232de812.png)

**Comment by khouloudbelguith** [comment] 2019-07-08 08:46
Hi @jdo17,

This issue should be fixed in this ticket: #9757
Your ticket is a duplicate of #9757
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-08 08:47
Duplicate of #9757

**Closed as completed by khouloudbelguith** 2019-07-08 08:46 UTC
Labels: Duplicate
