### ISSUE TITLE
Problem with the Product Attributes drop-dow 1.7.4.2

### ISSUE THREAD

**Issue by viperlodz** [PrestaShop/PrestaShop#10288] opened 2018-09-04 22:34 UTC
Product attributes didn't work in the newest version.
On page with product I can see combinations and select other than default but it refreshes back to default.

I try solutions from this link: https://www.prestashop.com/forums/topic/456002-problem-with-the-product-attributes-drop-down-menu-on-shop-page/#comment-2625346

but it still didn't work.

**Comment by khouloudbelguith** [comment] 2018-09-05 08:16
Hi @viperlodz,

Have you the same issue with this ticket: #9667?

Best regards, Khouloud

**Comment by viperlodz** [comment] 2018-09-06 18:27
I think that is not the same.
Here is video: https://fibor.com.pl/app/20180906_194741.mp4
I also check this: https://fibor.com.pl/sklep/phppsinfo.php
Apache log: https://fibor.com.pl/app/error.log

Firefox console:
Error: WebExtension context not found!  ExtensionParent.jsm:861:13
Error: WebExtension context not found!  ExtensionParent.jsm:861:13
sendTimingEvent addSite start undefined undefined  verboseLoggerHooks.js:1:1120
"EXPERIMENT: skipping ads/rich content frame https:=0&showinfo=0"  verboseLoggerHooks.js:1:1120
Error: WebExtension context not found!  ExtensionParent.jsm:861:13
sendTimingEvent addSite start undefined undefined  verboseLoggerHooks.js:1:1120
Promise resolved while context is inactive
  content.js:21
NS_ERROR_NOT_INITIALIZED:   contentscript.js:467
sendTimingEvent addSite start undefined undefined  verboseLoggerHooks.js:1:1120


I don't have any idea. I spend a lot of time and money to get it to work but still nothing. I can't migrate prestashop 1.6 to 1.7 so i install it on the new server vps server ssd on ovh. Everything was install as recomended.

I try also change in SEO page urls for products to:
1) {category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html
2) {category:/}{id}{-:id_product_attribute}-{rewrite_product}.html
3) {category:/}{id}{-:id_product_attribute}-{rewrite_product}{-:ean13}.html

**Comment by LedCloud** [comment] 2018-09-07 04:43
Hi, @viperlodz!
Have you tried the other browser? I had the same probled on Google Chrome but on FF everything works fine.
I played with extentions in chrome, after some changes (enabling and disabling) chrome works fine too.

I'm not sure it's related with extentions because now they are on the same state when they've been when problem occured.

And the problem you described happend on one computer of two I tested.

**Comment by viperlodz** [comment] 2018-09-07 05:26
Yes. I try on FF, Chrome, Mobile Chrome and in not work.
It's this product: https://fibor.com.pl/sklep/zamki-kontrola-dostepu/zamek-elektroniczny-do-drzwi-kaadas-k7-srebrny
I have module to beautiful links but when i trun it off also it don't work.

**Comment by khouloudbelguith** [comment] 2018-09-07 09:10
Hi @viperlodz,

In the Shop Parameters / Traffic & SEO page => you edited the schema of URLs, thanks to check the issue after changing those URLs to the default one & feedback.
![image](https://user-images.githubusercontent.com/16067358/45209936-8ddd7080-b28e-11e8-829e-2f4f140e1010.png)

Best regards, Khouloud

**Comment by viperlodz** [comment] 2018-09-07 09:19
Hi, as I write before I try also change in SEO page urls for products to:

    {category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html
    {category:/}{id}{-:id_product_attribute}-{rewrite_product}.html
    {category:/}{id}{-:id_product_attribute}-{rewrite_product}{-:ean13}.html

and it still don't work.

**Comment by khouloudbelguith** [comment] 2018-09-07 09:41
Hi @viperlodz,

Could you please try to regenerate the file .htaccess

1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL
Thanks to check and feedback

Best regards, Khouloud

**Comment by viperlodz** [comment] 2018-09-07 10:50
Ok I did it, but still don't work.

**Comment by khouloudbelguith** [comment] 2018-09-07 11:00
Hi @marionf what do you think about this issue?
I did not manage to reproduce it with the last version 1.7.4.2.
Also, it is not the same issue described here #9667 @viperlodz said.

Best regards, Khouloud

**Comment by marionf** [comment] 2018-09-07 12:57
@khouloudbelguith I can't reproduce the issue on 1.7.4.2
It looks like an old issue solved in 1.7.3.1 here: https://github.com/PrestaShop/PrestaShop/pull/7775

**Comment by marionf** [comment] 2018-09-07 12:58
@viperlodz I close the issue because we can't reproduce it on 1.7.4.2

**Closed as completed by marionf** 2018-09-07 12:58 UTC
Labels: FO, Can't reproduce, Combinations, 1.7.4.2

**Comment by viperlodz** [comment] 2018-09-07 13:48
It strange because I install new 1.7.4.2 without update it.
I replace controllers/front/ProductController.php from the new downloaded prestashop pack, but still it not work.

In this topic: https://www.prestashop.com/forums/topic/456002-problem-with-the-product-attributes-drop-down-menu-on-shop-page/#comment-2625346
you can see that "Admin523453" has the same problem like me in version 1.7.3.3
Also Pureshore, davenir
I think that it could be this: http://forge.prestashop.com/browse/BOOM-6113
When 1.7.5.0 will be released so I will check if it was that?

**Comment by khouloudbelguith** [comment] 2018-09-07 14:49
Hi @viperlodz,

code freeze should be in September, and then, beta will be released for debugging.

Best regards, Khouloud

**Comment by viperlodz** [comment] 2018-09-24 07:43
Ok I know where is the problem. This topic give me information: https://github.com/PrestaShop/PrestaShop/issues/9842
and I have similar module for preety url, but unistall didn'r resolve problem.
I put oryginal files from prestashop and it works now.

I talk with the module developer and now I have new module with working everything.
