### ISSUE TITLE
My Dashboard and Statisitcs don't work.

### ISSUE THREAD

**Issue by YourStylesas** [PrestaShop/PrestaShop#13678] opened 2019-05-06 09:49 UTC
The overall visits in my dashboard don't show the correct data. 
For example right now it says I got 1012 visits todays and it is completely wrong.
I already reset all the modules connected but nothing changed.
Can someone help me?
![Screenshot (25)](https://user-images.githubusercontent.com/50321557/57218163-eff49e00-6ff4-11e9-9628-6481a98aabd8.png)

**Comment by khouloudbelguith** [comment] 2019-05-07 12:46
Hi @YourStylesas,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by YourStylesas** [comment] 2019-05-07 16:09
[Edited by Khouloud]

**Comment by khouloudbelguith** [comment] 2019-05-08 07:39
@YourStylesas, I deleted your credentials for your security
This is a public space.
Let's be safe!

Thanks!

**Comment by YourStylesas** [comment] 2019-05-08 08:14
oh ok... I thought you needed them..

**Comment by YourStylesas** [comment] 2019-05-08 08:28
I use Plesk web host edition
Prestashop Versione 1.7.2.4 
 I tried to get the other data but I'm not very good at this.

**Comment by khouloudbelguith** [comment] 2019-05-08 09:16
@YourStylesas, Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by YourStylesas** [comment] 2019-05-08 09:26
I read but I can't do it... so sorry

**Comment by khouloudbelguith** [comment] 2019-05-08 09:40
@YourStylesas, If you don't have it, you should ask your hosting provider.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks for your understanding!

**Comment by YourStylesas** [comment] 2019-05-08 09:44
I sit possible I give you the credential to log in and you look at the reports you need?

**Comment by khouloudbelguith** [comment] 2019-05-08 11:14
@YourStylesas, I enabled the debug mode, in the dashboard, an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/57371264-39c2bd00-718a-11e9-80cc-30ab36df1722.png)
You have some issues with the `theme_sneaker2` theme
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by YourStylesas** [comment] 2019-05-08 11:14
That is not the theme I'm using, that is the old one.

**Comment by khouloudbelguith** [comment] 2019-05-08 11:15
@YourStylesas, you are welcome!
Waiting for your feedback.

**Comment by YourStylesas** [comment] 2019-05-08 11:16
do you think the old theme is the reason why the view statistics are wrong?

**Comment by khouloudbelguith** [comment] 2019-05-08 11:18
@YourStylesas, in the dashboard, the only exception displayed is related to the theme.
Thanks!

**Comment by YourStylesas** [comment] 2019-06-04 19:58
I contact the theme support and they told me it is not a problem of the theme.. can someone help me with this?

**Comment by khouloudbelguith** [comment] 2019-06-11 16:04
@YourStylesas, did you removed the old theme from your project folder?

Thanks!

**Comment by matks** [comment] 2019-06-11 16:06
> I contact the theme support and they told me it is not a problem of the theme.. can someone help me with this?

It might be true, but they need to be more specific 😄 "it comes from prestashop" is really not helpful

**Comment by khouloudbelguith** [comment] 2019-06-11 16:11
@YourStylesas, I checked today your shop again & it is OK.
![image](https://user-images.githubusercontent.com/16067358/59288566-fe754b80-8c6b-11e9-9834-e57b9e9d41f8.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-11 08:50
Hi @YourStylesas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-11 08:50 UTC
Labels: BO, Dashboard, No change required
