### ISSUE TITLE
Date of birth has no limitation

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#17507] opened 2020-02-05 12:17 UTC
<img width="558" alt="Screenshot 2020-02-05 at 12 22 53" src="https://user-images.githubusercontent.com/46492443/73841488-b286a080-4812-11ea-99f1-192ece969635.png">

When customer is entering a date of birth when creating an account. It's possible to enter the year 0001 - 0002 - 1710 etc

I would be nice if this was limited to the 19th century. 

Now we have a customer thats  2018 years old :)

**Comment by khouloudbelguith** [comment] 2020-02-05 12:38
Hi @01park,

This issue should be fixed fixing this issue: #17341. 
Your ticket is a duplicate of #17341
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-05 12:38
Duplicate of #17341

**Closed as completed by khouloudbelguith** 2020-02-05 12:38 UTC
Labels: Duplicate

**Comment by matks** [comment] 2020-02-17 13:12
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17664
