### ISSUE TITLE
Import prices by product combination referencen PS 1.7. not possible anymore

### ISSUE THREAD

**Issue by cd2500** [PrestaShop/PrestaShop#17207] opened 2020-01-16 11:56 UTC
Why isn't possible anymore to update prices of combinations on PS 1.7. via combination reference and product ID ?
I think this was possible with PS 1.6. (but I'm not 100% sure, as I'm an Presta Store Manager user).
Now we have the problem, that prices of combinations cannot be managed anymore via csv mass import.
If I import prices with product_id as and combination reference, the product _id is ignored and combinations are added with same reference already available. Seems that now no required field is needed as for distinction ???

**Comment by khouloudbelguith** [comment] 2020-01-16 13:41
Hi @cd2500,

I did not manage to reproduce the issue with PS1.7.6.2
I attached a screen record
https://drive.google.com/file/d/1EhAVYFOLjMJ4A0bxIv_8de-fPdRD2aCd/view
The option: `Use product reference as key` is enabled
First, I used this csv file for the creation
[com.csv.txt](https://github.com/PrestaShop/PrestaShop/files/4071512/com.csv.txt)
The I updated the prices & the quantity & re-import the file again => OK.

Thanks to check & feedback.

**Comment by cd2500** [comment] 2020-01-16 16:20
Oh I see, I was using product_ID as reference and my exported product csv, does not have column "Attribute". The problem is that you cannot use the standard product export file, because not all fields are available. With this you cannot import combination prices. If you try, it will import the combinations as new product, although product_id is available.
[import  combinations.csv.txt](https://github.com/PrestaShop/PrestaShop/files/4072289/import.combinations.csv.txt)

**Comment by khouloudbelguith** [comment] 2020-01-16 16:27
@cd2500, you are trying products or combinations?
The file attached is not a combination import but it is a products import.
Thanks to check & feedback.

**Comment by cd2500** [comment] 2020-01-16 16:35
Combinations

**Comment by khouloudbelguith** [comment] 2020-01-16 16:38
@cd2500, this file
[import.combinations.csv.txt](https://github.com/PrestaShop/PrestaShop/files/4072425/import.combinations.csv.txt) is not for combinations import, it is for a product import.
In the BO => Advanced Parameters => Import page => you can find some examples.
![image](https://user-images.githubusercontent.com/16067358/72544101-0989fd00-3887-11ea-96e9-a8d2ba4484ba.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-17 07:45
Hi @cd2500,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-17 07:45 UTC
Labels: Bug, BO, Import / Export, Combinations, No change required, 1.7.6.2

**Comment by dimitrisgi** [comment] 2022-02-07 14:22
> Hi @cd2500,
> 
> I did not manage to reproduce the issue with PS1.7.6.2 I attached a screen record https://drive.google.com/file/d/1EhAVYFOLjMJ4A0bxIv_8de-fPdRD2aCd/view The option: `Use product reference as key` is enabled First, I used this csv file for the creation [com.csv.txt](https://github.com/PrestaShop/PrestaShop/files/4071512/com.csv.txt) The I updated the prices & the quantity & re-import the file again => OK.
> 
> Thanks to check & feedback.

@khouloudbelguith 
Hi, I don't know if I should open new ticket, as it concerns the issue on this one.

Why it is needed in the file to have the attributes if we only want to update prices/quantities? Only combination reference (or/and product) should be enough.

And as there is NO export option in prestashop (I m wondering why really..), we can't have a .csv with those fields.
