### ISSUE TITLE
Missing images in migrated lists

### ISSUE THREAD

**Issue by tomas862** [PrestaShop/PrestaShop#14661] opened 2019-07-15 14:01 UTC
**Describe the bug**
For migrated lists which has image column images are not being displayed (see 1 screenshot)

**To Reproduce**

Your shop must be running as subdomain - e.g **http://localhost/PrestaShop/** or **http://yourdomain.com/my-inner-domain**

**Screenshots**
1.

![Screenshot (9)](https://user-images.githubusercontent.com/17051250/61221460-3d8e3500-a721-11e9-8d1d-95436d5cc3a0.png)

**Additional information**
PrestaShop version: I think it only targets develop branch , the commit after this problem appeared is this https://github.com/PrestaShop/PrestaShop/commit/0dd19909fd6993b4b2729c575910d094cb1e1fe9 I think it only is merged to develop due to on 1.7.6-beta I did not discovered this issue.

**Available fixing options**

I believe its good that https://github.com/PrestaShop/PrestaShop/commit/0dd19909fd6993b4b2729c575910d094cb1e1fe9 commit added such behavior - in my opinion bad thing is that `\PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser` also attaches shopUrl, its only purpose should be to strip image tags and nothing else.

option 1 of fixing problem:

from `\PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser` remove shopRootUri usage ( I think this is going to be BC break?) @matks wdyt?

option 2 :

add another service which does not include shopRootUri ( will be confusing to have two services of these types and since this bug is a bit sneaky to detect then most developers use the previous one service)

**Comment by mariem-abid** [comment] 2019-07-15 15:17
ping @PrestaShop/prestashop-core-developers

**Comment by marionf** [comment] 2019-07-16 08:17
Hi @tomas862 
Your issue seems to be a duplicate of #14374 ?

**Comment by marionf** [comment] 2019-07-18 07:08
@tomas862 it's fixed by #14543

**Comment by marionf** [comment] 2019-07-18 07:08
duplicate of #14374

**Closed as completed by marionf** 2019-07-18 07:08 UTC
Labels: develop, Duplicate, Image
