### ISSUE TITLE
Wire Payment Module error on validation

### ISSUE THREAD

**Issue by webPonte** [PrestaShop/PrestaShop#11808] opened 2018-12-18 14:30 UTC
Good afternoon,

The problem that I have is that when I make a purchase on the web that I am fulfilling when I choose the payment method and I choose the bank transfer, it remains in the validation and error 500 jumps.
It does not send the mail or the order neither to the client nor to the administration.

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-12-18 14:40
Hi @webPonte,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by webPonte** [comment] 2018-12-18 14:49
My version of prestashop is 1.7.4.2.

The PHP error log shows this: 
Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

And the web is [https://patineteswheels.com](https://patineteswheels.com)

I attached some screenshots
![fireshot capture 068 - patineteswheels - https___patineteswheels com_pedido](https://user-images.githubusercontent.com/45971995/50161511-4a0df480-02dc-11e9-9a33-ec40ea4d370e.png)
![captura](https://user-images.githubusercontent.com/45971995/50161583-79bcfc80-02dc-11e9-96d3-3816588797c5.JPG)

**Comment by khouloudbelguith** [comment] 2018-12-18 14:54
@webPonte, if you enable the debug mode from the Advanced Parameters / Performance page, is there any exception displayed?
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-18 15:07
@webPonte, you just closed the issue?

**Comment by webPonte** [comment] 2018-12-18 15:09
Yes because I put the debug mode for make the screenshot and after I quit the debug mode the module works again perfect

**Comment by khouloudbelguith** [comment] 2018-12-18 15:10
@webPonte, thanks!
Feel free to open a new one when needed.
Thanks!

**Comment by webPonte** [comment] 2018-12-18 15:38
Good afternoon again,
After a few tests the error occurred again, the message that appears in the debug is the one I send in the screenshot.
Comment that in the administrator I also see an error screen I also send screenshot of it.
sorry for the inconvenience
![fireshot capture 070 - - https___patineteswheels com_module_ps_wirepayment_validation](https://user-images.githubusercontent.com/45971995/50164546-534e8f80-02e3-11e9-8203-92720a50de85.png)
![fireshot capture 071 - - https___patineteswheels com_control_index php_configure_advanced_perfor](https://user-images.githubusercontent.com/45971995/50164547-53e72600-02e3-11e9-8952-f4d211332fd1.png)

**Comment by khouloudbelguith** [comment] 2018-12-18 15:48
@webPonte, this issue is occurred due to php-intl extension.
Could you please try to install it, it is required.
Also, this issue is not fixed with ps_mailalert, here's a similar issue #9638, it is added to our bug roadamp.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-18 15:48
Duplicate of #9638

**Closed as completed by khouloudbelguith** 2018-12-18 15:48 UTC
Labels: FO, Duplicate, Wire payment
