### ISSUE TITLE
Bug on aspect reserch: forbidden initial char on Features

### ISSUE THREAD

**Issue by angerangel** [PrestaShop/PrestaShop#20585] opened 2020-08-13 15:04 UTC
Hello,
I just discovered the following bug:

If you give a name starting with minus sign to a feature, for example "**-10/+50°C**",  it will not work the filter on the colum of aspect research in the frontend.
If you click on that feature on the frontend, it will not filter, it just refresh the page with no effects.
If you use a space before the minus sign all work well, for example:  " -10/+50°C"

* PrestaShop version: 1.7.5.2

**Comment by SimonGrn** [comment] 2020-08-14 08:15
Hello,
thank you for your issue. Would you be so kind as to use the correct template and not delete everything, please ?
We need precise steps and screenshots.

Thank you for your understanding.

**Comment by khouloudbelguith** [comment] 2020-09-07 08:26
Hi @angerangel,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-09-07 08:26 UTC
Labels: Duplicate, 1.7.5.2

**Comment by angerangel** [comment] 2020-09-15 20:13
#### Describe the bug

If you give a name starting with minus sign to a feature, for example "-10/+50°C", it will not work the filter on the column of aspect research in the frontend.
If you click on that feature on the frontend, it will not filter, it just refresh the page with no effects.
If you use a space before the minus sign all work well, for example: " -10/+50°C"

#### Expected behavior

A feature should be displayed no matter the starting character used.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. add a feature starting with "-" char, it's ignored
2. add a feature starting with " -" chars, all works fine

**Screenshots**
[![bug2.png](https://i.postimg.cc/MGfRG5F4/bug2.png)](https://postimg.cc/yJBWQmBX)

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.26

**Comment by khouloudbelguith** [comment] 2020-09-16 08:03
Hi @angerangel,

I think it is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/16320

Thanks!

**Comment by SimonGrn** [comment] 2020-09-16 08:05
Yes this is a duplicate.
The issue was also closed so it should have been better to follow Khouloud advice and open a new one.

**Comment by SimonGrn** [comment] 2020-09-16 08:06
Duplicate of #16320
