### ISSUE TITLE
BO - Incorrect display of the icon of messages when the screen is reduced

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24695] opened 2021-05-28 13:05 UTC
#### Describe the bug

When the size of the screen in the BO is reduced, the icon of error, confirmation, warning messages is sometimes not displayed OK.

#### Expected behavior

The icon should always be displayed OK.

#### Steps to Reproduce

It's a bit hard to find steps to reproduce the bug, it's not always there. But it was reproduced many times by @SD1982 and I, so it's there :D

1. Go to BO > Order > View any order page
2. Reduce the size of the screen (for example, by opening the console on the left side of the screen)
3. Display error or confirmation messages (for example, when the mail is not configured, add a message to the order and display it to the customer)
4. The error message should have the icon KO. If not, try to go in large screen again, display the messages, then go back in "reduced" screen.
5. If the error is still not displayed, try to empty cache and try again. Like I said, it's not always there so it's hard to give a scenario.

**Screenshots**

![image](https://user-images.githubusercontent.com/55688534/119987151-ffbcf180-bfc4-11eb-8b13-22eda8d71607.png)

![image](https://user-images.githubusercontent.com/55688534/119987167-03e90f00-bfc5-11eb-9689-6b6db95b2440.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by NeOMakinG** [comment] 2021-05-28 14:04
I'm totally unable to reproduce it, let's wait if someone else notice it

**Comment by PierreRambaud** [comment] 2021-06-01 09:39
Same, I'm not able to reproduce the error, I'm running on Debian Buster.

**Comment by MatShir** [comment] 2021-06-02 16:59
I can't reproduce it also. Last chance maybe @khouloudbelguith or @hibatallahAouadni ?

**Comment by Robin-Fischer-PS** [comment] 2021-06-03 08:35
I was able to reproduce it, just once, in front of @NeOMakinG , and @SD1982 was able too, but it is really random...

**Comment by MatShir** [comment] 2021-06-03 13:22
So what should we do ? Remove the issue from the kanban until someone finds the step to reproduce it ?

**Comment by NeOMakinG** [comment] 2021-06-03 13:28
> So what should we do ? Remove the issue from the kanban until someone finds the step to reproduce it ?

I think so

**Comment by hibatallahAouadni** [comment] 2021-06-04 02:14
Hello everyone,

I'm not able to reproduce it, see the attached screen record below:

https://drive.google.com/file/d/13EBiG1wAkAfGfVNi2c-xf3LRV13boVyo/view

It may caused by some cache, I think we should close it :slightly_smiling_face: wdyt?

**Comment by khouloudbelguith** [comment] 2021-06-25 09:54
Hi @Robin-Fischer-PS,

In my case also, I did not manage to reproduce the issue with 178x branch
![image](https://user-images.githubusercontent.com/16067358/123407296-1a768c00-d5ac-11eb-80d1-8a3b4771a81a.png)

Thank you!

**Comment by khouloudbelguith** [comment] 2021-06-25 12:53
Hi @Robin-Fischer-PS,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thank you!

**Closed as completed by khouloudbelguith** 2021-06-25 12:53 UTC
Labels: Bug, BO, Order, No change required, Front-end, Responsive, 1.7.8.x
