### ISSUE TITLE
Reorder product in category is not working in some condition

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#15291] opened 2019-08-28 13:53 UTC
**Describe the bug**
Reorder product in category is not working in some condition

**To Reproduce**
1. Go to products
2. Filter by accessory 
3. Click on "reorder"
4. Try to reorder but without using the icon in column position, just click on the line and move it
5. Click on saved and refresh
6. See that the change is not saved because the product is not selected if you don't click on the icon.

**Screenshots**
https://drive.google.com/file/d/1FKN7PwLrBGNOcUpp-t7RfJKmyKhSEe8B/view

**Additional information**
PrestaShop version: 1.7.7
PHP version: 7.1

**Comment by robi-bobi** [comment] 2020-02-21 09:43
Hi, I see that there are some events on this ticket, could you let me know what is the latest status on this and if still open, is this planned for a future release and if so, which one?

Thank you!

**Comment by hibatallahAouadni** [comment] 2020-10-28 13:38
Hi @sarahdib 

I was able to reproduce the issue with PrestaShop version 1.7.7.0_rc.1+build.3.

Thanks!

**Comment by ChineseNorris** [comment] 2021-11-12 11:51
Hi,

I would like to add one important issue with this and is you can't drag products from one page to another. A real case scenario is you have a very old product and you want to re-position it to the top (usually we sort from new to old), you can't drag from position 1 to 300 for instance due to drag from page to page issue.

**Comment by bc-devle** [comment] 2022-10-27 12:12
Hi,
Still get this issue on 1.7.8.7

**Comment by Maofree** [comment] 2023-02-16 09:29
Hi
this problem is present on prestashop 1.7.8.8 with php 7.4, I think it is present also on prestashop 8

**Comment by MatShir** [comment] 2023-06-27 14:59
Seems to be fixed in 8.1 on the new page. @PrestaShop/qa-functional could you double-check ? :)

**Comment by florine2623** [comment] 2023-06-28 14:45
@MatShir ,
Issue still remains on `8.0.x` :

https://github.com/PrestaShop/PrestaShop/assets/16019289/861217dc-101a-4c25-bcf5-2905a39c9e39

It is not fixed on `8.1.x` nor `develop`. Actually, the feature seems to have disappeared. I can't drag and drop anymore. :x:
<img width="1201" alt="Screenshot 2023-06-28 at 16 43 15" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/13b982dd-b320-42c9-b53e-93caf3033fe6">

**Comment by MatShir** [comment] 2023-06-28 15:15
You need to click on position title column and the line are drag and dropable.

**Closed as completed** 2023-08-28 12:34 UTC
Labels: Bug, Minor, BO, Fixed, 1.7.5.2, Must-have, Verified
