### ISSUE TITLE
problem total price on front office order ps 1.787

### ISSUE THREAD

**Issue by jomaeva** [PrestaShop/PrestaShop#30072] opened 2022-10-19 16:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi there

m using ps 1.787, and i got a problem with front office order history.

when a customer click on the order number, the total is showing 0. This problem occur only for customized products. The subtotal and total cost is correct.

I guess it s a problem on the order-detail-no-return.tpl

I use theme warehouse, but i tested on the classic theme and i got the same problem

I suspected my installation, then i tried a fresh installation and got the same problem.

It happens only with groups of customers with included taxes prices ( if you switch to without taxes the prices are ok again)
![Screenshot 2022-10-19 at 18-17-26 problem total price on front office order ps 1 787](https://user-images.githubusercontent.com/116192833/196747722-ed90cdbc-eb48-4338-bf6c-613ff8fd8808.png)
![Screenshot 2022-10-19 at 18-18-06 Probleme prix total detail de commande](https://user-images.githubusercontent.com/116192833/196748441-c4ce954f-c5fd-4cc4-8383-53d2c86015f1.png)
![Screenshot 2022-10-19 at 18-21-14 Probleme prix total detail de commande](https://user-images.githubusercontent.com/116192833/196748504-832d1629-066c-42a4-a792-db7e7594dc9b.png)

### Expected behavior

Displaying total price correctly 
![Screenshot 2022-10-19 at 18-21-14 Probleme prix total detail de commande](https://user-images.githubusercontent.com/116192833/196748881-e186457e-c0ef-4912-9b83-3b9b5afbfc89.png)

### Steps to reproduce

switch to Taxes included for a group of cutomer
Use a cusomized product

![Screenshot 2022-10-19 at 18-18-06 Probleme prix total detail de commande](https://user-images.githubusercontent.com/116192833/196748931-196665a8-71b3-418d-9324-41df17c9b880.png)

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by HanaRebaiQA** [comment] 2022-10-20 09:17
Hello @jomaeva 

Thanks for your report.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/10912
To be informed when it's fixed, please subscribe to the issue mentioned above.

**Comment by HanaRebaiQA** [comment] 2022-10-20 09:18
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/10912

**Closed as completed by HanaRebaiQA** 2022-10-20 09:18 UTC
Labels: Bug, Duplicate, Invalid
