### ISSUE TITLE
Order message not loaded on order detail page

### ISSUE THREAD

**Issue by DevSTG** [PrestaShop/PrestaShop#22168] opened 2020-12-01 11:58 UTC
#### Describe the bug

A message that customer adds while placing an order is not visible on order detail page.
I noticed that messages are loaded by `OrderLazyArray::getMessages()` but only non-private masseges:
`$customerMessages = CustomerMessage::getMessagesByOrderId((int) $order->id, false);`
and I can see in `ps_customer_message` table that first order message is marked as private (private = 1).
So first message should not be marked as private, or method should read private messages too.

#### Expected behavior

See all order messages (including first one) on order detail page.

#### Steps to Reproduce

1. Place an order with message
2. Go to this order detail page
3. See no messages at bottom of page

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 5.6.38

**Comment by hibatallahAouadni** [comment] 2020-12-01 14:05
Hello @DevSTG 

I didnt' manage to reproduce your issue with PS1.7.6.8, PS1.7.6.9 and PS1.7.7.0-rc.1, see the attached screen record below:

https://drive.google.com/file/d/1TG9lwpkKxWeo3zLNmuR8KVbsP5lmRSyL/view

Please check and feedback.

Thanks!

**Comment by DevSTG** [comment] 2020-12-01 14:12
Hi @hibatallahAouadni 
Thanks for checking!
Sorry, but I forgot to mention that issue appears in FO on order details page in customers orders history `/controllers/front/OrderDetailController.php`.
Please verify

**Comment by hibatallahAouadni** [comment] 2020-12-01 15:30
Hello @DevSTG 

Thanks for your clarification!
Could you please check if your issue is a duplicate of #9769.

Thanks!

**Comment by DevSTG** [comment] 2020-12-02 07:44
Hi @hibatallahAouadni
Yes it is, and fix #15614 is fixing the problem.
Do I understand correctly that issue is solved in PS version 1.7.8.0 ?

**Comment by hibatallahAouadni** [comment] 2020-12-02 08:07
Hello @DevSTG 

> Do I understand correctly that issue is solved in PS version 1.7.8.0 ?

Yes :sweat_smile: But you can apply the fix proposed in the PR #15614

Well, I close this issue cause it is a duplicate of #9769. 

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-02 08:07
Duplicate of #9769

**Closed as completed by hibatallahAouadni** 2020-12-02 08:07 UTC
Labels: Bug, BO, Duplicate, Order, Order messages, 1.7.6.8
