### ISSUE TITLE
PS_GDPR v2.0.0 - search function in personal data

### ISSUE THREAD

**Issue by PrestaPierre** [PrestaShop/PrestaShop#31878] opened 2023-03-22 12:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

in the personal data management tab, there are display errors
![Capture d’écran 2023-03-22 à 12 00 14](https://user-images.githubusercontent.com/112935373/226907236-75ec95ca-d175-4827-b95d-5a492c446ac1.png)

### Expected behavior

in the personal data management tab, I need to find the original page
![Capture d’écran 2023-03-22 à 13 40 19](https://user-images.githubusercontent.com/112935373/226907464-e216eb56-8e7f-4fee-a5d3-e0f02497d294.png)

### Steps to reproduce

Go to module ps-gdpr
and clic on "personnal data management"
and i see error

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.9

### If your bug is related to a module, specify its name and its version

ps_gdpr

**Comment by paulnoelcholot** [comment] 2023-03-22 16:17
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2023-03-22 16:17 UTC
Labels: Bug, Invalid
