### ISSUE TITLE
Mail::Send() printing error instead of throwing it

### ISSUE THREAD

**Issue by GuillaumeVrill** [PrestaShop/PrestaShop#31490] opened 2023-02-22 13:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The function `Mail::Send(...)` does not throw error when a template is not found, but instead it prints the error on screen, keeping developper from catching it and decide what to do with it (like alerting or logging it).

### Expected behavior

I expected the function to throw an error in this case, so that i can catch it and decide how to deal with it.

### Steps to reproduce

1. Create a simple module structure.
2. Add a hook on an order change (or elsewhere where it's straightforward enough to trigger an event)
3. Call `Mail::Send(...)` function in this hook, giving it a template that does not exists yet (in theming scenarios as an example)
4. You can put a try / catch clause around it to see the result
5. Be sure to be in debug mode or you won't even see it
6. Upload and test your module by triggering the event you hooked onto to see the error printed, but not thrown (not catchable). 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment] 2023-02-22 16:24
Hi @GuillaumeVrill 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by hibatallahAouadni** [comment] 2023-09-01 07:58
Hello @GuillaumeVrill 

Do you still encounter the same issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-29 14:20
Hello @GuillaumeVrill 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-29 14:20 UTC
Labels: Bug, CO, Modules, Email, Hook, Invalid, 8.1.x
