### ISSUE TITLE
gdpr checkbox activate add to cart button of out of stock product

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#27326] opened 2022-01-12 11:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Click on gdpr checkbox activate the add to cart button of an out of stock product
![image](https://user-images.githubusercontent.com/16720275/149128359-c56d9a26-676d-41a4-a1b0-8780e7b1501a.png)

Explanation:
modules/psgdpr/views/templates/hook/displayGDPRConsent.tpl contains a javascript that take care of buttons.
This javascript code disable the closest submit button.
Gdpr and mail alert are in the same form.

### Expected behavior

The add to cart button shoud stay disabled

### Steps to reproduce

- Activate GDPR and mail alert modules.
- Go to an out of stock product page: the add to cart button is disabled
- Check Gdpr checkbox
- The add to cart button become enabled

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

GDPR and mail alert modules, lastest version

**Comment by hibatallahAouadni** [comment] 2022-01-12 15:41
Hello @jf-viguier 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22880. 
This issue is already fixed with the upcoming ps_mailalerts release 2.3.1 with this [PR](https://github.com/PrestaShop/ps_emailalerts/pull/86)

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-12 15:42
Duplicate of #22880

**Closed as completed by hibatallahAouadni** 2022-01-12 15:41 UTC
Labels: Bug, Duplicate, Invalid

**Comment by kpodemski** [comment] 2022-01-12 15:43
@jf-viguier is this 2.3.1 of `ps_emailalerts`?

**Comment by jf-viguier** [comment] 2022-01-12 15:45
No 2.3.0, I don't see 2.3.1 in releases https://github.com/PrestaShop/ps_emailalerts/releases

**Comment by kpodemski** [comment] 2022-01-12 15:46
@jf-viguier ok then, it should be fixed in 2.3.1 but we haven't released it yet :D

**Comment by jf-viguier** [comment] 2022-01-12 15:46
ok, thanks @kpodemski
