### ISSUE TITLE
error trying to upload a new theme

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23068] opened 2021-02-01 01:05 UTC
#### Describe the bug

error trying to upload a new theme from my computer's file explorer
thats error "Se ha producido un error inesperado. [PrestaShop\PrestaShop\Core\Domain\Theme\Exception\ThemeConstraintException código 2]"

"Unexpected error has ocurred. [PrestaShop \ PrestaShop \ Core \ Domain \ Theme \ Exception \ ThemeConstraintException code 2]"

#### Steps to Reproduce

1. Go to themes
2. Click on Import from your computer
3. Select a theme

**Screenshots**

![image](https://user-images.githubusercontent.com/62474824/106404114-ea2e2580-6431-11eb-8ac3-6ca217bdd3c8.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-02-01 08:12
Hello @alfonsolr09 

I didn't manage to reproduce your issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1W6YBWt5mL_nn0MBfHJALEIT4d0nEtLWy/view

Could you please check your imported theme, it may be faulty or incompatible with this version.
Please check and feedback.

Thanks!

**Comment by alfonsolr09** [comment] 2021-02-01 08:14
Its compatible...

**Comment by hibatallahAouadni** [comment] 2021-02-01 11:44
Hello @alfonsolr09 

> Its compatible...

Ok, so could you please provide more infos so I can manage to reproduce your issue.
Cause as you can see I couldn't :confused: 

Thanks!

**Comment by alfonsolr09** [comment] 2021-02-01 23:31
I have prestashop in a subdirectory, I don't know if that influences

**Comment by hibatallahAouadni** [comment] 2021-02-02 08:34
Hello @alfonsolr09 

The Classic theme is well installed? if so, please click on **Export current theme** button to export the classic. Then change its name **classic_child**. Now try to import this **classic_child** and let's see if there's an error with your store or with your other theme.

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-22 14:45
Hello @alfonsolr09 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-22 14:45 UTC
Labels: Bug, BO, Theme & logo, No change required, 1.7.7.1
