### ISSUE TITLE
blockreassurance PHP fatal error

### ISSUE THREAD

**Issue by mattia-consiglio** [PrestaShop/PrestaShop#21268] opened 2020-10-02 10:26 UTC
I downloaded the public repository deleting the folder `.github`  and the file `.gitignore`
I installed the modified the ZIP on PrestaShop Modules > Module Manager > Upload Module

Going to product page there wasn't the Customer reassurance block and all the elements below, the same form the checkout page. I checked the PHP error log and I see this error

```
PHP Fatal error:  Uncaught Error: Call to undefined method ImageManager::getMimeType() in /home/capsor/public_html/modules/blockreassurance/classes/ReassuranceActivity.php:190
Stack trace:
#0 /home/capsor/public_html/modules/blockreassurance/blockreassurance.php(517): ReassuranceActivity::getAllBlockByStatus(2, 1)
#1 /home/capsor/public_html/modules/blockreassurance/blockreassurance.php(409): blockreassurance->renderTemplateInHook('displayBlockPro...')
#2 /home/capsor/public_html/classes/Hook.php(970): blockreassurance->hookdisplayReassurance(Array)
#3 /home/capsor/public_html/classes/Hook.php(355): HookCore::coreCallHook(Object(blockreassurance), 'hookdisplayReas...', Array)
#4 /home/capsor/public_html/classes/Hook.php(907): HookCore::callHookOn(Object(blockreassurance), 'displayReassura...', Array)
#5 /home/capsor/public_html/config/smarty.config.inc.php(167): HookCore::exec('displayReassura...', Array, NULL)
#6 /home/capsor/public_html/classes/Smarty/SmartyLazyRegister.php(83): smartyHook(Array, Object(Smarty_Internal_Templ in /home/capsor/public_html/modules/blockreassurance/classes/ReassuranceActivity.php on line 190
```

PrestaShop v. 1.7.6.8
PHP v. 7.2

**Comment by florine2623** [comment] 2020-10-02 12:08
Hi @mattia8961 ,
Was the installation of the module successful ? Which version did you install ?
Can you check if the module is hooked to displayReassurance hook ?
Thanks!

**Comment by matks** [comment] 2020-10-02 12:49
Hi, this bug is already reported 😉 it's this one https://github.com/PrestaShop/PrestaShop/issues/20254

And the bugfix is on its way 😄 https://github.com/PrestaShop/blockreassurance/pull/55

**Comment by SimonGrn** [comment] 2020-10-02 13:56
Hi @mattia8961 

please follow the template next time, it helps us save time by not asking you questions you would have answered in it.

Thanks in advance.

I close this one as it's a duplicate.

**Comment by SimonGrn** [comment] 2020-10-02 13:56
Duplicate of #20254

**Closed as completed by SimonGrn** 2020-10-02 13:56 UTC
Labels: Duplicate, Modules, Blockreassurance, 1.7.6.8

**Comment by pppplus** [comment] 2021-03-15 14:50
Bug is present in the module 5.0
The version of PS doesn't matter !!

Big bug is on file 
/modules/blockreassurance/classes/ReassuranceActivity.php on line 190

=> str_replace(__PS_BASE_URI__, _PS_ROOT_DIR_ . DIRECTORY_SEPARATOR, $item['custom_icon'])
Very big bug....

Replace ALL occurences "/" (__PS_BASE_URI__)  by _PS_ROOT_DIR_  in $item['custom_icon']
If custom icon is like that : /modules/blockreassurance/views/img//reassurance/pack1/payment.svg
the result is very bad.

So line 190
                && (ImageManager::getMimeType(str_replace(__PS_BASE_URI__, _PS_ROOT_DIR_ . DIRECTORY_SEPARATOR, $item['custom_icon'])) == 'image/svg');

Should probably be replaced by :
                && (ImageManager::getMimeType(preg_replace('#'.__PS_BASE_URI__.'#', _PS_ROOT_DIR_ . DIRECTORY_SEPARATOR, $item['custom_icon'], 1)) == 'image/svg');

To be verified, not sure, all cases are covered.

**Comment by matks** [comment] 2021-03-15 16:25
Hi @pppplus I'm sorry but I dont understand both the bug you talk about and what you do in the code.

If you want to help, please report a new github issue and fill the template 😉  without that, we cannot understand what you are talking about. It's clear for you but it's not for us 😄  that is why we need a complete bug report

**Comment by pppplus** [comment] 2021-03-15 16:34
Hi
This command is stupid : 
str_replace(PS_BASE_URI, PS_ROOT_DIR . DIRECTORY_SEPARATOR, $item['custom_icon'])
It replaces all / in the icon path, by PS_ROOT_DIR 

We should replace only first one : 
My icon is : /modules/blockreassurance/views/img//reassurance/pack1/payment.svg
The function has to replace only first /
So, with 
preg_replace('#'.PS_BASE_URI.'#', PS_ROOT_DIR . DIRECTORY_SEPARATOR, $item['custom_icon'], 1)

(the 4th parameter limits to the 1st replacement of /)

You ask me to report a new github issue... but I don't know how to do that, sorry.

**Comment by matks** [comment] 2021-03-15 17:00
To report an issue on github, you follow the link https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md and fill in the template 😉

**Comment by pppplus** [comment] 2021-03-15 18:09
Sorry, I misunderstand your request !
Why put a new report, it's the same one !

I just reported what I change to solve THIS bug : blockreassurance PHP fatal error
