### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by ilyassw** [PrestaShop/PrestaShop#20701] opened 2020-08-25 08:42 UTC
Hi,
Prestshop version 1.7.6.7
I posted about my issue on presta forum but i didn't get an answer , so i hope i will get one here .
I have problem setting up SMTP with port 587 and port 465 , if i use port 25 i can send and receive email without any issue ! note that port 25 is open on amazon light sale as well as port 587 and 465 ... but whenever i try port 587 encrypt ssl i get this error :

Error: Please check your configuration

Connection could not be established with host smtp.mydomain.com [ #0] same issue when using port 465 . I repeat and insist both port are open .

Please i need help to sort this out . Thank you

Note : please don't close this ticket till resolved , my stmp details all correct and i insist everything work with port 25 only when use port 587 and port 465 with ssl or tsl problem arise .

**Comment by khouloudbelguith** [comment] 2020-08-25 08:53
Hi @ilyassw,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1iilctyY__itql95dako5OFYWtOLlI9nM/view?usp=sharing
This is a custom configuration issue.
You need to check your host.
Please, On this github repository there is no software support. This is an open source project.
You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks for your understanding!

**Comment by khouloudbelguith** [comment] 2020-08-25 08:53
Duplicate of #20695

**Closed as completed by khouloudbelguith** 2020-08-25 08:53 UTC
Labels: Duplicate

**Comment by ilyassw** [comment] 2020-08-25 09:14
Cool thanks ! That make sense .
