### ISSUE TITLE
Issue After trying to Update to 1.7.7.0 -> SessionInterface

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#20165] opened 2020-07-13 14:43 UTC
<img width="1141" alt="Capture d’écran 2020-07-13 à 14 37 11" src="https://user-images.githubusercontent.com/43704805/87317836-d075d100-c527-11ea-9824-3c6c4a639ea7.png">

**Comment by matks** [comment] 2020-07-13 14:52
Hi, I guess you mean 1.7.6.7 and not 1.7.7.0 ?

We have seen someone else with same issue. On his shop he was missing the following file: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.7/src/Core/Session/SessionInterface.php

Can you tell us how you upgraded your shop and who is your hosting provider ? We believe the root cause to be a bad copy process as this file should have been copied into your shop during upgrade process. This might be because of tight constraints in a specific hosting provider.

**Comment by passio777x** [comment] 2020-07-13 14:56
I meant 1.7.7.0
With 1.7.6.7, I also have an issue,  I can't reactivate my shop ! Maintenance button doesn't work anymore...

My prestashop became hell when I activated Multishop.

**Comment by matks** [comment] 2020-07-13 14:58
But 1.7.7.0 is not available for upgrade 🤔   inside the module (as far as I know 😅  ..?) . It's a beta version only.

**Comment by passio777x** [comment] 2020-07-13 15:00
Awh, I downloaded it and put it in admin auto-upgrade folder and I tryed to update :) I though it was possible.

**Comment by atomiix** [comment] 2020-07-13 15:22
Hi @passio777x , it should be possible! Can you provide us your autoupgrade log file? It should be in `/adminXXX/autoupgrade/tmp/log.txt`

**Comment by qualityangel** [comment] 2020-07-14 09:30
> I meant 1.7.7.0
> With 1.7.6.7, I also have an issue, I can't reactivate my shop ! Maintenance button doesn't work anymore...
> 
> My prestashop became hell when I activated Multishop.

Same here, can't use the maintenance button, had to  set activation in database

**Comment by khouloudbelguith** [comment] 2020-07-27 15:34
Hi @passio777x, @qualityangel,

I did not manage to reproduce the issue after an upgrade from PS1.7.6.7. to PS1.7.7.0 (Branch 1.7.7.x)
I attached a screen record
https://drive.google.com/file/d/1JjaYC94hCeSMxrMHwDY5TjOmSC0ya_5n/view?usp=sharing

Thanks!

**Comment by passio777x** [comment] 2020-07-27 17:45
My issue was for 1.7.6.7, shop can't be reactivated when I was in "all shop", activate button has no effect in "all shop", but independantly, they can be reactivated, if I go in once store.

**Comment by khouloudbelguith** [comment] 2020-07-28 08:26
Hi @passio777x,

>My issue was for 1.7.6.7, shop can't be reactivated when I was in "all shop", activate button has no effect in "all shop", but independantly, they can be reactivated, if I go in once store.

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #19362
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-28 08:26
Duplicate of #19362

**Closed as completed by khouloudbelguith** 2020-07-28 08:26 UTC
Labels: Duplicate, Autoupgrade
