### ISSUE TITLE
Unit price cannot be zero

### ISSUE THREAD

**Issue by the-ge** [PrestaShop/PrestaShop#34260] opened 2023-10-12 18:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to save product with the "Display retail price per unit" settings activated and both per unit prices set at 0.000000 will error out with the "This value should be positive" message.

![2023-10-12-203316](https://github.com/PrestaShop/PrestaShop/assets/6468893/b778f645-2d10-440f-bfb0-86a448c3aea9)

Looking in the code it appears that  SpecificPriceImpactType and UnitPriceType are set with the Positive constraint.

### Expected behavior

Trying to save product with the "Display retail price per unit" settings activated and both per unit prices set at 0.000000 should succeed with no error message.

### Steps to reproduce

1. Go to admin > Sell > Catalog > Products.
2. Choose any product, go to the Pricing tab and activate "Display retail price per unit" with both prices set at 0.000000.
3. Click on "Save and publish"

Result: fail with "This value should be positive" message.

### PrestaShop version(s) where the bug happened

8.1.0, 8.1.1

### PHP version(s) where the bug happened

8.1.22

**Comment by AureRita** [comment] 2023-10-13 09:06
Hi @the-ge,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.2, as you can see : 

[Untitled_ Oct 13, 2023 11_00 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/7dd2b1a2-6903-41b6-9f44-ff4184974101)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

For information, this one can be an expected behavior because when you don't set the name of unit, you don't have issue on it. @PrestaShop/product-council what do you think ? 

Thanks

**Comment by MatShir** [comment] 2023-10-13 09:31
Hi @the-ge,
Why you would like to publish price per unit at 0. Isn't a good way to avoid issue on the product publication?

**Comment by the-ge** [comment] 2023-10-13 18:09
@MatShir Well, it doesn't feel that way for me. I can look at it in multiple ways:
- because I expect all prices to have the same behaviour, as long as any price can be zero, then all prices should be allowed to be zero;
- the seller should be able to give away a product that uses that price, if he/she so desires
- when importing products from a CSV and some of them don't have a price per unit, the unit will be switched on and the price will be set to zero for them; then, if one tries to save one of those products will be hit by the "This value should be positive" message (this is how I actually got it :grinning: ); allowing prices to be zero would eliminate that issue.

**Comment by Hlavtox** [comment] 2023-10-13 18:50
This is expected behavior. If you check “Display unit prices” why would you put zero? Unit price must be non zero.

**Comment by the-ge** [comment] 2023-10-14 01:09
You can find two use cases in my previous message.
But more importantly, if it's a price of any kind, the seller should be able to make it zero.
I cannot think of anything useful brought by this constraint.

> Unit price must be non zero.

Really? Why?

**Comment by Hlavtox** [comment] 2023-10-30 09:32
@the-ge There is a solid use case in the duplicate issue here - https://github.com/PrestaShop/PrestaShop/issues/34418. It's OK for me. Pinging @PrestaShop/product-council just to be sure. :-)

**Comment by MatShir** [comment] 2023-10-31 09:14
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34419
Thanks everyone

**Closed as completed by MatShir** 2023-10-31 09:14 UTC
Labels: Bug, PM ✔️, Minor, BO, Fixed, Verified, Products Page
