### ISSUE TITLE
Non working SEO preview on product page

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#11915] opened 2018-12-23 22:09 UTC
**Describe the bug**
The new SEO preview feature on product page is not working correctly after upgrade from 1.7.4.2 using 1-click upgrade.

**To Reproduce**
1. Have a previous PS version with a product SEO complete
2. Upgrade to 1.7.5
3. Go to product page SEO
4. See the problem as on screenshot

**Screenshots**
![bug seo product](https://user-images.githubusercontent.com/31688689/50387884-5395c300-0707-11e9-8185-e0f94e1e9de4.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2018-12-24 10:18
Hi @mrabsinthe,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11911
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-24 10:18
Duplicate of #11911

**Closed as completed by khouloudbelguith** 2018-12-24 10:18 UTC
Labels: Duplicate
