### ISSUE TITLE
1.7.6.0 - BackOffice - Update a category when the Home category is hidden

### ISSUE THREAD

**Issue by Msappdem** [PrestaShop/PrestaShop#15174] opened 2019-08-20 15:19 UTC
When the Home category is hidden it is not possible to update the subcategories

The solution is to reactivate the category home then after the updates, disable the category home

PrestaShop version: 1.7.6.0
PHP version: 7.3.0

**Comment by khouloudbelguith** [comment] 2019-08-20 15:45
Hi @Msappdem,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15030 to fix the issue.
Your ticket is a duplicate of #14790
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-20 15:45
Duplicate of #14790

**Closed as completed by khouloudbelguith** 2019-08-20 15:45 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2019-08-20 15:46
@Msappdem, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

**Comment by satheeshindr** [comment] 2019-11-16 17:27
Same Issue. Kindly provide the solutions ASAP.
I have Changed src/PrestaShopBundle/Resources/config/services/adapter/form.yml
from PR: #15030 to fix the issue.
But not worked form me.
Thanks
![1](https://user-images.githubusercontent.com/22688033/68996758-620f3f00-08c4-11ea-9e3c-a887ec28f8d7.jpg)

**Comment by khouloudbelguith** [comment] 2019-11-18 11:01
Hi @satheeshindr,

No, it is fixed for PS1.7.6.1.
https://drive.google.com/file/d/1IVv3GlsxcdyP8RK24ehVIBcD-OCg2kki/view
Thanks!
