### ISSUE TITLE
Product Page v2: Fix the scrollbars on the iframe for attachment form

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#25735] opened 2021-08-30 09:44 UTC
#### Describe the bug

Previously fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/26024
In product page v2 when adding a new file a modal opens containing an iframe that includes the form.
This modal has unwanted scrollbars, we need to find a way to remove those (maybe the max width is too
small, maybe the auto size feature is lacking a few pixels)

#### Expected behavior

No scroll bars

#### Steps to Reproduce

1. Go to Product page V2
2. Go to Specifications tab 
3. Click on 'Add new file'
4. See the unwanted scrollbars (see screenshot)

**Screenshots**

![Capture d’écran 2021-08-30 à 11 43 57](https://user-images.githubusercontent.com/13801017/131320499-f49e1a51-08ce-4e53-90d4-9d7a23821c63.png)

#### Additional information

* PrestaShop version: 8.0
* PHP version: N/A

**Comment by NeOMakinG** [comment] 2021-09-13 13:31
I took a look at the issue, it's mainly because of non-needed `.row` classes

It should be fixed by @Hlavtox on https://github.com/PrestaShop/PrestaShop/pull/25312, can you confirm @Hlavtox ?

**Comment by khouloudbelguith** [comment] 2022-03-08 08:35
Hi @jolelievre,

I will reopen the issue.
I manage to reproduce the issue again with develop branch.
![image](https://user-images.githubusercontent.com/16067358/157198399-3d4e4017-f0a2-465a-bb9c-bf0e986ea306.png)
![image](https://user-images.githubusercontent.com/16067358/157198497-b13ab2be-f8a5-4a70-8f68-6ade28d8b26a.png)

It was ok before
![image](https://user-images.githubusercontent.com/16067358/157198633-13838b3a-dba6-4f2b-84fd-62ec523b7a77.png)

Thanks!

**Closed as completed** 2022-04-07 11:32 UTC
Labels: Bug, 8.0.x, Trivial, BO, Regression, Fixed, Front-end, PR available, Verified
