### ISSUE TITLE
The HEAD request in webservice are handled as GET

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27634] opened 2022-02-09 22:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The GET and HEAD requests on the api return the same response, with the body inside them.

### Expected behavior

HEAD request need to avoid the body, only return the response code.

### Steps to reproduce

1. Enable the webservice
2. Make a call to the API with ps_method=HEAD to simulate the requet type.
3. See that a body answer is given.

![image](https://user-images.githubusercontent.com/16067358/153561764-baafdffd-34e4-4f0e-bdf5-ee89a4d52d86.png)

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by HanaRebaiQA** [comment] 2022-02-10 11:02
Hello @PrestaEdit 

Could you please provide us the request body that you use ? and a screenshot/screen-record to can reproduce your issue clearly ?

Thanks!

**Comment by PrestaEdit** [comment] 2022-02-10 11:04
The request body used is empty, there is no need.

You can try this with this kind of call:

- /api/carriers/1?ps_method=GET
- /api/carriers/1?ps_method=HEAD

**Comment by khouloudbelguith** [comment] 2022-02-11 08:45
Hi @PrestaEdit,

Thanks for your feedback.
I manage to reproduce the issue with PS1778 & PS1783.
![image](https://user-images.githubusercontent.com/16067358/153561238-d4bc5caf-3ebc-4618-818c-20ccb9b4074e.png)
The HEAD method is available in PrestaShop as described here: https://devdocs.prestashop.com/1.7/webservice/reference/#available-http-methods
So I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by matks** [comment] 2022-02-16 13:29
@khouloudbelguith I am not sure that this is a bug.

If, in the past, the developer who implemented the HEAD webservice management _wanted_ that HEAD requests would return no body, and it failed, then it would be a bug. Because it was wanted that no body would be returned, and this is not what's happening.

I believe actually the system was never designed to handle HEAD correctly.

So it's not a bug, rather an incomplete implementation.

**Comment by khouloudbelguith** [comment] 2022-02-16 13:36
Hi @matks,

Thanks for your feedback.
So, do we need to close this issue?

Thanks!

**Comment by matks** [comment] 2022-02-16 13:48
@khouloudbelguith no I think it's however something very valuable to implement. So I suggest to mark it as "Feature Request", "Developer feature"

**Closed as completed** 2022-11-07 16:40 UTC
Labels: Feature, Minor, WS, Webservice, Developer Feature, 1.7.7.8, Verified
