### ISSUE TITLE
Presta 1.7.6.5 pagination issue after using ps_fasetsearch

### ISSUE THREAD

**Issue by pearpl** [PrestaShop/PrestaShop#22603] opened 2020-12-28 01:25 UTC
#### Describe the bug

When using  ps_fasetsearch on the product listing page the pagination section does not refresh after selecting anything from the fast search list.  As a result instead of limited results, the pagination shows full pagination of all products. 

#### Expected behavior

After selecting anything from fasetsearch the pagination should refresh too same as the product listing page. 

#### Steps to Reproduce

1. Go to shorturl.at/afNX3
2. Select anything from the left fasetsearch module
3. Wait for results to refresh
3. Scroll down to the pagination segment at the bottom
4. The results in the pagination are not refreshed. 
5. Manually refresh the page by F5 to correctly load the pagination

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.22

**Comment by hibatallahAouadni** [comment] 2020-12-28 09:53
Hello @pearpl 

I didn't manage to reproduce your issue with PS1.7.6.5 and PS1.7.7.0, see the attached screen recored below:

https://drive.google.com/file/d/1b5hj-FPCBKro9CkHPuGLh87vwFOgOPaF/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-17 13:10
Hello @pearpl ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-17 13:10 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.7.0, 1.7.6.5
