### ISSUE TITLE
Minor bug of Description and summary of the product!

### ISSUE THREAD

**Issue by Peterits** [PrestaShop/PrestaShop#12515] opened 2019-02-08 15:18 UTC
Hi,
Still a little bug with the description and summary of the product, the tabs remain blocked:
To reproduce follow the video

![screencapture_08-02-2019_14_29_09](https://user-images.githubusercontent.com/44966543/52486955-c88c6180-2bbc-11e9-802c-729c0b844c8c.gif)

**Additionnal information**
PrestaShop version: 1.7.5.0 and 1.7.5.1 + maj # 12053 !
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-02-08 15:31
Hi @Peterits,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12234 to solve the issue.
It is fixed in the PS1.7.5.1.
Your ticket is a duplicate of #12053
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-08 15:31
Duplicate of #12053

**Closed as completed by khouloudbelguith** 2019-02-08 15:31 UTC
Labels: Duplicate

**Comment by Peterits** [comment] 2019-02-08 16:05
Hi, this is not the same problem, in this problem, both tabs remain open at once and the maj did not solve this problem! Watch the video to reproduce! Thank you

**Comment by khouloudbelguith** [comment] 2019-02-08 16:28
@Peterits, thanks for your feedback.
Yes, you are right.
It is not fixed yet, in fact, your issue is a duplicate of #9668
I will reopen it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-08 16:29
Duplicate of #9668
