### ISSUE TITLE
1.7.6 Back office freeze after rebuild entire search index

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15169] opened 2019-08-20 12:09 UTC
After clicking on rebuild entire search index in the search tab. Our backoffice freezes.

In the back ground the index gets updated, but its impossible to go to another tab. Even when the page is closed in the same browser then BO is still frozen. Only way to get back in to BO is via a different browser. I tried in safari and chrome and vice versa. 

PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-20 13:06
Hi @01park,

I did not manage to reproduce the issue with PS1.7.6.0.
https://drive.google.com/file/d/1CkJuP86GlTp_-m7iNQdZJ3XG4CYMfrnY/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by 01park** [comment] 2019-08-20 13:19
Hi @khouloudbelguith 

I see no error with debug turned on. That said, since the BO freezes I have no control over anything. 
Before I click on the rebuild option, the debug mode showed no errors.

Also, this is something I mentioned before. After saving an item the index never is update.

prestashop 1.7.6 multistore on
HOST: godaddy (VPN server)
PHP 7.2
All packages for PHP installed

<img width="1449" alt="Screenshot 2019-08-20 at 14 18 02" src="https://user-images.githubusercontent.com/46492443/63350463-6378ac00-c355-11e9-82cd-417a6fbc5d36.png">

**Comment by khouloudbelguith** [comment] 2019-08-20 13:48
@01park, "All shops" is selected in your case?
https://drive.google.com/file/d/1OSrYY1Df1u4YgXkwuBqCYftxo9G-mjtP/view
Thanks!

**Comment by 01park** [comment] 2019-08-20 13:52
@khouloudbelguith 

Correct, ALL SHOPS are selected

**Comment by khouloudbelguith** [comment] 2019-08-20 13:53
@01park, We need to retrieve the PHP error log in order to find out what's wrong.
If you don't have it, you should ask your hosting provider.
Thanks!

**Comment by 01park** [comment] 2019-08-20 13:55
@khouloudbelguith 

I will contact them.

**Comment by khouloudbelguith** [comment] 2019-08-20 14:02
@01park, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-09-19 07:35
Hi @01park,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by 01park** [comment] 2020-01-16 12:39
Hi,

Im still having this issue with 1.7.6.2. Maybe you can help with:

I attached a screen shot of my php.ini file, is this what you're looking for?,

Do I need to have a certain PHP extension installed to make the work?


<img width="1011" alt="Screenshot 2020-01-16 at 12 41 07" src="https://user-images.githubusercontent.com/46492443/72526107-8f914e00-385d-11ea-9f19-692f84f0f62a.png">

**Comment by khouloudbelguith** [comment] 2020-01-16 12:45
Hi @01park,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by 01park** [comment] 2020-01-16 12:50
Hi @khouloudbelguith 

I don't understand where to get the error log files from. Do I need to get them by SSH?

**Comment by khouloudbelguith** [comment] 2020-01-16 12:59
@01park, To turn on the Debug mode on PrestaShop 1.7, follow these steps:

1. Got to Advanced Parameters > Performance
2. In the Debug Mode section, set “Debug Mode” to “Yes”.
3. Click the “Save” button.

You can find logs in the path `/Project_Folder/var/logs/`.

Thanks!

**Comment by 01park** [comment] 2020-01-16 13:11
Where do I find this?
"You can find logs in the path /Project_Folder/var/logs/."

Is this in file management?

**Comment by khouloudbelguith** [comment] 2020-01-16 13:20
@01park, your Project folder PrestaShop: https://github.com/PrestaShop/PrestaShop/tree/develop/var/logs

Thanks!

**Comment by 01park** [comment] 2020-01-16 13:30
<img width="423" alt="Screenshot 2020-01-16 at 13 29 41" src="https://user-images.githubusercontent.com/46492443/72529011-4bee1280-3864-11ea-846e-22ecafc0006f.png">


Is this what your looking for, I found it in var/logs

**Comment by khouloudbelguith** [comment] 2020-01-16 13:44
@01park, yes!

Thanks!

**Comment by 01park** [comment] 2020-01-16 13:47
so what exactly  do you need? with file?

Question can I delete all these files? incl. dev. log and prod.log. 

Second piece of information, when I clear cache, the same thing happens. browser becomes non responsible until the cache is emptied

**Comment by khouloudbelguith** [comment] 2020-01-16 13:49
@01park, thanks to provide me `dev.log` & `prod.log`.

Thanks!

**Comment by 01park** [comment] 2020-01-16 13:53
<img width="1128" alt="Screenshot 2020-01-16 at 13 53 13" src="https://user-images.githubusercontent.com/46492443/72530598-9a50e080-3867-11ea-8615-5f5fc8a6eb83.png">

**Comment by 01park** [comment] 2020-01-16 13:54
im now getting this error with debug mode on
do you know what this is?

**Comment by khouloudbelguith** [comment] 2020-01-16 14:13
@01park, it seems that this issue ir related to the ps_newproducts module
![image](https://user-images.githubusercontent.com/16067358/72531828-92e30480-3872-11ea-9d41-7668d9360b35.png)

What is the exact version of the ps_newproducts did you use?
In the meantime, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by 01park** [comment] 2020-01-16 14:22
Im using version 1.01 new products.

No sure if this has anything to do with it, but I recently applied this fix:

https://github.com/PrestaShop/PrestaShop/pull/14558

**Comment by khouloudbelguith** [comment] 2020-01-16 14:33
@01park, could you please try to remove this fix, clear cache & check if you have the same issue.

Thanks!

**Comment by 01park** [comment] 2020-01-16 15:34
I tried to putting things back, but doesn't seem to, only making things worse.

I'll wait until 1.7.7 comes out any idea when this will happen?

Regarding the issue what this is all about.

php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"}

What does the mean, I found this the dev.log file. Maybe this RESET is the major problem why I have to wait for my execution time to pass to be able to access the site again. After clearing cache and rebuilding search index

**Comment by khouloudbelguith** [comment] 2020-01-16 15:39
@01park,
>php.INFO: User Deprecated

It is not an error, it is a just a PHP information.

>I'll wait until 1.7.7 comes out any idea when this will happen?

We are still working in the PS1.7.7.0.
You can follow our Project: https://github.com/PrestaShop/PrestaShop/projects/7
Since, I cannot reproduce the issue, It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-16 15:39 UTC
Labels: Bug, BO, Can't reproduce, Search, 1.7.6.0, 1.7.6.2
