### ISSUE TITLE
bad URL on Ajax combination change

### ISSUE THREAD

**Issue by kubjak** [PrestaShop/PrestaShop#12197] opened 2019-01-17 15:46 UTC
With multiple languages enabled, when changing combination, the default url to load the given controller is not only the root URL with /index.php, though /lang/index.php , rendering the request a 404 result.

Actually: /en/index.php?controller...
Should be: /index.php?controller...

1. Go to a product with combination
2. Click on any attribute and modify it.
3. The error appears "An error occurred while processing your request"

**Screenshots**
![image](https://user-images.githubusercontent.com/46787613/51330104-270b6780-1a77-11e9-953a-4e59ab0f20a6.png)
![image](https://user-images.githubusercontent.com/46787613/51330125-2f63a280-1a77-11e9-8497-81bab99a8af0.png)

This issue is only around in multilingual version of Frontend.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: FPM  7.0.30-0+deb9u1

**Comment by khouloudbelguith** [comment] 2019-01-17 15:49
Hi @kubjak,

Thanks for your report.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9390 to fix the issue.
It is fixed in the PS1.7.5.0.
Your ticket is a duplicate of #9390
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-17 15:49
Duplicate of #9390

**Closed as completed by khouloudbelguith** 2019-01-17 15:49 UTC
Labels: Duplicate

**Comment by kubjak** [comment] 2019-01-17 16:38
Could reproduce it as well with 1.7.5.0, but found the problem was with PHP-FPM 7.0 as proxy,
switched to php7.2 direct, its working.
