### ISSUE TITLE
Fallback when some details are missing for a theme during install

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#28649] opened 2022-06-01 11:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I just tried reinstalling my shop on which I have another theme I quickly made a long time ago. It was only to explain how the child feature works, and I didn't take the time to add a preview image or the version in the `theme.yml`.

Because these details are missing, the theme takes a lot of space for nothing: Image link broken & no version displayed.

![image](https://user-images.githubusercontent.com/6768917/171393802-58187f7b-5303-4428-9f6b-ef438764950e.png)

### Expected behavior

- For the preview: Either displaying a fallback image 
![image](https://user-images.githubusercontent.com/43613217/188489581-c60bcd73-2a81-4601-811b-af39d5c6a1b9.png)

- For the version: displays `N/A` (Admin.Global)

### Tech investigation 

- [ ] Check how do we test with proper child theme

### Steps to reproduce

I think you can quickly reproduce this issue by duplicating the `classic` theme, then remove the file preview.png and the version in the yml file

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment] 2022-06-01 15:43
Hello @Quetzacoalt91 

Thanks for reporting the issue!
I was able to reproduce the issue with PrestaShop version 8.0.0 (develop). I’ll add this to the debug backlog so that it’s fixed.

![image](https://user-images.githubusercontent.com/23308427/171445162-6430c57d-362b-4be7-93d7-6b47cbfd10db.png)

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. 
Waiting for your PR :rocket: :muscle: 

Thank you

**Comment by MatShir** [comment] 2022-06-27 13:40
@TristanLDD Could you design a fallback image for the installer ? :)

**Comment by TristanLDD** [comment] 2022-09-05 15:19
Hi, here is the fallback image : 

<img width="279" alt="fallback_theme_img" src="https://user-images.githubusercontent.com/27484094/188480030-214b5424-83c3-4281-abfa-d9c160536d65.png">

**Comment by matks** [comment] 2022-09-12 09:19
Handled by @nicosomb in https://github.com/PrestaShop/PrestaShop/pull/29615

**Comment by matks** [comment] 2022-10-19 07:45
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29615

**Closed as completed by matks** 2022-10-19 07:45 UTC
Labels: Bug, UX ✔️, 8.0.x, Minor, IN, Theme & logo, Fixed, PR available, Verified
