### ISSUE TITLE
Prestashop 1.7.5.1 module tab not working

### ISSUE THREAD

**Issue by willymuigai** [PrestaShop/PrestaShop#13026] opened 2019-03-23 16:03 UTC
**Describe the bug**
When opening Modules catalog page the error is Internal Server Error try again
When opening the Module Manager page the error is

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**To Reproduce**
1. Go to 'modules'
2. Click on 'modules catalog and modules manager'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![image](https://user-images.githubusercontent.com/25971572/54868514-43d95980-4d9e-11e9-8984-b113b3c4423f.png)

![image](https://user-images.githubusercontent.com/25971572/54868519-52c00c00-4d9e-11e9-8ccf-808f428326f8.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-03-25 09:19
Hi @willymuigai,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-24 08:24
Hi @willymuigai,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-24 08:24 UTC
Labels: BO, Modules, Modules catalog, No change required, 1.7.5.1
