### ISSUE TITLE
FR: Retain order of images at combination level

### ISSUE THREAD

**Issue by ProBackup-nl** [PrestaShop/PrestaShop#14338] opened 2019-06-23 17:43 UTC
When uploading product images in BO, an order is applied based on field "id_image". One can reorder the order in which images appear, by drag and drop, in which case field "position" is changed as well as display in BO and FO.

In case of a product with combinations, the same images may be selected for a combination. However the "position" is lost at the combination level, and all product images appear in "id_image" order.

I think that it is human logic to have the same ordering of images at the "combinations" level.

Current workaround is to delete all product images, and upload the images again in the exact required order at the combination level. That is not human efficient.

When not being able to change the order at the combination level, at least use the order of images as of at its product level.

[FO][BO][combinations][1.7.5.2]

**Comment by khouloudbelguith** [comment] 2019-06-24 08:50
Hi @ProBackup-nl,

I did not manage to reproduce the issue with PS1.7.6.0(Branch1.7.6.x) & PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/13dzAjHLpyw4BkckV2nrBNfLnEE1h_ATB/view
Thanks to check & feedback.

**Comment by ProBackup-nl** [comment] 2019-06-24 12:39
@khouloudbelguith I am sorry. This is the 2nd time where I am sure that the issue was there and at a later point in time I am also unable to reproduce.

**Comment by matks** [comment] 2019-06-24 12:40
> @khouloudbelguith I am sorry. This is the 2nd time where I am sure that the issue was there and at a later point in time I am also unable to reproduce.

Don't be sorry 😉PrestaShop is a big and complex software, so we have this kind of bugs around that occur only for very specific settings. It's always good to have feedback, even if no bug is reported at the end 😄

**Comment by khouloudbelguith** [comment] 2019-06-24 12:42
@ProBackup-nl, thanks for your feedback.
Since you can not reproduce it anymore, I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-24 12:42 UTC
Labels: Can't reproduce, Image, Combinations, 1.7.5.2
