### ISSUE TITLE
free gift and invoice

### ISSUE THREAD

**Issue by benlecoqartisans** [PrestaShop/PrestaShop#13757] opened 2019-05-11 10:09 UTC
Total products is wrong in invoice when you apply a reduction with free gift because reduction is not added.
In database, you don't have reduction in ps_orders.total_discount

1. Create a discount with free gift
2. Create a cart with this free gift
3. On the invoice, total products amount is wrong (and VAT also by the way)

**Screenshots**

![image](https://user-images.githubusercontent.com/48204607/57568294-9a016b00-73e5-11e9-81b0-5fc3f9488937.png)

**Comment by khouloudbelguith** [comment] 2019-05-13 09:37
Hi @benlecoqartisans,

We are aware of this issue.
Your ticket is a duplicate of #9757
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-13 09:37
Duplicate of #9757

**Closed as completed by khouloudbelguith** 2019-05-13 09:37 UTC
Labels: Duplicate
