### ISSUE TITLE
PrestaShop 1.7 image compression create noise on white background image

### ISSUE THREAD

**Issue by vincentsuperscale** [PrestaShop/PrestaShop#14950] opened 2019-08-01 12:01 UTC
**Description of the bug:**
When adding product images in the PrestaShop back-office, the generated (resized) images of the product contains some strange grey pattern if the background of the image is white.

The problem occurs even if the JPG quality is set to 100/100 and no matter what format is used (JPG/PNG).

The pattern is visible on most screen and is highly visible if you drop the luminosity of the picture in PhotoShop or any other image viewer.

The bug seems to have appeared since PrestaShop 1.7. I have not seen any PrestaShop 1.6 websites with this problem.

**To reproduce:**
Go to any PrestaShop back-office, upload a picture of a product that is on a white background.
Go in the front-office, download the product image in any format.
If you don't see the grey pattern, the drop the luminosity on PhotoShop and it will appear very clearly.

**Screenshots**
Image generated by PrestaShop:
![test_1_original](https://user-images.githubusercontent.com/42002176/62291583-991c2a80-b464-11e9-979a-515355ea0665.jpg)

With lower luminosity:
![test_2_low_luminosity](https://user-images.githubusercontent.com/42002176/62291599-a33e2900-b464-11e9-9b9b-d43032cadaa1.jpg)

Others random PrestaShop 1.7 website with the problem - Luminosity dropped by 80%:
![test3](https://user-images.githubusercontent.com/42002176/62291693-daacd580-b464-11e9-88c0-c740e733f57e.png)
![test4](https://user-images.githubusercontent.com/42002176/62291697-dc769900-b464-11e9-8288-5fe2ad62744a.png)

**Additional information**
PrestaShop version: 1.7.X
PHP version: 5.6 & 7.3 tested

**Comment by khouloudbelguith** [comment] 2019-08-01 12:38
Hi @vincentsuperscale,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/10Q5JGhbgftH07fM06M9sh2YjWXhKMMy-/view
I tried with this link: https://www.collectionsetvous.com/nos-coups-de-coeur/729-picsou-.html & it is OK.
![image](https://user-images.githubusercontent.com/16067358/62293922-9f5cd780-b461-11e9-86d1-e4c7a56ccdac.png)

Thanks to check & feedback.

**Comment by vincentsuperscale** [comment] 2019-08-01 12:50
@khouloudbelguith Hi,

I think that the object in your image is too thin, can you try with the following picture:
![test_1_original](https://user-images.githubusercontent.com/42002176/62294605-9cff7b00-b46b-11e9-85cd-bb74e57e5c85.jpg)

Also, on https://www.collectionsetvous.com/nos-coups-de-coeur/729-picsou-.html it's mostly visible on retina screen, and as I said you can also lower the luminosity to see the pattern (horizontal or vertical lines appearing).

**Comment by khouloudbelguith** [comment] 2019-08-01 13:06
@vincentsuperscale, I tried again with this image & I tried to decrease the luminosity & it is OK
![image](https://user-images.githubusercontent.com/16067358/62295701-90782400-b465-11e9-8ade-ded8b9f1000b.png)
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-02 07:16
Hi @vincentsuperscale, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-02 07:16 UTC
Labels: FO, Image, Topwatchers, No change required

**Comment by radekml** [comment] 2020-08-25 13:01
I have the same problem in Prestashop 1.7.6.4. The uploaded photos are 1500 x 1500 px resolution. Changing JPG quality and compression to 100 does not change anything. @vincentsuperscale did not respond and the topic was closed, but rather nothing was solved.

Each picture in a white background has ugly noises visible on some screens, especially when you look at the screen at an angle or if you drop the luminosity of the picture in PhotoShop or any other image viewer.

Below you can see the lowered luminosity in Photoshop also from the photo which @khouloudbelguith suggested to test: 
![luminosity](https://user-images.githubusercontent.com/60894502/91177629-5028bb00-e6e4-11ea-8271-19f0f9930285.jpg)

**Comment by eternoendless** [comment] 2020-09-04 16:34
PrestaShop uses the [GD library](https://www.php.net/manual/en/book.image.php) for image manipulation. If the quality is effectively 100/100, then it might be a problem with the library itself and/or how it was compiled. To  my best understanding this part of PrestaShop hasn't been changed since 2012/2015.

I don't see what we can do to help it, especially if we can't reproduce.

**Comment by uruk-hai-21** [comment] 2021-06-20 14:11
Same for me. This is my GD configuration:
![Schermata 2021-06-20 alle 16 09 59](https://user-images.githubusercontent.com/12673007/122677303-15978e00-d1e2-11eb-8db6-9f95808b82d5.png)

**Comment by nicolashsymediane** [comment] 2021-10-04 14:54
Hi,

I still have this issue on Presta 1.7.7.8, any solution ?

**Comment by gouna15** [comment] 2022-06-21 21:51
Hello,
I have same problem on a prestashop 1.7.6.8

**Comment by uruk-hai-21** [comment] 2022-06-24 10:22
> Hello, I have same problem on a prestashop 1.7.6.8

Try to add in css this:
```
.class img {
         filter: brightness(1.01);
}
```
