### ISSUE TITLE
getUriFromPath strips slashes when PS js 

### ISSUE THREAD

**Issue by edspiner** [PrestaShop/PrestaShop#14024] opened 2019-05-30 08:56 UTC
**Describe the bug**
When the web server is chrooted to DOCUMENT ROOT of the web application the getUriFromPath function will strip all slashes from the path, so they look like:
`http://someshop.examplethemeassetsstyle.css`
The issue happens because of:
```
str_replace('/', rtrim('/', '/'), '/theme/path/to/asset.css')
```

**To Reproduce**
1. Chroot the server to web servers DOCUMENT_ROOT
2. Install PS
3. Visit frontend
4. Path to JS and CSS are stripped from slashes 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-30 09:10
Duplicate of #14025

**Closed as completed by khouloudbelguith** 2019-05-30 09:10 UTC
Labels: Duplicate
