### ISSUE TITLE
{id_order_return} and {state_order_return} at order_return_state.html template not filled

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#27312] opened 2022-01-11 17:05 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

{id_order_return} and {state_order_return} at order_return_state.html template is not filled.

I receive the email with the variables and not the correct values.

### Steps to reproduce

Send e-mail with order_return_state.html template 

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment] 2022-01-11 17:39
Hello @seederp2p ,

I can't reproduce your issue in PS 1.7.7.8 nor PS 1.7.8.x.

{id_order_return} and {state_order_return} are displayed correctly. Here's the result I have : 
<img width="608" alt="Screenshot 2022-01-11 at 18 28 27" src="https://user-images.githubusercontent.com/16019289/148992003-af9b645d-3235-46c4-acf9-1a64783581df.png">

You can check if you have any override from an external module.

As I can't reproduce the issue, I will close it.
Thanks!

**Closed as completed by florine2623** 2022-01-11 17:39 UTC
Labels: Bug, Invalid
