### ISSUE TITLE
Order page 'Payment block' layout is under the 'Messages block'.

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#11957] opened 2018-12-30 21:41 UTC
Order page 'Payment block' layout is under the 'Messages block'.

Using PS1.7.4.4

![ps order page layout](https://user-images.githubusercontent.com/22105014/50551605-8b5ab880-0c7b-11e9-8288-69ed6164ce17.jpg)

**Comment by khouloudbelguith** [comment] 2018-12-31 07:48
Hi @gray-b 

I did not manage to reproduce the issue with the version PS 1.7.4.4 & PS 1.7.5.0.
I attached a screenshot.
![11957](https://user-images.githubusercontent.com/16067358/50556389-c9d29080-0cd8-11e9-917c-f79ce0f92cca.png)
Thanks to check and feedback.

Thanks,
Khouloud

**Comment by gray-b** [comment] 2018-12-31 18:37
Any idea why I have got it. Have you tested it on different screen sizes?

**Comment by khouloudbelguith** [comment] 2019-01-02 07:52
Hi @gray-b,

Sorry, we manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9863
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-02 07:53
Duplicate of #9863

**Closed as completed by khouloudbelguith** 2019-01-02 07:52 UTC
Labels: Duplicate, Order

**Comment by gray-b** [comment] 2019-01-02 09:35
I reported this on http://forge.prestashop.com/browse/BOOM-6135 but no action

**Comment by khouloudbelguith** [comment] 2019-01-02 09:47
@gray-b, yes it is the same issue here https://github.com/PrestaShop/PrestaShop/issues/9863, it is added to our bug roadmap but it is not fixed yet.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.
Thanks!
