### ISSUE TITLE
Error 500 Prestashop 1.7.5.2 + PHP 5.6.40-0+deb8u3 only when logging in backoffice

### ISSUE THREAD

**Issue by racfalit** [PrestaShop/PrestaShop#13996] opened 2019-05-28 09:39 UTC
Hello Good afternoon, I have a problem with my online store. At random from time to time, it can be 4 days, 1 week ... it gives me an error 500 when I try to access the Backoffice of my shop simply by entering and modifying articles, without installing any module or anything special.

We have deleted cache and nothing, I was also looking and delete these files and nothing:

www / var / cache / _prod / classes.map
www / var / cache / _prod / classes.php
I had to call my hosting and they had to restart the web server and it seems that it started working.

This is the error that I indicated from the hosting:

 [Tue May 28 08:27:04.274861 2019] [:error] [pid 23833] [client 188.78.22.26:49727] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34, referer: https://www.librephonia.com/admin443a84cyn/index.php?controller=AdminLogin&token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[Tue May 28 08:27:15.969631 2019] [:error] [pid 23683] [client 188.78.22.26:49733] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:27:17.505677 2019] [:error] [pid 23218] [client 188.78.22.26:49734] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:27:19.254854 2019] [:error] [pid 23820] [client 188.78.22.26:49738] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:27:20.417658 2019] [:error] [pid 23692] [client 188.78.22.26:49740] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:27:45.649005 2019] [:error] [pid 23791] [client 188.78.22.26:49747] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:27:54.277167 2019] [:error] [pid 23218] [client 188.78.22.26:49748] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:31:38.404804 2019] [:error] [pid 24079] [client 188.78.22.26:49800] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:31:41.508690 2019] [:error] [pid 24088] [client 188.78.22.26:49799] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:32:05.067220 2019] [:error] [pid 24069] [client 188.78.22.26:49808] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:32:13.992657 2019] [:error] [pid 24084] [client 188.78.22.26:49810] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 0
[Tue May 28 08:33:27.561423 2019] [:error] [pid 24321] [client 188.78.22.26:49827] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34, referer: https://www.librephonia.com/admin443a84cyn/index.php?controller=AdminLogin&token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[Tue May 28 08:58:59.306719 2019] [:error] [pid 26240] [client 188.78.22.26:49986] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 08:59:36.621755 2019] [:error] [pid 26504] [client 188.78.22.26:50048] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34
[Tue May 28 09:02:20.973862 2019] [:error] [pid 26677] [client 188.78.22.26:50035] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 34, referer: https://www.librephonia.com/admin443a84cyn/index.php?controller=AdminLogin&token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[Tue May 28 09:02:55.651599 2019] [:error] [pid 27856] [client 188.78.22.26:50055] PHP Fatal error:  Cannot redeclare class AppKernel in /srv/neoatica/hosting/00000075/librephonia.com/web/www/app/AppKernel.php on line 0, referer: https://www.librephonia.com/admin443a84cyn/index.php?controller=AdminLogin&token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Can someone please help me? I've been looking for information everywhere and I do not see anything that can help me. Someone who knows that it can happen or as if it were a clue if the template could be a module hosting ... Thanks in advance to everyone.

**Comment by khouloudbelguith** [comment] 2019-05-28 09:44
Hi @racfalit,

You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks to check & feedback

**Comment by racfalit** [comment] 2019-05-28 09:51
Thanks for the answer but the problem is not when modifying articles is when I log in in the backoffice that does not let me enter

**Comment by khouloudbelguith** [comment] 2019-05-28 09:53
@racfalit, thanks for your feedback.

When debug mode enabled, there is no exception displayed?
Thanks!

**Comment by racfalit** [comment] 2019-05-28 09:56
When I enter debugging mode I get these errors:
- AppKernel.php on line 34
- AppKernel.php on line 0
- PHP Fatal error: Cannot redeclare class AppKernel in

**Comment by khouloudbelguith** [comment] 2019-05-28 10:13
Hi @racfalit 

After removal of cache rm -fR var/cache/* thanks to run those commands:

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks to check & feedback

**Comment by racfalit** [comment] 2019-05-28 10:18
Sorry but I'm pretty newbie. Do these commands that you have put me have to do if you give me the error again?

**Comment by khouloudbelguith** [comment] 2019-05-28 10:22
@racfalit, those commands clear cache from your local & prod environment.
Thanks!

**Comment by racfalit** [comment] 2019-05-28 10:27
Thanks, but what do I do now or when I get the 500 error?

**Comment by khouloudbelguith** [comment] 2019-05-28 10:30
@racfalit, could you please provide me the credentials of your shop to test it.
This is a public space.
You can provide me the access by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by racfalit** [comment] 2019-05-28 10:33
what do you need? FTP and Backoffice?

**Comment by khouloudbelguith** [comment] 2019-05-28 10:34
@racfalit, no just Back office.
Thanks!

**Comment by racfalit** [comment] 2019-05-28 10:37
is already in your email. Thnks

**Comment by khouloudbelguith** [comment] 2019-05-28 10:53
@racfalit, I tried a few times, but it is OK.
I sent you a video record via email.
Thanks!

**Comment by racfalit** [comment] 2019-05-28 11:02
Thank you very much for the time you are dedicating me. I know that right now it does not fail, it was this morning when it failed and my hosting cleaned the cache and restarted the web server and now it works. But we do not know how to identify the failure so that it does not happen again :( Do you not know why those failures may be that I indicated earlier?

**Comment by khouloudbelguith** [comment] 2019-05-28 11:03
@racfalit, if your issue is solved after clearing the cache, so it is a cache issue.
Thanks!

**Comment by racfalit** [comment] 2019-05-28 11:05
It has not been fixed when clearing the cache, it has been fixed when restarting the web server of the hosting

**Comment by khouloudbelguith** [comment] 2019-05-28 11:09
@racfalit, 
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration.

Thanks!

**Comment by racfalit** [comment] 2019-05-28 11:13
ok thank you very much for everything, just one last question, in case it was the server could you give me some recommendation? The current PHP version is fine for the prestashop 1.7.5.2?

**Comment by khouloudbelguith** [comment] 2019-05-28 11:19
@racfalit, PrestaShop 1.7.5 supports all versions of PHP from 5.6 to 7.2, but not the latest 7.3
Thanks!
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-28 11:19 UTC
Labels: Bug, BO, No change required, 1.7.5.2
