### ISSUE TITLE
translation ps_wirepayment is uncomplete

### ISSUE THREAD

**Issue by ebonit** [PrestaShop/PrestaShop#10593] opened 2018-09-21 10:01 UTC
**Description**
The last 5 lines of the template modules/ps_wirepayment/views/templates/hook/payment_return.tpl are missing in the translation backoffice page Modules->Wirepayment->Shop

**To Reproduce**
1. In the backoffice go to '/index.php/international/translations?lang=nl&type=modules&selected=ps_wirepayment&locale=nl-NL' or en_US
![schermafbeelding 2018-09-21 om 11 58 16](https://user-images.githubusercontent.com/13302588/45874649-b76dc000-bd95-11e8-8bd2-fc4be64f1bda.png)

2. Click on 'Shop'
3. Scroll down 
4. the following strings cannot be found:

- 'Please specify your order reference %s in the bankwire description.'
- 'We\'ve also sent you this information by e-mail.'
- 'Your order will be sent as soon as we receive payment.'
- 'If you have questions, comments or concerns, please contact our [1]expert customer support team[/1].'
- 'We noticed a problem with your order. If you think this is an error, feel free to contact our [1]expert customer support team[/1].'

5. these strings are missing in the file ModuleWirepaymentShop.en-US.xlf and also in other language files

**Additional information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2018-09-21 10:02
Hi @ebonit,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9697
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-21 10:02
Duplicate of #9697

**Closed as completed by khouloudbelguith** 2018-09-21 10:02 UTC
Labels: Duplicate
