### ISSUE TITLE
Modifying an address in order table creates another address instead of changing the original one

### ISSUE THREAD

**Issue by Uff182** [PrestaShop/PrestaShop#12170] opened 2019-01-16 11:04 UTC
**Describe the bug**
Once an order is placed, you can modify one of the addresses. This will open the address tab; once you click on Save, a new address will be added to Prestashop instead of modifying the existing one. This worked properly in PS 1.6, but it doesn't in PS 1.7.

**To Reproduce**
1. Place an order
2. Open the order in backoffice
3. Click on Modify next to the address
4. Check the list of addresses in backoffice to see that a new address was added

**Screenshots**

![order_tab_00](https://user-images.githubusercontent.com/11455502/51244919-93f30480-1986-11e9-8591-185e6a492177.jpg)

![order_tab_01](https://user-images.githubusercontent.com/11455502/51244930-9b1a1280-1986-11e9-94dc-90d26a894add.jpg)

**Additional information**
PrestaShop version: 1.7
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-01-16 11:19
Hi @Uff182,

Have you the same issue with this ticket: #11199?
Thanks!

**Comment by Uff182** [comment] 2019-01-16 11:29
Hi @khouloudbelguith , no, the issue is different. The reported ticket refers to the fact that the suggested addresses are wrong, in my case I'm reporting the fact that the address you want to modify is left untouched and a new one is created. Let's say that in the first address you wrote "Street name, number 42", but you actually meant "Street name, number 41", you will end up with two addresses that are basically equals, qith just that detail changed.
This also causes problems when we develop a module that requires address id to display previously saved data (related to that ID): while on 1.6 the additional data are displayed, in 1.7 those informations are lost because the order gets a new address.

**Comment by khouloudbelguith** [comment] 2019-01-16 15:49
@Uff182, thanks for this clarifications.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
We will see how to fix it.
Thanks!

**Comment by ghost** [comment] 2019-01-22 00:53
Hello,
I think it's crazy to can change an invoice address
The best way is to deleted this button when a invoice is set to an order.

https://www.prestashop.com/fr/blog/module-de-certification-article88

**Comment by MatShir** [comment] 2019-01-30 13:50
Hi @Uff182 and @okom3pom,

@Uff182 you are right, it's a bug if we allow editing it should be without adding a new address for the customer. For now, the only way to not pollute your addresses database it's to change it on 'Addresses' directly in 'Customer' menu (not the fastest way). 

But as @okom3pom said with the new data regulation (88 article and RGPD and so on), we need to be careful. Our jurist team is working on this specific question.

We will come with the new answer soon. 
Thank you all for your feedback.

**Comment by MatShir** [comment] 2019-01-31 17:35
Hello @Uff182 and @okom3pom,

So any customer can ask to change their address before billing so in some cases the feature is required. But a merchant can't change the invoice when it is sent to the customer. @okom3pom, in the next version we will improve the feature blocking addresses changes when the invoice was sent to the customer.

Thank you all,

**Comment by ghost** [comment] 2019-02-01 11:21
Thank's

**Comment by simonecicognani** [comment] 2019-03-27 16:35
Reproduced in PS1.7.4.4
- Account with just shipping address (billing is same as the shipping)
- Remove check "Use this address also for the billing"
- Add the billing address
So now I have 3 shipping addresses and 3 billing addresses

**Comment by blks** [comment] 2019-04-23 14:24
Reproduced in PS 1.7.5 
When changing addressee in addition of creating a new addressee , shipping fees are not being recalculated correctly (because shipping fees are related to state_id, when changing state => shipping fees should be recalculated).

**Comment by marionf** [comment] 2019-05-10 07:34
Related to #12394 & #13537

**Comment by SharmPRO** [comment] 2019-06-20 17:40
The creation of a new address id will trigger error while a cart is already created with a certain id_address. In checkout process will not find any currier for address.
Cart data need to me updated with new id_address

**Comment by matthieu-rolland** [comment] 2019-09-09 08:21
To sum up:

It is normal that when we edit an address that has already been used in a completed order, it creates another entry in the database.

What we want to do here is to keep the backoffice from being able to link a completed invoice to another address. An invoice's address should always be the same once it has been sent to the customer.

**Comment by Uff182** [comment] 2019-09-09 08:34
> To sum up:
> 
> It is normal that when we edit an address that has already been used in a completed order, it creates another entry in the database.
> 
> What we want to do here is to keep the backoffice from being able to link a completed invoice to another address. An invoice's address should always be the same once it has been sent to the customer.

Hi, it is not normal though that, if you edit an order which is (for example) in a status like "Awaiting payment with bank transfer", the website creates another address instead of modifying the current one I think.
In case the customer placed more than one order and the current address can't be modified because there are previous orders in completed status, instead, it would be useful to have a hook where we get the previous address ID and the new one (something link actionAddressDuplicationAfter): in this way we would be able to detect the address duplication and bring over custom informations assigned by our modules to the customer's address from the old to the new one.

**Comment by matthieu-rolland** [comment] 2019-09-09 08:55
Thank you for your suggestion @Uff182, I ping the pms for their input about this.

@colinegin, what do you think?

(In the mean time I'll talk about your hook suggestion with other core team developers)

**Comment by colinegin** [comment] 2019-09-09 14:34
> > To sum up:
> > It is normal that when we edit an address that has already been used in a completed order, it creates another entry in the database.
> > What we want to do here is to keep the backoffice from being able to link a completed invoice to another address. An invoice's address should always be the same once it has been sent to the customer.
> 
> Hi, it is not normal though that, if you edit an order which is (for example) in a status like "Awaiting payment with bank transfer", the website creates another address instead of modifying the current one I think.
> In case the customer placed more than one order and the current address can't be modified because there are previous orders in completed status, instead, it would be useful to have a hook where we get the previous address ID and the new one (something link actionAddressDuplicationAfter): in this way we would be able to detect the address duplication and bring over custom informations assigned by our modules to the customer's address from the old to the new one.

I've just tested it on 1.6, it seems the behaviour is the same. Could you give me more information about it ?

**Comment by colinegin** [comment] 2019-09-09 14:38
@SharmPRO your issue seems to be the same as #9932, we have a PR currently in test.

**Comment by MatShir** [comment] 2020-10-23 15:29
I can't reproduce the issue in the 1.7.7 version, the address is edit for the current order and new orders but the old one is kept the old address to avoid undesired changes.

Hi @khouloudbelguith or @florine2623 , when you have time could you do a double check on this issue? I think we can close it.

**Comment by florine2623** [comment] 2020-10-23 15:44
Hello @Uff182 @okom3pom ,
This issue has been fixed in PS 1.7.7. The whole order page has been reworked.
After modifying an existing address, there's no new address created.
Here's the result in order page :
![Capture d’écran 2020-10-23 à 17 42 38](https://user-images.githubusercontent.com/16019289/97024568-3f1aef80-1557-11eb-92a5-fa9fbfbe41d6.png)
And the address list in customer page :
![Capture d’écran 2020-10-23 à 17 42 53](https://user-images.githubusercontent.com/16019289/97024591-480bc100-1557-11eb-9e2e-13f66f5ae413.png)
So I'll close the issue.
Thanks !

**Closed as completed by florine2623** 2020-10-23 15:44 UTC
Labels: BO, Order, Invoices, Addresses, Fixed, 1.7.5.0

**Comment by Damian-Rutkowski** [comment] 2021-02-09 12:14
Hello,
here's a quick fix for those who can't or won't upgrade to 1.7.7.x:
Go to the following file via FTP using this path:
_admin123_/themes/default/template/controllers/orders/helpers/view (_admin123_ replace with your adminfolder)

open the file:
view.tpl

and best result is search for "displayAddressDetail".
above is a link with the classes "bin bin-default pull-right", modify the links here; instead of (for delivery):
`href="?tab=AdminAddresses&amp;id_address={$addresses.delivery->id}&amp;addaddress&amp;realedit=1&amp;id_order={$order->id}&amp;address_type=1&amp;token={getAdminToken tab='AdminAddresses'}&amp;back={$smarty.server.REQUEST_URI|urlencode}"`
must be:
`href="?tab=AdminAddresses&amp;id_address={$addresses.delivery->id}&amp;updateaddress&amp;realedit=1&amp;address_type=1&amp;token={getAdminToken tab='AdminAddresses'}&amp;back={$smarty.server.REQUEST_URI|urlencode}"`

and invoice:
`href="?tab=AdminAddresses&amp;id_address={$addresses.invoice->id}&amp;addaddress&amp;realedit=1&amp;id_order={$order->id}&amp;address_type=2&amp;back={$smarty.server.REQUEST_URI|urlencode}&amp;token={getAdminToken tab='AdminAddresses'}"`
change to:
`href="?tab=AdminAddresses&amp;id_address={$addresses.invoice->id}&amp;updateaddress&amp;realedit=1&amp;address_type=2&amp;back={$smarty.server.REQUEST_URI|urlencode}&amp;token={getAdminToken tab='AdminAddresses'}"`

what exactly did i change? Instead of "addaddress" I use "updateaddress" because I want to update it.

and the parameter "id_order=xx" also causes problems here. So i remove it.

My "troubleshooting" is superficial, I didn't check if everything works like this, but I see the resultat that should be, I come to the form where I can change the address, after I save I come back to the order (wasn't like this before) AND I see a changed address.
