### ISSUE TITLE
Version 1.7.6.2 emails are not saved after editing

### ISSUE THREAD

**Issue by kyripapa** [PrestaShop/PrestaShop#18417] opened 2020-04-01 10:39 UTC
Hello everyone,
I have an issue with editing the texts in version 1.7.6.2.
In the BO the texts seem changed (the body of the email), but the texts are not saved somehow in the files and the sent email is always the default one (without the changes)
I have found others that have the same issue [here ](https://www.prestashop.com/forums/topic/1002846-prestashop-1761-problem-the-translation-of-email-in-local-language-doesnt-work/)

Any ideas?
Kind Regards,

**Comment by khouloudbelguith** [comment] 2020-04-01 11:00
Hi @kyripapa,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1Q0UFNCeWJElA6JMZev-alUdjJueFg3PH/view?usp=sharing

PS: we cannot edit the translation which is in the core of the mails.
It is planned for PS1.7.7.0: #14809

Thanks to check & feedback.

**Comment by kyripapa** [comment] 2020-04-01 11:02
Hello and thank you for looking it.
Actually in the backoffice the text is changed as you saw it in the video you made, in my backoffice it is like that too (the texts are changed).
Did you try to send an email?Are the texts changed in the email too?
PS. I only have emails in the core, does that mean I should move them into a theme?

Kind Regards,

**Comment by khouloudbelguith** [comment] 2020-04-01 11:58
@kyripapa, as I said previously, we cannot edit the translation which is in the core of the mails.
It is planned for PS1.7.7.0: #14809.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-01 16:01
@kyripapa, I close the issue.
Feel free to open a new oen when needed.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-01 16:01
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/15474

**Closed as completed by khouloudbelguith** 2020-04-01 16:01 UTC
Labels: Bug, BO, Duplicate, Translations, Email, 1.7.6.2
