### ISSUE TITLE
The total is not well calculated with free gift

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16673] opened 2019-12-04 09:38 UTC
**Describe the bug**
After fixing this issue: https://github.com/PrestaShop/PrestaShop/issues/11722 in the develop branch.
2 uses cases are not ok in the develop branch as reported here: https://github.com/PrestaShop/PrestaShop/issues/11722#issuecomment-561220896
Issue 1:
Create the following rules:

- Rule 1
Amount discount:
![image](https://user-images.githubusercontent.com/16067358/70130654-32f91b80-1681-11ea-8db0-d8eeb789ea10.png)

- Rule 2
![image](https://user-images.githubusercontent.com/16067358/70130695-45735500-1681-11ea-94dc-a201d69660a6.png)

- Rule 3
Free gift
![image](https://user-images.githubusercontent.com/16067358/70130733-545a0780-1681-11ea-9685-8a4c9e56d407.png)

Cart:
![image](https://user-images.githubusercontent.com/16067358/70130931-c29eca00-1681-11ea-9af2-7a97ffb5ceaa.png)

Issue 2:
- Change the first rule:
![image](https://user-images.githubusercontent.com/16067358/70131022-e530e300-1681-11ea-96a1-60031ac1c35f.png)

- Discount is higher than the amount
![image](https://user-images.githubusercontent.com/16067358/70131172-22957080-1682-11ea-8961-43db0441c008.png)

In the PS1.7.6.2, the total is well calculated

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by Hlavtox** [comment] 2019-12-04 11:31
I think you need to revert my PR... :-(

If we take the price of the gift with FinalUnitPrice, it works with whatever cartrule amount, but doesnt work for more than 1 gift rule.

If, after the PR we get it with InitialUnitPrice, it works properly, BUT gift rules must go first. Which we unfortunatelly cannot enforce in the code, because user can select both discount and gift in one single cart rule...

**Comment by arouiadib** [comment] 2020-01-01 17:11
With the indicated cart rules configuration above and  in branch `develop`, the issues are not reproducible:

1st issue:
![Screenshot from 2020-01-01 17-41-56](https://user-images.githubusercontent.com/23559010/71643994-83d05400-2cc1-11ea-906e-d0767bd6a2a1.png)



2nd issue:
![Screenshot from 2020-01-01 18-01-25](https://user-images.githubusercontent.com/23559010/71644001-96e32400-2cc1-11ea-86aa-3cbe4a48e522.png)

Thanks to everyone

**Comment by idnovate** [comment] 2020-01-02 11:00
Another issue.

Create 2 `Free shipping` rules. Total is correct but discount amount doesn't.

![image](https://user-images.githubusercontent.com/15104724/71663966-71085e80-2d57-11ea-8532-ca5b671ec65d.png)

**Comment by arouiadib** [comment] 2020-01-02 12:49
I confirm the issue mentioned by @idnovate concerning multiple free shippings.

![image](https://user-images.githubusercontent.com/23559010/71667543-da8f6980-2d65-11ea-80f2-1b97248d2954.png)

Questions:

* Should the total discounts be `-10` in the scenario instead of `-20`?
* Do you have in develop `-0.00$` instead of `free shipping` ?

Thanks in advance.

**Comment by idnovate** [comment] 2020-01-02 13:42
> * Should the total discounts be `-10` in the scenario instead of `-20`?

YES

> * Do you have in develop `-0.00$` instead of `free shipping` ?

The screenshot was not in last PS version which fixed this issue ;)

**Comment by khouloudbelguith** [comment] 2020-01-02 13:57
Hi @arouiadib, @idnovate,

About this issue: https://github.com/PrestaShop/PrestaShop/issues/16673#issuecomment-570175986
With PS1.7.0.0(develop branch) => Issue is fixed:
![image](https://user-images.githubusercontent.com/16067358/71670415-04e62480-2d70-11ea-8cee-31891c774bab.png)
![image](https://user-images.githubusercontent.com/16067358/71670429-15969a80-2d70-11ea-92ee-11ea8d18357e.png)

Thanks!

**Comment by arouiadib** [comment] 2020-01-02 14:48
Ok @idnovate , makes sense. Thank you. 

@khouloudbelguith , could you please make a test when there is no carrier with free shipping? Just make sure the carriers have the status "free shipping" disabled. 

Because I feel that, @idnovate and me,  are performing tests when there are no free shipping carriers, or at least with products configured without free shipping.

Again thank you very much for your time.

**Comment by khouloudbelguith** [comment] 2020-01-02 15:44
@arouiadib, thanks for these clarifications.
>Create 2 `Free shipping` rules. Total is correct but discount amount doesn't.
![image](https://user-images.githubusercontent.com/15104724/71663966-71085e80-2d57-11ea-8532-ca5b671ec65d.png)

Yes, you are right to reproduce the issue we should have no carrier with free shipping with develop branch.
https://drive.google.com/file/d/15_C65TxgG5dMlV9SCfbnn3gBoInbXXJT/view
Ping @atomiix, this issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16724?

Thanks!

**Comment by arouiadib** [comment] 2020-01-05 23:08
Hi @khouloudbelguith ,

After merging @atomiix  PR: [#16724](https://github.com/PrestaShop/PrestaShop/pull/16724) with `develop` in localhost, I found that it doesn't include the solution to the latter problem mentioned by @idnovate (which is maybe not the aim of that PR).

Anyways, what if we close this issue and create a separate one for multiple free shipping rules? I think it will make things clearer because this current issue is fixed with or without #16724 (and already closed here #11722).

Thank you very much for your time.
Regards,

**Closed as completed** 2020-01-08 15:19 UTC
Labels: Bug, develop, Major, FO, Discounts, Cart rules, Regression, Fixed, Shopping carts FO
