### ISSUE TITLE
Devtools error in Back Office

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#29201] opened 2022-07-29 11:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The following error is being reported by the browser (in my case Chrome) when viewing the list of orders in the back office on a fresh install of Prestashop 1.7.8.6:

`DevTools failed to load source map: Could not load content for https://mysite.test/adminroci/themes/new-theme/public/bootstrap-colorpicker.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

I can confirm the source map file file is indeed missing from the official download.  

### Steps to reproduce

1.  Login into the back office on a fresh install of Prestashop 1.7.8.6
2. Open Up Dev tools in your browser
3. Navigate to the list of orders in the back office
4.  In the browser console, the error detailed above will appear

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by hibatallahAouadni** [comment] 2022-07-29 16:43
Hello @musaffar-patel 

I was able to reproduce the issue with PrestaShop version 1.7.7.7, 1.7.8.6 and 8.0.0.
I’ll add this to the debug backlog so that it’s fixed.

![image](https://user-images.githubusercontent.com/23308427/181806401-488a640a-c841-4c1b-8088-65bc380b7ef6.png)

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment] 2024-11-05 09:44
Hello,

Checked on PS 9.0.x, I cannot find this error anymore.
It is fixed, so I'm closing the issue.

![Image](https://github.com/user-attachments/assets/f7c70f96-7d4c-45cd-a99c-24d786cb4b36)


Thanks!

**Closed as completed by florine2623** 2024-11-05 09:44 UTC
Labels: Bug, Trivial, BO, Fixed, Verified
