### ISSUE TITLE
Product falls from search index after update

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#16443] opened 2019-11-16 11:07 UTC
**Describe the bug**
If you update an existing product it is no longer listed in the search index.
And you have to manually 'add missing products to index'

**To Reproduce**
1. Go to a product, any product
2. Click on save
3. Scroll down to the search index page
4. See that one product is missing from the index (the product you just saved)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7

**Comment by khouloudbelguith** [comment] 2019-11-18 08:39
Hi @sickboards,

I did not manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/1I3Nmcmf5XtLivftsKs1MgmGx3kj5bisE/view
But, it could be your issue similar to those problems:
1. https://github.com/PrestaShop/PrestaShop/issues/15640 not fixed yet.
2. https://github.com/PrestaShop/PrestaShop/issues/10530 fixed in the PS1.7.6.0.
3. https://github.com/PrestaShop/PrestaShop/issues/9663 fixed in the next version PS1.7.7.0.

Thanks to check & feedback.

**Comment by sickboards** [comment] 2019-11-18 10:28
Hi, it seems pretty similar to https://github.com/PrestaShop/PrestaShop/issues/15640
can you try actually changing something in the product?

**Comment by khouloudbelguith** [comment] 2019-11-18 10:42
@sickboards,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15640
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-11-18 10:42
Duplicate of #15640

**Closed as completed by khouloudbelguith** 2019-11-18 10:42 UTC
Labels: Bug, BO, Duplicate, Search, 1.7.5.2
