### ISSUE TITLE
1.7.7 upgrade error Expected to find class PrestaShopBundle\Controller\Admin\Sell\index in file

### ISSUE THREAD

**Issue by Jojo-Kaly** [PrestaShop/PrestaShop#22275] opened 2020-12-07 15:09 UTC
Hi !

I tried to upgrade my Prestashop from 1.7.6.3 to 1.7.7 with 1-Click Upgrade 4.10.1 but I have an error 500 in back office.
See screenshot to see errors.
PHP version 7.2.34.

Thank you for your help.

<img width="1440" alt="Capture d’écran 2020-12-07 à 12 32 28" src="https://user-images.githubusercontent.com/59056657/101367534-8dd1de00-38a6-11eb-8137-cf97154e4428.png">

**Comment by PierreRambaud** [comment] 2020-12-07 15:55
HI @Jojo-Kaly 
Could you please give us the full Error stack trace?

**Comment by SimonGrn** [comment] 2020-12-07 15:56
Hello @Jojo-Kaly 

>PHP version 4.2.34.

Is this a typo ?

**Comment by hibatallahAouadni** [comment] 2020-12-08 08:40
Hello @Jojo-Kaly 

If your PHP version is 4.2 and not a typo as @SimonGrn mentioned, you need to upgrade your PHP version to 7.2.
Then try again upgrading.

Please check and feedback.

Thanks!

**Comment by Jojo-Kaly** [comment] 2020-12-08 17:19
PHP version 7.2.34 is wrtitten in my back office -> Advanced settings -> Informations. But I check in my host settings, there is written PHP version 7.2.
I don't save full error stack trace...

**Comment by hibatallahAouadni** [comment] 2020-12-09 08:20
Hello @Jojo-Kaly 

Could you please attach your log file, you can find it under your admin folder of your PrestaShop project:

**`admin > autoupgrade > tmp > log.txt`**

We need this file to find out the source of the bug.

Thanks!

**Comment by Jojo-Kaly** [comment] 2020-12-09 09:25
Thank you hibatallahAouadni. There is my log file.

[log.txt](https://github.com/PrestaShop/PrestaShop/files/5664799/log.txt)

**Comment by hibatallahAouadni** [comment] 2020-12-09 09:34
Thanks @Jojo-Kaly 

Ping @PrestaShop/prestashop-core-developers Could someone check what is the issue's source :pray:

**Comment by matks** [comment] 2020-12-09 13:02
Thanks for the log file ! It looks like it's the same issue as https://github.com/PrestaShop/PrestaShop/issues/22264

**Comment by Jojo-Kaly** [comment] 2020-12-09 13:23
Hi Matks.
Yes, it seems the same issue, except that after the update attempt, I haven't BO and FO blanck white pages but BO error 500 and always maintenance page on FO.
I updated 1-Clik upgrade to the last version and tried again, but there is always the error.

**Comment by Jojo-Kaly** [comment] 2020-12-10 17:36
Does anyone have any ideas on how to fix this error ?
Thank you.

**Comment by atomiix** [comment] 2020-12-11 10:33
@Jojo-Kaly I'm still trying to figure this out. The first installation of your shop was on version 1.7.6.3 or you already did an upgrade before?

**Comment by Jojo-Kaly** [comment] 2020-12-11 17:12
Hi Atomiix ! I already did an upgrade before, but I don't remember what was my first Prestashop version.

**Comment by atomiix** [comment] 2020-12-16 17:13
@Jojo-Kaly I looked in your `log.txt` a bit deeper and there is 2 things that look weird to me. 

First, the backup process seems to had stopped before the end, without notice:
<pre>
[2020-12-05 11:21:13] img/p/3/9/9/399-small_default2x.jpg added to archive. 41033 files left.
[2020-12-05 11:21:13] img/p/3/9/9/399-small_default.jpg added to archive. <b>41032 files left</b>.
[2020-12-07 12:27:57] <b>Starting upgrade...</b>
[2020-12-07 12:27:57] Shop deactivated. Now downloading... (this can take a while)
[2020-12-07 12:27:57] Downloaded archive will come from https://download.prestashop.com/download/releases/prestashop_1.7.7.0.zip
</pre>

Second, it looks like you have some `index.php` files in places where you shouldn't, for instance:
<pre>
[2020-12-05 11:11:22] <b>app/Resources/translations/index.php</b> added to archive. 44417 files left.
[2020-12-05 11:11:22] app/Resources/views/base.html.twig added to archive. 44416 files left.
[2020-12-05 11:11:22] <b>app/test/cache/index.php</b> added to archive. 44415 files left.
[2020-12-05 11:11:22] <b>app/test/index.php</b> added to archive. 44414 files left.
</pre>

I'm pretty sure that if we had the complete backup log, we'd see an `index.php` in `src/PrestaShopBundle/Controller/Admin/Sell/`.

Now, it would be great to find the source of what adds those `index.php`.
Maybe by opening one of them, you'll have a clue.

**Comment by hibatallahAouadni** [comment] 2020-12-28 10:32
Hello @Jojo-Kaly 

This issue is a duplicate of #20332 and it is already in our debug backlog.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-28 10:32
Duplicate of #20332

**Closed as completed by hibatallahAouadni** 2020-12-28 10:32 UTC
Labels: Bug, BO, Duplicate, Autoupgrade, 1.7.7.0
