### ISSUE TITLE
`updatePhysicalProductQuantity` is called twice in `PaymentModuleCore::validateOrder`

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#30400] opened 2022-11-24 17:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

`updatePhysicalProductQuantity` is called twice in `PaymentModuleCore::validateOrder`

`updatePhysicalProductQuantity` is an expensive function performance wise (see https://github.com/PrestaShop/PrestaShop/issues/14703). The fact to call it uselessly twice is just worsening that performance hit.

Here are the stacktraces for the two calls:
```
/src/Adapter/StockManager.php in PrestaShop\PrestaShop\Adapter\StockManager::updatePhysicalProductQuantity on line 106
/classes/order/OrderHistory.php in OrderHistoryCore::changeIdOrderState on line 425
/classes/PaymentModule.php in PaymentModuleCore::validateOrder on line 566
/modules/invoice/controllers/front/validation.php in InvoiceValidationModuleFrontController::postProcess on line 35
/classes/controller/Controller.php in ControllerCore::run on line 295
/classes/Dispatcher.php in DispatcherCore::dispatch on line 530
/index.php on line 28

/src/Adapter/StockManager.php in PrestaShop\PrestaShop\Adapter\StockManager::updatePhysicalProductQuantity on line 106
/classes/PaymentModule.php in PaymentModuleCore::validateOrder on line 780
/modules/invoice/controllers/front/validation.php in InvoiceValidationModuleFrontController::postProcess on line 35
/classes/controller/Controller.php in ControllerCore::run on line 295
/classes/Dispatcher.php in DispatcherCore::dispatch on line 530
/index.php on line 28
```

### Expected behavior

I expect the same queries (function) run only once, especially on expensive operations

### Steps to reproduce

1. In `src/Adapter/StockManager.php` at line 105, just after 
    ```
    public function updatePhysicalProductQuantity($shopId, $errorState, $cancellationState, $idProduct = null, $idOrder = null)
    {
    ```
   add `debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);`. If the payment method uses a async communication with the bank's server, instead of debug_print_backtrace, log the backtrace somewhere, either to a log file, or to a service like Sentry.io
2. Confirm an order with a payment method that validates the order (not bankwire). 
3. Note that there are two backtraces

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-11-25 16:44
Hello @lmeyer1 

Thanks for this well detailed bug report :clap: 
Ping @PrestaShop/prestashop-core-developers can someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by hibatallahAouadni** [comment] 2023-08-31 15:16
Hello @lmeyer1 

Do you still encounter the issue with PS811 or on the branch 8.1.x?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-29 14:13
Hello @lmeyer1 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-29 14:13 UTC
Labels: Bug, CO, Modules, Payment, Invalid, 8.1.x
