### ISSUE TITLE
PS 1.7.5 Cyrillic encoding after installation

### ISSUE THREAD

**Issue by Diniver** [PrestaShop/PrestaShop#12113] opened 2019-01-10 16:01 UTC
Hello all, 

My goal is to install prestashop with Bulgarian language, but I am meeting lots of issues with encoding. 

**How to reproduce**
Download lates 1.7.5 zip from official website. These are the steps which I follow during installation:

![image](https://user-images.githubusercontent.com/31882138/50978547-94098500-14ec-11e9-862b-d6b804a93b91.png)

![image](https://user-images.githubusercontent.com/31882138/50978635-c3b88d00-14ec-11e9-848a-bc36fe8fd7d9.png)

I have to sort my php problems with my hosting. I believe they are not related with the encoding problem.

![image](https://user-images.githubusercontent.com/31882138/50978856-2a3dab00-14ed-11e9-9cbc-38e3b72dd313.png)

![image](https://user-images.githubusercontent.com/31882138/50978921-52c5a500-14ed-11e9-8152-2306d34bb5c7.png)

After installation, when I look up in phpMyAdmin I can see the following:

![image](https://user-images.githubusercontent.com/31882138/50979064-a506c600-14ed-11e9-8ee6-6f66260557b3.png)
As you can see there are tables with different encoding: utf8_unicode_ci, utf8_general_ci, latin1_sweedish_ci

I am cheching table ps_lang
![image](https://user-images.githubusercontent.com/31882138/50979106-b780ff80-14ed-11e9-98ae-9dfa097c600a.png)

Furthermore, ps_meta_lang:

![image](https://user-images.githubusercontent.com/31882138/50979167-d7182800-14ed-11e9-8cef-49c2ff71c63a.png)

These results are imidiately after installation. I have not log in in admin panel.

I have found many issues with encoding here, but they are mainly after installation. I saw you have pull request related with that problem: https://github.com/PrestaShop/PrestaShop/pull/12103 but it looks like it is not yet released. Do you have idea how long it will take?

On the other hand, I have replaced DbPDO.php which solved this problem, but when I attempt to make translations in backshop-AdminModulesFeature, I am having this:problem

Before I save the translation
![image](https://user-images.githubusercontent.com/31882138/50980161-f31cc900-14ef-11e9-841a-f446b63b1032.png)

After I change the translation. The page is not able to load anymore
![image](https://user-images.githubusercontent.com/31882138/50980230-22cbd100-14f0-11e9-8b1d-7ab30c93beb3.png)

Currently, it is imposible to use prestashop with bulgarian language.

If this issue is already resolved in developer's branch, I am sorry for this lenghty post. 

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2
Other PS versions I have tried: 1.7.2.2, 1.7.3

**Comment by khouloudbelguith** [comment] 2019-01-10 17:03
Hi @Diniver,

I tried with Fresh installation PS1.7.5.0 with English language / Bulgaria country.
In my database, I have the same encoding as you described.
![image](https://user-images.githubusercontent.com/16067358/50984289-cffb1500-1501-11e9-94ca-2106357bb4f0.png)
But, in the BO, after changing the language of the employee I tried to edit the translation & it is OK.
https://drive.google.com/file/d/1Jxg-Td0G_s0GnkMtCKm4jnMEm_TtMbtq/view
It could be the changes that you made in the DbPDO.php related to your issue.
Thanks!

**Comment by Diniver** [comment] 2019-01-10 17:47
Thank you very much for this fast responce.
I can confirm that I reproduced your video without issues. It's strange that I got Malformed UTF-8 charactes during the traslation ofAdmin Modules Feature. Were you able to translate Admin Modules Feature as per my example?

**Comment by khouloudbelguith** [comment] 2019-01-11 08:39
Hi @Diniver,

In my side, the translation of `Admin > Modules > Feature` section is OK also.
I attached a video record.
https://drive.google.com/file/d/1OXj-ZuHfXGRrtEGZ49Bh5hx8ewci99uC/view
Thanks!

**Comment by Diniver** [comment] 2019-01-11 09:14
Hi @khouloudbelguith 
Thanks a lot. It looks like the problem is with my hosting/mysql or who knows what :) 

Keep up the good work.

**Comment by khouloudbelguith** [comment] 2019-01-11 09:15
@Diniver, thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Have a good day!

**Closed as completed by khouloudbelguith** 2019-01-11 09:15 UTC
Labels: BO, Can't reproduce, International, Translations, 1.7.5.0

**Comment by macavelli** [comment] 2020-12-12 01:04
I have the same problem with presta 1.7.7 after I updated from 1.7.6. The problem is that when I try to translate my new theme it stores values in database with wrong chars, e.g. "TwĂłj adres email" while on the backend I write "Twój adres email". It coverts ó into Ăł and then on the website it displays it from database as "Ăł", which is wrong as I wanted to have "Twój". 

Then I can make it correct in database and edit this row to "Twój", it displays it well on the frontend, but... when I go to backend translations and try to open category with "Twój" it displays error "Malformed UTF-8...". 

I tried to make it correctly with putting into DbPDO.php this:
        // UTF-8 support
        if (!$this->link->query('SET NAMES utf8mb4')) {
            throw new PrestaShopDatabaseException(Tools::displayError('PrestaShop Fatal error: no utf-8 support. Please check your server configuration.'));
        }

In previous versions it was working fine, cause it was only for displaying correct values on frontend, but now it stores wrong values in database. Shall I put some utf-8 encoding into javascript/php, while it's updated with json?

edit.
I found solution on some Russion forum (https://www.nulled.cc/threads/299380/page-3). Here's the link that they mention there.
https://github.com/Serios/PrestaShop/commit/a07e5b5fce40a26eee870fd64ae591d81a55a59b

In my case it solved an issue. Right now its saved in utf-8 and it's displayed in utf-8 on admin panel as well. 

> This one solves the issue with wrong encoding when not all server encodings are set to UTF8. This is not the full solution however, other files part of Symphony framework should be edited too as fallows:
> 
> vendor\doctrine\dbal\lib\Doctrine\DBAL\DriverManager.php 
> after line 154 add:
> $params['driverOptions'] = array(1002=>'SET NAMES utf8'); 
> 
> vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\DrizzlePDOMySql\Driver.php 
> replace line 35 with:
> public function connect(array $params, $username = null, $password = null, array $driverOptions = array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"))
> 
> vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.php 
> replace line 37 with:
> public function connect(array $params, $username = null, $password = null, array $driverOptions = array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"))

>classes/db/DbPDO.php 
>in  return new PDO($dsn, $user, $password, array(PDO::ATTR_TIMEOUT => $timeout, PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true, PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
