### ISSUE TITLE
Call to a member function formatPrice() on null  [Error 0]

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#36175] opened 2024-05-16 12:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PrestaShop was updated from 8.0.5 to 8.1.6. After enabling the new product page and attempting to edit previously added products on the old product page, I get the following error: Call to a member function formatPrice() on null [Error 0]. Adding new products works, but editing old ones does not.

### Expected behavior

Expected Behavior
After updating PrestaShop from 8.0.5 to 8.1.6 and enabling the new product page, I expected the following:

Editing Existing Products: I should be able to edit previously added products on the old product page without encountering any errors.
Consistent Functionality: The formatPrice() function should work correctly, and no errors should occur when editing existing products.
Data Integrity: The size and integrity of the product data should remain consistent, and any changes or updates should be saved and reflected correctly.

### Steps to reproduce

Go to product page and edit old products.

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.0

**Comment by Hlavtox** [comment] 2024-05-20 07:59
@eveneme Can you please check your database in phpmyadmin or adminer and check what is the difference between the old and the new product?

We are interested in `ps_product` and `ps_product_shop` tables. Compare a product that works and one that doesn't, what are the differences?

**Comment by eveneme** [comment] 2024-05-21 12:06
1. Old product page: 

https://github.com/PrestaShop/PrestaShop/assets/85762221/934dbea8-2742-44ae-8dab-53dc4b4275aa
https://github.com/PrestaShop/PrestaShop/assets/85762221/e72a650d-6aea-43a4-a91d-86dc266a2274

3. New product page:

https://github.com/PrestaShop/PrestaShop/assets/85762221/0c6977ef-6ae5-4854-a7e1-02747cc4fa66
https://github.com/PrestaShop/PrestaShop/assets/85762221/7c6a8439-3920-41f1-8a30-56fa77a0370b

**Comment by AureRita** [comment] 2024-05-24 09:56
Hi @eveneme 

Thank you for your report, I tried to reproduce your issue as you can see : 

[recording(218).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/6cd726a7-49ef-446a-be15-86b065dd4b63)

But currently I can't, Did I miss something ? 

Can you provide us some screenshot of the issue or videos. 

Waiting for feedback

**Comment by Hlavtox** [comment] 2024-05-24 10:03
@eveneme You need to find out what data of the old product makes the new product page crash.

When you find it, tell me and we can look into it.

**Comment by paulnoelcholot** [comment] 2024-06-11 08:50
Hello @eveneme,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-06-11 08:50 UTC
Labels: Bug, BO, Autoupgrade, Invalid, 8.1.x, Products Page

**Comment by JinicMedia** [comment] 2024-06-28 13:32
Hi !
Got the same issue here. I dont see any difference between products. I've been on Prestashop 8.1.6 since I've installed it. 

The product is saved but it shows the error.

![Capture d’écran du 2024-06-28 15-34-02](https://github.com/PrestaShop/PrestaShop/assets/161705596/a7fbe005-6aac-4d18-bf7e-496f9c7c0630)

**Comment by eveneme** [comment] 2024-11-29 23:28
And fixed?

**Comment by eveneme** [comment] 2024-11-30 17:16
@paulnoelcholot Please open a thread as the issue persists. It is not possible to enable the addition of new products because old ones cannot be edited due to this error in PrestaShop 8.0.5 updated to 8.2.0, and the error still occurs.

**Comment by eveneme** [comment] 2024-11-30 17:29
I found the solution, the problem is caused in my case by the module: OmniversePricing from TheEnumbin.
