### ISSUE TITLE
1-click upgrade > blank page and juste "error" message

### ISSUE THREAD

**Issue by Jerome08** [PrestaShop/PrestaShop#23859] opened 2021-04-01 12:37 UTC
#### Describe the bug

When i click 1-click upgrade module
a blank with only "error!" written on top

#### Expected behavior

the module doesn't appear

#### Steps to Reproduce

1. Go to 1-click upgrade (bottom left of B.O)

**Screenshots**
![ScreenShot009](https://user-images.githubusercontent.com/50581985/113294839-b3707080-92f7-11eb-9cae-a5c040a0dfd1.jpg)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.1

**Comment by Jerome08** [comment] 2021-04-01 13:22
I tried to activate debug mode, but there is no more information

**Comment by hibatallahAouadni** [comment] 2021-04-01 13:23
Hello @Jerome08 

Could you please provide your **1-click upgrade** module's version.
Please check and feedback.

Thanks!

**Comment by Jerome08** [comment] 2021-04-01 13:41
the last one v4.12.0 
i already uninstalled and installed again a few times (with delete folder of module)
i cleaned my cache

**Comment by florine2623** [comment] 2021-04-02 08:48
Hello @Jerome08 ,
I can't reproduce your issue with PS 1.7.5.2 and 1-click-upgrade v4.12.0.
Please check my screen record :
https://drive.google.com/file/d/1JhlJP1qrmryalHpy6ELiVfbyEpo_lk0m/view

Can you enable debug mode ?

**Comment by Jerome08** [comment] 2021-04-02 09:12
Hello

thanks,
it's same with or without debug mode, just "error" 

https://user-images.githubusercontent.com/50581985/113401758-2fc08d80-93a4-11eb-96b8-19cf22031b06.mp4


https://user-images.githubusercontent.com/50581985/113401768-34854180-93a4-11eb-85fb-8b58b48102c3.mp4

**Comment by florine2623** [comment] 2021-04-02 09:25
Can you make sure you are logged in as superadmin ?

**Comment by Jerome08** [comment] 2021-04-02 09:37
yes my account is superadmin, i tried with another account, superadmin too, it's same

**Comment by florine2623** [comment] 2021-04-02 12:03
What is the link redirecting to the blank page ?
It should look like : `https://your_shop_url/your_admin/index.php?tab=AdminSelfUpgrade&token=your_token`

**Comment by Jerome08** [comment] 2021-04-02 12:36
yes it look like urs
it's  ~/index.php?controller=AdminSelfUpgrade&token=   and my token at the end
u need all information? is it safe?

**Comment by florine2623** [comment] 2021-04-02 14:04
Yes, this is enough, and it is the correct link !

Sorry, but despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

 If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Closed as completed by florine2623** 2021-04-02 14:04 UTC
Labels: Bug, BO, Modules, Autoupgrade, No change required, 1.7.5.2

**Comment by Jerome08** [comment] 2021-04-02 17:25
finaly with firefox i had the upgrage page
i started to upgrade, now my prestashop is broken
i had this error :Erreur Javascript (parseJSON) détectée pour l'actionupgradeDb"Début de la restauration ..."

then the restoration failed too 

[INTERNAL] /home2/xx/public_html/xxxx/config/config.inc.php line 123 - Error: Call to a member function getName() on null #0 /home2/xxx/public_html/xxxx/modules/autoupgrade/classes/UpgradeContainer.php(552): require_once() #1 /home2/xxxx/public_html/xxx/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #2 /home2/xxx/public_html/xxxx/xxxxxx/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #3 {main}

wow
