### ISSUE TITLE
BO - Subscription to the Newsletter failed when there is no customer 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26698] opened 2021-11-22 10:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When deleting the customer with the email desired and then unsubscribe from the newsletter registations then adding the email from FO to subscribe again, the registration is created with a failed ID and an error message is displayed when subscribing again.

See screen-record below : 
When there is a customer created ==> Unsubsciption is OK
https://watch.screencastify.com/v/YCk7DeqvWoWxf3NE9Ik5 

When the customer does not exists ==> Unsubsciption is NOK
https://watch.screencastify.com/v/Ix3FGIbHrNqKsCDSg8g1

### Expected behavior

Unsubscription from the newsletter registrations must be done even when no customer is created.

### Steps to reproduce

1. BO > Go to Customers > Manage your Customers
2. Delete Customer with the email desired to add on subscription
3. GO to Modules > Module Manager > search for ps_emailsubscription module > Click on Configure
4. Check that the email desired is not yet registered
5. GO to FO > Subscribe with the email for the first time == > OK
6. Check that email is received (in case of send verification is Enabled)
7. Check that log is added
8. Check that the registration for the Newsletter is added with the email entered (ID of registration is incorrect with N...)
9. Click On Unsubscribe ===> OK
10. Back to FO > Refresh page > Subscribe again with the email for the 2+ time
11. See Error (An error message is displayed)

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.1 & 1.7.8.x

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2024-01-19 13:56
Hello,

I can't reproduced the issue anymore.
Testing on 8.1.x and email subscription v2.8.1.

Tested subscription and unsubscription from guest and customer accounts.

Customer account:

https://github.com/PrestaShop/PrestaShop/assets/16019289/f622d6cf-fd55-4102-b868-d5d2ad1f3f14

Guest account:

https://github.com/PrestaShop/PrestaShop/assets/16019289/4bc49e5d-e27e-4b34-a093-2c414f8e38fe


Im closing the issue to avoid clogging the backlog.
Thanks!

**Closed as completed by florine2623** 2024-01-19 13:56 UTC
Labels: Bug, Minor, BO, Needs Specs, Customer, Emailsubscription, 1.7.7.8, Verified, Module
