### ISSUE TITLE
Bug Newsletter v2.5.0

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15473] opened 2019-09-09 11:33 UTC
**Describe the bug**
Newsletter module does not regist mails.

**To Reproduce**
When try to register a mail in the newsletter text box and click on subscribe (and press enter key), the web refreshes and does not register the mail into de database (if I go to the back office and check is worked, the mail doesn't appear).
When the key has been pressed and the page auto refresh (an error) appears in the url: "https://...#footer" when #footer, before didn't appear.

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-09-09 11:41
Hi @pablo-gnzlz-escribano,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15425
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-09 11:41
Duplicate of #15425

**Closed as completed by khouloudbelguith** 2019-09-09 11:41 UTC
Labels: Duplicate
