### ISSUE TITLE
[IMPROVEMENT][HOOKS] Ability to enable and disable Hooks

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#20848] opened 2020-09-03 23:30 UTC
## Is your feature request related to a problem?

Users must be able to activate or deactivate hooks very quickly :

- In some cases, we want to investigate the cause of unexpected behavior, this will allow you to quickly activate and deactivate certain hooks without impacting the modules.
- With the current system if you have 20 modules hooked in a hook, if you unhook them all to investigate a problem for example, it will be complicated to hook them again, you have to do it one by one and you might forget someone

### Before
![image](https://user-images.githubusercontent.com/16455155/92182915-22aee080-ee4d-11ea-9c70-6d34c5a4c97e.png)

### After
![image](https://user-images.githubusercontent.com/16455155/92182832-e9767080-ee4c-11ea-86f6-31522c70f3ac.png)

## POC
https://drive.google.com/file/d/1em36ptle01LrXWV2RCxl-iliZtRW5zbj/view

## How to test ?
see POC section

**Comment by matks** [comment] 2020-09-04 07:45
Very nice idea and design !

I am only wondering whether it'll be obvious what this switch is for users 🤔  maybe we might add a label next to it to make it unambiguous ?

**Comment by florine2623** [comment] 2020-09-04 08:04
Hi @PululuK ,
Thanks for the suggestion !

Ping @PrestaShop/prestashop-product-team 
What do you think about this improvement ? :)

Thanks !

**Comment by PululuK** [comment] 2020-09-04 08:07
> I am only wondering whether it'll be obvious what this switch is for users thinking maybe we might add a label next to it to make it unambiguous ?

I think we'll need your help @prestascott @NeOMakinG   🙂

**Comment by rafapastor** [comment] 2020-09-05 21:16
Great idea!

**Comment by Hlavtox** [comment] 2020-09-08 10:57
@matks I can imagine a situation where you need to debug a speed/problem in some hook. You need to know if it is caused by PS itself or some module. Insteand of unhooking 8 modules, you just flick a switch.

_active_ flag could be added to _ps_hook_ and checked when executing the hook. No backward incompatibility.

**Comment by prestascott** [comment] 2020-09-17 09:03
Hi everyone!

Thank you @PululuK for your report. 

I understand your needs, and your improvement request seems a really nice idea to me. Overall, this hooks page needs a complete redesign since it has exclusive features such as managing hooks using the component that appears on the right side of this page. 

![image](https://user-images.githubusercontent.com/54888056/93450384-34c16200-f8d6-11ea-834a-284c48cdfde4.png)

This page uses tables to display available hooks but doesn't look like other tables in the bo, see the checkbox on the right side with the number of modules used. In fact, we definitely need to harmonize our components to keep consistency.

**Here is my design proposition:** 

- Bringing back the bulk actions on the left side for each table 
- Being able to activate/deactivate module using the switch
- Using an explicit icon 'remove' for unhook action
- Adding tooltips on each possible actions
- Reduce opacity to each deactivated modules
- Separate each table so it can be easily identifiable

**Screenshots:**
![image](https://user-images.githubusercontent.com/54888056/93449443-0bec9d00-f8d5-11ea-89e4-b41df965a462.png)
![image](https://user-images.githubusercontent.com/54888056/93449529-24f54e00-f8d5-11ea-834f-6a5cc5fc3966.png)

**Comment by PululuK** [comment] 2020-09-17 10:34
Hi @prestascott, thanks for your proposition, The design seems great to me, but ... : 

- My request does not concern the redesign of the positions module page
- I think I misspoke, or we misunderstood each other. The idea is to handle the Hooks status and not hook/unhook modules.

Before             |  After
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/16455155/93456947-a43b4f80-f8de-11ea-9823-940ef2f0a58a.png)|![image](https://user-images.githubusercontent.com/16455155/93459130-8e7b5980-f8e1-11ea-98e2-c0c5ddb3eff8.png)




In any case, your proposal seems very good to me! Could you create an issue for that and assign it to me please? I can provide another PR for the redesign of this page !

Thank you man !

**Comment by prestascott** [comment] 2020-09-17 13:43
Oh ok, I see what you mean. So your need is to change hook status and not modules status in the hook? Or you need both of them? 

If you only need to change hook status I don't think there's a better way than adding a switch before a hook like you did. Then I will also remove the switch to activate/deactivate a module from a hook. 

If you need both, I'll keep them.

**Comment by NeOMakinG** [comment] 2020-09-21 08:56
> Hi @prestascott, thanks for your proposition, The design seems great to me, but ... :
> 
> * My request does not concern the redesign of the positions module page
> * I think I misspoke, or we misunderstood each other. The idea is to handle the Hooks status and not hook/unhook modules.

But, being able to disable one or some modules rapidly could make it way easier to find a module which create side effects/bugs doesn't it ? I think it's as important as your initial issue, it even complete it !

By the way, that would be a great improvement !

**Comment by PululuK** [comment] 2020-09-21 08:58
> But, being able to disable one or some modules rapidly could make it way easier to find a module which create side effects/bugs doesn't it ? I think it's as important as your initial issue, it even complete it !
> 
> By the way, that would be a great improvement !

Then I said : _**In any case, your proposal seems very good to me! Could you create an issue for that and assign it to me please? I can provide another PR for the redesign of this page !**_

**Comment by prestascott** [comment] 2020-09-21 14:26
@PululuK Hey, you can find the new issue https://github.com/PrestaShop/PrestaShop/issues/21092 [here](https://github.com/PrestaShop/PrestaShop/issues/21092).

**Comment by PululuK** [comment] 2020-09-21 14:34
> @PululuK Hey, you can find the new issue #21092 [here](https://github.com/PrestaShop/PrestaShop/issues/21092).

Thank you so much @prestascott  !!!  
Can you assign it to me please? I'll provide a new PR for this case.

To avoid confusion could you rename your issue, something like that :  **[IMPROVEMENT][HOOKS] Redesign module positions page**

**Comment by MatShir** [comment] 2020-09-21 16:28
Hi @PululuK,
We can assign only people from the core team for now with the current restrictions. (We might need to improve the system for the next time).
But if you link the PR properly to this issue, we will know that the issue is assigned to you ;)

**Closed as completed** 2020-09-23 13:22 UTC
Labels: Improvement, PM ✔️, UX ✔️, Positions, Fixed, PR available, Hook

**Comment by jeckyl** [comment] 2020-11-27 19:17
Is there any information listing the fact that Hooks are disabled to avoid searching for hours why a module doesn't work?
Like, for example, on the modules page.
