### ISSUE TITLE
Perform order status update with webservice does not trigger "stock movement" quantity deduction

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#23453] opened 2021-03-01 10:13 UTC
#### Describe the bug

Using webservices to update order status with the "**order_histories**" resource toward a shipped order 
does not trigger the stock movement update (Catalog > Stocks) to deduct quantities.

#### Expected behavior

I expect the correct stock movement being registered (the same behaviour that happens when manually updating order status through backoffice).

#### Steps to Reproduce

1. Create a sample order , paid by banwire
2. Use the following code snippet to update the order status remotely with webservice (change variabiles accordingly) :
```

<?php
    
include 'PSWebServiceLibrary.php';

$ws = new PrestaShopWebservice(
'http://localhost:8083',
'xxxx',
false);

$opt = [
    'resource' => 'order_histories?schema=blank'
];
$xml = $ws->get($opt);
$resources = $xml->children()->children();

$resources->id_order = 9;
$resources->id_employee = 1;
$resources->id_order_state = 5;

$opt = [
    'resource' => 'order_histories',
    'postXml' => $xml->asXML()
];
$ws->add($opt);
```

3. Go in Catalog > Stocks > Movements and notice no movements are recorded for "Customer order"

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-03-01 11:35
Hello @gennaris 

Thanks for the detailed issue :clap: 
Could you please check this issue #15976 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by gennaris** [comment] 2021-03-01 11:42
Not really, in #15976 it is requested to expose all properties of the **ps_stock_available** table in webservice.

My problem is related to NOT writing stock movement (the table involved is **ps_stock_mvt**, although there is interaction with **ps_stock_available** too) when changing order state with WS.

The most typical scenario in which the bug I reported occurs is with third party integrations (especially carriers) that uses webservices to "ship" orders, in which case the stock movement for that order is lost.

**Comment by hibatallahAouadni** [comment] 2021-03-03 15:45
Hello @gennaris 

I didn't manage to reprodcue your issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1XoBMqbSjL04U4K3S3vnt1Ua5usST4yNt/view

Please check and feedback.
Thanks!

**Comment by gennaris** [comment] 2021-03-03 18:09
Hi @hibatallahAouadni ,
thank you for your time.

Problem is not related to Stock tab, but on "Movements" tab,
In fact, **ps_stock_available** is correctly updated, **ps_stock_mvt** is not.

If you check again your test order (the one you updated through webservice) ,
you will notice the missing movement.

See this image for better explanation : 

![2021-03-03_19-06-12](https://user-images.githubusercontent.com/43071148/109851258-c427bb00-7c53-11eb-94f8-8b563fe6f090.png)

**Comment by hibatallahAouadni** [comment] 2021-03-03 18:14
Hello @gennaris 

No, there's no missing movement, see the attached screenshot below (see the date):

![image](https://user-images.githubusercontent.com/23308427/109852074-aa3aa800-7c54-11eb-809c-651382c9d499.png)

Please check and feedback.
Thanks!

**Comment by gennaris** [comment] 2021-03-04 07:32
Hi @hibatallahAouadni 
You screen shows "Employee edition" as movement type but as far as I can see - If an order is getting updated through a status change,  the stock movement type should be "**Customer order**" as per my previous screenshot.

So your stock movement was probably triggered by a backoffice product save / update AFTER the status getting updated and not by the order status change.

Try reproducing the same order with MANUAL order status change towards DELIVERED and check the "Movements" tab again.

**Comment by florine2623** [comment] 2021-03-05 14:52
Hello @gennaris ,

I didn't manage to reproduce your issue with PS1.7.7.2 as @hibatallahAouadni and the mouvement is saved with Customer Order, see the attached screenshots below:

![Capture d’écran 2021-03-05 à 15 51 38](https://user-images.githubusercontent.com/16019289/110131699-b9436680-7dca-11eb-8a33-600540bf464e.png)

![Capture d’écran 2021-03-05 à 15 50 32](https://user-images.githubusercontent.com/16019289/110131601-9b760180-7dca-11eb-8e22-867a5e4953dd.png)

Please check and feedback.
Thanks!

**Comment by gennaris** [comment] 2021-03-06 07:51
@florine2623 @hibatallahAouadni 

This is weird since the problem has been reported to me by a customer and it was reproducible by me on a base 1.7.2 installation. Maybe I am missing something here ?

I made a video recording as well on a clean PS 1.7.7.2 to show you what happens to me : 

https://drive.google.com/file/d/1voqvG1YIF3oY1DVz24Ae2wukQ0OViIii/view

The order is set as "shipped" using the webservices with the code snippet I provided during ticket opening.

Thanks !

**Comment by hibatallahAouadni** [comment] 2021-03-08 13:35
Hello @gennaris 

May be your code is wrong, so could you please try to edit the order by Postman, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110328346-8a6fff00-801b-11eb-9950-5c2f540f39a3.png)

Please check and feedback.
Thanks!

**Comment by gennaris** [comment] 2021-03-26 11:38
Hi @hibatallahAouadni ,
sorry for late reply.
I have tried the same webservice call with Postman and I got the same result that I reported when opening this issue (missing stock movement).
I do not know why we get two different results and how else to support further verifications here.
If you think it can provide more details to investigate the problem let me know.

**Comment by hibatallahAouadni** [comment] 2021-03-30 11:05
Hello @gennaris 

> I do not know why we get two different results and how else to support further verifications here.
If you think it can provide more details to investigate the problem let me know.

I think we've come to a blocked path :confounded: 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug :confused: 

Sorry but I have to close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-30 11:05 UTC
Labels: Bug, WS, Can't reproduce, Order, Stocks, 1.7.7.2
