### ISSUE TITLE
Additional pixel in a product line

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30633] opened 2022-12-21 10:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If we compare the Products page of 8.0.x and that of develop, we can see that the lines on develop are one pixel longer.

![image](https://user-images.githubusercontent.com/112863083/208883467-2926900d-27a6-424f-af81-200e7f8f95f0.png)

### Expected behavior

There shouldn't be this gap

### Steps to reproduce

1. go on Catalog > Products with 8.0.x and develop
2. see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2022-12-21 14:11
Hello @paulnoelcholot 

Thanks for your report.

I tried to reproduce the issue but I was unable. Are you sure you are using the same screen without resizing it ?


https://user-images.githubusercontent.com/92912932/208924930-c48abf65-29c3-4a41-9f53-cbb3e560f798.mp4

Waiting for your feedback!

Thank You!

**Comment by hibatallahAouadni** [comment] 2023-01-10 09:35
Hello @paulnoelcholot 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-01-10 09:35 UTC
Labels: Bug, develop, BO, Invalid
