### ISSUE TITLE
The attributes function does not work correctly

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#25190] opened 2021-06-30 18:56 UTC
#### Describe the bug

By having three attributes of dimensions that depend on other combinations (Color) which do not have the same availability, it does not allow to choose the color of another size available in other colors.

#### Expected behavior

It should allow you to go to another size and show the available colors of that size.

#### Steps to Reproduce

1. Go to 'https://importaexpertospruebas.com/compras2/senuelos-duros/8-6901-rapala-x-rap.html'
2. Click on 'Tamaño 6cm and first color'
3. Try to go to "Talla 10 cm"
4. See error: It does not allow to display the colors of the "Talla de 10cm"

**Screenshots**

https://user-images.githubusercontent.com/12537826/124016045-d2d87180-d9aa-11eb-9989-4aecb629d380.mp4

#### Additional information

* PrestaShop version: 1.7.7.4 and 1.7.7.5
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-07-01 10:44
Hello @ocio87 

I think this issue is related to your theme, cause in the Classic theme, I didn't encounter this kind of behavior:

https://drive.google.com/file/d/1Dfj7tMv0Du07RPBkJcyzLRAb00MuxE3V/view

Please check and feedback, and I think you need to contact your theme developer to fix the issue.

Thanks!

**Comment by ocio87** [comment] 2021-07-01 13:41
Hello,

The news that I report also happens with the theme with defect.

To reproduce what I report you must do the following.

Size 1 with 3 colors (A, B, C) all with units available
Size 2 with 4 colors (A, B, C, D) all with units available
Size 3 with 2 Colors (B, C) Color B without units available.

Initially select Size 1 with color A and try to go to size 3. The theme cannot change to size 3 when it is selected in NO "Display attributes that are not available on the product page" in Store parameters - Product configuration . By not having color B available due to not having units for sale. It should go to size 3 and show at least color C or all other colors you have.

In this way, as it is working, it does not allow size 3 to pass only until in size 1 and 2 color C is selected.

https://importaexpertospruebas.com/compras2/inicio/2215-10346-test.html#/328-talla_vestuario-m/2735-colores_crocs-flip_candy_pink

**Comment by khouloudbelguith** [comment] 2021-07-02 14:05
Hi @ocio87,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/20565 to fix the issue.
It is fixed in the next release PS1780.
Your ticket is a duplicate of #9948
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-07-02 14:05
Duplicate of #9948

**Closed as completed by khouloudbelguith** 2021-07-02 14:05 UTC
Labels: Bug, FO, Duplicate, Combinations, 1.7.7.5

**Comment by ocio87** [comment] 2021-07-02 16:43
Thanks for you! @khouloudbelguith
