### ISSUE TITLE
Menu not work on PS 1.7.6.9 multistore frontend (only work on default store) 

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#22466] opened 2020-12-17 10:36 UTC
#### Describe the bug

Menu not work on PS 1.7.6.9 multistore frontend (only work on default store

#### Expected behavior

Menù must be shown on all multistore frontend

#### Steps to Reproduce

Configure a ne 
PS 1.7.6.9 fresh install with these exactly configuration:

Create a Mulstistore setup
![image](https://user-images.githubusercontent.com/24798703/102349338-7c25c000-3fa3-11eb-9d9f-4e9020efb329.png)

Check module Menu module position setup
![image](https://user-images.githubusercontent.com/24798703/102349381-8a73dc00-3fa3-11eb-8896-75d1d9d20901.png)

Configure Default store module menu setup:
![image](https://user-images.githubusercontent.com/24798703/102349440-9fe90600-3fa3-11eb-8e27-6741fcb46874.png)

Configure Second store module menu setup:
![image](https://user-images.githubusercontent.com/24798703/102349522-be4f0180-3fa3-11eb-83c1-75e149b801ba.png)

Open frontend store and check for menù

Default store (psmultistore) front end show module menu
![image](https://user-images.githubusercontent.com/24798703/102349561-d1fa6800-3fa3-11eb-85b2-7c89a64da96f.png)

Secondo store front end does not show module menu
![image](https://user-images.githubusercontent.com/24798703/102349582-db83d000-3fa3-11eb-89f2-f45d8d2a2bcf.png)

Cache disabled
![image](https://user-images.githubusercontent.com/24798703/102349604-e3dc0b00-3fa3-11eb-8aa7-4978e00a83aa.png)

PS 1.7.6.9
PHP 7.2

**Comment by florine2623** [comment] 2020-12-17 10:49
Hi @matteolavaggi ,

I can't reproduce your issue in my test shop PS 1.7.6.9 multistore context.

Top menus are different in both shops :
![Capture d’écran 2020-12-17 à 11 46 57](https://user-images.githubusercontent.com/16019289/102478221-a471f500-405d-11eb-9a79-cfce23f91ccc.png)
![Capture d’écran 2020-12-17 à 11 47 04](https://user-images.githubusercontent.com/16019289/102478228-a63bb880-405d-11eb-9708-d9a10e27c87a.png)

Please make sure your activated this option in your menu module :
![Capture d’écran 2020-12-17 à 11 46 45](https://user-images.githubusercontent.com/16019289/102478332-c4091d80-405d-11eb-91d6-af09532cd1dd.png)

I'll close this issue.
Thanks!

**Closed as completed by florine2623** 2020-12-17 10:49 UTC
Labels: No change required

**Comment by matteolavaggi** [comment] 2020-12-17 10:58
Hi, read carefoully my bug report, this is a fresh new installation of ps 1.7.6.9 installed on php 7.2 and apache, created 3 days ago.
And the bug is here, so why you close this issue? This store setup is a test env and is 100% new, default theme, default configuration ^^ !
Also your mulstistore setup use same domain a subfolder, mine use multiple domain, so its not the same test env , you close this bug report without a complete test over my paramethers? @florine2623 ? And maybe on a ps 1.7.6.5 instead 1.7.6.9?

**Comment by matteolavaggi** [comment] 2020-12-17 11:40
I took some time to open this bug report, it's not nice to close them without even checking the conditions correctly. Bad behavior.

**Comment by matteolavaggi** [comment] 2020-12-18 14:17
@florine2623 anyone there?
