### ISSUE TITLE
classic theme menu thumbnail

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#14148] opened 2019-06-11 04:52 UTC
When we add menu thumbnail image in category then it doesn't showing on front-office in the main menu with the classic theme. is it ok?

PrestaShop version: 1.7

**Comment by khouloudbelguith** [comment] 2019-06-11 08:05
Hi @Akashvastarpara,

> If I upload a cover image after the category thumbnail, it erases the thumbnail.

Yes, because the thumbnail is the same as the category cover image but in smaller

> If I upload a thumbnail image after the cover image, the thumbnail image, in the FO is not displayed.*

Yes, because the thumbnail is not used in classic template

> If I delete the "Category Cover Image" the "Category thumbnail" is deleted too.

Yes, because the thumbnail is the same as the category cover image

These behaviors are normal.

I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-11 08:05
Duplicate of #12760

**Closed as completed by khouloudbelguith** 2019-06-11 08:05 UTC
Labels: Duplicate
