### ISSUE TITLE
Error during upgrade the databse from 1.6.1.23 to 1.7.6.0

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#14890] opened 2019-07-28 18:25 UTC
Hi
I'm trying to upgrade a site from 1.6.1.23 to the 1.7.6.0
it is a big site with a big database, however I've tried many solutions also to 1.7.5.2 on the local archive. I get the same error.
I've upgraded to 1.7.x many sites but this one has problems with doctrine during the upgrade
upgrading to 1.6.1.24 all is ok

this is the error:

Updating database schema...
13:21:12 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it." ["exception" => Doctrine\DBAL\DBALException { …},"command" => "prestashop:schema:update-without-foreign","message" => "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it."]
In AbstractPlatform.php line 423:
Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform
may not support it.
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/62011215-87413b80-b175-11e9-9daf-699b68cc31ad.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-07-29 12:06
Hi @maofree,

Isn't the same issue reported in these tickets: https://github.com/PrestaShop/autoupgrade/issues/147 & https://github.com/PrestaShop/autoupgrade/issues/87#issue-335433391

Thanks to check & feedback.

**Comment by Maofree** [comment] 2019-07-29 12:25
Hi
yes it is the same error due from an extra module of Sequra that add a field in ps_product with bit(1)

![1](https://user-images.githubusercontent.com/653230/62048201-932c0c80-b20c-11e9-8315-fb38cb30eea3.png)

I've replaced it with TINYINT(1)

bye

**Comment by khouloudbelguith** [comment] 2019-07-29 12:27
@maofree, thanks for your feedback.
 close the issue, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-29 12:28
Duplicate of https://github.com/PrestaShop/autoupgrade/issues/87

**Closed as completed by khouloudbelguith** 2019-07-29 12:27 UTC
Labels: Bug, Duplicate, Autoupgrade, 1.7.6.0

**Comment by Maofree** [comment] 2019-07-29 17:43
Hi
now I get this error, after solved this one

https://github.com/PrestaShop/PrestaShop/issues/14904
