### ISSUE TITLE
The zh language pack cannot be downloaded during installation.

### ISSUE THREAD

**Issue by fxzxmicah** [PrestaShop/PrestaShop#15123] opened 2019-08-16 03:00 UTC
在安装时无法下载zh语言包

**Comment by fxzxmicah** [comment] 2019-08-16 03:19
经过许多次的尝试，zh语言包有很低的概率下载成功，不过之后还是会卡在安装插件模块这一步。
After many attempts, the zh language pack has a very low probability of being downloaded successfully, but it will still be stuck in the step of installing the plug-in module.

**Comment by mariem-abid** [comment] 2019-08-16 08:03
Hi @fxzxmicah,

I did not manage to reproduce the issue with the last Version PS 1.7.6.0.
I attached a screenshot.
![zh](https://user-images.githubusercontent.com/36841537/63152855-be806b00-c004-11e9-9f58-c4c7d5f7bd7e.png)

Thanks for check and feedback.

**Comment by matks** [comment] 2019-08-16 09:03
> 经过许多次的尝试，zh语言包有很低的概率下载成功，不过之后还是会卡在安装插件模块这一步。
> After many attempts, the zh language pack has a very low probability of being downloaded successfully, but it will still be stuck in the step of installing the plug-in module.

This is likely to be a network issue :/ can you check from a different network ?

**Comment by fxzxmicah** [comment] 2019-08-19 01:59
感谢你们的帮助，无法下载zh语言包确实是网络问题，但是之后会卡在安装插件模块这一步，尝试多次后仍无法解决，由于我在虚拟主机上尝试，可能是虚拟主机对此安装过程存在限制。
Thank you for your help, unable to download zh language package is indeed a network problem, but will be stuck in the plug-in module step, after trying many times still can not be resolved, because I tried on the virtual host, may be the virtual host for this installation process  There are limits.
 @mariem-abid @matks

**Comment by khouloudbelguith** [comment] 2019-08-20 11:20
Hi @fxzxmicah,

Thanks for your feedback.
I tried to install PrestaShop with the "简体字 (Simplified Chinese)" language with virtual host & it is well installed.
I attached a screen record
https://drive.google.com/file/d/1i7HkT_6_d_y38xofWI3x8Cjqtapw51Ot/view

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-19 07:33
Hi @fxzxmicah,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-19 07:33 UTC
Labels: Bug, BO, Languages, No change required
