### ISSUE TITLE
Customization fields and its saved value shows HTML content in order confirmation mail.

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#23261] opened 2021-02-15 10:45 UTC
#### Describe the bug

Customization fields in Order confirmation mail are not well-formatted and showing HTML content.

#### Expected behavior
It must show well-fomated content without any HTML tag
#### Steps to Reproduce

1- Go to customizable product: https://prnt.sc/zl9oi5
2- save your customization and place an order.
3- We receive an order confirmation mail
https://prnt.sc/zl9y6q
You will see that customization content show in HTML.

**Screenshots**
https://prnt.sc/zl9oi5
https://prnt.sc/zl9y6q

#### Additional information

* PrestaShop version: 1.7.6.9 & 1.7.7.1
* PHP version: 7.1

**Comment by florine2623** [comment] 2021-02-15 14:11
Hello @Amit-Kumar-Tiwari-Webkul ,
Your issue is a duplicate of #22330.

It is already in our debug roadmap.
So I'll close your issue.
Your PR will be linked to #22330 and reviewed.
Thanks!

**Comment by florine2623** [comment] 2021-02-15 14:11
Duplicate of #22330

**Closed as completed by florine2623** 2021-02-15 14:11 UTC
Labels: Duplicate
