### ISSUE TITLE
Upload new image in the native slider image module

### ISSUE THREAD

**Issue by hugosammons** [PrestaShop/PrestaShop#32013] opened 2023-04-03 08:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I was making some upload on my client web site and to do so I was changing the images that he has in a slider box at the top of his web site. ⬇️
![Capture d’écran 2023-04-03 à 09 50 37](https://user-images.githubusercontent.com/108458830/229445844-7daff888-aac1-4cd6-b968-000ddf7feb95.png)

This slider box is the native slider image module in Prestashop ⬇️
![Capture d’écran 2023-04-03 à 09 54 02](https://user-images.githubusercontent.com/108458830/229446363-f6917982-422e-44e8-982f-8be4c4aaaa0a.png)

It's not my first time so I go to the back office, find the slider image module and try to add a new image.
And here's my problem, it doesn't let my open my folder to upload a new file. ⬇️
![IMG_4630](https://user-images.githubusercontent.com/108458830/229445397-243263a6-e686-4a0e-8e42-dc7b075ed4b8.jpg)

I have a warning on top of the module asking me to add images in both french and english version (but there's no french web site version...)⬇️
![Capture d’écran 2023-04-03 à 09 56 23](https://user-images.githubusercontent.com/108458830/229446912-c0f956fa-7c82-4776-8f9d-c572d099c8f3.png)

Hope you will be able to help me.

Have a nice day,
Hugo

### Expected behavior

I am expecting to be able to add new images in the slider image module

### Steps to reproduce

go to back office
find the module manager
search for slider image
click on 'configure'
click on the 'plus' sign on the top right side
click on 'choose a file' (<- it's there that it doesn't work anymore)

### PrestaShop version(s) where the bug happened

1.7.8.8

### If your bug is related to a module, specify its name and its version

slider image

### Your company or customer's name goes here (if applicable).

v3.1.2

**Comment by florine2623** [comment] 2023-04-05 07:45
Hello @hugosammons ,

I can't reproduce your issue using ps_imageslider v3.1.2. You can still upload a file by clicking on the button Choose a file.

https://user-images.githubusercontent.com/16019289/230014870-6236ef49-4390-4307-85c0-c79d7f47b9b1.mov

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2023-04-05 07:45 UTC
Labels: Bug, Invalid

**Comment by AaronTajriba** [comment] 2023-04-25 12:36
I can say, this issue is here... I also see the following error in the console:
Uncaught Sortable: `el` must be an HTMLElement, not [object Undefined]

**Comment by AaronTajriba** [comment] 2023-04-25 12:48
But now... i can see it is resolved with the linked pull request in #31980. I think there is coming an new ps_imageslider release shortly
