### ISSUE TITLE
Products with option set "Allow orders" not possible to buy 10pcs if in stock 9pcs or less

### ISSUE THREAD

**Issue by diyan1234** [PrestaShop/PrestaShop#17023] opened 2020-01-05 20:28 UTC
If it is allowed to buy products that are not available but currently there are 9pcs available but the customer wants to buy 10pcs. or more he is not allowed.

How can this behavior be avoided and when this option is set, the customer can buy as many pieces as he wants

To reproduce:

1. In Back Office set 9pcs. in stock for any product
2. Set option "Allow orders" -- Back Office --> Catalog --> Products --> Product-settings --> Menu Quantities --> **Behavior when out of stock** --> check box "Allow orders"
3. In Front Office try to buy 10pcs. of this product

**Screenshots**
https://prnt.sc/qjqkyd

**Additional information**
PrestaShop version: 1.7.3.0

**Comment by khouloudbelguith** [comment] 2020-01-06 08:46
HI @diyan1234,

I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1U--nTBjUgt-OY8KTWZ_F4xdw3AFKf1Je/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-06 08:53
@diyan1234, the issue is fixed with PS1.7.3.2 with this PR: https://github.com/PrestaShop/PrestaShop/pull/9005
Thanks to check & feedback.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-04 08:11
Hi @diyan1234,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-04 08:11 UTC
Labels: Bug, FO, Stocks, No change required
