### ISSUE TITLE
Carrier interval BUG in 1.7.7.2

### ISSUE THREAD

**Issue by 4itsoft** [PrestaShop/PrestaShop#23636] opened 2021-03-14 14:07 UTC
#### Describe the bug
Couriers are not displayed correctly depending on the interval set in the BO.

#### Steps to Reproduce

1. Go to BO and set new interval for Prestashop carrier (http://prntscr.com/10le197)
2. Verify checkout in FO. "Prestashop" carrier The Prestashop courier is displayed to me, although the total order is not in its range (screenshot: http://prntscr.com/10le387)

#### Additional information
* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-03-15 17:24
Hello @4itsoft 

As you can see in this screenshot below, you choose **Applythe cost of the highest** for **out-of-range behavior** option, so it's not a bug, it's the wanted behavior:

![image](https://user-images.githubusercontent.com/23308427/111194042-11dce580-85bb-11eb-98ed-2238e0ed81c6.png)

If you want to disable the carrier, just choose **Disable the carrier** for **out-of-range behavior** option.
If you want the free shipping when the price is <30 euros, so you need to create another range from `>=0` to `<30`
So, I close this issue cause it's not a bug :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-15 17:24 UTC
Labels: No change required
