### ISSUE TITLE
"Products" and "Our company" sections not translated to French on 1.7.8.7 & 8.0.0-rc.1-8.1-apache

### ISSUE THREAD

**Issue by l-delin** [PrestaShop/PrestaShop#30498] opened 2022-12-05 10:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The "Products" and "Our company" sections in Front Office footer are not translated whenever the French localization pack is used on PS 1.7.8.7 & PS 8.0.0-rc.1-8.1-apache, but is translated just fine on PS 8.0.0-beta.1-8.1-apache. I have not tried reproducing the bugs with other localization packs.
The strings are all translated on Crowdin, so the issue is not coming from untranslated strings.

See:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/113511191/205615816-cd5dee9f-47c3-4c27-95b9-f219f87ddabe.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/113511191/205615893-512c93bc-0794-4267-b9d7-cd815e3b3829.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/113511191/205615929-d0fec9f8-89ca-4680-98b1-a7156cfd2ff6.png">

### Expected behavior

The sections should be translated into French like the rest of the sections (see "votre compte", "informations"). PS 8.0.0-beta.1-8.1-apache displays expected behavior.

### Steps to reproduce

1. Go to the PrestaShop front office
2. See the footer
3. Check if the "products" (produits) and "our company" (notre société) sections are translated.

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.0-rc.1-8.1-apache

**Comment by hibatallahAouadni** [comment] 2022-12-06 13:47
Hello @l-delin 

Sometimes the translation is not well displayed cause you need to update your language, check the attached screen record below:

[issue_30498.webm](https://user-images.githubusercontent.com/23308427/205928980-99970809-78ef-463f-98f2-865dec0d58c6.webm)

Closing the issue as it's not Core problem :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2022-12-06 13:47 UTC
Labels: Bug, Duplicate, Invalid

**Comment by Julievrz** [comment] 2022-12-08 08:54
> Hello @l-delin
> 
> Sometimes the translation is not well displayed cause you need to update your language, check the attached screen record below:
> 
>  issue_30498.webm 
> Closing the issue as it's not Core problem 😉
> 
> Thanks!

Hi 👋 I noticed the same issue on the demo. Is it normal?

**Comment by hibatallahAouadni** [comment] 2022-12-08 17:11
Hello @l-delin & @Julievrz 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23156. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: as you can see in the comment ([here](https://github.com/PrestaShop/PrestaShop/issues/23156#issuecomment-774157511)) you can solve the issue when you update your language :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-12-08 17:11
Duplicate of #23156

**Comment by RoseannePeeters** [comment] 2022-12-22 23:46
> Hello @l-delin
> 
> Sometimes the translation is not well displayed cause you need to update your language, check the attached screen record below:
> issue_30498.webm
> 
> Closing the issue as it's not Core problem 😉
> 
> Thanks!

Hey, facing same problem, however your video is gone, could you reprovide it to me? 
Thanks!
