### ISSUE TITLE
Order discounts calculated in wrong way prestashop 1.7.6.1

### ISSUE THREAD

**Issue by MohammedID** [PrestaShop/PrestaShop#19936] opened 2020-06-25 11:49 UTC
Dear Prestashop community;

Were getting issues with discount amounts on our shop, we did add cart rule applied to perfume category, each ordered product will get one mascara for free, this gift product cost 229.00 mad, if the client order more than one perfume for example two he will get 2 free mascaras, the issue is the discount total instead of displaying 229.00 * 2 which is 458.00 it displays 343.00.

I don't know where did he get this amount from, how did prestashop calculated the total amount of discounts.

In order to reproduce the error you can visit our prod version of the store : https://dev.infini.ma
Go to perfume category choose any one, add it to the cart, then increase the quantity of the product, put for example 2, and you will be able to reproduce the issue.

Below attached a screen shot of the issue.

* PrestaShop version: 1.7.6.1
* PHP version: 7.3

Best regards.
![2020-06-25-13-47-dev infini ma](https://user-images.githubusercontent.com/5112803/85714418-b1371100-b6ea-11ea-9c08-26b8b6ed31e5.png)

**Comment by florine2623** [comment] 2020-06-25 12:16
Hi @MohammedID ,
First, you need to downgrade your PHP version. PS 1.7.6.1 is available with PHP 7.2 max.
Second, I created a voucher that offers a free product when item from a specific category is in cart, I can't reproduce the issue.
Can you send the exact steps to reproduce please ?
Thanks!

**Comment by MohammedID** [comment] 2020-06-25 14:34
Hi florine;

In order to reproduce the issue you have to specify more than one rule applied to the same categories and the same gift product.

Can you please visit this url : dev.infini.ma, and add any product to the cart, then use these coupon codes : 'mascara_again' and 'mascara_natif'.

Or you will find attached the steps that you can follow to reproduce the error in your BO.
![step_3](https://user-images.githubusercontent.com/5112803/85740192-b5225d80-b701-11ea-8644-145644c31730.png)
![step_2](https://user-images.githubusercontent.com/5112803/85740196-b6538a80-b701-11ea-91e4-5ae67cfc2e77.png)
![step_1](https://user-images.githubusercontent.com/5112803/85740197-b6538a80-b701-11ea-94fd-445e9db0db50.png)

Best regrads.
--

**Comment by florine2623** [comment] 2020-06-25 15:51
Do you mean that you have 2 same discounts with the same category and same gift ?

**Comment by MohammedID** [comment] 2020-06-25 20:10
Yes, it the same gift product. for the same categories.

**Comment by florine2623** [comment] 2020-06-26 09:51
Regarding the free product sent to customer issue with the wrong calculated price, it has be fixed in PS 1.7.7.0.
I have 2 discounts with same configuration (same category restriction and same gift), they just have different names.

Please see my screenshot in PS 1.7.6.5 : **NOK**
![Capture d’écran 2020-06-26 à 11 47 14](https://user-images.githubusercontent.com/16019289/85844356-e1da8180-b7a2-11ea-8173-6bc62075507c.png)

In PS 1.7.7.0 : **OK**
![Capture d’écran 2020-06-26 à 11 44 54](https://user-images.githubusercontent.com/16019289/85844138-87d9bc00-b7a2-11ea-9238-9e536272cc1f.png)

I would advise yo to wait for the release candidate version of PS 1.7.7 and update your shop.
For now I will close this issue as it is fixed.
Thanks!

**Closed as completed by florine2623** 2020-06-26 09:51 UTC
Labels: Discounts, No change required, Fixed, 1.7.6.1
