### ISSUE TITLE
product image combinations dont work correct

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#24291] opened 2021-04-30 21:19 UTC
Hello!
PS 1.7.7.2
https://te.com.ua

I discover that when I put on product several combination with color variants in the FO the main image don`t change with checking different color.  The images below change. I apply the relevante images to color in BO
![image](https://user-images.githubusercontent.com/50954519/116755229-c9667380-aa12-11eb-952e-48088585b6f5.png)

I can`t understand what happened ((

**Comment by hibatallahAouadni** [comment] 2021-05-01 01:43
Hello @photinia73 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: it seems your issue is a duplicate of #21775.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-01 01:43 UTC
Labels: No change required
