### ISSUE TITLE
getRemoteAddr IF evaluation has potential to fail, when it should not fail

### ISSUE THREAD

**Issue by finlanderid** [PrestaShop/PrestaShop#14020] opened 2019-05-29 16:29 UTC
The bug that I want to report is IF evaluation in the following code.  If you look at it, you will see that it has the possibility to fail the IF evaluation, when it should not fail.  The goal is to get the remote_addr (the true visitor IP) when a CDN proxy is making website request.

Problem summary: if remote_addr is not set, then the right-hand half of the IF will fail (requiring && operator truth), if remote_addr is from a CDN such as Cloudflare that is using a proxy IP that does not start with 127 or 172 or 192 or 10.

For example, the REMOTE_ADDR for a Cloudflare request is the Cloudflare IP address, but it might not start with 127 or 172 or 192 or 10, so the right-hand half of IF evaluation will fail, then the whole IF will fail, when it should not fail.  For example, let's say that Cloudflare fetches a page from a website.  The Cloudflare REMOTE_ADDR is 188.114.96.100.  The true visitor IP is 67.60.1.2.  If the function evaluates with this incorrect Prestashop code, then getRemoteAddr() will return 188.114.96.100 instead of 67.60.1.2.  In this case, the function should return 67.60.1.2 (the visitor's true IP).

The reason for erroneous failure of the function:

HTTP_X_FORWARDED_FOR = 67.60.1.2
REMOTE_ADDR = 188.114.96.100

https://www.cloudflare.com/ips/

It is very possible (even likely) that remote_addr WILL be set by the proxy, but will not be set to an IP that starts with 127 or 172 or 192 or 10.  In that event, the whole IF statement will fail, when it should not fail.

===

In Tools.php (line 357 on PS 1.7)

```
    public static function getRemoteAddr()
    {
        . . . 

        if (isset($_SERVER['HTTP_X_FORWARDED_FOR']) && $_SERVER['HTTP_X_FORWARDED_FOR'] && (!isset($_SERVER['REMOTE_ADDR'])
            || preg_match('/^127\..*/i', trim($_SERVER['REMOTE_ADDR'])) || preg_match('/^172\.16.*/i', trim($_SERVER['REMOTE_ADDR']))
            || preg_match('/^192\.168\.*/i', trim($_SERVER['REMOTE_ADDR'])) || preg_match('/^10\..*/i', trim($_SERVER['REMOTE_ADDR'])))) {
            if (strpos($_SERVER['HTTP_X_FORWARDED_FOR'], ',')) {
                $ips = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);

                return $ips[0];
            } else {
                return $_SERVER['HTTP_X_FORWARDED_FOR'];
            }
        } else {
            return $_SERVER['REMOTE_ADDR'];
        }
    }

```

**Comment by khouloudbelguith** [comment] 2019-05-30 08:32
Hi @finlanderid,

Thanks for your report.
Have you the same issue reported in this ticket: #13074?

Thanks!

**Comment by finlanderid** [comment] 2019-05-30 13:10
Hi @khouloudbelguith,

no, this is a different issue than #13074.   This issue prevents true visitor IP from being captured from X_FORWARDED_FOR, when visitor comes through a CDN that uses an IP address that does not begin with 127 or 172 or 192 or 10.  If that happens, then the IF evaluation will fail, but it should not fail.  It should succeed so that X_FORWARDED_FOR will be used for the visitor IP.  The problem is that the IF evaluation constrains the potential CDN IP values to those four IP starting strings (in order to properly succeed), but CDNs use IPs that start with many, many **_other_** strings.

**Comment by khouloudbelguith** [comment] 2019-05-30 13:38
@finlanderid, thanks for your feedback.
@PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-15 15:10
Duplicate of #17117

**Closed as completed by khouloudbelguith** 2020-01-15 15:10 UTC
Labels: Bug, CO, Duplicate
