### ISSUE TITLE
Product detail - a specific price with quantity_from = 1 -> wrong prices displayed upon a quantity input changes

### ISSUE THREAD

**Issue by jancinert** [PrestaShop/PrestaShop#10710] opened 2018-09-26 00:37 UTC
**To Reproduce**
1. Install prestashop 1.6.1.20
2. Edit product demo_2 from demo database in backend.
3. Add specific price with parameters:
combination S white
quantity from: 1
discount 10%
4. Add another specific price with parameters:
combination S white
quantity from: 2
discount 10%
5. Go to frontend product detail page and make combination S White the active one.
6. Change a quantity box value to 2 and see unit price value wrong

**Screenshots**
![snimek obrazovky porizeny 2018-09-26 21-32-38](https://user-images.githubusercontent.com/5624510/46104631-1f783800-c1d4-11e8-9203-d41c96b9585e.png)
![snimek obrazovky porizeny 2018-09-26 21-32-52](https://user-images.githubusercontent.com/5624510/46104632-1f783800-c1d4-11e8-8145-6fdfb41c3836.png)

**Additional information**
PrestaShop version: 1.6.1.20
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-09-26 09:02
Hi @jancinert,

Thanks for your report & your PR.
Could you please add steps to reproduce your issue so we can test your fix.

Thanks & Best regards, Khouloud

**Comment by jancinert** [comment] 2018-09-26 19:36
> Hi @jancinert,
> 
> Thanks for your report & your PR.
> Could you please add steps to reproduce your issue so we can test your fix.
> 
> Thanks & Best regards, Khouloud

Added.

**Comment by khouloudbelguith** [comment] 2018-09-27 08:40
Hi @jancinert,

Thanks for the clarifications.
I manage to reproduce the issue with PS 1.6.1.20.
@marion what do you think?
Here's the fix: #10711

Best regards, Khouloud

**Comment by jancinert** [comment] 2018-09-27 09:54
Addendum:
I tried to keep code changes short.
Because pull requests with many changes tend to be not accepted by the team (no offence...).

But an ideal fix would be to code refactor whole product.js theme file.

**Comment by marionf** [comment] 2019-02-06 10:32
Duplicate of #10730

**Closed as completed by marionf** 2019-02-06 10:32 UTC
Labels: Bug, FO, Duplicate, Discounts
