### ISSUE TITLE
Product page not showing all attributes

### ISSUE THREAD

**Issue by TucoSalamanca** [PrestaShop/PrestaShop#17231] opened 2020-01-17 19:44 UTC
So i have the following problem when adding attributes to products, if i add color attribute it shows up on product page and everything is ok, if i continue to add size attributes it replaces the color attribute and its only showing the size selection (the color attributes are not showing anymore), any ideas how to fix it?

Im running custom theme on prestashop 1.7.6.0

here is product-variant.tpl, hope it helps, thanks!

```
<div class="product-variants">
  {foreach from=$groups key=id_attribute_group item=group}
  {if !empty($group.attributes)}
    <div class="clearfix product-variants-item">
      <span class="control-label">{$group.name}</span>
      {if $group.group_type == 'select'}
        <select
          class="form-control form-control-select"
          id="group_{$id_attribute_group}"
          data-product-attribute="{$id_attribute_group}"
          name="group[{$id_attribute_group}]">
          {foreach from=$group.attributes key=id_attribute item=group_attribute}
            <option value="{$id_attribute}" title="{$group_attribute.name}"{if $group_attribute.selected} selected="selected"{/if}>{$group_attribute.name}</option>
          {/foreach}
        </select>
      {elseif $group.group_type == 'color'}
        <ul id="group_{$id_attribute_group}">
          {foreach from=$group.attributes key=id_attribute item=group_attribute}
            <li class="float-xs-left input-container">
              <label>
                <input class="input-color" type="radio" data-product-attribute="{$id_attribute_group}" name="group[{$id_attribute_group}]" value="{$id_attribute}"{if $group_attribute.selected} checked="checked"{/if}>
                <span
                  {if $group_attribute.html_color_code}class="color" style="background-color: {$group_attribute.html_color_code}" {/if}
                  {if $group_attribute.texture}class="color texture" style="background-image: url({$group_attribute.texture})" {/if}
                ><span class="sr-only">{$group_attribute.name}</span></span>
              </label>
            </li>
          {/foreach}
        </ul>
      {elseif $group.group_type == 'radio'}
        <ul id="group_{$id_attribute_group}">
          {foreach from=$group.attributes key=id_attribute item=group_attribute}
            <li class="input-container float-xs-left">
              <label>
                <input class="input-radio" type="radio" data-product-attribute="{$id_attribute_group}" name="group[{$id_attribute_group}]" value="{$id_attribute}"{if $group_attribute.selected} checked="checked"{/if}>
                <span class="radio-label">{$group_attribute.name}</span>
              </label>
            </li>
          {/foreach}
        </ul>
      {/if}
    </div>
    {/if}
  {/foreach}
</div>

```

**Comment by sarahdib** [comment] 2020-01-20 14:11
Hello @TucoSalamanca 

Do you have the problem is in front office or back office ?

Thank you

**Comment by josegarvinvictoria** [comment] 2020-01-21 19:13
I am experiencing the same problem. On the products page with more than one attribute (front office) only the attribute that is in the first position of the "Attributes and features" page of the products (back office) is shown.

I have changed the order from the back office and if another attribute is placed as the first, the changes are reflected on the product page (front office) but only one is shown.

Sorry for my English.

**Comment by TucoSalamanca** [comment] 2020-01-22 06:18
> 
> 
> Hello @TucoSalamanca
> 
> Do you have the problem is in front office or back office ?
> 
> Thank you

Thanks for your reply!
Only in front office, back office is showing all attributes just fine and i can edit them & change stock for each of them etc.

**Comment by TucoSalamanca** [comment] 2020-01-22 06:28
This is how my back office looks with more attributes, everything looks fine
https://imgur.com/a/HQJPoGs
And this is how front office looks with all the attributes from the picture above
https://imgur.com/a/73cTObX

From 3 attributes Size / color / canvas size its only showing the size one, not the other two.

Now if i remove the size attributes and the back office looks like this 
https://imgur.com/a/2RgwvoS
The front office looks like this 
https://imgur.com/a/0S0kCpT
So you can see the color attributes has showed up, even if i have canvas size attributes aswell thats not displayed, and if we continue to delete the color attribute aswell
https://imgur.com/a/LeqFv4u
we get to show the canvas size attribute on front office like this 
https://imgur.com/a/tXCPVP7

My aim here is to be able to display 2 attributes (size S/M/L etc + color)

EDIT: I have also tried switching to the default theme and it has the same problem

**Comment by khouloudbelguith** [comment] 2020-01-22 09:57
Hi @TucoSalamanca,

Your combinations are not correctly generated.
Then, in the right column, you should select all your combinations (from your 1 group and click on "Generate" => for example in this product, you have some combination like: `Culoare -Rosu`, `Culoare - Alb`,...
I have to close this ticket because, in the combination list, every combination needs to have the same attributes as the others. I mean You can't have, in the same product, combinations with `Culoare` and some others with `Marime` and other with `Dimension`.
All of them need to have `Culoare + Marime + Dimension` or `Culoare` or `Marime` or `Dimension`.

First, you should delete all your combinations & re-cretae them.
Second, the solution could be like this: Culoare: Rosu, Culoare: Alb,... for product A / Marime: XS, Marime: S, Marime: L`,... for product B

I close the ticket, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2020-01-22 09:57 UTC
Labels: Bug, FO, Combinations, No change required, 1.7.6.0
