### ISSUE TITLE
Hamburger Menu issue on prestashop website

### ISSUE THREAD

**Issue by carinamoraru** [PrestaShop/PrestaShop#34733] opened 2023-11-30 02:03 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, How are you?
I have one issue on prestashop website(prestashop core's issue).
prestashop is showing both descktop menu and hamburger menu.
And hamburger menu dont work well.
There's a display problem in the header, some entries are taken out of the menu and there's a double menu, classic and hamburger.
I think Only the hamburger menu should appear on iPad.
Please check attached image file.
my website url: convertiblecenter.dev.yateo.com
user : yateo
pass : WtTfkD7jRGcPFWQgXEHh
i am waiting for your reply
Best regards
Carina
![Untitled](https://github.com/PrestaShop/PrestaShop/assets/108097833/87aed2de-9f00-4949-993c-bebf3354654e)

### Steps to reproduce

1. go to convertiblecenter.dev.yateo.com
2. put user name and password
user : yateo
pass : WtTfkD7jRGcPFWQgXEHh
3. go to https://convertiblecenter.dev.yateo.com/12-canapes-convertibles
4. can see both hamburger menu and desktop menu
5. hambuger menu dont work well

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

carina

**Comment by paulnoelcholot** [comment] 2023-12-01 09:10
Hello @carinamoraru,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2023-12-01 09:10 UTC
Labels: Bug, Can't reproduce, Invalid
