### ISSUE TITLE
Bots creating new users

### ISSUE THREAD

**Issue by matutin0** [PrestaShop/PrestaShop#16355] opened 2019-11-11 15:01 UTC
**Describe the bug**
Since November the 3th (8 days ago) there are dozens of new users registered on our website with e-mail addresses that look real and names/surname made by random characters. I don't know how to stop it. Seems similar to the issue about spam sent through the contact page, but is not the same. Totally looks like a bot behavior.

**To Reproduce**
It's just about to check your clients list in the back office.

**Screenshots**
![Captura de pantalla 2019-11-11 a las 14 56 45](https://user-images.githubusercontent.com/57630560/68596812-c0d35380-0493-11ea-9cd8-e48dc9e722b8.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1.32

**Comment by khouloudbelguith** [comment] 2019-11-11 15:28
Hi @matutin0,

Your ticket is a duplicate of #16327
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-11-11 15:28
Duplicate of #16327

**Closed as completed by khouloudbelguith** 2019-11-11 15:28 UTC
Labels: Duplicate

**Comment by matks** [comment] 2019-11-15 10:06
Hi @matutin0  

Like it was said in #16327, the very best protection against such spam is a reCAPTCHA.

ReCAPTCHA was designed to stop bots from submitting any form. It's the exact solution to use for this specific usecase. Nothing will be more efficient 😉.
