### ISSUE TITLE
$this->addJS in module not loading front js files in layout

### ISSUE THREAD

**Issue by jinpresta** [PrestaShop/PrestaShop#36200] opened 2024-05-20 15:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We're trying to load some custom js files from a hook action. 
In our hook action : 
`$this->context->controller->addJS([somepath].js); `
it seams to go throught `addJS` function but the files are not loaded 

### Steps to reproduce

1. call `addJS` function in hook action with `$this->context->controller`
2. go through `addJS` function in `PrestaShop/classes/controller/Controller.php` and try to print` $js_files`
a bunch of JS files in this list are not loaded on layout 

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_mbo

**Comment by paulnoelcholot** [comment] 2024-05-21 10:45
Hello @jinpresta,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by kpodemski** [comment] 2024-05-22 11:23
Maybe could be useful: https://github.com/PrestaShop/PrestaShop/pull/21016

**Comment by matks** [comment] 2024-07-08 13:10
Hello @jinpresta this bug report is not accurate enough, can you tell us which hook, which page exactly?

The best would be an example like
1. I do (...)
2. I browse page (...)
3. You can see (...)

**Comment by matks** [comment] 2024-07-08 18:34
Might have been fixed by https://github.com/PrestaShop/PrestaShop/pull/36433

**Comment by paulnoelcholot** [comment] 2024-08-07 08:35
Hello @jinpresta,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-08-07 08:35 UTC
Labels: Bug, develop, Invalid
