### ISSUE TITLE
Prestashop 1.7.6.3 problem in paypal 

### ISSUE THREAD

**Issue by Mejdios** [PrestaShop/PrestaShop#19817] opened 2020-06-17 11:07 UTC
Dear Friend 
paypal discount not working prestashop 1.7.6   
Thanks for Help

**Comment by Matt75** [comment] 2020-06-17 11:13
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19779

**Comment by colinegin** [comment] 2020-06-17 12:57
Hello @Mejdios ,

I close this issue as this is a duplicate of #19779. Please follow this issue.

Thanks !

**Closed as completed by colinegin** 2020-06-17 12:57 UTC
Labels: Duplicate
