### ISSUE TITLE
Strange round price for modules

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#14698] opened 2019-07-17 07:50 UTC
**Describe the bug**
I have some strange module prices displayed on PS 1.7.6.0.
French BO in Euro (€).
Some prices are : 29.990000000000002 € (see screenshot below).

**To Reproduce**
1. Go to Modules > Catalog of Modules
2. See strange prices for some modules

**Screenshots**
![module-prices](https://user-images.githubusercontent.com/7419525/61357130-054d3a80-a878-11e9-873e-f23ca4f7357b.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-17 08:34
Hi @Klemart3D,

Thanks for your report.
This issue seems related to https://github.com/PrestaShop/PrestaShop/issues/14608.
Could you please try to replace precision to `2` in the table `ps_currency`, clear cache, check & feedback.

Thanks!

**Comment by Klemart3D** [comment] 2019-07-17 12:33
Yes it related, my current instance is an upgrade from PS 1.7.5.1 to 1.7.6.0 and I'm in the second case of #14608.

Before upgrade, my `ps_currency` table was:

id_currency | name | iso_code | conversion_rate | deleted | active
--------------- | ------- | ------------ | -------------------- | --------- | -------
1| 'euro'| 'EUR'| 1.000000| 0| 1

Now it is:

id_currency | name | iso_code | *numeric_iso_code* | *precision* | conversion_rate | deleted | active
--------------- | ------- |-------------|---------------------------| ------------- | -------------------- | --------- | -------
1|euro|EUR| 0|6|1.000000| 0| 1

I changed `precision` from `6` to `2` and cleared cache but bug still persists :

![bug-price2](https://user-images.githubusercontent.com/7419525/61375627-a00d3f80-a89f-11e9-8f36-02f58bec38a9.png)

Seems only for module displaying the specific price of `29.99` (not for other prices).

**Comment by khouloudbelguith** [comment] 2019-07-17 12:49
@Klemart3D, thanks for your feedback.
In your BO => Shop Parameters => General page => the number of decimals is set to 2?
Thanks!

**Comment by Klemart3D** [comment] 2019-07-17 13:05
Yes, set to 2 decimals. But it's not specific to my shop, I can found same bug on your official demo Prestashop website:
![bug-price3](https://user-images.githubusercontent.com/7419525/61377797-3a6f8200-a8a4-11e9-986a-63175e64e95c.png)

**Comment by Quetzacoalt91** [comment] 2019-07-17 15:39
This information is provided by the marketplace:

![image](https://user-images.githubusercontent.com/6768917/61389842-e40d3e00-a8b9-11e9-889b-bf7d104c611f.png)

**Comment by colinegin** [comment] 2019-09-25 15:28
@khouloudbelguith IMO this issue has been fixed with 1761, can you confirm we can close this issue ?

**Comment by khouloudbelguith** [comment] 2019-09-25 15:33
Hi @colinegin,

No, I manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/1h0hNpneVqLhk9NLAzHD5JNYrNGUhWC4C/view
Thanks!

**Comment by Matt75** [comment] 2020-05-25 19:00
I think this is fixed in ps_mbo v2.0.0

**Comment by marionf** [comment] 2020-05-26 09:07
@PrestaShop/prestashop-qa Could you check if it's well fixed with ps_mbo v2.0.0 and close this issue if it is ?

**Comment by sarahdib** [comment] 2020-05-29 09:37
The problem is fixed with ps_mbo v2.0.0

**Closed as completed by sarahdib** 2020-05-29 09:37 UTC
Labels: Bug, Minor, BO, Modules, Modules catalog, Fixed, MBO, 1.7.5.2, 1.7.6.0, 1.7.6.1
