### ISSUE TITLE
Problem when I try to add a product to cart

### ISSUE THREAD

**Issue by passio777x** [PrestaShop/PrestaShop#21172] opened 2020-09-26 17:15 UTC
Hi, on Prestashop 1.7.6.7
For an unknow reason, the in a Private navigation (or new session), the 2 first try when I click on "Add to cart", it move me to the cart without adding the product. (It should add the product and not switch page to cart).

This occured with 1 others problem, that could maybe be related. I don't know.

When I recompile, I got this error : 
**Fatal error: require(): Failed opening required '/var/www/vhosts/***.fr/httpdocs/var/cache/prod/ContainerE7hcpdr/removed-ids.php' (include_path='/var/www/vhosts/***.fr/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/***.fr/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/***.fr/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/***.fr/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/***.fr/httpdocs/var/cache/prod/ContainerE7hcpdr/appProdProjectContainer.php on line 1616**

Do you have any idea about how I could solve this problem ? (I don't know if it's related  to the cache error, be the add to cart problem is the most important).

I join this picture that is what I see when i'm redirected to the cart that could be an indication.

<img width="320" alt="Capture d’écran 2020-09-26 à 19 11 07" src="https://user-images.githubusercontent.com/43704805/94346393-b29b1100-002c-11eb-95c4-7e23f76ee606.png">

**Comment by khouloudbelguith** [comment] 2020-09-28 09:01
Hi @passio777x,

I did not manage to reproduce the issue with PS1.7.6.8.
I attached a screen record
https://drive.google.com/file/d/1gXNRJFRaMlcujDUTMjfV-241xBnLTpSO/view?usp=sharing
It is a cache issue
Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Also, try to clear the cache manually by deleting all the folders into var/cache (prod & dev).
Don't forget to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-10-19 08:27
Hi @passio777x,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-19 08:27 UTC
Labels: Bug, FO, No change required, Shopping carts FO, 1.7.6.7
