### ISSUE TITLE
jQuery UI overrides bootstrap tooltip component

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25738] opened 2021-08-30 12:21 UTC
#### Describe the bug

When modules adds jQuery UI library (for example ps_searchbar, ps_facetedsearch), it is included in template due to higher priority after theme.js where bootstrap library is included. Bootstrap and jQuery UI uses $.fn.tooltip method for their tooltip components. When jQuery UI is included it overrides bootstrap tooltip method.

#### Expected behavior

JQuery UI should be included before theme.js file. To prevent it from overriding bootstrap tooltip component. 

#### Steps to Reproduce

1. Go to product page.
2. Open `themes/classic/templates/catalog/product.tpl` and place there inside `{block name='page_header_container'}` block. 

```
<span data-toggle="tooltip" title="tooltip content">tooltip hover me</span>
```
3. Open `themes/classic/assets/js/custom.js` and paste this code:
```
$(() => {
  $('[data-toggle="tooltip"]').tooltip();
})
``` 
4. Go back to product page and hover on that span.
Tooltip should appear with white background and box-shadow (it is jQuery UI tooltip).

<img width="230" alt="Zrzut ekranu 2021-08-30 o 14 20 46" src="https://user-images.githubusercontent.com/25306716/131337993-a65bc5e1-923a-4262-ab48-5d98423d87c4.png">

5. Go BO and disable ps_searchbar module.
6. Go back to product page and refresh.
7. Hover on span and red tooltip should appear. (it is bootstrap tooltip).
<img width="292" alt="Zrzut ekranu 2021-08-30 o 14 21 16" src="https://user-images.githubusercontent.com/25306716/131338053-3d207f1b-ddfb-4045-9cb7-b938bc4a3d51.png">

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-08-30 16:54
Hello @Oksydan 

I reproduce the issue with PS1770 & PS1775, see the attached screen record below:

https://drive.google.com/file/d/1lF6mXV270Y6bVRPxrIdU7qfXv51XbZQF/view

It's a regression cause with PS1767, I didn't manage to reproduce the issue (searchbar is enabled or disabled, the css of tooltip doesn't change), see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/131375394-fc136b83-025e-42e6-b070-20909e8fa024.png)

Thanks for reporting the issue! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-09-02 20:21
(Ping @NeOMakinG)

**Closed as completed** 2021-11-16 13:49 UTC
Labels: Bug, Trivial, FO, Regression, Fixed, Front-end, PR available, 1.7.7.0
