### ISSUE TITLE
Module Dashproducts Total product views is irrelevant

### ISSUE THREAD

**Issue by moflihmorad** [PrestaShop/PrestaShop#29302] opened 2022-08-10 15:03 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In Prestashop dashboard -> Dashproducts module

Total products views are fragmented (due to the formulated SQL request) resulting in showing multiple times the same product with each time different view count value (see picture 1). 

![issue-image-1](https://user-images.githubusercontent.com/71391149/183938018-2255c044-610e-4044-b616-0f6698b63af9.png)

### Expected behavior

diving into code **dashproducts.php** we can see that in function **getTotalViewed()** the formulated sql request is the issue; the date_range left_join fragments the results of the same product as this product is viewed multiple times during different days (date_ranges) during the given period.

a solution to this can simply be adding **SUM(pv.counter) as `counter`** to SELECT clause and **GROUP BY p.id_object.** this will be a much more useful query that is relevant and meaningful as a products views insight for the user.

```
SELECT p.id_object, SUM(pv.counter) as `counter`
			FROM `'._DB_PREFIX_.'page_viewed` pv
			LEFT JOIN `'._DB_PREFIX_.'date_range` dr ON pv.`id_date_range` = dr.`id_date_range`
			LEFT JOIN `'._DB_PREFIX_.'page` p ON pv.`id_page` = p.`id_page`
			LEFT JOIN `'._DB_PREFIX_.'page_type` pt ON pt.`id_page_type` = p.`id_page_type`
			WHERE pt.`name` = \'product\'
			'.Shop::addSqlRestriction(false, 'pv').'
			AND dr.`time_start` BETWEEN "'.pSQL($date_from).'" AND "'.pSQL($date_to).'"
			AND dr.`time_end` BETWEEN "'.pSQL($date_from).'" AND "'.pSQL($date_to).'"
			GROUP BY p.id_object
			ORDER BY `counter` DESC
			LIMIT '.(int)$limit);
```

instead of 

```
SELECT p.id_object, pv.counter
			FROM `'._DB_PREFIX_.'page_viewed` pv
			LEFT JOIN `'._DB_PREFIX_.'date_range` dr ON pv.`id_date_range` = dr.`id_date_range`
			LEFT JOIN `'._DB_PREFIX_.'page` p ON pv.`id_page` = p.`id_page`
			LEFT JOIN `'._DB_PREFIX_.'page_type` pt ON pt.`id_page_type` = p.`id_page_type`
			WHERE pt.`name` = \'product\'
			'.Shop::addSqlRestriction(false, 'pv').'
			AND dr.`time_start` BETWEEN "'.pSQL($date_from).'" AND "'.pSQL($date_to).'"
			AND dr.`time_end` BETWEEN "'.pSQL($date_from).'" AND "'.pSQL($date_to).'"
			ORDER BY `counter` DESC
			LIMIT '.(int)$limit);
```

![issue-image-2](https://user-images.githubusercontent.com/71391149/183938099-ea22246e-fd09-40c6-abb9-c685bde5c3b9.png)

### Steps to reproduce

1. go to Dashboard
2. Check products and sales-> most viewed

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

dashproducts 2.1.1

**Comment by HanaRebaiQA** [comment] 2022-08-11 14:48
Hello @moflihmorad 

Thanks for your report.
I guess that your ticket is a Feature instead of bug. 
I found this one [#23348](https://github.com/PrestaShop/PrestaShop/issues/23348) that seems be duplicate of yours. Could you confirm it ? 

Thank You!

**Comment by moflihmorad** [comment] 2022-08-12 14:22
hi @HanaRebaiQA 

i think what @marionf is suggesting is an overhaul of separated dashboard modules into one which is good, should the Prestashop team chose to go this way, then we can dismiss my report or better it can be incorporated in the overhaul to avoid adding same issue again, otherwise my report is a quickfix to an already existing sql query.

you are most welcome.

**Comment by hibatallahAouadni** [comment] 2022-08-16 07:12
Hello @moflihmorad 

Could you please provide a screen record :pray: Cause I didn't manage to reproduce the issue with the provided infos.
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-09-05 08:50
Hello @moflihmorad 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-09-05 08:50 UTC
Labels: Bug, BO, Dashboard, Dashproducts, 1.7.7.5, Invalid, Module
