### ISSUE TITLE
ps_googleanalytics - creates many "purchase"-events in BO

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#34053] opened 2023-09-25 11:36 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PrestaShop 8.1.1
with ps_googleanalytics v. 4.2.2

I have experienced that it suddenly sends a ton of "purchase"-events from the BackOffice to Google Analytics, which totally pollutes my tracking data.

First, I couldn’t understand why the number of conversions (and the conversion value) was suddenly so much higher than the actual numbers.
After some investigation, I noted that these “fake conversions” (in lack of better words) had been created from the Back Office:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/0a5ff697-5bdd-496a-a299-e9e1f700b630)

First of all, this shouldn't happen.

Second of all, I have actually disabled GA-tracking in the back office:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/b44a04bb-4ee9-4ae9-b078-5e38d0f38a61)

NOTE: I have censored the actual path to my back office and my GA-id from the screendumps above. Both actually have different values in real life.

### Expected behavior

When Google Analytics tracking for the Back Office has been disabled/turned off, it shouldn't track anything in the Back Office.

Secondly, I have not done anything in the back office that should be triggering a "purchase"-event. So I would not expect it to trigger any "purchase"-events in any case.

### Steps to reproduce

I don't actually know how to reproduce the error: I have tried different things, but was unable to reproduce it.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_googleanalytics v. 4.2.2

**Comment by sallemiines** [comment] 2023-09-28 09:12
Hello @LarsGMortensen 

Could you please provide us with screenshots or a screen recording describes the full scenario of your problem! unfortunately the steps you have defined are not enough to reproduce the problem!

Please check and feedback !
Thank you !

**Comment by zozoseo** [comment] 2023-10-25 19:56
Do you have any update on the resolution since your post ?

**Comment by paulnoelcholot** [comment] 2023-11-02 10:50
Hello @LarsGMortensen,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2023-11-02 10:50 UTC
Labels: Bug, Waiting for author, BO, Google Analytics, Module, 8.1.x
