### ISSUE TITLE
Can't import a theme after export

### ISSUE THREAD

**Issue by rtvt** [PrestaShop/PrestaShop#12382] opened 2019-01-31 07:48 UTC
I've exported theme from perfect working 1.7.5 without any errors and can't import it in clean install of another 1.7.5. Got this error: 
Warning on line 353 in file .../src/Core/Addon/Theme/ThemeManager.php
[2] file_get_contents(.../var/cache/dev/sandbox/5c520159ca28a//config/theme.yml): failed to open stream: No such file or directory

Notice on line 49 in file .../src/Core/Addon/Theme/Theme.php
[8] Undefined index: name

I checked zip file of theme and it's 100% correct and all files including config/theme.yml are here. 
I have cleared cache, delete config/themes/themename/shop1.json, set 777 to whole site recusively. I found somewhere that theme can be "zipped wrong" and unpack and rezip by hands can help - tried, but nothing.

**Comment by khouloudbelguith** [comment] 2019-01-31 09:13
Hi @rtvt,

I did not manage to reproduce the issue with PS1.7.5.0.
I tried with custom following these steps:
1. Shop1: export the theme => zip successfully exported
2. Shop2: import the zip downloaded => OK.

I attached a video record
https://drive.google.com/file/d/1Bejol9lbq7wrTLEd8I0JVqp-AitS2ztI/view
Could you please try to export your theme using the command from your terminal as described in this [link](https://devdocs.prestashop.com/1.7/themes/distribution/exporting/)

`php bin/console prestashop:theme:export THEME_DIRECTORY_NAME`

Thanks to check & feedback.

**Comment by rtvt** [comment] 2019-01-31 12:00
Thank you for answer. Hmm, I got this: https://gyazo.com/913bf357e43f7b6415401fa460c655ce

**Comment by khouloudbelguith** [comment] 2019-01-31 13:52
Hi @rtvt,

Could you please provide me with your theme to test it.
This is a public space.
You can provide me the theme by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by rtvt** [comment] 2019-01-31 14:23
Hi @khouloudbelguith, thank you, I just sent you a mail.

**Comment by khouloudbelguith** [comment] 2019-01-31 14:24
@rtvt, thanks!
I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-31 15:04
Hi @rtvt,

I unzipped the folder provided, but the strange thing, that it contains only files without folders
![image](https://user-images.githubusercontent.com/16067358/52062950-cc433700-2571-11e9-8723-ab9241a935b3.png)
This is an invalid theme, so I can't upload it.
Thanks!

**Comment by rtvt** [comment] 2019-01-31 15:38
Thank you for check, so this is a .zip created by Prestashop after click on export theme button. From working theme with all the files and folder. I don't understand why it shows folder as filenames with \ slash.

**Comment by khouloudbelguith** [comment] 2019-01-31 15:39
@rtvt, could you please provide your theme not exported, but before the export, to check it.
Thanks!

**Comment by rtvt** [comment] 2019-02-04 07:50
@khouloudbelguith Thank you for assistant!
I think it's solved. It seems that it's related to server archivator extension, cause after I transfer my whole shop to online server from local, then exported a theme - I got normal working archive, which can be imported to other Presta. I saw few similar posts on forum without answers, hope it will help.

**Comment by khouloudbelguith** [comment] 2019-02-04 10:36
Hi @rtvt,

Thanks for your feedback.
Since your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-04 10:36 UTC
Labels: BO, Can't reproduce, Design, Modules & Themes, 1.7.5.0
