### ISSUE TITLE
500 error after upgrade 1.7.4.4 to 1.7.5 : warning updating database

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#12134] opened 2019-01-12 16:00 UTC
During updating database, warnings below resultuted in 500 error for front and back office

[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE `ps_supply_order_receipt_history` CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '', CHANGE `employee_lastname` `employee_firstname` VARCHAR(255) DEFAULT '': Duplicate column name 'employee_firstname'
[OK] SQL 1.7.5.0 ALTER TABLE `ps_supplier_lang` CHANGE `meta_description` `meta_description` VARCHAR(512) DEFAULT NULL, CHANGE `meta_title` `meta_title` VARCHAR(255) DEFAULT NULL
[OK] SQL 1.7.5.0 ALTER TABLE `ps_order_detail` CHANGE `product_reference` `product_reference` varchar(64) DEFAULT NULL
[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE `ps_product` CHANGE `reference` `supplier_reference` varchar(64) DEFAULT NULL, CHANGE `supplier_reference` `supplier_reference` varchar(64) DEFAULT NULL: Duplicate column name 'supplier_reference'
[OK] SQL 1.7.5.0 ALTER TABLE `ps_product_attribute` CHANGE `reference` `reference` varchar(64) DEFAULT NULL, CHANGE `supplier_reference` `supplier_reference` varchar(64) DEFAULT NULL
[OK] SQL 1.7.5.0 ALTER TABLE `ps_warehouse` CHANGE `reference` `reference` varchar(64) DEFAULT NULL
[OK] SQL 1.7.5.0 ALTER TABLE `ps_stock` CHANGE `reference` `reference` varchar(64) DEFAULT NULL
[OK] SQL 1.7.5.0 ALTER TABLE `ps_supply_order_detail` CHANGE `reference` `reference` varchar(64) NOT NULL, CHANGE `supplier_reference` `supplier_reference` varchar(64) NOT NULL
[OK] SQL 1.7.5.0 ALTER TABLE `ps_product_supplier` CHANGE `product_supplier_reference` `product_supplier_reference` varchar(64) DEFAULT NULL
[OK] SQL 1.7.5.0 ALTER TABLE `ps_product_lang` CHANGE `meta_description` `meta_description` varchar(512) DEFAULT NULL, CHANGE `meta_keywords` `meta_keywords` varchar(255) DEFAULT NULL
[OK] SQL 1.7.5.0 ALTER TABLE `ps_customer_thread` CHANGE `email` `email` varchar(255) NOT NULL
[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE `ps_stock_available` ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`: Duplicate column name 'location'

**Comment by khouloudbelguith** [comment] 2019-01-15 08:14
Hi @Peter4661,

We manage to reproduce the issue.
Here's the PR: #11814 to fix the issue.
Your ticket is a duplicate of #11812
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-01-15 08:15
Duplicate of #11812

**Closed as completed by khouloudbelguith** 2019-01-15 08:14 UTC
Labels: Duplicate
