### ISSUE TITLE
Double order with the same transaction ID (paypal payment method)

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#11399] opened 2018-11-15 09:41 UTC
**Describe the bug**
Dear staff, 
we receive two identical order with the same transaction ID.
Orders have a gap, one from the other, of a few seconds!

order 1 - 14/11/2018 18:46:08
order 2 - 14/11/2018 18:46:13

We contacted the customer, he had no problems during the transaction.
We have forwarded the same request to the server service and to PayPal one.
Have you ever had a similar problem?
Thanks.

**To Reproduce**
1. Go to 'we can not reproduce'
2. Click on 'we can not reproduce'
3. Scroll down to 'we can not reproduce'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![ordine-doppio-github](https://user-images.githubusercontent.com/28685316/48543532-0b8eaf80-e8c2-11e8-9bf8-472749574b54.png)

![ordine-doppio-github-02](https://user-images.githubusercontent.com/28685316/48543779-7f30bc80-e8c2-11e8-94a6-3b316a6cd0e7.png)

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2018-11-15 10:19
Hi @ballashop,

I did not manage to reproduce the issue with 1.6.1.23 & the PayPal module v3.11.6.
I created two orders at the same time with different customers, but the orders are successfully created without errors.
![image](https://user-images.githubusercontent.com/16067358/48546292-44ca1e00-e8c8-11e8-9ddf-6a3b7845850b.png)
Are there any errors in your log file?
Thanks!

**Comment by ballashop** [comment] 2018-11-15 10:37
Hi @khouloudbelguith,
thanks to reply me, yes, we have a mailchimp error. 
"MailChimp error: A cart with the provided ID already exists in the account. url:..."
How can I send you a log file?
Is it possible in private mode?
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-15 10:41
@ballashop, so this issue occurs due to the mail chimp module?
This is a previous ticket: http://forge.prestashop.com/browse/BOOM-5486 about this issue.
Thanks to check & feedback.

**Comment by ballashop** [comment] 2018-11-15 10:46
Thanks @khouloudbelguith,
I'm going to contact the module Mailchimp developer.
I return to write soon what they told me
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-15 10:49
@ballashop, thanks!
Waiting for your feedback.

**Comment by ballashop** [comment] 2018-11-24 15:07
Hi @khouloudbelguith,
the problem is no longer presented, very strange, however we have disabled the mailchimp module because it required mysql 5.7. Unfortunately we have an older version 5.0.92 and therefore not compatible. I think you can close that issue.
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2018-11-26 14:14
Hi @ballashop,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-26 14:14 UTC
Labels: Bug, BO, Can't reproduce, Order
