### ISSUE TITLE
Wrong total cost in the Back Office in Total spent since registration

### ISSUE THREAD

**Issue by lilwayne470** [PrestaShop/PrestaShop#15212] opened 2019-08-22 01:34 UTC
**Wrong total cost in the Back Office in Total spent since registration**
In the Back Office on Prestashop 1.7.5.2.

**To Reproduce**
After a customer order as a guest:
1. Go to Orders
2. Click on the customer order to view order details
3. On the right Card titled Customer, click on the button 'Transform a guest into a customer'
4. You will see the Total amount listed isn't the same you have on Paypal

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-22 09:29
Hi @lilwayne470,

I did not manage to reproduce the issue with PS1.7.6.0 & the branch 1.7.6.x (next version PS1.7.6.1.)
I attached a screen record
https://drive.google.com/file/d/1O5Mz4hT1xf0axqEdyueC30A-1IFo22VO/view
Thanks to check & feedback.

**Comment by lilwayne470** [comment] 2019-09-02 17:21
Thanks you @khouloudbelguith, i will update my version and see if it work

**Comment by khouloudbelguith** [comment] 2019-09-03 08:10
@lilwayne470, thanks!
Waiting for your feedback.

**Comment by lilwayne470** [comment] 2019-09-05 02:45
Hi @khouloudbelguith i update my prestashot to 1.7.6 but i still have the same issue
see picture

![image](https://user-images.githubusercontent.com/7246518/64307857-523eba80-cf65-11e9-958e-69f420feaf6a.png)

I really dont know what s wrong, Below the real subtotal


Subtotal   $104.49
Shipping and handling  Free
Tax   $5.23
TOTAL (tax excl.) | $104.49

**Comment by khouloudbelguith** [comment] 2019-09-05 16:08
Hi @lilwayne470,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-07 07:50
Hi @lilwayne470,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-07 07:50 UTC
Labels: Bug, BO, Order, No change required, 1.7.5.2
