### ISSUE TITLE
Combinations with multiple color groups show only colors from the first group on the product page

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#12511] opened 2019-02-08 13:23 UTC
If you add multiple different color groups to combinations (without connecting them) only the first group is displayed on product page, however hovering above quick preview indicates that all colors are there.

This is problematic for products like doors where there can be multiple texture/finish types.
This gallery explains the issue: https://imgur.com/a/foGVZWE

**To reproduce:**
1. Create color attribute group called "Test Colors A", add 2 colors to it
2. Create color attribute group called "Test Colors B", add 2 colors to it
3. Create a test product with combinations
4. On combinations tab add all colors from "Test Colors A", click Generate
5. On combinations tab add all colors from "Test Colors B", click Generate
6. Combinations list should now have 4 entries, save product
7. Go to product listing/search for it, notice how hovering over quick preview shows all four colors
8. Visit product page and see only "Colors A" being displayed

**Additionnal information**
PrestaShop version: 1.7.5.0 
PHP version: 7.1.13

Currently minimal set of modules is activated (no 3rd party ones), as we are currently in the process of importing products and combinations and making sure everything will end up fine.

**Comment by khouloudbelguith** [comment] 2019-02-08 13:33
Hi @sudub,

This is not a bug, it is normal behavior.
In the combination list, every combination needs to have the same attributes than the others. I mean you can't have, in the same product, combinations with `Test Colors A`  and some others with `Test Colors B`.
All of them need to have `Test Colors A` + `Test Colors B` or `Test Colors A` or `Test Colors B`.
You need to delete all these combinations and you to correctly generate them.
I have to close this ticket because, in the combination list, every combination needs to have the same attributes than the others.
Thanks, feel free to open a new one when needed.

**Closed as completed by khouloudbelguith** 2019-02-08 13:33 UTC
Labels: Combinations, No change required

**Comment by ghost** [comment] 2019-02-08 14:27
> You need to delete all these combinations and you to correctly generate them.

How? I already stated that logically Color A can't be conncted with Color B. Now if I would like to make connections like this:
Color B <-> FeatureList, Color A <-> FeatureList
I won't be able to do it because Color A will not appear at all.

I honestly disagree that this is normal, you can add combinations consisting of just one attribute just like that, the fact that it shows all colors on the hover indicates something is not right!

**Comment by khouloudbelguith** [comment] 2019-02-08 14:34
ping @marionf what do you think?
In my opinion, the generation of those combinations is not valid.
Thanks!

**Comment by marionf** [comment] 2019-02-14 14:39
Yes, it's not a bug, you should select all colors from Test Colors A AND Test Colors B and click on generate

**Comment by ghost** [comment] 2019-02-14 14:43
Well then, you should consider at least a notification while adding single attribute to the combination list when there are already existing combinations there to prevent confusion, plus prevent/fix the visual bug from the screenshots.

I made workaround module for my use case.
