### ISSUE TITLE
Error during database upgrade with decimal columns

### ISSUE THREAD

**Issue by vincenttouzet** [PrestaShop/PrestaShop#18089] opened 2020-03-11 11:15 UTC
#### Describe the bug

An error occured during database upgrade from Prestashop 1.7.6.2 to 1.7.6.4. The error is located in `src/PrestaShopBundle/Command/UpdateSchemaCommand.php`.

The command retrieve the SQL queries to execute and put back the default fields (https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Command/UpdateSchemaCommand.php#L151)

In our case the sql generated by the Doctrine SchemaTool is :

```
ALTER TABLE ps_configurator_product_config_option_price_rule CHANGE price price DECIMAL(20, 6) DEFAULT NULL
```

And the code replace the sql with :
```
ALTER TABLE ps_configurator_product_config_option_price_rule CHANGE price price DECIMAL(20 DEFAULT NULL , 6) DEFAULT NULL
```

I think the problem is here : https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Command/UpdateSchemaCommand.php#L157
The preg_match stop at the first comma found. Therefore this could impact ALL SQL queries containing NUMERIC or DECIMAL fields.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.25

**Comment by khouloudbelguith** [comment] 2020-03-11 11:27
Hi @vincenttouzet,

Thanks for your report.
What is the exact version of the 1-click upgrade module did you use?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by vincenttouzet** [comment] 2020-03-11 13:28
Hi @khouloudbelguith ,

We're using the version 4.10.1 of the autoupgrade module and launch the migration with : 
```
modules/autoupgrade/cli-upgrade.php --dir=admin711ii4noq --action=upgradeDb --channel=minor
```
and the log file is not created.

We launched the migration from the module page on Admin but the error is triggered on our review environment.

**Comment by khouloudbelguith** [comment] 2020-03-11 14:14
@vincenttouzet, When I tried with this command line

`modules/autoupgrade/cli-upgrade.php --dir=admin-dev --action upgradeDb --channel=minor`
I have this error
```
modules/autoupgrade/cli-upgrade.php: ligne 1: ?php: Aucun fichier ou dossier de ce type
modules/autoupgrade/cli-upgrade.php: ligne 3: /2019-09-24-16-imgPrestashop : est un dossier
modules/autoupgrade/cli-upgrade.php: ligne 4: admin-dev : commande introuvable
modules/autoupgrade/cli-upgrade.php: ligne 5: admin-dev : commande introuvable
modules/autoupgrade/cli-upgrade.php: ligne 6: admin-dev : commande introuvable
modules/autoupgrade/cli-upgrade.php: ligne 7: admin-dev : commande introuvable
modules/autoupgrade/cli-upgrade.php: ligne 8: erreur de syntaxe près du symbole inattendu « ( »
modules/autoupgrade/cli-upgrade.php: ligne 8: ` * This source file is subject to the Open Software License (OSL 3.0)'
```

>We launched the migration from the module page on Admin but the error is triggered on our review environment.

there is a log file after launching the migration from the configuration page?

Thanks!

**Comment by sarahdib** [comment] 2020-04-14 11:51
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed** 2020-04-14 13:48 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.6.2, 1.7.6.4

**Comment by rblaurin** [comment] 2021-03-04 04:08
I can confirm this issue when upgrading to 1.7.7.2 if you have a module using doctrine/annotations and a table with  numeric field. If you ping the core team they can confirm there is a problem with the regex pointed by @vincenttouzet.
