### ISSUE TITLE
Category tree not populated in the product creation page 1.7.6.3

### ISSUE THREAD

**Issue by Sathish-i2i** [PrestaShop/PrestaShop#17460] opened 2020-01-31 11:00 UTC
I have enabled the multistore and created the three stores. Initially all the category tree showing while creating product page.

Now its not showing the category tree
![Category-tree-not-showing](https://user-images.githubusercontent.com/15522416/73534345-e9416d00-4446-11ea-8591-730eaef1695d.png)

**Comment by khouloudbelguith** [comment] 2020-01-31 11:28
Hi @Sathish-i2i,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1Vyron9ZHkG_k7EphK1MtjgyYJp7eZ9b0/view
Thanks to check & feedback.

**Comment by Sathish-i2i** [comment] 2020-01-31 12:44
Thanks for the response.

Can you suggest any workaround for this issue?

**Comment by khouloudbelguith** [comment] 2020-01-31 12:48
@Sathish-i2i, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-02 08:16
Hi @Sathish-i2i,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-02 08:16 UTC
Labels: Bug, BO, Categories, Multistore, No change required, 1.7.6.3
