### ISSUE TITLE
Installation Error in Persian (Farsi) Language.

### ISSUE THREAD

**Issue by AliShareei** [PrestaShop/PrestaShop#22657] opened 2021-01-04 14:59 UTC
#### Describe the bug

On the installation process (PrestaShop v1.7.7.0) in Persian (Farsi) language, one error happened about carrier->delay is empty and installation with demo data can't be succeeded

I created a PR for this #22564

#### Expected behavior

Nobody can install PrestaShop in version 1.7.7.0.  
unless disabling demo data -OR- install in English and after that add the Persian Language from admin.
#### Steps to Reproduce

1. Go to the installation
2. change the language to Persian (Farsi)
3. Go to the installation steps.
4. See an error

**Screenshots**

<img width="960" alt="image_2020-12-24_13-47-09" src="https://user-images.githubusercontent.com/9982451/103082647-d2bc7b00-45ef-11eb-8090-5d732484a541.png">

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: I don't remember but I believe 7.1

**Comment by LouiseBonnard** [comment] 2021-01-04 15:29
Thank you very much, @AliShareei, it will be taken into account very soon! @hibatallahAouadni, could you please try with another RTL language when you will reproduce it? I just want to make sure this bug only happens for the Farsi language, thanks a lot! 

cf. https://github.com/PrestaShop/PrestaShop/pull/22564#issuecomment-754003769

> Noted, thanks @AliShareei! Would you mind creating an issue reporting this bug and link your pull request to it? It'd be great as it'd allow us to reproduce and prioritize it. I would like to know if this is a regression (and therefore for which version it should be fixed) and if it also happens in the context of another RTL language.

**Comment by hibatallahAouadni** [comment] 2021-01-04 16:02
Hello @LouiseBonnard 

I didn't encounter any issue while installing PS with arabic language, see the screen record below:

https://drive.google.com/file/d/1DyI3J3REwRx2k4QDx5ibWvg9aVlhv4qc/view

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-04 16:12
Hello @AliShareei 

I reproduced your issue with PS1.7.7.0 and Persian language, see the attached screen record below:

https://drive.google.com/file/d/1fgv1Lq47OKiLAUN7ILDShuxuPnjrvg5d/view

Thanks for your issue and your PR :rocket: 

---
PS: it's not a regression cause I reproduced another issue with PS1.7.6.8 and persian language

![image](https://user-images.githubusercontent.com/23308427/103555525-b56d9380-4eb0-11eb-8386-d97b8a552ae5.png)

**Comment by AliShareei** [comment] 2021-01-04 16:50
Hello @hibatallahAouadni,
It's true. that I was defeated by a few other errors.
I experienced other errors in Firefox.
I did not check them carefully because I did not have enough time, but there seemed to be no problem (or less problem) with Chrome.
The error I encountered seemed to be related to a JavaScript error and an Ajax request.
The firefox has more problems with PrestaShop.

**Comment by LouiseBonnard** [comment] 2021-01-04 16:52
Great, thank you very much for this information, @hibatallahAouadni! I milestoned this bug to have it fixed for the next minor version. :-)

**Comment by AliShareei** [comment] 2021-01-04 16:54
dear @LouiseBonnard,
milestone v1.7.8.0 is not good for this problem!
I hope this problem (at least my PR) fixed in the next patch release. (not minor)
It's a big deal that users can't install PrestaShop.

**Comment by matks** [comment] 2021-01-05 10:41
Hi @AliShareei @LouiseBonnard I dont know why but Persian is the only language that has hardcoded fixtures in its install fixtures folder (see https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/fixtures/fashion/langs/fa/data). 😮 

Rather than fixing this data, which should not be there, I submitted a PR that remove it https://github.com/PrestaShop/PrestaShop/pull/22674 and it seems to solve the bug. Moreover it helps to make sure Persian language is processed similarly to other languages available at install step.

**Comment by AliShareei** [comment] 2021-01-06 07:24
Hi @matks,
I think removing that data is not a good idea. because of some reason which I told in your removing PR.
Please read this.
https://github.com/PrestaShop/PrestaShop/pull/22674#issuecomment-755131825

**Comment by matks** [comment] 2021-01-06 16:00
@marionf PR https://github.com/PrestaShop/PrestaShop/pull/22564 targets `develop`. Should it target `1.7.7.x` branch instead?

**Comment by marionf** [comment] 2021-01-06 16:27
@matks yes, this issue doesn't seems to be a regression but it prevents to install PS in Farsi, that's quiet annoying and I think we should fix it as soon as possible in a patch version

**Comment by Progi1984** [comment] 2021-01-12 10:37
Fixed by #22735.

**Closed as completed by Progi1984** 2021-01-12 10:37 UTC
Labels: Bug, Major, IN, Fixed, PR available, 1.7.7.0
