### ISSUE TITLE
[1.7.7] Order BO discount removing/changing not working properly

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19960] opened 2020-06-26 13:08 UTC
Removing discounts or changing product quantity is not working.

#### Video
https://drive.google.com/file/d/1e2-2veDRzWT45niwQJLlwOpc7waDWF5Y/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-06-26 13:55
Hi @Hlavtox ,
Thanks for the report.
I did manage to reproduce the issue in PS 1.7.7.0 in multiple installations.
My screen record here : https://drive.google.com/file/d/1z93DIVnp-jntdF48ZVoKCg64-H-h_pmh/view

In an order with multiple products and multiple quantities, and status not considered as accepted yet, the steps to reproduce are :
- go to order
- add a discount
- change quantity of one of the product
- delete another product
- delete the discount
- error shows like this :
![Capture d’écran 2020-06-26 à 15 53 00](https://user-images.githubusercontent.com/16019289/85864876-60481b00-b7c5-11ea-88c6-a0ec44bfdd35.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by jolelievre** [comment] 2020-06-26 14:33
Hi @Hlavtox,

thanks for spotting this bug, did you try on the beta release or on the 1.7.7.x branch?

I believe this issue is a duplicate of one/some of the issues in this Epic https://github.com/PrestaShop/PrestaShop/issues/19594

Most of the bugs have been fixed in the branch, the rest is being fixed at the moment.

By the way thank you for the video it helps a lot to understand the bug. I don't want to abuse but if you provide other videos in the future do you think it would be possible to record them with english language, it will probably help us understand more easily (except for bugs related to a specific language of course). Thanks in advance 😉

**Comment by Hlavtox** [comment] 2020-06-26 14:45
@jolelievre I am trying on a beta release, not on the latest code.

No prob bro, I will switch it next time 😎

**Comment by colinegin** [comment] 2020-06-29 08:21
I put this issue in to be tested so that we can check if the issue remains on the latest version of the code.
FYI @PrestaShop/prestashop-qa

**Comment by Robin-Fischer-PS** [comment] 2020-06-29 12:36
Hi,

When trying to reproduce the bug with the latest version of 1.7.7.x branch, I have the following behavior : As soon as I change the product quantity, or if I delete a product, the discount on the order is deleted.

See my screenrecord here : 
https://drive.google.com/file/d/1pfAzhoBRQgXEJjDn5V1FLffKc5zPQQZu/view?usp=sharing

Is this the expected behavior ? @jolelievre @colinegin 

Thanks

**Comment by jolelievre** [comment] 2020-06-29 14:56
Nope, I don't think so

**Comment by Hlavtox** [comment] 2020-06-29 15:02
@Robin-Fischer-PS @jolelievre Depends if the original cart rule exists or not. If it is already deleted, Prestashop has no chance knowing what the original logic was.

I think a good solution would be just to delete all discounts from the order when changing anything in it. Most of the time, the merchant changes the order to apply some custom-dealt prices or discounts by phone or text, so the discounts are changed anyway. And you would save yourself from a lot of 💩. :-)

**Comment by jolelievre** [comment] 2020-06-29 17:43
@Hlavtox I agree with you when the discount is removed it cannot come back after update
But in this case it has just been created specifically for the Order, and no one as deleted it, it should still be present after a product quantity update

**Comment by matks** [comment] 2020-07-20 14:01
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20083

**Closed as completed by matks** 2020-07-20 14:01 UTC
Labels: Bug, Minor, BO, Order, Discounts, Regression, Fixed, PR available, 1.7.7.0
