### ISSUE TITLE
PS 1.7.6.1 can't save products under Price tab

### ISSUE THREAD

**Issue by Fixmetal** [PrestaShop/PrestaShop#16038] opened 2019-10-21 09:47 UTC
**Describe the bug**
Since 1.7.6.0 I can't save prices anymore using the proper tab in BO

**To Reproduce**
1. Go to BO->Catalogue
2. Select any product
3. Click on "Prices" tab
4. Try to update Cost Price
5. Green tab is displayed saying it's been updated but it's not. A refresh will show up old price. Database is not updated

Only hint I got is that Chrome Dev Tools shows this entry when clicking on any product:
GET https://mydomain.org/ps/XXXXXXXXXXXXXXXX/themes/new-theme/public/index.php?controller=AdminDashboard&token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX net::ERR_ABORTED 404

I just wonder what this "new-theme" is. I don't have any in the FTP and I can't find any references in the DB.

I've updated to 1.7.6.1 thinking of a fixed bug but it's still here.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-21 09:53
Hi @Fixmetal,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1fWTOyFswDv7TOJkfma7DaszwI-jRCInk/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Fixmetal** [comment] 2019-10-21 22:03
Ok fine, I've got all the infos you asked.
May I share them privately with you?

**Comment by khouloudbelguith** [comment] 2019-10-22 09:20
@Fixmetal,
This is a public space.
You can provide me the Infos by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by Fixmetal** [comment] 2019-10-23 10:02
Thanks @khouloudbelguith , that's what I meant.
You should have a Dropbox invitation in your mailbox.
Thanks

**Comment by khouloudbelguith** [comment] 2019-10-23 12:54
@Fixmetal, I couldn't find errors in your file `access.log`.

You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. Update the cost price
5. save the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by fabio-zetaweb** [comment] 2019-11-20 10:35
Hello, 

I have the same issue (@Fixmetal) using v1.7.6.1.

1 - no error from GET request
8 - no error in response (status code 200) and wholestate_price field is filled

**Here are my server data**
server software: nginx/1.14.0
PHP v: 7.1.22
memory limit: 512M
max execution time: 300
max filesize to upload: 256M

Could I contact you in private?

**Comment by khouloudbelguith** [comment] 2019-11-20 10:47
@fabio-zetaweb, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.1 using an Nginx server.
https://drive.google.com/file/d/1IVsYmsP0P4a-wVkdrWN0WRqy5PQcwI8v/view
What is the exact type of product? if it a standard product, is it simple or with combinations?

Thanks!

**Comment by fabio-zetaweb** [comment] 2019-11-20 11:17
Hello,

only a few product are affected, those signaled from my customer are all simple product.

**Comment by khouloudbelguith** [comment] 2019-11-20 11:21
@Fixmetal, I found the exact issue.
The cost price reset to 0 if you activate/deactivate or duplicate products in the BO product list.
If you save a new cost price, then reopen product is always 0
Behavior only on duplicated products.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10792
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-20 11:21
Duplicate of #10792

**Closed as completed by khouloudbelguith** 2019-11-20 11:21 UTC
Labels: Bug, BO, Duplicate, Taxes and Prices, 1.7.6.1

**Comment by fabio-zetaweb** [comment] 2019-11-20 13:54
hi,

I did not manage to reproduce the issue duplicating another product. Cost price remains as it was and if i change the value it saves changes regularly.

**Comment by khouloudbelguith** [comment] 2019-11-20 16:13
@fabio-zetaweb, yes, you are right, it is fixed with PS1.7.6.1 but, we have a regression reported here:  https://github.com/PrestaShop/PrestaShop/issues/16353
so, in your case, it is related to the supplier price cost which is 0.


Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-20 16:14
Duplicate of #16353

**Comment by Hsalehm** [comment] 2021-09-05 16:51
I have a problem with this variable, cost price, and it is that I cannot find where in the database it is hosted, I have a lot of experience doing SQL queries and when I examine the product table (ps_product in my case) there is a variable (column) called wholesale_price, this variable appears at zero in SQL queries, however, when I query the product in BO (ps 1.7.7.3) I find that it is written, but when I generate SQL query it returns to zero (only some products). Does anyone know what could this be? Thanks in advance
