### ISSUE TITLE
Letters are allowed where only numbers should be allowes (Specials block module)

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28663] opened 2022-06-02 12:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the module "Specials block" there is only 1 input "Products to display", has a help text: " Define the number of products to be displayed in this block on home page. ". Entering random letters, symbols or anything like that saves as if it was a number, shows  a success message: " The settings have been updated. ". 

![image](https://user-images.githubusercontent.com/75423142/171628339-39ba490c-07bb-4e9f-86b1-360a697c81a1.png)

### Expected behavior

Should allow only numbers, any other symbols or letters should result to an error.

### Steps to reproduce

1. Install module "Specials block"
2. Go to configure it.
3. Enter random letters/symbols to the " Products to display " field.
4. Press "save".

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

ps_specials v1.0.1

**Comment by hibatallahAouadni** [comment] 2022-06-02 16:47
Hello @Saimis777 

I reproduce the issue with PS1767 and PS1786, I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2023-01-18 09:59 UTC
Labels: Bug, Minor, BO, ps_specials, 1.7.6.7, Verified, Module
