### ISSUE TITLE
Can't install prestashop before version 1.7.3.3 because of addons modules error 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#33293] opened 2023-07-18 14:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to install prestashop v1.7.2.4/ v 1.7.3.0 / v 1.7.3.3 I get an error 500 when the installations is on the addons modules, as you can see : 

[Untitled_ Jul 18, 2023 4_12 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a5adf2ab-d3a2-408f-9147-62afd6f59131)

For informations i'm on linux, with phpmyadmin

### Expected behavior

I expected that I can fully install my shop 

### Steps to reproduce

1. Start the installation of your prestashop 
2. Set up your name, the name of your shop
3. Set up your database 
4. Launch the installation  :heavy_multiplication_x: error 

### PrestaShop version(s) where the bug happened

v1.7.2.4/ v 1.7.3.0 / v 1.7.3.3 and before 

### PHP version(s) where the bug happened

7.4.33

**Comment by hibatallahAouadni** [comment] 2023-07-18 16:27
Hello @AureRita 

Your issue is duplicate to #32444, please check and feedback.

Thanks!

**Comment by leemyongpakvn** [comment] 2023-07-19 11:27
I used to pass this issue by logging-in to https://addons.prestashop.com prior starting PS installation process ;)

**Comment by MatShir** [comment] 2023-07-20 08:59
Those versions are not supported anymore. I'm closing this issue.
Thanks @AureRita

**Closed as completed by MatShir** 2023-07-20 08:59 UTC
Labels: Bug, IN, Duplicate, 1.7.2.4, Invalid

**Comment by hibatallahAouadni** [comment] 2023-08-02 10:13
Duplicate of #32444
