### ISSUE TITLE
Manual upgrade tool does not show fatal errors

### ISSUE THREAD

**Issue by dmg-leusden** [PrestaShop/PrestaShop#29482] opened 2022-08-30 17:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I ran php install/upgrade/upgrade.php.

A blank line was inserted, and then the command prompt showed again, with no xml for sql executed.
Turns out a fatal error occured, but wasn't showing. It's very impractical to use the CLI tool and not see any fatal errors.

The fatal error that I had was (unrelated to this ticket, after examining the system php error log):

[30-Aug-2022 17:26:21 Europe/Paris] PHP Fatal error:  Uncaught PrestaShopObjectNotFoundException: The hook id #1 does not exist in database in <removed>/classes/Hook.php:242

and then something about module "bankwire", which is a module that needed to be unistalled.

### Expected behavior

While running the manual upgrade tool (install/upgrade/upgrade.php) no fatal errors are shown (at least for exceptions in CLI mode). I'm using the CLI tool, obviously I want to see it when a fatal error occurs and there is no upgrade output.

```
$ php install/upgrade/upgrade.php
[30-Aug-2022 17:26:21 Europe/Paris] PHP Fatal error:  Uncaught PrestaShopObjectNotFoundException: [...]
```

### Steps to reproduce

Not applicable

### PrestaShop version(s) where the bug happened

manual upgrade from 1.7.7.5 to 1.7.8.6

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment] 2022-08-31 15:37
Hi @dmg-leusden, 

Thank for your report. I tried to reproduce your issue and I've only a great exception that looks like that : 
![image](https://user-images.githubusercontent.com/100699445/187719643-9703b94e-124d-4cc1-b594-de5506b0e306.png)

is this your issue ? 
If not, could you write the entire steps to reproduce to allow the QA team to reproduce your issue ? 

Waiting for your feedback

**Comment by sallemiines** [comment] 2022-09-20 09:32
Hello @dmg-leusden,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you !

**Closed as completed by sallemiines** 2022-09-20 09:32 UTC
Labels: Bug, IN, 1.7.7.5, Invalid
