### ISSUE TITLE
Unexpected 'your address is incomplete'-error rendered in FO

### ISSUE THREAD

**Issue by HunkBenny** [PrestaShop/PrestaShop#30988] opened 2023-01-20 21:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi all,

Due to a bug in the standard template, an error message is rendered in the HTML during the selection of the address in the checkoutprocess. The style is set to 'hidden', so people can not see it. However, when the owner of the e-commerce store adds custom CSS, it can suddenly appear. I believe it can simply be removed in line 70, correct me if I'm wrong :)

https://github.com/PrestaShop/PrestaShop/blob/e664e3d4cd5d59695d207ec186296a1857297da4/themes/classic/templates/checkout/_partials/steps/addresses.tpl#L67-L71

Screenshot that shows the behaviour:
![image](https://user-images.githubusercontent.com/80793807/213807590-0f6df741-b786-49b3-8544-36467616ecb3.png)

(Of course, I tested it for different addresses also)

### Expected behavior

No error, due to a valid address.

### Steps to reproduce

1. Create a fresh PS install.
2. Choose a product and start the checkout-process.
3. Create an address and look in the HTML.

### PrestaShop version(s) where the bug happened

1.7

**Comment by sallemiines** [comment] 2023-01-24 13:19
Hello @HunkBenny 

Thanx for reporting the issue.

I don't think that your issue could be a Bug or a core issue ! it's the normal code behavior of HTML , as you can see the status of  the alert is **display : none**  when you try to set the status of the alert to **display : yes** than an error message appears in the shop ! 
you can check the attached screen record bellow 

https://user-images.githubusercontent.com/31663369/214304414-6b15da6f-8137-4d04-a505-2a614d1d3cc6.mp4

Thank you !

**Comment by hibatallahAouadni** [comment] 2023-01-24 13:23
Hello @HunkBenny 

As @sallemiines mentionned above this is not a bug, this is the wanted behavior.
Closing the issue as it's not a bug.

Thanks for your understanding :pray:

**Closed as completed by hibatallahAouadni** 2023-01-24 13:23 UTC
Labels: Bug, Invalid

**Comment by HunkBenny** [comment] 2023-01-24 21:46
Thanks for your answers! :)

I know that it is not shown in the HTML due to the element-style. However, if there is no error, why would it still be present in the HTML? It seems confusing for users who customize the default template with their own CSS.

Also, it is inconsistent with how other error-alerts are being shown. For example:
https://github.com/PrestaShop/PrestaShop/blob/e664e3d4cd5d59695d207ec186296a1857297da4/themes/classic/templates/_partials/form-errors.tpl#L25-L35
Here, errors are only added to the HTML if they are present.

P.S. (added 16/01/2024):
![image](https://github.com/PrestaShop/PrestaShop/assets/80793807/78a030aa-ac13-4f95-aecd-e30fcc7a252a)
