### ISSUE TITLE
Friendly url not working for Attachments when multi lang used

### ISSUE THREAD

**Issue by Bellaco1** [PrestaShop/PrestaShop#25640] opened 2021-08-18 14:19 UTC
#### Describe the bug

Friendly url not working for products attachments when multi lang used on Ubuntu and Nginx setup  
 you get 404 Not Found https://shop.bellaco.se/en/index.php?controller=attachment&id_attachment=52
but when you take away /en/ it work's

#### Expected behavior

expected to download or show products attachments directly now somthing wrong when use multi lang 

#### Steps to Reproduce

1. Go to 'https://shop.bellaco.se/en/router/55-rg-ap180.html'
2. Click on 'Attachments try to open and you get error'

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

It works when not use multilang 

* PrestaShop version: 
 1.7.7.6

* PHP version: 
PHP 7.2.34-21+ubuntu20.04.1+deb.sury.org+1 (cli) (built: May  1 2021 11:53:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.34-21+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by hibatallahAouadni** [comment] 2021-08-19 10:18
Hello @Bellaco1 

Could you please check this issue #15936 seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Bellaco1** [comment] 2021-08-22 09:49
Hi No this don't feel like similar problem, I just looking for be able to use same Attachments for every language. I see a lot of diffrent solutions to use diffrent lang on attachments. Any one that can point me in right direction for just get rid of lang for attachments?

**Comment by florine2623** [comment] 2021-08-24 09:52
Hello @Bellaco1 ,

I can't reproduce your issue using PS 1.7.7.6 and PHP 7.2.
Please check my screen record : https://drive.google.com/file/d/13Vq_yUys_9L_VFt4k7KLHxUDg8LMiLP5/view

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-13 13:04
Hello @Bellaco1 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-13 13:04 UTC
Labels: Bug, FO, Languages, No change required

**Comment by Bellaco1** [comment] 2021-09-13 19:31
Sorry for my late respons, but been busy fammily things. Need to ask what OS and Webserver do you run this on?  My installation in not new is updated 2 times from 1.7.1 to  PS 1.7.7.6 and PHP 7.2.   and I run this on Nginx. Maybe I need to run on Apache to get this working. but should not be the problem. please give webserver and vertion you run this on and get it working.

**Comment by Bellaco1** [comment] 2021-09-14 22:27
Hi this is the same problem we have 
https://www.prestashop.com/forums/topic/1019348-problem-with-attachment-file-in-multilanguage/

any one have solution?

**Comment by Bellaco1** [comment] 2021-09-14 22:29
Hi sorry for my late respons, possible to open agian

my father got sik and did't get time to look

I have made some new comment
