### ISSUE TITLE
Problem with importing product using example csv file

### ISSUE THREAD

**Issue by avatec** [PrestaShop/PrestaShop#12789] opened 2019-03-04 22:50 UTC
**Describe the bug**
Trying to import product using css example file.

**To Reproduce**
1. Go to config > advanced > import 
2. Download example product csv file
3. Try to upload it

**Additionnal information**
PrestaShop version: 1.7.5.1

Repair - missing fields: after weight 2 fields:
- Delivery time of products available in the warehouse
- The product delivery time is out of date with the option of booking

and after low stock level:
Send me an e-mail when the quantity is below this level

After adding those 3 fields, import works successfully, so it should be repaired.

**Comment by khouloudbelguith** [comment] 2019-03-05 07:43
Hi @avatec,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9764
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-05 07:43
Duplicate of #9764

**Closed as completed by khouloudbelguith** 2019-03-05 07:43 UTC
Labels: Duplicate
