### ISSUE TITLE
Impossible to change product position in category (reorder)

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#21648] opened 2020-10-28 13:21 UTC
Hello,

It's currently (in the last versions) impossible to change products positions (in a category) to manually choose the product sort order.

1. Go to Catalog > Products in the Backoffice
2. Filter your products by a specific category
3. Click on the "Reorder" button to reorder products position in the category
4. Change the position of some products
5. Click on the "Save & Refresh" button

Nothing is happening 😔 And position is not saved.

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.25

**Comment by hibatallahAouadni** [comment] 2020-10-28 13:33
Hi @Daaaaad 

The problem is fixed if we use the icon in the position column in the next release PS1770.
We are aware of this issue. Your ticket is a duplicate of #15291
So, I close it.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-10-28 13:34
Duplicate of #15291

**Closed as completed by hibatallahAouadni** 2020-10-28 13:33 UTC
Labels: Duplicate

**Comment by Daaaaad** [comment] 2020-10-29 06:55
> Hi @Daaaaad
> 
> The problem is fixed if we use the icon in the position column in the next release PS1770.
> We are aware of this issue. Your ticket is a duplicate of #15291
> So, I close it.
> 
> Thanks!

Hello @khouloudbelguith, why did you remove the PR information?

How to fix it in 1.7.6?

Regards,

David.

**Comment by khouloudbelguith** [comment] 2020-11-03 14:42
Hi @Daaaaad,

Here's the PR #14879.

Thank you!
