### ISSUE TITLE
Remove From Cart button isn't working with Friendly URLs turned on

### ISSUE THREAD

**Issue by Crolug** [PrestaShop/PrestaShop#12520] opened 2019-02-09 01:20 UTC
Remove Form Cart button stops to work after turning on Friendly URLs in PrestaShop 1.7.5.

**Steps to reproduce the behavior**:
1. Go to Shop Parameters -> Traffic & SEO
2. Turn on Friendly URL
3. Add a product to a cart and go to a cart page
4. Click remove from cart button (on default theme -> trash bin icon)

**Additional information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.12

**Comment by khouloudbelguith** [comment] 2019-02-11 08:16
Hi @Crolug,


I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1M9sAK6ee-7i5foz5KJALfwJswB6z8fC2/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-13 09:41
Hi @Crolug,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-13 09:41 UTC
Labels: Bug, FO, Blockcart, No change required, 1.7.5.0

**Comment by Juiliard** [comment] 2020-09-12 23:12
I do not see step with delete button: ( this is the link from your video /index.php?controller=cart&actions=show  )
where should I go to activate visibility of this page?

**Comment by khouloudbelguith** [comment] 2020-09-14 09:01
Hi @Juiliard,

This issue is currently closed, can you open a new one with more information about your configuration.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
