### ISSUE TITLE
Carrier tracking number missing in "in_transit" email with webservice

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#20596] opened 2020-08-14 12:29 UTC
#### Describe the bug

When the carrier tracking number is updated on orders by webservice, the "in_transit" email is sent but the link {follow} includes the carrier url without the tracking number.

When it is updated manually in the admin, the url is complete with the tracking number.

#### Steps to Reproduce

1. Create an order.
2. Insert the tracking number to the order using webservice.
3. You will receive the "in_transit" email with the link to track the order.
4. The url is correct with the link setup with the carrier but the @ has been replaced by nothing and the tracking number is missing.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2.33

**Comment by khouloudbelguith** [comment] 2020-08-14 13:55
Hi @ced--ced,

Thanks for your report.
I tried to update the order status and the tracking using WS, but I didn't receive any `Package in transit` mail as reported here: https://github.com/PrestaShop/PrestaShop/issues/13912
I used this script
```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 14/08/20
 * Time: 14:35
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://prestashop.local/shop');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'http://prestashop.local/shop',
    'Key',
    false);
$id = 15; //ID order Here
$xml = $ws->get(array('resource' => 'orders', 'id' => $id));

echo "BEFORE\n";
print_r($xml->asXML());

unset($xml->order->current_state);

$xml->order->current_state = 4; // status = shipped
$xml->order->shipping_number = 22; //tracking number

$opt = array(
    'putXml' => $xml->asXML(),
    'id' => $id,
    'resource' => 'orders',
);
$xml = $ws->edit($opt);

$xml = $ws->get(array('resource' => 'orders', 'id' => $id));

echo "AFTER\n";
print_r($xml->asXML());
```
I well received the `Shipped` mail.

I'm blocked by this [issue](https://github.com/PrestaShop/PrestaShop/issues/13912) I cannot reproduce your issue.
Thanks to check and feedback.

**Comment by ced--ced** [comment] 2020-08-17 10:45
Hi @khouloudbelguith,

The email is sent when the tracking number is updated, not when the order status is changed.

Thanks

**Comment by khouloudbelguith** [comment] 2020-08-17 10:47
@ced--ced,

Yes, I'm trying to update the tracking number via WS.
`$xml->order->shipping_number = 22; //tracking number`

But there is no email sent.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-07 08:29
Hi @ced--ced,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-09-07 08:29 UTC
Labels: Bug, WS, Order, Email, Webservice, No change required, 1.7.6.1

**Comment by ramwebkul** [comment] 2022-05-31 06:23
@ced--ced @khouloudbelguith 
It is a bit late to come back on this issue but I have found a workaround that works for me for now.
The reason of this issue is that the webservice calls setWsCurrentState before setWsShippingNumber, that is why the shipping number is not found when seding email for PS_OS_SHIPPING status.

To solve this: In classes/Order.php, we need to reorder the webserviceParameters so that the shipping number is updated before updating status.
So now, the re-ordered webserviceParameters look like this:

    protected $webserviceParameters = [
        'objectMethods' => ['add' => 'addWs'],
        'objectNodeName' => 'order',
        'objectsNodeName' => 'orders',
        'fields' => [
            'id_address_delivery' => ['xlink_resource' => 'addresses'],
            'id_address_invoice' => ['xlink_resource' => 'addresses'],
            'id_cart' => ['xlink_resource' => 'carts'],
            'id_currency' => ['xlink_resource' => 'currencies'],
            'id_lang' => ['xlink_resource' => 'languages'],
            'id_customer' => ['xlink_resource' => 'customers'],
            'id_carrier' => ['xlink_resource' => 'carriers'],
            // shipping_number moved above current_state
            'shipping_number' => [
                'getter' => 'getWsShippingNumber',
                'setter' => 'setWsShippingNumber',
            ],
            'current_state' => [
                'xlink_resource' => 'order_states',
                'setter' => 'setWsCurrentState',
            ],
            'module' => ['required' => true],
            'invoice_number' => [],
            'invoice_date' => [],
            'delivery_number' => [],
            'delivery_date' => [],
            'valid' => [],
            'date_add' => [],
            'date_upd' => [],
            'note' => [],
        ],
        'associations' => [
            'order_rows' => ['resource' => 'order_row', 'setter' => false, 'virtual_entity' => true,
                'fields' => [
                    'id' => [],
                    'product_id' => ['required' => true, 'xlink_resource' => 'products'],
                    'product_attribute_id' => ['required' => true],
                    'product_quantity' => ['required' => true],
                    'product_name' => ['setter' => false],
                    'product_reference' => ['setter' => false],
                    'product_ean13' => ['setter' => false],
                    'product_isbn' => ['setter' => false],
                    'product_upc' => ['setter' => false],
                    'product_price' => ['setter' => false],
                    'id_customization' => ['required' => false, 'xlink_resource' => 'customizations'],
                    'unit_price_tax_incl' => ['setter' => false],
                    'unit_price_tax_excl' => ['setter' => false],
                ], ],
        ],
    ];
