### ISSUE TITLE
Can't translate with tags in BO

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#22512] opened 2020-12-21 08:20 UTC
#### Describe the bug

Hello,

I have a problem with translation

I used that in tpl file : 
`<p>{l s=" Un rideau [1]Thermique[/1] dans les pièces mal isolées pour une protection contre le froid en hiver et la chaleur en été." tags=['<span>'] d='Shop.Theme.Catalog'}</p>`

But when I go to the back office to translate this, it doesn't take into account the tag I put.  Moreover, in the display I see the tags

You can see my screenshot

Thanks

**Screenshots**

![Sans-traduire](https://user-images.githubusercontent.com/25744417/102754547-70ecde80-436d-11eb-9eb5-f33738b39604.JPG)
![avec-traduction-bo](https://user-images.githubusercontent.com/25744417/102754564-76e2bf80-436d-11eb-8936-66528616784b.JPG)
![avec-traduction](https://user-images.githubusercontent.com/25744417/102754576-7a764680-436d-11eb-8285-ba244ea34d6b.JPG)

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 5.6

**Comment by hibatallahAouadni** [comment] 2020-12-21 14:57
Hello @ShaimyWinda 

I managed to reproduce your issue with **PS1.7.6.1** and **PS1.7.6.4**, see the attached screen record below:

https://drive.google.com/file/d/1dZmOykTMiHakUCXr6e1zEWeFKfWU-LlW/view

But, with **PS1.7.6.7**, **PS1.7.6.9** and **PS1.7.7.0**, I got this error: 

![image](https://user-images.githubusercontent.com/23308427/102789850-f770e280-43a4-11eb-848d-9f5ba128f30c.png)

It seems the tags attribute is not supported anymore :confused: 
Ping @PrestaShop/prestashop-core-developers have you any idea about this issue?

Thanks!

**Comment by ShaimyWinda** [comment] 2020-12-24 09:04
Hi, do you have a solution ?

Thanks

**Comment by PierreRambaud** [comment] 2021-01-20 16:02
@hibatallahAouadni As you said, `tags` is not used anymore and `sprintf` has to be used. So you need to use `sprintf`

**Comment by hibatallahAouadni** [comment] 2021-02-09 09:41
Hello @ShaimyWinda ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-09 09:41 UTC
Labels: Bug, FO, Translations, No change required, 1.7.7.0, 1.7.6.9
