### ISSUE TITLE
Accented email in username part when user create account with old browser or JS disabled

### ISSUE THREAD

**Issue by psyray** [PrestaShop/PrestaShop#17126] opened 2020-01-12 21:35 UTC
**Problem**
When a customer create an account, he can't validate an accented email.
But this validation is made only using client side HTML email form type.

If a customer use an old browser like IE 6 to 9 (check [caniuse capture below](https://caniuse.com/#search=email)), the validation will not take place and the accented email will be saved to db and the user account is created, which is very bad because user will never receive email from shop.

![image](https://user-images.githubusercontent.com/1230954/72225810-ff67b600-3589-11ea-9c1c-7aae1b14a851.png)

**Steps to reproduce the behavior:**
1. Go to customer creation page with an old browser (or change input type from email to text with browser inspector)
2. Validate
3. Account is created, but the user never receive any email because it is invalid

**Expected behaviour**
Email should be saved without accented characters

**To resolve the problem**
A server validation must take place to verify email.

Two choices :
- Silently replace accent using [this kind of code](https://stackoverflow.com/questions/3371697/replacing-accented-characters-php)
- Prevent account creation and warn user to modify bad email

**Additional information**
Prestashop version: 1.7.5.2
PHP version: 7.2

**Comment by jf-viguier** [comment] 2020-01-13 17:48
IE 6 to 9 is not supported by Prestashop, too old.
I think that accentuated email addresses are now allowed : the domain name can contains special characters. What's the issue ?

**Comment by psyray** [comment] 2020-01-13 18:40
Not supported does not mean that there is no email check on server side.
It's [a very bad practice](https://www.smashingmagazine.com/2009/07/web-form-validation-best-practices-and-tutorials/) to not verify input on server side.
Not supported does not mean that users will not use it.

From what I've found accented email are not allowed
https://www.eila.univ-paris-diderot.fr/sysadmin/mail/mail
https://www.infomaniak.com/en/support/faq/438/what-characters-are-allowedvalid-in-an-email-address

Where do you read that accented characters are authorized in email ?
Is there any official document (RFC...)

The issue is clearly explained in the problem chapter, user will not receive email.
And the second issue is no check on server side (while check is done client side - try to type an email with an accent in the registration form).

**Comment by khouloudbelguith** [comment] 2020-01-14 09:57
Hi @psyray,

In fact, in the PS1.7.4.0, we fixed an issue with special chars in the domain mail address.
Here's the PR:
https://github.com/PrestaShop/PrestaShop/pull/9080
take a look at https://en.wikipedia.org/wiki/Punycode

In this situation we can't do anything about Chrome, it's normal behavior when you send anything in input type="email" everything store in hostname is converted in PunyCode. 

Thanks to check & feedback.

**Comment by psyray** [comment] 2020-02-01 16:40
@khouloudbelguith 
I've read links, and you're right that the domain name can contain special character according to the RFC 6530.
But the current issue is not in the domain part, but in the username part.

Try typing in the registration form an email like ééé@free.fr, client side validation prevent registration
![image](https://user-images.githubusercontent.com/1230954/73595439-237b3f00-4519-11ea-9884-190290108065.png)

Now try typing this email eeee@fréé.fr, no error on client side registration
![image](https://user-images.githubusercontent.com/1230954/73595449-43126780-4519-11ea-8ba8-754fea890ac8.png)

So if client side validation does not permit username with accented character, server side validation should do the same, because if for any reason javascript is disabled in the client browser, registration will pass, and user will never receive his email because swiftmailer email validation check will prevent sending and raise an error complaining about RFC.
```
'Address in mailbox given [...] does not comply with RFC 2822, 3.6.2.'
```

**Comment by psyray** [comment] 2020-02-01 16:50
I found this issue which is a solution to fix this issue but with one big caveat : PHP retro compatibility.
https://github.com/PrestaShop/PrestaShop/issues/9638#issuecomment-418125107

@eternoendless said that this should be fixed when swiftmailer will be updated, but there is a PHP older version problem.

So I think that the temporary solution is to synchronize validation (client and server)

@eternoendless @matks @khouloudbelguith 
What do you thing about it ?

**Comment by khouloudbelguith** [comment] 2020-02-03 10:21
Hi @psyray,

Thanks for these clarifications.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11588
So, I close it.
Thanks !

**Closed as completed by khouloudbelguith** 2020-02-03 10:21 UTC
Labels: Bug, FO, Duplicate, Customer, 1.7.5.2

**Comment by psyray** [comment] 2020-02-03 10:41
OK thanks.
Do you have a planned release date for 1.7.7?

**Comment by khouloudbelguith** [comment] 2020-02-03 10:47
@psyray, you can follow our Project here: https://github.com/PrestaShop/PrestaShop/projects/7

Thanks!
