### ISSUE TITLE
🐛 [BUG] Applied voucher / discount code for abandoned carts

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#28032] opened 2022-03-24 16:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I've been doing some tests on vouchers and abandoned carts. I'll explain it easily so everyone can understand and see the "issue" merchants face:

Merchant sets a discount for the weekend, for instance for saturday and sunday.
Customer applies discount but creates an abandoned cart
Customer returns to the store on monday(next week) or tuesday and creates the order
Order is created with already applied vouchers, so CartRule.php won't check if voucher is active or not, leading us to an order created outside the timeframe of the voucher, with the voucher.

### Expected behavior

Voucher/discount should be checked not when you try to apply the voucher/discount but when you are going to checkout, at the same level of stock checking

### Steps to reproduce

1. Create voucher for day X
2. Create order with voucher at day X and leave (abandoned cart)
3. Go back day X+1 and finish order
4. Order is created with voucher even when voucher time has ended

### PrestaShop version(s) where the bug happened

1.7.7.3

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-03-25 09:40
Hello @ChineseNorris 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26235. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-25 09:40
Duplicate of #26235

**Closed as completed by hibatallahAouadni** 2022-03-25 09:40 UTC
Labels: Bug, Duplicate, Invalid
