### ISSUE TITLE
Missing translations? "This value should not be blank." Product name 

### ISSUE THREAD

**Issue by Sasni** [PrestaShop/PrestaShop#31446] opened 2023-02-19 20:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Where to translate this : "This value should not be blank." ? 
In BO improve/international/translations when i search for "This value should" showing only 3 phrases and none of them match up.
![image](https://user-images.githubusercontent.com/3370929/219971797-08573e55-b98e-4168-b57f-b7bfc4da9e14.png)
So where is this phrases in files? 
![image](https://user-images.githubusercontent.com/3370929/219971707-b11fb94d-a9eb-41ee-9dd9-aa6b1bc9fe37.png)
I found it olny in this files: 
[content/1.7/back-office/catalog/products/add-edit-v2.md](https://github.com/PrestaShop/prestashop-specs/blob/40e795c5caf4bd367e66d0769f604b8d5cfe879b/content/1.7/back-office/catalog/products/add-edit-v2.md)
[content/1.7/spec-templates/technical-characteristics-template.md](https://github.com/PrestaShop/prestashop-specs/blob/6aaafe4457fe0d343ce51651ff91e2f393fd1c91/content/1.7/spec-templates/technical-characteristics-template.md)
[content/1.7/back-office/catalog/products/add-edit.md](https://github.com/PrestaShop/prestashop-specs/blob/a2d0ef3e323e2a4ed24dd27af0774d3e98a54561/content/1.7/back-office/catalog/products/add-edit.md)

### Expected behavior

I want to translate this phrase, 
I think this should be in AdminCatalogNotification.[xx-XX].xlf

### Steps to reproduce

Go To catalog -> Products -> add new product
Select type of product to -> Pack
Do not enter anything in the product name
Click Online OR Save 

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.2.34

**Comment by florine2623** [comment] 2023-02-21 09:53
Ping @l-delin ,

I have reproduced the issue for Polish Language in 1.7.7.8 and 8.0.0 :

<img width="903" alt="Screenshot 2023-02-21 at 10 53 08" src="https://user-images.githubusercontent.com/16019289/220310756-ae12593d-3845-49ff-bc56-e58f02f8e367.png">

Could you explain the steps to add the translation in Crowdin ?
THanks 🤗

**Comment by l-delin** [comment] 2023-02-27 12:57
Hello @Sasni !

The translation is missing because it hasn't been approved on Crowdin yet (see screenshot):
![image](https://user-images.githubusercontent.com/113511191/221568265-dbb20b85-b1e1-4f9d-9fc0-4957afa343b7.png)

To put it simply, translation strings are uploaded on Crowdin and are then translated by the community. 
When a string is translated but not approved on a language project in [Crowdin](https://crowdin.com/project/prestashop-official), it does not appear in the software until it has been approved by a proofreader.

If you wish to suggest a translation for this missing string, I'll gladly take it and approve it for you. Thank you!

If you wish to learn more about the translation process, you can check out [this page ](https://docs.prestashop-project.org/translating-prestashop/translating-prestashop-software-basics/translating-on-crowdin) 🙌

**Comment by florine2623** [comment] 2023-03-09 11:38
Thanks for your answer @l-delin .
I hope it helps @Sasni 

I'll close this issue !

**Closed as completed by florine2623** 2023-03-09 11:38 UTC
Labels: Bug, BO, Translations, Invalid, 8.0.0
