### ISSUE TITLE
Broken buttons when reducing window scale on Partial refund page (BO - 8.0.0)

### ISSUE THREAD

**Issue by l-delin** [PrestaShop/PrestaShop#31338] opened 2023-02-13 16:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When reducing the window scale on the partial refund page (in the BO under Orders > Order > Partial refund page), the buttons are bugged and are pushed out of the main page layout. 

This happens to the "Amount (Tax excluded)" currency field as well as the "Update status" button (see linked video). It gets worse as the window is scaled down.

I'm running Chrome on a Mac and I was able to reproduce the same thing on Safari.

https://user-images.githubusercontent.com/113511191/218509274-a9f7c41a-d585-4d80-a8e5-ef81de01d92d.mov

![updatestatussafari](https://user-images.githubusercontent.com/113511191/218514531-ec997385-95ff-415d-afe0-3dc776a3b924.png)

### Expected behavior

The field and button should keep up with the page's scale. 

### Steps to reproduce

1. Go to the Orders page 
2. Click on an order that has the "shipped" status
3. Clik on the Partial refund button
4. Scale down the window
5. Look at the "Amount (Tax excluded)" field and "Update status" button.

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment] 2023-02-14 20:09
Hello @l-delin 

I reproduce the issue with PS800, it's a regression!
 I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by hibatallahAouadni** [comment] 2023-02-14 20:27
Hello again @l-delin 

Happy news 🎉 it has been fixed on 8.0.1 you just need to upgrade 😉 
Your issue is duplicate to this one #29849 

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-02-14 20:27
Duplicate of #29849

**Closed as completed by hibatallahAouadni** 2023-02-14 20:27 UTC
Labels: Bug, BO, Duplicate, Order, Front-end, Responsive, Invalid, 8.0.0
