### ISSUE TITLE
Wrong price when i import (wrong input)

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#31264] opened 2023-02-07 18:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I have a problem with the import but not for all my stores. When I want to import just the price with tax of the product, on some stores, it is put in price without tax (HT). But on other stores, it works well and so the price without tax is calculated by prestashop. Do you know why?

I put you a video : https://drive.google.com/file/d/1ZSfa-deWf2U3c_ZG3K5Nbqgpa4Wo7GSA/view

Can you help me please ?

thank you

CSV
ID,TTC
386,1259
388,1879
571,1879
387,1879
846,599
850,599
848,599
847,599

### Steps to reproduce

1. Go in Import > Product
2. Check Force all ID numbers

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.2

**Comment by HanaRebaiQA** [comment] 2023-02-09 11:00
Hello @ShaimyWinda 

Thanks for your report.
Could you please send us your csv file, I have a problem when generating it.

**Comment by ShaimyWinda** [comment] 2023-02-09 11:31
Hello @HanaRebaiQA

Yes ofc. 

[exports_allshops_prixht_2023 - Feuille 18 (1).csv](https://github.com/PrestaShop/PrestaShop/files/10696597/exports_allshops_prixht_2023.-.Feuille.18.1.csv)

Thanks for help

**Comment by hibatallahAouadni** [comment] 2023-02-15 12:33
Hello @ShaimyWinda 

Thanks for your feedback and your patience 🙏 
I didn't manage to reproduce the issue with the latest version 8.0.1, see the attached screen record below:

[issue_31264.webm](https://user-images.githubusercontent.com/23308427/219028466-af8549d9-f8e5-4e6a-8f1e-b8f932ffe243.webm)

Please check and feedback.

Thanks!

**Comment by djoelleuch** [comment] 2023-03-07 09:10
Hello @ShaimyWinda ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as not planned by djoelleuch** 2023-03-07 09:10 UTC
Labels: Bug, BO, Import / Export, 1.7.7.2, Invalid
