### ISSUE TITLE
Product customization file can’t be downloaded if the customization label field contains a dot

### ISSUE THREAD

**Issue by Blaaszkovsky** [PrestaShop/PrestaShop#24036] opened 2021-04-13 18:56 UTC
#### Describe the bug

If the field title contains a "dot", then Presta in the order cannot generate the appropriate link with the photo to download - https://blachucik.pl/s/8M9xv.jpg

#### Expected behavior
When I changed the field name so that it did not contain a "dot" then everything returns to normal. The link correctly generates a photo for download. An error is returned in debug mode.

#### Steps to Reproduce

1. Go to product in "option" add field with "dot" ex. "Page nb. 1"
2. Try to buy this product
3. Go to BO and see this Order and try to download picture. 
4. Go to product from 1 and delete "dot" - "Page nb 1"
5. Repeat 2 and 3

Screen 1 - https://blachucik.pl/s/dk2mS.jpg (problem)
Screen 2 - https://blachucik.pl/s/eJx4P.jpg (solved)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

**Comment by florine2623** [comment] 2021-04-14 12:54
Hello @Blaaszkovsky ,
I was able to reproduce the issue with PrestaShop version 1.7.7.3, so I can confirm that this behavior is indeed a bug.

I attach a screen record of the issue : https://drive.google.com/file/d/1EOPxhdadw8FSIIdj948aa9LzVuSiLM30/view 
![Capture d’écran 2021-04-14 à 14 56 01](https://user-images.githubusercontent.com/16019289/114713575-909b7e80-9d31-11eb-9976-78ef3f69cd95.png)


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](url_here) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by hibatallahAouadni** [comment] 2021-04-20 09:13
Hello everyone,

I reproduce the issue with PS1.7.7.x and develop, and I didn't manage to reproduce is with PS1.7.6.7. 
So, it's a regression :wink: 

Thanks!

**Comment by Progi1984** [comment] 2021-04-23 12:07
Fixed by #24161

**Closed as completed by Progi1984** 2021-04-23 12:07 UTC
Labels: Bug, Minor, BO, Image, Regression, Fixed, 1.7.7.3
