### ISSUE TITLE
Incorrect text formatting for product with combinations

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19623] opened 2020-06-08 10:39 UTC
Hello,
I use PS 1.7.6.5 and there is incorrect text format if there is a product with combinations and there is 2 or more attributes. 
There is missing a blank space between the 1st and 2nd attribute. This text is used also in an invoice and some times it is confusing for an end user.

There is: 
... t-shirt - Size : **S-** Color...
There should be: 
... t-shirt - Size : **S -** Color...
![image](https://user-images.githubusercontent.com/33311857/84021101-4e244b00-a984-11ea-8d7e-4583a75d6ccb.png)

**Comment by florine2623** [comment] 2020-06-08 13:51
Hi @PrestaShop/prestashop-product-team ,
Can we implement adding a space between the combinations of product ?

It occurs at a few different places :
Recap of order FO :
![Capture d’écran 2020-06-08 à 15 42 31](https://user-images.githubusercontent.com/16019289/84038061-b16fa680-a99f-11ea-8cc4-922cf4e374b5.png)

Invoice PDF :
![Capture d’écran 2020-06-08 à 15 43 55](https://user-images.githubusercontent.com/16019289/84038011-a3218a80-a99f-11ea-8f40-5e4f7f32f682.png)

In the BO > Orders > Details :
![Capture d’écran 2020-06-08 à 15 44 08](https://user-images.githubusercontent.com/16019289/84038092-be8c9580-a99f-11ea-973a-06991714748a.png)

Thanks!

**Comment by LouiseBonnard** [comment] 2020-06-08 13:55
Sure, I just ping the @PrestaShop/prestashop-designers so that they can know about it but there should definitely be a space between the attributes. :-)

**Comment by florine2623** [comment] 2020-06-08 14:18
Hi @LouiseBonnard thanks for the response, but it was actually a duplicate. It is fixed in https://github.com/PrestaShop/PrestaShop/issues/17309.

Thanks @marionf for letting me know !

@juraj1000 , this issue will be fixed in PS 1.7.8.

**Comment by florine2623** [comment] 2020-06-08 14:18
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/17309

**Closed as completed by florine2623** 2020-06-08 14:18 UTC
Labels: BO, FO, Duplicate, Order, Combinations
