### ISSUE TITLE
Calculation of VAT details with card rules are wrong

### ISSUE THREAD

**Issue by MickaelJN** [PrestaShop/PrestaShop#14556] opened 2019-07-09 14:27 UTC
**Describe the bug**
Calculation of VAT details with card rules are wrong
First with a card rule, prestashop can't offer the delivery... In reality it make a reduction on total of product without tax.
Second : if product vat is 10% and delivery 20%, prestashop make wrong calculation of vat to delivery, product and total of the order.
All the invoices are illegals !!

**To Reproduce**
Product with VAT 10%
Card rule to offer delivery with VAT 20%
Do an order with some product and with the card rules (code to a customer)

**Screenshots**
![image](https://user-images.githubusercontent.com/44616092/60896054-f4903980-a265-11e9-9b54-0c6353115193.png)
![image](https://user-images.githubusercontent.com/44616092/60896139-1b4e7000-a266-11e9-8237-ace109f6c31b.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-09 15:37
Hi @micboss71,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11492
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-09 15:38
Duplicate of #11492

**Closed as completed by khouloudbelguith** 2019-07-09 15:37 UTC
Labels: Duplicate
