### ISSUE TITLE
Delivery slip locks order, invoice, payment, status does not

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#18999] opened 2020-05-06 10:02 UTC
Orders become un-editable “generate delivery slip”. 
Invoice, payment, status, "consider valid", or anything else affects if an order is editable.

Why is this a problem? When a merchant wants to pick and ship an order, he needs a delivery slip. When generating this the order gets locked. When then the merchant discovers that one of the items in the order is out of stock, he wants to change the order - but cannot.

I understand that an order needs to be locked after generating a legal document like the invoice, but when it comes to the invoice, this actually does not lock the order.

I don't get the logic.

**Comment by TristanLDD** [comment] 2020-05-06 12:52
Hi @onklmaps, thanks for your report 

As this is an improvement, could you please fill the feature request form? 
Here https://github.com/PrestaShop/PrestaShop/issues/new?template=feature_request.md
Thanks!

**Comment by LouiseBonnard** [comment] 2020-05-13 08:52
Hi there, it looks like a duplicate of #19043. I close this one so that we can all focus on #19043, thanks!

**Closed as completed by LouiseBonnard** 2020-05-13 08:52 UTC
Labels: Improvement, BO, Duplicate, Order, Invoices
