### ISSUE TITLE
multistore is not working properly || directory problem 

### ISSUE THREAD

**Issue by dharmendravirasat** [PrestaShop/PrestaShop#14108] opened 2019-06-07 12:06 UTC
i have a created multistore, shop name is shopA and copy from primary  folder/code/project &&  paste in  subfolder/newShop then i was changed themes logo for shopA.
But logo not showing.
i was checked problem is that added new logo image storing in primary project,i don't know why not store in subfolder/newShop   
 plz comment

Thanks

**Comment by mariem-abid** [comment] 2019-06-07 13:17
Hi @dharmendravirasat,

What is the exact version of PrestaShop did you use?

Thanks!

**Comment by dharmendravirasat** [comment] 2019-06-07 13:47
I am using  Prestashop version 1.7.5.1   @mariem-abid 
plz reply

**Comment by khouloudbelguith** [comment] 2019-06-11 16:14
@dharmendravirasat, you just created a new issue about this problem.
Duplicate of #14139

**Comment by khouloudbelguith** [comment] 2019-06-11 16:14
Duplicate of #14139

**Closed as completed by khouloudbelguith** 2019-06-11 16:14 UTC
Labels: Duplicate, Theme & logo, Multistore
