### ISSUE TITLE
OrderController for guest, unnecessary validating all suppliers,manufacturers,warehouses addresses

### ISSUE THREAD

**Issue by lutek** [PrestaShop/PrestaShop#14881] opened 2019-07-26 17:50 UTC
**Describe the bug**
On checkout page prestashop unnecessary validating all suppliers,manufacturers,warehouses addresses record for not logged user.

this line:
https://github.com/PrestaShop/PrestaShop/blob/368fc858b8cbc1f40949412d28ac2d273bae6abc/classes/checkout/AddressValidator.php#L80

generates sql:
```
SELECT DISTINCT a.*, cl.`name` AS country, s.name AS state, s.iso_code AS state_iso FROM `ps_address` a LEFT JOIN `ps_country` c ON (a.`id_country` = c.`id_country`) LEFT JOIN `ps_country_lang` cl ON (c.`id_country` = cl.`id_country`) LEFT JOIN `ps_state` s ON (s.`id_state` = a.`id_state`) INNER JOIN ps_country_shop country_shop ON (country_shop.id_country = c.id_country AND country_shop.id_shop = 1) WHERE `id_lang` = 1 AND `id_customer` = 0 AND a.`deleted` = 0
```

**To Reproduce**
enable _PS_DEBUG_PROFILING_
1. generate ex. 100 supplier addresses
2. add product to basket
3. go to checkout as non logged user

profiling page

selected call stack:
```
SELECT SQL_NO_CACHE *
FROM `ps_address` a
WHERE (a.`id_address` = 147217) LIMIT 1
/classes/ObjectModel.php:264
/tools/profiling/ObjectModel.php:33
/classes/Address.php:165
/classes/checkout/AddressValidator.php:85
/controllers/front/OrderController.php:232
/controllers/front/OrderController.php:262
/tools/profiling/Controller.php:233
/classes/Dispatcher.php:515
/index.php:28


SELECT SQL_NO_CACHE c.`need_identification_number`
FROM `ps_country` c
WHERE c.`id_country` = 14 LIMIT 
/classes/ObjectModel.php:1001
/classes/checkout/AddressValidator.php:86
/controllers/front/OrderController.php:232
/controllers/front/OrderController.php:262
/tools/profiling/Controller.php:233
/classes/Dispatcher.php:515
/index.php:28
```

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**patch**
```
Index: classes/Customer.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- classes/Customer.php	(date 1564217598000)
+++ classes/Customer.php	(date 1564217598000)
@@ -581,7 +581,8 @@
                     LEFT JOIN `' . _DB_PREFIX_ . 'country_lang` cl ON (c.`id_country` = cl.`id_country`)
                     LEFT JOIN `' . _DB_PREFIX_ . 'state` s ON (s.`id_state` = a.`id_state`)
                     ' . ($shareOrder ? '' : Shop::addSqlAssociation('country', 'c')) . '
-                    WHERE `id_lang` = ' . (int) $idLang . ' AND `id_customer` = ' . (int) $this->id . ' AND a.`deleted` = 0';
+                    WHERE `id_lang` = ' . (int) $idLang . ' AND `id_customer` = ' . (int) $this->id . ' AND a.`deleted` = 0
+                    AND a.`id_manufacturer` = 0 AND a.`id_supplier` = 0 AND a.`id_warehouse` = 0';
 
             $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($sql);
             Cache::store($cacheId, $result);
```

**Comment by khouloudbelguith** [comment] 2019-07-29 07:49
Hi @lutek,

This issue is fixed in the PS1.7.5.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/8904
Your ticket is a duplicate of #9690
Thanks to check & feedback.

**Comment by lutek** [comment] 2019-07-29 12:27
from profiler, i have over 90k addresses in database.

![queries](https://user-images.githubusercontent.com/846598/61970488-2a128200-afdd-11e9-8133-61299256d00d.png)

![doubles](https://user-images.githubusercontent.com/846598/61970491-2d0d7280-afdd-11e9-870b-9ffb59fa97d7.png)

after delete all unnecessary addresses with id_customer = 0 i notice that all other (ex supplier) are processed

**Comment by khouloudbelguith** [comment] 2019-07-29 12:30
ping @jocel1 what do you think?

Thanks!

**Comment by LouiseBonnard** [comment] 2020-09-09 09:03
Hi @lutek, can you confirm that PR https://github.com/PrestaShop/PrestaShop/pull/16620 fixes this issue?

**Comment by szykuc** [comment] 2020-11-03 16:09
@khouloudbelguith @LouiseBonnard in 1.7.6.8 i have still this issue.

Any advices to fix it?

**Comment by LouiseBonnard** [comment] 2020-11-03 17:05
Hello @lutek, did you try with the fix mentioned above? It is planned for version 1.7.8 but you can use this fix on your store if you feel comfortable with it. :-)

**Comment by szykuc** [comment] 2020-11-03 17:23
@LouiseBonnard I'm not lutek just find this issue after 2 days of searching problem with long chekout load ;)

Yes #16620 helped me. One simple condition and all my problems gone ;)

Btw, why are such important fixes not implemented as early as possible?

**Comment by lutek** [comment] 2020-11-04 13:30
@LouiseBonnard i didn't check this PR #16620, but my patch is on my live shop. I'm still on 1.7.6 version.

**Comment by LouiseBonnard** [comment] 2020-11-05 08:47
Oops, sorry for the name mistake, @szykuc! 🙈

Great to read it helped to fix this issue, I'll close it then, thanks. We aim at delivering bug fixes as soon as possible, but PrestaShop versions come with other projects (refactoring, migration, improvements, etc.) which require more time to code, review, and test. And this is what can extend the release cycle. At that time, the 1.7.7 scope was frozen (it should be released in a few days) so any fix or improvement was automatically planned for 1.7.8. :-)

As for your patch, @lutek, it's good news, thanks for your reply. You're more than welcome to share it here next time, it will make you improve the life of 100,000 merchants around the world!

**Closed as completed by LouiseBonnard** 2020-11-05 08:47 UTC
Labels: Addresses, Fixed, Checkout, 1.7.6.0
