### ISSUE TITLE
 library php_fileinfo extension.

### ISSUE THREAD

**Issue by web-centre** [PrestaShop/PrestaShop#10803] opened 2018-10-02 05:20 UTC
The issue has caused because when my Prestashop tries to upload a module, it doesn't find the library php_fileinfo extension.

**Comment by PierreRambaud** [comment] 2018-10-02 07:13
Hi,
Which version of PHP are you using? This extension of PHP is enabled by default as of PHP 5.3.0.
Regards

**Comment by khouloudbelguith** [comment] 2018-10-02 07:38
Hi @web-centre,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by web-centre** [comment] 2018-10-03 07:23
Good morning.
My prestashop version is 1.7.2.4
php: 5.6
attached all the filelog screens and settings
![errori cpanel](https://user-images.githubusercontent.com/43772147/46395839-f7199d80-c6ed-11e8-89cb-00b283b0b236.JPG)
![impostazione](https://user-images.githubusercontent.com/43772147/46395840-f7199d80-c6ed-11e8-8219-b6aaa4314af0.JPG)
![log errori pag 1](https://user-images.githubusercontent.com/43772147/46395841-f7b23400-c6ed-11e8-9f89-2874c1393e4a.JPG)
![log errori pag 2](https://user-images.githubusercontent.com/43772147/46395843-f7b23400-c6ed-11e8-9db1-c35404effa37.JPG)
![log errori pag 3](https://user-images.githubusercontent.com/43772147/46395844-f7b23400-c6ed-11e8-822f-aaa5d76f63d8.JPG)
![php version](https://user-images.githubusercontent.com/43772147/46395845-f7b23400-c6ed-11e8-8df6-4e873ef3fa0a.JPG)
![versione prestashop](https://user-images.githubusercontent.com/43772147/46395846-f84aca80-c6ed-11e8-9e6c-cf9fda588b5b.JPG)

**Comment by khouloudbelguith** [comment] 2018-10-03 08:47
Hi @web-centre,

Could you please check if the fileinfo PHP extension is enabled on your server.
![image](https://user-images.githubusercontent.com/16067358/46399945-7496db00-c6f9-11e8-9279-ef0645b6a8b7.png)
- You can follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
- Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
- Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
- Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/46400028-ac9e1e00-c6f9-11e8-8734-3e08a2f2f875.png)

Thanks to check and feedback.

**Comment by web-centre** [comment] 2018-10-03 09:33
I downloaded the file at www.web-centre.it/negozi but does not let me open it

**Comment by khouloudbelguith** [comment] 2018-10-03 09:41
@web-centre, could you please try to know if fileinfo is enabled in your PHP info.
You can follow this link http://kb.mediatemple.net/questions/764/How+can+I+create+a+phpinfo.php+page%3F#gs

**Comment by web-centre** [comment] 2018-10-03 14:50
ok, ho caricato il file in http://web-centre.it/negozi/info.php

allego screen
![info php 1](https://user-images.githubusercontent.com/43772147/46418581-5bf3e880-c72c-11e8-88ba-9cb548db52d6.JPG)
![info php 2](https://user-images.githubusercontent.com/43772147/46418582-5bf3e880-c72c-11e8-81ee-1a7e80978318.JPG)
![Uploading info php 4.JPG…]()
![Uploading info php 5.JPG…]()
![Uploading info php3.JPG…]()
![Uploading info php6.JPG…]()
![Uploading info php7.JPG…]()

**Comment by khouloudbelguith** [comment] 2018-10-03 14:54
Hi @web-centre, as expected, you need to enable the fileinfo extension on your server.
![image](https://user-images.githubusercontent.com/16067358/46418883-eccac400-c72c-11e8-8b31-9ada13e4761d.png)
You need to check your host, if you don't have access.

**Comment by web-centre** [comment] 2018-10-03 15:07
as?

**Comment by khouloudbelguith** [comment] 2018-10-03 15:11
@web-centre, sorry but it is a server issue, not in the core of PrestaShop.

**Comment by web-centre** [comment] 2018-10-04 14:39
the info file library is now working. Is there anything else to do?

**Comment by khouloudbelguith** [comment] 2018-10-04 14:44
@web-centre, thanks!
So the issue is solved?

**Comment by web-centre** [comment] 2018-10-04 15:45
no, now I have this
![errore2](https://user-images.githubusercontent.com/43772147/46486085-4dc1cd00-c7fd-11e8-82f1-28d3eb8aa101.jpg)

**Comment by khouloudbelguith** [comment] 2018-10-04 15:51
@web-centre, what is the exact name of the module do you want to install?

**Comment by web-centre** [comment] 2018-10-04 16:19
We want to update the module mmo_connector to synchronize  with the his right version 4.5.0.

**Comment by khouloudbelguith** [comment] 2018-10-04 16:22
@web-centre, this module is it compatible with the Prestashop version 1.7.2.4?
Have you tried to contact the module author?

**Comment by web-centre** [comment] 2018-10-04 16:25
yes, it is compatible with the prestashop version. The author of the module is helping me with the installation but it is necessary to solve these problems

**Comment by khouloudbelguith** [comment] 2018-10-04 16:31
@web-centre, when you click on the "What happened?" link, is there any exception displayed? (thanks to enable the debug mode)

**Comment by web-centre** [comment] 2018-10-05 06:53
When you click on "What happened?" shows the error 500.Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [PrestaShop/PrestaShop]  library php_fileinfo extension. (#10803)Da: khouloudbelguith A: PrestaShop/PrestaShop CC: web-centre ,Mention @web-centre, when you click on the "What happened?" link, is there any exception displayed? (thanks to enable the debug mode)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PrestaShop/PrestaShop","title":"PrestaShop/PrestaShop","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/PrestaShop/PrestaShop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@khouloudbelguith in #10803: @web-centre, when you click on the \"What happened?\" link, is there any exception displayed? (thanks to enable the debug mode)"}],"action":{"name":"View Issue","url":"https://github.com/PrestaShop/PrestaShop/issues/10803#issuecomment-427084991"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PrestaShop/PrestaShop/issues/10803#issuecomment-427084991",
"url": "https://github.com/PrestaShop/PrestaShop/issues/10803#issuecomment-427084991",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [PrestaShop/PrestaShop]  library php_fileinfo extension. (#10803)",
"sections": [
{
"text": "",
"activityTitle": "**khouloudbelguith**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@khouloudbelguith",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"PrestaShop/PrestaShop\",\n\"issueId\": 10803,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"PrestaShop/PrestaShop\",\n\"issueId\": 10803\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/PrestaShop/PrestaShop/issues/10803#issuecomment-427084991"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 386753760\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by web-centre** [comment] 2018-10-05 07:09
When you click on "What happened?" shows the error 500

debug mode enable

**Comment by web-centre** [comment] 2018-10-05 09:03
solved

**Comment by khouloudbelguith** [comment] 2018-10-08 16:20
@web-centre, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

**Closed as completed by khouloudbelguith** 2018-10-08 16:20 UTC
Labels: Modules, Fixed
