### ISSUE TITLE
Prestashop 1.7.6.4: attribute values starting with "-" (minus) are not shown in stock page

### ISSUE THREAD

**Issue by EnricoGentiletti** [PrestaShop/PrestaShop#18567] opened 2020-04-10 10:37 UTC
In the 1.7.6.4 Prestashop versione attribute values starting with "-" (minus) are not shown in stock page

![ScreenHunter 240](https://user-images.githubusercontent.com/60389117/78984941-d2468780-7b27-11ea-9e13-d7a3da0e7625.png)
![ScreenHunter 241](https://user-images.githubusercontent.com/60389117/78984944-d377b480-7b27-11ea-8e15-2c06f4955972.png)
![ScreenHunter 242](https://user-images.githubusercontent.com/60389117/78985021-091c9d80-7b28-11ea-81db-726a304206ae.png)

How can i fix it?

**Comment by florine2623** [comment] 2020-04-10 11:33
Hi @EnricoGentiletti ,

I managed to reproduce your issue in PS 1.7.5.2 as well as 1.7.6.4
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by EnricoGentiletti** [comment] 2020-04-10 13:38
I am sorry but i cannot fix it. I created a workaround using another unicode minus symbol.

**Comment by khouloudbelguith** [comment] 2020-04-10 16:45
Hi @EnricoGentiletti,

Your ticket is a duplicate of #16706
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-04-10 16:45
Duplicate of #16706

**Closed as completed by khouloudbelguith** 2020-04-10 16:45 UTC
Labels: Bug, Minor, BO, Duplicate, Attributes, Stocks, 1.7.5.2, 1.7.6.4
