### ISSUE TITLE
Wrong Product sort order by quantity

### ISSUE THREAD

**Issue by Ybeske** [PrestaShop/PrestaShop#10880] opened 2018-10-05 15:40 UTC
**Description**
In the "Pagination" section under "Shop Parameters" > "Product Settings", Prestashop wisely offered the product order "by quantity" so you could display the product with high quantities first for example.
However, the sort order in't changing in the correct sort order.

**To Reproduce**
1. Go to "Shop Parameters" > "Product Settings"
2. Scroll down to "Pagination", at "Default order by" select "Product quantity" 
3. "Save" settings
4. check the sort order and check the product quantities under catalog for the same category
5. the sort order is wrong.

**Screenshots**
<img width="1633" alt="product order by quantity" src="https://user-images.githubusercontent.com/43880279/46544740-aa3bef80-c8c4-11e8-9ced-459868d0b82d.png">

<img width="1505" alt="product quantities bo" src="https://user-images.githubusercontent.com/43880279/46544944-41a14280-c8c5-11e8-93d5-0a908dc6c41d.png">

<img width="864" alt="product wrong sort order" src="https://user-images.githubusercontent.com/43880279/46544947-45cd6000-c8c5-11e8-85e7-9612162e258d.png">

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: 5.6 and 7.0

**Comment by khouloudbelguith** [comment] 2018-10-08 10:26
Hi @Ybeske,

Your issue is a duplicate of #9956 so, I close it
Yous should follow this issue.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-08 10:26
Duplicate of #9956

**Closed as completed by khouloudbelguith** 2018-10-08 10:26 UTC
Labels: Duplicate
