### ISSUE TITLE
Multistore: visualize if config is inherited from global / parent group or fixed for the current store

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#20060] opened 2020-07-05 08:36 UTC
When using the multistore feature, we are able to change the configuration globally or by store.

- If you change a config value on the "All stores" / "Group" context, the new value will be applied to all children stores where you didn't set a specific value

- But if you already set a specific value to 1 of your store, you are not able to reset it to the parent value. 
Even if you change it to match the global value, if you change the global config, the specific store will keep the old value.

And we have no easy way to know if the value come from parent config or if it has been overridden in the current store.

I think this could be improved to something similar to Magento.
Using a checkbox to tell if we want to use the parent config value or if we want to set a custom one for the current store.

![image](https://user-images.githubusercontent.com/915273/86528566-7a73ae80-bed3-11ea-9abd-c57608b1cf6c.png)

With Prestashop, this could be:

![image](https://user-images.githubusercontent.com/915273/86528728-0cc88200-bed5-11ea-97af-a9426a806bf1.png)

**Comment by sarahdib** [comment] 2020-07-06 16:55
Hello @Seb33300 

We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #9833

To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you!

**Comment by sarahdib** [comment] 2020-07-06 16:55
Duplicate of #9833

**Closed as completed by sarahdib** 2020-07-06 16:55 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2020-07-07 07:20
Related to: https://github.com/PrestaShop/PrestaShop/issues/19304
