### ISSUE TITLE
ps_facetedsearch doesn't show all sizes

### ISSUE THREAD

**Issue by Bawalwebs** [PrestaShop/PrestaShop#21536] opened 2020-10-20 16:34 UTC
#### Describe the bug

In the product list of one category, there are some values that aren't showed.

For example, there are some size or color that is not showed in the module. 

#### Expected behavior

All combinatios of the product must be showed in the module for the user can filter the products correctly.

#### Steps to Reproduce

1. Go to 'http://31.200.244.88/~xlpieh2o/26-zapatos-planos-y-semicunas' (dev url)
2. See error: The color "yellow" or "green" of the first product and the size 43 don't appear in the filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/73185517/96616261-a1c77d80-1302-11eb-83c3-ae26498bc053.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: 7.3
* Module ps_facetedsearch 3.6.0

**Comment by khouloudbelguith** [comment] 2020-10-21 08:11
Hi @Bawalwebs,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.8 and ps_facetedsearch v3.6.0.
![image](https://user-images.githubusercontent.com/16067358/96691731-89e50d80-1385-11eb-8878-1769d06001db.png)
Could you please navigate to your BO > Module Manager > ps_facetedsearch configuration page => Click on "Build attributes and features indexes" and "Clear cache", check and feedback.

Also, what is the exact PrestaShop did you use?

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-10 08:41
Hello @Bawalwebs 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-10 08:41 UTC
Labels: Bug, FO, Can't reproduce, Faceted search
