### ISSUE TITLE
Product pack quantity wrong when using product variations

### ISSUE THREAD

**Issue by theodiablo** [PrestaShop/PrestaShop#23706] opened 2021-03-19 17:21 UTC
#### Describe the bug

I have a pack of products, which is the same products but with his different variations.
When one of those product variation is out of stock, the pack is still enabled.

#### Expected behavior

The pack should be disabled and display the "Email me when product is back on stock" form I have

#### Steps to Reproduce

Using the basic Prestashop installation

1. Create a product pack containing several variations of the product "Hummingbird printed t-shirt" s-white, s-black, m-white, m-black for instance
2. In Quantities tab, set "Decrement products in the pack only" option
3. Go to your newly created product, it should be displayed correctly and you can add it to the cart (remove the product if added)
4. Set the stock product "Hummingbird printed t-shirt" "S Black" variation to 0
5. Go to the product page, see that it is displayed as if it had items, however it should be disabled
6. Add the product to your cart, an error comes out.

The pack quantity should be 0, but it is 3000.

#### Screenshots

Variations quantities
![image](https://user-images.githubusercontent.com/8282971/111818228-3bf61680-88df-11eb-9e30-ef745a0c23d1.png)

Pack content
![image](https://user-images.githubusercontent.com/8282971/111818312-503a1380-88df-11eb-8c12-eb82517412a2.png)

Pack quantities config (auto calculated wrong)
![image](https://user-images.githubusercontent.com/8282971/111818385-67790100-88df-11eb-9db8-00b40d90569f.png)

Button enabled, even when one variation has 0 stock
![image](https://user-images.githubusercontent.com/8282971/111818566-9becbd00-88df-11eb-8ac0-686ab9a35db5.png)

Error message after clicking on the "add to cart button"
![image](https://user-images.githubusercontent.com/8282971/111818169-2d0f6400-88df-11eb-987f-6475cd95e786.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by theodiablo** [comment] 2021-03-19 17:22
It's been several months now I am experiencing weird behaviours with product packs quantities, now I understand it comes from the use of product variations in the pack, which seems to lead to a wrong calculation of available quantities of the pack.

**Comment by hibatallahAouadni** [comment] 2021-03-22 14:08
Hello @theodiablo 

Could you please check this issue #13769 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by theodiablo** [comment] 2021-03-22 17:17
@hibatallahAouadni, indeed, it seems to be the same issue. I think in my description I am giving a bit more details, but yes, this is very likely the same root cause!

**Comment by hibatallahAouadni** [comment] 2021-03-23 09:39
Hello @theodiablo 

> I think in my description I am giving a bit more details

Yes you're right :clap: so I will copy and paste your description into that issue :wink: Thanks!
But as you know, I have to close this issue cause it is already in our debug backlog. 
This issue is a duplicate of #13769. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-23 09:40
Duplicate of #13769

**Closed as completed by hibatallahAouadni** 2021-03-23 09:39 UTC
Labels: Bug, BO, Duplicate, Stocks, Pack, 1.7.7.2
