### ISSUE TITLE
[blockwishlist] No images available for my favorite products for blockwishlist v2 and 1.7.6

### ISSUE THREAD

**Issue by lolath-presta** [PrestaShop/PrestaShop#24021] opened 2021-04-13 08:28 UTC
#### Describe the bug

When I add products to my wishlist and then go to the favorites list, my products are displayed but the product image is missing.

#### Expected behavior

I should have the product image displayed 

#### Steps to Reproduce

1. Go to the front office, 
2. Click on the heart either directly on the product block or in the product sheet to add the product to your favorites list 
3. Go to my account >  My wishlists  > the wishlist where I added my products 
4. I can see all the products added but without their image 

![image](https://user-images.githubusercontent.com/61282681/114521654-ee9d6880-9c42-11eb-97d0-536617fa2a80.png)

#### Additional information

* PrestaShop version: 1.7.6.7

**Comment by NeOMakinG** [comment] 2021-04-13 09:00
@PrestaShop/prestashop-maintainers 

@kpodemski I remember you worked on this, what you've done is not working in production sometime, I need a backend dev to looks at it in order to provide the right image to the front-end! Hope someone can take this :)

**Comment by kpodemski** [comment] 2021-04-14 01:49
@NeOMakinG we have to find a way to reproduce it on my side, then I'll be happy to help, you can reach me on Slack 👍🏻

**Comment by kpodemski** [comment] 2021-04-21 12:15
@PrestaShop/qa-team 

Unfortunately I couldn't reproduce this issue, it might be related to some third party module or environment. 

Maybe any other @PrestaShop/prestashop-core-developers would be able to help?

**Comment by hibatallahAouadni** [comment] 2021-04-21 13:11
Hello @lolath-presta 

Thanks for reproting the issue! 
I didn't manage to reproduce it with PS1.7.7.3 but I reproduce it with PS1.7.6.7:

## PS1.7.6.7: :x: 

![image](https://user-images.githubusercontent.com/23308427/115559038-9b1ac280-a2b3-11eb-9aa9-7de499a92ce6.png)

## PS1.7.7.3: :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/115559070-a241d080-a2b3-11eb-96a5-4de48457b630.png)

@kpodemski could you please check it :wink: 

Thanks!

**Comment by kpodemski** [comment] 2021-04-23 07:42
Thanks @hibatallahAouadni - it's fixed on `dev`, you have PR linked to this issue 👍

**Comment by hibatallahAouadni** [comment] 2021-04-23 08:00
@kpodemski Perfect :rocket: Thanks for your PR

**Closed as completed** 2021-04-28 07:23 UTC
Labels: Bug, Minor, FO, Image, Fixed, Blockwishlist, PR available, 1.7.6.7

**Comment by matks** [comment] 2021-04-28 07:48
Should be fixed with blockwishlist 2.1.0 https://github.com/PrestaShop/blockwishlist/pull/108
