### ISSUE TITLE
Prestashop 1.7.5.1 Symphony Error: Missing translations while editing product in back office causing slow editing of products in back office

### ISSUE THREAD

**Issue by arpanjain100** [PrestaShop/PrestaShop#22591] opened 2020-12-25 11:33 UTC
Screenshot: [https://i.stack.imgur.com/OI5mp.png](https://i.stack.imgur.com/OI5mp.png)
This screenshot has been taken in debug mode. I have only 1 language en-US, yet I get errors of missing translations for all my categories, features, etc when trying to edit a product. The delay was 23 seconds, so I turned on debug mode to see the errors and found **all related to missing transaltions only.**

Since I have only 1 language, it is not possible to have translations for these terms in the back office. With debug mode off, everything works smoothly, but extremely slow with very high MySQL usage.

The error clearly states: "These messages are not available for the given locale and cannot be found in the fallback locales. Add them to the translation catalogue to avoid Symfony outputting untranslated contents."

Please explain how to avoid the same. and get the editing of products in Prestashop quick?
![Screenshot 2020-12-25 at 4 55 37 PM](https://user-images.githubusercontent.com/53334564/103133899-4e432880-46d3-11eb-95cf-839e851cdc83.png)
**Server information**
- Linux #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64
- Server software version: Apache/2.4.39 (Unix) OpenSSL/1.0.2k-fips
- PHP version: 7.1.33
- Memory limit: 512M
- Max execution time: 300
- Upload Max File size: 256M

**Database information**
- MySQL version: 10.1.48-MariaDB
- MySQL engine: InnoDB
- MySQL driver: DbPDO

**Comment by hibatallahAouadni** [comment] 2020-12-25 14:27
Hello @arpanjain100 

Usually those translation warning or translation errors do not affect the shop performance, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/103136959-087f6380-46c5-11eb-9cc6-dbe960077b25.png)

So, first of all, try to increase your **Upload Max File size** to 512M.
Then, please try to run those command lines to remove the cache:
```
rm -fR /Projet_PrestaShop/var/cache/*

php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Please check and feedback.
_**PS: Please next time follow the template that we afford to submit a complete bug report.**_

Thanks!

**Comment by arpanjain100** [comment] 2020-12-25 16:49
@hibatallahAouadni 
I have tried the same and yet the product page for back office takes 23 seconds to load. I have 343 categories. I will be having 1200 categories soon. Please advise what could be the possible reason for the product editing to take so long to load?
There is no other error except this one in debug.

**Comment by arpanjain100** [comment] 2020-12-28 10:57
Hi any update on this?

**Comment by hibatallahAouadni** [comment] 2020-12-29 09:01
Hello @arpanjain100 

> I have 343 categories. I will be having 1200 categories soon. 

When you mentioned categories, you mean this block:

![image](https://user-images.githubusercontent.com/23308427/103272213-9193e480-49bc-11eb-8e0f-3005ba4322dc.png)

If so, that's normal to be a little heavy to load all these categories.
We already have similar issue but with combinations #20928
Please check if it's similar, if so, what you suggest it's an improvement not a bug :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-18 13:01
Hello @arpanjain100 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-18 13:01 UTC
Labels: Bug, BO, Translations, Performance, No change required, 1.7.5.1
