### ISSUE TITLE
Cart Rules: Need Tax incl/excl config for percentage discount also

### ISSUE THREAD

**Issue by ramwebkul** [PrestaShop/PrestaShop#22060] opened 2020-11-23 14:54 UTC
**Describe the bug:**
- The Catalog Price Rules can be created with percentage discount, and the Tax incl/Excl option is available for percent as well. Please check:
![image](https://user-images.githubusercontent.com/53465735/99976577-9f58b780-2dc9-11eb-9271-8980f6c01270.png)

- In Cart Rule, the Tax excl/incl option is not available for percentage type:
![image](https://user-images.githubusercontent.com/53465735/99975799-adf29f00-2dc8-11eb-89a6-8017498e6b11.png)

**Expected Behaviour:**
- Tax incl/excl option should be in Percentage Cart Rules also. 
- Is there any reason for omitting this option from Cart Rules and Specific Prices?.

Additional information
PrestaShop version: 1.7.6.8
PHP version: 7.0.33

**Comment by hibatallahAouadni** [comment] 2020-11-24 09:06
Hello @ramwebkul 

Are you asking to have a select (**tax included** / **tax excluded**) for the **Percent (%)** like the **Amount**? 

![image](https://user-images.githubusercontent.com/23308427/100072435-889f7880-2e3c-11eb-85bd-512a00200056.png)

If so, what you suggested is an improvement and not a bug.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-14 15:37
Hello @ramwebkul ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-14 15:37 UTC
Labels: Improvement, BO, Cart rules, No change required, 1.7.6.8
