### ISSUE TITLE
1.7.8.7 Multistore probleme duplicate image

### ISSUE THREAD

**Issue by blawdi** [PrestaShop/PrestaShop#32903] opened 2023-06-14 08:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I'm encountering an issue on Prestashop 1.7.8.7 multistore. When I duplicate a product that has images and then remove the images from the duplicated version, I am no longer able to add any new images.

<p>350882139_1247128776162849_6802219340747274467_n.jpg: Error occurred while creating the additional image.</p>

I have to manually delete the entries in the "ps_image" table.

Could someone please confirm if this is a bug in the current version?

Thank you in advance.

On video : 
https://mega.nz/file/G80GiIwJ#t_5QdB8EQuAQpZzrD7jm4tl2BVVw0M_HkT2nqdUjQhg

### Steps to reproduce

Use 1.7.8.7 (i no test on another version)
Use Multistore with 2 shops
Duplicate product with img
Delete all img
Added new img 
= Error

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment] 2023-06-14 09:09
Hello @blawdi 

Your ticket is a duplicate of  [issue #10137]( https://github.com/PrestaShop/PrestaShop/issues/10137)
So, I close it.
Thanks!
Best regards.

**Comment by sallemiines** [comment] 2023-06-14 09:09
Duplicate of [#10137](10137)

**Closed as completed by sallemiines** 2023-06-14 09:09 UTC
Labels: Bug, Duplicate, Invalid
