### ISSUE TITLE
 SEO friendly url wrong example in preview box when adding new product

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14393] opened 2019-06-27 11:43 UTC
SEO friendly url wrong example in preview box when adding new product > tab SEO.

1) Add new product

2) Go to SEO tab of that product

3) It show's this in preview box admin 
<img width="712" alt="afbeelding" src="https://user-images.githubusercontent.com/2944981/60263665-8d779a00-98e1-11e9-9d78-2fb4a804b043.png">

**Comment by khouloudbelguith** [comment] 2019-06-27 12:01
Hi @sdwebdesign,

If you reload the page, it will be well displayed.
![image](https://user-images.githubusercontent.com/16067358/60264642-99f8f400-98db-11e9-855e-4f584d10c2ac.png)

Thanks to check & feedback.

**Comment by colinegin** [comment] 2019-07-11 09:59
Hello @khouloudbelguith, 
if i'm correct, this is a duplicate of this issue : https://github.com/PrestaShop/PrestaShop/issues/14054

There's a PR to fix this issue !

**Comment by khouloudbelguith** [comment] 2019-07-11 10:02
Hi @colinegin,

Yes, It is a duplicate.
@sdwebdesign, your ticket is a duplicate of #14054
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-11 10:03
Duplicate of #14054

**Closed as completed by khouloudbelguith** 2019-07-11 10:02 UTC
Labels: Bug, BO, Duplicate, SEO & URLs
