### ISSUE TITLE
public/preload.tpl does not exist in admin themes "default" or "new-theme"

### ISSUE THREAD

**Issue by wideline** [PrestaShop/PrestaShop#29181] opened 2022-07-27 09:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After a fresh install of the origin/develop branch, the admin fails with a smarty exception: cannot find file "admin-dev\themes\default\template\preload.tpl" being included from file "admin-dev\themes\default\template\header.tpl" at line 90

### Expected behavior

for the template file and parent directory to exist

### Steps to reproduce

Fresh install, go to admin

### PrestaShop version(s) where the bug happened

8/develop

### PHP version(s) where the bug happened

8.0.1

**Comment by zuk3975** [comment] 2022-07-27 13:37
command `make assets` seems to fix that

**Comment by sLorenzini** [comment] 2022-07-27 14:02
hello @wideline,

I couldn't reproduce your issue with fresh install on:
- Develop branch with PHP 7.3 & 8.1 version
- 8.0.x branch  with PHP 7.3 & 8.1 version

https://user-images.githubusercontent.com/2854834/181259538-ba3a17d2-ebc4-4b5f-bad6-9b93218e7d56.mp4

The file does not exist on those folders but admin has no errors.
Could you please provide us more precise details and a screenrecord to help you 🙏?

Thank you

**Comment by wideline** [comment] 2022-07-27 22:20
Thank you for responding. It was my error: the asset compilation failed and I skipped over it. Running ./tools/assets/build.sh fixed the issue. The error I was receiving prior to the fix is attached
![Screenshot 2022-07-28 073143](https://user-images.githubusercontent.com/1982357/181382396-0eb0e60d-4d26-4520-a0ef-4fd04dbf7c55.png)
.

**Comment by HanaRebaiQA** [comment] 2022-07-28 08:28
Hello @wideline 

Glad to hear that.
So, Closing this issue as it's not a Core bug.

Otherwise, if you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank You!

**Closed as completed by HanaRebaiQA** 2022-07-28 08:28 UTC
Labels: Bug, 8.0.x, BO, Administration, Invalid
