### ISSUE TITLE
500 Internal Server Error:  Undefined array key \"objectsNodeName\" when call /api/images/products/  with output_format=JSON

### ISSUE THREAD

**Issue by rafaterrerodistrisantiago** [PrestaShop/PrestaShop#34201] opened 2023-10-07 10:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

500 Internal Server Error:  Undefined array key \"objectsNodeName\" when call /api/images/products/  with output_format=JSON

Example: 
```
curl --location 'prestashop.XXXXXXXXX.es/api/images/products/7519?output_format=JSON' \
--header 'Authorization: Basic XXXXXXXXXXXX'
```

Response:
```
{
    "": [
        {
            "id": "7519"
        },
        {
            "id": 9501
        },
        {
            "id": 9502
        }
    ],
    "errors": [
        {
            "code": 3,
            "message": "[PHP Warning #2] Undefined array key \"objectsNodeName\" (/var/www/PrestaShop/classes/webservice/WebserviceOutputJSON.php, line 127)"
        },
        {
            "code": 3,
            "message": "[PHP Warning #2] Undefined array key \"objectsNodeName\" (/var/www/PrestaShop/classes/webservice/WebserviceOutputJSON.php, line 127)"
        },
        {
            "code": 3,
            "message": "[PHP Warning #2] Undefined array key \"objectsNodeName\" (/var/www/PrestaShop/classes/webservice/WebserviceOutputJSON.php, line 127)"
        },
        {
            "code": 61,
            "message": "This image does not exist on disk"
        }
    ]
}
```

### Expected behavior

No errors like when you choose XML format:

```
curl --location 'prestashop.XXXXXXXXX.es/api/images/products/7519?output_format=XML' \
--header 'Authorization: Basic XXXXXXXXXXXX'
```

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <image id="7519">
        <declination id="9501" xlink:href="https://prestashop.XXXXXXXXX.es/api/images/products/7519/9501"/>
        <declination id="9502" xlink:href="https://prestashop.XXXXXXXXX.es/api/images/products/7519/9502"/>
    </image>
</prestashop>
```

### Steps to reproduce

1.  Do a cURL to your Webservice choosing a product ID, in my case, product Id = 7519:
curl --location 'prestashop.XXXXXXX.es/api/images/products/7519?output_format=JSON' \
--header 'Authorization: Basic XXXXXXXXXXXXX'

2.  Check the response and you will find the error.

### PrestaShop version(s) where the bug happened

8.0 and 8.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

classes/webservice/WebserviceOutputJSON.php

**Comment by florine2623** [comment] 2023-10-09 13:56
Hello @rafaterrerodistrisantiago ,

I can't reproduce your exact issue.

<img width="484" alt="Screenshot 2023-10-09 at 15 55 44" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f1133cf7-bedd-4574-b840-e554fb27ac01">

> This image does not exist on disk


Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/15499 ?

Waiting for your feedback.

**Comment by rterrero** [comment] 2023-10-18 18:58
Yep. Same! But in Prestashop 8.1. Thanks @florine2623 !

**Comment by rafaterrerodistrisantiago** [comment] 2023-10-18 18:59
Yep! Same issue, but in Prestashop 8.1. Thanks @florine2623 !

**Comment by florine2623** [comment] 2023-10-25 09:06
Ok, I'm closing this one to avoid clogging the backlog then.
You can follow the updates via https://github.com/PrestaShop/PrestaShop/issues/15499.

Thanks

**Closed as completed by florine2623** 2023-10-25 09:06 UTC
Labels: Bug, WS, Duplicate, Image, Webservice, 8.1.x
