### ISSUE TITLE
No PDF reader can display and print Russian currency sign. I get rectangles instead

### ISSUE THREAD

**Issue by AndreyOgleznev** [PrestaShop/PrestaShop#19880] opened 2020-06-20 10:30 UTC
After updating Prestashop to version 1.7.6.5  "₽" character started to be used instead of "RUB". It's correctly displayed in both back and front offices but not in the Prestashop generated pdf invoices. I tried to open the invoice with the actual versions of Adobe Acrobat Reader, Foxit PDF Viewer, Google Chrome Browser, MS Edge, Yandex Browser, etc. No luck. If I copy the rectangle and paste it into MS Word document it's displayed correctly. If I convert the file into MS Word document it's displayed correctly as well.

1. Go to any order record paid in Russian Rubles as currency
2. Click on 'View invoice' button and download it
3. Open the file in a pdf viewer
4. See rectangles instead of "₽" symbol as on the screenshot attached

* PrestaShop version: 1.7.6.5
* PHP version:  7.3.17
![2020-06-20_14-23-14](https://user-images.githubusercontent.com/11665990/85199617-ff6e9d80-b301-11ea-834f-1c260861e5f8.png)

**Comment by sarahdib** [comment] 2020-06-23 07:03
Hello @AndreyOgleznev 

I was able to reproduce the issue with PrestaShop version 1.7.6.5
<img width="768" alt="Capture d’écran 2020-06-23 à 08 53 07" src="https://user-images.githubusercontent.com/3034677/85371345-5c4f9b00-b530-11ea-91e1-f5098392a7b7.png">
And 1.7.7.0
<img width="759" alt="Capture d’écran 2020-06-23 à 08 58 44" src="https://user-images.githubusercontent.com/3034677/85371365-640f3f80-b530-11ea-8ff5-a58bc720d8ca.png">

In 1.7.5.0 the currency sign is "RUB"
<img width="761" alt="Capture d’écran 2020-06-23 à 09 07 38" src="https://user-images.githubusercontent.com/3034677/85372000-76d64400-b531-11ea-8d76-b59e712ae4a6.png">


I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you!

**Comment by LouiseBonnard** [comment] 2020-06-23 10:04
Hi there, thanks for your feedback, it is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9817 & #12308 so I close this ticket in order to all focus on the same issue. :-)

**Closed as completed by LouiseBonnard** 2020-06-23 10:04 UTC
Labels: Bug, Minor, BO, Duplicate, Invoices, Currencies, Regression, Fixed, 1.7.7.0, 1.7.6.5
