### ISSUE TITLE
String given to get_parent_class() not accepted with PHP 8

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27978] opened 2022-03-19 12:43 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the develop branch, if you check the Modules Manager, there is this error:
<img width="1075" alt="Capture d’écran 2022-03-19 à 13 42 07" src="https://user-images.githubusercontent.com/2631425/159121519-7ce061f5-0a23-4f83-8a55-7f56573ce0d2.png">

The used function (`get_parent_class()`) doesn't no more allow a string as the first param with PHP8.

### Steps to reproduce

1. Get the develop branch
2. Use PHP8
3. Go to Modules Manager

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0.15

**Comment by khouloudbelguith** [comment] 2022-03-21 16:57
Hi @PrestaEdit,

I did not manage to reproduce the issue with PHP8.0.14 using the develop branch.
I attached a screen record

https://user-images.githubusercontent.com/16067358/159320795-13ad8671-18da-454c-a63c-a766f3ee5f49.mp4

Thanks to check and feedback

**Comment by atomiix** [comment] 2022-03-25 13:53
This should be solved by #27632 ;)

**Comment by hibatallahAouadni** [comment] 2022-04-11 12:12
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-04-11 12:12 UTC
Labels: Bug, 8.0.x, BO, Modules, Module manager, php, Invalid
