### ISSUE TITLE
Notice on module statscheckup due to missing translation array key

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#11761] opened 2018-12-13 10:53 UTC
**Describe the bug**
Notice of undefined index on translation array due to https://github.com/PrestaShop/statscheckup/commit/59eec4b40066e381427d509e3305b8380c6fad71#diff-f58ed5b03c11808ab9cde28a3b39a97bR159

**To Reproduce**
1. Enable debug mode
2. Go to backoffice
3. Click on Stats
4. Click on Catalog evaluation
5. See error

**Screenshots**
![issue-statscheckup](https://user-images.githubusercontent.com/5262628/49933681-91efde80-fecc-11e8-9b1c-40010dc7ae29.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2018-12-13 10:56
Hi @Matt75,

This issue is added to our bug roadmap.
Your ticket is a duplicate of #9643
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-13 10:56
Duplicate of #9643

**Closed as completed by khouloudbelguith** 2018-12-13 10:56 UTC
Labels: Duplicate
