### ISSUE TITLE
BUG ON MY ADMINISTRATOR PLATFORM PRESTASHOP

### ISSUE THREAD

**Issue by mnahygiene** [PrestaShop/PrestaShop#11013] opened 2018-10-15 13:31 UTC
Hello,
There are many bugs on my Prestashop administrator platform. I have to wait for long minutes to go from one section to another.
Can you help me and fix my problem please?
![capture d ecran 2018-10-15 a 15 31 08](https://user-images.githubusercontent.com/44167151/46953890-6056c480-d08f-11e8-8fc9-cb447a45aa5e.png)

**Comment by khouloudbelguith** [comment] 2018-10-15 13:37
Hi @mnahygiene,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-16 11:10
Hi @mnahygiene,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-16 11:10 UTC
Labels: No change required
