### ISSUE TITLE
The frontend does not assume the ordering of the categories

### ISSUE THREAD

**Issue by josejecas** [PrestaShop/PrestaShop#14070] opened 2019-06-04 12:50 UTC
The frontend does not assume the ordering of product categories as shown in the video

https://drive.google.com/file/d/1U9meBPQ74IWOceus8LSfYskm7T84PFyM/view

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-04 13:04
Hi @josejecas,

I manage to reproduce the issue PS1.7.5.2 & PS1.7.6.0beta.
In the PS1.7.5.2, in the BO => categories page => change positions => a green alert is displayed => if we reload the page => settings not saved
In the PS1.7.6.0, in the BO => categories page => change positions => there is no green alert displayed => if we reload the page => settings not saved too.
https://drive.google.com/file/d/17GonAIN0Bwu9G24QRnYhCOcPTA4feni8/view
In the ps_categorytree configuration page, we have sort by position
![image](https://user-images.githubusercontent.com/16067358/58881616-6c50ce80-86d2-11e9-9334-7fc2b9d5c32a.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2019-06-06 14:14
@khouloudbelguith 

I can't reproduce this issue with 1.7.6.x branch

https://drive.google.com/file/d/1JMpnKb4vZvmeucRd01RuGWvj0mRJcYuV/view?usp=sharing

**Comment by khouloudbelguith** [comment] 2019-06-11 10:34
Hi @marionf,

Thanks for your feedback.
Yes, with branch 1.7.6.x => it is OK.
https://drive.google.com/file/d/1mFP4WJU5G_mmqnbq_9PiqBZ-WdvoYest/view
I will close the issue since it is fixed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-11 10:34 UTC
Labels: Bug, Minor, BO, Can't reproduce, Categories, migration, Category tree, 1.7.5.2
