### ISSUE TITLE
ServiceNotFoundException - error 500 Admin Panel

### ISSUE THREAD

**Issue by w3bdesigne** [PrestaShop/PrestaShop#32089] opened 2023-04-08 07:05 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I added a missing translation to emails subject and click save, I can't go to enter the Admin Panel. Front works fine but in Backoffice I got message HTTP 500 Internal Server Error and when I check in debug mode, I have this information:

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber".

at /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:83)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:83)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:83)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:83)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:83)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:94)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() l/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:83)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:47)

at Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:40)

at Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:94)

at Symfony\Component\DependencyInjection\Compiler\Compiler->compile() (/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:762)

at Symfony\Component\DependencyInjection\ContainerBuilder->compile() (/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:594)

at Symfony\Component\HttpKernel\Kernel->initializeContainer() (/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:136)

at Symfony\Component\HttpKernel\Kernel->boot() (/public_html/app/AppKernel.php:84) at AppKernel->boot() (/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:196)

at Symfony\Component\HttpKernel\Kernel->handle() (//public_html/admin169xk/index.php:81)
```

Does anyone know how to fix this error? 

### Steps to reproduce

When I added a missing translation to emails subject and click save, I can't go to enter the Admin Panel. Front works fine but in Backoffice see error Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber".

### PrestaShop version(s) where the bug happened

 8.0.1

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2023-04-12 08:25
Hello @w3bdesigne 

Thanks for your patience!
Could you please provide a screen record :pray: cause with the provided infos I couldn't reproduce the issue :disappointed: 
Waiting for your feedback.

Thanks!

**Comment by florine2623** [comment] 2023-05-03 07:42
Hello @w3bdesigne ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-05-03 07:42 UTC
Labels: Bug, BO, Translations, Email, Invalid, 8.0.1
