### ISSUE TITLE
[IMPROVEMENT] Detect asset changes and cache CSS & JS again

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17728] opened 2020-02-19 08:46 UTC
Hi guys, would it be possible for Prestashop to detect changes in assets and redo the CCC again? It used to work that way in 1.6.

Now, everytime I change something in CSS, I either have to go to admin and clean the cache OR I have to delete assets/cache folder.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-19 09:08
Hi @Hlavtox,

Thanks for your report.
Isn't similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/10091?

Thanks!

**Comment by Hlavtox** [comment] 2020-02-19 09:10
@khouloudbelguith Maaaaaybe, can you include it to the post's description?

There is only: "CCC will probably need some attention (either make it better or remove it)"

**Comment by khouloudbelguith** [comment] 2020-02-19 09:14
@Hlavtox, I updated the previous issue.
I will close this ticket.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-19 09:14
Duplicate of #10091

**Comment by Hlavtox** [comment] 2020-02-19 09:14
@khouloudbelguith Thank you! :-)

**Closed as completed by khouloudbelguith** 2020-02-19 09:14 UTC
Labels: Improvement, Duplicate, Performance
