### ISSUE TITLE
Contact form on frontend does not send email (BO ok)

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#22412] opened 2020-12-14 16:00 UTC
Try to send an email from contactform page result in 2 scenario:

1) red error message ('An error occurred while sending the message') and email are not sent
2) green ('Your message has been correctly sent') but email are not sent the same

email config test in Back office work with no problem , we use custom smtp and email are right send to test email adress.

Have your own test ^^ : https://www.sixrace.it/it/contattaci

Debug mode does not show error, web server log file does not record message.

PS 17.6.1
PHP 7.2
APACHE

**Comment by matteolavaggi** [comment] 2020-12-14 16:14
Just because i'm in trouble to have contact email from customer i'm tring the customer thread function .. and ... not work -_-
Try to reply from customer support section of BO send an email to customer with a link for open a "customer thread" discussion. The link does nothing, simply redirect customer to front end contac page. Not bad ^^

**Comment by PululuK** [comment] 2020-12-14 16:21
Hi @matteolavaggi 

Can you check your contact form module config please ?

![image](https://user-images.githubusercontent.com/16455155/102106248-a014c480-3e30-11eb-8815-902b97bce95f.png)

**Comment by matteolavaggi** [comment] 2020-12-14 16:25
The setting is configured like your picuture, btw this cant trow an error i think.
Try to update to last version, manual paste the last release code in the php file. No way to have an error that can be undestood , and module does not send email from 4 days. 
we have not updated anything or installed module. Simply changed back office contact page detail (store details).

**Comment by PululuK** [comment] 2020-12-14 16:25
What version of contact form module are you using?

**Comment by matteolavaggi** [comment] 2020-12-14 16:26
I've the last git code release now, BO modules show 4.3.0

**Comment by hibatallahAouadni** [comment] 2020-12-14 16:30
Hello @matteolavaggi 

I didn't manage to reprodcue your issue with PS1.7.6.1, please check the attached screen record below:

https://drive.google.com/file/d/1trLU-HFKxp-UvFCL9F3KdCbZrD5Pvv8u/view

So, could you please check your Email setting in BO > CONFIGURE > Advanced Parameters > E-mail

![image](https://user-images.githubusercontent.com/23308427/102106906-6e502d80-3e31-11eb-9543-fef4f209341b.png)

Please check and feedback.

Thanks!

**Comment by matteolavaggi** [comment] 2020-12-14 16:33
Hi dear, i've check it again, but you can read above that in back office the test email function work, send email with no problem:
![image](https://user-images.githubusercontent.com/24798703/102107867-81afc880-3e32-11eb-981f-3c9db2aa199f.png)

Using real email result in real message received.

**Comment by PululuK** [comment] 2020-12-14 16:41
@matteolavaggi  This can be related to your theme.
Could you check if you have these lines in your theme :
(/themes/YOUR_THEME_NAME/modules/contactform/views/templates/widget/contactform.tpl)

https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/modules/contactform/views/templates/widget/contactform.tpl#L123-L129

**Comment by matteolavaggi** [comment] 2020-12-14 16:59
My template is classic theme and the code is exactly the same, there is no way to get an error with specific information ?

**Comment by matteolavaggi** [comment] 2020-12-16 10:16
So we have a record, the first ecommerce without a simple working contact form in 2021 ^^!

**Comment by matks** [comment] 2020-12-16 10:20
@matteolavaggi Hello, the last message is passive-aggressive and is against our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)

"Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members"

Please stop using passive-aggressive statements.

The contact form on your shop is not working. It does not mean every contact forms on the 300,000 shops running thanks to PrestaShop are broken.

**Comment by PululuK** [comment] 2020-12-16 10:21
> So we have a record, the first ecommerce without a simple working contact form in 2021 ^^!

It's nice 🎉 !  But we are still in 2020 😉

@matteolavaggi can you show me your mail params please ?

![image](https://user-images.githubusercontent.com/16455155/102335888-c487b280-3f90-11eb-8592-91156778c383.png)

**Comment by matteolavaggi** [comment] 2020-12-17 10:41
> > So we have a record, the first ecommerce without a simple working contact form in 2021 ^^!
> 
> It's nice 🎉 ! But we are still in 2020 😉
> 
> @matteolavaggi can you show me your mail params please ?
> 
> ![image](https://user-images.githubusercontent.com/16455155/102335888-c487b280-3f90-11eb-8592-91156778c383.png)

This is funny ^^ btw you ask to me what i've just confirmed to @hibatallahAouadni  (and what i've just write in the opening bug report) , email WORK on back office:

![image](https://user-images.githubusercontent.com/24798703/102477253-688a6000-405c-11eb-8125-d1dc25b91af8.png)

Here the configuration (that works on BO)
![image](https://user-images.githubusercontent.com/24798703/102477376-8fe12d00-405c-11eb-8dbb-ee93bbc30e12.png)

Usign php result in same errore, Front Office trow an error.

PS @matks You are right, forgive me if it seems absurd to me that a basic function such as a contact form can stop working on an ecommerce, it seems that some pieces are missing such as the management of conversations that does not work and yet is also integrated in the new releases of the module

**Comment by hibatallahAouadni** [comment] 2020-12-24 16:23
Hello @matteolavaggi 

We have been asking you again and again about these details cause we didn't manage to reproduce your issue :confused:
That's weird that in BO the test mail works but in FO it doesn't.
Could you please provide some details to reproduce your issue.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-13 09:23
Hello @matteolavaggi ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-13 09:23 UTC
Labels: Bug, FO, No change required, Contactform, 1.7.6.1
