### ISSUE TITLE
Theme & Logo page 'Explore more' card design have scroll on small screen

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#14602] opened 2019-07-12 04:01 UTC
**Describe the bug**
Please check the screenshot

**To Reproduce**
1. Go to 'Design -> Theme & Catalog' page
2. You can see the scroll as in the screenshot for normal screen

**Screenshots**
![download (2)](https://user-images.githubusercontent.com/19220745/61101532-beca9b00-a487-11e9-802b-b0b0cfe77b2a.png)

This should have a proper responsive small card for a small screen.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7

**Comment by khouloudbelguith** [comment] 2019-07-12 08:27
Hi @dheerajwebkul,

With a window size is more than 1149px * 928px, There is no scroll.
![image](https://user-images.githubusercontent.com/16067358/61113906-259b8480-a487-11e9-8aa8-f274835c96da.png)

What is the exact size of your window?

Thanks!

**Comment by dheerajwebkul** [comment] 2019-07-12 08:49
Hello @khouloudbelguith ,

My window size is 1301x591
But its occurs sometimes because 'Live from PrestaShop Addon' block appears in the right side,
As you can see the above screenshot the left block has spaces that's why card have scroll.

It comes sometimes only.

![AwesomeScreenshot-download-2-2019-07-12-14-07-98](https://user-images.githubusercontent.com/19220745/61115414-06651d00-a4b0-11e9-97fb-e7209e86c315.png)

**Comment by khouloudbelguith** [comment] 2019-07-12 08:57
@dheerajwebkul, I did not manage to reproduce this issue (white space).
![image](https://user-images.githubusercontent.com/16067358/61115780-1ae2ee80-a48b-11e9-893f-1be557ac5d18.png)

But it seems to be similar to this issue: #14301 which is fixed with this PR: #14401. 
Did you use the last version PS1.7.6.0?

Thanks!

**Comment by dheerajwebkul** [comment] 2019-07-12 10:08
@khouloudbelguith 

Yes, I have tested it on PS1.7.6.0.

Currently, I can not also reproduce also sometimes it comes only.

**Comment by khouloudbelguith** [comment] 2019-07-12 10:14
@dheerajwebkul, I tried with the http://demo.prestashop.com/#/en/back & it is OK.
Thanks!

**Comment by mariem-abid** [comment] 2019-08-13 07:41
Hi @dheerajwebkul,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by mariem-abid** 2019-08-13 07:41 UTC
Labels: BO, Can't reproduce, Theme & logo, 1.7.6.0
