### ISSUE TITLE
Filter products by the stock of matched variants, not just any of them

### ISSUE THREAD

**Issue by darioesposito** [PrestaShop/PrestaShop#18848] opened 2020-04-27 15:18 UTC
#### Is your feature request related to a problem?

I'm always frustrated when you choose a specific filter, in my case Size 40 and he shows up all the product with the size 40 but also that there are not avialable for purchase. This is confucing the customer

#### Steps to reproduce
- In module Faceted Search, choose option “Show unavailable, out of stock last” to NO
![Capture d’écran 2020-04-30 à 14 26 22](https://user-images.githubusercontent.com/1784781/80737986-a14ce780-8b14-11ea-9df6-6ae378d02d87.png)

- On product, put stock at 0
- Go to front-office, go to the category linked to the product
- See that product with no stock is displayed
Here’s the screen record :
https://drive.google.com/file/d/1qDQ3vLlP-6ph1ZMnQyX2dy9v7Kscf5fB/view

#### Describe the solution you'd like

A like a simple solution, when you choose a filter it's show you only the product with that filter but avialable for purchase.

#### Alternatives you've considered

Nothing at the moment

#### Additional context

Nothing

**Comment by sarahdib** [comment] 2020-04-28 06:59
Hello @darioesposito 

Thank you for your feedback.

In the last version of the module there is an option to display unavailable or out of stock in the last position.

**Comment by darioesposito** [comment] 2020-04-28 17:40
> Hello @darioesposito
> 
> Thank you for your feedback.
> 
> In the last version of the module there is an option to display unavailable or out of stock in the last position.

Hi sarahdib

Thanks for you reply, where i can find this module option?

I don't know if i explain my problem with consistence, i made another real actual example:

Now i have 8 pants with their combinations and i have 20 size (40 to 60) i have now only 48 avialable for purchase and the other is to 0 quantity and not aviabilable for purchase.

When in my list product page i select the filter size for example 42, prestashop show me up all the 8 products but i  dont't need this, i need to show up only the aviable size product i selected.

Sorry for my bad english, hope you helping me

Thanks,

Cheers

**Comment by florine2623** [comment] 2020-04-30 12:28
Hi @darioesposito ,

In you module **ps_facetedsearch**, you can choose the option no hide combinations that are out-of-stock : 
![Capture d’écran 2020-04-30 à 14 26 22](https://user-images.githubusercontent.com/16019289/80710268-d8a89d80-8aee-11ea-84b7-a0ee12ec1515.png)

Thanks!

**Comment by darioesposito** [comment] 2020-04-30 13:17
> Hi @darioesposito ,
> 
> In you module **ps_facetedsearch**, you can choose the option no hide combinations that are out-of-stock :
> ![Capture d’écran 2020-04-30 à 14 26 22](https://user-images.githubusercontent.com/16019289/80710268-d8a89d80-8aee-11ea-84b7-a0ee12ec1515.png)
> 
> Thanks!

Hi,

I activate it now that but nothing work, if you wanna try go to www.briglia1949.com/it/shop-2 and filter by size (in italian Taglia) for example 42 and you still see all the products, but at the moment i have only 48 size avialiable with combinations but if you can filter by other size you still see all the 8 products...

I don't understand how i can show only the product disponibility with specific filter 
I have only 8 products now with combinations.

With this option seams nothing work

Thanks

**Comment by florine2623** [comment] 2020-04-30 16:30
Thank you for the details.
Indeed I could reproduce your issue on both 1.7.5.2, 1.7.6.5 and 1.7.7. This is a bug.
I will let our team of developer know about this issue !
Thanks!

**Comment by marionf** [comment] 2020-04-30 18:25
Hello @darioesposito your issue is a duplicate of #16952
Please follow and comment on this issue if needed

**Comment by marionf** [comment] 2020-04-30 18:25
Duplicate of #16952

**Closed as completed by marionf** 2020-04-30 18:25 UTC
Labels: Bug, Minor, FO, Duplicate, Faceted search, 1.7.5.2, 1.7.7.0, 1.7.6.5

**Comment by darioesposito** [comment] 2020-04-30 18:31
> 
> 
> Thank you for the details.
> Indeed I could reproduce your issue on both 1.7.5.2, 1.7.6.5 and 1.7.7. This is a bug.
> I will let our team of developer know about this issue !
> Thanks!

Thank you very much and thanks the developer team for all the work they do!  i hope they fix that very soon cause it's very frustrating for customer see, after filtering, products not avialable for purchase!  i just reading the other post #16952 and i agree with @Twabi2 user. 

P.s Talking about filtering on List Products with Combinations Products and 1.7.6

**Comment by darioesposito** [comment] 2020-04-30 18:34
Hi all,

I now see the video attached to my thread question, the problem is i don't have the quantity field because i use combinations products, and if i set in combinations stock to 0 they still see after applying the filter the unavialable products on list page

Thanks

**Comment by superskyman100** [comment] 2020-05-07 09:44
Hello, we have exactly the same problem, the option ''do not show unavailable products'' isn't working.  We have unavailable variants, they always show up with the filter. Very bad for customers experience. 
PS 1.7.6.4
Faceted Search 3.5.0

**Comment by darioesposito** [comment] 2020-05-07 09:48
> 
> 
> Hello, we have exactly the same problem, the option ''do not show unavailable products'' isn't working. We have unavailable variants, they always show up with the filter. Very bad for customers experience.
> PS 1.7.6.4
> Faceted Search 3.5.0

Hi,

Yep, i think i a kind of a bug or somenthing like that. I hope they fix soon cause in my shop miss only this thing and it's ready and perfect! so big up for developers to fix this as soon as possible. 

If it's not a problem we keep up this thread under the "big eye" of the support and developers admin, because i think a lot of people facing this problem too.

I have PS 1.7.6.3

Thanks,
