### ISSUE TITLE
AdminOrders displays wrong prices (ignores PS_ROUND_TYPE value Order::ROUND_LINE)

### ISSUE THREAD

**Issue by rmilecki** [PrestaShop/PrestaShop#17365] opened 2020-01-27 07:00 UTC
**Describe the bug**
BO doesn't respect `PS_ROUND_TYPE` when displaying products table in order view. In `_product_line.tpl` there is
```
Tools::ps_round($product_price, 2) * ($product['product_quantity']
```
used which matches `Order::ROUND_ITEM` only. When using `Order::ROUND_LINE` BO user sees different prices than FO customer.

**To Reproduce**
1. BO: Set `PS_ROUND_TYPE` ("Round type") to `Order::ROUND_LINE`
2. BO: Create product with VAT rate 8% and gross price (VAT included) `5.415`
3. FO: Add 10 units of that product to a cart & place an order. Total price will be<br>5.013889 * 10 * 1,08 ~= 54,15
4. BO: Open order & check prices in products table

**Screenshots**
FO:
![fo](https://user-images.githubusercontent.com/452972/73155424-fa9f1800-40da-11ea-96a0-595d1e6052fb.png)
BO:
![bo](https://user-images.githubusercontent.com/452972/73155447-fd9a0880-40da-11ea-8005-1c6672b5caae.png)

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-01-27 10:20
Hi @rmilecki,

We have a different rounding problem, it is an issue that should be specified & fixed by our developers.
We are aware of this issue.
Your ticket is a duplicate of #9779
Please follow: https://github.com/PrestaShop/PrestaShop/issues/9779#issuecomment-415125166
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-27 10:20
Duplicate of #9779

**Closed as completed by khouloudbelguith** 2020-01-27 10:20 UTC
Labels: Duplicate
