### ISSUE TITLE
pdf invoice in customer page isn't create

### ISSUE THREAD

**Issue by Amiga500** [PrestaShop/PrestaShop#28255] opened 2022-04-13 15:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The invoice from the admin control works and generates a PDF while if I go to the history details of the customer page (not guest) and click on invoice pdf or details it ends up in "The page you are looking for was not found."??

 

using Prestashop 

### Steps to reproduce

1. Create an order 
2. go to customer page and click on the invoice pdf

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-04-13 16:09
Hello @Amiga500 

I didn't reproduce your issue with PS1785 😞 
Could you please enable the debug mode and provide screen record 🙏 

Waiting for your feedback.
Thanks!

**Comment by FF27** [comment] 2022-04-14 04:04
Actually I have the same error here, same version and same PHP 7.4 ... in debug mode nothing appear.
It looks like from the admin mode it is linking to a token to download the PDF but from the customer page instead not.

For example from the client control panel  --- > index.php?controller=pdf-invoice&id_order=6

---> page not found (404)

From the admin control panel  --- > admin/index.php/sell/orders/6/generate-invoice-pdf?_token=Gew6KVOufaUfoms9ig23IMj4MLo2MH_23jsQQG35EcA

---> download correctly the invoice .

Same as per oder details on the customer history order page... (not found)

For me looks like there is something missing inside the page code of the client side like a tokenizer to access the PDF itself? not sure about it and where can I modifiy eventually the code

**Comment by khouloudbelguith** [comment] 2022-04-14 08:16
Hi @Amiga500,

I did not manage to reproduce the issue with PS1785 using php7.4
I attached a screen record

https://user-images.githubusercontent.com/16067358/163343484-da030c15-60c8-4fb1-bd48-79abbfcf7f44.mp4

Thanks to check and feedback.

**Comment by FF27** [comment] 2022-04-14 08:57
@khouloudbelguith 

https://user-images.githubusercontent.com/19433897/163350859-4aa6ffb7-286a-46e2-a0d5-59d5e28a33f1.mp4


This for clicking on PDF and details respectively

**Comment by khouloudbelguith** [comment] 2022-04-14 09:46
@FF27, could you please provide me a screenshot from BO > Shop Parameters > Traffic & SEO page >  Schema of URLs  section

![image](https://user-images.githubusercontent.com/16067358/163359806-bc5f26f4-3984-4a43-9e2b-a070347b4722.png)

Thanks!

**Comment by FF27** [comment] 2022-04-14 10:43
<img width="754" alt="ddssd" src="https://user-images.githubusercontent.com/19433897/163374118-0c11afb7-5aff-412a-bbb4-31710f859e10.png">

**Comment by FF27** [comment] 2022-04-14 10:44
I upgraded recently with the module 1-click-upgrade.
probably is better i remove everything and installing there just the last version?

**Comment by FF27** [comment] 2022-04-14 11:08
i tried to toally remove the prestashop directory and installing a totally new one with :

fetch https://download.prestashop.com/download/releases/prestashop_1.7.8.5.zip

same exact problem!!!


https://user-images.githubusercontent.com/19433897/163379262-f5344522-9a87-41b2-a638-05b374ae0be4.mp4


clicking on PDF and details give the exact same result as before

**Comment by FF27** [comment] 2022-04-14 11:22
tried with 1.7.8.4 -- SAME!

it goes in 404!!!

**Comment by khouloudbelguith** [comment] 2022-04-14 11:33
@FF27, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration: screenshot from BO > Advanced Parameters > Information page
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log


Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by FF27** [comment] 2022-04-15 12:03
Actually is not a Prestashop bug. It was the misconfiguration of the default NGINX one that is on the prestashop website!

Changing all the rewrites inside the server block did the trick, now it works!

    # [EDIT] If you are using multiple languages.
    # rewrite ^/fr$ /fr/ redirect;
    # rewrite ^/fr/(.*) /$1;

       rewrite ^/([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$1$2$3.jpg last;
       rewrite ^/([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
       rewrite ^/([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
       rewrite ^/([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
       rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
       rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
       rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
       rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg la>
       rewrite ^/c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ /img/c/$1$2$3.jpg last;
       rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ /img/c/$1$2.jpg last;
       rewrite ^/[a-zA-Z][a-zA-Z]/index.php(.*)$ /index.php$1;

  # Force pdf files to be downloaded
    location ~* \.pdf$ {
    add_header Content-Disposition Attachment;
    add_header X-Content-Type-Options nosniff;
    }

**Comment by Amiga500** [comment] 2022-04-15 12:47
Hi @khouloudbelguith,
sorry a lot for the delay, i used NGINX too, and i confirm that with rewrite, all is working nice now!

**Comment by HanaRebaiQA** [comment] 2022-04-15 12:51
Hello @Amiga500 

Thanks for your feedback!
I'll close this issue as it's not a Core bug.

Otherwise, if you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you!

**Closed as completed by HanaRebaiQA** 2022-04-15 12:51 UTC
Labels: Bug, FO, Order, Invoices, Invalid
