### ISSUE TITLE
BO - Product V2 - combinations - when searching for combinations the attributes are not well displayed and an error is displayed in the console when selecting an attribute

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25592] opened 2021-08-12 16:37 UTC
#### Describe the bug
In the BO > Catalog > Product V2, when we try to regenerate some combinations, the attributes are not well displayed and an error is displayed in the console when selecting an attribute

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Experimental Features page
2. Enable Experimental product page
3. Go to BO > Catalog > Products page and add a product V2 with combinations
4. In the combinations Tab > Click on "Generate combinations"
5. Search for attributes for example `Color`
6. See error 
![image](https://user-images.githubusercontent.com/16067358/129234400-f7fde5c0-fd4d-45dd-a506-a3e3c932bed6.png)
7. Select an attribute > an error is displayed in the console 
![image](https://user-images.githubusercontent.com/16067358/129234479-d2e05319-6417-491f-8263-7dfbbfc70004.png)

#### Additional information

* PrestaShop version: 1.7.8.0rc1build2
* PHP version: 7.2

**Comment by NeOMakinG** [comment] 2021-09-13 13:47
@khouloudbelguith I can't reproduce, closing it, feel free to open it again if you reproduce it

**Closed as completed by NeOMakinG** 2021-09-13 13:47 UTC
Labels: Bug, Minor, BO, Combinations, Fixed, Front-end, 1.7.8.0
