### ISSUE TITLE
Module translations with different languages

### ISSUE THREAD

**Issue by margud** [PrestaShop/PrestaShop#30085] opened 2022-10-21 09:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If module has few different languages translated it will auto-fill missing fields with default language.
For example if default BO lang is set to NL and we try to translate the LT one, the missing LT fields will be filled with the filled NL fields. As I understand it should stay empty, because its hard to find missing fields for LT lang if the missing ones are filled with other lang.
![image](https://user-images.githubusercontent.com/51944825/197165969-c22f41fd-ce88-449d-b8f8-29165ff634c8.png)

### Expected behavior

If the translations are missing for the selected lang it should stay missing and not filled with default BO lang translations

### Steps to reproduce

1. Select any module that you want to test
2. Translated selected language, for example Netherlands.
3. Change BO language to Netherlands (profile->language)
4. Try to translate same module in Lithuanian language (can use any other language)
5. If the translation doesn't exist in Lithuanian but exists in Netherlands it will be filled with Netherlands translations

### PrestaShop version(s) where the bug happened

1.7+

**Comment by hibatallahAouadni** [comment] 2022-10-27 10:59
Hello @margud 

It seems your issue is related to this one #29316
Could you please check it and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-11-11 13:40
Hello @margud 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by margud** [comment] 2023-01-06 12:15
Sorry for delay. No its not related to #29316 issue. As added in description the issue is that the translations are filled from default language if they are missing and its really easy to save wrong translations on different languages because of this.

**Comment by florine2623** [comment] 2023-01-06 16:42
Hello @margud ,

I have reproduced your issue for any native module.

It seems like your issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/27351
I will update it, and you can subscribe to it, so it won't clog the backlog.

Thanks!

**Closed as completed by florine2623** 2023-01-06 16:42 UTC
Labels: Bug, BO, Duplicate, Modules, Translations, PR available, Invalid

**Comment by hibatallahAouadni** [comment] 2023-01-06 17:55
Duplicate of #27351
