### ISSUE TITLE
Faceted search resust is not shown after back to the product list

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#16951] opened 2019-12-29 12:47 UTC
**Describe the bug**
If in the Facetedsearch is cheked one or more brands and I visit the choosen product page and return back the list of product is not sorted accordanly to the chosen brand in the filter. I see the whole list despite the check box with brand is still choosen
![image](https://user-images.githubusercontent.com/50954519/71557101-1e266280-2a4a-11ea-8100-9b9b97bd5cb3.png)

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-12-30 11:25
Hi @photinia73,

I did not manage to reproduce the issue with PS1.7.6.2 & ps_facetedsearch v3.4.0.
I attached a screen record
https://drive.google.com/file/d/1loXXEtsXWGFe6u8OHi_8EfnLiYAkzJnO/view
What is the exact version of the ps_facetedsearch & PrestaShop did you use?

THanks!

**Comment by photinia73** [comment] 2019-12-30 11:30
Presta 1.7.5.2
Faceted the latest update vershion 3.4.0

пн, 30 груд. 2019, 13:25 користувач khouloudbelguith <
notifications@github.com> пише:

**Comment by photinia73** [comment] 2019-12-30 11:35
P.s. But I use non classic theme...

пн, 30 груд. 2019, 13:29 користувач Светлана Кричмаровская <
photinia73@gmail.com> пише:

**Comment by khouloudbelguith** [comment] 2019-12-30 11:47
@photinia73, As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment] 2020-01-29 07:41
Hi @photinia73,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-29 07:41 UTC
Labels: Bug, FO, Faceted search, No change required
