### ISSUE TITLE
Payment and Shipping backend gateway error

### ISSUE THREAD

**Issue by channeld** [PrestaShop/PrestaShop#11414] opened 2018-11-15 22:14 UTC
I have PS 1.7.3.3
All in backend work fine except when clicking to:
A. Payment Methods and Payment Preferences
B. Shipping Preferences
C. Shipping Carriers

Backend shows like loading forever and eventually shows a gateway error.

I tried turning off overrides and non-PS modules. Nothing. Cleaned cache, etc. Still nothing.
All max limits and memory settings are top.

Can't figure out what is going on.

All other things in the site work fine. I read about a .json solution here and I pasted the code into composer.json. This fixes the Shipping Preferences and I can go into that but all other don't work.

Help is needed.

**Comment by khouloudbelguith** [comment] 2018-11-16 07:39
Hi @channeld,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by channeld** [comment] 2018-11-16 09:54
Hi. Thank you for your prompt reply.

Here they are.
Server information Linux #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64
Server software version: Apache
PHP version: 5.6.38
Memory limit: 256M
Max execution time: 600
Upload Max File size: 25M

Database information
MySQL version: 10.1.37-MariaDB
MySQL server: localhost
MySQL engine: InnoDB
MySQL driver: DbPDO

allow_url_fopen = On
allow_url_include = Off
asp_tags = Off
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 600
max_input_time = 60
max_input_vars = 10000
memory_limit = 256M
post_max_size = 128M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php56"
upload_max_filesize = 25M
zlib.output_compression = Off
register_globals = Off
magic_quotes_gpc = Off
allow_url_include = Off

PS version: 1.7.3.3

Debug report: Shows no bugs

PHP error log: Shows no errors

apache error log: No errors

I am not sure what to add as a screenshot. The thing is thatI get 504 gateway error when I click only in these specific sections of admin and nowhere else. Other than that the site works perfect but I can't set Payment and Shipping Options.

**Comment by khouloudbelguith** [comment] 2018-11-16 09:57
Hi @channeld,

Did you use any custom carrier module?
Thanks!

**Comment by channeld** [comment] 2018-11-16 10:02
I have 2 modules uploaded
1. Is DHL module (through Prestashop)
2. FAN courier module provided by them.

But the problem is with Payments section too.

**Comment by channeld** [comment] 2018-11-16 10:03
I deactivated the modules but nothing. same error.

**Comment by channeld** [comment] 2018-11-16 10:08
I also saw this (near the end) but don't know how to cross check 
https://www.prestashop.com/forums/topic/177710-solved-please-please-help-500-internal-error-on-payment-modules/

**Comment by channeld** [comment] 2018-11-16 10:14
I also saw that in the log
[Thu Nov 15 18:51:56.366937 2018] [core:alert] [pid 99713:tid 47329724319488] [client 10.20.46.116:58600] /home/mostycom/public_html/.htaccess: </IfModule> without matching <IfModule> section, referer: https://mosty.com/eshop/admin123/index.php?controller=AdminPaymentPreferences&token=[]
[Thu Nov 15 18:51:56.366847 2018] [core:alert] [pid 99713:tid 47329724319488] [client 10.20.46.116:58600] /home/mostycom/public_html/.htaccess: </IfModule> without matching <IfModule> section, referer: https://mosty.com/eshop/admin123/index.php?controller=AdminPaymentPreferences&token=[]

**Comment by channeld** [comment] 2018-11-16 10:16
hm weird... it changes the code

![image](https://user-images.githubusercontent.com/5381252/48615364-647d4700-e999-11e8-8153-ec921954baa7.png)

**Comment by khouloudbelguith** [comment] 2018-11-16 10:16
@channeld, if you enable the debug mode, there are no exceptions displayed??
Could you please try to disable custom payment module & try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

**Comment by channeld** [comment] 2018-11-16 10:30
checking something... I found an error log that relates to /ifmodule and I show this
https://www.prestashop.com/forums/topic/294043-htaccess-problem/

**Comment by khouloudbelguith** [comment] 2018-11-16 10:44
Hi @channeld,

The root htaccess ("/home/mostycom/public_html/.htaccess") is being called. I don't know where that .htaccess comes from; if you didn't create it someone or something did it. This htaccess is the problem, it doesn't come from the Prestashop. Your problem, whatever is the source of it, should be corrected by the one who created the htaccess. It might be your host provider or your developer (If you got one).
Thanks to check & feedback.

**Comment by channeld** [comment] 2018-11-16 10:50
but there is not there.

**Comment by channeld** [comment] 2018-11-16 11:00
That htaccess was removed and is not there.
cleaning cache manually

**Comment by khouloudbelguith** [comment] 2018-11-16 11:02
Hi @channeld,

That's the error : `10.20.46.116:58600] /home/mostycom/public_html/.htaccess: without matching section`, that you have in your log file.
Thanks!

**Comment by channeld** [comment] 2018-11-16 11:03
Cache cleaned manually. Tried the call Payment preferences. Same.

**Comment by khouloudbelguith** [comment] 2018-11-16 11:05
@channeld, could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by channeld** [comment] 2018-11-16 11:07
Same.

**Comment by channeld** [comment] 2018-11-16 11:07
this is the file

# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>

<IfModule mod_rewrite.c>
<IfModule mod_env.c>
SetEnv HTTP_MOD_REWRITE On
</IfModule>


# Disable Multiviews
Options -Multiviews

RewriteEngine on


#Domain: mosty.com
RewriteRule . - [E=REWRITEBASE:/eshop/]
RewriteRule ^api$ api/ [L]

RewriteRule ^api/(.*)$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

# Images
RewriteRule ^([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$1$2$3.jpg [L]
RewriteRule ^([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$1$2$3$4.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$1$2$3$4$5.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg [L]
RewriteRule ^([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(\-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg [L]
RewriteRule ^c/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2$3.jpg [L]
RewriteRule ^c/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}img/c/$1$2.jpg [L]
# AlphaImageLoader for IE and fancybox
RewriteRule ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 [L]

# Dispatcher
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>

AddType application/vnd.ms-fontobject .eot
AddType font/ttf .ttf
AddType font/otf .otf
AddType application/font-woff .woff
AddType font/woff2 .woff2
<IfModule mod_headers.c>
	<FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|svg)$">
		Header set Access-Control-Allow-Origin "*"
	</FilesMatch>
</IfModule>

<IfModule mod_expires.c>
	ExpiresActive On
	ExpiresByType image/gif "access plus 1 month"
	ExpiresByType image/jpeg "access plus 1 month"
	ExpiresByType image/png "access plus 1 month"
	ExpiresByType text/css "access plus 1 week"
	ExpiresByType text/javascript "access plus 1 week"
	ExpiresByType application/javascript "access plus 1 week"
	ExpiresByType application/x-javascript "access plus 1 week"
	ExpiresByType image/x-icon "access plus 1 year"
	ExpiresByType image/svg+xml "access plus 1 year"
	ExpiresByType image/vnd.microsoft.icon "access plus 1 year"
	ExpiresByType application/font-woff "access plus 1 year"
	ExpiresByType application/x-font-woff "access plus 1 year"
	ExpiresByType font/woff2 "access plus 1 year"
	ExpiresByType application/vnd.ms-fontobject "access plus 1 year"
	ExpiresByType font/opentype "access plus 1 year"
	ExpiresByType font/ttf "access plus 1 year"
	ExpiresByType font/otf "access plus 1 year"
	ExpiresByType application/x-font-ttf "access plus 1 year"
	ExpiresByType application/x-font-otf "access plus 1 year"
</IfModule>

<IfModule mod_headers.c>
    Header unset Etag
</IfModule>
FileETag none
<IfModule mod_deflate.c>
    <IfModule mod_filter.c>
        AddOutputFilterByType DEFLATE text/html text/css text/javascript application/javascript application/x-javascript font/ttf application/x-font-ttf font/otf application/x-font-otf font/opentype image/svg+xml
    </IfModule>
</IfModule>

#If rewrite mod isn't enabled
ErrorDocument 404 /eshop/index.php?controller=404

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again

**Comment by khouloudbelguith** [comment] 2018-11-16 11:08
@channeld, could you please check the error with your host, it could be a server issue.
Thanks to check with them & feedback.

**Comment by channeld** [comment] 2018-11-16 11:20
they are checking and yet not finding something. I am on a dedicated server.

**Comment by khouloudbelguith** [comment] 2018-11-16 11:30
Is your Prestashop really installed in "/home/mostycom/"? There's no public HTML or whatever else? You might not be looking to the right .htaccess.
Thanks to check & feedback.

**Comment by channeld** [comment] 2018-11-16 11:44
Hi. The eshop is in public_html/mosty.com/eshop folder. There is only 1 htaccess in there.

**Comment by channeld** [comment] 2018-11-16 11:46
eeeer sorry.. .meaning mosty.com/public_html/eshop

**Comment by channeld** [comment] 2018-11-16 12:03
It is driving me crazy. I run other PS sites and never encountered such an issue.

**Comment by channeld** [comment] 2018-11-16 12:14
Hosting set all limits to the top in the dedicated, even timeouts and still the same error persists only in these 2 sections, I have removed payment and shipping modules. nothing.

**Comment by khouloudbelguith** [comment] 2018-11-16 13:03
@channeld, in the folder public_html, to show the cached files, you can run this command `ls -al` or you can type with your keyboard, `ctrl+h`.
Because the .htacces is a cached file which has a problem under  `/home/mostycom/public_html`
Thanks!

**Comment by channeld** [comment] 2018-11-16 13:09
I just try this... I move all modules to a temp folder. Then payment/shipping works. Now I move them in 1 by 1 to see which causes the issue.

**Comment by khouloudbelguith** [comment] 2018-11-16 13:13
@channeld, okay thanks!
Waiting for your feedback.

**Comment by channeld** [comment] 2018-11-16 13:18
they say t looks like there is no .htaccess under /home/mostycom/public_html 
and I really can't find one. why you say there is?

**Comment by khouloudbelguith** [comment] 2018-11-16 13:19
@channeld, that's what I saw in your log error.
Thanks!

**Comment by channeld** [comment] 2018-11-16 13:20
ah. that is old info

**Comment by channeld** [comment] 2018-11-16 14:18
I found the problem at a 1st level. I moved all modules from root Modules folder to a temp file and slowly placed them back by checking these 2 sections.
The sections worked. So I placed modules back (standard ps modules, plus 6 of the theme).
As I added the modules one by one semed like the backend needed more time for the Payment/Shipping sections to load each time they were clicked. At some point it showed the 504 gateway. Around before moving in the last 3-4 modules. 
Then I tried to see if the problem is with the specific modules or with the sum of modules as a total "weight". I randomly moved out modules and again it worked.
So seems like the server can't cope with the sum of modules and for some weird reason this only affect payment section and shipping section in backend. Front works fine.

**Comment by khouloudbelguith** [comment] 2018-11-16 14:23
Hi @channeld,

Could you please try to increase the `max_execution_time` in your php.ini file.
Thanks to check & feedback.

**Comment by channeld** [comment] 2018-11-16 14:30
that is max_execution_time = 600 already.

**Comment by khouloudbelguith** [comment] 2018-11-16 14:32
@channeld, have you tried to contact the theme author about this issue?
Because those modules decrease the performance of your shop.
Thanks!

**Comment by channeld** [comment] 2018-11-16 14:32
allow_url_fopen = On
allow_url_include = Off
asp_tags = Off
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 600
max_input_time = 60
max_input_vars = 10000
memory_limit = 256M
post_max_size = 128M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php56"
upload_max_filesize = 25M
zlib.output_compression = Off
register_globals = Off
magic_quotes_gpc = Off
allow_url_include = Off

**Comment by khouloudbelguith** [comment] 2018-11-16 16:37
Hi @channeld,

Could you please try to contact the theme author ( provided of those modules) about this issue & feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-21 13:55
Hi @channeld,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2018-12-21 13:55 UTC
Labels: Bug, BO, Can't reproduce, Carriers
