### ISSUE TITLE
Special Characters on Invoice Footer

### ISSUE THREAD

**Issue by iwan75** [PrestaShop/PrestaShop#25928] opened 2021-09-20 08:07 UTC
#### Describe the bug

On the Invoice Footer the Special Character "&" is printed as "&amp;"

#### Expected behavior

"&" should be printed as "&"

#### Steps to Reproduce

If your Company has an "&" in the Company Name it's printed wrong on all Invoices.

![image](https://user-images.githubusercontent.com/23296488/133972052-59eae45d-7e4a-42da-823d-1b22dde61d7c.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.30

[RE000006.pdf](https://github.com/PrestaShop/PrestaShop/files/7194337/RE000006.pdf)

**Comment by hibatallahAouadni** [comment] 2021-09-20 09:53
Hello @iwan75 

I didn't manage to reproduce your issue with PS1778, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/133984014-50504646-600a-4097-abd3-e51577409902.png)

---
![image](https://user-images.githubusercontent.com/23308427/133984090-b8fd59ba-bc2f-45fb-83e1-21d0dbef4115.png)

Please check and feedback.

Thanks!

**Comment by iwan75** [comment] 2021-09-21 06:06
i just recognised the problem is not on the report.
the problem is in master data.

when i enter an address with & it's stored as &amp;

![2021_09_21_08_03_37_Window](https://user-images.githubusercontent.com/23296488/134120020-b333e754-c1a6-4fed-ab9b-7680bff3f657.png)

**Comment by iwan75** [comment] 2021-09-21 06:32
it's correct in the DB... on the invoice it's printed not correct:

![2021_09_21_08_31_05_Window](https://user-images.githubusercontent.com/23296488/134122566-829b8f9b-79d7-4c7a-99ed-65b293041875.png)

**Comment by florine2623** [comment] 2021-09-21 07:18
Hello @iwan75 ,

Can you make sure your config in  International > Localization matches the one of your server ?
<img width="1194" alt="Screenshot 2021-09-21 at 09 15 34" src="https://user-images.githubusercontent.com/16019289/134128004-6bc15e14-7f77-4ba6-a125-62e139519518.png">

**Comment by iwan75** [comment] 2021-09-21 08:03
> Hello @iwan75 ,
> 
> Can you make sure your config in International > Localization matches the one of your server ?
> <img alt="Screenshot 2021-09-21 at 09 15 34" width="1194" src="https://user-images.githubusercontent.com/16019289/134128004-6bc15e14-7f77-4ba6-a125-62e139519518.png">

this is correct...

**Comment by florine2623** [comment] 2021-09-21 09:46
What about the encoding of files ?
<img width="1088" alt="Screenshot 2021-09-21 at 11 46 32" src="https://user-images.githubusercontent.com/16019289/134149598-03a94d6b-6cf7-4349-a165-bcb3c74e4683.png">

**Comment by florine2623** [comment] 2021-10-05 09:04
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-10-05 09:04 UTC
Labels: Bug, BO, Invoices, No change required, 1.7.7.8
