### ISSUE TITLE
Prestashop 1.7.8.x not working on IE11

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#26978] opened 2021-12-14 13:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I found two problems on IE11.

You can verify on your own demo:

1 - Slider doesn't work. Even if you click on the "next" arrow.
2 - You can't add products to cart (it will show the cart empty).

### Expected behavior

Base Prestashop should be fully functional with IE11 (?)

### Steps to reproduce

1 - Use IE11
2 - Check the main page slider. It won't slide even if you click.
3 - Try to add a product to cart.

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by florine2623** [comment] 2021-12-14 14:16
Hello @seederp2p ,

I was able to reproduce the issue with PrestaShop version 1.7.8.2 on IE11 (end of life 2022), so I can confirm that this behavior is indeed a bug.

I tested on the demo version, I have 3 issues :
- slider arrows can't be clicked (https://demo.prestashop.com/#/en/front)
- product is not added to the cart (screen below)
- tags on product do not have the right design (screen below)

![image](https://user-images.githubusercontent.com/16019289/146014684-e4b567eb-c127-4b37-abaa-896f5d291c77.png)

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by jf-viguier** [comment] 2021-12-14 15:41
IE is not supported by Prestashop (i've removed it from the doc) : 
https://devdocs.prestashop.com/1.7/themes/getting-started/guidelines/#html--css--javascript

**Comment by florine2623** [comment] 2021-12-14 15:51
Thanks @jf-viguier ,

@seederp2p it won't be fixed then. I'll close your issue. Thank you !

**Closed as completed by florine2623** 2021-12-14 15:51 UTC
Labels: Bug, FO, Imageslider, Invalid
