### ISSUE TITLE
500 error on db connection, always resolved within 60 seconds

### ISSUE THREAD

**Issue by maartenaalbers** [PrestaShop/PrestaShop#11006] opened 2018-10-14 18:51 UTC
Hi,

my prestashop (www.ma-kaartjes.nl) throws me the 500 page very often. If you refresh after +/- 60 seconds, the site works again. If you login to the backoffice during the error ti shows:

[PrestaShopException]
Link to database cannot be established: SQLSTATE[HY000] [2002] Connection refused
at line 120 in file classes/db/DbPDO.php

Backoffice:
<img width="994" alt="screenshot 2018-10-14 at 20 46 10" src="https://user-images.githubusercontent.com/2944858/46920736-f4bf1980-cff2-11e8-829e-fcc803dfa979.png">

Frontoffice:
<img width="690" alt="screenshot 2018-10-14 at 20 52 07" src="https://user-images.githubusercontent.com/2944858/46920744-0f918e00-cff3-11e8-8f59-d79a9821dee6.png">

**Comment by khouloudbelguith** [comment] 2018-10-15 08:06
Hi @maartenaalbers,

If the issue is this exact exception [Link to database cannot be established: SQLSTATE[HY000] [2002]] => your issue is not related to PrestaShop => it is an error on your server.
The problem comes from your web host. You must check your PrivateSql instance and everything around. It's not even a max_execution_time problem.
Try to connect to your mysql server in command line if you can :)
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-16 11:09
Hi @maartenaalbers,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-16 11:09 UTC
Labels: BO, Database, No change required
