### ISSUE TITLE
form_field template without cache

### ISSUE THREAD

**Issue by CLC1234** [PrestaShop/PrestaShop#22451] opened 2020-12-16 13:15 UTC
#### The bug

It exists a problem when you use the "form_field" template like this

![image](https://user-images.githubusercontent.com/76108448/102351693-28b57100-3fa7-11eb-9684-83ddf2e7dfce.png)

+ put settings :
PS_SMARTY_FORCE_COMPILE = 0 OR 1 (=Never recompile OR Recompile templates if the files have been updated)
PS_SMARTY_CACHE = NULL (NULL = disable, 1 = enable)

On front you see this (Customer login form)
We loop on 3 fields, but this the 3 same fields (loop on the 1st field (input type hidden))

![image](https://user-images.githubusercontent.com/76108448/102352302-f0faf900-3fa7-11eb-8c17-b83cf7a51935.png)

The render is trigger in "smartyfront.config.inc.php"

![image](https://user-images.githubusercontent.com/76108448/102352707-6666c980-3fa8-11eb-8884-c2f1cd348a47.png)

But we don't have cache key in fetch; perhaps the root cause ?

#### Additional information

* PrestaShop version: 1.7.4 (but file smartyfront.config.inc.php in the same in last release)
* PHP version: 7.1

Thanks

**Comment by hibatallahAouadni** [comment] 2020-12-16 14:05
Hello @CLC1234 

Are you trying to override some files? 
Ping @PrestaShop/prestashop-core-developers need some help :sweat_smile: I couldn't see where is the problem :sweat:

**Comment by PierreRambaud** [comment] 2020-12-16 14:51
I didn't manage to reproduce the issue
![image](https://user-images.githubusercontent.com/1462701/102364220-81403a80-3fb6-11eb-98ed-d63102d54aa2.png)

**Comment by CLC1234** [comment] 2020-12-16 17:25
@hibatallahAouadni No PHP override but we use this template throught a child theme (so like an override but in a theme).

**Comment by hibatallahAouadni** [comment] 2020-12-25 12:04
Hello @CLC1234 

@PierreRambaud didn't reproduce the issue. 
So, could you please provide more details that help us to reproduce the issue.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-14 11:52
Hello @CLC1234 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-14 11:52 UTC
Labels: Bug, CO, No change required
