### ISSUE TITLE
Problem with cart made some days before to buy

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#20073] opened 2020-07-06 13:25 UTC
Hi

at this time I have no image to upload
sometimes some shopkeepers report me this error:
in the checkout it is not present any carrier, so the customers cannot finish the order

after some tests, all these cases happen when the cart has been created for some time, like the day before or a few days before. So the customers continue to use the products addeds in the cart in the past.
the problem is resolved removing all products from the cart and add them again (in this mode a new cart will be recreated).

can the problem be due to this option ? or to the use of the token?

thanks

![1](https://user-images.githubusercontent.com/653230/86597992-c63e5a80-bf9c-11ea-8f19-2c3c4f8205be.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by matks** [comment] 2020-07-13 08:36
Hi @maofree, did you notice whether the products added in the cart were modified later ? I remember seeing issues with the scenario

1. customer adds to cart product A
2. later, merchant modifies product A in back-office
3. now customer has product A in cart with outdated informations => in Checkout, no "eligible carrier" found

**Comment by matks** [comment] 2020-07-13 08:41
@maofree Issue could be identical to https://github.com/PrestaShop/PrestaShop/issues/12267 . Could you confirm ?

**Comment by Maofree** [comment] 2020-07-13 08:42
Hi
I hadn't thought about this scenario. I don't know why this happens every now and then and on multiple sites. Surely these shopkeepers have very high activity on their site, so it may be due to what you say.
this also happens for orders, in some cases they cannot access the order, the only solution is to remove the cart associated with the order from the database.

**Comment by Maofree** [comment] 2020-07-13 08:44
probably is due from

`I finally found what's wrong.

Sometimes, when a customer create a new address, the new id_address_delivery is set to cart but not to cart_detail. That's why PS cannot find available carriers due to the fact id_address_delivery from cart didn't match cart_detail.`

**Comment by khouloudbelguith** [comment] 2020-07-13 08:50
Hi @maofree,

I think it is the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-467397790
This issue is fixed in the next release 1.7.7.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/15399

Thanks to check it and feedback.

**Comment by Maofree** [comment] 2020-07-13 09:11
ok thanks

**Comment by khouloudbelguith** [comment] 2020-07-13 09:14
@maofree,

Your ticket is a duplicate of #9932
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-13 09:14
Duplicate of #9932

**Closed as completed by khouloudbelguith** 2020-07-13 09:14 UTC
Labels: Duplicate
