### ISSUE TITLE
Chrome - FO - Quantity increment +1 when to we change quantity to 0 in cart with press enter key

### ISSUE THREAD

**Issue by jimmydupre** [PrestaShop/PrestaShop#25470] opened 2021-07-30 09:41 UTC
#### Describe the bug

In the shopping cart, when we change the quantity to 0 with **press enter Key** using Chrome. We have the quantity changes to 1 then to 2.
And I remark that i put a quantity she's multiplied by 2. 
Is possible bug to js ? 
https://drive.google.com/file/d/1dNzXFy-HEoM3BxJGJ2-snIjId08ZYzbu/view?usp=sharing
#### Expected behavior

We have checked on the official demonstration website prestashop and we have found the same issue. 

#### Additional information

* PrestaShop version: last version

**Comment by khouloudbelguith** [comment] 2021-07-30 10:22
Hi @jimmydupre,

Thanks for your report.

I did not manage to reproduce the issue with PS1775 and branch 1.7.8.x (1780).
I attached a screen record
https://drive.google.com/file/d/1r2vw2UJKKoKvFJ2oyqoqdW6HvFnpuWJk/view?usp=sharing

Thanks to check and feedback.

**Comment by jimmydupre** [comment] 2021-07-30 10:40
Hi @khouloudbelguith 

Thanks for your response.

I remade a video from the prestashop demo.
[https://demo.prestashop.com/#/en/front](https://demo.prestashop.com/#/en/front)
[https://drive.google.com/file/d/1dNzXFy-HEoM3BxJGJ2-snIjId08ZYzbu/view?usp=sharing](https://drive.google.com/file/d/1dNzXFy-HEoM3BxJGJ2-snIjId08ZYzbu/view?usp=sharing)

Use the enter key.

**Comment by khouloudbelguith** [comment] 2021-07-30 10:53
@jimmydupre,

Thanks for your feedback.
I used the same link, but it is ok in my case.
https://drive.google.com/file/d/1QE3SE12u0zmZ_kd8st5LyxF91BwitUI-/view?usp=sharing

Did I miss a step?

Thanks!

**Comment by jimmydupre** [comment] 2021-07-30 11:02
I remark that this bug is only available when i press enter key.

**Comment by khouloudbelguith** [comment] 2021-07-30 11:13
@jimmydupre, I used the increase-decrease icon => ok
I used the press enter key => ok
https://drive.google.com/file/d/1MWWXKahPqpKfMYQHYHco5nZIXVivEldF/view?usp=sharing

Thanks!

**Comment by jimmydupre** [comment] 2021-07-30 11:19
When we use the increase-decrease arrow, this functionality working so don't use arrow to make test. 
I have use new instance on navigation private to make another test.

**Comment by khouloudbelguith** [comment] 2021-07-30 12:55
@jimmydupre, Thanks for these clarifications.
I manage to reproduce the issue with PS1769, PS1775, and branch 1.7.8.x using Chrome Version 87.0.4280.141 
Firefox v78.5.0esr (64 bits) => ok

I'll add this to the debug backlog so that it's fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 
If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by jimmydupre** [comment] 2021-07-30 13:02
Thanks @khouloudbelguith
I follow this issue.

**Closed as completed** 2021-12-08 10:02 UTC
Labels: Bug, Trivial, FO, Fixed, Front-end, Shopping carts FO, PR available, 1.7.6.9, 1.7.8.x
