### ISSUE TITLE
White screen with "Testing" text appears when creating a cart rule

### ISSUE THREAD

**Issue by Jtrev94** [PrestaShop/PrestaShop#15678] opened 2019-09-24 20:54 UTC
**Describe the bug**
I'm trying to create a new cart rule, but when I save a white screen appears with just "Testing" as response. I activate debug mode and "non native modules" mode; but the problem persists.

**To Reproduce**
1. Go to 'Catalog > Cart rules'
2. Click on 'Add new'
3. Fill all the information, with Highlight = No, Partial use = No, No restrictions and just 10% discount
4. Click on Save

**Screenshots**
![Recorded error](https://media.giphy.com/media/cmC6O3SuxABei8KLKE/giphy.gif)
**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22

**Comment by khouloudbelguith** [comment] 2019-09-25 08:08
Hi @Jtrev94,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-25 07:36
Hi @Jtrev94,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-25 07:36 UTC
Labels: Bug, BO, Cart rules, No change required, 1.7.6.1
