### ISSUE TITLE
FO Mobile - on Search sort result list, click on back to top button reload the page with the sort

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28932] opened 2022-07-01 15:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Only on mobile screen, on search result page on the FO, we want to sort the result. At the end of the page, click on the "back to top" button: the page is reloaded and the result and sort choice are back to default.

Error on 8.0.0 and 1.7.8.0 version:

https://user-images.githubusercontent.com/2854834/176922718-0e8b0859-8abd-4aff-8ce0-7ad671df2bfe.mp4

Good on 1.7.7.8 version:

https://user-images.githubusercontent.com/2854834/176922754-d967defb-0582-45bc-88c3-356e7049f75d.mp4

It's a regression

### Expected behavior

The sort list and the result should be displayed the same choice after the click on the button.
The page shouldn't be reloaded.

### Steps to reproduce

1. Go to FO on mobile screen >  fill the search bar on the header > click on the icon to launch the research
2. Click on the sort list > choose one of them
3. Go to the end of the page > Click on the "back to top" button
4. See error: page is reloaded, result and sort list are back to default

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.2

**Comment by jolelievre** [comment] 2022-07-12 15:55
The bug as fixed on the 178x branch since the bug is a regression on 178 already https://github.com/PrestaShop/PrestaShop/pull/29055

It will fix the 8.0 branch when the fix is merged back into the 8.0.x branch

**Comment by matks** [comment] 2022-07-18 16:15
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29055

**Closed as completed by matks** 2022-07-18 16:15 UTC
Labels: Bug, 8.0.x, Minor, FO, Search, Regression, Fixed, PR available, Verified
