### ISSUE TITLE
Cart rule with carrier restriction is not applied automatically

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#20705] opened 2020-08-25 10:38 UTC
#### Describe the bug

Cart rule with carrier restriction is not applied automatically if default carrier is selected

#### Expected behavior

Cart rule should be applied in the cart automatically without changing carrier selection

#### Steps to Reproduce

1. Create a cart rule with carrier restriction and free shipping:

![image](https://user-images.githubusercontent.com/15104724/91164357-3335bd00-e6cf-11ea-896f-bdc3af285b1e.png)
_*Select default carrier_

![image](https://user-images.githubusercontent.com/15104724/91164373-37fa7100-e6cf-11ea-8301-6c48ea9feeb7.png)

2. Add a product to the cart and proceed to checkout

3. Rule is not applied by default:
![image](https://user-images.githubusercontent.com/15104724/91164536-76902b80-e6cf-11ea-9cd9-cd3ddc42ed6f.png)

4. If you change carrier from _Carrier 2_ and then back again to _My carrier_, rule is applied:
![image](https://user-images.githubusercontent.com/15104724/91164575-8ad42880-e6cf-11ea-828b-bb5a44dfd9b6.png)

**Comment by khouloudbelguith** [comment] 2020-08-25 10:50
Hi @idnovate,

Thanks for your report.
>Cart rule with carrier restriction is not applied automatically if default carrier is selected

This issue occurs due to this issue: #9688
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9688
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-25 10:50
Duplicate of #9688

**Closed as completed by khouloudbelguith** 2020-08-25 10:50 UTC
Labels: Duplicate
