### ISSUE TITLE
Tax Total is wrong in "Order Conf" mail when a Voucher is used.

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#22558] opened 2020-12-23 10:10 UTC
#### Describe the bug

In order confirmation email (template '`order_conf`') the field Total Tax (in the template `{total_tax_paid}`) report the wrong value in case a voucher applicable on order total (ex: 10% on order total) is used. In particular the total tax is calculated on the order total without the discount.

#### Expected behavior
Total tax is calculate on the discounted order total

#### Steps to Reproduce

1. Create a new voucher in the backoffice, ex a 10% on order total.
2. Create a new product for the test (ex: with price tax incl = 122€ and VAT = 22%)
2. perform a new order in prestashop using product created before in point 2). In the checkout step use the voucher created in point 1).
3. At this point the order should be like (the shipping is free) : 
    4.1. product: 122€ tax incl
    4.2. voucher 10%: 12,2€ tax incl
    4.3. order total: 109.8€ tax incl
    4.3. total tax: 19.8€
4. Check the email of "Order Confirmation". in the "total tax" you find 22€ that is the tax of the total order without the voucher.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2020-12-23 13:44
Hello @abramofranchetti 

We are aware of this issue, it is already fixed with our new release PS1.7.7.0. 
This issue is a duplicate of #16227. 

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-23 13:45
Duplicate of #16227

**Closed as completed by hibatallahAouadni** 2020-12-23 13:44 UTC
Labels: Duplicate
