### ISSUE TITLE
Missing data on product listing with custom search provider

### ISSUE THREAD

**Issue by Lwackp** [PrestaShop/PrestaShop#15313] opened 2019-08-29 13:41 UTC
**Describe the bug**
I've developped a very simple search provider that returns 1 result when the user searchs for a very specific product reference. In my code example, the reference is a "Code Produit" (product code) and is data i'm storing in different table through a module.

```
use PrestaShop\PrestaShop\Core\Product\Search\ProductSearchProviderInterface;
use PrestaShop\PrestaShop\Core\Product\Search\ProductSearchContext;
use PrestaShop\PrestaShop\Core\Product\Search\ProductSearchQuery;
use PrestaShop\PrestaShop\Core\Product\Search\ProductSearchResult;
require_once(_PS_MODULE_DIR_.'qb7/models/CodeProduit.php');

class CodeProduitSearchProvider implements ProductSearchProviderInterface {
    public function runQuery(ProductSearchContext $context, ProductSearchQuery $query) {
        $products = [];
        $count    = 0;
        
        $id_product = CodeProduit::getByCodeProduit(intval($query->getSearchString())); // Returns 1 product id if the search string is equal to a known product reference
        if ($id_product) {
            $products[] = ['id_product' => $id_product];
            $count++;
        }
        
        $result = new ProductSearchResult();
        
        if (!empty($products)) {
            $result
                ->setProducts($products)
                ->setTotalProductsCount($count);

//            $result->setAvailableSortOrders(
//                $this->sortOrderFactory->getDefaultSortOrders()
//            );
        }

        return $result;
    }
}
```

When searching for an existing product reference then my search provider is used and returns 1 result. However, some data is missing in the product listing. For now, I've only identified the field "manufacturer_name" as missing.

If you do a search with the product name, the product appears in the list and the manufacturer name isn't missing.

**To Reproduce**
- Develop a custom search provider
- When your search provider is used to retrieve a product list, the manufacturer name doesn't appear. If your search provider isn't used, the manufacturer name appears.

**Screenshots**
Without my search provider
![image](https://user-images.githubusercontent.com/38342913/63945083-c39bdc00-ca40-11e9-8c11-ff61666e05ae.png)

With my search provider
![image](https://user-images.githubusercontent.com/38342913/63945199-e928e580-ca40-11e9-8da6-eeec84b53731.png)

**Additional information**
PrestaShop version: 1.7.4.3
PHP version: 5.6.40-0+deb8u5

**Comment by khouloudbelguith** [comment] 2019-08-29 14:39
Hi @Lwackp,

Thanks for your report.
So, this issue occurs due to a PrestaShop core bug or only with your custom search?
Because without your search provider => OK.

Thanks!

**Comment by Lwackp** [comment] 2019-08-29 14:42
Hi,
Only with my custom search.
However, according to the docs, a custom search module should not be responsible to retrieve product data.

> The search provider returns a ProductSearchResult, it contains:
> -  the products, obviously (which may just be an array like [['id_product' => 2], ['id_product' => 3]] - the core will add the missing data!)

https://devdocs.prestashop.com/1.7/development/components/faceted-search/

So it seems to me that it might be a core bug ?

**Comment by khouloudbelguith** [comment] 2019-08-29 16:33
@Lwackp, thanks for these clarifications.
Yes I tried with PS1.7.6.1, all data are displayed after searching
`PrestaShop\PrestaShop\Core\Product\Search\ProductSearchResult Object ( [products:PrestaShop\PrestaShop\Core\Product\Search\ProductSearchResult:private] => Array ( [0] => Array ( [id_product] => 28 [id_supplier] => 0 [id_manufacturer] => 0 [id_category_default] => 2 [id_shop_default] => 1 [id_tax_rules_group] => 0 [on_sale] => 0 [online_only] => 0 [ean13] => [isbn] => [upc] => [ecotax] => 0.000000 [quantity] => 0 [minimal_quantity] => 1 [low_stock_threshold] => [low_stock_alert] => 0 [price] => 120 [wholesale_price] => 0.000000 [unity] => [unit_price_ratio] => 0.000000 [additional_shipping_cost] => 0.00 [reference] => boom [supplier_reference] => [location] => [width] => 0.000000 [height] => 0.000000 [depth] => 0.000000 [weight] => 0.000000 [out_of_stock] => 2 [additional_delivery_times] => 0 [quantity_discount] => 0 [customizable] => 0 [uploadable_files] => 0 [text_fields] => 0 [active] => 1 [redirect_type] => [id_type_redirected] => 0 [available_for_order] => 1 [available_date] => 0000-00-00 [show_condition] => 0 [condition] => new [show_price] => 0 [indexed] => 1 [visibility] => both [cache_is_pack] => 0 [cache_has_attachments] => 0 [is_virtual] => 0 [cache_default_attribute] => 0 [date_add] => 2019-08-29 18:11:58 [date_upd] => 2019-08-29 18:11:58 [advanced_stock_management] => 1 [pack_stock_type] => 0 [state] => 0 [id_shop] => 1 [description_short] => [available_now] => [available_later] => [link_rewrite] => aaaa [name] => testingproduct [id_image] => en-default [legend] => [manufacturer_name] => [position] => 6 [new] => 1 [product_attribute_minimal_quantity] => [id_product_attribute] => 0 [allow_oosp] => 0 [category] => home [category_name] => Home [link] => http://projet/1761build1/en/home/28-aaaa.html [attribute_price] => 0 [price_tax_exc] => 120 [price_without_reduction_without_tax] => 120 [price_without_reduction] => 120 [reduction] => 0 [reduction_without_tax] => 0 [specific_prices] => Array ( ) [quantity_all_versions] => 0 [features] => Array ( ) [attachments] => Array ( ) [virtual] => 0 [pack] => 0 [packItems] => Array ( ) [nopackprice] => 0 [customization_required] => [rate] => 0 [tax_name] => [ecotax_rate] => 0 [unit_price] => 0 ) )`

![image](https://user-images.githubusercontent.com/16067358/63958823-d3d4ab00-ca82-11e9-8d41-8bfec4366940.png)
But we should ask developers if it a real bug.
Ping @PrestaShop/prestashop-core-developers what do you think? retrieving all the data of the product is a bug or normal behavior?

Thanks!

**Comment by Nakira** [comment] 2020-11-16 13:51
I have the same issue.  
  
After digging a bit in code seems like 
```/src/Adapter/Presenter/Product/ProductLazyArray.php``` receives $product array with allow_oosp value of 0.

I double checked my config and the product is configured to allow oos orders.

version of prestashop : 1.7.6.8 
Tested without any override.
The issue is that i cannot reproduce the bug with classic theme because the allow_oosp is not uses in classic theme.... 

High time that prestashop takes thoses features into child theme. @PrestaShop/prestashop-core-developers 

Quick fix for me was to override the classe to force allow_oosp to 1 : i have the luxury to have an unified stock management method for all the catalog.

**Comment by Nakira** [comment] 2020-11-16 14:53
Ok so it seems like the source of the issue is src/prestashop/classes/ProductAssembler.php

the query returns a null value for  out_of_stock and does not take the global configuration : 

```php
  $sql = "SELECT
                    p.*,
                    pl.*,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_lang pl
                    ON pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa
			        ON sa.id_product = p.id_product 
			        AND sa.id_shop = $idShop
			    WHERE p.id_product = $idProduct"
```

$rows[0]["out_of_stock"] is null , should be true in my case

**Comment by PierreRambaud** [comment] 2020-12-08 16:29
There is one reason some fields are missing.
I tried with facetedsearch.

This is what is passed top the `prepareMultipleProductsForTemplate` when using the facetedsearch module 
![image](https://user-images.githubusercontent.com/1462701/101510868-bb885700-397a-11eb-97cc-9cc7b10e8118.png)


And when you don't have it:
![image](https://user-images.githubusercontent.com/1462701/101511143-de1a7000-397a-11eb-80ad-bd2f682f9ea0.png)


Afaik, you need to add custom fields or load fields you need in your module.

Otherwise, maybe the Core needs to load default data. I don't have the answer here.

**Comment by hibatallahAouadni** [comment] 2021-02-22 20:43
Hello @Lwackp 

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-22 20:43 UTC
Labels: Bug, Search, No change required, 1.7.4.3, 1.7.6.1
