### ISSUE TITLE
Endpoint /api/hooks & List of Hooks : Incorrect count of hooks

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#35616] opened 2024-03-12 09:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The endpoint /api/hooks returns a bad count of hooks (or the BO doesn't display all hooks).

### Expected behavior

The endpoint /api/hooks has the same count of hooks that in the BO.

### Steps to reproduce

1. Auth with the API (scope : `hook_read`)
2. Request the endpoint 'api/hooks' : It returns **947** hooks
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/98186fc8-fbd7-4781-9a16-59d79dfe03ac)
3. Go in the BO > Design > Positions
4. Display non-positionable hooks: It returns **124** hooks
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/22abe7a4-84b7-409f-af18-5bdecad64c99)

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

ps_apiresources `dev-fix/34852`

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment] 2024-03-12 10:11
Hi @Progi1984 ,

Thank you for your report, I reproduce the issue with PrestaShop version develop, as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/4573bae2-f9aa-44d7-a146-620cfd52b64f)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by Hlavtox** [comment] 2024-05-23 11:03
@Progi1984 @MatShir The difference is that in API, you get a full hook list, but in BO, it shows only hooks that have something hooked on it.

Expected behavior I guess? 🤷

**Comment by MatShir** [comment] 2024-05-23 12:28
It does make sense! @Hlavtox 

@Progi1984 I recommend that we consider closing this matter now. These issues could be considered trivial and it's important to focus on more significant matters to avoid unnecessary clutter in our minor issue backlog.

**Comment by Progi1984** [comment] 2024-05-23 13:49
It's blocking for @PrestaShop/qa-automation team for testing the endpoint /api/hooks because we have no location in the BO where we can list hooks. Perhaps I don't know about another page?

**Comment by MatShir** [comment] 2024-05-23 14:20
But it is not a bug! we need to find another way to have the hook list

**Closed as completed by MatShir** 2024-05-23 14:20 UTC
Labels: Bug, develop, Minor, BO, Positions, Ready, Verified, Experimental Features

**Comment by Robin-Fischer-PS** [comment] 2024-05-23 15:58
Hi there @MatShir 
Maybe it's not a bug (maybe more a "missing feature"), but I don't think that it can be considered as not significant, since as @Progi1984 says, it's blocking the autom team. Just closing the issue and the subject will go into limbo. Could this be prioritised somehow ?

**Comment by Hlavtox** [comment] 2024-05-23 16:04
@Robin-Fischer-PS I dont understand what is the issue. 

API returns all hooks in the system.
Backoffice module position shows only hooks with something shown on them.

What is the problem?

**Comment by kpodemski** [comment] 2024-05-24 09:18
>  I don't think that it can be considered as not significant, since as @Progi1984 says, it's blocking the autom team

This shows that there might be differences between how the back office renders things and how API returns some information. I think the problem here is the wrong assumption that everything has to be tested via UI Tests :)

Let's be honest: I don't know any use case (at the moment) for printing out a full list of hooks in the API. We should do it differently if we want to allow managing module hooks within the API.
