### ISSUE TITLE
Issue with Friendly URL while product update

### ISSUE THREAD

**Issue by Huzefa-anchanto** [PrestaShop/PrestaShop#13762] opened 2019-05-13 05:21 UTC
Hi Prestashop Team, 
We are facing an issue with the field Friendly URL while product update, details of which are mentioned below: 

The issue we are facing is with a field name as "Friendly URL". In this field if we input any random value as "abc.com" it accepts during product creation (API) but it doesn't allow the product to be updated because of the ".com" part in the field value. 
The expected scenario here is Prestashop should not allow a product to be created with any random values as "abc.com" as this is invalid value with respect to the field. 

Below is the requests body for the same for which we use post method to create the product: 

Request:

```
<?xml version='1.0' encoding='UTF-8'?>
<prestashop>
	<product>
		<id_supplier>3</id_supplier>
		<id_manufacturer>3</id_manufacturer>
		<id_tax_rules_group>1</id_tax_rules_group>
		<width>10</width>
		<height>10</height>
		<depth>10</depth>
		<weight>10</weight>
		<id_category_default/>
		<id_shop_default>1</id_shop_default>
		<on_sale>1</on_sale>
		<ean13>1234567</ean13>
		<upc/>
		<price>889.38</price>
		<wholesale_price/>
		<ecotax/>
		<unit_price_ratio/>
		<unity/>
		<reference>Leather Bag Collection</reference>
		<active>1</active>
		<available_for_order>1</available_for_order>
		<condition>new</condition>
		<visibility>both</visibility>
		<show_price>1</show_price>
		<online_only>0</online_only>
		<name>
			<language id='1'>Leather Bag Collection</language>
		</name>
		<description>
			<language id='1'>Leather Bag Collection</language>
		</description>
		<description_short>
			<language id='1'>Short Desc</language>
		</description_short>
		<link_rewrite>
			<language id='1'>xyz.com</language>
		</link_rewrite>
		<meta_title>
			<language id='1'>Meta</language>
		</meta_title>
		<meta_description>
			<language id='1'>Meta</language>
		</meta_description>
		<meta_keywords>
			<language id='1'>Meta</language>
		</meta_keywords>
		<associations>
			<tags>
				<tag>
					<id>106</id>
				</tag>
				<tag>
					<id>28</id>
				</tag>
				<tag>
					<id>297</id>
				</tag>
			</tags>
			<categories>
				<category>
					<id>24</id>
				</category>
			</categories>
		</associations>
	</product>
</prestashop>

```
Response:
Product created successfully. 

Expected:
The product shouldn't be created by returning an error as an invalid value for field Friendly URL. 

Can you please look into it and let us know a solution for this issue?

**Comment by khouloudbelguith** [comment] 2019-05-13 11:32
Hi @Huzefa-anchanto,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1.
I used this script
```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 13/05/19
 * Time: 11:44
 */

ini_set('display_errors','on');
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true); // Debug mode
//                      !! BACHA, nezapomenout přenastavit i DTB u obrázků dole !!!
define('PS_SHOP_PATH', 'http://shop.com'); // Root path of your PrestaShop store
define('PS_WS_AUTH_KEY', 'Key'); // Auth key (Get it in your Back Office)
require_once('./PSWebServiceLibrary.php');

$psXML = <<<XML
<prestashop>
<product>
  <id/>
  <state>1</state>
  <id_category_default>2</id_category_default>
  <active>1</active>
  <advanced_stock_management>1</advanced_stock_management>
  <associations>
    <categories>
      <category><id>2</id></category>
    </categories>
  </associations>
  <reference>boom</reference>
  <name>
  <language id="1">abc.com</language></name>
  <price>100</price>
  <id_shop_default>1</id_shop_default>
  <low_stock_alert>0</low_stock_alert>
  <link_rewrite>abc.com</link_rewrite>
  <show_price>1</show_price>
  <minimal_quantity>1</minimal_quantity>
  <available_for_order>1</available_for_order>
</product>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
var_dump($xml->asXML());
$opt = array( 'resource' => 'products' );
$opt['postXml'] = $xml->asXML();
//$opt['id_shop'] = 'all';
/*for ($i = 1; $i <= 10000; $i++) {
    $xml = $webService->add( $opt );
}*/

$xml = $webService->add( $opt );
```

I have an error

```
RETURN HTTP BODY
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[84]]></code>
<message><![CDATA[Validation error: "Property Product->link_rewrite is not valid"]]></message>
</error>
</errors>
</prestashop>
```
![image](https://user-images.githubusercontent.com/16067358/57618301-ecc05b80-757a-11e9-860d-e3dc86cba5b7.png)
Thanks to check & feedback

**Comment by khouloudbelguith** [comment] 2019-06-12 07:31
Hi @Huzefa-anchanto,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-12 07:31 UTC
Labels: WS, No change required
