### ISSUE TITLE
BO - Orders - An alert is displayed when my email service is not configured

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34318] opened 2023-10-17 12:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I update my order status without having my email service configured, I have a message alert : 
`An error occurred while changing the status for order #4, or we were unable to send an email to the customer.`
Also my status is not updated.

<img width="1221" alt="Screenshot 2023-10-17 at 12 16 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/aafec731-999b-427b-bb94-b9421218f82a">

I have to do it twice before seeing a change.

Reproduced with develop branch only.
The error is similar to https://github.com/PrestaShop/PrestaShop/issues/17615

### Expected behavior

I should be able to update my status on the first try.

### Steps to reproduce

1. Go to BO > Orders 
2. Update status
3. See alert :x: `An error occurred while changing the status for order #4, or we were unable to send an email to the customer.` 
4. Update status once more
5. Status is well updated

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment] 2023-10-24 13:40
Hi @florine2623,

Thank you for your report, Despite our efforts, we were not able to reproduce your issue with the provided information, as you can see : 

[Untitled_ Oct 24, 2023 3_35 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/5573937b-71fd-4cb2-a563-28c488c154dc)

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by AureRita** 2023-10-24 13:40 UTC
Labels: Bug, develop, Minor, BO, Order, Order statuses, Invalid
