### ISSUE TITLE
Shipping number is empty in {followup} if In transit email is launched with the WebService

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#10115] opened 2018-08-24 10:11 UTC
When you call update OrderCarrier with Prestashop WebService, the Shipping number is empty in the {followup} URL.

The bug is in sendInTransitEmail (OrderCarrier class), $order->shipping_number is empty.

PrestaShop version: 1.7

**Comment by khouloudbelguith** [comment] 2018-08-24 10:37
Hi @jf-viguier, 

I manage to reproduce your issue with the last version 1.7.4.2.
We will see how to fix it.
#10069 
Previous ticket in the forge: http://forge.prestashop.com/browse/BOOM-4228

Best regards, Khouloud

**Comment by jf-viguier** [comment] 2018-08-24 11:00
I've fixed it here https://github.com/PrestaShop/PrestaShop/pull/10117

**Comment by khouloudbelguith** [comment] 2018-08-24 11:01
Hi @jf-viguier ,

Thanks for your fix.

Best regards, Khouloud

**Comment by matks** [comment] 2018-08-28 11:08
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10117

**Comment by marionf** [comment] 2018-08-29 08:11
Reopened because the PR isn't merged yet

**Closed as completed** 2018-08-30 09:10 UTC
Labels: Bug, WS, Fixed, 1.7.4.2
