### ISSUE TITLE
updateProductPrice is pending for 15/30 sec in admin order

### ISSUE THREAD

**Issue by azralth** [PrestaShop/PrestaShop#16901] opened 2019-12-23 10:02 UTC
When i add new order in admin, and update the unit price tax exc, the price tax inc is taking too long to update. The ajax call function updateProductPrice is pending for 15/30 sec

1 Go to admin -> order
2 Choose a customer
3 Add a product to a cart
4 Update unit price tax exc
5 Wait for 15/30 sec to get the prix tax inc update.

PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-12-23 10:13
Hi @azralth,

I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1xjmwWQUiE0KuyyCR7fQ-TGJT7nfnBJVn/view
Could you please try to enable profiling mode
In your `Projetc_Folder/config/defines.inc.php`, you need to replace this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', flase);
}
```

by this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', true);
}
```
When profiling mode is enabled, you should have information about the time needed to run queries.

Thanks!

**Comment by azralth** [comment] 2019-12-23 10:27
Hi,
I just found what is goin on. I use filesystem cache in this site. I just cleared the cache and now price is update instantly. This is wired. Why i have to cleared the cache to get the query instantly ...

I have not cleared it for 3 weeks.
Thanks

**Comment by khouloudbelguith** [comment] 2019-12-23 10:39
@azralth, thanks for your feedback.
Since it is fixed, I will close the issue.
Feel free to open a new one hen needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-23 10:39 UTC
Labels: Bug, BO, Order, No change required, 1.7.5.2
