### ISSUE TITLE
Cannot delete adress from the FO 1.7.6.1

### ISSUE THREAD

**Issue by Traineau** [PrestaShop/PrestaShop#15957] opened 2019-10-15 09:57 UTC
**Describe the bug**
When I want to delete one of my adress in My account section on the Front-office, it display me a "Could not delete address." error. It seems that it's related to the CustomAdressPersister class, because in order to make it work I've rewrote the AdressController postProcess this way : 

```
<?php

class AddressController extends AddressControllerCore
{
   
    /**
     * Start forms process.
     *
     * @see FrontController::postProcess()
     */
    public function postProcess()
    {
        $this->context->smarty->assign('editing', false);
        $this->address_form->fillWith(Tools::getAllValues());
        if (Tools::isSubmit('submitAddress')) {
            if (!$this->address_form->submit()) {
                $this->errors[] = $this->trans('Please fix the error below.', array(), 'Shop.Notifications.Error');
            } else {
                if (Tools::getValue('id_address')) {
                    $this->success[] = $this->trans('Address successfully updated!', array(), 'Shop.Notifications.Success');
                } else {
                    $this->success[] = $this->trans('Address successfully added!', array(), 'Shop.Notifications.Success');
                }
                $this->should_redirect = true;
            }
        } elseif (($id_address = (int) Tools::getValue('id_address'))) {
            $this->address_form->loadAddressById($id_address);

            if (Tools::getValue('delete')) {
                 // Not using the AdressPersister
                $ok = (new Address($id_address, $this->context->language->id))->delete();
                
                if ($ok) {
                    $this->success[] = $this->trans('Address successfully deleted!', array(), 'Shop.Notifications.Success');
                    $this->should_redirect = true;
                } else {
                    $this->errors[] = $this->trans('Could not delete address.', array(), 'Shop.Notifications.Error');
                }
            } else {
                $this->context->smarty->assign('editing', true);
            }
        }
    }
}

```

It seems to work well, so I don't know if the AdressPersister class is really usefull and why it doen't work.

**To Reproduce**
1. Custom theme
2. Create two adresses 
3. Try to delete one

**Screenshots**
![Capture d’écran 2019-10-15 à 11 56 41](https://user-images.githubusercontent.com/20043825/66821552-ea579880-ef42-11e9-8a94-2ce675a6e011.png)
![Capture d’écran 2019-10-15 à 11 56 50](https://user-images.githubusercontent.com/20043825/66821561-ee83b600-ef42-11e9-9116-ba3bc671e03c.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-15 10:02
Hi @Traineau,

I did not manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/16hxdcUO0KxlDFxH1JQALHG2IEq4yk5Te/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Traineau** [comment] 2019-10-15 10:20
Hello @khouloudbelguith 

Here is all I've got, but there's nothing I can see concerning this event :/ I emptied them and tried to delete the adress multiple times.

**Prestashop informations :**
![Capture d’écran 2019-10-15 à 12 11 02](https://user-images.githubusercontent.com/20043825/66822987-94d0bb00-ef45-11e9-9bd4-0762dd6d29b5.png)

**JavaScript Console errors (nothing) :**

![Capture d’écran 2019-10-15 à 12 14 06](https://user-images.githubusercontent.com/20043825/66823032-aade7b80-ef45-11e9-9b6a-912211ce8806.png)

**PhP error logs :**

[dev.log](https://github.com/PrestaShop/PrestaShop/files/3728665/dev.log)

**Apache error logs is empty**

**Comment by khouloudbelguith** [comment] 2019-10-15 10:40
@Traineau, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by Traineau** [comment] 2019-10-15 12:06
Just tried it, nothing changed. Do you have any informations on what the CustomerAdressPersistor is supposed to do ?

**Comment by khouloudbelguith** [comment] 2019-10-15 13:22
@Traineau, this class: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/form/CustomerAddressPersister.php?
no, but we can ask the developers: ping @PrestaShop/prestashop-core-developers
In the meantime, have you tried to contact the theme author about this issue?

Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment] 2019-11-14 07:51
Hi @Traineau,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-14 07:51 UTC
Labels: Bug, FO, Addresses, No change required, 1.7.6.1

**Comment by MONA4GITHUB** [comment] 2023-07-20 11:33
Hey, same issue there on Prestashop 1.7.8.8 

Any client cannot delete any address from their account in front office. 

Any idea how to solve it ? 
![2023-07-20 13_31_59-Address and 3 more pages - Work - Microsoft​ Edge](https://github.com/PrestaShop/PrestaShop/assets/127497359/623f31fc-8ebe-481d-8570-a32bcd6ba645)
