### ISSUE TITLE
error search console : Either "offers", "review", or "aggregateRating" should be specified

### ISSUE THREAD

**Issue by feyll** [PrestaShop/PrestaShop#12802] opened 2019-03-06 08:20 UTC
![screenshot 54](https://user-images.githubusercontent.com/27018255/53866021-d2a15480-3ff0-11e9-9838-42b4df12efb0.png)

Hello everyone, now I think this problem is known in the new version of Google Search Console.
Please do you have any suggestions to correct this?
Thanks to everyone and good work

**Comment by khouloudbelguith** [comment] 2019-03-06 08:26
Hi @feyll,

Your ticket is a duplicate of #12687
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-06 08:26
Duplicate of #12687

**Closed as completed by khouloudbelguith** 2019-03-06 08:26 UTC
Labels: Duplicate
