### ISSUE TITLE
BO>Positions: you can not transplant a module neither edit a hook

### ISSUE THREAD

**Issue by lramos-prolaser** [PrestaShop/PrestaShop#28074] opened 2022-03-30 08:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Testing the `develop` branch and the new hummingbird theme, in the BO I went to Design -> Positions and clicked on "Transplant a module" button. 
![image](https://user-images.githubusercontent.com/90182741/160790707-a07fe025-0272-4bc1-9f2a-135f8ae0003e.png)

And this bug appeared :
![image](https://user-images.githubusercontent.com/90182741/160789507-effa3858-e16d-4924-9564-d01a4aaa016b.png)

And when you try to edit a hook
https://user-images.githubusercontent.com/100699445/161978454-98c585c3-1e72-4c8c-93f2-ceeb3346c134.mp4

I searched for related issues to form.tpl missing and I found this one #27543. I think they are related.

### Expected behavior

I should be able to transplant a module

### Steps to reproduce

1. Go to Design -> Positions
2. Click on "Transplant a module" button
3. See the bug appears

Another scenario
1. Go to BO
2. Go to Design > Position
3. Click on the Edit button near a module
4. The Exception appear 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-03-30 10:58
Hello @lramos-prolaser 

I was able to reproduce the issue on develop. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by rsoulard-prolaser** [comment] 2022-03-30 12:00
Hello @hibatallahAouadni,
The bug appears from this commit https://github.com/PrestaShop/PrestaShop/commit/bdca66904ff37a8e5663aaee736cc7788af0d365.
The folder `/admin-dev/themes/default/template/controllers/modules_positions/` has been deleted.

**Closed as completed** 2022-04-11 14:13 UTC
Labels: Bug, 8.0.x, Major, BO, Design, Positions, Regression, Fixed, PR available, Verified
