### ISSUE TITLE
Errors to upgrade from 1.7.4.x to 1.7.5.x

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#13674] opened 2019-05-05 18:32 UTC
Hi
today I've tried for the second times with another site to upgrade from 1.7.4.2 to 1.7.5.2 (the problem was present also when I tried to upgrade to the past 1.7.5.1)
using the 1-click upgrade module the updating is stopped when it tries to upgrade the database

Error during database upgrade. You may need to restore your database.
Error updating translations

I've upgraded other sites from 1.7.5.0 or 1.7.5.1 to 1.7.5.2 and all was ok
at this moment I cannot upgrade sites with 1.7.4.x to the last one

both sites are multi-languages

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/57198522-2c33ea00-6f74-11e9-8b27-03539fb089a7.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0
Module version: 4.7.0

bye

**Comment by Maofree** [comment] 2019-05-05 21:39
Hi
I've upgraded all those 3 sites to the 1.7.5.2 with debug mode enabled and all went well
so I don't know if it is present some bugs or not
finally they are updated

bye

**Comment by khouloudbelguith** [comment] 2019-05-07 09:38
Hi @maofree,

Thanks for your report.
I did not manage to reproduce the issue with the 1-click upgrade v4.7.0.
I attached a video record
https://drive.google.com/file/d/18t1bzUls03Eo--XpVLPTNHKvyOdhnC5e/view
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-07 07:29
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-06-07 07:29 UTC
Labels: Bug, BO, Can't reproduce, Autoupgrade, 1.7.4.2

**Comment by ITProfeska** [comment] 2020-02-09 20:34
Hello, 

can we reopen this case ? I've got the same issue.

Regards
Slavo

**Comment by khouloudbelguith** [comment] 2020-02-10 11:15
Hi @ITProfeska,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
