### ISSUE TITLE
Allow/disollow product out of stock - Revert Changes on product creation

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#17016] opened 2020-01-02 21:03 UTC
Prestashop upgraded from 1.7.5.2 to 1.7.6.2 went smooth without errors.

Like in title, when i try to change setting it goes back after edit/add new product. [Allow disallow order product of out stock]
see video:
https://drive.google.com/open?id=1iEYFWtwEVtWg9ODH-QHrF2q0FcqPHjiD
Already tried with turned off modules/overrieds and dev even with maintence mode.

When i made copy of shop with same database / files it did save changes.

Apache/2.4.25 (Debian)
PHP: 7.2.25-1
DB: 10.1.41-MariaDB-0+deb9u1
Memory limit: 2048M

**Comment by khouloudbelguith** [comment] 2020-01-03 08:14
Hi @slupostrupek,

Thanks for your report.
>Already tried with turned off modules/overrieds and dev even with maintenance mode.

Did you enable those options in the BO => Advanced Paramteres => Performance page?
![image](https://user-images.githubusercontent.com/16067358/71713305-73c38c00-2e09-11ea-805b-356daf7684a8.png)

Thanks!

**Comment by slupostrupek** [comment] 2020-01-03 10:44
yes, i tried

**Comment by khouloudbelguith** [comment] 2020-01-03 10:47
@slupostrupek, sorry, but those options do not work in PrestaShop as reported here:
1. https://github.com/PrestaShop/PrestaShop/issues/14596
2. https://github.com/PrestaShop/PrestaShop/issues/9965

Thanks to check & feedback.

**Comment by slupostrupek** [comment] 2020-01-03 16:30
ok, indeed it was somewhat module issue, but after uinstall it, prestashop still didn't work correctly i had change every product on default behavior:
`UPDATE ps_stock_available SET out_of_stock = 2
UPDATE it_ps_product SET out_of_stock = 2
`
instead of '0'

**Comment by khouloudbelguith** [comment] 2020-01-03 16:32
@slupostrupek,

>but after uninstall it

Did you check if you have an override? thanks to rename it & clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by slupostrupek** [comment] 2020-01-03 17:31
yes, override disappear after uninstall.


Cache cleared manually from var/cache

**Comment by khouloudbelguith** [comment] 2020-01-06 09:05
@slupostrupek, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-03 08:13
Hi @slupostrupek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-03 08:13 UTC
Labels: Bug, BO, Product settings, No change required, 1.7.6.2
