### ISSUE TITLE
ContextErrorException in CustomerFormatter.php line 215:

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#12551] opened 2019-02-13 11:00 UTC
Hello, I've the same problem like this https://github.com/PrestaShop/PrestaShop/issues/10439 but as willy2m does'nt reply anymore, I don't know if his problem is solved.
If the debug mode is enabled, I receive this message at the last step of order

![image](https://user-images.githubusercontent.com/11886689/52706356-829d1800-2f85-11e9-9f4c-81e50c714a86.png)

RGPD version : 1.1.12 (just upgraded to see if the issue is resolved but not)
PS : 1.7.2.4
PHP : 7.0.33
Theme : ZOneTheme
URL : http://preprod2.audilo.com

Different users have tested, with differents products, it's always the same.

If RGPD module is unabled, there is no error.

Thanks for your reply.

**Comment by khouloudbelguith** [comment] 2019-02-13 11:13
Hi @sirius82,

I did not manage to reproduce the issue with PS1.7.5.0 & the RGPD module v1.1.2.
I attached a video record.
https://drive.google.com/file/d/14H-uS6xMH_fSAZFB027NwXMzF68gPjx7/view
Thanks to check & feedback.

**Comment by sirius82** [comment] 2019-02-13 15:45
Hi khouloudbelguith ! Thanks for your reply but sorry for my stupid answer : is your debug enabled ?

**Comment by khouloudbelguith** [comment] 2019-02-13 16:04
@sirius82, yes, it is enabled.
https://drive.google.com/file/d/1z8x6rUxeb60F5wMWbSxoeQ2fwt0Er2au/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-15 07:30
Hi @sirius82, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-15 07:30 UTC
Labels: Bug, FO, 1.7.2.4, GDPR, No change required
