### ISSUE TITLE
Place order button always disabled IF 100% discount coupon AND setting Terms of service is no

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#22202] opened 2020-12-02 20:22 UTC
#### Describe the bug

If "Terms of service" is checked to be "no" and order contains 100% discount (making it a free order) it is not possible to complete the order. Going through the order process is not possible as "Place order" button stays disabled and there is no way of enabling the button. My guess is that there is no js check for this situation and nothing triggers the checks as there is no payment option selection nor checking of the terms of service checkbox.

#### Expected behavior

The "Place order button" should be enabled when the Payment step is opened if there is nothing to select or terms of service to check.

#### Steps to Reproduce

1. BO: Change shop setting "Terms of service" to no (Shop parameters -> order settings)
2. BO: Add a discount coupon rule with 100% and free shipping actions (Catalog -> discounts)
3. Go to shop storefront
4. Add product to basket
5. Go trough the order process to Payment step (check that shipping is also 0 priced and order total is 0)
6. Try to click on "Place order"
=> button is disabled and clicking does nothing

While taking screenshots also noticed that clicking on the "No payment needed for this order" triggers js warning:
```
jQuery('#') is not a valid selector    core.js:92 
```
(Actually that seems to happen in quite a lot of places on that page, at least total line on the right side and all the subtotals above it etc.)

**Screenshots**

#### Settings
Discount:
![image](https://user-images.githubusercontent.com/1352132/100926207-babf7300-34eb-11eb-9e8c-96382f47c09d.png)
Terms of service:
![image](https://user-images.githubusercontent.com/1352132/100926250-c9a62580-34eb-11eb-8826-6d1dcbacdb52.png)

#### Place order disabled
![image](https://user-images.githubusercontent.com/1352132/100926467-2c97bc80-34ec-11eb-868f-aa8474d0b09a.png)

#### Additional information

* PrestaShop version: 1.7.7.0 (also seen on 1.7.6.7)
* PHP version: 7.3.17

**Comment by hibatallahAouadni** [comment] 2020-12-03 13:11
Hello @tswfi 

I managed to reproduce the issue with PS1.7.6.9 and PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1nDKzxkB5ZSgmmbe1Jck2erlXH2AC-XDE/view

AFAIK, I think the status of the button required one of these two conditions to be true (payment or terms of service).
Ping @PrestaShop/product-team wdyt? is it a bug or is that the normal behavior?

Thanks!

**Comment by marionf** [comment] 2020-12-03 15:12
@hibatallahAouadni It seems to be a duplicate of #9927
Could you please verify ?

**Comment by hibatallahAouadni** [comment] 2020-12-03 15:29
Thanks @marionf indeed it's a duplicate :+1:

**Comment by hibatallahAouadni** [comment] 2020-12-03 15:31
Hello @tswfi 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9927. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-03 15:31
Duplicate of #9927

**Closed as completed by hibatallahAouadni** 2020-12-03 15:31 UTC
Labels: Bug, FO, Duplicate, Order settings, Checkout, 1.7.7.0
