### ISSUE TITLE
After update to PS 1.7.6.3 blockreassurance module automatically downgrade

### ISSUE THREAD

**Issue by rzuf666** [PrestaShop/PrestaShop#17361] opened 2020-01-26 14:07 UTC
**Describe the bug**
I had a blockreassurance module version 4.1.1, after update to PS 1.7.6.3 (from 1.7.6.2)   this module automatically downgrade to version 3.0.1.  Is it intended that there is an older version of this module in the PrestaShop 1.7.6.3 package? In official package (1.7.6.3) from Presta site there is older version of blockreassurance module.

**To Reproduce**
1. Go to 1 click update in PS 1.7.6.2 with blockreassurance module v4.1.1
2. Update Presta to 1.7.6.3
3. After update blockreassurance module is downgrade to version 3.0.1 with theme view of this module.

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-01-27 11:12
Hi @rzuf666,

I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1.
I attached a screen record
https://drive.google.com/file/d/1E1DfQtOLRBoZhw3eWwd06IToJtOR9WxY/view

Thanks to check & feedback.

**Comment by rzuf666** [comment] 2020-01-27 17:51
@khouloudbelguith I saw the video, it worked for you as it should, but after installation in my case, the return to the module configuration showed the old look coming from PS 1.6. The list of installed modules in my case still displayed that I have the module in version 4.1.1, but when I checked the files on the server, it turned out that the entire folder of the module contains its old version 3.0.1

So how do you explain that in the package from PrestaShop 1.7.6.3 downloaded from the site (https://www.prestashop.com/en/download) is in the folder "modules" version 3.0.1 of the blockreassurance module? I attach a screen of the package content downloaded on 27/01/2020

![ps-1763-module](https://user-images.githubusercontent.com/60318358/73199435-20f1a180-4135-11ea-8e20-3e9124cf5dc1.jpg)

**Comment by khouloudbelguith** [comment] 2020-01-28 08:10
@rzuf666, as you can see in this link: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.3/composer.lock#L3136
The `blockreassurance` module is a native module & the release of this module in the PS1.7.6 is v3.0.1.
PS1.7.6.3 is not a major release.
In the next Major release PS1.7.7.0, [the blockreassurance module will be 4.1.1](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/composer.lock#L3705).

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-27 07:58
Hi @rzuf666,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-27 07:58 UTC
Labels: Bug, BO, Autoupgrade, No change required, Blockreassurance, 1.7.6.3
