### ISSUE TITLE
On version 2.2.0 is sending email to all employees with no vendor profile 

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#20825] opened 2020-07-09 15:42 UTC
Hi the version 2.2.0 is sending out of stock email to all employees with no vendor profile, it should only send the out the stock email to the email that are configure on the module.

![image](https://user-images.githubusercontent.com/46203943/87061050-418c5000-c1d9-11ea-93d6-3bd2474c114e.png)

**Comment by florine2623** [comment] 2020-09-04 15:26
Hi @msaustral ,
Are all of the employees mentioned on the email list on the module here ?
![Capture d’écran 2020-09-04 à 17 25 59](https://user-images.githubusercontent.com/16019289/92256251-c93dc480-eed3-11ea-991c-0d06e817de0d.png)
Thanks!

**Comment by msaustral** [comment] 2020-09-04 15:38
Hi they are no on the list, that is the issue.

**Comment by khouloudbelguith** [comment] 2020-09-07 09:07
Hi @msaustral,

I did not manage to reproduce the issue with `ps_emailalerts` module v2.2.1.
I received those mails
![image](https://user-images.githubusercontent.com/16067358/92369895-ddfba180-f0f9-11ea-891b-7e1e162ce0f5.png)
Here's my configuration
![image](https://user-images.githubusercontent.com/16067358/92369968-f2d83500-f0f9-11ea-8d12-2f345661d83f.png)
Here's the list of employee's
![image](https://user-images.githubusercontent.com/16067358/92370060-126f5d80-f0fa-11ea-8116-9075e92bd561.png)

In the BO > Product details page > Quantities Tab > we have an option
`Send me an email when the quantity is below or equals this level `
If this option is selected
The email will be sent to all the users who have the right to run the stock page. To modify the permissions, go to Advanced Parameters > Team
![image](https://user-images.githubusercontent.com/16067358/92370172-3a5ec100-f0fa-11ea-8125-2f94e07bd30b.png)

Thanks to check and feedback.

**Comment by msaustral** [comment] 2020-09-07 15:27
Hi, thank you for your answer, we will check and get back to you, thank you

**Comment by khouloudbelguith** [comment] 2020-09-07 15:32
@msaustral, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2020-09-28 12:01
Hi @msaustral,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-09-28 12:01 UTC
Labels: No change required, 1.7.6.7, ps_emailalerts
