### ISSUE TITLE
Can't edit specific price

### ISSUE THREAD

**Issue by Marwazeinoo88** [PrestaShop/PrestaShop#12345] opened 2019-01-29 11:18 UTC
Hi, 
I'm adding more then 1200 products, so it's easier for me to duplicate products that are similar and only do some simple editing...
But when i add a"**Specific price**" it works on front office, and once i need to edit the "Specific price"on BO i just can't beacause this board (attached) is not there any more!!
![capture](https://user-images.githubusercontent.com/43037924/51904248-767a5d80-23be-11e9-8852-3c185e17660b.PNG)
Is that a bug on prestashop 1.7.3.0 ?

**INFORMATIONS** 
 Informations sur votre serveur Linux #1 SMP Thu Jan 4 16:43:57 MSK 2018 x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.1.20
Limite de mémoire : 256M
Temps maximal d'exécution : 80
Taille max. pour envoi de fichiers : 200M
Version de PrestaShop : 1.7.3.0

**Comment by khouloudbelguith** [comment] 2019-01-29 11:28
Hi @Marwazeinoo88,

This feature is added to the last version PS1.7.5.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9465
Your ticket is a duplicate of #10171
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-29 11:28
Duplicate of #10171

**Closed as completed by khouloudbelguith** 2019-01-29 11:28 UTC
Labels: Duplicate
