### ISSUE TITLE
Guest order tracking doesn't work

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21800] opened 2020-11-06 23:45 UTC
#### Describe the bug
You use the link (https://domain/index.php?controller=guest-tracking) for guest order tracking e.g. in email for orders status  Awaiting for bank wire payment but the link doesn't work. After clicking PS will jump to the homepage.
If you write this link manually to the browser then Guest order tracking screen is displayed. After filling reference and email address PS will jump to the homepage.

#### Expected behavior
The link should work otherwise it is not possible to track the order for guests. 
On the Guest order tracking screen are missing validations after pressing the button Send:
- order reference - mandatory field
- email - mandatory field

#### Steps to Reproduce
Example 1:
1. Enter link https://domain/index.php?controller=guest-tracking to the address field in any internet browser
2. Screen Guest order tracking is displayed
3. Press the button Send > ERROR - PS displays homepage, but there should be an error message "Enter mandatory fields order reference and email"

Example 2:
1. Place an order as a guest user
2. Enter link https://domain/index.php?controller=guest-tracking to address in any internet browser
3. Screen Guest order tracking is displayed
4. Enter order reference and email from your order and press the button Send > ERROR - PS doesn't display any track 

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment] 2020-11-09 08:48
Hello @juraj1000 

I didn't manage to reproduce your issue with PS1.7.6.8 and PS1.7.7.0-rc.1+build.4.
I attached a Screen recored below:

https://drive.google.com/file/d/13dkYyxibrE0mdAAoH8tp16go-x7CCgOG/view

And could you please check this ticket #20194 if is it similar to your case or no?

Please check and feedback.

Thanks!

**Comment by juraj1000** [comment] 2020-11-09 20:42
Hello @hibatallahAouadni,
you use different link for guest tracking in your video example. I use the link https://domain/index.php?controller=guest-tracking and it doesn't work. Which link is correct?

**Comment by hibatallahAouadni** [comment] 2020-11-09 20:58
Hi @juraj1000 

The one shown in my screen record is the right one.

Could you please try it and feedback.

Thanks!

**Comment by juraj1000** [comment] 2020-11-09 21:32
Hello @hibatallahAouadni,
do you mean [https://domain/en/guest-tracking](https://domain/en/guest-tracking) or [https://domain/prestashop_1.7.6.8/en/guest-tracking](https://domain/prestashop_1.7.6.8/en/guest-tracking)?

**Comment by hibatallahAouadni** [comment] 2020-11-09 21:39
Hi @juraj1000 

I meant 

```
https://domain/guest-tracking
```

If you use multilanguage and the English language is enabled, then add "en"

```
https://domain/en/guest-tracking
```

Please check and feedback.

Thanks!

**Comment by juraj1000** [comment] 2020-11-10 06:53
Hello @hibatallahAouadni,
still no link works. I have more core modules disabled because I don't need them. Which module has to be activated for working the link?

**Comment by hibatallahAouadni** [comment] 2020-11-10 08:25
Hello @juraj1000 

> still no link works

What do you mean? the links does not display the form or when you click on the button "send", an error is displayed?

Could you please check if this issue #20194 is similar to yours, cause it seems to me is the same, please check, you may find your answer.

Thanks!

**Comment by juraj1000** [comment] 2020-11-10 20:32
Hello @hibatallahAouadni,
you're right, it's the same issue

**Comment by hibatallahAouadni** [comment] 2020-11-11 08:24
Hello @juraj1000 

We are aware of this issue. The problem is fixed in the next release PS1780. 
Your ticket is a duplicate of #20194
Please subscribe to the issue mentioned above, cause I'm closing this one.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-11 08:24
Duplicate of #20194

**Closed as completed by hibatallahAouadni** 2020-11-11 08:24 UTC
Labels: Bug, FO, Duplicate, Checkout, 1.7.6.8
