### ISSUE TITLE
The translation of the pagination label in products list and combinations list is not correct

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#32053] opened 2023-04-05 12:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The translation of the pagination label in products list and combinations list is not correct => 
'**Viewing 1-21 on 21 (page 1 / 1)**' instead of '**Viewing 1-21 out of 21 (page 1 / 1)**'

=> In products page
![Capture d’écran de 2023-04-03 16-58-28](https://user-images.githubusercontent.com/24647495/230084018-b15852e1-5b41-4f07-b566-7b6303dba7c1.png)

=> In combinations list
![Capture d’écran de 2023-04-04 14-35-40](https://user-images.githubusercontent.com/24647495/230084159-6478b0e1-b734-4244-b34f-3ae6d4405f2a.png)

PS : Should be tested in docker

### Expected behavior

The pagination label should be => '**Viewing 1-21 out of 21 (page 1 / 1)**'
![Capture d’écran de 2023-04-05 14-49-05](https://user-images.githubusercontent.com/24647495/230085162-cc82a4c6-1e40-46eb-bff0-62cee189ba5a.png)

### Steps to reproduce

1- Go to 'Catalog > Products' page
2- Create 2 products to display the pagination (if PPV1)
3- See the error

### PrestaShop version(s) where the bug happened

8.0.x and 8.1.x

### PHP version(s) where the bug happened

7.3

**Comment by djoelleuch** [comment] 2023-04-06 11:37
Hi  @nesrineabdmouleh ,
I have tested your issue and I can't reproduce the bug as you can see here :
for PS 8.1.x : OK

[ppv2_81x.webm](https://user-images.githubusercontent.com/115152460/230362784-0dd29e7b-3194-4145-a5b6-7bc01393b71a.webm)

https://user-images.githubusercontent.com/115152460/230364597-9db6a641-4da3-4027-a10f-96467e69f4a8.mp4

for PS 8.0.x  : OK

[productppv2-80x.webm](https://user-images.githubusercontent.com/115152460/230364731-cb00c378-325a-43c9-8492-2dffa68c8664.webm)


![combin80x](https://user-images.githubusercontent.com/115152460/230364758-6929210c-da23-4ee4-83dc-2e047ba0a1bc.png)

Could you please check & feedback ^
Thank you !

**Comment by Progi1984** [comment] 2023-04-11 13:52
Fixed by @jolelievre in #32112

**Closed as completed by Progi1984** 2023-04-11 13:52 UTC
Labels: Bug, 8.0.x, Regression, Fixed, Detected by TE, Docker
