### ISSUE TITLE
Main menu disables itself automatically

### ISSUE THREAD

**Issue by TVBZ** [PrestaShop/PrestaShop#20116] opened 2020-07-09 07:44 UTC
#### Describe the bug

When making changes in modules (module manager) and positions (design -> positions), the main menu module disables itself automatically. I can't pinpoint when exactly this happens, but it's pretty clear it's allways after making changes in positions or modules.

#### Expected behavior

If the module is enabled, it should remain enabled.
It should only be disables when it is manually disabled (or by theme or such).

#### Steps to Reproduce

Not sure if this part matters, but in my scenario, the main menu module is hooked to "displayTop".
Ok, it might not be easy to reproduce, but here are some ways I have the problem regularly:

1. Go to Module Manager
2. Open Facetted search, make some changes and rebuild indexes
   AND/OR open links widget and add some links to a block
   AND/OR open featured products and switch the random products setting and change the number of products
   AND/OR make some changes in module positions
   ...
3. Go to front end and see if the main menu is still enabled

#### Possible fix / workaround

I found a working solution to this issue in PrestaShop forum.
It's pretty simple. I just **removed the blocktopdropdownmenu**.

[https://www.prestashop.com/forums/topic/995627-main-menu-automatically-disables/?tab=comments#comment-3213088
](https://www.prestashop.com/forums/topic/995627-main-menu-automatically-disables/?tab=comments#comment-3213088
)
#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-07-09 09:07
Hi @TVBZ ,
I tried to reproduce your issue in PS 1.7.6.5 and 1.7.7.0 without success.
I followed the full step 2 of your issue, the main menu is still enabled and displayed on the front.
Here's a screen recording : https://drive.google.com/file/d/14aoE6z0AOhWuw2Zsbs_snj0D9ktpI6Ja/view
Thanks!

**Comment by florine2623** [comment] 2020-07-24 10:18
Hi @TVBZ ,
Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.
Thanks!

**Closed as completed by florine2623** 2020-07-24 10:18 UTC
Labels: Positions, No change required, 1.7.6.5
