### ISSUE TITLE
Cannot uninstall module from the Module Manager

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#25441] opened 2021-07-27 15:46 UTC
#### Describe the bug

Try to uninstall any module from the module manager, you'll see the error saying "Cannot perform the action on the undefined module"

#### Expected behavior

Successful uninstallation of the module

#### Steps to Reproduce

1. Open the Module manager
2. Try to uninstall a module

#### Additional information

* PrestaShop version: 8.0.0
* PHP version: N/A

**Comment by deepindersingh83** [comment] 2021-07-27 16:10
> * PHP version: N/A



Same Issue with the Prestashop version: 1.7.7.5
PHP version: 7.4

**Comment by florine2623** [comment] 2021-07-27 16:17
Hello @kpodemski ,

I can't reproduce your issue in PS 8.0.0.

I successfully uninstalled module Available Quantities :
<img width="434" alt="Screenshot 2021-07-27 at 18 16 26" src="https://user-images.githubusercontent.com/16019289/127190140-6596a76f-335a-4c0d-a17f-47d2ba6fe4ee.png">

Did you try with a specific module ?

Thanks!

**Comment by kpodemski** [comment] 2021-07-27 16:18
@deepindersingh83 PrestaShop 1.7.7 is not compatible with 7.4, can you try with 7.3?

**Comment by kpodemski** [comment] 2021-07-27 16:20
@florine2623 

any module, it cannot work because `$(this)` is not in the right context if there's an arrow function syntax used

have you tried to run `make assets`? this error is coming from TypeScript version of the script

**Comment by hibatallahAouadni** [comment] 2021-07-28 09:19
Hello @kpodemski 

Thanks for your report!
Yes, I reproduce the issue with develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/127296615-524054cb-bd28-44cc-ad93-881ed43c4564.png)

I didn't manage to reproduce it with 178x, so it's a **regression**! I’ll add this to the debug backlog so that it’s fixed.

Thanks for your PR :rocket: 

Thank you

**Comment by khouloudbelguith** [comment] 2021-07-28 16:01
Hi @kpodemski, @hibatallahAouadni,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #25340
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-07-28 16:01
Duplicate of #25340

**Closed as completed by khouloudbelguith** 2021-07-28 16:01 UTC
Labels: Bug, develop, Major, BO, Duplicate, Modules

**Comment by kpodemski** [comment] 2021-07-28 16:06
This one wasn't related to none existing service, these issues are a bit different, but it's ok 👍 we can treat as one
