### ISSUE TITLE
The left menu in BO disappeared after upgrade to 1.7.7.0

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#22251] opened 2020-12-04 15:47 UTC
#### Describe the bug

Ufter upgrading PS to 1.7.7.0 in the BO NO left menu
I cleaned cache in the FAR manager but nothing changed ((
![image](https://user-images.githubusercontent.com/50954519/101183612-6554a480-3658-11eb-8145-6f8349ccc0aa.png)

* PrestaShop version: 1.7.7.0
* PHP version: 7.1.33

**Comment by florine2623** [comment] 2020-12-04 15:49
Hi @photinia73 ,
Seems like your issue is similar to #22250 
Let's discuss on the other issue to avoid duplicate.
Thanks.

**Comment by florine2623** [comment] 2020-12-04 15:49
Duplicate of #22250

**Closed as completed by florine2623** 2020-12-04 15:49 UTC
Labels: Duplicate

**Comment by photinia73** [comment] 2020-12-04 15:54
I am sorry, but where is dessision?

**Comment by NeOMakinG** [comment] 2020-12-04 15:59
> I am sorry, but where is dessision?

No decision yet, see #22250 responses, and talk on it if you wan't :) 

We close duplicated issues in order to organize that's it!

**Comment by photinia73** [comment] 2020-12-04 16:11
Ок, I uderstood.... But I`m panick a little .... Will follow the #22250
