### ISSUE TITLE
delete product attribute: DELETE not allowed for url

### ISSUE THREAD

**Issue by ebonit** [PrestaShop/PrestaShop#25952] opened 2021-09-21 14:15 UTC
#### Describe the bug

When I have added attributes to a product and I want to delete 1 or more of them then the server response is
DELETE not allowed for url

#### Expected behavior

I expect the attribute to be removed from the product

#### Steps to Reproduce

1. go to backoffice->catalogue->Attributes&Features.
2. add a new attribute
3. add some values
4. go to catalogue->products
5. edit a product
6. set to Product with combinations
7. click the combinations tab
8. add 1 or more attribute values to the product by clicking them in the multi select and then the generate button
9. when the attributes show then try to delete 1 or more
10. nothing happens
11. the resonse from ajax request is: 'Method Not Allowed The requested method DELETE is not allowed for this URL.'

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.28

**Comment by florine2623** [comment] 2021-09-21 14:39
Hello @ebonit ,

I can't reproduce your issue as you can see per my screen record : 
https://watch.screencastify.com/v/RNyKbLTKQzj5YyttboNh

You need to contact your hosting provider so the DELETE method can be activated.

As this is not an issue on the software, I will close it.
Thanks!

**Closed as completed by florine2623** 2021-09-21 14:39 UTC
Labels: No change required
