### ISSUE TITLE
[develop] BO - Carrier wizard is broken

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#32262] opened 2023-04-21 13:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to Add/Edit a carrier, the carrier wizard is broken.
<img width="445" alt="Screenshot 2023-04-21 at 14 58 43" src="https://user-images.githubusercontent.com/16019289/233642003-34764719-43db-4d87-bbc1-32dfe0202351.png">

It is a regression as it used to work before.

With PHP 7.3. I just have a warning :
<img width="1440" alt="Screenshot 2023-04-25 at 11 54 11" src="https://user-images.githubusercontent.com/16019289/234241757-6d86384e-e3c5-4b22-beff-1527948c681b.png">

### Expected behavior

I should be able to see the actual carrier wizard.

### Steps to reproduce

1. Go to BO > Shipping > Carriers
2. Click Edit or Add a new carrier button
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by djoelleuch** [comment] 2023-04-26 15:40
Hello @florine2623 ,
It's a regression ,  nice catch :clap:  

[Untitled_ Apr 26, 2023 5_37 PM.webm](https://user-images.githubusercontent.com/115152460/234628432-8c43b6a9-0ec7-44dc-a289-9e399660ba74.webm)

Thank you

**Comment by boherm** [comment] 2023-05-15 12:18
Hi @florine2623, I can't reproduce on my side with current develop and with PHP 8.1.
Can you retest on your side and tell me if you reproduce again your issue? Probably this issue may be fixed few days ago.

**Comment by M0rgan01** [comment] 2023-05-15 12:56
@florine2623  @boherm  I also tested on PHP versions 8.1 / 7.4, I do not reproduce (for adding and editing)

**Comment by florine2623** [comment] 2023-05-16 09:21
Hello all,

I tried again on a fresh install on `develop` branch, I tested with PHP `7.3`, `7.4` and `8.1`. 
With `7.3` and `7.4`, I have this issue : 
<img width="1189" alt="Screenshot 2023-05-16 at 11 17 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9d14bdf5-a077-4700-abf4-b12f25b0f5e9">

With `8.1, it works as expected.

What should be done with this issue ? keep it or close it ?

**Comment by boherm** [comment] 2023-05-16 09:31
Hello @florine2623!

We have drop all old PHP version (< 8.1) for PrestaShop 9 in develop branch. 

PR: https://github.com/PrestaShop/PrestaShop/pull/32514
Discussion: https://github.com/PrestaShop/PrestaShop/discussions/32358

So I think we can close it :)

**Closed as completed** 2023-05-22 14:18 UTC
Labels: Bug, develop, Major, BO, Carriers, Regression, Verified
