### ISSUE TITLE
Product_suppliers aren't filled throw webservice

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#20731] opened 2020-08-26 13:15 UTC
#### Describe the bug
Add or update a product throw webservice with id_supplier and supplier_reference filled.
Only product table is filled and product_supplier table isn't filled. This is a problem because database schema isn't repected like a product's update into backoffice.

#### Expected behavior
product_supplier table must be filled too.

#### Additional information
PrestaShop version: 1.7.7
I already did the patch, I'll commit it asap.

**Comment by matks** [comment] 2020-08-26 13:18
Hi ! this might be related/duplicate of https://github.com/PrestaShop/PrestaShop/pull/20198 and https://github.com/PrestaShop/PrestaShop/issues/20094

**Comment by Max84** [comment] 2020-08-26 13:25
Hi @matks 
I'm not sure. These issues tell the problem is product table isn't updated. Here, product table is updated and the product supplier isn't updated.

I suggest to update Product addWs() and updateWs() in order to use addSupplierReference() in order to update too product supplier table.

I see it only with webservice, I don't get this issue with BO.

What do you think about?

**Comment by marionf** [comment] 2020-08-26 16:02
As it concerns the 1.7.7, we need to ensure if it's not a regression compared to 1.7.6
@khouloudbelguith @sarahdib

**Comment by khouloudbelguith** [comment] 2020-08-27 07:57
Hi @marionf,

I manage to reproduce the issue with PS1.7.6.7.
I tried with this script
```
<prestashop>
<product>
  <id/>
  <id_manufacturer>2</id_manufacturer>
  <id_supplier xlink:href="http://prestashop.local/1767/api/suppliers/1">1</id_supplier>
  <supplier_reference>testing</supplier_reference>
  <state>1</state>
  <id_category_default>2</id_category_default>
  <active>1</active>
  <advanced_stock_management>1</advanced_stock_management>
  <associations>
    <categories>
      <category><id>2</id></category>
    </categories>
  </associations>
  <reference>boom</reference>
  <name>
  <language id="1">product_success_add</language></name>
  <price>100</price>
  <id_shop_default>1</id_shop_default>
  <low_stock_alert>0</low_stock_alert>
  <link_rewrite>abc</link_rewrite>
  <show_price>1</show_price>
  <minimal_quantity>1</minimal_quantity>
  <available_for_order>1</available_for_order>
</product>
</prestashop>
```

In the Table `ps_product` => ok
![image](https://user-images.githubusercontent.com/16067358/91413224-17efbc80-e84b-11ea-9304-fca622f41d25.png)
The table `ps_product_supplier` is empty
![image](https://user-images.githubusercontent.com/16067358/91413300-33f35e00-e84b-11ea-8a1b-e9fa950eca55.png)

In the BO => Catalog => Product details page, the supplier is not setected
![image](https://user-images.githubusercontent.com/16067358/91413642-b714b400-e84b-11ea-817d-c0ca200396f8.png)

Thanks!

**Comment by marionf** [comment] 2020-08-27 08:21
Thank you @khouloudbelguith, could you apply the severity label ?

**Comment by Max84** [comment] 2020-08-28 06:18
@PierreRambaud made a feedback onto my PR.
Maybe the issue isn't "product_supplier aren't filled", but the issue is "id_supplier and supplier_reference should be removed from product's object".
Maybe Pierre can give his point of view.
If Prestashop's team goal is to fully manage suppliers, maybe id_supplier and supplier reference into product's object are depreceated.
If not, i think my PR is OK.
If yes, my PR is KO and instead we should remove these fields from webservice product method.

I think someone should help with some spirit or guidelines about it !

**Comment by khouloudbelguith** [comment] 2020-09-01 11:04
Hi @Max84,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16086
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-01 11:04
Duplicate of #16086

**Closed as completed by khouloudbelguith** 2020-09-01 11:04 UTC
Labels: Bug, Minor, BO, WS, Duplicate, Webservice, Suppliers, PR available, 1.7.7.x, 1.7.6.7
