### ISSUE TITLE
500 internal error message after modul installation 1.7.4.2

### ISSUE THREAD

**Issue by DaveDavi** [PrestaShop/PrestaShop#10119] opened 2018-08-24 11:01 UTC
Hello, I need help...Actually it doesnt matter which module I try to install, I get this error message and cant go on....I use Prestashop 1.7.4.2...the module version is also for 1.7.4...i logged out...removed modules...tried with different modules...upload over downloaded file and also directly with login information....same problem.......anyone can help?****
![error occured](https://user-images.githubusercontent.com/42671574/44581351-a4b79980-a79d-11e8-89c1-047700ec6d67.JPG)

**Comment by khouloudbelguith** [comment] 2018-08-24 11:19
Hi @DaveDavi,

I did not manage to reproduce the issue with the last version 1.7.4.2.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Tomskor** [comment] 2018-08-24 11:22
Have this same problem, cant acces to back office, with our mirror when I first time trying to upload 4.1 autoupgrade module shows up information "something wrong error 500" and on the second time intalation was sucesfull and mirror is working but our main store DOESNT - cant acces to back office.

**Comment by khouloudbelguith** [comment] 2018-08-24 12:16
Hi @Tomskor 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards,
Khouloud

**Comment by Quetzacoalt91** [comment] 2018-08-24 14:21
@DaveDavi, please follow the link provided by @khouloudbelguith to enable the debug mode. Without it, we don't have the error details and we cannot provide any help.

@Tomskor your case is followed on #10118

**Comment by khouloudbelguith** [comment] 2018-09-24 11:11
Hi @DaveDavi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-24 11:11 UTC
Labels: Bug, Modules, No change required, 1.7.4.2
