### ISSUE TITLE
Make it possible to edit one-and-one field in Product "all-shops" context

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#16740] opened 2019-12-09 07:57 UTC
On 1.6 `multistore > back-office   > all shops> Product edit`, one would have to mark a checkbox for each field one would like to edit.
When for example editing the `Name` field, and clicking  `Save`, only the name field would be updated across all shops.

Nowadays on `1.7.6.1`, doing the same product edit, you have no such checkboxes, and therefore update **all fields** when you only wanted to update for example `name`.

I know I can edit the product for one and one shop, but there is many cases where you would like to make just small adjustments for each shop, but mainly edit the products in `all shops` context. This is no longer possible in `1.7.6.1`.

**Comment by khouloudbelguith** [comment] 2019-12-09 10:58
Hi @onklmaps,

We are aware of this issue, it should be specified by our product Team.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9833#issuecomment-415159319
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-09 10:58
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9833

**Closed as completed by khouloudbelguith** 2019-12-09 10:58 UTC
Labels: Duplicate
