### ISSUE TITLE
Adding customized product to the cart produce PHP warnings

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#37576] opened 2024-12-04 22:58 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After adding a customized product to the cart, there is a warning displayed in the developer mode:

> Warning: Undefined array key "isRewritable" in /Users/kpodemski/code/prestashop9/src/Adapter/Presenter/AbstractLazyArray.php on line 401

### Expected behavior

No warning after adding customized product to the shopping cart.

### Steps to reproduce

Add a customized product to the shopping cart and visit the home page.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2024-12-05 08:20
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/36907

**Closed as not planned** 2024-12-05 08:21 UTC
Labels: Bug, Duplicate
