### ISSUE TITLE
Scroll down doesn't work on the main product image in the product page

### ISSUE THREAD

**Issue by mikirimiki** [PrestaShop/PrestaShop#26597] opened 2021-11-14 12:36 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On a mobile phone (tried with two different Samsung devices), when you scroll down with your finger on the product image in a product sheet to go down to see the following information, the scroll doesn't work. To reach the other information you have to touch any other parts on the screen and scroll.
I tried on my website and on the demo.prestashop.com/#/en/front. Same problem.
![Screenshot from 2021-11-14 13-29-16](https://user-images.githubusercontent.com/53991635/141681248-594d5c90-96dd-4fce-a2a5-f2b6fa1971e2.png)

### Expected behavior

I expect you can scroll down touching the image like was in the precedent release, where you could scroll in any part of the screen on the product sheet

### Steps to reproduce

1. use a mobile phone (I used Samsung) and browse with Firefox, Chrome, or Opera.

2. go to this page: https://demo.prestashop.com/#/en/front

3. choose any product

4. try to scroll on the main image

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2021-11-15 10:02
Hello @mikirimiki ,

I was able to reproduce the issue with PrestaShop version 1.7.8.0, so I can confirm that this behavior is indeed a bug.
It was working fine on 1.7.7.7, so it is a regression.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by stifadoo** [comment] 2021-11-15 10:57
After commenting `class="js-qv-product-cover img-fluid"` in the file product-cover-thumbnails.tpl in the ..themes/classic/templates/catalog/_partials/ scrolling starts working. But this is not the solution.

`<div class="images-container js-images-container">
  {block name='product_cover'}
    <div class="product-cover">
      {if $product.default_image}
        <img
        {*  class="js-qv-product-cover img-fluid"    *}
          src="{$product.default_image.bySize.medium_default.url}"
          {if !empty($product.default_image.legend)}
            alt="{$product.default_image.legend}"
            title="{$product.default_image.legend}"
          {else}
            alt="{$product.name}"
          {/if}
          loading="lazy"
          width="{$product.default_image.bySize.medium_default.width}"
          height="{$product.default_image.bySize.medium_default.height}"
        >
        <div class="layer hidden-sm-down" data-toggle="modal" data-target="#product-modal">
          <i class="material-icons zoom-in">search</i>
        </div>
      {else}
        <img
          class="img-fluid"
          src="{$urls.no_picture_image.bySize.medium_default.url}"
          loading="lazy"
          width="{$urls.no_picture_image.bySize.medium_default.width}"
          height="{$urls.no_picture_image.bySize.medium_default.height}"
        >
      {/if}
    </div>
  {/block}`

**Comment by Progi1984** [comment] 2021-12-28 13:08
Fixed by @NeOMakinG  in #26703 & Tested by @HanaRebaiQA

**Closed as completed by Progi1984** 2021-12-28 13:08 UTC
Labels: Bug, Trivial, FO, Regression, Fixed, Front-end, PR available, 1.7.8.0
