### ISSUE TITLE
Backoffice styling and usability on smaller devices

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20316] opened 2020-07-24 10:16 UTC
It would be very difficult task to do anything from Prestashop Backoffice from my phone.

LEFT IMAGE
**Sticky header that uses one third of the page** - don't make it sticky
**Uneeded help and recommended module buttons that take up insane amount of space** - you can move it to left menu, the same as logout button.

CENTER IMAGE
**Unneeded info is taking half of the page** - It can be under collapse and displayed only if needed.
**Create new order button** - It can simply be a PLUS button in a right of "Orders".
**Duplicated orders text**

RIGHT IMAGE
**Main menu is under the sticky header**
**Main menu items are extremely large compared to other texts in BO.**

![screens](https://user-images.githubusercontent.com/6097524/88381113-117ea880-cda6-11ea-9b9f-0870ae6c2604.png)

#### Additional information

* PrestaShop version: 1.7.7 beta
* PHP version: 7.2
ping @prestascott

**Comment by florine2623** [comment] 2020-07-24 10:25
Hi @Hlavtox ,
Thanks for your suggestion, I will ping our product team !
Please stay tuned.

**Comment by florine2623** [comment] 2020-07-24 10:26
Hi @PrestaShop/prestashop-product-team ,

@Hlavtox has some improvement to suggest regarding the BO UX in smaller device like a phone
What do you think about that ?

Thanks!

**Comment by LouiseBonnard** [comment] 2020-07-24 10:42
Hi @Hlavtox and @florine2623, thanks, there are definitely responsive optimizations to do! I let the designers' team have a look at it and validate/complete your recommendations. :-)

**Comment by prestascott** [comment] 2020-08-17 12:49
Hi everyone,

Thanks @Hlavtox for your report.
Your point of view is really interesting! 

LEFT IMAGE
We have discussed about this sticky menu and its content internally. In fact, 'Help' and 'Recommended module' buttons aren't really required on mobile version so it can be removed. 

CENTER IMAGE
I agree with you, we can put the 'Add new product' where you said.

RIGHT IMAGE
We're also planning to change text size according to our new typescale and ratio rules we've established with the Design Team.

**Comment by Hlavtox** [comment] 2020-08-17 12:55
@prestascott That were just a few points I stumbled upon mate. 👍 

Do you have some EPIC for this? I think it would be good to go through all BO and just make a list of optimizations/tweaks.

I also noticed there are some px units in CSS and it's making some weird things, when you have your displays scaled.

**Comment by NeOMakinG** [comment] 2021-02-09 16:48
Closing this one in favor of https://github.com/PrestaShop/PrestaShop/issues/22358

Thanks for the feedback @Hlavtox

**Closed as completed by NeOMakinG** 2021-02-09 16:48 UTC
Labels: Improvement, UX ✔️, BO, Duplicate, Front-end, 1.7.7.0

**Comment by hibatallahAouadni** [comment] 2021-03-24 11:37
Duplicate of #22358
