### ISSUE TITLE
The ean code is not shown in the product pages if it is without combinations

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#20187] opened 2020-07-15 17:01 UTC
Hi
I've seen that the ean code appears onlly if set in the product combinations
instead if the product is without them, so just a simple product, the ean code set in the "option" tab will not be shown in the front-office like in the other case

can you fix it?

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/87573468-3d769b80-c6cd-11ea-8ecb-b1fa1b44490f.png)
![2](https://user-images.githubusercontent.com/653230/87573470-3f405f00-c6cd-11ea-9192-e607f8036b9d.png)
![3](https://user-images.githubusercontent.com/653230/87573474-3fd8f580-c6cd-11ea-899e-250223e5f1c4.png)
![4](https://user-images.githubusercontent.com/653230/87573475-410a2280-c6cd-11ea-9082-e97d641d3a86.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by Hlavtox** [comment] 2020-07-16 06:24
@maofree 


```
{if isset($product.specific_references.ean13) && $product.specific_references.ean13 neq ''}
    <div class="product-ean13">
        <label class="label">{l s='EAN' d='Shop.Theme.Catalog'}</label>
        <span>{$product.specific_references.ean13}</span>
    </div>
{elseif isset($product.ean13) && $product.ean13 neq ''}
    <div class="product-ean13">
        <label class="label">{l s='EAN' d='Shop.Theme.Catalog'}</label>
        <span>{$product.ean13}</span>
    </div>
{/if}
```

**Comment by florine2623** [comment] 2020-07-16 08:05
Hi @maofree ,
Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15783
So I close your issue.

**Comment by florine2623** [comment] 2020-07-16 08:05
Duplicate of #15783

**Closed as completed** 2020-07-16 12:52 UTC
Labels: Duplicate
