### ISSUE TITLE
Bug in the page Import 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11753] opened 2018-12-12 16:48 UTC
**Describe the bug**
In the BO => Advanced Parameters => Import page, an exception is displayed

**To Reproduce**
1. Go to the BO => Advanced Parameters => Import page

**Screenshots**
![capture d ecran de 2018-12-12 17-36-03](https://user-images.githubusercontent.com/16067358/49884794-f90e8400-fe35-11e8-87a4-a44ca5b2064e.png)

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by marionf** [comment] 2018-12-12 17:23
I will try to reproduce when 1.7.5.x will be merged into develop

**Comment by khouloudbelguith** [comment] 2018-12-13 09:08
Hi @marionf,

It is not about this PR #11689?
Thanks!

**Comment by marionf** [comment] 2018-12-13 09:12
Right, I didn't see this one !

**Comment by matks** [comment] 2018-12-18 09:30
@rokaszygmantas Started on a fix, here's the beginning of my work: https://github.com/matks/PrestaShop/commit/19d6fe19dfc7a73fb9d3d8c2ac87b21aba0de1bf

Looks like merges between branches 1.7.5.x and develop have messed up the Import page. Some files which were updated / renamed were left both in the code (the old version and the new version).

**Closed as completed** 2019-01-16 14:12 UTC
Labels: Bug, develop, Major, Import / Export, Regression, Fixed
