### ISSUE TITLE
Unable to link with my PrestaShop store page from the internet.

### ISSUE THREAD

**Issue by brucer44** [PrestaShop/PrestaShop#11870] opened 2018-12-20 00:50 UTC
**Describe the bug**
Unable to link with my brucereaves.com PrestaShop store page from the internet.

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-12-20 08:00
Hi @brucer44,

Thanks for your report.
Could you please provide us with a clear description of what is your issue?
We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by brucer44** [comment] 2018-12-20 18:30
Thanks for your reply. The problem appears to be resolved at this time.
--------------------------------------------
On Thu, 12/20/18, khouloudbelguith <notifications@github.com> wrote:

 Subject: Re: [PrestaShop/PrestaShop] Unable to link with my PrestaShop store page from the internet. (#11870)
 To: "PrestaShop/PrestaShop" <PrestaShop@noreply.github.com>
 Cc: "brucer44" <breaves44@sbcglobal.net>, "Mention" <mention@noreply.github.com>
 Date: Thursday, December 20, 2018, 3:01 AM
 
 Hi @brucer44,
 Thanks for your report.
 
 Could you please provide us with a clear description of what
 is your issue?
 
 We need more details to understand how we can reproduce your
 issue:
 
 server setup and configuration
 PrestaShop version (source)
 screenshots
 
 Don't you know how to get this information? Please
 read the following article:
 
 http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
 Thanks!
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by khouloudbelguith** [comment] 2018-12-21 10:47
Hi @brucer44,

Thanks for your report.
Since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-21 10:47 UTC
Labels: No change required
