### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Yassine3708** [PrestaShop/PrestaShop#36333] opened 2024-06-08 19:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello 
I have an issue in last step on my checkout when I place order 

link : https://datatechboutique.com
I get an error page as you can see in attachment 
 - version Prestashop  ///  8.1.2
 - version PHP //// PHP 8.2 
 -  steps to have this error 
1- select the item to add to cart 
2- add to cart 
3- proceed to checkout 
4- click  proceed to checkout 
5- fill full of personal informations
6- click continue 
7- click continue 
8- select shipping method  ( cod with tawssil here ) 
9- select : Pay by Cash on Delivery
10 - select : I agree to the [terms of service](https://datatechboutique.com/en/content/3-conditions-utilisation) and will adhere to them unconditionally.

11- click place order 

I get this error page like the attach file 
HTTP ERROR 500

<img width="960" alt="Capture d'écran 2024-06-07 130941" src="https://github.com/PrestaShop/PrestaShop/assets/172133197/03e5053e-6aa2-4fa5-9607-0df099b73b38">

### Steps to reproduce

1- select the item to add to cart 
2- add to cart 
3- proceed to checkout 
4- click  proceed to checkout 
5- fill full of personal informations
6- click continue 
7- click continue 
8- select shipping method  ( cod with tawssil here ) 
9- select : Pay by Cash on Delivery
10 - select : I agree to the [terms of service](https://datatechboutique.com/en/content/3-conditions-utilisation) and will adhere to them unconditionally.

11- click place order 

I get this error page like the attach file 
HTTP ERROR 500

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.2

### Your company or customer's name goes here (if applicable).

DATA SOFTWARE

**Comment by florine2623** [comment] 2024-06-10 07:46
Hello @Yassine3708 ,

I can't reproduce your issue using cash on delivery module on PS 8.1.2.

https://github.com/PrestaShop/PrestaShop/assets/16019289/6c8025aa-bd43-429a-a5ff-415cc2070326

Please use PHP 8.1 instead of 8.2. Here you will find more information about the system requirements : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

I'm closing the issue as it cannot be reproduced.

**Closed as completed by florine2623** 2024-06-10 07:46 UTC
Labels: Bug

**Comment by Yassine3708** [comment] 2024-06-12 11:22
Hello

I changed the HP version to 8.1 , unfortunately it still the same problem

 DATA SOFTWARE  Team

Cordialement

*DATA SOFTWARE *19, Rue 20 Aout , Hay El Houda

Berrechid, 26100 Maroc

Tel: +212 5 22 51 69 93

Merci de penser à la protection de l’environnement avant d’imprimer cet
émail.


Le lun. 10 juin 2024 à 08:47, florine2623 ***@***.***> a
écrit :
