### ISSUE TITLE
combination generator for 3 attributes having values count 11,28,12 giving time out error and website freezes 

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#19613] opened 2020-06-06 11:16 UTC
**Describe the bug**

When we have 3 attributes having values count 11,28,12 then the Prestashop combination generator freezes
also it's giving the memory limit error. I have already increased the PHP memory limit to 5gb

**Prestashop version**
1.7.6.5

**Expected behavior**
for the particular product, it must list all combinations without any error.

**Steps to Reproduce**

1. Created 3 attributes
2. add those attributes values. the total value for each attribute will be 11,28, 12. To understand please check screenshot
[http://i.imgur.com/b7ZWMFQ.png](http://i.imgur.com/b7ZWMFQ.png)
3.Create any combinational product 
4. Generate all possible combinations for that particular product.
5) After generating refresh the page  and you see the below screenshot

**Error is shown with debug mode**
[http://i.imgur.com/Ds3IZt5.png](http://i.imgur.com/Ds3IZt5.png)

**Comment by PululuK** [comment] 2020-06-06 12:44
This will interest you https://github.com/PrestaShop/PrestaShop/issues/19123

**Comment by pks891618** [comment] 2020-06-06 13:19
@PululuK  sorry but i can't see the solution for this

**Comment by NeOMakinG** [comment] 2020-06-08 12:51
Hello @pks891618,

As @PululuK said, it's already being discussed there https://github.com/PrestaShop/PrestaShop/issues/19123 for the next version but I tested it and I managed to reproduce it :

![image](https://user-images.githubusercontent.com/14963751/84032320-6f426700-a997-11ea-9890-61721ee762d9.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by NeOMakinG** [comment] 2020-06-08 15:11
We discussed with the team about it, and as it will be completely reworked on 1.7.8, this issue is considered as a duplicate of #19123, thanks for your time :)

**Closed as completed by NeOMakinG** 2020-06-08 15:11 UTC
Labels: Bug, Major, BO, Duplicate, Combinations, 1.7.6.5

**Comment by marionf** [comment] 2020-06-09 08:03
Duplicate of #19123
