### ISSUE TITLE
[1.7.7 beta 1] Updating order state throw webservice is KO

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#20029] opened 2020-07-02 12:30 UTC
#### Describe the bug

Some error append when you try to update order's state throw webservice.

#### Expected behavior

The order state must be updated. It doesn't updated now.

#### Steps to Reproduce

1. Just run attached file
2. See error: on backend, the order state isn't updated. PHP error log gives this:

[Thu Jul 02 14:27:41.819053 2020] [php7:notice] [pid 16908:tid 1976] [client ::1:12273] [PHP Notice #8] Trying to get property 'precision' of non-object (C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\classes\\Context.php, line 465)
[Thu Jul 02 14:27:41.819053 2020] [php7:error] [pid 16908:tid 1976] [client ::1:12273] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\ComputingPrecision::getPrecision() must be of the type integer, null given, called in C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\classes\\Context.php on line 465 and defined in C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\src\\Core\\Localization\\CLDR\\ComputingPrecision.php:41\nStack trace:\n#0 C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\classes\\Context.php(465): PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\ComputingPrecision->getPrecision(NULL)\n#1 C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\classes\\order\\Order.php(1441): ContextCore->getComputingPrecision()\n#2 C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\classes\\order\\Order.php(1329): OrderCore->setInvoiceDetails(Object(OrderInvoice))\n#3 C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\classes\\order\\OrderHistory.php(371): OrderCore->setInvoice(false)\n#4 C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\classes\\order\\OrderHistory.php(613): OrderHistoryCore->changeIdOrderState('2', '5')\n#5 C:\\ in C:\\xampp_php7.2\\htdocs\\prestashop_1.7.7.0b1\\src\\Core\\Localization\\CLDR\\ComputingPrecision.php on line 41

#### Additional information

* PrestaShop version: 1.7.7 beta 1
* PHP version: 7.2

**Comment by Max84** [comment] 2020-07-02 12:31
The php test file:
[add_order_state_ps15.zip](https://github.com/PrestaShop/PrestaShop/files/4864210/add_order_state_ps15.zip)

**Comment by florine2623** [comment] 2020-07-02 15:02
Hi @Max84 ,
What do you mean by "just run the attached file" ?
Thanks!

**Comment by Max84** [comment] 2020-07-02 15:27
Hi @florine2623 

This php script does an order's history update throw webservice. It reproduces a webservice call and it reproduces the bug.
You can run it with php cli or onto a webserver.

Best regards,

**Comment by florine2623** [comment] 2020-07-09 14:30
I ran that command :
`php -f add_order_state_ps15.php`
And I'm having an error.
Could you possibly do you and screen record it ?

**Comment by khouloudbelguith** [comment] 2020-07-29 09:46
Hi @Max84,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-07-29 09:46 UTC
Labels: WS, Duplicate, Webservice, 1.7.7.0

**Comment by khouloudbelguith** [comment] 2020-07-29 09:48
Hi @Max84,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/18859 to fix the issue.
Your ticket is a duplicate of #18789
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-07-29 09:48
Duplicate of #18789
