### ISSUE TITLE
importing data CSV products more from 100 items

### ISSUE THREAD

**Issue by Nelhagui** [PrestaShop/PrestaShop#16252] opened 2019-11-02 19:31 UTC
**Describe the bug**
when uploading products from files with CSV extension (more than 7000 products) returns an error (attached capture)

**Screenshots**
screenshot1: [https://www.distribuidora2g.com.ar/captura.png](url)
https://www.distribuidora2g.com.ar/captura.png
screenshot2 = [https://www.distribuidora2g.com.ar/captura2.png](url)
https://www.distribuidora2g.com.ar/captura2.png
screenshot3(php config) [https://www.distribuidora2g.com.ar/captura3.png](url)
https://www.distribuidora2g.com.ar/captura3.png

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

![Uploading captura.png…]()

**Comment by khouloudbelguith** [comment] 2019-11-04 10:25
Hi @Nelhagui,

I did not manage to reproduce the issue with ps1.7.6.1.
I tried with 1680 products & it is OK.
https://drive.google.com/file/d/1OMi80CJWWFxtlMH_tB1dqwxkFp3c7-Hu/view
Here's my configuration
![image](https://user-images.githubusercontent.com/16067358/68114197-c0681500-fef5-11e9-8ad2-51045ee6cd3a.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-04 07:59
Hi @Nelhagui,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-04 07:59 UTC
Labels: Bug, BO, Import / Export, No change required, 1.7.6.1
