### ISSUE TITLE
ActionGetProductPropertiesAfter missing on 1.7.7.4

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#26692] opened 2021-11-19 22:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It's not really a bug, but I waste time to find it.

I was trying to use the hook ActionGetProductPropertiesAfter as describe in the documentation : 
https://devdocs.prestashop.com/1.7/faq/product/
https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/

This hook is simply missing on 1.7.7.4 and there is no information about the version in the devdocs.
Why ?

### Steps to reproduce

Install a 1.7.7.4, try to use hook ActionGetProductPropertiesAfter

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2021-11-22 08:48
Hello @rflorent ,

In 1.7.7.4, /classes/Product.php, the hook is present ActionGetProductPropertiesAfter :
<img width="368" alt="Screenshot 2021-11-22 at 09 45 26" src="https://user-images.githubusercontent.com/16019289/142830201-2b1a5df1-ba62-4e93-9749-b0939703f6f9.png">

Are you trying to create an override ? If yes, you could share the piece of code so we can try on our end.
Thanks!

**Comment by rflorent** [comment] 2021-11-22 13:30
Hello @florine2623, 

Do you try to use these hook on a custom module ?

I have already seen that piece of code, but there no hook 'actionGetProductPropertiersAfter' in the database, so nothing is called at all. I've added the hook in the hook table and it work's now. Seems not normal.

Thanks

**Comment by hibatallahAouadni** [comment] 2021-11-22 14:16
Hello @rflorent 

I didn't manage to reproduce the issue with PS1774 and PS1781, see the attached screenr record below:

https://watch.screencastify.com/v/itwKl2BohUaIh9celAFB

Please check and feedback.
Thanks!

**Comment by PrestaEdit** [comment] 2021-11-25 08:52
Hi,

If the hook is called inside the PHP code, it's all good, you can use it.
The needs to have it inside the database is not mandatory, it's only allow you to transplant the module within the Position tab.

If your module is register to this hook on it's installation, it will work.

**Comment by rflorent** [comment] 2021-11-25 09:24
Hi @PrestaEdit 
The hook was added to a existing custom module, after install.
I was not able to transplant the module with the Position tab.
The hook was'nt available.

**Comment by PrestaEdit** [comment] 2021-11-25 09:43
It's that, the hook missing inside the database and so you can't transplant your module but the hook is there and usable, if you register your module onto it by the code, so.

I'm not sure that we need to add this kind of hook inside the available hook to transplant on it, but it could be the case.

**Comment by hibatallahAouadni** [comment] 2021-11-25 17:17
Hello @PrestaEdit & @rflorent 

Are you sure that you used this hook in Positions page in older versions?
Cause I tried to call it in PS1.7.6.7, I get nothing:

![image](https://user-images.githubusercontent.com/23308427/143481623-462ff9af-9032-4aa9-a5dc-baa6d4ee2b4c.png)

Please check and feedback.
Thanks!

**Comment by rflorent** [comment] 2021-11-25 18:07
Hello @hibatallahAouadni ,

That's the case, nothing show up on position tab. So you can't register that way.

I didn't say I used it on older versions. That's the first time I try to use this hook. As I find it in the docs, I thought I could use it like other hooks ! nothing on the invisibility in the position tab and db, would be good to describe how to use it...

**Comment by hibatallahAouadni** [comment] 2021-12-02 15:55
Hello @rflorent 

You need to use this hook in module (for exemple: [ps_qualityassurance](https://github.com/PrestaShop/ps_qualityassurance)), then make search in **BO>IMPROVE>Design>Position** page and click on **`Display non-positionable hooks`** option, the hook will be displayed :wink: 

https://watch.screencastify.com/v/QoCD0DaF6H4jy8qSOr2M

Closing this issue as it's not a bug.
Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-02 15:55 UTC
Labels: Bug, CO, Hook, 1.7.7.4, Invalid

**Comment by rflorent** [comment] 2021-12-02 16:42
Hello @hibatallahAouadni 

If it's not a bug, why I can't transplant my module on this hook by the ui ?
You see it on the positions list because you have already hooked your module on and you use code to register the hook.
If you add some snippet code like this to an existing module, for update, it will not work.

`$this->registerHook('actionGetProductPropertiesAfter')`
