### ISSUE TITLE
Getting error while registering a new customer on prestashop

### ISSUE THREAD

**Issue by renochost** [PrestaShop/PrestaShop#14129] opened 2019-06-10 08:06 UTC
Getting error while registering a new customer on prestashop. The error is mentioned below

#6 /home/renocojf/public_html/shopping/classes/controller/Controller.php(281): AuthControllerCore in /home/renocojf/public_html/shopping/classes/Mail.php on line 893

Please tell us how to resolve this, getting this error each and every time while registering or making order.

Waiting for your response.

**Comment by khouloudbelguith** [comment] 2019-06-10 08:36
Hi @renochost,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-10 07:37
Hi @renochost,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-10 07:37 UTC
Labels: Bug, FO, Customer, No change required
