### ISSUE TITLE
prestashop 1.7.5.2 cannot amend product quantities

### ISSUE THREAD

**Issue by leecharles25** [PrestaShop/PrestaShop#14862] opened 2019-07-25 16:48 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-07-26 06:59
Duplicate of #14861

**Closed as completed by khouloudbelguith** 2019-07-26 06:59 UTC
Labels: Duplicate
