### ISSUE TITLE
Stock management - Multistore

### ISSUE THREAD

**Issue by unreviewed** [PrestaShop/PrestaShop#12871] opened 2019-03-11 16:08 UTC
In Multistore Set "Share available quantities to sell" =>YES

Go to Catalog > Stocks
In All Shops context you receive notification,
"You can't manage your stock in this shop context: select a shop instead of a group of shops."

All stores are now set to share inventory, the ONLY way to manage inventory should be In the context of "All Shops" because it no longer make sense to edit inventory by store context, inventory is now stored in database without shop assignment.

But it gets worse,

In combination bulk edits it will not allow to add inventory in “All Shops” context, again the only way to add inventory is to choose a store. If you try to add inventory with combination bulk edits it will throw error.

This seems related to
[BOOM-5372] Can't create combinations on the second shop if multistore #9664
https://github.com/PrestaShop/PrestaShop/issues/9664#issuecomment-471480370

**Additionnal information**
PrestaShop version: 1.5.7.1

**Comment by unreviewed** [comment] 2019-03-11 16:42
Additional info.

As mentioned trying to add or update stock quantity with All Shops” context ends with error.

Switching to single shop context allows stock addition without error flag, however very nasty error is entered into Table: ps_stock_available

Here is image showing clean/empty table before using combination bulk edit in single store context:
![Capture1](https://user-images.githubusercontent.com/2993190/54140940-73ce4780-4403-11e9-9db2-f04724ef503f.JPG)

**Comment by unreviewed** [comment] 2019-03-11 16:42
Here is image about to add 100 to sample product "1",
![Capture2](https://user-images.githubusercontent.com/2993190/54140977-88124480-4403-11e9-9b8d-168476598efd.JPG)

**Comment by unreviewed** [comment] 2019-03-11 16:43
Update is reported as successful, however see final image of Table: ps_stock_available

1. All stock is assigned to id_shop_qroup > 1
All stock is set to be shared so it should not be assigned to a shop group.

2. Nasty bug, see field id_stock_available > 308
No value assigned to id_product_attribute
COMPLETELY WRONG quantity "800" where did that come from?
![Capture3](https://user-images.githubusercontent.com/2993190/54141021-9e200500-4403-11e9-8efb-f62509a073ef.JPG)

**Comment by unreviewed** [comment] 2019-03-11 19:10
Bulk edit quantity in Stock Management

Start with empty database tables,
![Capture1](https://user-images.githubusercontent.com/2993190/54150789-1bee0b80-4418-11e9-8791-99a3722a1036.JPG)

**Comment by unreviewed** [comment] 2019-03-11 19:10
Add 100 to all products.
![Capture4](https://user-images.githubusercontent.com/2993190/54150822-32946280-4418-11e9-82bc-16eb1787da4e.JPG)

**Comment by unreviewed** [comment] 2019-03-11 19:11
Prestshop shows all is well,

![Capture5](https://user-images.githubusercontent.com/2993190/54150852-4344d880-4418-11e9-97c1-bb7d318ddc6a.JPG)

**Comment by unreviewed** [comment] 2019-03-11 19:12
Database table shows many entry’s no atrib_ID and amounts not related to current inventory.

![Capture6](https://user-images.githubusercontent.com/2993190/54150959-7c7d4880-4418-11e9-9fa9-e56a1ccdd10b.JPG)

**Comment by unreviewed** [comment] 2019-03-11 19:17
I assume the the rows without id_product_attribute is a total of each id_product

**Comment by khouloudbelguith** [comment] 2019-03-12 10:21
Hi @unreviewed,

>In All Shop's context you receive notification,
"You can't manage your stock in this shop context: select a shop instead of a group of shops."

Yes, you are right, but this is the behaviour adpted in this page.
![image](https://user-images.githubusercontent.com/16067358/54191770-de8c8b00-44b6-11e9-8980-c82d882e67b8.png)
You can follow our documentation: http://doc.prestashop.com/display/PS17/Stock+overview
>Multi-store
This new stock management system is compatible with multi-store. For obvious reasons, if you have multiple shops inside a group where stocks are not shared, you cannot manage your stock in “all shops” or “group” context. If you try to do so, you might see the following error message.
Instead you have to select a shop in which you can work to edit its stock.
If you’re using a group of shops that share the same quantities, you’ll also have to select a unique shop context instead of a group but any change you make in a shop will also affect the other shops.

About the second issue, we are aware of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #10274, please follow this ticket: #10274
So, I close it.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-12 10:21
Duplicate of #10274

**Closed as completed by khouloudbelguith** 2019-03-12 10:21 UTC
Labels: Duplicate
