### ISSUE TITLE
Error DB Upgrade 1.6.1.23 to 1.7.4.4

### ISSUE THREAD

**Issue by JavierEB** [PrestaShop/PrestaShop#11629] opened 2018-12-06 08:05 UTC
**Describe the bug**
Error DB Upgrade 1.6.1.23 to 1.7.4.4   Using the module 1 click update v5.0  

**To Reproduce**

**Screenshots**
![sin titulo](https://user-images.githubusercontent.com/5004396/49569877-736e6e00-f935-11e8-916c-1ee8beb8f253.jpg)
![sin titulo2](https://user-images.githubusercontent.com/5004396/49569878-736e6e00-f935-11e8-9966-d2bfc52c8c00.jpg)
Updating database schema...
Executing: CREATE TABLE ps_admin_filter (id INT AUTO_INCREMENT NOT NULL, employee INT NOT NULL, shop INT NOT NULL, controller VARCHAR(60) NOT NULL, action VARCHAR(100) NOT NULL, filter LONGTEXT NOT NULL, UNIQUE INDEX admin_filter_search_idx (employee, shop, controller, action), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
Executing: CREATE TABLE ps_module_history (id INT AUTO_INCREMENT NOT NULL, id_employee INT NOT NULL, id_module INT NOT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
Executing: CREATE TABLE ps_translation (id_translation INT AUTO_INCREMENT NOT NULL, id_lang INT NOT NULL, `key` TEXT NOT NULL, translation TEXT NOT NULL, domain VARCHAR(80) NOT NULL, theme VARCHAR(32) DEFAULT NULL, INDEX IDX_ADEBEB36BA299860 (id_lang), INDEX `key` (domain), PRIMARY KEY(id_translation)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
Executing: ALTER TABLE ps_attribute CHANGE color color VARCHAR(32) NOT NULL, CHANGE position position INT NOT NULL DEFAULT '0' 

Attachment log.txt of the module 1 click upgrade
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2652188/log.txt)

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: 7.0.29

**Comment by khouloudbelguith** [comment] 2018-12-06 09:10
Hi @JavierEB,

Thanks for your report.
I did not manage to reproduce the issue after upgrade from PS1.6.1.23 to PS1.7.4.4 using the 1-click upgrade 4.5.0.
![image](https://user-images.githubusercontent.com/16067358/49573342-0c08ec00-f93e-11e8-82ed-cd5105c70cac.png)
But in your log file, I found that you are using the `advancedeucompliance` module, we are aware of this issue, you can follow this [ticket](https://github.com/PrestaShop/PrestaShop/issues/9553#issuecomment-415024108).
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
Thanks to check & feedback.

**Comment by Quetzacoalt91** [comment] 2018-12-06 12:06
Hi @JavierEB,

I guess you previously made a restoration with the module. This column needs an update, as reported by another contributor: https://disqus.com/home/discussion/prestashopbuild/test_the_updated_1_click_upgrade_module_prestashop_developers_blog/?utm_source=reply&utm_medium=email&utm_content=comment_date#comment-3966401197

Run the following SQL request: 
```
UPDATE `ps_attribute` SET `color` = ' ' WHERE `color` IS NULL
```

Then make a new upgrade.

**Comment by JavierEB** [comment] 2018-12-07 22:00
> 
> 
> Hi @JavierEB,
> 
> I guess you previously made a restoration with the module. This column needs an update, as reported by another contributor: https://disqus.com/home/discussion/prestashopbuild/test_the_updated_1_click_upgrade_module_prestashop_developers_blog/?utm_source=reply&utm_medium=email&utm_content=comment_date#comment-3966401197
> 
> Run the following SQL request:
> 
> ```
> UPDATE `ps_attribute` SET `color` = ' ' WHERE `color` IS NULL
> ```
> 
> Then make a new upgrade.

thanks @Quetzacoalt91 @khouloudbelguith  For your help, everything solved. The update process just worked. But now I have another problem, when I activate the debug. 
![error](https://user-images.githubusercontent.com/5004396/49674865-a6b71700-fa73-11e8-832a-db2477951d8c.jpg) E deleted advancedeucompliance modules
themeconfigurator
Thanks companions

**Comment by khouloudbelguith** [comment] 2018-12-10 11:06
@JavierEB, Did you use any module live_edit?
Thanks to disable it, check & feedback.

**Comment by Quetzacoalt91** [comment] 2018-12-11 11:20
Hi @JavierEB,

Your issue is unexpected as we have removed this field from the database, and obviously from SQL requests.
Do not worry, it seems easy to solve it. I'm pretty sure you have an override of the `Hook` class on your shop. You can confirm this by checking the file `override/classes/Hook.php` actually exists.

If yes, you can try to rename it. You *should* get the access back to your shop, but it also means one of your module will behave incorrectly. In that case, look at the comments inside the file to have more details on the concerned module, and contact the maintainer to have a new version of it.

Regards

**Comment by khouloudbelguith** [comment] 2019-01-21 10:32
HI @JavierEB,

Any news about your issues?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-11 11:23
Hi @JavierEB,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-11 11:23 UTC
Labels: Bug, Autoupgrade, No change required

**Comment by JavierEB** [comment] 2019-02-16 10:07
hello sorry for the delay in answering, and been out ... If it is already solved by following your steps and help. thank you
