### ISSUE TITLE
Wrong values on ps_tabs table after first language change/disable in BO

### ISSUE THREAD

**Issue by crishnakh** [PrestaShop/PrestaShop#22016] opened 2020-11-19 14:16 UTC
#### Describe the bug

Wrong translate sidebar names

#### Expected behavior

The sections on the sidebar keeps wrong after change the default language.

#### Steps to Reproduce

1. Fresh install on Portuguese lang.
2. Add Spanish lang in the backoffice
3. Inactive portuguese lang and change the lang of the backoffice's user to spanish.
4. Check the sidebar backoffice, names keeps in Portuguese.

**Screenshots**

#### Additional information
I edited the sql table manually to get this correct. It was ps_tabs table, the translations were all wrong.

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2020-11-19 15:03
Hello @crishnakh 

> I edited the sql table manually to get this correct. It was ps_tabs table, the translations were all wrong.

Don't change the translation manually from the database, it's dangerous to manipulate the database, just follow these steps:

1. BO > **IMPROVE** > **International** > **Translations**

![image](https://user-images.githubusercontent.com/23308427/99682181-42829780-2a7f-11eb-9d19-83b47e3b784e.png)

2. In **Modify translations block**, choose **Back office translations** as **Type of translation** (1)
3. select the spainish language as **Select your language** (2)
4. click on **Modify** button (3)

![image](https://user-images.githubusercontent.com/23308427/99683225-65fa1200-2a80-11eb-8f1f-7bcac7b6ff75.png)

5. under **Admin**, click on **Navigation** submenu (1), then click on **Menu** (2)

![image](https://user-images.githubusercontent.com/23308427/99683258-70b4a700-2a80-11eb-8df2-d9090073fb7e.png)

6. Just right there, you can change the menu translation 

![image](https://user-images.githubusercontent.com/23308427/99683286-78744b80-2a80-11eb-898c-ebcd67ad99a4.png)

7. Save

Hope it helps!
Please check and feedback.

Thanks!

**Comment by crishnakh** [comment] 2020-11-19 15:07
Hi @hibatallahAouadni  thanks for the advice. 

1. I tried as you say at first, but the translations were correct.
2. Then i tried to reinstall language, still all correct in the translations tab.
3. All the translations were ok, but the sidebar names still remain wrong ;) the only way to change the translations was editing it in the database.

Try to reproduce the steps as i commented.

I attach some screenshot of some translations wrong.
![Captura de pantalla 2020-11-19 a las 16 09 07](https://user-images.githubusercontent.com/3185290/99684402-b756d100-2a81-11eb-82c4-dcfe6a1bf354.png)
I searched for the translations with no records.
![Captura de pantalla 2020-11-19 a las 16 09 49](https://user-images.githubusercontent.com/3185290/99684839-31875580-2a82-11eb-9ec1-2e9a0a9cf818.png)
![Captura de pantalla 2020-11-19 a las 16 12 39](https://user-images.githubusercontent.com/3185290/99684864-377d3680-2a82-11eb-874b-d514b6b29a66.png)

**Comment by hibatallahAouadni** [comment] 2020-11-19 15:26
Hello @crishnakh 

I just install PS1.7.6.7 on Portuguese lang, then I add Spanish lang in the backoffice, and change the lang of the backoffice's user to spanish (See the screenshot below)

![image](https://user-images.githubusercontent.com/23308427/99685664-1e28ba00-2a83-11eb-8df9-e185cae14259.png)

I just checked and all the menu is in Spanich (I translate every menu on translate google).
What's weird that we don't have the same traductions!!!!! (see screenshot below)

![image](https://user-images.githubusercontent.com/23308427/99686539-f71eb800-2a83-11eb-99df-12f252a0edf8.png)

Please check and feedback.

Thanks!

**Comment by crishnakh** [comment] 2020-11-19 15:32
Thats really strange. Don't worry, don't know why my lateral menú still remain in portuguese. I think you can close the issue!. Thanks @hibatallahAouadni

**Comment by hibatallahAouadni** [comment] 2020-11-19 15:35
Hello @crishnakh 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-19 15:35 UTC
Labels: Bug, BO, Can't reproduce, Translations, 1.7.6.7
