### ISSUE TITLE
Specific prices are not displayed in the cart if from_quantity is greater than 1

### ISSUE THREAD

**Issue by MDWeb-Lille** [PrestaShop/PrestaShop#14181] opened 2019-06-13 06:56 UTC
**Describe the bug**
If you set a specific price for a product **with "from x units" to 1**, **the discount is displayed** next to the unit price of the product in the shopping cart page.
If you set a specific price for a product with "from x units"  **with a value greater than 1**, **the discount is not displayed** next to the unit price of the product in the shopping cart page.

**To Reproduce**
1. Go to a back office product page -> price tab
2. Add a specific price

- with all currencies
- all groups
- all customers
- all countries
- all combinations
- no date limitation
- from 1 unit
3. Save the specific price, go to the product page in front, add to cart with 1 quantity
4. The reduction is visible on the cart
5. Remove products in cart
6. Go to the back office, update the previous specific price, with "from 2 units"
7. Save the specific price, go to the product page in front, add to cart with 2 quantity
8. The discount is not displayed (applied but not displayed)

**Screenshots**
See video in zip file
[Enregistrement de l’écran 2019-06-13 à 08.30.00.mp4.zip](https://github.com/PrestaShop/PrestaShop/files/3284530/Enregistrement.de.l.ecran.2019-06-13.a.08.30.00.mp4.zip)

**Additionnal information**
PrestaShop version: 1.7.5.1 fresh install
PHP version: 7.2.13

**Comment by khouloudbelguith** [comment] 2019-06-13 08:15
Hi @MDWeb-Lille,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2, it is reproduced with a product which have combinations.
But this issue is fixed in the PS1.7.6.0.
https://drive.google.com/file/d/1m-ZJ4iKlyZGJPS9q3RiXp6D9KeDcLdo-/view
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-13 08:15 UTC
Labels: Bug, Minor, Combinations, Fixed, 1.7.5.2, Shopping carts FO

**Comment by MDWeb-Lille** [comment] 2019-06-13 08:26
Hi !

Thanks for the video response!

Is it possible to give me the PR corresponding to this correction?

Thank you in advance !

**Comment by matks** [comment] 2019-06-13 08:42
I would say either https://github.com/PrestaShop/PrestaShop/pull/11656 or https://github.com/PrestaShop/PrestaShop/pull/10465

**Comment by khouloudbelguith** [comment] 2019-06-13 09:56
Hi @MDWeb-Lille,

Here's the changelog for the PS1.7.6.0beta1 for more details.
https://assets.prestashop2.com/fr/system/files/ps_releases/changelog_1.7.6.0-beta.1.txt
Thanks!
