### ISSUE TITLE
I get [PrestaShop\PrestaShop\Core\Domain\Shop\Exception\ShopException code 0] error when I try to upload a custom logo..  how can I fix this or is this a bug?

### ISSUE THREAD

**Issue by Aidam-puk** [PrestaShop/PrestaShop#21695] opened 2020-10-31 11:19 UTC
#### Describe the bug

I get [PrestaShop\PrestaShop\Core\Domain\Shop\Exception\ShopException code 0] error when I try to upload a custom logo..

how can I fix this or is this a bug?

#### Steps to reproduce

1. Login to the backoffice of your shop
2. Go to "Design" > "Theme & Logo"
3. Try to upload a custom png logo

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2020-11-02 09:50
Hello @Aidam-puk 

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- steps to reproduce
- host
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by matks** [comment] 2020-11-02 09:58
@Aidam-puk Look into your php logs to read a more detailed error message

**Comment by hibatallahAouadni** [comment] 2020-11-23 10:54
Hello @Aidam-puk ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Daaaaad** [comment] 2021-01-27 22:46
Hello, I have the same problem as @Aidam-puk and another user in the forum: https://www.prestashop.com/forums/topic/1016205-prestashopprestashopcoredomainshopexceptionshopexception-code-0/

Here's the context: I copied an existing website to create a "dev" version of it. I'm using git with a .gitignore so files may be missing 🤔

Anyway the message we get is not very clear: `An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Shop\Exception\ShopException code 0]`

And according to me the php logs do not contain relevant information 😔
[dev.log](https://github.com/PrestaShop/PrestaShop/files/5883577/dev.log)

Could you help?

**Comment by hibatallahAouadni** [comment] 2021-01-28 10:30
Hello @Daaaaad 

Could you please provide steps to reproduce the issue, your PrestaShop version, your PHP version, ...
And I will re-open the issue :wink: 

Thanks!

**Comment by Daaaaad** [comment] 2021-01-28 10:42
Hi @hibatallahAouadni,

Here are the steps and the requested information:

1. Login to the backoffice of your shop
2. Go to "Design" > "Theme & Logo"
3. Try to upload a custom png logo

PHP version: 7.2.34
PrestaShop version: 1.7.6.7

I'm aware that this error could be related to specific installation parameters but the error message is too much "generic" and I can't find the solution 😔

**Comment by hibatallahAouadni** [comment] 2021-01-28 16:12
Thanks @Daaaaad I will try to reproduce it :wink:

**Comment by hibatallahAouadni** [comment] 2021-01-28 16:14
Hello @Daaaaad 

DId you change the **Header logo** or **Mail logo**?
Please check and feedback.

Thanks!

**Comment by Daaaaad** [comment] 2021-01-28 20:29
Hi @hibatallahAouadni, that's the "header logo" sorry I forgot to mention it 👍

**Comment by hibatallahAouadni** [comment] 2021-02-01 21:42
Hello @Daaaaad 

Sorry for the late response.
I didn't manage to reproduce your issue with PS1.7.6.7 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1EoTLrEmnpWxOsyOdL9SYND2jPHCXeh9i/view

Please check and feedback.
Thanks!

**Comment by Daaaaad** [comment] 2021-02-02 08:16
Hello @hibatallahAouadni,

As I told previously: "I'm aware that this error could be related to specific installation parameters but the error message is too much generic and I can't find the solution". So it doesn't surprise me that you didn't succeed to reproduce it with a fresh new install 😉

Anyway several people are encountering this problem and the error message that is displayed do not allow us to find a solution 😔

**Comment by hibatallahAouadni** [comment] 2021-02-02 08:19
Hello @Daaaaad 

Well then, how about we close this issue cause even the author never response, and you open a new issue as an improvement to specify the error message ?
I think that's better :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-22 14:45
Hello ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-22 14:45 UTC
Labels: Bug, BO, Design, Theme & logo, No change required, 1.7.6.8

**Comment by DiV666** [comment] 2022-05-21 23:34
In case it helps someone.

After investigating where the error might be, I saw that the error was coming from the checkImageMemoryLimit method

My problem was that I had the php memory_limit variable set to 64mb and it wasn't enough to process the image, so increasing it to 256mb in the php.ini fixed it.

**Comment by GregaMohorko** [comment] 2022-07-24 20:24
I also have this problem. Cannot upload a logo for the 2nd shop.

Steps to reproduce:

1. Have only one shop
2. Enable multistore
3. Create 2nd shop in different group
4. Try to upload Header logo

![image](https://user-images.githubusercontent.com/26408492/180664494-cd183883-4461-4019-8776-84fa9dfe9a8f.png)
