### ISSUE TITLE
Unable to call getOrderShippingCostExternal($params) method

### ISSUE THREAD

**Issue by glukash** [PrestaShop/PrestaShop#17803] opened 2020-02-24 14:36 UTC
Im trying to force Prestashop to call a getOrderShippingCostExternal($params) method from my carrier module.

To make it happen I need to set need_range to false.
Because in Cart::getPackageShippingCostFromModule() we have a code:

`if (!$carrier->need_range) {
    return $module->getOrderShippingCostExternal();
}`

The problem is that little earlier in Carrier::getCarriersForOrder()

we have a code:
`if (is_array($groups) && !empty($groups)) {
    $result = Carrier::getCarriers($id_lang, true, false, (int) $id_zone, $groups, self::PS_CARRIERS_AND_CARRIER_MODULES_NEED_RANGE);
    } else {
        $result = Carrier::getCarriers($id_lang, true, false, (int) $id_zone, array(Configuration::get('PS_UNIDENTIFIED_GROUP')), self::PS_CARRIERS_AND_CARRIER_MODULES_NEED_RANGE);
        }`

So only modules that need_range set to 1 are taken.

It is not possible to call getOrderShippingCostExternal($params) having is_module = 1 and need_range = 0

PrestaShop version: 1.7.6.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-02-24 14:53
Hi @glukash,

Could you please add steps to reproduce the issue in a new comment.
It will help us if you can attach your module.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-25 07:14
Hi @glukash,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-25 07:14 UTC
Labels: Bug, CO, Modules, Carriers, No change required, 1.7.6.2

**Comment by KoreLewi** [comment] 2022-12-18 06:58
Hi @glukash 
Have you managed to find a solution ?
I have encountered the same issue.

**Comment by mehdi-ghezal** [comment] 2023-03-14 05:13
Same issue and easy to reproduce, create a module that register a carrier like this.

```php
// Cereate carrier
$carrier = new Carrier();
$carrier->name ='My custom carrier';
$carrier->id_tax_rules_group = 0;
$carrier->id_zone = 1;
$carrier->url = '';
$carrier->active = true;
$carrier->is_free = true;
$carrier->deleted = false;
$carrier->shipping_handling = false;
$carrier->range_behavior = 1;
$carrier->is_module = true;
$carrier->shipping_external = true;
$carrier->external_module_name = 'mymodule';
$carrier->need_range = false;
$carrier->grade = 9;

// Add delay
foreach (Language::getLanguages(true) as $language) {
    if ($language['iso_code'] == 'fr') {
        $carrier->delay[$language['id_lang']] = 'Enlèvement sours 24-48h après prise de rendez-vous';
    }
}

// Save it
$carrier->add();

// Save its ID
if (Shop::isFeatureActive()) {
    foreach (Shop::getShops(true) as $shop) {
        Configuration::updateValue('MY_CUSTOM_CARRIER_ID', $carrier->id, false, $shop['id_shop_group'], $shop['id_shop']);
    }
} else {
    Configuration::updateValue('MY_CUSTOM_CARRIER_ID', $carrier->id, false, null, null);
}

// Add groups
foreach (Group::getgroups(true) as $group) {
    Db::getInstance()->execute('INSERT INTO ' . _DB_PREFIX_ . 'carrier_group VALUE (\'' . $carrier->id . '\',\'' . $group['id_group'] . '\')');
}
```

Go in BO and setup the zone of the carrier ; it is not shown in checkout.
Restart the process but this time in your module replace the line

```php
$carrier->need_range = false;
```

by this line

```php
$carrier->need_range = true;
```

And now (after setup the zone in BO) the carrier is displayed in checkout.

**Comment by mehdi-ghezal** [comment] 2023-03-14 06:22
In the same line, the [documentation](https://devdocs.prestashop-project.org/1.7/modules/carrier/#computing-the-shipping-price) state "The returned value must be a float or false if the carrier is not known or disabled." but even if we return false the carrier is still displayed. This at least for Prestashop 1.7.3.x.

Sorry I don't have the bandwidth to be more specific or open an additionnal ticket but at least your team may check both issue at the same time and so save some time.
