### ISSUE TITLE
Error Uncaught Exception: Could not load type "form": class does not exist.

### ISSUE THREAD

**Issue by felipeschmitz** [PrestaShop/PrestaShop#12157] opened 2019-01-14 22:38 UTC
**Describe the bug**
hi, in admin product images, i click the image, not show detail this, but this erros:

Uncaught Exception: Could not load type "form": class does not exist. {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"form\": class does not exist. at /home/public_html/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php:86)"} []

Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "Could not load type "form": class does not exist." at /home/public_html/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php line 86 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"form\": class does not exist. at /home/public_html/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php:86)"} []

thanks.

**Additionnal information**
PrestaShop version: 1.7
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-01-15 11:49
Hi @felipeschmitz,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-14 10:05
Hi @felipeschmitz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-14 10:05 UTC
Labels: Bug, BO, No change required

**Comment by choclove90** [comment] 2019-02-28 09:50
Hello. Had a nightmare with this issue.. this is a Prestashop 1.7.5.0 fatal bug, the only reason why this isn't exploding is because there aren't many shops moving to 1.7.5.0

Anyway, 1.7.5.1 seems to correct this. If upgrade is not an option, just replace the following folders with the ones from 1.7.5.1 (make sure to backup first):

/public_html/src/PrestaShopBundle/Controller/Admin

/public_html/src/PrestaShopBundle/Resources/views/Admin

Also, after you replace folders the image editing form seems to work only when DEBUG is active.

**Comment by MissLemon** [comment] 2020-07-23 11:22
When DEBUG mode is OFF, you have to delete the cache after replacing the folders. And then it will works.
