### ISSUE TITLE
ps-reminder module bug

### ISSUE THREAD

**Issue by evgenij-sobolev** [PrestaShop/PrestaShop#20466] opened 2020-08-05 12:28 UTC
#### Describe the bug

In prestashop 1.7, the followup module was renamed to ps-reminder.
But, in the module settings, generateing wrong url for the cron task:

https://prnt.sc/tugggu

It is necessary to replace the followup with ps_reminder

#### Additional information

* PrestaShop version: 1.7.6.x
* PHP version: 7.3

**Comment by khouloudbelguith** [comment] 2020-08-05 13:16
Hi @evgenij-sobolev,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9799
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-05 13:16
Duplicate of #9799

**Closed as completed by khouloudbelguith** 2020-08-05 13:16 UTC
Labels: Duplicate
