### ISSUE TITLE
Cannot add Iframe

### ISSUE THREAD

**Issue by willgo34** [PrestaShop/PrestaShop#22097] opened 2020-11-25 11:59 UTC
#### Describe the bug

I allowed iframes in my parameters and turned off htmlpurifier but I cannot add youtube videos

#### Expected behavior

A video should be added to my description

#### Steps to Reproduce

1. Go to 'parameter'
2. Turn on allow iframe / deactivate HTMLpurifier
3. Add a youtube video to a description

**Loom**

https://www.loom.com/share/a6161d52fd2843aea6297909d2da9658

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2020-11-25 12:33
Hello @willgo34 

Could you please check if your issue is similar to this one #18917 
Please check and feedback.

Thanks!

**Comment by willgo34** [comment] 2020-11-25 14:25
Hello, thanks but it's a sugestion for a feature in #18917.  For my case it's bug.

**Comment by hibatallahAouadni** [comment] 2020-11-25 15:33
Hello @willgo34 

I didn't manage to reproduce your issue with PS1.7.6.7, see the attached screen record below:

https://drive.google.com/file/d/14ZETr3HbDtDTC5tUFmBJXs5y5Ina8K0X/view

Please check and feedback.

PS: even when i deactivate HTMLpurifier, the video is well displayed in the product page FO

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-16 14:58
Hello @willgo34 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-16 14:58 UTC
Labels: Bug, BO, Product settings, No change required, 1.7.6.x
