### ISSUE TITLE
No carriers proposed after deletion of address

### ISSUE THREAD

**Issue by stoycho** [PrestaShop/PrestaShop#30350] opened 2022-11-18 13:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When products are added to a cart, the system sets ps_cart_product.id_address_delivery to current address of the cart. Later during the checkout process, function Carrier::getAvailableCarrierList uses this address to determine validity of carriers for this product (through function Address::isCountryActiveById). So if the address in question is deleted while the cart is still pending, then Carrier::getAvailableCarrierList returns empty list, therefore no carriers can be found for the cart, and the user has no other option than removing all his products from the cart and adding them again.

### Expected behavior

System should not fail to propose carriers when address is deleted while the cart is still pending.

### Steps to reproduce

1. Add a product to the cart from FO.
Note: the current default address of the cart should be not used in previous orders (so it can be deleted after)
2. Do not proceed to finish the order yet.
3. Check the id_address_delivery field of the newly created ps_cart_product record.
4. Delete this address from BO.
5. Go back to FO and try to finish the order.
6. At the step for choosing the carrier there will be an error that no carriers are available.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by matks** [comment] 2022-11-18 16:30
Hello @stoycho and thank you for the bug report and the pull request

> System should not fail to propose carriers when address is deleted while the cart is still pending.

But how can PrestaShop suggest carriers when address is deleted? Depending on where you want to deliver, carriers will be different. Without address, you cannot ask PrestaShop for carriers? 🤔

**Comment by Hlavtox** [comment] 2022-11-18 19:44
> But how can PrestaShop suggest carriers when address is deleted? Depending on where you want to deliver, carriers will be different. Without address, you cannot ask PrestaShop for carriers? 🤔

The same as when you create an empty cart, it will offer an address for default country. 👍

**Comment by Hlavtox** [comment] 2022-11-18 19:51
However, I think the Prestashop should automatically validate and reset the address id for the cart, so the following logic like getting carriers work correctly. Needs investigation. 🤔

**Comment by stoycho** [comment] 2022-11-19 11:04
> Hello @stoycho and thank you for the bug report and the pull request
> 
> > System should not fail to propose carriers when address is deleted while the cart is still pending.
> 
> But how can PrestaShop suggest carriers when address is deleted? Depending on where you want to deliver, carriers will be different. Without address, you cannot ask PrestaShop for carriers? 🤔

User may have more than one address. Currently, when some address is deleted, the system automatically resets the current address of the cart to 0, so it automatically suggests the next default address as an address for the cart, when trying to build the list of carriers. I think this is an acceptable behaviour. But because the address in the cart_product is not reset to 0, it cannot transmit this automatic new suggestion to products which are already in the cart. And in the same time it cannot find appropriate carrier for those products, because their address does not exist anymore.
That is, to my mind, an inconsistency between the logic for cart address and cart_product address.
A reset of the adress of cart_product to 0 would reconcile both logics.

**Comment by AureRita** [comment] 2022-11-21 10:54
Hi @stoycho 

Thank you for your report and for your PR :rocket: 

Can you say where I can find this variable from the BO ? 
"3. Check the id_address_delivery field of the newly created ps_cart_product record.
4. Delete this address from BO."

Because currently, I don't know where I can find them and delete them 

Waiting for your feedback

**Comment by stoycho** [comment] 2022-11-21 11:14
Hi @AureRita 
You can delete addresses from the Back Office. In the menu bar in the left select section "Customers" and then "Addresses". Then find the address which you want to delete and delete it by clicking on the corresponding button located at the right on the line of the address.

Point 3 (Check the id_address_delivery field of the newly created ps_cart_product record) is not necessary unless you cannot find the address without knowing it's ID. To check the value of the field `id_address_delivery` of table `ps_cart_product` you need to make an SQL query directly on your database. For example with phpMyAdmin, or with another mysql client, if your DB is MySQL.

**Comment by AureRita** [comment] 2022-11-21 15:29
Hi @stoycho ,

Thank to your new details, I reproduce the issue with PrestaShop version 1.7.8.8, As we can see in this video 

[Untitled_ Nov 21, 2022 4_26 PM.webm](https://user-images.githubusercontent.com/100699445/203093481-4d5a174b-d155-476c-9596-67f5deb07d30.webm)

I'll add this to the backlog so it can be fixed.

Thanks

**Comment by stoycho** [comment] 2022-11-22 11:44
Thanks for the help, @AureRita .
Hopefully, this issue should be fixed with the PR #30349 .

**Comment by Hlavtox** [comment] 2024-02-28 08:56
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35017

**Closed as completed by Hlavtox** 2024-02-28 08:56 UTC
Labels: Bug, Minor, FO, Needs Specs, Addresses, Carriers, PR available, Verified, 1.7.8.7
