### ISSUE TITLE
Users can use Discounts / Cart rule even if its finished or disabled

### ISSUE THREAD

**Issue by matydominguez** [PrestaShop/PrestaShop#29389] opened 2022-08-18 17:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We´ve createad a valid discount from 19th July to 21th July.
It was used more than 70 times and now is finished.

Since it was finished:

- Those users who have used that discount but not have created an order can still create an order with that coupon even if it finished

- We have disabled that coupon and even that users who added to cart can use it even if it disabled and finished.

Now we´ve changed to 0 the amount of discounts an user can use it.

Sincerly this is a bad way to manage cart rules

### Steps to reproduce

Explained

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by hibatallahAouadni** [comment] 2022-08-19 08:20
Hello @matydominguez 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19393. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-19 08:20
Duplicate of #19393

**Closed as completed by hibatallahAouadni** 2022-08-19 08:20 UTC
Labels: Bug, Duplicate, Invalid
