### ISSUE TITLE
Date is not correctly displayed on orders page

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18275] opened 2020-03-23 16:52 UTC
## Describe the bug
In orders page , the order date is not correctly displayed when side menu is displayed

#### Expected behavior

The date should be correctly displayed

#### Steps to Reproduce

1. Go to BO => Sell => Orders => Orders 
2. See error

**Screenshots**
**Side menu displayed**
![capture d'écran_4](https://user-images.githubusercontent.com/40635814/77340055-07cc3200-6d2d-11ea-987c-e99b499c54ba.png)

**Side menu not displayed
![capture d'écran_5](https://user-images.githubusercontent.com/40635814/77341353-e2d8be80-6d2e-11ea-98a2-89779f106005.png)
**

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-23 17:02
Ping @PrestaShop/prestashop-product-team this issue should be fixed in the 1.7.7.0, is it?

Thanks!

**Comment by marionf** [comment] 2020-03-23 17:59
As it's a regression of the 1.7.7, yes

**Comment by atomiix** [comment] 2020-03-25 13:20
@SD1982 @khouloudbelguith  @marionf I'm not sure we can do something about that. It's not really when the side menu is displayed, it's related to the screen size. On a big screen you can have the side menu open and the date being display on only 1 line : 

![Capture d’écran 2020-03-25 à 14 18 38](https://user-images.githubusercontent.com/2168836/77540614-aed2da00-6ea3-11ea-8c86-a4ba5b5afa3b.png)

**Comment by marionf** [comment] 2020-03-26 09:29
Maybe @NeOMakinG has an idea to fix that ?
Or do you confirm that we can't fix that ?

**Comment by matks** [comment] 2020-03-27 16:30
> Maybe @NeOMakinG has an idea to fix that ?
> Or do you confirm that we can't fix that ?

The standard solution for this kind of problem is to define a minimum length for the column.
When the screen is too small, then the page will grow larger than the screen and you'll need to scroll horizontally.

I dont know if this is something we want 🤔 

@prestascott has been working on this topic

**Comment by jolelievre** [comment] 2020-03-30 15:59
@prestascott @NeOMakinG I made a little PR that overrides the `break-word` only for date time columns https://github.com/PrestaShop/PrestaShop/pull/18373
Do you think it's an acceptable solution? It shouldn't change dramatically the grid display since only date time columns are impacted (and they can still break between the date and the time)

![Capture d’écran 2020-03-30 à 17 58 36](https://user-images.githubusercontent.com/13801017/77934272-2348b700-72b0-11ea-9325-28d23a536d57.png)

**Comment by NeOMakinG** [comment] 2020-03-31 07:30
That right @jolelievre, I wouldn't have done something else to be honest

**Comment by jolelievre** [comment] 2020-03-31 07:59
> That right @jolelievre, I wouldn't have done something else to be honest

That means a lot to me! 🥺

**Comment by Progi1984** [comment] 2020-04-01 07:54
Fixed by #18373

**Closed as completed by Progi1984** 2020-04-01 07:54 UTC
Labels: Bug, Trivial, BO, Order, Regression, Fixed, Front-end, migration, PR available, 1.7.7.x
