### ISSUE TITLE
PS 1.7.4.2 ignore discount setting: Exclude discounted products: YES

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#10454] opened 2018-09-16 20:56 UTC
**Describe the bug**
PS 1.7.4.2 ignore discount setting: Exclude discounted products: YES. 

**To Reproduce**
1. Go to 'Catalog, Discounts, Create discount 10%, Exclude discounted products: YES'

2. Go to 'FO insert to cart product with price reduction and without price reduction '
3. Insert created voucher
4. See error:

FO: showing wrong price (is counted from all product)
BO: showing wrong price in overview (Discounts, total) but above is discount calculate correctly without product which are with price reduce.

Thank you

Best regards

PN

**Screenshots**
![1](https://user-images.githubusercontent.com/38213520/45600713-6f4f4600-ba01-11e8-89f4-d25879e929ce.JPG)
![2](https://user-images.githubusercontent.com/38213520/45600719-76765400-ba01-11e8-9155-614514bd6662.JPG)
![3](https://user-images.githubusercontent.com/38213520/45600833-7f682500-ba03-11e8-9990-ebda58b8f286.JPG)
![4](https://user-images.githubusercontent.com/38213520/45600838-8b53e700-ba03-11e8-8e60-bdd48b6b3411.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.30-0+deb9u1

**Comment by khouloudbelguith** [comment] 2018-09-17 07:41
Hi @PeNov,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10300
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-17 07:41
Duplicate of #10300

**Closed as completed by khouloudbelguith** 2018-09-17 07:41 UTC
Labels: Duplicate
