### ISSUE TITLE
Import news products by CSV ignorate the 'active' field

### ISSUE THREAD

**Issue by alexvalentin-chama** [PrestaShop/PrestaShop#15408] opened 2019-09-04 21:15 UTC
Hi!
When we tried to import new products by CSV in our Prestashop 1.7.4, we need to activate the products later because **the system not recognize the "activate" field** with the first import and it's a problem for us because we need to do 2 steps:

1. Import the standard csv for products.
2. Then, import a CSV with the ID/SKU and the column Activate again.

This is a new feature of Prestashop 1.7.4 or is a bug?

**Comment by khouloudbelguith** [comment] 2019-09-05 09:46
Hi @v-alexer,

Thanks for your report.
By default, if import products ignoring the "active" field => they will be enabled by default.
We will add an option to activate/disable products in bulk in the import process
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12653
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-05 09:46
Duplicate of #12653

**Closed as completed by khouloudbelguith** 2019-09-05 09:46 UTC
Labels: Duplicate
