### ISSUE TITLE
No carriers available

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#12267] opened 2019-01-22 19:12 UTC
Carriers are not always available for customers. Issue is in cart - but i don't know how to reproduce it. **When customer will remove all items from cart and add them again** they will be able to choose carrier without issue of "no carriers available". I had this error when i was creating new module and needed orders in backoffice.

I am creating this issue for others, who don't know how to help customers and i have proposition for partial solve it. **Prestashop should have an option to let create order in those cases, with extra information 'Your order maybe extra charged after confirmation' - in that way, seller will not loose order.** 

in my case it's second time problem with cart, previous issue (not resolved) https://github.com/PrestaShop/PrestaShop/issues/11436

**Additionnal information**
PrestaShop version: 1.7.5 (but it was already on 1.7.0 and all of them)
PHP version: 7.1.25

**Comment by khouloudbelguith** [comment] 2019-01-23 09:19
Hi @slupostrupek,

Sorry, I did not manage to reproduce the issue following your steps
https://drive.google.com/file/d/1mtTiIf_DuwX7zxuvDCBRPM5kupaStHy1/view
If PrestaShop Carriers Are Not Available At Checkout, you need to check:

1. Carrier Is Inactive: PrestaShop carrier status is the first thing you should consider
Incorrect Zone Assign or Country Disabled: Zone association is among the first things to check if a created carrier does not show for a specific shopper. When configuring PrestaShop carrier you are supposed to assign it to zones, this very carrier can deliver parcels within. If a carrier is not assigned to the zone, customer address belongs to, then it will not show as a delivery method at the checkout.
2. Carrier Is Not Allowed for Customer Group: This detail might easily be skipped, since you can have hundreds and thousands of customers, belonging to various customer groups. If some customer belongs to the group that is not served by the current shipper, it will not be offered as a delivery method for this customer
3. Weight or Price Ranges Are Not Specified: Creating PrestaShop carrier you usually define billing cost for each by one of the criteria: order price or weight. Having selected a suitable method, you need to create ranges and set prices for them. In case ranges are not created, “The product selection cannot be delivered by the available carrier(s). Please amend your cart” message will display at shipping step for a customer.
4. Package Dimensions Are Out of Range: If all above listed settings are configured properly but still PrestaShop carrier does not display at the checkout, you have to compare package dimensions with maximum dimensions PrestaShop carrier can handle. If the package goes beyond these limits, the carrier can’t ship it and, respectively will not display as a delivery method.

Thanks to check & feedback.

**Comment by simondaigre** [comment] 2019-01-23 21:47
I have the same issues. Some customers have "no carriers available". The only solution is to delete cart in backoffice and re-add same products.
I think this issue is related to editing carriers prices, who change cart's carrier ID.. but I can't confirm it.

**Comment by khouloudbelguith** [comment] 2019-01-24 11:15
Hi @simondaigre,

About the strange behavior, while editing the carrier, we have a previous ticket https://github.com/PrestaShop/PrestaShop/issues/9592, it is added to our bug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-29 16:35
Hi @slupostrupek,

I manage to reproduce an issue similar reported here: #10903 with free shipping

Steps to reproduce the issue

Create cart rule
1.1 without code
1.2 In the condition Tab "Minimum amount 100 EUR & Shipping included
1.3 In the actions tab, apply any action => Free shipping
Go to FO, add to cart a product which price = 70 EUR < 100 EUR (must be < 100 EUR) => so the cart rule is not applied
Complete your order => in step 3: SHIPPING METHOD => Unfortunately, there are no carriers available for your delivery address.
Only following these steps, I have "No carriers available" in the FO.
Thanks!

**Comment by simondaigre** [comment] 2019-02-04 19:56
I finally found what's wrong.

Sometimes, when a customer create a new address, the new id_address_delivery is set to cart but not to cart_detail. That's why PS cannot find available carriers due to the fact id_address_delivery from cart didn't match cart_detail.

I can't reproduce this issue but some of my customers' clients have this issue. Maybe an ajax issue ?

Issue only happens for PS 1.7 customers (tested 1.7.2.4 - 1.7.4.0 and 1.7.5.0). No overrides or custom modifications.

**Comment by khouloudbelguith** [comment] 2019-02-05 08:22
Hi @simondaigre,

So, you have the same issue reported to this ticket: #9932?
@slupostrupek, could you please confirm that your issue is similar to this ticket: #9932?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 07:59
Hi @slupostrupek,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-07 07:59 UTC
Labels: Bug, FO, Carriers, No change required, 1.7.5.0
