### ISSUE TITLE
AH01071: Got error 'PHP message: PHP Warning: Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#14119] opened 2019-06-08 06:30 UTC
**Description**

Enable APC cache in performance section and watch logs. If you dont see anything before this patch, maybe yo have a small shop. it is need to overpass the limit $maxCachedObjectsByTable = 10000

>Edited by Khouloud

Steps to reproduce the issue

1. Create more than 10000 products
2. Go to FO
3. See error

![image](https://user-images.githubusercontent.com/16067358/105337283-85c1c980-5bda-11eb-9fe4-49f7210b36aa.png)

Prestashop 1.7.5.2 on php 7.2.19
today I've this warning:

`AH01071: Got error 'PHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 567\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\n'`

I've also read this topic https://www.prestashop.com/forums/topic/582890-cannot-use-a-scalar-value-as-an-array/

**Comment by khouloudbelguith** [comment] 2019-06-10 14:08
Hi @centoasa,

Thanks for your report.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12683 to fix the issue.
Your ticket is a duplicate of #12509
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-10 14:08
Duplicate of #12509

**Comment by slal2003** [comment] 2020-04-22 19:22
Hi, I am an end user and getting the exact same warning on Prestashop 1.7.6.4:
PHP Warning:  Cannot use a scalar value as an array in /classes/cache/Cache.php on line 463
It looks like this is not at a all a duplicate of  #12509.
<img width="1511" alt="Screenshot 2020-04-22 at 21 22 19" src="https://user-images.githubusercontent.com/37602955/80024451-6547d000-84df-11ea-8670-f43d5b820dc6.png">

**Comment by Dakror** [comment] 2020-07-02 08:31
https://github.com/PrestaShop/PrestaShop/blob/b223331f5d4df42babbdd1fabbaa0a4457c0f326/classes/cache/Cache.php#L515

This is the source of the issue.

**Comment by Dakror** [comment] 2020-07-02 08:42
@khouloudbelguith please reopen and fix.

**Comment by davidglezz** [comment] 2020-08-04 10:44
I fixed with https://github.com/PrestaShop/PrestaShop/pull/20446

**Closed as completed** 2021-01-21 10:18 UTC
Labels: Bug, Performance, Fixed, 1.7.5.2, PR available
