### ISSUE TITLE
Acces information page page issue CPU is fully

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#19256] opened 2020-05-22 01:04 UTC
Hi,

I try to access this page but it keeps loading and I get 505 error message so I edit the Nginx and Apache as it described on the knowledge
but I still can't access
https://domaine.com/backoffice/index.php/configure/advanced/performance/?_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 

https://drive.google.com/file/d/1Ma6BJm2bYgC1PygVf2WzkFk-p2P-jzbC/view

Regards

the Plesk support replied
> Hello,
> I was not able to reproduce the exact error 505, however, when accessing PrestaShop dashboard the following errors appeared in Websites & Domains > domaine.com > Logs when clicking on Parametres acances > Informations: 
> Code 503 message: GET /backoffice/index.php/configure/advanced/system-information/?_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.0
> (104)Connection reset by peer: AH01075: Error dispatching request to :
> The error 503 means that the website is unavailable and indicates the server’s lack of availability due to overload or being down, therefore, the connection is being reset.
> 
> At that moment server's CPU is fully loaded by php-fpm process of the website:
> top - 10:32:26 up 23:05,  1 user,  load average: 0.98, 1.44, 1.35
> Tasks: 133 total,   2 running, 131 sleeping,   0 stopped,   0 zombie
> %Cpu(s):  9.4 us, 18.2 sy,  0.0 ni, 70.1 id,  0.9 wa,  0.0 hi,  0.2 si,  1.2 st
> KiB Mem :  8008696 total,   725008 free,   835728 used,  6447960 buff/cache
> KiB Swap:        0 total,        0 free,        0 used.  6717932 avail Mem
> 
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
> 11972 store20+  20   0  591444  41356  23196 R  99.7  0.5   0:37.55 php-fpm
> 
> After that, the website goes offline. To make it online again I have restarted the php-fpm process of the website:
> systemctl restart plesk-php73-fpm
> 
> I have also found the following messages in the /var/log/plesk-php73-fpm/error.log:
> [20-May-2020 09:29:50] WARNING: [pool domaine.com] server reached max_children setting (10), consider raising it
> [20-May-2020 11:01:02] WARNING: [pool domaine.com] server reached max_children setting (10), consider raising it
> The max_children PHP directive is the maximum number of child processes to be created by PHP.
> I have raised this value for the domain via Domains > domaine.com > PHP Settings to pm.max_children=20.
> 
> However, it did not fix the issue.
> 
> I have also noticed that PrestaShop was not installed via Websites & Domains > domaine.com > Applications. The application was not also found after using Scan button.
> 
> In addition, I have created a test website testdomain.com and installed a WordPress instance on it. Pressing any buttons on the WordPress admin dashboard does not result in any errors or timeouts. This test website used the same PHP settings and nginx as a proxy server. The website was removed after the testing. 
> 
> Summarizing all of the above, the PrestaShop application consumes too much CPU but cannot load the required page. Being a Plesk support engineer, I can do only superficial troubleshooting on that matter. Thus, I would suggest you contacting the website developer or PrestaShop support directly to get more information regarding the issue and let me know if they find anything related to Plesk.
> 
> I appreciate your understanding.
> Best regards,
> 
> Yaroslav Tarasov
> Technical Support Engineer
> Plesk
>

**Comment by florine2623** [comment] 2020-05-22 10:42
Hi @go-sudo ,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots

Thanks!

**Comment by go-sudo** [comment] 2020-05-22 12:49
host : contabo

CPUIntel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (4 core(s))VersionPlesk Obsidian v18.0.26_build1800200410.18 os_CentOS 7OSCentOS Linux 7.8.2003 (Core)Key number System Uptime:3 day(s) 03:12 | CPU | Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (4 core(s)) | Version | Plesk Obsidian v18.0.26_build1800200410.18 os_CentOS 7 | OS | CentOS Linux 7.8.2003 (Core) | | System Uptime: | 3 day(s) 03:12
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CPU | Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (4 core(s))
Version | Plesk Obsidian v18.0.26_build1800200410.18 os_CentOS 7
OS | CentOS Linux 7.8.2003 (Core)
server setup and configuration : https://bit.ly/2LRY7E0
PrestaShop version (source) 1.7.6.2 
debug mode report 
PHP error logs
apache error log

  |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --

2020-05-22 14:46:09	Error	41.249.240.238	503	GET /admin/index.php/configure/advanced/system-information/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg HTTP/1.0	https://store.com/admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36	1.35 K	Apache SSL/TLS access
2020-05-22 14:47:09	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: https://store.com/admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg				Apache error
2020-05-22 14:46:33	Error	41.249.240.238	503	POST /admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg HTTP/1.0	https://store.com/admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36	4.40 K	Apache SSL/TLS access
2020-05-22 14:47:33	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: https://store.com/admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg				Apache error
2020-05-22 14:46:35	Error	41.249.240.238	503	GET /admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg HTTP/1.0	https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36	1.35 K	Apache SSL/TLS access
2020-05-22 14:47:35	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6				Apache error

javascript console log: I can't access 

I can provide you backoffice access

Regards

**Comment by florine2623** [comment] 2020-05-22 13:33
This is a server error. It does not come from PrestaShop core.

If you are using PHP 7.3, please downgrade to 7.2.
Here's he compatibility chart :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I advise you to put this file in the root of your website and go to yourwebsite.com/php_info.php
[php_info.php.zip](https://github.com/PrestaShop/PrestaShop/files/4668279/php_info.php.zip)
You can see the recommandation of PrestaShop and you will be able to change your server configuration.

**Comment by go-sudo** [comment] 2020-05-22 14:29
HI @florine2623 
I switch to 7.2
2020-05-22 16:10:34 | Error | 41.249.240.xx| 500 | GET /admin/index.php/configure/advanced/system-information/?_token=xxxxxxxxxxxxxxxxxxxxxxxxx
 HTTP/1.0
php info https://bit.ly/3gkmZlZ
-- | -- | -- | -- | --

2020-05-21 18:18:57	Warning	2.139.241.62		AH01071: Got error 'PHP message: PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/vhosts/store.com/httpdocs/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/vhosts/store.com/httpdocs/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665', referer: https://store.com/admin/index.php?controller=AdminOrders&token=abd5a0008db17295c3ec02737a4722d0				Apache error
2020-05-21 22:34:05	Error	2.138.146.51		AH01068: Got bogus version 32, referer: https://store.com/				Apache error
2020-05-21 22:34:05	Error	2.138.146.51		(22)Invalid argument: AH01075: Error dispatching request to :, referer: https://store.com/				Apache error
2020-05-21 22:34:06	Error	2.138.146.51		AH01068: Got bogus version 71, referer: https://store.com/				Apache error
2020-05-21 22:34:06	Error	2.138.146.51		(22)Invalid argument: AH01075: Error dispatching request to :, referer: https://store.com/				Apache error
2020-05-22 04:58:25	Error	91.216.107.228		9944#0: *6771 open() "/var/www/vhosts/default/htdocs/.well-known/acme-challenge/b7e82bab491f2a3c28f23798451dcf15.txt" failed (2: No such file or directory)				nginx error
2020-05-22 11:09:39	Error	94.130.237.173		9944#0: *7457 open() "/var/www/vhosts/store.com/httpdocs/sitemap.xml" failed (2: No such file or directory)				nginx error
2020-05-22 11:09:45	Error	94.130.237.173		9944#0: *7462 open() "/var/www/vhosts/store.com/httpdocs/sitemap.xml" failed (2: No such file or directory)				nginx error
2020-05-22 14:47:09	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: https://store.com/admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg				Apache error
2020-05-22 14:47:33	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: https://store.com/admin/index.php/configure/advanced/performance/?_token=lnd0KI9Ndz5KhRPx4WE4QLjElTL5pz-7Kxt4ssw-szg				Apache error
2020-05-22 14:47:35	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6				Apache error
2020-05-22 14:50:19	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :				Apache error
2020-05-22 15:15:04	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6				Apache error
2020-05-22 15:15:15	Error	41.249.240.238		(70007)The timeout specified has expired: AH01075: Error dispatching request to :				Apache error
2020-05-22 16:13:03	Warning	41.249.240.238		(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6				Apache error
2020-05-22 16:13:03	Error	41.249.240.238		End of script output before headers: index.php, referer: https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6				Apache error
2020-05-22 16:19:10	Warning	41.249.240.238		(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6				Apache error
2020-05-22 16:19:10	Error	41.249.240.238		End of script output before headers: index.php, referer: https://store.com/admin/index.php?controller=AdminDashboard&token=bcf1e8baf6692344d2c10aadab4070f6

**Comment by go-sudo** [comment] 2020-05-23 11:55
HI @florine2623 
Any update please

**Comment by go-sudo** [comment] 2020-05-24 10:23
HI @khouloudbelguith any update please

**Comment by elboletaire** [comment] 2020-05-24 15:39
Are you sure you properly downgraded and there's no other file affecting your current php version? Because that warning you shared above is a PHP 7.3 one. It does not happen if you have PHP 7.2, which makes me think that you haven't properly downgraded PHP 7.3 to 7.2.

**Comment by florine2623** [comment] 2020-05-25 08:05
@go-sudo ,
Could you make sure PHP version used is 7.2 ?

@elboletaire is right !

Thanks!

**Comment by go-sudo** [comment] 2020-05-27 20:49
Hi @florine2623 I added the php info with my previous answer https://bit.ly/3gkmZlZ

**Comment by florine2623** [comment] 2020-05-28 08:32
Ok, thanks !
When you go back to your Information Page, what error do you have now ?

**Comment by matks** [comment] 2020-05-28 08:37
Multiple people noticed indeed that Information or Performance BO pages are slow lately

**Comment by prestascott** [comment] 2020-06-24 08:17
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Closed as completed** 2020-06-24 08:17 UTC
Labels: BO, Information, Performance, No change required, 1.7.6.2
