### ISSUE TITLE
Checkout not possible with Order amount 0

### ISSUE THREAD

**Issue by ConvarDeutschland** [PrestaShop/PrestaShop#15078] opened 2019-08-12 13:27 UTC
Checkout is not possible in prestashop 1.7.6.0 if order amount is null (0). In the payment section the text "No payment needed for this order" is shown but on the bottom of the page the button "Order with an obligation to pay" is deactivated and the error message "Please make sure you've chosen a payment method and accepted the terms and conditions." is displayed. In 1.6 this was working.
![Order_0_Amount](https://user-images.githubusercontent.com/14978257/62868272-8aabf980-bd15-11e9-8521-f4cbee6e29c3.jpg)

**Comment by marionf** [comment] 2019-08-12 16:10
Hello @ConvarDeutschland 

I can't reproduce the issue with PS 1.7.6.0 & classic theme, as you can see below I validated a free order with success

![capture d'écran_1880](https://user-images.githubusercontent.com/13449658/62879813-3d875200-bd2c-11e9-8720-62894775af91.png)

![capture d'écran_1881](https://user-images.githubusercontent.com/13449658/62879816-3fe9ac00-bd2c-11e9-86a6-af788ef93823.png)

![capture d'écran_1882](https://user-images.githubusercontent.com/13449658/62879823-437d3300-bd2c-11e9-846e-b4f094ab2a0e.png)

On your screenshot it seems you didn't checked the terms & conditions, I guess this why the "Order with an obligation to pay' button is disabled.

**Comment by ConvarDeutschland** [comment] 2019-08-13 07:50
Hello Marionf,
thanks for the help, your are right we had removed the terms checkbox as our lawyer told us that this box is not needed as long as the terms sentance is there(I agree to the terms of service and revocation terms and will adhere to them unconditionally.), and for this reason when cart has an amount of 0 and no payment has to be selected, the error message was displayed. We resolved it by unchecking and checking the terms box over javascript and now it works.

**Comment by marionf** [comment] 2019-08-13 08:05
Thank you for your answer @ConvarDeutschland 
I close this issue

**Closed as completed by marionf** 2019-08-13 08:05 UTC
Labels: No change required
