### ISSUE TITLE
Combinations never found by combination reference in stocks

### ISSUE THREAD

**Issue by Ybeske** [PrestaShop/PrestaShop#12171] opened 2019-01-16 11:10 UTC
***situation***
I created a combination product for a red balloon. Every combination has another size. The general product information tab has a product reference field with filled in for example "redballoon".
All combinations 5", 12" and 18" have filled in in the combination product reference field of every balloon respectively: redballoon05, redballoon12 and redballoon18.

***bug***
When I search in "Stocks" to organize my stock movements, The combinations are never found by the combination product reference.
However, When I search by redballoon, I got my 3 results.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-01-16 12:52
Hi @Ybeske 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9727
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-01-16 12:52
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9727

**Closed as completed by khouloudbelguith** 2019-01-16 12:52 UTC
Labels: Duplicate
