### ISSUE TITLE
Some products' thumbnails don't appear in dropdown when creating a new pack of products

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13420] opened 2019-04-16 08:21 UTC
**Describe the bug**
In Catalog>Products>Add a new **pack of products**, when searching for products to add to the pack, some product's thumbnails don't appear in the dropdown displaying the list of products.
A broken image icon is displayed instead of the thumbnail.

**To Reproduce**
1. Go to Catalog>Products>Add a new product, select pack of products
2. Search for a product to add, if you have the demo products type "humm"
3. In the dropdown list, scroll down to sweaters

**Screenshots**
![Capture d’écran 2019-04-16 à 10 12 10](https://user-images.githubusercontent.com/47456895/56193398-d208ce80-6030-11e9-8e47-145413efc541.png)

**Additionnal information**
The source of the problem seems to be the URLs of some products' images.

PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by marionf** [comment] 2019-04-16 08:42
Duplicate of #9976

**Closed as completed by marionf** 2019-04-16 08:42 UTC
Labels: Bug, Trivial, Duplicate, 1.7.5.0, Front-end, 1.7.5.1
