### ISSUE TITLE
Link List translate save success but data not change 

### ISSUE THREAD

**Issue by 121213tjfgalfjaf** [PrestaShop/PrestaShop#27522] opened 2022-01-29 02:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![image](https://user-images.githubusercontent.com/5094727/151644585-37663cc2-6a3d-4958-849c-f9146be61e65.png)
![image](https://user-images.githubusercontent.com/5094727/151644593-80bf4eac-6177-45bc-8f5d-66497750bd94.png)

### Expected behavior

the translation could be saved correctly

### Steps to reproduce

1、Design
2、Link List

### PrestaShop version(s) where the bug happened

1.7.8.2 1.7.8.3

**Comment by hibatallahAouadni** [comment] 2022-01-30 22:54
Hello @121213tjfgalfjaf 

Could you please provide the linklist module version and your PHP version 🙏 
It seems your issue similar to this one #24010 

Please check and feedback.
Thanks!

**Comment by 121213tjfgalfjaf** [comment] 2022-02-06 16:37
> Hello @121213tjfgalfjaf
> 
> Could you please provide the linklist module version and your PHP version 🙏 It seems your issue similar to this one #24010
> 
> Please check and feedback. Thanks!

The PHP version is v7.3.32  and the Link list module version is v5.0.4

**Comment by florine2623** [comment] 2022-02-09 11:03
Hello @121213tjfgalfjaf ,

I can't reproduce your issue with PS 1.7.8.2, PHP 7.3 and ps_linklist v5.0.4.
Please check my screen record : 

https://user-images.githubusercontent.com/16019289/153185537-c1a6c6e3-0b84-4e4c-a7a0-7ed201117037.mov

As your issue can't be reproduce, i will close it.
Thanks!

**Closed as completed by florine2623** 2022-02-09 11:03 UTC
Labels: Bug, BO, Link widget, Linklist, Invalid, Module

**Comment by 121213tjfgalfjaf** [comment] 2022-02-24 01:53
the chinese simplified and traditional still can't save the translation
