### ISSUE TITLE
Duplicate and triple call to CartPresenter::present()

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#31299] opened 2023-02-09 15:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When on cart page, `CartPresenter::present()` is called the first time here: https://github.com/PrestaShop/PrestaShop/blob/c130e2d2e0a2bd72d0dd1800114e05c0dff9e22d/classes/controller/FrontController.php#L491
then a second time: https://github.com/PrestaShop/PrestaShop/blob/c130e2d2e0a2bd72d0dd1800114e05c0dff9e22d/classes/controller/FrontController.php#L496 calls `this->getTemplateVarPage()` which is https://github.com/PrestaShop/PrestaShop/blob/c130e2d2e0a2bd72d0dd1800114e05c0dff9e22d/controllers/front/CartController.php#L551-L562
And a third time here:
https://github.com/PrestaShop/ps_shoppingcart/blob/58eb1f7a0fd481976cff427e57ebc6c0b2d8e06e/ps_shoppingcart.php#L96

### Expected behavior

We should call this function only once. There is no reason to call it multiple times.

### Steps to reproduce

1. Add after this line https://github.com/PrestaShop/PrestaShop/blob/674d6128c852a61ff3803206051d2bc29288871f/src/Adapter/Presenter/Cart/CartPresenter.php#L317 : `debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);`
2. Navigate to the cart page of the shop
3. Note the three backtraces displaying

### PrestaShop version(s) where the bug happened

8.0.1, dev

### PHP version(s) where the bug happened

any

### If your bug is related to a module, specify its name and its version

ps_shoppingcart dev

**Comment by Hlavtox** [comment] 2023-02-09 15:48
It was 4 times originally. 🤣 

@PululuK fixed it in the initContent here - https://github.com/PrestaShop/PrestaShop/commit/714128057c17a36a14402353b184b6efdc41149f

**Comment by hibatallahAouadni** [comment] 2023-02-13 21:10
Hello @Hlavtox 

If the issue is fixed by this PR #27227 which is merged in 8.0.0, why @lmeyer1 still encounter the same issue with 8.0.1?
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment] 2023-02-13 21:49
@hibatallahAouadni Because 4 calls - 1 call = 3 calls left :-)

**Closed as completed** 2023-03-30 14:24 UTC
Labels: Bug, CO, Fixed, Shopping carts FO, PR available, Verified, 1.7.8.8
