### ISSUE TITLE
 Grey lines on generated images with white background

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20900] opened 2020-09-08 14:54 UTC
#### Describe the bug

GD library that Prestashop is using to generate it's thumbnails is making strange artifacts and grey lines on images. It's very irritating on images with white background.

#### Steps to Reproduce
1. Set your Prestashop image settings to standard - JPG and 85-90% quality.
2. Make a product. Upload any image with white background.
3. Go to FO and view it's thumbnail in product list and on product page.
4. You will see grey artefacts on the background.

It's not visible on cheaper displays - it's visible on my Dell P-series display, Macbooks, iPhones etc.

#### Images
View them here:
[http://www.trendo.cz/test_1.jpg](http://www.trendo.cz/test_1.jpg)
Darker version if you don't see it: [http://www.trendo.cz/test_1_darker.jpg](http://www.trendo.cz/test_1_darker.jpg)

#### How we can solve this
This problem can be solved by using another graphics toolkit available in PHP - Imagick.

Advantages:
- No visual artifacts
- Better image quality with the same compression
- Lower file size
- About the same speed
- Lower code complexity (no calculating the center of the image etc.)

See my test here:
[http://www.trendo.cz/imageTest.php](http://www.trendo.cz/imageTest.php)

#### Additional information
* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-09-08 15:17
Hi @Hlavtox,

I did not manage to reproduce the issue with PS1.7.6.7.
![image](https://user-images.githubusercontent.com/16067358/92495343-1634da00-f1f7-11ea-8cb7-6621e337d548.png)
I used iPhone11.
Could you please try with this image if you have some issues?
![image](https://user-images.githubusercontent.com/16067358/92495447-32d11200-f1f7-11ea-9f7a-6ac091bab2a3.png)

Thanks!

**Comment by Hlavtox** [comment] 2020-09-08 15:26
@khouloudbelguith I see it on your screenshot. 😄

![92495343-1634da00-f1f7-11ea-8cb7-6621e337d548](https://user-images.githubusercontent.com/6097524/92496321-48930700-f1f8-11ea-812e-39d126d37490.png)

**Comment by PierreRambaud** [comment] 2020-09-08 15:27
Nice catch @Hlavtox

**Comment by ngodefroy** [comment] 2020-09-08 15:39
Hello @Hlavtox !
I am using a macbook with LG display, I wasn't able to reproduce it :s
<img width="1379" alt="Capture d’écran 2020-09-08 à 17 37 45" src="https://user-images.githubusercontent.com/69145330/92497720-023ea780-f1fa-11ea-8518-bcebe441d604.png">

**Comment by Hlavtox** [comment] 2020-09-08 15:43
@ngodefroy Not looking close enough.

If you don't see it, open Photoshop or GIMP and replace #fefefe with red and you get this.

<img width="1379" alt="replaced" src="https://user-images.githubusercontent.com/6097524/92498217-a6c0e980-f1fa-11ea-8931-1b5057467fb5.png">

_________

@PierreRambaud It's gonna be fun reproducing this 😄 😄

**Comment by Hlavtox** [comment] 2020-09-08 20:43
@khouloudbelguith @ngodefroy The lines are perfectly visible on iPhone XS or 11 Pro with max brightness.

**Comment by khouloudbelguith** [comment] 2020-09-09 09:35
@Hlavtox, could you please provide me a screenshot about your `Images generation options` settings.

Thanks!

**Comment by eternoendless** [comment] 2020-09-09 10:27
IMO it looks like an issue in the GD library. I found [other people having similar problems](https://stackoverflow.com/questions/43455282/php-gd-resizing-causes-artifacts) and [this open bug in libgd](https://github.com/libgd/libgd/issues/99). I don't think we can do anything about it.

**Comment by Hlavtox** [comment] 2020-09-09 10:50
@eternoendless What if we move to Imagick? It is avaialble on 9/10 (if not all) PHP installs.

**Comment by PierreRambaud** [comment] 2020-09-09 12:07
@Hlavtox We are also able to manage both. If Imagick is available use it, otherwise use the gd library

**Comment by khouloudbelguith** [comment] 2020-09-14 09:45
Hi @PrestaShop/prestashop-core-developers,

We need to close this issue or we can add it to the debug roadmap?

Thanks!

**Comment by PierreRambaud** [comment] 2020-09-14 09:52
I add the label To Do :+1:

**Comment by eternoendless** [comment] 2020-09-22 11:04
> We are also able to manage both. If Imagick is available use it, otherwise use the gd library

@PierreRambaud Unless I'm mistaken, that's not the current behavior. So if it's a feature request, that should be expressed in a new issue. This bug can't and won't be fixed by us.

**Closed as completed by eternoendless** 2020-09-22 11:04 UTC
Labels: Bug, Minor, FO, Image, No change required, 1.7.6.2
