### ISSUE TITLE
When modifying address and cart already created 'No curriers..' in checkout

### ISSUE THREAD

**Issue by SharmPRO** [PrestaShop/PrestaShop#14311] opened 2019-06-20 20:47 UTC
**Describe the bug**
When modifying address and cart already created 'No curriers..' in checkout
If there is a 'disabled' address that is referred into ps_cart_product, then in checkout there are no currier available.

**To Reproduce**
1. Modify address in checkout phase
2. Currier not avalable

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

File: classes/Cart.php 
Line: 2302
...

        $array_address_delivery_is_valid = array();
        foreach ($product_list as &$product) {
            if ((int) $product['id_address_delivery'] != 0) {
                if(!isset($array_address_delivery_is_valid[ $product['id_address_delivery'] ])){
                    $array_address_delivery_is_valid[ $product['id_address_delivery'] ] = 
                        (int)Db::getInstance()->getValue('SELECT active FROM '._DB_PREFIX_.'address WHERE id_address = '.(int)$product['id_address_delivery'].' AND deleted = 0 AND active = 1');
              }
              if ((int)$array_address_delivery_is_valid[ $product['id_address_delivery'] ] === 0){
                    $product['id_address_delivery'] = 0;
              }
        }
...

            if ((int) $product['id_address_delivery'] == 0) {
                $product['id_address_delivery'] = (int) $this->id_address_delivery;
            }

**Comment by khouloudbelguith** [comment] 2019-06-21 08:02
Hi @SharmPRO,

Thanks for your report.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9932
So, I close it.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by khouloudbelguith** [comment] 2019-06-21 08:02
Duplicate of #9932

**Closed as completed by khouloudbelguith** 2019-06-21 08:02 UTC
Labels: Duplicate
