### ISSUE TITLE
ps_legalcompliance overwrite $link variable

### ISSUE THREAD

**Issue by StudioAquilon** [PrestaShop/PrestaShop#19799] opened 2020-06-16 14:45 UTC
**ps_legalcompliance  overwrite $link smarty variable**

ps_legalcompliance/ps_legalcompliance.php
_overwrite_
classes/Link.php

piece of code from ps_legalcompliance.php ( creation of a "smarty" variable named "link" ) :

    public function hookDisplayCheckoutSubtotalDetails($param)
    {
        // Display "under conditions" when the shipping subtotal equals 0
        if ('shipping' === $param['subtotal']['type'] && 0 === $param['subtotal']['amount']) {
            $cms_role_repository = $this->entity_manager->getRepository('CMSRole');
            $cms_page_shipping_and_payment = $cms_role_repository->findOneByName(self::LEGAL_SHIP_PAY);
            $link = $this->context->link->getCMSLink((int)$cms_page_shipping_and_payment->id_cms);

            $this->context->smarty->assign(array('link' => $link));
            return $this->display(__FILE__, 'hookDisplayCartPriceBlock_shipping_details.tpl');
        }
    }

result, the "link" object cannot be used in .tpl on the "basket" page. Third-party modules that use this, doesn't work.

**Comment by florine2623** [comment] 2020-06-17 14:52
Hi @PrestaShop/prestashop-core-developers ,

@StudioAquilon reports the non-usability of Link object in the Cart.tpl.
Do you thing we need to change the code from ps_legalcompliance.php in order in fit third-party modules ?

Thanks!

**Comment by matks** [comment] 2020-06-18 07:41
@StudioAquilon Hi ! So you say that the issue is that https://github.com/PrestaShop/ps_legalcompliance/ assigns a `$link` Smarty variable, so you (as a 3rd party module developer) cannot use it, right ?

And I guess you suggest https://github.com/PrestaShop/ps_legalcompliance/ uses another variable name ?

I don't understand how this is an issue, you can assign whatever variable you want in Smarty ? You can use `$myLink`, `$anotherLink`, any variable name ? You have also the possibility to override the template ?

What is exactly blocking you ? I'm sorry I cant see it

**Comment by StudioAquilon** [comment] 2020-06-18 10:28
Hi,

in the TPL of my module i use the link object method (classes/Link.php, it's a Prestashop class) to get a brand url : 
$link->getmanufacturerLink()

Native modules also use this object ( ps_checkpayment/views/templates/hooks/payment.tpl )
$link->getModuleLink()

I do not generate the link object with my module.

**Comment by kpodemski** [comment] 2020-06-18 11:03
@StudioAquilon @matks 

well, one of 1.7 good practices is to **not** use global context variables like `$link` (see `url` helper in dev docs), tho i'm surprised that core module uses generic variable name like this, especially that it was common to use `$link` in PS 1.6

IMO this code should be deleted and we should have link thanks to `{url}` helper in template :)

**Comment by matks** [comment] 2020-06-18 12:20
Multiple topics clash here 😛 

### ps_legalcompliance should not use variable name `link`

This one is easy to be solved, and indeed following @kpodemski suggestion we could use `{url}` helper.
However doing this will create a Breaking Change 🤔 : any theme using this TPL will fail if we remove `link`.

So the issue in the code is clear, what is unclear is "how to solve it without requiring any theme that use it to update" ?

When you look at it like this it's obvious 😄 :
```
$link = $this->context->link->getCMSLink((int)$cms_page_shipping_and_payment->id_cms);
$this->context->smarty->assign(array('link' => $link));
```

### Since `link` is being defined, we cannot access standard global `link` variable

As @kpodemski there is the `{url}` helper (see https://devdocs.prestashop.com/1.7/development/components/smarty-extensions/#url) that can help you. Does this solve your need ?

Else I think you can retrieve the global object Link by other means 🤔 ? You can assign it to another variable in your hook ?

```
    public function myHook($param)
    {
        $this->context->smarty->assign(array('link' => $this->context->link));
    }
```

I'm not saying this is a good solution, but at least it provides a workaround available immediately. Does this work for you @StudioAquilon ?

**Comment by StudioAquilon** [comment] 2020-06-18 14:42
yes for me it's ok, i can do otherwise. Thank you all.

**Comment by khouloudbelguith** [comment] 2020-10-12 09:53
Hi!

On this github repository there is no software support. This is an open source project.

I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-12 09:53 UTC
Labels: CO, No change required
