### ISSUE TITLE
missing translation in order_conf mail for bankwire payment PS 1.7.7.x

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#24170] opened 2021-04-22 19:20 UTC
#### Describe the bug

Missing translation in order_conf mail for bankwire or check payment.
The additon "(waiting for validation)" after Bankwire Payment in order_conf mail is added since PS 1.7.7.x and was not there before. 

#### Expected behavior

have the opportunity to translate it

#### Steps to Reproduce

1. have Deutsch (German) or Arabic language
2. make an order with bankwire (or check) payment
3. receive mail order_conf
4. See error that translation is missing

**Screenshots**

![image](https://user-images.githubusercontent.com/44971218/115773198-4f9a0e80-a3b0-11eb-85da-95ea7bcfb797.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by florine2623** [comment] 2021-04-23 10:34
Hello @didi-2018 ,

Do you also have the issue in the "Versand" part ?
![Capture d’écran 2021-04-23 à 12 31 47](https://user-images.githubusercontent.com/16019289/115859150-13a68e00-a430-11eb-9eee-68cfdab0142c.png)

Please check and feedback.

**Comment by didi-2018** [comment] 2021-04-23 15:24
@florine2623  I removed the double Payment in the Shipping Section from the Beginning of the new Mail Templates. I found it not neccessary to have it twice.

**Comment by hibatallahAouadni** [comment] 2021-04-28 09:08
Hello @didi-2018 

I was able to reproduce the issue with PrestaShop version 1.7.7.3 with Deutch language and Arabic language. It seems this sentence (waiting for validation) is missing in these files: 

- `app/Resources/translations/de-DE/EmailsBody.de-DE.xlf` for **Deutsch** language  
- `app/Resources/translations/ar-SA/EmailsBody.de-DE.xlf` for **Arabic** language

> The additon "(waiting for validation)" after Bankwire Payment in order_conf mail is added since PS 1.7.7.x and was not there before.

Indeed, it's a regression! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-05-11 09:43
Just discussed with @Julievrz : it seems that this string has not been proofreaded by translators so the translation has not been validated so not sent in packages. We ask proofreading in arabic & german. So the bug will be fixed at this moment.

I define the issue in locked in the meantime.

**Comment by Progi1984** [comment] 2021-05-17 10:04
Translations are now available : 
* https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/ar-SA/EmailsBody.ar-SA.xlf#L5-L9
* https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/de-DE/EmailsBody.de-DE.xlf#L5-L9

@didi-2018 @florine2623 @hibatallahAouadni Could you check it ? Don't forget to remove cache translations (`app/Resources/translations/`).

**Comment by hibatallahAouadni** [comment] 2021-06-02 07:14
Hello @Progi1984 

Yes, it works! (German)

![image](https://user-images.githubusercontent.com/23308427/120436883-c945f480-c37f-11eb-808a-52fe03c23aa7.png)

(Arabic):

![image](https://user-images.githubusercontent.com/23308427/120439481-dadccb80-c382-11eb-8606-4d7f9eb1fe46.png)

Thanks!

**Closed as completed** 2021-06-02 07:14 UTC
Labels: Bug, Minor, CO, Translations, Email, Regression, Fixed, 1.7.7.x, 1.7.7.3
