### ISSUE TITLE
Product quantity not a sum of individual product variations' quantities

### ISSUE THREAD

**Issue by spelagp** [PrestaShop/PrestaShop#21718] opened 2020-11-02 16:56 UTC
#### Describe the bug

When viewing a products in BO catalogue, it shows quantity of 12. When viewing the same product in product editing mode, there are two combinations to the product. One has quantity -1, the other has 0.  

I have two problems: 
First: -1 + 0 is not 12.
Second: Selling of the out ouf stock items is disabled. How could quantity be -1 if the purchase cannot be made once product quantity hits 0? 

#### Expected behavior

I would expect two things: 
First: that the sum of the product varinations' quantities would equal the product's quantity in list view.
Second: If the selling of the out of stock products is disabled, there should be not possibility for the product's quantity to go below 0.

#### Steps to Reproduce

1. Go to Catalog, search for the affected product.
2. Look at and note the product quantity.
3. Open the product for editing.
4. Open the Combinations tab.
5. Look at and note quantities for individual combinations. They do not sum up correctly. 
6. Look at the "Availability preferences". They are set to "Use default behavior (Deny orders)". Nontheless, the quantity of one of the combinations is -1 (below 0).

**Screenshots**
![image](https://user-images.githubusercontent.com/73843367/97895514-2a4b1280-1d34-11eb-83d9-661f2546341b.png)
![image](https://user-images.githubusercontent.com/73843367/97895647-5cf50b00-1d34-11eb-86b4-9bfd5c8164b4.png)
![image](https://user-images.githubusercontent.com/73843367/97895704-6aaa9080-1d34-11eb-94a2-26e7b83913da.png)

#### Additional information
* PrestaShop version: 1.7.6.7
* PHP version: 7.2.24-0ubuntu0.18.04.6

Thank you very much for your help in advance.

Kind regards.
Špela

**Comment by kpodemski** [comment] 2020-11-02 18:28
Hello,

this difference is very big, do you have any import mechanism in your shop? any mechanism to sync product stocks, import from wholesaler inventory etc?

**Comment by spelagp** [comment] 2020-11-02 21:12
Hello,

we are using
Product Catalog (CSV, Excel) Import
v5.3.4 - od MyPrestaModules module on several of our stores and have never
encountered this problem before.

Špela

**Comment by hibatallahAouadni** [comment] 2020-11-03 08:45
Hello @spelagp 

> that the sum of the product varinations' quantities would equal the product's quantity in list view.

I didn't manage to reproduce this problem with PS1.7.6.7.
 It seems that your issue is not a PrestaShop core bug but most likely a module problem. Please contact support team on [Addons](https://addons.prestashop.com/en/data-import-export/19091-product-catalog-csv-excel-import.html)

> If the selling of the out of stock products is disabled, there should be not possibility for the product's quantity to go below 0.

This bug happens when two customers check out concurrently for the same product, we are awre of it and it seems simular to this one #18700.
Could you please check and feedback.

Thanks!

**Comment by spelagp** [comment] 2020-11-03 09:41
Hello again,

thank you very much for the link to ticket #18700, we will certainly look
into buying the suggested addon. It looks perfect.

Regarding the import module I don't believe it is a module problem, since
even if we modify the stock manually (e.g. change the stock of one the
combinations from -1 to 0), the sum of both becomes 13 (before 12). So the
basic calculation is wrong. Can this be caused by a module which is not
used at the time of manual correction? Can some module action permanently
change something in the database that causes permanent calculation error?

Z lepimi pozdravi / Best regards,

Špela Golob Peterlin


Naveza d.o.o., Ščita 9, SI-1315 Velike Lašče, Slovenija
P.E. Ljubljana, Letališka 33, 1000 Ljubljana

Modra številka: 080 23 03
Tel./faks: +386 1 787 3025
E-mail: spela.golob@naveza.com
WEB: www.naveza.com

VAT ID: SI37483188
------------------------------------------------------------
-------------------------
<https://www.odoo.com/partners/naveza-d-o-o-2138006>
Naveza d.o.o. je Ready partner
https://www.odoo.com/partners/naveza-d-o-o-2138006

**Comment by hibatallahAouadni** [comment] 2020-11-03 10:09
Hi @spelagp 

I attached the screen record in the link below:
https://drive.google.com/file/d/1LTY3z99RL_CWTMxO2c1QnUPeX7LQAn0E/view

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment] 2020-11-23 10:55
Hello @spelagp ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-23 10:55 UTC
Labels: Bug, BO, Order, No change required, 1.7.6.7
