### ISSUE TITLE
Multistore header leaks sensitive information between team members of different shops.

### ISSUE THREAD

**Issue by fivegit** [PrestaShop/PrestaShop#27705] opened 2022-02-16 20:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Employee with minimal permissions can see shop information from other multi-stores

go to 1:50 
https://www.youtube.com/watch?v=UtOdXzM1Tnk

### Expected behavior

Employees/team members should only see the assigned shop or shops and not be able to search  through all multistores

<img width="1834" alt="20220216211002_msedge_RAVzeRGreJ" src="https://user-images.githubusercontent.com/99838584/154347616-e95d7690-f37a-4dba-9b2f-6e1120ef51d3.png">
 

### Steps to reproduce

create multistore
create team member "example"
Assign to 1 multistore 
<img width="1516" alt="20220216211148_firefox_LKguJcS21D" src="https://user-images.githubusercontent.com/99838584/154348755-5f7c531c-f475-4ce7-9f0b-71a947992abc.png">
create profile "test"
customize profile "test" with only product permissions
assign team member "example" profile "test"
sign into multistore backoffice with user "example"
click on the multistore-header dropdown 
see all multistores 

SEE VIDEO
Employee with minimal permissions can see shop information from other multi-stores
go to 1:50 

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.25

**Comment by hibatallahAouadni** [comment] 2022-02-16 22:25
Hello @fivegit 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27377. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-02-16 22:25
Duplicate of #27377

**Closed as completed by hibatallahAouadni** 2022-02-16 22:25 UTC
Labels: Bug, Duplicate, Invalid
