### ISSUE TITLE
Specific price tax included is applyed instead of tax excluded

### ISSUE THREAD

**Issue by romain-le-mercier** [PrestaShop/PrestaShop#20069] opened 2020-07-06 10:54 UTC
Customer from other countries pay products tax ecluded.
On my products I added specific price depending on the quantity for example -5€ tax incl for qty >=5.

My product is 10€ tax excl, 12€ tax incl.
The customer order 5 products and pay 5€ per product (10€ tax excl - 5€ tax **incl**) instead of 5.833.

* PrestaShop version: 1.7.6.5
* PHP version: 7.3

**Comment by sarahdib** [comment] 2020-07-06 14:20
Hello @romain-le-mercier ,

We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #15835.

To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you!

**Comment by sarahdib** [comment] 2020-07-06 14:21
duplicate of #15835

**Closed as completed by sarahdib** 2020-07-06 14:20 UTC
