### ISSUE TITLE
ccc_up hidden field remove in js in admin performance

### ISSUE THREAD

**Issue by agnesdennetiere** [PrestaShop/PrestaShop#11724] opened 2018-12-11 17:00 UTC
Hello,

I was trying to save my configuration in advanced parameters > performance (for example: Smart cache for CSS)
but when I submitted the form, nothing was saved.
So I looked into the code and realized that these fields are saved only when the ccc_up field is present.
It is in the source code however, it is removed in javascript, and I have no idea why.
Could you tell me what causes this?

Thank you very much

**Additionnal information**
PrestaShop version: 1.6.1.4, 1.6.1.23
PHP version: 5.6, 7.1

**Comment by khouloudbelguith** [comment] 2018-12-12 09:12
Hi @agnesdennetiere,

Thanks for your report.
So, in your BO => Advanced Parameters => Performance, you enable all the CCC (COMBINE, COMPRESS AND CACHE) & you clicked on save, but this configuration is not saved?
![image](https://user-images.githubusercontent.com/16067358/49858895-70bcbe80-fdf6-11e8-93f2-8801c15a43c1.png)
Thanks!

**Comment by agnesdennetiere** [comment] 2018-12-12 09:22
Hello,

yes exactly, and it is not saved because the input hidden "ccc_up" is removed in javascript (I don't know where in the code it is done but I know it is removed in js since when i deactivate js on my browser, it is not removed)

and in AdminPerformanceController, there is this code line 749
`if ((bool)Tools::getValue('ccc_up')) {`

**Comment by khouloudbelguith** [comment] 2018-12-12 09:28
@agnesdennetiere, in my case, I did not manage to reproduce the issue with PS1.6.1.21.
I attached a video record
https://drive.google.com/file/d/1YIgoYPlCdToElh-73Q3zmAJ_X4joeU2E/view
@agnesdennetiere, did you make any changes in the core of PrestaShop?

**Comment by agnesdennetiere** [comment] 2018-12-20 13:13
hello,

no we did not... and we have this problem on several websites (and different versions).
Could you just tell me, if you know, where (in which file) it could be remove in js? I searched in the projects but could not find it...
Maybe I could patch it myself.

**Comment by khouloudbelguith** [comment] 2018-12-20 13:19
Hi @agnesdennetiere,

You need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-25 17:21
Hi @agnesdennetiere,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-25 17:21 UTC
Labels: BO, Performance, No change required
