### ISSUE TITLE
Prestashop 8.1 - in the customer detail, all the discounts that have the "Highlight" option active are shown

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34592] opened 2023-11-16 10:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've found this bug in prestashop 8.1

if I go in a customer details page, it is possible to see all vouchers that have the "Highlight" option active, even if they have not been used by the customer, even if they have expired, they just need to have that option enabled. in this way it is not possible to understand which discounts the customer has used. this problem is not present on prestashop 1.7

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/53259afe-8876-4468-b3e0-33868a702ab8)
![2](https://github.com/PrestaShop/PrestaShop/assets/653230/6a53d862-4eab-4020-b9d3-c671232f8e50)
![3](https://github.com/PrestaShop/PrestaShop/assets/653230/43fadbdf-bd8f-47fc-bb6d-ac28971da3bc)
![4](https://github.com/PrestaShop/PrestaShop/assets/653230/630aaba8-e7ba-4c70-a89d-b0b6db33ac97)

to reproduce this problem just create a new voucher and activate the "Highlight" option

### Steps to reproduce

1. go to catalog - discounts
2. create a new voucher with active the option "Highlight"
3. go to a customer to see his details
4. in the voucher section you will see this new voucher

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-11-16 11:37
Hello @maofree ,

I have the same behavior with PS 1.7.8 and PS 8.1.

In both cases, the voucher with Highlight code is displayed in the customer details page.
Whether the discount has been used or not, used by the customer or another one, not available anymore, it is displayed in all customer details page.

If the voucher has been used, it will be displayed 0 in Qty available column :
<img width="611" alt="Screenshot 2023-11-16 at 12 37 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1930f708-72f6-49ae-8640-110407ae6da4">


Am I missing something ?

**Comment by Maofree** [comment] 2023-11-16 11:40
Hi @florine2623 
I get the same behavior
Yes, the discount coupons that have that option active are shown in the discounts of all customers and even if they are deactivated or with zero quantities

**Comment by florine2623** [comment] 2023-11-16 11:43
So where is the issue ? I am not sure I understand.

Do you mean you want to change the behavior and propose a feature request ?

**Comment by Maofree** [comment] 2023-11-16 11:45
being on a customer page, the discounts section must show the discounts used by the customer, the same thing happens for orders, carts, addresses, emails

What would be the point of showing discounts not used by the customer?

**Comment by florine2623** [comment] 2023-11-16 13:30
Let's ask for the PM ^^

@PrestaShop/product-council 
What do you think about that ?
Showing only the used Discounts in the Customer details page instead of showing all the discount available or not.

**Comment by Maofree** [comment] 2023-11-16 13:33
if the shopkeeper goes to check a customer's details, what would be the point of seeing all the active and highlighted discounts? could go in catalog - discounts to see them

in fact in this section is write so

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/4cba2dfa-b1bd-4859-b20f-0c1e624e3cba)

therefore they should be the ones used by the customer

**Comment by Hlavtox** [comment] 2023-11-16 13:34
I agree with @maofree, I think it should display only discounts FOR THAT SPECIFIC CUSTOMER. Highlighted or not, doesn't matter - highlight option controls the front office behavior. Also, both used and not used should be there, so the merchant knows.

Ping @kpodemski @MatShir to confirm.

**Comment by MatShir** [comment] 2023-11-17 15:50
I could see some use cases to have view for actives discounts (share again lost discount to the customer) and inactive discount (see what discount he used). But I agree that the highlight can pollute the list a lot. We should filter only discount specific to the customer (highlighted or not). A discount for a specific customer can be highlighted in the cart, no ?

**Comment by Hlavtox** [comment] 2023-11-17 15:57
We should just revert https://github.com/PrestaShop/PrestaShop/pull/22518 because not only it broke the logic, you can't control it with the Highlight option.

**Comment by venditdevs** [comment] 2023-11-21 05:22
This changed between 1.7.8.8 and 8.1.2, we've updated one of our stores two weeks ago and this exact problem is also present there, and was not present in 1.7.8.8. This customer (show owner) uses a lot of discount vouchers (600+) and a lot of them are now in de customer bo page which misleads the shop owner.

**Comment by RosaBenouamer** [comment] 2023-11-21 15:10
I reproduce the bug maofree is talking about.

- in 1.7.8, when a hightlight voucher is created, it is not added to customers unless it has been created specifically for a user.

If a user uses the voucher, it appears in all customers.

- in 8.X, when a hightlight voucher is created, it is added to all customers, whether or not there is a restriction on the user.

This seems to be a regression.

**Comment by Hlavtox** [comment] 2023-11-21 15:58
@RosaBenouamer The same regression is on front office, customer zone shows all vouchers even if highlight is not enabled.

**Comment by RosaBenouamer** [comment] 2023-11-22 15:27
Don't have the issue in FO @Hlavtox 

https://github.com/PrestaShop/PrestaShop/assets/124665010/f8ed8e3e-a986-46aa-8b18-910d59f669e3

**Comment by Hlavtox** [comment] 2023-11-22 15:53
It concerns the vouchers without highlight option enabled and no code.

### 1.7.6
![Snímek obrazovky 2023-11-22 165221](https://github.com/PrestaShop/PrestaShop/assets/6097524/d248ecf6-c59a-4fcf-8c63-e9835245c7ef)

### 8.1.2
![sn__mek_obrazovky_2023-10-31_143703](https://github.com/PrestaShop/PrestaShop/assets/6097524/0c0302b7-8350-4641-9298-9680936360e2)

**Comment by RosaBenouamer** [comment] 2023-11-23 10:15
Sorry I don't reproduce the issue in FO but perhaps better to create a specific one for FO to not pollute this one (BO) with which I share your opinion :-)

**Comment by Maofree** [comment] 2023-11-24 19:45
Hi
I think there are some other issues with vouchers, yesterday a customer alert me that an order is done with a disabled voucher an order has been placed. Today another customer alert me about the same problem with a disabled voucher. Both use ps 8.1.2
the problem is that I cannot reproduce them, so I don't know if to create another topic to report this problem if you cannot reproduce them.
the two vouchers have different settings, I can't find a connection, yet they placed orders with deactivated discount coupons

**Comment by Hlavtox** [comment] 2023-11-24 19:47
@maofree Yeah that's a known issue. If you have the voucher in cart, you can use it, no matter if it expires or it gets disabled

**Comment by Maofree** [comment] 2023-11-24 19:49
ok thanks
I didn't know about this problem

**Comment by ocio87** [comment] 2023-11-28 22:15
Hello @Hlavtox ,


Is there any possible correction?

Something similar happened to me.

I enabled a coupon with 15% that was valid from November 24 to 26 and I enabled a second coupon for November 27, also for 15%.

Customers who created a cart between November 24 and 26 associated the first discount which expired on November 26 and on the 27th they returned to the cart and added the new coupon so they had a total discount of 30% due to this known error. I was unaware that the cart did not recheck the validity date of the coupons before confirming the order.

**Comment by RosaBenouamer** [comment] 2023-11-29 10:03
The related issue https://github.com/PrestaShop/PrestaShop/issues/26235

**Comment by RosaBenouamer** [comment] 2023-11-29 10:54
> I reproduce the bug maofree is talking about.
> 
> * in 1.7.8, when a hightlight voucher is created, it is not added to customers unless it has been created specifically for a user.
> 
> If a user uses the voucher, it appears in all customers.
> 
> * in 8.X, when a hightlight voucher is created, it is added to all customers, whether or not there is a restriction on the user.
> 
> This seems to be a regression.

 Correction
 * in 1.7.8, when a hightlight voucher is created, it is not added to customers 
 
 If a user uses the voucher, it appears in all customers.
 
 * in 8.X, when a hightlight voucher is created, it is added to all customers, whether or not there is a restriction on the user.
 

with video
1.7.8
BO :
without specific customer :
https://github.com/PrestaShop/PrestaShop/assets/124665010/a192b347-7e7d-40ad-8162-1773023e2023

with specific customer :
https://github.com/PrestaShop/PrestaShop/assets/124665010/3156a031-e199-41a3-9976-82605e5ad001


8.1.2

BO :
without specific customer :
https://github.com/PrestaShop/PrestaShop/assets/124665010/a3d5e66e-f03e-46be-9241-237dedd2d929

with specific customer :
same comportement is added

**Comment by Hlavtox** [comment] 2024-02-25 17:16
@maofree @RosaBenouamer @ocio87 @MatShir Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/35464

**Comment by Hlavtox** [comment] 2024-02-27 17:28
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35464

**Closed as completed by Hlavtox** 2024-02-27 17:28 UTC
Labels: Bug, Minor, BO, Customer, Discounts, Topwatchers, Ready, PR available, 8.1.x
