### ISSUE TITLE
Bug Search module Japanese language

### ISSUE THREAD

**Issue by gregthai** [PrestaShop/PrestaShop#12352] opened 2019-01-29 16:55 UTC
Hi everyone,

The search module of the Japanese version of my website does not work, while everything works fine for French and English.

Can someone help me :)

**To Reproduce**
1. Go to 'www.yosaso.com'
2. Choose japanese language 
3. Try searching this product for example "お茶 セット" ("Sushi Start - 1kg" in english)
4. See error... :(

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: N7.1.2

**Comment by khouloudbelguith** [comment] 2019-01-29 17:22
Hi @gregthai,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1Fai7lxqvxtyvsOTxYgqUk6exFuB496qb/view
Thanks to check & feedback.

**Comment by gregthai** [comment] 2019-01-29 17:45
Thank you for your answer, but my PS is 1.7.4.2...
I'm looking for a solution to fix this bug in my version. I'm a little chilly about updating PS...

**Comment by khouloudbelguith** [comment] 2019-01-30 09:10
Hi @gregthai,

No, it is OK, I tried with PS1.7.4.2 & the search is working.
In your BO => Shop Parameters => Search page => click on "Re-build the entire index" link, check & feedback.
Thanks!

**Comment by gregthai** [comment] 2019-01-30 10:01
I did it already. Not working :(

**Comment by khouloudbelguith** [comment] 2019-01-30 10:07
@gregthai, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by gregthai** [comment] 2019-01-30 14:16
Here more info :)
Version du logiciel serveur : Apache/2.2.22 (Debian)
Version de PHP : 7.1.2
memory limit : 128M
Version de MySQL : 5.5.44-0+deb7u1
Temps maximal d'exécution : 30

There is no Php, apache or javascript error logs associated with JA translate... excepted this one :

[Wed Jan 30 11:02:29 2019] [error] [client 555.555.55.55] FastCGI: server "/var/www/clients/client3/web111/cgi-bin/php5-fcgi-*-443-epicerie-alimentation-japonaise.com" stderr: PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/var/www/clients/client3/web111/web/themes/at_junior/modules/index.php/translations/ja.php) is not within the allowed path(s): (/var/www/clients/client3/web111/web:/var/www/clients/client3/web111/private:/var/www/clients/client3/web111/tmp:/var/www/epicerie-alimentation-japonaise.com/web:/srv/www/epicerie-alimentation-japonaise.com/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin) in /var/www/clients/client3/web111/web/classes/Language.php on line 394, referer: https://www.epicerie-alimentation-japonaise.com/admin1234/index.php?controller=AdminLanguages&token=numbersblablabla:)

3 more things:
1 - Would it be useful to empty the tables "ps_search_index" and "ps_search_word" in the DB before re-indexing.
2 - I have a product named "BUTTERFLY - 蝶 々 箸 置 き - 5 色 セ ッ ト" in Japanese. I noticed that the search works by writing "BUTTERFLY" in the search engine in Japanese. Would not it be a question of non-Latin characters in the research module? ...
3 - I added "max_input_vars = 2786" in the php.ini, but nothing has changed ...

Thanks for your help

**Comment by khouloudbelguith** [comment] 2019-01-30 15:16
Hi @gregthai,

Did you use the default templet provided by PrestaShop?
Thanks!

**Comment by gregthai** [comment] 2019-01-30 15:51
No, i use a different template (from Leo Theme)
I've already asked the dev of the template about this problem. I made him access to FTP and administration. 
Here is his answer : 
"After verification, this is probably due to a bug Prestashop, we checked the default theme of Prestashop and it was not possible to search in Japanese." :(

**Comment by khouloudbelguith** [comment] 2019-01-30 16:04
I tried with PS1.7.4.2 & PS1.7.5.0 with the default theme provided by PrestaShop & it is OK.
I attached a video record.
https://drive.google.com/file/d/1wKMx6fBWd7Aw9FHPQbSRlf1flRBEfjD9/view
THanks!

**Comment by gregthai** [comment] 2019-01-30 16:31
Ok...

So, is there anything else i could try...

**Comment by khouloudbelguith** [comment] 2019-01-30 16:34
@gregthai, did you installed your shop with Japanese language or did you import this language from BO?
Thanks!

**Comment by gregthai** [comment] 2019-01-30 16:55
Installed in french then imported JAP from BO

**Comment by khouloudbelguith** [comment] 2019-01-30 17:16
@gregthai, have you tried to contact your host about this issue` [Wed Jan 30 11:02:29 2019] [error] [client 555.555.55.55] FastCGI: server "/var/www/clients/client3/web111/cgi-bin/php5-fcgi-*-443-epicerie-alimentation-japonaise.com" stderr: PHP message: PHP Warning: file_exists(): open_basedir restriction in effect. ` ?
Thanks to check with them & feedback.

**Comment by gregthai** [comment] 2019-02-01 13:25
Hi @khouloudbelguith ,
Would like to tell you that everything works now :)

The solution is so stupid... 
The "minimum word size" parameter was set to 4. I changed it to 3...

Thanx a lot for the time you spent trying to help me.
Have a nice day :)

**Comment by khouloudbelguith** [comment] 2019-02-01 13:28
@gregthai, thanks for your feedback.
Since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-01 13:28 UTC
Labels: Bug, FO, International, No change required, 1.7.4.2
