### ISSUE TITLE
PHP Notice:  Array to string conversion in classes/Hook.php on line 935

### ISSUE THREAD

**Issue by wzzly** [PrestaShop/PrestaShop#24165] opened 2021-04-22 15:28 UTC
#### Describe the bug

Every time I visit the BO order page, I get a PHP notice on the server log with PS 1.7.7.3 and PHP 7.3:

line with --> is line 935 of Hook.php

```
                if ($array_return) {
                    $output[$moduleInstance->name] = $display;
                } else {
                    if (true === $chain) {
                        $output = $display;
                    } else {
-->                        $output .= $display;
                    }
                }
```

```

`[Thu Apr 22 17:21:40.616981 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP Notice:  Array to string conversion in /public_html/classes/Hook.php on line 935\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617042 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP Stack trace:\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617082 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   1. {main}() /public_html/admin/index.php:0\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617117 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   2. AppKernel->handle() /public_html/admin/index.php:82\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617152 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617188 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617224 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   5. PrestaShopBundle\\Controller\\Admin\\Sell\\Order\\OrderController->indexAction() /public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617261 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   6. PrestaShop\\PrestaShop\\Core\\Grid\\GridFactory->getGrid() /public_html/src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:141\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617296 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   7. PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher->dispatchWithParameters() /public_html/src/Core/Grid/GridFactory.php:93\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617331 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   8. PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher->dispatchHook() /public_html/src/Core/Hook/HookDispatcher.php:67\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617371 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP   9. PrestaShop\\PrestaShop\\Adapter\\Hook\\HookDispatcher->dispatchForParameters() /public_html/src/Core/Hook/HookDispatcher.php:58\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617406 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP  10. PrestaShop\\PrestaShop\\Adapter\\Hook\\HookDispatcher->dispatch() /public_html/src/Adapter/Hook/HookDispatcher.php:156\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617442 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP  11. PrestaShop\\PrestaShop\\Adapter\\Hook\\HookDispatcher->doDispatch() /public_html/src/Adapter/Hook/HookDispatcher.php:75\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617476 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP  12. PrestaShop\\PrestaShop\\Adapter\\LegacyHookSubscriber->call_644_170()/public_html/src/Adapter/Hook/HookDispatcher.php:120\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617512 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP  13. PrestaShop\\PrestaShop\\Adapter\\LegacyHookSubscriber->__call() /public_html/src/Adapter/Hook/HookDispatcher.php:120\n, referer: https://www.ha-ma.nl/admin/index.php?controller=AdminLogin&token=58775bed1cb83e5f5799c4adc92f1e9e&redirect=AdminOrders
[Thu Apr 22 17:21:40.617546 2021] [lsapi:warn] [pid 32135:tid 140063304214272] [client 2001:1c03:510a:7100:3825:3caf:320d:b3ee:55890] [host www.ha-ma.nl] Backend log: PHP  14. HookCore::exec() /public_html/src/Adapter/LegacyHookSubscriber.php:292\n, referer: https://www.ha-ma.nl/admin/index.php?`
```

#### Expected behavior

I expect no php notice with php 7.3

#### Steps to Reproduce

1. Go to BO
2. Click on Orders
4. See error in log

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-04-23 07:44
Hello @wzzly ,

I can't reproduce your issue by following your steps.

This is just a notice so it is not a bug.
Also please do not display your admin link to the public for security reasons.

Can you give more detail about this issue ?

**Comment by wzzly** [comment] 2021-04-23 07:50
@florine2623  thanks, I edited the links.
I use the orginal Hook.php without any overrides. That's why I thought it had to be a bug?
It's only a notice, but why am I getting it, if this class is the original class?

**Comment by hibatallahAouadni** [comment] 2021-04-23 10:15
Hello @wzzly 

Could you please provide more infos and steps to reproduce more detailed cause as @florine2623 mentioned above following your steps, we couldn't reproduce your issue.

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-17 07:45
Hello @wzzly,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-17 07:45 UTC
Labels: Bug, BO, Order, No change required, 1.7.7.3

**Comment by wzzly** [comment] 2021-06-02 11:10
Is there a way for me to see where this is coming from? I don't know how to let you reproduce it, as the notices are just there when visiting the orders page. I'm not doing anything else...

**Comment by idnovate** [comment] 2021-09-22 10:27
> Is there a way for me to see where this is coming from? I don't know how to let you reproduce it, as the notices are just there when visiting the orders page. I'm not doing anything else...

Are you using module `roja45quotationspro`?

**Comment by wzzly** [comment] 2021-09-22 13:27
> > Is there a way for me to see where this is coming from? I don't know how to let you reproduce it, as the notices are just there when visiting the orders page. I'm not doing anything else...
> 
> Are you using module `roja45quotationspro`?

@idnovate no we don't use that module

**Comment by kpodemski** [comment] 2021-09-22 13:31
The easiest way, but not the quickest, would be to move modules to some temporary directory to see which is causing this issue. Then you check if the error persists.

The second option would be to do something like:

```
if (is_array($display)) {
    dump($moduleInstance->name);
}
```

just before the line #935

**Comment by idnovate** [comment] 2021-09-22 14:42
@wzzly We just came across the same notice today, and it was because of this module. We debugged it like @kpodemski said.
