### ISSUE TITLE
WYSIWYG - Edit HTML Email Template Stops Working After Save

### ISSUE THREAD

**Issue by hitinder** [PrestaShop/PrestaShop#15743] opened 2019-09-29 21:11 UTC
**Describe the bug**
While editing email if you save it, the WYSIWYG editor won't load; therefore, it is not possible for users to edit emails in the BO after saving an email. None of the emails will work after you save. 

**To Reproduce**
1. Go to 'International  >> Translations >> Modify Translations'
2. Click on 'Email translations'
3. Select  'body' as the content type
4. Select your language
5. Click on 'Modify'
6. Select a template to edit.
7. Click on save without making any changes.

**Screenshots**
In below screenshot **Edit Html Version** is selected but editor won't load.
![image](https://user-images.githubusercontent.com/9841229/65839495-ad6e8d80-e316-11e9-839a-976a657f826a.png)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-09-30 10:57
Hi @hitinder,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
I attached a screen record
[translation.webm.zip](https://github.com/PrestaShop/PrestaShop/files/3670521/translation.webm.zip)
Thanks to check & feedback.

**Comment by hitinder** [comment] 2019-09-30 11:42
Hello @khouloudbelguith,
I am getting "not found" error for the attached file.
Thanks,
Hitin

**Comment by khouloudbelguith** [comment] 2019-09-30 12:59
@hitinder, https://drive.google.com/file/d/1H0-2A6h5SkFTdl20NLDF4jRNxiiiN-Dt/view

Thanks!

**Comment by hitinder** [comment] 2019-10-01 19:46
@khouloudbelguith you are correct, it is working. However, it is not working for me when I am editing emails only for **followup** module.
I guess it is something to do with the module emails itself.

**Comment by khouloudbelguith** [comment] 2019-10-02 08:58
@hitinder, it is ok for me also with PS1.7.5.2 & PS1.7.6.1.
https://drive.google.com/file/d/15rFH6PZQemrMDJYdd3N3mHq8TIhMOVJg/view
But we have reproduced another issue previously with the followup module as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9585
But it is different.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-01 07:46
Hi @hitinder,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-01 07:46 UTC
Labels: BO, Translations, Follow up, No change required, 1.7.5.1

**Comment by xlkiller** [comment] 2020-05-23 19:14
Same Probleme only with the last Line Module Translation.

Editor load for all Module Translation but not for the last.

Screenshot: https://ibb.co/tQj2zDp
