### ISSUE TITLE
I can not upload images into products

### ISSUE THREAD

**Issue by AntonioManta** [PrestaShop/PrestaShop#12146] opened 2019-01-14 13:14 UTC
I can not load the images of the products, I return error 500. I checked all the parameters of the permissions, I did check all the settings from the server manager, I did check all the settings of prestashop, I disabled all the modules but the error persists. I'm really in trouble I can not even go back to the previous version because I received orders in the meantime. Can anyone help me?

**Comment by marionf** [comment] 2019-01-14 15:32
Duplicate of #11939

**Closed as completed by marionf** 2019-01-14 15:32 UTC
Labels: Duplicate
