### ISSUE TITLE
Inline assets css not loaded

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#16855] opened 2019-12-18 16:38 UTC
**Describe the bug**
Try to create a new css file, and include inline in theme assets following the dev guide, result in empy content generated in html:

HTML generated:
![image](https://user-images.githubusercontent.com/24798703/71104988-0d116200-21bd-11ea-874d-9fd05aec558f.png)

Asset created:

![image](https://user-images.githubusercontent.com/24798703/71105005-169aca00-21bd-11ea-83fb-1e2622a6c0cf.png)

PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-12-19 07:49
Hi @matteolavaggi,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13872
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-12-19 07:49
Duplicate of #13872

**Closed as completed by khouloudbelguith** 2019-12-19 07:49 UTC
Labels: Duplicate
