### ISSUE TITLE
Admin customer page (list) very slow

### ISSUE THREAD

**Issue by ddevigne** [PrestaShop/PrestaShop#27873] opened 2022-03-10 09:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In our prestashop admin, the customer page (list) is very slow.
It takes 7s to display.
Customer table has 200.000 lines.
No override here.
Prestashop 1.7.6.9
mysql 5.7.37

This is the slow query (5 seconds), according to symfony profiler :

`SELECT c.id_customer, c.firstname, c.lastname, c.email, c.active, c.newsletter, c.optin, c.date_add, gl.name as social_title, s.name as shop_name, c.company, (SELECT SUM(total_paid_real / conversion_rate) FROM ps_orders o WHERE (o.id_customer = c.id_customer) AND (o.id_shop IN (1)) AND (o.valid = 1)) as total_spent, (SELECT con.date_add FROM ps_guest g LEFT JOIN ps_connections con ON con.id_guest = g.id_guest WHERE g.id_customer = c.id_customer ORDER BY con.date_add DESC LIMIT 1) as connect FROM ps_customer c LEFT JOIN ps_gender_lang gl ON c.id_gender = gl.id_gender AND gl.id_lang = 1 LEFT JOIN ps_shop s ON c.id_shop = s.id_shop WHERE (c.deleted = 0) AND (c.id_shop IN (1)) ORDER BY c.id_customer desc LIMIT 50;`

This query is generated in `src/Core/Grid/Query/CustomerQueryBuilder.php`.

This query runs slowy if executed directly in mysql, outside of prestashop context.

If we remove the `left join ps_gender_lang` or if we remove the `order by c.id_customer`, then the query runs very fast (0.0058 seconds).

How can we improve this ? Is this a known issue when customer table has a lot of lines ?

### Expected behavior

faster display

### Steps to reproduce

- display customer listing page

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2.24

**Comment by hibatallahAouadni** [comment] 2022-03-10 14:16
Hello @ddevigne 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25683. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-10 14:16
Duplicate of #25683

**Closed as completed by hibatallahAouadni** 2022-03-10 14:16 UTC
Labels: Bug, Duplicate, Invalid

**Comment by ddevigne** [comment] 2022-03-11 07:51
Hi @hibatallahAouadni,

I'm not sure to understand why it is a duplicate of #25683, the issue seem very different to me... Could you take a second look on it ?
