### ISSUE TITLE
 Total invoice value error

### ISSUE THREAD

**Issue by JorgeNogueiraLFMPro** [PrestaShop/PrestaShop#14699] opened 2019-07-17 08:08 UTC
Hi,

When I download the pdf file from the invoice, the total is unconfigured, and the value is incorrect. As you can see in the picture.

![image](https://user-images.githubusercontent.com/49063138/61358526-607c2e80-a872-11e9-9c08-cab883b89578.png)

**Comment by khouloudbelguith** [comment] 2019-07-17 08:37
Hi @JorgeNogueiraLFMPro,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment] 2019-07-17 08:59
Version: 1.7.5.2
Steps:
- My account;
- Order history;
- Download PDF;
Debug report:
![image](https://user-images.githubusercontent.com/49063138/61361454-6e34b280-a878-11e9-94f0-91a03b152cbc.png)

![image](https://user-images.githubusercontent.com/49063138/61362029-66c1d900-a879-11e9-920f-ff7952121ced.png)

![image](https://user-images.githubusercontent.com/49063138/61362048-6e817d80-a879-11e9-848e-c36aa2736d35.png)

![image](https://user-images.githubusercontent.com/49063138/61362086-7e00c680-a879-11e9-96c1-90afa6d14058.png)

**Comment by khouloudbelguith** [comment] 2019-07-17 09:12
@JorgeNogueiraLFMPro, if your download the invoice from the back office the total is well displayed?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment] 2019-07-17 09:21
@khouloudbelguith  in BO the invoice total is correct.

**Comment by khouloudbelguith** [comment] 2019-07-17 09:52
@JorgeNogueiraLFMPro, in my case, I did not manage to reproduce the issue with PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/61366132-e4d5ae00-a880-11e9-98e0-9a2e521a528f.png)
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment] 2019-07-17 10:40
Everything is there in this file

Operating System: CentOS release 6.6 (Final)
Type and version of webserver: Apache/2.4.25 (Unix)
Version of PHP: PHP 7.1.22
Version of MySQL/MariaDB: mysql  Ver 14.14 Distrib 5.5.31

[bGZtcHJvLmNvbS5lcnJvci5sb2c=.zip](https://github.com/PrestaShop/PrestaShop/files/3401430/bGZtcHJvLmNvbS5lcnJvci5sb2c.zip)

**Comment by khouloudbelguith** [comment] 2019-07-17 16:38
@JorgeNogueiraLFMPro, in your log file, you don't have errors, there are just some warnings and PHP notice.
Did you the default theme by PrestaShop?

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment] 2019-07-17 16:44
@khouloudbelguith I have a theme that I bought in prestashop.

**Comment by khouloudbelguith** [comment] 2019-07-17 16:45
@JorgeNogueiraLFMPro, have you tried to contact the theme author via your addons account?
Thanks to check with them & feedback.

**Comment by JorgeNogueiraLFMPro** [comment] 2019-07-17 16:47
@khouloudbelguith I talked to them and they said to talk to you.

**Comment by khouloudbelguith** [comment] 2019-07-17 16:49
@JorgeNogueiraLFMPro, Could you please provide your theme to test it.
This is a public space.
You can provide me the theme by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

PS: I used the default theme & it is OK.

Thanks!

**Comment by JorgeNogueiraLFMPro** [comment] 2019-07-17 16:54
@khouloudbelguith I already sent the email

**Comment by khouloudbelguith** [comment] 2019-07-17 16:59
@JorgeNogueiraLFMPro, thanks!
I just received the email.
But the zip file is just an XML file & not the exact theme that I need to upload & check it.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-18 11:15
@JorgeNogueiraLFMPro, I tried also with your theme & it is OK.
I attached a screen record
https://drive.google.com/file/d/1w-QqRUWjH-x_sWUyHhDDt84QgkQMGWSa/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-07-19 13:05
@JorgeNogueiraLFMPro, I tried with your shop & it is OK.
I sent you by email a screen record

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-19 07:48
Hi @JorgeNogueiraLFMPro,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-19 07:48 UTC
Labels: Bug, Invoices, Taxes and Prices, No change required, 1.7.5.2
