### ISSUE TITLE
French translation for test email is bad - bad encoding

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20645] opened 2020-08-19 16:45 UTC
#### Describe the bug

When using "send me a test email" from Email BO page (if you want to test your SMTP parameters for example), if BO is using French, the message which is sent is quite weird:

- title: "Message de test -- PrestaShop" => OK
- content: `Ceci est un e-mail test, votre serveur est pr&ecirc;t pour envoyer des e-mails.` => what's that 😆  ? looks like "prêt" is badly encoded

#### Expected behavior

Message should arrive properly.

#### Steps to Reproduce

0. Install shop in French
1. Go in Emails BO page
2. Put some valid SMTP parameters
3. Send a test email
4. See bad message

* PrestaShop version: develop

**Comment by SimonGrn** [comment] 2020-08-19 20:19
Hello,
could you add a screenshot maybe ? Because your message ended correctly when you pasted it, ironically 😄

**Comment by matks** [comment] 2020-08-20 07:15
Here we go 😄 

![Capture d’écran 2020-08-20 à 09 14 30](https://user-images.githubusercontent.com/3830050/90728670-98e80a80-e2c5-11ea-99d7-e281a78e264e.png)

Now I'm wondering, maybe the issue comes from gmail 😛

**Comment by SimonGrn** [comment] 2020-08-20 08:14
Could you please try with an Outlook SMTP server maybe ?

**Comment by matks** [comment] 2020-08-20 09:40
> Could you please try with an Outlook SMTP server maybe ?

Microsoft stuff ? 😱

**Comment by khouloudbelguith** [comment] 2020-08-21 08:50
Hi @matks,

I manage to reproduce the issue with develop branch(1780), 
![image](https://user-images.githubusercontent.com/16067358/90871955-2dbd3780-e39c-11ea-9521-9f7e5a706c78.png)
But it is added to our debug roadmap.
Your ticket is a duplicate of #15469
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-21 08:51
Duplicate of #15469

**Closed as completed by khouloudbelguith** 2020-08-21 08:50 UTC
Labels: Bug, develop, BO, Duplicate, Email
