### ISSUE TITLE
Autoupgrade - BO - An error related to the Controller is missing or invalid on the Theme Catalog page after an upgrade from 1.7.8 to 8.0.1/8.0.2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31645] opened 2023-03-03 15:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An error related to the Controller is missing or invalid on the Theme Catalog page after an upgrade from 1.7.8 to 8.0.1/8.0.2

This issue is reported previously and fixed after the upgrade to 8.0.0 in this issue #29858 

**Upgrade from 1788 to 8.0.1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/222765816-f940804c-ad0c-4492-b0cc-4320bdcd3c51.png)

**Upgrade from 1788 to 8.0.2 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/222765861-2d1bc9ff-bd09-4cf9-bfb1-6d70268272a5.png)

### Expected behavior

The Theme Catalog pages should not be displayed in the BO menu after an upgrade to 8.0.0

### Steps to reproduce

1. Install PS8.0.1 / PS8.0.2
2. Use the release of autoupgrade.zip (v4.15)
3. Go to 1-click upgrade > Configure
4. Enable the Disable non-native module option
5. Do not uninstall the problematic modules
6. Under auto-upgrade > Download > Use the .zip for the 8.0.2 and the xml for the 8.0.2
7. Upgrade from PS1788 to PS8.0.2
8. Check that the upgrade to 8.0.2 is OK
9. Connect to 8.0.2 shop
10. GO to BO > Design > Theme Catalog page
11. See error ==> related to the controller is missing or invalid of Theme Catalog

### PrestaShop version(s) where the bug happened

8.0.1, 8.0.2

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15

**Comment by Zoefinders** [comment] 2023-04-13 10:08
I can't reproduce the bug in 1.7.8. @hibatallahAouadni  try to reproduce the bug again ? Thanks !

**Comment by AchrafKchaou1991** [comment] 2023-06-01 09:38
Hello @Zoefinders ;
I Tested the issue , it still persists.See the screenshot
![Capture d’écran du 2023-06-01 10-38-45](https://github.com/PrestaShop/PrestaShop/assets/131356155/983013c1-25ac-45a5-8776-e78e9e5e4a3c)
Thanks.

**Comment by MatShir** [comment] 2023-06-21 15:10
Closed in favor of https://github.com/PrestaShop/PrestaShop/issues/31645

**Closed as not planned by MatShir** 2023-06-21 15:10 UTC
Labels: Bug, Minor, BO, Design, Theme catalog, Regression, Autoupgrade, Verified, Module, 8.0.1
