### ISSUE TITLE
Backoffice help pop-up doesn't work in all pages

### ISSUE THREAD

**Issue by sersis-dev** [PrestaShop/PrestaShop#33902] opened 2023-09-11 07:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The pop-up help in the backoffice doesn't work on most pages.
I saw other post with similar problem and check the related solution, but it doesn't work for me.

Examples: 
it works in Shipping > Carriers
![image](https://github.com/PrestaShop/PrestaShop/assets/118921057/3c7f4da6-9708-4db4-9bba-10268e46b1cc)

it not works in Catalog > Products, in Orders, in Modules > Module Manager and many other pages (a white sidebar is shown)
![image](https://github.com/PrestaShop/PrestaShop/assets/118921057/85cff6e6-4617-4f40-9757-fb20bac2da48)

In the chrome devTools i see an url similar to this with 404 http response:
https://www.mysite.com/manager/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop.com%252Fen%252Fdoc%252FAdminProducts%253Fversion%253D1.7.8.9%2526country%253Den/Help?_token=uSJZf9vGOPqO0pC3dLA1as9TG2gIKAvj9G6joChSQ1g

### Steps to reproduce

1. Go to Admin Panel
2. Go to Catalog > Products or Modules > Module Manager or other
3. Click the Help button

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment] 2023-09-11 10:21
Hello @sersis-dev 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23996.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by sallemiines** [comment] 2023-09-11 10:21
Duplicate of #23996

**Closed as completed by sallemiines** 2023-09-11 10:21 UTC
Labels: Bug, Duplicate, Invalid

**Comment by sersis-dev** [comment] 2023-09-11 10:32
Hi,
I saw post #23996, but the given solution #25004 is not applicable in my case. Indicated lines of code are already present in the files.
Also, the post is marked as closed.

Thank you.
