### ISSUE TITLE
Product assembler, check null missing

### ISSUE THREAD

**Issue by jonathangreco** [PrestaShop/PrestaShop#24666] opened 2021-05-26 14:16 UTC
#### Describe the bug

For some reason, we may have this bug when the SQL request return null: 

`
"PHP message: PHP Notice:  Undefined offset: 0 in /home/my_website/site/www/classes/ProductAssembler.php on line 95 PHP message: PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/my_website/site/www/classes/ProductAssembler.php on line 95
`

that leads to the following fatal : 

`
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PrestaShop\PrestaShop\Adapter\Presenter\Product\ProductListingPresenter::present() must be of the type array, bool given, called in /home/my_website/site/www/modules/ybc_blog/ybc_blog.php on line 7472 and defined in /home/my_website/site/www/src/Adapter/Presenter/Product/ProductListingPresenter.php:43
Stack trace:
`

#### Expected behavior

The code should throw no warning and no fatal if the rows is also check for th `null` case in the code below

```PHP
    private function addMissingProductFields(array $rawProduct)
    {
        $idShop = (int) $this->searchContext->getIdShop();
        $idLang = (int) $this->searchContext->getIdLang();
        $idProduct = (int) $rawProduct['id_product'];
        $prefix = _DB_PREFIX_;

        $nbDaysNewProduct = (int) Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
        if (!Validate::isUnsignedInt($nbDaysNewProduct)) {
            $nbDaysNewProduct = 20;
        }

        $now = date('Y-m-d') . ' 00:00:00';

        $sql = "SELECT
                    p.*,
                    pl.*,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_lang pl
                    ON pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa
			        ON sa.id_product = p.id_product 
			        AND sa.id_shop = $idShop
			    WHERE p.id_product = $idProduct";

        $rows = Db::getInstance()->executeS($sql);

        // testing false, is not enougth as rows can also be null. <------------------ testing null here
        if ($rows === false || $rows == null) {
            return $rawProduct;
        }

        return array_merge($rows[0], $rawProduct);
    }
```

#### Additional information
The method signature of executeS is as follow 
![image](https://user-images.githubusercontent.com/1587180/119676412-1f75dd80-be3e-11eb-8288-bfd6e1a79230.png)

So null is a real thing.

* PrestaShop version: 1.7.7.2
* PHP version: 8

**Comment by hibatallahAouadni** [comment] 2021-05-26 19:42
Hello @jonathangreco 

Could you please provide steps to reproduce the issue.
Please downgrade your PHP version to 7.3 cause PS1.7.7.2 is not compatible with PHP v8 (see our [system requirement](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-15 08:19
Hello @jonathangreco 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-15 08:19 UTC
Labels: Bug, CO, No change required, 1.7.7.2

**Comment by jonathangreco** [comment] 2021-06-30 15:53
This ticket should not be closed.

The code shown is enough and does not need more information or use case.

ExecuteS can return null ! It's a fact. Everybody knows it.

Since this fact is real, array_merge on null values will throw fatal errors even in PHP 7.3 (tested). So the if statement that check false, have to check null also.

**Comment by hibatallahAouadni** [comment] 2021-06-30 15:55
>The code shown is enough and does not need more information or use case.
>
>ExecuteS can return null ! It's a fact. Everybody knows it.
>
>Since this fact is real, array_merge on null values will throw fatal errors. So the if statement that check false, have to check null also.

Ping @PrestaShop/prestashop-maintainers could someone please check this issue :pray: 
Thanks in advance.

**Comment by jonathangreco** [comment] 2021-06-30 16:00
Thanks @hibatallahAouadni I updated my description. It should be an easy fix ;)

**Comment by jonathangreco** [comment] 2021-07-05 11:59
@hibatallahAouadni Hi ! No news on this one ?

**Comment by hibatallahAouadni** [comment] 2021-07-05 12:12
@PrestaShop/prestashop-core-developers friendly reminder 🙏 could someone please check the code above.

Thanks in advance!
