### ISSUE TITLE
Attributes + Attributes = mess  1.7.5.1

### ISSUE THREAD

**Issue by flameair** [PrestaShop/PrestaShop#13917] opened 2019-05-22 12:00 UTC
**Describe the bug**
Attributes + Attributes = mess

**To Reproduce**
1. Add attributes 3x colors red,ble,green with images and 3x attributes M, L, XL
2. Generate combinations
3. Set up avalable Red M, Red L, Red XL, Blue M, Green XL
4. Set up in BO visibilyty out of stock to no and can order when product out of stock to no.

Conclusion when You are in size M You can see Green but when You click on it nothing happening. It Refresh and go back to avalable RED.

**Video**
https://streamable.com/r59bs

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-05-22 12:09
Hi @flameair,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9667
It will be fixed in the next major release 1.7.7.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-22 12:10
Duplicate of #9667

**Closed as completed by khouloudbelguith** 2019-05-22 12:09 UTC
Labels: Duplicate
