### ISSUE TITLE
Impossible to clean Logs

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#15014] opened 2019-08-07 08:47 UTC
**Describe the bug**
When you are on the Logs pages using the Delete All function, absolutely nothing happens.

**To Reproduce**
1. Go to Advanced Parameters >Logs
2. Click on Cogs icon
3. Scroll down to Erase All
4. and ... nothing happend

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6.40 i don't test other versions

**Comment by khouloudbelguith** [comment] 2019-08-07 08:50
Hi @jeckyl,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14701 to fix the issue.
It is added to PS1.7.6.1.
Your ticket is a duplicate of #14686
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-07 08:51
Duplicate of #14686

**Closed as completed by khouloudbelguith** 2019-08-07 08:50 UTC
Labels: Duplicate

**Comment by Matt75** [comment] 2019-08-07 08:57
Welcome @jeckyl 
Thanks for participating 🥳
