### ISSUE TITLE
AdminStockManagementController clears smarty cache every time it's loaded.

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#21944] opened 2020-11-17 08:46 UTC
#### Describe the bug

AdminStockManagementController.php has Tools::clearSmartyCache(); in the postprocess function, this cause the smarty cache to be cleared every time the page is loaded, causing lots of stress on the hosting on larger shops.

#### Expected behavior

If smarty cache needs to be cleared for this feature, it should only be cleared if there are any changes made.

#### Steps to Reproduce

1. go to catalogue price rules in the admin, the smarty cache is cleared.

#### Additional information

* PrestaShop version: 1.7.0.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2020-11-17 09:25
Hello @Prestaworks 

Could you please check if your issue is duplicate to this one #14761

> PrestaShop version: 1.7.0.0

I believe you meant 1.7.7.0, is that so?

Thanks!

**Comment by Prestaworks** [comment] 2020-11-17 13:38
it seems to be related but not the same. That ticket talks about adding clear cache for smarty to the new controller? I guess symfony controller? if that is the case, make sure that this issue is not replicated on the new controller.

**Comment by hibatallahAouadni** [comment] 2020-11-17 16:40
Hello @Prestaworks 

> go to catalogue price rules in the admin, the smarty cache is cleared.

Could you please provide clearer steps to reproduce.

Thanks!

**Comment by Prestaworks** [comment] 2020-11-18 07:31
not really, that's all you have to do to trigger the smartyclearchache feature. You can look in the cache folder in Prestashop, see if you have some files and folders there and then just open the catalogue price rules list and all the files and folders will be deleted.

**Comment by hibatallahAouadni** [comment] 2020-11-18 08:32
Hello @Prestaworks 

I managed to reproduce your issue with PS1.7.6.8, and it has been fixed in PS1.7.7.0 with this PR #13716
Please check and feedback.

Thanks!

**Comment by Prestaworks** [comment] 2020-11-18 10:44
nice

**Comment by hibatallahAouadni** [comment] 2020-11-18 10:50
Well then, I close this issue because it was fixed in PS1.7.7.0.
Thanks for your report and feel free to create a new issue when you need.

**Closed as completed by hibatallahAouadni** 2020-11-18 10:50 UTC
Labels: Bug, BO, Catalog price rules, Fixed, 1.7.7.0
