### ISSUE TITLE
Problem with cart and products with customization

### ISSUE THREAD

**Issue by lorenzoripa** [PrestaShop/PrestaShop#25293] opened 2021-07-09 07:03 UTC
#### Describe the bug

When I add a product to the cart with personalization and then I go to add the same product in another color but without personalization.
In the cart I find the personalization on the second product instead of on the first inserted and when I go to update the quantities of the first product, the system creates a new line with the same product
It only happens if I insert the product with the personalization the first time, otherwise not

https://user-images.githubusercontent.com/9265978/125037459-75bc7a00-e094-11eb-9e4b-aec1ecab2718.mp4

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.4

**Comment by khouloudbelguith** [comment] 2021-07-09 09:31
Hi @lorenzoripa,

First, PrestaShop is not compatible with PHP 7.4, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
PrestaShop 1.7.7 is compatible with PHP7.3
The next Major release PS1.7.8 will be compatible with PHP7.4.
You need to downgrade your PHP version.

Second, thanks for the issue, but you need to follow the template, you need to edit your first comment, and add the exact steps to reproduce the issue.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Third, about your issue, I manage to reproduce it with PS1.7.6.9 and PS1.7.7.5
https://drive.google.com/file/d/1a7azn8HyadBH3xGzxRBm5eqk_Ud1qdg9/view?usp=sharing

[Untitled_ Jul 9, 2021 9_57 AM.webm](https://user-images.githubusercontent.com/16067358/182120276-0e0cb160-99e3-46af-8b0d-864059524546.webm)

But it is fixed in the next major release PS1780
I attached a screen record: https://drive.google.com/file/d/1YC2bQrzLyArc1OOU6zODVi-zdejxnFOu/view?usp=sharing

[Untitled_ Jul 9, 2021 10_32 AM.webm](https://user-images.githubusercontent.com/16067358/182120857-4fff930c-3320-40f7-9745-95467ad3ac1d.webm)


It is ok with PS1780_rc1.

Since it is fixed, I close the issue.

Thank you

**Closed as completed by khouloudbelguith** 2021-07-09 09:31 UTC
Labels: Bug, FO, Combinations, Product customization, Fixed, 1.7.6.9, 1.7.7.5
