### ISSUE TITLE
Inconsistency in the exibition of products with combinations having minimal quantities 

### ISSUE THREAD

**Issue by amaurigabriel** [PrestaShop/PrestaShop#19283] opened 2020-05-22 14:44 UTC
HI!

I opened a bug report, which got closed because I didn't understood what more information were you askind from me.

https://github.com/PrestaShop/PrestaShop/issues/18209

I think the old thread is no longer being monitored, so I will copy the description. I am really sorry if it is considered as a duplicate...

> Hi,
> 
> I have a product with two combinations, one of them with minimal_quantity of 25 and the other with minimal_quantity of 1 (check the product [here](https://php72.paradadigital.com.br/acessorios-para-casa/10-25-brown-bear-cushion.html)).
> 
> If I set the combination **Cor: Branco**, the quantity input is set to 25, as expected. If I change back to combinaton **Cor: Preto** the input is set to 1. I don't think this is the expected behavior, but even if this is intended, the request used to render the product info send the parameter **quantity_wanted=25**. If the quantity input is set to 1, the parameter **quantity_wanted** should be 1 as well.
> 
> We have a module that uses this hook to display information based in the quantity wanted by the user. As the parameter **quantity_wanted** is **25** but the quantity input is rendered with **1**, the information displayed by our module became inconsistent.
> 
> ![image](https://user-images.githubusercontent.com/1836086/76978224-330de600-6915-11ea-9e99-0ded1215ca51.png)
> ![image](https://user-images.githubusercontent.com/1836086/76978274-428d2f00-6915-11ea-98fa-e509528ab9b6.png)
> 
> If I change back to **Cor: Branco** we have the same unexpected behavior. The hook tell us that the customer want **1** units of the product, but the input is rendered with **25**.
> 
> This issue only happens in PS Version >= 1.7.6.
> 

==========================
What more information do you need from me about this issue?

**Comment by florine2623** [comment] 2020-05-22 16:10
Hi @amaurigabriel ,

Sorry your issue has been closed unintentionally.

Indeed your issue seems to be linked to https://github.com/PrestaShop/PrestaShop/issues/14744
So it is a duplicate.
For now, it is in our debug roadmap.

As the issue is a duplicate, I will close it.

Thanks for your understanding !

**Comment by florine2623** [comment] 2020-05-22 16:10
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/14744

**Comment by marionf** [comment] 2020-05-25 08:39
@florine2623 We can close this issue if it's a duplicate

**Closed as completed** 2020-05-29 16:07 UTC
Labels: CO, Duplicate, Combinations
