### ISSUE TITLE
TTFB over 1.0 seconds for 1.7.7.1 and 1.7.7.2

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#23450] opened 2021-02-28 17:29 UTC
Hi,

I'm having a TTFB with no less than 1.0 seconds (sometimes 2.0s or 3.0s). I run my prestashop on a VM with apache and mysql. This server is a dedicated server, so there are no other "shared" workloads there.  My VM has 32 cores and 32gb of RAM.

I already tried lots of things on the server side (changed Apache MPM, tried different values, etc).
I also tried to disable Prestashop modules do the maximum possible.
I'm using Cloudflare as Media Server.

I already excluded the network settings because I've the same values when I reach the server on my local network
I don't see any resource exhaustion on the server side...
My shop has 10.000 Products, 60.000 Registered Customers and an average of 4500 users per day.
I'm using filesystem cache. CCC, etc. 

So I'm running out of ideas.

```
Server information Linux Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64

Server software version: Apache
PHP version: 7.2.24-0ubuntu0.18.04.7
Memory limit: 1024M
Max execution time: 600
Upload Max File size: 128M
```

```
<IfModule mpm_prefork_module>
		StartServers 3
		MinSpareServers 5
		MaxSpareServers 10
		MaxRequestWorkers 420
		ServerLimit 420
		MaxConnectionsPerChild 0
</IfModule>
```

```
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 fcgid_module (shared)
 filter_module (shared)
 headers_module (shared)
 http2_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
```

**Comment by matks** [comment] 2021-02-28 18:20
Hi @seederp2p, "Performance is a subjective topic" as mentioned in https://build.prestashop.com/news/performance-and-prestashop/ so I'm afraid we wont be able to help you boost the perf of your server without looking at it. It's like trying to repair a phone but you cannot touch it. Someone needs to look at it closely, and this person needs to be paid.

So the only thing we can provide you:
- this series about performance https://build.prestashop.com/news/performance-and-prestashop/
- our White paper about performance https://content.prestashop.com/hubfs/WhitePaper/PrestaShop_System_Performance.pdf
- you might find people with similar interests and experts to hire on the Slack channel https://github.com/PrestaShop/open-source/blob/master/slack/readme.md
- you might find people with similar interests and experts to hire on the forum https://www.prestashop.com/forums/

Else you can also have a look at the PrestaShop Company’s support plans https://www.prestashop.com/support

As we use GitHub issues only to discuss about bugs and new features for the PrestaShop project, I close the issue as this is not a bug or a feature, but rather a need for expertise.

**Closed as completed by matks** 2021-02-28 18:20 UTC
Labels: No change required

**Comment by seederp2p** [comment] 2021-02-28 18:40
Hi @matks I can't agree with you.

If you can point me a shop with 1.7.x.x with a TTFB < 1sec I would appreciate. I mean a real shop... not a demo, not a stripped down version of PS. Not a baby shop, a real shop!

If in the same server I can provide a wordpress with arround 400/500ms of TTFB and PS is higher 1 second or more it tells me that there's something with PS.

Of course we can do the easiest way which is "well, it's working, there are no error messages... so everything's ok". A software product is not only about its functionality. You assume that its a server problem... I don't rule it out.... but honestly? Don't think so.

But we will never know as you just closed the issue without any further troubleshooting :)

Cheers.

**Comment by kpodemski** [comment] 2021-02-28 19:27
I just checked two stores, two of them have TTFB < 1s

jezykiobce.pl
resibo.pl

If you want to discuss performance of PrestaShop I suggest to create topic on official forum or visit PrestaShop' Slack.

Every store is different and something working in one, it could be no good for other.

**Comment by seederp2p** [comment] 2021-02-28 19:50
Hi @kpodemski Thank you for your feedback.

Polish servers look great in terms of TTFB ;) However my store has a better overall loading speed according to GTMetrix.

I already created a topic on official. Without any reply: https://www.prestashop.com/forums/topic/1043773-how-to-get-the-best-performance/

Cheers

**Comment by matks** [comment] 2021-02-28 20:27
> Of course we can do the easiest way which is "well, it's working, there are no error messages... so everything's ok". A software product is not only about its functionality. You assume that its a server problem... I don't rule it out.... but honestly? Don't think so.

@seederp2p I dont assume it's a server problem. What I however assume is that we will not able to find out the root of the issue without being able to access and modify your server settings. Do you think I can simply "troubleshoot" your shop by thinking very hard? 😄 Performance issues can be fixed by tracking and monitoring many metrics, and trying many things. So opening a github issue is pointless.

What you need is someone to check at your store and do this exploration work. Maybe it's an issue from PrestaShop, maybe it's an issue from your modules, maybe it's an issue from your theme, maybe it's an issue from the settings. But only someone who will spend time on your shop and your server will find out.

We are GitHub maintainers, we dont go on users shops and servers to find the issue for them 😉 . This is why I think you need an expert.

When you have found the issue, we would very happy to know what was the issue. If it's in PrestaShop code, we will be happy to improve it. That would be a great opensource story. But the work needed to identify your issue can only happen on your shop and your server, and the person that will do this will probably be a paid expert, not a GitHub maintainer that helps this project move forward using his own time.

**Comment by matks** [comment] 2021-02-28 20:32
@seederp2p An expert in PrestaShop once told me, when he troubleshoots a shop, the very first things he checks are this:

1. Disable all modules. See if it helps. If yes, issue come from one module. Issues can also come from bad modules caching system, especially Smarty cache.
2. Disable the FO theme. See if it helps. If yes, issue come from the theme.
3. Check MySQL indexes, look for SQL tables with too much data. If you find too much useless data (like logs), remove useless data. For example `ps_configuration` can be filled of data left there by old (uninstalled) modules, and this can slow down the shop.
4. Check MySQL config. Check webserver config. Looks for bottlenecks.

If you have checked these 4 steps, then only an expert paid time can help you for forward I think.

**Comment by seederp2p** [comment] 2021-02-28 21:11
> @seederp2p An expert in PrestaShop once told me, when he troubleshoots a shop, the very first things he checks are this:
> 
> 1. Disable all modules. See if it helps. If yes, issue come from one module. Issues can also come from bad modules caching system, especially Smarty cache.
> 2. Disable the FO theme. See if it helps. If yes, issue come from the theme.
> 3. Check MySQL indexes, look for SQL tables with too much data. If you find too much useless data (like logs), remove useless data. For example `ps_configuration` can be filled of data left there by old (uninstalled) modules, and this can slow down the shop.
> 4. Check MySQL config. Check webserver config. Looks for bottlenecks.
> 
> If you have checked these 4 steps, then only an expert paid time can help you for forward I think.

Yeah, I can confirm that I already did all the steps ;)
