### ISSUE TITLE
Order Cart Rule Name is empty

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#27633] opened 2022-02-09 20:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,
I'm using the 1.7.8.2 version. When using cart rule for an order, the name of th cart rule is empty in the admin order and in the pdf order.

### Steps to reproduce

Create a cart rule with a name.
Place an order and use the cart rule
You will see empty name
![Capture d’écran du 2022-02-09 21-36-07](https://user-images.githubusercontent.com/5048627/153286432-902be2db-828c-4533-a923-f5cbe50ac420.png)

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by grabelle** [comment] 2022-02-09 20:44
Here is the cart rule

![Capture d’écran du 2022-02-09 21-43-40](https://user-images.githubusercontent.com/5048627/153286681-111f1c6d-cca7-470b-ac1e-38e30884e270.png)
![Capture d’écran du 2022-02-09 21-43-29](https://user-images.githubusercontent.com/5048627/153286683-5e79f20d-4420-4c71-9ba5-74c072c36cc2.png)
![Capture d’écran du 2022-02-09 21-43-14](https://user-images.githubusercontent.com/5048627/153286685-f7915bac-6089-4823-86c1-7b1c1e64fac2.png)

**Comment by grabelle** [comment] 2022-02-09 20:49
For information I have 4 langages activated.

**Comment by HanaRebaiQA** [comment] 2022-02-10 13:37
Hello @grabelle 

I used the **PS1782** version with **php7.3** & **php7.4** and i was unable to reproduce your issue. 
Here is my executed case : 
![image](https://user-images.githubusercontent.com/92912932/153415957-88857fc3-2eba-4cb9-b56f-317113bf9ac7.png)

https://user-images.githubusercontent.com/92912932/153418922-78cbc78e-136a-486b-b7dd-7cfdc30b9f57.mp4


Did i missed a step ?

Please check and feedback!

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-02 00:49
Hello @grabelle 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-03-02 00:49 UTC
Labels: Bug, BO, Order, Cart rules, Invalid
