### ISSUE TITLE
Missing store on special prices at product page

### ISSUE THREAD

**Issue by krasnycz** [PrestaShop/PrestaShop#10702] opened 2018-09-25 15:21 UTC
Store name is missing at the special prices on the product page in the BO.

1. Go to back office
2. Edit a product
3. Add special price
4. Now you can see special prices list for the product. However there i no way to see multistore domain -> now way to see what is the special price for because you can have same looking records with duplicate data.

All PS 1.7 versions. Multistore only.

**Comment by khouloudbelguith** [comment] 2018-09-25 15:58
Hi @krasnycz,

This issue should be fixed in this ticket: #9833
Your ticket is a duplicate of #9833
So, I close it.
Thanks !

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-25 15:58
Duplicate of #9833

**Comment by krasnycz** [comment] 2018-09-25 16:43
I do belive this ticket is not a duplicate of #9833. It is just UI bug - the BO is not displaying store domain on special prices. Not related to price in multistore context. I saw that ticket before.

**Comment by khouloudbelguith** [comment] 2018-09-26 10:21
Hi @krasnycz,

Could you please add a screenshot about your issue?

Best regards, KHouloud

**Comment by khouloudbelguith** [comment] 2018-10-25 11:21
Hi @krasnycz,

Any news about your issue?
Thanks!

**Comment by krasnycz** [comment] 2018-10-25 11:28
Well everything needed was examplained in the opening reply. Shop domain is missing in the backend when edit the products.

**Comment by khouloudbelguith** [comment] 2018-10-25 11:32
@krasnycz, It will help us if you can attach a screenshot about your issue.
Thanks!

**Comment by krasnycz** [comment] 2018-10-25 11:39
Well when you set special discount for different stores the stores are not showing in the special discounts overview at the product page > prices. So basically there is no way to manage the prices but delete them all and start from scrath. Totaly unusable. However this is not going to help much, in past version core team completely damaged the special prices funcionaltiy and discounts are not working at all. If you set more then 1 special price the wrong prices are deducted and wrong VAT is calculated. However it seems pointless to report it since you always close tickets even from different issues and there seems to bude language problems with the devs too.

![missing-store](https://user-images.githubusercontent.com/15078106/47497636-0908df00-d85b-11e8-8689-cbc66cc603d1.png)

**Comment by khouloudbelguith** [comment] 2018-10-25 15:04
Hi @krasnycz,

Now, in the 1.7.5.0, editing specific prices is available.
![image](https://user-images.githubusercontent.com/16067358/47510178-e46f3000-d877-11e8-9ac5-03802503f2fe.png)
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9465 to add this feature.
Thanks to check & feedback.

**Comment by krasnycz** [comment] 2018-10-28 10:18
Lets see. Whole special prices functionality is broken in the latest release. I will wait for 1.7.5 release and then check it again and report issues.

**Comment by khouloudbelguith** [comment] 2018-10-29 07:51
Hi @krasnycz,

Thanks for your feedback. PS 1.7.5.0 will be released in a few weeks.
I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-29 07:51 UTC
Labels: Multistore, No change required, 1.7.4.2
