### ISSUE TITLE
Multistore monitoring problem

### ISSUE THREAD

**Issue by costads** [PrestaShop/PrestaShop#23547] opened 2021-03-06 19:44 UTC
#### Describe the bug
'List of products without combinations and without available quantities for sale'

is always 0 when a shop in multistore is selected. I have to switch to 'All shops' to see products in that table.

#### Expected behavior
I expected to see my out of stock products, like I could in 1.7.6 and previous years versions.

#### Steps to Reproduce
Select a Shop in multistore mode.

1. Go to Catalogue -> Monitoring
2. Now, add a new single product for ShopA or B (shop_id 1), and set stock to 0, and save the product.
3. It should now appear in Monitoring for either shop A or B, but it's not.

If you check the DB, you will see that the product is added as id_shop 0 in ps_stock_available, and not id_shop 1.
If I change id_shop to 1, the product will appear in 'List of products without combinations and without available quantities for sale' as it should.

I just checked my old running PS 1.7.6.1, and that has all my products listed as id_shop 0 in ps_stock_available, but was working fine in monitoring? I don't understand what is going on :)

#### Screenshots
![github](https://user-images.githubusercontent.com/67175129/110219010-099af100-7ebd-11eb-8b10-de06361c8194.png)

Edit: Spending a little more time looking at this, I compared:
```
NoQtyProductWithCombinationQueryBuilder.php
NoQtyProductWithoutCombinationQueryBuilder.php
```

And noticed a slight difference in line 86. In one file it's $attrSubQuery and the other $SubQuery,
so I tried to use $attrSubQuery in NoQtyProductWithoutCombinationQueryBuilder.php and that seem to fix the problem.

Don't know what the difference is though, as I am no coder at all.

Anyway, this is what I have now:

```
        $subQuery = $this->connection->createQueryBuilder()->select(1);
        $subQuery
            ->from($this->dbPrefix . 'stock_available', 'stock')
            ->andWhere('p.id_product = stock.id_product')
            ->andWhere('NOT EXISTS(' . $attrSubQuery->getSQL() . ')')
            ->andWhere('IFNULL(stock.quantity, 0) <= 0');

        if ($this->multistoreContextChecker->isSingleShopContext()) {
            $attrSubQuery->andWhere('stock.id_shop = :context_shop_id')
                ->setParameter('context_shop_id', $this->contextShopId);
        }
```

#### Additional information

- PrestaShop 1.7.7.2 (New installation - stock)
- PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-03-08 12:50
Hello @costads 

I didn't manage to reproduce your issue with PS1.7.7.2, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110323621-21858880-8015-11eb-97b7-b95f5e44834a.png)

Please check and feedback.
Thanks!

**Comment by costads** [comment] 2021-03-08 13:08
Well, I don't know what to say. All i know is that I have been using PS for years and never had this problem untill 1.7.7.
The changes I did with the code above fixed my problem in both my running shop, and test install.

I must do something in a special order or something, since only I seem to have this problem on both my old, and a new install. Did you create the new costads product in shop_id 1?

I don't guess this could be something server related, f.ex. my PHP 7.3.25 ?

If you want to check,  you can have access to my test install.

**Comment by matks** [comment] 2021-03-08 13:38
> Well, I don't know what to say. All i know is that I have been using PS for years and never had this problem untill 1.7.7.
> The changes I did with the code above fixed my problem in both my running shop, and test install.
> 
> I must do something in a special order or something, since only I seem to have this problem on both my old, and a new install. Did you create the new costads product in shop_id 1?

On-premise software is a very unreliable science 😄  dont worry, it happens regularly.

> I must do something in a special order or something, since only I seem to have this problem

Some module installed? Some FO theme? Some integrations?

**Comment by costads** [comment] 2021-03-08 13:47
No, I made a brand new stock install to eliminate any modules, themes, overrides,  etc. :)
Then I enabled Multistore, added a new shop in same shop group, enabled share stock, added a new product under id_shop 1 with 0 in stock, and then noticed it was not listed in monitoring.

**Comment by hibatallahAouadni** [comment] 2021-03-08 13:59
Hello @costads

> I must do something in a special order or something, since only I seem to have this problem on both my old, and a new install. Did you create the new costads product in shop_id 1?

Yes, as you can see in the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110331090-e8eaac80-801e-11eb-8429-440e6519f738.png)

Please check and feedback.
Thanks!

**Comment by costads** [comment] 2021-03-08 14:12
I mean in the table ps_stock_available.

When I add a new product as id_shop 1 (ShopA or ShopB) , the row is added as id_shop 0 in the ps_stock_available table.
Should it not be either added in the DB as id_shop 1 or maybe both id_shop 0 and 1 at the same time?

**Comment by hibatallahAouadni** [comment] 2021-03-10 22:06
Hello @costads 

Thanks for your feedback!
I didn't manage to reproduce the issue, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110704453-433d6600-81f5-11eb-84a6-9d7b8c84085b.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-30 17:56
Hello @costads ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-30 17:56 UTC
Labels: Bug, BO, Monitoring, No change required, 1.7.7.2
