### ISSUE TITLE
Discount edit close button not working on PS 8.1.0

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#33299] opened 2023-07-18 22:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

You enter to edit the discount of a product but you try to close the popup window from the close button but it does not work. It only allows closing from the cancel button.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/0649c406-46b9-415c-8502-e224b839af98)

### Expected behavior

It should allow you to close the popup from the close button on the top right.

### Steps to reproduce

Enter the edition of a product.
Go to the Price tab.
Edit the discount already applied.
Try to close the popup from the close button on the top right.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-07-19 08:45
Hello @ocio87 ,

I can't reproduce your issue : 

https://github.com/PrestaShop/PrestaShop/assets/16019289/eac035ac-dc59-454a-8578-a066d70052e6

I can close the popup by clicking on the cross, on the cancel button and outside the popup.

**Comment by ocio87** [comment] 2023-07-19 11:18
Hello, can you please reopen the bug?

The tests were done on ps 8.1.1, the bug happens on prestashop 8.1.0.

Updated from prestashop 1.7.8.7 to prestashop 8.1.0.

I also see that the new discount was applied in a popup window. in 8.1.0 it is not applied in popup, it is done in the same window.

I don't know if it's due to problems in the update module.

https://drive.google.com/file/d/1qGobHXGxpgHuW3mhgijsZMy20AlizRv1/view?usp=sharing

**Comment by ocio87** [comment] 2023-07-19 14:24
As I see it is because you have activated the experimental functions. I activated it and the error does not reproduce. But if you disable the experimental functions, if the error occurs.

**Comment by ocio87** [comment] 2023-07-24 11:44
@florine2623 Can you check again without having the experimental functions active?

**Comment by hibatallahAouadni** [comment] 2023-08-06 22:12
Duplicate of #33541

**Closed as not planned** 2023-08-06 22:12 UTC
Labels: Bug, Duplicate
