### ISSUE TITLE
stock problems ps 1.7.4

### ISSUE THREAD

**Issue by jviure** [PrestaShop/PrestaShop#11257] opened 2018-11-05 08:36 UTC
Hi.I've created a new prestashop, first I install de 1.7.0, after two weeks I upgraded to 1.7.4. 
At the beggining, I migrate woocommerce products to prestashop with an external plugin. At the begining, all seems ok, BUT now I see some inconsistencies. Some customers have ordered products (combinations, with stock, usually 1) and they received an email of NO stock.  Strange... not? I have detected that... some of this conflictive products, if  I go to Catalog-> Stock, the product does not appear there, but exists. Some idea? What could be happening? Thank you!

**Comment by khouloudbelguith** [comment] 2018-11-05 08:40
Hi @jviure,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots
 - what is the exact version of the 1-click upgrade did you used?

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-07 16:18
Hi @jviure,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-07 16:18 UTC
Labels: Bug, No change required, 1.7.4.3
