### ISSUE TITLE
Faceted search | Page unsuable after loading page with filters in URL

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15102] opened 2019-08-13 19:28 UTC
Watch the video and/or follow the steps.

**To Reproduce**
1. Select a filters, so no product's match.
2. See no error message.
3. Parameters get written to the URL.
4. Refresh page.
5. Page loads with different "not-found" error box. No active filters are selected above the product list.
6. Remove all selected filters in left columns.
7. Error message stays. The page is unusable.
8. The only way to get it working is another refresh or going elsewhere with clear URL.

**What's wrong**
- Why is there no error message when selecting parameters and no products are found?
- Why is it even possible?
- No active selected filters when reloading the page.
- Error message stays when removing filters in left column.

**Videos**
https://drive.google.com/file/d/1bWo2pZSmC9KmVcpqoQuzJiJPlASv9nr_/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.6
PHP version: 3.1.0

**Comment by marionf** [comment] 2019-08-14 09:32
Hello @Hlavtox 

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14655
So, I close it.
Please follow the issue above

**Comment by Hlavtox** [comment] 2019-08-14 09:34
@marionf watch the video, this is not duplicate of my other ticket

With upgrade to 3.2.0, these conditions are not reproducable, but will be after you fix the module

**Comment by marionf** [comment] 2019-08-14 09:38
@Hlavtox 

I watched the video, it seems the same issue as in #14655, you select many filters and get 0 results

> With upgrade to 3.2.0, these conditions are not reproducable, but will be after you fix the module

I am not sure to understand, which version of facetedsearch are you using ?

**Comment by Hlavtox** [comment] 2019-08-17 11:23
@marionf

1. Install faceted search 3.1.0 (currently, in 3.2.0, this condition is not reproducible, because there is another bug)

2. Select some filters, so no products are found.

3. Refresh page

4. Remove filters

5. Page unusable until another refresh

**Comment by marionf** [comment] 2019-08-19 07:58
@Hlavtox 

I can't reproduce it with the steps described

https://drive.google.com/open?id=1_RKDCH5mwLf6m8o2Xvx9YN4S9a_F9OmH

**Comment by Hlavtox** [comment] 2019-08-19 09:21
@marionf 

Ohhh maybe it's a problem in the classic-rocket theme. Can you look at this @prestarocket ?

**Comment by marionf** [comment] 2019-08-19 12:24
@Hlavtox 

I close the issue as I can't reproduce it
Feel free to open a new one if needed.

Thanks

**Closed as completed by marionf** 2019-08-19 12:24 UTC
Labels: Can't reproduce, Faceted search
