### ISSUE TITLE
After returning from the payment gateway - requires user authorization 

### ISSUE THREAD

**Issue by mkuzmych** [PrestaShop/PrestaShop#26785] opened 2021-11-28 17:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the user returns to the site from a third-party payment gateway and a POST request to the site is made - the user loses authorization. This feature has worked successfully in versions 1.7.7. *. After payment, I redirect the user to: https://{DOMAIN}/en/module/{module}/result and even without doing anything in the module - the user automatically exits. 

### Steps to reproduce

1. Create payment module
2. Return user from third-party payment gateway to site
3. User loses authorization after redirect

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

wayforpay

**Comment by Matt75** [comment] 2021-11-28 21:03
Caused by recent change of Cookie Same-Site directive.

Previously default value was `None` now it's `Lax`.

https://developer.mozilla.org/en/docs/Web/HTTP/Headers/Set-Cookie/SameSite

So when customer returns to your shop from payment gateway, due to this change PrestaShop cookie will not be used due to a redirection from external website.

Thats why modern payment gateways use Javascript components like PayPal Checkout or Stripe or others to avoid redirection if server is not well configured.

In your case PrestaShop `Context` will not be initialized with `Cookie` data because you're coming from external website.

For example if PaymentModule redirect customer to `OrderConfirmationController` directly after payment on external gateway, it will enter to one of these conditions that's will do another redirection : https://github.com/PrestaShop/PrestaShop/blob/02d8f396b9649cbe1c454d388750ea24840bdaee/controllers/front/OrderConfirmationController.php#L65
Because PrestaShop `Context` doesn't contains Customer data from your `Cookie`.

Quick fix: you can add a new line on your .htaccess
`Header always edit Set-Cookie (.*) "$1; SameSite=None; Secure"`

https://web.dev/samesite-cookies-explained/

**Comment by mkuzmych** [comment] 2021-11-29 05:36
@Matt75  Hello! Thank you very much for such a detailed answer.

How to ask for your advice - I understand that in the future this directive will be in future updates, and therefore it is better than possible to redesign the module using Javascript gateway component?

**Comment by Matt75** [comment] 2021-11-29 08:24
If your payment provider allow to use iframe or JavaScript components, I recommend to implement it otherwise you can change Same-Site directive of your Cookie to None like before to restore previous behavior waiting another solution.

Since PrestaShop 1.7.8.0, you can manage Same-Site directive from your PrestaShop BO > Advanced Parameters > Administration > Cookie SameSite
Changes introduced thanks to https://github.com/PrestaShop/PrestaShop/pull/20601

**Comment by hibatallahAouadni** [comment] 2021-11-29 16:35
Hello @mkuzmych 

Thanks @Matt75 for your quick replies :superhero: 
Closing this issue as it has been solved by changing the configuration.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-11-29 16:35 UTC
Labels: Bug, Invalid

**Comment by devphoenix2404** [comment] 2022-01-23 15:26
Hi @Matt75 
for 1.7.8.x where we can find `you can manage Same-Site directive from your PrestaShop BO > Préférences > General > Cookie SameSite` as it's not available can you please share screenshot. Thanks

**Comment by Matt75** [comment] 2022-01-23 19:32
@devphoenix2404 Cookie SameSite settings introduced in 1.7.8.0
![BO > Advanced Parameters > Administration](https://user-images.githubusercontent.com/5262628/150694889-cd5286d1-99f2-44dd-bc96-55fd8a443fc5.png)
