### ISSUE TITLE
Hello  I need your help please when i try to clear cache i get on backend ERRO 500 and php side 

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#12916] opened 2019-03-13 22:10 UTC
Hello

I need your help please when i try to clear cache i get on backend ERRO 500 and php side 

https://playstore.ma/phpinfo.php

https://playstore.ma/phpps.php
prestashop
prestashop

Version de PrestaShop : 1.7.5.1

```
2574#0: *119607 FastCGI s﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class 'Tools' not found in﻿ /var/www/vhosts//httpdocs/classes/db/Db.php:794
Stack trace:
#0 /var/www/vhosts//httpdocs/config/alias.php(48): DbCore->escape('configuration', false)
#1 /var/www/vhosts//httpdocs/config/alias.php(53): pSQL('configuration')
#2 /var/www/vhosts//httpdocs/classes/Configuration.php(155): bqSQL('configuration')
#3 /var/www/vhosts//httpdocs/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()
#4 /var/www/vhosts//httpdocs/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...')
#5 /var/www/vhosts//httpdocs/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()
#6 [internal function]: PrestaShopAutoload->load('Tools')
#7 /var/www/vhosts//httpdocs/config/config.inc.php(85): spl_autoload_call('Tools')﻿

#8 /var/www/vhosts//httpdocs/admin/index.php(42): require('/var/www﻿" while reading response header from upstream﻿﻿﻿



```

**Comment by khouloudbelguith** [comment] 2019-03-14 08:56
Hi @go-sudo,

Your ticket is a duplicate of #12667
So, I close it.
You can follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/12667#issuecomment-466330421) for temporary fix.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-14 08:56
Duplicate of #12667

**Closed as completed by khouloudbelguith** 2019-03-14 08:56 UTC
Labels: Duplicate
