### ISSUE TITLE
ps_imageslider - Images with invalid name are saved but not displaying correctly

### ISSUE THREAD

**Issue by Becold** [PrestaShop/PrestaShop#37452] opened 2024-11-24 18:15 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I uploaded an image with a specific name "-30% blackweek.jpg" but it is not displayed correctly.

![Image](https://github.com/user-attachments/assets/2020def1-920d-4869-a995-ab9e1c55d48d)

![Image](https://github.com/user-attachments/assets/a7ecfaec-b050-4f9d-92fe-3da6f9fdcb34)

### Expected behavior

Image is displayed correctly.
Invalid characters are stripped or replaced with valid character.

### Steps to reproduce

1. Go to module "Carousel" (ps_imageslider)
2. Create a new slide and upload an image named "-30%.jpg".
3. Save

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1.30

### If your bug is related to a module, specify its name and its version

ps_sliderimage v3.2.1

**Comment by florine2623** [comment] 2024-11-25 08:18
Hello @Becold ,

I reproduce the issue with PrestaShop version 8.2.0, 9.0.0 and module Image slider v3.2.1 I'll add this to the backlog so it can be fixed.

https://github.com/user-attachments/assets/a10de87d-351d-4206-b217-8a7f6f0727ad


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Codencode** [comment] 2024-11-25 16:00
The issue is caused by the % character in the file name.
I have created a PR that converts the file name using the `Tools::str2url()` function.
Here is the PR: https://github.com/PrestaShop/ps_imageslider/pull/112

**Closed as completed** 2024-12-10 16:08 UTC
Labels: Bug, Minor, FO, Imageslider, Verified, Module, 9.0.x
