### ISSUE TITLE
Notify in the bell order not appear yes for the  new users

### ISSUE THREAD

**Issue by v1per4llbl4ck** [PrestaShop/PrestaShop#32544] opened 2023-05-12 07:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

if i place an order i dont see a notify in the bell.. an i see this: Per ora nessun nuovo ordine :(
Have you checked your <strong><a href="https://.........................../....................................../index.php?controller=AdminCarts&action=filterOnlyAbandonedCarts&token=765a905f4c0cb555f860dd6c83c8b770">abandoned carts</a></strong>?<br>Your next order could be hiding there!

and i dont see notification
![Screenshot_58](https://github.com/PrestaShop/PrestaShop/assets/82314915/bc3f7a7e-6e2e-4dc5-91b2-e76375b5512c)
![Screenshot_57](https://github.com/PrestaShop/PrestaShop/assets/82314915/bab32457-aa64-44a0-a10a-abb9c15e6c0d)
![Screenshot_59](https://github.com/PrestaShop/PrestaShop/assets/82314915/3a26c574-55bb-46af-bb1e-a029ed5191f1)

### Expected behavior

im expected too see the same things on every page

### Steps to reproduce

1. open the bell in backoffice home page and i see not weel the traduuction
2. go to 1click upgrade module
3. now reopen the bell
4. i dont see the traduction because is in english
![Screenshot_58](https://github.com/PrestaShop/PrestaShop/assets/82314915/12193af2-ef03-4444-87b9-dbd43d016065)
![Screenshot_59](https://github.com/PrestaShop/PrestaShop/assets/82314915/d4aeeed9-96a6-45cf-926c-e899ac37fdad)
![Screenshot_57](https://github.com/PrestaShop/PrestaShop/assets/82314915/0385ec64-f70c-4f3b-b188-289818dc0d57)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

info@agworksolution.it

**Comment by hibatallahAouadni** [comment] 2023-05-15 23:51
Hello @v1per4llbl4ck 

The only issue I reproduced is #31268 see the attached screen record below:

[issue_32544.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/c35857da-3490-4f4f-ac1d-5f2252e2414d)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-06-04 22:23
Hello @v1per4llbl4ck 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed by hibatallahAouadni** 2023-06-04 22:23 UTC
Labels: Bug, Waiting for author, BO, NMI, Favicon notification BO, Module, 8.0.4
