### ISSUE TITLE
Missing Template when sending mail

### ISSUE THREAD

**Issue by thejoshualewis** [PrestaShop/PrestaShop#17873] opened 2020-02-27 15:07 UTC
@khouloudbelguith 

We are the module author, the issue is interacting with the core Prestashop using the mail functionality.  Does that block of code look correct, or is there somewhere that shows how to call this directly with explanations?
https://github.com/PrestaShop/PrestaShop/issues/17856

**Comment by khouloudbelguith** [comment] 2020-02-27 15:21
Duplicate of #17856

**Closed as completed** 2020-02-27 15:21 UTC
Labels: Duplicate
