### ISSUE TITLE
Fix error when updating a used address with no DNI

### ISSUE THREAD

**Issue by shaffe-fr** [PrestaShop/PrestaShop#18740] opened 2020-04-21 09:33 UTC
#### Describe the bug

When the DNI required settings is turned on, existing used addresses with no DNI cannot be updated.

#### Expected behavior

When I update the missing DNI field of an address used in an order, I expect the used address to be updated silently (with the deleted flag set to 1) and I expect a new address to be created.

#### Steps to Reproduce

1. Ensure that the DNI to not required for the default country in International > Locations > Countries (no dni in the address format and Do you need a tax identification number? set to No)
2. Create a customer address for this country
3. Create an order and use the address created at step 2
4. Set the DNI to required for the country's address in International > Locations > Countries (add dni to the address format and set Do you need a tax identification number? to Yes)
5. Update the customer address and fill the DNI field

![capture d'écran_2560](https://user-images.githubusercontent.com/13449658/80107383-49920780-857b-11ea-8a7f-83bf8e364ed7.png)

#### Additional information

* PrestaShop version: 1.7.7, develop
* PHP version: N/A

**Comment by shaffe-fr** [comment] 2020-04-21 09:35
A PR fix is available #18697

**Comment by sam-pires** [comment] 2020-04-22 16:06
@PrestaShop/prestashop-product-team  I think we should have a look at the expected behaviors to make sure we don't miss something. A PR is available, the sooner, the better.
ping @LouiseBonnard (you commented the PR ;))

**Comment by shaffe-fr** [comment] 2020-04-23 07:13
The annoying thing with this issue is that there is no workaround for shop administrators.

I did not test it, but there is maybe a similar bug when setting up required fields from the bottom of the addresses admin section. Should I create another issue or extend the scope of the issue and PR?

**Comment by LouiseBonnard** [comment] 2020-04-23 08:47
And the other issue is that the expected behavior regarding address formats does not seem to be specified on our end... does it only concern the DNI field or any other field lately set as required? We must investigate before making any decision, I'll try to do it by the end of the week. :-)

**Comment by marsaldev** [comment] 2020-04-23 08:55
I would add another problem, this behaviour happens also for the supplier address, if you set the DNI mandatory (and the supplier address doesn't have DNI) you'll receive an error when save it 😊
I think it's linked.
(the affected version are also the 1.7.6 and before)

**Comment by LouiseBonnard** [comment] 2020-04-23 09:12
Another nice inconsistency, aha, thanks for the feedback, @marsaldev! It seems to happen only for the DNI field... alright, let's change that!

**Comment by marionf** [comment] 2020-04-23 09:16
Guys, are we sure it's not a regression of the 1.7.7 ?

**Comment by marsaldev** [comment] 2020-04-23 09:36
To be more specific about the supplier, in the form (new or edit) you'll see also the DNI field and you need to write something 😊
Even more, if there is a module that makes check on that field you must insert a valid DNI XD

**Comment by LouiseBonnard** [comment] 2020-04-23 15:02
Hi all, the great @marionf has managed to reproduce this bug, see screenshot in the issue description. It is a regression, introduced by the 1.7.7. @shaffe-fr, would you mind rebasing your pull request on the 1.7.7.x branch? 

Regarding the required fields you can set at the end of the Customers > Addresses page, if you experienced the same bug, please open a new issue so that it can be qualified by the teams. ;-)

@marsaldev, we could not reproduce the same bug for suppliers, we guess it has been solved by #17305.

**Comment by shaffe-fr** [comment] 2020-04-24 12:46
Hi @LouiseBonnard, the PR is updated. 
About the required fields set in the database, I'll check if there is an issue and I'll create a new issue and PR.

**Comment by Progi1984** [comment] 2020-04-28 09:59
Fixed by #18697 (@shaffe-fr)

**Closed as completed by Progi1984** 2020-04-28 09:59 UTC
Labels: Bug, Minor, BO, Regression, Fixed, PR available, 1.7.7.x, 1.7.7.0

**Comment by shaffe-fr** [comment] 2020-04-29 10:18
Hi,
I just upgraded a PrestaShop from 1.7.5 to 1.7.6.5 and I was able to reproduce the bug on that branch.
@Progi1984, maybe the PR should be cherry-picked on the 1.7.6 branch?
