### ISSUE TITLE
Catalog page's products are in wrong order with child categories

### ISSUE THREAD

**Issue by AtteR** [PrestaShop/PrestaShop#15874] opened 2019-10-09 07:37 UTC
Products in catalog page do not follow the order set in Backoffice. If we go to product page in Backoffice and filter by categories and select category with child categories. Order here is right, ascending from 0. After we go to shop and select the same category from catalog, the order is completely different. If the category doesn't have any child categories, the order is right. Child categories seem to change order for some reason, and we can't figure out what is the logic how the ordering works.

1. Go to category with child categories in Backoffice
2. Check the order of products
3. Go to same category page in the shop
4. Order is completely different there
5. Position doesn't seem to work in categories with child categories

PrestaShop version: 1.7.6.1
PHP version: 7.2.19

**Comment by khouloudbelguith** [comment] 2019-10-09 08:10
Hi @AtteR,

The problem of the positions is fixed in the PS1.7.7.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14529 to fix the issue.
Your ticket is a duplicate of #14504
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-09 08:10
Duplicate of #14504

**Closed as completed by khouloudbelguith** 2019-10-09 08:10 UTC
Labels: Duplicate
