### ISSUE TITLE
Can not update product with combinations when disabled stock management in 8.0.1

### ISSUE THREAD

**Issue by Tobbewik** [PrestaShop/PrestaShop#31532] opened 2023-02-24 16:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I can not update a product with combinations when the stock management i disabled.
My installation of 8.0.1 is an update from earlier versions.

### Steps to reproduce

1. Create a product with combinations.
2. Disable Stock Management.
3. Try to update the product. (error)
4. Activate Stock Mgmt
5. Update product (works fine)

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.33

**Comment by hibatallahAouadni** [comment] 2023-02-25 10:48
Hello @Tobbewik 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #30179. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-02-25 10:48
Duplicate of #30179

**Closed as completed by hibatallahAouadni** 2023-02-25 10:48 UTC
Labels: Bug, Duplicate, Invalid
