### ISSUE TITLE
Ordering discounting products by price (FO)

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#12629] opened 2019-02-19 16:20 UTC
When sorting products by price in the front office, if a product has a specific price that greatly lowers the final price, this is displayed on a certain page based on the original price and, then, ordered on that page based on the discounted price.

For example, starting from a clean install:
1. Add a specific price to the product "Pack Mug + Framed poster" id_product: 15 with a discount of 85%;
2. Set "Products per page" to 6 in "Pagination";
3. In the Front-office enter the "Accessories" category id_category: 6;
4. Order by price in increasing order;
5. The item to which the specific price has been assigned should be shown in the first position (first page), instead it is shown as first product on the second page

The problem has always occurred with all versions of Prestashop and does not depend on the PHP version.

**Comment by khouloudbelguith** [comment] 2019-02-19 16:33
Hi @Codencode,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10010
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-19 16:33
Duplicate of #10010

**Closed as completed by khouloudbelguith** 2019-02-19 16:33 UTC
Labels: Duplicate
