### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by jannakz** [PrestaShop/PrestaShop#28374] opened 2022-04-29 03:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![registration error](https://user-images.githubusercontent.com/104608013/165879504-6bb83937-bdae-42ee-b588-98876b9c0cc2.png)

### Steps to reproduce

Cannot register new accounts

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.1

**Comment by jannakz** [comment] 2022-04-29 03:12
Cannot make a new accounts at site
Please help me to fix the issues

**Comment by HanaRebaiQA** [comment] 2022-04-29 12:17
Hello @jannakz 

Thanks for your report.
I was unable to reproduce your issue with 1785 and 178x 

https://user-images.githubusercontent.com/92912932/165942903-ce1f3a91-6f71-4524-a083-ccf469bb989e.mp4



Could you please provide us more information about the steps to reproduce with a screen-record ?

Thank you.

**Comment by hibatallahAouadni** [comment] 2022-05-18 15:53
Hello @jannakz 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-05-18 15:53 UTC
Labels: Bug, FO, Customer, 1.7.6.8, Invalid
