### ISSUE TITLE
Customer should know free shipping in cart when they used a coupon

### ISSUE THREAD

**Issue by FlorentinGarnier** [PrestaShop/PrestaShop#11746] opened 2018-12-12 11:21 UTC
**Describe the bug**
When customer have a coupon with reduction and free shipping, the free shipping is not display in Cart but a calcul that remove the shipping price. Customer think that the freeshiping is not take in account and scream to scam...

**To Reproduce**
1 - Create a reduce coupon with free shipping and tarif reduction.
2 - Enter Coupon Code
3 - Reduction calculate the freeshipping without display in clear "Shipping Free" in cart summary

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2018-12-12 11:33
Hi @florentingarnier,

Have you the same issue with this ticket: #11492?
Thanks!

**Comment by FlorentinGarnier** [comment] 2018-12-12 13:19
Okay this is the same issue
Thanks !!

**Comment by khouloudbelguith** [comment] 2018-12-12 13:24
Hi @florentingarnier,

We are aware of this issue.
Your ticket is a duplicate of #11492
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-12 13:25
Duplicate of #11492

**Closed as completed by khouloudbelguith** 2018-12-12 13:24 UTC
Labels: Duplicate, Discounts
