### ISSUE TITLE
High resolution product images are not displayed

### ISSUE THREAD

**Issue by jak78** [PrestaShop/PrestaShop#26599] opened 2021-11-14 16:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

My Prestashop Installation: 1.7.8.0, classic theme.
My products images in large format are displayed in low res. But I enabled the high resolution image generation.
When I inspect the HTML I can see that Prestashop generates the URL of the low-res image:

<img width="1180" alt="Capture d’écran 2021-11-14 à 17 16 58" src="https://user-images.githubusercontent.com/351773/141689196-b2ac02eb-c131-4f8d-890a-65cfe38245e9.png">

When I fix the URL in the inspector by adding `2x`:

<img width="1178" alt="Capture d’écran 2021-11-14 à 17 22 08" src="https://user-images.githubusercontent.com/351773/141689324-8506b9af-ca41-45ac-813b-9ab6ca5ace2b.png">

Then the image is displayed in high-res as expected.

### Expected behavior

@NeOMakinG 
We investigated with @Hlavtox and we think that the best solution would be to use the `picture` element with `srcset` so every pictures will adapt depending on the browser and the viewport

### Steps to reproduce

1. show a product image
2. click on the image to sse it large
3. observe that the image is in low-res

Tested on macOS Big Sur on:
- Firefox latest version
- Safari latest version
- Chrome latest version

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment] 2021-11-15 17:08
Hello @jak78 ,

I was able to reproduce the issue with PrestaShop version 1.7.8.0, so I can confirm that this behavior is indeed a bug.
In PS 1.7.7.7, it was working fine, so it is a regression.

In PS 1.7.7.7, before regenerating images - low res : 
<img width="798" alt="Screenshot 2021-11-15 at 18 06 18" src="https://user-images.githubusercontent.com/16019289/141823870-874915d8-02d6-4df6-a3c7-15f314c418bd.png">
After - high res :
<img width="799" alt="Screenshot 2021-11-15 at 18 06 11" src="https://user-images.githubusercontent.com/16019289/141823885-7df9986a-64f5-4d75-adb4-b8b7ad17bdad.png">

In PS 1.7.8.0, no change, low res images in product.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by jak78** [comment] 2021-12-05 22:31
Should be fixed by:
- https://github.com/PrestaShop/PrestaShop/pull/26877 on `develop`
- https://github.com/PrestaShop/PrestaShop/pull/26876 on `1.7.8.x`

**Comment by MatShir** [comment] 2021-12-13 14:16
@NeOMakinG, Could you help on this issue for the expected behavior? Do you think we could use the 'srcset' parameters on the theme to handle this issue? 🤔

**Comment by matks** [comment] 2021-12-23 09:52
@NeOMakinG is now enjoying some time off 😛 

Let's ask some other people skilled in frontend @PrestaShop/prestashop-maintainers

**Comment by Oksydan** [comment] 2021-12-23 10:13
I think we could introduce smarty function to render 2x images for generating src/srcset for retina.
Example of usage smarty function that generates srcset for retina and rendering other attributes for lazyload  https://github.com/Oksydan/is_themecore/blob/main/classes/SmartyHelperFunctions.php#L5 
Example of usage and results https://github.com/Oksydan/modern-prestashop-starter-theme#generateimagessources

OFC we can just make `{if $configuration.highDpiImagesEnabled}` (yes it isn't available in $configuration array) in smarty  and depending on that make changes in template. Smarty function have this advantage that we don't have to pollute our files with additional code.

**Comment by jak78** [comment] 2022-01-08 12:45
My pull requests won’t fix this issue properly. The required fix is too complex for me as I don’t understand Prestashop codebase well enough, so I won’t fix it, sorry

**Comment by NeOMakinG** [comment] 2022-01-09 12:12
Np, atleast you tried!

We investigated with @Hlavtox and we think that the best solution would be to use the `picture` element with `srcset` so every pictures will adapt depending on the browser and the viewport

**Comment by MatShir** [comment] 2022-01-10 16:59
@NeOMakinG I have updated the issue solution part, don't hesitate to complete it if needed.
Thanks guys for the investigation 👌

**Comment by NeOMakinG** [comment] 2022-01-11 08:12
@MatShir We've the same issue with the new theme, we need to improve the image system in order to give every information themes needs (jpg, png, webp, avif and every sizes corresponding (normal, x2, different sizes in order to load different images on responsive and deskop))

https://github.com/PrestaShop/theme-refacto/issues/147

Can we plan a meet with you or someone from the product team? It's a key feature to me and I would like that we prioritize it because it's really important and we need some back-end developers

**Comment by MatShir** [comment] 2022-01-21 10:46
From the discussion with @Hlavtox and @NeOMakinG, I will close this issue in favor for this EPIC https://github.com/PrestaShop/PrestaShop/issues/27318. This issue can't be solved easily, we need to solve the issue on a higher level.

**Closed as completed by MatShir** 2022-01-21 10:46 UTC
Labels: Bug, Minor, FO, Won't fix, Image, Regression, PR available, 1.7.8.0, Verified

**Comment by webstartconsulting** [comment] 2022-03-19 16:32
Hello! Any update from this bug? Anybody can help to resolve this? :)
