### ISSUE TITLE
Page title is not working on checkout page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23697] opened 2021-03-19 10:12 UTC
### Describe the bug

Page title entered in SEO & URL settings is not taken into account on order/checkout page. Shop name is displayed instead.

### Expected behavior

Page title should work and contain the title, as on all other controllers.

### Cause
This is how OrderController.php presents itself to Prestashop:
```
public $php_self = 'order';
public $page_name = 'checkout';
```
Then, in classes/controller/FrontController.php it uses **checkout** as a page name to find the meta, but the page meta are stored under **order** in meta settings and the databse. So it finds no meta information and uses shop name instead.
```
$page_name = $this->getPageName(); // This looks for page_name first, then for php_self
$meta_tags = Meta::getMetaTags($this->context->language->id, $page_name);
```

### Fix possibilities
- Removing **$page_name = 'checkout'** so it uses **$php_self = 'order'** or changing **$page_name** to **order** works, but causes some CSS to break, because they rely on **body id="checkout"**. But some small CSS tweaks in two files will solve this. In 1.6, the controller was also called **order**. Also, modules check only for php_self, not page_name, so no BC break there. This would only break some child themes.
- Renaming OrderController to CheckoutController is a suicide.
- If pagename = **checkout**, then search for **order** in meta table is a hackjob.

### Steps to Reproduce

1. Install 1.7.7
2. Go to checkout
3. See that shop name is displayed in page title, instead of "Order" or "Checkout"

### Screenshots

![meta title](https://user-images.githubusercontent.com/6097524/111764624-ae490580-88a3-11eb-9221-eaaa3572d4af.png)

### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by florine2623** [comment] 2021-03-19 13:15
Hello @Hlavtox ,
I was able to reproduce the issue with PrestaShop version develop, 1.7.7 and 1.7.6. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by hibatallahAouadni** [comment] 2021-03-22 07:56
Hello @Hlavtox 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10653. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-22 07:57
Duplicate of #10653

**Closed as completed by hibatallahAouadni** 2021-03-22 07:56 UTC
Labels: Bug, FO, Duplicate, Traffic & SEO, Checkout, 1.7.7.2
