### ISSUE TITLE
Update Prestashop to 1.7.8.11 via 1ClickUpgrade and all went OK, but I cannot access the backoffice

### ISSUE THREAD

**Issue by wwwwjapt** [PrestaShop/PrestaShop#35390] opened 2024-02-16 14:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

With the module 1 click upgade I have updated my shop: update went all the way with no errors.
I have running PHP 7.3 (I have tried 7.0, 7.1, 7.2 and 7.4 onwards, and did not allowed backoffice access (give different error)

Please see attached the errors showed with debug:
![20240215_1ClickUpgrade](https://github.com/PrestaShop/PrestaShop/assets/160248181/bf55f64d-273e-4090-b034-f25bdb8c7b77)
![20240215_erroAposUpdate](https://github.com/PrestaShop/PrestaShop/assets/160248181/02555d2a-a9ba-4cd6-b36e-4ea02cd08377)
![20240215_erroAposUpdateRouteNotFind](https://github.com/PrestaShop/PrestaShop/assets/160248181/1215c4fc-ff34-43fa-a568-d259d321e66a)
![20240215_erroAposUpdate_Logs](https://github.com/PrestaShop/PrestaShop/assets/160248181/829a57de-61ca-4e62-a136-5e8547b7f012)

I have clean the cache both on the browser and on the webpage (var\cache\dev)

Please help, as I now have the shop not available.

Best regards,
José.

### Expected behavior

I expected a normal login to the backoffice.

### Steps to reproduce

Go to www.ja.pt/admin123

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

Já Comprei, Já Usei, Já Vendi

**Comment by paulnoelcholot** [comment] 2024-02-21 11:21
Hello @wwwwjapt ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Also, versions of PrestaShop prior to version 8.0.x are no longer maintained.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-02-21 11:21 UTC
Labels: Bug, Can't reproduce, Invalid
