### ISSUE TITLE
500 server error on index

### ISSUE THREAD

**Issue by renochost** [PrestaShop/PrestaShop#14204] opened 2019-06-14 08:07 UTC
I was uploading the products on website through BO of prestashop, when I checked my website after uploading it showed me 500 Server Error, I had uploaded 3 products more before on the same time but that time the website was working properly, I have contact to my hosting provider also but they said there no issue from their hands. I don't know what the problem is & how to resolve this and even I am not a developer so I am unable to check the codings. Please kindly resolve this.

Below is the error log which is showing in the cpanel :-

- [14-Jun-2019 11:12:21 Asia/Calcutta] PHP Deprecated:  Function create_function() is deprecated in /home/mfb2qfltlsq9/public_html/shopping/modules/gamification/classes/GamificationTools.php on line 38

- [14-Jun-2019 11:12:21 Asia/Calcutta] PHP Deprecated:  Function create_function() is deprecated in /home/mfb2qfltlsq9/public_html/shopping/modules/gamification/classes/GamificationTools.php on line 39

- [14-Jun-2019 11:12:21 Asia/Calcutta] PHP Deprecated:  Function create_function() is deprecated in /home/mfb2qfltlsq9/public_html/shopping/modules/gamification/classes/GamificationTools.php on line 40

- [14-Jun-2019 11:12:21 Asia/Calcutta] PHP Deprecated:  Function create_function() is deprecated in /home/mfb2qfltlsq9/public_html/shopping/modules/gamification/classes/GamificationTools.php on line 41

- [14-Jun-2019 11:12:21 Asia/Calcutta] PHP Deprecated:  Function create_function() is deprecated in /home/mfb2qfltlsq9/public_html/shopping/modules/gamification/classes/GamificationTools.php on line 42

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-06-14 08:09
Hi @renochost,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-14 08:12
@renochost, about the warnings about the module gamification, here's the PR: https://github.com/PrestaShop/gamification/pull/61 to fix the issue.
Thanks!

**Comment by renochost** [comment] 2019-06-14 08:12
host
server setup and configuration
PrestaShop version (source)
debug mode report
PHP error logs
javascript console log

Sorry but I don't know how to get this things. Can you please help.

**Comment by khouloudbelguith** [comment] 2019-06-14 08:15
@renochost, don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by renochost** [comment] 2019-06-14 08:27
Server information Linux #1 SMP Wed May 2 07:43:19 EDT 2018 x86_64

Server software version: Apache
PHP version: 7.1.28

Database Information

MySQL version: 5.6.43-cll-lve

MySQL server: localhost

MySQL name: i5793684_pr2

MySQL user: i5793684_pr2

Tables prefix: pr_

MySQL engine: InnoDB

MySQL driver: DbPDO

PrestaShop Information

PrestaShop version: 1.7.5.2

Shop URL: http://www.renoc.in/shopping/

Current theme in use: ZOneTheme


![error_log in prestashop](https://user-images.githubusercontent.com/51604042/59495048-26eb8880-8eac-11e9-8f32-50509d3209d3.png)
![500 error](https://user-images.githubusercontent.com/51604042/59495124-4aaece80-8eac-11e9-9d36-6b876256d656.png)

**Comment by khouloudbelguith** [comment] 2019-06-14 08:31
@renochost, you need to enable debug mode in the BO => Advanced Parameters => Performances page, to display the exception.

Thanks!

**Comment by renochost** [comment] 2019-06-14 08:34
I have enabled the debug mode and now it showing this on my web page.


![Opera Snapshot_2019-06-14_140339_www renoc in](https://user-images.githubusercontent.com/51604042/59495640-5bac0f80-8ead-11e9-92a3-dde5b261381a.png)

**Comment by renochost** [comment] 2019-06-14 08:49
What happen taking too long please tell me what i have to do next

**Comment by khouloudbelguith** [comment] 2019-06-14 09:10
@renochost, the issue occurs due to the `zonehomeblocks` module.
![image](https://user-images.githubusercontent.com/16067358/59498006-728e3a00-8e8c-11e9-90d7-53aa59c2f09a.png)

As it's not the module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.

I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-14 09:10 UTC
Labels: Bug, BO, Import / Export, No change required, 1.7.5.2
