### ISSUE TITLE
HTML tag not closed properly in blockwishlist module

### ISSUE THREAD

**Issue by thomasnavarro** [PrestaShop/PrestaShop#24922] opened 2021-06-11 13:49 UTC
#### Describe the bug
Hi 👋
The <a> tag is not closed properly in the /views/templates/hook/account/myaccount-block.tpl template

#### Expected behavior

Closed the tag properly with `</a>`

#### Steps to reproduce

1. Go to '/views/templates/hook/account/myaccount-block.tpl'.
2. See the error line 24

![Capture d’écran 2021-06-11 à 15 46 43](https://user-images.githubusercontent.com/36193187/121696553-7a5d3500-cacc-11eb-81b3-cb3f44e4fd40.jpg)

**Comment by florine2623** [comment] 2021-06-11 15:00
Hello,

I was able to reproduce the issue with module blockwishlist v2.0.1, so I can confirm that this behavior is indeed a bug.
https://github.com/PrestaShop/blockwishlist/releases/tag/v2.0.1 
<img width="489" alt="Screenshot 2021-06-11 at 16 59 27" src="https://user-images.githubusercontent.com/16019289/121707098-86e68b00-cad6-11eb-9f72-8b7c17ab0491.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2021-06-14 17:40 UTC
Labels: Bug, Minor, CO, Fixed, Blockwishlist

**Comment by hibatallahAouadni** [comment] 2021-06-15 08:13
Reproduced with blockwishlist v2.0.0 and PS1.7.6.7
