### ISSUE TITLE
Bug with ps_facetedsearch when PS_LAYERED_FULL_TREE set to NO

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#24913] opened 2021-06-10 22:01 UTC
#### Describe the bug

When the PS_LAYERED_FULL_TREE option is set to NO the products displayed using a ps_facetedsearch subcategory filter are not correct.

#### Expected behavior

I expect to have product filtered and only display products that are associated with the selected subcategory.

#### Steps to Reproduce

1. Set the PS_LAYERED_FULL_TREE option to NO in the ps_facetedsearch configuration panel

<img width="743" alt="Capture d’écran 2021-06-10 à 23 56 12" src="https://user-images.githubusercontent.com/167037/121602358-789d5e00-ca47-11eb-9b0e-34291d0a6f7d.png">

2. Filter products by a subcategory
3. Products that are displayed are incorrect

In modules/ps_facetedsearch/src/Product/Search.php file ([line 103](https://github.com/PrestaShop/ps_facetedsearch/blob/a62590c46171053724c97054c5867398f00fa56e/src/Product/Search.php#L103))

`$psLayeredFullTree = Configuration::get('PS_LAYERED_FULL_TREE');`

You are adding a filter if the option is set to NO. I don't understand why 🤔

#### Additional information

* PrestaShop version: v1.7.6.3
* PHP version: v3.7.1

Regards,

David.

**Comment by florine2623** [comment] 2021-06-11 07:47
Hello @Daaaaad ,

Using PS 1.7.6.3 and module Faceted Search v3.7.1 by PrestaShop, I can't reproduce your issue.
Please check my screenshot below :
_**Same config as you mentioned :**_
<img width="632" alt="Screenshot 2021-06-11 at 09 43 23" src="https://user-images.githubusercontent.com/16019289/121650337-c347c600-ca99-11eb-9f5d-38445dcfbd43.png">
**_The products in BO :_**
<img width="1183" alt="Screenshot 2021-06-11 at 09 43 33" src="https://user-images.githubusercontent.com/16019289/121650412-d8245980-ca99-11eb-9f34-77dc1a5d152c.png">
**_The result in FO :_**
<img width="1135" alt="Screenshot 2021-06-11 at 09 43 50" src="https://user-images.githubusercontent.com/16019289/121650422-d9ee1d00-ca99-11eb-9456-4160196da2cb.png">

Can you give more details on the issue please ?

Thanks !

**Comment by hibatallahAouadni** [comment] 2021-07-01 10:58
Hello @Daaaaad 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-01 10:58 UTC
Labels: Bug, BO, FO, Categories, Faceted search, No change required, 1.7.6.3
