### ISSUE TITLE
[BO] Mismatch between default-theme and new-theme for RTL languages

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26017] opened 2021-09-28 10:15 UTC
Hello,

#### Describe the bug

There is two themes for back-office, default and new-theme:
public_html/admin/themes/default
public_html/admin/themes/new-theme

Some pages works with default-theme and some pages works with new-theme.
I checked RTL version of default-theme and new-theme source codes (theme.rtlfix) and i found some problems:
1. Mismatch: Some CSS rules not exported from default-theme to new-theme (Rules that fixes RTL direction and Persian Fonts definition)
2. Outdated: Persian fonts defined in default-theme are outdated and need to update (Used: V18, Current: [V30](https://github.com/rastikerdar/vazir-font))

#### Expected behavior

Themes should to be synchronized to looks same everywhere in back-office.

#### Steps to Reproduce

(1) Steps to reproduce the behavior (**Arabic/Persian**):

1. Go to BO > Products
2. Edit a product
3. See categories list

<img src="https://user-images.githubusercontent.com/85633460/135064692-b6fc5fdc-6447-48d5-94e0-887b0e171bde.png" width="340"/>

(2) Steps to reproduce the behavior (**Persian**):
_(Persian language needs to be selected as default language for BO)_

1. Go to BO > Employees
2. Edit Admin account
3. Select Persian for language
4. See the main menu font (new-theme)
5. Go to BO > Dashboard
6. See the main menu font (default-theme)

Different font faces for different pages:

<img src="https://user-images.githubusercontent.com/85633460/135073400-a418d395-953b-4a19-a61e-14263e561c89.png" width="600"/>

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by florine2623** [comment] 2021-09-28 10:44
Hello @mparvazi ,

For your first issue I managed to reproduce it in PS 1.7.8.x :

<img width="305" alt="Screenshot 2021-09-28 at 12 42 54" src="https://user-images.githubusercontent.com/16019289/135072588-ba747a71-1f5b-4737-85c0-2d41b11863a5.png">

Only classic template is available :
<img width="1199" alt="Screenshot 2021-09-28 at 12 42 18" src="https://user-images.githubusercontent.com/16019289/135072481-6b41ddc6-ccf6-4b32-81ea-2880443063d8.png">
Which template are you using ?

**Comment by mparvazi** [comment] 2021-09-28 11:01
Hello @florine2623,

This problem is related to admin theme for Persian language.

In BO by selecting Persian as default language for back-office you can see the problem, different font faces for different pages. 
_Employees > Admin > Language (Persian)_

I think the screenshot that you sent is related to front-office theme. 

Theme style for RTL languages in BO are coded in css files:
1. public_html/admin/themes/default/public/theme.rtlfix
2. public_html/admin/themes/new-theme/public/theme.rtlfix

Btw these two files must be matched to show the same view on all RTL back-office pages.

**Comment by florine2623** [comment] 2021-09-28 16:43
Thanks for the details.

I have the same behavior in my PS 1.7.8.x shop :
Dashboard page :
<img width="214" alt="Screenshot 2021-09-28 at 18 40 51" src="https://user-images.githubusercontent.com/16019289/135129769-67499e43-381e-4c5b-ae5e-61defe31e2b3.png">
Employee page :
<img width="199" alt="Screenshot 2021-09-28 at 18 40 56" src="https://user-images.githubusercontent.com/16019289/135129790-969b12cc-650e-42e8-becb-c71da94d64fe.png">

I think this the normal behavior, as one page is legacy and the other is not.
I'll ping a dev to get a confirmation. Please stay tuned.

**Comment by florine2623** [comment] 2021-09-28 16:44
ping @PrestaShop/prestashop-core-developers & @NeOMakinG ,

What do you think about @mparvazi 's issue ? Is it the normal behavior ?
Thanks !

**Comment by NeOMakinG** [comment] 2021-09-29 07:43
Hey @mparvazi @florine2623 

It looks like it's not a normal behavior :)

We worked on default styling to match with new theme, but this is a miss and should be fixed tbh!

**Comment by mparvazi** [comment] 2021-09-29 08:48
Hello @NeOMakinG

I can fix this issue. I made these changes on my store for **theme.rtlfix** files and the problem was solved.

Two changes are needed:

1. New font face definition for Persian language ([Vazir v30.1.0](https://github.com/rastikerdar/vazir-font) An Optimized Persian font for web)
2. Exporting missed css rules from legacy to new theme

If you want me to make these changes as a PR, please inform me about that, I would be happy!

**Comment by NeOMakinG** [comment] 2021-09-29 08:57
@mparvazi Feel free, it would be awesome :)

We need to define if it needs to be fixed on 1.7.8.x branch or on develop @PrestaShop/product-team

**Comment by marionf** [comment] 2021-09-29 09:05
@neomaking it seems that this issue isn't a regression of the 1.7.8, so the PR can be done on develop ;)

**Comment by itsvahid** [comment] 2021-09-29 17:20
Hi
It's also related to this issue I had opened #25785

**Comment by marionf** [comment] 2021-11-05 09:34
@Progi1984 It doesn't seem to be a regression of the 1.7.8.0, why did you add to the 1.7.8.1 milestone?

**Closed as completed** 2022-01-10 17:30 UTC
Labels: Bug, Minor, BO, Theme & logo, Languages, Front-end, PR available, 1.7.8.0
