### ISSUE TITLE
Stock moving quantity editing is taking zero, generating human error

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#27736] opened 2022-02-18 20:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In version 1.7.7.x when entering Catalog - Stocks, when editing the quantity of a reference, it did not take into account the number zero, if 1 was entered, only one remained. In version 1.7.8.3 the zero must be deleted since by not doing so and typing the 1, the quantity remains with 10 units, this generates human errors.

https://drive.google.com/file/d/11A5QJGVbrBDVGuOB5sAYCkQzVj4o1Z38/view?usp=sharing

### Expected behavior

It should behave as in version 1.7.7.5. when placing any number, it did not take into account the number 0.

### Steps to reproduce

1. Catalog - Stocks
2. Add a one as quantity without deleting the zero.
3. Take as 10 in quantity and not 1 when applying the new quantity.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-02-21 08:52
Hello @ocio87 

I reproduce the issue with PS1780 and above, it's a regression!

https://user-images.githubusercontent.com/23308427/154920475-df5fd650-b914-46a5-8d84-7313b682f952.mp4

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2022-03-09 14:19
Fixed by @jolelievre in #27776

**Closed as completed by Progi1984** 2022-03-09 14:19 UTC
Labels: Bug, Minor, BO, Stocks, Regression, Fixed, Front-end, PR available, 1.7.8.0
