### ISSUE TITLE
When I edit a product in the Backoffice return 500 error server

### ISSUE THREAD

**Issue by lewis2413** [PrestaShop/PrestaShop#12483] opened 2019-02-07 13:44 UTC
Hi,

I have a problem when I edit a product in the backoffice, return 500 server error:

![image](https://user-images.githubusercontent.com/47395448/52414905-d91dd880-2ae5-11e9-8fca-ba3749d8a47b.png)

my setup and configuration is the following:

![image](https://user-images.githubusercontent.com/47395448/52414855-b4c1fc00-2ae5-11e9-938d-9d91a6651e83.png)

Error log from var/logs path
[prod.log](https://github.com/PrestaShop/PrestaShop/files/2841026/prod.log)

--------------------------

the hosting where shop is allocated is a shared server and i don´t have access to php_error_logs neither apache_error_logs files.

I don´t know if this information is enough or you need anymore.

thanks advance

**Comment by khouloudbelguith** [comment] 2019-02-07 13:52
Hi @lewis2413,

In your log file, you have this error: `Error: Allowed memory size of 268435456 bytes exhausted`, have you tried to contact with your host about this issue?
Thanks to check with them & feedback.
In the meantime, could you please try to enable the debug mode & provide me the exceptions displayed?
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 14:01
I´ve not contact with them, i do it now, the hosting provider is called Arsys, i don´t know if you know it.  By the way, I have enabled debug mode and don´t show anything in my screen.

attach the dev.log file

[dev.zip](https://github.com/PrestaShop/PrestaShop/files/2841133/dev.zip)

**Comment by khouloudbelguith** [comment] 2019-02-07 14:27
@lewis2413, so when debug mode is enabled & you navigate to the product page, only error 500 is displayed?
THanks!

**Comment by lewis2413** [comment] 2019-02-07 14:29
Yes only that
*--*

*Saludos Cordiales*


*Ing. Jose Luis Idrogo*
Movil: +34 678 878385
Email: joseluis.idrogo@edisa.com
Web Site: http://www.edisa.com/
* <http://www.edisa.com/>*
*MADRID - BARCELONA - VIGO - OVIEDO - OURENSE - LAS PALMAS - MEXICO -
COLOMBIA - ECUADOR - REP. DOMINICANA - PANAMÁ*
*------------------------------CONFIDENCIALIDAD:* Este mensaje se dirige
exclusivamente a su destinatario y puede contener información privilegiada
o confidencial. Si no es vd. el destinatario indicado, queda notificado de
que la utilización, divulgación y/o copia sin autorización está prohibida
en virtud de la legislación vigente. Si ha recibido este mensaje por error,
le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda
a su destrucción.

Antes de imprimir este mensaje, asegúrate de que es necesario. Proteger el
medio ambiente está también en tu mano.

**Comment by khouloudbelguith** [comment] 2019-02-07 14:32
@lewis2413, in your log file, `doctrine.DEBUG: SELECT name FROM ps_module WHERE active = 1 [] []`, it could be a problem with a custom module but it is not mentioned.
THanks!

**Comment by lewis2413** [comment] 2019-02-07 14:55
umm when you say custom module, it could be a template that is not the default? We have a new template

**Comment by lewis2413** [comment] 2019-02-07 15:01
Checking the Symfony Profile I found this:

![image](https://user-images.githubusercontent.com/47395448/52419959-716d8a80-2af1-11e9-9bf4-707b2327ef14.png)


and the logs, i found this too

![image](https://user-images.githubusercontent.com/47395448/52420035-8e09c280-2af1-11e9-962d-233a20e6582f.png)

**Comment by khouloudbelguith** [comment] 2019-02-07 15:02
@lewis2413, before uploading the new theme, the issue doesn't exist?
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 15:06
I don´t test it

**Comment by lewis2413** [comment] 2019-02-07 15:07
Sorry, i didn´t test it

**Comment by khouloudbelguith** [comment] 2019-02-07 15:11
@lewis2413, so some issues with translations, did you created any languages or did you imported any pack from the BO?
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 15:15
I don´t have created any languages, the only thing that i have done is install a laguage package

**Comment by khouloudbelguith** [comment] 2019-02-07 15:22
@lewis2413, from the BO => International => Translations => you added your language?
![image](https://user-images.githubusercontent.com/16067358/52421571-97485e80-2af4-11e9-8314-1fc79e5176bd.png)

**Comment by lewis2413** [comment] 2019-02-07 15:26
Yes, i have added it

**Comment by khouloudbelguith** [comment] 2019-02-07 15:59
@lewis2413, sorry, but I did not manage to reproduce the issue with PS1.7.5.0, you need to check if you have an override incompatible or a custom module may cause a problem.
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 16:03
How to check if i have an incompatible module in my lastest prestashop version?

**Comment by khouloudbelguith** [comment] 2019-02-07 16:09
@lewis2413, try to disable one by one manually, check & feedback.
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 16:11
only the modules from  the new template, rigth?

**Comment by khouloudbelguith** [comment] 2019-02-07 16:16
@lewis2413, modules which they are related to the product page.
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 17:05
Ok, BTW, provider hosting have extended the memory limit from 256 to 512MB and  it works for me, the load´s time is 20seg only show the frontend but it continue loading yet.


![image](https://user-images.githubusercontent.com/47395448/52428748-ebf2d600-2b02-11e9-8f53-02aeda741844.png)

**Comment by khouloudbelguith** [comment] 2019-02-07 17:07
@lewis2413, so the issue is fixed?
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 17:09
well, if i check error log, i look translation errors, the commented above.

**Comment by lewis2413** [comment] 2019-02-07 17:12
this is solved but not totally.

**Comment by khouloudbelguith** [comment] 2019-02-07 17:17
@lewis2413, could you please try to update the Espanol language again from the BO => International => Translations.
Thanks!

**Comment by lewis2413** [comment] 2019-02-07 17:19
i just updated

**Comment by lewis2413** [comment] 2019-02-07 17:23
when the page is loaded, the features are loading very slow one by one

![image](https://user-images.githubusercontent.com/47395448/52430001-691f4a80-2b05-11e9-9d3d-405814e86fda.png)

**Comment by khouloudbelguith** [comment] 2019-02-07 17:26
@lewis2413, could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by lewis2413** [comment] 2019-02-07 17:55
I don´t look the httpdoc directory


![image](https://user-images.githubusercontent.com/47395448/52432095-e1880a80-2b09-11e9-80ed-636d50f1c2b1.png)

**Comment by lewis2413** [comment] 2019-02-07 18:16
this is the report


[PHP PrestaShop Info.zip](https://github.com/PrestaShop/PrestaShop/files/2842156/PHP.PrestaShop.Info.zip)

**Comment by khouloudbelguith** [comment] 2019-02-08 09:21
Hi @lewis2413, your configuration seems to be OK.
Could you please provide me your credentials to access your BO to check it.
This is a public space.
You can provide me the link by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by lewis2413** [comment] 2019-02-08 09:25
Hi @khouloudbelguith 

i just sent the information requested.

**Comment by khouloudbelguith** [comment] 2019-02-08 09:29
@lewis2413, I just received the email, I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-08 09:54
@lewis2413, I tried to add/edit a product & it is OK.
I sent you a screen record via Email.
Thanks!

**Comment by lewis2413** [comment] 2019-02-08 10:06
Yes I´ve received, but try to test with products that they are there. for example 731 only click in modify button and check loading time. Each product have 43 features aprox.

**Comment by khouloudbelguith** [comment] 2019-02-08 10:19
@lewis2413, thanks for your feedback.
We are aware of this issue and we are working on it.
No, this issue is in progress, it is assigned to our developer Jocelyn Fournier, he is working on it.
Thanks for your patience
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-08 10:19
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2019-02-08 10:19 UTC
Labels: Bug, BO, Duplicate, 1.7.5.0

**Comment by lewis2413** [comment] 2019-02-08 10:21
All rigth, thansks to you.

**Comment by lewis2413** [comment] 2019-02-08 16:19
hi @khouloudbelguith 

the issue commented above is in progress? are there any solution?

**Comment by khouloudbelguith** [comment] 2019-02-08 16:21
@lewis2413, the issue is in progress.
This is not something we can easily fix.
Thanks for your understanding!

**Comment by lewis2413** [comment] 2019-02-08 16:25
Ok, i undestand, i´ll hope for you response...

Thansk for you support
