### ISSUE TITLE
Administration area Dashboard day/month/year buttons not work.

### ISSUE THREAD

**Issue by makitlas** [PrestaShop/PrestaShop#26739] opened 2021-11-24 18:43 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Day & month & year buttons not work. Nothing happens when buttons are pressed.

### Expected behavior

Change date

### Steps to reproduce

Administration area Dashboard

### PrestaShop version(s) where the bug happened

PS 1.7.8.0 Multistore

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment] 2021-11-25 11:45
Hello @makitlas 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25966. 
It has been fixed on PS1.7.8.1 :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-25 11:46
Duplicate of #25966

**Closed as completed by hibatallahAouadni** 2021-11-25 11:45 UTC
Labels: Bug, Duplicate, Invalid
