### ISSUE TITLE
Impossible to delete feature added in the product page if they are not linked to an existing feature

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/PrestaShop#19012] opened 2020-05-06 15:19 UTC
#### Describe the bug

If you create a feature in a product page "Add a new feature" and give it a custom value, **but without selecting an existing feature** then it is impossible to delete it after

In addition to no being able to delete it, it seems to impact existing and fine features by applying the custom value of the created feature to all the features' values.

#### Expected behavior

On the product page. You should have to select a feature. You should not be able to let the "Feature" on the default placeholder value?

#### Steps to Reproduce

1. Go to 'Catalog > products > select any product'
2. In the product page, on the first tab, click on 'Add a feature'
3. For "Feature" and "Pre-defined value", select "Choose a feature" and add a custom value
4. Save
5. go to another page and come back to the product page
6. See the feature you created, delete it and save
7. Go to another page and come back, the feature still exist.

**Screenshots**

See the video:
https://drive.google.com/file/d/1nZPWLhODwa9FQlvmK2aHRDWNPVEy8O1W/view

#### Additional information

* PrestaShop version: 1.7.6.5

**Comment by sam-pires** [comment] 2020-05-06 15:23
@TristanLDD and @marionf maybe it is something you've already identified on the product page. Let me know 🙂

**Comment by marionf** [comment] 2020-05-06 15:36
@sam-pires Yes, I created an issue about that some times ago: https://github.com/PrestaShop/PrestaShop/issues/16306

**Comment by marionf** [comment] 2020-05-11 13:18
Duplicate of #16306

**Closed as completed by marionf** 2020-05-11 13:18 UTC
Labels: Bug, BO, Duplicate, Features
