### ISSUE TITLE
Optional field are compulsary without reason and give HTTP 500 error

### ISSUE THREAD

**Issue by Benla79** [PrestaShop/PrestaShop#10860] opened 2018-10-04 12:36 UTC
**Describe the bug**
For account registration, the fields, company, adress2, phone are compulsary and if not entered an **error HTTP 500** occurs.
I checked in Client/address and nothing is checked.

It should not be compulsary...

**To Reproduce**
1. Go to 'create an account'
1. Go to 'checkout'
2. enter 'name, adress, postcode, city,..'
3. Click on 'continue'

**Screenshots**
![2018-10-01 1](https://user-images.githubusercontent.com/43850197/46474280-c0717f00-c7e2-11e8-9b02-015d6093424c.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-04 13:16
Hi @Benla79,

Thanks for your report.
You should add the company field in the format address => Go to => International > Locations > Edit your country and add the field in the address format for your country.
The issue is fixed in the PS version 1.7.3.0.
Here is a PR: https://github.com/PrestaShop/PrestaShop/pull/8435
https://github.com/PrestaShop/PrestaShop/pull/7975
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by Benla79** [comment] 2018-10-04 13:40
Hi @khouloudbelguith
I did what you said and it took away the fields address 2, company, phone (but I still need them optional).
But even if I do it and click on "continue" I have the same HTTP 500 with the same screenshot as above...

![2018-10-04 5](https://user-images.githubusercontent.com/43850197/46477802-cd46a080-c7eb-11e8-82ce-07c4c87b511c.png)

**Comment by Benla79** [comment] 2018-10-04 13:45
Here you can see:
![2018-10-04 6](https://user-images.githubusercontent.com/43850197/46478110-89a06680-c7ec-11e8-843c-3838f1e2f4f1.png)

**Comment by khouloudbelguith** [comment] 2018-10-04 13:46
@Benla79, you need to navigate International > Locations > Edit your country and add these fields (address 2, company, phone ) in the address format for your country.
Also, you need to navigate to BO => Customers => Addresses => Click on " Set required fields for this section" & uncheck these fields.
![image](https://user-images.githubusercontent.com/16067358/46478190-afc60680-c7ec-11e8-812e-738a53ea76bd.png)

**Comment by Benla79** [comment] 2018-10-04 13:49
Unfortunately, they are not checked!

**Comment by Benla79** [comment] 2018-10-04 14:24
![2018-10-04 7](https://user-images.githubusercontent.com/43850197/46480689-05e97880-c7f2-11e8-9c55-4e0b770eadfb.png)

**Comment by Benla79** [comment] 2018-10-04 15:26
It acts as if all of the fiels were checked but in fact aren't...

**Comment by khouloudbelguith** [comment] 2018-10-04 15:42
@Benla79, did you use the default theme provided by PrestaShop?

**Comment by Benla79** [comment] 2018-10-04 15:49
@khouloudbelguith 
No I use a different theme.
But it still does the same with the default theme.

**Comment by khouloudbelguith** [comment] 2018-10-04 15:53
@Benla79, you have fields not checked as required in BO => But they are required in the FO?
Did you make the test with both default theme & custom theme?

**Comment by Benla79** [comment] 2018-10-04 15:55
Yes I made the test with both default theme & custom theme.

Yes, I have fields not checked as required in BO => But they are required in the FO (even though it is written optional)!!

**Comment by Benla79** [comment] 2018-10-04 15:58
For example, I have this:
![2018-10-04 11](https://user-images.githubusercontent.com/43850197/46486857-ec026280-c7fe-11e8-85bb-37414af69af4.png)
and If I press continue, I have:
![2018-10-04 12](https://user-images.githubusercontent.com/43850197/46486918-0e947b80-c7ff-11e8-9512-00a345d824a7.png)

**Comment by khouloudbelguith** [comment] 2018-10-04 16:01
@Benla79, you need to navigate International > Locations > Edit your country and add this field (address 2) in the address format for your country.
![image](https://user-images.githubusercontent.com/16067358/46487124-8d89b400-c7ff-11e8-8c8f-dfcbc6c6c5d9.png)
Thanks to add this field & feedback.

**Comment by Benla79** [comment] 2018-10-04 16:02
It is.

**Comment by khouloudbelguith** [comment] 2018-10-04 16:03
@Benla79, it is added in the address format?

**Comment by Benla79** [comment] 2018-10-04 16:04
![2018-10-04 13](https://user-images.githubusercontent.com/43850197/46487293-f3763b80-c7ff-11e8-95a5-60f19e101814.png)

**Comment by khouloudbelguith** [comment] 2018-10-04 16:27
@Benla79, could you please check your file AddressFormat.php into the path Project_Folder/classes/AddressFormat.php, the list of requireFormFieldsList.
![image](https://user-images.githubusercontent.com/16067358/46488500-20781d80-c803-11e8-80db-2222f9fd8f2b.png)
Thanks to check & feedback.

**Comment by Benla79** [comment] 2018-10-04 16:33
Seems good
![2018-10-04 14](https://user-images.githubusercontent.com/43850197/46488766-eeb38680-c803-11e8-8b38-f82f92fee7ca.png)

**Comment by khouloudbelguith** [comment] 2018-10-04 16:42
@Benla79, now could you please check your database => the PREFIX_address_format, what is the exact format of your country (you need to check your id's country)
PS: PREFIX is the prefix of your tables, t could be for example ps.

**Comment by Benla79** [comment] 2018-10-04 16:47
@khouloudbelguith , it is:
firstname lastname
company
vat_number
address1
address2
postcode city
Country:name
phone

**Comment by khouloudbelguith** [comment] 2018-10-04 16:53
@Benla79, sorry but I did not manage to reproduce this issue with PS1.7.4.2
This issue is fixed in the PS version 1.7.3.0.
Here is a PR: #8435, #7975
@marion what do you think?

**Comment by marionf** [comment] 2018-10-05 08:00
Yes, this issue has been fixed in 1.7.3.0 and I can't reproduce it on 1.7.4.3

**Closed as completed by marionf** 2018-10-05 08:00 UTC
Labels: Bug, FO, Can't reproduce, Addresses, 1.7.4.2

**Comment by Benla79** [comment] 2018-10-05 08:02
@marionf 
Thank you for trying. I see you closed the topic so what should I do? Does that mean I have to start over, erase all and restart?
