### ISSUE TITLE
Brands are shown wrongly in the FO

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#25214] opened 2021-07-02 11:23 UTC
#### Describe the bug

Brands with description and links are shown wrongly in the FO. Links are not available.

Example:
**1) Brand without description:**
BO:
![image](https://user-images.githubusercontent.com/38213520/124265604-3216bd00-db36-11eb-972c-a5519d796f7d.png)
FO:
![image](https://user-images.githubusercontent.com/38213520/124265627-3b078e80-db36-11eb-860d-240b8e73aff4.png)
Logo, Link: Fashion manufactured have link: domain.com/1_fashion-manufacturer - **This is correct behavior.**

**2) Brand with description:**
BO:
![image](https://user-images.githubusercontent.com/38213520/124265779-7efa9380-db36-11eb-9dc4-6ba805bdf666.png)
link 1 (Link to the product 1): domain.com/tshirts/1-1-faded-short-sleeves-tshirt.html#/1-velikost-s/13-barva-oranzova
link 2 (Product 2): domain.com/summer-dresses/7-printed-chiffon-dress.html
_Inserted code:_
`<p>Text Text Text Text Text Text Text Text Text Text Text for example: <a href="https://domain.com/tshirts/1-1-faded-short-sleeves-tshirt.html#/1-velikost-s/13-barva-oranzova">Link to the product 1</a> and <a href="https://domain.com/summer-dresses/7-printed-chiffon-dress.html">Product 2</a></p>`  

FO:
![image](https://user-images.githubusercontent.com/38213520/124266041-bf5a1180-db36-11eb-8d1d-bba312733f75.png)
Logo, text Fasion Manufacturer contain link to **domain.com/summer-dresses/7-printed-chiffon-dress.html** (last link in the description) - **this is wrong!** 

**Correct link is domain.com/1_fashion-manufacturer**

Second problem is Links to the product 1 and Product 2 are not available/clickable. There is last url from description: domain.com/summer-dresses/7-printed-chiffon-dress.html

Thank you
Best regards
PN
#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.27-1~deb10u1

**Comment by khouloudbelguith** [comment] 2021-07-02 11:56
Hi @PeNov,

Thanks for your report.
I was able to reproduce the issue with PrestaShop version 1.7.7.5. 
In fact, links are ok, but they are not clickable
![image](https://user-images.githubusercontent.com/16067358/124270713-dbf94800-db3c-11eb-8e0d-3f216f1501f7.png)
It seems related to this PR: https://github.com/PrestaShop/PrestaShop/pull/16857

With PS1765 => ok
![image](https://user-images.githubusercontent.com/16067358/124270909-1531b800-db3d-11eb-9d14-7edfd83495f9.png)


I'll add this to the debug backlog so that it's fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 
If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by Progi1984** [comment] 2021-07-08 14:47
Fixed in #25216 by @NeOMakinG

**Closed as completed by Progi1984** 2021-07-08 14:47 UTC
Labels: Bug, Minor, FO, Brands, Regression, Fixed, Front-end, PR available, 1.7.7.4, 1.7.7.5
