### ISSUE TITLE
PS 1.7.5.2 carrier ID increase after each save...

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14063] opened 2019-06-03 22:05 UTC
Go to Carriers and edit My Carrier with ID = 2. After save My Carrier will have ID = 3, next edit and save ID = 4 etc...

Then go to first Carrier with ID =1 and save. He will get ID = 5...

Thats huge regression

-------------

Also weird problem with assigment payment method with shipping options... After making changes Payment options totally disapear on front office. Payment/s module reset help to show them again but assigment is not working.

**Comment by khouloudbelguith** [comment] 2019-06-04 07:38
Hi @PrestaShark,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9592
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-04 07:38
Duplicate of #9592

**Closed as completed by khouloudbelguith** 2019-06-04 07:38 UTC
Labels: Duplicate
