### ISSUE TITLE
ps_emailalerts has problems with same products and different customizations

### ISSUE THREAD

**Issue by arkadiusz-kozub** [PrestaShop/PrestaShop#17327] opened 2020-01-23 13:20 UTC
When client orders same product (same id and attribute_id) couple of times, but each time provides different customization, module ps_emailalerts combine all customizations and puts it to each posision in {items} table. It looks like that: 

![image](https://user-images.githubusercontent.com/60222171/72987039-d648f000-3de9-11ea-9976-4b168b0b3d5b.png)

I know - it's different language, but i think it's readable.

I've traced the issue in ps_emailalerts.php file, line 291 and so one. It uses
```
$customized_datas = Product::getAllCustomizedDatas((int) $params['cart']->id);
$customized_datas[$product['product_id']][$product['product_attribute_id']][$order->id_address_delivery];
```

instead of 

`$customized_datas = $product['customizedDatas'][$order->id_address_delivery][$product['id_customization']];`

I tested it on Prestashop 1.7.4.4 and PHP > 7

**Comment by khouloudbelguith** [comment] 2020-01-23 13:31
Hi @arkadiusz-kozub,

We are aware of this issue, it is added to our debug roadmap.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Your ticket is a duplicate of #16551. 
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-23 13:31
Duplicate of #16551.

**Closed as completed by khouloudbelguith** 2020-01-23 13:31 UTC
Labels: Duplicate, Product customization, ps_emailalerts
