### ISSUE TITLE
BO > Positions : Can't change the hook on develop

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#28149] opened 2022-04-06 12:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you want to change an hook on BO>Deisgn>Position in develop, you've an exception, we search a file name form.tpl and, as my knowledge, this file has never existed. 

You can see this exception  on this video

https://user-images.githubusercontent.com/100699445/161978454-98c585c3-1e72-4c8c-93f2-ceeb3346c134.mp4

On 1.7.8.5 -> Ok  

### Expected behavior

We want this type of page : 

![image](https://user-images.githubusercontent.com/100699445/161977821-1e2237ea-b1a8-4869-8a3b-95b8d04a3d56.png)

### Steps to reproduce

1. Install a shop with develoo
2. Go to BO
3. Go to Design > Position
4. Click on the Edit button near a module
5. The Exception appear 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-04-06 13:40
Duplicate of #28074

**Closed as completed by hibatallahAouadni** 2022-04-06 13:40 UTC
Labels: Bug, 8.0.x, BO, Duplicate, Design, Positions, Invalid
