### ISSUE TITLE
Error al respaldar BD

### ISSUE THREAD

**Issue by PlacerAbsoluto** [PrestaShop/PrestaShop#18087] opened 2020-03-11 09:38 UTC
Alguien sabe como solucionar este error al respaldar copia de seguridad?
Tengo miedo de perder todo y no puedo hacer copia

OutOfMemoryExceptionError: tamaño de memoria permitido de 134217728 bytes agotados (intentó asignar 111268896 bytes)
--
en DbPDO.php línea 156

**Comment by khouloudbelguith** [comment] 2020-03-11 09:41
Hi @PlacerAbsoluto,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by PlacerAbsoluto** [comment] 2020-03-11 09:48
Anyone know how to fix this error when backing up backup?
I'm afraid of losing everything and I can't make a copy:

OutOfMemoryExceptionError: tamaño de memoria permitido de 134217728 bytes agotados (asignado 111268896 bytes)
en DbPDO.php línea 156

**Comment by khouloudbelguith** [comment] 2020-03-11 10:14
@PlacerAbsoluto,

It is a size problem.
Thanks to check your configuration in the `php.ini` file & try to increase them

```
upload_max_filesize

post_max_size

max_file_uploads

memory_limit

max_input_vars

max_input_time

max_execution_time

```
And enable `set_time_limit`


Thanks!

**Comment by PlacerAbsoluto** [comment] 2020-03-11 10:45
Thank you for your reply.
I have PHP 7.3.9 an FPM
I have increased the parameters and now I have the following values:

upload_max_filesize  120M

post_max_size   120M

max_file_uploads   (no have)

memory_limit   512M

max_input_vars  (no have)

max_input_time  300

max_execution_time   300
set_time_limit  ON

I have tried again and the error message is now:

 OutOfMemoryException
Error: tamaño de memoria permitido de 536870912 bytes agotados (intentó asignar 638976 bytes)

What I can do?

**Comment by khouloudbelguith** [comment] 2020-03-11 10:49
@PlacerAbsoluto,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks!

**Comment by PlacerAbsoluto** [comment] 2020-03-11 11:18
My version is 1.7.6.3 and I have changed the version to 7.2.2 and downloaded and executed the phppsinfo.php tool and all the values ​​are correct over the recommended ones.

# | Required | Recommended | Current
-- | -- | -- | --
allow_url_fopen | Yes | Yes | Yes
expose_php | No | No | Yes
file_uploads | Yes | Yes | Yes
register_argc_argv | No | No | No
short_open_tag | No | No | No
max_input_vars | 1000 | 5000 | 1000
memory_limit | 64M | 256M | 512M
post_max_size | 16M | 128M | 120M
upload_max_filesize | 4M | 128M | 200M
set_time_limit | Yes | Yes | Yes

Even so, error still appears:

OutOfMemoryExceptionError: Tamaño de memoria permitido de 536870912 bytes agotados (intentó asignar 4096 bytes)
--
en DbPDO.php línea 156

**Comment by khouloudbelguith** [comment] 2020-03-11 11:25
@PlacerAbsoluto, in your BO => Advanced Parameters => Information page.
Thanks to provide me a screenshot
![image](https://user-images.githubusercontent.com/16067358/76412148-67245c80-6393-11ea-86a8-1222a38def34.png)

Thanks!

**Comment by PlacerAbsoluto** [comment] 2020-03-11 13:16
![Captura](https://user-images.githubusercontent.com/62055370/76420745-e40b0280-63a2-11ea-9f6c-a564540312e7.PNG)

**Comment by khouloudbelguith** [comment] 2020-03-11 13:27
@PlacerAbsoluto, on which page this error `OutOfMemoryExceptionError` is displayed?

Thanks!

**Comment by PlacerAbsoluto** [comment] 2020-03-11 13:50
I go to BO => Advanced Parameters =>Database.
On the second tab backup db,  
Click on "I have read the legal notice on ... Please create a new backup"
Start to make it and soon that message comes out

**Comment by khouloudbelguith** [comment] 2020-03-11 14:18
@PlacerAbsoluto, I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1uUwKjJZtNO-ISJnIGFLnZHYWtODkVHei/view
Could you please check with your host and feedback.

Thanks!

**Comment by marionf** [comment] 2020-04-08 13:31
Hello,
Since we had no news from you for more than 25 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Closed as completed by marionf** 2020-04-08 13:31 UTC
Labels: Bug, BO, DB Backup, No change required, 1.7.6.3
