### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#17585] opened 2020-02-10 13:14 UTC
I moved my website on a new hosting server. I have access to the BO but unfortunately I am not able to display the front office.

The error : ERR_TOO_MANY_REDIRECTS

SSL is enable
I tried to remove cache from var (dev and prod)
Disabling and enabling simplify links.
Changed missings values http:// to https:// on the database 

I did everything I found on Google to fix this but without success

Redirection is 301 you can check the redirections issue on http://www.redirect-checker.org/index.php.
I have 19 redirections 301.

Domain is https://maillotsdemarseille.com, PHP version is 7.2

Thank you for your help

**Comment by khouloudbelguith** [comment] 2020-02-10 13:40
Hi @Dupflo,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Dupflo** [comment] 2020-02-10 13:53
Host: Linux #1 SMP Wed Aug 14 08:29:59 EDT 2019 x86_64
Php version : 7.2.27
No debug mod report
No php error
No apache error
No javascript error 

I don't know how you can reproduce it since it came from a special case ... I migrate from another server. I have access to backoffice

**Comment by khouloudbelguith** [comment] 2020-02-10 13:59
@Dupflo,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by Dupflo** [comment] 2020-02-10 14:24
I did but not work

**Comment by khouloudbelguith** [comment] 2020-02-10 14:30
@Dupflo,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by didi-2018** [comment] 2020-02-10 15:17
@Dupflo  have you enabled SSL? This happens at my PS if SSL in PrestaShop is disabled. Please check it.

**Comment by khouloudbelguith** [comment] 2020-02-10 15:19
@didi-2018, similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10482?

Thanks!

**Comment by didi-2018** [comment] 2020-02-10 15:22
@khouloudbelguith YES exactly like this ticket #10482 !

**Comment by khouloudbelguith** [comment] 2020-02-10 15:24
@Dupflo, any news?

Thanks!

**Comment by Dupflo** [comment] 2020-02-10 15:32
> @Dupflo have you enabled SSL? This happens at my PS if SSL in PrestaShop is disabled. Please check it.

SSL is enable

**Comment by Dupflo** [comment] 2020-02-10 15:32
@khouloudbelguith 

<img width="1244" alt="Capture d’écran 2020-02-10 à 16 31 57" src="https://user-images.githubusercontent.com/39828779/74163648-f61e4780-4c22-11ea-92a3-ff11d40a0f65.png">

**Comment by khouloudbelguith** [comment] 2020-02-10 15:35
@Dupflo, could you please try to disable SSL mode, check & feedback.

Thanks!

**Comment by didi-2018** [comment] 2020-02-10 15:42
> > @Dupflo have you enabled SSL? This happens at my PS if SSL in PrestaShop is disabled. Please check it.
> 
> SSL is enable

and SSL "on all pages" too? 

![image](https://user-images.githubusercontent.com/44971218/74164589-46e27000-4c24-11ea-9047-a6b3fb1a4311.png)

**Comment by Dupflo** [comment] 2020-02-10 15:44
> > > @Dupflo have you enabled SSL? This happens at my PS if SSL in PrestaShop is disabled. Please check it.
> > 
> > 
> > SSL is enable
> 
> and SSL "on all pages" too?
> 
> ![image](https://user-images.githubusercontent.com/44971218/74164589-46e27000-4c24-11ea-9047-a6b3fb1a4311.png)

Yes !

**Comment by Dupflo** [comment] 2020-02-10 15:44
> @Dupflo, could you please try to disable SSL mode, check & feedback.
> 
> Thanks!

Same ...

**Comment by didi-2018** [comment] 2020-02-10 15:45
@Dupflo Browser Cache and Cookies deleted?

**Comment by Dupflo** [comment] 2020-02-10 15:47
> @Dupflo Browser Cache and Cookies deleted?

Yes..

**Comment by Dupflo** [comment] 2020-02-10 15:47
Check here https://maillotsdemarseille.com

**Comment by khouloudbelguith** [comment] 2020-02-10 15:50
@Dupflo, in this link https://maillotsdemarseille.com
SSL is still enabled.
You are using https & not http.

Thanks!

**Comment by Dupflo** [comment] 2020-02-10 15:51
> @Dupflo, in this link https://maillotsdemarseille.com
> SSL is still enabled.
> You are using https & not http.
> 
> Thanks!

Ok I disabled for you again, please check

**Comment by khouloudbelguith** [comment] 2020-02-10 15:53
@Dupflo, in your BO => Shop Parameters => Traffic & seo page => "Set shop URL", your shop domain is updated.

Thanks!

**Comment by Dupflo** [comment] 2020-02-10 16:18
<img width="1560" alt="Capture d’écran 2020-02-10 à 17 18 05" src="https://user-images.githubusercontent.com/39828779/74167954-52846580-4c29-11ea-8d55-b9d25db9e856.png">
@khouloudbelguith  Yes

**Comment by khouloudbelguith** [comment] 2020-02-10 16:19
@Dupflo, after disabling the SSL try to regenerate the file .htaccess again

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

Thanks to check and feedback

**Comment by Dupflo** [comment] 2020-02-10 16:25
> @Dupflo, after disabling the SSL try to regenerate the file .htaccess again
> 
> * Rename the old file to .htaccess_old
> * Disable friendly URL
> * Enable friendly URL
> 
> Thanks to check and feedback

Done but not working

**Comment by khouloudbelguith** [comment] 2020-02-10 16:30
@Dupflo, in your database => table ps_configuration, thanks to check the value of `PS_SSL_ENABLED` & `PS_SSL_ENABLED_EVERYWHERE`
![image](https://user-images.githubusercontent.com/16067358/74169078-020e0780-4c2b-11ea-8782-14963fffa02f.png)

Thanks!

**Comment by Dupflo** [comment] 2020-02-10 16:51
Value was NULL, I put 0 then

Still not working

**Comment by khouloudbelguith** [comment] 2020-02-10 16:56
@Dupflo,

I moved my Project to a new domain without errors.
1. I made a backup for my files & my database
2. I uploaded my store's files to your new server
3. I imported the old store's database to the new server
4. In file /app/config/parameters.php, I configured my PrestaShop site.
4.1. DB_SERVER: database's server;
4.2. DB_NAME: Name of the database from step 5;
4.3. DB_USER: User associated with the database;
4.4. DB_PASSWD: The user's password;
5. in the Table ps_shop_url, I changed with the 
5.1. domain => new domain
5.2. domain_ssl => new domain_ssl
5.3. physical_uri => new physical_uri
6. I cleared cache manually by deleting all the folder into var/cache (prod & dev).

Thanks!

**Comment by Dupflo** [comment] 2020-02-10 17:00
> @Dupflo,
> 
> I moved my Project to a new domain without errors.
> 
> 1. I made a backup for my files & my database
> 2. I uploaded my store's files to your new server
> 3. I imported the old store's database to the new server
> 4. In file /app/config/parameters.php, I configured my PrestaShop site.
>    4.1. DB_SERVER: database's server;
>    4.2. DB_NAME: Name of the database from step 5;
>    4.3. DB_USER: User associated with the database;
>    4.4. DB_PASSWD: The user's password;
> 5. in the Table ps_shop_url, I changed with the
>    5.1. domain => new domain
>    5.2. domain_ssl => new domain_ssl
>    5.3. physical_uri => new physical_uri
> 6. I cleared cache manually by deleting all the folder into var/cache (prod & dev).
> 
> Thanks!

I did same than you

**Comment by Dupflo** [comment] 2020-02-10 17:34
I have access to my admin panel ...

**Comment by khouloudbelguith** [comment] 2020-02-11 10:17
@Dupflo,

https://github.com/PrestaShop/PrestaShop/issues/17585#issuecomment-584219622
In your database => table ps_configuration, thanks to change the value of `PS_SSL_ENABLED` to `1` and `PS_SSL_ENABLED_EVERYWHERE` to `1`.

Now try to Rename the old file to .htaccess_old & Disable friendly URL &Enable friendly URL, clear cache from your shop & your browser & check.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-11 08:04
Hi @Dupflo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-11 08:04 UTC
Labels: Bug, FO, No change required
