### ISSUE TITLE
Preg_match error on product page with group array

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#16629] opened 2019-11-29 20:39 UTC
We see a lot of warning errors using the newrelic APM on product page with combination group.

For example, this url is generated when we change the color
https://www.example.localhost/en/index.php?controller=product?token=bbc9c29ec62ee06deb919edab05e1a3a&id_product=133766&id_product_attribute=155272&id_customization=0&group%5B8%5D=7970&group%5B11%5D=5378&qty=1

In debug mode, we have
(1/1) ContextErrorException
Warning: preg_match() expects parameter 2 to be string, array given

Error happens in FrontControllerCore->canonicalRedirection

PrestaShop version: 1.7.4

**Comment by khouloudbelguith** [comment] 2019-12-02 10:43
Hi @cedricfontaine,

Thanks for your report.
Have you the same issue with PS1.7.6.2?

Thanks!

**Comment by cedricfontaine** [comment] 2019-12-02 14:21
Hello,
I didn't check. But I look at the code and there is no changes done. So for me problem still exists.

**Comment by khouloudbelguith** [comment] 2019-12-02 16:35
@cedricfontaine, thanks for your feedback.
Ping @eternoendless @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment] 2020-11-20 16:27
I'm not able to reproduce the issue, I need more detail to be able to reproduce it.

**Comment by hibatallahAouadni** [comment] 2020-12-14 15:38
Hello @cedricfontaine,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-14 15:38 UTC
Labels: Bug, FO, Combinations, No change required
