### ISSUE TITLE
No combinations in BO after upgraded from 1.7.5.0 to 1.7.6.5

### ISSUE THREAD

**Issue by oriolpiera** [PrestaShop/PrestaShop#19276] opened 2020-05-22 12:15 UTC
#### Describe the bug

Product Combinations empty in BO, but I can see in FO. (all products)

#### Expected behavior

List of Combinations in Product page, tab Combinations

#### Steps to Reproduce

1. Go to Catagol
2. Click on Products
3. Click on Combinations tab
3. Scroll down
4. No combinations

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/26488435/82665583-61b97d00-9c34-11ea-858e-c6ffb93cfb92.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.5

I made an OneClick updated from PS 1.7.5.0. I check the logs, and I updated the database with data in `ps_current_lang` because the error:
```
[INTERNAL] /usr/home/casapiera.com/web/testing/admin52758278/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Error: Call to a member function get() on null 
#0 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang() 
#1 /usr/home/casapiera.com/web/testing/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(372): call_user_func_array('ps_1760_copy_da...', Array) 
#2 /usr/home/casapiera.com/web/testing/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(340): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...') 
#3 /usr/home/casapiera.com/web/testing/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(264): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...') 
#4 /usr/home/casapiera.com/web/testing/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(52): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.7.5.0') 
#5 /usr/home/casapiera.com/web/testing/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.5.0') 
#6 /usr/home/casapiera.com/web/testing/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#7 /usr/home/casapiera.com/web/testing/admin52758278/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#8 {main}
```

I check with Chrome DevTools and I miss this calls in 1.7.6.5 that I had in PS 1.7.5.0:
```
index.php/sell/catalog/products/attributes/form-images/4075?_token=***
index.php/sell/catalog/products/combinations/form/61010?_token=***
```
Also various JSON: numbers.json, currencies.json...

So, **could you show me where this missing calls were suposed to be called**? I supose theres a line in some JavaScript files who make this calls.

**Comment by florine2623** [comment] 2020-05-22 15:06
Hi @oriolpiera ,
I upgraded my PS 1.7.5.0 to PS 1.7.6.5 using 1-click upgrade v4.10.1 and I couldn't reproduce the issue. My combinations are all here.
Did you have any errors during the upgrade apart from ps_current_lang ?
Thanks!

**Comment by florine2623** [comment] 2020-06-11 08:08
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-11 08:08 UTC
Labels: BO, Autoupgrade, Combinations, No change required, 1.7.5.0, 1.7.6.5

**Comment by oriolpiera** [comment] 2020-06-11 08:12
If someone get there with the same problem, I had no other solution to install a fresh Prestashop and migrate all catalog tables (lucky it wasn't scheme changes).
