### ISSUE TITLE
wrong currency symbol displayed in order summary 1.7.6.1

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#17359] opened 2020-01-26 11:09 UTC
Our default currency is GBP and one of our currencies is Japanese yen. But the issue is not related to yen, euro or usd.
When a customer makes a purchase in own currency (yen for example) and pays with PayPal, prices in BO/order are displayed in yen. However, as you can see on the printscreen, the final, bottom summary is in default currency (GBP), however with wrong figures - those are yen amounts.

The screenshot is self-explaining:
![order-currency](https://user-images.githubusercontent.com/31688689/73134235-7abe7280-4034-11ea-82ac-5d8c24d14bff.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.26

**Comment by khouloudbelguith** [comment] 2020-01-27 11:40
Hi @mrabsinthe,

I did not manage to reproduce the issue with PS1.7.6.3 & Paypal module v5.1.0.
I attached a screen record
https://drive.google.com/file/d/1ShMWhWBaGk_8oOIweKKWgDfkWVDaUZ4H/view

We have related issues:
https://github.com/PrestaShop/PrestaShop/issues/12521
https://github.com/PrestaShop/PrestaShop/issues/9850
https://github.com/PrestaShop/PrestaShop/issues/16578

Thanks to check & feedback.

**Comment by mrabsinthe** [comment] 2020-01-27 11:47
Not sure why you're unable to reproduce, perhaps because the payment error? I'm using PayPal v4.5.0, I'll try to update and we'll see if it makes any difference (I don't think so). It is certainly related to those issues mentioned.

**Comment by khouloudbelguith** [comment] 2020-01-27 12:04
@mrabsinthe, with status order green, it is OK also.
https://drive.google.com/file/d/1iHpyfO2768U1ZRBGsmZ_TNsYx-9q366e/view

Waiting for your feedback.

**Comment by mrabsinthe** [comment] 2020-01-27 13:33
I have just upgraded PayPal to v5.1.0 and it seems to be OK now (believe it or not). Even that old Japanese order is OK now...
![order-summary-updated](https://user-images.githubusercontent.com/31688689/73178614-e9bdc900-4111-11ea-9816-531725e8e02d.png)

**Comment by khouloudbelguith** [comment] 2020-01-27 13:36
@mrabsinthe, since it is OK.
I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-27 13:36 UTC
Labels: Bug, BO, Order, Discounts, Currencies, Taxes and Prices, No change required, 1.7.6.1
