### ISSUE TITLE
404 generate invoice in BO

### ISSUE THREAD

**Issue by VincentVallee** [PrestaShop/PrestaShop#36805] opened 2024-09-03 15:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello evryone, sorry for my english.

I have shop on prestashop 1.8.5. 

When I want generate invoice or oder-slip for order I have an 404 error, but it's ok when I generate order from invoice section in BO. 
I specify that I don't have the error on local.

Shop is hosting on ikoula server, so I don't have access to config of nginx/apache or a little bit.

I don't have not much more informations about this error.

Thanks in advance

### Steps to reproduce

Go to order section in BO and generate invoice or order-slip for another order

### PrestaShop version(s) where the bug happened

1.8.5

### PHP version(s) where the bug happened

8.2.23

**Comment by kpodemski** [comment] 2024-09-04 14:04
Hello

First of all you shouldn't use PHP 8.2 with this version of PS. PHP 8.1 is the latest compatible version.

Secondly, consider increasing max execution time and memory limit as some hosting redirect to 404 if there are no available resources to finish the process.

**Comment by ibahloul-ps** [comment] 2024-09-05 14:25
Hello @VincentVallee,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
Have a great day!

**Closed as completed by ibahloul-ps** 2024-09-05 14:25 UTC
Labels: Bug
