### ISSUE TITLE
Error on install..

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#25232] opened 2021-07-05 10:45 UTC
Guys!?
What the hell is that??!

1.7.7.5

ps_facebook1: Nie można zainstalować modułu "ps_facebook"

![Zrzut ekranu z 2021-07-05 o 12 44 13](https://user-images.githubusercontent.com/8243273/124459778-d2671e80-dd8e-11eb-8d14-3b6e62e90068.png)

**Comment by hibatallahAouadni** [comment] 2021-07-05 11:01
Hello @PrestaShark 

We are aware of this issue, the Addons Team is already work on it. This issue is a duplicate of #25191. 
This issue is related to Addons API and not to PS Core.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-05 11:01
Duplicate of #25191

**Closed as completed by hibatallahAouadni** 2021-07-05 11:01 UTC
Labels: Duplicate
