### ISSUE TITLE
Problem modifying products

### ISSUE THREAD

**Issue by YerayC78** [PrestaShop/PrestaShop#23204] opened 2021-02-10 10:52 UTC
When I modify a product and click to save, it remains blocked and does not make the change. It does not allow me to remove product features.

Normally, when you click on save, you make the change to the product and a message appears that says: Product modified successfully. 

The error occurs when selecting catalog / products, edit a product and click on save. Then it gets bloqued.

![Fallo al guardar un producto](https://user-images.githubusercontent.com/78850868/107500433-0d717700-6b8e-11eb-9817-389a4a81b439.jpg)

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-02-10 13:10
Hello @YerayC78 

I didn't manage to reproduce your issue with PS1.7.7.1.

Could you please enable the mode debug and try again, let's see if the system could identify the cause of the error.
And could you please provide a screenshot of your console.

Thanks!

**Comment by alfonsolr09** [comment] 2021-02-11 20:51
what theme are you using?

**Comment by YerayC78** [comment] 2021-02-12 09:06
my server log says the problem is:

mod_fcgid: stderr: PHP Warning: "continue" targeting switch is 
equivalent to "break". Did you mean to use "continue 2"? in 
/var/www/vhosts/host/shop.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php 

on line 2665, referer: 
https://shop.com/admin/index.php?controller=AdminDashboard

I have to edit line 2665 of the file


<https://host/smb/file-manager/list?currentDir=%2Fshop.com> 
/ vendor 
<https://host/smb/file-manager/list?currentDir=%2Fshop.com%2Fvendor> 
/ doctrine 
<https://host/smb/file-manager/list?currentDir=%2Fshop.com%2Fvendor%2Fdoctrine> 
/ orm 
<https://host/smb/file-manager/list?currentDir=%2Fshop.com%2Fvendor%2Fdoctrine%2Form> 
/ lib 
<https://host/smb/file-manager/list?currentDir=%2Fshop.com%2Fvendor%2Fdoctrine%2Form%2Flib> 
/ Doctrine 
<https://host/smb/file-manager/list?currentDir=%2Fshop.com%2Fvendor%2Fdoctrine%2Form%2Flib%2FDoctrine> 
/ ORM 
<https://phost/smb/file-manager/list?currentDir=%2Fshop.com%2Fvendor%2Fdoctrine%2Form%2Flib%2FDoctrine%2FORM> 
/ UnitOfWork.php

that line says
    continue;
I don't know if I have to delete or modify it

**Comment by hibatallahAouadni** [comment] 2021-02-12 10:29
Hello @YerayC78 

Please do not disclose your confidentiality here for security reason.
Let's be safe :wink: 

Did you upgrade your shop lately? if so, what was your shop version? and did you override a Controller? if so, what is it?
Please check and feedback.

Thanks!

**Comment by alfonsolr09** [comment] 2021-02-12 14:20
Something similar happened to me due to a js problem with the theme

**Comment by hibatallahAouadni** [comment] 2021-02-12 18:01
@alfonsolr09 thanks for helping :relaxed: 
@YerayC78 could you please check your console if you have any JS errors?

**Comment by YerayC78** [comment] 2021-02-13 12:07
I have solved the problem. I restored the Prestashop to version 1.7.6.8. 
The log of my server detected errors in the reading of some php files. I removed the command "continue;" of the lines that were wrong and now works fine. 

Thanks a lot.

**Comment by hibatallahAouadni** [comment] 2021-02-15 22:34
@YerayC78 thanks for your feedback!
Glad that you resolve your issue :tada: 
So, I close this issue :wink:

**Closed as completed by hibatallahAouadni** 2021-02-15 22:34 UTC
Labels: Bug, BO, No change required, 1.7.7.1
