### ISSUE TITLE
BO - the customization field appears in BO>Order only when the shop is disabled

### ISSUE THREAD

**Issue by miss0001** [PrestaShop/PrestaShop#30477] opened 2022-12-03 11:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hallo
I have problems with orders, in orders I do not see the configuration of the product that the customer made

it only shows for a few moments and then disappears

When my web shop is online, I don't see what the customer has added to the product.

When I turn off the webb shop, I see what the customer has added.
![Snimka zaslona 2022-12-03 115444](https://user-images.githubusercontent.com/119735558/205438591-5f1350df-c6b0-4e47-bc38-3215c3b88cb0.png)
![Snimka zaslona 2022-12-03 115810](https://user-images.githubusercontent.com/119735558/205438592-0c26034b-4800-4039-9a2a-f56e1f88a080.png)
![Snimka zaslona 2022-12-03 120036](https://user-images.githubusercontent.com/119735558/205438593-89caa522-e40c-4b57-94ce-e0e7b4db47fe.png)
![Snimka zaslona 2022-12-03 115930](https://user-images.githubusercontent.com/119735558/205438594-493e5768-114a-4990-87eb-8925c6066d3a.png)

### Steps to reproduce

![Snimka zaslona 2022-12-03 115444](https://user-images.githubusercontent.com/119735558/205438637-3cd7f47d-1b48-42e1-98b7-added15123eb.png)
![Snimka zaslona 2022-12-03 115810](https://user-images.githubusercontent.com/119735558/205438638-3f2be19b-659b-4650-a008-1e40b4c28ecb.png)
![Snimka zaslona 2022-12-03 120036](https://user-images.githubusercontent.com/119735558/205438639-35dc14a9-cde6-479a-9ea3-21e6dfaf509d.png)
![Snimka zaslona 2022-12-03 115930](https://user-images.githubusercontent.com/119735558/205438642-343708e1-b1b9-4f2c-b6b6-060c5e5358b5.png)

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by hibatallahAouadni** [comment] 2022-12-05 18:31
Hello @miss0001 

I didn't manage to reproduce the issue with the provided infos.
That's odd! Could you please provide a screen record and your PHP version :pray: 
Waiting for your feedback.

Thanks!

**Comment by miss0001** [comment] 2022-12-08 08:49
I have problems with orders, in orders I do not see the configuration of the product that the customer made

it only shows for a few moments and then disappears

When my web shop is online, I don't see what the customer has added to the product.

When I turn off the webb shop, I see what the customer has added.

prestashop 1.7.8.7


![Snimka zaslona 2022-12-03 115810](https://user-images.githubusercontent.com/119735558/206400662-5bc1b83c-0e94-4928-9b93-834a9ed200dd.png)
![Snimka zaslona 2022-12-03 133841](https://user-images.githubusercontent.com/119735558/206400686-81b51d8f-21ae-4a17-a56e-c3ad5e46cba9.png)
![Snimka zaslona 2022-12-03 115930](https://user-images.githubusercontent.com/119735558/206400709-dc466f28-314f-4116-8c1f-fb60e26d12a1.png)
![Snimka zaslona 2022-12-03 120036](https://user-images.githubusercontent.com/119735558/206400729-8ce0da01-9111-4ee4-ba37-1464b0a590b6.png)
![Snimka zaslona 2022-12-08 094838](https://user-images.githubusercontent.com/119735558/206401160-9b33cc36-9430-4dca-be97-8cc8b7f393ce.png)

**Comment by paulnoelcholot** [comment] 2022-12-08 11:30
Hello @miss0001 

I tried with the information you gave us but I can't reproduce the problem. Could you make us a video of the behavior?

![image](https://user-images.githubusercontent.com/112863083/206435653-9dc4d8bf-e10e-4691-8aa1-4064af7074f3.png)

Thank you

**Comment by miss0001** [comment] 2022-12-08 19:18
Uploading Miss Pokloni j.d.o.o. i još jedna stranica – Osobno – Microsoft_ Edge 2022-12-08 19-40-41 (video-converter.com).mp4…

**Comment by paulnoelcholot** [comment] 2022-12-08 19:44
There seems to have been a problem sending your message, could you try posting the video again please.

Thank you

**Comment by miss0001** [comment] 2022-12-09 06:10
https://user-images.githubusercontent.com/119735558/206636293-bf222713-eae7-46cf-b03b-09a96b028c1a.mp4

**Comment by AureRita** [comment] 2022-12-09 15:43
Hi @miss0001 

Thank you for your report ! I tried to reproduce your problem as you can see here : 

[Untitled_ Dec 9, 2022 4_41 PM.webm](https://user-images.githubusercontent.com/100699445/206739103-8e42e77d-714d-4cc7-ba4f-9c2b0d224857.webm)

but I didn't reproduce it. Did I miss something ?

**Comment by miss0001** [comment] 2022-12-12 20:03
It doesn't work for me, what should I do? Should I try to reinstall prestashop?

**Comment by AureRita** [comment] 2022-12-13 13:27
Hi @miss0001 

Can you say me if you install it with a zip or with command line ? try to reinstall and check if you continue to have this issue ?

Waiting for your feedback

**Comment by hibatallahAouadni** [comment] 2023-01-02 09:21
Hello @AureRita 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-01-02 09:21 UTC
Labels: Bug, BO, Order, Product customization, Invalid, 1.7.8.7
