### ISSUE TITLE
BUG Product Combinations Prestashop 1.7.4.3

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#11271] opened 2018-11-06 00:24 UTC
**Describe the bug**
When you have a product with combinations, and set the product configuration in the BO, to do not show products with non attributes in stock, When you select one attribute in the Front, and select again the other attribute dont change the combination. But if you select in product configuration in the BO, Show protuct with non attributes in stock, do not have a problem. Pls solve the issue

**To Reproduce**
1. Go to 'BO'
2. Click on 'Product Configurations.'
3. Set "Show product with attributes not available" to NO
4. Go to Front
5. Click in one product combinations
6. Select another attribute in the same product
7. Select again the attribute before
8. See error
9. The combination dont change again

**Screenshots**

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-11-06 08:38
Hi @TecnoHands,

We are aware of this issue.
It is added to our bug roadmap.
Your ticket is a duplicate of #9667
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-06 08:38
Duplicate of #9667

**Closed as completed by khouloudbelguith** 2018-11-06 08:38 UTC
Labels: Duplicate
