### ISSUE TITLE
Prestashop1.7.4.4 product error

### ISSUE THREAD

**Issue by maviteknoloji** [PrestaShop/PrestaShop#12510] opened 2019-02-08 13:22 UTC
I'm using prestashop 1.7.4.4 ... the problem with the new ... no problem when I say replicate product. when I say the product edit the product fix it when I say it seems to have saved the old information stands ....
I will add new product, I still say the same ...
just sometimes I'm allowed to add
Add a photo. Open product Open product Add new photo. open products open product name save product ...
If this is the way it works sometimes please help ...
I can't add products since 1 week

No error ... seems to be noted.

**Comment by khouloudbelguith** [comment] 2019-02-08 13:24
Hi @maviteknoloji,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by maviteknoloji** [comment] 2019-02-08 19:27
@khouloudbelguith https://youtu.be/9P55D5IfoL4 videoyu izlerseniz sorunu görürsünüz...

**Comment by maviteknoloji** [comment] 2019-02-08 19:28
@khouloudbelguith https://youtu.be/9P55D5IfoL4 sorun burada gözüküyor...

**Comment by khouloudbelguith** [comment] 2019-02-11 10:00
@maviteknoloji, you closed your issue? it is fixed?
Your video is not available.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-20 10:30
Hi @maviteknoloji,

Feel free to open a new one when needed.
Thanks!

**Comment by maviteknoloji** [comment] 2019-02-28 05:57
Stack trace:
#0 /home/vtwparan/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(277): Smarty_Internal_Extension_Handler->__get('registerPlugin')
#1 /home/vtwparan/public_html/config/smarty.config.inc.php(125): Smarty_Internal_TemplateBase->registerPlugin('function', 'toolsConvertPri...', Array)
#2 /home/vtwparan/public_html/config/smartyadmin.config.inc.php(35): smartyRegisterFunction(Object(Smarty), 'function', 'toolsConvertPri...', 'toolsConvertPri...')
#3 /home/vtwparan/public_html/config/smarty.config.inc.php(57): require_once('/home/vtwparan/...')
#4 /home/vtwparan/public_html/config/config.inc.php(202): require_once('/home/vtwparan/...')
#5 /home/vtwparan/public_html/aavc1fdnnp7dak6a/index.php(42): require('/home/vtwparan/...')
#6 {main}
  thrown in /home/vtwparan/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 168

**Comment by khouloudbelguith** [comment] 2019-02-28 11:45
@maviteknoloji, your issue is not fixed?
I re-open your ticket?
Thanks!

**Comment by maviteknoloji** [comment] 2019-02-28 11:56
I'm getting these errors right now

# 0 /home/vtwparan/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(277): Smarty_Internal_Extension_Handler -> __ olsun ( 'registerPlugin') 
[1.](https://github.com/PrestaShop/PrestaShop/pull/1) / home / vtwparan / public_html / config / çokbilmiş .config.inc.php (125): Smarty_Internal_TemplateBase-> registerPlugin ('function', 'toolsConvertPri ...', Array) 
[# 2](https://github.com/PrestaShop/PrestaShop/pull/2) /home/vtwparan/public_html/config/smartyadmin.config.inc.php(35): smartyRegisterFunction (Object (Smarty), 'function', 'toolsConvertPri ...', 'toolsConvertPri ...') 
[# 3](https://github.com/PrestaShop/PrestaShop/pull/3) /home/vtwparan/public_html/config/smarty.config.inc.php(57): requ_once (' / home / vtwparan / ... ') 
[# 4](https://github.com/PrestaShop/PrestaShop/pull/4) / home / vtwparan/public_html/config/config.inc.php(202): requ_once (' / home / vtwparan / ... ') 
[# 5](https://github.com/PrestaShop/PrestaShop/pull/5)/home/vtwparan/public_html/aavc1fdnnp7dak6a/index.php(42): gerektirir ('/ home / vtwparan / ...') 
[# 6](https://github.com/PrestaShop/PrestaShop/pull/6) {main} 
/ home / vtwparan / public_html / vendor / smarty / smarty / libs /sysplugins/smarty_internal_extension_handler.php on line 168

**Comment by khouloudbelguith** [comment] 2019-02-28 13:03
@maviteknoloji, could you please add steps to reproduce the issue.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-29 08:32
Hi @maviteknoloji,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-29 08:32 UTC
Labels: Bug, BO, No change required
