### ISSUE TITLE
Importing / Exporting products website stuck on keep loading it

### ISSUE THREAD

**Issue by ArnasL** [PrestaShop/PrestaShop#18194] opened 2020-03-18 09:45 UTC
Hello, I am trying to export/import products and I get stuck on 0/7000 products to be exported. My website is keep loading and I have to restart apache to make it accessible again. What can cause this issue? I think it's something related to PHP, but I'm not sure, because all my PHP settings are increased.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 5.6

# | Required | Recommended | Current
allow_url_fopen | Yes | Yes | Yes
expose_php | No | No | Yes
file_uploads | Yes | Yes | Yes
register_argc_argv | No | No | No
short_open_tag | No | No | No
max_input_vars | 1000 | 5000 | 10000
memory_limit | 64M | 256M | 512M
post_max_size | 16M | 128M | 256M
upload_max_filesize | 4M | 128M | 256M
set_time_limit | Yes | Yes | Yes

**Comment by khouloudbelguith** [comment] 2020-03-18 13:11
Hi @ArnasL,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
[Untitled_ Mar 18, 2020 2_07 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4349089/Untitled_.Mar.18.2020.2_07.PM.webm.zip)
It is a server issue, it could be that your server is not powerful enough.

Thanks to check with your host and feedback.

**Comment by ArnasL** [comment] 2020-03-18 15:22
Strange thing now it working and I don't even know what has been changed :D ..

**Comment by khouloudbelguith** [comment] 2020-03-18 15:27
@ArnasL, Great!
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-18 15:27 UTC
Labels: Bug, BO, No change required, 1.7.6.1
