### ISSUE TITLE
PHP 7.4: Using array_key_exists() on objects is deprecated

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#19463] opened 2020-05-29 18:34 UTC
Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /src/Adapter/EntityMapper.php on line 99

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/partlada/classes/module/Module.php on line 330

**Comment by jolelievre** [comment] 2020-06-01 08:59
Hi @TemKaSD,

could you please provide more info about this deprecation notice? Especially:

- which version of PHP you are using?
- which version of PrestaShop you are using?

If I'm not wrong `array_key_exists` has been deprecated since PHP 7.4, as of today even our coming latest version 1.7.7 is compatible to PHP 7.3 max, the full support of PHP 7.4 will be implemented in 1.7.8

So these warnings are "normal" for now (as they have not been fixed yet) and should be addressed in the 1.7.8.

This is already defined in this issue https://github.com/PrestaShop/PrestaShop/issues/16477 so I'm gonna close this one as a duplicate.

Thanks for your feedback regardless :)

**Comment by jolelievre** [comment] 2020-06-01 09:00
Duplicate of #16477

**Closed as completed** 2020-06-01 08:59 UTC
Labels: Duplicate

**Comment by TemKaSD** [comment] 2020-06-01 19:35
@jolelievre Why can't you make corrections for PHP 7.4 in 1.7.7?
