### ISSUE TITLE
Unable to access ps_faceted_search "Available" translation

### ISSUE THREAD

**Issue by Afterglow93290** [PrestaShop/PrestaShop#32962] opened 2023-06-20 19:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When trying to replace translation of "Available" facet label from availability filter, this one is not showing into admin translation panel.

![image](https://github.com/PrestaShop/PrestaShop/assets/106123483/cad95d0e-78cf-4efc-b80b-74111eb86ca7)

Source code **/modules/ps_facetedsearch/src/Filters/Converter.php** : 

case self::TYPE_AVAILABILITY:
 if (!isset($facetAndFiltersLabels[$filterLabel])) {
                        // No need to filter if no information
                        continue 2;
                    }

                    $quantityArray = [
                        $this->context->getTranslator()->trans(
                            'Not available',
                            [],
                            'Modules.Facetedsearch.Shop'
                        ) => 0,
                        $this->context->getTranslator()->trans(
                            'Available',
                            [],
                            'Modules.Facetedsearch.Shop'
                        ) => 1,
                        $this->context->getTranslator()->trans(
                            'In stock',
                            [],
                            'Modules.Facetedsearch.Shop'
                        ) => 2,
                    ];

Chain exists, but cannot be updated from Admin Panel (didn't tried through editing manually translation file)

### Expected behavior

Expected to replace "Available" text to "Available on demand" because of misunderstanding between "In Stock" which is relative to current stock and "Available" which is relative to unavailable products with allowed orders, and can be understood as both available in stock.

### Steps to reproduce

1. Go to Admin Panel
2. Go to Modules
3. Select "Configure" on ps_faceted_search module
4. Click on "Translations" on top right
5. Type or Browse for "Available" chain

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_faceted_search v3.12.1

**Comment by Hlavtox** [comment] 2023-06-21 11:46
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28302

**Comment by aniszr** [comment] 2023-06-21 14:44
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of [#28302](https://github.com/PrestaShop/PrestaShop/issues/28302)
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed** 2023-06-21 15:05 UTC
Labels: Bug, Duplicate, Invalid
