### ISSUE TITLE
Faceted search availability filter not showing up

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14666] opened 2019-07-15 19:14 UTC
**Describe the bug**
Enable filter for product availability. Go to FO, filter is not there.

**Additional information**
PrestaShop version: 1.7.6 final
Faceted search version: 3.1.0

**Comment by khouloudbelguith** [comment] 2019-07-16 07:48
Hi @Hlavtox,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.0 & the ps_facetedsearch module v3.1.0.
I attached a screen record
https://drive.google.com/file/d/1KN6q4FdB6BpvGIqqRNY5ozQ4kdBA61C-/view
Thanks to check & feedback.

**Comment by Hlavtox** [comment] 2019-07-16 10:11
@khouloudbelguith https://drive.google.com/file/d/16IYAtpvPofv5NE5caBQU0zv8D9dOhVHJ/view

**Comment by khouloudbelguith** [comment] 2019-07-16 14:46
@Hlavtox, what is the exact behavior is selected when out of stock?
![image](https://user-images.githubusercontent.com/16067358/61304263-d3d56000-a7e0-11e9-9a32-cc7d3e3b0f31.png)
Is it "Deny orders" or "Allow orders"?

Thanks!

**Comment by Hlavtox** [comment] 2019-07-17 14:19
@khouloudbelguith Use default behavior (Allow orders) for all products.

**Comment by khouloudbelguith** [comment] 2019-07-17 14:21
@Hlavtox, So, it is normal behavior that the availability filter is not displayed.
Because, in your case, all the products can be added to the cart => so they are available to the sale.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-17 14:29
@Hlavtox, this filter will be improved.
Here's a ticket: #14518 to improve the search filter by availability. 
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-17 14:29 UTC
Labels: FO, Faceted search, No change required, 1.7.6.0
