### ISSUE TITLE
stock management with multiple stores 

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#11511] opened 2018-11-26 12:51 UTC
When we declare 2 or more stores with the option "share the quantities available", there are some unlogical behaviour and little bugs that should be corrected : 
1) the Stock page cannot be used if we don't select ONE shop. This page should be available only when we select the GROUP of shops that share quantities, or "all shops" if we have only one group (that shares the quantities). The function works ok and if we change the qtty of a product in one shop it's spread on the others, it's just a permission/display point of view.
2) on the product page, when we open a product ("all shops" selected) and go the the "quantities" part (or declinaisons if available) to modify a quantity, red error message if we clic on "save" (impossible to store changes)
If we clic on "go to catalog" instead of "save" red message too, no redirection to catalog, but and we discover that the changes has been done anyway.

PrestaShop version: 1.7.5beta1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-11-26 14:03
Hi @elmanu13,

About the first issue, it is a normal behavior, you can follow our [documentation](http://doc.prestashop.com/display/PS17/The+multistore+interface) so you can find that the "Advanced stock management" is only available per shop.
About the second issue, we are aware of this issue, you can follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/10274.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-26 14:03
Duplicate of #10274

**Closed as completed by khouloudbelguith** 2018-11-26 14:03 UTC
Labels: Duplicate
