### ISSUE TITLE
Save dashboard module is not possible

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#36520] opened 2024-07-09 08:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since 8.1.2 (https://github.com/PrestaShop/PrestaShop/commit/1b884c8b4a5850cd45925bb41416ea16fffb1084) it's not possible to save the dashboard module config due to an error on submit.

### Expected behavior

Be able to save the config without error.

### Steps to reproduce

1. Install PrestaShop (at least 8.1.2)
2. Go to Dashboard
3. Edit a dashboard module config
4. Click to save
See error "Hook is not allowed there".

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

n/d

### If your bug is related to a module, specify its name and its version

n/d

### Your company or customer's name goes here (if applicable).

PrestaEdit

**Comment by florine2623** [comment] 2024-07-09 08:38
Hello @PrestaEdit ,

Your issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/34326

I'm closing your issue to avoid clogging the backlog.
Thanks!

**Closed as completed by florine2623** 2024-07-09 08:38 UTC
Labels: Bug
