### ISSUE TITLE
Creating a once deleted currency causes duplicate rows in database

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17661] opened 2020-02-13 16:23 UTC
**Describe the bug**
When a currency is added in PrestaShop it is impossible to add it a second time, thus it prevents having duplicate
However, if you delete a currency and then add it again a new row is inserted and the former one is still present with its deleted column set to 1 (soft delete)
This means the database has duplicated rows, and that different orders with the same currency do not use the same one in database
**To Reproduce**

1. Go to Internationalisation > Localization > Currencies
2. Add a new currency (for example USD)
3. Go back to the currencies list and delete the newly created currency
4. Download the "added and deleted" curreny localization pack, for example, United Stets pack
5. A second row in the database is created

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/74455314-6a582580-4e85-11ea-8396-ef1becc49d80.png)

**Additional information**
PrestaShop version: 1.7, 1.7.7.x
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-02-13 16:24
Ping @matthieu-rolland 
 Related to https://github.com/PrestaShop/PrestaShop/pull/16287

**Comment by colinegin** [comment] 2020-02-14 17:05
Is this a regression ? Should it be fixed for 177 ?

**Comment by khouloudbelguith** [comment] 2020-02-17 13:52
Hi @colinegin,

No, it is not a regression.
Same issue with PS1.7.5.2 & PS1.7.6.3
![image](https://user-images.githubusercontent.com/16067358/74659486-bad8c700-5194-11ea-8c5d-6474fe0ee7bd.png)
![image](https://user-images.githubusercontent.com/16067358/74659522-cc21d380-5194-11ea-8a1d-01a26a0fa023.png)

In fact, this [issue](https://github.com/PrestaShop/PrestaShop/issues/15934) is not totally fixed.

Thanks!

**Comment by jolelievre** [comment] 2020-04-07 13:57
@khouloudbelguith I think this one is not only related but seems like a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15934
Which has been fixed by this PR in 1.7.7 https://github.com/PrestaShop/PrestaShop/pull/16287/files

**Comment by khouloudbelguith** [comment] 2020-04-07 14:11
Hi @jolelievre,

No, this issue is not fixed in the PS1.7.7.
I can reproduce the issue with 177x branch
https://drive.google.com/file/d/132ouko0vHbDeP1ro0KL902C0-DRS-86X/view?usp=sharing
Following these steps

1. Go to Internationalisation > Localization > Currencies
2. Add a new currency (for example USD)
3. Go back to the currencies list and delete the newly created currency
4. Download the "added and deleted" curreny localization pack, for example, United Stets pack
5. A second row in the database is created

Thanks!

**Comment by jolelievre** [comment] 2020-04-07 14:31
Oh my bad! I didn't understand it was added via the localization pack
Thank you @khouloudbelguith

**Closed as completed** 2020-07-29 14:27 UTC
Labels: Bug, Minor, BO, Currencies, Fixed, 1.7.5.2, PR available, 1.7.7.x, 1.7.6.3
