### ISSUE TITLE
Cant save product with a lot of combinations on shared hosting

### ISSUE THREAD

**Issue by PatrykMakowski** [PrestaShop/PrestaShop#12862] opened 2019-03-11 10:50 UTC
**Describe the bug**
I have problem with saving product that has a lot of combinations. Problem is over 1000 active combinations per product.  Maybe this isnt a prestashop bug, but its very unoptimized solution and most shared hostings have problem with saving product When we have 1000 combinations, then button "Save" on product backoffice sending ajax request with **14000** variables. PHP max_input_vars is set to 30k, but server still give me error code 400 or 503. In 1.6 problem doesnt exists - combinations was saving separately.

**To Reproduce**
1. Use any shared hosting
2. Generate 1000 combinations for any product 
3. You cant save product anymore

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-03-11 10:54
Hi @PatrykMakowski,

Thanks for your report.
We are aware of this issue and we are working on it.
No, this issue is in progress, it is assigned to our developer Jocelyn Fournier, he is working on it.
Thanks for your patience
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-11 10:54
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2019-03-11 10:54 UTC
Labels: Duplicate
