### ISSUE TITLE
Error accessing json files in translation folder

### ISSUE THREAD

**Issue by TBurtin** [PrestaShop/PrestaShop#10183] opened 2018-08-29 10:15 UTC
The BO product form page try to access to some .json files in the translation folder, but the .htaccess file in that folder has a "Require all denied" rule.

![image](https://user-images.githubusercontent.com/42802847/44781366-731b4580-ab84-11e8-9539-b21a2d9d9f81.png)

````
# Apache 2.2
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>
````

The issue appears in Apache 2.4 in 1.7.4. On previous versions, the .htaccess file was different (only for Apache 2.2)

It generate lots of errors in Apache error logs, and the json contents are probably needed somewhere in the forms

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-08-29 10:17
Hi @TBurtin,

Could you please add steps to reproduce the issue in a new comment.

Best regards, Khouloud

**Comment by Quetzacoalt91** [comment] 2018-08-29 10:18
Hi,

We are aware of that issue, which will be fixed in the next version of PrestaShop.
You can find more details here: https://github.com/PrestaShop/PrestaShop/pull/9474

I'm closing as this is a duplicate.
Regards

**Closed as completed by Quetzacoalt91** 2018-08-29 10:18 UTC
Labels: Bug, Duplicate, 1.7.4.2

**Comment by khouloudbelguith** [comment] 2018-08-29 10:20
Duplicate of #9474

**Comment by feyll** [comment] 2019-01-23 22:04
hi I have the same error with 1.7.4.2 I can not update my site to later versions but I have to keep this version. please can you tell me how I can solve?

**Comment by TBurtin** [comment] 2019-01-24 08:18
Hi, you can replace the content of the translations/cldr/.htaccess file with that;
````
# Apache 2.2
<IfModule !mod_authz_core.c>
    Order deny,allow
    Allow from all
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
    Require all granted
</IfModule>
````

It's the content of the file in 1.7.5 where the bugs is solved.

**Comment by khouloudbelguith** [comment] 2019-01-24 08:29
Hi @feyll,

Here's the change made in the PS1.7.5.0 https://github.com/PrestaShop/PrestaShop/pull/9474/files to fix the issue.
Thanks!

**Comment by feyll** [comment] 2019-01-24 12:55
Thank you very much for your answers, now I have solved thanks to you. I wish you a good job and a good day.
