### ISSUE TITLE
[FO] gift product and manually added products do not get separated in cart.

### ISSUE THREAD

**Issue by moflihmorad** [PrestaShop/PrestaShop#21041] opened 2020-09-17 13:51 UTC
#### Describe the bug

adding a cart rule allowing a customer a free gift appears as a normal product in the cart product listing

#### Expected behavior

According to the classic theme tpl this should appear as a gift product
1) the quantity of a gift product cannot be modified, but the bug allows this
2) the price of a gift product should not show up, the FREE tag should appear instead.
3) gift product cannot be deleted unless the cart rule is deleted from cart

#### Steps to Reproduce

1. BO > Catalog > Discounts > create a Cart Rule with a free gift as Action and chose a product to give for free.
2. FO > Add whatever product to cart > Go to cart > Add cart rule using the code generated in BO.
3. You will see that the gift product behaves the same as the manually added product.

**Screenshots**

![issue](https://user-images.githubusercontent.com/71391149/93479330-18342280-f8f4-11ea-875c-bb12681b509c.png)

#### Additional information
in themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl which is responsible for displaying product listing
the $product.is_gift value is used to differentiate between gift and none gifts 
this value is set in Cart.php > getProductsWithSeparatedGifts()
but it is removed in CartPresenter.php > PresentProduct() where the $rawProduct Array is turned into $product lazy array.

**Comment by florine2623** [comment] 2020-09-17 15:13
Hi @moflihmorad ,
Thanks for the issue. I have reproduced it in PS 1.7.6.5 and PS 1.7.7.0.
I will ping our product team to get an official answer.
Please stay tuned.

**Comment by florine2623** [comment] 2020-09-17 15:14
ping @PrestaShop/product-team ,
I indeed reproduce what @moflihmorad explained in his issue.
Isn't that the way it is supposed to work ?
If not, can that be added as an improvement in the next versions ?
Thanks!

**Comment by moflihmorad** [comment] 2020-09-17 16:21
thank you @florine2623 
i suppose it is not the way it should work, because if you keep adding the quantity of the gift product the discount adds up too. the customer should never be allowed to change gift quantity.

**Comment by Hlavtox** [comment] 2020-09-17 16:57
@moflihmorad This bug is not fixed for more than 3 years... https://github.com/PrestaShop/PrestaShop/issues/9757

Until it's fixed, use my solution here - https://github.com/PrestaShop/PrestaShop/issues/9757#issuecomment-691047001

**Comment by khouloudbelguith** [comment] 2020-09-25 09:25
Hi @Hlavtox,

Thanks for the feedback!
@moflihmorad, thank you for the report.
Your ticket is a duplicate of #9757
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-25 09:25
Duplicate of #9757

**Closed as completed by khouloudbelguith** 2020-09-25 09:25 UTC
Labels: FO, Duplicate, Discounts, Shopping carts FO
