### ISSUE TITLE
ps_emailsubscription not add new suscriptors

### ISSUE THREAD

**Issue by messplay** [PrestaShop/PrestaShop#27378] opened 2022-01-17 23:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when I test add new susciption , this not update, I test with clasic theme and custom theme, not receiven email confirmatione either, I test my email module send me test email and work fine

![image](https://user-images.githubusercontent.com/5551700/149847473-563b8a43-ed36-4110-a779-b2d67ad78f7e.png)

### Expected behavior

Sending confirmation email, with voucher code and new suscriptor on the list

### Steps to reproduce

1. Add my email to newsletter suscription
2. go to email suscripttion module
3. new suscriptor not available

### PrestaShop version(s) where the bug happened

1.7.8.2

### If your bug is related to a module, specify its name and its version

ps_emailsuscription

**Comment by marwachelly** [comment] 2022-01-18 15:27
Hello,

Thank you for your report, We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of [#26698]
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment] 2022-01-18 15:27
Duplicated to [#26698]

**Closed as completed by marwachelly** 2022-01-18 15:27 UTC
Labels: Bug, Duplicate, Invalid
