### ISSUE TITLE
First column in configure main menu screen has no enough space

### ISSUE THREAD

**Issue by eopws** [PrestaShop/PrestaShop#26054] opened 2021-10-01 18:23 UTC
#### Describe the bug

'Change position' label in Modules/ps_mainmenu/Configure has no enough space and next columns overlay it

#### Expected behavior

![after](https://user-images.githubusercontent.com/42320170/135668183-61d2f246-d266-403a-b85f-ab2f7b2df959.png)

#### Steps to Reproduce

1.) go to module manager
2.) click on configure Main menu module button
3.) in 'Menu Top Link' section you can see the issue

**Screenshots**

![test](https://user-images.githubusercontent.com/42320170/135667977-a4614c99-4b84-42d3-a3f1-0886f0bfc25a.png)

#### Additional information

my monitor is 20 inches with 1600x900 resolution

**Comment by hibatallahAouadni** [comment] 2021-10-04 09:44
Hello @eopws 

I didn't manage to reproduce the issue with PS1778 and 1600x900 monitor, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/135829601-eb4c2df6-424e-4130-ac73-f6671263f5cf.png)

Could you please provide your PrestaShop version :pray: 
Please check and feedback.

Thanks!

**Comment by eopws** [comment] 2021-10-04 13:40
Hello, @hibatallahAouadni.
The version of my prestashop is 1.7.8.1

**Comment by hibatallahAouadni** [comment] 2021-10-04 16:41
Hello @eopws 

> The version of my prestashop is 1.7.8.1

How's that we didn't release yet the 1.7.8.1 :sweat_smile: 
Did you mean the develop branch or the 1.7.8.x branch?

Thanks!

**Comment by eopws** [comment] 2021-10-05 07:12
I downloaded my prestashop from source code on github, so I have dev version 1.7.8.1.

**Comment by florine2623** [comment] 2021-10-05 09:56
Hello @eopws ,

Thanks for the report. I was able to reproduce the issue with PrestaShop version 1.7.8.1, so I can confirm that this behavior is indeed a bug :
<img width="966" alt="Screenshot 2021-10-05 at 11 51 28" src="https://user-images.githubusercontent.com/16019289/136001437-25b7a8f0-22dd-46d9-bddd-2281cd305a0b.png">

How it was in PS 1.7.7.8 :
<img width="978" alt="Screenshot 2021-10-05 at 11 51 34" src="https://user-images.githubusercontent.com/16019289/136001495-42941e1d-8cd0-4278-b313-edff2eb0e582.png">

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2022-06-16 13:12 UTC
Labels: Bug, Trivial, BO, Regression, Mainmenu, Fixed, Module manager, Front-end, PR available, Responsive, 1.7.8.0, Verified, Module
