### ISSUE TITLE
Webservice - Stock issue when adding a new product via WS

### ISSUE THREAD

**Issue by jonasburneika** [PrestaShop/PrestaShop#20406] opened 2020-07-31 12:01 UTC
#### Expected behavior

After product stock update via API call, expecting to see product stock movement.

#### Steps to Reproduce

1. execute StockAvailable::setQuantity(8, 0, 100000); // Default Mug Today is a good day product_id  - 8
2. Go to page: /admin/index.php/sell/stocks/movements
3. There is no info about product stock update

#### Additional information

* PrestaShop version: 1.7.3.3
* PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-08-03 13:11
Hi @jonasburneika,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #17748
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-03 13:11
Duplicate of #17748

**Closed as completed by khouloudbelguith** 2020-08-03 13:11 UTC
Labels: Duplicate
