### ISSUE TITLE
Payment amount not updated at 2nd checkout try

### ISSUE THREAD

**Issue by fall-en** [PrestaShop/PrestaShop#24877] opened 2021-06-08 16:00 UTC
#### Describe the bug

Hello, I have an issue with credit card payment.
Tested with Prestashop Checkout and Stripe Official modules, so maybe it's a core bug.

The total amount to pay is not updated correctly if you add or remove products from the cart at 2nd (3rd, 4th, ecc) 
 payment with credit card try.

#### Steps to Reproduce

1. Add products to cart (example cart total is € 15)
2. Checkout with credit card
3. When credit card pin request modal it's showed, cancel the payment clicking cancel on the modal window
4. Prestashop Checkout will show out an error (Card holder authentication failed...)
5. Add or remove products from the cart (example new cart total is € 10)
6. Checkout again with credit card
7. When credit card pin request modal appear check the charged amount showed in the modal. Also check the amount in your SMS or App for the confirmation of the payment. It will show you € 15 to pay, the first cart you checked out with. And not € 10 the cart you checking out.

The charged amount will never update till I will delete the cart from BO.
In FO Prestashop calculate and show correctly the cart total, issue is only when you go to pay with credit card, the charged amount is not updated.

Issue will not occour with PayPal Official module, or if you select pay with PayPal in Prestashop Checkout module.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.28

**Comment by hibatallahAouadni** [comment] 2021-06-09 14:18
Hello @fall-en 

Could you please provide a screen record cause I tried to reproduce the issue in vain. 
Even some screenshots will be helpful :pray: 

PS: Thanks @SD1982 for help :wink: 

Thanks!

**Comment by fall-en** [comment] 2021-06-09 16:28
Hello @hibatallahAouadni 

Yes of course here it is the complete process with screenshots, let me know if is enough to reproduce the issue:

1. First cart is created, cart and checkout match correctly
![1 - first cart](https://user-images.githubusercontent.com/48456655/121392090-59230a00-c94f-11eb-9366-d6e09de217ee.png)

2. Payment is canceled by clicking  "Cancel" (Annulla) in the modal window. Error will be shown by Prestashop Checkout
![2 - first order payment canceled](https://user-images.githubusercontent.com/48456655/121392318-8ec7f300-c94f-11eb-923c-77655e9c1a1f.png)

3. Update cart by removing something, or reducing number of products, and checkout again. Payment value will not match cart value
![3 - update cart lower value](https://user-images.githubusercontent.com/48456655/121392512-c20a8200-c94f-11eb-8e2f-2c6d201f86a2.png)

4. You can try to do same by adding products to cart so value of the cart will be higher. Payment value will not match cart value
![4 - update cart higher value](https://user-images.githubusercontent.com/48456655/121393084-4826c880-c950-11eb-9be3-bbb34d46ced0.png)

**Comment by hibatallahAouadni** [comment] 2021-06-16 15:55
Hello @fall-en 

Thanks for your patience :pray: 
Your screenshots show a modal of your payment module, so I think the problem is with the payment module.
Have you checked with the developer of the module?
Please check and feedback.

Thanks!

**Comment by fall-en** [comment] 2021-06-16 17:09
Hello @hibatallahAouadni 

Thank you for your reply. Yes, I thought the same first time I have encountered this issue. So i dediced to send bug report to Prestashop Checkout team (it was March/April). In this months they have not solved this issue.

At this point, 2 weeks ago, I decided to change payment module and try with Stripe Official module (https://addons.prestashop.com/it/pagamento-carta-credito-wallet/24922-stripe-official-dotato-di-sca.html) to check if it is a module issue or maybe a Prestashop bug. With Stripe payment module the bug is still there.

Possible issue:

1. Maybe when cart is updated Prestashop do not updated some kind of information usefull for card payment?
2. Modules keep in memory firts generated "token" (?) and keep sending it without updating it after the cart is updated?

**Comment by FolleRumba** [comment] 2021-06-21 23:54
Same problem with my installatation: PrestaShop version: 1.7.7.2

I tried to update prestashop to 1.7.7.5 but the issue still remains both in prestashop checkout and in stripe. PayPal works.

**Comment by florine2623** [comment] 2021-06-22 14:46
Hello @fall-en & @FolleRumba 

I tested with PrestaShop Checkout v2.15.3
I can't reproduce your issue.

There's a difference between the shop browser and the PS Checkout window :
![image](https://user-images.githubusercontent.com/16019289/122944638-48738a80-d378-11eb-9dd2-7df2ef8d7845.png)

But when you refresh your shop page, it will be updated with the correct cart :
![image (2)](https://user-images.githubusercontent.com/16019289/122946049-54138100-d379-11eb-8b15-3411e03450ab.png)

**Comment by FolleRumba** [comment] 2021-06-22 15:26
Hi @florine2623, the issue is when you pay by credit card. PayPal works fine.

Try to pay with credit card instead of paypal and then cancel the payment when you are in the windows of 3d secure and after that edit the cart you will have the issue.

**Comment by florine2623** [comment] 2021-06-22 16:25
Hello @FolleRumba ,

You said "the issue still remains both in prestashop checkout and in stripe." so I tried with PS Checkout and it works well.
What module are you using for paying with credit card ?

Thanks

**Comment by FolleRumba** [comment] 2021-06-22 16:49
Hello @florine2623 correct both in stripe and prestashop checkout, but in the latter you have to pay with credit card to get the issue.

Please check the screenshot of @fall-en he explained it very well

**Comment by fall-en** [comment] 2021-06-22 20:17
Hello @florine2623 

Please read full bug report in my first post. To be specific:

> Issue will not occour with PayPal Official module, or if you select pay with PayPal in Prestashop Checkout module.

The bug will occur if your try to pay with credit card using Prestashop Checkout and Official Stripe modules. I have only tested this two modules.

**Comment by FolleRumba** [comment] 2021-06-22 20:28
@fall-en I found a way to correct the bug directly in the Stripe module. But I don't know if this is the the right place to describe it, cause it involves a file of the module and not in the core of prestashop

**Comment by fall-en** [comment] 2021-06-22 21:14
@FolleRumba I have opened a bug report with 202 ecommerce (author of the Stripe module) few days ago. Please contact them and let them know.

Also if you can, please check if same workaround works with Prestashop Checkout too.

Anyway I think you can write it here maybe it involve PS indirectly. What do you think @hibatallahAouadni ?

**Comment by FolleRumba** [comment] 2021-06-23 09:49
@fall-en it's not an official fix but it appears to resolve this issue on Stripe Official 2.3.1.

File _modules\stripe_official\controllers\front\createIntent.php_

Just add:

```
$intent = \Stripe\PaymentIntent::update(
      $stripeIdempotencyKey->id_payment_intent,
            [
                'amount' => $amount
            ]
);
```

after `$intent = \Stripe\PaymentIntent::retrieve($stripe_idempotency_key->id_payment_intent);` line 139

The final resolt should be:

```
if ($stripe_idempotency_key->id == '') {
                $idempotency_key = $this->context->cart->id.'_'.uniqid();

                $intent = \Stripe\PaymentIntent::create(
                    $datasIntent,
                    [
                      'idempotency_key' => $idempotency_key
                    ]
                );

                $stripeIdempotencyKey->id_cart = $this->context->cart->id;
                $stripeIdempotencyKey->idempotency_key = $idempotency_key;
                $stripeIdempotencyKey->id_payment_intent = $intent->id;
                $stripeIdempotencyKey->save();

                $paymentIntent = new StripePaymentIntent();
                $paymentIntent->setIdPaymentIntent($intent->id);
                $paymentIntent->setStatus($intent->status);
                $paymentIntent->setAmount($intent->amount);
                $paymentIntent->setCurrency($intent->currency);
                $paymentIntent->setDateAdd(date("Y-m-d H:i:s", $intent->created));
                $paymentIntent->setDateUpd(date("Y-m-d H:i:s", $intent->created));
                $paymentIntent->save(false, false);
            } else {
                $intent = \Stripe\PaymentIntent::retrieve($stripe_idempotency_key->id_payment_intent);

                $intent = \Stripe\PaymentIntent::update(
                    $stripeIdempotencyKey->id_payment_intent,
                    [
                        'amount' => $amount
                    ]
                );

            }
```

**Comment by fall-en** [comment] 2021-06-23 13:33
@FolleRumba thank you. I have just received a reply from Stripe author. They sent me a beta version of the new update that should solve the bug. I will update you as soon i will be able to try it.

**Comment by khouloudbelguith** [comment] 2021-06-25 09:37
Hi @fall-en, @FolleRumba,

Thank you for the solution.
It seems that your issue is not a PrestaShop core bug.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 
If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We will close this issue.

Thanks!

**Closed as completed by khouloudbelguith** 2021-06-25 09:37 UTC
Labels: Bug, FO, Payment methods, No change required, Checkout, 1.7.7.4

**Comment by fall-en** [comment] 2021-06-25 13:05
@khouloudbelguith thank you, yes it seems not a core bug.
Today I have received a mail from Prestashop Checkout team and they confirmed they are aware of this bug and will solve it.

Thank you!

**Comment by bsh** [comment] 2021-09-17 16:06
> @khouloudbelguith thank you, yes it seems not a core bug.
> Today I have received a mail from Prestashop Checkout team and they confirmed they are aware of this bug and will solve it.
> 
> Thank you!

Hi! Do you have any update on this?

**Comment by fall-en** [comment] 2021-09-28 22:22
> > @khouloudbelguith thank you, yes it seems not a core bug.
> > Today I have received a mail from Prestashop Checkout team and they confirmed they are aware of this bug and will solve it.
> > Thank you!
> 
> Hi! Do you have any update on this?

@bsh I checked it with last update and issue was still not solved.

**Comment by bsh** [comment] 2021-09-29 06:40
Stripe Official fixed this:
2.3.2 @yves202 yves202 released this on Jul 15
[] Create new payment intent when returning in checkout after selecting the payment method
