### ISSUE TITLE
BO > Orders - Exception displayed when I create a credit slip with only Shipping cost

### ISSUE THREAD

**Issue by Mel-meel** [PrestaShop/PrestaShop#35802] opened 2024-04-02 15:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,

It is impossible to display the order slip PDF document when the order contain a one product's reduction and the order slip is about shipping cost.

![Capture_d_écran_2024-04-02_123550](https://github.com/PrestaShop/PrestaShop/assets/115707501/064b4dd2-44eb-43f7-bbe7-b1485a4a3f37)

Log just contain the following content :

` [2024-04-02 15:17:21] request.CRITICAL: Uncaught PHP Exception TypeError: "PrestaShop\PrestaShop\Core\Util\Sorter::natural(): Argument #1 ($array) must be of type array, null given, called in /var/www/html/prestashop8-test/classes/pdf/HTMLTemplateOrderSlip.php on line 167" at /var/www/html/prestashop8-test/src/Core/Util/Sorter.php line 43 {"exception":"[object] (TypeError(code: 0): PrestaShop\\PrestaShop\\Core\\Util\\Sorter::natural(): Argument #1 ($array) must be of type array, null given, called in /var/www/html/prestashop8-test/classes/pdf/HTMLTemplateOrderSlip.php on line 167 at /var/www/html/prestashop8-test/src/Core/Util/Sorter.php:43)"} [] `

Please note : my using Prestashop is full-vanilla.

Thanks.
Mel

### Steps to reproduce

1. Make a reduction for a specific product
2. Make an order by the Backoffice admin interface :
    1. Order the product
    2. Order another product
    3. Apply the reduction for the first product
    4. Set the command as "payment accepted"
    5. Make sure the command has no free shipping
3. Set the command to "delivered"
4. Make an order slip for the order :
    1. Click "partial refund"
    2. just put the shipping cost in the order slip
    3. Apply
5. Try display de order slip -> 500 internal error

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1.27

**Comment by florine2623** [comment] 2024-04-04 10:19
Hello @Mel-meel ,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.
On `8.0.x` and `develop` branch, it works correctly.

It is the same issue as : https://github.com/PrestaShop/PrestaShop/issues/33890
it was fixed, but the bug seems to be back.

https://github.com/PrestaShop/PrestaShop/assets/16019289/77beda89-1695-4dc1-83a1-2a6573b23dec

> PrestaShop\PrestaShop\Core\Util\Sorter::natural(): Argument #1 ($array) must be of type array, null given, called in /Users/fHea/Desktop/ps810/classes/pdf/HTMLTemplateOrderSlip.php on line 167

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Mel-meel** [comment] 2024-04-04 14:01
Hi @florine2623, thank you very much for your answer, i will try downgrade to Prestashop 8.0.x.

Regards,

Mel

**Closed as completed** 2024-04-17 12:58 UTC
Labels: Bug, Major, BO, Order, Credit notes, Verified, 8.1.x

**Comment by dalel123** [comment] 2024-12-18 10:14
IL faut juste modifier la ligne 167 par ce code : 
if (!empty($order_details) && is_array($order_details)) {
    $order_details = $sorter->natural($order_details, Sorter::ORDER_DESC, 'product_reference', 'product_supplier_reference');
} else {
    error_log('Order details are empty or not an array.');
}
