### ISSUE TITLE
Shopping cart is not working properly

### ISSUE THREAD

**Issue by Elsximplets** [PrestaShop/PrestaShop#11369] opened 2018-11-13 15:30 UTC
**Describe the bug**
The add to cart button behaves differently depending on whether you are adding items or packs (managed with Advanced pack 5)
The following buttons do the action they should do but do not refresh the page automatically:
Add to cart in product page (simple article) direct link: https://elsximplets.cat/tasses/45-tassa-quins-pebrots.html
-Icon to add to cart on top of miniature of the Home (simple article) direct link to the home; https://elsximplets.cat
- Button "x" page of the shopping cart to remove products. (to check it, add product to the cart and then try to remove it)

The add to product page (pack) button redirects you directly to the shopping cart, but does not add the item to the cart.
Direct link to pack product page: https://elsximplets.cat/samarretes-home/222-854-samarreta-home-torracollons-blau-mari.html#/79-ap5_pack-222_defaultcombination

**Additionnal information**
Today I uninstalled the module (to then reinstall it again) and when I had the module uninstalled, I also went to the classic theme to rule out errors in my template, and the behaviors (except for the pack, because it was uninstalled) were the same.

In addition to the packs management module, I use the Alysum template.
PrestaShop version: 1.7.4.4
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-11-13 16:02
Hi @Elsximplets,

I did not manage to reproduce the issue with PS1.7.5.0beta1 / PS1.7.4.4
I attached a video record.
https://drive.google.com/file/d/1JFVZZMC0V6NNXPy3gfdWlPcZYO8KDsJQ/view
Thanks to check & feedback

**Comment by khouloudbelguith** [comment] 2018-12-14 17:20
Hi @Elsximplets,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-14 17:20 UTC
Labels: Bug, FO, Shopping carts, Pack, No change required
