### ISSUE TITLE
Missing specfic references in product detail screen

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19739] opened 2020-06-14 17:25 UTC
#### Describe the bug
There are missing ISBN and EAN codes in detail product page.

#### Expected behavior
If ISBN and EAN codes are filled they should be displayed as Specific references in the section Product details.

**Screenshots**
Product > Options > ISBN and EAN codes are filled
![image](https://user-images.githubusercontent.com/33311857/84599750-aff91f00-ae74-11ea-8eed-7de1271934f1.png)

Missing ISBN and EAN codes
![image](https://user-images.githubusercontent.com/33311857/84599760-bbe4e100-ae74-11ea-9581-0523b5731f9c.png)

* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by matthieu-rolland** [comment] 2020-06-15 09:27
We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #19685

To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you!

**Closed as completed** 2020-06-15 09:28 UTC
Labels: Duplicate
