### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by Oanaalexandramihai** [PrestaShop/PrestaShop#17601] opened 2020-02-11 12:26 UTC
Hello,

I have presta 1.7.5.1, and when I try to move a module I receive the error 500 and log me out from my shop. Can anybody help me? Thank you!

![Screenshot 2020-02-08 at 17 18 13](https://user-images.githubusercontent.com/60925508/74236552-1f4ddf00-4cda-11ea-91fe-5e25b19da2de.png)
![Screenshot 2020-02-08 at 17 16 47](https://user-images.githubusercontent.com/60925508/74236567-2bd23780-4cda-11ea-9dac-9f4729f2c1c9.png)

**Comment by khouloudbelguith** [comment] 2020-02-11 13:14
Hi @Oanaalexandramihai,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-12 07:57
Hi @Oanaalexandramihai,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-12 07:57 UTC
Labels: Bug, BO, Positions, No change required, 1.7.5.1
