### ISSUE TITLE
product-availability-date is always US format in Spanish language

### ISSUE THREAD

**Issue by cesarfierro** [PrestaShop/PrestaShop#12947] opened 2019-03-17 08:57 UTC
Hello

Prestashop 1.7.5.1

At the front office, product page always shows the product-availability-date in US format (yyyy-mm-dd) instead of dd-mm-yyyy.

Regards
Cesar

**Comment by khouloudbelguith** [comment] 2019-03-18 07:57
Hi @cesarfierro,

We are aware of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #9591
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-18 07:57
Duplicate of #9591

**Closed as completed by khouloudbelguith** 2019-03-18 07:57 UTC
Labels: Duplicate
