### ISSUE TITLE
Editing order - value of an item

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#15809] opened 2019-10-03 12:56 UTC
BO-> Orders -> Edit order -  If you want to edit price of any product and set it to 0.00 (should be available), you'll receive an alert message: Error: Product price must be set
However if you would like to add any product to the same order with 0.00 price, you are able to. But if you would like to change the product with zero price later (change the qty), you cannot because you'll receive the same error message: Error: Product price must be set

So, if we are able to add a product with price set to 0.00, we should be able to:
a/ edit the very same product later (change qty)
b/ change price of any product that is already on the order to 0.00

**Additional information**
PrestaShop version: 1.7.6.1 
PHP version: 7.2.23

**Comment by khouloudbelguith** [comment] 2019-10-03 13:08
Hi @mrabsinthe,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9830
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-03 13:08
Duplicate of #9830

**Closed as completed by khouloudbelguith** 2019-10-03 13:08 UTC
Labels: Duplicate
