### ISSUE TITLE
Bad display with modal

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11042] opened 2018-10-17 08:45 UTC
**Describe the bug**
Modal are hidden under the header in differents pages

**To Reproduce**
1. Go to Modules > Modules catalog or Catalog > Product
2. Click on Install a module or select many products and click on bulk action > duplicate
3. See the modal

**Screenshots**

![capture d ecran_443](https://user-images.githubusercontent.com/13449658/47073938-a7f95f80-d1f9-11e8-988e-0afd791213f7.png)

![capture d ecran_445](https://user-images.githubusercontent.com/13449658/47077052-64eeba80-d200-11e8-95e2-f52330017652.png)

![capture d ecran_447](https://user-images.githubusercontent.com/13449658/47079883-d2054e80-d206-11e8-805e-c40d8fba31d5.png)

Should be like this

![capture d ecran_444](https://user-images.githubusercontent.com/13449658/47073952-b0ea3100-d1f9-11e8-8d81-e02b1b3fb7b4.png)

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment] 2018-10-17 10:58
This is caused by this freshly merged PR https://github.com/PrestaShop/PrestaShop/pull/10436

**Comment by khouloudbelguith** [comment] 2018-10-17 11:04
Hi @marionf,

The same issue happens in the symfony pages.
If we click on the "Setting" icon => Sow SQL query => the modal is behind the header.
Product page:
![image](https://user-images.githubusercontent.com/16067358/47082161-0bd95380-d20d-11e8-960c-dbe18375775f.png)
SEO & URLs page
![image](https://user-images.githubusercontent.com/16067358/47082189-1dbaf680-d20d-11e8-9f4e-555553a20644.png)
Thanks!

**Closed as completed** 2018-11-26 09:05 UTC
Labels: Bug, Major, BO, Modules catalog, Regression, Fixed, Front-end
