### ISSUE TITLE
Upgrade ps_googleanalytics to use gtag.js instead of analytics.js ?

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#21357] opened 2020-10-08 08:03 UTC
Hi
Google sends emails about the new upgrade of its tracking script to use the new gtag.js

![1](https://user-images.githubusercontent.com/653230/95427529-002a4e80-0948-11eb-82e2-86fbb9a05784.png)

is it possible to upgrade it?

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2
* module version: 4.0.0

**Comment by matks** [comment] 2020-10-08 08:08
Related to https://github.com/PrestaShop/ps_googleanalytics/issues/78

**Comment by SimonGrn** [comment] 2020-10-08 08:30
Hello @maofree 

Thank you for your issue. We already have an issue for this improvement, and it will be taken care of as soon as possible.

I close this issue as it's a duplicate of https://github.com/PrestaShop/ps_googleanalytics/issues/78 (thank you @matks )

Regards

**Closed as completed by SimonGrn** 2020-10-08 08:30 UTC
Labels: Duplicate, Google Analytics

**Comment by khouloudbelguith** [comment] 2020-10-08 10:18
Duplicate of https://github.com/PrestaShop/ps_googleanalytics/issues/78

**Comment by matks** [comment] 2023-03-04 21:49
Release 4.2.0 of module ps_googleanalytics should provide GA4 support

https://github.com/PrestaShop/ps_googleanalytics/pull/131
