### ISSUE TITLE
Wrong product details editing

### ISSUE THREAD

**Issue by UbuMarketing** [PrestaShop/PrestaShop#33656] opened 2023-08-18 14:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When i try to add some feature to an existing product in my back-office, like the "color" or "size" or "material" prestashop let me save them and update the new settings. The problem is that when i open that product after an houre, the editing i did is not present anymore as i did nothing. 

### Expected behavior

The expected behaviour is that the new feature i add to a product will be saved and persistant to the product untill i edit them another time. 

### Steps to reproduce

1. Go to "catalog"
2. Click on "product"
3. edit one product
4. click "aggiungi una caratteristica"
5. and save all
6. after one hour check if the modify is still present or not
7. 

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment] 2023-08-23 08:15
Hello @UbuMarketing 

I couldn't reproduce the issue with PS811, 8.1.x and develop, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/8c32f4d1-71dd-4678-9ded-c5a6d3e8ac9e)

Even after an hour, the feature still there. Could you please provide more infos 🙏 
Waiting for your feedback.

Thanks!

**Comment by UbuMarketing** [comment] 2023-08-25 07:50
Hi, thanks for your reply. 
You have perfectly understood my issue, but when i add a feature to a catalog product, this feature will no longer be visible after an hour.

**Comment by hibatallahAouadni** [comment] 2023-08-29 12:43
Hello @UbuMarketing 

It's been more than one hour and still the feature is displayed in BO and FO, see the attached screenshots below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/1ae9bed6-4351-4d93-9d12-0e2561437ae3)

### BO

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/d908d6a4-5bd7-445c-99bd-b2333175f7e6)

### FO

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/b85a9ec5-a842-4a39-834c-94017707e26b)

Please check and feedback.

Thanks!

**Comment by UbuMarketing** [comment] 2023-08-31 09:25
Gentile assistenza,

io ho provato ad effettuare delle modifiche ai prodotto con seguente 
riferimento 00206,01197,02288. Nello specifico ho provato ad aggiungere 
la marca del prodotto ma non riesco più a visualizzare queste modifiche. 
Può gentilmente illustrarmi la procedura perchè a questo punto l'unica 
cosa che mi viene da pensare è che commetto un errore nella modifica del 
prodotto.

Il 2023-08-29 12:43 Hibatallah Aouadni ha scritto:

> Hello @UbuMarketing [1]
> 
> It's been more than one hour and still the feature is displayed in BO 
> and FO, see the attached screenshots below:
> 
> [2]
> 
> BO
> 
> [3]
> 
> FO
> 
> [4]
> 
> Please check and feedback.
> 
> Thanks!
> 
> --
> Reply to this email directly, view it on GitHub [5], or unsubscribe 
> [6].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/UbuMarketing
[2] 
https://user-images.githubusercontent.com/23308427/264021652-1ae9bed6-4351-4d93-9d12-0e2561437ae3.png
[3] 
https://user-images.githubusercontent.com/23308427/264021719-d908d6a4-5bd7-445c-99bd-b2333175f7e6.png
[4] 
https://user-images.githubusercontent.com/23308427/264021946-b85a9ec5-a842-4a39-834c-94017707e26b.png
[5] 
https://github.com/PrestaShop/PrestaShop/issues/33656#issuecomment-1697371934
[6]

**Comment by aniszr** [comment] 2023-08-31 14:40
Hello @UbuMarketing 

Please send your request in English. English is the norm on GitHub.

Could you please check the table  `ps_feature_product` in Database and check if the feature assigned to the product is well saved or not!

Thank you!

**Comment by hibatallahAouadni** [comment] 2023-09-18 07:49
Hello @UbuMarketing 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-18 07:49 UTC
Labels: Bug, BO, Features, Invalid, 8.1.x, Products Page
