### ISSUE TITLE
Seo Url, incorrect category path in product url 

### ISSUE THREAD

**Issue by mkdgs** [PrestaShop/PrestaShop#31827] opened 2023-03-17 16:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
This issue is about Url generated for product page.
Assume this:
a category **foo** with id **321**
a product   **baz** with id **123** 
Rewrite for SEO url is set to defaut:
see [documentation](https://docs.prestashop-project.org/1.7-documentation/v/french/guide-utilisateur/configurer-boutique/configurer-parametres-boutique/trafic/seo-et-url)

The Url path of generated for category is:
/**321-foo**
For product url is:
/**foo**/baz-123.html

the product URL not reflect the category path of the URL for category 
Note: actually it's not working like mentioned in first part of the documentation:
`By default, PrestaShop's deep URLs (that is, specific pages rather than online the domain name) are uninformative to both customers and search engines: a URL such as http://www.myprestashop.com/product.php?id_product=27 does not help visitors know what product is on that page. Friendly URLs are the way to achieve that and get for instance http://www.myprestashop.com/2-music-players/27-ipod-nano-green.`

### Expected behavior

Show the correct categories path in Url, according to the rewrite Rule for categories

the correct url path is:
shop.com/**321-foo**/123-baz.html
NOT 
shop.com/**foo**/123-baz.html

### Steps to reproduce

1-  SEO Url  is set to defaut:
see [documentation](https://docs.prestashop-project.org/1.7-documentation/v/french/guide-utilisateur/configurer-boutique
2- add category and product, see url of product with a main category

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment] 2023-03-17 20:50
@mkdgs Can you please provide more clear information, the issue is not understandable, sorry.

And I am afraid that rewriting works perfectly for many many years and you just don't understand the way it works. 👍

**Comment by mkdgs** [comment] 2023-03-18 07:19
@Hlavtox, no, that's not working like expected since many many years :)

But, i agree it's was unclear, i have edited the issue, so please take a look and come back if you need more detail.
See the code and unlock the PR

**Comment by Hlavtox** [comment] 2023-03-18 08:11
@mkdgs Yes, now I understand what you mean, and the current behavior is correct.

Product URLs look like this `/foo/baz-123.html` at least 7 years I use Prestashop. The category prefix does NOT contain the full path or the category ID.

**Comment by mkdgs** [comment] 2023-03-18 09:32
@Hlavtox it's exactly what i said, not correct since many year, actually not correct for SEO, actually not correct regarding the documentation, actually simply not corresponding to the logic.

Your personnal experience is not an argument, personnaly my first PR on prestashop ten year ago... and i have contributed to many project i've a little experience... and i'm trying to stay open to change ;)

**Comment by SharakPL** [comment] 2023-03-18 10:59
@Hlavtox is right. You should look up "friendly URL" 😉
Without it the link to the product looks like this:

`http://exampleshop.com/index.php?id_product=20&controller=product`

As you can see there's nothing about category, but with friendly urls enabled you can use whatever you want in urls as long as there's clear identifier for a product. Generally it's ID and thus only this number is required. Check Preferences > Traffic > URL scheme in your shop's admin panel for more.

Also developers rather try to remove all numbers from the URL and leave just specific names there to improve SEO so adding more numbers to url would be wrong.

**Comment by mkdgs** [comment] 2023-03-18 11:30
@SharakPL sorry, i think you don't understand the point. please read the doc and this issue.

I know very well what is friendly URL, prestashop is weak on that.
And no you can't do whatever you want, and you can't have logic and consistency path generated by default.

`Also developers rather try to remove all numbers from the URL and leave just specific names there to improve SEO so adding more numbers to url would be wrong.`

It's another subject... Consistency against all path is better than removing things (id) without logic. if you don't want ID in url some third party module exist for that need.

**Comment by SharakPL** [comment] 2023-03-18 12:05
Then it's french docs that need changing, especially this iPod nano example which was last seen on prestashop 1.5 😉 Feel free to update it on PrestaShop/docs repo

**Comment by mkdgs** [comment] 2023-03-18 13:56
@SharakPL the only argument exposed is that it has always worked this way...  
I'm saying that is the wrong way and it has no logic.
The documentation, perhaps older, points out that this is a regression that has never been fixed.

And it's not only the french documentation:

https://docs.prestashop-project.org/1.7-documentation/user-guide/configuring-shop/shop-parameters/traffic/seo-and-urls#seoandurls-homepageseosettings

I let you fix the documentation if it's an error in it.

**Comment by SharakPL** [comment] 2023-03-20 00:14
Closing since there's nothing to fix on this repository. It should be done on [User-documentation repos](https://github.com/PrestaShop?q=user-documentation&type=all&language=&sort=)

**Closed as completed by SharakPL** 2023-03-20 00:14 UTC
Labels: Bug, PR available

**Comment by Hlavtox** [comment] 2023-03-23 10:54
@mkdgs Mickael, just to clarify, we are not against improvements of course. First, we should fix the documentation for now, so it is aligned with the current way the URLs are structured.

Then, we can start discussions on how they could be possibly improved. But my personal opinion is that it's probably good to leave it as it is, because the URLs are standardized for soooooo long. :-) And I think that adding category ID to it will bring absolutely no benefit. Search engines already understand the structure perfectly because of structured data etc.
