### ISSUE TITLE
Shipping costs not mentioned on invoice

### ISSUE THREAD

**Issue by nielsverhoeven84** [PrestaShop/PrestaShop#15411] opened 2019-09-05 07:26 UTC
When a customer places an order and pays with KBC paypage, the correct price is displayed in the KBC interface, but on the invoice generated by Prestashop, the shipping cost is 0 / free.

**Screenshots**
![Schermafbeelding 2019-09-05 om 09 25 20](https://user-images.githubusercontent.com/52320806/64320568-20f2d880-cfbf-11e9-82aa-75320a807e1c.png)

The order is 240 EUR  
The shipping is 32 EUR  (applied for weight < 4.9kg)

**Additional information**
PrestaShop version: 1.7.5.2

Where is defined not to display/calculate the shipping costs for the PDF?

**Comment by khouloudbelguith** [comment] 2019-09-05 09:31
Hi @nielsverhoeven84,

I did not manage to reproduce the issue with PS1.7.6.1 using the Paypal module.
https://drive.google.com/file/d/1tABUiMWTE8hj9TLnT2djZ2Z9FwL9A6pr/view
Have you tried to contact the module author about this issue?
Thanks to check with them & feedback.

**Comment by nielsverhoeven84** [comment] 2019-09-05 09:44
Hello @khouloudbelguith,

The payment module calculates the correct total, but the pdf invoice doesn't.
Isn't the pdf a default module of PS?

**Comment by khouloudbelguith** [comment] 2019-09-05 09:49
@nielsverhoeven84, yes the Pdf is generated by PrestaShop.
In my case it is OK.
Have you tried to use another payment module to check if the issue occurs again?

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-09-05 11:15
Hello @khouloudbelguith 
I did not try another module, since the payment module itself handles the correct price, so it must me in the system, but not processed on the pdf invoice

**Comment by khouloudbelguith** [comment] 2019-09-05 11:22
@nielsverhoeven84, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-09-13 07:25
Hello @khouloudbelguith 
In the overview, the price is wrong:
![Schermafbeelding 2019-09-13 om 09 23 06](https://user-images.githubusercontent.com/52320806/64844518-4fe4fc00-d608-11e9-82ce-53a8897a63a1.png)

and in the detail it is wrong, except for the payment with kbc:
![Schermafbeelding 2019-09-13 om 09 23 32](https://user-images.githubusercontent.com/52320806/64844534-5c695480-d608-11e9-89ce-711ccfeab7e4.png)

387 EUR is the correct price, so it was available in the system, just not stored correctly

**Comment by khouloudbelguith** [comment] 2019-09-13 09:23
Hi @nielsverhoeven84,

So i your case, The correct payemnt is 387 Eur => which is displayed in the KBC section, but in the other sections is incorrect (355Eur) because the shipping cost is missing.

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-09-13 09:30
Hello @khouloudbelguith 

I only have a PHP error log:  

[error.log.2.txt](https://github.com/PrestaShop/PrestaShop/files/3609346/error.log.2.txt)

**Comment by khouloudbelguith** [comment] 2019-09-13 09:48
@nielsverhoeven84, in your php error log you have only some warnings & PHP notice.
When debug mode enabled => there is no exception displayed?

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-09-13 09:51
@khouloudbelguith  debug wasn't enabled, I've enabled it now. Are there some general files that handle shipping costs in the admin interface? on the front end it shows shipping in every step of the checkout

**Comment by khouloudbelguith** [comment] 2019-09-13 14:01
@nielsverhoeven84, your issue is not reproduced in the FO => checkout steps.
But could you please check in the order confirmation page (after the payment step) if the shipping cost is correct or no?
![order_confirmation](https://user-images.githubusercontent.com/16067358/64868481-5ccd1400-d637-11e9-86b8-b1d7b934fce3.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-14 08:13
Hi @nielsverhoeven84,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-10-15 06:21
@khouloudbelguith  On the confirmation page, the price is also wrong (without shipping cost)

![Schermafbeelding 2019-10-15 om 08 17 58](https://user-images.githubusercontent.com/52320806/66805224-ba999800-ef24-11e9-9461-62e503051e33.png)

**Comment by khouloudbelguith** [comment] 2019-10-15 15:47
@nielsverhoeven84, in the checkout summary, same issue?
![image](https://user-images.githubusercontent.com/16067358/66847511-c95b6b80-ef73-11e9-8b83-36f9677e992b.png)

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-10-16 06:05
@khouloudbelguith no, in the check out the price is correct.
![Schermafbeelding 2019-10-16 om 08 04 17](https://user-images.githubusercontent.com/52320806/66892276-9785eb80-efeb-11e9-9fa0-cea96b86e608.png)

![Schermafbeelding 2019-10-16 om 08 03 20](https://user-images.githubusercontent.com/52320806/66892231-7624ff80-efeb-11e9-8fec-f4d8ab0c2867.png)

**Comment by khouloudbelguith** [comment] 2019-10-16 08:28
@nielsverhoeven84, did you use a condition of free shipping like this
Carrier ranges?
![image](https://user-images.githubusercontent.com/16067358/66901716-88109d80-efff-11e9-87e7-aaf712d54710.png)
Carrier preferences?
![image](https://user-images.githubusercontent.com/16067358/66901765-9e1e5e00-efff-11e9-84f1-72f9ffee5431.png)

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-10-16 10:19
It is only configured for 1 region, and the price is send to the payment module and processed in it as it should be. After that it is gone for some reason.

![Schermafbeelding 2019-10-16 om 12 16 58](https://user-images.githubusercontent.com/52320806/66910520-ff99f900-f00e-11e9-82fe-2c63f2946078.png)

**Comment by khouloudbelguith** [comment] 2019-10-16 10:47
@nielsverhoeven84,

Could you please provide me the access to your shop.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-16 11:27
@nielsverhoeven84, I tried to make an order with another payment method (COD)
The shipping is OK.
![image](https://user-images.githubusercontent.com/16067358/66915159-a2a34080-f018-11e9-9054-5fb657ab2fb8.png)

But I have an exception on the FO
https://drive.google.com/file/d/1NKbXg020ZND1-6aoLtT7MKCTZN0ZVHFz/view
Thanks to check & feedback.

**Comment by nielsverhoeven84** [comment] 2019-10-16 11:30
Hello 

The problem is happening in cardinalrouge.fr (the second shop in the same prestashop)


Met vriendelijke groeten

 <https://www.robarov.be/?utm_source=Handtekening> <http:> 	 	Niels Verhoeven 
Robarov 
Wampenberg 28/2 
2370 Arendonk 
+32 14 480 780 
www.robarov.be <http://www.robarov.be/> 

 <https://www.facebook.com/robarov/>  <https://www.linkedin.com/company/robarov/>  <https://www.instagram.com/robarov/>

E-mail disclaimer: Alle vermelde prijzen zijn excl. 21% BTW. De inhoud van deze mail is vertrouwelijk en voorbehouden aan de geadresseerde. Wanneer deze mail niet voor u bestemd is, is verspreiding op welke manier dan ook, in strijd met de wet. Gelieve ons te verwittigen indien deze mail niet voor u bestemd is.

**Comment by khouloudbelguith** [comment] 2019-10-16 12:00
@nielsverhoeven84, I just sent you an email.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-30 11:23
Hi @nielsverhoeven84,

As discussed in the email, the issue is solved.
In fact, there are some issues with the carrier & multistore.
When we enable the carrier in all shops => the issue doesn't exist anymore.
In my case, I did not manage to reproduce the issue with PS1.7.6.1.
Since it is fixed, I will close the issue.
Feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-30 11:23 UTC
Labels: Bug fix, Shipping, Invoices, No change required, 1.7.5.2

**Comment by SEFranke** [comment] 2020-10-26 17:20
Just curious... Have was this fixed a year ago?
I have the same issue in a 1.7.6.3 install.

In the carrier preferences, it is all 0, so that should disabele that option.
![afbeelding](https://user-images.githubusercontent.com/46524335/97205640-02016800-17b8-11eb-8bac-0f98d7470fc0.png)


In the carrier ranges, we have only got this: so no free shipping  under € 200,-
![afbeelding](https://user-images.githubusercontent.com/46524335/97205423-c6669e00-17b7-11eb-840d-92271fefd610.png)

The summary when ordering is correct, when the payment is done it is correct, but on the invoice we have free shipping.
