### ISSUE TITLE
Possible to add a product as an accessory to itself

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#12537] opened 2019-02-12 09:23 UTC
**Describe the bug**
It's possible to add a product as an accessory to itself. See attached image.

**To Reproduce**
1. Edit a product
2. Go to "Basic settings tab"
3. Scroll down to "Related products"
4. Search for the same product. If you're editing the product ID1, search, find and select the same product in the list.

**Screenshots**
![attachments_bug](https://user-images.githubusercontent.com/5259451/52624951-37fd9c00-2eb0-11e9-8d15-62bb00273449.jpg)

**Additional information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment] 2019-02-12 09:26
Hi @dennispw,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9617
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-12 09:27
Duplicate of #9617

**Closed as completed by khouloudbelguith** 2019-02-12 09:26 UTC
Labels: Duplicate
