### ISSUE TITLE
Localized extra product attributes can't be accessed in accessories 

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#17158] opened 2020-01-14 09:44 UTC
**Describe the bug**
Localized extra product attributes can't be accessed in accessories 

**To Reproduce**
1. Add a localized extra attribute to Product class : subtitle by example in a hook or an override
`self::$definition['fields']['subtitle'] = array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isString');`
2. The subtitle is not available in Product::getAccessories, see
https://github.com/PrestaShop/PrestaShop/blob/85f982c4feb7d5f88f8f4532ab6f46cdd8255ba1/classes/Product.php#L4024

It should be pl.* instead of fixed list of pl.something attribute.

**Additional information**
PrestaShop version: develop
PHP version: all

**Comment by khouloudbelguith** [comment] 2020-01-15 15:52
Hi @jf-viguier,

Thanks for your report.
Could you please provide the exact override did you use?

Thanks!

**Comment by jf-viguier** [comment] 2020-01-16 11:13
Add subtitle to product_lang table and use this Product.php override :
```
<?php
 
class Product extends ProductCore
{
    public $subtitle;
    public function __construct($id_product = null, $full = false, $id_lang = null, $id_shop = null, Context $context = null)
   {
		self::$definition['fields']['subtitle'] = array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isString', 'size' => 128);
		parent::__construct($id_product, $full, $id_lang, $id_shop, $context);
	}
}
```

**Comment by khouloudbelguith** [comment] 2020-01-16 14:56
@jf-viguier, thanks for your feedback.
>The subtitle is not available in Product::getAccessories, see
https://github.com/PrestaShop/PrestaShop/blob/85f982c4feb7d5f88f8f4532ab6f46cdd8255ba1/classes/Product.php#L4024
It should be pl.* instead of fixed list of pl.something attribute.

Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-16 15:07
@jf-viguier, as discussed with our developer, it is an improvement more than a bug.
So, we thought about an alternative solution that you could offer them.

Thanks!

**Comment by matthieu-rolland** [comment] 2020-01-16 15:12
hi @jf-viguier !

We are not sure object models should be overriden like this. We'll try to suggest a better alternative, I'll get opinions from other core developers 👍

**Comment by jf-viguier** [comment] 2020-01-16 15:36
@matthieu-rolland seriously ? I override objets models since years like that.
It's in the doc https://devdocs.prestashop.com/1.7/modules/concepts/overrides/#overriding-a-class
We can discuss if column should be in a separate mysql table by the issue is the same : we need a way to extends the mysql query, maybe by adding a hook.

**Comment by matthieu-rolland** [comment] 2020-01-16 16:02
@jf-viguier 

We can't use a wildcard in this query, the reason is that wildcards are very costly in sql queries, and if we were to add a wildcard in this sql query, then we would have to do it everywhere, because we can't know in advance what objectModels will be overriden by users.

If you add a field to an ObjectModel then you will have to override every queries that are supposed to return your new field, and be careful existing code responds well to the existence of this new field...

But in the end, overriding an ObjectModel to add a field doesn't seem to be a good practice, depending on your usecase, you should be able to find another way,  if a new kind of data needs to be stored, then it should probably be stored in a new table.

The overriding of an object model is indeed mentioned in the documention, so I'll still wait for some input from other developers:

@PrestaShop/prestashop-core-developers . what do you think ?

**Comment by jf-viguier** [comment] 2020-01-16 16:32
> overriding an ObjectModel to add a field doesn't seem to be a good practice

There is no other way now to have extra fields available in front and in back.
Just try to add a product field in a module and tell me. 
Prestashop has to be as customizable as possible, thanks.

> If you add a field to an ObjectModel then you will have to override every queries that are supposed to return your new field,

Yes, we do it every day ans it works, except here and in some presenters.

**Comment by jf-viguier** [comment] 2020-01-16 16:35
Check this article from @nenes25 https://www.h-hennes.fr/blog/2017/10/19/prestashop-1-7-ajouter-des-champs-produit/

**Comment by matthieu-rolland** [comment] 2020-01-16 17:21
Ok @jf-viguier , I understand your concern, we will come back to you in this issue shortly.

**Comment by nenes25** [comment] 2020-01-16 20:53
@jf-viguier i ve faced the same issue with attribute in cart as you can see here
https://www.h-hennes.fr/blog/2018/04/24/recuperer-des-informations-personnalisees-dans-le-panier/

I ve already think about a generic hook to alter dbQuery objects but it will needs lot of changes.
But in some case it could be usefull

**Comment by matks** [comment] 2021-03-23 21:13
> We are not sure object models should be overriden like this. We'll try to suggest a better alternative, I'll get opinions from other core developers 👍

Hi everybody and sorry for late answer. I fully agree with @matthieu-rolland 

Extending an existing ObjectModel to customize its data structure and the SQL structure is _exactly_ what we _dont recommend_ because we believe it brings huge instability into PrestaShop and created a huge trend of issues with upgrade.

**I think allowing the raw php files to be customized by raw overrides is one of the main reasons why so many upgrades fail** and now there's a cliché "it's so hard to upgrade PrestaShop ! PrestaShop is so bad at upgrades! never click on upgrade button, it will destroy your shop" 😅 

We are now convinced we must _prevent_ people to extend the core data structure and instead store their data _separately_ in other SQL tables (like `mymodule_product_extradata`) as isolating the core data structure is needed to ensure it's integrity. Isolation is key for integrity.

So in the future versions of PrestaShop we will try to avoid people to modify the core objects by introducing an anti corruption layer (but provide alternative solutions). Although since it's php code, well, you can do whatever you want with it. You can read about it here https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/

> The Core sits in the back-end and is at the center of it all. It accounts for all the business needs and use cases that PrestaShop is capable of doing (managing products, shopping carts, orders, etc.). The Core is domain-oriented, meaning that it is built around business use cases, expressed in an ubiquitous language. The Core is also master of its own Domain; in order to let it be the guardian of system-wide coherence, **it has to be isolated from other services and be the only one capable of performing state transitions. Other services can only interact with the Core through well-defined interfaces, that we call the Core API. Incidentally, this also means that Core behavior can be extended, not modified**, by other services–or at least not in a way that it puts system coherence at risk. In addition, the Core is designed to be easily testable and is covered by automated tests.

I understand that https://www.h-hennes.fr/blog/2017/10/19/prestashop-1-7-ajouter-des-champs-produit/ is very efficient and straightforward and allows you to quickly add extra product fields that are very quick available both in Back Office and Front Office. It's because _it was designed to work like this_ 😄 : raw overrides are so powerful and efficient !

Unfortunately years later, we are now being devoured by raw overrides as there are thousand of shops where people customized so much their data structure that now _upgrading these shops is likely to fail and crash_. You can consider overrides of an ObjectModel like a short-term investment: it does what you want today, but it will hit you so much stronger months later when you need to upgrade the shop version and the upgrade process fails.

So we have decided to progressively stop recommending overrides because of this. Raw overrides is a double-edged sword, it's time to put the sword aside and grab a scalpel instead. It's smaller, so if you need to cut a big piece it will be longer, but it's so much more accurate!

You might be interested in this topic https://github.com/PrestaShop/docs/issues/896

I close this issue because, as analyzed by @matthieu-rolland, I dont think a SQL wildcard is a good solution.

If there are hooks we can add, let's add them. If we are missing extension points, let's add them. But I dont think adding SQL wildcards is a robust and long-term solution to a real problem. I think there must be something better, that can suit our needs of today AND our needs of tomorrow (upgrade, stay consistent, shop integrity), and it's not wildcards.

Note: even though I close the issue it does not mean the conversation is over 😉 we can continue talking and reopen if needed.

EDIT:

> Prestashop has to be as customizable as possible, thanks.

See the part "It cannot be everything at once" of https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/ 😄 

Do you prefer a software as customizable as possible but unreliable or a software as reliable as possible but less customizable ? 😉

**Closed as completed by matks** 2021-03-23 21:13 UTC
Labels: Improvement, develop, CO, Attributes, No change required

**Comment by matks** [comment] 2021-03-24 10:32
I just ran into an example that demonstrates exactly the topic https://github.com/PrestaShop/PrestaShop/issues/23750

Error number one
```
/override/classes/Cart.php line 0 - Declaration of Cart::getPackageShippingCost(...) should be compatible with CartCore::getPackageShippingCost(...)
```

Error number 2
```
Compile Error: Declaration of LGTools::getMediaServer($filename, $id_shop = NULL) must be compatible with ToolsCore::getMediaServer(string $filename): string
```

**Overrides are a main instability vector for shop upgrades**

**Comment by jf-viguier** [comment] 2021-03-24 18:55
@matks
- Adding columns in an object model doesn't break Prestashop upgrades
- Adding columns in an object model should be in the design like in Magento, it's a very common task : ok, there is no subtitle in category model : I want a simple way to do this and have this data in front.
- Ok for isolating the core and not allowing behavior changes but after having fixed cart rules and cart calculation nightmares and add hook to add marchant specific rules.

**Comment by Progi1984** [comment] 2021-03-25 08:05
> Adding columns in an object model doesn't break Prestashop upgrades

@jf-viguier I disagree : Imagine, you add a field type in a column with a specific type. Ok that works for your version. But an upgrade add this same column but with a different type : upgrade will be broken ! Isn't it ?

**Comment by matks** [comment] 2021-03-25 09:32
@jf-viguier Adding new columns in an object model means changing the data structure. Let's say I add a new field `wholesale_price_x2`. It's supposed to be the same value as `wholesale_price` but multiplied by 2.

Then in PS 1.7.9 we want to split `wholesale_price` into 2 different fields: `wholesale_price_value` and `wholesale_price_currency` because we want to enable the use of different currencies for `wholesale_price` and `price`.

The `wholesale_price_x2` column is not compatible anymore with the new implementation. Also I think if you override `Category` class and we modify it for 1.7.9 then the new data structure `wholesale_price_value` and `wholesale_price_currency` in 1.7.9 will be ignored while some of the php logic will require it so it will crash.

This is just an example. But you are right on one thing: "Adding columns in an object model" is not the issue, what is the issue is "Using overrides" 😅  which is a more global concern. Overrides introduce instability in a shop system.

> Ok for isolating the core and not allowing behavior changes

We want to isolate the Core but it will still be possible to modify PrestaShop behavior. However
- every change that happens "outside of the Core" at application level will be very easy (like modifying forms, adding new pages, creating payment/shipping/search modules)
- actually it will still be possible to modify the inside behavior of the Core using decoration/overrides of Symfony services but we will not recommend it because, although it will be less intrusive than overrides, it can still decrease the shop consistency
- in the end, it's just PHP files: once the shop is installed you can do whatever you want with it 😅  if you really want to modify a class, even an ObjectModel, you can : it's on your server, you are the only owner

> ok, there is no subtitle in category model : I want a simple way to do this and have this data in front.

This statement looks simple, but actually if you explore it, it's a lot of things
- you want to add a subtitle `field` in Add/Edit a Category Back Office page
- and you want to store it, probably in MySQL
- you want to be able to access this new field on Front Office
- but maybe you also want that this field is accessible and modifiable through the Webservice?
- but maybe you also want that this field is accessible and modifiable through CSV Import?
- but maybe you also want that this field is exported when you use "Export data" button in Back Office page?
- but maybe you also want to add this field inside the Category List in the Back Office, and enable merchant to sort the list alphabetically by subtitle?
- but maybe you also want to add this field inside the Category List in the Back Office, and enable merchant to filter the list using this field ("I want to find all categories which subtitle starts by jf")?

If you override ObjectModel, I think most of the above statements are done out-of-the-box "more or less". Some things will work as you want them, others will be done but maybe not how you wished they were done. You'll have, quickly, a satisfiable result but maybe not 100% what you wished you had.

Once we isolate the Core and you cannot override ObjectModel, you will still be able to implement all of these changes. But maybe it will require more work because you might to implement a hook for each of these usecases. So more work? Yes! But also more control! Because you will be able to select and define _exactly_ how it works for CSV, and how it works for webservice, and how it's being used in Back Office listing page, and how it's being used in Back Office add/edit page, and...

So overrides of an ObjectModel are a quick way to achieve something very fast and globally, but in a raw and broad way. We are leaving this behind to allow more advanced model where you need to define, for each statement, what you want, but also you control better each of them. More work, more control, and more advanced capabilities.

We are putting down the double-edged sword and grabbing a scalpel 😄  .

**Comment by jf-viguier** [comment] 2021-03-25 16:17
Thanks @matks for the answer. We'll have to charge more the merchants.

**Comment by matks** [comment] 2021-03-25 16:24
> Thanks @matks for the answer. We'll have to charge more the merchants.

I'm not sure.

If you charge the merchant only the features, yes. Because the same feature, to be implemented might be more expensive to develop without overrides.

But once again you have to look at the full period. If you can setup a 1.7.7 shop for 30.000€ but then when the time to upgrade to PS 1.7.9 you have to charge again 20.000€ because the upgrade process fails and there is a lot of bugfix to do to perform this version increase, the merchant spent 50.000€.

If you can setup a 1.7.7 shop for 40.000€ without overrides (so "no override" costs you 10K) but then when the time to upgrade to PS 1.7.9 you have to charge only 5.000€ because the upgrade process works very well, the merchant spends 45.000€

Also we think that isolating the Core and going for the scalpel will reduce instability, bugs and issues with the software. How much do you charge the merchant for fixing bugs?

So back to my usecase:

**With overrides**

Initial 1.7.7 shop production: 30.000€
Upgrade to 1.7.9 1 year later: 20.000€
Fix of many bugs in the software: 20.000€

**Without overrides**

Initial 1.7.7 shop production: 40.000€
Upgrade to 1.7.9 1 year later: 5.000€
Fix of fewer bugs in the software: 10.000€

Well, the numbers look better now 😊 ?

**Comment by matks** [comment] 2021-03-25 16:53
Also @jf-viguier, again I insist on one thing:

> in the end, it's just PHP files: once the shop is installed you can do whatever you want with it 😅 if you really want to modify a class, even an ObjectModel, you can : it's on your server, you are the only owner

**If you really want to modify a ObjectModel, you can simply modify the Core file**. I cannot prevent you from doing it 😄  the code is on your server. You are the only captain aboard. ⛵ 

One day we aim to replace ObjectModel by [Doctrine](https://www.doctrine-project.org/). The principle behind is similar. If you want to extend a data structure controlled by a Doctrine entity, you modify the file and hop! you are done. One modified file, and the data structure is extended.

<hr>

**In this github issue** we are discussing about "what the Core will aim for? what the documentation of PrestaShop will recommend?"

But when you download PrestaShop, it's a ZIP 📦  with PHP, JS, CSS and HTML files in it. **You do whatever you want with it in the end** 😉  .

Let's say we remove override system for PrestaShop 8.0.0 (unlikely to happen, the Core isolation project is going to take years). Nothing can prevent you to download PS 8.0.0 ZIP, **inject the override system** you have extracted from PS 1.7 and continue to use it. _You can run a modified version of the software if you want to_. I cannot forbid it. The only thing maintainers can do is choose a direction for the Core and aim for it.

We have chosen a [direction for the Core project](https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/#our-proposal-for-a-future-architecture): integrity, stability, consistency. We chose this direction because for years we have heard "bouuuuh PrestaShop has so many bugs hahaha it's so broken" feedback 😅  . We did not choose this direction randomly, it's the solution we have chosen to fix the software following years of negative feedbacks. We have listened to the community complaining about PrestaShop instability, so we have decided to act.

<hr>

You can already see the first consequences of this choice for integrity, stability, consistency: the [Bug bounty](https://build.prestashop.com/news/bug-bounty-program/) which aims to keep the software secure, the focus on [architectural issues](https://github.com/PrestaShop/PrestaShop/issues/14994), the focus on [keeping up-to-date](https://github.com/PrestaShop/PrestaShop/issues/16477) with latest technologies, the huge increase in quality thanks to the [QA team](https://build.prestashop.com/news/pr-testing-on-prestashop/) who went from 2 people to 10 😄  in 3 years. You can see the PrestaShop investments are focusing on dealing with deep pains and increasing quality and stability.

This will impact what work we do in the Core. But what you put in production is only up to you. If you really like the override system, you could create a module (call it the JFViguierOverrideSystemModule) that you plug on PrestaShop Core and it enables people to continue using overrides. _You can choose to consider the Core as a development platform on top of which you build your own flavor of PrestaShop_ (and sell it?). Don't think about PrestaShop decisions like "definitive". We are the foundations of a shop, you, and only you, choose what is deployed in production.

Finally, _we are not sitting in an ivory tower_. We are listening. We are discussing almost everyday with PrestaShop users. It will take time to see the advantages of the decision we have chosen, but if it was proved it was a complete mistake, I'm confident we would rollback on it. Nobody can predict the future 😊  so if we find out that this decision is bringing PrestaShop into a wall we'll change the direction. We are not going to say "no, we follow the direction, I wont listen, I dont care" 😄

**Comment by kpodemski** [comment] 2021-03-25 17:06
Hey @jf-viguier 

You don't need to modify SQL queries, every place where you get products in PrestaShop is using `getProductProperties` where proper hooks are available, of course this would create n+1 issue but it's something to discuss in the future, `pl.*` is not an answer here.

> Adding columns in an object model should be in the design like in Magento, it's a very common task : ok, there is no subtitle in category model : I want a simple way to do this and have this data in front.

IMO it's better for you to create a relation between two tables than keep extending core ones, of course - as everything - it depends, but most of the time it's much safer to do, especially if you plan to support your customer for a longer period of time.

**Comment by jf-viguier** [comment] 2021-03-26 15:55
> in the end, it's just PHP files: once the shop is installed you can do whatever you want with it 😅 if you really want to modify a class, even an ObjectModel, you can : it's on your server, you are the only owner

I never do that, it's a bad practice that block upgrade process far more that overrides.

thanks for your answers.
