### ISSUE TITLE
Fonts are not loaded when not connected to internet

### ISSUE THREAD

**Issue by alireza2005** [PrestaShop/PrestaShop#12772] opened 2019-03-02 07:45 UTC
hello.

I install prestashop 1.7.5.1 (the final version) in local server (in wamp server - Apache 2.4.37 - PHP 7.2.14 - MySQL 5.7.24). My front office is ok, but most pages in my back office have problem ( for example  picture below )(in this case My computer is not connected to the Internet).
![product problems](https://user-images.githubusercontent.com/48148331/53679000-f7898500-3cdb-11e9-9443-d490b7aba70a.PNG)

but when i connect my computer to the internet my back office all is ok (for example picture below).
![produck okey](https://user-images.githubusercontent.com/48148331/53679015-16881700-3cdc-11e9-8d41-e29e55527d73.PNG)

as if jquery  or css not load Properly in my back office (when My computer is not connected to the Internet).

please help me,very thanks.

PrestaShop version: 1.7.5.1
wamp server version: 3.1.7 64bit
PHP version: 7.2.14
MySQL version: 5.7.24

**Comment by rblaurin** [comment] 2019-03-02 11:20
Hi
It seems your browser is not able to access the material icons. Is there something in javascript console log?

**Comment by alireza2005** [comment] 2019-03-02 12:18
Hi
where is  javascript console log

**Comment by rblaurin** [comment] 2019-03-02 12:38
If you are using Google Chrome, just press F12 and click the Console tab

**Comment by alireza2005** [comment] 2019-03-02 12:57
![errors](https://user-images.githubusercontent.com/48148331/53682145-0d14a400-3d08-11e9-89ba-cc3de57cd7ed.PNG)

**Comment by rblaurin** [comment] 2019-03-02 13:19
Can you send also a full print of the network tab?

**Comment by alireza2005** [comment] 2019-03-02 13:32
![errors-network](https://user-images.githubusercontent.com/48148331/53682641-0177ac00-3d0d-11e9-983b-8faed61b329a.PNG)

**Comment by rblaurin** [comment] 2019-03-02 13:38
Try to clear cache and cookies, go to command prompt and enter the commands listed below, one by one:
ipconfig /flushdns
ipconfig /renew

**Comment by alireza2005** [comment] 2019-03-02 14:02
Hi
ipconfig donot solve my problem
when my computer is connected to internet there is no problem
in offline mode as if google font and btn (botton) classes have loading problem

**Comment by rblaurin** [comment] 2019-03-02 16:23
Ok, sorry, I misunderstood your problem. You are not connected.
I am afraid this is the default behavior of Prestashop, you must be connected because it uses Google Fonts. I think these fonts could be stored locally to avoid this behavior. Maybe you could download them and modify the paths in admin/themes/new-theme/public/theme.css file.

**Comment by alireza2005** [comment] 2019-03-02 18:02
Hi 
Thank you very much for your help
good bye

**Comment by khouloudbelguith** [comment] 2019-03-04 11:29
Hi @alireza2005,

I did not manage to reproduce the issue with PrestaShop 1.7.5.1, I tried with private navigation & no connection.
I attached a video record.
https://drive.google.com/file/d/1IUKMW9_P8WKyxK5fkXwVwwBLgSdUe1z3/view
I think you have a conflis in your address ip.
Thanks to check the issue with your host & feedback.
Thanks!

**Comment by rblaurin** [comment] 2019-03-04 12:08
@khouloudbelguith, I think you have to try to navigate between BO pages. I managed to reproduce It this way.

**Comment by khouloudbelguith** [comment] 2019-03-04 15:06
Hi @rblaurin,

This issue occurs only when I'm offline & in the Symfony migrated page.
![image](https://user-images.githubusercontent.com/16067358/53741489-cf925100-3e96-11e9-9268-2ae722fd5deb.png)
Because those links are not loaded
https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700&subset=latin-ext
https://fonts.googleapis.com/icon?family=Material+Icons

This issue occurs with PrestaShop 1.7.5.1 & PS1.7.4.4.
@marionf, what do you think?
Is it a bug or normal behavior?
Thanks!

**Comment by alireza2005** [comment] 2019-03-04 15:57
Hi
Could not have these files inside PrestaShop to be used in offline mode in local server?

**Comment by marionf** [comment] 2019-03-05 11:39
No idea, let's ask to @PrestaShop/prestashop-core-developers if we can do something to avoid this probem

**Comment by Amulliez** [comment] 2019-03-18 12:40
Hi @khouloudbelguith

I have the same problem since 2 days in front office and back office on Prestashop 1.7.5.0.
How can I fix this problem ?

Thanks you !

**Comment by khouloudbelguith** [comment] 2019-03-18 12:48
Hi @Amulliez, this issue occurs only when there is no connection.
If your connection is ok, so, you have a different issue, it could be in your address ip.
You need to check the issue with your host the issue.

**Comment by Amulliez** [comment] 2019-03-18 13:53
Hi @khouloudbelguith

This issue is solved, a connection issue was. present

Thanks you !.

**Comment by khouloudbelguith** [comment] 2019-03-18 13:58
@Amulliez, thanks!

**Comment by ttoine** [comment] 2020-01-21 14:34
relative to #10456

**Comment by PierreRambaud** [comment] 2020-11-18 15:59
Should be fixed. PIng @NeOMakinG

**Comment by NeOMakinG** [comment] 2020-11-18 16:42
Not yet because scss var `$local-font: true;` is missing inside the core (will be fixed when https://github.com/PrestaShop/PrestaShop/pull/18396 will be finished)

**Comment by hibatallahAouadni** [comment] 2021-03-06 02:01
Ping @PrestaShop/prestashop-core-developers could you pelase specify the status of this issue :pray:
Thanks in advance.

**Comment by NeOMakinG** [comment] 2021-03-08 07:59
#18396 is not merged yet, so it's in progress!

**Comment by PierreRambaud** [comment] 2021-03-08 08:50
It has been merged now :)

**Comment by NeOMakinG** [comment] 2021-03-08 08:58
It should be fixed then, when rebuilding assets

**Comment by hibatallahAouadni** [comment] 2021-03-08 13:37
Fixed by #18396

**Closed as completed by hibatallahAouadni** 2021-03-08 13:37 UTC
Labels: Bug, Minor, BO, Fixed, Front-end, 1.7.5.1, 1.7.6.0, PR available
