### ISSUE TITLE
Problem on install modules and visiting advanced sections pages

### ISSUE THREAD

**Issue by MattiaMarchiorato** [PrestaShop/PrestaShop#13721] opened 2019-05-09 07:16 UTC
**Describe the bug**
1)Can't install module, when click on install the module loading still spinning and we receive this js error
module_card.js:231 Uncaught TypeError: Cannot convert undefined or null to object
2)Can't visit advanced setting page, when click we see this page with a redirect [Debug] This page has moved
Please use the following URL http://prestashop.test/index.php?_token=fwhz9ZtImtidgTFAQhoWyQ8lbyrflR-AqkAo44P6l98

**To Reproduce**
1) Install a moduel
2) Go do performance section under advanced

**Screenshots**
![Schermata 2019-05-09 alle 09 01 10](https://user-images.githubusercontent.com/3527474/57433535-05f2a080-7239-11e9-8788-8c3799b92237.png)

**Additionnal information**
On Homestead Vagrant
PrestaShop version: 1.7.5.2
PHP version: PHP 7.3

**Comment by khouloudbelguith** [comment] 2019-05-09 07:28
Hi @insology,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/1Jr2nZPAIuVVzIctreAUS02DtDvpeyHGx/view
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP, check & feedback.

**Comment by MattiaMarchiorato** [comment] 2019-05-09 07:40
Hello @khouloudbelguith 

Same problem for php 7.2
![Schermata 2019-05-09 alle 09 40 09](https://user-images.githubusercontent.com/3527474/57435763-8071ef00-723e-11e9-961e-d0d19345854e.png)

**Comment by khouloudbelguith** [comment] 2019-05-09 08:02
@insology, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by MattiaMarchiorato** [comment] 2019-05-09 08:17
Solved the issue by adding
`location ~ /(sell|improve|configure|international|_profiler|product|feature|attribute|supplier|combination|specific-price)/(.*)$ {
      try_files $uri $uri/ /index.php?q=$uri&$args $admin_dir/index.php$is_args$args;
    }`

in nginx config file.
Is there any official configuration for ngnix/apache server?

**Comment by khouloudbelguith** [comment] 2019-05-09 08:31
@insology, yes!
You can follow this link
https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-09 08:31 UTC
Labels: Bug, BO, Modules catalog, No change required, 1.7.5.2

**Comment by MattiaMarchiorato** [comment] 2019-05-09 08:44
> @insology, yes!
> You can follow this link
> https://github.com/PrestaShop/PrestaShop/blob/develop/docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
> Since it is fixed, I close the issue, feel free to open a new one when needed.
> Thanks!

Need some fix but ok, thanks

**Comment by roncarino** [comment] 2020-08-26 09:02
Hi @insology, I saw you made some configuration in your nginx inside vagrant homestead. Can you let me know where this config file is? I have kinda the same problem and I wanted to try your solution but I am having hard time finding where that config file is.... thanks!
