### ISSUE TITLE
When ps_crosselling module is installed too, display its informations into modal

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16969] opened 2019-10-11 14:47 UTC
Spec:

If https://github.com/PrestaShop/ps_crossselling is installed too, then we can display the "Customers who bought this product also bought..." block into the shopping cart modal into https://github.com/PrestaShop/ps_shoppingcart/blob/master/modal.tpl#L4

**Comment by khouloudbelguith** [comment] 2019-12-31 15:46
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by colinegin** [comment] 2020-06-17 14:41
This issue is a duplicate of #17709. I close this one in favor of the other one ;)
Thanks !

**Closed as completed by colinegin** 2020-06-17 14:41 UTC
Labels: Improvement, FO, Duplicate, ps_shoppingcart
