### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#26957] opened 2021-12-12 23:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

memcache is old and redis is faster

### Describe the solution you'd like

make support for Redis cache

**Comment by florine2623** [comment] 2021-12-13 08:27
Hello @thbl ,

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/26129.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by florine2623** [comment] 2021-12-13 08:27
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/26129

**Closed as completed by florine2623** 2021-12-13 08:27 UTC
Labels: Feature, Duplicate, Invalid
