### ISSUE TITLE
bugs on ps_emailalerts module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#20216] opened 2020-07-17 15:13 UTC
Hi
on a new small site the module ps_emailalerts doesn't send email like for new orders
I've upgraded to 1.7.6.7 but with the same error
I've done many tests, many installations but each time at the start all settings are without data, look at the image
I can save all settings and emails, but each contact form on prestashop work well, instead from this module I cannot get emails

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/87801618-4774d780-c850-11ea-9120-7ad8972c87ad.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2
* Module version: 2.2.0

**Comment by florine2623** [comment] 2020-07-17 15:21
Hi @maofree ,
Thanks for the report.
Your issue seems to be a duplicate of this one : https://github.com/PrestaShop/PrestaShop/issues/19842
Could you check ?

**Comment by Maofree** [comment] 2020-07-17 15:32
hi
yes the problem is the same
but I cannot see the fix
in other sites works well, but it happens also in another one site some weeks ago

**Comment by Maofree** [comment] 2020-07-17 15:44
hi
the problem is due from this condizion

if ($delete_params && $this->uninstallPrestaShop16Module()) {

replacing it to

if ($delete_params) {

all data is created in the db and all works well

**Comment by SimonGrn** [comment] 2020-07-17 16:19
Hello @maofree,

the fix you're looking for is here : https://github.com/PrestaShop/ps_emailalerts/pull/58
It is still waiting for a QA check. Once verified, a new version of the module will be released.

Since it's a duplicate of #19842 I close this issue.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you.

**Comment by SimonGrn** [comment] 2020-07-17 16:20
Duplicate of #19842

**Closed as completed by SimonGrn** 2020-07-17 16:19 UTC
Labels: Bug, Duplicate, 1.7.6.7, ps_emailalerts

**Comment by Maofree** [comment] 2020-07-17 16:23
I found this bug on 5 sites
so it is necessary to fix it quickly
bye
