### ISSUE TITLE
No-unique ID 

### ISSUE THREAD

**Issue by peladillas** [PrestaShop/PrestaShop#9760] opened 2018-08-22 17:19 UTC
After clean installation, get this javascript Errors

**To Reproduce**

1) Install
2) Open Backend
3) Show console Javascript in any navigator

**Screenshots**

https://snag.gy/6rzPuI.jpg

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: 5.6

> Console log:

19:01:40.779 index.php?controller=AdminModules&token=70263331933fec7dcdd5e6b74ef8483a&configure=simpleimportproduct&module_tab=step_2&save=6:1 [DOM] Found 2 elements with non-unique id #supplier: (More info: https://goo.gl/9p2vKq) <select name=​"supplier" class=​"chosen fixed-width-xl" id=​"supplier" style=​"display:​ none;​ width:​350px;​">​…​</select>​ <select name=​"supplier" class=​"chosen fixed-width-xl" id=​"supplier" style=​"display:​ none;​">​…​</select>​
19:01:40.782 index.php?controller=AdminModules&token=70263331933fec7dcdd5e6b74ef8483a&configure=simpleimportproduct&module_tab=step_2&save=6:1 [DOM] Found 2 elements with non-unique id #supplier_currency: (More info: https://goo.gl/9p2vKq) <select name=​"supplier_currency" class=​"chosen fixed-width-xl" id=​"supplier_currency" style=​"display:​ none;​ width:​350px;​">​…​</select>​ <select name=​"supplier_currency" class=​"chosen fixed-width-xl" id=​"supplier_currency" style=​"display:​ none;​">​…​</select>​
19:01:40.782 index.php?controller=AdminModules&token=70263331933fec7dcdd5e6b74ef8483a&configure=simpleimportproduct&module_tab=step_2&save=6:1 [DOM] Found 2 elements with non-unique id #supplier_ids: (More info: https://goo.gl/9p2vKq) <select name=​"supplier_ids" class=​"chosen fixed-width-xl" id=​"supplier_ids" style=​"display:​ none;​ width:​350px;​">​…​</select>​ <select name=​"supplier_ids" class=​"chosen fixed-width-xl" id=​"supplier_ids" style=​"display:​ none;​">​…​</select>​
19:01:40.783 index.php?controller=AdminModules&token=70263331933fec7dcdd5e6b74ef8483a&configure=simpleimportproduct&module_tab=step_2&save=6:1 [DOM] Found 2 elements with non-unique id #supplier_price: (More info: https://goo.gl/9p2vKq) <select name=​"supplier_price" class=​"chosen fixed-width-xl" id=​"supplier_price" style=​"display:​ none;​ width:​350px;​">​…​</select>​ <select name=​"supplier_price" class=​"chosen fixed-width-xl" id=​"supplier_price" style=​"display:​ none;​">​…​</select>​
19:01:40.783 index.php?controller=AdminModules&token=70263331933fec7dcdd5e6b74ef8483a&configure=simpleimportproduct&module_tab=step_2&save=6:1 [DOM] Found 2 elements with non-unique id #supplier_reference: (More info: https://goo.gl/9p2vKq) <select name=​"supplier_reference" class=​"chosen fixed-width-xl" id=​"supplier_reference" style=​"display:​ none;​ width:​350px;​">​…​</select>​ <select name=​"supplier_reference" class=​"chosen fixed-width-xl" id=​"supplier_reference" style=​"display:​ none;​">​…​</select>​

**Comment by khouloudbelguith** [comment] 2018-08-23 13:15
Hi @peladillas,

Thanks for your feedback.
I manage to reproduce the issue with PS 1.7.4.2.
![image](https://user-images.githubusercontent.com/16067358/44527460-28627f00-a6e7-11e8-8a3f-2d5ddba01a5b.png)
We will see how to fix it.

Best regards, Khouloud

**Comment by marionf** [comment] 2018-12-07 16:15
@khouloudbelguith I can't reproduce the issue with 1.7.5.0, can you try ?

**Comment by khouloudbelguith** [comment] 2018-12-07 16:24
Hi @marionf,

I did not manage to reproduce the issue with PS1.7.5.0rc1.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10684 to solve the issue.
Duplicate of #10469

**Closed as completed by khouloudbelguith** 2018-12-07 16:24 UTC
Labels: Bug, Minor, Duplicate, Dashboard, 1.7.4.2
