### ISSUE TITLE
Can't Save any preferences

### ISSUE THREAD

**Issue by Guttio1** [PrestaShop/PrestaShop#17505] opened 2020-02-05 09:23 UTC
I need to enable the "Allow iframe on HTML fields"  i turn on and save and 
apparently it was save, but no. There's no error showed
https://i.imgur.com/2dnQtUF.png

**Comment by khouloudbelguith** [comment] 2020-02-05 09:34
Hi @Guttio1,

I did not manage to reproduce the issue with PS1.7.6.3
I attached a screen record
https://drive.google.com/file/d/1eSZGMRZ3l7lPIQjiffttWCHzpw_690tn/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-06 08:05
Hi @Guttio1,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-06 08:05 UTC
Labels: Bug, BO, General, No change required
