### ISSUE TITLE
Order split with wrong shipping cost calculations

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#15918] opened 2019-10-11 13:47 UTC
Scenario:
1. Create two carriers, first one A for weight < 10kg and cost of 10€ , second one B with weight > 10kg and cost of 25€
2. Edit Article X weight is 1kg and only carrier A assigned. Edit article Y weight 11kg and only carrier B assigned.
3. Create a order, 1pc of article X and 1pc of article Y.
4. Cart/checkout shows both articles with shipping cost of 25€
--> expectation would be 10€+25€ as both carriers have to be paid.
5. After checkout the order is split into two:
  a. Order A with 25€ shipping cost and heavy weight carrier--> correct
  b. Order B 
       - without any carrier assingment --> wrong
       - without 0,00€ shipping cost visible --> wrong
       - with another 25€ added to the total value --> totally wrong
       --> expected is to either have carrier A assigned and shipping cost of 10€

![grafik](https://user-images.githubusercontent.com/47666330/66656191-cbed5680-ec3d-11e9-8e71-f3a3a5eebaed.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-11 13:53
Hi @JBWModules,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15304#issuecomment-526137500
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-11 13:53
Duplicate of #15304

**Closed as completed by khouloudbelguith** 2019-10-11 13:53 UTC
Labels: Duplicate

**Comment by JBWModules** [comment] 2019-10-11 13:57
@khouloudbelguith I think the issue #15304 is different. In my scenario both order can and should be shipped but the shipping cost are calculated incorrectly

**Comment by khouloudbelguith** [comment] 2019-10-11 14:01
@JBWModules, no it is the same issue, order are splited in two orders because you have different carriers.
The shipping is wrong calculated.

Thanks!

**Comment by JBWModules** [comment] 2019-10-11 14:06
Hmm ok, the expected results are compeltely different but maybe same technical reason. Ok, waiting for the fix. It would be nice if we could control the shiping cost calculation even further: In my case we could either charge the customer for the order split (e.g. due to different weights) - or we give the cheaper shippment for free (e.g. two carriers due to different storages the customer can influence)
