### ISSUE TITLE
ps_facetedsearch product order using "position" value is inconsistent

### ISSUE THREAD

**Issue by NickolayGett** [PrestaShop/PrestaShop#20298] opened 2020-07-23 12:36 UTC
#### Describe the bug

ps_facetedsearch adds a leftJoin to the MySQL query to handle product ordering.
For the "position" value it joins "category_product" with a condition "p.id_product = cp.id_product". The issue is that "category_product" table's primary unique index consists of two columns: id_product and id_category.
This means that ps_facetedsearch condition "p.id_product = cp.id_product" will take the row of a certain product and any category, and any category's position as a result.
#### Expected behavior

ps_facetedsearch should have an additional condition "cp.id_category = {category}", where {category} is the ID of the category that is being viewed.

#### Steps to Reproduce

1. Go to the ps_facetedsearch\src\Adapter\MySQL.php, line 208. Notice the condition is "p.id_product = cp.id_product";
2. Go to the "category_product" table primary index. Notice the unique primary index has two columns: id_product and id_category.
This should be enough for a developer to understand the issue.

The issue on category pages is inconsistent, since the database can return both correct and incorrect data. The way to recreate the issue on category pages:
1. Create a large amount of categories;
2. Set completely different positions of each product in each category;
3. Go to every category page and compare the position value with the actual product position on the page. 

#### Additional information

* ps_facetedsearch version: 3.5.0

**Comment by florine2623** [comment] 2020-07-23 16:01
Hi @NickolayGett ,
In my test shop PS 1.7.6.7, I can't reproduce the issue.
Having different position in each category shows up well in the front shop.

You can check this option in BO > Shop Parameters > Products :
![Capture d’écran 2020-07-23 à 18 00 15](https://user-images.githubusercontent.com/16019289/88309297-666ee000-cd0e-11ea-99c0-f22af8f82c2a.png)
Thanks!

**Comment by NickolayGett** [comment] 2020-07-24 06:47
> Hi @NickolayGett ,
> In my test shop PS 1.7.6.7, I can't reproduce the issue.
> Having different position in each category shows up well in the front shop.
> 
> You can check this option in BO > Shop Parameters > Products :
> ![Capture d’écran 2020-07-23 à 18 00 15](https://user-images.githubusercontent.com/16019289/88309297-666ee000-cd0e-11ea-99c0-f22af8f82c2a.png)
> Thanks!

As I said, the issue is inconsistent. It appears rarely, but it does appear.
Instead of trying to reproduce the issue in the fornt-end, I would suggest that someone with knowledge in MySQL queries to check if the condition "p.id_product = cp.id_product" is enough to pick unique values from the "category_product" table. Keep in mind that the values should be picked for a specific category.

**Comment by florine2623** [comment] 2020-07-24 14:31
Hi @PrestaShop/prestashop-core-developers ,

@NickolayGett is having an inconsistent bug that I cannot reproduce in FO.
There's this following condition that is "p.id_product = cp.id_product" in the product position query.
It is well explained by user : 
For the "position" value it joins "category_product" with a condition "p.id_product = cp.id_product". The issue is that "category_product" table's primary unique index consists of two columns: id_product and id_category.
This means that ps_facetedsearch condition "p.id_product = cp.id_product" will take the row of a certain product and any category, and any category's position as a result.

Should something be done about this ?
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-15 10:47
Hi @NickolayGett,

I did not manage to reproduce the issue with PS1770beta2 as commented [here](https://github.com/PrestaShop/PrestaShop/issues/20972#issuecomment-691968705).

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-10-05 09:41
Hi @NickolayGett,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-05 09:41 UTC
Labels: Faceted search, No change required, Back-end, 1.7.6.7
