### ISSUE TITLE
Module Customer follow-up (ps_reminder)

### ISSUE THREAD

**Issue by LaureMatou** [PrestaShop/PrestaShop#15602] opened 2019-09-18 14:12 UTC
Module ps_reminder does not work
Module provides with a URL to call manually or to add to a crontab, but the URL does not seem to work: it returns a 404 error

**To Reproduce**
1. Install ps_reminder
2. Try to configure it (we tested with easycron for instance)
3. Error 404

**Additional information**
PrestaShop version: 1.7.5.2 (Ready)
Module version: 2.0.0

**Comment by khouloudbelguith** [comment] 2019-09-18 14:17
Hi @LaureMatou,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9799
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-18 14:18
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9799

**Closed as completed by khouloudbelguith** 2019-09-18 14:17 UTC
Labels: Duplicate, Follow up
