### ISSUE TITLE
Cash on delivery (COD) module's translations are not working in confirmation letter

### ISSUE THREAD

**Issue by Arminas-adisoft** [PrestaShop/PrestaShop#31501] opened 2023-02-23 06:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Cash On Delivery (COD) module (v2.0.1) was installed on Prestashop 1.7.8.7 and has been configured by changing the language in the front end. The website (gudruciovaistine.lt) has a Multishop, so when the clients choose the DPD Payment On Delivery, it shows in the Payment list Cash On Delivery. For example, if the client uses EN language on the website, he sees this view - https://d.pr/i/dquzOy, https://d.pr/i/iaW1sN. After that, when the products have been bought, the Confirmation letter shows in a different language the payment method - https://d.pr/i/1LUNbL.

### Expected behavior

The payment method (COD) in the Confirmation letter should be visible in that language, which was selected in the front end. 

### Steps to reproduce

1. Go to the gudruciovaistine.lt
2. Choose EN language
3. Select any product and go to the cart
4. Fill up the fields that was asked in the cart
5. Select DPD Payment On Delivery (Delivery method) and after that Cash On Delivery (Payment method)
6. Confirm the cart
7. Check the Confirmation letter's payment method.

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by HanaRebaiQA** [comment] 2023-02-23 10:00
Hello @Arminas-adisoft 

Thanks for your report.
I was unable to reproduce your issue using the steps t reproduce on PS1788, PS8.1.0_beta, and using your website [gudruciovaistine.lt](gudruciovaistine.lt) with the `ps_cashondelivery v2.0.1 ` module.

**On your Website gudruciovaistine.lt** : OK :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/220874277-0a2b0a80-510c-44bb-b9f1-7477ee5fe3bb.png)

**On PS1788 : OK** :heavy_check_mark: 

In order confirmation : 

![image](https://user-images.githubusercontent.com/92912932/220874488-fdc9528d-149b-45c5-b1b1-8478428a8fcb.png)

Order history details :

![image](https://user-images.githubusercontent.com/92912932/220874415-c37f0c9f-1af4-4781-b551-9c3a8b11f2e1.png)

**On PS8.1.0_beta : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/220874597-fe16955d-9c91-40a1-b1bd-09d2e5dabc72.png)

https://user-images.githubusercontent.com/92912932/220875221-a0393ddb-f18b-41ce-8909-bcb35f40340f.mp4


So, maybe the problem is related to any configuration on your website.
I'll close this issue. Feel free to open new tickets when needed.

Thank You!

**Closed as completed by HanaRebaiQA** 2023-02-23 10:00 UTC
Labels: Bug, FO, Order, ps_cashondelivery, Invalid, 1.7.8.8
