### ISSUE TITLE
Occasional: Payments options not displayed, without any alert message

### ISSUE THREAD

**Issue by mmystery** [PrestaShop/PrestaShop#23355] opened 2021-02-22 19:18 UTC
#### Describe the bug

Some clients are trying to checkout, the issue occours on the last step where they should select the payment option of their preference. Instead, it doesn't show the payment options as you can see in the screenshots. Furthermore, no errors are recorded in the logs.

I'm worried that other clients are having the same issue, but I'm unable to reproduce it. Furthermore the bug is casual, as other clients are able to order. 

I've had in the recent past a relevant issue, where unexpectedly some entries were missing on the module_carrier table and a manual fix was implemented according to #14554 . As of today I don't know how or why these entries were deleted, for sure it wasn't by the administrator. It was the first thing to check, but seems that the entries are there (and are working most of the times, as I'm still receiving some orders).

I've also read another similar issue #17681 or maybe #11379 but no results.

#### Expected behavior

Always show payment options, or if there's a problem, it should show the alert message that unfortunately no payment methods are available.

#### Steps to Reproduce

Carriers: 1 selection available: Core functionality carrier, free
Payments: 4 selections available, Core COD, Core Bank Wire, Paypal official, third party bank credit card redirection module.

Unable to reproduce it on my tests, as the payment options are being shown. I attach a screenshot from an actual client.

<img width="387" alt="Screenshot 2021-02-22 at 8 49 27 PM" src="https://user-images.githubusercontent.com/22262950/108755244-ad94ac00-754f-11eb-807d-b63d3ab77c9b.png">

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-02-23 10:03
Hello @mmystery 

I didn't manage to reproduce the issue following the steps in this issue #14554, see the attached screen record below:

https://drive.google.com/file/d/1EGVz8XLBMlvjVrU_oXKGlVRW_HDRNDBp/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-14 21:55
Hello @mmystery ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-14 21:55 UTC
Labels: Bug, FO, Payment methods, No change required, Checkout, 1.7.6.8
