### ISSUE TITLE
Webservice: Category: Invalid XML response

### ISSUE THREAD

**Issue by HassanKapadia** [PrestaShop/PrestaShop#31698] opened 2023-03-09 13:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Request made by URL: api/categories?schema=blank returns invalid XML format.

Example:
![image](https://user-images.githubusercontent.com/74450062/224048523-870cac81-e2fc-4896-b0c2-5356a533bd03.png)

### Steps to reproduce

1. Setup PrestaShop's v8.1.0-beta.1 with PHP v8.1.6
2. Create a Webservice
3. Use Webservice like [your_shop_url]/api/categories?schema=blank
4. Error: XML Parsing Error: not well-formed

### PrestaShop version(s) where the bug happened

8.1.0-beta.1

### PHP version(s) where the bug happened

8.1.6

**Comment by hibatallahAouadni** [comment] 2023-03-11 12:57
Hello @HassanKapadia 

As you mentioned in the other issue, your issue is duplicate of it.
As the original issue has been fixed on 8.0.x branch and this merge PR https://github.com/PrestaShop/PrestaShop/pull/31680 will add the fix to the branch 8.1.x.
You can check it if you want 😉 

Closing the issue.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-03-11 12:58
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/30987

**Closed as completed** 2023-03-11 12:58 UTC
Labels: Bug, Duplicate, Invalid
