### ISSUE TITLE
Sorting products not working after duplicating product and changing pages

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14175] opened 2019-06-12 15:39 UTC
**Describe the bug**
Sorting by price tax excl not working after changing pages

**To Reproduce**
1. Go to Catalog > Products
2. Select all product and click on bulk actions > duplicate
3. Click on an arrow to filter data ASC (no matter which one)
4. Go to page 2
5. Products are not sorted anymore by price tax excl ASC and you see again products that was on page 1

**Screenshots**
https://drive.google.com/file/d/1q2BipKus_ARANjNbdH5jsaJhYW4l6-1L/view?usp=sharing

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by arouiadib** [comment] 2020-03-05 19:06
Thank you @marionf for this constructive issue (at least for me who is blocked trying to understand what is happening under the hood).

<del>The problem is that I am blocked for a weird reason. In 1.7.7.0, I can reproduce the behaviour in  ONLY one time, just after duplicating the products :confused:. Afterwards, pagination seems to work correctly depending on the filter applied, even after deleting the duplicated products and duplicating them again.</del>
<del>
At a certain time again, I manage to reproduce the issue, but I can't find what is the exact situation to reproduce it again and work on it. Bizarre :)
</del>
<del>
Could you please, when you have time, help me. I think we should find a better way to reproduce this issue.</del>

I finally managed to reproduce this issue :D. The problem comes from pagination. Tricky to fix for the moment but I will give a try later. 

Thank you very much

**Comment by marionf** [comment] 2020-03-06 09:54
Hello @arouiadib 

We plan to re-migrate the product listing in symfony for the 1.7.8 version, we will fix this bug by the way

**Comment by arouiadib** [comment] 2020-03-06 14:38
@marionf , Good news thank you

**Comment by arouiadib** [comment] 2020-03-06 16:06
Hello @marionf ,
Let me please add another question for a better understanding. By re-migration, you mean from Symfony+Twig to Symfony+VueJs. Right? Or we will be using same technology but with different architecture? 
Thank you very much

**Comment by marionf** [comment] 2020-03-09 09:10
I don't have the answer but maybe @matks has it ?

**Comment by matks** [comment] 2020-03-09 14:01
> Hello @marionf ,
> Let me please add another question for a better understanding. By re-migration, you mean from Symfony+Twig to Symfony+VueJs. Right? Or we will be using same technology but with different architecture?

No, we keep Symfony+Twig.

Product page listing was migrated to Symfony+Twig a long time ago following an specific architecture. Since then, we have built a generic system to create listings in Symfony page (see https://devdocs.prestashop.com/1.7/development/components/grid/) that we are using for all of our listings.

So today we have
- product listing using custom system
- every other migrated listing using the grid

This is bad on multiple levels: developers need to learn 2 systems, twice the cost of maintainance ...

So we're going to re-migrate the product listing so it is built using the Grid in order to harmonize all prestashop listings. This way we'll be able to say "hello, if you want to modify a listing in PrestaShop BO, you just need to learn how to use the Grid, and then you know how any listing works"

**Comment by arouiadib** [comment] 2020-03-09 14:51
@matks, thank you for the explanation. Important before building a BO module with listing.
I think documentations has evolved over time. Thanks to every contributor.

**Comment by florine2623** [comment] 2024-01-03 14:59
This is fixed on PS 8.1.x :


https://github.com/PrestaShop/PrestaShop/assets/16019289/144342a9-05b0-4096-9362-95aff9e7e5b3



I'm closing the issue.

**Closed as completed by florine2623** 2024-01-03 14:59 UTC
Labels: Bug, Minor, BO, Catalog, Fixed, 1.7.5.2, 1.7.6.0, Must-have, 1.7.7.3
