### ISSUE TITLE
Unable to import combinations sizes with the same reference (index) it only import first one

### ISSUE THREAD

**Issue by nikos83** [PrestaShop/PrestaShop#23714] opened 2021-03-20 19:33 UTC
#### Describe the bug

I want to import product combinations ( sizes and colors). On this combinations each product have reference number (index). Products with the same color have the same reference number. (there is 33 sizes on color1 where every 33 products have the same reference). In my file I have 66 combinations.

From 66 combinations only 2 have been imported.
Imported combination are first size color nr1 and first size of color nr2. All the others are not in combination.
 
#### Expected behavior

It should import 66 combinations. 

#### Steps to Reproduce
1. Download [Example of CSV file](https://mail.mmkomputery.pl/test.csv)
2. If you have fresh installation of Prestashop you should have product id 11 - otherwise you need to change id on test.csv
3. Click import from Advanced menu
4. Select import combination
![image](https://user-images.githubusercontent.com/4093704/111882717-5a2f4580-89b7-11eb-87c2-b4ead60d3940.png)
4. Map file to types like this:
Product ID*  Attribute (Name:Type:Position)* Value (Value:Position)* EAN13 Image URLs (x,y,z...) image alt texts (x,y,z...) Quantity, Reference (index)
![image](https://user-images.githubusercontent.com/4093704/111882972-cc545a00-89b8-11eb-9191-be2cfb0e86fb.png)
And the next image
![image](https://user-images.githubusercontent.com/4093704/111882986-e3934780-89b8-11eb-8eb9-ff9260807d80.png)
Then click on import
![image](https://user-images.githubusercontent.com/4093704/111883007-f9087180-89b8-11eb-842d-e161b977f22f.png)

It should import 66 combinations of the size and color where the product with same color has the same reference number.

It only imported two combinations
![image](https://user-images.githubusercontent.com/4093704/111883079-57355480-89b9-11eb-8e47-70194af1e6df.png)
So it looks like the reference number is unique but I **have not** selected on import (yes on reference)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.4.6 also checked on 7.2.2
* https://youtu.be/R_Nw8qjqq34

**Comment by hibatallahAouadni** [comment] 2021-03-22 10:51
Hello @nikos83 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12321. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-22 10:51
Duplicate of #12321

**Closed as completed by hibatallahAouadni** 2021-03-22 10:51 UTC
Labels: Duplicate
