### ISSUE TITLE
Wrong contextual mail logo in multistore

### ISSUE THREAD

**Issue by jweillinfo** [PrestaShop/PrestaShop#31033] opened 2023-01-25 17:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When emails are sent with a specific $id_shop in parameter, if a different PS_LOGO_MAIL is configured for this shop and if the mail is sent using an other store context, it won't be used because Configuration::get uses the contextualised shop to check if a specific LOGO_EMAIL exists. 

### Expected behavior

The correct PS_LOGO_MAIL should be used in all the emails

### Steps to reproduce

1. Use a multistore prestashop.
2. Different stores must have a different PS_LOGO_MAIL (configured in Theme).
3. Display an Order corresponding to a store that is not the default store of the installation, using the context "all stores" (or another store).
4. Send an email on this Order or change the Order State to a state that will send an email
 
The attached logo will not be the one that corresponds to the store

### PrestaShop version(s) where the bug happened

1.5.4.0 to 8.0.x

### PHP version(s) where the bug happened

all

**Comment by florine2623** [comment] 2023-01-26 10:05
Hello @jweillinfo ,

I can't reproduce your issue on PS 8.0.1.

My configuration on shop2 :
<img width="1215" alt="Screenshot 2023-01-26 at 11 01 52" src="https://user-images.githubusercontent.com/16019289/214808865-2f05dac2-fd1a-4fd3-884a-9eff397ba94d.png">


My order confirmation with the correct logo :
<img width="619" alt="Screenshot 2023-01-26 at 11 03 26" src="https://user-images.githubusercontent.com/16019289/214808805-2c9613f7-9507-4da6-b7b5-dc41b3e6f64c.png">

I canceled my order on my shop2, same logo in email :
<img width="659" alt="Screenshot 2023-01-26 at 11 01 07" src="https://user-images.githubusercontent.com/16019289/214808958-b8edd680-6084-45fa-b98c-65b4ef04ec85.png">
<img width="1121" alt="Screenshot 2023-01-26 at 11 01 17" src="https://user-images.githubusercontent.com/16019289/214808981-e8468f41-8abd-440c-a008-0a03c5fc700e.png">

Am I missing something ?
Thanks!

**Comment by jweillinfo** [comment] 2023-01-26 10:50
Hello @florine2623, 

please be sure to upload recognizable different logos for "Header Logo" and "Email Logo" for each shop, you should have 4 different logos

**if your test order was made on shop 1 :** 
- if you manage this order to send an email on "shop 1" context, (or on "all shops" context, if the shop 1 if your "default" shop)
=> you should get the correct PS_LOGO_MAIL for shop 1
- but if you manage this order on "shop 2" context
=> the correct PS_LOGO_MAIL won't be found and the system will use the shop's header logo instead "PS_LOGO"

**if your test order was made on shop 2 :** 
- if you manage this order to send an email on "shop 1" context, (or on "all shops" context, if the shop 1 if your "default" shop)
=> the correct PS_LOGO_MAIL won't be found and the system will use the shop's header logo instead "PS_LOGO"


the reason is because `Configuration::get('PS_LOGO_MAIL')` don't use the `$idShop` given as a parameter of the `Mail.php` `Send()` function, and it will use the contextual selected shop to get `PS_LOGO_MAIL` instead of order's `$idShop`


i hope this will help you to reproduce this issue

regards

**Comment by florine2623** [comment] 2023-01-26 17:06
@jweillinfo ,

Tested again, with 4 different logos :
<img width="1220" alt="Screenshot 2023-01-26 at 17 56 09" src="https://user-images.githubusercontent.com/16019289/214899107-85eb6948-8418-4cbc-8b12-a5560701cd88.png">

<img width="1221" alt="Screenshot 2023-01-26 at 17 55 59" src="https://user-images.githubusercontent.com/16019289/214899126-90b2cea3-8315-4a9a-82c1-567a731fe3a4.png">

Indeed I have reproduce the issue, I have the same logo for my 2 orders from different shops:
<img width="1082" alt="Screenshot 2023-01-26 at 18 04 47" src="https://user-images.githubusercontent.com/16019289/214901168-3ba2f1af-7bfe-40dd-826e-aac0d0fe12e4.png">


On my default shop: (I should have had the green logo)
<img width="861" alt="Screenshot 2023-01-26 at 17 57 47" src="https://user-images.githubusercontent.com/16019289/214900631-3aad5b52-2cd9-4541-a03b-04f9c62a04ca.png">

On shop A:
<img width="842" alt="Screenshot 2023-01-26 at 18 01 48" src="https://user-images.githubusercontent.com/16019289/214900601-617d0796-f28c-40f7-81bc-5d9d84af15fc.png">

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by jweillinfo** [comment] 2023-01-26 17:14
@florine2623 perfect, 

i made a PR yesterday to fix this little issue, you can find it there : https://github.com/PrestaShop/PrestaShop/pull/31032

regards

**Comment by mflasquin** [comment] 2023-02-13 11:51
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31032

**Closed as completed by mflasquin** 2023-02-13 11:51 UTC
Labels: Bug, Minor, BO, Order, Theme & logo, Email, Multistore, Verified, 8.0.1
