### ISSUE TITLE
Faceted Search in special product pages "new-products", "prices-drop", "best-sales" etc. - 🚀 Feature Request

### ISSUE THREAD

**Issue by rzuf666** [PrestaShop/PrestaShop#25323] opened 2021-07-12 14:43 UTC
#### Is your feature request related to a problem?

Faceted Search only works in product categories. 

For years, product subpages displaying new products, with discounts, bestsellers only have the option of sorting (which also does not work well, bugs have been reported, such as this one https://github.com/PrestaShop/PrestaShop/issues/25309). 

#### Describe the solution you'd like

These subpages cannot be filtered by variants and features.

some-domain.com/new-products
some-domain.com/prices-drop
some-domain.com/best-sales

It would be great if Faceted Search also worked on these product subpages.

**Comment by hibatallahAouadni** [comment] 2021-07-12 14:55
Hello @rzuf666 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by Hlavtox** [comment] 2021-07-12 15:59
Duplicate: https://github.com/PrestaShop/PrestaShop/issues/15137

**Comment by hibatallahAouadni** [comment] 2021-07-13 09:19
Hello @rzuf666 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15137. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @Hlavtox for the tip :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-13 09:19
Duplicate of #15137

**Closed as completed by hibatallahAouadni** 2021-07-13 09:19 UTC
Labels: Improvement, FO, Duplicate, Taxes and Prices, Faceted search
