### ISSUE TITLE
SEO Optimisation Micro-data

### ISSUE THREAD

**Issue by jimmydupre** [PrestaShop/PrestaShop#22934] opened 2021-01-21 16:09 UTC
#### Describe the bug

Product listings must not contain micro-data. This is a **recommendation from Google**.

Here is the source:
https://developers.google.com/search/docs/data-types/product#guidelines

I noticed that in the product thumbnails we have these attributes on the article tag that we could remove to correct this problem and be in the indications of Google :
```html
itemscope itemtype = "http://schema.org/Product"
```
apart from these, are not necessary.
It would be wise to remove them in order to avoid an error in the google search console.

#### Predictable behavior

Here is a console error I may have had due to it:

![InkedCapture d’écran 2021-01-18 à 15 18 03_LI](https://user-images.githubusercontent.com/9616658/105378054-b837ea80-5c0b-11eb-8098-4110d6283fd5.jpg)

Sorry, this image is in French.

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-21 16:35
Hello @jimmydupre 

Could you please check this issue #22636 cause it seems similar to yours :wink: 
And we are already have a multiple similar issues about this topic:

#13737 - Solved - big problem about the canonical url in the category pages when there is pagination and multi languages 
#15554 - Errors with latest changes on itemList for products listing
#15764 - Some microdata are missing in the product page

Please check and feedback.
Thanks!

**Comment by jimmydupre** [comment] 2021-01-22 07:53
I looked at the issues you gave me unfortunately that is not one of them. 
I think it would be interesting to add it to this issue:
[#18402](https://github.com/PrestaShop/PrestaShop/issues/18402) - [EPIC] - SEO optimizations

**Comment by hibatallahAouadni** [comment] 2021-01-22 11:17
Hello @jimmydupre 

Could you please check this screen record below:

https://drive.google.com/file/d/16aBG8tfPRGuo6XpHqh-C7k3E62p6sLLY/view

I believe this is your issue, please check and feedback.
Thanks!

**Comment by jimmydupre** [comment] 2021-01-22 13:13
Hello @hibatallahAouadni ,
It's exactly that. Thank you

**Comment by hibatallahAouadni** [comment] 2021-01-22 14:02
Hello @jimmydupre 

Thanks for the feedback.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22416. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-22 14:02
Duplicate of #22416

**Closed as completed by hibatallahAouadni** 2021-01-22 14:02 UTC
Labels: Bug, FO, Duplicate, SEO & URLs, 1.7.6.9

**Comment by alfonsolr09** [comment] 2021-02-07 20:36
@jimmydupre 
I think it is solved with version 1.7.7.0 (this pr #14558)
