### ISSUE TITLE
HTML-Entities in Checkout-Form

### ISSUE THREAD

**Issue by jansass** [PrestaShop/PrestaShop#15673] opened 2019-09-24 14:32 UTC
In last step of Checkout-Form a client can send a message attached to the order (and attached to client service messages). This form encodes special chars like öäüÖÄÜß to HTML-entities like &ouml; etc. Other forms are not affected, just in cart, last step textarea #delivery_message.

Reproducable with an 1.7.5 and even 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-09-24 14:35
Hi @jansass,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9726
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-24 14:35
Duplicate of #9726

**Closed as completed by khouloudbelguith** 2019-09-24 14:35 UTC
Labels: Duplicate
