### ISSUE TITLE
FO - merchandise return table: if we click on the checkbox in the header, checkboxes in the table are no more clickable

### ISSUE THREAD

**Issue by stigmi-man** [PrestaShop/PrestaShop#28963] opened 2022-07-05 14:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the order details page when we want to return product, if we click on the checkbox in the header (encircled in red), checkboxes inside the table are no more clickable (encircled in orange) :
![image](https://user-images.githubusercontent.com/45425264/177344007-4dec81ae-c204-413c-ac85-8095d2916927.png)
I reproduce the bug with the **Classic Theme** on FF/Chrome but not with the "Prestarocket Theme"

### Steps to reproduce

1. Go to Your Account -> My order history and details
2. Select an order to return
3. Scroll down to the list of products
4. Click on the checkbox in the header
5. The checkboxes inside the table are no more clickable

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.0

**Comment by HanaRebaiQA** [comment] 2022-07-06 11:14
Hello @stigmi-man 

Thanks for your report.
I was able to reproduce your issue on **8.0.x and PS1786.**
It's OK on 1778. **So it's a regression.**

8.0.x : NOK :x: 

https://user-images.githubusercontent.com/92912932/177537544-391db961-fb35-4e1e-a8d5-75f7c4dbd49f.mp4



PS1786 : NOK :x: 

https://user-images.githubusercontent.com/92912932/177537583-55bab3e8-c32a-4892-8515-41b0737642d0.mp4


PS1778 : Ok :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/177537490-e4d0f619-c81b-4b4c-835a-94021df9ae63.mp4



I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank You!

**Closed as completed** 2022-10-07 07:52 UTC
Labels: Bug, Minor, FO, Order, Merchandise returns, Regression, PR available, Verified, 1.7.8.6
