### ISSUE TITLE
Hit Enter key on cart set a random quantity

### ISSUE THREAD

**Issue by CyrilGuyot74** [PrestaShop/PrestaShop#10205] opened 2018-08-29 19:18 UTC
Hello

**Describe the bug**
In the cart screen on front-office, is the user set a new quantity then hit enter key, a randon quantity is shown on the screen

**To Reproduce**
1. Go to http://fo.demo.prestashop.com/fr/ then add a product in the cart
2. In http://fo.demo.prestashop.com/fr/panier?action=show put a new quantity then enter (don't use the mouse)
3. the quantity is set to another name.

**Screenshots**
It seems that AJAX call are done twice, the first one is ok and the second is a new quantity
![image](https://user-images.githubusercontent.com/3932427/44810040-c4e9bd00-abd0-11e8-8f17-488e03aeeef7.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-08-30 07:37
Hi @CyrilGuyot74,

I manage to reproduce the issue with the last version 1.7.4.2.
https://drive.google.com/file/d/1RdMkPt6b18Njh0TWOwweTr0Co3RClaJH/view
![image](https://user-images.githubusercontent.com/16067358/44836951-943d6e00-ac38-11e8-903e-20994bb1085a.png)
We will see how to fix it.

Best regards, Khouloud

**Comment by marionf** [comment] 2018-08-30 08:19
Duplicate of #9841

**Closed as completed by marionf** 2018-08-30 08:19 UTC
Labels: Bug, FO, Duplicate, Shopping carts, 1.7.4.2
