### ISSUE TITLE
Related product update after adding to card issue

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#14847] opened 2019-07-24 18:58 UTC
**Describe the bug**
Product page content is updated with first related product content.

**To Reproduce**
1. Go to any related product page
2. Add it to cart
3. Close modal
4. Page content (image, title, price) will be updated with first related product content

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-26 06:40
Hi @Flower7C3,

I did not manage to reproduce the issue with PS.7.6.0.
I attached a screen record
https://drive.google.com/file/d/11S5Oelz2ToZjjGwr2cH7FMfWg0lZ0EgT/view
Thanks to check and feedback.

**Comment by Flower7C3** [comment] 2019-07-30 19:20
Hi @khouloudbelguith You did not understand my problem. I mean product with relations (package).

https://we.tl/t-pKOObQENnp

**Comment by khouloudbelguith** [comment] 2019-07-31 09:32
@Flower7C3, thanks for your feedback.
Related products part is this section
![image](https://user-images.githubusercontent.com/16067358/62200781-043f0180-b37e-11e9-9184-bc2d3a788ab0.png)
But a pack product is a type of product.
In my case, I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/11wKXcRBGpIkUS-kOlmMI1LmPR84NYFDu/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Flower7C3** [comment] 2019-08-01 20:11
* server setup and configuration: Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux, PHP 7.1.8 
* PrestaShop version: 1.7.6.0

Problem is, that when I click **Continue shopping** button on modal there there is emited JS event **updateProduct** and it calls URL with all products from pack like this:
http://example.com/index.php?controller=product&token=30ec951f282675157ba9ac8febe043cd&id_product=3434&id_customization=0&qty=1&token=30ec951f282675157ba9ac8febe043cd&id_product=668&id_customization=0&token=30ec951f282675157ba9ac8febe043cd&id_product=2505&id_customization=0

**Comment by khouloudbelguith** [comment] 2019-08-02 09:18
@Flower7C3, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by Flower7C3** [comment] 2019-08-13 18:07
@khouloudbelguith there are no PHP error logs. Problem is in AJAX request after modal is closed.

**Comment by mariem-abid** [comment] 2019-08-16 14:11
Hi @Flower7C3,

Did you use the default template by Prestashop?

**Comment by Flower7C3** [comment] 2019-08-16 20:19
No. I have custom template. But this request comes from `themes/_core/js/product.js` file. Problem also occurs when I add product from main page and category page.

**Comment by khouloudbelguith** [comment] 2019-08-20 11:41
@Flower7C3, the issue occurs with related products & not a pack product as reported here: #9919.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-09-19 07:34
Hi @Flower7C3,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-19 07:34 UTC
Labels: Bug, FO, Pack, No change required, 1.7.6.0
