### ISSUE TITLE
Enable all shops from maintenance page - Multistore

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#17181] opened 2020-01-15 13:39 UTC
After updating Prestashop it would be nice if it would be possible to enable all stores at once from being in All shops.

Now this is not the case, yes you can select enable shop, but you still have to go in to every shop and manual set it to yes, enable shop.

**Comment by khouloudbelguith** [comment] 2020-01-15 13:53
Hi @01park,

We are aware of this issue, it is a multistore issue in all symfony pages.
It should be specified by our product team.
Your ticket is a duplicate of #9548
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-01-15 13:53
Duplicate of #9548

**Closed as completed by khouloudbelguith** 2020-01-15 13:53 UTC
Labels: Duplicate
