### ISSUE TITLE
Uncaught TypeError: e.indexOf is not a function psgdpr

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20884] opened 2020-09-08 06:11 UTC
#### Describe the bug

Uncaught TypeError: e.indexOf is not a function

#### Steps to Reproduce

1. Use prestashop 1.7.7.0-beta2
1. Go to 'order'
2. Open console
3. See error

**Screenshots**

![Capture d’écran de 2020-09-08 08-07-08](https://user-images.githubusercontent.com/5064590/92439196-a567d080-f1aa-11ea-9729-0580ce2e3404.png)

#### Additional information

* PrestaShop version: 1.7.7.0-beta2
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-09-08 07:51
Hi @okom3pom,

You can find here PRs to fix the issue:
https://github.com/PrestaShopCorp/psgdpr/pull/96
https://github.com/PrestaShop/PrestaShop/pull/20628
Your ticket is a duplicate of #18776
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-08 07:51
Duplicate of #18776

**Closed as completed by khouloudbelguith** 2020-09-08 07:51 UTC
Labels: Duplicate
