### ISSUE TITLE
Order confirmation page is not loading

### ISSUE THREAD

**Issue by rasasu333** [PrestaShop/PrestaShop#26076] opened 2021-10-04 10:48 UTC
I can't confirm/create new order nor in Backoffice nor in the shop. It does not matter what is the payment method, with all of them is the same (bank wire payment, paypal, e.t. ). After i press button "Confirm order/Pay", it starts to load the page and then after few minutes it shows 503 or blank page. Nothing happens, the new order is not placed. 

First i upgraded Prestashop, from 1.7.7.1 to 1.7.7.3  - it doesn't fixed the problem
Then i upgraded my theme - it doesn't fixed the problem
Then i changed the theme - it doesn't fixed the problem
Debug shows nothing, no error messages

Any ideas how to fix? 

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by rasasu333** [comment] 2021-10-04 10:58
<img width="1157" alt="Screenshot 2021-10-04 at 13 55 14" src="https://user-images.githubusercontent.com/91870185/135839837-c4692f67-d644-4b27-8a4b-2d00500b3243.png">

**Comment by rasasu333** [comment] 2021-10-04 10:59
I receive this then i try to log in to my Backoffice.

**Comment by deepindersingh83** [comment] 2021-10-04 12:23
Last time I came across same error was due to the payment module (stripe).

Try disabling your payment module and then access the backend.

**Comment by hibatallahAouadni** [comment] 2021-10-04 12:23
Hello @rasasu333 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

And it seems that your issue is not a PrestaShop core bug.
If your module is Official, please contact support team on Addons

We will close this issue.

Thanks!

**Closed as completed** 2021-10-04 12:23 UTC
Labels: No change required
