### ISSUE TITLE
Carrier ranges calculated wrong when EU VAT is used

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#11194] opened 2018-10-30 15:17 UTC
**Description**
Shipping prices are calculated incorrectly when you use _EU VAT module_ and _VAT number is entered_

**Preparation**
A) Activate _EU VAT module_, set to country of origin to Czech Republic for example.
B) Set 21% TAX to all countries you want to test, for example Slovakia.
C) Set up the following carrier:
1. Calculate by order sum.
2. Tax rate - 21%
3. Set up ranges for Slovakia - Range from 0 to 249.9 - 5 EUR, range from 250 - 999999 - 0 EUR
4. DO NOT USE the free shipping constant in Shipping > Configuration

D) Create some product with 21% TAX.

**How to reproduce**
E) Go to checkout, add products worth 251 EUR with tax to cart = Customer has FREE shipping = CORRECT
F) Enter VAT number = Customer has to PAY the shipping because order total is now 206 EUR = WRONG

**Possible resolution**
We should enter the range prices in backoffice without tax. Then, in the cart, it should calculate the ranges according to these prices.

**Additionnal information**
PrestaShop version: 1.6.1.22, but try to reproduce it also on 1.7, maybe it happens too
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-10-30 15:33
Hi @Hlavtox,

Is it the same issue described here: #9928?
Thanks!

**Comment by Hlavtox** [comment] 2018-10-30 15:41
@khouloudbelguith

I also have some slight other bugs, but I think it's not related. Even if I fill VAT number, then go back to shop, I see the correct prices, but with "including tax" text, which is wrong - but it could be related to my previous theme modifications in product.tpl.

In my case, the order itself is calculated correctly, both in cart and after submitting it. Just the shipping is calculated wrong.

Shortly:
Customer without VAT number needs to order **250 EUR with tax** worth of goods to get free shipping.
Customer with VAT number needs to order **302,5 EUR with tax (250 without tax)** worth of goods to get free shipping.

**Comment by khouloudbelguith** [comment] 2018-10-30 16:23
Hi @Hlavtox,

I did not manage to reproduce the issue with PS 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1o3CW0c2QBhEakcUTAyTnl1xQmOkszgNO/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2018-11-30 13:58
Hi @Hlavtox,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-30 13:58 UTC
Labels: FO, Can't reproduce
