### ISSUE TITLE
gdpr module

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#12942] opened 2019-03-15 18:48 UTC
prestashop 1.7.5.1 on debian-php 7.2.16
in gdpr module now this is new issue: 
Notice alla linea 545 nel file /var/www/vhosts/100asa.it/httpdocs/modules/psgdpr/psgdpr.php
[8] Trying to get property 'displayName' of non-object

Notice alla linea 546 nel file /var/www/vhosts/100asa.it/httpdocs/modules/psgdpr/psgdpr.php
[8] Trying to get property 'name' of non-object

**Comment by khouloudbelguith** [comment] 2019-03-18 07:53
Hi @centoasa,

We are aware of this issue.
Your ticket is a duplicate of https://github.com/PrestaShop/psgdpr/issues/47
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-18 07:53
Duplicate of https://github.com/PrestaShop/psgdpr/issues/47

**Closed as completed by khouloudbelguith** 2019-03-18 07:53 UTC
Labels: Duplicate
