### ISSUE TITLE
specific price only for a specific customer no works

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#29296] opened 2022-08-09 23:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://watch.screencastify.com/v/N9xrIzjw9k0du06KXbyr

When you cant to  have a specific price for specific customer that no save specific prices 

### Expected behavior

I want to let me the possibility to modify and choose customers where the specific price is applied 

### Steps to reproduce

1. Go to BO > Advenced parameters > New & Experimental features 
2. Enable "New product page - Single store"
3. Go to BO > Catalog  > products 
4. Edit one product 
5. Go to the Pricing Tab 
6. Add a Specific prices wich it'll be applied to all customers 
7. Clic on "Save and publish" and close the tab 
8. Edit this Specific price 
9. Mark only one customer
10. Clic on " Save and publish" 
11. See that there is no save

### PrestaShop version(s) where the bug happened

8.0.0 beta

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment] 2022-08-10 13:06
Hi @alfonsolr09  ,

I reproduce the issue with PrestaShop version 8.0.0 and not with the version 1.7.8.7 because it's not available in this version. Nice catch ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

I'll change your Issue to let us understand more clearly the problem 

Thank you

**Closed as completed** 2022-08-12 14:25 UTC
Labels: Bug, 8.0.x, Minor, BO, Fixed, PR available, Verified, Prerelease
