### ISSUE TITLE
Mail Alerts Module (ps_emailalerts) sends the same out of stock product email multiple times

### ISSUE THREAD

**Issue by abcmkt** [PrestaShop/PrestaShop#37179] opened 2024-10-17 09:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On Prestashop 1.7.8.7 website with PHP version 7.3.33, I encounter a problem with the Mail Alerts module.
The product out of stock notification email is sent several times a day, with the same value of out of stock quantity.

### Expected behavior

I would like the system to send the out of stock notification email with the same out of stock quantity value only once

### Steps to reproduce

Set the Mail Alerts module, in the "Merchant notifications" section, the out of stock alert and a value for the threshold to be considered as out of stock quantity

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by metacreo** [comment] 2024-10-18 07:25
Maybe is not ps_emailalerts sending alerts. Have you ps_mbo or ps_eventbus modules enabled in your ps store ?

**Comment by abcmkt** [comment] 2024-10-18 07:32
> Maybe is not ps_emailalerts sending alerts. Have you ps_mbo module enabled in your ps store ?

Hi, if you mean the "PrestaShop Marketplace in your Back Office" module, I confirm that v2.0.1 is installed in my ps store.
Why?

**Comment by metacreo** [comment] 2024-10-18 07:37
Just try to disable this malware module :) and most likely your problem will disappear.

**Comment by abcmkt** [comment] 2024-10-18 07:47
> Just try to disable this malware module :) and most likely your problem will disappear.

Why do you consider this module as "malware"? Does disabling it involve any changes to the management of the site or something else?
Thanks

**Comment by metacreo** [comment] 2024-10-18 07:55
@abcmkt  Just try :) I can't explain it to you briefly, in general I'll say that there are too many problems because of it. You'll see for yourself if this action helps you. Let's not get into a discussion, just try to turn it off.

Sorry @abcmkt  quite recently there was such a situation with PS 1.7
maybe I got it mixed up ps_mbo with ps_eventbus

**Comment by abcmkt** [comment] 2024-10-18 08:58
> @abcmkt Just try :) I can't explain it to you briefly, in general I'll say that there are too many problems because of it. You'll see for yourself if this action helps you. Let's not get into a discussion, just try to turn it off.
> 
> Sorry @abcmkt quite recently there was such a situation with PS 1.7 maybe I got it mixed up ps_mbo with ps_eventbus

I disabled ps_mbo and it didn't fix it.
Should I try disabling ps_eventbus?

**Comment by metacreo** [comment] 2024-10-18 08:59
yes try. sorry
just ps_mbo not works without ps_eventbus

**Comment by abcmkt** [comment] 2024-10-18 15:10
> yes try. sorry just ps_mbo not works without ps_eventbus

I disabled ps_eventbus at 12 o'clock and since then I am not receiving any more out of stock notification emails.
So I think this system has stopped working, so this is not good and I think I will reactivate this module.
Do you have any other solutions?

**Comment by abcmkt** [comment] 2024-10-18 16:22
> yes try. sorry just ps_mbo not works without ps_eventbus

I disabled ps_eventbus at 12 o'clock and since then I seem to have received fewer notification emails. However, at 17:38 and 17:54 I received two emails referring to the same out of stock product and with the same amount of remaining stock.
So unfortunately it didn't work.
Do you have any other solutions?

**Comment by metacreo** [comment] 2024-10-20 08:23
1. Clean cache via Advanced Parameters > Performance
2. Remove folder /var/cache/prod
3. Keep disabled ps_eventbus and ps_mbo
4. truncate table ps_employee_session

If nothing helped, you need PHP debugging
look at the code of the letters and make sure that the source is the same.
find the classes that call the mail class

**Comment by florine2623** [comment] 2024-10-21 12:12
Hello @abcmkt ,

I'm using PS 9.0.x and Mail alerts v3.0.0 and I cannot reproduce your issue.
I only receive 1 email per article and per out-of-stock option.

I'm closing this issue but you will still be able to comment on the issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2024-10-21 12:12 UTC
Labels: Bug
