### ISSUE TITLE
Exception to update with 1 clik upgrade

### ISSUE THREAD

**Issue by jagcAnelis** [PrestaShop/PrestaShop#25968] opened 2021-09-22 16:01 UTC
#### Describe the bug

```
(1/1) UndefinedMethodException
Attempted to call an undefined method named "getAssociatedLanguage" of class "Cart".
```

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to https://deva.herbalistgrow.es/ 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment] 2021-09-22 16:51
Hello @jagcAnelis 

Could you please provide the steps before upgrading, what's the 1-click upgrade module version?
From which version you did upgrade?
Please check and feedback.

Thanks!

**Comment by jagcAnelis** [comment] 2021-09-22 16:59
Hi there.

The previous version was 1.7.6.3
The steps have been, make a backup copy, put the store in maintenance mode, download the 1-Click Upgrade module
v4.12.0 - from PrestaShop
Activate it and follow the steps indicated.
The web loaded well, but when registering a user a 500 error came up, from then on the eb stopped loading and in debugging mode this error jumps.
Thanks.

**Comment by khouloudbelguith** [comment] 2021-09-24 11:44
Hi @jagcAnelis,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1778 after an upgrade from PS1763 using the 1-click upgrade v4.12.0.
I attached a screen record
https://drive.google.com/file/d/1XpvbOE7UxVondUbuC_KG5JlHXFLl_XhD/view?usp=sharing

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment] 2021-10-11 12:52
Hello @jagcAnelis 

Since we had no news from you for days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-10-11 12:52 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.7.8
