### ISSUE TITLE
Bug when adding more than 600 characters in message block 

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#18030] opened 2020-03-06 16:15 UTC
On the order page, we have this text displayed on top of the page when adding more than 600 chars in the message block : 
`<h1 class="d-inline"> <strong class="text-muted">#5</strong> <strong>KHWLILZLL</strong> </h1> <p class="lead d-inline"> from John DOE </p> <span class="badge rounded badge-dark ml-2 mr-2 font-size-100"> 20,90 € </span> <p class="lead d-inline"> 2020-02-28 <span class="text-muted"> at 17:15:36 </span> </p>`

**Comment by jolelievre** [comment] 2020-03-18 10:12
Hi @colinegin,
I tried to reproduce this bug but it seems impossible to add more than 600 characters, the input blocks adding more characters, so how did you manage to add more than 600?

![Capture d’écran 2020-03-18 à 11 06 19](https://user-images.githubusercontent.com/13801017/76949232-862d6c00-6908-11ea-8df8-7a4f8e579c4f.png)

Also do you have a screenshot of the bug? Thank you

**Comment by colinegin** [comment] 2020-03-18 10:58
I can try to reproduce it, but what you can try is use a predefined message and then copy paste it a few times, and it this case you should be able to add more than 600 characters. Otherwise, by just writing text, indeed you are blocked when reaching the max limit.

**Comment by arouiadib** [comment] 2020-03-18 14:03
I agree with the fact that it is not always reproducible and that you need copy-paste to see the error
![image](https://user-images.githubusercontent.com/23559010/76968714-a3befd80-6929-11ea-9379-f3802ec9f77a.png)

**Comment by colinegin** [comment] 2020-03-18 14:05
Thanks for the screenshot @arouiadib ;)

**Comment by zuk3975** [comment] 2020-03-19 12:19
Couldn't reproduce it nor by writing manually nor by pasting, however I noticed the following inconsistency:
Predefined message (when editing in sell/customer-service/order-messages) allows to fill up to 1200 characters, but here in order message its limited to 600. We must equalize these numbers IMO., someone just needs to decide to leave 600 or 1200

**Comment by colinegin** [comment] 2020-03-19 14:51
After more investigation, let me be more precise about how to reproduce this bug :
- copy paste a few times a preset message - indeed the block seems to be blocking the number of characters
- save
- check in the header, you have the error message as on @arouiadib's screenshot.

About your 2nd comment, you're right @zuk3975, let's be more consistent. I would recommend to accept 600 characters everywhere, but what would happen to merchants who had messages with more characters and update to 177 ?

**Comment by MatShir** [comment] 2020-03-20 16:58
Hi @zuk3975,

On 1.7, you can predefine order messages to 1200 and send them. They are correctly displayed in BO as well as FO. Likewise, for customer service pages, merchants do not have any character limitations. Once a message is sent from the customer service page, they are displayed correctly in FO and order messages bloc.

So the harmonization of the content limitation between the order page, the customer service page and the order messages can wait until all pages are completely migrated. That is probably at the next release. 

In the meantime, confirmed with @colinegin,  we can increase the limitation on the order page to 1200 char to align with the predefined order messages page. Doing the opposite would cause a regression by aligning both pages at 600.

**Comment by zuk3975** [comment] 2020-03-27 10:52
fix in #18326

**Comment by Progi1984** [comment] 2020-04-01 11:25
Fixed by #18326

**Closed as completed by Progi1984** 2020-04-01 11:25 UTC
Labels: Bug, PM ✔️, Minor, Order, Regression, migration, PR available, 1.7.7.x
