### ISSUE TITLE
Translations not saved

### ISSUE THREAD

**Issue by NuclearDetergent** [PrestaShop/PrestaShop#23033] opened 2021-01-28 12:33 UTC
#### Describe the bug

Prestashop dosen't overwrite translations, once a new one is made and saved

#### Expected behavior

Once a new input is made in the translation panel, and saved, it should be shown in the front and backend - it is not. All forms of caching are turned off, and forced refresh has been made to no avail.

#### Steps to Reproduce

1. Go to 'International -> Translations'
2. Select any installed module translation and click edit
3. Input a translation, and click save
4. Return to the same translation, change the input in sted #3´and click save
5. Return once again to the same translation: The input from step #3 is still present

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-28 12:56
Hello @NuclearDetergent 

Could you please check this issue #13392 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by NuclearDetergent** [comment] 2021-01-29 07:47
> Hello @NuclearDetergent
> 
> Could you please check this issue #13392 cause it seems similar to yours.
> Please check and feedback.
> 
> Thanks!

This is not the problem I'm experiencing.

I'm using the standard Prestashop translation panel, to translate any module. Once a translation has been made, this translation is impossible to overwrite with a new one, in the same standard translation panel. 

**Practical example:** So let's say I've translated field "X" with "This order" and saved the translation. Shows up fine. Now I want to make a change to the translation in field "X" and change it to "That order", and save the translation. Nothing happens. The translation still shows "This order" both in the frontend, and the backend. If I check the translation files the field have been changed correctly to the new input "That order" - which is pretty strange. How can the translation file say one thing, and the frontend and backend another? One would quickly jump to the conclusion that it's a caching problem, but all of the caching have been turned off in the backend, and force refresh have been tried numerous times.

**Comment by hibatallahAouadni** [comment] 2021-02-01 23:09
Hello @NuclearDetergent 

Sorry for the late response.
I didn't manage to reproduce your issue with 1.7.6.8 and 1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1ATps4exByFbVHdn444Lk2bAW01OW6ODw/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-22 09:48
Hello @NuclearDetergent ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-22 09:48 UTC
Labels: Bug, BO, Modules, Translations, No change required, 1.7.6.8
