### ISSUE TITLE
Wrong language displayed on front office in multistore mode

### ISSUE THREAD

**Issue by onkstudio** [PrestaShop/PrestaShop#15753] opened 2019-09-30 12:31 UTC
**Describe the bug**
I have a multistore PS installation configured to display one different language for each store. 

Shop 1 : French
Shop 2 : English

But on front-office, if I have each store opened in different tabs of my navigator, each time I refresh one of the store, the other one displays the wrong language after refresh.

**To Reproduce**
1. Create a multistore PS installation
2. Configure 2 stores with only one different language activated per store
3. Set the default language to the desired one on each store and the "Set language from browser" option to "No".
4. Open both stores front pages  in different tabs in navigator.
5. Refresh one store -> the correct language is displayed
6. Refresh the other store -> the language for the first store is displayed instead of the language set in the back-office.

**Screenshots**
https://www.dropbox.com/s/07e2gifvixphjaf/multistore-wrong-language-1.jpg?dl=0
https://www.dropbox.com/s/9nll9fhsngzrxtu/multistore-wrong-language-2.jpg?dl=0
https://www.dropbox.com/s/72lomw1o9qlz9il/multistore-wrong-language-3.jpg?dl=0
https://www.dropbox.com/s/cdaxjnbbl3uhfcv/multistore-wrong-language-4.jpg?dl=0

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-09-30 12:43
Hi @onkstudio,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9682
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-30 12:43
Duplicate of #9682

**Closed as completed by khouloudbelguith** 2019-09-30 12:43 UTC
Labels: Duplicate
