### ISSUE TITLE
Cart does calculate discount rule, until selecting carrier.

### ISSUE THREAD

**Issue by SnefIT** [PrestaShop/PrestaShop#16442] opened 2019-11-15 21:12 UTC
**Describe the bug**
When I put some items in my cart, it won't calculate the discount rule. (above € 75,- free shippping). When I add items with a total of above € 75, it still says the ocnfigured shipping costs from the carrier (with kg rules). 
When going further in the proces and I (reselect) the default carrier, the discount will be applied.
Seems that the discount rule will only apply correctly when I explicitly select the carrier. This should be also the case when the default carrier is used.

**To Reproduce**
- Create carrier with kilo's
- create 2 columns: 0 - 1kg (€ 0,0) and 1 - 100 kg (€ 4,09).
- create discount for free shipping from € 75,- (no voucher code)
- add items with kg's to the card. The costs from the columns will be calculated, but above € 75,- will not result in discount
- When selecting carrier in the payment and go back to cart, discount will be calculated.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: N/A

**Comment by SnefIT** [comment] 2019-11-15 22:04
Well, it does, when I select that the rule is available for all carriers. Seems to be a nice workaround for me.

**Comment by khouloudbelguith** [comment] 2019-11-18 08:26
Hi @SnefIT,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1H9wTMH8JT_pk_bxNy9qH5a3fhuH0VwbY/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-17 07:31
Hi @SnefIT,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-17 07:31 UTC
Labels: Bug, Shipping, Discounts, Cart rules, No change required, 1.7.6.1
