### ISSUE TITLE
Invalid argument supplied ProductLazyArray json encode

### ISSUE THREAD

**Issue by jacob-v-dam** [PrestaShop/PrestaShop#23670] opened 2021-03-17 09:30 UTC
#### Describe the bug

PHP crashes with the following warning:
```
Warning: Invalid argument supplied for foreach()
```

The products do not have any attachments attached. If i check the value of `$this->product['attachments]` it is null.

#### Expected behavior

Create an json encoded string

#### Steps to Reproduce
- Add products without attachments to the cart
- Try to create an json string with the cart presenter

```
$presenter = new PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter();
json_encode($presenter->present($this->context->cart));
```

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-03-17 09:55
Hello @jacob-v-dam 

Thanks for your issue!
But, could you please make the steps to reproduce clearer :sweat_smile: 

Thanks!

**Comment by jacob-v-dam** [comment] 2021-03-17 10:12
Hope this makes it clear?

**Comment by florine2623** [comment] 2021-03-18 13:19
Hello @jacob-v-dam ,
Which file are you modifying ?
Is it src\Adapter\Cart\CartPresenter.php ?

Could you provide your file ?
Thanks!

**Comment by jacob-v-dam** [comment] 2021-03-18 14:11
I did not modify any file. In my module I required to present the cart to store it for later use.

This is just what i ran:
```
$presenter = new PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter();
json_encode($presenter->present($this->context->cart));
```

**Comment by florine2623** [comment] 2021-03-19 14:22
Ok @jacob-v-dam ,

Are you talking about web services ?
If so, could you provide the JSON schema that you used to create the cart ?

Thanks!

**Comment by florine2623** [comment] 2021-04-07 08:01
Hello,
Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.
Thanks!

**Closed as completed by florine2623** 2021-04-07 08:01 UTC
Labels: Bug, CO, Shopping carts, No change required, 1.7.7.0
