### ISSUE TITLE
PrettyCI is shutting down

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#17983] opened 2020-03-04 16:34 UTC
This year we will have to change PrettyCI for something else.

https://prettyci.com/goodbye

**Comment by khouloudbelguith** [comment] 2020-03-04 16:36
Hi @davidglezz,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers

Thanks!

**Comment by matks** [comment] 2020-03-04 16:47
Already done in https://github.com/PrestaShop/PrestaShop/issues/17744

**Comment by khouloudbelguith** [comment] 2020-03-04 16:49
@matks, can we close this issue as a duplicate?

Thanks!

**Comment by matks** [comment] 2020-03-04 16:56
I think yes :)

**Comment by khouloudbelguith** [comment] 2020-03-04 16:58
Duplicate of #17744

**Closed as completed by khouloudbelguith** 2020-03-04 16:58 UTC
Labels: Duplicate

**Comment by davidglezz** [comment] 2020-03-04 17:02
Sorry for these useless issues.
Now I see: https://github.com/PrestaShop/PrestaShop/issues/17744#issuecomment-593347233
