### ISSUE TITLE
Error Creating Products via API in PrestaShop 1.7.8.10 - PHP Array Offset Boolean Issue

### ISSUE THREAD

**Issue by Jaimevillla** [PrestaShop/PrestaShop#37574] opened 2024-12-04 16:30 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Describe the bug and add attachments
When attempting to create a product using the Webservice API in PrestaShop version 1.7.8.10, the following error occurs:

bash
Copiar código
[PHP Notice #8] Trying to access array offset on value of type bool (/home/niro2332/duplicado.singlequiver.com/classes/Product.php, line 7178)
This error appears even when using a minimal valid XML request body like this:

xml
Copiar código
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <product>
    <id_category_default><![CDATA[16]]></id_category_default>
    <price><![CDATA[29.99]]></price>
    <active><![CDATA[1]]></active>
    <name>
      <language id="1"><![CDATA[Example Product]]></language>
    </name>
    <link_rewrite>
      <language id="1"><![CDATA[example-product]]></language>
    </link_rewrite>
  </product>
</prestashop>
Upon submission, the server responds with a 500 Internal Server Error, accompanied by the PHP notice mentioned above. This issue suggests that the system is attempting to process an invalid boolean or array at the specified line in the Product.php class.

The problem persists across multiple attempts and with different XML configurations. Adjusting or reducing the payload does not resolve the issue, and this seems to be related to the way the Product class processes specific attributes or validates data.

### Expected behavior

Expected behavior
The product should be created successfully without any errors when providing the minimum required fields in the XML payload. The API should properly handle data validation and array offsets to avoid such PHP notices. Additionally, it should gracefully reject invalid data without causing internal server errors, providing clear and actionable error messages instead.

The behavior should allow developers to submit products with minimal configurations and handle optional fields correctly by setting default values or ignoring them when not provided.

### Steps to reproduce

Steps to reproduce
Prepare the XML payload: Use the following minimal XML to create a product:

xml
Copiar código
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <product>
    <id_category_default><![CDATA[16]]></id_category_default>
    <price><![CDATA[29.99]]></price>
    <active><![CDATA[1]]></active>
    <name>
      <language id="1"><![CDATA[Example Product]]></language>
    </name>
    <link_rewrite>
      <language id="1"><![CDATA[example-product]]></language>
    </link_rewrite>
  </product>
</prestashop>
Send a POST request: Use the /api/products endpoint with the XML payload in the body. Ensure that:

The API key is valid and provided via Basic Authentication.
The request has the Content-Type: application/xml header set.
Observe the response: The server returns a 500 Internal Server Error with the following PHP notice in the response body:

bash
Copiar código
[PHP Notice #8] Trying to access array offset on value of type bool (/home/niro2332/duplicado.singlequiver.com/classes/Product.php, line 7178)
Additional notes:

The issue occurs regardless of the content in the id_category_default, price, or name fields.
Other endpoints, such as creating manufacturers (/api/manufacturers), work correctly, suggesting the issue is specific to the Product creation process.
Context and possible cause
This issue may be related to how the Product.php class in PrestaShop 1.7.8.10 handles certain attributes or validations during product creation. Specifically, the error implies that the system is trying to access an array index or boolean value that does not exist or is invalid.

Given the error trace and the changes introduced in recent PHP versions (such as stricter type checking in PHP 7.4+), it is possible that the API codebase does not account for these stricter rules, causing the notice.

This could be resolved by:

Ensuring that array or object values are checked before accessing their indices or properties.
Reviewing the code in Product.php at line 7178 and around it to ensure compatibility with PHP 7.4+.
Updating the API to provide clearer error messages and reject invalid fields with proper HTTP status codes (e.g., 400 Bad Request).
This behavior makes it difficult to integrate with the API reliably and suggests there may be a regression or compatibility issue introduced in PrestaShop 1.7.8.10.

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Not related to a module

### Your company or customer's name goes here (if applicable).

Single Quiver (Duplicated Environment)

**Comment by florine2623** [comment] 2024-12-04 16:47
Hello @Jaimevillla ,

Yuur issue is similar to https://github.com/PrestaShop/PrestaShop/issues/37574

Could you confirm ?

Thanks

**Comment by Jaimevillla** [comment] 2024-12-04 16:50
Hello @florine2623 

Which issue?

Does it happen to you too?

**Comment by florine2623** [comment] 2024-12-04 16:53
To this one : https://github.com/PrestaShop/PrestaShop/issues/37574

I have reproduce the problem explained here yes : https://github.com/PrestaShop/PrestaShop/issues/37574

**Comment by Jaimevillla** [comment] 2024-12-04 17:52
Hello @florine2623, I believe there has been a misunderstanding. Issue #37574 is the report I opened myself regarding this problem. It seems you are referring to my own report. Could you clarify if this issue has already been reproduced on your side? Thank you.

**Comment by florine2623** [comment] 2024-12-05 08:41
Please excuse me @Jaimevillla , this is the issue I'm talking about : https://github.com/PrestaShop/PrestaShop/issues/28586

**Comment by kpodemski** [comment] 2024-12-05 14:35
Hello @Jaimevillla 

You can change this method from:

```
public function getCoverWs()
    {
        $result = $this->getCover($this->id);

        return $result['id_image'];
    }
```

to

```
public function getCoverWs()
    {
        $result = $this->getCover($this->id);

        return $result['id_image'] ?? 0;
    }
```

but origin of this error is that you have some products without a cover in your store

**Comment by paulnoelcholot** [comment] 2024-12-26 14:05
Hello @Jaimevillla,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-12-26 14:05 UTC
Labels: Bug, Webservice, 1.7.8.x, Invalid
