### ISSUE TITLE
Bad client IP from Tools::getRemoteAddr

### ISSUE THREAD

**Issue by maniolias** [PrestaShop/PrestaShop#21780] opened 2020-11-05 16:39 UTC
#### Describe the bug

The method Tools::getRemoteAddr has a bad behaviour when Prestashop is behind a proxy.

If I understand correctly  this method :

REMOTE_ADDR is used as client IP if present and:
- doesn't match '/^127\..*/i'
- doesn't match '/^172\.16.*/i'
- doesn't match '/^192\.168\.*/i'
- doesn't match '/^10\..*/i'

Even if HTTP_X_FORWARDED_FOR is set.

But if HTTP_X_FORWARDED_FOR is set it contains the client IP at index 0 then the proxy IP addresses and REMOTE_ADDR contains the last proxy IP not the client IP. So REMOTE_ADDR can be avoided if HTTP_X_FORWARDED_FOR is present.

If the proxy have many IP (cloud native one like GCP external load balancer for example) the cookie and the value returned by getRemoteAddr have a lot of chance to be differents. This behavior introduce an error when we try to log in the backoffice. When we try to connect we are disconnected 9/10 times.

#### Expected behavior

Get ip from HTTP_X_FORWARDED_FOR even if REMOTE_ADDR to get the right client ip.

##### From the app

1. Start a Prestashop behind a proxy with many IP addresses
2. Try to log in the back office
3. If you're lucky (same proxy on cookie creation call and page loading call) you will see the backoffice, otherwise you're back on the login page.

##### With code
Each call shoul get 1.2.3.4 but the first one get 5.6.7.8.

```php
<?php

require(__DIR__.'/config/config.inc.php');

$_SERVER = array(
  "HTTP_X_FORWARDED_FOR" => "1.2.3.4,5.6.7.8",
  "REMOTE_ADDR" => "5.6.7.8",
);

echo "Should get 1.2.3.4\n";
echo Tools::getRemoteAddr();
echo "\n";

$_SERVER = array(
  "REMOTE_ADDR" => "1.2.3.4",
);

echo "Should get 1.2.3.4\n";
echo Tools::getRemoteAddr();
echo "\n";

$_SERVER = array(
  "HTTP_X_FORWARDED_FOR" => "1.2.3.4,10.2.3.4",
  "REMOTE_ADDR" => "10.2.3.4",
);

echo "Should get 1.2.3.4\n";
echo Tools::getRemoteAddr();
echo "\n";

exit(0);
```
Output:
```
Should get 1.2.3.4
5.6.7.8
Should get 1.2.3.4
1.2.3.4
Should get 1.2.3.4
1.2.3.4
```

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34-8

**Comment by matks** [comment] 2020-11-05 17:04
Makes sense 👍

**Comment by matks** [comment] 2020-11-05 17:31
After reading a few more RFCs, I have to say it's a bit harder to be confident of this change 😅 

The issue you raise is real but I'm not 100% sure we can ignore REMOTE_ADDR when HTTP_X_FORWARDED_FOR is set

ping @PierreRambaud @djodjo3  who have huge network knowledge, can you help me ?

**Comment by matks** [comment] 2020-11-05 21:58
Prepared some unit test following your scenario https://github.com/PrestaShop/PrestaShop/pull/21784

**Comment by hibatallahAouadni** [comment] 2020-11-09 13:15
Hello @maniolias 

Is your issue similar to this one #17117 ?
Please check and feedback.

Thanks!

**Comment by PierreRambaud** [comment] 2020-11-09 13:17
Hi everyone.

Yes @hibatallahAouadni it's a duplicate :wink:

**Comment by PierreRambaud** [comment] 2020-11-09 13:17
Duplicate of #17117

**Closed as completed by PierreRambaud** 2020-11-09 13:17 UTC
Labels: Bug, CO, Duplicate, 1.7.6.8
