### ISSUE TITLE
ps_facetedsearch remove H1 tag

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15538] opened 2019-09-13 18:09 UTC
Hi
can you remove forever these H1 from modules?
I've already explain the motive to remove them
in active-filters.tpl replace it with a "p" tag

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/64884497-2d7fcc80-d662-11e9-8ad9-1753a2bf93be.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0
Module version: 3.2.1

**Comment by mariem-abid** [comment] 2019-09-16 10:33
Hi,
@maofree, thank you for your report.
@marionf, @colinegin, what do you think?

**Comment by PierreRambaud** [comment] 2019-09-17 08:12
Duplicate of #14044

**Closed as completed by PierreRambaud** 2019-09-17 08:12 UTC
Labels: Improvement, Duplicate, Faceted search, 1.7.6.1
