### ISSUE TITLE
Cannot manually upgrade a native module to a version that is not the last given by ps_distributionapiclient

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#29594] opened 2022-09-09 15:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If I try to manually update (with a zip) a native module to a version that not the latest one returned by ps_distributionapiclient, it's always the one given by ps_distributionapiclient that gets installed.

### Expected behavior

I should be able to manually update a module

### Steps to reproduce

1. In the module manager, fully delete psgdpr
2. download [an old version of psgdpr (v1.4.0)](https://github.com/PrestaShop/psgdpr/releases/download/v1.4.0/psgdpr.zip) and install it manually
3. download [a version that is not the latest one (v1.4.1)](https://github.com/PrestaShop/psgdpr/releases/download/v1.4.1/psgdpr.zip)
4. Try to install it manually
5. The version installed is the latest one (v1.4.2)

### PrestaShop version(s) where the bug happened

8.0.x

**Comment by hibatallahAouadni** [comment] 2022-09-12 09:30
Hello @atomiix 

I was blocked in the steps two cause of this error, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/189620516-0e1b50df-e7c1-4c84-b473-dfdbb5e730a5.png)

Waiting for your feedback.

Thanks!

**Comment by atomiix** [comment] 2022-09-12 09:34
@hibatallahAouadni it looks like psgdpr was not removed correctly and thus the psgdpr table was still present in the DB.
Also, what's your version of ps_distributionapiclient?

**Comment by hibatallahAouadni** [comment] 2022-09-12 09:38
Hello @atomiix 

My version of ps_distributionapiclient is v1.0.1
I upgraded to v1.0.2, and I tried again to upload the module. But, I still encounter the same error again :disappointed: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-09-15 16:18
Hello @atomiix 

Thanks for all your feedback on this issue (on Slack).
I reproduce the issue with PS8.0.x, `ps_distributionapiclient` v1.0.1, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/190455681-f090f6cb-7f13-4ea4-9ea4-f960024cd8cc.mp4

Thanks for your PR :superhero:

**Comment by matks** [comment] 2022-09-21 19:40
This ticket will be fixed with ps_distributionapi release 1.0.3

**Comment by matks** [comment] 2022-09-22 08:29
PR for release https://github.com/PrestaShop/ps_distributionapiclient/pull/12

**Comment by matks** [comment] 2022-10-25 12:32
I put this ticket back in "In progress" as there is issues on the PR for the module release https://github.com/PrestaShop/ps_distributionapiclient/pull/12

**Comment by matks** [comment] 2022-12-19 14:42
This bug is actually blocked by https://github.com/PrestaShop/PrestaShop/issues/29542 (see https://github.com/PrestaShop/ps_distributionapiclient/pull/12)

@atomiix explored the issues detected by @florine2623 and is now blocked by the above bug

**Comment by matks** [comment] 2022-12-19 16:44
OK I have read https://github.com/PrestaShop/PrestaShop/issues/29542 and here is a summary of the problem:

## When the Module Manager is tasked to update module X from version A to a new version B it needs to know "which version is the target"?
This is because modules can contain upgrade scripts ([example](https://github.com/PrestaShop/ps_linklist/tree/dev/upgrade)), and the Module Manager needs to know which scripts to run.

For example if module A contains 5 upgrade scripts:
- upgrade-3.0.1.php
- upgrade-3.0.2.php
- upgrade-3.1.0.php
- upgrade-3.1.1.php
- upgrade-3.2.0.php

An upgrade from A = v3.0.1 to B = v3.1.1 needs to run 3 upgrade scripts upgrade-3.0.2.php upgrade-3.1.0.php and upgrade-3.1.1.php while an upgrade from A = 3.0.0 to B = 3.0.2 only need to run upgrade-3.0.1.php and upgrade-3.0.2.php

So Module Manager needs to know, for a module upgrade
- what version of the module is installed today -> version A
- what is the target version we aim for -> version B

## However PHP classes cannot be [autoloaded](https://www.php.net/manual/en/language.oop5.autoload.php) twice

Versions A and B both contain the same PHP main module class. For [https://github.com/PrestaShop/ps_linklist/](ps_linklist) for example the version 3.0.0 contains the file ps_linklist.php and the version 3.0.1 _also contains ps_linklist.php_

### Most of the time in order to retrieve the version number of a module, we simply load the main module class

So if we try to load the version 3.0.0 of the module then the new version... it won't work. PHP does not allow us to do that. **We cannot use PHP loading to load classes and fetch version numbers** so we are not able to fetch version B.

## 🔴 This is the problem blocking this issue https://github.com/PrestaShop/PrestaShop/issues/29594 🔴 

> So Module Manager needs to know, for a module upgrade
- what version of the module is installed today -> version A
- what is the target version we aim for -> version B

We don't know how to fetch version B when version A has already been loaded.

**Comment by matks** [comment] 2022-12-21 09:22
Very good idea for a solution by @Quetzacoalt91 : start setting module version inside a composer.json file in the module. Reading this JSON file does not require to load a PHP file and allow to workaround the problem.

If we introduce this system, we have to be aware 99% of modules will _not_ contain a composer.son at the beginning so it needs to be a fallback system. When we attempt to fetch the module version 1) look inside composer.json and if it cannot be found/read 2) look inside main PHP module class.

If we implement this "read module version from composer.json" strategy inside the Core we should be able to fix this bug.

**Comment by kpodemski** [comment] 2023-01-16 11:22
Hi @matks 

Any news on this one?

**Comment by lartist** [comment] 2023-01-24 13:22
After investigation it's seems like we reached a dead end. We can't merge https://github.com/PrestaShop/ps_distributionapiclient/pull/12 because of this issue but this issue need this PR to be fixed :)
Indeed here is the needed modification https://github.com/PrestaShop/ps_distributionapiclient/pull/12/files#diff-852d1524531784b3358caad1b84ac1a76535ceb051fa2ae6ff1d0981060cb397R86
It introduces a condition which means "if a zip has been uploaded we are not getting the last version of the module". Currently this condition doesn't exist and then the last version of the module is downloaded even if we provide a specific version of a module through a zip.
Sorry but we have to merge the release first !

**Comment by lartist** [comment] 2023-02-08 13:41
I think this issue can be marked as done.

**Comment by kpodemski** [comment] 2023-03-03 17:48
Distribution API has been released. I think we can close this issue. CC @hibatallahAouadni @MatShir

**Closed as completed** 2023-03-03 20:32 UTC
Labels: Bug, 8.0.x, BO, Regression, Fixed, PR available, Module, ps_distributionapiclient
