### ISSUE TITLE
"An error occurred while processing your request" on product page on quantity or combination change

### ISSUE THREAD

**Issue by astartav** [PrestaShop/PrestaShop#17602] opened 2020-02-11 13:22 UTC
**Describe the bug**
Changing combinations or quantity on product pages results in "An error occured while processing your request". 

**To Reproduce**
1. Go to product page on frontend (for example, https://udevices.shop/en/uecg/26-121-uecg.html)
2. Click on combination (for example, color) or change quantity
3. See red error "An error occured while processing your request"

**Screenshots**
![Screenshot at 15-00-00](https://user-images.githubusercontent.com/8000687/74238890-67bbcb80-4cdf-11ea-9472-92116d72172f.png)
![Screenshot at 14-55-34](https://user-images.githubusercontent.com/8000687/74238900-6d191600-4cdf-11ea-988e-2dd13c446a9f.png)

**Additional information**
Can't find anything in PHP or Nginx logs when this happens. Attaching screenshots from dev tools in Chrome. Also, all of the solutions for similar issues from previous versions don't work because they are implemented in 1.7.6.3 already.
PrestaShop version: 1.7.6.3
PHP version: 7.2
Nginx 1.14.0, Ubuntu 18.04 Server

**Comment by khouloudbelguith** [comment] 2020-02-11 13:31
Hi @astartav,

If you are using Nginx make sure you enable the `mod_rewrite`.
This issue occurs when `mod_rewrite` is not enabled on your server.

The main issue if you try to enable the "Friendly URL", it is enabled but you have a message "`URL rewriting (mod_rewrite) is not active on your server, or it is not possible to check your server configuration. If you want to use Friendly URLs, you must activate this mod`." => so this option should be disabled.
In the FO, URL rewriting is enabled, when I try to switch between combinations, I have an error:
`An error occurred while processing your request`.
We are awre of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #10178
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-11 13:31
Duplicate of #10178

**Closed as completed by khouloudbelguith** 2020-02-11 13:31 UTC
Labels: Duplicate
