### ISSUE TITLE
Upgrade bootstrap

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#17025] opened 2020-01-06 09:14 UTC
Current version is Bootstrap v4.0.0-alpha.5 (release date: 19 Oct 2016)
Why there are alpha versions in stable prestashop releases?

Current version of bootstrap is v4.4.1, the release of stable v4.0 is one year ago..

**Comment by khouloudbelguith** [comment] 2020-01-06 09:29
Hi @sharkooon,

Most of the themes on Addons are already based on the Classic theme, so updating bootstrap 4 to the latest (we all want to do that, believe me) will break **every theme** on the market place first, then will break every website once they will upgrade their shop.

You can rely on the community theme  *[classic-rocket](https://github.com/PrestaShop/classic-rocket)* which is mostly up to date regarding bootstrap :)

For more details, you can follow this improvement: https://github.com/PrestaShop/PrestaShop/pull/9294

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-06 09:30
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/10463#issuecomment-425008014

**Closed as completed by khouloudbelguith** 2020-01-06 09:29 UTC
Labels: Improvement, Duplicate

**Comment by sharkooon** [comment] 2020-01-07 08:28
Understand it, but why decided to use alpha versions. Alpha is not even beta.. Now it's shit because it "will break every theme on the market place first" when upgrading..

Would you suggest that all webshops run on a prestashop alpha version? No, is the answer. Community is depending on the core of prestashop, if the core is not good, community will find other solutions, which is leaving prestashop or using other stuff..

classic-rocket, didnt know that theme. why not include both themes, classic and classic-rocket?

**Comment by khouloudbelguith** [comment] 2020-01-07 08:51
@sharkooon, for more details you can follow this link, it is added by our lead developer
https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-2-pain-points/
You can find in this section `Obsolete dependencies`
>Here’s another example. Early 2016, during the development of the Classic theme (the default theme for PrestaShop 1.7), the team chose to use Bootstrap 4, even though it was still in alpha stages at the time. To my best understanding, they were hoping that the final version would be released in time for 1.7.0.
As Murphy’s Law dictates, this turned out to work out wrong. Not only Bootstrap 4 didn’t ship in time for 1.7.0 (which forced the Classic theme to be released based on Boostrap 4 alpha 5), but the Bootstrap team also decided to introduce major layout changes in alpha 6, after PrestaShop 1.7.0 was released. This effectively blocked the team from upgrading Bootstrap on the Classic theme, because that would break all their child themes (and there are lots of them)… so Classic is now stuck with an obsolete dependency that cannot be upgraded.
Not all is lost though. We have encouraged the development a community-driven project called Classic-rocket, which is an improved version of Classic built on top of the latest Bootstrap version. Thanks to this project, merchants can choose between backward compatibility and benefits from the latest Bootstrap version.

Thanks!
