### ISSUE TITLE
forecast native module doesn't work

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#15606] opened 2019-09-18 23:00 UTC
The native "forecast" module in the dashboard gives a flat graph and doesn't save the parameters values

**To Reproduce**
1. Go to dashboard and see this flat graph
2. Click on parameters and fill some boxes, then save
3. see the still flat graph
4. come back to parameters, change the year (before or after) and go back to actual year : parameters gone !

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3

**Comment by khouloudbelguith** [comment] 2019-09-19 09:08
Hi @elmanu13,

For your information: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9662
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-19 09:08
Duplicate of #9662

**Closed as completed by khouloudbelguith** 2019-09-19 09:08 UTC
Labels: Duplicate, Dashgoals

**Comment by elmanu13** [comment] 2019-09-19 09:14
Thanks for the information about PHP versions. It was not working with 7.1 and 7.2 anyway ;-)
I'll try the solution in the #9662 of wait until it's solved.
Thanks again !
