### ISSUE TITLE
After Update 1.7.5 got problem to price shopping cart

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#12462] opened 2019-02-06 14:29 UTC
**Describe the bug** After updating prestashop 1.7.5 i got a problem with price. 
I insert product into the cart I'll go to checkout and it doesn't give me the price on subtotal. 
It remains 0.00€. 
What can I do ? my customer can't proceed to finish the order. 
<img width="1405" alt="schermata 2019-02-06 alle 15 28 24" src="https://user-images.githubusercontent.com/47249256/52348149-e96d7f00-2a23-11e9-8b17-749ea6a2e179.png">

<img width="1419" alt="schermata 2019-02-06 alle 15 27 23" src="https://user-images.githubusercontent.com/47249256/52348102-c8a52980-2a23-11e9-8c6f-75246acfc206.png">

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-02-06 14:36
Hi @morghy1992,

did you use a product with customization?
Have you a similar issue with this ticket: #10912?
Thanks!

**Comment by morghy1992** [comment] 2019-02-06 14:38
@khouloudbelguith yes I use customization because the products has different size and you can choose it and it change the price. What do you suggest to do?

**Comment by khouloudbelguith** [comment] 2019-02-06 14:42
@morghy1992, so you have a similar issue with this ticket:#10912??
Thanks!

**Comment by morghy1992** [comment] 2019-02-06 14:48
@khouloudbelguith no it's not the same problem

**Comment by khouloudbelguith** [comment] 2019-02-06 15:20
@morghy1992, did you use this section 
![image](https://user-images.githubusercontent.com/16067358/52351405-fa6dbe80-2a2a-11e9-8d4d-86b4bc6ff1e7.png)
in your product added to the cart?
Thanks!

**Comment by morghy1992** [comment] 2019-02-06 15:22
@khouloudbelguith i am sorry just confused customization with combination.
For my product only use COMBINATION I never used customization because I don't need it.

**Comment by morghy1992** [comment] 2019-02-06 15:35
<img width="1439" alt="schermata 2019-02-06 alle 16 42 03" src="https://user-images.githubusercontent.com/47249256/52353116-35252600-2a2e-11e9-83d8-c4f2133e51e1.png">
@khouloudbelguith any suggestion? :) just active debug mode and got this error

**Comment by khouloudbelguith** [comment] 2019-02-06 15:45
@morghy1992, in my case, I did not manage to reproduce the issue with PS1.7.5.0 after an upgrade.
![image](https://user-images.githubusercontent.com/16067358/52353049-10c94980-2a2e-11e9-875f-b587850bd0e7.png)
You can check this value in the file 
Project_PrestaShop/src/Adapter/Presenter/Cart/CartPresenter.php
```
$subtotals['products'] = array(
            'type' => 'products',
            'label' => $this->translator->trans('Subtotal', array(), 'Shop.Theme.Checkout'),
            'amount' => $totalCartAmount,
            'value' => $this->priceFormatter->format($totalCartAmount),
        );
```

The value of subtotals is set in this section.

In the file /Project_Folder/themes/your_theme/templates/checkout/_partials/cart-summary.tpl

```
{block name='cart_summary_subtotals'}
      {foreach from=$cart.subtotals item="subtotal"}
        {if $subtotal && $subtotal.type !== 'tax'}
          <div class="cart-summary-line cart-summary-subtotals" id="cart-subtotal-{$subtotal.type}">
            <span class="label">{$subtotal.label}</span>
            <span class="value">{$subtotal.value}</span>
          </div>
        {/if}
      {/foreach}
    {/block}
```

The subtotal is displayed in this section.
Thanks!

**Comment by morghy1992** [comment] 2019-02-06 15:54
@khouloudbelguith checked and everything is like yours file. I really do not what can be :( do you think I can resolve the problem?

**Comment by khouloudbelguith** [comment] 2019-02-06 15:56
@morghy1992, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by morghy1992** [comment] 2019-02-06 16:01
@khouloudbelguith here debug mode report 
<img width="1434" alt="schermata 2019-02-06 alle 17 00 37" src="https://user-images.githubusercontent.com/47249256/52354475-cb5a4b80-2a30-11e9-9974-aa42a15e1c56.png">

**Comment by morghy1992** [comment] 2019-02-06 16:03
log errors: 
Next LogicException: Request stack is empty in /home/gelitaly/public_html/app/bootstrap.php.cache:3224
Stack trace:
#0 [internal function]: Symfony\Component in /home/gelitaly/public_html/app/bootstrap.php.cache on line 3224
[31-Jan-2019 08:37:42] PHP Parse error:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home/gelitaly/public_html/admin123/index.php on line 26
[31-Jan-2019 21:40:22 Europe/Rome] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message '"" cannot be interpreted as a number' in /home/gelitaly/public_html/vendor/prestashop/decimal/src/Number.php:466
Stack trace:
#0 /home/gelitaly/public_html/vendor/prestashop/decimal/src/Number.php(72): PrestaShop\Decimal\Number->initFromString('')
#1 /home/gelitaly/public_html/src/Adapter/CombinationDataProvider.php(98): PrestaShop\Decimal\Number->__construct('')
#2 /home/gelitaly/public_html/src/Adapter/CombinationDataProvider.php(69): PrestaShop\PrestaShop\Adapter\CombinationDataProvider->completeCombination(Array, Object(Product))
#3 /home/gelitaly/public_html/src/PrestaShopBundle/Controller/Admin/CombinationController.php(54): PrestaShop\PrestaShop\Adapter\CombinationDataProvider->getFormCombination('80')
#4 [internal function]: PrestaShopBundle\Controller\Admin\CombinationController->generateCombinationFormAction('80-81')
#5 /home/gelitaly/public_html/app/bootstrap.php.cache(3246): call_user_func_array(Array, Array)
#6 /home/gelitaly/public_html in /home/gelitaly/public_html/app/bootstrap.php.cache on line 3224
[01-Feb-2019 21:59:44 Europe/Rome] PHP Warning:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: require(/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getPrestashop_Core_Addon_Theme_RepositoryService.php): failed to open stream: No such file or directory' in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php:1207
Stack trace:
#0 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php(1207): ContainerTy3vgqe\appDevDebugProjectContainer::load()
#1 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php(1531): ContainerTy3vgqe\appDevDebugProjectContainer->load('getPrestashop_C...')
#2 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php(1555): ContainerTy3vgqe\appDevDebugProjectContainer->getPrestashop_CategoriesProviderService()
#3 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php(1569): ContainerTy3vgqe\appDevDebug in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:44 Europe/Rome] PHP Fatal error:  ContainerTy3vgqe\appDevDebugProjectContainer::load(): Failed opening required '/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getPrestashop_Core_Addon_Theme_RepositoryService.php' (include_path='/home/gelitaly/public_html/vendor/pear/pear_exception:/home/gelitaly/public_html/vendor/pear/console_getopt:/home/gelitaly/public_html/vendor/pear/pear-core-minimal/src:/home/gelitaly/public_html/vendor/pear/archive_tar:.:/usr/local/php56/pear') in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:44 Europe/Rome] PHP Fatal error:  require(): Failed opening required '/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getDebug_FileLinkFormatter_UrlFormatService.php' (include_path='/home/gelitaly/public_html/vendor/pear/pear_exception:/home/gelitaly/public_html/vendor/pear/console_getopt:/home/gelitaly/public_html/vendor/pear/pear-core-minimal/src:/home/gelitaly/public_html/vendor/pear/archive_tar:.:/usr/local/php56/pear') in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:45 Europe/Rome] PHP Warning:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: require(/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getSecurity_Authentication_Listener_Anonymous_MainService.php): failed to open stream: No such file or directory' in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php:1207
Stack trace:
#0 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php(1207): ContainerTy3vgqe\appDevDebugProjectContainer::load()
#1 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getSecurity_Firewall_Map_Context_MainService.php(13): ContainerTy3vgqe\appDevDebugProjectContainer->load('getSecurity_Aut...')
#2 /home/gelitaly/public_html/var/cache/dev/classes.php(5019): ContainerTy3vgqe\appDevDebugProjectContainer::{closure}()
#3 /home/gelitaly/public_html/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Debug/TraceableFirewallListener.php(33): Symfony\Component\Security\Http\Firewall::S in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:45 Europe/Rome] PHP Fatal error:  ContainerTy3vgqe\appDevDebugProjectContainer::load(): Failed opening required '/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getSecurity_Authentication_Listener_Anonymous_MainService.php' (include_path='/home/gelitaly/public_html/vendor/pear/pear_exception:/home/gelitaly/public_html/vendor/pear/console_getopt:/home/gelitaly/public_html/vendor/pear/pear-core-minimal/src:/home/gelitaly/public_html/vendor/pear/archive_tar:.:/usr/local/php56/pear') in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:45 Europe/Rome] PHP Fatal error:  require(): Failed opening required '/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getDebug_FileLinkFormatter_UrlFormatService.php' (include_path='/home/gelitaly/public_html/vendor/pear/pear_exception:/home/gelitaly/public_html/vendor/pear/console_getopt:/home/gelitaly/public_html/vendor/pear/pear-core-minimal/src:/home/gelitaly/public_html/vendor/pear/archive_tar:.:/usr/local/php56/pear') in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:45 Europe/Rome] PHP Warning:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: require(/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getSecurity_Authentication_Listener_Anonymous_MainService.php): failed to open stream: No such file or directory' in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php:1207
Stack trace:
#0 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php(1207): ContainerTy3vgqe\appDevDebugProjectContainer::load()
#1 /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getSecurity_Firewall_Map_Context_MainService.php(13): ContainerTy3vgqe\appDevDebugProjectContainer->load('getSecurity_Aut...')
#2 /home/gelitaly/public_html/var/cache/dev/classes.php(5019): ContainerTy3vgqe\appDevDebugProjectContainer::{closure}()
#3 /home/gelitaly/public_html/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Debug/TraceableFirewallListener.php(33): Symfony\Component\Security\Http\Firewall::S in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:45 Europe/Rome] PHP Fatal error:  ContainerTy3vgqe\appDevDebugProjectContainer::load(): Failed opening required '/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getSecurity_Authentication_Listener_Anonymous_MainService.php' (include_path='/home/gelitaly/public_html/vendor/pear/pear_exception:/home/gelitaly/public_html/vendor/pear/console_getopt:/home/gelitaly/public_html/vendor/pear/pear-core-minimal/src:/home/gelitaly/public_html/vendor/pear/archive_tar:.:/usr/local/php56/pear') in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207
[01-Feb-2019 21:59:45 Europe/Rome] PHP Fatal error:  require(): Failed opening required '/home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/getDebug_FileLinkFormatter_UrlFormatService.php' (include_path='/home/gelitaly/public_html/vendor/pear/pear_exception:/home/gelitaly/public_html/vendor/pear/console_getopt:/home/gelitaly/public_html/vendor/pear/pear-core-minimal/src:/home/gelitaly/public_html/vendor/pear/archive_tar:.:/usr/local/php56/pear') in /home/gelitaly/public_html/var/cache/dev/ContainerTy3vgqe/appDevDebugProjectContainer.php on line 1207

**Comment by khouloudbelguith** [comment] 2019-02-06 16:07
@morghy1992, the table ps1i_apbooking_cart is created by a custom module, what the exact name of this module?
Thanks!

**Comment by morghy1992** [comment] 2019-02-06 16:09
@khouloudbelguith i do not know the name, maybe this: Leo feature for prestashop 1.7: ajax cart, dropdown cart, fly cart, review, compare, wishlist at product list?

**Comment by khouloudbelguith** [comment] 2019-02-06 16:12
@morghy1992, As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by morghy1992** [comment] 2019-02-06 16:22
@khouloudbelguith thank you very much I am going to contact them now. hope they resolve the problem

**Comment by khouloudbelguith** [comment] 2019-02-06 16:27
@morghy1992, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-03-08 08:15
Hi @morghy1992,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-08 08:15 UTC
Labels: No change required, 1.7.5.0
