### ISSUE TITLE
Weird Cart URL bug

### ISSUE THREAD

**Issue by harm-smits** [PrestaShop/PrestaShop#15973] opened 2019-10-16 08:03 UTC
**Describe the bug**
The Cart URL in `{$urls.pages.cart}` does not work when the user is authenticated in the frontend, as the user simply gets redirected to the homepage. It seems to only work when we add the 'action=show' query parameter to the URL, but then again, the URL provided by PrestaShop should work nonetheless.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by harm-smits** [comment] 2019-10-16 08:05
There have also been previous comments about this issue, forgot to mention that: https://www.prestashop.com/forums/topic/899438-solved-cart-url-redirect-me-to-homepage-if-i-am-logged-in/

**Comment by khouloudbelguith** [comment] 2019-10-16 08:21
Hi @harm-smits,

This is used in your custom theme?
https://github.com/PrestaShop/PrestaShop/blob/33684a3828f66e3a0e91ed53a8239813dcef41dd/themes/classic/templates/checkout/_partials/cart-summary.tpl#L25

Thanks!

**Comment by harm-smits** [comment] 2019-10-16 08:50
No I just referenced the cart on some other buttons too as I tend to support no JavaScript too.

**Comment by khouloudbelguith** [comment] 2019-10-16 08:54
@harm-smits, could you please provide the exact steps to reproduce the issue in a new comment? (the exact files edited).

Thanks!

**Comment by harm-smits** [comment] 2019-10-16 09:13
Well, I just added a link to the checkout.tpl file where it says 'back to cart'. Now when an authenticated user clicks the link he gets redirected to the homepage. It doesnt matter where a user does this, its simply a fault in the cart controller. If the 'action=show' parameter is not set on the cart link when a user is authenticated, the user gets redirected to the homepage.

Code:
```smarty
{**
 * 2007-2019 PrestaShop and Contributors
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://www.prestashop.com for more information.
 *
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2007-2019 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 * International Registered Trademark & Property of PrestaShop SA
 *}
<!doctype html>
<html lang="{$language.iso_code}">

  <head>
    {block name='head'}
      {include file='_partials/head.tpl'}
    {/block}
  </head>

  <body id="{$page.page_name}" class="{$page.body_classes|classnames}">

    {block name='hook_after_body_opening_tag'}
      {hook h='displayAfterBodyOpeningTag'}
    {/block}

    <header id="header">
      {block name='header'}
        {include file='checkout/_partials/header.tpl'}
      {/block}
    </header>

    {block name='notifications'}
      {include file='_partials/notifications.tpl'}
    {/block}

    <section id="wrapper">
      {hook h="displayWrapperTop"}
      <div class="container">

      {block name='content'}
        <section id="content">
          <div class="custom-floating-back-to-cart"><a href="{$urls.pages.cart}">{l s="Back to cart"}</a></div>
          <div class="row">
            <div class="cart-grid-body col-xs-12 col-lg-8">
              {block name='cart_summary'}
                {render file='checkout/checkout-process.tpl' ui=$checkout_process}
              {/block}
            </div>

            <div class="cart-grid-right col-xs-12 col-lg-4">

              {block name='cart_summary'}
                {include file='checkout/_partials/cart-summary.tpl' cart = $cart}
              {/block}

              {hook h='displayReassurance'}
            </div>
          </div>
        </section>
      {/block}
      </div>
      {hook h="displayWrapperBottom"}
    </section>

    <footer id="footer">
      {block name='footer'}
        {include file='checkout/_partials/footer.tpl'}
      {/block}
    </footer>

    {block name='javascript_bottom'}
      {include file="_partials/javascript.tpl" javascript=$javascript.bottom}
    {/block}

    {block name='hook_before_body_closing_tag'}
      {hook h='displayBeforeBodyClosingTag'}
    {/block}

  </body>

</html>
```

**Comment by khouloudbelguith** [comment] 2019-10-16 11:03
@harm-smits, thanks for your feedback.
Yes, redirection works only if this parameter exists `&action=show`.
I have the same behavior as PS1.7.5.2 & PS1.7.6.1.
We need to ask developers if it is normal behavior or an exception PHP?
Ping @PrestaShop/prestashop-core-developers what do you think? 
Same used here: https://github.com/PrestaShop/ps_buybuttonlite/blob/master/controllers/front/RedirectManager.php#L34

Thanks!

**Comment by AlFalahTaieb** [comment] 2020-10-18 19:56
Is there a fix please ?

**Comment by PierreRambaud** [comment] 2020-11-23 15:23
Hi, afaik it's the desired behavior, the action is needed in order to access to the cart (depending on if we want to refresh or show) :thinking:

**Comment by hibatallahAouadni** [comment] 2020-12-14 15:35
Hello @harm-smits ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-14 15:35 UTC
Labels: FO, CO, No change required, 1.7.5.2, Shopping carts FO, 1.7.6.1

**Comment by haveyougotanypets** [comment] 2021-02-21 13:13
HI 

I believe this bug is still present and needs addressing.

To replicate, add the following link to themes/themes/classic/templates/catalog/_partials/product-add-to-cart.tpl

` <a href="{$urls.pages.cart}">View Cart</a>`

Test this link on the product page as a non logged in and a logged in user. It will take you to cart page when user is not logged in, but the home page when the user is logged.

The `{$urls.pages.cart}` variable should provide a link that acts consistently for both logged and none logged users. 

When developing a theme this is the kind of bug that is easily missed.

Please open and add to bug fixes for future releases.
