### ISSUE TITLE
Stock Management: impossible to write minus sign

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#15789] opened 2019-10-02 01:55 UTC
On PS 1.7.5.0, In Stock Management, I can't write a minus sign in the Edit Qty box.
I need to click on the down arrow to display a minus sign then I can write the qty.

**Comment by khouloudbelguith** [comment] 2019-10-02 08:10
Hi @BenTen,

The issue is fixed in the PS1.7.6.0.
Your ticket is a duplicate of #9636
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-02 08:10
Duplicate of #9636

**Closed as completed by khouloudbelguith** 2019-10-02 08:10 UTC
Labels: Duplicate

**Comment by BenTen** [comment] 2019-10-02 08:15
@khouloudbelguith Where is the pull request for this issue?

**Comment by khouloudbelguith** [comment] 2019-10-02 10:19
@BenTen, after the upgrade to PS1.7.6.0, this issue doesn't exist anymore.

Thanks!

**Comment by BenTen** [comment] 2019-10-02 10:33
Yes, but each time after an upgrade PS doesn't work :)

**Comment by khouloudbelguith** [comment] 2019-10-02 11:44
@BenTen, did make an upgrade to PS1.7.6? from which version?

Thanks!
