### ISSUE TITLE
Error 500 trying to fetch blank schema of products

### ISSUE THREAD

**Issue by TomLorenzi** [PrestaShop/PrestaShop#31263] opened 2023-02-07 17:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried to fetch `http://example.com/api/products?schema=blank`

And I got this error `This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error - (Code 5): [PHP Notice #8] Trying to access array offset on value of type null (/prestashop/classes/webservice/WebserviceOutputBuilder.php, line 716) - (Code 5): [PHP Notice #8] Trying to access array offset on value of type null (/prestashop/classes/webservice/WebserviceOutputBuilder.php, line 716)`

### Expected behavior

Return the correct blank schema

### Steps to reproduce

1. Try to fetch the link i provided above
2. Get a 500 error

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by TomLorenzi** [comment] 2023-02-08 08:43
While i was trying to fix the issue it appears to be fixed by this PR https://github.com/PrestaShop/PrestaShop/commit/26b6234c75e9fec8c4df8fb4ab11f826fc9f4429
But the latest downloaded ZIP online does not seems to have this release ? Am I missing something ?

**Comment by HanaRebaiQA** [comment] 2023-02-09 08:32
Hello @TomLorenzi 

Thanks for your report.
Indeed, your issue is a duplicate of this one #26559 which has been fixed in this [PR](https://github.com/PrestaShop/PrestaShop/pull/28280)  on develop branch.

I tried to reproduce it on develop using this URL `http://myshop/api/products?schema=blank` and with **PHP 7.4** when debug mode (enabled and disabled), it's already fixed and it will be available also in the next release 8.1.0

![image](https://user-images.githubusercontent.com/92912932/217758695-c420da9e-d5b5-4902-a52d-e4ece5ae4fb0.png)

https://user-images.githubusercontent.com/92912932/217757414-465f5643-9c83-4734-85fb-85d5031e6fa7.mp4


So, i'll close this issue. 

Thank You!

**Comment by HanaRebaiQA** [comment] 2023-02-09 08:33
Duplicate of #26559

**Closed as completed by HanaRebaiQA** 2023-02-09 08:32 UTC
Labels: Bug, Duplicate, PR available, Invalid

**Comment by TomLorenzi** [comment] 2023-02-09 08:43
No problem, but may I get some explaination why on the latest ZIP available on your website this error was here (downloaded 1 week ago) ?

**Comment by HanaRebaiQA** [comment] 2023-02-09 08:52
I will ping @PrestaShop/product-team @MatShir Please if there is some explanation ? And if this issue could be fixed as a hot bug on `1.7.8.x `?

@TomLorenzi Otherwise, Thanks for your PR!
