### ISSUE TITLE
Faceted Plugin clear cache error

### ISSUE THREAD

**Issue by gaelson** [PrestaShop/PrestaShop#18341] opened 2020-03-27 13:20 UTC
Please when I click on Clear cache I get en error "Indexation failed".
Please how to ?

THX

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by sarahdib** [comment] 2020-03-27 14:05
Hello @gaelson 

Can you  give us some information :
- Prestashop Version : 
- Module Version :

Can you also provide us a screenshot or a screen record

Thank you

**Comment by gaelson** [comment] 2020-03-27 18:05
Prestashop Version : 1.7.5.0
Module Version : 3.5.0

![faceted](https://user-images.githubusercontent.com/10993235/77786341-8ee31800-7055-11ea-9e69-ee674750cec3.jpg)
Thank you

**Comment by sarahdib** [comment] 2020-03-30 08:28
@gaelson 
I didn't reproduce the issue you can see in my screen record. https://drive.google.com/file/d/1_ScoB65aOOYqyu2Zroe46soNle9tiUa3/view

Can you try to reset the module ?

Thank you

**Comment by gaelson** [comment] 2020-03-31 17:24
Hello,
yes all is working excepted the clear cache link. 
I don't know why.

**Comment by khouloudbelguith** [comment] 2020-04-01 12:13
Hi @gaelson,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sarahdib** [comment] 2020-05-05 12:07
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 12:07 UTC
Labels: Bug, BO, Faceted search, No change required, 1.7.5.0
