### ISSUE TITLE
Webservices: [SQL Error] Deadlock on product addition

### ISSUE THREAD

**Issue by rGaillard** [PrestaShop/PrestaShop#12740] opened 2019-02-27 14:52 UTC
**Describe the bug**
When multiple products are added in //, there are SQL errors : 

[SQL Error] Deadlock found when trying to get lock; try restarting transaction. From DbCore->insert() Query was : INSERT INTO `ps_stock_available` (`out_of_stock`, `id_product`, `id_product_attribute`, `id_shop_group`, `id_shop`) VALUES ('2', '237', '0', '0', '1') ON DUPLICATE KEY UPDATE `out_of_stock` = '2',`id_product` = '237',`id_product_attribute` = '0',`id_shop_group` = '0',`id_shop` = '1'
[SQL Error] Deadlock found when trying to get lock; try restarting transaction. From StockAvailableCore->setProductOutOfStock() Query was : INSERT INTO `ps_stock_available` (`out_of_stock`, `id_product`, `id_product_attribute`, `id_shop_group`, `id_shop`) VALUES ('2', '237', '0', '0', '1') ON DUPLICATE KEY UPDATE `out_of_stock` = '2',`id_product` = '237',`id_product_attribute` = '0',`id_shop_group` = '0',`id_shop` = '1' 

**To Reproduce**
Create multiple products using the webservices.

**Comment by rGaillard** [comment] 2019-02-27 14:55
I just tried on PrestaShop 1.6 and this is working well, i reproduce only on the 1.7 version.

**Comment by khouloudbelguith** [comment] 2019-02-27 15:21
Hi @rGaillard,

I used this script with PS1.7.5.1

```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 27/02/19
 * Time: 16:15
 */

ini_set('display_errors','on');
// Here we define constants /!\ You need to replace this parameters
define('DEBUG', true); // Debug mode
//                      !! BACHA, nezapomenout přenastavit i DTB u obrázků dole !!!
define('PS_SHOP_PATH', 'http://shop'); // Root path of your PrestaShop store
define('PS_WS_AUTH_KEY', 'Key'); // Auth key (Get it in your Back Office)
require_once('./PSWebServiceLibrary.php');

$psXML = <<<XML
<prestashop>
<product>
  <id/>
  <state>1</state>
  <id_category_default>2</id_category_default>
  <active>1</active>
  <advanced_stock_management>1</advanced_stock_management>
  <associations>
    <categories>
      <category><id>2</id></category>
    </categories>
  </associations>
  <reference>test</reference>
  <name>
  <language id="1">webservice</language></name>
  <price>100</price>
  <id_shop_default>1</id_shop_default>
  <low_stock_alert>0</low_stock_alert>
</product>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
var_dump($xml->asXML());
$opt = array( 'resource' => 'products' );
$opt['postXml'] = $xml->asXML();
//$opt['id_shop'] = 'all';
$xml = $webService->add( $opt );
```
But, I did not manage to reproduce the issue.
I attached a video record.
https://drive.google.com/file/d/1VwTPKCdTyX78aLFtX1B-g524eUDTwh4L/view
Thanks to check & feedback.

**Comment by rGaillard** [comment] 2019-02-27 15:26
@khouloudbelguith Thank you for your answer!

The problem occurs when there is concurrency requests, to reproduce you can launch your script multiple time in // or use pcntl_fork.

**Comment by rGaillard** [comment] 2019-02-27 15:31
@khouloudbelguith we will have more than 100K products to synchronize with the webservices this is why we have to make concurrency requests.

**Comment by rGaillard** [comment] 2019-02-27 16:07
@khouloudbelguith you can also reproduce using nodejs:
var PS = require('prestan');
var api = new PS('http://domain', 'KEY, {debug: true});

var product = {prestashop: {product:{
                        price:100,
                        name: 'test',
                        low_stock_alert: 0,
                        active:1,
                        id_category_default:2
                    }
                }
};

for (var i = 0; i < 100; i++) {
api.add('products', product);
}

**Comment by khouloudbelguith** [comment] 2019-02-27 16:36
@rGaillard, thanks!

If I add this line code 

```
for ($i = 1; $i <= 10; $i++) {
    $xml = $webService->add( $opt );
}
```
to my previous script, cannot help me to reproduce the issue, is it?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-27 17:27
@rGaillard, I used also, the runner in Postman & it is OK.
I attached a video record.
https://drive.google.com/file/d/1ZlS8cSKexdkvzSwpB4Eg1EZQRP3pUnEq/view
Thanks!

**Comment by rGaillard** [comment] 2019-02-28 10:02
@khouloudbelguith the Postman runner is sending the requests sequentially and not concurrency. I have make more tests on my side and i reproduce the bug on the 1.6 version (from the 1.6.1.0) with the same setup (working well with faster HD).
@jocel1 you have introduce the on duplicate key here: https://github.com/PrestaShop/PrestaShop/commit/337a5e94f4a366bce828d948a3647e203cb7a5c2#diff-6a810cff1b3b082a1b2a3f1dbca30eee do you think that i can remove it without risks? (working well without)

**Comment by khouloudbelguith** [comment] 2019-03-01 09:47
Hi @rGaillard,

I created a bash script start_dev.sh
```
#!/usr/bin/env bash

php CreateProduct.php &
php CreateProduct.php &
php CreateProduct.php
```
then, I run this command `./start_dev.sh`, then 3 products are created concurrenctly without errors.
What do you think?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-01 08:26
Hi @rGaillard,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-01 08:26 UTC
Labels: WS, No change required, 1.7.5.1
