### ISSUE TITLE
Hundred of queries on ps_address table

### ISSUE THREAD

**Issue by augustomurri** [PrestaShop/PrestaShop#28728] opened 2022-06-10 17:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I get hundred of queries like this on all pages when logged in .. 
I tried to apply this changes manually but doesn't solve the problem 
[https://github.com/PrestaShop/PrestaShop/pull/28232/files/a54fb55a7395a61ad5989b956acbf5c0e0542b38](https://github.com/PrestaShop/PrestaShop/pull/28232/files/a54fb55a7395a61ad5989b956acbf5c0e0542b38)

```
SELECT SQL_NO_CACHE `id_address`
FROM ps_address a
WHERE a.`id_address` = 127887 LIMIT 1
```

![image](https://user-images.githubusercontent.com/16515870/173116023-d83f9f07-db03-4c3f-add3-dd40f6da78fa.png)

### Expected behavior

one singular query to get all user address

### Steps to reproduce

- Login
- Add one product to the cart
- Activate Profiler
- Check on "Doubles" section

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by matks** [comment] 2022-06-10 20:42
@augustomurri is it the same problem as https://github.com/PrestaShop/PrestaShop/issues/26754 ?

**Comment by augustomurri** [comment] 2022-06-11 14:46
I don't know exactly if is the same bug, but fix [#28232](https://github.com/PrestaShop/PrestaShop/pull/28232/commits/a54fb55a7395a61ad5989b956acbf5c0e0542b38) doesn't fix the bug

The problem is not related to any module, i have disabled and make many tests before now.

You can see the website in Profile mode active [here](https://nuovo.tsunaminutrition.it/) but **you need to register or social login  AND some products to basket**

I wrote also here [here](https://github.com/PrestaShop/PrestaShop/issues/26754#issuecomment-1152941414)

**Comment by augustomurri** [comment] 2022-06-11 15:30
This a fresh installation PS 1.7.8.6 and PHP7.4
with default theme, no third part modules

1. register and login
2. add one or more address in your customer area
3. add one or more product to the basket

![image](https://user-images.githubusercontent.com/16515870/173194303-8bd40eb4-8108-4d4c-9806-b53d1a861aba.png)

**Comment by AureRita** [comment] 2022-06-13 15:07
HI @augustomurri  ,

We are aware of this issue, it is already in our debug backlog. As you can see with @matks this issue is a duplicate of #28232 .
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by AureRita** [comment] 2022-06-13 15:08
Duplicate of #28232

**Closed as completed** 2022-06-13 15:07 UTC
Labels: Bug, Duplicate, Invalid
