### ISSUE TITLE
Missing translation: Unit discount from ShopThemeCatalog 

### ISSUE THREAD

**Issue by Flower7C3** [PrestaShop/PrestaShop#22342] opened 2020-12-10 15:42 UTC
#### Describe the bug

Value **Unit discount** from **ShopThemeCatalog** domain is missing for some languages in https://github.com/PrestaShop/TranslationFiles/ files.

#### Expected behavior

Translate string **Unit discount** declared in https://github.com/PrestaShop/PrestaShop/blob/939b866b5ef6060d034a3838adfc77ce6fba7e43/app/Resources/translations/default/ShopThemeCatalog.xlf#L3-L16
in __ShopThemeCatalog.*.xlf__ files https://github.com/PrestaShop/TranslationFiles/ repository.

#### Steps to Reproduce

Try to find **Unit discount** in https://github.com/PrestaShop/TranslationFiles/ repository. Eg:

- https://github.com/PrestaShop/TranslationFiles/blob/a4b6f1152e27b11baae65c362159afc4b2b2050b/1.7/translations/1.7.7/pl-PL/ShopThemeCatalog.pl-PL.xlf#L3-L10

**Screenshots**

![image](https://user-images.githubusercontent.com/3767861/101799122-10a7a280-3b0c-11eb-8065-84c3334a3799.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2020-12-10 16:13
Hello @Flower7C3 

Could you please edit your issue, cause we need these sections (Expected behavior, Steps to Reproduce, Additional information) to reproduce your issue as soon as possible.

We create this template to make it easy for you and for us to handle the issue :smile: 

Thanks

**Comment by Flower7C3** [comment] 2020-12-10 16:31
@hibatallahAouadni I have just updated issue description.

**Comment by hibatallahAouadni** [comment] 2020-12-14 10:22
Hello @Flower7C3 

It's not a bug :sweat_smile: it's just missing translations, in Arabic language, this word is also not translated, see the attached screen record below:

https://drive.google.com/file/d/1OjetSPK8z5pTzCFatLrKBKHXo-n8DHMc/view

1. Go to **BO** > **IMPROVE** > **International** > **Translations**
2. In the block **Modify translations**, choose **Themes translations** as **Type of translation**, then choose your theme and select your language, click on **Modify** button.
3. Make a search for the missing word **Unit discount** and then add your translation, see the attached screen record below:
https://drive.google.com/file/d/1bpUeWUL6JEnroyW4zc1KagDjhxat63wt/view
4. **FO** > check the product again, see the attached screen record below: 
https://drive.google.com/file/d/1LkTHp9IBe1AoLTMF70muWOXTyGAJ7vB7/view

So, I close this issue :wink: 
Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-14 10:22 UTC
Labels: Bug, BO, Translations, No change required, 1.7.7.0

**Comment by Flower7C3** [comment] 2020-12-14 10:32
Sorry, I am unable to find this translation in BO:
![image](https://user-images.githubusercontent.com/3767861/102070866-01706f80-3e00-11eb-8380-7d037c844a5b.png)

**Comment by hibatallahAouadni** [comment] 2020-12-14 15:48
Hello @Flower7C3 

DO you have another theme installed? By the way, what's your language?

Thanks!

**Comment by Flower7C3** [comment] 2020-12-15 09:20
I have another theme, but this one is sop default theme. I am using Polish language version.
