### ISSUE TITLE
Strange behavior of the combinations not all of them are displayed correctly

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#25073] opened 2021-06-22 07:44 UTC
Hello everybody,
I noticed that creating one combination at a time, merging more attributes for each combination, on the front end the combinations are not shown all as expected.
I perform the necessary steps to reproduce the problem:
1) I create a new product

<img width="635" alt="Schermata 2021-06-22 alle 08 45 47" src="https://user-images.githubusercontent.com/28685316/122876951-5f918880-d336-11eb-923d-e985af9b0b8b.png">

2) I choose the combinations

<img width="1163" alt="Schermata 2021-06-22 alle 08 44 37" src="https://user-images.githubusercontent.com/28685316/122877063-7afc9380-d336-11eb-959c-1bb95dce29ab.png">

3) I access the combinations tab and start to create them:
<img width="1113" alt="Schermata 2021-06-22 alle 08 49 27" src="https://user-images.githubusercontent.com/28685316/122877390-d9c20d00-d336-11eb-8989-7db582b4a611.png">

3.1) I create the first combination by combining 3 attributes
Attribute **a+b+c** (size+color+combination) then I generate it (**e**)
<img width="1146" alt="Schermata 2021-06-22 alle 08 36 03" src="https://user-images.githubusercontent.com/28685316/122877869-5fde5380-d337-11eb-876e-2f58453b3575.png">

3.2) I create the second combination by combining three other attributes
<img width="1132" alt="Schermata 2021-06-22 alle 08 36 32" src="https://user-images.githubusercontent.com/28685316/122878205-c3688100-d337-11eb-96fe-51e87824678e.png">

3.3) I create the second combination by combining 3 other attributes
<img width="1141" alt="Schermata 2021-06-22 alle 08 36 48" src="https://user-images.githubusercontent.com/28685316/122878241-d11e0680-d337-11eb-9bc7-da459108c44c.png">

4) I check that the combinations have been created, I enter the price impact, the quantity, I access each combination to enter the reference and any other information such as EAN, impact weight etc ...

<img width="1148" alt="Schermata 2021-06-22 alle 08 58 24" src="https://user-images.githubusercontent.com/28685316/122880213-10e5ed80-d33a-11eb-820a-902254781aa3.png">

5) Save and check in front end, the screenshot shows the first combination set correctly, the second and third not.

<img width="912" alt="Schermata 2021-06-22 alle 09 16 17" src="https://user-images.githubusercontent.com/28685316/122881064-0546f680-d33b-11eb-897c-1202f8a4f4b0.png">

I'm waiting your kind response.
Balla

PS version: 1.7.6.3
PHP version: 7.2.x

**Comment by florine2623** [comment] 2021-06-22 08:22
Hello @ballashop ,

Your issue is related to : https://github.com/PrestaShop/PrestaShop/issues/22661
Can you confirm it is a duplicate ?

Thanks.

**Comment by ballashop** [comment] 2021-06-22 09:31
Hi @florine2623 
thanks to replied to me.
I think is similarity, but I do not understand if the #22661 issue the attributes have been created, the images do not show well.
for completeness of information, we use a module that allows us to see in the table the variants with the buy button, in the table the visualization is ok:

<img width="1050" alt="Schermata 2021-06-22 alle 09 40 28" src="https://user-images.githubusercontent.com/28685316/122899346-0af90800-d34c-11eb-8d32-dd3b4a48076c.png">

If instead I add all the attributes together to create the combinations, the system rightly creates 27 to match the 3 attributes.
![localhost - 720](https://user-images.githubusercontent.com/28685316/122900298-d9347100-d34c-11eb-98fc-8acee4e9fe5b.png)

this is then the result in the front end:
<img width="796" alt="Schermata 2021-06-22 alle 11 28 40" src="https://user-images.githubusercontent.com/28685316/122900563-1862c200-d34d-11eb-828e-8e71b4d19982.png">

but this is not the result we are looking for, we need to combine multiple attributes together, and PrestaShop allows us to do that, so I thought it was a case allowed by the system.
Thanks for any reply.
Balla

**Comment by florine2623** [comment] 2021-06-22 13:39
Hello @ballashop ,

Thanks for confirming it is similar.
I suggest following directly the progress of the issue on  #22661

As you can see there's already a fix available through the PR.
So i close your issue.
Thanks!

**Comment by florine2623** [comment] 2021-06-22 13:39
Duplicate of  #22661

**Closed as completed by florine2623** 2021-06-22 13:39 UTC
Labels: Bug, BO, Duplicate, Combinations, 1.7.6.3
