### ISSUE TITLE
product_mini images not generated

### ISSUE THREAD

**Issue by ADM777** [PrestaShop/PrestaShop#32862] opened 2023-06-08 05:30 UTC
### Describe the bug

product_mini images not generated
![product_mini_10047 1](https://github.com/PrestaShop/PrestaShop/assets/41301917/8264e4ad-5016-45e8-97bd-aa822a974f3f)

### Steps to reproduce

1. .....
2. ...
3. ....

### Additional infos

- PS version: 1.7.7.8
- PHP version: 7.3

_Originally posted by @ADM777 in https://github.com/PrestaShop/PrestaShop/pull/24394#pullrequestreview-1435030892_

**Comment by hibatallahAouadni** [comment] 2023-06-09 08:06
Hello @ADM777 

I see that you created this issue from your comment in the related PR. But could you please edit your issue description and provide more infos to help us reproducing the issue 🙏 
Otherwise, your comment made me think of this issue #21731 whose fixed with PS1770.
Could you please check it and feedback, and don't forget to edit your description 🙏 

Thanks!

**Comment by florine2623** [comment] 2023-06-20 09:06
Hello @ADM777 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-06-20 09:06 UTC
Labels: Bug, BO, Image, Invalid, 8.0.0
