### ISSUE TITLE
With new switch design if form doesn't have default value for switch input it will not be visible until you click on it.

### ISSUE THREAD

**Issue by JevgenijVisockij** [PrestaShop/PrestaShop#21922] opened 2020-11-15 09:22 UTC
#### Describe the bug

The new switch button design relies on value to be checked. If none of the values are checked the button will not be visible until you click on it(thus making one of the values checked). One example is Add new Currency. 
My suggested solution is to either change CSS so there is a fallback in case of neither value being selected or modify switch type so even if no default value is provided it will default to false.

#### Expected behavior

Switch button should always be visible.

#### Steps to Reproduce
1. Go to Currency page
2. Click add new currency
3. Status button is invisible

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/47781757/99181072-c9103f80-2734-11eb-898f-fac2e0eccc2f.png)

#### Additional information

* PrestaShop version: newest develop branch (1.7.8.0).
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2020-11-16 08:32
Hello @JevgenijVisockij 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #21842. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: there's Epic about the UI-KIT bugs #21832 

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-16 08:33
Duplicate of #21842

**Closed as completed by hibatallahAouadni** 2020-11-16 08:32 UTC
Labels: Duplicate
