### ISSUE TITLE
Menu not showing during order process

### ISSUE THREAD

**Issue by Digit-89** [PrestaShop/PrestaShop#11426] opened 2018-11-17 14:35 UTC
**Describe the bug**
Main menu not showing during order process.

**To Reproduce**
1. Go to the official demo : http://fo.demo.prestashop.com/en/order
2. If needed put something in the cart and proceed to checkout

**Screenshots**
http://www.mediafire.com/view/wudz2tyaaqnkyn6/Capture.PNG

**Additionnal information**
PrestaShop version: 1.7.4.4 non modified

**Comment by psydomin** [comment] 2018-11-17 14:52
I strongly believe that that is the intended behaviour. The objective is to remove any distraction while checking out and increase the conversion rate.

**Comment by Rolige** [comment] 2018-11-17 17:25
As @psydomin said, this is not an error, it's done so with the purpose of removing all distractions from the checkout process, keeping only the essentials.

Regards!

**Comment by khouloudbelguith** [comment] 2018-11-19 08:25
Hi @Digit-89,

The design of the checkout page in PrestaShop 1.7 is different from other pages, it does not have footer, just a logo in its header. It is an improvement to let customers do nothing, but checkout.

To make the checkout page have the same header and footer as other pages, you need to edit the `\themes\your-theme\templates\checkout\checkout.tpl` file.

1. Replace this code

`{include file=’checkout/_partials/header.tpl’}`
by this one

`{include file=’_partials/header.tpl’}`

2. Replace this code

`{include file=’checkout/_partials/footer.tpl’}`
by this one

`{include file=’_partials/footer.tpl’}`
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-19 08:25 UTC
Labels: No change required
