### ISSUE TITLE
email's subject for admin in wrong language

### ISSUE THREAD

**Issue by dolmenhir** [PrestaShop/PrestaShop#27964] opened 2022-03-18 11:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm working in french language.
At least two emails subject are sended in wrong language:
- "New order" instead "Nouvelle commande"
- "Product out of stock" instead "Produit en rupture de stock" (sended by emailalerts module)
![PS-issue-emails-subject](https://user-images.githubusercontent.com/32955440/158997201-c834500d-9774-4fe1-8c0c-fb473d3ee2d6.jpg)

### Steps to reproduce

1. use french language
2. install and activate emailalerts module
3. valid a command to get email "New order"
4. or open a product out of stock to get email "Product out of stock"

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4.28

### If your bug is related to a module, specify its name and its version

emailalerts 2.3.3

**Comment by HanaRebaiQA** [comment] 2022-03-18 14:27
Hello @dolmenhir 

Thanks for you report.
I was able to reproduce your issue with PS1778 & PS1784 
![image](https://user-images.githubusercontent.com/92912932/159021040-b3b5e057-e4e7-4a3b-9594-1adf8a113ca5.png)

![image](https://user-images.githubusercontent.com/92912932/159020952-5f87fbe6-4124-4ce2-b541-613105c7d18d.png)

It's related to this one [#17810](https://github.com/PrestaShop/PrestaShop/issues/17810)  ?

Thank you!

**Comment by dolmenhir** [comment] 2022-03-18 16:06
Hi Hana,
Yes, related to #17810 for some sentences.
Others are there as "not mail alert yet" in French.
![PS-no-alert-yet](https://user-images.githubusercontent.com/32955440/159038688-c7f8b474-0e99-4c22-a8a0-57c04309006c.jpg)

**Comment by hibatallahAouadni** [comment] 2022-03-21 13:59
Hello @dolmenhir 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17810. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-21 13:59
Duplicate of #17810

**Closed as completed by hibatallahAouadni** 2022-03-21 13:59 UTC
Labels: Bug, BO, Duplicate, Translations, ps_emailalerts, 1.7.7.8, Invalid, Module
