### ISSUE TITLE
Different sql table prefix in one hook hookActionCustomerGridQueryBuilderModifier

### ISSUE THREAD

**Issue by scorp1czech** [PrestaShop/PrestaShop#26889] opened 2021-12-06 13:45 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In hook hookActionCustomerGridQueryBuilderModifier when i add joined table, it has error, because in CustomerList view is joined customer table with alias c.id_customer, but in CustomerDetail has alias customer.id_customer, here code crashed. I have now fixed with my issue, but not elegance.
My instance in public function hookActionCustomerGridQueryBuilderModifier(array $params) in my module
`		foreach ($searchCriteria as $key => $val) {
			if ($key == 'filters') {
				if (!empty($val)) {
					$has_filter = true;
				}
			}
		}
		if ($has_filter) {
			$searchQueryBuilder->addSelect(
				'IF(customer.promo_code IS NULL,0,customer.promo_code) AS promo_code'
			);
		} else {
			$searchQueryBuilder->addSelect(
				'IF(c.promo_code IS NULL,0,c.promo_code) AS promo_code'
			);
		}
`
It's not ideal, but solve it my problem. Please, do you can unite aliases of tables in joins, maybe only from importants as orders, customers, carts etc.

### Steps to reproduce

In module use public function hookActionCustomerGridQueryBuilderModifier(array $params) function and use reading from SQL customer table with alias, extend by some columns. 

In different views Customer, CustomerDetail are different alias for customer table in sql query.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2021-12-06 17:00
Hello @scorpio-angel 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23394. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-06 17:00
Duplicate of #23394

**Closed as completed by hibatallahAouadni** 2021-12-06 17:00 UTC
Labels: Bug, Duplicate, Invalid
