### ISSUE TITLE
cant update any module and traduccions

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#27796] opened 2022-02-25 14:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If I update any prestashop module it tells me that it has been updated correctly, but when refreshing page or going to any other it continues to appear to update, same whit translates

Video: https://youtu.be/IYOpSAOxtio

### Expected behavior

Click in update and the module get updated and the translates get updates

### Steps to reproduce

1. Go to modules
2. Click in updates
3. whait for update
4. resfresh
5. see the update dont get complete
6. go to translate opcion
7. translate any string
8. save
9. see the translate dont update

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

EDIT: if desactivate apcu php get updates ¿is a posible bug whit apcu?
EDIT2: The translations dont work

**Comment by khouloudbelguith** [comment] 2022-02-25 15:04
Hi @LinkOfLight,

I did not manage to reproduce the issue with PS1783
**Apcu not installed**

https://user-images.githubusercontent.com/16067358/155737837-8141c6cf-7a07-481a-a6f8-4745704425bc.mp4

**Apcu installed**

https://user-images.githubusercontent.com/16067358/155737870-52990578-ff48-4c02-9b78-8260ad0ea8da.mp4


I used also PHP7.4

Thanks to check and feedback

**Comment by hibatallahAouadni** [comment] 2022-03-14 10:14
Hello @LinkOfLight 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module/configuration/overrides problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-03-14 10:14 UTC
Labels: Bug, BO, Modules, Translations, Module manager, Invalid, Module, 1.7.8.3
