### ISSUE TITLE
Trying to access array offset on value of type bool classes/Product.php, line 7170

### ISSUE THREAD

**Issue by riess82** [PrestaShop/PrestaShop#29402] opened 2022-08-21 13:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Adding a product over the api, I get an error 500 returned. The product is created in prestashop, but obviously something had gone wrong.

The php log shows:
[Sun Aug 21 14:37:08.542363 2022] [proxy_fcgi:error] [pid 2004:tid 139638236767808] [client IP_REMOVED:45452] AH01071: Got error 'PHP message: [PHP Notice #8] Trying to access array offset on value of type bool (/var/www/clients/client439/web395/web/katalog2/classes/Product.php, line 7170)'

I searched the web for possible solutions and found https://stackoverflow.com/questions/66867369/prestashop-error-trying-to-access-array-offset-on-value-of-type-bool

I have changed the code as suggested and the error disappears.

I will search my database now for "broken" products before trying to figure out what caused the error in the first place.

### Steps to reproduce

"POST" to API

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by PrestaEdit** [comment] 2022-08-21 16:57
Hi @riess82,

Thanks for your issue.

@QA-team : it's solved into the develop branch (https://github.com/PrestaShop/PrestaShop/pull/28280) ; as the 1.7.8.x is 7.4 compliant, don't we need to do a backport of it onto this branch ?

**Comment by hibatallahAouadni** [comment] 2022-08-22 09:21
Hello @riess82 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26559. 
It's fixed on 8.0.0 (next major release), please subscribe to the issue mentioned above.

PS: @PrestaEdit as this issue isn't a regression, that's why we fixed it on 8.0.0 :slightly_smiling_face: but let's check with the Maintainer Team, if we can backport it to 1.7.8.x branch :wink: 

Ping @PrestaShop/prestashop-maintainers wdyt of @PrestaEdit suggestion? should we backport this PR #28280 to 1.7.8.x?

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-22 09:21
Duplicate of #26559

**Closed as completed by hibatallahAouadni** 2022-08-22 09:21 UTC
Labels: Bug, Duplicate, Invalid
