### ISSUE TITLE
Error - Unclear alert when adding keywords with max length > 255 chars or an invalid Friendly URL to a category

### ISSUE THREAD

**Issue by nicoladze** [PrestaShop/PrestaShop#16514] opened 2019-11-23 15:48 UTC
**Describe the bug**
I encounter an error when I add a new keyword to an old category (but not everytime... and there is no error on debug mode)
 
**To Reproduce**
**Case1:**
1. Go to Catalog -> Category
2. Click on Modify on a category already created and fulfilled while you were on PS 1.7.2.4
3. Scroll down to "Keywords"
4. Add new keywords  with max length > 255 chars
5. Save
6. See error : "Une erreur inattendue s'est produite. [PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryException code 0]"

**Case2:**
1. Check that the Accented URL is disabled
2. Create a new category with an invalid Friendly URL for `example child.1`
3. see error

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![Error](https://user-images.githubusercontent.com/47031957/69481334-a9d81e00-0e10-11ea-87f5-630bfb9fbc9e.png)

**Additional information**
PrestaShop version: 1.7.6.1

Server :
Informations sur votre serveur Linux #1 SMP Wed May 15 10:40:34 CEST 2019 x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.0.33
Limite de mémoire : 512M
Temps maximal d'exécution : 300
Taille max. pour envoi de fichiers : 128M

**Comment by khouloudbelguith** [comment] 2019-11-25 08:10
Hi @nicoladze,

I did not manage to reproduce the issue with PS1.7.6.1 after an upgrade from PS1.7.2.4 using the 1-click upgrade v4.9.0.
I attached  screen record
https://drive.google.com/file/d/1Ej7tSADUVrIdLcH51XIEFt97jbb7bOnO/view
Thanks to check & feedback.

**Comment by nicoladze** [comment] 2019-11-25 12:29
@khouloudbelguith 

Yes, I know; even in my case, it does not occur everytime.

Do you know what kind of error it means : [PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryException code 0]

**Comment by khouloudbelguith** [comment] 2019-11-25 14:39
@nicoladze, I think the issue is related to the Friendly URL of your category.
In your BO => Shop Parameters => Traffic & SEO page => Try to enable "Accented URL" => save & now check again the category.

Thanks!

**Comment by nicoladze** [comment] 2019-11-25 15:11
@khouloudbelguith 

I did what you have suggested but the error is still occuring.
And just for you to know, there was no accent in my URL.

Is that coming from too much meta keywords? 

42 keywords, total letters : 286

(And now, I have another one : "Une erreur inattendue s'est produite. [Symfony\Component\Debug\Exception\ContextErrorException code 0]"

But for that one, I disabled the Debug mode, and it was fixed)

**Comment by khouloudbelguith** [comment] 2019-11-25 15:40
@nicoladze, thanks for these clarifications.
Yes, you are right.
When we create a category with Meta keywords with max length > 255 chars, we have this alert => not clear( reproduced with PS1.7.6.1 & PS1.7.6.2build1 & develop)
![image](https://user-images.githubusercontent.com/16067358/69553856-1eda5d80-0fa1-11ea-9b10-76a4642e0d32.png)

It was ok with PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/69553811-08340680-0fa1-11ea-946e-44274d5a8f50.png)

Same issue when Accented URL is disabled & we try to create a category with invalid friendly URL(`child.1`) ( reproduced with PS1.7.6.1 & PS1.7.6.2build1 & develop)
![image](https://user-images.githubusercontent.com/16067358/69554378-0159c380-0fa2-11ea-8244-838445a5e27e.png)

It was ok with PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/69554417-0e76b280-0fa2-11ea-82df-0901b9559573.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by nicoladze** [comment] 2019-11-25 15:44
@khouloudbelguith 

Is there a way in the BO to enlarge the size limitation (like for a description in a product sheet)?

**Comment by khouloudbelguith** [comment] 2019-11-25 15:52
@nicoladze, in this line: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Category.php#L130
You can change `255` by your desired value.

Thanks!

**Comment by nicoladze** [comment] 2019-11-25 15:53
@khouloudbelguith 

Thanks a lot

**Comment by khouloudbelguith** [comment] 2019-11-26 13:50
Same issue with PS1.7.6.0
![image](https://user-images.githubusercontent.com/16067358/69638954-fd8a7780-105b-11ea-8fb2-b967d2f12acc.png)

Thanks!

**Comment by Progi1984** [comment] 2020-01-10 15:53
Fixed in #17087

**Closed as completed** 2020-01-10 15:52 UTC
Labels: Bug, Minor, BO, Categories, Regression, Fixed, migration, 1.7.6.0, 1.7.6.1, PR available
