### ISSUE TITLE
Upgrade and new install use different software

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#34799] opened 2023-12-09 16:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I did an upgrade to PS 8.1.2 and a fresh installation.

The software is different in the file /classes/Context.php

In the upgrade this starts with 
`if (null !== $this->translator && $this->language->locale === $this->translator->getLocale()) {
            return $this->translator;
        }`

In the new installation that code is outcommented.

### Expected behavior

software in new installations and upgrade is the same

### Steps to reproduce

Install and upgrade

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment] 2023-12-11 15:54
Hello @musicpanda,

I don't really understand your problem, could you detail the problem a little more as well as the steps to reproduce?

Thanks for your feedback!

**Comment by musicpanda** [comment] 2023-12-11 16:24
Sorry Paul, I doubt I can take you seriously after you closed my other post. For me you are one of the nerd ideologues who are destroying Prestashop since its organization has split.

It looks like a deletion of linefeeds in a Windows-to-Linux copy had blurred the situation.
Anyway, here is the same thing in an image:
![dddd](https://github.com/PrestaShop/PrestaShop/assets/13930107/e6151cc4-81c2-4579-8485-e78ae00f3626)

**Comment by paulnoelcholot** [comment] 2023-12-12 09:16
Hello @musicpanda,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #34385
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by fabienvallon** [comment] 2023-12-12 10:47
Hi @musicpanda  

I think you wrong. 
The main problem is people who talking a lot without contributing ( PretaShop is an OpenSource software) 

Talk is Cheap , show me the code (TM Linus Torvalds) 


I don't really like (at all) the way you are talking to @paulnoelcholot .
I think you need times to read again [our code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)

**Comment by kpodemski** [comment] 2023-12-12 11:04
@paulnoelcholot This is not the same issue

@musicpanda I'm sorry, but you have to calm down, also, please do report whether you are using PrestaShop Classic or the version downloaded from GitHub, otherwise it's hard to understand your problem fully.

**Comment by kpodemski** [comment] 2023-12-12 11:11
I can confirm this issue but it comes from the PrestaShop Classic version, it is not related to the project's release. I'll share this to the team responsible for PrestaShop Classic.

**Comment by kpodemski** [comment] 2023-12-12 14:07
I'm closing this issue since it is not related to the core available on GitHub.

**Closed as completed by kpodemski** 2023-12-12 14:07 UTC
Labels: Bug, 8.1.x

**Comment by matks** [comment] 2023-12-13 10:57
> For me you are one of the nerd ideologues who are destroying Prestashop since its organization has split.

This message is against our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/ae98a9b763aff03a0d004332865a0f87a17ca556/CODE_OF_CONDUCT.md). @musicpanda you have repeatedly been speaking harsh to project members, in this issue and in others ([example](https://github.com/PrestaShop/PrestaShop/issues/22819#issuecomment-767535198) in 2021) and consequently it was decided to ban you from this GitHub area for 2 months, starting from now.

**Comment by matks** [comment] 2024-02-13 08:25
Today is the 13th of February and the ban of @musicpanda is finished.
