### ISSUE TITLE
Updated links on PS_Linklist not visible if cache is enabled

### ISSUE THREAD

**Issue by sasa-yovanovicc** [PrestaShop/PrestaShop#29203] opened 2022-07-29 15:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If the cache is enabled (Memcache/APC) any update of links is not visible. When the cache is disabled updated links show immediately.

Prestashop v. 1.7.8.5

### Expected behavior

After edited link value (name for example) changes should be visible.

### Steps to reproduce

Login as the system adminstrator
Go to Improve > Design > Link List
Edit Resources in some widget
Click the Save button at the bottom of the page
Note the Succesful Update message indicates the update is completed
Visit a frontend

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

1.7.8.5

### If your bug is related to a module, specify its name and its version

ps_linklist v5.0.4

**Comment by hibatallahAouadni** [comment] 2022-07-29 16:49
Hello @bastijan 

I didn't manage to reproduce the issue with PS1786 :disappointed:
Could you please provide a screen record :pray: 
Waiting for your feedback!

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-19 16:48
Hello @bastijan 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-08-19 16:48 UTC
Labels: Bug, FO, Performance, Linklist, Invalid, Module
