### ISSUE TITLE
 Undefined offset  in Faceted search module

### ISSUE THREAD

**Issue by ladypixl** [PrestaShop/PrestaShop#12676] opened 2019-02-22 15:56 UTC
**Describe the bug**
I'm using Prestashop 1.7.5 with a PHP 7.2 server.
I created an attribute for my products.
When I try to filter my products by this attribute, the result list is empty (but it shouldn't), and when I disable the filter get a 500 error in the browser console.

I put the Debug mode and I've got this error :

```
ContextErrorExceptionNotice: Undefined offset: 1
in Ps_FacetedsearchFacetsURLSerializer.php line 75
```

The URL called to get this trace is this 
`http://[url-of-my-shop]/3-proteines-vegetales?q=Poids-500g&from-xhr`
where 3-proteines-vegetales is the product category
and Poids-500g the filter (attribute-value).

When I click the second time, it tries to call
`http://[url-of-my-shop]/3-proteines-vegetales?from-xhr`

And it becomes impossible to get back to the initial product list.

**To Reproduce**
I don't know if you can reproduce it with what I explained.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5
PHP version: 7.2

I installed a theme (Fami), but disabled it to be sure that the problem didn't come from it.
I also compared the code of the faceted search module with the one on Github, to be sure it hadn't been modified by the theme (because it seems that it already happened in other cases), and the code seems to be the same.

**Comment by khouloudbelguith** [comment] 2019-02-22 17:04
Hi @etasia79,

What is the exact version ps_factedsearch did you use?
Thanks!

**Comment by ladypixl** [comment] 2019-02-22 17:11
Hi @khouloudbelguith ,
it's the 2.2.1 !

**Comment by khouloudbelguith** [comment] 2019-02-25 17:30
Hi @etasia79,

I did not manage to reproduce the issue with PS1.7.5.1 & the ps_factedsearch v2.2.1.
I attached a video record.
https://drive.google.com/file/d/1IpbZX_Yy4D9bQs4UQ-Qcgra8fDGPQwur/view
Thanks to check & feedback.

**Comment by ladypixl** [comment] 2019-03-01 12:05
@khouloudbelguith ,

thanks for your feedback.
I finally completely uninstalled my shop (fortunately, there was not much on it yet), and reinstall it from scratch. And I didn't reinstall the theme because I think it had modified something in native modules...

I don't have the 500 error anymore, but the search by attributes still returns 0 results.
Everything seems well configured, as you can see in the following video:

https://www.dropbox.com/s/zervtpnd8dnf1zg/faceted_search.mp4?dl=0

- checked the versions of prestashop and php
- showed the attribute called 'poids' (weight in english)
- showed the configuration of Faceted Search
- when displaying the products list, you can see the number of items per attribute (in the filters list)
- but when clicking on one filter, it empties the list

**Comment by khouloudbelguith** [comment] 2019-03-01 13:50
@etasia79, I did not manage to reproduce the issue with PS1.7.5.1 & the ps_facetedsearch v2.2.1.
I attached a video record.
https://drive.google.com/file/d/1E0t9RQT9KwfSCj11yDe7EfMXIzfunvUR/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by ladypixl** [comment] 2019-03-01 14:11
I enabled the debug mode in prestashop but the search doesn't generate no error anymore.
And in the logs I can't see what SQL request is generated (I looked in public_html/var/logs : maybe it's not the right place ?).

**Comment by khouloudbelguith** [comment] 2019-03-01 14:49
@etasia79,

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ladypixl** [comment] 2019-03-01 15:12
@khouloudbelguith ,
that's what I've done : enabled the debug mode and looking in var/logs (the same as written in the page you linked).
Unfortunately it doesn't log nothing except the SQL requests for the translations.

**Comment by khouloudbelguith** [comment] 2019-03-01 16:31
@etasia79, I found the exact error.
the module doesn't show results of combinations out of stock.
Your ticket is a duplicate of #12143
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-01 16:31
Duplicate of #12143

**Closed as completed by khouloudbelguith** 2019-03-01 16:31 UTC
Labels: Duplicate, Faceted search, 1.7.5.0
