### ISSUE TITLE
Unable to Edit Products on PS 1.7.1.2 ( Unexpected token < in JSON at position 0 )

### ISSUE THREAD

**Issue by MartynMcOnie** [PrestaShop/PrestaShop#13800] opened 2019-05-15 13:34 UTC
**Describe the bug**
When trying to edit any product on our website, we get an error 'unable to save settings' and in the console log of the browser the error: 
`Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.de.parseJSON (bundle.js:4)
    at Object.error (form.js?1.7.0:906)
    at l (bundle.js:3)
    at Object.fireWith [as rejectWith] (bundle.js:3)
    at n (bundle.js:4)
    at XMLHttpRequest.<anonymous> (bundle.js:4)`

and

`bundle.js:4 POST https://www.gardensleepersexpress.co.uk/admin699rdmeyz/index.php/product/form/23?_token=StxC3eEfjo33Fh7KWGJBnnrFoz2dRveW5lWBqVuQph8 404 (Not Found)`

I am not a programmer so I need all the help I can get, but this is essentially a worst case senarior for us as we need to change pricing on products and are currently unable to.

**Additionnal information**
PrestaShop version: 1.7.1.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-05-15 13:57
Hi @MartynMcOnie,

I did not manage to reproduce the issue with PS1.7.5.2, PS1.7.6.0beta1 & PS1.7.1.2.
I attached a video record
https://drive.google.com/file/d/1D8FQs6ZWH6xq7HwoPA864vy1htIVt5fQ/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-14 08:02
Hi @MartynMcOnie,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-14 08:02 UTC
Labels: Bug, BO, No change required
