### ISSUE TITLE
javascript prestashop.cart goes undefined after quantity update

### ISSUE THREAD

**Issue by syffs** [PrestaShop/PrestaShop#20550] opened 2020-08-12 07:19 UTC
#### Describe the bug

javascript `prestashop.cart` goes undefined after quantity update from cart.

#### Expected behavior

`prestashop.cart` should update according to cart content on cart update.

#### Steps to Reproduce

1. Go to any prestashop 1.7.6.3 shop (I haven't tested below, which doesn't mean it's working)
2. Add a product to cart
3. From cart, with devtools check the content of `prestashop.cart`. It should be well defined
4. Increase your product quantity and wait for cart refresh
5. check the content of `prestashop.cart` again, it's now undefined

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-08-12 07:48
Hi @syffs,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17074 to fix the issue.
Your ticket is a duplicate of #16665
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-12 07:48
Duplicate of #16665

**Closed as completed by khouloudbelguith** 2020-08-12 07:48 UTC
Labels: Duplicate
