### ISSUE TITLE
1-click upgrade with 1.6 doesn't function

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33115] opened 2023-07-05 12:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you want to upgrade PS 1.6.1.24 one of the requirements that you see is that the upgrade module should be upgraded to the latest version. When you click to do so the module is upgraded to version 4.14.2. This is also the version that is offered to you when you download it on addons and you tell the system that you are on 1.6.

However, the requirements section of the module keeps telling you that you are not on the latest version. So de facto upgrading is impossible.

### Expected behavior

See above

### Steps to reproduce

See above

### PrestaShop version(s) where the bug happened

1.6.1.24

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by florine2623** [comment] 2023-07-05 13:57
Hello @musicpanda ,

I reproduced the same issue as you :

https://github.com/PrestaShop/PrestaShop/assets/16019289/bcfeb041-143c-4ab0-8f6c-18d1cf6031db

FYI @MatShir

**Comment by kpodemski** [comment] 2023-07-05 16:36
Hi @musicpanda 

Have you considered using some migration script instead of autoupgrade? :) I did some upgrades from 1.6 to 8.0, and now I'm not sure if it's worth it.

**Comment by musicpanda** [comment] 2023-07-07 17:55
> Hi @musicpanda
> 
> Have you considered using some migration script instead of autoupgrade? :) I did some upgrades from 1.6 to 8.0, and now I'm not sure if it's worth it.

You are right that autoupgrade has its problems. But I don't think that is a reason to stop bugging Prestashop to get its act straight. 

When I upgrade a fresh 1.6.1.24 to 1.7.0.6 under PHP 7.4 (those were at hand) I get the following error:

> [INTERNAL] \modules\autoupgrade\upgrade\php\migrate_tabs_17.php line 61 - Error: Call to undefined method ProfileCore::resetCacheAccesses() #0 [internal function]: migrate_tabs_17() #1


BTW: I could upgrade by manually changing the version number of my autoupgrade module from 4.14.2 to 4.16.2.

**Comment by kpodemski** [comment] 2023-07-08 09:50
> You are right that autoupgrade has its problems. But I don't think that is a reason to stop bugging Prestashop to get its act straight.

I'm unsure about that, honestly. Most people I know used a third-party tool to migrate. Why would we invest a lot of time to make those upgrades available now after all these years? We know it's difficult for a technical person to upgrade, for a regular user, it's almost impossible, given how many tasks in the middle there are.

I'm just not sure if it's with spending extra time on it where we could improve the module for 1.7+.

**Comment by musicpanda** [comment] 2023-07-08 20:59
> > You are right that autoupgrade has its problems. But I don't think that is a reason to stop bugging Prestashop to get its act straight.
> 
> I'm unsure about that, honestly. Most people I know used a third-party tool to migrate. Why would we invest a lot of time to make those upgrades available now after all these years? We know it's difficult for a technical person to upgrade, for a regular user, it's almost impossible, given how many tasks in the middle there are.
> 
> I'm just not sure if it's with spending extra time on it where we could improve the module for 1.7+.

If that is the type of thinking of the Prestashop leadership then Prestashop is doomed. If you don't have your basic functions ok then nobody is going to trust you for more advanced functionality

**Comment by matks** [comment] 2023-07-10 07:35
> If that is the type of thinking of the Prestashop leadership then Prestashop is doomed. If you don't have your basic functions ok then nobody is going to trust you for more advanced functionality

What @kpodemski said makes sense.

It's 2023. I think most of 1.6 users who wanted to upgrade to 1.7 and could do it easily have done it since a long time now. What remains are either users unwilling to upgrade or users who have such a complex setup* that the open source upgrade module won't work (as mentioned there are some nice third-party tools that handle these particuliers setups well).

*Heavy customizations, very large catalogs, large number of modules, altered database schema...

I expect you're going to say that my opinion means PrestaShop is doomed, but people have been telling me this for 5 years now and the PrestaShop project is still kicking 😁 .

This was just my opinion, that does not mean this bug will not be fixed (the upgrade module can still be useful for some 1.6 users).

**Comment by testing-nerd** [comment] 2023-07-10 09:55
It's 2023. I think most of the 1.6 users who wanted to upgrade to 1.7 and **could do it easily** have done it since a long time now.

Easily? For your information, the official auto-upgrade module never worked to upgrade from 1.6 to 1.7. It was never easy to upgrade from 1.6 to 1.7, and it's still the same, you need a third-party module to upgrade.

All shops were running on 1.6 before the 1.7 version was introduced, so why did you not invest your time to make a good upgrade module to EASILY upgrade from 1.6 to 1.7 before launching it? If a third-party module can do it, then why it can't be done by the official module? It's really a shame.

**Comment by kpodemski** [comment] 2023-07-10 09:58
@testing-nerd 

I upgraded 10 to 15 stores from 1.6 to 1.7 using the autoupgrade module. There were troubles, mostly related to third-party modules, but from day one, it was clear that the process is challenging since you have to upgrade your theme, almost all of your modules, etc.

> If a third-party module can do it, then why it can't be done by the official module? It's really a shame.

Migration modules work differently than the one which upgrades a single instance from one version to another. These are two completely different approaches.

**Comment by testing-nerd** [comment] 2023-07-10 10:15
The official module never supported the 1.6 to 1.7 upgrade, it was never mentioned in the official module's specifications.
It was meant only for 1.6 to 1.6, and then 1.7 to the latest versions.

Regarding the migration modules. I'm not talking about them, there are 1-click direct upgrade modules available that can do the job.

> There were troubles, mostly related to third-party modules

Why would you upgrade without uninstalling the 3rd party modules? I tried with the default theme and uninstalled every single module, but it never worked.



> it was clear that the process is challenging since you have to upgrade your theme, almost all of your modules, etc.

I'm talking about an easy Prestashop upgrade. Upgrading the modules after upgrading the shop is a different thing.

If you face challenges upgrading the shop by the official module, then there is something wrong with the module, and the developers should accept it.

**Comment by kpodemski** [comment] 2023-07-10 10:34
@testing-nerd 

> The official module never supported the 1.6 to 1.7 upgrade, it was never mentioned in the official module's specifications.
It was meant only for 1.6 to 1.6, and then 1.7 to the latest versions.

That's not true 🤔 We still have automated tests for upgrades from 1.6 to 1.7 :D I also wrote to you that I did plenty of successful upgrades, I know that @x13pl probably did like 50 upgrades or even more :D

> Why would you upgrade without uninstalling the 3rd party modules? I tried with the default theme and uninstalled every single module, but it never worked.

Why would you uninstall your modules and lose your data? You can disable the modules but never uninstall them. And it could still fail because of the overrides, modifications in the database, etc.

The thing is that the upgrade tool should be core independent, but it requires a lot of time, meaning it requires a lot of money. It's an open source project, if you know developers out there who are motivated to help us improve the module, that would be great :)

**Comment by testing-nerd** [comment] 2023-07-10 10:54
> That's not true 🤔 We still have automated tests for upgrades from 1.6 to 1.7 :D I also wrote to you that I did plenty of successful upgrades

Really? Then why don't you dare to mention it on the module's specification page :D 

![Screenshot 2023-07-10 161108](https://github.com/PrestaShop/PrestaShop/assets/58697830/12d5be15-d6a9-4c15-9553-eac36ab5c79e)


> Why would you uninstall your modules and lose your data? You can disable the modules but never uninstall them. And it could still fail because of the overrides, modifications in the database, etc.

I never thought you'll do it on a live server! The module data and overrides can be migrated later if you do it on a staging server.
But first, the upgrade should work at all.

Perhaps, you're not understanding the point, I mean, it should be an easy upgrade. If you need to do many technical things to make the upgrade work, then using the module is not worthwhile, and you need to work on the module.

**Comment by kpodemski** [comment] 2023-07-10 11:01
@testing-nerd 

> Really? Then why don't you dare to mention it on the module's specification page :D

Well, I know it's a bit confusing, but we're PrestaShop Project. We don't control what's going on on the PrestaShop Marketplace. 

> I never thought you'll do it on a live server! The module data and overrides can be migrated later if you do it on a staging server.
But first, the upgrade should work at all.
> Perhaps, you're not understanding the point, I mean, it should be an easy upgrade. If you need to do many technical things to make the upgrade work, then using the module is not worthwhile, and you need to work on the module.

There are different strategies on how to perform the 1.6 to 1.7 upgrade. It certainly shouldn't be on a live server, and I didn't mean that. What I meant is that third-party solutions are hard to handle for a regular non-technical user. He/She won't understand what's going on, and believe me, some third-party solutions are extremely hard to handle during upgrades. You upgrade, everything's fine, and the next thing you see is a blank page because of this module, even tho it is disabled.

Upgrades from one major version to another are hard, maybe they should be easy as you write, but it requires a lot of work, from the project team, and from developers who make modules.

**Comment by musicpanda** [comment] 2023-07-10 20:51
It wouldn't be that much work to the module to add as an extra requirement for the update from 1.6 to 1.7 that the theme is the default theme. This to name just one idea how the process could become

Just like the previously mentioned problems, this a matter of a few hours work at most. 

I find it a pity that Prestashop is increasingly becoming cryptic about its functioning. Before 8.0 you could find under the /install/upgrade directory how the versions differed from each other. That is no longer possible. I recently tried to find out how the 1.6 Rijndael keys are converted to the 1.7 "secret". I found it impossible. 

Opensource implies openness. Keep it as simple and clear as possible.

**Comment by Quetzacoalt91** [comment] 2024-04-09 16:32
Hi there,

I found out the latest release compliant with PrestaShop 1.6 ([v4.14.3](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.3)) was not on addons.prestashop.com.
I've just uploaded it, so people should be able to upgrade to it and have this issue fixed shortly.

**Comment by Quetzacoalt91** [comment] 2024-04-10 08:29
v4.14.3 is now available on the marketplace and can be download from PrestaShop 1.6.

[Capture vidéo du 10-04-2024 09:24:28.webm](https://github.com/PrestaShop/PrestaShop/assets/6768917/33d4e63a-d67d-4463-91cf-9a3b64db2247)

**Comment by AureRita** [comment] 2024-04-10 10:18
Hi @musicpanda 

As @Quetzacoalt91 said, now you can use autoupgrade on shop 1.6.1.24 as you can see : 

[recording(182).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/743a37b5-6991-4c28-ad1a-19d0cf7aaf6f)

Because this issue seems to be corrected, I'll close this issue. 

Thank you

**Closed as completed** 2024-04-10 10:19 UTC
Labels: Bug, Major, BO, Autoupgrade, Fixed, Verified, Module
