### ISSUE TITLE
Placeholders displayed instead of real data in mails sent to guest customers (1.7.5.1)

### ISSUE THREAD

**Issue by infoviaplus** [PrestaShop/PrestaShop#12663] opened 2019-02-21 19:20 UTC
**Describe the bug**
After upgrading from 1.7.4 branch to 1.7.5.1, guest customers (those without an user account) receive emails with placeholders like {firstname}, {lastname}, {order_name} or {shop_name} instead of real data. Registered users receive well-formed emails. 

**To Reproduce**
1. Update to 1.7.5.1.
2. Make an order as a guest user. 
3. Check the emails received (I've checked the issue at least affects "payment accepted", "order confirmation" and "order cancelled" templates). 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/47867445/53195455-fdb19e80-3615-11e9-8437-bc86fa06ab0f.png)
![imagen](https://user-images.githubusercontent.com/47867445/53195506-115d0500-3616-11e9-9fd5-d4e8cc394213.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-02-22 08:01
Hi @infoviaplus,

Thanks for your report.
In my case, I did not manage to reproduce the issue with PS1.7.5.1 after upgrade from PS1.7.5.0 with the 1-click upgrade v4.6.0.
This issue occurs only with this language?
Did you use the theme by default of PestaShop?
Did you occurs errors during the upgrade?
Thanks!

**Comment by infoviaplus** [comment] 2019-02-22 10:17
Hi: 

No errors during upgrade using 1-click plugin version 4.4.0 (previous version of PS was 1.7.4.3).

The theme is a child of default theme. 

I can't change the language: it's a production site running. 

Don't get me wrong, but I can't see how the front-end theme or the language of the site could be involved taking into account that previously registered users receive correct emails. 

Thanks!

PS: just in case, I add the 1-click update plugin config:

![imagen](https://user-images.githubusercontent.com/47867445/53236239-16609980-3694-11e9-8eb6-ed57e4637e8a.png)

**Comment by khouloudbelguith** [comment] 2019-02-22 10:26
@infoviaplus, the 1-click upgrade v4.4.0 is not the last version released, it is 4.6.0.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by infoviaplus** [comment] 2019-02-22 11:26
I'll try to gather all this information, but in the meanwhile...

> the 1-click upgrade v4.4.0 is not the last version released, it is 4.6.0.

In that case I'm afraid there's also a bug with the 1-click-upgrade plugin. Before and after doing the PrestaShop upgrade, version 4.4.0 of the plugin says that is updated (i.e. is the last release): 

![imagen](https://user-images.githubusercontent.com/47867445/53239717-026d6580-369d-11e9-8481-e57c1c752724.png)

**Comment by khouloudbelguith** [comment] 2019-02-22 11:29
@infoviaplus, you need to upgrade it.
![image](https://user-images.githubusercontent.com/16067358/53239893-73ad1880-369d-11e9-8477-7479e5ccfc6f.png)
Or, you can find it in our marketplace
https://addons.prestashop.com/en/data-migration-backup/5496-.html
Thanks!

**Comment by infoviaplus** [comment] 2019-02-22 11:32
Of course I'll upgrade it, but why the 4.4.0 version displays that is the last release therefore marking the point as OK?

**Comment by khouloudbelguith** [comment] 2019-02-22 11:39
@infoviaplus, it is displayed your actual version or your last version?
Thanks!

**Comment by infoviaplus** [comment] 2019-02-22 11:45
It says "1-click-upgrade plugin is updated (current version is 4.4.0)". 

But that's wrong: it isn't updated (4.6.0 is the last release as you said). But the most relevant part of what I'm saying is that the plugin marks the point of the checklist as OK, leading to the usage of an obsolete version of the plugin.

**Comment by khouloudbelguith** [comment] 2019-02-22 14:55
@infoviaplus, thanks for these clarifications.
I just created a new issue in the `autoupgrade` repository: https://github.com/PrestaShop/autoupgrade/issues/282 
Thanks a lot!

**Comment by khouloudbelguith** [comment] 2019-03-25 07:56
Hi @infoviaplus,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-25 07:56 UTC
Labels: Bug, Email, Autoupgrade, No change required, 1.7.5.1
