### ISSUE TITLE
Breadcrumb Search Console problem still present on Index

### ISSUE THREAD

**Issue by francct** [PrestaShop/PrestaShop#16942] opened 2019-12-27 19:31 UTC
**Describe the bug**
Hi,
After applying the solution suggested in #15632 PR, there is still an error in search console.
Index page still has the "BreadcrumbList" itemtype, but there are no "ListItem" elements.

I believe that `{if $page.page_name != 'index'}` before "breadcrumb.tpl" code can be a solution, but I don't know if there is a better way to solve.

**To Reproduce**
1. Fresh Install of Prestashop 1.7.6.2
2. Apply #15632 PR (change breadcrumb.tpl file)
3. Run Search Console

**Screenshots**
![search_console](https://user-images.githubusercontent.com/59253436/71529709-6cbaec00-28e6-11ea-8005-8a89833159ff.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.6

**Comment by khouloudbelguith** [comment] 2019-12-30 10:19
Hi @francct,

This issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/15642
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15641
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-30 10:19
Duplicate of #15641

**Closed as completed by khouloudbelguith** 2019-12-30 10:19 UTC
Labels: Duplicate
