### ISSUE TITLE
Stock text in product page NOT change

### ISSUE THREAD

**Issue by frankymartinES** [PrestaShop/PrestaShop#14654] opened 2019-07-15 11:37 UTC
Hi, I have found an issue in product page about the stock info of any combination.
To reproduce the error you need to do:
1.- Go to product page
https://noeshoponline.com/cinturones/185-774-test.html#/5-color-gris/32-talla-unica
You will see stock info "Disponible - ¡Recíbelo en 24/48 Horas!"  It is OK!!!
2.- Change color producto and you will see that the stock info NOT change. It is a fail, because that color has not stock. If you press F5 then the text change to "No hay suficientes productos en stock".
3.- And if you change again the product color the error appear again.

I use PS 1.7.5.1 and the products configuration set to NOT sell products without stock.

**Comment by mariem-abid** [comment] 2019-07-15 11:51
Hi @frankymartinES,

I did not manage to reproduce the issue with PS:1.7.6.0
Could you please check with the default template provided by PrestaShop.

**Comment by frankymartinES** [comment] 2019-07-15 11:53
I am going to contact before the theme developers because could be a theme error. Thanks

**Comment by mariem-abid** [comment] 2019-07-15 11:57
@frankymartinES, waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-08-19 07:53
Hi @frankymartinES,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-19 07:53 UTC
Labels: Bug, FO, No change required, 1.7.5.1
