### ISSUE TITLE
Attributes & categories bug in Multishop

### ISSUE THREAD

**Issue by itisco** [PrestaShop/PrestaShop#15073] opened 2019-08-12 11:58 UTC
**Describe the bug**
If you have a Prestashop 1.7.5 or 1.7.6 and want to use the multishop feature then you have 2 major issues : 
1/ the attributes won't display in the product page
2/ the categories won't display in the categories list

**To Reproduce**
0. create at least 2 shops via the multishop menu
1. create categories, attributes and attribute values in "All shops" mode in the catalog menu availlable for all shops
2. select a shop in the drop down menu (top right)
3. click on categories in the catalog and then you won't see any category, even the one you created and availlable on all shops.
4. If you create a product, same issue, the attributes you created are not availlable on the right panel of the combinaison tab.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2
![Screenshot(9)](https://user-images.githubusercontent.com/4580313/62863490-3569eb00-bd09-11e9-8df6-c6cc5dd8f52d.png)
![Screenshot(8)](https://user-images.githubusercontent.com/4580313/62863492-3569eb00-bd09-11e9-94a8-0fa61c1ab25f.png)
![Screenshot(7)](https://user-images.githubusercontent.com/4580313/62863493-36028180-bd09-11e9-9296-11d3d2bc1733.png)
![Screenshot(6)](https://user-images.githubusercontent.com/4580313/62863495-36028180-bd09-11e9-9bad-2ef8c9d01fbb.png)
![Screenshot(5)](https://user-images.githubusercontent.com/4580313/62863496-36028180-bd09-11e9-8780-f6a814d1d302.png)

**Comment by mariem-abid** [comment] 2019-08-13 13:14
Hi @itisco,

I did not manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1omixtsSXVQdECtVt1IsTPgf_94OBvS0S/view

Thanks for check and feedback.

**Comment by khouloudbelguith** [comment] 2019-09-12 07:32
Hi @itisco,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-12 07:32 UTC
Labels: Bug, Categories, Attributes, Multistore, No change required, 1.7.5.2
