### ISSUE TITLE
BO - Popap reduced in the order product page 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26857] opened 2021-12-03 12:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Popap  in the order product page is reduced
![image](https://user-images.githubusercontent.com/89604350/144591243-a7825121-10f6-4a17-848c-d7518594a370.png)
https://watch.screencastify.com/v/4CNQODIWozvuFECFRyyl

### Expected behavior

PS 1.7.7.8
![image](https://user-images.githubusercontent.com/89604350/144591163-d9cf5f7c-c105-42a4-b3be-cc68f16a9f21.png)

### Steps to reproduce

1. Go to BO> Orders> Add new order> search for a customer
2. Go to carts page> detail > Creat an order from this cart
3. see error

### PrestaShop version(s) where the bug happened

1.7.8.0 / 1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by MatShir** [comment] 2022-08-18 13:09
For this behavior, we should have a pop-in not an iframe view. It is supposed to help the merchant to gather information, not for him to navigate. So I'm closing this issue since the solution would be to transform the iframe to a proper popin, it not a bug but a big improvement that will require too much work for what it is worth. We can reopen the issue if a contributor is motivated.

**Closed as not planned by MatShir** 2022-08-18 13:09 UTC
Labels: Bug, Minor, BO, Order, Regression, 1.7.8.0, Verified
