### ISSUE TITLE
FO -  the wishlist button change

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#32717] opened 2023-05-25 15:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The button of wishlist changed 

### Expected behavior

![image](https://github.com/PrestaShop/PrestaShop/assets/115152460/1b41340b-3ba1-426f-bb47-0093b8f2d507)

### Steps to reproduce

Go to FO >add some product to any wishlist > view profile >My wishlists > SEE the button "add to cart "  changed 
 
![image](https://github.com/PrestaShop/PrestaShop/assets/115152460/de13a587-cf14-40db-8f6c-fcba6a84d997)

### PrestaShop version(s) where the bug happened

PS 810-rc

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2023-05-29 16:55
Regression on 8.1.0 :rocket:

**Comment by hibatallahAouadni** [comment] 2023-05-30 09:50
It's seems that the issue is fixed with branch 8.1.x :tada: 
Closing the issue!

**Closed as completed by hibatallahAouadni** 2023-05-30 09:50 UTC
Labels: Bug, Trivial, FO, Fixed, Front-end, Blockwishlist, Verified, Module, 8.1.x
