### ISSUE TITLE
Missing backgrounds on migrated order page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23115] opened 2021-02-03 07:40 UTC
#### Describe the bug

Backgrounds/shadows of some elements are missing on order page.

#### Expected behavior

There should be grey backgrounds to separate the content and make it more readable.

**Screenshots**
![bugs](https://user-images.githubusercontent.com/6097524/106713866-55772380-65fb-11eb-97f5-ae218a5a6ed2.JPG)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-03 09:27
Hello @Hlavtox 

Thanks for your issue! I reproduced the issue only with develop, it seems to be a regression!
But, we need to check if it's really regression or that's the wanted behavior :wink: 

Ping @PrestaShop/ux-team @PrestaShop/product-team I use to see a background-color for these items (see the attached screenshot below) with 1.7.7.1 and now with develop there's no background-color, is it a regression? or this is the expected behavior?

![image](https://user-images.githubusercontent.com/23308427/106726121-5499be00-660a-11eb-9986-bf8f2f968fde.png)

**Comment by marionf** [comment] 2021-02-10 17:19
@TristanLDD @MatShir wdyt ?

**Comment by Hlavtox** [comment] 2021-04-30 09:44
@NeOMakinG @hibatallahAouadni Bump, so it does not make it into 1.7.8 ;-)

**Comment by Progi1984** [comment] 2021-05-28 12:40
Fixed in #24283 by @NeOMakinG

**Closed as completed by Progi1984** 2021-05-28 12:40 UTC
Labels: Bug, PM ✔️, develop, BO, Order, Fixed, Front-end, PR available
