### ISSUE TITLE
Error when sending message to customer + PS Facebook module

### ISSUE THREAD

**Issue by malcek** [PrestaShop/PrestaShop#23391] opened 2021-02-24 14:58 UTC
#### Describe the bug

when sending message on order to customer we get following error:
Type error: Argument 1 passed to PrestaShop\Module\Ps_facebook\Utility\CustomerInformationUtility::getCustomerInformationForPixel() must be an instance of Customer, null given, called in /home/veleproda/public_html/katalog/modules/ps_facebook/classes/Provider/EventDataProvider.php on line 329

[Symfony\Component\Debug\Exception\FatalThrowableError 0]

but when module PS FAcebook is disable message goes through without any problem

#### Expected behavior

Sending message on order to customer

#### Steps to Reproduce

install module, set-up everything in module. Error appears when you hit the button SEND MESSAGE TO CUSTOMER on order detail page

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/54998637/109019107-fa47c680-76b8-11eb-8a20-70ecf73d4197.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.23

**Comment by hibatallahAouadni** [comment] 2021-02-24 16:21
Hello @malcek 

Could you please provide a screenshot of the displayed error.

Thanks!

**Comment by malcek** [comment] 2021-02-24 17:32
this is what i get
![image](https://user-images.githubusercontent.com/54998637/109040859-aea01780-76ce-11eb-85f0-2c55a0109ad4.png)

**Comment by malcek** [comment] 2021-02-24 17:35
and with debugg enable
![image](https://user-images.githubusercontent.com/54998637/109041154-076fb000-76cf-11eb-9266-104ec1eded96.png)

**Comment by Quetzacoalt91** [comment] 2021-02-24 17:47
Hello, that's an error related to the ps_facebook module, and will be fixed in the next version (expect it between tomorrow and the beginning of next week if everything goes well).

This issue is caused by a pixel Event. They are supposed to be sent only on the front office, and checks will be added accordingly.

**Comment by MatShir** [comment] 2021-02-24 17:55
@Quetzacoalt91 Thanks for the clarification. 
Then this issue will be fixed on the Facebook module side. The issues on this repository only concern the bugs and features requests of PrestaShop itself. For any other issue related to the Facebook module, please contact the module [support](support-facebook@prestashop.com). 
Thank you !

**Closed as completed by MatShir** 2021-02-24 17:55 UTC
Labels: Bug, BO, Order, Order messages, No change required, 1.7.7.1
