### ISSUE TITLE
Error 500 on load of categories, clients, orders and customer threads

### ISSUE THREAD

**Issue by Almtesh** [PrestaShop/PrestaShop#21899] opened 2020-11-13 08:09 UTC
### Describe the bug

When I'm on the admin section, I try to go to one of products categories, clients, orders or customer threads, I get a 500 error (Internal Server Error).

The problem pages contents can be seen on the stats page without problem.

#### Expected behavior

This should load the requested page, as seen in the demo website.

#### Steps to Reproduce

1. Download Prestashop 1.7.6.8 from the official website or from github's releases pages
2. Install it on a computer under debian 10 with apache2, mariadb and php from the Debian's official repository
3. Install Prestashop with French language and food and restaurant preset
4. Connect on the admin page after removing the install dir and notice you have a clothes shop
5. Go on one of the problem pages and see the error

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.3.19-1~deb10u1

**Comment by florine2623** [comment] 2020-11-13 08:39
Hi @Almtesh ,

Please downgrade your PHP version to 7.2, more info on server configuration here : 
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
You could also check the [forum](https://www.prestashop.com/forums/) for help.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2020-11-13 08:39 UTC
Labels: Can't reproduce, No change required

**Comment by Almtesh** [comment] 2020-11-13 08:49
I don't get “we were not able to reproduce your issue with the provided information”. You tell me Prestashop 1.7.6.8 does not work with PHP 7.3, but you got it to work when I can't.

**Comment by SimonGrn** [comment] 2020-11-13 09:20
Hello @Almtesh 
It's because we don't reproduce when we test with PHP 7.2.

**Comment by SimonGrn** [comment] 2020-11-13 09:46
I just answer this bit I didn't notice earlier:
>Install Prestashop with French language and food and restaurant preset
>Connect on the admin page after removing the install dir and notice you have a clothes shop

There is no "preset". "Food and Restaurant" is just the "Main Activity" of your shop, it has absolutely no impact on the demo data which is always the same set: a bunch of clothes, mugs and posters.
![image](https://user-images.githubusercontent.com/49909275/99058391-72243200-259d-11eb-9f14-2b2b2e01b5be.png)
