### ISSUE TITLE
BO - Unable to import 'United State' at localization.

### ISSUE THREAD

**Issue by Smriti-webkul271** [PrestaShop/PrestaShop#27156] opened 2021-12-31 10:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When import 'United State' at localization -> getting error 
"The length of property State->name is currently 36 chars. It must be between 0 and 32 chars."

![screenshot-smritidwivedi com-2021 12 31-15_43_07](https://user-images.githubusercontent.com/56150505/147817568-d42ece7d-123a-425d-b1d4-8e689002e0bf.png)

### Expected behavior

State should be import successfully.

### Steps to reproduce

1. Go to International
2. Go to Localization
3. Import State 'United State' -> getting error. 

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.0, 1.7.8.2

### PHP version(s) where the bug happened

_7.3_

### If your bug is related to a module, specify its name and its version

_NA_

**Comment by hibatallahAouadni** [comment] 2021-12-31 13:50
Hello @Smriti-webkul271 

Thanks for reporting the issue!
It's not related to USA but even with Chile you can reproduce the issue.
I was able to reproduce the issue with PS1778 and PS1782. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: last week I didn't reproduce the issue.

Thank you

**Comment by rickygzz** [comment] 2022-01-01 01:16
I guess I solved the issue.

Recently I updated us localization pack to add United States outlying areas or islands, including one which has 36 characters.

And inside `classes/State.php` they limit the state name to 32 characters, while the database name field allows 64.

Updated that line in PR #27162 which solves that problem. Hope it gets reviewed soon

Happy holidays!

**Comment by eternoendless** [comment] 2022-01-03 10:06
The offending strings should be truncated to unblock older shops

**Closed as completed** 2022-01-10 13:09 UTC
Labels: Bug, Major, BO, LO, International, Localization, PR available, 1.7.7.8, Verified
