### ISSUE TITLE
Brands are missing UI for deleting logo image

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#15261] opened 2019-08-26 12:44 UTC
It is currently not possible to delete manufacturer logo image. It is only possible to replace it by another one though.

I suggest implementing something similar like in category page (simple delete button) in manufacturer edit page.

In addition, the behavior of file input differs depending on browser, that might bring some issues (firefox leaves previous value on canceling, - chrome resets the value on canceling). We could solve this to behave equaly by using javascript.

**Comment by khouloudbelguith** [comment] 2019-08-26 12:50
Hi @zuk3975

Your ticket is a duplicate of #14106
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-08-26 12:50
Duplicate of #14106

**Closed as completed by khouloudbelguith** 2019-08-26 12:50 UTC
Labels: Duplicate, Brands
