### ISSUE TITLE
Only part of the images have been regenerated. The server timed out before finishing.

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#10980] opened 2018-10-12 08:01 UTC
**Describe the bug**
Only part of the images have been regenerated. The server timed out before finishing. How to solve?

**To Reproduce**
1. Go to 'Design > Image setting'
2. Click on 'Regenerate thumbnails'
3. See error : Only part of the images have been regenerated. The server timed out before finishing.

**Screenshots**
![timeout](https://user-images.githubusercontent.com/40850132/46855957-ce4a8400-ce22-11e8-9f5e-616c3fa68a43.png)

**Additionnal information**
PrestaShop version: 1.7.3.4
Server software version: Apache
PHP version: 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
Memory limit: 256M
Max execution time: 0
Upload Max File size: 64M

**Comment by khouloudbelguith** [comment] 2018-10-12 08:38
Hi @Akashvastarpara,

I did not manage to reproduce the issue with 1.7.4.3
I attached video record.
https://drive.google.com/file/d/1VcmK02Q7kscEUdSlaT5ihkWosqW_go8K/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by dineshbadrukhiya** [comment] 2018-10-16 11:38
Hello @Akashvastarpara 

As you have mentioned **Max execution time: 0**, I think you have set it to run script for unlimited time but it will give return value timeout "controllers/admin/AdminImagesController.php" at line 625.

Solution: Find the line  
`$this->max_execution_time = (int)ini_get('max_execution_time');`
(approx line 637) and comment it.

Now save the file and again try to regenerate thumbnail.
Best regards.

**Comment by Akashvastarpara** [comment] 2018-10-16 12:36
I have commented line as you have suggested and It's worked.
Thank you @dbadrukhiya .

**Comment by khouloudbelguith** [comment] 2018-10-16 12:48
Hi @Akashvastarpara,

Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-16 12:48 UTC
Labels: Bug, Minor, BO, Image, Fixed

**Comment by dineshbadrukhiya** [comment] 2018-11-21 14:57
@khouloudbelguith do you think this is a bug or ask right person to look on it? Because if I’m not wrong max_execution_time to 0 needs to run scripts for unlimited time.

**Comment by khouloudbelguith** [comment] 2018-11-21 15:14
Hi @dineshbadrukhiya,

I did not manage to reproduce the issue with PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1RZP0xQVruQ0mKtd0qssXFniPIB6kXhZc/view
Thanks!
