### ISSUE TITLE
docker-compose fails to bring up services in 1.7.8.x branch under Linux

### ISSUE THREAD

**Issue by mpaolino** [PrestaShop/PrestaShop#26950] opened 2021-12-11 04:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I found a small issue while trying to `docker-compose up` a fresh environment with branch `1.7.8.x` that makes it fail under Linux (probably other OSs too)

`docker-compose up` [creates 2 volumes](https://github.com/PrestaShop/PrestaShop/blob/4b6ef666897c87e7d2b31f03b8bea5acdd8add6e/docker-compose.yml#L5-L6) that are mounted with default ownership under `/var/www/html/vendor` and `/var/www/html/var`. This makes the start script along with the install fail. Ownership of both directories need to belong to the user `www-data` inside the built image. 

From inside a running prestashop freshly build image brought up with `docker-composer up`:

![Screenshot from 2021-12-10 20-44-04](https://user-images.githubusercontent.com/757973/145662544-f557c53f-ddbb-46b3-b853-7c8cf8e9d050.png)

The output of `docker-compose up`:

![Screenshot from 2021-12-11 01-21-04](https://user-images.githubusercontent.com/757973/145664056-5f21ab20-390d-40cc-84bc-791eca0138a4.png)

I fix `/var/www/html/vendor` directory permissions I still get:

![Screenshot from 2021-12-11 01-29-36](https://user-images.githubusercontent.com/757973/145664074-64371b5f-7072-4f21-a030-731480385856.png)
 
If I point a browser to the running apache service in port 8001 I get:

![Screenshot from 2021-12-10 19-14-52](https://user-images.githubusercontent.com/757973/145663574-70fce431-9510-4901-8c31-a59f3ae8b053.png)

BTW I'm not sure if considering the npm missing error a bug, I'll leave it to the team to decide, the fix is also trivial, install it along nodejs in the Dockerfile or in the parent docker image.

### Expected behavior

`$ docker-compose up` brings up a new environment, either installing a fresh one or starting an already installed one.

### Steps to reproduce

Under Linux (not tested in other environments):

1- Delete any previous old containers, in my case: `$ docker image rm prestashop_prestashop-git_1 prestashop_mysql_1`
2- Delete any previous old volumes, in my case: `$ docker volume rm prestashop_db-data prestashop_var prestashop_vendor`
3- Delete any previous old prestashop image, in my case: `$ docker rmi prestashop_prestashop-git`
4- Clone a fresh copy of Prestashop repository and switch to branch `1.7.8.x`:
`$ git clone --branch 1.7.8.x https://github.com/PrestaShop/PrestaShop.git && cd PrestaShop`
5- Run `$ docker-compose up` (make sure you deleted previous containers, volumes and image first!)

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

n/a

**Comment by matks** [comment] 2021-12-11 14:15
> BTW I'm not sure if considering the npm missing error a bug, I'll leave it to the team to decide, the fix is also trivial, install it along nodejs in the Dockerfile or in the parent docker image.

Well, there's going to be saying yes and people saying no 😅  see below discussion

https://github.com/PrestaShop/PrestaShop/pull/26562

**Comment by hibatallahAouadni** [comment] 2021-12-13 14:33
Hello @mpaolino & @matks 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26768. 
And it's already fixed on 8.0.0 (next major version) :tada: Here's the PR #26769

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-13 14:34
Duplicate of #26768

**Comment by mpaolino** [comment] 2021-12-13 14:45
> Hello @mpaolino & @matks
> 
> We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26768. And it's already fixed on 8.0.0 (next major version) tada Here's the PR #26769
> 
> Thanks!

@hibatallahAouadni (cc @matks) with all due respect I have some issues regarding your decision:

1) Its **not** the same bug.
2) What's the point in having a stable branch if you don't fix reported bugs (with fix contributions) and expect them to be fixed in a future incompatible release?
3) The bug wasn't even tested

**Comment by hibatallahAouadni** [comment] 2021-12-15 15:04
Hello @mpaolino 

Thanks for your patience and your understanding :pray: 
@SD1982 reproduce the issue with PS1.7.7.x and PS1.7.8.x. I’ll add this to the debug backlog so that it’s fixed.

Thanks for your PR :rocket: 

Thank you

**Comment by mpaolino** [comment] 2021-12-15 15:37
> Hello @mpaolino
> 
> Thanks for your patience and your understanding pray @SD1982 reproduce the issue with PS1.7.7.x and PS1.7.8.x. I’ll add this to the debug backlog so that it’s fixed.
> 
> Thanks for your PR rocket
> 
> Thank you

![giphy](https://user-images.githubusercontent.com/757973/146216695-2e2a9695-78d3-407e-9629-578226b31091.gif)

**Comment by dingedi** [comment] 2022-02-04 11:06
same issue, dont work with this fix [https://github.com/PrestaShop/PrestaShop/pull/26769](https://github.com/PrestaShop/PrestaShop/pull/26769)

**Comment by matks** [comment] 2022-04-25 15:42
The bug we could observe has been fixed by https://github.com/PrestaShop/PrestaShop/pull/26951

@dingedi please open another bug report if you have another issue ;)

**Closed as completed by matks** 2022-04-25 15:42 UTC
Labels: Bug, Minor, CO, Fixed, PR available, 1.7.7.0, Verified, Docker
