### ISSUE TITLE
Wrong voucher conversion between currencies

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#11787] opened 2018-12-15 22:34 UTC
**Describe the bug**
Voucher value is not converted correctly between currencies. Minus sign missing in front of discount value in basket.

**To Reproduce**
1. in BO create a voucher with value of 10 USD
2. in FO, currencies set to GBP insert that voucher in basket
3. voucher will be displayed showing -£10.00 
4. change currencies to USD - correct voucher value is shown
5. change currencies back to GBP and you'll see
Discount £7.17 (there is minus sign missing -£7.17)
and the voucher displayed below is showing -£10.00
Very confusing.

**Screenshots**
![screenshot_basket](https://user-images.githubusercontent.com/31688689/50048010-9e895800-00c1-11e9-829a-553b6ad50991.png)

**Additionnal information**
Default currency: GBP
PrestaShop version: 1.7.4.2
PHP version: 5.6.30

**Comment by khouloudbelguith** [comment] 2018-12-17 08:01
Hi @mrabsinthe,

Thanks for your report.
Have you the same issue described in this ticket: #9914?
Thanks!

**Comment by mrabsinthe** [comment] 2018-12-17 08:22
I don't think it is the same, it's very similar plus the fact that I do mention there should be "minus sign" in cart if discount is displayed. This has nothing to do with loyalty points. Anyway, the bug is still present and as soon as 1.7.5 is in stable, I'll test it. Or will you?

**Comment by BenTen** [comment] 2018-12-17 08:45
You can add 1.7.4.4, I have the same issue with this version.

BO: create a voucher TESTVOUCHER of 5000 jpy
FO: make an order of 5.71 EUR with this discount

1st error:
FO: in order detail, the discount line is wrong
https://tof.cx/image/H75fD
The amount is the total of the discount, not the partial discount

(BO: the new TESTVOUCHER is convert in euro (33.38 eur))

FO: Add an item in the cart, in JPY with this voucher
2nd error: the amount is not display correctly  (33 JPY instead than 2570 JPY)
https://tof.cx/image/H77bf

**Comment by khouloudbelguith** [comment] 2018-12-17 09:19
Hi all,

The issue still exists in PS 1.7.5.0RC1, it is not fixed yet.
I manage to reproduce the issue with PS1.7.5.0rc1
![image](https://user-images.githubusercontent.com/16067358/50077602-1ac88c00-01e5-11e9-8ebf-60800c782a75.png)
As described in this #9914, a voucher with a value in secondary currency, in the FO, the voucher text is displaying the wrong amount.
It is described in the pdf file attached to the ticket: http://forge.prestashop.com/secure/attachment/60735/loyalty%20points%20error%20when%20in%20sar%20value.pdf
About the "minus sign", it is a normal behavior, because we the total discount = 10£ &  not discount = -10£
Your ticket is a duplicate of #9914
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-17 09:19
Duplicate of #9914

**Closed as completed by khouloudbelguith** 2018-12-17 09:19 UTC
Labels: FO, Duplicate, Cart rules, Currencies, 1.7.4.2
