### ISSUE TITLE
Missing index on table ps_address

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25764] opened 2021-09-02 07:16 UTC
#### Describe the bug

The display of the BO page *Catalog - Brands and suppliers* takes ~60 s to display. 

We have ~50'000 addresses and ~5'000 manufacturers (=brands)

#### Expected behavior

Working with BO should be more fluid.

#### Steps to Reproduce

1. Go to *Catalog - Brands and suppliers*
2. Go and get a coffee ☕ 🥐 (wait for  ~60 s)

**Solution**

There is a missing index on `ps_address`:

    alter table `ps_address` add index manufacturer_deleted (`id_manufacturer`, `deleted`);

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-09-02 10:50
Hello @lmeyer1 

I didn't manage to reproduce your issue with PS1775 (fresh install), see the attached screen record below:

https://drive.google.com/file/d/1gB-Y8Ev5P9SK8Yj6mwcA1IyHuVeLcHLz/view

After adding 5 suppliers, it took longer. Then, I add 5 more (10 brands), it tooks only 1 second:

https://drive.google.com/file/d/1IsIeQw3m9FVvc91vWYqbhM--kmdRE973/view

So, could you please provide  an excel file with all needed brands to help me reproducing the issue.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-03 14:54
Hello @lmeyer1 

As discusssed on Slack, I didn't encounter this issue even with 5000 Suppliers:

https://drive.google.com/file/d/1BH1xuS60S_gIR6R-SCb-Zw8Kf7nBw7xW/view

Despite our efforts, we were not able to reproduce your issue with the provided information.We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-03 14:54 UTC
Labels: Bug, BO, Can't reproduce, Brands, 1.7.7.5
