### ISSUE TITLE
1.7.4.3 reserved products after creating order slip without "book in stock"

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#11359] opened 2018-11-12 13:03 UTC
Hi to everybody,

if a costumer sends back a product and an credit-slip was created without choosing "book in stock" (german: "auf Lager buchen")
![image](https://user-images.githubusercontent.com/44971218/48349104-8fa72400-e683-11e8-82e1-03619465abb5.png)

product is set in stock management on status "reserved"

![image](https://user-images.githubusercontent.com/44971218/48349068-70a89200-e683-11e8-98ea-216b1a94e1b4.png)

but what benefit is behind it? For what purpose is the product reserved? I do not see that as a necessity.
There is no way to remove the product from the "reserved" state. Setting the reserved amount in the database to zero does not bring any results. The corresponding column always jumps back to the reserved quantity.

I need a solution to get these products out of the "reserved" status.
Thank you for your help

PS version is 1.7.4.3

**Comment by khouloudbelguith** [comment] 2018-11-12 14:18
Hi @didi-2018,

When you create an order with the ProductA(qty=1), in the stocks page, a product is set in stock management on status "reserved".
![image](https://user-images.githubusercontent.com/16067358/48352788-f4677c00-e68d-11e8-841e-c3c017b12285.png)
In the ps_stock_available table the physical_quantity = quantity + reserved_quantity
But the reserved_quantity represents the quantity of products that are currently in an open customer order.
Thanks to check & feedback.

**Comment by didi-2018** [comment] 2018-11-12 14:55
Hi, 
This has nothing to do with an open order, but with it as described above.
Please do the following steps:
1.) go to any shipped order
2.) select: "return product"
![image](https://user-images.githubusercontent.com/44971218/48354706-9e490780-e692-11e8-9b46-f6faaed3e2d2.png)
3.) choose any product of that order
4.) choose "create credit slip"
5.) choose NOT "book on stock" 
![image](https://user-images.githubusercontent.com/44971218/48354838-f97afa00-e692-11e8-915f-f406d48b88a9.png)
6.) press button "return product"
7.) go to stock management and you will see that this product is now "reserved"

thank you very much for doing that!

**Comment by khouloudbelguith** [comment] 2018-11-12 15:45
Hi @didi-2018,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1U0MlfeQIzAb74MF2t0Oz3R8E94x8qi0C/view
Thanks to check & feedback.

**Comment by didi-2018** [comment] 2018-11-12 16:15
thanks for testing it! But you are using 1.7.4.4 and I use 1.7.4.3

**Comment by didi-2018** [comment] 2018-11-12 16:24
I tested it again with "Re-Stock products" and order status "refunded"

Could you please make a test with that informations

**Comment by khouloudbelguith** [comment] 2018-11-12 16:55
@didi-2018, yes when I change the order to the refunded status, the quantity of reserved product will be changed from 0 to 1.
In our documentation, you can find that Reserved stock represents the quantity of products that are currently in an open customer order that has not been shipped yet. In other terms, these products are physically in your storage but are not available for sale anymore => the case of your issue.
For more details, you can follow this [link](http://doc.prestashop.com/display/PS17/Stock+overview)
Thanks!

**Comment by didi-2018** [comment] 2018-11-12 17:07
But products which are returned and refunded, should not be reserved again. Reserved for what? A costumer who returns a products do not want to by that product again. Such an order is after return and refund closed. Don´t you think so?

Is there a solution to get all these "reserved" products from returned orders out of that status?

**Comment by khouloudbelguith** [comment] 2018-11-13 07:52
@didi-2018, the term reserved in this case is that these products are physically in your storage but are not available for sale anymore, they not be reserved again but they are expired (not in use)
Thanks!

**Comment by didi-2018** [comment] 2018-11-13 12:46
so there is no way to see which are reserved for open orders and which are expired. I still do not understand the meaning behind it. What did the programmer think about programming such a thing? Can I change something in the status "refunded" that the product is no longer "reserved"?

I really need a solution to get all these products out of the "reserved" state.

**Comment by khouloudbelguith** [comment] 2018-11-13 13:20
@marionf, what do you think, in our [documentation](http://doc.prestashop.com/display/PS17/Stock+overview), Reserved stock represents the quantity of products that are currently in an open customer order that has not been shipped yet. In other terms, these products are physically in your storage but are not available for sale anymore.
Is that possible to add another term for `products are physically in your storage but are not available for sale anymore` which is not `reserved`?

**Comment by didi-2018** [comment] 2018-11-13 13:25
I found the solution! ! !  
Choose in order status "refunded" the field "set order on shipped"
![image](https://user-images.githubusercontent.com/44971218/48416143-ae72ec80-e74f-11e8-8285-7fc02284d485.png)
And thats it! no more reserved products! hahahaha.....so simple to do :-)))))

**Comment by khouloudbelguith** [comment] 2018-11-13 13:27
@didi-2018, so can I close the issue? since it is fixed?
Thanks!

**Comment by didi-2018** [comment] 2018-11-13 13:28
Yes please close it, but as "solved" if it possible

**Comment by khouloudbelguith** [comment] 2018-11-13 13:29
@didi-2018, thanks!

**Closed as completed by khouloudbelguith** 2018-11-13 13:29 UTC
Labels: Improvement, BO, Stocks, No change required, 1.7.4.3

**Comment by pks891618** [comment] 2020-10-30 04:49
Is there is any possibilities that if we reset our stock then reserved also reset to 0 ?
