### ISSUE TITLE
Can't upgrade the shop

### ISSUE THREAD

**Issue by Kallhagens** [PrestaShop/PrestaShop#35344] opened 2024-02-13 21:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I I'm trying to do the latest upgrade with 1 click upgrade but I'm getting a bunch of error codes. And the zettle module with the sync doesn't work either, and it says something with webhook error, but one.com can't find anything wrong with it. What can I do?
I'll send you pictures of some of the errors my last few days. Yesterday I didn't even get into the back office so I had to do a full restore of a saved backup.

<img width="760" alt="1-click upgrade" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/88133db0-85b3-4f8f-b92e-389cc582cf11">
<img width="584" alt="2 till one Skärmbild 2024-02-09 203254" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/cd6abd46-8974-4dc1-b7f1-9ca2c38e0bae">
<img width="938" alt="3 till one Skärmbild 2024-02-09 203352" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/e935615b-aff8-4251-98a9-559649793201">
<img width="808" alt="4 till one Skärmbild 2024-02-09 203448" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/7753faf0-af24-4056-927e-15d20de27be5">
<img width="895" alt="5 till one Skärmbild 2024-02-09 203736" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/cc397638-0518-4670-8303-1ae820869b49">
<img width="1119" alt="error ps" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/58cbf763-d55e-4a31-92f4-d31cd2617b5e">
<img width="674" alt="fel koder " src="https://github.com/PrestaShop/PrestaShop/assets/159957893/0b57cf75-a878-4b32-8a58-9e9e79c86206">
<img width="644" alt="mer felkoder" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/09ca1b9b-8b77-49a6-a692-e657e365c12c">
<img width="662" alt="my curent php version" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/c8c65c40-a13c-4a2b-a7ec-44c49b352f1c">
<img width="652" alt="server fel" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/7d66176b-7608-4ba0-bc4e-c0f7d648459d">
<img width="907" alt="Skärmbild 2024-02-08 104129" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/04f88736-d090-4255-bf3e-a1392d330755">
<img width="727" alt="till one Skärmbild 2024-02-09 203135" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/bcb72b01-ac6b-43f7-ba28-a870d5ef7472">

### Expected behavior

I want to be able to do the upgrade so that all bugs disappear so I can use the zettle clutch. And Klarna checkout with Postnord and DHL connection without any problems.

### Steps to reproduce

 The update: I'm in the middle of a 1-click upgrade.and have installed your zip module before the upgrade.
 
 I have installed the Zettle module, I have connected it with API. I've synced the layer. Then the problems start when it has to synchronize the updates itself. Then you get the e-mails about webhook that you see a picture of.
 
 I have installed the module for klarna. configured it with API. and post the link. It works first, then it stops working. And the shipping options aren't included at checkout. I think all problems can be solved with an update. But it doesn't work.
 
 I get "thrown out" all the time so I have to do a back up and reset to even get back into the back office again.

### PrestaShop version(s) where the bug happened

Your current PrestaShop version: 8.0.2

### PHP version(s) where the bug happened

Your current PHP version: 8.0.30

### If your bug is related to a module, specify its name and its version

 Klarna payments v1.5.0 - av Invertus. v1.2.18 - av Zettle. 1-clickupgrade.

**Comment by SharakPL** [comment] 2024-02-14 08:12
Hi @Kallhagens 

Please remember to make titles of your issues more concise.

Looks like one of your modules is causing the problem. By default 1-click upgrade module should disable non-native modules. I suggest you use this option.

**Comment by Kallhagens** [comment] 2024-02-14 08:29
I don't understand what you mean by – I suggest you use this option. ?
When I use 1-click upgrade, everything crashes and I can't get into the back office, but have to recreate a backup that was before the update to get back in.

Med vänliga hälsningar
Källhagens Gård Lindesberg AB
Hanna Christoffersson

***@***.***
073-8195495 Källhagens gård
072-1435548 Om ert ärende gäller försäkring i Svedea

________________________________
Från: Tom Zajac ***@***.***>
Skickat: den 14 februari 2024 09:13
Till: PrestaShop/PrestaShop ***@***.***>
Kopia: Kallhagens ***@***.***>; Mention ***@***.***>
Ämne: Re: [PrestaShop/PrestaShop] Can't upgrade the shop (Issue #35344)


Hi @Kallhagens<https://github.com/Kallhagens>

Please remember to make titles of your issues more describing.

Looks like one of your modules is causing the problem. By default 1-click upgrade module should disable non-native modules. I suggest you use this option.

**Comment by florine2623** [comment] 2024-02-14 08:42
Have you enabled theses options on your autoupgrade module :
<img width="817" alt="Screenshot 2024-02-14 at 09 41 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/97adbbf9-1ba7-4960-a598-863962715cbb">

**Comment by Kallhagens** [comment] 2024-02-14 08:56
Yes it looks like the picture you sent, please send with a picture

Med vänliga hälsningar
Källhagens Gård Lindesberg AB
Hanna Christoffersson

***@***.***
073-8195495 Källhagens gård
072-1435548 Om ert ärende gäller försäkring i Svedea

________________________________
Från: florine2623 ***@***.***>
Skickat: den 14 februari 2024 09:42
Till: PrestaShop/PrestaShop ***@***.***>
Kopia: Kallhagens ***@***.***>; Mention ***@***.***>
Ämne: Re: [PrestaShop/PrestaShop] Can't upgrade the shop (Issue #35344)


Have you enabled theses options on your autoupgrade module :
Screenshot.2024-02-14.at.09.41.22.png (view on web)<https://github.com/PrestaShop/PrestaShop/assets/16019289/97adbbf9-1ba7-4960-a598-863962715cbb>

**Comment by Kallhagens** [comment] 2024-02-14 09:40
Now I tried updating and unchecking the green boxes. There will be no difference still get error codes. See the pictures

Med vänliga hälsningar
Källhagens Gård Lindesberg AB
Hanna Christoffersson

***@***.***
073-8195495 Källhagens gård
072-1435548 Om ert ärende gäller försäkring i Svedea

________________________________
Från: Hanna Christoffersson ***@***.***>
Skickat: den 14 februari 2024 09:56
Till: PrestaShop/PrestaShop ***@***.***>
Ämne: Sv: [PrestaShop/PrestaShop] Can't upgrade the shop (Issue #35344)

Yes it looks like the picture you sent, please send with a picture

Med vänliga hälsningar
Källhagens Gård Lindesberg AB
Hanna Christoffersson

***@***.***
073-8195495 Källhagens gård
072-1435548 Om ert ärende gäller försäkring i Svedea

________________________________
Från: florine2623 ***@***.***>
Skickat: den 14 februari 2024 09:42
Till: PrestaShop/PrestaShop ***@***.***>
Kopia: Kallhagens ***@***.***>; Mention ***@***.***>
Ämne: Re: [PrestaShop/PrestaShop] Can't upgrade the shop (Issue #35344)


Have you enabled theses options on your autoupgrade module :
Screenshot.2024-02-14.at.09.41.22.png (view on web)<https://github.com/PrestaShop/PrestaShop/assets/16019289/97adbbf9-1ba7-4960-a598-863962715cbb>

**Comment by florine2623** [comment] 2024-02-14 09:50
You need to answer via github, if not, I can't see the attached files

**Comment by Kallhagens** [comment] 2024-02-14 09:55
Now I tried updating and unchecking the green boxes. There will be no difference still get error codes. See the pictures
<img width="407" alt="error during database" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/bb951fc7-3d97-43fd-a8d1-5a7a9df8af68">
<img width="375" alt="error" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/c7b4e30f-bfae-4337-9ea0-cc0f7561e199">

**Comment by florine2623** [comment] 2024-02-14 10:31
I upgraded my shop from 8.0.2 to 8.0.5

<img width="877" alt="Screenshot 2024-02-14 at 11 24 07" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7090995c-afa2-4e4c-bbcb-b083d7b39121">

The upgrade is successful :

https://github.com/PrestaShop/PrestaShop/assets/16019289/cad97c0e-c03a-4401-8887-b3a83869e71a

The issue can come from some of your external modules.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. I suggest you to contact the support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I will close the issue as it is not reproducible.

Thank you

**Closed as completed by florine2623** 2024-02-14 10:31 UTC
Labels: Bug, Waiting for author, Autoupgrade, Module

**Comment by Kallhagens** [comment] 2024-02-14 10:34
But even if it says that the update is done, it is not, it still says that I have the old update.

**Comment by Kallhagens** [comment] 2024-02-14 10:46
<img width="679" alt="version" src="https://github.com/PrestaShop/PrestaShop/assets/159957893/6d2735fa-ea09-444f-9004-a008dc7026ee">
