### ISSUE TITLE
Problem with updating PrestaShop 8 modules

### ISSUE THREAD

**Issue by przemexm** [PrestaShop/PrestaShop#32174] opened 2023-04-15 07:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I have a problem with updating modules in PrestaShop 8, they don't update, PrestaShop php 7.4 but even if I switch to 8.1 the same, I see that it's a global problem because a lot of people have a problem with it, there are hundreds of posts around the world with this problem e.g. entry:  https://github.com/PrestaShop/PrestaShop/issues/32129#issuecomment-1509370447

### Steps to reproduce

Idea on the modules tab, I click update, all the process starts after a while on the right side I get an error message
  it does not go to update the requested module and it says that updates are available

Nie można Upgrade modułu mbeshipping. Handler not found for source https://addons.prestashop.com/pl/kurierzy/89528-mbe-eship-plugin.html?utm_source=back-office&utm_medium=push-addons&utm_campaign=back-office-PL&utm_content=download

Nie można Upgrade modułu mbeshipping. Handler not found for source https://addons.prestashop.com/pl/kurierzy/89528-mbe-eship-plugin.html?utm_source=back-office&utm_medium=push-addons&utm_campaign=back-office-PL&utm_content=download

Unable to Upgrade the mbeshipping module. Handler not found for source https://addons.prestashop.com/en/couriers/89528-mbe-eship-plugin.html?utm_source=back-office&utm_medium=push-addons&utm_campaign=back-office-PL&utm_content=download

[
![231978667-c81ab79d-2b99-4fc1-bc12-0dcc96d5df60](https://user-images.githubusercontent.com/77234765/232194307-2af24a72-bbd9-4730-9e47-fe4cb956525d.jpg)
](url)

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2023-04-19 00:47
Duplicate of #32129

**Closed as completed by hibatallahAouadni** 2023-04-19 00:47 UTC
Labels: Bug, Duplicate, Invalid
