### ISSUE TITLE
Product Availability not displayed in detail page anymore

### ISSUE THREAD

**Issue by icemansparks** [PrestaShop/PrestaShop#15210] opened 2019-08-21 21:38 UTC
**Describe the bug**
In on of the current Versions of the module, the fields for editing the product availaility were removed. After this change the fields are no longer editable in the backoffice and the availability wich is set in the product details does not show on the details page in frontoffice.

**To Reproduce**
1. Go to product details
2. edit settings for shipping and select "custom shipping time"
3. disable product stock management from system settings
4. lookup product in frontoffice, the availability you edited is not visible.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-08-22 08:39
Hi @icemansparks,

I did not manage to reproduce the issue with PS1.7.6.0 & the ps_legalcompilance v3.0.2.
The "Delivery time" is well displayed.
I attached a screen record
https://drive.google.com/file/d/1L4nLrJ58RE2-JPCHuJzch9cuQw5tC9Io/view
Thanks to check & feedback.

**Comment by icemansparks** [comment] 2019-09-09 09:45
I can't reproduce the steps in the video - possibly this has something to do with the template used in the project.
We now created a workaround for this specific template until we can fully align it with the behaviour displayed in your video. Thanks for checking and responding :)

**Comment by khouloudbelguith** [comment] 2019-09-09 13:50
@icemansparks, what is the exact version of the ps_legalcompilance did you use?
Did you use the default theme Classic?

Thanks!

**Comment by icemansparks** [comment] 2019-09-09 14:01
Hi @khouloudbelguith,
the version for the legal compliance module is the exact same as in your video (3.0.2).

The template of this specific shop is already customized, but was based on the Prestashop 1.7.5.2 "Classic" theme. I will try to switch to the untouched classic theme for comparison but will have to set up a test-environment first.

**Comment by khouloudbelguith** [comment] 2019-09-11 13:29
@icemansparks, thanks!
Waiting for your feedback

**Comment by khouloudbelguith** [comment] 2019-10-10 07:48
Hi @icemansparks,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-10 07:48 UTC
Labels: Bug, FO, No change required, 1.7.5.2
