### ISSUE TITLE
Cache not working in getPriceStatic function. Poor performance when lot of products in cart.

### ISSUE THREAD

**Issue by alx-web** [PrestaShop/PrestaShop#24978] opened 2021-06-15 20:06 UTC
#### Describe the bug
The bug, is prestashop is very slow when we have a lot of (>50) products on the cart. The website load in 4/5 sec 

#### Expected behavior
Normally, even if we have a big cart prestashop should have good performance (load <= 1sec)

#### Steps to Reproduce

1/ Add 50 different products on the cart
2/ Navigate on the website

#### Where the problem come :

The problem come from the function `getPriceStatic`. The problem is the function receive a `$quantity` for each line of the cart. But `$cart_quantity` is calculated for all combinations of a cart for a same product.

Therefore, the first part of the "if" pass, and the cache is never stored. This cause lot of performance problem. I think we should insert `$id_product_attribute` on `cache_id` var name to not have the problem

```
$cart_quantity = 0;
        if ((int) $id_cart) {
            $cache_id = 'Product::getPriceStatic_' . (int) $id_product . '-' . (int) $id_cart;
            if (!Cache::isStored($cache_id) || ($cart_quantity = Cache::retrieve($cache_id) != (int) $quantity)) {
                $sql = 'SELECT SUM(`quantity`)
                FROM `' . _DB_PREFIX_ . 'cart_product`
                WHERE `id_product` = ' . (int) $id_product . '
                AND `id_cart` = ' . (int) $id_cart;
                $cart_quantity = (int) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue($sql);
                Cache::store($cache_id, $cart_quantity);
            } else {
                $cart_quantity = Cache::retrieve($cache_id);
            }
        }

```

#### Additional information

* PrestaShop version: 1.7.7x
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-06-16 08:39
Hello @alx-web 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #14979. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-16 08:39
Duplicate of #14979

**Closed as completed by hibatallahAouadni** 2021-06-16 08:39 UTC
Labels: Duplicate
