### ISSUE TITLE
Problem with button insert a module prestashop 1.7.4.3

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#20081] opened 2020-07-07 11:43 UTC
Hello,
when I try to click the "Insert a module" button, 
the white page with "Gateway timeout" appears, 
How can I solve it?

Thanks for help

**Comment by marionf** [comment] 2020-07-08 08:57
Hello, 

Since the provided information isn't sufficient to reproduce the issue, we are closing it. Feel free to open a new one with all the requested information. 

Thank you

**Closed as completed by marionf** 2020-07-08 08:57 UTC
Labels: Missing information
