### ISSUE TITLE
Email subject french translation is missing for changed order

### ISSUE THREAD

**Issue by jlebleu** [PrestaShop/PrestaShop#21175] opened 2020-09-27 09:25 UTC
#### Describe the bug

For a shop using french language, when modifying an order the customer receives an email with subject : 'Your order has been changed'
Email body is in french, I did not find any translation in the internationalization translation page.

#### Expected behavior
Should receive an email with subject 'Votre commande a été modifiée'

#### Steps to Reproduce

1. Got to order page
2. Update order

#### Additional information
Shop : https://carnetsbleus.fr/

* PrestaShop version:  1.7.6.7
* PHP version: 7.2.31 
* MySQL : 5.6.48-log

**Comment by khouloudbelguith** [comment] 2020-09-28 09:49
Hi @jlebleu,

I manage to reproduce the issue with PS1768 and ps_emailalerts module v2.2.1.
![image](https://user-images.githubusercontent.com/16067358/94417638-9c05ce80-0180-11eb-8969-e4737d936e08.png)
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14183
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-28 09:49
Duplicate of #14183

**Closed as completed by khouloudbelguith** 2020-09-28 09:49 UTC
Labels: Duplicate
