### ISSUE TITLE
dashboard not load values

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#14162] opened 2019-06-12 09:53 UTC
**Describe the bug**
I don`t know why but my dashboard stoped downolad the value. The uploading "wheels" are rotating but nothing happen...

**To Reproduce**
4. See error all the values in the left column in dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/50954519/59341718-0509ce80-8d11-11e9-9610-0e055b09630a.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 5.6.4

**Comment by khouloudbelguith** [comment] 2019-06-12 10:01
Hi @photinia73,

You just created a previous ticket: #14124 about this issue.
Please follow: #14124

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-12 10:01
Duplicate of #14124

**Closed as completed by khouloudbelguith** 2019-06-12 10:01 UTC
Labels: Duplicate, Dashboard
