### ISSUE TITLE
prestashop 1.7.6.1 email subject shop name not changing

### ISSUE THREAD

**Issue by amarmib2** [PrestaShop/PrestaShop#16675] opened 2019-12-04 10:16 UTC
**Describe the bug**
Hi I try my options but still name is not changing. 
I had try changing name by Enable Multistore. But after that also its not changing every where it got changed but on email subject line shop name has not changed.

So can some one help me out with this 

Thanks  

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3
![email](https://user-images.githubusercontent.com/58510133/70133612-7c129500-16ac-11ea-96d9-8e8a7d510f03.jpg)

**Comment by khouloudbelguith** [comment] 2019-12-04 10:26
Hi @amarmib2,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16500 to fix the issue.
It is fixed in the last release PS1.7.6.2.
Your ticket is a duplicate of #16499
So, I close it.
Thanks!

PS: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Please downgrade your PHP version.

**Comment by khouloudbelguith** [comment] 2019-12-04 10:26
Duplicate of #16499

**Closed as completed by khouloudbelguith** 2019-12-04 10:26 UTC
Labels: Duplicate
