### ISSUE TITLE
Admin hooks of format "display#controller_name#Form" on legacy admin forms are not executed 

### ISSUE THREAD

**Issue by hugo-fasone** [PrestaShop/PrestaShop#36185] opened 2024-05-17 12:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Admin hooks of format "display#controller_name#Form" on legacy admin forms such as "displayAdminReturnForm" are not executed.

The hook is supposed to be called here : https://github.com/PrestaShop/PrestaShop/blob/8.1.6/admin-dev/themes/default/template/helpers/form/form.tpl#L663
Here `$name_controller` is supposed to be the name of the controller, so for exemple "AdminReturn" in the case of the  "AdminReturn" controller when we try to view a single order return. The hook should be called at the end of the form

![screenshot-127 0 0 1_4502-2024 05 17-12_55_42](https://github.com/PrestaShop/PrestaShop/assets/28593328/bbb78141-796f-4585-a8e5-1a72f4dd94ce)

But actually, the value of `$name_controller` is an empty string, so the executed hook is "displayForm" and not "displayAdminReturnForm". This behaviour is caused by these two code snippets:

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L2621C1-L2623C10
https://github.com/PrestaShop/PrestaShop/blob/8.1.6/classes/helper/HelperForm.php#L40

On the `AdminController.php` file, we see that `$name_controller` takes the value only if it doesn't equal null. But in the `HelperForm.php` file we see that `$name_controller` is not equal to null, it's an empty string, thus the bug : `$name_controller` is equal to an empty string and never takes the `Tools::getValue('controller')` as a value

We see in this file the smarty affectation of the "name_controller" variable used in the `form.tpl` file
https://github.com/PrestaShop/PrestaShop/blob/8.1.6/classes/helper/HelperForm.php#L291

This PR introduced this bug : https://github.com/PrestaShop/PrestaShop/pull/31514

### Expected behavior

The hook "displayAdminReturnForm" should be executed at the end of a return form in backoffice (in the red rectangle on the screenshot above)

### Steps to reproduce

1. Create a module that's attached to the "displayAdminReturnForm" hook
2. On this module, create a function that returns a simple string, such as "test"
3. On the "AdminReturn" in backoffice, select a return issued by a customer
4. The text "test" should appear at the end of the form (see screenshot above), but it doesn't 

### PrestaShop version(s) where the bug happened

Tested on 8.1.4, but was presumably introduced in 8.0.2

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

### Your company or customer's name goes here (if applicable).

PliciWeb

**Comment by AureRita** [comment] 2024-05-29 14:09
Hi @hugo-fasone 

Thank you for your report and sorry for the time we spend to answer you, to try to reproduce your issue, can you provide us a exemple module to test it ? 

waiting for your feedback

**Comment by paulnoelcholot** [comment] 2024-06-24 14:26
Hello @hugo-fasone,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-06-24 14:26 UTC
Labels: Bug, BO, Hook, Invalid, 8.1.x
