### ISSUE TITLE
Error 500 on Referrer front stats.php

### ISSUE THREAD

**Issue by igurina** [PrestaShop/PrestaShop#12731] opened 2019-02-26 22:18 UTC
The front for referrers doesnt work: gives error 500

Debug: 

(1/1) ContextErrorException
Notice: Undefined index: tpl_dir

in 637850b4c77dc61801b9efcd0f6a5664557e626e_2.file.login.tpl.php line 33
at content_5c33ddc8a5a651_98543382(object(SmartyDevTemplate))
in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))
in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))
in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)
in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)
in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)
in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()
in Module.php line 2375
at ModuleCore->display('/var/www/vhosts/host/domain.com/modules/trackingfront/trackingfront.php', 'login.tpl')
in trackingfront.php line 169
at TrackingFront->displayLogin()
in stats.php line 35

**Comment by khouloudbelguith** [comment] 2019-02-27 07:09
Hi @igurina,

We are of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9780
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-27 07:09
Duplicate of #9780

**Closed as completed by khouloudbelguith** 2019-02-27 07:09 UTC
Labels: Duplicate
