### ISSUE TITLE
System is Translating "Class" Term To Turkish Meaning at Brands

### ISSUE THREAD

**Issue by burakgit** [PrestaShop/PrestaShop#20056] opened 2020-07-03 16:16 UTC
#### Describe the bug

Imagine that you are using Turkish Language, and the brand name is CLASS, it is translating it to turkish name "sınıf"
Class means sınıf but it is global brand name. 

#### Steps to Reproduce
create a brand name as Class Under Turkish System. Version 1.7.6.4
Front office, it writess CLASS no problem. 

![image](https://user-images.githubusercontent.com/32361879/86485484-7aec3800-bd61-11ea-9f2d-f6e264016309.png)

**Comment by sarahdib** [comment] 2020-07-06 08:58
Hello,

Using the last 1.7.6 I didn't reproduce.
<img width="1276" alt="Capture d’écran 2020-07-06 à 10 51 48" src="https://user-images.githubusercontent.com/3034677/86575023-eb1fd700-bf76-11ea-9347-a4ff655e7be6.png">
Maybe you are using the translation of your browser.


Despite our efforts, we were not able to reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop core bug.

I close this issue, feel free to open a new one.
Thank you!

**Closed as completed by sarahdib** 2020-07-06 08:58 UTC
Labels: Can't reproduce
