### ISSUE TITLE
Impossible to download PDF invoice for guest order

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#35537] opened 2024-03-01 11:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm creating this issue for @Hlavtox.

What's wrong?
- When you want to download an invoice via a standardized link `https://www.domain.com/index.php?controller=pdf-invoice&id_order=XXXX&secure_key=XXXX`, it doesn't work sometimes.
- The condition now says this: `if there is a customer in context and it doesn't match the order customer OR the secure key doesn't match`, die.
- So now if you have a perfectly legit link with secure_key, but you are logged in as different customer or start a guest checkout, the link won't work.
- So the fix is easy, die only if both of these fail:
  - If there is a customer in context and it's not the customer of the order.
  - If there isn't a secure key in the link.

### Expected behavior

I should be able to download the invoice.

### Steps to reproduce

- Make sure that some guest order exists in a shop and invoice is available for it.
- Go to FO, make sure you are logged out. Start a checkout as a guest (without password), no need to fill any addresses.
- Now go to guest tracking and try to track the order and try to download an invoice.
- You will get white screen and `The invoice was not found.`.
- Same situation is when you are logged in in FO as a different customer and you have the link to the invoice in the mail for example.

### PrestaShop version(s) where the bug happened

8.1.x

**Comment by florine2623** [comment] 2024-03-01 14:49
Hello @kpodemski ,

I tested on PS 8.1.x, I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/0d25f036-81e1-41d5-85f9-af4628ec99b3

I can download my invoice as a guest.
Am I missing something ?
Thanks!

**Comment by Hlavtox** [comment] 2024-03-01 14:54
@florine2623 You did not follow the steps to reproduce, you must have a different customer in the context -  `Start a checkout as a guest (without password), no need to fill any addresses.` :-)

Or, right click the link to download the invoice, save it somewhere. Then log in as a different customer and try to open that URL. Imagine you have this link in your inbox or something.

**Comment by florine2623** [comment] 2024-03-01 15:33
Hi again, 

Yes indeed I forgot some steps. 

But on the first try, I had no issue downloading the invoice. And when I tested a second time, I have the issue that you are mentioning :
<img width="1257" alt="Screenshot 2024-03-01 at 16 31 06" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ca7848d8-65c2-4399-ba01-dfb4c0d6ae89">

Thanks for the PRs.

I see that tehre's 2 PRs from @kpodemski and @Hlavtox . Which one should we test ? ^^

**Comment by Hlavtox** [comment] 2024-03-01 15:34
@florine2623 HA, good!!! :-)

The PR is mine, Krystian just created the issue. :-)

**Comment by Hlavtox** [comment] 2024-03-01 16:25
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35530

**Closed as completed by Hlavtox** 2024-03-01 16:25 UTC
Labels: Bug, Major, FO, Order, Ready, PR available, Verified, 8.1.x
