### ISSUE TITLE
Cart Rule restricted to visitor still in cart after registration

### ISSUE THREAD

**Issue by agnesdennetiere** [PrestaShop/PrestaShop#24863] opened 2021-06-08 10:53 UTC
Hello,

I created a cart rule restricted to the customer group "visitor", with no code, so it is added automatically to the cart.
When I login, the cart rule is removed (since I am not in the "visitor" group anymore)
However if I create an account, the cart rule stays in the cart until I update it (by adding a product, for example)

Prestashop version : 1.7.6.9

Thanks you for your help !

**Comment by agnesdennetiere** [comment] 2021-06-08 11:01
It seems that if I add this
```
CartRule::autoRemoveFromCart($this->context);
CartRule::autoAddToCart($this->context);
```

juste before the return in the submit function of the CustomerForm class, it works... (like in the CustomerLoginForm class)

Is this the right way?

**Comment by arouiadib** [comment] 2021-06-08 15:27
The code you mentionned do somehing and do the opposite just after that (at least from the method names).

Anyways, I don't think your changes will stay if you update your PS version in the future to a version that itself updated this class.

Finally, I think we should ask other people from product management if the cart rule should always stay. i.e should stay if the customer changes the status from "visitor" to "Logged in" AND from "visitor" to "Registed in" as well

**Comment by hibatallahAouadni** [comment] 2021-06-08 16:33
Hello @agnesdennetiere 

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- expected behavior
- steps to reproduce
- screenshots
- ...

Please respect and follow the provided template to submit a complete bug report.
You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by Hlavtox** [comment] 2021-06-09 19:52
Could be related to https://github.com/PrestaShop/PrestaShop/issues/19815

@agnesdennetiere Can you put {$customer.id_default_group} anywhere to any tpl file, for example to `templates/_partials/footer` and check the customer group id, after you register? Is it registered group id or visited group id?

**Comment by florine2623** [comment] 2021-06-29 08:42
Hello @agnesdennetiere ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-06-29 08:42 UTC
Labels: Bug, FO, Discounts, Cart rules, Customer groups, No change required, Checkout, 1.7.6.9
