### ISSUE TITLE
Product image upload limited to 2MB on 1.7.6.3

### ISSUE THREAD

**Issue by choclove90** [PrestaShop/PrestaShop#17745] opened 2020-02-19 16:11 UTC
**Describe the bug**
It seems that on PS 1.7.6.3 whenever I add/edit a product and try to add a new image, the limit is by default set at 2MB. I looked everywhere in the back office at the configuration options but I have not found this to be editable. After a few hours of looking up in the files I have found that in /src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/essentials.html.twig there is a data-max-size="{{ 'PS_LIMIT_UPLOAD_IMAGE_VALUE'|configuration }}" so I went directly in the database and modified PS_LIMIT_UPLOAD_IMAGE_VALUE to allow for bigger uploads.

Is this a mistake and PS_LIMIT_UPLOAD_IMAGE_VALUE is not configurable from back office or did I just miss it?

**To Reproduce**
1. Back office
2. Add/Edit Product
3. Upload any image > 2 MB
4. See error (tested on PS 1.7.6.3)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.3

**Comment by khouloudbelguith** [comment] 2020-02-19 16:16
Hi @choclove90,

We are awre of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15183
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-19 16:16
Duplicate of #15183

**Closed as completed by khouloudbelguith** 2020-02-19 16:16 UTC
Labels: Duplicate
