### ISSUE TITLE
Price TTC is incorrect in product catalog

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#27553] opened 2022-02-01 11:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the BO product page, for some products, the price including VAT is displayed as the price excluding VAT.

### Steps to reproduce

https://user-images.githubusercontent.com/51961329/151957112-3df7c5d7-4269-4d5b-a018-bf2ceac48c36.mp4

### PrestaShop version(s) where the bug happened

1.7.7.3

**Comment by marwachelly** [comment] 2022-02-01 17:21
Hello,

I didn't manage to reproduce the issue with 1.7.7.3 as it is shown in the screen record bellow
https://watch.screencastify.com/v/M05h0qllrv4mWEu9G3Wq

Did I miss some thing? Could you please check and feedback?

Thanks,

**Comment by Gaja-A** [comment] 2022-02-01 17:25
Hi @marwachelly,

Yes, in fact for some products, the TTC price displays correctly. Only for
few products, I'm facing this issue. I didn't know where it reproduce.
If you want, I can share you the access in private to look forward.

Regards,
Gaja

**Comment by florine2623** [comment] 2022-02-09 11:10
Hello @Gaja-A ,

You need to make sure the TAX in your product is the right one.
For example, I don't have a difference in tax incl and tax excl on this product :
<img width="1182" alt="Screenshot 2022-02-09 at 12 09 24" src="https://user-images.githubusercontent.com/16019289/153186639-ddec1180-c808-473c-8fdc-627ef6908a03.png">

Because there is no tax chosen :
<img width="299" alt="Screenshot 2022-02-09 at 12 08 11" src="https://user-images.githubusercontent.com/16019289/153186659-4d59225f-33f8-4556-965a-643823f553e4.png">

I will close this issue as it cannot be reproduced.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2022-02-09 11:10 UTC
Labels: Bug, BO, Taxes and Prices, 1.7.7.3, Invalid
