### ISSUE TITLE
ADD TO CART BUTTOM NOT WORKING IN ONE SHOP

### ISSUE THREAD

**Issue by sextoysunivers1964** [PrestaShop/PrestaShop#26945] opened 2021-12-10 13:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I have a multishop and in one of my shops, the italian one the add to cart buttom is not working in all pages.

I have inspected and seems to be a problem with a core.js. but I don't have the competences to solve it. I really wish !

Please check :

https://i.imgur.com/Z4Iup2T.png

Best regards,
Juan Carlos

### Expected behavior

Add to cart

### Steps to reproduce

https://sextoysunivers.it

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment] 2021-12-10 15:14
Hello,

The issue is not well detailed. There is no steps to reproduce it.

So, i will close the issue.

Thanks!

**Closed by HanaRebaiQA** 2021-12-10 15:14 UTC
Labels: Bug

**Comment by sextoysunivers1964** [comment] 2021-12-10 15:27
Hi Ana,

What you else you need to describe the issue. The add to cart buttom at sextoysunivers.it is not working in any page.

Do you need from me to show you how to clic to add to cart buttom ?

Best regards,
Juan Carlos

**Comment by HanaRebaiQA** [comment] 2021-12-10 15:34
Hello 

I did not manage the issue with classic theme. It seems that this issue is due to your theme.

Thanks!

**Comment by sextoysunivers1964** [comment] 2021-12-10 16:01
Hi Hana,

Sorry I've change your name.

Did you actually inspected yourself the add to cart buttom at sextoysunivers.it to get to that conclusion ?

Or is just from the screenshot that I've sent to you.

I'm asking you this because maybe I didn't inspected in a correct way.

Please tell me if that is the case or not.

If you didn't please try to do it before I contact the developper of the theme

Best regards,
Juan Carlos

**Comment by sextoysunivers1964** [comment] 2021-12-10 16:20
Hi Hanna,

I don't have the competences but I tried to inspect the add to cart buttom at sextoysunivers.it and seems that is not from the actual theme but instead from the core.js

https://sextoysunivers.it/themes/core.js

Best regards,
Juan Carlos
