### ISSUE TITLE
Strange behavior in Image slider Module in Mozilla Firefox

### ISSUE THREAD

**Issue by adpu** [PrestaShop/PrestaShop#31281] opened 2023-02-08 16:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have a prestashop website and Im using the Image slider Module ( https://addons.prestashop.com/en/sliders-galleries/22320-image-slider.html ), I detected an issue in firefox browser. This issue is that If you are in firefox in the page where you have the slideshow, and you scroll down, if you are in the middle of the page, the page jump to down and up automatically, without touch nothing. I think that this issue is when slide change. Im tried in a fresh installation with default theme, and is the same issue. In this link you can watch a video of this issue: https://www.veed.io/view/88453afc-9b04-41e1-8432-27e732cef0a7?sharingWidget=true&panel=share

My Mozilla Firefox version is 109.0.1 (64-bit)
Im using MAC Operation System

### Expected behavior

The expected is the same behavior that in Safari or Chrome. If you scroll to the middle of page, the page keep static without jumps

### Steps to reproduce

1. Open Firefox mozilla browser
2. Open website
3. Go to page where you have Image Slider module
4. Scroll down to the middle of page
5. Stop and wait 
6. Automatically in a few seconds the page jump to up and to down. The page scroll up and down

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_imageslider v3.1.1

**Comment by HanaRebaiQA** [comment] 2023-02-09 14:15
Hello @adpu 

Thanks for your report.
I tried to reproduce your issue using the same steps to reproduce on **PS1788** with **php7.4** and using the **ps_imageslider v3.1.1** module, but I was unable to reproduce it.

https://user-images.githubusercontent.com/92912932/217836823-33dc1f3e-d5f0-4707-a5aa-04e00f1d9616.mp4


You mentioned that you used php8.0 with PS1788. Or, PS1788 is not compatible with this php version (8.0)

Here is my server information : 

- Server information: Linux # 64~20.04.1-Ubuntu 
- Server software version: Apache/2.4.52 (Debian)
- PHP version: 7.4.27
- Memory limit: 128M
- Max execution time: 30
- Upload Max File size: 10000M
- Browser : Mozzila Firefox for Ubuntu Version 109.0.1

Could you please check again ?

Thank You!

**Comment by adpu** [comment] 2023-02-09 16:05
Hi Hana,

Im sorry my version is not 8.0, I have wrong the version in the previous
email. I attach you my server info:

Server: Linux #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP version: 7.4.33
Memory limit: 256M
Max execution time: 30
Upload MAx File size: 20M
Browser: Mozilla Firefox for Mac Version 109.0.1 (64-bit)

Thanks

Missatge de Hana REBAI ***@***.***> del dia dj., 9 de febr.
2023 a les 15:15:

**Comment by hibatallahAouadni** [comment] 2023-02-15 12:51
Hello @adpu 

Thanks for your feedback and your patience 🙏 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or navigator problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-02-15 12:51 UTC
Labels: Bug, FO, Imageslider, Invalid, Module, 1.7.8.8
