### ISSUE TITLE
Prestashop Backoffice does not load most of items after upgrade 1.7.5.2 - 1.7.6

### ISSUE THREAD

**Issue by Marko-fin** [PrestaShop/PrestaShop#14624] opened 2019-07-13 02:08 UTC
**Describe the bug**
After upgrading from 1.7.5.2 to 1.7.6 using 1-click-upgrade most of Backoffice items do not load, this is majority of items in Backoffice sidebar menu. After clicking eg. Catalog - Products, Products page is loaded, but content shown is empty, just blank page without anything.

My shop is in maintenance mode, and when opening the shop Frontend, I can see all how it was also in 1.7.5.2. Also MySQL database has all items in tables.

Some Backoffice pages work (very few), like Catalog - Attributes.

When looking browser developer tools, I can see requested URL format is different for those Backoffice areas that work, and those that do not.

Like Catalog - Attributs that loads properly, and its URL looks like this:
..../index.php?controller=AdminAttributesGroups&token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 

but like Catalog - Products, that fails to show anything, the URL looks like this:
..../index.php/sell/catalo﻿g/products?_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx﻿xxxx 

And same patters seem to be for all working and non-working pages atfer upgrade to 1.7.6, working pages has url format "...index.php?controller=...." and "...&token=".

**To Reproduce**
1. Go to 'Prestashop Backoffice'
2. Click on 'Catalog - Products'
4. Products are not listed on page

**Screenshots**
Find screenshots from
Catalog - Products

![prestashop-1-7-6-catalog-products](https://user-images.githubusercontent.com/52843932/61165660-97c1a700-a523-11e9-8c90-461ed0d5729a.jpg)

Advanced - Information

![prestashop-1-7-6-advanced-information](https://user-images.githubusercontent.com/52843932/61165658-97c1a700-a523-11e9-87f4-c51145b8593a.jpg)

Catalog - Attributes

![prestashop-1-7-6-catalog-atributes](https://user-images.githubusercontent.com/52843932/61165659-97c1a700-a523-11e9-9fbf-e7d439f96672.jpg)

**Additional information**
PrestaShop version: 1.7.6
PHP version: php5-common (5.6.40+dfsg-0+deb8u4)

**Comment by Marko-fin** [comment] 2019-07-13 12:22
I have restored whole /var/www/prestashop folder from tar.gz. Version is back to 1.7.5.2 and all works again normally.

Here is advanced - information

**Server information**
Server information Linux #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64
Server software version: Apache
PHP version: 5.6.40-0+deb8u4
Memory limit: 512M
Max execution time: 300
Upload Max File size: 50M

**Database information**
MySQL version: 5.5.62-0+deb8u1
MySQL server: localhost
MySQL name: prestashop
MySQL user: pshop
Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPDO

 **Check your configuration**
Required parameters: OK
Optional parameters: OK

But something is not working at all from upgrade from 1.7.5.2 to 1.7.6 with 1-click-upgrade tool

**Comment by Amulliez** [comment] 2019-07-15 08:50
Hello @Marko-fin 

I have exactly the same problem after upgrading from 1.7.5.2 to 1.7.6 using 1-click-upgrade. I hope we will have answers quickly.

**Comment by Quetzacoalt91** [comment] 2019-07-15 08:55
Hi,

This issue is caused by a old version of the autoupgrade module. There is currently a conflict between the twig versions included by the core and the module.

As you cannot upgrade the module, you can instead safely remove it by deleting the folder `modules/autoupgrade`. You will recover your BO immediately.

As this issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/13633, I'm closing it.

**Closed as completed by Quetzacoalt91** 2019-07-15 08:55 UTC

**Comment by Marko-fin** [comment] 2019-07-15 22:05
Thanks!

Renamed backup restored 1.7.5.2 version to temporary to something else, and restored renamed prestashop-176 folder to prestashop. Renamed modules/autoupgrade -> modules/_autoupgrade

All is loading fine now.
