### ISSUE TITLE
1-Click Upgrade v5.0.2 

### ISSUE THREAD

**Issue by DzieckoExpert** [PrestaShop/PrestaShop#36330] opened 2024-06-07 16:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

after module update to 5.0.2 i see this when i try to cofigure a module: Argument 2 passed to PrestaShop\Module\AutoUpgrade\UpgradeSelfCheck::__construct() must be an instance of PrestaShop\Module\AutoUpgrade\PrestashopConfiguration, string given, called in /home/utfhrjdobw/domains/dzieckoexpert.pl/public_html/modules/autoupgrade/AdminSelfUpgrade.php on line 497

[TypeError 0]

### Steps to reproduce

try to open module in PS

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

7.4.33

**Comment by jak78** [comment] 2024-06-08 17:51
Same on PHP 8.1 & Prestashop 8.1.6: 

```
PrestaShop\Module AutoUpgrade\UpgradeSelfCheck::_construct): Argument #2 ($prestashopConfiguration) must be of type
PrestaShop|Module\AutoUpgrade\PrestashopConfiguration, string given, called in <<undisclosed-path>>/modules/autoupgrade/AdminSelfUpgrade.php on line 497
[TypeError 0]
```

**Comment by 14hkr** [comment] 2024-06-09 08:35
Same here

**Comment by venditdevs** [comment] 2024-06-10 06:50
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/36317

Solution is provided there.

**Comment by paulnoelcholot** [comment] 2024-06-11 09:26
Hello @DzieckoExpert,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #36317.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment] 2024-06-11 09:26
Duplicate of #36317

**Closed as completed by paulnoelcholot** 2024-06-11 09:26 UTC
Labels: Bug, Duplicate
