### ISSUE TITLE
[autoupgrade] cli upgrade 8.1.2 > 8.1.3 fails on db upgrade

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#34987] opened 2024-01-06 17:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When upgrading PrestaShop 8.1.2 to 8.1.3 using autoupgrade module with command line, the database upgrade fails:

> INFO - === Step upgradeDb
INFO - Cleaning file cache
INFO - Running opcache_reset
INFO - Initializing required environment constants
INFO - Checking version validity
ERROR - Error during database upgrade. You may need to restore your database.
ERROR - [ERROR] Version to install is too old. Current version: 8.1.3.0. Version to install: 8.1.3.

### Steps to reproduce

1. Install PS 8.1.2
2. Install the autoupgrade module
3. Manually unzip PS 8.1.3
4. Run command line: `php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --channel=private --action=upgradeDb`

### PrestaShop version(s) where the bug happened

8.1.3

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.0

**Comment by Seb33300** [comment] 2024-01-06 17:43
Here is the PR to fix that issue: https://github.com/PrestaShop/autoupgrade/pull/661

**Comment by florine2623** [comment] 2024-01-08 09:57
Hello @Seb33300 ;

Following the steps you shared, I can't reproduce your issue on my end.
<img width="560" alt="Screenshot 2024-01-08 at 10 55 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/88f4f5df-8154-4ab2-a182-1edc25906fc2">

Is there something else I can try ?

**Comment by Seb33300** [comment] 2024-01-08 10:13
Hi @florine2623,

Weird, from which version are you upgrading?

**Comment by florine2623** [comment] 2024-01-08 10:51
8.1.2 to 8.1.3 like you mentioned

**Comment by Seb33300** [comment] 2024-01-10 11:46
I think I found what's wrong.

I am able to reproduce it without failure but when adding some `var_dump` I can see that compared versions are not correct.
It tries to compare `8.1.2.0` instead of `8.1.2`:

![image](https://github.com/PrestaShop/PrestaShop/assets/915273/17f67330-c097-4fd9-9c10-4e745f5d42f8)


In my case, it fails because I upgraded to PS 8.1.2 and the autoupgrade module installed SQL migrations of 8.1.3 because of the version comparaison that failed. (because of the extra `.0` added to 8.1.2.0)
After that, whn I tried to upgrade to 8.1.3, that error occured.

You can reproduce it that way:

1. Install the latest version of PrestaShop
2. Install the autoupgrade module
3. Run command line: php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --channel=private --action=upgradeDb
4. See error

Module autoupgrade should skip migration and shows message `You already have the %s version.`.
But it will fail with the same error message as in my first post.

My PR fixes the issue by preventing to add an extra `.0` to version 8+

**Comment by Seb33300** [comment] 2024-01-10 12:09
Updated my previous message to clarify with a simplier example.

**Comment by paulnoelcholot** [comment] 2024-01-10 19:47
Hello @Seb33300,

I reproduce the issue with PrestaShop version 8.1.3, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/fd5a304f-dd9c-4986-93af-a7a863a6b518)

**Comment by Seb33300** [comment] 2024-01-11 01:18
@paulnoelcholot, as I said, I already created a PR to fix the issue.
The fix just need to be tested: https://github.com/PrestaShop/autoupgrade/pull/661

**Closed as completed** 2024-01-25 12:01 UTC
Labels: Bug, Autoupgrade, Verified
