### ISSUE TITLE
Warning message after upgrade presatshop 8.1.6

### ISSUE THREAD

**Issue by openpresta** [PrestaShop/PrestaShop#36234] opened 2024-05-25 02:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrade many prestashop from 8.1.5 to 8.1.6 ; same problem 
![Capture d’écran 2024-05-25 à 3 03 24 AM](https://github.com/PrestaShop/PrestaShop/assets/30599677/ebd0a42a-5aa9-4352-b2ef-7b5f552db2c8)

### Steps to reproduce

just upgrade with the module autoupgrad version 5.0.2 

### PrestaShop version(s) where the bug happened

8.1.6 

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by Hlavtox** [comment] 2024-05-25 10:14
Obviously something is wrong with your URL configuration. And without providing it, nobody here can help you.

**Comment by openpresta** [comment] 2024-05-25 10:43
All shop upgraded same error not only one

**Comment by openpresta** [comment] 2024-05-25 10:44
the warning show only in AdminDashboard

**Comment by Hlavtox** [comment] 2024-05-25 11:19
@openpresta I upgraded about 20 stores and never got an issue like this, the same for hundreds and thousands of other users. Something is wrong with your config, you are connecting from a different domain, www or non www variant, maybe something wrong with SSL, something.

Send a screenshot of the URL you are connecting with, send a screenshot of your URL configuration in prestashop, then someone can maybe help you. :-)

**Comment by openpresta** [comment] 2024-05-25 23:18
https://github.com/PrestaShop/PrestaShop/assets/30599677/7ba6cc19-d219-458c-883c-5572a2856c63


https://github.com/PrestaShop/PrestaShop/assets/30599677/b862af68-b320-4469-b033-9d80d99b2624

**Comment by paulnoelcholot** [comment] 2024-05-28 09:55
Hello @openpresta ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-05-28 09:55 UTC
Labels: Bug, Can't reproduce
