### ISSUE TITLE
[PrestaShopException]

### ISSUE THREAD

**Issue by Klixa-Web** [PrestaShop/PrestaShop#10305] opened 2018-09-06 07:14 UTC
I get this, when I try to load cart page in BO:

[PrestaShopException]

Invalid address #6252
at line 444 in file classes/Address.php

439.             // if an id_address has been specified retrieve the address
440.             if ($id_address) {
441.                 $address = new Address((int)$id_address);
442. 
443.                 if (!Validate::isLoadedObject($address)) {
444.                     throw new PrestaShopException('Invalid address #'.(int)$id_address);
445.                 }
446.             } elseif ($with_geoloc && isset($context->customer->geoloc_id_country)) {
447.                 $address             = new Address();
448.                 $address->id_country = (int)$context->customer->geoloc_id_country;
449.                 $address->id_state   = (int)$context->customer->id_state;

    AddressCore::initialize - [line 197 - classes/tax/Tax.php] - [1 Arguments]
    TaxCore::getProductEcotaxRate - [line 767 - classes/Cart.php] - [1 Arguments]
    CartCore->getProducts - [line 1866 - classes/Cart.php]
    CartCore->getOrderTotal - [line 1782 - classes/Cart.php] - [2 Arguments]
    CartCore::getTotalCart - [line 869 - controllers/admin/AdminCartsController.php] - [3 Arguments]
    AdminCartsControllerCore->getOrderTotalUsingTaxCalculationMethod - [line 335 - classes/helper/HelperList.php] - [2 Arguments]
    HelperListCore->displayListContent - [line 164 - classes/helper/HelperList.php]
    HelperListCore->generateList - [line 929 - controllers/admin/AdminCartsController.php] - [2 Arguments]
    AdminCartsControllerCore->renderList - [line 2082 - classes/controller/AdminController.php]
    AdminControllerCore->initContent - [line 255 - classes/controller/Controller.php]
    ControllerCore->run - [line 428 - classes/Dispatcher.php]
    DispatcherCore->dispatch - [line 99 - admin/index.php]

**Comment by khouloudbelguith** [comment] 2018-09-06 07:40
Hi @Klixa-Web,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9782
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-06 07:40
Duplicate of #9782

**Closed as completed by khouloudbelguith** 2018-09-06 07:40 UTC
Labels: Duplicate

**Comment by MathiasReker** [comment] 2018-09-12 21:53
I can't reproduce this bug on 1.7.4.2. @khouloudbelguith can you make a screenrecord, then I will see if I can fix it?
