### ISSUE TITLE
Slow edit product

### ISSUE THREAD

**Issue by tarasklymets** [PrestaShop/PrestaShop#19475] opened 2020-05-30 23:49 UTC
https://skr.sh/v2QXe2Xhh91
Other sections load quickly. The old site on version 1.6 loads quickly when editing the product. Can I hide categories, as was in 1.6?

**Comment by tarasklymets** [comment] 2020-05-30 23:59
![image](https://user-images.githubusercontent.com/16720338/83341322-b91db400-a2ea-11ea-92e1-3f69d2d6e450.png)

**Comment by tarasklymets** [comment] 2020-05-31 00:00
![image](https://user-images.githubusercontent.com/16720338/83341326-cf2b7480-a2ea-11ea-9743-ac3df44d1356.png)
As it was in 1.6

**Comment by florine2623** [comment] 2020-06-01 13:37
Hi @tarasklymets ,

You can click "collapse" to hide the categories.
![Capture d’écran 2020-06-01 à 15 35 58](https://user-images.githubusercontent.com/16019289/83414380-b1126100-a41d-11ea-86c0-cdd96c921a95.png)
Is that what your issue is about ?
Please check and let me know !

**Comment by tarasklymets** [comment] 2020-06-01 13:45
The problem is that the site wants to display all 7000 categories, in 1.6 it worked somehow differently.

How do I make collapsed categories when entering editing? To make the page load faster. Or can I make a video of the difference in speed of 1.6 and 1.7?

PrestaShop 1.6 very fast https://skr.sh/v2STKMcje4L
PrestaShop 1.7 very slow https://skr.sh/v2SK5Qu6vQq

Most likely it is already difficult for the browser to display 7000 categories at once. The load on the server is minimal.

**Comment by MatShir** [comment] 2020-06-03 14:43
@tarasklymets for your feedback, indeed there is a huge performance issue. 
I suggest continuing the discussion on this issue #14955. Tell us your thoughts on it. The issue will be close because it is a duplicate of #14955


We are aware of this issue, it is already in our debug backlog.
To be informed when it’s fixed, please subscribe to the issue above.

Thank you!

**Closed as completed by MatShir** 2020-06-03 14:43 UTC
Labels: BO, Duplicate
