### ISSUE TITLE
Product flag “new” is untranslatable

### ISSUE THREAD

**Issue by thebodzio** [PrestaShop/PrestaShop#33836] opened 2023-09-05 00:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In https://github.com/PrestaShop/PrestaShop/blob/482af6462a9d319290ef767eee45bd59aaf4c43d/src/Adapter/Presenter/Product/ProductLazyArray.php#L511-L516 label for the flag “new” is attempted to be sourced from `Shop.Theme.Global` which makes it basically untranslatable, since `Shop.Theme.Global` does not have such entry. There is a suitable string in `Shop.Theme.Catalog`.

Frankly speaking, this appears to be a simple mistake, especially since almost all of the neighbouring strings are sourced from `Shop.Theme.Catalog` domain.

### Expected behavior

Label for the “new” flag is translatable with BO translation tools.

### Steps to reproduce

Try to translate string “New” from `Shop.Theme.Global` using BO translation facility. Good luck! 😉

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.2.7

**Comment by thebodzio** [comment] 2023-09-05 00:55
Related PR: #33837

**Comment by kpodemski** [comment] 2023-09-05 06:25
Thank you, @thebodzio. I'm closing this issue since it's a duplicate of https://github.com/PrestaShop/PrestaShop/issues/33780

**Closed as completed by kpodemski** 2023-09-05 06:25 UTC
Labels: Bug, Duplicate

**Comment by thebodzio** [comment] 2023-09-05 09:05
@kpodemski Yeah, sorry for the duplicate. FYI: I really did use the notorious search field 😊
