### ISSUE TITLE
Combination update through CSV import (PS 1.7.8.8)

### ISSUE THREAD

**Issue by S-Zicari** [PrestaShop/PrestaShop#36061] opened 2024-04-30 10:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to update a single field (for example the EAN) in combinations leads to almost every field blanked in the specific combination: quantity, prices, MPN, virtually every field excepting the availability date (that will we overwritten with the today's date) and reference (but I am using the "use reference as key", so it is probable that it has been overwritten with the same data).

It works flawlessly with simple products, but it really doesn't with combinations. What am I doing wrong?

### Expected behavior

Combinations data untouched, excepting the single field (l'et's say columns in the CSV file) mapped with the new data we want to update/overwrite.

### Steps to reproduce

1 - Prepare CSV file with base product ID, base product Reference, combination reference, attributes and attributes value and the field you'd like to update/fill (let's say the EAN number)
2 - Import the file selecting Combinations in the dropdown and "use reference number as keyword"
3 - Map the file with this columns: ID (probably not necessary), base product Reference, combination reference, attributes and attributes value, EAN number
4 - wait for the procedure to complete, no errors.
5 - check the product/s you updated. You'll see that every updated combination has almost all the fields blanked out, with some exceptions.

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by S-Zicari** [comment] 2024-04-30 14:43
Let me know if there is some information that you need. Thanks in advance for the help

**Comment by florine2623** [comment] 2024-05-14 07:49
Hi @S-Zicari ,

It seems like your issue has already been reported here : https://github.com/PrestaShop/PrestaShop/issues/23083

Please check and confirm.
Thanks!

**Comment by S-Zicari** [comment] 2024-05-14 08:18
Hello @florine2623 , yes, it seems to be the same issue. Even tho the OP didn't use the "use reference as key" because of it's specific needs. The topic has been created in 2021 (the other one in 2019), but I didn't understand if it has been fixed or not.

Thank you for your help.

**Comment by florine2623** [comment] 2024-05-14 12:51
It has not been fixed yet.
If the issue is fixed, you will see it Closed, you will see the PR related and the label Fixed on it ^^

I will close your issue to avoid clogging the backlog.
Thanks!

**Closed as completed by florine2623** 2024-05-14 12:51 UTC
Labels: Bug, BO, Duplicate, Import / Export, Combinations, 1.7.8.8
