### ISSUE TITLE
New sentences in the email theme are not added to the translation system

### ISSUE THREAD

**Issue by AimSai59** [PrestaShop/PrestaShop#27169] opened 2022-01-03 03:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I create a new email theme, with phrases that are not already present in the Modern theme for example, the new phrases are not added to the email translation system in appearance > email theme > Translate emails.

the only way to add the translations is to do it manually in the database by adding one by one the sentences in prefix_translation

### Expected behavior

The new sentences should automatically appear in the list of sentences to translate once the new email theme is selected.

### Steps to reproduce

- Create a new email theme containing custom phrases like {{ 'go to the store'|trans({}, 'Emails.Body', locale)|raw }} and copy it to root/mails/themes
- Activate the new theme in appearance > email theme
- Regenerate or not the emails (it doesn't change anything anyway)
- Go to appearance > email theme > email translation and choose a language, any language
- The sentence "go to the store" does not appear in the translatable sentences

### PrestaShop version(s) where the bug happened

1.7.8.1

**Comment by hibatallahAouadni** [comment] 2022-01-03 15:45
Hello @AimSai59 

Your issue seems related to this one #22968
Please check and feedback.

Thanks!

**Comment by AimSai59** [comment] 2022-01-03 16:01
Hi @hibatallahAouadni !

It's not really that. My theme is perfectly taken into account from header to footer. 

Only the sentences other than those already present in the provided themes (classic or modern) are not added to the translation system in **appearance > email theme > email translation**. 

I have to generate my new emails, then go to **localization > translation > email translation** and edit the generated emails in each language.
In this case, variables like `{{ 'go to the store'|trans({}, 'Emails.Body', locale)|raw }}` which are in the theme files, are no longer useful :-/

Thank you

**Comment by hibatallahAouadni** [comment] 2022-01-06 11:17
Hello @AimSai59 

Could you please provide a screen record to understand better the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-25 11:05
Hello @AimSai59 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-25 11:05 UTC
Labels: Bug, BO, Translations, Email theme, Invalid

**Comment by mavalentin** [comment] 2022-05-06 15:46
Hello, I have the same issue, the description of the issue is exactly as described by @AimSai59. 
I have added a new mail theme in /mails/themes, and have added a new translatable sentence in one of the .twig files.
![Unbenannt2](https://user-images.githubusercontent.com/16594586/167166375-1c2da243-87a7-4f6d-9d02-5efca49b21a7.PNG)
As you can see from my screenshot, the new sentence is "Hi {customer_company_name},".
![Unbenannt1](https://user-images.githubusercontent.com/16594586/167166464-12203b89-ccef-46c5-bc0c-ed41f583efc8.PNG)

If I go in Backoffice to Design->Email Theme->Translate Emails and select another language to which I want to translate this sentence, f.ex. Italian, the sentence should show up, but it does not, as you can see
![Unbenannt3](https://user-images.githubusercontent.com/16594586/167167013-b99221fa-883d-4a6b-a6c3-4365beaeb7bd.PNG)

I cannot find any other interface to translate the contents of custom email themes
