### ISSUE TITLE
[BO] [RTL] Bad display of categories list on Product (V2) edit page 

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#25991] opened 2021-09-24 14:45 UTC
Hello,

#### Describe the bug

In Product (V2) edit page (RTL language), categories list has invalid padding direction, checkbox overflow and bad radio button placement.

This is what we get:
![Screenshot 2021-09-24 171433](https://user-images.githubusercontent.com/85633460/134693093-c5ead505-a6d1-4611-9e27-f15cb43ab985.png)

#### Expected behavior

This is what we expect:
![Screenshot 2021-09-24 171622](https://user-images.githubusercontent.com/85633460/134693234-7c12c2b4-8a59-472f-8091-c6d8cce183d3.png)

#### Steps to Reproduce

1. Go to BO > Products
2. Select a product to edit
3. Switch to experimental product page
4. Go to categories section

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by khouloudbelguith** [comment] 2021-09-24 16:15
Hello @mparvazi,

I manage to reproduce the issue with PS1.7.8.0rc.
![image](https://user-images.githubusercontent.com/16067358/134707647-afbdc7b2-baa5-4c72-8d3c-e20269f43a77.png)
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

**Closed as completed** 2021-10-01 17:34 UTC
Labels: Bug, Minor, BO, Fixed, Front-end, PR available, 1.7.8.0
