### ISSUE TITLE
This payment method is not available

### ISSUE THREAD

**Issue by rnervi** [PrestaShop/PrestaShop#10304] opened 2018-09-06 06:33 UTC
**Describe the bug**
shop customer chooses "pay by bank wire" or "pay by check"

**To Reproduce**
1. Go to 'checkout'
2. Click on '4 payment'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version:  1.7.4.2 
PHP version: 7.2.8 

I've seen there was an old issue BOOM-5518 gone lost
All setups has been checked twice

**Comment by khouloudbelguith** [comment] 2018-09-06 07:36
Hi @rnervi,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by rnervi** [comment] 2018-09-06 08:11
apache log:
Wed, 05 Sep 2018  22:53:00 GMT [notice] - www.komorebisnc.it - AH00163: Apache/2.4.34  (Unix) configured -- resuming normal operations
--
Wed, 05 Sep 2018 22:53:00 GMT [notice] - www.komorebisnc.it - AH00094: Command line: '/apache/bin/httpd -D FOREGROUND'
Wed,  05 Sep 2018 21:58:00 GMT [notice] - www.komorebisnc.it - AH00163:  Apache/2.4.34 (Unix) configured -- resuming normal operations
Wed, 05 Sep 2018 21:58:00 GMT [notice] - www.komorebisnc.it - AH00094: Command line: '/apache/bin/httpd -D FOREGROUND'

----------------------
[dev.log](https://github.com/PrestaShop/PrestaShop/files/2356153/dev.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/2356154/prod.log)
[console.txt](https://github.com/PrestaShop/PrestaShop/files/2356159/console.txt)




Server information Linux #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64
Server software version: Apache
PHP version: 7.2.8
Memory limit: 256M
Max execution time: 120
Upload Max File size: 25M
PrestaShop version: 1.7.4.2 
MySQL server: 89.46.111.66:3306 

no clues from debug=on on frontside

**Comment by khouloudbelguith** [comment] 2018-09-06 08:20
Hi @rnervi,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
If you don't have it, you should ask your hosting provider.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by rnervi** [comment] 2018-09-06 08:37
aske hoster for log. 
q: where is the "debug mode report" to be found ?

**Comment by khouloudbelguith** [comment] 2018-09-06 08:41
Hi @rnervin,

When debug mode is enabled, when you navigate to the checkout page and you try chooses "pay by bank wire" or "pay by check", there is no exception displayed?

Best regards, Khouloud

**Comment by rnervi** [comment] 2018-09-06 08:42
exact. blank page with just This payment method is not available. upper left corner
shop is still "under maintenance" im entering as admin from backoffice to frontoffice to test

**Comment by khouloudbelguith** [comment] 2018-09-06 08:44
Hi @rnervi,

Could you please try to re-install the payment method module and feedback.

Best regards, Khouloud

**Comment by rnervi** [comment] 2018-09-06 08:50
removed both with "clean folder" option on.
reinstalled. 
recfg both modules.
WORKED !

this installation comes from an update from 1.6
probably modules has some issues and need to be updated too

**Comment by khouloudbelguith** [comment] 2018-09-06 08:53
Hi @rnervi;

Thanks for the feedback.
Since it is fixed, I will close the issue.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-06 08:53 UTC
Labels: Bug, FO, Payment methods, Fixed, 1.7.4.2

**Comment by rnervi** [comment] 2018-09-06 08:55
ty. 
just notice this fact to update team.
also I had to manually touch the table permissions (some days ago) as some menu was not opening after update (found a 1,7 table in a forum and replaced)

**Comment by khouloudbelguith** [comment] 2018-09-06 09:04
Hi @rnervi,

This issue is reported here #9513.

Thanks & best regards, Khouloud

**Comment by xiropot** [comment] 2019-06-04 10:17
@rnervi @khouloudbelguith Also some kind of this behavior can happen when we code modules specialized for checkout/carriers/payment because we may have missed the id_state/id_country field in the record creation. As a result, 💀 error.
