### ISSUE TITLE
Customers can order products which do not have an available carrier for their country

### ISSUE THREAD

**Issue by mrl22** [PrestaShop/PrestaShop#22804] opened 2021-01-13 14:26 UTC
#### Describe the bug

We have an issue where we have select products that can not be shipped internationally. If a customer located outside of the UK purchases one of these items which has no international carrier along with a product which does, Prestashop will allow the order to go through with no notification to the customer. This also results in the order being split into two orders inside the Prestashop admin. There are other weird things that happen regarding PayPal/WorldPay API due to there being two orders, but I won't go into that here.

#### Expected behaviour

When a customer tries to order an item with no carrier along with an item that does have a carrier, the customer should be returned to the cart identifying products in their basket that can not be shipped to their location.

OR

A notification on choosing a shipping method that there are one or more items in their basket which can not be shipped to their location with maybe a bullet-pointed list of these identified products.

#### Steps to Reproduce

Being located in the UK and using Ireland as an example: In the admin, we have created a separate zone called "EU - Ireland" and moved the country "Ireland" from "UK Mainland" to the "EU - Ireland" zone. In Shipping carriers, we have a carrier called "Standard Delivery" which has pricing for "UK Mainland" zone and also "International Standard Delivery" which contains all international locations including "EU - Ireland".

Create two products:
1. First product tick available carrier "Standard Delivery" only. (Only allowed to be posted inside the UK)
2. Second product tick available carrier "Standard Delivery" and "International Standard Delivery". (Allowed to be posted inside the UK and Internationally)

When adding the first product to your basket on its own and choosing "Ireland" as your delivery country, the shipping method tab says "Unfortunately, there are no carriers available for your delivery address.". If you then go back to add the second product and follow the checkout process again, the shipping method tab will display "International Standard Delivery" and will allow you to checkout as normal for both items.

In the admin, the order is split into two successful orders. This creates a headache as we have to contact the customer and tell them that we can not ship one of the items to their country.

#### Screenshots

[Screenshot 1](https://cdn.discordapp.com/attachments/572912019221774362/798958075087159346/1.JPG)
[Screenshot 2](https://cdn.discordapp.com/attachments/572912019221774362/798958071992418334/2.JPG)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.34-8

**Comment by mrl22** [comment] 2021-01-13 16:56
I have set up a complete fresh install on PS 1.7.7.1 which highlights this issue. [http://presta.devfwd.com/](http://presta.devfwd.com/) 

1. Add product "UK ONLY SHIPPING PRODUCT (NO INTERNATIONAL CARRIERS)" to your cart.
2. Add product "INTERNATIONAL PRODUCT (CAN BE SHIPPED ANYWHERE)" to your cart.
3. Check out all the way to "Shipping method" and use the delivery country "Ireland" along the way.

[Screenshot 1](https://cdn.discordapp.com/attachments/572912019221774362/798958075087159346/1.JPG)
[Screenshot 2](https://cdn.discordapp.com/attachments/572912019221774362/798958071992418334/2.JPG)

**Comment by hibatallahAouadni** [comment] 2021-01-13 18:41
Hello @mrl22 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15159. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-13 18:42
Duplicate of #15159

**Closed as completed by hibatallahAouadni** 2021-01-13 18:41 UTC
Labels: Duplicate
