### ISSUE TITLE
Webservice API "product_type" field comes empty problem

### ISSUE THREAD

**Issue by kemalatila** [PrestaShop/PrestaShop#28826] opened 2022-06-23 10:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I create products from panel then I get products from Webservice but product_type comes as empty string. 

### Steps to reproduce

 create products from panel and list from Webservice API

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.2

**Comment by sLorenzini** [comment] 2022-06-23 12:30
Hello @kemalatila,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 

Could you provide us more steps with details and screenshots or screenrecord to reproduce this issue please 🙏? 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by hibatallahAouadni** [comment] 2022-07-18 14:43
Hello @kemalatila 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-07-18 14:43 UTC
Labels: Bug, CO, Webservice, Invalid, 1.7.8.6
