### ISSUE TITLE
is the virtual_uri buggy?

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#34383] opened 2023-10-25 14:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The virtual_uri field is a rather obscure field in the ps_shop_url table. In this Github there is just one post where it is even named.

The field is supposed to provide altenative urls for the frontside. However, there is now a complaint on the forum that is changing some backoffice links too - with a resulting dysfunction.

See: https://www.prestashop.com/forums/topic/1081141-no-input-file-specified-backoffice-url-prefix-is-not-working/

### Expected behavior

No effect in the backoffice

### Steps to reproduce

Set up virtual_uri's in a multishop configuration.
Go to the carriers page

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-10-25 14:37
Hello @musicpanda ,

I tested on a multistore with `develop` branch.

<img width="645" alt="Screenshot 2023-10-25 at 16 35 05" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e8cac830-7144-4d89-a006-498ec698a523">

I can't reproduce the issue. The link for carriers and other elements on the BO is always : `myshop.com/adminXXX` even when I'm in a shop context in particular.

https://github.com/PrestaShop/PrestaShop/assets/16019289/680eda4a-8295-439a-a69e-b3f902d96fc0

**Comment by florine2623** [comment] 2023-11-13 10:40
Hello ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-11-13 10:40 UTC
Labels: Bug, BO, Multistore, 8.1.x
