### ISSUE TITLE
Errore 500 - "Il file tmp / XXXX non esiste"

### ISSUE THREAD

**Issue by AntonioManta** [PrestaShop/PrestaShop#12144] opened 2019-01-14 11:24 UTC
After upgrading to 1.7.5 with autoupgrade, when you try to upload an image in the product section: you get error 500. I've checked the tmp folder and wasn't there after the upgrade, so I created it with 755 perm.
![50982285-2580f300-14fd-11e9-8967-f7adb24b9105](https://user-images.githubusercontent.com/46569923/51110014-4eec9800-17f7-11e9-9287-31aa28505b28.jpg)
![50982286-2580f300-14fd-11e9-8d8b-eb2b0d8a10c0](https://user-images.githubusercontent.com/46569923/51110015-4eec9800-17f7-11e9-8a04-ae2ad1602477.jpg)
![50982287-26198980-14fd-11e9-9d99-b73fe29cabc3](https://user-images.githubusercontent.com/46569923/51110016-4eec9800-17f7-11e9-92e5-f43a8f77bb2b.jpg)
![50982288-26198980-14fd-11e9-8a4d-1cd98f301f17](https://user-images.githubusercontent.com/46569923/51110017-4eec9800-17f7-11e9-88f7-41708486e08b.jpg)

**Comment by PierreRambaud** [comment] 2019-01-14 11:38
If you don't have the permission, you must be sure your apache user have the right to write in this directory.

**Comment by AntonioManta** [comment] 2019-01-14 11:48
Already checked

**Comment by marionf** [comment] 2019-01-14 12:59
Duplicate of #11939

**Closed as completed by marionf** 2019-01-14 12:59 UTC
Labels: Duplicate
