### ISSUE TITLE
Hidden price not work

### ISSUE THREAD

**Issue by makitlas** [PrestaShop/PrestaShop#26740] opened 2021-11-24 18:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Guest visitors see product prices. Settings selected that the price should not be displayed when not logged in

### Expected behavior

The price should only be visible to logged in users.

### Steps to reproduce

In the store

### PrestaShop version(s) where the bug happened

PS 1.7.8.0 Multistore

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment] 2021-11-25 16:51
Hello @makitlas 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23131. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-25 16:51
Duplicate of #23131

**Closed as completed by hibatallahAouadni** 2021-11-25 16:51 UTC
Labels: Bug, Duplicate, Invalid
