### ISSUE TITLE
Rating disappear after using of pagination or select filter Prestashop 1.7.6.0 

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#14996] opened 2019-08-05 19:48 UTC
**Describe the bug**
I am using the PrestaShop 1.7.6.0 and "Classic" theme. I have noticed a bug with a native module "Products comments" on catalog page.  A rating disappear after using of pagination or enabling of a filter. 

**To Reproduce**
1. Install a native module "Product comments":
http://prntscr.com/ooqmmq
2. Leave a comment:
http://prntscr.com/ooqnu1
3. Go to catalog page with with product:
http://prntscr.com/ooqo73
4. Enable filter or use a pagination:
http://prntscr.com/ooqoj6
http://prntscr.com/ooqomr
5. Look on product: the rating disappeared after completing:
http://prntscr.com/ooqph6  

**Additional information**
PrestaShop version: 1.7.6.0

**Comment by web-burn** [comment] 2019-08-06 08:38
Can you help me?

**Comment by kpodemski** [comment] 2019-08-06 08:42
it's known bug of new version of module, you have to wait for a new version with fix

**Comment by khouloudbelguith** [comment] 2019-08-06 08:45
Hi @web-burn,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14878
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-06 08:45
Duplicate of #14878

**Closed as completed by khouloudbelguith** 2019-08-06 08:45 UTC
Labels: Duplicate

**Comment by web-burn** [comment] 2019-08-06 09:15
@khouloudbelguith, sorry, thank!
