### ISSUE TITLE
Order set to 0.00 with sold out product after changing status

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#25584] opened 2021-08-12 11:40 UTC
#### Describe the bug

we have an order that the payment was accepted. the order was set to processing. The product was sold out and deleted.

Later we put the order back to payment accepted, because we where able to replace the product, but now the total order price is set to 0.00 instead of keeping the original value of the order.

#### Expected behavior

Order to keep it orginal value

#### Steps to Reproduce

1. Create an order
2. Set to payment accepted
3. Remove the product 
4. Set the order back to payment accepted
5. See error => the total order price is set to 0.00 instead of keeping the original value of the order.

**Screenshots**

![Screenshot 2021-08-12 at 14 39 10](https://user-images.githubusercontent.com/46492443/129190787-19561b98-1a1e-4aa6-a5e9-badeac62fc1d.png)

#### Additional information

* PrestaShop version: 1.7.7.6 / 1.7.7.5
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-08-13 08:53
Hello @01park 

I just edit your steps to reproduce, could you please check if there's something missing :pray: 
I didn't manage to reproduce your issue with PS1776, see the attached screen record below:

https://drive.google.com/file/d/11uQGLedTkFWVYOtoduCtNQjycUmAr4_x/view

Well, it seems that you define this new status **In progress**, so could you please make a screenshot of its configuration.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-01 08:48
Hello @01park 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-01 08:48 UTC
Labels: Bug, BO, Order, No change required, 1.7.7.5
