### ISSUE TITLE
Product delivery not possible to save on product

### ISSUE THREAD

**Issue by rbuelund** [PrestaShop/PrestaShop#11353] opened 2018-11-12 05:46 UTC
**Describe the bug**
When choose a special delivery company on a product it is not saved. The Green "Settings updated" is showed, but the setting is NOT saved.

**To Reproduce**
1. Go to products
2. Click on Delivery
3. Scroll down to Delivery company and mark one of several
4. Press save
5. Go back to product

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-11-12 09:33
Hi @rbuelund,

I did not manage to reproduce the issue with the last version 1.7.4.2 / PHP v7.2.8.
I attached a video record.
https://drive.google.com/file/d/1UlWW4JDfH9-b2_Rop6fxQl6OADkFxZhI/view
Thanks to check & feedback.

**Comment by rbuelund** [comment] 2018-11-12 13:14
Actually I can save nothing at all !! The products where imported from Prestashop 1.6.1.20 But I can see that lots of others have problems with saving.. and no errors !! This is really bad !
https://www.prestashop.com/forums/topic/604058-i-cant-save-changes-to-my-products-in-prestashop-17/?page=2

**Comment by khouloudbelguith** [comment] 2018-11-12 13:21
@rbuelund, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rbuelund** [comment] 2018-11-12 13:41
Host is Unoeuro
Prestashop version 1.7.4.4
    Server setup:
        Operating system: Linux linux235.unoeuro.com 2.6.32-954.3.5.lve1.4.58.el6.x86_64 #1 SMP Fri Oct 19 05:28:14 EDT 2018 x86_64 
        Type and version of webserver : Apache 
        Version of PHP: 7.2.10
        Version of MySQL/MariaDB: 5.7.23-23-log 
        Make sure you have emptied PrestaShop’s cache - I did!
    Browser setup:
        Operating system: Windows 10
        Version of the browser: Tried all new browsers - Firefox, Chrome, Edge
        Make sure you have emptied your browser’s cache - I did !
    Any error message: Nonq at all !



I have now tried to create a completely new product and that was possible - and this product I can also edit. Here are two lines from the product table. The product with ID=417 i cannot edit. The new product with id=418 I can edit:
(417, 3, 3, 154, 1, 1, 0, 0, '', '', '', '0.000000', 0, 1, NULL, 0, '1279.200000', '0.000000', '', '0.000000', '0.00', '', '', '', '0.000000', '0.000000', '0.000000', '0.000000', 2, 1, 0, 0, 0, 0, 1, '404', 0, 1, '0000-00-00', 0, 'new', 1, 1, 'both', 0, 0, 0, 1035, '2018-09-10 20:26:57', '2018-09-10 20:31:22', 0, 3, 1),
(418, 0, 0, 2, 1, 1, 0, 0, '', '', '', '0.000000', 0, 1, NULL, 0, '0.000000', '0.000000', '', '0.000000', '0.00', '', '', '', '0.000000', '0.000000', '0.000000', '0.000000', 2, 1, 0, 0, 0, 0, 0, '404', 0, 1, '0000-00-00', 0, 'new', 1, 0, 'both', 0, 0, 0, 0, '2018-11-12 14:30:35', '2018-11-12 14:31:48', 0, 0, 1);

**Comment by khouloudbelguith** [comment] 2018-11-12 14:41
Hi @rbuelund,

Could you please check those issues: 
#9677: you need to check if your product tag field contains " symbol
#9954: you need to check the description of your product
#9717: you need to check if the meta description is more than 255 characters in product
It can be an issue similar.
Thanks to check & feedback.

**Comment by rbuelund** [comment] 2018-11-12 15:51
_tag table:
(65, 1, 'dansk møbeldesign'),
(66, 1, 'hynder'),
(67, 2, 'dansk møbeldesign'),
(68, 2, 'hynder');

Attached _product_lang table:
[xxx_product_lang.zip](https://github.com/PrestaShop/PrestaShop/files/2572567/xxx_product_lang.zip)
No meta_description in the table that is longer than 200 chars


Another thing: If I try to duplicate a product i get this error:

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. "

When activating debug and doing a Duplicate of a product I see this error:

"CRITICAL                 17:11:15 | php | Uncaught Exception: Egenskaben Product->link_rewrite er ikke gyldig
-- | -- | --
CRITICAL                 17:11:15 | request | Uncaught PHP Exception PrestaShopException:  "Egenskaben Product->link_rewrite er ikke gyldig" at  /var/www/xxxxxx.xx/public_html/shop/classes/ObjectModel.php  line 1000
"
What is wrong here ??

**Comment by rbuelund** [comment] 2018-11-12 16:18
Is the problem because of the use of æ,ø,å - in the link_rewrite ?? This worked in 1.6.20 - as this is an export from 1.6.20 ???

**Comment by khouloudbelguith** [comment] 2018-11-12 16:18
@rbuelund, if you enable the mode debug, is there any exception displayed?

**Comment by rbuelund** [comment] 2018-11-12 16:19
Did you see the exception further up this thread ?

**Comment by khouloudbelguith** [comment] 2018-11-12 16:20
@rbuelund, we just commented in the same time, I will check & feedback.

**Comment by khouloudbelguith** [comment] 2018-11-12 16:22
@rbuelund, in the BO => Shop Parameters => Traffic & SEO,  in the "SET UP URLS" part, you need to check if the `Accented URL` is enabled?

**Comment by rbuelund** [comment] 2018-11-12 16:26
Good God! That did the trick.. BUT it would be nice with a Prestashop that gave a little more information about such error, when trying to save a product.. maybe a suggestion for a new feature ;-)

Thank you very much for your help on this...

**Comment by khouloudbelguith** [comment] 2018-11-12 16:31
@rbuelund, in our doc Accented URL => PrestaShop is able to produce URL with special characters, for products with non-ASCII names.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-12 16:31 UTC
Labels: BO, No change required
