### ISSUE TITLE
Wrong carrier after payment

### ISSUE THREAD

**Issue by twazerty** [PrestaShop/PrestaShop#10445] opened 2018-09-15 21:56 UTC
I am using a dutch Payment module called Sisow (https://www.sisow.nl/implementatie-plugin). When using their plugin the following happens:
1. Add product to Cart
2. Place order
3. Payment by Sisow
4. Order will be created after Payment (Cart will be converted to Order)
5. Carrier is wrong in the Order
6. The right Carrier is still available on the associated Cart

Normal payment module works different:
1. Add product to Cart
2. Place order
3. Create order
4. Pay order by payment provider
5. The right Carrier is set on the Cart

After reading the source code a little bit and trying some stuff I found (actually Sisow technicians) that the result of the following code on line 322 in PaymentModule.php always returns the first carrier instead of the selected one:
```
$carrier = null;
if (!$this->context->cart->isVirtualCart() && isset($package['id_carrier'])) {
   $carrier = new Carrier((int)$package['id_carrier'], (int)$this->context->cart->id_lang);
   $order->id_carrier = (int)$carrier->id; // always the same carrier
   $id_carrier = (int)$carrier->id;
} else {
   $order->id_carrier = 0;
   $id_carrier = 0;
}
```

I traced it back to line 250 and it is still the wrong carrier:
```
$cart_delivery_option = $this->context->cart->getDeliveryOption();
```

Then after some more digging I noticed some caching on line 3074 in Cart.php:
```
    public function getDeliveryOption($default_country = null, $dontAutoSelectOptions = false, $use_cache = true)
    {
        $cache_id = (int)(is_object($default_country) ? $default_country->id : 0).'-'.(int)$dontAutoSelectOptions;
        if (isset(static::$cacheDeliveryOption[$cache_id]) && $use_cache) {
            return static::$cacheDeliveryOption[$cache_id];
        }
```

so I changed line 250 in PaymentModule.php to see what happens if I disable the cache:
```
$cart_delivery_option = $this->context->cart->getDeliveryOption(null,true,false);
```
now the carrier is correctly set at the order after payment. This probably is not the root cause of the problem but should give you a lead on where to look. I am not a PHP developer myself so I could only help you this far.

Prestashop 1.7.4.2 (but also in 1.7.3)

**Comment by khouloudbelguith** [comment] 2018-09-17 09:21
Hi @twazerty,

Could you please provide me the Sisow module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks & best regards, Khouloud

**Comment by twazerty** [comment] 2018-09-18 21:40
The module itself is available for free:
https://www.sisow.nl/implementatie-plugin
Direct link:
https://www.sisow.nl/Sisow/down.aspx?doc=prestashop17-5.0.0.zip

But I think you need a working api-key to use it in test mode. If needed I can ask sisow if they will contact you.

**Comment by khouloudbelguith** [comment] 2018-09-19 09:58
Hi @twazerty,

I attached a video record.
https://drive.google.com/file/d/1ii938EkEKbtav5dA75tnLUtKiJOy-vao/view
Thanks to check & feedback.
PS: Have you tried to contact the module author about this issue?

Best regards, Khouloud

**Comment by twazerty** [comment] 2018-09-19 21:04
@khouloudbelguith , your video does not show the actual problem. Can you test it with iDeal option? Maybe you also need an api key from sisow in order to actually test it.

Yes I contacted Sisow first. They analysed the problem and concluded it is a problem within prestashop's core.

**Comment by khouloudbelguith** [comment] 2018-09-20 10:02
Hi @twazerty,

Could you please provide me your API key from sisow module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks & best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-21 08:14
Hi @twazerty,

Done.
I just received your email.
I will check & feedback.

Thanks & best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-21 08:34
Hi @twazerty,

As always.
Some strange thinks.
In the checkout page, I have this error.
![image](https://user-images.githubusercontent.com/16067358/45869874-e1b98080-bd89-11e8-98b5-a01109151ca4.png)


Best regards, Khouloud

**Comment by Sisow** [comment] 2018-10-08 07:00
Dear Khouloud,

looks something in Giropay/EPS, can you switch it off in the Sisow settings?
I'll check it out why this error occurs.

With kind regards,
Mark van Haaren
Sisow

**Comment by khouloudbelguith** [comment] 2018-10-08 16:58
HI @twazerty,

I attached a video record.
https://drive.google.com/file/d/1YnyqLfMjKFY-DRxiA2G7WgqHbbZXClrh/view
Thanks to check & feedback.

**Comment by Sisow** [comment] 2018-10-09 06:36
Dear,

Could you try this plug-in, it’s the lasted update with the fix for the non-numeric error.

Met vriendelijke groet,

Mark van Haaren
R&D Manager

[1507886609460_sisow.png]

Binnen Parallelweg 14
5701 PH Helmond

E:   m.vanhaaren@sisow.nl<mailto:m.vanhaaren@sisow.nl>
W: https://www.sisow.nl
T:   +31 (0)85 2 734 734

Volg ons op:
[1507836975509_linkedin.png]<http://www.linkedin.com/company/sisow-payment-innovations> [1507836987254_facebook.png] <http://www.facebook.com/Sisow.nl>  [1507836998772_twitter.png] <http://twitter.com/Sisow_nl>
Sisow (ingeschreven bij Kamer van Koophandel onder nummer 52093328) streeft ernaar geen vertrouwelijke informatie per e-mail te verzenden. Desondanks kunnen dit bericht en eventueel meegestuurde bestanden vertrouwelijk zijn en informatie bevatten. De informatie in dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Mocht de e-mail niet voor u bestemd zijn, dan verzoeken wij u vriendelijk de afzender daarvan op de hoogte te stellen en deze e-mail te vernietigen.

Sisow wijst iedere aansprakelijkheid af voor en/of in verband met alle gevolgen en/of schade van een onjuiste of onvolledige verzending en/of vertraging ervan. Sisow is niet verantwoordelijk voor meegestuurde virussen. Het is uw eigen verantwoording om e-mails en de meegezonden bestanden hierop te scannen. Aan deze e-mail kunnen geen rechten worden ontleend. Belangrijke afspraken of contracten dienen altijd door de daarvoor bevoegde personen te worden ondertekend.

Van: khouloudbelguith <notifications@github.com>
Verzonden: maandag 8 oktober 2018 18:59
Aan: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
CC: Support | Sisow <support@sisow.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [PrestaShop/PrestaShop] Wrong carrier after payment (#10445)


HI @twazerty<https://github.com/twazerty>,

I attached a video record.
https://drive.google.com/file/d/1YnyqLfMjKFY-DRxiA2G7WgqHbbZXClrh/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2018-10-09 08:27
Hi @Sisow,

I did not receive anything, you need to connect to GitHub & upload the attachment.
Thanks!

**Comment by Sisow** [comment] 2018-10-09 11:19
[sisow 5.1.0.zip](https://github.com/PrestaShop/PrestaShop/files/2460142/sisow.5.1.0.zip)

Dear Khouloud,

here is the missing attachment.

**Comment by khouloudbelguith** [comment] 2018-10-09 11:35
@Sisow, same issue here: https://drive.google.com/file/d/16ONsnvP6lQRt90BioyTFGwi8SxdBkN6h/view

**Comment by Sisow** [comment] 2018-10-09 12:03
Dear @khouloudbelguith,

the sisow account is only active for test transactions.
You have to enable the testmode in the settings.

**Comment by khouloudbelguith** [comment] 2018-10-09 12:41
@Sisow, https://drive.google.com/file/d/1c_sp0K73SOMvKNcAHeYAsk8XUvuadcKZ/view
Thanks to check & feedback.

**Comment by Sisow** [comment] 2018-10-09 13:17
That's because there are no PayPal API data in the account.
If it's alright you receive a new password for your Sisow account, can you send it to support@sisow.nl?
Then I can set the API data.

**Comment by Sisow** [comment] 2018-10-09 13:30
i added the data, you should be able to start an test payment with paypal

**Comment by khouloudbelguith** [comment] 2018-10-09 13:34
@Sisow thanks!

**Comment by khouloudbelguith** [comment] 2018-10-09 13:41
HI @twazerty,

I attached video record.
https://drive.google.com/file/d/1kjxz7dutjzBbgrJV7YRtpMv4D1qndkTn/view
Thanks to check & feedback.

**Comment by Sisow** [comment] 2018-10-09 13:52
Hi @khouloudbelguith,

and what happens when you select a different shipping option?
Maybe it's cached on our server's ip?

**Comment by khouloudbelguith** [comment] 2018-10-09 14:07
Hi @Sisow,

I checked different carriers, The right Carrier is set on the Cart => OK.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-16 16:42
Hi @twazerty,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-16 16:42 UTC
Labels: Payment methods, No change required, 1.7.4.2

**Comment by JosBerkhof** [comment] 2021-01-06 16:41
I have the exact same issue with PS1.7.7.0 and Sisow. What was done to fix this?

**Comment by Sisow** [comment] 2021-01-07 14:20
The problem appeared to be a caching issue in classes\PaymentModule.php, the function below is called on line 250-261 (depending on the PrestaShop version).

`$cart_delivery_option = $this->context->cart->getDeliveryOption();`
This line has to be edited to the following:
`$cart_delivery_option = $this->context->cart->getDeliveryOption(null,true,false);`

What has now changed is that the carriers are not loaded from the cache anymore, but instead fully reloaded.
Everything else remains the same.
If you are updating PrestaShop, the edit listed above will need to be applied again.

- JW

**Comment by JosBerkhof** [comment] 2021-01-08 11:51
Thanks @Sisow 

I can confirm that the workaround is working.
I was just a bit puzzled that this suggested workaround was mentioned in 1.7.4 and still a problem in 1.7.7.0
But for me I can live with this.

Kind regards,
Jos Berkhof

**Comment by JoryHogeveen** [comment] 2021-11-15 10:20
@Sisow 
Any idea when this override will be in PS core? Is there an open pull request for this?

**Comment by RobinFlikkema** [comment] 2022-01-22 16:38
Any news on this? As this issue is closed, but the problem still exists.

The workaround works, but is seems like a hassle to do this ever ytime.

**Comment by JoryHogeveen** [comment] 2022-01-24 12:55
@RobinFlikkema Don't expect a bug fix at all. Sisow will stop entirely since Buckaroo took over.
