### ISSUE TITLE
Hreflang Tags with Errors-no return tags(one language website)

### ISSUE THREAD

**Issue by azitafomo** [PrestaShop/PrestaShop#17200] opened 2020-01-16 09:23 UTC
I have error which is related to no return tags and as
![Capture](https://user-images.githubusercontent.com/57670369/72510602-f9f6be00-385e-11ea-8e46-a3d940780701.JPG)

 my website has only one language a friend told me me to delete this lines from: head.tpl
{block name='head_hreflang'}
    {if isset($urls.alternative_langs)}
      {foreach from=$urls.alternative_langs item=pageUrl key=code}
        <link rel="alternate" href="{$pageUrl}" hreflang="{$code}">
      {/foreach}
    {/if}
  {/block}
but my errors are available and some errors are added to my webmaster again.
I send the first head.tpl of my website. please help me
[head.txt](https://github.com/PrestaShop/PrestaShop/files/4070286/head.txt)

**Comment by khouloudbelguith** [comment] 2020-01-16 09:57
Hi @azitafomo,

What is the exact version PrestaShop did you use?
Could you please add steps to reproduce the issue in a new comment.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-17 07:43
Hi @azitafomo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-17 07:43 UTC
Labels: Bug, No change required
