### ISSUE TITLE
Trouble with Duplicate and make Offline products

### ISSUE THREAD

**Issue by manon-pitron** [PrestaShop/PrestaShop#22929] opened 2021-01-21 12:44 UTC
Good morning all,

I have just recently joined my company which hosts 2 e-commerce sites via prestashop.
In the middle of my audit, the teams in charge of referencing / writing product sheets informed me of a bug that I absolutely cannot resolve.

---
#### Describe the bug

In backOffice, when I go to my list of my products display and want to put one of my products offline, if I subsequently re-activate it, all of its characteristics disappear (see attachment)

I get exactly the same problem when I duplicate a product: only the title and the description are duplicated, the other fields (caracteristics and custom fields )remain empty.

#### Steps to Reproduce

1. **BO**>**Catalog**>**Products**
2. **Disable** a product
3. Then **enable** it again
4. See error => all of its characteristics disappear
5. Try to **duplicate** a product
6. See error => only the title and the description are duplicated, the other fields remain empty.

When I launch the console I get the following error:
`
Failed to load resource: the server responded with a status of 404 ()
`
**Screenshots**

![Capture d’écran 2021-01-21 à 13 41 01](https://user-images.githubusercontent.com/71016913/105352676-82d0d400-5bee-11eb-91df-7d50d9522c15.png)

![Capture d’écran 2021-01-21 à 13 41 31](https://user-images.githubusercontent.com/71016913/105352688-85332e00-5bee-11eb-83f3-bc58ac079fbd.png)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

---
I hope my English is not too bad and that you can help me, it is very complicated (and super dangerous!) To recover a project without the background and no active dev / test environment ...

Thx u!

**Comment by hibatallahAouadni** [comment] 2021-01-21 15:47
Hello @manon-pitron 

Welcome to PS :tada: 
Well, as you can see I edit your issue cause you need to **follow the provided template to submit a complete bug report**.
Please next time follow the template :wink: 

I need to know your PHP version cause I didn't manage to reproduce your issue with PS1.7.6.1 and PS1.7.7.0, see the attached screen record below:

- the first case: disable/enable a product 
https://drive.google.com/file/d/1i8275gxL3dmqYhYBK4Fo7aupYoUPn8Op/view
- the second case: duplicate a product
https://drive.google.com/file/d/1c7F4MnYMdgtYZ8K-DlXEpmIDRAjUgyxl/view

Please check and feedback.
Thanks!

**Comment by BenTen** [comment] 2021-01-26 12:17
"points cles", "inclus dans votre colis" and "technologie / innovation" seems to be customs features, right?
Do you use a module for that?

Maye the problem come from this module.

**Comment by hibatallahAouadni** [comment] 2021-02-11 16:29
Hello @manon-pitron ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-11 16:29 UTC
Labels: Bug, BO, No change required, 1.7.6.1, 1.7.6.3, 1.7.7.0
