### ISSUE TITLE
[BO] Can't remove discount added from a cart rule on product selection after adding a product in order (again!)

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20244] opened 2020-07-20 14:05 UTC
#### Describe the bug

This bug was initially reported in https://github.com/PrestaShop/PrestaShop/issues/18379, fixed by https://github.com/PrestaShop/PrestaShop/pull/18205 but we observe it again after merging https://github.com/PrestaShop/PrestaShop/pull/20083 (according to @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/pull/20083#issuecomment-659477917)

Can't remove discount added from a cart rule on product selection after adding a product in order

#### Expected behavior

Can remove discount added from a cart rule on product selection after adding a product in order

#### Steps to Reproduce

1. Create a product A (100€, 100 items in stock, available)
2. Create a cart rule:
  - has no code
  - product selection on previous created product with 100 euro tax included
  - discount amount of 500 EUR tax included
3. In BO, add the product to a previous order
4. The discount has been added to order
5. **ERROR :** The discount can't be removed

Edit by @Robin-Fischer-PS :
6. Go back to the order after trying to delete the discount
7. The voucher is no longer displayed but the discount is still applied in the total of the order

Video from @Robin-Fischer-PS : 
https://drive.google.com/file/d/1yXPaN5rDVTXcLychf1ft3e_3RbblR3QT/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x branch

**Comment by jolelievre** [comment] 2020-07-20 14:34
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/20246

**Closed as completed by jolelievre** 2020-07-20 14:34 UTC
Labels: Bug, Major, BO, Order, Discounts, Regression, Fixed, migration, 1.7.7.x
