### ISSUE TITLE
BO->Catalog->Proucts non proporsional column size

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#25218] opened 2021-07-02 15:25 UTC
Hello!
After several updates I discovered that in the BO->Catalog->Proucts the column have non-prorportional size and this make inconvenience 
the column with Nomber is too large but the Product name column is too small ((

#### Expected behavior

Unfortunately I have not find the template or css to make changes.
May be you can suggest me where look for decision ?

#### Steps to Reproduce

1. Go to 'BO'
2. Click on 'Catalog->Products.'
4. See the non proporsional columns

**Screenshots**

![image](https://user-images.githubusercontent.com/50954519/124296309-7ae46b00-db62-11eb-8afd-e808374effa5.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.1.33

**Comment by khouloudbelguith** [comment] 2021-07-02 16:01
Hi @photinia73,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/24952 to fix the issue.
Your ticket is a duplicate of #24915
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-07-02 16:01
Duplicate of #24915

**Closed as completed by khouloudbelguith** 2021-07-02 16:01 UTC
Labels: Duplicate

**Comment by photinia73** [comment] 2021-07-02 19:57
Hello @khouloudbelguith !
Thank you for reply...
I think I will wait for the upgrade, cource I have not folder admin-dev and etc )) I just have a PS shop and admin it. My php is very modest ))
