### ISSUE TITLE
Product discounts depending on quantity showing incorrect prices

### ISSUE THREAD

**Issue by ebaubau** [PrestaShop/PrestaShop#14636] opened 2019-07-14 09:31 UTC
If i set some specific price for a product in the BO, the price shown in front End on the table is different fro the one used to calculate the amount to pay

**To Reproduce**
1. Go to 'bo' in 'Catalog Price Rules'
2. Insert 2 rules for the same product for quantity 1 and 2
3. Go to front end, select the product and choose 2 pieces

**Screenshots**
see the attached files
![bo](https://user-images.githubusercontent.com/37108454/61181788-fa519a80-a62a-11e9-96e2-743a7d826ef4.png)
![fe](https://user-images.githubusercontent.com/37108454/61181789-fa519a80-a62a-11e9-8a13-b7a9e6bf7b73.png)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2.19

**Comment by mariem-abid** [comment] 2019-07-15 10:33
Hi @ebaubau,

I did not manage to reproduce the issue with PS:1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1H7-XMOaIZiBujHPXGp5J7kKsHV99srMn/view

Thanks for check and feedback.

**Comment by ebaubau** [comment] 2019-07-15 11:33
Hi Mariem, to get the error it is necessary to insert a rule for quantity 1.
If you do this you will see the error when you choose quantity 2.

Thanks

**Comment by mariem-abid** [comment] 2019-07-15 15:39
@ebaubau, I did not manage to reproduce the issue with quantity 1.
I attached a video record
https://drive.google.com/file/d/1ckzUn-GDcII21yrsmKUAybeNka1P_UmH/view

Thanks for check and feedback.

**Comment by mariem-abid** [comment] 2019-08-14 07:35
Hi @ebaubau,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by mariem-abid** 2019-08-14 07:35 UTC
Labels: Bug, FO, Can't reproduce, Discounts
