### ISSUE TITLE
Broken tabs in the product description on the edit page in back office

### ISSUE THREAD

**Issue by elrosi** [PrestaShop/PrestaShop#21863] opened 2020-11-11 12:01 UTC
#### Describe the bug
Broken tabs in the product description on the edit page in back office

#### Steps to Reproduce

1. Go to the product modification page
2. Click the **Description** tab
3. Click the top **Quantities** tab in the product settings
4. Return to the **Basic settings** tab

**Product description cards left broken**

**Screenshots**
https://share.vidyard.com/watch/NP3WeZGXrrSzr9Dq96EayY?

#### Additional information
* PrestaShop version: form 1.7.5.2 to 1.7.6.8

**Comment by hibatallahAouadni** [comment] 2020-11-11 12:58
Hello @elrosi ,

I was able to reproduce the issue with PrestaShop version 1.7.6.8 and 1.7.7.0-rc.1+build.4 
I’ll add this to the debug backlog so that it’s fixed. I attached a screen record with PS1770:

https://drive.google.com/file/d/12gf5TfQUC4-T6heIwwTblES9AVUF9e8o/view

If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you.

**Comment by elrosi** [comment] 2020-11-11 13:18
Hello @hibatallahAouadni 
Thank you for your time and care.

**Comment by hibatallahAouadni** [comment] 2020-11-12 09:17
Hello @elrosi 

Your issue has been fixed in our next release 1.7.8.0. This issue is a duplicate of #9668. 
You can try the solution provided on this PR #18033 , please subscribe to the issue mentioned above.
So, I close it.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-12 09:18
Duplicate of #9668

**Closed as completed by hibatallahAouadni** 2020-11-12 09:17 UTC
Labels: Bug, Trivial, BO, Duplicate, 1.7.5.2, 1.7.7.0, 1.7.6.8
