### ISSUE TITLE
[BO/FO IMPROVEMENT] Specific price date from/to with hours

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14433] opened 2019-06-29 16:34 UTC
Hi.
We cant set specific price date from/to with hours. Only full days but hour/minute/seconds field is available. 

In case of immediate SALE offer valid in next few hours we are unable to set that specific date.

![zrzut 2019-06-29 18 05 21](https://user-images.githubusercontent.com/8243273/60386771-e38f3d80-9a99-11e9-8b75-21bade5bddb6.png)

**Comment by matks** [comment] 2019-06-30 15:28
Hi @PrestaShark, we have already registered this need in https://github.com/PrestaShop/PrestaShop/issues/11329 and it should be done soon as it was added in v1.7.7 backlog 😄 

By the way, is the seconds really useful ? Hours and minutes, it's obvious but I dont think we need to add the seconds, do we ?

**Comment by ghost** [comment] 2019-07-01 08:23
Seconds are not crucial. 

But dammm.... 1.7.7 roadmap... I will try to fix anyway

**Comment by ghost** [comment] 2019-07-04 00:08
/admin/themes/new-theme/public/catalog_product.bundle.js

Change from .datetimepicker({format:"YYYY-MM-DD"}) 
to .datetimepicker({format:"YYYY-MM-DD HH:mm:ss"})

**Comment by khouloudbelguith** [comment] 2019-07-04 07:39
Hi @PrestaShark,

Your ticket is a duplicate of #11329
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-04 07:40
Duplicate of #11329

**Closed as completed by khouloudbelguith** 2019-07-04 07:39 UTC
Labels: Duplicate
