### ISSUE TITLE
Template - Won't allow to place an order with 0 amount

### ISSUE THREAD

**Issue by theodiablo** [PrestaShop/PrestaShop#24232] opened 2021-04-27 11:22 UTC
If we try to place an order with an amount of 0 because we are using discount codes, the final checkout step button is disabled.

#### Expected behavior

If amount is 0 and no payment method is selected (because there is none), we should be able to place the order

#### Steps to Reproduce

1. Create a discount code of 100€ amount and free shipping
2. Add products to your cart (bellow 100€ amount)
3. Add the discount code to your cart
4. Complete checkout steps
5. See that complete order button is disabled when it should be enabled

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by theodiablo** [comment] 2021-04-27 11:24
Fixed by #24230

**Comment by dariel97** [comment] 2021-04-27 11:46
Ok

**Comment by hibatallahAouadni** [comment] 2021-04-27 12:21
Hello @theodiablo 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9927 and there's already a PR to fix the issue #22389
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-04-27 12:22
Duplicate of #9927

**Closed as completed by hibatallahAouadni** 2021-04-27 12:21 UTC
Labels: Duplicate
