### ISSUE TITLE
1.7.4.3. Frontoffice after selecting combination, returns to standard combination

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#11067] opened 2018-10-18 14:40 UTC
Prestashop 1.7.4.3.
PHP 7.2

Frontoffice: When selecting combination, within second system returns to standard combination.
Disabled all modules. No cache. 

This behaviour cannot be reproduced on our DEV server

**Comment by khouloudbelguith** [comment] 2018-10-18 14:43
Hi @Peter4661,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9667
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-18 14:43 UTC
Labels: Duplicate

**Comment by GuimDotCom** [comment] 2018-10-25 16:44
Hi @Peter4661, have you done something to correct this problem, waiting the fix?

**Comment by Peter4661** [comment] 2018-10-25 17:24
Hello Guim,

We decided not to wait for the fix since this issue has not been solved for 6 months or so. 

We started to split up products with options into individual products; i.e. "Dress" with color options became " yellow Dress, "red dress", "Green dress".   This on the risk that Google at all sees this as duplicate products.
