### ISSUE TITLE
I try to update prestashop 1.7.6.9 to 1.7.7.1

### ISSUE THREAD

**Issue by Marcelozippo** [PrestaShop/PrestaShop#22822] opened 2021-01-13 21:25 UTC
Hello, I try to update prestashop 1.7.6.9 to 1.7.7.1 and when the update finishes I get the following error.
---
[INTERNAL] /www/wwwroot/cotillonunpocoloco.com/classes/db/DbPDO.php line 136 - PrestaShopException: Link to database cannot be established: SQLSTATE[HY000] [2002] Connection refused #0 /www/wwwroot/cotillonunpocoloco.com/classes/db/Db.php(379): DbPDOCore->connect() #1 /www/wwwroot/cotillonunpocoloco.com/classes/db/Db.php(566): DbCore->query('ALTER TABLE `pr...') #2 /www/wwwroot/cotillonunpocoloco.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(430): DbCore->execute('ALTER TABLE `pr...', false) #3 /www/wwwroot/cotillonunpocoloco.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(362): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runSqlQuery('1.7.7.0', 'ALTER TABLE `pr...') #4 /www/wwwroot/cotillonunpocoloco.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(284): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.7.0', 'ALTER TABLE `pr...') #5 /www/wwwroot/cotillonunpocoloco.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(55): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.7.6.9') #6 /www/wwwroot/cotillonunpocoloco.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(101): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.6.9') #7 /www/wwwroot/cotillonunpocoloco.com/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /www/wwwroot/cotillonunpocoloco.com/cotillonadmin/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}

----

The web loads badly, and the back office does not load the menu on the left. Same thing happened when trying to upgrade from 1.7.6.9 to 1.7.7.0

Template: Warehouse 4.3.7
----
Linux Server # 1 SMP Information Tue Aug 25 17:23:54 UTC 2020 x86_64
Server software version: Apache 2.4.46
PHP version: 7.3.25
Memory limit: 2048M
Maximum run time: 300
Max size for file upload: 40M
---
  Database information
MySQL version: 10.4.12-MariaDB-log
MySQL server: localhost
MySQL name: ****
MySQL user:*****
Tables prefix: pr_
MySQL Engine: InnoDB
MySQL Driver: DbPDO

What could be the problem?

Thank you

**Comment by florine2623** [comment] 2021-01-14 10:52
Hello @Marcelozippo ,
Your issue is a duplicate of #22250.
Please follow the instructions there.
Thanks !

**Comment by florine2623** [comment] 2021-01-14 10:53
Duplicate of #22250

**Closed as completed by florine2623** 2021-01-14 10:53 UTC
Labels: Duplicate

**Comment by Marcelozippo** [comment] 2021-01-14 17:58
Hello, I think it is not duplicated, because #22250 talks about updating to version 1.7.7.0 and I am trying to update to 1.7.7.1 and prestashop on this website says that that was already solved
https://build.prestashop.com/news/prestashop-1-7-7-1-maintenance-release/
---
Core

* Behat tests: Reset static cache of all object models between feature tests
* Upgrade 1.6.1.24 => 1.7.7.0 fails; XmlLoader Call to a member function trans () on null
* In autoupgrade process, Doctrine schema update process is performed after scripts which create inconsistent behavior
* The left menu in BO disappeared after upgrade to 1.7.7.0
* Module is not registered in "aliases" hooks
-----
And the problem continues. And in # 22250 there is no solution to the problem?
I currently have PHP 7.2

Thank you
Marcelo
