### ISSUE TITLE
Prestashop 8 localization files missing

### ISSUE THREAD

**Issue by bogwero** [PrestaShop/PrestaShop#32430] opened 2023-05-03 18:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Error 404 when trying to add localization languages, however it appears to be adding the correct language parameters after more tries.
The files appear to be missing (err 404) from:
http://api.prestashop.com/localization/8/de.xml
http://api.prestashop.com/localization/8/es.xml
http://api.prestashop.com/localization/8/it.xml
and so on...

 in /home/user/www/public_html/src/Core/Localization/Pack/Loader/AbstractLocalizationPackLoader.php on line 47 PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;http://api.prestashop.com/localization/8/es.xml&quot; in /home/user/www/public_html/src/Core/Localization/Pack/Loader/AbstractLocalizationPackLoader.php on line 47" while reading response header from upstream, client: xxx.xxx.xxx, server: localhost, request: "POST /admin/index.php/improve/international/localization/import-pack?_token=xxxxxx HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "v8.psbox.net", referrer: "https://localhost/admin/index.php/improve/international/localization/?_token=xxxx"
2023/05/03 17:39:17 [error] 48406#48406: *268 FastCGI sent in stderr: "PHP message: PHP Warning:  simplexml_load_file(http://api.prestashop.com/localization/8/de.xml): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

### Steps to reproduce

Admin->International->Localization->Languages->Add Language

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.7

**Comment by hibatallahAouadni** [comment] 2023-05-09 06:21
Hello @bogwero 

Could you please provide a screen record 🙏 cause it seems I'm missing step as I didn't manage to reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-05-23 15:06
Hello @bogwero 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-23 15:06 UTC
Labels: Bug, BO, Localization, Languages, Invalid, 8.0.4
