### ISSUE TITLE
Conflict between themes and template files when prestashop is used in multistore mode and cache activated

### ISSUE THREAD

**Issue by thiebauld** [PrestaShop/PrestaShop#10695] opened 2018-09-25 11:35 UTC
**Describe the bug**
The Prestashop cache is not working in multistore with different templates activated fo each store. Templates in cache seems to be "mixed up" and some content of .tpl files from the other theme are visible in the current visible website.

**To Reproduce**
1. Activate multistore
2. Create and configure two (or more) different store
3. Select a different theme for each store
4. In the performance panel, be sure that the option "Cache" is activated. 
5. Go to your different configured stores and do some actions (go to a page, add a product to the cart)
6. Depending of the themes, some tpl of the other theme will appear instead of the correct template.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment] 2018-09-25 13:31
Hi @thiebauld,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9763
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-25 13:31
Duplicate of #9763

**Closed as completed by khouloudbelguith** 2018-09-25 13:31 UTC
Labels: Duplicate
