### ISSUE TITLE
 When modifying an order in BO, the total tax included amount of the item is wrong in BDD

### ISSUE THREAD

**Issue by tortueduweb** [PrestaShop/PrestaShop#22665] opened 2021-01-04 17:21 UTC
#### Describe the bug

When modifying a BO order by adding a product with several quantities, the total including tax is false on the customer side.
In database, in the ps_order_detail table, the data are wrong in the total_price_tax_incl column

#### Expected behavior

The line total on the client side should be the same as the total displayed in the BO.

#### Steps to Reproduce

1. Go to an order in BO
2. In product, section, click on "Add a product"
3. Add a product with multiple quantities
4. In BO, Total with taxe is ok but on the customer invoice or on the FO order, the total is false

**Screenshots**

![tempsnip](https://user-images.githubusercontent.com/76944826/103561010-0c776680-4eb9-11eb-8bd0-cf7949dedb41.png)

![IMG_1154](https://user-images.githubusercontent.com/76944826/103561029-1ac58280-4eb9-11eb-9bad-76dfaf51764a.jpg)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-01-05 08:40
Hello @tortueduweb 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1Uj2sMDDMtXiqD0_YpNQSj2gLtXr0t8xb/view

Please check and feedback.
Thanks!

**Comment by tortueduweb** [comment] 2021-01-05 09:45
Hello @hibatallahAouadni ,

Thank you for your interest and sharing.
Indeed, the error is not reproduced on your demonstration. Maybe because you are using a test version of pretashop.
My prestashop has been updated from version 1.5.7.0 to 1.7.7.0 with the 1-click Update module. I am using the classic theme.

**Comment by hibatallahAouadni** [comment] 2021-01-05 10:22
Hello @tortueduweb 

I think you mean you upgraded 1.5.6.3 to 1.6.1.24 then to 1.7.7.0, is that so?

---
If so, I couldn't upgrade my shop 1.5.6.3 to 1.6.1.24 cause it seems the system always consider 1.6.1.24 as 1.7.7.0, see the attached screen record and screenshot below:

https://drive.google.com/file/d/1Y6UxJNqot5SUbCeBa9lO3ABS_uvFSxw8/view

![image](https://user-images.githubusercontent.com/23308427/103637064-324d4b80-4f4b-11eb-8e63-1abd876b5191.png)

Even when I click on update, my shop looks like 1.6.1.24 but it's written in the header 1.7.7.0 and it's impossible to upgrade my shop to 1.7.7.0 in this way:

![image](https://user-images.githubusercontent.com/23308427/103637081-38432c80-4f4b-11eb-8837-4956e3e2a708.png)

Please check and feedback.
Thanks!

**Comment by tortueduweb** [comment] 2021-01-05 12:14
@hibatallahAouadni  Sorry it was 1.7.5 to 1.7.7

**Comment by hibatallahAouadni** [comment] 2021-01-05 15:57
Hello @tortueduweb 

I updated my shop from 1.7.5.2 to 1.7.7.0 and I didn't encounter your issue, see the attached screen record below:

https://drive.google.com/file/d/1WkJAdbPtNNGA-Z1jEjPtlGHNE8N1YYij/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-25 21:19
Hello @tortueduweb ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-25 21:19 UTC
Labels: Bug, FO, Order, Invoices, Taxes and Prices, No change required, 1.7.7.0
