### ISSUE TITLE
BO - Stocks - The filter by Supplier by supplier do not work, it crashes the whole page after clicking on it

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31248] opened 2023-02-07 10:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The `Filter by supplier` block does not work, it crashes the whole page after clicking on it

When we click on the `Filter by supplier` block, it crashes the page, and nothing works then!

![image](https://user-images.githubusercontent.com/92912932/217214969-13dfe2b6-7d9a-40a7-9b10-2bd236ddf52e.png)

**PS8.0.1 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/217217721-e523a373-90df-48c2-a539-6728b812cae0.mp4

**develop  : NOK** :x: 

https://user-images.githubusercontent.com/92912932/217218309-2a527242-b3f0-42c8-a195-526a1048f75b.mp4

### Expected behavior

The Filter by Supplier block should work as usual!

### Steps to reproduce

1. Go to BO >  SELL > Catalog > Stock 
2. Click on Advanced filters
3. Go to the `Filter by Supplier` block 
4. Use the `Search a supplier` and click on enter
5. OR
6. Click on the checkboxes of `Fashion supplier` OR `Accessories supplier`
7. See error > The page is crashed

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-02-07 13:36
Hello @HanaRebaiQA ,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment] 2023-02-07 13:48
Does it work on 8.1.x ?

**Comment by zuk3975** [comment] 2023-02-07 14:04
I tried it on both develop and 8.1.x just now and failed to reproduce :man_shrugging:

**Comment by florine2623** [comment] 2023-02-07 14:30
It's broken on 8.1.x too : 

https://user-images.githubusercontent.com/16019289/217272707-739471a9-8664-4306-bfcf-98cf6a672287.mov

<img width="1037" alt="Screenshot 2023-02-07 at 15 29 20" src="https://user-images.githubusercontent.com/16019289/217272731-3cddb7ed-3767-452a-9a89-f4bb81c56f4d.png">

**Comment by MatShir** [comment] 2023-02-09 18:31
very weird bug ! I can reproduce it as well

**Comment by unlocomqx** [comment] 2023-02-10 07:43
[`getItems`](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/filter-component.vue#L127) is being called infinitely

https://user-images.githubusercontent.com/793712/218033056-ad4463c9-5274-4896-87b1-f116f96a50e7.mp4

**Comment by mflasquin** [comment] 2023-02-14 14:19
Hi @MatShir, @florine2623 can't reproduce too. There is specific action to reproduce it each time ?

**Comment by MatShir** [comment] 2023-02-16 16:33
Are you sure you have tested on the right branch 8.1.x?
Could you please test it quickly to be sure before closing the issue? @mflasquin

**Comment by mflasquin** [comment] 2023-03-10 13:54
The error seems to be related to this property :

![image](https://user-images.githubusercontent.com/6594752/224333590-a18a0af1-cd85-4f9a-8d8d-648bfdf48e3b.png)

In admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/filter-component.vue line 63

If is set a fix value (true for example) there is no memory leak anymore.

Ping @NeOMakinG, do you have any idea ?

**Comment by MatShir** [comment] 2023-03-10 16:05
Maybe @Hlavtox, if you have an idea 💡  
The bug is a bit blocking for the release of the 8.1, we need to find a way to answer why quickly :/

**Comment by Hlavtox** [comment] 2023-03-10 19:37
@MatShir I don't have an idea, but I found that @florine2623 reproduced this bug in **December** and it was just merged - https://github.com/PrestaShop/PrestaShop/pull/28463#pullrequestreview-1206389077 🙄

**Closed as completed** 2023-03-24 15:04 UTC
Labels: Bug, develop, Major, BO, Catalog, Stocks, Regression, PR available, Verified
