### ISSUE TITLE
Page 404 with google ad

### ISSUE THREAD

**Issue by xiaoyuan1998** [PrestaShop/PrestaShop#19536] opened 2020-06-02 17:14 UTC
when i used google ads or facebook ads and the loading page is home page,
example : www.maison-des-meches.fr?gclid=123

PS 302 TO  https://maison-des-meches.fr/accueil/?gclid=123

and then PS redirect 302 to https://maison-des-meches.fr/index.php?controller=404 and I got an 404 error.

LOG:  https://maison-des-meches.fr/logdebug.html

I have tried deactivate the addons ttproductimagehover,  deactivate the all the addons on of displayLeftColumn(ps best selles, ps last product viewed,) deactivate the product, clear sever and brower cache but it does not work.

you can test in live  https://maison-des-meches.fr?testid=123  get error 404         

 (now i forced the https://maison-des-meches.fr/?gclid=xxx redirect 302 to https://maison-des-meches.fr to walkaround )

Version de PrestaShop : 1.7.4.4
Informations sur votre serveur Linux #1 SMP Thu Nov 7 09:59:16 CET 2019 x86_64
Version  serveur : Apache/2.4.25 (Debian)
Version de PHP : 7.0.33-0+deb9u3
Version de MySQL : 10.1.38-MariaDB-0+deb9u1

**Comment by MatShir** [comment] 2020-06-03 08:34
Hi @xiaoyuan1998,
Could you provide us with more information? I can't reproduce your issue. We need more details on how you can help us understand how we can reproduce your number.

But the problem seems to be related to the module you bought on the addon store and not to PrestaShop itself. I strongly recommend that you contact the developer of the module or our support team [here](https://addons.prestashop.com/fr/599-tickets). 
**For now, I will close the issue until you provide the request information. You can reopen it at any moment.** 

Thank you for your understanding

**Closed as completed by MatShir** 2020-06-03 08:34 UTC
