### ISSUE TITLE
Add a PrestaShop MakerBundle to generate common code 🚀

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#25170] opened 2021-06-30 09:47 UTC
`HelperOptions`, `HelperList`, `HelperForm` all helped us alot in the 1.6-era, and it was (still is if you use legacy code) a very effective way to make forms, lists and config/option-forms for modules. 

**Example:**
I make a lot of ‘one-simple-functionality’-modules, that as an example consists of the main module class only, calling one hook, showing a line of text. Very often in such cases I need to add a very simple config form. Doing so
with a legacy `AdminController` and `$this->fields_options` this is done in 5 minutes.

Now, as those helper-classes are deprecated (?) and replaced with better ways (welcome Symfony), we get better code, more flexibility, but so far we loose the effective way of quickly adding a list or a config-form for a module.

### Wouldn't it be great to have a `PrestaShop MakerBundle` to auto-generate code via cli? 
For those of us that have used `Symfony MakerBundle`, I belive most of us love the easy and fast way of creating a skeleton with the multitude of files needed for a `Controller`, `Entity` and so on.
A similar thing could be done in a `PrestaShop MakerBundle` with commands like:
`bin/console make:module` (a skeleton)
`bin/console make:config-form` (Like `HelperOptions`)

And more can be added along the way.

Briefly discussed on Slack with @eternoendless

**Comment by hibatallahAouadni** [comment] 2021-06-30 10:29
Hello @onklmaps 

Thank you for your suggestion. The Developeer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by matks** [comment] 2021-07-01 15:09
I find the idea awesome

ping @ldeprestashop

**Comment by kpodemski** [comment] 2023-07-26 13:26
Closing since it is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/28017.

It seems that we couldn't agree on merging it 🤷🏻

**Closed as completed by kpodemski** 2023-07-26 13:26 UTC
Labels: Feature, CO, Needs Specs, Duplicate, Developer Feature

**Comment by hibatallahAouadni** [comment] 2023-07-28 11:12
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28017
