### ISSUE TITLE
googleanalytics module PHP E_WARNING error 

### ISSUE THREAD

**Issue by conricit** [PrestaShop/PrestaShop#34719] opened 2023-11-28 17:29 UTC
/#
/## Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
```php
AH01071: Got error 'e: PHP Warning: Undefined array key "category" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 162
PHP message: PHP Warning: Undefined array key "list" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 163
PHP message: PHP Warning: Undefined array key "variant" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 164
PHP message: PHP Warning: Undefined array key "quantity" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 157
PHP message: PHP Warning: Undefined array key "price" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 158
PHP message: PHP Warning: Undefined array key "position" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 160
PHP message: PHP Warning: Undefined array key "brand" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 161
PHP message: PHP Warning: Undefined array key "category" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 162
PHP message: PHP Warning: Undefined array key "list" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 163
PHP message: PHP Warning: Undefined array key "variant" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 164
PHP message: PHP Warning: Undefined array key "quantity" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 157
PHP message: PHP Warning: Undefined array key "price" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 158
PHP message: PHP Warning: Undefined array key "position" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 160
PHP message: PHP Warning: Undefined array key "brand" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 161
PHP message: PHP Warning: Undefined array key "category" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 162
PHP message: PHP Warning: Undefined array key "list" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 163
PHP message: PHP Warning: Undefined array key "variant" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 164
PHP message: PHP Warning: Undefined array key "quantity" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 157
PHP message: PHP Warning: Undefined array key "price" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 158
PHP message: PHP Warning: Undefined array key "position" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 160
PHP message: PHP Warning: Undefined array key "brand" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 161
PHP message: PHP Warning: Undefined array key "category" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 162
PHP message: PHP Warning: Undefined array key "list" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 163
PHP message: PHP Warning: Undefined array key "variant" in ..../httpdocs/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 164'
``` 
the GoogleAnalyticsTools.php file in the lines indicated appears with this code:

```php
public function addProductClick($products, $currencyIsoCode)
    {
        if (!is_array($products)) {
            return;
        }

        $js = '';
        if ($this->isV4Enabled) {
            foreach ($products as $key => $product) {
                $eventData = [
                    'items' => [
                        'item_id' => (int) $product['id'],
                        'item_name' => $product['name'],
                        'quantity' => (int) $product['quantity'],
                        'price' => (float) $product['price'],
                        'currency' => $currencyIsoCode,
                        'index' => (int) $product['position'],
                        'item_brand' => $product['brand'],
                        'item_category' => $product['category'],
                        'item_list_id' => $product['list'],
                        'item_variant' => $product['variant'],
                    ],
                ];

``` 

### Expected behavior

Is it possible to solve the problem of this error?

### Steps to reproduce

recurring error present in system logs

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.26

### If your bug is related to a module, specify its name and its version

ps_googleanalytics v4.2.2

### Your company or customer's name goes here (if applicable).

Robert

**Comment by Hlavtox** [comment] 2023-11-28 17:51
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/32813

Will be fixed after this is merged and a new version of the module released - https://github.com/PrestaShop/ps_googleanalytics/pull/153. :-)

**Closed as completed by Hlavtox** 2023-11-28 17:51 UTC
Labels: Bug, Duplicate
