### ISSUE TITLE
Incompatibility Issue with PDO Returning Integer Values with PHP 8.1

### ISSUE THREAD

**Issue by fox-john** [PrestaShop/PrestaShop#36836] opened 2024-09-05 15:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

 (All PS versions that support PHP 8.1 are affected)

### Describe the bug and add attachments

When using PHP 8.1 with PrestaShop 8.0 (minimal version that support PHP 8.1), the function executeS() from the Db class returns integers for columns that are defined as tinyInt or unsignedInt in the database. In previous PHP versions (before 8.1), the values returned were always strings, regardless of the column type.

This change in behavior is due to PHP 8.1 no longer automatically casting values to strings. Unfortunately, many modules have historically relied on these values being returned as strings, which causes issues when comparing values like '1' === 1.

As a result, module integrations expecting stringified values are disrupted, leading to compatibility issues across PrestaShop versions that support PHP 8.1.

This breaking change is documented here : https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.pdo.sqlite

Exemple with Db->executeS() on ps_product table. 
![image](https://github.com/user-attachments/assets/3a232848-bedd-488d-a0a7-f4268b9e220d)
![image](https://github.com/user-attachments/assets/c97d0c1f-286f-40a4-bd96-6d68057fb8b1)

### Expected behavior

The "PDO::ATTR_STRINGIFY_FETCHES" parameter should be set to true on the PDO instance to maintain the historical behavior and avoid breaking changes.

![image](https://github.com/user-attachments/assets/ab8f0b3b-04a1-4532-b58c-efcf70b33296)

### Steps to reproduce

- Run PrestaShop 8.X with PHP 7.4; 
- Dump result of Db-<executeS() query ;
- Run PrestaShop 8.X with PHP 8.1 ;
- Dump result of Db-<executeS() query ;
- Strict compare two result.

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by kpodemski** [comment] 2024-09-05 15:35
@fox-john 

I think you meant strict comparison and `===`?

Because:

`1 == '1'` = true
`1 === '1'` = false

To be honest, I've never encountered this issue since when I want to use strict comparison, I make sure to cast variables, but I do agree that the behavior is different.

I reproduced it, provided solution also works as intended.

**Comment by fox-john** [comment] 2024-09-06 08:48
@kpodemski Yes, sorry, i mean strict comparison with "===". 

I have update my issue, with this change. 

And yes, I also try to cast my variables as much as possible, but the code I work on is not entirely mine, and it is easy to say that 99% of the existing modules do not pay attention to this in 100% of the cases.

**Comment by Hlavtox** [comment] 2024-10-21 20:21
Fixed by https://github.com/PrestaShop/PrestaShop/pull/36875

**Closed as completed by Hlavtox** 2024-10-21 20:21 UTC
Labels: Bug, Major, Developer Feature, PR available, php, Verified, 8.2.x
