### ISSUE TITLE
Button "Place order" from checkout is not enabled with a free order

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#24152] opened 2021-04-21 15:39 UTC
#### Describe the bug

If you disable "Terms of service", it is not possible to place a free order.

#### Expected behavior

Button "Place order" should be enabled automatically.

#### Steps to Reproduce

1. Create a cart rule with a high discount

![image](https://user-images.githubusercontent.com/15104724/115581111-ff478180-a2c7-11eb-95fd-51b601e4011a.png)

2. Disable "Terms of service"

![image](https://user-images.githubusercontent.com/15104724/115581213-16866f00-a2c8-11eb-801e-3c939d60a616.png)

3. Try to finish the order. Button "Place order" is disabled.

![image](https://user-images.githubusercontent.com/15104724/115581265-23a35e00-a2c8-11eb-846a-88b9a19564ac.png)

4. If you enable "Terms of service" the behaviour is correct.

![image](https://user-images.githubusercontent.com/15104724/115581522-5c433780-a2c8-11eb-8e4b-03d9fffbe708.png)

#### Additional information

* PrestaShop version: 1.7.7.3

**Comment by florine2623** [comment] 2021-04-21 16:00
Hello @idnovate ,
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9927.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by florine2623** [comment] 2021-04-21 16:04
Duplicate of #9927

**Closed as completed by florine2623** 2021-04-21 16:04 UTC
Labels: Duplicate
