### ISSUE TITLE
Shop front page - ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Labige** [PrestaShop/PrestaShop#18737] opened 2020-04-21 08:50 UTC
#### Describe the bug

The front page of my shop does not load and says "ERR_TOO_MANY_REDIRECTS" 
Chrome also suggests that I should erase the cookies but I did it and it hasn't changed anything.

If I enable the debug mode I have the following message:
"[Debug] This page has moved
Please use the following URL instead: [My shop url]"

On the contrary to [this ticket](https://github.com/PrestaShop/PrestaShop/issues/17585) I haven't changed anything regarding DB or server. Everything was correctly working a few days ago when I checked.

#### Expected behavior

I expect the front page to appear correctly when the debug mode is off instead of saying "ERR_TOO_MANY_REDIRECTS"

**Screenshots**

Attached is the list of errors that appears when I have the debug mode on and that I go to the backoffice.
[Bugs boutique.pdf](https://github.com/PrestaShop/PrestaShop/files/4508782/Bugs.boutique.pdf)

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 7.0.0

**Comment by rdy4ever** [comment] 2020-04-21 09:25
Hi @Labige 
I would suggest trying the following steps to try and fix your error:
1. Delete var/cache/dev and var/cache/prod folders from your projects web root
2. Rename or delete .htaccess file from the projects web root in order to regenerate it. (You could then go to Preferences->SEO and URLs and deactvate pretty URLs, then reactivate.

**Comment by Labige** [comment] 2020-04-21 10:34
Hi @rdy4ever thank you for quick answer!
Unfortunately this hasn't changed anything.... I usually do not use pretty URLs (attached my configuration)
![Bugs boutique 2](https://user-images.githubusercontent.com/64069182/79856224-5cb2a500-83cc-11ea-958e-0a956bc74ccd.PNG)

**Comment by rdy4ever** [comment] 2020-04-21 10:40
Could you take a look in your database, table `ps_shop_url ` that `domain`, `domain_ssl` and `physical_url` correspond to your current domain? You should have your domain name for both `domain` and `domain_ssl` and `/` for `physical_url`

**Comment by Labige** [comment] 2020-04-21 10:47
Yes I do...

**Comment by rdy4ever** [comment] 2020-04-21 10:59
> Yes I do...

In your case, `physical_url` should be `/boutique/`

**Comment by rdy4ever** [comment] 2020-04-21 11:05
I think to solve the problem is better to create a subdomain for the shop instead of a directory. For example boutique.herosdepapierfroisse.fr and put `boutique.herosdepapierfroisse.fr` in both `domain` and `domain_ssl`, leaving `physical_url` to `/`. This way you will avoid URL redirect problems, as you already have another cms on the main domain.

**Comment by Labige** [comment] 2020-04-21 11:27
> > Yes I do...
> 
> In your case, `physical_url` should be `/boutique/`

Yes it is.
Ok thank you for your advice, but I still don't understand why does the problem appear now as it has worked for years before. But paying for another subdomain does not really fix it, yet I understand why you advise me to do so.

**Comment by rdy4ever** [comment] 2020-04-21 11:34
Subdomains shoud be free, you can add them in cPanel. But if this is a new problem, then it could be a module you installed lately.

**Comment by rdy4ever** [comment] 2020-04-21 11:35
Oh, and if this URL is old, don't change it.

**Comment by Labige** [comment] 2020-04-21 12:04
But I haven't installed something new or even updated a module since November or something like that. I will keep looking for a solution without chaing the URL, thank you for your kind help :)

**Comment by sarahdib** [comment] 2020-04-21 13:04
Hello @Labige 

Please be aware that this bug tracker should be used to report issues only. 
This is a support question. You can try to contact our support. I'll close this issue.

Thanks for your understanding!

**Closed as completed by sarahdib** 2020-04-21 13:04 UTC
Labels: No change required

**Comment by alcinopitchprint** [comment] 2021-05-18 10:16
This worked for me:
1.- Login as Administrator in Prestashop and enable "SSL" and enable "SSL on all pages" options. Both are under Configure -> Shop Parameters -> General.
