### ISSUE TITLE
Phone number not clickable

### ISSUE THREAD

**Issue by Trylam** [PrestaShop/PrestaShop#12212] opened 2019-01-18 13:27 UTC
**Describe the bug**
In category, in description on source code, I try to insert number phone clickable (with href="tel:") and the number appear but it nor clickable. When i return in source code  href="tel:" was disappeared.

**To Reproduce**
1. Go to 'catalog'
2. Click on 'category'
3. Click on 'add category'
4. On 'description' i write a number phone.
5. Click on 'source code'
6. I add '\<a href="tel:+33102030405"\>' and '\</a\> around my phone number
7. Save
8. The phone number appear but it not clickable
9. When i return in the source code, my tag '\<a href="tel:+33102030405"\>' is modified by '\<a\>'

**Additionnal information**
PrestaShop version: 1.7.4.4

**Comment by khouloudbelguith** [comment] 2019-01-18 13:43
Hi @Trylam,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10376 to fix the issue.
It is fixed in the last release 1.7.5.0.
Your ticket is a duplicate of #9685
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-18 13:43
Duplicate of #9685

**Closed as completed by khouloudbelguith** 2019-01-18 13:43 UTC
Labels: Duplicate
