### ISSUE TITLE
BO - Client details template is broken

### ISSUE THREAD

**Issue by saulaski** [PrestaShop/PrestaShop#27244] opened 2022-01-06 13:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Any client details page throws an exception from the view template.
URL: /admin-dev/index.php/sell/customers/{client_id}/view

An exception has been thrown during the rendering of a template ("Notice: Undefined index: isPrestaShopVersionLessThan176").
in src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/view.html.twig (line 51)

![bug-client-details](https://user-images.githubusercontent.com/97030953/148392606-a68bfc57-fbdc-4297-991e-3f6f88d431ef.png)

### Expected behavior

The page should render and display.

### Steps to reproduce

1. Go to Back Office
2. Open Clients menu
3. Click on Clients link
4. Click on any client in the list
5. The client details page fails to display

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4.3

**Comment by saulaski** [comment] 2022-01-06 14:06
Duplicates of #27119

**Comment by hibatallahAouadni** [comment] 2022-01-06 14:24
Duplicate of #27119

**Closed as completed by hibatallahAouadni** 2022-01-06 14:24 UTC
Labels: Bug, Duplicate, Invalid
