### ISSUE TITLE
Issue with double shipping and Prestashop split orders

### ISSUE THREAD

**Issue by nexinet** [PrestaShop/PrestaShop#12745] opened 2019-02-28 10:23 UTC
**Describe the bug**
I have in my store different products and different way of shipping.
I have create for test
3 Different Shipping way and I gave them same configuration
Into product page I have assigned to each product a different shipment.
When I add products on the cart it show in right manner different shipping and calculate shipping according to my configuration, but, when I confirm order prestashop split the order in 3 because I added 3 products and not put the same order with 3 different shipping

To reproduce:

1) create 3 different shipping ways
2) add to 3 product from different category one of this shipping way
3) add these products to the cart
4) create the order and you see order splitted in 3
I make here a Video to understand better to simplify I just do 2 products and 2 shipping:
Link to the video; https://drive.google.com/file/d/1QGjfoeAhYCXQhnHSzOcDXAkqQyvD8K6t/view?usp=sharing

**Comment by khouloudbelguith** [comment] 2019-02-28 10:28
Hi @nexinet,

Thanks for your report.
We are aware of this issue.
Your ticket is a duplicate of #9998
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-28 10:28
Duplicate of #9998

**Closed as completed by khouloudbelguith** 2019-02-28 10:28 UTC
Labels: Duplicate
