### ISSUE TITLE
Private note about customer from order page (new)

### ISSUE THREAD

**Issue by Anthotill** [PrestaShop/PrestaShop#16920] opened 2019-12-26 05:44 UTC
**Describe the bug**
After upgrading PS version from 1.7.5.2 to 1.7.6.2 using 1-Click Upgrade, when we add a private note **from the order page** => ?controller=AdminOrders&vieworder=&id_order=XXX the private note is not saved. It doesn't work only on order page, not on customer information page

**To Reproduce**

1. Go to order and display an order => ?controller=AdminOrders&vieworder=&id_order=XXXX
2. Add a private note and click to save
3. Response is success (green) but response message is "undefinined".
4. Refresh the page to see that the private message is not saved.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![Firebug1](https://user-images.githubusercontent.com/59243605/71459766-51969200-27a9-11ea-95c0-a8708d00aa7f.PNG)
![Capture](https://user-images.githubusercontent.com/59243605/71459779-607d4480-27a9-11ea-9f2e-f3cf066cd59b.PNG)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.26
Each files mentionned on : https://github.com/PrestaShop/PrestaShop/commit/f527f0713089e16491503ef0a7cbf7104e47a38b are ok on my PS version

**Comment by khouloudbelguith** [comment] 2019-12-26 08:59
Hi @Anthotill,

I did not manage to reproduce the issue with PS1.7.6.2 after an upgrade from PS1.7.5.2 using the 1-click upgrade v4.10.0.
I attached a screen record
https://drive.google.com/file/d/1P0OgoUNguWBzpTNZ_BfLriV2E1yXrWW2/view
Thanks to check & feedback.

**Comment by stephR** [comment] 2020-01-08 16:24
Duplicate of #13916

This issue was noticed on 1.7.6.0 and apparently the fixes in #13916 are not enough because I notice too that I have the exact same issue running on 1.7.6.1 

I notice I also get an error with the module "Colissimo" on this page, the ajax request which should display a modal window to create a label fails with a notification message "test".

Even if this module is disabled, I still have the error with the private note too.

**Comment by Anthotill** [comment] 2020-01-08 16:58
> Duplicate of #13916
> 
> This issue was noticed on 1.7.6.0 and apparently the fixes in #13916 are not enough because I notice too that I have the exact same issue running on 1.7.6.1
> 
> I notice I also get an error with the module "Colissimo" on this page, the ajax request which should display a modal window to create a label fails with a notification message "test".
> 
> Even if this module is disabled, I still have the error with the private note too.

Yes you are right, the Colissimo module have a problem in their TPL files (problem with a link badly written), once corrected, it works :-)

**Comment by stephR** [comment] 2020-01-08 19:54
@Anthotill  out of context but do you know which file and line regarding Colissimo ? thanks ! :)

**Comment by khouloudbelguith** [comment] 2020-01-16 11:16
Hi @stephR,

I did not manage to reproduce the issue with PS1.7.6.2, it is OK
https://drive.google.com/file/d/1JmVvZa6ZLtvt7xPNR4VXpYk60bOLPE0i/view
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

About the Colissimo module, as it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Closed as completed by khouloudbelguith** 2020-01-16 11:16 UTC
Labels: Bug, BO, Can't reproduce, Autoupgrade, 1.7.6.2
