### ISSUE TITLE
Problem with prices decimals

### ISSUE THREAD

**Issue by pollat** [PrestaShop/PrestaShop#22269] opened 2020-12-07 08:15 UTC
#### Describe the bug

On Prestashop 1.7.6.5 I setted "0" on "General settings > Number of decimals", but on the front-end prices continue to be showed with 2 decimals (for example 200,00€ instead of 200€).

#### Steps to Reproduce

1. Go to 'General settings'
2. Set "0"on 'Number of decimals'
3. Save
4. Clear cache

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

How can I solve this problem?

**Comment by Hlavtox** [comment] 2020-12-07 09:37
@pollat That setting does not affect the display in FO.

1. Go to your database manager
2. Open ps_currency
3. Edit the currency you want and put 0 into "precision" field
4. Clear cache and there you go. :-)

On 1.7.7, you can manage the "precision" from backoffice, on 1.7.6, you must do it like this.

**Comment by hibatallahAouadni** [comment] 2020-12-07 12:51
Hello @pollat 

This issue has been fixed in our new patch 1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1HMQLYWnGOc5xhVhKWgHS8O8mGSsuj7yO/view

As @Hlavtox mentionned above, follow his steps you solve can your issue.
Thanks @Hlavtox for your quick replies and fix :wink: 

So, I close this issue.
PS: you can see the original fixed issue here #12223

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-07 12:51 UTC
Labels: Duplicate

**Comment by hibatallahAouadni** [comment] 2020-12-07 12:55
Duplicate of #12223
