### ISSUE TITLE
Product on category page display out of stock instead of availlable on order

### ISSUE THREAD

**Issue by Rizzen59** [PrestaShop/PrestaShop#25542] opened 2021-08-08 13:06 UTC
#### Describe the bug

On catagory page i have product display as out of stock even if the product is availlable for order. But if I access to the product page, status is ok and product can be added on cart. More, when I add the product to cart, the status on category page change for the good status until the product are removed from the cart.

Not all product are affected. I searched in code and the problem come from the `out_of_sotck` parameter to define if you can order product out of stock. For some product the value of `out_of_stock` is empty on category page instead of `0`,`1` or `2`. In this case it should be `1`. 

**Product.php line 4907 :**
```
      $row['allow_oosp'] = Product::isAvailableWhenOutOfStock($row['out_of_stock']);
```

Problem is only on category page. 
Home page, product page, search page are ok. 
To avoid loosing customer i disable message on category page

#### Expected behavior

When a product is availlable for order even if its qty equal 0, display on demand on category page.

#### Steps to Reproduce

1. Define product witch capability to be order even if stock are equal to 0
2. Define stock to 0
3. Show product on category page
4. Flag is out of stock instead of On-demand

**Screenshots**

![image](https://user-images.githubusercontent.com/25029253/123515579-3fe0c400-d698-11eb-885c-77ece1205fcc.png)
![image](https://user-images.githubusercontent.com/25029253/123515636-7b7b8e00-d698-11eb-853f-76c3ce5b1a0c.png)

![image](https://user-images.githubusercontent.com/25029253/128632685-d1507f7f-9bf3-4c52-8459-34b62a81d6ac.png)
![image](https://user-images.githubusercontent.com/25029253/128632731-46a0e0c9-5313-4dec-85c8-4040db14b05a.png)

![image](https://user-images.githubusercontent.com/25029253/128632843-5d73b17b-3530-48b5-939e-0583711376be.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version:  7.3.28
* MySQL : 10.4.18-MariaDB-1:10.4.18+maria~stretch-log
* No cache
* Multishop activated (1 group for 2 shop)
* Customer share : no
* Quantity of product share : yes
* Order share : no

Related to ticket: #25137

---
I try to come back on the classic theme to identify if the problem occurs too. At first glance, no message is displaying and it seems to be normal. But classic theme doesn't display out of stock or allows order by default. If stock equal 0, no message is displayed. I try with not allow and allow order:

**themes/classic/templates/catalog/_partials/product-flags.tpl**
```
{block name='product_flags'}
    <ul class="product-flags">
        {foreach from=$product.flags item=flag}
            <li class="product-flag {$flag.type}">{$flag.label}</li>
        {/foreach}
    </ul>
{/block}
```

But if i add the check on allow on order (product.allow_oosp) and display message, we can see that property is not initialize with correct value on catalog part and availability message is wrong : 

**themes/classic/templates/catalog/_partials/product-flags.tpl**
```
{block name='product_flags'}
    <ul class="product-flags">
        {if $product.quantity > 0}
            {foreach from=$product.flags item=flag}
                <li class="product-flag {$flag.type}">{$flag.label}</li>
            {/foreach}
        {else}
            {if !$product.allow_oosp}
                <li class="product-flag out-of-stock">{$product.availability_message}</li>
            {/if}
        {/if}
    </ul>
{/block}
```

**Comment by hibatallahAouadni** [comment] 2021-08-09 13:48
Hello @Rizzen59 

I didn't manage to reproduce the issue with PS1774 and PS1775, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/128716787-9ff289f3-fecc-49f5-af9e-c10eeebed69e.png)

![image](https://user-images.githubusercontent.com/23308427/128716811-24eeb6e4-fade-4ed0-a311-6e86b183bc34.png)

Please check and feedback.
Thanks!

**Comment by Rizzen59** [comment] 2021-08-09 14:06
You can't see the issue if you use the default `product_tag.tpl`. Only tag are display Not the product availlabilibity. 

If you try to use `$product.allow_oosp` or `$product.availability_message` in any tpl on catalog page, value are incorrect.

But these values are ok on product detail page or on module views.

**Comment by hibatallahAouadni** [comment] 2021-08-17 16:09
Hello @Rizzen59 

Thanks for your feedback.
Could you provide the code that you add in `product_tag.tpl` while using these attributes `$product.allow_oosp` and `$product.availability_message` to reproduce the issue.

Thanks in advance :pray:

**Comment by Rizzen59** [comment] 2021-08-19 06:55
No problem : 

```
{block name='product_flags'}
    <ul class="product-flags">
        {if $product.quantity > 0}
            {foreach from=$product.flags item=flag}
                <li class="product-flag {$flag.type}">{$flag.label}</li>
            {/foreach}
        {else}
            {if !$product.allow_oosp}
                <li class="product-flag out-of-stock">{$product.availability_message}</li>
            {/if}
        {/if}
    </ul>
{/block}
```

**Comment by hibatallahAouadni** [comment] 2021-08-19 08:45
Hello @Rizzen59 

After adding the provided code in `themes/classic/templates/catalog/_partials/product-flags.tpl`, I didn't manage to reproduce the issue with PS1774, see the screen record below:

https://drive.google.com/file/d/1m2qhMsC7AvU8GrWbzeE2evZVmuYdYZkC/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-08 14:36
Hello @Rizzen59 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-08 14:36 UTC
Labels: Bug, FO, No change required, 1.7.7.4
