### ISSUE TITLE
IT Standard Rates missing UK and Croatia

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#19642] opened 2020-06-09 08:28 UTC
#### Describe the bug

Because UK and Croatia are in Europe, the IT Standard Rate (22%) for example must contain also UK and Croatia but by default these countries are not preset,

#### Expected behavior

Because UK and Croatia are in Europe if a customer purchase something from Italy without VAT the Tax must be applicated.

#### Steps to Reproduce

Simulate any purchase from UK or Croatia and you will see no italian Taxes applicated

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-10-15 15:06
Hi @HartLarsson ,
Sorry for the late reply.

Could you specify the steps to reproduce ?
What is the config of your shop ?
What is the default currency, country, language, etc

Thanks!

**Comment by HartLarsson** [comment] 2020-10-15 20:37
Hi,

my store is based in italy, Euro is the currency.
Default taxation is 22%

Prestashop default installation forgot to add under 22% Tax the 2 countries.

![image](https://user-images.githubusercontent.com/16102074/96183310-ff408080-0f36-11eb-8bd4-54392fb8922d.png)


I've added them manually

**Comment by khouloudbelguith** [comment] 2020-10-19 08:40
Hi @HartLarsson,

1. What is the exact `Language/Country` did you used during the install of your shop?
2. Did you import any Localization pack? from BO > International > Localization page?

Thanks!

**Comment by HartLarsson** [comment] 2020-10-21 14:09
Used Italian / Italy
I've not used any import Localization Pack.

**Comment by khouloudbelguith** [comment] 2020-10-21 15:49
@HartLarsson,

Thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/96744618-88d3d080-13c5-11eb-97fd-9b50f82786de.png)
But it is fixed in the next release 1780 as reported here: https://github.com/PrestaShop/PrestaShop/issues/16336

Thanks to check and feedback.

**Comment by HartLarsson** [comment] 2020-11-04 22:29
yvw, i think you must plan to update also the 1.7.6.x branch 
Is not really nice to have a available stable branch with bugs, missing things and so on.

**Comment by SimonGrn** [comment] 2020-11-06 08:35
Hello,

we only make patch versions for security reasons and critical/major bugs in the system. We sadly won't make a `1.7.6.9` for such an issue. You can read more about patch versions [here](https://devdocs.prestashop.com/1.7/project/release/minor-release-lifecycle/#when-is-it-decided-to-release-a-patch-).
You can however apply the fix @khouloudbelguith linked (#16336) to your own shop if you know how to do it (be careful and do not do it in production directly, make a backup, all the care measure you would take for an upgrade).
If you are not sure you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you for your understanding.

**Closed as completed by SimonGrn** 2020-11-06 08:35 UTC
Labels: Bug, BO, Won't fix, International, Tax rules, 1.7.6.5

**Comment by SimonGrn** [comment] 2020-11-06 08:38
Hello,

we only make patch versions for security reasons and critical/major bugs in the system. We sadly won't make a `1.7.6.9` for such an issue. You can read more about patch versions [here](https://devdocs.prestashop.com/1.7/project/release/minor-release-lifecycle/#when-is-it-decided-to-release-a-patch-).

Thank you for your understanding.

**Comment by HartLarsson** [comment] 2020-11-06 16:21
> Hello,
> 
> we only make patch versions for security reasons and critical/major bugs in the system. We sadly won't make a `1.7.6.9` for such an issue. You can read more about patch versions [here](https://devdocs.prestashop.com/1.7/project/release/minor-release-lifecycle/#when-is-it-decided-to-release-a-patch-).
> 
> Thank you for your understanding.

i can understand your point of view but running on a new branch 1.7.7 while 1.7.6 is full of problems too seems a suicide for me. Why no make all fix to 1.7.6 branch that are tons (round clculation errors, cart resevation problems, and so on) that are unresolved since 1.6 and when the branch is stable and fixed move on to a new branch?

**Comment by PierreRambaud** [comment] 2020-11-09 07:53
> > Hello,
> > we only make patch versions for security reasons and critical/major bugs in the system. We sadly won't make a `1.7.6.9` for such an issue. You can read more about patch versions [here](https://devdocs.prestashop.com/1.7/project/release/minor-release-lifecycle/#when-is-it-decided-to-release-a-patch-).
> > Thank you for your understanding.
> 
> i can understand your point of view but running on a new branch 1.7.7 while 1.7.6 is full of problems too seems a suicide for me. Why no make all fix to 1.7.6 branch that are tons (round clculation errors, cart resevation problems, and so on) that are unresolved since 1.6 and when the branch is stable and fixed move on to a new branch?

Hi @HartLarsson ,

Trying to fix all issues on the 1.7.6.x branch whereas everything is moving on the 1.7.7.x and develop branches is a suicide for developers, QA analyst, and everyone working on this project (we are a very small team :sweat_smile: ). 
We won't be able to maintain three versions with a lot of complicated fixes such as cart rules, calculation, tax, etc.

Regards

**Comment by HartLarsson** [comment] 2020-11-10 10:28
> > > Hello,
> > > we only make patch versions for security reasons and critical/major bugs in the system. We sadly won't make a `1.7.6.9` for such an issue. You can read more about patch versions [here](https://devdocs.prestashop.com/1.7/project/release/minor-release-lifecycle/#when-is-it-decided-to-release-a-patch-).
> > > Thank you for your understanding.
> > 
> > 
> > i can understand your point of view but running on a new branch 1.7.7 while 1.7.6 is full of problems too seems a suicide for me. Why no make all fix to 1.7.6 branch that are tons (round clculation errors, cart resevation problems, and so on) that are unresolved since 1.6 and when the branch is stable and fixed move on to a new branch?
> 
> Hi @HartLarsson ,
> 
> Trying to fix all issues on the 1.7.6.x branch whereas everything is moving on the 1.7.7.x and develop branches is a suicide for developers, QA analyst, and everyone working on this project (we are a very small team 😅 ).
> We won't be able to maintain three versions with a lot of complicated fixes such as cart rules, calculation, tax, etc.
> 
> Regards

I agree with you Pierre, is why is a suicide to release 1.77 & 1.7.8 while 1.7.6 is continue to be full of errors!
Why not finish one relase put all dev efforts to finish a relase that works fully? 
The way to move so fast to a new release when the previous is full of problems is not helping, developers, integrators and resellers!
You can imagine the Chaos for people that sell solutions on 1.7.6.x branch to patch MANUALLY and alone the 1.7.6.x version grabbing fix from 1.7.7 and 1.7.8 and try to adapting to the previous version?

Small team = low resource => you must slow the releases
If you don't do that the chaos will happens and every release will fix errors but introduce new ones.

Is so necessary to run to move to 1.7.7 and 1.7.8 while 1.6 branch continue to be used anyway and 1.7.6.x is not fully fixed?

**Comment by SimonGrn** [comment] 2020-11-10 10:46
This is an Open Source project, you are welcome to contribute to help fixing theses bugs so we can move forward.

We have this kind of conversation pretty regularly and they lead nowhere so I'm gonna close this thread.

**Comment by matthieu-rolland** [comment] 2020-11-10 11:02
> Is so necessary to run to move to 1.7.7 and 1.7.8 while 1.6 branch continue to be used anyway and 1.7.6.x is not fully fixed?

I'm afraid no project of this size will ever be "fully fixed", bug free software just doesn't exist, that's a myth, you have to move forward at some point.

See the 10 common software myths:  https://onix-systems.medium.com/10-common-software-myths-dispelled-96e1c5d5d014

(myth number 7)

**Comment by matks** [comment] 2020-11-10 13:33
> Small team = low resource => you must slow the releases

Dear @HartLarsson,

The [current release lifecycle of PrestaShop](https://devdocs.prestashop.com/1.7/project/release/patch-release-lifecycle/) is a balance between "the need to stabilize" and "the need to move on". We aim for a new minor release every 6 months although we regularly miss this schedule (so releases are even slower). This is very slow compared to the PHP ecosystem average lifecycle I think (like Laravel, Symfony).

Each new minor release brings in more bugfixes, more patches, more migration, more developer tools. It also brings php upward compatibility which is awaited by a lot of people. We cannot freeze this forever, else PrestaShop will ... stagnate. In the software world, a software that stagnates is a dying software. The world moves fast and the software world moves even faster. PHP versions, PHP dependencies evolve. JavaScript versions, JavaScript dependencies evolve. eCommerce trends evolve, customer needs evolve, developer needs evolve (for example current PrestaShop Webservice is outdated and we need to build a more recent version that follows today best practices for webservices). [PrestaShop has a number of internal/architecture issues](https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-2-pain-points/) that we need to solve with long-term work. Our competitors also evolve. We cannot freeze this all.

So we will continue following this lifecycle that is a compromise between stability and evolution. A compromise between moving towards a better future and improving the present.

If one day PrestaShop business becomes very wealthy we could imagine releasing LTS or having work being done on 2 versions simultaneously. In the current state of the project we do not have this luxury.

By the way this is not just "our" strategy. This is the strategy followed by all major projects because we all are in the same situation. Magento does it. There are unfixed bugs in Magento 1 and they work on Magento 2. WooCommerce does it too. Drupal does it too. They might do more of a A or more of B but everyone has a backlog of bugs that never reaches zero.
It's normal, everybody has to address this subtle balance. [DHH explained this very well in his blog post "Software has bugs. This is normal."](https://m.signalvnoise.com/software-has-bugs-this-is-normal/) Once a project reaches a certain size, there is a never-ending number of bug reports and you cannot solve them all before moving on.

This is not a pleasant answer 😉  but this is the reality about such large scale projects. It cannot be shiny like smaller projects.

What is important, I believe, is that _each new version of PrestaShop is better than the previous_. More tests. More robust. Better documented. Easier to maintain. Easier to read. More up-to-date. This is why we have the ["no regressions" rule](https://devdocs.prestashop.com/1.7/project/release/minor-release-lifecycle/). A bug might wait some time to be fixed but we refuse that a bug that something that was working at some point does not work in the next version.
