### ISSUE TITLE
[1.7.7 beta 2] Create order from backoffice still not working

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20814] opened 2020-09-02 09:05 UTC
#### Steps to Reproduce

1. Install 1.7.7 beta 2 release.
2. Go to Orders. Click create new order.
3. Select customer. 
4. Page is dead.

#### Screenshot
![beta2](https://user-images.githubusercontent.com/6097524/91961965-33a40880-ed0c-11ea-99e2-1a0d61858cbe.PNG)

#### Additional information

* PrestaShop version: 1.7.7 beta 2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-09-02 10:04
Hi @Hlavtox,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/20644 to fix the issue.
Your ticket is a duplicate of #20643
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-09-02 10:04
Duplicate of #20643

**Closed as completed by khouloudbelguith** 2020-09-02 10:04 UTC
Labels: Duplicate
