### ISSUE TITLE
BO Order Page -> Payment adjustment

### ISSUE THREAD

**Issue by matik4** [PrestaShop/PrestaShop#22977] opened 2021-01-25 11:43 UTC
#### Describe the bug

Hello,

Just wanted to highlight a possible bug (as it looks intentional). On the order page in back office, if you edit the order in a way that the total paid changes - let's say I will apply free shipping - you will not be able to balance the total by adding a negative amount in payment details. 

You might probably suggest refunding by using one of the payment modules, but in a case with card payments, merchants should not charge customer's card until the goods are shipped, therefore the charge is 'authorised' and not 'captured'. This allows to simply 'capture' the new adjusted total (since we only 'authorised' the amount, there's no refund). 

#### Expected behavior

Allow negative value to be input as in Prestashop 1.6 for example.

#### Steps to Reproduce

1. Orders -> View -> Apply any discount to existing order to change the total -> Add 'Payment' with negative amount to balance the total

**Screenshots**

https://www.dropbox.com/sh/sepn0799nprj3ts/AADILK1YpNai7vPUFT6ednNka?dl=0

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

Kind Regards,
Mateusz

**Comment by hibatallahAouadni** [comment] 2021-01-25 12:42
Hello @matik4 

You can't add negative value to the payment method. To balance an overdue by the clients, **it is recommended to make a credit slip** (See the [original issue](https://github.com/PrestaShop/PrestaShop/issues/16582#issuecomment-575582954)).

So, I close it cause it's not a bug.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-25 12:42 UTC
Labels: No change required
