### ISSUE TITLE
Localization issue for messages with currencies that have not cents, like KRW

### ISSUE THREAD

**Issue by kamilrafik** [PrestaShop/PrestaShop#29405] opened 2022-08-21 19:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There were some critical errors in localization process when currency did not have cents, like KRW.

Unfortunately, we did not keep full details of the bug. But the solution presented in this PR worked fine for more than month already:  https://github.com/PrestaShop/PrestaShop/pull/29404 Please, see details in code.

### Expected behavior

Absence of cents should not affect localization behavior.

### Steps to reproduce

Unfortunately, detailed logging of steps was not performed.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-08-22 09:55
Hello @kamilrafik 

To test your PR, we need to validate the issue, and to validate it, we need to reproduce it.
Without steps to reproduce and infos, we can not validate the issue and the PR :disappointed: 
So, please provide more infos and steps to reproduce :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-09-12 10:43
Hello @kamilrafik 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-09-12 10:43 UTC
Labels: Bug, BO, Localization, Currencies, PR available, Invalid
