### ISSUE TITLE
Can't import united states localization pack

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13271] opened 2019-04-10 13:49 UTC
**Describe the bug**
Can't import united states localization pack

**To Reproduce**
1. Go to International > Localization
2. Select united states and click on import
3. See error

**Screenshots**
![capture d'écran_1348](https://user-images.githubusercontent.com/13449658/55884378-43b3c900-5ba8-11e9-8f15-3ab1cf7a7c52.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by Quetzacoalt91** [comment] 2019-04-10 13:51
Could be a duplicate of https://github.com/PrestaShop/PrestaShop/issues/13247

**Closed as completed** 2019-04-15 09:25 UTC
Labels: Bug, Major, International, Localization, Regression, Fixed, 1.7.6.x
