### ISSUE TITLE
Uncaught Exception: You have requested a non-existent service "prestashop.core.addon.theme.theme_provider".

### ISSUE THREAD

**Issue by benchonaut** [PrestaShop/PrestaShop#31293] opened 2023-02-09 14:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

* V1.7.7.3

### non-devmode-enabled: 
![image](https://user-images.githubusercontent.com/12718580/217834879-6d7423fc-cc51-43e0-91b6-2db725f94333.png)

### devmode-enabled: 
![image](https://user-images.githubusercontent.com/12718580/217833614-3082cab5-a095-40eb-826e-68f2244490f0.png)

### happens during 
*  ### ( module init part)
   ```
   use PrestaShop\PrestaShop\Core\Addon\Theme\ThemeProviderInterface;
   use PrestaShop\PrestaShop\Core\Module\WidgetInterface;
   ```
* ### ( failing part )
   ```
   $themeProvider = $this->get('prestashop.core.addon.theme.theme_provider');
   ```
   ↑↑ executed by module 

## strangeness: 

* i can export the theme , 
 this code in `src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php`
 works 
 ```
 public function exportAction()
    {
        $themeProvider = $this->get('prestashop.core.addon.theme.theme_provider');
        $exporter = $this->get('prestashop.core.addon.theme.exporter');

        $path = $exporter->export($themeProvider->getCurrentlyUsedTheme());

 ```
 but the in the module it fails

## trace → more exactly ( in-depth )

```
You have requested a non-existent service "prestashop.core.addon.theme.theme_provider".
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException 0]
```
this (should) be a result of 
`var/cache/dev/ContainerIuhxoax/getPrestashop_Core_Addon_Theme_ThemeProviderService.php`
OR
`var/cache/prod/ContainerIuhxoax/getPrestashop_Core_Addon_Theme_ThemeProviderService.php`

whereas this file says 
```
return $this->services['prestashop.core.addon.theme.theme_provider'] = new \PrestaShop\PrestaShop\Core\Addon\Theme\ThemeProvider(${($_ = isset($this->services['prestashop.core.addon.theme.repository']) ? $this->services['prestashop.core.addon.theme.repository'] : $this->load('getPrestashop_Core_Addon_Theme_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->shop->theme);
```

by digging deeper i found that prestashop.core.addon.theme.repository will be constructed from 

`var/cache/[dev_OR_prod]/ContainerIuhxoax/getPrestashop_Core_Addon_Theme_RepositoryService.php`

by the statement

```
return $this->services['prestashop.core.addon.theme.repository'] = new \PrestaShop\PrestaShop\Core\Addon\Theme\ThemeRepository(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->shop);
```

* i dont know how to check prestashop.adapter.legacy.configuration ( except writing a module that logs this  with try-catch )

* this system was upgraded by 1-click-upgrader 

* i dont get further into it right now , checked the vendor folder against the 1.7.7.3 release zip , 
   the "non-orig" files are the composer installers and 1 test file

```
b1c4e988ccc36553752db5d1d598fa7d  vendor/composer/installers/src/Composer/Installers/CiviCrmInstaller.php
a0bd458f0ef4e2bb05cd645968be81c1  vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
220f66da9ebad991c7610e90cf9067ec  vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
576e684aa434af2fa98e753400766f62  vendor/composer/installers/src/Composer/Installers/Plugin.php
37b4eff9e56004a6657c3515d53188e4  vendor/composer/installers/src/Composer/Installers/DrupalInstaller.php
482e2806bbafb01efd4e1937d7eb0d11  vendor/composer/installers/src/Composer/Installers/KnownInstaller.php
8f5ee137e6592b1acacd9f55f543fbe4  vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
f40803e2a921b23a254f8847ae8a93b0  vendor/composer/installers/src/Composer/Installers/Installer.php
1495b43d0ca1120a38cf017512cf17f5  vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
45084203f42ab1f4e5f2c304b03a72d0  vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
fe04b064ee33cdae252e590487998480  vendor/composer/installers/src/Composer/Installers/MediaWikiInstaller.php
235b939331039f453de8273fe7cfc2bd  vendor/composer/installers/src/Composer/Installers/MicroweberInstaller.php
3b3c814abbbed4452624f3f49464a763  vendor/composer/installers/src/Composer/Installers/DframeInstaller.php
48d9ef5737e650412cbaff1f4978277f  vendor/composer/installers/src/Composer/Installers/WHMCSInstaller.php
7afa5102c681321ccfa6da44e3c71304  vendor/composer/installers/src/Composer/Installers/SyliusInstaller.php
29a790b5e0ecea8afdbaeb5e52212dc2  vendor/composer/installers/src/Composer/Installers/Redaxo5Installer.php
d7e3827b9484d6585463a2cd3c9f9e86  vendor/composer/installers/src/Composer/Installers/MantisBTInstaller.php
d41d8cd98f00b204e9800998ecf8427e  vendor/symfony/symfony/src/Symfony/Component/Finder/Tests/Fixtures/r+e.gex[c]a(r)s/dir/bar.dat

```

### Expected behavior

Run the plugin by returning 

       $this->get('prestashop.core.addon.theme.theme_provider');

### Steps to reproduce

1. setup presta 1.7.7.3 , no changes to the relevant controllers or hooks 
2. install a plugin that uses 
`$themeProvider = $this->get('prestashop.core.addon.theme.theme_provider');` 
3. see the fail

### PrestaShop version(s) where the bug happened

1.7.7.3
( working with 1.7.7.8 etc. )

### PHP version(s) where the bug happened

PHP7.3

### If your bug is related to a module, specify its name and its version
 ( unreleased ) , you might try https://is.gd/ps_turnstile

---
P.S. : i would recommend to just upgrade if someone asked me , but maybe $any1 has a clue

**Comment by hibatallahAouadni** [comment] 2023-02-13 12:10
Hello @benchonaut 

Bravo 👏 thanks for detailed bug report 🙌 
This issue is too technical for me 😓 So ping @PrestaShop/prestashop-core-developers can someone please try to reproduce the issue 🙏 

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-01 07:32
Hello @benchonaut 

Do you still encounter the issue with PS81x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-29 14:16
Hello @benchonaut 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-29 14:16 UTC
Labels: Bug, BO, Theme & logo, Modules & Themes, Invalid, 8.1.x
