### ISSUE TITLE
Very Slow Cart actions on 15k Product store

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#29558] opened 2022-09-06 18:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

My store has 15K Products, some modules that I bought and a custom theme.

I find it very slow to:

- Add products to cart (5 seconds)
- Recalculate price if you add more items of a specific product (7 seconds)
- Delete product from cart (7 seconds).

The rest of the store seems ok.

Now, I just copied it to a testing environment and:

- Disabled all the modules and cleared cache - No speed improvements
- Changed to default theme  and cleared cache - No speed improvements
- Deleted my store catalog (all products) and created a testing product - expected speed now <1s to do those actions.

I also installed a clean PS store on the same production server to assess the performance, and with a clean install everything works fine.

Now, I get that you'll say that you can't reproduce, etc... however it seems to me that on a real world store, with a good amount of products (in my case 15K), this might happen.

I also saw this: https://github.com/PrestaShop/PrestaShop/issues/29028 but I'm not sure if my problem has anything to do with that.

Server software version: Apache
PHP version: 7.4.3
Memory limit: 2G
Max execution time: 60
Upload Max File size: 128M

MySQL version: 8.0.30-0ubuntu0.20.04.2
MySQL server: 127.0.0.1
MySQL name: x
MySQL user: x
Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPDO

Required parameters: OK
Optional parameters: OK

### Expected behavior

All the cart actions shouldn't take more than 1s - 1.5s

### Steps to reproduce

1 - Install a PS store v. 1.7.8.7
2 - Load 15K products into your catalog
3 - Test your cart actions speed.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2022-09-07 08:47
Hello @seederp2p ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14979.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by florine2623** [comment] 2022-09-07 08:48
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/14979

**Closed as completed** 2022-09-07 08:48 UTC
Labels: Bug, Duplicate

**Comment by seederp2p** [comment] 2022-09-07 08:57
hello @florine2623 

Are you sure this is the same issue?

My report doesn't depend on the number of products on the cart.
