### ISSUE TITLE
Error updating modules

### ISSUE THREAD

**Issue by TelasMonti** [PrestaShop/PrestaShop#34015] opened 2023-09-21 09:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have almost 40 updates to do in my Prestashop and when I want to do it I get an error. The error is the following "Could not perform action update for module undefined"
The modules I am trying to update are all free and native to Prestashop itself. I have tried updating the modules individually, all together and it has not worked. I have also tried updating the modules by putting the page in maintenance.
![Error_que_aparece](https://github.com/PrestaShop/PrestaShop/assets/145661877/a0d2d3ad-df99-431e-930a-0f1ebe31533e)

### Steps to reproduce

1. I go to modules.
2. Module manager.
3. Updates.
4. Error.

### PrestaShop version(s) where the bug happened

1.7.8.7

### Your company or customer's name goes here (if applicable).

Telas Monti

**Comment by aniszr** [comment] 2023-09-21 16:12
Hello @TelasMonti 

I couldn't reproduce your issue with provided informations!

Could you please Clear the cache using the appropriate command in Advanced parameters> Performance then enable debugging (Advanced parameters> Performance) and retry the upgrade process!

Thank you!

**Comment by TelasMonti** [comment] 2023-09-26 07:34
Hola!

Acabo de hacer lo que me comentas, pero me sigue saliendo el mismo error. 

![12](https://github.com/PrestaShop/PrestaShop/assets/145661877/53c4b51a-c13c-41eb-8d4f-f17c2cb11650)

**Comment by paulnoelcholot** [comment] 2023-09-27 16:06
Hello @TelasMonti,

I tried to reproduce your issue but I can't. Could you give me additional information that could help us better understand the specificity of your case?

Thanks for your feedback!

**Comment by TelasMonti** [comment] 2023-09-28 07:25
Hola, 

Es que no sé que más información podría darles. Me salta el mensaje de "could not perform action update for module undefined" cada vez que intento actualizar un módulo. Y todos los módulos que tengo son propios y gratuitos del Prestashop. 

Si me decís que necesitáis para poder guiarme en resolver esto os lo digo sin problema.

Gracias.

**Comment by florine2623** [comment] 2023-10-03 14:13
Hello @TelasMonti ,

I can't reproduce your issue. I'm closing it since it wasn't reproduced by multiple people.

https://github.com/PrestaShop/PrestaShop/assets/16019289/5c0adb31-56d6-4450-999f-d30c590257c5


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2023-10-03 14:13 UTC
Labels: Bug, BO, 1.7.8.x, Invalid, Module
