### ISSUE TITLE
Can't save & edit combinations - not working on client server PS1.7.3.3

### ISSUE THREAD

**Issue by MarekKaliszuk** [PrestaShop/PrestaShop#11471] opened 2018-11-22 10:22 UTC
Hello,

i have same shop on two servers. One is strong vps second is hosted (client server). On my vps server saving combinations is working flawless. On client server  i can't generate and save combinations at all. Here is alert (can't save)  plus some errors in background:

Data posted in background:

```
Request URL: https://xxxxx.pl/admin64xxxxsgpnnp/index.php/product/form/5346?_token=832tfg49VMG0wOZlyg0D_ZTbpo9A9Vc27zrAhXyqWN8
Request Method: POST
Status Code: 400 
```
```
form[step1][name][1]: Acrilic master test  new
form[step1][name][8]: Acrilic master test  new
form[step1][description_short][1]: 
form[step1][description_short][8]: 
form[step1][description][1]: 
form[step1][description][8]: 
form[step1][id_manufacturer]: 
form[step1][id_category_default]: 2
form[step1][categories][tree][]: 2
ignore: 2
form[step1][new_category][name]: 
form[step1][new_category][id_parent]: 2
show_variations: 1
form[step6][reference]: 
form[step1][qty_0_shortcut]: 5
form[step1][price_shortcut]: 4,065041
form[step1][price_ttc_shortcut]: 5
form[step2][id_tax_rules_group]: 1
form[step3][qty_0]: 5
form[step3][minimal_quantity]: 1
form[step3][low_stock_threshold]: 
form[step3][virtual_product][is_virtual_file]: 0
form[step3][virtual_product][name]: 
form[step3][virtual_product][nb_downloadable]: 
form[step3][virtual_product][expiration_date]: 
form[step3][virtual_product][nb_days]: 0
form[step3][pack_stock_type]: 3
form[step3][attributes]: 121, 39, 40
options[8][121]: 121
options[8][39]: 39
options[8][40]: 40
product_combination_bulk[quantity]: 
product_combination_bulk[cost_price]: 
product_combination_bulk[impact_on_weight]: 
product_combination_bulk[impact_on_price_te]: 
product_combination_bulk[impact_on_price_ti]: 
product_combination_bulk[date_availability]: 
product_combination_bulk[reference]: 
product_combination_bulk[minimal_quantity]: 
product_combination_bulk[low_stock_threshold]: 
product_combination_bulk[_token]: vX4xPAQtlaAlWFNsAYoPw2-Ab4FMNClwCK2-FpkABP0
form[step3][out_of_stock]: 2
form[step3][available_now][1]: 
form[step3][available_now][8]: 
form[step3][available_later][1]: 
form[step3][available_later][8]: 
form[step4][width]: 0
form[step4][height]: 0
form[step4][depth]: 0
form[step4][weight]: 0
form[step4][additional_delivery_times]: 1
form[step4][delivery_in_stock][1]: 
form[step4][delivery_in_stock][8]: 
form[step4][delivery_out_stock][1]: 
form[step4][delivery_out_stock][8]: 
form[step4][additional_shipping_cost]: 0,000000
form[step2][price]: 4,065041
form[step2][price_ttc]: 5
form[step2][unit_price]: 0,000000
form[step2][unity]: 
form[step2][ecotax]: 0,000000
form[step2][id_tax_rules_group]: 1
form[step2][wholesale_price]: 0,000000
form[step2][specific_price][sp_id_shop]: 1
form[step2][specific_price][sp_id_currency]: 
form[step2][specific_price][sp_id_country]: 
form[step2][specific_price][sp_id_group]: 
form[step2][specific_price][sp_id_product_attribute]: 
form[step2][specific_price][sp_from]: 
form[step2][specific_price][sp_to]: 
form[step2][specific_price][sp_from_quantity]: 1
form[step2][specific_price][leave_bprice]: 1
form[step2][specific_price][sp_reduction]: 0,000000
form[step2][specific_price][sp_reduction_type]: amount
form[step2][specific_price][sp_reduction_tax]: 1
form[step2][specificPricePriority_0]: id_shop
form[step2][specificPricePriority_1]: id_currency
form[step2][specificPricePriority_2]: id_country
form[step2][specificPricePriority_3]: id_group
form[step5][meta_title][1]: 
form[step5][meta_title][8]: 
form[step5][meta_description][1]: 
form[step5][meta_description][8]: 
form[step5][link_rewrite][1]: acrilic-master-test-new
form[step5][link_rewrite][8]: acrilic-master-test-new
form[step5][redirect_type]: 404
form[step6][visibility]: both
form[step6][display_options][available_for_order]: 1
form[step6][display_options][show_price]: 1
form[step6][tags][1]: 
form[step6][tags][8]: 
form[step6][condition]: new
form[step6][isbn]: 
form[step6][ean13]: 
form[step6][upc]: 
form[step6][attachment_product][name]: 
form[step6][attachment_product][description]: 
hook_name: displayHome
form[id_product]: 5346
form[_token]: OMo31T8k3evwoSXH7M9JjpdZ9o-z0qiVw897Yi2XkTg
```
Response error:

```
{combination_7066_attribute_ecotax: ["This value should not be blank."],…}
combination_7066_attribute_ecotax: ["This value should not be blank."]
0: "This value should not be blank."
combination_7066_attribute_minimal_quantity: ["This value should not be blank."]
combination_7066_attribute_quantity: ["This value should not be blank."]
combination_7067_attribute_ecotax: ["This value should not be blank."]
combination_7067_attribute_minimal_quantity: ["This value should not be blank."]
combination_7067_attribute_quantity: ["This value should not be blank."]
combination_7068_attribute_ecotax: ["This value should not be blank."]
0: "This value should not be blank."
combination_7068_attribute_minimal_quantity: ["This value should not be blank."]
0: "This value should not be blank."
combination_7068_attribute_quantity: ["This value should not be blank."]
 
```

On screen there are errors in background. I've tested generating combinations on new and old products. Both are not working. Somehow new product when first time combination is created - it remembers how many of combinations were used (0/3). After that when i open product in admin panel there is also error on reading combinations: 

```
https://xxxx/xxxxadmingpnnp/index.php/combination/7066-7067-7068?_token=832tfg49VMG0wOZlyg0D_ZTbpo9A9Vc27zrAhXyqWN8

Request Method: GET
Status Code: 500 
```
And it logs  php error:

```
[21-Nov-2018 19:26:34 Europe/Warsaw] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message '"" cannot be interpreted as a number' in /home/xxxxx.pl/vendor/prestashop/decimal/src/Number.php:466
Stack trace:
#0 home/xxxxx.pl/vendor/prestashop/decimal/src/Number.php(72): PrestaShop\Decimal\Number->initFromString('')
#1 home/xxxxx.pl/src/Adapter/CombinationDataProvider.php(131): PrestaShop\Decimal\Number->__construct('')
#2 home/xxxxx.pl/src/Adapter/CombinationDataProvider.php(94): PrestaShop\PrestaShop\Adapter\CombinationDataProvider->completeCombination(Array, Object(Product))
#3 home/xxxxx.pl/src/PrestaShopBundle/Controller/Admin/CombinationController.php(44): PrestaShop\PrestaShop\Adapter\CombinationDataProvider->getFormCombinations(Array, 1)
#4 [internal function]: PrestaShopBundle\Controller\Admin\CombinationController->generateCombinationFormAction('7066-7067-7068')
#5 home/xxxxx.pl/app/bootstrap. in /home/weblider/ftp/sklep.apapolska.pl/app/bootstrap.php.cache on line 3231
```
 
ScreenShots:
[screen1](https://ibb.co/eHUSQV)
[screen2](https://ibb.co/jxpizq)

How to recreate?
- Create new product
- Add combination to product
- Click generate

What occurs?
- After clicking generate noting happens
- There is error in background releated to lack of values
- Generared combination list is empty(should be filled with added attributes - probably that causes errror)
- When opening product where (above) error occured it show that combination exist  0/1 (for example) - but no attributes on list + error 500 on loading in background. There is screenshot of that.

Any ideas how to fix it?

Presta 1.7.3.3

PHP 5.6

kind regards

Mark

**Comment by khouloudbelguith** [comment] 2018-11-22 10:30
Hi @w0lf1991,

This issue occurs randomly in your case?
After clicking on generate button & the generated combination list is empty if you refresh the page, the list will be displayed?
Because we are aware of this issue: https://github.com/PrestaShop/PrestaShop/issues/9826
Thanks to check & feedback.

**Comment by MarekKaliszuk** [comment] 2018-11-22 10:40
I've tested in few situations and it seems  not random:
- old product + old attribute = not working
- old product + new attribute = not working
- new product + old attribute = not working
- new product + new attribute = not working

I have VPS server where it's working normal. On client serwer (not vps powered) - it's not working.

After clicking on generate button - there is still empty list (should be loaded via ajax but it's not)
After generating with error + refresh - there is info that combination exist like (mass actions - 0/1 choosen combinations)  but list is empty.

**Comment by khouloudbelguith** [comment] 2018-11-22 13:12
@w0lf1991, if you enable the debug mode are there any exceptions displayed?
You can enable the debug mode in BO => Advanced Parameters => Performance page.
Thanks!

**Comment by MarekKaliszuk** [comment] 2018-11-22 17:11
I see no exceptions on debug mode. But i've visited ajax url which is not loading and throwing 500(for product with generated combinations but failing to load in table)

Here are screenshots:
https://ibb.co/kFFrLV
https://ibb.co/dqacSA

**Comment by khouloudbelguith** [comment] 2018-11-23 08:05
@w0lf1991, your problem is fixed in the 1.7.3.2, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/8948, could you please check your files with the [fix](https://github.com/PrestaShop/PrestaShop/pull/8948/files)
If yes, I advise you to updated your shops to PHP 7 already, why keep a slow version of PHP?
Thanks!

**Comment by MarekKaliszuk** [comment] 2018-11-23 09:20
Yes i saw 1.7.3.2 before posting bug report. I had fixed files. 

Well i would like to use php 7.2 for testing (i have only that version on server) but it's crashing presta pretty hard - BO  500 error, front in pieces. I would like not to update to 1.7.4 on client server. If something go wrong i will be in deep sh*t.

**Comment by khouloudbelguith** [comment] 2018-11-23 11:18
ping @mickaelandrieu, what do you think?

**Comment by MarekKaliszuk** [comment] 2018-11-23 12:24
I  have spent few hours on debuging problem. It's looks like releated to database - not presta files.
How i debug problem:
- on my VPS  is a copy of client shop where combinations are working flawless  (dev before production)
- on client server - they're not working at all

So i've copied client shop(production) to my server and created new database (fully exported from client db). And i've noticed that shop has same problem as on client server but on mine VPS.

Now i tried to find where is a problem exacly. Php/ajax errors suggested  that some files were changed. I've copied folder by folder from my working shop to client exported copy - result - not working.

So maybe database?  I've used exported production database to switch with my working ones on vps. Well after that combinations stopped working at all. I've did reverse - i've used my working db on my shop and combinations are working as they did - flawless. So problem in 99% exist in database. But where - that's a nice riddle before weekend. Interesting is that both shops - dev and production had same database copy and something had to change in 1-1,5 months on production server.

**Comment by khouloudbelguith** [comment] 2018-11-23 14:42
Hi @w0lf1991,

You can find the full schema for 1.7.3.3 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.3.3/install-dev/data/db_structure.sql
Thanks!

**Comment by MarekKaliszuk** [comment] 2018-11-25 18:57
After testing with clean sql schema i've found error:

```
`PrestaShopDatabaseException in Db.php line 746:
Duplicate entry '7072-1' for key 'PRIMARY'<br /><br /><pre>INSERT INTO `ps_product_attribute_shop` (`id_product_attribute`, `id_product`, `wholesale_price`, `price`, `ecotax`, `weight`, `unit_price_impact`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `default_on`, `available_date`, `id_shop`) VALUES ('7072', '5347', '0', '0', '0', '0', '0', '1', NULL, '0', NULL, '0000-00-00', '1')</pre>`
```

Im not sure how to fix it. It shows that  key exist in database. I've search for id_product_attribute 7072 and id_shop 1 - there is one but it belong to totaly different product. SHall i remove this key to get rid off non unique errors?

**Comment by khouloudbelguith** [comment] 2018-11-27 07:41
Hi @w0lf1991, 

Did you use the multishop context?
We have the same issue [here](https://github.com/PrestaShop/PrestaShop/issues/9664)
It is added to our bug roadmap.
Thanks to check & feedback.

**Comment by MarekKaliszuk** [comment] 2018-11-28 10:48
Well after spending more that 10h on debuging i've created peace of code that cleans database. For some reason on client server  table ps_product_attribute and ps_product_attribute_shop had different id_product for the same attribute.

This code displays differences between tables which causing duplicate key problem AND FIXES wrong id_products in ps_product_attribute_shop table:

```
`<?php
$servername = "localhost";
$username = "x";
$password = "x";
$dbname = "x";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT * FROM ps_product_attribute";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
    echo 'count '.$result->num_rows.'<br>';
    $diff = 0;
    while($row = $result->fetch_assoc()) {
        $sqlX = 'SELECT * FROM ps_product_attribute_shop WHERE id_product_attribute = '.$row['id_product_attribute'];
        $resultX = $conn->query($sqlX);
        if ($resultX->num_rows > 0) {
            while($rowX = $resultX->fetch_assoc()) {
                if($row['id_product'] != $rowX['id_product']){
                    $diff++;
                    echo 'id_product / id_product_attribute  '. $row['id_product'].'/'.$row['id_product_attribute'].' - '. $rowX['id_product'].'/'.$rowX['id_product_attribute'].'<br>';
                    $sqlY = 'UPDATE ps_product_attribute_shop
                            SET id_product = '.$row['id_product'].'
                            WHERE id_product_attribute = '.$row['id_product_attribute'].';';
                    $resultY = $conn->query($sqlY);
                }
            }
        }
    }
    echo 'Znaleziono roznych id product :'.$diff;
} else {
    echo "0 results";
}
$conn->close();
?>
`
```

Problem could persist when there are some wrong rows in table (errors on my presta caused  missing data in attribute table then script had problem with inserting new data. I've made also script for cleaning my tables:

```
<?php
$servername = "localhost";
$username = "x";
$password = "x";
$dbname = "x";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT * FROM ps_product_attribute_shop pas WHERE  NOT EXISTS (SELECT *
                   FROM   ps_product_attribute pa
                   WHERE  pas.id_product_attribute = pa.id_product_attribute) ";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
    echo 'count '.$result->num_rows.'<br>';
    $diff = 0;
    while($row = $result->fetch_assoc()) {
        echo "id_product: " . $row["id_product"]. " - id_p_a: " . $row["id_product_attribute"]."<br>";
        $sqlX = "DELETE FROM ps_product_attribute_shop WHERE id_product=$row[id_product] AND id_product_attribute=$row[id_product_attribute];";
        $resultX = $conn->query($sqlX);

    }
    echo 'Znaleziono roznych id product :'.$diff;
} else {
    echo "0 results";
}
$conn->close();
?>
```
And now adding combinations works flawless. 

Well there is still question why it happend on client server...
There should be something like rollback if query or code fails.

**Comment by khouloudbelguith** [comment] 2018-11-28 11:08
Hi @MarekKaliszuk,

Good work, glad it is solved for you!
About your question, we just manage to reproduce the issue when we have enabled the multishop context like described in this [ticket](https://github.com/PrestaShop/PrestaShop/issues/9664), & I think it is different in your case.
Since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-28 11:08 UTC
Labels: Bug, BO, Combinations, Fixed
