### ISSUE TITLE
ps_wirepayment error

### ISSUE THREAD

**Issue by WebShopDesigners** [PrestaShop/PrestaShop#34766] opened 2023-12-04 20:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

ps_wirepayment/controllers/front/validation.php
error in:
$this->module->validateOrder($cart->id, Configuration::get('PS_OS_BANKWIRE'), $total, $this->module->displayName, NULL, $mailVars, (int)$currency->id, false, $customer->secure_key);
![2023-12-04_211028](https://github.com/PrestaShop/PrestaShop/assets/152921133/a9afa212-99f1-4363-83ec-e53f9654a197)

### Expected behavior

Get a cart error

### Steps to reproduce

2. click on

### PrestaShop version(s) where the bug happened

1.7.4.2

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

WSD

**Comment by paulnoelcholot** [comment] 2023-12-07 00:08
Hello @WebShopDesigners,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- step to reproduce
- debug mode report

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you

**Comment by florine2623** [comment] 2023-12-27 15:16
Hello ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-12-27 15:16 UTC
Labels: Bug, BO, Modules, Wire payment, 1.7.4.2
