### ISSUE TITLE
 Referrers problem

### ISSUE THREAD

**Issue by Azur42** [PrestaShop/PrestaShop#15830] opened 2019-10-04 09:26 UTC
This bug is present in Prestashop since a long time, and unfortunately It seems no one at Prestashop does care about Referrers !  My Prestashop site in 1.7.5.2 (and PHP 7.0.33), but as of today this bug concern all 1.7 versions, and still exists in the last 1.7.6.1 !

The documentation (http://doc.prestashop.com/display/PS17/Referrers) confirm it is possible to create and use Referrers and states :
 

> When you create an affiliate campaign for a site, you can grant that site access to all of the activity it will have made for your site, through a password-protected URL: http://example.com/modules/trackingfront/stats.php.

 but the Referrers are unable to access to their page on http://example.com/modules/trackingfront/stats.php, they just got a blank page !! 

It is very bad this bug is not considered, as Referrers is truly an important lever for commerce !

Thanks if anyone could pay attention to this important missing feature

**Comment by khouloudbelguith** [comment] 2019-10-04 09:29
Hi @Azur42,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9780
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-04 09:29
Duplicate of #9780

**Closed as completed by khouloudbelguith** 2019-10-04 09:29 UTC
Labels: Duplicate

**Comment by Azur42** [comment] 2019-10-04 09:37
Thanks khouloudbelguith , I was not aware for ticket #9780, so I will follow it.

Thanks again for your support !
