### ISSUE TITLE
Regression - Product thumbnails always uses cover and doesn’t allow customization anymore

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#19029] opened 2020-05-07 08:52 UTC
#### Describe the bug

Introduced into https://github.com/PrestaShop/PrestaShop/commit/79753f45c60ee641763c476ef34d5d61d61ae8a6 in branch 1.7.7.x and develop

#### Expected behavior

We expect to be able to change the `id_image` on a product array after defining a specific id_product_attribute (covered by `ImageRetriever::getProductImages`).

For an unknown reason, this behaviour has been changed and static call to Product::getCover have been introduced.
`Product::getCover` method does not take any combination into consideration or does not allow any override of it using hooks, like it was possible using `actionGetProductProperties`* hooks.

#### Steps to Reproduce

Use the classic theme using branch 1.7.7 develop
BTW, this bug does not exists into classic-rocket project (ping @prestarocket)

#### Additional information

* PrestaShop version: 1.7.7 and more

**Comment by atomiix** [comment] 2020-05-11 12:05
Hi @prestamodule 

Thanks for your feedbacks. @PrestaShop/prestashop-core-developers What do you think?

**Comment by PierreRambaud** [comment] 2020-05-11 12:42
It's more a question for @PrestaShop/prestashop-product-team :)
As you said, the problem doesn't appears in clasic-rocket because it's a decision that has been taken for the classic theme only, feel free to improve your theme to reuse the wanted behavior :thinking:

**Comment by PrestaEdit** [comment] 2020-05-11 12:45
Of course not, the problem is not the used theme. If you do something in the Classic, you will have all the theme follow them. And somes behavior (used in somes modules) are now broken with the Classic one.

**Comment by colinegin** [comment] 2020-05-12 12:41
Hello @prestamodule, thanks for the feedback. 
Indeed, we have introduced a change in product thumbnails in 1.7.7 following this issue : https://github.com/PrestaShop/PrestaShop/issues/12241. As you can see it was very demanded (topwatchers label).

Could you explain in more details in which situations you need to customize the thumbnail ? 
Which modules need this ? 

Thanks !

**Comment by PrestaEdit** [comment] 2020-05-12 12:46
Advanced Search 4 use it. And more: Products by Attributes.

**Comment by prestamodule** [comment] 2020-05-12 12:53
Hey @colinegin, it may be a very demanded "feature", but we are not complaining about this.

First, using static call to Product class to retrieve the cover doesn't allow any contributor/developer to change this behaviour without overriding core files (which you want to completely disallow on 1.7, using Symfony services).
So, we are complaining about this.

Despite making a big regression here (this behaviour exists since 1.5), we cannot change the displayed image anymore, which is a big problem for all your merchants that are having catalogs  using colors.

For example, you want to search a red skirt using search facets.
While selecting red facet, you want to see red skirt only, with their associated images.
Why would i want to display a blue skirt while i'm searching for a red skirt ? that is a non-sense.

I really don't understand why it has been done like this, while there was others way to do it.
We could revert the template file and introduce the use of the cover into the Product presenter class.

This way, we could still override the id_image using the existing hooks, like before.
Like this, nothing is broken on contributor/developer side, only the native behaviour is changed (we still think that it's strange, but anyway).

Please reconsider this because most of themes are based on classic code, and this change will spread on all of them and make many modules not working anymore.

**Comment by colinegin** [comment] 2020-05-13 16:46
What do you think about it @PrestaShop/prestashop-core-developers ?

**Comment by jolelievre** [comment] 2020-05-13 17:47
Maybe we can see if the modif that was made in the template can be done in PHP, maybe in the ProductLazyArray:
https://github.com/PrestaShop/PrestaShop/blob/4505c0b24efeff28422f2063af2fc21fc6bfeb4d/src/Adapter/Presenter/Product/ProductLazyArray.php#L593-L609

I don't know fully the behaviour of `actionGetProductProperties` after that, but that's an idea, maybe the Presenter is a better option, this needs to be tested.

@prestamodule does your module rely on `actionGetProductProperties` to modify this `cover` field in the array?

I'm not sure I understand fully the previous issue https://github.com/PrestaShop/PrestaShop/issues/12241 But maybe it was a bad idea to force displaying the cover as it prevents search modules to display the image matching the searched attribute 😕

**Comment by kpodemski** [comment] 2020-05-13 17:56
IMHO it's a good change (i mean, logic is good) because main image should be indeed, a cover, not a default combination image, but it needs to be possible to change this behavior. I wrote about few other things here:
https://github.com/PrestaShop/PrestaShop/pull/15748

You shouldn't make a call to `Product` from your template file if you have entire `ProductPresenter` available...

Also, from what i see, it's getting **original** image, this is insane, original images can be like 5MB or more...

**Comment by prestamodule** [comment] 2020-05-13 21:06
> @prestamodule does your module rely on `actionGetProductProperties` to modify this `cover` field in the array?

@jolelievre We are defining a specific `id_product_attribute` on each product before providing the full product array to `ProductSearchResult::setProducts()` method.
This behaviour works fine since PrestaShop 1.7.0.
On PrestaShop 1.6, we were defining a specific `id_image` & `id_product_attribute`

**Comment by eternoendless** [comment] 2020-05-14 09:08
I don't know the specifics of this bug but looking at the [change](https://github.com/PrestaShop/PrestaShop/commit/79753f45c60ee641763c476ef34d5d61d61ae8a6) it looks like something that would be best done by adding a property in the presented  product, then using that property in the template.

**Comment by hadjedjvincent** [comment] 2020-05-14 10:11
I would really suggest to revert the mentioned commit into the issue https://github.com/PrestaShop/PrestaShop/commit/79753f45c60ee641763c476ef34d5d61d61ae8a6, first, so the module ecosystem is not broken if 1.7.7 get released with it.
Then, let everyone think about the best way to achieve this without breaking everything, and still allow modules to change the behaviour.
We must keep a simple way to do this.

**Comment by Progi1984** [comment] 2020-06-03 14:57
Fixed by #19437

**Closed as completed by Progi1984** 2020-06-03 14:57 UTC
Labels: PM ✔️, FO, Regression, Fixed, 1.7.7.x

**Comment by sam-pires** [comment] 2020-06-08 15:08
[Link to specs](https://github.com/PrestaShop/prestashop-specs/blob/master/front-office/Product-images.md)
