### ISSUE TITLE
Fixed width and height value for product image in listing template

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25849] opened 2021-09-11 09:19 UTC
#### Describe the bug

In prestashop 1.7.8 with recent changes to fix CLS, fixed values for width and heigh has been added to template. That causing problem when someone is adding images with different ratio than has been assumed.

#### Expected behavior

Product listing - [this lines](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0-build/themes/classic/templates/catalog/_partials/miniatures/product.tpl#L37-L38), value should be `$product.cover.bySize.home_default.width` and `$product.cover.bySize.home_default.height`.

#### Steps to Reproduce

1. In BO go to Desing->Images settings.
2. Edit image `home_default` width and height to for example 350px height and 250 width. Save it. 
3. Scroll down to **Regenerate thumbnails**, check `Erase previous images` and click `Regenerate thumbnails` button. 
4. Go to front page and clear webpage cache to download latest images. 
5. Images should be bad displayed. 

**Screenshots**

<img width="281" alt="Zrzut ekranu 2021-09-11 o 11 18 48" src="https://user-images.githubusercontent.com/25306716/132942969-31b042ef-f004-40d3-b8b0-ec9e3d41f364.png">

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by NeOMakinG** [comment] 2021-09-13 07:47
Already fixed there: https://github.com/PrestaShop/PrestaShop/pull/25556

**Comment by hibatallahAouadni** [comment] 2021-09-13 07:54
Hello @Oksydan 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25283. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: Thanks @NeOMakinG for the tip :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-13 07:54
Duplicate of #25283

**Comment by NeOMakinG** [comment] 2021-09-13 07:59
@hibatallahAouadni reopening as I seen that @Oksydan came way further on this PR: https://github.com/PrestaShop/PrestaShop/pull/25855

**Comment by Oksydan** [comment] 2021-09-13 08:39
@NeOMakinG there is not point of not making fixed values if you are not able to change that img coz of css styling. 
I made it working with every image dimension and reduce some redundant css selectors. (we saved 2kb of css there 😄)

**Comment by hibatallahAouadni** [comment] 2021-09-14 08:15
Hello @Oksydan 

Thanks for reproting the issue!
I reproduce the issue with 178x, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/133221425-c48c3bfd-41bb-431b-beee-60850af67770.png)

While with 1777, the images was well displayed, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/133221363-3b7be811-8006-4f4e-a309-80c3430de14c.png)

Thanks for your PR :rocket:

**Comment by SharakPL** [comment] 2021-11-08 11:52
> 
> 
> Already fixed there: #25556

I'm afraid that's not enough, because changing product thumbnails ratio will also break `.higlighted-information` position which is fixed to 250px.

![obraz](https://user-images.githubusercontent.com/5007456/140736879-8b2ef46a-3a42-4896-b215-f19d43d4910f.png)

Really awful way of implementing it as it clearly should be related to `.product-description` block to popup from behind it but it is to whole `.product-thumbnail` block so it works _only_ on 250x250 thumbnails.

I'm making a fix for all images (#26373 and more) so I'll fix that too...

**Comment by Oksydan** [comment] 2021-11-08 12:07
@SharakPL 
check [PR](https://github.com/PrestaShop/PrestaShop/pull/25855/files) it is all covered there.
Listing styling got refacto.

**Comment by SharakPL** [comment] 2021-11-08 12:11
OK. Then let me know when you finish patching this. I'll check what else can be fixed later.

**Comment by Progi1984** [comment] 2021-12-08 14:14
Fixed by @Oksydan in #25855 and tested by @marwachelly

**Closed as completed by Progi1984** 2021-12-08 14:14 UTC
Labels: Bug, Minor, FO, Design, Image, Regression, Fixed, Front-end, PR available, 1.7.8.x
