### ISSUE TITLE
 problem when an address is deleted 

### ISSUE THREAD

**Issue by riga75** [PrestaShop/PrestaShop#23267] opened 2021-02-15 17:33 UTC
#### Describe the bug

I noticed this problem. If a user places an order and then deletes the address from his panel in fgront end. In administration in the item orders that sale disappears, if I go to the database I go but it is not feasible for a customer.  

#### Steps to Reproduce

1- I place an order with an address
2 - proceed to payment
3 - from the front end I go to my panel and delete the address to which I sent the package
4 - if I go to the back end there is no order .

#### Additional information

* PrestaShop version: 1.7.7.0

**Comment by hibatallahAouadni** [comment] 2021-02-16 09:30
Hello @riga75 

I didn't manage to reproduce your issue with PS1.7.7.0 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1snPinn22iJUZQ4AYgzNAI2UfRZeoakst/view

Please check and feedback.
Thanks!

**Comment by riga75** [comment] 2021-02-16 09:37
I did not change the status of the order, but I placed the order and immediately canceled it from the front end

Stefano Rigazio

**Comment by hibatallahAouadni** [comment] 2021-02-16 11:32
Hello @riga75 

You mean that you deleted the address when the order status is "Awaiting bank wire payment", is that so? If so, even without changing the order status, I still can't reproduce your issue :confused:
 
Thanks!

**Comment by riga75** [comment] 2021-02-16 13:37
Yes, right
my other clients also have the same problem with 1.7.70

Stefano Rigazio

**Comment by hibatallahAouadni** [comment] 2021-02-17 14:54
Hello @riga75 

Sorry, but I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1kLTB9kirjSblezzFAx7aTu1Th_q66-or/view

Please check and feedback.
Thanks!

**Comment by riga75** [comment] 2021-02-17 15:09
See here: https://www.loom.com/share/2fef40ed9a9c4e289409dfdf5e295927

**Comment by hibatallahAouadni** [comment] 2021-02-17 15:49
Hello @riga75 

That's extremely odd! Could you please switch to the default theme and try again. If you still encounter it, please disable your purchased modules one by one to identify the culprit :sweat_smile: 

Thanks!

**Comment by matks** [comment] 2021-02-17 21:21
> I noticed this problem. If a user places an order and then deletes the address from his panel in fgront end. In administration in the item orders that sale disappears, if I go to the database I go but it is not feasible for a customer.

I confirm that in PrestaShop 1.7.7 this does not happen. It is probably related to a custom setting on your side (3rd party theme, 3rd party module, or custom code).

> in the item orders that sale disappears

If you can see the data inside the database but it is not displayed, I think something fails to fetch the data from your database (might be a module, might be a customization of your database structure) so you cant see it because the data is considered "not valid" (for some reasons).

**Comment by hibatallahAouadni** [comment] 2021-03-09 14:45
Hello @riga75 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-09 14:45 UTC
Labels: Bug, BO, Order, Addresses, No change required, 1.7.7.0
