### ISSUE TITLE
Carriers Error - Technical error when changing range price 

### ISSUE THREAD

**Issue by pantagru** [PrestaShop/PrestaShop#17110] opened 2020-01-10 16:24 UTC
Hi, 
I work with prestashop 1.7.2.4
I have some big problems with carriers.
I need to configure many carrier into my shop.
Everytime a set a new carrier and his range prices I have no problem.
Example:
![immagine](https://user-images.githubusercontent.com/41157394/72166662-f203cd80-33c9-11ea-8b1f-ac3d5c4260f2.png)
If I close carrier, then reopen it, and I try to change range prices, for example from 60.000000 to 70.000000, the first time I don't have problem.
Example:
![immagine](https://user-images.githubusercontent.com/41157394/72166950-7d7d5e80-33ca-11ea-9382-6a7380537414.png)
I save and close.
If I try to modify carrier range price again, so from 70.000000 to 60.000000, I can't save and a pop-up notify an error.
![immagine](https://user-images.githubusercontent.com/41157394/72167311-32b01680-33cb-11ea-8b71-63e7c05d9925.png)

I noted then in the db, when I change carrier, every time I make a change, in ps_carrier new records are generated with new carrier_id, so at the end I have many records, some deleted, some active. 
![immagine](https://user-images.githubusercontent.com/41157394/72168031-a0107700-33cc-11ea-942d-45b253b92f62.png)

And in the ps_range_price, I have some record, connected to some (not all) carrier_Id
![immagine](https://user-images.githubusercontent.com/41157394/72168174-eebe1100-33cc-11ea-93ac-78fa8ae515be.png)

Many time I have had this problem and everytime the only way is to delete and regenerate a new carrier e fill in all value.

Untile one day ago I have had 4 carriers with range price setted, today every range price are disapperead, the carrier_id in ps_range_price was changed and no connected to the carrier_id active.

Can you help me please?

thank you
daniela

**Comment by Matt75** [comment] 2020-01-10 23:26
I think this issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12577
Fixed in 1.7.6

**Comment by Matt75** [comment] 2020-01-10 23:50
I think this issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12577 and has been solved in 1.7.6

**Comment by khouloudbelguith** [comment] 2020-01-13 08:54
Hi @pantagru,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12946 to fix the issue.
Your ticket is a duplicate of #12577
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-01-13 08:55
Duplicate of #12577

**Closed as completed by khouloudbelguith** 2020-01-13 08:54 UTC
Labels: Duplicate
