### ISSUE TITLE
ps_emailalerts - Email title has [no_sync] at the end

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34880] opened 2023-12-19 16:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The email has [no_sync] at the end of the title.
I don't know what it is about. 
It is not supposed to be there. If I check Design > Email theme > modern > check HTTP of contact email, I don't see the [no_sync] part

<img width="1183" alt="Screenshot 2023-12-19 at 16 52 09" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1ff28cf9-ae83-423e-a8ba-16b144955f8e">

### Expected behavior

Just the simple title should be displayed.

### Steps to reproduce

1. Go to BO > Modules > Edit Contact form module
2. Enable 2nd option Receive customers' messages by email : YES > Save
3. Go to FO > Contact Us > Send a message
4. Go to BO > Advanced parameters > Email 
5. See last email sent : [no_sync] at the end of the email :x:

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Contact form v4.4.1

**Comment by Misty-94** [comment] 2023-12-20 01:48
Hi Florine,

This is not really a bug and has already been reported one year ago, see https://github.com/PrestaShop/PrestaShop/issues/30189

**Comment by paulnoelcholot** [comment] 2023-12-22 11:09
Hello @florine2623,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #30189.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment] 2023-12-22 11:09
Duplicate of #30189

**Closed as completed by paulnoelcholot** 2023-12-22 11:09 UTC
Labels: Bug, Duplicate, Invalid
