### ISSUE TITLE
Bad total price product custom

### ISSUE THREAD

**Issue by feyromain** [PrestaShop/PrestaShop#15175] opened 2019-08-20 15:51 UTC
**Describe the bug**
Bad price total display for custom products on detail order

**To Reproduce**
1. Go to product custom
2. Click on add to cart
3. Go to checkout
4. To confirm order for display page confirmation

**Screenshots**
<img width="1172" alt="Capture d’écran 2019-08-20 à 17 42 32" src="https://user-images.githubusercontent.com/2391917/63362892-dd6b5e00-c372-11e9-9b9b-377887d9f45e.png">

<img width="1108" alt="Capture d’écran 2019-08-20 à 17 43 05" src="https://user-images.githubusercontent.com/2391917/63362901-e0fee500-c372-11e9-9821-e3ca4a9e17f0.png">

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment] 2019-08-20 15:55
Hi @feyromain,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10912
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-20 15:56
Duplicate of #10912

**Closed as completed by khouloudbelguith** 2019-08-20 15:55 UTC
Labels: Duplicate, Product customization
