### ISSUE TITLE
isTablet() and isMobile() doesn't work for some IOS devices

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#19747] opened 2020-06-15 09:17 UTC
Using https://www.browserstack.com/

Some devices (like iPad 7) is **NOT** detected as a tablet with prestashop isTablet() function

PS: 1.7.6.5
PHP: 7.2

**Comment by thbl** [comment] 2020-06-15 09:52
Found it seams to be a problem with IOS13 and up it is also noted as an issue at https://github.com/serbanghita/Mobile-Detect
Cause IOS set safari as desktop mode by default.

could we implant this function some how ?
https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up

```
let isIOS = /iPad|iPhone|iPod/.test(navigator.platform)
|| (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)
```

**Comment by matthieu-rolland** [comment] 2020-06-15 13:32
hi @thbl , could you describe the exact steps to reproduce your issue, and describe the current behavior on a iPad with ios 13?

**Comment by thbl** [comment] 2020-06-15 15:09
@matthieu-rolland 
using isTablet() or isMobile() returns false for IOS 13 and up but should return true
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Context.php

**Comment by florine2623** [comment] 2020-06-19 13:21
Hi @thbl ,
Using browserstack.com, I was able to see a PS 1.7.6.5 shop correctly on FO and BO.
Is there another way to test that functions isTablet() or isMobile() are not working ?
Thanks

**Comment by thbl** [comment] 2020-06-19 13:26
@florine2623 
Only by a module/theme that uses the function, etc. amp theme / plugin

**Comment by florine2623** [comment] 2020-06-19 13:58
ok and can you be a little more clear ?
What are the steps to reproduce the issue ?
What does the problem looks like ?
Do you have a test module ?
I cannot help you if I don't see an issue

**Comment by sarahdib** [comment] 2020-07-07 11:59
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Closed as completed by sarahdib** 2020-07-07 11:59 UTC
Labels: No change required, 1.7.6.5
