### ISSUE TITLE
Watermark Module | HTTP 500 Internal Server Error 

### ISSUE THREAD

**Issue by silicon755** [PrestaShop/PrestaShop#18955] opened 2020-05-04 08:18 UTC
I have installed https://github.com/PrestaShop/watermark module but upon configuration, I get the HTTP 500 Internal Server Error with the following Stack Trace, I have tried clearing cache and editing .htaccess as suggested on Prestashop Forums but I can't seem to get it working. Someone with a workaround? 

 **Store Information**

PrestaShop version: 1.7.6.1

Server software version: Apache

MySQL version: 5.6.47 
````
Attempted to load class "CategoryFetcher" from namespace "PrestaShop\Module\Watermark\Addons".
Did you forget a "use" statement for "PrestaShop\Module\BlockReassurance\Addons\CategoryFetcher"?
````
![Firefox_Screenshot_2020-05-04T07-29-21 251Z](https://user-images.githubusercontent.com/22223504/80947419-d13c0980-8df8-11ea-9612-e28167878ae3.png)

**Comment by Progi1984** [comment] 2020-05-04 08:54
Hi @silicon755 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- how have you installed the module ?
 ...

You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by silicon755** [comment] 2020-05-04 09:20
Hello @Progi1984 

The module had issues with the normal Backoffice upload so I used FTP to upload it in /modules folder and after successful installation, I am getting HTTP 500 Internal Server Error when trying to configure it.

SERVER INFORMATION
==================
Server information Linux #1 SMP Wed Oct 2 07:53:12 EDT 2019 x86_64
Server software version: Apache
PHP version: 7.2.30
Memory limit: 512M
Max execution time: 300
Upload Max File size: 20M

STORE INFORMATION
==============
PrestaShop version: 1.7.6.1 

DEBUG REPORT
==========
````
Symfony\Component\Debug\Exception\ClassNotFoundException:
Attempted to load class "CategoryFetcher" from namespace "PrestaShop\Module\Watermark\Addons".
Did you forget a "use" statement for "PrestaShop\Module\BlockReassurance\Addons\CategoryFetcher"?

  at modules/watermark/watermark.php:607
  at Watermark->renderAddonsSuggestion()
     (modules/watermark/watermark.php:341)
  at Watermark->getContent()
     (controllers/admin/AdminModulesController.php:907)
  at AdminModulesControllerCore->postProcessCallback()
     (controllers/admin/AdminModulesController.php:1167)
  at AdminModulesControllerCore->postProcess()
     (classes/controller/Controller.php:281)
  at ControllerCore->run()
     (classes/Dispatcher.php:515)
  at DispatcherCore->dispatch()
     (admin217zkn0qj/index.php:97)
````

**Comment by TristanLDD** [comment] 2020-05-06 09:22
@PrestaShop/prestashop-core-developers WDYT? Do you manage to reproduce with the provided informations?

**Comment by Flightys** [comment] 2020-05-06 19:20
I have the same problem! Why did you not remove this addon if it give bugs? I just do it 15 minutes ago but i see they have this problem 3 days ago already.
"I have installed https://github.com/PrestaShop/watermark module but upon configuration, I get the HTTP 500 Internal Server Error with the following Stack Trace, I have tried clearing cache and editing .htaccess as suggested on Prestashop Forums but I can't seem to get it working. Someone with a workaround?"
I install the program but i think it not really download or install it. When i press "Configure" i get the Error screen on my AdminDashboard and also my online website Corona19.be

**Comment by Flightys** [comment] 2020-05-06 19:51
I have same problem. I install it but i think it not download, not sure. Because i could no find the file i press "Configure" and i get the Error.

**Comment by jul-m** [comment] 2020-05-06 22:54
I have the same problem with Prestashop 1.7.6.4, with the last release of the module, and the dev version.
I commented all content of the renderAddonsSuggestion() function, the module works correctly (on the dev version of the module, I have not tested on "stable" version).

**Comment by silicon755** [comment] 2020-05-07 02:45
@jul-m your workaround did the trick on Prestashop 1.7.6.1 and Watermark-2.0.0 stable versions.
I commented out the following lines of code
341 ```` // $html .= $this->renderAddonsSuggestion();````
````
// public function renderAddonsSuggestion()
    // {
    //     $categoryFetcher = new CategoryFetcher(
    //         465,
    //         [
    //             'name' => 'Labels & Logos',
    //             'link' => '/en/465-labels-logos',
    //             'description' => '<h2>Reassure your customers, encourage them to make purchases and make it easier to browse on your e-commerce website by adding badges to your product pages!</h2>For example, you can add “Free delivery”, “-30%”, “New”, “Last articles in stock” or “No. 1 selling product” badges to make your products more visible and ensure they stand out. Also propose badges indicating the composition (100% cotton, 100% organic etc.) or even  icons highlighting each product\'s strengths. You can therefore personalize your store in just a few clicks.',
    //         ]
    //     );
    //     $category = $categoryFetcher->getData($this->context->language->iso_code);
    //     $this->context->smarty->assign(array(
    //         'addons_category' => $category,
    //     ));

    //     return $this->context->smarty->fetch('module:watermark/views/templates/admin/addons-suggestion.tpl');
    // }
````

**Comment by Flightys** [comment] 2020-05-07 06:24
It is back online now, i don't know who did it, but i could not do this myself because i could not get back into my admin of prestashop.

**Comment by Progi1984** [comment] 2020-05-07 06:30
@silicon755 Which version of the module do you use ?

**Comment by silicon755** [comment] 2020-05-07 08:16
> @silicon755 Which version of the module do you use ?

Watermark-2.0.0

**Comment by Progi1984** [comment] 2020-05-07 08:30
@silicon755 Where did you download the module from addons ? or from the repository ?

**Comment by silicon755** [comment] 2020-05-07 15:58
@Progi1984 I downloaded from the repository, here's the [link](https://github.com/PrestaShop/watermark)

**Comment by Progi1984** [comment] 2020-05-11 06:51
In this case, have you done a `composer install` in the module ?

**Comment by silicon755** [comment] 2020-05-12 09:37
No, I did not

**Comment by Progi1984** [comment] 2020-05-13 13:03
Could you do it ? I think that fix the problem.

**Comment by khouloudbelguith** [comment] 2020-10-19 10:19
Hi @silicon755,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-19 10:19 UTC
Labels: Bug, No change required, 1.7.6.1

**Comment by mklimkiew** [comment] 2020-12-29 15:22
This module (2.0) gives an error in version 1.7.7
After re-generating new pictures, FO gives error HTTP 500
only uninstalling module makes FO work again. BO seems not to be afected.

**Comment by wencs00** [comment] 2023-11-04 02:20
No funciona
sigue dando el mismo error no e logrado arreglarlo, si alguien tiene una idea gracias
