### ISSUE TITLE
There's no condition in the product's name - Multilanguage 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10459] opened 2018-09-17 14:00 UTC
**Describe the bug**

Multilanguage Shop
In the BO => Product page => There's no condition in the name's product when id_lang <> 1 
**To Reproduce**
English is the default language
1. Go to BO => Product page
2. Click on 'add new product'
3. Enter a name with 2 chars
4. Save
5. See error "This value is too short. It should have 3 characters or more." => OK
6. Edit the name & save => OK
7. Select "Fr" => the name of this product is 2chars in French => save => there's no alert.

**Screenshots**
https://drive.google.com/file/d/1Fvs_ufL0Me9ssDVRExCdRgnAOH3hPLED/view

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2020-11-20 16:09
Hello,

I managed to reproduce the issue with PS1.7.7.0-rc.1+build.4 and develop, see the attached screen record below:

https://drive.google.com/file/d/1MQ_rXiz0gZ1mDYiW0rggF8EKjo1CNcmQ/view

Thanks!

**Comment by zuk3975** [comment] 2021-06-29 12:57
related https://github.com/PrestaShop/PrestaShop/issues/19441 (product name is not even required and can end up being empty string, because of legacy behavior of "ghost product"))

**Comment by MatShir** [comment] 2023-06-26 14:00
It should be fixed on 8.1 :)

**Closed as completed by MatShir** 2023-06-26 14:00 UTC
Labels: Bug, Trivial, BO, Fixed, 1.7.4.2, Verified
