### ISSUE TITLE
503 php max children; 504 timeout Uncaught ErrorException: Warning: Undefined property; PS 8.1.2 PHP 8.2.8-fpm DockerVersion

### ISSUE THREAD

**Issue by Trackhe** [PrestaShop/PrestaShop#34114] opened 2023-10-01 10:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PHP server reached pm.max_children setting (5), consider raising it.

The shop doesn't load after navigating a couple of times through the backend. It gives me the error: `PHP server reached pm.max_children setting (5), consider raising it.` and stops loading. This results in an 503 error.

A quick fix is to adjust the pm.max_children https://www.php.net/manual/en/install.fpm.configuration.php but i m not sure if that is the wanted behavior and if that fix it permanently. pm.max_children = 5 is the default.

After the raise of that option to 100. I get the timeout and in php the error: 

```
NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: Warning: Undefined property: Symfony\Component\VarDumper\Caster\CutStub::$cache_locking in /usr/share/nginx/html/shop-shp-electronics/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:737
Stack trace:
#0 [internal function]: Smarty_Internal_Template->__destruct()
#1 {main}
  thrown in /usr/share/nginx/html/shop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 737
```

### Expected behavior

No timeout after switching several times through the backend. Using less php threads if its a unnormal behavior. 

### Steps to reproduce

Setup the PS 8.1.2 with docker php-fpm 8.2-fpm navigate through the backend 8-10 site switches should be enough to get it stuck. After waiting a few minutes it comes automatically back to life.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.2.8-fpm

**Comment by AureRita** [comment] 2023-10-04 08:57
Hello @Trackhe 

Thank you for your report, currently Prestashop 8.1 can't support php 8.2 so it's an expected behavior, you can see the different version of php that the latest version of prestashop supports on this link :https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

I'll close the issue because it's an expected behavior 

Thank you

**Closed as completed** 2023-10-05 04:34 UTC
Labels: Bug, Invalid

**Comment by marekhotshot** [comment] 2025-01-09 15:09
We are experiencing the same issue as described above. Can you please advise?
Our prestashop version is 8.1.1. We use official prestashop docker image as base image for our store. PHP version is 8.1.29.

root@prestashop-5c46dd8589-dnkvc:/var/www/html# php -v
PHP 8.1.29 (cli) (built: Jun 13 2024 03:08:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.29, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.29, Copyright (c), by Zend Technologies

However I can see that we are missing MySQLi Extension... Shouldn't this be included in official image??
![Image](https://github.com/user-attachments/assets/94efe79e-99f0-4760-a3ef-8b9813b54d9e)
