### ISSUE TITLE
We can no longer add products to the order in the back office

### ISSUE THREAD

**Issue by Thierry-Pimentbleu** [PrestaShop/PrestaShop#28096] opened 2022-03-31 18:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
When I am in the order of a customer in the back office that is validated, I can not find the button to add products to the order of my customers while I had the button in 1.7.7.7
Have a nice day
Thierry

### Expected behavior

The button should have been present below the list of products in the order. 

### Steps to reproduce

1 - Go to an order in the back office that has a status of "Payment accepted" (default status after payment of an order)
2 - The button at the bottom of the product list is no longer displayed.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.2

**Comment by alfonsolr09** [comment] 2022-03-31 21:20
![image](https://user-images.githubusercontent.com/62474824/161151274-b9b49956-7fa0-439f-bc00-8419e653cb9b.png)

**Comment by alfonsolr09** [comment] 2022-03-31 21:21
can´t reproduce

**Comment by alfonsolr09** [comment] 2022-03-31 21:24
![image](https://user-images.githubusercontent.com/62474824/161151542-f38ac512-5f72-489e-b465-bc574a3ebda8.png)
if you have activated the delivery in the "payment accepted" state, it will not let you modify the order

**Comment by khouloudbelguith** [comment] 2022-04-01 09:34
Hi @Thierry-Pimentbleu,

I did not manage to reproduce the issue with PS1785.
![image](https://user-images.githubusercontent.com/16067358/161236567-62a9853b-edff-459b-ac74-95400496e6bc.png)
In the BO > Shop Parameters > Order Settings > Statuses page
![image](https://user-images.githubusercontent.com/16067358/161236959-f2ca8f9b-4c88-45d1-b00b-da2e49990004.png)
![image](https://user-images.githubusercontent.com/16067358/161237000-36ea2902-618e-471e-b826-a10f27787301.png)

Could you please provide me a screenshot from the `Edit: Payment accepted` page?

Thanks @alfonsolr09 for your comments!

Thank you!

**Comment by willowtree336** [comment] 2022-04-09 19:29
I have the same issue in 1.7.8.4
![Screenshot 2022-04-09 8 22 52 PM](https://user-images.githubusercontent.com/103334112/162588962-97279fe5-8176-482b-874c-662daa8fb81c.png)

**Comment by hibatallahAouadni** [comment] 2022-04-11 12:27
Hello @Thierry-Pimentbleu & @willowtree336 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a statuses configuration problem, see the attached screen record below:


https://user-images.githubusercontent.com/23308427/162738997-78418c68-5d83-462f-840c-34e70614fd6c.mp4

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-04-11 12:27 UTC
Labels: Bug, BO, Order, Order statuses, Invalid

**Comment by alfonsolr09** [comment] 2022-04-11 13:48
> In the BO > Shop Parameters > Order Settings > Statuses page\n\n\n\nCould you please provide me a screenshot from the Edit: Payment accepted page?

@willowtree336 can you see this? And send a picture please

**Comment by willowtree336** [comment] 2022-04-11 19:17
We have the delivery slip available on the payment accepted as it is used as a packing slip.

I've not worked out the intended purpose of the delivery slip if it's only available AFTER a product has left the building.

**Comment by alfonsolr09** [comment] 2022-04-12 00:20
> We have the delivery slip available on the payment accepted as it is used as a packing slip.
> 
> I've not worked out the intended purpose of the delivery slip if it's only available AFTER a product has left the building.

Can you send a picture pls?

**Comment by lucasvavon** [comment] 2022-04-28 07:10
Hello, 

At Piment Bleu, we followed your advice and solved our problem, the option "delivery" should not be activated to allow the edition of products of an order.

Thank you [alfonsolr09](https://github.com/alfonsolr09) :)

Best regards,
Lucas, 
Piment Bleu (FR)
