### ISSUE TITLE
Error on upload attachments file with POST method

### ISSUE THREAD

**Issue by clemdesv** [PrestaShop/PrestaShop#35922] opened 2024-04-15 12:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Configuration : 
Prestashop 8.1.5, no module, no theme
This prestashop is a basic prestashop dedicated for tests and POCs with webservices.

I was trying to implement the attachments webservices endpoints and during my test with Postman I encountered an error when I do a POST method with a document through https://url/api/attachments/file/ : "! [CDATA[[PHP Warning https://github.com/PrestaShop/PrestaShop/pull/2] Trying to access array offset on value of type null (/var/www/prestashop/classes/webservices/WebservicesSpecificManagementAttachments.php, line 344)]]"

But the document is uploaded on the server and is available on files sections on Prestshop BO.

Error with Postman :
![error_PS_WS](https://github.com/PrestaShop/PrestaShop/assets/167074009/41ffd055-8a15-4b57-b552-5ae5893bfb48)

### Expected behavior

I expected to get the reponse with the attachment object.

### Steps to reproduce

1. Go to your Prestashop BO
2. Activate WS and attachments endpoints
3. Create a request with POST method on the api/attachments/file/ endpoint and add a document in bynary as body
4. Send it

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.27

**Comment by AureRita** [comment] 2024-04-16 12:40
Hi @clemdesv 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 
 
[recording(187).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/065f83cd-136f-4486-bd67-f42eb4a0e1f9)

Did I miss something ? 

Can you do a get before to see if you've all the authorization to use the webservice ? 

Waiting for feedback

**Comment by TeddyBear06** [comment] 2024-04-17 05:45
@AureRita Would you mind share the cURL code generated from Postman with us (for the first POST request in your video, when you upload the picture)?

**Comment by AureRita** [comment] 2024-04-17 08:26
Hi @TeddyBear06 

No problem, I'll share you this : 
curl --location 'localhost/pr81x/api/attachments/file' \

waiting for your feedback

**Comment by clemdesv** [comment] 2024-04-17 08:40
Hi @AureRita , 
Can you add the other lines of your cURL ? 

Here are mine (I hid information with XXXXXX): 
curl --location 'http://XXXX/api/attachments/file?io_format=JSON' \
--header 'Authorization: Basic XXXXXXX' \
--header 'Content-Type: application/pdf' \
--header 'Cookie: PrestaShop-XXXXXXXX' \
--data '@9Qt5DyrDu/code-barre-preparateur.pdf'

Thanks

**Comment by AureRita** [comment] 2024-04-23 09:55
Hi @clemdesv 

No problem, there is the followed cURL : 

curl --location 'localhost/pr81x/api/attachments/file' \
--header 'Content-Type: image/png' \
--header 'Authorization: Basic SFFNUkhCV0k0WUcxM1ZHNU43Q0laMVYzMjM1WFpXN0c6SFFNUkhCV0k0WUcxM1ZHNU43Q0laMVYzMjM1WFpXN0c=' \
--header 'Cookie: PrestaShop-c23eae09d26197a03c65f0a73aa50cb1=def50200141f773f0ffe71f7132d167d6a7a98a5ee543a1891b545a6bbe9a23bc2248e70ce7253548291dc3a53cf13e3c81a34d5b5de755018b8cde36c92c1bf786691ec340ff1101e2d0a42899446cc6358e2a9ae3159fa9a4ead2c5eb2e84952d3908e688d0ee5deeecfc26831dac81a0d2792e046f1d36c57959f912ba6f0c353fe0a087236cd467e0dca03e3028f249bb47ecf1c164eaafbe8a56cec1e7577fe74775eae03ea96d83bea583650b519ad73b78c70fcd67fd9ab0bb26561dd37bd82265695fb6da829337e8f3b3e7e6386904b2c72d8bbc7' \
--data '@/home/arita/Téléchargements/logo.png'

**Comment by clemdesv** [comment] 2024-04-26 08:43
Hi @AureRita,

Thank you for your cURL.
So we have the same type of cURL but you don't have my problem to POST files through webservices.

I summarize, we are on the same version of prestashop (8.1.5), all the methods are allowed on the attachement endpoint.
For me the the only visible difference is the default language we are using (me french and you english according to your video).

Here are the informations of my prestashop and the environement  : 
![chrome_ipA2ZM44ZS](https://github.com/PrestaShop/PrestaShop/assets/167074009/b41b7f6a-a616-40cb-a76e-ca97c008b30a)

I'm working with @TeddyBear06 on a docker config to test to reproduce the bug and try to debug it with Xdebug.
We will let you know about it soon.

**Comment by TeddyBear06** [comment] 2024-04-26 09:56
Hi there,

Below a video explaining why the response from the webservice is not the one expected (@AureRita PHP warnings seems desactivated in your environement, that's why you did not reproduce our issue).

In order to summarize:

1. Raw PrestaShop install
2. Warnings activated in php.ini
3. PHP warnings that pops inside the XML response from PrestaShop when upload file attachment (but the file is correctly uploaded) so we can't get the uploaded file's ID back

If we desactivate PHP warnings, it works as expected.

Maybe it would be better to consolidate the `$attachment->name[$defaultLanguage]` test (line 342) as `$attachment->name` is NULL (maybe we've missed something in the PrestaShop configuration? If not, this PR https://github.com/PrestaShop/PrestaShop/pull/35920/commits/eab90203409cb742734dac830bde745f70cb3ec7 could avoid the PHP warning message).

https://github.com/PrestaShop/PrestaShop/assets/1452474/4f2e02aa-149b-455c-b455-d21ea4bd3953

**Comment by TeddyBear06** [comment] 2024-05-02 20:25
I was wondering how a warning can be injected inside the XML (not a criticism, just by curiosity).

Found that in `classes\webservice\WebserviceRequest.php`, there is a custom error handler definition to "replace the default PHP error handler":

https://github.com/PrestaShop/PrestaShop/blob/fc70da94492a8426597ab76e3a6adbf30025ac50/classes/webservice/WebserviceRequest.php#L487

This is the line that set warning messages (but also handle other "errors" lines around):

https://github.com/PrestaShop/PrestaShop/blob/fc70da94492a8426597ab76e3a6adbf30025ac50/classes/webservice/WebserviceRequest.php#L744

And errors are rendered as XML content here:

https://github.com/PrestaShop/PrestaShop/blob/fc70da94492a8426597ab76e3a6adbf30025ac50/classes/webservice/WebserviceRequest.php#L1886

This is neat, but as developpers, we work with at least PHP warnings enabled.

**Comment by florine2623** [comment] 2024-11-13 10:23
I will close this issue as it hasn't had any activity for a few months.

However, conversation can still be had on the issue.

**Closed as completed by florine2623** 2024-11-13 10:23 UTC
Labels: Bug, WS, Webservice, 8.1.x
