### ISSUE TITLE
 Error during prestashop first installation of Prestashop 1.7.8.2

### ISSUE THREAD

**Issue by manoloprova** [PrestaShop/PrestaShop#27072] opened 2021-12-23 15:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I have the same exact error shown in [this bug report](https://github.com/PrestaShop/PrestaShop/issues/16680).

How can I solve it?

Thanks.
Regards,

### Expected behavior

I expected the installation to be successful, but it isn't.

### Steps to reproduce

1. Upload the PS installation files on my hosting space
2. Run the installation
3. it fails at 45%

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3, 7.1, 5.6

**Comment by hibatallahAouadni** [comment] 2021-12-23 16:34
Hello @manoloprova 

I'm not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server confiduration problem or slow network problem.
Sorry but I have to close the issue :pray: 

PS: PrestaShop 1.7.8.2 is not compatible with PHP5.6 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

Thanks!

**Closed as completed** 2021-12-23 16:34 UTC
Labels: Bug, Can't reproduce, Invalid

**Comment by manoloprova** [comment] 2021-12-26 11:14
Could you please provide more details on how can I solve the issue?
You may want to register a free domain on Altervista and try to install Prestashop there, just as I did.
Looking forward to receiving your good news.
Regards.
