### ISSUE TITLE
Minor problems with image thumbnail generation

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#24157] opened 2021-04-22 10:01 UTC
#### Describe the bug

1. A thumbnail of a transparent gif has its background changed from transparent to white.
2. In menu *Improve - Design - Image Settings*, some settings are restricted to the context *All shops*, while other are not, even though different settings in different shops might give unexpected results.

#### Expected behavior

1. A transparent gif should keep its transparency when converted to png.
2. All thumbnail generation settings should be restricted to the context *All shops*.

#### Steps to reproduce

**First Bug:** Gif looses transparency => **`Duplicate`** of #23920

1. In Design - Image settings use the setting Image format: Use PNG for all images
2. Import a image in format gif with a transparent background as a product image
3. In the FO, the generated image is not transparent, but has a white background.

---

**Second Bug:** Incoherent restriction of settings to context *All shops* => **`Duplicate`** of #19377

1. In a multishop environment, choose context *All shops*
2. Go to *Design - Image settings*
3. Everything is like expected
4. Change to the context of a specific shop
5. In *Design - Image settings*, some settings display *You can't change the value of this configuration field in the context of this shop.*, others do not show that message, but should display it also.

#### Additional information

* PrestaShop version: 1.6 to 1.7.7.3
* PHP version: any

**Comment by hibatallahAouadni** [comment] 2021-04-22 11:35
Hello @lmeyer1 

I believe you've mixed the PrestaShop version and PHP version :sweat_smile: 
As much as I understand you're reporting two bugs, is that so?
And could you please provide steps to reproduce the issues (your report is well detailed :clap: but we need these steps :wink: )

Please check and feedback.
Thanks!

**Comment by lmeyer1** [comment] 2021-04-22 12:23
@hibatallahAouadni 

> I believe you've mixed the PrestaShop version and PHP version 😅

Sorry, I edited

> As much as I understand you're reporting two bugs, is that so?

Yes, it is.

> And could you please provide steps to reproduce the issues.

The intention of this issue is to further document the corrections I introduced in PR #24159. I didn't mean reporting a bug for you to fix. If you still need a test file and detailed steps, I could do it for you, but if it's no longer needed since my PR, I prefer put my energy in developing our shops.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-04-26 09:12
Hello @lmeyer1 

Your PR will be tested when this is validated, and to be validated I need to reproduce it.
So, I need those steps to reproduce the issue and validate it 😉 

Thanks!

**Comment by lmeyer1** [comment] 2021-04-29 15:15
@hibatallahAouadni 
Hello, I added the steps to reproduce the issues. Sorry I omitted it when submitting.

**Comment by hibatallahAouadni** [comment] 2021-05-05 00:35
Hello @lmeyer1 

Thanks for the steps and your patience :pray: 
For the first issue **`gif looses transparency`**, I think it's the same issue as yours with JPEG #23920
For the second issue **`Incoherent restriction of settings to context All shops`**, we still working on **Image Settings** with the **Multistore**, check these features:

- #19412 - Multistore - Design > Images settings > Add new image type - Add information message
- #19377 - Multistore - Design > Image Settings - Add checkboxes
- #19329 - Multistore - Design > Image Settings - Add specific settings dropdown

Please check and feedback.
Thanks!

**Comment by lmeyer1** [comment] 2021-05-05 05:59
@hibatallahAouadni 
PR #24159 fixes both bugs.

**Comment by hibatallahAouadni** [comment] 2021-05-12 11:56
Hello @lmeyer1 

>#### First Bug: gif looses transparency:
>
>1. In Design - Image settings use the setting Image format: Use PNG for all images
>2. Import a image in format gif with a transparent background as a product image
>3. In the FO, the generated image is not transparent, but has a white background.

=> I manage to reproduce with PS1.7.7.4 & PS1.7.6.7 (the image has been transformed to jpg), see the attached screen record below:

https://drive.google.com/file/d/1r19P1wLQj3rDYkZ2VrQlZWWdBTIRVSrb/view

>#### Second Bug: Incoherent restriction of settings to context All shops
>
>1. In a multishop environment, choose context All shops
>2. Go to Design - Image settings
>3. Everything is like expected
>4. Change to the context of a specific shop
>5. In Design - Image settings, some settings display You can't change the value of this configuration field in the context of this shop., others do not show that message, but should display it also.

=> We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19377. 
You can update your PR as it will fix both issue (the first one about the gif image and the second one #19377) :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-12 12:07
I just check on develop and it seems your PR #24119 fixed the first issue 

![image](https://user-images.githubusercontent.com/23308427/117972356-553da100-b32b-11eb-8a91-a92cd0e25e65.png)

So, as I told you it's a duplicate of #23920

**Comment by hibatallahAouadni** [comment] 2021-05-12 12:07
Duplicate of #23920

**Comment by hibatallahAouadni** [comment] 2021-05-12 12:08
Duplicate of #19377

**Closed as completed by hibatallahAouadni** 2021-05-12 12:07 UTC
Labels: Bug, BO, Duplicate, Image, 1.7.7.3
