### ISSUE TITLE
Bug in displayed discount when adding product (linked to a coupon) to an existing order from BO

### ISSUE THREAD

**Issue by hanicab** [PrestaShop/PrestaShop#13880] opened 2019-05-20 15:29 UTC
**Describe the bug**

**To Reproduce**

1. Create a coupon rule with: empty code + product restriction + discount amount
1. try to add this product above (linked to the coupon) to any existing order
1. you will see that the discount is duplicated
1. also if you delete the discount from the order, the discount displayed ins incorrect

**Screenshots**
![1!UNITO-UNDERSCORE!part1](https://user-images.githubusercontent.com/50826540/58033444-c8d5ba80-7b24-11e9-82f5-09aecda4132b.png)
![1!UNITO-UNDERSCORE!part2](https://user-images.githubusercontent.com/50826540/58033445-c8d5ba80-7b24-11e9-8f15-12388d20349f.png)
![1!UNITO-UNDERSCORE!part3](https://user-images.githubusercontent.com/50826540/58033447-ca06e780-7b24-11e9-91c1-503b389002c1.png)
![2!UNITO-UNDERSCORE!part1](https://user-images.githubusercontent.com/50826540/58033448-ca06e780-7b24-11e9-91e7-f0ddb94fa841.png)
![2!UNITO-UNDERSCORE!part2](https://user-images.githubusercontent.com/50826540/58033449-ca9f7e00-7b24-11e9-926c-5a38a88684af.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-21 11:36
Hi @hanicab,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2.

The cart rule:
1. has no code
2. product selection a product with 100 euro tax included / without product selection => same issue
3. discount amount of 500 EUR tax included

PS1.7.6.0:
1. add the product to old order
2. discount value =100 EUR = price of the product => diffent from the FO 
3. Discounts = 200 EUR => Incorrect
4. Total => incorrect
![image](https://user-images.githubusercontent.com/16067358/58092588-66cc9200-7bc4-11e9-8e26-111ca663b961.png)

PS1.7.5.2
1. add the product to old order
2. discount value =100 EUR = price of the product => different from the FO
3. Discounts = 600 EUR  = 500EUR + 100 EUR=> Incorrect
4.Total discount => Incorrect

![image](https://user-images.githubusercontent.com/16067358/58092753-cd51b000-7bc4-11e9-96e8-876294b6844e.png)

In the FO => ok

![image](https://user-images.githubusercontent.com/16067358/58092801-f2462300-7bc4-11e9-8edf-1cc982852605.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by hanicab** [comment] 2019-05-21 12:20
@khouloudbelguith Thank you for your reply

I want to tell that I have also an incorrect discount if the cart rule is without any product restriction.

Can you try to reproduce this please ?

**Comment by khouloudbelguith** [comment] 2019-05-21 12:39
@hanicab, it is a different issue? 
this discount is added from the BO? / FO?
Thanks!

**Comment by hanicab** [comment] 2019-05-21 15:02
it is different in just 1 step.

when you create the cart rule, no need to set a product restriction to the cart rule. (just empty coupon code and discount amount)

then try to add any product to any existing order, you will see that the total order wiol be incorrect

**Comment by khouloudbelguith** [comment] 2019-05-21 15:10
@hanicab, yes you are right.
Thanks!

**Comment by hanicab** [comment] 2019-05-22 11:12
@khouloudbelguith You are welcome,

I think that it will be better to add that as comment in the issue , it can be important for devloppers when resolving problem

**Comment by khouloudbelguith** [comment] 2019-05-22 11:20
@hanicab, yes, I just edited my last comment.
Thanks!

**Comment by colinegin** [comment] 2019-12-02 13:21
@MatShir do you know if this issue has been fixed with the page migration ?

**Comment by colinegin** [comment] 2019-12-16 13:23
In stand-by waiting for the order page to be fully migrated.
We need to check if the issue is still present once all order PRs have been merged.

**Comment by colinegin** [comment] 2020-02-12 10:52
This issue needs to be tested with the new migrated order page. If it is not fixed, it should be fixed in 178.

**Comment by khouloudbelguith** [comment] 2020-03-05 11:48
Hi @Progi1984,

I tried with the branch 1.7.7.x (Migrated Order page)
1. The cart rule:
1.1. has no code
1.2. product selection a product with 100 euro tax included 
1.3. discount amount of 500 EUR tax included
2. add the product to the old order
![image](https://user-images.githubusercontent.com/16067358/75976199-3f884c80-5eda-11ea-9f63-5fac5538887f.png)
=> the product is well added but

- The price of the product is incorrect ( It is displayed Tax excluded => but it should be tax included)
It only occurs with dummy data (order created by default) => #17994 / This issue does not occur with an order created manually. :notebook:  **NOTE : This will be fixed in 1.7.8**:notebook: 

- discount value = price of the product => different from the FO
![image](https://user-images.githubusercontent.com/16067358/75976553-f1277d80-5eda-11ea-87d2-ac439eb7697c.png)


- The block discount is not displayed
![image](https://user-images.githubusercontent.com/16067358/75978775-8d538380-5edf-11ea-9690-6779ab327368.png)

- Total => incorrect

Thanks!

**Comment by colinegin** [comment] 2020-03-09 09:18
Thanks @khouloudbelguith for testing this. I would recommend to fix it in 178 then. What do you think @Progi1984 ?

**Comment by Progi1984** [comment] 2020-03-09 10:43
@colinegin In the last comment, I think we can fix the last item "The block discount is not displayed" for 177x. May be we should divide this comment in multiple issues ?

**Comment by colinegin** [comment] 2020-03-09 11:18
Alright, let's do it then ! 

About issue 2 : discount value = price of the product => different from the FO
@khouloudbelguith i'm not sure I understood the problem. Could you give me more details please? 

And also about issue 4 : total => incorrect. Do you know where is the issue ?

**Comment by khouloudbelguith** [comment] 2020-03-09 11:56
Hi @colinegin,

>About issue 2 : discount value = price of the product => different from the FO
@khouloudbelguith i'm not sure I understood the problem. Could you give me more details please?

Thre is a difference between the BO and the FO when the sam cart rule is applied.
![image](https://user-images.githubusercontent.com/16067358/76210888-534af000-6205-11ea-9f29-66409ae27bd6.png)

1. In the FO, when the cart rule is applied 
The discount value = `500 Euro `
It is the value discount added
![image](https://user-images.githubusercontent.com/16067358/76210806-2a2a5f80-6205-11ea-9761-f643f277629e.png)

2. In the BO => Order details page, when the same cart rule is applied on an old order
The discount value = the price of the product added which is `different` from the discount value in the FO.
![image](https://user-images.githubusercontent.com/16067358/76210848-3f06f300-6205-11ea-99e8-a36a822b9d55.png)

Thanks!

**Comment by Progi1984** [comment] 2020-03-17 16:03
In my PR : 
- :ok_hand: for "The block discount is not displayed"

**Comment by Progi1984** [comment] 2020-04-07 13:54
Fixed by #18205 & #18204

**Closed as completed by Progi1984** 2020-04-07 13:54 UTC
Labels: Bug, Major, BO, Order, Discounts, Taxes and Prices, Fixed, 1.7.5.2, 1.7.6.0
