### ISSUE TITLE
Import removes categories in product card

### ISSUE THREAD

**Issue by slachino** [PrestaShop/PrestaShop#34601] opened 2023-11-16 20:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Import makes category tree changes inside product, removes all categories except Main one. I have checked forum and found similar issue on older prestashop version https://github.com/PrestaShop/PrestaShop/issues/22336, but there Import feature removes Main category, so a little bit different case.

I just try to import CSV file with two columns (Refernce # and Feature), but it impacts on category tree inside product and remains only Main category.
![image](https://github.com/PrestaShop/PrestaShop/assets/151079804/fe117425-1d6c-4e69-a031-5ac04cb5ccc7)

Before IMPORT: 
![image](https://github.com/PrestaShop/PrestaShop/assets/151079804/a58416eb-e0ad-4b4c-9b6c-3ad5654e667b)

After IMPORT:
![image](https://github.com/PrestaShop/PrestaShop/assets/151079804/08b286d0-1fd5-4e6b-8024-418e286109e3)

### Expected behavior

I want the import not to affect the categories inside the product when adding information through the Import function

### Steps to reproduce

1. Advanced parametrs
2. Import -> Products
3. Creating excel table with two columns (Reference # and Feature)
4. Select file -> products.csv
5. Use product reference as key -> ON (other checkbox off)
6. Next step -> mapping Reference, Feature
7. Import -> Successfuly done
8. Features appeared in product cards
9. All categories removed expect "Main category"

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-11-21 16:43
Hello @slachino ,

I can't reproduce your issue.

Here's what my import looks like :
<img width="1184" alt="Screenshot 2023-11-21 at 17 40 37" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/91a62655-5ff6-4a46-b61a-e9e6e023d827">

Before and after the export, I have the same result :
<img width="1198" alt="Screenshot 2023-11-21 at 17 39 52" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/747d77ab-fd93-4694-9f81-ffce2193711a">

Am I missing something ?

**Comment by slachino** [comment] 2023-11-21 17:59
> Hello @slachino ,
> 
> I can't reproduce your issue.
> 
> Here's what my import looks like : <img alt="Screenshot 2023-11-21 at 17 40 37" width="1184" src="https://user-images.githubusercontent.com/16019289/284653133-91a62655-5ff6-4a46-b61a-e9e6e023d827.png">
> 
> Before and after the export, I have the same result : <img alt="Screenshot 2023-11-21 at 17 39 52" width="1198" src="https://user-images.githubusercontent.com/16019289/284653262-747d77ab-fd93-4694-9f81-ffce2193711a.png">
> 
> Am I missing something ?

**Comment by slachino** [comment] 2023-11-21 18:01
Hi @florine2623 

Thank you for a response.

Made a quick vid

https://github.com/PrestaShop/PrestaShop/assets/151079804/3294c85a-c29f-4270-b717-3f1cbe3a0127

One addition - issue not related to Feature or Reference, i have tried force by ID or only Reference, or change product name instead feature adding and etc.
+ on video just new downloaded prestashop version without additionals on it
+ also tried on presta v8.1.0

**Comment by ShaiMagal** [comment] 2023-11-25 12:27
@StarpTech Try edit this file:
/controllers/admin/AdminImportController.php
BEFORE:
```
     if (is_array($category_data)) {
                foreach ($category_data as $tmp) {
                    if ($product->category && is_array($product->category)) {
                        continue;
                    }
                    $product->category[] = $tmp;
                }
            }
```
AFTER:
```
     if (is_array($category_data)) {
                foreach ($category_data as $tmp) {
                    $product->category[] = $tmp;
                }
            }
```


Working? Let me know.

**Comment by florine2623** [comment] 2023-12-13 15:45
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by tswfi** [comment] 2023-12-14 08:07
Happens in 8.0.3 too.

**Comment by tswfi** [comment] 2023-12-14 09:23
> Happens in 8.0.3 too.

or maybe not, seems that merchant has done something strange. Needs more testing.

**Comment by tswfi** [comment] 2023-12-14 11:44
Changed here: https://github.com/PrestaShop/PrestaShop/commit/d0f9edeb15b7c1b249d8b7fdb692987d3270f6f2#diff-7d9a1a25c8bc7d5b8d5e6368443975f834a9cf26816836645223e49b8293f338L1753

I don't understand why the data is even touched in that situation. When using existing products shouldn't the import touch only the fields that are imported?

Steps to recreate on 8.0.3 and current develop (and probably everything in between)

1) login to admin and check that `demo_1` product is attached to multiple categories:
![image](https://github.com/PrestaShop/PrestaShop/assets/1352132/afe75854-d4ab-4b19-a64f-39c143affeb9)

this can also be checked from the database:
![image](https://github.com/PrestaShop/PrestaShop/assets/1352132/19e6115e-4e91-412c-b549-d82a0f922ef9)

2) create csv file with following content

```
$ cat test.csv
Reference,Description
demo_1,Lorem ipsum dolor sit amet
```

3) import the file with following settings:

File to import: the test file from above
Field separator: `,`
Use product reference as key: true
Send notification email: false

![image](https://github.com/PrestaShop/PrestaShop/assets/1352132/58b09675-913e-4e57-b0c1-b8e882e56832)

Click "next" and for the first column select `reference` and for the second column select `description`

![image](https://github.com/PrestaShop/PrestaShop/assets/1352132/24a61514-5240-4bad-b226-e8479a211146)

click "Import"

![image](https://github.com/PrestaShop/PrestaShop/assets/1352132/f0952b35-6acb-4451-bae8-5d6518f78c08)

## Expected result:

Only product description changed

## What happened

Product description was changed **AND** the product assignments to other than the main category were wiped out:

![image](https://github.com/PrestaShop/PrestaShop/assets/1352132/8029f5de-7d5a-40e1-85f4-dc13d578e160)

Also seen in the database

![image](https://github.com/PrestaShop/PrestaShop/assets/1352132/12a5c53f-87ca-479b-b88a-cb7e91aba972)

@florine2623 please reopen this and mark as "critical" as this is a data loss situation.

**Comment by kpodemski** [comment] 2023-12-14 12:25
@florine2623 it's important to follow @tswfi comments and retest this issue, it seems the problem is real and is quite a big one

**Comment by florine2623** [comment] 2023-12-18 15:57
Hello @slachino ,

In the steps to reproduce you said : Use product reference as key -> ON (other checkbox off)
But in your video, it is not the same option checked.

When I try with `Use product reference as key -> YES` 
I can't reproduce your issue. :x:

https://github.com/PrestaShop/PrestaShop/assets/16019289/08662371-095b-416f-93ce-6a55ff5d2dee

When I try with the same option as your video :  `Force all ID numbers -> YES`
I can reproduce your issue ✅ 

https://github.com/PrestaShop/PrestaShop/assets/16019289/a159ea23-e07a-48da-93c7-6ce020d4ddde

Can you specify which one of the option is the one that causes you pain ?

Waiting for your answer.

**Comment by tswfi** [comment] 2023-12-19 07:08
@florine2623 your first video has in the csv file reference `D-218343` and your demo product has reference `demo_14` so your import did not even touch that product that you are showing in the video.

Please see my steps to reproduce here: https://github.com/PrestaShop/PrestaShop/issues/34601#issuecomment-1855697070

**Comment by paulnoelcholot** [comment] 2023-12-20 12:06
Hello @slachino @tswfi ,

I reproduce the issue with PrestaShop version 8.1.1, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

[Products • the future (8).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/f83807a6-f547-4ca0-8e79-883b3c1fe667)

**Closed as completed** 2024-01-04 15:37 UTC
Labels: Bug, BO, Import / Export, Verified, 8.1.x
