### ISSUE TITLE
Error creating a product and not saving it

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18822] opened 2020-04-25 22:52 UTC
#### Describe the bug

When I create a product and exit without saving it, it is saved in the database disabled for the backoffice, but enabled for the frontoffice

https://youtu.be/cQqJoBii1bM

#### Expected behavior

It should not be saved until I click save, or at least save it with the status active so I can edit it

#### Steps to Reproduce

1. Go to create a new product
2. Click on another task or on the back arrow of your browser (don´t click on save)
3. Go to backoffice (products) and you can´t see the new product 
4. Go to database an see the new id of the product
5. Go to front office (new products) and you can see the empty product (no tittle, no image...)

**Screenshots**

https://youtu.be/cQqJoBii1bM

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29

**Comment by PierreRambaud** [comment] 2020-04-27 12:37
Hi @alfonsolr09 
Despite our several trials, we could not reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

You should see with the theme author

Thank you!

**Comment by PierreRambaud** [comment] 2020-04-27 12:41
Hi @alfonsolr09 and thanks for your report.

We manage to reproduce the issue but it looks like we also have problem with the classic theme.
![image](https://user-images.githubusercontent.com/1462701/80373166-ef53b800-8894-11ea-968a-a2badac19ddc.png)

**Comment by alfonsolr09** [comment] 2020-04-27 12:49
do you think it could be solved?

**Comment by PierreRambaud** [comment] 2020-04-27 12:59
Oh, just notice it's a duplicate of #9945 Thanks @khouloudbelguith 
Feel free to continue the discussion on #9945 please.

**Comment by PierreRambaud** [comment] 2020-04-27 12:59
Duplicate of #9945

**Closed as completed by PierreRambaud** 2020-04-27 12:59 UTC
Labels: Bug, FO, Duplicate, 1.7.6.4
