### ISSUE TITLE
ps_shoppingcart | ajax version: "$.parseHTML is not a function" and when no ajax: no redirect

### ISSUE THREAD

**Issue by marioquartz** [PrestaShop/PrestaShop#27101] opened 2021-12-27 11:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have a shop with 1.8.0 and a child theme using "classic" as parent them. When I add a product to the cart when ajax is active the product is added, but there are an error in console

> ps_shoppingcart.js:66 Uncaught TypeError: $.parseHTML is not a function
>     at Object.<anonymous> (ps_shoppingcart.js:66)
>     at o (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at w (jquery.min.js:4)
>     at XMLHttpRequest.d (jquery.min.js:4)

And when ajax is deactivated there are no redirect. But there are an ajax call. A succesful one.

Later I updated the shop to 1.8.2 and ps_shoppingcart but the outcome have not changed.

If the problem comes for JQuery version, why when i overwrite the entire tree of files when I update the version the problem remain?
Searching about this problem, I found [this bug](https://github.com/PrestaShop/PrestaShop/issues/10025) from 2018, but they mention that affects 1.6 and 1.7

### Expected behavior

When ajax is active:

- No error in console
- cart changing its text with number of products

When ajax is no active

- Redirect to cart page

### Steps to reproduce

In a new shop with a theme "classic" add a product to the cart.

### PrestaShop version(s) where the bug happened

1.8.2

### PHP version(s) where the bug happened

7.4.27

### If your bug is related to a module, specify its name and its version

ps_shoppingcart

**Comment by marwachelly** [comment] 2021-12-28 14:48
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10025 and 
To be informed when it's fixed, please subscribe to the issue mentioned above.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks,

**Closed as completed by marwachelly** 2021-12-28 14:48 UTC
Labels: Bug, FO, Duplicate, ps_shoppingcart, Invalid

**Comment by marioquartz** [comment] 2021-12-28 15:35
> Hello,
> 
> We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #[10025 ] and To be informed when it's fixed, please subscribe to the issue mentioned above. Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you.
> 
> If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.
> 
> Thanks,

Its not duplicated. **Ajax version dont work either.** Is a problem with Jquery. I suppose the solution is manually include the function parseHtml in the header.

**Comment by marwachelly** [comment] 2021-12-28 15:45
Hello

> > Hello,
> > We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #[10025 ] and To be informed when it's fixed, please subscribe to the issue mentioned above. Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you.
> > If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.
> > Thanks,
> 
> Its not duplicated. **Ajax version dont work either.** Is a problem with Jquery. I suppose the solution is manually include the function parseHtml in the header.

For the Ajax version I didn't manage to reproduce the issue. It seems that your issue is not a PrestaShop core bug but most likely a module problem.
https://watch.screencastify.com/v/j6p17bSEYCsOvIU2aHy6

**Comment by marioquartz** [comment] 2021-12-28 16:20
Thanks. Reviewing again I have found a problem with my custom.js. Sorry for the incovenience.

**Comment by marwachelly** [comment] 2021-12-28 16:33
Duplicate of #10025
