### ISSUE TITLE
Updating quantity in multishop is adding a row with shop_id = 0 instead of 1 (the main shop id is 1)

### ISSUE THREAD

**Issue by enrybisco** [PrestaShop/PrestaShop#35363] opened 2024-02-14 16:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Updating a combination quantity in multishop is adding a row with shop_id = 0 instead of 1 (the main shop id is 1)
and when I order the sku it is calculating qty=physical_qty - available in the quantity field itself 
[indagine prestashop physical_quantity update.docx](https://github.com/PrestaShop/PrestaShop/files/14283781/indagine.prestashop.physical_quantity.update.docx)
At frontend i see 14 pieces like the 2nd row instead of 99 

### Steps to reproduce

postman

get a product 
https://eni.audes.com/anstg/api/products/54
get a combination
https://eni.audes.com/anstg/api/combinations/340/

open the table stock_available with Dbeaver:
substitute a prod id a comb id and the row id of your combination foundable in the table stock_available

call with postman to update a quantity by logistics api (it should be a physical quantity anyway)
endpoint:
https://eni.audes.com/anstg/api/stock_availables/
body:
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <stock_available>
    <id><![CDATA[1044]]></id>
    <id_product><![CDATA[54]]></id_product>
    <id_product_attribute><![CDATA[340]]></id_product_attribute>
    <id_shop><![CDATA[1]]></id_shop>
    <id_shop_group><![CDATA[1]]></id_shop_group>
    <physical_quantity><![CDATA[50]]></physical_quantity>
    <depends_on_stock><![CDATA[0]]></depends_on_stock>
    <out_of_stock><![CDATA[0]]></out_of_stock>
    <location><![CDATA[]]></location>
  </stock_available>
</prestashop>

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.0

**Comment by AureRita** [comment] 2024-02-15 15:18
Hi @enrybisco 

Thank you for your report, currently we can't try to reproduce on other shop, so we need to hav ean exemple with general parameters, 
Moreover, can you put your explaination with some numbers or bullet point to give us some clear guideline ? 

Waiting for your feedback

**Comment by enrybisco** [comment] 2024-02-15 16:17
Hi Aurerita

Just use the API on multi shop with postman and that's it. It is not
working the update of the quantity in the right place (quantity should be
the result of the subtraction not exposed by API!!) And shop_id if you
don't set in the body is writing in the wrong shop_id(0 instead of the main
1) In fact the user from logistics can't know the reserved quantity of not
paid bank payments.

That's super easy to understand you don't need for sure bullet points!
Anyway:

Set up multi shop
Set the main shop
Set the warehouse as shared between shops
Try to make an order
Try to add 10 quantity to a sky
Try to make an order at frontend
Try to make an API call to update quantity (it should be the physical
anyway !!) Without setting in the body the shop_id but just group_id
Now check the table stock_available to see the mess!

I am sure you can reproduce this very easily!! Try and let me know!

Thanks have a good day
Enrico Bisco

Il gio 15 feb 2024, 16:18 AureRita ***@***.***> ha scritto:

**Comment by florine2623** [comment] 2024-02-22 15:54
Here are the steps to reproduce I used :

- Go to General Parameters > Enable Multistore
- Go to Advanced Parameters > Multistore > Add a new store named `shop2`
- Choose shop context `shop2`
- Go to Advanced parameters > Webservices > Enable PrestaShop's webservice > Save
- Add a new webservice key and give all Permissions to `stock_availables` and `products` > Save
- Open WS of the product with id = 1 : `http://myshop/shop2/api/products/1`
- Check the stock_available id = 59
- Open WS of the stock_avalable = 59 : `http://myshop/shop2/api/stock_availables/59`
- Open postman > launch your PUT request : 

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<stock_available>

<id>59</id>
<id_product xlink:href="http://ps810:8888/shop2/api/products/1">1</id_product>
<id_product_attribute>0</id_product_attribute>
<id_shop xlink:href="http://ps810:8888/shop2/api/shops/2">2</id_shop>
<id_shop_group>1</id_shop_group>
<quantity>1234</quantity>
<depends_on_stock>0</depends_on_stock>
<out_of_stock>2</out_of_stock>

</stock_available>
</prestashop>
```

You need to change the `<id_shop_group>1</id_shop_group> `

The quantity is well edited. I can't reproduce your issue.
Waiting for your feedback.

Please answer via GitHub directly and not from your emails.

**Comment by florine2623** [comment] 2024-03-08 09:06
Hello,

Since we had no news from you for, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2024-03-08 09:06 UTC
Labels: Bug, WS, Stocks, 8.1.x
