### ISSUE TITLE
Bug Prestashop in customer review : Error encoding, htmls characters displayed 

### ISSUE THREAD

**Issue by 01design** [PrestaShop/PrestaShop#23364] opened 2021-02-23 15:15 UTC
#### Describe the bug

When a custumer wants to write a review, you can read it fine in the back-office, validate it and publish it un your product page. But when you go back on the product page , you have some <br> tags displayed in the comments. I guess it's an encodage UTF-8 problem ?

#### Expected behavior
I would like that every reviews come clean without any tags html or strange characters.

#### Steps to Reproduce

1. Go to https://meyrignac.shop/lymphologie/68-188-solidea-silver-wave-legging.html#/11-couleur-noir/54-taille-1s
2. Click on 'Lire les avis'
3. Scroll down to 'Lire les avis'
4. See error with strange html characters in the page

**Screenshots**

![image](https://user-images.githubusercontent.com/26067136/108864228-47ad3080-75f2-11eb-8e7e-2730c124b5f0.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-23 15:47
Hello @01design 

Thanks for following the template :clap: 
Well, I didn't manaage to reproduce the issue with PS1.7.6.8, see the attached screen record below:

https://drive.google.com/file/d/1zHoEjGNKWfeZszLoWtBKcnd2KlkQQ4xl/view

Please check and feedback.
Thanks!

**Comment by 01design** [comment] 2021-02-23 15:54
Hello support and thank you for your quick answer 

It means that the error is only visible with my theme Drama ? If you use the classic template it’s fine ?

**Comment by hibatallahAouadni** [comment] 2021-02-23 17:35
Hello @01design 

Yep I think so. Could you please switch your theme to the Classic and check if you still encounter the same issue.
Please check and feedback.

Thanks!

**Comment by 01design** [comment] 2021-02-24 10:06
Hello

thanks for your answer. I did what you asked and weirdly the Reviews box doesn’t appear on the Prestashop default template, as you can see on the screenshot bellow. I will have to contact the support of the theme editor, or maybe you have another solution in mind ?

Thanks

Yvan

**Comment by hibatallahAouadni** [comment] 2021-02-24 11:20
Hello @01design 

Could you please answer by Github not by mail, and I can't see where did you attach the screenshot :confused: 

Thanks!

**Comment by 01design** [comment] 2021-02-25 08:40
Sorry again for the screenshot,

here we go, as you can see, no review box visible on the product page with the classic template (and the module is published in the BO)
![Screenshot_2021-02-24 Solidea - Silver Wave Long](https://user-images.githubusercontent.com/26067136/109126187-48a6a500-774d-11eb-80ea-c2ff3e88dc41.png)

**Comment by hibatallahAouadni** [comment] 2021-02-26 08:26
Hello @01design 

I didn't manage to reproduce it, see the attached screen record below:

https://drive.google.com/file/d/1l85QtnGEXTph4s2SVsDaMnuE3vNsvUxa/view

Did you upgrade your shop lately from 1.6 to 1.7.6.8? what is your ProductComment module version? and in your first comment, it seems the comments wasn't displayed well and no they're disappeared!!!??

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-19 08:50
Hello @01design ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-19 08:50 UTC
Labels: Bug, FO, No change required, Productcomments, 1.7.6.8

**Comment by 01design** [comment] 2021-03-19 09:13
Hi

thanks for your answer, I didn’t’ have time to answer, I will get back to the theme developper to find a solution too this issue, but thanks you have been very reactive, which isn’t the case of the French Team, 

All the best

Yvan
