### ISSUE TITLE
Backup changes data

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33818] opened 2023-09-03 09:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you make a backup in the Prestashop backoffice it modifies the data that you save by replacing some empty strings with NULL values. Note that this applies to the independent function (advanced settings->database: second tab). The automatic backup during an upgrade uses different code.

In the database the fields isbn, upc and mpn in the ps_product table are declared as default NULL. However, when Prestashop creates products it gives them an empty string value. Yet the backup procedure takes the NULL default as excuse to change empty strings into NULLs.

The problem is that when you do have these values filled with NULL product edit in the backofffice will not work and create a ProductDetails construct crash (see image) with the message: _Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\ProductDetails::__construct() must be of the type string, null given, called in \src\Adapter\Product\QueryHandler\GetProductForEditingHandler.php on line 405_
![nulls](https://github.com/PrestaShop/PrestaShop/assets/13930107/84e9feee-fa4c-42aa-9365-1ba1035d6494)

One situation where this arises is when you make a backup in the backoffice. The backup will look at the field definition and replace empty fields with NULL values.

### Expected behavior

Consist behavior that doesn't cause a crash.

### Steps to reproduce

Make a backup of a PS 8.1 installation. 
Restore the backup and use it as the database.
Edit one of the products

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment] 2023-09-03 12:25
Hi @musicpanda, run these queries over your DB and it will fix all the issues, there could be much more... https://github.com/PrestaShop/autoupgrade/pull/605/files

I want to add it to autoupgrade script, but I don't know if it's gonna get accepted.

Btw - this issue has been opened maaaany times ;-) - https://github.com/PrestaShop/PrestaShop/issues/33371, https://github.com/PrestaShop/PrestaShop/issues/25996, https://github.com/PrestaShop/PrestaShop/issues/22862, https://github.com/PrestaShop/PrestaShop/issues/22386, https://github.com/PrestaShop/PrestaShop/issues/22215

**Comment by sallemiines** [comment] 2023-09-04 16:24
Hello @musicpanda 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #33371.
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @Hlavtox for your quick reply :rocket: 

Thank you

**Comment by sallemiines** [comment] 2023-09-04 16:24
Duplicate of #33371

**Comment by Hlavtox** [comment] 2023-09-05 06:45
It may be a duplicate, but @musicpanda discovered a pretty serious flaw.

- Install prestashop.
- Backup database via backoffice.
- Restore it in phpmyadmin.
- Open any order in backoffice

![Snímek obrazovky 2023-09-05 084443](https://github.com/PrestaShop/PrestaShop/assets/6097524/9d1cea9d-8c9c-434b-b9cf-5652efa527ef)

**Comment by musicpanda** [comment] 2023-09-06 19:13
> It may be a duplicate, but @musicpanda discovered a pretty serious flaw.
> 
> * Install prestashop.
> * Backup database via backoffice.
> * Restore it in phpmyadmin.
> * Open any order in backoffice
> 
> ![Snímek obrazovky 2023-09-05 084443](https://user-images.githubusercontent.com/6097524/265608933-9d1cea9d-8c9c-434b-b9cf-5652efa527ef.png)

The problem here is in the code that creates the backup. That is the function add() in /classes/PrestashopBackup.php. That contains the following code to store a field:
`                        foreach ($row as $field => $value) {
                            $tmp = "'".pSQL($value, true)."',";
                            if ($tmp != "'',") {
                                $s .= $tmp;
                            } else {
                                foreach ($lines as $line) {
                                    if (strpos($line, '`'.$field.'`') !== false) {
                                        if (preg_match('/(.*NOT NULL.*)/Ui', $line)) {
                                            $s .= "'',";
                                        } else {
                                            $s .= 'NULL,';
                                        }
                                        break;
                                    }
                                }
                            }
                        }`

$line is containing the field definition here and the code is basically saying that when a field is an empty string and the default value for that field is NULL, a NULL value should be stored in the backup file.

**Comment by Hlavtox** [comment] 2023-09-07 09:21
@sallemiines @musicpanda Can you reopen this and change the description?

The issue with NULLs in the database is duplicate, but backup messing with our data is new. :-)

**Comment by musicpanda** [comment] 2023-09-08 02:03
> @sallemiines @musicpanda Can you reopen this and change the description?
> 
> The issue with NULLs in the database is duplicate, but backup messing with our data is new. :-)

I changed the title. As far as I know I cannot reopen the issue.

**Comment by Hlavtox** [comment] 2023-10-18 12:27
@PrestaShop/qa-functional Please put proper labels on this

**Comment by hibatallahAouadni** [comment] 2023-10-18 12:31
@Hlavtox Done 😉

**Comment by Hlavtox** [comment] 2024-02-14 10:39
@musicpanda Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/35351

**Comment by MatShir** [comment] 2024-02-26 17:52
fixed by https://github.com/PrestaShop/PrestaShop/pull/35351

**Closed as completed by MatShir** 2024-02-26 17:52 UTC
Labels: Bug, Minor, BO, DB Backup, PR available, Verified, 8.1.x
