### ISSUE TITLE
Multilanguage shop -> invoices in Admin language

### ISSUE THREAD

**Issue by holle75** [PrestaShop/PrestaShop#12686] opened 2019-02-23 17:37 UTC
Well, i´m wondering why somebody has to report it. I´m also wondering why nobody who is using Presta do complain about it. It seems the problem exist since many years.

It is reported here http://forge.prestashop.com/browse/BOOM-4972
and here http://forge.prestashop.com/browse/PSCSX-7924

Why the heck nobody cares about this?

There are three possible logic ways:

1) customers gets his invoices in HIS language and BO too (might be complicated with your taxoffice at home)
2) customer gets invoices in a predefined language. BO same language (should be default)
3) customer gets his invoice in HIS language and BO in predefined language

Absolutely NOT should BO or the customer gets the invoice automatically in the language the Admin is using. 

**EDIT:**
**I have to correct myself. BO and attached invoice to payment accepted eMail is Admin (logged in user) Language.** 
**FO, when customer is logged in, is customer language. Still no consistent logic here. I would consider this a bug.**

Please could somebody enlighten me why it seems to be this way still in 1.7.5.1? Maybe i´m missing something.

**Comment by khouloudbelguith** [comment] 2019-02-25 07:54
Hi @holle75,

Thanks for your report.
We are aware of this issue, we have come up with an idea.
We could add in Shop parameters > Order settings the ability to choose between customer language and employee language to download delivery slips and invoices when preparing orders.
it is added to our debug roadmap.
Your ticket is a duplicate of #10258
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-25 07:55
Duplicate of #10258

**Closed as completed by khouloudbelguith** 2019-02-25 07:54 UTC
Labels: Duplicate

**Comment by holle75** [comment] 2019-02-25 10:53
Thank you @khouloudbelguith
