### ISSUE TITLE
Category.php -> searchByPath: support using same category names under different hierarchy

### ISSUE THREAD

**Issue by mschiele** [PrestaShop/PrestaShop#19241] opened 2020-05-20 14:46 UTC
#### Is your feature request related to a problem?
When importing non existing categories via e.g. csv import as a string, searchByPath does not properly resolve all levels if we reuse a category name under a different hierarchy.

To resolve this, the signature of searchByPath needs to be extended to pass idParentCategory.

**Comment by LouiseBonnard** [comment] 2020-05-20 16:23
Hi @mschiele, thanks for the feedback! Could you please provide us with more information? We need more details to fully understand this issue:

- PrestaShop version (source)
- screenshots
- expected behavior
- etc.

You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report, thank you.

**Comment by sarahdib** [comment] 2020-06-16 12:12
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-06-16 12:12 UTC
Labels: Improvement, BO, Categories, Import / Export, No change required
