### ISSUE TITLE
When maintenance mode is enabled, don't require adding IP for logged in admins

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#30161] opened 2022-10-30 09:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I do a lot of IT support for various shops and I have to store my IP each time (I have a dynamic IP)

### Describe the solution you'd like

The front-end could detect if the user is logged in to the backoffice and allow them access without requiring the IP to be stored

### Additional context

If you'd like, I can submit a PR to implement this improvement

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment] 2022-10-31 09:20
Hello @unlocomqx ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Thank you

**Comment by unlocomqx** [comment] 2022-10-31 10:17
Hello @florine2623 ,

I can submit a PR for this feature

Best regards

**Comment by kpodemski** [comment] 2022-10-31 10:31
@unlocomqx I've just assigned you to this issue! :) I think it's a great idea, but it should probably be an additional setting inside the Maintenance tab. What do you think?

**Comment by unlocomqx** [comment] 2022-10-31 10:57
@kpodemski Thank you

Yes, it's a good idea to add a switch to determine if admins get automatic access to the front-end or not

Example

![screenshot-001366](https://user-images.githubusercontent.com/793712/198990899-d0dec9a0-7c9a-40fd-8e89-ababe4a27c31.png)

The maintenance mode icon could indicate if the option is enabled
<img width="370" alt="image" src="https://user-images.githubusercontent.com/793712/198991715-3969d3ed-3866-40b0-9bac-d81d0ff39f5f.png">

The tooltip can also indicate this
![screenshot-001369](https://user-images.githubusercontent.com/793712/198992499-65210fd5-0f09-4385-aa47-a954e565ed3c.png)

**Comment by Hlavtox** [comment] 2022-11-02 01:13
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/18932

Specs and wording for this issue are here: https://github.com/PrestaShop/prestashop-specs/pull/183/files

**Closed as completed** 2023-01-24 13:57 UTC
Labels: Feature, CO, Maintenance, Developer Feature, PR available
