### ISSUE TITLE
Installing Prestashop 8 fails at the first step SSL_CTX_set_default_verify_paths

### ISSUE THREAD

**Issue by Signtester** [PrestaShop/PrestaShop#36080] opened 2024-05-03 01:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I uploaded the zip file, then manually installed. But when it got to "Create File parameters" the install fails.  My host techs claim it is a problem with the coding, and I don't understand enough to know, but they say I need coding help from the developers. Hoping someone can tell me how to fix this issue.

This is the error log.

[02-May-2024 20:22:05 UTC] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in /home/signtest/public_html/stablehandspottery.ca/install/controllers/http/smarty_compile.php on line 26
[02-May-2024 13:22:08 America/Vancouver] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2026] SSL connection error: SSL_CTX_set_default_verify_paths failed in /home/signtest/public_html/stablehandspottery.ca/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40

### Steps to reproduce

Follow the install procedure everything works until create file parameters

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

7.1

**Comment by matks** [comment] 2024-05-03 09:18
Hi @Signtester your issue is identical to https://github.com/PrestaShop/PrestaShop/issues/33524

Read the thread https://github.com/PrestaShop/PrestaShop/issues/33524 to see if it can help you

I am 100% this is related to a server specific configuration item on your side and not a problem of PrestaShop

> My host techs claim it is a problem with the coding

Your host tech is wrong. He should read the line `PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2026] SSL connection error: SSL_CTX_set_default_verify_paths failed in` and google it : https://www.google.com/search?q=ssl_ctx_set_default_verify_paths

**Comment by paulnoelcholot** [comment] 2024-05-06 14:08
Hello @Signtester,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-05-06 14:08 UTC
Labels: Bug, Can't reproduce

**Comment by ChillCode** [comment] 2024-05-07 13:08
Hi @Signtester 

PrestaShop 8.1* is not compatible with PHP 7.1, try to upgrade to 7.4 or 8.1.

![image](https://github.com/PrestaShop/PrestaShop/assets/9787055/5442685c-de7f-43d5-9dba-e27aa52620b4)
