### ISSUE TITLE
Product comment module doesn't display comments in FO

### ISSUE THREAD

**Issue by amine-O** [PrestaShop/PrestaShop#34814] opened 2023-12-12 10:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As a visitor I comment a product and I give a note. 
Actual behavior : The count of comments appear and the grade but not the commentary text 
![image (33)](https://github.com/PrestaShop/PrestaShop/assets/153521311/a5458d29-b3e4-41fb-90a0-44d4390a4828)

### Expected behavior

The commentary text is displayed with all the commentaries

### Steps to reproduce

1. As a visitor on FO 
2. Write a review and add a grade

### PrestaShop version(s) where the bug happened

8.1.2

### If your bug is related to a module, specify its name and its version

productcomments v6.0.2

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by florine2623** [comment] 2023-12-13 09:43
Hello @amine-O ,

I can't reproduce your issue with PS 8.1.2 and productcomments v6.0.2.

Can you specify the config of your module ?

**Comment by paulnoelcholot** [comment] 2024-01-02 16:02
Hello @amine-O,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-01-02 16:02 UTC
Labels: Bug, FO, Can't reproduce, Productcomments, Module, 8.1.x
