### ISSUE TITLE
Invoice language settings suggestion

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#24177] opened 2021-04-23 08:54 UTC
#### Is your feature request related to a problem?

The problem is that invoice is created in the language of the shop in backoffice of team member that create it, for example, if the team member has backoffice in Italian all invoices are created in Italian, but if you export outside CE , invoices must be in english.  

#### Describe the solution you'd like

A workaround is to set language in english, make invoice and then reset lang to Italian, a better solution will be that i can set zone or nations with invoice lang

#### Additional context
* PrestaShop version: ALL
* PHP version: ALL

**Comment by florine2623** [comment] 2021-04-23 09:39
Hello @Betafer ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by hibatallahAouadni** [comment] 2021-06-14 06:51
Hello @Betafer 


We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10258. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-14 06:52
Duplicate of #10258

**Closed as completed** 2021-06-14 06:51 UTC
Labels: Feature, CO, Duplicate, Invoices, Translations
