### ISSUE TITLE
courier image error

### ISSUE THREAD

**Issue by Gionny996** [PrestaShop/PrestaShop#11433] opened 2018-11-19 11:51 UTC
when I change courier and load the logo, I do not load the image, but it does not give me no error, in fact when I do "end" tells me that everything is successful and in the folder img / tmp also loads the image

**Comment by khouloudbelguith** [comment] 2018-11-19 13:11
Hi @Gionny996,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Gionny996** [comment] 2018-11-19 13:21
the problem is caused by some module, in fact if you rename the module folder in module_del, after the problem no longer occurs. The problem is that I do not know what module it is

**Comment by khouloudbelguith** [comment] 2018-11-19 13:28
@Gionny996, it is probably a transport module, when the debug mode, there are no exceptions displayed, you need to rename all folder module one by one, clear cache & check if the error happens again.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-21 14:01
Hi @Gionny996,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-21 14:01 UTC
Labels: BO, Can't reproduce, Carriers
