### ISSUE TITLE
Exception when configuring a module with multi-store context, with a developer mode enabled

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#37433] opened 2024-11-22 08:46 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It is impossible to configure modules with a developer mode and multi-store enabled.

![Image](https://github.com/user-attachments/assets/36eb2031-3511-46c2-b139-eb6575c5a9cb)

### Steps to reproduce

Use multi-store, configure any module.

### PrestaShop version(s) where the bug happened

9.0.0

### Your company or customer's name goes here (if applicable).

PrestaShop SA

**Comment by florine2623** [comment] 2024-11-22 09:18
Hello @kpodemski ,

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/37222

I'm closing your issue to avoid clogging the backlog ^^

**Closed as completed by florine2623** 2024-11-22 09:18 UTC
Labels: Bug, Duplicate
