### ISSUE TITLE
Mail alerts module - emailing when the number in stock matches the minimum stock held

### ISSUE THREAD

**Issue by saudis79** [PrestaShop/PrestaShop#24360] opened 2021-05-05 17:07 UTC
#### Describe the bug

Having recently installed the mail alerts module (v2.3.0) to my Prestashop installation (1.7.7.4) I am now receiving "almost out of stock" reports on items that are in stock and meet the minimum quantity available. The emails arrives even if I only alter the price of the product! I have checked and the reported number of products available is equal to or more than the minimum amount in stock set within the mail alerts module.

#### Expected behavior

I would only expect the alert to be sent when the number of available products falls under the minimum amount of stock held

#### Steps to Reproduce

1. Modify the price of the product
2. Receive the email below highlighting the quantity in stock

**Screenshots**

![image](https://user-images.githubusercontent.com/40228983/117180400-0d1efb80-adcc-11eb-9298-bec383357090.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment] 2021-05-06 05:12
Hello @saudis79 

Could you please check this issue #17830 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by saudis79** [comment] 2021-05-07 13:25
@hibatallahAouadni - I think it could be the same issue. I had copied the code from the other issues into the override code and I'm not seeing the false email alerts for sticking issues. Hopefully this issue can be merged and fixed in one minor update.

**Comment by hibatallahAouadni** [comment] 2021-05-07 15:00
Hello @saudis79 

Glad to hear :tada: 
> Hopefully this issue can be merged and fixed in one minor update.

Yep, I hope so too. (https://github.com/PrestaShop/ps_emailalerts/pull/45)

As we are aware of this issue and it is already in our debug backlog. This issue is a duplicate of #17830 . 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-07 15:01
Duplicate of #17830

**Closed as completed by hibatallahAouadni** 2021-05-07 15:00 UTC
Labels: Bug, CO, Duplicate, Stocks, Email, ps_emailalerts, 1.7.7.4
