### ISSUE TITLE
Backoffice Order: Product with custom field is added twice

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#17064] opened 2020-01-08 13:49 UTC
**Describe the bug**
When creating a backoffice order and adding a product that **has custom text fields not required**, the product is added twice.

**To Reproduce**
Requirement: Have a product that has a custom text field **NOT required**
1. Go to Orders settings
2. Click on add new order
3. Select your customer
4. Search for a product that has custom text field
5. Add this product to the cart
=> The product is added with quantity 2 even if we filled the quantity with 1

If we set the custom field as required, the quantity is correct, but we can't edit the quantity (it stays at 1 even if we change the quantity.

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.3

**Comment by khouloudbelguith** [comment] 2020-01-08 13:57
Hi @arirangz,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9689
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-08 13:57
Duplicate of #9689

**Comment by khouloudbelguith** [comment] 2020-01-08 13:58
PS: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-08 13:57 UTC
Labels: Duplicate, Order, Product customization

**Comment by arirangz** [comment] 2020-01-08 14:17
Thanks! I changed my php version.

Do you know approx when this issue will be solved?

Thanks

**Comment by khouloudbelguith** [comment] 2020-01-08 15:10
@arirangz, in the next version PS1.7.7.0, the Order page will be migrated => so it could be fixed.

Thanks!

**Comment by webstartconsulting** [comment] 2020-03-30 11:47
Hi!
My prestashop version is 1.7.6.4 and php 7.1 (or 7.2 as i wish). How i can fix this issue? Have a quickfix on it?
Thanks

Regards
Norbert

**Comment by khouloudbelguith** [comment] 2020-03-30 12:31
Hi @webstartconsulting,

This issue is fixed in the migrated page as you can see in this [comment](https://github.com/PrestaShop/PrestaShop/issues/9689#issuecomment-574751535).

Thanks!

**Comment by webstartconsulting** [comment] 2020-03-30 15:54
The "migrated page" will arrive with version 1.7.7. In the meantime, I should somehow fix it in a 1.7.6.x web store.
Or do I misunderstand it all?

**Comment by khouloudbelguith** [comment] 2020-03-30 16:22
@webstartconsulting, sorry, there is no fix for the branch 1.7.6.x.
>The "migrated page" will arrive with version 1.7.7

Yes!
We are re-working on the new Order page to fix issues.

Thanks!

**Comment by arirangz** [comment] 2020-03-31 10:32
Thanks for the update.
Do you have an approx. ETA for the release of the 1.7.7?
Thanks

**Comment by khouloudbelguith** [comment] 2020-03-31 10:42
Hi @arirangz,

You can follow our Project PrestaShop 1.7.7 process [here](https://github.com/PrestaShop/PrestaShop/projects/7)

Thanks!

**Comment by arirangz** [comment] 2020-04-15 10:30
Thanks @khouloudbelguith  
But do you have an approx ETA? It's to know if the release should be in the next weeks or months
