### ISSUE TITLE
Category description text shouldn't be below the image

### ISSUE THREAD

**Issue by dineshbadrukhiya** [PrestaShop/PrestaShop#11494] opened 2018-11-25 05:38 UTC
**Describe the bug**
Category description texts should not be below the image in the classic theme design.

**To Reproduce**

1. Go to 'Category page on classic theme'

**Screenshots**
![category-page](https://user-images.githubusercontent.com/40850057/48975919-5074cc00-f0a2-11e8-9ab1-9302447f7e40.png)

**Additionnal information**
PrestaShop version: 1.7.4.4

**Comment by Quetzacoalt91** [comment] 2018-11-26 09:11
I wonder if it wasn't the expected behavior. Adding a UX review.

**Comment by khouloudbelguith** [comment] 2018-11-26 10:40
Hi @dineshbadrukhiya,

We are aware of this issue, it is added to our debug roadmap.
Thanks for your fix.
Your ticket is a duplicate of #9979
@Quetzacoalt91, I will add the label in the other issue.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-26 10:40
Duplicate of #9979

**Closed as completed by khouloudbelguith** 2018-11-26 10:40 UTC
Labels: Duplicate
