### ISSUE TITLE
BO orders history error 500

### ISSUE THREAD

**Issue by jajarom** [PrestaShop/PrestaShop#16059] opened 2019-10-22 05:07 UTC
Error 500 appear when try to acces orders history in admin. Have some errors with modules maintenance mode on.
This is related to #15173 ?

Price specification not found for currency: ""

    Exception Logs 2 Stack Trace 

PrestaShop\PrestaShop\Core\Localization\Exception\ LocalizationException
in src/Core/Localization/Locale.php (line 171)

        public function getPriceSpecification($currencyCode)
        {
            $currencyCode = (string) $currencyCode;
            $priceSpec = $this->priceSpecifications->get($currencyCode);
            if (null === $priceSpec) {
                throw new LocalizationException(
                    'Price specification not found for currency: "' . $currencyCode . '"'
                );
            }
            return $priceSpec;

Locale->getPriceSpecification('') in src/Core/Localization/Locale.php (line 155)
Locale->formatPrice('0.000000', null) in classes/Tools.php (line 776)
ToolsCore::displayPrice('0.000000', object(Currency)) in src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php (line 247)
GetCustomerForViewingHandler->getCustomerOrders(object(Customer)) in src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php (line 124)
GetCustomerForViewingHandler->handle(object(GetCustomerForViewing)) in vendor/league/tactician/src/Handler/CommandHandlerMiddleware.php (line 71)
CommandHandlerMiddleware->execute(object(GetCustomerForViewing), object(Closure)) in vendor/league/tactician/src/CommandBus.php (line 62)
CommandBus->League\Tactician\{closure}(object(GetCustomerForViewing)) in vendor/league/tactician/src/CommandBus.php (line 42)
CommandBus->handle(object(GetCustomerForViewing)) in src/Core/CommandBus/TacticianCommandBusAdapter.php (line 54)
TacticianCommandBusAdapter->handle(object(GetCustomerForViewing)) in src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (line 226)
CustomerController->viewAction('1357', object(Request)) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 151)
HttpKernel->handleRaw(object(Request), 1) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 68)
HttpKernel->handle(object(Request), 1, false) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
Kernel->handle(object(Request), 1, false) in admin094lidvz5/index.php (line 86) 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-22 08:53
Hi @jajarom,

This bug was already identified in https://github.com/PrestaShop/PrestaShop/issues/15376
And here's the PR fixing this issue: https://github.com/PrestaShop/PrestaShop/pull/15643
It is fixed in the next patch PS1.7.6.2
Your ticket is a duplicate of #15376
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-22 08:53
Duplicate of #15376

**Closed as completed by khouloudbelguith** 2019-10-22 08:53 UTC
Labels: Duplicate
