### ISSUE TITLE
Meta Description bug 

### ISSUE THREAD

**Issue by damiankalka** [PrestaShop/PrestaShop#14105] opened 2019-06-07 07:05 UTC
Hey!

I would like Presta not to download to meta description the text from category description, but only from a field meta description. In case of an empty field "meta description" there should be a replacement content.

In Presta 1.6. I used below solution and it worked:

```
{if isset($meta_description) AND $meta_description}
<meta name="description" content="{$meta_description|escape:html:'UTF-8'}" />
{else}
<meta name="description" content="{$meta_title|escape:html:'UTF-8'} Lorem ipsum Lorem ipsum Lorem Ipsum." />
{/if} 
```

Unfortunately in Prestashop 1.7. variable  $page.meta.description is always downloading category description. Is there any solution to block it?

**Comment by mariem-abid** [comment] 2019-06-07 15:43
Hi @damiankalka,

I did not manage to reproduce the issue with PS:1.7.5.2 and PS:1.7.6.0beta1
I attached a video record.
https://drive.google.com/file/d/1XcP0ti7QtHohempcD0FgAW2Z8j9gARSD/view
Thanks for check and feedback.

**Comment by damiankalka** [comment] 2019-06-07 17:11
Check out the source code for this category.

**Comment by khouloudbelguith** [comment] 2019-06-11 13:22
Hi @damiankalka,

In fact, if you create a new category with description not empty, this is will be automatically meta description.
I attached a video record.
https://drive.google.com/file/d/1lU3FJj40srlRvq4wJoC-zHARcyJz9zvz/view
Same behavior with PS1.7.6.0beta1 & PS1.7.5.2
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-07-11 08:47
Hi @damiankalka,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-11 08:47 UTC
Labels: BO, Categories, No change required

**Comment by damiankalka** [comment] 2019-07-11 08:50
???

**Comment by khouloudbelguith** [comment] 2019-07-11 08:52
@damiankalka, I 'm just waiting for your feedback about my last comment & there is no response for more than 30 days.
>In fact, if you create a new category with description not empty, this is will be automatically meta description.
I attached a video record.
https://drive.google.com/file/d/1lU3FJj40srlRvq4wJoC-zHARcyJz9zvz/view
Same behavior with PS1.7.6.0beta1 & PS1.7.5.2
Thanks to check & feedback.
