### ISSUE TITLE
Out of stock product is still added to the cart

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#13374] opened 2019-04-12 06:58 UTC
**Describe the bug**
Add to cart an out of stock product (order refused) return an error but the product is still added to the cart

**To Reproduce**
1. Go to a product page
2. Change quantity to zero without reloading 
3. Add the product to the cart
4. See errror in the chrome inspector

**Screenshots**
see screenshot
http://creabilis.com/tmp/addtocartbug.jpg

**Additionnal information**
PrestaShop version: 1.7.6 develop branch
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-04-12 08:23
Hi @jf-viguier,

I did not manage to reproduce the issue with PS:1.7.5.1 and 1.7.6.x develop branch.
I attached a video record.
https://drive.google.com/file/d/1tvzj7WKJkE3GxvmmTDQcMqsU2RDw3sA6/view

Thanks to check and feedback.

**Comment by jf-viguier** [comment] 2019-04-12 13:12
Your test is wrong, your product has to be in stock before adding it to the cart :
Change quantity to 4
Go to a product page in front
Change quantity to zero without reloading
Add the product to the cart
See errror in the chrome inspector

**Comment by khouloudbelguith** [comment] 2019-04-12 13:55
@jf-viguier, could you please add a video record.

**Comment by marionf** [comment] 2019-04-12 14:37
Related to https://github.com/PrestaShop/PrestaShop/issues/11631

**Comment by jf-viguier** [comment] 2019-04-12 14:49
@khouloudbelguith : -1 is and out of stock quantity : use 4 or 5 and u'll see.

**Comment by jf-viguier** [comment] 2019-04-17 21:32
Have you reproduced the error ?

**Comment by khouloudbelguith** [comment] 2019-04-18 15:02
@jf-viguier, yes I manage to reproduce the issue with PS1.7.5.1.
![image](https://user-images.githubusercontent.com/16067358/56370480-307daa80-61f3-11e9-9c2e-3348832d1317.png)
It is added to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by jf-viguier** [comment] 2019-04-18 15:52
ok great.

**Comment by matks** [comment] 2019-05-15 16:06
@marionf After trying to reproduce on 1.7.6.x, I do that:
- go on FO product page
- display the page when product has stock > 0, keep the page open
- then go to BO, modify the stock quantity for this product to 0
- go back to the FO page not refreshed and click on "add to cart"

I see the following behavior now:
- the modal opens which still bad (this will be fixed by https://github.com/PrestaShop/ps_shoppingcart/pull/41)
- but the product is not added to the cart 🤔so I think this issue is solved

**Comment by marionf** [comment] 2019-05-15 16:18
@matks 

I just tried on 1.7.6.x branch, after clicking on add to cart if you refresh the page you will see the product has been added to the cart

**Comment by matks** [comment] 2019-05-15 16:28
@marionf Let's see together tomorrow 🤔I dont have this behavior

I mean, is it really added to the cart or do you see "Product successfully added to cart" message ?

**Comment by marionf** [comment] 2019-05-15 16:31
This what I have:
https://drive.google.com/file/d/1IPJ1Oely15nhPG5MEUshGWttMGf5XVIF/view?usp=sharing

But yes, let's see it tomorrow if you don't have the same behavior :+1:

**Comment by marionf** [comment] 2019-06-03 15:19
We have 2 cases to handle: 

1) Enter 5 in quantity field, change product quantity in BO for 3, return on the product page and click on add to cart. In this case, we can:
- Add 3 products to the cart and display a message like "Only 3 products have been added to the cart because there isn't enough quantity in stock"
- Add 0 products to the cart and display a message like "The product is no longer available in this quantity. Please adjust quantity"

2) Enter 5 in quantity field, change product quantity in BO for 0, return on the product page and click on add to cart. In this case, 0 products should be added to the cart and we can display a message like "This product is out of stock"

@matks wdyt ?

**Closed as completed** 2019-10-11 14:28 UTC
Labels: Bug, Major, FO, Fixed, 1.7.5.1, 1.7.6.0, Must-have

**Comment by matks** [comment] 2019-10-11 14:29
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15623
