### ISSUE TITLE
email variables not filled when email address is all capital letters

### ISSUE THREAD

**Issue by kodarco** [PrestaShop/PrestaShop#16436] opened 2019-11-15 17:24 UTC
I'm having a bizzarre problem with email variables. They are not filled out completely when the customer's email address is spelled all capital letters.
This is for the payment by money order (standard prestashop module) and it refers to cheque.html and txt template, tried on customized and also on default template.
See example, on first image customer's email astralogo... is spelled small letters, the second screen shows what email I've got. Bear in mind the variables {check_name} and {check_address_html}  are never filled out and I don't know why.
But when I change the email address to all capital, see image 3, I got the email without any variables filled out, see image 4.

![screen1](https://user-images.githubusercontent.com/43558067/68962533-1df14100-07d5-11ea-9562-cf192e796910.JPG)
![screen2](https://user-images.githubusercontent.com/43558067/68962542-20ec3180-07d5-11ea-9ef9-a0319f622eec.JPG)
![screen3](https://user-images.githubusercontent.com/43558067/68962545-22b5f500-07d5-11ea-97a7-a03e287bc88b.JPG)
![screen4](https://user-images.githubusercontent.com/43558067/68962548-247fb880-07d5-11ea-94f7-a4c4bdf0836b.JPG)
![screen5](https://user-images.githubusercontent.com/43558067/68962550-25b0e580-07d5-11ea-8cea-9e134297c5da.JPG)

This is on PS 1.7.6.0, php 7.2.24 and I'm using php mail() function, see image 5 for more details.
I don't see any errors in Apache log related to this. The screenshots are from the test store install. The same error appears on the production store on the same domain/server.

Thanks for your help!

**Comment by Allba** [comment] 2019-11-18 07:41
Same problem here, didn't notice that the problem was capital letters on the email, i will try to enforce lowercase email submission until their is a proper fix.

**Comment by khouloudbelguith** [comment] 2019-11-18 07:46
Hi @kodarco, @Allba,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13386
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-11-18 07:46
Duplicate of #13386

**Closed as completed by khouloudbelguith** 2019-11-18 07:46 UTC
Labels: Duplicate

**Comment by crishnakh** [comment] 2019-12-05 17:38
Wow! a lot time with this problem.  Never imagine that the uppercase email was the problem.

**Comment by khouloudbelguith** [comment] 2019-12-06 09:57
Hi @crishnakh,

Fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16550

Thanks!

**Comment by sharkooon** [comment] 2020-03-09 11:29
So why is this bug still not deployed in 1.7.6.4?

**Comment by khouloudbelguith** [comment] 2020-03-09 11:32
Hi @sharkooon,

A new patch version is released for the correction of critical bugs and regressions only.

Thanks!
