### ISSUE TITLE
There are not anough products in stock for virtual products

### ISSUE THREAD

**Issue by jajarom** [PrestaShop/PrestaShop#16301] opened 2019-11-07 06:16 UTC
**Describe the bug**
When I try to add a custom virtual product, I get the error "There are not anough products in stock", even if the product is in stock.

**To Reproduce**
Add any virtual product in cart.
I thought this problem was solved

**Screenshots**
![error](https://user-images.githubusercontent.com/5030991/68364497-ce58a880-0136-11ea-9db1-a427bde8d9bf.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-11-07 08:01
Hi @jajarom,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1aSIAAClDv_WZJX_66d21WgXnyOsUBg4X/view
Thanks to check & feedback.

**Comment by jajarom** [comment] 2019-11-07 19:35
Ok.
This problem occurs after I upgrade the Block Cart module, from 2.0.2 to 2.0.3 in the BO. After copy old files back, all good.
So i think here can be a bug from the module.

Thx

**Comment by khouloudbelguith** [comment] 2019-11-08 11:03
@jajarom, is it the ps_shoppingcart module? 
We have reproduced recently an issue with products out of stock reported here: https://github.com/PrestaShop/PrestaShop/issues/16260
Do you have the same issue?

Thanks!

**Comment by jajarom** [comment] 2019-11-08 11:22
Yes, same issue on latest Prestashop.
So need to copy old folder after update.

**Comment by khouloudbelguith** [comment] 2019-11-08 11:27
@jajarom, we are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16260
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-11-08 11:28
Duplicate of #16260

**Closed as completed by khouloudbelguith** 2019-11-08 11:27 UTC
Labels: Bug, FO, Duplicate, Product customization, Virtual, 1.7.6.1
