### ISSUE TITLE
BO - The RTL language is not functional and an empty loaded pop-up is displayed on BO when change profile language in Arabic 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#32361] opened 2023-04-27 09:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The RTL language is not functional and an empty loaded pop-up is displayed on BO when change profile language in Arabic

![image](https://user-images.githubusercontent.com/92912932/234826683-0aa03723-86a8-4a6f-baf9-1fbc6446ac81.png)

**Develop : NOK** :x: 

https://user-images.githubusercontent.com/92912932/234827322-7542e113-a191-4c27-85a1-d3bc34be2e15.mp4

**8.0.3 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/234828361-9d46dd75-beb4-4462-a2d0-1007d16858d1.mp4

**8.0.4 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/234828395-30756078-0fd2-4973-bcab-9114d0e3ad94.mp4

So, it's a regression on develop!

### Expected behavior

The language is well changed and no empty loaded pop-up

### Steps to reproduce

1. Use develop
2. Go to IMPROVE > International > Localization > Import Algeria pack
3. Go to You profile > Change the language to Arabic
4. Click on Save
5. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-04-28 12:06
Hello @HanaRebaiQA ,

Your issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/32070

So I'll close it ^^
Thanks!

**Comment by florine2623** [comment] 2023-04-28 12:06
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/32070

**Closed as completed by florine2623** 2023-04-28 12:06 UTC
Labels: Bug, develop, Major, BO, Duplicate, Languages, Profiles, Regression
