### ISSUE TITLE
whishlist: add a product, it is duplicated in the list

### ISSUE THREAD

**Issue by ftrouve** [PrestaShop/PrestaShop#37324] opened 2024-11-06 07:25 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,

On my client's PrestaShop 1.7.8.8 store, I installed the free whishlist module provided on addons.
https://www.leguano.fr/
I activate it, everything is ok on the store. you can add a product. But when you consult the product, it appears in duplicate.
If I delete it the 2 duplicates are deleted.
Tested several times same behavior with each addition 2 products are found in the list.
I tested the module on another store, same behavior

I had to deactivate the module due to the bug

best regards

### Steps to reproduce

1. activation wishlist module 
2. connection to my account on the store
3. adding a product to the list
4. consultation of the list
5. 2 duplicate products

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7

### If your bug is related to a module, specify its name and its version

Wishlist v2.1.2 - par PrestaShop

**Comment by ftrouve** [comment] 2024-11-06 07:25
![Image](https://github.com/user-attachments/assets/c62a4e09-b905-4af2-8855-237a210f02b2)

**Comment by florine2623** [comment] 2024-11-06 08:59
Hello @ftrouve ,

I can't reproduce your issue with module Wishlist v3.0.2. Please update your module.

I'm closing the issue as I can't reproduce it.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2024-11-06 08:59 UTC
Labels: Bug

**Comment by ftrouve** [comment] 2024-11-06 10:29
**but the module V3.0.2  is not for the prestashop version 1.7.8.**
For this version the module is on v2.1.2
