### ISSUE TITLE
Wrong current category on the product page when browsing paginated product list

### ISSUE THREAD

**Issue by jbenezech** [PrestaShop/PrestaShop#20946] opened 2020-09-11 01:08 UTC
#### Describe the bug

When a category has many products, the category page lists these products with a pagination.
Clicking on a product from the second or more page will change the "current" category to the product's default instead of the category being browsed.

#### Expected behavior

The "current" category should be the last visited one

#### Steps to Reproduce
>Edit by Khouloud
1. Go to BO > Design > Position > Transplant the `ps_categorytree` module to `displayProductAdditionalInfo` hook
2. Go to BO > Products > edit the demo product id_product=7 with default category = Home & edit the demo product id_product=8 with default category = Home
![image](https://user-images.githubusercontent.com/16067358/93078328-98574f80-f68a-11ea-8f30-a9ac066cd6ba.png)
3. Go to BO > Shop Parameters > Product Settings > set Product per page =2
4. Go to http://shop.com/en/6-accessories
5. Choose the product "MUG THE ADVENTURE BEGINS"
-> Notice the breadcrumb, the default category is Home
-> Notice the ps_categorytree under it, the current category is "Accessories"
6. Go to http://shop.com/en/6-accessories
7. Click on the "Next" in the pagination
8. Choose the product "MUG TODAY IS A GOOD DAY"
-> Notice the breadcrumb,  the default category is also Home
-> Notice the ps_categorytree under it, current category is "Home"

1. Have a category of products "T-Shirts"
2. Create many products that belong to the "T-Shirts" category and which default category is "Home"
3. Got to the "T-Shirts" category
4. Click on a product -> the current category is "T-Shirts" (<strong>This is correct</strong>)
5. Go to the second page of pagination of the "T-Shirts" category
6. Click on a product -> the current category is "Home" (<strong>This is NOT correct</strong>)

This affects in particular the behaviour of the `ps_categorytree` module.

**Screenshots**

#### Additional information

PR to follow

**Comment by florine2623** [comment] 2020-09-11 10:26
Hi @jbenezech ,
I can't reproduce your issue on PS 1.7.6.7. Maybe the issue in on another version of PrestaShop ?

When a product has "Home" as it main category and "T-shirt" as an associated category, you can find the product under T-shirt and Home category, but the breadcrumb will show the main category.
![Capture d’écran 2020-09-11 à 12 24 36](https://user-images.githubusercontent.com/16019289/92912319-f3d6d280-f429-11ea-9c3a-4ad960529736.png)
![Capture d’écran 2020-09-11 à 12 24 57](https://user-images.githubusercontent.com/16019289/92912327-f5a09600-f429-11ea-8a84-bbe20cbb3e9f.png)

Please check the version of PS and screenshots if you have any.
Thanks!

**Comment by jbenezech** [comment] 2020-09-11 10:35
I'm pretty sure the bug is still there as I've identified the faulty piece of code in the develop branch.  
It's just difficult to spot as it affects an internal variable which has side effects on other things like the ps_categorytree module.  
It doesn't affect the breadcrum, you're correct.

I'll try to do a demo video when I get time.

Definitely not a priority bug though.

**Comment by florine2623** [comment] 2020-09-11 15:14
Ok nice, I'm waiting for your video :)

**Comment by jbenezech** [comment] 2020-09-13 02:24
I've setup an install instead ;) From the develop branch.

1. Go to http://presta20946.khlix.com/en/6-accessories
2. Choose the product "MUG THE ADVENTURE BEGINS"
-> Notice the breadcrumb, the default category is Home
-> Notice the ps_categorytree under it, current category is "Accesssories"

3. Go to http://presta20946.khlix.com/en/6-accessories
4. Click on the "Next" in the pagination
5. Choose the product "MUG TODAY IS A GOOD DAY"
-> Notice the breadcrumb,  the default category is also Home
-> Notice the ps_categorytree under it, current category is "Home"

**Comment by khouloudbelguith** [comment] 2020-09-14 09:09
Hi @jbenezech,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10763
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-14 09:09
Duplicate of #10763

**Comment by khouloudbelguith** [comment] 2020-09-14 09:48
Hi @jbenezech,

As commented [here](https://github.com/PrestaShop/PrestaShop/issues/10763#issuecomment-691939014), I will re-open the issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-14 10:50
@jbenezech,

Thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.7 and PS1770beta2 using the `ps_categorytree` v2.0.0.
Similar products but different current category
![image](https://user-images.githubusercontent.com/16067358/93077180-c045b380-f688-11ea-9b6d-cfdc099295df.png)
![image](https://user-images.githubusercontent.com/16067358/93077229-ce93cf80-f688-11ea-97a6-9ad82fa0abcb.png)

I’ll add this to the debug roadmap.

Thanks!

**Comment by florine2623** [comment] 2023-10-12 13:12
Hello all,

I can't reproduce this issue anymore on PS `8.1.0` and Category tree links `v2.0.3`.

In both cases, the category is always Home as expected :

<img width="1171" alt="Screenshot 2023-10-12 at 15 11 19" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/78d254ce-1f00-45b6-a30e-ed19676c6f9e">
<img width="1141" alt="Screenshot 2023-10-12 at 15 11 24" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4f542b4c-cd01-42c9-929e-977fe398f897">

I'm closing this issue to avoid clogging the backlog.

**Closed as completed by florine2623** 2023-10-12 13:12 UTC
Labels: Bug, Minor, FO, Categories, Fixed, Category tree, PR available, Module, 8.1.x
