### ISSUE TITLE
Welcome module: cannot uninstall module from command line

### ISSUE THREAD

**Issue by denys202** [PrestaShop/PrestaShop#24946] opened 2021-06-14 08:18 UTC
#### Describe the bug

I am trying to uninstall module from the command line, but there is an error during this process.

#### Expected behavior

No errors while uninstalling module.

#### Steps to Reproduce

1. Go to your root directory in console.
2. Run the next command `php bin/console prestashop:module uninstall welcome -e prod` (or without -e prod if your are in prod environment)
3. You will see the next error in console: 
In welcome.php line 148:  Call to a member function setCurrentStep() on null 
**Screenshots**
![image](https://user-images.githubusercontent.com/52750352/121861030-bcb78980-ccf9-11eb-8d1b-089bc6283671.png)

#### Additional information

I tried to uninstall this module from BO, but everything is ok (because the onBoarding object is not null and the _PS_ADMIN_DIR_ constant exists).

* PrestaShop version: 1.7.7.5
* Wlcome module version: 6.0.5
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-06-14 08:56
Hello @denys202 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12552. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-14 08:56 UTC
Labels: Duplicate

**Comment by hibatallahAouadni** [comment] 2021-06-14 08:58
Duplicate of #12552
