### ISSUE TITLE
Warning on line 1021 in file /prestashop/controllers/admin/AdminCustomerThreadsController.php [2] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by FRaccie** [PrestaShop/PrestaShop#23837] opened 2021-03-31 10:21 UTC
#### Description

When saving the imap settings on the backend customer service page the following error is shown.

`Warning on line 1021 in file /prestashop/controllers/admin/AdminCustomerThreadsController.php [2] count(): Parameter must be an array or an object that implements Countable`

LINE 1014 = `$errors = imap_errors()` 
this returns a boolean when there are no errors.

LINE 1021 = `if (count($errors) && is_array($errors) {` _[current code]_
This is because the IF-statement which checks the $errors array is in the wrong order.
If nothing is returned from imap_errors() then $errors becomes a boolean which isn't countable

Changing LINE 1021 fixes the issue 
`if (is_array($errors) && count($errors))  {` _[fix code]_
 -> switching the 2 options of the IF-statement

#### Steps to Reproduce

1. Go to 'Customer Service' in the backend
2. Setup IMAP settings & Save
3. Revisit the 'Customer Service' page

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-03-31 12:36
Hello @FRaccie ,
I can't reproduce your issue on neither PS 1.7.7.2 nor PS 1.7.7.3.
Please check my screen record : https://drive.google.com/file/d/1jvAfNJzVqAAmQ45SNGqb-RTxoHa1LA--/view
Am i missing something ?

Please check and feedback.
Thanks!

**Comment by florine2623** [comment] 2021-04-16 09:49
Hello @FRaccie ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-04-16 09:49 UTC
Labels: Bug, BO, Can't reproduce, Customer service, PR available, 1.7.7.2

**Comment by musicpanda** [comment] 2021-09-11 11:44
I saw the same error under PS 1.7.7.7. I don't know why Prestashop cannot reproduce it as it obvious  - as explained by FRaccie - that this can happen. imap_errors() is defined to return boolean false when nothing found and that results in this error. 

Did the Prestashop team test in a situation where this code was accessed and where imap_errors didn't return any faults?

Note that the image shows also another error: $overview->date is not defined. This was caused by a spam mail that indeed didn't have a date field.

In the process I found also another problem: the mail on the server is not deleted by the Imap process.
![imap](https://user-images.githubusercontent.com/13930107/132946776-55d5639d-372c-4f38-a4de-997dc27c67cb.jpg)

**Comment by musicpanda** [comment] 2021-09-11 12:12
Note that the fact that the emails are not deleted resulted in a situation where every time the Customers messages page was opened the headers for all 9000 mails that were in this account were downloaded from the mailserver.

**Comment by kpodemski** [comment] 2021-09-11 13:04
Hello @musicpanda 

I've fixed this first warning. For the second problem, could you copy your message to a separate issue? It seems that we have to investigate and test this page more thoroughly. Thank you very much for your help on this one.
