### ISSUE TITLE
Customer Address Form sometimes renders incorrectly when the 'set default country from browser' option is enabled

### ISSUE THREAD

**Issue by yo7hli** [PrestaShop/PrestaShop#29433] opened 2022-08-24 23:02 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the 'set default country from browser' option is enabled and you want to add or edit a customer address with a different country, the browser's country overwrites the user selected country or the one saved on file, resulting in incorrect rendering of the states field and possibly others related to the country.

This scenario is pretty common since many users from different countries have their OS or browser language/country set to US.

Behaviour was introduced by this [commit](https://github.com/PrestaShop/PrestaShop/commit/27b1c5f484cd71cdcf7a2d4b484d32f1c7708bc8) ,so it doesn't manifest itself in  versions < 8.0

### Expected behavior

If the saved address that needs to be edited already has a country set, or if the address controller is called with a id_country param, these shoud take precedence over the one detected from the browser.

### Steps to reproduce

1. have a customer account on the frontend
1. Enable the option 'set default country from browser' in BOInternational/Localization
2. Set your default browser language to en-US (e.g. in firefox go to settings/preferences/language and select English(United States))
3. Make sure the State:name field exists in the address format for U.S. in BO:International/Localization/Countries
4. Go to the customer account/addresses/add new address
5. Select another country than the one detected(United States)
6. Now check the states select field, it still renders the U.S. States, regardless of wether the new country has states or not.

Something similar happens if you try to edit an address having another country on file.

### PrestaShop version(s) where the bug happened

8.0.0 beta

### PHP version(s) where the bug happened

7.4

**Comment by yo7hli** [comment] 2022-08-24 23:23
related to [#28781](https://github.com/PrestaShop/PrestaShop/issues/28781) and [#29012](https://github.com/PrestaShop/PrestaShop/issues/29012) which I didn't find on a first quick search but since the fix is not yet merged, i'll leave it open

**Comment by hibatallahAouadni** [comment] 2022-08-25 18:22
Hello @yo7hli 

Thanks for reporting the issue!
But as you mentioned your issue is a duplicate of #28781 and #29012

As we are aware of this issue and it is already in our debug backlog, I close yours as a duplicate. 

To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: both issues are fixed by this PR #29122

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-25 18:23
Duplicate of #28781

**Closed as completed** 2022-08-25 18:23 UTC
Labels: Bug, Duplicate, Invalid

**Comment by cdigruttola** [comment] 2023-08-05 14:43
Hi,
I'm using the branch 8.1.x in my local environment and the problem seems to happens in My Account -> Addresses.

My configuration:
PrestaShop version: 8.1.1
PHP version: 7.4
Countries: IT and UK
Request Header: Accept-Language: en-GB,en;q=0.9,it-IT;q=0.8,it;q=0.7,en-US;q=0.6

To avoid the problem is switched off the PS_DETECT_COUNTRY config.

After some debug, I found out that in the AddressController the first call to loadAddressById works fine, but when the system calls again the filleWith method https://github.com/PrestaShop/PrestaShop/blob/ed15b32588a32fbd40186cdedb6cad61aa4f5064/controllers/front/AddressController.php#L69 the id_country in $params is not set, so the browser header will be used and the format it isn't correct.
