### ISSUE TITLE
Null Values for Decimal Fields in layered_price_index

### ISSUE THREAD

**Issue by melriksdesign** [PrestaShop/PrestaShop#19119] opened 2020-05-13 22:25 UTC
After I updated the faceted search module this error still persisted.  This fixed it.

Symptoms --------------------------
- I couldn't add combinations or save other product edits when products had combinations.
- I received the red "couldn't save" error notification.

Debug Error ------------------------
The sql error was this 
***************************
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' , 21) ON D' at line 5
INSERT INTO `ps_layered_price_index` (id_product, id_currency, id_shop, price_min, price_max, id_country)
                     VALUES (979,
                        1,
                        2,
                        ,
                        ,
                        21)
                     ON DUPLICATE KEY UPDATE id_product = id_product

Core Problem ----------------
The problem was the layered_price_index table has two decimal fields that are required.  In our shop, those fields weren't populating to a decimal (I'm not sure why).  You'll see in the sql dump that price_min, price_max were null values.

1.7.6\modules\ps_facetedsearch\ps_facetedsearch.php Line 553

The fix -------------------
I fixed it by adding additional if statements for null values.
if (is_null($minPriceValue)) { $minPriceValue == '0.00'; }
if (is_null($maxPriceValue)) { $maxPriceValue == '0.00'; }

**Comment by florine2623** [comment] 2020-05-14 09:02
Hi @melriksdesign ,

I'm using v3.5.0 of module Faceted Search and PS 1.7.6.5/ PS 1.7.7.0 and can't reproduce your issue. I can save products with combinations.
Glad to hear that you could fix it manually.
You might have had some overrides. You could check by disabling the overrides and try to save again your products with combinations.

As you succeeded in fixing your issue, I will close it.
Feel free to open a new one if needed !
Thanks!

**Closed as completed by florine2623** 2020-05-14 09:02 UTC
Labels: BO, Faceted search, No change required, 1.7.6.5

**Comment by strangegitter** [comment] 2020-07-29 20:27
This error can be reproduced by saving a product in a system that has 2 shops and the product is only on one of the shops.  In Prestashop Version 1.7.6.7 / ps_facetedsearch Version 3.5.0 on line 441 of ps_facetedsearch $price = Product::priceCalculation(.........  brings back nothing because you cannot calculate a price on a product that does not exist in that store.
