### ISSUE TITLE
dashtrends considers the amount without discount

### ISSUE THREAD

**Issue by corsik** [PrestaShop/PrestaShop#10114] opened 2018-08-24 09:19 UTC
dashtrends considers the amount without discount

**Comment by khouloudbelguith** [comment] 2018-08-24 09:28
Hi @corsik 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9983
So, I close it.
Thanks!

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-08-24 09:28 UTC
Labels: Bug, Duplicate, 1.7.4.2
