### ISSUE TITLE
Can't send e-mail because of incomplete SMTP configuration form

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/PrestaShop#21108] opened 2020-09-22 17:15 UTC
#### Describe the bug

Can't define e-mail sender address and e-mail sender name.

#### Expected behavior

To allow to authenticate to mail server sometimes we must define e-mail sender address. It's good if we define e-mail sender name. It's common practice nowadays.

#### Steps to Reproduce

1. Go to admin dashboard
2. Login
3. Go to Advanced, E-mail settings
4. Choose own SMTP settings
5. Can't set correct settings because of incomplete setting form.

**Screenshots**

![image](https://user-images.githubusercontent.com/42643563/93915132-d64a1880-fd07-11ea-9aa0-826145732145.png)
![image](https://user-images.githubusercontent.com/42643563/93915141-db0ecc80-fd07-11ea-922f-abfe7dec3cc2.png)

#### Additional information

* PrestaShop version: all
* PHP version: all

**Comment by sarahdib** [comment] 2020-09-23 07:29
Hello @LocalHeroPro 

Those information are define in shop parameter -> Contact -> Shop.

I close this issue, feel free to open a new one if the problem is not solved.

Thank you

**Closed as completed by sarahdib** 2020-09-23 07:29 UTC
Labels: No change required

**Comment by LocalHeroPro** [comment] 2020-09-23 16:11
They paying for you for closing unresolved issues?

**Comment by matks** [comment] 2020-09-24 16:00
Hi @LocalHeroPro ,

If I understand correctly the issue, you are saying that it would be nice to add a "sender name" field into the form. Is that right ?

If I got it right, this is not a bug, it's a feature request. A bug report indicates something that does not work as expected. The current form is working as expected, what you suggest is to expand it.

Please however understand that statement like

> They paying for you for closing unresolved issues?

Are considered quite rude and aggressive and consequently we are very unlikely to welcome them. As mentioned in our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md), we request of everybody here (be it prestashop team members or contributors) to
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members

We can work together on this feature request if we all use the right language and show empathy toward each other 😉

**Comment by jolelievre** [comment] 2020-09-24 16:30
Hi @LocalHeroPro,

I'm not sure I understand your problem? 🤔
You're talking about sender email and name, but these infos are dynamic and depend on the context and especially who is sending the mail.

If you look at the `Mail::send` function you'll see that you can provide `$from` (email from) and `$fromName` (email name). I think this is what you are looking for. The from email/name don't have to be set on the Shop global configuration.

When mails are sent by the shop, they are usually configured with the appropriate sender, either the Employee logged in the BO that performed the related action. When these parameters are not defined the `Mail::send` methods uses some configuration values as default fallback, in your case `PS_SHOP_EMAIL` and `PS_SHOP_NAME`

These two parameters can be configured in the BO in Shop Parameters > Contact > Store (as @sarahdib already explained).

So I think you should be good with all these informations, but indeed I don't see a bug here so this issue has no reason. Unless you can provide more details on the problem you're encountering which would be related to another problem.

**Comment by fabienlege** [comment] 2021-02-23 14:30
The problem is, sometime, you want to send email with different email address than store contact.
In my case, I want to use contact@myshop.com in shop address (to show it in contact page) but I want to send my transactionnal emails with no-reply@maildomain.com.

My SMTP provider (mailjet, for exemple. but many smtp provider work as it) deny any outgoing mail if from address isn't exactly no-reply@maildomain.com). In SMTP configuration, you allow to set "domain name" (i don't undertant what this parameter do) but not to set from address... it's a realy blocking issue for mailing of many website
