### ISSUE TITLE
Activity overview with PHP >=8

### ISSUE THREAD

**Issue by thecyberman1024** [PrestaShop/PrestaShop#34513] opened 2023-11-09 17:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I upgrade my hosting's PHP version to 8 or higher, the module dashactivity v2.1.0 stops working, and instead of the normal values (listed below), I get a loading indicator spinning indefinitely. When I switch back to PHP 7.4, everything works again.

### Expected behavior

Have the values instead of loading indicator.

### Steps to reproduce

1. upgrade PHP version to version 8.0 or higher
2. go to the dashboard and see the indicator spinning infinitely
3. ![php 8](https://github.com/PrestaShop/PrestaShop/assets/6449955/e5f3fc3b-a06b-4f00-9172-420ea4c92ddc)
4. downgrade PHP to 7.4
5. everything is fine again
![php 7 4](https://github.com/PrestaShop/PrestaShop/assets/6449955/05ea8fae-9ce9-4a05-bc3f-b054018ee451)

### PrestaShop version(s) where the bug happened

8.1.0 8.1.1 8.1.2

### PHP version(s) where the bug happened

8.0 8.1 8.2

### If your bug is related to a module, specify its name and its version

dashactivity v2.1.0

### Your company or customer's name goes here (if applicable).

Maëlicia

**Comment by 3DPTronics** [comment] 2023-11-09 20:50
Same issue here. Downgrading php to 7.4 works 
PS 8.1.2

**Comment by ShaiMagal** [comment] 2023-11-11 09:59
PS 8.1.2
PHP 8.2.12
dashactivity 2.1.0
 -> no problem here for me

**Comment by florine2623** [comment] 2023-11-13 08:52
Hello @thecyberman1024 ,

I can't reproduce your issue.


https://github.com/PrestaShop/PrestaShop/assets/16019289/3fec3fed-d90c-4683-95be-7b18fd5fb4ff



We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by thecyberman1024** [comment] 2023-11-13 08:58
> Hello @thecyberman1024 ,
> 
> I can't reproduce your issue.
> 
>  Screen.Recording.2023-11-13.at.09.51.06.mov 
> We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).
> 
> Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
> 
> Thank you

Don't you think that just because it works on a server doesn't mean it can't be a bug? While at least one other person has validated the problem?

**Comment by ShaiMagal** [comment] 2023-11-13 11:55
@thecyberman1024 One person confirmed (3DPTronics) and one person unconfirmed this (me) - I tested without problem (2 days ago).

So, 2:2....

Be kind and provide @florine2623 more informations, she needs step by step how to reproduce to confirm it's bug.
I don't see any problem, I tested 3 instances of PrestaShop without problems on your setup (php/prestashop/dashactivity).

**Isn't any error in javascript console for example?**

Try press F12 and check javascript console for errors first. Maybe there will be answer for this problem.

**Comment by thecyberman1024** [comment] 2023-11-13 13:45
@ShaiMagal Unfortunately I don't have any error il javascript console...
And i have the same problem on my computer and mobile.

**Comment by ShaiMagal** [comment] 2023-11-13 15:23
@thecyberman1024 check php error log.

**Comment by florine2623** [comment] 2023-11-29 15:33
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-11-29 15:33 UTC
Labels: Bug

**Comment by thecyberman1024** [comment] 2024-04-13 15:43
the last update 2.1.1 fixed the problem !

**Comment by 3DPTronics** [comment] 2024-05-16 14:35
Don't know why, but resetting Product Comments module fixed the issue! 

![2024-05-16_16h33_11](https://github.com/PrestaShop/PrestaShop/assets/109287233/4177ab2b-2d80-41ef-acec-f229509ac984)


PS v8.1.6
PHP v8.3ea
DashActivity v2.1.1
