### ISSUE TITLE
ps_facetedsearch - texture and color - empty  

### ISSUE THREAD

**Issue by jasinskipr** [PrestaShop/PrestaShop#18175] opened 2020-03-17 09:55 UTC
presta 1.7.6.4
ps_facetedsearch v3.4.1

I used the command {$displayedFacets|@print_r} in the file "facets.tpl".
I have empty array like in picture. 

![presta](https://user-images.githubusercontent.com/62284805/76844245-4f3e5400-683d-11ea-9f60-0741875a815c.png)

I want to get a color or texture.

**Comment by khouloudbelguith** [comment] 2020-03-17 11:13
Hi @jasinskipr,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.4 and PS1.7.5.2 using the ps_facetedsearch module v3.4.1.
I have an empty `array` for properties
![image](https://user-images.githubusercontent.com/16067358/76850867-8b2ae680-6848-11ea-8238-6671ad3811db.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Ping @PierreRambaud what do you think?

Thanks!

**Comment by PierreRambaud** [comment] 2020-12-01 15:06
I did not manage to reproduce the issue.
![image](https://user-images.githubusercontent.com/1462701/100757813-1a842400-33ef-11eb-92b5-6f72610ba6b4.png)

@khouloudbelguith Color and texture are only available on attributes, not for categories

**Comment by PierreRambaud** [comment] 2020-12-28 16:04
I'm closing this one, it's not a bug.

**Closed as completed by PierreRambaud** 2020-12-28 16:04 UTC
Labels: Bug, Minor, CO, Faceted search, No change required, 1.7.5.2, 1.7.6.4
