### ISSUE TITLE
Update translations not working

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#17610] opened 2020-02-12 04:25 UTC
I installed Prestashop with french translations but my customers are receiving emails in english.
When I check in `International > Translations > Edit translations` I can see that french translations for emails are not fully translated in french.

So I did  `International > Translations > Add / Update a language > Update french`.
But translations are still partially in english.

PrestaShop version:  1.7.6.1 (upgraded from a previous 1.7.* version)

![image](https://user-images.githubusercontent.com/915273/74303154-65af4680-4d8b-11ea-8855-777072cc0ffa.png)

**Comment by khouloudbelguith** [comment] 2020-02-12 08:38
Hi @Seb33300,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16294 to fix the issue.
It is fixed in PS1.7.6.3
Your ticket is a duplicate of #16273
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-12 08:38
Duplicate of #16273

**Closed as completed by khouloudbelguith** 2020-02-12 08:38 UTC
Labels: Duplicate
