### ISSUE TITLE
Cant activate / deactivate my products on Prestashop 1.7.5

### ISSUE THREAD

**Issue by CBSMarty** [PrestaShop/PrestaShop#16445] opened 2019-11-16 17:53 UTC
Hi, 
All of a sudden, without any (known) major changes or modules added to the site, my site stopped letting me activate / deactivate my products..

When I click on the button, site starts loading and ends up with what looks to me as a timeout.. 
I dont have a lot of products, the site is only on its testing fase.. and it has never been an issue before?

![image](https://user-images.githubusercontent.com/57841996/68997015-e8fef000-08a1-11ea-9d14-87e73edf0727.png)

I run PS in debug mode, but it doesn't really give me any relevant result regarding this issue.. 
Or at least i dont see how this could be related or fixed.. 

Any ideas.. 
Thanks!

**Comment by CBSMarty** [comment] 2019-11-17 15:22
I figured out some more: 
I Get this error ....

VM350:1 Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (form.js?1.7.5.1:703)
    at u (main.bundle.js:313)
    at Object.fireWith [as rejectWith] (main.bundle.js:313)
    at i (main.bundle.js:313)
    at XMLHttpRequest.<anonymous> (main.bundle.js:313)


Help anyone?

**Comment by khouloudbelguith** [comment] 2019-11-18 09:45
Hi @CBSMarty,

You need to enable debug mode in your store and debug request which is sent for product enable/disable action in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. enable/disable product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by CBSMarty** [comment] 2019-11-18 09:53
Hello, yes.. 

That got me here: 

![image](https://user-images.githubusercontent.com/57841996/69042461-8157ba80-09f1-11ea-8859-ee843faeb2e1.png)

But that corresponds to what i already sent .. :/ i have no idea what to do

**Comment by khouloudbelguith** [comment] 2019-11-18 09:56
@CBSMarty, now click on it, you should see the error message in "Response" or "Preview" tab.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-18 09:58
@khouloudbelguith  nothing shows up.

![image](https://user-images.githubusercontent.com/57841996/69042965-66d21100-09f2-11ea-96b9-ad9746ad6aa3.png)

**Comment by khouloudbelguith** [comment] 2019-11-18 10:02
@CBSMarty, debug mode is enabled?

Thanks!

**Comment by CBSMarty** [comment] 2019-11-18 10:03
@khouloudbelguith  Yes, yes it is..

**Comment by khouloudbelguith** [comment] 2019-11-18 10:05
@CBSMarty, thanks to provide me your log file.
You can find it in this path `Project_Folder/var/logs`.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-18 10:09
@khouloudbelguith the dev.log file?

**Comment by khouloudbelguith** [comment] 2019-11-18 10:10
@CBSMarty, yes!

Thanks!

**Comment by CBSMarty** [comment] 2019-11-18 10:11
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3858064/dev.log)

**Comment by CBSMarty** [comment] 2019-11-18 10:27
@khouloudbelguith  any ideas... ?
Im starting to get desperate... I really cant understand what changed and made my products stop working..

**Comment by CBSMarty** [comment] 2019-11-18 10:32
this is the only thing that shows on my debug:

![image](https://user-images.githubusercontent.com/57841996/69045457-29bc4d80-09f7-11ea-8f5f-9031d8f6f41b.png)

**Comment by khouloudbelguith** [comment] 2019-11-18 11:23
@CBSMarty, you have this error:
`php.CRITICAL: Fatal Error: Allowed memory size of 536870912`
In your php.ini file, Try to increase:

```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```
Thanks to check & feedback

**Comment by CBSMarty** [comment] 2019-11-18 11:29
@khouloudbelguith where do i find that?

**Comment by khouloudbelguith** [comment] 2019-11-18 11:30
@CBSMarty, this is a configuration in your server.
If you don't have access, you need to contact your host.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-18 11:33
@khouloudbelguith i have access to all my files, but my init.php doesnt look like that, looks like this.

![image](https://user-images.githubusercontent.com/57841996/69049226-abb07480-09ff-11ea-8f4c-dca04a8b53aa.png)

**Comment by khouloudbelguith** [comment] 2019-11-18 12:34
@CBSMarty, no it is not a PrestaShop file.
Thanks to follow this link: https://www.php.net/manual/en/configuration.file.php

**Comment by CBSMarty** [comment] 2019-11-18 17:20
@khouloudbelguith  Hi, i have been trying to figure this out all day.. 
Now im currently waiting for my host provider to upgrade my service, hopefully this helps.

And I noticed my prestashop is not up to date either. So i will try to update my version after my host has been upgraded.

**Comment by khouloudbelguith** [comment] 2019-11-19 08:31
@CBSMarty, thanks, waiting for your feedback.

PS: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 09:35
Hi @khouloudbelguith  

I set my php version to 7.2. However im tryng to update my store via the 1-click upgrade but gives me an error... I can see more people have the same issue with this: 
[Ajax / Server Error for action unzip] textStatus: "error " errorThrown:" " jqXHR: " "

**Comment by khouloudbelguith** [comment] 2019-11-20 09:44
@CBSMarty, what is the exact version of 1-click upgrade did you use?

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 09:47
@khouloudbelguith  v4.9.0

**Comment by khouloudbelguith** [comment] 2019-11-20 09:50
@CBSMarty, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 09:52
@khouloudbelguith 
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3868494/log.txt)

**Comment by khouloudbelguith** [comment] 2019-11-20 10:00
@CBSMarty, there is no error in this log file, the upgrade just stopped.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 10:10
Hi, i read the article but doesnt quite help me.. 

In my files i cant find any log regarding php.

![image](https://user-images.githubusercontent.com/57841996/69229769-5d79ad80-0b86-11ea-8fa6-5a57b823929a.png)

And my debug mode doesnt show on the 1-click upgrade page

**Comment by khouloudbelguith** [comment] 2019-11-20 10:13
@CBSMarty, your log file is available in this path `Project_Folder/var/logs/`.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 10:16
@khouloudbelguith  is it this one? 
[dev.log](https://github.com/PrestaShop/PrestaShop/files/3868622/dev.log)

**Comment by CBSMarty** [comment] 2019-11-20 10:19
@khouloudbelguith  here i can see it timesout: 

https://gyazo.com/045e4df739c2ad29bce0503f842ddac8

**Comment by khouloudbelguith** [comment] 2019-11-20 10:26
@CBSMarty, you have this error
`php.DEBUG: Warning: set_time_limit(): Cannot set max execution time limit due to system policy {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/customers/9/f/8/cbsracingshop.com/httpd.www/modules/autoupgrade/AdminSelfUpgrade.php`
It is a server issue, you need to forward this error to your host.
I think that you don't have permission to change the settings for "set_time_limit()". This should be a PHP setting "php.ini"
Thanks to check your host & feedback.

**Comment by CBSMarty** [comment] 2019-11-20 10:29
@khouloudbelguith  Ill try that!
However I found this aswell , is this related?

![image](https://user-images.githubusercontent.com/57841996/69231282-1c36cd00-0b89-11ea-9c4c-4d1b893f747a.png)

**Comment by khouloudbelguith** [comment] 2019-11-20 10:35
@CBSMarty, the process of the upgrade is just stoped.
Thanks to check with your host & feedback.

**Comment by CBSMarty** [comment] 2019-11-20 10:48
@khouloudbelguith  they told i cant get access to my php.ini file and change it... 
But these are my settings...
Shouldnt it be enough?

PHP safe_mode   Off
PHP memory_limit    4 GB
PHP upload_max_filesize    96 MB
PHP post_max_size  96 MB
PHP max_execution_time 50 seconds
GD Graphics Library      On  
MySQL max_user_connections     40
MySQL max_allowed_packet   512MG

**Comment by CBSMarty** [comment] 2019-11-20 10:53
would you say its maybe better to upgrade prestashop manually instead?

Maybe this can fix all my other issues

**Comment by khouloudbelguith** [comment] 2019-11-20 10:54
@CBSMarty, thanks to provide me a screenshot from your BO => Advanced Parameters => Information page.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 10:56
@khouloudbelguith  https://gyazo.com/8f99d0009b7352dcb4fab6ecd29cf280

**Comment by khouloudbelguith** [comment] 2019-11-20 11:02
@CBSMarty, your PHP version is still PHP7.3.
![image](https://user-images.githubusercontent.com/16067358/69233626-86517100-0b8d-11ea-8c3e-a284eb8bddb3.png)

This is an incorrect, please downgrade your PHP version.
Also, your memory limit is defined without unity.

For example, check my configuration
![image](https://user-images.githubusercontent.com/16067358/69233666-9bc69b00-0b8d-11ea-9a1d-71dcd4700d11.png)

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 11:04
I changed my php version again now..

yes i know, thats what i told them, but didnt say anything about it

**Comment by khouloudbelguith** [comment] 2019-11-20 11:05
@CBSMarty, Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by CBSMarty** [comment] 2019-11-20 11:21
I cant login to see it...

**Comment by khouloudbelguith** [comment] 2019-11-20 11:23
@CBSMarty, the credentials are:

- `prestashop` 
- `prestashop`

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 11:25
yes, didnt work... my site completely broke now

**Comment by khouloudbelguith** [comment] 2019-11-20 11:36
@CBSMarty, it is just a phpinfo file equivalent to the phpinfo() function.
thanks to try with this file
[test.php.zip](https://github.com/PrestaShop/PrestaShop/files/3868968/test.php.zip)

I deleted the credential check.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 11:41
Hello, that worked... 

https://www.cbsracingshop.com/test.php

But my site now is totally broken...

**Comment by khouloudbelguith** [comment] 2019-11-20 11:45
@CBSMarty, try to remove the previous file phppsinfo.php & clear cache.
Also, as you can see now
![image](https://user-images.githubusercontent.com/16067358/69236250-6ae96480-0b93-11ea-855c-5c297faaa8b3.png)
Thanks to check `memory_limit` value with your host, there is no Unity & try to increase `post_max_size` & the `upload_max_filesize`.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 11:46
They wont let, they say its their server configuration

**Comment by khouloudbelguith** [comment] 2019-11-20 11:49
@CBSMarty, could you please provide me again the screenshot from the BO => Advanced Parameters => Information page.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 12:23
@khouloudbelguith  yes ofc.
https://gyazo.com/0e7e3865220c5ff2412d391687d0f184

**Comment by khouloudbelguith** [comment] 2019-11-20 13:09
@CBSMarty, thanks for your feedback.
As I said before
> Thanks to check `memory_limit` value with your host, there is no Unity & try to increase `post_max_size` & the `upload_max_filesize`.

This is the only solution for now because you have time out of the server & the upgrade process is stopped due to the memory_limit.

Thanks!

**Comment by CBSMarty** [comment] 2019-11-20 13:14
Yea, and they dont want to change it... 
So now im just backing up and deleting everything on my site.. And download a new version and start from the beginning again....

**Comment by khouloudbelguith** [comment] 2019-11-20 13:16
@CBSMarty, Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-20 13:16 UTC
Labels: Bug, BO, Can't reproduce, 1.7.5.2
