### ISSUE TITLE
White page on each translation pages

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15432] opened 2019-09-05 17:25 UTC
Hi
i think there are some javascript errors in a site with prestashop 1.7.6.0, it happens for each type of translation

I can give you the access to this site

bye

**Screenshots**
![11](https://user-images.githubusercontent.com/653230/64364149-989e2300-d012-11e9-8479-ef2f9ec53d15.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0

**Comment by Maofree** [comment] 2019-09-05 17:52
now where are the translations?
not in the translations folders of theme and of webroot

**Comment by Maofree** [comment] 2019-09-05 18:01
on my local server I can translate that site
so I want to upload these translations on the real site, but I cannot find where are saved them on 1.7.x

**Comment by khouloudbelguith** [comment] 2019-09-06 07:27
Hi @maofree,

With PS1.7.6.0, we have some regressions related to the translation.
They are fixed in the last release PS1.7.6.1.
You can find those issues in this [link](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ATranslations+milestone%3A1.7.6.1+is%3Aclosed)

Thanks to check & feedback.

**Comment by Maofree** [comment] 2019-09-06 07:41
hi
can you say me where are stored the translations now?

**Comment by khouloudbelguith** [comment] 2019-09-06 08:12
@maofree, the zip files are downloaded in the `folder/translations`, and then they are extracted and the XLF files they contain are exported to`app / Resources / translations`.

Thanks!

**Comment by Maofree** [comment] 2019-09-06 08:21
thanks

**Comment by khouloudbelguith** [comment] 2019-09-06 08:27
@maofree, you are welcome!
Any news about your issue.
Did you check the fixes in the PS1.7.6.1?

Thanks!

**Comment by Maofree** [comment] 2019-09-06 08:30
I think it is not due from prestashop version, because the clone of this site works well on my local server
I think it is due from other problems
the debug mode doesn't show anything, just a javascript error in the web tool of chrome, it happens only in this site

**Comment by khouloudbelguith** [comment] 2019-09-06 08:40
@maofree, We need to retrieve the PHP error log and the debug mode report(doesn't show anything in your case) in order to find out what's wrong.

Thanks!

**Comment by Maofree** [comment] 2019-09-06 10:04
![111](https://user-images.githubusercontent.com/653230/64419666-ad73c880-d09d-11e9-86f9-bf63de1aff9f.png)
this is a translation file inside a theme bought from Addons
the url inside these files are not of my pc or site's server but of the developer's server

**Comment by Maofree** [comment] 2019-09-06 10:06
I've seen inside app/Resources/translations/ShopThemeCustomeraccount.it-IT.xlf
the translations are ok but in the front office the translation is like the first one and I cannot change it again. Removed all files inside the cache, but nothing
I don't know where is that translation

**Comment by khouloudbelguith** [comment] 2019-09-06 10:33
@maofree, it could an issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15075?

Thanks to check & feedback.

**Comment by zodit** [comment] 2019-09-06 10:53
Hello, thank you for your explanation, also i have problems with transations (italian, both custom **Theme** and **Modules**) in PS 1.7.6.1. I confirm that my version is fixed, but still has some bugs.
I try to provide all details i can.

1. Theme translations from BO tool do not work properly, i translated over 250 strings, most are saved, but 6 of them are not... they display as missing everytime i reload the translation tool. 

These are the following:
ShopThemeActions: "back to login", "Edit"
ShopThemeCatalog: "Including %amount% for ecotax"
ShopThemeCheckout: "%products_count% items in your cart"
ShopThemeCustomeraccount: "Your package must be returned to us within %number% days of receiving your order.", "%number% on %date%"

I notice an anomaly: in the menu on the left side. After the "Shop" group there is a "it-I" group with sub group "T". I think this is a parsing error of the xlf files, eventualy it broke the string "it-IT".

2. As you suggested i checked the translations in **/app/Resources/translations/it-IT**. They seems ok, strings are not missing.

3. Before your suggestion I exported them using BO tool, and uploaded them in theme folder **/translations/it-IT/**, 13 files in total.  I used the translation tool again for the 6 missing strings, but nothing changed. I guess these files are not used or overrided either, date/time never changed. What is the use of the theme folder then?

4. Modules translation seems working in BO tool, i translated a module, all strings are ok, no missing ones this time. Anyway this is not working in FO, it is half translated (perhaps some common strings come from the Theme? The peculiar strings are not translated, for example: "You can try some popular tags here" is not translated). I have no cache, force rebuild, and i keep cleaning Smarty Cache.

5. As for the theme i searched where the xlf files are saved but i could not find them. The name of the module "ModulesRoyleviboxRoy" is not in the **/app/Resources/translations/it-IT**, the module folder **translations** does not have it.php file (not working as legacy), and it is not in theme folder **/translations/it-IT/**. Please, where is it?

**Comment by khouloudbelguith** [comment] 2019-09-06 11:22
@zodit, thanks for your feedback.
>Theme translations from BO tool do not work properly

When you search for the "back to login" / "Edit" expressions are not displayed?
![image](https://user-images.githubusercontent.com/16067358/64423571-c6c94480-d09e-11e9-849e-a611b9f36807.png)
In my case, are expressions are well displayed
https://drive.google.com/file/d/1S3lv_kVxszyom_dSc0-lqb0q5EwjjEw_/view

>Modules translation seems working in BO tool, i translated a module, all strings are ok, no missing ones this time. Anyway this is not working in FO

Could you please provide me an example of modules to check them.

**Comment by zodit** [comment] 2019-09-06 11:34
Here is my screenshot. You can see 6 missing strings (but not missing when i open the files in app/Resources/translations/it-IT). Also a weird "it-I" > "T" menu item.

![immagine](https://user-images.githubusercontent.com/5260044/64424820-60e2ba00-d0aa-11e9-9a3e-d2bd2e6d1a6e.png)

For the modules i show you. This is BO.

![immagine](https://user-images.githubusercontent.com/5260044/64424984-d8b0e480-d0aa-11e9-908d-baaa4dedf312.png)

And this is FO result.

![immagine](https://user-images.githubusercontent.com/5260044/64425036-0138de80-d0ab-11e9-9652-70657ccbd5f3.png)

**Comment by khouloudbelguith** [comment] 2019-09-06 11:45
@zodit, you are trying to translate a custom theme? isn't?
The translations in your thme should be like this 
![image](https://user-images.githubusercontent.com/16067358/64425517-d39c6700-d0a3-11e9-8353-713a980912c2.png)

About the module, did you tried to check the module translation in your theme translation?

Thanks!

**Comment by zodit** [comment] 2019-09-06 12:16
Yes, custom theme "modez" and custom module "roy levibox".
Strings in my theme are like this... 

![immagine](https://user-images.githubusercontent.com/5260044/64426319-870a5900-d0ae-11e9-9ad7-a18a765ecca6.png)


BO display that "Back to login" is missing, but it is not, as we can see in **app/Resources/translations/it-IT**, here the screenshot.

![immagine](https://user-images.githubusercontent.com/5260044/64426181-385cbf00-d0ae-11e9-9008-8a82bd7c129b.png)

I could be wrong, but don't you think it could be a BO "display" problem? Maybe a parsing error of xlf files? There is still that weird menu after "Shop".

About the module, this is it:

![immagine](https://user-images.githubusercontent.com/5260044/64427039-7fe44a80-d0b0-11e9-8a16-94c7b0df5b3a.png)

And in my theme folder i have this template:

![immagine](https://user-images.githubusercontent.com/5260044/64426527-0c8e0900-d0af-11e9-833e-9b6cae5d7952.png)

And this is the translations folder of my Theme (i uploaded these files manually, from exportation). There is no track of Levibox module or its strings. 

![immagine](https://user-images.githubusercontent.com/5260044/64426788-ceddb000-d0af-11e9-82bf-ea6f26b3e2d1.png)

Where else could be the xlf files?

**Comment by zodit** [comment] 2019-09-06 12:33
I found the trick finally.
BO translation for this module is ignored. It is working like old school, with MD5 strings in the module folder.
I added manually the "it.php" file and the specific string.

![immagine](https://user-images.githubusercontent.com/5260044/64427743-3432a080-d0b2-11e9-9ccc-d1aa2d7e400a.png)

This is the result in FO.

![immagine](https://user-images.githubusercontent.com/5260044/64427785-4c0a2480-d0b2-11e9-9fb6-4abafa2ef6f2.png)

So, do i need to translate the module this way? No way to make the BO translations work?

**Comment by khouloudbelguith** [comment] 2019-09-06 14:41
@zodit, Here's a PR: https://github.com/PrestaShop/PrestaShop/pull/14609 to fix this issue "Cannot translate existing module wordings for a specific theme" => it is your module translation issue.
@zodit, about the translation of your theme, it is a theme issue, you need to contact the theme author about this problem.
for example
I have this in my theme `<th>{l s='Date' d='Shop.Theme.Global}</th>` it is incorrect missing the '
![image](https://user-images.githubusercontent.com/16067358/64436526-71039500-d0bc-11e9-9d79-33cb09810fb1.png)
So => I will have this error
![image](https://user-images.githubusercontent.com/16067358/64436556-85479200-d0bc-11e9-9b4c-721f1977da1e.png)

Thanks!

**Comment by zodit** [comment] 2019-09-06 15:02
Thank you khouloudbelguith, i will check for errors in theme. About the module i managed to translate it.

**Comment by khouloudbelguith** [comment] 2019-09-06 15:04
@zodit, you are welcome!

Thanks!

**Comment by Maofree** [comment] 2019-09-11 00:44
hi
the my error has been solved upgrading to 1.7.6.1
bye

**Comment by khouloudbelguith** [comment] 2019-09-11 07:36
@maofree, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-11 07:36 UTC
Labels: Bug, Translations, No change required, 1.7.6.0
