### ISSUE TITLE
Performance issue when deleting products

### ISSUE THREAD

**Issue by lukaslau** [PrestaShop/PrestaShop#17271] opened 2020-01-21 12:41 UTC
Hello,

I have a shop with nearly 100k products and I had to delete almost half of it. What I saw was even deleting 10 products takes forever (30 seconds).

After some digging I found out that the main issue with performance comes from Product class cleanPositions function product field date_upd date update action.

Does it really have to update products date_upd field? 
Commenting out this date_upd update action I managed to improve product delete performance from **10 products per 30 seconds to 1000 products per 90 seconds**.

My shop is running on VPS, 2xCPU, 8gb RAM, so it's more than enough power to run a shop.

**Comment by khouloudbelguith** [comment] 2020-01-21 13:09
Hi @zapper,

Your ticket is a duplicate of #12907
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-21 13:10
Duplicate of #12907

**Closed as completed by khouloudbelguith** 2020-01-21 13:09 UTC
Labels: Duplicate, Performance
