### ISSUE TITLE
error in Symfony after upgrade to 1.7.4.2

### ISSUE THREAD

**Issue by nbexiga** [PrestaShop/PrestaShop#10313] opened 2018-09-06 13:16 UTC
Hi

Today i updated my prestashop from version  1.7.3.2 to version 1.7.4.2 , via the upgrae module . 

Everything went ok, i tested almost all the store , did purchases , emails received , etc  but i noticed when i go to the Shop Parameters -> General Option i got an error . I activated the debug mode , and the error that appear is this "Compile Error: Cannot redeclare class PrestaShopPaymentExceptionCore"

 

Kindly see the prinscreen atached with more detailed information with the error.

 

It seems until now that everything is working ok (the parts that i tested) , except the General Settings.

Can someone please help?

I have PHP 5.6 and FPM/FastCGI

P.S - because of this issue after upgrade i had to restore the server snapshoot for the step before upgrade. 

P.S.2 - I have the same error in other store that i have in the same server. I did the upgrade on both stores.

So i want now to see what is causing the error and then fix it after do the upgrade again.

Many thanks

Nuno

**Comment by khouloudbelguith** [comment] 2018-09-06 13:26
Hi @nbexiga,

Could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by nbexiga** [comment] 2018-09-06 13:30
Hi
Thanks for that detailed information.
I will do that. But how can I see after that what is the problem?
For what directory should I upload regarding my described error?

https://www.prestashop.com/forums/uploads/monthly_2018_09/errorongeneralsettings.JPG.207170fe50fce1d70497fa554e0f8b8a.JPG

https://www.prestashop.com/forums/uploads/monthly_2018_09/errorongeneralsettings2.JPG.e83156625ab63671cd4f7dc3b3119242.JPG

This links are the prinscreens of the error

Thanks

**Comment by khouloudbelguith** [comment] 2018-09-06 13:35
Hi @nbexiga,

It describes the PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
It helps you to get information about your server.

Thanks & best regards, Khouloud

**Comment by nbexiga** [comment] 2018-09-06 14:21
Hi
everything is green and ok except this

PHP Version | 5.6 | 7.1 | 5.6.37
-- | -- | -- | --


but....

There is other way instead of migrate to 7.1 ?

Other fix?

Because it would be very tricky to me to upgrade from 5.6 in prod.

It's a VPS and I have to install it myself .

It's not like a cpanel that it's possible only to change version..

I am running Running centos7

**Comment by khouloudbelguith** [comment] 2018-09-06 15:50
Hi @nbexiga,

What is the exact version of the 1-click upgrade did you used?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by nbexiga** [comment] 2018-09-06 21:00
Hi @khouloudbelguith 
Thanks for you reply, 
the version of 1-click upgrade is 4.1.1
Regarding the log, i did not take it because i needed to go to prod with no issues , so i restore the server snapshoot.
i will have to try again and get the log and more information for what to do after the upgrade in case of error again..
it happens with both stores that i have in the server.

**Comment by khouloudbelguith** [comment] 2018-09-07 10:31
Hi @nbexiga,

Thanks!
Waiting for your feedback.

Best regards, Khouloud

**Comment by nbexiga** [comment] 2018-09-07 11:13
@khouloudbelguith 
Hi 
i have updated again and have the same error.... 

how can i send you the log?
thanks

**Comment by khouloudbelguith** [comment] 2018-09-07 11:16
Hi @nbexiga,

Yes, can you please provide us the log of your upgrade? It can be found in the log.txt file, available in /autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by nbexiga** [comment] 2018-09-07 11:44
Hi
kindly see the log atached
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2360890/log.txt)

**Comment by nbexiga** [comment] 2018-09-07 13:29
@khouloudbelguith did you got the error?

**Comment by khouloudbelguith** [comment] 2018-09-07 16:00
Hi @nbexiga,

Sorry, but I did not manage to reproduce the issue with the 1-click upgrade module v4.1.1 (PS 1.7.3.2 => PS 1.7.4.2), there's no error in the General page after the upgrade.
@Quetzacoalt91 what do you think about this error?

Best regards, Khouloud

**Comment by nbexiga** [comment] 2018-09-08 10:38
Hi
good morning.. anybosy can help? ;)

**Comment by Quetzacoalt91** [comment] 2018-09-10 08:37
I guess there are some issues with the registered class. In general, finding and deleting the files `class_index.php` helps.

**Comment by nbexiga** [comment] 2018-09-10 08:56
HI
and i delete that file where? in what folder?

thanks
________________________________
De: Thomas N <notifications@github.com>
Enviado: 10 de setembro de 2018 08:37
Para: PrestaShop/PrestaShop
Cc: N Bexiga; Mention
Assunto: Re: [PrestaShop/PrestaShop] error in Symfony after upgrade to 1.7.4.2 (#10313)


I guess there are some issues with the registered class. In general, finding and deleting the files class_index.php helps.

**Comment by Quetzacoalt91** [comment] 2018-09-10 09:03
You can potentially find it in:
* cache/
* app/cache/dev
* app/cache/prod
* var/cache/dev
* var/cache/prod

**Comment by nbexiga** [comment] 2018-09-10 09:34
Hi
i did not found any class_index.php in
cache/
app/cache/dev
app/cache/prod

and i cannot locate the folder var ...
is in the root of the prestashop?

thanks

**Comment by khouloudbelguith** [comment] 2018-09-10 09:42
Hi @nbexiga,

Yes, the folder var/ is located into the Prestashop project folder.

Best regards, Khouloud

**Comment by nbexiga** [comment] 2018-09-10 10:06
i canot finde the var folder .... i locate all of them but not the var.. grrr :(:(

**Comment by Quetzacoalt91** [comment] 2018-09-10 10:14
That's probably because you roll-backed your shop. This folder is only available from PrestaShop 1.7.4.0. :)

**Comment by nbexiga** [comment] 2018-09-10 16:05
@Quetzacoalt91  Hi
 yes.. i had to rollback my install.
i will try do delete that files now when i do the upgrade again...
hope it will fix that ;)

**Comment by nbexiga** [comment] 2018-09-11 11:28
Hi
already tried , the only class_index.php was on app/cache/dev and deleted it , but the issue persist ;(;(

don't know more what to do ;(;(;

**Comment by nbexiga** [comment] 2018-09-11 11:32
@Quetzacoalt91 

Symfony\Component\Debug\Exception\FatalErrorException:
Compile Error: Cannot redeclare class PrestaShopPaymentExceptionCore

  at classes/exception/PrestaShopPaymentException.php:0

**Comment by nbexiga** [comment] 2018-09-11 12:04
i am using 1-click upgrade module v4.1.1

**Comment by nbexiga** [comment] 2018-09-13 16:31
@Quetzacoalt91 
hi i updated the 1 click to new version 4.2.0 but the same issue persist... :(:(
can you help pleasE?
thanks

**Comment by khouloudbelguith** [comment] 2019-02-11 13:32
Hi @nbexiga,

We released a new version for the module 1-click upgrade v4.5.1.
Have you the same issue as before?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-12 09:39
Hi @nbexiga,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-12 09:39 UTC
Labels: Autoupgrade, No change required, 1.7.4.2
