### ISSUE TITLE
Problems seeing details order

### ISSUE THREAD

**Issue by fustereta** [PrestaShop/PrestaShop#28440] opened 2022-05-06 15:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When listing the orders in our backend and we press the magnifying glass the page breaks as follows (please find screenshort attached). The same issue happens if we press on the reference number and payment type.
When we click on the clients name we can see the clients profile, orders made and contact details but we can't see any order details (not even from the clients history).

![order](https://user-images.githubusercontent.com/4046113/167168359-8c88ab48-8a48-42e1-8a77-9684ca7bf3a1.jpg)

### Expected behavior

We expect to see the details of an order when clicking on the links mentioned above, as it happens in Prestashop.

### Steps to reproduce

1. Go to 'Pedidos'
2. Press any of the orders listed here, over reference number, payment type or magnifying glass.
3. The page breaks with an error

![order](https://user-images.githubusercontent.com/4046113/167168546-754c7ef7-80e7-40c5-bcf2-8cd186ee4874.jpg)

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment] 2022-05-06 16:46
Hello @fustereta,

I didn't manage to reproduce the isue with PS1.7.8.2 and PHP 7.4.


https://user-images.githubusercontent.com/89604350/167387238-fe478c6a-f008-4e74-a8cc-2a63dabc87f4.mp4



Did I miss some thing?

Thanks,

**Comment by fustereta** [comment] 2022-05-07 07:19
Hi @marwachelly,

And thanks for your reply, but I don't really get what's on the video.
In our Prestashop, when we go to the orders menu (in the left hand side) and press orders to list them, then when we want to see any details of an order (except the clients) that's when the site breaks.

The Prestashop was migrated from version 1.7.2.4 and it seemed there was no problems at all until this happened.

We don't know how to fix it.
Carme.

**Comment by marwachelly** [comment] 2022-05-09 10:04
> 

Hello @fustereta,

Sorry. I attached a wrong video :confused: . I Updated my comment with the right one.
Sorry again :smiling_face_with_tear: 

Did I miss some thing?

Waiting for your feedback.
Thanks

**Comment by fustereta** [comment] 2022-05-12 21:15
Thanks @marwachelly ,

That's exactly what we would like to get, but since we migrated Prestashop 1.7.2.4 to version 1.7.8.2 these links break and we don't know why. We thought about a module that has been uninstalled but these orders are from the new version and they have nothing to do with the old Prestashop.

Do you have any idea? :'(

Regards,
carme.

**Comment by leemyongpakvn** [comment] 2022-05-15 13:33
@marwachelly @fustereta It looks like the problem was described more clearly and solved at issue #22215

**Comment by hibatallahAouadni** [comment] 2022-05-16 17:11
Hello @fustereta 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

PS: thanks @leemyongpakvn for your quick reply :rocket: 

Thanks!

**Closed as completed by hibatallahAouadni** 2022-05-16 17:11 UTC
Labels: Bug, BO, Order, Invalid

**Comment by fustereta** [comment] 2022-05-16 17:53
Hi,
Thank you all for your time.
Thanks @leemyongpakvn for you comment. We think it's a similar problem but not sure if it's the same.

We've been trying to find out what module is giving us problems, @hibatallahAouadni, and we couldn't find it. That's why we posted the issue here. Thanks anyway.

If anyone needs credentials to see what we are explaining, more than welcome. It's pretty difficult to explain the issue by text.

Regards,
Carme.

**Comment by leemyongpakvn** [comment] 2022-05-17 00:39
@fustereta I'm quite sure that is the same problem, it is not a module bug, but in fact a mismatch between **old** order data (PS 1.7.2 allows NULL value in phone, product_isbn, etc fields) and **new** order data (PS 1.7.8 does not allow that NULL), so we need SET phone, product_isbn, etc to EMPTY string "" if they are NULL after upgrade. There is no problem with NEW order created after upgrade because their data match with PS 1.7.8 rule.
Just need backup your database, then follow what [DelosTR](https://github.com/DelosTR) commented [on Dec 21, 2020](https://github.com/PrestaShop/PrestaShop/issues/22215#issuecomment-748894921).

**Comment by fustereta** [comment] 2022-05-17 18:12
Thanks @leemyongpakvn for your reply and solution.

It seems we have it sorted out. It was related to the online TPV module. If we had it unpublished, then we could access the orders and with the module published the order details page broke the backend. So we finally found out the problem.

Thanks again to everyone who replied our issue. Really appreciated.

Regards,
carme.
