### ISSUE TITLE
Postcode validation in address must not consider non-significant spaces

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#25848] opened 2021-09-11 08:37 UTC
#### Describe the bug

When you enter a postal code in the compilation of an address, any space character before or after the string is being considered in the validation , resulting in a "Invalid postcode" error message.

This could be a common mistake for customers with browser address autocompletion or during copy-paste, 
since I got several report of customers who did not notice this over time , reporting then a "techincal problem".

#### Expected behavior

Postcode should be "trimmed" of starting / trailing spaces before being validated

#### Steps to Reproduce

Try adding a new Italy address with a postcode "12345 " or " 12345" (make sure to enter a space at the beginning or end),
you'll get the _Invalid postcode - should look like "NNNNN"_ message. , altough the postcode is valid.

**Screenshots**

![2021-09-11_10-17-47](https://user-images.githubusercontent.com/43071148/132941712-4c42a227-016a-4920-86b9-9f14a0176fb4.png)

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-09-13 15:24
Hello @gennaris 

This is the expected behavior because the space is a specific character.
I close this issue as it's not a bug.

Thanks for understanding.

**Closed as completed by hibatallahAouadni** 2021-09-13 15:24 UTC
Labels: No change required
