### ISSUE TITLE
filterCategoryContent hook not working

### ISSUE THREAD

**Issue by Nonoland** [PrestaShop/PrestaShop#27487] opened 2022-01-27 12:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Using the filterCategoryContent hook causes an error as the hook is misconfigured in the controller.

### Steps to reproduce

1. Create module with filterCategoryContent hook.

2. Modifiy $params['object']['description'] for instance.

3. Show: Type error: Argument 3 passed to HookCore::callHookOn() must be of the type array, string given.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-01-27 15:45
Hello @Nonoland 

Could you please provide a basic module contains this hook, to help me reproducing the issue :pray: 
Waiting for your feedback.

Thanks in advance!

**Comment by PrestaEdit** [comment] 2022-01-29 11:53
Hi @Nonoland ,

I'm not able to reproduce with this quick example:

```
public function hookFilterCategoryContent($params)
    {
        $params['object']['description'] = 'PrestaShop Issue';

        return $params;
    }
```

**Comment by Nonoland** [comment] 2022-02-04 22:52
Hi @PrestaEdit ,

This is the error I get when the hook runs :

```
public function hookFilterCategoryContent($params)
{
	$page_name = 'category';
	if (isset($params['object']['description']) && !empty($params['object']['description'])) {
		$params['object']['description'] = $this->getFilterContent($page_name, $params['object']['description']);
	}
	return $params;
}
```

![Capture d’écran 2022-02-04 à 23 43 03](https://user-images.githubusercontent.com/17767908/152613171-72e51bda-7352-4b2b-ae05-3110c16336cb.png)

And I noticed that in CategoryController, the hook was not configured to dispatch an array.

**Comment by florine2623** [comment] 2022-02-09 13:09
Hello @Nonoland ,

Thanks for the detail, did you have the time to check @hibatallahAouadni 's comment : 
>Could you please provide a basic module contains this hook, to help me reproducing the issue 🙏

It would be helpful to have a module to reproduce the issue.
Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-02 00:51
Hello @Nonoland 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-03-02 00:51 UTC
Labels: Bug, CO, Modules, PR available, Hook, Invalid

**Comment by dominservice** [comment] 2022-08-16 09:32
Hello, I have the same problem on version 1.7.8.7, according to the information in the message, it is about the litespeed module. From the comments above, it can be seen that this error arises with different modules not related to each other in any way

**Comment by kpodemski** [comment] 2022-08-16 11:20
Hello @dominservice 

You need to follow the changes from this PR:
https://github.com/PrestaShop/productcomments/pull/137

**Comment by KForge-Web-Solutions** [comment] 2023-06-16 10:20
Hi, I have the same problem with prestashop 8.0.4 and it's not related to Litespeed module that i do not have on my system.
the module that throw the exception has the method like:
```
public function hookFilterCategoryContent($params)
{
	$page_name = 'category';
	if (isset($params['object']['description']) && !empty($params['object']['description'])) {
		$params['object']['description'] = $this->getFilterContent($page_name, $params['object']['description']);
	}
	return $params;
}
```
As far i can see the hook on category controller is called with $chain = true

```
$filteredCategory = Hook::exec( 
            'filterCategoryContent',
            ['object' => $categoryVar],
            $id_module = null,
            $array_return = false,
            $check_exceptions = true,
            $use_push = false,
            $id_shop = null,
            $chain = true
        );
```
With this type of arguments the `$display = Hook::callHookOn($moduleInstance, $registeredHookName, $hook_args);`
will thrown an exception because the $hook_args will never be an array (as requested form the method callHookOn definition), in fact i can see the follow:

```
if (0 !== $key && true === $chain) {
     $hook_args = $output;
 }
```
so $hook_args = $output;
$output is defined as `$output = ($array_return) ? [] : '';` so it's '' because 
$array_return is defined as
```
// $chain & $array_return are incompatible so if chained is set to true, we disable the array_return option
if (true === $chain) {
    $array_return = false;
}
```
Am I wrong?
Regards

**Comment by fire2** [comment] 2023-07-24 22:57
@KForge-Web-Solutions I just stumbled upon the same doing debugging. I don't understand how this can ever work when `$chain == true`

**Comment by thomasDelaporte** [comment] 2025-04-30 08:36
Hey, I've just had the same problem; in case anyone comes across this ticket, in my case the problem was due to the fact that I still had a module in my “ps_module”/“ps_module_shop” tables that was hooked but no longer existed in the files so my real module was counted as number 2 (index 1) and blocked by this code:

```
if (0 !== $key && true === $chain) {
     $hook_args = $output;
}
```

If you feel like debugging, I've put this after the previous code to check : 

```
if ($registeredHookName == 'filterCategoryContent') {
     dump($module_list);
     dump($key);
}
```
