### ISSUE TITLE
Product price calculation, $specific_price output not converted when price is cached.

### ISSUE THREAD

**Issue by Perfecticus** [PrestaShop/PrestaShop#36364] opened 2024-06-14 11:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Scenario:

Product with specific price in undefined currency (0).
Customer with non-default currency.

The first time the price is looked up, the correct info is populated in $specific_price.
The second time ($_prices cache is populated for $cache_id), the $price returned is correct, but the $specific_price data is not converted to customer currency.

The conversion of $specific_price.price and reduction occurs after cache lookups, and the price cache only stores one value (the price).

Possible fix:
Overwrite $specific_price.price with cached price value. Convert reduction_amount if reduction_type='amount'.

[https://github.com/PrestaShop/PrestaShop/blob/1d31acbf2322305b7d1efb1bb7dc2a7776b5eb4f/classes/Product.php#L3839](url)

```       
        if (isset(self::$_prices[$cache_id])) {
            // convert only if the specific price is in the default currency (id_currency = 0)
            if ($specific_price && !$specific_price['id_currency'] &&
                    $id_currency !== $specific_price['id_currency']) {
                if (isset($specific_price['price']) && $specific_price['price'] >= 0) {
                    $specific_price['price'] = self::$_prices[$cache_id];
                    if ($specific_price['reduction_type'] == 'amount') {
                        $specific_price['reduction'] = Tools::convertPrice($specific_price['reduction'], $id_currency);
                    }
                }
            }
            return self::$_prices[$cache_id];
        }
```

### Expected behavior

$specific_price output always in correct currency

### Steps to reproduce

Product with specific price in default currency.
Customer with non-default currency.

Display the same product twice on a page.
If the same price calculation is requested multiple times during render, it might be enough to just display the product.

### PrestaShop version(s) where the bug happened

8.1.x

**Comment by florine2623** [comment] 2024-06-14 12:31
Hello @Perfecticus ,

Could you specify the Steps to reproduce ?
As well as send a screen record of the actions ?

Waiting for your feedback
Thanks!

**Comment by florine2623** [comment] 2024-07-09 08:55
ping @Perfecticus

**Comment by paulnoelcholot** [comment] 2024-07-10 08:11
Hello @Perfecticus ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-07-10 08:11 UTC
Labels: Bug, FO, Can't reproduce, 8.1.x, Products Page
