### ISSUE TITLE
Error to copy translations from the classic theme to extra theme

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#18076] opened 2020-03-10 11:55 UTC
Hi
I manage a site with 11 languages
the translations of the theme for some languages are ok (because inside its translations folders are present files) and in others no like for russian (because in its translations folder there are no files)
However it is not important because not all themes have all possible translations.

in the translation admin page, at the bottom, there is a section named "Copy" to Copies data from one language to another.

I've seen that the classic theme is well translated about russian language, so I think to use this tool to copy the russin translations from the classic theme to the PRS170_02
but I get an error.
This error is strange, because it wants to copy the lang/ru.php file of classic theme to the other theme, but that file doesn't exist in a theme folder, normally it is present a translations folder, however the calssic theme doesn't use it, probably its translations are in the main translations folder in the webroot

This tool can be very useful for everyone needs less used languages that are usually not present in the themes purchased on addons

I've the same problem with polish, hungarian, dutch, greek and others

I'll wait your answer
thanks

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/76309159-7c828380-62cc-11ea-8469-d8cc83001e2e.png)
![2](https://user-images.githubusercontent.com/653230/76309161-7d1b1a00-62cc-11ea-9548-0ebe80638905.png)
![3](https://user-images.githubusercontent.com/653230/76309163-7db3b080-62cc-11ea-9b8e-59145743798f.png)
![4](https://user-images.githubusercontent.com/653230/76309165-7e4c4700-62cc-11ea-9745-42c3722b39af.png)
![5](https://user-images.githubusercontent.com/653230/76309168-7f7d7400-62cc-11ea-9f73-12edf2ae0c16.png)

#### Additional information

* PrestaShop version: 7.2
* PHP version: 1.7.6.3

**Comment by khouloudbelguith** [comment] 2020-03-10 12:07
Hi @maofree,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16132
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-10 12:07
Duplicate of #16132

**Closed as completed by khouloudbelguith** 2020-03-10 12:07 UTC
Labels: Duplicate
