### ISSUE TITLE
Wrong behaviour when using "tax included" in amount specific prices 

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#10798] opened 2018-10-01 16:47 UTC
**Describe the bug**

When using an "amount" type specific price, it the discount is set to be "tax included",
taxes are not removed if the customer country have a tax-free rule 

**To Reproduce**
1. Install a Prestashop in Italian language to have standard VAT handling

2. Create a Tax Rule named "Tax Free" and add a country into it with "This tax only" behaviour  I used "Singapore" and enabled Singapore country in Prestashop]

![image_1](https://user-images.githubusercontent.com/43071148/46302733-2a531400-c5aa-11e8-973f-737e8557bcce.png)

3. Create a product with 100€ price (tax included) 
![image_2](https://user-images.githubusercontent.com/43071148/46302751-34751280-c5aa-11e8-9f46-636b041c0213.png)

4. Create a specific price on the product with -€20.00 (Tax incl.) [See Image 3]
![image_3](https://user-images.githubusercontent.com/43071148/46302757-39d25d00-c5aa-11e8-9880-7796e033683d.png)

5. Create a front office customer with a Singapore address and open the product.

![image_4](https://user-images.githubusercontent.com/43071148/46302765-3fc83e00-c5aa-11e8-8455-8f9948a60c5b.png)

Price is shown in this way 
Retail price 100€ became 81.97€ because of "Tax free"  rule deduction [THIS IS OK!]
Discounted price became 61.97€ because of the 20.00€ specific price deduction [THIS IS NOT OK! I expect to have a 16.40€ deduction , because the specific price had been set "tax included" itself]

**Screenshots**
Screenshot are referred in "To reproduce" description.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-10-01 17:01
Hi @gennaris,

Have the same issue with this ticket: #9696?

Best regards, Khouloud

**Comment by gennaris** [comment] 2018-10-01 17:11
Hi @khouloudbelguith ,
Kind of... Reporter on ticket #9696 had display issue with customers group, I'm having calculation issue with tax rules group. I am not sure a single PR can fix both issues.

**Comment by khouloudbelguith** [comment] 2018-10-01 17:23
Hi @gennaris,

We have a lot of issue related to the prices. 
Thanks to take a look at this link: Prices - Lot 2 #9700
You may have your issue described in this list. 
Thanks to check and feedback.

Best regards, Khouloud

**Comment by gennaris** [comment] 2018-10-02 07:17
Hi @khouloudbelguith ,
indeed my issue is duplicate of #9856  (BOOM-4062) 

I wasn't able to find this issue yesterday.

**Comment by khouloudbelguith** [comment] 2018-10-02 08:05
Hi @gennaris,

This issue is added to our bug roadmap with a Major priority.
Your ticket is a duplicate of #9856
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-02 08:05
Duplicate of #9856

**Closed as completed by khouloudbelguith** 2018-10-02 08:05 UTC
Labels: Bug, FO, Duplicate, 1.7.4.2
