### ISSUE TITLE
BO: While printing the order the sidepanel is shown.

### ISSUE THREAD

**Issue by LedCloud** [PrestaShop/PrestaShop#10371] opened 2018-09-11 09:06 UTC
Fresh clean install 1.7.4.2

If you try to print the order the left side panel is shown.

See the attach.
[Orders _ Order_KHWLILZLL_from_John_DOE_Test1.pdf](https://github.com/PrestaShop/PrestaShop/files/2370280/Orders._.Order_KHWLILZLL_from_John_DOE_Test1.pdf)
[Orders_Order_KHWLILZLL_from_John_DOE_Test2.pdf](https://github.com/PrestaShop/PrestaShop/files/2370281/Orders_Order_KHWLILZLL_from_John_DOE_Test2.pdf)

Second file was created with collapsed panel. First with expanded.

**Comment by rdy4ever** [comment] 2018-09-11 09:24
Hello. This is the PR to fix the issue: https://github.com/PrestaShop/PrestaShop/pull/10135

**Comment by Quetzacoalt91** [comment] 2018-09-11 09:53
Thank you @rdy4ever.

The issue will be fixed on 1.7.5.0. I'm closing as this is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9527.

Regards

**Closed as completed by Quetzacoalt91** 2018-09-11 09:53 UTC
