### ISSUE TITLE
Errors  upgrading prestashop 8.1.0  to 8.1.2 with Module  1-click-upgrade 4.16.4

### ISSUE THREAD

**Issue by orvalvert** [PrestaShop/PrestaShop#34170] opened 2023-10-04 16:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi 
I got these errors upgrading prestashop 8.1.0 to 8.1.2

[INTERNAL] /home/zrda3257/public_html/vendor/composer/autoload_real.php line 36 - Error: Class "Composer\Autoload\ComposerStaticInit5eb78744eba60b19a8380318056b086b" not found #0 /home/zrda3257/public_html/vendor/autoload.php(25): ComposerAutoloaderInit5eb78744eba60b19a8380318056b086b::getLoader() #1 /home/zrda3257/public_html/modules/autoupgrade/classes/UpgradeContainer.php(567): require_once('/home/zrda3257/...') #2 /home/zrda3257/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(87): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader() #3 /home/zrda3257/public_html/admin123/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #4 {main}

### Steps to reproduce

initial install was prestahop 8.1.0 
then upgrade module 1- click upgrade from 4.16.2 to 4.16.4
then upgrade prestashop to 8.1.2 with 1- click upgrade 

### PrestaShop version(s) where the bug happened

8.1.0 to 8.1.2

### PHP version(s) where the bug happened

8.1.16

### If your bug is related to a module, specify its name and its version

1- click upgrade 4.16.4

**Comment by paulnoelcholot** [comment] 2023-10-05 09:46
Hello @orvalvert,

I tested your issue but as you can see, I can't reproduce it : 
[Module manager • the future (1).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/c269be2e-62ea-45d3-a501-a8919778b7c8)

Did I miss something?

Thank you for your feedback!

**Comment by orvalvert** [comment] 2023-10-05 13:58
HI Paul-Noël

Thanks for you answer and your help! 

I used juste the default upgrade (see Attachment) 
---------------------------------------------------------------------------------------------------------------------------
START YOUR UPGRADE
Your current PrestaShop version: 8.1.0
Your current PHP version: 8.1.22
Latest official version for minor channel.: 8.1 stable - (8.1.2)

 PrestaShop will be downloaded from https://github.com/PrestaShop/PrestaShop/releases/download/8.1.2/prestashop_8.1.2.zip
-----------------------------------------------------------------------------------------------------------------------------
Is that different ? 
 should I copy 

prestashop_8.1.2.xml 2.16 MB last week
and prestashop_8.1.2.zip
 from github to server ?
 
Why does it change?

Thanks a lot for your help !




----- Mail original -----
De: "Paul-Noël" ***@***.***>
À: "PrestaShop/PrestaShop" ***@***.***>
Cc: "orvalvert" ***@***.***>, "Mention" ***@***.***>
Envoyé: Jeudi 5 Octobre 2023 11:46:38
Objet: Re: [PrestaShop/PrestaShop] Errors  upgrading prestashop 8.1.0  to 8.1.2 with Module  1-click-upgrade 4.16.4 (Issue #34170)





Hello @orvalvert , 

I tested your issue but as you can see, I can't reproduce it : 
Module manager • the future (1).webm 

Did I miss something? 

Thank you for your feedback!

**Comment by orvalvert** [comment] 2023-10-05 14:59
Hi 
I try again now it's good ! I don't know why but it's all right .
Thanks


----- Mail original -----
De: ***@***.***
À: "PrestaShop/PrestaShop" ***@***.***>, "Paul-Noël" ***@***.***>
Envoyé: Jeudi 5 Octobre 2023 15:58:31
Objet: Re: [PrestaShop/PrestaShop] Errors  upgrading prestashop 8.1.0  to 8.1.2 with Module  1-click-upgrade 4.16.4 (Issue #34170)


HI Paul-Noël

Thanks for you answer and your help! 

I used juste the default upgrade (see Attachment) 
---------------------------------------------------------------------------------------------------------------------------
START YOUR UPGRADE
Your current PrestaShop version: 8.1.0
Your current PHP version: 8.1.22
Latest official version for minor channel.: 8.1 stable - (8.1.2)

 PrestaShop will be downloaded from https://github.com/PrestaShop/PrestaShop/releases/download/8.1.2/prestashop_8.1.2.zip
-----------------------------------------------------------------------------------------------------------------------------
Is that different ? 
 should I copy 

prestashop_8.1.2.xml 2.16 MB last week
and prestashop_8.1.2.zip
 from github to server ?
 
Why does it change?

Thanks a lot for your help !




----- Mail original -----
De: "Paul-Noël" ***@***.***>
À: "PrestaShop/PrestaShop" ***@***.***>
Cc: "orvalvert" ***@***.***>, "Mention" ***@***.***>
Envoyé: Jeudi 5 Octobre 2023 11:46:38
Objet: Re: [PrestaShop/PrestaShop] Errors  upgrading prestashop 8.1.0  to 8.1.2 with Module  1-click-upgrade 4.16.4 (Issue #34170)





Hello @orvalvert , 

I tested your issue but as you can see, I can't reproduce it : 
Module manager • the future (1).webm 

Did I miss something? 

Thank you for your feedback!

**Comment by RosaBenouamer** [comment] 2023-10-06 04:53
Great so I close the issue @paulnoelcholot :-)

**Closed as completed** 2023-10-06 04:54 UTC
Labels: Bug, BO, Autoupgrade, Invalid, 8.1.x

**Comment by orvalvert** [comment] 2023-10-06 13:27
Hi 

Sorry it's not finished.
I've test prestashop and i've many problems (tickets 34186 and 34188).  So I deduced that the installation of 8.1.2 after upgrade must have gone badly. 
I started from scratch. I deleted prestashop. 
Then Installed first with softaculous (on o2switch) the prestashop version available 8.1.0. I tested it and no problem. 
I decided next to retrieve the files from the prestahop github site to use the click upgrade expert mode to upgrade to 8.1.2 as in your video to see what that gives. And here I have errors again in the upgrade report (PJ). However this time I see the marketplace and I can select the products in the back office..
I noticed that in the XML file to use section I put the xml retrieved from the site but you put prestashop_8.1.2+build.1.xml. Is that the good version to import , does it makes the différence? Where can i found this package?
Thanks for helping me i try to learn to do as well as possible.



----- Mail original -----
De: ***@***.***
À: "PrestaShop/PrestaShop" ***@***.***>, "Paul-Noël" ***@***.***>
Envoyé: Jeudi 5 Octobre 2023 16:59:51
Objet: Re: [PrestaShop/PrestaShop] Errors  upgrading prestashop 8.1.0  to 8.1.2 with Module  1-click-upgrade 4.16.4 (Issue #34170)



Hi 
I try again now it's good ! I don't know why but it's all right .
Thanks


----- Mail original -----
De: ***@***.***
À: "PrestaShop/PrestaShop" ***@***.***>, "Paul-Noël" ***@***.***>
Envoyé: Jeudi 5 Octobre 2023 15:58:31
Objet: Re: [PrestaShop/PrestaShop] Errors  upgrading prestashop 8.1.0  to 8.1.2 with Module  1-click-upgrade 4.16.4 (Issue #34170)


HI Paul-Noël

Thanks for you answer and your help! 

I used juste the default upgrade (see Attachment) 
---------------------------------------------------------------------------------------------------------------------------
START YOUR UPGRADE
Your current PrestaShop version: 8.1.0
Your current PHP version: 8.1.22
Latest official version for minor channel.: 8.1 stable - (8.1.2)

 PrestaShop will be downloaded from https://github.com/PrestaShop/PrestaShop/releases/download/8.1.2/prestashop_8.1.2.zip
-----------------------------------------------------------------------------------------------------------------------------
Is that different ? 
 should I copy 

prestashop_8.1.2.xml 2.16 MB last week
and prestashop_8.1.2.zip
 from github to server ?
 
Why does it change?

Thanks a lot for your help !




----- Mail original -----
De: "Paul-Noël" ***@***.***>
À: "PrestaShop/PrestaShop" ***@***.***>
Cc: "orvalvert" ***@***.***>, "Mention" ***@***.***>
Envoyé: Jeudi 5 Octobre 2023 11:46:38
Objet: Re: [PrestaShop/PrestaShop] Errors  upgrading prestashop 8.1.0  to 8.1.2 with Module  1-click-upgrade 4.16.4 (Issue #34170)





Hello @orvalvert , 

I tested your issue but as you can see, I can't reproduce it : 
Module manager • the future (1).webm 

Did I miss something? 

Thank you for your feedback!

**Comment by orvalvert** [comment] 2023-10-06 15:14
![image001](https://github.com/PrestaShop/PrestaShop/assets/143817250/5598092b-2ba0-46c7-a814-85d1fd09136e)
