### ISSUE TITLE
Unable to update Stock, Order and Shipping

### ISSUE THREAD

**Issue by atonia** [PrestaShop/PrestaShop#15516] opened 2019-09-12 18:50 UTC
We are unable to update the order, stock or shipping confirmation for one of our customer. We are receiving a 405 error message.However customer has enabled all the methods that could possibly cause this error if disabled. Something seems to be blocking the PUT method.

![image](https://user-images.githubusercontent.com/55251690/64812125-9ab13600-d56c-11e9-9de5-d64daae5c679.png)

The customer has enabled all the necessary PUT methods.
![image](https://user-images.githubusercontent.com/55251690/64812041-6fc6e200-d56c-11e9-926f-0a548c165d64.png)

 But we receiving the error as follows.
![image](https://user-images.githubusercontent.com/55251690/64812063-810fee80-d56c-11e9-9bea-47cf351d0f73.png)

Please help.

**Comment by khouloudbelguith** [comment] 2019-09-13 08:40
Hi @atonia,

I did not manage to reproduce the issue with PS1.7.6.1.
In the webservice account page, All these permissions `View (GET) | Modify (PUT) | Add (POST)` are enabled for all Resource.
I used this script & it is OK

```
<html><head><title>pUT DATA</title></head><body>
<?php
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://prestashop.local/1761');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'http://prestashop.local/1761',
    'Key',
    false);



$id = 2; //ID order Here

$xml = $ws->get(array('resource' => 'orders', 'id' => $id));

echo "BEFORE\n";
echo $xml->asXML();

unset($xml->order->current_state);
//unset($xml->order->manufacturer_name);
//unset($xml->order->associations->order_features); 
//unset($xml->order->quantity);
//unset($xml->order->associations);

$xml->order->current_state = 4;
$xml->order->shipping_number = 12;

$xml->order->total_shipping = 12;
$xml->order->total_shipping_tax_incl = 12;
$xml->order->total_shipping_tax_excl = 12;

$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'orders';

$xml = $ws->edit($opt);


$xml = $ws->get(array('resource' => 'orders', 'id' => $id));
echo "AFTER\n";
echo $xml->asXML();

```
https://drive.google.com/file/d/1s_0V9djuBcv-J0hgKXLpsWVcAPBKjzC1/view

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-14 08:12
Hi @atonia,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-14 08:12 UTC
Labels: Bug, WS, Order, No change required, 1.7.6.1
