### ISSUE TITLE
When I activate SMARTY cache, the description of the related products is not displayed

### ISSUE THREAD

**Issue by Marcelozippo** [PrestaShop/PrestaShop#16248] opened 2019-11-01 15:53 UTC
Hello, I have the problem that when I activate SMARTY cache, the description of the related products is not displayed. And the same products are always shown. How can I solve it? What can I do to avoid having to deactivate SMARTY?
Prestashop 1.7.6.1
Cpanel
PHP 7.2.23
MySQL: 10.2.27-MariaDB-log-cll-lve 

Video
https://drive.google.com/file/d/1wkwFFIhqaBtxpt1Pm__ir5aO8h3G8MPe/view

The creator of the wharehouse template tells me that it is a prestashop problem.

Regards
Marcelo

**Comment by khouloudbelguith** [comment] 2019-11-01 16:03
Hi @Marcelozippo,

I did not manage to reproduce the issue with PS1.7.6.1 & Two different themes.
I attached a screen record
https://drive.google.com/file/d/1MWWXV2aqk2rWhZKXdjvbCQwqQS04uav6/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Marcelozippo** [comment] 2019-11-01 16:45
Hi, I think I'm using another module, it's not the same as seen in your video. The module I am using is:

Enhance your business, add a block on every product page that displays items from the same category.
Products in the same category
PrestaShop v1.0.4

This is a free module of official Prestashop, it appears on all products. I send you a photo.

In the server log it doesn't give me any errors.
If I activate debug, I have no error

Prestashop 1.7.6.1
Cpanel
PHP 7.2
Video

Regards
Marcelo
![categorias relacionadas](https://user-images.githubusercontent.com/53478767/68040805-d5eafe00-fcad-11e9-8dce-5189c47db711.jpg)

**Comment by khouloudbelguith** [comment] 2019-11-04 13:02
Hi @Marcelozippo,

I tried with PS1.7.6.1 fresh install & it is OK.
I attached a screen record
https://drive.google.com/file/d/1XFkwj5GC4lhe-GkbDiil_pwp65esCdym/view
Your issue is duplicate of #15684. 
If you enable the debug mode, you can find an exception related to your theme.
The issue is fixed with this PR: https://github.com/PrestaShop/ps_categoryproducts/pull/6

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-04 08:00
Hi @Marcelozippo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-04 08:00 UTC
Labels: Bug, FO, Category products, No change required, 1.7.6.1
