### ISSUE TITLE
displayAdminProductsExtra bug

### ISSUE THREAD

**Issue by adu42** [PrestaShop/PrestaShop#15148] opened 2019-08-19 03:36 UTC
version 1.7.7.0, develp

file line 513:
src\PrestaShopBundle\Resources\views\Admin\Product\ProductPage\product.html.twig

`{% if hookcount('displayAdminProductsExtra') > 0 %}`    line 513 This line get always false
`{% set hooks = renderhooksarray('displayAdminProductsExtra', { 'id_product': id_product }) %}` line 
 612

is declare after render?

_____________________

Not call hookDisplayAdminProductsExtra  in any way.

DEBUG SHOW:
Hook name | Call(s)
-- | --
moduleRoutes | 2
displayBackOfficeHeader | 2
displayBackOfficeTop | 2
actionAdminControllerSetMedia | 2
displayAdminNavBarBeforeEnd | 2
displayAdminAfterHeader | 2

——————————————————————————————————
found the bug.

hooks name are strtolower in EventSubscriber just in HookDispatcher use strtolower, but all other position not use strtolower.  your need to change all or change the two position.
displayadminproductsextra in EventSubscriber 
displayAdminProductsExtra to chceck is not exist.

**Comment by khouloudbelguith** [comment] 2019-08-19 10:04
Hi @adu42,

Could you please provide me the exact steps to reproduce the issue?

Thanks!

**Comment by adu42** [comment] 2019-08-20 01:10
I don't kown why EventSubscriber hooks in strtolower, Is it to solve the declaration problem?

**Comment by matks** [comment] 2019-08-20 08:52
> I don't kown why EventSubscriber hooks in strtolower, Is it to solve the declaration problem?

It's because of this issue: https://github.com/PrestaShop/PrestaShop/issues/10412

Basically: in PS 1.6 hooks were case-insensitive. We started using Symfony EventDispatcher to replace hooks, but Symfony EventDispatcher is case-sensitive so the behavior was changed which caused issues.

We used the strtolower trick internally to make them case-insensitive again but we still display the hooks without the strtolower to make code navigation better.

I'm aware it's a dirty trick 😞 . It will be fixed in next major version, PS 8.0, when we will officially drop the case-insensitive behavior and tell people to make sure they call hook names properly.

**Comment by matks** [comment] 2019-08-20 08:55
So it seems that the PR https://github.com/PrestaShop/PrestaShop/pull/14249 introduced this issue

@adu42 If I understand correctly, 
```
{% if hookcount('displayAdminProductsExtra') > 0 %}
{% set hooks = renderhooksarray('displayAdminProductsExtra', { 'id_product': id_product }) %} 
```
do not work, even though you have a module that is hooked on them ?

**Comment by adu42** [comment] 2019-08-24 02:01
OK,I get it. 
#14249  help me 
Thanks

**Closed as completed** 2019-08-24 02:01 UTC
Labels: Bug, develop, No change required

**Comment by khouloudbelguith** [comment] 2019-08-26 07:50
@adu42, thanks for your feedback.
Feel free to open a new ticket when needed.
