### ISSUE TITLE
Customer add address to account result in 500 error

### ISSUE THREAD

**Issue by Assalea** [PrestaShop/PrestaShop#10284] opened 2018-09-04 19:17 UTC
Hello!
Need some help with the prestashop adding an address to your account. When you sign in to your account and click "my addresses" and the "add address" when you save you new address by clicking the "save" button you are redirected to a 500 error page, even though the address is saved.

If you instead try to update your current address the sam button works and the changes is saved without any problem. Please help me get rid off that 500 error page showing!

**Comment by khouloudbelguith** [comment] 2018-09-05 08:09
Hi @Assalea,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Assalea** [comment] 2018-09-05 08:57
Okay!

Our host i misshosting (www.misshosting.com) and put prestashop version is 1.7.1.2. We are getting this error: 500 Server Error
Oops, something went wrong.

Try to refresh this page or feel free to contact us if the problem persists.

And its reproduced by two ways:
1. Go to Discboss.se sign in to your account>”my addresses”>”add new address”>fill in the required fields>click save. Error page showing.
2. Go to Discboss.se> sign in to your account> put a product in the shipping cart> go to checkout> fill in your address> click next step. Error page showing.
Please help

**Comment by khouloudbelguith** [comment] 2018-09-05 09:08
Hi @Assalea,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Assalea** [comment] 2018-09-05 11:10
I am not sure how to get the PHP error log dont see it in that document. Am i going to set our prestashop version in debug mode like it says in the document?

**Comment by khouloudbelguith** [comment] 2018-09-05 11:14
Hi @Assalea,

Yes, you need to navigate to BO > Advanced Parameters > Performance Page
In the Debug Mode section, set “Debug Mode” to “Yes”.
Click the “Save” button.
Try to repeat all the steps to save an address, check, and feedback.

Best regards, Khouloud

**Comment by Assalea** [comment] 2018-09-05 11:23
Debug mode is now activated

**Comment by Assalea** [comment] 2018-09-05 11:23
[PrestaShopException]
Egenskap Address->id_country är tom.
at line 944 in file classes/ObjectModel.php

939.             }
940. 
941.             $message = $this->validateField($field, $this->$field);
942.             if ($message !== true) {
943.                 if ($die) {
944.                     throw new PrestaShopException($message);
945.                 }
946.                 return $error_return ? $message : false;
947.             }
948.         }
949. 
ObjectModelCore->validateFields - [line 272 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 683 - classes/ObjectModel.php]
ObjectModelCore->update - [line 202 - classes/Address.php] - [1 Arguments]
AddressCore->update - [line 219 - classes/Address.php]
AddressCore->delete - [line 73 - classes/form/CustomerAddressPersister.php]
CustomerAddressPersisterCore->save - [line 162 - classes/form/CustomerAddressForm.php] - [2 Arguments]
CustomerAddressFormCore->submit - [line 58 - controllers/front/AddressController.php]
AddressControllerCore->postProcess - [line 194 - classes/controller/Controller.php]
ControllerCore->run - [line 369 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

**Comment by khouloudbelguith** [comment] 2018-09-05 11:25
Hi @Assalea,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9812
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-05 11:26
Duplicate of #9812

**Closed as completed by khouloudbelguith** 2018-09-05 11:25 UTC
Labels: Bug, FO, Duplicate, Addresses

**Comment by Assalea** [comment] 2018-09-05 12:28
Its not says how to resolve it, the line 944 shows error in the debug mode but what am I supposed to change it too?

**Comment by khouloudbelguith** [comment] 2018-09-05 13:05
Hi @Assalea,

It is not fixed yet, it is added to our bug roadmap.
But for a quick solution, you need to navigate to your BO => International => Locations => Countries Tab => Search for your country and edit it.
In the Address format, you need to add the city field.
![image](https://user-images.githubusercontent.com/16067358/45094961-1b00b800-b11d-11e8-9085-474164d282f2.png)

Best regards, Khouloud

**Comment by Assalea** [comment] 2018-09-05 14:02
The city field was already added, so is there any other quick fix?

**Comment by khouloudbelguith** [comment] 2018-09-05 14:06
Hi @Assalea,

Sorry no.
You need to follow #9812.

Best regards, Khouloud

**Comment by storygram** [comment] 2020-02-17 12:19
Hi,
when I want to make a new account, or create an account during orders, I get the error ''500 Server Error Oops, something went wrong.
Try to refresh this page or feel free to contact us if the problem persists.''

**Comment by storygram** [comment] 2020-02-17 12:19
Please help me

**Comment by khouloudbelguith** [comment] 2020-02-17 12:58
@storygram, issue created here: https://github.com/PrestaShop/PrestaShop/issues/17692
