### ISSUE TITLE
Deleted customization field not ignored

### ISSUE THREAD

**Issue by Spir** [PrestaShop/PrestaShop#21320] opened 2020-10-06 10:06 UTC
#### Describe the bug

When a product has a required customization field, if I delete this one I can no longer add the product to basket.

#### Expected behavior

The product should be added to the basket

#### Steps to Reproduce

1. Go to edit a product in the backend
2. On option add a customization field (text) make it required and save
3. Add this product to a basket on the frontend
4. Edit the product in the backend and delete the customization field, the customization field is marked as deleted in the table:

![Screenshot from 2020-10-06 12-02-20](https://user-images.githubusercontent.com/213191/95187838-ed8b0a80-07cb-11eb-8670-376cad1fad85.png)

5. now when adding the product on the frontend (after refreshing the cache from server/client) the product is no longer added:
The JSON error is:
{"hasError":true,"errors":["Veuillez remplir tous les champs requis, puis enregistrer votre personnalisation."],"quantity":null}
6. If i delete manually the line in the database it is working again:
`DELETE FROM ps_customization_field WHERE id_customization_field = 452`

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3.22

**Comment by khouloudbelguith** [comment] 2020-10-06 10:18
Hi @Spir,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15739 to fix the issue.
Your ticket is a duplicate of #13211
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-10-06 10:18
Duplicate of #13211

**Closed as completed by khouloudbelguith** 2020-10-06 10:18 UTC
Labels: Duplicate, Product customization
