### ISSUE TITLE
E-Mails cannot be sent / E-Mail Templates are missing

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#22388] opened 2020-12-12 15:18 UTC
#### Describe the bug
When you try to send Order message to client, the system display an error.
It happens also with other messages, for example when changing the status (to any which would send out an email) - in that case the error message is just looking different, but email sending also not possible - please check the screenshot
the important part is maybe here that it is a Multishop - as on a multilanguage system (with the same languages available) it is working well.

#### Expected behavior
The mails are sent without an error

#### Steps to reproduce
1. open an order
2. fill in a message/comment in the comment field and click on (send also to the customer)
3. click send message
4. error message on a new blank page (and nothing else): "Error - The following e-mail template is missing: order_merchant_comment"

#### Screenshots
Error Message: `"Error - The following e-mail template is missing: X" (with X as var for different template-names)`

#### Additional informations

- Multilanguage
- Multishop
- Prestashop 1.7.7
- PHP 7.3

**Comment by tom75** [comment] 2020-12-14 10:23
just wanted to let you know that it is a multilanguage and also multishop installation

**Comment by hibatallahAouadni** [comment] 2020-12-14 16:00
Hello @tom75 

Could you please edit your issue, cause we need these sections (Expected behavior, Steps to Reproduce, Additional information) to reproduce your issue as soon as possible.

We create this template to make it easy for you and for us to handle the issue :smile: 

Thanks

**Comment by hibatallahAouadni** [comment] 2020-12-26 11:47
Hello @tom75 

Sorry for the late response, I just edit your issue description :wink: 
Unfortunally I didn't manage to reproduce your issue with PS1.7.7.0, please see the screen record below:

https://drive.google.com/file/d/1gY3-6175ZOb6L-7xu6H69FexdohGcfz2/view

Could please check your Email configuration, see the attached screenshot below:

1. **BO**>**CONFIGURE**>**Advanced Paramters**>**E-mail** (1)
2. Scroll down to the **Email** block
3. Fill all the inputs, then **Save** (2)
4. Test your email configuration, by sending a test email (3) (put your email not the demo email :wink: )

![image](https://user-images.githubusercontent.com/23308427/103150753-32915e00-4777-11eb-92fd-2bd80b50f0ad.png)

_**PS: while using Multistore and multilanguage, you need to check Email Theme for every store/language and Generate emails (see the attached screenshot below)**_

![image](https://user-images.githubusercontent.com/23308427/103150908-1b537000-4779-11eb-9939-b87025056e9c.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-17 13:08
Hello @tom75 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-17 13:08 UTC
Labels: BO, Email, No change required, 1.7.7.0
