### ISSUE TITLE
Carrier not available for customer, but it is for me.

### ISSUE THREAD

**Issue by Prestashopper** [PrestaShop/PrestaShop#14201] opened 2019-06-13 15:51 UTC
Hi,
big issue with Ps, probably a big bug.  
A user notified me she can't buy due to error "unfortunately the are no carriers available for your delivery address."

I have one carrier, available for visitors, guests and customers.

I have Already shipped in europe and USA, so i think carrier settings are ok.

I tried with the same address and everything is ok: carrier available.
I tried create a new customer and using that address: carrier available.
I tried a guest purchase with that address: carrier available.

I tried erasing her cart to make her create a new cart: carrier not avalaible.

The big problem is I don't know if this issue afflicted other customers. 

I can't reproduce the error, i never had that during my tests.

How can I fix this issue?

How can I investigate to find where problem starts and find if others customers had the same problem in the past?

Thanks

**Comment by khouloudbelguith** [comment] 2019-06-13 15:55
Hi @Prestashopper,

Thanks for your report.
Have you the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/10903#issuecomment-438573882?
Thanks to check & feedback.

**Comment by Prestashopper** [comment] 2019-06-13 16:17
NO, #10903 issue is on cart rule. My problem is on carrier.

________________________________
Da: khouloudbelguith <notifications@github.com>
Inviato: giovedì 13 giugno 2019 17:55
A: PrestaShop/PrestaShop
Cc: Prestashopper; Mention
Oggetto: Re: [PrestaShop/PrestaShop] Carrier not available for customer, but it is for me. (#14201)


Hi @Prestashopper<https://github.com/Prestashopper>,

Thanks for your report.
Have you the same issue reported here: #10903 (comment)<https://github.com/PrestaShop/PrestaShop/issues/10903#issuecomment-438573882>?
Thanks to check & feedback.

**Comment by BenTen** [comment] 2019-06-14 02:42
Which version of PS?

Did you check the group of this customer? Try to change it and save.

**Comment by Prestashopper** [comment] 2019-06-14 07:46
Hi Ben, 

PS is 1.7.5.1

the customer was on guest while having the issue, i changed her in customer and had the same issue.

**Comment by khouloudbelguith** [comment] 2019-06-14 08:17
Hi @Prestashopper,

If PrestaShop Carriers Are Not Available At Checkout, you need to check:

1. Carrier Is Inactive: PrestaShop carrier status is the first thing you should consider
Incorrect Zone Assign or Country Disabled: Zone association is among the first things to check if a created carrier does not show for a specific shopper. When configuring PrestaShop carrier you are supposed to assign it to zones, this very carrier can deliver parcels within. If a carrier is not assigned to the zone, customer address belongs to, then it will not show as a delivery method at the checkout.
2. Carrier Is Not Allowed for Customer Group: This detail might easily be skipped, since you can have hundreds and thousands of customers, belonging to various customer groups. If some customer belongs to the group that is not served by the current shipper, it will not be offered as a delivery method for this customer
3. Weight or Price Ranges Are Not Specified: Creating PrestaShop carrier you usually define billing cost for each by one of the criteria: order price or weight. Having selected a suitable method, you need to create ranges and set prices for them. In case ranges are not created, “The product selection cannot be delivered by the available carrier(s). Please amend your cart” message will display at shipping step for a customer.
4. Package Dimensions Are Out of Range: If all above listed settings are configured properly but still PrestaShop carrier does not display at the checkout, you have to compare package dimensions with maximum dimensions PrestaShop carrier can handle. If the package goes beyond these limits, the carrier can’t ship it and, respectively will not display as a delivery method.

Thanks to check & feedback.

**Comment by Prestashopper** [comment] 2019-06-14 08:57
Hi @khouloudbelguith,
thanks for replying.

1) Russia is the country from one customer had the issue (but i don't know if somebody else had the same problem). These are the settings 
<img width="601" alt="Schermata 2019-06-14 alle 10 47 51" src="https://user-images.githubusercontent.com/51794226/59496610-19c1a000-8e92-11e9-8688-167efd233ac2.png">

 here the config of country
<img width="1208" alt="Schermata 2019-06-14 alle 10 48 46" src="https://user-images.githubusercontent.com/51794226/59496619-1fb78100-8e92-11e9-95ec-c3d0bd2e7816.png">


2) Carrier is available for all groups
<img width="566" alt="Schermata 2019-06-14 alle 10 54 30" src="https://user-images.githubusercontent.com/51794226/59497038-f4816180-8e92-11e9-89c9-8542194a08d2.png">

3) look above

4) look above

How can I find the steps of checkout process? Is there any log and where I can find it/them?

**Comment by khouloudbelguith** [comment] 2019-06-14 10:51
@Prestashopper, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.0beta1
I used the same steps described in this comment: https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-467397790

Thanks to check if they are similar or not?

**Comment by Prestashopper** [comment] 2019-06-14 11:16
No, it's different. My system doesn't produce the #9932 issue.

**Comment by khouloudbelguith** [comment] 2019-06-14 11:18
@Prestashopper, you need to have old orders with the custom C1 & Address A1 before editing it in the next order.

Thanks!

**Comment by Prestashopper** [comment] 2019-06-14 12:25
what's C1?

**Comment by khouloudbelguith** [comment] 2019-06-14 12:50
@Prestashopper, it is the customer created.

Steps to reproduce the issue:
1. Go to FO
2. Create a new customer customer1
3. Create an address for this one
4. Create an order with this customer 
5. Go to BO => Orders => change the status of this order to shipped
6. Go to FO => with the same customer1 => add products to the cart => process the checkout => in the Adress step => go to the customer's account & edit the address
7. Go back to the checkout process => at the shipping step => the error is displayed

Thanks to check & feedback.

**Comment by Prestashopper** [comment] 2019-06-14 20:51
Ok, I reproduced "successfully" your issue... I tested it also in PS 1.7.5.2 and the issue appears.

But I don't know if this issue was my customer issue. How can I find that?

PS. my customer didn't create any order before having that issue, so I don't think #9932 is the issue I met.

**Comment by khouloudbelguith** [comment] 2019-06-17 08:34
@Prestashopper, 
>I tried erasing her cart to make her create a new cart: carrier not available.

In the cart of your customer, are there any of the products added to this cart with available carriers?
![image](https://user-images.githubusercontent.com/16067358/59589969-ee81bf80-90e2-11e9-922f-6199cf001364.png)

Those products are they standard? 

Thanks!

**Comment by Prestashopper** [comment] 2019-06-17 10:50
@khouloudbelguith 

Hi, in the cart of my customer all products are setted like your image: no carrier selected, so the carrier is available for any product.

<img width="709" alt="Schermata 2019-06-17 alle 12 44 19" src="https://user-images.githubusercontent.com/51794226/59598979-bc318b80-90fd-11e9-8e49-57a1a9a31636.png">

All of products are standard

**Comment by khouloudbelguith** [comment] 2019-06-17 11:07
@Prestashopper, thanks for your feedback.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matrixino** [comment] 2019-06-25 14:04
This is a URGENT issue. I have at least 10 shops of customers with this problem. They are filled with support request because they can't find any carrier. If i try the same order, with same address, I can see it.
The only solution is clearing customer cookies, which is clearly not a solution.

**Comment by khouloudbelguith** [comment] 2019-06-25 14:58
Hi @matrixino,

Have you the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-467397790?

Thanks!

**Comment by matrixino** [comment] 2019-06-25 18:43
> Hi @matrixino,
> 
> Have you the same issue reported here: [#9932 (comment)](https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-467397790)?
> 
> Thanks!

It happens even without any cart rule. I mean it happens even with order without free shipping. I'm telling you because I also read the other issue about cart rules.
I can't confirm it's the same case because I don't know if customers did that exact procedure.
All I can tell is that I'm not able to reproduce it if I edit the address from the checkout directly (without going into account->address like you show in the video for the second order). Didn't try going to my account first, but I don't think it's relevant at this point (aka I don't think a customer would go that route to change address when he has "Update/Edit" right under the address step).

**Comment by khouloudbelguith** [comment] 2019-06-26 08:35
@matrixino, thanks for your feedback.
Could you please provide me the exact steps to reproduce the issue reported by your customer, It will help us if you can attach a screen record.

Thanks!

**Comment by matrixino** [comment] 2019-06-26 12:00
I'm unable to provide such info because I can't reproduce it, except following your video 9932.
I fixed that already by modifying the sql query on addressupdate as posted on here before, i hope it was the problem.
The shop customer calling the support are all not-tech-savvy people. So is a pain trying to get useful infos.
The real problem is that the moajority probably don't even call, they just see there are no carriers and quit the shop. This is a very breaking bug for a shop. We are losing lots of sales.
I see this is has been roadmapped for 1.7.7, but it should be first bug to solve.

**Comment by khouloudbelguith** [comment] 2019-06-26 12:44
@matrixino, yes, it is milestoned for 1.7.7 & it is in the epic Topwatchers issue.
@Prestashopper, any news about your issue?

Thanks!

**Comment by matrixino** [comment] 2019-06-26 12:48
> @matrixino, yes, it is milestoned for 1.7.7 & it is in the epic Topwatchers issue.
> @Prestashopper, any news about your issue?
> 
> Thanks!

I don't think you realize how much severe this bug is. PS is not usable at this point. The fix should be released ASAP in the next minor release. We can't wait 2 versions to have a working checkout. We can just close the shop at this point, since we can't sell anything. What is the point of an ecommerce without working cehckout? The are customer literally losing hundred of thousand € per month.

**Comment by khouloudbelguith** [comment] 2019-06-26 12:55
@matrixino, I just pinged our lead Product Manager about the severity of this issue: https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-505826695
Thanks for your understanding!

**Comment by purepixels** [comment] 2019-07-05 14:22
Same problem here (PS 1.7.5.2) With some clients there is no carrier available for their address. When adding address to new client, carriers are all available and orders go through without any problems. All settings checked, there can't be something wrong with carrier or localisation settings. 

In error logs on server I cannot find anything gone wrong. 

Need a solution for this, our client is also on the edge of moving the shop over to other platforms because of this problem. Any help would be highly appreciated!

**Comment by khouloudbelguith** [comment] 2019-07-05 14:34
Hi @purepixels,

This shipping issue in the checkout page is added to our backlog PS1.7.7, it is with "Major" severity.
This ticket is a duplicate of #9932
Please follow: #9932
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-05 14:34
Duplicate of #9932

**Closed as completed by khouloudbelguith** 2019-07-05 14:34 UTC
Labels: FO, Duplicate, Carriers
