### ISSUE TITLE
Quick Access links contain the domain: as a result, they potentially log out the user

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#29763] opened 2022-09-27 06:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I the BO, the Quick Access links contain the domain. As a consequence, in a multishop environment, on gets potentially logged out when using Quick Access, because the domain of the BO changes unexpectedly. This is quite annoying.

### Expected behavior

No link in the BO must log me out. All the links must be relative to the domain and not include the domain.

### Steps to reproduce

Prerequisite:
- Set up a multishop installations with two shops
- Shop A on domain https://shop-a.com
- Shop B on domain https://shop-b.com
- A employee account that has access to the two shops.

Reproduce:
1. As employee log into the BO using https://shop-a.com
2. In the shop selection dropdown list select shop B
3. On the Quick Access menu, inspect the links, they all are like `<a href="https://shop-b.com...`
4. Follow a Quick access link
5. You are logged out and asked to log into shop B on https://shop-b.com

### PrestaShop version(s) where the bug happened

1.7.8.7 (1.6.1.1 does not have this erroneous behavior)

### PHP version(s) where the bug happened

7.3

**Comment by sallemiines** [comment] 2022-09-27 15:40
Hello @lmeyer1 

Thanks for reporting the issue
I reproduce the issue with PrestaShop versions PS1.7.7.8, PS1.7.8.7, you can see the issue here :

https://user-images.githubusercontent.com/31663369/192571574-d04b341e-dfe9-4266-bb7b-56018a93b727.mp4


But, I found this [issue](https://github.com/PrestaShop/PrestaShop/issues/28106) . Could you confirm it's similar to yours ?
Please check and feedback!

Thank you !

**Comment by lmeyer1** [comment] 2022-09-27 16:06
@sallemiines
Yes, #28106 and mine both report the same problem, under a different aspect.
It is quite difficult to follow the screencasts on #28106. If I understand well, the problem has been fixed partially (Link to Dashboard), but not for Quick Access.

**Comment by HanaRebaiQA** [comment] 2022-09-28 10:38
Hello @lmeyer1 

Thank you for your feedback.

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank You!

**Comment by HanaRebaiQA** [comment] 2022-09-28 10:39
It's related to this issue [#28106](https://github.com/PrestaShop/PrestaShop/issues/28106)

**Closed as completed** 2023-01-17 08:20 UTC
Labels: Bug, BO, Shop parameters, Traffic & SEO, Multistore, SEO & URLs, PR available, 1.7.7.8, Verified
