### ISSUE TITLE
Problem with loyalty points

### ISSUE THREAD

**Issue by pruault** [PrestaShop/PrestaShop#24900] opened 2021-06-09 22:29 UTC
#### Describe the bug

2 variables are not correctly defined when you want to convert your loyalty points

#### Expected behavior

Try to convert loyalty points.
Solution: Replace

`$ customer = new Customer ((int) $ context-> customer-> id);
`
through
  ` $ customer = new Customer ((int) $ this-> context-> customer-> id);`

because `$ context `is not defined
AND replace the block

```
if (Configuration :: get ('PS_LOYALTY_TAX')
                && in_array ((int) $ country-> zone, $ allowedTaxZones)
            ) {
                $ cartRule-> reduction_tax = 1;
            } else {
                $ cartRule-> reduction_tax = 0;
            }
```

THROUGH
 ```
 if (Configuration :: get ('PS_LOYALTY_TAX')
                && in_array ((int) $ country-> zone, $ allowedTaxZones)
            ) {
                $ cart_rule-> reduction_tax = 1;
            } else {
                $ cart_rule-> reduction_tax = 0;
            }
```

because `$ cartRule` is not defined

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: NA

**Comment by matks** [comment] 2021-06-10 08:18
Hello @pruault I cannot find mention of PS_LOYALTY_TAX inside the code of PrestaShop. Am I missing something? I think the bug you report maybe is related to a module

**Comment by hibatallahAouadni** [comment] 2021-06-10 10:17
Hello @pruault 

Could you please fill the steps to reproduce and answer @matks question.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-30 16:04
Hello @pruault 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-30 16:04 UTC
Labels: Bug, FO, Cart rules, No change required, 1.7.7.4
