### ISSUE TITLE
PHP errors in log if you edit orders in BO

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#10335] opened 2018-09-07 09:49 UTC
Hello,

**Describe the bug**
PHP errors are present if you edit (add, remove product or change carrier) order in BO.

**To Reproduce**
1. Go to 'BO / orders / add product'
2. Scroll down to 'order overview - product, delivery, total is empty'
3. Refresh page or load this order again
3. See error in PHP log:

[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Undefined index: customized_product_quantity in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/19/34/fb/1934fbae34cc35b8ea26dbe94425c98e5a76176b_0.file._product_line.tpl.php on line 31
[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Undefined index: customized_product_quantity in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/19/34/fb/1934fbae34cc35b8ea26dbe94425c98e5a76176b_0.file._product_line.tpl.php on line 101
[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Undefined index: customized_product_quantity in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/19/34/fb/1934fbae34cc35b8ea26dbe94425c98e5a76176b_0.file._product_line.tpl.php on line 101
[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Undefined index: amount_refundable_tax_incl in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/19/34/fb/1934fbae34cc35b8ea26dbe94425c98e5a76176b_0.file._product_line.tpl.php on line 247
[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Undefined index: recalculate_shipping_cost in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 130
[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Trying to get property of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 130
[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Undefined index: carrier_list in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 147
[07-Sep-2018 08:10:29 Europe/Prague] PHP Notice:  Trying to get property of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 147
[07-Sep-2018 08:10:39 Europe/Prague] PHP Notice:  Undefined index: recalculate_shipping_cost in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 130
[07-Sep-2018 08:10:39 Europe/Prague] PHP Notice:  Trying to get property of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 130
[07-Sep-2018 08:10:39 Europe/Prague] PHP Notice:  Undefined index: carrier_list in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 147
[07-Sep-2018 08:10:39 Europe/Prague] PHP Notice:  Trying to get property of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/e9/70/b4/e970b432df5944146b244df6e48a28a2483051c6_0.file._shipping.tpl.php on line 147

2) Is not possible change carrier from different country/zone. Customer have created two address with different country/zone.

**Screenshots**
NA

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.37-0+deb8u1

Thank you

Best regards

PN

**Comment by khouloudbelguith** [comment] 2018-09-07 10:03
Hi @PeNov,

First, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Second, could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.
Ps: isn't the same issue reported in this ticket: #9602?

Best regards, Khouloud

**Comment by PeNov** [comment] 2018-09-07 11:23
Hello Khouloud,

BOOM-5839 - contain more errors. But you are right this problem was part of this BOOM. Sorry I forgot. But, now we know what cause this errors. :-)

1) /var/cache - deleted: log have same errors
2) smarty cache disabled + force compilation + /var/cache - deleted: log have same errors

Thank you

Best regards

PN

![before_and_after_edit_order_in_bo](https://user-images.githubusercontent.com/38213520/45216396-c25a2800-b2a0-11e8-93fe-2dbb51c18b47.JPG)

**Comment by khouloudbelguith** [comment] 2018-09-07 12:22
Hi @PeNov,

So, can I close this ticket, since it is duplicated?

Best regards, Khouloud

**Comment by PeNov** [comment] 2018-09-07 12:35
Hello Khouloud,

partly duplicate but with steps how to reproduce. Can you please create link between both?

Thank you

Best regards

PN

**Comment by khouloudbelguith** [comment] 2018-09-07 13:13
Hi @PeNov,

It is the same error log, on the same page, order page.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9602
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-07 13:13
Duplicate of #9602

**Closed as completed by khouloudbelguith** 2018-09-07 13:13 UTC
Labels: Duplicate, Order, 1.7.4.2
