### ISSUE TITLE
BO - An exception is thrown when edit combinations in product V2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28933] opened 2022-07-01 15:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is thrown when edit combinations in product V2

![image](https://user-images.githubusercontent.com/92912932/176924454-2783144a-6588-4453-a143-d1157d4e0ea2.png)

https://user-images.githubusercontent.com/92912932/177124690-bc042199-52bc-4b88-b1c5-cafe1e575acd.mp4

https://user-images.githubusercontent.com/92912932/177125227-133670b5-c591-4ef1-a631-61ccd56f0f1b.mp4

### Expected behavior

The page to edit combination is well displayed

### Steps to reproduce

1. Create a product with combinations
2. Generate w new combinations 
3. Click to edit combinations
4. See error >> An exception is thrown 

### PrestaShop version(s) where the bug happened

8.0.x, 8.0.0

### PHP version(s) where the bug happened

7.2

**Comment by jolelievre** [comment] 2022-07-20 16:47
This issue has already been fixed by #28959

**Comment by khouloudbelguith** [comment] 2022-08-05 15:08
Hi @HanaRebaiQA, @jolelievre,

In my case, I cannot reproduce the issue with branch 8.0.x.

https://user-images.githubusercontent.com/16067358/183106187-2943b506-13f7-4c87-95f7-35bffcd4ef6a.mp4

It is fixed.

I will close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2022-08-05 15:08 UTC
Labels: Bug, 8.0.x, Major, BO, Regression, Combinations, Fixed, Verified

**Comment by HanaRebaiQA** [comment] 2022-08-08 08:33
Thank You @khouloudbelguith & @jolelievre
