### ISSUE TITLE
Problem PS 1.7.5 Search Console

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#12806] opened 2019-03-06 15:01 UTC
**Describe the bug**
Hello everyone, I have a problem with Google Search Console because it asks me to insert offers", "review" o "aggregateRating" on my products. Do you know how to insert it?
Should I need a module?

Hope you can help me

Thanks

**Comment by khouloudbelguith** [comment] 2019-03-06 15:09
Hi @morghy1992,

Your ticket is a duplicate of #12687
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-06 15:09
Duplicate of #12687

**Closed as completed by khouloudbelguith** 2019-03-06 15:09 UTC
Labels: Duplicate
