### ISSUE TITLE
Specific price table not change by clicking an nother combination

### ISSUE THREAD

**Issue by mdw230** [PrestaShop/PrestaShop#13257] opened 2019-04-10 07:14 UTC
**Describe the bug**
Specific price table not change by clicking an nother combination

![price2](https://user-images.githubusercontent.com/49470290/55857316-1564c800-5b6d-11e9-8173-9c1b76683600.jpg)
![price3](https://user-images.githubusercontent.com/49470290/55857322-172e8b80-5b6d-11e9-885d-475384344c73.jpg)
After change the combinations the specific prices table are not correctly shown
![price4](https://user-images.githubusercontent.com/49470290/55857325-18f84f00-5b6d-11e9-8bad-79f9d8111754.jpg)
After a reload the page it is correctly shown.I test it on many browsers all have the same problem

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.16

**Comment by khouloudbelguith** [comment] 2019-04-10 08:51
Hi @mdw230,

I manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1EKXILE_E-2Mzp7Xlq8xBiZxNWhj6vBnC/view
This issue is added to our bug roadmap.

Thanks!

**Comment by marionf** [comment] 2019-04-12 09:41
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9872
This issue will be fixed in 1.7.6.0

**Closed as completed by marionf** 2019-04-12 09:41 UTC
Labels: Bug, Minor, FO, Duplicate, Combinations, 1.7.5.1
