### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by FayInter** [PrestaShop/PrestaShop#12350] opened 2019-01-29 15:21 UTC
On Admin panel on customer care->customer messages I am getting the following error.

I have clear the cache and all the files under var/cache but every time I am reproducing the error the folders and files are created again.

Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getTaxCalculationMethod() on null" at /var/www/vhosts/nayaandpiu.gr/httpdocs/var/cache/dev/smarty/compile/91/b2/47/91b247d8aa22b54202d54a61fd0ee41367e2817d_0.file.view.tpl.php line 78

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2.14

**Comment by khouloudbelguith** [comment] 2019-01-29 16:51
Hi @FayInter,

I did not manage to reproduce the issue with PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1h7EClrvMERwfHbWHpDWmgK9a_KYBKM-A/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-28 07:36
Hi @FayInter,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-02-28 07:36 UTC
Labels: BO, Customer service, No change required
