### ISSUE TITLE
Errors on paypal module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11323] opened 2018-11-08 17:11 UTC
Hi
today I cannot join paypal module to a site
I've removed the module, removed its files, then removed its variables in ps_configuration page and try again a new installation, but I get these errors, 30 minutes before I join in paypal from the module and after the login nothing happen I stay in the account in the main page of paypal without return on the site

**Screenshots**
![11](https://user-images.githubusercontent.com/653230/48214883-39836980-e381-11e8-94a7-7069e26da6c6.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0
paypal module: 4.4.2

**Comment by khouloudbelguith** [comment] 2018-11-08 17:12
Hi @maofree,

The Paypal module isn't developed by PrestaShop, but by one of our partner.
You can contact them here: https://support.202-ecommerce.com/fr/support/home

Thanks!

**Comment by Maofree** [comment] 2018-11-08 17:16
the errors are on prestashop's site if you look at the url

**Comment by Maofree** [comment] 2018-11-08 19:28
I get the same error from another site, you should inform well about this error

**Comment by khouloudbelguith** [comment] 2018-11-09 08:12
Hi @maofree,

Yes, you are right, I have the same issue with Paypal v4.4.2.
But, as it's not a native module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by Maofree** [comment] 2018-11-09 08:14
hi
I know well that company, their assistance is less than 0
I've reported it to them on addons and sending 2 emails
at this moment no answer

**Comment by khouloudbelguith** [comment] 2018-11-09 08:26
@maofree, you can contact them here also: support@202-ecommerce.com
Thanks!

**Comment by Maofree** [comment] 2018-11-09 08:36
thanks
already done
also to this one contact@202-ecommerce.com

**Comment by Maofree** [comment] 2018-11-09 11:18
I report you the answer get from 202-ecommerce

Thanks you, there is a problem with your country. This problem comes from Prestashop. We are going to contact directly with them to tell them what's going on with your country, and tell them that is necessary to resolve this problem as soon as possible.

I'm sorry for this inconvenience, but is not from error of our module. It comes from Prestashop Directly.

**Comment by khouloudbelguith** [comment] 2018-11-09 11:20
@maofree, what the exact country that you use?
Thanks!

**Comment by Maofree** [comment] 2018-11-09 11:21
I'm from Italy
but you get the same problem also from France

**Comment by Maofree** [comment] 2018-11-09 11:22
try to speak to Esteban of 202-ecommerce

**Comment by khouloudbelguith** [comment] 2018-11-09 11:25
@maofree, yes I get the same problem with PS1.7.4.4 & the Paypal module v4.4.2 and we have different countries.
https://drive.google.com/file/d/1bBFxX_6QdsLpJ_iVOmdpgG2Em-PwzM8D/view
@marionf what do you think?

**Comment by Maofree** [comment] 2018-11-09 11:29
yes the same
if you look at the url it is a sub-domain of prestashop probably it is due from some permissions to paypal from prestashop

the problem is that there is not the permission from paypal and the return not happen on the module

in same cases I get that errors in others I arrive on paypal account and remain on the main page oftheaccount

**Comment by matks** [comment] 2018-11-09 14:58
This sub-domain of prestashop is a gateway that performs operations using PayPal API before redirecting you to paypal. It looks like a temporary API failure lead to this issue.

It seems fixed now.

**Comment by Maofree** [comment] 2018-11-10 18:46
hi
yes now it is ok

thanks

**Comment by jordytr971** [comment] 2018-11-20 14:28
Hi, I have the same issue since more than 5 month please someone can help me ?

Thankyou in advance

**Comment by LanmanGroup** [comment] 2018-11-20 15:36
> Hi
> today I cannot join paypal module to a site
> I've removed the module, removed its files, then removed its variables in ps_configuration page and try again a new installation, but I get these errors, 30 minutes before I join in paypal from the module and after the login nothing happen I stay in the account in the main page of paypal without return on the site
> 
> **Screenshots**
> ![11](https://user-images.githubusercontent.com/653230/48214883-39836980-e381-11e8-94a7-7069e26da6c6.png)
> 
> **Additionnal information**
> PrestaShop version: 1.7.4.2
> PHP version: 7.0
> paypal module: 4.4.2

If you turn ON Sandbox mode the problem still appears.


**EDIT:  If you come back after the error and retry, now works good**
...but persist the problem that the module doesn't update PAYPAL_%_SANDBOX configuration﻿

**Comment by marionf** [comment] 2018-11-20 15:55
It's a failure of PayPal API not due to PrestaShop
The only thing we can do is to display an error message more clear

**Comment by jordytr971** [comment] 2018-11-20 16:58
> It's a failure of PayPal API not due to PrestaShop
> The only thing we can do is to display an error message more clear

So what we can do about it ?

**Comment by ttoine** [comment] 2018-11-20 18:02
Question: could this be related to a TLS issue with PHP and Paypal? [Other CMS have the same issue](https://www.google.fr/search?q=problem+paypal+tls+php&oq=problem+paypal+tls+php&aqs=chrome..69i57.6480j0j1&sourceid=chrome&ie=UTF-8).

**Comment by ttoine** [comment] 2018-11-21 09:27
More information here from Paypal:
https://www.paypal.com/fm/smarthelp/article/why-do-i-need-to-upgrade-my-system-to-tls-1.2-faq3898
Can someone check their server to see if this is the reason of this issue?

**Comment by macpes** [comment] 2018-11-21 10:33
A update to PrestaShop 1.7.4.4 solved the problem for me.

**Comment by jordytr971** [comment] 2018-11-21 11:31
> A update to PrestaShop 1.7.7.4 solved the problem for me.

1.7.7.4 ? The lastest version is 1.7.4.4

**Comment by macpes** [comment] 2018-11-21 11:38
Sorry, i mean 1.7.4.4. (I have now edited my previous post).

**Comment by Maofree** [comment] 2018-12-09 09:30
Hi
Today I get the same problem but without errors
I cannot join the module to the Paypal's account, I arrive to the Paypal's login and then in the summary page. I cannot see the other page where the granting of authorizations is shown.
I've alerted 202commerce
can you check if there are the same problems on your system?

**Comment by khouloudbelguith** [comment] 2018-12-10 10:21
Hi @maofree,

I did not manage to reproduce the issue with PS1.7.5.0rc1build2 & PS1.7.4.0 & PayPal v4.4.2.
It is OK.
Thanks!

**Comment by Maofree** [comment] 2018-12-10 10:46
Hi
tested again today, and I cannot join paypal to the module like the last time.
![1](https://user-images.githubusercontent.com/653230/49727540-cbc4a900-fc70-11e8-88b2-c7e609237e30.png)
![2](https://user-images.githubusercontent.com/653230/49727543-cbc4a900-fc70-11e8-90cf-d1719e83958e.png)

the first page can be ok, after that I get the default paypal's login
I install the module, then push on the active button and then go to paypal's site. I remember that now it is no more present the country selection.
I pass you the admin of this site to try a test

bye

**Comment by khouloudbelguith** [comment] 2018-12-10 11:04
Hi @maofree,

Can you please contact directly to PayPal via
email in this address: PPpbBTsupport@paypal.com to resolve your issue.
Thank you!

**Comment by Maofree** [comment] 2018-12-10 11:06
ok

**Comment by Maofree** [comment] 2018-12-11 12:41
Hi @khouloudbelguith 
I tried other tests
the problem is on prestashop or in the module
from the first login it is no more present the country selection like 3 weeks ago
with the previous email now has the same problem, I cannot get the authorization from paypal
202commerce said me the same thing to contact paypal, but it has no sense

the country selection is no more present, the problem is this
who manage this this?

![1](https://user-images.githubusercontent.com/653230/49801457-87a5d700-fd4a-11e8-9f7c-bed634212b15.png)

it should be like this (with sandbox it is ok)
![2](https://user-images.githubusercontent.com/653230/49801511-ac9a4a00-fd4a-11e8-92c0-0f239070cf87.png)

**Comment by khouloudbelguith** [comment] 2018-12-11 14:00
Hi @maofree,

Thanks for your feedback.
In my case, it is Ok.
I attached a video record
https://drive.google.com/file/d/1rpQBQrzUbL8YL8IoQD7_sMkuJGEsXJNv/view
Thanks to check & feedback.

**Comment by Maofree** [comment] 2018-12-11 17:25
Hi
problem solved, it was due from my browser
using the private navigation in google chrome I can get the country selection and I can join paypal to the module
it can be useful with others

thanks

**Comment by khouloudbelguith** [comment] 2018-12-12 08:38
@maofree, since it is fixed, can I close the issue?
Thanks!

**Comment by Maofree** [comment] 2018-12-12 08:45
yes
thanks

**Comment by khouloudbelguith** [comment] 2018-12-12 08:55
@maofree, feel free to open a new issue when needed.
Have a great day!

**Closed as completed by khouloudbelguith** 2018-12-12 08:55 UTC
Labels: Bug, Major, BO, Modules, No change required

**Comment by pkirk** [comment] 2019-08-30 19:46
Lost a couple of hours to that. Using private navigation/incognito mode resolved. F**k PayPal.

**Comment by ttoine** [comment] 2019-09-02 09:21
please stay polite.
