### ISSUE TITLE
Wrong shipping vat calculation on redeem & purchase of a voucher without shipping

### ISSUE THREAD

**Issue by CatchMeZZo** [PrestaShop/PrestaShop#17378] opened 2020-01-27 22:18 UTC
Redeeming a "premium gift voucher" reduces the total value and vat. Unfortunately, the vat has to be fully calculated on Redeeming if the customer has purchased a voucher with 0%. Otherwise this would be tax evasion. 

-> If I sell a premium gift voucher in germany. I sell it to 0% VAT.-> Why? Easy!
-> Because this time it is not clear at which products the customer will be bought with the premium gift voucher. So far so clear!
-> Now the customer buys products at 7% and 19% VAT and want to redeems his premium gift voucher. Problem? Paying attention now!
-> Let's say the customer have 50 Euro in the shopping cart and he want to redeem it with his 50 Euro premium gift card. After purchasing, prestashop will generate an invoice with a total of 0 euros. That's right... BUT!!!!! the VATs of the total must be calculated in the invoice and should not be set to 0 euros! That would be tax evasion and illegal!!!
-> It must not be treated like a simple coupon (price reduction)! The total amount must be taxed with a premium gift voucher.

Even when redeeming the shipping vat is calculated incorrectly. See my screenshot!

**Screenshots**
[https://imgur.com/a/6XVudi2](https://imgur.com/a/6XVudi2)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-01-28 08:45
Hi @CatchMeZZo,

Thanks for your report.
I tried with PS1.7.6.3 & similar prices & it is OK.
![image](https://user-images.githubusercontent.com/16067358/73248037-7fa93080-41b2-11ea-8f77-6bcb180ec7ec.png)
Could you please add steps to reproduce the issue in a new comment.
1. Did you create a cart rule gift?
![image](https://user-images.githubusercontent.com/16067358/73248151-b67f4680-41b2-11ea-8924-e46c343e8b49.png)
2. Did you use a custom module?
![image](https://user-images.githubusercontent.com/16067358/73248218-d7e03280-41b2-11ea-8fa4-4f92b2a4a68a.png)
what is the exact name of this module?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-27 07:58
Hi @CatchMeZZo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-27 07:58 UTC
Labels: Bug, Invoices, Discounts, Taxes and Prices, No change required, 1.7.6.3
