### ISSUE TITLE
blockreassurance module: non-svg custom icon is hidden in FO after editing in BO

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#29134] opened 2022-07-22 04:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

**New** non-svg icon **added** via Upload file shows well in FrontOffice after First Save in BackOffice, then disappears in FrontOffice after Second Edit Save.
![blockreassurance_newIcon_database](https://user-images.githubusercontent.com/3759923/180364402-67ca0468-6f0c-40ec-b65d-709c06d59257.png)
Database checking shows that image source is stored in `custom_icon` column at first, then is moved to `icon` column later.
![blockreassurance_editTitle_database](https://user-images.githubusercontent.com/3759923/180364427-764090e3-b4fa-4540-b459-ee97527df2c0.png)

### Expected behavior

The icon must be showed in FO after **later** Save as it is in FO after **first** Upload and Save.

### Steps to reproduce

1. Edit any row in **Block Content** listing of module configure (I choose id=1 in the screenshots)
2. Add a new **non-svg** image via **or upload file**, then Save; check FO to see the icon is there.
3. Edit the **above** row in Block Content listing of module configure **again**
4. Change something in title or description, then Save; check FO to see the icon is **not** there.
5. Any Edit and Save after that won't help to bring the icon back in FO, except Modify (svg) icon or Upload (new) file.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockreassurance v5.1.1

**Comment by sLorenzini** [comment] 2022-07-22 14:08
Hello @leemyongpakvn,

I reproduce the issue with: 
- PrestaShop version 8.0.0 / 1.7.8.6 / 1.7.7.8
- Blockreassurance version 5.1.1 / develop branch.

https://user-images.githubusercontent.com/2854834/180456753-f26574c7-36c5-49a7-8d92-48b9c14398e8.mp4


However, I can't reproduce it with the 5.0.0 version of the module in 1.7.8.3 version of PrestaShop:

![non-svg-reassurance-after-edition](https://user-images.githubusercontent.com/2854834/180456367-57fee397-2eba-4128-9612-380080097220.png)

It's a regression of the module. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by leemyongpakvn** [comment] 2022-07-22 14:59
@sLorenzini this issue happens after Release 5.1.1 with many commits especially these two:
[AdminBlockListingController.php line 167](https://github.com/PrestaShop/blockreassurance/pull/386/files#diff-eaed6bcd7e7ebf263bbaa48a45491889bf8de557a9241e6fb00264514289e73cL167)
and 
[_dev/front/index.js](https://github.com/PrestaShop/blockreassurance/pull/386/files#diff-283a0021afa358f618ceb66b9582913f0a2b89f3dffec4502166b5cdc2be11c7R56-L57)
of @Progi1984 
And it maybe related to #28256 where icon source was moved back and forth between `icon` and `custom_icon` columns

**Closed as completed** 2022-08-12 12:16 UTC
Labels: Bug, Minor, Regression, Fixed, Blockreassurance, 1.7.7.8, Verified, Module
