### ISSUE TITLE
Shipping cost is not recalculated when changing currency in the order

### ISSUE THREAD

**Issue by weddingtextile** [PrestaShop/PrestaShop#11413] opened 2018-11-15 21:14 UTC
**Describe the bug**
If you change the currency in the order, the cost of delivery is not recalculated based on the exchange rate.

**Additionnal information**
PrestaShop version: 1.7.4.3

**Comment by Rolige** [comment] 2018-11-15 21:27
Hi @weddingtextile,

I think this is a particular error in your store, I have tested and I'm not able to reproduce the error.

Try turning on the debug mode in **Advanced Parameters > Performance** and open the console of your browser to see if it gives you an error that helps you to find a solution.

**Comment by khouloudbelguith** [comment] 2018-11-16 07:52
Hi @weddingtextile,

I did not manage to reproduce the issue either.
I attached a video record: https://drive.google.com/file/d/1yty0GaXSl1EwTUyetxWnDBVRQ1Q9Rbl1/view
To provide us with more info you can follow this article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by weddingtextile** [comment] 2018-11-16 09:03
Strange, the problem disappeared.
The problem was 100% and it occurred on several orders.
I don’t know if it will help to find the problem, but the only thing that was changed in the system is that the Handling charges (Shipping/Preferences) set and saved $ 1.5, after which the value was again changed to 0.

**Comment by weddingtextile** [comment] 2018-11-16 09:15
![carrier1](https://user-images.githubusercontent.com/44600313/48612189-e321b680-e990-11e8-90f5-47bfc27d7310.jpg)
![carrier2](https://user-images.githubusercontent.com/44600313/48612190-e321b680-e990-11e8-8d02-fc7de7a701ac.jpg)

**Comment by weddingtextile** [comment] 2018-11-16 09:28
Initially, the currency in the order was a dollar. Then the currency was changed to hryvnia, as a result, the value of Shipping cost did not change, but the currency sign changed to UAH.
Now I can not reproduce the problem.

**Comment by khouloudbelguith** [comment] 2018-11-16 09:38
@weddingtextile, I checked again the issue, but I did not manage to reproduce the issue.
https://drive.google.com/file/d/1d0_QP28CFWhxjwsaJ1YAbRkcSyuN_ryv/view
Since you can't reproduce it either, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-16 09:38 UTC
Labels: Bug, FO, Can't reproduce, Shipping, 1.7.4.3
