### ISSUE TITLE
Spinner element colors have reversed names

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25116] opened 2021-06-24 09:53 UTC
#### Describe the bug
https://build.prestashop.com/prestashop-ui-kit/?path=/story/spinner--spinner

light spinner is dark
dark spinner is light

#### Expected behavior
light spinner is light
dark spinner is dark

#### Steps to Reproduce
1. Open any modern page in Prestashop backoffice.
2. Insert this code via dev tools - `<div class="spinner spinner-light"></div><div class="spinner spinner-dark"></div>`
3. See

**Screenshots**
![Výstřižek](https://user-images.githubusercontent.com/6097524/123242843-b76cf280-d4e2-11eb-8f3f-67381cf4431c.JPG)

ping @prestascott

**Comment by florine2623** [comment] 2021-06-24 10:14
Hello @Hlavtox ,

I was able to reproduce the issue with PrestaShop version 1.7.7.x, 1.7.8.x and develop, so I can confirm that this behaviour is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by prestascott** [comment] 2021-06-24 14:36
Hello @Hlavtox,

Maybe it was reversed because of the purpose of the spinner. 
For example, naming the light spinner as "dark spinner" because of the dark mode. But there is actually no dark mode. 

Otherwise, it's good to me 👍

**Comment by hibatallahAouadni** [comment] 2021-06-25 09:06
So, @prestascott & @NeOMakinG  is it a bug or this is the expected behavior?

**Comment by prestascott** [comment] 2021-06-25 11:31
@hibatallahAouadni It's an improvement to me ^^

**Comment by NeOMakinG** [comment] 2021-06-25 12:53
I think it's an improvement too, even it if it sounds like a bug :p

**Closed as completed** 2021-07-01 07:56 UTC
Labels: Improvement, UX ✔️, Trivial, BO, Fixed, Front-end, 1.7.6.7, 1.7.7.5
