### ISSUE TITLE
No create a good Sitemap 

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#18487] opened 2020-04-07 08:59 UTC
V 4.10 on PS 1.7.6.4, does not work at all, here is the CRON.PHP sitemap it creates:

<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://popup-mode.com/1_fr_0_sitemap.xml</loc><lastmod>2020-03-27T02:30:03+01:00</lastmod></sitemap></sitemapindex>
That's all, No other file created.

If i launch in the generate link in the module, all is OK

A clear and concise description of what went wrong.

#### Expected behavior

2 files, one index and one with list pages.

#### Steps to Reproduce

1. Go to 'https://popup-mode.com/1_index_sitemap.xml'

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3
![Capture](https://user-images.githubusercontent.com/61431435/78650227-e9367100-78be-11ea-844d-981717124373.JPG)

**Comment by khouloudbelguith** [comment] 2020-04-07 09:12
Hi @ECC64,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your PHP version, check, and feedback.

**Comment by ECC64** [comment] 2020-04-07 09:43
Hello,
Thank you for your speed answer, but i change the PHP version to 7.2 and the problem is same.
When i click in the module on éGenerate Sitemap" the file is good, but if i launch le CRON.PHP, the file is broken.
Best regards
Patrick

**Comment by khouloudbelguith** [comment] 2020-04-07 09:48
@ECC64, I think, it is similar to your issue: https://github.com/PrestaShop/PrestaShop/issues/17173#issuecomment-581909481 which fixed in this PR: https://github.com/PrestaShop/gsitemap/pull/127/files

Thanks to check and feedback.

**Comment by ECC64** [comment] 2020-04-07 09:57
Hello,
It is the same thing.
The problem is with GSITEMAP_CRON, and the error of Chrome is : HTTP Error 500
Best regards
Patrick

**Comment by khouloudbelguith** [comment] 2020-04-07 10:06
@ECC64,

Here's the PR: https://github.com/PrestaShop/gsitemap/pull/127 to fix the issue.
Your ticket is a duplicate of #16991
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-07 10:06
Duplicate of #16991

**Closed as completed by khouloudbelguith** 2020-04-07 10:06 UTC
Labels: Bug, BO, Duplicate, Google sitemap, 1.7.6.4
