### ISSUE TITLE
facetedsearch don't display depending of countrie

### ISSUE THREAD

**Issue by n-e-r-u** [PrestaShop/PrestaShop#24841] opened 2021-06-07 11:18 UTC
#### Describe the bug

When customers use a specific country (Nouvelle-Calédonie) the product on categorie page are not displayed. If we deactivate faceted search, the products are displaying.

#### Expected behavior

The products have to be visible in all cases. There is no restriction in back office.

#### Steps to Reproduce

1. Go to https://coudreetbroder.com
2. Create an account and put an adress in france and another one in New Caledonia
3. Go to Machines à coudre

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-06-07 16:13
Hello @n-e-r-u 

I tried to add the pack of this country New Caledonia in BO, but I couldn't found it.
Could you please provide some screenshots or explain how to import this country.
Please check and feedback.

Thanks!

**Comment by n-e-r-u** [comment] 2021-06-08 07:03
Hello @hibatallahAouadni 

In International > Geographic Zone we have a zone named Outre mer (it's for island attached to France like Polynesia or New Caledonia)

![image](https://user-images.githubusercontent.com/12851944/121138742-4b2e9580-c838-11eb-92e7-8d16ea8ccd0d.png)
![image](https://user-images.githubusercontent.com/12851944/121138812-5c77a200-c838-11eb-9dce-637d06bb401b.png)

**Comment by florine2623** [comment] 2021-06-11 12:56
Hello @n-e-r-u ,

I can't reproduce your issue in PS 1.7.6.x using module ps_facetedsearch v3.7.1.
**In customer account France :**
<img width="351" alt="Screenshot 2021-06-11 at 14 48 13" src="https://user-images.githubusercontent.com/16019289/121689278-b42a3d80-cac4-11eb-80a6-820e3cb10614.png">
<img width="1153" alt="Screenshot 2021-06-11 at 14 49 22" src="https://user-images.githubusercontent.com/16019289/121689288-b8eef180-cac4-11eb-8024-008bec5005a7.png">

**In customer account New-Caledonia :**
<img width="357" alt="Screenshot 2021-06-11 at 14 48 38" src="https://user-images.githubusercontent.com/16019289/121689256-ae345c80-cac4-11eb-99cb-3c8d08195cdf.png">
<img width="1136" alt="Screenshot 2021-06-11 at 14 49 43" src="https://user-images.githubusercontent.com/16019289/121689264-b12f4d00-cac4-11eb-9416-1ae51e29ed6a.png">

On both cases with module Faceted Search i can see my product.
Can you check if you have any overrides ?

**Comment by hibatallahAouadni** [comment] 2021-07-01 10:57
Hello @n-e-r-u 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-01 10:57 UTC
Labels: Bug, FO, Countries, Faceted search, No change required, 1.7.6.x
