### ISSUE TITLE
1.7.6 dashboard many decimals in amounts

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#14614] opened 2019-07-12 11:11 UTC
After updating to 1.7.6 from 1.7.5.2 I discovered that the amount of additionals decimals in the dashboard and stats are in some cases more than 2. 

<img width="186" alt="Screenshot 2019-07-12 at 12 08 21" src="https://user-images.githubusercontent.com/46492443/61124056-d3199280-a49d-11e9-8efd-ecde75c6b392.png">

<img width="125" alt="Screenshot 2019-07-12 at 11 53 44" src="https://user-images.githubusercontent.com/46492443/61124063-d745b000-a49d-11e9-8b04-9236272931f4.png">

Prestashop 1.7.6 multistore
Server software version: Apache
PHP version: 7.2.20
Memory limit: 6000M
Max execution time: 600
MySQL version: 10.2.25-MariaDB
Upload Max File size: 250M

**Comment by 01park** [comment] 2019-07-12 11:53
I fixed this problem by changing in PS_currency the decimals to 2, instead of 6. Now it showing correct in dashboard.

<img width="435" alt="Screenshot 2019-07-12 at 12 52 23" src="https://user-images.githubusercontent.com/46492443/61126283-f6dfd700-a4a3-11e9-9abe-fc4054987fb9.png">

**Comment by khouloudbelguith** [comment] 2019-07-12 11:54
Hi @01park,

Thanks for your report.
I did not manage to reproduce the issue with fresh installation PS1.7.6.0 & PS1.7.6.0 after upgrade from PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/61125442-bf702b00-a4a1-11e9-8f71-a886e33b8729.png)

Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-12 11:54 UTC
Labels: No change required

**Comment by gorkij77** [comment] 2019-08-25 18:54
> I fixed this problem by changing in PS_currency the decimals to 2, instead of 6. Now it showing correct in dashboard.
> 
> <img alt="Screenshot 2019-07-12 at 12 52 23" width="435" src="https://user-images.githubusercontent.com/46492443/61126283-f6dfd700-a4a3-11e9-9abe-fc4054987fb9.png">

Pardon my necromancy, but where did you set this?

**Comment by 01park** [comment] 2019-08-25 19:15
@gorkij77  you need to change it in the database - table PS_CURRENCY

**Comment by gorkij77** [comment] 2019-08-25 19:21
> @gorkij77 you need to change it in the database - table PS_CURRENCY

Ah, so you set the precision to 2 for the main currency?

**Comment by 01park** [comment] 2019-08-25 19:36
I set all currencies to 2

**Comment by gorkij77** [comment] 2019-08-25 19:38
Thanks! I'd leave the other currencies since that's used to calculate exchange rates, but if you don't have international customers that's probably a moot issue.

**Comment by 01park** [comment] 2019-08-25 19:56
@gorkij

In my case, when I change the precision to 6 my front office price also has 6 decimals. For this reason, I set all to 2.
