### ISSUE TITLE
Docker-compose up failed after clone develop branch

### ISSUE THREAD

**Issue by slawomirlewczyk** [PrestaShop/PrestaShop#26827] opened 2021-12-01 21:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

Just wanna run PrestaShop via docker on fresh install Ubuntu 20.04, so:
```
git clone https://github.com/PrestaShop/PrestaShop.git
cd PrestaShop
docker-compose up
```
Then:

```
Building prestashop-git
Sending build context to Docker daemon  665.5MB
Step 1/13 : FROM prestashop/prestashop-git:latest
 ---> f7840770fd3f
Step 2/13 : ARG GROUP_ID
 ---> Using cache
 ---> 1ca3223c9ac7
Step 3/13 : ARG USER_ID
 ---> Using cache
 ---> 037a199e1262
Step 4/13 : RUN groupmod -g $GROUP_ID www-data   && usermod -u $USER_ID -g $GROUP_ID www-data
 ---> Using cache
 ---> a4f8018d3ea6
Step 5/13 : COPY .docker/wait-for-it.sh /tmp/
 ---> Using cache
 ---> a643ac6fa95d
Step 6/13 : COPY .docker/docker_run_git.sh /tmp/
 ---> Using cache
 ---> b6983c4a48d0
Step 7/13 : RUN mkdir -p /var/www/.npm
 ---> Using cache
 ---> bfc3cb47493f
Step 8/13 : RUN chown -R www-data:www-data /var/www/.npm
 ---> Using cache
 ---> ca57ba44af83
Step 9/13 : RUN mkdir -p /var/www/.composer
 ---> Using cache
 ---> 6d1a6cf81b25
Step 10/13 : RUN chown -R www-data:www-data /var/www/.composer
 ---> Using cache
 ---> 33fcf7f91792
Step 11/13 : RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
 ---> Running in d3ed0c68a73e

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.

## Installing packages required for setup: lsb-release gnupg...

+ apt-get install -y lsb-release gnupg > /dev/null 2>&1
Error executing command, exiting
The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_14.x | bash -' returned a non-zero code: 1
ERROR: Service 'prestashop-git' failed to build : Build failed
```

### Expected behavior

Containers running.

### Steps to reproduce

Step 1. git clone https://github.com/PrestaShop/PrestaShop.git
Step 1a. git clone -b 1.7.8.x https://github.com/PrestaShop/PrestaShop.git
Step 2. cd PrestaShop
Step 3. docker-compose up

### PrestaShop version(s) where the bug happened

develop / 1.7.8.x

**Comment by hibatallahAouadni** [comment] 2021-12-02 11:15
Hello @slawomirlewczyk 

> git clone -b 1.7.8.x https://github.com/PrestaShop/PrestaShop.git

I think you mean:
`git checkout -b 1.7.8.x origin/1.7.8.x`
Is that so? so you an error when you execute `docker-compose up` in **`1.7.8.x`** branch?
Please check and feedback.

Thanks!

**Comment by krekken** [comment] 2021-12-02 12:01
i got exited with code 1 too
![image](https://user-images.githubusercontent.com/58357424/144417749-36f894d9-a487-43a1-94d7-ddc7022e9a57.png)
i used a docker-compose.yml-file
this:
```yml
version: "3"

services:
  web:
    image: "prestashop/prestashop:1.7.8.1"
    ports:
      - "8080:80"
    environment:
      - PS_DEV_MODE=1
      - XDEBUG_CONFIG
      - PS_INSTALL_AUTO=1
      - PS_FOLDER_ADMIN=admin1234
      - PS_FOLDER_INSTALL=installNeedToBeRenamed
      - ADMIN_MAIL=admin@shop.com
      - ADMIN_PASSWD=admin1234
      - DB_SERVER=database
      - PS_INSTALL_DB=1
      - PS_ERASE_DB=1
    networks:
      - network
    volumes:
      - .:/var/www/html/

  database:
    # MySQL 5.7 is recommended for the Docker version
    # https://hub.docker.com/r/prestashop/prestashop/
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - network

networks:
  network:
```
and used
```bash
sudo docker-compose up
```

i tried it with 1.7.7.8 as well, and it exited with code 1 too, although a bit differently
![image](https://user-images.githubusercontent.com/58357424/144418265-095e63d4-4c82-456c-8730-00fadb4c76cc.png)

**Comment by hibatallahAouadni** [comment] 2021-12-02 16:15
@krekken That's caused by this issue #26838

**Comment by slawomirlewczyk** [comment] 2021-12-02 17:23
@hibatallahAouadni 

Already test 1.7.8.x

`git checkout -b 1.7.8.x origin/1.7.8.x`
`* 1.7.8.x`

Still same error.

**Comment by hibatallahAouadni** [comment] 2021-12-06 14:35
@slawomirlewczyk Could you please try again :pray: This issue #26838 has been fixed.
Please chech and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-13 14:31
Hello @slawomirlewczyk 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17479. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-13 14:31
Duplicate of #17479

**Closed as completed by hibatallahAouadni** 2021-12-13 14:31 UTC
Labels: Bug, CO, Duplicate, 1.7.8.x, Invalid

**Comment by globalworming** [comment] 2023-03-02 11:01
@hibatallahAouadni The fist message mentions :red_circle:  `The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_14.x | bash -' returned a non-zero code: 1` and that's exactly what i am getting.

I cloned this repository and ran docker-compose up resulting in the error @slawomirlewczyk saw. I added some outputting to the scripts and this is what i got:

```
Selecting previously unselected package python3.9-minimal.
Preparing to unpack .../python3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking python3.9-minimal (3.9.2-1) ...
Setting up libpython3.9-minimal:amd64 (3.9.2-1) ...
Setting up python3.9-minimal (3.9.2-1) ...
Traceback (most recent call last):
File "/usr/lib/python3.9/py_compile.py", line 215, in <module>
  sys.exit(main())
File "/usr/lib/python3.9/py_compile.py", line 207, in main
  compile(filename, doraise=True)
File "/usr/lib/python3.9/py_compile.py", line 172, in compile
  importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
File "<frozen importlib._bootstrap_external>", line 126, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/__pycache__/__future__.cpython-39.pyc.140701931754416'
dpkg: error processing package python3.9-minimal (--configure):
installed python3.9-minimal package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
python3.9-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error executing command, exiting
+ bail
+ echo 'Error executing command, exiting'
+ exit 1
The command '/bin/sh -c bash -x /tmp/install_node.sh' returned a non-zero code: 1
ERROR: Service 'prestashop-git' failed to build : Build failed
`docker-compose` process finished with exit code 1
```

<details>
  <summary>full docker compose output</summary>
  
  ```
Creating network "prestashop_default" with the default driver
Building prestashop-git
Sending build context to Docker daemon  721.9MB
Step 1/17 : ARG VERSION
Step 2/17 : FROM prestashop/base:$VERSION
 ---> 6ee378bcceac
Step 3/17 : ARG GROUP_ID
 ---> Using cache
 ---> 3bfa1f6efae2
Step 4/17 : ARG USER_ID
 ---> Using cache
 ---> 5449e6cbd489
Step 5/17 : RUN groupmod -g $GROUP_ID www-data   && usermod -u $USER_ID -g $GROUP_ID www-data
 ---> Using cache
 ---> 1f576fc3f4f1
Step 6/17 : COPY .docker/wait-for-it.sh /tmp/
 ---> Using cache
 ---> f0d4bfcc51f3
Step 7/17 : COPY .docker/docker_run_git.sh /tmp/
 ---> Using cache
 ---> 1a1d07797400
Step 8/17 : COPY .docker/install_node.sh /tmp/
 ---> 7373f8dff995
Step 9/17 : RUN mkdir -p /var/www/.npm
 ---> Running in e7bf36fbf736
Removing intermediate container e7bf36fbf736
 ---> 2b7f0efc6441
Step 10/17 : RUN chown -R www-data:www-data /var/www/.npm
 ---> Running in 1903b49c6421
Removing intermediate container 1903b49c6421
 ---> fa1c38cdea6d
Step 11/17 : RUN mkdir -p /var/www/.composer
 ---> Running in ba707bfb4f15
Removing intermediate container ba707bfb4f15
 ---> e39a97fbe1c8
Step 12/17 : RUN chown -R www-data:www-data /var/www/.composer
 ---> Running in f50e0a09695f
Removing intermediate container f50e0a09695f
 ---> c859c2252463
Step 13/17 : RUN bash -x /tmp/install_node.sh
 ---> Running in ddf1ccb22895
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ SCRSUFFIX=_14.x
+ NODENAME='Node.js 14.x'
+ NODEREPO=node_14.x
+ NODEPKG=nodejs
+ test -t 1
+ setup
+ script_deprecation_warning
+ '[' X_14.x == X ']'
+ node_deprecation_warning
+ [[ XNode.js 14.x == \X\i\o\.\j\s\ \1\.\x ]]
+ [[ XNode.js 14.x == \X\i\o\.\j\s\ \2\.\x ]]
+ [[ XNode.js 14.x == \X\i\o\.\j\s\ \3\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \0\.\1\0 ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \0\.\1\2 ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \4\.\x\ \L\T\S\ \A\r\g\o\n ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \5\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \6\.\x\ \L\T\S\ \B\o\r\o\n ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \7\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \8\.\x\ \L\T\S\ \C\a\r\b\o\n ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \9\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \1\0\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \1\1\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \1\2\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \1\3\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \1\5\.\x ]]
+ [[ XNode.js 14.x == \X\N\o\d\e\.\j\s\ \1\7\.\x ]]
+ print_status 'Installing the NodeSource Node.js 14.x repo...'
+ echo
+ echo '## Installing the NodeSource Node.js 14.x repo...'
+ echo

## Installing the NodeSource Node.js 14.x repo...

++ uname -m
++ grep -Eq '^armv6'
+ PRE_INSTALL_PKGS=
+ '[' '!' -e /usr/lib/apt/methods/https ']'
+ '[' '!' -x /usr/bin/lsb_release ']'
+ PRE_INSTALL_PKGS=' lsb-release'
+ '[' '!' -x /usr/bin/curl ']'
+ '[' '!' -x /usr/bin/gpg ']'
+ PRE_INSTALL_PKGS=' lsb-release gnupg'
+ print_status 'Populating apt-get cache...'

## Populating apt-get cache...

+ apt-get update
+ echo
+ echo '## Populating apt-get cache...'
+ echo
+ exec_cmd 'apt-get update'
+ exec_cmd_nobail 'apt-get update'
+ echo '+ apt-get update'
+ bash -c 'apt-get update'
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [229 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Fetched 8635 kB in 2s (4480 kB/s)
Reading package lists...
+ '[' 'X lsb-release gnupg' '!=' X ']'
+ print_status 'Installing packages required for setup: lsb-release gnupg...'
+ echo
+ echo '## Installing packages required for setup: lsb-release gnupg...'
+ echo
+ exec_cmd 'apt-get install -y lsb-release gnupg'
+ exec_cmd_nobail 'apt-get install -y lsb-release gnupg'
+ echo '+ apt-get install -y lsb-release gnupg'
+ bash -c 'apt-get install -y lsb-release gnupg'

## Installing packages required for setup: lsb-release gnupg...

+ apt-get install -y lsb-release gnupg
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  dirmngr distro-info-data gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client
  gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libmpdec3 libnpth0
  libpython3-stdlib libpython3.9-minimal libpython3.9-stdlib pinentry-curses
  python3 python3-minimal python3.9 python3.9-minimal
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage
  scdaemon pinentry-doc python3-doc python3-tk python3-venv python3.9-venv
  python3.9-doc binfmt-support
The following NEW packages will be installed:
  dirmngr distro-info-data gnupg gnupg-l10n gnupg-utils gpg gpg-agent
  gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libmpdec3
  libnpth0 libpython3-stdlib libpython3.9-minimal libpython3.9-stdlib
  lsb-release pinentry-curses python3 python3-minimal python3.9
  python3.9-minimal
0 upgraded, 24 newly installed, 0 to remove and 33 not upgraded.
Need to get 12.8 MB of archives.
After this operation, 35.6 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-minimal amd64 3.9.2-1 [801 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 python3.9-minimal amd64 3.9.2-1 [1955 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 python3-minimal amd64 3.9.2-3 [38.2 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 libmpdec3 amd64 2.5.1-1 [87.7 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-stdlib amd64 3.9.2-1 [1684 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 python3.9 amd64 3.9.2-1 [466 kB]
Get:7 http://deb.debian.org/debian bullseye/main amd64 libpython3-stdlib amd64 3.9.2-3 [21.4 kB]
Get:8 http://deb.debian.org/debian bullseye/main amd64 python3 amd64 3.9.2-3 [37.9 kB]
Get:9 http://deb.debian.org/debian bullseye/main amd64 libassuan0 amd64 2.5.3-7.1 [50.5 kB]
Get:10 http://deb.debian.org/debian bullseye/main amd64 gpgconf amd64 2.2.27-2+deb11u2 [548 kB]
Get:11 http://deb.debian.org/debian-security bullseye-security/main amd64 libksba8 amd64 1.5.0-3+deb11u2 [123 kB]
Get:12 http://deb.debian.org/debian bullseye/main amd64 libnpth0 amd64 1.6-3 [19.0 kB]
Get:13 http://deb.debian.org/debian bullseye/main amd64 dirmngr amd64 2.2.27-2+deb11u2 [763 kB]
Get:14 http://deb.debian.org/debian bullseye/main amd64 distro-info-data all 0.51+deb11u3 [7812 B]
Get:15 http://deb.debian.org/debian bullseye/main amd64 gnupg-l10n all 2.2.27-2+deb11u2 [1086 kB]
Get:16 http://deb.debian.org/debian bullseye/main amd64 gnupg-utils amd64 2.2.27-2+deb11u2 [905 kB]
Get:17 http://deb.debian.org/debian bullseye/main amd64 gpg amd64 2.2.27-2+deb11u2 [928 kB]
Get:18 http://deb.debian.org/debian bullseye/main amd64 pinentry-curses amd64 1.1.0-4 [64.9 kB]
Get:19 http://deb.debian.org/debian bullseye/main amd64 gpg-agent amd64 2.2.27-2+deb11u2 [669 kB]
Get:20 http://deb.debian.org/debian bullseye/main amd64 gpg-wks-client amd64 2.2.27-2+deb11u2 [524 kB]
Get:21 http://deb.debian.org/debian bullseye/main amd64 gpg-wks-server amd64 2.2.27-2+deb11u2 [516 kB]
Get:22 http://deb.debian.org/debian bullseye/main amd64 gpgsm amd64 2.2.27-2+deb11u2 [645 kB]
Get:23 http://deb.debian.org/debian bullseye/main amd64 gnupg all 2.2.27-2+deb11u2 [825 kB]
Get:24 http://deb.debian.org/debian bullseye/main amd64 lsb-release all 11.1.0 [27.9 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 12.8 MB in 1s (10.1 MB/s)
Selecting previously unselected package libpython3.9-minimal:amd64.
(Reading database ... 15468 files and directories currently installed.)
Preparing to unpack .../libpython3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking libpython3.9-minimal:amd64 (3.9.2-1) ...
Selecting previously unselected package python3.9-minimal.
Preparing to unpack .../python3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking python3.9-minimal (3.9.2-1) ...
Setting up libpython3.9-minimal:amd64 (3.9.2-1) ...
Setting up python3.9-minimal (3.9.2-1) ...
Traceback (most recent call last):
  File "/usr/lib/python3.9/py_compile.py", line 215, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/py_compile.py", line 207, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.9/py_compile.py", line 172, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 126, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/__pycache__/__future__.cpython-39.pyc.139912877278128'
dpkg: error processing package python3.9-minimal (--configure):
 installed python3.9-minimal package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python3.9-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
+ bail
+ echo 'Error executing command, exiting'
+ exit 1
Error executing command, exiting
The command '/bin/sh -c bash -x /tmp/install_node.sh' returned a non-zero code: 1
ERROR: Service 'prestashop-git' failed to build : Build failed
`docker-compose` process finished with exit code 1

  ```
</details>

Any pointers what I might be doing wrong would be very appreciated.

**Comment by globalworming** [comment] 2023-03-02 11:20
nevermind, it's seems to be related to running docker from `snap` https://forums.docker.com/t/bug-on-apt-install-permission-denied/100196/7

removing from snap and installing according to https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository fixed the issue

**Comment by slawomirlewczyk** [comment] 2023-03-02 11:36
Hi, first check your docker installation, it has to be installed way by docs.docker.com/engine/install/ubuntu. Secondly, check internet access inside docker container, maybe u need to create/edit /etc/docker/daemon.json to setup DNS.

**Comment by globalworming** [comment] 2023-03-02 11:37
Thanks @slawomirlewczyk was able to resolve it, removing docker from snap and installing according to https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository fixed the issue

**Comment by slawomirlewczyk** [comment] 2023-03-02 11:40
Too slow typing, I apologize :)
