### ISSUE TITLE
list of products with combinations but without available quantities for sale

### ISSUE THREAD

**Issue by fall-en** [PrestaShop/PrestaShop#12876] opened 2019-03-11 21:26 UTC
In catalog monitoring/LIST OF PRODUCTS WITH COMBINATIONS BUT WITHOUT AVAILABLE QUANTITIES FOR SALE it is showing a product that have combination and available quantities for sale.

1. Create a product with 1 combination
2. in FO sell few time this product
3. In BO delete the combination (because the product combination it is no more available)
4. Set new combination with quantity

It will show the product as "with combination but without available quantities for sale" table in BO because the old combination it is still available in the database but not in BO. I think something goes wrong during the delete process.

As you can see in this screenshot I have deleted previous combination with 0 availabale quantity and created new one:
![BO quantity available](https://user-images.githubusercontent.com/48456655/54158758-88cec900-444b-11e9-96e2-c2c29819cf6c.PNG)

But still showing as combination without available quantities for sale. Also in ps_stock_available it still showing the old combination)
![DB ID 63](https://user-images.githubusercontent.com/48456655/54158842-bf0c4880-444b-11e9-8b89-badb03066fa3.PNG)

This happens sometime, not everytime, and only if you delete a combination with 0 available quantities. If you set at leat 1 quantity and delete the combination this issue does not occur

**Additionnal information**
PrestaShop version: 1.7.4.2
Server information Linux x86_64
Server software version: Apache
PHP version: 7.1.26
Memory limit: 1024M
Max execution time: 180
Upload Max File size: 150M

Can I delete the row in ps_stock_available or it will create issues?

**Comment by khouloudbelguith** [comment] 2019-03-12 08:17
Hi @fall-en,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12814
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-12 08:17
Duplicate of #12814

**Closed as completed by khouloudbelguith** 2019-03-12 08:17 UTC
Labels: Duplicate
