### ISSUE TITLE
SEO & URLs frontend bug

### ISSUE THREAD

**Issue by SimonasB88** [PrestaShop/PrestaShop#28144] opened 2022-04-06 07:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Seems like `button id` information is being duplicated in the `label classes` in the Titles of the fields, and Titles can have hover and click interactions.

https://user-images.githubusercontent.com/29095235/161923496-5aa94ebe-7861-49b6-86ad-149f9e0018d3.mp4

https://user-images.githubusercontent.com/29095235/161922513-ea4c3909-9232-4be2-a63e-2aceef9d2398.mp4

### Expected behavior

Shouldn't be any hover and click interactions on Titles.

### Steps to reproduce

1. Open CONFIGURE > Shop Parameters > Traffic & SEO > SEO & URLs tab
2. Editing / Creating any SEO page
3. Click on the label (for ex: Meta description) 
4. See error > the language select is opened and displayed

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment] 2022-04-06 15:16
Hello @SimonasB88 

I was able to reproduce the issue with PS1767, PS1778 and PS1785. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2022-04-14 14:58 UTC
Labels: Bug, Minor, BO, SEO & URLs, Fixed, Front-end, PR available, Forms BO, 1.7.6.7, Verified
