### ISSUE TITLE
 Unnecessary extra field for availability in faceted search 

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#29729] opened 2022-09-23 11:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 Hello!

I think I ran into a bug in Faceted Search module. My product stock filter looks like this (Im only using 1 language in my shop, Polish): 
![image png 5774210ddf92dfb21901eed46e63d57d](https://user-images.githubusercontent.com/60825638/191954086-8164cc46-aeb6-4264-8d34-a49a90389969.png)

 (Niedostepne = Unavailable, W magazynie = In stock)

So I'm getting proper fields in Polish, but there's also a random extra field and I've got no clue where is it coming from. Ive checked translations panel and while there are options of translating "In stock" and "Unavailable", there's no such field as "Available". Any ideas what might be wrong and how to fix it and remove the extra field? 

### Expected behavior

We should have Available or In Stock on left filter.

### Steps to reproduce

Go to Faceted Search module and set product condition filter.
Now on front we have two filters showing the same with other names. Available and In Stock

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.8.0

**Comment by Hlavtox** [comment] 2022-09-23 13:21
Hi @GTriber, this is a behavior I added, it allows to filter products really in stock, instead only by 'available when not in stock'.

**This is what those mean:**
| Availability | Meaning |
|------|-------|
| W magazynie | quantity > 1 |
| Available (Do dyspozycji) | quantity > 1 OR available for order when not in stock |
| Niedostępne | quantity < 1 AND not available for order when not in stock |

Do you think it should be adjusted, for example add some checkboxes with availabilities you want to show?
Also, I don't know why it's not translatable. 🤔

**Comment by GTriber** [comment] 2022-09-23 13:28
@Hlavtox Is not bad option but clients seems confused. 

On setting, we have set only one filter for it. Red on screen, that show the 3 statuses W magazynie / Available (Do dyspozycji) / Niedostępne
On settings there on more to set black on screen. Product state?
![Przechwytywanie zawartości sieci Web_23-9-2022_152523_sklep semperfi pl](https://user-images.githubusercontent.com/60825638/191970426-a3b9da5e-8930-475e-a8c3-490ded5d54d6.jpeg)

Either way. As for first on. Would be great to have this separate as in most cases W magazynie showing same numbers as  Available (Do dyspozycji).

Cheers

**Comment by Hlavtox** [comment] 2022-09-24 08:34
@GTriber They are the same only in your scenario, but the filter was unusable previously without this distinguishion.

My clients allow to order everything, even if not in stock.
So, everything was basically "in stock" before, and this filter was unusable.

___________________

"Filtr stanu produktu" is product condition filter - new/used/refurbished. That's a different thing.

**Comment by hibatallahAouadni** [comment] 2022-09-27 16:29
Hello @GTriber 

Thanks for your patience :pray: 
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28302. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @Hlavtox for your quick replies :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-09-27 16:29
Duplicate of #28302

**Closed as completed by hibatallahAouadni** 2022-09-27 16:29 UTC
Labels: Bug, Duplicate, Invalid
