### ISSUE TITLE
Mysql table missing after upgrade

### ISSUE THREAD

**Issue by papich06** [PrestaShop/PrestaShop#27464] opened 2022-01-25 19:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
i migrate my shop from 1.4 to 1.7.8.2 and after upgrade i have this message
`SQL 1.7.7.0 1146 in ALTER TABLE `xxx_pagenotfound` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'dbxx_pagenotfound' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `xx_statssearch` CHANGE `keywords` `keywords` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL: Table 'xxx_statssearch' doesn't `exist``

i don't have this tables how can i download them ? Why weren't they loaded during the migration?

why when i use the module "Nettoyage de PrestaShop" i can repare and optimize my database ?

thanks

### Steps to reproduce

I upgrade ps 1.4.5.2 to 1.7.8.2

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.25

**Comment by hibatallahAouadni** [comment] 2022-01-26 09:52
Hello @papich06 

You shouldn't upgrade from `1.4` to `1.7` :disappointed: because the PHP version **7.4** is not compatible with PS`1.4`.
So, if you could roll back to `1.4` and downgrade your PHP version to **5.2**, it will be great!
Then, upgrade your shop from `1.4.5.2` to `1.6.1.24` with PHP version **5.2**.
Upgrade your PHP version from **5.2** to **7.1**
Finally, upgrade your shop from `1.6.1.24` to `1.7.8.2`

Please check and feedback.
Thanks!

**Comment by papich06** [comment] 2022-01-26 10:21
Hello @hibatallahAouadni ,

sorry you right I had version 1.7.4.1 and 1.7.5.2

I managed to migrate to 1.7.8.2
Is there a module to check databases and compress them?

**Comment by hibatallahAouadni** [comment] 2022-01-26 10:46
Hello @papich06 

> Is there a module to check databases and compress them?

Check the https://addons.prestashop.com/ you may found one :wink: 
By the way, your issue seems duplicate of this one #22995
Could you please check and feedback.

Thanks!

**Comment by papich06** [comment] 2022-01-26 11:30
Hello @hibatallahAouadni,

It's the same problem but it's not solved.
I was telling you about this module which is no longer maintained, too bad

https://github.com/PrestaShop/pscleaner

**Comment by hibatallahAouadni** [comment] 2022-01-26 14:07
Hello @papich06 

Thanks for your feedback.
Closing this issue as we are aware of this issue and it is already in our debug backlog. 
This issue is a duplicate of #22995. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-26 14:08
Duplicate of #22995

**Closed as completed by hibatallahAouadni** 2022-01-26 14:07 UTC
Labels: Bug, BO, Duplicate, Autoupgrade, Invalid, Module
