### ISSUE TITLE
Error 500 on Suppliers View

### ISSUE THREAD

**Issue by Bulikus** [PrestaShop/PrestaShop#15733] opened 2019-09-27 11:11 UTC
**Describe the bug**
Hello, community!
I Migrated from Prestashop 1.6.1.8 to Prestashop 1.7.6.1 with Prestashop Migrator module (ETS-Soft) to a freshly installed Presta.
Everything seems to work fine, but today I tried to "VIEW" one of my suppliers.
On the supplier's page, after I push "VIEW" button error 500 occurred.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Catalog -> Brands&Suppliers -> Suppliers'
2. Click on 'View '
3. See error

**Screenshots**
https://youtu.be/SKKgOUBTDII
![2019-09-27_03-25-38](https://user-images.githubusercontent.com/11628875/65765356-b6056f00-e130-11e9-8606-a43e4af6c16d.png)
![2019-09-27_03-25-48](https://user-images.githubusercontent.com/11628875/65765357-b69e0580-e130-11e9-878a-f8851597a6d7.png)
![2019-09-27_03-25-57](https://user-images.githubusercontent.com/11628875/65765358-b69e0580-e130-11e9-83d8-f8462ac8cd1a.png)
![2019-09-27_03-26-06](https://user-images.githubusercontent.com/11628875/65765359-b69e0580-e130-11e9-884a-2ddf1d8844eb.png)
![2019-09-27_03-26-16](https://user-images.githubusercontent.com/11628875/65765360-b69e0580-e130-11e9-99eb-0733d3ef7d4e.png)
![2019-09-27_03-30-24](https://user-images.githubusercontent.com/11628875/65765361-b69e0580-e130-11e9-8e94-07602c028f62.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by lichesser** [comment] 2019-09-29 12:06
It looks like your new PrestaShop is missing a currency definition.

Maybe try adding a default currency like described in the following link 

https://zemez.io/prestashop/support/how-to/prestashop-1-7-manage-currencies-set-default-one/

**Comment by Bulikus** [comment] 2019-09-29 13:42
Unfortunately not. I got three languages and three currencies. And one of them from the beginning was my default currency.

**Comment by khouloudbelguith** [comment] 2019-09-30 10:30
Hi @Bulikus,

This issue occurs after deleting a currency.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15486
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-30 10:30
Duplicate of #15486

**Closed as completed by khouloudbelguith** 2019-09-30 10:30 UTC
Labels: Duplicate
