### ISSUE TITLE
Unable to run `composer create-test-db`

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/PrestaShop#24547] opened 2021-05-18 12:48 UTC
It is not possible to run Behat test on develop or in 1.7.8.x. 
Tests need a database to be run on. According to docs,  `composer create-test-db` is used to create test database.
But this command fails.

#### Expected behavior

Tests to be run.

#### Steps to Reproduce

1. Go to develop and pull the latest changes
2. run  `composer create-test-db`
3. See Error: Fatal error:  Uncaught PrestaShopException: Property Profile->name is empty

#### Additional information

* PrestaShop branches: develop, 1.7.8.x 
* PHP versions: 7.3, 7.2

**Comment by kpodemski** [comment] 2021-05-18 12:50
Hey @zuk3975 are you familiar with this error? You or @JevgenijVisockij had same one, right?

**Comment by matks** [comment] 2021-05-18 13:01
I also have this error in some conditions.

I noticed that when I work on `develop` branch and then switch to `1.7.8.x` branch (or reverse), I have this error. I then reinstall the software and it's fine.

**Comment by JevgenijVisockij** [comment] 2021-05-18 13:01
Hey. Yes I still have exactly this problem.
I don't remember the details, but something about test mode and doctrine not creating a database (or filling them with data) properly.

Nobody else was able to reproduce it until now so I fixed it by changing, `define('_PS_IN_TEST_', false);` to `define('_PS_IN_TEST_', true);` in `./tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php` line 44. (Use at your own risk).

**Comment by zuk3975** [comment] 2021-05-18 13:05
same for me, I get it sometimes, but usually I make it work by just repeating same command again (sometimes I change permissions locally and that helps, but I **do not recommend this**)

**Comment by hibatallahAouadni** [comment] 2021-05-18 14:05
Hello everyone,

I reproduce the issue too with 1.7.8.x and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/118664634-ed3aff00-b7f1-11eb-8ee2-57e862d15f04.png)

ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: with 1.7.7.x, I encountred another issue (about loadLanguages), I don't know if it's related or not :sweat_smile: 

Thanks!

**Comment by arouiadib** [comment] 2021-05-18 22:25
Thanks all of you guys @matks @JevgenijVisockij @zuk3975 for confirming this error exists.
Special thanks to @hibatallahAouadni who confirmed by reproducing it.

The last month, I tried many times just after pulling from 1.7.8.x and develop. I also switched php versions to no avail.

@JevgenijVisockij @zuk3975 Thanks for the tricks.

Since that I am happy to know that the problem happens to many, that I can't hire a specialist, and that I am not now hired either, I will attack asap.

Thanks.

**Comment by arouiadib** [comment] 2021-05-19 04:12
Update:

The problem is in the data fixtures; the xml loading process.

What is weird is that this same issue was fixed in the last commits of the two files `profile.xml` available in `data/xml` and `fixtures/fashion`.
I will be back here soon to continue; any insights are invaluable.

**Closed as completed** 2021-06-02 09:44 UTC
Labels: Bug, TE, develop, Minor, Regression, Fixed, 1.7.8.x

**Comment by arouiadib** [comment] 2021-06-02 22:08
Best community
