### ISSUE TITLE
Error 500 on POST delivery-settings with Cart Rule Category and FreeShipping Checked on order

### ISSUE THREAD

**Issue by lthienard** [PrestaShop/PrestaShop#27281] opened 2022-01-08 16:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

If I have a cart rule that offers a reduction on products of a certain category when I create an order with a product in this category and I check Free Shipping I get a **500 erro**r on the **POST delivery -settings** 

### Expected behavior

https://watch.screencastify.com/v/w8iLuH16ENHe3hLFhbWu

### Steps to reproduce

1. Create Cart Rule with -10% promotion for all customer on 2 category with a minimum purchase of 1500$
2. Create Order with a product of one of these category
3. Check the box for free shipping 

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-01-10 18:30
Hello @lthienard 

I didn't manage to reproduce the issue with PS1782, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/148819532-e5369c25-b6fb-4bbe-8e2f-5fdf18dad6ed.mp4

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-31 14:02
Hello @lthienard 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-31 14:02 UTC
Labels: Bug, BO, Order, Cart rules, Invalid
