### ISSUE TITLE
Prestashop Wish List does not show all items

### ISSUE THREAD

**Issue by Stefanr123** [PrestaShop/PrestaShop#32764] opened 2023-05-30 21:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Original Prestashop Wish List module doesn't show all wishlist items but you can see the number of wishlist items added.

I have 1.7.8.7 with PHP 7.4 and previously had to change the code in Wishlist/src/Search.

I had to insert the following because an article was shown to me three times:

$querySearch->from('product', 'p');
$querySearch->join(Shop::addSqlAssociation('product', 'p'));
$querySearch->innerJoin('wishlist_product', 'wp', 'wp.id_product = p.id_product');
$querySearch->leftJoin('category_product', 'cp', 'p.id_product = cp.id_product AND cp.id_category = product_shop.id_category_default');
Then I added the following sentence:
$querySearch->groupBy('id_product_attribute');

Did you find a solution for this?

### Steps to reproduce

1. You can only add items if you are directly at the item and not in the item preview where all items are in the web shop, otherwise the wish list will not show any items.
2. Articles are only added if you are directly at the product.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment] 2023-05-31 15:16
Hello @Stefanr123,

I tried to reproduce your issue but as you can see, I can't. https://watch.screencastify.com/v/qBM3fGxPJr6WBkUOyaIv

Did I miss something?

Thanks for your feedback

**Comment by florine2623** [comment] 2023-06-20 07:57
Hello @Stefanr123 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-06-20 07:57 UTC
Labels: Bug, FO, Blockwishlist, Invalid, 1.7.8.7
