### ISSUE TITLE
missing invoice logo

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24495] opened 2021-05-13 19:02 UTC
#### Describe the bug

My logo is not visible on my prestashop

#### Expected behavior

My logo should appear

#### Steps to Reproduce

- Setup a prestashop thought Docker, expose the port 8000 for the prestashop.
- Add invoice logo
- Geneate an invoice from the front.
- The PHP code try to inject the WHOLE URL instead of the relative path or filepath : 127.0.0.1:8000. 

However, the container can't contact 127.0.0.1:8000, for him, he is 127.0.0.1:80. 

![image](https://user-images.githubusercontent.com/4645967/118173887-72a76380-b42e-11eb-826d-fa97c15d1c97.png)

Hovewer, when i manually print the value of logo in the PDf i got 
![image](https://user-images.githubusercontent.com/4645967/118173939-8226ac80-b42e-11eb-9922-123f722390b7.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Possible solution

Remove the whole HOST path, example: `http://127.0.0.1:8000/logo.png` should become: `/logo.png`.

I tried this, and it works !

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.4

**Comment by florine2623** [comment] 2021-05-14 12:28
Hello @henri9813 ,

I tried an installation using Docker with port 80, I didn't encounter the issue.
![Capture d’écran 2021-05-14 à 14 27 56](https://user-images.githubusercontent.com/16019289/118270608-95825800-b4c0-11eb-9444-ddb15be174fe.png)

Does the port really matter in this case ?

Can you downgrade your PHP version to 7.3 and test again ?
PS 1.7.7.4 is not compatible with PHP 7.4 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by henri9813** [comment] 2021-05-15 21:04
As i said, you need to expose OTHER thing than 80.

1. Setup a prestashop thought Docker, expose the port `8000` for the prestashop.
2. Add invoice logo
3. Geneate an invoice from the front.
4. The PHP code try to inject the WHOLE URL instead of the relative path or filepath : `127.0.0.1:8000`.

**Comment by hibatallahAouadni** [comment] 2021-05-18 10:36
Hello @henri9813 

Thanks for your details I manage to reproduce this issue #22581
So, as we are aware of this issue and it is already in our debug backlog. This issue is a duplicate of #22581. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-18 10:37
Duplicate of #22581

**Closed as completed by hibatallahAouadni** 2021-05-18 10:36 UTC
Labels: Bug, CO, Duplicate, Invoices, Theme & logo, 1.7.7.4
