### ISSUE TITLE
Obbligatory address field dissapears

### ISSUE THREAD

**Issue by nexinet** [PrestaShop/PrestaShop#12837] opened 2019-03-08 05:19 UTC
**Describe the bug**
Into----> BO ---> address----> set up obbligatory field ----> i set up some field to be obbligatory to be filled by customer, I refresh FO and it is ok obbligatory field are there.
AFter few minutes the obbligatories field return as default automatically and the field I wanted obbligatory become again optionally alone.
What is a bug?
**To Reproduce**
1. Go to address in BO and set up obbligatory Field
2. Click on obbligatory field and Save
3. save and check FO
4. error is that after few minutes the obbligatory field I had setting up were return to the default one and beome optionaly...
**Screenshots**
no screenshot applicable
**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-03-08 07:56
Hi @nexinet,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/12_XZAPLOQb5BN0aEDIwCKnpnlkyXQ0y7/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nexinet** [comment] 2019-03-08 11:40
Hi.
I see your video and it works like mine.
the problem is after some time spent on backoffice automatically turns as default you can check mine video at min. 1.05 after some time spent on backoffice it turns in default....
please check the entire video...
https://drive.google.com/file/d/10w9YrsIy7XAEgFOUqh_UEDiiJP3T78EA/view?usp=drivesdk

informations:
Informazioni sul server Linux #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64

Versione software del server: nginx/1.14.2
Versione di PHP: 7.1.26
Limite di memoria: 2G
Tempo di esecuzione massimo: 15000
Dimensione Max. dei file da caricare: 240M

No error Logs

**Comment by khouloudbelguith** [comment] 2019-03-08 14:36
@nexinet, in my case, it is OK.
https://drive.google.com/file/d/1gmHgsqdQuEVX4tHuDTYpI3qmW4NqtXg4/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-08 07:29
Hi @nexinet,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-08 07:29 UTC
Labels: Bug, BO, Can't reproduce, Addresses, 1.7.5.1
