### ISSUE TITLE
BO - Order page - Invoices - Multicurrencies - Incorrect Product's total when adding a product with a discount gift or changing the Shipping

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21566] opened 2020-10-22 11:26 UTC
#### Describe the bug

In the BO > Order detail page, when we add a product with a specific discount (Gift) to an order that contains the gift product at first, we have incorrect total

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO > International > Upload United states pack
2. Change the currency "US Dollar" Exchange rate = 10, Decimals =2
3. Go to BO > Catalog > Discounts page
4. Create a cart rule "free gift "demo_11" Avec specific product "demo_6"
In the Conditions Tab: Product selection => demo_6
![image](https://user-images.githubusercontent.com/16067358/96879446-5933cf80-147c-11eb-8f05-96ec797b760f.png)
In the Action Tab: free gift "demo_11"
![image](https://user-images.githubusercontent.com/16067358/96879572-7ec0d900-147c-11eb-9eaa-cfae6e5c8a53.png)

5. Go to FO > Add demo_11 to the cart with currency **$** selected
6. Continue checkout
7.  Go to the BO => Orders > Order details > add demo_6 to the cart
8. the "demo_11" quantity well updated but the values are NOK
9. Generate an invoice => see the error

It is ok when the order doesn't contain the gift product **at first**

**Other steps to reproduce the issue:**
1. Go to BO > International > Upload United states pack
2. Change the currency "US Dollar" Exchange rate = 10, Decimals =2
3. In the FO > Choose the $ currency
4. add a product to the cart > checkout
5. In the BO > Order page > change the Shipping with another carrier
6. See the error, Base price is NOK & Total NOK
https://drive.google.com/file/d/1qD2FaDEGu1z06YET2dxuv0kzs-666nkf/view?usp=sharing
7.  Generate an invoice => see the error
![image](https://user-images.githubusercontent.com/16067358/96881510-a2851e80-147e-11eb-811f-351da8a3b8c5.png)

With PS1.7.6.8, only the gift product is NOK
Other product => ok
![image](https://user-images.githubusercontent.com/16067358/96864425-aa39c880-1468-11eb-9d4e-bd0247b3a393.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/96863664-80cc6d00-1467-11eb-9bdc-8439774bf60c.png)

#### Additional information

* PrestaShop version: 1770rc1build2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-10-22 11:28
Related to:
https://github.com/PrestaShop/PrestaShop/pull/21326
https://github.com/PrestaShop/PrestaShop/pull/21447

**Comment by eternoendless** [comment] 2020-10-22 11:57
So the problem is that in the products list the amounts are shown in € with the $ symbol, rather than being converted to $, right?

The totals look correct though.

**Comment by jolelievre** [comment] 2020-10-22 12:26
Just a question, what happens if you refresh the page?
Does it become correct or still the same issue?

**Comment by khouloudbelguith** [comment] 2020-10-22 13:19
Hi @eternoendless,

>So the problem is that in the products list the amounts are shown in € with the $ symbol, rather than being converted to $, right?

Yes!

Hi @jolelievre,
>what happens if you refresh the page?
Does it become correct or still the same issue?

No, the same issue
https://drive.google.com/file/d/1eP9SFgunBPxXd9vTcP_gAHgnsGP0grVI/view?usp=sharing

Thanks!

**Comment by matks** [comment] 2020-10-22 13:31
Hi @khouloudbelguith,

I did not reproduce the scenario, I think maybe some info is missing. Can you help me ?

➡️  I install the shop in French, with € as default currency. Is that OK ?

1. Go to BO > International > Upload United states pack
2. Change the currency "US Dollar" Exchange rate = 10, Decimals =2
3. Go to BO > Catalog > Discounts page
4. Create a cart rule "free gift" "demo_11" with specific product "demo_6"

➡️ So I create a cart rule. This cart rule gives "demo_6" as a gift ? But what is "demo_11" ?
What I did
- create cart rule, give it name "test RC2 discount", with code "ABC123"
- enable "free git", choose demo_6 product

5. Go to FO > Add demo_11 to the cart with currency **$** selected

➡️ can you confirm when you open FO it's in € then you switched to $ ?
➡️ can you confirm you added the discount or is that a gift that is automatically granted to customer ?

6. Continue checkout
7.  Go to the BO => Orders > Order details > add demo_6 to the cart
8. the "demo_11" quantity well updated but the values are NOK

**Comment by khouloudbelguith** [comment] 2020-10-22 13:40
Hi @matks,

>Create a cart rule "free gift" "demo_11" with specific product "demo_6"
arrow_right So I create a cart rule. This cart rule gives "demo_6" as a gift ? But what is "demo_11" ?
What I did

In the Conditions Tab: Product selection => demo_6
![image](https://user-images.githubusercontent.com/16067358/96879446-5933cf80-147c-11eb-8f05-96ec797b760f.png)
In the Action Tab: free gift "demo_11"
![image](https://user-images.githubusercontent.com/16067358/96879572-7ec0d900-147c-11eb-9eaa-cfae6e5c8a53.png)

>create cart rule, give it name "test RC2 discount", with code "ABC123"

No there is no code

>can you confirm when you open FO it's in € then you switched to $ ?

Yes, because the default currency is €

>can you confirm you added the discount or is that a gift that is automatically granted to customer ?

No, from the BO > Order page, when you add demo_6 the specific product => the gift will be automatically added

@eternoendless, @jolelievre, @matks  I find other steps to reproduce the issue, I will update my first comment

Thanks!

**Comment by jolelievre** [comment] 2020-10-22 13:42
Hi @khouloudbelguith 

I managed to reproduce the scenario :) @matks your scenario is not the appropriate one the CartRule must be automatic with a code.

1. Have two currencies EUR and USD (with USD exchange rate at 10.00, and EUR default currency)
2. Create two products "Gifted Product" and "Product with associated gift" (quantity 100 for both)
3. Create a CartRule with
    - no code
    - restricted to product "Product with associated gift"  (in conditions)
    - with actions
        - free shipping
        - reduction amount 1€ tax included
        - send gift "Gifted Product"
4. In FO us USD as currency, order the "Gifted Product" and finish checkout
5. In BO go to the Order view page of created order, add product "Product with associated gift"
6. The quantities are correctly updated but the amount in product rows (OrderDetail) are saved as euros amount not dollars
7. The Order totals are correct though

**Comment by khouloudbelguith** [comment] 2020-10-22 13:54
@jolelievre, this issue occurs in the invoices too, if you download the invoice => the prices are NOK.

Thanks!!

**Comment by Progi1984** [comment] 2020-10-26 09:02
Fixed by #21574

**Closed as completed by Progi1984** 2020-10-26 09:02 UTC
Labels: Bug, Major, BO, Order, Discounts, Cart rules, Currencies, Regression, Fixed, migration, 1.7.7.x
