### ISSUE TITLE
Unable to Add Products Manually in Order Creation

### ISSUE THREAD

**Issue by ItsAnfield** [PrestaShop/PrestaShop#34065] opened 2023-09-26 10:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm experiencing an issue when trying to manually create an order in PrestaShop. After entering the customer information, I encounter a problem with the input field when attempting to add products to the order. The input field doesn't respond or provide any results, making it impossible to add products to the order.

### Expected behavior

I expected the product input field to function correctly, allowing me to search for and add products to the order seamlessly.

### Steps to reproduce

Go to the PrestaShop admin panel.
Click on the "Orders" section.
Select "Create new order."
Enter customer information.
Attempt to add products to the order by using the product input field.

### PrestaShop version(s) where the bug happened

1.7.6.3

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

This issue is not related to any specific module.

### Your company or customer's name goes here (if applicable).

 I have also searched for existing issues and found previous reports of this bug, but always happen do to updates or migrations. We haven't done this before.

**Comment by Hlavtox** [comment] 2023-09-26 10:39
Hi @ItsAnfield, I am also running 1.7.6 and it works correctly, 8.1.x also. I think some of your module is breaking it. Can you check what is happening in the console and network tab when you are typing something into that field? It might lead you to the cause. :-)

**Comment by ItsAnfield** [comment] 2023-09-26 10:52
Thanks for the reply @Hlavtox 

When I enter an identifier, it searches for something else, and if I enter text, it does search for something, but I'm not sure exactly what filter it's using in both cases. However, it doesn't display anything, and the dropdown still doesn't show up.

![image](https://github.com/PrestaShop/PrestaShop/assets/78814210/1bca3232-4a61-46e3-99d8-5ebb2a9aa1e6)

**Comment by Hlavtox** [comment] 2023-09-26 10:54
@ItsAnfield There is an F letter in the response, something somewhere is outputting it, breaking the JSON response. :-)

**Comment by ItsAnfield** [comment] 2023-09-26 11:04
@Hlavtox Sorry, that's the dev page. Just checked the prod site where we have the same issue and there is no F letter.
![image](https://github.com/PrestaShop/PrestaShop/assets/78814210/f5aff378-4593-4183-9d4d-080d4a25c1b2)

**Comment by paulnoelcholot** [comment] 2023-10-02 09:10
Hello @ItsAnfield,

PrestaShop 1.7 has reached end of life and is no longer officially maintained, We invite you to upgrade your shop to a more recent version (8.1.2). So I'm closing this issue.

Thank you

**Closed as completed by paulnoelcholot** 2023-10-02 09:10 UTC
Labels: Bug, BO, Order, Invalid
