### ISSUE TITLE
Add the possibility of translating the name of the states

### ISSUE THREAD

**Issue by aboussaid** [PrestaShop/PrestaShop#25560] opened 2021-08-10 13:15 UTC
#### Is your feature request related to a problem?

I have a multilingual site (English / Arabic), and I need to translate the states of the active countries, unfortunately the names of the states are not translatable

![image](https://user-images.githubusercontent.com/33961628/128873375-e3ac8988-2227-490b-9eec-e23e9a6a535a.png)

#### Describe the solution you'd like

add the possibility to translate the name of the states, as for the name of the countries

**Comment by hibatallahAouadni** [comment] 2021-08-11 07:29
Hello @aboussaid 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by BenTen** [comment] 2021-08-12 03:43
@aboussaid be patient, I already created a ticket #11294 in 2018 :D

**Comment by hibatallahAouadni** [comment] 2021-08-12 07:27
@BenTen Thanks for the tip, I habe been searching for your issue :sweat_smile: 
Well, we already have the PM approval but we need users vote for it to change the status of the improvement to **`ToDo`** :wink:

**Comment by hibatallahAouadni** [comment] 2021-08-12 07:28
Hello @aboussaid 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #11294 . 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-08-12 07:28
Duplicate of #11294

**Closed as completed by hibatallahAouadni** 2021-08-12 07:28 UTC
Labels: Improvement, BO, Duplicate, International, Locations, Translations, States

**Comment by matks** [comment] 2021-09-08 16:56
> @aboussaid be patient, I already created a ticket #11294 in 2018 :D

If you want this to happen, the best is to submit a PR yourself. Open source is a joint effort.

PrestaShop is an open source, community project. If you find that any topic is major for you, and it's important to have it fixed fast, then you can _invest_ into having it done. You can hire a developer to implement it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

Don't wait for maintainers to do everything, we don't have the time to do it all. You want it to happen, then do it :) and submit it as a contribution. You cannot do this with proprietary software, this is OSS strength.

**Comment by BenTen** [comment] 2021-09-09 00:59
@matks I guess no need to say that, what I say was not bad meaning. I never complain about maintainers (peace)
