### ISSUE TITLE
Problem with discounts in price catalog rules:

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#24938] opened 2021-06-12 21:14 UTC
Problem with discounts in price catalog rules:

By applying two discounts on a product using price rules catalog, for example I apply a 30% discount on the entire catalog, but I want to apply a more discount in a given category for example -50%, 50% discount is ignored and therefore not Managed correctly, it is always considered the catalog discount (-30%). Otherwise if I apply a discount for a single product amount example -100 € from the product details and this amount exceeds 30% this is applied correctly.

How to reproduce the bug: 
Create a discount on all products of 30% then create a discount of 50% in a single category

Prestashop version: 1.7.6.8
PHP: 7.2 

Regards

**Comment by hibatallahAouadni** [comment] 2021-06-14 06:45
Hello @Gipielle 


We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20185. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-14 06:46
Duplicate of #20185

**Closed as completed** 2021-06-14 06:45 UTC
Labels: Duplicate
