### ISSUE TITLE
After changing product attribute, thumbnails scroll is not working.

### ISSUE THREAD

**Issue by grigorevlad** [PrestaShop/PrestaShop#12064] opened 2019-01-08 13:24 UTC
Fresh 1.7.5 installation.
After changing an attribute that has other product pictures assigned it it, thumbnails scrolling is not working on quick view or in product page. 

Te reproduce:
1. Go to product page
2. Select an attribute that changes product pictures 
3. Click on cover image to open photos zoom
4. Try to scroll thumbnails by clicking arrows 

![issue](https://user-images.githubusercontent.com/8983330/50833331-7a840400-1359-11e9-9a70-ed2f33bde25d.jpg)

PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-01-08 13:36
Hi @grigorevlad,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & ps1.7.4.4.
We will see how to fix it.
Thanks!

**Comment by georgelouk** [comment] 2019-02-27 16:16
I'm experiencing the same issue!
I see that there is no javascript event listener as it should for

< div class="arrows js-modal-arrows"

**Comment by khouloudbelguith** [comment] 2019-02-27 16:25
@grigorevlad, the issue is added to our bug roadmap.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by georgelouk** [comment] 2019-02-27 17:45
@khouloudbelguith It seems that the class js-modal-arrows doesn't gain the Javascript event listener when you are viewing a combination.

Something notable is 

Opening a product with combinations and many images ..
1) modal thumbnails  scroll works fine
2) changing combination -> URL is changing to the combination and modal thumbnails is not working
3) refreshing the page to the "new" combination from step 2, the modal is working
4) changing combination again -> modal thumbnails are not working agian

It seems that changing combination (i guess it's AJAX request) disables the event listener for the two arrows at the class i mentioned above.

**Comment by Progi1984** [comment] 2020-02-03 08:29
Fixed in #16863

**Closed as completed by Progi1984** 2020-02-03 08:29 UTC
Labels: Bug, Minor, FO, Combinations, Fixed, 1.7.5.0, 1.7.6.0
