### ISSUE TITLE
Html tags in order confirmation email if custom fields

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#23870] opened 2021-04-02 09:53 UTC
#### Describe the bug

When a client gets the email confirmation order with custom fields, html tags are showing in the email (see screenshot below)

#### Expected behavior

Html should not be escaped

#### Steps to Reproduce

1. Order products with custom fields
2. See the email Order confirmation

**Screenshots**
![image](https://user-images.githubusercontent.com/1193727/113405299-e70bd300-93a9-11eb-9e9b-21cfd7791301.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-04-02 12:22
Hello @arirangz ,
I was able to reproduce the issue with PrestaShop version 1.7.7.3. 
![Capture d’écran 2021-04-02 à 14 22 00](https://user-images.githubusercontent.com/16019289/113415122-d31e9c00-93be-11eb-9b6e-25c7fe608a5b.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by florine2623** [comment] 2021-04-02 12:23
This is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/22330

So I close your issue.

**Comment by florine2623** [comment] 2021-04-02 12:24
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22330

**Closed as completed by florine2623** 2021-04-02 12:24 UTC
Labels: Bug, Duplicate, Order, Email, Product customization, 1.7.7.1
