### ISSUE TITLE
automatic indexing of products - Multistore - not working 1.7.5.2

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#14479] opened 2019-07-04 08:44 UTC
I noticed that after saving or adding a productpage  the automatic index for the search does not work. Its necessary to click on : Add missing products to the index 

Example before saving a product page:

<img width="1096" alt="Screenshot 2019-07-04 at 09 33 42" src="https://user-images.githubusercontent.com/46492443/60652868-db8c2080-9e40-11e9-9723-02431534dadf.png">

<img width="624" alt="Screenshot 2019-07-04 at 09 34 16" src="https://user-images.githubusercontent.com/46492443/60652885-e2b32e80-9e40-11e9-8a4f-04614951afd7.png">

After saving

<img width="1071" alt="Screenshot 2019-07-04 at 09 35 26" src="https://user-images.githubusercontent.com/46492443/60652897-e5ae1f00-9e40-11e9-9f18-b8aaad93fb48.png">

<img width="941" alt="Screenshot 2019-07-04 at 09 35 41" src="https://user-images.githubusercontent.com/46492443/60652910-eb0b6980-9e40-11e9-95ad-7fd1fc53456f.png">

**Additionnal information**
PrestaShop version: 1.7.5.2 - Multistore
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-04 09:02
Hi @01park,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0.rc1.
I attached a screen record
https://drive.google.com/file/d/1YpxXy4ioCybZZm_pX4Y0x52S65QtTQni/view
Did you add those products throw the import age?

Thanks!

**Comment by 01park** [comment] 2019-07-04 09:27
Hi khouloudbelguith,

We add products with multistore on ALL SHOPS. The index does not work after adding a product, but also once a product is saved is not update. I tried adding a product to an individual store ( shop 1 ) and one to shop 2. Same result.

I'm looking forward to 1.7.6. maybe the problem is fixed after this update, if not I'll report back to you.

**Comment by khouloudbelguith** [comment] 2019-07-04 09:29
@01park, I tried with "All shops" also & it is OK.
https://drive.google.com/file/d/15k_c4ymqOosvmOt3fqgHqW9anFszf9xX/view
Thanks!

**Comment by 01park** [comment] 2019-07-04 09:40
Thank you for now

**Comment by khouloudbelguith** [comment] 2019-07-04 09:43
@01park, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-05 07:24
Hi @01park,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by BenTen** [comment] 2020-01-21 00:18
Sadly, I have the same issue.
@01park did you found a solution?

PS 1.7.5.0
PHP 7.2

@khouloudbelguith I request to reopen the ticket and found the problem :)

**Comment by 01park** [comment] 2020-01-21 08:56
Hi,

No, I don't have any solution to solve this is issue, but I can confirm that I tested this problem this weekend on a single shop store and also here it doesn't work. Maybe we need to install a PHP extension for this option, but what one I don't know. I was hoping someone from PS could help with this. 

I have had this on 1.7.5 up to 1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-01-23 12:14
@01park, It is ok with PS1.7.6.3
https://drive.google.com/file/d/1PprJWQh-L55hxc65DM0NsjtV2YEVCcAF/view

Thanks!

**Comment by 01park** [comment] 2020-01-23 15:50
I updated to 1.7.6.3 on both stores, but made no difference.

Is there any server settings that has to be active for this to work?

**Comment by khouloudbelguith** [comment] 2020-01-23 16:10
@01park, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by 01park** [comment] 2020-01-28 20:37
I just discovered something tonight. 

When I login in to BO, but not as Super administrator and edit and save an product. The search engine index does work. 

Tested again with a new super admin account and search enige index does not work.

**Comment by BenTen** [comment] 2020-01-28 21:53
Since, other profils doesn't have permission for other module by default.
Maybe it's because a module.

Do you have some 3rd part module in hook "actionProductUpdate"?
You can see it in Design > Positions.

**Comment by khouloudbelguith** [comment] 2020-01-29 08:31
Hi @01park,

It is ok with PS1.7.6.3 using a new employee with a different profile than the super admin.
https://drive.google.com/file/d/1YmCwuLrUzahWyo6bVIHzupHBgnsj_nHZ/view
Thanks to check @BenTen request.

Thanks!

**Comment by 01park** [comment] 2020-02-05 12:24
Hi, no I don't have this module installed.

But I do have another store and the same issue with super-admin profile. Very strange.

**Comment by khouloudbelguith** [comment] 2020-02-05 12:42
@01park, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by BenTen** [comment] 2020-02-05 14:41
> 
> 
> Hi, no I don't have this module installed.
> 

@01park I mean, in the BO, in **Design > Positions** page, you can see hook.
If you search "_actionProductUpdate_" and check the box "Display non-positionable hooks", you will see all modules hook to this position.

Which modules can you see? Could you make a screenshot of them (or just copy/past)?

**Comment by 01park** [comment] 2020-02-05 14:48
<img width="1485" alt="Screenshot 2020-02-05 at 14 47 47" src="https://user-images.githubusercontent.com/46492443/73852091-82e19380-4826-11ea-8b3c-c37028b95112.png">


Hi Ben, this is what I see.

**Comment by BenTen** [comment] 2020-02-05 14:51
@01park Is there only 5? It's like your screenshot is cut. (sorry)

**Comment by 01park** [comment] 2020-02-05 14:54
One more module which I do not use. Could this be blocking it?

**Comment by BenTen** [comment] 2020-02-05 14:59
@01park What's the name of this module?
If you don't use it, try to deactivate (or uninstall it) and check if the indexing works.

**Comment by 01park** [comment] 2020-02-05 15:22
No way, I disabled this and now it works!!!

Ben thank you so much!!!

**Comment by khouloudbelguith** [comment] 2020-02-05 15:23
@01park, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Closed as completed by khouloudbelguith** 2020-02-05 15:23 UTC
Labels: Bug, BO, Search, No change required, 1.7.5.2, 1.7.6.3

**Comment by BenTen** [comment] 2020-02-05 15:27
> 
> 
> No way, I disabled this and now it works!!!
> 
> Ben thank you so much!!!

@01park  Could you tell me the name of the module  please, I have the same issue but for my part I can't find the wrong module. Maybe I have the same.

**Comment by 01park** [comment] 2020-02-05 15:27
I stopped using this module because it's related to another problem we have with Prestashop. Its about the product features. When one value gets updated, this value is not updated over all fields of languages. I opened a ticket for this last year, but looks like doesn't have a priority. 

This said, my search is working again. Thank you for your help.

**Comment by BenTen** [comment] 2020-02-05 15:40
@01park  Could you tell me the name of the module  please, I have the same issue but for my part I can't find the wrong module. Maybe I have the same.

**Comment by 01park** [comment] 2020-02-05 15:41
The module is named: Multiple Features

**Comment by 01park** [comment] 2020-02-05 15:44
Btw this is the other case: #13751

Any chance this will be solved?

**Comment by khouloudbelguith** [comment] 2020-02-05 15:48
@01park, It is not fixed yet.
It is added to our bug roadmap.

Thanks!

**Comment by valy72ro** [comment] 2020-09-30 06:56
I have the same issue on multistore 1.768
