### ISSUE TITLE
Don't display warning if module is disabled (ps_wirepayment) 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#23941] opened 2021-04-08 13:03 UTC
#### Describe the bug

When the module is disabled a waring is display

#### Expected behavior

Dont show warning is module is disabled

#### Steps to Reproduce

1 ) Disable the module 
2 ) Go to module catalogue
3)  Check Warning
**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-04-08 14:44
Hello @okom3pom ,

I manage to reproduce the issue in 1.7.7.3, so I can confirm that this behavior is indeed a bug.
![Capture d’écran 2021-04-08 à 16 14 09](https://user-images.githubusercontent.com/16019289/114047078-b1735800-9889-11eb-8f3f-5f820218958e.png)
![Capture d’écran 2021-04-08 à 16 41 07](https://user-images.githubusercontent.com/16019289/114047180-c5b75500-9889-11eb-9080-263f45cc4c8c.png)

It is added to the debug roadmap.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](url_here) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by Progi1984** [comment] 2021-04-12 13:06
Fixed by PrestaShop/ps_wirepayment#62

**Closed as completed by Progi1984** 2021-04-12 13:06 UTC
Labels: Bug, Minor, BO, Modules, Bankwire, Fixed, 1.7.7.3
