### ISSUE TITLE
currency symbol in rtl

### ISSUE THREAD

**Issue by javadalmasi** [PrestaShop/PrestaShop#22541] opened 2020-12-22 14:15 UTC
In Arabic, Persian and Hebrew, which are RTL, in the current version of PrestaShop (1.7.7) the currency symbol is placed to the right of the product price, and this is if the currency symbol should be shown to the left of the price. . This only applies to RTL languages.
Consider the following examples:
- The currency symbol is currently like this
ريال 35000
- The currency symbol in RTL languages should look like this
35000 ريال
1199 درهم

**Comment by hibatallahAouadni** [comment] 2020-12-22 15:42
Hello @javadalmasi 

**Please next time respect and follow the template to submit a complete bug report.**

To change the currency position, please follow my steps:

1. **BO**>**IMPROVE**>**International**>**Localization**
2. Go to **Currencies** tab
3. Click on edit button to edit your currency
4. Scroll down to the **Language** table
5. Click on **Edit symbol** button of **Arabic** language
6. **Choose the format** that you want (you may say that all of them are the same but it's not, it's just the navigator problem :wink: )
7. Click on **Apply** button
8. Then, click on **Save** button.

Please see the screen record below to understand better:
https://drive.google.com/file/d/1aiqjbFxkcZMbrgwnno0QXY9_C9gojW-5/view

I close this issue cause it's not a bug. 
Feel free to open a new one if you encounter any problem with PrestaShop. We will gladly investigate it.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-22 15:42 UTC
Labels: No change required

**Comment by javadalmasi** [comment] 2020-12-22 17:23
There is no Edit symbol section in PrestaShop 1.7.7
Not even in the official demo of Prestashop site
[](https://imgur.com/a/CxSSX5f)
