### ISSUE TITLE
Prestashop Router class does not generate absolute url

### ISSUE THREAD

**Issue by Theodode** [PrestaShop/PrestaShop#18703] opened 2020-04-18 15:19 UTC
Hello,

#### Describe the bug

The method "generate" into PrestaShopBundle\Service\Routing\Router allows the Symfony parameters $referenceType to generate absolute url but it give only relative url. After debugging it seems that the issue come from the method "generateTokenizedUrl" used into "generate". It returns a relative URL even if an absolute one is given as parameter.

#### Expected behavior

Obtain an absolute URL (host + path) with a token

#### Steps to Reproduce

Into a module controller, just use :
$this->generateUrl('some-route',[], UrlGeneratorInterface::ABSOLUTE_URL);
"generateUrl" method will call above mantionned method

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6 but i checked the develop branch on the repository and the code for Router class is the same.
* PHP version: N/A

**Comment by matthieu-rolland** [comment] 2020-04-20 14:08
@PrestaShop/prestashop-core-developers  Wdyt? this issue needs to be checked by a core developer.

**Comment by PierreRambaud** [comment] 2020-11-24 14:39
After several tries, I'm not able to reproduce.
```php
$link->generate('admin_product_new', [], 1); // => ABSOLUTE_PATH
// /admin-dev/index.php/sell/catalog/products/new

$link->generate('admin_product_new', [], 0);  // => ABSOLUTE_URI
// http://ps-develop.localhost/admin-dev/index.php/sell/catalog/products/new
```

**Comment by hibatallahAouadni** [comment] 2020-12-16 15:34
Hello @Theodode ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-16 15:34 UTC
Labels: Bug, CO, SEO & URLs, No change required, 1.7.6.x
