### ISSUE TITLE
webservice customers - can't create new customers

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#26568] opened 2021-11-10 11:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Impossible to create new customer via webservices

URL/api/customers?schema=blank gives an error : 
```
<prestashop>
<errors>
<error>
<code>5</code>
<message>
[PHP Notice #8] Trying to access array offset on value of type null (/home/.../public_html/classes/webservice/WebserviceOutputBuilder.php, line 669)
</message>
</error>
<error>
<code>5</code>
<message>
[PHP Notice #8] Trying to access array offset on value of type null (/home/.../public_html/classes/webservice/WebserviceOutputBuilder.php, line 716)
</message>
</error>
</errors>
</prestashop>
```

### Expected behavior

It should done something like : 
```
<prestashop>
 <customer>
  <id/>
  <id_default_group/>
  <id_lang/>
  <newsletter_date_add/>
  <ip_registration_newsletter/>
  <last_passwd_gen/>
  <secure_key/>
  <deleted/>
  <passwd/>
  <lastname/>
  <firstname/>
  <email/>
  <id_gender/>
  <birthday/>
  <newsletter/>
  <optin/>
  <website/>
  <company/>
  <siret/>
  <ape/>
  <outstanding_allow_amount/>
  <show_public_prices/>
  <id_risk/>
  <max_payment_days/>
  <active/>
  <note/>
  <is_guest/>
  <id_shop/>
  <id_shop_group/>
  <date_add/>
  <date_upd/>
  <reset_password_token/>
  <reset_password_validity/>
  <associations>
   <groups>
    <group>
     <id></id>
    </group>
   </groups>
  </associations>
 </customer>
</prestashop>
```

### Steps to reproduce

Create a new customer with webservice
> Originally posted by @ceer (see the [comment](https://github.com/PrestaShop/PrestaShop/pull/29258#issuecomment-1223126475))

Here’s is the way to reproduce the bug
1. Use this docker-compose:

```yaml
version: "3"

services:
  prestashop:
    image: prestashop/prestashop:1.7.8.4-7.4-apache
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - PS_DEV_MODE=0
      - PS_DEMO_MODE=0
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8080
      - PS_FOLDER_ADMIN=admin
      - ADMIN_MAIL=demo@prestashop.com
      - ADMIN_PASSWD=prestashop_demo
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - prestashop-net

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    networks:
      - prestashop-net

networks:
  prestashop-net:
```

2. Enable Webservice in back-office, create a key with all permissions for `customers` ressource
3. Go to http://localhost:8080/api/customers?schema=blank

Results :
```xml
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <errors>
        <error>
            <code>
                <![CDATA[ 5 ]]>
            </code>
            <message>
                <![CDATA[
[PHP Notice #8] Trying to access array offset on value of type null (/var/www/html/classes/webservice/WebserviceOutputBuilder.php, line 669)
]]>
            </message>
        </error>
        <error>
            <code>
                <![CDATA[ 5 ]]>
            </code>
            <message>
                <![CDATA[
[PHP Notice #8] Trying to access array offset on value of type null (/var/www/html/classes/webservice/WebserviceOutputBuilder.php, line 716)
]]>
            </message>
        </error>
    </errors>
</prestashop>
```

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2021-11-11 09:14
Hello @pppplus 

I didn't manage to reproduce the issue with PS1780, see the attached screenshots below:

### URL/api/customers?schema=blank
![image](https://user-images.githubusercontent.com/23308427/141270630-e2806d48-7927-4721-9e03-620ff23c9ccc.png)

### URL/api/customers
![image](https://user-images.githubusercontent.com/23308427/141270925-8c2f51d4-8517-41c1-b0a0-1235f8d29bf7.png)

### URL/api/customers/3?schema=blank
![image](https://user-images.githubusercontent.com/23308427/141270803-dddf6352-90e4-46d1-a800-be94a0fb29a3.png)

Please check and feedback.
Thanks!

**Comment by pppplus** [comment] 2021-11-11 10:17
Hi, I see.
I've the problem only on /api/customers?schema=blank
for /api/customers/3?schema=blank, it's OK
for /api/customers/3, it's OK

Strange.
It's an update from PS 1.7.6.? to 1.7.8
On page system-information, no file are detected as wrong

So no idea, what can be wrong.
I do not find any documentation, for error code 5

**Comment by hibatallahAouadni** [comment] 2021-11-11 17:11
Hello @pppplus 

Could you please check this issue #26559 seems similar to yours.
Please check and feedback.

Thanks!

**Comment by pppplus** [comment] 2021-11-11 17:52
Yes !! It works.

So the 2 errors messages have to be solved to avoid such correction to apply.
[PHP Notice #8] Trying to access array offset on value of type null (/home/.../public_html/classes/webservice/WebserviceOutputBuilder.php, line 669)
[PHP Notice #8] Trying to access array offset on value of type null (/home/.../public_html/classes/webservice/WebserviceOutputBuilder.php, line 716)

Thanks to report this issue, so I can use my API again

**Comment by khouloudbelguith** [comment] 2021-11-18 14:23
Hi @pppplus,

I did not manage to reproduce the issue with PS1781
![image](https://user-images.githubusercontent.com/16067358/142432946-517b1fbc-3d1e-4acd-82e2-02f761265dea.png)
**BO**
![image](https://user-images.githubusercontent.com/16067358/142433054-e772887c-6355-40fc-8b38-3532bdca6b28.png)

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by pppplus** [comment] 2021-11-18 14:39
Hi
Try with 
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
instead of 
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT

You will see small errors, as explained before.

**Comment by waflessnet** [comment] 2022-01-24 13:51
hi 
I use PS 1.7.8.2 , php  7.4.2 , nginx  
install yesterday [23-01-2022]  with themes  or modules external  

``` https://XXXXXXX.cl/api/customers/?schema=blank&io_format=JSON ```
although in the same way, shema black return error last json : 

![image](https://user-images.githubusercontent.com/6413704/150794932-3fe07d86-011a-4fb6-a593-ea706eca2785.png)

**Comment by kpodemski** [comment] 2022-09-16 14:14
Hello @PrestaShop/qa-team 

We have PR Available with the fix for this issue + detailed explanation there:
https://github.com/PrestaShop/PrestaShop/pull/29258#issuecomment-1223126475

Can we simply reopen this issue and use the author's comment as a "How to reproduce"?

**Comment by hibatallahAouadni** [comment] 2022-09-16 14:40
Hello @kpodemski 

Ofc we can :wink: 
Changing the issue status to New 

Thanks for the ping

**Comment by MhiriFaten** [comment] 2022-09-16 16:30
Hello @kpodemski ,

I tested the issue with PS1.7.7.8
[Untitled_ Sep 16, 2022 5_30 PM.webm](https://user-images.githubusercontent.com/111756615/190686317-7f22da6a-39f1-46cc-b0ad-ad104ff0ec96.webm)


I was able to reproduce the issue with PS1.7.8.0.
I’ll add this to the debug backlog so that it’s fixed. Waiting for your PR

[Untitled_ Sep 16, 2022 4_41 PM.webm](https://user-images.githubusercontent.com/111756615/190682190-a2dc2470-b2f2-439c-9707-cb84b5818331.webm)

Thank you

**Comment by MatShir** [comment] 2023-02-28 09:19
FIxed by https://github.com/PrestaShop/PrestaShop/pull/30993

**Closed as completed by MatShir** 2023-02-28 09:19 UTC
Labels: Bug, Major, WS, Customer, Fixed, PR available, 1.7.8.0, Verified
