### ISSUE TITLE
Prestashp Email Alert Module - Order Edit email is not sent

### ISSUE THREAD

**Issue by kpoptown** [PrestaShop/PrestaShop#35492] opened 2024-02-26 23:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I installed Prestashop Email Aleart and when admin change order details, I set to notify customers about "order edit"
But email is not sent. Even though admin change the order details, "Email NOtification to customer about order edit" does not work

### Steps to reproduce

1. Go to Module " Email Alert" by prestashop
2.  Enable Customer notification about ORder Edit

### PrestaShop version(s) where the bug happened

1.8.1

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2024-02-27 08:54
Hello @kpoptown ,

I can't reproduce your issue.
When I edit an order (delete a product from the order), I receive an email titled [my_shop] Your order has been changed.

<img width="603" alt="Screenshot 2024-02-27 at 09 53 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/638f5b88-1758-4b74-952c-c8125873e528">

I'm closing your issue.

**Closed as completed by florine2623** 2024-02-27 08:54 UTC
Labels: Bug
