### ISSUE TITLE
Faceted search stock filter

### ISSUE THREAD

**Issue by gluhicom** [PrestaShop/PrestaShop#14171] opened 2019-06-12 12:17 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-12 12:20
Hi @gluhicom,

Could you please provide us more information about your issue?
What is the exact version of the ps_factedsearch did you use? we need a clear description about this issue to understand how to reproduce it.

Thanks!

**Comment by gluhicom** [comment] 2019-06-12 12:20
Hello.

The filter "in stock" does not work properly, if we mark products with stock, the products without stock is also displayed, but if select filter "out of stock", nothing is displayed, even if the products are not stocked. What's the problem, I think it's the same in the default theme? Clearing cache and this things not help.

Best regards,
Matija

**Comment by gluhicom** [comment] 2019-06-12 12:21
Version of module is 3.0.3
Prestashop version 1.5.7.2
PHP 7.2

**Comment by gluhicom** [comment] 2019-06-12 12:22
Sorry, prestashop version 1.7.5.2 :)!

**Comment by khouloudbelguith** [comment] 2019-06-12 12:35
@gluhicom, the option `Allow ordering of out-of-stock products` option in the Shop Parameters / Product Settings page is enabled or not?

Thanks!

**Comment by gluhicom** [comment] 2019-06-12 12:41
Yes, it's enabled:


[cid:image001.png@01D5212C.CE6A2C80]

**Comment by khouloudbelguith** [comment] 2019-06-12 12:54
@gluhicom,
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13139
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-12 12:54
Duplicate of #13139

**Closed as completed by khouloudbelguith** 2019-06-12 12:54 UTC
Labels: Duplicate, Faceted search
