### ISSUE TITLE
Translations missing - error folder missing

### ISSUE THREAD

**Issue by ConvarDeutschland** [PrestaShop/PrestaShop#15331] opened 2019-08-30 12:34 UTC
Hello, we have the following error when we try to make changes in the translations ot the "legal EU" module.

Could not crawl for translation files: The "/var/www/....." directory does not exist.

If I create the folder the error change to " no translations found".

But why is the system expecting the translation in this folder"/var/cache/prod/themes/AngarTheme/translations" Thranslations are normally inthe modules folder or not?

**Comment by khouloudbelguith** [comment] 2019-08-30 13:19
Hi @ConvarDeutschland,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots
 - what is the exact name of this module?
 - This module is provided by your theme "AngarTheme"?
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ConvarDeutschland** [comment] 2019-08-30 14:59
Hello khouloudbelguith,
Please find here the request informations

- PHP error logs are not activated on this server (live system)
- Javascript console no error reported on this page
- The module name is "Legal Compliance - v3.0.2 - by PrestaShop" it is not part of the theme it's a Prestashop module

[apache_error.zip](https://github.com/PrestaShop/PrestaShop/files/3560419/apache_error.zip)
![Modulename](https://user-images.githubusercontent.com/14978257/64030760-7eae9d00-cb47-11e9-8484-4bc4755edd04.jpg)
![systemInfo](https://user-images.githubusercontent.com/14978257/64030769-82daba80-cb47-11e9-926d-ccb8d9157d17.jpg)

![Error](https://user-images.githubusercontent.com/14978257/64031103-0e544b80-cb48-11e9-9888-7b8bad5c0806.jpg)
![DebugError](https://user-images.githubusercontent.com/14978257/64031114-13b19600-cb48-11e9-8585-d8946ff3440d.jpg)

**Comment by khouloudbelguith** [comment] 2019-08-30 15:20
@ConvarDeutschland, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15139 to fix the issue.
It is fixed in the PS1.7.6.1.
Your ticket is a duplicate of #15133
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-30 15:20
Duplicate of #15133

**Closed as completed by khouloudbelguith** 2019-08-30 15:20 UTC
Labels: Bug, BO, Duplicate, Translations, Modules & Themes

**Comment by pierreloicq** [comment] 2019-09-04 09:30
Hi, 
The problem seems to be still present on 1.7.6.1 when I want to translate a child theme (child_classic). I can translate the classic theme. Is it important that I bring my modifications in the child theme rather than in the parent theme ?

`The "C:\Program Files (x86)\Ampps\www\presta17\var\cache\prod/themes\child_classic\translations\fr-FR" directory does not exist.`

**Comment by khouloudbelguith** [comment] 2019-09-04 10:22
Hi @pierreloicq,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1GPmWi8B_TLKJxEPfr_1MwqiZnA5l2ypP/view
Thanks!

**Comment by pierreloicq** [comment] 2019-09-04 19:22
It occurs also on a fresh install.
Maybe the way I import my child theme is not correct (I just pasted it in my theme folder)
Actually I cannot do the 3rd step of [this picture](http://doc.prestashop.com/download/attachments/51184280/Capture%20d%E2%80%99e%CC%81cran%202019-08-12%20a%CC%80%2014.59.28.png?version=1&modificationDate=1565614783000&api=v2) because it fails to load my zip (even if the zip lead directly to the folders (assets, config, templates) and files (index.php, preview.png)
Thanks

**Comment by khouloudbelguith** [comment] 2019-09-05 10:05
@pierreloicq, this issue occurs because when we try to upload a theme with a zip folder which includes the theme folder in the zip, an alert is displayed as reported in this ticket: 
https://github.com/PrestaShop/PrestaShop/issues/15004

Thanks!

**Comment by pierreloicq** [comment] 2019-09-09 09:50
Here is the topic of interest : 
https://github.com/PrestaShop/PrestaShop/issues/15268

**Comment by mynameisboris** [comment] 2020-04-01 21:22
This solution helped: https://www.prestashop.com/forums/topic/999019-176-could-not-crawl-for-translation-files/?do=findComment&comment=3214285
Seems like Prestashop was unable to auto-extract the translation ZIP to the folder.


> I was able to resolve this.
> 
> 1) International -> Translations, click Add or update a language for the language that doesnt work.
> This will create translations/sf-de-DE.zip
> 2) Manually create a folder app/Resources/translations/de-DE  (or the one that is missing for your language)
> 3) Extract files there manually.
