### ISSUE TITLE
Cyrillic symbols bug in Prestashop 1.7.8.3

### ISSUE THREAD

**Issue by devcodex2025** [PrestaShop/PrestaShop#27520] opened 2022-01-28 20:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In some columns in the back-office Cyrillic symbols not displaying correctly. For example - in orders page. Why? I installed the latest version of CMS, in my hosting utf-8 encoding is set everywhere in .htaccess, in PHP my admin. But these symbols not showing correctly, it's very strange.

### Expected behavior

i want to fix it, or update cms to fix issues

### Steps to reproduce

1. Go to back-office
2. Open orders page or some another
3. Get undefined symbols

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-01-30 22:40
Hello @karbivskij 

Could you please provide a screenshot cause I didn't manage to reproduce the issue 🙏 
Which language did you use for your back office?

Did you try to clear cache? Go to **Advanced Parameters**>**Performance** and change the smarty parameters like in the attached screenshot below, then click on **Save**:

![image](https://user-images.githubusercontent.com/23308427/151720899-f3a83106-c403-4aea-957b-5e495d09bcac.jpeg)

Now, click on the **Clear cache** button and check if you still encounter the same problem.
Waiting for your feedback.

Thanks!

**Comment by karbivskij** [comment] 2022-01-30 23:00
Hi, Hibatallah Aouadni! I am using a ukrainian language in admin panel. The screenshot from page of orders I attached to email, the cache is cleared many times. Some text showing with errors, some text showing correctly, I'm testing in different pages text showing differently, sometimes with errors, some times correctly, in database showing nice, without bags. -------- Исходное сообщение --------От: Hibatallah Aouadni ***@***.***>Дата: пн, 31 янв. 2022 г., 00:40Кому: PrestaShop/PrestaShop ***@***.***>Копия: Roman K ***@***.***>, Mention ***@***.***>Тема: Re: [PrestaShop/PrestaShop] Cyrillic symbols bug in Prestashop 1.7.8.3 (Issue #27520)

Hello @karbivskij

Could you please provide a screenshot cause I didn't manage to reproduce the issue 🙏

Which language did you use for your back office?

Did you try to clear cache? Go to Advanced Parameters>Performance and change the smarty parameters like in the attached screenshot below, then click on Save:



Now, click on the Clear cache button and check if you still encounter the same problem.

Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-30 23:30
Hello @karbivskij 

Thanks for your feedback!
But could you please respond and attach the screenshot on GitHub not via mail 🙏 cause when you answer via mail, that's what I got 😓 


> Hi, Hibatallah Aouadni! I am using a ukrainian language in admin panel. The screenshot from page of orders I attached to email, the cache is cleared many times. Some text showing with errors, some text showing correctly, I'm testing in different pages text showing differently, sometimes with errors, some times correctly, in database showing nice, without bags. -------- Исходное сообщение --------От: Hibatallah Aouadni ***@***.***>Дата: пн, 31 янв. 2022 г., 00:40Кому: PrestaShop/PrestaShop ***@***.***>Копия: Roman K ***@***.***>, Mention ***@***.***>Тема: Re: [PrestaShop/PrestaShop] Cyrillic symbols bug in Prestashop 1.7.8.3 (Issue #27520) Hello @karbivskij Could you please provide a screenshot cause I didn't manage to reproduce the issue 🙏 Which language did you use for your back office? Did you try to clear cache? Go to Advanced Parameters>Performance and change the smarty parameters like in the attached screenshot below, then click on Save: Now, click on the Clear cache button and check if you still encounter the same problem. Waiting for your feedback. Thanks! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Waiting for your feedback.
Thanks!

**Comment by karbivskij** [comment] 2022-01-30 23:39
Screenshot (maybe I forgot add it to email) -------- Исходное сообщение --------От: Hibatallah Aouadni ***@***.***>Дата: пн, 31 янв. 2022 г., 01:30Кому: PrestaShop/PrestaShop ***@***.***>Копия: Roman K ***@***.***>, Mention ***@***.***>Тема: Re: [PrestaShop/PrestaShop] Cyrillic symbols bug in Prestashop 1.7.8.3 (Issue #27520)

Hello @karbivskij

Thanks for your feedback!

But could you please respond and attach the screenshot on GitHub not via mail 🙏 cause when you answer via mail, that's what I got 😓



Hi, Hibatallah Aouadni! I am using a ukrainian language in admin panel. The screenshot from page of orders I attached to email, the cache is cleared many times. Some text showing with errors, some text showing correctly, I'm testing in different pages text showing differently, sometimes with errors, some times correctly, in database showing nice, without bags. -------- Исходное сообщение --------От: Hibatallah Aouadni @.>Дата: пн, 31 янв. 2022 г., 00:40Кому: PrestaShop/PrestaShop @.>Копия: Roman K @.>, Mention @.>Тема: Re: [PrestaShop/PrestaShop] Cyrillic symbols bug in Prestashop 1.7.8.3 (Issue #27520) Hello @karbivskij Could you please provide a screenshot cause I didn't manage to reproduce the issue 🙏 Which language did you use for your back office? Did you try to clear cache? Go to Advanced Parameters>Performance and change the smarty parameters like in the attached screenshot below, then click on Save: Now, click on the Clear cache button and check if you still encounter the same problem. Waiting for your feedback. Thanks! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: @.***>



Waiting for your feedback.

Thanks!

**Comment by karbivskij** [comment] 2022-01-31 00:35
![кодировка.png](https://user-images.githubusercontent.com/67425372/151724687-8ece4c11-d8b3-4d39-b9d9-6e732bd83026.png)

**Comment by karbivskij** [comment] 2022-01-31 11:14
I sent to you the screenshot, can you test this?

**Comment by hibatallahAouadni** [comment] 2022-01-31 11:37
Hello @karbivskij 

I didn't manage to reproduce the issue, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/151786712-1796c80b-7896-420b-91f5-475a5a6af723.png)

At first, not all the sentences were translated, so I updated the language twice to have the good results:

![image](https://user-images.githubusercontent.com/23308427/151786822-d9f5be3c-1384-4638-bc72-f8dd1fc19f5e.png)

Now, here's the Order page, no Cyrillic symbols at all:

![image](https://user-images.githubusercontent.com/23308427/151786898-019a1bb3-8f2a-4594-847b-84c4372aff94.png)

Please check and feedback.
Thanks!

**Comment by karbivskij** [comment] 2022-01-31 11:41
OK, maybe the problem with database encoding?

**Comment by hibatallahAouadni** [comment] 2022-02-01 00:11
Hello @karbivskij 

May be but it's definitely not related to PS Core :wink: 
So, closing the issue!

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Closed as completed by hibatallahAouadni** 2022-02-01 00:11 UTC
Labels: Bug, BO, Performance, Front-end, Invalid, 1.7.8.3
