### ISSUE TITLE
Unable to update an attachment via the webservice

### ISSUE THREAD

**Issue by rsoulard-prolaser** [PrestaShop/PrestaShop#27552] opened 2022-02-01 11:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Unable to update an attachment via the webservice:
`[PHP Warning #2] Use of undefined constant PS_DOWNLOAD_DIR - assumed 'PS_DOWNLOAD_DIR' (this will throw an Error in a future version of PHP) (/.../classes/webservice/WebserviceSpecificManagementAttachments.php, line 330)`

It is fixed on the `develop` branch but it must be fixed also on versions `1.7.8.x`

### Expected behavior

No error

### Steps to reproduce

1. Go to BO
2. Add an attachment
3. Update this attachment via webservice

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by marwachelly** [comment] 2022-02-01 15:51
Hello,

Thank you for your report. Could you please provide the body request that you used to update the attachement? 

Thanks,

**Comment by rsoulard-prolaser** [comment] 2022-02-02 09:05
Hello,

```
<?php

$url = 'http://_YOU_URL_/api/attachments/file/1?ps_method=PUT';
$key  = '_YOUR_KEY_';

$path = '/path/to/the/file.pdf';
$name = 'My file';

$args = [
    'file' => new CURLFile($path),
    'name' => $name,
];

$ch = curl_init();
curl_setopt($ch, CURLOPT_HEADER, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLINFO_HEADER_OUT, 1);
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_USERPWD, $key.':');
curl_setopt($ch, CURLOPT_POSTFIELDS, $args);
$result = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

echo '<pre>';
print_r($httpCode);
echo '</pre>';

echo '<pre>';
print_r($result);
echo '</pre>';
```

**Comment by khouloudbelguith** [comment] 2022-02-11 12:52
Hi @rsoulard-prolaser,

Thanks for your feedback.
In fact, I used two methods with PS1783.
It is ok :heavy_check_mark: 
I used postman => OK

https://user-images.githubusercontent.com/16067358/153593764-b97bd71e-4d55-4ad6-a5f4-19c9e9e6967c.mp4

I used this script:
```
<html><head><title>CRUD Tutorial - update example</title></head><body>

<form action="http://0.0.0.0:8081/1783/api/attachments/file/1" method="POST" enctype="multipart/form-data">
<attachment>
    <file_name>Update file of the first attachement</file_name>
    <input name="ps_method" value="PUT" type="hidden">
    <input name="file" type="file">
    <input value="Execute" type="submit">
</attachment>
</form>
```
It is ok also


https://user-images.githubusercontent.com/16067358/153594225-6f432ebd-1596-4ee1-8d16-35889c606103.mp4


Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you!

**Closed as completed by khouloudbelguith** 2022-02-11 12:52 UTC
Labels: Bug, WS, Files, Webservice, PR available, 1.7.8.0, Invalid

**Comment by rsoulard-prolaser** [comment] 2022-02-11 13:21
Hello @khouloudbelguith,

I made a mistake in the title and the description, the modification works but it is the deletion of the old file which is not done and causes a warning because of an error on the name of the variable `PS_DOWNLOAD_DIR` instead of `_PS_DOWNLOAD_DIR_`.
I'm sorry for the bad explanation.

**Comment by rsoulard-prolaser** [comment] 2022-02-16 07:55
@khouloudbelguith, do i have to make a new issue?

**Comment by khouloudbelguith** [comment] 2022-02-16 07:58
Hi @rsoulard-prolaser,

This issue is currently closed, can you open a new one with more information about your configuration & the exact steps to reproduce the issue.

Thanks!

**Comment by rsoulard-prolaser** [comment] 2022-02-16 08:54
@khouloudbelguith, here the issue #27690
