### ISSUE TITLE
Order confirmation email without data

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15646] opened 2019-09-23 08:36 UTC
Hi
I manage 15 websites but only in this case I get this error. In some cases the order confirmation email is without data inside the email.
Upgrading to 1.7.6.1 I thought to solve this problem (on 1.7.6 were missing only the products) instead on 1.7.6.1 all variables are without data
can you check please this type of error because it creates problems to customers?
I can give you the access of this site
bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/65411377-01e0ad00-dded-11e9-8f92-4fa9110010c7.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-09-23 08:47
Hi @maofree,

This issue occurs when entering an email address in uppercase.
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13386
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-23 08:47
Duplicate of #13386

**Closed as completed by khouloudbelguith** 2019-09-23 08:47 UTC
Labels: Duplicate

**Comment by Maofree** [comment] 2019-09-23 09:01
Hi
Is this error solved?
from that page I see that it is already present

**Comment by Maofree** [comment] 2019-09-23 09:15
hi
yes th customer has enter an email in uppercase
is there a fix to solve this problem without to wait a new release?

thanks

**Comment by khouloudbelguith** [comment] 2019-09-23 10:39
@maofree, sorry not yet.
