### ISSUE TITLE
User and guest accounts addresses conflict

### ISSUE THREAD

**Issue by lusimeon** [PrestaShop/PrestaShop#12088] opened 2019-01-09 14:09 UTC
Hi,

On the administration panel, when I want to add an address to an existing user account (eg: test@test.com) who has also been registered as a guest account with the same email address before, the address is attached to the guest account unless the user account.

1. Install a clean Prestashop
2. Enable guest account mode
3. Process an order as a guest with email address "test@test.com"
4. Create a user account with the same email address "test@test.com"
5. On the admin panel, add a new address to the user account
6. The address don't appeared on the user account cause is attached to the guest account

**Additionnal information**
PrestaShop version: 1.6.1.23
PHP version: 5.6

This problem has been fixed in Prestashop 1.7 because guest accounts are transformed to user account on order process. So it's impossible to create a second account with same email address. But the problem is still present in Prestashop 1.6.1.23.

**Comment by khouloudbelguith** [comment] 2019-01-09 14:21
Hi @lusimeon,

The issue is not fixed with PS1.7.5.0, I manage to reproduce the issue with PS1.7.5.0.
If you navigate to FO => Add a product to the cart => In the checkout process => Step1 (PERSONAL INFORMATION) => Order as a guest "test@prestashop.com", **without Password**. => so the Guest account is not transformed into a customer account.
But this issue will be fixed in this issue: #10122.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-09 14:21
Duplicate of #10122

**Closed as completed by khouloudbelguith** 2019-01-09 14:21 UTC
Labels: Duplicate
