### ISSUE TITLE
ps_emailalerts box icon not showing in customer account

### ISSUE THREAD

**Issue by Robysoldtamiya** [PrestaShop/PrestaShop#30397] opened 2022-11-24 13:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have problem with alerts box not showing correctly in customer accout.
I have 2 sites version 1.7.7.8 one is live other is test and give same problem.
A 3rd test site is 1.7.8 and has no problem.
When I debug customer page with browser tools I see code is different in v 1.7.8 it clearly calls the icon

I have disinstalled module with option to delete folders and reinstalled new version or previous version and then upgraded but problem is still there.

![errore_psemailalerts](https://user-images.githubusercontent.com/118987492/203799645-3ed4db72-692c-4731-b130-f7caa40a0036.jpg)
![errore_psemailalerts2](https://user-images.githubusercontent.com/118987492/203799661-c5a731c9-edb6-40a3-ab10-cc8d98c08a5c.jpg)
![errore_psemailalerts_ps178](https://user-images.githubusercontent.com/118987492/203799683-540b0499-9235-43b7-8a00-04c1551a7678.jpg)

### Expected behavior

I'm expecting correct visualization of box

### Steps to reproduce

Install module

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by sallemiines** [comment] 2022-11-24 14:21
Hello @Robysoldtamiya 

Thanks for reporting the issue .
Could you please provide us the `ps_emailalerts ` module version that you used ? 

In my case i check you issue with the `ps_emailalerts V2.4.0` , and unfortunately I can't manage to reproduce your issue, I tried to reproduced it with `PS1778 + php 7.33` `PS1787`

you can see the attached screenShots 

**Module ps emailalerts installed** 

![emailalert1-png-1833×1051-](https://user-images.githubusercontent.com/31663369/203806090-94f8ae9b-f4b6-44c9-9a07-f06deabba9d5.png)

![emailalert2-png-1392×220-](https://user-images.githubusercontent.com/31663369/203806182-36d7505e-fe00-47fa-9c14-075f7f5aba88.png)

**Module ps emailalerts uninstalled** 

![image-1-png-1786×973-](https://user-images.githubusercontent.com/31663369/203806564-09250b21-b3a7-4fd3-8842-2216c031611f.png)

Please check and feedback ! 

Thank you !

**Comment by Robysoldtamiya** [comment] 2022-11-24 15:24
I have the problem with all version
I started from v2.2.0 up to latest

**Comment by Robysoldtamiya** [comment] 2022-11-26 10:16
any help ? what can I do to understand why the module inserts different code in the menu ?

**Comment by sallemiines** [comment] 2022-11-28 08:49
Hello @Robysoldtamiya ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by sallemiines** 2022-11-28 08:49 UTC
Labels: Bug, FO, Can't reproduce, ps_emailalerts, 1.7.7.8, Invalid
