### ISSUE TITLE
hook actionValidateCustomerAddressForm validation in class CustomerAddressFormCore is not enough efficient

### ISSUE THREAD

**Issue by Ryttis** [PrestaShop/PrestaShop#26925] opened 2021-12-08 15:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bug appears  when hook actionValidateCustomerAddressForm is not registered. In class CustomerAddressFormCore method validate()  Hook::exec returned value 'Null' is evaluated as false that fails form validation process even when all fields are fulfilled properly.

### Expected behavior

After improvement returned Null will be evaluated as true and form validation will pass.

### Steps to reproduce

1. Ensure that hook actionValidateCustomerAddressForm is not registered ( is absent on database ).
2. Start Checkout process.
3. After fulfilling address tab and pushing button "Continue" form not will be passed to delivery tab.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2021-12-09 10:06
Hello @Ryttis ,

On your step 1, in which table should it be checked ?
In `ps_hook`, I have the hook present :
<img width="958" alt="Screenshot 2021-12-09 at 11 00 45" src="https://user-images.githubusercontent.com/16019289/145375381-90cf8301-900a-42b6-9769-86095e167b98.png">

In `ps_hook_alias`, `ps_hook_module`, `ps_hook_module_exceptions` : absent.

Step 2, done

Step 3, I have no issue with finish the checkout process :
<img width="1110" alt="Screenshot 2021-12-09 at 11 05 41" src="https://user-images.githubusercontent.com/16019289/145376021-b0a24eb1-f1c6-46f1-bc64-582ae630fb6d.png">

Is there something else I can do to trigger the bug you're having ?
Thanks!

**Comment by devecomiz** [comment] 2021-12-14 10:15
Hello @florine2623,

I reproduce the same issue after shop upgrade from 1.7.7.2 to 1.7.8.2 with autoupgrade module v4.13.0.
(PS_INSTALL_VERSION = 1.4.9.0, upgraded several times to Prestashop 1.6 and Prestashop 1.7)

The hook actionValidateCustomerAddressForm is absent on database table ps_hook.
- On Frontoffice form add address, in checkout page, button Continue : 
no error message, address is not registered, cannot access to the delivery tab
- On Frontoffice form add address, in my account page, button Save : 
error message "Please fix the error below." but no detail, address is not registered
- On Backoffice form add address, button Save :
no problem here : address is registered

PR 26926 fix this issue.
Thank you.
Regards

**Comment by florine2623** [comment] 2021-12-14 14:06
Hello @devecomiz ,

I have upgraded my shop from 1.7.7.2 to 1.7.8.2, using 1-click upgrade v4.13.0, I didn't encounter the issue.

Upgrade went well :
<img width="745" alt="Screenshot 2021-12-14 at 14 05 29" src="https://user-images.githubusercontent.com/16019289/146003781-4986ecfd-8a02-4f92-afd2-e2dfb2c68697.png">

After the upgrade, the hook actionValidateCustomerAddressForm is present in the database in table ps_hook :

<img width="966" alt="Screenshot 2021-12-14 at 15 00 32" src="https://user-images.githubusercontent.com/16019289/146012938-dc027980-ccda-4eae-8e7a-a9b316b725a8.png">

In FO it is OK : https://watch.screencastify.com/v/wJqd1MCAam8SXonyOLxb

In BO my address is registered : 
<img width="1200" alt="Screenshot 2021-12-14 at 15 05 18" src="https://user-images.githubusercontent.com/16019289/146013547-3e1e6a69-d746-4632-b7e0-3e4b4cb823cf.png">

I can't reproduce your issue.
Is there something more about configuration that I can try on my end ?
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-29 11:03
Hello @Ryttis 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-29 11:03 UTC
Labels: Bug, Addresses, PR available, Hook, 1.7.8.0, Invalid
