### ISSUE TITLE
ps_facetedsearch special chars in feature value

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#23726] opened 2021-03-22 15:45 UTC
#### Describe the bug

Faceted search doesn't work when there are some special chars in feature values.
Example : "-" or "/"

#### Steps to Reproduce

Steps to Reproduce :
1. Create feature value containing "-" or "/"
2. Activate this feature value on faceted search
3. Select this feature value on the front
4. Nothing happens

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-03-22 16:39
Hello @guigplt 

This issue has been fixed with **ps_facetedsearch** v3.7.0 see the issue #16320 and the PR https://github.com/PrestaShop/ps_facetedsearch/pull/275
Could you please upgrade your **ps_facetedsearch** module and check if you still encounter the issue.

Thanks!

**Comment by guigplt** [comment] 2021-03-22 17:13
That's the version I have.

**Comment by hibatallahAouadni** [comment] 2021-03-23 05:43
Hello @guigplt 

Thank for you feedback! 
So your **ps_facetedsearch** version is 3.7.0 and you still encounter this issue? That's odd!
Could you please provide a screenshot or a screen record.

Thanks!

**Comment by guigplt** [comment] 2021-03-23 09:29
Hi,
Yes that's right.

Here is an example : 
![image](https://user-images.githubusercontent.com/44002621/112124093-44da3700-8bc2-11eb-8e57-3698702692a1.png)

When I click, the q parameter is not added to the url.

Also I tried to add the feature url : 
![image](https://user-images.githubusercontent.com/44002621/112124371-8ff44a00-8bc2-11eb-9936-809eba637cbb.png)

But it's not used in the q parameter.

**Comment by guigplt** [comment] 2021-03-24 13:19
I see there is a new version 3.7.1.
Isn't it fixed in this version ?

**Comment by hibatallahAouadni** [comment] 2021-03-24 17:10
Hello @guigplt 

I reproduce the issue with PS1.7.6.5 (FacetedSearch v3.7.0 & v3.7.1) but I didn't manage to reproduce the issue with PS1.7.7.2.
See the attached screen record below:

https://drive.google.com/file/d/1B7e-wjSKOmDM0kjzZ7yxqfP5VFLM9-O4/view

I think the problem is related with module compatibility with PrestaShop version.
Ping @PrestaShop/prestashop-core-developers what we should do? shall we put the label **`To Do`** or what?

**Comment by PierreRambaud** [comment] 2021-03-25 10:29
> Hello @guigplt
> 
> I reproduce the issue with PS1.7.6.5 (FacetedSearch v3.7.0 & v3.7.1) but I didn't manage to reproduce the issue with PS1.7.7.2.
> See the attached screen record below:
> 
> https://drive.google.com/file/d/1B7e-wjSKOmDM0kjzZ7yxqfP5VFLM9-O4/view
> 
> I think the problem is related with module compatibility with PrestaShop version.
> Ping @PrestaShop/prestashop-core-developers what we should do? shall we put the label **`To Do`** or what?

Yes you can put this in To Do, I'm still convinced we have to make this module compatible with older version because it's really important for the front office.

**Comment by florine2623** [comment] 2024-12-24 13:55
I can't reproduce this issue on PS 9.0.0. tested with Feature name and Feature Value name, in both cases, I can find my product.

https://github.com/user-attachments/assets/22b54d1c-ee45-41f2-a95d-4ee89a07f33e


I'm closing this issue to avoid clogging the backlog.

**Closed as completed by florine2623** 2024-12-24 13:55 UTC
Labels: Bug, Minor, FO, Faceted search, Fixed, 1.7.5.1, Verified, Module
