### ISSUE TITLE
Migrated Order page does not contain order reference

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25078] opened 2021-06-22 11:45 UTC
#### Describe the bug

When opening an order in backoffice, there was order reference in page title, and you could see which tab is which order. This disappeared after page migration

#### Expected behavior

Page title should contain order reference on order pages.
The same goes for product edit, I think it can contain product reference or ID.

#### Steps to Reproduce

1. Open any order in backoffice in develop.
2. Open any order in backoffice on 1.7.6.
3. Compare page titles in the browser.

#### Additional information

* PrestaShop version: 1.7.7, develop

**Comment by florine2623** [comment] 2021-06-22 11:59
Hello @Hlavtox ,

I was able to reproduce the issue with PrestaShop version 1.7.7.x, 1.7.8.x and develop so I can confirm that this behavior is indeed a bug.
![Screenshot 2021-06-22 at 13 54 57 (2)](https://user-images.githubusercontent.com/16019289/122920753-04758b00-d362-11eb-815e-d8f6c1b2c44c.png)


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment] 2021-06-24 08:02
Hi @MatShir would that be a good opportunity to improve this title?

The title was "Order ABCDEF from Mathieu Ferment" before. It contains order reference, and customer firstname and lastname. Maybe there are some informations more valuable to put in the page title? Order ID? Order status ?

**Comment by Progi1984** [comment] 2021-06-24 08:04
@matks Nope, it's not a good opportunity.

Why ? We fix a regression. So the wording can't be changed in patch versions.

If you want to change the wording, it will be in next version.

**Comment by matks** [comment] 2021-06-24 08:48
> @matks Nope, it's not a good opportunity.
> 
> Why ? We fix a regression. So the wording can't be changed in patch versions.
> 
> If you want to change the wording, it will be in next version.

Agreed 😉  let's keep it like it was for 1.7.7, but we can discuss in parallel with @MatShir for an improvement for next version

**Comment by Progi1984** [comment] 2021-06-24 08:54
@matks Totally agree :heart_eyes:

**Comment by Hlavtox** [comment] 2021-06-24 09:27
@matks Order ID is not needed at all, as a merchant, you don't work with it... `Order XXXXXX from Firstname Lastname | Shop name` is perfectly fine, IMHO. :-)

**Comment by Hlavtox** [comment] 2021-06-24 09:31
BTW @Progi1984 Can you remove the Orders > from the title? It's making the title kinda unusable :-D

![Výstřižek](https://user-images.githubusercontent.com/6097524/123239479-af5f8380-d4df-11eb-9dbe-4c96b83d6821.JPG)

**Comment by Progi1984** [comment] 2021-06-24 09:39
@Hlavtox In `1776`, we fix the regression. But in `develop`, we could change it. Ping @MatShir

**Comment by Progi1984** [comment] 2021-07-08 11:54
Fixed in #25107 by @Progi1984

**Closed as completed by Progi1984** 2021-07-08 11:54 UTC
Labels: Bug, develop, Trivial, BO, Order, Regression, Fixed, PR available, 1.7.7.x, 1.7.8.x
