### ISSUE TITLE
"Available" Translation missing for Faceted Search moldule

### ISSUE THREAD

**Issue by chloepasquis** [PrestaShop/PrestaShop#33536] opened 2023-08-03 11:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is no translation of "available" for the module Faceted Search.
There is nothing in the translation files in /www/modules/ps_facetedsearch/translations

![translation](https://github.com/PrestaShop/PrestaShop/assets/141329282/482bfbfc-62af-4691-8e38-d567450af7da)

### Expected behavior

Should have the translation "available" in ModulesFacetedsearchShop, but instead, I only have "not available".
![translation](https://github.com/PrestaShop/PrestaShop/assets/141329282/46de86d4-8df1-43fb-a2bb-8d3d77704990)

### Steps to reproduce

Go to International > Translation
Choose Installed mdules translations > Faceted search
Use the search bar to look for "available"

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.13.0

### Your company or customer's name goes here (if applicable).

B2B ONLINE

**Comment by Hlavtox** [comment] 2023-08-03 12:02
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28302

**Closed as completed by Hlavtox** 2023-08-03 12:02 UTC
Labels: Bug, Duplicate
