### ISSUE TITLE
Filter order of the form Faceted search

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#12781] opened 2019-03-04 09:22 UTC
When changing the position of filters in a model, this is retained until you access the edit in that template again; in fact, in doing so, the system shows the positions of the filters as they originally were.
The problem does not concern memorization, but it concerns the visualization in the modification phase, in fact, there are no instructions to show the filters respecting the previously specified positioning.

PrestaShop version: all version
Faceted search: all version

I'm attaching files with a possible solution (search for 'modifying Faceted search')
[ps_facetsearch.zip](https://github.com/PrestaShop/PrestaShop/files/2925265/ps_facetsearch.zip)

**Comment by khouloudbelguith** [comment] 2019-03-04 09:44
Hi @Codencode,

We are aware of this issue, it is in progress.
We are currently working on a big refactoring of this module.
Your ticket is a duplicate of #9880
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-04 09:44
Duplicate of #9880

**Closed as completed by khouloudbelguith** 2019-03-04 09:44 UTC
Labels: Duplicate, Faceted search

**Comment by Codencode** [comment] 2019-03-04 10:15
Ok Tranks!
