### ISSUE TITLE
Unable to update products and can not see combinations after 1-click upgrade into 1.7.5.0

### ISSUE THREAD

**Issue by Roodrock** [PrestaShop/PrestaShop#11824] opened 2018-12-18 20:14 UTC
After 1-click upgrade where there was no issues i can not update my products and i can not see combinations anymore even tho they exist when i go to stock management.

![1](https://user-images.githubusercontent.com/45979333/50180289-201af900-0301-11e9-91ba-ccc08d2c5771.JPG)
![2](https://user-images.githubusercontent.com/45979333/50180290-201af900-0301-11e9-946e-c9a5cb95ea76.JPG)
![3](https://user-images.githubusercontent.com/45979333/50180292-201af900-0301-11e9-9f53-a6b934bb2ad6.JPG)

My shop:
Server information Linux #1 SMP Debian 3.16.56-1~ui80+1 (2018-05-15) x86_64

Server software version: Apache

PHP version: 7.2.13

Memory limit: -1

Max execution time: 50000

Upload Max File size: 64M

MySQL version: 5.5.60-0+deb7u1-log

MySQL server: db759948707.hosting-data.io

MySQL name: db759948707

MySQL user: dbo759948707

Tables prefix: kab9_

MySQL engine: InnoDB

MySQL driver: DbPDO

Thank You for your help

**Comment by Roodrock** [comment] 2018-12-18 21:35
When run debugging found this issue:

GET Parameters
_token | "x0TUa0-A15QKrgFnK7XtRrgaMsr37aLdR4vStzxbKZo"
-- | --

Request Attributes

_controller | "PrestaShopBundle\Controller\Admin\AttributeController::getFormImagesAction"
-- | --
"security.firewall.map.context.main"
"json"
"admin_get_form_images_combination"
[▶]
"PrestaShopBundle\Controller\Admin\AttributeController"
2
"1"

Is it because i have not back up pictures?

**Comment by Roodrock** [comment] 2018-12-18 21:57
I rolled back to previous version and it works...

**Comment by khouloudbelguith** [comment] 2018-12-19 08:15
Hi @Roodrock,

In my case, I did not manage to reproduce the issue with the 1-click upgrade v4.5.1 after upgrade from 1.7.4.4 to 1.7.5.0.
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-19 08:20
Duplicate of #11825

**Closed as completed by khouloudbelguith** 2018-12-19 08:20 UTC
Labels: Bug, Duplicate, Autoupgrade, Combinations, 1.7.5.0
