### ISSUE TITLE
bug design

### ISSUE THREAD

**Issue by nouveautestament** [PrestaShop/PrestaShop#35141] opened 2024-01-24 12:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://github.com/PrestaShop/PrestaShop/assets/84104408/16374134-c455-4631-9f06-c2f596cb98b1)

### Steps to reproduce

default

### PrestaShop version(s) where the bug happened

1.8.3

**Comment by nouveautestament** [comment] 2024-01-24 12:44
bug on windows, not on linux ?!

**Comment by florine2623** [comment] 2024-01-24 13:26
Hello,

I can't reproduce your issue, so I'm closing it.

https://github.com/PrestaShop/PrestaShop/assets/16019289/74852792-9257-4266-a928-5f7bee6c6b58

Thanks

**Closed as completed by florine2623** 2024-01-24 13:26 UTC
Labels: Bug

**Comment by nouveautestament** [comment] 2024-01-26 02:38
With Win10
https://demo.prestashop.com/#/en/front
https://www.onworks.net/playonline/index.php

![image](https://github.com/PrestaShop/PrestaShop/assets/84104408/96f28a3b-8049-4813-b983-31402d4559bb)

**Comment by nouveautestament** [comment] 2024-01-28 09:35
assets/css/theme.css

`.carousel{/*left:50%;width:100vw;*/padding-bottom:.5rem;/*margin-left:-50vw;*/`

DONE
