### ISSUE TITLE
Back office orders page loads very very slowly.

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#12771] opened 2019-03-02 06:01 UTC
Hello,

When in the back office, I want to check orders so I clicked the orders link. However, the webpage of orders loads very very slowly.

Tom

**Comment by khouloudbelguith** [comment] 2019-03-04 08:16
Hi @TomHsiung,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-03 10:47
Hi @TomHsiung,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed** 2019-06-05 15:41 UTC
Labels: BO, Order, No change required
