### ISSUE TITLE
Total order price is wrong for customized product

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#30756] opened 2023-01-06 17:15 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Buy a customized product like "Mug personnalisable" demo-14
the front office order display a wrong total price to zero.
![image](https://user-images.githubusercontent.com/16720275/211062764-a14612e1-1670-48b3-b4ee-fa9296c331fa.png)

### Expected behavior

Display the real price.

### Steps to reproduce

1. Buy a customized product like "Mug personnalisable" demo-14 with a customized text
2. In the confirmation page, the total of the product is zero
3. In the detail order price, , the total of the product is zero

### PrestaShop version(s) where the bug happened

1.7.8.8 and 8.0.1

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment] 2023-01-06 17:29
Hello @jf-viguier 

We are aware of this issue, it is already in the Project debug backlog. This issue is a duplicate of #10912. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-01-06 17:29
Duplicate of #10912

**Closed as completed by hibatallahAouadni** 2023-01-06 17:29 UTC
Labels: Bug, Duplicate, Invalid

**Comment by jf-viguier** [comment] 2023-01-06 17:56
Thanks @hibatallahAouadni for the duplicate search, you rocks.
