### ISSUE TITLE
BO - Exception thrown when adding invalid avatar format in profile page

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28484] opened 2022-05-13 07:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Exception thrown when adding invalid avatar format in profile page
PS 1.7.8.0

https://user-images.githubusercontent.com/89604350/168235398-6705cede-7d87-4f6c-8bd1-849be6d6b595.mp4

PS1.7.7.8
![image](https://user-images.githubusercontent.com/89604350/168235354-fa3f4b19-98c8-4a7f-8990-6bedbbf37665.png)

### Steps to reproduce

1. Go to BO > Advanced parameters > Team > Profiles tab
2. Fill the name 
3. Choose a file with a format different from .gif, .jpg, .png
4. see error

### PrestaShop version(s) where the bug happened

1.7.8.5/1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by matks** [comment] 2022-09-06 07:34
@PrestaShop/qa-team is this a duplicate of https://github.com/PrestaShop/PrestaShop/issues/28985 ? or related?

**Comment by khouloudbelguith** [comment] 2022-09-06 08:36
Hi @matks,

I think those issues are related, they are not reproduced on the same page.
The #28484 is reproduced in the BO > Advanced Parameters > Team > Employee edit/add page
The #28985 is reproduced in the BO > Advanced Parameters > Team > Profile edit/add page

Thanks!

**Closed as completed** 2022-10-26 13:53 UTC
Labels: Bug, Trivial, BO, Advanced parameters, Team, Profiles, Regression, Fixed, PR available, Good first issue, 1.7.8.0, Verified
