### ISSUE TITLE
ObjectModel function update returns TypeError on line 775

### ISSUE THREAD

**Issue by mnowakpcgs** [PrestaShop/PrestaShop#30873] opened 2023-01-15 15:03 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm working with prestashop 8.0 and at this time that means porting 1.7 themes and modules

One theme module extends the ObjectModel class and has a 'update' function which calls parent::update();

That returns a "TypeError" on line 775 of classes/ObjectModel.php

`count(): Argument #1 ($value) must be of type Countable|array, bool given`

Upon debugging I find $id_shop_list from line 774 returns array([1] => 1) but $this->id_shop_list is empty

Resolution:

Update line 775 from

`if (count($this->id_shop_list)) {`
		
to:
		
`if (is_array($this->id_shop_list) && count($this->id_shop_list)) {`

### Steps to reproduce

Call parent::update() from a module extending ObjectModel class

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment] 2023-01-16 14:56
Hi @mnowakpcgs 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by kpodemski** [comment] 2023-01-18 11:18
Hello @mnowakpcgs 

My guess is that it's only for your module.  When I see `ObjectModel` this property is always an array, and the method returning IDs of shops is also required to return an array. Maybe you overridden it somewhere in your module?

**Comment by florine2623** [comment] 2023-03-09 11:13
Hello @mnowakpcgs ,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-03-09 11:13 UTC
Labels: Bug, Theme & logo, Theme custo, Module, 8.0.0
