### ISSUE TITLE
1.7.4.4 category grid view, text shows long discription, not short discription.

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#11636] opened 2018-12-06 10:20 UTC
1.7.4.4 category grid view, text shows long discription, not short discription.

PS 1.7.4.4
PHP 7.2

![2018-12-06_11h12_27](https://user-images.githubusercontent.com/11147327/49577916-d61d3500-f948-11e8-880d-b487c7e34352.png)

**Comment by khouloudbelguith** [comment] 2018-12-06 10:38
Hi @Peter4661,

Thanks for your report.
Did you the default theme by PrestaShop?
Because with PrestaShop 1.7.4.4 & the default theme Classic, I did not manage to reproduce your issue.
I attached a video record
https://drive.google.com/file/d/1Hcy6OypyQeWC0Zt11ILlqsdAJDcQRri3/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-11 16:49
Hi @Peter4661,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-11 16:49 UTC
Labels: FO, Modules & Themes, No change required
