### ISSUE TITLE
Duplicate code for invoice formatting in several locations

### ISSUE THREAD

**Issue by JoryHogeveen** [PrestaShop/PrestaShop#26646] opened 2021-11-17 08:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There are several locations where an invoice formatting is done using the same (duplicate) code.
Even the PDF filenames are created using the same formatting (duplicate) code.

### Expected behavior

It's better to remove any duplicate code and apply formatting in one single location.

### Steps to reproduce

This isn't something to reproduce.

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

All

**Comment by hibatallahAouadni** [comment] 2021-11-17 13:50
Hello @JoryHogeveen 

> This isn't something to reproduce.

Sorry :sweat_smile: but you need to provide clear and concise steps to reproduce to validate the issue and then to review/test your PR.
So, please try your best to provide steps to reproduce, your PS version and your PHP version :pray: 
Waiting for your feedback.

Thanks!

**Comment by JoryHogeveen** [comment] 2021-11-17 14:23
Hi @hibatallahAouadni 

Again, this isn't a bug that is something to reproduce, please read the description.
It's a code style "bug" and I already provided a PR that will enhance this code.

Nothing "breaks" due to this bug, it only gets harder for dev's and users to properly override the invoice number format.
The PR aims to fix this issue by having only one location in PrestaShop core where invoice number formatting is done.

EDIT: I only created this issue because the PR reviewer asked me to ;)

**Comment by hibatallahAouadni** [comment] 2021-11-17 14:30
Hello @JoryHogeveen 

> There are several locations where an invoice formatting is done using the same (duplicate) code.
> Even the PDF filenames are created using the same formatting (duplicate) code.


> Nothing "breaks" due to this bug

well then, it looks like an improvement :wink: 
Ping @PrestaShop/prestashop-core-developers wdyt?

**Comment by JoryHogeveen** [comment] 2021-11-17 14:43
@hibatallahAouadni Correct! It is :) Though I didn't see a template for an improvement, only a bug report or a feature request..

**Comment by hibatallahAouadni** [comment] 2021-11-17 17:15
Hello @JoryHogeveen 

Here's the button to click when you want to create an improvement:

![image](https://user-images.githubusercontent.com/23308427/142249131-6d7ee99f-c4fd-4ba2-abaf-6a1d5b0baf4d.png)

Hope it helps :wink: 
Thanks!

**Comment by JoryHogeveen** [comment] 2021-11-17 18:22
Hi @hibatallahAouadni
But it isn't a feature request, it's an improvement.. Maybe include that in the description :)
Anyhow, I'll use the feature request template from now on!

**Comment by matks** [comment] 2022-04-21 15:57
Fixed by https://github.com/PrestaShop/PrestaShop/pull/26587

**Closed as completed** 2022-04-21 15:57 UTC
Labels: Feature, CO, Invoices, Developer Feature, PR available
