### ISSUE TITLE
Problem with additions!

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18270] opened 2020-03-23 15:07 UTC
How is it possible that in 2020 there are problems related to simple arithmetic calculations?
What about an ecommerce program, by the way?

Here are the pictures of the problem, you can see the email which has another problem (Shipping with vat price although the site is set to show the price without VAT)
and the total in backoffice 

* PrestaShop version: 1.7.6.3
* PHP version: 7.2
<img width="1760" alt="Schermata 2020-03-23 alle 16 04 52" src="https://user-images.githubusercontent.com/5024055/77331920-ac487700-6d21-11ea-89cb-851bb89c104a.png">
<img width="1086" alt="Schermata 2020-03-23 alle 16 03 16" src="https://user-images.githubusercontent.com/5024055/77331931-afdbfe00-6d21-11ea-9b93-de1b9ee706e4.png">
<img width="583" alt="Schermata 2020-03-23 alle 15 59 59" src="https://user-images.githubusercontent.com/5024055/77331934-b0749480-6d21-11ea-93ec-b1b5aec16bbe.png">
<img width="355" alt="Schermata 2020-03-23 alle 15 59 41" src="https://user-images.githubusercontent.com/5024055/77331943-b1a5c180-6d21-11ea-92bb-c874499a4948.png">

**Comment by khouloudbelguith** [comment] 2020-03-23 15:10
Hi @Betafer,

Thanks for your report.
There is no pictures attached.
Thanks to sign in to GitHub and upload your pictures [here](https://github.com/PrestaShop/PrestaShop/issues/18270).

Thanks!

**Comment by Betafer** [comment] 2020-03-23 15:16
This is in PayPal also wrong ! 
77,08 € +
18,30 € 

--------
95,38 € + VAT (22%)
95,38 * 1,22 = 116,36 €

The problem is that shipping cost is send to paypal with vat and not without. Total is correct

<img width="315" alt="Schermata 2020-03-23 alle 16 10 19" src="https://user-images.githubusercontent.com/5024055/77331337-dd747780-6d20-11ea-9f6f-7b0be75aab89.png">

**Comment by Betafer** [comment] 2020-03-23 15:19
<img width="825" alt="Schermata 2020-03-23 alle 16 18 41" src="https://user-images.githubusercontent.com/5024055/77332197-06493c80-6d22-11ea-87c7-3457cb06871c.png">
This is the DB

**Comment by Betafer** [comment] 2020-03-23 15:27
The correct amount is:
(77,08+15)*1,22= 112,3376 € Rounded 112,34 €
The customer paid: 112,26€

**Comment by Betafer** [comment] 2020-03-23 15:38
In this case there are more problems:

The first is the calculation error
The second is logical, as prices are shown with or without VAT instead of keeping the shop rule.
The third is that by showing different prices, customers ask questions rightly.
So instead of taking care of the sales job we merchants have to do assistance on problems like this, then go to modify the database by hand with the risk of making other mistakes and finally, hope not to send incorrect invoices and also risk penalties.

I hope I made my point of view clear and that a solution can be found.

**Comment by khouloudbelguith** [comment] 2020-03-23 15:52
@Betafer, thanks for these clarifications.
>The second is logical, as prices are shown with or without VAT instead of keeping the shop rule.
The third is that by showing different prices, customers ask questions rightly.

We are awre of this issue, it is added to our bug roadmap.
Please follow: https://github.com/PrestaShop/PrestaShop/issues/17764

>The first is the calculation error

We are awre of this issue, we have two issues reported about this problem:

- https://github.com/PrestaShop/PrestaShop/issues/17161
- https://github.com/PrestaShop/PrestaShop/issues/9779

Thanks to check and feedback.

**Comment by Betafer** [comment] 2020-03-23 16:02
Ok, thanks.
We solved the problem more than 5 years ago, if you tell me which files were involved in version 1.5 I can share them so maybe it helps you speed up the fix and include it in the official version. And we don't have to redo the change in future updates.

**Comment by khouloudbelguith** [comment] 2020-03-23 16:07
@Betafer, sorry we don't support any more PS1.5 and [PS1.6](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
If you think you can do it, please do send us a pull request!
I will close the issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-23 16:07
Duplicate of #17764

**Closed as completed by khouloudbelguith** 2020-03-23 16:07 UTC
Labels: Bug, Duplicate, Taxes and Prices, 1.7.6.3

**Comment by Betafer** [comment] 2020-03-23 16:11
I meant, if I share the 1.5 files that are interested in this problem, you can use them to speed up the resolution in 1.7.

**Comment by Matt75** [comment] 2020-03-23 16:12
> Ok, thanks.
> We solved the problem more than 5 years ago, if you tell me which files were involved in version 1.5 I can share them so maybe it helps you speed up the fix and include it in the official version. And we don't have to redo the change in future updates.

You can compare file of previous PrestaShop version thanks to repositories
PrestaShop 1.4 https://github.com/PrestaShop/PrestaShop-1.4
PrestaShop 1.5 https://github.com/PrestaShop/PrestaShop-1.5
PrestaShop 1.6 https://github.com/PrestaShop/PrestaShop-1.6
PrestaShop 1.7 https://github.com/PrestaShop/PrestaShop

You can target a specific version thanks to tags
![github-tags](https://user-images.githubusercontent.com/5262628/77337684-832be480-6d29-11ea-9e1f-4d67c0c22620.png)

**Comment by Betafer** [comment] 2020-03-23 16:17
We have edited many core files in 1.5 to fix lots of bugs, 
can you tell me which files are related to this problem in 1.7 if they are partially the same as in 1.5, we can share our solution.

**Comment by Matt75** [comment] 2020-03-23 16:36
What is exact PrestaShop version of your files ?
@khouloudbelguith Do you know how to receive modified files from @Betafer ? Maybe by email ?
It can be useful to get clues.

**Comment by khouloudbelguith** [comment] 2020-03-23 16:41
@Matt75,
>@khouloudbelguith Do you know how to receive modified files from @Betafer ? Maybe by email ?
It can be useful to get clues.

What do you think about this solution if it possible
1. `$git clone https://github.com/PrestaShop/PrestaShop-1.5.git`
2. create a new branch - `$git checkout -b [name_of_the_branch]`
3. Make the changes
4. Create a PR

Or, yes, sending files by email.

Thanks!

**Comment by Betafer** [comment] 2020-03-23 16:43
> What is exact PrestaShop version of your files ?
> @khouloudbelguith Do you know how to receive modified files from @Betafer ? Maybe by email ?
> It can be useful to get clues.

1.5.6.3

**Comment by Matt75** [comment] 2020-03-23 16:53
@Betafer Thanks, if you're not confident to know make a diff of your files with git you can send files in zip to khouloud.belguith@prestashop.com thanks

**Comment by Betafer** [comment] 2020-03-23 18:38
The problem isn't make a diff of the files, but know which files controls these functions
