### ISSUE TITLE
Wrong Specific Price Amount when taxes changes

### ISSUE THREAD

**Issue by urimarti** [PrestaShop/PrestaShop#12169] opened 2019-01-16 11:03 UTC
What changes do?
There is a bug in prestashop that doesn't calculate correctly Specific Prices when taxes are changed in Front Office.

For example, with a 21% taxes when the product costs 100€ and it has an specific price of 10€ tax included total price should be 90€ tax included.
Without taxes should be:
original price: 82,64€
discount: 8,26 €
total price: 74,34 €

The problem is that the discount is always 10€. So i modiffied the way it gets the taxes of product.
With this, it checks the default country and gets its tax rule. When checks the specific_price amount it calculates the current tax_rule and calculates the difference of % into its amount to display and get the correct amount in product price discount.

Soultion:
classes/Product.php

on line 3092:
```
// Added By UriMarti
		$total_tax = Tax::getProductTaxRate($id_product);
		$prod = new Product($id_product);
		$default_tax = Db::getInstance()->getRow('
			SELECT t.rate
			FROM `'._DB_PREFIX_.'tax_rules_group` trg
			INNER JOIN `'._DB_PREFIX_.'tax_rule` tr ON tr.id_tax_rules_group = trg.id_tax_rules_group AND tr.id_country = '.(int)Configuration::get('PS_COUNTRY_DEFAULT').' AND tr.id_state = 0
			INNER JOIN `'._DB_PREFIX_.'tax` t ON t.id_tax = tr.id_tax
			WHERE trg.id_tax_rules_group = '.(int)$prod->id_tax_rules_group.'
			GROUP BY 1');
		$default_tax = $default_tax['rate'];
		$difference_tax = (float)$default_tax - (float)$total_tax;
		if($specific_price['reduction_tax'] == 1){
			$specific_price_reduction = $specific_price_reduction / (1+($difference_tax/100));
		} else {
			$specific_price_reduction = $product_tax_calculator->addTaxes($specific_price_reduction);
		}
		// Ending by UriMarti
		    
                // Adjust taxes if required
		/*
                if (!$use_tax && $specific_price['reduction_tax']) {
                    $specific_price_reduction = $product_tax_calculator->removeTaxes($specific_price_reduction);
                }
                if ($use_tax && !$specific_price['reduction_tax']) {
                    $specific_price_reduction = $product_tax_calculator->addTaxes($specific_price_reduction);
                }
		*/
```

You can check it [here](https://github.com/urimarti/Prestashop/commit/cb02974cacba8457eedd54c203fc12ff1b0c8372#diff-0a7a17e9ff155e6890d7a5b01eea713c)

**Comment by khouloudbelguith** [comment] 2019-01-16 11:52
Hi @urimarti,

Thanks for your report & for the fix.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9856, please follow #9856
So, I close it.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by khouloudbelguith** [comment] 2019-01-16 11:52
Duplicate of #9856

**Closed as completed by khouloudbelguith** 2019-01-16 11:52 UTC
Labels: Duplicate
