### ISSUE TITLE
Problem with 1-click upgrade

### ISSUE THREAD

**Issue by adrifi90** [PrestaShop/PrestaShop#29579] opened 2022-09-08 06:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

when I install your 1-click upgrade module and try to configure it, I get a blank page and I can't do anything.
Even with the debug mode active, no errors are reported, only the blank page.

I run a 1.7.8.0 Prestashop version.

How can I solve the problem?

### Steps to reproduce

Just install and configure it

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by HanaRebaiQA** [comment] 2022-09-08 08:38
hello @adrifi90 

Thanks for your report.
I was unable to reproduce your issue with **PS1780** using the `1-click upgrade module v4.14.2`.
Here is a screenshot following by a screen-record : 

![image](https://user-images.githubusercontent.com/92912932/189076852-73956daf-0d06-47d5-ad94-273f7d8452f3.png)

https://user-images.githubusercontent.com/92912932/189076291-81f1ce59-dd02-4d0f-94c6-220e87e5db3c.mp4



Could you please check if it's a cache problem? Or maybe an environment configuration problem.

To clear your caches please check these ones :  

- BO > Advanced parameters > Performance > Use `Force compilation` and click on `Clear cache`
- The cache under `var/cache` is well cleared 
- Clear your cache browser.

Could you please check again ?

Thank You!

**Comment by adrifi90** [comment] 2022-09-08 08:46
Hello,

thanks for your reply.

I have disabled all caches, both server side and backoffice side and deleted the contents of the var/cache folder.

The problem remains.

Now I am trying to do a manual upgrade by replacing the contents of my installation with the files of the latest version available (1.7.8.7). As soon as it is finished, I will launch the database upgrade hoping that everything goes well.

I've done a server-side backup just to be safe, if that doesn't work either I'll come back to this thread to update you.

**Comment by HanaRebaiQA** [comment] 2022-09-08 08:51
Hello @adrifi90 

Thank you for your response and we are waiting for your feedback.
Otherwise, if the problem still exists, could you please provide us a screen-record to can see the issue ?

Thank You!

**Comment by HanaRebaiQA** [comment] 2022-09-28 10:47
Hello @adrifi90 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank You!

**Closed as completed by HanaRebaiQA** 2022-09-28 10:47 UTC
Labels: Bug, BO, Autoupgrade, 1.7.8.0, Invalid, Module

**Comment by yakayit** [comment] 2023-04-06 13:37
Hi,
the issue suppose to be a bug of the "1-click upgrade"  module; it's also in PS 8.x.x... the only way is updating PS manually.

However, also manual mode upgrade needs an hint: you have to edit the file upgrade.php at lines 47/48/49 because one more "up directory" command is missing: you have to add ../

Best regards.

yaKay
