### ISSUE TITLE
prestashop product edit backoffice not working ( loads forever )

### ISSUE THREAD

**Issue by Ericdev89** [PrestaShop/PrestaShop#23285] opened 2021-02-17 11:32 UTC
#### Describe the bug

Unable to edit or add  a product in backoffice.
as soon as i want to edit a product in backoffice the page loads forever and after a lonnnnnnnnnnnnnng time 503 error.
and all links in backoffice do the same thing after click on edit link for product in backoffice

#### Expected behavior

The edit or add link button must open the form for edition

#### Steps to Reproduce

1. Go to backoffice'
2. Click on  product catalog link
3. Click on edit or add link for product
4. page load forever

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.2.0
* PHP version: 7.1.3

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:17
Hello @Ericdev89 

We are aware of this issue, it is already fixed with this PR #8780 (PS version 1.7.3.1). 
This issue is a duplicate of #11268. 
Sorry but I have to close the issue, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:17
Duplicate of #11268

**Closed as completed by hibatallahAouadni** 2021-02-17 13:17 UTC
Labels: Duplicate
