### ISSUE TITLE
Sorting of attributes do not save Prestashop 8.0.1

### ISSUE THREAD

**Issue by jokn74** [PrestaShop/PrestaShop#30804] opened 2023-01-11 08:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

You can move the attributes and it looks like the sorting is saved, but the database is not updated.

### Expected behavior

The sorting should be updated in the Database

### Steps to reproduce

1. Go to attributes
2. Clic on an attribute group to enter in it 
3. move an attribute inside the group pressing the arrow in the position field
4. the system writes "successful update"
5. press F5, and the attributes are back at where you started

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2023-01-11 13:44
Hello @jokn74 

Thanks for your report.
I tried to reproduce your issue using PS8.0.1 and ph7.4. But, I was unable to reproduce it when refreshing the page and clicking on F5, the attributes are well updated.


https://user-images.githubusercontent.com/92912932/211821571-80339eec-07c8-4dec-8ced-3d7d10e07e34.mp4


Did I miss something?

Thank You!

**Comment by jokn74** [comment] 2023-01-11 14:01
Hi @HanaRebaiQA 

Yes step 2.

It is not the attribute "groups" that can not save the ordering, it is the attributes inside them, the groups are fine :-)

![ATTributes groups](https://user-images.githubusercontent.com/122433444/211825044-d9b79e7d-8638-41f3-8a37-0465fa1d6ad8.png)
![ATTributes inside group](https://user-images.githubusercontent.com/122433444/211825046-3edefc08-0c24-4163-984e-3ddf3bd0a45c.png)

I tries with PHP 8.0 same problem, so not a PHP issue :-)

**Comment by AureRita** [comment] 2023-01-12 14:36
Hi @jokn74 

Thank for your report and your precision, with this new details. I reproduce the issue with PrestaShop version 8.0.1 and not with the version 1.7.8.8. as we can see : 

[Untitled_ Jan 12, 2023 3_27 PM.webm](https://user-images.githubusercontent.com/100699445/212093308-4646b658-afdc-4796-8571-c2f8eb01d073.webm)

 Nice catch ! It's a regression ! I'll add it to the patch backlog.

We can see also that we haven't this issue with color : 

[Untitled_ Jan 12, 2023 3_25 PM.webm](https://user-images.githubusercontent.com/100699445/212093127-3b3072b6-1695-4cfe-8a1a-18912a9b764c.webm)


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you !

**Comment by arcanewater** [comment] 2023-02-17 12:59
This one is kinda annoying would be good for 8.0.2 fix because the only way is to sort through sql now

**Closed as completed** 2023-04-19 09:43 UTC
Labels: Bug, Minor, BO, Attributes, Regression, PR available, Verified, 8.0.1
