### ISSUE TITLE
PHP Fatal error. 1.7.6.3 + PHP 7.1.30. Random blank page

### ISSUE THREAD

**Issue by alvijo** [PrestaShop/PrestaShop#18117] opened 2020-03-12 11:56 UTC
#### Describe the bug

Randomly on BO and FO I get blank page (no error 500).

On log  PHP Fatal error:  Class AppKernel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Serializable::unserialize) in ***/app/AppKernel.php on line 32

Clear cacha solve problem... but I can't be continously cleaning the cache

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1.30

**Comment by khouloudbelguith** [comment] 2020-03-12 11:58
Hi @alvijo,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Hlavtox** [comment] 2020-03-12 12:55
@alvijo Restart the server and see if it happens again.

Do you have cache enabled in the bottom of BO > Performance?

**Comment by khouloudbelguith** [comment] 2020-03-17 10:54
@alvijo, any news?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-16 07:25
Hi @alvijo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-16 07:25 UTC
Labels: Bug, BO, FO, No change required, 1.7.6.3
