### ISSUE TITLE
Bulk action in Module manager is broken

### ISSUE THREAD

**Issue by M0rgan01** [PrestaShop/PrestaShop#32689] opened 2023-05-24 14:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An error appears and asks me to select at least one module for a bulk action, while a module is selected.

Also if I reload the page with modules selected, the select bulk action is disabled while the elements before the reload are still selected

[Capture vidéo du 24-05-2023 16:14:34.webm](https://github.com/PrestaShop/PrestaShop/assets/36233446/1f8db697-7649-4c8b-91d3-3d8e48d9e114)

### Expected behavior

- bulk action works as expected
- reload the page with modules selected makes the bulk action active

### Steps to reproduce

1. Go to BO
2. Go to Modules / Module Manager
3. Select one or more modules
4. Select an action from Bulk action

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment] 2023-05-29 17:17
Hello @M0rgan01 

Nice catch :rocket: :clap: It's a regression on develop branch as I didn't reproduce on 81x.
I will add it to the backlog to be fixed. 
Waiting for your PR :rocket: 

Thanks!

**Comment by boherm** [comment] 2023-06-05 09:43
Seems to be already fixed by https://github.com/PrestaShop/PrestaShop/pull/32664 in develop branch.

**Comment by MatShir** [comment] 2023-06-15 19:44
fixed by https://github.com/PrestaShop/PrestaShop/pull/32664 i

**Closed as completed by MatShir** 2023-06-15 19:44 UTC
Labels: Bug, develop, Minor, BO, Fixed, Module manager, Verified
