### ISSUE TITLE
Bug with reorganization of products within category

### ISSUE THREAD

**Issue by globaldigitalagency** [PrestaShop/PrestaShop#36512] opened 2024-07-08 08:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you click on the "Reorganize" button, and click to begin drag and drop in the "Position" column, it works. If you click elsewhere to start dropping the product at the top or bottom, it won't register.

example : https://sharing.clickup.com/clip/p/t4631900/0b127d4e-447b-4ce5-9b6b-eef7f4e2d1ef/screen-recording-2024-07-04-12%3A01.webm?open=true

### Expected behavior

When the button "Réorganiser" is clicked on, wherever you can click in order to drag and drop the product, in order ton organize the products within the category, the final list have to be saved.

### Steps to reproduce

- go in product list
- select a category (the smallest category level you can)
- clic on button in "Position" column (in the video it is called "Réorganiser")
- case n°1 : clic and maintain this clic on a product line, under column "ID" for example, drop it in first place and save => it doesn't save at all
-  case n°2 : clic and maintain this clic on a product line, under column "Position", drop it in first place and save => the change is saved

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.23

### Your company or customer's name goes here (if applicable).

GDA

**Comment by florine2623** [comment] 2024-07-08 09:02
Hello @AboGDA ,

I tested on PS `8.0.5` and on **develop** branch, on both cases it work correctly.

**8.0.5 :**

https://github.com/PrestaShop/PrestaShop/assets/16019289/bb29b026-4ab5-4226-9e9e-b3ae03b483dd

**develop :**

https://github.com/PrestaShop/PrestaShop/assets/16019289/3ac2e305-bdfc-48ac-b002-a673b711fd14

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing your issue as I can't reproduce it.
Thanks!

**Closed as completed by florine2623** 2024-07-08 09:02 UTC
Labels: Bug
