### ISSUE TITLE
Fuzzy Search - not working

### ISSUE THREAD

**Issue by SlaVkos** [PrestaShop/PrestaShop#22351] opened 2020-12-10 21:42 UTC
**#### Describe the bug**

After update PS from 1.7.6.4 to 1.7.7.0 i saw that fuzzy search not work.

**#### Expected behavior**

I was expecting fuzzy search to work when turned on in settings

**#### Steps to Reproduce**
N/A

**Screenshots**

![obraz](https://user-images.githubusercontent.com/75788592/101833130-cee12100-3b38-11eb-877a-966f32ed2a45.png)
![obraz](https://user-images.githubusercontent.com/75788592/101833166-dbfe1000-3b38-11eb-8eaa-42e112f8326c.png)
![obraz](https://user-images.githubusercontent.com/75788592/101833440-4d3dc300-3b39-11eb-906a-48e2e49664ab.png)
![obraz](https://user-images.githubusercontent.com/75788592/101833461-5464d100-3b39-11eb-99db-97979414cebf.png)

**#### Additional information**

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by florine2623** [comment] 2020-12-11 10:18
Hi @SlaVkos ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Fuzzy search is working correctly :
![Capture d’écran 2020-12-11 à 10 56 11](https://user-images.githubusercontent.com/16019289/101890990-c07b1f80-3ba1-11eb-9600-4281bebc6ff7.png)

You can delete cache, rebuild index if it's not done yet.
Check if you had errors during your upgrade in /adminXXX/autoupgrade/tmp/log.txt
You can check if you have any missing files in Advanced Parameters > Informations

We will close this issue.

Thanks!

**Closed as completed by florine2623** 2020-12-11 10:18 UTC
Labels: Can't reproduce
