### ISSUE TITLE
Serious issue : 8.1 Cannot add feature or cusotmization fields to virtual product

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33792] opened 2023-09-01 09:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Fresh install of Prestashop 8.1.0
Create a new virtual product or edit existing virtual product
Under the details tab, try to add a new feature, but nothing will happen.
Customization field can also not be added.  It seems nothing JS related under the details tab works

In browser dev tools, you'll notice a JS error:

TypeError: Cannot read properties of null (reading 'dataset')
    at product_edit.bundle.js?8.1.0:1922:64

This is probably related to the issuie.

Is there any solution available as this has put a spanner in the works for a site I am developing for a client.

### Steps to reproduce

Fresh install of Prestashop 8.1.0
Create a new virtual product or edit existing virtual product
Under the details tab, try to add a new feature, but nothing will happen.

The issue also affects Prestashop 8.1.1

### PrestaShop version(s) where the bug happened

8.1.0 and 8.1.1

**Comment by paulnoelcholot** [comment] 2023-09-01 13:10
Hello @musaffarpatel

I reproduce the issue with PrestaShop version 8.1.0, 8.1.x and develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

[Products • the future (1).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/d3c4aa99-61a1-4a9a-a1ac-da48a1376189)

**Comment by musaffarpatel** [comment] 2023-09-01 14:03
@paulnoelcholot Thanks, effectively, this bug prevents us from creating virtual products and therefore is a show stopper.  I hope the issue can be prioritised.

**Comment by ChillCode** [comment] 2023-09-02 11:09
Hi

I've had the same issue, since there is no Shipping tab the query to get carriers returns null on Virtual products.

The temp workaround is to modify admin/themes/new-theme/public/product_edit.bundle.js

Replaced at line 1922 the following:

`function(t,e){const n=document.querySelector(t),r=
`
with:

`function(t,e){const n=document.querySelector(t); if (n === null) {return false;};const r=`

I previously added this comment to another issue, sorry.

**Comment by musaffarpatel** [comment] 2023-09-02 11:30
@ChillCode Many thanks for the temp fix

**Comment by MatShir** [comment] 2023-09-08 09:14
@ChillCode don't you feel like contributing the fix ? The 8.1.2 is planned to be released pretty soon, I would be nice to have our fix

**Comment by M0rgan01** [comment] 2023-09-12 07:51
PR: https://github.com/PrestaShop/PrestaShop/pull/33909

**Comment by ChillCode** [comment] 2023-09-12 07:51
Hi @MatShir 

Was going to pull it today but @M0rgan01 did it.

**Comment by MatShir** [comment] 2023-09-12 08:08
What a coincidence! 😉 
Next time, there are plenty of issue on the product page. If you are looking for some, let me know

**Closed as completed** 2023-09-13 19:43 UTC
Labels: Bug, Major, CO, Catalog, Fixed, Verified, 8.1.x, Products Page
