### ISSUE TITLE
Impossible to set SMTP settings - PrestaShop keeps old password

### ISSUE THREAD

**Issue by kornwaikas** [PrestaShop/PrestaShop#22298] opened 2020-12-08 19:01 UTC
#### Describe the bug
EDIT: error is below https://github.com/PrestaShop/PrestaShop/issues/22298#issuecomment-741054468

After update to GoogleWorkspace (Gsuite) i receive this error in Prestashop Configuration. I was asking by chat with Google and they say that my configuration is OK.

I show the code with the chrome inspector and i saw that if i modify the class CSS of the password to show the "******" its show an old password. Prestashop doesn't save my current password.

I fixed it deleting the password in the Prestashop database (ps_configuration) and deleting the passwords stored in chrome.
After that its works again!

- name of domain: percuforum.com (I also try with blank)
- server SMTP: smtp.gmail.com
- user name SMTP: info@percuforum.com
- pass: mypass (I recheck it in my gmail)
- SSL / 465 (I also try with TLS / 587)

#### Screenshots
```
Error: Please check your settings

Failed to authenticate on SMTP server with username "info@percuforum.com" using 3 possible authenticators. 
Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. 
Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials 20sm5110984wmk.16 - gsmtp ". 
Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. 
Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials 20sm5110984wmk.16 - gsmtp ". 
Authenticator XOAUTH2 returned Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. 
Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials 20sm5110984wmk.16 - gsmtp ".
```

#### Additional informations

- Prestashop version: 1.7.7.0
- PHP version:

**Comment by matks** [comment] 2020-12-08 21:06
Hi @kornwaikas I had the same issue recently. This is not a bug in PrestaShop. This is an issue about gmail not trusting PrestaShop.

You can see many questions (and solutions) on Google about this topic:
- https://stackoverflow.com/questions/42558903/expected-response-code-250-but-got-code-535-with-message-535-5-7-8-username
- https://support.google.com/mail/thread/40210887?hl=en
- https://support.google.com/mail/thread/5621336?hl=en

PrestaShop allows sending mail with SMTP but Gmail is a bit ... "paranoid" 😅

**Comment by kornwaikas** [comment] 2020-12-08 21:23
> e issue recently. This is n

I show the code with the chrome inspector and i saw that if i modify the class CSS of the password to show the "******" its show an old password. Prestashop doesn't save my current password.
I fixed it deleting the password in the Prestashop database (ps_configuration) and deleting the passwords stored in chrome.
After that its works again!

**Comment by matks** [comment] 2020-12-08 21:51
> > e issue recently. This is n
> 
> I show the code with the chrome inspector and i saw that if i modify the class CSS of the password to show the "******" its show an old password. Prestashop doesn't save my current password.
> I fixed it deleting the password in the Prestashop database (ps_configuration) and deleting the passwords stored in chrome.
> After that its works again!

Hoho 🧐 that is interesting

**Comment by SimonGrn** [comment] 2020-12-09 17:56
Hello @kornwaikas,

we're not really able to reproduce this issue as is. However one of our testers said that she solved a similar issue by changing the browser and going to the settings page in incognito mode.
Can you try, please ?

This bug doesn't seem to be tied to PrestaShop per se, but is more about the browser not recognizing the fields properly and filling them weirdly.

If you're able to find a way to 100% reproduce it, we'll be happy to investigate further.

Thank you !

**Comment by hibatallahAouadni** [comment] 2020-12-29 15:20
Hello @kornwaikas ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-29 15:20 UTC
Labels: Bug, BO, Email, No change required, 1.7.7.0

**Comment by Betafer** [comment] 2022-12-05 08:36
i also have this problem ps 1.7.8.7 and chrome since 108.0.5359.94

**Comment by hectoruvh** [comment] 2023-03-02 04:18
Using a different browser worked for me. Also tried putting in the password and tabbing to the send button which also worked

**Comment by TimonAndries** [comment] 2023-06-01 08:14
I have the same issue with ps 1.7.8.7, i've tried 3 different browsers and also incognito mode. Where in the database I can find this field? so I can just put the password in there.

**Comment by matks** [comment] 2023-06-01 08:23
I think it's `PS_MAIL_PASSWD` in `ps_configuration` SQL table.

**Comment by TimonAndries** [comment] 2023-06-01 08:29
Thanks! That did the trick for me.
