### ISSUE TITLE
Carrier restrictions on products and checkout/order confirmation

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#23555] opened 2021-03-08 09:35 UTC
#### Describe the bug

Having a product A and product B.
We set the available carrier for product A to be the X.
We set the available carrier for product B to be the Y.

Adding A and B on cart.
On the carrier step, we only see one carrier (like the Y) choice.

Choose it and process the payment.
On the confirmation page, we see only one order (with product A, carrier X) and nothing about the other order created.

#### Expected behavior

Handle separate package as before (1.6 of PrestaShop) and allow the customer to choose any carrier on each package, and show them on confirmation page.

#### Steps to Reproduce

See point 1.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-03-08 13:27
Hello @PrestaEdit 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9594. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-08 13:27
Duplicate of #9594

**Closed as completed by hibatallahAouadni** 2021-03-08 13:27 UTC
Labels: Duplicate

**Comment by PrestaEdit** [comment] 2021-03-08 13:29
Ouch'.
