### ISSUE TITLE
Issue status resets to Open in customer service

### ISSUE THREAD

**Issue by ianronald** [PrestaShop/PrestaShop#18382] opened 2020-03-31 11:15 UTC
We use Prestashop to run www.seedpotatoesdirect.co.uk.

Infrequently and unpredictably the customer service status on closed issues resets to open. This means that we can no longer see which issues we have handled and which still require attention.

#### Expected behavior

Once the status is set to Closed it should not change unless the topic is re-opened.

#### Steps to Reproduce

BO/Customer Service

Cannot reproduce. Just happens periodically.

#### Additional information

This has happened on all previous version of Prestashop we have used from 1.6. 

* PrestaShop version: 1.7.6.4
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-03-31 11:37
Hi @ianronald,

I did not manage to reproduce the issue with PS1.7.6.4.
The Thread is Re-opened only if I click manually on the "Re-open" button.
![image](https://user-images.githubusercontent.com/16067358/78022080-a6bbe400-7354-11ea-8f45-86469b6c86ac.png)

Did you use any custom module or have you any override related to this?

Thanks!

**Comment by ianronald** [comment] 2020-03-31 12:31
Hi @khouloudbelguith 

Thank you so much for the response. Forgive me but I have not explained clearly. The problem is on the summary screen - see screenshot. As we process the topics from customers we mark them as closed. For example the topic ID 68702 is green at present but once handled it will be red.

Then the summary screen has many red topics. Infrequently these red topics all go green again. We lose track then of which topics have been closed.

I realise this is difficult since I cannot reproduce but it has happened to us several times over the last few months.

We use a custom theme - panda, but have no installed modules for customer service - this is core Prestashop.

I hope that is clearer?


[Screenshot 2020-03-31 at 13.19.37.pdf](https://github.com/PrestaShop/PrestaShop/files/4408997/Screenshot.2020-03-31.at.13.19.37.pdf)

**Comment by khouloudbelguith** [comment] 2020-03-31 15:10
@ianronald, 
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ianronald** [comment] 2020-03-31 15:13
@khouloudbelguith 

Thanks I will do my best and get back to you.

**Comment by khouloudbelguith** [comment] 2020-03-31 15:19
@ianronald, thanks!
Waiting for your feedback.

**Comment by ianronald** [comment] 2020-04-01 09:45
@khouloudbelguith 

Ok I have done my best on this. I am not a programmer just a Prestashop user (and a happy one btw) so please forgive if I have provided the wrong information.

- host
GoDaddy
- server setup and configuration
GoDaddy service called 2 GB Gen3 VPS
CentOS 6 + cPanel
On the cPanel patching report I see 1.1.1.cpanel.x86_64

- PrestaShop version (source)
[Screenshot 2020-04-01 at 10.36.24.pdf](https://github.com/PrestaShop/PrestaShop/files/4414223/Screenshot.2020-04-01.at.10.36.24.pdf)

Happy to provide the following if you explain how I find them.
- debug mode report
- PHP error logs
- apache error log
- javascript console log

**Comment by khouloudbelguith** [comment] 2020-04-01 11:12
@ianronald, thanks for your feedback.
PS: you can use the following settings to optimize the performances:

```
[Date]
date.timezone = UTC

[Session]
session.auto_start = Off

[PHP]
short_open_tag = Off
display_errors = Off

magic_quotes_gpc = off
; Increase this value if you are able to do it
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
upload_max_filesize = 20M
post_max_size = 22M
; Increase this value if you work with products with a lot of combinations
max_input_vars = 20000
allow_url_fopen = on
```
For more details, you can follow this [link](https://devdocs.prestashop.com/1.7/scale/optimizations/).

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

>Happy to provide the following if you explain how I find them.
debug mode report
PHP error logs
apache error log
javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/, you can find

- `Adding logs` section
- `Enabling Debug Mode + cache` section

Thanks!

**Comment by ianronald** [comment] 2020-04-01 11:55
@khouloudbelguith 

Thanks for the settings info.

I have been looking for the php_error.log file on my server using cPanel. I cannot find any file anywhere with php_error in the name.

Any tips please?

**Comment by khouloudbelguith** [comment] 2020-04-01 12:02
@ianronald, 
> cannot find any file anywhere with php_error in the name.

If you don't have it, you should ask to your hosting provider.

Thanks!

**Comment by ianronald** [comment] 2020-04-20 12:58
@khouloudbelguith 

Hi again,

I asked a technical colleague to look at the php log and they tell me there was nothing on it to help in understanding the problem.

We have now enabled debug mode as our trading has become more normal (covid-19 made us very very busy) and have the following errors:

[2] count(): Parameter must be an array or an object that implements Countable

[8] iconv(): Detected an illegal character in input string

In addition the problem with the customer service screen resetting all status to open and removing historic actions taken per customer message has repeated. We continue to have an error saying 'message is empty cannot import it'.

Does that help you?

Regards
Ian

**Comment by ianronald** [comment] 2020-04-22 08:27
@khouloudbelguith 

Was that information helpful? We have a quiet period before we are busy selling again in 2 weeks so I have time to look into this further. Please advise. Thanks.

**Comment by khouloudbelguith** [comment] 2020-04-23 14:31
HI @ianronald, 

>[8] iconv(): Detected an illegal character in input string

Could you please check if the `iconv` extension is well installed in your server.

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4523133/phppsinfo.php.zip)

1.  Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by LouiseBonnard** [comment] 2020-05-20 08:51
Dear @ianronald, since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can provide more details, thank you very much!

**Closed as completed** 2020-05-20 08:52 UTC
Labels: Bug, BO, Customer service, No change required, 1.7.6.4
