### ISSUE TITLE
Customer Reassurance module issues

### ISSUE THREAD

**Issue by KEDYPACK** [PrestaShop/PrestaShop#25358] opened 2021-07-15 10:41 UTC
#### Describe the bug

I encountered a bug on the prestashop 1.7.6 module functionality --- "Customer Reassurance" is not working correctly.

the link URL that we put in the corresponding camps via the configuration page, does not take into account.
on the product page, when we click on the link we configured, it directs to another page, but it does not respect the configuration we made on the module.

in Block Content, we created 3 contents,

the first is "Secure payment", direction: none, so we didn't set the link:
result: he directed us to a "delivery" page url: https://domaine/index.php?id_cms=1&controller=cms

2nd is "Delivery 24 / 72h *", direction: url link, so: https://domaine/index.php?id_cms=1&controller=cms
result: he directed us to another "return within 15 days" page url: https://domaine/index.php?id_cms=3&controller=cms

3rd is "Return under 15 days *", direction: url link, so: https://domaine/index.php?id_cms=3&controller=cms
result: he directed us to another "return within 15 days" page url: https://domaine/index.php?id_cms=3&controller=cms

but i tried to put aure url to know if it works correctly:
so url I put for 3rd is: https://domaine/index.php?id_cms=1&controller=cms

but it is still directing to the "Return under 15 days *" page, so: url: https://domaine/index.php?id_cms=3&controller=cms

#### Expected behavior

I expect a correct function instead so:

in Block Content, we created 3 contents,

the first is "Secure payment", direction: none, so we didn't set the link:
result: by clicking on the text "Secure payment", it must not lead to a page. no effect.

2nd is "Delivery 24 / 72h *", direction: url link, so: https://domaine/index.php?id_cms=1&controller=cms
result: it should go to the "Delivery" page url: https://domaine/index.php?id_cms=1&controller=cms

3rd is "Return under 15 days *", direction: url link, so: https://domaine/index.php?id_cms=3&controller=cms
result: it must lead to the "return within 15 days" page url: https://domaine/index.php?id_cms=3&controller=cms

#### Steps to Reproduce

1. Go to 'BOoffice presta 1.7.6 '
2. Click on 'Module --- module manager --- "designates & navigation" customer Reassurance '---- Content --- edit "Secure payment"'
3. Scroll down to 'Block reinsurance --- down redirection '
4. See error go to the page for importing a product, click on each line

**Screenshots**

See video by clicking here: https://streamable.com/j2jjj3

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: code Libster php édition professional version 5.15.0

**Comment by hibatallahAouadni** [comment] 2021-07-15 11:12
Hello @KEDYPACK 

Please update your request in English. English is the norm on GitHub.
Then notify me :wink: 

Thank you

**Comment by KEDYPACK** [comment] 2021-07-15 13:15
@hibatallahAouadni it is done

**Comment by khouloudbelguith** [comment] 2021-07-16 10:26
Hi @KEDYPACK,

I did not manage to reproduce the issue with PS1775 & The 177x branch (PS1776) using the Customer Reassurance v5.0.0.
I attached a screen record
https://drive.google.com/file/d/1tYqMwqwGkWYnev7HXsnthmo4EsZzJ3rr/view?usp=sharing
What is the exact version of the module did you use?
Did you use multi-languages?

Thanks!

**Comment by KEDYPACK** [comment] 2021-07-19 15:20
Hello,

I uninstalled the module, then I wanted to re-install, but I can't manage anymore. here is the error message: "Error!
Exception returned by the blockreassurance module for install. The locale is invalid "

can you check?
attached the photo in appendix
![WeChat Image_20210719171213](https://user-images.githubusercontent.com/87474058/126184238-e47d6d3e-db05-4a3e-b753-f808eb8034f1.png)
![customer](https://user-images.githubusercontent.com/87474058/126184574-86914f98-d392-4bfb-8627-07df60cb69e3.png)

**Comment by KEDYPACK** [comment] 2021-07-19 15:20
Hi @khouloudbelguith

**Comment by florine2623** [comment] 2021-07-20 08:37
Hello @KEDYPACK ,

Please change your admin link of your shop. This is a public space.

You can download the source code [here](https://github.com/PrestaShop/blockreassurance/releases/tag/v5.0.0) and install the module by clicking on "Upload a module" :
<img width="1229" alt="Screenshot 2021-07-20 at 10 36 38" src="https://user-images.githubusercontent.com/16019289/126289414-6a2f9456-2c40-4071-8e63-e9a00cb387da.png">

**Comment by KEDYPACK** [comment] 2021-07-20 11:03
Hello, @florine2623 

I can not install the module, attached the photo, can you test?
I updated, then configure again, but the problem is still appearing, then I uninstalled to reinstall the .zip that you send it to the result, impossible to install.

**Comment by florine2623** [comment] 2021-07-20 12:36
Hello @KEDYPACK ,

Are you using multi-language in your store ?
If, yes, what languages ?
Send a screenshot of your database for ps_lang please.

**Comment by KEDYPACK** [comment] 2021-07-20 12:56
Hello, @florine2623 

we have created 2 languages, but only the fr is active, here is the screen capture of .tpl

**Comment by florine2623** [comment] 2021-07-21 14:05
Please send a screenshot of your table **ps_lang** please.

**Comment by KEDYPACK** [comment] 2021-07-21 14:37
Hello @florine2623 
![WeChat Image_20210721163201](https://user-images.githubusercontent.com/87474058/126507031-46981423-3498-4873-9c14-fb1779a6f506.png)
![WeChat Photo Editor_20210721163946](https://user-images.githubusercontent.com/87474058/126507667-78b9528b-54fc-443d-829f-98194aad5d08.jpg)

In the end, I deleted the second "Chinese" language, then I successfully installed, then I reconfigured, the question still the same; it directs with wrong URL, then I deactivated the Block Content then I recreated, resulted, when we click on the icon, it directs correctly, but when we smile directly on the text to companion each icon, the problem come back the same.

**Comment by florine2623** [comment] 2021-07-21 15:19
Hello @KEDYPACK ,

Despite our efforts, we were not able to reproduce your issue with the provided information. 
Please check my screen record : https://drive.google.com/file/d/1kaKcUb9Nm88WH3h2dXLvixPN3yMwCAbc/view 
It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
You can contact the support [here](https://www.prestashop.com/en/support) for customised help.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2021-07-21 15:19 UTC
Labels: Bug, FO, Modules, No change required, Blockreassurance, 1.7.6.4
