### ISSUE TITLE
"Virtual" Stock not lowered when adding Product with customization to Cart.

### ISSUE THREAD

**Issue by twazerty** [PrestaShop/PrestaShop#23288] opened 2021-02-17 13:19 UTC
#### Describe the bug

When you add a product to your Cart the stock is lowered. This is visible under the Product Details tab in the frontend. This way you can see how many items there are still left. So you know how many more items you can add to your Cart. This works like a charm, except when you can apply a customization to the product. Then the stock in the frontend is not lowered. 

You can also add more products to your Cart than there is stock. Add 300 with customization. Then again 300 with different customization. No complaining in the Cart even though there are 600 items in your Cart for the same product with a stock of 300. If you go beyond 300 items for either on of the customized product you get a message that there is not enough in stock.

#### Expected behavior

The remaining stock in the frontend should be lowered when adding products with customization to the Cart.

#### Steps to Reproduce

1. Install a fresh copy of Prestashop 1.7.7.1
2. Browse to the "Customizable mug" product in the frontend.
3. Under the product details tab, the stock is 300 items
4. customize the product and hit save
5. Add 1 or more items to the Cart
6. Under the product details tab, the stock is still 300 items instead of 299.
7. Go to the "Mug The best is yet to come" product in the frontend
8. Under the product details tab, the stock is 300 items
9. Add 1 or more items to the Cart
10. Under the product details tab, the stock is lowered to 299.

1. Add 300 items with customization to cart
2. Add another 300 items with customization to cart
3. go to cart
4. no complaining you have 600 items in your cart while there are only 300 in stock.

**Screenshots**

If the issue is not clear I will add some screenshots.

#### Additional information

* PrestaShop version: 1.7.7.1, experienced this behavior on a fresh copy of 1.7.7.1 and on our 1.7.4.2 shop.
* PHP version: 7.1 and 7.3 didn't make any difference

**Comment by hibatallahAouadni** [comment] 2021-02-17 14:31
Hello @twazerty 

Could you pleasse check this issue #9974 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by twazerty** [comment] 2021-02-17 18:54
@hibatallahAouadni 

It looks like it is related. Just like #20948

But those reports don't mention the issue I am presenting. Maybe this is the same issue, maybe it is just more information related to the same cause. The other issues only mention the Cart part were you can order more than there is stock. If you go beyond 300 items from the Cart you actually get a message there is not enough in stock. In my case I am more focusing on the product page where the stock is not lowered giving the user the impression there is an unlimited amount of stock. The user doesn't see the remaining stock lowering.

I ran into this problem when we started to use the plugin "Knowband - Advance Product Attribute/Field", This module also makes use of the customization feature of prestashop, but slightly different. When your customization fields are the same it will increase the amount in the Cart, instead of creating a new product in the cart with the same customization (reuse of the customization id). Result in this case is slight different. In the fronend your can add the same product + customization multiple times, beyond the available stock. In the Cart you get a message that there is not enough stock. 

I am not focusing on the Cart, but on the product page where the stock is not updated.

**Comment by hibatallahAouadni** [comment] 2021-02-22 07:47
Hello @twazerty 

Thanks for the explication :pray: , I just edit the old issue and add your description :wink: 

> I am not focusing on the Cart, but on the product page where the stock is not updated.

As you can see in this issue #9974 I added both problems (in Cart, in Product page).
So, I think we can close your issue as a duplicate :slightly_smiling_face: 

This issue is a duplicate of #9974. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-22 07:47
Duplicate of #9974

**Closed as completed by hibatallahAouadni** 2021-02-22 07:47 UTC
Labels: Bug, FO, Duplicate, Stocks, Product customization, 1.7.4.2, 1.7.7.1
