### ISSUE TITLE
ps_facetedsearch - feature issues

### ISSUE THREAD

**Issue by Varindien** [PrestaShop/PrestaShop#14505] opened 2019-07-05 13:51 UTC
Hello,
Just to notify about a bug due to feature filter  value - tested on a fresh install of PS 1.7.5.2 
by  default filter is not active on demo, active one :  e.g. "Composition" and fill an article with a product feature of Composition.

Even if you active "display" on module configuration page, features filter won't appear.. and sometime do bugging filter (click on an attribute  filter  will render 0 result with no possibility to erase active filters.. i did not go futher on this step .. cause i think is due to the main bug above)

**Additionnal information**
PrestaShop version:  v1.7.5.2
PHP version: v7.1.x
module ps_facetedsearch : v3.0.6

**Comment by khouloudbelguith** [comment] 2019-07-05 14:04
Hi @Varindien,

In fact, the main issue that, the Faceted filter doesn't show attribute selection/feature if a category has only one product with the same attribute or feature.
Your ticket is a duplicate of #11207
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-05 14:04
Duplicate of #11207

**Closed as completed by khouloudbelguith** 2019-07-05 14:04 UTC
Labels: Duplicate, Faceted search

**Comment by Varindien** [comment] 2019-07-05 14:16
Hi @khouloudbelguith,

got it :)
