### ISSUE TITLE
Order payment duplicated depending on order state configuration

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#12588] opened 2019-02-15 12:37 UTC
**Describe the bug**
If a state has these 3 options enabled, when you call validateOrder with this state the order payment is duplicated:

- Consider the associated order as validated.
- Set the order as paid.
- Show delivery PDF.

**To Reproduce**
1. Configure "Awaiting bank wire payment" order state with the 3 options enabled.
2. Create an order paid with bankwire
3. Check order payments

It doesn't happen when you change an order into an state with these 3 options, it only happens when it's called from ValdiateOrder.

**Screenshots**
![image](https://user-images.githubusercontent.com/15104724/52857057-553ba000-3126-11e9-9e0e-4efae9305fb6.png)
![image](https://user-images.githubusercontent.com/15104724/52857133-80be8a80-3126-11e9-97d7-e75e87efda7f.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-02-15 13:46
Hi @idnovate,

Thanks for your report.
I manage to reproduce the issue with ps1.7.5.0 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/52860677-68ec0400-3130-11e9-87de-90dae06f66fe.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

A similar previous reported in the forge: http://forge.prestashop.com/browse/BOOM-4196
Thanks!

**Comment by ntiepresta** [comment] 2019-02-18 11:26
Hi,

Same issue with Ps1.7.5.1 build1 and the develop branch.
Thanks!

**Comment by flexcodenet** [comment] 2019-04-07 13:58
Hi,
Same issue with Ps 1.7.5.0.

Thanks.

**Comment by flexcodenet** [comment] 2019-04-09 13:31
Any solution for this bug?

**Comment by khouloudbelguith** [comment] 2019-04-09 13:36
Hi @flexcodenet,

Sorry, not yet.

**Comment by Prestaworks** [comment] 2019-08-20 10:59
This issue is still present in 1.7.6.0 (it has been in Prestashop since 2015)

**Comment by khouloudbelguith** [comment] 2019-08-20 11:02
@Prestaworks, sorry, it is not fixed yet.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by Prestaworks** [comment] 2019-08-21 06:55
Hi,

Maybe the software designer can help expain how it is supposed to work? today the payments are stored in orderpayments and invoicepayments and when a status is set with payed=1 it creates orderpayments if there are no invoicepayments. I do not want to try to fix this unless I know how it is supposed to work.

**Comment by khouloudbelguith** [comment] 2019-08-29 15:42
Same issue with PS1.7.6.1
![image](https://user-images.githubusercontent.com/16067358/63955010-f2837380-ca7b-11e9-9603-6b82df27024d.png)
Thanks!

**Comment by Prestaworks** [comment] 2019-08-30 07:23
I made a new pull request now for 1.7, basicly the same fix as was suggested 2018.
https://github.com/PrestaShop/PrestaShop/pull/15322

**Comment by khouloudbelguith** [comment] 2020-04-07 09:51
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/18468
Ping @matks @erouvier29 

Thanks!

**Closed as completed** 2020-06-10 15:37 UTC
Labels: Bug, Minor, BO, Order, Order statuses, Fixed, 1.7.5.0, 1.7.6.0, 1.7.6.1, PR available

**Comment by mihaiSeoCup** [comment] 2021-05-31 20:10
in the PaymentModule.php you need to comment out OR CHANGE:
--  line 377
if (!$order->addOrderPayment($amount_paid, null, $transaction_id)) {
                    PrestaShopLogger::addLog('PaymentModule::validateOrder - Cannot save Order Payment', 3, null, 'Cart', (int) $id_cart, true);

                    throw new PrestaShopException('Can\'t save Order Payment');
                }

location:
/root/classes/PaymentModule.php

**At this time i';m not sure what that fix wanted to do. From my point of view you could rewrite this but the conditons should be CHECKING IF THE PAYMENT INVOICE EXISTS OR IF THE PAYMENT METHODE IS DIFERENT THAN ONE OF THE DEFAULT ONES**

// if( !empty($order->invoice_number) && isset($order->invoice_number)   ) {
if( $order->module != "ps_cashondelivery" ) {
                if (!$order->addOrderPayment($amount_paid, null, $transaction_id)) {
                    PrestaShopLogger::addLog('PaymentModule::validateOrder - Cannot save Order Payment', 3, null, 'Cart', (int) $id_cart, true);

                    throw new PrestaShopException('Can\'t save Order Payment');
                }

}

PS: i conditioned it by what i needed, you guys could change it to fit yout situation.
