### ISSUE TITLE
BO - The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by pro8181** [PrestaShop/PrestaShop#20438] opened 2020-08-04 07:09 UTC
#### Describe the bug

I can't edit / change / delete installed modules on my site and can't change them positions.

#### Expected behavior

I want to edit / delete / change my installed modules on my site.

#### Steps to Reproduce

1. Go to menu 'Ulepszenia'
2. Click on 'Moduły' (img presta1 attached)
3. Click on 'Wybrane'
4. See error: 
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Another:
1. Go to menu 'Ulepszenia'
2. Click on 'Wygląd' (img presta2 attached)
3. Click on 'Pozycje'
4. See error: 
This page isn’t workingtomishop.pl is currently unable to handle this request.
HTTP ERROR 500
![presta1](https://user-images.githubusercontent.com/69017456/89263619-e1e76000-d631-11ea-910b-4bf7d09d2fa7.JPG)
![Presta2](https://user-images.githubusercontent.com/69017456/89263660-f0357c00-d631-11ea-9714-0b2f644a1724.JPG)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.3.0
* PHP version:

**Comment by khouloudbelguith** [comment] 2020-08-04 08:01
Hi @pro8181,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-24 09:34
Hi @pro8181,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-24 09:34 UTC
Labels: Bug, BO, Modules, Positions, No change required
