### ISSUE TITLE
Assigning states to zone in bulk is not working.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#17540] opened 2020-02-07 08:35 UTC
**Describe the bug**
In menu: "International > Locations > States"    assigning multiple states to zone (bulk action) doesn't do anything, only refreshes the page without any change or any new inputs. 

**To Reproduce**
1. Go to 'International > Locations > States'
2. Select few states
3. Scroll down to bottom, to button 'bulk actions'
4. Choose "assign to a new zone"
5. Page refreshes and nothing changes.
 

**Additional information**
PrestaShop version:  1.7.6.1
PHP version: 7.2.18

**Comment by khouloudbelguith** [comment] 2020-02-07 08:37
Hi @grzegorzgit,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9971
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-07 08:37
Duplicate of #9971

**Closed as completed by khouloudbelguith** 2020-02-07 08:37 UTC
Labels: Duplicate, States
