### ISSUE TITLE
IpAddressType not reusable without template custumization

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19552] opened 2020-06-04 06:40 UTC
#### Describe the bug

IpAddressType cannot be resused in the form_rest.

![image](https://user-images.githubusercontent.com/4932192/83721515-8140a480-a63b-11ea-9c9c-ca0bcf496679.png)

1. you need to assign in you Admin Controller a specific parameter `'currentIp' => $request->getClientIp()`
2. you need to call specifically the form_row. This require that you define all previous fields Type to keep order of your form.
```twig
{{ form_row(settings.CHECKBOFORM_IPADDRESS, {'currentIp': currentIp}) }}
```

#### Expected behavior

Refactor:
* Use dependency injection on IpAddressType to hydrate request->getClientIp() and assign currentIp to the block ip_address_text_widget.
* Js location of IP component looks in the wrong place `admin-dev/themes/new-theme/js/maintenance-page/ip-input` instead of `admin202/themes/new-theme/js/components/form/ip-input`

#### Steps to Reproduce

1. Install PS 1.7.7 and [sample module](https://github.com/202ecommerce/checkboform)
2. See the problem on configurations.html.twig

#### Additional information

* PrestaShop version: 1.7.6 / 1.7.7
* PHP version: N/A

**Comment by florine2623** [comment] 2020-06-04 12:58
Hey @PrestaShop/prestashop-core-developers ,
Could you check @202-ecommerce request ?
Thanks!

**Comment by PierreRambaud** [comment] 2020-06-05 13:16
Hey @zuk3975 or @matks I think the `IpAddressType` should contain a default value for `current_ip` wdyt?

**Comment by JevgenijVisockij** [comment] 2020-11-26 07:18
Hey. I will solve this when I simplify the MaintenanceType. The way I see it at the very least you should be able to provide current IP from form type instead of needing to get it from twig. Having default value could also work.

**Comment by matks** [comment] 2021-04-24 12:16
Hello everyone, the simplification of MaintenanceType has been merged https://github.com/PrestaShop/PrestaShop/pull/22379.

@PrestaShop/qa-team could it be possible to verify if issue is fixed for 1.7.8 ?

**Comment by hibatallahAouadni** [comment] 2021-07-13 13:43
Hello everyone,

I didn't reproduce any issue following these steps:

1. Under **PS1.7.7.5** > **modules** 
2. I cloned your module https://github.com/202ecommerce/checkboform
3. **BO** > **IMPROVE** > **Modules** > **Module Catalog**
4. install **Check form** module

See the attached screen record below:

https://drive.google.com/file/d/1yi2udcZ1wOsPpGmf8U2lwEPgse7gPT53/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-08-04 10:38
Ping @202-ecommerce friendly reminder :wink:

**Comment by khouloudbelguith** [comment] 2021-08-20 09:22
Hi @202-ecommerce,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2021-08-20 09:22 UTC
Labels: Bug, BO, Refactoring, No change required, Developer Feature, migration, 1.7.7.5
