### ISSUE TITLE
dashproducts - PHP Warning:  Illegal string offset 'id_category_default' in dashproducts.php : 224

### ISSUE THREAD

**Issue by crv248** [PrestaShop/PrestaShop#30653] opened 2022-12-22 16:58 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've this error in my log's:
PHP Warning:  Illegal string offset 'id_category_default' in /var/www/vhosts/shop.pompadour.es/httpdocs/modules/dashproducts/dashproducts.php on line 224

Also in the section on the dashboard im getting some NULL categories and other with the value ROOT.
![image](https://user-images.githubusercontent.com/15896239/209186445-d95a31db-5917-4e00-89df-47f3f7a50886.png)

Reviewing the code I noticed that the problem is in this change in the last upgrade(v2.1.2) of the module: 
![image](https://user-images.githubusercontent.com/15896239/209186591-75980983-8ab2-44c4-968e-8c2dc5199606.png)

### Steps to reproduce

1 - Go to Dashboard
2 - Sales and product block
3 - Best sellers section

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

dashproducts - v2.1.2

**Comment by florine2623** [comment] 2022-12-22 17:13
Hello @crv248 ,

Using module Dashboard Products v2.1.1, I can't reproduce your issue.

The categories are correct:
<img width="1008" alt="Screenshot 2022-12-22 at 18 09 29" src="https://user-images.githubusercontent.com/16019289/209189430-71a654ec-d48c-45f2-9da0-f0b710d3b18d.png">

I don't have any log error.
I checked in `Advanced Parameters > Logs` and in `/var/log/`

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2022-12-22 17:13 UTC
Labels: Bug, Invalid

**Comment by crv248** [comment] 2022-12-22 17:31
Hi @florine2623, the problem is with the version 2.1.2, no 2.1.1 as you used.
