### ISSUE TITLE
Your PrestaShop version is up to date

### ISSUE THREAD

**Issue by kris711** [PrestaShop/PrestaShop#15845] opened 2019-10-05 17:49 UTC
**Describe the bug**
Since Prestashop 1.7.5.2 the PrestashopUpdates box on the right side tells only "
"Your PrestaShop version is up to date"
Even if its not.

**To Reproduce**
Nothing changed 

**Screenshots**
I guess its clear

**Additional information**
PrestaShop version: 1.7.6.2 
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-10-07 08:43
Hi @kris711,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14688
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-07 08:44
Duplicate of #14688

**Closed as completed by khouloudbelguith** 2019-10-07 08:43 UTC
Labels: Duplicate
