### ISSUE TITLE
Not all carriers are listed under payment preference

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#16385] opened 2019-11-13 07:20 UTC
**Describe the bug**

**To Reproduce**
1. Create a number of carriers, using different shipping methods (dhl, ups etc)
2. got to payment => preferences at the bottom (with me) only 2 are listed (in store pickup and the first of the UPS carriers)
3. I have to manually add the extra carriers in the database in order to even have payment methods showing 
4. And if I press save on the preferences page all the extra carriers are lost in the database again
![carriers](https://user-images.githubusercontent.com/3520123/68741626-6c90b680-05ee-11ea-8c89-5b34b70f1902.JPG)
![preferences](https://user-images.githubusercontent.com/3520123/68741636-70bcd400-05ee-11ea-823d-996e934d0bc2.JPG)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7

**Comment by khouloudbelguith** [comment] 2019-11-13 08:35
Hi @sickboards,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12379 to fix the issue.
It is fixed in the PS1.7.7.0.
Your ticket is a duplicate of #16094
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-13 08:35
Duplicate of #16094

**Closed as completed by khouloudbelguith** 2019-11-13 08:35 UTC
Labels: Duplicate
