### ISSUE TITLE
Cant enter iframe in cms in 1.7.5

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#12528] opened 2019-02-10 16:46 UTC
**Describe the bug**
i get 404 whit iframe in 1.7.5 in cms pages

**To Reproduce**
1º. go to cms page and make new page
2º. Click in code mode and insert the iframe
3º. See the 404

**Screenshots**
https://youtu.be/5mwD_4GfH4A

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by RUMBuilder** [comment] 2019-02-10 17:28
@LinkOfLight 
Some admin is going to tell you to make sure you've enabled iframes in html fields, and possibly turn off html purifier.
In 1.7.5, go to Shop Parameters>General, and then set "Allow iframes on HTML fields" to YES, and also set "Use HTMLPurifier Library" to NO.

The admin might also tell you to use the dropdown option in the Editor to insert the iframe, as opposed to just entering code mode and pasting it yourself. 

Would love to hear if that works for you, i'm having issue with this as well, and also when adding iframes to product description fields, They've claimed it's not a PS issue, so seeing someone else with iframe issues is of great interest to me. Thanks!

**Comment by MathiasReker** [comment] 2019-02-10 22:59
Please paste the specific code you try to embed, then I can try if I can reproduce your issue.

**Comment by MathiasReker** [comment] 2019-02-10 22:59
`Paste it in code tag`

**Comment by khouloudbelguith** [comment] 2019-02-11 10:11
Hi @LinkOfLight,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1vXNtnjNNYQCULlNC_D3fz6_bJxkGPK6E/view
Thanks to check & feedback.
PS: You need to enable "Allow iframes on HTML fields" in BO => Shop Parameters => General page.
![image](https://user-images.githubusercontent.com/16067358/52556742-bcd3b180-2ded-11e9-8319-e840828af38d.png)

Thanks!

**Comment by LinkOfLight** [comment] 2019-02-11 15:49
i thried to embed `<iframe src="https://e.issuu.com/anonymous-embed.html?u=tecsports.l.&d=catalogo_2019" style="border:none;width:100%;height:500px;" allowfullscreen></iframe>` and i get error 404

**Comment by khouloudbelguith** [comment] 2019-02-11 17:22
@LinkOfLight, thanks for these clarifications.
I tried with ps1.7.5.0, with your code & it is OK.
I attached a video record.
https://drive.google.com/file/d/1jDLjRPugoGtm0yGgQTQU80RejG-VRsyJ/view
Thanks!

**Comment by LinkOfLight** [comment] 2019-02-24 17:57
get 404, i dont know what happend, is only in 1 domain

**Comment by khouloudbelguith** [comment] 2019-02-25 14:41
Hi @LinkOfLight,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-02 07:37
Hi @LinkOfLight,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-02 07:37 UTC
Labels: FO, Can't reproduce, Pages, 1.7.5.0
