### ISSUE TITLE
Elementor editor will not load

### ISSUE THREAD

**Issue by Integraelec** [PrestaShop/PrestaShop#12954] opened 2019-03-18 16:42 UTC
When loading elementor editor for building or viewing a built page. Box will Pop up saying "Page Not found". But the page is showing on the live site. 
![image](https://user-images.githubusercontent.com/48558437/54547021-2ea99880-4962-11e9-9721-9cee5fa61714.png)

**Comment by khouloudbelguith** [comment] 2019-03-18 16:45
Hi @Integraelec,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- PrestaShop version
- The issue on FO / BO
- In which page, have you this issue?
- Steps to reproduce the issue
Thanks!

**Comment by Integraelec** [comment] 2019-03-18 17:17
Thank you for quick response.. See my reply below.

**Comment by khouloudbelguith** [comment] 2019-03-18 17:26
@Integraelec, IQT Elementor editor, is it a module/theme?
Thanks!

**Comment by Integraelec** [comment] 2019-03-18 17:33
I believe yes, Question:


1.       Is our Prestashop version the latest? 1.7.2.2

2.       Has there been a resent automatic update?

3.       Could the module we have be non-compatible with the current version?
[cid:image001.png@01D4DD75.DAF071D0]

**Comment by Integraelec** [comment] 2019-03-18 18:55
Here is the page view on here you access the elemntor – Visual Page builder.

[cid:image001.png@01D4DD81.8851F820]

**Comment by khouloudbelguith** [comment] 2019-03-19 07:58
Hi @Integraelec,

> 1.       Is our Prestashop version the latest? 1.7.2.2

No, the latest version PrestaShop is PS1.7.5.1, you can download it from our official link: https://www.prestashop.com/en/previous-versions

> 2.       Has there been a resent automatic update?

Yes, you can use this module: https://addons.prestashop.com/en/data-migration-backup/5496-.html
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

>3.       Could the module we have be non-compatible with the current version?

Yes, it could be, you need to check the issue with the module author

About your screenshot, it is not attached, you need to login to GitHub & upload the image

Thanks!

**Comment by Integraelec** [comment] 2019-03-19 14:01
Thank you for the guidance. I’ll make the updates and test prior to going live.
Appreciate the quick response.
Rgds,
Mark

**Comment by khouloudbelguith** [comment] 2019-03-19 14:05
@Integraelec, so can I close the issue?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-18 15:51
Hi @Integraelec,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-18 15:51 UTC
Labels: No change required
