### ISSUE TITLE
Vat Number and Dni missing from Order View in 1.7.7.x

### ISSUE THREAD

**Issue by maxadp** [PrestaShop/PrestaShop#23215] opened 2021-02-10 16:14 UTC
In Prestashop 1.7.7.x Vat Number and DNI are missing in both Shipping / Inovice address when you go to Order page in backoffice. Vat and Dni is also missing from email and other sections.

**Comment by hibatallahAouadni** [comment] 2021-02-10 16:27
Hello @maxadp 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22979. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-10 16:28
Duplicate of #22979

**Closed as completed by hibatallahAouadni** 2021-02-10 16:27 UTC
Labels: Duplicate
