### ISSUE TITLE
It is not possible to translate "Categories" for ps_facesearch module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#24827] opened 2021-06-05 11:40 UTC
Hi

#### Describe the bug

I need to change "Categories" to "Collections" for the title of the categories of ps_facesearch
I do it from the admin translations and I can see that the "Collezione" is present inside ps_translation table
I've removed all folders inside var/cache/*
but it the front-end there is always "Categorie"
in the theme it is present only an override on ps_facetedsearch.tpl

#### Expected behavior

I want to see the translation done in the traslation admin page about this module shown in the front-office

#### Steps to Reproduce

1. go in the admin translation page and change the translation on "Categories" of italian language "Categorie" into "Collezioni"

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/120890391-af681400-c602-11eb-9ed2-e23f500c6db4.png)
![2](https://user-images.githubusercontent.com/653230/120890392-b000aa80-c602-11eb-9bb3-7d48055868d5.png)
![3](https://user-images.githubusercontent.com/653230/120890394-b0994100-c602-11eb-93bb-749ac3944cad.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

bye

**Comment by hibatallahAouadni** [comment] 2021-06-07 08:45
Hello @maofree 

I didn't manage to reproduce the issue with PS1.7.7.4, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/120986890-57a1e800-c77d-11eb-990f-d3279e36adc1.png)

![image](https://user-images.githubusercontent.com/23308427/120986779-3ccf7380-c77d-11eb-89b8-890ab3947e9e.png)

Please check and feedback.
Thanks!

**Comment by Maofree** [comment] 2021-06-07 08:53
Hi
can you try with a child theme to do the same operation?
I get this problem using a child theme
thanks

**Comment by florine2623** [comment] 2021-06-11 15:13
Hello @maofree ,

I was able to reproduce the issue with PrestaShop version 1.7.7.4, even after clearing the cache, so I can confirm that this behavior is indeed a bug.
**_In BO :_**
<img width="257" alt="Screenshot 2021-06-11 at 15 46 05" src="https://user-images.githubusercontent.com/16019289/121708830-3c660e00-cad8-11eb-8839-ce0c927a9c38.png">
**_In FO :_**
<img width="1161" alt="Screenshot 2021-06-11 at 16 04 36" src="https://user-images.githubusercontent.com/16019289/121708835-3ec86800-cad8-11eb-9b86-ae4bd19cee37.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-06-13 22:48
Hello @maofree 

Could you please confirm if this bug is a regression or not? did you encounter this bug only with Faceted Search v3.7.1?
Please check and feedback.

Thanks!

**Comment by Maofree** [comment] 2021-06-14 14:28
Hi
I tested it only on the version 3.7.1

**Comment by Hlavtox** [comment] 2023-01-30 17:59
Just tested on develop, translation is working correctly. 👍

![Faceted](https://user-images.githubusercontent.com/6097524/215556718-6c7a2269-ae89-4a09-ab69-ae67d5e7f8e6.jpg)
![facetedbo](https://user-images.githubusercontent.com/6097524/215556719-ec398c11-e854-4edc-aeff-b808335791c2.jpg)

**Closed as completed by Hlavtox** 2023-01-30 17:59 UTC
Labels: Bug, Minor, FO, Translations, Faceted search, Fixed, 1.7.7.4, Verified, Module
