### ISSUE TITLE
Cannot give permissions to modules pages

### ISSUE THREAD

**Issue by rokaszygmantas** [PrestaShop/PrestaShop#12656] opened 2019-02-21 12:05 UTC
**Describe the bug**
When trying to give employee profile permissions for Module Catalog page, it fails and doesn't save new permissions. 

**To Reproduce**
1. Go to BO->Advanced parameters->Team->Permissions, select any profile other than super admin.
2. Click on "All" checkbox on the top right of first permissions panel (this one: https://prnt.sc/mo4j76)
3. Wait to get a success message.
4. Reload the page.
5. Scroll down to "Module Catalog" permissions.
6. You will see that several checkboxes are not checked and therefore you won't have access to what is not checked.

**Screenshots**
After giving ALL permissions and reloading the page it still shows those as not given: https://prnt.sc/mo4hao

**Additionnal information**
PrestaShop version: develop branch

Permissions are saved via AJAX and when saving it results in 500 error, with this error message:
```Cannot find role slug``` https://prnt.sc/mo4m8y

**Comment by khouloudbelguith** [comment] 2019-02-21 13:29
Hi @rokaszygmantas,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11547
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-21 13:30
Duplicate of #11547

**Closed as completed by khouloudbelguith** 2019-02-21 13:29 UTC
Labels: Duplicate

**Comment by Zzareb** [comment] 2020-01-28 09:40
For those encountering the issue, this solved the problem for me ; 

Connect to your DB interface;

`
INSERT INTO `ps_authorization_role`(`id_authorization_role`, `slug`) VALUES 
(NULL, "ROLE_MOD_TAB_ADMINPARENTMODULESCATALOG_CREATE"),
(NULL, "ROLE_MOD_TAB_ADMINPARENTMODULESCATALOG_READ"),
(NULL, "ROLE_MOD_TAB_ADMINPARENTMODULESCATALOG_UPDATE"),
(NULL, "ROLE_MOD_TAB_ADMINPARENTMODULESCATALOG_DELETE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESCATALOG_CREATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESCATALOG_READ"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESCATALOG_UPDATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESCATALOG_DELETE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESNOTIFICATIONS_CREATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESNOTIFICATIONS_READ"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESNOTIFICATIONS_UPDATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESNOTIFICATIONS_DELETE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESUPDATES_CREATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESUPDATES_READ"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESUPDATES_UPDATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESUPDATES_DELETE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESMANAGE_CREATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESMANAGE_READ"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESMANAGE_UPDATE"),
(NULL, "ROLE_MOD_TAB_ADMINMODULESMANAGE_DELETE")
`

Then the slugs are found, and you can adjust the permissions.
