### ISSUE TITLE
Fresh install always fails at step:  Create databases tables  1: HTTP 500 - error-

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#37323] opened 2024-11-05 19:37 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 I wanted to try out prestashop. I tried to install a fresh install.

It always fails at this step:

Create databases tables

1: HTTP 500 - error-

An error occurred during installation...

You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

When i try to restart the installation by clicking on the link i see: 

`https://mysite.com/shop/install/index.php?restart=true`

 I tried 2 different versions of prestashop and i get the same issue

PrestaShop 1.7.8.10
PrestaShop 8.1.7

PHP Version 7.4.33
DOM/XML enabled
libXML support active
SimpleXML support enabled

Server information: Linux # 1 SMP Thu Feb 22 12:55:50 UTC 2024 x86_64
Server software version: LiteSpeed
Memory limit: 512M
Max execution time: 300
Upload Max File size: 512M
MySQL version: 10.6.19-MariaDB-cll-lve
MySQL server: 127.0.0.1
Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPDO 

```
Notice: Undefined property: DOMDocument::$documentElement in 
/home/max/mysite.com/shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php on line 590

Fatal error: Uncaught Error: Call to a member function getAttributeNS() on null in 
/home/max/mysite.com/shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:590 Stack trace: #0 
/home/max/mysite.com/shop/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php(89): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->validateSchema(Object(DOMDocument), false) #1 
/home/max/mysite.com/shop/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php(146): Symfony\Component\Config\Util\XmlUtils::parse('<?xml version="...', Array) #2 
/home/max/mysite.com/shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(397): Symfony\Component\Config\Util\XmlUtils::loadFile('/home/max/...', Array) #3 
/home/max/mysite.com/shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(49): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFi in 
/home/max/mysite.com/shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php on line 590
```

![Image](https://github.com/user-attachments/assets/90541691-c1b6-4b63-be35-2471d603316d)

### Steps to reproduce

It's not something that can be reproduced. I suspect it's an issue with my server? I search but have not seen anyone else have the same problem as me.

### PrestaShop version(s) where the bug happened

PrestaShop 1.7.8.10 & PrestaShop 8.1.7

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment] 2024-11-06 09:19
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Please make sure your system requirements are met : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

Thank you

**Closed as completed by florine2623** 2024-11-06 09:19 UTC
Labels: Bug
