### ISSUE TITLE
Enable product image does not work

### ISSUE THREAD

**Issue by presmobic** [PrestaShop/PrestaShop#16384] opened 2019-11-13 05:58 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Backoffice > Orders > Invoices'
2. Click on 'Enable product image  = Yes'
Product Images is not showing in PDF invoice, Delivery.
When __PS_BASE_URI__ = / -> print PDF -> Product Image does not show
When __PS_BASE_URI__ = /subdirectory -> print PDF -> Product Image is showing
This error caused in PDF Delivery Slips
**Additional information**
PrestaShop version: 1.7.6.1
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-11-13 08:32
Hi @presmobic,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1AztooBbutegAVFWsCVZud5ezucxxyyz3/view
SSL is enabled in your shop?

Thanks!

**Comment by presmobic** [comment] 2019-11-13 09:29
Hi, your shop is https://prestashop.com/1761/
So it works, if you install in ROOT, it will not work
https://prestashop.com/1761 -> it works
https://prestashop.com/ -> it does not work

**Comment by khouloudbelguith** [comment] 2019-11-13 10:25
@presmobic, no, it is not the exact problem
https://drive.google.com/file/d/1e2yqcKvMNY40iCadqTzQXzJultfTbUi9/view

Thanks!

**Comment by presmobic** [comment] 2019-11-13 10:52
File: public_html/classes/pdf/HTMLTemplateInvoice.php
Line 210:
$order_detail['image_tag'] = preg_replace(
                        '/\.*' . preg_quote(__PS_BASE_URI__, '/') . '/',
                        _PS_ROOT_DIR_ . DIRECTORY_SEPARATOR,
                        ImageManager::thumbnail($path, $name, 45, 'jpg', false),
                        1
                    );
When
__PS_BASE_URI__ = /
_PS_ROOT_DIR_  = /home/u8140p9460/domains/edsmartparts.nl/public_html
DIRECTORY_SEPARATOR = /
`ImageManager::thumbnail($path, $name, 45, 'jpg', false) = <img src="../img/tmp/product_mini_1038_0.jpg" alt="" class="imgm img-thumbnail" />`
--> `$order_detail['image_tag'] = <img src="/home/u8140p9460/domains/edsmartparts.nl/public_html/img/tmp/product_mini_1038_0.jpg" alt="" class="imgm img-thumbnail" />`
-> Can not display this IMAGE in PDF
But if` $order_detail['image_tag'] = <img src="../tmp/product_mini_1038_0.jpg" alt="" class="imgm img-thumbnail" />`
-> Image is showing

**Comment by khouloudbelguith** [comment] 2019-11-13 11:07
@presmobic, my base URI is / & it is well displayed
![image](https://user-images.githubusercontent.com/16067358/68758445-21869b80-060e-11ea-9407-c7f31f6897bb.png)

SSL is enabled in your shop?

Thanks!

**Comment by presmobic** [comment] 2019-11-13 11:21
SSL is enabled
You can check SRC attribute: /home/u8140p9460/domains/edsmartparts.nl/public_html/img/tmp/product_mini_1038_0.jpg
-> it does not work when PATH is absolute

**Comment by khouloudbelguith** [comment] 2019-11-13 11:26
@presmobic, I think the issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15088
But as you can see here: https://github.com/PrestaShop/PrestaShop/pull/15109#issuecomment-522501213

It is a problem related to the self-signed certificate.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-13 08:06
Hi @presmobic,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-13 08:06 UTC
Labels: Bug, Invoices, Delivery slip, Image, No change required, 1.7.6.1

**Comment by presmobic** [comment] 2019-12-13 08:31
what is your ticket?

Vào Th 6, 13 thg 12, 2019 lúc 15:07 khouloudbelguith <
notifications@github.com> đã viết:

**Comment by khouloudbelguith** [comment] 2019-12-13 10:36
@presmobic, this issue: #16384 is closed because there is no news for more than 30 days.

Thanks!

**Comment by presmobic** [comment] 2019-12-13 10:45
it is not our module

Vào Th 6, 13 thg 12, 2019 lúc 17:36 khouloudbelguith <
notifications@github.com> đã viết:
