### ISSUE TITLE
Disabling a language, I can't translate product (no language selection in product page)

### ISSUE THREAD

**Issue by pantagru** [PrestaShop/PrestaShop#18147] opened 2020-03-13 15:42 UTC
#### Describe the bug

When I disable the second language, to not show it in the front-end, I can translate pages or categories, but I can't translate the single product: no language selection appears in product page. 

#### Expected behavior

I want to translate all products before showing them translated in the public site.

#### Steps to Reproduce

1. I set localization > Languages > English (second language - the first is italian) edit > Status: NO
2. I go to catalog > product
3. I can't see the language selection, then I can't translate product

**Screenshots**

language selection example (in pages and categories)
![immagine](https://user-images.githubusercontent.com/41157394/76636044-a6e07500-6548-11ea-9e5e-9c2c12246032.png)
language selection in products (not show)
![immagine](https://user-images.githubusercontent.com/41157394/76636119-cd061500-6548-11ea-8546-129a4736747d.png)

#### Additional information

* PrestaShop version: 1.7.2.4
* PHP version: PHP 7.1.33

**Comment by pantagru** [comment] 2020-03-13 15:45
Clarification: If I active the second language, I see the language selection in product.

**Comment by khouloudbelguith** [comment] 2020-03-16 11:59
Hi @pantagru,

Your ticket is a duplicate of #16626
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-16 11:59
Duplicate of #16626

**Closed as completed by khouloudbelguith** 2020-03-16 11:59 UTC
Labels: Duplicate
