### ISSUE TITLE
BO - An error undefined index in Stats page related to statscheckup module when there is a new languages imported and not configured for the new shop 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28485] opened 2022-05-13 08:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error undefined index in Stats page related to `statscheckup` module when there is a new languages imported and not configured for the new shop 

1786 :x: 
![image (5)](https://user-images.githubusercontent.com/92912932/168237764-8f803e11-25a6-42dd-a853-101cec278eee.png)

https://user-images.githubusercontent.com/92912932/168240424-809c7abc-af5a-4201-92cd-8bef03f4cfc0.mp4

1778 :x:
![image](https://user-images.githubusercontent.com/92912932/168237886-1e5bcf64-d87e-4c39-ac33-9ea71ad06020.png)

1785 :x: 

https://user-images.githubusercontent.com/92912932/168239057-9e9c4488-f45d-4487-8d71-a772db18b93f.mp4

### Expected behavior

No error is displayed

### Steps to reproduce

1. BO > International > Localization > Import new packs to add a new languages with the default shop
2. Enable debug mode
3. Enable multisotre
4. Create a new shop
5. Select this new shop created in BO
6. BO > International > Localization > Languages > Check that this new shop created is not configured for the added languages
7. GO to BO > SELL > Stats > click on catalog evaluation
8. See error

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.5 & 1.7.8.6

### PHP version(s) where the bug happened

7.4 & 7.2

### If your bug is related to a module, specify its name and its version

statscheckup

**Comment by florine2623** [comment] 2024-12-24 11:32
I can't reproduce this issue in PS 9.0.0.

https://github.com/user-attachments/assets/14c91b6a-0a14-4320-86f3-68fec70f69ac


So I'm closing it to avoid clogging the backlog.

**Closed as completed by florine2623** 2024-12-24 11:32 UTC
Labels: Bug, Minor, BO, Stats, Multistore, Languages, Fixed, 1.7.7.8, Verified, Module
