### ISSUE TITLE
Link List Module Error 500

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#14455] opened 2019-07-02 13:18 UTC
Go to Modules
Configure Link List Module.
Configure a list and click save
You'll get this error:

Symfony\Component\Debug\Exception\
FatalThrowableError
in modules/ps_linklist/src/Form/LinkBlockFormDataProvider.php (line 294)
     * @throws \PrestaShopException     */    private function updateHook($hookId)    {        $hookName = Hook::getNameById($hookId);        $module = $this->moduleRepository->getInstanceByName(Ps_Linklist::MODULE_NAME);        if (!Hook::isModuleRegisteredOnHook($module, $hookName, $this->shopId)) {            Hook::registerHook($module, $hookName);        }    }}

PrestaShop version: 1.7.5.2

**Comment by khouloudbelguith** [comment] 2019-07-02 13:23
Hi @seederp2p,

I did not manage to reproduce the issue with PS1.7.5.2 & the Link Widget module v3.0.4.
I attached a video record
https://drive.google.com/file/d/1HS9eqMBZ7KYJHIlw03GU4C6-xP64FRNJ/view
What is the exact version of the link widget did you use?

Thanks!

**Comment by seederp2p** [comment] 2019-07-02 13:34
Hi!

I'm using 3.0.4

**Comment by khouloudbelguith** [comment] 2019-07-02 13:41
@seederp2p, did you make an upgrade of this module from a previous version?

Thanks!

**Comment by seederp2p** [comment] 2019-07-02 16:49
I don't remember. But I did upgrade the store from 1.7.5.1 to 1.7.5.2...

**Comment by khouloudbelguith** [comment] 2019-07-03 09:17
@seederp2p, could you please try to uninstall the link widget module with removing the folder & install it again from the Module Catalog page.
You need to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2019-08-02 07:20
Hi @seederp2p, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-02 07:20 UTC
Labels: Bug, BO, Link widget, No change required, 1.7.5.2

**Comment by elrosi** [comment] 2020-02-12 19:09
Hi, 

I have the same error after updating from 1.7.5.2 to 1.7.6.3

[2020-02-12 20:06:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Undefined class constant 'MODULE_NAME'" at /nfsmnt/hosting2_1/6/7/67dcd3ea-4121-4281-af0b-7c0e35976080/profidiet.net/web/modules/ps_linklist/src/Form/LinkBlockFormDataProvider.php line 294 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined class constant 'MODULE_NAME' at /nfsmnt/hosting2_1/6/7/67dcd3ea-4121-4281-af0b-7c0e35976080/profidiet.net/web/modules/ps_linklist/src/Form/LinkBlockFormDataProvider.php:294)"} []

**Comment by khouloudbelguith** [comment] 2020-02-13 10:31
Hi @elrosi,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
