### ISSUE TITLE
download stable version without sharing email address and agreeing terms

### ISSUE THREAD

**Issue by baptx** [PrestaShop/PrestaShop#23165] opened 2021-02-06 18:02 UTC
The README file says:
"This repository contains the source code of PrestaShop, which is intended for development and preview only. To download the latest stable public version of PrestaShop (currently, version 1.7), please go to the download page on the official PrestaShop site."

However on the download page, we need to share and email address and agree to the "Terms and Conditions of Use" / "Data protection policy".
If PrestaShop is open source, this should not be needed. Can you confirm that the [latest version](https://github.com/PrestaShop/PrestaShop/releases/latest) from GitHub releases is exactly the same stable version as the one from the website? Then this should be clarified in the README file.

**Comment by matks** [comment] 2021-02-06 20:34
> Can you confirm that the [latest version](https://github.com/PrestaShop/PrestaShop/releases/latest) from GitHub releases is exactly the same stable version as the one from the website?

Yes

**Comment by hibatallahAouadni** [comment] 2021-02-08 11:56
Hello @baptx 

DId you try to download the latest PS version from this [page](https://www.prestashop.com/fr/versions-precedentes), see the attached screen record below:

https://drive.google.com/file/d/1qNyhkqxoWRIXcLTMnW6IU0aEFySdj_Lm/view

Cause when I download from this page, I don't need to share my email address or agree Terms and Conditions of Use" / "Data protection policy".

Besides, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 
So, next time when you had a question just ask in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: I close this issue cause it's not a bug or an improvement related to PS Core :wink: 

Thank you

**Closed as completed by hibatallahAouadni** 2021-02-08 11:56 UTC
Labels: No change required

**Comment by matks** [comment] 2021-02-08 13:04
ping @ttoine FYI

**Comment by baptx** [comment] 2021-02-11 10:51
Hello @hibatallahAouadni, indeed, I did not pay attention to the small link "All Versions " / "Toutes les versions" on the download page. I created an issue here because I thought the README file of the GitHub project could be improved.
By the way, the links https://www.prestashop.com/en/previous-versions and https://www.prestashop.com/fr/versions-precedentes could be renamed to `all-versions` and `toutes-les-versions` to be less confusing (since it also includes the current version).

**Comment by hibatallahAouadni** [comment] 2021-02-11 10:53
@baptx yep you're right :slightly_smiling_face: 
@matks FYI

**Comment by matks** [comment] 2021-02-11 13:19
> By the way, the links https://www.prestashop.com/en/previous-versions and https://www.prestashop.com/fr/versions-precedentes could be renamed to `all-versions` and `toutes-les-versions` to be less confusing (since it also includes the current version).

You might not believe it, but I recently asked the team behind prestashop.com to do _exactly that_ 😄  . The work is WIP on their side (there's a lot of work because pages on prestashop.com are translated in 8 languages so they need translaters before pushing to production)
