### ISSUE TITLE
Non-regulatory prestashop Customer Notice module according to the DGCCRF and the prefecture services in France

### ISSUE THREAD

**Issue by Brunettib78** [PrestaShop/PrestaShop#25019] opened 2021-06-18 09:37 UTC
Hello, I am using the free productcomments v4.2.2 module on my prestashop 1.7.6.8 store.
The competition department in France audits all sites in the French well-being sector, 
and mine went through this audit, which ends with an injunction.

 I am stuck on customer reviews, because according to them I am facing penalties because it is not legal. If I understand them correctly, I will remember to remove them from my site because:

I don't have a review management procedure,
I do not respond to a notice and can indicate my possible refusal of publication
there is no date of experience in addition to the date of the notice
Is it possible to change the free customer review module so that it is legal?
I don't have a lot of opinion, and I want to stay in the free module

Do you have any ideas ?

Without changes made, the French prefecture asks me to desactivate this module 
because it does not comply with French law on notices

can youhelp me? 
thank you

#### Is your feature request related to a problem?
Non-regulatory prestashop Customer Notice module according to the DGCCRF and the prefecture services in France
not comply with French law

#### Additional context
url of my shop :
https://www.stagereiki.com/boutique/

Version PrestaShop : 1.7.6.8
Version PHP : 7.2.34
Product comments V 4.2.2

Sorry for my english; it's a google translation

**Comment by florine2623** [comment] 2021-06-18 15:17
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/25014

**Closed as completed by florine2623** 2021-06-18 15:17 UTC
Labels: Duplicate
