### ISSUE TITLE
Abandoned carts permit selling articles even stock is 0

### ISSUE THREAD

**Issue by Aplastaneitor** [PrestaShop/PrestaShop#11523] opened 2018-11-26 21:00 UTC
**Describe the bug**
If you change the quantity of an article to 0 when the article is in the cart, the abandoned cart reflects that change but the customer is able to finish the order even the quantity is 0. 

**To Reproduce**
As a customer:
1. Add a product to the cart.
2. Close session or wait 30 minutes so the cart turns to abandoned status.
As a backoffice user:
1. Change the quantity of the same product to 0 (I do it by importing it in csv).
As a customer again:
1. Log in.
2. Finish the order, you will be able to finish it even the stock is 0.

**Screenshots**
Added an actual abandoned cart from my website.
![captura](https://user-images.githubusercontent.com/11150080/49041332-3da6e800-f1c5-11e8-8d19-6d0ccb6a978f.PNG)

**Additionnal information**
PrestaShop version: From 1.6 to 1.7.4.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-11-27 08:26
Hi @Aplastaneitor,

I did not manage to reproduce the issue after upgrade from 1.6 to 1.7.
I attached a video record.
[Nov 27 2018 9_22 AM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2618925/Nov.27.2018.9_22.AM.webm.zip)
Thanks to check & feedback.

**Comment by Aplastaneitor** [comment] 2018-11-27 11:28
Hi @khouloudbelguith, 

Thanks for taking the time to try it.
You did exactly what i did but it didn't fail to you. I'll try to reproduce and record it but it is strange because you did it perfect and didn't work as I expected. 
I'm very busy this week but i'll try to take a moment to do it and record it.
I had at least two orders (real orders, with real customers I mean) that had this casuistry.
There has to be another step that I maybe skipped.

As I said, thank you very much, i'll keep you posted.

**Comment by khouloudbelguith** [comment] 2018-11-27 13:40
@Aplastaneitor, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2018-12-28 11:37
Hi @Aplastaneitor,

Any news about your issue?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-31 10:42
Hi @Aplastaneitor,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-31 10:42 UTC
Labels: Order, No change required, 1.7.4.3
