### ISSUE TITLE
Prestashop 8.1.3 - Each new import with file.csv deletes the categories assigned to the products

### ISSUE THREAD

**Issue by Delvezio** [PrestaShop/PrestaShop#36183] opened 2024-05-17 08:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,
I have a problem with assigning categories and subcategories.
Every day I manually reload a .csv file that I need to update the stocks of the over 1000 products I have on my site, the upload is set with a table that only updates the prices and stocks, all the other columns (name, category, etc) are ignored. After import, however, the categories and subcategories are reset on all products, leaving only one category, the highest among those assigned, even if it had another one set as default, and removing all subsequent subcategories.

Example:
I assign to product A the generic category 1 (Default category), the subcategory 2 and the sub-subcategory 3,
I assign generic category 1, subcategory 2 and sub-subcategory 3 (Default Category) to product B.
I assign only subcategory 2 and sub-subcategory 3 to product C (default category)

After the next import:
Products A and B remain assigned only in category 1, subcategory 2 and sub-subcategory 3 are removed, even if 3 for product B was set as Default.
Product C remains assigned to subcategory 2, and sub-subcategory 3 (set as default) is removed.

The big problem is that if I only assign the sub-subcategory 3, even if it is a daughter of 2 which in turn is a daughter of 1, the product appears only in 3 and does not appear either in category 1 or in subcategory 2.

In practice, the system does not allow me to assign more than one category to each product, or to essentially have subcategories.

website: sanmicheleparafarmacia.com
Prestashop version: 8.1.3
PHP version:7.3
Steps to reproduce the problem:
1. Import product from file.csv (without modules) from Advanced Parameters -> Import
2. Add manually category and subcategory to product from edit product page in backend
3. Update the products with a new.csv file, again going from Advanced parameters -> Import, using a data matching configuration ignoring almost all the columns except reference, stock and price, therefore also ignoring the categories column.

![Add-category-1](https://github.com/PrestaShop/PrestaShop/assets/20090246/e330d259-f888-4036-aa2f-983e560f8ba7)
![Add-category-2](https://github.com/PrestaShop/PrestaShop/assets/20090246/11754e42-5f9a-40a6-ba2a-785ab51afebd)
![1](https://github.com/PrestaShop/PrestaShop/assets/20090246/de6e8ec3-30ef-4f9c-acbb-71b82cc79eb4)
![2](https://github.com/PrestaShop/PrestaShop/assets/20090246/a54f4425-03e9-466a-9fb6-76cc38976f1e)
![3](https://github.com/PrestaShop/PrestaShop/assets/20090246/077c51db-6c29-4006-a57d-e8e16cff775d)
![4](https://github.com/PrestaShop/PrestaShop/assets/20090246/277978e6-dddb-46df-bd68-027c9c636874)
![5](https://github.com/PrestaShop/PrestaShop/assets/20090246/5fc6bf7c-383a-4f16-85ae-43a5af331282)
![Final-result-after-second-import](https://github.com/PrestaShop/PrestaShop/assets/20090246/271e034e-2acb-4137-8522-eaaf93aacda6)

### Expected behavior

I want the categories and subcategories to remain those assigned manually and not to be deleted each time a new.csv file is imported

### Steps to reproduce

1. Import products from file.csv (without modules) from Advanced Parameters -> Import
2. Add manually category and subcategory to product from edit product page in backend
3. Update the products with a new.csv file, again going from Advanced parameters -> Import, using a data matching configuration ignoring almost all the columns except reference, stock and price, therefore also ignoring the categories column.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

Parafarmacia San Michele s.r.l

**Comment by Delvezio** [comment] 2024-05-17 09:02
I forgot a detail, the categories and subcategory are deleted only for the products that are present in the new.csv file, but if they are not present the assigned categories remain

**Comment by AureRita** [comment] 2024-05-21 08:09
Hi @Delvezio, 

Thank you for your clear report. Unfortunately, when I try to reproduce it, I can't have the same behavior than you as you can see : 

[recording(210).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/69b8b6d8-eb89-46b5-80e7-8c07e5f29e59)

Did I miss something ? 

Waiting for your feedback

**Comment by Delvezio** [comment] 2024-05-21 08:44
Hi, thank you for your reply.
Categories are only removed for products that are imported from the new CSV. For example, on my store I have product A and product B, I customize the categories for both, then when I upload the new CSV that only includes product B, the categories for A remain as I set them, while those for B are deleted.
I couldn't tell from your video whether the product to which you changed the categories in the backend was present in the .csv file you uploaded. Aside from that, it doesn't seem like you missed a step.

I also noticed from the video that you don't use the same version of Prestashop as me, mine is 8.1.3, your it's 8.1.5.
and that you ignore all the columns of the csv file, while I keep: Price, product reference and stock. From your video I don't understand if you also override these parameters.

Waiting for your feedback

**Comment by Delvezio** [comment] 2024-05-21 14:47
I also noticed from the video that you don't use the same version of Prestashop as me, mine is 8.1.3, your it's 8.1.5. 
and that you ignore all the columns of the csv file, while I keep: Price, product reference and stock. From your video I don't understand if you also override these parameters.

**Comment by Delvezio** [comment] 2024-06-14 08:40
Hi @AureRita,
Is there any news about this bug?

**Comment by ShaiMagal** [comment] 2024-08-03 16:28
@Delvezio I think, this is already fixed in latest PS 8.1 version, because of PR #34857

**Comment by Delvezio** [comment] 2024-08-05 11:02
BUONGIORNO,
si, si è risolto con l'ultimo aggiornamento.
grazie, il tiket può essere chiuso.

Alessandro

Il giorno sab 3 ago 2024 alle ore 18:28 Dominik Shaim Ulrich <
***@***.***> ha scritto:

**Comment by ShaiMagal** [comment] 2024-08-06 06:19
@Delvezio OK, closing.

**Closed as completed** 2024-08-06 06:19 UTC
Labels: Bug, BO, Import / Export, 8.1.x, Products Page
