### ISSUE TITLE
Products created by new employee are not visible in BO under SuperAdmin profile

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#20257] opened 2020-07-21 07:03 UTC
#### Describe the bug

I created a new employee profile with basic functionality to add new products. After adding the products, all is working as per normal and products are appearing in FO. However, when I sign in to the superadmin profile, the products are no longer visible in the BO.

#### Steps to Reproduce

1. Create new profile to add new products.
2. Create new employee under new profile
3. Sign in BO using new employee details and add a product. 
4. Sign out from new employee account and sign in with SuperAdmin profile.
5. Products not visible in BO.

My only guess as to why this could be happening is that **the email of the new employee is an alias to the superadmin email**. Could it be for that reason?
#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by SimonGrn** [comment] 2020-07-22 16:18
Hello, thanks for your report.
Could you explain this part, please ?
> My only guess as to why this could be happening is that the email of the new employee is an alias to the superadmin email. Could it be for that reason?

Do you mean the email address of the employee is something like `adminemail+1@test.com` ?

**Comment by nrcjea001** [comment] 2020-07-22 16:34
Hello SimonGrn

An alias is an alternate address to the original address, but still points to the original address. It basically provides another name for the same email. Please refer to the following [link](https://support.google.com/domains/answer/6304345?hl=en) for more details.

**Comment by SimonGrn** [comment] 2020-07-22 16:48
Thank you for your answer. The alias here has nothing to do with PrestaShop, since your shop cann't know that an email is an alias of another email, it doesn't connect to Gmail to know that.

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thank you

**Closed as completed by SimonGrn** 2020-07-22 16:48 UTC
Labels: Can't reproduce, 1.7.6.2

**Comment by nrcjea001** [comment] 2020-07-22 17:00
In my case, I am using the alias as my email to contact. It is also the email I use to respond to customers using Prestashop.  Please refer to image below
![Untitled](https://user-images.githubusercontent.com/26452178/88205744-47187a00-cc5e-11ea-8a0d-6c92279eea62.png)
