### ISSUE TITLE
Transporter picker before payment : the page auto reload as soon as a transporter is clicked

### ISSUE THREAD

**Issue by GuyoST** [PrestaShop/PrestaShop#14017] opened 2019-05-29 14:29 UTC
**Describe the bug**
Add something to the cart and go to the payment page.
Pick a transporter in the list and click Next.
You are now on the Payment section
Now you want to change the transporter : click Delivery Option
As soon as you click a transporter, the page is refreshed automatically to the payment section, which is not good because the user has no time to set the transporter options if there are some options.

You can see a video example here : https://youtu.be/W78d3vlnwgc the second transporter has a button to pick a relay picker, and the user has no time to click on it.

**To Reproduce**
1. Pick a transporter and click continuer after adding some item in your cart.
2. When you're at the payment step, try to change the transporter
3. you will see the page is reloaded before you click the NEXT button

**Screenshots**
Video here : https://youtu.be/W78d3vlnwgc

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.3.5

**Comment by khouloudbelguith** [comment] 2019-05-30 08:12
Hi @GuyoST,

This issue is fixed in the last version PS1.7.6.
PRs to fix the issue: #13440, https://github.com/PrestaShop/PrestaShop/pull/13106
Your ticket is a duplicate of #12456
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-30 08:12
Duplicate of #12456

**Closed as completed by khouloudbelguith** 2019-05-30 08:12 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2019-05-30 08:14
@GuyoST, for your information, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks!
