### ISSUE TITLE
wrong id when updating carriers

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18951] opened 2020-05-03 13:49 UTC
#### Describe the bug

when you update the information of the carriers, the id is not overwritten, it seems that a new one is created

#### Expected behavior

that information on the same carrier should be updated

#### Steps to Reproduce

1. Go to carriers
2. Look at the id and modify the information of one
3. See error

**Screenshots**

https://youtu.be/APPy39QDnSE

#### Additional information

* PrestaShop version: 1.7.6.4 - 1.7.7
* PHP version: 7.2.29

**Comment by ionut-gheorghe** [comment] 2020-05-03 14:31
Same here, trying to modify an existent carrier and it creates a new one as of ps 1.7.6.5. This happend with ps 1.6 also.

![image](https://user-images.githubusercontent.com/54311614/80916804-5b359500-8d5b-11ea-9794-3eab290af199.png)
![image](https://user-images.githubusercontent.com/54311614/80916824-77393680-8d5b-11ea-943e-ec4f1f2cfb68.png)

**Comment by Gipielle** [comment] 2020-05-03 21:24
This bug is still present since prestashop 1.4 ...

**Comment by kpodemski** [comment] 2020-05-03 21:46
It's not a bug, it's proper behavior to prevent updating historical data in orders

**Comment by alfonsolr09** [comment] 2020-05-03 21:52
?????????

**Comment by Progi1984** [comment] 2020-05-04 07:13
Hi @alfonsolr09,

We are aware of this issue but it's a feature.
This issue is a duplicate of #9592.

Thank you!

**Comment by Progi1984** [comment] 2020-05-04 07:14
Duplicate of #9592

**Closed as completed** 2020-05-04 07:14 UTC

**Comment by alfonsolr09** [comment] 2020-05-16 19:59
> Hola @ alfonsolr09 ,
> 
> Somos conscientes de este problema, pero es una característica.
> Este problema es un duplicado de [# 9592](https://github.com/PrestaShop/PrestaShop/issues/9592) .
> 
> ¡Gracias!

why?
