### ISSUE TITLE
do not show all modules

### ISSUE THREAD

**Issue by sitolab** [PrestaShop/PrestaShop#10793] opened 2018-10-01 12:40 UTC
I just installed prestashop version 1.7.4.2 but if I log in modules -> Modules & Services -> Selection

only 1 module "The best brands" is displayed while the others are not displayed, also with inspection I have noticed these errors

catalog? _token = D5MGJZ1nBngJYJj2gKXs2PPBRw7_kPRqYTobxqV1DVM: 1 [DOM] Found 2 elements with non-unique id #addons_login_button: (More info: https://goo.gl/9p2vKq) <button id = "addons_login_button" class = "btn btn- primary btn-block btn-lg "type =" submit "> ... </ button> <button id =" addons_login_button "class =" btn btn-primary btn-block btn-lg "type =" submit "> ... </ button>
catalog? _token = D5MGJZ1nBngJYJj2gKXs2PPBRw7_kPRqYTobxqV1DVM: 1 [DOM] Found 2 elements with non-unique id #addons_login_form: (More info: https://goo.gl/9p2vKq) <form id = "addons_login_form" method = "post"> ... </ form> <form id = "addons_login_form" method = "post"> ... </ form>
catalog? _token = D5MGJZ1nBngJYJj2gKXs2PPBRw7_kPRqYTobxqV1DVM: 1 [DOM] Found 2 elements with non-unique id #password_addons: (More info: https://goo.gl/9p2vKq) <input id = "password_addons" name = "password_addons" type = "Password" value autocomplete = "off" class = "form-control ac_input"> <input id = "password_addons" name = "password_addons" type = "password" value autocomplete = "off" class = "form-control ac_input">
catalog? _token = D5MGJZ1nBngJYJj2gKXs2PPBRw7_kPRqYTobxqV1DVM: 1 [DOM] Found 2 elements with non-unique id #username_addons: (More info: https://goo.gl/9p2vKq) <input id = "username_addons" name = "username_addons" type = "Text" value autocomplete = "off" class = "form-control ac_input"> <input id = "username_addons" name = "username_addons" type = "text" value autocomplete = "off" class = "form-control ac_input">

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by sitolab** [comment] 2018-10-01 12:50
Informazioni sul server
Informazioni sul server Linux #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64

Versione software del server: Apache

Versione di PHP: 7.0.32

Limite di memoria: 256M

Tempo di esecuzione massimo: 299

Dimensione Max. dei file da caricare: 256M

 Database Information
Versione MySQL: 5.6.41

Server MySQL: 127.0.0.1

Prefisso delle tabelle: ps_

Motore MySQL: InnoDB

Driver MySQL: DbPDO

**Comment by khouloudbelguith** [comment] 2018-10-01 13:20
Hi @sitolab,

Thanks for your report.
The issue of the selection modules & the console error log is not the same.
In the selection page, you have just one module is because the PrestaShop API is not responding correctly, and any action on the administration tries to connect to it (api.prestashop.com) => we are aware of this issue & it is in progress to fix it.
The second issue, we manage to reproduce the issue, it is added to our debug roadmap.
Your issue is a duplicate of #10469
So, I close it.
Thanks!

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-10-01 13:20 UTC
