### ISSUE TITLE
[BO] Product listing - Unable to search for a product with an apostrophe (if using the apostrophe)

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#26550] opened 2021-11-08 14:45 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If my product name has an apostrophe, I cannot search for it using the apostrophe in the search. It does not return any results.
Example: "L'arbre".
![08-11-2021 15-45-12](https://user-images.githubusercontent.com/76649472/140762689-dc2b264b-a53c-4da1-9ec9-0f763cf8cebd.png)

I have to search without the apostrophe. In some cases, this is not practical

![08-11-2021 15-45-21](https://user-images.githubusercontent.com/76649472/140762697-13b148a5-f560-47e9-ab26-4b12e675a1f2.png)

### Expected behavior

Be able to search with an apostrophe

### Steps to reproduce

1. Create a product with an apostrophe
2. Search for the product on the BO

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2021-11-09 09:45
Hello @d33x ,

I was able to reproduce the issue with PrestaShop version 1.7.7.7, 1.7.8.x and develop, so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2021-12-01 12:05 UTC
Labels: Bug, Trivial, BO, Fixed, PR available, 1.7.8.x, Verified
