### ISSUE TITLE
Double Search Bar

### ISSUE THREAD

**Issue by delphiv4** [PrestaShop/PrestaShop#26734] opened 2021-11-24 15:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After the Prestashop 1.7.8.1 update, the search bar is doubled on the website
![aroys](https://user-images.githubusercontent.com/94971116/143271051-749134d8-9b61-4c4c-a815-27a7c16ac03e.PNG)

### Expected behavior

It should be a single search bar in a green bar, not another search bar in the pink background

### Steps to reproduce

.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_seach_bar

**Comment by hibatallahAouadni** [comment] 2021-11-25 08:17
Hello @delphiv4 

About the double search bar, I think it's related to your theme. If you switch the default the issue will be gone.
So, you need to contact the theme developer to fix the issue.

About the bad display of search bar, we are aware of this issue and it is already in our debug backlog. 
This issue is a duplicate of #25594. To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-25 08:17
Duplicate of #25594

**Closed as completed by hibatallahAouadni** 2021-11-25 08:17 UTC
Labels: Bug, Duplicate, Invalid

**Comment by delphiv4** [comment] 2021-12-14 13:58
The theme developer doesn't want to help us as the theme was not bought directly through his website.

**Comment by matks** [comment] 2021-12-14 14:11
> The theme developer doesn't want to help us as the theme was not bought directly through his website.

We're sorry but nobody else than the theme developer can fix this. You should contact the merchant who sold you the theme maybe.
