### ISSUE TITLE
User cannot select product variants

### ISSUE THREAD

**Issue by tabularasadev** [PrestaShop/PrestaShop#10850] opened 2018-10-04 09:41 UTC
Hi,

I have a lot of products that have variations, but on one in particular, i have an issue. When a visitor chooses a variant that is not available in stock. The site de-select the declination and return to the default, but I would like the user can still place his order.

I tried with the parameter "Availability Preference" in "Accept Orders" but nothing helps.

I also noticed that the choice of variant works if all the stock are at 0.

I tried to make a new product, disable all modules that do not come prestashop, disabled overrides, updated prestashop, updated modules, tried with the default theme, but still nothing, the problem persists.

Also note that I have no particular error in the javascript console.

You can see problem here : https://normandie-archerie.com/accueil/813-5918-longbow-black-hawk.html#/35-lateralite-gaucher_lh/358-puissance-25_

Is this a core bug ?

Thanks in advance

**Additionnal information**
PrestaShop version: 1.7.2.4
PHP version: 5.6.38

**Comment by khouloudbelguith** [comment] 2018-10-04 10:08
Hi @JimTabularasa,

We are aware of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #9667
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-04 10:08
Duplicate of #9667

**Closed as completed by khouloudbelguith** 2018-10-04 10:08 UTC
Labels: Duplicate
