### ISSUE TITLE
Faceted Search - bad info about stocks

### ISSUE THREAD

**Issue by TaccCZ** [PrestaShop/PrestaShop#19600] opened 2020-06-05 12:47 UTC
#### Describe the bug

Stock information works poorly in the category listing when the faceted search module is turned on.
If faceted search is active, the "stock" of the product is displayed incorrectly in the statement, if the product is in more than one category.

#### Steps to Reproduce

1. Define custom "stock type" if is product not in stock
2. Go to 'producs categories'
3. See error on pictures

**Screenshots**
**Setting stock for product:**
![image](https://user-images.githubusercontent.com/37780517/83879772-7589d680-a73e-11ea-8358-de1b341b2be9.png)

**Bad info about stock if is faceted search activated:**
![image](https://user-images.githubusercontent.com/37780517/83879890-a8cc6580-a73e-11ea-9461-bdc6402ec6ac.png)

**Product detail is OK**
![image](https://user-images.githubusercontent.com/37780517/83879943-bd106280-a73e-11ea-83d2-c7e0882735d3.png)

**If I activate "Show unavailable, out of stock last"**
![image](https://user-images.githubusercontent.com/37780517/83880416-62c3d180-a73f-11ea-95a4-087994e280e4.png)
**Products are ok:**
![image](https://user-images.githubusercontent.com/37780517/83880473-7bcc8280-a73f-11ea-8033-e43e87bba16a.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-06-05 13:03
Hi @TaccCZ ,

Please keep in mind that this is a public space, do not share your admin here. Let's be careful.

Regarding your issue. I don't understand the language used in the video. Could you explain the exact steps to reproduce in English so that I can help you ?
Thanks!

**Comment by TaccCZ** [comment] 2020-06-05 13:17
I updated first post and write additional informations.

**Comment by florine2623** [comment] 2020-06-05 15:15
**In Shop 1 :**
In product page :
![Capture d’écran 2020-06-05 à 17 11 27](https://user-images.githubusercontent.com/16019289/83893157-e4236000-a74f-11ea-910c-39291ba99cf5.png)
On order page :
![Capture d’écran 2020-06-05 à 17 12 29](https://user-images.githubusercontent.com/16019289/83893177-e980aa80-a74f-11ea-916f-0d0a33550189.png)
On order detail : 
![Capture d’écran 2020-06-05 à 17 11 22](https://user-images.githubusercontent.com/16019289/83893184-ed143180-a74f-11ea-8171-1a53fb124ff3.png)
**On shop 2 :** 
On product page :
![Capture d’écran 2020-06-05 à 17 14 49](https://user-images.githubusercontent.com/16019289/83893376-28166500-a750-11ea-94b4-16e10dae5c20.png)
No orders made :
![Capture d’écran 2020-06-05 à 17 15 10](https://user-images.githubusercontent.com/16019289/83893406-2ea4dc80-a750-11ea-8e66-80e0cc8293ff.png)

**Comment by florine2623** [comment] 2020-06-05 15:33
Thanks for the details !

I think the issue is with your theme. I advise you to contact directly the developer of the theme.

In my shop, with theme classic, I have the right message :
When back order is allowed :
![Capture d’écran 2020-06-05 à 17 29 04](https://user-images.githubusercontent.com/16019289/83895098-86444780-a752-11ea-8dd2-1a74150093d6.png)
![Capture d’écran 2020-06-05 à 17 29 15](https://user-images.githubusercontent.com/16019289/83895104-893f3800-a752-11ea-8cda-f67f03832f12.png)

When back order is not allowed :
![Capture d’écran 2020-06-05 à 17 31 05](https://user-images.githubusercontent.com/16019289/83895142-96f4bd80-a752-11ea-9b67-9100328bf232.png)
![Capture d’écran 2020-06-05 à 17 30 54](https://user-images.githubusercontent.com/16019289/83895152-99571780-a752-11ea-9c17-36c2b4623947.png)

**Comment by TaccCZ** [comment] 2020-06-05 16:23
Hi, but problem is not in product detail. Problem is in category (product list)
look here: https://www.strojni-pily.eu/64-kotouce-na-beton-zdivo-dlazbu
![image](https://user-images.githubusercontent.com/37780517/83899770-47fe5680-a759-11ea-8895-ff5214ab7ef8.png)
product detail is OK: https://www.strojni-pily.eu/864-vodici-lista-na-retezy-force3-pro-pilu-agp-cs11.html.
![image](https://user-images.githubusercontent.com/37780517/83899914-83008a00-a759-11ea-94d5-5a0daafe3af6.png)


If I turned off faceted search module, everything is ok.

**Comment by TaccCZ** [comment] 2020-06-05 20:35
I added video for develop web version: 
https://www.loom.com/share/e31447b6e86b4221ad8e540746f0994a

In this category i have active faceted search filters: https://www.strojni-pily.eu/64-kotouce-na-beton-zdivo-dlazbu, and stock info is BAD

But in this category, i have inactive faceted search: https://www.strojni-pily.eu/111-retezy-na-beton-zdivo , and everything is OK.

So I think,  faceted navigation can´t work with stock information at all like a standard product listing or product detail.

**Comment by florine2623** [comment] 2020-06-08 09:08
Thanks for the clarification. But as I said earlier, that issue has something to do with your theme. I advise you to contact directly the developer of the theme.

In classic theme provided by PrestaShop, in the categories, the stock label is not displayed.

I will close this issue since it is not a bug from PrestaShop itself.
Thanks!

**Closed as completed by florine2623** 2020-06-08 09:08 UTC
Labels: No change required
