### ISSUE TITLE
[backoffice] rewriteRule not working on fresh install.

### ISSUE THREAD

**Issue by irvine48** [PrestaShop/PrestaShop#19292] opened 2020-05-24 20:18 UTC
#### Describe the bug

Fresh install 1.7.6.5, rewriteRule not working as aspect, backoffice always need to remove /index.php from url manually to make all work.

#### Expected behavior

Load any page without redirect to access denied page.

#### Steps to Reproduce

1. Fresh install, delete install folder.
2. Login into admin console.
3. Click any link to reproduce.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.3

I manage to solve the problem by un-comment .htaccess line 57 & 58  in admin folder.

```
RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteRule ^index\.php(/(.*)) %{ENV:BASE}/$2 [R:301, L]
```
After this, i still need to remove "Redirect" `R:301` from code above.

> RewriteRule ^index\.php(/(.*)) %{ENV:BASE}/$2 [L]

to avoid getting error 405 for query on page

> common/notifications?_token

Is there a configuration page for admin .htaccess? i modify everything in Traffic & SEO, nothing changed made.

**Comment by matks** [comment] 2020-05-25 13:48
Hi @irvine48 I tried to reproduce your issue but I could not.

See the following video:
https://drive.google.com/file/d/1boD7A7iuSfpzfpWZS0KEwaPoN3Sdazqp/view
- I install fresh 1.7.6.5
- I remove install folder, login into BO
- links work as expected

I am running php7.2 . PS 1.7.6 is not compatible with php7.3 but I dont think this is the root of the issue. Could you check again on your side ? It's strange, a bug like "all links are broken" should easily be spotted. I think something specific on your side (server config ? shop config ? browser config ?) triggers the bug.

Are you using apache2 with standard config ?

**Comment by irvine48** [comment] 2020-05-25 13:57
Hi @matks,

Update 1,

> PHP Version 7.2.31
> $_SERVER['HTTP_MOD_REWRITE'] | On
> $_SERVER['REDIRECT_HTTP_MOD_REWRITE'] | On

Landing page work fine as usual, `BUT`
> google inspector -> network show

> http://www.prestashop.loc/admin621xoxtjh/index.php/common/notifications?_token=gaGT3gEjKarJZQfYv4LxabtaxZU849kU-fI6dYK8Wnw&rand=1590421382523

it return  `Error 403`

if i remove the index.php manually from address bar, landing page loading without any error.

Update 2,
So i guess is something wrong with .htaccess?

**Comment by florine2623** [comment] 2020-06-05 14:46
You can regenerate your .htaccess by going to Traffic & SEO and saving the config (no need to change anything else)

**Comment by florine2623** [comment] 2020-06-25 10:10
Since we had no news from you for, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-25 10:10 UTC
Labels: BO, No change required

**Comment by Rafnexx** [comment] 2022-06-09 20:21
Sorry for commenting in this topic so long after its closing, but it seems that this issue still exists.
I had exact same problem as @irvine48. 
I'm using: 

- Prestashop 1.7.8.6
- PHP 7.4

Uncommenting below lines in admin-dev/.htaccess resolved it.
```
RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteRule ^index\.php(/(.*)) %{ENV:BASE}/$2 [R=301,L]
```
