### ISSUE TITLE
Customer Service email issues

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33663] opened 2023-08-18 23:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am having some issues with the customer service emails in PrestaShop 8.1.1

We do get the messages/emails into PrestaShop (awesome!), but its not working as expected. Please see my step by step explanation in the "Steps to reproduce" below for further explanation.

### Expected behavior

I would expect it to work once the IMAP and SMTP are fully configured. We do get the messages/emails into PrestaShop (awesome!), but its not working as expected. Please see my step by step explanation in the "Steps to reproduce" below.

### Steps to reproduce

1: The customer sends us a message and we reply:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/7f669d61-5804-49a0-b429-39fd4ece4c28)

2: The cutomer gets our reply, sent via email from inside PrestaShop Customer Service (Awesome!! So far, so good!)

**3a: The customer can now choose** to answer the email via email client (by simply hitting "reply" in his email-client). When this happens, we do get the reply inside PrestaShop Customer Service (Yihaa! So far, so good) ... BUT! it is not added to the existing thread, but placed separately in a new thread: 

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/f626b21f-42e5-4b05-9a46-72d4b6a270d7)

Also, the email-reply from the customer looks funny in Prestashop, showing HTML-tags:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/054402f4-bb15-43de-a634-6191c68b24c2)

So, every time the customer responds via email, we will get it in PrestaShop (awesome!), but each answer will create a new thread (bummer!)

**3b: Alternatively,** the customer chooses to not answer via email by hitting "reply" in his email-client, but in stead clicks the link (as instructed in the email):

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/7b7c2589-229e-45c1-a1ba-40448edc9c6d)

When the customer clicks this link in the email, he opens the contact-page on our webshop, which contains the contact-form. But when the contact-page is accesed via the link in the email (with the query-params from that link), the subject-dropdown is not populated:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/ab13fb48-03f2-4313-85e7-85c024895e60)

And if the customer just fills out his answer to our reply and hits send, it will prompt that he forgot to make a choice in the (unpopulated) dropdown:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/62a18908-31dd-454f-8e2c-bdbac15e39e5)

If he then chooses "Kundeservice" (Customer service) from that dropdown and hits send again, it now tells him that there was an error sending the message:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/e6d6132c-c010-4c02-a9be-d30df8e531f6)

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by paulnoelcholot** [comment] 2023-08-23 14:35
Hello @LarsGMortensen 

I tried to reproduce these 2 issues but I can't.

If I reply by the link I have the expected behavior : 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/c1f55e36-82ca-43f5-9567-feda41e2ed1e)

And for the reply by mail, as specified in the email (Please do not respond directly to this message, we will not receive your response. To answer, click on the following link:), I must not respond via this email, but go through the URL link. I can't click on "reply" with my mailbox.

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/63953426-b527-45a7-9d4e-b7f18440cbd1)

Can you give me more information to reproduce the second issue pls?

Thank for your feedback

**Comment by sallemiines** [comment] 2023-09-11 15:34
Hello @LarsGMortensen 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by sallemiines** 2023-09-11 15:34 UTC
Labels: Bug, BO, Customer, Email, Invalid, 8.1.1
