### ISSUE TITLE
order object not create in PaymenModule and generate throw error

### ISSUE THREAD

**Issue by ComonSoft** [PrestaShop/PrestaShop#13882] opened 2019-05-20 17:27 UTC
**Describe the bug**
Create order in BO with specific cart rule. Second order hangs with an error 500. Object $order is not created in PaymentModule in validateOrder() line 457
 if (!$order->addOrderPayment($amount_paid, null, $transaction_id))

**To Reproduce**
1. Connect to BO
2. Create a cart rule with voucher code for a specific customer with 100% discount and free shipping. Ie order amout should be 0.
3. Go to Orders, create a new order, select customer
4. Add products in cart
5. Enter voucher code, order total should be 0
5. Create order
6. Create a new order in BO again from step 2
7. When create order : error 500

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.4.2 to 1.7.5.2
PHP version: 7.1

Seem to be a cache issue on $delivery_option_list = $this->context->cart->getDeliveryOptionList() that is empty

if we call $delivery_option_list = $this->context->cart->getDeliveryOptionList(null,true)
to refresh cache, there is no error. Not sure if this is the right solution.

**Comment by khouloudbelguith** [comment] 2019-05-21 10:23
Hi @ComonSoft,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0BETA1
I attached a video record
https://drive.google.com/file/d/1eC6MVXLsm4C_YRZPfjFEx2Uvy8ynrd8R/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-20 11:13
Hi @ComonSoft,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-20 11:13 UTC
Labels: Bug, BO, Order, No change required, 1.7.4.2, 1.7.5.2
