### ISSUE TITLE
Problem with product on 1.7.5

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#16427] opened 2019-11-15 13:36 UTC
Hello,
I have a product with 1323 combinations when I try to modify it in any way it gives me the error "Could not update settings" how can I proceed?
Thanks for help!

**Comment by khouloudbelguith** [comment] 2019-11-15 13:39
Hi @Webgaict,

I have an issue similar to your problem reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9809
It is added to our bug roadmap.
Thanks to check & feedback.

**Comment by Webgaict** [comment] 2019-11-15 13:43
An imminent solution does not exist? Because as far as I can see the problem dates back to about a year ago.

**Comment by khouloudbelguith** [comment] 2019-11-15 14:05
@Webgaict, sorry, it is not fixe yet.
Your ticket is a duplicate of #9809
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-11-15 14:06
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2019-11-15 14:05 UTC
Labels: Bug, BO, Duplicate, Combinations, 1.7.5.2
