### ISSUE TITLE
PS1.7.6.1 Pagination Ajax problem back history

### ISSUE THREAD

**Issue by Noido** [PrestaShop/PrestaShop#16816] opened 2019-12-15 10:17 UTC
Hi PS got a bug, when category got pagination we can click different page 1 2 3 etc but when we go in page 2 for sample and then click back button of navigator page is not reloaded

See here for sample : 

https://demo-sixtrone.dev-sixtrone.com/8-accessoires-de-maison

Thanks

**Comment by mariem-abid** [comment] 2019-12-16 13:52
Hi @Noido,

I did not manage to reproduce the issue with PS:1.7.6.2.
I attached a video record.
https://drive.google.com/file/d/1k24ap2SaacRjQH3IJYfiSKfMLX6ACMe3/view

Thanks for check and feedback.

**Comment by Noido** [comment] 2019-12-16 15:17
Hi @mariem-abid it s with navigator back button see my picture attached , i put yellow on it

![image](https://user-images.githubusercontent.com/5593403/70918566-896e3e80-201f-11ea-8349-c2cb757335b6.png)

Thanks

**Comment by mariem-abid** [comment] 2019-12-16 16:14
@Noido, I manage to reproduce the issue with PS:1.7.6.1 and PS:1.7.6.2.
I attached a video record.
https://drive.google.com/file/d/1HiBva_GO0O0opOUxHrfbT6wfS1VrHOvK/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-17 08:53
Same issue with PS1.7.5.2
https://drive.google.com/file/d/107gcnZIWhjbpdE4QShEcDOlGAJWyJy5S/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-17 08:55
Hi @Noido,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14821
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-17 08:56
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/14821

**Closed as completed by khouloudbelguith** 2019-12-17 08:55 UTC
Labels: Bug, Minor, FO, Duplicate, Categories, 1.7.5.2, 1.7.6.1, 1.7.6.2
