### ISSUE TITLE
BO - cannot change the type of a product 

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#32675] opened 2023-05-23 16:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when you add the product name you can't  change the type of product .

[iss1produitname810.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/8edb1175-7853-49db-b066-47e26391c631)

### Expected behavior

after adding all the informations , you can change the type of your product 
 PS 8.0.4 : OK  

[iss1produitname804.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/4826c461-8764-4688-9704-e51b1412959c)

### Steps to reproduce

1. Go to Catalog > Products >Add new product (ex : standard  product ) > see you can click to change the type of your product .
2. Add the name of the product > See NOW you can't change the type of your product   .

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment] 2023-05-24 16:43
Hello @djoelleuch 

It seems this behavior is the new expected behavior, see the attached screen record below:

[issue_32675.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/cc8209d7-74ce-4107-9103-6127b18a5142)

As you modify the product you can't change its type.
Ping @PrestaShop/product-team could you please confirm that this behavior is the expected behavior :pray: 

Thanks!

**Comment by RosaBenouamer** [comment] 2023-05-25 13:23
@MatShir for me it seems to be a bug isn't it ?

**Comment by MatShir** [comment] 2023-05-29 09:25
To avoid data loss, we block irreversible actions such as changing products, leaving the page or duplicating if there is data not yet saved. The user must either save or delete them to proceed to the various actions. We could enhance the UI to more explicit. @TristanLDD FYI. In the meantime, I will close the issue. Thanks for the report :)

**Closed as not planned by MatShir** 2023-05-29 09:25 UTC
Labels: Bug, BO, PR available, Invalid, 8.1.x
