### ISSUE TITLE
Prestashop duplicates the customer's address and indicates that there is no carrier

### ISSUE THREAD

**Issue by Demax81** [PrestaShop/PrestaShop#14573] opened 2019-07-10 11:52 UTC
Hello,

I have encountered a Prestahsop problem that I have not been able to solve.

I have installed Prestashop 1.7 on different websites and with different versions of Prestashop 1.7 and the same thing happens in all of them.

When a new customer makes a purchase and writes his address, he impatiently clicks the continue button several times.

This, what it does, is to keep several copies of the address.

Sometimes, when the client continues to the section to select carrier, the id of the address must be lost and shows that there are no carriers for that address.

In this video the client clicks several times on the continue button

https://drive.google.com/file/d/1h6Iu3p7Vvy-4ujVMYSq47AXDeGOHJnhz/view

In this video the client only clicks once on the continue button

https://drive.google.com/file/d/1Q5RRyzdtZS-WOeAZV_jRxU8CjXljQg80/view

Has anyone else happened to this?
Does this problem have a solution?

Thanks!.

**Comment by khouloudbelguith** [comment] 2019-07-10 13:13
Hi @Demax81,


Thanks for your report.
We are aware of this issue, it is added to our debug roadmap.
I added your steps in a new comment: https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-510054925
Your ticket is a duplicate of #9932
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-10 13:13
Duplicate of #9932

**Closed as completed by khouloudbelguith** 2019-07-10 13:13 UTC
Labels: Duplicate
