### ISSUE TITLE
Cart Rules Javascript error when using Cloudflare Rocket Loader™

### ISSUE THREAD

**Issue by bLeveque42** [PrestaShop/PrestaShop#23332] opened 2021-02-19 21:58 UTC
#### Describe the bug

Whenever Cloudflare Rocket Loader™ feature is turned on, PrestaShop produces a blocking JavaScript error on the "Cart rules" creation form in the back-office.

#### Expected behavior

The Cart rules creation/modification form shouldn't produce a JavaScript error.

#### Steps to Reproduce

1. Go to your Cloudflare account (you can get a free account), then to "Speed" and turn on "Rocket Loader™"
2. Go to your PrestaShop admin panel and click on "Catalog / Cart rules"
3. Click on "Add new cart rule"

`Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'only."' is not a valid attribute name.
    at https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1:2328
    at NamedNodeMap.forEach (<anonymous>)
    at https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1:2246
    at NodeList.forEach (<anonymous>)
    at g (https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js:1:2147)`

**Screenshots**

![cloudflare](https://user-images.githubusercontent.com/2835187/108565512-a7859d80-72b9-11eb-8a05-b2cc188979b0.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.27
* Web browser: Chrome 88.0.4324.150 as well as Firefox 85.0.1 - No browser extensions enabled

It looks like this issue was already reported by several users on the PrestaShop forum (e.g. https://www.prestashop.com/forums/topic/1025895-admin-cart-rules-js-unchecked-runtimelasterror/)

**Comment by hibatallahAouadni** [comment] 2021-02-22 11:08
Hello @bLeveque42 ,

Thanks for your issue!
I was able to reproduce the issue with PrestaShop version 1.7.7.1. 
I’ll add this to the debug backlog so that it’s fixed.

PS: thanks to @NeOMakinG & @PierreRambaud 

Thank you.

**Comment by PierreRambaud** [comment] 2021-02-22 14:17
FYI, we found issue on how smarty use `function|modifier`, the modifier is not applied, we are working on it. It will be fixed for the next version :wink:

**Comment by PierreRambaud** [comment] 2021-03-19 08:06
I create a first pull request, but since the HTML structure is broken for years, I'm not sure it will fix everything :(

**Closed as completed** 2021-05-28 13:37 UTC
Labels: Bug, Major, BO, Cart rules, Fixed, Front-end, PR available, 1.7.6.4, 1.7.7.1
