### ISSUE TITLE
Conflicting free shipping discounts causing "no carriers available for your delivery address" at checkout

### ISSUE THREAD

**Issue by OdeYec** [PrestaShop/PrestaShop#21286] opened 2020-10-04 09:45 UTC
Hi there!
This issue might relate to these bug reports that I found (but I don't think they are exactly the same):  #11172, #10903

In Prestashop 1.7.6.7,  when trying to create two "free shipping" discounts, which one has a minimum amount conditions, no shipping method show up in checkout and instead there is "Unfortunately, there are no carriers available for your delivery address."

#### Steps to reproduce:
1. Add cart rule of "Free Shipping":
-- Information:
![image](https://user-images.githubusercontent.com/10381040/95011435-5aba6680-0639-11eb-88a1-89ffa247ba66.png)
-- Conditions:
![image](https://user-images.githubusercontent.com/10381040/95011444-69088280-0639-11eb-8b64-e6434c578b95.png)
-- Actions:
![image](https://user-images.githubusercontent.com/10381040/95011452-71f95400-0639-11eb-8cf6-b2088302011b.png)
2. Add a second cart rule for a specific user:
-- Information:
![image](https://user-images.githubusercontent.com/10381040/95011475-a1a85c00-0639-11eb-9ac8-8539b089ced8.png)
-- Conditions (user is crossed out but is needed, shipping can be excluded or included):
![image](https://user-images.githubusercontent.com/10381040/95011497-c8669280-0639-11eb-9e60-6b7018a7b232.png)
-- Actions (the "apply a discount" does not matter here, it can be set to a lower percent or set to "None"):
![image](https://user-images.githubusercontent.com/10381040/95011527-f21fb980-0639-11eb-9a1d-7fd86f412321.png)
3. Add a products to the cart that are less than cart rule 1 amount (i.e 100 ILS) and add the discount code:
![image](https://user-images.githubusercontent.com/10381040/95011589-64909980-063a-11eb-9fe9-17b1ad39231a.png)
The conditions of cart rule 1 are not met and therefore do no apply, while cart rule 2 is applied and price changes as need be.
4. Advance to address selection and finally to shipping method, where the issue resides:
![image](https://user-images.githubusercontent.com/10381040/95011646-c6510380-063a-11eb-9082-17c9c1a2724d.png)

#### Other tests:
- I tried disabling the "Free Shipping" cart rule (1), which brought back the shipping methods for cart rule 2. Of course this means I cannot offer my customers free shipping on orders over X amount.
- Cart rule 2, while now was just meant for testing, has a use case of offering individual customers free shipping on any amount. The ability to do this is of course impacted if they cannot choose a shipping method.
- Adding an additional user-specific cart rule with free shipping (whether or not has minimum amount condition) does not impact cart rule 2 and shipping methods show properly.
- Adding products that total > 100 ILS (cart rule 1's condition) works normally and **shows shipping methods** even if cart rule 2 is applied (cart rule 1 applies automatically and they stack).
![image](https://user-images.githubusercontent.com/10381040/95011735-93f3d600-063b-11eb-9e98-512652eabd83.png)

#### Additional information:
* PrestaShop version: 1.7.6.7
* PHP version: 7.3

Please let me know what other information I can and should provide to assist with this issue :)

**Comment by khouloudbelguith** [comment] 2020-10-05 09:18
Hi @OdeChan,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.8.
![image](https://user-images.githubusercontent.com/16067358/95061445-e98fb780-06fb-11eb-800c-f3e7dbc7b91b.png)
But it is fixed with the next release 1770.
I tried with PS1770rc1build1 => ok
![image](https://user-images.githubusercontent.com/16067358/95061557-0a580d00-06fc-11eb-972b-e6ef0162d96d.png)
I attached a screen record
https://drive.google.com/file/d/1nw1gc1mgosCEl0GjDU4Y_D2aWrZxXgQ2/view?usp=sharing
I close the issue since it is fixed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-05 09:18 UTC
Labels: Bug, FO, Discounts, Fixed, 1.7.6.8
