### ISSUE TITLE
Expired cart rules are not removed from the cart

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#26600] opened 2021-11-14 23:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Customers are able to complete order with expired cart rule because if the code has been added before the expiration, than also if it expire, prestashop consider it valid.
So for example, if you make a one day flash sale, all the customer that added the voucher code to the cart, will be able to complete the order with the discount also the next day or week.

### Expected behavior

Prestashop should prevent the customer from completing the order if there's an expired cart rule into the cart.

### Steps to reproduce

B.O. >> Create a cart rule
F.O. >> Add something to the cart and add the cart rule
B.O. >> Change the expiration date of the cart rule and set it as expired.
F.O. >> Proceed with the order
You'll see that you're able to complete the order with the expired voucher code.

### PrestaShop version(s) where the bug happened

1.7.7

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2021-11-15 10:11
Hello @darfk3d3 ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19393.
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by florine2623** [comment] 2021-11-15 10:12
Duplicate of #19393

**Closed as completed** 2021-11-15 10:14 UTC
Labels: Bug, Duplicate, Invalid
