### ISSUE TITLE
Can't swich off cache 1.7.4.3

### ISSUE THREAD

**Issue by Solander** [PrestaShop/PrestaShop#13915] opened 2019-05-22 10:47 UTC
**Describe the bug**
I'm trying to switch off caching to be able to run 1-click upgrade.

**To Reproduce**
1. Go to 'Advanced settings -> Performance'
2. Under section "Caching" toggle Yes to No and hit Save.
3. See the success message on top of the screen but the No has been switched to Yes again.

**Screenshots**
![1558521262_1234_22052019_614x522](https://user-images.githubusercontent.com/5007224/58168318-4537dd00-7c8e-11e9-829b-2472f9f34723.png)
![1558521448_1237_22052019_618x238](https://user-images.githubusercontent.com/5007224/58168361-626cab80-7c8e-11e9-9b68-e978d6f0fd13.png)
![1558521239_1233_22052019_745x380](https://user-images.githubusercontent.com/5007224/58168333-4f59db80-7c8e-11e9-877d-6125233494ef.png)
![1558521500_1238_22052019_1777x1191](https://user-images.githubusercontent.com/5007224/58168430-862ff180-7c8e-11e9-9429-be741d386220.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
MySQL version: 10.2.24-MariaDB-log
Server information: FreeBSD FreeBSD 12.0-RELEASE-p3 GENERIC amd64
The Servers version of software: Apache/2.4.39 (FreeBSD) mpm-itk/2.4.7-04 PHP/7.2.17
PHP-version: 7.2.17
Memory limit: 2048M
Max time for execution: 1000
Maximum filesize for upload: 200M

Shared hosting

What I've done is switched hosting company. Don't know if the problem could be there but I don't see how.

**Comment by khouloudbelguith** [comment] 2019-05-22 12:12
Hi @Solander,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rdy4ever** [comment] 2019-05-22 12:35
Hi @Solander 
I think you should check file permissions on the new server. They need to be 0755 for folders and 0644 for files. Prestashop needs to have write permissions for `app/config/parameters.php` in order to switch off the cache, so I would check permissions on that file. Alternatively, you can switch off cache manually by setting `'ps_cache_enable' => 0` in this file. 
But if file permissions are incorrect to begin with, you will encounter other problems as well, so you need to fix it for all files and folders. So you'll need to connect via FTP (using a FTP clinet like Filezilla) and set file permissions _recursively_ (this is important) to 0755/0644.

**Comment by khouloudbelguith** [comment] 2019-05-22 12:48
Hi @Solander,

In my case, I did not manage to reproduce the issue with PS1.7.6.0beta1
I attached a video record
https://drive.google.com/file/d/1t-Ru3CL9jPOHsmjzbgv9q3MbpQ_KL1ro/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-21 08:44
Hi @Solander,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-21 08:44 UTC
Labels: Bug, BO, Performance, No change required, 1.7.4.3
