### ISSUE TITLE
Adding to cart quantity out of stock

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#17250] opened 2020-01-20 14:45 UTC
1. Go to product page
2. Write number which is out of stock like 9999 and FAST click add to cart before button will change to disabled. 
3. See window 'Product successfully added to your shopping cart' which is false. Product wasn't added.

There should be error.

**Additional information**
PrestaShop version: 1.7
![sagw3ahas](https://user-images.githubusercontent.com/9866119/72735312-d94ea100-3b9b-11ea-8b3d-2f8284855d6f.jpg)

**Comment by sarahdib** [comment] 2020-01-21 08:13
Hello @slupostrupek 

In order to try to reproduce the issue can you give us the complete version of PrestaShop ?

Thank you

**Comment by slupostrupek** [comment] 2020-01-21 12:13
All versions from 1.7.0

**Comment by khouloudbelguith** [comment] 2020-01-21 12:57
Hi @slupostrupek,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15623 to fix the issue.
It is fixed in the next version PS1.7.7.0.
Your ticket is a duplicate of #13374
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-21 12:57
Duplicate of #13374

**Closed as completed by khouloudbelguith** 2020-01-21 12:57 UTC
Labels: FO, Duplicate, Shopping carts FO
