### ISSUE TITLE
Free delivery voucher is shown as zero percent in the cart

### ISSUE THREAD

**Issue by LedCloud** [PrestaShop/PrestaShop#15460] opened 2019-09-07 11:29 UTC
Prestashop 1.7.6.1

BO
Create voucher with free delivery. 

FO
Create an order, proccess it. When the voucher is beeing applied you will see in the cart line -0.00% Instead of shipping value.

I created a pull request https://github.com/PrestaShop/PrestaShop/pull/15542

**Comment by khouloudbelguith** [comment] 2019-09-09 08:36
Hi @LedCloud,

We are aware of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9702
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-09 08:36
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9702

**Closed as completed by khouloudbelguith** 2019-09-09 08:36 UTC
Labels: Duplicate
