### ISSUE TITLE
ps_shopping cart mode ajax error out of stock

### ISSUE THREAD

**Issue by lparenty-deleganet** [PrestaShop/PrestaShop#19911] opened 2020-06-23 13:29 UTC
#### Describe the bug

when I add a product more than the stock, I get an empty popin
and no product are added to cart

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. choose a product
2. add a quantity more than stock
3. call to /checkout/cart with an error "the item in your basket is no longer available in this quantity ..." in Network Tab
4. call to ps_shoppingcart which give a partially empty popin and no products adding
![Capture d’écran 2020-06-23 à 15 27 41](https://user-images.githubusercontent.com/46315182/85409524-3349fd00-b566-11ea-967e-298322a72524.png)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: N/A

**Comment by prestascott** [comment] 2020-06-24 14:36
Hi @lparenty-deleganet, thanks for your report! 

I can't reproduce the bug, i have a success message in Network tab:
![image](https://user-images.githubusercontent.com/54888056/85576092-66f55780-b638-11ea-8ee9-da56ce94e5b4.png)

I also have an alert indicating that i can't add more items because of the limited quantity:
![image](https://user-images.githubusercontent.com/54888056/85576359-a15ef480-b638-11ea-9195-224710fd3902.png)

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP version
- PHP error logs
- apache error log
- Javascript console log
- screenshots

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you!

**Comment by prestascott** [comment] 2020-07-15 09:14
Hello @lparenty-deleganet,

Since we had no news from you for more than 20 days, I'll close this ticket not to clutter up the backlog, but note that you can always create a new one if further information pops up.

Thank you!

**Closed as completed** 2020-07-15 09:14 UTC
Labels: No change required, ps_shoppingcart, 1.7.6.1
