### ISSUE TITLE
Inaccessible BO and FO, after upgrading from 1.7.6.9 to 1.7.7.0

### ISSUE THREAD

**Issue by jannathretail** [PrestaShop/PrestaShop#22324] opened 2020-12-10 05:51 UTC
I started upgrading my Prestashop shop from 1.7.6.9 to 1.7.7.0 using the 1 Click Upgrade module,

While processing both files and database has been successfully upgraded but I received a warning while upgrading modules and it was exhausted memory size, I could not able to take a screenshot at that time

then I have reloaded the page to check whether the BO is working or not but I found out that both BO and FO are inaccessible.

Then I have enabled error reports (By changing _PS_MODE_DEV_ from false to true in config/defines.inc.php) and I found 

these kinds of Fatal errors after refreshing the page 

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in 
![prestashop1](https://user-images.githubusercontent.com/49386651/101726974-9ceca200-3ad9-11eb-8265-bb0ca9818174.png)
![prestashop2](https://user-images.githubusercontent.com/49386651/101726978-9e1dcf00-3ad9-11eb-8721-02d6189ec845.png)

/home/lovzmecom/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/ParameterBag.php on line 95

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /home/lovzmecom/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/HeaderBag.php on line 332

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /home/lovzmecom/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Request.php on line 273

I am using chrome, 
PHP version (currently 7.2) but checked for both 7.2 as well 7.3 (recommended one)

I have increased the memory_limit as well as max_execution_time but still could not be able access site

**Comment by hibatallahAouadni** [comment] 2020-12-10 09:53
Hello @jannathretail 

We are aware of this issue. This issue is a duplicate of ##22264. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-10 09:53
Duplicate of #22264

**Closed as completed by hibatallahAouadni** 2020-12-10 09:53 UTC
Labels: Duplicate

**Comment by jannathretail** [comment] 2020-12-10 09:59
it's not at all duplicate, I am getting a different error and the other side it was different

**Comment by hibatallahAouadni** [comment] 2020-12-10 10:45
Hello @jannathretail 

ok! let's ping @matks is this issue duplicate of #22264 ?

**Comment by matks** [comment] 2020-12-10 13:41
@hibatallahAouadni I confirm it's 2 different issues.

@jannathretail it seems that something HUGE is trying to be put in memory and this is too much for your shop to handle.

I suggest disabling installed modules one by one and check BO and FO to see if it is one of your module that is eating all this memory. Else you'll need someone to take a look at your shop.

**Comment by hibatallahAouadni** [comment] 2020-12-10 15:22
Hello @jannathretail 

As @matks mentioned above, your problem is not with PrestaShop Core. And we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by jannathretail** [comment] 2020-12-11 05:27
Thank you @matks  and @hibatallahAouadni, will check by disabling modules one by one

**Comment by TheMax98000** [comment] 2021-06-14 07:23
@hibatallahAouadni Just to let you know that i just upgraded a website from 1.7.6 to 1.7.7 and have exactly the same problem, so how can you say this isn't related to Prestashop core ?

Like, a third party module works perfectly on 1.7.6 and crash the website with an out of memory on 1.7.7 ?

I really like Prestashop, but the support and help is really terrible in my point of view.

**Comment by hibatallahAouadni** [comment] 2021-06-14 09:14
Hello @TheMax98000 

> so how can you say this isn't related to Prestashop core ?

Did you try disabling modules one by one to figure out the culprit?

> Like, a third party module works perfectly on 1.7.6 and crash the website with an out of memory on 1.7.7 ?

It could be, sometimes you need to upgrade your modules before upgrading your shop, so that you won't encounter this kind of issue.

> I really like Prestashop, but the support and help is really terrible in my point of view.

Thank you :slightly_smiling_face:

**Comment by matks** [comment] 2021-06-14 12:11
> I really like Prestashop, but the support and help is really terrible in my point of view.

Hello, this is because you are not in the right location. This repository is not a support channel. If you need support please follow https://devdocs.prestashop.com/1.7/faq/i-need-help/
