### ISSUE TITLE
ps_emailsubscription not rendering html

### ISSUE THREAD

**Issue by baskettcase** [PrestaShop/PrestaShop#16538] opened 2019-11-26 03:00 UTC
**Describe the bug**
On the signup form it renders as this:
Sign up for our newsletter &lt;br&gt;&lt;em&gt;You may unsubscribe at any time.&lt;/em&gt;

instead of this:

Sign up for our newsletter<br><em>You may unsubscribe at any time.</em>

**To Reproduce**
1. Go to the user signup page
2. Look at the subscription checkbox field label

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by baskettcase** [comment] 2019-11-26 03:28
I finally just created an override for the hookAdditionalCustomerFormFields method and changed this:

```
$label = $this->trans(
            'Sign up for our newsletter[1][2]%conditions%[/2]',
            array(
                '[1]' => '<br>',
                '[2]' => '<em>',
                '%conditions%' => Configuration::get('NW_CONDITIONS', $this->context->language->id),
                '[/2]' => '</em>',
            ),
            'Modules.Emailsubscription.Shop'
        );
```

to this:

```
$label = $this->trans(
            'Sign up for our newsletter. %conditions%',
            array(
                '%conditions%' => Configuration::get('NW_CONDITIONS', $this->context->language->id),
            ),
            'Modules.Emailsubscription.Shop'
        );
```

I would rather not override, but at this point I don't see any other way to do this. It doesn't want to actually render the html, it's just rendering the html tags. And in the theme/templates/_partials/form-fields.tpl file we have nofilter for rendering, if I remove that, then it actually shows the html entities code, so basically double encodes htmlentities.

**Comment by khouloudbelguith** [comment] 2019-11-26 07:58
Hi @baskettcase,

Her's the PR: https://github.com/PrestaShop/PrestaShop/pull/16468 to fix the issue.
Your ticket is a duplicate of #15849
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-26 07:58
Duplicate of #15849

**Closed as completed by khouloudbelguith** 2019-11-26 07:58 UTC
Labels: Duplicate, Emailsubscription
