### ISSUE TITLE
The "Options -MultiViews" option does not allow a smooth update

### ISSUE THREAD

**Issue by karelkryda** [PrestaShop/PrestaShop#25535] opened 2021-08-06 13:21 UTC
#### Describe the bug

Leaving "Options -MultiViews"option active in Admin .htaccess file will cause an HTTP error 500 on shared hostings when attempting to upgrade using the "1-Click Upgrade" plugin.
Due to this fact, it is not possible to use the plugin for a seamless update. To perform the update correctly, the update archive must be downloaded and modified and the store updated from it.

#### Expected behavior

The update should run smoothly.

#### Steps to Reproduce

1. Create shared hosting (for example on wedos.com)
2. Try to install / update the eshop
3. Update fails with HTTP code 500 and damages eshop (backup recovery required)

**Screenshots**

\-

#### Additional information

* PrestaShop version: Happens on all versions (current 1.7.7.5)
* PHP version: Happens on all versions (current 7.3)

**Comment by khouloudbelguith** [comment] 2021-08-06 15:04
Hi @karelkryda,

I did not manage to reproduce the issue.
I made an upgrade from PS1772 to PS1775 using the 1-click upgrade v4.12.0.
I attached a screen record
https://drive.google.com/file/d/1B3yaRJzQUL_raRDguJEL2VHJNyb4m_Vr/view?usp=sharing

Thanks to check and feedback.

**Comment by karelkryda** [comment] 2021-08-06 18:40
Hi @khouloudbelguith,

I tried to turn on "Disables the Apache MultiViews feature"
![image](https://user-images.githubusercontent.com/59953812/128556691-8ae862cc-8221-49c1-8e76-733b7b393a4e.png)
and then uncomment "Options -MultiViews"option in Admin .htaccess file and this happens.

![image](https://user-images.githubusercontent.com/59953812/128556616-cf52f9f7-26cc-4c17-abed-e8bd48fe1e43.png)

This means that if this option is uncommented (which is the default), the update will fail.
My store crashed several times during the update just because I forgot that it has to be updated from the modified archive.

Did I forget to set something?

Thank you so much

**Comment by PierreRambaud** [comment] 2021-08-09 16:34
You should check your PHP log to see what failed exactly.

**Comment by karelkryda** [comment] 2021-08-09 16:41
> You should check your PHP log to see what failed exactly.

Well, Options MultiViews is disabled by my hosting. That means, it can't work and must be commented. And I think most of shared hostings has MultiViews disabled, so I think it should be commented by default.

**Comment by PierreRambaud** [comment] 2021-08-09 16:51
This is what `Options -MultiViews` is doing, disabling the Multiviews, you can option do it a lot of time, it will work. If you're talking about `mod_negotiation` there is already a condition surrounded it.

**Comment by hibatallahAouadni** [comment] 2021-08-30 17:02
Hello @karelkryda 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-30 17:02 UTC
Labels: Bug, BO, SEO & URLs, No change required, PR available, 1.7.7.5
