### ISSUE TITLE
Error update version Multistore from PS1.6

### ISSUE THREAD

**Issue by 4ngeluxpunk** [PrestaShop/PrestaShop#23652] opened 2021-03-15 14:18 UTC
#### Describe the bug

Hello good evening, I am having an error when updating a Multistore, I have carried out all the steps to update the main store, it updates me without problems but the virtual store gives me an error: "Trying to get property 'precision' of non-object" the Prestashop version I am using is 1.7.7.1 and PHP 7.2. Greetings.

#### Expected behavior

I would like to know the exact error that generates this error when opening the virtual multistore.

#### Steps to Reproduce

1. When I go to the url of my virtual store.
2. When I click on my store group.
3. Trying to get property 'precision' of non-object

**Screenshots**

![Error](https://user-images.githubusercontent.com/22511504/111167378-0ebc0800-856f-11eb-8e9e-35367d265845.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-03-16 10:26
Hello @4ngeluxpunk 

Thanks for respecting the template :clap: 
What was your PrestaShop version before upgrade? and did you use the **1-click upgrade** module to upgrade? if so, what was this module version?
Please check and feedback.

Thanks!

**Comment by 4ngeluxpunk** [comment] 2021-03-16 23:39
Very kind to answer, compared to the previous version it is 1.6.1.18, and I have not used the 1-click upgrade module but the migration pro module.

It is worth mentioning that in another multi-store I have had no problem updating with the same module.

Greetings.

**Comment by hibatallahAouadni** [comment] 2021-03-17 16:51
Hello @4ngeluxpunk 

> I have not used the 1-click upgrade module but the migration pro module.

You may need to contact the **migration pro module** developer to see the problem.

---
I didn't manage exactly your issue, but I encountred another problem, see my attached screen record below:

https://drive.google.com/file/d/1pFaYGuYZ-zrkwXN2D0DixpV77ilBpq8P/view

https://drive.google.com/file/d/1efq4nO7qyT2FvPzyenrXamxq3t4vTMaK/view

I encountered an error 500, and when I enbabled the debug mode, it display this bug:

![image](https://user-images.githubusercontent.com/23308427/111461703-d4dd3400-871d-11eb-8cbe-867a07dce35c.png)

And it seems be launched cause some modules (ps_banner, ...) are not updated.
When I try to update these modules, some of them won't upgrade, so I uninstall and re-install these modules, then everything works normally. 

@khouloudbelguith & @Robin-Fischer-PS told me that I encountred this issue (modules issue) cause I didn't check this option before upgrade:

![image](https://user-images.githubusercontent.com/23308427/111490768-948cae80-873b-11eb-82b5-33cbb9472ef1.png)

Unfortunally, even when I check this option I still encounter this issue :confounded: 
So, I didn't reproduce your issue but thanks to you I discovered another issue :relaxed: thanks :pray: 

---
When I upgrade my shop from 1.6.1.20 to 1.7.7.2 with multistore enabled, I encounter a lot of issues:
1.  Minor with the FO: cause all you need is to uninstall all old modules and re-installed
2. Major issue: UNABLED to access to **Shop Parameters>General** => redirect to Dashboard
3. Major issue: the **Multistore** menu is not displayed :confounded: 

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by tomablan** [comment] 2021-06-22 12:33
@4ngeluxpunk Hi, do you have any updates on it ? I reproduced the problem on a shop but in a particular situation. 

Thanks !

**Comment by hibatallahAouadni** [comment] 2021-06-22 13:19
Hello @tomablan 

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by gericfo** [comment] 2024-04-22 15:40
Hello,
Version 1.6 is no longer actively supported with the Autoupgrade module ([see this announcement](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.3)).
However, this behaviour has been clearly identified and will be taken into account in our future developments.
I therefore close this ticket.
Thanks!

**Closed as completed** 2024-04-22 15:46 UTC
Labels: Bug, Major, FO, Multistore, Autoupgrade, 1.7.7.1, Verified, Module
