### ISSUE TITLE
Bug on Admin CustomerThreads (Single page)

### ISSUE THREAD

**Issue by sunisasiangto** [PrestaShop/PrestaShop#11415] opened 2018-11-16 08:08 UTC
**Dear Community,**

I'm one of the developer who work with prestashop for long time - since version 1.4-1.7
I just got a small bug and fix it by manually many times, i think now is the time to report this bug.

I got the problem that alphabet letter show looks not correct on Admin CustomerThreads (Single page),
But the CustomerThreads list displayed correctly. Example these danish letter : æ, ø, å, Æ, Ø, Å. It display as ascii code instead of the letter. Mostly my customer is danish person, Then it very important that the messages be able to read. Seems like the convert went wrong somehow. 

**This is the list of file that i normally fix**
1.  For the top section.{admin}\themes\default\template\controllers\customer_threads\helpers\view\message.tpl (line 58)
**Default** : {$message.message|escape:'html':'UTF-8'|nl2br}
**My change** : {$message.message|nl2br} 

2. For the timeline
Controllers/admin/CustomerThreadsController.php (line 764 or notice function "getTimeline")
**Default** : $content .= Tools::safeOutput($message['message']);
**My change** : $content .= preg_replace(
            '/(https?:\/\/[a-z0-9#%&_=\(\)\.\? \+\-@\/]{6,1000})([\s\n<])/Uui',
            '<a href="\1">\1</a>\2',
            html_entity_decode($message['message'],
            ENT_QUOTES, 'UTF-8')
        );

Could be nice if this issue can fix soon, It don't have to be the way i fixed - that is the temporary way.

**Additionnal information**
PrestaShop version: 1.7.3.3
PHP version: 7
Languages : Danish (Usually is main), English

**Best regards,**
Faii

**Comment by khouloudbelguith** [comment] 2018-11-16 08:19
Hi @sunisasiangto,

Could you please check this PR: https://github.com/PrestaShop/PrestaShop/pull/9080, it fixes Punycode problem when the register.
It is fixed in the PS1.7.4.0.
Thanks to check & feedback.

**Comment by matks** [comment] 2018-11-16 13:05
> **Dear Community,**
> 
> I'm one of the developer who work with prestashop for long time - since version 1.4-1.7
> I just got a small bug and fix it by manually many times, i think now is the time to report this bug.

@sunisasiangto Thank you for reporting this bug and how you fix it 😉 it's great to hear you have been using PrestaShop for long. You probably have more useful feedbacks from all those years, feel free to tell us more, either in github or you can come discuss with us on https://gitter.im/PrestaShop/General

**Comment by sunisasiangto** [comment] 2018-11-22 02:06
Thanks - everyone. 
I download the patch file of new version and figured out already. It's work :)

**Comment by khouloudbelguith** [comment] 2018-11-22 08:22
Hi @sunisasiangto,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

**Comment by khouloudbelguith** [comment] 2018-11-22 08:22
Duplicate of #9080

**Closed as completed by khouloudbelguith** 2018-11-22 08:22 UTC
Labels: Duplicate, Customer, International
