### ISSUE TITLE
DB Backup > "Ignore statistics tables" switch works as contrary

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#30514] opened 2022-12-06 18:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you do a database backup you have the opportunity to not backup statistical data choose to "Ignore statistics tables" (switch to YES.

![image](https://user-images.githubusercontent.com/16102074/205989225-7e95a1fd-3d01-4ef7-99c1-da9ff35d4571.png)

if you do that the statistics are exported, while if you choose NO (not ignore the statistics) they are NOT exported.

The label must changed to "Include statistic tables"

### Expected behavior

If i choose to ignore something means i dont' want it :)

### Steps to reproduce

1. Go to Advanced Parameters
2. Database
3. DB Backup tab
4. Choose the option "Ignore statistic Tables" to YES and try to create a backup
5. Change the parameter to NO and do a backup
6. check that it works in the inverse way

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

php7.4/7.3/7.2

**Comment by sallemiines** [comment] 2022-12-07 09:41
Hello  @HartLarsson 

I reproduce your issue with `PS 1787` , `PS 1788` , `PS 800` , you can see the attached screen record 

[Untitled_ Dec 7, 2022 10_31 AM.webm](https://user-images.githubusercontent.com/31663369/206141657-5bf68929-b7a6-45a7-9ff1-18dbb27b000e.webm)

Thank you

**Comment by gennaris** [comment] 2022-12-07 16:35
Duplicate of #28520
@HartLarsson have a check at this PR it will fix the issue => https://github.com/PrestaShop/PrestaShop/pull/28590

**Comment by HartLarsson** [comment] 2022-12-08 22:56
> Duplicate of #28520 @HartLarsson have a check at this PR it will fix the issue => #28590

thank you i will take a look

**Comment by sallemiines** [comment] 2022-12-23 12:27
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28520

**Closed as completed by sallemiines** 2022-12-23 12:27 UTC
Labels: Bug, Minor, BO, Duplicate, Database, DB Backup, Verified, Invalid, 1.7.8.7
