### ISSUE TITLE
With an ecotax subject to a tax, the amount of ecotax is continuously decreased on each product update

### ISSUE THREAD

**Issue by fmipsylone** [PrestaShop/PrestaShop#16777] opened 2019-12-11 16:06 UTC
**Describe the bug**
From the BO, in a shop with an ecotax allowed and setup with a tax to apply on it, the amount of ecotax on a product form is recalculated on each update, subtracted by the amount of the tax applied to the ecotax. This leads to an ecotax amount who decrease on every product update action.

**To Reproduce**
Firstable: From the BO, Enable ecotax and setup a tax to apply on it
1. Go to 'Localization -> Tax'
2. Check on 'use ecotax' field at the bottom page
3. Select a tax to apply on ecotax in the listbox just below to the 'use ecotax' field
4. Save
Next: Always in the BO, set an ecotax amount and save
1. Go to 'Catalog -> Product'
2. Select a product in the list
3. Go to the 'Price' tab
4. Set an ecotax amount in the ecotax field
5. Save the product
6. Refresh the page (F5)
7. The ecotax amount displayed has been recalculated and the ecotax tax has been removed from the value I have entered.
8. Save on more time without changing anything
9. Refresh the page
10. The ecotax amount has been recalculated on more time and the amount is decreased to the ecotax tax amount.

The bug appears too if I click on the 'Preview' button (who save the product).  

**Additional information**
In my case, I fixed this issue and the issue #9855 at the same time with:
1. In `AdminProductsControllerCore` class from file `controllers/admin/AdminProductsController.php`, I removed calls to `_removeTaxFromEcotax()` protected method in `AdminProductsControllerCore.processAdd` and `AdminProductsControllerCore.processUpdate` public methods
2. In  `admin//themes/default/js/bundle/product/form.js`, I disabled the `keyup` listener on `#form_step2_ecotax` field (lines 1702 to 1704)
=> For me recalculate excluded tax price on an ecotax value change make absolutely no sense (see my [comment](https://github.com/PrestaShop/PrestaShop/issues/9855#issuecomment-564435170) on issue #9855 )

**My setup**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-12-12 14:49
Hi @fmipsylone,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10026
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-12-12 14:49 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2019-12-12 14:50
@fmipsylone, Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-12 14:50
Duplicate of #10026
