### ISSUE TITLE
Email Templates Missing

### ISSUE THREAD

**Issue by wop99** [PrestaShop/PrestaShop#28360] opened 2022-04-27 20:43 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am trying to edit and add link to the emails sent out to my customers.  When I click on any of the emails I get this message: "No subject was found for ........"  When I look this up on the forums, it appears to be an on going issue.  I wanted to reinstall a newer version of the email module and see if that helps, but I cannot find one.

### Expected behavior

I hope I can download a newer module with the templates.

### Steps to reproduce

Go to translations and try to edit the Core email

### PrestaShop version(s) where the bug happened

1.7.8.5

### If your bug is related to a module, specify its name and its version

Email Templates Manager

**Comment by hibatallahAouadni** [comment] 2022-04-28 09:44
Hello @wop99 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19081. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-04-28 09:44
Duplicate of #19081

**Closed as completed by hibatallahAouadni** 2022-04-28 09:44 UTC
Labels: Bug, Duplicate, Invalid
