### ISSUE TITLE
prestashop 1.7 customization field doesn't appear in backoffice order

### ISSUE THREAD

**Issue by molsondry** [PrestaShop/PrestaShop#28041] opened 2022-03-25 19:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When putting a customized product into the cart a new entry is put into table ps_customized_data correctly. 
Even id_customization field in  table ps_cart_product is set correctly to that key.
But after finishing the order id_customization field in table ps_order_detail is not set to that value but remains to 0.

### Expected behavior

Display the customization content of the customer.

Idea:
 id_customization field in table ps_order_detail should be set to that value of table ps_cart_product.id_customization

### Steps to reproduce

1. Go to FO > Search the customized product
2. Add customization for this product & save it
3. Increase the quantity to 2
4. Click on Add to cart
5. Go to BO > Orders > Shopping carts page 
6. View the last cart created
7. See error > The customization is not displayed

https://user-images.githubusercontent.com/16067358/162447288-272742af-70bb-4c5a-95c5-76a7bfd84c16.mp4

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

-

**Comment by hibatallahAouadni** [comment] 2022-03-28 09:20
Hello @molsondry 

Could you please provide clear and concise steps to reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by tobiasbrunner** [comment] 2022-04-06 08:42
We've seen the same issue (there are actually three), which can be easily reproduced as follows.

1. Customize a product (e.g. the customizable mug in the demo shop)
2. Change either the quantity, or attributes if the product offers any (issue 1)
3. Put the article(s) into the cart (issue 2)
4. The cart in the front end still shows customization fields (issue 3), while the cart in the backend (or the final order) does not

Issue 1 is caused by the following line, which resets the `id_customization` field to 0 whenever the user changes product properties (quantity/attributes): https://github.com/PrestaShop/PrestaShop/blob/fc5f3418643a3edfa5aa0596c9fe4de7a6ae9430/themes/_core/js/product.js#L231

This was added with #22145 (d0e4350bfed894c5681db17a7b74aa566cb6dbd7) but should probably be conditional on adding the product to the cart and not updating anything else.

Issue 2 is that there is apparently no check that enforces an `id_customization != 0` for products that have mandatory customization fields when they are put into the cart.

Issue 3 is related to the check here (and getting *all* customizations with a specific cart ID afterwards):
https://github.com/PrestaShop/PrestaShop/blob/fc5f3418643a3edfa5aa0596c9fe4de7a6ae9430/classes/Product.php#L6026
Note that if multiple products with customizations are in the cart, but all with incorrect `id_customization = 0`,  they each show multiple "Product customization" links.

**Comment by hibatallahAouadni** [comment] 2022-04-06 10:47
Hello @tobiasbrunner 

I didn't manage to reproduce the issue with PS1785, see the attached screen record and screenshot below:

https://user-images.githubusercontent.com/23308427/161957920-02960b73-41a5-426b-8a19-61356a49f502.mp4

![image](https://user-images.githubusercontent.com/23308427/161957728-adbf130a-af12-4e49-93a1-6849f4bf5185.png)

And to be honest, I didn't understand why you considers these behavior are issues :thinking: 
> 1. Customize a product (e.g. the customizable mug in the demo shop)
> 2. Change either the quantity, or attributes if the product offers any (issue 1)
> 3. Put the article(s) into the cart (issue 2)
> 4. The cart in the front end still shows customization fields (issue 3), while the cart in the backend (or the final order) does not

Could you please provide a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by tobiasbrunner** [comment] 2022-04-06 12:29
The crucial step is **2.**, i.e. changing the quantity or attributes after saving the customization before step **3.**, i.e. pressing the "add to cart" button.

**Comment by hibatallahAouadni** [comment] 2022-04-06 13:44
Hello @tobiasbrunner 

Please provide a screen record and specify what's the expected behavior :pray: 
Waiting for your feedback.

Thanks!

**Comment by tobiasbrunner** [comment] 2022-04-06 14:05
Here you go: 

https://user-images.githubusercontent.com/457648/161991399-8153c2e0-1506-47a4-8d57-9df525c3f3e5.mp4

It shows what I described above, including, in the second part, a detailed view of the hidden input field that gets reset to 0 when the quantity is changed (again, when changing attributes, the same happens). (Just noticed that the quantity is also not shown correctly in the backend, not sure if that's related.)

The expected behavior is to not reset the customization ID when changing the quantity or attributes. And since the text is a mandatory customization for the customizable mug, it should never have been accepted to the cart without customization (i.e. with `id_customization = 0`).

**Comment by khouloudbelguith** [comment] 2022-04-08 13:32
Hi @tobiasbrunner,

Thanks for your feedback.
I manage to reproduce the issue with PS1783 & PS1784 & PS1785.
![image](https://user-images.githubusercontent.com/16067358/162445870-438367d8-7934-4ba8-827a-19f743058220.png)
It is ok with PS1782
![image](https://user-images.githubusercontent.com/16067358/162445973-f9f8c688-0e63-44e4-abdd-b82435b2f6c8.png)

so I can confirm that this behavior is indeed a bug.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by molsondry** [comment] 2022-04-24 18:21
Can anybody in this forum tell, how we proceed with this problem? There is another issue:
You are not able to order/ put into the cart the same product twice or more times with different customization content. Then you get the message that the maximum amount of articles of this kind is reached and no more may be put into the cart

https://user-images.githubusercontent.com/5124936/164990709-8fd8a414-99c8-4e3c-8b93-28dde2ab350a.mp4

.

**Comment by MatShir** [comment] 2022-04-25 11:55
@molsondry it seems to be a different issue. I tried on my side and I can't reproduce the bug. Could you create an new issue with all step (product configuration, stock configuration, step on the front office side...) [here](https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&template=1_bug_report.yml) ? 
Thanks in advance

**Comment by molsondry** [comment] 2022-04-25 14:46
@MatShir : find it here please: https://github.com/PrestaShop/PrestaShop/issues/28323

**Comment by Miloune** [comment] 2022-05-15 09:09
Same problem here, it's pretty confusing for my customers to select attribute fields before customization.
Version: 1.7.8.3

**Comment by atomiix** [comment] 2022-09-05 14:14
It seems that #29228 solve this issue!

**Comment by MatShir** [comment] 2022-09-05 16:31
then should we change the branch of dev ?

**Comment by atomiix** [comment] 2022-09-05 17:51
@MatShir I don't know, as it's already in QA, maybe we should cherry-pick it to 1.7.8.x once merged in dev?

**Comment by matks** [comment] 2022-09-16 14:48
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29635

**Closed as completed by matks** 2022-09-16 14:48 UTC
Labels: Bug, Minor, BO, Order, Shopping carts, Regression, Product customization, Fixed, PR available, Verified, 1.7.8.3
