### ISSUE TITLE
PS 1.7.6 import products *.csv

### ISSUE THREAD

**Issue by Mars228** [PrestaShop/PrestaShop#14974] opened 2019-08-02 15:01 UTC
On Prestashop Multistore, stops importing *.csv product file after validation(!), returns error:

"Errors occurred:
error"

/ Advanced Parameters / Import > (select file) /
Prestashop 1.7.6 | PHP Version 7.2.20

**Comment by khouloudbelguith** [comment] 2019-08-02 15:07
Hi @Mars228,

I did not manage to reproduce the issue with PS1.7.6.0. using the CSV file by default.
I attached a screen record
https://drive.google.com/file/d/1A2fQrLULNBIFe5LzLXLfkONI9tjLXZWl/view
Thanks to check & feedback.

**Comment by Mars228** [comment] 2019-08-02 20:32
Screenshot... there is something with file, but yet have no idea what i'm still looking for...
![Zrzut ekranu z 2019-08-02 22-28-27](https://user-images.githubusercontent.com/582141/62397221-76c60200-b575-11e9-8b67-874c24df9a9d.png)

**Comment by groomershop** [comment] 2019-08-03 15:37
If you have multishop (from screen shot seems yes), select specified shop in header and it will work - we have today morning the same problem.

**Comment by Mars228** [comment] 2019-08-05 07:47
On previous screen shows error but this same file on import in Prestashop 1.7.5.2 shows:
![Zrzut ekranu z 2019-08-05 09-42-15](https://user-images.githubusercontent.com/582141/62447390-902da080-b765-11e9-94b9-d0c35430f27b.png)

As attachment sample of *.csv file which was imported
[gatito_items_er.zip](https://github.com/PrestaShop/PrestaShop/files/3466431/gatito_items_er.zip)

**Comment by groomershop** [comment] 2019-08-05 07:59
On the second screen (PrestaShop 1.5.2) I see that you have not multishop, so this is probably, why it is processed without problem.

**Comment by khouloudbelguith** [comment] 2019-08-05 08:33
Hi @Mars228,

As said by @groomershop, in the first screenshot, `all shops` option is selected
![image](https://user-images.githubusercontent.com/16067358/62450293-f0bbde00-b763-11e9-99cb-b7dee8591d23.png)
But in the second screenshot, Multishop context is not enabled
![image](https://user-images.githubusercontent.com/16067358/62450364-1517ba80-b764-11e9-9e34-1911cdd3a5d7.png)

Thanks to check & feedback.

**Comment by Mars228** [comment] 2019-08-05 09:56
Ok, once again - same *.csv file in PS 1.7.6 and 1.7.5.2, both multistore, both one specific store:
![Zrzut ekranu z 2019-08-05 11-53-22](https://user-images.githubusercontent.com/582141/62456121-0b984d80-b778-11e9-84fc-406ef29c110c.png)
![Zrzut ekranu z 2019-08-05 11-51-06](https://user-images.githubusercontent.com/582141/62456132-118e2e80-b778-11e9-9d47-e9b4bd15f058.png)

**Comment by khouloudbelguith** [comment] 2019-08-05 11:24
@Mars228, I did not manage to reproduce the issue with PS1.7.6.0, Multistore context is enabled, shop1 is selected for the import.
I used your file CSV attached.
[gatito_items_er2.txt](https://github.com/PrestaShop/PrestaShop/files/3467337/gatito_items_er2.txt)

I attached a screen record
https://drive.google.com/file/d/1HwUahbzFs_3fq0AqtXX6bc8qT0OZLRSp/view
Thanks to check & feedback.

**Comment by Mars228** [comment] 2019-08-05 11:54
Is it even possible to debug looks we have same version 1.7.6 - don't know if we have same "revision" differences(?) This is a fresh install of PS without any modules. During import in my case i select polish lang, "Field separator" = , (comma) and "Multiple value separator" = ; (semicolon)
Maybe there is some PHP cofiguration difference? /I'm using PHP Version 7.2.20/ Don't have any notice in "Advanced Parameters / Information"

![Zrzut ekranu z 2019-08-05 13-50-00](https://user-images.githubusercontent.com/582141/62462767-836e7400-b788-11e9-8144-8ee2f9937ee5.png)

**Comment by khouloudbelguith** [comment] 2019-08-05 13:29
@Mars228, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-05 13:38
@Mars228, in my case, it is OK.
https://drive.google.com/file/d/1Xk6aSLWko5eDXjrxpV2_fHBBKHVgPMj-/view
Thanks!

**Comment by Mars228** [comment] 2019-08-06 08:05
Log file contains information from attempted import of *.csv file. Any help is welcome...
[dev.zip](https://github.com/PrestaShop/PrestaShop/files/3471032/dev.zip)

**Comment by khouloudbelguith** [comment] 2019-08-06 09:47
@Mars228, thanks for your feedback.
In your log file, you have this exception
>request.CRITICAL: Uncaught PHP Exception PrestaShopBundle\Exception\NotImplementedException: "Shop context types other than "single shop" are not supported" at /home/portfell/domains/portfello.eu/public_html/src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php line 142 {"exception":"[object] (PrestaShopBundle\\Exception\\NotImplementedException(code: 0): Shop context types other than \"single shop\" are not supported at /home/portfell/domains/portfello.eu/public_html/src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php:142)"} []

It is related to the multishop context, Import is supported only for one shop.
Could you please, try to disable multistore, try to import the file again & feedback.

**Comment by Mars228** [comment] 2019-08-06 10:30
As You suggest I turn OFF multistore, "Clear cache" and try to import, have this:
![Zrzut ekranu z 2019-08-06 12-21-17](https://user-images.githubusercontent.com/582141/62532589-02c17d80-b845-11e9-859a-8c824f55f692.png)
[dev.zip](https://github.com/PrestaShop/PrestaShop/files/3471692/dev.zip)

**Comment by khouloudbelguith** [comment] 2019-08-06 10:58
@Mars228, in the new file provided, there are only PHP `Warnings` & PHP `INFO`.
Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by Mars228** [comment] 2019-08-07 09:08
On previous version of Prestashop (1.7.5.2) this file was imported correctly. On 1.7.6 stops randomly on 525; 127; 116 no idea why. Is it possible that image external links broke something?
file: 
[gatito_items.zip](https://github.com/PrestaShop/PrestaShop/files/3476213/gatito_items.zip)

**Comment by khouloudbelguith** [comment] 2019-08-07 11:04
@Mars228, in my case, I tried to import your file with PS1.7.6.0 & it is OK
https://drive.google.com/file/d/1gk2DsBfVyCS_RQlEXra1fF1uR9aPJ2GU/view

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-06 07:24
Hi @Mars228,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-06 07:24 UTC
Labels: BO, Duplicate, Import / Export, 1.7.6.0

**Comment by ricardoceci** [comment] 2020-10-27 12:13
Hi!, just a heads up on this, if you avoid importing quantities you can import the products in multistore in "all shops".

**Comment by khouloudbelguith** [comment] 2020-10-27 12:45
Hi @ricardoceci,

We are awre of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #21482
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-10-27 12:45
Duplicate of #21482
