### ISSUE TITLE
Tabs in BO after the update do not work 1.7.5.0

### ISSUE THREAD

**Issue by Mreco83** [PrestaShop/PrestaShop#11836] opened 2018-12-19 06:31 UTC
Hello. After updating prestashop from version 1.7.4.4 to 1.7.5.0, the Back Office tab does not work for products, performance, administration invoice and e-mail. In dev mode, the tabs work﻿. In one tab in the Back Office named invoice in dev mode shows the error.
![48429336_2000978323311993_1260919887488876544_o jpg da0be00f36cdad26d45bcf220ec89231](https://user-images.githubusercontent.com/36883457/50202898-fd6bfd00-035f-11e9-85e5-abc4737018fb.jpg)
![48385275_2000978613311964_446260008431124480_o jpg 4071fcb6e8a137038a4aefaf61779d1b](https://user-images.githubusercontent.com/36883457/50202899-fd6bfd00-035f-11e9-9338-b68aa249511d.jpg)
![48378031_2000979233311902_5707436599176855552_o jpg 8fe8708cc6ab143f9f1de8c1818fe79f](https://user-images.githubusercontent.com/36883457/50202900-fd6bfd00-035f-11e9-90e6-8121f7aa64c3.jpg)

**Comment by khouloudbelguith** [comment] 2018-12-19 07:57
Hi @Mreco83,

Thanks for your report.
In my case, I did not manage to reproduce the issue after upgrade from PS1.7.4.4 to PS1.7.5.0 using the 1-click upgrade v4.5.1.
All page all displayed well when Debug mode is disabled or enabled.
But, as I see that your error occurred previously with a previous version.
If you already upgraded, please follow the message of Peter Visser: http://forge.prestashop.com/browse/BOOM-5982?focusedCommentId=171708&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171708 to fix your issue.
Thanks to check & feedback.

**Comment by Mreco83** [comment] 2019-01-11 14:57
Hello. Unfortunately, this solution did not help. The error still appears only in the invoice tab.

**Comment by khouloudbelguith** [comment] 2019-01-11 15:28
@Mreco83, to fix this issue you can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/11909#issuecomment-450416475
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-11 15:29
Duplicate of #11909

**Closed as completed by khouloudbelguith** 2019-01-11 15:29 UTC
Labels: Bug, BO, Duplicate, Autoupgrade, 1.7.5.0
