### ISSUE TITLE
Strange shopping carts, with many quantity of products

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11432] opened 2018-11-19 11:25 UTC
Hi
A my customer has a strange problem with shopping carts
it was present on the past 1.6.x and it is also present on the new 1.7.4.4

almost every day displays trolleys with many products and sometimes even manages to reproduce it by itself. This happens only a few times, I have never been able to reproduce it however as you can see even different customers reproduce the error finding a cart full of products

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/48703474-1d3ec280-ebf4-11e8-9a5e-722a728d95fc.png)
![2](https://user-images.githubusercontent.com/653230/48703476-1dd75900-ebf4-11e8-8488-457454db564b.png)
![3](https://user-images.githubusercontent.com/653230/48703478-1dd75900-ebf4-11e8-85c3-668a52ec8311.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

thanks

**Comment by Maofree** [comment] 2018-11-19 12:47
with other sites that I manage I don't get this problem.
I can give you the access to this site

**Comment by khouloudbelguith** [comment] 2018-11-19 13:14
Hi @maofree,

Your issue is so difficult to reproduce it, in your case it random.
But, when the issue occurs, is there any error in your log file?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by Maofree** [comment] 2018-11-19 13:21
in the log I see many 301 redirect of some bot

VelenPublicWebCrawler (velen.io)
Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)
or google bot

I don't know it is due from them
in some cases those shopping cart are due from some customers also from the shopkeeper

the site is this
http://www.kasa-store.com

**Comment by khouloudbelguith** [comment] 2018-11-19 13:55
@maofree, they are robots, did you generate the robots.txt file?

Generating the robots.txt file: A robots.txt file allows you to block robots and other automated software that browse the Web to find more pages to add to their company's server. You will want to give full access to some robots, like those of Google or Yahoo !, while others will have to find closed doors, such as spam robots, content thieves, e-mail address collectors, etc.

**Comment by Maofree** [comment] 2018-11-19 14:03
yes it is present
if this problem can be reproduced by the owner I think it is due from something else, however it is strange

**Comment by khouloudbelguith** [comment] 2018-11-19 14:32
@maofree, did you use any custom module to secure your shop from such this attack?

**Comment by Maofree** [comment] 2018-11-19 15:08
@khouloudbelguith it is not sure that it is due from this
He does not use any security module
I'll check in the next days

**Comment by khouloudbelguith** [comment] 2018-11-19 15:38
Hi @maofree,
Thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-01-29 16:20
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-29 16:20 UTC
Labels: Bug, BO, Shopping carts, No change required
