### ISSUE TITLE
Duplicates in "Related products", "Pack products" autocomplete feature

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10765] opened 2018-09-29 00:46 UTC
**Describe the bug**
Read below.

**To Reproduce**
1. Go to 'Catalog -> Product -> Edit'
2. Click on 'Add a related product'
3. Type 'mug' just to add a product with for example demo_11 ref, add it
4. Type 'mug' again, it's once again available to add (demo_11 ref)

Same situation on Related products and on the search field to add products to Product Pack. In 1.6 products were correctly filtered using NOT IN in query for selecting these products.

**Additionnal information**
PrestaShop version: 1.7.0.0 to 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-01 10:01
Hi @kpodemski,

Thanks for your report.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9617
I edit the #9617 to add the "Related products" issue.
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 10:02
Duplicate of #9617

**Closed as completed by khouloudbelguith** 2018-10-01 10:01 UTC
Labels: Duplicate
