### ISSUE TITLE
Special carachters in customer name

### ISSUE THREAD

**Issue by squaremedia1** [PrestaShop/PrestaShop#19579] opened 2020-06-04 15:29 UTC
Hi, I have a problem with prestashop 1.7.6.5
My clients are unable to register when an apostrophe or a special carachter is entered in the first or last name.
I checked the validate.php in the classes and seems everithing ok.

public static function isCustomerName($name)
    {
        $validityPattern = Tools::cleanNonUnicodeSupport(
            '/^(?:[^0-9!<>,;?=+()\/\\@#"°*`{}_^$%:¤\[\]|\.。]|[\.。](?:\s|$))*$/u'
        );

        return preg_match($validityPattern, $name);
    }

Can you help me?

**Comment by matks** [comment] 2020-06-04 15:33
> Hi, I have a problem with prestashop 1.7.6.5
> My clients are unable to register when an apostrophe or a special carachter is entered in the first or last name.
> I checked the validate.php in the classes and seems everithing ok.

Can you provide some examples ?
In order to protect your customers privacy, you can provide modified names 😊 so if your customer is David Smith you can tell us Vavid Mhsit is not able to register for example

**Comment by squaremedia1** [comment] 2020-06-04 15:34
Name: Davide 
last name: d'alessandro

**Comment by florine2623** [comment] 2020-06-04 16:27
Hi @squaremedia1 ,

I couldn't reproduce your issue.
Please check my screen record : https://drive.google.com/file/d/1VblTa0rWdHV8-cuUZs3azDMHR03zGi9k/view

What version of PHP are you using ?

**Comment by squaremedia1** [comment] 2020-06-04 16:40
PHP 7.3
I see your video, but for me it is not the same, i got an error

**Comment by matks** [comment] 2020-06-04 20:33
> PHP 7.3
> I see your video, but for me it is not the same, i got an error

Are you sure your shop has not a custom behavior, either introduced by a module you installed, or some custom you or someone else wrote ?

Can you check on a fresh PS 1.7.6.5 install ?

**Comment by PululuK** [comment] 2020-06-04 20:49
> PHP 7.3
> I see your video, but for me it is not the same, i got an error

Hi  @matks @squaremedia1
PS 1.7.6.5 with PHP 7.3 ? 🤔
See https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by squaremedia1** [comment] 2020-06-05 07:09
Tryed to change the php version setting it to 7.1, 7.2 and 7.0. Unfortunately nothing changes

**Comment by florine2623** [comment] 2020-06-05 09:08
Did you try to unable your overrides ?
In your FTP `override` becomes `_override`

**Comment by florine2623** [comment] 2020-06-25 10:09
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed** 2020-06-25 10:09 UTC
Labels: FO, No change required, 1.7.6.5
