### ISSUE TITLE
Some of the users are redirected to main page after clicking on checkout despite IP cookie validation being temporary turned off

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#22732] opened 2021-01-08 08:47 UTC
#### Describe the bug

Some of the users are redirected to main page after clicking on checkout despite IP cookie validation being turned off

#### Expected behavior

User can correctly go with the ordering flow

#### Steps to Reproduce

This is not 100% reproducable.

#### Additional information

* PrestaShop version: 1.7.7.0 (but this existed on 1.7.6.4)
* PHP version: 7.2

Please, give me some feedback on it because these random cases are popping off since like a half a year and currently I am running out of ideas why users are being redirected. Literally any idea no matter how long shot would it be can be appreciated.

I will support this issue later with some web proxy server logs to show the way user navigated through the page, this is the most detailed logs I currently have.

**Comment by florine2623** [comment] 2021-01-08 08:55
Hello @ProteanCode ,

I can't reproduce your issue on PS 1.7.7.0.

Could you include a screen record ?
Do you have any modification of your .htaccess ?
Is there any module that would have overrides ? Try to unable them if that's the case.
Are you using a special module for checkout ?
Is the template compatible with your version of PS ?

Thanks

**Comment by hibatallahAouadni** [comment] 2021-01-28 12:59
Hello @ProteanCode ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-28 12:59 UTC
Labels: Bug, FO, No change required, Checkout, 1.7.7.0, 1.7.6.4
