### ISSUE TITLE
Store selection not displayed

### ISSUE THREAD

**Issue by homer8173** [PrestaShop/PrestaShop#23867] opened 2021-04-01 18:17 UTC
#### Describe the bug

i have a strange bug on many screens of the backoffice. When i have to select a store, no inputs are displayed.
Even without external any modules.
As a mandatory field it breaks all those BO screens.

#### Expected behavior

the list of stores

#### Symphony Doctrine report

PrestaShopBundle\Entity\AdminFilter | No errors.
-- | --
**PrestaShopBundle\Entity\Tab** | **The  association PrestaShopBundle\Entity\Tab#tabLangs refers to the owning  side field PrestaShopBundle\Entity\TabLang#tab which does not exist.**

**Screenshots**
![Presse-papier02](https://user-images.githubusercontent.com/8720867/113336327-8a1b0900-9326-11eb-8586-523148ff0c96.jpg)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-04-02 09:28
Hello @homer8173 ,

I can't reproduce your issue in 1.7.7.0, PHP 7.3 :
![Capture d’écran 2021-04-02 à 11 27 28](https://user-images.githubusercontent.com/16019289/113403096-69929380-93a6-11eb-8abf-b174cbab4e96.png)

Is this a fresh install or an upgrade ?
Could you please provide us more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

Thanks!

**Comment by homer8173** [comment] 2021-04-02 13:50
Hello @florine2623 
unfortunately i can't tell you how to reproduce this, i made an other install and everything is fine.

this shop have been installed from sources and datas imported by a module.

is there s a way to track this issue ? i need to fix this 
What are the class involved into store selection ? ShopChoiceTreeType ?

There are no php error, no js error, just store input fields that are not here.

Thanks !

**Comment by homer8173** [comment] 2021-04-02 13:54
The ul.choice-tree is just empty and i have 3 shops
![image](https://user-images.githubusercontent.com/8720867/113421524-8db49b80-93cb-11eb-8198-48ebd1fe9806.png)

**Comment by florine2623** [comment] 2021-04-23 13:01
Hello @homer8173 ,

Sorry for the delay.

You might find more info here : https://devdocs.prestashop.com/1.7/development/components/form/types-reference/shop-choice-tree/

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

**Closed as completed by florine2623** 2021-04-23 13:01 UTC
Labels: Bug, BO, Can't reproduce, Contact, Multistore, 1.7.7.0
