### ISSUE TITLE
Add category products number in BO list

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#23514] opened 2021-03-04 00:08 UTC
## Is your feature request related to a problem?

It would be interesting to have the number of products in a category. 
For example, this can be an indicator to know whether or not we can delete a category.

## Describe the solution you'd like

Add category products number in BO list.

1 - Go to _**BO > Category > List**_
2 - See the new column **_Products_** (number of products for in category)

### Before 

![Capture d’écran du 2021-03-04 01-00-45](https://user-images.githubusercontent.com/16455155/109889549-dfabb980-7c85-11eb-8f43-e692f78d840a.png)

### After

![Capture d’écran du 2021-03-04 01-03-22](https://user-images.githubusercontent.com/16455155/109889543-dc183280-7c85-11eb-9aec-69627abe8906.png)

**Comment by hibatallahAouadni** [comment] 2021-03-04 00:11
Hello @PululuK 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by marionf** [comment] 2021-03-25 14:41
I am not in favor of integrating this feature on the category page, it's a duplicate of the feature in the monitoring page where it is already possible to see and delete empty categories

![capture d'écran_3004](https://user-images.githubusercontent.com/13449658/112491069-3c2f5f80-8d80-11eb-9a29-5ca238ed1000.png)

**Comment by marionf** [comment] 2021-03-25 14:42
@PululuK 

Did you know about this feature on monitoring page ?

**Comment by hibatallahAouadni** [comment] 2021-04-23 13:24
Hello @PululuK,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: as discussed on Slack you can re-open when you're available :wink: 

Thanks!

**Closed as completed** 2021-06-14 06:47 UTC
Labels: Improvement, BO, Catalog, Categories, Fixed, PR available
