### ISSUE TITLE
[Blockwishlist] Prestashop wishlist module can't be installed on 1.7x

### ISSUE THREAD

**Issue by jasper4ni** [PrestaShop/PrestaShop#25969] opened 2021-09-22 17:53 UTC
### Description
Prestashop wishlist module can't be installed on 1.7x

The module is from https://github.com/PrestaShop/blockwishlist

#### Steps to Reproduce

1. Download the zip file and extract and change the filename to without "-dev" Zip it again
2. Upload module in module manager
3. Error shown as
4. ``Attempted to load class "Install" from namespace "PrestaShop\Module\BlockWishList\Database".
Did you forget a "use" statement for e.g. "PrestaShopBundle\Install\Install" or "PrestaShop\AccountsAuth\Installer\Install"?``

**Screenshots**

![image](https://user-images.githubusercontent.com/68841876/134396453-c8678014-86c3-45ac-8751-a723f18dc609.png)

#### Additional information
I've tried clear var/cache but it's not helping

Please help with this error, I cant find any solution after surfing a day on google, thx!

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.2

**Comment by Rus-Design** [comment] 2021-09-22 20:01
Hi.
Just download this zip and try
https://github.com/PrestaShop/blockwishlist/releases/download/v2.0.1/blockwishlist.zip

**Comment by hibatallahAouadni** [comment] 2021-09-23 10:42
Hello @jasper4ni 

Could you please try the proposed solution by @Rus-Design and feedback.
Thanks @Rus-Design for your quick reply :superhero: 

Thanks!

**Comment by fire2** [comment] 2021-10-09 11:56
The proposed solution to install latest version of module (2.0.1) does not work on Prestashop 1.7.8.0 either. This is what I get:

<img width="665" alt="Screenshot 2021-10-09 at 13 53 43" src="https://user-images.githubusercontent.com/7990315/136656901-3874ea7c-e5ef-40b5-b87c-3233a95de1e9.png">

**Comment by kpodemski** [comment] 2021-10-09 21:22
@fire2 I think this is a completely different problem, tho I couldn't manage to reproduce it on the fresh 1.7.8 installation 🤔 

@jasper4ni it's because you didn't run `composer install` so the autoloading basically doesn't work. You should use a package from the release page.

**Comment by fire2** [comment] 2021-10-09 23:22
> @fire2 I think this is a completely different problem, tho I couldn't manage to reproduce it on the fresh 1.7.8 installation 🤔

Yes, sorry, you are right. There was another bug report already open for it. And it happens only when you had version 1.3.2 of the module (probably from a migrated PS 1.6 site), the upgrade doesn't work. Completely uninstalling the module and installing the new version worked.

**Comment by Matt75** [comment] 2021-10-09 23:40
@fire2 Fixed by https://github.com/PrestaShop/blockwishlist/pull/130

**Comment by fire2** [comment] 2021-10-09 23:42
Yep, would be good to merge it though.

**Comment by jasper4ni** [comment] 2021-10-10 04:33
> Hi. Just download this zip and try https://github.com/PrestaShop/blockwishlist/releases/download/v2.0.1/blockwishlist.zip

this fix my prob, should download the release module instead of just download the repo

**Comment by hibatallahAouadni** [comment] 2021-10-11 13:19
Hello @jasper4ni 

> this fix my prob

Glad to hear :tada: So, closing the issue :wink: 
@kpodemski @Matt75 Thanks guys for your quick replies :superhero: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-10-11 13:19 UTC
Labels: Bug, BO, Modules, No change required, Blockwishlist, 1.7.7.8
