### ISSUE TITLE
Image slider not working properly for all screens

### ISSUE THREAD

**Issue by V41F** [PrestaShop/PrestaShop#18034] opened 2020-03-07 11:15 UTC
Hello,
on my Prestashop 1.7.3 the image slider is not working properly for some smaller screens. Image is show but only a part and the rest of slider is filled with grey color. See attachment. 
![screen](https://user-images.githubusercontent.com/41673053/76142349-37144b00-606d-11ea-9088-51a6fad81607.png)

**Comment by khouloudbelguith** [comment] 2020-03-09 07:59
Hi @wewew85,

Thanks for your report.
It is not about smaller screens.
It is related to the image size.
https://drive.google.com/file/d/1yJY8It710mPfoVYZZbipWy3J_1WTNFNl/view
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9882
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-09 07:59
Duplicate of #9882

**Closed as completed by khouloudbelguith** 2020-03-09 07:59 UTC
Labels: Duplicate, Imageslider
