### ISSUE TITLE
Webservice Error - APi key issue

### ISSUE THREAD

**Issue by mark-ebs** [PrestaShop/PrestaShop#11799] opened 2018-12-18 09:47 UTC
Using clean install of Prestashop 1.7.4.4 installed on an 1&1 service - via 1&1 control Panel

trying to contact an inventory control program (www.selro.com) to prestashop via an API webservice.

upon trying to link - i get the following error
 We couldn't connect with prestashop. Please check the API keys and try again. Following error returned by prestashop
exception while getting prestashop ; nested exception is java.lang.RuntimeException: Failed : HTTP error code : 401

I have talked to selro technical team - who are saying eerything there side is fine
i have talked to 1&1 - they are saying everything is fine - all API access login on server are active and work
the problem lays with the prestashop website

Anyone able to help me solve this??

**Comment by khouloudbelguith** [comment] 2018-12-18 10:01
Hi @mark-ebs,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Also, did you enabled the Webservice from the Advanced Parameters => Webservice page?
did you check the key of your webservice generated?
![image](https://user-images.githubusercontent.com/16067358/50146519-3353a780-02b4-11e9-82b3-d33ff34a42d1.png)

Thanks!

**Comment by matks** [comment] 2018-12-18 10:01
Hello @mark-ebs, the error message `java.lang.RuntimeException: Failed : HTTP error code : 401` clearly indicates that whatever answers to your Inventory Program requests, it is a Java program.

PrestaShop is a php program, it can never return this error message. I guess you Inventory Program is sending requests to the wrong target on your server, but this is related to your server configuration and the programs that are running on it, not PrestaShop.

I think Selro needs some informations to know "where to send" the requests to PrestaShop API webservice. The informations provided must be wrong because instead of targeting PrestaShop they target something else, a Java program.

**Comment by khouloudbelguith** [comment] 2019-01-25 17:18
Hi @mark-ebs,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-25 17:18 UTC
Labels: Bug, Webservice, No change required
