### ISSUE TITLE
1.7.5 Modules under Catalog > Articles > Moduls does not work anymore cause of js Error file: ../admin/themes/new-theme/public/main.bundle.js

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#12203] opened 2019-01-17 21:37 UTC
**Describe the bug**
Under 'Catalog > Articles' in tab 'Modules' I have two modules which I need to use. But after update from PS 1.7.4.4 to 1.7.5 I can not use this modules anymore cause of an js ERROR in file: ../admin/themes/new-theme/public/main.bundle.js  in line 275. 

I now try to use file main.bundle.js from an older PS Version (1.7.4.4) and I can use my modules again. But now I have the problem, that I can not edit any articles. All changes were not saved. So, I please need a solution in file main.bundle.js line 275 to use my modules and can edit all articles. 

**To Reproduce**
1. Go to 'Catalog > Articles'
2. Click on 'tab Modules'
3. Click on 'settings' from modul
4. See js error in ../admin/themes/new-theme/public/main.bundle.js in line 275

**Screenshots**

![image](https://user-images.githubusercontent.com/44971218/51349026-87fd6480-1aa4-11e9-99e8-7078846026e3.png)

![image](https://user-images.githubusercontent.com/44971218/51348657-8e3f1100-1aa3-11e9-95f2-923fee7ded3f.png)

Replace file main.bundle.js from PS 1.7.5 with same file from PS 1.7.4.4 and edit Moduls is no problem:

![image](https://user-images.githubusercontent.com/44971218/51350113-a31da380-1aa7-11e9-989f-de53e9c4de9a.png)

but then edit article do not work any more:

![image](https://user-images.githubusercontent.com/44971218/51350266-0e677580-1aa8-11e9-8f71-019609421678.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.1.13 or 7.2.1

Issue also happens with a new and clean PS 1.7.5 installation.

**Comment by khouloudbelguith** [comment] 2019-01-18 07:32
Hi @didi-2018,

We manage to reproduce the issue.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11923 to fix the issue.
It is fixed in the next release 
Your ticket is a duplicate of #11911
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-18 07:32
Duplicate of #11911

**Closed as completed by khouloudbelguith** 2019-01-18 07:32 UTC
Labels: Duplicate
