### ISSUE TITLE
[FO - Product] Product comment structured data AggregateRating isn't working

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25372] opened 2021-07-18 22:21 UTC
#### Describe the bug

Variables that are used inside `themes/classic/templates/_partials/microdata/product-jsonld.tpl`: `$nbComments`, `$ratings` are not assigned into smarty template.

#### Expected behavior

Product rating data should be available inside structured data. 
As I mention in issue https://github.com/PrestaShop/PrestaShop/issues/25371 the easier way to implement this would be to structured data inside productController. Code may not be perfect but it is my way to implement comments data https://github.com/Oksydan/is_themecore/blob/main/classes/ThemeStructuredJsonData.php#L151-L174 and we could just do the same inside productController.

#### Steps to Reproduce

1. Go to product page and add comment.
2. Make sure that comment is accepted via BO.
3. Go to BO > Design > Position page
4. Click on "Transplant a module"
5. Choose the product comments module and transplant to displayProductAdditionalInfo hook
3. Refresh page and **AggregateRating** data shouldn't be displayed in product structured data even if comments exists. 

![image](https://user-images.githubusercontent.com/16067358/127660593-786e1008-45bb-48d5-a9bb-b8ab043f0c61.png)

#### Additional information

* PrestaShop version: 1.7.8 beta
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-07-19 06:10
Hello @Oksydan 

I think your issue is a duplicate of this one #22962
Please check and feedback.

Thanks!

**Comment by Oksydan** [comment] 2021-07-19 07:57
Hi @hibatallahAouadni 

Issue is not related to issue listed above. 
Since json-ld structured data was implemented in prestashop 1.7.8, issue is related to latest new feature.

**Comment by Hlavtox** [comment] 2021-07-19 12:00
@fdonnet check this out man

**Comment by fdonnet** [comment] 2021-07-19 12:52
@Hlavtox hi, it wasn't in the PR, because ratings come from a specific module. The shop owner who needs this, need to override the template and add it based on the module he is using.

**Comment by fdonnet** [comment] 2021-07-19 12:56
@Hlavtox I didn't take care of this in my PR but if someone find a good solution via smarty var usage it can be great to add that function and fill the google corresponding fields. It is the only 2 warnings you will have in the Google Rich tool (2 warnings about the ratings) => need to be completed by the shop dev based on the module he is using....

**Comment by Hlavtox** [comment] 2021-07-19 13:01
@fdonnet I think we should remove this block it if it's not assigned, WDYT?

Then adapt https://github.com/PrestaShop/productcomments to use it. Can the module add just this rating lines or it has to override the block completely? Can the module even assign this nbComments to header or not?

**Comment by Hlavtox** [comment] 2021-07-19 13:07
1) We can remove the ratings from **product-jsonld.tpl** and output it by productcomments module to **{block name='head_microdata_special'}{/block}** available in **head.tpl**.

2) Or can we put a new block in here, right to **product-jsonld.tpl**?
![block](https://user-images.githubusercontent.com/6097524/126164320-e1ecebf5-22df-4165-9a33-afbfea6aab46.JPG)

3) Just keep it like this and somehow assign **$nbComments** and **$ratings** to smarty?

**Comment by Oksydan** [comment] 2021-07-19 13:29
@Hlavtox 
What about removing it form template completely and implement it inside prestashop core.
Add actionHook with way to modify that data and just keep it as associative array. 
So not only comments module will be able to inject data.

**Comment by fdonnet** [comment] 2021-07-20 06:53
hi @Hlavtox, @Oksydan , 

_3. Just keep it like this and somehow assign $nbComments and $ratings to smarty?_

That was my first idea... it comes from "prestarocket theme" approach and at the time, I was thinking "it is not so bad"...

Maybe, if by convention, the modules assign this smarty vars it can be good.

**Comment by khouloudbelguith** [comment] 2021-07-30 09:49
Hi @fdonnet, @Oksydan,

This issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/22417
The issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/22416

Can you please confirm that? so I can close this ticket.

Thank you!

**Comment by Hlavtox** [comment] 2021-07-30 09:58
@khouloudbelguith No it's something completely different, just read this issue... 😄

**Comment by khouloudbelguith** [comment] 2021-07-30 13:47
@Hlavtox, thanks!

@Oksydan, I manage to reproduce the issue with PS1769, PS1775 & branch 1.7.8.x using the module productcomments v4.2.2
![image](https://user-images.githubusercontent.com/16067358/127660834-feed4849-89d2-46e3-a4a2-ef7979dd869a.png)

But I found a solution to fix the issue:
1. Go to BO > Design > Position page
2. Click on "Transplant a module"
3. Choose the product comments module and transplant to **displayProductAdditionalInfo** hook
![image](https://user-images.githubusercontent.com/16067358/127662074-b1ed1fe9-154b-4133-b00c-7480f8366e39.png)
4. Now check with google rich data test tool: https://search.google.com/test/rich-results
![image](https://user-images.githubusercontent.com/16067358/127662173-5d14be15-2847-41cb-820c-b95a726349c8.png)

Can you please confirm that?

Thank you!

**Comment by Oksydan** [comment] 2021-08-02 21:32
Hi @khouloudbelguith, 
yes it will work properly for prestashop version < 1.7.8. 
In prestashop 1.7.8 structured data has been changed and actually right now productcomments module aggregateRating from product page block is outside of product structured data scope which right now is in json-ld inside page head.

**Comment by hibatallahAouadni** [comment] 2021-08-06 12:57
Hello everyone,

Lets' summarize !
So, we have some issues when we check the FO product page with google rich data test tool:
- #22416 (Fixed)
- #22962
- #25372 (this one)

Is that so? Please check and feedback.
By the way @Oksydan I encounter the same issue with PS178x in product page (only when I submit a comment):

![image](https://user-images.githubusercontent.com/23308427/128513641-6dc19312-cacf-478f-ba73-f3d1b2a9f0db.png)

Please confirm :pray: 
Thanks!

**Comment by Oksydan** [comment] 2021-08-06 13:57
Hi @hibatallahAouadni 
since 1.7.8.0 structured data has been removed form html tags in favor of json-ld.
`itemtype="https://schema.org/Product"` doesn't exits anymore in product page on main container.
`productcomments` microdata implementation was right until 1.7.8.0 version. Aggregate rating can't be implemented this way anymore. (we can keep it as backwards compatibility with `_PS_VERSION_` logic).

In 1.7.8.0 Aggregate rating has been implemented in the way that is not possible to work right now. It requires to fetch data and assign it for example to head.tpl for product page to make sure that data is available.

There still exits other issue with new structured data implementation https://github.com/PrestaShop/PrestaShop/issues/25371 we can make workaround for it but in my opinion it will be better to make that structured data independent from theme.

**Comment by khouloudbelguith** [comment] 2021-08-06 16:03
Hi @Oksydan,

>yes it will work properly for prestashop version < 1.7.8.

Yes, you are right.
I manage to reproduce the issue with 178x branch.
**FO**
![image](https://user-images.githubusercontent.com/16067358/128539003-bd0edbd2-eb67-4414-a1f9-f1750172a717.png)
I used https://search.google.com/test/rich-results
![image](https://user-images.githubusercontent.com/16067358/128539087-87c9b538-f5b3-4020-9965-5afda620ed44.png)

It is ok with PS1769, PS1775 when I transplant the product comments module to displayProductAdditionalInfo hook.

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by Progi1984** [comment] 2021-10-01 07:20
Fixed by @Progi1984 in #25551

**Closed as completed by Progi1984** 2021-10-01 07:20 UTC
Labels: Bug, Minor, FO, SEO & URLs, Regression, Fixed, Productcomments, PR available, 1.7.8.0
