### ISSUE TITLE
Product feature indexation

### ISSUE THREAD

**Issue by reanim8ed** [PrestaShop/PrestaShop#15018] opened 2019-08-07 10:05 UTC
**Describe the bug**
Custom product feature is updarted in the search index only after second saving.

**To Reproduce**
1. Open the product in the backoffice (Catalog > Products)
2. Add feature: http://bit.ly/2KBfO9R and enter a custom value: http://bit.ly/2KymFk9
3. Save product
4. In database open ps_search_word, order by id_word, scroll to the bottom and you can see that the value is not saved: http://bit.ly/2KwUYIz
5. Return to the product edit page and save it second time. Repeat query in database and the value appears this time: http://bit.ly/2KwV8j9 Also only after the second saving the value is added to the ps_search_index too: http://bit.ly/2KA5r6h

The same behaviour if the value is deleted. You remove the feature, save product, the ps_search_index table still includes record with id_word value for this feature. You save the product again and only then the record is removed.

**Additional information**
PrestaShop version: 1.7.6.0 and older
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-08-07 10:57
Hi @reanim8ed,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2.
https://drive.google.com/file/d/162T4Tmw32upwjTv4yd_BI9SZljgCWiby/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by reanim8ed** [comment] 2019-08-08 06:22
getFeatures method is run before the values are saved:
classes/Search.php @ 658:
$product['features'] = Search::getFeatures($db, (int)$product['id_product'], (int)$product['id_lang']);

So thats why first time it doesnt save new value to the index. After that value are recorded to the ps_feature_product and ps_feature_value_lang tables so the second time the saving is run the getFeatures method returns all values correctly.

**Comment by marionf** [comment] 2019-08-08 07:03
Thanks for diving into this @reanim8ed 

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

Thank you!

**Comment by NeOMakinG** [comment] 2020-06-02 08:08
Hey @reanim8ed, regarding comments of @SD1982 and @colinegin, I'm closing the issue related to https://github.com/PrestaShop/PrestaShop/pull/15035 as it looks fixed due to another change, if you manage to reproduce it again, don't hesitate to open the issue again :)

Thanks for your contribution anyway, have a good day !

**Closed as completed by NeOMakinG** 2020-06-02 08:08 UTC
Labels: Bug, Minor, BO, 1.7.5.2, 1.7.6.0, PR available
