### ISSUE TITLE
Cannot generate email templates for theme modern with locale en

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33551] opened 2023-08-05 19:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As I spend more time in Prestashop 8, I am sad to say the more I am regretting to switching to it.

It seems Prestashop 8.1 is unable to generate module emails from the back office.  It produces the following error:

Could not find layout file: C:\websites\prestashop\81\www\modules\test/mails/layouts/modern/admin_notification.html.twig

The file above does exist.  Furthermore the same module works fine in Prestashop 1.7.6 +

### Steps to reproduce

1.  Create a sample module with email layouts in the modules/sample_module/mails/layouts/classic and modules/sample_module/mails/layouts/modern
2.  In the back Office, head over to Design > Email Theme and attempt tpo generate the emails for the above.

At this point Prestashop will claim it can't find the layout file, even though it exists.

As mentioned, the same module works ok in Prestadhop 1.7.6+

### PrestaShop version(s) where the bug happened

8.0.4, 8.1.0

**Comment by AureRita** [comment] 2023-08-08 13:59
Hi @musaffarpatel 

Thank you for your report, I tried to reproduce you issue as you can see : 

[Untitled_ Aug 8, 2023 3_46 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/b3840add-d706-42ab-8067-ffef4e83e734)

But I can't. FIY at the end I try to have the expected behavior (but I didn't create a correct theme) 

DId I miss something ? 
Can you provide us a zip of the sample module ? 

Thank you 

Waiting for your feedback

**Comment by PrestaEdit** [comment] 2023-08-17 14:26
Same issue there with three temptatives ; and also the example-modules that you can use to make this (not) working if needed.

Seems to be good onto v8 alpha/beta, at least.
Not working on the 8.0.4 too.

**Comment by musaffarpatel** [comment] 2023-08-20 18:40
@AureRita If you follow the instructions at : https://devdocs.prestashop-project.org/8/modules/concepts/mail-templates/ it should reproduce the error in 8.1.  The same works in 1.7.8

**Comment by hibatallahAouadni** [comment] 2023-08-29 10:48
Hello @musaffarpatel 

Thanks for your feedback and your patience :pray: 
Could you please provide a sample module with email layouts to help me reproducing the issue and accelerate the process :pray: please :relaxed: 
Waiting for your feedback.

Thanks!

**Comment by sallemiines** [comment] 2023-09-11 15:37
Hello @musaffarpatel 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. 
Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by sallemiines** 2023-09-11 15:37 UTC
Labels: Bug, BO, Design, Email theme, Invalid, 8.1.x
