### ISSUE TITLE
BO - Discount -- Free shipping error if cart amount is 0

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#20396] opened 2020-07-30 12:47 UTC
#### Describe the bug

If in an order some discount are applied and the amount is equal to 0 it is impossible to add a free shipping discount

#### Expected behavior

We should be able to add a free shipping discount even if the amount of the order is equal to 0

#### Steps to Reproduce

PS : It is better to reproduce with real product not the demo one

1. In BO create a basic product wtih the following parameters : 
              - price => 10 € taxes included
              - quantity => 100 available
2. On the FO make a order ( don't select the free shipping option ) with the previously created product
3. In BO go to the detail page of the previously created order 
4. Add 2 discount one 10% discount and one 10 € discount => The amount of the order is equal to the price of delivery
5. Try to add a free shipping discount
6. See error

**Screenshots**

https://drive.google.com/file/d/1lAX6kclvL17sQjver9jdIMbRy4HSTtWk/view?usp=sharing

PS : in 1.7.6.5 version an exception is diplayed
![Screenshot at 14-45-51](https://user-images.githubusercontent.com/40635814/88924381-7be68b80-d273-11ea-9b7b-64186d1b16df.png)

#### Additional information

* PrestaShop version: 1.7.7.x & 1.7.6.5 
* PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-08-03 15:03
Related to https://github.com/PrestaShop/PrestaShop/issues/13809

**Comment by hibatallahAouadni** [comment] 2020-11-24 16:54
Hello @SD1982 

I managed to reproduce the issue with PS1.7.6.5 and develop, see attached screenshot (develop) below:

![image](https://user-images.githubusercontent.com/23308427/100126273-0768d580-2e7e-11eb-84c5-f2283923e073.png)

Thanks!

**Comment by florine2623** [comment] 2024-11-26 15:42
Hello @SD1982 ,

I can't reproduce this issue anymore :

![Image](https://github.com/user-attachments/assets/9dcffea4-d053-4ca9-9af1-922d529a82b6)

So I'm closing the issue

**Closed as completed** 2024-11-26 15:43 UTC
Labels: Bug, Major, BO, Order, Shipping, Discounts, Cart rules, Fixed, 1.7.6.5, Verified
