### ISSUE TITLE
Issues after upgrading 1.6.23->1.7.50

### ISSUE THREAD

**Issue by bettinz** [PrestaShop/PrestaShop#12413] opened 2019-02-02 22:02 UTC
Hello, this is what I've found:
1. If the password start with _ (underscore) the upgrade process on the database step fail (I think because of the _LEGACY_ added at the start of the password).

2. That are some errors after browsing the backend (the fronted is a white page).
I've disabled non-core modules and switched to default theme in upgrade options

```[2019-02-02 22:45:18] request.INFO: Matched route "admin_product_catalog". {"route":"admin_product_catalog","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\ProductController::catalogAction","_legacy_controller":"AdminProducts","limit":"last","offset":0,"orderBy":"last","sortOrder":"last","_route":"admin_product_catalog"},"request_uri":"https://*admin_url*/index.php/sell/catalog/products?_token=C9TOuwnD36CGlfRxugio-iNaOMBCxOlhcpUgs6GhL_Y","method":"GET"} []
[2019-02-02 22:45:18] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-02-02 22:45:18] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@bettinz.com"} []
[2019-02-02 22:45:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, "ProductController", "catalogAction"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist" at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, \"ProductController\", \"catalogAction\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-02-02 22:45:18] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-02-02 22:46:22] request.INFO: Matched route "admin_product_catalog". {"route":"admin_product_catalog","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\ProductController::catalogAction","_legacy_controller":"AdminProducts","limit":"last","offset":0,"orderBy":"last","sortOrder":"last","_route":"admin_product_catalog"},"request_uri":"https://*admin_url*/index.php/sell/catalog/products?_token=C9TOuwnD36CGlfRxugio-iNaOMBCxOlhcpUgs6GhL_Y","method":"GET"} []
[2019-02-02 22:46:22] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-02-02 22:46:22] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@bettinz.com"} []
[2019-02-02 22:46:22] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, "ProductController", "catalogAction"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist" at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, \"ProductController\", \"catalogAction\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-02-02 22:46:22] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-02-02 22:46:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Cannot rename "/home2/*username*/public_html/var/cache/prod/translations/catalogue.it-IT.NXhscRe.php.metarOyLtU" to "/home2/*username*/public_html/var/cache/prod/translations/catalogue.it-IT.NXhscRe.php.meta"." at /home2/*username*/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php line 289 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"/home2/*username*/public_html/var/cache/prod/translations/catalogue.it-IT.NXhscRe.php.metarOyLtU\" to \"/home2/*username*/public_html/var/cache/prod/translations/catalogue.it-IT.NXhscRe.php.meta\". at /home2/*username*/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:289)"} []
[2019-02-02 22:46:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function all() on boolean" at /home2/*username*/public_html/classes/Context.php line 374 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function all() on boolean at /home2/*username*/public_html/classes/Context.php:374)"} []
[2019-02-02 22:47:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function all() on boolean" at /home2/*username*/public_html/classes/Context.php line 374 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function all() on boolean at /home2/*username*/public_html/classes/Context.php:374)"} []
[2019-02-02 22:47:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function all() on boolean" at /home2/*username*/public_html/classes/Context.php line 374 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function all() on boolean at /home2/*username*/public_html/classes/Context.php:374)"} []
[2019-02-02 22:48:08] request.INFO: Matched route "admin_order_invoices". {"route":"admin_order_invoices","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\Sell\\Order\\InvoicesController::indexAction","_legacy_controller":"AdminInvoices","_legacy_link":"AdminInvoices","_route":"admin_order_invoices"},"request_uri":"https://*admin_url*/index.php/sell/orders/invoices/?_token=C9TOuwnD36CGlfRxugio-iNaOMBCxOlhcpUgs6GhL_Y","method":"GET"} []
[2019-02-02 22:48:08] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-02-02 22:48:08] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@bettinz.com"} []
[2019-02-02 22:48:08] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected argument of type "object, array or empty", "string" given" at /home2/*username*/public_html/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 41 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"object, array or empty\", \"string\" given at /home2/*username*/public_html/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:41)"} []
[2019-02-02 22:48:08] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-02-02 22:51:48] request.INFO: Matched route "admin_product_catalog". {"route":"admin_product_catalog","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\ProductController::catalogAction","_legacy_controller":"AdminProducts","limit":"last","offset":0,"orderBy":"last","sortOrder":"last","_route":"admin_product_catalog"},"request_uri":"https://*admin_url*/index.php/sell/catalog/products?_token=C9TOuwnD36CGlfRxugio-iNaOMBCxOlhcpUgs6GhL_Y","method":"GET"} []
[2019-02-02 22:51:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-02-02 22:51:49] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@bettinz.com"} []
[2019-02-02 22:51:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, "ProductController", "catalogAction"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist" at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, \"ProductController\", \"catalogAction\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*username*_site.ps_admin_filter' doesn't exist at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-02-02 22:51:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-02-02 22:52:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function all() on boolean" at /home2/*username*/public_html/classes/Context.php line 374 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function all() on boolean at /home2/*username*/public_html/classes/Context.php:374)"} []
[2019-02-02 22:52:14] request.INFO: Matched route "admin_international_translations_show_settings". {"route":"admin_international_translations_show_settings","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\TranslationsController::showSettingsAction","_legacy_controller":"AdminTranslations","_legacy_link":"AdminTranslations:settings","_route":"admin_international_translations_show_settings"},"request_uri":"https://*admin_url*/index.php/improve/international/translations/settings?_token=C9TOuwnD36CGlfRxugio-iNaOMBCxOlhcpUgs6GhL_Y","method":"GET"} []
[2019-02-02 22:52:14] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-02-02 22:52:14] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@bettinz.com"} []
[2019-02-02 22:52:22] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot declare class AeucCMSRoleEmailEntity, because the name is already in use" at /home2/*username*/public_html/modules/advancedeucompliance/entities/AeucCMSRoleEmailEntity.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Cannot declare class AeucCMSRoleEmailEntity, because the name is already in use at /home2/*username*/public_html/modules/advancedeucompliance/entities/AeucCMSRoleEmailEntity.php:0)"} []
[2019-02-02 22:52:22] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []  
```

3. The upgrade process fail with this error

``` 
[2019-02-02 22:36:59] console.ERROR: Error thrown while running command "prestashop:schema:update-without-foreign". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (using password: YES) at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (using password: YES) at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (using password: YES) at /home2/*username*/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"prestashop:schema:update-without-foreign","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (using password: YES)"} []
[2019-02-02 22:36:59] console.DEBUG: Command "prestashop:schema:update-without-foreign" exited with code "1" {"command":"prestashop:schema:update-without-foreign","code":1} []
```

4. here the error during upgrade: i've ran the sql in phpMyadmin manually after the upgrade

```
[2019-02-02 22:36:58] <div class="upgradeDbOk">[OK] SQL 1.7.5.0 ALTER TABLE `ps_customer_thread`
  CHANGE `email` `email` varchar(255) NOT NULL</div>
[2019-02-02 22:36:58] 
            <div class="upgradeDbError">
            [WARNING] SQL 1.7.5.0
            1060 in ALTER TABLE `ps_stock_available`
  ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`: Duplicate column name 'location'</div>
[2019-02-02 22:36:59] 22:36:59 ERROR     [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (using password: YES)" ["exception" => Doctrine\DBAL\Exception\ConnectionException { …},"command" => "prestashop:schema:update-without-foreign","message" => "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (using password: YES)"]
[2019-02-02 22:36:59] In AbstractMySQLDriver.php line 103:
[2019-02-02 22:36:59]                                                                                
[2019-02-02 22:36:59]   An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for us  
[2019-02-02 22:36:59]   er '*username*'@'localhost' (using password: YES)                         
[2019-02-02 22:36:59]                                                                                
[2019-02-02 22:36:59] In PDOConnection.php line 47:
[2019-02-02 22:36:59]                                                                                
[2019-02-02 22:36:59]   SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (  
[2019-02-02 22:36:59]   using password: YES)                                                         
[2019-02-02 22:36:59]                                                                                
[2019-02-02 22:36:59] In PDOConnection.php line 43:
[2019-02-02 22:36:59]                                                                                
[2019-02-02 22:36:59]   SQLSTATE[HY000] [1045] Access denied for user '*username*'@'localhost' (  
[2019-02-02 22:36:59]   using password: YES)                                                         
[2019-02-02 22:36:59]                                                                                
[2019-02-02 22:36:59] prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] <command>
[2019-02-02 22:36:59] Error during database upgrade. You may need to restore your database.
[2019-02-02 22:36:59] Error upgrading Doctrine schema
```

**Comment by khouloudbelguith** [comment] 2019-02-04 11:00
Hi @bettinz,

I did not manage to reproduce the issue with 1-click upgrade v4.5.1, upgrade id done successfully from PS1.6.1.23 to PS1.7.5.0, I used this password _123456789_ for the employee.
I attached a video record.
https://drive.google.com/file/d/1Nc546Oko7G-DzqzCIvnvVWU9-0Nzqz8j/view
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by bettinz** [comment] 2019-02-04 11:11
Hello, about the password, I mean the mysql user. Can you try with user `test` and password `_test` ?

Today I try again, but the errors after upgrade in the second attempt are about `ps_stock_available` -> `location`  and it's duplicated.
This happen because the 1.7.5.0.sql have this query
```sql
ALTER TABLE `PREFIX_stock_available`
  ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`;
```
at line 13 and line 94.

**Comment by khouloudbelguith** [comment] 2019-02-04 13:18
@bettinz, thanks for these clarifications.
I manage to reproduce the issue with the 1-click upgrade v4.5.1.

During the upgrade, the page of the upgrade is not well displayed
![image](https://user-images.githubusercontent.com/16067358/52210272-d40f1e00-2886-11e9-8f0d-22f201cd7db4.png)
Here's the log.txt
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2828105/log.txt)
I cannot log in to the BO / FO after upgrade => 
![image](https://user-images.githubusercontent.com/16067358/52210357-1df80400-2887-11e9-9c43-40b3993b27ea.png)
I checked the file /app/config/parameters.php, I found that 'database_password' => '_LEGACY_admin', it is chagend from 'database_password' => '_admin', 
I corrected it manually, but I have errors
![image](https://user-images.githubusercontent.com/16067358/52210551-ac6c8580-2887-11e9-8deb-21b3ee1c25f5.png)

Ping @Quetzacoalt91 what do you think?
Thanks!

**Comment by bettinz** [comment] 2019-02-04 13:23
@khouloudbelguith 
Thanks for the reply. This issue (the underscore issue) is unrelated to the sql issue I guess (the last one happen if I use the password without underscore) 🤔

**Comment by khouloudbelguith** [comment] 2019-02-04 13:37
@bettinz, no in my case, it is OK as described in my first screen record. The only issue I have that some legacy pages not available as described in this ticket: https://github.com/PrestaShop/autoupgrade/issues/100
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-06 15:16
Hi @bettinz,

We are aware of this issue it is added to our debug roadmap.
Your ticket is a duplicate of #9564
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-06 15:16
Duplicate of #9564

**Closed as completed by khouloudbelguith** 2019-03-06 15:16 UTC
Labels: Bug, Major, Duplicate, Autoupgrade, 1.7.5.0
