### ISSUE TITLE
Invalid processing of field definition for objects on insert, for multishop fields

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25346] opened 2021-07-14 07:34 UTC
#### Describe the bug

`$obj->add()` returns false when $obj is an instance of a descendant of `ObjectModel`, if its table definition contains a field with `'shop' => true`

#### Expected behavior

The basic method `add()` should work on multishop enabled `ObjectModel`s, i.e. an object mapped to two database tables `objectname` and `objectname_shop`

#### Steps to Reproduce

This is not an observable behavior in UI, it is a bug in low level API. To reproduce it create an object definition similar to 

    public static $definition = [
        'table' => 'mytable',
        'primary' => 'id_mytable',
        'multishop' => true,
        'fields' => [
             (...)
            'shopfield' => ['type' => self::TYPE_BOOL, 'shop' => true, 'validate' => 'isBool', 'required' => true],
        ]
    ];

`ObjectModel::add()` will generate an insert query like `insert into PREFIX_mytable (..., shopfield) values ...`. Shop fields should not be inserted into PREFIX_mytable, but PREFIX_mytable_shop

#### Additional information

The exact line responsible for the bug is https://github.com/PrestaShop/PrestaShop/blob/62206a604f2557d5e067d6b8d81f68528e254d47/classes/ObjectModel.php#L409, because of 

```
$data['shop'] = true;
$data['shop'] != 'both'; // => false !!!
$data['shop'] !== 'both'; // => true, this would be correct, and $obj->add() would work
```

* PrestaShop version: any after commit https://github.com/PrestaShop/PrestaShop/commit/07c3ee5dd1ddc1b091fc0700249d5d5def6ca7cd by @jocel1 
* PHP version: N/A

Discussed on slack with @eternoendless

**Comment by jocel1** [comment] 2021-07-14 09:39
Good catch!

**Comment by lmeyer1** [comment] 2021-07-14 10:58
@jocel1
Can you tell what *for retro compatibility* means at https://github.com/PrestaShop/PrestaShop/blob/62206a604f2557d5e067d6b8d81f68528e254d47/classes/ObjectModel.php#L296?

`Shop::isTableAssociated($this->def['table'])` must be true, because in `add()` (https://github.com/PrestaShop/PrestaShop/blob/62206a604f2557d5e067d6b8d81f68528e254d47/classes/ObjectModel.php#L586) it must be true to save the shop associations. 

The correct bugfix as far as I can tell is
- change the comparison operator 
-  remove those *retro compatibility* lines in `getFields()`

What do you think about this? How would you fix that bug?

**Comment by jocel1** [comment] 2021-07-14 11:09
Well I guess it was for really old PrestaShop version without shop table, it doesn't really makes sense nowaday

**Comment by hibatallahAouadni** [comment] 2021-07-14 11:10
Hello @lmeyer1 

Thanks for your technical detailed bug report :clap: 
But I need a simple module to reproduce the issue, so could you please provide a module :pray: 

Thanks in advance!

**Comment by hibatallahAouadni** [comment] 2021-08-04 10:07
Hello @lmeyer1 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-04 10:07 UTC
Labels: Bug, 1.7.x, CO, Multistore, No change required, Back-end

**Comment by lmeyer1** [comment] 2021-08-04 12:01
@hibatallahAouadni
The reason why I didn't give news is because fixing https://github.com/PrestaShop/PrestaShop/blob/62206a604f2557d5e067d6b8d81f68528e254d47/classes/ObjectModel.php#L409 alone does not fix the wrong behavior. There are at least three related bugs, and I didn't have time either to investigate further or to create a module that pops the bug to the surface.
