### ISSUE TITLE
Rounding problem in cart page (1.7.8.X - 8.X)

### ISSUE THREAD

**Issue by fos016** [PrestaShop/PrestaShop#35028] opened 2024-01-11 14:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

<img width="1216" alt="Screenshot 2024-01-11 at 15 19 53" src="https://github.com/PrestaShop/PrestaShop/assets/10567881/04544a1f-fbc7-4a5d-ae5c-fcaec340211d">

### Steps to reproduce

1) Configure two products with:

- 18.56
- 28.03

TAX 21

2) Create a cart with these productos

3) Check the price is incorrect

### PrestaShop version(s) where the bug happened

1.7.8.X 1.8.x

**Comment by florine2623** [comment] 2024-01-11 14:37
Hello @fos016 ,

Your issue seems to be the same as : https://github.com/PrestaShop/PrestaShop/issues/28621

Could you confirm ?

**Comment by fos016** [comment] 2024-01-11 14:53
> #28621

No, round mode and type are different in this case

Round mode: Round up away from zero, when it is half way there
Round type: Round on each line
<img width="909" alt="Screenshot 2024-01-11 at 15 52 43" src="https://github.com/PrestaShop/PrestaShop/assets/10567881/ef9d5448-0905-424a-bdaa-5f81d866e820">

**Comment by florine2623** [comment] 2024-01-11 15:58
I have found the same issue as yours (same config, same tax) here : https://github.com/PrestaShop/PrestaShop/issues/32097
Could you confirm ?

**Comment by Hlavtox** [comment] 2024-01-12 13:16
Yep, the correct total is 56,38.

**Comment by fos016** [comment] 2024-01-13 09:33
> I have found the same issue as yours (same config, same tax) here : #32097 Could you confirm ?

Yes it's the same

**Comment by paulnoelcholot** [comment] 2024-01-15 12:11
Duplicate of #32097

**Closed as completed by paulnoelcholot** 2024-01-15 12:11 UTC
Labels: Bug, FO, Duplicate, Taxes and Prices, Checkout, 1.7.8.x
