### ISSUE TITLE
Cart check quantity when stock disabled

### ISSUE THREAD

**Issue by vladikk007** [PrestaShop/PrestaShop#27505] opened 2022-01-28 09:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error occured while adding product to cart (after clicking "add to cart" button and no entry for given product in ps_stock_available table.

### Expected behavior

Product should be added to cart without error...

### Steps to reproduce

- Disable Stock management
- remove entries from ps_stock_available table
- add to cart product 

### PrestaShop version(s) where the bug happened

1.7.8.0-1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by khouloudbelguith** [comment] 2022-01-28 15:03
Hi @vladikk007,

Thanks for your report.
I manage to reproduce the issue with PS1783 and PS1780 using PHP7.4.
![image](https://user-images.githubusercontent.com/16067358/151569522-e95df0ff-0e55-43bd-bdf2-e92e7dbe5c6b.png)

I tried with 
PS1780 + php7.2 => ok
PS1778 + php7.2 => ok
PS1782 + php 7.3 => ok

PS1778 is compatible with php7.3 & not php7.4

I’ll add this to the debug roadmap so that it’s fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by vladikk007** [comment] 2022-01-28 15:09
Hello,

Thanks. I've created a fix and I will try to create pull request.

Thanks
Vladimir


Dňa pi, 28. jan 2022, 16:03 khouloudbelguith ***@***.***>
napísal(a):

**Comment by Progi1984** [comment] 2022-02-09 08:32
Fixed in #27586 by @vladikk007 and tested by @khouloudbelguith

**Closed as completed by Progi1984** 2022-02-09 08:32 UTC
Labels: Bug, Minor, FO, Stocks, Product settings, Regression, Fixed, ps_shoppingcart, PR available, php, 1.7.8.0, Verified
