### ISSUE TITLE
Order with zero cost can not be completed

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#16143] opened 2019-10-27 18:06 UTC
**Describe the bug**
We had a shipping problem so the client had to create a new order and we gave him a voucher for the entire amount (since he had already paid). So, the total to pay was 0€.

Prestashop correctly said no payment is needed for this order but the Pay button is inactive.

**To Reproduce**
- Put a product in the cart.
- Create a voucher for the same amount and free shipping.
- Try to complete the order. Pay button is not active.

**Screenshots**
![Uploading Screenshot 2019-10-27 at 17.15.54.png…]()

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by sarahdib** [comment] 2019-10-28 07:52
Hello @johanlantz 

Thank you for your bug report.

I didn't reproduce : https://drive.google.com/file/d/1Hh4_XRskitlIBoK0F29z9YeRO70ZY4oJ/view 
For 1.7.6.0 and 1.7.6.1
The button was active.

Can you give us more information or a screen record.

Thank you

**Comment by khouloudbelguith** [comment] 2019-11-26 07:36
Hi @johanlantz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-26 07:36 UTC
Labels: Bug, FO, Cart rules, No change required, Checkout, 1.7.6.0

**Comment by jungwirbtgut** [comment] 2020-08-27 07:00
I got same issue and don't know how to handle or fix.

Someone an idea? Still exsists in 1.7.6.7

**Comment by khouloudbelguith** [comment] 2020-08-28 09:58
Hi @jungwirbtgut,

This issue is currently closed, can you open a new one with more information about your configuration.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
