### ISSUE TITLE
Short description is not shown until your edit the source code

### ISSUE THREAD

**Issue by CArlvJ1N0N8** [PrestaShop/PrestaShop#10243] opened 2018-09-03 01:44 UTC
**Describe the bug**
In the product section when selecting a product, in the Essental tab the short description or the long description are not shown as long as you don't click on the button to view the source code. 

**To Reproduce**
1. Go to Product, select a random product, Go to edit the product. Do you seen the description (short or long? If not then, 
2. Click on Source code.
3. Click on OK 
4. Now you are back in the product description and you can see the description. 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.27-0+deb9u1

**Comment by khouloudbelguith** [comment] 2018-09-03 08:09
Hi @CArlvJ1N0N8,

Could you please provide me the language and the country selected for the installation of your shop?

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment] 2018-09-03 13:23
Sure! 
The settings are Canada English... 

Let me know if you need credentials to my BO if you can't reproduce.

**Comment by khouloudbelguith** [comment] 2018-09-03 14:23
Hi @CArlvJ1N0N8,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment] 2018-09-04 01:46
Hello, 

I have requested the required information to our developer. 
I will send it to you as soon as i receive it. 

Thanks, 

Carl

**Comment by khouloudbelguith** [comment] 2018-09-04 08:30
Hi @CArlvJ1N0N8,

Thanks!
Waiting for your feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-03 13:35
@CArlvJ1N0N8 any news?

**Comment by CArlvJ1N0N8** [comment] 2018-10-16 17:19
Sorry for the delay here is the requested information 


server setup and configuration:  Debian9 Ngixn + php-fpm Php7
PHP error logs : 
nothing
nginx  error log : 
2018/10/11 06:36:34 [error] 19383#19383: *30460 open() "/home/live/web/easy-pharma.ca/public_html/cdn-cgi/scripts/d07b1474/cloudflare-static/email-decode.min.js" failed (2: No such file or directory), client: 142.44.160.129, server: www.easy-pharma.ca, request: "GET /cdn-cgi/scripts/d07b1474/cloudflare-static/email-decode.min.js HTTP/1.1", host: "www.easy-pharma.ca", referrer: "https://www.easy-pharma.ca/fr/module/wtblog/post?id_wt_blog_post=3&amp;;;;amp;;;;;;;;;amp;category_parent=1-are-you-subject-to"

**Comment by khouloudbelguith** [comment] 2018-10-17 09:38
Hi @CArlvJ1N0N8,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-16 16:44
Hi @CArlvJ1N0N8,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-16 16:44 UTC
Labels: BO, No change required, 1.7.4.2
