### ISSUE TITLE
var/cache/prod/AppParameters.php with 000 premissions

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13111] opened 2019-03-29 15:27 UTC
When pressing the "Clear Cache" button, You get a 500 error, upon investigation, var/cache/prod/AppParameters.php has 000 permission, I need to change permission manually, then reload the page to fix the issie. Everytime.

**Comment by khouloudbelguith** [comment] 2019-03-29 15:41
Hi @Legendarior,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ghost** [comment] 2019-04-02 09:50
linux x86_64, MariaDB 10.2.23, Apache 2.4.38, PHP 7.2.16, Perl 5.16.3, kernel ver: 3.10.0-962.3.2.lve1.5.24.8.el7.x86_64
Error_log: PHP Fatal error:  require_once(): Failed opening required '/home/mmcom3h6/public_html/var/cache/prod/appParameters.php' (include_path='/home/mmcom3h6/public_html/vendor/pear/pear_exception:/home/mmcom3h6/public_html/vendor/pear/console_getopt:/home/mmcom3h6/public_html/vendor/pear/pear-core-minimal/src:/home/mmcom3h6/public_html/vendor/pear/archive_tar:.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/mmcom3h6/public_html/config/bootstrap.php on line 86
Prestashop 1.7.5.1

**Comment by khouloudbelguith** [comment] 2019-04-02 14:57
Hi @Legendarior,

Could you please try to clear cache manually: go to your Prestashop installation directory and delete the content of the following folders: cache/smarty/compile, cache/smarty/cache.

**Comment by khouloudbelguith** [comment] 2019-05-02 07:34
Hi @Legendarior,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-02 07:34 UTC
Labels: Performance, No change required

**Comment by ambrooo** [comment] 2019-05-31 19:46
I have exact same issue. Do you have a fix for it

**Comment by khouloudbelguith** [comment] 2019-06-03 08:39
Hi @ambrooo,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by ambrooo** [comment] 2019-06-03 08:43
The issue was solved to me by https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-476361695
