### ISSUE TITLE
input type "number" is not styled properly

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#36164] opened 2024-05-15 09:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you use input type "text" everything is nice, but if you use input type "number", it's not styled properly. So, we should edit CSS for type "number" as well, it must be same like input type "text"
Check screenshot:
![type_number](https://github.com/PrestaShop/PrestaShop/assets/8518736/1800d67f-d625-495e-8410-445dd085e94c)

### Expected behavior

Same styling for input type "text" and type "number".
Module developers can use input type "number", so we should make it nice like "text".

### Steps to reproduce

Use <input type="number"> and compare with <input type="text"> in html in BO for example and you will see results like on my screenshot.

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

openservis.cz

**Comment by florine2623** [comment] 2024-05-15 13:06
Hello @ShaiMagal ,

I checked on the Customer page, but is looks ok to me.

https://github.com/PrestaShop/PrestaShop/assets/16019289/cd9a3d1d-f31f-4280-8003-fd21951bb07c

Is there a specific page where you have this problem ?

Thanks!

**Comment by Hlavtox** [comment] 2024-05-15 14:57
@ShaiMagal Legacy or Symfony?

**Comment by ShaiMagal** [comment] 2024-05-15 19:14
@florine2623 @Hlavtox 
I am talking about usage type="number" in module of 3rd party developers. Not PrestaShop itself
Florine tested Customer page, but there is type="text", not type="number"

**Comment by Hlavtox** [comment] 2024-05-15 20:01
@ShaiMagal As per internal discussion, issue is caused by missing `class="form-control"`, as required by boostrap. :-)

**Comment by ShaiMagal** [comment] 2024-05-15 20:06
Nope, there is missing CSS rule in theme.css for
**.bootstrap input[type=number]**
Check screenshot.

I don't know, how are CSS rules generated, so I am not able to add this line to CSS :)
![Untitled](https://github.com/PrestaShop/PrestaShop/assets/8518736/8e896940-3ae0-4aba-984d-b031bc71166a)

**Comment by Hlavtox** [comment] 2024-05-15 20:07
@ShaiMagal Yes, but this is a hackjob done by someone in ancient history. Boostrap 3 requires having `form-control` class.

**Comment by ShaiMagal** [comment] 2024-05-15 20:08
@Hlavtox So, why this exists in theme.css? Why we don't remove it, if this is not used? :)

I prefer add this line to CSS file... -> **unification**

**Comment by Hlavtox** [comment] 2024-05-15 20:13
@ShaiMagal For the same reason as all the other crap in the core. Somebody sometime somewhere decided to add it there, and it was there so long that removing it would be a BC break. :-)

**Comment by Hlavtox** [comment] 2024-05-15 20:15
Proper Boostrap 3 forms (https://getbootstrap.com/docs/3.3/css/#forms) look like `<input type="text" class="form-control" placeholder="Text input">`, that will work every time on all versions.

**Comment by ShaiMagal** [comment] 2024-05-15 20:40
After consulatition with @Hlavtox  -> PR here #36172

**Comment by kpodemski** [comment] 2024-05-17 08:55
To ease QA validation, you could provide them with a simple module to reproduce this problem @ShaiMagal

**Comment by florine2623** [comment] 2024-06-14 09:08
friendly reminder for getting a simple module for testing purposes @ShaiMagal :D

**Comment by ShaiMagal** [comment] 2024-06-19 10:12
@kpodemski @florine2623 
Here:
But I already posted in PR #36172 (yes, now :-D)

[shaim_number_test.zip](https://github.com/user-attachments/files/15899120/shaim_number_test.zip)

**Comment by florine2623** [comment] 2024-08-09 13:16
Closing this because the PR has been merged. Thanks all.

**Closed as completed by florine2623** 2024-08-09 13:16 UTC
Labels: Improvement, BO, PR available, 8.1.x
