### ISSUE TITLE
[BO] PPV2 Enable, disable default product status is not applied automatically

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#33671] opened 2023-08-21 12:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When enabling the option **Activate new products by default** in shop parameters > Product Settings , and try to create a new product the status is alwyas OFFLINE . (it should be online by default )

### Expected behavior

The default product status should be Online. The product can only be save online if the product name is fulfilled. 

### Steps to reproduce

1. Go to 'Shop parameters > Product Settings' page
2. Enable Activate new products by default > save 
3. Go to product page and create a product 
=>> The product status is OFFLINE 

https://github.com/PrestaShop/PrestaShop/assets/31663369/7054a388-1977-48cb-b971-b90c6e70f426

### PrestaShop version(s) where the bug happened

PS 8.1.x

### PHP version(s) where the bug happened

php 810

**Comment by MatShir** [comment] 2023-08-22 08:45
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/31784

**Closed as completed** 2023-09-06 07:54 UTC
Labels: Bug, Minor, BO, Product settings, Ready, Detected by TE, Verified, 8.1.x, Products Page
