### ISSUE TITLE
BO - Products page - cannot change the default category 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24130] opened 2021-04-20 14:46 UTC
#### Describe the bug

In the BO > Catalog > Product details page, we cannot change the default category, we have an error in the console when we select any category

#### Steps to Reproduce

1. Go to BO > Catalog > Products page
2. Edit/Add a product
3. Try to change the default category
4. See error in the console 
![image](https://user-images.githubusercontent.com/16067358/115415976-a4def000-a1f7-11eb-8078-f0fabd17537e.png)
5. Save => Setting updated
6. Refresh the page => the default category not updated

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by matks** [comment] 2021-04-24 14:00
When this bug is fixed, let's check if https://github.com/PrestaShop/PrestaShop/issues/9811 is fixed

**Comment by arouiadib** [comment] 2021-04-25 20:03
Hi guys,

**The problem:**
If you go to javascript console in browser and type `window.defaultCategory` you got `undefined`. But if you only type `defaultCategory` it prints the appropriate object.

When  you replace `window.defaultCategory` by `defaultCategory`, the problem is resolved but ESLint throws an error: `defaultCategory is  not declared`. To fix this, I made 2 trials since I am not sure which is the best one and I really hope I get javascript guys feedback if there is other better solution.

1. The first PR uses module export/import. ( i.e exporting `dedaultCategory` from default theme to new theme): https://github.com/PrestaShop/PrestaShop/pull/24173

2. The second  PR uses `no-undef` rule in ESLing configuration. It eliminates any `undeclared object ` warnings in the whole theme: https://github.com/PrestaShop/PrestaShop/pull/24200

Thank you very much

**Comment by NeOMakinG** [comment] 2021-04-26 08:35
Hey @arouiadib, what about adding defaultCategory into window inside default theme ? This is a best practice and should fix it

**Comment by arouiadib** [comment] 2021-04-26 22:20
> Hey @arouiadib, what about adding defaultCategory into window inside default theme ? This is a best practice and should fix it

Great idea as discussed in closed PR. Thanks a lot for sharing expertise with us @NeOMakinG 

Could you please see the new  [PR](#24220)  in favor of your approach.

Thanks again, a lot.

**Comment by NeOMakinG** [comment] 2021-04-27 09:45
Np @arouiadib, thanks for the contribution, I need to create a reminder for me in order to check every others objects, it's an error when I added ESLint on the default theme

**Comment by arouiadib** [comment] 2021-04-28 22:23
@NeOMakinG It is always better to add ESLint. Thanks a lot for this.

+1 for setting the reminder instead of doing `no-undef:0`.

**Comment by Progi1984** [comment] 2021-04-30 06:53
Fixed by @PierreRambaud in #24247

**Closed as completed by Progi1984** 2021-04-30 06:53 UTC
Labels: Bug, Major, BO, Categories, Regression, Fixed, Front-end, PR available, 1.7.8.x
