### ISSUE TITLE
Wrong total value of cart

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#18513] opened 2020-04-08 05:21 UTC
#### Describe the bug

Total price of the cart is wrongly calculated on demo products.

#### Expected behavior

Well... cart should have a valid total value. This is critical.

#### Steps to Reproduce

1. Install PrestaShop 1.7.7 (1.7.7 branch) in Polish.
2. You'll have few products with PLN currency, one of them, product ID 2, has price equal to: 35.33 PLN
3. Now add two units of this product to cart.
4. Total price of the cart should be 35.33 * 2 => 70.66, but it's 70.65

It was working fine on previous versions with changed precision calculation to `Round on each item` but it's not a case in 1.7.7.

btw. this scenario has been around for years, after 20% discount we have:
35.328

So it's tricky to recalculate final price **but** it was possible by changing type of price calculation, this option from Preferences -> General is not working now... unfortunately. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2137763/78747361-851cb700-7969-11ea-88c4-9e350ec5bbd6.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by marionf** [comment] 2020-04-08 10:08
Hello @kpodemski 

I can reproduce the issue with PrestaShop 1.7.7, with the option Round on each item and with a product with 20% discount

![capture d'écran_2508](https://user-images.githubusercontent.com/13449658/78771640-caa0aa80-7990-11ea-89cc-e7d20263077c.png)

It's well working with a product without discount

![capture d'écran_2507](https://user-images.githubusercontent.com/13449658/78771678-dbe9b700-7990-11ea-84db-81cc79382bba.png)

It's well a regression as it was working on 1.7.6.4

**Comment by marionf** [comment] 2020-04-08 10:12
Related to: #17045 and #17976

**Comment by kpodemski** [comment] 2020-04-08 10:21
@marionf this tax related issue is also a nasty one, having this kind of issues on clean installation of PrestaShop is destructive

**Comment by matks** [comment] 2020-04-08 15:38
> @marionf this tax related issue is also a nasty one, having this kind of issues on clean installation of PrestaShop is destructive

We agree, that is why there is the `Major` label 😊

**Comment by colinegin** [comment] 2020-04-17 15:17
According to a discussion with @matthieu-rolland, this issue should be fixed thanks to the addition of 2 fixes : 
- make computing precision matching currency's display precision : #18617 
- bug on "round on each item" rounding type #18640 

@sarahdib these PR / issues should be tested and validated before. I leave this issue in to be tested, just to ensure it is correctly fixed once PRs have been merged.

**Comment by colinegin** [comment] 2020-04-20 13:05
I just removed the issue from 1.7.7 kanban because both issues related to PR detailed earlier are already in the kanban. We will test that this issue is fixed after merging both PRs.

ping @sarahdib @matthieu-rolland FYI

**Comment by sarahdib** [comment] 2020-04-24 14:16
The PR made by @matthieu-rolland fix this issue. When the PR will be merged this issue can be closed @colinegin

**Comment by colinegin** [comment] 2020-04-24 14:17
Amazing, thanks a lot !

**Comment by Progi1984** [comment] 2020-04-24 14:47
Fixed by #18617

**Closed as completed by Progi1984** 2020-04-24 14:47 UTC
Labels: Bug, Major, FO, Duplicate, Regression, Fixed, 1.7.7.x

**Comment by HartLarsson** [comment] 2020-09-11 14:34
there is also a major problem on bad calculation. Every Paypal payment return an error on payment due to some calculation problem.
Every time a customer purchase some items with a voucher or cart discount the total ammount is always wrong as i reported here: https://github.com/PrestaShop/PrestaShop/issues/20889

Tax calculation are wrong and discount % are wrong too cause the rounding problem that is still there since 2018.

Customer PAY MORE of what they due and this is a BIG problem that must be fixed in 1.7.6.x branch too nad not postponed to 1.7.7 or 1.7.8 is a fincncial problem that stop prestashop working as intended.

Can someone prioritize this problem?

Thanks

**Comment by HartLarsson** [comment] 2020-09-19 01:08
continue errors on every order where vouchers are presents:
![image](https://user-images.githubusercontent.com/16102074/93655686-4bc29a00-fa25-11ea-89cf-da2672bc969d.png)

PS: 1.7.6.7
php: 7.2

**Comment by khouloudbelguith** [comment] 2020-10-08 09:54
Duplicate of #18717
