### ISSUE TITLE
Catalog rule creates inconsistent specific prices

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26912] opened 2021-12-08 06:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Setting up a catalog rule seems to add some weird undeletable specific prices to all current products.

**Problem 1**
These products are not added to products added after setting up this catalog rule. This creates inconsistencies for many modules.

**Problem 2**
Shouldn't the setup of the catalog rule itself provide all the rules? Why there are some specific prices added to database?

### Steps to reproduce

1. Set up catalog rules. Here I have some rules with discounts on everything for our VIP customer groups.
![skupinjy](https://user-images.githubusercontent.com/6097524/145160212-774d603d-0c5f-4e0f-b29d-113d0ac89623.JPG)

2. Open any product and you should see some specific prices added.
![specific1](https://user-images.githubusercontent.com/6097524/145160218-9bbaa075-22c0-4768-a85c-d669369c16bf.JPG)

3. Create a new product and see that it has no specific prices.
![specific2](https://user-images.githubusercontent.com/6097524/145160226-b737201b-23b4-4a81-a7c5-75f7aee4062c.JPG)

### PrestaShop version(s) where the bug happened

1.7.6.2

### PHP version(s) where the bug happened

7.2, 7.3

**Comment by matks** [comment] 2021-12-08 08:48
> Shouldn't the setup of the catalog rule itself provide all the rules? Why there are some specific prices added to database?

I might be wrong, but I think there is a weird system where what happens is:

"I set up a rule for products A, B, C but I exclude products D and E, so the system creates the cart rule and then generates specific prices that do apply only to D and E".

The result is that products A, B, C have the cart rule effect, but products D and E have the specific price that _cancel_ the cart rule so it looks like they are excluded from cart rule.

Not sure, but I think I remember something like this.

EDIT: not sure if it generates specific prices or cart rules

**Comment by hibatallahAouadni** [comment] 2021-12-08 13:58
Hello @Hlavtox 

I didn't manage to reproduce the issue with PS1781, see the attached screen record below:

https://watch.screencastify.com/v/LqjYMMlzTNqInrxzRFkC

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-29 11:01
Hello @Hlavtox 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-29 11:01 UTC
Labels: Bug, BO, Catalog price rules, Customer groups, 1.7.6.2, Invalid
