### ISSUE TITLE
Bug logs backoffice

### ISSUE THREAD

**Issue by iulianm16** [PrestaShop/PrestaShop#15021] opened 2019-08-07 12:38 UTC
When i go to Configure advanced > Logs and i select filter by employee and date between two dates i recive this error. 

An exception occurred while executing 'SELECT l.*, e.email, CONCAT(e.firstname, ' ', e.lastname) as employee FROM psdr_log l LEFT JOIN psdr_employee e ON l.id_employee = e.id_employee WHERE (e.lastname LIKE :employee OR e.firstname LIKE :employee) AND (l.date_add BETWEEN :date_from AND :date_to) ORDER BY id_log desc LIMIT 100 OFFSET 0' with params ["2019-08-01", "2019-08-01"]:

Value for :employee not found in params array. Params array key should be "employee"

**Screenshots**
https://drive.google.com/drive/folders/1SnftPPMonMXGrH1HQTECyjzvT824G8Qf?usp=sharing

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-07 12:41
Hi @iulianm16,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by iulianm16** [comment] 2019-08-07 12:41
sry, i edit now the post.

**Comment by khouloudbelguith** [comment] 2019-08-07 12:47
@iulianm16, before this issue occurs, did you make a search with some filters in the logs page?
![image](https://user-images.githubusercontent.com/16067358/62623905-df1c3700-b919-11e9-9d2c-8670133bc317.png)
Thanks!

**Comment by iulianm16** [comment] 2019-08-07 12:49
yes, i select two filters, by employee and by date ( from and to ).

**Comment by iulianm16** [comment] 2019-08-07 12:51
I completed exactly that: 

employee: stancu
date: from 1 august
          to 1 august

p.s: same date at from and to

**Comment by khouloudbelguith** [comment] 2019-08-07 12:59
@iulianm16, Here's the PR: #14926 to fix the issue.
It is added to ps1.7.6.1.
Thanks to check & feedback.

**Comment by iulianm16** [comment] 2019-08-07 13:08
Thanks

**Comment by khouloudbelguith** [comment] 2019-08-07 13:14
Duplicate of #14785

**Closed as completed by khouloudbelguith** 2019-08-07 13:14 UTC
Labels: BO, Duplicate, Logs
