### ISSUE TITLE
[WS] [POST/PUT] Carts - id_customization is not propaged to DB

### ISSUE THREAD

**Issue by mullerpetr76** [PrestaShop/PrestaShop#23570] opened 2021-03-08 21:36 UTC
#### Describe the bug

id_customization is not propagated into DB via webservice/API POST or PUT /carts request

#### Expected behavior

Once I put correct id (not 0) into id_customizaiton, into POST or PUT request to endpoint /carts, this id should be stored into DB.

## 1. Create a cart: 
- **method: POST**
- **body:**

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <cart>
    <id_address_delivery>14</id_address_delivery>
    <id_address_invoice>14</id_address_invoice>
    <id_currency>1</id_currency>
    <id_customer>2</id_customer>
    <id_guest>42</id_guest>
    <id_lang>1</id_lang>
    <id_shop_group>1</id_shop_group>
    <id_shop>1</id_shop>
    <id_carrier></id_carrier>
    <recyclable></recyclable>
    <gift></gift>
    <gift_message></gift_message>
    <mobile_theme></mobile_theme>
    <delivery_option></delivery_option>
    <secure_key>5aa7510184d3eb0a9f550af2456ee182</secure_key>
    <allow_seperated_package></allow_seperated_package>
    <date_add></date_add>
    <date_upd></date_upd>
    <associations>
      <cart_rows>
        <cart_row>
          <id_product>19</id_product>
          <id_product_attribute>0</id_product_attribute>
          <id_address_delivery>14</id_address_delivery>
          <id_customization></id_customization>
          <quantity>1</quantity>
        </cart_row>
      </cart_rows>
    </associations>
  </cart>
</prestashop>
```
## 2. Create a customization
- **method: POST**
- **body:**
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <customization>
    <id_address_delivery>14</id_address_delivery>
    <id_cart>59</id_cart>
    <id_product>19</id_product>
    <id_product_attribute>0</id_product_attribute>
    <quantity>1</quantity>
    <quantity_refunded>0</quantity_refunded>
    <quantity_returned>0</quantity_returned>
    <in_cart>1</in_cart>
    <associations>
      <customized_data_text_fields>
        <customized_data_text_field>
          <id_customization_field>2</id_customization_field>
          <value>[WS] - test customization</value>
        </customized_data_text_field>
      </customized_data_text_fields>
      <customized_data_images></customized_data_images>
    </associations>
  </customization>
</prestashop>
```
## 3. Add the created customization to the cart
- **method: PUT**
- **body:**
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <cart>
	<id>59</id>
    <id_address_delivery>14</id_address_delivery>
    <id_address_invoice>14</id_address_invoice>
    <id_currency>1</id_currency>
    <id_customer>2</id_customer>
    <id_guest>42</id_guest>
    <id_lang>1</id_lang>
    <id_shop_group>1</id_shop_group>
    <id_shop>1</id_shop>
    <id_carrier></id_carrier>
    <recyclable></recyclable>
    <gift></gift>
    <gift_message></gift_message>
    <mobile_theme></mobile_theme>
    <delivery_option></delivery_option>
    <secure_key>5aa7510184d3eb0a9f550af2456ee182</secure_key>
    <allow_seperated_package></allow_seperated_package>
    <date_add>2021-03-16 15:56:18</date_add>
    <date_upd></date_upd>
    <associations>
      <cart_rows>
        <cart_row>
          <id_product>19</id_product>
          <id_product_attribute>0</id_product_attribute>
          <id_address_delivery>14</id_address_delivery>
          <id_customization>10</id_customization>
          <quantity>1</quantity>
        </cart_row>
      </cart_rows>
    </associations>
  </cart>
</prestashop>
```
### The customization id is not saved => NOK
ERROR: Directly in response I receive 0 in id_customization, instead of 14. 
And also in DB is stored 0 in table ps_cart_product in columnt id_customization

#### Additional information

* PrestaShop version: 1.7.7.2 and also 1.7.6.5
* PHP version: 7.3.27

**Comment by hibatallahAouadni** [comment] 2021-03-09 16:21
Hello @mullerpetr76 

Just to make sure, in the first step you create a customization for a product (with this blank schema WS):

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <customization>
    <id><![CDATA[]]></id>
    <id_address_delivery><![CDATA[]]></id_address_delivery>
    <id_cart><![CDATA[]]></id_cart>
    <id_product><![CDATA[]]></id_product>
    <id_product_attribute><![CDATA[]]></id_product_attribute>
    <quantity><![CDATA[]]></quantity>
    <quantity_refunded><![CDATA[]]></quantity_refunded>
    <quantity_returned><![CDATA[]]></quantity_returned>
    <in_cart><![CDATA[]]></in_cart>
    <associations>
      <customized_data_text_fields>
        <customized_data_text_field>
          <id_customization_field><![CDATA[]]></id_customization_field>
          <value><![CDATA[]]></value>
        </customized_data_text_field>
      </customized_data_text_fields>
      <customized_data_images>
        <customized_data_image>
          <id_customization_field><![CDATA[]]></id_customization_field>
          <value><![CDATA[]]></value>
        </customized_data_image>
      </customized_data_images>
    </associations>
  </customization>
</prestashop>
```

And for the cart, did you use this blank schema:

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <cart>
    <id><![CDATA[]]></id>
    <id_address_delivery><![CDATA[]]></id_address_delivery>
    <id_address_invoice><![CDATA[]]></id_address_invoice>
    <id_currency><![CDATA[]]></id_currency>
    <id_customer><![CDATA[]]></id_customer>
    <id_guest><![CDATA[]]></id_guest>
    <id_lang><![CDATA[]]></id_lang>
    <id_shop_group><![CDATA[]]></id_shop_group>
    <id_shop><![CDATA[]]></id_shop>
    <id_carrier><![CDATA[]]></id_carrier>
    <recyclable><![CDATA[]]></recyclable>
    <gift><![CDATA[]]></gift>
    <gift_message><![CDATA[]]></gift_message>
    <mobile_theme><![CDATA[]]></mobile_theme>
    <delivery_option><![CDATA[]]></delivery_option>
    <secure_key><![CDATA[]]></secure_key>
    <allow_seperated_package><![CDATA[]]></allow_seperated_package>
    <date_add><![CDATA[]]></date_add>
    <date_upd><![CDATA[]]></date_upd>
    <associations>
      <cart_rows>
        <cart_row>
          <id_product><![CDATA[]]></id_product>
          <id_product_attribute><![CDATA[]]></id_product_attribute>
          <id_address_delivery><![CDATA[]]></id_address_delivery>
          <id_customization><![CDATA[]]></id_customization>
          <quantity><![CDATA[]]></quantity>
        </cart_row>
      </cart_rows>
    </associations>
  </cart>
</prestashop>
```

Please check and feedback.

PS: it will be better if you could provide the request body that you used :wink: (for creating the customization or the cart)

Thanks!

**Comment by mullerpetr76** [comment] 2021-03-09 17:51
Many thanks for feedback.
(Looks like I dont know how to place code....)

1) Created cart
POST /carts
Body:
at the beginning I have always following:
![obrazek](https://user-images.githubusercontent.com/66279944/110515674-e9f80880-8108-11eb-9aa3-de6a57f51339.png)

>      <cart>
>         <id_address_delivery>8</id_address_delivery>
>         <id_address_invoice>8</id_address_invoice>
>         <id_currency>3</id_currency>
>         <id_customer>5</id_customer>
>         <id_guest></id_guest>
>         <id_lang>1</id_lang>
>         <id_shop_group>1</id_shop_group>
>         <id_shop>1</id_shop>
>         <id_carrier></id_carrier>
>         <recyclable></recyclable>
>         <gift></gift>
>         <gift_message></gift_message>
>         <mobile_theme></mobile_theme>
>         <delivery_option></delivery_option>
>         <secure_key>55c480b89a2122ef19ef9b2186e4a110</secure_key>
>         <allow_seperated_package></allow_seperated_package>
>         <date_add>2021-02-14 12:20:02</date_add>
>         <date_upd>2021-02-14 12:20:02</date_upd>
>         <associations>
>             <cart_rows>
>                 <cart_row>
>                     <id_product>1</id_product>
>                     <id_product_attribute>0</id_product_attribute>
>                     <id_address_delivery>8</id_address_delivery>
>                     <id_customization>0</id_customization>
>                     <quantity>1</quantity>
>                 </cart_row>
>             </cart_rows>
>         </associations>
>     </cart>
> </prestashop>


Response was cart Id = 5

Than I created customization by this:
POST /customizations
Body:

>     <customization>
>         <id_cart>5</id_cart>
>         <id_product>20</id_product>
>         <id_product_attribute>0</id_product_attribute>
>         <quantity_refunded>0</quantity_refunded>
>         <quantity_returned>0</quantity_returned>
>         <in_cart>0</in_cart>
>         <id_address_delivery>0</id_address_delivery>
>         <quantity>5</quantity>
>         <associations>
>             <customized_data_text_fields>
>                 <customized_data_text_field>
>                     <id_customization_field>2</id_customization_field>
>                     <value>zAPI</value>
>                 </customized_data_text_field>
>                 <customized_data_text_field>
>                     <id_customization_field>3</id_customization_field>
>                     <value>z API</value>
>                 </customized_data_text_field>
>                 <customized_data_text_field>
>                     <id_customization_field>4</id_customization_field>
>                     <value>123</value>
>                 </customized_data_text_field>
>             </customized_data_text_fields>
>         </associations>
>     </customization>
> </prestashop>

Response is customization id = 15

Then added to cart:
PUT /carts/5

>     <cart>
>         <id>5</id>
>         <id_address_delivery>8</id_address_delivery>
>         <id_address_invoice>8</id_address_invoice>
>         <id_customer>5</id_customer>
>         <id_currency>3</id_currency>
>         <id_lang>1</id_lang>
>         <id_carrier></id_carrier>
>         <delivery_option></delivery_option>
>         <secure_key>55c480b89a2122ef19ef9b2186e4a110</secure_key>
>         <date_add>2021-02-14 12:20:02</date_add>
>         <date_upd>2021-02-14 12:20:02</date_upd>
>         <associations>
>             <cart_rows>
>                 <cart_row>
>                     <id_product>1</id_product>
>                     <id_product_attribute>0</id_product_attribute>
>                     <id_address_delivery>8</id_address_delivery>
>                     <id_customization>0</id_customization>
>                     <quantity>1</quantity>
>                 </cart_row>
>                 <cart_row>
>                     <id_product>20</id_product>
>                     <id_product_attribute>0</id_product_attribute>
>                     <id_address_delivery>8</id_address_delivery>
>                     <id_customization>15</id_customization>
>                     <quantity>5</quantity>
>                 </cart_row>
>             </cart_rows>
>         </associations>
>     </cart>
> </prestashop>

Hope expected process and bodies :)
(PS: I made this manually from requests, there could be some marginal error)

**Comment by mullerpetr76** [comment] 2021-03-14 11:38
any news please?

**Comment by hibatallahAouadni** [comment] 2021-03-16 15:50
Hello @mullerpetr76 

Sorry for the late response, but I encountered a blocking issue with Postman :confused: 
Now, I followed your steps and here's what I got:

## 1. Create a cart: 
- **method: POST**
- **body:**

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <cart>
    <id_address_delivery>14</id_address_delivery>
    <id_address_invoice>14</id_address_invoice>
    <id_currency>1</id_currency>
    <id_customer>2</id_customer>
    <id_guest>42</id_guest>
    <id_lang>1</id_lang>
    <id_shop_group>1</id_shop_group>
    <id_shop>1</id_shop>
    <id_carrier></id_carrier>
    <recyclable></recyclable>
    <gift></gift>
    <gift_message></gift_message>
    <mobile_theme></mobile_theme>
    <delivery_option></delivery_option>
    <secure_key>5aa7510184d3eb0a9f550af2456ee182</secure_key>
    <allow_seperated_package></allow_seperated_package>
    <date_add></date_add>
    <date_upd></date_upd>
    <associations>
      <cart_rows>
        <cart_row>
          <id_product>19</id_product>
          <id_product_attribute>0</id_product_attribute>
          <id_address_delivery>14</id_address_delivery>
          <id_customization></id_customization>
          <quantity>1</quantity>
        </cart_row>
      </cart_rows>
    </associations>
  </cart>
</prestashop>
```
- **Result:**
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <cart>
        <id>
            <![CDATA[59]]>
        </id>
        <id_address_delivery xlink:href="http://prestashop/prestashop_1.7.7.1/api/addresses/14">
            <![CDATA[14]]>
        </id_address_delivery>
        <id_address_invoice xlink:href="http://prestashop/prestashop_1.7.7.1/api/addresses/14">
            <![CDATA[14]]>
        </id_address_invoice>
        <id_currency xlink:href="http://prestashop/prestashop_1.7.7.1/api/currencies/1">
            <![CDATA[1]]>
        </id_currency>
        <id_customer xlink:href="http://prestashop/prestashop_1.7.7.1/api/customers/2">
            <![CDATA[2]]>
        </id_customer>
        <id_guest xlink:href="http://prestashop/prestashop_1.7.7.1/api/guests/42">
            <![CDATA[42]]>
        </id_guest>
        <id_lang xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/1">
            <![CDATA[1]]>
        </id_lang>
        <id_shop_group>
            <![CDATA[1]]>
        </id_shop_group>
        <id_shop>
            <![CDATA[1]]>
        </id_shop>
        <id_carrier></id_carrier>
        <recyclable></recyclable>
        <gift></gift>
        <gift_message></gift_message>
        <mobile_theme></mobile_theme>
        <delivery_option></delivery_option>
        <secure_key>
            <![CDATA[5aa7510184d3eb0a9f550af2456ee182]]>
        </secure_key>
        <allow_seperated_package></allow_seperated_package>
        <date_add>
            <![CDATA[2021-03-16 15:56:18]]>
        </date_add>
        <date_upd>
            <![CDATA[2021-03-16 15:56:18]]>
        </date_upd>
        <associations>
            <cart_rows nodeType="cart_row" virtualEntity="true">
                <cart_row>
                    <id_product xlink:href="http://prestashop/prestashop_1.7.7.1/api/products/19">
                        <![CDATA[19]]>
                    </id_product>
                    <id_product_attribute xlink:href="http://prestashop/prestashop_1.7.7.1/api/combinations/0">
                        <![CDATA[0]]>
                    </id_product_attribute>
                    <id_address_delivery xlink:href="http://prestashop/prestashop_1.7.7.1/api/addresses/14">
                        <![CDATA[14]]>
                    </id_address_delivery>
                    <id_customization xlink:href="http://prestashop/prestashop_1.7.7.1/api/customizations/0">
                        <![CDATA[0]]>
                    </id_customization>
                    <quantity>
                        <![CDATA[1]]>
                    </quantity>
                </cart_row>
            </cart_rows>
        </associations>
    </cart>
</prestashop>
```
## 2. Create a customization
- **method: POST**
- **body:**
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <customization>
    <id_address_delivery>14</id_address_delivery>
    <id_cart>59</id_cart>
    <id_product>19</id_product>
    <id_product_attribute>0</id_product_attribute>
    <quantity>1</quantity>
    <quantity_refunded>0</quantity_refunded>
    <quantity_returned>0</quantity_returned>
    <in_cart>1</in_cart>
    <associations>
      <customized_data_text_fields>
        <customized_data_text_field>
          <id_customization_field>2</id_customization_field>
          <value>[WS] - test customization</value>
        </customized_data_text_field>
      </customized_data_text_fields>
      <customized_data_images></customized_data_images>
    </associations>
  </customization>
</prestashop>
```
- **result:**
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <customization>
        <id>
            <![CDATA[10]]>
        </id>
        <id_address_delivery xlink:href="http://prestashop/prestashop_1.7.7.1/api/addresses/14">
            <![CDATA[14]]>
        </id_address_delivery>
        <id_cart xlink:href="http://prestashop/prestashop_1.7.7.1/api/carts/59">
            <![CDATA[59]]>
        </id_cart>
        <id_product xlink:href="http://prestashop/prestashop_1.7.7.1/api/products/19">
            <![CDATA[19]]>
        </id_product>
        <id_product_attribute>
            <![CDATA[0]]>
        </id_product_attribute>
        <quantity>
            <![CDATA[1]]>
        </quantity>
        <quantity_refunded>
            <![CDATA[0]]>
        </quantity_refunded>
        <quantity_returned>
            <![CDATA[0]]>
        </quantity_returned>
        <in_cart>
            <![CDATA[1]]>
        </in_cart>
        <associations>
            <customized_data_text_fields nodeType="customized_data_text_field" virtualEntity="true"/>
            <customized_data_images nodeType="customized_data_image" virtualEntity="true"/>
        </associations>
    </customization>
</prestashop>
```
### As you can see the customization value is not saved => NOK

## 3. Add the created customization to the cart
- **method: PUT**
- **body:**
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <cart>
	<id>59</id>
    <id_address_delivery>14</id_address_delivery>
    <id_address_invoice>14</id_address_invoice>
    <id_currency>1</id_currency>
    <id_customer>2</id_customer>
    <id_guest>42</id_guest>
    <id_lang>1</id_lang>
    <id_shop_group>1</id_shop_group>
    <id_shop>1</id_shop>
    <id_carrier></id_carrier>
    <recyclable></recyclable>
    <gift></gift>
    <gift_message></gift_message>
    <mobile_theme></mobile_theme>
    <delivery_option></delivery_option>
    <secure_key>5aa7510184d3eb0a9f550af2456ee182</secure_key>
    <allow_seperated_package></allow_seperated_package>
    <date_add>2021-03-16 15:56:18</date_add>
    <date_upd></date_upd>
    <associations>
      <cart_rows>
        <cart_row>
          <id_product>19</id_product>
          <id_product_attribute>0</id_product_attribute>
          <id_address_delivery>14</id_address_delivery>
          <id_customization>10</id_customization>
          <quantity>1</quantity>
        </cart_row>
      </cart_rows>
    </associations>
  </cart>
</prestashop>
```
- **result:**
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <cart>
        <id>
            <![CDATA[59]]>
        </id>
        <id_address_delivery xlink:href="http://prestashop/prestashop_1.7.7.1/api/addresses/14">
            <![CDATA[14]]>
        </id_address_delivery>
        <id_address_invoice xlink:href="http://prestashop/prestashop_1.7.7.1/api/addresses/14">
            <![CDATA[14]]>
        </id_address_invoice>
        <id_currency xlink:href="http://prestashop/prestashop_1.7.7.1/api/currencies/1">
            <![CDATA[1]]>
        </id_currency>
        <id_customer xlink:href="http://prestashop/prestashop_1.7.7.1/api/customers/2">
            <![CDATA[2]]>
        </id_customer>
        <id_guest xlink:href="http://prestashop/prestashop_1.7.7.1/api/guests/42">
            <![CDATA[42]]>
        </id_guest>
        <id_lang xlink:href="http://prestashop/prestashop_1.7.7.1/api/languages/1">
            <![CDATA[1]]>
        </id_lang>
        <id_shop_group>
            <![CDATA[1]]>
        </id_shop_group>
        <id_shop>
            <![CDATA[1]]>
        </id_shop>
        <id_carrier></id_carrier>
        <recyclable></recyclable>
        <gift></gift>
        <gift_message></gift_message>
        <mobile_theme></mobile_theme>
        <delivery_option></delivery_option>
        <secure_key>
            <![CDATA[5aa7510184d3eb0a9f550af2456ee182]]>
        </secure_key>
        <allow_seperated_package></allow_seperated_package>
        <date_add>
            <![CDATA[2021-03-16 15:56:18]]>
        </date_add>
        <date_upd>
            <![CDATA[2021-03-16 16:36:21]]>
        </date_upd>
        <associations>
            <cart_rows nodeType="cart_row" virtualEntity="true">
                <cart_row>
                    <id_product xlink:href="http://prestashop/prestashop_1.7.7.1/api/products/19">
                        <![CDATA[19]]>
                    </id_product>
                    <id_product_attribute xlink:href="http://prestashop/prestashop_1.7.7.1/api/combinations/0">
                        <![CDATA[0]]>
                    </id_product_attribute>
                    <id_address_delivery xlink:href="http://prestashop/prestashop_1.7.7.1/api/addresses/14">
                        <![CDATA[14]]>
                    </id_address_delivery>
                    <id_customization xlink:href="http://prestashop/prestashop_1.7.7.1/api/customizations/0">
                        <![CDATA[0]]>
                    </id_customization>
                    <quantity>
                        <![CDATA[1]]>
                    </quantity>
                </cart_row>
            </cart_rows>
        </associations>
    </cart>
</prestashop>
```
### The customization id is not saved => NOK

I was able to reproduce the issue with PS1.7.7.2, PS1.7.6.7 and develop. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you!

**Comment by mullerpetr76** [comment] 2021-03-16 16:08
Hi @hibatallahAouadni 
thanks for confirming the bug.
I am not able to fix it.
I will wait for the bug fix.
Many thanks!
Petr

**Comment by mullerpetr76** [comment] 2021-06-01 22:10
Any progress so far?! :(

**Comment by hibatallahAouadni** [comment] 2021-06-02 07:23
Hello @mullerpetr76 

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2022-11-01 19:57 UTC
Labels: Bug, Minor, WS, Shopping carts, Product customization, Fixed, PR available, 1.7.6.7, Verified

**Comment by mullerpetr76** [comment] 2023-01-15 16:30
The issue is still in the product :( I just installed 8.0.0 and upgraded to 8.0.1 and the issue is still there :(

**Comment by NeOMakinG** [comment] 2023-01-15 17:24
@mullerpetr76 I guess this has been fixed on `develop` so it should be shipped into `8.1` as it was not a regression but an historical bug!

**Comment by oubihis** [comment] 2023-10-03 22:43
Any progress ??
Is there any update regarding this issue.

**Comment by oubihis** [comment] 2023-10-03 22:57
Reproducing the Bug:

- Describe the bug: id_customization is not propagated into the database via the webservice/API POST or PUT /carts request.

Expected behavior:

- When a correct id (not 0) is included in the id_customization field of a POST or PUT request to the /carts endpoint, this id should be stored in the database.

Code Suggestion:

In the `setWsCartRows` function inside `classes/Cart.php`, consider adding the following code to ensure that `id_customization` is correctly handled:

```php
(isset($value['id_customization']) ? (int) $value['id_customization'] : 0) . ', '
