### ISSUE TITLE
PrestaShopCollection pagination fails when not providing $id_lang

### ISSUE THREAD

**Issue by thomasnares** [PrestaShop/PrestaShop#32300] opened 2023-04-24 07:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using PrestaShopCollection, 
When not using `$id_lang` in constructor,
When fetching entities with multi-lang attributes,
When using pagination, 

It fails. 

For example: we expect to retrieve 10 products :

```php
$productCollection = (new PrestaShopCollection('Product'))->setPageSize(10)->setPageNumber(1); 
var_dump(count($productCollection));
if(count($productCollection) > 0){
  foreach($productCollection as $product){
    var_dump($product->id, $product->name); 
  }
}
```

```
int(5)
int(1)
array(2) {
  [1]=>
  string(27) "Hummingbird printed t-shirt"
  [2]=>
  string(27) "Hummingbird printed t-shirt"
}
int(2)
array(2) {
  [1]=>
  string(27) "Hummingbird printed sweater"
  [2]=>
  string(27) "Hummingbird printed sweater"
}
int(3)
array(2) {
  [1]=>
  string(38) "The best is yet to come' Framed poster"
  [2]=>
  string(38) "The best is yet to come' Framed poster"
}
int(4)
array(2) {
  [1]=>
  string(34) "The adventure begins Framed poster"
  [2]=>
  string(34) "The adventure begins Framed poster"
}
int(5)
array(2) {
  [1]=>
  string(33) "Today is a good day Framed poster"
  [2]=>
  string(33) "Today is a good day Framed poster"
}
```

Also discussed here: https://github.com/PrestaShop/docs/pull/1645

### Expected behavior

Works fine when specifying an `$id_lang` in the Constructor
```php
$productCollection = (new PrestaShopCollection('Product', 1))->setPageSize(10)->setPageNumber(1); 
var_dump(count($productCollection));
if(count($productCollection) > 0){
  foreach($productCollection as $product){
    var_dump($product->id, $product->name); 
  }
}
```

```
int(10)
int(1)
string(27) "Hummingbird printed t-shirt"
int(2)
string(27) "Hummingbird printed sweater"
int(3)
string(38) "The best is yet to come' Framed poster"
int(4)
string(34) "The adventure begins Framed poster"
int(5)
string(33) "Today is a good day Framed poster"
int(6)
string(27) "Mug The best is yet to come"
int(7)
string(24) "Mug The adventure begins"
int(8)
string(23) "Mug Today is a good day"
int(9)
string(20) "Mountain fox cushion"
int(10)
string(18) "Brown bear cushion"
```

### Steps to reproduce

1. Create a PrestaShopCollection
2. Use pagination

Please explore this bugs by developers. 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2023-04-25 13:10
Hello @thomasnares ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by hibatallahAouadni** [comment] 2023-09-01 08:34
@thomasnares & @PrestaShop/committers do you still encounter this issue with 8.1.x?

**Comment by hibatallahAouadni** [comment] 2023-09-29 14:25
Hello @thomasnares 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-29 14:25 UTC
Labels: Bug, CO, Languages, Invalid, 8.1.x
