### ISSUE TITLE
Autoupgrade is unusable

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#22817] opened 2021-01-13 16:41 UTC
In Addons 1-click upgrade is not available. The page is there nut you cannot download anything.

Using PS 1.7.6.1 I have version 3.0.3 of 1-click upgrade. When I click on the Upgrade button I get an error message and nothing is upgraded. 

So I went to Github and downloaded the latest version (4.11.0) there. But when I try to install it I get an error. See the attached image.
![upgrade](https://user-images.githubusercontent.com/13930107/104481852-8baa2000-55c6-11eb-8038-eb177c4bbd6c.jpg)

**Comment by matks** [comment] 2021-01-13 16:44
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22819

**Closed as completed by matks** 2021-01-13 16:44 UTC
Labels: Duplicate

**Comment by hibatallahAouadni** [comment] 2021-01-13 17:04
Thanks @matks :wink:
