### ISSUE TITLE
Cart rules: problem with "Carrier selection"

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#24101] opened 2021-04-17 09:43 UTC
Hi

#### Describe the bug
If I create a cart rule without to set the promo code and adding a gift product, it works well like usually adding it directly to the cart. but if I add a "carrier selection" removing a carrier the cart rule will not work anymore.

#### Expected behavior

with the carrier selection the cart rule should work like normal

#### Steps to Reproduce

follow the settings present in the images. at the end add the carrier selection removing a carrier, the promo will not work and you can remove the gift product from the cart summary.
the last image is when the carrier selection is not set

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/115108233-98486680-9f6f-11eb-9733-72042bb96477.png)
![2](https://user-images.githubusercontent.com/653230/115108236-99799380-9f6f-11eb-82b0-b41389b69bdf.png)
![3](https://user-images.githubusercontent.com/653230/115108237-9a122a00-9f6f-11eb-844d-a591494900ed.png)
![4](https://user-images.githubusercontent.com/653230/115108238-9aaac080-9f6f-11eb-9148-0497bb69321f.png)
![5](https://user-images.githubusercontent.com/653230/115108239-9b435700-9f6f-11eb-9d95-c52acd69de54.png)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-04-19 12:04
Hello @maofree 

Thanks for the detailed report :clap: 
Well, the voucher doesn't not apply cause you didn't select yet the carrier, please check my screen record below:

https://www.awesomescreenshot.com/video/3433808?key=003ec50557a72b461d2ef083621fc7c7

As you can see when I select the carrier, the voucher has been applied.
So, it's not a bug :sweat_smile: I close the issue. 
If you have any other question or if it seems that I didn't understand the problem, please notify me and I will reopen the issue :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-19 12:04 UTC
Labels: No change required
