### ISSUE TITLE
Adding a basket of personalized products

### ISSUE THREAD

**Issue by TFF1604** [PrestaShop/PrestaShop#18572] opened 2020-04-10 12:04 UTC
Good morning all,

I would like to point out a small anomaly in the addition of a customizable product basket and inventory management.

I have a customizable product (stock: quantity: 1)

1 / I add the product to the cart with a first personalization (image 1)

2 / I add the same product with a second personalization (image 2)

Normally, with inventory management activated and only one product in stock, I should not be able to add the second to the basket, but in this case I get there: (image 3)

I also specify that when I try with a product without personalization, the stock management works and I cannot therefore add more products than there is in stock.

Thank you for your help.

![image](https://user-images.githubusercontent.com/63454932/78989402-d11b5780-7b33-11ea-89fa-eafa890ee212.png)

![image](https://user-images.githubusercontent.com/63454932/78989413-d8dafc00-7b33-11ea-9ee9-8cb9bdecc7da.png)

![image](https://user-images.githubusercontent.com/63454932/78989422-dd9fb000-7b33-11ea-8665-68e27b70aa0b.png)

PrestaShop version : 1.7.6.4 
PHP version : 7.1.32

**Comment by marionf** [comment] 2020-04-14 12:53
Hello @TFF1604 

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9974
Please follow this issue

**Comment by marionf** [comment] 2020-04-14 12:53
Dulicate of https://github.com/PrestaShop/PrestaShop/issues/9974

**Closed as completed by marionf** 2020-04-14 12:53 UTC
Labels: Duplicate
