### ISSUE TITLE
Permission denied under Windows for PS 8.1

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33554] opened 2023-08-06 13:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

While browsing through the frontside of my shop under Windows I regularly get the following pair of errors in the error log:

> [Sun Aug 06 15:45:18.541569 2023] [php7:warn] [pid 5576:tid 1832] [client ::1:50859] PHP Warning:  SessionHandler::read(): open(D:\\xampp\\tmp\\sess_3641ag7r35pvip63agm13s2bd8, O_RDWR) failed: Permission denied (13) in D:\\xampp\\htdocs\\shop\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\StrictSessionHandler.php on line 59, referer: http://localhost/shop/content/10-impressum
[Sun Aug 06 15:45:18.541569 2023] [php7:warn] [pid 5576:tid 1832] [client ::1:50859] PHP Warning:  session_start(): Failed to read session data: user (path: D:\\xampp\\tmp) in D:\\xampp\\htdocs\\shop\\classes\\controller\\FrontController.php on line 732, referer: http://localhost/shop/content/10-impressum

The appearance is irregular: I estimate once every two or three pages that I visit.

### Expected behavior

No error messages.

This is Windows. So write permissions shouldn't be a problem.

### Steps to reproduce

Browse 8.1 installation under Windows

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment] 2023-08-06 18:33
Hello @musicpanda 

I am closing this ticket since there's very little chance we can handle these errors correctly. There are more Windows-specific errors, for example, sometimes you have to clear the cache a few times, and sometimes there's a problem with how Windows reads cache files, producing fatal errors, but it is not a PrestaShop-specific error. It occurs on any web app since Windows handles applications with many files poorly. I've experienced them very often because I used to work on Windows for over ten years of my developer's journey.

If you want a much better experience using any web app on Windows, I highly recommend using their WSL2 solution (Windows sub-system Linux) or Docker.

**Closed as completed by kpodemski** 2023-08-06 18:33 UTC
Labels: Bug

**Comment by musicpanda** [comment] 2023-08-06 19:30
This is indeed a minor problem. There is a much more serious problem with PS 8.1 under Windows crashing on pages with accented text (see for example: https://www.prestashop.com/forums/topic/1078879-prestashop-81-a-problem-with-combinations/). But in my installation I first consistently got an error and later it consistently worked. So I can't make post it yet.

**Comment by kpodemski** [comment] 2023-08-06 19:42
It looks like an error with the database engine 🤔 tricky part is that maybe 1 or 2 members of the project have access to Windows, so it is hard to even reproduce errors, also there's Xampp, Laragon, WAMP and they all work differently :/
