### ISSUE TITLE
Duplicate feature when importing from csv in 1.7.6.8

### ISSUE THREAD

**Issue by sebidk** [PrestaShop/PrestaShop#24386] opened 2021-05-07 07:42 UTC
**#### Describe the bug**

hello, i am facing the following issue when importing products via the native import module in 1.7.6.8

For new products, when i import the Features (Feature:name:value:customize) everything works fine and adds the correct predefined value. If i need to update the feature of certain products i am faced with a duplication of the feature rather than an update, therefore i get 2 different values for the same Feature, and that messes the filters in the product list. So for example:

**#### Expected behavior**

Importing 50 products with the regular infos and the Feature value as: Product Type:CD:1:0 - Everything works fine

but oops, 25 of the products i've just imported are actually DVD's, so naturally i get the 25 products and modify the feature to Product Type:DVD:1:0, and make a csv that contains only the ID and Feature columns, and import it again.

Now, before 1.7, this would automatically update the value for the predefined feature, but now, because you are able to add 2 values to the same feature in the backend (why would someone do that?) the import just ADDS another row with the same feature and the second value, so now my filters are messed because instead of having 25 CDs and 25 DVDs in the layered navigation filters, i have:

CD (50) - the 25 cds plus the modified dvd's that now have the second value
DVD (25) - the 25 products that were modified to be dvds but also kept the CD value, therefore rendering the the CD option useless, because it basically shows all of the products.

**#### Steps to Reproduce**

1. Create a csv file with 2 new products to import and the same Feature and Value that is not customized - so value 0 (Product type: x : 1 : 0)

2. Import the file, and you will have one feature and value for every product in the backend

3. Modify one of the products value from "x", to "y" so you will have Product type:y:1:0 and re-upload the file.

4. Check the backend of the products an you will notice that one product has 2 Feature row with the same value "x" and one product has 2 Feature row with value x and y.

**
[testfiles.zip](https://github.com/PrestaShop/PrestaShop/files/6440265/testfiles.zip)
**

no screenshots that can make sense, but i have added to csv file for testing, one for import, one for update, the separator is ";" if someone asks.

**#### Additional information**

* PrestaShop version: 1.7.6.8
* PHP version: 7.3.27

**Comment by florine2623** [comment] 2021-05-07 08:17
Hello @sebidk ,

Could you follow the bug template so we can try to reproduce the issue ?
![Capture d’écran 2021-05-07 à 10 17 10](https://user-images.githubusercontent.com/16019289/117420013-77938100-af1d-11eb-8227-402b19e30623.png)

**Comment by sebidk** [comment] 2021-05-07 08:47
sorry, first post :) - i have edited the post, hopefully it's more understandable now.

**Comment by hibatallahAouadni** [comment] 2021-05-10 01:46
Hello @sebidk 

Could you please check this issue #14305 it seems realted to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-27 13:29
Hello @sebidk ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-27 13:29 UTC
Labels: Bug, BO, Import / Export, Features, No change required, 1.7.6.8
