### ISSUE TITLE
Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#21675] opened 2020-10-29 17:53 UTC
Dear staff,
every order we've got we receive into the logs (BO) section this advice (only information):
Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

<img width="951" alt="Schermata 2020-10-29 alle 18 51 00" src="https://user-images.githubusercontent.com/28685316/97612491-c95fc980-1a17-11eb-8808-0c93ac68f13f.png">

**Payment module we use**
Paypal native module
PagOnline (purchased from prestashop addons)

Can this compromise the site?
Thanks for any reply.
Balla

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-10-30 08:25
Hi @ballashop ,

Your issue seems to be related to this : https://github.com/PrestaShop/PrestaShop/issues/9866
Please check
Thanks!

**Comment by hibatallahAouadni** [comment] 2020-10-30 09:22
Hi @ballashop ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9866 (as @florine2623 mentionned).
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-10-30 09:23
Duplicate of #9866

**Closed as completed** 2020-10-30 09:23 UTC
Labels: Duplicate, Logs, 1.7.6.8

**Comment by ballashop** [comment] 2020-10-30 09:27
ok, thanks a lot, sorry for the duplication, I had searched but not found it before posting.
Balla
