### ISSUE TITLE
Products missing in BO due to languages

### ISSUE THREAD

**Issue by lionelJDN** [PrestaShop/PrestaShop#35758] opened 2024-03-27 10:45 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Two languages are available (English and French) and only one is enabled (English). Because i need the FO is in English.
![image](https://github.com/PrestaShop/PrestaShop/assets/111759208/db5851d8-aba8-4bbe-a59f-16011739abff)
The BO is in French language.
I added a product and it's missing of the listing of products.
To display the product, i need to switch the language of the BO to English.

### Expected behavior

Even the FO is in English, i need to have the BO in French with all products. 

### Steps to reproduce

1. Go to International / Localization / Languages
2. Enable English / Disable French
3. Go to your profile / Switch to French language and Save.
![image](https://github.com/PrestaShop/PrestaShop/assets/111759208/ac6dec89-4a8d-4ca0-838e-3807fa9ade82)
4. Go to Catalogue / Produits
5. Add a product by clicking on the "+ Nouveau produit" button.
6. Give a name and a reference to the product and click on the "Enregistrer" button.
7. Return to Catalogue / Produits ==> the new product is missing
8.  Go to your profile / Switch to English language and Save.
![image](https://github.com/PrestaShop/PrestaShop/assets/111759208/ac6dec89-4a8d-4ca0-838e-3807fa9ade82)
9. Go to Catalog / Products ==> the product is visible now

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.13

**Comment by paulnoelcholot** [comment] 2024-03-28 08:20
Hello @lionelJDN,

Despite our efforts, we were not able to reproduce your issue with the provided information on Prestashop 8.1.5. We invite you to upgrade your shop to correct the problem.

We will close this issue.

Thank you

https://www.loom.com/share/d0aee2c4995046c18aed6431e7960363?sid=b0c732ce-6e3c-4b00-aaf8-bffe11bf4c3c

**Closed as completed by paulnoelcholot** 2024-03-28 08:20 UTC
Labels: Bug, Can't reproduce
