### ISSUE TITLE
Order prices block not correctly displayed in the BO

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#25140] opened 2021-06-28 08:55 UTC
#### Describe the bug

When you go to the Order view in the BO, the summary block that displays the order prices (products, shipping, total) is not correctly displayed.

In develop the block is aligned to the left and is out of its container:
![Capture d’écran 2021-06-28 à 10 44 18](https://user-images.githubusercontent.com/13801017/123608000-abdd3c80-d7fe-11eb-9bb2-ff22143ceb0e.png)

In 1.7.8.x the block is correctly centered but the buttons "Add a product" "Add a discount" are not correctly aligned:
![Capture d’écran 2021-06-28 à 10 45 54](https://user-images.githubusercontent.com/13801017/123608112-c4e5ed80-d7fe-11eb-98e5-e99ca46831e0.png)

#### Expected behavior

The expected result is like in 177, the buttons are don't the same line as the pagination details and the summary block is correctly centered:
![Capture d’écran 2021-06-28 à 10 46 09](https://user-images.githubusercontent.com/13801017/123608240-de873500-d7fe-11eb-898b-a08bd8e08f25.png)

#### Steps to Reproduce

Steps to reproduce the behavior (on develop and 178x):

1. Go to Orders in the BO
2. Click on any order you want to preview
3. See that the block is not correctly displayed

#### Additional information

* PrestaShop version: 1.7.8, develop
* PHP version: N/A

**Comment by jolelievre** [comment] 2021-06-28 12:25
I installed a fresh version from `develop` branch The block is now correctly centered (I guess my former assets were not up to date) However I have the same bug as in 178 (the buttons are not correctly aligned)

**Comment by hibatallahAouadni** [comment] 2021-06-28 12:32
Hello @jolelievre 

Exactly, :sweat_smile: because I update my develop and I didn't see any error, I was confused.
Well, I close the issue :wink: 

Thanks!

**Comment by jolelievre** [comment] 2021-07-15 16:06
Hi @hibatallahAouadni I reopen this issue because there is still the problem on the 1.7.8.x branch
Also at the time the develop branch was fine but now I have the same problem as in 178 branch

The problem is like this:
![Capture d’écran 2021-07-15 à 18 05 06](https://user-images.githubusercontent.com/13801017/125820423-20a903a5-2bd1-41f4-bc39-ea7f9c431fe0.png)

The expected display (from 177)
![Capture d’écran 2021-07-15 à 18 05 15](https://user-images.githubusercontent.com/13801017/125820481-c5ce1c5d-3c34-403d-bc70-d8aa26d5c18a.png)

**Comment by hibatallahAouadni** [comment] 2021-07-16 09:42
Hello @jolelievre 

Yes I manage to reproduce the issue only with PS178x and develop. So, it's a regression!
And thanks for your PR :rocket: 

Thanks!

**Comment by Progi1984** [comment] 2021-07-21 12:37
Fixed in #25364 by @jolelievre

**Closed as completed by Progi1984** 2021-07-21 12:37 UTC
Labels: Bug, develop, Trivial, BO, Order, Regression, Fixed, Front-end, PR available, 1.7.8.x
