### ISSUE TITLE
Sort products in 1.7.6.3

### ISSUE THREAD

**Issue by luciobenini** [PrestaShop/PrestaShop#20049] opened 2020-07-03 10:38 UTC
Hello,
the default sort order in categories position ASC but it can't be selected and the controller returns only position DESC.

How can I add position ASC to the sort orders?

Thank you.

**Comment by florine2623** [comment] 2020-07-03 12:00
Hi @luciobenini ,
Could you give more info about your issue ?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by luciobenini** [comment] 2020-07-15 17:05
Hi,
sorry for the delay.


host -> linux
server setup and configuration -> lamp
PrestaShop version (source) -> 1.7.6.3
debug mode report -> N/A
PHP error logs -> N/A
apache error log -> N/A
javascript console log -> No errors
screenshots -> ![WhatsApp Image 2020-07-15 at 19 02 47](https://user-images.githubusercontent.com/12533159/87574031-1076b880-c6ce-11ea-81b2-11709142a572.jpeg)

**Comment by florine2623** [comment] 2020-07-16 10:22
Is your issue related to https://github.com/PrestaShop/PrestaShop/issues/19810 ?

**Comment by khouloudbelguith** [comment] 2020-08-05 08:25
Hi @luciobenini,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-05 08:25 UTC
Labels: No change required
