### ISSUE TITLE
Error loading products if changing products route parameters order

### ISSUE THREAD

**Issue by Miguel86** [PrestaShop/PrestaShop#22204] opened 2020-12-03 07:28 UTC
Hello:

#### Describe the bug

I have changed the products route in the backoffice, now the products shown in the main page don't work. When i enter to a product shows another product or returns a 404 page.

#### Expected behavior

Load the correct product.

#### Steps to Reproduce

1. Fresh install of 1.7.6.9
2. Added English (English GB) package as my installation is in Spanish
3. Go to Shop parameters => SEO & URLs
4. Scroll down to: Route to products and change from:
     {category:/}{id}{-:id_product_attribute}-{rewrite}{-:ean13}.html
    To:
     {category:/}{rewrite}-{id}{-:id_product_attribute}{-:ean13}.html
5. Go to home page and click on the product added by the default installation: Hummingbird Printed T-Shirt in the white color square box.
6. Instead of that product is loaded the product: The best is yet to come' Framed poster

Other products just give a 404 error, for example loading:
Mountain Fox Cushion

**Screenshots**
![Captura de pantalla 2020-12-03-1](https://user-images.githubusercontent.com/3440225/100977570-73fc6800-3541-11eb-9ed4-7d7cfa9f1f85.png)
![Captura de pantalla 2020-12-03-2](https://user-images.githubusercontent.com/3440225/100977585-78288580-3541-11eb-867c-62ba212ef117.png)

Error 404 loading fox cushion:
![Captura de pantalla 2020-12-03-3](https://user-images.githubusercontent.com/3440225/100977624-7eb6fd00-3541-11eb-84f0-e2d81b423e1f.png)
![Captura de pantalla 2020-12-03-4](https://user-images.githubusercontent.com/3440225/100977636-824a8400-3541-11eb-9779-f57087ed7828.png)

#### Additional information
* PrestaShop version: 1.7.6.9
* PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment] 2020-12-03 12:52
Hello @Miguel86 

Could you please check if your issue is duplicated to this one #11041 ? see this [comment](https://github.com/PrestaShop/PrestaShop/issues/11041#issuecomment-431840672) 

Thanks!

**Comment by Miguel86** [comment] 2020-12-03 13:04
> Hello @Miguel86
> 
> Could you please check if your issue is duplicated to this one #11041 ? see this [comment](https://github.com/PrestaShop/PrestaShop/issues/11041#issuecomment-431840672)
> 
> Thanks!

That comment suggests to change order as i made, however is when the error comes up. Originally the user wanted to remove the anchor, i didn't expect that i just wanted to reorder the fields of the URL, which was working fine for me in Prestashop 1.6 so in my opinion is not the same.

**Comment by hibatallahAouadni** [comment] 2020-12-03 14:12
@Miguel86 I believe that improvement when it's done, your issue will be fixed :wink:

**Comment by Miguel86** [comment] 2020-12-03 14:22
That improvement was requested 2 years ago. This is breaking the possibility to upgrade websites from Prestashop 1.6 to 1.7 and an error should not wait to be fixed by an improvement (in my opinion obviously). This is a several SEO problem, is not something we can just "leave" for the future.

**Comment by hibatallahAouadni** [comment] 2020-12-03 15:20
Hello @Miguel86 

It's already in our debug backlog (**`To Do`**) and it's assigned to @PierreRambaud  
So, I don't think it will take a long time to be resolved!

Thanks!

**Comment by PierreRambaud** [comment] 2020-12-03 15:26
> That improvement was requested 2 years ago. This is breaking the possibility to upgrade websites from Prestashop 1.6 to 1.7 and an error should not wait to be fixed by an improvement (in my opinion obviously). This is a several SEO problem, is not something we can just "leave" for the future.

Don't forget this is an open source project. Feel free to contribute if you think this issue or another one is mandatory for your business :wink:

**Comment by hibatallahAouadni** [comment] 2020-12-03 15:38
Hello @Miguel86 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #11041. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

As @PierreRambaud mentioned above, if you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-03 15:38
Duplicate of #11041

**Closed as completed by hibatallahAouadni** 2020-12-03 15:38 UTC
Labels: Bug, BO, Duplicate, SEO & URLs, 1.7.6.9
