### ISSUE TITLE
Faceted search don't work fine

### ISSUE THREAD

**Issue by maarlok** [PrestaShop/PrestaShop#15157] opened 2019-08-19 14:39 UTC
**Describe the bug**
Facetedsearch module don't work fine. 
when the filters are selected at the same time the products are not found.

PrestaShop version: 1.7.5
Facetedsearch version: 3.2.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-08-19 15:42
Hi @maarlok,

I did not manage to reproduce the issue with PS1.7.6.0 & the ps_facetedsearch v3.2.0.
I attached a screen record
https://drive.google.com/file/d/1ojiRjUVk99a-7DGGKrWliKZuqB8iunCJ/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-09-18 07:36
Hi @maarlok,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-18 07:36 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.5.2
