### ISSUE TITLE
Errors appear when we import some localization pack (shuffle machine)

### ISSUE THREAD

**Issue by mariem-abid** [PrestaShop/PrestaShop#29550] opened 2022-09-06 13:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

When we perform the technical validation of some modules, we have to import localization packages.

### Expected behavior

The pack should be imported successfully.

### Steps to reproduce

1. Go to International.
2. Go to Localization.
3. Import Pack 'United States' -> getting error.

Examples of packs that generated an error: United States, United Kingdom, Egypt, Ecuador, and Argentina ...

See the screen record below.
https://forge.prestashop.com/secure/attachment/92300/pack.webm

### PrestaShop version(s) where the bug happened

1.7.7.7 / 1.7.8.7

### PHP version(s) where the bug happened

7.3 / 7.4

**Comment by sLorenzini** [comment] 2022-09-06 14:39
Hello @mariem-abid ,

I reproduce the issue with PrestaShop version 1.7.8.7 on shuffle machine. I couldn't tested it on an older version (shuffle machine doesn't allow it). As discussed with you, this issue seems to be here since at least 2020.
Here's my screenrecord:

https://user-images.githubusercontent.com/2854834/188663860-53f31a6b-99f8-4e5f-a17a-7050dca69c6c.mp4

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment] 2024-11-21 15:43
Won't fixed as cannot be reproduced on 9.0.0 (no shuffle machine used)

**Closed as completed by florine2623** 2024-11-21 15:43 UTC
Labels: Bug, Minor, BO, Won't fix, Localization, Languages, 1.7.6.9, Verified
