### ISSUE TITLE
It should not be possible to purchase a pack which requires more quantity of pack item than there is in stock

### ISSUE THREAD

**Issue by robi-bobi** [PrestaShop/PrestaShop#13769] opened 2019-05-13 12:16 UTC
**Describe the bug**
It should not be possible to purchase a pack which requires more quantity of pack item than there is in stock.

**To Reproduce**

In Admin I have pack product.
In that Pack product I have added a combination product with quantity 100.
The combination product itself has less than 100 quantity availability (for example, 99).
Global setting for packs is to "Decrease both".
My Global Availability preference is "Deny orders" when out of stock.

_Result_:
It is possible to add to cart and purchase the pack.
This results in my combination product having a negative quantity after the purchase. Check screenshot.

_Expected_:
It should not be possible to purchase the pack with this scenario.

**Screenshot:**
<img width="509" alt="Screenshot 2019-05-13 at 15 14 50" src="https://user-images.githubusercontent.com/230215/57620637-07ea9580-7592-11e9-948b-b8e4e6512937.png">

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.17

---
> Originally posted by  @theodiablo in #23706

#### Describe the bug

I have a pack of products, which is the same products but with his different variations.
When one of those product variation is out of stock, the pack is still enabled.

#### Expected behavior

The pack should be disabled and display the "Email me when product is back on stock" form I have

#### Steps to Reproduce

Using the basic Prestashop installation

1. Create a product pack containing several variations of the product "Hummingbird printed t-shirt" s-white, s-black, m-white, m-black for instance
2. In Quantities tab, set "Decrement products in the pack only" option
3. Go to your newly created product, it should be displayed correctly and you can add it to the cart (remove the product if added)
4. Set the stock product "Hummingbird printed t-shirt" "S Black" variation to 0
5. Go to the product page, see that it is displayed as if it had items, however it should be disabled
6. Add the product to your cart, an error comes out.

The pack quantity should be 0, but it is 3000.

#### Screenshots

Variations quantities
![image](https://user-images.githubusercontent.com/8282971/111818228-3bf61680-88df-11eb-9e30-ef745a0c23d1.png)

Pack content
![image](https://user-images.githubusercontent.com/8282971/111818312-503a1380-88df-11eb-8c12-eb82517412a2.png)

Pack quantities config (auto calculated wrong)
![image](https://user-images.githubusercontent.com/8282971/111818385-67790100-88df-11eb-9db8-00b40d90569f.png)

Button enabled, even when one variation has 0 stock
![image](https://user-images.githubusercontent.com/8282971/111818566-9becbd00-88df-11eb-8ac0-686ab9a35db5.png)

Error message after clicking on the "add to cart button"
![image](https://user-images.githubusercontent.com/8282971/111818169-2d0f6400-88df-11eb-987f-6475cd95e786.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-13 13:09
Hi @robi-bobi,

Your ticket is a duplicate of #9671
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-13 13:09
Duplicate of #9671

**Comment by robi-bobi** [comment] 2019-05-13 13:14
Hi @khouloudbelguith 

Thank you for quick reply.
I think my case is a bit different than the one described in #9671.

The #9671 explains some wrong quantities after the purchase, while I explain that the purchase should not be possible at all.

Or, is it that the underlying reason why this happen is the same?

**Comment by khouloudbelguith** [comment] 2019-05-13 13:55
Hi @robi-bobi,

Sorry, yes, it is not a duplicate of #9671, just similar.
But your issue is fixed in the PS1.7.6.0beta1.
I did not manage to reproduce the issue with PS1.7.6.0beta1
https://drive.google.com/file/d/1ESQaaiBQbaMcyoA95WTThMddoaVzqhMU/view
Thanks!

**Comment by robi-bobi** [comment] 2019-05-15 23:38
Hi @khouloudbelguith ,

I have found an issue with 1.7.6 as well.

Screengrab here:
(removed)

What happens, I think, is that the logic takes into account quantity for all combinations, while it should only check that of the selected combination in the pack product.

This is why when I have 7x Pack (which has 3x the item 1), that would result in 21 Item1 products being used. Since there are 4 combinations with 5 quantity each, it is only then that the logic says: Product available with different options.

What should happen instead is when I get to 2x of Pack product - the message should be shown.

**Comment by khouloudbelguith** [comment] 2019-05-16 10:05
Hi @robi-bobi, 

Thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1
Steps to reproduce the issue:
1. create a product P1 with 4 combinations PC1, PC2, PC3, PC4
2. All these combinations have 5 quantity
![image](https://user-images.githubusercontent.com/16067358/57845241-811ffd80-77c9-11e9-8fb6-5766767b6252.png)
3. Create a pack P2 of 3 products PC4 with quantity 50
4. In the Fo, you can add to the cart 6 pack 
5. complete your order
6. Check your product P1 in the BO => quantity = -13

![image](https://user-images.githubusercontent.com/16067358/57845709-72861600-77ca-11e9-9659-93534fead079.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-16 10:06
Related to #9671

**Comment by robi-bobi** [comment] 2019-05-20 11:13
Is the debug roadmap public, I could not find it.
Can you let me know on when this is being planned for?

P.S. I am currently going through your documentation on how to contribute and are investigating the issue as well, but do not let that stop you from fixing it.

**Comment by khouloudbelguith** [comment] 2019-05-20 11:46
@robi-bobi, in this link https://github.com/PrestaShop/PrestaShop/projects, you can find our list of projects.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by robi-bobi** [comment] 2019-05-21 00:19
I understand.
However, rough estimate would be good as well.

***

I'm trying to get to the bottom of this, but the logic is a bit scattered.
I think I have found one candidate for the origin of the issue.

In `PREFIX_pack` table, the `quantity` field contains the value that represents the SUM of all combinations of the pack item.
I believe it should only be the value of quantity of exact combination added.

**Comment by marionf** [comment] 2019-05-22 16:11
@khouloudbelguith In your [example](https://github.com/PrestaShop/PrestaShop/issues/13769#issuecomment-493004964)

What did you choose here ?
![capture d'écran_1584](https://user-images.githubusercontent.com/13449658/58190513-f6ee0280-7cbc-11e9-8816-940b868bb895.png)

**Comment by khouloudbelguith** [comment] 2019-05-23 09:51
Hi @marionf,

I used `Decrement both`.
Thanks!

**Closed as completed** 2021-04-06 12:07 UTC
Labels: Bug, Minor, BO, Stocks, Pack, Fixed, 1.7.5.2, 1.7.6.0, 1.7.7.2

**Comment by matks** [comment] 2021-04-06 12:09
@aDamelincourt Is this bug completely fixed by https://github.com/PrestaShop/PrestaShop/pull/23742 or only partially?

**Comment by aDamelincourt** [comment] 2021-04-06 12:54
> @aDamelincourt Is this bug completely fixed by #23742 or only partially?

I tested this particular case. It is corrected, you can no longer order a pack when the stock of products in the pack is not available.
