### ISSUE TITLE
Multistore shop context

### ISSUE THREAD

**Issue by 2ec0b4** [PrestaShop/PrestaShop#15776] opened 2019-10-01 12:41 UTC
**Describe the bug**
From the back office, on a multistore installation, in a shop context, product price is not displayed in the shop currency ~~and product price included taxes is not well updated on a shop tax rule selection~~

**To Reproduce**
1. I made a PrestaShop installation based on a shop in France, with currency in € and 4 taxes rules
2. I have activated the multistore option
3. In the same shop group, i have add another shop in Switzerland, importing all the data from the first shop except currency and taxes rules
4. From the localization admin page, i have selected this new shop and imported data from Switzerland and get the currency in CHF and 3 new taxes rules for this shop
5. Go edit a product in the context of this shop and see that:
    - the product price currency is not CHF
    - ~~product price included taxes is not well updated on a shop tax rule selection~~

**Additional information**
PrestaShop version: 1.7.4.0

**Comment by khouloudbelguith** [comment] 2019-10-01 12:57
Hi @2ec0b4,

When your second shop is selected, could you please navigate to the BO => International => Localization and check the exact currency by default.

Thanks!

**Comment by 2ec0b4** [comment] 2019-10-01 13:08
Hello @khouloudbelguith 

Thanks for your answer.

From this page, i saw that the default country for the second shop was France. This was a mistake, i change it to Switzerland and now the product price included taxes is well updated on a shop tax rule selection. But, the default currency is good with CHF.

**Comment by khouloudbelguith** [comment] 2019-10-02 09:04
@2ec0b4, The currency CHF  is available only in the second shop?
The first currency € is available in all shops? is it?

Thanks!

**Comment by 2ec0b4** [comment] 2019-10-02 09:22
There is only one currency by shop:

- € for the first one
- CHF for the second one

**Comment by khouloudbelguith** [comment] 2019-10-02 09:59
Hi @2ec0b4,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1CXFVRgHJ9qNIoukJbu7An7dZ7dBj1sTU/view
What is the exact version PrestaShop did you use?

Thanks!

**Comment by 2ec0b4** [comment] 2019-10-02 12:28
@khouloudbelguith,

I use PS1.7.4.0 for a client. I reproduce it on a fresh installation with Docker and PS1.7.4.0: https://www.youtube.com/watch?v=dQw4w9WgXcQ (sorry for the quality)
I did not manage to reproduce it either with PS1.7.6.1.
I have updated the initial comment with the version

Thank you

**Comment by khouloudbelguith** [comment] 2019-10-02 12:33
@2ec0b4, since it is fixed in the last version PrestaShop, I will close the issue.
Related to: https://github.com/PrestaShop/PrestaShop/issues/9931

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-02 12:33 UTC
Labels: 1.7.4.0, Multistore, Currencies, Fixed
