### ISSUE TITLE
Tools::getBrightness($hex) error for order_state

### ISSUE THREAD

**Issue by Eva-F** [PrestaShop/PrestaShop#23101] opened 2021-02-02 14:34 UTC
#### Describe the bug

for order statuses is parsed text as hex (see picture)
![ps34](https://user-images.githubusercontent.com/3242659/106613916-07b2da80-656b-11eb-8fa0-bc05c7b27e86.png)

#### Expected behavior
**Should be evaluated also Web HTML Color  names**

for limegreen (=rgb(50, 205,50) ) should be returned value 141 => color of text  should be #383838 ( instead of white) 
(for now is returned the value 8 )

#### Steps to Reproduce

1. Go to Shop parameters ->Order Settings -> Statuses

#### Additional information

* PrestaShop version: 1.7.6

**Comment by hibatallahAouadni** [comment] 2021-02-02 14:51
Hello @Eva-F 

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- PrestaShop version (source)
- PHP version
- steps to reproduce (to know how this issue impact your store)
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by Eva-F** [comment] 2021-02-02 15:11
Added into the first post

**Comment by hibatallahAouadni** [comment] 2021-02-03 18:50
Hello @Eva-F 

This issue has been fixed with PS1.7.7.0, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/106794347-01029100-6659-11eb-96ca-03829bd8532c.png)

![image](https://user-images.githubusercontent.com/23308427/106794363-06f87200-6659-11eb-8b30-4a0cd9e3634c.png)

This issue is a duplicate of #15228

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-03 18:51
Duplicate of #15228

**Closed as completed by hibatallahAouadni** 2021-02-03 18:50 UTC
Labels: Bug, CO, Duplicate, Order, Order statuses, 1.7.6.x

**Comment by Eva-F** [comment] 2021-02-03 19:14
ok, thx for info
