### ISSUE TITLE
Update product name in multishop

### ISSUE THREAD

**Issue by RosaBenouamer** [PrestaShop/PrestaShop#35126] opened 2024-01-22 15:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I update the name of a product.
The name is well updated in the product page but is uptaded nor in the list of products nor in the FO (but you can find it looking for it with the new name but is displayed with the old name)

### Expected behavior

The product name is updated

### Steps to reproduce
In a multistore shop (not tested in not multistore)
1 - Go in Catalog product
2 - Choose an existing product or a new product
3 - Edit the name of the product
4 - Check in the list of products (name not updated)
5 - open the product the name is updated
6 - Go in the FO Look for the product with the new name. The product is found with the old name displayed

### PrestaShop version(s) where the bug happened

8.1.3

**Comment by AureRita** [comment] 2024-01-22 15:56
Hi @RosaBenouamer 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(73).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/788f2bef-f550-48e7-bb14-9502d78fc921)

Did I miss something ? 
Did you clear you cache ? Did you disable the cache on the store ? 

Waiting for your feedback

**Comment by RosaBenouamer** [comment] 2024-01-23 15:58
Hello @AureRita !
It seems to be good on your store.
Thank you to try ! Indeed I have tried to clear the cache but not better. @MatShir reproduced the issue too but we don't know what are the exact configuration that implies the case. He is in a multistore like me. 
I have the issue on 8.1.3 and he has a shop upgraded from 8.1.2 to 8.1.3.

**Comment by florine2623** [comment] 2024-01-24 09:06
Hello @RosaBenouamer 
At what step do you upgrade your shop ?

**Comment by RosaBenouamer** [comment] 2024-01-24 09:38
@MatShir make the upgrade not me :-)

**Comment by florine2623** [comment] 2024-02-06 10:49
I can't reproduce the issue. So I'm closing it.

I upgraded from 1.7.8.11 to 8.1.3, I updated the name of the product on my store, I had no issues.

**Closed as completed by florine2623** 2024-02-06 10:49 UTC
Labels: Bug, BO, FO, 8.1.x, Products Page
