### ISSUE TITLE
Order of 2 product where one product have no carrier available for shipping

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#20615] opened 2020-08-17 18:12 UTC
#### Describe the bug

If a customer from USA order a product "A" that have no carrier configured to send in USA during the checkout, at step 3 will be warned with a prompt like "no carrier is presend for shipping".
All is fine, but if the customer add another product "B" that as a carrier able to ship it in USA, all the order composed by A and B will be finalized with a strange calculation (order A has a default shipment cost that not correspont to nothing calculable).

Prestashop will make 2 different order with same order ID but ask to pay a wrong value not the sum

![image](https://user-images.githubusercontent.com/16102074/90427874-725a8180-e0c3-11ea-8234-919c2c09ba33.png)

the underlined in red is the undeliverable product

#### Expected behavior

If in a cart there is a product that is not deliverable in a specific adress, the order cannot be completed till the product undeliverable is removed from cart!

#### Steps to Reproduce

Create 2 products with different curriers and ad to a specific zone to ship only one curier correpsonding to one object only:
For example a product deliverable everywhere in the world and another one product deliverable only in italy.

1) Try to purchase each one from USA and you will see that the product deliverable only in italy will block the checkout at step3

2) add now to the same order the other product and you will see that a curier will appear and allow you to complete the whole order of 2 product (one not deliverable too)

Calculation of what to pay is a rebus:

order 1 deliverable:
![image](https://user-images.githubusercontent.com/16102074/90428727-b69a5180-e0c4-11ea-9573-0c788e91397d.png)

Order 2 with product without curier covering that country (not deliverable):
![image](https://user-images.githubusercontent.com/16102074/90428857-e6e1f000-e0c4-11ea-9b11-8ec87083e4ef.png)

Customer has payed : 178.61€
I really don't uderstand what calculation it mades.

![image](https://user-images.githubusercontent.com/16102074/90434106-290f2f80-e0cd-11ea-98fc-304240ddf736.png)

Plus on the undeliverable order the carrier is unknow and the price was take from where??:
![image](https://user-images.githubusercontent.com/16102074/90428961-185abb80-e0c5-11ea-937b-d3151184f793.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by HartLarsson** [comment] 2020-08-17 19:38
i think i've  found the problem and a fix in cart.php

```
            // Foreach packages, get the carriers with best price, best position and best grade
            foreach ($packages as $id_package => $package) {
                // No carriers available
                if ( /*count($packages) == 1 &&*/ count($package['carrier_list']) == 1 && current($package['carrier_list']) == 0) {
                    $cache[$this->id] = array();

                    return $cache[$this->id];
                }
```

by removing :

`count($packages) == 1 &&`

now all products will be checked to have an available carrier.
The best things will be to have a error message that show witch products has no carrier for that address available.

I've temporary fixed with this error message:

![image](https://user-images.githubusercontent.com/16102074/90436999-e3089a80-e0d1-11ea-978c-2c0eb13a5bd3.png)

**Comment by khouloudbelguith** [comment] 2020-08-18 08:21
Hi @HartLarsson,

Your ticket is a duplicate of #15491
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-18 08:21
Duplicate of #15491

**Closed as completed by khouloudbelguith** 2020-08-18 08:21 UTC
Labels: Duplicate

**Comment by HartLarsson** [comment] 2020-08-18 09:21
> Hi @HartLarsson,
> 
> Your ticket is a duplicate of #15491
> So, I close it.
> Thanks!

my case is not covered by the ticket you suggested. Is not related to different payments is related to  undeliverability based on the same zone of one product while the other is deliverable anche the checkout must be blocked because if the core splits the order one will be without carrier and random shipping price.
I hope is more clear now..

**Comment by khouloudbelguith** [comment] 2020-08-18 10:46
@HartLarsson,

The FO issue is reported here: https://github.com/PrestaShop/PrestaShop/issues/9998#issue-353170013
The BO issue is reported here: https://github.com/PrestaShop/PrestaShop/issues/15304#issuecomment-526137500

All those issues are reported in this Epic: https://github.com/PrestaShop/PrestaShop/issues/15491

Thanks!

**Comment by ZingAsia** [comment] 2022-03-17 10:40
@HartLarsson 
Thank you for very much for this, have you got the code for the error message

> i think i've found the problem and a fix in cart.php
> 
> ```
>             // Foreach packages, get the carriers with best price, best position and best grade
>             foreach ($packages as $id_package => $package) {
>                 // No carriers available
>                 if ( /*count($packages) == 1 &&*/ count($package['carrier_list']) == 1 && current($package['carrier_list']) == 0) {
>                     $cache[$this->id] = array();
> 
>                     return $cache[$this->id];
>                 }
> ```
> 
> by removing :
> 
> `count($packages) == 1 &&`
> 
> now all products will be checked to have an available carrier. The best things will be to have a error message that show witch products has no carrier for that address available.
> 
> I've temporary fixed with this error message:
> 
> ![image](https://user-images.githubusercontent.com/16102074/90436999-e3089a80-e0d1-11ea-978c-2c0eb13a5bd3.png)

**Comment by HartLarsson** [comment] 2022-05-18 19:05
> @HartLarsson Thank you for very much for this, have you got the code for the error message
> 
> > i think i've found the problem and a fix in cart.php
> > ```
> >             // Foreach packages, get the carriers with best price, best position and best grade
> >             foreach ($packages as $id_package => $package) {
> >                 // No carriers available
> >                 if ( /*count($packages) == 1 &&*/ count($package['carrier_list']) == 1 && current($package['carrier_list']) == 0) {
> >                     $cache[$this->id] = array();
> > 
> >                     return $cache[$this->id];
> >                 }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > by removing :
> > `count($packages) == 1 &&`
> > now all products will be checked to have an available carrier. The best things will be to have a error message that show witch products has no carrier for that address available.
> > I've temporary fixed with this error message:
> > ![image](https://user-images.githubusercontent.com/16102074/90436999-e3089a80-e0d1-11ea-978c-2c0eb13a5bd3.png)

i simply add more text in the default message when is not possible to ship cause there is no courrier :)
