### ISSUE TITLE
Hook `actionProductInformationFormBuilderModifier` not triggered.

### ISSUE THREAD

**Issue by zubco** [PrestaShop/PrestaShop#23977] opened 2021-04-09 17:32 UTC
#### Describe the bug

Since 1.7.6 there is available this hook:
`action<FormName>FormBuilderModifier`
Located in: /src/Core/Form/IdentifiableObject/Builder/FormBuilder.php.
For **majority** of BO forms it **works correctly**. But for **Product** forms it **doesn't**.

#### Expected behavior

It should trigger the hooks for:
actionProductInformationFormBuilderModifier
actionProductQuantityFormBuilderModifier
... 

#### Steps to Reproduce

1. Create a module.
2. Inside install function, call: `$this->registerHook('actionProductQuantityFormBuilderModifier');`
3. Implement: `public function hookActionProductQuantityFormBuilderModifier($params) { ... }`
4. Expected this function to be called, but it's not.

#### Considerations

If it is not implemented yet, there should be a note about it in documentation.

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by sarahdib** [comment] 2021-04-12 11:57
Hello @zubco 

Could you send us a module in order to try to reproduce this issue ?

Thank you :)

**Comment by zubco** [comment] 2021-04-12 16:05
Hello @sarahdib,

[Here](https://github.com/PrestaShop/PrestaShop/files/6298071/aa_product_information_test.zip) you can find a zipped test module. 
With one example of a not triggered `actionProductInformationFormBuilderModifier` hook.
And a second example with `actionCategoryFormBuilderModifier` hook, that is not related to Product and works just fine.

**Comment by florine2623** [comment] 2021-04-23 12:33
Hello @zubco ,
I installed the module in my shop 1.7.7.2. Clicked Configure. I see no issues.

Can you let me know the extra step to see the issue ?

Thanks!

**Comment by zubco** [comment] 2021-04-23 12:52
@florine2623 This module is a playground to test the issue, but ofc it requires some technical understanding of PHP/PrestaShop.
For my purposes I used `trigger_error()`, present in both hooks but are commented there (and should be uncommented if you decide to use them).
As reference, for less technical ppl:
The  `actionProductInformationFormBuilderModifier` should be called when accessed in BO - Catalog - Products - Create/Edit a product.
The `actionCategoryFormBuilderModifier` should be called when accessed in BO - Catalog - Categories - Create/Edit a category.
Hope this helps, thanks !

**Comment by hibatallahAouadni** [comment] 2021-05-04 05:01
Hello @zubco 

Thanks for your patience :pray: 
i installed your module and configure it, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/116962509-6c82eb80-aca6-11eb-8289-febfc02dc893.png)

What I should do to encounter the issue?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-24 07:53
Hello @zubco ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-24 07:53 UTC
Labels: Bug, CO, No change required, Hook, 1.7.7.2

**Comment by LouisBertin** [comment] 2021-07-19 16:24
Hi @hibatallahAouadni,

Any update about this issue ? 

I've encountered the same problem with the `hookActionProductInformationFormBuilderModifier` whereas it works with the `hookActionCategoryFormBuilderModifier`.

@zubco gave us an example module to test this behavior.

> Hello @sarahdib,
> 
> [Here](https://github.com/PrestaShop/PrestaShop/files/6298071/aa_product_information_test.zip) you can find a zipped test module.
> With one example of a not triggered `actionProductInformationFormBuilderModifier` hook.
> And a second example with `actionCategoryFormBuilderModifier` hook, that is not related to Product and works just fine.

**Comment by intelsys** [comment] 2023-09-13 10:42
It happens to me the same with hookActionOrderMessageFormBuilderModifier

Prestashop version 8.0.4

This is not being triggered. Any new?
