### ISSUE TITLE
[BO] Unable to exit REARRANGE mode on catalog

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#29429] opened 2022-08-24 12:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After clicking on REARRANGE button on catalog page in the admin, we are not able to exit the rearrange mode so we can't use search filters

### Expected behavior

A button should allow us to exit the REARRANGE mode

### Steps to reproduce

1. Go to catalog page in the admin
2. Clic on filter by category > choose one category ( Home for ewemple)
3. Click on REARRANGE
4. Now we are stack in REARRANGE mode unless we change the order of products (the save button is disabled)

### PrestaShop version(s) where the bug happened

1.7.8.7 - 1.7.7.8 - 

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment] 2022-08-24 14:38
Hi @arirangz ,

I reproduce the issue with PrestaShop version1.7.7.8, I'll add this to the backlog so it can be fixed.we can see this issue on this video : 

https://user-images.githubusercontent.com/100699445/186446815-175f29bc-60e3-42d7-91c7-f359cbb066e6.mp4

You can go to the search bar if you select "unselect" on the category slider.
Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by MatShir** [comment] 2023-07-06 10:17
It should be fixed on 8.1 on the product page :)

**Comment by florine2623** [comment] 2023-07-12 15:15
@MatShir ,

The button Rearrange does not exist anymore on 8.1.0.
Should this be considered fixed ? 
<img width="1210" alt="Screenshot 2023-07-12 at 17 02 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ec06426a-4132-4119-ab32-2ff856cbf725">

**Comment by MatShir** [comment] 2023-07-17 15:35
Close in favor of https://github.com/PrestaShop/PrestaShop/issues/32833

**Closed as completed by MatShir** 2023-07-17 15:35 UTC
Labels: Bug, BO, Duplicate, Catalog, 1.7.7.8

**Comment by hibatallahAouadni** [comment] 2023-08-17 09:49
Duplicate of #32833
