### ISSUE TITLE
$urls.alternative_langs is unusable with 'language_code' as index when accessed with DOT syntaxe. (iso_code would be better)

### ISSUE THREAD

**Issue by moflihmorad** [PrestaShop/PrestaShop#24513] opened 2021-05-16 00:00 UTC
#### Describe the bug

the Global variable $urls.alternative_langs cannot be accessed with dot syntax using language code as index

#### Expected behavior

using $urls.alternative_langs.en-us should give access to language url 

#### Steps to Reproduce

classes/controller/FrontController.php

File:
`FrontController->getAlternativeLangsUrl(){
       foreach ($languages as $lang) {
            $alternativeLangs[$lang['language_code']] = $this->context->link->getLanguageLink($lang['id_lang']);
        }
}`

generates:
smarty {debug}
`$urls(array)
      alternative_langs => Array (2)
          en-us => "https://www.testhost.ma/en/"
          fr-fr => "https://www.testhost.ma/fr/"`

in Tpl file
 using  {$urls.alternative_langs.en-us} for href, returns 0

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.1.29

**Comment by hibatallahAouadni** [comment] 2021-05-17 10:23
Hello @moflihmorad 

Well, you need to use `{$urls.alternative_langs['en-us']}` to get the pageUrl :wink: 
So, I close this issue as it's not a bug.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-17 10:23 UTC
Labels: No change required

**Comment by moflihmorad** [comment] 2021-05-17 21:15
Hi @hibatallahAouadni, yes it works with `{$urls.alternative_langs['en-us']}` syntaxe, but what i was suggesting is 
being indexed with "iso_code" would be better since the hyphen breaks the dot syntaxe 
anyway i guess they have done it with the language_code because it sorts both language and country.
thank you @hibatallahAouadni.
