### ISSUE TITLE
Upgrading from 1.7.6.9 to 1.7.7.0 Error with 1- Click Update or Manually Method

### ISSUE THREAD

**Issue by cmauro** [PrestaShop/PrestaShop#22624] opened 2020-12-30 14:14 UTC
#### Describe the bug

I performed a copy of my production site and try to update it by 1-Click Update (latest version) and manually. In both cases i received the same error message. 

[INTERNAL] /vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 -
 Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\
 Configure\index" in file "/src/PrestaShopBundle/Controller/Admin/Configure/index.php" 
 while importing services from resource "/app/../src/PrestaShopBundle/Controller/*", 
 but it was not found! Check the namespace prefix used with the resource in /app/
 config/config.yml (which is being imported from "app/config/config_prod.yml"). 

It seems to try to find some classes in a directory that aren't exist. I don't know how to fix this, because I cannot see the Backoffice loging. 
After set debug to true, the Symfony shows the same message mention the autoloader. 

#### Expected behavior

A clen update of the site

#### Steps to Reproduce

1. Go to 1-Click Update
2. Click on Update latest version of Presta
3. Error Message

**Screenshots**
![upgrade_error_1769_to1770](https://user-images.githubusercontent.com/4930850/103356604-0421c480-4a90-11eb-9fde-d15658b6ac87.png)

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment] 2020-12-30 14:31
Hello @cmauro 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20332. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-30 14:31
Duplicate of #20332

**Closed as completed by hibatallahAouadni** 2020-12-30 14:31 UTC
Labels: Duplicate

**Comment by cmauro** [comment] 2020-12-30 14:40
@hibatallahAouadni thanks for your quick reply, I'll follow the issue that you mentioned. 
Thanks
