### ISSUE TITLE
for 1click upgrade from prestashop 1.6.1.24 to 1.7.6.2 error

### ISSUE THREAD

**Issue by froncare** [PrestaShop/PrestaShop#17037] opened 2020-01-06 17:03 UTC
I always get this error msg whenever i tried to upgrade my prestashop. what should i do...
"
[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:"Service Unavailable " jqXHR: "
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

"

**Comment by khouloudbelguith** [comment] 2020-01-07 07:47
Hi @froncare,

I did not manage to reproduce the issue with PS1.6.1.24 & the 1-click upgrade v4.10.0.
I attached a screen record
https://drive.google.com/file/d/17qxbSssHHQYOPtYbUmbSqSPfbOOYTamm/view
What is the exact version of the 1-click upgrade did you use?

Thanks!

**Comment by froncare** [comment] 2020-01-07 14:57
this screen is showing for my BO
[image: image.png]


Yaenee Ryu
46-01 Bell Blvd.
Bayside, N.Y. USA 11361
www.froncare.com
Phone#: (929) 800-1016



CONFIDENTIALITY NOTICE:
This message is for the named person's use only. This e-mail may have
information that is CONFIDENTIAL or legally privileged.  No confidentiality
or privilege is waived or lost by any mistransmission. If you receive this
message in error, please immediately delete it and all copies of it from
your system, destroy any hard copies of it and notify the sender at
Esther@froncare.com.  You must not, directly or indirectly, use, disclose,
distribute, print, or copy any part of this message if you are not the
intended recipient. Any views expressed in this message are those of the
individual sender, except where the message states otherwise and the sender
is authorized to state them to be the views of any such entity. Thank You.

**Comment by khouloudbelguith** [comment] 2020-01-07 15:04
@froncare, you need to sign in to GitHub & attach the screenshot here.
Thanks!

**Comment by froncare** [comment] 2020-01-07 15:07
![image](https://user-images.githubusercontent.com/59448179/71905064-6245f100-3135-11ea-90cd-f9536eaeecc1.png)
I'm currently stuck on this page

**Comment by khouloudbelguith** [comment] 2020-01-07 15:12
@froncare, you need to enable the PHP's zip extension on your server & disable your shop.
![image](https://user-images.githubusercontent.com/16067358/71905419-65a6a000-3168-11ea-89d9-e234febbff62.png)

Thanks!

**Comment by froncare** [comment] 2020-01-07 15:17
how can i enable the PHP's zip extension?

**Comment by khouloudbelguith** [comment] 2020-01-07 15:21
@froncare, Zip. The [Zip extension](https://www.php.net/manual/en/book.zip.php) is used to expand compressed files such as modules and localization packages.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-06 07:34
Hi @froncare, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-06 07:34 UTC
Labels: Bug, BO, Autoupgrade, No change required
