### ISSUE TITLE
BUG displaying "dni" field in address form which country has not dni field set

### ISSUE THREAD

**Issue by Liewebs** [PrestaShop/PrestaShop#30450] opened 2022-11-30 13:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have found a BUG testing Prestashop 8.0 version.  The BUG is in address form displaying "dni" field (Identification number) even when the country selected has not this field selected to display it.

![1](https://user-images.githubusercontent.com/14276490/204803220-e75007e4-9fbc-4c30-89a0-560de9aeda56.png)

![2](https://user-images.githubusercontent.com/14276490/204804255-8a89c746-5fc9-45cf-b682-e2bc1c1c179f.jpg)

![3](https://user-images.githubusercontent.com/14276490/204804268-b6c39d91-c8b2-4b59-921c-eb9499ddb50e.jpg)

![4](https://user-images.githubusercontent.com/14276490/204804288-e1e43d78-7514-48b4-8a52-4fbc1b8c54af.jpg)

This issue happens only when you save the address and go into same address to edit it (FO) and when you go into address edit in BO.

If you change the country in country select, the field will disappear, but once you save the address, and go into the address again to edit, the fiel will be displayed.

![5](https://user-images.githubusercontent.com/14276490/204804862-04f81d7d-8a9e-4a5a-aaed-63435df2ae95.jpg)

### Expected behavior

The "dni" field should not be displayed any way

### Steps to reproduce

1. Go to address form in FO
2. Save address
3. Go to same address form and will see the "dni" field.

### PrestaShop version(s) where the bug happened

1.8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2022-11-30 14:49
Hello @Liewebs 

Thanks for your report.
I tried to reproduce your issue on PS8.0.x, PS1787 and PS1778.
Here is the exact steps to reproduce : 

1. GO to FO > Add a product to cart 
2. In checkout process > Fill the Address fields 
3. See that the Identification number is not displayed
4. In BO > International > Locations > Countries > Edit `France` Country
5. See that the `Do you need a tax identification number` field is disabled
6. Select ADDRESS column > Check that `dni` is not displayed in the list of `Address format` table
7. Enable `Do you need a tax identification number` field and Save
8. See that the dni field is now displayed in the list of the `Address format` table
9. Come back to FO > Refresh the page of the Address > See that the Identification number is now displayed
10. In BO > International > Locations > Countries > Edit `France` Country > Disable again `Do you need a tax identification number` field
11. Click on Save
12. Check that the `dni` parameter does not disappear from the list of `Address format` table ==> This is the main issue !
13. Come back to FO and check the Address fields > see that the `Identification number `still dispalyed
14. When come back and delete manually the dni parameter from the list of table 
15. Check that the `Do you need a tax identification number` field is disabled
16. Come back to FO > refresh the page of Address > See now that the identification number is disappearing!


**PS8.0.x : NOK** :x: 

https://user-images.githubusercontent.com/92912932/204825831-193894fe-3072-445c-ae5c-00a9f2895094.mp4


**PS1.7.8.7 : NOK** :x: 


https://user-images.githubusercontent.com/92912932/204826521-92df0177-4e31-497f-a36f-e4fdd1d6f7b1.mp4


**PS1.7.7.8 : NOK** :x: 

https://user-images.githubusercontent.com/92912932/204827106-75813876-a062-4b3c-b4f0-f5dde44479a6.mp4


By the way, i found this [issue](https://github.com/PrestaShop/PrestaShop/issues/17647). Is it similar to yours? 

Thank You!

**Comment by Liewebs** [comment] 2022-12-01 09:44
Hi Hana,

Yes, the issue is the same. I did less tests than you but I found the same issue with "dni" field. I will continue testing..

**Comment by Liewebs** [comment] 2022-12-01 09:46
In next comment I will send a video showing the issue from my side and some details more to add to your testing videos. Thanks!

**Comment by AureRita** [comment] 2022-12-01 10:22
Hi @Liewebs 

Because this issue is thre same than another issue we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17647 .

To be informed when it's fixed, please subscribe to the issue mentioned above.

Maybe this [comment](https://github.com/PrestaShop/PrestaShop/issues/26843#issuecomment-1002697612) can help you 

Thank you

**Comment by AureRita** [comment] 2022-12-01 10:22
Duplicate of #17647

**Closed as completed by AureRita** 2022-12-01 10:22 UTC
Labels: Bug, BO, FO, Duplicate, Addresses, Countries, Invalid

**Comment by Liewebs** [comment] 2022-12-01 11:44
Ok, thanks for the comment. We will subscribe  to the first issue reported
