### ISSUE TITLE
Improvement - Error on activating products with multiples grouped selected products disapear and show success

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#16874] opened 2019-12-19 16:26 UTC
Tested in Version 1.7.5.1

The error while activate a lot of selected products disapear too fast + message of success still show success.

It's annoying to know which one has failed. I was needed to screen record to pause a video to know which product has failed to activate. 

The error are shown about half second and the window disapear.
![2019-12-19_11h22_05](https://user-images.githubusercontent.com/16780421/71190049-d8031f00-2251-11ea-8763-94612c4aed96.png)

After the Window disapear, the top message stil shown success.
![2019-12-19_11h23_38](https://user-images.githubusercontent.com/16780421/71190188-1a2c6080-2252-11ea-9706-9165c64be897.png)

[Solution 1]
If you can pause the process before the Window Hover disapear, it's really fast and not having time to note the Product ID.

[Solution 2] *Recommended*
Change the message on top with the error and which product ID has failed to activate;

To Reproduce:
- Edit an existing product;
- Add more texte of maximum character capacity (i don't know why i have some product has success before with more than 800 characters (the maximum i set)
- Select more than 2-3 products and choose "Grouped Actions > Activate Products";

Thanks.

**Comment by khouloudbelguith** [comment] 2019-12-19 17:06
Hi @8ternity,

>Add more texte of maximum character capacity (i don't know why i have some product has success before with more than 800 characters (the maximum i set)

I did not manage to reproduce the issue with PS1.7.6.2
![image](https://user-images.githubusercontent.com/16067358/71193216-08ff4600-228a-11ea-9015-e4cc50deefc9.png)

In the BO => Shop Parameters => Product Settings => we have an option to set "Max size of short description "
I tried with a lot of products & they are ok
https://drive.google.com/file/d/18YcSV4Ow5dOzU6hcbhqn4IRUxrpLDmvo/view

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-21 07:52
Hi @8ternity,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-21 07:52 UTC
Labels: Bug, BO, No change required, 1.7.5.1
