### ISSUE TITLE
PS 8.0.0.0 BO module statsstock error

### ISSUE THREAD

**Issue by PrestaVision** [PrestaShop/PrestaShop#30711] opened 2023-01-01 08:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

1. Migrate of data completed from PS 1.7.7.8 to fresh install of PS 8.0.0.0. 
2. In back office > statistics > module statsstock, entire shop content is displayed. 
3. ID's are correct, References are all empty, Item Descriptions are all correct, Quantities are all correct, 
3a. Price* some values are displaying €0,00, while the shopitem is priced correctly
3b. Value some values are displaying €0,00, while they have value set correctly.
4. total amounts at bottom of page give value, but this can't be correct total value IMHO.

![mod_statsstock](https://user-images.githubusercontent.com/119726053/210165227-970dab44-c524-4aa9-ace9-98b1bce3bba9.jpg)

### Expected behavior

Values in module should be mentioned as set in product values, not €0,00.

### Steps to reproduce

1. migrate PS 1.7.7.8 database to PS 8.0.0.0
2. in BO, go to Statistics > Available Quantities (module statsstock)
3. check columns for €0,00 values and correlate with values set in products themselves.
4. check and correlate total amounts on bottom of page (value being the most important).

### PrestaShop version(s) where the bug happened

8.0.0.0.

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

statsstock

**Comment by AureRita** [comment] 2023-01-03 14:37
Hi @PrestaVision 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by PrestaEdit** [comment] 2023-01-04 08:31
Hi @PrestaVision,

The amount show there is the wholesale price. It's this price setted into your catalog ?

**Comment by hibatallahAouadni** [comment] 2023-09-01 07:23
Hello @PrestaVision 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-01 07:23 UTC
Labels: Bug, BO, Stats, Database, Invalid, 8.0.0
