### ISSUE TITLE
Multi-store: productoutofstock email being sent to every employee of every shop

### ISSUE THREAD

**Issue by polevoyk** [PrestaShop/PrestaShop#22142] opened 2020-11-27 14:21 UTC
#### Describe the bug

When getting the productoutofstock for a product below the stock level, the email being sent to every employee configured for every shop. 

#### Expected behavior

Email should be sent only to employees of this product shop

#### Steps to Reproduce

Set multi-store
Set employees for every store
Set a stock alert below the current stock on the product page in the admin
Order the product
Check sent mails log\inbox of employees

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.1

**Comment by florine2623** [comment] 2020-11-27 15:30
Hi @polevoyk ,

I just want to make sure, did you do an upgrade from a previous PS version to PS 1.7.6.8 ?
If yes, can you specify which one ?

In PS 1.7.6, choosing which employee is related to which store is not possible.

Waiting for your answer,
Thanks!

**Comment by polevoyk** [comment] 2020-12-01 10:54
Hi @florine2623 ,
Yes, it was upgraded, but just from 1.7.6.6.
I already solve this bug and made pull request (https://github.com/PrestaShop/PrestaShop/pull/22166)
I hope i made it correct, because it was my first :)

There was no filtering of employees before send notice

**Comment by hibatallahAouadni** [comment] 2021-01-24 23:29
Hello @polevoyk 

Sorry for the late response. I tried to reproduce your issue following your steps and here's what I got:

1. Multistore enabled (store1: presta1771, store2: PrestaFast)
2. I created an employee for Store1 presta1771: a.hibatallah@gmail.com
3. I created an employee in Store2 PrestaFast: a.hibatallah@hotmail.com
4. PrestaFast: I set the product quantity to 0
5. I only receive the "out of stock" mail in my superAdmin mailbox and a.hibatallah@hotmail.com mailbox
6. I didn't receive any mail in a.hibatallah@gmail.com mailbox

Please check the screen record below and feedback:

https://drive.google.com/file/d/1CAWMoXjIXvnDyR3fdhmNPCmMLW8rdaLK/view

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-22 14:47
Hello @polevoyk ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-22 14:47 UTC
Labels: Bug, Multistore, Employees, No change required, 1.7.6.8, 1.7.7.1, ps_emailalerts
