### ISSUE TITLE
Bug fix with creating order slip

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#22903] opened 2021-01-19 20:11 UTC
#### Describe the bug

I created an order with tax rule 1 that had 19% tax. After that I changed the percentage of this rule by 10%. And made a return. The refund has already been made not in 19% percent, but in 10%

#### Steps to Reproduce

1. Set tax rule about product , shipping. Rule tax = 19%
2. Create order with this product, set this shipping with tax rule 19%
3. Change in Rule tax 19%, tax rate from 19% => 10%
4. Create order slip in the order what was created earlier

#### Additional information

* PrestaShop version: 1.7.4
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-20 12:11
Hello @dariusakafest 

I didn't managed to reproduce the issue with PS1.7.4.1 and PS1.7.7.0, see the attached screen record below:

**PS1.7.7.0:**

https://drive.google.com/file/d/15Tf7D7FX9F-gnRGk5rwn-EtlmfWi_b90/view

**PS1.7.4.1:**

![image](https://user-images.githubusercontent.com/23308427/105173177-f1dff700-5b20-11eb-9f5e-e7ef289e1bb1.png)

![image](https://user-images.githubusercontent.com/23308427/105173191-f6a4ab00-5b20-11eb-8626-689d447399a5.png)

Did you miss something in your steps to reproduce? :confused: 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-23 23:36
Hello ,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-23 23:36 UTC
Labels: Bug, BO, Order, Credit notes, Tax rules, No change required, 1.7.4.1, 1.7.7.0
