### ISSUE TITLE
Missing Alias CustomerQueryBuilder.php

### ISSUE THREAD

**Issue by BoutiquesInternet** [PrestaShop/PrestaShop#23394] opened 2021-02-24 16:31 UTC
#### Describe the bug

When you add a left join ps_employee in hookActionCustomerGridQueryBuilderModifier and you filter the customer table with the lastname column for example, symfony show this error 
`SQLSTATE[23000]: Integrity constraint violation: 1052 Champ: 'lastname' dans where clause est ambigu`
because ps_employee contain a lastname column too

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > with the `ps_qualityassurance` module
2. Register this hook `actionCustomerGridQueryBuilderModifier` 
3. Fill the content: 
```
$searchQueryBuilder = $params['search_query_builder'];

$searchQueryBuilder->addSelect(
  'employee.lastname as employee'
);

$searchQueryBuilder->leftJoin(
  'c',
  '`' . pSQL(_DB_PREFIX_) . 'employee`',
  'employee',
  'employee.`email` = c.`email`'
);
```
4. Click on **Register** button
5. **BO** > **SELL** > **Customers** > **Customers**
6. Enter a last name to search for a client and click on **Search** button
7. See error

**Screen record**

https://user-images.githubusercontent.com/23308427/148936907-1f98c272-2f3b-44ad-8431-b24279835ad9.mp4

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

I think to fix this, we have to add the alias "c" in CustomerQueryBuilder.php on line 229 like below 
`$qb->andWhere('c.`' . $filterName . '` LIKE :' . $filterName);`

**Comment by hibatallahAouadni** [comment] 2021-02-25 10:45
Hello @BoutiquesInternet 

Are you trying to create you own module? 
> Add a left join ps_employee in the $searchQueryBuilder in hookActionCustomerGridQueryBuilderModifier via custom Module

And could you please provide the whole SQL request that you create.

Thanks!

**Comment by atomiix** [comment] 2021-02-25 10:48
Hi @BoutiquesInternet, could you provide us a sample module to be able to reproduce your issue? Also, you seem to know how to fix it, don't hesitate to open a pull request!

**Comment by BoutiquesInternet** [comment] 2021-02-25 10:58
Hi,

I can show you the hook function in my custom module, see below.

```
public function hookActionCustomerGridQueryBuilderModifier(array $params)
    {
        /** @var QueryBuilder $searchQueryBuilder */
        $searchQueryBuilder = $params['search_query_builder'];

        $searchQueryBuilder->addSelect(
            'employee.lastname as employee'
        );

        if (!is_null($this->sellerProfile)) {

            $current_employee = $this->context->employee;

            if ($this->sellerProfile == $current_employee->id_profile) {
                $searchQueryBuilder = $params['search_query_builder'];
                $countQueryBuilder = $params['count_query_builder'];

                $searchQueryBuilder->innerJoin(
                    'c',
                    '`' . pSQL(_DB_PREFIX_) . 'bi_sellers`',
                    'bi_sellers',
                    'bi_sellers.`id_customer` = c.`id_customer` AND bi_sellers.`id_employee` = ' . $current_employee->id
                );

                // So the pagination and the number of customers
                // retrieved will be right.
                $countQueryBuilder
                    ->innerJoin(
                        'c',
                        '`' . pSQL(_DB_PREFIX_) . 'bi_sellers`',
                        'bi_sellers',
                        'bi_sellers.`id_customer` = c.`id_customer` AND bi_sellers.`id_employee` = ' . $current_employee->id
                    );
            } else {
                $searchQueryBuilder->leftJoin(
                    'c',
                    '`' . pSQL(_DB_PREFIX_) . 'bi_sellers`',
                    'bi_sellers',
                    'bi_sellers.`id_customer` = c.`id_customer`'
                );
            }
        }

        $searchQueryBuilder->leftJoin(
            'c',
            '`' . pSQL(_DB_PREFIX_) . 'employee`',
            'employee',
            'employee.`id_employee` = bi_sellers.`id_employee`'
        );
    }
```

**Comment by atomiix** [comment] 2021-02-26 10:15
@hibatallahAouadni with the [`ps_qualityassurance`](https://github.com/PrestaShop/ps_qualityassurance) module, you can add this:
```
$searchQueryBuilder = $params['search_query_builder'];

$searchQueryBuilder->addSelect(
  'employee.lastname as employee'
);

$searchQueryBuilder->leftJoin(
  'c',
  '`' . pSQL(_DB_PREFIX_) . 'employee`',
  'employee',
  'employee.`email` = c.`email`'
);
```
to the `actionCustomerGridQueryBuilderModifier` hook and then follow step 2 & 3, you should be able to reproduce the error.

**Comment by kpodemski** [comment] 2021-06-05 12:32
@hibatallahAouadni @BoutiquesInternet 

This problem has been fixed in the 1.7.8 version

**Comment by hibatallahAouadni** [comment] 2022-01-06 18:41
Ping @kpodemski is this issue duplicate of #27235 ?

**Comment by hibatallahAouadni** [comment] 2022-01-11 11:47
@kpodemski that's true :tada: the issue has been fixed with PS1782, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/148937142-5acfa563-d253-470e-9e3d-a002f45bea93.mp4

Closing the issue :wink: 
Thanks you!

**Closed as completed by hibatallahAouadni** 2022-01-11 11:47 UTC
Labels: Bug, CO, Modules, Fixed, Hook, 1.7.7.1
