### ISSUE TITLE
Bug with creating new product

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#19913] opened 2020-06-23 15:12 UTC
#### Describe the bug

When you are going to create a new product and leave the page, the record in the database is made. This create a new product which is available in FO bot not in the BO.

#### Steps to Reproduce

1. Go to Back office > Catalog > Product
2. Press New product button
3. Do not press or doing anything and then leave or close the page
4. Look into database. In the ps_product, ps_product_lang and ps_product_shop database tables  were ceated new entry with next ID.
5. This new database entry is not available in the product list in BO, but on FO appear as a new product.
6. See the video for better explanation - https://vimeo.com/431834620

Note: I forgot show in the video the product in the FO.

#### Additional information

* PrestaShop version: tested on 1.7.6.5 and also 1.7.7 beta 1
* PHP version: 7.2

**Comment by prestascott** [comment] 2020-06-24 14:11
Hi @Caleydon, thanks for your report!

I managed to reproduce the bug:
1. last product has id=28
2. click on new product, don't save
3. in database, new entry with id=29 exists

Here are some screenshots:
![image](https://user-images.githubusercontent.com/54888056/85572383-38c24880-b635-11ea-8f23-bb48cf326d0e.png)
![image](https://user-images.githubusercontent.com/54888056/85572429-42e44700-b635-11ea-99a8-9c7bce51adef.png)

@PrestaShop/prestashop-core-developers Have you heard about this product list problem?

**Comment by marionf** [comment] 2020-06-24 16:08
Duplicate of #9945

**Comment by marionf** [comment] 2020-06-24 16:08
Hello @Caleydon 

Your issue is a duplicate of #9945, please follow this issue :)

**Closed as completed by marionf** 2020-06-24 16:08 UTC
Labels: Bug, Major, BO, Duplicate, 1.7.7.0, 1.7.6.5
