### ISSUE TITLE
Tax rate in invoice wrong when combining taxes

### ISSUE THREAD

**Issue by Whip** [PrestaShop/PrestaShop#24174] opened 2021-04-23 05:33 UTC
I posted this on the forums first but didn't get any reply. I will explain my tax setup here. I have 2 taxes:

- CGST (6%)
- SGST (6%)

Then I created a tax rule called GST which contains both of the taxes above and mode set to Combine. So the customer should be charged 12% on the order.

Then I created an order, the calculations are all correct but in the invoice, the Tax Detail table shows 6% tax rate which should either be 12% or two entries of 6%.

Secondly - and this is not necessary but - it would be nice if tax names would be shown in the invoice.

**Screenshots**

![180](https://user-images.githubusercontent.com/11595460/115823046-4007dd80-a423-11eb-96b4-c90bd6cf959d.jpg)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by florine2623** [comment] 2021-04-23 09:32
Hello @Whip ,

I was able to reproduce the issue with PrestaShop version 1.7.7.3, so I can confirm that this behavior is indeed a bug.
![Capture d’écran 2021-04-23 à 11 30 33](https://user-images.githubusercontent.com/16019289/115851628-78111f80-a427-11eb-90e4-544221776a2d.png)


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-04-28 00:52
Hello @Whip 

I'm really sorry, but I didn't manage to reproduce your issue with PS1.7.6.7, PS1.7.7.0 and PS1.7.7.3 :confounded:  
Could you please check my screen record below and notify me if there's a missing steps:
### PS1.7.7.0:

https://drive.google.com/file/d/1fcg0Hc1EJCTk2-tw6AvFY8uxLRXA7UzB/view

### PS1.7.6.7: 

![image](https://user-images.githubusercontent.com/23308427/116329847-7e5b1f00-a7cc-11eb-9d26-7c3fd04a0d8b.png)

### PS1.7.7.3:

![image](https://user-images.githubusercontent.com/23308427/116329818-6c797c00-a7cc-11eb-8b20-7580807f3771.png)

_PS: I was checking if this issue is a regression or not than I notice that I can't reproduce with all these version mentioned above._

Please check and feedback.
Thanks!

**Comment by Whip** [comment] 2021-04-28 03:47
Hi @hibatallahAouadni , thanks for the extensive testing. I decided to upgrade my installation to 1.7.7.3 in case something fixes the problem but I still have the issue. Just to cover all bases, I've included the screenshots of the setup, maybe you'll spot something.

![tax-1](https://user-images.githubusercontent.com/11595460/116343541-3c4cd000-a802-11eb-99a6-53dd8a6162ec.jpg)
![tax-2](https://user-images.githubusercontent.com/11595460/116343554-42db4780-a802-11eb-8954-9b3922d4803c.jpg)
![tax-3](https://user-images.githubusercontent.com/11595460/116343560-48d12880-a802-11eb-9fb6-ead1e168d12c.jpg)

**Comment by hibatallahAouadni** [comment] 2021-04-28 13:34
Hello @Whip 

It seems all good!
Did you choose the GST tax in the product page? (see the attached screenshot below)

![image](https://user-images.githubusercontent.com/23308427/116412499-0a099580-a837-11eb-9496-8eea5a148437.png)

Please check and feedback.
Thanks!

**Comment by Whip** [comment] 2021-04-28 14:01
Yes. Did that too. It is afterall getting applied correctly in the calculations.

**Comment by hibatallahAouadni** [comment] 2021-04-28 14:47
Hello @Whip 

> Yes. Did that too. It is afterall getting applied correctly in the calculations.

So, your issue is fixed?
Please check and feedback.

Thanks!

**Comment by Whip** [comment] 2021-04-28 15:03
No. What I mean is that calculations are correct but tax is displayed 6%, not 12%.

**Comment by hibatallahAouadni** [comment] 2021-04-28 15:11
Hello @Whip 

Well, in my case I didn't manage to reproduce the issue as I mentioned above with PS1.7.6.7, PS1.7.7.0 and PS1.7.7.3
It could be the cause of your issue an override or third-party modules.
Please check and feedback.

Thanks!

**Comment by Whip** [comment] 2021-04-28 15:20
@florine2623 was also able to reproduce the issue. Maybe he would like to pitch in?

**Comment by hibatallahAouadni** [comment] 2021-04-29 08:15
Hello @Whip 

I just checked again with @florine2623 and it seems to be a mistake, see the attached screen record below:

![image](https://user-images.githubusercontent.com/23308427/116520854-8ea9f180-a8d3-11eb-9e83-c8e8d644b73f.png)

As you can see it seems that she mistook the tax (it's not combined) :wink: 
So, I close this issue as we were not able to reproduce your issue with the provided information.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-29 08:15 UTC
Labels: Bug, Order, Invoices, Tax rules, No change required, 1.7.7.3

**Comment by Whip** [comment] 2021-04-29 09:52
The image you posted shows the problem too. On a 100 euro product, the invoice says 6% tax and 12 euro in amount. 6% tax should be 6 euro.

**Comment by hibatallahAouadni** [comment] 2021-04-29 09:59
@florine2623 could you please share your steps to reproduce :wink:

**Comment by florine2623** [comment] 2021-04-29 14:25
@hibatallahAouadni @Whip ,

I tried to recreate the issue once more one a fresh install, but I couldn't.
I have the same result as @hibatallahAouadni 
Sorry @Whip

**Comment by hibatallahAouadni** [comment] 2021-04-29 14:26
Thanks @florine2623 for your feedback ☺️

**Comment by Whip** [comment] 2021-05-02 14:47
@hibatallahAouadni Sorry to bother you guys but can you tell me in which file does this calculation happen? I want to compare it with a fresh installation and see if something went wrong in the file during any of the upgrades I've done since I made this website.
