### ISSUE TITLE
Regression into product URL assign, for product list

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#14765] opened 2019-07-19 09:11 UTC
**Describe the bug**
Introduced here :
https://github.com/PrestaShop/PrestaShop/pull/13009/commits/48125d7707fec1e3ec55a91e8db56ac510efdb52

We cannot define a specific URL for the product anymore while using search engine or when splitting products by their attributes. The canonical URL is always used into the template ( cc @jolelievre )

**Additional information**
PrestaShop version: 1.7.6
PHP version: any

**Comment by khouloudbelguith** [comment] 2019-07-19 09:22
Ping @jolelievre what do you think?

Thanks!

**Comment by jolelievre** [comment] 2019-07-19 16:08
@prestamodule indeed this was introduced in 176 because previously on product with combinations the canonical url (without attribute) redirected to the default combination
this was bad practice for two main reasons:
- the canonical itself was not accessible and always returned a redirect response
- if the default combination changed then the redirection also changed so even the redirection was not very consistent

As for the listing it is better to use the canonical url so that you can have more backlinks to the canonical page But this canonical always displays the default combination by default
And even though the attribute urls are not used in listing any more they are still accessible (when you change an attribute the url is updated you can try to access them it will work) so any previous SEO ranking won't be lost but transferred to the canonical

**Comment by prestamodule** [comment] 2019-07-19 16:45
I understand the SEO improvements. But this is not what we are complaining about here :)
For example, in our search engine module, we are presenting products with the best possible combination. Meaning that we will display a dress as red if the color is available. We are also assigning the best combination URL, so the user will get to the product page with the same image, price, etc.
From this point of view, this is a big regression regarding UX ! 
We just want to bring back the possibility to force a specific product URL instead of the canonical one, when needed (search engine, faceting, splitting products by their attributes groups...), as it’s the case since PrestaShop 1.5+ 🤷🏻‍♂️

**Comment by prestamodule** [comment] 2019-08-01 10:58
any news regarding this issue ? @jolelievre ?

**Comment by jf-viguier** [comment] 2019-08-29 10:40
any news ?

**Comment by prestamodule** [comment] 2019-09-23 07:59
any news ?

**Comment by jolelievre** [comment] 2019-09-23 08:16
Hi @prestamodule, 
sorry for the delay in my response. Ok, I get what you mean with specific product url and I see how it can be troublesome for the user.

Do you suggest to never use the canonical url of the product in listing then? And instead always use `product.url` in the templates? I wonder if we should have a setting for this behaviour or if we can force it for everyone.

Either way I guess this won't have drawbacks on SEO since all the product combinations have the same canonical anyway.

@colinegin @marionf what do you think of reverting these modifications?
https://github.com/PrestaShop/PrestaShop/commit/48125d7707fec1e3ec55a91e8db56ac510efdb52#diff-f2a39218feae4cfb78f374d5c0909a9cR30

**Comment by matks** [comment] 2019-09-23 08:20
It seems we're going back-and-forth on these SEO topics 😐maybe we should stop forcing one behavior or another one, and provide options to choose the behavior ? Provide a small configuration panel in "Trafic & SEO" BO page to choose which url to use in the listing ?

**Comment by prestamodule** [comment] 2019-09-23 08:26
@matks @jolelievre That could be an option, but as it's a very little modification into the template, and really specific, i don't think that this is necessary (and also, users will have to wait for 1.7.7...).
We do not think that there will be impact on SEO as the canonical URL is already exposed when you are on the product page.

**Comment by jolelievre** [comment] 2019-09-23 09:24
As @prestamodule I don't think the impact will be huge on SEO, if it's just reverting the change I'm sure we can integrate it in 1762, however if this needs to be managed via a configuration this needs to be validated by the product team
Which is why I'd like an input from them @PrestaShop/prestashop-product-team :)
Also @colinegin maybe we should validate the SEO impact with our SEO consultant.

By the way @prestamodule could you detail a test scenario please, like which kind of product create and what kind of research perform so that the QA team can test and validate it?
Does this problem only occurs when researching with facetedsearch? or is it more generic?

Thank you

**Comment by xiaoyuan1998** [comment] 2019-09-24 12:09
i have same issue,  and +  the social network share the bad url without attribute
https://github.com/PrestaShop/PrestaShop/issues/15655


Thanks

**Comment by jf-viguier** [comment] 2019-10-15 10:43
What have you decided here ?

**Comment by xiaoyuan1998** [comment] 2019-10-15 12:53
Bonjour François,

J'ai acheté une moudule payant sur prestashop pour sauter ce pb.

Cdt,
Yuan

**Comment by jf-viguier** [comment] 2019-10-15 13:04
@xiaoyuan1998 ok, mais je posait la question à la team prestashop pour le core.
Il y a vraiement des modules pour tout !

**Comment by jf-viguier** [comment] 2019-10-15 13:09
@colinegin @jolelievre we just had a discussion with @prestamodule and we agreed that the best solution for now is to revert to this to avoid regression :
https://github.com/PrestaShop/PrestaShop/commit/48125d7707fec1e3ec55a91e8db56ac510efdb52#diff-f2a39218feae4cfb78f374d5c0909a9cR30

For me, there is no need for an extra parameter : the perfect solution is to have a product url without combinaison : it's already implemented in ps : just remove the default combinaison and you'll see.

**Comment by xiaoyuan1998** [comment] 2019-10-15 13:17
> @xiaoyuan1998 ok, mais je posait la question à la team prestashop pour le core.
> Il y a vraiement des modules pour tout !

I spent 90 euros for the addone  (pretty url):(   but at least it works

**Comment by colinegin** [comment] 2019-10-15 13:21
Hello @jf-viguier ,

sorry this issue is still in progress as we are currently discussing with @jolelievre and a SEO expert, to be sure we do not introduce any SEO regression, while taking into account prestamodule's problem. 
We will take a decision asap and keep you updated !

**Comment by matks** [comment] 2019-10-16 10:09
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15964

Thanks @prestamodule, @jf-viguier and @xiaoyuan1998 for helping us on this matter

**Closed as completed by matks** 2019-10-16 10:09 UTC
Labels: Bug, PM ✔️, SEO & URLs, Regression, Fixed, 1.7.6.0
