### ISSUE TITLE
weight attribute in combination should not be shop dependant

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#30837] opened 2023-01-12 14:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The weight attribute in Combination class (product_attribute* tables) is shop dependant ('shop' => true).
Two arguments to change this :
- the product weight attribute is not shop dependant 'shop' => false
- the combination weight calculation is based in product_attribute table, not in product_attribute_shop table.

For dev : 
- Read Combination class definition 
- Read sql for weight_attribute here: ('shop' => true)
https://github.com/PrestaShop/PrestaShop/blob/07603650b8437027b02d0df833e0ce0d23777faa/classes/Cart.php#L719

### Expected behavior

The combination weight attribute should be shop independant.

### Steps to reproduce

1. set a combination weight to 5 in a shop, 10 in another shop
2. Check weight in the two shops (by placing an order) : the weight is the same.

### PrestaShop version(s) where the bug happened

1.7, 8.0

### PHP version(s) where the bug happened

N/A

**Comment by sallemiines** [comment] 2023-01-13 14:04
Hello @jf-viguier 

Thanks for reporting the issue .

Following your steps , i didn't reproduce the issue , could you please  provide more infos, screenshots .. ? 

Please check and feedback ! 

Thank you !

**Comment by jf-viguier** [comment] 2023-01-16 12:23
@sallemiines please check first in db that you have different combination weight.

**Comment by AureRita** [comment] 2023-01-16 14:38
Hi @jf-viguier 

I reproduce this issue on 1.7.8.8 but not in 8.0.1 or on develop so it seems to be already in our backlog and it's already corrected. So I'll close this issue 

Thanks

**Closed as completed** 2023-01-16 14:39 UTC
Labels: Bug, BO, Combinations, Fixed, 1.7.8.0

**Comment by jf-viguier** [comment] 2023-01-16 15:54
@AureRita no, the weight is still shop dependant in 8 version.

**Comment by AureRita** [comment] 2023-01-16 16:26
that's what I get from 1.7.8.8 : 
![image](https://user-images.githubusercontent.com/100699445/212725069-a620f08c-e5b3-450c-96f3-c475d896c9ef.png)

(it's 30 kg in case of) 

And that's what I get on 8.0.1 : 
![image](https://user-images.githubusercontent.com/100699445/212725546-1eaf2fb2-1531-46bb-a131-a085e580a657.png)

it's seems to be corrected

**Comment by jf-viguier** [comment] 2023-01-16 16:40
Your test indicate that prestashop now use the first one but the weight should not be sop dependant in the code: 
https://github.com/PrestaShop/PrestaShop/blob/d9c905f4a4793cf04b4a911678a936f48e66b23c/classes/Combination.php#L104
