### ISSUE TITLE
faceted search 1.7.3 attribute limit not working

### ISSUE THREAD

**Issue by Jacquelin130** [PrestaShop/PrestaShop#10500] opened 2018-09-19 15:23 UTC
Install last fresh version of prestashop 1.7.3. Use faceted search module, setup with type checkbox  or type select  wiht limit (eg: 5 or 10)

On the front end the limit on attributes is ignored, so if you have eg: 30 attributes on checkbox, you have very long list of 30 choices. the list is not limited to first 5 or 10 as you've chosen on the module's configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/43415258/45763238-5d071f00-bc30-11e8-8d26-880734ecb415.png)

**Additionnal information**
PrestaShop version: 1.7.3.3

**Comment by khouloudbelguith** [comment] 2018-09-19 15:32
Hi @Jacquelin130,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9992
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-19 15:33
Duplicate of #9992

**Closed as completed by khouloudbelguith** 2018-09-19 15:33 UTC
Labels: Duplicate

**Comment by petterenge** [comment] 2019-03-19 00:03
Any idea when this will be fixed ?  Its still not working in version 1.7.4.3
The problem is very annoying when you have a large line of attributes like in clothing sizes.
The product list looks very bad and unprofessional with a list of more than 30 selections on the i.e size attribute.

Petter

**Comment by khouloudbelguith** [comment] 2019-03-19 08:05
Hi @petterenge,

We are currently working on a big refactoring of the ps_facetedsearch module.
It will be available soon.
Thanks for your understanding!

**Comment by amaxtrading** [comment] 2020-04-08 19:59
Hi @khouloudbelguith 
It's now over year but still nothing!?
I use 1.7.6.4 and facing with same problem!

BR W

**Comment by khouloudbelguith** [comment] 2020-04-09 07:35
Hi @amaxtrading,

We made a huge refactoring of the `ps_facetedsearch,` the last release is 3.5.0.
https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.5.0

Thanks!
