### ISSUE TITLE
2nd level subcategory not expanding correctly when creating new store

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#11610] opened 2018-12-04 13:29 UTC
When creating a new store, 2nd level subcategories do not display correctly when expanding. Please see screenshot below. Although this may seem trivial, when the store is created those 2nd level subcategories are not imported correctly and are not associated with any products that were imported from one shop to another. (2nd level subcategories refer to a subcategory of subcategory which in this case is men and women under clothing).

A quick fix would be to uncheck all and then pressing the expand/collapse several times until it eventually expands. Please see second screenshot below. Only then can we check all so that the categories import correctly. 

![image](https://user-images.githubusercontent.com/26452178/49444421-93444b80-f7e8-11e8-9101-85906aeadf9a.png)

![image](https://user-images.githubusercontent.com/26452178/49444774-9a1f8e00-f7e9-11e8-9d93-3bff834ec32e.png)

**Additional information**
PrestaShop version: 1.7.4.4 and 1.7.5

**Comment by khouloudbelguith** [comment] 2018-12-04 13:35
Hi @nrcjea001 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9701
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-04 13:35
Duplicate of #9701

**Closed as completed by khouloudbelguith** 2018-12-04 13:35 UTC
Labels: Duplicate
