### ISSUE TITLE
Multistore - all prices updated in view "all shops"

### ISSUE THREAD

**Issue by agnesdennetiere** [PrestaShop/PrestaShop#14081] opened 2019-06-05 09:50 UTC
Hello,

the bug described there http://forge.prestashop.com/browse/PSCSX-8758 is still on Prestashop 1.7.5.2, this correction https://github.com/PrestaShop/PrestaShop/commit/c224384c524a5a995804252cf62d035abea1a9a9 has not been made on 1.7

**Comment by agnesdennetiere** [comment] 2019-06-05 10:30
In fact, this solution does not seem to work with 1.7...

**Comment by mariem-abid** [comment] 2019-06-07 14:25
Hi @agnesdennetiere,

I did not manage to reproduce the issue with PS:1.7.5.2
I attached a video record.
https://drive.google.com/file/d/12TA7KCuvr6N4CPXvDT-PHDqji1POVg6S/view
Thanks for check and feedback.

**Comment by agnesdennetiere** [comment] 2019-06-11 08:39
Hello,

In your example, the price is the same (29) in both shops? At 1:08 you change the shop in the backoffice to go to the "prestashop" shop but it is still 29€, I do not understand.
Could you try with a different price (without tax)?

**Comment by khouloudbelguith** [comment] 2019-06-12 11:17
Hi @agnesdennetiere,

We are aware of this issue.
Your ticket is a duplicate of #9833
Please follow #9833
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-12 11:17
Duplicate of #9833

**Closed as completed by khouloudbelguith** 2019-06-12 11:17 UTC
Labels: Duplicate, Multistore, Currencies
