### ISSUE TITLE
Prestashop 1.7.7.4 - Stripe Refunds not working using Standard Refund or Partial Refund Buttons + array of workaround issues

### ISSUE THREAD

**Issue by i-pity-the-fool** [PrestaShop/PrestaShop#24939] opened 2021-06-12 23:26 UTC
#### Describe the bug

Refunds processes and journeys contain a multitude of issues when we are using Stripe, however majority of the issues would appear to be Prestashop side rather than stripe.

1) Within an order, we have 2 buttons, Standard Refund and Partial Refund. When these buttons are used, nothing happens on stripe at all. This is very misleading as the records that are written show that a refund has been processed on Prestashop back end when this hasnt happened. This could lead to complaints as we expect Prestashop has issue an appropriate message to stripe to perform an appropriate transaction when it has not.
2) When using the Stripe module to process a refund, it cancels the order. This would be fine if we have issued a full refund, but in the case where customer only wants a partial refund because they only want to cancel a single item for example, a cancellation transaction is not appropriate and neither is the cancellation email that is issued to the customer.
3) When i process a refund either full or partial from stripe itself, the order is cancelled. Per point 2, this is presumptuous, particularly in the case of a partial refund. If entire amount is refunded then i could see merit in this feature but as it stands it doesnt work. In addition when a refund is processed directly on stripe itself, only a Cancelled Transaction is written. We do not get a 'Stripe Partial Refund' transaction or a 'Refunded' transaction. Interesting i spotted we dont have a 'Stripe Full Refund' transaction status. Maybe that is needed moving forward too.
4) When dealing with refunds from anywhere, we should be sending customers a refund email. Although i have seen a refund email, i am unsure of the logic that generates it. I think potentially it gets generated when a status of 'Refunded' or 'Stripe Partial Refund' is written to the order, but as i have called out, there are a multitude of scenarios where this type of status does not get written as follows:
   - Using 'Standard Refund' or 'Partial Refund' buttons
   - Using Stripe website to process the refund. It only writes a cancellation transaction back to the order.

#### Expected behavior

In the same way that when a customer makes a payment for an order using prestashop and this payment is written to stripe, i expect when i process a refund via the partial or standard refund buttons that this refund request is processed through stripe. I expect an appropriate and corresponding transaction to be written to the order itself and i expect an appropriate email to be issued to my customer.

#### Steps to Reproduce

1. Install Prestashop 1.7.7.4 and upload a product which can be purchased
2. Add Stripe module v2.3.1
3. Configure stripe module using test API credentials
4. Buy a product using prestashop. We can observe successful and corresponding stripe transaction and order generation within
    prestashop -> Orders.
5. If we then hit either PARTIAL REFUND or STANDARD REFUND within the order just submitted, and then SUBMIT that refund. The amount on the order screen shows refund and my customer receives a credit note confirmation, however NO REFUND HAS BEEN ISSUED BY STRIPE. 

I have 2 viable options to return money to my customers

A Processing refund via stripe module
---------------------------------------
When I key a full or partial refund, the transaction does successfully pass to stripe and a corresponding refund entry is written to the corresponding order on prestashop and the status is changed to CANCELLED automatically, HOWEVER

My order is cancelled now. This is fine if it were only 1 product but in the case where i have issued only a partial refund as the customer only wants to return 1 item out of say more than 1 item, the entire order is showing as cancelled. My customer receives an email confirming the order is cancelled. The orders page is showing as cancelled. 

I believe the correct behaviour should be.

If order contains 1 or more items and a Full Refund is processed on Stripe Module, a) write a full refund transaction on the orders page, b) Cancel the order, c) Email customer advising order has been cancelled d) Email customer advising order has been refunded (Doesnt happen).

If order contains 1 or more items and a Partial Refund is processed on Stripe Module,  a) write a partial refund transaction on the orders page, b) email customer to advise a partial refund has been processed (Doesnt happen). DO NOT as is currently the case a) Cancel the order b) Email customer advising order has been cancelled.

B Processing refund directly from Stripe
---------------------------------------

I have processed a full and a partial refund using the refund facility on stripe itself. It results also in the order being cancelled and an email to the customer advising the order has been cancelled so behaviour is consistent with scenario A outlined above using the stripe Module HOWEVER there is one added problem. If processing the refund directly via the Stripe system, no transaction is written to prestashop other than cancelled. This proves a transaction can be written but we do not see a full or a partial stripe refund transaction being shown.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.2.7
* Classic Theme

**Comment by hibatallahAouadni** [comment] 2021-06-14 08:54
Hello @i-pity-the-fool 

> however majority of the issues would appear to be Prestashop side rather than stripe.

What makes you sure about the issues are from PS side and not the module?
Did you try to disable the module and then reproduce the issue?
Did you contact the module developer?
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment] 2021-06-14 10:32
Could be related to missing data in 1.7.7. It will be fixed in 1.7.8 by this PR https://github.com/PrestaShop/PrestaShop/pull/22686, but modules must adapt.

**Comment by hibatallahAouadni** [comment] 2021-06-14 10:49
Thanks @Hlavtox :wink:

**Comment by i-pity-the-fool** [comment] 2021-06-16 23:35
No response from module developers. I have installed PS 1.7.6.9 with the same module and received the same behaviour. I am unable to say confidently whether this is a PS or a module issue as i have only recently started working with PS and cannot say whether this refund functionality ever worked.

I just realised i have a screen in advanced -> order Settings -> Status where i can disable emails to customers when a cancellation transaction is written so this makes the matter less customer visible which is good, but id like to find a way to force subsequent transactions written AFTER a stripe refunds to result in a new status transaction i would create to be written instead of the cancellation transaction. This would mean i can revert to using the cancellation transaction for its intended purpose.

**Comment by hibatallahAouadni** [comment] 2021-06-17 08:00
Hello @i-pity-the-fool 

I didn't manage to reproduce your issue with PS1.7.7.4, see the attached screen record below:

https://drive.google.com/file/d/1z8fE5hhzp-g_2-qPHd8O5E197-299e9G/view

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem. We will close this issue.

PS: you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack), may be some contributors encounter your issue and can help you to solve it :slightly_smiling_face: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-17 08:00 UTC
Labels: Bug, BO, Order, Modules, Credit notes, No change required, 1.7.7.4
