### ISSUE TITLE
Can't reorder product in product list

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#26046] opened 2021-10-01 10:52 UTC
#### Describe the bug

I can't reorder the products in the product list. Sometimes it works, sometimes not. I just notice that when it works, the inputs are well checked. When it doesn't work, the inputs don't get checked.

#### Expected behavior

Inputs must be checked and it must be possible to reorder the products. I have to refresh the page several times to be able to reorder products

#### Steps to Reproduce

1. Go to 'Catalog > Product'
2. Choose a category
3. Click on 'Reorder'
4. Reorder product
5. Save
6. See error

Sorry, the problem looks random and I don't know the method to reproduce it every time

**Screenshots**

When it doesn't work:
![reorder-product-ko](https://user-images.githubusercontent.com/76649472/135607213-650d08f7-24f2-4109-8c28-1890fdd7f5f3.gif)

When it works (after several refreshes and tests):
![reorder-product-ok](https://user-images.githubusercontent.com/76649472/135608295-de839324-f910-4b0e-a513-1c3a61c5f453.gif)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.29

**Comment by khouloudbelguith** [comment] 2021-10-01 11:19
Hi @d33x,

Thanks for your report.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15291
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-10-01 11:19
Duplicate of #15291

**Closed as completed by khouloudbelguith** 2021-10-01 11:19 UTC
Labels: Duplicate
