### ISSUE TITLE
Integrated Import do not import

### ISSUE THREAD

**Issue by cyjo5** [PrestaShop/PrestaShop#12224] opened 2019-01-19 06:28 UTC
Hi
after reinstalling the shop (and changing from 1.7.2.2 to 1.7.5) the last step was to import my product data into the new shop. i go to installation an made the settings: import article, choose file, set seperators, and made the field combinations. Everything looks good. But after pressing import, nothing else happened.

PS 1.7.5
PHP 7.2
MySQL 5.5

Kind regards
Frank

**Comment by khouloudbelguith** [comment] 2019-01-21 07:53
Hi @cyjo5,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1OLDWC7VpRsuxOBywe7CUU00GjFuc0AXj/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-20 11:54
Hi @cyjo5,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-20 11:54 UTC
Labels: BO, Import / Export, No change required, 1.7.5.0
