### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by harryajc** [PrestaShop/PrestaShop#25076] opened 2021-06-22 09:55 UTC
#### Is your feature request related to a problem?

To save space allow pictures used within one item to be reused without having to reupload the same image multiple times.

#### Describe the solution you'd like

A media section within the admin dashboard that allows a admin to see all images uploaded to the platform.

These can then be selected within the product pages rather than reuploading to each product.

**Comment by florine2623** [comment] 2021-06-22 10:13
Hello @Goldshop ,

Your improvement request is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12773
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-12 08:26
Hello @Goldshop 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12773. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-12 08:26
Duplicate of #12773

**Closed as completed by hibatallahAouadni** 2021-07-12 08:26 UTC
Labels: Improvement, BO, Duplicate, Image
