### ISSUE TITLE
BO: Product form is slow when having a lot of categories (2000+)

### ISSUE THREAD

**Issue by djbuch** [PrestaShop/PrestaShop#25409] opened 2021-07-23 00:24 UTC
#### Describe the bug

When having a shop with a lot of categories, the loading of the product form is very slow (4-5sec).

#### Expected behavior

It should be much more quick, max 2 sec

#### Steps to Reproduce

Create a shop with 2000+ categories, and try to load product form in BO.

I investigated a bit, and it seems it is the twig rendering of the category form elements that slows the whole down...

It is confirmed by another user in this topic : https://www.prestashop.com/forums/topic/596141-very-slow-page-when-i-click-edit-product-option-prestashop-1705/

**Screenshots**

None

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by florine2623** [comment] 2021-07-23 07:30
Hello @djbuch ,

Your issue seems to be a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/19281
Can you check and confirm please ?

Thanks!

**Comment by djbuch** [comment] 2021-07-23 07:52
Hi,

yes I thinks these issues are linked. But it seems that it is not a javascript problem, but a TWIG rendering problem.

Regards

**Comment by florine2623** [comment] 2021-07-27 08:31
Hello @djbuch ,

Thanks for confirming.
It is better if you could follow the thread directly #19281. If you have anything to add, please do so in the original issue.

I'll close this one as it is a duplicate.
Thanks !

**Comment by florine2623** [comment] 2021-07-27 08:31
Duplicate of #19281

**Closed as completed by florine2623** 2021-07-27 08:31 UTC
Labels: Bug, BO, Duplicate, Categories, 1.7.6.8
