### ISSUE TITLE
1.7.4.4 to 1.7.5.0 with Product combinations not loading

### ISSUE THREAD

**Issue by jimmybsilva** [PrestaShop/PrestaShop#11825] opened 2018-12-18 20:18 UTC
When I go to a product that I created on 1.7.4.4 in the admin area under products ->  combination tab it does not load the combinations products.  When I try to regenerate the combinations it says "error updating product"

PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-12-19 08:22
Hi @jimmybsilva,

Thanks for your report.
I did not manage to reproduce the issue with the 1-click upgrade v4.5.1 from PS1.7.4.4 to PS1.7.5.0.
Did you have any errors during the upgrade?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by jimmybsilva** [comment] 2018-12-19 21:20
When you go a business profile and you click on the companies link it takes you to an error page

Example 
https://420nurses.com/businesses/420nurses-las-vegas-highrollers-chapter/

![image](https://user-images.githubusercontent.com/35279981/50248693-ba764d80-0390-11e9-9789-b39a8026593e.png)

you click on 
![image](https://user-images.githubusercontent.com/35279981/50248706-c95d0000-0390-11e9-8285-46ad6c140791.png)

It takes you to a page can not be found

**Comment by khouloudbelguith** [comment] 2018-12-20 08:25
@jimmybsilva, did you delete your last comment?
Thanks!

**Comment by slupostrupek** [comment] 2018-12-22 00:13
i had same issue. After few minutes its gone. 

 In my prestashop logs there is information about clearing cache by command line.

```
console.ERROR: Error thrown while running command "doctrine:cache:clear-metadata --flush=1". Message: "Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI." {"exception":"[object] (LogicException(code: 0): Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI. at /var/www/web/prestashop/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php:89)","command":"doctrine:cache:clear-metadata --flush=1","message":"Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI."} []
console.DEBUG: Command "doctrine:cache:clear-metadata --flush=1" exited with code "1" {"command":"doctrine:cache:clear-metadata --flush=1","code":1} []

console.ERROR: Error thrown while running command "doctrine:cache:clear-query --flush=1". Message: "Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI." {"exception":"[object] (LogicException(code: 0): Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI. at var/www/prestashop/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php:89)","command":"doctrine:cache:clear-query --flush=1","message":"Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI."} []
 console.DEBUG: Command "doctrine:cache:clear-query --flush=1" exited with code "1" {"command":"doctrine:cache:clear-query --flush=1","code":1} []
```

**Comment by khouloudbelguith** [comment] 2018-12-24 09:21
Hi @slupostrupek,

Thanks for your comment.
So the issue is fixed in your case?
Did you clear cache from your shop & your browser?
Thanks!

**Comment by popovoleksandr** [comment] 2018-12-25 08:34
Also reporting this issue - I'm not able to see combitations in Combinations tab and also to save new product with combination after I've added combitation supplier price... @khouloudbelguith any solution for this issue?

**Comment by popovoleksandr** [comment] 2018-12-25 08:38
I'm getting 400 error saving new product with combinations: 
admin*****/index.php/sell/catalog/products/62?_token=xhl7VpSC2XZDItdyOWDEuX_hR0dYLQjZNKRxIe4fnM8#tab-step6

**Comment by khouloudbelguith** [comment] 2018-12-25 08:39
Hi @anantaramdas,

I did not manage to reproduce the issue after upgrade from PS1.6.1.23 to PS1.7.5.0 & after an upgrade from PS1.7.4.4 to PS1.7.5.0.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by popovoleksandr** [comment] 2018-12-25 09:06
Followin exception I got by enabling debug mode:

Symfony\Component\Debug\Exception\ContextErrorException:
Notice: Undefined offset: 0

  at src/Adapter/CombinationDataProvider.php:123
  at PrestaShop\PrestaShop\Adapter\CombinationDataProvider->completeCombination(array(), object(Product))
     (src/Adapter/CombinationDataProvider.php:108)
  at PrestaShop\PrestaShop\Adapter\CombinationDataProvider->getFormCombinations(array(':numbers'), 2)
     (src/PrestaShopBundle/Controller/Admin/CombinationController.php:45)
  at PrestaShopBundle\Controller\Admin\CombinationController->generateCombinationFormAction(array(':numbers'))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin12765zh1b/index.php:88)

**Comment by popovoleksandr** [comment] 2018-12-25 09:08
In following line:
![image](https://user-images.githubusercontent.com/7561827/50418681-6d352880-0835-11e9-806d-6ac3d8421562.png)

**Comment by khouloudbelguith** [comment] 2018-12-25 09:30
Hi @anantaramdas,

Did you use a multishop context?
What is the exact PHP version did you use?
THanks!

**Comment by popovoleksandr** [comment] 2018-12-25 09:36
No I do not use multishop and my php is 7.2.10

**Comment by khouloudbelguith** [comment] 2018-12-25 10:14
Hi @anantaramdas,

Despite our several trials, I could not reproduce your issue with the provided information.
We are the Holidays season, our developers are not here right now.
I will assign your issue to our developer to reproduce the issue.
Thanks for your patience & your understanding!
@marionf what do you think? could you please try to reproduce the issue?
Thanks!

**Comment by popovoleksandr** [comment] 2018-12-25 10:33
@khouloudbelguith Do you have any tool to export all data and import it on new installation? I'm not able to add any product now :(

**Comment by khouloudbelguith** [comment] 2018-12-25 11:17
@anantaramdas,

In your file Projet_folder/src/Adapter/CombinationDataProvider.php line 123, could you please add this code line ( to debug your issue, you need to delete it after checking)
```
print_r($attributesCombinations[0]);
exit;
```
![image](https://user-images.githubusercontent.com/16067358/50421372-e5ecb280-083e-11e9-9aee-66ed6d8085ce.png)
and provide the exact result when you edit your product with combinations
![image](https://user-images.githubusercontent.com/16067358/50421387-01f05400-083f-11e9-93db-6ddd258017a8.png)

Thanks!

**Comment by popovoleksandr** [comment] 2018-12-25 11:21
:) That is obvious however:
![image](https://user-images.githubusercontent.com/7561827/50421438-05d4a400-0848-11e9-90e0-d3527d4984d8.png)

**Comment by khouloudbelguith** [comment] 2018-12-25 11:27
@anantaramdas, thanks to try with this
 ```
print_r($attributesCombinations);
exit;
```
![image](https://user-images.githubusercontent.com/16067358/50421494-5f38d500-0840-11e9-8d71-1903dedf243a.png)
Thanks!

**Comment by popovoleksandr** [comment] 2018-12-25 11:30
Already tried = it is empty arrays - i.e. array():
![image](https://user-images.githubusercontent.com/7561827/50421551-45e85680-0849-11e9-89c5-113109cf8ed7.png)

**Comment by popovoleksandr** [comment] 2018-12-25 12:32
@khouloudbelguith I have prepeared initial creencast to reproduce this issue on my installation. Hope it will help resolve the issue:
![presta_combinations_issue](https://user-images.githubusercontent.com/7561827/50422282-f5292b80-0851-11e9-89e2-e5bc80f5552c.gif)

**Comment by khouloudbelguith** [comment] 2018-12-25 13:15
@anantaramdas, Can you check if there is already a 'prod' folder in var/cache, and remove it manually in order to reset the permissions?
Thanks!

**Comment by popovoleksandr** [comment] 2018-12-25 13:21
What I can see there is:
![image](https://user-images.githubusercontent.com/7561827/50423031-9915d580-0858-11e9-8804-a52dbdb17690.png)

I removed both (dev and prod) and dev folder recreated after relogin to admin panel. Is this expected behavior?

**Comment by khouloudbelguith** [comment] 2018-12-25 13:22
@anantaramdas, yes, it is normal behavior.
Thanks!

**Comment by popovoleksandr** [comment] 2018-12-25 13:23
Forgot to say - issue still there...

**Comment by khouloudbelguith** [comment] 2018-12-25 16:02
@anantaramdas, It could be like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.

Can you please check if you have missing columns on your database schema.
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/upgrade/sql/1.7.5.0.sql

You can find the full schema for 1.7.5.0 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/data/db_structure.sql

Thanks!

**Comment by popovoleksandr** [comment] 2018-12-26 04:42
I checked https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/upgrade/sql/1.7.5.0.sql and found 2 syntax errors:
![image](https://user-images.githubusercontent.com/7561827/50432268-56e0a880-08d9-11e9-980a-d5fc3f49d3b1.png)

![image](https://user-images.githubusercontent.com/7561827/50432273-5b0cc600-08d9-11e9-8b35-2e9b1d8306d0.png)

**Comment by popovoleksandr** [comment] 2018-12-26 04:46
After correcting them and reapplying to database all went back normal. Any Christmas candies for finding bugs? 😄

**Comment by khouloudbelguith** [comment] 2018-12-26 08:09
Hi @jimmybsilva,

I m glad to solve the issue.
In fact, we manage to reproduce three warnings during the upgrade, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11814 to solve the issue.
Thanks to check this fix & apply changes on your Database.
Thanks!

**Closed as completed** 2018-12-26 09:28 UTC
Labels: Bug, Minor, BO, Can't reproduce, Autoupgrade, Combinations, 1.7.5.0

**Comment by popovoleksandr** [comment] 2018-12-26 20:29
Still you did not applied fix on your code in github... why?

**Comment by popovoleksandr** [comment] 2018-12-27 04:20
@jimmybsilva @marionf ?

**Comment by all-sd** [comment] 2019-01-10 20:15
This problem seams to happen only in Apple Safari and not with Chrome on Mac

**Comment by khouloudbelguith** [comment] 2019-01-11 08:26
Hi @ossd,

I tried with PS1.7.5.0 after upgrade from PS1.7.4.4 & all the combinations are displayed.
I'm using Operating system `Apple` os_version=`Mojave` & browser=`Safari` & browser_version=`12.0`.
![image](https://user-images.githubusercontent.com/16067358/51021857-fca34100-1582-11e9-9d65-15c7660453db.png)
Thanks!

**Comment by all-sd** [comment] 2019-01-18 07:40
Ok, true. An other mac don't have this problem. Sorry.

**Comment by khouloudbelguith** [comment] 2019-01-18 07:42
Hi @ossd,

Ok, thanks for your feedback!

**Comment by bartes1987** [comment] 2019-01-22 07:15
I'm not sure if I understand correctly. What steps do I have to take to solve the problem?

**Comment by khouloudbelguith** [comment] 2019-01-22 07:59
Hi @bartes1987,

As described by @anantaramdas, you need to update your database
1- table `PREFIX_product`, change the `reference` & supplier_reference from `varchar(32)` to `varchar(62) `
2- table `PREFIX_supply_order_receipt_history`, chnage the `employee_firstname` & `employee_lastname` from varchar(32) to varchar(255).
PS: PREFIX is the prefix of your tables, it could be for example ps.
For more details, you can follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/12062#issuecomment-452269373) & this [one](https://github.com/PrestaShop/PrestaShop/issues/12062#issuecomment-452270266) also.
Thanks!

**Comment by bartes1987** [comment] 2019-01-22 10:04
I made all these updates and I'm afraid that the problem still occurs in my case.

**Comment by khouloudbelguith** [comment] 2019-01-22 10:09
@bartes1987, did follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/12062#issuecomment-452269373)?, did you made changes in all those tables:

ALTER TABLE `PREFIX_supply_order_receipt_history` CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '';

ALTER TABLE `PREFIX_supply_order_receipt_history` CHANGE `employee_lastname` `employee_lastname` VARCHAR(255) DEFAULT '';

ALTER TABLE `PREFIX_order_detail` CHANGE `product_supplier_reference` product_supplier_reference varchar(64) DEFAULT NULL;
![image](https://user-images.githubusercontent.com/16067358/50828388-8e237080-1341-11e9-940a-eac03ad7c9fb.png)

ALTER TABLE `PREFIX_product_attribute` CHANGE product_supplier_reference product_supplier_reference varchar(64) DEFAULT NULL;

ALTER TABLE `PREFIX_product` CHANGE `reference` `reference` varchar(64) DEFAULT NULL;

ALTER TABLE `PREFIX_product_lang` CHANGE `meta_description` `meta_description` varchar(512) DEFAULT NULL, CHANGE `meta_keywords` `meta_keywords` varchar(255) DEFAULT NULL;

PS: **PREFIX** is the prefix of your tables, t could be for example ps.

In your Database, for each table, did you check the "Structure" tab?

**Comment by bartes1987** [comment] 2019-01-22 10:26
Yes, I made these changes. I'm attaching the screenshots from my current databse. 
![database](https://user-images.githubusercontent.com/31964938/51529215-9c40b900-1e38-11e9-9119-58940efc73bf.png)
![database1](https://user-images.githubusercontent.com/31964938/51529216-9c40b900-1e38-11e9-9725-7525c5f0f1ef.png)
![database2](https://user-images.githubusercontent.com/31964938/51529217-9c40b900-1e38-11e9-844a-dff54463b042.png)
![database3](https://user-images.githubusercontent.com/31964938/51529218-9cd94f80-1e38-11e9-9d6b-7c7e605aaf42.png)
![database4](https://user-images.githubusercontent.com/31964938/51529220-9cd94f80-1e38-11e9-8c98-c642fbadd3ce.png)

**Comment by khouloudbelguith** [comment] 2019-01-22 10:38
@bartes1987, it seems that your issue is different, this issue is currently closed, can you open a new one with more information about your configuration.
Thanks!

**Comment by bartes1987** [comment] 2019-01-22 10:54
@khouloudbelguith  Ok, I did it: #12257

**Comment by damiafrau** [comment] 2019-01-28 09:45
> This problem seams to happen only in Apple Safari and not with Chrome on Mac

Hi, 

same error here, using Mac and Chrome upgrading from 1.7.2 to 1.7.5

**Comment by Argez** [comment] 2021-01-08 19:18
Hi. I am having this same problem but it is multistore when I select the "all store" view

**Comment by amerigeau** [comment] 2024-05-24 08:39
Hi,

In order to help someone with same issue.
Context : prestashop 1.7.8.8 / multishop enabled / product with combinations.

Error : same as https://github.com/PrestaShop/PrestaShop/issues/11825#issuecomment-449841858

Discover in /src/Adapter/CombinationDataProvider.php line 102 $productId returns 0 so $combinations returns empty array.
`$productId = (new Combination($combinationIds[0]))->id_product;`

Change it to : 
`$productId = ($productId) ? $productId : Product::getIdProductByIdProductAttribute((int) $combinationIds[0]);`

Then add an override of Product.php classe here /override/classes/Product.php with file attached.
[Product.txt](https://github.com/PrestaShop/PrestaShop/files/15430664/Product.txt)

Should solve the problem ;)
