### ISSUE TITLE
url rewriting accented

### ISSUE THREAD

**Issue by fafa0659** [PrestaShop/PrestaShop#15124] opened 2019-08-16 07:20 UTC
**Describe the bug**
problem on url rewriting , all url accented are modified in google result
when you use url  "+" to replace "-" this is remplaced by %2
**To Reproduce**
create a product with url modified ( url accented must be actived )
**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![2019-08-16_09h17_04](https://user-images.githubusercontent.com/53341093/63150386-eec90900-c006-11e9-9602-3a4e18943e3b.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.1.31

**Comment by mariem-abid** [comment] 2019-08-16 08:51
Hi @fafa0659,

Could you please add steps to reproduce the issue.

**Comment by fafa0659** [comment] 2019-08-21 05:43
step are easy. ( on prestashop 1.7.6)

1.activated url accentued
2.create a product 
3.on url product replace "-" by "+" 
when the url is read by google all "+" will be  replace by %2

**Comment by khouloudbelguith** [comment] 2019-08-21 10:15
Hi @fafa0659,

I did not manage to reproduce the issue with PS1.7.6.0.
https://drive.google.com/file/d/1BGh88X8PMlIXoWvORCqK7IDwZtXwctr_/view
- Route to products: `{category:/}{id}{+:id_product_attribute}+{rewrite}{-:ean13}.html`
- When a product has not a combination => `http://projet/QA/1760ch/en/home/25+test.html`
- When a product with combinations => `http://projet/QA/1760ch/en/home/25+43+test.html#/2-size-m`
- I tried with this link `http://projet/QA/1760ch/en/home/25+43+test.html#/2+size+m` => OK
https://drive.google.com/file/d/1qSddXv5IUqvnjvLJptZpB4kulU0Gr3Rr/view
Thanks to check & feedback.

**Comment by fafa0659** [comment] 2019-08-21 18:43
hi @khouloudbelguith 
the problem is it on encoding for google .
i have tried to take some pictures to help you to find origin problems
on this example i have create a page cms 

domain.com/23-xxx+xxxx+xxxx+xxx
you can see it on pictures attached, google remplace all "+" by 2b now in search co,sole or google result the page became domain.com/23-xxx2%xxxx2%xxxx2%xxx

when you clic on the google resulkt you can be rediriged to  my website for the goog page but with the url corrupted.

the page work with the two adress  ( domain.com/23-xxx2%xxxx2%xxxx2%xxx and domain.com/23-xxx+xxxx+xxxx+xxx )

i think it is encoding problem 
url accentued actived and in page way i dont have put "+"


![after-clikingon google](https://user-images.githubusercontent.com/53341093/63458870-e1bb7800-c453-11e9-84c6-c6786c874b3f.png)
![cms-page-url-modified](https://user-images.githubusercontent.com/53341093/63458883-e6802c00-c453-11e9-8c08-96fe7ea20e03.png)
![search-console](https://user-images.githubusercontent.com/53341093/63458900-ed0ea380-c453-11e9-8a6b-820442d18586.png)
![url original+](https://user-images.githubusercontent.com/53341093/63458901-ed0ea380-c453-11e9-911d-226fe842b007.png)
![url-accentued-actived](https://user-images.githubusercontent.com/53341093/63458902-eda73a00-c453-11e9-84d5-2af676400e59.png)
![url-google-result](https://user-images.githubusercontent.com/53341093/63458904-eda73a00-c453-11e9-8a85-627fd8fcb687.png)
![way-not-modified](https://user-images.githubusercontent.com/53341093/63458906-ee3fd080-c453-11e9-89ff-bab04a6b1fa1.png)

best regards

**Comment by khouloudbelguith** [comment] 2019-08-22 11:08
@fafa0659;
>url product replace "-" by "+"

How did you replaced "-" by "+".
I tried with cms pages & it is OK
They are well displayed in th Google analytic report.
![pages_url](https://user-images.githubusercontent.com/16067358/63510073-9053cd00-c4d5-11e9-9065-6e233bfe3b33.png)

Thanks!

**Comment by fafa0659** [comment] 2019-08-22 14:36
@khouloudbelguith

i replace directly in product detail url , i put "+" between every word
you cannnot do it from trafic seo page

search console and google analytics dont do the same things i have show you
in google result that make it wrong .

you can see in files attached other site using it and are not wrong on
google , i think really that it is encoding problem for special caractere




[image: Pièces jointes]










Le jeu. 22 août 2019 à 13:09, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2019-08-22 15:05
@fafa0659, you can check those files
`src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php `
Files into this path `src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/`

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-22 15:37
@fafa0659, so in your browser after clicking this "http://projet/QA/1760ch/en/home/25+43+test.html#/2+size+me" you are redirected to the incorrect URL.
Why you are editing the URL from the browser & not from the Shema of URLs from the BO?
What is the exact browser did you use?

Thanks!

**Comment by fafa0659** [comment] 2019-08-22 16:37
@khouloudbelguith
i will check it



Le jeu. 22 août 2019 à 17:06, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by fafa0659** [comment] 2019-08-22 16:45
@khouloudbelguith

in firefox and console search that is idenpendant of the browser

if i edit from the scema url i cannot build url with "+" between every word

**Comment by khouloudbelguith** [comment] 2019-08-23 09:24
@fafa0659, in fact, you need to edit the schema URL for the Route pages & when you create a new page => you need to edit the Friendly URL of this page
![image](https://user-images.githubusercontent.com/16067358/63582015-29dfb500-c590-11e9-820c-d19e84bb32d2.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-23 07:32
Hi @fafa0659,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-23 07:32 UTC
Labels: Bug, FO, SEO & URLs, No change required, 1.7.6.0
