### ISSUE TITLE
Add 'Best sellers' as default order by in category page

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#21027] opened 2020-09-17 07:28 UTC
#### Describe the solution you'd like

Add 'Best sellers' as default order by in category page.

![image](https://user-images.githubusercontent.com/15104724/93434095-fc1a8c00-f8c7-11ea-9f0f-e802d9109d32.png)

![image](https://user-images.githubusercontent.com/15104724/93434178-16ed0080-f8c8-11ea-8790-8f9159e1b8d9.png)

**Comment by florine2623** [comment] 2020-09-17 07:35
Hi @idnovate ,
Thanks for the suggestion.
Please stay tuned as we review your request.
Thanks!

**Comment by florine2623** [comment] 2020-09-17 07:36
Ping @PrestaShop/product-team ,
What do you about this improvement ?
Thanks!

**Comment by marionf** [comment] 2020-09-17 08:34
Hello,

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/20535#issuecomment-672918693
Please subscribe to the issue mentioned above and don't hesitate to add a comment to share your need

Thank you!

**Closed as completed by marionf** 2020-09-17 08:34 UTC
Labels: Improvement, FO, Duplicate, Best Sellers
