### ISSUE TITLE
Autoupgrade - from V8.1.7 to V9 - When you want to upgrade, you've an error because of Empty text 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#36402] opened 2024-06-21 08:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to upgrade from V 8.1.7 to V 9.0.0, during the installation, I have an Error as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/2a912d56-b4e1-4fa9-a2a5-4194d7d73dd5)

I also have the issue on the dev branch of Autoupgrade

### Expected behavior

I wish I could Upgrade to the version 9.0.0

### Steps to reproduce

1. Install V 8.1.7
2. Go to BO 
3. Go to module Manager
4. Install Autoupgrade
5. Clic on Configure 
6. Set on Local archive with a V9
7. Launch the Autoupgrade 
8. :x: Your Upgrade should be stopped 

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.3

### Your company or customer's name goes here (if applicable).

PS

**Comment by Quetzacoalt91** [comment] 2024-06-21 09:06
@AureRita Can you share your log.txt file? The TextEmptyType.php should have been deleted during the step upgrading files.

![image](https://github.com/PrestaShop/PrestaShop/assets/6768917/d64e632c-f88b-4f26-bc58-a1dd5a20d232)

**Comment by AureRita** [comment] 2024-06-21 09:14
No problem, I give you the files :  
[log.txt](https://github.com/user-attachments/files/15925479/log.txt)

**Comment by Quetzacoalt91** [comment] 2024-06-21 09:22
Interesting. The wasn't deleted during the process, there is no mention of it during the upgrade step in the logs.

Can you provide the archive and the xml file you used for the upgrade?

**Comment by AureRita** [comment] 2024-07-01 09:22
Hello @Quetzacoalt91 

sorry for the time spend to answer you, I'll give you the archive and the XML : 

[20221019_163118.zip](https://github.com/user-attachments/files/16050691/20221019_163118.zip)

Waiting for your feedback

**Comment by Quetzacoalt91** [comment] 2024-07-01 09:41
We've tried again last Friday as you previously provided the files privately, but the issue could not be reproduced. The issue may be fixed by a previous PR on the autoupgrade module

**Comment by paulnoelcholot** [comment] 2024-07-02 13:29
Hello @AureRita,

I tried to reproduce your issue but as you can see, I can't.

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/28cb3dcf-836e-4e68-9c49-cf27a4cce384)

Did I miss something?

Thanks for your feedback :pray:

**Comment by paulnoelcholot** [comment] 2024-08-07 08:37
Hello @AureRita,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-08-07 08:37 UTC
Labels: Bug, BO, Can't reproduce, Autoupgrade, Module, 8.1.x, Backlog SUE
