### ISSUE TITLE
Support for SVG files

### ISSUE THREAD

**Issue by DracoBluee** [PrestaShop/PrestaShop#25600] opened 2021-08-14 00:01 UTC
Prestashop 8.0.0 must have svg support adding a logo, favicon etc.

**Comment by eveneme** [comment] 2021-08-14 11:25
yes, please supported SVG files

**Comment by matks** [comment] 2021-08-14 19:46
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/10600 and https://github.com/PrestaShop/PrestaShop/issues/17673 😉 

Please do a quick search before creating a new issue, someone might have already created something before 😄

**Closed as completed by matks** 2021-08-14 19:46 UTC
Labels: Duplicate
