### ISSUE TITLE
JS error prevents the launch of the module configuration.  Prestashop 1.7.5.0

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#12906] opened 2019-03-13 12:04 UTC
This problem occurs in the back office when editing a product in Prestashop 1.7.5.  Active modules under the 'Modules' tab are unable to launch due to a JS error produced by Prestashop.

Screen shot of the error attached.
![screenshot](https://user-images.githubusercontent.com/44204668/54277527-07c91c00-4588-11e9-8fad-49aaa224311f.jpg)

It seems it is related to the text which is entered into the "Meta Description" field under the SEO tab.  IN this case the text which causes the JS error is:

"Actie Laminaat 715 is niet alleen mooi om te zien, maar ook nog eens onderhoudsvriendelijk en bestand tegen de uitdagingen in het dagelijkse leven."

Hope this will be solved as I am getting multiple tickets regarding this issue.

Kind Regards
Musaffar

**Comment by khouloudbelguith** [comment] 2019-03-14 08:46
Hi @musaffar-patel,

here's the PR: #11923 to fix the issue.
It is fixed in the next release PS1.7.5.1.
Your ticket is a duplicate of #11911
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-14 08:47
Duplicate of #11911

**Closed as completed by khouloudbelguith** 2019-03-14 08:46 UTC
Labels: Duplicate
