### ISSUE TITLE
Problème lors du passage de prestashop 1.6 vers 1.7

### ISSUE THREAD

**Issue by Lucascetii** [PrestaShop/PrestaShop#14069] opened 2019-06-04 10:01 UTC
**Describe the bug**
suite à une mise à jour de prestashop je n'ai pas accès à certaines parties du back office comme la partie "produit" ou "module" Lorsque je souhaite y accéder un message d'erreur s'affiche 

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

**To Reproduce**
1. Go to prestashop backoffice -> catalog-> product

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/51364067/58870363-5df9b700-86c0-11e9-9330-40c78dddae85.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-06-04 10:03
Hi @Lucascetii,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

PS: English is the norm on GitHub 

Thank you!

**Comment by Lucascetii** [comment] 2019-06-04 12:24
Thanks fo your answer

host : apache 
server setup and configuration : Linux #1 SMP Thu Aug 23 15:15:40 CEST 2018 x86_64
debug mode report : https://www.cetii-distribution.fr/admin137/index.php/_profiler/c9e405?panel=logger&_token=V37ZnfUQMq8uCeLvXzG4ZdiLfKNxhMJNuCKzeO6gCV4 
PHP error logs : i don't know how to have this information
apache error log : i don't know how to have this information
javascript console log : i don't know how to have this information

i took a screenshot what the issue seems to be 
![image](https://user-images.githubusercontent.com/51364067/58878804-6eb42800-86d4-11e9-95a8-31a97494bfbd.png)

Please tell me if you need more information

**Comment by khouloudbelguith** [comment] 2019-06-04 12:27
@Lucascetii, you have an issue with the `easyloginascustomer` module.
It could be not compatible with PS1.7.
You should contact the module author about this issue.

Thanks!

**Comment by Lucascetii** [comment] 2019-06-04 12:35
Thanks i will do that but why i can open "order or categorie" on the back office and i can't open specifically "product" ?

**Comment by khouloudbelguith** [comment] 2019-06-04 12:36
@Lucascetii, try to disable this module temporarily, clear cache, check & feedback.
Thanks!!

**Comment by Lucascetii** [comment] 2019-06-04 12:40
i can't beacause i have a issue when i try to open module menu. 
![image](https://user-images.githubusercontent.com/51364067/58879745-a3c17a00-86d6-11e9-9d33-de6e33f2750b.png)

**Comment by khouloudbelguith** [comment] 2019-06-04 12:43
@Lucascetii, you have an issue with the `shopimpoter` module also.
![image](https://user-images.githubusercontent.com/16067358/58879959-b59f1f00-86ce-11e9-82a4-7668c12b2bbd.png)

It could be not compatible with PS1.7, you need to check with the module author.
In the meantime, in your Projet_folder/modules/ you can rename the module folder to name_of_module_old.
This is a temporary fix.

Thanks!

**Comment by Lucascetii** [comment] 2019-06-04 13:00
i did this but now i can't open my back office there is message
![image](https://user-images.githubusercontent.com/51364067/58881015-893cd000-86d9-11e9-87aa-d9d75acf8173.png)

**Comment by khouloudbelguith** [comment] 2019-06-04 13:13
@Lucascetii, what about the `easyloginascustomer` module, 
![image](https://user-images.githubusercontent.com/16067358/58881819-db2e2780-86d2-11e9-98c6-3cc4b31a7a6f.png)
This module is causing the issue.
Thanks!

**Comment by Lucascetii** [comment] 2019-06-04 13:29
yes it was resolved the issue so now i can open the "module menu" but even if i added "_old" after the name of the folder of the "shopimporter" module and "easylogincustomer" module i still can't open the product on the back office.
![image](https://user-images.githubusercontent.com/51364067/58882834-817f2a80-86dd-11e9-8c53-91718f2c025f.png)

**Comment by khouloudbelguith** [comment] 2019-06-04 13:51
@Lucascetii, It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.2
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.5.2 here: 
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql

Thanks to check & feedback

**Comment by Lucascetii** [comment] 2019-06-04 14:25
i dont know how to do this it will be too difficult for me to edit the datebase...

**Comment by khouloudbelguith** [comment] 2019-06-04 14:30
@Lucascetii, you just need to follow this link: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/install-dev/data/db_structure.sql, this is our database schema for the PS1.7.5.2 & compare it with yours, it could something missing in your case.
It could be some tables were different from the 1.7.5.2 schema, you need to update them.

Thanks for your understanding!

**Comment by Lucascetii** [comment] 2019-06-04 14:51
i understand the issue but i don't know how to open my database schema

**Comment by khouloudbelguith** [comment] 2019-06-04 15:16
@Lucascetii, if you use phpmyadmin you can export the database schema to pdf.
Thanks!

**Comment by Lucascetii** [comment] 2019-06-05 09:06
hi, 

i have a an other issue with the image slider on home page. It doesn't work whatever the size of the picture.

**Comment by Lucascetii** [comment] 2019-06-05 09:06
![image](https://user-images.githubusercontent.com/51364067/58944361-fa37c280-8781-11e9-9876-3e69b728e516.png)

**Comment by khouloudbelguith** [comment] 2019-06-11 15:52
@Lucascetii, I checked your shop.
the ps_sliderimage is not displayed
![image](https://user-images.githubusercontent.com/16067358/59287251-33cc6a00-8c69-11e9-9aea-d05670cf35c9.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-07-11 08:48
Hi @Lucascetii,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-11 08:48 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.5.2
