### ISSUE TITLE
1.7.4.2 Crosseling product detail

### ISSUE THREAD

**Issue by sirion89** [PrestaShop/PrestaShop#11276] opened 2018-11-06 10:11 UTC
**Describe the bug**
Link to PS forum for BC: https://www.prestashop.com/forums/topic/934110-1742-crosseling-product-detail/

My product detail page has a crosselling product carousel, theme developers told me it's based on PS_CROSSELLING so i'm posting this here. 

The issue, at least for what i could understand by testing, is that it has something to do with the template/cache.
Looks like that if i leave it like this,everything works fine (see attachments, i can see all the carousel product detail info (title,description,stars). If i remove nocache

and i have active cache setting in backend (see screenshots) then only the first product has all the info, the following one has not even generated HTML for those parts. Looking at the compiled smarty file i can say that changing that "nocache" actually change what is generated drastically. 

Another way to make this work is to simply disable cache in backend setting, but since it's a production webiste with some decent traffic i would like to keep cache enabled and find a solution for this.

I couldn't find any way to debug this, enabling debug mode, forcing php to show errors, looking at server log didn't help in any way,

 

Any suggestion/fix for this?

**To Reproduce**
I don't really know if by installing the same exact thing i have you could reproduce it

**Screenshots**
![schermata 2018-11-06 alle 10 53 27](https://user-images.githubusercontent.com/5064007/48057576-a8f82e00-e1b4-11e8-8603-7f3f5812d9ad.png)
![schermata 2018-11-06 alle 10 53 46](https://user-images.githubusercontent.com/5064007/48057577-a8f82e00-e1b4-11e8-8497-7f66f1ae2be1.png)
![schermata 2018-11-05 alle 16 10 05](https://user-images.githubusercontent.com/5064007/48057591-b1506900-e1b4-11e8-8245-6162040f6f20.png)
![schermata 2018-11-05 alle 16 10 19](https://user-images.githubusercontent.com/5064007/48057592-b1e8ff80-e1b4-11e8-95ea-d56be6509c88.png)
![schermata 2018-11-05 alle 16 10 32](https://user-images.githubusercontent.com/5064007/48057593-b1e8ff80-e1b4-11e8-83fe-a61c6d065ddf.png)
![schermata 2018-11-05 alle 16 11 05](https://user-images.githubusercontent.com/5064007/48057594-b1e8ff80-e1b4-11e8-95ea-a093a3262012.png)

**Additionnal information**
Prestashop: 1.7.4.2 (migrated form an old 1.6.x if it can help understand something with MigrationPro)

Theme: warehouse 4.1.7

**Comment by khouloudbelguith** [comment] 2018-11-06 10:43
Hi @sirion89,

I did not manage to reproduce the issue with the last version 1.7.4.3& the default theme.
I attached a video record.
https://drive.google.com/file/d/1mXVGUpOsc1rd1TlJwk7AAmOX0RkI0Rd3/view
Thanks to check & feedback.

**Comment by sirion89** [comment] 2018-11-06 10:49
Mmmm then i suppose it has something to do with my theme/extra module, the stars for example comes from an extra module that hooks into the display to add that part.

Do i have any way to debug what's happening? it's quite freaky that with cache disable everything works. I'm not a PS expert and i never used smarty in my life (i come from symfony). Do you have any idea on where i could find any extra info? debugging doesn't work inside .tpl files in my IDE (PhpStorm)

**Comment by khouloudbelguith** [comment] 2018-11-06 10:59
@sirion89, to get more info?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sirion89** [comment] 2018-11-06 11:15
Debug mode: since it's something i could reproduce on my local env where i can even go with xDebug i can tell you that i couldn't find any difference with debug mode enabled
PHP error log: i use MAMP PRO, and there are no errors in my logs
Apache log: nothing weird there
Javascript log: using chrome inspector i have nothing wrong in my console, i even disabled JS/inspect page source. The HTML is simply missing with cache enabled

This is why i'm kinda depressed with this issue, i have nothing to start understanding what's wrong.

As soon as i have a free moment i will try to install a fresh PS with the same theme i'm using online (just with a new fresh download) and see if it's still happening. That would be my last hope i guess

**Comment by khouloudbelguith** [comment] 2018-11-06 11:22
Hi @sirion89,

Thanks!
Waiting for your feedback.

**Comment by sirion89** [comment] 2018-11-06 15:09
Looks like i cannot reproduce it either with fresh PS + theme, it must be something to do with something else added later,maybe the star module, ill keep investigating in free times

**Comment by khouloudbelguith** [comment] 2018-11-06 15:12
@sirion89, Okey.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-14 15:22
Hi @sirion89,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-14 15:22 UTC
Labels: FO, Cross selling, No change required, 1.7.4.2

**Comment by sirion89** [comment] 2018-12-14 15:58
> Hi @sirion89,
> 
> Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
> Thanks!

It's ok, we gave up trying to understand what's going wrong. We just disabled the cache and everything works fine
