### ISSUE TITLE
Overlap between description and category image in the Front Office

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#13230] opened 2019-04-08 10:28 UTC
**Describe the bug**
Try to add a description and an image for a category in the Back office and then display them in the front office.

**Screenshots**
![category](https://user-images.githubusercontent.com/16067358/55717526-66e84800-59f1-11e9-84b6-282260ab66cd.png)

**Additionnal information**
PrestaShop version: 1.7.5.1

**Comment by marionf** [comment] 2019-04-08 14:22
I can reproduce it on 1.7.5.1

![capture d'écran_1329](https://user-images.githubusercontent.com/13449658/55731377-66b07280-5a1a-11e9-9843-cfd82c3ab958.png)

But not on develop branch

![capture d'écran_1328](https://user-images.githubusercontent.com/13449658/55731409-7465f800-5a1a-11e9-9689-9ddaa67b5ec5.png)

So I close it

**Closed as completed by marionf** 2019-04-08 14:22 UTC
Labels: Bug, Minor, FO, Duplicate, Categories, 1.7.5.1

**Comment by marionf** [comment] 2019-04-08 14:23
Duplicate of #9979

**Comment by marionf** [comment] 2019-04-08 14:24
It's fixed by https://github.com/PrestaShop/PrestaShop/pull/11495
