### ISSUE TITLE
Cart error messages not consistent/persistent

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#29384] opened 2022-08-18 07:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When having a product in the cart, in a quantity that is not available we get an error message saying that. When we change the quantity of a product in the cart to a quantity that is not available we get a message saying that. Changing another product to a quantity that is available, the previous error message disappears and everything seems to be fine.

Screen recording here: https://www.loom.com/share/3090eecd27554833af1d48c579a4f954

### Expected behavior

If there is a problem with the current cart those error messages should always be consistent/persistent. If a product is out of stock, it should clearly state just that. Only the changes that actually takes care of that message should remove that message. I.e. removing the product or adjusting the quantity of said product.

### Steps to reproduce

1. Add two or more products to cart
2. Go to cart
3. Change desired quantity for product 1 to a quantity that is not available
4. See error message.
5. Change quantity on product 2. Previous error message disappears

You can also refresh the page with an invalid quantity for one product and repeat step 5 above.

### PrestaShop version(s) where the bug happened

1.7.x - 8.0

### PHP version(s) where the bug happened

Not applicable

**Comment by hibatallahAouadni** [comment] 2022-08-18 14:27
Hello @dennispw 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #18958. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-18 14:27
Duplicate of #18958

**Closed as completed by hibatallahAouadni** 2022-08-18 14:27 UTC
Labels: Bug, Duplicate, Invalid
