### ISSUE TITLE
Can not access old orders after upgrade presta to 1.7.7.

### ISSUE THREAD

**Issue by idiamin777** [PrestaShop/PrestaShop#22769] opened 2021-01-11 15:38 UTC
Hello
I updated my Prestashop from 1.7.6 to 1.7.7.0 some 2 month ago and everything works fine.  
now I cant see details of old orders and I will get the below error :

```
Type error: Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderProductCustomizationForViewing::__construct() must be of the type string, null given, called in /var/www/print-it.dk/public_html/src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php on line 116
ExceptionLogs 2Stack Trace
Symfony\Component\Debug\Exception\
FatalThrowableError
in src/Core/Domain/Order/QueryResult/OrderProductCustomizationForViewing.php (line 60)
    /**    
       * @param int $type     
       * @param string $name
       * @param string $value
       * */    
      public function __construct(int $type, string $name, string $value)    {
              $this->type = $type;
              $this->name = $name;
              $this->value = $value;
              if (Product::CUSTOMIZE_FILE === $this->type) {
```

PrestaShop version: 1.7.7.0 (DK)
PHP version: 7.3

Seen other having problems and I added the hack unto copy/testshop and everything worked again - but on lifeshop I get this error when I try to access the BO Order.

Thanks - AR

**Comment by hibatallahAouadni** [comment] 2021-01-11 15:47
Hello @idiamin777 

Could you please edit your issue **following the provided template to submit a complete bug report**.
And your issue seems similar to this one #22386
Please check and feedback.

Thanks!

**Comment by idiamin777** [comment] 2021-01-11 17:44
Thanks, I am a first time user, and just gave it a shot – it´s done now and looking good!

The issue  #22386 did help on our testshop which has not all the newest orders. 

Have a great day.

**Comment by hibatallahAouadni** [comment] 2021-01-12 09:27
Duplicate of #22770

**Closed as completed by hibatallahAouadni** 2021-01-12 09:27 UTC
Labels: Bug, BO, Duplicate, Order, Autoupgrade, Product customization, 1.7.7.0
