### ISSUE TITLE
PS 1.7.7.0 - cannot find products when using "Add a new order"

### ISSUE THREAD

**Issue by cla1982** [PrestaShop/PrestaShop#22606] opened 2020-12-28 11:59 UTC
Hello, 

after the upgrade to PS 1.7.7.0, when I try to "add a new order" in the backoffice PS can find the customer in the first search box, but in the next step PS doesn't find any product to add in the order (as if there weren't even one, but there are over 1k products).

Please, can someone help me? Thanks in advance.

![Screenshot - 28_12_2020 , 12_55_50](https://user-images.githubusercontent.com/59873029/103212830-3d312c00-490c-11eb-96c1-a579f51ef479.jpg)

**Comment by hibatallahAouadni** [comment] 2020-12-28 16:23
Hello @cla1982 

Could you please provide the PrestaShop version before the upgrade?

Thanks!

**Comment by cla1982** [comment] 2020-12-28 16:25
The previous version was 1.7.6.9

**Comment by hibatallahAouadni** [comment] 2020-12-29 08:39
Hello @cla1982 

I didn't manage to reproduce your issue, the only issue I encountred is #22250 
Could you please provide more infos and edit your issue description **following the template to submit a complete bug report**.
We afford this template to help you with your issue, we need every detail.
Please check your console, if you have any error thrown (make a screenshot and attache it).

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-21 15:42
Hello @cla1982 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-21 15:42 UTC
Labels: Bug, BO, Order, Autoupgrade, No change required, 1.7.7.0
