### ISSUE TITLE
Google analytics does not work in BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17798] opened 2020-02-24 13:36 UTC
**Describe the bug**
Default ps_googleanalytics module does not track anything in Prestashop backoffice. It is important to track cancelled and refunded orders.

Error is detected by Tag Assistant as well as manual check, even after 48 hours, nothing changed.

There are 2 year old bug reports in the module repo, but they are closed without a solution. (???)

**To Reproduce**
1. Install and set up ps_googlenalytics. Fill in tracking ID.
2. Install Google Tag assistant, enable recording.
3. See "No HTTP response detected" error.

**Additional information**
PrestaShop version: 1.7.6.2
Google analytics module: 3.2.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-02-24 15:19
Hi @Hlavtox,

I have the same behavior as PS1.7.6.3 and PS1.7.5.2 and ps_googlenalytics v3.2.0.
![image](https://user-images.githubusercontent.com/16067358/75164456-2389eb80-5721-11ea-8633-c14e311e4cb7.png)
But, I think, it could a good improvement for the module.
@Hlavtox, what do you think, can we update this issue from bug to improvement?

Thanks!

**Comment by Hlavtox** [comment] 2020-02-24 15:35
@khouloudbelguith 

I discovered this, because I went to add another functionality for the BO (https://github.com/PrestaShop/ps_googleanalytics/pull/43). And 2 days later, I was wondering why the transaction still does not appear, and I discovered that it does not work at all in BO. 😄 

I think it's definitely a bug, because there is functionality for refund in the code. It is indended for it to work like this. The module is hooked to actionProductCancel, displayBackOfficeHeader etc.

Look at the existing code:
![refund](https://user-images.githubusercontent.com/6097524/75165996-841a2800-5723-11ea-983c-6cea0121326a.JPG)

It is probably some JS error, but my console is clear, I have no idea.

**Comment by khouloudbelguith** [comment] 2020-02-24 15:41
@Hlavtox, thanks for your feedback.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Hlavtox** [comment] 2020-02-27 09:07
@khouloudbelguith False alarm, it shows the error because there is no pageview action sent. 

My refund PR works fine!!! 🍺

Shouldn't we write this somewhere, that is it not a bug? I am like the third person to open this... 😄

**Comment by khouloudbelguith** [comment] 2020-02-27 09:14
@Hlavtox, 

>My refund PR works fine!!!

this PR: https://github.com/PrestaShop/ps_googleanalytics/pull/43?

Thanks!

**Comment by Hlavtox** [comment] 2020-02-27 09:54
@khouloudbelguith Yes :-)

**Comment by khouloudbelguith** [comment] 2020-02-27 09:58
@Hlavtox,

>Shouldn't we write this somewhere, that is it not a bug?

What do you think about updating the [Readme.md](https://github.com/PrestaShop/ps_googleanalytics/blob/master/Readme.md)?

>Yes :-)

I will close this issue as it is not a bug.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-27 09:58 UTC
Labels: Bug, BO, No change required, Google Analytics, 1.7.5.2, 1.7.6.3

**Comment by Hlavtox** [comment] 2020-03-09 16:22
@khouloudbelguith Hi, I added a note to readme. :-)

https://github.com/PrestaShop/ps_googleanalytics/pull/44
