### ISSUE TITLE
Price filter not working correctly on pages >1

### ISSUE THREAD

**Issue by DevSTG** [PrestaShop/PrestaShop#15950] opened 2019-10-15 09:03 UTC
If category has more than 1 page of products and you set price filter on page >1 and there are not enough products that match the filter to fill subsequent pages, then on those pages there are wrong results.
Also in case of other filters (colour, fabric) customer is moved to first page, but not in this case.

1. Go to category that has products for >1 pages (for example Home category on fresh install or online PS demo)
2. Go to page 2 of the category
3. Set price filter that will not match products on 2nd page
4. See empty page although products are matched (but not in amount to fill current page) and see wrong pagination text.

Screenrecord:
https://drive.google.com/file/d/1N3KG7B5gA4F5CTHR0a-amlpT1oqg2MhE/view

PrestaShop version: 17.6.1
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-10-15 10:26
Hi @DevSTG,

Here's the PR: https://github.com/PrestaShop/ps_facetedsearch/pull/143 to fix the issue.
Your ticket is a duplicate of #15608
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-15 10:26
Duplicate of #15608

**Closed as completed by khouloudbelguith** 2019-10-15 10:26 UTC
Labels: Duplicate, Faceted search
