### ISSUE TITLE
A category in multistore environment still works in a certain shop even if is disabled

### ISSUE THREAD

**Issue by marsaldev** [PrestaShop/PrestaShop#28093] opened 2022-03-31 13:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If a category is disabled for a certain shop, is still navigable in that shop

https://user-images.githubusercontent.com/48283112/161071241-fdf20a95-db29-4f42-8733-0d756bb57f67.mov

### Expected behavior

The shops should return a 404, or whatever. 
Basically, the category url should not be "active" in the shop(s) where is disabled.

### Steps to reproduce

1. Enable the multistore feature (possibly on a fresh installation)
2. Do not share customers, orders, and quantities
<img width="1116" alt="Schermata 2022-03-31 alle 15 20 45" src="https://user-images.githubusercontent.com/48283112/161070186-df45ebbf-ca70-458b-b225-fd5a63ddd4bc.png">

4. Create a new store without selecting the categories of main shop 
<img width="806" alt="Schermata 2022-03-31 alle 15 43 19" src="https://user-images.githubusercontent.com/48283112/161069810-2fb752d3-ceda-4676-a6fa-ef8fa4b3da59.png">

5. Go to the front office of the new store created (e.g. shop2) (don't forget to set the url)
6. Write in the navigation bar of the browser the url of the category disabled (e.g. myshop.com/shop2/6-accessories)
7. Category and products are visible

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by khouloudbelguith** [comment] 2022-04-01 08:18
Hi @marsaldev,

Thanks a lot for your report.
I manage to reproduce the issue with PS1785.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13468
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2022-04-01 08:18
Duplicate of #13468

**Closed as completed by khouloudbelguith** 2022-04-01 08:18 UTC
Labels: Bug, Duplicate, Categories, Multistore, SEO & URLs, Invalid
