### ISSUE TITLE
Error 500 on "Choose layout" page

### ISSUE THREAD

**Issue by cdcvince** [PrestaShop/PrestaShop#26330] opened 2021-10-19 16:00 UTC
#### Describe the bug

Error 500 on the "Choose layout" page on the BO

#### Steps to Reproduce

1. Go to Backoffice
2. Click on Design > Theme & logo
3. Scroll to bottom of page and click on "choose layouts"
4. This error appears :

![Screenshot from 2021-10-19 17-57-51](https://user-images.githubusercontent.com/39367588/137947973-877dc530-fbf1-475e-bd75-cf3c2dcd26cd.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3.28

**Comment by hibatallahAouadni** [comment] 2021-10-20 09:16
Hello @cdcvince 

I didn't manage to reproduce the issue with PS1780, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/138065168-03216541-3b06-43fd-b53a-8174dbeec732.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-08 15:42
Hello @cdcvince 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-11-08 15:42 UTC
Labels: Bug, BO, Design, Theme & logo, 1.7.8.0, Invalid
