### ISSUE TITLE
OnBoarding

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#31507] opened 2023-02-23 12:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
I can not access to position menu 
L'action Enable est impossible pour le module welcome. Le module n'est pas valide et ne peut pas être chargé.
I enabled the debug then i can see this message

Attempted to load class "OnBoarding" from namespace "OnBoarding".
Did you forget a "use" statement for another namespace?

in [modules/welcome/welcome.php ](modules/welcome/welcome.php&line=85#line85)(line 85)
            $smartyDisplayHeader = $this->smarty->getTemplateVars('display_header');            $this->displayHeader = (null !== $smartyDisplayHeader && is_bool($smartyDisplayHeader)) ?                $smartyDisplayHeader :                true;            $this->onBoarding = new OnBoarding(                $this->getTranslator(),                $this->smarty,                $this,                SymfonyContainer::getInstance()->get('router')            );

### Expected behavior

I should get access to the position page 

### Steps to reproduce

Go to design the position 

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

welcome

**Comment by HanaRebaiQA** [comment] 2023-02-23 16:09
Hello @go-sudo 

Thanks for your report.
I was unable to reproduce your issue using the same step to reproduce. The position page is well displayed on PS8.0.1 with php7.4.

![image](https://user-images.githubusercontent.com/92912932/220964035-9ce0333f-782e-4a83-b147-9a96d059edce.png)

Could you please check again?

Thank You!

**Comment by go-sudo** [comment] 2023-02-23 16:36
Hi @HanaRebaiQA 
I enabled the default theme but the issue remains 
```

in [modules/welcome/welcome.php ](_profiler/open?_token=oZHDwpDO8IX47IUpZF62JX9sdx5VzWz2HMjHFy4Q1TI?file=modules/welcome/welcome.php&line=85#line85)(line 85)
            $smartyDisplayHeader = $this->smarty->getTemplateVars('display_header');            $this->displayHeader = (null !== $smartyDisplayHeader && is_bool($smartyDisplayHeader)) ?                $smartyDisplayHeader :                true;            $this->onBoarding = new OnBoarding(                $this->getTranslator(),                $this->smarty,                $this,                SymfonyContainer::getInstance()->get('router')            );
```

i tested with php 7.3 / 7.4/ 8.0

idem
Regards

**Comment by hibatallahAouadni** [comment] 2023-02-24 08:29
Hello @go-sudo 

Could you please uninstall the module Welcome/onBoarding and check if you still encounter the issue 🙏 
Did you upgrade your shop lately? or it's fersh install?
Please check and feedback.

Thanks!

**Comment by go-sudo** [comment] 2023-02-24 10:25
Hi @hibatallahAouadni 
Could you please uninstall the module Welcome/onBoarding and check if you still encounter the issue 
I do not find onBoarding on my backend, but I have onBoarding welcome v6.0.8 
**Could not perform action uninstall for module undefined**
I can not uninstal it from backend, so I did remove the /modules/welcome/onBoarding but idem
then i deleted the /modules/welcome, **and YES !! I can get position page even with debug mode**

Did you upgrade your shop lately? or it's fersh install?
Fresh install. 

Should I install the welcome module again if so how and where can I find it please

Regards

**Comment by hibatallahAouadni** [comment] 2023-02-24 13:31
Hello @go-sudo 

> Should I install the welcome module again if so how and where can I find it please

No, you shouldn't! I close the issue as the problem is solved.
BTW, the module Welcome is archived and it will be no longer maintained with 8.0.0.

Thans!

**Closed as completed by hibatallahAouadni** 2023-02-24 13:31 UTC
Labels: Bug, Design, Positions, Welcome, Invalid, Module, 8.0.1
