### ISSUE TITLE
Paypal Translation changes not showing in FO

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#12330] opened 2019-01-28 11:55 UTC
**Describe the bug**
I'm tryin﻿g to change an English translation in the PayPal module from "Currency is not supported" to "Please switch to EUR, USD or GBP". I changed and saved in BO. In my Cpanel I see in the Paypal module/translations folder en.php is updated. However, the change is not appearing in FO.

I only have one language, English. Looking at php configuration: http://loopshops.mu/test.php everything seems fine. Permissions appear fine. I've tried clearing Smarty Cache and browser cache. But nothing works.

The only thing that works is directly replacing text in file error.php in /modules/paypal/controllers/front

**To Reproduce**
1. in BO choose currency not supported by Paypal (e.g. Mauritian Rupee)
2. Go to Paypal module translation (make sure paypal is set up with credit card)
3. Search for "Currency is not supported" and change it to something else
4. Save.
5. Go to FO and make a purchase through Paypal credit card 
6. Error: Currency Not Supported

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-01-28 13:09
Hi @nrcjea001,

This issue reported previously but as described [here](http://forge.prestashop.com/browse/BOOM-5601?focusedCommentId=168493&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-168493): The Paypal module isn't provided by PrestaShop.
You can contact the developer of this module here: https://www.202-ecommerce.com/en/partners-modules/technical-support/
Thanks!

**Comment by nrcjea001** [comment] 2019-01-28 13:52
I'm not sure your link refers to the same issue. The currency works, its just the translation that is the problem.

I spoke to the module developer and they say its an issue with Prestashop

**Comment by khouloudbelguith** [comment] 2019-01-28 14:52
@nrcjea001, thanks for this clarifications.
Sorry, you are right, they are related [link](http://forge.prestashop.com/browse/BOOM-5601) But, when I use a not supported currency, I cannot continue with payment of PayPal, it is not the issue when I use Euro for example.
I attached a video record.
https://drive.google.com/file/d/1O-StOYAX3qyxJkAlTmh-DiAhYGYYeXvR/view
Reported here: https://github.com/PrestaShop/paypal/issues/90
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-28 15:06
@nrcjea001, what is the exact version Paypal did you use?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-28 15:22
Hi @nrcjea001,

Could you please try with this demo module to check if the translation is saved & updated in the FO
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2803647/mymodule.zip)
I tried it with PS1.7.5.0 & it is OK.
Thanks to check & feedback.

**Comment by nrcjea001** [comment] 2019-01-28 17:08
Hi Khouloud

I tried your module and it appears to be working. The issue is only happening with Paypal module

Paypal offers two methods of payment, one via Paypal account and one via credit card. In order for you to use credit card, you would need to activate it in the Paypal module. It does not appear to be activated on your side based on the video record you shared.

You can try Paypal credit card on my website: https://fakebakemauritius.com/index.php

Once you select credit card, you get taken to the following screen (assuming a currency not supported by Paypal): https://fakebakemauritius.com/index.php?error_code=10605&fc=module&module=paypal&controller=error

I wanted to change the translation "Currency is not supported" to something else. I made the change in BO but it did not appear in FO. I had to manually adjust the error.php file to do it. See for example this change: https://loopshops.mu/module/paypal/error?error_code=10605

**Comment by nrcjea001** [comment] 2019-01-28 17:38
Below is the original error message:

![image](https://user-images.githubusercontent.com/26452178/51854717-d7fde600-2344-11e9-8b8b-dd5d9a063c99.png)

and here is my new error message when changing error.php

![image](https://user-images.githubusercontent.com/26452178/51854780-07145780-2345-11e9-9de6-851e8a387d82.png)

**Comment by khouloudbelguith** [comment] 2019-01-29 14:02
Hi @nrcjea001,

Thanks for your feedback.
Yes, in your shop, I have the same issue as you.
But, in my local, I have a strange thing when I used unsupported currency(I tried Paypal credit card)
In the last step, all the payment methods are not displayed.
https://drive.google.com/file/d/1BxWaG-BOqjMIiM4rwpkKoMIgbGaNv8eq/view
What is the exact version of Paypal did you use?
Thanks!

**Comment by nrcjea001** [comment] 2019-01-29 14:27
Paypal v4.4.2

**Comment by khouloudbelguith** [comment] 2019-01-29 15:12
Hi @nrcjea001,

Since this function is blocked.
I tried with another expression provided by PayPal "Unexpected error occurred." & I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4 and the PayPal module v4.4.2.
In the BO => Translations page, I tried to translate the "Unexpected error occurred." expression & save.
![image](https://user-images.githubusercontent.com/16067358/51917666-4e035b00-23e0-11e9-995d-57f88db63c57.png)
The translation is saved successfully.
I the FO => This translation is not displayed
![image](https://user-images.githubusercontent.com/16067358/51917712-6ecbb080-23e0-11e9-998e-ad7cffc77e7e.png)
I attached a video record.
https://drive.google.com/file/d/1vsRhOL94kTxukE7zfJ_rTDpbNNPMMisN/view
I’ll add this to the debug roadmap so that will be fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by marionf** [comment] 2019-06-07 14:28
@khouloudbelguith Could you try to reproduce it with 1.7.6.x ?

**Comment by khouloudbelguith** [comment] 2019-06-11 11:35
Hi @marionf,

Yes, it is OK.
I tried with PS1.7.6.0beta1 & the PayPal v4.4.6 => ok
https://drive.google.com/file/d/1HPbDxKat9PH4HyGpCqyBBBCNSYlmHtWw/view

I will close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-11 11:35 UTC
Labels: Bug, Minor, FO, Can't reproduce, International, Translations
