### ISSUE TITLE
Can't use translations on module overrides

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#17844] opened 2020-02-26 14:40 UTC
**Describe the bug**
We can't use translations on override files of modules.
According to [this documentation](https://devdocs.prestashop.com/1.7/modules/creation/module-translation/classic-system/#other-classes), we tried with `Module::getInstanceByName('mymodulename')->l()`.

**To Reproduce**
1. Create an override file in a module (inside `override` folder)
2. Add a translation with `Module::getInstanceByName('mymodulename')->l()`
3. The translation doesn't appear in BO

>Edited by Khouloud

1. Override `/ps_facetedsearch/src/Product/SearchProvider.php`
2. Create an override of the module ps_facetesearch in this path `/Project_folder/override/modules/ps_facetedsearch/src/Product/SearchProvider.php`

```
<?php

if (!defined('_PS_VERSION_'))
    exit;
class SearchProviderOverride extends SearchProvider
{

    private function hideUselessFacets(array $facets)
    {
        foreach ($facets as $facet) {
            if ($facet->getWidgetType() === 'slider') {
                $facet->setDisplayed(
                    $facet->getProperty('min') != $facet->getProperty('max')
                );
                continue;
            }

            $usefulFiltersCount = 0;
            foreach ($facet->getFilters() as $filter) {
                if ($filter->getMagnitude() > 0) {
                    ++$usefulFiltersCount;
                }
            }

            $facet->setDisplayed(
                $usefulFiltersCount > 2
            );
        }
        Module::getInstanceByName('Facetedsearch')->l('My text to translate');
    }
}
```
3. Delete the cache manually
4. In the BO => Translation pf the module => I couldn't find this translation

**Additional information**
PrestaShop version: 1.7.x

**Comment by florine2623** [comment] 2020-02-26 14:46
Hello @micka-fdz ,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13392
So, I close it.

**Comment by florine2623** [comment] 2020-02-26 14:47
Duplicate of #13392

**Comment by jf-viguier** [comment] 2020-02-26 15:20
@florine2623 it's not the same, we're talking about class override, not about tpl.

**Comment by micka-fdz** [comment] 2020-02-26 15:24
@florine2623 my issue is about php files (in `override` folder), not template files override in theme... Can you reopen it please?

**Comment by florine2623** [comment] 2020-02-26 15:29
Hello @jf-viguier & @micka-fdz ,

I just reopened the issue.

**Comment by jf-viguier** [comment] 2020-02-26 15:30
A file in override folder is definitely a class override, not a tpl extend. Thanks for reopening.

**Comment by florine2623** [comment] 2020-02-26 15:31
Hi @jf-viguier ,

It is similar to this issue : https://github.com/PrestaShop/PrestaShop/issues/12300 ?

Thanks to check & feedback!

**Comment by jf-viguier** [comment] 2020-02-26 15:38
@florine2623 not at all, : #12300 uses the new translation system $this->trans()
We're talking about the classic one $this->l()

**Comment by florine2623** [comment] 2020-02-26 15:53
Hello @jf-viguier ,

Could you send me the demo module you have created, I will test this on my shop ?

Thanks!

**Comment by jf-viguier** [comment] 2020-02-26 17:16
@florine2623 I don't have any demo module for that, but you can use our module generator in fop_console.

**Comment by micka-fdz** [comment] 2020-02-26 17:59
Or just create a simple override file in any native module.

**Comment by khouloudbelguith** [comment] 2020-02-27 11:41
Hi @micka-fdz, @jf-viguier,

I am trying to override `/ps_facetedsearch/src/Product/SearchProvider.php`
I created an override of the module ps_facetesearch in this path `/Project_folder/override/modules/ps_facetedsearch/src/Product/SearchProvider.php`

```
<?php

if (!defined('_PS_VERSION_'))
    exit;
class SearchProviderOverride extends SearchProvider
{

    private function hideUselessFacets(array $facets)
    {
        foreach ($facets as $facet) {
            if ($facet->getWidgetType() === 'slider') {
                $facet->setDisplayed(
                    $facet->getProperty('min') != $facet->getProperty('max')
                );
                continue;
            }

            $usefulFiltersCount = 0;
            foreach ($facet->getFilters() as $filter) {
                if ($filter->getMagnitude() > 0) {
                    ++$usefulFiltersCount;
                }
            }

            $facet->setDisplayed(
                $usefulFiltersCount > 2
            );
        }
        Module::getInstanceByName('Facetedsearch')->l('My text to translate');
    }
}
```
I deleted the cache manually
In the BO => Translation pf the module => I couldn't find this translation

Can you confirm this?

PS: If I edit the `/ps_facetedsearch/src/Product/SearchProvider.php` directly (without override)
The translation is well displayed
![image](https://user-images.githubusercontent.com/16067358/75441662-5bca3d80-595e-11ea-95cb-9d78219ac0e4.png)

Thanks to check & feedback.

**Comment by micka-fdz** [comment] 2020-02-27 12:58
Yes @khouloudbelguith, the issue is about override in module folder.

**Comment by khouloudbelguith** [comment] 2020-02-27 13:46
@micka-fdz, thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.3 and PS1.7.5.2
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by boy51** [comment] 2020-06-25 15:05
How is this not fixed?

**Comment by eternoendless** [comment] 2020-09-11 08:36
New wordings declared in `overrides` don't show up in the translation interface because only modules and themes can declare new wordings. Wordings don't appear magically in the translation interface, they require static analysis of the source code (aka reading and interpreting code via code), which is terribly slow.

Overrides are meant to progressively disappear as core legacy classes are replaced by services that modules can decorate or replace. As such, I don't think it makes sense to add a "wording discovery" feature there.

If you need to create new wordings and use them in your overrides, just create a simple module containing those wordings. Follow the documentation on [how to make your wordings appear in the translation interface](https://devdocs.prestashop.com/1.7/modules/creation/module-translation/new-system/#making-your-wordings-appear-in-the-translation-interface). Once translated, you'll be able to use them anywhere in PrestaShop (including in overrides), just by getting the translator instance.

Alternatively, you can just create them in the `ps_translations` table. Once the cache is rebuilt they should be available for use.

**Comment by eternoendless** [comment] 2020-09-11 08:39
I'm assuming this bug is about using **new** translations in overrides and closing it as won't fix. Feel free to ping me otherwise.

**Closed as completed** 2020-09-11 08:39 UTC
Labels: Bug, Minor, CO, Won't fix, Modules, Translations, 1.7.5.2, 1.7.6.3

**Comment by jf-viguier** [comment] 2020-09-11 08:54
It's sad. Actually, there is no other way than override for customizing front module behaviors.
