### ISSUE TITLE
Wrong sorting by ID order on BO carts page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25780] opened 2021-09-03 08:12 UTC
#### Describe the bug

When you sort carts by ID order on cart listing page in backoffice, it sorts them wrong, as a string.

#### Current result

Abandoned carts, 99, 98 .... 66, 65, 595, 594...

#### Expected result

595, 594 ... 66, 65, Abandoned carts

Abandoned cart should be taken as a 0 and the column sorted as an int.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2021-09-03 09:05
Hi @Hlavtox,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/21456 to fix the issue.
Your ticket is a duplicate of #21251
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-09-03 09:05
Duplicate of #21251

**Closed as completed by khouloudbelguith** 2021-09-03 09:05 UTC
Labels: Duplicate

**Comment by Hlavtox** [comment] 2021-09-03 09:06
@khouloudbelguith Aaaah, but I really tried to find it! :D
