### ISSUE TITLE
Database not updated on declinations

### ISSUE THREAD

**Issue by Prestadhauc** [PrestaShop/PrestaShop#36031] opened 2024-04-25 15:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm having a problem with the database not connecting to products that are in declination form. And I think this adds another problem on top of that, which is that the "Add to cart" button disappears. The actual stock of my products is 14, 14 and 16 respectively, but none of them are displayed.

### Expected behavior

The quantity is updated and the "add to cart" button appears in the store. The catalog mode is not activated

### Steps to reproduce

![Capture d’écran 2024-04-25 174637](https://github.com/PrestaShop/PrestaShop/assets/167996825/47c87330-a2a4-455d-9b9d-e8c421c71ce6)
![Capture d’écran 2024-04-25 174413](https://github.com/PrestaShop/PrestaShop/assets/167996825/a2f3a3ea-300d-48a0-a23e-1fd3d5ebbe21)
![Capture d’écran 2024-04-25 174556](https://github.com/PrestaShop/PrestaShop/assets/167996825/60cc89b6-06b9-4038-874b-093517fe430d)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

8.7

### If your bug is related to a module, specify its name and its version

i don't now

### Your company or customer's name goes here (if applicable).

ADHAUC

**Comment by florine2623** [comment] 2024-04-26 08:44
Hello @Prestadhauc ,

This is not reproducible on a fresh install.
You must use a PHP version compatible with PS 1.7.8 : max PHP 7.4.
https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/

I'm closing your issue as I can't reproduce it on a fresh install.
Thanks!

**Closed as completed by florine2623** 2024-04-26 08:44 UTC
Labels: Bug
