### ISSUE TITLE
APC Cache TTL not working

### ISSUE THREAD

**Issue by DevSTG** [PrestaShop/PrestaShop#21945] opened 2020-11-17 09:26 UTC
#### Describe the bug

I use CacheApc as my caching system.
No matter what $ttl value I set in $cache->set($cacheId, $result, $ttl) method cached result is stored for about a minute.
I wrote a module to test APC:

```
class Mymodule extends Module {
...
    public function hookDisplayTop() {
	$this->context->smarty->assign(array(
            'result' => self::testCacheTtl(),
	));
        return $this->display(__FILE__, 'views/templates/front/cache.tpl');
    }
	
   private static function testCacheTtl() {
	$ttl = 0;
        $cacheId = "testCacheTtl";
	$cache = Cache::getInstance();
        if (!$cache->exists($cacheId)) {
            $result = date("Y-m-d H:i");
	    $cache->set($cacheId, $result, $ttl);
            return $result;
        }
        return $cache->get($cacheId);
    }
}
```
and it always displays time value >= 1 minute past.
See: https://sukcesgroup.pl/sklepnowy/pl/kontakt
Here are my APC settings: https://sukcesgroup.pl/sklepnowy/apc.png

#### Expected behavior

APC storing values for given ttl value

#### Steps to Reproduce

Enable APC caching, try to store and restore some values

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 5.6.38

**Comment by hibatallahAouadni** [comment] 2020-11-17 10:34
Hello @DevSTG 

> I set in $cache->set($cacheId, $result, $ttl)

Where excatly did you set the $ttl value, in which class or controller?

Thanks!

**Comment by DevSTG** [comment] 2020-11-17 13:19
I set $ttl value in my module class (see method Mymodule::testCacheTtl() in code that I included) and tried to display it using displayTop hook (hookDisplayTop() method above).
If I'm not mistaken Cache is a singleton, so it doesn't really matter when I use it ...

**Comment by hibatallahAouadni** [comment] 2020-11-17 16:35
Hello @DevSTG 

As you can see in the screenshot below my APC settings:

![image](https://user-images.githubusercontent.com/23308427/99414002-a9c11000-28f6-11eb-8658-04c067625e75.png)

And in my BO, I enabled the **Use Cache** option and choose **CacheApc**:

![image](https://user-images.githubusercontent.com/23308427/99414124-cbba9280-28f6-11eb-9f09-19833449bfb0.png)

And as you explained to me I add the code in a module. And yet, I couldn't manage to reproduce your issue with PS1.7.6.8.
Could you please provide more info.

Thanks!

**Comment by DevSTG** [comment] 2020-11-18 07:05
What additional info would you need?

**Comment by hibatallahAouadni** [comment] 2020-11-18 09:04
Ping @PrestaShop/prestashop-core-developers what do you think of this problem?

**Comment by PierreRambaud** [comment] 2020-11-18 15:58
@hibatallahAouadni Are you able to reproduce, we need to be sure the problem come from the PrestaShop core and not the APC/APCU configuration :)

**Comment by hibatallahAouadni** [comment] 2020-11-18 16:13
@PierreRambaud I didn't manage to reproduce the issue

**Comment by DevSTG** [comment] 2020-11-20 09:46
@hibatallahAouadni did you try to reproduce th issue on PHP version: 5.6.x ?

**Comment by PierreRambaud** [comment] 2020-11-23 08:58
> @hibatallahAouadni did you try to reproduce th issue on PHP version: 5.6.x ?

We are not supporting PHP 5.6 anymore.

**Comment by DevSTG** [comment] 2020-11-23 09:43
It's quite important news, I think I shouldn't be able to install PS if my PHP version is not supported.
Anyway, can you confirm PHP version affects APC cache?

**Comment by PierreRambaud** [comment] 2020-11-23 09:50
@DevNet Here's the [PHP Compatibility Chart](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).
I'm not able to reproduce the problem with the latest PHP version. Unfortunately, we will not spend time testing all PrestaShop versions with old PHP versions if everything is working well on latest releases :)

**Comment by DevSTG** [comment] 2020-11-23 10:04
@PierreRambaud The chart you provided suggests that my PS version 1.7.6.x seems to be ok with my PHP version 5.6.x, so maybe the chart should be updated?

**Comment by PierreRambaud** [comment] 2020-11-23 10:31
> @PierreRambaud The chart you provided suggests that my PS version 1.7.6.x seems to be ok with my PHP version 5.6.x, so maybe the chart should be updated?

Not it is, but we are now working on 1.7.7.x and develop branches only. There will be no update on 1.7.6.x branch.

**Comment by hibatallahAouadni** [comment] 2020-12-26 13:28
Hello @DevSTG 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-26 13:28 UTC
Labels: Bug, BO, Can't reproduce, Performance, 1.7.6.8
