### ISSUE TITLE
Countries & Carriers Restrictions  - Payment preferences

### ISSUE THREAD

**Issue by cgascard** [PrestaShop/PrestaShop#10995] opened 2018-10-12 17:08 UTC
**Describe the bug**
Countries and carriers restrictions in payment preferences doesn't work.

**To Reproduce**
Side back-office
Click on 'Payment and "preferences " 
Check 2 payment modes (bank transfer and bank check) in currencies restrictions
Select group customers for these payment modes 
Check bank transfer and uncheck bank check for France for example

Side Front-office, create account with French address
Both payments modes appear

Same problem with carriers resctrictions. 

**I tested :**
- currency restrictions (ok)
- Group restristrions (ok)
- countries restrictions (doesn't work)
- Carriers restrictions (doesn't work)

**Environment :**
Multi-shop (2)
PrestaShop version: 1.7.4.2
PHP version: 7.0.31
I use bank transfer + bank check addons

Thanks for your help!

**Comment by khouloudbelguith** [comment] 2018-10-15 11:02
Hi @cgascard,

I did not manage to reproduce the issue with PS 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/16N3DMHP79jO6UxM7S-PUWZD9AOS4z23v/view
Thanks to check & feedback.

**Comment by cgascard** [comment] 2018-10-15 12:14
Hi @khouloudbelguith 
I don't understand why my shop's reacting same that. I going to check if the problem isn't in the theme.
Have you other search suggestions after my currencies problem  in the same page? 
Carine

**Comment by khouloudbelguith** [comment] 2018-10-15 13:04
@cgascard, if you enable the debug mode, is there any exception displayed?
You can check also the file error log.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by cgascard** [comment] 2018-10-24 07:40
Yes the debug is enable but i haven't got exception display. 
I tried to install the theme on a clean prestashop, the problem doesn't come of there.
Then, I imported again the countries and states. Also I desinstalled whith delete and reinstalled the "check bank" and "tranfer bank" modules. the bug continue....

**Comment by cgascard** [comment] 2018-10-24 08:15
Hi again, 
I disabled debug mode and country payment restrictions work!
So, there is probably a problem with this function, but there's no error message on the BO or in the server logs.

**Comment by khouloudbelguith** [comment] 2018-10-24 09:18
Hi @cgascard,

If you use the default theme provide by Prestashop & the debug mode is enabled, the bug continue?
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-27 16:41
Hi @cgascard,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-27 16:41 UTC
Labels: FO, Payment preferences, No change required, 1.7.4.2
