### ISSUE TITLE
[BO] Multistore - PPV2 : Problem of Managing Product Combinations

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#30839] opened 2023-01-12 15:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The updats of **managing product cobinations** cannot be saved because when clicking on `save` button it still loading.

![image](https://user-images.githubusercontent.com/111756615/212097119-fc6410af-0a71-43ef-90e6-29e2ba7ba11b.png)

### Expected behavior

The updates will be saved after clicking the `save` button.

### Steps to reproduce

1. Go to BO>General>Preferences
2. Enable Multistore **`YES`**
3. Create a new store
4. Go to BO>Advanced Parameters>New & Experimental Features
5. Enable New product page - Multi store
6. Go to BO>Catalog>Products>Product with combinations
7. Go to combinations>Generate combinations
8. Edit  `Reference | Impact on price (tax excl.) | Impact on price (tax incl.) | Final price (tax excl.) | Quantity`
9. Save
:warning: **See Error** The table still loading without saving 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4 & 8.1

**Comment by sallemiines** [comment] 2023-01-13 13:12
Hello @MhiriFaten 

Thanx for reporting the issue.

I reproduce your issue with

 **develop** **NOK** 

https://user-images.githubusercontent.com/31663369/212308287-251eed96-4532-452b-8659-3db2de05492e.mp4

**PS 8.0.x , PS 8.0.0 & PS 8.0.1** **OK**

![Capture-d’écran-de-2023-01-13-14-06-33-png-3840×1080-](https://user-images.githubusercontent.com/31663369/212327115-be5e2312-35b3-4404-9090-5b11c12fd2b2.png)

Nice catch ! It's a regression ! I'll add it to the patch backlog.
Thank you for your PR :rocket:

**Comment by jolelievre** [comment] 2023-02-03 16:36
FYI seems like the same bug was reproduced while testing the feature flag PR https://github.com/PrestaShop/PrestaShop/pull/31130#pullrequestreview-1283003290
So the bug is probably still present in 8.1.x

**Comment by zuk3975** [comment] 2023-02-10 12:25
Should be fixed by this https://github.com/PrestaShop/PrestaShop/pull/31296/files#diff-b4375039bc10e7623bc779b2817dc03ee049fc8d049ee5ee21c57ee0ab76e347R221-R225

**Comment by MatShir** [comment] 2023-03-16 16:11
seems to be fixed :)

**Comment by florine2623** [comment] 2023-03-27 15:34
Tested on `8.1.x` and `develop`.

It is fixed, I can't reproduce the issue.

I close this issue :)

**Closed as completed by florine2623** 2023-03-27 15:34 UTC
Labels: Bug, Minor, BO, Regression, Combinations, Fixed, Verified, 8.1.x
