### ISSUE TITLE
prestashop création incomplete charge for stripe

### ISSUE THREAD

**Issue by elviraprint** [PrestaShop/PrestaShop#15794] opened 2019-10-02 11:28 UTC
hi,

this is what stripe told me :
"I had a look at the incomplete charges on the account and I can see that prestashop are creating the charges for Stripe to process on your behalf.
So I would suggest to get in touch with prestashop directly to help you resolve this issue."

can you fix it ?

**Comment by khouloudbelguith** [comment] 2019-10-02 11:34
Hi @elviraprint,

Could you please provide us the exact steps to reproduce the issue in a new comment & some information about your configuration: PrestaShop version, PHP version,...?

Thanks!

**Comment by elviraprint** [comment] 2019-10-02 11:49
the customer wants to order a product,
he choose it and add it to the cart
for the paiement he got choice between stripe and PayPal
he choose stripe
when he add the credit card number and press pay,
nothing happen the paiement is still processing, processing, processing...
or they can't pay and I don't receive the paiement
or they can't pay (error message) but I receive the paiement
I got both case
so this is what stripe told me : "I had a look at the incomplete charges on the account and I can see that prestashop are creating the charges for Stripe to process on your behalf.
So I would suggest to get in touch with prestashop directly to help you resolve this issue."
>[EDited by Khouloud]

Serveur / Host:
access771285746.webspace-data.io
Port: 22
Protocole: SFTP


prestashop version : 1.7.5.0
php : 7.2

please help me

**Comment by khouloudbelguith** [comment] 2019-10-02 12:36
@elviraprint, 
This is a public space.
I deleted the credentials from your comment.
Let's be safe!

**Comment by elviraprint** [comment] 2019-10-02 12:48
oh my god thanks a lot !

then do you need other details or my request is clear ? whats should I do ?

**Comment by khouloudbelguith** [comment] 2019-10-02 13:05
@elviraprint, I did not manage to reproduce the issue with PS1.7.6.1 & Stipr module v2.5.0.
I attached a screen record
https://drive.google.com/file/d/1nIGNWP6DhaV02NCKonU0CfESkmMLw7oO/view
Thanks to check & feedback.

**Comment by elviraprint** [comment] 2019-10-02 13:12
Thanks god I know how to do an order !

I m telling you that prestashop creating charges for stripe to process that’s why all the paiement become incomplete

**Comment by khouloudbelguith** [comment] 2019-10-02 13:22
@elviraprint, this issue is random?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by elviraprint** [comment] 2019-10-02 13:43
Random ???
I get this email maybe more than 1000 time each days and no one either stripe module or stripe themselves can find out whats wrong they don’t help me at all !!!

I got an error 404 who makes the paiement incomplete ! People loose confidence in my website cause of that, and nobody gives me answer thats the worst
I don’t even know how to do even I told this error 1000 time at prestashop stripe module or stripe

Its happening each day mme

I got a huge problem there please help me
I did everything everybody asks me, upload new version same problem

**Comment by khouloudbelguith** [comment] 2019-10-02 13:50
@elviraprint, any error log files or debug mode report can help us to find what's wrong?

Thanks!

**Comment by elviraprint** [comment] 2019-10-02 14:17
Is that what you need ?
They told me that the 404 error is on this but I don’t understand do you ?

**Comment by khouloudbelguith** [comment] 2019-10-02 15:16
@elviraprint, this error 404 is very frustrating because it is such a vague error.
So, we need php error log & debug mode report to find what's wrong.

Thanks!

**Comment by elviraprint** [comment] 2019-10-02 15:28
Ok where do I find that ?
Can you do it ?

**Comment by khouloudbelguith** [comment] 2019-10-02 15:29
@elviraprint, Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

**Comment by elviraprint** [comment] 2019-10-04 16:20
hi
Since I gave you the code and ask to have a look on the website everything goes incorrect look the error I got !

Dinde have that 2 days ago and a lot of new module have been download without my permission !

Anyway what do I do with that ?

You add a product on the cart
And thats whats you see on the cart page ?????
Please
thanks

**Comment by khouloudbelguith** [comment] 2019-10-07 09:00
@elviraprint, you provide me the link & the access with the insecurity way, in a public space.
So, I deleted the credentials for your safety but you must change those credentials immediately because it is not me who downloads those modules. 
You can provide me for example by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks for your understanding!

**Comment by elviraprint** [comment] 2019-10-07 10:01
Ok thanks you I send it to you on you email,

Thanks again !

**Comment by khouloudbelguith** [comment] 2019-10-07 12:04
@elviraprint, this issue provided in the email occurs due to the `customfields` module.
<img width="320" alt="Capture d’écran 2019-10-04 à 18 18 29" src="https://user-images.githubusercontent.com/16067358/66309983-4c911780-e90b-11e9-8cbf-2529d16c99da.png">
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by elviraprint** [comment] 2019-10-07 12:59
Ok thanks a lot you really helped me

I deleted the module and everything seems to go well right now
Thanks again :))

**Comment by khouloudbelguith** [comment] 2019-10-07 13:09
@elviraprint, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-07 13:09 UTC
Labels: No change required, 1.7.5.0
