### ISSUE TITLE
403 Error after Deleting Product Images

### ISSUE THREAD

**Issue by OguzhanLevent** [PrestaShop/PrestaShop#32198] opened 2023-04-18 11:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I'm not sure if this is a mistake or if this is how the system works, but I would like to share some of my experiences and get some information.

In previous versions, we made changes to our product images and Google Search Console informed us that the url addresses of the old images gave 403 errors.

Since there are a lot of edits in the version I mentioned, I thought that there might be such a situation due to a mistake we made until we updated our Prestashop version to 1.7.8.8.

We will make visual changes in almost all of our products. I tested this situation yesterday to check and observed that it is still the same. If you delete any image from a product, the url address of that image now starts to give 403.

For example; domain.com/1234-large_default/shoes.jpg

This is especially dangerous for your ranked images. If one of your images is indexed in any search engine such as Google, when robots visit the address again and cannot reach it, they will lose you in the rankings.

Is this a bug or a feature that works perfectly fine? If it is a feature, how can we prevent ranking losses other than 301 redirects.

### Steps to reproduce

1. Visit any product
2. Open a photo of the product in a new tab
3. Find the product in the back office and delete the selected image
4. Refresh the image you opened in a new tab
5. You will see a 403 Error

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment] 2023-04-18 14:38
@OguzhanLevent I think you are a bit confused.

- URL `domain.com/1234-large_default/shoes.jpg` is an URL of an image, not a product.
- That number in the URL is the ID of the product image in the system.
- If you delete the image (and upload a new one for example), the old image URL should return 404 error.

------------------------

But, I thought about the issue and I tested it. On the new product page that is coming in Prestashop 8.1, you should be able to replace the product image and keep it's ID = keep it's ranking. 👍

**Comment by OguzhanLevent** [comment] 2023-04-19 06:43
Hello @Hlavtox 

Sorry for the misunderstanding, it has to do with the language barrier. What I wanted to say is not the URL address of the product, but the URL address of the image of the product instead. If you delete an image and then try to visit the URL, it gives you 403.

For some users it is not possible to update, and we are one of those users, I was hoping that you could enlighten me about this situation, so that way I can fix it myself.

I hope this was clearer.

**Comment by AureRita** [comment] 2023-04-20 10:25
Hi @OguzhanLevent 

Thank you for your report, I tried your issue and I reproduced it as you can see : 

[Untitled_ Apr 20, 2023 12_20 PM.webm](https://user-images.githubusercontent.com/100699445/233338277-f56ed085-cbc4-45bf-a742-4724e95abd8f.webm)

But, currently it's a normal feature because when you delete your images, it's deleted in your folder, so the url takes you to a non-existent link 

Because this one is a normal feature, I'll close it

Thank you

**Closed as completed by AureRita** 2023-04-20 10:25 UTC
Labels: Bug, Invalid
