### ISSUE TITLE
Issue with text editors

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#10738] opened 2018-09-27 11:49 UTC
**Describe the bug**
There is something wrong with text editors on multiple pages, see Brands for example here https://prnt.sc/kzcjnb

**To Reproduce**
Open Brands page.

**Screenshots**
n/a

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-09-27 12:22
Hi @

Here's the PR: #10462 to solve the issue.
Your ticket is a duplicate of #10461
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-27 12:23
Duplicate of #10461

**Closed as completed by khouloudbelguith** 2018-09-27 12:23 UTC
Labels: Duplicate
