### ISSUE TITLE
Cannot create Variations | change not saved

### ISSUE THREAD

**Issue by BullyBlue** [PrestaShop/PrestaShop#26499] opened 2021-11-02 07:48 UTC
Dear Community,

I am currently losing my mind. I reinstalled this shop the 5th time now - and again an error occured. I googled and checked all forums but could not find the same issue / relatable issues but no solution.

Host: Strato
PHP: 7.3
website: bullyblue.de
Prestashop: 1.7.7.8 
Used Theme: Osome (i think the issue might be in modules from that theme - but idk how to find out)

**Problem:** I cannot create / change any variations 
**Error:** Changes could not be saved
![grafik](https://user-images.githubusercontent.com/93530349/139805887-b48d5010-f479-4684-bd83-9e2516077750.png)

When I installed the shop i tried an article with variation and it worked - but now i cannot even change that combinations.

Tries to solve the issue: →cleared cache manually

I am working in Debugging Mode - but it does not show me fatal errors

If you need further information let me know - I appreciate any help, since I am new to this topic at all.

**Comment by florine2623** [comment] 2021-11-02 09:36
Hello @BullyBlue ,

First, please change your admin folder name for security reasons, this is a public platform.

I couldn't reproduce your issue, as you can see per my screen record video : 
https://watch.screencastify.com/v/vXHKD4748976ZG7O8dY7
<img width="266" alt="Screenshot 2021-11-02 at 10 36 09" src="https://user-images.githubusercontent.com/16019289/139822094-f5b5f442-dfed-474f-b165-9ef0cb082671.png">

Please make sure your shop is compatible with all system requirements. Here the link for more information :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please check and feedback.
Thanks!

**Comment by BullyBlue** [comment] 2021-11-02 10:01
Hello @florine2623,
thanks for your reply !

I might be doing something wrong - but the link to check the requirements doesnt work somehow.
I uploaded it to another domain using the same server - but it does not accept the password.
Feel free to check [Here](http://kästnerdoreen.de/phppsinfo.php)

Since I could create combinations when freshly installed - I dont feel there is an issue with the requirements.
All I did after the installing was
→ download paypal modul (not configured yet)
→ use theme → deactivate 80% of modules of theme
→ changed the Tab file since an error occured 
→ started debug mode
→ deleted cache a few times

current situation:
→ can create a "normal" article without any issues
→ ´looks like the first combination can be created but not edited - not even the quantitiy - nor the picture - nor create any other variant
→ i can not change created combinations of other existing products

Best regards and thank you !

**Comment by florine2623** [comment] 2021-11-02 10:39
That's strange indeed.
For the system requirements info, could you try to put this file directly in your shop folder ?
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/7459842/phppsinfo.php.zip)

I tested on my shop and the link works correctly with login and password `prestashop`

On my test shop :
- I installed Paypal module (con configuration)
- I added a file in Option Tab
<img width="806" alt="Screenshot 2021-11-02 at 11 35 40" src="https://user-images.githubusercontent.com/16019289/139831104-8ee7bc30-dee1-4111-a641-a6ff40b05759.png">

- I'm still using classic template

And cannot reproduce your issue. You might need to contact the developer of the template to see if the issue comes from there.

**Comment by BullyBlue** [comment] 2021-11-02 18:36
Dear @florine2623,
I uploaded the file directly to the shop - still it does not work
Feel free to test yourself [Here](http://bullyblue.de/phppsinfo.php)

I activated the classic theme → still no success 
only thing i can see in debugger is:

POST | xhr | 500 - /index.php/sell/catalog/products/
might there be any issue?

Thanks in advance

**Comment by BullyBlue** [comment] 2021-11-03 08:27
Since I am still trying to find something

I found out the following:
→ I can create 1 combination
→ but i cant give that combination any quantity or other settings
→ cant create more variants
→ The existing article with variants cannot be changed or deactivated

**Comment by khouloudbelguith** [comment] 2021-11-03 14:31
Hi @BullyBlue,

What is the exact language of the employee?
I think it is the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/25797
Can you please confirm?

Thanks!

**Comment by BullyBlue** [comment] 2021-11-03 16:31
Hi @khouloudbelguith,

thanks for the hint.
My employee language is german - i did not change that after installing at all.
![grafik](https://user-images.githubusercontent.com/93530349/140102441-07bc1ddd-0dcb-4f90-bd1e-81b247a38ac6.png)

Looks close to the issue but not the same...
Since i could create combinations once...yet I am not able to.

Thank you and regards !

**Comment by khouloudbelguith** [comment] 2021-11-03 17:10
@BullyBlue, I manage to reproduce the issue with PS1778 when the debug mode = enabled 
https://watch.screencastify.com/v/uQ7sCMTBZTtdWX8ZqZdV
Your ticket is a duplicate of #25797
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-11-03 17:10
Duplicate of #25797

**Closed as completed by khouloudbelguith** 2021-11-03 17:10 UTC
Labels: Bug, BO, Duplicate, Combinations, 1.7.7.8, Invalid

**Comment by BullyBlue** [comment] 2021-11-03 20:01
Hello @khouloudbelguith !
You saved my day - if i just knew it was that easy. Thank you so much !
