### ISSUE TITLE
Email template error: payment for transfer, order from the back end, variables not replaced

### ISSUE THREAD

**Issue by javierVP** [PrestaShop/PrestaShop#20120] opened 2020-07-09 10:59 UTC
When I make an order from the back end when choosing the bank transfer payment method, the mail comes to me well but the payment data is not shown, but the variables are shown.
I leave a screenshot so you can see what I mean.

PrestaShop 1.7.6.5
Php 7.2
![Captura de pantalla 2020-07-09 a las 12 56 29](https://user-images.githubusercontent.com/42347565/87031838-f0ce2480-c1e3-11ea-98ae-8bac0d6c1870.png)

**Comment by florine2623** [comment] 2020-07-09 12:44
Hi @javierVP ,

I can't reproduce your issue on my test shop.
Can you check your log file in /var/log ?

Thanks!

**Comment by javierVP** [comment] 2020-07-10 09:52
What file?

**Comment by javierVP** [comment] 2020-07-10 09:54
I can't find anything related to it

**Comment by florine2623** [comment] 2020-07-10 14:47
The log file located in directory /var/log from your FTP

**Comment by javierVP** [comment] 2020-07-11 10:59
It does not reflect anything about the mentioned error.

**Comment by matks** [comment] 2020-07-13 15:10
Hi @javierVP I just did a test on a fresh install of PS 1.7.6.7 (it's 99% the same code as 1.7.6.6 so no difference should be observed for your case), the email I receive is good. See (in French):

![Capture d’écran 2020-07-13 à 17 09 05](https://user-images.githubusercontent.com/3830050/87320762-9b6b7d80-c52b-11ea-9b73-daf4c740ef46.png)

Maybe your email templates have been customized / modified and the variable names have been changed ? On my side I cannot reproduce the behavior you observe.

**Comment by javierVP** [comment] 2020-07-14 08:56
A new installation was installed and only the products were migrated, so it is strange that placing the order from the back end does not leave the data in the mail.
No email template was customized.
From the front when ordering if the data arrives correctly.
I will review the templates again but I do not see anything strange.

**Comment by khouloudbelguith** [comment] 2020-07-14 09:29
Hi @javierVP,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1ct3FRyWxA6MbTFTDCXvB0JyRrGQSwQOu/view?usp=sharing
Tanks to check this [comment](https://github.com/PrestaShop/PrestaShop/issues/16741#issuecomment-649552260), it could be a solution.

Thanks!

**Comment by matks** [comment] 2020-07-15 07:51
By the way it seems to be a duplicate of https://github.com/PrestaShop/PrestaShop/issues/16741

**Comment by prestascott** [comment] 2020-07-15 09:26
Hi @javierVP,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16741. To be informed when it's fixed, please subscribe to the issue mentioned above.

I close the ticket.

Thank you!

**Comment by prestascott** [comment] 2020-07-15 09:27
Duplicate of #16741

**Closed as completed** 2020-07-15 09:28 UTC
Labels: Bug, Duplicate, Email, Bankwire, 1.7.6.5
