### ISSUE TITLE
Gift message bug if clicking fast

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26044] opened 2021-10-01 08:49 UTC
#### Steps to Reproduce

1. Enable gift wrapping.
2. Add something to cart, go to checkout, delivery step.
3. Click on gift wrapping checkbox very fast and you can get it to a state where the checkbox is checked, but the gift message is hidden, or reverse.

**Screenshots**

![ezgif-6-75155786c09b](https://user-images.githubusercontent.com/6097524/135592404-278b58c0-a06e-4d11-98bc-08671c79e4ce.gif)

**Related code**
https://github.com/PrestaShop/PrestaShop/blob/ad181f7fb89dea67dfebba779a6440854baa6d5b/themes/classic/_dev/js/checkout.js#L48

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

**Comment by khouloudbelguith** [comment] 2021-10-01 10:07
Hi @Hlavtox,

I manage to reproduce the issue with PS1769, PS1778, PS1771, develop branch
![image](https://user-images.githubusercontent.com/16067358/135602320-fa58f95f-142f-49f6-ba78-2c7926f76f24.png)
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Closed as completed** 2021-10-27 06:11 UTC
Labels: Bug, Trivial, FO, Order settings, Fixed, Checkout, PR available, 1.7.6.9
