### ISSUE TITLE
Reordering products in category only works a specific way

### ISSUE THREAD

**Issue by mrl22** [PrestaShop/PrestaShop#22915] opened 2021-01-20 13:18 UTC
#### Describe the bug

When reordering products in a category, it will not save if you drag the row. If you drag the up/down icon it works perfectly.

At first, when our client reported the issue, we thought that it was specific to them as I could not reproduce (I was dragging the up/down arrow icon).

#### Expected behaviour

It should save the category order as it was dragged regardless of where you drag.
Or just make the up/down arrow icon draggable and add an explanation of how to drag.

#### Steps to Reproduce

Steps to reproduce the behaviour:

1. Go to Admin -> Catalog -> Products
2. Filter by a specific category
3. Click the reorder button.
4. Drag a product up or down (do not tick any boxes and do not drag by the up/down icon or order number on the right)
5. When clicking Save order, the page will refresh in their original order and not the dragged order.

Not sure if related: I have found that when dragging the up/down arrow icon on the right while dragging, it ticks the product. When dragging the row (drag any other column) it does not tick the product.

**Screenshots**

[Dragging a product from anywhere on the row (does not save)](https://www.dropbox.com/s/ahqrxgapo7nrluq/screen-recorder-wed-jan-20-2021-13-10-13.webm?dl=0)

[Dragging a product from the up/down arrow icon (does save)](https://www.dropbox.com/s/0rroq2nhxyiooei/screen-recorder-wed-jan-20-2021-13-10-36.webm?dl=0)

#### Additional information

I have found this thread where people are discussing this issue as early as 1.7.5
https://www.prestashop.com/forums/topic/954698-175-product-position-within-category-not-working/

* PrestaShop version: 1.7.7.0
* PHP version:  7.1

**Comment by hibatallahAouadni** [comment] 2021-01-20 15:59
Hello @mrl22 

Could you please check this issue #15291 cause it seems similar to yours.
Please check and feddback.

Thanks!

**Comment by mrl22** [comment] 2021-01-20 16:02
Yes, #15291 seems to be the same issue, I did try to find people with the same issue before posting.

**Comment by mrl22** [comment] 2021-01-20 16:06
Duplicate of #15291

**Comment by hibatallahAouadni** [comment] 2021-01-20 16:07
Hello @mrl22 

It's OK :sweat_smile: Thanks for your feedback :wink: 

As you can see we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15291. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-20 16:07
Duplicate of #15291

**Closed as completed by hibatallahAouadni** 2021-01-20 16:07 UTC
Labels: Bug, BO, Duplicate, Categories, 1.7.7.0
