### ISSUE TITLE
Remove Customization from product unexpected error

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#35590] opened 2024-03-08 14:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When i want to remove a product customization, and save the product. It gives me the following error:
`An unexpected error occurred. [PrestaShop\PrestaShop\Core\Exception\CoreException code 0]: Error occurred when trying to soft delete CustomizationField #1 [Field "deleted" is missing from definition in object model CustomizationField]`

Table: customization_field doesn't have a field called: `'deleted'`, but has: `'is_deleted'`

See attached video.

https://github.com/PrestaShop/PrestaShop/assets/533123/897aff17-e763-4752-b79f-bb3abe679aa7

### Expected behavior

Removing the customization from product without errors.

### Steps to reproduce

1. add product
2. add product customization
3. save product
4. delete product customization

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1.27

**Comment by florine2623** [comment] 2024-03-08 16:03
Hello @sharkooon ,

I can't reproduce your issue on PS 8.1.x as you can see from my screen record :

https://github.com/PrestaShop/PrestaShop/assets/16019289/d85bf1df-8008-4421-89ef-9f0115e4d170

I'm closing the issue as it cannot be reproduced.
Thanks!

**Closed as completed by florine2623** 2024-03-08 16:03 UTC
Labels: Bug
