### ISSUE TITLE
Lost special characters utf8 on update  1.6.1.21 to 1.7.4.3

### ISSUE THREAD

**Issue by iDanielBH** [PrestaShop/PrestaShop#10855] opened 2018-10-04 11:28 UTC
I had the database configured as utf8_general_ci, the files as utf8. The configuration in php.ini and apache, all in utf8.

After updating from 1.6.1.21 to 1.7.4.3 I have lost the special characters of many tables. After investing a lot of time i have solved it by personalizing the update file.

Removing the line:

/ * PHP: latin1_database_to_utf8 (); * /;

In /prestashop/install/upgrade/sql/1.0.0.1.sql

After this I have executed the update and everything is correct.

**Comment by khouloudbelguith** [comment] 2018-10-04 12:24
Hi @iDanielBH, thanks for your fix suggestion.
@Quetzacoalt91 what do you think??

**Comment by Quetzacoalt91** [comment] 2018-10-04 12:58
Well, the actual issue is totally different from what you could expect from the description.

When an upgrade is done between PrestaShop 1.6.1.21 and 1.7.4.3, only the sql files in this version range are supposed to be run.
The file 1.0.0.1.sql wasn't supposed to be executed. If you still have the database backup before the upgrade, I'd like to know what are the VERSION registered in your configuration table.

**Comment by iDanielBH** [comment] 2018-10-04 13:59
Where do I find the configuration table? "Ps_configuration"? and if so, in what value is the VERSION registered

**Comment by Quetzacoalt91** [comment] 2018-10-04 15:17
Exactly, in the ps_configuration table.

I ran this request to get the installation version:

```sql
SELECT * FROM `ps_configuration` WHERE `name` LIKE '%VERSION%' 
```

**Comment by iDanielBH** [comment] 2018-10-04 15:34
Only returns PS_LAST_VERSION_CHECK

I come to update from a version 1.3.2.3 and in the copy of the database of 1.4.0.17 that query does not return anything, and in 1.5.0.17 either.

In other words, that parameter did not exist and has never been created automatically in the database.

**Comment by Quetzacoalt91** [comment] 2018-10-04 16:40
That's interesting, thanks for the feedback. This could explain why I get this kind of report.

How did you make the previous upgrades? With the 1-click upgrade module?

**Comment by iDanielBH** [comment] 2018-10-04 17:04
From v1.3.2.3 to v1.4.11.1 manually. As of v1.4.11.1 with 1-click upgrade module.

Thanks for the help.

I'm going to add the field PS_VERSION_DB manually in the database and to update everything again. Just in case it solves other problems.

**Comment by florine2623** [comment] 2021-03-19 15:35
Hello,

After upgrading from 1.6.1.21 to 1.6.1.24 and from 1.6.1.24 to 1.7.4.3, I couldn't reproduce your issue :
![Capture d’écran 2021-03-19 à 15 40 01](https://user-images.githubusercontent.com/16019289/111805129-0ba77b80-88d1-11eb-9919-e94567da5285.png)
![Capture d’écran 2021-03-19 à 15 52 33](https://user-images.githubusercontent.com/16019289/111805137-0ea26c00-88d1-11eb-8ec6-6588d0657435.png)

So I close it.

Thanks!

**Closed as completed by florine2623** 2021-03-19 15:35 UTC
Labels: Bug, CO, Can't reproduce, Autoupgrade, 1.7.4.3
