### ISSUE TITLE
Backoffice-created customer does not get his password

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22646] opened 2021-01-03 23:54 UTC
#### Is your feature request related to a problem?

When you create a registered customer from BO, he does not get his password sent in the email. How does he know the password, unless you send him an extra email or call him?

#### Describe the solution you'd like

Sending the password in plain text is not very safe, so what about putting a link to change the password in 'account' template?

**Comment by hibatallahAouadni** [comment] 2021-01-04 08:31
Hello @Hlavtox 

It seems a bit similar to this issue #17097
Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , I think @Hlavtox got a point, cause when we create a client from BO the client doesn't get any notification about the new account created. So, do you agree about adding this feature?

**Comment by MatShir** [comment] 2021-01-12 20:29
You are right! 
The merchant shouldn't enter the password for their customer, even though it seems easy way to create a account for the customer. 
The password field should be change to a warning message saying that an email with the link is sent to the registered email.

**Comment by Hlavtox** [comment] 2021-01-13 12:48
@MatShir @hibatallahAouadni In 1.6 times, when you created a customer, he got the password sent in _account_ email.

Then, it got removed for security purposes, because it is not good if passwords are just revealed as plain text. But, now he does not know the password, unless he goes through a password recovery.

I think that the customer should receive a link to create a new password in the account email. He will click it and it will show him a form to create his first password.

Now, what if he tries to log in in FO? Do we show him a new-password creation form, only by just entering his email?

**Comment by hibatallahAouadni** [comment] 2021-01-13 14:35
> Now, what if he tries to log in in FO? Do we show him a new-password creation form, only by just entering his email?

That's a good question and needs specs :wink: 
Ping @PrestaShop/product-team can someone please answer @Hlavtox question, thanks in advance :slightly_smiling_face:

**Comment by LouiseBonnard** [comment] 2021-01-13 15:16
... and I'm afraid it is not yet specified, aha! But thanks for the reminder, @hibatallahAouadni. ;-)

@Hlavtox, I've suggested a solution in https://github.com/PrestaShop/PrestaShop/issues/21887, I think your issue is a duplicate. If you confirm, I'll specify it right away and close this issue as a duplicate of https://github.com/PrestaShop/PrestaShop/issues/21887, thank you very much!

**Comment by Hlavtox** [comment] 2021-01-13 15:18
Yes @LouiseBonnard, it's the same, you can close this. :-)

**Closed as completed** 2021-01-13 15:19 UTC
Labels: PM ✔️, Feature, BO, Duplicate, Customer, Email, 1.7.7.0

**Comment by hibatallahAouadni** [comment] 2021-01-13 15:37
Duplicate of #21887
