### ISSUE TITLE
FO - Wishlist button is blocked in the list of products attached to the brand page in FO

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26755] opened 2021-11-25 15:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the list of products by a specific brand, when clicking in the Wishlist button, no pop-up is displayed to can add to whishlist. 

See the attached screen-record below : 
https://watch.screencastify.com/v/XmRcfMMJnVfqCvmdf9SJ

### Expected behavior

The wishlist button works correctly on every page in FO and the pop-up to add to Wishlist is well displayed.

### Steps to reproduce

1. FO > HOME
2. Click to an product to see its details
3. Go to Product Details 
4. Click on the logo > The ' List of products by brand ' is well displayed
5. Click on the wishlist of an product of the specific brand
5. See Error > The wishlist button is not functional

### PrestaShop version(s) where the bug happened

1.7.8.1 & 1.7.8.x

### PHP version(s) where the bug happened

7.3

**Comment by NeOMakinG** [comment] 2022-01-05 14:16
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/26853

**Closed as completed by NeOMakinG** 2022-01-05 14:16 UTC
Labels: Bug, Minor, FO, Needs Specs, Blockwishlist, 1.7.7.8, Verified, Module
