### ISSUE TITLE
Wrong price calculation when discounts

### ISSUE THREAD

**Issue by josiasdx** [PrestaShop/PrestaShop#21020] opened 2020-09-16 14:25 UTC
Shop parameters/configuration 
-> round type: round on each line
-> round mode: round up away from zero, when it is half way there

Taxes: 21.00

Catalog/products-> new product:
Product price (tax excluded): 282,96€
Discount: 30%

Expected result
--------------------
282,96€-30%= 198,072€ -> (round on each line) 198,07€ + 21%= **239,66€**

Prestashop result
-----------------------
**239,67€** (instead 239,66€)

Database
---------------------
ps_orders:
total_products: 198.07000€
total_products_wt: 198.0700€
total_paid_tax_excl: 198.07000€
total_paid_tax_incl: 239.670000€

198,07€+21% is not 239,67€ but 239,66€

Prestashop version: 1.7.6.2 - 1.7.7.0 beta

**Comment by florine2623** [comment] 2020-09-17 07:43
Hello @josiasdx ,
Is your issue relate to : https://github.com/PrestaShop/PrestaShop/issues/9981 ?
Thanks!

**Comment by josiasdx** [comment] 2020-09-17 07:48
Hello @florine2623 
No exactly the same problem (9981 have selected round in each article and I selected round in each line), but probably in both cases the origin of the problem is the same, yes

**Comment by Hlavtox** [comment] 2020-09-17 11:56
@josiasdx I think the discount is calculated from the price with tax, as this is the price displayed everywhere.

282,96 * 1,21 = 342,38 is the line total
342,38 * 0,7 = 239,67 = correct

**Comment by josiasdx** [comment] 2020-09-17 12:30
@Hlavtox thank you for your comment. Indeed, seems the discount is calculated from price tax included (thank you for confirm this point)

This is a problem for **invoices** in B2B sales, because 198,07€ + 21% is not 239,67€.
Some of our invoices have differences much bigger than 0,01€ due this reason (orders with lot of lines)

we are sending invoices with all our orders. All our invoices are:
line 1 price tax excluded - discount = total line tax excluded
line 2 price tax excluded - discount = total line tax excluded
line 3 price tax excluded - discount = total line tax excluded

 line1+line2+line3 = total tax excluded 
+taxes = total taxes included.

 In spain all invoices are like this.

I'm coming from Magento, and Magento allows to select if use prices tax excluded or included for the calculations.
If PS haven't an option for change this behaviour, will usefull to know which kind of lines modify to change the calculation from tax included to tax excluded because if not, many invoices will generated with wrong info...

In database is appearing total_products: 198.07000€, instead 198.07**2**000

**Comment by khouloudbelguith** [comment] 2020-09-28 14:14
Hi @josiasdx,

Thanks for your report.
Issue reported here: https://github.com/PrestaShop/PrestaShop/issues/20981.
Can we close this ticket?

Thanks!

**Comment by josiasdx** [comment] 2020-09-28 14:52
If you want, you can close the ticket. I think the only solution to this problem is follow the way other ecommerce platforms: an option in the backoffice to choose if works tax included or tax excluded. The shop will show both prices, but the internal calculations will different according this option. Is very important for B2B sales.

**Comment by khouloudbelguith** [comment] 2020-09-28 15:05
@josiasdx, thanks for your feedback.
Your ticket is similar to @HartLarsson issue:https://github.com/PrestaShop/PrestaShop/issues/20981.
I'm still working on this issue.
Your ticket is a duplicate of #20981
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-09-28 15:06
Duplicate of #20981

**Closed as completed by khouloudbelguith** 2020-09-28 15:05 UTC
Labels: Duplicate, Discounts, Taxes and Prices, 1.7.6.2, 1.7.7.x
