### ISSUE TITLE
A little suggestion for some overridable classes

### ISSUE THREAD

**Issue by fkomaralp** [PrestaShop/PrestaShop#20784] opened 2020-08-29 18:05 UTC
#### Is your feature request related to a problem?

I was creating a module. My module needs some overrides. So I want to override some classes. 
Let's talk about `classes/form/CustomerAddressFormatter.php` class. This class members are declared private. Thats my problem.

```
<?php

/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 */
use Symfony\Component\Translation\TranslatorInterface;

class CustomerAddressFormatterCore implements FormFormatterInterface
{
    private $country;
    private $translator;
    private $availableCountries;
    private $definition;
```

#### Describe the solution you'd like

If I want to override to a function or variable, I need to copy all of members from the source class, because some(or all) members are declared private. I just need to override one function.

#### Alternatives you've considered

We can't make private variables to public?

#### Additional context

I just want to override `getFormat` function. If someone want's to override this class's different function (not getFormat ex.), should be able to do this. Maybe you explain an example solution for this class, for override a function. I can see some solutions just for this class but not all of other classes. Or am I wrong?

**Comment by khouloudbelguith** [comment] 2020-08-31 08:18
Duplicate of #15396

**Closed as completed** 2020-08-31 08:18 UTC
Labels: Duplicate
