### ISSUE TITLE
Trying to get property 'id' of non-object (/var/www/html/classes/CartRule.php, line 754)

### ISSUE THREAD

**Issue by demperador** [PrestaShop/PrestaShop#19608] opened 2020-06-05 14:39 UTC
#### Describe the bug

I have a webservice from our ERP to Prestashop to update the order status and most of my orders are correctly updated but some of them in Prestashop is giving the following error:

Trying to get property 'id' of non-object (/var/www/html/classes/CartRule.php, line 754)

In fact, my orders do get updated but keeps sending my customers emails about their order status. I believe it is something related with a Cart Rule but I do not know exactly where to look.

#### Expected behavior

Simply update the order status

#### Steps to Reproduce

[Pedidos > Pedido NTBABHZZZ  CentroBell Cosmética.pdf](https://github.com/PrestaShop/PrestaShop/files/4736677/Pedidos.Pedido.NTBABHZZZ.CentroBell.Cosmetica.pdf)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.30

**Comment by florine2623** [comment] 2020-06-05 15:03
Hi @demperador ,
What are the steps to reproduce your issue ?

Thanks!

**Comment by demperador** [comment] 2020-06-05 16:34
Hello,

Main problem is that it seems that Context::getContext()->currency->id in line 754 of CartRule.php inside _public function checkValidity_ is not getting what it is expected.

**Comment by florine2623** [comment] 2020-06-08 09:05
If I cant reproduce your issue on my end, I cannot help you.
Please share the steps to reproduce your issue.

**Comment by marionf** [comment] 2020-06-10 09:40
@florine2623 Could you add missing labels (bug or improvement, the severity) ?

**Comment by demperador** [comment] 2020-06-11 12:48
Hello,

This error occurs when using the API / Orders to modify the tracking number. We have got a cart rule which is configured as shown in the attached video (cartRuleConfig.zip) that when it is deactivated, the API / Orders works correctly. If it is activated, the API throws the error Trying to get property 'id' of non-object (/var/www/html/classes/CartRule.php, line 754).
[cartRuleConfig.zip](https://github.com/PrestaShop/PrestaShop/files/4764765/cartRuleConfig.zip)

A workaround to avoid this error is to add an if statement that surrounds the if statement that is failing as shown below:

**if (isset(Context::getContext()->currency->id)){**
                if ($this->minimum_amount_currency != Context::getContext()->currency->id) {
                    $minimum_amount = Tools::convertPriceFull($minimum_amount, new Currency($this->minimum_amount_currency), Context::getContext()->currency);
                }
**}**
 in classes/CartRule.php line 758

Can this be resolved in future versions of Prestashop?

**Comment by florine2623** [comment] 2020-07-02 12:43
Hi @PrestaShop/prestashop-core-developers ,
Could you take a look at @demperador 's issue regarding the update of the cart rules via webservices please ?
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-28 11:42
Hi @demperador,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
[Order Settings • 1764.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4988041/Order.Settings.1764.webm.zip)

I used this script
```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 28/07/2020
 * Time: 12:01
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://shop.com');
define('PS_WS_AUTH_KEY', 'key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'http://shop.com',
    'Key',
    false);
$id = 11; //ID order Here
$xml = $ws->get(array('resource' => 'orders', 'id' => $id));
echo "BEFORE\n";
echo $xml->asXML();
unset($xml->order->current_state);
$xml->order->shipping_number = 10;
$xml->order->current_state = 4;
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'orders';

$xml = $ws->edit($opt);


$xml = $ws->get(array('resource' => 'orders', 'id' => $id));

echo $xml->asXML();
```

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-08-17 08:27
Hi @demperador,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-17 08:27 UTC
Labels: Bug, Minor, WS, Order, Webservice, Cart rules, No change required, 1.7.6.4
