### ISSUE TITLE
Use customer token instead of global token for webservice auth

### ISSUE THREAD

**Issue by Bonobomagno** [PrestaShop/PrestaShop#11053] opened 2018-10-17 15:32 UTC
**Is your feature request related to a problem? Please describe.**
Actually an user cant make any stateless action. In fact webservice  token is an backoffice token, that simulate an admin. So every request will include the "admin" token when using webservice. 
But if you have an app, you must insert this token inside the app, making it not more secure.

**Describe the solution you'd like**
The token must be customer based, like bearer /oauth / jwt etc, so that will be no need to include the secret token 

**Describe alternatives you've considered**
as i indicated, bearer token, oauth, jwt, any token stateless auth is ok.

**Additional context**
this is a pretty standard feature, in fact there are official symfony bundle that handle that easly

**Comment by khouloudbelguith** [comment] 2018-10-17 15:50
Hi @Bonobomagno,

Thanks for your improvement.
@eternoendless, @PrestaShop/prestashop-core-developers what do you think of his suggestion?
Thanks!

**Comment by PierreRambaud** [comment] 2020-10-12 09:15
With a really, really long wait :roll_eyes: 
I totally agree about this type of connection. The usage of a global token is a bad practice.

**Comment by LouiseBonnard** [comment] 2020-11-23 09:38
A duplicate issue (https://github.com/PrestaShop/PrestaShop/issues/19291) has the same request to reinforce WS security by adding an authorization layer. So I close this one and keep the other open so that we can all stay focus at the same place, feel free to comment on the other one. :-)

**Closed as completed by LouiseBonnard** 2020-11-23 09:38 UTC
Labels: Improvement, WS, Duplicate, Developer Feature

**Comment by hibatallahAouadni** [comment] 2021-01-18 12:51
Duplicate of #19291
