### ISSUE TITLE
Front office connection from back office order

### ISSUE THREAD

**Issue by Belyce32** [PrestaShop/PrestaShop#33906] opened 2023-09-11 11:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since versions 1.7.7, when you create a back office order and you want to finalise the order in the front office, the customer you are supposed to be connected to for this back office order is not connected to the shop.

### Expected behavior

once the option to Proceed to payment on the front office has been selected, the customer account must be automatically connected.
This is the behaviour of previous versions. Worked perfectly on version 1.7.5

### Steps to reproduce

1.Go to order and create a back office order.
2.Choose an existing customer.
3.Fill in the order and to finalise, select the option PROCEED TO PAYMENT FROM THE FRONT OFFICE.
![image](https://github.com/PrestaShop/PrestaShop/assets/47316162/1c14a5d1-9484-492c-9d35-9c2b62c01945)

4.The shop opens, but on a customer login page.
![image](https://github.com/PrestaShop/PrestaShop/assets/47316162/5377240f-ac53-47ba-8863-2c6e2edc7f62)

The customer is not automatically authenticated. You need to go to login and enter your password.
It is impossible to finalise a BO order with a customer account that logs in automatically.

### PrestaShop version(s) where the bug happened

1.7.7.4 and 1.7.8.10

### PHP version(s) where the bug happened

 7.3.33 and 7.2.34

**Comment by Hlavtox** [comment] 2023-09-11 11:49
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/30074 and https://github.com/PrestaShop/PrestaShop/issues/20977

**Comment by Belyce32** [comment] 2023-09-11 13:02
I applied the fix from #31489
all is ok, thank you

**Closed as completed** 2023-09-11 13:02 UTC
Labels: Bug, Duplicate, Invalid

**Comment by sallemiines** [comment] 2023-09-11 14:51
Duplicate of #20977
