### ISSUE TITLE
Error actualización de 1.7.5.1 a 1.7.6.5

### ISSUE THREAD

**Issue by javierVP** [PrestaShop/PrestaShop#19250] opened 2020-05-21 10:40 UTC
Tengo mi prestashop 1.7.5.1 con el módulo 1-clic versión 4.10.1 y la versión de php 7.2

Y este es el error que me muestra el módulo:

[INTERNAL] /var/www/vhosts/manzanosmoda.es/httpdocs/src/PrestaShopBundle/PrestaShopBundle.php line 64 - Error: Class 'PrestaShopBundle\DependencyInjection\Compiler\OverrideTwigServiceCompilerPass' not found #0 /var/www/vhosts/manzanosmoda.es/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(797): PrestaShopBundle\PrestaShopBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /var/www/vhosts/manzanosmoda.es/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /var/www/vhosts/manzanosmoda.es/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(636): Symfony\Component\HttpKernel\Kernel->buildContainer() #3 /var/www/vhosts/manzanosmoda.es/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /var/www/vhosts/manzanosmoda.es/httpdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #5 /var/www/vhosts/manzanosmoda.es/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #6 /var/www/vhosts/manzanosmoda.es/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #7 /var/www/vhosts/manzanosmoda.es/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /var/www/vhosts/manzanosmoda.es/httpdocs/admin195moqyo1/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}

**Comment by javierVP** [comment] 2020-05-21 10:41
Subo el archivo log.txt
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4661970/log.txt)

**Comment by florine2623** [comment] 2020-05-22 07:11
Hi @javierVP ,

Your issue seems to be the same as https://github.com/PrestaShop/PrestaShop/issues/18251#issuecomment-605089128
Could you check and let me know ?
Thanks!

**Comment by javierVP** [comment] 2020-05-22 09:24
also disable the native prestashop modules option and it did not work either

**Comment by florine2623** [comment] 2020-05-22 15:04
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev) ?

**Comment by javierVP** [comment] 2020-05-29 10:17
but before the update, because the error takes me out in the module when updating.

**Comment by florine2623** [comment] 2020-05-29 10:27
I don't understand, can you specify more ?

**Comment by javierVP** [comment] 2020-05-29 10:28
I mean if I should delete those folders before doing the installation, because the error removes it when I am updating.

**Comment by florine2623** [comment] 2020-05-29 14:51
I would advise you to roll back to a previous version in order to get rid of all the errors first. You can do that with your manual back-up or directly with your host.
On my test shop, I can't reproduce your issue. You might have some external modules/theme that conflict with the module 1-click upgrade.

**Comment by javierVP** [comment] 2020-06-01 15:14
Ok, I'll try to see.

**Comment by florine2623** [comment] 2020-06-01 15:36
For now, I close this issue.
If later on you need support on your migration, you can contact the support team : https://addons.prestashop.com/en/388-support
Thanks!

**Closed as completed by florine2623** 2020-06-01 15:36 UTC
Labels: Autoupgrade, No change required, 1.7.5.1, 1.7.6.5
