### ISSUE TITLE
[BO] Category admin jumps to home when deleting a category

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17463] opened 2020-01-31 12:05 UTC
You have categories: 
Home > Cars > SUVs > Small
Home > Cars > SUVs > Medium
Home > Cars > SUVs > Big

You are editing categories.
You are in SUVs category.
You delete Small category and the view jumps all the way back to Home category, annoying.

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-01-31 12:50
Hi @Hlavtox,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15588
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-31 12:50
Duplicate of #15588

**Comment by khouloudbelguith** [comment] 2020-01-31 14:29
Hi @PululuK,

Thanks for the ping.
I just re-opened this issue.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2.
1.7.6.3: https://drive.google.com/file/d/1cYgY4oHoQtZ8_6m8DIpRY1-PFBYnSjwz/view
1.7.5.2: https://drive.google.com/file/d/1fHX0lR8kXbN1DDtsaE4F9aKZfe9kogS7/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-31 14:29
Related to #15588

**Comment by Progi1984** [comment] 2020-04-01 07:57
Fixed by #17467

**Closed as completed** 2020-04-01 07:57 UTC
Labels: Bug, Minor, BO, Categories, Fixed, migration, 1.7.5.2, PR available, 1.7.6.3
