### ISSUE TITLE
error free shipping costs

### ISSUE THREAD

**Issue by gabbodrummer** [PrestaShop/PrestaShop#24060] opened 2021-04-15 08:28 UTC
Hi,

I noticed a bug regarding free shipping.
I set the shipping based on the weight of the items purchased and then in the appropriate section I set the free shipping above a certain amount, but the weight rule overrides that of the free price 

![image](https://user-images.githubusercontent.com/48911349/114838515-102e5980-9dd5-11eb-8a6d-7f8745b6e4a5.png)
-------------------------------------------------
![image](https://user-images.githubusercontent.com/48911349/114838547-16bcd100-9dd5-11eb-84fc-7840c7c9fa4e.png)
-------------------------------------------------
![image](https://user-images.githubusercontent.com/48911349/114838566-1ae8ee80-9dd5-11eb-9cbd-c4d7f0fce536.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34

**Comment by florine2623** [comment] 2021-04-16 08:51
Hello @gabbodrummer ,

I can't reproduce your issue. Please see my screenshots below.
Config of product :
![Capture d’écran 2021-04-16 à 10 15 10](https://user-images.githubusercontent.com/16019289/114994145-c610ab00-9e9c-11eb-8466-a8d7997d89f5.png)
Config of carrier :
![Capture d’écran 2021-04-16 à 10 15 36](https://user-images.githubusercontent.com/16019289/114994154-c7da6e80-9e9c-11eb-9233-c5741208c8a0.png)
Config in Carrier preference :
![Capture d’écran 2021-04-16 à 10 16 56](https://user-images.githubusercontent.com/16019289/114994250-e2144c80-9e9c-11eb-9a40-14a2ce1d57dc.png)

Result in cart :
![Capture d’écran 2021-04-16 à 10 14 55](https://user-images.githubusercontent.com/16019289/114994122-c14bf700-9e9c-11eb-873f-92c332c57cfb.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

**Closed as completed by florine2623** 2021-04-16 08:51 UTC
Labels: Can't reproduce
