### ISSUE TITLE
Reservation period help text is incorrect [Bank transfer module]

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28354] opened 2022-04-27 13:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Not sure if this is a bug, but I think this needs to be corrected. The help text in "Reservation period" field states: "Number of days the items remain reserved". Though you can enter any symbol possible, it will accept it, should allow only numbers (day count that the product would be reserved for) or the help text should be changed.
![Uploading image.png…]()

### Expected behavior

Should not allow anything apart from numbers in the field, or the help text edited.

### Steps to reproduce

1. Go to Modules -> Module Manager -> Bank transfer module, edit the module.
2. In the "Customization" tab, in the "Reservation period" enter anything apart from numbers.
3. Press "Save".

### PrestaShop version(s) where the bug happened

1.7.8.4

### If your bug is related to a module, specify its name and its version

Bank transfer v2.1.1

**Comment by hibatallahAouadni** [comment] 2022-04-27 14:52
Hello @Saimis777 

I reproduce the issue with PS1767, PS1778, PS1785 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/165546505-0580eb08-ae7b-44d8-a7eb-56fbfbf7354e.png)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment] 2022-09-01 07:31
Fixed by https://github.com/PrestaShop/ps_wirepayment/pull/78

**Closed as completed** 2022-09-01 07:31 UTC
Labels: Bug, Trivial, BO, Bankwire, Fixed, 1.7.6.7, Verified, Module
