### ISSUE TITLE
Hook displayBackOfficeTop not being called anymore on Login BO Page in 1.7.7

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#21379] opened 2020-10-09 10:20 UTC
#### Describe the bug

I can no longer read post parameters from backofficetop hook on login page on 1.7.7. Please see below example:

#### Expected behavior

PS 1.6.1 - 1.7.6:
```
public function hookDisplayBackOfficeTop($params)
{
    if (Tools::isSubmit('submitLogin')) {
        exit;
    }
}
```
Go to login page -> Submit -> Die as expected

PS 1.7.7:
```
public function hookDisplayBackOfficeTop($params)
{
    if (Tools::isSubmit('submitLogin')) {
        exit;
    }
}
```
Go to login page -> Submit -> Logged in (not expected)

**Comment by florine2623** [comment] 2020-10-09 10:34
Hi @MathiasReker ,
Could you send the steps to reproduce the bug please ?
And screenshots if possible.
Thanks!

**Comment by MathiasReker** [comment] 2020-10-09 11:34
Hello @florine2623 

1. Add this code to a module at the DisplayBackOfficeTop hook:
```
public function hookDisplayBackOfficeTop($params)
{
    if (Tools::isSubmit('submitLogin')) {
        exit;
    }
}
```
2. Go to BO
3. Login
4. Repeat process for 1.7.6 and 1.7.7 -> 1.7.7. The hook is not working in this area of 1.7.7

**Comment by matks** [comment] 2020-10-09 12:23
@MathiasReker I dont know what is the root cause for this issue but the current behavior seems to make sense 🤔 .

When Login Page is displayed, following a GET request, a HTML response is sent => hookDisplayBackOfficeTop is triggered
When user submits a POST request to Login Page, if successfull, the user is redirected to its main page (usually it's dashboard).

It makes sense that a successfull authentication POST request to login process does not render template, and hookDisplayBackOfficeTop is a display hook.

**Comment by khouloudbelguith** [comment] 2020-10-12 11:51
Hi @MathiasReker,

I used `ps_banner` module.
![image](https://user-images.githubusercontent.com/16067358/95743436-114dc500-0c92-11eb-97d2-e9b7f81dae86.png)

I tried with PS1.7.6.8.
I cannot log in
![image](https://user-images.githubusercontent.com/16067358/95743332-e6fc0780-0c91-11eb-9707-069ca40d96b6.png)

I tried with 17.7.x branch
I can log in => no issue
Is this the exact problem?

Thanks!

**Comment by MathiasReker** [comment] 2020-10-12 12:11
@khouloudbelguith yes, the behavior is different. Something in 1.7.7 changes its behavior.

@matks thanks, I get your point. My issue is, that my module includes a brute force protection where I need to monitor the login attempts. I made this work for 1.6 - 1.7.6, but I cannot make it work in 1.7.7.

I have tried the different hooks, but I cannot do this:
```
        if (Tools::isSubmit('submitLogin')) {
        	// do something
        }
```

Do you have a suggestion for another solution achieving this? :)

**Comment by khouloudbelguith** [comment] 2020-10-12 14:02
@MathiasReker,

Thanks for the clarification.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2020-10-12 14:15
Ping @PrestaShop/product-team, I couldn't find the Epic related to this issue.
Can you check it!

Thank you!

**Comment by matks** [comment] 2020-10-12 16:24
Hi @MathiasReker so I checked and found the reason : https://github.com/PrestaShop/PrestaShop/pull/19712

Hook `displayBackOfficeTop` was being fired from this block:
```
        $this->context->smarty->assign([
            'displayBackOfficeTop' => Hook::exec('displayBackOfficeTop'),
            'submit_form_ajax' => (int) Tools::getValue('submitFormAjax'),
        ]);
```
This block has been moved from `init()` to `initHeader()`

**Comment by matks** [comment] 2020-10-12 16:29
@MathiasReker Have a look at the hooks being called in `postProcess()` I think they should do the job for your case

**Comment by MathiasReker** [comment] 2020-10-12 18:58
@matks I cannot solve the problem 😕 Can you point out what specific hook from the postProcess that I could use for this? 🤔

**Comment by PierreRambaud** [comment] 2020-10-14 09:43
hey @MathiasReker Have a look at #21435 You should be happy :)

**Comment by MathiasReker** [comment] 2020-10-14 09:49
@PierreRambaud Thanks! 👍🏻

**Comment by matks** [comment] 2020-10-14 15:48
https://github.com/PrestaShop/PrestaShop/pull/21435 merged => @MathiasReker so the answer to your question "what should I use for 177" is "one of the new hooks" 😃

**Closed as completed** 2020-10-14 15:48 UTC
Labels: Bug, Minor, CO, Regression, Fixed, Must-have, 1.7.7.x, Hook

**Comment by MathiasReker** [comment] 2020-10-15 08:53
@matks Thanks for the new hooks, I really appreciate that. 👍🏻
