### ISSUE TITLE
Problème affichage backoffice

### ISSUE THREAD

**Issue by ludofrenchy** [PrestaShop/PrestaShop#14342] opened 2019-06-24 11:11 UTC
**Describe the bug**
L'affichage des éléments se superpose.

**To Reproduce**
1. Go to 'Commandes'
2. Click on 'une commande de la liste'
3. Scroll down to 'bas de la page de la commande'

**Screenshots**
<img width="773" alt="Capture" src="https://user-images.githubusercontent.com/42412208/60014423-47240000-9681-11e9-9e4e-2bed5cb14286.PNG">

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: N/A

**Comment by xalerafera** [comment] 2019-06-24 11:18
<img src="data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4=">

**Comment by khouloudbelguith** [comment] 2019-06-24 11:55
Hi @ludofrenchy,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13061
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-24 11:55
Duplicate of #13061

**Closed as completed by khouloudbelguith** 2019-06-24 11:55 UTC
Labels: Duplicate
