### ISSUE TITLE
Error while getting JSON output through API on any request

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11917] opened 2018-12-24 06:49 UTC
**Describe the bug**
Error while getting JSON output through API on any request, See error screenshot attached

**To Reproduce**
1. Call this endpoint URL: /api/languages?output_format=JSON

**Screenshots**
![download 37](https://user-images.githubusercontent.com/19220745/50392628-056bd880-0776-11e9-8986-335b99fb5b59.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: PHP7

Sending the PR to fix this issue

**Comment by khouloudbelguith** [comment] 2018-12-24 07:38
Hi @dheerajwebkul,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11902 to fix the issue.
Your ticket is a duplicate of #11840
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-24 07:39
Duplicate of #11840

**Closed as completed by khouloudbelguith** 2018-12-24 07:38 UTC
Labels: Duplicate
