### ISSUE TITLE
Category sorting options different in FO vs. BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14244] opened 2019-06-17 10:41 UTC
**Describe the bug**
Options for sorting products in category are different in Back Office and Front Office.

FO: price, name, importance
BO: price, name, add date, edit date, reference, manufacturer, quantity, position

Once you select different filter in FO, you can't go back unless you refresh page.

Should be unified OR user should be able to select which options he wants to show in FO, for example by a checkbox list.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-06-17 10:44
Hi @Hlavtox,

Thanks for your report.
Your ticket is a duplicate of #14210
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-17 10:44
Duplicate of #14210

**Closed as completed by khouloudbelguith** 2019-06-17 10:44 UTC
Labels: Duplicate

**Comment by Hlavtox** [comment] 2020-04-16 17:36
@khouloudbelguith Can you reopen this please? The issue I specify here was not fixed on the "duplicate" issue.
