### ISSUE TITLE
Feature multipling in BO product page

### ISSUE THREAD

**Issue by AndrzejWolan** [PrestaShop/PrestaShop#23119] opened 2021-02-03 11:40 UTC
#### Describe the bug

When we in back office editing product and add new feature without select any feature from list, we can't choose pre-defined value but still we can fill field Customized value and save product. This feature is saved in database and each time we add new feature to this product those features is doubled.

 
#### Expected behavior

Disabled input if feature is not selected

#### Steps to Reproduce

1. Go to BO - Sell - Catalog - Products
2. Click Edit any product
3. Scroll down to Features
4. Click - Add a feature
5. Do not choose any feature from Select just fill last field **OR Customized value**
6. Save product
7. Click - Add a feature
8. Choose Feature from select
9. Choose feature value from select
10. Save product
11. Refresh page
12. Do steps from 7 to 11 

#### Additional information

* PrestaShop version: 1.7.7.1 and previous
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-02-03 13:06
Hello @AndrzejWolan 

It seems your issue is similar to this one #16306
Please check and feedback.

Thanks!

**Comment by AndrzejWolan** [comment] 2021-02-03 13:15
Yes this is same issue, so this is doubled ;/

**Comment by hibatallahAouadni** [comment] 2021-02-03 14:17
Hello @AndrzejWolan 

Thanks for your feedback :wink: 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16306. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-03 14:17
Duplicate of #16306

**Closed as completed by hibatallahAouadni** 2021-02-03 14:17 UTC
Labels: Bug, BO, Duplicate, Features, 1.7.7.1
