### ISSUE TITLE
Menu "Orders-Invoices" throws Error 500

### ISSUE THREAD

**Issue by Goalfair** [PrestaShop/PrestaShop#12159] opened 2019-01-15 09:39 UTC
After manual upgrade from PS 1.6 to 1.7.5, when trying to view dashboard page "Orders" => "Invoices" an Error 500 is thrown.

Enabling debug mode provides the following:

**Exception:**

![2019-01-15_prestahop-scrn-01](https://user-images.githubusercontent.com/46447000/51171602-9a637c80-18b1-11e9-831b-337602b6a063.jpg)

**Logs:**

Level | Channel | Message
-- | -- | --
DEBUG                 10:32:13 | doctrine | SELECT name FROM ps_module WHERE active = 1
INFO                 10:32:13 | request | Matched route "admin_order_invoices".
DEBUG                 10:32:13 | security | Read existing security token from the session.
DEBUG                 10:32:13 | security | User was reloaded from a user provider.
DEBUG                 10:32:13 | doctrine | SELECT name FROM ps_module WHERE active = 1
DEBUG                 10:32:13 | doctrine | SELECT COUNT(o.id_order) AS nbOrders, o.current_state as id_order_state FROM `ps_order_invoice` oi LEFT JOIN `ps_orders` o ON oi.id_order = o.id_order WHERE o.id_shop IN(:shopIds) AND oi.number > 0 GROUP BY o.current_state
INFO                 10:32:13 | php | User Deprecated: Implementing  "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface"  without the "reset()" method is deprecated since Symfony 3.4 and will be  unsupported in 4.0 for class  "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector".
CRITICAL                 10:32:13 | php | Uncaught Exception: Expected argument of type "object, array or empty", "string" given
CRITICAL                 10:32:13 | request | Uncaught PHP Exception  Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected  argument of type "object, array or empty", "string" given" at [url redacted]/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php  line 41

**Stack Trace:**

Symfony\Component\Form\Exception\UnexpectedTypeException:
Expected argument of type "object, array or empty", "string" given

  at vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:41
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms('', object(RecursiveIteratorIterator))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:379)
  at Symfony\Component\Form\Form->setData('')
     (vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('RET', false), 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('Vielen Dank für Ihre Bestellung bei Golf Direkt. ', false), 'invoice_model' => 'invoice', 'use_disk_cache' => false), object(RecursiveIteratorIterator))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:379)
  at Symfony\Component\Form\Form->setData(array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('RET', false), 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('Vielen Dank für Ihre Bestellung bei Golf Direkt. ', false), 'invoice_model' => 'invoice', 'use_disk_cache' => false))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(array('invoice_options' => array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('RET', false), 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('Vielen Dank für Ihre Bestellung bei Golf Direkt. ', false), 'invoice_model' => 'invoice', 'use_disk_cache' => false)), object(RecursiveIteratorIterator))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:379)
  at Symfony\Component\Form\Form->setData(array('invoice_options' => array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('RET', false), 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('Vielen Dank für Ihre Bestellung bei Golf Direkt. ', false), 'invoice_model' => 'invoice', 'use_disk_cache' => false)))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:483)
  at Symfony\Component\Form\Form->initialize()
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:226)
  at Symfony\Component\Form\FormBuilder->getForm()
     (src/Core/Form/FormHandler.php:114)
  at PrestaShop\PrestaShop\Core\Form\FormHandler->getForm()
     (src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php:57)
  at PrestaShopBundle\Controller\Admin\Sell\Order\InvoicesController->indexAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (devadmin/index.php:88)

**Additional information:**
PrestaShop version: 1.7.5.0
PHP version: 7.2.13

**Comment by khouloudbelguith** [comment] 2019-01-15 09:56
Hi @Goalfair,

To fix this issue you can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/11909#issuecomment-450416475
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-15 09:57
Duplicate of #11909

**Closed as completed by khouloudbelguith** 2019-01-15 09:56 UTC
Labels: Duplicate
