### ISSUE TITLE
 lorsque je clique sur le bouton "ajouter au panier", l'icone du panier avec le nb d'articles ne se met à jour que si je change de page

### ISSUE THREAD

**Issue by Redparkerdoz** [PrestaShop/PrestaShop#12477] opened 2019-02-07 10:31 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-02-07 10:33
Hi @Redparkerdoz,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-11 07:54
Hi @Redparkerdoz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-11 07:54 UTC
Labels: Bug, FO, Blockcart, No change required
