### ISSUE TITLE
Module ps_featuredproducts is not upgrading from v2.1.2 -> v2.1.3

### ISSUE THREAD

**Issue by Ybeske** [PrestaShop/PrestaShop#31055] opened 2023-01-26 21:03 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The standard built in module featuredproducts is not upgrading from v2.1.2 -> v2.1.3.
Even if the green confirmation message is shown, the module is still active as an upgrade.

### Expected behavior

The Update tab to be empty because the upgrade succeeded

### Steps to reproduce

> Module manager
> Tab "Update (1)"
> Featured Products v2.1.2 -> v2.1.3 "Upgrade"
> Green message: "Upgrade succesful"
> Still : Module Manager and  "Update (1)" => Featured Products v2.1.2 -> v2.1.3 "Upgrade"

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

ps_featuredproducts v2.1.2

**Comment by HanaRebaiQA** [comment] 2023-01-27 13:52
Hello @Ybeske 

Thanks for your report.
I tried to reproduce your issue using : 

**PS8.0.1 and php8.0** : Not reproduced. In fact, I was able always to reproduce this [issue](https://github.com/PrestaShop/PrestaShop/issues/29613) 
**PS8.0.1 and php7.3** : Reproduced

https://user-images.githubusercontent.com/92912932/215102875-09be8ef7-e9b5-4648-a0d2-43fb9d796700.mp4

**PS8.0.x and php7.3** : Reproduced

https://user-images.githubusercontent.com/92912932/215104221-d0c004c0-7f10-441a-92a5-a748fd71dcb9.mp4


**PS1.7.8.7 and php7.3** : Not reproduced

https://user-images.githubusercontent.com/92912932/215103039-48a10822-f61c-41e6-9d75-5072cda9bf81.mp4

Indeed, it's a regression of the module on PS8.0.1.

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank You!

**Comment by Hlavtox** [comment] 2023-02-07 13:03
Hi @nl2ttl, there was a version mismatch in the build. Tommorow a 2.1.4 version will pop up and the upgrade will work fine.

Or you can manually update from this zip - https://github.com/PrestaShop/ps_featuredproducts/releases/download/v2.1.4/ps_featuredproducts.zip

**Closed as completed by Hlavtox** 2023-02-07 13:03 UTC
Labels: Bug, Minor, BO, Fixed, Module manager, Verified, Module, ps_distributionapiclient, 8.0.1
