### ISSUE TITLE
500 error backoffice calling shopping carts after editing address requirements

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#11633] opened 2018-12-06 10:07 UTC
After modifying address requirements for customer ( i.e. removing 2nd address and 2nd phonenumber) visit backoffice shopping carts will result in 500 error.

![2018-12-06_10h40_09](https://user-images.githubusercontent.com/11147327/49576915-99503e80-f946-11e8-83e1-ed5409f64a90.png)

**Comment by khouloudbelguith** [comment] 2018-12-06 10:29
Hi @Peter4661,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11416 to fix the issue.
It is fixed in the PS1.7.5.0.
Your ticket is a duplicate of #9782
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-06 10:30
Duplicate of #9782

**Closed as completed by khouloudbelguith** 2018-12-06 10:29 UTC
Labels: Duplicate

**Comment by Peter4661** [comment] 2018-12-06 10:55
Hi Khouloud,

Just implemented the proposed fix; classes/customer.php and classess/address.php. 

Cleared cache.
(again) 500 error when visiting back office cart. 


![2018-12-06_11h49_18](https://user-images.githubusercontent.com/11147327/49579787-8bea8280-f94d-11e8-882d-9a4e212bbf7c.png)

**Comment by khouloudbelguith** [comment] 2018-12-06 11:03
@Peter4661,  
You have an issue on your table ps_cart.
you need to truncate your table ps_cart.
In your Database, table ps_cart, you need to check the last **id** of cart created for example 1000, after that you need to truncate the ps_cart table, in the options tab, you need to set the "AUTO_INCREMENT"= 1000 + 1 = 1001 and save, then the id of the next cart created will be 1001.
![image](https://user-images.githubusercontent.com/16067358/49580252-c6085400-f94e-11e8-9e09-28cdf29d8736.png)

**Comment by Peter4661** [comment] 2018-12-06 11:40
👌

Truncate tabel ps_cart did the job.

Thank you
Met vriendelijke groet,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op do 6 dec. 2018 om 12:03 schreef khouloudbelguith <
notifications@github.com>:

**Comment by Peter4661** [comment] 2018-12-06 11:53
mmmm, cannot add product to cart.  Server error log:


[Thu Dec 06 12:50:53.421312 2018] [core:error] [pid 3780700:tid 140692093310720] [client 54.235.163.229:58822] AH00126: Invalid URI in request GET home HTTP/1.1
[Thu Dec 06 12:50:53.891331 2018] [core:error] [pid 3780700:tid 140692135270144] [client 54.235.163.229:51356] AH00126: Invalid URI in request GET home HTTP/1.1
[Thu Dec 06 12:50:56.906782 2018] [core:error] [pid 3786846:tid 140692282128128] [client 54.235.163.229:51439] AH00126: Invalid URI in request GET home HTTP/1.1
[Thu Dec 06 12:50:57.329898 2018] [core:error] [pid 3786846:tid 140692229678848] [client 54.235.163.229:51451] AH00126: Invalid URI in request GET shop/database/metacart.mdb HTTP/1.1
[Thu Dec 06 12:51:06.663051 2018] [core:error] [pid 3790091:tid 140692208699136] [client 54.235.163.229:59166] AH00126: Invalid URI in request GET autosc.jsp?\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\windows\\\\win.ini HTTP/1.1
[Thu Dec 06 12:51:06.915524 2018] [core:error] [pid 3748158:tid 140692240168704] [client 54.235.163.229:59180] AH00126: Invalid URI in request GET autosc.jsp?\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\winnt\\\\win.ini HTTP/1.1
[Thu Dec 06 12:51:07.377907 2018] [core:error] [pid 3790091:tid 140692124780288] [client 54.235.163.229:51719] AH00126: Invalid URI in request GET autosc.jsp?\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\windows\\\\win.ini HTTP/1.1
[Thu Dec 06 12:51:07.808019 2018] [core:error] [pid 3789334:tid 140692114290432] [client 54.235.163.229:51732] AH00126: Invalid URI in request GET autosc.jsp?\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\winnt\\\\win.ini HTTP/1.1
[Thu Dec 06 12:51:12.902985 2018] [cgid:error] [pid 3790104:tid 140692198209280] [client 54.235.163.229:59367] AH01265: attempt to invoke directory as script: /home/deb115780/domains/derks-wielersport.nl/public_html/cgi-bin/
[Thu Dec 06 12:51:14.389197 2018] [cgid:error] [pid 3790091:tid 140692303107840] [client 54.235.163.229:51931] AH01265: attempt to invoke directory as script: /home/deb115780/domains/derks-wielersport.nl/public_html/cgi-bin/

**Comment by khouloudbelguith** [comment] 2018-12-06 13:22
@Peter4661, in your Database, ps_cart => Table options => have you set the AUTO_INCREMENT ?
Thanks!
