### ISSUE TITLE
Missing sign for Discount(s)

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#24838] opened 2021-06-07 10:47 UTC
#### Describe the bug
There is missing sign for Discounts(s) in the cart.

#### Expected behavior
There should be always used sign "-" for Discount(s)

#### Steps to Reproduce
1. Create any rule for Discount > Cart Rule in BO
2. Add products to the cart in FO where the discount is used
3. Go to the cart and you'll see correct sign for Discount(s) > in my example: **- €4.35**
![image](https://user-images.githubusercontent.com/33311857/121003261-a0619d00-c78d-11eb-941c-d715d1ff3b65.png)

4. Press button "Proceed to checkout" > there is missing sign "-" for Discount(s) > in my example:  **€4.35**
![image](https://user-images.githubusercontent.com/33311857/121003613-051cf780-c78e-11eb-967d-860bb54a46e3.png)

#### Additional information
* PrestaShop version: 1.7.7.4
* PHP version:  7.3.28

**Comment by hibatallahAouadni** [comment] 2021-06-07 17:42
Hello @juraj1000 

Thanks for reporting this issue!
Ping @PrestaShop/product-team is this the expected behavior or it's a bug?

**Comment by RosaBenouamer** [comment] 2023-07-06 09:11
In my opinion it seems to be a bug @hibatallahAouadni

**Comment by hibatallahAouadni** [comment] 2023-07-28 11:26
Thanks @RosaBenouamer :pray:

**Comment by florine2623** [comment] 2024-01-08 11:16
This is fixed in 8.1.x.


https://github.com/PrestaShop/PrestaShop/assets/16019289/bd8e6f90-36c2-4f34-8d46-85bade9431ce



I'm closing the issue.

**Closed as completed by florine2623** 2024-01-08 11:16 UTC
Labels: Bug, Minor, FO, Discounts, Cart rules, Fixed, Checkout, 1.7.7.4, Verified
