### ISSUE TITLE
invalid customer names

### ISSUE THREAD

**Issue by NKoonen** [PrestaShop/PrestaShop#16453] opened 2019-11-18 14:40 UTC
If a customer does not have a valid name (for example a dot) and you want to change that user's password, it gives the following error in the backend: 

> [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0

If that very same user wants to reset their password through the frontoffice, the users receives a invalid reset link.

**Additional information**
PrestaShop version: 1.7.X
PHP version: 7.2 / 7.3

**Comment by khouloudbelguith** [comment] 2019-11-18 14:45
Hi @NKoonen,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14838 to fix the issue.
It is fixed in the next version PS1.7.7.0.
Your ticket is a duplicate of #14157
So, I close it.

PS: PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-18 14:46
Duplicate of #14157

**Closed as completed by khouloudbelguith** 2019-11-18 14:45 UTC
Labels: Duplicate

**Comment by Betafer** [comment] 2020-08-05 07:49
I can confirm the problem with PS: 1.7.6.6 
in surname we have "/" for c/o and we got same error, removing / password can be setted

This also affects that customer cannot reset the password by itself
