### ISSUE TITLE
Error after upgrade 1.7.6.1 -> 1.7.6.2 when unused currencies in database

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#16634] opened 2019-11-30 21:26 UTC
**Describe the bug**
After upgrade from 1.7.6.1 to 1.7.6.2 get error:
```
PHP Fatal error: Uncaught Error: Call to a member function isActive() on null in /var/www/html/prestashop/src/Core/Localization/Currency/Repository.php:109
Stack trace:
#0 /var/www/html/prestashop/src/Core/Localization/Currency/Repository.php(95): PrestaShop\PrestaShop\Core\Localization\Currency\Repository->formatCurrencies(Array)
#1 /var/www/html/prestashop/src/Core/Localization/Locale/Repository.php(207): PrestaShop\PrestaShop\Core\Localization\Currency\Repository->getAllInstalledCurrencies('en-US')
#2 /var/www/html/prestashop/src/Core/Localization/Locale/Repository.php(150): PrestaShop\PrestaShop\Core\Localization\Locale\Repository->getPriceSpecifications('en-US')
#3 /var/www/html/prestashop/classes/controller/Controller.php(189): PrestaShop\PrestaShop\Core\Localization\Locale\Repository->getLocale('en-US')
#4 /var/www/html/prestashop/classes/controller/FrontController.php(271): ControllerCore->init()
#5 /var/www/html/prestashop/classes/controller/Controller.php(273): FrontControllerCore->init()
#6 /var/www/html/prestashop in /var/www/html/prestashop/src/Core/Localization/Currency/Repository.php on line 109
```

Solution to fix: delete unused currencies from DB table.

**Comment by matks** [comment] 2019-11-30 21:27
Bug report submitted through disqus on Build blog: https://build.prestashop.com/news/prestashop-1-7-6-2-maintenance-release/#comment-4707507793

**Comment by khouloudbelguith** [comment] 2019-12-02 13:33
Hi @matks,

I did not manage to reproduce the issue with PS1.7.6.2 after an upgrade from PS1.7.6.1 using the 1-click upgrade v4.10.0.
https://drive.google.com/file/d/1AlqJEFequj_WNQFuNIB3t_q84N2MqD3E/view
I used three currencies, 
The currency with id_currency = 1 is disabled
The currency with id_currency = 2 is enabled
The currency with id_currency = 3 is deleted
![image](https://user-images.githubusercontent.com/16067358/69963552-b5160280-1510-11ea-8bc5-dafeef9a2f49.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-31 07:53
Hi @matks,

Since we had no news from the user for more than 30 days, I'll close this ticket.

Thanks!

**Comment by kmorgen** [comment] 2020-04-01 08:11
We just updated from PS 1.7.6.1 to 1.7.6.4 in our testshop, and now get similar error when changing to Norwegian language:

https://ps17test.morgen.dk/
https://ps17test.morgen.dk/no/
(testshop is in maintaince mode, so not public visible)

All languages and curriencies in the shop are enabled. Other language urls work. Everything worked prior to the update.

Error:
Fatal error: Uncaught Error: Call to a member function isActive() on null in /var/www/morgen.dk/ps17test/src/Core/Localization/Currency/Repository.php:109 Stack trace: #0 /var/www/morgen.dk/ps17test/src/Core/Localization/Currency/Repository.php(95): PrestaShop\PrestaShop\Core\Localization\Currency\Repository->formatCurrencies(Array) #1 /var/www/morgen.dk/ps17test/src/Core/Localization/Locale/Repository.php(207): PrestaShop\PrestaShop\Core\Localization\Currency\Repository->getAllInstalledCurrencies('no-NO') #2 /var/www/morgen.dk/ps17test/src/Core/Localization/Locale/Repository.php(150): PrestaShop\PrestaShop\Core\Localization\Locale\Repository->getPriceSpecifications('no-NO') #3 /var/www/morgen.dk/ps17test/classes/controller/Controller.php(189): PrestaShop\PrestaShop\Core\Localization\Locale\Repository->getLocale('no-NO') #4 /var/www/morgen.dk/ps17test/classes/controller/FrontController.php(271): ControllerCore->init() #5 /var/www/morgen.dk/ps17test/classes/controller/Controller.php(273): FrontControllerCore->init() #6 /va in /var/www/morgen.dk/ps17test/src/Core/Localization/Currency/Repository.php on line 109

**Comment by khouloudbelguith** [comment] 2020-04-01 15:11
Hi @kmorgen,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- 1-click upgrade module version
- PS1.7.6.1: what are the exact languages and currencies used in this shop
- PS1.7.6.1: the new languages are added manually or after importing a pack for the Localization page or after adding a new language from the Translations Page?
- PS1.7.6.1: the new currencies are added manually from the Currencies page or added after importing a pack?


Thanks!

**Comment by kmorgen** [comment] 2020-04-01 17:53
Hello

• 1-click upgrade module version
V4.10.1
• PS1.7.6.1: what are the exact languages and currencies used in this shop
Same as in live store: https://www.chill-innovation.com/ (Still on V1.6.1.24)
• PS1.7.6.1: the new languages are added manually or after importing a pack for the Localization page or after adding a new language from the Translations Page?
Added manually in the Language page
• PS1.7.6.1: the new currencies are added manually from the Currencies page or added after importing a pack?
Added manually in the Currencies page

I might suspect it is related to the locale variations available for some languages. For Norwegian there is Bokmål and Nynorsk. Only this language is causing the error after the update.
Previously (and in the live store) Norwegian (bokmål) has been labled Iso: no and code no-NO.  This have been working fine in the V1.6 live store and also on the 1.7.6.1 test-store. 

However it might make more sense to use iso: no and code nb-NO in accordance to IETF now.
In the V1.6 live store I just tried to change to iso: no and code nb-NO and it still works.

In the test-store I will get the error no matter which iso / code is used for Norweigian.
The error message seem to be a mix between files. Translations refer to no-NO, but /js/tiny_mce/langs is nb.js (the is not a no.js, and renaming it did not help). 

All Currencies and Languages are Active in both live and teststore.

**Comment by khouloudbelguith** [comment] 2020-04-02 10:03
@kmorgen, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.4 after an upgrade from PS1.7.6.1 using the 1-click upgrade v4.10.1.
I attached screen records
1. https://drive.google.com/file/d/1FwU736C69mIivl16YBtegMmcxQ3pQVku/view?usp=sharing
2. https://drive.google.com/file/d/1F3GTY-hZh76j1AqxHh6DR5HReBrmnVvW/view?usp=sharing

Thanks to check and feedback.

**Comment by kmorgen** [comment] 2020-04-02 13:38
@khouloudbelguith I have temporarily activated the shop, so you can inspect it (or else please provide IP, so can add it to maintenance mode): https://ps17test.morgen.dk/

The shop and configuration was installed prior to V1.7.6.1, and was working until the update. No error message during update, and only problem is for /no (norway).

Do you know how I can fix it?

**Comment by khouloudbelguith** [comment] 2020-04-02 13:42
@kmorgen, could you please try to navigate to the BO => International => Localization page => Import the "Norway" pack.
![image](https://user-images.githubusercontent.com/16067358/78256162-79a83680-74f8-11ea-9e84-e81561fc4374.png)

Thanks to check and feedback.

**Comment by kmorgen** [comment] 2020-04-02 13:55
@khouloudbelguith Unfortunately did not help. Tried to delete the Norske Kroner before the import too.

**Comment by khouloudbelguith** [comment] 2020-04-02 14:07
@kmorgen, so, it could be something went wrong with your update and don't have some of the database columns that were added for 1.7.6.4
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.4 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.4/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by kmorgen** [comment] 2020-04-02 14:21
@khouloudbelguith I think I located the problem/solution

In table PS_lang locale for Norway, this was called no-NO. I changed this to nb-NO, so now it works.

So the issue seem to have been been triggered by changes in language variations, since Norway have 2 languages. I guess this might then also occur for other language variations like en-US, en-GB etc. 

EDIT: I just checked a database backup from V1.7.6.1 and was also no-NO here and site worked.

**Comment by khouloudbelguith** [comment] 2020-04-02 14:27
@kmorgen, as you can see in my previous screen record
![image](https://user-images.githubusercontent.com/16067358/78260813-b0814b00-74fe-11ea-8e83-28f783976910.png)
![image](https://user-images.githubusercontent.com/16067358/78260888-c8f16580-74fe-11ea-86f6-642bd21c4327.png)

It is well working also.
Thanks!

**Comment by kmorgen** [comment] 2020-04-02 14:35
@khouloudbelguith 

If I edit Norway under Languages (even if not changing anything, just saving). It will change the table column 'Locale' to no-NO again, and site will not work. Site only works if I manually change database to nb-NO. Even if writing nb-NO inside Languages, it will use no-no in the database.

**Comment by khouloudbelguith** [comment] 2020-04-02 14:52
@kmorgen, I tried with a fresh install PS1.7.6.4 no-No => OK
I attached a screen record
https://drive.google.com/file/d/1mPysjzbqCUKePK-LnIct7hROM4mKTQwb/view?usp=sharing

Thanks!

**Comment by kmorgen** [comment] 2020-04-02 15:15
@khouloudbelguith Weird, our shop then no longer works with no-NO in the database after the update?!
I noticed you write 'no' in language code when creating language. Can you try with nb-NO (this is actually the IETF tag for Bokmål which is the norwegian language installed. PS also have Nynorsk as a seperate language, so guess 'no' is not really sufficient anymore.

(we probably initially created the language with no-no. Unfortuantely I cannot delete the language and make it again as translations are then lost)

EDIT: What will actually happen if you change locale to nb-NO in the database?

**Comment by khouloudbelguith** [comment] 2020-04-02 15:21
@kmorgen, I tried with nb in the language code => ok 
https://drive.google.com/file/d/1pPup-WyShi61DnCwKs9kUv46ygTTmrLC/view?usp=sharing

Thanks!

**Comment by kmorgen** [comment] 2020-04-02 15:45
@khouloudbelguith In your example the locale remains as no-no no matter the change. Can you try to manually change it to nb-NO and see it FO still works then?

So we can assume it is still supposed to be called no-no in the Locale column. 
So the big question is then why no-no then no longer works after we updated to 1.7.6.4, and why nb-NO suddenly does.

I can only get the site to work when manually changing it to nb-NO (despite we never used this term before). So I assume some code/theme/modules files etc. might now look for nb-NO.

If installing the Nynorsk language, is it also called no-no?. In fact, I would say no-no is the incorrect term for Bokmal. it should probably correctly be called nb-NO.

**Comment by khouloudbelguith** [comment] 2020-04-02 16:06
@kmorgen, it is working also!
https://drive.google.com/file/d/1DnV6WaHkkfb8oCYjFrt7Tz9ygerpU8E4/view?usp=sharing

Thanks!

**Comment by kmorgen** [comment] 2020-04-02 16:13
@khouloudbelguith Well, thats a bit weird isn't it? The same language works with both locale no-no and nb-no as well?

**Comment by khouloudbelguith** [comment] 2020-04-02 16:23
Ping @LouiseBonnard what do you think about this?
>Well, thats a bit weird isn't it? The same language works with both locale no-no and nb-no as well?

Thanks!

**Comment by LouiseBonnard** [comment] 2020-04-02 16:58
@khouloudbelguith, @kmorgen, actually the use of the Norwegian languages is a bit confused in PrestaShop... Bokmal is kind of recognized as the main Norwegian language, this is both locales (no-NO and nb-NO) refer to the same language.

**Comment by khouloudbelguith** [comment] 2020-04-03 09:48
@LouiseBonnard, Thanks :wink: 
@kmorgen, so can I close the issue?

Thanks!

**Comment by kmorgen** [comment] 2020-04-03 11:07
@khouloudbelguith well, the issue is not really solved yet.
Though, I manage to get the site to work again by manually changing database locale to nb-NO, it will change back to no-no when editing Languages (since no-no is the default setting) and the site will then not work again. 

Since only related to this language and happened after the update, something is causing this.

**Comment by khouloudbelguith** [comment] 2020-04-03 11:33
@kmorgen, but I cannot reproduce the issue with all information provided as reported previously.
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by kmorgen** [comment] 2020-04-03 12:57
@khouloudbelguith Yeah, it is weird. Hereby the log file
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4427324/log.txt)

**Comment by khouloudbelguith** [comment] 2020-04-03 16:04
@kmorgen,

In your log file
`All files upgraded.`
`Database upgrade OK`
`Addons modules files have been upgraded.`

There is no problem during the upgrade.
Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4428487/phppsinfo.php.zip)

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by kmorgen** [comment] 2020-04-23 09:39
Hello, sorry for the long reply time.
Have now updated to PS 1.7.6.5 and the issue remains.

![phpinfo](https://user-images.githubusercontent.com/4300688/80084404-1dfd2600-8557-11ea-9aa7-2bc1930105eb.jpg)

**Comment by khouloudbelguith** [comment] 2020-04-23 14:40
Hi @kmorgen,

Can you please provide us the **new** log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
What is the exact version of the 1-click upgrade did you use to make an upgrade from PS1.7.6.4 to PS1.7.6.5?

Thanks!

**Comment by sarahdib** [comment] 2020-05-12 10:10
@kmorgen I will close this issue since your log indicate that all is good. Please contact our merchant success team in order to help you with this problem.

**Closed as completed by sarahdib** 2020-05-12 10:10 UTC
Labels: Bug, Currencies, Autoupgrade, No change required, 1.7.6.1
