### ISSUE TITLE
Multistore wrong email recipient

### ISSUE THREAD

**Issue by Nesta78** [PrestaShop/PrestaShop#23470] opened 2021-03-02 10:05 UTC
#### Describe the bug

Hi,

I'm using Multistore mode.
I setup several emails contacts (1 for each shop). But when a customer send a message from order details, the email is received at the wrong recipient ==> It's always sent to the main shop email address.
#### Expected behavior

The order message sent by the customer should arrive to the email address setted up in BO.
#### Steps to Reproduce

1. Go to order details with customer account in front office
2. Add a message to the order
3. Email is sent to the main shop, instead of the email address setted up in BO

**Screenshots**
As you can see here, configuration seems to be ok 
![1](https://user-images.githubusercontent.com/64215260/109632049-ea136980-7b46-11eb-8fe5-f1db905005dc.jpg)
![2](https://user-images.githubusercontent.com/64215260/109632058-eed81d80-7b46-11eb-93f1-6a41026f8508.jpg)

But email is send to the main shop email address 
![3](https://user-images.githubusercontent.com/64215260/109632134-00212a00-7b47-11eb-9760-3b6ba7041075.jpg)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

Any idea about that ?
Thank you guys :)

**Comment by hibatallahAouadni** [comment] 2021-03-02 11:08
Hello @Nesta78 

Could you please edit your issue description **following the provided template to submit a complete bug report**. Follow these steps to find the template:

1. Click on **New issue** button

![image](https://user-images.githubusercontent.com/23308427/109639615-af61ff00-7b4f-11eb-9568-1f2c3780b6e1.png)

2. Click on the **Get Started** of **Bug Report**

![image](https://user-images.githubusercontent.com/23308427/109639643-b5f07680-7b4f-11eb-857e-f5559e0a5953.png)

3. Fill all the blocks mentioned in the template and please make the **steps to reproduce** clear :wink: 

![image](https://user-images.githubusercontent.com/23308427/109639661-bbe65780-7b4f-11eb-9c73-6ffc765de00f.png)

Then notify me :wink: 
Thanks!

**Comment by Nesta78** [comment] 2021-03-02 11:15
Sorry, must be ok now ?

**Comment by hibatallahAouadni** [comment] 2021-03-03 10:00
Hello @Nesta78 

I didn't reproduce your issue with PS1.7.7.2 and PS1.7.6.7, see the screen record below:

https://drive.google.com/file/d/1lmDJWBHD8ncahjgimhmnS3QOVfs9BKVg/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-23 08:28
Hello @Nesta78 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-23 08:28 UTC
Labels: Bug, BO, Email, Multistore, No change required, 1.7.6.7
