### ISSUE TITLE
Order of payment module not shown on FO

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#12503] opened 2019-02-07 23:16 UTC
**Describe the bug**
I change the order of Payment Module in BO
It's not ok on FO, modules are always in the same order (order of their ID)
I check the table hook_module, and the order is ok, as I put in Modules Positions.
Prestashop 1.7.5.0 / theme Classis

**To Reproduce**
Change Module payment order in BO
No change in FO

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.14

**Comment by khouloudbelguith** [comment] 2019-02-08 08:01
Hi @pppplus,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9756
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-08 08:02
Duplicate of #9756

**Closed as completed by khouloudbelguith** 2019-02-08 08:01 UTC
Labels: Duplicate
