### ISSUE TITLE
Multi-store disappears in the Catalog menu - stock

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#26972] opened 2021-12-14 05:09 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The multistore selection menu disappears from the stock input menu.

https://drive.google.com/file/d/1-D7E1pGx3lmLlBQIzjPp0sfawTLxMEFc/view?usp=sharing

### Expected behavior

It shouldn't disappear in which store the inventory is being handled.

### Steps to reproduce

Enter Catalog
Enter Stock with all stores
Select store to enter stock
It disappears from the top of the menu to which store you are intervening and the store selection also disappears at the top right.
![image](https://user-images.githubusercontent.com/12537826/145936655-f3721eb5-ee8d-4ff9-bce9-63a0afeca8bc.png)

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2021-12-14 09:36
Hello @ocio87 ,

I was able to reproduce the issue with PrestaShop version 1.7.8.2 and develop branch, so I can confirm that this behavior is indeed a bug.
This is a regression as it can't be reproduced on PS 1.7.7.x.

How it was in 1.7.7.8 :
<img width="1231" alt="Screenshot 2021-12-14 at 10 33 56" src="https://user-images.githubusercontent.com/16019289/145972237-ada22292-23d0-4637-b6c7-3e5ce58dbe2d.png">
 
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment] 2021-12-27 10:01
https://user-images.githubusercontent.com/43613217/147460629-0560e2e6-b922-4e90-b7ec-4999615bf2e2.mp4

**Comment by atomiix** [comment] 2022-01-17 10:44
This issue seems to have been solved as it is not reproducible both on 1.7.8.x & develop branches.

**Closed as completed by atomiix** 2022-01-17 10:44 UTC
Labels: Bug, Minor, BO, Stocks, Multistore, Regression, 1.7.8.0, Invalid

**Comment by ocio87** [comment] 2022-01-17 12:33
Hello @atomiix ,

What change must be made so that it can show the store in Stock?

Thanks,

**Comment by MatShir** [comment] 2022-01-17 13:51
Edit: @ocio87 It is fixed in the next release the 1.7.8.3 PrestaShop version that is going to release in couple weeks :)

**Comment by ocio87** [comment] 2022-01-17 13:52
Perfect @MatShir, thank you very much!
