### ISSUE TITLE
Shipping costs in customer account not respect the customer group price display method 

### ISSUE THREAD

**Issue by DelecroixQuentin** [PrestaShop/PrestaShop#25825] opened 2021-09-09 09:28 UTC
#### Describe the bug

The `!$order->getTaxCalculationMethod()` condition is reversed, you can find it here: 
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Order/OrderDetailLazyArray.php#L231-L233

The condition is reversed because if the price is to be displayed in VAT, the function `Group::getPriceDisplayMethod((int) $customer->id_default_group)` must return 0 else if it is to be displayed in HT it must return 1.
See : https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/Order.php#L296-L301

So in case customer is in VAT display method group
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/Order.php#L298
will set `$this->_taxCalculationMethod` as 0 and so `$order->getTaxCalculationMethod()` will return 0 in `OrderDetailLazyArray`

That mean `!$order->getTaxCalculationMethod()` will be true, so `$shipping['shipping_cost_tax_excl']` is use instead `$shipping['shipping_cost_tax_incl']`.

#### Expected behavior

If the customer group is configured to display prices including VAT, the shipping costs must be displayed in VAT.

#### Steps to Reproduce

1. Place an order with a customer in a group that displays prices including VAT.
2. Go to the customer's order history, open the order details
3. See error: 
![image](https://user-images.githubusercontent.com/8830801/132658934-5d46086d-d39a-494d-a275-4737c83e0724.png)

#### Additional information

* PrestaShop version: 1.7.7.5 (same on 1.7.7.7)
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-09-09 15:07
Hello @DelecroixQuentin 

Your issue seems related to this one #9815 could your please check it.
Please check and feedback.

Thanks!

**Comment by DelecroixQuentin** [comment] 2021-09-09 15:51
Hello @hibatallahAouadni,

No, it's not an issue about rounding but about price display method VAT incl / VAT excl.
The first shipping cost (14.9) is VAT incl (compute in `OrderSubtotalLazyArray`).
The second shipping cost (12.42) is VAT excl (compute in `OrderDetailLazyArray`).

The two shipping cost must be in the same price display method.

**Comment by florine2623** [comment] 2021-09-10 07:42
Hello @DelecroixQuentin ,

I can't reproduce your issue in 1.7.7.x.

In order confirmation page :
<img width="1083" alt="Screenshot 2021-09-10 at 09 36 17" src="https://user-images.githubusercontent.com/16019289/132818519-eb0b5926-b26e-48bc-838d-818a6576675d.png">

In email received by customer :
<img width="515" alt="Screenshot 2021-09-10 at 09 36 24" src="https://user-images.githubusercontent.com/16019289/132818459-75612537-eb68-44db-9f21-6f4aa53448af.png">

In customer's order detail history :
<img width="1095" alt="Screenshot 2021-09-10 at 09 39 06" src="https://user-images.githubusercontent.com/16019289/132818501-fed1b17f-9b6d-4724-b3ce-9ab3e8621354.png">

How is your carrier tax set ? like this : 
<img width="281" alt="Screenshot 2021-09-10 at 09 40 43" src="https://user-images.githubusercontent.com/16019289/132818357-6777591d-71d8-460a-b224-16608e333482.png">

Please check and feedback.

**Comment by DelecroixQuentin** [comment] 2021-09-10 09:10
Hi @florine2623,
Issue is on customer's order detail history only, not email

Carrier configuration: 
![image](https://user-images.githubusercontent.com/8830801/132829355-fa6d67e7-ae5d-484a-803f-ad330d06264d.png)

On PS 1.7.7.7 with classic theme :
![image](https://user-images.githubusercontent.com/8830801/132829897-c00d5b32-a175-473c-a8b8-3031850f0ad5.png)

There are 2 blocks on customer's order detail history which display shipping cost, and the value of each block is not the same (one is VAT included, other one is VAT excluded).

**Comment by florine2623** [comment] 2021-09-14 09:53
Hello @DelecroixQuentin ,

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19132.
To be informed when it's fixed, please subscribe to the issue mentioned above.
I'll close your issue to avoid backlog.

Thank you

**Comment by florine2623** [comment] 2021-09-14 09:53
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19132

**Closed as completed by florine2623** 2021-09-14 09:53 UTC
Labels: Bug, FO, Duplicate, Order, Shipping, VAT, Taxes and Prices, 1.7.7.5
