### ISSUE TITLE
On prices drop, new products pages sort by price sorts only products on this page but not in whole

### ISSUE THREAD

**Issue by rzuf666** [PrestaShop/PrestaShop#25309] opened 2021-07-09 17:52 UTC
On prices drop, new products pages sort by price sorts only products on this page (pagination) but not in whole. If user go to page 2 or more the sorting position are unexpected. This is about if products have attributes and products have set specyfic price.

This leads to a situation that when sorting from the cheapest to the most expensive, we can have the cheaper product on the page, e.g. 2 than 1 .

I tested a loto of products with size attribute and set specyfic price to all attributes with amount or percent.

I think this bug is linked with this resolved issue - https://github.com/PrestaShop/PrestaShop/issues/10010  - @marionf @colinegin 
The same problem was in categories but has been solved. Apparently, on special non-category product pages, the problem remained.

Please, somebody look into this. In Prices Drop page sorting about price low / high is very important. Customers looking by this best prices on sales. Our customers see this and they report this to me. This bug with Prices Drop / new product pages and sorting by price is still in Prestashop from 1.5 version. 

Tested on Prestashop 1.7.7.5 and 1.5.6.2 - in both the same bug.

#### Expected behavior

Products in special subpages (prices drop, new product etc.) should be displayed in decreasing or decreasing order within all pages of pagination during sorting.

#### Steps to Reproduce

Add some products with attributes, set special price in every product than try sort by price with pagination.

#### Additional information

* PrestaShop version: 1.7.7.5 (and legacy 1.5.6.2 :) )
* PHP version: 7.3

**Screenshots**
![product-drop-bug](https://user-images.githubusercontent.com/60318358/125117873-222b4a00-e0ef-11eb-9ba0-b294bf01650e.jpg)

**Comment by rzuf666** [comment] 2021-07-09 22:21
It looks like these problems will be fixed in Prestashop 1.7.8 as I found a solution to my problems in the code of this version. However, there is still a bug, I described it here - https://github.com/PrestaShop/PrestaShop/issues/25310

**Comment by hibatallahAouadni** [comment] 2021-07-12 08:50
Hello @rzuf666 

I didn't manage to reproduce your issue with PS1775, see the attached screen record below:

https://drive.google.com/file/d/1HtlJOeJJD3zn1ZxqszQO6b_VewCdzuPt/view

The only issue I reproduce is #19810.
Please check and feedback.

Thanks!

**Comment by rzuf666** [comment] 2021-07-12 14:30
Hi @hibatallahAouadni  
I don't think you fully understood what the problem is. Sorting by price does not work on special pages "prices-drop" where only products with a discount and "new-products" are displayed where only products marked as new are displayed. 

Subpages running in the default preset at the addresses:

some-domain.com/new-products 
some-domain.com/prices-drop
maybe in  some-domain.com/best-sales  but I have no way to check it (because I have no sales in the test store)

This issue does not apply in cathegories with Faceted Search. There are no filters on these special subpages and Faceted Search does not work in them. Although I am curious why, these subpages dont have Faceted Search in Prestashop for years. It should be. 

The problem is visible if there are many products with promotions on these subpages. Then, for example, it sorts from the cheapest to the most expensive, but within the pagination page you are currently viewing. When you go to the next one, you will see the products from the cheapest to the most expensive, but the price of the cheapest is lower than the last product on the previous page. 

In your video, you show products in the category. And that's not the place it is about. In terms, there was the same problem, but in version 1.7.7.5 it was fixed. Other subpages with products that are not categories have not been repaired.

However, it looks like it will be fixed in PS version 1.7.8, but the variable order bug that it points to here must be fixed - https://github.com/PrestaShop/PrestaShop/issues/25310 

Some code specialist in PrestaShop should comment on this topic :)

**Comment by florine2623** [comment] 2021-07-13 16:56
Hello @rzuf666 ,

I didn't manage to reproduce your issue in PS 1.7.7.5.

**Page new-products :**
<img width="658" alt="Screenshot 2021-07-13 at 18 49 48" src="https://user-images.githubusercontent.com/16019289/125493323-e7cb7dbf-80f2-4a0a-973a-12633aa2b7ad.png">
<img width="639" alt="Screenshot 2021-07-13 at 18 49 53" src="https://user-images.githubusercontent.com/16019289/125493338-b821dea9-8725-48c4-8981-2b342753a53f.png">

**Page on-sale :**
<img width="836" alt="Screenshot 2021-07-13 at 18 54 41" src="https://user-images.githubusercontent.com/16019289/125493959-510568ae-60af-4469-b97a-4c20a23f0ec4.png">
<img width="847" alt="Screenshot 2021-07-13 at 18 54 46" src="https://user-images.githubusercontent.com/16019289/125493963-c913675f-f526-477d-993e-9089bd45055a.png">

Am I missing something ?

Thanks!

**Comment by rzuf666** [comment] 2021-07-14 14:16
@florine2623  Yes, can't you see it? You can see it in your screenshots :)

It showed you well in new products, apparently it may be related to a small amount of discounted products.

However, in the screenshots from the sale, note that you have products with prices:

On Sale Page 1 prices:  7.74  /  17.68 /  22.94 
On Sale Page 2 prices:  12.92  /  24.80

So sorting does not work as a whole on all products on sale, but per page.

It should be like this:

On Sale Page 1 prices:  7.74  /  12.92  /  17.68 
On Sale Page 2 prices:  22.94  /  24.80

Can you see it now?

**Comment by khouloudbelguith** [comment] 2021-07-16 11:35
Hi @rzuf666,

Thanks for these clarifications.
I did not manage to reproduce the issue with branch 177x (PS1776) using the ps_facetedsearch v3.7.1.
I checked these pages:
1. Price drop
2. New products
3. Best sales

https://drive.google.com/file/d/1w9jtcCpGiGb0jQYCB3ncxjJFfFwIuVRr/view?usp=sharing

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment] 2021-08-04 10:19
Hello @rzuf666 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-04 10:19 UTC
Labels: Bug, FO, Taxes and Prices, Faceted search, No change required, 1.7.7.5
