### ISSUE TITLE
HTTP 200 -parsererror-

### ISSUE THREAD

**Issue by Hightmar** [PrestaShop/PrestaShop#16663] opened 2019-12-02 21:26 UTC
**Describe the bug**
Installation fails at 67% when installing addons
phppsinfo.php say everything is OK with the config
max_input_time & max_execution_time set up at 600 sec

**To Reproduce**
Happens during installation

**Screenshots**
![install_bug](https://user-images.githubusercontent.com/32802347/69996519-87ea4400-1552-11ea-8ed1-93ed95ac22bc.PNG)
![phppsinfo](https://user-images.githubusercontent.com/32802347/69996521-87ea4400-1552-11ea-9d08-d928ef84ab96.PNG)
![phppsinfo1](https://user-images.githubusercontent.com/32802347/69996517-8751ad80-1552-11ea-8fd4-fd7509442629.PNG)
`

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.25

**Comment by khouloudbelguith** [comment] 2019-12-03 08:40
Hi @Hightmar,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source), downloaded from the official link?
 - debug mode report, try to enable the debug mode & try to re-install again
>edit the config/defines.inc.php file. Find the following line in the file:
`define('_PS_MODE_DEV_', false);`
… and change it to:
`define('_PS_MODE_DEV_', true);`

 - PHP error logs (have you any logs in your Prestashop_folder/var/logs/ path?)
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-02 07:58
Hi @Hightmar,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-02 07:58 UTC
Labels: Bug, IN, No change required, 1.7.6.2

**Comment by PEscar** [comment] 2020-11-06 00:16
Having similar ( maybe same ) problem.

![image](https://user-images.githubusercontent.com/28983045/98310582-a318cb80-1fcd-11eb-888b-55c106e5f799.png)

**Comment by khouloudbelguith** [comment] 2020-11-06 07:43
Hi @PEscar,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
