### ISSUE TITLE
Import csv changes main category assigned to article

### ISSUE THREAD

**Issue by Manuel905** [PrestaShop/PrestaShop#24361] opened 2021-05-06 06:41 UTC
Good Morning;
When importing a CSV with a simple update of product stock, the association that the product has in the category is changed. Attached image example csv, 2st example associated category, 3nd as it remains after import.

![cambios de categoria csv img 1](https://user-images.githubusercontent.com/83748387/117252275-0208b180-ae46-11eb-8c6b-96c1dedeedd9.JPG)
![cambios de categoria img2](https://user-images.githubusercontent.com/83748387/117252412-34b2aa00-ae46-11eb-9493-79479552cc8f.JPG)
![cambios de categoria img3](https://user-images.githubusercontent.com/83748387/117252431-3bd9b800-ae46-11eb-9c88-cc4ac92b7efa.JPG)
I attach a photo of the configuration in prestashop, there are only three columns and the description, it is in ignore columns,
![cambios de categoria importar csv img4](https://user-images.githubusercontent.com/83748387/117252541-66c40c00-ae46-11eb-9591-f0fad80d8367.JPG)
I have created a new installation of prestashop 1.7.7.3, without adding any theme, to rule out that it could be from the theme, I have created a category and subcategory and then a product, to do a test on a clean installation, the problem also occurs.
Let's see if anyone can reproduce this, I get this error.
Thank you.

**Comment by hibatallahAouadni** [comment] 2021-05-06 08:08
Hello @Manuel905 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22336. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-06 08:08
Duplicate of #22336

**Closed as completed by hibatallahAouadni** 2021-05-06 08:08 UTC
Labels: Duplicate
