### ISSUE TITLE
Invoice address reset when in carrier step click on personal information.

### ISSUE THREAD

**Issue by MassimoGS3** [PrestaShop/PrestaShop#22456] opened 2020-12-16 15:00 UTC
#### Describe the bug

Stepping on checkout process prestashop reset the invoice address.

#### Expected behavior

I'm expected was the invoice addresses previous inserted

#### Steps to Reproduce

The issue is in checkout.
1. Fill personal information.
2. Fill delivery addresses information ( you must uncheck "use same addresses for invoice)
3. Fill invoice addresses information.
4. In carrier section click on step 1. Personal information.
5. Re-fill personal information and press "Continue".
6. The procedure landing on step 3. (Carrier).
7. Click on step 2. (Addresses information).

You have two addresses saved. On Invoice address  does not set the previous inserted but the same of delivery.

**Screenshots**
![Example](https://user-images.githubusercontent.com/76114491/102365152-881b7d00-3fb7-11eb-9f57-c421f6c9dce1.PNG)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.34

Someone have a temporary fix ?

**Comment by florine2623** [comment] 2020-12-17 08:26
Hello @MassimoGS3 ,

Your issue is fixed in PS 1.7.8.0.
You can check it here : https://github.com/PrestaShop/PrestaShop/issues/11595.

I'll close your issue.

Thank you

**Comment by florine2623** [comment] 2020-12-17 08:30
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/11595

**Closed as completed by florine2623** 2020-12-17 08:30 UTC
Labels: Bug, Minor, FO, Addresses, Fixed, 1.7.5.2, Checkout, 1.7.7.0

**Comment by MassimoGS3** [comment] 2020-12-17 17:21
@florine2623 i've see other reporting error.
I think was different issue.
i've found the section code where it's reset.
My issue is explicit only on "Personal Information" Step.

![image](https://user-images.githubusercontent.com/76114491/102520900-8378c680-4094-11eb-8918-9f7c9c3b5649.png)
