### ISSUE TITLE
Mail  getTemplateBasePath bug

### ISSUE THREAD

**Issue by adu42** [PrestaShop/PrestaShop#15250] opened 2019-08-24 01:27 UTC
**Describe the bug**
the path can not find base template email core path.
$templatePath . $isoTemplate . '.txt'
$templatePath . $isoTemplate . '.html'

Just look the code..

And mails template file are xxx.html.twig, 
Path in core/

**Additional information**
PrestaShop version: 1.7.7.0
PHP version:7.2

**Comment by khouloudbelguith** [comment] 2019-08-26 12:20
Hi @adu42,

Thanks for your report.
Could you please povide us the exact steps to reproduce your issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-25 07:50
Hi @adu42,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-25 07:50 UTC
Labels: Bug, develop, No change required

**Comment by shawe** [comment] 2019-09-27 15:32
Problem also exists on 1.7.6.1 @adu42 @khouloudbelguith

This line is replacing the $templatePath given as parameter:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Mail.php#L393
Comenting it can read the template file.

The problem maybe was related on how $moduleName is filled outside the foreach.
This problem seems to only affect when a module is trying to send emails with their own templates.

Why the issues are closed if it really has a problem and is not solved? I can understand that not all bugs can be fixed fast, but closing existing issues that are not solved doesn't help to find the same problem and add more details from others that have the same issue.

Steps to reproduce it:
- Create a tiny module with only a controller that try to send a mail from a template inside the same module.
- The template is never readed, and the mail can't be sended.
