### ISSUE TITLE
In the input "generate" block only 5 attributes with similar names will be displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12006] opened 2019-01-03 10:49 UTC
**Describe the bug**
In the BO => Products => Product detail page => Combinations Tab, when we have more than 5 attributes start with the same characters => in the input "generate" block only 5 attributes will be displayed.
**To Reproduce**
1. Go to BO => Catalog => Atributes => Create more than 5 attributes which they start with the same characters
![image](https://user-images.githubusercontent.com/16067358/50633844-06a6bd80-0f4d-11e9-96e0-f7cb96b7cfc4.png)
2. Go to BO => Products => Product detail page => Combinations Tab
3. In the input "generate" block => enter the first characters => only 5 attributes will be displayed
![image](https://user-images.githubusercontent.com/16067358/50633955-55ecee00-0f4d-11e9-97f1-c6092b7630eb.png)

**Additionnal information**
PrestaShop version: 1.7.4.4 / 1.7.5.0
PHP version: 7.1

**Comment by marionf** [comment] 2019-01-03 14:19
Duplicate of #9939

**Closed as completed by marionf** 2019-01-03 14:19 UTC
Labels: Bug, Minor, BO, Duplicate, Combinations, 1.7.5.0
