### ISSUE TITLE
Javascript not included in correct order in back office when added from module

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#15023] opened 2019-08-07 14:03 UTC
When adding a javascript file to the back office using the Controller::addJs function, it is being included before the jquery libraries are loaded.

Screenshots are from the welcome module (which I assume is loading the files correctly).

This means that if the js file you are loading uses jquery, you will receive an error that the library has not been loaded.

The front controller has the new registerJavascript function, which mitigates this, but this funcion is not available to the admin controller.

**To Reproduce**
1. See the attached images.

**Screenshots**
![image](https://user-images.githubusercontent.com/19314911/62628828-a8322b00-b8f1-11e9-903b-d91123ee7e53.png)

![image](https://user-images.githubusercontent.com/19314911/62628888-c3049f80-b8f1-11e9-9377-5bf55d180baa.png)

![image](https://user-images.githubusercontent.com/19314911/62629127-360e1600-b8f2-11e9-9336-42e69a7657d3.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-07 14:20
Hi @roja45,

Thanks for your report.
In my case also, the back office using the Controller::addJs function, it is being included before the jquery libraries are loaded.
But there is no error in the console.
I attached a screen record
https://drive.google.com/file/d/1yrjz8ghOcc9qGHGgPjxCwlrfHudezvqE/view
Thanks to check & feedback.

**Comment by roja45** [comment] 2019-08-07 15:32
Sorry, I wasn't clear.

There is no issue with the welcome module, that is not using jquery in the js file.

The error is from a js file loaded that **does** use jquery.

**Comment by roja45** [comment] 2019-08-07 15:35
actually, you can probably close this.  There appears to besomething of a work around.

Using this code,

`
if (method_exists($this->context->controller, 'addJquery')) {
            $this->context->controller->addJS($this->_path . 'views/js/roja45notifications.js');
}
`

will force it to load at the end, and prevent the error.  The gamification module uses this.

**Comment by khouloudbelguith** [comment] 2019-08-07 15:36
@roja45, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-07 15:36 UTC
Labels: BO, Welcome, No change required, 1.7.6.0

**Comment by damianobertuna** [comment] 2019-12-16 09:34
Hi,

the problem is still present, I read in this page that is not possible anymore to use addJQuery:
https://devdocs.prestashop.com/1.7/modules/core_updates/1.7.6

But if I try to load a js file (that uses jQuery) in a module I'm developing, I have an error in the console ("JQuery is not defined").

It's not clear how to solve this problem.

Regards.

**Comment by khouloudbelguith** [comment] 2019-12-30 10:31
Issue created here: https://github.com/PrestaShop/PrestaShop/issues/16944
