### ISSUE TITLE
Saving product with combination without value in quantity field.

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#22165] opened 2020-12-01 10:38 UTC
#### Describe the bug

During product saving, that in one of its combinations has empty quantity field (not 0 but just empty) the error appears "unable to update settings". There is no information what is wrong.

#### Expected behavior

When the quantity field is empty the system should assume 0, or inform clearly the user that the problem with saving is in combinations, in a specific combination field.

#### Steps to Reproduce

Go to product edit, (switch to product with combinations), in combinations tab remove the number from one of the combinations quantities fields. Click save.

  
#### Additional information

* PrestaShop version:  1.7.6.1

**Comment by hibatallahAouadni** [comment] 2020-12-01 11:09
Hello @grzegorzgit 

I managed to reproduce your issue with PS1.7.6.2, PS1.7.6.9 and PS1.7.7.0_build2, see the attached screen record below:

https://drive.google.com/file/d/1yhiR7J-geOw6fOOc4luYQDlKMRm55RP6/view

But, I think what you are suggesting is an improvement, we need to improve / specify the error message, so that the user knows exactly where it went wrong. So, thanks for the suggestion, the product team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , what do you think?

**Comment by LouiseBonnard** [comment] 2020-12-01 16:38
I concur, thanks @grzegorzgit and @hibatallahAouadni! @marionf, should we add it to the specifications [here](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#combinations-tab-epic)?

**Comment by marionf** [comment] 2020-12-03 10:17
This occurs also with standard product: if you empty the quantity field (which 0 by default) and save, then the error "unable to update settings" is displayed + "This value should not be blank." under the quantity field are displayed

I think we shouldn't put 0 when the field is empty because we don't know if the merchant forget to fill the quantity or if he/she removed it by mistake.

I think we should rather display a more explicit error message than just "unable to update settings"

wdyt @MatShir ?

**Comment by MatShir** [comment] 2023-07-04 15:53
Fixed on the new product page on PS 8.1 :)

**Closed as completed by MatShir** 2023-07-04 15:53 UTC
Labels: Feature, BO, Combinations, Fixed
