### ISSUE TITLE
wrong translation in admin panel (Persian-fa)

### ISSUE THREAD

**Issue by shahin0x** [PrestaShop/PrestaShop#11392] opened 2018-11-14 15:14 UTC
Hello
Translation of fifth item of SELL section(Stats) is correct in AdminNavigationMenu.xlf file, but panel shows translation of "States" instead of "Stats"

[https://i.postimg.cc/j5w7sxVk/stats.jpg](url)

`File: classes/lang/KeysReference/TabLang.php:113</note>
      </trans-unit>
      <trans-unit id="b8464cdd84b5f068ad72bf5c4f32163d" approved="yes">
        <source>States</source>
        <target xml:lang="fa" state="translated">استان‎ها</target>
        <note>Context:		
File: classes/lang/KeysReference/TabLang.php:114</note>
      </trans-unit>
      <trans-unit id="452a7601dbc6f2c38aa89e68bda8b603" approved="yes">
        <source>Stats</source>
        <target xml:lang="fa" state="translated">آمار</target>
        <note>Context:`

**Comment by khouloudbelguith** [comment] 2018-11-14 15:28
Hi @shahin0x,

Thanks for your report.
What is the exact language did you use? did you installed your shop with which language/country?
Thanks!

**Comment by shahin0x** [comment] 2018-11-14 15:45
> Hi @shahin0x,
> 
> Thanks for your report.
> What is the exact language did you use? did you installed your shop with which language/country?
> Thanks!

Persian Language (fa)

**Comment by khouloudbelguith** [comment] 2018-11-14 16:35
Hi @shahin0x,

Thanks for your feedback.
I manage to reproduce the issue with PS1.7.4.4.
The `Stats` is showed `استان ها` which is wrong.
![image](https://user-images.githubusercontent.com/16067358/48497043-a7bda580-e833-11e8-8b78-3076815d3842.png)
@LouiseBonnard what do you think? it could be fixed in Crowdin
Thanks!

**Comment by LouiseBonnard** [comment] 2018-11-14 16:38
@khouloudbelguith, it can not because it is all right in Crowdin, then I guess that it is a bug... I asked @shahin0x to open an issue on GitHub to see it fixed.

**Comment by khouloudbelguith** [comment] 2018-11-14 16:41
@LouiseBonnard thanks!
@marionf, what do you think?

**Comment by shahin0x** [comment] 2018-11-14 18:07
i found problem. its in database ps_tab_lang table. 
![ps_tab_lang](https://user-images.githubusercontent.com/45041106/48502635-427aac00-e855-11e8-8cef-43686ea5992c.jpg)

**Comment by shahin0x** [comment] 2018-11-14 18:14
it happens just if the default language be Persian. in case of installing Persian language manually, translation appears correctly

**Comment by khouloudbelguith** [comment] 2018-11-15 07:52
@shahin0x, thanks for this clarifications.

**Comment by marionf** [comment] 2019-05-28 13:18
@khouloudbelguith Could you try to reproduce it with 1.7.6.0 ?

**Comment by khouloudbelguith** [comment] 2019-05-28 13:25
Hi @marionf,

I cannot reproduce it with PS1.7.6.0
![image](https://user-images.githubusercontent.com/16067358/58481491-6435e380-8154-11e9-8cd0-94366dcbade4.png)
It is correct now.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-28 13:25 UTC
Labels: Bug, Minor, BO, Stats, International, Fixed
