### ISSUE TITLE
Cart refreshing problem 

### ISSUE THREAD

**Issue by msornin** [PrestaShop/PrestaShop#18709] opened 2020-04-20 07:50 UTC
I post a request for help again, my first request has been pending since Friday evening:

Cart refreshing problem #18693

Excuse me for my language, I translated with google. 

For some time, when I add a product to the cart, it does not update and the pop up no longer appears, to offer me to "Continue my purchases" or "Order".
If I click on Home, the Basket is updated.
I activated debub mode in the file "define.inc.ph", it does not report any error.
I returned the original theme, deactivated all the modules one by one, emptied the caches correctly each time, deleted the contents of the cache folder located in the var folder, without success.
Thank you.

Michelle

* Version PrestaShop: 7.5.2 - Thème classic
* Version PHP: 7.1

**Comment by msornin** [comment] 2020-04-20 11:28
Someone to help me? Please

**Comment by msornin** [comment] 2020-04-20 14:46
> Someone to help me? Please
I have no response. No doubt I expressed myself badly? What can I do ?

**Comment by khouloudbelguith** [comment] 2020-04-20 14:50
Hi @msornin,

Here's the PR: #17633 to fix the issue.
Your ticket is a duplicate of #16665
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-20 14:50
Duplicate of #16665

**Closed as completed by khouloudbelguith** 2020-04-20 14:50 UTC
Labels: Duplicate
