### ISSUE TITLE
Shop associations for cart_rules are saved without taking into account the employee permissions

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28148] opened 2022-04-06 12:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In a multishop environment, when selecting all available shop in Shop selection, nothing is saved to `ps_cart_rule_shop`, or if there are entries, they are deleted. This is correct if the employee has access to all shop. It is wrong if not.

**Case 1:**
An employee has access to only one shop. If he creates a cart rule, it is valid in all shops. There is no way to avoid this behavior.
This can have disastrous consequences: If the employee does not understand what he does, he can offer free orders in any random shop. If shops are independent, this is a nightmare.

**Case 2:**
A cart rule is limited to one shop (created by an employee with permissions for more than one shop).
An other employee, that has only permissions in that shop, views the cart rule and saves it without changes.
Now the cart rule is corrupted, and applies to all shops.

**Case 3:**
A cart rule is limited to one shop. An employee with access to two shops adds the second shop and saves it. Now the cart rule is valid in all shops, and the checkbox `shop restriction` has been removed (what represents an error).

### Expected behavior

I expect, that the shop associations of a cart rule reflect the permissions of the creator of the rule. There must be no possible permission escalation.

**Case 1:**
If an employee is restricted to a set of shops, all cart rules he creates must be restricted to shops inside that set.

**Case 2:**
If a cart rule is limited to a set of shops, these shop associations must not change, unless there is a explicit action by the user.

**Case 3:**
If `Shop restriction` is checked, it must not be removed. A cart rule associated to two shops must remain associated to the two shops, unless there is a explicit action by the user.

### Steps to reproduce

Setup:
- Multishop environment with at least three shops
- Edit or create a employee profile with permissions for cart rules, and use this profile for creating two employees as follows:
- An employee A that has permissions only for shop A
- An employee B that has permissions for shop A and B

**Case 1:**
1. Log in as employee A
2. Create a cart rule
3. Note that there is no option to select `Shop restriction` in the conditions tab 
![image](https://user-images.githubusercontent.com/16067358/162452737-0c30e332-7647-4a65-b157-3c818eb5ef4c.png)
4. Log in as super admin
5. Find the new cart rule, click on `Edit`
6. In the conditions tab > note that the cart rule has no `Shop restriction` and is valid in all shops.

https://user-images.githubusercontent.com/16067358/162452982-80e2717a-bb57-4b4b-9878-550c0c705eae.mp4

**Case 2:**
1. Log in as super admin
2. Create a cart rule restricted to shop A
3. Log in as user A
4. View the cart rule, do not make any modification, and click on `Save`
5. Log in as super admin
6. Note that the shop restriction has been removed from the cart rule

**Case 3:**
1. Log in as user B
2. Create a cart rule restricted to shop A
3. Edit the cart rule
4. Add shop B to the shop restrictions, click `Save and stay`
5. Note that `Shop restrictions` has been unchecked
6. You can note the same thing as super admin

### PrestaShop version(s) where the bug happened

1.6.1.1, 1.7.7.1, 1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by lmeyer1** [comment] 2022-04-06 12:12
Replaces #23082, that I close in favor of this one.

**Comment by hibatallahAouadni** [comment] 2022-04-07 11:30
Hello @lmeyer1 

Which profile do you choose for employee A and employee B?
Because if you choose **SuperAdmin** you can't restrict its permissions on other shops.

https://user-images.githubusercontent.com/23308427/162188981-62341365-aa2f-4d00-bcba-18984cf04c26.mp4

If **Logistician** or **Translator** or **Salesman**, you do not have permission to access the discounts/cart rules page by default.
Waiting for your feedback.

Thanks!

**Comment by lmeyer1** [comment] 2022-04-07 11:36
@hibatallahAouadni Hello, I didn't notice that the profile configuration in my shops is not the standard one.
I've chose `Salesman`, and in my installation salesmen have the permission to create cart rules.

This also means that these bugs cannot happen when all profiles are configured with the default permissions.

**Comment by khouloudbelguith** [comment] 2022-04-08 14:21
Hi @lmeyer1,

Thanks for your feedback.
I manage to reproduce the issue with PS1778 & PS1785.
so I can confirm that this behavior is indeed a bug.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Closed as completed** 2022-05-03 14:41 UTC
Labels: Bug, Minor, BO, Multistore, Cart rules, Employees, Fixed, PR available, Verified
