### ISSUE TITLE
Unable to unselect a dropdown in grid filter

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27530] opened 2022-01-29 13:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

You are unable to “unselect” a select/dropdown filter in backoffice listing grid without completely resetting all filters. See how to reproduce.

### Expected behavior

You should be able to unselect all filters one by one.

### Steps to reproduce

1. Open backoffice customers.
2. Filter by name and select only active customers. Press search.
3. Now put active back to blank and press search again.
4. Active stays set to Yes instead of blank. 🔴 

Only way to get rid of the active filter is to press reset - delete all filters and start again.

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

all

**Comment by PrestaEdit** [comment] 2022-01-29 19:26
Hi,

I'm not able to reproduce this on 1.7.8.2 and develop branch.

The only thing I noticed is the "All" label that is white/blank on 1.7.8.2 version.

**Comment by hibatallahAouadni** [comment] 2022-01-30 23:18
Hello @Hlavtox 

I didn't manage to reproduce the issue with PS1783 neither on develop as @PrestaEdit mentioned above.

Did you disable all your overrides and your third-party modules?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-02-17 08:04
Hello @Hlavtox 

Since we had no news from you for days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-02-17 08:04 UTC
Labels: Bug, BO, Customer, Invalid
