### ISSUE TITLE
Price display problem on product page

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#14446] opened 2019-07-01 15:51 UTC
When adding a tax rule, the prices displayed on the product pages are now wrong (no more taxes calculated)

**To Reproduce**
1. Using only one tax, the french VAT at 20%, based on shipping address
2. Declare 2 tax rules : 
-the 20% VAT for France, with postal codes 01000 - 96999
-another rule for postal codes 97000 - 99999 with no tax (to ship in french islands)
3. go to any product page in your catalog, price tab
4. See error : taxed price is the same than no tax price, even if you selected the 20% tax

See attached screenshot :
<img width="999" alt="Capture d’écran 2019-07-01 à 17 39 52" src="https://user-images.githubusercontent.com/32092528/60449811-c046c880-9c28-11e9-84b7-dfc3a9e05b24.png">

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by elmanu13** [comment] 2019-07-01 15:53
Just note that the price is correct in the front office. The problem concerns back office only (but a real pain to calculate final public prices

**Comment by khouloudbelguith** [comment] 2019-07-01 16:17
Hi @elmanu13,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
https://drive.google.com/file/d/1ksduSEgDAMY305TcBhYw8UMH6BGRB_F9/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by nielsverhoeven84** [comment] 2019-07-09 12:25
@khouloudbelguith When can we expect a fix for this issue?

**Comment by khouloudbelguith** [comment] 2019-07-09 12:36
Hi @nielsverhoeven84,

This issue is added to our bug roadmap.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by aniszr** [comment] 2023-05-30 08:11
Hi,

I think this issue should be closed since i couldn't reproduce it.

If you choose a specific `Tax rule` for your product,the `Retail Price(tax incl)`is automatically filled based on retail price and tax rule chosen,however if you try to modify the `Retail price(tax incl)` field you can observe that the `Retail price(tax excl)` is automatically updated to keep up correct values corresponding to tax rule and Retail price(tax incl). 

see in linked video,

https://github.com/PrestaShop/PrestaShop/assets/92626242/12d53079-43e8-43a5-a5bc-67b2f7e8798f


Additional Infos:
PS Version :8.0.4
PHP version:8.0.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-05-30 16:00
Hello @aniszr 

As you mentioned the issue is already fixed with PS804 in both pages Product V1 & V2, see the attached screen record below:

[issue_14446.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/5ddca087-b91f-41a7-90c2-5ae433a6fa06)

Closing the issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-30 16:00 UTC
Labels: Bug, Minor, BO, Taxes and Prices, Fixed, 1.7.5.2
