### ISSUE TITLE
FO -  Your account  - Add/Edit Addresses - unclear alert when we have invalid address

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26833] opened 2021-12-02 10:02 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > Your account > Add/update address => when have an address with invalid data in the `address` field => unclear error
![image](https://user-images.githubusercontent.com/16067358/144399926-3b4feb6c-d4c8-47c1-918a-7076a0a257b5.png)

In the PS1778, we have
![image](https://user-images.githubusercontent.com/16067358/144400144-d1ff1502-11fe-496a-8e58-2ab63f1885fc.png)

### Steps to reproduce

1. Go to FO > Sign in and try to add a new address
2. In the address field, add invalid data for example `address_`
3. Click on Save

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.1, 1.7.8.2build1

### PHP version(s) where the bug happened

7.2, 7.3

**Comment by MatShir** [comment] 2021-12-13 14:20
Maybe, we should check why the behavior changed before fixing it 🤔

**Comment by rsoulard-prolaser** [comment] 2022-01-17 14:05
Hello,

The problem is here:
https://github.com/PrestaShop/PrestaShop/blob/507da67f87e222caffadeeb26dfa79a3293192c2/classes/form/AbstractForm.php#L151-L170
The `continue;` line 169 should be placed between line 158 and 159.
I can create a PR if you want.

**Comment by atomiix** [comment] 2022-01-17 15:06
@rsoulard-prolaser nice catch! Waiting for you PR :)

**Comment by Progi1984** [comment] 2022-01-30 08:43
Fixed by @rsoulard-prolaser in #27376 and tested by @marwachelly

**Closed as completed by Progi1984** 2022-01-30 08:43 UTC
Labels: Bug, Trivial, FO, Customer, Addresses, Regression, PR available, 1.7.8.0, Verified
