### ISSUE TITLE
Can't add PNG or JPG file in module Customer Reassurance

### ISSUE THREAD

**Issue by ASchmidt84** [PrestaShop/PrestaShop#20295] opened 2020-07-23 10:38 UTC
#### Describe the bug

Upload a ong or jpg at blockreassurance with activate the item leads in an exception and the article detail site cannot be displayed

#### Expected behavior

Display the png image

#### Steps to Reproduce

1. Go to blockreassurance 
2. Click on +
3. upload png
4. activate
5. load article detail page

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 

```
PHP Fatal error:  Uncaught Error: Call to undefined method ImageManager::getMimeType() in /bitnami/prestashop/modules/blockreassurance/classes/ReassuranceActivity.php:190\nStack trace:\n#0 /bitnami/prestashop/modules/blockreassurance/blockreassurance.php(517): ReassuranceActivity::getAllBlockByStatus(1, 1)\n#1 /bitnami/prestashop/modules/blockreassurance/blockreassurance.php(409): blockreassurance->renderTemplateInHook('displayBlockPro...')\n#2 /bitnami/prestashop/classes/Hook.php(970): blockreassurance->hookdisplayReassurance(Array)\n#3 /bitnami/prestashop/classes/Hook.php(355): HookCore::coreCallHook(Object(blockreassurance), 'hookdisplayReas...', Array)\n#4 /bitnami/prestashop/classes/Hook.php(907): HookCore::callHookOn(Object(blockreassurance), 'displayReassura...', Array)\n#5 /bitnami/prestashop/config/smarty.config.inc.php(167): HookCore::exec('displayReassura...', Array, NULL)\n#6 /bitnami/prestashop/classes/Smarty/SmartyLazyRegister.php(83): smartyHook(Array, Object(Smarty_Internal_Template))\n#7 /bitnami/prestashop/var/cache/p in /bitnami/prestashop/modules/blockreassurance/classes/ReassuranceActivity.php on line 190, referer: https://******/11-koerper-seifen
```

**Comment by florine2623** [comment] 2020-07-23 11:03
Hi @ASchmidt84 ,
Thanks for your report, I did manage to reproduce your issue with Customer Reassurance module version 5.0.0.
![Capture d’écran 2020-07-23 à 12 59 07](https://user-images.githubusercontent.com/16019289/88279557-92756b80-cce4-11ea-9c2f-de42aff911e2.png)
In my case I added a png file, same issue goes for jpg uploads.
![Capture d’écran 2020-07-23 à 13 01 36](https://user-images.githubusercontent.com/16019289/88279636-b2a52a80-cce4-11ea-9f89-b9c09e871260.png)
I will ping our dev team to let them know about this issue.
Please stay tuned.
Thanks!

**Comment by zodit** [comment] 2020-08-01 13:29
This problem is the same of this: https://github.com/PrestaShop/PrestaShop/issues/20254
Solution is like described here: https://github.com/PrestaShop/blockreassurance/pull/35#issuecomment-566556584

Change file: classes/ReassuranceActivity.php on line 190.
Search "getMimeType" and Replace "getMimeTypeByExtension".

**Comment by marionf** [comment] 2020-08-11 16:12
Duplicate of #20254

**Closed as completed by marionf** 2020-08-11 16:12 UTC
Labels: Bug, Minor, FO, Duplicate, Blockreassurance, 1.7.6.7
