### ISSUE TITLE
Wrong behaviour of Block Category

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#12785] opened 2019-03-04 11:35 UTC
With my version 1.7.5.1 if I set CMS to have two collumns (Category Block Enabled) it shows the last category I visited. In my opinion, if you're NOT searching a category it should display the root category and not the last visited.

To Reproduce
Enable Category Block to show at CMS pages.
Visit a Category
Visit a CMS page
Check the category displayed at the Category Block

Additionnal information
PrestaShop version: 1.7.5.1
PHP version: PHP 7.0.33-0ubuntu0.16.04.1

**Comment by khouloudbelguith** [comment] 2019-03-04 12:16
Hi @seederp2p,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4
In the BO => Design => Theme & Logo => Click on "Choose layouts" => Edit CMS to `Two Columns, small left column - Two columns with a small left column`
In the FO => 
I navigate to a page first => OK.
![image](https://user-images.githubusercontent.com/16067358/53732859-74089900-3e7f-11e9-9bf3-e21b777c90cb.png)

If I navigate to a category then to a page => NOK =>  the last visited category is displayed
![image](https://user-images.githubusercontent.com/16067358/53732875-8256b500-3e7f-11e9-870d-2c66daf40a3b.png)

https://drive.google.com/file/d/1L1BkO2ruizMcVR0uOl41cbadfsPUXkOd/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-04 12:20
Hi @seederp2p,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10763
So, I close it.
Thanks !

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2019-03-04 12:20
Duplicate of #10763

**Closed as completed by khouloudbelguith** 2019-03-04 12:20 UTC
Labels: Bug, Minor, FO, Duplicate, Theme & logo, Category tree, 1.7.5.1
