### ISSUE TITLE
Lithuanian translations from Crowdin are not updated to localization pack.

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [PrestaShop/PrestaShop#18927] opened 2020-05-01 07:00 UTC
Lithuanian translations from Crowdin are not updated to localization LT-lt pack.  
Can't see updated translations in Front as in BO.

PrestaShop version: since 1.7 first versions.

**Comment by LouiseBonnard** [comment] 2020-05-05 15:30
Hi @Laimonas-Mituzas, thanks for the feedback. Can you give me more information about this issue: which PrestaShop version are you using? do you have screenshots to display as examples? does it regard Crowdin only or it happens when translating in the International > Translations section of the back office?

**Comment by Laimonas-Mituzas** [comment] 2020-05-13 19:35
For testing puposes installed 1.7.6.1 on local. Added Lithuanian language in Localisation. Switched profile to Lithuanian language. And in BO menu we have not translated "Module manager", see in picture https://prnt.sc/sg86hw
In Crowdin for 1.7.6 folder we have https://prnt.sc/sg8a81
as traslation wa made a year ago
link https://crowdin.com/translate/prestashop-official/35096/en-lt#q=module+manager

The same story with "Link Widget". In BO we have
https://prnt.sc/sg8nmu
On Crowdin
https://prnt.sc/sg8mib
https://crowdin.com/translate/prestashop-official/35578/en-lt

**Comment by LouiseBonnard** [comment] 2020-05-14 12:37
Hi @Laimonas-Mituzas, thank you very much for the detailed explanation! I know what you're talking about! Indeed, translations for the _Module Manager_ string were not retrieved so far. It has been fixed and will be released in PrestaShop 1.7.7, cf. https://github.com/PrestaShop/PrestaShop/pull/17986. Also, there are known issues to the menu translation that this [PR](https://github.com/PrestaShop/PrestaShop/pull/18082) should fix for the 1.7.8.

I close this issue since it is taken into account in PR #17986 and #18082, feel free to reopen it if need be or comment directly in #18082. Thank you. :-)

**Closed as completed by LouiseBonnard** 2020-05-14 12:37 UTC
Labels: Bug, 1.7.x, Duplicate, International, Translations, Fixed

**Comment by khouloudbelguith** [comment] 2020-10-08 09:58
Duplicate of #9762
