### ISSUE TITLE
tcpdf deleting images - tcpdf must be updated

### ISSUE THREAD

**Issue by metacreo** [PrestaShop/PrestaShop#25801] opened 2021-09-07 10:53 UTC
#### Describe the bug

tcpdf do unlink for template images
https://github.com/tecnickcom/TCPDF/issues/158

#### Expected behavior

pdf template images may not be deleted.

#### Steps to Reproduce

Attach image to content.tpl.
```
...
</style>
<img src="{$module_img}pdf/101.png" />
<table style="width: 100%;" cellpadding="5">
...
```
generate pdf
````
            $template = _PS_MODULE_DIR_ . 'mymodule/views/templates/pdf/content.tpl';
            $pdfGen = new PDFGenerator(false, 'P');
            $pdfGen->setFontForLang(Context::getContext()->language->iso_code);
            $pdfGen->startPageGroup();
            $pdfGen->createHeader($this->context->smarty->fetch(_PS_MODULE_DIR_ . 'mymodule/views/templates/pdf/header.tpl'));
            $pdfGen->createFooter($this->context->smarty->fetch(_PS_MODULE_DIR_ . 'mymodule/views/templates/pdf/footer.tpl'));
            $content = $this->context->smarty->fetch($template);
            $pdfGen->AddPage();
            $pdfGen->writeHTML($content, true, false, true, false, '');
            $pdfGen->lastPage();
            $pdfGen->output(_PS_MODULE_DIR_ . 'mymodule/pdf/mymodule.pdf', false);
````

PrestaShop version: 1.7.7.7
PHP version: 7.3

**Comment by florine2623** [comment] 2021-09-07 12:01
Hello @metacreo ,

Please share the steps to reproduce the issue.

Thanks!

**Comment by metacreo** [comment] 2021-09-07 13:08
> 
> 
> Hello @metacreo ,
> 
> Please share the steps to reproduce the issue.
> 
> Thanks!

This is not prestashop bug. This bug of outdated tcpdf libs. Bug described in code. If you put image in pdf content (from any PS place (module, root, etc...)), after pdf generation image will be deleted by tcpdf class code, deleted physically from any prestashop dir.  

Example 2:
I create module who generate some pdf files. My module images in /modules/mymodule/views/img/*. If I attach this images in pdf template content (not header, not footer), then after pdf creation, tcpdf remove used images from /modules/mymodule/views/img/.

**Comment by metacreo** [comment] 2021-09-07 13:15
Example 2:
I create module who generate some pdf files. My module images in /modules/mymodule/views/img/*. If I attach this images in pdf template content (not header, not footer), then after pdf creation, tcpdf remove used images from /modules/mymodule/views/img/.

**Comment by florine2623** [comment] 2021-09-07 13:50
Just to make sure I understand well, the issue comes from TCPDF and not PrestaShop ?

**Comment by metacreo** [comment] 2021-09-07 13:59
Yes. But TCPDF libs must be updated in PrestaShop. Otherwise, it make unavailable to use TCPDF in PrestaShop modules.

**Comment by florine2623** [comment] 2021-09-07 14:44
Regarding the PrestaShop module, are you talking about native module ? If yes, could you list them please ?
Thank you!

**Comment by hibatallahAouadni** [comment] 2021-09-27 15:44
Hello @metacreo 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-27 15:44 UTC
Labels: Bug, CO, Image, No change required

**Comment by kpodemski** [comment] 2021-09-28 08:24
Hello @metacreo 

I couldn't reproduce this issue with PrestaShop 1.7.8. PrestaShop uses 6.2 of TCPDF in this version, and after updating to the latest version (6.4.2), everything is working as expected.

It seems that this error has been fixed in some v6.3, but PrestaShop was not using this version.

I've tested it on PHP 8.

**Comment by metacreo** [comment] 2021-09-29 08:24
Latest PS is 1.7.7.8 (1.7.8 still beta). 1.7.7.8 use 6.3.2 /vendor/tecnickcom/tcpdf/tcpdf.php
To reproduce this issue you need create module who generate some pdf. You need assign image file to pdf CONTENT section.
Here my module full function (based on code example from https://devdocs.prestashop.com/1.7/modules/concepts/pdf/)

    public function generatePdfFile($type)
    {
        // /modules/mymodule/views/templates/pdf/01-content.tpl
        $template = _PS_MODULE_DIR_ . 'mymodule/views/templates/pdf/' . $type['part_code'] . '-content.tpl';
        if (file_exists($template)) {
            $this->context->smarty->assign([
                'pdf_id_lang' => $this->idLang,
                'pdf_year' => date('Y'),
                'pdf_date' => date('Y-m-d'),
                'pdf_part_type' => $type,
                'pdf_part_properties' => MyModuleClass::getPartTypeProperties($this->idLang, $type['id_part_type']),
                'pdf_parts' => MyModuleClassOther::getPartsByType(true, $type['id_part_type'], Configuration::get('MYMODULE_DEFAULT_PARTS_BRAND'), $this->idLang, true)
            ]);
            $pdfGen = new PDFGenerator(false, 'P');
            $pdfGen->setFontForLang(Context::getContext()->language->iso_code);
            $pdfGen->startPageGroup();
            $pdfGen->createHeader($this->context->smarty->fetch(_PS_MODULE_DIR_ . 'mymodule/views/templates/pdf/header.tpl'));
            $pdfGen->createFooter($this->context->smarty->fetch(_PS_MODULE_DIR_ . 'mymodule/views/templates/pdf/footer.tpl'));
            $pdfGen->createContent($this->context->smarty->fetch($template));
            $pdfGen->SetAutoPageBreak(TRUE, 15);
            $pdfGen->SetHeaderMargin(5);
            $pdfGen->SetFooterMargin(10);
            $pdfGen->setMargins(10, 40, 10);
            $pdfGen->AddPage();
            $pdfGen->writeHTML($pdfGen->content, true, false, true, false, '');
            $filename = strtolower($type['part_code'] . '-' . str_replace(' ', '-', $type['name'])) . '.pdf';
            $pdfGen->render(_PS_MODULE_DIR_ . 'mymodule/pdf/' . $filename, 'F');
        }
    }

Here CONTENT template realization:

```
{*** /modules/mymodule/views/templates/pdf/01-content.tpl ***}
{*** /modules/mymodule/views/img/pdf/01-1.png ***}
```

```
<table style="width: 100%; border: none;" cellpadding="5">
    <tr style="border: none;">
        <td style="border: none;">
            <img src="{$module_img}pdf/{$pdf_part_type.part_code}-1.png" />
        </td>
    </tr>
</table>
```

ISSUE: After pdf generation, image **01-1.png** will be deleted by tcpdf.php library.
/vendor/tecnickcom/tcpdf/tcpdf.php line 8119 function _destroy (unlink($file)).

**Comment by kpodemski** [comment] 2021-09-29 08:28
@metacreo 

1.7.8 uses 6.2:
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/composer.json#L117

I've tried to reproduce this issue by creating a module as you said, but I didn't manage to reproduce it. Maybe you've updated your TCPDF by mistake?

**Comment by metacreo** [comment] 2021-09-29 08:34
No. I checked on 2 last PS instalation. 1.7.7.7 and 1.7.7.8 both have 6.3.2 tcpdf. Prestashop downloaded from PS site not from git.

**Comment by kpodemski** [comment] 2021-09-29 08:36
@metacreo thanks, let me check that again

**Comment by metacreo** [comment] 2021-09-29 08:42
PS updated via 1-Click, maybe 1-click update vendors?

**Comment by kpodemski** [comment] 2021-09-29 08:43
@metacreo no, no, I didn't notice `^` in composer.json, I still cannot reproduce this error on PHP 8, I'll check on 7.3

**Comment by kpodemski** [comment] 2021-09-29 08:47
[demopdfbug.zip](https://github.com/PrestaShop/PrestaShop/files/7250337/demopdfbug.zip)

Could you check this example module? I've tested it on PHP 8 and PHP 7.3, my `example1.jpg` is not deleted during the generation

**Comment by metacreo** [comment] 2021-09-29 10:10
Thanks tested. Your module not shown the bug. I found that this issue only on multi-paged pdf I upgraded module, check now
[demopdfbug.zip](https://github.com/PrestaShop/PrestaShop/files/7250945/demopdfbug.zip)
.

**Comment by kpodemski** [comment] 2021-09-29 10:40
@metacreo 

Thank you for the updated version. Unfortunately, I still cannot reproduce this issue.

I'm going to the module configuration, to re-generate the PDF, all images from the `/views/img/pdf` are still there, even after the regeneration.

Is there anything else that might be an issue here? Maybe you use a different font than the default one?

And thank you very much for your help with this Issue! ❤️

**Comment by metacreo** [comment] 2021-09-29 11:17
Now I tried 3 different ps installations with last demopdfbug.zip All 3 servers running with PHP 7.3.29, PS 1.7.7.8, tcpdf libs 6.3.2
After click Configure images from /views/img/pdf removed. I can try upgrade PHP to 8 but afraid that 1.7.7.8 presta works incorrectly.

one test is on fresh install... no other modules, no hacks, no changes

**Comment by kpodemski** [comment] 2021-09-29 11:20
@metacreo I've checked this issue on PHP 7.3.11.

@PrestaShop/prestashop-maintainers can someone help with this, please? All you need to do is to download the module provided by metacreo, install it, click the configuration button, and see if there are still images in `views/img/pdf` 💪

**Comment by tswfi** [comment] 2021-11-26 09:58
We are seeing this also on one live shop

presta: 1.7.7.8
php: 7.3.20

we are trying to replicate this on our dev environment next.

I think this should be reopened.

**Comment by kpodemski** [comment] 2021-11-26 10:04
Let me know @tswfi because I wasn't able to reproduce this issue, maybe it's related to something specific.

**Comment by tswfi** [comment] 2021-11-26 10:26
https://github.com/tecnickcom/TCPDF/pull/174 sounds like the culprit

**Comment by tswfi** [comment] 2021-11-26 10:40
yup, on the live server tcpdf is on version 6.3.2 and this commit fixes the situation

https://github.com/tecnickcom/TCPDF/commit/510070b5e068e10d97b8cb0e25295e54755ec09d

now to replicate this on a test environment.

**Comment by tswfi** [comment] 2021-11-26 12:18
actually how does this work? composer.json says that above 6.2.12
https://github.com/PrestaShop/PrestaShop/blob/630ebcc8c3e9369b24d4326e7e091a2294cfcf58/composer.json#L130
but at what point of the release build process are those updated? shouldn't we get the latest tcpdf for each new version?

**Comment by tswfi** [comment] 2021-11-26 13:00
ok, after digging a bit this is what I found:

```
ps 1.7.7.8 comes with tcpdf 6.3.2
ps 1.7.8.0 comes with tcpdf 6.3.5
ps 1.7.8.1 comes with tcpdf 6.3.5
```

tcpdf versio 6.3.4 fixes this problem. So the solution is to upgrade to atleast ps 1.7.8.0 

I didn't dig backwards on when this was introduced tho...

note that `docker-compose up` seems to install even newer version (6.4.1 as of writing this) as the lock file has been updated.

https://github.com/tswfi/PrestaShop/blame/develop/composer.lock#L9781

@kpodemski might make sense to up the minimal requirement in composer.json to at least 6.3.4 which is the first one that has the fix according to here: https://github.com/tecnickcom/TCPDF/commit/510070b5e068e10d97b8cb0e25295e54755ec09d

**Comment by kpodemski** [comment] 2021-11-30 20:33
@atomiix I think you forgot to update tcpdf in the `composer.json`? 🤔
