### ISSUE TITLE
Issue when installing in Arabic

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10250] opened 2018-09-03 10:06 UTC
⚠️ (EDIT) No PR related to this as the issue was with translations and not with the code. Can you check that it is solved ? :)

**Describe the bug**
Can't complete the installation of Prestashop in Arabic  because in step 3 the Next & previous buttons are pointing to legal@prestashop.com

**Screenshots**
![capture d ecran_225](https://user-images.githubusercontent.com/13449658/44981005-a9d0d180-af71-11e8-9739-e750f64482dc.png)

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by ntiepresta** [comment] 2018-09-03 12:26
Hi, marionf 
I manage to reproduce the issue 

Best regards, Reddy Ntie

**Comment by marionf** [comment] 2018-09-03 13:16
@ntiepresta 
You need to test all the installation process for these PRs where a language is added
this issue could be found before QA approved :)

**Comment by ntiepresta** [comment] 2018-09-03 13:25
@marionf ,
Thank you 
Best regards, Reddy Ntie

**Comment by matks** [comment] 2018-09-07 14:35
Bug analysis:
**Right DOM**
![capture d ecran 2018-09-07 a 16 35 15](https://user-images.githubusercontent.com/3830050/45225107-0870b500-b2bc-11e8-82cc-6b7503d98ee3.png)
**Faulty DOM**
![capture d ecran 2018-09-07 a 16 35 08](https://user-images.githubusercontent.com/3830050/45225129-13c3e080-b2bc-11e8-9bd8-f94eb936b1d5.png)

**Comment by matks** [comment] 2018-09-10 08:44
@eternoendless Thanks to Quetzacoalt91 we were able to find the issue root cause: a bad translation. We're going to fix it on crowdin however do you know if we can check the result ? Is crowdin automatically updated or is there some kind of release process ?

**Comment by eternoendless** [comment] 2018-09-12 12:44
Translation packages are updated every night automatically in a two tier process. 

First they are pulled from Crowdin and placed in this repo: https://github.com/PrestaShop/TranslationFiles/

Every time something is pushed to that repo, a Jenkins task builds the zip packages which are then made available for live shops.

**Comment by matks** [comment] 2018-09-12 15:44
@eternoendless OK I can see the fix there: https://github.com/PrestaShop/TranslationFiles/commit/d5a1d81a4662b8937c6562f4766b91185a6070c1
I'll try in 24 hours so that I am sure that the Jenkins task is done

**Comment by matks** [comment] 2018-09-14 08:01
@eternoendless ⚠️  Language pack ar-SA has been updated for 1.7.4
http://i18n.prestashop.com/translations/1.7.4/ar-SA/ar-SA.zip

But language pack ar-SA 1.7.5 is not updated
http://i18n.prestashop.com/translations/1.7.5/ar-SA/ar-SA.zip

**Comment by Quetzacoalt91** [comment] 2018-09-19 10:45
Regarding your update @matks, I completed an installation of PrestaShop after switching the version back to 1.7.4.2.

![capture du 2018-09-19 11-45-19](https://user-images.githubusercontent.com/6768917/45748774-8e1c2b00-bc01-11e8-85bb-c300c18a02de.png)

**Comment by eternoendless** [comment] 2018-09-19 16:59
@matks:
> language pack ar-SA 1.7.5 is not updated

This is normal as only TranslationFiles for 1.7.4 are being pulled from crowdin and pushed in TranslationFiles. Once the catalog of 1.7.5 has been uploaded to crowdin and the polling system is updated, then it will start updating 1.7.5 files instead.

Until then, we can workaround the problem by copying files from [here](https://github.com/PrestaShop/TranslationFiles/tree/master/1.7/translations/1.7.4) and pushing them [here](https://github.com/PrestaShop/TranslationFiles/tree/master/1.7/translations/1.7.5).

**Comment by matks** [comment] 2018-09-26 13:01
Looks like 1.7.5 catalog has been updated to crowdin and this solves this issue :)

**Comment by marionf** [comment] 2018-09-26 13:08
Yes, it's solved :+1:

**Comment by eternoendless** [comment] 2018-09-27 08:46
FYI the 1.7.5 catalog hasn't been uploaded to Crowdin yet, I simply updated TranslationFiles manually.

**Comment by Robin-Fischer-PS** [comment] 2020-01-20 13:45
I reopened the issue since this bug appears again on 176 and on develop.

**Comment by matks** [comment] 2020-01-20 14:03
Confirmed, same issue as before

**Comment by matks** [comment] 2020-01-20 14:50
I checked the Arabic language translation packs
http://i18n.prestashop.com/translations/1.7.6.0/ar-SA/ar-SA.zip
http://i18n.prestashop.com/translations/1.7.6.2/ar-SA/ar-SA.zip
http://i18n.prestashop.com/translations/1.7.6.3/ar-SA/ar-SA.zip
http://i18n.prestashop.com/translations/1.7.7.0/ar-SA/ar-SA.zip

In file Install.ar-SA.xlf
```
<trans-unit id="6794fece26df4610c0523bffd7a45231" approved="yes">
        <source><![CDATA[All information you give us is collected by us and is subject to data processing and statistics, it is necessary for the members of the PrestaShop company in order to respond to your requests. Your personal data may be communicated to service providers and partners as part of partner relationships. Under the current "Act on Data Processing, Data Files and Individual Liberties" you have the right to access, rectify and oppose to the processing of your personal data through this <a href="%s" onclick="return !window.open(this.href)">link</a>.]]></source>
        <target state="final"><![CDATA[سوف نقوم بجمع كافة المعلومات المقدمة لنا من قبلكم واستخدامها لاغراض تحليل البيانات أو لأهداف إحصائية، وهي ضرورية لتمكين أعضاء بيريستاشوب من الإستجابة لطلباتكم واستفساراتكم. كما وقد يتم مشاركة بيناتكم مع مزودي الخدمة و الشركاء كجزء أساسي من علاقتنا مع الشركاء. تحت "قانون معالجة البيانات، وملفات البيانات والحريات الفردية" الحالي، لديك الحق في الوصول و تصحيح ومعارضة معالجة البيانات الشخصية الخاصة بك من خلال هذا الرابط <a href="%s" onclick="return !window.open(this.href)">.]]></target>
        <note>Line: 178</note>
      </trans-unit>
```

The `</a>` missing in arabic translation is the issue. It seems these files are not up-to-date with https://github.com/PrestaShop/TranslationFiles/commit/d5a1d81a4662b8937c6562f4766b91185a6070c1

**Comment by matks** [comment] 2020-01-20 15:07
OK, this is because the fix was only on 1.7.4 crowdin database, and not on 1.7.5 nor 1.7.6 databases

@LouiseBonnard can you confirm that
- the translation is OK on crowdin for 1.7.4
- the translation has still the issue "missing </a>" on 1.7.5 and 1.7.6 (and then fix it) ?

**Comment by LouiseBonnard** [comment] 2020-01-20 17:36
I have copied the right translation from the 1.7.4 branch and pasted it in the other catalogs, but I would gladly like to have a native speaker's feedback before. I'll ask the Arabic translators community to review it tomorrow. :-)

cf. [Crowdin](https://crowdin.com/translate/prestashop-official/all/en-ar#q=All+information+you+give+us+)

**Comment by LouiseBonnard** [comment] 2020-01-24 13:07
UPDATE: no answer from the Arabic translating community for now, but if there is an issue for the Arabic, I suggest you check the install wizard in Persian and Hebrew as well. Both languages are right-to-left. ;-)

UPDATE: Persian and Hebrew are just fine, we investigated it last Friday, the string is okay in the code but appears weirdly on Crowdin, cf. their [documentation](https://support.crowdin.com/online-editor/#translating-rtl-languages).

**Comment by sam-pires** [comment] 2020-01-27 15:25
After @LouiseBonnard updated the translation on Crowdin it should be fixed. To be sure it needs to be tested :
- [ ] 1.7.4.4
- [x] 1.7.5.2 ❌
- [ ] 1.7.6.0
- [x] 1.7.6.2 ❌
- [ ] 1.7.6.3
- [x] 1.7.7 ❌

@PrestaShop/prestashop-qa can someone help me test on the 1.7.7 ?

**Comment by Robin-Fischer-PS** [comment] 2020-01-27 15:44
@sam-pires Fail in 1.7.7.x (the bug is on the left side of the screenshot) : 
![Capture d’écran de 2020-01-27 16-42-26](https://user-images.githubusercontent.com/55688534/73189160-3f9b6c80-4124-11ea-9387-f285768aece9.png)

**Comment by sam-pires** [comment] 2020-01-27 15:47
Damn!
It's not the same problem right?

**Comment by sam-pires** [comment] 2020-01-27 16:47
Ok actually it doesn't work on the 1.7.6.2 either nor on the 1.7.5.2

The mystery is still alive ✨

**Comment by sam-pires** [comment] 2020-01-27 16:49
We need an investigation 🚨👮‍♀️

**Comment by matks** [comment] 2020-01-27 17:09
> After @LouiseBonnard updated the translation on Crowdin it should be fixed.

Sorry, not, it's not automatic 😄there is a manual process needed to be done to export crowdin data and update i18n.prestashop.com data

Hence the issue

**Comment by LouiseBonnard** [comment] 2020-01-28 08:55
@matks, how frequently this data is updated? Could we consider doing it on a weekly basis at least or automatizing it?

**Comment by Progi1984** [comment] 2020-01-30 16:57
My check :
- :ok_hand: In Crowdin, 
  - :ok_hand: In catalog 1.7.6, the string is well translated ([Reference](https://crowdin.com/translate/prestashop-official/35152/en-ar#q=All+information+you+give+us+is+collected))
  - :boom: No catalog 1.7.7
- In TranslationsFiles,
  - :ok_hand:  the string is well translated in 1.7.6 / latest ([Reference](https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.6/ar-SA/Install.ar-SA.xlf#L479))
  - :boom: the string is not well translated in 1.7.7 ([Reference](https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/ar-SA/Install.ar-SA.xlf#L479))
- In i18n
  - :ok_hand:  the string is well translated in 1.7.6.3 package ([Reference](http://i18n.prestashop.com/translations/1.7.6.3/ar-SA/ar-SA.zip))
  - :boom: the string is not well translated in 1.7.7.0 package ([Reference](http://i18n.prestashop.com/translations/1.7.7.0/ar-SA/ar-SA.zip))

**Comment by Progi1984** [comment] 2020-01-31 13:13
After discussion with @LouiseBonnard, we need to check this issue after the feature freeze when the catalog for 1.7.7 will be available (and so the translation files, and so the i1n package).

**Comment by colinegin** [comment] 2020-02-24 13:15
@Progi1984 the catalog is now available, you can check this issue

**Comment by eternoendless** [comment] 2020-02-26 15:16
Translations packages have been updated for 1.7.7 (copied over from 1.7.6). This should fix the problem if it's fixed by the translation itself.

**Comment by Robin-Fischer-PS** [comment] 2020-03-11 18:43
Problem is fixed on 1.7.7x branch !

**Comment by sam-pires** [comment] 2020-03-11 19:25
[yes](https://media2.giphy.com/media/ei4y3i1imwhTjq43V0/giphy.gif?cid=19f5b51adf097b0ceb118e2c99d09e49a6f331275348896d&rid=giphy.gif)

**Comment by sam-pires** [comment] 2020-03-11 19:26
![image](https://user-images.githubusercontent.com/25405887/76455876-7ed10480-63d6-11ea-8acf-5770e3ee64c9.jpg)

Yeeeesss!!!

**Closed as completed** 2020-03-12 08:22 UTC
Labels: Bug, develop, 1.7.5.x, Minor, IN, Fixed, Wording ✔️, 1.7.6.0, 1.7.6.2
