### ISSUE TITLE
The help pop-up no longer displays anything. 1.7.8 and lower

### ISSUE THREAD

**Issue by spinoops** [PrestaShop/PrestaShop#33878] opened 2023-09-08 06:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The help pop-up no longer displays anything. 1.7.8 and lower. It seems that the url https://help.prestashop.com/fr/doc/AdminProducts?version=1.7.8.10 is not working.

The version 8 doesn't have this issue because an other url is used : prestashop-project.org

### Steps to reproduce

1. Go admin panel
2. Go to Catalog > Products (all sections have this problem)
3. Click on the Help button in the top right
4. Nothing in the pop-up
5. https://help.prestashop.com/fr/doc/AdminProducts?version=1.7.8.10 not working

### PrestaShop version(s) where the bug happened

1.7.8.10 and lower

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2023-09-10 16:30
Hello @spinoops 

Thanks for reporting the issue 🙏 
Your issue is duplicate to this one #23996 and it has been fixed by this PR #25004
It's recommended to upgrade your shop, otherwise you may use the fix in the mentioned PR.
Closing the issue!

Thanks for your understanding 🙏

**Comment by hibatallahAouadni** [comment] 2023-09-10 16:30
Duplicate of #23996

**Closed as completed by hibatallahAouadni** 2023-09-10 16:30 UTC
Labels: Bug, Duplicate, Invalid

**Comment by spinoops** [comment] 2023-09-14 05:58
Thanks for your anwser. It seems that the problem is not the same as you mentionned. 

The files are already up to date in 1.7.8.10. It must be something else.

I saw someone with the same problem : #33902 and #33917

**Comment by MatShir** [comment] 2023-09-14 08:52
Thanks @spinoops you are right ! There is bug. I'm investigating. I will keep you updated

**Comment by MatShir** [comment] 2023-09-14 15:22
https://help.prestashop.com/en/doc/AdminCustomers?version=1.7.8.10&country=en is working again ! 🥳
Could you try again see if it works on your side ?

**Comment by spinoops** [comment] 2023-09-14 15:23
Yes, it's working :D Thanks a lot !
