### ISSUE TITLE
Manual changes for shipping cost in BO

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19753] opened 2020-06-15 13:19 UTC
#### Is your feature request related to a problem?
Sometimes we want to create an order in BO and we can't use any shipping price which is defined in BO, we've to use an individual shipping price. But it is not possible to edit the shipping price in BO.

#### Describe the solution you'd like
The shipping price should be possible to edit and change.

#### Additional context
BO > Orders > Orders > detail info > section Shipping > Shipping cost
![image](https://user-images.githubusercontent.com/33311857/84661897-4b44cf80-af1b-11ea-8c10-fbd08b2b671a.png)

**Comment by matthieu-rolland** [comment] 2020-06-15 15:52
@PrestaShop/prestashop-product-team , this is a feature request, I didn't find a duplicate, do you think there is something to be done about this ?

(this feature doesn't exist in 1.7.7 or previous versions)

**Comment by colinegin** [comment] 2020-06-16 16:00
ping @MatShir 
@matthieu-rolland don't forget to add labels on the issue.

**Comment by MatShir** [comment] 2020-06-22 09:04
Thank you for your feedback. This feature has already been requested.
This issue is a duplicate of #17225.

**Comment by marionf** [comment] 2020-06-23 09:33
@MatShir We can close it if it's a duplicate ?

**Closed as completed** 2020-06-23 13:55 UTC
Labels: Improvement, Duplicate, Order, 1.7.7.0
