### ISSUE TITLE
Stock Management in Multi-store shows copy of products

### ISSUE THREAD

**Issue by viktormalka** [PrestaShop/PrestaShop#27251] opened 2022-01-06 16:43 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

We are facing some issues in the stock management section inside the BO, at the moment we have a multi-store, and everytime we create or duplicate a product in the second store, we see in the stock management the product with the prefix "copy of ..." or an empty name which is pointing to the version of the product in the first store.

![image](https://user-images.githubusercontent.com/36510496/148416728-8c40afe6-c58d-4018-81a3-d25caec51d15.png)

It's important to say the product was created in the context of the second store, also the stores are not sharing clients, categories, or orders, and both stores are separated in diffrent shop groups.

![image](https://user-images.githubusercontent.com/36510496/148417312-3f2be5ee-8cde-4aa9-92ab-6cd585793f09.png)

![image](https://user-images.githubusercontent.com/36510496/148417415-ed8415ca-abdc-42f8-ae40-655757e2c72d.png)

Maybe some can help us to understand what are doing wrong or maybe why is happening this issue.

### Expected behavior

Stock management just show the products of the shop context, not all of them.

### Steps to reproduce

1. Create a store
2. Enable the mutl-store capability
3. Create a second store
4. Create a product in the second store and saved.
5. Duplicate your product previously created, and change the name
5. Go to the stock management and search the second product by name.
6. You will see the "copy of" in the stock results.

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment] 2022-01-07 10:29
Hello @viktormalka 

I did not manage to reproduce your issue with PS1777 & PS1778

**Comment by HanaRebaiQA** [comment] 2022-01-07 10:38
Hello @viktormalka 

I did not manage to reproduce your issue with PS1777, PS1778 
https://watch.screencastify.com/v/MsD62Mama4TYlBLa19Vu

Please check and feedback?

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-26 09:58
Hello @viktormalka 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-26 09:58 UTC
Labels: Bug, BO, Stocks, Multistore, Invalid
