### ISSUE TITLE
Multistores stock page product name not visible

### ISSUE THREAD

**Issue by Jose-comonsoft** [PrestaShop/PrestaShop#29684] opened 2022-09-19 09:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In multishop context when you create a product in the second shop only, the product name don't appear in the stock management page. 

I think the bug is from the sql request in StockRepository.php L228 

![productNameStockPS](https://user-images.githubusercontent.com/81296286/190991943-5403303a-a3c2-4778-bfb0-739425d2b342.JPG)

### Expected behavior

the product name

### Steps to reproduce

step 1: In general settings, activate multishop.
step 2: Create a second shop with share stock option.
step 3: Select the second shop in shop menu.
step 4: Go to catalog->product and create a product for the second shop only.
step 5: Go to catalog->stock.

 The product name is not visible.

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment] 2022-09-20 08:54
Hello @Jose-comonsoft 

Thanks for reporting the issue
I reproduce the issue with PrestaShop versions **PS1.7.7.0**, **PS1.7.8.7**, **Ps8.0.0**, you can see the issue here :

https://user-images.githubusercontent.com/31663369/191206781-abeee363-1c20-4912-93db-5efb3fcf5802.mp4

Thank you !

**Comment by 0x346e3730** [comment] 2022-10-06 09:01
@Jose-comonsoft Wanted to thank you for the analysis you did, made it easier to track and fix !

**Comment by Jose-comonsoft** [comment] 2022-10-07 14:45
Hello @sallemiines,

your welcome!
Thx for the video.

best regards

**Comment by Jose-comonsoft** [comment] 2022-10-07 14:49
> @Jose-comonsoft Wanted to thank you for the analysis you did, made it easier to track and fix !

Thank you too for the fix! 
I tested it on prestashoop  version 1.7.8.4 and it works.

best regards.

**Comment by 0x346e3730** [comment] 2022-10-07 14:50
The fix is not merged so I don't think the issue is fixed yet 🤔

**Closed as completed** 2022-10-13 09:22 UTC
Labels: Bug, Minor, BO, Stocks, Multistore, PR available, 1.7.7.0, Verified
