### ISSUE TITLE
Cannot add order via the prestashop 1.7.7.x back office

### ISSUE THREAD

**Issue by Esh-network** [PrestaShop/PrestaShop#25736] opened 2021-08-30 10:03 UTC
Hello,

I allow myself to post a message following a bug encountered on version 1.7.7.x.

#### Describe the bug
When I want to create an order via the back office I end up with different problems (error 500).
Which does not allow me to create an order.

#### Steps to Reproduce
here is the procedure:
1. Go to the back office command tab.
2. Click on create an order
3. Search for a user (preferably with a current basket or with orders already placed).
4. Choose this user (open the F12 console) Continue the procedure click on the different tabs for example (command)
5. Check your console for a 500 error.

**Screenshots**
1. https://cdn.esh-dev.fr/upload/chrome_FxTu1Ht1lE.png 
2. https://cdn.esh-dev.fr/upload/chrome_IR6sTHqHGK.png 

**Screen records**
https://cdn.esh-dev.fr/upload/errorx.mp4
https://cdn.esh-dev.fr/upload/errorcom.mp4 

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1 -> 7.3

**Comment by hibatallahAouadni** [comment] 2021-08-30 12:46
Hello @Esh-network 

I didn't manage to reproduce your issue with PS177x, see the attached screen record below:

https://drive.google.com/file/d/16VL49O5RsLKRZ3NmcWLoZUmIHVN7Y1IZ/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-20 08:02
Hello @Esh-network 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-20 08:02 UTC
Labels: Bug, BO, Order, No change required
