### ISSUE TITLE
ps_facetedsearch | Sorting in BO does not work for main categories in FO

### ISSUE THREAD

**Issue by kkasztann** [PrestaShop/PrestaShop#15328] opened 2019-08-30 10:30 UTC
**Describe the bug**
Setting products order in BO do not work for major categories, but work correctly for subcategories. For the main categories, the order of products set in BO is displayed in the wrong order on FO, but when I disable module: "ps_facetedsearch" everything displaying correctly.

**To Reproduce**
1. Go to 'BO ->Catalog -> Products -> '
2. Click on 'Filter by category'
3. 'Select category with subcategories inside' *
4. Click on 'Sort'
5. 'Set order and save'
6. Go to 'FO -> Shop -> Category (selected in step 3) '
7. See error: "the products display in a different order than you set in BO"

 \* For subcategories everything working correctly

**Screenshots**
1. Main Category + ps_facetedsearch enabled
![ss1](https://user-images.githubusercontent.com/33009149/64003284-3e7df900-cb0c-11e9-9e7f-9ab5a76f0359.png)
![ss2](https://user-images.githubusercontent.com/33009149/64009871-fb765280-cb18-11e9-9dfd-d5fe3f930d82.png)

1.1 Main Category + ps_facetedsearch disabled  [displayed correctly]
![ss6](https://user-images.githubusercontent.com/33009149/64013544-53648780-cb20-11e9-887a-073a1b5149f5.png)

2. Any Subcategory + ps_facetedsearch enabled [displayed correctly]
![ss3](https://user-images.githubusercontent.com/33009149/64013577-64ad9400-cb20-11e9-8c9e-03139df1c856.png)
![ss4](https://user-images.githubusercontent.com/33009149/64013578-66775780-cb20-11e9-8bc4-4f1c0a6459c0.png)
![ss5](https://user-images.githubusercontent.com/33009149/64013581-68411b00-cb20-11e9-88d0-e22a51010ffc.png)

**Additional information**
Issue occurs on my 2 sites: 
PrestaShop version: 1.7.5.1  | 1.7.6.1
PHP version: 7.2.21 | 7.1.31
ps_facetedsearch version: 3.1.0 | 3.2.0

**Comment by khouloudbelguith** [comment] 2019-08-30 10:34
Hi @kkasztann,

The problem is fixed if we use the icon in position column. The product is selected and we can change the position and saved and all changes is validated.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14879 to fix the issue.
It is fixed in the PS1.7.7.0.
Since this PR correct the problem it's OK a New issue was created for the second issue : #15291
Your ticket is a duplicate of #14616
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-08-30 10:35
Duplicate of #14616

**Closed as completed by khouloudbelguith** 2019-08-30 10:34 UTC
Labels: Duplicate
