### ISSUE TITLE
Redirected to login page

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#20308] opened 2020-07-24 07:20 UTC
After entering login and password, I was redirected to login page again and everything repeated.

Hello again, 

Thank you for your patience.

I've checked the information about the issue and I found these errors in the access_log of the domain iptv366.com
[Thu Jul 23 10:22:45.866256 2020] [fcgid:warn] [pid 18904:tid 139730930861824] [client 172.68.11.11:34390] mod_fcgid: stderr: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- , referer: https://iptv366.com/fr/connexion?back=my-account
Most likely this is connected to the original issue. For example, this error is discussed here:
https://www.prestashop.com/forums/topic/960128-php-fatal-error-uncaught-smarty-0missing-template-parameter/
https://stackoverflow.com/questions/58686542/smartyexception-0missing-template-parameter-with-prestashop

Then I checked other Plesk and system logs, and I did not find anything related to this issue with the PrestaShop. 
Therefore, I can say that in this case, the issue arises from the outside of the Plesk. Most likely it is connected to the PrestaShop itself.

I've found an article about login issues, you may refer to it:
https://bobcares.com/blog/prestashop-admin-login-problem/

Also, I've checked the PrestaShop forum for similar cases, here are the links to them, please check it:

https://www.prestashop.com/forums/topic/910115-solved-16117-cant-login-to-admin-pannel/
(Disabling the "customers expertise" module and/or renaming gamification folder helped here)

https://www.prestashop.com/forums/topic/566159-17-cant-login-backend/
(Changing the permissions and Line 'locale' at the app/config/parameters.php)

https://www.prestashop.com/forums/topic/921994-i-cant-login-in-prestashop-back-office/
(PHP issue)

Also, this issue is discussed here:
https://stackoverflow.com/questions/11335073/prestashop-cant-login-in-admin

Please note, that you may enable the error reporting for debug information:
https://www.prestashop.com/forums/topic/224525-how-to-turn-on-error-reporting-for-debug-information-blank-page-500-internal-server-error/
I would suggest using this debug option to check if there will be an error on login. 

After that, you may check the error online or check it on the PrestaShop forum:
https://www.prestashop.com/forums/

If this doesn't help, please contact them directly via this link:
https://www.prestashop.com/en/support

Please let me know if you have any Plesk related questions.
Best regards,

Vladislav Kolosovskii
Technical Support Engineer
Plesk

**Comment by matks** [comment] 2020-07-24 07:35
@go-sudo Thanks ! That is very valuable information

**Comment by SimonGrn** [comment] 2020-07-24 09:47
Hello,

> After entering login and password, I was redirected to login page again and everything repeated.

In the back-office, right ? Like I answered you before in #20234 , your problem is linked to your own configuration and not a problem in PrestaShop itself. We cannot help you here, you need to ask in the [forums](https://www.prestashop.com/forums/) or the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack), or get a [support plan](https://www.prestashop.com/en/support).

The next lines are from a mail you got from your Plesk administrator, you should specify that. In general, you are strongly advised to use our template (you deleted everything...).
You will find below my answers.

> I've checked the information about the issue and I found these errors in the access_log of the domain iptv366.com
> [Thu Jul 23 10:22:45.866256 2020] [fcgid:warn] [pid 18904:tid 139730930861824] [client 172.68.11.11:34390] mod_fcgid: stderr: PHP Fatal error: Uncaught --> Smarty: 0():Missing '$template' parameter <-- , referer: https://iptv366.com/fr/connexion?back=my-account

This is a front-office error, not a back-office error. This is not related to your problem

> Most likely this is connected to the original issue. For example, this error is discussed here:
> https://www.prestashop.com/forums/topic/960128-php-fatal-error-uncaught-smarty-0missing-template-parameter/
> https://stackoverflow.com/questions/58686542/smartyexception-0missing-template-parameter-with-prestashop

Same here, this is related to the front-office error, not a back-office error.

> Then I checked other Plesk and system logs, and I did not find anything related to this issue with the PrestaShop.
> Therefore, I can say that in this case, the issue arises from the outside of the Plesk. Most likely it is connected to the PrestaShop itself.
> 
> I've found an article about login issues, you may refer to it:
> https://bobcares.com/blog/prestashop-admin-login-problem/

Errors detailed on this article are configuration problems, not PrestaShop problems. They lie in the way the environment is configured, not in PrestaShop itself.

> Also, I've checked the PrestaShop forum for similar cases, here are the links to them, please check it:
> 
> https://www.prestashop.com/forums/topic/910115-solved-16117-cant-login-to-admin-pannel/
> (Disabling the "customers expertise" module and/or renaming gamification folder helped here)

This is a 1.6.1.17 problem, from 2 years ago. This problem arose when PrestaShop (the company) had an outage and that blocked all back-office connections. This is not related to your current problem.

> https://www.prestashop.com/forums/topic/566159-17-cant-login-backend/
> (Changing the permissions and Line 'locale' at the app/config/parameters.php)

It's again a configuration problem.

> https://www.prestashop.com/forums/topic/921994-i-cant-login-in-prestashop-back-office/
> (PHP issue)

A configuration problem, from the server itself, not PrestaShop.

> Also, this issue is discussed here:
> https://stackoverflow.com/questions/11335073/prestashop-cant-login-in-admin

It's a report from 8 years ago, not related to your problem (it didn't use the proper URL to navigate to the back-office).

> Please note, that you may enable the error reporting for debug information:
> https://www.prestashop.com/forums/topic/224525-how-to-turn-on-error-reporting-for-debug-information-blank-page-500-internal-server-error/
> I would suggest using this debug option to check if there will be an error on login.

This is a good suggestion from your Plesk representative, you should try to use the debug option.

We can only tackle problems relative to PrestaShop itself, like a bug in the Core or the native modules. We cannot troubleshoot problems lying in your own configuration or environment.
There is no actual evidence that the problem you encountered is relative to PrestaShop, as we were not able to reproduce it and you seem to be the only one with this exact problem.

Seeing as you [report](https://github.com/PrestaShop/PrestaShop/issues/20234) trouble with the cache, I suggest you try to investigate your cache configuration at the server level (maybe a misconfiguration, maybe you don't have enough free space, maybe your cache is not invalidated properly or you have a permissions problem on the cache folder).

If you need more information, I strongly suggest you to use the [forums](https://www.prestashop.com/forums/), or get a dedicated [support plan](https://www.prestashop.com/en/support) where our team will be able to assist you for your specific problem.

Also, please use the template when submitting a bug report, as it *really* helps us helping you.

Thank you for your comprehension.

**Comment by go-sudo** [comment] 2020-07-25 12:14
Hi @SimonGrn 

I noticed now that when i'm rejected and I delete the all the link in the bar address except the admin folder then put enter I can access but when I click on order menu I'm disconnected again 


i let you know that I stopped all kind of cache Nginx and Memcached even mode_deflate and all kind of apache modification then I enabled the Debug mode.
 
![image](https://user-images.githubusercontent.com/11594433/88457004-e44ffa00-ce7a-11ea-9a46-9d3786bed14d.png)
![image](https://user-images.githubusercontent.com/11594433/88457007-e914ae00-ce7a-11ea-86ea-10be24adfcd2.png)


I tried on firefox chrome and edge

```
(1/1) ContextErrorExceptionUser Notice: Undefined property: SmartyDev::$smarty
--
in Smarty.class.php line 1354
at Smarty->__get('smarty')in abandonedcart.php line 526
at Abandonedcart->hookDisplayHeader(array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 13))in Hook.php line 970
at HookCore::coreCallHook(object(Abandonedcart), 'hookdisplayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 13))in ets_hook line 505
at Ets_Hook::callHookOn(object(Abandonedcart), 'displayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 13))in ets_hook line 356
at Ets_Hook::exec17('displayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 13), null, false, true, false, null, false, array(array('file' => '/var/www/vhosts/iptv366.com/httpdocs/classes/controller/FrontController.php', 'line' => 556, 'function' => 'exec', 'class' => 'Hook', 'type' => '::')))in Hook.php line 36
at Hook::exec('displayHeader')in FrontController.php line 556
at FrontControllerCore->initContent()in FrontController.php line 37
at FrontController->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in IndexController.php line 18
at IndexController->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in Dispatcher.php line 36
at Dispatcher->dispatch()
```

You think I should create a new account.
Cache https://youtu.be/E8aE99_zVVU

I removed the modules Abandonedcart & ets all this module now debug mode show me this 


```
(1/1) ContextErrorExceptionNotice: Undefined index: id
--
in awscloudfronts3.php line 550
at AWSCloudFrontS3->getStylesheets(array('external' => array('theme-ccc' => array('id' => 'theme-ccc', 'type' => 'external', 'path' => '/var/www/vhosts/iptv366.com/httpdocs/themes/ZOneTheme/assets/cache/theme-49d473931.css', 'uri' => 'https://iptv366.com/themes/ZOneTheme/assets/cache/theme-49d473931.css', 'media' => 'all', 'priority' => 50)), 'inline' => array()))in awscloudfronts3.php line 580
at AWSCloudFrontS3->prepareMedia()in awscloudfronts3.php line 406
at AWSCloudFrontS3->hookDisplayHeader(array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 16))in Hook.php line 970
at HookCore::coreCallHook(object(AWSCloudFrontS3), 'hookdisplayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 16))in Hook.php line 355
at HookCore::callHookOn(object(AWSCloudFrontS3), 'displayHeader', array('cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 16))in Hook.php line 907
at HookCore::exec('displayHeader')in FrontController.php line 556
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in IndexController.php line 18
at IndexController->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

```

Regards

**Comment by SimonGrn** [comment] 2020-07-25 13:40
Do you use the Classic theme ?
Do you see some modified files (in the PrestaShop backoffice, there is a section in Advanced Parameters > Information) ?
You should try creating a new account and giving it administrator rights, but something is definitely messed up on your shop.

**Comment by go-sudo** [comment] 2020-07-25 22:39
Hi @SimonGrn 
I don't think that theme is the issue because i have 3 or 4 PS shops on the same server with different themes, why when I remove the token I'm enable to access but rejected from order menu.
 
I even created a new super admin account but still the same
![image](https://user-images.githubusercontent.com/11594433/88467454-476b7c00-cecf-11ea-82f6-0d9d7a27826f.png)

you'll find videos for my tests on EDGE, Chrome and Firefox and I will try to make a test by 3am this morning and let you know 
[redirect.zip](https://github.com/PrestaShop/PrestaShop/files/4976802/redirect.zip)

Regards

**Comment by khouloudbelguith** [comment] 2020-07-27 12:35
Hi @go-sudo,

Did you use a custom module for example `pagespeed` module?
Your issue seems to be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/14371#issuecomment-509956780

THanks!

**Comment by go-sudo** [comment] 2020-07-27 19:01
Hi @khouloudbelguith 
Pageseed is off and I delete it.
--Idem
rm -fR var/cache/*,
--Idem
Clear your browser cache and your cookies
--Idem
Disable the IP check cookies
---Idem
/classes/controller/AdminController.php, replace 900 to 3600 
Idem
![image](https://user-images.githubusercontent.com/11594433/88580882-385a0a80-d044-11ea-9fe0-b21bb4ff0ac9.png)
![image](https://user-images.githubusercontent.com/11594433/88580892-3c862800-d044-11ea-968b-55646da6331c.png)
[cache.zip](https://github.com/PrestaShop/PrestaShop/files/4983972/cache.zip)

https://drive.google.com/file/d/1dq4nvpRBIusr31lHn37dBAWGn42TOlxK/view

Question ; why on login page i remove the token link and put enter I can access but order section reject me
I'm ready to provide privately Bo acces  
Regards,

**Comment by go-sudo** [comment] 2020-07-28 04:43
Hi @khouloudbelguith 
I noticed that when this file login.js is loaded from disk cache I can't access here is a video 

[2020-07-28_05-41-14.zip](https://github.com/PrestaShop/PrestaShop/files/4986034/2020-07-28_05-41-14.zip)

Regards

**Comment by SimonGrn** [comment] 2020-07-28 08:01
Thank you @go-sudo for all these details.
Sadly, as we were suspecting, this is definitely an issue on your side.
Once again, I strongly suggest you contact our support team to help you with this specific case. You can also try to get help in our forums or our Slack channel.
There is nothing more we can do on Github.

I'll close this issue.

I hope you understand.

**Closed as completed by SimonGrn** 2020-07-28 08:01 UTC
Labels: Bug, BO, Can't reproduce

**Comment by go-sudo** [comment] 2020-07-28 13:13
@SimonGrn  i do not understand why you suggest that I pay to get help if you can't resolve the issue so you support team wil not do i think i will move to CS cart or Magento soon

**Comment by SimonGrn** [comment] 2020-07-28 13:40
We do not provide free support on Github, this is not the place to get help. Please get in touch with our support or the forums/Slack channel.
Thank you for your understanding.

**Comment by eternoendless** [comment] 2020-07-28 13:41
It's not a question of if we can or can't. Specialists's time cost money. if you're looking for free help on your own terms you're going to have a hard time finding it, regardless of the CMS you use.
