### ISSUE TITLE
Transplant a module > "Search input" exception is not working in Wishlist module and displayCustomerAccount hook

### ISSUE THREAD

**Issue by SimonasB88** [PrestaShop/PrestaShop#26895] opened 2021-12-06 15:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Tried to make a Search input exception for My Account page in FO, managing the Wishlist module and displayCustomerAccount hook, but came up with slightly no changes in FO.

https://user-images.githubusercontent.com/29095235/144875219-b1014ce8-cec1-4fee-a775-680fb3738f72.mp4

### Expected behavior

Search input UI is excepted and hidden in Wishlist UI.

### Steps to reproduce

1. Go to IMPROVE > Positions 
2. Search for displayCustomerAccount hook
3. Click the Editing hook icon on Wishlist module
4. In Exceptions, search for "Search" file to exclude in hook UI
5. Go to FO > My Account > Wishlist 

### PrestaShop version(s) where the bug happened

1.7.8.0 Multistore

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

wishlist v2.0.1

**Comment by hibatallahAouadni** [comment] 2021-12-06 17:06
Hello @SimonasB88 

Do you mean that the search bar shouldn't be displayed in Wishlist page:

![image](https://user-images.githubusercontent.com/23308427/144889986-4246b9f8-dfcb-46eb-a5f3-70874ed5a4a4.png)

Is that so? Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-27 08:14
Hello @SimonasB88 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-27 08:14 UTC
Labels: Bug, FO, Duplicate, Positions, Blockwishlist, Search bar, Hook, Invalid

**Comment by SimonasB88** [comment] 2022-01-05 08:35
Hey, sorry, was a bit vacationing @hibatallahAouadni 

Yes, the search field shouldn't be displayed, as it is set to be exception. Did you get a possibility to reproduce this?

Thanks.

**Comment by hibatallahAouadni** [comment] 2022-01-06 09:28
Duplicate of #27056
