### ISSUE TITLE
Product combinations are not shown and cannot be removed

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#12000] opened 2019-01-02 14:06 UTC
In PS 1.7.4 (.3 and .4), new product combinations dont show op in backoffice when making product.
Only default demo combinatiosn can be selected.
Combinations do show up under attributes list.

Problem is because of changing and deleting default language by prestashop (changing english to another default and remove english) which causes the soutce code not to comply anymore with numbers of language in the BO.
But when this is done, after making combinations at product, they cannot be removed and need to make new product with new combinations.

**Comment by khouloudbelguith** [comment] 2019-01-02 14:29
Hi @loetje88,

Have you the same issue with this ticket: #9627?
Thanks to check & feedback.

**Comment by loetje88** [comment] 2019-01-02 15:50
Hi Khouloud,

No not exactly - i dont have any attributes at all which i make myself.
Only the default ones by prestashop demo content.

**Comment by khouloudbelguith** [comment] 2019-01-02 16:09
@loetje88, so the block of the list of attributes is not displayed created by you?
![image](https://user-images.githubusercontent.com/16067358/50600336-17095a80-0eb1-11e9-85f8-f04d4f3d0680.png)
Thanks!

**Comment by loetje88** [comment] 2019-01-02 16:13
hi khouloud,

No, none of the attributes i make myself.
These above block are demo content, to that are the only ones available.
But if i make (for example) 

Decor
- Flowers
- Vase
-Book

This, an other custom made, are not shown at the product making.
They only show in attributes list under "Attributes"- not in the combination section of the product.

**Comment by khouloudbelguith** [comment] 2019-01-02 16:18
@loetje88, have you tried to apply this patch https://github.com/PrestaShop/PrestaShop/pull/10924/files ?
Thanks!

**Comment by dineshbadrukhiya** [comment] 2019-01-03 02:46
@loetje88 Have you tried this patch that I have fixed : [https://github.com/PrestaShop/PrestaShop/pull/10924](url)

**Comment by dineshbadrukhiya** [comment] 2019-01-03 02:47
@loetje88 Have you tried this patch that I have fixed : #10924

**Comment by khouloudbelguith** [comment] 2019-01-31 10:42
Duplicate of #9627

**Closed as completed by khouloudbelguith** 2019-01-31 10:42 UTC
Labels: Bug, BO, Duplicate, Combinations
