### ISSUE TITLE
MySQL SSL connect

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#26956] opened 2021-12-12 19:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

yes

### Describe the solution you'd like

make it possible to connect prestashop to a MySql database that requries SSL connection, like digital ocen manged sql servers.

**Comment by florine2623** [comment] 2021-12-13 08:34
Hello @thbl ,

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/10784.
Please refer directly to it for more information. Especially to this comment : https://github.com/PrestaShop/PrestaShop/issues/10784#issuecomment-425874313

I'll close your issue as it is a duplicate.
Thank you

**Comment by florine2623** [comment] 2021-12-13 08:34
Duplicate of #10784

**Closed as completed by florine2623** 2021-12-13 08:34 UTC
Labels: Feature, Duplicate

**Comment by thbl** [comment] 2021-12-13 08:42
@florine2623 well that ticked seams closed and out of date ?

**Comment by thbl** [comment] 2021-12-18 15:22
@florine2623 any info on how to connect with ssl ?
