### ISSUE TITLE
Can't open Module manager

### ISSUE THREAD

**Issue by ITProfeska** [PrestaShop/PrestaShop#28373] opened 2022-04-28 21:19 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi, 

I have a problem with Module manager tab, when I try to open it I've got an error: 

Oops... looks like an unexpected error occurred. 
Compile Error: require_once(): Failed opening required '/srv/users/server/apps/…/public/modules/statscheckup/statscheckup.php' (include_path='/srv/users/server/apps/domain/public/vendor/pear/pear_exception:/srv/users/server/apps/domain/public/vendor/pear/console_getopt:/srv/users/server/apps/domain/public/vendor/pear/pear-core-minimal/src:/srv/users/server/apps/domain/public/vendor/pear/archive_tar:.:/opt/sp/php7.4/lib/php')
[Symfony\Component\Debug\Exception\FatalErrorException 0]

I'm able to open it only in dabug mode without any issues.

### Expected behavior

..// index.php/configure/advanced/performance/ Module manger not accesible

### Steps to reproduce

1. Go to admin panel 
2. click on modules and expand options
3. click on Module Manager

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2022-04-29 11:06
Hello @ITProfeska 

Thanks for your report.

I was unable to reproduce your issue with 1785 and php 7.4.

https://user-images.githubusercontent.com/92912932/165923516-22f86236-1301-457d-9bcd-4b30d55e5b9f.mp4

It seems that your issue is related to `statscheckup`, could you reset it ?

Please check again and feedback 

Thanks!

**Comment by ITProfeska** [comment] 2022-04-29 14:16
Hi, 

I reset statscheckup but this action doesn't help, so I disabled this module but this do not change situation at all same error showing up when I clicked on module manager.

Regards

**Comment by mparvazi** [comment] 2022-05-01 16:54
Hello @ITProfeska 
Please try to delete folders inside `PS/var/cache` and test again.

**Comment by ITProfeska** [comment] 2022-05-01 19:05
yeah that's was it, 

many thanks :-)

**Comment by AureRita** [comment] 2022-05-02 15:45
Thank you @mparvazi for your support, 

I'll close this issue, 

Thanks

**Closed as completed by AureRita** 2022-05-02 15:45 UTC
Labels: Bug, BO, Fixed, Module manager
