### ISSUE TITLE
Incorrect product assignment to a category after importing from CSV file

### ISSUE THREAD

**Issue by mgielecinski** [PrestaShop/PrestaShop#25927] opened 2021-09-20 07:53 UTC
#### Describe the bug

Hello
I have problem with CSV import.
The category tree is created correctly, but the second product is assigned to the first instance of the category with that name

#### Expected behavior

The second product should be correctly assigned to the subcategory called Tools under the Second category

#### Steps to Reproduce

1. Go to import section in BO
2. Upload and import CSV from the attachment
3. Check the assignment of the product named test2 to the category

**Screenshots**

![zgloszenie](https://user-images.githubusercontent.com/70368592/133968948-19d35c82-38b1-4fd6-8311-1c879f673863.png)
![zgloszenie2](https://user-images.githubusercontent.com/70368592/133970251-125007e1-af58-4e53-8344-86db198c3b69.png)

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

[test.csv](https://github.com/PrestaShop/PrestaShop/files/7194247/test.csv)

**Comment by hibatallahAouadni** [comment] 2021-09-20 10:07
Hello @mgielecinski 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12092. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-20 10:07
Duplicate of #12092

**Closed as completed by hibatallahAouadni** 2021-09-20 10:07 UTC
Labels: Duplicate
