### ISSUE TITLE
Change URL when changing store in multistore

### ISSUE THREAD

**Issue by Ludofloria** [PrestaShop/PrestaShop#10982] opened 2018-10-12 08:14 UTC
**Describe the bug**
With the Multistore feature enabled, we often change the shop context (to jump from the B2B store to the B2C store, or the other way around). 
The two stores have differents URL. But when we go from B2B to B2C store, we are still on the B2B URL while on the B2C store. Thus, half of the URL redirect us on the B2C URLs, but not all. So, when we are in this configuration (B2B context, B2C URL), the ajax queries fail (because of the CORS, or because the AJAX request get redirected to the login on the B2B URL).

For example : On the B2B context, B2B URL, everything works fine. When we change to the B2C context, almost all URL in the backoffice get changed to the B2C URL, except the "Product" URL, "Modules" URL, "Shop settings", "Advanced settings".
Also, after changing the context, you'll be on the same URL as the previous context.

**To Reproduce**
1. Go to the Order pages
2. Change the shop context
3. Click on the "+" button to add an order
4. Try to search for a customer

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: PHP 7.0

**Comment by khouloudbelguith** [comment] 2018-10-12 08:58
Hi @Ludofloria,

Here's the PR: #9450 to solve the issue.
It is fixed in the new release: 1.7.5.0.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-12 08:59
Duplicate of #9450

**Closed as completed by khouloudbelguith** 2018-10-12 08:58 UTC
Labels: Duplicate

**Comment by Ludofloria** [comment] 2018-10-12 09:04
Ow, i didn't find it while using the search bar. My terms weren't the good one apparently.
Thank's for pointing this out !
