### ISSUE TITLE
cost price not saved

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#16027] opened 2019-10-18 16:08 UTC
Prestashop 1.7.6.1 with php 7.2.23 on ubuntu-apache
Cost price not saved, please see my video: https://nimb.ws/XcafU3

**Comment by khouloudbelguith** [comment] 2019-10-21 08:28
Hi @centoasa,

I did not manage to reproduce the issue with PS1.7.6.1 & PHP 7.2.23.
I attached a screen record.
https://drive.google.com/file/d/1fWTOyFswDv7TOJkfma7DaszwI-jRCInk/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by CatchMeZZo** [comment] 2019-11-19 02:28
Same issue here!

PrestaShop-Version 1.7.6.1 - SingleShop
MySQL-Version 5.7.26-nmm1-log
Apache Server Linux #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64
PHP-Version 7.1.30-nmm1

**Comment by khouloudbelguith** [comment] 2019-11-19 08:06
Hi @CatchMeZZo,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by CatchMeZZo** [comment] 2019-11-19 13:15
Now i know the issue. 

This only applies to products that have entered a supplier as a standard!

When you deactivate under supplier the main supplier (radio) and save the product - now you can save the wholesale price.

Thats a PrestaShop Bug!

**Comment by khouloudbelguith** [comment] 2019-11-19 13:36
Hi @CatchMeZZo,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1Kq0Q6XSFsxpHxHgqLd_dtv0bLGAmQjT-/view
Thanks!

**Comment by CatchMeZZo** [comment] 2019-11-20 11:52
I got it! A new function has been installed with the ps update secretly in the stock management. If you activate a supplier you must enter a wholesale price at the bottom. If not, the wholesale price under the tab "price" changes automatically to 0. Even if a value has already been entered there.

I am now desperately looking for a solution to deactivate the function or transfer the price that already entered under the tab "price" to the supplier price under the tab "option". Because if you have to change a product for example the product name - my purchase price under the tab "price" will automatically be set to 0.

Should both not go, I am forced to go through all the products. That's absolutely not acceptable 
and for me a prestashop bug!

**Comment by khouloudbelguith** [comment] 2019-11-20 11:58
@CatchMeZZo,

I  just reproduced this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16353
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-20 11:58
Duplicate of #16353

**Closed as completed by khouloudbelguith** 2019-11-20 11:58 UTC
Labels: Bug, BO, Duplicate, Taxes and Prices, 1.7.6.1
