### ISSUE TITLE
upgrade from 1.7.6.8  to 1.7.7.7 giving js error in admin

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#25873] opened 2021-09-14 10:27 UTC
#### Describe the bug

After upgrade Prestashop **1.7.6.8**  to **1.7.7.7** using **1-Click Upgrade v4.12.0** admin console showing  js error.
When searching for the module, the search is not working

http://i.imgur.com/UJBLNuj.png

**Comment by florine2623** [comment] 2021-09-14 12:39
Hello @pks891618 ,

Upgrade from 1.7.6.8 to latest version available went well :
<img width="1195" alt="Screenshot 2021-09-14 at 14 24 06" src="https://user-images.githubusercontent.com/16019289/133258782-a0f5798c-e40b-4454-8405-d63f637b778d.png">
<img width="770" alt="Screenshot 2021-09-14 at 14 31 57" src="https://user-images.githubusercontent.com/16019289/133258800-b098ceb0-64e3-4cc1-8dc9-ada40e955bfb.png">

I can't reproduce your issue :
https://drive.google.com/file/d/13qrlKoA7ZNz-5hrA9vdHQxYz3BRf6gYw/view

Please upgrade your version of PHP if below 7.1 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I'm closing your issue as I can't reproduce it.
Thanks!

**Closed as completed by florine2623** 2021-09-14 12:39 UTC
Labels: Can't reproduce

**Comment by pks891618** [comment] 2021-09-15 05:53
yes i found that there is third party module that was causing this issue, any way thanks for prompt reply
