### ISSUE TITLE
ISBN blocks product saving

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33828] opened 2023-09-04 12:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you create a new product in the backoffice and save it without modifying the ISBN field the saving will be blocked because "0" is an invalid value for the isbn field. As only a small minority of the products uses an ISBN number that is inconvenient. 

![isbn](https://github.com/PrestaShop/PrestaShop/assets/13930107/d9b55c51-3505-4c97-b94c-0996109f5610)

### Expected behavior

By default this field should have an empty value that is accepted when you submit.

### Steps to reproduce

Create a new product
Do not touch the isbn field
submit

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment] 2023-09-04 16:33
Hello @musicpanda 

It seems your issue is similar to this one #33371 could you please check it.
Waiting for your feedback.

Thanks!

**Comment by musicpanda** [comment] 2023-09-04 17:04
No. 33371 is a bug. This is a usability issue that happens when entering products

I noticed that it happens with me on a 8.1.1 installation that is an upgrade. However, an 8.0 fresh shop doesn't show the problem and offers the fields empty instead of with zero's.

![saver](https://github.com/PrestaShop/PrestaShop/assets/13930107/55c848e6-3bf8-4b79-9c18-99f3c77f0947)

**Comment by kpodemski** [comment] 2023-09-05 06:29
There's something wrong with your installation. We don't set these fields to `0`. I didn't reproduce this, and I tested on both, the 8.1 version and the develop branch.

**Comment by MatShir** [comment] 2023-09-05 12:44
Is it a fresh install or an upgrade ? I couldn't reproduced either :/

**Comment by paulnoelcholot** [comment] 2023-09-27 15:42
Hello @musicpanda,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2023-09-27 15:42 UTC
Labels: Bug, BO, Invalid, 8.1.x, Products Page

**Comment by paulnoelcholot** [comment] 2023-09-27 15:45
Hello @musicpanda,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
