### ISSUE TITLE
Login to BO in 1.7.7.2 does not work after upgrade from 

### ISSUE THREAD

**Issue by akaeu** [PrestaShop/PrestaShop#23729] opened 2021-03-22 18:41 UTC
#### Describe the bug
When going to BO after inserting the credential, no login possible. 
The link in any broser redirect to https://websitedomanin.com/adminpanel/index.php?controller=AdminLogin&token=609642c69c1650b5c72662a73e2fc41d

In the error log no message appear. After setting debug to TRUE also no message available.

#### Steps to Reproduce

Go to https://websitedomanin.com/adminpanel/index.php
Insert username and password
Click LOGIN 
Here is nothing

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
My Server INFO 
Prestashop Version : 1.7.7.2
ICU version: 63.1
PHP Version: 7.2.34
1. When upgrading with 1ClickUpgrade module no errors or warnings
In page of 1ClickUpgrade before I started upgrade on VERSION COMPARISON It was 63 files modifications detected.
2. It's not an INTL_IDNA_VARIANT_UTS46 issue because I made corrections 
3. I have the ps_employees_session and ps_customes_session . Both empty
4. In any broser I try to login I'm redirected to the same url: https://myshopwebsite.ext/adminfolder/index.php?controller=AdminLogin&token=609642c69c1650b5c72662a73e2fc41d - I've noticed it;s always the same token.
5. In Chrome developer tools I see the followind 

![error_all](https://user-images.githubusercontent.com/33682189/112041346-f8a1df00-8b4e-11eb-8b93-f0d27a5bb0de.jpg)

**Comment by hibatallahAouadni** [comment] 2021-03-23 05:48
Hello @akaeu 

Could you please provide your previous PrestaShop version (before upgrade) and what was the **1-click upgrade** module version that you used.
Please check and feedback.

Thanks!

**Comment by akaeu** [comment] 2021-03-23 18:03
Sorry my mistake. I forgot to say the original version . 1.7.2.4 .

1ClickUpgrade version  : 4.12.0

**Comment by akaeu** [comment] 2021-03-23 18:16
And these was my modified files before I click UPGRADE 

•	classes/Attachment.php
•	classes/Context.php
•	classes/Product.php
•	controllers/admin/AdminProductsController.php
•	js/jquery/ui/themes/base/minified/jquery-ui.min.css
•	modules/ps_banner/config.xml
•	modules/ps_banner/img/sale70.png
•	modules/ps_banner/ps_banner.php
•	modules/ps_categorytree/ps_categorytree.php
•	modules/ps_facetedsearch/src/Ps_FacetedsearchFiltersConverter.php
•	modules/ps_facetedsearch/config.xml
•	modules/ps_facetedsearch/ps_facetedsearch.php
•	modules/ps_wirepayment/config.xml
•	modules/ps_wirepayment/controllers/index.php
•	modules/ps_wirepayment/controllers/front/index.php
•	modules/ps_wirepayment/controllers/front/payment.php
•	modules/ps_wirepayment/controllers/front/validation.php
•	modules/ps_wirepayment/views/templates/index.php
•	modules/ps_wirepayment/views/templates/hook/index.php
•	modules/ps_wirepayment/views/templates/hook/_partials/payment_infos.tpl
•	modules/ps_wirepayment/views/templates/hook/infos.tpl
•	modules/ps_wirepayment/views/templates/hook/payment.tpl
•	modules/ps_wirepayment/views/templates/hook/payment_return.tpl
•	modules/ps_wirepayment/views/templates/hook/ps_wirepayment_intro.tpl
•	modules/ps_wirepayment/views/index.php
•	modules/ps_wirepayment/index.php
•	modules/ps_wirepayment/logo.png
•	modules/ps_wirepayment/payment.php
•	modules/ps_wirepayment/ps_wirepayment.php
•	modules/ps_wirepayment/validation.php
•	override/classes/controller/index.php
•	override/classes/index.php
•	override/controllers/admin/templates/index.php
•	override/controllers/admin/index.php
•	override/controllers/index.php
•	override/controllers/front/index.php
•	override/modules/index.php
•	override/index.php
•	src/PrestaShopBundle/Controller/Admin/ProductImageController.php
•	src/PrestaShopBundle/Resources/views/Admin/Product/form.html.twig
•	src/PrestaShopBundle/Resources/views/Admin/ProductImage/form.html.twig
•	robots.txt


MAIL FILE(S) (10)
•	mails/en/in_transit.html
•	mails/en/in_transit.txt
•	mails/en/order_customer_comment.html
•	mails/en/order_customer_comment.txt
•	modules/ps_emailsubscription/mails/en/newsletter_conf.html
•	modules/ps_emailsubscription/mails/en/newsletter_conf.txt
•	modules/ps_emailsubscription/mails/en/newsletter_verif.html
•	modules/ps_emailsubscription/mails/en/newsletter_verif.txt
•	modules/ps_emailsubscription/mails/en/newsletter_voucher.html
•	modules/ps_emailsubscription/mails/en/newsletter_voucher.txt


TRANSLATION FILE(S) (1)
•	modules/ps_wirepayment/translations/index.php

**Comment by hibatallahAouadni** [comment] 2021-03-24 18:20
Ping @florine2623 could you please try to reproduce the issue :pray: 
Thanks in advance.

**Comment by florine2623** [comment] 2021-03-25 10:35
Hello @akaeu ,

After upgrading my test shop from PS 1.7.2.4 to PS 1.7.7.2 with one-click upgrade v4.12.0 :
![Capture d’écran 2021-03-25 à 11 33 25](https://user-images.githubusercontent.com/16019289/112459280-f3ff4580-8d5d-11eb-9b23-cd2e25a8bad8.png)

I logged in with no issue :
https://drive.google.com/file/d/1kXBGYNX2p_bUM9qIFlxTqyNQ5XZPpVoZ/view

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.
Thanks!

**Closed as completed by florine2623** 2021-03-25 10:35 UTC
Labels: Bug, BO, Can't reproduce, Employees, Autoupgrade, 1.7.7.2
