### ISSUE TITLE
BO - Shopping Carts : Incorrect result for Conversion Rate

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#30445] opened 2022-11-29 15:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

bad **Conversion Rate** statistics result  :
It does not respect the percentage of customers present in the list

[Untitled_ Nov 29 2022 4_00 PM.webm](https://user-images.githubusercontent.com/111756615/204565726-ee7d404a-b35f-487e-9ba9-7386d99dfb27.webm)

### Expected behavior

If all visitors become customers > should be 100%
If half of the visitors become customers > should be 50%
..and the percentage changes according to the number of customers

### Steps to reproduce

1. Go to BO >  Orders > Shopping carts > See Conversion Rate
2. :warning: see error : the **Conversion Rate** statistics result does not respect the percentage of customers present in the list

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment] 2022-11-29 16:23
Hello @MhiriFaten 

Following your steps,unfortunately  I can't manage to reproduce your issue with PS 1787 and PS 1788 

![image](https://user-images.githubusercontent.com/31663369/204584902-9e397fe1-2b9f-48f9-8519-786a8166be4e.png)

Did I miss some config to set ? 

Please check and feedback !

**Comment by HanaRebaiQA** [comment] 2022-12-16 08:55
Hello @MhiriFaten 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank You!

**Closed as completed by HanaRebaiQA** 2022-12-16 08:55 UTC
Labels: Bug, BO, Shopping carts, 1.7.8.x, Invalid
