### ISSUE TITLE
Error when upgrading from 1.7.2.4 to 1.7.4.2

### ISSUE THREAD

**Issue by LSClaire** [PrestaShop/PrestaShop#10833] opened 2018-10-03 12:51 UTC
**Describe the bug**
Site live and healthy on 1.7.2.4. We upgraded it using 1 click upgrade module, "successfully" upgraded to 1.7.4.2. Many errors appeared in front office. We decided to go for a manual upgrade. We get an error when running http://<shop_domain>/install/upgrade/upgrade.php (see screenshot). When refreshing, we get an error code 28, which means upgrade is already complete. That's the only error we get during the process. Once done, we get the same errors in front office than with the 1 click upgrade module. Mainly, we have encoding issues and js errors. We notice that in source code "var prestashop" is empty. The second screenshot shows the errors we have in front office.

**To Reproduce**
All explained in the bug's description.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/43815115/46411189-6b1e6a80-c71b-11e8-9488-ed4bfb915b90.png)
![screen shot 2018-10-03 at 5 51 17 pm](https://user-images.githubusercontent.com/43815115/46411218-76719600-c71b-11e8-9dcb-519eb6564d35.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2018-10-03 13:14
Hi @LSClaire,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Thanks!

**Comment by LSClaire** [comment] 2018-10-04 06:11
[20181001_upgrade.log](https://github.com/PrestaShop/PrestaShop/files/2445077/20181001_upgrade.log)

**Comment by khouloudbelguith** [comment] 2018-10-04 10:27
@LSClaire, in your log file => you have this error [You already have the 1.7.4.2 version] as you said.
It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.4.
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.4.2 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by LSClaire** [comment] 2018-10-05 09:04
We check thoroughly and we have no column missing in the database. Do you have other ideas of where the issue can come from?

**Comment by khouloudbelguith** [comment] 2018-10-08 16:19
ping @Quetzacoalt91 what do you think of this issue?

**Comment by LSClaire** [comment] 2018-10-09 14:39
We still haven't been able to upgrade the site. Does someone have an idea? We are keen to try things but we have no idea what to try anymore!

**Comment by LSClaire** [comment] 2018-10-09 14:41
This is the list of modified files given by 1 click upgrade module. From what I understand it's a comparaison between our site and 1.7.2.4 original.
[COMPARAISON DES VERSIONS.docx](https://github.com/PrestaShop/PrestaShop/files/2460869/COMPARAISON.DES.VERSIONS.docx)

**Comment by Quetzacoalt91** [comment] 2018-10-09 15:08
It seems the SQL upgrade is properly done.

Your issue could be caused by something else. Once you upgraded your shop, you should have a look at the PHP logs. You may find some HTTP 500 errors, PHP notices, warning or errors... You can already see that the module `posslideshow` triggers errors on your shop.

**Comment by LSClaire** [comment] 2018-10-17 12:55
Still no luck with that upgrade! :( :(

**Comment by khouloudbelguith** [comment] 2018-12-11 11:20
Hi @LSClaire,

We released a new version for the 1-click upgrade v4.5.1.
You can download this module from our Marketplace: https://addons.prestashop.com/en/data-migration-backup/5496-.html
Thanks to check with the new version & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-11 16:50
Hi @LSClaire,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-11 16:50 UTC
Labels: Autoupgrade, No change required, 1.7.4.2
