### ISSUE TITLE
Carrier form broken PS 8.0.4

### ISSUE THREAD

**Issue by s2amaxime** [PrestaShop/PrestaShop#32887] opened 2023-06-13 07:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Capture d’écran 2023-06-13 à 09 38 56](https://github.com/PrestaShop/PrestaShop/assets/66297818/454cb407-5988-4bad-a667-336c24c33a15)

Carrier form HTML is broken on PS 8.0.4 due to JS error.

Console shows : 

![Capture d’écran 2023-06-13 à 09 48 12](https://github.com/PrestaShop/PrestaShop/assets/66297818/861a2ace-532a-49c1-bb35-e49585175b9d)

French translations seem to contain " ' " which prints like so : 

var need_to_validate = 'Veuillez valider la dernière tranche avant d'en ajouter une nouvelle.';

This causes the JS to crash.

Fix : 

After you add " \ " before the single quotation mark for all the translations that need this fix it works again.

### Expected behavior

The carrier form HTML should show correctly.

### Steps to reproduce

1/ Install PS 8.0.4

2/ Go to carriers listing

3/ Try to add or edit a carrier

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4.33

**Comment by djoelleuch** [comment] 2023-06-13 16:11
Hello @s2amaxime ,
I didn't reproduce the issue as you can see below : 

[Untitled_ Jun 13, 2023 6_09 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/5a815e12-074c-4cb3-9657-9013d042534d)

did i miss something ? 
thank you !

**Comment by florine2623** [comment] 2023-06-20 12:18
Hello @s2amaxime ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2023-06-20 12:18 UTC
Labels: Bug, BO, Shipping, Carriers, Invalid, 8.0.4
