### ISSUE TITLE
Error 500 when trying to access to FO page in french

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#13377] opened 2019-04-12 09:20 UTC
**Describe the bug**
For my case I've installed a simple shop with language: english and country: France and after successfully installed the shop, I've tried accessing to the home page /fr by changing the language in french.

**To Reproduce**
1. Go to your home page
2. Click on language and set french
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/29543279/56026670-f0ab5480-5d14-11e9-8404-5515aa5299e7.png)

https://drive.google.com/file/d/1rK6jXxx6K7s4RnVVpxLavxpZFTCtrFH7/view

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7

**Comment by matks** [comment] 2019-04-12 09:29
Looks like a duplicate of https://github.com/PrestaShop/PrestaShop/issues/13247

**Comment by khouloudbelguith** [comment] 2019-04-12 09:31
Hi @mbadrani,

Your ticket is a duplicate of #13247
So, I close it.
Thanks!

**Comment by mbadrani** [comment] 2019-04-12 09:32
yes definitely

**Comment by khouloudbelguith** [comment] 2019-04-12 09:32
Duplicate of #13247

**Closed as completed by khouloudbelguith** 2019-04-12 09:31 UTC
Labels: Duplicate
