### ISSUE TITLE
Prestashop 1.7.2.4 Problem with multiple carrier

### ISSUE THREAD

**Issue by kiweez63** [PrestaShop/PrestaShop#10204] opened 2018-08-29 17:01 UTC
Hello.
There is a problem with different carriers depending on the products.
If a customer puts in his basket products that do not have the same carrier, this bug.
It is always the carrier of the last product that will be displayed.
What to do ?

**Comment by khouloudbelguith** [comment] 2018-08-30 07:26
Hi @kiweez63,

Your ticket is a duplicate of #9998
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-08-30 07:26
Duplicate of #9998

**Closed as completed by khouloudbelguith** 2018-08-30 07:26 UTC
Labels: Duplicate
