### ISSUE TITLE
Unable to translate emails subjects from ps_emailalerts

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#24724] opened 2021-06-01 09:27 UTC
#### Describe the bug

Unable to translate emails subjects from `ps_emailalerts` module.
Translations are missing from `EmailsSubject.xlf` file and don't appear in the interface.

#### Expected behavior

We need to be able to translate the subjects of these emails.

As I discussed with @jolelievre on Slack, `ps_emailalerts` module is no longer a native module and must use its own translation domain. I'll make a PR soon to replace `Emails.Subject` translation domain in this module.

#### Steps to Reproduce

1. Install `ps_emailalerts` module (last version)
2. Go to BO translation interface (for emails subjects)
4. See missing translations of `ps_emailalerts` module

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1.x

**Comment by hibatallahAouadni** [comment] 2021-06-01 10:49
Hello @micka-fdz 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17810. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-01 10:49
Duplicate of #17810

**Closed as completed by hibatallahAouadni** 2021-06-01 10:49 UTC
Labels: Duplicate

**Comment by micka-fdz** [comment] 2021-06-01 12:14
Hi @hibatallahAouadni,

My issue isn't related to #17810. Mine is about translations of email subjects, not FO translations.

Can you please reopen my issue? Like I said, I'm in discussion with @jolelievre and I'll make a PR soon.

**Comment by hibatallahAouadni** [comment] 2021-06-01 16:20
@micka-fdz is it related to #17096?

**Comment by micka-fdz** [comment] 2021-06-02 08:02
Yes @hibatallahAouadni, it's related to the switch on new translation system for email subjects.

**Comment by hibatallahAouadni** [comment] 2021-06-04 02:55
Hello @micka-fdz 

> 3. See missing translations of `ps_emailalerts` module

Could you please at least specify which translations are missing. And if you could provide screenshots it will be helpful. I need to reproduce the issue to reopen it :wink:

Thanks!

**Comment by micka-fdz** [comment] 2021-06-04 07:45
Hi @hibatallahAouadni,

Missing translations are those with `Emails.Subject` domain:

- Product available
- New order : #%d - %s
- Product out of stock
- Stock coverage
- New return from order #%d - %s
- Your order has been changed

They don't appear in BO translation interface and subjects of emails sent are not translated.
Try to install the module, configure it, place an order (for example) and have a look at received mail.
