### ISSUE TITLE
Plain json shown after payment module install/disable

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#24314] opened 2021-05-03 12:33 UTC
#### Describe the bug

When installing/disabling any payment module in **BO -> Payments -> Payment methods** plain json response is shown instead of normal page rendering.

#### Expected behavior

I would expect a redirection back to the page with success message.

#### Steps to Reproduce

1. Go to admin page -> Improve -> payment -> Payment methods
2. Click on "Installed" tab
3. Disable any existing payment method (e.g. ps_wirepayment)
4. See the plain json

**Screenshots**

![Screenshot from 2021-05-03 15-32-08](https://user-images.githubusercontent.com/31609858/116876231-ce9b0c80-ac24-11eb-97fa-7ad4b2174e27.png)

#### Additional information

* PrestaShop version: develop (might be same on 1.7.8.x and older)
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-05-04 03:40
Hello @zuk3975 

Thanks for your issue!
I reproduce the issue with develop and 1.7.8.x.
When I try to reproduce the issue with 1.7.8.x (not updated since friday), I get this error:

![image](https://user-images.githubusercontent.com/23308427/116958403-cbdafe80-ac9a-11eb-8e72-042d6862a91b.png)

After updating the branch, I get the same error as develop:

![image](https://user-images.githubusercontent.com/23308427/116958426-e44b1900-ac9a-11eb-8dc5-470e99c74b2c.png)

’ll add this to the debug backlog so that it’s fixed.

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

**_PS: I didn't manage to reproduce it with PS1.7.7.3, so it's a regression!_**

_PS: This issue only occurs if you try to disable/enable the payment module in **Payment Methods**, in **Module Manager** it works._

Thank you

**Comment by atomiix** [comment] 2021-05-12 12:46
Fixed by #24461

**Closed as completed by atomiix** 2021-05-12 12:46 UTC
Labels: Bug, develop, Major, BO, Payment methods, Regression, Fixed, PR available, 1.7.8.x
