### ISSUE TITLE
Product.php: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by MarcorOnline** [PrestaShop/PrestaShop#27482] opened 2022-01-27 09:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Enable DEBUG MODE and you can see this error on Frontend Product Page:

```
ContextErrorException
Notice: Trying to access array offset on value of type bool

in Product.php line 4071
at ProductCore::isDiscounted(75)
in LoyaltyModule.php line 99
at LoyaltyModule::getCartNbPoints(object(Cart), object(Product))
in myprestaloyalty.php line 327
at myprestaloyalty->hookdisplayProductAdditionalInfo(array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))
in Hook.php line 997
at HookCore::coreCallHook(object(myprestaloyalty), 'hookDisplayProductAdditionalInfo', array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))
in Hook.php line 421
at HookCore::callHookOn(object(myprestaloyalty), 'displayProductAdditionalInfo', array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2))
in Hook.php line 934
at HookCore::exec('displayProductAdditionalInfo', array('product' => object(ProductLazyArray), 'smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 2), null)
in smarty.config.inc.php line 167
at smartyHook(array('h' => 'displayProductAdditionalInfo', 'product' => object(ProductLazyArray)), object(SmartyDevTemplate))
in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayProductAdditionalInfo', 'product' => object(ProductLazyArray)), object(SmartyDevTemplate)))
in be53dbcee404ab2590cdbfc436ba2735c9628a7e_2.file.product-additional-info.tpl.php line 25
at content_61f19031935b52_12529096(object(SmartyDevTemplate))
in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))
in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))
in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()
in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('file:catalog/_partials/product-additional-info.tpl', null, 'classiclayouts/layout-full-width.tpl', 0, 3600, array(), 0, false)
in 9ca295cef0469d1cb8bbe22996aeacf0882a734e_2.file.product.tpl.php line 318
at Block_33857334761f19030b29c90_46525347->callBlock(object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_33857334761f19030b29c90_46525347), object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_33857334761f19030b29c90_46525347))
in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_33857334761f19030b29c90_46525347', 'product_additional_info', 0)
in 9ca295cef0469d1cb8bbe22996aeacf0882a734e_2.file.product.tpl.php line 367
at Block_53558131861f19030ac4a97_68640074->callBlock(object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_53558131861f19030ac4a97_68640074), object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_53558131861f19030ac4a97_68640074))
in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_53558131861f19030ac4a97_68640074', 'product_buy', 0)
in 9ca295cef0469d1cb8bbe22996aeacf0882a734e_2.file.product.tpl.php line 819
at Block_195224887061f19030a8d653_24771408->callBlock(object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_195224887061f19030a8d653_24771408), object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_195224887061f19030a8d653_24771408), object(Block_158171744161f1900de2e195_34729021))
in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_158171744161f1900de2e195_34729021))
in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_158171744161f1900de2e195_34729021', 'content', 1)
in 0a717cc42b62bc061e8345866cd950e1ca66e78a_2.file.layout-full-width.tpl.php line 101
at Block_168835898161f1900de2cf38_34013956->callBlock(object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_168835898161f1900de2cf38_34013956), object(SmartyDevTemplate))
in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_168835898161f1900de2cf38_34013956), object(Block_39983347761f1900df090d9_10897541))
in smarty_internal_runtime_inheritance.php line 186
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_39983347761f1900df090d9_10897541))
in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_39983347761f1900df090d9_10897541', 'content_wrapper')
in 4b920b16f553888f1ed13d5807f0f9a55d41ee0c_2.file.layout-both-columns.tpl.php line 92
at content_61f1900df3ce98_83835673(object(SmartyDevTemplate))
in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))
in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))
in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()
in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'classiclayouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)
in smarty_internal_runtime_inheritance.php line 116
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')
in 0a717cc42b62bc061e8345866cd950e1ca66e78a_2.file.layout-full-width.tpl.php line 42
at content_61f1900de2f995_61905937(object(SmartyDevTemplate))
in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))
in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))
in smarty_internal_template.php line 216
at Smarty_Internal_Template->render()
in smarty_internal_template.php line 385
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'classiclayouts/layout-full-width.tpl', 0, 3600, array(), 2, false, null, null)
in smarty_internal_runtime_inheritance.php line 116
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')
in 9ca295cef0469d1cb8bbe22996aeacf0882a734e_2.file.product.tpl.php line 56
at content_61f19030bcd6d4_34813588(object(SmartyDevTemplate))
in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))
in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))
in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)
in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'classiclayouts/layout-full-width.tpl', null, 0)
in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('catalog/product.tpl', null, 'classiclayouts/layout-full-width.tpl', null, false, true, false)
in SmartyDev.php line 40
at SmartyDev->fetch('catalog/product.tpl', null, 'classiclayouts/layout-full-width.tpl')
in FrontController.php line 727
at FrontControllerCore->smartyOutputContent('catalog/product.tpl')
in FrontController.php line 709
at FrontControllerCore->display()
in FrontController.php line 13
at FrontController->display()
in Controller.php line 326
at ControllerCore->run()
in Dispatcher.php line 518
at DispatcherCore->dispatch()
in index.php line 28
```

### Expected behavior

Fix the class **Product.php** to check with **isset** the result of **getCountryAndState** function

### Steps to reproduce

1. Enable PHP 7.4
2. Enable DEBUG MODE
3. Go to Product Page

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-01-27 11:47
Hello @MarcorOnline 

I didn't manage to reproduce the issue with PS1780 and PHP7.4 while the debug mode enabled, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/151352814-890b1263-21ee-4435-bf49-495efe896539.mp4

Please check and feedback.
Thanks!

**Comment by MarcorOnline** [comment] 2022-01-27 19:07
Hello @hibatallahAouadni 

My configuration:
PHP: 7.4.27
Prestashop: 1.7.8.3

This is my suggested fix:
https://github.com/PrestaShop/PrestaShop/pull/27480

My proposal is to use **isset** inside the function **isDiscounted**.
This is already used, in the same way, inside the function **_getProductIdByDate**

**Comment by khouloudbelguith** [comment] 2022-01-28 15:38
Hi @MarcorOnline,

I tried in my case PS1783 + php 7.4.27 => it is ok.
I attached a screen record

https://user-images.githubusercontent.com/16067358/151575917-951104a3-6203-42cc-b3a4-da26d5a63c9a.mp4

What is the exact type of the product?
Is there any specific price related to this product?

Thanks!

**Comment by MarcorOnline** [comment] 2022-01-28 15:58
@khouloudbelguith try these steps:

- Install and enable this module:
https://mypresta.eu/modules/advertising-and-marketing/loyalty-points.html
- Go to a product page

The extension use the core function "isDicounted" (inside Product.php class), but this function is bugged.

I know that "loyalty-points" is not a Core Module, but it's usefull to found the issue, because it call a Product.php function.

________

REMEMBER:
The function **isset** is already used inside the function **_getProductIdByDate**

______

Thanks

**Comment by khouloudbelguith** [comment] 2022-01-28 17:19
@MarcorOnline, did you try to contact the module author about this issue?
Is it not a module problem?

Thanks!

**Comment by MarcorOnline** [comment] 2022-01-29 11:24
@khouloudbelguith this is not a module bug, because the module simply use a core method that is bugged.

If you look at the function **_getProductIdByDate** you can see the same check (**isset**) suggested by me inside the method **isDicounted**

**Comment by florine2623** [comment] 2022-02-09 13:13
Hello @MarcorOnline ,

Without using your module I didn't encounter your issue. That means if you use this module and have the issue, the issue doesn't come from PS itself.

As @khouloudbelguith , you should contact the author of the module to get it fixed.

As the issue is not reproduce on our end, I will close it.
Thanks!

**Closed as completed by florine2623** 2022-02-09 13:13 UTC
Labels: Bug, BO, PR available, 1.7.8.0, Invalid

**Comment by danidomen** [comment] 2022-02-22 16:14
Hi @florine2623 ,

Reopened again here, and with the PR:
https://github.com/PrestaShop/PrestaShop/issues/27774
