### ISSUE TITLE
Prestashop 1.7 - Delayed shipping function does not work

### ISSUE THREAD

**Issue by kratekk** [PrestaShop/PrestaShop#16660] opened 2019-12-02 17:51 UTC
**Describe the bug**
With the "Delayed shipping" option enabled and the "Magayne management" option enabled and the "allow products ordered out of stock" option enabled, the option to split the order does not appear in the basket as it was in Prestashop 1.6. The function is available in the administration panel but is not programmed on the frontend side. Will it be developed in the future?

**Screenshots**
Delayed shipping function: https://prnt.sc/q56d8b
Allow to order products without stock and turned on function for managing stock: https://prnt.sc/q56dtb

**Additional information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment] 2019-12-03 08:14
Hi @kratekk,

Your ticket is a duplicate of #9781
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-03 08:14
Duplicate of #9781

**Closed as completed by khouloudbelguith** 2019-12-03 08:14 UTC
Labels: Duplicate
