### ISSUE TITLE
Contact information module 3.3.0 error

### ISSUE THREAD

**Issue by Macrisu** [PrestaShop/PrestaShop#20512] opened 2020-08-09 14:30 UTC
#### Describe the bug

Upgrade to 3.3.0 => error when I try to visit the index of the site.
The problem seems to be PS_contact_info
![error1](https://user-images.githubusercontent.com/16325429/89734632-f67a8c80-da65-11ea-84bd-1ad8aeaacfca.png)

(1/1) ContextErrorExceptionNotice: Undefined index: state
--
in 9992f3fe04dd41bcec1a2029cf07bead637caf4d_2.module.pscontactinfopscontactinf.php line 48

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-08-10 09:06
Hi @Macrisu,

I did not manage to reproduce the issue with PS1.7.6.7 and ps_contactinfo module v3.3.0.
I attached a screen record
https://drive.google.com/file/d/1j9pqY0gdN9siedVu4yTGakOX5TMqiz43/view?usp=sharing
Could you please try to re-install the ps_contactinfo module, clear cache, check, and feedback.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-31 08:30
Hi @Macrisu,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-31 08:30 UTC
Labels: Bug, FO, No change required, Contactinfo, 1.7.6.7
