### ISSUE TITLE
Cart not finding Delivery Options due to static::cache variables not tested correctly

### ISSUE THREAD

**Issue by SharmPRO** [PrestaShop/PrestaShop#13671] opened 2019-05-05 04:39 UTC
I had to investigate why suddenly PS 1.7.5.0 / PHP Version 7.2.16 did not find any available carrier for any checkout.
I tracked down to class/Cart.php functions using static::$cachePackageList and static::$cacheDeliveryOptionList being the problem.
Adding more strict tests on cache validity solve the problem.
E.g.

public function getPackageList($flush = false)
    {
        $cache_key = (int) $this->id . '_' . (int) $this->id_address_delivery;
        if (isset(static::$cachePackageList[$cache_key]) && static::$cachePackageList[$cache_key] !== false && !$flush) {
            return static::$cachePackageList[$cache_key];
        }

changed with:

public function getPackageList($flush = false)
    {
        $cache_key = (int) $this->id . '_' . (int) $this->id_address_delivery;
        if (isset(static::$cachePackageList[$cache_key]) && static::$cachePackageList[$cache_key] !== false && is_array(static::$cachePackageList[$cache_key]) && count(static::$cachePackageList[$cache_key])>0 && !$flush) {
            return static::$cachePackageList[$cache_key];
        }

and:

public function getDeliveryOptionList(Country $default_country = null, $flush = false)
    {
        if (isset(static::$cacheDeliveryOptionList[$this->id]) && !$flush) {
            return static::$cacheDeliveryOptionList[$this->id];
        }

changed with:

public function getDeliveryOptionList(Country $default_country = null, $flush = false)
    {
        if (isset(static::$cacheDeliveryOptionList[$this->id]) && is_array(static::$cacheDeliveryOptionList[$this->id]) && count(static::$cacheDeliveryOptionList[$this->id])>0 && !$flush) {
            return static::$cacheDeliveryOptionList[$this->id];
        }

**Comment by khouloudbelguith** [comment] 2019-05-07 07:40
Hi @SharmPRO,

Could you please add steps in a new comment to reproduce the issue.
in my case, I did not manage to reproduce your issue.

What to Check If PrestaShop Carriers Are Not Available At Checkout?

1.  Carrier Is Inactive: PrestaShop carrier status is the first thing you should consider
2. Incorrect Zone Assign or Country Disabled: Zone association is among the first things to check if a created carrier does not show for a specific shopper. When configuring PrestaShop carrier you are supposed to assign it to zones, this very carrier can deliver parcels within. If a carrier is not assigned to the zone, customer address belongs to, then it will not show as a delivery method at the checkout.
3. Carrier Is Not Allowed for Customer Group: This detail might easily be skipped, since you can have hundreds and thousands of customers, belonging to various customer groups. If some customer belongs to the group that is not served by the current shipper, it will not be offered as a delivery method for this customer
4. Weight or Price Ranges Are Not Specified: Creating PrestaShop carrier you usually define billing cost for each by one of the criteria: order price or weight. Having selected a suitable method, you need to create ranges and set prices for them. In case ranges are not created, “The product selection cannot be delivered by the available carrier(s). Please amend your cart” message will display at shipping step for a customer.
5- Package Dimensions Are Out of Range: If all above-listed settings are configured properly but still PrestaShop carrier does not display at the checkout, you have to compare package dimensions with maximum dimensions PrestaShop carrier can handle. If a package goes beyond these limits, the carrier can’t ship it and, respectively will not display as a delivery method.

PS: your issue could be similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/10903
Thanks to check & feedback.

**Comment by SharmPRO** [comment] 2019-05-07 09:41
Hi, 
- checked all carriers had no package limit ( all 0) NO Carriers available (Sfortunatamente, non ci sono vettori disponibili per il tuo indirizzo di consegna.)
- disabled the 2 cart rules ( with minimum amount not reached ) - Carriers available!
- enabled the 2 cart rules and one does not reach the minimum amount - NO Carriers available
- enabled the 2 cart rules and all do reach the minimum amount - Carriers available!
Checked on PS 1.7.5.0 1.7.5.2
similar  [#10903](https://github.com/PrestaShop/PrestaShop/issues/10903)
it is enough one rule with 'Minimum amount  & Shipping included'  to trigger the bug

**Comment by khouloudbelguith** [comment] 2019-05-07 09:52
@SharmPRO, thanks for your feedback.
So, your issue seelms to be similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/10903?
As described here: https://github.com/PrestaShop/PrestaShop/issues/10903#issuecomment-438573882
Thanks!

**Comment by SharmPRO** [comment] 2019-05-07 09:57
Correct

**Comment by khouloudbelguith** [comment] 2019-05-07 09:59
Duplicate of #10903

**Comment by SharmPRO** [comment] 2019-05-07 10:00
So there is no 'bug fix' ?

**Comment by khouloudbelguith** [comment] 2019-05-07 10:00
@SharmPRO, we are aware of this issue, it is added to our debug roadmap so that it will be fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Your ticket is a duplicate of #10903
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-07 09:59 UTC
Labels: FO, Duplicate, Shipping, 1.7.5.0

**Comment by SharmPRO** [comment] 2019-05-07 10:02
class/Cart.php

public function getPackageList($flush = false)
{
$cache_key = (int) $this->id . '_' . (int) $this->id_address_delivery;
if (isset(static::$cachePackageList[$cache_key]) && static::$cachePackageList[$cache_key] !== false && !$flush) {
return static::$cachePackageList[$cache_key];
}

changed with:

public function getPackageList($flush = false)
{
$cache_key = (int) $this->id . '_' . (int) $this->id_address_delivery;
if (isset(static::$cachePackageList[$cache_key]) && static::$cachePackageList[$cache_key] !== false && is_array(static::$cachePackageList[$cache_key]) && count(static::$cachePackageList[$cache_key])>0 && !$flush) {
return static::$cachePackageList[$cache_key];
}

and:

public function getDeliveryOptionList(Country $default_country = null, $flush = false)
{
if (isset(static::$cacheDeliveryOptionList[$this->id]) && !$flush) {
return static::$cacheDeliveryOptionList[$this->id];
}

changed with:

public function getDeliveryOptionList(Country $default_country = null, $flush = false)
{
if (isset(static::$cacheDeliveryOptionList[$this->id]) && is_array(static::$cacheDeliveryOptionList[$this->id]) && count(static::$cacheDeliveryOptionList[$this->id])>0 && !$flush) {
return static::$cacheDeliveryOptionList[$this->id];
}

**Comment by khouloudbelguith** [comment] 2019-05-07 10:18
@SharmPRO, Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by SharmPRO** [comment] 2019-05-08 17:03
Yes it will be an honor to contribute. Just no idea how it works.
I did open a Pull Request for another feature request but i think it is all wrong what i did.

**Comment by khouloudbelguith** [comment] 2019-05-09 08:33
@SharmPRO, you can follow our documentation: https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/
Thanks!
