### ISSUE TITLE
Wrong error when uploading favicon with bad extension

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#10271] opened 2018-09-04 13:31 UTC
**Describe the bug**
On fresh install of PS 1.7.4.2, a wrong error is displayed when uploading a favicon with an undesired  format (like .png or .gif): "You do not have permission to edit this." (EN) - "Vous n'avez pas la permission de modifier ce contenu." (FR)

**To Reproduce**
1. Go to Design  > Theme & logo > Favicons menu
2. Click on 'Add a file' and add an image (or other) file type .png, .gif, .jpg... 
3. Save
4. Warning displayed
5. Retry with .ico file, it's working

**Screenshots**
![](https://i.imgur.com/NeGAOt5.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-09-04 13:42
Hi @Klemart3D,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2.
The red alert is wrong when uploading a jpeg image.
It should be like in PS1.7.2.4.
![image](https://user-images.githubusercontent.com/16067358/45035394-25a64900-b05a-11e8-8eb9-46eb666f703f.png)

We will see how to fix it.

Best regards, Khouloud

**Comment by ink-ru** [comment] 2019-03-01 07:49
I have download newest prestashop. The problem still exists.

**Comment by khouloudbelguith** [comment] 2019-03-01 08:08
Hi @ink-ru,

The issue is not fixed yet, it is added to our bug roadmap.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-09 12:16
Hi,

This issue is fixed in the PS1.7.6.0.
![image](https://user-images.githubusercontent.com/16067358/57452809-a1e1d380-725c-11e9-9ae5-eec167f47161.png)
I close the issue.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-09 12:16 UTC
Labels: Bug, Minor, BO, Theme & logo, Fixed, 1.7.4.2
