### ISSUE TITLE
Languages and localization unaccessible due to filter_id

### ISSUE THREAD

**Issue by krasnycz** [PrestaShop/PrestaShop#17320] opened 2020-01-23 10:57 UTC
I have an issue after upgrade from 1.7.5.0 multistore to 1.7.6.2/3. Whole update goes fine however I am unable to access Languages and Languages in Localization. I get the following error:

An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1' with params [4, 1, "language"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.filter_id' in 'field list'

**Comment by khouloudbelguith** [comment] 2020-01-23 11:03
Hi @krasnycz,

Thanks for your report.
This issue was fixed in the last version PS1.7.6.1 with this PR: https://github.com/PrestaShop/PrestaShop/pull/14620 as reported here: https://github.com/PrestaShop/PrestaShop/issues/14617
Here's a provisional solution:

`ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;`

I will close this issue as a duplicate of https://github.com/PrestaShop/PrestaShop/issues/17310
Please follow: https://github.com/PrestaShop/PrestaShop/issues/17310

Thanks!

**Comment by krasnycz** [comment] 2020-01-23 11:08
This seems to fix the currencies page. However languages still gives:

An exception occurred while executing 'SELECT l.* FROM ps_lang l ORDER BY id_currency asc LIMIT 50 OFFSET 0':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_currency' in 'order clause'

**Comment by khouloudbelguith** [comment] 2020-01-23 11:18
@krasnycz, thanks to provide a screenshot from the table ps_cuurency & ps_currency_lang.
PS: in my case, I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.7.5.1 using the 1-click upgrade v4.10.1.
https://drive.google.com/file/d/1JutVHUjSHft-WUuqW4ZOTuSFzok3lE9l/view
Thanks!

**Comment by krasnycz** [comment] 2020-01-23 11:22
The strange is that in the https://github.com/PrestaShop/PrestaShop/blob/1.7.6.3/install-dev/data/db_structure.sql there is no "CREATE TABLE for PREFIX_lang.

ps_lang https://nimb.ws/0L6yNX
ps_currency https://nimb.ws/CMnTWV
ps_currency_lang https://nimb.ws/r1hVGi

**Comment by khouloudbelguith** [comment] 2020-01-23 11:26
@krasnycz, symbols of the second & the third currencies are missing in all languages
![image](https://user-images.githubusercontent.com/16067358/72980795-8ebb6780-3ddb-11ea-8604-b5497b25a4b5.png)


Thanks to edit this table `ps_currency_lang` & add all symbols.

Thanks to check & feedback.

**Comment by krasnycz** [comment] 2020-01-23 11:58
Well I tried it before. Now again. It did not help.

**Comment by khouloudbelguith** [comment] 2020-01-23 12:08
@krasnycz, thanks to navigate to the BO => International => Translations => update all your languges.
![image](https://user-images.githubusercontent.com/16067358/72983375-6c2c4d00-3de1-11ea-860c-c2bb38e716ca.png)

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by krasnycz** [comment] 2020-01-23 12:21
All languages updated. Cache cleared manually. Same result.

See complete error at https://nimb.ws/0jXtJk

Where can I see PREFIX_lang table structure? It is not included in the sql file.

**Comment by khouloudbelguith** [comment] 2020-01-23 13:45
@krasnycz, thanks to edit those currencies EUR & PLN in the `ps_currency` table.
![image](https://user-images.githubusercontent.com/16067358/72989629-ed3e1100-3dee-11ea-8331-d59259c64077.png)

Thanks!

**Comment by krasnycz** [comment] 2020-01-23 14:36
I tried to to add currency symbols and laos iso code and change precision prior opening this ticket. I tried it again now but it did not help :(

Same error persists.

**Comment by khouloudbelguith** [comment] 2020-01-23 15:09
@krasnycz, could you please try to navigate to the BO => International => Localization page => import the:

- Czech republic pack
- Poland pack
- Germany pack
- Slovakia pack

![image](https://user-images.githubusercontent.com/16067358/72996219-a1916480-3dfa-11ea-9878-140a13887184.png)

Thanks!

**Comment by krasnycz** [comment] 2020-01-23 16:10
Same results :(

**Comment by khouloudbelguith** [comment] 2020-01-23 16:16
@krasnycz, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by krasnycz** [comment] 2020-01-23 16:18
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4104047/log.txt)

Can you tell me what is correct ps_lang db structure?

**Comment by khouloudbelguith** [comment] 2020-01-23 16:44
@krasnycz, the structure of `ps_lang`
![image](https://user-images.githubusercontent.com/16067358/73004633-f25b8a00-3e07-11ea-865b-9a9106d93dc5.png)

Thanks!

**Comment by krasnycz** [comment] 2020-02-12 08:04
Well I installed clean 1.7.6.3 and compared db scheme with my production. It is same.

When I try access Currency or Languages in the BO it simply trying to use non-exist column "id_log" from ps_currency or ps_lang tables.

**Comment by krasnycz** [comment] 2020-02-12 08:30
Well I found the issue. Something is creating record in the ps_admin_filter where controller and action coumn is empty and in filter content is

{"limit":50,"orderBy":"id_lang","sortOrder":"ASC","filters":[],"filter_category":"","filter_column_id_product":"","filter_column_name":"smart","filter_column_reference":"","filter_column_name_category":"","filter_column_price":"","filter_column_sav_quantity":"","filter_column_active":"","last_offset":"0","last_limit":"20","last_orderBy":"sav_quantity","last_sortOrder":"asc"}

This record causes the issue. Do you have any idea why this occurs?

**Comment by khouloudbelguith** [comment] 2020-02-12 09:10
@krasnycz, thanks to provide me a screenshot from your table `ps_admin_filter` and also the structure of this table.
![image](https://user-images.githubusercontent.com/16067358/74319775-c89ae080-4d7f-11ea-8be5-a57b3a4428f2.png)
![image](https://user-images.githubusercontent.com/16067358/74319790-d51f3900-4d7f-11ea-981b-123c495091da.png)

Thanks!

**Comment by krasnycz** [comment] 2020-02-12 09:41
https://nimb.ws/clgO7P
https://nimb.ws/qeuHo1

**Comment by khouloudbelguith** [comment] 2020-02-12 09:59
@krasnycz, thanks to run this SQL command

```ALTER TABLE `ps_admin_filter` CHANGE `filter_id` `filter_id` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;```

Thanks!

**Comment by krasnycz** [comment] 2020-02-12 13:42
Well it did not help. But the error is different:

An exception occurred while executing 'INSERT INTO ps_admin_filter (employee, shop, controller, action, filter, filter_id) VALUES (?, ?, ?, ?, ?, ?)' with params [4, 1, "", "", "{\"limit\":50,\"orderBy\":\"id_currency\",\"sortOrder\":\"asc\",\"filters\":[]}", "currency"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-1--' for key 'admin_filter_search_idx'

**Comment by khouloudbelguith** [comment] 2020-02-12 13:47
@krasnycz, on the same page? Languages page?
You have duplicated data in your table `ps_admin_filter` for the `id=4`.

Thanks!

**Comment by krasnycz** [comment] 2020-02-12 15:24
I know. But when I delete the data currency/language works. However when I access the page 2nd time it again generates the error and page is not accessible. And duplicate data are there again.

**Comment by krasnycz** [comment] 2020-02-12 15:26
The problem are these data https://nimb.ws/5xPfmD

Once in the table pages are not accesible. When deleted the pages works on first view only.

**Comment by khouloudbelguith** [comment] 2020-02-12 15:33
@krasnycz, could you please try to delete the table `ps_admin_filter` & re-upload it again from a fresh install PS1.7.6.3.

Please make sure you have a backup of your database & your files.

Thanks!

**Comment by krasnycz** [comment] 2020-02-12 16:27
After clean install this table is empty. I emptied the table on staging and also noticed that clean 1.7.6.3 install also has unique filter_id so I adjusted the settings of the table. All seems to be fine now.

**Comment by khouloudbelguith** [comment] 2020-02-12 16:38
@krasnycz, Great!
I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-12 16:38 UTC
Labels: Bug, BO, Languages, Autoupgrade, No change required, 1.7.6.3

**Comment by krasnycz** [comment] 2020-03-12 13:09
Unfortunately 1.7.6.4 again got issue even after the fix. When try access langauges or currencies on production with debug mode OFF I got error

[2020-03-12 14:06:04] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "Unrecognized field: filterId" at /home/ABC.ABC.com/ABC/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 101 {"exception":"[object] (Doctrine\\ORM\\ORMException(code: 0): Unrecognized field: filterId at 

With debug mode ON it works fine.

Same issue reported here

https://www.prestashop.com/forums/topic/1012729-some-issues-after-upgrading-from-1752-to-1762/
