### ISSUE TITLE
Error creating product via webserice

### ISSUE THREAD

**Issue by xonox** [PrestaShop/PrestaShop#23183] opened 2021-02-08 21:34 UTC
#### Describe the bug

Insert a product record via web services API - OK

Then update the product stock - OK

The problem is that the product is never displayed in the stock management screen on backoffice.

#### Expected behavior

I except to see the product in the stock management no only in products.

#### Steps to Reproduce

The problem is a dummy record inserted into product_attributes table for every product I create via API.

If I create the product from the UI no additional record is created in the product_attributes table.

If I delete by hand from product_attributes the dummy record created by the API invocation the product gets displayed in the management screen.

#### Dummy row generated by API invoication

```sql
INSERT INTO `ps_product_attribute` (`id_product_attribute`, `id_product`, `reference`, `supplier_reference`, `location`, `ean13`, `isbn`, `upc`, `wholesale_price`, `price`, `ecotax`, `quantity`, `weight`, `unit_price_impact`, `default_on`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `available_date`) VALUES (77, 61, NULL, NULL, NULL, NULL, NULL, NULL, 0.000000, 0.000000, 0.000000, 0, 0.000000, 0.000000, NULL, 1, NULL, 0, NULL);
```

#### API Invocation

```php
<?php

require_once('./vendor/autoload.php');

try {
	
    // creating webservice access
    $webService = new PrestaShopWebservice('URL', 'API_SECRET', true);
 
    $opt = array();
    
    $opt['resource'] = 'products';
    $opt['output_format'] = 'XML';

    // call to retrieve
    $opt['schema'] = 'blank';
    $xml = $webService->get($opt);
    unset($opt['schema']);
    
    $product = $xml->product->children();
    $product->state = 1;
    $product->active = 1;
    $product->reference = 'ref1';
	$product->name->language[0] = 'name1';
	$product->name->language[1] = 'nome1';
	$product->description->language[0] = 'description1';
	$product->description->language[1] = 'descrição1';
	$product->price = 10;
	$product->show_price = 1;
	$product->available_for_order = 1;
	$product->minimal_quantity = 1;
	$product->additional_delivery_times = 1;
	$product->pack_stock_type = 3;
	$product->id_tax_rules_group = 53;
	$product->weight = 5;
	$product->id_category_default = 4;
	$product->redirect_type = 404;
	
	$categories = $product->associations->addChild('categories'); 

	$category3 = $categories->addChild('category');
	$category3->addChild('id', 3);
	
	$category4 = $categories->addChild('category');
	$category4->addChild('id', 4);
	
    // call to post
    $opt['postXml'] = $xml->asXML();
    $xml = $webService->add($opt);
    unset($opt['postXml']);
    
    $product = $xml->product->children();

	//var_dump($product->id);
	//var_dump($product->associations[0]->stock_availables->stock_available[0]->id);
	
    $opt['resource'] = 'stock_availables';

	// call to retrieve
	$opt['schema'] = 'blank';
    $xml = $webService->get($opt);
    unset($opt['schema']);
    
    $stock_available = $xml->stock_available->children();
    $stock_available->id = $product->associations[0]->stock_availables->stock_available[0]->id;
    $stock_available->id_product = $product->id;
    $stock_available->id_shop = 1;
    $stock_available->id_product_attribute = 0;
    $stock_available->quantity = 3;
    $stock_available->depends_on_stock = 0;
    $stock_available->out_of_stock = 2;

    // call to put
	$opt['id'] = $stock_available->id;
	$opt['putXml'] = $xml->asXML();
    $xml = $webService->edit($opt);
	unset($opt['putXml']);
	unset($opt['id']);
    
    var_dump($xml);
    
} catch (PrestaShopWebserviceException $ex) {
    
    var_dump($ex);
    
}
```

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-02-09 08:29
Hello @xonox 

It seems your issue is similar to this one #17748
Could you please check it and feedback.

Thanks!

**Comment by xonox** [comment] 2021-02-09 12:23
Hi @hibatallahAouadni 

The other issue is exactly the same problem.

I found a workaround.

When I call the webservice I have to unset the combinations association before creating the product.

```php
unset($product->associations->combinations);
```

And the fix might be simple in the prestashop source code.

It seems the code misses to validate if the combinations are empty and always creates an empty product attribute record in product_attributes table.

Cheers.

**Comment by hibatallahAouadni** [comment] 2021-02-09 12:37
Hello @xonox 

> I found a workaround.

Glad to hear :tada: so could you please make a PR (Pull Request) to fix the issue :wink: 
Well, I had to close this issue cause it's a duplicate of #17748. 
Please subscribe to the issue mentioned above and don't forget to create a PR.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-09 12:37
Duplicate of #17748

**Closed as completed by hibatallahAouadni** 2021-02-09 12:37 UTC
Labels: Bug, WS, Duplicate, Stocks, 1.7.6.9
