### ISSUE TITLE
Broken sort by price for products with price based on Customer group

### ISSUE THREAD

**Issue by barglm** [PrestaShop/PrestaShop#22713] opened 2021-01-07 14:54 UTC
#### Describe the bug

When you set product prices and then create specific prices based on customer groups, the product index does not reflect this. When I sort by price from the cheapest, the order does not match the real product price. It is sorted by index price_min, which is not really the real price I can see as the customer who belongs in the group.

#### Expected behavior

I would expect the sorting to respect the real product price. Basic Prestashop sorting with disabled facetedsearch works fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/7255313/103906590-6fa70a00-5100-11eb-9192-14db613a85f4.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2
* Module version: 3.7.0

**Comment by Hlavtox** [comment] 2021-01-07 15:25
@barglm See https://github.com/PrestaShop/PrestaShop/issues/19810

You mitigate the issue by commenting part of the code, that indexes specific prices. In my case, users with specific prices are only like 5% of people. So, better if it works fine for the remaining 95% of customers... sucks

**Comment by barglm** [comment] 2021-01-07 15:38
@Hlavtox thank you Daniel, unfortunately, this project uses specific prices for B2B clients (maybe 10% of clients), but most important clients. I will try to resolve this, I will let you know in case I find a solution

**Comment by florine2623** [comment] 2021-01-08 08:43
Hi @barglm ,

I'll close your issue as it is a duplicate.
You can follow the progress directly on #19810 as @Hlavtox said.

Thanks!

**Comment by florine2623** [comment] 2021-01-08 08:43
Duplicate of #19810

**Closed as completed by florine2623** 2021-01-08 08:43 UTC
Labels: Duplicate
