### ISSUE TITLE
Shipping modal does not show up on IE 11

### ISSUE THREAD

**Issue by antho-girard** [PrestaShop/PrestaShop#11176] opened 2018-10-29 13:55 UTC
**Describe the bug**
On Internet Explorer 11, we cannot edit shipping number in the Shipping section (BO order page).
Instead of displaying the modal with the carriers list and the shipping number input, the page goes to the top. There're no JS errors in the console of the "developer tools".

**To Reproduce**
1. On IE 11, open an order in BO
2. Click the Edit button in the shipping section

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-29 14:18
Hi @antho-girard,

Thanks for your report.
Manage to reproduce the issue with 1.7.4.3 / 1.7.5.0.
We will see how to fix it.
Thanks.

**Comment by marionf** [comment] 2020-01-15 16:56
@khouloudbelguith 
Could you check if this issue is fixed on `1.7.7.x` branch with the migrated page ?
URL of the page: `/admin-dev/index.php/sell/orders/orders/5/`

**Comment by khouloudbelguith** [comment] 2020-01-16 09:46
Hi @marionf,

It is OK with PS1.7.7.x & Windows & os_version=10 & browser=IE & browser_version=11.0.
![image](https://user-images.githubusercontent.com/16067358/72513339-420ce500-384d-11ea-8dab-867603a357f5.png)
I will close the issue since it is fixed.
THanks!

**Closed as completed by khouloudbelguith** 2020-01-16 09:46 UTC
Labels: Bug, Trivial, BO, Order, Fixed, 1.7.4.3, 1.7.6.0
