### ISSUE TITLE
Invalid CSS property value

### ISSUE THREAD

**Issue by dali-rajab** [PrestaShop/PrestaShop#21068] opened 2020-09-18 17:55 UTC
https://github.com/PrestaShop/PrestaShop/blob/2460b01ad3dcc7af10349a6f60ea242b8bb767de/admin-dev/themes/default/sass/partials/_tables.sass#L14

https://github.com/PrestaShop/PrestaShop/blob/2460b01ad3dcc7af10349a6f60ea242b8bb767de/admin-dev/themes/default/sass/partials/_tables.sass#L45

the CSS `word-wrap` property does not have a `nowrap` value, these should be `white-space: nowrap` instead.

**Comment by sarahdib** [comment] 2020-09-21 08:05
Hello @dali-rajab ,

since the provided information isn't sufficient to reproduce the issue, we are closing it. Feel free to open a new one with all the requested information. 

Thank you!

**Closed as completed by sarahdib** 2020-09-21 08:05 UTC
Labels: No change required

**Comment by dali-rajab** [comment] 2020-09-21 09:26
@sarahdib the word-wrap CSS property accepts only these values;

word-wrap: normal|break-word|initial|inherit;

source: https://www.w3schools.com/cssref/css3_pr_word-wrap.asp

It's CSS basics, that doesn't need any more informations or issue reproduction, every body here knows what i am talking about, so please re-open this issue.
