### ISSUE TITLE
unable to update settings in product list

### ISSUE THREAD

**Issue by saad-elalfy** [PrestaShop/PrestaShop#12107] opened 2019-01-10 12:01 UTC
hello guys i need help in my prestashop in new update  1.7.5 
i cant save and new products its gives me  unable to update settings

**Comment by khouloudbelguith** [comment] 2019-01-10 13:10
Hi @saad-elalfy,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by saad-elalfy** [comment] 2019-01-13 18:36
hello 

the info you need 
thanks in the first 

goddady linux 

PrestaShop version (source)
 1.7.5.0

debug mode report
[PrestaShopDatabaseException]

Table 'biski2_ps2.ps_ttvcms_image_type' doesn't exist

SELECT * FROM `ps_ttvcms_image_type`  WHERE active = 1 AND id_shop = 1


at line 769 in file classes/db/Db.php

764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }

    DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
    DbCore->query - [line 613 - classes/db/Db.php] - [1 Arguments]
    DbCore->executeS - [line 78 - modules/ttvcmsblog/classes/ttvcmsimagetypeclass.php] - [1 Arguments]
    TtvcmsImageTypeClass::getAllImageTypes - [line 676 - modules/ttvcmsblog/classes/ttvcmspostsclass.php]
    TtvcmsPostsClass::getCategoryPosts - [line 400 - modules/ttvcmsblogdisplayposts/ttvcmsblogdisplayposts.php] - [5 Arguments]
    TtvcmsBlogDisplayPosts->executeHook - [line 428 - modules/ttvcmsblogdisplayposts/ttvcmsblogdisplayposts.php]
    TtvcmsBlogDisplayPosts->hookdisplayHome - [line 966 - classes/Hook.php] - [1 Arguments]
    HookCore::coreCallHook - [line 351 - classes/Hook.php] - [3 Arguments]
[error_log.zip](https://github.com/PrestaShop/PrestaShop/files/2753317/error_log.zip)

about screenshot now we not get error now  to get screen 

thanks  :)

**Comment by khouloudbelguith** [comment] 2019-01-15 14:41
Hi @saad-elalfy,

Could you please try to disable the `ttvcmsblog` module & `ttvcmsproductco` module, clear cache, check & feedback.
Thanks!

**Comment by saad-elalfy** [comment] 2019-01-16 18:47
hello khouloudbelguith 

now everything now working well but now the modulle ttvcmsblog  not working ! 
and i have something error else i have more than 5 images on the products image and sometime disappear like that image from there place  ! 

![50257242_297892894179733_8578876013285474304_n](https://user-images.githubusercontent.com/42609526/51271241-ad6c6e80-19cf-11e9-9cd0-69afd9a8ca7d.png)
thanks

**Comment by khouloudbelguith** [comment] 2019-01-17 08:35
Hi @saad-elalfy,

I'm glad that your issue is fixed.
About the `ttvcmsproductco` module, it's not provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
About the images issue, it could be a cache issue, you can clear cache manually by deleting all the folder into var/cache (prod & dev).
You should force refresh the browser (by pressing ctrl + shift + R on Windows / Linux, CMD + R on Mac OS).
Also, go to BO => Design => Image Settings => click on Regenerate thumbnails.
Thanks to check & feedback.

**Comment by saad-elalfy** [comment] 2019-01-17 11:12
hi khouloudbelguith  
ill do  now  ,  thank you very much :)

**Comment by khouloudbelguith** [comment] 2019-01-17 11:14
@saad-elalfy, thanks!
Waiting for your feedback.

**Comment by saad-elalfy** [comment] 2019-01-17 11:29
sorry from where i can do that

**Comment by khouloudbelguith** [comment] 2019-01-17 11:32
@saad-elalfy, sorry do you need to know how to do?
Thanks!

**Comment by saad-elalfy** [comment] 2019-01-17 11:33
sure ,  but i found it :)

**Comment by khouloudbelguith** [comment] 2019-01-17 11:34
@saad-elalfy, the issue is fixed?

**Comment by saad-elalfy** [comment] 2019-01-17 11:46
thanks the feedback done 
about issue 
i don`t know :D it sometimes appear and disappear ,it will showing after hard work

**Comment by saad-elalfy** [comment] 2019-01-17 12:12
hi khouloudbelguith  
please i have another issue  the in the search result the image its so big  !  
[20190117_140755.zip](https://github.com/PrestaShop/PrestaShop/files/2768553/20190117_140755.zip)

**Comment by khouloudbelguith** [comment] 2019-01-17 13:57
Hi @saad-elalfy,

This a different issue, can you open a new one with more information about your configuration.
About your first issue, since it is fixed, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-17 13:57 UTC
Labels: Bug, BO, No change required, 1.7.5.0

**Comment by evsport** [comment] 2019-01-23 19:50
Hello
I can't update the quantity in products combination list.
How can I fix this?
Can you please help me

Here my configuration:
Prestashop 1.7.4.2
Server information Linux #1 SMP Tue Oct 9 17:27:49 UTC 2018 x86_64

Server software version: Apache/2.4.37 (cPanel) OpenSSL/1.0.2q mod_bwlimited/1.4

PHP version: 7.0.33

Memory limit: 1024M

Max execution time: 600

Upload Max File size: 256M

Thank you

**Comment by khouloudbelguith** [comment] 2019-01-24 09:28
Hi @evsport,

This a different issue, can you open a new one with more information about your configuration.
Thanks!
