### ISSUE TITLE
Reorganize products 

### ISSUE THREAD

**Issue by willgo34** [PrestaShop/PrestaShop#20576] opened 2020-08-13 12:27 UTC
#### Describe the bug

When you try to reorganize products in a category and change the way the are appearing, when you click on save, a bug do dot save your modifications

#### Expected behavior

When you change the order of products, you can save and apply the new organisation

#### Steps to Reproduce

1. Go to 'Catalog->Product'
2. Click on 'Filter by category' and select a category
3. Click on 'Position"
4. Change position for 3 or 4 products
5. Click on save
6.See that changes are not applied

**Screenshots**

https://www.loom.com/share/330da75251b14a319c7c4937953fa869

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.31

**Comment by SimonGrn** [comment] 2020-08-13 15:16
Hello,

as stated by @sarahdib on your precedent issue (#20572), this is a duplicate of #15291.
I will close this issue.

**Comment by SimonGrn** [comment] 2020-08-13 15:17
Duplicate of #15291

**Closed as completed by SimonGrn** 2020-08-13 15:16 UTC
Labels: Duplicate, No change required
