### ISSUE TITLE
Prestashop 1.7.6.5 - not sendign notifications emails and there is no setting to choose for it.

### ISSUE THREAD

**Issue by TheSxW** [PrestaShop/PrestaShop#21091] opened 2020-09-21 13:40 UTC
i found out that in my Prestashop 1.7.6.5 its also not sending notifications i detect that this line isnt getting any configuration value compared to issue https://github.com/PrestaShop/PrestaShop/issues/10772
```php
$sendNotificationEmail = Configuration::get(self::SEND_NOTIFICATION_EMAIL);
```
in modules/contactform/contactform.php at line ~575
replacing that CONFIGURATION variable to true enables (hardcode) that variable to always being on but its not a proper solution if someone could respond to this and find proper solution i will be glad :)

additionally i was adding fields named CONTACTFORM_SEND_NOTIFICATION_EMAIL and CONTACTFORM_SEND_CONFIRMATION_EMAIL into db configuration but that didn't help much

ps. after hardcoding that variable to true system starts to sending an emails on contact form send (as notification for administration), i would like to know if there is any way to fix that ?

**Comment by sarahdib** [comment] 2020-09-21 14:16
Hello @TheSxW ,

Please follow the template when you submit a request.

Could you provide us the steps in order to try to reproduce.

Thank you!

**Comment by khouloudbelguith** [comment] 2020-10-12 11:56
Hi @TheSxW,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-12 11:56 UTC
Labels: No change required, Contactform
