### ISSUE TITLE
PDF Invoices : incorrect URLs for product images

### ISSUE THREAD

**Issue by WebXYAgency** [PrestaShop/PrestaShop#25505] opened 2021-08-04 14:43 UTC
#### Describe the bug

Product images can't be displayed in invoices because their URLs are incorrect.
The variable used to show products images uses files' physical paths instead of URIs (see screenshots).

#### Expected behavior

Product images shown in invoices when the "Enable product image" is enabled in "Orders" / "Invoices" menu.

#### Steps to Reproduce

1. Go to "Orders" / "Invoices" menu
2. Enable "Enable product image" option
3. Download an order invoice
4. The product images don't show

#### How to fix

1. Edit /classes/pdf/HTMLTemplateInvoice.php
2. Replace line 224 ($order_detail['image_tag'] assign) with the code below

`$order_detail['image_tag'] = ImageManager::thumbnail($path, $name, 45, 'jpg', false);`

**Screenshots**

##### Invoices without fix
![invoices without fix](https://user-images.githubusercontent.com/57484794/128198981-3cc95799-ad7f-4b71-b377-d3ca040d8a04.png)

##### Invoices with fix
![invoices with fix](https://user-images.githubusercontent.com/57484794/128200070-4f9c6329-55ce-4e3d-9ca4-2dadb4634a8a.png)

#### Additional information

* PrestaShop versions tested: 1.7.7.2 & 1.7.7.5
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2021-08-04 17:46
Hello @WebXYAgency 

I didn't manage to reproduce your issue with PS1775, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/128229265-29064ba8-3ec9-4160-a8b3-7275ab6cd736.png)

Please check and feedback.
Thanks!

**Comment by WebXYAgency** [comment] 2021-08-05 08:00
Can you add `&debug=1` to the invoice download URL and post the content of the `image_tag` variables ?

**Comment by khouloudbelguith** [comment] 2021-08-06 09:40
Hi @WebXYAgency,

I tried to navigate to this link: http://prestashop.com/1775stable/admin-dev/index.php?controller=AdminPdf&submitAction=generateInvoicePDF&id_order_invoice=5&token=6558c835df8ad9fbb392098bcae3e4ff&debug=1
I have no `image_tag`
![image](https://user-images.githubusercontent.com/16067358/128491146-5774f98f-8149-4f0b-b594-ca9ced4ab67a.png)

Thanks to check and feedback.

**Comment by WebXYAgency** [comment] 2021-08-06 12:37
Hi @khouloudbelguith,

Can you open the page in your browser code inspector and post the HTML code of the `<img>` tag ?

It should look like this 
![image_tag browser inspect without fix](https://user-images.githubusercontent.com/57484794/128511284-b21810d1-8492-48fa-97c2-1c121ac8aaf5.png)

**Comment by khouloudbelguith** [comment] 2021-08-06 13:57
Hi @WebXYAgency,

I have `<img src="\&quot;\/var\/www\/html\/1775stable\/img\/tmp\/product_mini_26_0.jpg\&quot;" alt="\&quot;\&quot;" class="\&quot;imgm" img-thumbnail\"="" \="">`

Thanks!

**Comment by WebXYAgency** [comment] 2021-08-13 13:06
Hi @khouloudbelguith,

It looks like you have the same problem as me.
Are your product images displayed in your PDF invoices?

**Comment by hibatallahAouadni** [comment] 2021-08-17 14:31
Hello @WebXYAgency 

> Are your product images displayed in your PDF invoices?

Yes they are!

**Comment by hibatallahAouadni** [comment] 2021-09-06 11:21
Hello @WebXYAgency 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-06 11:21 UTC
Labels: Bug, CO, Invoices, Image, No change required, PR available, 1.7.7.5
