### ISSUE TITLE
Refund products with customization not wokring

### ISSUE THREAD

**Issue by josef-var** [PrestaShop/PrestaShop#15683] opened 2019-09-25 09:51 UTC
Any order containing a product with customization will not allow refunds with 'An invalid quantity was selected for this product.' error.

Problem is line 943 of AdminOrdersController.php

$customization_quantity should be $customization_quantity['quantity']

**Comment by khouloudbelguith** [comment] 2019-09-25 11:04
Hi @josef-var,

In the BO => Customer Service =>  Merchandise Returns  => Did you enabled the "Enable returns" option?
Did you used " Return products" or "Partial refund"?
![image](https://user-images.githubusercontent.com/16067358/65595366-91709200-df8c-11e9-866d-7b8d1a2a3334.png)

Thanks!

**Comment by josef-var** [comment] 2019-09-25 14:53
We need to have a negative invoice, which is not possible with partial refund. We always use "Return products". The change in AdminOrdersController.php does solve the problem.

Thank you!

**Comment by khouloudbelguith** [comment] 2019-09-25 15:02
@josef-var, I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1DEo3ueujG5pVnaAeraPJvwPPKlM-I7XC/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-10-25 07:45
Hi @josef-var,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-25 07:45 UTC
Labels: Order, Product customization, No change required
