### ISSUE TITLE
Missing translation 'Password must be between 5 and 72 characters long' in ShopNotificationsError.de-DE.xlf

### ISSUE THREAD

**Issue by Hehn-MB** [PrestaShop/PrestaShop#29226] opened 2022-08-02 11:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

classes/form/CustomerForm.php calls within validate() at line 117
`$this->translator->trans(
                'Password must be between 5 and 72 characters long',
                [],
                'Shop.Notifications.Error'
            )`
at line 146 et seq but translation is missing in ShopNotificationsError.de-DE.xlf

### Expected behavior

Sth. like
`<trans-unit id="b09361692fc1f7636d9b8657b94a7bb4">
        <source>Password must be between 5 and 72 characters long</source>
        <target>Passwort muss eine Länge von 5 bis 72 Zeichen haben</target>
        <note>Line: 147</note>
      </trans-unit>`
in ShopNotificationsError.de-DE.xlf after line 108.

### Steps to reproduce

1. Select language DE if active
2. 'Proceed to checkout'
3. Set either no password or with a length of <5 or >72 characters in '1 Personal information'
4. Error 'Password must be between 5 and 72 characters long' appears but is not translated into DE

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-08-02 14:20
Hello @Hehn-MB 

> Error 'Password must be between 5 and 72 characters long' appears but is not translated into DE

Because you didn't fill in the field to translate:

![image](https://user-images.githubusercontent.com/23308427/182396756-b9705b78-02e4-4537-8e20-6b354dbc4d09.png)

When you fill in the missing translation:

![image](https://user-images.githubusercontent.com/23308427/182396912-a8b3445b-1b3a-4d25-a19c-2e4e107d9c38.png)

It will be well displayed in FO:

![image](https://user-images.githubusercontent.com/23308427/182397126-f548b82b-5798-4700-970f-4dacb0fe948a.png)

Closing the issue as it's not a bug :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2022-08-02 14:20 UTC
Labels: Bug, Invalid

**Comment by Hehn-MB** [comment] 2022-08-02 14:38
Hello,

I’m new to our Prestashop installation.
Within my system there’s no such a translation field.

***@***.***

All I see in Shop -> Notifications -> Error is…
***@***.***

Don’t know what’s wrong. Do you? Thanks in advance.

Best wishes
Heiko Hehn

**Comment by hibatallahAouadni** [comment] 2022-08-03 10:49
Hello @Hehn-MB 

> I’m new to our Prestashop installation.

Welcome :tada: hope you enjoy using PrestaShop :relaxed: 
> Within my system there’s no such a translation field.

Please follow the steps in my attached screen record below to find these fields to translate:

https://user-images.githubusercontent.com/23308427/182586010-ad63ca24-53d8-4ae6-ad1e-6a62a46a0d0c.mp4

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by Hehn-MB** [comment] 2022-08-03 12:21
Hi,

I’ve selected the wrong theme to us.

So I removed the lines
<trans-unit id="b09361692fc1f7636d9b8657b94a7bb4">
  <source>Password must be between 5 and 72 characters long</source>
  <target>Passwort muss eine Länge von 5 bis 72 Zeichen haben</target>
  <note>Line: 147</note>
</trans-unit>
from app/Resources/translations/de-DE/ShopNotificationsError.de-DE.xlf and added German translation as follows:

***@***.***

Translation is now in database:

***@***.***

But after clearing caches both in PrestaShop backend and in browser I get no translation.

***@***.***

Is the CustomerFormCore (classes/form/CustomerForm.php) really looking for database translation in table „ps_translation“?

***@***.***

Best wishes
Heiko

Heiko Hehn
Web Entwicklung
[MB_Logo_email]

Minerva Biolabs GmbH
Schkopauer Ring 13
D-12681 Berlin
Phone:  +49 (0)30 / 2000 437-0
[SM-01]<https://www.linkedin.com/company/12878525/>[SM-02]<https://twitter.com/minervabiolabs>[SM-04]<https://www.instagram.com/minerva_biolabs/>

***@***.******@***.***>    www.minerva-biolabs.com<http://www.minerva-biolabs.com/>
Sitz der Gesellschaft: Berlin; Registergericht Berlin-Charlottenburg; HRB 69805; USt.ID DE199467805; Geschäftsführer Dr. Dirk Vollenbroich
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail by error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
Member of the [Beschreibung: Dilarus_Group_196x69]


Von: Hibatallah Aouadni ***@***.***>
Gesendet: Mittwoch, 3. August 2022 12:49
An: PrestaShop/PrestaShop ***@***.***>
Cc: Heiko Hehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [PrestaShop/PrestaShop] Missing translation 'Password must be between 5 and 72 characters long' in ShopNotificationsError.de-DE.xlf (Issue #29226)


Hello @Hehn-MB<https://github.com/Hehn-MB>

I’m new to our Prestashop installation.

Welcome 🎉 hope you enjoy using PrestaShop ☺️

Within my system there’s no such a translation field.

Please follow the steps in my attached screen record below to find these fields to translate:

https://user-images.githubusercontent.com/23308427/182586010-ad63ca24-53d8-4ae6-ad1e-6a62a46a0d0c.mp4

If you need support, you can find resources to help you on this page: Get help with PrestaShop<https://www.prestashop-project.org/support/>.

Alternatively, you can also ask for help in the community forums<https://www.prestashop.com/forums/> or in the public Slack channel<https://prestashop.slack.com>.

Thank you
