### ISSUE TITLE
Incorrect date format in product comment

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#20337] opened 2020-07-24 19:01 UTC
#### Describe the bug
We use date format "Y-m-d h:i:s" but there is displayed data with incorrect format in product comment. 
There is displayed "24/07/2020, 19:07" but there should be displayed "2020-07-24 19:07" (also without comma between date and time).

_Format definition_
![image](https://user-images.githubusercontent.com/33311857/88425770-41eb3480-cdf0-11ea-810a-0ac56a61e56d.png)

_Product comment_
![image](https://user-images.githubusercontent.com/33311857/88425825-5a5b4f00-cdf0-11ea-8402-5db4d8459180.png)

#### Additional information
* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-07-27 08:28
Hi @juraj1000,

We are awre of the date format issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9591
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-27 08:28
Duplicate of #9591

**Closed as completed by khouloudbelguith** 2020-07-27 08:28 UTC
Labels: Duplicate, Productcomments
