### ISSUE TITLE
Product title considered as blank so I can't update my product

### ISSUE THREAD

**Issue by jnvgi** [PrestaShop/PrestaShop#13432] opened 2019-04-16 13:41 UTC
Hello,

I have a kind of annoying bug. I have products with combinations, i wanna update the quantity for each combination and when I do so i got an error message under my product title "This value should not be blank."
Sometimes the modification goes through, most of the time i stay stuck there. 
Of course my product title is not empty.

Note that I upgraded this website from 1.5 to the last version of 1.7.

![screen](https://user-images.githubusercontent.com/37938274/56213497-6e949600-605c-11e9-8b84-8fe20809e83f.png)

PrestaShop version: 1.7.5.1
PHP version: 5.6.40 (weirdly, because I setted engine to 7.1...)

**Comment by khouloudbelguith** [comment] 2019-04-16 13:55
Hi @jnvgi,

Could you please try to upgrade your PHP version to 7.1, clear cache from your shop and your navigator, check and feedback.

Thanks!

**Comment by jnvgi** [comment] 2019-04-16 13:58
I contacted my hosting provider to find out why the PHP vesion doesn't match the configuration i chose. Will keep you posted as soon as they reply (OVH tends to be veeeery slow since a few years...)

**Comment by khouloudbelguith** [comment] 2019-04-16 14:00
@jnvgi, waiting for your feedback!

**Comment by jnvgi** [comment] 2019-04-23 08:12
Hello there,

Well there was a misconfiguration in the PHP version naming. Hosting is now in PHP 7.1 but the problem still happen.
There are also many other bugs. I think the update from Prestashop 1.5 was kinda shitty...

**Comment by khouloudbelguith** [comment] 2019-04-23 08:15
Hi @jnvgi,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by jnvgi** [comment] 2019-04-23 08:43
Sure, but it's hard to reproduce since it's very random ! Sometimes changes are saved, sometimes I get this error.

It's a cloud hosting on OVH.
PHP version : 7.1.26
MySQL : 5.6
Prestashop version : 1.7.5.1

I get much of this in the console log : 
> ReferenceError: $ is not defined serp.js:131:2

And among the Ajax request, when the error occur, I get a status 400 on the xhr request that should update the product.

![error-400-xhr](https://user-images.githubusercontent.com/37938274/56567183-a2b80b80-65b4-11e9-8cef-914efec0d43d.png)

Sorry i'm not familiar at all with debugging Prestashop.

**Comment by khouloudbelguith** [comment] 2019-04-23 08:55
@jnvgi, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by jnvgi** [comment] 2019-04-23 09:17
I found this in the PHP error log : 
> [2019-04-23 10:41:46] translation.WARNING: Translation not found. {"id":"This value should not be blank.","domain":"validators","locale":"fr-FR"} []

That match with my error message. There are many other translation errors in the log. That's weird because i updated the langauge pack and everything is translated well in the BO.

[php_error_log.txt](https://github.com/PrestaShop/PrestaShop/files/3106763/php_error_log.txt)

Also, it looks like the form validation block on attributes. It says ecotax, minimal quantity and quantity should not be empty. I setted all, so I don't understand, and I don't even have ecotax field...

![form-validation](https://user-images.githubusercontent.com/37938274/56569439-3db2e480-65b9-11e9-840b-f74668105ffc.png)

**Comment by khouloudbelguith** [comment] 2019-04-23 13:35
@jnvgi, did you use multishop? and did you use multilanguage?

In your browser, you can use DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks to check & feedback.

**Comment by jnvgi** [comment] 2019-04-23 17:20
@khouloudbelguith Yep, i get the same message :
`{"step1_name_5":["This value should not be blank."]}`

No multishop and no multilanguage either :s

**Comment by khouloudbelguith** [comment] 2019-04-24 09:16
@jnvgi, thanks for your feedback.
Could you please provide the exact steps did you follow to upgrade your shop from 1.5 to 1.7 and what is the exact tool did you used to make the upgrade?
During the upgrade did you have any errors?
Thanks!

**Comment by jnvgi** [comment] 2019-04-24 12:07
@khouloudbelguith I upgraded from 1.5 to 1.6 thought the 1-click-upgrade plugin, using a local archive of the last version of PS 1.6 (1.6.1.23 if i remember well)
After that I uploaded PS 1.7.1.5 on my FTP and did the upgrade thought install/upgrade/upgrade.php.
Despite the blank page and the feel that nothing was working, I found out my PS was updated when I checked the website again.
The plugin 1-click-upgrade was just doing a backup of my setup and no update., that's why i forgot about it after a while.

**Comment by khouloudbelguith** [comment] 2019-04-24 13:57
@jnvgi, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by jnvgi** [comment] 2019-04-25 12:52
@khouloudbelguith Sorry for late reply, some Internet blackout :)
I cleared the folders, tried to edit about 20 products, message didn't appear anymore. We will assume it was once again a cache problem i guess !

**Comment by khouloudbelguith** [comment] 2019-04-25 13:05
@jnvgi, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-04-25 13:05 UTC
Labels: BO, Combinations, No change required, 1.7.5.1
