### ISSUE TITLE
Login Admin BO - error 500

### ISSUE THREAD

**Issue by nobodyelse84** [PrestaShop/PrestaShop#11020] opened 2018-10-16 07:09 UTC
**Describe the bug**
I'm trying to sign into the backend, with administration id and password, but I get a 500 error.
All the other users are logged in, but not the admin.

**Screenshots**
https://drive.google.com/open?id=1Jd7i5c2Ad4mwbn_QI4MgXHUggeATFO0L

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 5.5.38

Thank you in advance.
Giorgia

**Comment by GaetanNaulin** [comment] 2018-10-16 07:34
Same here with prestashop 1.6 or 1.7.2.. error 504 all the time..

**Comment by khouloudbelguith** [comment] 2018-10-16 08:02
Hi @nobodyelse84,

Could you please try to rename the `gamification` module to `gamification_off`.
You can find it, in your Project_Folder/modules/
Thanks to check & feedback.

**Comment by GaetanNaulin** [comment] 2018-10-16 08:22
This solution works for me, thanks !

**Comment by nobodyelse84** [comment] 2018-10-16 08:32
Sorry, but I have no "gamification" folder... :(

**Comment by khouloudbelguith** [comment] 2018-10-16 08:52
@nobodyelse84, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nobodyelse84** [comment] 2018-10-16 09:21
- atribute folder: 755 / atribute files: 755
- debug error report

<img width="1680" alt="schermata 2018-10-16 alle 11 18 37" src="https://user-images.githubusercontent.com/44086265/47006096-71f2a780-d135-11e8-9c8c-c19acdc46281.png">
<img width="1680" alt="schermata 2018-10-16 alle 11 18 30" src="https://user-images.githubusercontent.com/44086265/47006097-71f2a780-d135-11e8-93d4-a0e326863247.png">

I hope all these infos will be helpfull.
Thank you in advcanfe.

Giorgia

**Comment by khouloudbelguith** [comment] 2018-10-16 10:00
@nobodyelse84, Thanks for your feedback.
Could you please try to disable the ttcmsservices module in the Modules & Services pages.
You don't have access to the BO => You need to rename the ttcmsservices folder to ttcmsservices_off in the path Project_Folder/modules.
Could you please try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

**Comment by nobodyelse84** [comment] 2018-10-16 12:35
I was trying to erase the prod into the cache folder, but it replace all the files.
I've tried to log in and it doesn't work :(

**Comment by khouloudbelguith** [comment] 2018-10-16 12:56
@nobodyelse84 did you manage to rename the ttcmsservices folder?

**Comment by nobodyelse84** [comment] 2018-10-16 13:01
Yes, I did! I've rename adding _off
<img width="703" alt="schermata 2018-10-16 alle 15 00 42" src="https://user-images.githubusercontent.com/44086265/47018104-4fbc5200-d154-11e8-9203-f47074f733a0.png">

**Comment by khouloudbelguith** [comment] 2018-10-16 13:03
@nobodyelse84, Is there any other exceptions displayed?

**Comment by nobodyelse84** [comment] 2018-10-16 13:18
Are getting replaced always these folders and files:
<img width="712" alt="schermata 2018-10-16 alle 15 17 23" src="https://user-images.githubusercontent.com/44086265/47019154-ac207100-d156-11e8-9998-28754aad3cdc.png">

I was trying to replace the atribut to 777/755, but are getting replaced in this way.

**Comment by khouloudbelguith** [comment] 2018-10-16 13:29
@nobodyelse84, it could be a server restriction, you need to check your host about this issue.

**Comment by nobodyelse84** [comment] 2018-10-16 14:16
Thanks a lot!

Distinti saluti

Giorgia Bortesi
Cell. 366.1284643

**Comment by khouloudbelguith** [comment] 2018-10-16 14:17
@nobodyelse84, issue solved?

**Comment by nobodyelse84** [comment] 2018-10-16 14:21
No, I’m going to contact the host owner.
I’ll let you know.

Thanks again

Distinti saluti

Giorgia Bortesi
Cell. 366.1284643

**Comment by khouloudbelguith** [comment] 2018-10-16 14:24
@nobodyelse84, thanks!
Waiting for your feedback.

**Comment by nobodyelse84** [comment] 2018-10-17 11:10
Found the problem and risolve it: in the modules folder, I found two app that annoyed the structure:
<img width="410" alt="schermata 2018-10-17 alle 13 03 26" src="https://user-images.githubusercontent.com/44086265/47082486-fb75a880-d20d-11e8-8e35-0a5113b6432e.png">

Just disabled it and now everything it works perfectly.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-17 11:15
Hi @nobodyelse84,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-17 11:15 UTC
Labels: Bug, BO, Fixed
