### ISSUE TITLE
1.7.6 product-customizations not recording & lost when order placed by customer

### ISSUE THREAD

**Issue by Nexus6ITA** [PrestaShop/PrestaShop#16762] opened 2019-12-10 18:39 UTC
When client adding fields in custom product text, add to cart it's ok
but when customer placed AND PAY THE ORDER PRODUCT CUSTOMISATION IS LOST
NOT SHOWING ON BACK OFFICE not in customer order history, - not in email order_conf, for customer and merchant order
in BO line product have no customisation line !!! no information about this custom and it not appears on the Email
how to resolve it?
thank you.

**Comment by khouloudbelguith** [comment] 2019-12-11 09:11
Hi @Nexus6ITA,

I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1d8HOALQbE0LUsSTrQVDdKNb8dggzzRYH/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-13 08:02
Hi @Nexus6ITA,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-13 08:02 UTC
Labels: Bug, Product customization, No change required
