### ISSUE TITLE
New product. Bad error msg about product name field if try to save short name or blank.

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29163] opened 2022-07-25 16:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1. If the field with name is blank, two type of msg is displaying at one time:
![scrnli_7_25_2022_6-03-04 PM](https://user-images.githubusercontent.com/90208051/180824054-ba1437a0-8332-436d-9585-11b9b6746dd3.png)

2. If in name is too short, msg is duplicating. 

![scrnli_7_25_2022_6-03-08 PM](https://user-images.githubusercontent.com/90208051/180824135-76ab48bd-4f54-45e5-bb77-ec0c159e41b8.png)

### Expected behavior

1. If the field with name is blank
![scrnli_7_25_2022_5-56-13 PM](https://user-images.githubusercontent.com/90208051/180824338-9690e6a5-f348-4a28-9256-a25f4082d803.png)

3. If in name is too short
 
![scrnli_7_25_2022_5-57-32 PM](https://user-images.githubusercontent.com/90208051/180824371-dcb4df67-f10e-4acc-b0b8-0d28a8da1abc.png)

### Steps to reproduce

1. Create a new product in BO
2. Leave the product name field blank and click Save
3. Check Error msg
4. In product name field, enter a name less than 3 characters
5. Check Error msg

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2022-07-26 07:19
Hello @szavadskiy ,

I reproduce the issue with PrestaShop version 8.0.x and develop, I'll add this to the backlog so it can be fixed.
It is a regression, as it was well displayed in 1.7.8.x.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MeKeyCool** [comment] 2022-07-28 16:04
It seems the second part of this issue is related to https://github.com/PrestaShop/PrestaShop/issues/28877

We found a way to fix the constraint message consistency.
@szavadskiy , do you think it would be ok if we always (I mean blank or small string) "This value is too short. It should have 3 characters or more." ?

Some opinion @PrestaShop/product-team ?

**Comment by szavadskiy** [comment] 2022-07-29 08:28
Hello @MeKeyCool, yes I think it would be good, thank you.

**Comment by khouloudbelguith** [comment] 2022-07-29 08:49
Hello @szavadskiy,

Your ticket is not a duplicate of #28877?
@MeKeyCool, @yanmakouf fixes this issue with this PR: https://github.com/PrestaShop/PrestaShop/pull/29040 or they are related?

PS: sorry, I closed the issue by mistake!

Thanks!

**Comment by MeKeyCool** [comment] 2022-07-29 10:12
@khouloudbelguith and @szavadskiy after a discussion with @yanmakouf  and @MatShir , it looks that the problem is exactly the same than #28877 and @szavadskiy you were right about expected behavior.

I am currently investigating to understand the regression root cause ^^

**Comment by khouloudbelguith** [comment] 2022-07-29 10:44
@MeKeyCool, thanks for your feedback.

@szavadskiy, your ticket is a duplicate of #28877
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2022-07-29 10:45
Duplicate of #28877

**Closed as completed by khouloudbelguith** 2022-07-29 10:44 UTC
Labels: Bug, 8.0.x, Minor, BO, Duplicate, Regression, PR available, Verified
