### ISSUE TITLE
gsitemap module doesn't check group access for categories and products

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#27517] opened 2022-01-28 15:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Related to https://github.com/PrestaShop/PrestaShop/issues/16992
If a category isn't publicly accessible and limited to a specific customer group, this category and his products are still listed in the sitemap.

### Expected behavior

Don't list restricted categories and his products in the sitemap.

### Steps to reproduce

1. restict a category to the customer group
2. Generate sitemap
3. Check this category in the sitemap
4. Check for exclusive category's products

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

gsitemap all versions

**Comment by khouloudbelguith** [comment] 2022-01-28 16:04
Hi @jf-viguier,

Related to https://github.com/PrestaShop/PrestaShop/issues/16992.

I manage to reproduce the issue with PS1778 & PS1783 using gsitemap v4.2.0.
I’ll add this to the debug roadmap so that it’s fixed. 

https://user-images.githubusercontent.com/16067358/151580328-0eeda2e1-92f3-44c6-bce0-456ee930f8e4.mp4

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by jf-viguier** [comment] 2022-01-28 16:50
> we strongly suggest you consider hiring a specialist to help you
I can hire myself but not today.

**Comment by Hlavtox** [comment] 2022-12-03 14:13
@jf-viguier Fixed by https://github.com/PrestaShop/gsitemap/pull/156

**Closed as completed** 2023-01-09 10:45 UTC
Labels: Bug, Minor, BO, Customer, Categories, Fixed, Google sitemap, 1.7.7.8, Verified, Module
