### ISSUE TITLE
dashproducts module - SQL error with refunded product in validated order

### ISSUE THREAD

**Issue by NicolasCador** [PrestaShop/PrestaShop#35107] opened 2024-01-19 10:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a SQL error when there is at least a refunded product in a validated order:

> SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(((`dbname`.`od`.`product_quantity` - `dbname`.`od`.`product_quantity_refunded`) - `dbname`.`od`.`product_quantity_return`) - `dbname`.`od`.`product_quantity_reinjected`)'

And the hook does not show anything:
![image](https://github.com/PrestaShop/PrestaShop/assets/96910631/cea7ea5e-7075-4737-be02-69588bceb28e)

### Expected behavior

the hook shows data:
![image](https://github.com/PrestaShop/PrestaShop/assets/96910631/bfbce364-f9e3-4a16-b0b5-091b5c286ae3)

### Steps to reproduce

1. Create a validated order (payment by credit card)
2. go to BO and in the order
3. Create a refunding
4. go to dashboard
5. see there isn't any data in dashproducts hook

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

dashproducts

**Comment by ChillCode** [comment] 2024-01-19 12:55
Nice, hope all tests and everything passes:

Already reported, so if it's merged can be closed:

https://github.com/PrestaShop/PrestaShop/issues/28431

**Comment by florine2623** [comment] 2024-01-19 13:10
This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/28431 as said @ChillCode 

@NicolasCador you can follow the updates on that issue directly. I'll close this one to avoid clogging the backlog.

**Closed as completed by florine2623** 2024-01-19 13:10 UTC
Labels: Bug, Duplicate
