### ISSUE TITLE
Bug customer optin is empty

### ISSUE THREAD

**Issue by AdriCruz** [PrestaShop/PrestaShop#13396] opened 2019-04-13 21:41 UTC
Hello, when a client tries to register and does not click on the offer checkbox of the partners, the error that appears is attached. I do not want it to appear or be mandatory. I have looked for a way to repair it but I have not found it.

![imagen](https://user-images.githubusercontent.com/43041205/56085511-c35dc400-5e44-11e9-8a6c-0efceafeb7b6.png)

I have modified the customerformatter file to remove the obligation but when I deactivate the option, the same error still appears.
![imagen](https://user-images.githubusercontent.com/43041205/56085561-aa094780-5e45-11e9-9696-48d5d0b7d84d.png)

**Comment by khouloudbelguith** [comment] 2019-04-15 08:35
Hi @AdriCruz,

What is the exact version of PS did you used?
Did you use the default template by Prestashop?

Thanks!

**Comment by AdriCruz** [comment] 2019-04-15 08:48
Hello, the bug also remains if you activate the classic template. 

The exact version is 1.7.5.1

**Comment by khouloudbelguith** [comment] 2019-04-15 08:50
@AdriCruz, could you please try to clear cache from your project and your navigator and feedback.

**Comment by AdriCruz** [comment] 2019-04-15 09:04
I just did it and it remains the same, I attach all the errors that appear!

![Screenshot_2019-04-15](https://user-images.githubusercontent.com/43041205/56120345-39117f00-5f6e-11e9-98a8-54028b96c59d.png)

**Comment by khouloudbelguith** [comment] 2019-04-18 17:09
Hi @AdriCruz,

Could you please navigate to your BO => Customers => page => click on " Set required fields for this section" & provide me the exact list displayed & which option is checked?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-20 07:28
Hi @AdriCruz,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-20 07:28 UTC
Labels: FO, Duplicate, Customer

**Comment by khouloudbelguith** [comment] 2020-09-01 10:10
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/20801
