### ISSUE TITLE
Upgrading ps_contactinfo to latest 3.2.0 not working

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/PrestaShop#18080] opened 2020-03-10 13:54 UTC
#### Describe the bug

It seems to successfully upgrade (3.1.0 to 3.2.0) but the module section keeps showing the module is version 3.1.0
The problem is with PS 1.7.6.4 and on both PHP 7.1 and 7.2.
#### Expected behavior

Upgrade ps_contactinfo correctly

#### Steps to Reproduce

1. Go to Modules section
2. Select ps_contactinfo module (version 3.1.0)
2. Click on 'upgrade'
3. Wait for the process to finish
4. Refresh the page
5. the module is still 3.1.0
6. Note that the sources have the right 3.2.0 version

**Screenshots**

![ps_contactinfo_error](https://user-images.githubusercontent.com/731916/76319069-f0c62280-62de-11ea-9da2-1ef12be6bac1.gif)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1, 7.2

**Comment by khouloudbelguith** [comment] 2020-03-10 13:57
Hi @masiorama,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16066
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-10 13:57
Duplicate of #16066

**Closed as completed by khouloudbelguith** 2020-03-10 13:57 UTC
Labels: Duplicate
