### ISSUE TITLE
How to handle/display error messages for required fields

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20279] opened 2020-07-22 14:18 UTC
#### Describe the bug
As suggested by @matks in this [comment](https://github.com/PrestaShop/PrestaShop/pull/20263#issuecomment-662447464)

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to the BO => Addresses page
2. Create a new address
3. Set an invalid field Address 1 ( too long > 128 chars )
4. Click save
5. See error => unclear alert

 The reason why "address1" field has an unclear error message is that he has a specific status of "required field" that "alias" or "address2" do not have. Required fields can be configured by merchants which is why they have a specific behavior.

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/88187477-dd38aa00-cc36-11ea-8b9d-6597438890c5.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-07-22 14:24
@matks @PrestaShop/prestashop-product-team should we add to the 177 project?

**Comment by matks** [comment] 2020-07-22 15:07
To provide some context for this issue: the unclear message error happens when you fill an input with an invalid value AND this input is marked as "required field".

So if you define that "address2" field is **REQUIRED** too, same unclear alert appears when filling badly "address2" field.

There are multiple issues that need to be adressed, and the very first step is to decide what should be the right behavior.

### 1. How to manage "required fields" on a global scale and by country

You can define that a field such as "address2" is REQUIRED from the BO "Adresses" page ... but you can also define it as REQUIRED on a country BO page !

So what happens if you say
- address2 is not required globally
- address2 is mandatory for country USA

What should be done ? What should be displayed ?

And if I'm not wrong there might be even a 3rd way to define REQUIRED fields 🤔  (ping @zuk3975 )

### 2. Make error messages appear nicely

Error messages appear nicely just below the input when the constraint is applied at form level, like this => https://user-images.githubusercontent.com/16067358/88161348-2b868280-cc10-11ea-991c-0f1187dc1c81.png

However when we build the type we are not aware of the constraints configured. So we check the validity of the data at domain level, which explains why the error message appear at the top and not next to input.

### 3. Differences in constraints between required and not required fields

It seems that "required fields" have a max length of 128 while "not required fields" have a max length of 255

**Comment by matks** [comment] 2020-07-22 15:07
Because there is so much usecases to explore I think it's best to take the time to find a good solution 🤔  so I suggest studying this for 1.7.8

**Comment by zuk3975** [comment] 2020-07-22 15:21
> And if I'm not wrong there might be even a 3rd way to define REQUIRED fields thinking (ping @zuk3975 )

I don't recall any other way to achieve it using UI. Although I think there was some hook to add the required field in FO, which didn't add it in BO (or something like that)

**Comment by matks** [comment] 2020-07-22 15:41
> > And if I'm not wrong there might be even a 3rd way to define REQUIRED fields thinking (ping @zuk3975 )
> 
> I don't recall any other way to achieve it using UI. Although I think there was some hook to add the required field in FO, which didn't add it in BO (or something like that)

Yes, that was it. You can make a field required through a module by using this hook

**Comment by LouiseBonnard** [comment] 2020-07-23 11:21
Don't hesitate to ping @Junebyun in case a rewording is necessary. ;-)

**Comment by LouiseBonnard** [comment] 2020-10-14 10:29
It looks like this issue is more an improvement than a regression/bug - as the original ticket was qualified. I will edit the labels and add this ticket to a dedicated EPIC so that it can be studied later.

**Comment by florine2623** [comment] 2023-12-27 13:53
This issue is fixed, so I'm closing it.

<img width="787" alt="Screenshot 2023-12-27 at 14 52 07" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/35956780-5a81-4546-9c3a-9f52fa90c3f4">

**Closed as completed by florine2623** 2023-12-27 13:53 UTC
Labels: Waiting for PM, Feature, BO, Addresses, Fixed, migration, 1.7.7.x
