### ISSUE TITLE
Can't bind a product feature to a product after upgrading from v1.6.1.5 to v1.7.5.0 with the 1-click Upgrade module

### ISSUE THREAD

**Issue by d-roduit** [PrestaShop/PrestaShop#13867] opened 2019-05-20 09:26 UTC
**Describe the bug**
I added a product feature and its value in the Back-Office. Unfortunately, when I tried to bind the product feature to a product, the product feature hasn't been added to the database (I checked, and the `ps_feature_product`  table was empty), and thus never appeared neither as a feature on the product settings page, nor on the front-office product page.

Strange detail : after that, I tried to manually bind the product feature to the product by inserting their IDs in the `ps_feature_product` table, and the product feature finally appeared on the product settings page and on the front-office product page.
The problem is that once I tried again to bind another product feature to the product, but in the Back-Office this time, the `ps_feature_product` table was completely wiped (so the values I had manually entered got removed).

I did the exact same manipulation (adding a product feature and its value in the Back-Office, then binding the product feature to a newly created product) in the `v1.6.1.5` site (the same shop but before the upgrade), and all worked well.

I later installed the `v1.7.5 stable` and `v1.7.5.2` (the latest version to this day) to do the same manipulation and check, and both newly installed version worked well.

I suspect a problem with the upgrade, as it's the only thing that is substantially different between my site and the new ones.

**To Reproduce**
1. Upgrade a site from `v1.6.1.5` to `v1.7.5.0` using the 1-click upgrade module.
2. Log into the Back-Office of `v1.7.5.0`.
2. Go to  `Catalog` > `Attributes & Features` > `Features` .
3. Add a new feature and a new feature value (mine was : *'pf_dimension'* : *'6 x 15'*).
4. Go to `Catalog` >`Products`.
5. Click `New product`.
6. Change nothing, just put a title and a summary, and add the product feature created before with its value to the product.
7. Click on `Save`. (you will stay on the product settings page, so you should still see the feature on the product settings page as if it worked well).
8. Enable the product online if not the case.
9. Click on `Preview`
10. The product feature shouldn't be displayed on the Product Page.
11. Go back to the product settings page and refresh the page.
12. The product feature should have disappeared from the product settings page, meaning that the product feature has not been binded to the product.

**Screenshots**
No screenshot available, as there's no error displayed. 

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0.29 with Wamp

**Comment by khouloudbelguith** [comment] 2019-05-20 09:29
Hi @d-roduit,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-20 11:11
Hi @d-roduit,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-20 11:11 UTC
Labels: Bug, BO, Features, Autoupgrade, No change required, 1.7.5.0
