### ISSUE TITLE
FO - javascript issues on cart after upgrade from 1.7.6.5 to 1.7.8.7

### ISSUE THREAD

**Issue by Juiliard** [PrestaShop/PrestaShop#29466] opened 2022-08-29 11:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After upgrade from PS 1.7.6.5 to 1.7.8.7 following issues spotted:
1. cart Qty not increased / decreased
2.  button  Delete from cart does nothing
3. when select next product variant / combination -> product picture is not changing to that variation's default pic (the first one for this combination) but stays the default one for the whole product. As a result a wrong picture (from first variant) is added to the cart. 

The following warnings in console:
<img width="950" alt="Screenshot 2022-08-29 at 13 00 58" src="https://user-images.githubusercontent.com/58143423/187186947-4e51045b-1a33-48e2-9bab-a0e845ce66a9.png">

This appears in console when click on Increase items in cart:
<img width="626" alt="Screenshot 2022-08-29 at 13 21 22" src="https://user-images.githubusercontent.com/58143423/187190150-e29c3a69-f30e-416e-8de5-9df999d06716.png">

Solution of problem 1 and 2 I found here - by replacing core.js attached to that forum: (assumably from PS version 1.7.7.8) https://www.prestashop.com/forums/topic/1055219-not-working-shopping-cart-after-upgrade-1780/#comment-3406341 

Problem 3. still not solved. 
Ideas ? solutions?

### Steps to reproduce

1. go to BO > upgrade from 1.7.6.5 to 1.7.8.7
2. remove maintenance mode
3. go to FO > open product with combination - > try to change variant / combination 
4. add second variant / combination of that product to cart 
5. try to increase / decrease qty in cart
6. try to delete product from the cart 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by sLorenzini** [comment] 2022-08-29 14:35
hello @Juiliard,

Thanks for your report.

I've upgraded my shop from 1.7.6.5 to 1.7.8.7.
I couldn't reproduce your console errors. I can add, increase / decrease quantity, remove product from cart. Here's a screenrecord:

https://user-images.githubusercontent.com/2854834/187226349-4e04d57e-7b3b-42cf-a7c6-f5b43c889a5c.mp4

And a screenshot of my logs:

![Capture d’écran 2022-08-29 à 16 28 54](https://user-images.githubusercontent.com/2854834/187226402-a366f06c-6168-402a-82af-8f2c79acb922.png)

Did you try to clear the cache? force compilation of the files? active/deactive CCC?

Waiting for your feedback

Thank you

**Comment by Juiliard** [comment] 2022-08-29 15:02
> 

Hi [sLorenzini](https://github.com/sLorenzini), thanks for your checkup and reply.
I guess it is not a bug then. 
And it looks like I have to dig somewhere else for the reason of this issue with this error in core.js
Any ideas would be appreciated.

I did: deactivated CCC, clean Cache, deleted Cache - no help.
Also I tried to install a new Theme - still the same issue: cannot select other pictures from combinations.

**Comment by Hlavtox** [comment] 2022-08-30 12:11
Did you upgrade your theme when upgrading the shop? If not, I suggest comparing the two ZIPs and applying changes that occured in classic theme between the versions. ;-)

**Comment by Juiliard** [comment] 2022-08-30 15:09
That's a really good idea @Hlavtox, thanks !

Here are settings which I used during Upgrade, so yes I kept my modified classic theme:
<img width="623" alt="Screenshot 2022-07-28 at 13 07 17" src="https://user-images.githubusercontent.com/58143423/187472641-d19f10ef-b0da-4c53-aa16-d61bab9ffb9c.png">

Would you also recommend the best tool for Mac users to do "comparing the two ZIPs"?

**Comment by hibatallahAouadni** [comment] 2022-09-05 09:08
Hello @Juiliard 

Closing the issue as it's not a bug and you seem you found the source of your issue.
Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-09-05 09:08 UTC
Labels: Bug, FO, Shopping carts FO, Invalid, 1.7.8.7

**Comment by tameroski** [comment] 2023-02-23 15:13
For the record and because i spent quite some time on this issue myself : the updateCart event in core.js is now expected the full response as a second parameter, so in most of the case (i guess), juste replace : 

```
prestashop.emit('updateCart', {
  reason: dataset
});
```

with : 

```
prestashop.emit('updateCart', {
  reason: dataset,
  resp
});
```

in your theme's handleCartAction function (cart.js in my case)

**Comment by masiorama** [comment] 2024-02-13 18:15
@tameroski you saved me, thanks mate.
