### ISSUE TITLE
Problem/Bug: Prestashop 1.7.4.2 and discount code without VAT

### ISSUE THREAD

**Issue by Suisso** [PrestaShop/PrestaShop#11022] opened 2018-10-16 08:20 UTC
Hello,

I have a problem with Prestashop 1.7.4.2 and discount code.

Our store is destined to B2B, meaning the prices are all without VAT.

Our store is mainly for people who live in Switzerland (non-European).

When we apply the promotion code he applies the discount with rates, and we want the discount always be without taxes, ie without VAT.

How do you do this?

I've tried debugging, but I can not find the class or file that defines this.

P.S: Attached I send you an example with a discount of 10%

Can you help me, please?

Infos: 
- Prestashop version: 1.7.4.2
- Theme: ZOneTheme version: 2.2.8

Thanks in advance,
Best Regards.

![44106494_10156960165388714_2093121722948517888_n 2](https://user-images.githubusercontent.com/383590/47002175-8d0ce980-d12c-11e8-98c6-4ace50c2949c.jpg)

**Comment by khouloudbelguith** [comment] 2018-10-16 08:43
Hi @Suisso,

We are aware of the issue( Discount problems for customers without VAT), it is added to our debug roadmap.
Your ticket is a duplicate of #9856
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-16 08:43
Duplicate of #9856

**Closed as completed by khouloudbelguith** 2018-10-16 08:43 UTC
Labels: Duplicate
