### ISSUE TITLE
Lack of full high DPI support when regenerating images in admin panel

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#19801] opened 2020-06-16 15:01 UTC
#### Describe the bug

When setting the option "Generate high resolution images" and generating some image type with "Erase previous images" set to NO, the high resolution images are not generated.

#### Expected behavior

Prestashop should generate missing images without a need to delete all of them.

#### Steps to Reproduce

1. Have a product with a set of images already generated (without high res images)
2. Go to image settings and set "Generate high resolution images" to YES
3. Perform thumbnail regeneration but with "Erase previous images" set to NO
4. Verify that the high res thumbnails are not generated

#### Additional information

The error is in the AdminImagesController, when generating images it only checks if the low res images exist, if they exist it does not do any regenerating even if the high res images are not there.

* PrestaShop version: 1.7.6.5 and probably also 1.7.7

**Comment by PierreRambaud** [comment] 2020-06-22 08:31
Hi and thanks for your report.

You're right, there is a missing check :)
If you know exactly what to do, feel free to open a pull request :+1: 

Kind regards

**Comment by Prestaworks** [comment] 2020-08-04 08:06
was fixed here I belive https://github.com/PrestaShop/PrestaShop/pull/16097
But it was only about a year ago so it maybe have not found itself into the release versions yet :)

**Comment by marionf** [comment] 2020-08-04 09:01
@khouloudbelguith Could you check if this issue is fixed on 1.7.7.x ?

**Comment by khouloudbelguith** [comment] 2020-08-04 10:39
Hi @marionf,

I did not manage to reproduce the issue with 1.7.7.x branch.
I attached a screen record
https://drive.google.com/file/d/1NJkMRRwtMlUeqoX0u8C-VVtJPKlJLqAz/view?usp=sharing
I close the issue since it is fixed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-04 10:39 UTC
Labels: Bug, Minor, BO, Image, Fixed, Good first issue, 1.7.6.5

**Comment by marionf** [comment] 2020-08-04 12:28
Great to hear, thank you @khouloudbelguith
