### ISSUE TITLE
Updating a product combination location via API no longer is possible

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/PrestaShop#29779] opened 2022-09-27 14:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Updating a product combination's location used to be possible by PUTing a product combination object with the 

`<location></location>` field populated to the API via

`https://www.example.com/api/combinations/ID` 

Currently you can send an update to this path which returns an `200 OK` response. However when you GET this combination path again the field is no longer populated. The back office UI also does not show the location.

On investigation it seems PUTing an object to the path above does update the `location` field in the `ps_product_attribute` table however it does not update the `location` field in the `ps_stock_available` table. 

When you use the back office UI to update a product combination's location, Prestashop updates both the  `ps_product_attribute` & `ps_stock_available` tables which seems to be the correct behaviour.

### Expected behavior

Updating a combination object via the API should also update the `ps_stock_available` table with a product location. This way it will show to API requests and via the Admin area.

Alternately GETing a product combination via the API should at least get the `location` field from the `ps_product_attribute`

Note: I have not tried it the other way by setting the `https://www.example.com/api/stock_availables/ID` object and seeing the results. It would be worth checking how this affects the database.

### Steps to reproduce

1. Update a product combination using the API. Set the `<location></location>` field
2. Get this combination - no location will be shown
3. Check the  back office UI - no location will be shown
4. Check the `ps_product_attribute` table, the updated location **will** be shown
5. Check the `ps_stock_available` table, the updated location will **not** ben shown

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by HanaRebaiQA** [comment] 2022-09-28 14:31
Hello @haveyougotanypets 

Thanks for your report.
Is this issue [#29653](https://github.com/PrestaShop/PrestaShop/issues/29653) similar to this yours ?

Thank You!

**Comment by haveyougotanypets** [comment] 2022-09-28 14:38
HI @HanaRebaiQA 

No this issue not the same. This issue relates to the location field belonging to a combination. The feature request you have linked to is related updating a product image

**Comment by hibatallahAouadni** [comment] 2022-10-05 16:23
Hello @haveyougotanypets 

Thanks for your patience :pray: 
Unfortunately I didn't manage to reproduce the issue with the provided infos :disappointed: 
Could you please provide a screen record :pray: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-10-25 10:45
Hello @haveyougotanypets 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-10-25 10:45 UTC
Labels: Bug, WS, Webservice, Combinations, Invalid, 1.7.8.7

**Comment by haveyougotanypets** [comment] 2024-01-11 10:35
@hibatallahAouadni 

Could you re-look / reopen this ticket. 

See below, here is an example of a request for a combination using the API from an older version on Prestashop. If you try this same request on a current version. You will see the <location> element is missing. 

Also if you do an update and add the location element, the location is not updated.

![old-example](https://github.com/PrestaShop/PrestaShop/assets/1625635/2daabbe8-ab5a-4a93-ba96-6c52077d08a4)

**Comment by hibatallahAouadni** [comment] 2024-01-11 10:45
Hello @haveyougotanypets 

It's been over 1 year since your last reply. So, it will be better if you create a new issue. 

Thanks for your understanding!

**Comment by haveyougotanypets** [comment] 2024-01-11 11:01
Hi @hibatallahAouadni 

Can we not just reopen and assign. Otherwise i am just going to copy and paste all the info word for word to a new ticket
