### ISSUE TITLE
1.7.5.1 error shipping cost calculation

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#13041] opened 2019-03-25 12:25 UTC
For Product A, only shipping method X is available. When only product A is in the shopping card, shipping costs are shown correct,

For Product B shipping only methode Y is available.   When only product B is in the shopping card, shipping costs are shown correct,

With both, product A and product B are in the card, shipping cost is not calculated correct = €8,90, should be €4,95) . (see attachement) 

![2019-03-25 13_15_13-Winkelwagen - Opera](https://user-images.githubusercontent.com/11147327/54919336-c843ed80-4f00-11e9-8f61-bb1609981ecb.png)

When for product A shipping method X and shipping method Y is made available then shipping cost is calculated correct.

![2019-03-25 13_14_17-Winkelwagen - Opera](https://user-images.githubusercontent.com/11147327/54919389-f6c1c880-4f00-11e9-815c-b49696fa2365.png)

**Comment by khouloudbelguith** [comment] 2019-03-25 13:18
Hi @Peter4661,

We are aware of this issue.
Your ticket is a duplicate of #9594
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-03-25 13:18 UTC
Labels: Duplicate

**Comment by Peter4661** [comment] 2019-03-26 14:33
Hi  khouloudbelguith ,

Thank you for your answer. I see this item is open since August 2018 with minor priority. 

I would like to give my opinion about priority to get it moved up on the priority list.

No doubt you are aware of, customers don't like to see shipping cost.  In the Netherlands, large shops which are sending out hunderds of parcels every day have the advantage of negotiating for better shipping conditions, offer shipping for free with slightly higher total price.

Our averange value of shopping cart is approx €35. The calculation error of €3,95, adds +10% on top of our regular shipping cost. 

Example:
Shipping mode AA: Product A+B delivered to mailbox, no tracking,  €2,99
Shipping mode AB: Product A+B delivered to mailbox, with tracking, no signature upon delivery €3,99
Shipping mode AC: Product A +B delivery as parcel, no signature upon delivery, €6,95
Shipping mode AD: Product A+B  delivery as parcel, signature upon delivery, €7,95

Because of the shipping cost calculation error Prestashop adds €3,95 which puts us out of competition.

Wish Prestashop team would move up the this item on the piority list.

Thank you.
