### ISSUE TITLE
The new order and/or new customer alert under the bell sign wont close

### ISSUE THREAD

**Issue by qualityangel** [PrestaShop/PrestaShop#20169] opened 2020-07-14 09:28 UTC
#### Describe the bug

When a customer has made an order or there is a new customer registration, the notifications on top right of the screen keeps displaying even when you already clicked it.

#### Expected behavior

When opening the notifications bell, then when you close it, the notifications normally goes away.

#### Steps to Reproduce

Make an fictive order, then you see the new order notification als normal.

#### Additional information

* PrestaShop version: 1.7.7.0beta
* PHP version: 7.2.31

**Comment by khouloudbelguith** [comment] 2020-07-14 10:45
Hi @qualityangel,

Thanks for your report.
I manage to reproduce the issue with PS1.7.7.0beta1, 1.7.7.x branch.
In the PS1.7.6.7 is not well working well as reported here: https://github.com/PrestaShop/PrestaShop/issues/9550
I will add this issue to our bug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Ping @PrestaShop/prestashop-product-team what do you think, this issue should be fixed in the next release 1.7.7.0?
_In the PS1.7.7:_ The notifications on the top right of the screen keeps displaying even when you already clicked it.
_In the PS1.7.6:_  If I select the notification bell. The new orders and new messages have all been cleared, even though they have not been read

Thanks!

**Comment by colinegin** [comment] 2020-07-15 08:43
Hello @khouloudbelguith ,

It depends if we intended to fix the 176 issue for 177. Is there any PR related to it ? 
If yes, then I'd suggest to fix this bug for 177 as it means we haven't fixed it correctly.
If no, then we should not fix it for 177.

Thanks

**Comment by matks** [comment] 2020-07-16 08:07
> Hello @khouloudbelguith ,
> 
> It depends if we intended to fix the 176 issue for 177. Is there any PR related to it ?
> If yes, then I'd suggest to fix this bug for 177 as it means we haven't fixed it correctly.
> If no, then we should not fix it for 177.
> 
> Thanks

There is a PR https://github.com/PrestaShop/PrestaShop/pull/20188 that aims for `develop` (178).
We can review/QA it and when it is merged we can backport it for 177

**Closed as completed** 2020-09-03 13:56 UTC
Labels: Bug, Minor, BO, Fixed, PR available, 1.7.7.x
