### ISSUE TITLE
Wrong checking requirements

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/PrestaShop#21047] opened 2020-09-17 19:10 UTC
#### Describe the bug

Build in checking requirements compatibility don't prevent install Prestashop on incompatibility environment ([server configuration](https://github.com/PrestaShop/PrestaShop/issues/20999#issuecomment-693237508)). That tool check PHP extensions but don't check PHP version o.0.

#### Expected behavior

Prevent to install Prestashop on incompatibility enviroment.

#### Steps to Reproduce

1. Install Prestashop 1.7.6.x with PHP7.3

#### Additional information

* PrestaShop version: 1.7.6.x
* PHP version: PHP7.3

**Comment by matks** [comment] 2020-09-17 22:33
This might already be fixed for 1.7.7 according to https://github.com/PrestaShop/PrestaShop/issues/20842 🤔

**Comment by LocalHeroPro** [comment] 2020-09-21 18:39
It wasn't 1.7.6.x. Different version.

**Comment by khouloudbelguith** [comment] 2020-09-28 11:59
Hi @LocalHeroPro,

Did you tried with the `1770beta2` version, is it the issue reproduced?
We have already a fix in the PS1770
https://github.com/PrestaShop/PrestaShop/pull/16506

Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-10-19 09:21
Hi @LocalHeroPro,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-19 09:21 UTC
Labels: Bug, IN, No change required
