### ISSUE TITLE
Enable/Disable button doesn't work properly in slides list in ps_imageslider

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#35703] opened 2024-03-20 18:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Enable/Disable button doesn't work properly in slides list in ps_imageslider.
Example you click to disable first slide:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/ad404d9f-2b86-4556-8a9a-c6d837f2a088)
After the the button shows what the slide is disabled:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/73ca4e39-98c1-46e6-aa22-1bc91c9df728)
Then you click to disable the second slide:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/7f731fe7-ef93-4647-b8ce-2cbee4aaf1dc)
Result: 
The second slide's button shows what the second slide disabled **BUT the first slide is enabled now. Although the first slide was disabled before:**
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/5ff2d172-8112-437f-bc79-f7dc8f0d9408)

Also the button doesn't actually change the status of the slide. 
Example, click to disable first slide:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/ad404d9f-2b86-4556-8a9a-c6d837f2a088)
After the the button shows what the slide is disabled:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/73ca4e39-98c1-46e6-aa22-1bc91c9df728)
Then go to first slide's settings:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/b7981335-ab37-4068-9cbe-6015628a1312)
And you see what the first slide is not disabled actually:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/19a49e44-8608-4584-9ff6-2452ed51c7c7)
It turns out that the “on/off” button doesn’t actually turn off the slide at all, it’s just decoration.

Also i recorded the video with bugs:
https://github.com/PrestaShop/PrestaShop/assets/22581200/47c47097-42a1-488a-869e-7408c94c55a8

### Expected behavior

when you click to "enable/disable" slide button in slides list the slide will be disabled in slide's settings too:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/f3b12dad-a450-4add-98eb-f78c5249e18e)
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/c2f9d591-46f5-4f0c-ac2f-4fe03234f56d)

Also if you disable first slide and then disable second slide the first slide must not be enabled.

### Steps to reproduce

1. Go to the "Image slider" settings.
2. Try to disable first slide, then disable second slide, then disable third slide.
3. Also go to the slide settings after disable to see wrong stutus.

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

 8.1.25

### If your bug is related to a module, specify its name and its version

ps_imageslider v3.1.4

**Comment by florine2623** [comment] 2024-03-21 09:53
Hello @web-burn ,

I can't reproduce your issue with version 3.1.4.

https://github.com/PrestaShop/PrestaShop/assets/16019289/07c905f2-6064-4728-b8fd-3cccb32156e1

Am I missing something ?

**Comment by web-burn** [comment] 2024-03-21 10:01
Hello @florine2623, the Ps_edition_basic is disabled in your shop:
![image](https://github.com/PrestaShop/PrestaShop/assets/22581200/d0471b7b-6337-44a3-a69c-1a46f88ef9c5)
I have tested when the Ps_edition_basic is disable then the slider settings works right. 
When Ps_edition_basic is enabled the slider settings works not good.

**Comment by florine2623** [comment] 2024-03-21 12:52
@web-burn 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project Open Source.

You can ask directly on the Edition support page for that issue in particular.

I'm closing the issue as it is not an issue reproducible on PS Open Source.

Thank you

**Closed as completed by florine2623** 2024-03-21 12:52 UTC
Labels: Bug, BO, Imageslider, Module, 8.1.x

**Comment by web-burn** [comment] 2024-03-21 13:03
@florine2623  but the module Ps_edition_basic is installed in the PrestaShop 8.1.5 by default, after prestashop installation. Or not?

**Comment by web-burn** [comment] 2024-03-21 18:42
@florine2623  What different beetween https://prestashop.com/prestashop-offers/classic/ and https://www.prestashop-project.org/? 
I don't understand. What is official version of the PrestaShop? Where can i write about prestashop_edition_basic_version?

**Comment by matks** [comment] 2024-03-21 22:32
@web-burn > Prestashop 8.1.4 basic edition downloaded from here https://prestashop.com/prestashop-edition-basic/ is different from the open source project PrestaShop that you can download on GitHub 😉 . It's a specific distribution. Just like Ubuntu or Debian both are distributions of Linux.

https://prestashop-project.org/ -> the PrestaShop open source project
https://prestashop.com/ -> the PrestaShop company

> Where can i write about prestashop_edition_basic_version?

You can contact PS company support team or browse the Help center https://help-center.prestashop.com/en

**Comment by web-burn** [comment] 2024-03-21 22:43
@matks  thanks for your explanations. Now i understand. While I was looking for information in google on this issue, I noticed that this module "Ps_edition_basic" from the PrestaShop company brings a lot of problems. I disabled the module.
