### ISSUE TITLE
FeatureValue::addFeatureValueImport create new item instead of finding the good one.

### ISSUE THREAD

**Issue by voxTeam** [PrestaShop/PrestaShop#19773] opened 2020-06-16 07:45 UTC
#### Describe the bug

In a specific development (like handmade import) if you want find or create a feature value with FeatureValue::addFeatureValueImport a new feature value is always created.

#### Expected behavior

If the feature value (not custom and in current language) exists, it should be found and not created

#### Steps to Reproduce

Use :
    FeatureValue::addFeatureValueImport($id_feature, $value); 
or
    FeatureValue::addFeatureValueImport($id_feature, $value, $id_product);

in a loop of items with the same feature value. In admin panel you'll see multiple values with same name.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.0.33

**Comment by florine2623** [comment] 2020-06-17 13:24
Hi @voxTeam ,
Could you share the steps to reproduce your issue ?
I will try it on my end !
Thanks!

**Comment by prestascott** [comment] 2020-07-15 09:06
Hello @voxTeam,

Since we had no news from you for more than 20 days, I'll close this ticket not to clutter up the backlog, but note that you can always create a new one if further information pops up.

Thank you!

**Closed as completed** 2020-07-15 09:10 UTC
Labels: Import / Export, No change required, 1.7.6.3
