### ISSUE TITLE
Dashtrends 

### ISSUE THREAD

**Issue by flistefliste** [PrestaShop/PrestaShop#15727] opened 2019-09-27 09:16 UTC
**Dashtrends module shows bad _Sales_ amount after upgrading from 1.7.4 to 1.7.6.1**
Before upgrade : _Sales_ tab amount was showing order total paid tax excl. (including shipping and coupons)
After upgrade : Sales tab show only total products tax excl.

**To Reproduce**
1. Update from 1.7.4 to 1.7.6.1  using Autoupgrade 4.9.0
2. Go to dashboard and compare _Sales_ amount to real orders amount (including shipping cost and cart rules if exist)
3. See error

**Screenshots**
In this example we have juste one order.
Tax is 20% French TVA (price tax excl. = price tax incl. / 1.2)

Dashboard:
![Capture-d’écran-2019-09-27-à-10 47 35](https://user-images.githubusercontent.com/6929108/65757243-0a9bf080-e117-11e9-936f-4e73e9248337.png)

Order detail:
![Capture-d’écran-2019-09-27-à-10 47 57](https://user-images.githubusercontent.com/6929108/65757803-2784f380-e118-11e9-89cf-2c3bf7310415.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.19-0ubuntu0.18.04.2

**Comment by khouloudbelguith** [comment] 2019-09-30 10:11
Hi @flistefliste,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15114
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-30 10:11
Duplicate of #15114

**Closed as completed by khouloudbelguith** 2019-09-30 10:11 UTC
Labels: Duplicate, Dashtrends
