### ISSUE TITLE
BO - Error while Upgrading some modules 

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#34022] opened 2023-09-21 15:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you click on Upgrade on a module in BO you get an error even all the permissions to read/write are verified!

See attached screenschot:

**- On Develop**

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/032fe8c3-4dd5-4474-91ae-182b866dc8f4)

**- On 8.1.x**

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/69f759d9-d35c-4949-be4c-405a1637df0a)

Only the module Autoupgrade was upgraded successfully :heavy_check_mark: 

The problem concern some modules that I tried to upgrade:

1. Product Comments

> 5.0.2 => 6.0.2 :white_check_mark:
> 5.0.3 => 6.0.0 :x:
> 5.0.3 => 6.0.2 :x:
> 5.0.2 => 6.0.0 => 6.0.3 :white_check_mark:
> 5.0.2 => 5.0.3 => 6.0.0 => 6.0.3 :white_check_mark:

2. Mail alert

> 2.4.0 -> 2.4.2 :white_check_mark:
> 2.4.1 -> 2.4.2 :x:

3. Link list

> 6.0.2 => 6.0.4 :white_check_mark:
> 6.0.3 => 6.0.4 :x:

4. Faceted search

> > 3.13.0 => 3.13.2 :white_check_mark:
> > 3.13.1 => 3.13.2 :x:
> 5.0.2 => 5.0.3 => 6.0.3 :white_check_mark:

### Expected behavior

All modules should be upgraded successfully from BO

### Steps to reproduce

1. Go to Modules > Module Manager
2. Click on Updates tab
3. Click on Upgrade button
4. See Error

### PrestaShop version(s) where the bug happened

8.1.x & develop

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment] 2023-09-21 16:05
PS: when I uninstall the version of productcomments 5.0.3 (installed by default), then download the same version 5.0.3 from github, install it, then upgrade it to 6.0.2 :heavy_check_mark: it's upgraded without any errors

**Comment by leemyongpakvn** [comment] 2023-09-23 04:12
Both productcomments and ps_linklist are at  "^6" after @jolelievre [Update product comments in composer.lock](https://github.com/PrestaShop/PrestaShop/commit/4e4a0e0fdc48d90f269e30c90638f500c0846179) for 8.1.x so we won't see problem with Upgrade from v5 to v6 with these 2 modules in **8.1.x** any more.
By the way, I think the problem comes from Upgrade module or some Core changes, not other modules. You can try with a fresh installation of 8.1.x, do upgrade other modules without Autoupgrade upgrade **prior**.

**Comment by florine2623** [comment] 2024-01-19 13:28
Hello @aniszr ,

I can't reproduce your issue anymore. It seems fixed.

On `8.1.x`, all modules were successfully upgraded.
- Contact form : v4.4.1 → v4.4.2
- Image slider : v3.1.3 → v3.1.4
- Mail alerts : v2.4.2 → v3.0.0

https://github.com/PrestaShop/PrestaShop/assets/16019289/0d1b0df2-dad4-4ee0-a689-9d07d59ea4e1

On `develop`, there were on errors, but eventually all module were successfully upgraded.
- Main menu v2.3.2 → v2.3.4
- Mail alerts : v2.4.2 → v3.0.0
- Newsletter Subscription v2.7.1 → v2.8.1
- Google sitemap v4.3.1 → v4.4.0

https://github.com/PrestaShop/PrestaShop/assets/16019289/efcb163a-00f8-44b6-b10a-163940eed76a

I'm closing the issue to avoid clogging the backlog.
Thanks!

**Closed as completed by florine2623** 2024-01-19 13:28 UTC
Labels: Bug, Minor, BO, Needs Specs, Faceted search, Module manager, Productcomments, Linklist, ps_emailalerts, Verified, Module, 8.1.x
