### ISSUE TITLE
Prestashop Backoffice Error

### ISSUE THREAD

**Issue by maviteknoloji** [PrestaShop/PrestaShop#12757] opened 2019-03-01 05:52 UTC
Admin > Products  > Duplucater 

Error

www.site.com/admin/index.php/sell/catalog/products/unit/duplicate/155?_token=_5TKAKtfZRwSiVel2_VLHNVCW0Fbx4igU7K5k3uL2-I

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment] 2019-03-01 07:43
Hi @maviteknoloji,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by maviteknoloji** [comment] 2019-03-01 08:24
PRESTASHOP 7.5.0

/home/vtwparan/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php dosyasında 101 satırında Notice
[8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php70) failed: Permission denied (13)


(1/1) ContextErrorExceptionUyarı: SessionHandler :: gc (): ps_files_cleanup_dir: opendir (/ var / cpanel / php / sessions / ea-php70) başarısız oldu: İzin reddedildi (13)
--
içinde StrictSessionHandler.php hattı 101
en StrictSessionHandler -> gc ( 1440 )içinde SessionHandlerProxy.php hattı 83
En SessionHandlerProxy -> gc ( 1440 )
en session_start ()İçinde NativeSessionStorage.php hattı 145
En NativeSessionStorage -> başlangıç ()İçinde NativeSessionStorage.php hattı 295
En NativeSessionStorage -> getBag ( 'nitelikleri' )içinde Session.php hattı 256
En Oturumu -> getBag ( 'nitelikleri' )içinde Session.php hattı 278
En Oturumu -> getAttributeBag ()İçinde Session.php hat 73
En Oturumu -> olsun ( '_security_main' )içinde ContextListener.php hattı 89
en ContextListener -> kolu ( nesne ( GetResponseEvent ) )içinde WrappedListener.php hat 46
en WrappedListener -> kolu ( nesne ( GetResponseEvent ) )içinde TraceableFirewallListener.php hattı 35
en TraceableFirewallListener -> handleRequest ( nesne ( GetResponseEvent ), nesne ( Jeneratör ) )içinde Firewall.php hattı 84
en Firewall -> onKernelRequest ( nesne ( GetResponseEvent ) )içinde FirewallListener.php hat 48
en FirewallListener > - onKernelRequest ( nesne ( GetResponseEvent ) 'kernel.request', nesne ( TraceableEventDispatcher ) )içinde WrappedListener.php hattı 111
en WrappedListener -> __invoke ( nesne ( GetResponseEvent ) 'kernel.request', nesne ( ContainerAwareEventDispatcher ) )içinde EventDispatcher.php hattı 212
en EventDispatcher'a -> doDispatch ( dizi ( nesne ( WrappedListener ), nesne ( WrappedListener ), nesne ( WrappedListener ), nesne ( WrappedListener ),nesne ( WrappedListener ), nesne ( WrappedListener ), nesne ( WrappedListener ), nesne ( WrappedListener ), nesne ( SarılmışListener ), nesne(WrappedListener ), nesne ( WrappedListener ), nesne ( WrappedListener ), nesne ( WrappedListener ), nesne ( WrappedListener )), 'kernel.request', nesne (GetResponseEvent ) )içinde EventDispatcher.php hat 44
en EventDispatcher'a -> gönderme ( 'kernel.request', nesne ( GetResponseEvent ) )içinde TraceableEventDispatcher.php hattı 139
en TraceableEventDispatcher -> gönderme ( 'kernel.request', nesne ( GetResponseEvent ) )içinde HttpKernel.php hattı 127
en HttpKernel -> handleRaw ( nesne ( ayrıntılı ), 1 )içinde HttpKernel.php hattı 68
en HttpKernel -> kolu ( nesne ( ayrıntılı ), 1, sahte )içinde Kernel.php hattı 200
de çekirdek > - sap ( nesne ( ayrıntılı ), 1, sahte )içinde İndex.php hat 88

**Comment by khouloudbelguith** [comment] 2019-03-01 08:29
@maviteknoloji, 
You have a permission issue on your server [Permission denied].
Thanks to check your issue with your host & feedback.

**Comment by khouloudbelguith** [comment] 2019-04-01 08:25
Hi @maviteknoloji, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-01 08:25 UTC
Labels: Bug, BO, No change required

**Comment by Varindien** [comment] 2019-07-12 08:59
Hi @maviteknoloji ,

i see that issue is closed  but just to notify this is a server issue configuration. Ask your provider to modify path of "session.save_path" in WHM. Prestashop has no right here for security reason.

most of time it will be modified with "/tmp" folder

regards

**Comment by audas** [comment] 2020-06-21 02:31
This is a serious and reoccurring issue which is not being dealt with correctly.

Just advice users under cpanel to edit "MultiPHP INI Editor" and set "session.save_path" to "/tmp"

You should also advise them to correct their memory issues here as well - these are TWO critical problems with PrestaShop installations on standard servers which prevent thousands of users from proceeding.

The help and response from PrestaShop is poor on this.
