### ISSUE TITLE
No access to module

### ISSUE THREAD

**Issue by verybecoming** [PrestaShop/PrestaShop#11543] opened 2018-11-28 15:27 UTC
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by khouloudbelguith** [comment] 2018-11-28 15:29
Hi @verybecoming,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by verybecoming** [comment] 2018-11-28 15:33
Host is ionos
prestashop 1.7.4.4
Server information Linux #1 SMP Debian 3.16.56-1~ui80+1 (2018-05-15) x86_64

Server software version: Apache

PHP version: 7.2.12

Memory limit: -1

Max execution time: 50000

Upload Max File size: 64M

Nom d'hôte
db762198941.hosting-data.io

Port
3306
Nom d'utilisateur
dbo762198941
Type et version
MySQL 5.5
![image](https://user-images.githubusercontent.com/45430491/49162521-56c9a900-f32b-11e8-9a94-8199c3b37115.png)

**Comment by khouloudbelguith** [comment] 2018-11-28 15:44
@verybecoming, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-28 11:33
Hi @verybecoming,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-28 11:33 UTC
Labels: Bug, Modules, No change required
