### ISSUE TITLE
Huge allowed memory size exhausted

### ISSUE THREAD

**Issue by johstrom** [PrestaShop/PrestaShop#13564] opened 2019-04-25 12:21 UTC
**Describe the bug**
Getting error 500 with this details when trying to open a product detailed page in backoffice:

Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes)

It appeared that the application required more memory in order to display the product details page. I have increased the memory limit to 1024MB, however, the same error was presented as well (this time with the increased value of the memory):

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)

It seems to have occured after some big imports of categories and products. 

**To Reproduce**
1. Import products and categories. I have 110 categories and +40.000 products.
2. Click on Catalog / Products. And choose a product to see the detailed page to alter price, specifications etc.
3. Error 500 occurs with mentioned memory exhaust report.

**Screenshots**
See this screen share video: https://hstrom.mangoapps.com/sf/MTc0ODMyXzYzOTIzODA

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-04-25 13:14
Hi @johstrom,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-04-25 13:14 UTC
Labels: Duplicate
