### ISSUE TITLE
Sort of the mails in the translation page

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#22448] opened 2020-12-16 12:21 UTC
#### Describe the bug

Since version 1.7.5.0, the mails are no more ordered by ASCENDING NAME in the translation page.
A "SCANDIR_SORT_NONE" parameter has been added to the scandir function in getMailFiles() from AdminTranslationsController.php.
Is there any good reason ?

I'm offering a module compatible with all version since 1.5 to 1.7, so I have to include the mails in all version because the display has changed. I'm naming my mail with a prefix "1.5-...", "1.6-....", or "1.7-....". Until version 1.7.5.0, it was easy to find the one to translate, they were ordered by name, so all grouped by prefix.
Since 1.7.5.0, they are all mixed.

#### Expected behavior

Have the list of the mails ordered by ascending name

#### Steps to Reproduce

Enter the translation page in admin, select "mails" + body + your theme + your language.
Check the order of the list, either for the core emails or a module emails.

#### Additional information

* PrestaShop version: All since 1.7.5.0

**Comment by hibatallahAouadni** [comment] 2020-12-16 13:25
Hello @Prestaplugins 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22043. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-16 13:25
Duplicate of #22043

**Closed as completed by hibatallahAouadni** 2020-12-16 13:25 UTC
Labels: Duplicate
