### ISSUE TITLE
Product Sort Problem 

### ISSUE THREAD

**Issue by peppoweb** [PrestaShop/PrestaShop#22160] opened 2020-11-30 14:35 UTC
#### Describe the bug

hello, we encounter a problem on the ordering of products within categories.
Prestashop version 1.7.6.5

#### Expected behavior

I expect that clicking on "Salva e Riordina" the order will be maintained.

**Screenshots**
You can see the error in this screen capture movie
https://drive.google.com/file/d/1z2qW6qtDEFv2SrGFsZE7hcdSLUIVHl9l/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2020-11-30 15:20
Hello @peppoweb 

I didn't manage to reproduce your issue with PS1.7.6.5, PS1.7.6.9 and PS1.7.7.0-rc.1, see the attached screen record below:

https://drive.google.com/file/d/188xUboVUAJg6lptqf4KsnOaAcUNlch75/view

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-21 10:48
Hello @peppoweb,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-21 10:48 UTC
Labels: Bug, BO, No change required, 1.7.6.5
