### ISSUE TITLE
Problem with Tax Round

### ISSUE THREAD

**Issue by sitolab** [PrestaShop/PrestaShop#15361] opened 2019-09-02 13:01 UTC
Hi Guys,
there are problems with tax round (the same error with PRESTASHOP 1.6/1.7)

file.1 - configuration
file.2 - error with total price (with tax)

Any Solution?
Best Regards,

Luigi.
![configurazione](https://user-images.githubusercontent.com/35496189/64116402-8c0b9780-cd92-11e9-86d1-dfe0967d5501.png)
![errore](https://user-images.githubusercontent.com/35496189/64116403-8c0b9780-cd92-11e9-8878-5578a05995f6.png)

**Comment by khouloudbelguith** [comment] 2019-09-02 13:22
Hi @sitolab,

We are aware of the Rounding issue.
Your ticket is a duplicate of #9779
You can also these issues: #9981 & #9815
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-09-02 13:22
Duplicate of #9779

**Closed as completed** 2019-09-02 14:25 UTC
Labels: Duplicate
