### ISSUE TITLE
Incorrect stock management with packs

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#25620] opened 2021-08-16 16:06 UTC
#### Describe the bug
When increasing the stock of a pack, the stock of the products of the pack are increase but wrongly (5 times more than expected) and the pack is not increase

#### Expected behavior
The products of the pack should increase the same as the pack increase

#### Steps to Reproduce

Requirement: Edit the pack and set Decrease product of pack only (but it may be the same issue with other option)

1. Go to Stock management
2. Increase the stock of the pack by 500
3. The products of the pack will be increased by 2500

Also you will see the pack hasn't been increase in the stock management. And another issue is if you go and edit the pack, you will see that the quantity has been increase.

The other way round, if you change the quantity of the pack editing the product itself, if you save and refresh the page you will see still the old quantity. But if you go to stock management, you will see the updated quantity

#### Additional information

* PrestaShop version: 1.7.7.6
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-08-17 10:59
Hello @arirangz 

I didn't manage to reproduce your issue with PS1776, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/129714686-36fc0e78-995e-4644-a36a-3fd7e11c2b39.png)

![image](https://user-images.githubusercontent.com/23308427/129714696-73e80e85-c6c3-4ada-8711-8e001725b7d6.png)

![image](https://user-images.githubusercontent.com/23308427/129714702-e3e2ca23-82db-4018-9938-a5ef789b2c03.png)

And could you please check this issue #9806 seems related to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-06 11:21
Hello @arirangz 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-06 11:21 UTC
Labels: Bug, BO, Stocks, Pack, No change required
