### ISSUE TITLE
Google maps on order

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#10402] opened 2018-09-12 12:36 UTC
On customer order, Google maps have an error like this
https://screenshots.firefox.com/ugYQL8qWd96LdzdZ/www.100asa.it
Prestashop 1.7.4.2 on debian 9.5, apache+nginx

**Comment by khouloudbelguith** [comment] 2018-09-12 12:54
Hi @

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10393
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-12 12:54
Duplicate of #10393

**Closed as completed by khouloudbelguith** 2018-09-12 12:54 UTC
Labels: Duplicate
