### ISSUE TITLE
Argument 4 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\ProductDetails::__construct() must be of the type string, null given, called in

### ISSUE THREAD

**Issue by nolnul** [PrestaShop/PrestaShop#35251] opened 2024-02-02 17:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Argument 4 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\ProductDetails::__construct() must be of the type string, null given, called in....
![1dd88b06a29fe83fd93dbc7337bbfe5c](https://github.com/PrestaShop/PrestaShop/assets/93933991/d408eba8-bbff-4570-96cc-7c2701aba838)

### Steps to reproduce

i dont know

### PrestaShop version(s) where the bug happened

8.1.3

**Comment by Hlavtox** [comment] 2024-02-03 16:22
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/34454

**Closed as completed by Hlavtox** 2024-02-03 16:22 UTC
Labels: Bug
