### ISSUE TITLE
Image slider ignores changes after upgrade

### ISSUE THREAD

**Issue by frankmasio** [PrestaShop/PrestaShop#23440] opened 2021-02-26 17:56 UTC
#### Describe the bug
After a upgrade from 1 click upgrade. From v1.7.6.7 to 1.7.7.2, I configure the  Image slider (v3.1.0 - by PrestaShop). Originally i had 3 images. I removed one. and added a new image. View my shop FO, nothing has changed. it completely ignores any changes?  

#### Expected behavior
It should of changed the image slider removing the first image and show the added image.

#### Steps to Reproduce

1. upgrade with 1 click upgrade from v1.7.6.7 to 1.7.7.2
2. configure the  Image slider (v3.1.0 - by PrestaShop)
3. Originally i had 3 images. I removed one. and added a new image.
4. Save
5. See error => the removed image slider still displayed the first image and  the new one isn't displayed
6. I turned on debugging ( Advanced>performance>debug mode> yes)
7. refresh FO, I didn't get the expected page with slider . All i get is this (see the error below)

**Screenshots**

 ```
(1/1) ContextErrorException

Warning: Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfo = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false)
in Cart.php
at ErrorHandler->handleError(2, 'Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfo = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false)', '/var/www/clients/client1/web2/web/override/classes/Cart.php', 0, array('className' => 'Cart', 'classDir' => '/var/www/clients/client1/web2/web/'))in PrestaShopAutoload.php line 152
at require_once()in PrestaShopAutoload.php line 152
at PrestaShopAutoload->load('Cart')in DebugClassLoader.php line 159
at DebugClassLoader->loadClass('Cart')
at spl_autoload_call('Cart')in FrontController.php line 416
at FrontControllerCore->init()in Controller.php line 287
at ControllerCore->run()in Dispatcher.php line 518
at DispatcherCore->dispatch()in index.php line 28
```
#### Additional information
* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by frankmasio** [comment] 2021-02-27 19:39
this is not a slider issue

the slider module was a theme module that seemed hidden and took searching with grep at the console to find it. 

and its all find.  I still have warnings mentioned above so take note ?

**Comment by hibatallahAouadni** [comment] 2021-03-01 11:20
Hello @frankmasio 

I just edit your issue description, could you please check it if it's correct.
And please next time **FOLLOW THE PROVIDED TEMPLATE TO SUBMIT A COMPLETE BUG REPORT**.
Please check and feedback.

Thanks!

**Comment by frankmasio** [comment] 2021-03-01 14:09
thank you yes, be nice if you could change title to installed but getting warnings and page will not load.

**Comment by hibatallahAouadni** [comment] 2021-03-01 15:20
Hello @frankmasio 

You can edit your issue description and title by yourself :wink: 
I didn't manage to reproduce your issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1tfwlTQ2mDEOCz12umTwUaM_Tk4v7HDA2/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-22 08:31
Hello @frankmasio ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-22 08:31 UTC
Labels: Bug, FO, Imageslider, No change required, 1.7.7.2
