### ISSUE TITLE
BO / Order partial refund / Wrong stock issue

### ISSUE THREAD

**Issue by arcofins** [PrestaShop/PrestaShop#28819] opened 2022-06-22 12:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Back-office : On the view of an order, I can create a partial refund.
If I choose to not put back the item refunded in the stock, however the stock of this item is increased. 

<img width="1430" alt="Capture d’écran 2022-06-22 à 14 46 38" src="https://user-images.githubusercontent.com/65950828/175033068-9065621f-a4af-4055-936a-ade423b2d024.png">

### Expected behavior

Back-office : When I want to partially refund an order, if I don't thick the box "Remettre les produits en stock (add refunded products to the stock)", the stock of this item don't have to change.

### Steps to reproduce

1 . Go to your BO
2. Click on an order
3. Click on "partial refund"
4. Choose the number of products to refund and check the stock (for example, product 1 with stock = 0)
5. Don't thick the box "Add refunded products to the stock" 
6. Click on "refund the order" and change the state of the order to "Refunded" 
7. Check your stock (my stock for product 1 is now = 1)
8. Create an issue on GitHub...

### PrestaShop version(s) where the bug happened

1.7.1.2

### PHP version(s) where the bug happened

7.0.33

**Comment by sLorenzini** [comment] 2022-06-23 09:37
Hello @arcofins, 

Thank you for submitting this issue. 

I couldn't reproduce this issue on ps1712. Here's my screenrecord:

https://user-images.githubusercontent.com/2854834/175268288-4fabc7f8-b621-426c-a389-3dcbb70eec43.mp4


Furthermore, If I check the "Re-stock products" checkbox, the quantity of the product is well updated.

Did I missed something? Could you provide us more details or update your step to reproduce please 🙏?

Waiting for your feedbacks. 

Thank you

**Comment by hibatallahAouadni** [comment] 2022-07-12 16:15
Hello @arcofins 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-07-12 16:15 UTC
Labels: Bug, BO, Order, Stocks, Order statuses, Invalid
