### ISSUE TITLE
editing combination results in a symfony error for a NULL isbn

### ISSUE THREAD

**Issue by ihulsbus** [PrestaShop/PrestaShop#33970] opened 2023-09-18 16:02 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to edit a product combination results in a 500 error on NULL value for ISBN.

```
HTTP 500 Internal Server Error
PrestaShop\PrestaShop\Core\Domain\Product\Combination\QueryResult\CombinationDetails::__construct(): Argument #2 ($isbn) must be of type string, null given, called in /var/www/html/src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php on line 211
```

```
TypeError:
PrestaShop\PrestaShop\Core\Domain\Product\Combination\QueryResult\CombinationDetails::__construct(): Argument #2 ($isbn) must be of type string, null given, called in /var/www/html/src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php on line 211

  at src/Core/Domain/Product/Combination/QueryResult/CombinationDetails.php:76
  at PrestaShop\PrestaShop\Core\Domain\Product\Combination\QueryResult\CombinationDetails->__construct('0', null, null, '5058110', null, object(DecimalNumber))
     (src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php:211)
  at PrestaShop\PrestaShop\Adapter\Product\Combination\QueryHandler\GetCombinationForEditingHandler->getDetails(object(Combination))
     (src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php:174)
  at PrestaShop\PrestaShop\Adapter\Product\Combination\QueryHandler\GetCombinationForEditingHandler->handle(object(GetCombinationForEditing))
     (vendor/league/tactician/src/Handler/CommandHandlerMiddleware.php:71)
  at League\Tactician\Handler\CommandHandlerMiddleware->execute(object(GetCombinationForEditing), object(Closure))
     (vendor/league/tactician/src/CommandBus.php:62)
  at League\Tactician\CommandBus->League\Tactician\{closure}(object(GetCombinationForEditing))
     (src/Core/CommandBus/Middleware/CommandRegisterMiddleware.php:79)
  at PrestaShop\PrestaShop\Core\CommandBus\Middleware\CommandRegisterMiddleware->execute(object(GetCombinationForEditing), object(Closure))
     (vendor/league/tactician/src/CommandBus.php:62)
  at League\Tactician\CommandBus->League\Tactician\{closure}(object(GetCombinationForEditing))
     (vendor/league/tactician/src/CommandBus.php:42)
  at League\Tactician\CommandBus->handle(object(GetCombinationForEditing))
     (src/Core/CommandBus/TacticianCommandBusAdapter.php:54)
  at PrestaShop\PrestaShop\Core\CommandBus\TacticianCommandBusAdapter->handle(object(GetCombinationForEditing))
     (src/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProvider.php:81)
  at PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CombinationFormDataProvider->getData(415)
     (src/Core/Form/IdentifiableObject/Builder/FormBuilder.php:133)
  at PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder->getFormFor(415)
     (src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php:82)
  at PrestaShopBundle\Controller\Admin\Sell\Catalog\Product\CombinationController->editAction(object(Request), 415)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:169)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:81)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin/index.php:84)                
```

### Expected behavior

I expect to be able to edit the product combination.

### Steps to reproduce

1. Enable debug mode
2. Open product combination in backend
3. In the combinations tab, click the pencil of a combination entry
4. see the symfony exception

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.22

**Comment by florine2623** [comment] 2023-09-20 08:48
Hello @ihulsbus ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/d40fe7dc-d42b-4138-b49a-55bd8443befb

Can yous end a screenrecord of the error please ?

Waiting for your feedback

**Comment by ihulsbus** [comment] 2023-09-21 08:50
Hi yes screen recording without debug mode attached. (debug mode reveals some information I'd not like to have public)
https://github.com/PrestaShop/PrestaShop/assets/11390889/86a0d3b8-02b4-4feb-9ed5-0977007f82f3

**Comment by aniszr** [comment] 2023-09-21 15:51
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. 

Could you please enable debug mode to make sure that is not the cause of your problem

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/1cd6321a-a5ec-4f29-ac87-04b78f71bd2d)

We will close this issue.

Thank you!

**Closed as not planned by aniszr** 2023-09-21 15:51 UTC
Labels: Bug, BO, Combinations, Invalid, Products Page
