### ISSUE TITLE
Can no longer search for customer by email only.

### ISSUE THREAD

**Issue by dialt0n3** [PrestaShop/PrestaShop#23347] opened 2021-02-22 14:18 UTC
#### Describe the bug
Did a sandbox upgrade from 1.7.5.2 to 1.7.71 

Mostly everything is working except i can no longer search for customer via email only, or name ect.

It is requiring me to search for customers with their mobile number (which was not previously collected by customers)

#### Expected behavior

Allow search for customers by email only or first and last name 

#### Steps to Reproduce

1. Go to customers section
2. Search for customer by email only
3. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.71
* PHP version: 7.2
![Capture2](https://user-images.githubusercontent.com/2801150/108720518-ecdee080-74ee-11eb-9ded-94e21fcef267.JPG)

**Comment by hibatallahAouadni** [comment] 2021-02-22 14:42
Hello @dialt0n3 

I didn't manage to reproduce your issue with PS1.7.7.1 cause I don't have within the default shop the column **Mobile number**.
Please check the attached screen record below:

https://drive.google.com/file/d/1LBIGCX6kFK45m5aDijw5JbpIqKAYV1og/view

Please check and feedback.
Thanks!

**Comment by dialt0n3** [comment] 2021-02-22 14:49
@hibatallahAouadni thank you for the video 
i would record one to show you as well but i can not as it would expose customer data.

My search has the following fields 
![Capture3](https://user-images.githubusercontent.com/2801150/108724031-e05c8700-74f2-11eb-9e83-b10da7ca8318.JPG)

where as i noticed that yours does not have mobile number field. 

this issue does not exist in my previous version and it does allow a search on email alone
![Capture4](https://user-images.githubusercontent.com/2801150/108724416-4943ff00-74f3-11eb-96f7-aa1533ba448c.JPG)

Is there perhaps a setting to turn this off that i am un aware of ?

**Comment by dialt0n3** [comment] 2021-02-22 15:30
digging further 
my required fields section looks like this, only option being partner offers 

![image](https://user-images.githubusercontent.com/2801150/108729830-f0776500-74f8-11eb-9786-ce8603ffad3e.png)

**Comment by hibatallahAouadni** [comment] 2021-02-22 19:01
@dialt0n3 yep I have the same requierd fields as yours :wink: 
Well, @khouloudbelguith any idea where I could add this column **Mobile number** in my Customer table?

**Comment by dialt0n3** [comment] 2021-02-22 21:55
it seems the phone and phone_mobile columns were deleted by the one click upgrade module to 1.7.7.1 

We have added them manually. Now everything is seems to be ok.

i will do further testing but something is broken in the 1 click updater.

**Comment by dialt0n3** [comment] 2021-02-23 14:32
No i was wrong that fixed another issue but it is still requiring a mobile number to search for the customers

**Comment by hibatallahAouadni** [comment] 2021-02-23 14:48
Hello @dialt0n3 

> it seems the phone and phone_mobile columns were deleted by the one click upgrade module to 1.7.7.1

what was your previous version?

Thanks!

**Comment by dialt0n3** [comment] 2021-02-23 14:49
1.7.5.2
Also i have a temporary work around. 

If i enter only the email for customer in search, and then a single whitespace in the mobile number field it does allow the search to be preformed.

so this is a 100% bug

**Comment by hibatallahAouadni** [comment] 2021-02-23 14:54
@dialt0n3 did you add the **mobile number** column manually?

**Comment by dialt0n3** [comment] 2021-02-23 14:54
phone and phone_mobile yes were added manually

**Comment by hibatallahAouadni** [comment] 2021-02-23 14:59
Hello @dialt0n3 

So, it's not a PS Core bug but it's actually your bug :sweat_smile: 
Check your code, it seems you add the **required** attribute in your **Mobile number** input :wink: 

I'm closing this issue cause it's not related to the PS Core. But I can always answer you in this thread :wink: 
And if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-23 14:59 UTC
Labels: Bug, BO, Customer, No change required, 1.7.7.1

**Comment by dialt0n3** [comment] 2021-02-23 15:00
no i have confirmed that required for these are set to false

**Comment by dialt0n3** [comment] 2021-02-23 15:06
![image](https://user-images.githubusercontent.com/2801150/108862904-aa84d480-75be-11eb-92d4-9ebb6bf061fa.png)

As you can see @hibatallahAouadni you are incorrect.

Also you are not addressing the issue as to why the tables were removed by updater ?

**Comment by dialt0n3** [comment] 2021-02-23 15:06
@hibatallahAouadni please reopen issue case

**Comment by hibatallahAouadni** [comment] 2021-02-23 15:11
@dialt0n3 try to delete what you have been add and check if the issue still persist. 
And please don't be frustrated as I told you I can always answer even when the issue is closed :wink:

**Comment by dialt0n3** [comment] 2021-02-23 15:12
i tried that last night when i restored the backup
and even without the added table the issue is still there

**Comment by hibatallahAouadni** [comment] 2021-02-23 15:19
Did you install some module related to Customer management?

**Comment by dialt0n3** [comment] 2021-02-23 15:29
@hibatallahAouadni none relating to customer management no.
Just payment modules and security pro.

**Comment by hibatallahAouadni** [comment] 2021-02-23 15:48
ok! Did you disable your overrides?

**Comment by dialt0n3** [comment] 2021-02-23 15:52
No overrides are set.

**Comment by dialt0n3** [comment] 2021-02-23 21:33
@hibatallahAouadni the issue should still need to be corrected....
