### ISSUE TITLE
new-theme office - mobile

### ISSUE THREAD

**Issue by PL4STER** [PrestaShop/PrestaShop#22871] opened 2021-01-18 09:46 UTC
Hello, I have modified (added) custom entries to the office templates to improve responsiveness on mobile devices

```
@media (max-width: 767.98px){
#order-view-page .product-row .nav-tabs {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: nowrap;
    flex-wrap: wrap;
    -ms-flex-align: end;
    white-space: inherit;
    padding: 10px;
    font-size: 0.6rem;
}



#order-view-page #historyTabContent .badge {
    white-space: revert;
}


.btn {
    border-width: 1px;
    font-weight: 600;
    border-radius: .063rem;
    white-space: initial;
}




}


@media (max-width: 1299.98px){
#order-view-page .table {
    display: block;
    overflow-x: scroll;
}}


@media (max-width: 767.98px){
.adminorders .header-toolbar .toolbar-icons {
    margin-top: 25px;
    float: right;
}}

@media (max-width: 767.98px){
.card-header:first-child {
   overflow-x: scroll;
}}
```

A layman's fixes so there may be some mistake.

**Comment by NeOMakinG** [comment] 2021-01-18 09:49
Hey

https://github.com/PrestaShop/PrestaShop/issues/22358

We're working on the responsive these days, it looks like we've worked on a lot of things you've modified there, maybe this won't be needed anymore :)

**Comment by hibatallahAouadni** [comment] 2021-01-18 11:02
Hello @PL4STER 

Thanks for your hard working :rocket:
But as @NeOMakinG mentioned we are already working on it :wink: 

This issue is a duplicate of #22660. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: @NeOMakinG thanks :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-18 11:03
Duplicate of #22660

**Closed as completed by hibatallahAouadni** 2021-01-18 11:02 UTC
Labels: Duplicate
