### ISSUE TITLE
BO: Themes translation are empty in BO

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#27410] opened 2022-01-20 14:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Themes translations are empty in the BO:
![Screenshot_1](https://user-images.githubusercontent.com/22581200/150354209-54e2d365-62d5-4b69-84ff-2d006dfefc97.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/22581200/150354329-f1ca34fe-1be8-4c9f-92c0-1d152790c3a7.jpg)
But all tested themes by me fully translated to French and the translations appear in Front office:
![Screenshot_3](https://user-images.githubusercontent.com/22581200/150355085-b815c860-965d-450f-9a94-2f080bf5d9be.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/22581200/150355089-ad3596aa-c0f6-4e1d-862b-7f8056395f2b.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/22581200/150355094-8a01c3a3-0c65-4aa2-8296-9b262287cc2a.jpg)
But these translations are empty in BO:
![Screenshot_6](https://user-images.githubusercontent.com/22581200/150355469-190ece81-93cb-4468-9d04-02a3bca079ab.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/22581200/150355476-f292b414-fe84-475b-91f5-29eaf6e64612.jpg)
This problem occur since the PrestaShop 1.7.8.0. 
There are not this problem in previous PrestaShop versions.

### Expected behavior

I expect to see all translations filled in BO because all phrases were translated in tested themes.

### Steps to reproduce

1. Install any custom theme (except "Classic".) that was translated to other languages.
2. Go to Translations:
![Screenshot_1](https://user-images.githubusercontent.com/22581200/150356292-63c3f6bd-ee3e-487a-ac07-1b9ab93165ff.jpg)

3. And see that most of translations are empty
![Screenshot_2](https://user-images.githubusercontent.com/22581200/150356407-fb8a00d7-83f3-4e20-8330-25537277133d.jpg)
:

### PrestaShop version(s) where the bug happened

1.7.8.0 - 1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-01-20 22:10
Hello @web-burn 

Thanks for reporting the issue!
I reproduce the issue with PS1780 and PS1783, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/150429791-00983151-2b8c-412e-b285-19f1eb420c83.mp4

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by web-burn** [comment] 2022-01-21 07:57
Hello @hibatallahAouadni

Thank you for your quick response!

Unfortunately, I do not have sufficient skills. but i will try to find a solution.

**Closed as completed** 2022-08-02 08:12 UTC
Labels: Bug, Minor, BO, Theme & logo, Translations, Regression, Fixed, PR available, 1.7.8.0, Verified
