### ISSUE TITLE
blockreassurance: svg not supported

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#15939] opened 2019-10-14 15:36 UTC
- Create a new reassurance block with an svg file attached : the block is not created and there is no error message.
- Modify an existing reassurance block and upload an svg file : the file is not used and no error message.
Svg should be supported because it's the recommended format: "Choose SVG for best customization."
It works well with jpeg files.

**Comment by khouloudbelguith** [comment] 2019-10-14 15:39
Hi @jf-viguier,

Yes, PrestaShop doesn't support SVG.
Your ticket is a duplicate of #10600
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-14 15:40
Duplicate of #10600

**Comment by jf-viguier** [comment] 2019-10-14 15:44
It's not a duplicate of #10600 : I'm talking about blockreassurance module only and it recommend svg format.

**Comment by matks** [comment] 2019-10-14 15:44
@khouloudbelguith The module blockreassurance is supposed to handle SVG (I think)

**Comment by jf-viguier** [comment] 2019-10-14 15:46
![download](https://user-images.githubusercontent.com/16720275/66764603-7073d080-eeaa-11e9-8408-873244bf64d5.png)
Just open the block page and see.

**Comment by khouloudbelguith** [comment] 2019-10-14 15:53
@jf-viguier, sorry, it is my fault.
I just re-opened the issue.

**Comment by khouloudbelguith** [comment] 2019-10-14 16:02
@jf-viguier, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & `blockreassurance` v4.1.1.
https://drive.google.com/file/d/1BFRYF9iHMztbHnWuoCVK0fNAlSdZ6W1X/view
With `blockreassurance` v3.0.1, I have other behavior, when I add a new block with svg logo => click on save => redirection to empty page => Configure the module again => OK
https://drive.google.com/file/d/1m7BMEtJTU8Y4aFEtNEGXQRZhtKPzyYx9/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-15 07:28
ping @Progi1984

**Comment by Progi1984** [comment] 2019-11-15 13:07
Fixed in PrestaShop/blockreassurance#35

**Closed as completed by Progi1984** 2019-11-15 13:07 UTC
Labels: Bug, Minor, BO, Fixed, Blockreassurance, 1.7.5.2, 1.7.6.1, PR available

**Comment by jf-viguier** [comment] 2019-11-15 13:22
Thanks @Progi1984
