### ISSUE TITLE
session.save_path﻿﻿ problem

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#13436] opened 2019-04-16 14:50 UTC
**Describe the bug**
I am not sure I should call it a bug or a feature request.
There is an issue with session.save_path, specially in cPanel+EasyApache envirornments, when the user gets a "nothing friendly" error if session.save_path is not writable. It is, of course, a server configuration issue, but I think PrestaShop should check it, as it is very common:
https://www.prestashop.com/forums/topic/609679-opendirvarcpanelphpsessionsea-php56-failed-permission-denied-13/
https://www.prestashop.com/forums/topic/853947-change-the-permissions-of-either-applogs-or-varlogs-directory-so-that-the-web-server-can-write-into-it/
https://www.prestashop.com/forums/topic/563895-ps-1700-rc3-error-500-on-install/
https://www.prestashop.com/forums/topic/624164-debugs-error/
https://www.prestashop.com/forums/topic/622875-contexterrorexception-in-classesphp-line-429/
https://www.prestashop.com/forums/topic/648266-error-when-i-enter-products/
https://www.prestashop.com/forums/topic/932181-error-setelah-mengaktifkan-debug-mode/
https://www.prestashop.com/forums/topic/627203-error-in-new-template-in-ps-1722/

... and there are lots of topics in forums about it.

I can see there is already a check in ConfigurationTest.php:
```
 public static function test_sessions()
    {
        if (!$path = @ini_get('session.save_path')) {
            return true;
        }

        return is_writable($path);
    }
```
But it seems it is not properly checking. Is it correct?

**To Reproduce**
Setting a not writable session.save_path in php.ini?

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: all

**Comment by khouloudbelguith** [comment] 2019-04-16 15:48
Hi @rblaurin,

We'll first try to reproduce it and we'll come back to you if we need more information.

Thanks!

**Comment by PierreRambaud** [comment] 2019-04-16 20:40
`session.save_path` depends on the environment.
If this one is empty, you must have properly configure your server.
https://www.php.net/manual/en/session.configuration.php#ini.session.save-path

As I read, this problem came from cPanel and not PrestaShop, we can't test if the directory is writable if we can't get it :D

**Comment by rblaurin** [comment] 2019-04-16 21:25
Thanks for the clarification, @PierreRambaud 
As I said, I know it's a server issue, and not PrestaShop. But it would be good if there was a way to test it from PrestaShop, as it is a very common server issue.
So, no way to avoid this exception in PrestaShop side?

**Comment by khouloudbelguith** [comment] 2019-04-17 08:16
@PrestaShop/prestashop-core-developers, what do you think?

**Comment by matks** [comment] 2019-04-18 20:59
Looks like there is at least 2 usecases
- `session.save_path` empty (not provided): missing configuration
- `session.save_path` targeting a not writable folder: bad configuration

The code
```
 public static function test_sessions()
    {
        if (!$path = @ini_get('session.save_path')) {
            return true;
        }

        return is_writable($path);
    }
```
is supposed to handle the bad configuration usecase.

So what's left is how to handle the missing configuration usecase. Is that correct ?

**Comment by rblaurin** [comment] 2019-04-18 21:17
I think so.
I don't know... maybe it could be tested with some operation in a try block?

**Comment by PierreRambaud** [comment] 2020-10-12 14:55
FYI: https://www.php.net/manual/en/session.configuration.php#ini.session.save-path

The save_path can also be empty because sessions are not only saved in the server and can rely on an external server (like Memcached)

**Comment by rblaurin** [comment] 2020-10-12 16:45
> The save_path can also be empty because sessions are not only saved in the server and can rely on an external server (like Memcached)

That's right. So, the save_handler should also be tested, right?

**Comment by PierreRambaud** [comment] 2020-10-13 12:34
> save_handler

I'm not sure it's a good idea to check that because it's specific to the PHP runner, and it's not a good idea to spend a long time to be sure the PHP runner is able to properly use itself. It's up to the system administrator/developer to be sure that his own configuration is working well. Otherwise, we have to be sure all other configuration variables are properly configured :sweat: 

The principle of checking some PHP configuration keys is for the minimum requirement. 
We should remove all these "sessions checks" instead :thinking:

**Comment by rblaurin** [comment] 2020-10-13 12:53
So maybe could be a good idea to have a separated official tool to help system administrator/developers to detect this kind of misconfiguration and suggest the right way to correct it? 
If you make a simple search in google with the keywords "prestashop session.save_path" you will see this is a very common problem for new users/developers. The same search for magento, for example, will return much less results.
Of course it is not a problem for an experienced user/developer, but I am thinking about the new ones.

**Comment by rblaurin** [comment] 2020-10-13 13:11
So maybe could be a good idea to have a separated official tool to help new developers/users to discover and correct this kind of misconfiguration?
It is a very common problem for new users/developers, and I think it is worth to check it at least on the installation process. No need check all the configuration variables, but I think it woud be nice to check the ones that commonly cause problems.

**Comment by PierreRambaud** [comment] 2020-10-13 13:22
We already have one: https://github.com/PrestaShop/php-ps-info :tada:

**Comment by rblaurin** [comment] 2020-10-13 13:30
Yes, I know it! It is a great tool.
It doesn't test session.save_path/save_handler, right?

**Comment by PierreRambaud** [comment] 2020-10-13 13:35
Not yet, but it's something you can try to add if you want.
Regarding the conversation, I'm closing this one. 
Feel free to create an issue with what you want exactly here https://github.com/PrestaShop/php-ps-info/issues/new :)

**Closed as completed by PierreRambaud** 2020-10-13 13:35 UTC
Labels: Improvement
