### ISSUE TITLE
SyntaxError: redeclaration of let moduleCardController

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#27309] opened 2022-01-11 16:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Browser's console generates an error when I edit product in BO. Error referes to `/admin1234abcde/themes/default/js/bundle/module/module_card.js?1.7.8.2:1`

#### Firefox
> Uncaught SyntaxError: redeclaration of let moduleCardController

#### Chrome
> Uncaught SyntaxError: Identifier 'moduleCardController' has already been declared

### Expected behavior

I'm not sure what exactly does it break. All 1.7.8.2 shops show this error, even [DEMO](https://demo.prestashop.com/#/en/back). I doubt it's related, but on one of them I can't delete any product combination. Ajax call returns `DELETE method not allowed`, but that's only on one of them.

### Steps to reproduce

1. Open BO and browser's console.
2. Go to Catalog -> Products.
3. Edit any product and check the console.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.2,7.3,7.4

**Comment by florine2623** [comment] 2022-01-11 16:29
Hello @SharakPL ,

I was able to reproduce the issue with PrestaShop version 1.7.8.2, although I can't reproduce it on develop branch.

This means that it will be fixed in later version of PS.
So I will close your issue.

Thank you

**Closed as completed by florine2623** 2022-01-11 16:29 UTC
Labels: Bug, Invalid

**Comment by SharakPL** [comment] 2022-01-11 16:32
Thanks @florine2623
Too bad all 1.7.8 releases so far are unusable 😞

**Comment by florine2623** [comment] 2022-01-11 17:42
What is unusable ?
Could you explain it more ?

I tried deleting a product with combinations, as you mentioned, it works well ^^
<img width="287" alt="Screenshot 2022-01-11 at 18 41 36" src="https://user-images.githubusercontent.com/16019289/148994006-ff1e5897-b71e-4428-bf25-28a7c1ea4e7a.png">

Thanks!

**Comment by SharakPL** [comment] 2022-01-11 21:08
I meant deleting a combination from a product, not a product with combinations. Although I fixed it by deleting whole product as I couldn't find exact cause.

Anyway I feel like there's a lot more regressions with 1.7.8 than before and since all other bugs won't even be fixed within 1.7.8 branch, then there's really no point to install it. I'd rather have fairly stable 1.7.7 on new shops and start upgrading when v8 will become fairly stable so probably around 8.3. At least that's the plan. I just don't have good experience with Prestashop lately. Instead of getting more stable it becomes more and more messed up.

**Comment by SharakPL** [comment] 2022-03-04 13:17
Hasn't been fixed in 1.7.8.3 and 1.7.8.4 😖
Console throws this error every time when a product is open for edit.

Why admin uses scripts from themes/default and themes/new-theme? Seems like insane configuration!

**Comment by SharakPL** [comment] 2022-03-04 14:57
@florine2623 please reopen this issue because nothing has been fixed yet, even in develop

https://github.com/PrestaShop/PrestaShop/blob/eaee04a33efc774fd24b3225feb4ef0b2ca02b26/admin-dev/themes/new-theme/js/pages/module/index.ts#L26-L36

https://github.com/PrestaShop/PrestaShop/blob/eaee04a33efc774fd24b3225feb4ef0b2ca02b26/admin-dev/themes/default/js/bundle/module/module_card.js#L2-L7

`moduleCardController` is being redeclared!
