### ISSUE TITLE
FO - The way of specific price which applied in the cart is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27229] opened 2022-01-05 18:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/26762#issuecomment-999467762
When we have different specific prices on different combinations, the way specific price which applied in the cart is NOK.
For more details, check the @jolelievre [comment](https://github.com/PrestaShop/PrestaShop/pull/26762#issuecomment-1002548117)

### Steps to reproduce

1. Go to BO > Shop Parameters > Products Settings > `Quantity discounts based on` Products 
![image](https://user-images.githubusercontent.com/16067358/146761582-cdaf1b6f-9c8a-48c1-b30d-62b259f49888.png)
1. Create a product with 2 combinations with `Retail price(tax excl.) = 10`  & `Retail price per unit (tax excl.)=10` 
![image](https://user-images.githubusercontent.com/16067358/147061921-e73ed18b-a7e8-4335-bbd8-f2ffb6f89206.png)
2. For each combination has an `Impact on price (tax excl.)= 10` & `Impact on price per unit (tax excl.) =10` 
![image](https://user-images.githubusercontent.com/16067358/147062393-fcd9f62f-fab1-4a55-845c-a236903d6590.png)
3. Create a first specific price on all combinations `Starting at 2` and `Apply a discount of 20 Euro tax included`
4. Create a second specific price on the Second combination `Starting at 3` and `Apply a discount of 50%`
![image](https://user-images.githubusercontent.com/16067358/147063444-817b2aa4-83f5-4cc9-a149-3feecf66807f.png)
5. Go to FO > Add first combination with quantity = 1 & second combination with quantity = 1 
![image](https://user-images.githubusercontent.com/16067358/147063564-6556f3cb-9e57-4885-9aa1-4e73441b27da.png)
6. In the FO > Shopping carts page 
![image](https://user-images.githubusercontent.com/16067358/147064731-e71bba1d-01bc-47b1-9b63-994c9f2b251c.png)
7. Increase the quantity of the seond combination 
8. See error
![image](https://user-images.githubusercontent.com/16067358/147079934-94c5df3d-6078-4603-bc83-89dcae16edc1.png)

PS: if we increase the quantity to 3 => ok 
![image](https://user-images.githubusercontent.com/16067358/147067906-af293c51-1f7b-4763-8937-b685f6843e31.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by jolelievre** [comment] 2022-01-05 18:46
Hi @khouloudbelguith I already created an issue for this one https://github.com/PrestaShop/PrestaShop/issues/27226

I don't care which one is kept, if you think yours is better described then we can close mine

**Comment by hibatallahAouadni** [comment] 2022-01-06 11:26
Duplicate of #27226

**Closed as completed by hibatallahAouadni** 2022-01-06 11:26 UTC
Labels: Bug, 8.0.x, FO, Duplicate, Taxes and Prices, Combinations, Shopping carts FO
