### ISSUE TITLE
Prices with VAT not calculated/displayed properly when not logged in

### ISSUE THREAD

**Issue by nielsverhoeven84** [PrestaShop/PrestaShop#14475] opened 2019-07-04 06:14 UTC
All prices are displayed without VAT for users that aren't logged in.

The shop is set up wilth multi store:
- The first shop has no problem with prices
- The second shop is showing prices without VAT if not logged in.

I've already checked the groups settings and they are the same for both stores.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-04 08:19
Hi @nielsverhoeven84,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
I attached a screen record.
https://drive.google.com/file/d/1hBHO8aeyReNqkVdKbwwC4oBtHvT1PRZ7/view
Thanks to check & feedback.

**Comment by nielsverhoeven84** [comment] 2019-07-04 10:05
Hello @khouloudbelguith,

For every customer group (for my store group and each individual store) it shows `inclusief belasting`, the value of that option is `0`.

**Comment by khouloudbelguith** [comment] 2019-07-04 10:11
@nielsverhoeven84, for the customer group, the Price display method is "Tax included" as described in this screenshot
![image](https://user-images.githubusercontent.com/16067358/60659008-4000ad00-9e4c-11e9-81f9-9c385f4ad898.png)
What is the exact option which has 0 as a value?

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-07-04 10:17
@khouloudbelguith 

The HTML is:
```
<select name="price_display_method" class=" fixed-width-xl" id="price_display_method">
	<option value="1">Exclusief belasting</option>
	<option value="0" selected="selected">Inclusief belasting</option>
</select>
```

0 is including taxes, but that is only working on the first store

**Comment by khouloudbelguith** [comment] 2019-07-04 10:22
@nielsverhoeven84, yes, about the HTML, it is normal => 

- Value 1 => for the `Tax excluded`
- Value 0 => for the `Tax included`

![image](https://user-images.githubusercontent.com/16067358/60659669-e0a39c80-9e4d-11e9-967c-e40e8f21dffd.png)
About your issue, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-07-04 13:37
I've solved this issue.

It seemed that customer groups weren't enabled for the second store.

**Comment by khouloudbelguith** [comment] 2019-07-04 13:42
@nielsverhoeven84, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-07-04 13:45
I was wrong, after checking more thorough, I saw VAT was still calculated wrong.

![Schermafbeelding 2019-07-04 om 15 44 41](https://user-images.githubusercontent.com/52320806/60671121-af899300-9e72-11e9-9ef0-2b68f3475202.png)
![Schermafbeelding 2019-07-04 om 15 44 00](https://user-images.githubusercontent.com/52320806/60671122-b0222980-9e72-11e9-95ae-87b5ad1432b6.png)

**Comment by khouloudbelguith** [comment] 2019-07-04 14:13
@nielsverhoeven84, have you the same issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14446?

Thanks!

**Comment by nielsverhoeven84** [comment] 2019-07-04 14:16
Yes, but it shows differently for logged in / not logged in users.

**Comment by khouloudbelguith** [comment] 2019-07-04 14:20
@nielsverhoeven84, yes, the first issue, in the Fo => Ok
The second issue => in the Bo > product page => similar to #14446, is it?
Thanks!

**Comment by nielsverhoeven84** [comment] 2019-07-04 14:22
Yes, it shows all prices without VAT in BO, although VAT of 21% is selected.

**Comment by khouloudbelguith** [comment] 2019-07-04 14:25
@nielsverhoeven84, we are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14446
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-07-04 14:25
Duplicate of #14446

**Closed as completed by khouloudbelguith** 2019-07-04 14:25 UTC
Labels: Bug, FO, Duplicate, Multistore, Customer groups, Taxes and Prices, 1.7.5.2
