### ISSUE TITLE
Attributes list isn't appear in the combination tab with the second language and delete the language id = 1

### ISSUE THREAD

**Issue by namkynam** [PrestaShop/PrestaShop#12339] opened 2019-01-29 08:29 UTC
When you add a language and delete the original language, the BO page does not display new attributes . The list of Attributes is not displayed in the combined tab
![ps1750](https://user-images.githubusercontent.com/19523750/51894544-a0da1400-23da-11e9-847c-7589d96c20a9.jpg)
![ps1750-2](https://user-images.githubusercontent.com/19523750/51894545-a0da1400-23da-11e9-8e84-ef2133f1e3c7.jpg)

**Comment by khouloudbelguith** [comment] 2019-01-29 08:53
Hi @namkynam,

Here's the PR: #10924 to fix the issue.
It is fixed in the next release PS1.7.6.
Your ticket is a duplicate of #9627
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-29 08:53
Duplicate of #9627

**Closed as completed by khouloudbelguith** 2019-01-29 08:53 UTC
Labels: Duplicate
