### ISSUE TITLE
ps_emailalerts - BO - An exception is displayed after deleting a product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20478] opened 2020-08-06 09:58 UTC
#### Describe the bug

When the last release of the ps_emailalerts is installed, an exception is displayed after deleting a product
It is ok with ps_emailalerts v2.1.0

#### Expected behavior

NO exception displayed

#### Steps to Reproduce

1. Install the ps_emailalerts module v2.2.0
2. configure it
3. Go to BO => Catalog => products page => try to delete a product

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/89519017-07b06880-d7dc-11ea-989b-30cdced8365b.png)

#### Additional information

* PrestaShop version: 1.7.7.x, 1.7.6.7
* PHP version: 7.2
* ps_emailalerts v2.2.0

**Comment by matks** [comment] 2020-08-06 13:25
This issue is almost critical.

Because of an issue in install logic, if module is installed on PS 1.7 the SQL table `ps_mailalert_customer_oos` will not be created. Module "looks" OK but without its SQL table its behavior is corrupted.

**Comment by matks** [comment] 2020-08-13 13:03
It seems this issue is actually a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19842 which is already fixed

**Closed as completed** 2020-08-13 13:05 UTC
Labels: Bug, Major, BO, Duplicate, Regression, PR available, 1.7.7.x, 1.7.6.7, ps_emailalerts

**Comment by matks** [comment] 2020-08-14 12:42
Module releases => bugfix has been delivered https://github.com/PrestaShop/ps_emailalerts/releases/tag/v2.2.1
