### ISSUE TITLE
Maintenance information translation at BO header is not escaped properly

### ISSUE THREAD

**Issue by ks129** [PrestaShop/PrestaShop#24686] opened 2021-05-28 08:10 UTC
#### Describe the bug

If you set translation of
```
Your visitors and customers cannot access your shop while in maintenance mode.%s To manage the maintenance settings, go to Shop Parameters > Maintenance tab.
```

to like
```
Your visitors and customers cannot access your shop while in maintenance mode.%s To manage the maintenance settings, go to "Shop Parameters" > "Maintenance" tab.
```
then header breaks:
![Screenshot 2021-05-28 at 11 00 49](https://user-images.githubusercontent.com/45097959/119951037-32a2bd80-bfa4-11eb-969f-c458a2efe378.png)

#### Expected behavior

The header should remain normal and show only icon + maintenance text.

#### Steps to Reproduce

1. Shop must be in English
2. Translate the string that is shown in Describe the bug section and **add quotes** to the string.
3. Activate maintenance mode.
4. Go to any non-dashboard page.
5. See broken header.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-05-28 08:55
Hello @ks129 ,

I was able to reproduce the issue with PrestaShop version 1.7.7.4 and develop, so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-05-28 22:03
Reproduced with PS1.7.6.7, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/120045805-256fe800-c011-11eb-8834-e4a92fe72574.png)

It's not a regression!
> Go to any non-dashboard page

I reproduce the issue only in these pages:

- Dashboard
- Orders > Orders
- Orders > Credit Slips
- Catalog > Monitoring
- Catalog > Attributes & Features
- Catalog > Files
- Catalog > Discounts
- Customers > Addresses
- Customer Service > Customer Service
- Customer Service > Order Messages
- Customer Service > Merchandise Returns
- Stats
- Design > Image Settings
- Shipping > Carriers
- International > Locations
- Advertising
- Shop Parameters > Search
- Shop Parameters > Merchant Expertise
- More > 1-Click Upgrade

**Comment by matks** [comment] 2021-06-14 16:29
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24897

**Closed as completed** 2021-06-14 16:29 UTC
Labels: Bug, develop, Trivial, BO, Translations, Fixed, Front-end, PR available, 1.7.6.7, 1.7.7.4
