### ISSUE TITLE
error during create carrier 

### ISSUE THREAD

**Issue by v1per4llbl4ck** [PrestaShop/PrestaShop#32552] opened 2023-05-12 10:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when i create a carrier i recive this error
TECHNICAL ERROR:

Details:
Error thrown: [object Object]
Text status: parsererror

![image](https://github.com/PrestaShop/PrestaShop/assets/82314915/1eccac99-d22c-435e-86f5-b7e2a15c7fc1)

### Steps to reproduce

1. go to carrier
2. add carrier
3. complete all step
4. at finish recive the error

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment] 2023-05-15 23:10
Hello @v1per4llbl4ck 

I didn't manage to reproduce the issue following the provided steps, see the attached screen record below:

[issue_32552.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/04099602-9ac2-4b5a-b7b1-37826ea9852d)

Please check and feedback.

Thanks!

**Comment by ComonSoft** [comment] 2023-05-16 14:00
I was able to reproduce this error message, after an upgrade process. After clearing cache browser, error message disappeared.

**Comment by hibatallahAouadni** [comment] 2023-06-04 22:24
Hello @v1per4llbl4ck 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed by hibatallahAouadni** 2023-06-04 22:24 UTC
Labels: Bug, Waiting for author, BO, NMI, Shipping, Carriers, 8.0.4
