### ISSUE TITLE
problem upgrade vers 1.7.0 to 1.7.6

### ISSUE THREAD

**Issue by arg73** [PrestaShop/PrestaShop#17063] opened 2020-01-08 10:02 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-01-08 10:06
Hi @arg73,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - Autoupgrade version
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by arg73** [comment] 2020-01-08 10:12
i want to upgrade with the module my prestashop version 1.7.0 to 1.7.6
when i start i have this message :+1: 
Erreurs
Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it.

**Comment by arg73** [comment] 2020-01-08 10:16
Version de PrestaShop : 1.7.0.4

URL de la boutique : http://www.gravure-verre.fr/

Thème actif : classic 
![Capture](https://user-images.githubusercontent.com/46370249/71969862-d05ae880-3207-11ea-995f-789f4dbd9713.JPG)

**Comment by khouloudbelguith** [comment] 2020-01-08 10:18
@arg73, Your ticket is a duplicate of #17062
Here's a solution: https://github.com/PrestaShop/PrestaShop/issues/17062#issuecomment-571973953
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2020-01-08 10:18 UTC
Labels: Bug, Duplicate, Autoupgrade
