### ISSUE TITLE
{order_link} is empty in the mail sent from back end

### ISSUE THREAD

**Issue by johannsnr** [PrestaShop/PrestaShop#27882] opened 2022-03-11 01:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

```
private function getEmailTemplateVars(int $cartId, Language $cartLanguage, Customer $customer): array
    {
        $orderLink = $this->contextLink->getPageLink(
            'order',
            false,
            $cartLanguage->id,
            http_build_query([
                'step' => 3,
                'recover_cart' => $cartId,
                'token_cart' => md5(_COOKIE_KEY_ . 'recover_cart_' . $cartId),
            ])
        );

        return [
            '{order_link}' => $orderLink,
            '{firstname}' => $customer->firstname,
            '{lastname}' => $customer->lastname,
        ];
    }
}
```

The {order_link} is present as you can see but I don't think it is sent in the email or `$ordeLink` is empty. The only other section is this below:
```
 public function handle(SendProcessOrderEmailCommand $command): void
    {
        $cartId = $command->getCartId();

        try {
            $cart = $this->getCart($cartId);
            $customer = $this->getCustomer(new CustomerId((int) $cart->id_customer));
            $cartLanguage = $cart->getAssociatedLanguage();
            $langId = (int) $cartLanguage->getId();
            

            if (!Mail::send(
                $langId,
                'backoffice_order',
                $this->getSubject($cartLanguage),
                $this->getEmailTemplateVars($cartId->getValue(), $cartLanguage, $customer),
                $customer->email,
                $customer->firstname . ' ' . $customer->lastname,
                null,
                null,
                null,
                null,
                _PS_MAIL_DIR_,
                true,
                $cart->id_shop
            )) {
                throw new OrderEmailSendException('Failed to send order process email to customer', OrderEmailSendException::FAILED_SEND_PROCESS_ORDER);
            }
        } catch (PrestaShopException $e) {
            throw new OrderException('An error occurred when trying to get info for order processing');
        }
    }

```
This is the code to send the email when a order is created in the back office and sending order to client. There should be a payment link in the variable {ORDER_LINK}. It is just plain text. I have checked this with STRIPE and PAYPAL gateways and are not working.

### Expected behavior

When the mail is sent from the back office  the mail should contain a payment link so that the customer can easily click the link and pay for the products ordered. This is not happening and the only conclusion I can draw that there is a bug in code.

### Steps to reproduce

1. Go to back office 
2. select new order
3. create an order
4. at bottom of page select payment method, bank, Stripe or Paypal
5. click create order

### PrestaShop version(s) where the bug happened

1.7.8

**Comment by khouloudbelguith** [comment] 2022-03-11 09:27
Hi @johannsnr,

I did not manage to reproduce the issue with PS1784 using
- Bank wire payment module v2.1.1

https://user-images.githubusercontent.com/16067358/157839547-b5bd6fdd-41e5-4d99-bb3c-bb538e2b315f.mp4


- Paypal module v5.5.0

https://user-images.githubusercontent.com/16067358/157839579-fb55c5c1-c150-473d-97c5-c2eac776dd97.mp4

I attached screen records, thanks to check and feedback.

**Comment by johannsnr** [comment] 2022-03-12 01:54
Hi 

This is not what I get, I get an email that gives me this
A new order has been generated on your behalf.

Please go on  <https://syn01be.syd5.hostyourservices.net:2096/cpsess2323685527/3rdparty/roundcube/#NOP> {order_link} to complete the payment.

Please can you help

**Comment by johannsnr** [comment] 2022-03-12 01:56
Hi I get the same for the STRIPE payment email

A new order has been generated on your behalf.

Please go on  <https://syn01be.syd5.hostyourservices.net:2096/cpsess2323685527/3rdparty/roundcube/#NOP> {order_link} to complete the payment.

And the order link is not clickable it is empty

**Comment by hibatallahAouadni** [comment] 2022-03-14 09:39
Hello @johannsnr 

It seems that you have an issue with your mail server cause we are not able to reproduce the issue with all modules that you mentioned :disappointed: Seems your issue is not a PrestaShop core bug.

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

We will close this issue.

Thank you

**Closed as completed by hibatallahAouadni** 2022-03-14 09:39 UTC
Labels: Bug, BO, Order, Modules, Payment methods, Email, Invalid, Module

**Comment by johannsnr** [comment] 2022-03-21 03:11
No I do not have an issue with my email server. Send the mail to yourself and check it out. You are misunderstanding the issue at hand. I have sent and resent this order to myself over and over. There is an issue with the var {order_link} it does not have a href  in the email, it is empty. I cannot be more specific. If you say there is no problem then what is the problem because it does exist. Nothing has been changed in the code! If you could be so kind to elaborate a bit more because I certainly have an issue and simply saying it does not exist is not an answer. Please do not close the issue as I will just lodge it again, it is an issue.

**Comment by johannsnr** [comment] 2022-03-21 03:40
You also are sending the wrong email to yourself. Send the backoffice_order  not the order_confirmation and you will see the problem

**Comment by hibatallahAouadni** [comment] 2022-03-21 08:19
@johannsnr could you please provide a screen record (recording all steps) to help me reproducing the issue :pray: 
Thanks in advance!
