### ISSUE TITLE
Connot install prestashop with docker compose

### ISSUE THREAD

**Issue by Julien-ADDREA** [PrestaShop/PrestaShop#24524] opened 2021-05-17 12:09 UTC
#### Describe the bug

I have tried several times to install prestashop with docker but the same error occurs every time

```
An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

1: Cannot download language pack "fr"
```

#### Expected behavior

Clean install normally ?!

#### Steps to Reproduce

```
version: "3.9"
services:

    # MYSQL
    mysql:
        container_name: mysql.dev
        image: mysql:5
        restart: always
        ports:
            - "3305:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secure
            MYSQL_DATABASE: prestashop
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        networks:
            - dev-network

    # PRESTASHOP
    prestashop:
        container_name: prestashop.dev
        image: prestashop/prestashop
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge
```

**Screenshots**

![image](https://user-images.githubusercontent.com/59737586/118485393-adecaf80-b718-11eb-9317-2c3c047de110.png)

#### Additional information

* PrestaShop version: latest (1.7)
* PHP version: Use Prestashop docker php image v7

**Comment by hibatallahAouadni** [comment] 2021-05-17 16:31
Hello @Julien-ADDREA 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server problem (check max_execution_time, memory_limit) .

We will close this issue.

PS: by the way you can ask for help in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack), you may find someone encounter the same issue and could help you to solve it :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-17 16:31 UTC
Labels: Can't reproduce

**Comment by Julien-ADDREA** [comment] 2021-05-17 16:44
Hello @hibatallahAouadni

I use official docker image for prestashop (prestashop/prestashop) normally php is set correctly no ?

i never can finished install on many tries

I use Docker on Windows with WSL2
