### ISSUE TITLE
ps_metrics Module causes Prestashop Install to fail without write permission above base directory

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/PrestaShop#25044] opened 2021-06-20 14:51 UTC
**Describe the bug:**

The Prestashop install currently fails on the _Install Addons modules_ section with the following error (see image at end for more details):

`
An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.
    ps_metrics1: Cannot install module "ps_metrics"
`

Restarting the install gives the same error each time.

I believe it is due to the module _ps_metrics_ needing write permissions on the folder above the Prestashop base folder. This should not be needed. Although from the description below I do not think this is the full extent of the problem.

**Expected behaviour**

Prestashop should not need write access outside it's base directory. A well configured web server setup might achieve this by setting PHP's `open_basedir` flag and / or by not setting write access on folders outside the base dir for the webserver user.

Prestashop and all required modules should install fully in the above described situation.

**Steps to Reproduce**

Install Prestashop.

**Workaround**

This workaround stops _ps_metrics_ from being included on install. It can then be manually installed after.

1. Start install up to fail point
2. Edit `/src/PrestaShopBundle/Install/Install.php` from the Prestashop base dir
2. Add `ps_metrics` to blacklist array of modules in function `getAddonsModulesList` on line 978
3. Reinstall 
4. Install should complete

If you still want to install the _ps_metrics_ module you can do the following:
1. Download _ps_metrics_ module zip manually from [Addon Store](https://addons.prestashop.com/en/analytics-statistics/49583-prestashop-metrics-beta.html)
2. Set write permission on the folder above the Prestashop base directory / Also remove any PHP `open_basedir` restrictions.
3. Install manually: Module Manager > Upload a Module
4. Set permission back to read only on folder above the Prestashop base directory

You might also be thinking why don't you just set the write permission and do the install and not have to bother with the work around that excludes _ps_metrics_ from the install. For me setting write permissions on the folder above prior to the Prestashop install still causes the install to fail on my setup. I don't know why this is. 

It only works (to a point) if I install Prestashop excluding _ps_metrics_ then install _ps_metrics_ after. Note that if I try to install the module through the module manager after without setting the write permissions the module fails to install. The write permission must be set so their seems to be a write issue but this may not be the whole issue.

The above allows the module to install. However when you go to the modules configure page it informs that you need the Prestashop Accounts module which it gives a button to click to install. After clicking this the following error is reported `Something went wrong. Please try again. ` If you inspect the request made using the browsers web developer tools the following JSON error is given: 

`{"ps_accounts":{"status":false,"msg":"Cannot install module ps_accounts. The module is invalid and cannot be loaded."}}`

I can't seem to find out what ps_accounts is. It's not in your repos and not a lot turns up when i Google for it. So I am a bit suck from here. 

At the end of the day I personally don't want the _ps_metrics_ module installed in the first place but the fact the default install includes it and you can't opt out (without the above hack of adding it to the blacklist) is not ideal.

**Notes**
- PS: 1.7.7.5 (Also occurs on 1.7.7.4)
- OS: Ubuntu 20.04.2 LTS
-  Apache 2.4.41
- PHP: 7.3.28-2 with PHP-FPM setup as per [Prestashop Guide](https://devdocs.prestashop.com/1.7/basics/installation/httpd/)
- [php-ps-info](https://github.com/PrestaShop/php-ps-info) - All green - see attached image
- No errors are raised in the Apache error logs or PHP error logs.

**Reference** 
![install-error](https://user-images.githubusercontent.com/1625635/122676786-6fdf2180-d1d7-11eb-92b9-4c7b1b887cf0.png)
![php-ps-info](https://user-images.githubusercontent.com/1625635/122676785-6f468b00-d1d7-11eb-91b8-018ce1aa3b20.png)

**Comment by matks** [comment] 2021-06-21 07:54
Very good bug report, thank you

Good news: on `develop` branch modules like ps_metrics are not pushed anymore https://github.com/PrestaShop/PrestaShop/pull/24676 but for 1.7.7.5 issue is still there I guess

I'll ping the people working on ps_metrics ASAP

**Comment by hibatallahAouadni** [comment] 2021-06-21 09:31
Hello @haveyougotanypets 

As @matks mentionned this issue has been fixed on develop.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24638. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-21 09:31
Duplicate of #24638

**Closed as completed by hibatallahAouadni** 2021-06-21 09:31 UTC
Labels: Duplicate

**Comment by SharakPL** [comment] 2021-07-05 09:28
> 
> As @matks mentionned this issue has been fixed on develop.
> We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24638.

#24638 states it will be fixed in 1.7.9.0. Is that correct? Does it mean all previous version will still be affected?

**Comment by matks** [comment] 2021-07-05 09:34
@SharakPL No, it's because https://github.com/PrestaShop/PrestaShop/issues/24638 will remove any modules that are not related to the core from the project, so any issues that are introduced by these modules (like ps_metrics) will be removed.

If an issue comes from ps_metrics and we remove ps_metrics from the core, the issue is gone ✅
