### ISSUE TITLE
In product combinations the "Final retail price (tax excl.)" doesn't change setting "Impact on price (tax incl.)"

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15405] opened 2019-09-04 16:19 UTC
Hi
try to go in Hummingbird printed t-shirt product then go in its combinations and select one of them. Then try to change the "Impact on price (tax incl.)", you can see that "Final retail price (tax excl.)" is not changed. This value changes only changing the value without tax
bye

**Screenshots**
![11](https://user-images.githubusercontent.com/653230/64272584-f44bac00-cf3f-11e9-9a32-dd1b69315673.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-09-05 07:55
Hi @maofree,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 / PS1.7.6.0 / PS1.7.6.1.
If we set the field "Impact on price (tax incl.)" =>"Final retail price (tax excl.)" is not changed. (NOK)
If we set the field "Impact on price (tax excl.)" => "Final retail price (tax excl.)" is changed. (Ok)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Maofree** [comment] 2019-09-05 07:57
Hi
I've just reported this error without a fix

**Comment by Maofree** [comment] 2019-09-05 09:36
the shopkeeper ask me if that final price can be set with tax included to see the customer price
is it possible to do like on the 1.6?

**Comment by khouloudbelguith** [comment] 2019-09-05 10:41
@maofree, in the PS1.6, the final price is not displayed
![image](https://user-images.githubusercontent.com/16067358/64333114-cdd45200-cfcd-11e9-9a47-6f843ef3c43e.png)

Thanks!

**Comment by Maofree** [comment] 2019-09-05 10:49
on the 1.6 the final price is with tax, check better
![11](https://user-images.githubusercontent.com/653230/64335635-85239580-cfdb-11e9-849e-dcf426ec6781.png)
![22](https://user-images.githubusercontent.com/653230/64335636-85bc2c00-cfdb-11e9-9db4-ea1f1d12a437.png)

**Comment by khouloudbelguith** [comment] 2019-09-05 11:07
@maofree, improvement created here: https://github.com/PrestaShop/PrestaShop/issues/15416

Thanks!

**Comment by Maofree** [comment] 2019-09-05 11:09
thanks

**Comment by aniszr** [comment] 2023-05-30 12:49
Hi,

I couldn't reproduce this issue in PS8.0.4.
I think that the problem is solved.

see linked video

https://github.com/PrestaShop/PrestaShop/assets/92626242/138ae9a6-14a2-4ae0-896b-10564f8dc05c


Additional info:
PS version :8.0.4
PHP version :8.0

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-05-30 16:17
Hello @aniszr 

Thanks for your feedback.
Indeed the issue has been fixed with PS8.0.4 in both pages Prouct V1 & V2, see the attached screen record below:

[issue_15405.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/aa385548-c806-4fff-a63b-5754590b80ad)

Closing the issue :tada: 

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-30 16:17 UTC
Labels: Bug, Minor, BO, Combinations, Fixed, 1.7.5.2
