### ISSUE TITLE
Blank screen when editing any product in backend

### ISSUE THREAD

**Issue by onlinedhlx** [PrestaShop/PrestaShop#12714] opened 2019-02-26 10:08 UTC
**Describe the bug**

When logging into the admin section, enter the catalog and try to edit any product and all i get is a blank white screen

if you need a log on to test this i can provide one

**Additionnal information**
PrestaShop version: 1.7.3.0
PHP version: 5.6.37
MYSQL version : 5.6.41

**Comment by khouloudbelguith** [comment] 2019-02-26 10:23
Hi @onlinedhlx,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 10:30
hi,

here is the screenshot, probably not much help as it is just a blank screen

![screen shot 2019-02-26 at 11 28 20](https://user-images.githubusercontent.com/48013540/53406239-d6fabb80-39b9-11e9-826f-885924039056.png)

gonna see what other info i can get for you

thanks

**Comment by khouloudbelguith** [comment] 2019-02-26 10:31
@onlinedhlx, Thanks!
Waiting for your feedback, because a white page cannot help us to understand the issue.
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 10:40
not sure what you need from the debug mode, i have turned it on 

is there a way to output a report for you?

**Comment by khouloudbelguith** [comment] 2019-02-26 10:42
@onlinedhlx, when you enable the debug mode, are there any exceptions displayed in the products page?
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 10:42
no there are not...

**Comment by onlinedhlx** [comment] 2019-02-26 10:50
it all appears fine, just goes to teh white screen when i click on edit product

this has been tried in as many browsers and locations as we can get access too (so all browsers really)

**Comment by khouloudbelguith** [comment] 2019-02-26 10:51
@onlinedhlx, do you have a lot of data for this product?
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 10:51
i have asked the server guys for any error reports from their end

thanks :D

**Comment by onlinedhlx** [comment] 2019-02-26 10:52
what do you mean a lot of data? there are a lot of products... each is quite simple

**Comment by khouloudbelguith** [comment] 2019-02-26 10:53
@onlinedhlx, thanks!
A lot of combinations, features,..?

**Comment by onlinedhlx** [comment] 2019-02-26 10:53
no, they are fairly simple

Could it be a disk space issue at the host?

**Comment by khouloudbelguith** [comment] 2019-02-26 10:55
@onlinedhlx,

In your php.ini file, Try to increase:
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit = 512M

Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 10:56
where is the php.ini located?

thanks

**Comment by khouloudbelguith** [comment] 2019-02-26 10:59
@onlinedhlx, on your server, you check with your host provider.
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 11:00
that's what i thought, just checking there isn't a prestashop file..

thanks.. will sort that and see if it helps

**Comment by onlinedhlx** [comment] 2019-02-26 11:23
not sure if this is connected but i can't even log into the admin area of site now

![screen shot 2019-02-26 at 12 22 19](https://user-images.githubusercontent.com/48013540/53409479-458f4780-39c1-11e9-98d7-262ae0694515.png)

**Comment by khouloudbelguith** [comment] 2019-02-26 11:29
@onlinedhlx, Could you please try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

**Comment by onlinedhlx** [comment] 2019-02-26 11:33
so delete all the subfolders in app/cache dev?

thanks?

**Comment by khouloudbelguith** [comment] 2019-02-26 11:36
@onlinedhlx, yes.
dev & prod are cache folders.
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 11:38
ok, will delete now..

thanks

**Comment by onlinedhlx** [comment] 2019-02-26 11:51
ok, back to being able to log in but still get blank white screen when trying to edit a product ...

**Comment by onlinedhlx** [comment] 2019-02-26 11:54
if i try to browse about the backend i get this sort of error lots..
![screen shot 2019-02-26 at 12 53 47](https://user-images.githubusercontent.com/48013540/53410966-9dc84880-39c5-11e9-9a7d-2d38c1441eec.png)

**Comment by khouloudbelguith** [comment] 2019-02-26 11:55
@onlinedhlx, we need to retrieve the PHP error log provided by your host to understand what's wrong.
About your last screenshot, it is a cache issue as before.
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-26 11:57
ok... 
i have asked for php error log, will call later if not received

**Comment by rdy4ever** [comment] 2019-02-26 20:15
You need to give write permissions (0755 should work with apache) to app/cache folder.
You get a 500 error because PS tries to write to cache but the folder may not be writable on the server.

**Comment by onlinedhlx** [comment] 2019-02-27 08:27
the permissions on that folder are already set to 755

regards

**Comment by khouloudbelguith** [comment] 2019-02-27 08:31
@onlinedhlx, could you please try with 775 permissions.
Thanks to check & feedback.

**Comment by onlinedhlx** [comment] 2019-02-27 08:55
still just get a white screen :(

Regards

**Comment by khouloudbelguith** [comment] 2019-02-27 08:57
@onlinedhlx, what about PHP error logs? any news?
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-27 08:57
also there are no errors showing, the apache logs are not available and they don't have php logs as shouldn't they be outputted by Prestashop?

the server guys have checked everything their end and all is good


i don't have a php.ini yet to change the setting in but i will create ASAP

**Comment by khouloudbelguith** [comment] 2019-02-27 09:02
@onlinedhlx, thanks!
Waiting for your feedback after updating your settings.

**Comment by onlinedhlx** [comment] 2019-02-27 09:13
i set up the php.ini with no change

i set it up according to this https://www.prestashop.com/en/blog/php-ini-file

**Comment by khouloudbelguith** [comment] 2019-02-27 09:37
@onlinedhlx,  could you please provide me your credentials to access your shop to test it.
This is a public space.
You can provide me the access by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-27 09:45
no probs, give me one sec to set you up

**Comment by onlinedhlx** [comment] 2019-02-27 09:50
email sent

**Comment by khouloudbelguith** [comment] 2019-02-27 09:57
@onlinedhlx, thanks!
I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment] 2019-02-27 10:11
@onlinedhlx, could you please check this PR: https://github.com/PrestaShop/PrestaShop/pull/8871, it improves rendering of combinations in the Product page, it is fixed in the PS1.7.3.1.
In the other case, we have an issue reported in this ticket #9809, it seems to be similar to your issue, is it?
Thanks!

**Comment by onlinedhlx** [comment] 2019-02-27 10:17
I will take a look this afternoon as I have to go out right now.. I will
report back later

Regards

**Comment by khouloudbelguith** [comment] 2019-02-27 10:20
@onlinedhlx, thanks!
Waiting for your feedback.

**Comment by onlinedhlx** [comment] 2019-03-01 17:27
hi, from what i can tell neither of these are the same issue i am having

regards

**Comment by khouloudbelguith** [comment] 2019-03-04 11:41
@onlinedhlx, thanks for your feedback.
This issue is in progress, it is assigned to our developer Jocelyn Fournier, he is working on it.
Thanks for your patience
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-04 11:41
Duplicate of #9809

**Comment by onlinedhlx** [comment] 2019-03-04 11:43
Will take another look

**Comment by onlinedhlx** [comment] 2019-03-04 13:28
can you point out how this was fixed, can't seem to see the resolution to the problem

**Comment by khouloudbelguith** [comment] 2019-03-04 13:30
@onlinedhlx, isn't your issue duplicate of this ticket: #9809?
Thanks!

**Comment by onlinedhlx** [comment] 2019-03-04 13:31
not as far as i can tell...

**Comment by onlinedhlx** [comment] 2019-03-04 13:33
their issue
"When client connect to backoffice and operate on product the browser blocks because the Features tab are too large.
Is there a best way to paginate and manage features in admin product page?"

MY ISSUE - blank screen when editing product.... 

thanks

**Comment by khouloudbelguith** [comment] 2019-03-04 13:36
@onlinedhlx, have you tried to make this fix: #8871? it improves rendering of combinations in the Product page, it is fixed in the PS1.7.3.1.
Thanks!

**Comment by onlinedhlx** [comment] 2019-03-04 13:38
we don't have combinations as far as i know.. checking with customer....

**Comment by onlinedhlx** [comment] 2019-03-04 13:39
no combinations were added...

**Comment by khouloudbelguith** [comment] 2019-03-04 13:40
@onlinedhlx, only blank page when you edit a standard product without combinations?
Thanks!

**Comment by onlinedhlx** [comment] 2019-03-04 13:42
yep, 

try to edit or add a product and get a blank page

(confirmed there are no product combinations)

**Comment by khouloudbelguith** [comment] 2019-03-04 13:51
@onlinedhlx, to understand your issue, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
In fact, a blank page cannot help us to understand your issue.
thanks!

**Comment by onlinedhlx** [comment] 2019-03-04 13:52
i have said there is no php error log, i asked and was told there isn't one

can you use the log in i sent you to get the debug mode report?

**Comment by khouloudbelguith** [comment] 2019-03-04 14:28
@onlinedhlx, I tried with your shop, debug mode enabled, the same issue occurs.
I try to edit a product, just a blank page.
This is cannot help us
Thanks!

**Comment by onlinedhlx** [comment] 2019-03-04 14:31
that is all the info i have..

server guys have said there are no error logs, and all is working fine
there end..

everything else seems to work fine on prestashop so something to do with
how it deals with products has gone wrong. i need help to fix it

**Comment by khouloudbelguith** [comment] 2019-03-04 14:32
@onlinedhlx, The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself is vague, there are actually several different issues that can cause the 500 error message to appear.

**Comment by onlinedhlx** [comment] 2019-03-04 14:34
i dont get an error message, it doesn't make it that far it seems...

**Comment by khouloudbelguith** [comment] 2019-03-04 14:38
@onlinedhlx, I get this error in your shop,
```
This page does not work Unable to process this request via www.toptoners.com at this time.
HTTP ERROR 500
```
As I said, there are several different issues that can cause the 500 error message to appear.
Thanks!

**Comment by onlinedhlx** [comment] 2019-03-04 14:40
i have given all the info i can about this issue...

this was the reply from my server guy about error logs

"The Apache logs are not available.
PHP error logs should i think by default be being output from presta ?"

**Comment by khouloudbelguith** [comment] 2019-03-04 14:52
@onlinedhlx, in your Project_Folder/var/log, you don't have any files log?
Thanks!

**Comment by onlinedhlx** [comment] 2019-03-05 09:22
the only var/log folder i know of is completely empty

cheers

**Comment by khouloudbelguith** [comment] 2019-03-05 10:08
Hi @onlinedhlx,

Sorry, despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-05 10:08 UTC
Labels: Bug, BO, Can't reproduce

**Comment by onlinedhlx** [comment] 2019-03-05 10:12
so wash hands and charge fortune for support... way to go prestashop

thanks for your help though...will see what i can work out on my own.. and change CMS away from prestashop if needs be

**Comment by khouloudbelguith** [comment] 2019-03-05 10:14
@onlinedhlx, unfortunately, you only have a blank page, and the 500 Internal Server Error can be very frustrating because it is such a vague error.
Thanks!
