### ISSUE TITLE
Language.php warning

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#14136] opened 2019-06-10 12:00 UTC
**Describe the bug**
After I added second language in the back office appeared the Warning when I enter the language to edit
Warning в рядку 393 у файлі /var/www/testmW/test.te.com.ua/classes/Language.php
[2] file_exists(): open_basedir restriction in effect. File(/var/www/testmW/test.te.com.ua/themes/pixtronpro/modules/ps_shoppingcart.tpl/translations/uk.php) is not within the allowed path(s): (/var/www/testmW:/usr/lib/php5:/usr/lib/php:/usr/bin/php:/tmp)
end others

**To Reproduce**
Warning в рядку 393 у файлі /var/www/testmW/test.te.com.ua/classes/Language.php
[2] file_exists(): open_basedir restriction in effect. File(/var/www/testmW/test.te.com.ua/themes/pixtronpro/modules/ps_shoppingcart.tpl/translations/uk.php) is not within the allowed path(s): (/var/www/testmW:/usr/lib/php5:/usr/lib/php:/usr/bin/php:/tmp)

Warning в рядку 393 у файлі /var/www/testmW/test.te.com.ua/classes/Language.php
[2] file_exists(): open_basedir restriction in effect. File(/var/www/testmW/test.te.com.ua/themes/pixtronpro/modules/index.php/translations/uk.php) is not within the allowed path(s): (/var/www/testmW:/usr/lib/php5:/usr/lib/php:/usr/bin/php:/tmp)

Warning в рядку 393 у файлі /var/www/testmW/test.te.com.ua/classes/Language.php
[2] file_exists(): open_basedir restriction in effect. File(/var/www/testmW/test.te.com.ua/themes/pixtronpro/modules/ps_shoppingcart.tpl/translations/uk.php) is not within the allowed path(s): (/var/www/testmW:/usr/lib/php5:/usr/lib/php:/usr/bin/php:/tmp)

Warning в рядку 393 у файлі /var/www/testmW/test.te.com.ua/classes/Language.php
[2] file_exists(): open_basedir restriction in effect. File(/var/www/testmW/test.te.com.ua/themes/pixtronpro/modules/index.php/translations/uk.php) is not within the allowed path(s): (/var/www/testmW:/usr/lib/php5:/usr/lib/php:/usr/bin/php:/tmp)

**Screenshots**
![image](https://user-images.githubusercontent.com/50954519/59194019-46bf3b80-8b90-11e9-99d4-d0e89d3632d7.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 5.6.4

**Comment by khouloudbelguith** [comment] 2019-06-10 12:25
Hi @photinia73,

You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with the theme author & feedback.

**Comment by photinia73** [comment] 2019-06-10 12:34
Already contacted, but they said that this is PS problem, not the theme

**Comment by khouloudbelguith** [comment] 2019-06-10 12:48
@photinia73, thanks for your feedback.
Could you please navigate to your BO => International => Translations => try to update your language.
![image](https://user-images.githubusercontent.com/16067358/59196402-71a49200-8b86-11e9-8da4-1c0c28784d0e.png)

Thanks to check & feedback.

**Comment by photinia73** [comment] 2019-06-10 15:34
I did this but Warning is still apper... In the Back office is the debugging mode, may be if I turn off it? the Warning will disappear, but this don`t mean that the problem will resolve...

**Comment by khouloudbelguith** [comment] 2019-06-10 15:39
@photinia73, when debug mode is disabled, this problem is not displayed, because it is just a warning.
With the classic theme, I did not manage to reproduce the issue.
Have you tried to add a language when the classic theme is selected?

Thanks!

**Comment by photinia73** [comment] 2019-06-10 15:47
You know, I scare change the theme, becase after changing my Pixtron theme does not work properly... So I left a ticket on the theme support, may be this is their bug...

**Comment by khouloudbelguith** [comment] 2019-06-11 16:02
@photinia73, Could you please provide me your theme to test it.
This is a public space.
You can provide me the theme by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-11 08:49
Hi @photinia73,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-11 08:49 UTC
Labels: Bug, BO, Languages, No change required, 1.7.5.1
