### ISSUE TITLE
BO - Problem with google chrome and the eye of Preston 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#29890] opened 2022-10-05 14:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you're with Google chrome v.105.0.5195.52, when you connect and disconnect from the BO, the preston eye have to close and open, this "animation" create an issue with the preston image, as you can see in this video : 

[Untitled_ Oct 5, 2022 11_16 AM.webm](https://user-images.githubusercontent.com/100699445/194083716-375fd1c9-f5b1-45b8-9d54-76cb2ae58eed.webm)

I think the Preston's Image is already loaded when you come from a disconnection so the Image load the second version of the image and want to go to the version 2+1 ( unknow version ) 

### Expected behavior

I wish Preston can blink without problem

### Steps to reproduce

1. Go to BO and connect to it 
2. Disconnect from the BO 
3. Connect again on the BO 
4. Repeat this scenario until you see this issue 

### PrestaShop version(s) where the bug happened

1.7.7.8 - 8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by matks** [comment] 2022-10-05 14:46
@AureRita maybe Preston is sad 😢

**Comment by hibatallahAouadni** [comment] 2022-10-05 15:12
Hello @AureRita 

I didn't manage to reproduce the issue with PS1778, PS1787 and PS800 with Chrome v105, see the attached screen record below:

[issue_29890_2.webm](https://user-images.githubusercontent.com/23308427/194090981-a88079c1-2308-462c-b16d-dbf11d97c5d0.webm)

Closing the issue as it's not a bug.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-10-05 15:12 UTC
Labels: Bug, BO, 1.7.7.8, Invalid, Login
