### ISSUE TITLE
Customer see own order-->add cart=0

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11935] opened 2018-12-27 11:42 UTC
Prestashop 1.7.5 (upgraded from 1.7.4.4)
Linux #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
php 7.2.13
10.1.37-MariaDB-0+deb9u1
Issue: every time a customer see own order (details, tracking, invoice...) prestashop genrate a cart with 0
http://nimb.ws/rxvlu1

**Comment by khouloudbelguith** [comment] 2018-12-27 13:21
Hi @centoasa,

Did you delete any carts from the database manually?
Thanks!

**Comment by centoasa** [comment] 2018-12-27 13:45
Already done many times, but every time customer see own order, PrestaShop add cart=0
Ps: I seem to remember that this was a problem already highlighted, I tried a lot but I did not find anything about it. maybe I remember badly.

**Comment by khouloudbelguith** [comment] 2018-12-27 13:50
@centoasa, After deleting carts from the table ps_cart table, in this table options Tabs you need to set the "AUTO_INCREMENT"= 1101 and save, then the id of the next cart created will be 1001.
PS: 1001 is "the last id_cart + 1" deleted.
![screenshot-1](https://user-images.githubusercontent.com/16067358/50482428-c1333f00-09e6-11e9-9868-cb160ec0641e.png)
Thanks!

**Comment by centoasa** [comment] 2018-12-27 14:32
Done!
Now my ps_cart is http://nimb.ws/ipsVkj
and my shopping cart into presta backoffice is empty!
Let you know when updates incoming.

**Comment by khouloudbelguith** [comment] 2018-12-27 15:06
@centoasa, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-01-29 16:35
Hi @centoasa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-29 16:35 UTC
Labels: Bug, Duplicate, Shopping carts, 1.7.5.0

**Comment by centoasa** [comment] 2019-01-29 16:39
issue still remain: https://nimb.ws/REuF10

> @centoasa, After deleting carts from the table ps_cart table, in this table options Tabs you need to set the "AUTO_INCREMENT"= 1101 and save, then the id of the next cart created will be 1001.
> PS: 1001 is "the last id_cart + 1" deleted.
> ![screenshot-1](https://user-images.githubusercontent.com/16067358/50482428-c1333f00-09e6-11e9-9868-cb160ec0641e.png)
> Thanks!

followed your instruction, but issue still remain!
as you can see here https://nimb.ws/REuF10

**Comment by khouloudbelguith** [comment] 2019-01-30 10:36
Hi @centoasa,

We are aware of this issue, it is added to our bug roadmap.
 If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Your ticket is a duplicate of #9589 
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-30 10:37
Duplicate of #9589
