### ISSUE TITLE
BO - An exception is thrown when save the packed product after adding an associated combinations product when multistore is enabled with product V2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29344] opened 2022-08-15 15:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is thrown when save the packed product after adding an associated combinations product when multistore is enabled with product V2

**8.0.x : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/184663654-2d3fcd9f-942f-4d28-872b-229918c6148f.png)

https://user-images.githubusercontent.com/92912932/184663722-6369f97c-88d6-4a04-a6a0-eab1ed9ed1dd.mp4

### Steps to reproduce

1. Create a combinations product
2. Click to generate combinations and add a reference of each combination and a global reference for the product
3. Create a packed product
4. Add the combinations associated to the previous product
5. Click on Save
6. See error > En exception is thrown

### PrestaShop version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment] 2022-08-15 15:22
Related to this issue [#29343](https://github.com/PrestaShop/PrestaShop/issues/29343)

**Comment by MatShir** [comment] 2022-12-28 14:47
Seems to be fixed

**Comment by MhiriFaten** [comment] 2023-01-11 15:44
This issue is not fixed yet.
I can still reproduce it.

[Untitled_ Jan 11, 2023 4_15 PM.webm](https://user-images.githubusercontent.com/111756615/211850263-482fd9fd-dd8e-4b17-8f25-7d9b84cc3d40.webm)

**Comment by MatShir** [comment] 2023-01-11 16:47
Check on develop :)
Edit: it seems to be fixed on 8.1.x

**Comment by florine2623** [comment] 2023-03-09 16:32
Tested on branches `8.0.x`, `8.1.x` and `develop`.
It is fixed on all theses branches 👍

**Closed as completed by florine2623** 2023-03-09 16:32 UTC
Labels: Bug, 8.0.x, Major, BO, Multistore, Regression, Pack, Verified
