### ISSUE TITLE
Problem calcul tax with Ecotax (Display)

### ISSUE THREAD

**Issue by Ideoclic** [PrestaShop/PrestaShop#24135] opened 2021-04-20 20:25 UTC
#### Describe the bug

The calculation (tax display is wrong) of the tax and when there is an ecotax product in the invoice.

#### Expected behavior

10 % > 34.32 -> Tax is 3.43 and **NOT 3.21**
20 % > 529.20 -> Tax is 105.84 and **NOT 105.62**

3.43 + 105.84 = **109.27 (So it's good on this Invoice)**

#### Steps to Reproduce

1. Create Products 10% (FR)
2. Create Product 20% (FR) Ecotaxe (0.156 TTC for same example)

**Screenshots**

![chrome_G5kTGG506T](https://user-images.githubusercontent.com/80488574/115450594-64de3400-a21c-11eb-8311-7906ca1d9efa.png)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.4

**Comment by florine2623** [comment] 2021-04-21 14:07
Hello @Ideoclic ,

I reproduce your issue in PS 1.7.7.3. It seems like it is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9855
Could you check and let me know.
Thanks!

**Comment by Ideoclic** [comment] 2021-04-21 14:20
> Hello @Ideoclic ,
> 
> I reproduce your issue in PS 1.7.7.3. It seems like it is a duplicate of #9855
> Could you check and let me know.
> Thanks!

Product price is **good** (With ecotaxe) on **1.7.7.3**  0.156 in TTC so 0.13 HT.

but In _1.7.6.9 it's bug_


![chrome_6TAyMN3DmY](https://user-images.githubusercontent.com/80488574/115569324-67449a80-a2bd-11eb-92d7-b669f0a7d3d3.png)

**Comment by Ideoclic** [comment] 2021-04-22 03:48
-> Same problem for **1.7.6.9**
-> In **1.7.6.9** Price Ecotax is bug when i add him so i fix with that : https://github.com/PrestaShop/PrestaShop/issues/10026#issuecomment-457350536 (I don't know if a better fix exist)

![1 7 6](https://user-images.githubusercontent.com/80488574/115652726-1325ce80-a32e-11eb-92db-b859e0ac2e9f.png)

**Comment by florine2623** [comment] 2021-04-23 13:18
Hello @Ideoclic ,

Please check my invoice with product 18.90 and ecotax 0.156 both tax incl.
![Capture d’écran 2021-04-23 à 15 18 13](https://user-images.githubusercontent.com/16019289/115876878-2082ac00-a447-11eb-8e08-d9ec13c82bc3.png)
![Capture d’écran 2021-04-23 à 15 18 28](https://user-images.githubusercontent.com/16019289/115876911-29737d80-a447-11eb-8bbf-0a3b2cc6d7f8.png)

**Comment by Ideoclic** [comment] 2021-04-23 15:11
Hello @florine2623 

Your invoice **is not good**, because if your product has 0.156 TTC (ecotaxe) on your invoice in HT, you sould have **0.13** and not 0.16

Ecotaxe is include in the price

Check this invoice. 

![produitflorine](https://user-images.githubusercontent.com/80488574/115891736-b3771280-a456-11eb-9947-bbed0f6c30b4.png)

![florinegithub](https://user-images.githubusercontent.com/80488574/115891131-08665900-a456-11eb-989c-756f5ed757c4.png)

Many bug with ecotaxe :

(When i add a product ecotaxe in order): https://gyazo.com/4bc8671ca9d1142fef0f4d16807058ba
> Price ecotaxe change 18.9 to 21.18
> Price UVB Mercury... change 132.30 to 148.63 after i add product (ecotaxe)

(When i add a reduction with ecotaxe product in order): https://gyazo.com/27fa55d6b4c42739a460032006d31473
> Price ecotaxe change 18.9 to 21.18 (when i add a reduction)

**Comment by hibatallahAouadni** [comment] 2021-04-28 02:03
Hello @Ideoclic 

I see that you're submitting a lot of issues about ecotax :wink: 
A lot of them are already in our debug roadmap, check this [EPIC] Ecotax #14900
Please check attentively these issues (listed in the EPIC mentioned above) and precise your issue.

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-17 13:36
Hello @Ideoclic ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-17 13:36 UTC
Labels: Bug, CO, Invoices, Taxes and Prices, No change required, 1.7.7.3

**Comment by NorthThomas** [comment] 2022-04-22 13:06
Hi, 

i'm facing the exact same problem. 
I saw that you've add it to the roadmap a year ago, is it fixed ? 

**_The problem_** 

![ecotaxpresta](https://user-images.githubusercontent.com/100681503/164720100-98e3f7fa-f9c7-491c-b0ca-03392fbc6772.jpg)

![ecotaxpresta 2](https://user-images.githubusercontent.com/100681503/164720109-bac5caa8-1532-434e-bc4b-5e2e76c024a4.jpg)


Prestashop version : 1.7.6.2
