### ISSUE TITLE
Related product and color selector bug?

### ISSUE THREAD

**Issue by gcurco** [PrestaShop/PrestaShop#17776] opened 2020-02-21 11:13 UTC
Hi,

I am very confused, I used prestashop just two times, and I have a problem in my Site, and I don't know if it is a bug.

In my product page, when I select a color variation, if there is a related product, the site changes de page to the related product. That is so strange. Any solution? 

Sorry if there is a similar issue opened. Thanks.

**Comment by khouloudbelguith** [comment] 2020-02-21 11:24
Hi @gcurco,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15531 to fix the issue.
Your ticket is a duplicate of #9919
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-21 11:24
Duplicate of #9919

**Closed as completed by khouloudbelguith** 2020-02-21 11:24 UTC
Labels: Duplicate
