### ISSUE TITLE
Double payment on the order after order status "shipped"

### ISSUE THREAD

**Issue by Bekazede** [PrestaShop/PrestaShop#19630] opened 2020-06-08 15:21 UTC
#### Describe the bug

I have disabled billing on the site.
After the order status changed in "shipped", I have double payment in my order (screen 1) and a fake PDF bill...
I found a "solution", if i disable "Show delivery PDF." on the paramaters of the status "shipped" there is no problem anymore.

#### Steps to Reproduce

1. You need to have no facturation on the PrestaShop
2. You must have checked "Show delivery PDF." on the paramaters of the status "shipped" (I have not tested with other statuses)
3. Make a payment
4. Change status to "shipped"

**Screenshots**

1. Double payment : https://ibb.co/gmkvNf4
2. Uncheck (solution) : https://ibb.co/vJ9w2xr

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1

**Comment by florine2623** [comment] 2020-06-08 15:55
Hi @Bekazede ,
I could not reproduce your issue. Please check my screen record : https://drive.google.com/file/d/1fzo53mxuuRWKOIXJ8s5CcR6izckhmWoi/view

I try with 2 different payment methods (Check and wire payment) and it works correctly in both cases.

You are using another payment method, the problem might come from an override. Please check your overrides. You can also disable them to see if it changes anything.
`override` becomes `_override`

Thanks!

**Comment by Bekazede** [comment] 2020-06-09 12:45
Hi @florine2623 

Thanks for your message !
On your video, you disable "Show delivery PDF." but you need to have this activate to see the bug.

Unchecked "Show delivery PDF." is the solution i found at this problem for the moment.

Can you try like that ?

**Comment by florine2623** [comment] 2020-06-11 08:49
Hi @Bekazede ,
Here's my new screen record : https://drive.google.com/file/d/13IpqoO7uVAWCakbY1uBCDDoM_nuoAzXH/view
I can't reproduce the issue.

Please try the following and let me know the outcome :
You are using another payment method, the problem might come from an override. Please check your overrides. You can also disable them to see if it changes anything.
`override` becomes `_override`

Thanks!

**Comment by florine2623** [comment] 2020-07-03 08:38
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-07-03 08:38 UTC
Labels: BO, Order, Order statuses, No change required, 1.7.6.3
