### ISSUE TITLE
Free shipping and invoice

### ISSUE THREAD

**Issue by benlecoqartisans** [PrestaShop/PrestaShop#14191] opened 2019-06-13 13:08 UTC
When you offer shipping in Back-office, the reduction is impacting products amount and not shipping amount.

**To Reproduce**
1. Make an order with shipping costs
2. On back-office, offer the shipping
![image](https://user-images.githubusercontent.com/48204607/59434979-eda01380-8dec-11e9-8556-47640c3fac0c.png)

3. Validate your order and check the invoice
![image](https://user-images.githubusercontent.com/48204607/59434925-cb0dfa80-8dec-11e9-9600-ad22b58a6157.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-06-13 13:36
Hi @benlecoqartisans,

Thanks for your report.
I have the same issue with PS1.7.6.0beta1.
https://drive.google.com/file/d/18v0LTICrFxtsmHHccRB76capyqnMC-5b/view
This issue will be fixed in this ticket: #11492.
It is added to our debug roadmap.
Your ticket is a duplicate of #11492
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-13 13:36
Duplicate of #11492

**Closed as completed by khouloudbelguith** 2019-06-13 13:36 UTC
Labels: Duplicate
