### ISSUE TITLE
Quick View : get "An error occurred while processing your request" error when updating quantity

### ISSUE THREAD

**Issue by jouino16** [PrestaShop/PrestaShop#27810] opened 2022-03-01 07:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

**Context: product page with combinations.** 

Open a quick view modal for any **simple** product listed on the bottom of a product page. When trying to change the quantity, we get the following error "An error occurred while processing your request".
**This happens when the main product (the one in the product page) has combinations, but the product in the quick view model is a simple product**.
### Screenshot
![quick-view-bug](https://user-images.githubusercontent.com/12447492/156120657-4682d3f6-7321-4308-b6bc-2403fb03975c.png)
### Stacktrace
![stacktrace](https://user-images.githubusercontent.com/12447492/156120669-497b73dd-b0c9-4b43-91fd-203e9c75a098.png)

### Expected behavior

The quantity should be updated without error.

### Steps to reproduce

First, enable the display of a carousel of products in the product page. This could be "People also bought", "Viewed products", "You may also like", or any.

1. Open a product page that has combinations (in my example, I took hummingbird-printed-t-shirt in the default PrestaShop installation, which has a size and colour combinations).
2. Make sure that this page has a carousel of related product at the bottom of the page.
3. Open one of these product in a quick view modal. **Make sure it is a simple product without combinations**.
4. Change the quantity.
5. The error message should be displayed.

### Troubleshooting
**After some debugging, I ended with this explanation:**
This is the URL of the request when changing the quantity:

`controller=product&token=<token>&id_product=1&id_customization=0&group[1]=1&group[2]=8&qty=1&token=<token>&id_product=7&id_customization=0&qty=2`

This link is sent from the product page with ID=1 and combination (attributes) group[1]=1 and group[2]=8, to request the quantity change of the product in the quick view modal that has the ID=7.

What happens is that in the method `private function getIdProductAttributeByGroup()` in the `ProductController`:
```
private function getIdProductAttributeByGroup()
{
    $groups = Tools::getValue('group');
    if (empty($groups)) {
        return null;
    }

    return (int) Product::getIdProductAttributeByIdAttributes(
        $this->product->id,
        $groups,
        true
    );
}
```
The `Tools::getValue('group')` will return the combination of the product with ID=1, as if it was for the product with the ID=7, which is wrong.

**I guess we should send an empty `group` parameter for the second product in the URL, like it is done for `id_customization=0`. And this is apparently done through an Ajax call in the minified `core.js` file.**

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.33

**Comment by marwachelly** [comment] 2022-03-01 10:27
Hello, 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22667. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment] 2022-03-01 10:28
Duplicated of https://github.com/PrestaShop/PrestaShop/issues/22667

**Closed as completed by marwachelly** 2022-03-01 10:27 UTC
Labels: Bug, Duplicate, Invalid
