### ISSUE TITLE
"display edit" mention appear in purchase process

### ISSUE THREAD

**Issue by jes6mac** [PrestaShop/PrestaShop#12948] opened 2019-03-17 12:55 UTC
**Describe the bug**
When in then end of purchase process "display edit" mention appear in middle of French text.

**Screenshots** : https://prntscr.com/mx21ct

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.16

**Comment by khouloudbelguith** [comment] 2019-03-18 08:19
Hi @jes6mac,

I did not manage to reproduce the issue with PS1.7.5.1. & PHP7.2.14 and the classic theme provided by PrestaShop.
![image](https://user-images.githubusercontent.com/16067358/54516277-b4c3e000-495e-11e9-9097-55fb7a5c02e4.png)
Did you use the classic theme?
Thanks!

**Comment by jes6mac** [comment] 2019-03-18 09:11
Hi,

Thanks to your reply,
I use a theme I bought on Prestashop Addons. The developer said me that this issue is related to Prestashop…

**Comment by khouloudbelguith** [comment] 2019-03-18 09:15
@jes6mac, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-17 07:39
Hi @jes6mac,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-17 07:39 UTC
Labels: FO, Can't reproduce, 1.7.5.1
