### ISSUE TITLE
Contact form doesn't send email

### ISSUE THREAD

**Issue by uruk-hai-21** [PrestaShop/PrestaShop#17112] opened 2020-01-10 16:55 UTC
**Describe the bug**
Contact form doesn't send email and in back office (Advanced Parameters -> E-mail) is not saved.

I tried in 3 different clean installations with classic theme, both with PHP mail() and SMTP.

The module parameters are setted to:
- Send confirmation email to your customers: YES
- Receive customers' messages by email: YES

**To Reproduce**
1. Go to Contact Page
2. Compile form
3. Click send button
4. No error shows but email wasn't sent

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.26

**Comment by khouloudbelguith** [comment] 2020-01-13 09:07
Hi @ajejebrazorf01,

I did not manage to reproduce the issue with PS1.7.6.2 & the contactform module v4.1.1.
I attached a screen record
https://drive.google.com/file/d/1qxz7vxC3Psd12WRA8_iRZv1Cyb9k8Ql9/view
The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

You need to check with your host.
Could you please navigate to your Back office => Advanced Parameters => E-mail, try to " Test your email configuration" by sending a test email.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-02-10 07:51
Hi @ajejebrazorf01,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-10 07:51 UTC
Labels: Bug, No change required, Contactform, 1.7.6.2
