### ISSUE TITLE
Prestashop 1.7.3.1 - Simple combinations not loaded in admin

### ISSUE THREAD

**Issue by peskajan** [PrestaShop/PrestaShop#22381] opened 2020-12-11 19:52 UTC
#### Describe the bug

I have an issue in 1.7.3.1 - I create a simple combination (two) for a product and everything works in the shop, but when I go back to that product again combinations are not loaded and I get 500 in the console
![image](https://user-images.githubusercontent.com/3920837/101948300-137cc300-3bf2-11eb-976a-e316bdf567a3.png)

Here is my setup info:
![image](https://user-images.githubusercontent.com/3920837/101948442-5048ba00-3bf2-11eb-9617-4db20c49b0b5.png)

**Comment by hibatallahAouadni** [comment] 2020-12-14 14:46
Hello @peskajan 

Could please check if your issue is similar to this one #11471 ?
Please check and feedback!

Thanks!

**Comment by peskajan** [comment] 2020-12-16 10:14
It seems related, although in my case the combinations are generated (I see them correctly in the shop), but I can't see/load them in the admin.

Reading the related issue, it seems to update to 1.7.3.2 should help?

**Comment by hibatallahAouadni** [comment] 2020-12-16 11:44
Hello @peskajan 

> It seems related, although in my case the combinations are generated (I see them correctly in the shop), but I can't see/load them in the admin.

It's the same, cause the problem is about loading these combinations in BO :wink: 

This issue is already in our debug backlog and it is a duplicate of #11471. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-16 11:44
Duplicate of #11471

**Closed as completed by hibatallahAouadni** 2020-12-16 11:44 UTC
Labels: Bug, BO, Duplicate, Combinations

**Comment by peskajan** [comment] 2020-12-16 11:53
@hibatallahAouadni but the duplicate issue you mentioned is already closed so is it fixed or not? Will upgrade to a 1.7.3.2. wont fix the issue?

Thanks,
Jan

**Comment by hibatallahAouadni** [comment] 2020-12-16 12:56
Hello @peskajan 

If you don't use multishop, so you problem can be solved by the solution proposed in this [comment](https://github.com/PrestaShop/PrestaShop/issues/11471#issuecomment-442403800).

If you use multishop context, so your issue is a duplicate of this issue #9664

Thanks!
