### ISSUE TITLE
Faceted Search - products are displayed in wrong order when sorted by "position"

### ISSUE THREAD

**Issue by TaccCZ** [PrestaShop/PrestaShop#16398] opened 2019-11-13 12:17 UTC
**Describe the bug**
When I set the product's position in the administration, my settings won't be reflected on the front of the site.
If I disable Faceted Search module, everyhing works fine!

**To Reproduce**
1. Go to 'Go to admin panel -> add some products and sort them the way you wish'
2. Click on 'Save it'
3. Go to your shop and category you put products in.

**Screenshots**
Video here: https://www.loom.com/share/2e5537bd52164725afcabd72e35e4650

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-11-13 12:49
Hi @TaccCZ,

The problem is fixed if we use the icon in the position column. The product is selected and we can change the position and saved and all changes are validated.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14879 to fix the issue.
It is fixed in the PS1.7.7.0.
Since this PR correct the problem it's OK a New issue was created for the second issue: #15291
Your ticket is a duplicate of #14616
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-13 12:50
Duplicate of #14616

**Closed as completed by khouloudbelguith** 2019-11-13 12:49 UTC
Labels: Duplicate
