### ISSUE TITLE
Combination error with custom attribute PS 1.7.4.4

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#11591] opened 2018-12-03 05:15 UTC
When selecting combinations in FO, I get an error (see screenshot below). To reproduce please follow these steps:

1. Create an attribute with 2 options.
2. Add any product with combination. Combine two colours with the 2 options of your custom attribute. You should see 4 combinations. 
3. Now delete any one of the combinations. Now you should have 3. Save
4. Go to FO, and choose between the colours and the error should arise. If the error does not arise, please delete another combination (please make sure you still have the 2 colours there).

![image](https://user-images.githubusercontent.com/26452178/49354156-d31d0d00-f6da-11e8-8024-818d0117db52.png)

**Additionnal information**
PrestaShop version: 1.7.4.4

**Comment by khouloudbelguith** [comment] 2018-12-03 08:12
Hi @nrcjea001,

Thanks for your report.
This issue is fixed in the version PS1.7.5.0.
This PR: #9390 should fix this issue.
Your ticket is a duplicate of #9390
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-03 08:13
Duplicate of #9390

**Closed as completed by khouloudbelguith** 2018-12-03 08:12 UTC
Labels: Duplicate
