### ISSUE TITLE
Error 500 in orders page

### ISSUE THREAD

**Issue by gerlandog** [PrestaShop/PrestaShop#15316] opened 2019-08-29 14:42 UTC
Hi, i am trying to get my eshop up and running and after configuring everything when I try to go to the orders page i get an error 500...
![Sin título1](https://user-images.githubusercontent.com/21976353/63950301-1b8f0e80-ca52-11e9-8dad-97d7d495055a.png)

could you please help me out?

Thanks!!!

**Comment by khouloudbelguith** [comment] 2019-08-29 14:57
Hi @gerlandog,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15173 to fix the issue.
It is fixed in the PS1.7.6.1.
Your ticket is a duplicate of #14595
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-29 14:57
Duplicate of #14595

**Closed as completed by khouloudbelguith** 2019-08-29 14:57 UTC
Labels: Duplicate, Order

**Comment by gerlandog** [comment] 2019-08-29 14:59
Thanks!
