### ISSUE TITLE
Statistics graphs doesn't work

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#13178] opened 2019-04-04 09:06 UTC
Hello,
On the BO page "statistics", I have numbers but all the graphs are flat.

**To Reproduce**
1. Go to Statistics, then product detail (for example)
2. Select any product that have sales
3. See the result : numbers but flat graph

**Screenshots**

<img width="834" alt="Capture d’écran 2019-04-04 à 10 59 38" src="https://user-images.githubusercontent.com/32092528/55543391-3fc80880-56c9-11e9-8ad6-430c7ca86ff1.png">

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-04-04 09:28
Hi @elmanu13,

We are aware of this issue.
Your ticket is a duplicate of #9983
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-04 09:29
Duplicate of #9983

**Comment by elmanu13** [comment] 2019-04-04 10:04
Hi @khouloudbelguith 

The #9983 is related to the discount prices not taken into account in the dashboard graph for sales and profits, do you think it's the same base problem ?
In the example I put, there is no discount in my sales, and the graph is at zero. If it was the same problem, the graph should show all the sales, even the discounted ones.

Anyway, I trust you if you think the same files are responsible of the 2 problems.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-04-04 15:49
Hi @elmanu13,

I don't have the same result as you.
I attached a video record.
https://drive.google.com/file/d/1S6UoSczFwtt2qFG3DILmu4DCPF38LiLG/view

Could you please add a video record to reproduce your issue.

**Comment by elmanu13** [comment] 2019-04-04 18:55
Hi @khouloudbelguith 

You don't have the same results because the products you selected have zero sales.
You need to have sales to have graphs ;-)
https://drive.google.com/file/d/1qDmhNFmmfmipiIUJhSI3CZinqGsXpJo8/view

**Comment by khouloudbelguith** [comment] 2019-04-05 08:56
Hi @elmanu13,

No graph for me.
I attached a screenshot.
![Capture du 2019 04 05 09 52 32](https://user-images.githubusercontent.com/16067358/55616072-ed4e2100-5788-11e9-99a5-82f33accb12f.png)

I manage to reproduce the issue with PS:1.7.5.1.
This issue is added to our bug roadmap.

Thanks!

**Comment by Progi1984** [comment] 2021-06-15 12:53
Fixed by @daresh in PrestaShop/statsproduct#21

**Closed as completed by Progi1984** 2021-06-15 12:53 UTC
Labels: Bug, Minor, Stats, Fixed, 1.7.5.1, statsproduct, 1.7.6.0, PR available
