### ISSUE TITLE
Order Invoice wrong ecotax

### ISSUE THREAD

**Issue by StoreCommanderDev** [PrestaShop/PrestaShop#14622] opened 2019-07-12 15:27 UTC
**Describe the bug**
Amount of ecotax in Order invoie can be wrong.
SQL request in OrderInvoice->getProductsDetail() is wrong.

**To Reproduce**
In database
1. ps_order_detail : look at ecotax column (example : 0,50)
2. in back office, set new ecotax of product (example: 0,99)
3. Go to Order in back office and click on "View invoice"
4. On product line, under Unit Price column, you can see the ecotax is not 0,50 but 0,83

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.3.1

**Comment by khouloudbelguith** [comment] 2019-07-12 15:58
Hi @StoreCommanderDev,

So, your exact issue is about editing the ecotax of a product after generating an invoice.
The new ecotax is not changed in your invoice or is incorrect?
I attached a screen record
https://drive.google.com/file/d/1JwybPNLWvJECyVRC2NKaqFfYkkt6OLzE/view

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your version PHP.

Thanks!

**Comment by StoreCommanderDev** [comment] 2019-07-15 07:17
Hi @khouloudbelguith !
Your screen record show exactly what the problem is.
Edit ecotax After generate invoice change the ecotax on the product line in the invoice.

I think the SQL request in OrderInvoice->getProductDetail() is wrong. Use a "SELECT *" with 2 LEFT JOIN and some same column name is not really good.

Thank you for you information about PHP version. But actually I don't have any problems with php 7.3.1 and Prestashop 7.6

**Comment by khouloudbelguith** [comment] 2019-07-17 10:41
@StoreCommanderDev, so the exact issue, that the eco-tax in the invoice should not be changed after updating the ecotax? because the merchant can have different invoices for the same order which it's not legal.

Thanks!

**Comment by StoreCommanderDev** [comment] 2019-07-17 11:40
@khouloudbelguith 
Right. eco-tax in the invoice **should not be changed** after updating the ecotax.

**Comment by khouloudbelguith** [comment] 2019-07-17 13:56
@StoreCommanderDev, thanks for these clarifications.
I just added a new comment in this ticket: https://github.com/PrestaShop/PrestaShop/issues/12394
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12394
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-17 13:56
Duplicate of #12394

**Closed as completed by khouloudbelguith** 2019-07-17 13:56 UTC
Labels: Duplicate, Invoices, Taxes and Prices, 1.7.6.0
