### ISSUE TITLE
Bugs - prestashop 1.7.6.3

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17570] opened 2020-02-08 16:43 UTC
Hello
I installed the current script install we add
But the software bugs I found are much greater than the experience itself
Where I found login problems
Adding products in the basket is not completed
The process of changing the properties of the customer's address is not done correctly
Many additions collapse ...

**Comment by LINUX3932** [comment] 2020-02-09 12:56
> Adding products in the basket is not completed

Basket issue here too.

**Comment by matks** [comment] 2020-02-09 14:44
Hi there,

Sorry to hear that you are disappointed in PrestaShop. Indeed there are known bugs in PrestaShop, most of them are listed on this github (see https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3ABug). We are aware of it and working to fix them.

However developer time is limited, and when the amount of issues opened in a certain timeframe exceeds the amount of issues that can be processed using the available developer time, tasks will simply pile up. This is common to ALL projects. I suggest reading [this article](https://m.signalvnoise.com/software-has-bugs-this-is-normal/) written by the founder of Ruby on Rails, it explains why every large projects have, unfortunately, hundred of known (and not yet fixed) bugs.

But here's the upside: PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

So I can read your frustration between the words, but writing "worst experience ever" or "there are lot of bugs" is not going to help at all. Again, PrestaShop is an open source project: it will get better if everybody puts some energy in it. A good start would be to create github issues, like this one, about the bugs you have found. There might be already registered on github so looking for them might be a good thing.

Also, PrestaShop is being used by 300,000 shops worlwide. So it's far from perfect, but I'd say it's impressive that 300,000 shops are using a system unable to add products in the basket. So "adding products in the basket is not completed" is probably not accurate, can you explain further your issue ?

The best way to write a bug report is to follow this template 😉 :

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

Writing accurate bug reports is a very good start to help us (by us, I mean both you and we !) fix those annoying bugs and make PrestaShop a solution you actually like !

**Comment by khouloudbelguith** [comment] 2020-03-17 07:37
Hi @khalidzuhd,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-17 07:37 UTC
Labels: Bug, No change required, 1.7.6.3
