### ISSUE TITLE
Problem running Docker

### ISSUE THREAD

**Issue by danieljarrett74** [PrestaShop/PrestaShop#19052] opened 2020-05-10 07:53 UTC
When running a clean clone of the latest version of prestashop using `docker-compose up` I get the following error when i load it in my browser for the first time:

(1/1) ContextErrorExceptionNotice: Undefined offset: 0
--
in ImageRetriever.php line 271
at ImageRetriever->getNoPictureImage(object(Language))in FrontController.php line 1515
at FrontControllerCore->getTemplateVarUrls()in FrontController.php line 490
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 549
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

![image](https://user-images.githubusercontent.com/223892/81493777-98af9a80-92e6-11ea-9118-5585e05afdc5.png)

I'm assuming this is a bug in given that I would expect it to run the same for all when using docker.

**Comment by atomiix** [comment] 2020-05-11 10:09
Hi @danbot 

We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #17725.

To be informed when it’s fixed, please subscribe to the issue above.

Thank you!

**Comment by atomiix** [comment] 2020-05-11 10:10
Duplicate of #17725

**Closed as completed by atomiix** 2020-05-11 10:10 UTC
Labels: Duplicate
