### ISSUE TITLE
Multiline Translation strings on modules aren't available on backofice for translation

### ISSUE THREAD

**Issue by sesousa** [PrestaShop/PrestaShop#10360] opened 2018-09-10 09:25 UTC
**Describe the bug**
On a multiline translation string on a config page of a 3rd party module, the string doesn't appear for translation on backend.

**To Reproduce**
1. Go to any 3rd party module and construct a multiline language translation like this on a HelperForm's field:
$this->l(
'big translation string here, and we have to split line to pass validation',
'examplemodule'
),
2. Go to Backend -> International -> Translations and select the module you are testing and the other language you want to translate.
3. Check the field, is missing translation.
4. Go to code and concatenate the multiline translation string in one line (it won't pass validation, but serves as test purpose).
5. Go to Backend -> International -> Translations and select the module you are testing and the other language you want to translate.
6. Check the field, translation is there.

**Screenshots**
Multiline:
![ps_t_1](https://user-images.githubusercontent.com/32913352/45288821-8a8ef280-b4e3-11e8-9f5c-e0d02c5004da.png)

Nothing appear on backend for translation.

Single line (doesn't pass validation, too many characters):
![ps_t_2](https://user-images.githubusercontent.com/32913352/45288901-b4e0b000-b4e3-11e8-982d-b7a222c407ac.png)

But appear on backend available for translation:
![ps_t_3](https://user-images.githubusercontent.com/32913352/45288922-c1fd9f00-b4e3-11e8-8bca-635103c4591d.png)

**Additionnal information**
PrestaShop version: 1.7.4.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2018-09-10 09:29
Hi @sesousa,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9525
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-10 09:29
Duplicate of #9525

**Closed as completed by khouloudbelguith** 2018-09-10 09:29 UTC
Labels: Duplicate

**Comment by bogdanbeniaminb** [comment] 2020-08-30 05:47
#9525 has been fixed in 1.7.5, but this issue hasn't (as of 1.7.6.7). I don't think it's a duplicate of #9525 - it isn't similar. The issue is pretty big for people who use code formatters.
