### ISSUE TITLE
Cannot upgrade modules 

### ISSUE THREAD

**Issue by evoratec** [PrestaShop/PrestaShop#26659] opened 2021-11-17 21:15 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Does not upgrade when click on button
![Screenshot 2021-11-17 at 22 14 30](https://user-images.githubusercontent.com/490450/142283557-abf87c1f-14d7-443d-8eea-45da4f014a17.png)
.

### Steps to reproduce

1. Got to Modules
2. Click Upgrade 

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

php 7.4

**Comment by khouloudbelguith** [comment] 2021-11-18 08:41
Hi @evoratec,

Thanks for your report.
I did not manage to reproduce the issue with PS1781 using PHP v7.4.
I attached a screen record
https://watch.screencastify.com/v/KVhvarZ02GuQN8daHVnY
Thanks t check and feedback.

**Comment by evoratec** [comment] 2021-11-18 09:27
Solve here https://githubmemory.com/repo/PrestaShop/PrestaShop/issues/26028 it's a problem with spanish.

https://github.com/PrestaShop/TranslationFiles/blob/5469512ed964238744002c54e272a644497c15d4/1.7/translations/1.7.8/es-ES/AdminModulesNotification.es-ES.xlf#L881

**Comment by khouloudbelguith** [comment] 2021-11-18 11:16
@evoratec,

I did not manage to reproduce the issue with PS1781.
https://watch.screencastify.com/v/SPdsU4XeAH5C5FVjwYp2
Your ticket is a duplicate of #26028
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2021-11-18 11:16
Duplicate of #26028

**Closed as completed by khouloudbelguith** 2021-11-18 11:16 UTC
Labels: Bug, BO, Duplicate, Modules, Module manager, Invalid
