### ISSUE TITLE
I can't delete product combinations

### ISSUE THREAD

**Issue by luisway2net** [PrestaShop/PrestaShop#27104] opened 2021-12-27 20:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have this problem on version 1.8.7.2 and when delete combination display this error:
![Captura de pantalla 2021-12-27 a la(s) 16 28 15](https://user-images.githubusercontent.com/2183028/147501578-d698ca93-e143-4587-a11b-18162b65466b.png)
![Captura de pantalla 2021-12-27 a la(s) 17 01 12](https://user-images.githubusercontent.com/2183028/147503587-168026f7-5cf6-4e50-baac-9f9071a1541c.png)

### Expected behavior

I expected the combination to be erased

### Steps to reproduce

1. Click delete combination
2. Error display in console
3. the combination is not deleted

### PrestaShop version(s) where the bug happened

1.7.8.0 and 1.7.8.2

### PHP version(s) where the bug happened

7.3

**Comment by harman-jack** [comment] 2021-12-28 06:58
Hi @luisway2net, I have checked it on the same version 1.7.8.2, and combinations are removed successfully without any issue, and I think any third-party other module creating this issue on your site.

**Comment by marwachelly** [comment] 2021-12-28 09:24
Hello, 

Thank you for you report but we were not able to reproduce your issue with the provided information on PS1.7.8.2.
https://watch.screencastify.com/v/HlgFARY4AJ8QUl3YuI27
Could you please check again and provide more detailed steps to reproduce the issue.

Thanks,

**Comment by luisway2net** [comment] 2021-12-28 12:53
Hello!,
Thank you for answering. Here reproduced the problem.
https://drive.google.com/file/d/1w8HHXB3xy6NiN9LXNATyyvdPCs39vJGs/view?usp=sharing

**Comment by luisway2net** [comment] 2021-12-29 14:26
I have the same problem in other site with prestashop 1.7.7.2 and different third-party modules. 
I tried to deactivate it and nothing.

Información del servidor
Información del servidor Linux #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64
Versión del software del servidor: Apache/2
Versión PHP: 7.3.16
Límite de memoria: 256M
Tiempo máx. de ejecución: 500
Tamaño máx. para la subida de archivos: 64M

**Comment by hibatallahAouadni** [comment] 2021-12-29 14:54
Hello @luisway2net 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module or a server configuration problem.

We will close this issue.

PS: Please upgrade your Memory limit to 512M.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-29 14:54 UTC
Labels: Bug, BO, Combinations, Invalid
