### ISSUE TITLE
Row duplication on product save for tables pr_feature_product, pr_feature_value and pr_feature_value_lang 

### ISSUE THREAD

**Issue by ProBackup-nl** [PrestaShop/PrestaShop#13760] opened 2019-05-12 10:17 UTC
**Describe the bug**
1 product with combinations (6 variations) results in — when editing and saving the product — to grow — read: duplicate — the mysql tables **pr_feature_product**, **pr_feature_value** and **pr_feature_value_lang** to abnormal row counts (31.000+ **rows**).

**pr_feature_product**
- id_feature = 0
- id_product = 7
- id_feature_value = 1 and counting up

**pr_feature_value**
- id_feature_value = 1 and counting up
- id_feature = 0
- custom = 1

**pr_feature_value_lang**
- id_feature_value = 1 and counting up
- id_lang = 2
- value = Regio

**To Reproduce**
1. Go to '/index.php/sell/catalog/products/number'
2. Just edit something, like title or body text
3. Choose 'Save'
4. and the number of these table rows grow (guestimate: the number of rows will double)

**Additional information**
PrestaShop version: 1.7.5.1
Language: NL
PHP version: 7.2.16 
MySQL version: 10.2.22-MariaDB-cll-lve 
MySQL-engine: InnoDB 
MySQL-driver: DbPDO 
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:60.0) Gecko/20100101 Firefox/60.0 

AttributesGroups = 1
viewattribute_group = 6 attributes

**Cleanup**
With a
```
DELETE FROM `pr_feature_value` WHERE `pr_feature_value`.`id_feature_value` > 1
DELETE FROM `pr_feature_value_lang` WHERE `pr_feature_value_lang`.`id_feature_value` > 1 
DELETE FROM `pr_feature_product` WHERE `pr_feature_product`.`id_feature_value` > 1 

```
I did clean up the mess.

<strike>Not sure if it is a bug, can also be the user interface not making clear to the user that 100+ rows are being generated.</strike>

It is a bug. After a save there are 6 rows. One product save later, and there are 12 rows. Another product save later, and there are 24 rows in all 3 tables (**pr_feature_product**, **pr_feature_value** and **pr_feature_value_lang**).

**Comment by ProBackup-nl** [comment] 2019-05-12 10:29
With a
```
DELETE FROM `pr_feature_value` WHERE `pr_feature_value`.`id_feature_value` > 1
DELETE FROM `pr_feature_value_lang` WHERE `pr_feature_value_lang`.`id_feature_value` > 1 
DELETE FROM `pr_feature_product` WHERE `pr_feature_product`.`id_feature_value` > 1 

```
I did clean up the mess.

Not sure if it is a bug, can also be the user interface not making clear to the user that 100+ rows are being generated.

**Comment by ProBackup-nl** [comment] 2019-05-12 11:46
It is a bug. After a save there are 6 rows. One product save later, and there are 12 rows. Another product save later, and there are 24 rows in all 3 tables.

**Comment by khouloudbelguith** [comment] 2019-05-13 10:28
Hi @ProBackup-nl,

I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0beta1.
I attached a video record
https://drive.google.com/file/d/17s-Gvw1frG9C8FKnCJrbt4j5AM_i-5TA/view
Thanks to check & feedback

PS: your issue could be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/9680
Thanks!

**Comment by ProBackup-nl** [comment] 2019-05-13 21:18
I can't reproduce either.
1. Create new product
2. Fill title, fill summary
3. Go to "Combinations" (2nd tab)
4. Type/choose: "Regio: all"
5. Choose: Generate
6. Six combination lines are create
7. Fill number value lines (six times the same value) 
8. Fill out price value
9. Fill out "State = Refurbished"
10. Save -> there is no issue yet
11. Upload 3 images
12. Assign images to combination items.
there is no issue yet

**Comment by khouloudbelguith** [comment] 2019-05-14 07:15
@ProBackup-nl, so the issue doesn't exist anymore?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-13 07:26
Hi @ProBackup-nl, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-13 07:26 UTC
Labels: BO, Features, No change required, 1.7.5.1
