### ISSUE TITLE
Bug in "EMail" panel after updating to  1.7.6

### ISSUE THREAD

**Issue by johnndunbar** [PrestaShop/PrestaShop#14943] opened 2019-07-31 20:23 UTC
Hello,

After updating with 1 click update from v.1.7.5.2 to 1.7.6.0 I can't access anymore to the Email Panel in the backoffice.
When I'm activated the debug mode, I've got an SQL error :

_An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM rc_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, "email", "index"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.filter_id' in 'field list'_

![image](https://user-images.githubusercontent.com/53540004/62245310-06d74080-b3ea-11e9-8ed9-d3fa999553ee.png)

Do you have any idea what it can be ?

Thank you

**Comment by khouloudbelguith** [comment] 2019-08-01 08:07
Hi @johnndunbar,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14620 to fix the issue.
Your ticket is a duplicate of #14617
Please follow #14617.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-01 08:07
Duplicate of #14617

**Closed as completed by khouloudbelguith** 2019-08-01 08:07 UTC
Labels: Duplicate

**Comment by johnndunbar** [comment] 2019-08-01 08:23
Hello,
I read the PR 14620, it talk about an manuel update issue. In my case I used automatic update.
When I read the ticket I can't find any relation with my problem. Could you please explain a bit more ? Thank you

**Comment by johnndunbar** [comment] 2019-08-01 08:30
Ok sorry I saw it with the ticket 14617. Thanx
