### ISSUE TITLE
Plus "+" character in search blacklisted words give error message after saving a product

### ISSUE THREAD

**Issue by marsaldev** [PrestaShop/PrestaShop#30610] opened 2022-12-19 14:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you add the plus "+" character in the search blacklist words when you save the product you get the error tooltip message.
Actually, the product is saved correctly but you get a "misleading" message.
The problem is in the Search class in a preg_replace: https://github.com/PrestaShop/PrestaShop/blob/4280bf3c29f5e428f22dfbaba38ac59e0cc7c708/classes/Search.php#L216

https://user-images.githubusercontent.com/48283112/208444620-72036e21-d942-4e5e-86e5-e39838366892.mp4

### Expected behavior

Message that product is saved correctly

### Steps to reproduce

1. Go to "Shop Parameters > Search"
2. Scroll to "Search" box
3. Add to _Blacklisted words_  the "+" character at the end (don't forget the | separator)
4. Go in a product sheet (back office)
5. Save
6. See the error

The product is saved correctly, but the message is misleading

### PrestaShop version(s) where the bug happened

1.7.8.x, 8.0.0, develop

### PHP version(s) where the bug happened

7.4, 8.0, 8.1

**Comment by hibatallahAouadni** [comment] 2022-12-20 10:10
Hello @marsaldev 

Thanks for reporting the issue and for your PR!
Unfortunately, the issue is random as you can see in my attached screen record below:

[issue_30610.webm](https://user-images.githubusercontent.com/23308427/208640762-b0691112-b3c1-47a2-beb0-9079e8c27863.webm)

And I didn't manage to reproduce it (even randomly) with the Product V2.
Ping @PrestaShop/product-team should we close the issue, as it only happens in Product V1 randomly? wdyt?

Thanks!

**Comment by marsaldev** [comment] 2022-12-20 10:19
Hi @hibatallahAouadni , thanks for your time 😊 
I think it's probably related to the debug mode 🤔
Did you activated it?

**Comment by MatShir** [comment] 2022-12-27 08:20
I'm putting back `Waiting for QA`. I think it should be retested from the @marsaldev feedbacks. If the bug happens only on debug mode, I suggest flagging it as a trivial. @PrestaShop/qa-functional

**Comment by hibatallahAouadni** [comment] 2022-12-27 10:04
Hello @marsaldev 

Thanks for your feedback.
Indeed, when I enable the debug mode, I reproduce the issue all the time, and it seems related to the product's quantity.
Cause when you change the product's name and save, the error message is displayed "unable to update settings" but you can see that the product's name is well saved. 
But, when you try to edit the product's quantity and save, the quantity is not saved 😞 

**BTW, I didn't reproduce the issue with the new Product Page V2 with PS8.0.0**

Thanks @MatShir for the ping 😉 wdyt, should we fix it with Product Page V1? or just close it as the issue doesn't exist in the Product Page V2 + PS8.0.0?

Thanks in advance 🙏

**Comment by MatShir** [comment] 2022-12-27 10:26
If it is fixed on V2, the issue is too trivial IMO. I suggest closing it. Is that okay for you @marsaldev?

**Comment by MatShir** [comment] 2022-12-28 08:07
@marsaldev don't hesitate to reopen the issue if needed

**Closed as not planned by MatShir** 2022-12-28 08:07 UTC
Labels: Bug, Minor, BO, Won't fix, Search, Verified, 1.7.8.7

**Comment by marsaldev** [comment] 2022-12-28 11:15
Thanks @hibatallahAouadni and @MatShir !
Sorry for my late reply.
To be honest, we will have the v1 page for at least (at best) 1 another year (probably more), although I think the issue is on the Search (the Class) side and not on the Product Page side 🤔

**Comment by MatShir** [comment] 2022-12-28 16:12
You are probably right! Can you look at this issue https://github.com/PrestaShop/PrestaShop/issues/28293 ?
I was wondering, have you seen uses cases where you have to search '+' ?
Otherwise we might need just to block the validation 🤔
