### ISSUE TITLE
Mail alert

### ISSUE THREAD

**Issue by mbazylow** [PrestaShop/PrestaShop#37365] opened 2024-11-13 12:08 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After installing and configuring the "Mail Alerts" plugin, the email input field does not appear on the page of an unavailable product, so users cannot subscribe to receive notifications when the product is back in stock.

### Expected behavior

The user will have an email input field to subscribe for a notification when the product is back in stock.

### Steps to reproduce

1. Go to https://steven.pl/427-podkolanowki-welniane-damskie-z-welny-merino
2. Click on "podkolanowki z welny merynosow" (first item)
3. After opening an item there is no field to enter an email

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Mail Alers

**Comment by florine2623** [comment] 2024-11-13 15:27
Hello @mbazylow ,

I cannot reproduce your issue. 

Please make sure the module is hooked everywhere.

Go to Design > Position > Hook a module > Hook to all hook possible.
![Image](https://github.com/user-attachments/assets/795cee97-508b-4651-b33c-a7533361b195)

Clear the cache and try again.

Also, the theme might not be compatible with this module.

I am closing the issue as it cannot be reproduced.
Thanks!

**Closed as completed by florine2623** 2024-11-13 15:27 UTC
Labels: Bug

**Comment by mbazylow** [comment] 2024-11-15 11:57
Hi @florine2623 
We have ensured that our module is hooked to all possible hooks and have cleared the cache several times, but we still cannot get it to work.
Could you please send us an example page where it is functioning correctly?
We can also provide you with credentials to our PrestaShop so you can check how it looks.
Thanks!
