### ISSUE TITLE
Error in cart - removing products in debug mode and specific language doesn't work

### ISSUE THREAD

**Issue by web-plus** [PrestaShop/PrestaShop#30272] opened 2022-11-11 21:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue occurs since Prestashop 8, in Classic theme. If you delete product(s) from cart on cart page, nothing happens after clicking the remove button. Only after manually refreshing the page, the products will disappear. The problem is visible only in debug mode (works ok in production mode) and only if you choose language other then English (try with French).

See this video: https://www.dropbox.com/s/kr09za0c3qcf6k0/Test%20-%20Google%20Chrome%202022-11-11%2021-07-01.mp4?dl=0

### Expected behavior

Cart should be reloaded after deleting product on cart page. 

### Steps to reproduce

1. Setup Debug mode ON
2. Clear smarty cache
3. Choose language other then English.
4. Add products to cart, go to cart page
5. Try to remove product from cart, nothing happens (unless you refresh the page manually)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.9

**Comment by Hlavtox** [comment] 2022-11-11 21:52
Hi @web-plus, can you please show the ajax response after clicking the button? (F12 in chrome, network tab, filter only XHR, click button and click the request.)

Also, make sure to clear cache in both debug and normal mode, they have their own cache in /var/cache.

**Comment by web-plus** [comment] 2022-11-11 22:00
Ahoj @Hlavtox  :-)
ok, I was to quick before, there is this warning, see attachment. Happens only with CZ, FR language, not EN.  

![Screenshot 2022-11-11 22 58 08](https://user-images.githubusercontent.com/3237634/201436713-2fef2320-be94-4fd7-ab00-b2b9eb9ec252.png)

Yes I know about the cache  (happens only in dev)

**Comment by Hlavtox** [comment] 2022-11-11 22:21
@web-plus 
Caused by this PR: https://github.com/PrestaShop/PrestaShop/pull/28290/files
Fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/30194/files, but only on develop.

We must backport it to v8 branch so it get's into 8.0.1 patch, it's a regression. :(

**Comment by web-plus** [comment] 2022-11-11 22:26
ok @Hlavtox, thank you for information and checking so fast!

**Comment by Hlavtox** [comment] 2022-11-11 22:29
@web-plus Made a PR that will fix it 👍 Dobrou noc :-))

**Comment by hibatallahAouadni** [comment] 2022-11-14 12:35
Hello @web-plus 

Thanks for reporting the issue!
As @Hlavtox mentioned we need to backport the PR and thanks @Hlavtox for your PR and quick replies 🚀 
I didn't reproduce the issue with PS1787, so it's a regression 😉 

Thanks!

**Closed as completed** 2022-12-14 13:24 UTC
Labels: Bug, Minor, FO, Regression, Fixed, Shopping carts FO, PR available, Verified, 8.0.0
