### ISSUE TITLE
Contact form does not send emails

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10772] opened 2018-09-29 11:40 UTC
Hi

I've seen from 3 sites that the contact form does not send emails
this problem is present on 2 online sites, they use different hosting and different themes (one report an error when I send a message, the other says all is ok)
and on my local server with a clean installation with default theme (the form answer that the email is sent but it is not true and the log does not report this sending)

I have no problems with Mail::Send because I use it from my modules and it works well
also the test mail works well
the email logs page in the admin does not show any log when I send email from the contact form instead with the other forms yes, so I think there is a problem with the contactform module

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment] 2018-10-01 09:35
HI @maofree,

Have you the same issue with this ticket: #9566?

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-10-01 10:02
hi
I don't know if it is the same error, but could be (in one site I get the same error answer in the other 2 no but the mail is not sent)
but I reproduce this error on 3 different servers
I can give you the access to one of it

bye

**Comment by Maofree** [comment] 2018-10-01 10:11
at this moment there is another problem on many prestashop 1.6.x sites, the hosting said me it is due from the api connection

Dear Customer,

The problem is because the PrestaShop API is not responding correctly, and any action on the administration tries to connect to it (api.prestashop.com) and it takes about 10-12 seconds to cut the connection. You have to wait for PrestaShop to solve the problem with the connection to your server.

can you check please?
Is it necessary to create a new ticket?

**Comment by khouloudbelguith** [comment] 2018-10-01 10:18
Hi @maofree,

About the Contact form issue, what the exact version of the module did you use?
About the second issue (PrestaShop API), what is the exact issue do you have?

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-10-01 10:34
the contactform version is 4.1.1

the other problem is in the admin's panel (it is very slow today in many sites)
The problem is because the PrestaShop API is not responding correctly, and any action on the administration tries to connect to it (api.prestashop.com) and it takes about 10-12 seconds to cut the connection. You have to wait for PrestaShop to solve the problem with the connection to your server.
The only option is to wait for PrestaShop to solve the problem.

**Comment by khouloudbelguith** [comment] 2018-10-01 10:48
Hi @maofree,

Could you please check if the contactform works with the older version (v3.0)?
Thanks to check & feedback.

Best regards, Khouloud

**Comment by Maofree** [comment] 2018-10-01 10:56
hi
the problem is inside the sendmessage function
if I use the function of 3.0 the 4.1.1 works well and it can send email

I can give you the ftp and admin access to a site to do some tests

**Comment by khouloudbelguith** [comment] 2018-10-01 11:02
Hi @maofree,

So, it is the same issue reported here: #9566.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9566
So, I close it.
Thanks!
For the second issue: here's a PR: https://github.com/PrestaShop/PrestaShop/pull/10791 may help you solve the API issue & You can follow this link: https://twitter.com/PrestaShop/status/1046770589002878977

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 11:02
Duplicate of #9566

**Comment by Maofree** [comment] 2019-03-06 13:34
Hi @khouloudbelguith
can you repopen this topic, because this bug is not the same of the other one of #9566 
in this case I don't get an error after the submit

I can give you the BO and ftp access
I'm sure that there are some problems in that function of 4.1.1
using the previous version all is ok
at this moment I've can reproduce this error on 4 sites and on my local server

I get the confirm message but no emails arrive

3 sites on the same italian hosting the module doesn't work (php mail solution)
1 site on vps of a spanish hosting the module doesn't work (smtp solution)
1 site on Netsons the module works (php mail solution)

in one of those 3 sites the module gives the same error reported on this topic and also doesn't send email

thanks

**Comment by khouloudbelguith** [comment] 2019-03-06 13:45
@maofree, could you please navigate to your BO => Module manager page => search for thi module & click on "Configure" button & check that "Send confirmation email to your customers" & "Receive customers messages by email" options are enabled.
Thanks!

**Comment by Maofree** [comment] 2019-03-06 14:09
hi
you are right it is necessary only to active the option
Receive customers messages by email

can you set it by default?

**Comment by khouloudbelguith** [comment] 2019-03-06 14:18
@maofree, these options by default are disabled.
So, the issue is fixed?
Can I close the issue?
Thanks!

**Comment by Maofree** [comment] 2019-03-06 16:00
yes thanks

**Comment by khouloudbelguith** [comment] 2019-03-06 16:12
@maofree, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-03-06 16:12 UTC
Labels: FO, Contact, No change required, 1.7.4.2

**Comment by TheSxW** [comment] 2020-09-21 13:35
i found out that in my Prestashop 1.7.6.5 its also not sending notifications i detect that this line isnt getting any configuration value
```php
$sendNotificationEmail = Configuration::get(self::SEND_NOTIFICATION_EMAIL);
```
in modules/contactform/contactform.php at line ~575
replacing that CONFIGURATION variable to true enables (hardcode) that variable to always being on but its not a proper solution if someone could respond to this and find proper solution i will be glad :)

additionally i was adding fields named CONTACTFORM_SEND_NOTIFICATION_EMAIL and CONTACTFORM_SEND_CONFIRMATION_EMAIL into db configuration but that didn't help much
