### ISSUE TITLE
URL Rewrite problem

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#20090] opened 2020-07-07 17:27 UTC
When you generate url in product > seo tab

If there are special characters in the product title, and the url is generated with the button for creation, these are not removed and the url is wrong, you have to correct it manually.

* PrestaShop version: 1.7.6.6 and above
* PHP version: 7.2

Here are screenshots of the problem

<img width="710" alt="Schermata 2020-07-07 alle 19 08 13" src="https://user-images.githubusercontent.com/5024055/86819342-cc5d3580-c087-11ea-9496-d865af39c8b4.png">
<img width="737" alt="Schermata 2020-07-07 alle 19 15 14" src="https://user-images.githubusercontent.com/5024055/86819345-cd8e6280-c087-11ea-98c1-98c3c596fe35.png">

**Comment by marionf** [comment] 2020-07-08 11:45
Hello @Betafer 

What do you mean by "the url is generated with the button for creation" ?

If in your product name there is some specials characters non authorized in the URL they are automatically removed of the friendly-url field

**Comment by Betafer** [comment] 2020-07-08 11:52
Hello
The button generate friendly url.. 
, as i tell is not so ....

**Comment by florine2623** [comment] 2020-07-10 14:42
In your product page > SEO tab
When you click on "Reinitialize URL" you should see your friendly url with no error.

**Comment by Betafer** [comment] 2020-07-10 14:48
> In your product page > SEO tab
> When you click on "Reinitialize URL" you should see your friendly url with no error.

when i click Reinitialize URL the url is with error

**Comment by florine2623** [comment] 2020-07-10 14:52
Did you do a migration or is it a fresh install ?
Could you share a screen record and the steps to reproduce your issue please ?

**Comment by Betafer** [comment] 2020-07-10 14:54
migration from 1.5, soon i will make the screen record

**Comment by Gipielle** [comment] 2020-07-10 15:00
https://drive.google.com/file/d/1aDpqcjFvsbvq4GrFRE_K1AKHSeRyzMSa/view

**Comment by florine2623** [comment] 2020-07-10 15:17
Ok thanks for the clarification.
It only happens when you are using multilanguage.
I tried on my test shop with EL, FR, LT and I can't reproduce your issue.

Could you take a look at the console ? right-click > inspect element
And check for errors.

**Comment by Betafer** [comment] 2020-07-13 08:53
There is another problem with url friendly button, that it changes all languages, so if i change a url manually in one language, and than i change language and set url with the Reinitialize URL, it also change url in the language that i have correct manually

**Comment by khouloudbelguith** [comment] 2020-07-14 14:43
Hi @Betafer,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1l8uHDwyGCGrvKD0bGvDtevMb1mpoqibJ/view?usp=sharing

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-03 08:11
Hi @Betafer,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-03 08:11 UTC
Labels: Bug, Minor, BO, No change required

**Comment by Maofree** [comment] 2020-08-26 14:25
hi
the problem shown by this ticket is that the Tools::link_rewrite doesn't remove the strange characters
if you seen in the title there is an " but it is not a regular, it is an oblique apex
it should be removed by that function

” is different from "
the first has 226 unicode value the second 34
using ord()
I've seen that it is the
`&rdquo;`

https://stackoverflow.com/questions/6931386/how-to-convert-this-to-htmlcharacters-and
they are called fancy or smart quotes

bye

**Comment by Maofree** [comment] 2020-08-26 15:38
it is necessary to use this code

`        $beta_name = htmlentities($beta_name, ENT_QUOTES);
        $beta_name = str_replace(array('&rdquo;', '&ldquo;'), '&quot;', $beta_name); 
        $beta_name = html_entity_decode($beta_name);`

**Comment by Gipielle** [comment] 2020-10-18 19:10
Same problem with prestashop 1.7.6.8 ...
![Uploading Schermata 2020-10-18 alle 21.05.27.png…]()

**Comment by Maofree** [comment] 2020-10-18 22:15
Hi @khouloudbelguith and @marionf
can you reopen this topic? now I've inderstood the reason of this problem and it is possible to reproduce it
it is present in all prestashop 1.7 versions

![1](https://user-images.githubusercontent.com/653230/96386842-382e5e80-119e-11eb-8e12-703ea4389172.png)

it happens when it is active the option "Accented URLs"
when this option is active the function
Tools::link_rewrite
works well with special characters removing it excepts accented characters, instead from the product page pushing on the button "reset url" from seo tab, it does not work adding the special characters like quotes or ² or ³ ...

so to reproduce it following this steps:
1) active the option "Accented URLs"
2) go in an admin product page and set a name like:

Pantalon de travail multipoches en T/C canvas 260 g/m², empiècements en Oxford, gris - Beta 7900E

3) push on the "reset url" button

this problem is not present with disabled the option "Accented URLs", the "reset url" button remove the special characters

![2](https://user-images.githubusercontent.com/653230/96387066-d40c9a00-119f-11eb-8dc8-c9017f1706a3.png)
![3](https://user-images.githubusercontent.com/653230/96387068-d53dc700-119f-11eb-8e30-4e79f87c2cdd.png)

it is a javascript bug, the "reset url" button active a javacript cleaning, it should use an ajax solution to use Tools::link_rewrite

bye

**Comment by Maofree** [comment] 2020-10-19 08:54
Hi
I've created a new topic to reopen the case

https://github.com/PrestaShop/PrestaShop/issues/21495

**Comment by Gipielle** [comment] 2021-09-15 19:13
This problem is also created by \x{200B} (Unicode Character 'ZERO WIDTH SPACE' (U+200B)) in the product name.

**Comment by Betafer** [comment] 2022-06-15 10:22
The problem is still present in prestashop 1.7.8.6

in in the product title the is a apostrophe >>  ’
the generate url button doesn't remove it, and when save button is clicked you get error the url is invalid, so you have to remove manually form url in order to get link ad product saved

**Comment by Betafer** [comment] 2022-08-21 15:50
the problem is also present with prestashop 1.7.8.7 with ' in product name

**Comment by Betafer** [comment] 2024-04-05 12:43
This problem is still present in Prestahop 8.1.5

**Comment by Betafer** [comment] 2024-09-19 21:25
Problem is still present in prestashop 8.1.7
If you use ΐ in the name of product and make url you got error

**Comment by Betafer** [comment] 2024-09-23 13:22
Also in prestashop 8.1.7 the character: – 
in product it is inserted into the rewrite url and generates the error
