### ISSUE TITLE
Email Theme navigation menu link is not shown for other permission profiles than admin

### ISSUE THREAD

**Issue by RaimondasSapola** [PrestaShop/PrestaShop#17367] opened 2020-01-27 07:35 UTC
**Describe the bug**
Email theme page link in navigation is shown only for admin permission profile. Also some strange behavior if trying to open page with url. If not full permission given it redirects to dashboard. Some further investigation may be required.

**To Reproduce**
1. Go to Back office as administrator
2. Create new employee with mail theme permissions
3. Go to Back office as new employee
4. In Design navigation section there is no mail theme link

**Screenshots**
![Screen Shot 2020-01-27 at 9 22 39 AM](https://user-images.githubusercontent.com/17932157/73156557-d9442900-40e6-11ea-93c3-556853b563e5.png)
![Screen Shot 2020-01-27 at 9 30 17 AM](https://user-images.githubusercontent.com/17932157/73156815-af3f3680-40e7-11ea-8385-5cc70b6f48e8.png)
It seems that PS doesn't allow to save parent Email Theme permissions.
![Screen Shot 2020-01-27 at 9 31 33 AM](https://user-images.githubusercontent.com/17932157/73156861-d5fd6d00-40e7-11ea-8e54-b6a88a6231e8.png)
When only Email theme permissions are set it shows design menu section but because there is no item in it that should be Email Theme, Design section doesn't behave like a dropdown so it doesn't work correctly. See above

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-01-27 10:17
Hi @RaimondasSapola,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16696 to fix the issue.
It is fixed in the PS1.7.6.3.
Your ticket is a duplicate of #16337
So, I close it.
Thanks!

PS: I tried with 1.7.7.x => OK.
https://drive.google.com/file/d/1DjinADYdHEPR-TQoHJqdIkQCJy1SBRkT/view

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-27 10:17
Duplicate of #16337

**Closed as completed by khouloudbelguith** 2020-01-27 10:17 UTC
Labels: Duplicate, Permissions, Email theme
