### ISSUE TITLE
The design of the droplists is not harmonized

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30631] opened 2022-12-21 10:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

In the BO, you can currently find 3 types of design for droplists. This is not aesthetic and there is no reason for these differences in design.

example :
https://watch.screencastify.com/v/iE2TtDElD8OxlzxBqqHX

here are the droplists concerned by the problem
![image](https://user-images.githubusercontent.com/112863083/208881031-4d2cf658-6c95-422a-b817-f96e29357940.png)
![image](https://user-images.githubusercontent.com/112863083/208881050-ca571fc4-d9b1-4238-bd77-15c443de9571.png)
![image](https://user-images.githubusercontent.com/112863083/208881509-c719fd9c-391e-4de3-b2af-012494e9ac05.png)
![image](https://user-images.githubusercontent.com/112863083/208881533-096512fa-3495-469b-abcf-85869143052c.png)
![image](https://user-images.githubusercontent.com/112863083/208881560-b64829e7-dd56-4496-a0fc-fda001d4088b.png)
![image](https://user-images.githubusercontent.com/112863083/208881594-11bec53d-4c42-4e6b-bbd2-8b8627a36b45.png)
![image](https://user-images.githubusercontent.com/112863083/208881617-382e0e64-ee9e-4761-88e0-4ce3130959ee.png)
![image](https://user-images.githubusercontent.com/112863083/208881632-6684c016-22fc-4a2f-9a5f-8da93d092b55.png)
![image](https://user-images.githubusercontent.com/112863083/208881657-3634a608-ca7d-4185-8b84-f837ef8ce38f.png)
![image](https://user-images.githubusercontent.com/112863083/208881669-516f864e-f3d7-4530-9e82-0df1ce8413e6.png)
![image](https://user-images.githubusercontent.com/112863083/208881686-721a488c-c90b-45ae-9f51-17c3b6670954.png)
![image](https://user-images.githubusercontent.com/112863083/208881708-106bdb50-b092-4538-b5dd-a6db7bcd1688.png)
![image](https://user-images.githubusercontent.com/112863083/208881727-bb6c2337-7b95-4156-8f47-5126a38ff9db.png)
![image](https://user-images.githubusercontent.com/112863083/208881744-47aeffa3-41bd-4254-9be0-d04066e935ea.png)
![image](https://user-images.githubusercontent.com/112863083/208881760-9e193f9a-0884-4ee7-9019-d4f21d9d83de.png)
![image](https://user-images.githubusercontent.com/112863083/208881783-c02b0636-3621-4580-8545-bb123541fcf7.png)
![image](https://user-images.githubusercontent.com/112863083/208881801-54225b20-6164-454a-bc23-2067a58565d4.png)
![image](https://user-images.githubusercontent.com/112863083/208881819-7f334e4c-f9b6-4286-af34-bdc8d722aea6.png)

### Describe the solution you'd like

All the BO droplists should all have the same design (blue background)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment] 2022-12-21 11:45
This is normal. To simplify, we have three designs of dropdown:
- Legacy pages selectbox (this will vanish in time when all is migrated)
- Modern pages selectbox
- Language switch bootstrap dropdown

Selectbox design depends on the browser and its styling options are limited, sometimes completely ignored by a browser. And dropdown is a completely different element. Even in clean boostrap 4, it's different:
- https://getbootstrap.com/docs/4.6/components/forms/
- https://getbootstrap.com/docs/4.6/components/dropdowns/

**Comment by Hlavtox** [comment] 2022-12-21 11:59
Closing, there are much more differences between legacy and modern, it will never be the same. 👍

**Comment by paulnoelcholot** [comment] 2022-12-21 12:51
Hi @Hlavtox, 
The problem is that on some pages, there are two different droplists, and from a user point of view, this is not normal. For example on this page which is a migrated page:

Page for terms and conditions = New droplist
Gift-wrapping tax = Old droplist

![image](https://user-images.githubusercontent.com/112863083/208909425-f5cf7ce5-2d1b-4aa7-84fa-294985940ec9.png)

**Comment by Hlavtox** [comment] 2022-12-21 13:00
Yes, this is an issue, I agree. It should be using selectbox, not dropdown in configuration forms. 👍

EDIT: Well, not exactly.. In general configuration, there is also one input as a dropdown with a search bar, and it looks different. But thats normal. It just won't look the same as a selectbox.

![elements](https://user-images.githubusercontent.com/6097524/208911851-5fe8107d-a760-4db2-94f2-361cbbbcac46.png)

**Comment by kpodemski** [comment] 2022-12-21 13:05
I suggest clarifying that in the issue description to avoid situation where somebody will have to go through legacy styles to improve selectboxes.

**Comment by HanaRebaiQA** [comment] 2022-12-21 13:35
Hello @paulnoelcholot 

Thanks for your suggestion and for all provided details. But, your are asking here about the dropdowns styles and formats ? Or, like you have mentioned in the expected behavior, about the Blue background ?

- I think if it's for the first point, i agree with this case and we should ping the UX design for it. For the other cases, there are differences between the legacy page and the migrated one.

![image](https://user-images.githubusercontent.com/92912932/208917051-3bb9c6a0-00f9-42bd-9864-4e2ac3faf1bc.png)

- But, if it's about the blue background, this behavior is displayed when you clicked on the field. 

https://user-images.githubusercontent.com/92912932/208917654-df0ff5e4-74a5-4b04-93e8-7954a7522685.mp4


What do you think ? 

Thank You!

**Comment by hibatallahAouadni** [comment] 2023-01-10 09:34
Hello @paulnoelcholot 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-01-10 09:34 UTC
Labels: Feature, BO, Design, Invalid
