### ISSUE TITLE
Debug profiling not using overriden methods by module

### ISSUE THREAD

**Issue by acalvomanxa** [PrestaShop/PrestaShop#36988] opened 2024-09-20 11:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, I'm trying to activate the profiler in my shop, but when I do so, it throws this error
![image](https://github.com/user-attachments/assets/1b8c1b9e-268f-4342-aa5c-c39599cc48b4)

The error disappears whenever I disable the _PS_DEBUG_PROFILING, while still having PS_MODE_DEV to true. It seems like whenever I activate the DEBUG PROFILING, the Tools Class overriden methods by a module are not detected anymore.

### Expected behavior

Since with debug mode the Tools overriden methods are detected, with profiler enabled it should be no different

### Steps to reproduce

Create a module that overrides the Tools class, and adds methods inside of it
Enable Debug Mode
Enable Profiler Debug Mode
Go to a page where you have a controller that uses said method
Crash

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

**Comment by acalvomanxa** [comment] 2024-09-26 07:20
Solved by commenting out this line in the configuration, but this shouldn't be marked as solved.

![image](https://github.com/user-attachments/assets/ed24e9e3-134d-45aa-9965-e07febf2c8b6)

**Comment by florine2623** [comment] 2024-10-22 08:32
Hello @acalvomanxa ,

Could you send an example module so that we can test your issue ?
We will try to reproduce your issue with your module and PS 9.0.x. FYI, if it is indeed reproduced, it will be fixed in 9.0.x, not 1.7.8.x.

Waiting for your feedback,
Thanks!

**Comment by florine2623** [comment] 2024-11-13 10:17
friendly reminder @acalvomanxa

**Comment by paulnoelcholot** [comment] 2024-12-10 12:33
Hello @acalvomanxa,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-12-10 12:33 UTC
Labels: Bug, BO, Can't reproduce, Performance
