### ISSUE TITLE
Admin -> Catalogue -> "Stocks" redirects to frontpage / 404

### ISSUE THREAD

**Issue by KristianI** [PrestaShop/PrestaShop#10312] opened 2018-09-06 11:32 UTC
The bug is described in http://forge.prestashop.com/browse/BOOM-5869

BUT it even happens on a clean prestashop v.1.7.4.2 install.
Tried it on a clean database.

Got no warning etc., but clicking the "Stocks" button simply redirects to customer facing frontend.

**To Reproduce**
1. Login to manager/admin
2. Click "Catalogue" -> "Stocks".
3. I am now on the customer facing frontend instead of an admin stocks module.

**Screenshots**
Clicking "Stocks"
![image](https://user-images.githubusercontent.com/1626966/45154801-1699d500-b1d9-11e8-86a1-c046bd4eb552.png)
Next thing  I see is this:
![image](https://user-images.githubusercontent.com/1626966/45154817-231e2d80-b1d9-11e8-87f6-653a0739ffbe.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2018-09-06 11:34
Hi @KristianI,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-10 11:09
Hi @KristianI,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-10 11:09 UTC
Labels: BO, No change required

**Comment by antonioreyna** [comment] 2018-11-18 06:52
i have the same issue its a clean install of newest release

**Comment by KristianI** [comment] 2018-11-18 16:02
My issue was that I used nginx. Presta shop is preconfigured for Apache.

**Comment by khouloudbelguith** [comment] 2018-11-19 13:48
Hi @KristianI, @antonioreyna,

If you are running a Nginx server on your shop, you may need to configure your virtual host for running properly with PrestaShop. We provide an example here: https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist
Thanks!
