### ISSUE TITLE
Croatia - wrong Zone

### ISSUE THREAD

**Issue by malcek** [PrestaShop/PrestaShop#18578] opened 2020-04-10 14:28 UTC
#### Describe the bug

Croatia is in EU from 1. julija 2013 and it should be placed into Europe zone when made fresh install. Right now it is in Europe (non-EU) zone

#### Expected behavior

Should be placed in Europe zone

* PrestaShop version: 1.7.6.4
* PHP version: N/A

**Comment by florine2623** [comment] 2020-04-10 15:03
Hi @malcek ,
Thanks for the recommandation.
I will let our Product Team know.
Thanks !

**Comment by florine2623** [comment] 2020-04-10 15:16
Hi @PrestaShop/prestashop-product-team !

This request seems very relevant, what do you think ?

Thanks !

**Comment by khouloudbelguith** [comment] 2020-04-10 15:22
Hi, 

it is duplicate of https://github.com/PrestaShop/PrestaShop/issues/9630
we need to close this issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-10 15:23
Hi @malcek,

Your ticket is a duplicate of #9630
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-04-10 15:24
Duplicate of #9630

**Closed as completed by khouloudbelguith** 2020-04-10 15:23 UTC
Labels: Feature, BO, Duplicate, Locations, 1.7.6.4
