### ISSUE TITLE
Deactivation of non built-in modules

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#14779] opened 2019-07-19 15:55 UTC
**As a user making a major upgrade, I want to be able to disable my non built-in modules before the upgrade to be able to start the upgrade and ensure its success.**
When doing a major upgrade, in the pre-upgrade step (mandatory part), we should check that all installed and non built-in modules are well disabled. If it's not the case, the user should not be able to lunch the upgrade.

**As a user making a minor or patch upgrade, I want to be able to choose if I want to disable my non built-in modules before the upgrade or to keep them enabled.**
When doing a minor or a patch upgrade, in the pre-upgrade step (recommended part), we should check if the non built-in modules are disabled or not. If it's not the case, the user should be able to lunch the upgrade.
Disabling the non built-in module is not mandatory, it should be done only if the user enabled the option to disable them.

**Comment by Quetzacoalt91** [comment] 2019-07-22 07:40
> At the beginning of the upgrade process, all installed modules have to be disabled and move to another folder to prevent them from being used once the upgrade has been done.

Keep PrestaShop modules enabled to allow their data to be migrated. :)

**Comment by MatShir** [comment] 2023-04-26 09:24
duplicate of https://github.com/PrestaShop/PrestaShop/issues/25649

**Closed as completed by MatShir** 2023-04-26 09:24 UTC
Labels: Waiting for PM, Feature, BO, Autoupgrade, PR available
