### ISSUE TITLE
Error 500 / mail not sending 

### ISSUE THREAD

**Issue by VirginieFeyaerts** [PrestaShop/PrestaShop#33579] opened 2023-08-09 07:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I can't make an order without having a 500 error. It seems to be a conflict with swiftmailer. 

### Expected behavior

[](url)
![Capture d’écran 2023-08-09 091542](https://github.com/PrestaShop/PrestaShop/assets/141812569/a422d558-a3ef-4da8-a1a7-8c72aaf18b80)

In Debug mode, this is what it says. 

Can anyone help me  ? 

I tried de SMTP mode but it seems to not be working either. 

### Steps to reproduce

1. Make an order
2. The order can't go to the end because i have a 500 error

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.3.30

### If your bug is related to a module, specify its name and its version

Swiftmailer

**Comment by Hlavtox** [comment] 2023-08-09 07:56
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22262, https://github.com/PrestaShop/PrestaShop/issues/25380 etc.

**Comment by aniszr** [comment] 2023-08-09 10:52
Hello @VirginieFeyaerts 

Could you please try with an other PHP version (7.4 for exemple ), the 8.3.3 version may be not compatible with PS 8.0.4.


Otherwise this issue is a duplicate of [#25380](https://github.com/PrestaShop/PrestaShop/issues/25380).

You can find more help in this [comment](https://github.com/PrestaShop/PrestaShop/issues/22262#issuecomment-795599209) related to this [issue](https://github.com/PrestaShop/PrestaShop/issues/22262)

To be informed when it's fixed, please subscribe to the issue mentioned above.


Thank you

**Closed as completed by aniszr** 2023-08-09 10:52 UTC
Labels: Bug, Duplicate, Invalid
