### ISSUE TITLE
No email (order confirmation) to customer when ordering.

### ISSUE THREAD

**Issue by simonswif** [PrestaShop/PrestaShop#15715] opened 2019-09-26 14:48 UTC
Hope You can help!

I use Prestashop 1.7.6.1.

When a customers makes an order, they don't get any order confirmation by email, But I do.

Also, if they send a message through contact-page, I dont get an email alert.
Sure, I can check Backoffice. But I also want an email, when a customer have sent a message.

I have installed mailalert v2.1.1 and it dosen't work.

I have tried the Test-button. And that works fine.

I hope someone can help!

**Comment by PululuK** [comment] 2019-09-26 14:57
Hello @simonswif 

In the **Back office > Advanced parameters > E-mail** you have checked that your mails are going well?

You must also check if there is an email template for the language concerned.

**Comment by khouloudbelguith** [comment] 2019-09-26 14:58
Hi @simonswif,

Thanks to check sending the test email  from the Bo and feedback.

Thanks!

**Comment by simonswif** [comment] 2019-09-26 15:04
I bought a template/theme for my shop and contacted the developer. They said that it is a Prestashop issue.

I also tried to send a screenshot of the informations from BO regarding the email, and they said that it all looked fine.

What to do?

**Comment by simonswif** [comment] 2019-09-26 15:05
Also.. I have contacted my host, and they also said that it looked fine.

**Comment by khouloudbelguith** [comment] 2019-09-26 15:15
@simonswif 
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by simonswif** [comment] 2019-09-26 15:27
I am not much of a coder, and I don't understand PHP and JS very well, but I have attached some screenshots of my informations.

When a customers makes an order, they don't get any order confirmation by email, But I get one.

And then some time later, I get an email (see attached) that the email can not be delevered to the customer.

![kundeservice](https://user-images.githubusercontent.com/55844683/65701935-7aac6700-e082-11e9-8f85-2b69ecefe08c.jpg)
![mail](https://user-images.githubusercontent.com/55844683/65701936-7aac6700-e082-11e9-837e-f024cd814f66.jpg)
![testmail](https://user-images.githubusercontent.com/55844683/65701939-7b44fd80-e082-11e9-91dc-5c98348950a6.jpg)

**Comment by khouloudbelguith** [comment] 2019-10-01 16:01
@simonswif, as you can see in your "no-Replay" mail
![image](https://user-images.githubusercontent.com/16067358/65978583-dfddcf00-e46b-11e9-918b-4dd95b21245e.png)
This is an issue related to your server & not PrestaShop.
Thanks to check with your host again.

PS: In my case, it is OK
![image](https://user-images.githubusercontent.com/16067358/65979340-051f0d00-e46d-11e9-8b59-5bf6202760fa.png)


Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-31 07:35
Hi @simonswif,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-31 07:35 UTC
Labels: Email, No change required, 1.7.6.1
