### ISSUE TITLE
 ps_themecusto module keeps loading for ever on fresh 1.7.6.5

### ISSUE THREAD

**Issue by hassan-1985** [PrestaShop/PrestaShop#19346] opened 2020-05-26 08:23 UTC
### Describe the bug

ps_themecusto module keeps loading for ever!

The problem is that this "pages customization" is not functioning at all (circle 2 in the attached pic). It seems the module is still loading for ever (circle 1 in the attached pic).

I cannot customize the pages, when put the crosser on the menu or slider or whatever, nothing is changing (circle 3 in the attached pic). 

Please help?#### Expected behavior

I expected to see the menu to drop down when clicking on "menu" or "others" in the "Pages configuration".

#### Steps to Reproduce

I reinstalled without any success!

**Screenshots**
![Untitled pictured](https://user-images.githubusercontent.com/65922523/82877536-fd9ffd00-9f42-11ea-8a82-bec3a3d4e55d.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: I tried changing from 5.6 to 7 to 7.1 to 7.2 to 7.3 and nothing changing

**Comment by sarahdib** [comment] 2020-05-26 13:37
Hello @hassan-1985 

I didn't reproduce the issue, you can see my screenrecord.
https://drive.google.com/file/d/1p0Pz6Eq-sYu_JOC6_0pQF57jHZ9q7SoT/view

Which module version did you use ?

Thank you

**Comment by hassan-1985** [comment] 2020-05-27 06:31
Hi Sarahdib, 
I used this https://github.com/PrestaShop/ps_themecusto,

**Comment by florine2623** [comment] 2020-05-28 10:09
Hi @hassan-1985 ,
I can't reproduce your issue on fresh install 1.7.6.5 with module ps_themecusto v1.0.10.
Do you have any error on console ?
What happens when you enable DEBUG mode ?
Thanks!

**Comment by sarahdib** [comment] 2020-06-16 12:30
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-06-16 12:30 UTC
Labels: Theme custo, No change required
