### ISSUE TITLE
Scroll Blocking event on mobile product page in core.js:39

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#16311] opened 2019-11-07 12:16 UTC
**Describe the bug**
The mobile menu can freeze (unable to scroll) on a product page.

**To Reproduce**
1. Go to a product page in chrome
2. Change to mobile view (in browser), open de hamburger menu
3. Check the console

**Screenshots**
see screenshot from your demo site.

**Additional information**
PrestaShop version: lastest
![Capture](https://user-images.githubusercontent.com/3520123/68388091-29eb5c00-0160-11ea-903d-011d142c83e6.JPG)

**Comment by khouloudbelguith** [comment] 2019-11-07 13:00
Hi @sickboards,

Thanks for your report.
I did not manage to reproduce the issue with PrestaShop download v1.7.6.1.
the dem PrestaShop is not the latest version.
Did you try with a PrestaShop download?
You can try with this shop: http://melted-ring.machine-shuffle.prestashop.net/en/stationery/16-mountain-fox-notebook.html

Thanks!

**Comment by sickboards** [comment] 2019-11-07 13:07
Hello
Yes, I still see the same issue.
We noticed the issue on an iphone,
but I see it on win10/chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by khouloudbelguith** [comment] 2019-11-07 13:18
@sickboards, it is OK in my case, I tried with this shop http://melted-ring.machine-shuffle.prestashop.net/en/stationery/16-mountain-fox-notebook.html & windows 10 chrome v77 & an iPhone.
I attached a screen record
https://drive.google.com/file/d/12A_Yv-9_qwTD88khYQ9rLbaTEQQQW1ND/view
Thanks to check & feedback.

**Comment by sickboards** [comment] 2019-11-11 12:02
Hi, the link to your shop is not working unfortunately

**Comment by khouloudbelguith** [comment] 2019-11-11 12:07
@sickboards, this link should be used instantly, it disappears after a time.
Thanks to check with this link: http://foolish-things.machine-shuffle.prestashop.net/en/

Thanks!

**Comment by sickboards** [comment] 2019-11-11 13:26
Same issue is visible for me
![Capture](https://user-images.githubusercontent.com/3520123/68590584-3688f080-048f-11ea-8b34-41d2ce9f12a2.JPG)

**Comment by khouloudbelguith** [comment] 2019-11-11 16:27
@sickboards, I tried with this shop: http://snowy-girls.machine-shuffle.prestashop.net/en
I have only some deprecations
https://drive.google.com/file/d/13bzWlxzo7O2UC5FZvXS8UVYR9lHJftrC/view
Thanks to check & feedback.

**Comment by sickboards** [comment] 2019-11-13 07:14
Hi, I don't know what else I can say, it works for you but not for me,
good software should work for everyone. I don't know what the difference is, I tried it on multi pc's on my end and the result is the same, maybe it is location-based?
Can't you implement the suggestion offered?

**Comment by khouloudbelguith** [comment] 2019-11-13 10:19
@sickboards, what is your exact location?, I can use a fixed location.

Thanks!

**Comment by sickboards** [comment] 2019-11-13 16:02
den haag, the netherlands

**Comment by khouloudbelguith** [comment] 2019-11-13 16:14
@sickboards, I tried with this localization & it is OK
https://drive.google.com/file/d/1pjukjecpxLs-ZcOFAGBEiDYd1HIEQr8R/view

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-13 08:07
Hi @sickboards,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-13 08:07 UTC
Labels: Bug, FO, No change required, 1.7.6.0
