### ISSUE TITLE
Delete icon next to gift products

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14651] opened 2019-07-15 10:48 UTC
**Describe the bug**
A trash/delete icon is shown in cart sumamry next to products, that have been given for free as a gift.

PS: I think the severity of these two issues should be much higher. What's more important, migration of a BO page or a nonsense that customer sees? eg. #10766 #13002

**To Reproduce**
1. Setup a cart rule, that gives a product for free as gift. For example for orders over 100 EUR.
2. Fullfill the requirement.
3. Go to cart.
4. See trash icon next to the gift. Clicking the icon does nothing.

**Related issue**
The same applies for the trash icon next to cart rules that are permanent.
Issue: #12608

**Solution**
The trash icons should be hidden for products that are added as a gift and for cart rules that are applied automatically without a promo code.

**Additional information**
PrestaShop version: 1.7.6

**Comment by mariem-abid** [comment] 2019-07-15 12:27
Hi @Hlavtox,

I did not manage to reproduce the issue with PS:1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1HAHMzT8zARZv8VnvItONebqWo8OL5lrN/view

Thanks for check and feedback.

**Comment by Hlavtox** [comment] 2019-07-15 12:29
@mariem-abid Remove the voucher code, set quantity to 999999 and you will see the error.

Scenario: Dear customers, a free gift for all orders over 100 EUR!

**Comment by marionf** [comment] 2019-07-15 15:10
Hello @Hlavtox 

Your issue is a duplicate of  #9757, so I close it.
Please follow this issue.

**Closed as completed by marionf** 2019-07-15 15:10 UTC
Labels: Bug, FO, Duplicate, Cart rules, 1.7.6.0

**Comment by khouloudbelguith** [comment] 2020-10-08 09:44
Duplicate of #9757
