### ISSUE TITLE
Prestashop 1.7.6.1 can't see ean

### ISSUE THREAD

**Issue by copyact** [PrestaShop/PrestaShop#16120] opened 2019-10-25 11:45 UTC
Hello, I have imported some products to prestashop 1.7.5.1 and then upgraded it to 1.7.6.1.

Now, when I go to product page in back office I see 0 in ean13 field in every product. 
I checked in database that in table ps_products ean13 field is filled. 

When I enter some number  in ean13 in backoffice and update product I see that this field changes in databese but when I refresh that product page I see 0 in that field again.

I noticed that thing because I have installed module which generates XML from my products and there I saw ean13 field is 0 or 2147483647 and I was thinking why. But then I saw that I don't see this eans in backoffice.

Can you provide me a solution to this issue?

**Comment by sarahdib** [comment] 2019-10-25 12:36
Hello @copyact 

Thank you for your bug report.

I install a shop in 1.7.5. add an ean13 to a product then upgrade the shop. After upgrading I go to catalog > Product edit the product and the ean13 wasn't 0 but the one I set up before. 

https://drive.google.com/file/d/1BaXzTbThWRVV1sjB6JFj417dk5lAd2Ss/view

I didn't reproduce.

There was a problem during the upgrade or it was ok ?

**Comment by khouloudbelguith** [comment] 2019-11-25 07:36
Hi @copyact,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-25 07:36 UTC
Labels: Bug, BO, Taxes and Prices, No change required
