### ISSUE TITLE
Edit Product 1.7.4.4

### ISSUE THREAD

**Issue by tengav** [PrestaShop/PrestaShop#11373] opened 2018-11-13 18:16 UTC
**Describe the bug**

**To Reproduce**
If we go to the backend on products to edit or create new, we get an Error 500 loading also takes forever.

We have to say that we have nearly 90000 items in the shop and lots of attachments to PDF documents

It just seems that too many MySQL queries are being produced and it is coming to an end

INFO 19:12:54 User Deprecated: Implementing "Symfony \ Component \ HttpKernel \ DataCollector \ DataCollectorInterface" without the "reset ()" method is deprecated since Symfony 3.4 and will unsupported in 4.0 for class "Csa \ Bundle \ GuzzleBundle \ Data Collector \ GuzzleCollector ".
CRITICAL 19:12:54 php Uncaught Warning: PDO :: query (): MySQL server has gone away
CRITICAL 19:12:54 request Uncaught PHP Exception Symfony \ Component \ Debug \ Exception \ ContextErrorException: "Warning: PDO :: query (): MySQL server has gone away" at /var/www/vhosts/mediamv.de/httpdocs/ classes / db / DbPDO.php line 147

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version:1.7.4.4
PHP version: 7.1.24

**Comment by khouloudbelguith** [comment] 2018-11-14 08:17
Hi @tengav,

We are aware of this issue and we are working on it.
Now, this issue is in progress, it is assigned to our developer Jocelyn Fournier, he is working on it.
Thanks for your patience!
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-14 08:17
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2018-11-14 08:17 UTC
Labels: Duplicate
