### ISSUE TITLE
Product image changes when editing its accessory's attributes.

### ISSUE THREAD

**Issue by AloitR** [PrestaShop/PrestaShop#15150] opened 2019-08-19 08:00 UTC
**Describe the bug**
When changing an accessory's attribute it swaps the product image.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a product with an accessory.
2. Give the accessory an attribute.
3. Give both items an image.
4. Go to the product.
5. Preview the accessory ( from the product's page )
6. Change some accessory values and see how the product image gets swaped when closing the preview.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

Printer
![Printer](https://i.gyazo.com/2fd99b41e82f4cb09aeb2efbf1672b97.png)
Viewing an accessory
![Viewing an accessory](https://i.gyazo.com/ea933261f215ff6de69f9e4a9b370a8a.png)
You can see in the background how the product image changes when selecting a category
![You can see in the background how the product image changes when selecting a category](https://i.gyazo.com/0e6934b0dc9560040017a385315db3bb.png)
Product with the image swapped
![Product with the image swapped](https://i.gyazo.com/201fd8fcfb41b6101803a22f0e72f4c3.png)

gif:
![gif](https://i.gyazo.com/a224c990032a021ab2301b6b5c9e9221.gif)

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.0.22

**Comment by khouloudbelguith** [comment] 2019-08-19 09:54
Hi @AloitR,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9919
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-19 09:54
Duplicate of #9919

**Closed as completed by khouloudbelguith** 2019-08-19 09:54 UTC
Labels: Duplicate
