### ISSUE TITLE
h1 is used by news letter

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#17353] opened 2020-01-25 13:23 UTC
Hi,

on the homepage the news letter subscription is using a h1, which is basicly not recommened for the SEO. One h1 per page.

**Comment by demeldoo** [comment] 2020-01-25 13:23
Also, on product page is used h1 for the same module

**Comment by khouloudbelguith** [comment] 2020-01-27 08:27
Hi @demeldoo,

I did not manage to reproduce the issue with PS1.7.6.3 & PS1.7.6.2 & the ps_emailsubscription v2.5.1.
![image](https://user-images.githubusercontent.com/16067358/73159629-33dd8500-40e7-11ea-901e-47d59e9a5797.png)
What is the exact version of PS did you use? & what is the exact version of the ps_emailsubscription did you use?

Thanks!

**Comment by demeldoo** [comment] 2020-01-27 09:04
hi,

is it possible that the gdpr, europan rechtsichert module is creating this issue ?

i have this module for european market...

**Comment by khouloudbelguith** [comment] 2020-01-27 11:24
@demeldoo, I tried with gdpr module v1.1.3 & it is OK in the FO
https://drive.google.com/file/d/1edaKolojQm9KMq7TIpklwyFxhUWh6HWt/view

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-26 07:39
Hi @demeldoo, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-26 07:39 UTC
Labels: Improvement, FO, Traffic & SEO, Emailsubscription, No change required
