### ISSUE TITLE
In the combinazion page only few values can be selected

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11458] opened 2018-11-21 10:07 UTC
Hi
in the combination section, the attribute blocks show only limited values
in this case the colors are 177 but only few colors can be selected

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/48833932-c1537580-ed7c-11e8-9ce3-2f9020684009.png)

![2](https://user-images.githubusercontent.com/653230/48834032-05df1100-ed7d-11e8-82d7-c6a192485b1d.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

bye

**Comment by khouloudbelguith** [comment] 2018-11-21 11:36
Hi @maofree,

All the 177 colors are displayed in the left block, but you cannot select some of the colors?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Maofree** [comment] 2018-11-21 11:48
@khouloudbelguith  there are no errors
debug mode with no errors
there are some errors in javascript console
![1](https://user-images.githubusercontent.com/653230/48839370-8d338100-ed8b-11e8-872d-05f8354b27fb.png)

but I think it is not around this problem
the bugs are different

177 colors are set in Color attribute but from product page you can select only few of them not all

**Comment by khouloudbelguith** [comment] 2018-11-21 14:27
Hi @maofree,

I just found the problem in your shop, you have deleted the language which has id_language = 1.
Here's the PR: #10924 to solve the issue.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-21 14:27
Duplicate of #9627

**Closed as completed by khouloudbelguith** 2018-11-21 14:27 UTC
Labels: Bug, Duplicate, Attributes, Combinations
