### ISSUE TITLE
No default cover for products without images

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10767] opened 2018-09-29 01:03 UTC
**Describe the bug**
If you have product without images it should display some default cover, just like it was in PrestaShop 1.6. Now PrestaShop is trying to load image which does not exists.

**To Reproduce**
1. Edit product
2. Remove all photos, save it
3. Preview this product on listings and product page

**Additionnal information**
PrestaShop version: 1.7.0.0 to 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-01 10:23
Hi @kpodemski,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9926
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 10:23
Duplicate of #9926

**Closed as completed by khouloudbelguith** 2018-10-01 10:23 UTC
Labels: Duplicate
