### ISSUE TITLE
Issue after importing categories 

### ISSUE THREAD

**Issue by Kristianna1** [PrestaShop/PrestaShop#15442] opened 2019-09-06 10:31 UTC
Hello Guys!

I am using Prestashop  1.7.6.1,  recently we have imported categories an subcategories, now I want all categories to be shown in front-end and when I go to the module "Main Menue" there are no categories, even categories which were not imported but created manually. (unfortunately, I cant attached here screenshots).

Can anybody help with the issue!

Thank you very much,  for your help!

P.S. I am not developer, so please be so kind while giving you advice explain it in a simple language. ;)

**Comment by khouloudbelguith** [comment] 2019-09-06 10:39
Hi @Kristianna1,

Thanks for your report.
In the Back office => Main menu configuration => the List of categories are not displayed in the "Available items" section?

![image](https://user-images.githubusercontent.com/16067358/64422034-fbd39800-d09a-11e9-949b-f37cd229ed40.png)

Thanks!

**Comment by Kristianna1** [comment] 2019-09-06 10:43
> Hi @Kristianna1,
> 
> Thanks for your report.
> In the Back office => Main menu configuration => the List of categories are not displayed in the "Available items" section?
> 
> ![image](https://user-images.githubusercontent.com/16067358/64422034-fbd39800-d09a-11e9-949b-f37cd229ed40.png)
> 
> Thanks!

Hello, yes exactly!

**Comment by khouloudbelguith** [comment] 2019-09-06 10:51
@Kristianna1, what is the exact version of the main menu module did you use?
![image](https://user-images.githubusercontent.com/16067358/64422736-af895780-d09c-11e9-8a18-d14562e3744c.png)

Thanks!

**Comment by Kristianna1** [comment] 2019-09-06 11:10
> @Kristianna1, what is the exact version of the main menu module did you use?
> ![image](https://user-images.githubusercontent.com/16067358/64422736-af895780-d09c-11e9-8a18-d14562e3744c.png)
> 
> Thanks!

It is  v2.1.1(

**Comment by khouloudbelguith** [comment] 2019-09-06 11:12
@Kristianna1, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Kristianna1** [comment] 2019-09-06 11:28
> @Kristianna1, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
> 
> * host
> * server setup and configuration
> * PrestaShop version (source)
> * debug mode report
> * PHP error logs
> * apache error log
> * javascript console log
> * screenshots
> 
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!
Is it okay if I provide all the information tomorrow? 
Thank you very much for your help.

**Comment by khouloudbelguith** [comment] 2019-09-06 11:30
@Kristianna1, it is OK.
Tomorrow is a week-end.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-07 07:51
Hi @Kristianna1,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-07 07:51 UTC
Labels: Bug, BO, Mainmenu, No change required, 1.7.6.1
