### ISSUE TITLE
Canonical redirects for product pages do not work, gives duplicate content

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#18299] opened 2020-03-25 08:56 UTC
#### Describe the bug

Canonical urls do not work on product pages. You can change the link rewrite text to anything. If you use multishop, it will not redirect to www subdomain properly. This will give duplicate content in search engines.

#### Expected behavior

If a link is entered without www, it should redirect to www.
If a product link is entered with the wrong link rewrite text, it should redirect to the correct link.

#### Steps to Reproduce

1. Go to https://typical-wax.demo.prestashop.com/en/women/2-9-brown-bear-ddddd-sweater.html#/1-size-s
2.  See error (it should redirect to 
https://typical-wax.demo.prestashop.com/en/women/2-9-brown-bear-printed-sweater.html#/1-size-s

* PrestaShop version: 1.7.6.1+
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-03-25 11:29
Hi @Prestaworks,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1yWYKGNHtwdMXOTbZJlMbkAQqsuo-8pOZ/view?usp=sharing

Thanks to check and feedback.

**Comment by Prestaworks** [comment] 2020-03-25 11:42
Your movie show the issue. It should not keep ddddd in the url but instead do a redirect to the correct url that you get if you click on the link in the category page.

**Comment by khouloudbelguith** [comment] 2020-03-25 12:03
@Prestaworks, thanks for these clarifications.
I think the issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/17095#issuecomment-577130574

Thanks to check and feedback.

**Comment by Prestaworks** [comment] 2020-03-25 12:07
No.
My ticket is only for the product page and it is due to changes made to the canonicalRedirect function on that controller.
This change is what broke it I think
https://github.com/PrestaShop/PrestaShop/commit/ed02f13d5511a45d9568b0556bdab7dd73dbc66c#diff-514c245ae9a59a3ffd37a1e35d97f00c

**Comment by khouloudbelguith** [comment] 2020-03-25 14:02
@Prestaworks, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.4, PS1.7.6.3, PS1.7.6.2, PS1.7.6.1, PS1.7.6.0.
In the PS1.7.5.2, it is OK => https://drive.google.com/file/d/1zsVc5Bif-ib32RBLROB7vQlUsFF7C5Vb/view?usp=sharing
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Ping @jolelievre, this issue is related to this PR: https://github.com/PrestaShop/PrestaShop/pull/13009

Thanks!

**Comment by colinegin** [comment] 2020-03-31 17:16
Hello @Prestaworks ,

Thanks for your report !
Indeed, somehow the fix we have done to be able to have access to canonical urls has had an impact when rewriting the url. 

Nevertheless, after testing on 1.7.6.4, it seems that the canonical URL is still correctly used in the head, which is supposed to prevent duplicated content. What do you think about it ?

**Comment by Prestaworks** [comment] 2020-04-01 06:36
I don't think that is enough, if the 301 redirects is not working properly, you will most likely still get issues with the links.

**Comment by colinegin** [comment] 2020-04-02 16:58
Hello, 

After a deeper study with @jolelievre we have indeed found where and why was this bug introduced. We need to fix it for 1.7.6.5. 
Please find specifications related to SEO [here](https://github.com/PrestaShop/prestashop-specs/blob/master/seo-rules-and-behaviours.md), this will help us avoid future regressions on SEO.

For this regression in particular, we need to make sure that : 
- rewriting the name on the url of a product with combinations makes an automatic redirection to the correct combination url
- rewriting the url without the www makes an automatic redirection to the url with www if the domain was correctly defined with www.
- changing the attribute ID in the url with an incorrect ID makes an automatic redirection to the canonical url.

Do you confirm @jolelievre ?

Thanks !

**Comment by jolelievre** [comment] 2020-04-03 09:31
Yep, all good for me

**Comment by jolelievre** [comment] 2020-04-07 11:30
@colinegin I added one test to your list in the PR description:
`- edit the rewriting part in BO and refresh the product page -> you should be redirected to the same combination with new rewriting`

Maybe this should be added to the specs?

**Comment by colinegin** [comment] 2020-04-08 08:50
@jolelievre specs updated in "PrestaShop URLs and friendly URLs" paragraph ;)

**Comment by Progi1984** [comment] 2020-04-10 08:44
Fixed by #18493

**Closed as completed by Progi1984** 2020-04-10 08:44 UTC
Labels: Bug, PM ✔️, Minor, FO, SEO & URLs, Regression, Fixed, 1.7.6.0, 1.7.6.1, 1.7.6.2, 1.7.6.4
