### ISSUE TITLE
mails in customer service

### ISSUE THREAD

**Issue by Leous88** [PrestaShop/PrestaShop#11942] opened 2018-12-28 01:33 UTC
in customer service, the mail counter goes up and up without new messages, counts old and closed messages as new.

**Comment by khouloudbelguith** [comment] 2018-12-28 09:55
Hi @Leous88,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots
- What is the exact mail counter? 

Thanks!

**Comment by Leous88** [comment] 2018-12-28 16:46
sure, attached screenshots,
when updating, change the number of emails.
(which do not exist), if I click on the number redirects me to old mails, answered and closed...

prestashop 1.7.5.. problem since presta 1.7.0.0
debug mode : Notice en línea 1145 en archivo /home/sofitecc/public_html/on/controllers/admin/AdminCustomerThreadsController.php
[8] iconv(): Detected an illegal character in input string

![captura de pantalla 2018-12-28 13 43 30](https://user-images.githubusercontent.com/44386425/50521909-dcfe1a00-0aa6-11e9-9ff3-381a9cc186d3.png)


![captura de pantalla 2018-12-28 13 35 39](https://user-images.githubusercontent.com/44386425/50521791-226e1780-0aa6-11e9-9238-fd44fdea71aa.png)
![captura de pantalla 2018-12-28 13 35 25](https://user-images.githubusercontent.com/44386425/50521803-33b72400-0aa6-11e9-9829-26c6ed4c82c4.png)
![captura de pantalla 2018-12-28 13 35 15](https://user-images.githubusercontent.com/44386425/50521813-47fb2100-0aa6-11e9-9bc7-a8c400a5bf10.png)
![captura de pantalla 2018-12-28 13 34 53](https://user-images.githubusercontent.com/44386425/50521825-5a755a80-0aa6-11e9-8fd7-4d47e10fa7d8.png)

**Comment by khouloudbelguith** [comment] 2018-12-28 17:15
@Leous88 thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.5.0
I attached a video record.
https://drive.google.com/file/d/1R9CRV8AHSlx2qhUOE75cBKbh8jQBdZct/view
It will help us if you can attach a screen record.
Thanks!

**Comment by Leous88** [comment] 2018-12-28 17:23
https://www.dropbox.com/s/h7ktorkouc8afwe/Servicio%20al%20cliente%20%E2%80%A2%20Sofitec%20-%20Google%20Chrome%2028_12_2018%2014_19_14.mp4?dl=0

**Comment by khouloudbelguith** [comment] 2019-01-02 14:58
Hi @Leous88,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Also, thanks to check if the `iconv` extension is enabled on your server.
Thanks!

**Comment by Leous88** [comment] 2019-01-08 03:13
hi how i can get debug mode report ?
php error log and apache error log?

**Comment by Leous88** [comment] 2019-01-08 03:26
i can give you acces to server and admin profile of presta 1.7.5 if you want .. thanks !
Artículo | Detalle
-- | --
Paquete de alojamiento | plan1blue
Nombre del servidor | blue79
cPanel Versión | 70.0 (build 52)
Versión Apache | 2.4.27
Versión PHP | 5.4.45
Versión MySQL | 5.6.39-cll-lve
Arquitectura | x86_64
Sistema operativo | linux
Dirección IP compartida | 186.64.119.30
Ruta de acceso a Sendmail | /usr/sbin/sendmail
Ruta de acceso a Perl | /usr/bin/perl
Versión Perl | 5.10.1
Versión Kernel | 2.6.32-896.16.1.lve1.4.54.el6.x86_64

[cPanel - Información del servidor.pdf](https://github.com/PrestaShop/PrestaShop/files/2735099/cPanel.-.Informacion.del.servidor.pdf)

**Comment by khouloudbelguith** [comment] 2019-01-08 08:19
Hi @Leous88,

To turn on the Debug mode on PrestaShop 1.7, follow these steps:

1. Got to Advanced Parameters > Performance
2. In the Debug Mode section, set “Debug Mode” to “Yes”.
3. Click the “Save” button.

Sometimes you just don’t know what’s wrong: something’s not happening, that’s all.

That’s where log data can be helpful. They keep track of what is happening and allows to trace back to the moment when the issue happens.
There are several different log data that you can add as a file to your ticket:

1. - Server log:
1.1. - Apache: /var/log/apache/apache_error.log
1.2. - Nginx: /var/log/nginx/nginx_error.log
1.3. - IIS: %SystemDrive%\inetpub\logs\LogFiles
2. - PHP error log:
2.1. - Apache: /var/log/apache/php_error.log
2.2. - Nginx: /var/log/php-fpm/default/error.log
2.3. - IIS: %SystemDrive%\inetpub\logs\LogFiles
3. - Console log:
3.2. - Firefox and Chrome: press Ctrl+Shit+J or Cmd+Shift+J.
3.3. - Internet Explorer and Edge: press F12 then go to the Console tab.

If you don't have it, you should ask to your hosting provider.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-08 08:22
@Leous88, did you checked that the `iconv` extension is enabled on your server?

**Comment by khouloudbelguith** [comment] 2019-02-08 09:24
Hi @Leous88,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-08 09:24 UTC
Labels: Customer service, No change required
