### ISSUE TITLE
Fatal error when saving new memcached server in PS 1.7.6.0

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#14860] opened 2019-07-25 16:11 UTC
**Describe the bug**
After adding a new server, and testing the connection, click save and get the below error.  Any idea what this error is telling me?

![image](https://user-images.githubusercontent.com/19314911/61890176-8c2f9200-aecc-11e9-9f37-7b3da4eaf6ef.png)

**To Reproduce**
1. Install memcached - Tested in stalled correctly and listening on ip:port
2. Add new memcached server in Prestashop
3. Test connection details - OK
4. Click save.
5. Get error in screenshot.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
Ubuntu 18.04
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-26 07:40
Hi @roja45,

You have an exception into the cache file.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by roja45** [comment] 2019-07-26 14:15
Done, same result, /var/cache has full permissions.  This is a back office exception anyway, and the files indicated in the error just don't exist.

![image](https://user-images.githubusercontent.com/19314911/61957891-dde82300-af85-11e9-8376-eee604489bd3.png)

**Comment by roja45** [comment] 2019-07-26 14:18
The file it wants:
`[26-Jul-2019 15:13:06 Europe/London] PHP Fatal error:  require(): Failed opening required '/var/www/var/cache/dev/ContainerX7jeuzj/getDebug_FileLinkFormatter_UrlFormatService.php' (include_path='/var/www/vendor/pear/pear_exception:/var/www/vendor/pear/console_getopt:/var/www/vendor/pear/pear-core-minimal/src:/var/www/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/var/cache/dev/ContainerX7jeuzj/appDevDebugProjectContainer.php on line 1707`

The contents of the cache dir:
![image](https://user-images.githubusercontent.com/19314911/61958041-328b9e00-af86-11e9-9e9c-7687bfdf83c9.png)

**Comment by khouloudbelguith** [comment] 2019-07-31 11:43
@roja45, In my case, I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1KtvL14BtDOv-Nw4U5rxlqSoZ8rvtHvB3/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-08-30 07:20
Hi @roja45. 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-30 07:20 UTC
Labels: Bug, BO, Performance, No change required, 1.7.6.0
