### ISSUE TITLE
EU VAT still charged if VAT number provided

### ISSUE THREAD

**Issue by php-me** [PrestaShop/PrestaShop#10799] opened 2018-10-01 17:38 UTC
Hello,

In PS 1.6 when a store located in the UK had a customer from the EU e.g. France, it would charge them 20% tax (VAT). If the customer provided a VAT number, it would **not** charge them VAT (0% VAT).

However, in PS 1.7.4.2 this does not appear to be the case and VAT is charged for all the EU countries **regardless** of a VAT number being entered during checkout.

To recreate the issue, use a vanilla install and set store location to UK. Then place an order as a customer based in France (or any EU country). Provide a VAT number during the checkout and you will still be charged VAT on the final stage.

**Comment by prestamodule** [comment] 2018-10-02 07:04
See #10734 #9928, very critical indeed

**Comment by khouloudbelguith** [comment] 2018-10-02 08:01
Hi @php-me,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9928
So, I close it.
Thanks!

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-10-02 08:01 UTC
Labels: Duplicate
