### ISSUE TITLE
Unexpected behaviour with shipping price. It's free until payment (with any carrier). But shipping cost is correct after payment. Found the fix but it's also very strange.

### ISSUE THREAD

**Issue by Kharabet** [PrestaShop/PrestaShop#12009] opened 2019-01-03 12:52 UTC
**Describe the bug**
When you add something to cart - shipping is always free even if carrier is not free shipping.

![image](https://user-images.githubusercontent.com/14793248/50637369-74111900-0f62-11e9-9ec6-e7cb131ab5cf.png)

next step..

![image](https://user-images.githubusercontent.com/14793248/50637408-9acf4f80-0f62-11e9-8637-2633b7816c0b.png)

Only when you confirm the order you see actual shipping cost and final price:

![image](https://user-images.githubusercontent.com/14793248/50637483-d407bf80-0f62-11e9-85f1-8b41877331a0.png)

In this way my shop is not client-oriented :)

So I found the place where the shipping cost is calculating. https://github.com/PrestaShop/PrestaShop/blob/65dfa13e3876d711ed8e2779fedef89cdbaa08dc/classes/Cart.php#L3250

I decide to create a FileLogger and check which price is calculating. Then I opened a logfile and saw expected result. Then I open a cart and shipping was NOT FREE. I fixed it!
![image](https://user-images.githubusercontent.com/14793248/50637821-25fd1500-0f64-11e9-9e98-b803aa06c831.png)

![image](https://user-images.githubusercontent.com/14793248/50637784-f817d080-0f63-11e9-9113-dbb3e62eb3f5.png)

I have commented FileLogger lines and shipping cost was Free again..

I try to log shipping cost by myself with file_put_contents with FileLogger and get expected result:
![image](https://user-images.githubusercontent.com/14793248/50637936-9146e700-0f64-11e9-8b00-b32407c9afc5.png)
![image](https://user-images.githubusercontent.com/14793248/50637942-96a43180-0f64-11e9-8735-8c7e4da4e5f8.png)

I have commented FileLogger lines and my own log writes all zeros:
![image](https://user-images.githubusercontent.com/14793248/50637975-b9364a80-0f64-11e9-8a3c-c5304c8b54a7.png)

I tried to find out what FileLogger (https://github.com/PrestaShop/PrestaShop/blob/0d53d6b58b951ac364ad44671cf1ae9bf7ab6aed/classes/log/FileLogger.php) do with given arguments and got nothing. It just writes the message to specific file without any transformation or something else.   

So how does it works with this dumb fix? And why shipping cost appears in such a strange way without it? I see that people have the same problem and no one have solved it. 
For instance: https://www.prestashop.com/forums/topic/640460-where-to-change-text-for-free-shipping-prestashop-1724/#comment-2874066

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.3

**Comment by rdy4ever** [comment] 2019-01-03 13:48
Hi
This is strange. In my shop the shipping cost is displayed as soon as a product is added to cart:
![image](https://user-images.githubusercontent.com/12268701/50640900-f273b800-0f6e-11e9-8897-cbbf37d39159.png)
Do you use a contrib shipping module for DHL or did you just set it up in the Carriers page? If it's a module, then the problem is with the module and not Prestashop core and you should contact the module developer.

**Comment by khouloudbelguith** [comment] 2019-01-03 13:51
HI @Kharabet,

In my case, I did not manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
As @rdy4ever said, did you use any custom module for your carrier?
Thanks!

**Comment by Kharabet** [comment] 2019-01-03 14:03
Hi @rdy4ever

I use embeded shipping module which i get from this repo with Prestashop. It's just a carrier which I did set up in BO with DHL logo. 
This is out of the box prestashop. I didn't make any changes in code, except some css.

**Comment by Kharabet** [comment] 2019-01-03 14:07
Hi @khouloudbelguith ,

I had the same problem earlier with PS 1.7.4.x and then I decide to upgrade to PS 1.7.5 and problem was not solved. Then I reinstall PS from scratch and still get problem with shipping price.

I didn't use any custom carrier module. Only embeded in prestashop carrier module. It's the only carrier from my BO and it's not free shipping.
Thank you!

**Comment by khouloudbelguith** [comment] 2019-01-03 14:13
@Kharabet, in your BO => Shipping => Preferences, what is the carrier by default?
Thanks!

**Comment by Kharabet** [comment] 2019-01-03 14:18
@khouloudbelguith ,
![image](https://user-images.githubusercontent.com/14793248/50642188-0caf9500-0f73-11e9-8091-f4bf4567a4ae.png)

![image](https://user-images.githubusercontent.com/14793248/50642194-11744900-0f73-11e9-85fd-355d00772442.png)


As I said, this is the only carrier. So prestashop has no choice. The shipping price have to be not free.

**Comment by khouloudbelguith** [comment] 2019-01-03 14:33
@Kharabet, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Kharabet** [comment] 2019-01-04 13:00
Hi @khouloudbelguith 

I downgraded version of PHP from 7.3.0 to 7.2.13 and it works fine without any fixes.

**Comment by khouloudbelguith** [comment] 2019-01-04 13:08
Hi @Kharabet,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-04 13:08 UTC
Labels: Bug, FO, Shopping carts, Carriers, No change required, 1.7.5.0

**Comment by Alexxxxis** [comment] 2019-03-16 22:58
Hi @khouloudbelguith

Thank's a lot !!! PHP 7.2 and it works great !

Many thanks !

**Comment by Gipielle** [comment] 2020-08-24 20:01
I have similar problem with php 7.2.33 and ps 1.7.6.6, sometimes customers tells me that cart show free shipping but we don't have any free shipping option
