### ISSUE TITLE
Submit button being disabled and not enabled again normally 

### ISSUE THREAD

**Issue by rafaelsgritti** [PrestaShop/PrestaShop#15994] opened 2019-10-17 06:15 UTC
Pay button being disabled after missing data in payment method.

When using a credit card payment method, if I submit any wrong data it sets the submit button to disabled and doesn't return unless I retype data that I already entered as Credit card number and number of installments, or if I have the terms and conditions checkbox enabled, if I uncheck and check it again.

My website: loja.bradhoncursos.com.br

PrestaShop version: 1.7.6.0
PHP version: 7.2.23

**Comment by khouloudbelguith** [comment] 2019-10-17 08:39
Hi @zagalux,

I did not manage to reproduce the issue with PS1.7.6.0.I used the stripe module.
I attached a screen record
https://drive.google.com/file/d/1lg5QPVTQfabHO2M2tI7Lrmzq8jF1l_Mx/view
THanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-11-18 07:38
Hi @zagalux,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-18 07:38 UTC
Labels: FO, Payment, No change required, Checkout, 1.7.6.0
