### ISSUE TITLE
prestashop 8.1.0 1 click upgrade error

### ISSUE THREAD

**Issue by Emotion-Price** [PrestaShop/PrestaShop#34226] opened 2023-10-10 05:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hello.
please help with this error when trying to upgrade prestashop 8.1.0 to 8.1.2 using the 1 click upgrade.
![Capture](https://github.com/PrestaShop/PrestaShop/assets/147473203/9f452a8d-7d06-4d84-a19a-7111aada2b1a)
  setcookie('id_employee', $idEmployee, 0, $cookiePath); modules/autoupgrade/classes/chookie.php 
the requested log file is empty.

### Expected behavior

please help with this error when trying to upgrade prestashop 8.1.0 to 8.1.2 using the 1 click upgrade.
![Capture](https://github.com/PrestaShop/PrestaShop/assets/147473203/9f452a8d-7d06-4d84-a19a-7111aada2b1a)
  setcookie('id_employee', $idEmployee, 0, $cookiePath); modules/autoupgrade/classes/chookie.php 
the requested log file is empty.

### Steps to reproduce

i dont know.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Emotion-Price

**Comment by paulnoelcholot** [comment] 2023-10-10 09:31
Hello @Emotion-Price 

I tried to reproduce your issue but as you can see, I can't :
[1-Click Upgrade _ 1-Click Upgrade • the future (1).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/f98d9352-bddf-4c5b-b229-62ae788f38c2)

Can you give me a detailed step to reproduce please? What is your version of 1-Click Upgrade?

Thanks for your feedback

**Comment by Emotion-Price** [comment] 2023-10-10 10:11
Hi.
Thank you for your response.
Not sure if I can replay here.

I did a fresh install, and it showed this problem, i did install prestashop many times and tried the upgrade and it worked, but this time its showing this issue, I don't know what you mean "to recreate the problem" as I did nothing different from the other times when it was working.

Please is there any way to fix this?
Kind regards.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by paulnoelcholot** [comment] 2023-10-10 12:17
@Emotion-Price 

We are unable to correct a bug that is not reproducible, unfortunately. Nor can we afford to spend days investigating the problem. If you can't provide us with the precise steps to reproduce in order to reproduce the issue, we'll have to close this issue.

Thank you for understanding

**Comment by Emotion-Price** [comment] 2023-10-10 18:16
hello.
thank you for your replay.
im new to prestashop and i have no idea what do you mean with "reproducing the error"
the only way i understand to reproduce this error is to go to my back office and click upgrade, thats all i know.
please tell me how can i reproduce a problem like this, otherwise.
here is a new image with the message error (this shows up when i click the debug mode)
![Capture1](https://github.com/PrestaShop/PrestaShop/assets/147473203/57e224c8-ab33-42b7-b922-462d5d1d1950)

any help?
thank you.
kind regards.

**Comment by paulnoelcholot** [comment] 2023-10-11 12:28
Hello @Emotion-Price 

Ok, when I say "reproduce the error", I mean the steps to follow (step by step) to, from a new installation of the store, successfully find the bug.

For example :

1. BO > Improve > Modules > Module Manager
2. Set up 1-click upgrade
3. Click “Upgrade PrestaShop now!” »
4. See error

Do you see what I mean?

Thank you for your feedback

**Comment by paulnoelcholot** [comment] 2023-11-02 10:51
Hello @Emotion-Price,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2023-11-02 10:51 UTC
Labels: Bug, Waiting for author, 8.0.x, BO, Autoupgrade
