### ISSUE TITLE
ps_emailalerts unable to save email title translation, core translation is saved in theme

### ISSUE THREAD

**Issue by sitte** [PrestaShop/PrestaShop#11242] opened 2018-11-02 13:52 UTC
**Describe the bug**
I think it's all problem with translation destination (core/theme) :
ps_emailallert (example) title translations is not saved
editing core translation saves translation into theme dir not in module translation dir

**To Reproduce**
On fresh installation of 1.7.4.3 i install ps_emailallert module.
Go to international>translations>Email Translations>Body>Core>Polish (or other not english) >modify
Go to  ps_emailalerts>new_order>Email subject put here any translation > Save

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-11-02 13:56
Hi @sitte,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9599
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-02 13:56 UTC
Labels: Duplicate
