### ISSUE TITLE
 The email is already used, please choose another one or sign in 

### ISSUE THREAD

**Issue by Klixa-Web** [PrestaShop/PrestaShop#10306] opened 2018-09-06 07:27 UTC
**Guest checkout should be as simple as possible, even for returning customers**. The prestashop default message "An account using this email address has already been registered" is unlikely to make such customers happy.

In our research we have come across a number of entries on this topic with older PS versions. Unfortunately, there is nowhere a guide on how to fix the problem in PS 1.7. to older versions one should adapt the file "AuthController.php" 

Here is one thread:
https://www.prestashop.com/forums/topic/632869-the-email-is-already-used-please-choose-another-one-or-sign-in/

And here your bugfix to an older version: 
https://github.com/PrestaShop/PrestaShop/pull/5832

It's definitely not a theme related issue! Please fix bug ASAP!

**Comment by khouloudbelguith** [comment] 2018-09-06 07:48
Hi @

This issue needs to be specified.
Your ticket is a duplicate of #10122
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-06 07:49
Duplicate of #10122

**Closed as completed by khouloudbelguith** 2018-09-06 07:48 UTC
Labels: Duplicate
