### ISSUE TITLE
Multishop /// Module Linklist

### ISSUE THREAD

**Issue by thequickmick** [PrestaShop/PrestaShop#17723] opened 2020-02-18 16:57 UTC
**Describe the bug**
In Design -> Link Widget ->Add own Content
Its on different Shops the Same!

PrestaShop version: 1.7.6.3
PHP version: 7.2 - 7.3

**Comment by khouloudbelguith** [comment] 2020-02-19 07:53
Hi @thequickmick,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

Second, we are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9795
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-19 07:53
Duplicate of #9795

**Closed as completed by khouloudbelguith** 2020-02-19 07:53 UTC
Labels: Duplicate, Link widget
