### ISSUE TITLE
ERROR 500 when clearing cache

### ISSUE THREAD

**Issue by laurentmacca** [PrestaShop/PrestaShop#21906] opened 2020-11-13 12:48 UTC
#### Describe the bug

As soon a I clear cache it returns an ERROR 500. When I refresh admin page ERROR 500 disappears and cache has been cleared.
Thanks.
#### Expected behavior

Working as usual.

#### Steps to Reproduce

1. Go to 'Performances'
2. Click on 'Clear cache'
4. See error 500

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.31

**Comment by florine2623** [comment] 2020-11-13 12:53
Hi @laurentmacca ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
![Capture d’écran 2020-11-13 à 13 51 49](https://user-images.githubusercontent.com/16019289/99074146-81b07480-25b7-11eb-8d95-748f58d79ead.png)

You can check the PrestaShop [forum](https://www.prestashop.com/forums/) for more info.
We will close this issue.

Thank you

**Closed as completed by florine2623** 2020-11-13 12:53 UTC
Labels: No change required

**Comment by mrjcgoodwin** [comment] 2021-04-13 08:36
Hi @laurentmacca did you resolve this issue. We have the exact same problem with both 1.7.7.2 and 1.7.7.3.

Everything installs ok, but it's not possible to clear cache, change theme or save some settings in the performance screen without first getting an error 500 screen. Clicking reload clears the error and everything proceeds as normal but I cannot stop the 500 errors.

I have tried manually clearing all caches as per many threads on here and have checked file/folder permissions and file ownership too. Server settings all look healthy AFAIK and PHPPSInfo.php comes back all good also.

Getting the same problem with fresh copies of both 1.7.7.2 and 1.7.7.3.

Site is running on an NGINX/Apache VPS using Runcloud control panel. Pretty sure it's a caching problem but error messages aren't giving the clues needed to for me to trace.

Error in debug displays as:

`(1/1) FatalErrorException
Compile Error: ContainerUyu2frx\appDevDebugProjectContainer::load(): Failed opening required '/home/runcloud/webapps/project/var/cache/dev/ContainerUyu2frx/getPrestashop_UserProviderService.php' (include_path='/home/runcloud/webapps/project/vendor/pear/pear_exception:/home/runcloud/webapps/project/vendor/pear/console_getopt:/home/runcloud/webapps/project/vendor/pear/pear-core-minimal/src:/home/runcloud/webapps/project/vendor/pear/archive_tar:.:')

in appDevDebugProjectContainer.php line 2599`
