### ISSUE TITLE
Issue with gift vouchers with an empty cart

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#22270] opened 2020-12-07 11:40 UTC
#### Describe the bug
1st problem : when you have a cart rule offering a free product WITHOUT CODE (so automatically added), and you remove the NORMAL products from the cart, then the quantity of the free product is modified to 2 !!
When the voucher HAS A CODE, if you remove all the normal products from your cart, then the cart is emptied even if some vouchers are remaining. So the behavior is not the same depending if your voucher has a code or not... It should be the same.

2nd problem : it should be possible to have a cart containing only free products (with or without code set in the voucher !). So you should be able to access the cart summary and see the "voucher" field even if your cart is empty.

3rd problem : if you force the cart to contains only the voucher (add a normal product + add the voucher with code + remove the normal product from ps_cart_product table), then you can display the cart summary correctly. You can go until the shipping step but then you can't select the payment method, your cart is emptied and your are redirected to the homepage.

#### Steps To reproduce
1st problem : create a voucher with NO CODE, and offering a free product. Add a normal product to your cart, your cart now display your normal product + your free product. Remove the normal product clicking the "delete" icon, the quantity of the free product is updated to 2.

2nd problem : create a voucher WITH A CODE, and offering a free product. Add a normal product to your cart. Add your voucher to your cart. Now, remove the normal product clicking the "delete" icon. Your cart is emptied.

3nd problem : 
Add a normal product to your cart + the voucher with code + delete the normal product from the ps_cart_product table in database. Refresh the cart summary. Then try to go until payment step.

#### How to make it work
The only way I found is to add a real "0€ product" to the cart BEFORE applying the cart rule, and manage the addition/removal of this product (when necessary) through hookActionCartSave method in a module. So the cart always contains at least 1 real product, even if it's 0€ and everything works... But that's not a very nice solution... 
This problem has always existed... the cart SHOULD BE ABLE to contains only free products.

#### Additional information
Prestashop : 1.7.x
PHP : 7.1

**Comment by hibatallahAouadni** [comment] 2020-12-08 10:53
Hello @Prestaplugins 

So let's do it step by step :sweat_smile: 
### 1st problem: 
Yes I managed to reproduce with **PS1.7.6.7** but it **has been fixed** with the new release **PS1.7.7.0**, see attached screen records below:

**1.7.6.7:**
https://drive.google.com/file/d/10Yxj5iL4Hzih_byvyNm2drC3oCAFeTCj/view

**1.7.7.0:**
https://drive.google.com/file/d/1QX8pRSdeH8ViVCiClENcrn4D5kVAGFNd/view

---

### 2nd problem: 
**That's the normal behavior** :+1: you can not add a voucher to an empty cart.

https://drive.google.com/file/d/1_tZKoQh3NEVpLTxeXRLvzaU7zYWrMzCC/view

![image](https://user-images.githubusercontent.com/23308427/101474295-3f2a4f80-394b-11eb-8f7a-87e27f847206.png)

---

### 3nd problem:
**It is not advisable to manipilate the database manually!** It is not good to implement your solution like that, advise you to override the controller whose in charge.

Please check and feedback.

Thanks!

**Comment by Prestaplugins** [comment] 2020-12-08 11:12
Hello @hibatallahAouadni ,

Thanks for your test.
Ok for 1st problem, good to know. Can you give me the link with the fix ?

About the 2nd problem, yes that's how it works since the 1st version of Prestashop... but that's not normal !
I understand you can't add a voucher with a discount in % or fixed value, but you should be able to order a free product alone.
You can have a voucher for free product for many reasons, to resolve a litige, as a reward for your previous orders...
The cart should consider there's 1 product inside, instead of considerating it's empty.
That's an issue.

The 3rd problem was just here to explain that it seems the cart works properly if it contains only the free gift product + voucher until the payment step. So maybe that's not so hard to make it work...

**Comment by hibatallahAouadni** [comment] 2020-12-08 15:17
Hello @Prestaplugins 

> You can have a voucher for free product for many reasons, to resolve a litige, as a reward for your previous orders...
The cart should consider there's 1 product inside, instead of considerating it's empty.

What you sugguested here it's an improvement.
If you would like to discuss it as new feature, please **open a new issue with Feature template**, then the **product team** will take a look and consider your sugguestion.

> Can you give me the link with the fix ?

I don't know if this PR #16635 is the fix, but let's ask @Hlavtox, did your PR fix this issue?

So, I close this issue while waiting @Hlavtox feedback.

_**PS:** even the issue is closed, we will be glad to respond all your questions_ :smile: 

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-08 15:17 UTC
Labels: Bug, 1.7.x, FO, Discounts, No change required, Shopping carts FO
