### ISSUE TITLE
Sorting by price makes  the product list becomes empty.

### ISSUE THREAD

**Issue by Tonio1987** [PrestaShop/PrestaShop#18596] opened 2020-04-12 21:22 UTC
Hello,
Since a few hours, i have a problem on the front when I try to sort products by price.
When I clic on "Sort by price ASC or DESC", the product list becomes empty.

I read on github or on prestashop forum that this issue was known on old version of prestashop.
I have tried to empty the cache, reindex prices, reindex all items, disable and enable sub products etc. 

On old version, I have found a person which have modified php code by changing a limit in an SQL query but I think it's a bad way to do and I don't know if on my version of Prestashop it could work.

I am running on 
- Prestashop 1.7.6.4
- Module Navigation à facettes v3.5.0
My website is www.le-jardin-des-saveurs.com

I precise that the site is under construction.

Thanks in advance for your reply.

Best regards.
Anthony

**Comment by MatShir** [comment] 2020-04-15 16:15
Hi @Tonio1987
https://www.le-jardin-des-saveurs.com/13-epicerie?order=product.price.desc seems to work.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
 
To be sure the problem come from PrestaShop and not your envireonment.
You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by Tonio1987** [comment] 2020-04-15 21:22
Hello.

Thank you for your reply, here is the informations :
Host : le-jardin-des-saveurs.com
Server : OVH Performence1
Prestashop version : 1.7.6.4
Php version : 7.2

I am on a mutualized server so I can't access to Apache logs.

**Before clic** :
<img width="512" alt="Capture1" src="https://user-images.githubusercontent.com/708391/79390384-e0edce00-7f6f-11ea-95f4-5ac7796d8b0c.PNG">

**And after click** :
<img width="532" alt="Capture2" src="https://user-images.githubusercontent.com/708391/79390399-e8ad7280-7f6f-11ea-8b96-77207cfbc709.PNG">

**Comment by Tonio1987** [comment] 2020-04-15 21:23
In Chrome console, there is nothing indicated, so i think there is no error on client side.

**Comment by khouloudbelguith** [comment] 2020-04-16 15:13
Hi @Tonio1987,

I did not manage to reproduce the issue with PS1.7.6.4 and the ps_facetsearch module v3.5.0.
I attached a screen record
https://drive.google.com/file/d/1Mlk4QuXkWX87gCKWyJp2wgJYYS3MIq8f/view?usp=sharing
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by burakgit** [comment] 2020-04-17 08:46
Same issue with 1.7.6.4, May be it is related with With or Without TAX show option. Will you please @Tonio1987, tell us which type you are using ? i am using "without TAX " option. 

in adittion to this, after you order with price( so there is no product), if you refresh, drop down menu disappears. 

there is no php log info, also no warning. 

@khouloudbelguith 

Problem is before " ::after == $0 " line
![image](https://user-images.githubusercontent.com/32361879/79551424-5063da80-80a2-11ea-97b2-7bbc8b667e1b.png)

**Comment by burakgit** [comment] 2020-04-17 19:08
Fixed, 

please check this 
https://www.prestashop.com/forums/topic/990434-sort-by-price-not-working-on-ps-17/

Just go to modules manager faceted search -> rebuild price index...

**Comment by Tonio1987** [comment] 2020-04-17 20:58
Ok thank you; I will test tomorrow and let you know if it resolved my problrm.
Bert regards.

**Comment by Tonio1987** [comment] 2020-04-18 17:37
Ok, 

I confirm that the solution mentioned here works.
https://www.prestashop.com/forums/topic/990434-sort-by-price-not-working-on-ps-17/

The bug seems to be fixed for me by commenting these lines in file : ps_facetedsearch/src/Adapter/MySQL.php: : 

![image](https://user-images.githubusercontent.com/708391/79644841-c99b2480-81ab-11ea-8e62-5c15998b89df.png)

I hope there is nothing that will break in background.

Thank you.

**Comment by marionf** [comment] 2020-04-20 08:40
@Tonio1987 It's fixed after clicking on rebuild prices index ?

**Comment by Tonio1987** [comment] 2020-04-21 21:39
It's fix after having commented the lines 326 237 and 328 in ps_facetedsearch/src/Adapter/MySQL.php

**Comment by khouloudbelguith** [comment] 2020-04-23 14:03
Hi @Tonio1987,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16822
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-23 14:03
Duplicate of #16822

**Closed as completed by khouloudbelguith** 2020-04-23 14:03 UTC
Labels: FO, Duplicate, Faceted search
