### ISSUE TITLE
Prestashop 1.7.4.2 backofice multistore issue

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#12364] opened 2019-01-30 14:04 UTC
After login to the backoffice i see the issue following issue http://prntscr.com/me9tf3 .Please check the screenshot

**Comment by khouloudbelguith** [comment] 2019-01-30 14:13
Hi @pks891618,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10684 to fix the issue.
It is fixed in the last release 1.7.5.0.
Your ticket is a duplicate of #10469
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-30 14:16
@pks891618, in the console, the DOM error is not related to the multistore shop.
What is the exact issue with your shop multistore?
Thanks!

**Comment by pks891618** [comment] 2019-01-30 19:18
http://prntscr.com/meepif

Please check screenshot , this is the error occuring on 1.7.4.2

**Comment by khouloudbelguith** [comment] 2019-01-31 09:29
@pks891618, it is the [DOM] console issue, fixed in the PS1.7.5.0.
And you are using the PS1.7.4.2, is it?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-01 16:40
Hi @pks891618,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-01 16:40 UTC
Labels: Multistore, No change required, 1.7.4.2
