### ISSUE TITLE
Double order for a single cart

### ISSUE THREAD

**Issue by fabio-zetaweb** [PrestaShop/PrestaShop#17991] opened 2020-03-05 10:46 UTC
#### Describe the bug

Randomly orders are duplicated from a single cart. Orders have identical ref. code and customer details and the same datetime. The purchased items are distributed in both orders. In one of my case the customer had to pay shipping rate twice.

**Screenshots**

https://drive.google.com/file/d/10XrWi3z7cHLt56SmYWkz7Lt9EBUun2F8/view

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1.22

**Comment by PululuK** [comment] 2020-03-05 10:53
Hi @fabio-zetaweb 

This can happen if you have more than one carrier in your order. Could you please check if this is the case?

**Comment by fabio-zetaweb** [comment] 2020-03-05 11:12
Hello,

Yes, in both cases the carrier is different from an order to another. Why?

**Comment by khouloudbelguith** [comment] 2020-03-05 12:06
Hi @fabio-zetaweb,

Your ticket is a duplicate of #11115
Please follow: #11115
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-05 12:06
Duplicate of #11115

**Closed as completed by khouloudbelguith** 2020-03-05 12:06 UTC
Labels: Duplicate

**Comment by fabio-zetaweb** [comment] 2020-04-02 15:11
Hi,

it happened again! But this time the carrier is the same in both orders.

![order-compared](https://user-images.githubusercontent.com/56585945/78265506-d0b40880-7504-11ea-9ecb-bb39fa5d6152.jpg)
![order-01](https://user-images.githubusercontent.com/56585945/78265519-d4e02600-7504-11ea-8b7e-9e41b9b61043.jpg)
![order-02](https://user-images.githubusercontent.com/56585945/78265530-d90c4380-7504-11ea-8887-f5c7f2d49d79.jpg)

**Comment by khouloudbelguith** [comment] 2020-04-02 15:13
Hi @fabio-zetaweb,

Please follow: https://github.com/PrestaShop/PrestaShop/issues/11115
It is still open.

Thanks!
