### ISSUE TITLE
Remove Free Shipping on (modal, total and sub total carts)

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#18449] opened 2020-04-03 01:04 UTC
When a use gets in for first time to the store an has no login (navigate as a guess) and add to the carta product, on the summary modal say free shipping.

The use have not type where he is or where to ship the product, it should not say free shipping would be better to say "to be quote"?

So we suggest this changes:

1. on themes/classic/modules/ps_shoppingcart/modal.tpl    line 60

<p><span>{l s='Shipping:' d='Shop.Theme.Checkout'}</span>&nbsp;
<span class="value">
  {if $customer.addresses|count > 0} #to validate if the is an address to ship to
    {$cart.subtotals.shipping.value}{hook h='displayCheckoutSubtotalDetails' subtotal=$cart.subtotals.shipping}
  {else}
   {l s='Por Cotizar' d='Shop.Theme.Checkout'}
  {/if}
</span></p>

![shipping1](https://user-images.githubusercontent.com/46203943/78313602-acb8ed00-752d-11ea-9734-44129d45aa06.png)

2. on themes/classic/templates/checkout/_partials/cart-detailed-totals.tpl line 39

	   {if $subtotal.type === 'shipping'}
            {if $customer.addresses|count > 0}#to validate if the is an address to ship to
              <span class="value">
                {$subtotal.value}
              </span>
              <div><small class="value">{hook h='displayCheckoutSubtotalDetails' subtotal=$subtotal}</small></div>
            {else}
              <span class="value">
               {l s='Por Cotizar' d='Shop.Theme.Checkout'}
              </span>
            {/if}
          {else}
            <span class="value">
              {if 'discount' == $subtotal.type}-&nbsp;{/if}{$subtotal.value}
            </span>
          {/if}

![shipping2](https://user-images.githubusercontent.com/46203943/78313610-b4789180-752d-11ea-8c82-3c3798e1e16a.png)

3. on themes/classic/templates/checkout/_partials/cart-summary-subtotals.tpl line 35

<span class="value"> 
          {if $subtotal.type === 'shipping'}
            {if $customer.addresses|count > 0}
              {$subtotal.value}
            {else}
              {l s='Por Cotizar' d='Shop.Theme.Checkout'}
            {/if}
          {else}
            {$subtotal.value}
          {/if}
        </span>
 
![shipping3](https://user-images.githubusercontent.com/46203943/78313617-bc383600-752d-11ea-9063-0f49ba4f6bd6.png)

![shipping4](https://user-images.githubusercontent.com/46203943/78313624-c22e1700-752d-11ea-9a8b-c9c094cce3cf.png)

**Comment by khouloudbelguith** [comment] 2020-04-03 07:27
Hi @msaustral, 

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13517 to fix the issue.
It is fixed in the next release PS1.7.7.0.
Your ticket is a duplicate of #10739
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-04-03 07:27
Duplicate of #10739

**Closed as completed by khouloudbelguith** 2020-04-03 07:27 UTC
Labels: Duplicate
