### ISSUE TITLE
Zoho Mail Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by Digital5253** [PrestaShop/PrestaShop#18090] opened 2020-03-11 12:50 UTC
#### Describe the bug

I am using prestashop ecommerce and it is giving me below error when getting notifications from the system.

#### Expected behavior

============ Forwarded Message ============
From : MAILER-DAEMON@mailchannels.net
To : info@appcity.co.tz
Date : Tue, 10 Mar 2020 22:29:50 +0300
Subject : Undelivered Mail Returned to Sender
============ Forwarded Message ============
This is the mail system at host relay.mailchannels.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<info@appcity.co.tz>: host mx.zoho.com[204.141.32.121] said: 554 5.2.3
MailPolicy violation Error delivering to mailboxes (in reply to end of DATA
command)
Reporting-MTA: dns; relay.mailchannels.net
X-Postfix-Queue-ID: 7AF42260F2A
X-Postfix-Sender: rfc822; info@appcity.co.tz

Arrival-Date: Tue, 10 Mar 2020 19:29:46 +0000 (UTC)

Final-Recipient: rfc822; info@appcity.co.tz

Original-Recipient: rfc822;info@appcity.co.tz

Action: failed
Status: 5.2.3
Remote-MTA: dns; mx.zoho.com
Diagnostic-Code: smtp; 554 5.2.3 MailPolicy violation Error delivering to
mailboxes

#### Steps to Reproduce

Responce from Zoho
On analysis, we observe that your emails from prestashop ecommerce for your domain were considered as potential spoofed mails and were rejected by our Antispam filters.

 

To resolve this, please contact prestashop ecommerce support team and get their IP address or range from which emails are sent to your address. Please include it along with Zoho's hostname in your existing SPF record for your domain.

​
Refer this help document for further details.

  

Further, please contact the application support and ensure that proper DKIM signature is configured for the emails sent from prestashop ecommerce. Once done, the emails will be delivered without any issues.

 

We hope this helps.

Sincerely, 
Karthikeyan S - Zoho Cares.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-03-11 13:13
Hi @Digital5253,

Spams on 1.6 are caused by the sendtofriends module. (1.6 versions have token protection, more informations: http://build.prestashop.com/news/fighting-against-spamming/)

Spams on 1.7 are caused by the contactform, here are the PRs resolving this issue:

contactform module:
https://github.com/PrestaShop/contactform/pull/19 => fixed in the `contactform` module v4.0.0.

ps_emailgenerator:
https://github.com/PrestaShop/ps_emailgenerator/pull/17 => fixed in the last release of `ps_emailgenerator`
 
PrestaShop:
https://github.com/PrestaShop/PrestaShop/pull/8873 fixed in the PS1.7.3.1.

You can follow this link:
http://build.prestashop.com/news/fighting-against-spamming-again/

The very best protection against such spam is a reCAPTCHA.

Thanks to check & feedback.

**Comment by marionf** [comment] 2020-04-08 13:30
Hello,
Since we had no news from you for more than 30 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Closed as completed by marionf** 2020-04-08 13:30 UTC
Labels: Email, No change required
