### ISSUE TITLE
Order with 2 cart rules (Offers free shipping)

### ISSUE THREAD

**Issue by fredNativ** [PrestaShop/PrestaShop#14461] opened 2019-07-03 10:02 UTC
Hi, In prestashop 1.7.5.1.
When i make a order with 2 reduction with offers shipping), the total is OK. Prestashop is offering only shipping 1 time but the reduction is false (The shipping is offer 2 times)
<img width="1396" alt="Capture d’écran 2019-07-03 à 11 59 06" src="https://user-images.githubusercontent.com/46342662/60583091-60683300-9d8a-11e9-8fd2-38e56b2186d6.png">

**Comment by khouloudbelguith** [comment] 2019-07-03 10:10
Hi @fredNativ,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11722
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-03 10:10
Duplicate of #11722

**Closed as completed by khouloudbelguith** 2019-07-03 10:10 UTC
Labels: Duplicate
