### ISSUE TITLE
Sitemap module - Timeout server error 500 with images in sitemap

### ISSUE THREAD

**Issue by arseniov** [PrestaShop/PrestaShop#34572] opened 2023-11-15 01:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a website with more than 62000 product IDs, when generating the sitemap with the selection to include images for products, the server goes on timeout and returns a 500 error while working on the 2nd or 3rd splitted sitemap.
Cannot further increase PHP's max_execution_time more than 900s as already set.

If excluding product images from the sitemap, the sitemaps are generated correctly within 40-60 seconds.

**Selected options and sections:**
![selected-options](https://github.com/PrestaShop/PrestaShop/assets/83009979/22d66e8b-4cce-460b-8a20-1c533133dba2)

**Debug error code:**
None specific. The server just goes on timeout and returns the 500 server error code.

### Expected behavior

The sitemaps are correctly generated without server timeouts.

### Steps to reproduce

1. Configure the Gsitemap module
2. Press create Sitemap button
3. Get server timeout after max_execution_time (900s in my case)

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

gsitemap v4.3.0

**Comment by florine2623** [comment] 2023-11-16 10:01
Hello @arseniov ,

I can't reproduce your issue on my end.

Have you checked if your system requirements were ok ?
https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/#how-to-verify-your-server-meets-prestashops-requirements

**Comment by arseniov** [comment] 2023-11-16 10:58
Hi @florine2623 
So I can't test that as I'm not on a managed server but I can give you the corresponding values from PHPInfo for the recommended specs, with the only "negative" differences being the ones in bold italic (max_input_vars is **_3000_** instead of 5000; set_time_limit is **_not defined_** instead of true; short_open_tag is **_enabled_** instead of disabled).

Besides that, did you test the described behavior on a large product database (with images) like mine? I think the culprit here is the large products dataset when adding images to the sitemaps.

Also this issue seems to be relevant to #32625 and #18508?

'versions' => [
            'php' => '7.1', 7.4.33
            'mysql' => '5.6', 7.4.33
        ],
        'extensions' => [
            'curl' => true, true
            'dom' => true, true
            'fileinfo' => true, true
            'gd' => true, true
            'imagick' => true, true
            'intl' => true, true
            'json' => true, true
            'openssl' => true, true
            'mbstring' => true, true
            'memcache' => false, false
            'memcached' => true, false
            'pdo_mysql' => true, true
            'zip' => true, true
            'bcmath' => true, true
        ],
        'config' => [
            'allow_url_fopen' => true, true
            'expose_php' => false, false
            'file_uploads' => true, true
            'max_input_vars' => 5000, _**3000**_
            'memory_limit' => '256M', 1024M
            'post_max_size' => '128M', 128M
            'register_argc_argv' => false, false
            'set_time_limit' => true, _**N/A**_
            'short_open_tag' => false, **_true_**
            'upload_max_filesize' => '128M', 128M
        ],
        'apache_modules' => [
            'mod_rewrite' => true, true
        ],

**Comment by ShaiMagal** [comment] 2023-11-16 19:25
@arseniov option "check images" is very tricky, normally it shoul by unchecked...

**For 60k products it takes a lot of time. Disable it.**

I will be happy, if we will remove this function(checkbox) for future versions of modulu "gsitemap"

There is no reason to check, if file exists on FTP. Image should exists every time.

It take too much CPU time resulting to 500 (max_execution_time limit in most of cases). Uncheck this option is my recommendation.

**Comment by arseniov** [comment] 2023-11-17 14:28
@ShaiMagal I understand that, though having images in the sitemap can improve ranking and that would be a good function to keep.
I also agree that checking if the image exists doesn't really have much sense, so I've modified the codes as follows to keep the images in the sitemap but disabling the HTTP check.
If this makes sense I'll push a PR.

```
$image_product = [];
				if (isset($image_link)) {
					$images_product[] = [
						'title_img' => htmlspecialchars(strip_tags($product->name)),
						'caption' => htmlspecialchars(strip_tags($product->meta_description)),
						'link' => $image_link,
					];
				}
```

```
$image_category = [];
			if (isset($image_link)) {
				$image_category = [
					'title_img' => htmlspecialchars(strip_tags($category->name)),
					'caption' => Tools::substr(htmlspecialchars(strip_tags($category->description)), 0, 350),
					'link' => $image_link,
				];
			}
```

**Comment by ShaiMagal** [comment] 2023-11-17 15:28
@arseniov I think, it's already done from yesterday:
https://github.com/PrestaShop/gsitemap/pull/169
I hope, I don't miss something :)

**Comment by florine2623** [comment] 2023-12-21 09:11
I'm closing the issue as it has been fixed by a PR

**Closed as completed by florine2623** 2023-12-21 09:11 UTC
Labels: Bug, BO, Fixed, Google sitemap, Module, 8.1.x
