### ISSUE TITLE
impossible to translate Pdf contents

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#17808] opened 2020-02-24 19:03 UTC
Impossible to translate pdf contents like: {l s='Billing Address' d='Shop.Pdf' pdf='true'} in admin environment.

prestashop version: 1.7.6.1

**Comment by khouloudbelguith** [comment] 2020-02-25 09:59
Hi @sharkooon,

I did not manage to reproduce the issue with PS1.7.6.1 and PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1w_boInPwH5d-WJshvaXUIAJpCrph3fvc/view
Thanks to check & feedback.

**Comment by sharkooon** [comment] 2020-02-25 15:33
Alright i see, but i'm using prestashop "classic-rocket" as main theme with a child theme.
When i select "classic-rocket" theme for translation, i cant make translation for pdf. 
<img width="661" alt="Schermafbeelding 2020-02-25 om 16 30 59" src="https://user-images.githubusercontent.com/533123/75262167-6a90e300-57ec-11ea-833c-1312f6438df8.png">

When i use classic theme for theme translation, i see pdf section. Why is pdf only related to classic theme?

**Comment by khouloudbelguith** [comment] 2020-02-25 15:42
@sharkooon, have you tried to contact the theme author about this issue?

Thanks to check with them and feedback.

**Comment by sharkooon** [comment] 2020-02-25 21:01
Theme author is Prestashop
https://github.com/PrestaShop/classic-rocket

**Comment by khouloudbelguith** [comment] 2020-02-26 07:57
@sharkooon, no, it is `Prestarocket`
https://github.com/PrestaShop/classic-rocket/blob/master/config/theme.yml#L4

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-26 15:52
Hi @sharkooon,

We are awre of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #9804
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-26 15:52
Duplicate of #9804

**Closed as completed by khouloudbelguith** 2020-02-26 15:52 UTC
Labels: Bug, Duplicate, Translations, Modules & Themes, 1.7.6.1
