### ISSUE TITLE
PS 1.7.2.4 in module and product page in 500 error

### ISSUE THREAD

**Issue by lakhveer** [PrestaShop/PrestaShop#10368] opened 2018-09-10 16:54 UTC
My PS 1.7.2.4 in module and product page in 500 error
**PrestaShop version:** 1.7.2.4
**Shop URL:** http://www.thebellcollections.com/
**Server information:** Linux #76-Ubuntu SMP Thu Aug 16 16:21:21 UTC 2018 x86_64
**Server software version:** Apache/2.4.18 (Ubuntu)
**PHP version:** 7.0.30-0ubuntu0.16.04.1
**Memory limit:** 1000M
**Max execution time:** 5000
**Upload Max File size:** 750M
**MySQL version:** 5.7.23-0ubuntu0.16.04.1
**MySQL engine:** InnoDB
**MySQL driver:** DbPDO

i have use aws , please help me as soon as.

**Comment by khouloudbelguith** [comment] 2018-09-10 16:57
Hi @lakhveer,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by lakhveer** [comment] 2018-09-10 17:02
Thanks for your response
where i found server setup and configuration?

**Comment by khouloudbelguith** [comment] 2018-09-10 17:07
Hi @lakhveer,

You need to navigate to the BO => Advanced Parameters => Information page.

Best regards, Khouloud

**Comment by lakhveer** [comment] 2018-09-10 17:10
![screencapture-thebellcollections-admin375oippbf-index-php-2018-09-10-22_39_13](https://user-images.githubusercontent.com/8274910/45312738-7d591e80-b54a-11e8-89eb-bbeb15b4cafa.png)
![screenshot from 2018-09-10 22 23 40](https://user-images.githubusercontent.com/8274910/45312748-8518c300-b54a-11e8-93d2-2e0cb9eb245f.png)

please check server configuration

**Comment by rdy4ever** [comment] 2018-09-11 09:29
Hi there. Please [enable debug mode](https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/) in order to see a more detailed error that could indicate the cause.

**Comment by ghost** [comment] 2018-09-11 20:06
Same problem, url error 500: /admin/index.php/configure/shop/product_preferences?_token=xxx

Vers. PrestaShop: 1.7.4.2

<img width="587" alt="info server" src="https://user-images.githubusercontent.com/2458824/45385549-5d406280-b611-11e8-8b79-768f064f49f0.png">

<img width="589" alt="conf status" src="https://user-images.githubusercontent.com/2458824/45385559-64677080-b611-11e8-848a-468357347374.png">

<img width="1037" alt="error 500 exception 01" src="https://user-images.githubusercontent.com/2458824/45384661-ea35ec80-b60e-11e8-9eb2-441520e1026f.png">

<img width="1036" alt="error 500 exception 02" src="https://user-images.githubusercontent.com/2458824/45384663-ea35ec80-b60e-11e8-81cb-a5d10ef37a44.png">

<img width="1090" alt="error 500 logs" src="https://user-images.githubusercontent.com/2458824/45384664-ea35ec80-b60e-11e8-9586-054f6a2993b4.png">

<img width="1039" alt="error 500 stact trace 01" src="https://user-images.githubusercontent.com/2458824/45384665-ea35ec80-b60e-11e8-97b1-6f36b8b13334.png">

<img width="1036" alt="error 500 stact trace 02" src="https://user-images.githubusercontent.com/2458824/45384666-ea35ec80-b60e-11e8-9372-77bfdfbfe5c5.png">

**Comment by khouloudbelguith** [comment] 2018-09-12 14:34
Hi @lakhveer,

The issue has been fixed with the v4.0.0-beta.4 release of 1-click upgrade module (https://github.com/PrestaShop/autoupgrade/releases).
In fact, the v4.2.0 is released today.
If you already upgraded, please follow the message of Peter Visser: http://forge.prestashop.com/browse/BOOM-5982?focusedCommentId=171708&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171708

Best regards, Khouloud

**Comment by ghost** [comment] 2018-09-12 14:59
After 1000 searches, I had already seen that post, but in my opinion is not a solution for everyone..., especially for those who fear to get their hands on the database/configuration file. Will there be an automated solution to remove human error?

**Comment by khouloudbelguith** [comment] 2018-09-12 15:15
Hi @dritancami,

The module 1-click upgrade was always cleaning the empty data found.
Fixed with https://github.com/PrestaShop/autoupgrade/pull/103
The solution of Peter Visser can help you to solve the problem after getting those exceptions.

Best regards, Khouloud

**Comment by lakhveer** [comment] 2018-09-12 15:41
![screencapture-thebellcollections-admin375oippbf-index-php-_profiler-cd15f3-2018-09-12-21_10_00](https://user-images.githubusercontent.com/8274910/45436369-47de3d80-b6d0-11e8-960c-d248116a972b.png)
![screencapture-thebellcollections-admin375oippbf-index-php-_profiler-cd15f3-2018-09-12-21_09_33](https://user-images.githubusercontent.com/8274910/45436370-47de3d80-b6d0-11e8-8754-d47986a020ae.png)
![screencapture-thebellcollections-admin375oippbf-index-php-_profiler-cd15f3-2018-09-12-21_11_47](https://user-images.githubusercontent.com/8274910/45436476-84119e00-b6d0-11e8-8bba-9d55b65803de.png)

This is my debug log report

**Comment by khouloudbelguith** [comment] 2018-09-12 15:45
Hi @lakhveer,

Did you enable the debug mode?
In the meantime, it seems that a description is missing, and that's why it could not be listed in the "following errors" in the information page
Here's the PR about that issue in https://github.com/PrestaShop/PrestaShop/pull/9407.
If you're confident in modifying the core files manually, you can apply the changes to show the test in failure.

Best regards, Khouloud

**Comment by lakhveer** [comment] 2018-09-12 15:54
yes it's show in debug mode otherwise 500 error display :(

**Comment by khouloudbelguith** [comment] 2018-09-12 16:47
Hi @lakhveer,

Have you installed any customized module before the error occurs?

Best regards, Khouloud

**Comment by lakhveer** [comment] 2018-09-12 16:49
NO, product page in same error display

**Comment by khouloudbelguith** [comment] 2018-09-13 09:56
Hi @lakhveer,

The 3 screenshots that you provided us, cannot help us to find what's wrong, there are just warnings.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by lakhveer** [comment] 2018-09-13 14:21
🙁 so what can I do?

**Comment by khouloudbelguith** [comment] 2018-09-13 14:30
Hi @lakhveer,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-13 14:30 UTC
Labels: Bug, BO, Can't reproduce, 1.7.2.4
