### ISSUE TITLE
Currency settings is missing in PS1.7.4.2

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10238] opened 2018-09-02 13:48 UTC
In PS 1.6 I can set the way the currency is displayed. In PS 1.7 this is missing? Bug?

The goal is to have the price written 300,00 SEK or 300,00 kr. Right now it's SEK300.00

![skarmavbild 2018-09-02 kl 15 36 58](https://user-images.githubusercontent.com/42907000/44956611-25297900-aec7-11e8-80a7-8f993cf1065a.png)
![skarmavbild 2018-09-02 kl 15 37 08](https://user-images.githubusercontent.com/42907000/44956612-25297900-aec7-11e8-8a76-90c8f0a05ceb.png)
![skarmavbild 2018-09-02 kl 15 38 08](https://user-images.githubusercontent.com/42907000/44956613-25c20f80-aec7-11e8-91de-617b300536ee.png)
![skarmavbild 2018-09-02 kl 15 38 26](https://user-images.githubusercontent.com/42907000/44956614-25c20f80-aec7-11e8-9276-982129c4d8e4.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9
http://sjostromaudio.net

**Comment by khouloudbelguith** [comment] 2018-09-03 07:27
Hi @peranderssjostrom,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10017
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-03 07:27
Duplicate of #10017

**Closed as completed by khouloudbelguith** 2018-09-03 07:27 UTC
Labels: Duplicate
