### ISSUE TITLE
is the virtual_uri buggy 2?

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#34793] opened 2023-12-08 20:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am very sorry to see that this is the only way to reopen https://github.com/PrestaShop/PrestaShop/issues/34383

Quote from previous post:
The virtual_uri field is a rather obscure field in the ps_shop_url table. In this Github there is just one post where it is even named.

The field is supposed to provide altenative urls for the frontside. However, there is now a complaint on the forum that is changing some backoffice links too - with a resulting dysfunction.

See: https://www.prestashop.com/forums/topic/1081141-no-input-file-specified-backoffice-url-prefix-is-not-working/

After that post [florine2623](https://github.com/florine2623) provided a test and said that he found no problems.

The issue is that in his case the first shop had no virtual_uri while in the mentioned forum post all shops had a virtual_uri. This matters as the first shop is used for the backoffice.

The forum post has in the mean time evolved. It provides the code trace how the admin is link is created. And that looks indeed problematic:
/classes/Link.php  contains the function getAdminBaseLink() 
getAdminBaseLink() contains the line: return $base.$shop->getBaseURI();
/classes/shop/Shop.php contains the function getBaseUri.
getBaseUri() contains the line: return $this->physical_uri . $this->virtual_uri;

### Expected behavior

Correct links in the backoffice

### Steps to reproduce

See above

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-01-08 10:33
Hello,

You can create a [discussion](https://github.com/PrestaShop/PrestaShop/discussions) on that topic.
Or create another issue with the exact steps to reproduce.

I'm closing the issue for now as we can't reproduce it.
Thanks!

**Closed as completed by florine2623** 2024-01-08 10:33 UTC
Labels: Bug

**Comment by simbus82** [comment] 2024-11-06 09:36
I encountered the same issue (/it/ in the admin urls) with PrestaShop 8.1.7, (php 8.1, apache 2.4) in a multistore setup configured as shown in the screenshot.

![Image](https://github.com/user-attachments/assets/6dc946cc-1c34-4253-a440-242690a3be8d)


The solution I found was to remove the /it value in the virtual_uri field of the ps_shop_url table in the database, specifically in the row corresponding to the default website.

![Image](https://github.com/user-attachments/assets/1339d1ab-7259-4cfe-b884-fa50c0f800be)


Result: Removing /it resolved the backend access issue. However, as a drawback, I lost the /it/it language prefix in the frontend URLs (for the default shop in the default language), now i have only /it for the default website, for the secondary url is /eu/it (store/language)

Note: This issue only appeared after a server change. On the old server, everything worked as expected. The main difference between the two servers is that open_basedir was left empty (less secure) on the old server but is configured (more secure) on the new server.

Please reopen the issue @florine2623.
The bug is very clear, consistently present, and reproducible: the virtual_uri of the default shop is, for some inexplicable reason, also used by the back office to generate admin URLs. The virtual_uri is essential for correctly managing frontend URLs in multistore/multilanguage setups, so removing it to solve a back office issue is a significant and impactful workaround.
