### ISSUE TITLE
PDF Not generating for Invoice & Delivery Slip also Checkout error 500

### ISSUE THREAD

**Issue by tuhingr** [PrestaShop/PrestaShop#10240] opened 2018-09-02 14:22 UTC
Hello
My Prestashop 1.7.3.3 can not generate PDF for Invoice and Delivery Slip.
When Checkout FO then getting error 500 with all payment mode, COD and Local Gateway,
I checked all forum and forge report, try to resolve it, no success.
>If I upgrade PS then work well for some time, after then getting same error.
>When Upgrade 1.7.3.3, DB not upgraded. but site running well.
>Now cannot upgrading 1.7.4.2
Help!
BR

**Comment by khouloudbelguith** [comment] 2018-09-03 07:38
Hi @tuhingr,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by tuhingr** [comment] 2018-09-04 11:59
Server information Linux #1 SMP Wed May 2 07:43:19 EDT 2018 x86_64
Server software version: Apache
PHP version: 5.6.37
Memory limit: 512M
Max execution time: 300
Upload Max File size: 1G
MySQL version: 10.1.31-MariaDB-cll-lve

If you needs for more info then please ask me, will provide info.
BR
![no_error](https://user-images.githubusercontent.com/24760582/45029951-1cbe7300-b06c-11e8-95a0-daf1ca0a8bd8.png)

**Comment by khouloudbelguith** [comment] 2018-09-04 12:56
Hi @tuhingr,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by tuhingr** [comment] 2018-09-04 18:10
Finally resolved this issue.
tcpdf.php.suspected rename to tcpdf.php
/vendor/tecnickcom/tcpdf on located.
Thanks

**Comment by khouloudbelguith** [comment] 2018-09-05 09:00
Hi @tuhingr,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-05 09:00 UTC
Labels: Bug, Fixed
