### ISSUE TITLE
Duplicate addresses when you modify them since the checkout of an order

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18625] opened 2020-04-14 17:07 UTC
#### Describe the bug

When you make an order and you are on the screen to select the address, you can modify an already created address or add a new one. if you modify an already created one, it is duplicated.
Video: https://youtu.be/xMuhtGXhVX8

#### Expected behavior

if you modify the address it should be updated and not duplicated

#### Steps to Reproduce

1. Go to checkout 
2. Click on addres

**Screenshots**

https://youtu.be/xMuhtGXhVX8

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by alfonsolr09** [comment] 2020-04-14 17:10
I think the solution is simple, the same link must be executed as when you update an address from my user profile

**Comment by Matt75** [comment] 2020-04-15 06:54
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18103
Will be handled by v1.7.6.5

**Comment by marionf** [comment] 2020-04-15 08:07
Duplicate of #18100

**Closed as completed by marionf** 2020-04-15 08:07 UTC
Labels: Duplicate
