### ISSUE TITLE
Only variables in mails {firstname} {lastname}

### ISSUE THREAD

**Issue by 97t** [PrestaShop/PrestaShop#14848] opened 2019-07-24 23:42 UTC
Hi,

i installed PrestaShop multiple times, in version 1.7.5 and 1.7.6. german edition and every time I make an order, there is only a mail with variables like:

_________
Hallo {firstname} {lastname},
--
Thank you for shopping on {shop_name}!
_________

**To Reproduce**
Install prestashop, make an order.

**Screenshots**
https://share-your-photo.com/img/5d4a2fa547.png
https://share-your-photo.com/img/a62111d3b8.png
https://share-your-photo.com/img/5eff91e77f.png
https://share-your-photo.com/img/2d06c1cae5.png
(Black bg ist because of dark mode)

**Additional information**
PrestaShop version: 1.7.5 & 1.7.6
PHP version: 7.3

**Comment by khouloudbelguith** [comment] 2019-07-26 06:29
Hi @97t, 
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your version PHP, check & feedback.

**Comment by 97t** [comment] 2019-07-26 07:04
I downgrade to 7.2 and it's same problem.

A developer from India made a test order. He got an email with correct format, but in English (i think because of browser settings). But when order with German language browsers (safari, chrome, firefox..) there is the mails with variables.

**Comment by khouloudbelguith** [comment] 2019-07-26 11:08
@97t, could you please navigate to the BO > International > Translations > "Add / Update a language" section, Select your Deutch language & click on the on the "Add or update a language" button.

Thanks to check & feedback!

**Comment by 97t** [comment] 2019-07-26 13:06
I updated language successful, but nothing changed in mails (same problem with variables)

**Comment by 97t** [comment] 2019-07-27 03:31
I discovered the problem. It's when email address of client contain BIG and small letters.

1.) works: test@abc.de  -> Hello Michael Kane
https://share-your-photo.com/img/d2249096f4.png

2.) error: Test@Abc.de or Test@abc.de or test@Abc.de  -> Hello {firstname} {lastname}
https://share-your-photo.com/img/c0ec805731.png

I think its a PrestaShop error.
Best regards

**Comment by marionf** [comment] 2019-07-29 08:00
@khouloudbelguith It seems to be a duplicate of #13386

**Comment by khouloudbelguith** [comment] 2019-07-29 08:03
@marionf, yes, it is the same issue.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-29 08:03
Hi @97t,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13386
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-29 08:03
Duplicate of #13386

**Closed as completed by khouloudbelguith** 2019-07-29 08:03 UTC
Labels: Duplicate, Email, 1.7.5.2, 1.7.6.0
