### ISSUE TITLE
1.7.8.2 - Wrong search box size - Backoffice (Spanish, Portuguese, etc.)

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#26955] opened 2021-12-12 01:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

Visit your own demo and go to orders:

https://demo.prestashop.com/#/en/back

and now in spanish (go to orders also:

https://demo.prestashop.com/#/es/back

As you can see the search box is messing with the layout.

### Expected behavior

The search box must have the same size in all languages.

### Steps to reproduce

Visit your own demo and go to orders:

https://demo.prestashop.com/#/en/back

and now in spanish (go to orders also:

https://demo.prestashop.com/#/es/back

As you can see the search box is messing with the layout.

### PrestaShop version(s) where the bug happened

1.7.8.2

### If your bug is related to a module, specify its name and its version

7.2.24

**Comment by florine2623** [comment] 2021-12-13 08:18
Hello @seederp2p ,

The search box is the same in both languages:
<img width="1431" alt="Screenshot 2021-12-13 at 09 16 21" src="https://user-images.githubusercontent.com/16019289/145776125-37ed0d75-b243-4b69-86fa-3c95352818e4.png">
<img width="1435" alt="Screenshot 2021-12-13 at 09 16 16" src="https://user-images.githubusercontent.com/16019289/145776131-f8e77c07-d3b5-4bc5-bd16-9e4d1307b699.png">

As I can't reproduce your bug, I'll close this issue.
Thanks!

**Closed as completed by florine2623** 2021-12-13 08:18 UTC
Labels: Bug, Invalid

**Comment by seederp2p** [comment] 2021-12-13 12:44
@florine2623 Do you read what I wrote??

go to the "ORDERS" sections.
