### ISSUE TITLE
Module translations are not working

### ISSUE THREAD

**Issue by M4ketech** [PrestaShop/PrestaShop#23351] opened 2021-02-22 15:56 UTC
#### Describe the bug

Like #19229 i started to test module translations and found that all module translations are incorrect. Lets take next example. "Featured Products", with Finnish language that module is shown as "Suosittuja tuotteita" on the frontend and on the backend i did translate it to "Tuotteemme" in the default theme and installed modules translations.

Same behavior goes to all installed modules. I tested with search bar, contact information and featured products.

#### Expected behavior

After i click "Save" in translation page, it should be updated on the frontend side. But right now its showing default translation value.

#### Steps to Reproduce

1. Go to 'International -> Translations'
2. Click on 'Installed modules translations ->Pick one and one language'
3. Scroll down to 'Save, click it'
4. See error (Translations are not updated in frontend)

**Screenshots**

![kuva](https://user-images.githubusercontent.com/8841448/108733056-cd6ba600-7536-11eb-974d-69edf78ef676.png)

#### Additional information

* PrestaShop version: 1.7.7.2 and 1.7.7.1
* PHP version: 7.3.27

**Comment by M4ketech** [comment] 2021-02-22 16:09
I think its critical bug in version after versions, since same thing seems to be talked here https://www.prestashop.com/forums/topic/958547-prestashop-1751-translations-not-saving-updating/

**Comment by hibatallahAouadni** [comment] 2021-02-22 16:18
Hello @M4ketech 

I think this issue is similar to this one #13392 and it's already in our debug roadmap.
Please check and feedback.

Thanks!

**Comment by M4ketech** [comment] 2021-02-22 16:36
Yeah, somewhat similar to that issue. I think last version with working translation system out of the box was 1.7.5. Main problem comes from duplicated translations? Like Classic theme translations have:
![kuva](https://user-images.githubusercontent.com/8841448/108738116-f17db600-753b-11eb-8d96-a249e9f8e40b.png)

And there is also way to try translate that module via "installed modules".

**Comment by M4ketech** [comment] 2021-02-22 16:42
Tested with removing translations from database and edited files in sf-fi-FI.zip. After uploading .zip to server and clearing cache (even when i dont use it) frontend shows "valikko_määritykset" in footer contact infromation.

**Comment by hibatallahAouadni** [comment] 2021-02-23 17:38
Hello @M4ketech 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #13392. 
To be informed when it's fixed, please subscribe to the issue mentioned above.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

PS: I will add your issue description to the issue mentioned above :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-23 17:38
Duplicate of #13392

**Closed as completed by hibatallahAouadni** 2021-02-23 17:38 UTC
Labels: Bug, FO, Duplicate, Modules, Translations, 1.7.7.1
