### ISSUE TITLE
[CI] Automatic tests are failing at PHP Unit (7.2), because of an outdated certificate.

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#26831] opened 2021-12-02 08:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Automatic tests are failing at PHP Unit (7.2).
The certificate used in the test is outdated (8.12.2020)

1) Tests\Unit\Adapter\ToolsTest::testRefreshCaCertFile
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '##\n
 ## Bundle of CA Root Certificates\n
 ##\n
-## Certificate data from Mozilla as of: Tue Oct 26 03:12:05 2021 GMT\n
+## Certificate data from Mozilla as of: Tue Dec  8 04:12:05 2020 GMT\n
 ##\n
 ## This is a bundle of X.509 certificates of public Certificate Authorities\n
 ## (CA). These were automatically extracted from Mozilla's root certificates\n
@@ @@

https://github.com/PrestaShop/PrestaShop/runs/4391890669?check_suite_focus=true

### Expected behavior

Test should fail only due to changes introduced be the PR

### Steps to reproduce

1. Open a PR
2. Wait for tests to run

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

github

### If your bug is related to a module, specify its name and its version

CI

**Comment by hibatallahAouadni** [comment] 2021-12-02 08:37
Hello @lmeyer1 

Thank you for reporting this issue. The Developer Team will investigate this problem.
Ping @PrestaShop/prestashop-core-developers can you reproduce the issue?

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.
If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment] 2021-12-02 12:58
Weird, https://github.com/PrestaShop/PrestaShop/pull/26832 tests pass 🤔

**Comment by atomiix** [comment] 2021-12-03 14:26
I think it was a bug in the matrix, re-running tests solve the issue 😅
I close this issue, feel free to reopen if the problem comes back.

**Closed as completed by atomiix** 2021-12-03 14:26 UTC
Labels: Bug, develop, Developer Feature, CI/CD, Invalid
