### ISSUE TITLE
Unexisting BO route exception 

### ISSUE THREAD

**Issue by LouisAUTHIE** [PrestaShop/PrestaShop#33552] opened 2023-08-06 05:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a route is added to the menu in the BO, if this route doesn't exist, there is an error : 
Attempted to call an undefined method named "addWarning" of class "Symfony\Bridge\Monolog\Logger".

### Expected behavior

Add a warning in a toast but redirect to the admin dashbord

### Steps to reproduce

1. Install a module with a tab linking to an unexisting route
2. Go to any page of the BO (even the module BO controller)
<img width="1095" alt="Capture d’écran 2023-08-06 à 07 00 48" src="https://github.com/PrestaShop/PrestaShop/assets/65625876/cc2e19ef-a5e7-413e-a384-0f06d2992beb">

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

WebHelpers

**Comment by kpodemski** [comment] 2023-08-06 18:37
Hi @LouisAUTHIE 

You need to provide us with an example module to reproduce this error. The simplest possible module, just to observe the behavior you reported.

**Comment by matks** [comment] 2023-08-10 16:06
@LouisAUTHIE So basically if one creates a module, but the module links to a non-existant route, all the BO pages fail?

**Comment by hibatallahAouadni** [comment] 2023-08-24 13:38
Hello @LouisAUTHIE 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-08-24 13:38 UTC
Labels: Bug, develop, BO, Modules, Invalid
