### ISSUE TITLE
Large number of combinations error in product edit page

### ISSUE THREAD

**Issue by stefanrvc** [PrestaShop/PrestaShop#11074] opened 2018-10-19 06:15 UTC
#Hi,

we are running presta 7.4.3 (but bug was also in 7.4.2). We run it on IIS windows 2016 and PHP 7.2
The system ran fine until we imported about 80 product. We import products and combinations via the import tool. Each product has 110 productcombinations. When displayed on the frontend this works fine. However when we visit in the backend the productpage and click on the Combinations tab the system does recognize there are 110 product combinatins (it says 0/110), but it won't load all the combinations. Further when pressing save an error appears.

The problem is caused by the backend trying to retrieve the product combinations. In debug mode we found out that an url like:

https://somethinglikeourdomain.com/adminpage/index.php/combination/11190-11191-11192-11193-11194-11195-11196-11197-11198-11199-11200-11201-11202-11203-11204-11205-11206-11207-11208-11209-11210-11211-11212-11213-11214-11215-11216-11217-11218-11219-11220-11221-11222-11223-11224-11225-11226-11227-11228-11229-11230-11231-11232-11233-11234?_token=cz893j0hGrcN74x-g_EGQXMi9XQ-Gv_U5YXoZHCjaXo
Did not work and gave an error like:
Bad Request - Invalid URL
HTTP Error 400. The request URL is invalid.

But a shorter url of the same like:
https://somethinglikeourdomain.com/adminpage/index.php/combination/11200-11201-11202-11203-11204-11205-11206-11207-11208-11209-11210-11211-11212-11213-11214-11215-11216-11217-11218-11219-11220-11221-11222-11223-11224-11225-11226-11227-11228-11229-11230-11231-11232-11233-11234?_token=_bzuW87Aqk8hFioRfnP_WAkqIOE0fWp-FZKl-JozNy4
Worked fine and reported a page with the requested productcombinations. 

When we open the first products that we uploaded to the store and tab productcombinations, these work fine. Probably because the productcombination ids are low resulting in a shorter url resulting in a working response.

1. IIS PHP 7.2 Presta 7.4.3 config
2. Import say 100 products and per products 110 productcombinations
3. Go to Products in de backoffice and select the last imported product. 
4. Click on combinations and/or click save.

**Screenshots**
See screenshot of the product combinations. We wait a long time so it is not a performance issue. Plus when debugger is on we could see the error of the
https://somethinglikeourdomain.com/adminpage/index.php/combination/11190-11191-11192-11193-11194-11195-11196-11197-11198-11199-11200-11201-11202-11203-11204-11205-11206-11207-11208-11209-11210-11211-11212-11213-11214-11215-11216-11217-11218-11219-11220-11221-11222-11223-11224-11225-11226-11227-11228-11229-11230-11231-11232-11233-11234?_token=cz893j0hGrcN74x-g_EGQXMi9XQ-Gv_U5YXoZHCjaXo
page and visit that page manually to result in the error. Shortening the url resulted in a normal response. 

**Additionnal information**
PrestaShop version: 7.4.3
PHP version: 7.2

We tried to change settings in IIS and PHP to see if any settings needed to be increased to allow larger urls. We changed suggestions on this matter but with no better result.

Regards
Stefan

![combationstab-wont-load-combinations](https://user-images.githubusercontent.com/44285014/47200590-0e57bc80-d377-11e8-9972-935e78c3e218.png)

**Comment by khouloudbelguith** [comment] 2018-10-19 07:58
Hi @stefanrvc,

We are aware of this issue and we are working on it.
No, this issue is in progress, it is assigned to our developer Jocelyn Fournier, he is working on it.
Thanks for your patience
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-19 07:58 UTC
Labels: Duplicate
