### ISSUE TITLE
Bug suppression option personnalisation et ajout au panier/ Bug deletion option customization and addition to the cart

### ISSUE THREAD

**Issue by Micdales** [PrestaShop/PrestaShop#16844] opened 2019-12-18 06:36 UTC
Bonjour,

Impossible d'ajouter le produit au panier

Le bug ce produit de la manière suivante :
1. ajouter un champ personnalisation avec l'option "requis" (enregistrer)
2. supprimer le champ personnalisation sans désactivé l'option "requis" (enregistrer)
3. impossible d'ajouter le produit au panier

Noter: Vider le cache ne suffit pas à résoudre le bug

Merci!

Hello,

Unable to add product to cart

The bug occurs in the following way:
1. add a personalization field with the "required" option (save)
2. delete the personalization field without deactivating the "required" option (save)
3. cannot add product to cart

Note: Clearing the cache is not enough to resolve the bug

Thank you!

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.25

**Comment by khouloudbelguith** [comment] 2019-12-18 08:39
Hi @Micdales,

Thanks for your report.
>delete the personalization field without deactivating the "required" option (save)

The deletion is from the Back office?
![image](https://user-images.githubusercontent.com/16067358/71070002-2cd36680-217a-11ea-896e-f1c7707e3bd2.png)

Thanks!

**Comment by Micdales** [comment] 2019-12-18 10:47
Hi @khouloudbelguith 

Yes deletion from the back office.

Deletion when "required" disabled is ok.
Deletion when "required" is activated is not ok, bug add to cart.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-18 10:59
@Micdales, I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1fUiNPabIGFT6wq5ph-gj3-5hNRjQQsEK/view

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-01-17 09:10
Hi @Micdales,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-17 09:10 UTC
Labels: Bug, FO, Product customization, No change required, 1.7.6.2
