### ISSUE TITLE
Translation theme export bad xlf files

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#18665] opened 2020-04-16 10:36 UTC
#### Describe the bug

We folow the documentation to export theme translations
https://devdocs.prestashop.com/1.7/themes/reference/theme-translation/
But when we export the theme we found partial translations.

Probably not related to #15791

#### Expected behavior

Generate a correct file xlf file.

#### Steps to Reproduce

Please note :
* We supply a sample child theme to be easy to test but this bug is not specific to children theme.
* We suggest to translate only one sentence out of 2. It's just to have a proof of the bug.

1. Install a defaut prestashop 1.7.6.4 with classic theme
2. Install our theme issue in attached file (simple child of classic theme) 
[child_classic.zip](https://github.com/PrestaShop/PrestaShop/files/4486449/child_classic.zip)

3. Go to the translation manager to translate the child classic theme. translate the first sentence and not the second.
4. Export your theme.

You'll see 2 files:
![image](https://user-images.githubusercontent.com/52157233/79444959-2e078980-7fdc-11ea-946e-29c4396d5446.png)

* fr-FR.fr-FR.xlf : we don't understand why we have this file without translations from DB
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="/var/www/prestashop/admin" source-language="fr-FR" target-language="fr-FR" datatype="plaintext">
    <body>
      <trans-unit id="0a40d090851aca6d8f7eae0066fe5c2e">
        <source>My classic translation</source>
        <target>My classic translation</target>
        <note>Line: </note>
      </trans-unit>
      <trans-unit id="e7274d66e562f869f08ba8eee7c83e64">
        <source>My second translation not in DB</source>
        <target>My second translation not in DB</target>
        <note>Line: </note>
      </trans-unit>
    </body>
  </file>
</xliff>
```
* ShopChildclassic.fr-FR.xlf Why there is only the translated sentence ?
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="/var/www/prestashop/admin" source-language="fr-FR" target-language="fr-FR" datatype="plaintext">
    <body>
      <trans-unit id="0a40d090851aca6d8f7eae0066fe5c2e">
        <source>My classic translation</source>
        <target>Ma traduction en français</target>
        <note>Line: </note>
      </trans-unit>
    </body>
  </file>
</xliff>
```

We think the PrestaShop should generate something like that on ShopChildclassic.fr-FR.xlf without other file) :
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="/var/www/prestashop/admin" source-language="fr-FR" target-language="fr-FR" datatype="plaintext">
    <body>
      <trans-unit id="0a40d090851aca6d8f7eae0066fe5c2e">
        <source>My classic translation</source>
        <target>Ma traduction en français</target>
        <note>Line: </note>
      </trans-unit>
      <trans-unit id="e7274d66e562f869f08ba8eee7c83e64">
        <source>My second translation not in DB</source>
        <target>My second translation not in DB</target>
        <note>Line: </note>
      </trans-unit>
    </body>
  </file>
</xliff>
```
Note: we have a PR to fix according to our suggested behaviour.

#### Additional information

* PrestaShop version: 1.7.6 & 1.7.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-04-16 10:43
Hi @clotaire202,

Thanks for your report.
Here's just a PR: https://github.com/PrestaShop/PrestaShop/pull/18293 still in progress to fix the issue.
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16555
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-16 10:43
Duplicate of #16555

**Closed as completed by khouloudbelguith** 2020-04-16 10:43 UTC
Labels: Duplicate
