### ISSUE TITLE
ps_facetedsearch wrong product sorts in front-office

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#35647] opened 2024-03-14 13:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
there is a problem with the module ps_facetedsearch about product sorts in front-office
this problem is present on many websites normally in those with many products, perhaps because it is more easily noticed

the problem is present in every type of ordering, and accentuated if the "Show unavailable, out of stock last" option is activated

the problem does not depend on the graphics used, in this case it is developed by me.

taking a random category from this site
https://www.lampadaribartalini.it/7-plafoniere-lampade-soffitto

when "Show unavailable, out of stock last" is enabled
![3](https://github.com/PrestaShop/PrestaShop/assets/653230/f30b14a1-c745-4066-b0e5-310400cbf501)

when "Show unavailable, out of stock last" is not enabled
![5](https://github.com/PrestaShop/PrestaShop/assets/653230/d1f8edcf-b227-4002-aa97-94b82b736c2b)

this also happens on the best-selling products page, with a product at €5.66
https://www.lampadaribartalini.it/vendite-migliori?order=product.price.asc

on this site the problem is even more evident
in general it seems that the order is correct but then it makes a mistake on some products
https://www.mondialshop.it/it/piatti-doccia-in-marmo-resina-339

I can provide other sites with the same problem. obviously on a demo site with 20 products you won't notice it

here is another example, at the end of this page
https://www.stilebagno.com/it/63-box-doccia-2-lati

here another error on the first row
https://www.velliniilluminazione.com/it/49-lampade-da-tavolo-abat-jour

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/ff4602bd-faf8-4d66-acbe-322e1ef8144a)

I can provide access to a copy of the site if you need verification

bye

### Steps to reproduce

1. it is necessary to check on a real website

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.15.1

**Comment by Hlavtox** [comment] 2024-03-14 15:22
Hi @maofree, there is an issue about this already - https://github.com/PrestaShop/PrestaShop/issues/19810 :-)

**Comment by Maofree** [comment] 2024-03-14 15:35
the problem is also present with sorting by reference and name and the option to put deactivated products at the end also adds problems.
From what I see, the problem has persisted for 4 years, so I think it's a bit long to resolve

**Comment by AureRita** [comment] 2024-03-14 16:00
Hi @maofree 

Thank you for your report.I think you know the rules about real website, we have to follow some steps to reproduce on our shop to see if it's not related to your shop environment. As you can see on the @Hlavtox issue, we have a clear steps to reproduce that let us reproduce it. 

Can you provide us more information about how we can reproduce it on our local shop ? 

Waiting for your feedback

**Comment by Maofree** [comment] 2024-03-14 16:08
Hi
honestly I can't find any logic, I don't understand why he puts 90% of the products in order and then gets some completely wrong.
locally on 20 demo products, I believe it is not possible to replicate this problem.
however, given that it is present on many completely different sites, it highlights the presence of errors in the module code.
this problem is also present when using other advanced search modules, so I think it is a problem with some Prestashop core functions.
in the end it comes down to sorting by price or reference or name, I don't think it's that strange of a query.
I also saw it on other sites made with prestashop

**Comment by florine2623** [comment] 2024-03-21 14:55
Hello @maofree ,

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19810

You can follow that issue directly to get updated.
If you want to add any details, feel free to do it directly on the original issue : https://github.com/PrestaShop/PrestaShop/issues/19810

Thank you 💪

**Closed as completed by florine2623** 2024-03-21 14:55 UTC
Labels: Bug, FO, Faceted search, Module, 8.1.x
