### ISSUE TITLE
1.7.6.3 Unable to select shipping carrier during checkout.

### ISSUE THREAD

**Issue by goombaylabs** [PrestaShop/PrestaShop#18354] opened 2020-03-29 20:48 UTC
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

Good Afternoon,

I added an additional shipping carrier so I now have 2 for my customers to choose from. However, during the checkout process, it does not allow customers to choose which shipping method they want to use. Additionally, I had set up a carrier that was only available to customers in a particular region and now when they place orders, they can not move on to the next step, which would be to choose shipping or choose payment method. After selecting your address, the checkout simply refreshes to the choose shipping address step.

Please see screenshots.

![screenshot 1](https://user-images.githubusercontent.com/51277054/77860401-ad235200-71d4-11ea-8f35-5678001e7029.jpg)
![screenshot2](https://user-images.githubusercontent.com/51277054/77860402-adbbe880-71d4-11ea-9aec-6e525e3c4321.jpg)

**Comment by sarahdib** [comment] 2020-03-30 07:00
Hello @goombaylabs 

Thank you for reporting this issue.

I didn't reproduce this issue with the information you gave me.

If you click on continue it goes to the newt step or not ? Can you sent me a screenshot of your console (right click -> inspect -> click on the second tab named "console") when you clicking on continue to see if there is error ?

The new carrier is it added by a module ? 

Thank you

**Comment by goombaylabs** [comment] 2020-03-31 15:27
Hello,

If i click continue it does not allow me to move to the next step, nor does it allow me to choose the carrier. And yes, the additional shipping carrier was added via module.

Regards,

![Console Screenshot 1](https://user-images.githubusercontent.com/51277054/78044211-fa6d0400-7339-11ea-9f01-fd88ce9a9382.jpg)

![Console Screenshot 2](https://user-images.githubusercontent.com/51277054/78044250-06f15c80-733a-11ea-8692-0ded672a3a17.jpg)

**Comment by khouloudbelguith** [comment] 2020-03-31 15:34
Hi @goombaylabs,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sarahdib** [comment] 2020-04-28 09:36
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed** 2020-04-28 09:36 UTC
Labels: Bug, FO, Shipping, Carriers, No change required, Checkout, 1.7.6.3
