### ISSUE TITLE
Add the possibility to save current theme configuration

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21743] opened 2020-11-04 09:10 UTC
#### Describe the bug
I use my own theme during adjustment of an e-shop and there are more standard modules disabled, e.g. Banner, Search bar... If I switch to classic theme for checking and then I switch back to my theme then these disabled modules are automatically enabled. I have to disable them again manually, it is very uncomfortable because there are more modules which I have to disable again and again and again.

#### Expected behavior
If any module is disabled and if the theme is changed then the module shouldn't be automatically enabled and it should stay  disabled.

#### Steps to Reproduce
1. Go to BO
2. Switch to your own theme 
3. Disable modules, e.g. Banner, Search bar
4. Switch to classic theme 
5. Switch to your own theme 
6. Check modules, e.g. Banner, Search bar => they are enabled

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment] 2020-11-04 09:41
Hi @juraj1000 

I didn't manage to reproduce the issue with PS1.7.6.8 and PS1.7.7.0-rc.1+build.3
I attached the screen record:

https://drive.google.com/file/d/1K2wXWKnpIk44xnAKEYhucFtg1szGfr3N/view

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-04 11:09
Hello again,

In my last comment I changed only BO modules and that's why I didn't manage to reproduce it.
When I tired with FO modules like search bar, I managed to reproduce the issue with PS1.7.6.8 and PS1.7.7.0-rc.1+build.4.

https://drive.google.com/file/d/11xHgpOiG7e3g7TvLiZyCmiE3b-rkcneM/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by marionf** [comment] 2020-11-04 13:46
Hello @juraj1000 

I am not sure to understand what is the problem here.
When you install a theme the modules associated to this theme are automomatically installed / enabled because otherwise you will need to install and enable them one by one

**Comment by dennispw** [comment] 2020-11-04 15:43
Related: https://github.com/PrestaShop/PrestaShop/issues/12933

**Comment by juraj1000** [comment] 2020-11-05 11:06
Hello @marionf,
I need to have a possibility to save current theme configuration. It could be in the file theme.yml, it could be in any other file. It could be also done manually like "Export to...". Without this functionality it is really complicated to develop own theme or to use own positions of modules in hooks, because all information is lost if you change the theme. And usually you need quite often to compare the functionality of classic theme and your theme during development or adjustment of the customer theme.
You can see the detail info in related #12933 where this issue is exactly described.

**Comment by marionf** [comment] 2020-11-05 17:07
Ok thank you for the explanation @juraj1000, so your request is an improvement 
It seems to be a duplicate of #12933 ?

**Comment by juraj1000** [comment] 2020-11-06 21:38
Hello @marionf,
yes, it seems to be the duplicate of #12933

**Comment by marionf** [comment] 2020-11-09 10:49
Duplicate of #12933

**Closed as completed by marionf** 2020-11-09 10:49 UTC
Labels: Improvement, BO, FO, Duplicate, Theme & logo, Modules & Themes, 1.7.7.0, 1.7.6.8
