### ISSUE TITLE
Wrong Product Price in the listing of Category, Search and Others

### ISSUE THREAD

**Issue by fyndpriser** [PrestaShop/PrestaShop#10800] opened 2018-10-01 18:12 UTC
Hello
I have a shop that has multiple stores the product price of the products having combinations in the category list and search list shows wrong. It shows the highest value but in the product it shows the correct price.
The problem is solved by entering the product page in the BO and then clicking Save! Please note that I do not modify anything in the product information just click Save
How do I fix the problem?
Sorry for my English

Thanks in advance
Best Regards
Adam

**Comment by MathiasReker** [comment] 2018-10-01 22:02
What is your prestashop version?

**Comment by fyndpriser** [comment] 2018-10-01 22:22
Hi,
Prestashop version 1.7.4
I've recorded a video
https://youtu.be/-gTr7CDU5co

**Comment by fyndpriser** [comment] 2018-10-01 22:32
Maybe the problem is due to the different product combinations ID?
For example
Product A in SV store has the following link
https://www.domain.com/891385-29777-militarinspirerad-duffelvaska-85-l-olivgron.html#/44-storlek-n_a/80-farg-gron

The same Product in UK store has the following link

https://www.domain.co.uk/891385-55756-army-style-duffel-bag-85-l-olive-green.html#/44-storlek-n_a/80-farg-gron

**Comment by khouloudbelguith** [comment] 2018-10-02 07:52
Hi @fyndpriser,

Thanks for your report.
Could you please navigate to BO => Modules & Services page => search for the ps_facetedsearch module => Click on configure button => Click on the "Rebuild entire price index" button, clear cache, check & feedback.

Best regards, Khouloud

**Comment by fyndpriser** [comment] 2018-10-02 15:39
Hello
Thank you for replying
I've rebuild an entire price index but unfortunately the same problem

Please note that products which have no combinations there is no problem with them
Best Regards
Adam

**Comment by khouloudbelguith** [comment] 2018-10-02 15:48
@fyndpriser have you tried to contact the theme author with this issue?
Thanks to check with them & feedback.

**Comment by fyndpriser** [comment] 2018-10-03 02:49
Hi Khouloud,
The problem also exists in the default theme
Thank you
Best Regards
Adam

**Comment by khouloudbelguith** [comment] 2018-10-03 08:29
Hi @fyndpriser, sorry but I did not manage to reproduce the issue with PS 1.7.4.2 & the default theme.
I attached a video record: https://drive.google.com/file/d/1mDyypuRJ4BJqJZL6qV5c_rFf4QM8LvSV/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2018-11-08 11:47
Hi @fyndpriser,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-08 11:47 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.4.2
