### ISSUE TITLE
Password bug with ampersand symbol during initial installation

### ISSUE THREAD

**Issue by arafatx** [PrestaShop/PrestaShop#26645] opened 2021-11-17 06:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I install Prestashop using the following password, instead of showing me an error that it cannot handle some characters in password but I got an apache / nginx error page (Forbidden) 

The password is: Bk29s9suOP78ujk()(@&123x9

I believe this due to the character & 

### Expected behavior

It should have password validation instead of showing an error page that has no meaning.

### Steps to reproduce

1) Install Prestashop 
2) During the installation creates an admin account using the following password:

`k29s9suOP78ujk()(@&123x9`

or any passwords that have ampersand '&' symbol

You will get an error page during the account creation.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4+

**Comment by mparvazi** [comment] 2021-11-17 07:18
Hello @arafatx 

It was very interesting for me! 

Then i tried to test:
<img src="https://user-images.githubusercontent.com/85633460/142150644-9fb9bbd7-d52d-44d0-bf06-947e60613ecf.png" width="350"/>

But installation done successfully:
<img src="https://user-images.githubusercontent.com/85633460/142153535-c8c547f5-99cf-456e-9e58-d5b359c454a1.png" width="550"/>

Apache 2.4.51
PHP 7.4.25
PS 1.7.8.1

**Comment by arafatx** [comment] 2021-11-17 09:43
Hi @mparvazi May I know what is your database version? Mine is MariaDB 10.6.4

Also, I will try to reproduce this with an apache only server because my current server is nginx_apache (reverse proxy)

**Comment by mparvazi** [comment] 2021-11-17 10:38
@arafatx 

10.4.21-MariaDB

[https://stackoverflow.com/questions/34817907/nginx-escaping-ampersand](https://stackoverflow.com/questions/34817907/nginx-escaping-ampersand)

**Comment by hibatallahAouadni** [comment] 2021-11-17 14:00
Hello @arafatx 

As @mparvazi mentioned, I didn't manage to reproduce the issue too.
Could you please provide more details :pray: 

Thanks!

**Comment by arafatx** [comment] 2021-11-19 12:47
@hibatallahAouadni Please wait, I'm inspecting this issue further and I'll let you know.

**Comment by khouloudbelguith** [comment] 2021-11-19 14:17
@arafatx, thanks!
Waiting for your feedback.

**Comment by hibatallahAouadni** [comment] 2021-12-09 13:48
Hello @arafatx 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-09 13:48 UTC
Labels: Bug, IN, Invalid
