### ISSUE TITLE
Delivery time 

### ISSUE THREAD

**Issue by tlukowskia** [PrestaShop/PrestaShop#13452] opened 2019-04-17 10:46 UTC
**Describe the bug**
I want to add delivery time when product is out of stock.

**To Reproduce**
1. Go to 'product'
2. Click on 'shipping'
3. Scroll down to 'delivery time'
4. Nothing happend

**Screenshots**
http://prntscr.com/nd50h3 what i get?
http://prntscr.com/nd50rh

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-04-17 13:33
Hi @tlukowski, 

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/14FsFCsmOmjn2xHtJZGih8lNYmcXWOtyw/view

Thanks for check and feedback.

**Comment by tlukowskia** [comment] 2019-04-18 07:35
What did i wrong?
https://drive.google.com/file/d/1-8FpjWFU1aRXE76gMQjULreAy8xTxDlm/view?usp=sharing

**Comment by khouloudbelguith** [comment] 2019-04-18 16:22
@tlukowski,

In my case with PS1.7.5.1, it is OK
![image](https://user-images.githubusercontent.com/16067358/56375787-5b213080-61fe-11e9-8d75-861fee8647bb.png)
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by tlukowskia** [comment] 2019-04-19 06:44
Okey i know everythink now, when i install polish version "delivery time" doesn't work, after install new presta 1.7.5.1 everythink is fine, what can i do?

**Comment by tlukowskia** [comment] 2019-04-19 06:48
Check it http://prntscr.com/ne0jlm - polish version
http://prntscr.com/ne0jyg - English version

**Comment by khouloudbelguith** [comment] 2019-04-19 09:31
@tlukowski, thanks for your feedback.
I installed a PrestaShop v1.7.5.1 with Poland country & Polish language => but I did not manage to reproduce the issue.
I attached a video record.
https://drive.google.com/file/d/1lg-TIAo27PriEQqqnH26g20k41zHRgI3/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-20 07:28
Hi @tlukowski,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-20 07:28 UTC
Labels: FO, No change required, 1.7.5.1
