### ISSUE TITLE
Stock notifications duplicated when editing products with combinations at back-end

### ISSUE THREAD

**Issue by ftardio** [PrestaShop/PrestaShop#18150] opened 2020-03-13 17:30 UTC
There is a problem with seller stock notifications when updating a product with combinations at back-end. At 1.7 Prestashop version, all the combinations are stored at the same time when updating a product, so if you have a stock alert (for example, alert for 0 quantity), and you update a variable product with 10 combinations, 5 of them having 0 stock, you will get 5 email with stock notifications, one for each combination, even if you doesn't change stocks nor combinations.

This is not appropriate, the seller doesn't have to get any stock notification when updating a product at back-end, only when stock changes because a order is placed. Maybe the hook the module is using is not suitable?

**Comment by ftardio** [comment] 2020-03-13 17:38
Sorry, this report was for email notifications module. I just opened it at the right place, you can discard this issue.

**Comment by khouloudbelguith** [comment] 2020-03-17 11:27
Hi @ftardio,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9641
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-17 11:27
Duplicate of #9641

**Closed as completed by khouloudbelguith** 2020-03-17 11:27 UTC
Labels: Duplicate
