### ISSUE TITLE
problem with attributs product PS 1.7.5.2

### ISSUE THREAD

**Issue by koalabang** [PrestaShop/PrestaShop#14660] opened 2019-07-15 13:52 UTC
**Describe the bug**
Hi ,I have a problem with the attributs on my products. When I select an attribute on a product I am permanently positioned on the default attribute. The rewrite of url does not work towards the new attribute. Do you have an idea ? 

You can test this product : 

**To Reproduce**
1. Go to 'https://rf-market.fr/casquette-tactique/192-17-casquette-tactique-noire-camo-kaki.html#/32-casquette_tactique-noir'
2. Click on 'different colors'
3. the page remains on the default attribute

**Screenshots**
live demo works

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2.19

**Comment by mariem-abid** [comment] 2019-07-15 14:00
Hi @koalabang,

I did not manage to reproduce the issue with PS:1.7.6.0
Could you please check with the default template provided by PrestaShop.

**Comment by koalabang** [comment] 2019-07-15 14:02
Hi @mariem-abid , with the default template i have the same issue.

**Comment by mariem-abid** [comment] 2019-07-15 15:30
@koalabang, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by koalabang** [comment] 2019-07-16 16:53
hi, after upgrade in 1.7.6 it works good.
But i have a new error for webservice, i have an error 401 and on webservice page i have a message :
Please activate the 'mod_auth_basic' Apache module to allow authentication of PrestaShop's webservice
Have you got an idea ?

**Comment by khouloudbelguith** [comment] 2019-07-17 09:31
@koalabang, this issue occurs in the BO => Advanced Parameters => webservice page or while using a script because it could be an issue related to the outdated version of PSWebServiceLibrary.php.
If no, you need to check with your host that the `mod_auth_basic` is enabled on the server.

Thanks to check & feedback.

**Comment by mariem-abid** [comment] 2019-08-16 07:28
Hi @koalabang,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by mariem-abid** 2019-08-16 07:28 UTC
Labels: Bug, FO, Can't reproduce, Attributes, 1.7.5.2

**Comment by NBoESFWbVaf** [comment] 2019-08-26 04:29
Hi,
- Fresh install from Presta 1.7.6.0 on Ubuntu 16.04 with php7.1
- mod_auth_basic is enabled
but the warnmessage appears in webservice.

This is my first install of a Prestashop and i can't locate the problem.
If more information is needed, let me know.
Please, any help will be gratefully accepted.

Thx

**Comment by khouloudbelguith** [comment] 2019-08-26 09:08
Hi @NBoESFWbVaf,
This issue is currently closed, can you open a new one with more information about your configuration

Thanks!

**Comment by NBoESFWbVaf** [comment] 2019-08-26 09:56
Hello,
Yes i can open a new issue, later. For now, i've installed clean Pres 1.7.5.2 and the mistake is gone. The error seems to be in the version 1.7.6.0.
