### ISSUE TITLE
Cart rule amount displayed is different than order amount

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#19763] opened 2020-06-15 15:06 UTC
#### Describe the bug

When a customer is using a discount created through a cart rule, the amount displayed in the shopping cart is the total amount of the cart rule instead of the amount of the order

#### Expected behavior

Have the same amount displayed between the cart rule and the total price of the order

#### Steps to Reproduce

1. In BO, create a Cart Rule
2. Choose partial use, no code, a specific customer and 100€
3. In FO, log in to that customer account
4. Place an order
5. See that he amount displayed is the total amount of the cart rule instead of the amount of the order

**Screenshots**

In PS 1.7.6.5
![Capture d’écran 2020-06-15 à 16 54 39](https://user-images.githubusercontent.com/16019289/84673177-9fef4700-af29-11ea-9f98-dead92dbf2a0.png)

In PS 1.7.7.0
![Capture d’écran 2020-06-15 à 16 54 29](https://user-images.githubusercontent.com/16019289/84673191-a67dbe80-af29-11ea-93f7-19b3c0821743.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by colinegin** [comment] 2020-06-16 15:57
Hello @florine2623,

this is weird, I've tested on a 1.7.6.5 and I actually have the same behaviour as on 1.7.7.
![image](https://user-images.githubusercontent.com/35263827/84798027-c29d6080-affa-11ea-91c2-7717d0e44c26.png)

Could you test again on a fresh install please ?

**Comment by marionf** [comment] 2020-09-29 10:38
Hello @khouloudbelguith 

Could you please try to reproduce this issue on 1.7.7.x ?

**Comment by khouloudbelguith** [comment] 2020-09-29 11:13
Hi @marionf, @florine2623,

It is ok with 1.7.7.x branch.
1. If `amount < discount`
![image](https://user-images.githubusercontent.com/16067358/94551342-7e566900-0255-11eb-8155-be9c0e466e93.png)
2. If `amount > discount`
![image](https://user-images.githubusercontent.com/16067358/94551375-8c0bee80-0255-11eb-8961-4709b442aa05.png)

I close the issue since it is fixed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-09-29 11:13 UTC
Labels: Bug, Minor, FO, Cart rules, Regression, Blockcart, Fixed, 1.7.7.0, 1.7.6.5
