### ISSUE TITLE
Decimal

### ISSUE THREAD

**Issue by MikiMix** [PrestaShop/PrestaShop#14730] opened 2019-07-18 11:20 UTC
Greeting,
My shop 1.7.6 does not show me the right decimal  for the old price and savings. It should appear 2 decimal places, not 4.
Does anyone know what the problem is?﻿
![Opera Snapshot_2019-07-18_113358_ceger ba](https://user-images.githubusercontent.com/1534324/61453559-b928f580-a95e-11e9-8e39-8906fe69f1e0.png)

**Comment by khouloudbelguith** [comment] 2019-07-18 11:22
Hi @MikiMix,

Your ticket is a duplicate of #14615
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-18 11:22
Duplicate of #14615

**Closed as completed by khouloudbelguith** 2019-07-18 11:22 UTC
Labels: Duplicate
