### ISSUE TITLE
Error creating an order from the BO with free shipping

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18744] opened 2020-04-21 11:47 UTC
#### Describe the bug

When you create an order from the backoffice to a customer and mark it as free shipping, this creates a discount code that in the front office is seen as a null percentage, attached video
https://youtu.be/w2giZcOWzAU

#### Expected behavior

Should not add one more discount line but apply it in the discount code, just like a discount code.

#### Steps to Reproduce

1. Go to BO.
2. Click on Create new order
3. Scroll down to Shipping way
4. if you check yes, scroll to "Go to the payment page to process the payment"
5. Click and see error

**Screenshots**

https://youtu.be/w2giZcOWzAU

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29

**Comment by sam-pires** [comment] 2020-04-23 06:56
Hello @PrestaShop/prestashop-core-developers & @PrestaShop/prestashop-product-team 

Is this issue related to this one https://github.com/PrestaShop/PrestaShop/issues/16842?

We have a discount display problem.
As we check the free shipping option when creating an order from the BO, the discount amount displayed in FO in 0%.

**Comment by marionf** [comment] 2020-04-23 10:08
@sam-pires Did you manage to reproduce it on 1.7.6.x ?
We should try to reproduce it on 1.7.7.x also

**Comment by sam-pires** [comment] 2020-04-23 12:30
I did reproduce it on 1.7.6.x

I did try to reproduce it on 1.7.7.x as well but I couldn't create an order from the BO. So I don't know if it still happens on 1.7.7.x

**Comment by marionf** [comment] 2020-04-23 15:22
On 1.7.7.x there is no issue we well see "free shipping" and the amount of the discount is the same as the amount of the shipping

![capture d'écran_2566](https://user-images.githubusercontent.com/13449658/80117061-0047b500-8587-11ea-94b2-7dd7ff69fa46.png)

**Comment by marionf** [comment] 2020-04-23 15:25
Duplicate of #9702

**Comment by marionf** [comment] 2020-04-23 15:26
Fixed in 1.7.7.0 by https://github.com/PrestaShop/PrestaShop/pull/16235

**Closed as completed** 2020-04-23 15:26 UTC
Labels: Bug, Minor, FO, Duplicate, 1.7.6.x

**Comment by alfonsolr09** [comment] 2020-04-23 17:30
@marionf perfect, when will final version 1.7.7 be released??
