### ISSUE TITLE
Doctrine error on accessing customer details

### ISSUE THREAD

**Issue by pomichel** [PrestaShop/PrestaShop#27455] opened 2022-01-25 08:59 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I get the following error message when clicking on a customer either from the orders view or the customer view.
```
An exception occurred while executing 

'SELECT a.`id_address`, a.`firstname`, a.`lastname`, a.`address1`, a.`address2`, a.`postcode`, a.`city`, a.`company`, a.`phone`, a.`phone_mobile`, cl.`name` as country_name, grl.`name` FROM ps_address a LEFT JOIN ps_country c ON a.`id_country` = c.`id_country` LEFT JOIN ps_customer customer ON a.`id_customer` = customer.`id_customer` LEFT JOIN ps_country_lang cl ON c.`id_country` = cl.`id_country` AND cl.`id_lang` = ? LEFT JOIN `ps_customer_group` gr ON gr.`id_customer` = c.`id_customer` LEFT JOIN `ps_group_lang` grl ON grl.`id_group` = gr.`id_group` WHERE (a.`id_customer` != 0) AND (a.`deleted` = 0) AND (customer.id_shop IN (?)) AND (a.`id_customer` = ?) ORDER BY id_address asc LIMIT 50' 

with params [1, 1, "11579"]: 
SQLSTATE[42S22]: 
Column not found: 1054 Unknown column 'c.id_customer' in 'on clause'
[Doctrine\DBAL\Exception\InvalidFieldNameException 0]
```

### Expected behavior

View customer details

### Steps to reproduce

1. Go to the orders view
2. Click on the cutomer link

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-01-25 10:32
Hello @pomichel 

I didn't manage to reproduce the issue with PS1782 and PHP 7.4, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/150959801-4cc5b9b8-02ca-486e-bdcf-95435223ceec.mp4

Please check and feedback.
Thanks!

**Comment by pomichel** [comment] 2022-01-25 10:39
Hi,

Thanks for your feedback.

I unfortunately face the issue both from the orders list, the order detail and the customers list.

Please check the attached screenshot.

![ss-ps-admin-1](https://user-images.githubusercontent.com/35295725/150961433-5a1fc719-5778-4d7b-ab5b-6679f14919c1.jpg)

**Comment by pomichel** [comment] 2022-01-25 10:45
The SQL request is malformed.

There is no "id_customer column" in the "ps_country" table.

**Comment by hibatallahAouadni** [comment] 2022-01-25 14:52
Hello @pomichel 

Could you please enable the debug mode and make provide a screenshot of the issue :pray: 
Cause in this Request, there's a three mistakes:

1. `AND cl.'id_lang' = ?`
2. `customer.id_shop IN (?)`
3. `a.'id_customer' = ?`

Besides the issue that you mentioned above: `c.'id_customer'`
That should be: `customer.'id_customer'`
Waiting for your feedback.

PS: if you have any module that may affect the Order or Customer, please disable it and check if you still encounter the issue.

Thanks!

**Comment by pomichel** [comment] 2022-01-25 16:41
The screenshot is my previous post.

As already mentioned, I get the error message described in the screenshot by clicking on the customer link in the orders list view.

Of course, I have not generated the SQL request myself.

Hope this is clear enough.

**Comment by hibatallahAouadni** [comment] 2022-01-25 18:09
Please **enable the debug mode** and then make a screenshot :wink:

**Comment by pomichel** [comment] 2022-01-26 07:59
Hi,

Here is the output supplied by debug mode. Nothing new actually :

<html><head></head><body><div class="trace trace-as-html">

InvalidFieldNameException                                                                  An  exception occurred while executing 'SELECT a.`id_address`,  a.`firstname`, a.`lastname`, a.`address1`, a.`address2`, a.`postcode`,  a.`city`, a.`company`, a.`phone`, a.`phone_mobile`, cl.`name` as  country_name, grl.`name` FROM ps_address a LEFT JOIN ps_country c ON  a.`id_country` = c.`id_country` LEFT JOIN ps_customer customer ON  a.`id_customer` = customer.`id_customer` LEFT JOIN ps_country_lang cl ON  c.`id_country` = cl.`id_country` AND cl.`id_lang` = ? LEFT JOIN  `ps_customer_group` gr ON gr.`id_customer` = c.`id_customer` LEFT JOIN  `ps_group_lang` grl ON grl.`id_group` = gr.`id_group` WHERE  (a.`id_customer` != 0) AND (a.`deleted` = 0) AND (customer.id_shop IN  (?)) AND (a.`id_customer` = ?) ORDER BY id_address asc LIMIT 50' with  params [1, 1, "2"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.id_customer' in 'on clause'
--
in AbstractMySQLDriver.php line 60
at AbstractMySQLDriver->convertException()in DBALException.php line 169
at DBALException::wrapException()in DBALException.php line 145
at DBALException::driverExceptionDuringQuery()in Connection.php line 913
at Connection->executeQuery()in QueryBuilder.php line 200
at QueryBuilder->execute()in DoctrineGridDataFactory.php line 96
at DoctrineGridDataFactory->getData()in CustomerAddressGridDataFactoryDecorator.php line 60
at CustomerAddressGridDataFactoryDecorator->getData()in GridFactory.php line 90
at GridFactory->getGrid()in CustomerController.php line 309
at CustomerController->viewAction()in HttpKernel.php line 151
at HttpKernel->handleRaw()in HttpKernel.php line 68
at HttpKernel->handle()in Kernel.php line 200
at Kernel->handle()in index.php line 82

</div></body></html>

**Comment by khouloudbelguith** [comment] 2022-01-28 16:51
Hello @pomichel,

Despite our efforts, we were not able to reproduce your issue with the provided information.

https://user-images.githubusercontent.com/16067358/151587854-376c5e0a-2e59-4b10-8219-5c0c160dc67f.mp4

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue, feel free to create a new one when needed.

Thank you!

**Closed as completed by khouloudbelguith** 2022-01-28 16:51 UTC
Labels: Bug, BO, Can't reproduce, Customer, 1.7.8.0, Invalid

**Comment by pomichel** [comment] 2022-01-31 09:21
Hi,

I have finally worked it out.

It was an issue with a custom module using hookActionCustomerGridQueryBuilderModifier.

Sorry for disturbing ;-)
