### ISSUE TITLE
payment method not set for some type of payments with a strange behavior

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#28591] opened 2022-05-25 06:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
in the delivery slip pdf, in one website, it is not set the "payment method" like in the invoice pdf.
in other website this problem is present only for some type of payments, like for bank wire and cash on delivery is ok, but not for the rest of payments.
instead in one website all payment methods are set in the delivery slip pdf

I've upgraded all of them to 1.7.8.3 - 17.8.5

instead in the invoice pdf it is set correctly the payment method in all of websites

I cannot reproduce this bug on a default prestashop because real website have much more orders and payments

![1](https://user-images.githubusercontent.com/653230/170195984-1fd812c0-5877-4f3c-921e-2d555135499f.png)
![2](https://user-images.githubusercontent.com/653230/170195988-70432947-c585-4e58-8135-8eb7c855e907.png)
![3](https://user-images.githubusercontent.com/653230/170195991-61b2fca5-2e1c-4adf-b76a-13dfde0c32ba.png)
![4](https://user-images.githubusercontent.com/653230/170195993-bf368d22-7548-4fe5-aedb-4fa1d2e34975.png)
![5](https://user-images.githubusercontent.com/653230/170195995-8ab3df33-1ced-40e0-953c-6c22120fc20f.png)
![6](https://user-images.githubusercontent.com/653230/170195999-5a68d605-ba2b-4341-ae18-c73cfac5bf8b.png)

bye

### Expected behavior

all delivery slip should set the payment method of the order

### Steps to reproduce

1. go to the order list and push on the delivery slip icon

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-05-25 10:07
Hello @maofree 

As you said, it's not reproducible with native payment module/method.
Did you check with the payment module developer, cause it seems the issue is not Core bug but mostly like a module issue.

We will close this issue. Remember if you could provide any more infos, please ping me here and if I reproduce the isuse, I will reopen it :wink: 

Otherwise, if you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks!

**Closed as completed by hibatallahAouadni** 2022-05-25 10:07 UTC
Labels: Bug, Invalid
