### ISSUE TITLE
500 Internal Server Error - upload photo

### ISSUE THREAD

**Issue by attractive** [PrestaShop/PrestaShop#13695] opened 2019-05-07 09:58 UTC
Hi, 

After upgrading from 1.7.3 to 1.7.5. we can not add photos to the product. We click add photos and we get a mistake every time.

'
wielkanoc2019.jpg:
{"tmp_name":"\/tmp\/php35WqVA","name":"wielkanoc2019.jpg","size":91294,"type":"image\/jpeg","err
{"1":true},"url_update":"\/admin!\/index.php\/sell\/catalog\/products\/image\/form\/1116?
_token=ZYn6otBbkq4ZyrS229LR9V8OE1rHktocQ9O6WsrVM94","url_delete":"\/admin!\/index.php\/sell\
_token=ZYn6otBbkq4ZyrS229LR9V8OE1rHktocQ9O6WsrVM94"}

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will x itas soon as possible. Sorry for any inconvenience caused.

PrestaShop version: 1.7.5.2
PHP version: 7.2.17

**Comment by khouloudbelguith** [comment] 2019-05-07 10:08
Hi @attractive,

Could you please to delete the `tmp` folder, try to create a new one with access permission 777& regenerating thumbnails ( go to BO => Design => Image Settings => click on Regenerate thumbnails ).
Thanks to check & feedback.

**Comment by attractive** [comment] 2019-05-07 10:52
> Hi @attractive,
> 
> Could you please to delete the `tmp` folder, try to create a new one with access permission 777& regenerating thumbnails ( go to BO => Design => Image Settings => click on Regenerate thumbnails ).
> Thanks to check & feedback.

Hi, 

We don''t have folder tmp, but we create and regenerating thumbnails - There is still the same problem.

**Comment by khouloudbelguith** [comment] 2019-05-07 11:08
@attractive, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by attractive** [comment] 2019-05-07 11:31
Still the same problem.  I turned on debug:

![error-presta](https://user-images.githubusercontent.com/566471/57296073-4f71ad00-70cc-11e9-8bf3-3f21c8059730.jpg)

**Comment by khouloudbelguith** [comment] 2019-05-07 11:54
@attractive, your issue is related to the `litespeedcache` module.
You should contact the module author about this issue.
Your ticket is a duplicate of #11939
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-07 11:55
Duplicate of #11939

**Closed as completed by khouloudbelguith** 2019-05-07 11:54 UTC
Labels: BO, Duplicate, Image, 1.7.5.2
