### ISSUE TITLE
1 click uprgrade - PHP's max_execution_time setting error

### ISSUE THREAD

**Issue by monix12** [PrestaShop/PrestaShop#18232] opened 2020-03-19 18:27 UTC
I would like to update my prestashop 1.7.6.3 store to the latest version 1.7.6.4. However, an error occurs (PHP's max_execution_time setting has a high value or is disabled entirely (current value: 300 seconds) )

How can I change it? Where should it be done? 

* PrestaShop version: 1.7.6.3
* PHP version:  7.1.33

**Comment by khouloudbelguith** [comment] 2020-03-23 14:04
Hi @monix12,

Your ticket is a duplicate of #18264
Please follow: #18264.
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-03-23 14:04
Duplicate of #18264

**Closed as completed by khouloudbelguith** 2020-03-23 14:04 UTC
