### ISSUE TITLE
Schema blank Combination WS request bugged

### ISSUE THREAD

**Issue by geimsdin** [PrestaShop/PrestaShop#33545] opened 2023-08-04 03:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to get a schema blank for Combinations in Webservice the XML contains some <0> tag and it generates an error:

![image](https://github.com/PrestaShop/PrestaShop/assets/46976508/9f00fb56-ab4d-4133-8e2a-b4a41827431a)

fixed with pull request #33544

### Expected behavior

Get the blank schema without errors

### Steps to reproduce

Try to get a schema blank on Combinations from Webservice with a call like this: https://yourdomain.com/api/combinations/?1&schema=blank&ws_key=yourwebservicekey

### PrestaShop version(s) where the bug happened

since PS 8

### PHP version(s) where the bug happened

8.0, 8.1

### Your company or customer's name goes here (if applicable).

Simone - UnusualDope.com

**Comment by AureRita** [comment] 2023-08-04 13:57
Hi @geimsdin 

Thank you for report, can you give us an example of WS request you send ? The team QA'll try to reproduce your issue with your example. 

Waiting for your feedback

**Comment by geimsdin** [comment] 2023-08-04 14:52
It is written above @AureRita

Steps to reproduce
Try to get a schema blank on Combinations from Webservice with a call like this: https://yourdomain.com/api/combinations/?1&schema=blank&ws_key=yourwebservicekey

**Comment by AureRita** [comment] 2023-08-04 15:20
Hi @geimsdin 

Sorry for my misunderstanding, Indeed I reproduce it in Prestashop Version 8.0.5 as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/a53b13c2-2bf3-486a-b28f-ac8cf28d7225)

I'll add this to the backlog so it can be fixed  

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by geimsdin** [comment] 2023-08-05 03:46
Hi, it is present also in 8.1 version as well and I already submitted a PR that fixes it https://github.com/PrestaShop/PrestaShop/pull/33544

**Comment by Nikos22350** [comment] 2023-08-31 14:25
Hi,

I would like to revive the subject because i encountered the same problem with "Categories" on version 8.0.5.
I followed the fact that version 8.1 fixed the problem by updating.
Despite everything, it still doesn't work for "Categories" and also for "Combinations" on my side.

![image](https://github.com/PrestaShop/PrestaShop/assets/77013220/0e85ce80-3289-4df8-a2a2-a9840595c4ba)

Is there a solution ?

Thanks

Nicolas

**Comment by geimsdin** [comment] 2023-09-01 02:50
Hi @Nikos22350 

the fix seems that will be implemented on version 9 of PS, you can manually edit your installation following this easy fix https://github.com/PrestaShop/PrestaShop/pull/32884/commits/9d8848bf6ccba22cab8ef17506c95e7a3efa7934

I hope it works for you.

Simone

**Comment by Nikos22350** [comment] 2023-09-01 10:06
Hi @geimsdin,

Thank you for your solution, it's perfect everything works.

Nicolas

**Comment by matks** [comment] 2023-09-21 08:58
Dear @PrestaShop/qa-functional team could you verify if this bug has been fixed on branch `develop` thanks to PR https://github.com/PrestaShop/PrestaShop/pull/32884 ?

**Comment by aniszr** [comment] 2023-09-21 11:01
Hello @geimsdin  @matks 

I couldn't  reproduce the issue on `develop`, seems thats the issue is fixed by PR [#32884](https://github.com/PrestaShop/PrestaShop/pull/32884).

See attached screenshot :

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/ca76468b-2735-4ef5-80f6-08e013b380d0)

Blank schema is generated without errors :heavy_check_mark: 

Thanks!

**Closed as completed by aniszr** 2023-09-21 11:01 UTC
Labels: Bug, Minor, WS, Combinations, Fixed, Verified

**Comment by matks** [comment] 2023-09-21 11:42
And I am backporting the fix to 8.1.x in https://github.com/PrestaShop/PrestaShop/pull/34014
