### ISSUE TITLE
Module without description in webservice ressource break ressources listing on /api/

### ISSUE THREAD

**Issue by maniolias** [PrestaShop/PrestaShop#25124] opened 2021-06-25 09:54 UTC
#### Describe the bug

If installed modules use the hook `hookAddWebserviceResources` without providing "description" the list on the root /api/ path fails with `Undefined index: description` errors.

For instance:
```php
  /**
     * @param array $params
     * @return array
     */
    public function hookAddWebserviceResources($params)
    {
        return array(
            'colissimo_custom_products' => array(
                'class' => 'ColissimoCustomProduct',
                'forbidden_method' => array('HEAD', 'POST', 'PUT', 'DELETE'),
            ),
            'colissimo_custom_categories' => array(
                'class' => 'ColissimoCustomCategory',
                'forbidden_method' => array('HEAD', 'POST', 'PUT', 'DELETE'),
            ),
            'colissimo_ace' => array(
                'class' => 'ColissimoACE',
                'forbidden_method' => array('GET', 'HEAD', 'PUT', 'DELETE'),
            ),
        );
    }
```

The error is raised [here](https://github.com/PrestaShop/PrestaShop/blob/57894f9e9acb1f75088ec4ae63aaf6c468eac4b5/classes/webservice/WebserviceOutputBuilder.php#L331)

#### Expected behavior

Being able to list webservice ressources even if no description as been provided.

#### Steps to Reproduce

1. Install colissimo offical module for instance
2. Create a webservice API key
3. Open 'https://yourawesomeshop.com/api/'

![image](https://user-images.githubusercontent.com/4567538/123407152-ec914780-d5ab-11eb-8908-1e671c127f49.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2021-06-25 10:28
Hi @maniolias,

I did not manage to reproduce the issue with PS1769 and 177x branch (PS1776).
I attached a screen record
https://drive.google.com/file/d/1BmC-AF-FUor2b7UQhyopVCvg61mmK842/view?usp=sharing

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment] 2021-07-15 08:22
Hello @maniolias 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-15 08:22 UTC
Labels: Bug, WS, Modules, Webservice, No change required, 1.7.6.4
