### ISSUE TITLE
Suppression of several pictures of a product in one action.

### ISSUE THREAD

**Issue by couillaler** [PrestaShop/PrestaShop#17835] opened 2020-02-26 10:00 UTC
I would like to ask for a useful function in PS.
The idea is to have the possibility to suppress several (or all) pictures in one action on the product page.

Actually, on my PS 1.7.5.1, to suppress photos of a product I have to select one picture, wait for its loading, click on the link _Suppression_, wait for the suppression. Then, I select the next picture, wait for its loading, click on the link _Suppression_, wait for the suppression. Then, I select the next picture, wait for its loading, click on the link _Suppression_ ,...

Boring to read, isn't it ?
So to do, it is the same, it takes many time for a simple action : select several pictures in one time (with check boxes), click on Suppression, and it's done. :)

Can we expect to see this one day ? ^_^

For information, after my request on the PS forum webpage ([https://www.prestashop.com/forums/topic/1002492-supprimer-plusieurs-images-en-m%C3%AAme-temps-sur-une-page-produit-ps-17/](https://www.prestashop.com/forums/topic/1002492-supprimer-plusieurs-images-en-m%C3%AAme-temps-sur-une-page-produit-ps-17/) ), a developer has made an addon for this (here : [https://prestatuts.com/en/prestashop-modules/113-bulk-delete-product-images-for-17-and-16.html](https://prestatuts.com/en/prestashop-modules/113-bulk-delete-product-images-for-17-and-16.html) ).

It seems possible to add this function to PS. :)

Antoine

**Comment by florine2623** [comment] 2020-02-26 10:31
Hello @couillaler ,
It is added to our roadmap.
Your ticket is a duplicate of #12773
So, I close it.

**Comment by florine2623** [comment] 2020-02-26 10:32
Duplicate of #12773

**Closed as completed by florine2623** 2020-02-26 10:31 UTC
Labels: Duplicate, Image
