### ISSUE TITLE
Impossible to upgrade modules

### ISSUE THREAD

**Issue by LSClaire** [PrestaShop/PrestaShop#17068] opened 2020-01-08 15:48 UTC
**Describe the bug**
Hello,
On one of my prestashop sites, turning on 1.7.5.1, I am totally unable to upgrade modules, even native ones like "navigation à facettes". I have no idea where it can come from and don't know where to look. I don't have this issue on other sites. Can you help me to find out what is going on so I can fix it?

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A
<img width="1398" alt="Capture d’écran 2020-01-08 à 17 47 38" src="https://user-images.githubusercontent.com/43815115/71992982-01a2db00-323f-11ea-96eb-667f2f24dbea.png">
<img width="1398" alt="Capture d’écran 2020-01-08 à 17 45 14" src="https://user-images.githubusercontent.com/43815115/71992999-05cef880-323f-11ea-8f5b-355b314e4ec3.png">

**Comment by khouloudbelguith** [comment] 2020-01-08 16:02
Hi @LSClaire,

Thanks for your report. 
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by LSClaire** [comment] 2020-01-09 08:42
Hello, 
I don't have all the info asked yet but maybe these can give you some ideas to start?
PHP version is 5.6. 
I attach the debug mode error message for each module that we try to upgrade. A lot of them report a 404. Where can that come from?
I also attach some logs.
[prod.log](https://github.com/PrestaShop/PrestaShop/files/4039449/prod.log)
[dev.log](https://github.com/PrestaShop/PrestaShop/files/4039450/dev.log)


Thanks for your precious help.
[Orisques Modules Upgrade Error Messages.xlsx](https://github.com/PrestaShop/PrestaShop/files/4039431/Orisques.Modules.Upgrade.Error.Messages.xlsx)

**Comment by sarahdib** [comment] 2020-01-09 10:21
Hello @LSClaire,

The log indicate that your are not logged in addons : 
"app.ERROR: Exception retournée par le module gmerchantcenter pour upgrade. Error sent by Addons. You may need to be logged. [] []"
Try to connect your back office to the addons marketplace and see if the error is still there.

Thank you

**Comment by LSClaire** [comment] 2020-01-09 10:23
please check the excel document. This is the error related to ONE of the 12 modules. I understand that one this is not the one I need help with...

**Comment by khouloudbelguith** [comment] 2020-01-15 16:35
Hi @LSClaire,

I found those errors in your log:
>"Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes)"

In your php.ini file, Try to increase:

```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```
Also, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).

Thanks to check & feedback

**Comment by khouloudbelguith** [comment] 2020-02-11 08:02
Hi @LSClaire,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-11 08:02 UTC
Labels: Bug, BO, Modules, No change required, Module manager, 1.7.5.1
