### ISSUE TITLE
Some problems with displayOverrideTemplate hook

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11241] opened 2018-11-02 12:54 UTC
Hi

today I've seen the new hook, so from here it is possible to do some override like does the module ps_legalcompliance.

I tested this solution it works but not completely
I want to override the copyright_link block
it works but in the front-office I get only the footer code, the rest is not present

{extends file='_partials/footer.tpl'}
{block name='copyright_link'}
some text
{/block}

I see the "some text" and the rest of footer code but not of the html code

I attach here my mini block so you can test this hook

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0

bye

[maofreecopyright.zip](https://github.com/PrestaShop/PrestaShop/files/2542461/maofreecopyright.zip)

EDIT: see https://github.com/PrestaShop/PrestaShop/issues/11241#issuecomment-448914864

**Comment by khouloudbelguith** [comment] 2018-11-02 15:32
Hi @maofree,

After installing your module, I have issues in the Front office.
![image](https://user-images.githubusercontent.com/16067358/47924766-d004e600-debc-11e8-93b9-3036ea9dcd5a.png)
Thanks to check & feedback.

**Comment by Maofree** [comment] 2018-11-02 17:13
HI @khouloudbelguith 
yes I have the same problem
in fact the hook displayOverrideTemplate does not work very well
the override works but then in the front office will be present only the footer html code, the rest is not present

there is something wrong around this displayOverrideTemplate hook

**Comment by khouloudbelguith** [comment] 2018-11-05 13:05
Hi @maofree,

Thanks for this clarifications.
When after installing the "maofreecopyright", which only use the displayOverrideTemplate hook, I have issues in the FO.
![image](https://user-images.githubusercontent.com/16067358/47999738-c15c4000-e103-11e8-928d-4d2b11591154.png)
![image](https://user-images.githubusercontent.com/16067358/47999744-c620f400-e103-11e8-8cea-489fb1ea4636.png)
@marionf, what do you think?
Thanks!

**Comment by dheerajwebkul** [comment] 2018-12-20 08:30
Hello @khouloudbelguith 
We are still getting an issue in V1.7.4.4 if multiple modules register this hook.

Please check the attached screenshot.
![fatal_error](https://user-images.githubusercontent.com/19220745/50273071-946bae80-045f-11e9-86ba-36caa0f79a14.png)

**Comment by khouloudbelguith** [comment] 2018-12-20 08:32
Hi @dheerajwebkul,

This issue is not fixed yet.
It is added to our bug roadmap.
Thanks!

**Comment by matks** [comment] 2019-06-19 15:48
Hi @maofree I think there is a misunderstanding about what `DisplayOverrideTemplate` hook can do.
When I look at the implementation, this hook is there to allow developers to modify **which smarty template is being loaded** for a FrontController.

For example, on a Product page, the standard template file being loaded is `catalog/product.tpl`. This hook allows you to modify this behavior and use `catalog/my-own-template.tpl` if you want instead.

**However** this hook is called on every call of `FrontController::getTemplateFile()`. So when you are using it, you should only enable it **for the controllers and templates you want**.

Example of such usage:
```
    public function hookDisplayOverrideTemplate($param)
    {
        $template_file = $param['template_file'];

        // when I see that FrontController is trying to load 'catalog/product' I modify the behavior:
        if ($template_file === 'catalog/product') {
            return 'catalog/product-v2.tpl';
        }

         // else I do nothing
         return false;
    }
```

So I think there is no issue in the code, however we might be able to clear the misunderstanding about this hook by an improvement of the doc, maybe ?

**Comment by matks** [comment] 2019-06-19 16:01
@marionf Is the "major" label related to initial feedback or 2nd feedback (multiple hook causes crashs) ?

**Comment by marionf** [comment] 2019-06-26 08:02
@matks it's related to the multiple hook causes crashs

**Comment by matks** [comment] 2019-06-28 13:46
I failed to reproduce the "multiple hook crashes" (https://github.com/PrestaShop/PrestaShop/issues/11241#issuecomment-448914864). I installed 2 modules which both register hook `displayOverrideTemplate` and I have no issue on `develop`.

So, in this issue 2 bugs were reported:
- [the initial one](https://github.com/PrestaShop/PrestaShop/issues/11241#issue-376798679) but, as explained in https://github.com/PrestaShop/PrestaShop/issues/11241#issuecomment-503618526 I think it's a misusage of the hook, not an issue in the hook
- [the multiple hooking case](https://github.com/PrestaShop/PrestaShop/issues/11241#issuecomment-448914864) that I dont reproduce

I'm missing a clear procedure about "how to reproduce the issue" here.

**Comment by marionf** [comment] 2019-07-25 14:35
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
So, I close the issue. Don't hesitate to open a new one if needed.

**Closed as completed by marionf** 2019-07-25 14:35 UTC
Labels: Bug, Major, FO, Can't reproduce, Modules, 1.7.4.3
