### ISSUE TITLE
FO - The sum of products is not correct when we use round type for each item

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#33962] opened 2023-09-18 12:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The calculation for the sum of products is not good when we use round type for each item: 
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/ab0aff2d-c5c8-484d-a32f-222086e771e7)

22.94 * 4 + 15.48 = 91,76+15,48 = `107.24` != `107.26`

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/c79c827a-fe6c-4056-8725-183aa4d316fd)

### Expected behavior

The calculation for the sum of products is good : 107.24

### Steps to reproduce

1. Install PS in Language : English / Country : France
2. Create a product of type "Pack" with the name : "My pack"
3. Set the product as visible
4. Add the product `demo_1` with quantity = 4 in pack
5. Add the product `demo_4` with quantity = 1 in pack
6. Go to Front Office
7. The calculation is not good

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by Hlavtox** [comment] 2023-09-18 13:13
@Progi1984 Can you specify what is the tax rate, price without tax of the products and rounding settings? It's not possible to work on the issue without this information.

**Comment by Progi1984** [comment] 2023-09-18 13:16
@Hlavtox I work on a basic install. It was detected by UI tests.

**Comment by Hlavtox** [comment] 2023-09-18 13:18
@Progi1984 Yes, but A) basic install does not contain product MY PACK, B) every country has different tax settings. So, please again, can you provide this information?

**Comment by Progi1984** [comment] 2023-09-18 13:19
I updated steps.

**Comment by Hlavtox** [comment] 2023-09-18 13:35
This is expected behavior and correct calculation, you need to adapt the tests. Please confirm @MatShir @RosaBenouamer. 👍

![Snímek obrazovky 2023-09-18 153441](https://github.com/PrestaShop/PrestaShop/assets/6097524/84bb334b-95a9-4981-bab1-6fcf4fa9f2aa)

**Comment by Hlavtox** [comment] 2023-09-18 13:41
However, I think that when you setup to round each item, it should really be 107,24.❗

![rounding](https://github.com/PrestaShop/PrestaShop/assets/6097524/7a88c0d0-a043-4b27-bd38-a4f0696a215a)

______

Investigating "Round each item" case.
Method Pack::noPackPrice returns..

- 91.776 - WRONG
- 15.48 - OK

**Comment by hibatallahAouadni** [comment] 2023-09-18 13:57
Hello @Progi1984 

As you're using the defaut conf in BO>General like this:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/007bbff5-fbef-456d-bb77-d7884c6b300d)

So the calculation is right as @Hlavtox mentioned above.
23.900000 + 20% (tax) = 28,68
28,68 - 20% (specific price) = 22,944 
22,944 * 4 = 91,776 => (round on line) => 91,78
Total = 91,78 + 15,48 = 107,26

Thanks!

**Comment by Hlavtox** [comment] 2023-09-18 13:59
@hibatallahAouadni It must be fixed anyway, it's not correct in "round each item". :-)

Fixed by https://github.com/PrestaShop/PrestaShop/pull/33964

**Comment by Progi1984** [comment] 2023-09-18 14:04
@hibatallahAouadni I'm in default configuration

![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/35f887c3-ea26-4e83-a791-326d687f3d45)

**Comment by RosaBenouamer** [comment] 2023-09-18 15:12
I agree with @hibatallahAouadni that the result for round line is ok but as we tested with her the issue is on the round item. Indeed the expected behavior is 107.24 as @Hlavtox described but is today displayed 107,26

**Comment by hibatallahAouadni** [comment] 2023-09-18 15:12
As @Hlavtox mentioned above the issue only persist with round type for each item.
Reproduced with @RosaBenouamer 🚀

**Closed as completed** 2023-09-27 15:11 UTC
Labels: Bug, Minor, FO, Taxes and Prices, Pack, Detected by TE, Verified, 8.1.x
