### ISSUE TITLE
iso_code_num and numeric_iso_code set to zero after upgrade to 1.7.6.0

### ISSUE THREAD

**Issue by stefanovita** [PrestaShop/PrestaShop#14986] opened 2019-08-05 10:47 UTC
After upgrade to 1.7.6.0 with the one click upgrade module the currency object always returns 0 for the field "iso_code_num". Analyzing the code, in the currency object constructor there is:

`$this->iso_code_num = $this->numeric_iso_code;`

During the updgrade the new column "numeric_iso_code" is added but set to zero for all the currencies.

**To Reproduce**
1. Upgrade to 1.7.6.0 form a previous 1.7.x version with one click upgrade module.

During the updgrade the new column "numeric_iso_code" is added but set to zero for all the currencies.

There is no way to set numeric_iso_code vi admin interface, the only way is ot set the value in the db manually. 

This is breaking several payment modules, so it is a very urgent issue!

**Comment by khouloudbelguith** [comment] 2019-08-05 10:55
Hi @stefanovita,

This issue is fixed.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14664
Your ticket is a duplicate of #14608
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-08-05 10:55
Duplicate of #14608

**Closed as completed by khouloudbelguith** 2019-08-05 10:55 UTC
Labels: Duplicate
