### ISSUE TITLE
hompage link  not updated with language on header.tpl

### ISSUE THREAD

**Issue by Varindien** [PrestaShop/PrestaShop#18846] opened 2020-04-27 13:57 UTC
#### Describe the bug

if we activate multilang on website, and switch to anotherlanguage, link on logo from header.tpl is always the same.

#### Expected behavior

if we switch to english, link should be : mydomain.fr/en (and not mydomain.fr)

#### Steps to Reproduce

Activate multilanguage on shop.

#### Additional information

* PrestaShop version: 1.7.6.4 (did not see anything about this on changelog in 1.7.6.5 version)
* PHP version: 7.3

**Comment by PierreRambaud** [comment] 2020-04-27 16:07
Hi @Varindien and thanks for your report.

I don't manage to reproduce the issue, are you using the classic theme?
Could you provide us screenshots or screencast?

Kind regards

**Comment by marionf** [comment] 2020-05-27 08:03
Hello,
Since we had no news from you for more than 30 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Closed as completed by marionf** 2020-05-27 08:03 UTC
Labels: Bug, FO, Can't reproduce, Multistore
