### ISSUE TITLE
Contact form - unable to reply via link

### ISSUE THREAD

**Issue by bgolemba** [PrestaShop/PrestaShop#20886] opened 2020-09-08 07:22 UTC
#### Describe the bug
When user tries to reply to message via link the contact form throws ContextErrorException: Undefined offset: 0.
Bugs occurs only when customer previously didn't write any message via contact form (for ex. by adding message to order).
Problem lies in zeroed id_contact field in ps_customer_thread table.

#### Expected behavior
Load of contact form even if any contact isn't assigned to customer thread.

#### Steps to Reproduce
1. Place an order and add message to it during order process.
2. Reply to that message from BO (Go to: Customer service -> Customer service -> select just created thread and reply to customer).
3. Click on reply link in response message.

**Screenshots**
![1](https://user-images.githubusercontent.com/48016069/92445430-a00f8380-f1b4-11ea-81f1-32d08f85f5cb.jpg)

![2](https://user-images.githubusercontent.com/48016069/92445433-a0a81a00-f1b4-11ea-8dd0-d243237a7c92.jpg)

#### Additional information
* PrestaShop version: 1.7.6.4
* PHP version: 7.2.30

**Comment by khouloudbelguith** [comment] 2020-09-08 07:57
Hi @bgolemba,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #20041
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-08 07:57
Duplicate of #20041

**Closed as completed by khouloudbelguith** 2020-09-08 07:57 UTC
Labels: Duplicate, Contactform

**Comment by bgolemba** [comment] 2020-09-08 08:17
It's not exactly the same issue because in that case proposed solution in #20041 doesn't work.
I managed to fix that problem just by modifying that line 
from this: `if (isset($this->customer_thread['id_contact']){` 
to that: `if (isset($this->customer_thread['id_contact']) && $this->customer_thread['id_contact'] != 0) {`

**Comment by khouloudbelguith** [comment] 2020-09-08 08:19
@bgolemba, no there is no PR related to this issue: #20041.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by bgolemba** [comment] 2020-09-08 08:36
My solution to problem is just a workaround. contactform.php should be reworked as mentioned in #20041 .
