### ISSUE TITLE
Imported products do not appear in search (incorrectly indexed)

### ISSUE THREAD

**Issue by cbatista8a** [PrestaShop/PrestaShop#33112] opened 2023-07-05 10:19 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

search by reference code or name on Search Bar (FO) after CSV import. Index are checked and seems to be completely `Prodotti indicizzati 77821 / 77821.`

[Screencast from 05-07-2023 12:04:04.webm](https://github.com/PrestaShop/PrestaShop/assets/59052959/bee5126e-8501-47a0-b593-87f5a58492ac)
[Screencast from 05-07-2023 12:04:50.webm](https://github.com/PrestaShop/PrestaShop/assets/59052959/f582fe03-c456-4acf-9bea-cfb86bf6a13e)
[Screencast from 05-07-2023 12:05:31.webm](https://github.com/PrestaShop/PrestaShop/assets/59052959/14e104bc-96c9-44b1-8708-574b3b01ba49)

### Expected behavior

Show the product

### Steps to reproduce

- Import products from csv
- search by reference code or name on Search Bar (FO)
- product not found
- Go to Product Page (BO) and press "Save" button
- search again by reference code or name on Search Bar (FO)
- You will see now the product properly

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

Nextre Digital S.R.L

**Comment by florine2623** [comment] 2023-07-05 14:39
Hello @cbatista8a ,

I can't reproduce your issue with a more recent version:

https://github.com/PrestaShop/PrestaShop/assets/16019289/6b2cd40f-0c47-4d12-a28d-03f537bf9a26

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by cbatista8a** [comment] 2023-07-06 09:09
> Hello @cbatista8a ,
> 
> I can't reproduce your issue with a more recent version:
> 
>  Screen.Recording.2023-07-05.at.16.28.54.mov 
> We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
> 
> Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
> 
> Thank you

Hi @florine2623 , you test it in a wrong mode, in the issue description i indicate "BO" for Back Office and "FO" for Front Office, the issue is on "Front Office"

**Comment by MatShir** [comment] 2023-07-26 12:19
/

**Comment by kpodemski** [comment] 2023-07-26 12:23
Hello @cbatista8a 

If I remember correctly, this bug was due to the lack of indexation in the Amazzing Filter module, I'll close the issue :)

**Closed as completed by kpodemski** 2023-07-26 12:23 UTC
Labels: Bug, Invalid

**Comment by MatShir** [comment] 2023-07-26 12:31
> Hi 
> [@kpodemski (Krystian Podemski)](https://prestashop.slack.com/team/U0160HUJW79)
> , after a lot of research with the help of 
> [@Wilson Alba - Rolige](https://prestashop.slack.com/team/U04EQKMPJ3X)
> , we were able to identify the cause of this problem, we found a module that we use to handle advanced filters on product listing pages, this module implements the ProductSearchProviderInterface interface, captures the search intent and returns the result, but only if the products are also indexed by this module. It was also necessary to create the index in the configuration of the module in addition to the native PrestaShop index so that the products were visible in the search. Thanks
Actually it is solved !

-> https://prestashop.slack.com/archives/CTKG1NKAP/p1688652148665009?thread_ts=1688631273.015989&cid=CTKG1NKAP
