### ISSUE TITLE
Visual style of dropwdown is broken on file selection into import history

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#32415] opened 2023-05-02 15:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Check this screen :
<img width="941" alt="Capture d’écran 2023-05-02 à 17 29 21" src="https://user-images.githubusercontent.com/2631425/235713233-82c30a02-44b4-47bd-9bff-97ae9871b1ca.png">

As you can see, the dropdown have a space inside it.

### Steps to reproduce

1. Go to Importer
2. Download a file
3. Edit the used file
4. And see the history table.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

@Wepika

**Comment by florine2623** [comment] 2023-05-03 08:18
Hello @PrestaEdit ,

In PS `1.7.8.9`, I have the issue :
<img width="789" alt="Screenshot 2023-05-03 at 10 11 01" src="https://user-images.githubusercontent.com/16019289/235863353-f0df49f1-dc21-4d05-a025-11efe6c2fa24.png">

But in later versions `8.0.4`, `8.1.x` and `develop`, the issue is not present anymore :
<img width="622" alt="Screenshot 2023-05-03 at 10 12 59" src="https://user-images.githubusercontent.com/16019289/235863676-86462c4b-4a51-448d-9613-a2fca6d45665.png">

I have tested with multiple versions of PHP.

As this has been fixed in later versions, I'll close your issue ^^

Thanks for the report

**Closed as completed by florine2623** 2023-05-03 08:18 UTC
Labels: Bug
