### ISSUE TITLE
Prestashop 1.7.6.1 - Turkish Character Encoding Problem With Order Messages

### ISSUE THREAD

**Issue by cemalarik** [PrestaShop/PrestaShop#15944] opened 2019-10-14 16:32 UTC
Hello,

Turkish characters in order messages are encoded wrong. 
It displays correct on contact form messages.  The problem is only on order messages. 

I enter "ÖĞŞÜÇİışçüğı" as a message on order confirmation page, just after selecting carrier.

![order_message_front](https://user-images.githubusercontent.com/49948836/66767466-2b0acf80-eeb9-11e9-91e4-36bb04234805.JPG)

And when I check the message on admin page, message is converted to "&Ouml;ĞŞ&Uuml;&Ccedil;İış&ccedil;&uuml;ğı".

![order_message_bo_listing](https://user-images.githubusercontent.com/49948836/66767495-44ac1700-eeb9-11e9-8cea-faff781f6332.JPG)

![order_message_bo_detail](https://user-images.githubusercontent.com/49948836/66767500-48d83480-eeb9-11e9-9a92-d5b6c9b84c71.JPG)

Screen shot are also added.

Thanks

**Comment by khouloudbelguith** [comment] 2019-10-14 16:53
Hi @cemalarik,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15840 to fix the issue.
It is fixed in the PS1.7.7.0.
Your ticket is a duplicate of #9726
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-14 16:53
Duplicate of #9726

**Closed as completed by khouloudbelguith** 2019-10-14 16:53 UTC
Labels: Duplicate

**Comment by HartLarsson** [comment] 2025-03-27 12:53
for 1.7.6 i've post a fix here: https://github.com/PrestaShop/PrestaShop/issues/18890#issuecomment-2757705638
