### ISSUE TITLE
Installation failed 1.7.5.1, no error message

### ISSUE THREAD

**Issue by BvdPutten** [PrestaShop/PrestaShop#13398] opened 2019-04-14 09:27 UTC
Installation process stopped with an error at 45%
php7.1, Prestashop 1.7.5.1
![image](https://user-images.githubusercontent.com/35196091/56090884-39474700-5ea8-11e9-9e23-8b12530e2146.png)

**Comment by rblaurin** [comment] 2019-04-14 22:40
Are you connected over Proxy with authentication?
https://github.com/PrestaShop/PrestaShop/issues/12721#

**Comment by khouloudbelguith** [comment] 2019-04-15 10:08
Hi @BvdPutten,

Do you have an issue similar to #12721?

Thanks!

**Comment by BvdPutten** [comment] 2019-04-15 10:22
No, I never reached the stage mentioned. It seems that I need to disable server caching.
Varnish Cache need to be disable on my hosted server configuration. Unable to do that (now), so I think Presta is a nogo for me.

**Comment by khouloudbelguith** [comment] 2019-04-18 17:06
Hi @BvdPutten,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-20 07:27
Hi @BvdPutten,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-20 07:27 UTC
Labels: IN, No change required, 1.7.5.1
