### ISSUE TITLE
1-click upgrade error to upgrade to 1.7.8.10

### ISSUE THREAD

**Issue by yachaylegal** [PrestaShop/PrestaShop#34786] opened 2023-12-07 16:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am using Prestashop 1.7.8 and tried to upgrade to 1.7.8.10 
I tried to do it by using 1-Clip-Upgrade, but it shows the following error

![image](https://github.com/PrestaShop/PrestaShop/assets/153211780/a75825c5-a150-4af6-ae41-d757e899d844)

### Expected behavior

I expected to upgrade without any problems, becasuse, I have done the same process before.

I will explain: I made a backup in september and **AFTER** that I upgraded to 1.7.8.10 using 1-click upgrade. Everything went well.

So, recenttly I restored my website from a that backup (which did not include the upgrade). Since my backup did not include this update I proceed to upgrade again in the same way I did it before, but now it shows the error I mentioned.
I have attached the final part of the log fil.e

![image](https://github.com/PrestaShop/PrestaShop/assets/15321178
![log](https://github.com/PrestaShop/PrestaShop/assets/153211780/8172a90c-88f4-4eac-8cfb-f3b4ceda6929)
0/559572d8-3952-49ba-be9b-8bee9d3fa982)

### Steps to reproduce

1. I installed module 1-Click Upgrade
2. I put website in maintenance mode
3. All conditions to proceed were checked ok
4. I proceed to press UPGRADE
5. The process started 
6. Just inmediately it show the error I mentioned above.

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

native 8.2

### If your bug is related to a module, specify its name and its version

1-click upgrade

### Your company or customer's name goes here (if applicable).

Corporación Yachay SAC

**Comment by paulnoelcholot** [comment] 2023-12-11 09:13
Hello @yachaylegal 

To reproduce your problem, I need to have your initial version of PrestaShop. You said 1.7.8 but I need the 4th digit.

Thanks for your feedback!

**Comment by yachaylegal** [comment] 2023-12-11 14:15
Hello:

Here it is:

[image: image.png]



Atentamente,



*Dpto. de Atención al Cliente*(+511) 963 576 341

***@***.***
Calle Andalucia 119 Of. 302 - Lima 21 - Lima
www.yachaylegal.com

**Comment by paulnoelcholot** [comment] 2023-12-11 14:18
Hello @yachaylegal,

Your image was not uploaded correctly, can you resend it please?

**Comment by yachaylegal** [comment] 2023-12-11 14:22
Here it goes again:


Current Prestashop Version: 1.7.8.4
Current PHP version 7.3.33


[image: image.png]
Atentamente,



*Dpto. de Atención al Cliente*(+511) 963 576 341

***@***.***
Calle Andalucia 119 Of. 302 - Lima 21 - Lima
www.yachaylegal.com

**Comment by florine2623** [comment] 2023-12-13 16:10
You need to send it through GitHub, not via email.

**Comment by yachaylegal** [comment] 2023-12-14 15:21
I already did it.

Atentamente,



*Dpto. de Atención al Cliente*(+511) 963 576 341

***@***.***
Calle Andalucia 119 Of. 302 - Lima 21 - Lima
www.yachaylegal.com

**Comment by florine2623** [comment] 2023-12-21 09:16
I have upgraded from 1.7.8.0 to 1.7.8.10. It works as expected.
<img width="906" alt="Screenshot 2023-12-21 at 10 06 14" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1beb2e27-6979-49c5-a4b9-ce50efb3ff32">
<img width="1439" alt="Screenshot 2023-12-21 at 10 15 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/aa96f671-9d68-4a51-aa4f-caffeec75cf9">

https://github.com/PrestaShop/PrestaShop/assets/16019289/9909dd3c-bdbe-4878-8ef9-ddcaab8a792e



I can't reproduce your issue. I'm closing the issue to avoid clogging the backlog.

**Closed as completed by florine2623** 2023-12-21 09:16 UTC
Labels: Bug, BO, Autoupgrade, Module manager, Module
