### ISSUE TITLE
Dashgoals launches many connections to the database when accessing the dashboard 

### ISSUE THREAD

**Issue by Mmoraco** [PrestaShop/PrestaShop#23958] opened 2021-04-09 08:48 UTC
#### Describe the bug

It launches many connections to the database when accessing the dashboard that does not close or sleeps and collapses the database that in my hosting has a maximum limit of 20. 

Looking at the mysql processes in real time, the query that is executed by this module is not shown, it is only seen that a connection enters and it stays asleep until 20sg 

#### Expected behavior

When I have disabled it by renaming the dashgoasl folder everything works fine. ¿?

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2
* Module version: 2.0.2  (seen in dashgoals.php)

**Comment by florine2623** [comment] 2021-04-09 12:59
Hello @Mmoraco ,

Could you add the steps to reproduce your issue please ?
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-04-29 07:21
Hello @Mmoraco ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-29 07:21 UTC
Labels: Bug, BO, Dashgoals, No change required, 1.7.6.8
