### ISSUE TITLE
Save after adding an attachment in product page gives an error

### ISSUE THREAD

**Issue by leah68** [PrestaShop/PrestaShop#26808] opened 2021-11-30 13:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After adding by upload an attachment in the product page, when we try to save the product we get an error.

![image](https://user-images.githubusercontent.com/62328187/144055992-bc34cacb-82df-49fb-acef-7d096dcaaa5b.png)

### Expected behavior

After Save the green "Settings Updated." should popup.

### Steps to reproduce

1. Go to product page
2. Upload an attachment in Options
3. Click on the save button for register the product

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2021-11-30 13:51
Hello @leah68 

I didn't manage to reproduce the issue with PS1780, see the attached screen record below:

https://watch.screencastify.com/v/KCWhXRffW0lxS4qT7a8K

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-20 08:23
Hello @leah68 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-20 08:23 UTC
Labels: Bug, BO, Files, 1.7.8.0, Invalid
