### ISSUE TITLE
Support getting available products from category

### ISSUE THREAD

**Issue by rmilecki** [PrestaShop/PrestaShop#20507] opened 2020-08-08 16:23 UTC
#### Is your feature request related to a problem?

In some scenarios it may be desired to find category products that are **available** (quantity >= n). E.g. some shop owners may want `ps_featuredproducts` to list available products only as it's usually pointless to recommend something that can't be ordered.

#### Describe the solution you'd like

`Category`'s `getProducts()` should allow specifying minimal quantity.
`ProductSearchQuery` should allow specifying minimal quantity.

#### Alternatives you've considered

Modules may ignore `ProductSearchQuery` and implement custom SQL query on their own but that means:
1. Code duplication
2. Worse maintenance

#### Additional context

![unavailable](https://user-images.githubusercontent.com/452972/89715142-1d708a00-d9a4-11ea-8d71-b6f7305e472d.png)

**Comment by khouloudbelguith** [comment] 2020-08-10 09:37
Hi @rmilecki,

Your ticket is a duplicate of #16386
Please follow: https://github.com/PrestaShop/PrestaShop/issues/16386#issuecomment-553851735
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-10 09:37
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16386#issuecomment-553851735

**Closed as completed by khouloudbelguith** 2020-08-10 09:37 UTC
Labels: Duplicate
