### ISSUE TITLE
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18142] opened 2020-03-13 14:27 UTC
With google Chrome 80 i got this notice in FO and also backoffice:

DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-17 10:03
Hi @Betafer,

Thanks for your report.
This issue is related to the Google Maps issue.
Your ticket is a duplicate of #10393
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-03-17 10:03
Duplicate of #10393

**Closed as completed by khouloudbelguith** 2020-03-17 10:03 UTC
Labels: Duplicate
