### ISSUE TITLE
Exchange rate autoupdate not working

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#13825] opened 2019-05-16 15:30 UTC
Hello, it seems that the autoupdate function for exchange rate is not working.

Tom

**Comment by khouloudbelguith** [comment] 2019-05-17 08:13
Hi @TomHsiung,

Did you installed the cronjobs module?
What is the exact version PrestaShop did you use?
Thanks!

**Comment by TomHsiung** [comment] 2019-05-17 08:17
I use 1.7.5.2 and I don't know what the corncobs modeule is. But I browsed my module list and there is no cronjobs module. So did you mean the exchange rate autoupdate function requires the cronjobs module?

Tom

**Comment by khouloudbelguith** [comment] 2019-05-17 08:37
@TomHsiung, yes, you need to install the cronjobs module
![image](https://user-images.githubusercontent.com/16067358/57914742-25b44500-7887-11e9-9bfe-ebeb5f11054c.png)
Navigate to your BO => Module Catalog page => search for the cronjobs module & install it.
Thanks to check & feedback

**Comment by TomHsiung** [comment] 2019-05-17 08:38
Oh, let me try that. Thank you.

- Tom

**Comment by khouloudbelguith** [comment] 2019-05-17 08:39
@TomHsiung, waiting for your feedback.
Thanks!

**Comment by TomHsiung** [comment] 2019-05-17 08:42
Oh, I think I searched modules with a wrong keyword. The cron tasks manager was indeed installed when I created my shop website.

As a result, the autoupdate issue is a issue not caused by the absence of this module.

**Comment by khouloudbelguith** [comment] 2019-05-17 08:48
@TomHsiung, so the cronjobs module is installed?
Thanks!

**Comment by TomHsiung** [comment] 2019-05-17 08:50
Yep, it is there from the very beginning.

**Comment by khouloudbelguith** [comment] 2019-05-17 08:54
@TomHsiung, the Live exchange rates is enabled?
![image](https://user-images.githubusercontent.com/16067358/57915911-b2f89900-7889-11e9-96d2-3880c15acf6d.png)
Thanks!

**Comment by TomHsiung** [comment] 2019-05-17 09:18
That option had been turned on weeks earlier. But the exchange rate still remains updated.

Due to the trade conflict between China and United States, the exchange rate between currencies changes dramatically everyday. However, I have to click the Update button manually in order to get it updated.
Tom

**Comment by khouloudbelguith** [comment] 2019-05-17 10:05
@TomHsiung, thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.beta1 & the cronjobs module v1.4.0
I configured the cronjobs module to do the task every hour => but no result
![image](https://user-images.githubusercontent.com/16067358/57918055-eb01db00-788d-11e9-9bd4-a7e828a321f4.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Similar issue on forge: http://forge.prestashop.com/browse/BOOM-3534
Thanks!

**Comment by TomHsiung** [comment] 2019-05-17 10:31
It is unlikely that I were able to solve this issue. I no little about coding.

**Comment by TomHsiung** [comment] 2019-09-02 04:20
Hello, how about the progress? Still under investigation?

**Comment by khouloudbelguith** [comment] 2019-09-02 11:38
Hi @TomHsiung,

Sorry not yet.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by TomHsiung** [comment] 2019-09-02 14:13
Hello, @khouloudbelguith 
Thank you for the elucidation. Although the manual update of the currency exchange rate is annoying, I will wait your official fix.

Appreciating your hard working!

**Comment by marionf** [comment] 2021-02-25 16:06
The cronjob module is pushed by API for the versions from 1.5 to 1.6.1.24 and is not compatible with 1.7, that is the reason why you can't find it in 1.7 and why it's not working.

You can find cronjob module compatible with 1.7 on the marketplace like this one for example: https://addons.prestashop.com/fr/outils-administration/48669-sht-cronjobs.html

As this module isn't included in the core and not maintained by the core team but by PrestaShop Corp, I close this issue

You can submit an issue for this module here: https://github.com/PrestaShopCorp/cronjobs

**Closed as completed by marionf** 2021-02-25 16:06 UTC
Labels: Bug, Minor, BO, Currencies, No change required, 1.7.5.2, 1.7.6.0, cronjobs
