### ISSUE TITLE
Error 500 changing order status on multishop

### ISSUE THREAD

**Issue by pollat** [PrestaShop/PrestaShop#22156] opened 2020-11-30 09:43 UTC
Hello,

#### Describe the bug
I have a multishop on Prestashop 1.7.3.3 and If I try to change order status (on "All shops" configuration), I get this error (see image):
How can I solve this problem?

#### Steps to Reproduce

1. BO > SELL > Order > edit order
2. Change the order status like "Delivered" (on "All shops" configuration)
3. See error

`NotImplementedExeption in StockManagementRepository.php line 133: Shop contest types others than "Single shop " are not supported`

#### Screenshots

![error-order](https://user-images.githubusercontent.com/9538665/100593421-ad8e6280-32f8-11eb-8ece-572323c5a4f8.jpg)

#### Additional information

- Prestashop 1.7.3.3 version (multishop)
- PHP 7.1

**Comment by hibatallahAouadni** [comment] 2020-11-30 09:57
Hello,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- PrestaShop version (the exact version not just 1.7.3)
- PHP version

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

And please **follow the template to submit a complete bug report**.

Thanks!

**Comment by pollat** [comment] 2020-11-30 10:09
I have: 
 
- Prestashop 1.7.3.3 version (multishop)
- PHP 7.1

**Problem:** If I try to change order status, I get white page with "500 error" and if I active debug mode, is showed the error that I have posted before.

**Comment by hibatallahAouadni** [comment] 2020-11-30 11:19
Hello @pollat 

I just edit your issue description, could you please confirm the steps to reproduce.

Thanks!

**Comment by pollat** [comment] 2020-11-30 14:42
> Hello @pollat
> 
> I just edit your issue description, could you please confirm the steps to reproduce.
> 
> Thanks!

The steps are ok.

**Comment by pollat** [comment] 2020-12-02 10:13
So, how can I solve this problem?

**Comment by hibatallahAouadni** [comment] 2020-12-02 10:25
Hello @pollat 

I didn't manage to reproduce your issue with PS1.7.4.0, PS1.7.6.9 and PS1.7.7.0-rc.1, see the attached screen record below:

https://drive.google.com/file/d/1694G8xrX3dc5eq7Ybzoeszd32BJL7jtb/view

Please check and feedback.
Thanks!

**Comment by pollat** [comment] 2020-12-02 11:45
The problem is with Prestashop 1.7.3.3 version.

**Comment by hibatallahAouadni** [comment] 2020-12-02 14:03
I can't say that, I need to test with PS1.7.3.3 to confirm

**Comment by hibatallahAouadni** [comment] 2020-12-26 14:26
Hello @pollat 

I can't confirm that the issue is with PS1.7.3.3 but I can confirm that if there was an issue with PS1.7.3.3, it's already fixed with PS1.7.4.0
So, you should upgrade your version to PS1.7.6.9 :wink: 
Sorry for the late response :confused: 
But I have to close this issue cause it seems fixed.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-26 14:26 UTC
Labels: Bug, BO, Can't reproduce, Multistore, Order statuses
