### ISSUE TITLE
issue on total when change courier on admin

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#25418] opened 2021-07-24 09:27 UTC
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

when I change courier on active order, even if this flag is off (see this https://nimb.ws/JrHXi4 )  the total of the order (only the total) changes

![image](https://user-images.githubusercontent.com/1533248/126998100-70f7df63-8733-41c2-9551-0b78debf7925.png)

#### Steps to Reproduce

1. Go to 'admin-->shop parameters-->order setting-->Recalculate shipping costs after editing the order-->OFF'
2. change carrier into an active orde
4. order total changes

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.4.16

**Comment by hibatallahAouadni** [comment] 2021-07-26 13:17
Hello @centoasa 

Thanks for your issue! I think you need to downgrade your PHP version to 7.3 cause it's not compatible with PS1775 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements)).

I reproduce the issue with PS177, 178x and develop, see the attached screen record below:

https://drive.google.com/file/d/1Eg4XYl_GOGrA5oiTqmrL843dGG9biLp2/view

This is a regression! check the PS176 behavior:

https://drive.google.com/file/d/1EFhQHVdMAfZDCNFlvlH79ERjBObsBIHM/view

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-07-28 11:31
Fixed in #25428 by @Progi1984

**Closed as completed by Progi1984** 2021-07-28 11:31 UTC
Labels: Bug, develop, Minor, BO, Order, Order settings, Regression, Fixed, PR available, 1.7.7.x, 1.7.8.x
