### ISSUE TITLE
Order status doesn't change to refunded when make a refund

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/PrestaShop#28661] opened 2022-06-02 10:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I do a refund of an order. I expect status change to refund or partial refunded, but it won't change.
This is expected?

![imagen](https://user-images.githubusercontent.com/10741347/171613263-5feaeadf-d7ba-471c-938b-4ac44d1cde45.png)

### Steps to reproduce

1. Make an order
2. Do a refund or a partial refund
3. Check order status

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-06-02 16:42
Hello @rodriciru 

This is the expected behavior, please check our specs [here](https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/orders/orders/view-page.md#5-summary-of-the-standard-refund-partial-refund-and-return-product-feature) :pray: 
Closing the issue as it's not a bug.

PS: if you would like to change this behavior please open a feature request providing all details and we will gladly study it.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-06-02 16:42 UTC
Labels: Bug, Invalid
