### ISSUE TITLE
Back-office frontend wrong summary/description active tab displayed

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#12349] opened 2019-01-29 13:40 UTC
**Describe the bug**
Sometimes, in a product page of BO the summary and the description tabs are both active.

**To Reproduce**
1. Go to a product page (Basic Settings tab)
2. Click on Description sub-tab (of Basic Settings tab)
3. Click on Quantities tab
4. Get back to Basic Settings tab
5. See summary and description tabs both actives

**Screenshots**
![ps-tab-product-bug](https://user-images.githubusercontent.com/7419525/51911924-4f7a5680-23d3-11e9-9f3c-c9522c65ef1a.png)

Reproduced on official demo of Prestashop site (still v.1.7.4.2 ??) and on fresh install of 1.7.5.0.

**Additionnal information**
PrestaShop version: Reproduced on PS 1.7.4.2 and 1.7.5.0
Browsers: Last Chrome + Firefox

**Comment by khouloudbelguith** [comment] 2019-01-29 13:42
Hi @Klemart3D,

This issue is added to our debug roadmap.
Your ticket is a duplicate of #9668
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-29 13:42
Duplicate of #9668

**Closed as completed by khouloudbelguith** 2019-01-29 13:42 UTC
Labels: Duplicate

**Comment by Klemart3D** [comment] 2019-01-29 15:07
Oh sorry, I only searched issues for "product tab bug" and didn't find #9668. Thanks you :)
