### ISSUE TITLE
Order validation with cash on delivery or bank transfer payments

### ISSUE THREAD

**Issue by tmsio** [PrestaShop/PrestaShop#23367] opened 2021-02-23 17:38 UTC
#### Describe the bug
Order paid with cash on delivery o bank transfer :

1) Are are not counted in the statistics.

2) In the order list do not buy the invoice icon.

3) In the order details the Invoice button is gray out.

****************************

Hi, I have a problem with order validation, let me explain.

In the statistics I don't see all the orders paid on delivery, looking in the DB I noticed that in the ps_order table the fields invoice_number and total_paid_real are empty.

On the contrary, in ps_invoice_order the number field is correctly set.

This involves:

1) Orders without invoice_number are not counted in the statistics.

2) in the order list do not buy the invoice icon.

3) in the order details the Invoice button is gray out.

This happens when the order status is changed via webservices, as I use a centralized shipping system (shippypro).

Can anyone recommend me a workarround?

Thank you in advance.

ScreenShoot:

https://raskal.shop/img/Cattura.PNG

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.3.11
* MySQL version: 8.0.18

**Comment by hibatallahAouadni** [comment] 2021-02-24 11:12
Hello @tmsio 

Could you please provide the order_status_id please of "consegna contrassegno".

Thanks!

**Comment by tmsio** [comment] 2021-02-24 16:02
Hello hibatallahAouadni the id it s "11", this state had the same options of default "Order Payed" (id 2).
Regards

Screen:
https://raskal.shop/img/Cattura2.PNG

**Comment by tmsio** [comment] 2021-02-24 16:09
Can you provide a sql query that i would you insert in some php file:
If in ps_invoice_order the value of number it s not null
then
insert ps_invoice_order --> number in ps_order-->invoice_number

Regards
Emiliano

Then:

**Comment by hibatallahAouadni** [comment] 2021-02-24 17:59
Hello @tmsio 

Could you please downgrade your PHP version to 7.2 at first, cause PS1.7.6.2 is not compatible with PHP 7.3 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements)).

Second, is your problem about the Orders paid by **Cash on Delivery** (Order's status is **Remote Payment accepted**) are not considered in the statistics?

I'm really sorry but could you please make a screen record to understand better the problem :sweat_smile: 

Thanks in advance :pray:

**Comment by tmsio** [comment] 2021-02-24 19:07
Im sorry, prestashop version it s 1.7.7.1 , my mistake. i ll make some screen shoot and try to explain better my problem. Thank You.

Regards.
Emiliano

**Comment by tmsio** [comment] 2021-02-24 19:35
The orders paid by **Cash on Delivery** or **Bank Transfer** are not considered in the statistics.
Even if after delivery I manualy change the status of the orders to Order Paid.
All this orders are not considered in the statistics and i can t see the invoice icon in order list
Screen:
https://raskal.shop/img/Cattura.PNG

Also, in the **order dettail** the invoice button is missed.
Screen:
https://raskal.shop/img/Cattura3.PNG

The issue it s in the database.
In **ps_order_invoice**, **number** have value "159"
Screen:
https://raskal.shop/img/Cattura4.PNG

In ps_oerder, invoice_number it s 0
Screen:
https://raskal.shop/img/Cattura5.PNG

If i set invoice_number to 159 all work fine and i see the order in statistics.

My question is:
Why, when i change manualy the order to "Order paid" the invoice_number it is not valued?


I hope I was clearer.
Regards

Emiliano

**Comment by hibatallahAouadni** [comment] 2021-02-25 00:40
Hello @tmsio 

> The orders paid by Cash on Delivery or Bank Transfer are not considered in the statistics.

Could you please specify which stats: **Sales and orders** or **statsproduct** or **Best-selling products**, ...
Please check and feedback.

Thanks!

**Comment by tmsio** [comment] 2021-02-25 08:22
Hello, in Sales and orders are missed all orders paid by Cash on Delivery or Bank Transfer
Screen:
https://raskal.shop/img/Cattura6.PNG
Regards

Emiliano

**Comment by hibatallahAouadni** [comment] 2021-02-26 08:18
Hello @tmsio 

Thanks for your feedback.
I didn't manage to reproduce the issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/14QFTT-ARM7tsIya9JLiZK5b6A2lfMgoZ/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-19 08:49
Hello @tmsio ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-19 08:49 UTC
Labels: Bug, BO, Order, Invoices, Order statuses, No change required, 1.7.7.1
