### ISSUE TITLE
PDF generation does not work with a logo (jpg, png ...) 1.7.6.0

### ISSUE THREAD

**Issue by Romain-Del** [PrestaShop/PrestaShop#15043] opened 2019-08-08 15:57 UTC
After installing Prestashop 1.7.6.0
Go to Appearance -> Theme and logo -> Logo of mails / Logo of invoices
Change the logo by yours (jpg, png ...)
Then in Orders -> Orders -> [YOUR CUSTOMER] -> Documents -> Display Invoice / Delivery Note = ERROR
So if you change your logo you can't generate PDF

Or am I the only one ?
Prestashop is freshly installed, no module or customization

I have already tried several images in different formats
![Screenshot_2019-08-08 Error imagecreatefromjpeg() gd-jpeg JPEG library reports unrecoverable error Not a JPEG file starts w](https://user-images.githubusercontent.com/46653527/62718224-ba9d8900-ba05-11e9-8971-af371462e352.png)

**Comment by khouloudbelguith** [comment] 2019-08-08 16:13
Hi @Romain-Del,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a video record
https://drive.google.com/file/d/1n2JvxJjiyTZ_l2Ewa4kP9ExPlSCYhOFu/view
I tried with .png file & .jpg file.
Thanks to check & feedback.

**Comment by Romain-Del** [comment] 2019-08-08 16:41
Thank you for fast response,
i attached a video in zip
My problem is when I generate PDF

[Projet sans titre.zip](https://github.com/PrestaShop/PrestaShop/files/3482778/Projet.sans.titre.zip)

**Comment by khouloudbelguith** [comment] 2019-08-08 16:46
@Romain-Del, did you make any changes in the "Images generation options" section (BO => Design => Images Settings) Page?
Could you please provide the logo uploaded to check it.

Thanks!

**Comment by Romain-Del** [comment] 2019-08-09 07:02
I have not made any changes, everything is by default
Screenshoot of my config :
![Screenshot_2019-08-09 Images • bureauland](https://user-images.githubusercontent.com/46653527/62760364-21fa1e00-ba84-11e9-96c6-2f30caf85d5b.png)
And my logo :
![Logo BL by DBSi noir FT](https://user-images.githubusercontent.com/46653527/62760403-34745780-ba84-11e9-92e6-76e37aabcd37.jpg)
I have already try another logo like this one : https://fr.m.wikipedia.org/wiki/Fichier:AMD_Logo.svg

**Comment by khouloudbelguith** [comment] 2019-08-09 15:04
@Romain-Del, I tried with your logo & it is OK
https://drive.google.com/file/d/1Qx2VmJpRPH7lewvhIEoFVbyyF1lkg62y/view
SVG images are not supported by PrestaShop: improvement created here: https://github.com/PrestaShop/PrestaShop/issues/10600

Thanks!

**Comment by Romain-Del** [comment] 2019-08-09 16:20
I don't understand, I have two website and the same problem.
Even if I reinstall since zero

![InkedScreenshot_2019-08-09 Error imagecreatefromjpeg() gd-jpeg JPEG library reports unrecoverable error Not a JPEG file starts w _LI](https://user-images.githubusercontent.com/46653527/62793510-0a498680-bad2-11e9-87ac-20591f928ebc.jpg)


My code at line 7034 :
`				try {
					// GD library
					$img = $gdfunction($file);
					if ($img !== false) {
						if ($resize) {
							$imgr = imagecreatetruecolor($neww, $newh);
							if (($type == 'gif') OR ($type == 'png')) {
								$imgr = TCPDF_IMAGES::setGDImageTransparency($imgr, $img);
							}
							imagecopyresampled($imgr, $img, 0, 0, 0, 0, $neww, $newh, $pixw, $pixh);
							$img = $imgr;
						}
						if (($type == 'gif') OR ($type == 'png')) {
							$info = TCPDF_IMAGES::_toPNG($img, TCPDF_STATIC::getObjFilename('img', $this->file_id));
						} else {
							$info = TCPDF_IMAGES::_toJPEG($img, $this->jpeg_quality, TCPDF_STATIC::getObjFilename('img', $this->file_id));
						}
					}
				} catch(Exception $e) {
					$info = false;
				}`

You know what I can do ? or just wait patch ?

**Comment by MathiasReker** [comment] 2019-08-12 19:29
Maybe it is related this this https://github.com/PrestaShop/PrestaShop/issues/15088?

**Comment by khouloudbelguith** [comment] 2019-08-19 14:23
Hi @Romain-Del,

In your case, SSL is enabled?

Thanks!

**Comment by Romain-Del** [comment] 2019-08-21 07:42
No, SSL isn't enabled.
it's working in local with UwAmp, I have this problem only on my server (OVH), on my server before change my logo I don't see Prestashop logo like video in issue #15088 
I think I will wait the next upgrade/patch
Thanks for your help

**Comment by khouloudbelguith** [comment] 2019-08-21 09:37
@Romain-Del, Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-08-21 09:37 UTC
Labels: Bug, BO, Can't reproduce, Theme & logo, 1.7.6.0
