### ISSUE TITLE
Problem with minimum order quantity 

### ISSUE THREAD

**Issue by sonosergio** [PrestaShop/PrestaShop#10806] opened 2018-10-02 08:32 UTC
**Describe the bug**
There's a bug when a product has the minimum order quantity setted. For instance if a product has set to 10 the Minimum Order Quantity, when I add to cart the ten product and then I proceed to checkout, in this page is possible to decrease the quantity of the product in the cart. It shouldn't be possible to do that instead.

**To Reproduce**
Go to a product page with minimum order quantity 
Add ten product to the cart
Go to checkout page
It's possible to decrease the quantity of the product in the cart (but it shouldn't be possible)

**Screenshots**
![error](https://user-images.githubusercontent.com/5682550/46337420-c2dea800-c62d-11e8-85b0-e914d2fa65d3.PNG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2018-10-02 08:34
Hi @sonosergio,

We manage to reproduce the issue.
Here's the PR: #10279 to solve the issue
Your ticket is a duplicate of #10162
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-02 08:34
Duplicate of #10162

**Closed as completed by khouloudbelguith** 2018-10-02 08:34 UTC
Labels: Duplicate
