### ISSUE TITLE
Related products - exclude possibility to add product that we already editing

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15419] opened 2019-09-05 11:40 UTC
Hi team,
Just noticed that we are able to add the product that we already editing as related product.

That's regression since 1.6

![bug](https://user-images.githubusercontent.com/8243273/64338661-9de37980-cfe2-11e9-912c-ec846b7d9f7e.png)

Thanks! <3

**Comment by khouloudbelguith** [comment] 2019-09-05 12:04
Hi @PrestaShark,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9617
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-05 12:04
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9617

**Closed as completed by khouloudbelguith** 2019-09-05 12:04 UTC
Labels: Duplicate
