### ISSUE TITLE
PS 1.7.4.2 Id_country is empty

### ISSUE THREAD

**Issue by fuga00** [PrestaShop/PrestaShop#10282] opened 2018-09-04 18:55 UTC
I have a problem,

When placing an order when I fill out the address and click on it I receive error 500.

If I enable the debugger, I have:

The Address-> Id_country property is empty.

It's strange because in the address the country from default is Poland and there is no other choice.

If im am on 500error site and click back and go back to step with the address, the address is already created and you can normally place an order ...

that if I turn on any other country and I choose it in the address, it is error 500 anyway...
with default address fields is the same...

i can not reproduce this on test server...
so.. can you tell my what file i should replace to fix this?
i want to copy file form fresh install...

and last question.
its possible that is something wrong in DB?

THANKS FOR HELP :)

**Comment by khouloudbelguith** [comment] 2018-09-05 07:32
Hi @fuga00,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9812
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-05 07:33
Duplicate of #9812

**Closed as completed by khouloudbelguith** 2018-09-05 07:32 UTC
Labels: Duplicate
