### ISSUE TITLE
ORDER CONFIRMATION E_MAIL TEMPLATE

### ISSUE THREAD

**Issue by martinrepko** [PrestaShop/PrestaShop#21792] opened 2020-11-06 13:15 UTC
#### order_conf tamplate e-mail damaged when triggered from order status. 

- order_conf template set as to be sent for orders in status "Confirmed"
- when status changed to "Confirmed" or click button "resend e-mail" in ORDERS section, format and content of received e-mail is damaged
- when the same template sent as test, e-mail looks ok but content is bit different

#### Expected behavior

Template to look properly (with product list and variable values) and consistent

#### Steps to Reproduce

1. Go to orders -> order -> resend e-mail for status CONFIRMED
2. Click on Design -> e-mail theme -> modern -> order_conf -> "send test e-mail"
3. Compare received e-mails

**Screenshots**
![2020-11-06 15_38_32-98369146-c036b400-2038-11eb-9013-5dcebbb3426e png (1913×1029)](https://user-images.githubusercontent.com/67289703/98378386-3988d380-2046-11eb-9ad0-93343afb853a.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 5.6.40

**Comment by florine2623** [comment] 2020-11-06 13:54
Hi @martinrepko ,

For security reasons, please hide your admin shop url in your screenshot.

I can't reproduce the issue on my end. Emails are sent with correct format :
![Capture d’écran 2020-11-06 à 14 52 27](https://user-images.githubusercontent.com/16019289/98373567-b6647f00-203f-11eb-8b5d-8f239f4bdd56.png)
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue. 
If you have some specific questions, you can ask on the [PrestaShop Forum](https://www.prestashop.com/forums/) or directly on [slack](https://prestashop.slack.com/).
Thank you for your understanding.

**Closed as completed by florine2623** 2020-11-06 13:54 UTC
Labels: Bug, Can't reproduce, Front-end, Email theme, 1.7.6.5
