### ISSUE TITLE
Prestashop 1.7.6.x cannot remove override classes on module uninstall

### ISSUE THREAD

**Issue by fkomaralp** [PrestaShop/PrestaShop#20761] opened 2020-08-27 15:56 UTC
#### Describe the bug

Overrides not removing on module uninstall.

#### Expected behavior

I don't understand.

#### Steps to Reproduce
Hi,
I want to create a new Prestashop State,District,Neighborhood module. And I did it finally. But i have a problem on module uninstall.
I'm overriding some classes and controllers. Like AddressCore, AddressFormatCore, CustomerCore and StateCore. Plugin works perfectly on every install. Overrides is working etc. Everything is ok/working.

This is my AddressCore override ex. ss
![](https://i.snipboard.io/U91rdV.jpg)

If I want to uninstall the module (without deleting module folder). BO Page is giving this error debug page.
![](https://i.snipboard.io/MWS8tK.jpg)

And after that, I'm looked my Address.php under override/classes folder. I see this code.
![](https://i.snipboard.io/ZhzBUO.jpg)

Everything is gone. Am I wrong somewhere? This is normal?

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: php-7.3.21-nts-Win32-VC15-x64

**Comment by fkomaralp** [comment] 2020-08-27 16:16
I have experienced this now: If I remove between the **curly braces** codes in my override/classes/Address.php and override/classes/State.php; module uninstalled successfully.

**Comment by fkomaralp** [comment] 2020-08-27 23:10
After some hours later...
Ok, after some fun. I discovered something. Looks like PrestaShop's Module.php `removeOverride()` function doesn't supports static, protected etc. variables with the given value. If I setup the static variables and protected variables on the class `__construct()` what gonna happend?
I'm installed fresh PrestaShop 1.7.6.5 on my localhost and generated a demo module from https://validator.prestashop.com/generator website. Added fake override class like State.php. Code bellow.

```
<?php
class State extends StateCore
{
    public $id_country;

    public $id_zone;

    public $iso_code;

    public $name;

    public $active = true;

    public static $definition = array(
        'table' => 'state',
        'primary' => 'id_state',
        'fields' => array(
            'id_country' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => true),
            'id_zone' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => true),
            'iso_code' => array('type' => self::TYPE_STRING, 'validate' => 'isStateIsoCode', 'required' => true, 'size' => 7),
            'name' => array('type' => self::TYPE_STRING, 'validate' => 'isGenericName', 'required' => true, 'size' => 32),
            'active' => array('type' => self::TYPE_BOOL, 'validate' => 'isBool'),
        ),
    );

    protected $webserviceParameters = array(
        'fields' => array(
            'id_zone' => array('xlink_resource' => 'zones'),
            'id_country' => array('xlink_resource' => 'countries'),
        ),
    );
```
Removed all comment lines. After I'm installed the demo module with this override class State.php writed to the override/classes folder without an error/problem. After that if I hit the demo module Uninstall button I'm getted same error. 
I was said before.

Now lets try this one. Move the given values to under the `__construct()`. My code looks like that now.

```
<?php
class State extends StateCore
{ 
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $id;
    
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $id_lang;
        
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $id_shop;

    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $id_country;
    
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $id_zone;
    
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $iso_code;
    
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $name;
    
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public $active = true;
    /**
     * @see ObjectModel::$definition
     */
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public static $definition;
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    protected $webserviceParameters;
    /*
    * module: deneme
    * date: 2020-08-28 01:04:54
    * version: 1.0.0
    */
    public function __construct($id = null, $id_lang = null, $id_shop = null){
        
        self::$definition = array(
            'table' => 'state',
            'primary' => 'id_state',
            'fields' => array(
                'id_country' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => true),
                'id_zone' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => true),
                'iso_code' => array('type' => self::TYPE_STRING, 'validate' => 'isStateIsoCode', 'required' => true, 'size' => 7),
                'name' => array('type' => self::TYPE_STRING, 'validate' => 'isGenericName', 'required' => true, 'size' => 32),
                'active' => array('type' => self::TYPE_BOOL, 'validate' => 'isBool'),
            ),
        );
         
        $this->websericeParameters = array(
            'fields' => array(
                'id_zone' => array('xlink_resource' => 'zones'),
                'id_country' => array('xlink_resource' => 'countries'),
            ),
        );

        $this->id = $id;
        $this->id_lang = $id;
        $this->id_shop = $id;

        parent::__construct($id = null, $id_lang = null, $id_shop = null);
        
    }
}

...
```

After, I'm installed the module without any problem. If I hit the Uninstall module button on module page, bingo! demo module uninstalled without any errors. And my State.php override file deleted successfully. Little bit hacky mode I guess.

**Comment by khouloudbelguith** [comment] 2020-08-28 07:58
Hi @fkomaralp,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13352
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-28 07:58
Duplicate of #13352

**Closed as completed by khouloudbelguith** 2020-08-28 07:58 UTC
Labels: Duplicate
