### ISSUE TITLE
error when trying to delete a file that was imported in excel format

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28228] opened 2022-04-11 23:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I cannot delete a file that I uploaded to import products in excel format

### Steps to reproduce

1. Import
2. Select file in excel format
3. Click on next step
4. Now click on Cancel
5. Now you will have two file to select from FTP (one .csv and one .xls)
6. Try to delete (from prestashop, same page)
7. Imposible to delete it

![image](https://user-images.githubusercontent.com/62474824/162847740-6761765e-e3e9-4d7f-a507-9388d2fabbf8.png)
![image](https://user-images.githubusercontent.com/62474824/162847766-bc11aec4-3100-49a8-8799-73ea7f43485c.png)

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.28

**Comment by marwachelly** [comment] 2022-04-12 09:11
Hello @alfonsolr09,

I was able to reproduce the issue with PrestaShop version 1.7.7.8.

https://user-images.githubusercontent.com/89604350/162924549-5ab2c5d4-62ec-44d7-9d95-72cee80ccf25.mp4

I'll add this to the debug backlog so that it's fixed. Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks,

**Comment by alfonsolr09** [comment] 2022-04-13 00:03
@marwachelly thats bug its with 1.7.8.5 too

**Closed as completed** 2022-06-15 17:57 UTC
Labels: Bug, Minor, BO, Import / Export, PR available, 1.7.7.8, Verified
