### ISSUE TITLE
Impossible to update 1.7.4.4

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11347] opened 2018-11-10 08:28 UTC
Hello,

When I try to update from 1.7.4.3 to 1.7.4.4 with autoupgrade v4.4.1, nothing happen.

All the pre-Upgrade checklist is green, I click on Upgrade button, but the icone on the left top turn infinitly.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2.11
MySQL: mysqlnd 5.0.12-dev
Apache

**Comment by Rolige** [comment] 2018-11-10 18:20
Hi @BenTen,

It is very likely that the problem is due to file permissions, try changing it to:
files: `0644`
folders: `0755`

If you don't know how, [here](https://www.rolige.com/en/blog/how-to-assign-the-correct-permissions-to-my-prestashop-files-and-folders-n7) a tutorial.


Regards!

**Comment by BenTen** [comment] 2018-11-10 21:55
Thank you to reply.

- [x] I thought that too, so I change it for:
- the modules folder
- the folder autoupgrade in adminxxx

- [x] I used the [phppsinfo.php by Pierre Rimbaud](https://github.com/PierreRambaud/phppsinfo) too, to check if there is something bad with my environment but it's full green.

- [x] By doubt, I tried to change php 7.2 to 7.1

But finally, the same problem happen.

**Comment by Rolige** [comment] 2018-11-11 03:18
@BenTen The upgrade module manages everything through Ajax requests, if you have already changed the file permissions and the problem persists, the only way to go deeper into the problem is unfairly inspecting the Ajax requests in the browser console, [here](http://www.techchanging.com/how-to-check-ajax-request-and-response-in-browser/) a tutorial for google chrome.

Regards!

**Comment by BenTen** [comment] 2018-11-11 07:28
Here the errors:
https://tof.cx/image/Vacyz

**Comment by Rolige** [comment] 2018-11-11 14:44
It seems that the problem is the lack of jQuery, if you are using cache deactivate it as well as all the CCC compressions, this from the performance tab.

**Comment by BenTen** [comment] 2018-11-11 15:38
no Cache | no CCC.
I forgot to say I'm in multishop (but I guess it's not related)

**Comment by khouloudbelguith** [comment] 2018-11-12 08:37
Hi @BenTen,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by Quetzacoalt91** [comment] 2018-11-12 09:34
Hi,

I wouldn't say that jQuery isn't available. Actually, an error in a javascript script (from another module) makes the other unable to run and the upgrade javascript is among them.

I'd rather have a look at the installed modules instead, and disabling them temporarily.

**Comment by BenTen** [comment] 2018-11-13 02:17
@Quetzacoalt91 In performance > Debug mode, I disabled non PrestaShop modules and disabled all overrides.
But nothing changed.

**Comment by khouloudbelguith** [comment] 2018-11-13 08:08
@BenTen, this function doesn't work, you can follow this link: https://github.com/PrestaShop/PrestaShop/issues/9965 for more details.
You need to disable non PrestaShop modules manually.
Thanks!

**Comment by BenTen** [comment] 2018-11-14 07:34
I think I found the issue.

When we deactivate Notifications in "Advanced Parameters", the first error javascript happen for a line:
_(for my part, only "new order" was activate, so the first error was for the line):_
`  var show_new_customers = ;`
of
```
<script>
  var show_new_orders = 1;
  var show_new_customers = ;
  var show_new_messages = ;
  var jQueryVersionPS = parseInt($().jquery.replace(/\./g, ""));
</script>
```
Anyway, I activated the three notifications, the Autoupgrade seems work fine.

**Conclusion: I can't upgrade if the notifications are not activated.**

**Comment by khouloudbelguith** [comment] 2018-11-14 09:06
Hi @BenTen,

Thanks a lot for your feedback.
I manage to reproduce the issue with the 1-click upgrade v4.4.1.
When we disable Notifications in "Advanced Parameters" ( any option), an error is displayed in the console &we cannot do the upgrade, the click action on the "Upgrade PrestaShop now!" just scroll the page to the top.
![image](https://user-images.githubusercontent.com/16067358/48471401-1ed34980-e7f4-11e8-87b6-f868e44f13d1.png)
We will see how to fix it.
@Quetzacoalt91 what do you think?
Thanks!

**Comment by Rolige** [comment] 2018-11-14 15:13
Hi @BenTen,

Try this...

In the file: `/classes/controller/AdminController.php`

Change this:
```php
'show_new_orders' => Configuration::get('PS_SHOW_NEW_ORDERS'),
'show_new_customers' => Configuration::get('PS_SHOW_NEW_CUSTOMERS'),
'show_new_messages' => Configuration::get('PS_SHOW_NEW_MESSAGES '),
```

To this:
```php
'show_new_orders' => (int)Configuration::get('PS_SHOW_NEW_ORDERS'),
'show_new_customers' => (int)Configuration::get('PS_SHOW_NEW_CUSTOMERS'),
'show_new_messages' => (int)Configuration::get('PS_SHOW_NEW_MESSAGES '),
```

Clear cache and check if fix the issue.

**Comment by khouloudbelguith** [comment] 2018-11-14 15:23
Hi @Rolige,
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by Rolige** [comment] 2018-11-14 15:41
@khouloudbelguith to be honest I have not tested my fix suggestion, if @BenTen or you can corroborate it, I gladly to send the PR.

**Comment by Quetzacoalt91** [comment] 2018-11-15 11:02
Hi, this will be done in the module, I found out these variables are also defined in it: https://github.com/PrestaShop/autoupgrade/blob/900017bd5831becde0e55cfd5fd4191ed20533e1/views/templates/main.twig#L2-L7

**Comment by Quetzacoalt91** [comment] 2018-11-15 13:11
Will be fixed by https://github.com/PrestaShop/autoupgrade/pull/190

**Comment by Quetzacoalt91** [comment] 2018-11-22 11:21
The module has been released, I'm closing this issue.

Regards

**Closed as completed by Quetzacoalt91** 2018-11-22 11:21 UTC
Labels: Bug, Major, BO, Autoupgrade, 1.7.4.3
