### ISSUE TITLE
Free shipping not correctly displayed

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#15112] opened 2019-08-14 14:46 UTC
**Describe the bug**
Basket displays free shipping when total weight of purchased products higher than maximum carrier limit. Free shipping is disabled in BO. Customers can think that free shipping is available with more products purchased.

**To Reproduce**
1. make sure free shipping is disabled in BO/Shipping/Preferences
2. set some weight limits for a carrier and prices - set when over limit - carrier disabled
3. go to FO and place a product in cart, shipping is correctly displayed
4. increase quantity of the product so the total weight is over max weight set previously in carrier
5. shipping will be displayed as Free and that is not correct and it is misleading - it should be displayed as N/A or something like that

![free-disabled](https://user-images.githubusercontent.com/31688689/63030437-98e34c80-beb2-11e9-8085-28cd1e047ff9.png)
![free-over-weight](https://user-images.githubusercontent.com/31688689/63030446-9da80080-beb2-11e9-9608-72a754beb557.png)

**Additional information**
PrestaShop version: 1.7.5.1 - 1.7.6.0
PHP version: 7.1.31

**Comment by mariem-abid** [comment] 2019-08-14 15:22
Hi @mrabsinthe,

I did not manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1txyDlkQAM34NDYRr7GBXLrCBbr5Do1G5/view

Thanks for check and feedback.

**Comment by mrabsinthe** [comment] 2019-08-14 15:49
In you carrier settings, step 4 you have the following:
If the order is out of range, the behaviour is to apply the cost of the highest defined range.
That is why you cannot duplicate the issue.
You need to change Out-of-range behaviour in step 2.

**Comment by mariem-abid** [comment] 2019-08-16 10:05
Hi @mrabsinthe,

I change the out-of-range to "Disable" and I did not manage to reproduce the issue
I attached a video record.
https://drive.google.com/file/d/1Xkj0aKQstfGWAmImLbOpWxZHp9waWObB/view

Thanks for check and feedback.

**Comment by mrabsinthe** [comment] 2019-08-16 10:18
Because you have My Carrier enabled. Try with "test" carrier only please.

**Comment by mariem-abid** [comment] 2019-08-16 10:51
@mrabsinthe, I manage to reproduce the issue  with the last version 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1ue8k52hJvyHRWEmqqjNi5s80J2F8QgcG/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by mrabsinthe** [comment] 2019-08-16 10:56
Would be great if it is fixed in 1.7.6.1 as this could cause many confused customers!

**Comment by marionf** [comment] 2019-08-16 12:31
@mariem-abid Could you please try to reproduce it with PS 1.7.5.2 ?

**Comment by mariem-abid** [comment] 2019-08-16 13:01
@marionf, the same issue.

**Comment by marionf** [comment] 2019-08-16 16:26
Hello @mrabsinthe 

Your issue is a duplicate of #10739, you should follow this issue
A Pull request is already in progress to solve this issue: https://github.com/PrestaShop/PrestaShop/pull/13517

Regards

**Closed as completed by marionf** 2019-08-16 16:26 UTC
Labels: Bug, Major, FO, Duplicate, Shipping, 1.7.5.2, 1.7.6.0
