### ISSUE TITLE
Error when filtering in Product BO

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#25373] opened 2021-07-19 08:03 UTC
#### Describe the bug

Hello,

I have an error when I want to filter the inactive products.

Can you help me?

For info, I also put this correction: 
https://github.com/PrestaShop/PrestaShop/pull/23584/files

Thanks

**Screenshots**

![image](https://user-images.githubusercontent.com/25744417/126124432-4b917fec-14b2-49c1-8790-4194b7a3d18f.png)
![image](https://user-images.githubusercontent.com/25744417/126124475-9614aad6-5700-4038-a225-0f29b95b19cc.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-07-19 11:07
Hello @ShaimyWinda 

I didn't manage to reproduce your issue, so could you please enable debug mode to understand better the problem.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-08-09 07:24
Hello @ShaimyWinda 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-09 07:24 UTC
Labels: Bug, BO, No change required, 1.7.7.2
