### ISSUE TITLE
Display "Free shipping" cart rule as an amount rule

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#13644] opened 2019-05-03 08:13 UTC
**Describe the bug**
A weird discount is displayed when a free shipping cart rule is applied. Instead of "-0.00%" it should be displayed the shipping cost

**To Reproduce**
1. Create a "Free shipping" cart rule
![image](https://user-images.githubusercontent.com/15104724/57126085-f2a08a80-6d8b-11e9-961b-8f7343829443.png)

2. Check cart
![image](https://user-images.githubusercontent.com/15104724/57126102-ffbd7980-6d8b-11e9-8a94-860f3e686580.png)

**Additionnal information**
PrestaShop version: 1.7.5.1

**Comment by idnovate** [comment] 2019-05-03 08:21
Sent PR

https://github.com/PrestaShop/PrestaShop/pull/13645

**Comment by khouloudbelguith** [comment] 2019-05-03 08:26
Hi @idnovate,

Thanks a lot for your fix.
Your ticket is a duplicate of #9702
So, I close it.
Thanks !

**Closed as completed by khouloudbelguith** 2019-05-03 08:26 UTC
Labels: Duplicate
