### ISSUE TITLE
Problem with Image/Label related products in product page - administration panel

### ISSUE THREAD

**Issue by Nerque** [PrestaShop/PrestaShop#17781] opened 2020-02-21 21:11 UTC
> Edit by Khouloud

Steps to reproduce the issue:
1. Install PS with English language / France country (you will have two languages)
2. Change the default language to French
3. Disable the English language
4. Change the employee language to FRench
5. Go to the BO => Product page
6. Create two products PRODUCT1 and PRODUCT2.
7. Edit PRODUCT1 and add PRODUCT2 as a related product.
8. Save and exit from the edition of PRODUCT1.
9. Enter again in an edition of PRODUCT1.
10. see the error
![image](https://user-images.githubusercontent.com/16067358/75998249-d2d47880-5f00-11ea-8a79-24ac5d89b540.png)

-------------------------

The same thing that others reported long ago

When you set up related products, the product page in the admin panel works fine, but if you set it up, save it, exit from the product page and go back in, you don't see the images or the names of the related products, just the reference.

As others said before, the problem is only in the administration panel. In the FO you can see everything perfectly.

What I could see is that the file name of the image is not correct, it just appears as ".jpg" without any name. Of course, it's impossible to render and that's why the icon of the not found image appears.

And with the label of the related product, the same thing. Only the reference appears, but not the name of the related product.

This problem is only fixed when you configure it not to use the friendly urls.

Then, I think it's useless to give the browser logs, because it's a server-side problem. The driver or class that takes care of getting the images and label configured for the related products, doesn't work well when the friendly urls are enabled.

The same could be due to the templates that Symphony uses... ...I don't know.

The only explanation for this not happening to others is the language of the shop (Spanish in my case) or the fact of using several languages.

But I've tried the same with the English interface, and it's exactly the same.

I have already tried to regenerate the images. But the same, as the others said a year ago.

And I've also put in debugging, but the truth... it's quite useless in many cases. It doesn't say anything.

And little else...

---------------------

Prestashop 1.7.6.3
PHP 7.2
MariaDB 10.3

(phpinfo is not necessary)

**Comment by khouloudbelguith** [comment] 2020-02-24 10:47
Hi @Nerque,

>The only explanation for this not happening to others is the language of the shop (Spanish in my case) or the fact of using several languages.
But I've tried the same with the English interface, and it's exactly the same.

What is the exact language/country did you use during the install?

The employee language is Spanish? is it the language by default?

For the other languages, did you create them manually or did you upload some country packs?

Thanks!

**Comment by Nerque** [comment] 2020-02-25 18:22
I have installed Prestashop in two websites, both in English (USA), because the installation from Plesk in other languages does not work in all cases.
So, in one of the shops I have English disabled and I have installed the Spanish package.
With the other one, I have disabled the English (USA), and I have installed the Spanish, German, Italian, French, Portuguese, and English (GB) package.
In both websites, the same problem.
I would like to know which method generates the string with the image filename, and the template file where the string is used, and debug from there.

**Comment by florine2623** [comment] 2020-02-26 13:59
Hello @Nerque ,
Despite our several trials, we could not reproduce your issue with the provided information.
Please check my video and give us feedback.
[video.mp4.zip](https://github.com/PrestaShop/PrestaShop/files/4256093/video.mp4.zip)

Thanks!

**Comment by Nerque** [comment] 2020-02-28 18:28
Hello @florine2623

I found the problem (It's a prestashop bug)

In my case, English(English) is off, because I am using English(GB). But English(English) is the first language installed in the shop, id_language=1. I haven't deleted it, just disabled it.

As I don't have English(English) activated, I don't have the possibility to edit the name and descriptions in this language, only in the languages I have activated. As it could be the English(GB).

When I select a related product, the "plugin" or whatever, which displays the related product in the list of related products, displays the product in the language of the active language in the profile. But if you leave the product page, and come back in, the same plugin or whatever shows the list of related products, tries to show the name of the product in English (English). 

I guess it tries that because it's the language with id_language=1. In your case, I see that it's French (France), but unlike me, you have French (France) enabled in the shop.

Therefore, it is a bug in Prestashop, because, Prestashop allows you to disable the default language installed in Prestashop and select another one as the default language. And in this case, people who edit the product page do not have access to English translations, and therefore they will never be able to fill in the texts in that language.

If you want to reproduce the problem, try installing the French (Canada) package, deactivate the French (France), and add a new product (so that it does not let you add the name or descriptions in French (France). In that case, you would have the same problem as me with English (English).

Greetings

**Comment by khouloudbelguith** [comment] 2020-03-02 14:52
@Nerque, I did not manage to reproduce the issue with PS1.7.6.3.
https://drive.google.com/file/d/1LT_eFWEmL3-T4cZVcpEeCbuDnrDBmegH/view
The language related products names in BO product settings will be shown in English as reported here: https://github.com/PrestaShop/PrestaShop/issues/17822

Thanks!

**Comment by Nerque** [comment] 2020-03-05 15:29
In the video I see that you have related to product B (created with English disabled), a product that was created before. Probably, with English(English) enabled.
You must relate a product, in Product B, that was created with English(English) disabled.

1. Disable English(English)
2. Create two products PRODUCT1 and PRODUCT2.
3. Edit PRODUCT1 and add PRODUCT2 as related product.
4. Save and exit from edition of PRODUCT1. 
5. Enter again in edition of PRODUCT1.

**Comment by khouloudbelguith** [comment] 2020-03-05 15:45
@Nerque, thanks a lot for these clarifications.
I manage to reproduce the issue with PS1.7.6.3 and PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/75997661-f77c2080-5eff-11ea-830f-8dec9c92f1f0.png)
https://drive.google.com/file/d/1eUDvRxrU6V8sMYC_K2wq8-0GFeAPc_2_/view
Steps to reproduce the issue:
1. Install PS with English language / France country (you will have two languages)
2. Change the default language to French
3. Disable the English language
4. Change the employee language to FRench
5. Go to the BO => Product page
6. Create two products PRODUCT1 and PRODUCT2.
7. Edit PRODUCT1 and add PRODUCT2 as a related product.
8. Save and exit from the edition of PRODUCT1.
9. Enter again in an edition of PRODUCT1.
10. see the error

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

Related to https://github.com/PrestaShop/PrestaShop/issues/17822

**Comment by Nerque** [comment] 2020-03-06 13:50
Thank you for your patience and time. I was beginning to think I was crazy.

To try to correct it, for myself, I would need to know the method that queries the name of the related product name and displays it in the product administration panel.

Either way, I'm sure there are others with more knowledge about the subject who can easily solve it.

So I have to wait for it to be solved. I don't know if those who opened all the previous threads and didn't make themselves understood got any solution...

**Comment by florine2623** [comment] 2024-01-03 15:07
Following the steps from the issue, I can't reproduce the bug. It is fixed in PS 8.1.x :

From step 7 :
https://github.com/PrestaShop/PrestaShop/assets/16019289/fb268246-4ace-4d91-a062-d6ce8808618a

I'm closing the issue.

**Closed as completed by florine2623** 2024-01-03 15:07 UTC
Labels: Bug, Minor, BO, Image, Languages, Fixed, 1.7.5.2, 1.7.6.3
