### ISSUE TITLE
Unknown column 'id_tax_rules_group' in 'where clause' while TaxRuleGroup updating

### ISSUE THREAD

**Issue by dpuhach** [PrestaShop/PrestaShop#32317] opened 2023-04-25 09:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

While TaxRuleGroup updating an error was appeared due to the fact that carrier table doesn't contain 'id_tax_rules_group' field.

https://github.com/PrestaShop/PrestaShop/blob/15e537dfa820b729980ca5ca58b7eff707b22f67/classes/tax/TaxRulesGroup.php#L115

https://github.com/PrestaShop/PrestaShop/blob/023d9f19c2cafb644dcc4ab8f1121984d499770d/install-dev/data/db_structure.sql#L83

### Expected behavior

Updating without errors.

### Steps to reproduce

1. Update tax rule group when this tax rule group is already used.
2. In this case TaxRuleGroup::historize will be run and you get this error.

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-04-25 13:23
Hello @dpuhach ,

What exactly is the issue ? Could you further explain it please ? I can't reproduce it.

Please send a screen record of the issue.

https://user-images.githubusercontent.com/16019289/234289886-32ab7623-41ed-4497-b335-9e86e84b3cca.mov

Thanks

**Comment by dpuhach** [comment] 2023-04-26 15:16
Hello @florine2623 

![image](https://user-images.githubusercontent.com/56586957/234619273-cf8c4a21-afda-4dda-8c82-7741fc0cc1b6.png)

This happens while saving Tax Rules Group (even without any changes with tax rules). 
Important thing: this Tax Rules Group must be an already "used" group (for example, in any customer's order).

I get this error when debug mode is enabled. Maybe in other cases it won't be visible.

Please check the mentioned by me code lines. It's pretty simple to understand the issue ("id_tax_rules_group" column is missed in 'PREFIX_carrier' table).

**Comment by florine2623** [comment] 2023-04-28 12:51
Hello @dpuhach ,

Thanks. I managed to reproduce your issue with PS `8.0.x` and `develop` :x:
On PS `8.1.x` and PS `1.7.8.9`, it is OK ✅ 

1. Product with my tax rule group :
<img width="1235" alt="Screenshot 2023-04-28 at 14 32 28" src="https://user-images.githubusercontent.com/16019289/235150030-b1a621b6-e453-4c43-8b3a-23b18a050edf.png">

2. Order considered as payed with my product :
<img width="1219" alt="Screenshot 2023-04-28 at 14 32 45" src="https://user-images.githubusercontent.com/16019289/235150047-21020865-7574-4dc6-adc9-a5cecb86ff5b.png">

3. Edition of my tax rule group with a payed order :
<img width="1227" alt="Screenshot 2023-04-28 at 14 33 17" src="https://user-images.githubusercontent.com/16019289/235150076-88716c8b-7b12-4138-9dd4-bbed92e68450.png">

Exception is displayed : 
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_tax_rules_group' in 'where clause'`

It is a regression. In PS `1.7.8.9`, there's no exception :
<img width="1427" alt="Screenshot 2023-04-28 at 14 48 31" src="https://user-images.githubusercontent.com/16019289/235151830-31254986-ce52-445c-b66f-8a072f74a7ab.png">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by LameuleFR** [comment] 2023-11-01 10:08
Hello @florine2623 
I also have the issue with PS 8.1.2 & PHP 8.1

**Comment by LameuleFR** [comment] 2023-11-01 10:37
The problem seem to be also present with PS 1.7.8.9 because the db structure don't contain this collumn.
https://github.com/PrestaShop/PrestaShop/blob/f39b7a843ed779258ee7c5340e94a5f3f9da9724/install-dev/data/db_structure.sql#L84C14-L84C14

If we look at PS 1.7.7.5 for example, the column is present in the data structure: https://github.com/PrestaShop/PrestaShop/blob/535b624d9ef522f4b5d3fc1c306e4ecb6a883236/install-dev/data/db_structure.sql#L98

**Comment by Hlavtox** [comment] 2024-02-27 10:23
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34450

**Closed as completed by Hlavtox** 2024-02-27 10:23 UTC
Labels: Bug, Minor, BO, Tax rules, Regression, Verified, 8.0.2
