### ISSUE TITLE
[BUG] It is possible to externally create a set of addresses entries

### ISSUE THREAD

**Issue by bertoferrero** [PrestaShop/PrestaShop#25945] opened 2021-09-21 10:45 UTC
A possible bug is found in the CustomerAddressPersister that allows creating addresses externally. It could be tested using Postman or similar, just send the form body to address controller on a POST request and the persister will create a non-customer linked address (id_customer = 0).

Pull-request with the suggested fix: https://github.com/PrestaShop/PrestaShop/pull/25944

**Comment by florine2623** [comment] 2021-09-21 11:34
Hello @prestaquality ,

Could you follow the Bug report template, so we can reproduce the bug ?

<img width="627" alt="Screenshot 2021-09-21 at 13 33 15" src="https://user-images.githubusercontent.com/16019289/134163418-11674f25-99ee-42af-a40c-4598426fb606.png">

Thanks!

**Comment by florine2623** [comment] 2021-09-28 13:34
Hello @prestaquality ,

I see that you submitted a new PR. Can you update your issue so it can be tested ?

**Comment by hibatallahAouadni** [comment] 2021-10-11 12:55
Hello @prestaquality 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-10-11 12:55 UTC
Labels: Bug, CO, Addresses, No change required, PR available
