### ISSUE TITLE
Customer's message to order at checkout

### ISSUE THREAD

**Issue by hejmi** [PrestaShop/PrestaShop#25472] opened 2021-07-30 11:57 UTC
#### Describe the bug

Don't know if it's a bug or if it's supposed to be like this.
When a customer leaves a message at checkout the message is added to the database with option "private = 1", which results in that the customer can't view this message afterwards. 

#### Expected behavior

Private set to 0 in db, customer can view the message added to the order. 

#### Steps to Reproduce

Add message to order at checkout, go to "My Account" in FO and see details for the order.
Message is not visible, but all other messages added here will be visible for both customer and in BO

**Screenshots**

none

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3

**Comment by khouloudbelguith** [comment] 2021-07-30 13:02
Hi @hejmi,

Thanks for your report.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15614 to fix the issue.
It is fixed in the next release 1.7.8.0
Your ticket is a duplicate of #9769
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-07-30 13:02
Duplicate of #9769

**Closed as completed by khouloudbelguith** 2021-07-30 13:02 UTC
Labels: Duplicate

**Comment by hejmi** [comment] 2021-07-30 13:20
@khouloudbelguith awesome! Thank you very much!
