### ISSUE TITLE
ps_reminder invalid cron link

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#18570] opened 2020-04-10 11:36 UTC
Hi. PS 1.7.6.4 and latest ps_reminder module installed from modules menu.

- no ssl (when store has ssl)
- wrong module name in cron link
http://domain.test/modules/modules/**followup**/cron.php?secure_key=L0GKS9NDVLEHNUTM
instead of
https://domain.test/modules/**ps_reminder**/cron.php?secure_key=L0GKS9NDVLEHNUTM
- old style email templates

**Comment by florine2623** [comment] 2020-04-10 12:15
Hi @PrestaShark ,
- In module ps_reminder the SSL is activated : 
![Capture d’écran 2020-04-10 à 14 08 04](https://user-images.githubusercontent.com/16019289/78989905-328ff600-7b35-11ea-9e7f-f4ff6125beb4.png)

For the other issues I will ping our Product Team.
Thanks !

**Comment by florine2623** [comment] 2020-04-10 12:16
Hi @PrestaShop/prestashop-product-team ,

In module ps_reminder, Customer follow-up, version 2.0.0,two things need to be checked out : 

- Cron link is not correct : 
![Capture d’écran 2020-04-10 à 14 05 17](https://user-images.githubusercontent.com/16019289/78989997-7c78dc00-7b35-11ea-8898-f94caa8d04c6.png)

- Old style email : 
![Capture d’écran 2020-04-10 à 14 13 55](https://user-images.githubusercontent.com/16019289/78990014-8bf82500-7b35-11ea-9e78-42f3ccf05f68.png)

What do you thing about these requests ?
Thanks !

**Comment by khouloudbelguith** [comment] 2020-04-10 17:44
Hi @PrestaShark,

Your ticket is a duplicate of #9799
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-04-10 17:44
Duplicate of #9799

**Closed as completed by khouloudbelguith** 2020-04-10 17:44 UTC
Labels: Feature, BO, Duplicate, Customer reminder, 1.7.6.4
