### ISSUE TITLE
Admin Navigation Notification in Back Office show HTML

### ISSUE THREAD

**Issue by ArteInfoRM** [PrestaShop/PrestaShop#31795] opened 2023-03-15 12:19 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
![Screenshot_13](https://user-images.githubusercontent.com/41371761/225307478-f3da01ae-7809-4a1d-9952-6528a2cfe240.jpg)

In BackOfficine HTML code is shown in Notification the string:

- **Have you checked your [1][2]abandoned carts[/2][/1]?[3]Your next order could be hiding there!**
**is shown as:**
No new order for now :(
Have you checked your **&lt;strong&gt**; &lt;a href="https://yoururl/index.php?controller=AdminCarts&action=filterOnlyAbandonedCarts&token=XXX"&gt;abandoned carts&lt;/a&gt;&lt;/strong&gt;?&lt;br&gt;Your next order could be hiding there!

### Steps to reproduce

- In a new clean install of PS 8.0.1 go to the top right on the bell icon

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by djoelleuch** [comment] 2023-03-15 14:12
Hello @ArteInfoRM , 
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #29940 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as not planned by djoelleuch** 2023-03-15 14:12 UTC
Labels: Bug, Duplicate, Invalid
