### ISSUE TITLE
After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#17788] opened 2020-02-23 10:42 UTC
**Describe the bug**

I resolved the problem with GitHub Code. But wont to draw your attantion that this issue was not fixed in the 1.7.6.1 as was announce and it still exist.

After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error".
In some menu item like Tool Panel all is Ok, but the accesss to the Catalog or some other menu is have such result
![image](https://user-images.githubusercontent.com/50954519/75110612-ed713c80-5638-11ea-9e8f-b9f9c7ec73d8.png)

In the FO all look Ok, exept some details like path to img in the SmartBlog module.
Order process , Search, facetedsearch work properly.

In the debug mode
"An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.controller = ? AND t0.action = ? LIMIT 1' with params [1, 1, "ProductController", "catalogAction"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.filter_id' in 'field list'"

The problem in the BO. Please help me.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-02-24 08:36
Hi @photinia73,

This issue is fixed previously as reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14617
As a Provisional solution thanks to try with this SQL query

> ```
> ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;
> ```

Thanks to check & feedback.

**Comment by photinia73** [comment] 2020-02-24 13:43
I used his one ALTER TABLE `PREFIX_admin_filter`         ADD `filter_id` VARCHAR (255) DEFAULT '' NOT NULL AFTER `shop`,  DROP INDEX IF EXISTS `admin_filter_search_idx`,  DROP INDEX IF EXISTS `search_idx`,         ADD UNIQUE INDEX `admin_filter_search_id_idx` (`employee`, `shop`, `controller`, `action`, `filter_id`);``` Because short variant resolve the access to Product division but leave the access problem to the some division in the BO like stuff… З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 10:36Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788) Hi @photinia73,This issue is fixed previously as reported in this ticket: #14617As a Provisional solution thanks to try with this SQL queryALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;Thanks to check & feedback.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by khouloudbelguith** [comment] 2020-02-24 13:47
@photinia73, could you please try to delete the table ps_admin_filter & re-upload it again from a fresh install PS1.7.6.3.

Please make sure you have a backup of your database & your files.

Thanks!

**Comment by photinia73** [comment] 2020-02-24 13:58
-->I updated my PS from 1.7.5.2 to 1.7.6.3 just 2 days ago, so it fresh enough )) … And I was shocked from such strange bug – impossible access my Catalog in BO. The BO work now correctly and I scare to delete something because I’m not a cool programmer, just a little bit web master )) Upgraded from here The 1-click upgrade module is up-to-date (your current version is v4.10.1)      З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 15:47Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788)

**Comment by khouloudbelguith** [comment] 2020-02-24 14:11
@photinia73, your comments are not clear, there are extra texts.
>fresh install PS1.7.6.3

A new install PS1.7.6.3 and not an upgrade from a previous version.
I think that the structure of your table ps_admin_filter is not correct.

>The BO work now correctly and I scare to delete something because I’m not a cool programmer, just a little bit webmaster 

So, the issue is fixed? can we close the ticket?

Thanks!

**Comment by photinia73** [comment] 2020-02-24 14:22
Yes, this ticket you can close. I just wanted draw your attention that after upgrade to 1.7.6.3 I had a problem with BO and it was resolved with SQL query.It mean that the error  still had a place in the fresh version 1.7.6.3 ! З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 16:11Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788) @photinia73, your comments are not clear, there are extra texts.fresh install PS1.7.6.3A new install PS1.7.6.3 and not an upgrade from a previous version.I think that the structure of your table ps_admin_filter is not correct.The BO work now correctly and I scare to delete something because I’m not a cool programmer, just a little bit webmasterSo, the issue is fixed? can we close the ticket?Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by khouloudbelguith** [comment] 2020-02-24 14:23
@photinia73, thanks for your feedback.
Since it is fixed, I will close the issue.
Feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-24 14:24 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.6.3

**Comment by photinia73** [comment] 2020-02-24 14:25
And I have a new question.I read that in the PS 1.7.6 must be realized  the product review with a stars ))) But didn`t found it. Will it appear in the future release?  З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 16:11Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788) @photinia73, your comments are not clear, there are extra texts.fresh install PS1.7.6.3A new install PS1.7.6.3 and not an upgrade from a previous version.I think that the structure of your table ps_admin_filter is not correct.The BO work now correctly and I scare to delete something because I’m not a cool programmer, just a little bit webmasterSo, the issue is fixed? can we close the ticket?Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by khouloudbelguith** [comment] 2020-02-24 14:34
@photinia73, you need to install the ps_productcomment module.
![image](https://user-images.githubusercontent.com/16067358/75160352-22a18b80-571a-11ea-830f-b079908b2e05.png)

Thanks!

**Comment by photinia73** [comment] 2020-02-24 22:02
З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 16:34Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788) @photinia73, you need to install the ps_productcomment module.Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by photinia73** [comment] 2020-02-24 22:08
I will be apresiate if you will explain how install code from GitHub.I find such release https://github.com/PrestaShop/productcomments/releases/tag/v4.0.1But when try install it my PS wrire that this The file is not a module’s archive I don’t know what’s wrong (( З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: понедельник, 24 февраля 2020 г. в 16:34Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788) @photinia73, you need to install the ps_productcomment module.Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by khouloudbelguith** [comment] 2020-02-25 11:54
@photinia73, you can find this module in the BO => Module => Module Catalog page.
From GitHub, you need to install dependencies of this module after cloning it from GitHub.
[productcomments.zip](https://github.com/PrestaShop/PrestaShop/files/4249825/productcomments.zip)

Thanks!

**Comment by photinia73** [comment] 2020-02-25 12:15
If it will be in the Module catalog it will be grate.Unfortunately in my BO only few others modules are proposed З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: вторник, 25 февраля 2020 г. в 13:54Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788) @photinia73, you can find this module in the BO => Module => Module Catalog page.From GitHub, you need to install dependencies of this module after cloning it from GitHub.productcomments.zipThanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by photinia73** [comment] 2020-02-25 12:38
If I try to nstall this module the answer is ERROR З повагоюКричмарівська Світлана От: khouloudbelguithОтправлено: вторник, 25 февраля 2020 г. в 13:54Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] After upade to 1.7.6.3 in the BO The server returned a "500 Internal Server Error". (#17788) @photinia73, you can find this module in the BO => Module => Module Catalog page.From GitHub, you need to install dependencies of this module after cloning it from GitHub.productcomments.zipThanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
