### ISSUE TITLE
Declination creation issues

### ISSUE THREAD

**Issue by LSClaire** [PrestaShop/PrestaShop#10994] opened 2018-10-12 15:22 UTC
**Describe the bug**
Trying to create a new products and its declinations with 2 attributes: colour and size. I have hundreds of products successfully created with these same attributes. 
The declinations are not all sorted the same way, which create conflicts in front office. Some consider the colour first, other the size first. 
Create declination colour A size 1 / colour A size 2 / colour B size 1. In the declinations list you get: colour A size 1 / colour A size 2 / size 1 Colour B (instead of Colour B size 1) 
In front office, select colour A size 2 and then change for colour B (which doesn't exist in size 2). It doesn't tell me that the product doesn't exist and allows me to add to cart, which then creates an error. 
This error doesn't occur when the declinations are created properly in BO, but once it's created I don't have any option to sort it or select what is the first attribute.
I ran many tests but can't find any pattern. 

**To Reproduce**

**Screenshots**
<img width="1388" alt="capture d ecran 2018-10-12 a 17 08 02" src="https://user-images.githubusercontent.com/43815115/46878173-e205e280-ce42-11e8-8d66-22b0841f7145.png">

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-12 15:26
Hi @LSClaire,

The exactly main issue is that all the attributes are ordered by id.
Sorting by positions doesn't work.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9836
So, I close it.
Thanks!
PS: For a quick fix, you need to recreate in order all these attributes.

**Comment by khouloudbelguith** [comment] 2018-10-12 15:26
Duplicate of #9836

**Closed as completed by khouloudbelguith** 2018-10-12 15:26 UTC
Labels: Duplicate

**Comment by LSClaire** [comment] 2018-10-12 15:34
How can I recreate an attribute when hundreds of existing products are using it? This is not possible... I hope it's fixed soon because this is a real problem.

**Comment by LSClaire** [comment] 2018-10-12 15:49
I checked the initial post and it's not the same issue. Have you checked my screenshot? My issue is in product creation, not in attribute creation.

**Comment by khouloudbelguith** [comment] 2018-10-12 15:52
@LSClaire, yes, there is a weird creation order for combinations.
In the product page / combination tab, all the attribute are ordered by id.
