### ISSUE TITLE
The validation of the bank is not taken into account by PrestaShop 1.7.6.0

### ISSUE THREAD

**Issue by flyman30** [PrestaShop/PrestaShop#14834] opened 2019-07-23 16:11 UTC
Hello everyone.

I am looking to install the Crédit Agricole E-transaction module (Paybox) on my Prestashop 1.7.6 site.

When I try to place an order to check the correct operation of my module. I receive by mail, a Paybox payment ticket telling me the transaction has taken place. But Prestashop does not validate the order. However, it is well created in the database and in BO but is simply not validated. When I look at the logs of the E-transaction module, here's what I get:
``

2019-07-22 18:07:43 1563811663 DEBUG: Cart 1102: Standard IPN
2019-07-22 18:07:43 1563811663 DEBUG: Cart 1102: Validating order
2019-07-22 18:07:44 1563811664 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 0).
2019-07-22 1﻿8:07:45 1563811665 DEBUG: Call params: M=5900&R=1102%20-%20Kevin%20TEST%20IMPACT%20WEB&T=51636600&A=XXXXXX&B=0&C=Maestro&D=2012&E=00000&I=FRA&J=44&N=111122&P=CARTE&Q=18%3A07%3A30&S=30446761&W=22072019&Y=FRA&K=NULaHOZYkzYfrnYrQ%2FPlKr2Ty6B7pXHUBn3abbyNw2DnlezWnfGXWCW5FRibt9%2Fls5mp5hAdbA2HnbI%2BOGWXn4XbXl0pSXExDeWhU6ZTg2BI270CTIWDnIeGFeEQO7jZfdN6FfCD7%2BiqVz7fn7BFcr4MoEGy3btZAW4R5uZmm18%3D
2019-07-22 18:07:45 1563811665 DEBUG: Cart 1102: (IPN) Cart already being validated as order with the transaction 30446761.
2019-07-22 18:07:46 1563811666 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 1).
2019-07-22 18:07:47 1563811667 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 2).
2019-07-22 18:07:48 1563811668 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 3).
2019-07-22 18:07:50 1563811670 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 4).
2019-0﻿7-22 18:07:51 1563811671 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 5).
2019-07-22 18:07:52 1563811672 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 6).
2019-07-22 18:07:53 1563811673 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 7).
2019-07-22 18:07:55 1563811675 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 8).
2019-07-22 18:07:56 1563811676 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 9).
2019-07-22 18:07:57 1563811677 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 10).
2019-07-22 18:07:58 1563811678 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 11).
2019-07-22 18:08:00 1563811680 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 12).
2019-07-22 18:08:01 1563811681 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 13).
2019-07-22 18:08:02 1563811682 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 14).
2019-07-22 18:08:03 1563811683 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 15).
2019-07-22 18:08:04 1563811684 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 16).
2019-07-22 18:08:06 1563811686 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 17).
2019-07-22 18:08:07 1563811687 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 18).
2019-07-22 18:08:08 1563811688 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Waiting order validation (loop 19).
2019-07-22 18:08:09 1563811689 DEBUG: Cart 1102: Customer is back from E-Transactions payment page. Order not validated.

After the transaction, when I come back to my site. I get a page "next to the validation of your order" which reloads loop a dozen times before redirecting me to the home of my site. By reading the FAQ of Paybox, this is due to the fact that the latter can not validate the order by my site.

After multiple exchanges with the support of E-transaction, my problem would probably be due to a parameter of Prestashop 1.7.6 which must act on the "validateorder".
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-07-23 16:13
Hi @flyman30,

Have you tried to contact the module author?
Thanks to check with them & feedback.

**Comment by flyman30** [comment] 2019-07-23 16:22
297/5000
Yes of course, everything works except that Prestashop 1.7.6.0 does not able to receive validation data, so do not update the orders and do not send emails.
There are dozens (see more) of shop impacted by this bug, look at the forum fr PrestaShop it's edifying!

**Comment by flyman30** [comment] 2019-07-24 10:58
Voilà ce qu'envoi E-transaction à Prestashop 1.7.6.0

Voici les logs du retour IPN de votre transaction :

Jul 22 11:00:01 pbxprwb24 PayboxIPN.cgi[63522]: (INF) - Contact de l'URL en POST : https://*****.com/modules/etransactions/index.php?t=s&a=i - Donnees : M=1710&R
=1190%20-%20patrick%20Planul&T=524982735&A=446555&B=0&C=Visa&D=2106&E=00000&F=Y&G=O&I=FRA&J=--&N=------&O=Y&P=3DSECURE&Q=10%3A59%3A17&S=114349215&W=22072019&Y=FRA&Z=0-0&K=u
X9XAj%2F6sRLy6n1p3WEHKfLIUlsorlkcq6Lygs8f7y1WHaADP3T5DFf59H%2BeX0mRecz1RDRtMXiYN5jF2zykTE4o40hjgzbsbuz1w3LsaDwwnUUWh4jgtG4dkdIB7LA1zdhwpUAQLDz9bFYj5FpZXgY5JC0lU6n2%2BySOXYy
Nup4%3D
Jul 22 11:00:01 pbxprwb24 PayboxIPN.cgi[63522]: (INF) - Resolution DNS IPV4
Jul 22 11:00:01 pbxprwb24 PayboxIPN.cgi[63522]: (INF) - Utilisation de la version SSL par défaut
Jul 22 11:00:01 pbxprwb24 PayboxIPN.cgi[63522]: (INF) - Liste des ciphers SSL forces : RC4-MD5:RC4-SHA:DHE-RSA-AES256-SHA:DES-CBC3-SHA:AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-R
SA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:
ECDHE-RSA-AES128-GCM-SHA256:+ALL
Jul 22 11:00:01 pbxprwb24 PayboxIPN.cgi[63522]: (INF) - Utilisation de libcurl v7.53.1
Jul 22 11:00:11 pbxprwb24 PayboxIPN.cgi[63522]: (ERR) - Erreur de connexion - essai 1 :  (code http: 500 - code curl: 0)
Jul 22 11:00:21 pbxprwb24 PayboxIPN.cgi[63522]: (INF) - https://*****.com/modules/etransactions/index.php?t=s&a=i - Succes

**Comment by khouloudbelguith** [comment] 2019-07-27 08:16
Duplicate of #14648

**Closed as completed by khouloudbelguith** 2019-07-27 08:16 UTC
Labels: Duplicate, Order, Payment methods, 1.7.6.0

**Comment by beforcom** [comment] 2019-10-22 08:50
Bonjour,

J'ai également ce soucis avec un temps de retour à ma boutique très long après le paiement. Et dans les logs j'ai moi aussi des message du style :

Customer is back from E-Transactions payment page. Waiting order validation (loop 2).

Je suis aussi sur etransactions du Crédit Agricole.

En creusant un peu j'ai trouvé ceci :

​​​​​​​Lorsque j'active le mode débug sur mon Presta 1.7.4 et que je fais un paiement, au retour à ma boutique j'ai une belle erreur Notice PHP. qui m'indique que la variable cardType n'est pas définie.

Et là, dans le fichier EtransactionsController.php je vois ceci à la ligne concernée par l'erreur :
                if ('LIMOCB' == $cardType) {
                    sleep(6);
                }

A votre avis la boucle viens de là ? J'ai bien envie de mettre la valeur à 1 seconde mais bon... Je ne sais pas ce que cela implique au niveau de la validation du paiement..

Votre avis ?

**Comment by flyman30** [comment] 2019-10-22 09:25
Quel est la version du module e-transaction que tu utilise ?

Parcequ'avec PrestShop **1.7.4.*** il faut la version **3.0.12** il n'y a qu'a partir des versions Prestashop **1.7.6.*** qu'il faut le module version **3.013** d'e-transaction...
