### ISSUE TITLE
Upgrade 1.6 to 1.7 : PrestaShopDatabaseException ps_module_access

### ISSUE THREAD

**Issue by fsoabsix** [PrestaShop/PrestaShop#22524] opened 2020-12-21 16:06 UTC
#### Describe the bug

Hi, i tried to upgrade my website from PS 1.6.1.19 (I also tried form 1.6.1.24) to PS 1.7.6.4 (I tried the newest version, but I had PHP errors...)
I tried automatic and manual upgrade.
After a manual upgrade with no errors on the upgrade script, i can't do anything on the PS admin. I always have the error : 

> PrestaShopDatabaseException
> Unknown column 'ma.id_authorization_role' in 'on clause'

```
SELECT r.`slug`
FROM `psauthorization_role` r
INNER JOIN `ps_module_access` ma ON ma.`id_authorization_role` = r.`id_authorization_role`
WHERE ma.`id_profile` = "1"
```

I compare the ps_module_access between my 1.6 and 1.7 PS DB, the fields are the same.

**NOTE : I don't have the field "id_authorization_role" on the table "ps_module_access" in my DB.**

#### Expected behavior

A full functional upgrade.

#### Steps to Reproduce

Manual upgrade from 1.6.1.19 to 1.7.6.4

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2020-12-21 17:05
Hello @fsoabsix 

The issue of upgrading from PS1.6.1.24 to PS1.7.7.0, it will be fixed in the next patch PS1.7.7.1 (see issue #22237).
Also, I advise you to not upgrade your store manually as it will throw lots of errors.
So, please roll back to PS1.6.1.19 and when the next patch is released, upgrade your shop with the module **1-click upgrade** (this is the safest way to upgrade your store).

Ping @atomiix are you aware of this issue? 

Thanks!

**Comment by fsoabsix** [comment] 2020-12-22 08:08
Hi @hibatallahAouadni,
Thanks for your answer, I will wait the next patch and try the automatic upgrade 👍 
Thanks !

**Comment by hibatallahAouadni** [comment] 2021-01-07 09:48
Hello @fsoabsix 

Your issue is a duplicate to this one #22485 and it's already fixed with the new patch release PS1.7.7.1
I close this issue cause it's fixed :wink: and like I said before wait till the next patch release and then upgrade your shop.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-07 09:49
Duplicate of #22485

**Closed as completed by hibatallahAouadni** 2021-01-07 09:48 UTC
Labels: Bug, Duplicate, Autoupgrade
