### ISSUE TITLE
Product Comments module: error 500 after update

### ISSUE THREAD

**Issue by Prosveta83600** [PrestaShop/PrestaShop#35886] opened 2024-04-10 11:15 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning. A short time ago I updated the Prestashop modules and I got an error 500 after updating Product Comments. Via the Prestashop chat, a technician advised me to rename the productcomments folder, which I did and everything was back to normal. However this module is now disabled and I can no longer update it.
Prestashop version: 1.7.7.8
PHP version: 7.3.31-1~deb10u5
Thank you in advance for your support

### Steps to reproduce

Good morning. A short time ago I updated the Prestashop modules and I got an error 500 after updating Product Comments. Via the Prestashop chat, a technician advised me to rename the productcomments folder, which I did and everything was back to normal. However this module is now disabled and I can no longer update it.
Prestashop version: 1.7.7.8
PHP version: 7.3.31-1~deb10u5
Thank you in advance for your support

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.31-1~deb10u5

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by ChillCode** [comment] 2024-04-10 19:26
Hi

6.0.3 use services and ps_feature_flag table only available from PS 1.7.8.0 > not compatible with 1.7.7.*.

**Comment by paulnoelcholot** [comment] 2024-04-11 09:32
Hello @Prosveta83600,

I reproduce the issue with PrestaShop version 1.7.7.8, I'll add this to the backlog so it can be fixed. In the meantime you can correct the problem by upgrading your shop.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by leemyongpakva** [comment] 2024-04-11 14:27
@Prosveta83600 You can try **Back-Office > CONFIGURE > Advanced Parameters > Performance > Clear Cache**, then rename module folder name back to productcomments.

**Comment by BENHAM40** [comment] 2024-04-12 12:12
Hello
I have a similar issue, and i follow the same instructions but it’s doesn’t work for me.

our website: lenda.ma

**Comment by leemyongpakva** [comment] 2024-04-12 14:44
`prestashop.core.admin.lang.repository` is a non-existent service in PS 1.7.7.x . So you need to download https://github.com/PrestaShop/productcomments/releases/tag/v6.0.2/productcommens.zip, unzip then upload `productcomments` folder to your `modules` folder **manually**.

**Comment by ChillCode** [comment] 2024-04-12 18:06
> `prestashop.core.admin.lang.repository` is a non-existent service in PS 1.7.7.x . So you need to download https://github.com/PrestaShop/productcomments/releases/tag/v6.0.2/productcommens.zip, unzip then upload `productcomments` folder to your `modules` folder **manually**.

Since you are the committer I just found that  prestashop.core.admin.* are not present in the $container, but as @kpodemski points `prestashop.core.admin.lang.repository` service  do exists.

https://github.com/PrestaShop/PrestaShop/issues/35854#issuecomment-2052212726

**Comment by leemyongpakva** [comment] 2024-04-13 01:40
@ChillCode In theory `prestashop.core.admin.lang.repository service` do exists in PS 1.7.7.x as **kpodemski** point out. But in practice, it is  non-existent in PS 1.7.7.8.
For safety, I think we need to bump minimum PS version for productcomments 6.0.3 to PS 1.7.8, and even bump module version to major version 7.0.0

**Comment by ChillCode** [comment] 2024-04-16 14:20
Version control is not easy, but this issue I think is just trivial/minor, people must update to version 8 since 1.7 is not supported anymore, but I understand PS cannot break current installations.

@leemyongpakva Thanks for the great effort!

**Comment by leemyongpakva** [comment] 2024-09-13 10:22
Solved by PrestaShop/productcomments/pull/205

**Closed as completed by leemyongpakva** 2024-09-13 10:22 UTC
Labels: Bug, Minor, BO, Modules, Productcomments, 1.7.7.8, Verified, Module
