### ISSUE TITLE
1.7.5.0 -> 1.7.5.1 One Click Upgrade Error

### ISSUE THREAD

**Issue by vincentchu37** [PrestaShop/PrestaShop#12635] opened 2019-02-20 11:06 UTC
One Click Upgrade errors out at upgrading database. 

**Information from One click upgrade backoffice:**
[Ajax / Server Error for action upgradeDb] textStatus: "error " errorThrown:"Internal Server Error " jqXHR: " {"nextQuickInfo":["Migrating old setting file...","parameters file already exists!","Finished...","

[OK] PHP 1.7.5.1 : \/* PHP:ps_1751_update_module_sf_tab(); *\/<\/div>","[INTERNAL] \/home\/shop\/webapps\/SwatShop\/src\/PrestaShopBundle\/Service\/Command\/AbstractCommand.php line 51 - set_time_limit() has been disabled for security reasons","Database upgrade OK","[SKIP] directory "\/app\/cache\/" does not exist and cannot be emptied.","[SKIP] directory "\/themes\/classic\/cache\/" does not exist and cannot be emptied."],"nextErrors":["[INTERNAL] \/home\/shop\/webapps\/SwatShop\/classes\/Validate.php line 26 - Cannot declare class ValidateCore, because the name is already in use"],"error":true,"next":"error"}{"nextQuickInfo":["Migrating old setting file...","parameters file already exists!","Finished...","

[OK] PHP 1.7.5.1 : \/* PHP:ps_1751_update_module_sf_tab(); *\/<\/div>","[INTERNAL] \/home\/shop\/webapps\/SwatShop\/src\/PrestaShopBundle\/Service\/Command\/AbstractCommand.php line 51 - set_time_limit() has been disabled for security reasons","Database upgrade OK","[SKIP] directory "\/app\/cache\/" does not exist and cannot be emptied.","[SKIP] directory "\/themes\/classic\/cache\/" does not exist and cannot be emptied."],"nextErrors":["[INTERNAL] \/home\/shop\/webapps\/SwatShop\/classes\/Validate.php line 26 - Cannot declare class ValidateCore, because the name is already in use","[INTERNAL] \/home\/shop\/webapps\/SwatShop\/classes\/Validate.php line 26 - Symfony\\Component\\Debug\\Exception\\FatalErrorException: Error: Cannot declare class ValidateCore, because the name is already in use\n#0 {main}"],"error":true,"next":"error"}"

------------------

**Php Error Log:** 
[Wed Feb 20 04:40:15.519654 2019] [proxy_fcgi:error] [pid 1796:tid 139909046114048] [client 162.158.186.216:0] AH01071: Got error 'PHP message: PHP Fatal error:  require_once(): Failed opening required '/home/shop/webapps/SwatShop/config/defines.inc.php' (include_path='/home/shop/webapps/SwatShop/vendor/pear/pear_exception:/home/shop/webapps/SwatShop/vendor/pear/console_getopt:/home/shop/webapps/SwatShop/vendor/pear/pear-core-minimal/src:/home/shop/webapps/SwatShop/vendor/pear/archive_tar:.:') in /home/shop/webapps/SwatShop/modules/autoupgrade/classes/UpgradeContainer.php on line 469\n',

[Wed Feb 20 04:52:29.790251 2019] [proxy_fcgi:error] [pid 1796:tid 139909319464704] [client 162.158.186.216:0] AH01071: Got error 'PHP message: PHP Fatal error:  Cannot declare class ValidateCore, because the name is already in use in /home/shop/webapps/SwatShop/classes/Validate.php on line 26\n',

**One click upgrade options:** 
![ocu options](https://i.quickbrownfoxes.org/FirstSleepyBrant812.png)
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-02-20 11:24
Hi @vincent8balls,

In my case, I did not manage to reproduce the issue with 1-click upgrade v4.6.0 from PS1.7.5.0 to PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1Ej3bJdkBgCnGotk0_CxH1x5kGfUBeBpV/view
About this error: "AH01071: Got error 'PHP message: PHP Fatal error: require_once(): Failed opening required '/home/shop/webapps/SwatShop/config/defines.inc.php'", it could be a permission issue, thanks to check the permission on your host.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by vincentchu37** [comment] 2019-02-20 11:32
Thanks for the reply. I will give that a shot. What permissions should give for the file? 755?

**Comment by khouloudbelguith** [comment] 2019-02-20 11:39
@vincentchu37, could you please try with 775.
I tried with another shop PS1.7.5.0 installed in a server with 7.2.10 & it is OK(successfully upgraded)
Thanks!

**Comment by vincentchu37** [comment] 2019-02-21 20:58
Yep. Seems to have fixed it by changing the defines.inc.php file's permissions!

**Comment by khouloudbelguith** [comment] 2019-02-22 07:32
Hi @vincentchu37,

Thanks for your feedback. 
Since it is fixed, I will close the issue, feel free to open a new one needed. 
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-22 07:32 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.5.1
