### ISSUE TITLE
PS 1.7.2 Unable to delete adress or confirm order

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#11684] opened 2018-12-10 07:38 UTC
[PrestaShopException]
Invalid address #638
at line 439 in file classes/Address.php

434.             // if an id_address has been specified retrieve the address
435.             if ($id_address) {
436.                 $address = new Address((int)$id_address);
437. 
438.                 if (!Validate::isLoadedObject($address)) {
439.                     throw new PrestaShopException('Invalid address #'.(int)$id_address);
440.                 }
441.             } elseif ($with_geoloc && isset($context->customer->geoloc_id_country)) {
442.                 $address             = new Address();
443.                 $address->id_country = (int)$context->customer->geoloc_id_country;
444.                 $address->id_state   = (int)$context->customer->id_state;
AddressCore::initialize - [line 197 - classes/tax/Tax.php] - [1 Arguments]
TaxCore::getProductEcotaxRate - [line 722 - classes/Cart.php] - [1 Arguments]
CartCore->getProducts - [line 3867 - classes/Cart.php]
CartCore->isVirtualCart - [line 1797 - classes/Cart.php]
CartCore->getOrderTotal - [line 3644 - classes/Cart.php] - [1 Arguments]
CartCore->getSummaryDetails - [line 746 - controllers/admin/AdminCustomersController.php]
AdminCustomersControllerCore->renderView - [line 2090 - classes/controller/AdminController.php]
AdminControllerCore->initContent - [line 209 - controllers/admin/AdminCustomersController.php]
AdminCustomersControllerCore->initContent - [line 205 - classes/controller/Controller.php]
ControllerCore->run - [line 387 - override/classes/Dispatcher.php]
Dispatcher->dispatch - [line 97 - admin/index.php]

**Comment by khouloudbelguith** [comment] 2018-12-10 08:19
Hi @matteolavaggi,

This issue happens if you have an abandoned cart and if you delete the customer's address.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11416 to fix the issue.
Your ticket is a duplicate of #9782
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-10 08:20
Duplicate of #9782

**Closed as completed by khouloudbelguith** 2018-12-10 08:19 UTC
Labels: Duplicate
