### ISSUE TITLE
BO - Unable to update settings for products with combinations

### ISSUE THREAD

**Issue by templatin** [PrestaShop/PrestaShop#30179] opened 2022-11-01 12:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![error-1](https://user-images.githubusercontent.com/3615808/199229636-735fa8e0-ef78-4974-a4c9-6adfc30b7c13.jpg)

Tested in fresh installation of PS 8.0.0.

When Stock management is disabled, the products having combinations is showing error while saving any of its data. I tested it with default (demo) products as well as new products.
Simple products are working fine.

### Steps to reproduce

1. Go to BO > Shop Parameters > Product Settings. Disable the Stock management option.
2. Go to BO > Catalog > Products. Edit any product which has combinations.
3. Click on "Combinations" tab, edit price impact field or any data in the combination and click "Save".
4. Error showing "Unable to update settings" as in above screenshot.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3.21

**Comment by sallemiines** [comment] 2022-11-01 14:40
Hello @templatin 

Thanks for reporting the issue .
I tried to reproduce your issue with Ps1787 & PS800

Following your steps , i didn't reproduce the issue,  see the attached screen-record



https://user-images.githubusercontent.com/31663369/199252709-5229dc9e-9002-489f-b29e-7788d38f0e8b.mp4 

Could you please provides us a screen record shows all the steps

Thank you !

**Comment by templatin** [comment] 2022-11-02 04:14
Please read step-1 in "Steps to reproduce". The error is shown only when Stock management is disabled. In your screen record, it seems that option is still enabled.

**Comment by sallemiines** [comment] 2022-11-02 07:35
Hello, 

Thanks for your feedback :pray: 

I can reproduce the issue, see the attached screenshot 

![Capture d’écran de 2022-11-02 08-30-00](https://user-images.githubusercontent.com/31663369/199426816-0948f060-2bc8-4132-86f3-57701ddacb47.png)

Thank you !

**Comment by rizzok** [comment] 2023-01-29 19:19
This issue is still present on version 8.0.1.
We also can't edit and save the price in "Basic settings" tab.

**Comment by Pharweb** [comment] 2023-01-31 18:42
same thing for me.
This happens as soon as a combination is added or modified.

**Comment by babawy** [comment] 2023-02-21 17:27
Same problem with 8.0.1, when stock management is disabled. This is a important issue that force me to enable stock management on every shops.

**Comment by StarDev-it** [comment] 2023-03-30 21:28
The issue is still present in v8.0.2 (I've lost 4 hours of my life to figure out this behavior). I suggest to increase the issue priority in order to fix it in the next release

**Comment by matks** [comment] 2023-04-03 08:15
This issue just got fixed by https://github.com/PrestaShop/PrestaShop/pull/31390 which will be shipped in PrestaShop 8.0.4

**Closed as completed by matks** 2023-04-03 08:15 UTC
Labels: Bug, Minor, BO, Needs Specs, Topwatchers, Combinations, PR available, Verified, 1.7.8.7
