### ISSUE TITLE
Problem with sending mails PS. 1.7.8.7

### ISSUE THREAD

**Issue by misieq12** [PrestaShop/PrestaShop#30247] opened 2022-11-08 17:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I have a problem with my PS mail. 1.7.8.7, namely I have mail after SMTP configured, but I get the error:

Error: please check configuration

Expected response code 250 but got code "550", with message "550 Bad HELO - Host impersonating domain name [DOMAIN.COM]".

 
However, when I switch the settings to / usr / sbin I get an error:

Error: please check configuration

Expected response code 220 but got an empty response

What may be the problem?

Regards.

### Steps to reproduce

1. go to Advanced
2. check email
3. test it

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2022-11-09 08:39
Hello @misieq12 

Thanks for your report.

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/28014
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank You!

**Closed as completed by HanaRebaiQA** 2022-11-09 08:39 UTC
Labels: Bug, Duplicate, Invalid

**Comment by HanaRebaiQA** [comment] 2022-11-09 08:41
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28014

**Comment by HartLarsson** [comment] 2023-01-06 20:45
> ### Prerequisites
> * [x]  I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
> * [x]  I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.
> 
> ### Describe the bug and add screenshots
> Hello,
> 
> I have a problem with my PS mail. 1.7.8.7, namely I have mail after SMTP configured, but I get the error:
> 
> Error: please check configuration
> 
> Expected response code 250 but got code "550", with message "550 Bad HELO - Host impersonating domain name [DOMAIN.COM]".
> 
> However, when I switch the settings to / usr / sbin I get an error:
> 
> Error: please check configuration
> 
> Expected response code 220 but got an empty response
> 
> What may be the problem?
> 
> Regards.
> 
> ### Expected behavior
> _No response_
> 
> ### Steps to reproduce
> 1. go to Advanced
> 2. check email
> 3. test it
> 
> ### PrestaShop version(s) where the bug happened
> 1.7.8.7
> 
> ### PHP version(s) where the bug happened
> 7.4
> 
> ### If your bug is related to a module, specify its name and its version
> _No response_

what smtp server you still using on your configuration?
