### ISSUE TITLE
Manual prestashop update -> Unzipping error - Unable to find the release zip file

### ISSUE THREAD

**Issue by mati771** [PrestaShop/PrestaShop#35211] opened 2024-01-29 23:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An error has occured:
Unzipping error - Unable to find the release zip file. Make sure that the prestashop.zip file has been uploaded and is located in the same directory as this dezipper.

### Expected behavior

i update with the Prestashop instructions.
https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/
![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/121d1e97-4eb4-4351-a1f5-1797b5140355)

![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/3c5acf12-357b-4751-bc9c-705f9a384f63)

### Steps to reproduce

I created a prestashop folder for installation
![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/3d535751-b318-4096-a726-58f8bb899bd7)

### PrestaShop version(s) where the bug happened

1.7.x

**Comment by AureRita** [comment] 2024-01-30 14:24
Hi @mati771  ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Because this one seems to be more like a support ticket, I'll close this issue. 
If you encounter some bugs about the prestashop project after this operation, we'll be happy to identify your issue and correct it later.

Thank you

**Closed as completed by AureRita** 2024-01-30 14:24 UTC
Labels: Bug, Invalid
