### ISSUE TITLE
Multistore- Product feature reappearing with a value from one shop into another in BO

### ISSUE THREAD

**Issue by DianaEFB** [PrestaShop/PrestaShop#17780] opened 2020-02-21 18:07 UTC
In BO, when I edit one product, a feature appears with a value corresponding to the second shop. I delete it but it reappears. 

In multistore after upgrade from 1.6.1.24 to 1.7.6.2 with a MigrationPro module.
1. Go to "Catalog>Product"
2. Click on a product
3. Scroll down to 'Features'

Image shows the product is saved with 4 features:
![image](https://user-images.githubusercontent.com/61324467/75059232-cf8ec500-54dc-11ea-817b-b60fad9dc224.png)
I reopen the same product and it shows 5 features, the last one with a value that belongs to the second shop and no feature selected. This happens over and over again.
![image](https://user-images.githubusercontent.com/61324467/75059470-4a57e000-54dd-11ea-9a1b-b24a94b45fb5.png)

PrestaShop version: 1.7.6.2
PHP version: 7.2.27

**Comment by khouloudbelguith** [comment] 2020-02-24 10:31
Hi @DianaEFB,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15383
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-24 10:31
Duplicate of #15383

**Closed as completed by khouloudbelguith** 2020-02-24 10:31 UTC
Labels: Duplicate
