### ISSUE TITLE
Not possible to choose one combination

### ISSUE THREAD

**Issue by mathieuhen** [PrestaShop/PrestaShop#10400] opened 2018-09-12 12:18 UTC
Hello, 

when you have a product with combinations.

For example 3 combinations of a shirt : 
 - size : S, color : white
 - size : M, color : black
 - size : XL, color : black

In front, on the product page, it's not possible to choose the second or the third declinaison.  

When you arrive on the page, it's the default combination selected (S and White). 
If you try to change the size, nothing happens. And if you try to change the color, there is only the white. 

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by mortenhartvig** [comment] 2018-09-12 12:54
I think the developers would like to know what theme you are using.

In the core/classic theme, the server responds with some new DOM elements, that replaces the whole "select combination" part of the site when you click a variant. It sounds like that part is broken for your site. 

While we can argue how smart/over complicated that approach is, I'm pretty sure that it just works in the classic theme (at least it does for me in 1.7.2.2). Are you using a custom theme, and if so, could you test the behaviour in the classic theme?

Also, (if using chrome), you could see potential reasons for the error in the network tab/console log). (Ctrl+shift+i) before you click the combination. In the network tab, you can see what happends in terms of response from the server.

**Comment by khouloudbelguith** [comment] 2018-09-12 13:32
Hi @mathieuhen,

Have you the same issue with this ticket: #9667?

Best regards, Khouloud

**Comment by benwallis** [comment] 2018-09-12 14:06
I have similar issues in default "Classic" theme in fresh installation of 1.7.4.2.

E.g. edit "Hummingbird Printed T-Shirt", delete combination for Size XL with Color Black. Now go to that product page on the front end. If you select Color Black, and then change size to XL, then you get a 500 error displaying "An error occurred while processing your request" and the black swatch is NOT removed. 
With Debug mode enabled I can see the error is:

[PrestaShopObjectNotFoundException]
Can not retrieve the id_product_attribute at line 6164 in file classes/Product.php

**Comment by khouloudbelguith** [comment] 2018-09-12 14:14
Hi @benwallis,

Your issue is different, it is fixed & it is added to the next release 1.7.5.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9390 to solve your issue.

Best regards, Khouloud

**Comment by mathieuhen** [comment] 2018-09-12 14:26
Yes, it's the same issue that PR : #9390  

I try to change the getIdProductAttribute function like them. And it works on a fresh installation of 1.7.4.2. 
But it doesn't work if 
- you enable multishop feature
- add a new shop
- in all shops context : 6 combinations
- in tested shop : only 3 combinations of the 6

**Comment by khouloudbelguith** [comment] 2018-09-12 14:54
Hi @mathieuhen,

After applying the patch: #9390, I di not manage to reproduce your issue by following your steps.
It will help us if you can attach a screen record.

Thanks & Best regards, Khouloud

**Comment by vladootz** [comment] 2018-10-10 15:18
@mathieuhen, not sure if this helps, but do you use Pretty URLS or another module or is there an override on the ProductController.php?
I had the exact same issue and I installed a fresh Prestashop, activated the module again, grabbed the ProductController.php from the fresh install and added it to the live site, and now combinations work.

**Comment by mathieuhen** [comment] 2018-10-11 07:29
Hi, 

I don't use any module or override because I had issue on clean install of Prestashop.

**Comment by khouloudbelguith** [comment] 2018-10-11 08:34
Hi @mathieuhen, The Shema of URLs seems like that by default:
![image](https://user-images.githubusercontent.com/16067358/46791304-214c0a80-cd41-11e8-85d0-022227f95c24.png)
You can check it on the BO => Shop Parameters => Traffic & SEO.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-13 11:36
Hi @mathieuhen,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-13 11:36 UTC
Labels: FO, Combinations, No change required, 1.7.4.2

**Comment by Jonatan949** [comment] 2021-06-17 09:07
@khouloudbelguith I have a problem related with this. When the customer adds a product with combinations to the cart, the combination of products that the customer chooses is not chosen, the Samsung S21 Plus always appears. This problem only occurs in the mobile version, in the computer version it works fine.

What can I do?

**Comment by khouloudbelguith** [comment] 2021-06-17 09:56
Hi @Jonatan949,

This issue is currently closed, can you open a new one with more information about your configuration.

Thank you!

**Comment by Jonatan949** [comment] 2021-06-17 10:08
Ok, this is the url of the new issue: https://github.com/PrestaShop/PrestaShop/issues/24998

**Comment by Jonatan949** [comment] 2021-06-17 10:08
@khouloudbelguith i need your help please 🙏🙏

**Comment by matks** [comment] 2021-06-17 12:26
@Jonatan949 If you need help with your shop, please have a look at  https://devdocs.prestashop.com/1.7/faq/i-need-help/
