### ISSUE TITLE
Cart with order is empty

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#24816] opened 2021-06-04 15:03 UTC
#### Describe the bug

Cart with a placed order is empty. Product is in the order but not in the cart anymore. So if I try to add a discount on the order page, I get the error message "Could not find the product in cart, meaning Order and Cart are out of sync".

Why would the cart get empty?

**Screenshots**

![Screen-Shot-2021-06-04-at-15 59 57](https://user-images.githubusercontent.com/71735/120822360-3c9d6100-c54e-11eb-94f6-d24a2604be6a.jpg)
![Screen-Shot-2021-06-04-at-16 00 22](https://user-images.githubusercontent.com/71735/120822382-42934200-c54e-11eb-8f05-91ee6567270b.jpg)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-06-05 00:32
Hello @ced--ced 

Could you please check the third issue in #22948 it seems related to yours.
Please check and feedback.

Thanks!

**Comment by ced--ced** [comment] 2021-06-05 11:48
Hi @hibatallahAouadni,

It's not the same. The person was creating first a discount code in the cart rules and then creating an order from the BO.

In my case the order has already been placed by the customer. It's the customer who also creates the cart.

So first we have the problem that the cart is empty in the bo. And secondly, we have the error message when we go in the order and create straight from there a new discount.

Thanks

**Comment by hibatallahAouadni** [comment] 2021-06-09 23:09
Hello @ced--ced 

> It's not the same. The person was creating first a discount code in the cart rules and then creating an order from the BO.

Ok, so could you please provide clear and concise steps to reproduce the issue :pray: 
Related to #9589 & #23620

Thanks!

**Comment by florine2623** [comment] 2021-06-29 08:43
Hello @ced--ced ,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-06-29 08:43 UTC
Labels: Bug, BO, Order, Shopping carts, Discounts, No change required, 1.7.7.3
