### ISSUE TITLE
Back office - got error 500 when click on "Add new customer"

### ISSUE THREAD

**Issue by yutailin1993** [PrestaShop/PrestaShop#18557] opened 2020-04-10 03:17 UTC
Hi,
I have got 500 internal server error when click on "Add new customer" in Orders -> Add new order, the description are mentioned as followed.

Thanks~

### Steps to Reproduce

1. In back office
2. Click on side bar -> Orders -> Orders 
3. Click on "Add new order"
4. Click on "Add new customer"
5. got 500 internal server error

### Describe the bug

Got 500 internal server error when click on "Add new customer" in Orders -> Add new order
 
The error log in var/logs/prod.log are shown as below:
```
[2020-04-10 10:49:44] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Link could not be converted to string")." at /volume1/web/prestashop1.7/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig line 34 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class Link could not be converted to string\"). at /volume1/web/prestashop1.7/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig:34, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class Link could not be converted to string at /volume1/web/prestashop1.7/var/cache/prod/smarty/compile/83/ed/09/83ed092a63eecb4f0b4e86ab60e4360f61cd19f5_0.file.content.tpl.php:67)"} []
```

It seems that the error occurred in the code which was generated by php plugin "smarty". The line in `83ed092a63eecb4f0b4e86ab60e4360f61cd19f5_0.file.content.tpl.php:67` is:
```php
"<?php echo $_smarty_tpl->tpl_vars['link']->value;?>
```
I've used gettype() to see `$_smarty_tpl->tpl_vars['link']->value` and it returned "Object". I think that's the reason causing the error.

Besides, I found that the error was gone when I turn on the debug mode and revisit the page. I've also try to get the type of `$_smarty_tpl->tpl_vars['link']->value` and it returned "String".

I've tried to clean cache by remove var/cache manually but still got same error.

Any clue?

### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: PHP 7.2.24

**Comment by florine2623** [comment] 2020-04-10 07:47
Hi @yutailin1993 ,
I can't reproduce your error
- Could you deactivate the overrides : comment directly the overrides folder via FTP and refresh.
- Could you deactivate your modules and see if it comes from there.
Please check and let me know !

**Comment by sarahdib** [comment] 2020-05-05 16:02
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 16:02 UTC
Labels: BO, Order, No change required, 1.7.6.4

**Comment by iverestchagin** [comment] 2020-10-01 11:40
The problem is that "welcome" module uses `$link` template variable as a string rather than a `Link` instance (that it is in fact) in `modules/welcome/views/content.tpl:49`. Error only appears while product creation wizard is not finished.
