### ISSUE TITLE
PS prices after Upgrade v1.7.2.5 to 1.7.6 not correct

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15249] opened 2019-08-23 17:46 UTC
**Describe the bug**
Hello developer,

I have a shop price problem after upgrading from PS 1.7.5.2 to 1.7.6. All prices in the shop show 6 digits after the comma.

Here in the ticket also a screenshot. 

As currency, I use EURO and it a German Onlineshop.

Now I have discovered this Github command, but in PHPmyAdmin I cannot work with it. It is not accepted. I have SharedHosting with MariaDB and PHP 7.2.

`UPDATE ps_currency SET numeric_iso_code = '978', precision = '2' WHERE ps_currency.id_currency = 2;`

What must the MySQL command be exactly, in my shop settings?

Thanks in advance.

**To Reproduce**

**Screenshots**

![github-issue-shopprices-not-correct](https://user-images.githubusercontent.com/7885632/63612408-7e118600-c5de-11e9-8787-5034703500ee.jpg)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-08-26 08:04
Hi @AlexL777,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14664 to fix the issue
Your ticket is a duplicate of #14640
So, I close it.
For a quick fix, you can run this SQL command on your Database
UPDATE `ps_currency` SET `numeric_iso_code` = '978', `precision` = '2' WHERE `ps_currency`.`id_currency` = 2; 
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-26 08:04
Duplicate of #14640

**Closed as completed by khouloudbelguith** 2019-08-26 08:04 UTC
Labels: Duplicate
