### ISSUE TITLE
Prestashop Technical Error: Details: Error Thrown: [Object Object] Text Status: Parsererror

### ISSUE THREAD

**Issue by yimilan** [PrestaShop/PrestaShop#18094] opened 2020-03-11 14:45 UTC
This is the bug, to save carrier data:

Prestashop Technical Error: Details: Error Thrown: [Object Object] Text Status: Parsererror

When saving or attempting to save carriers, the system is bugged and the error mentioned above appears, although SSL is already active throughout the site and does not allow enabling SSL, this happens on one of the servers that was tested, on the other simply was forced to reproduce the error

I never save the carriers, now if I delete it and recreate it, it saves but when I start to put a lot of data it gets bugged.

I attached a video explaining how to reproduce the error and what I have been able to prove.

https://www.youtube.com/watch?v=tH1EiV4aIH0

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-11 14:49
Hi @yimilan,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by yimilan** [comment] 2020-03-11 14:55
> Hi @yimilan,
> 
> Please, send your request in English.
> English is the norm on the GitHub
> Thank you!

very well, it's edited

**Comment by khouloudbelguith** [comment] 2020-03-11 16:00
@yimilan,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12946 to fix the issue.
It is fixed in the PS1.7.6.0.
Your ticket is a duplicate of #12577
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-11 16:00
Duplicate of #12577

**Closed as completed by khouloudbelguith** 2020-03-11 16:00 UTC
Labels: Duplicate

**Comment by yimilan** [comment] 2020-03-11 16:52
@khouloudbelguith  I aplicated this change https://github.com/PrestaShop/PrestaShop/pull/12946/files/6d1877ba5edae40afbecfe069886ef7c8f7e9bda
But  i no solucionate the problem.
The problem persists on servers with multiple SSL redirects.

Even applying this change #12946 on a server without multiple SSL redirects, the problem remains when forcing HTTPS by redirect
