### ISSUE TITLE
BO Import page crashes with "The controller must return a response" error when import directory does not exist

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#20163] opened 2020-07-13 12:56 UTC
I get this error message when trying to access "Import" tab in PrestaShop backoffice.

1. Log into the backoffice
2. Click on "Advanced parameters" then "Import"

Capture ➡️ https://www.dropbox.com/s/j07mx309gposw7u/Capture%20d%27%C3%A9cran%202020-07-13%2014.55.35.png

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by matks** [comment] 2020-07-13 14:31
@Daaaaad I cannot reproduce your issue 🤔  . You can try yourself on http://demo.prestashop.com/#/en/back

I think something is wrong with your shop. Did someone customize it ? Did you perform an upgrade recently ?

Look here
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.7/src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php#L106
This is the part where the Controller return a response. Response is created by `$this->render()` which is a very standard Symfony function used everywhere. I dont see how it could fail 😅  if your code is the same as here.

**Comment by Daaaaad** [comment] 2020-07-13 20:04
Hi @matks,

That was because to the lack of and "import" folder in the "adminXXX" directory...

Regards,

David.

**Comment by matks** [comment] 2020-07-13 21:00
@Daaaaad So we have 1 good news and 1 bad news:
- good news: you found the issue \o/
- bad news: the error message was very bad and could not help us to find the issue

So the error message must be improved, which I do immediately 😊 

PR is on its way to fix that => https://github.com/PrestaShop/PrestaShop/pull/20166

**Comment by matks** [comment] 2020-07-15 12:10
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20166

**Closed as completed by matks** 2020-07-15 12:10 UTC
Labels: Trivial, BO, Import / Export, Fixed, PR available
