### ISSUE TITLE
Retrieve password with email with uppercase

### ISSUE THREAD

**Issue by fixo94** [PrestaShop/PrestaShop#23070] opened 2021-02-01 12:12 UTC
#### Describe the bug

Can't recover password when email contain an uppercase

#### Steps to Reproduce

Register a client with an uppercase in the email (such as toto@Gmail.com)

And try to recover the password.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/8167966/106457150-d49b1900-648e-11eb-849d-3c904970aff9.png)

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-02-01 12:40
Hello @fixo94 

We are aware of this issue, it is already fixed with PS1.7.7.0. This issue is a duplicate of #13386. 
Here's the PR: #16550 to fix the issue.

PS: please downgrade your PHP version to 7.2 cause PS1.7.6.9 is not compatible with PHP 7.2 (se our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements))

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-01 12:40 UTC
Labels: Duplicate

**Comment by hibatallahAouadni** [comment] 2021-02-01 12:41
Duplicate of #13386
