### ISSUE TITLE
psadmin admin panel not available?!

### ISSUE THREAD

**Issue by zoomietoon** [PrestaShop/PrestaShop#16559] opened 2019-11-27 09:29 UTC
Hi everyone, 

I haven't been able to access my admin panel for the last week. The front end of my site www.zoomietoon.com works fine for me, but when I try to see orders at the zoomietoon.com/psadmin address I get the following message:

This page isn’t working
zoomietoon.com is currently unable to handle this request.
HTTP ERROR 500

I've tried emailing and calling prestashop directly but am not receiving replies. Help?

**Comment by khouloudbelguith** [comment] 2019-11-27 09:33
Hi @zoomietoon,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by zoomietoon** [comment] 2019-11-27 09:48
I'm using Bluehost as my domain host 
I think I have prestashop 1.6 but I can't access the admin page to be certain. 
I would really like to send you the logs and reports you asked for, but I don't know where to find them and the link you sent doesn't specify where they are located. 

Here is a screenshot of what I am seeing when I want to get to my admin login page. The issue should be easily reproduced by going to zoomietoon.com/psadmin - I've tried on various computers (pc, mac, android phone) and always get the same results. For some reason the front end of the shop is fine. I'm not sure how this can be fixed since I can't access any of the settings available in the admin panels. 

![Capture](https://user-images.githubusercontent.com/58252837/69712491-33366b80-1103-11ea-9a8e-e322cd47b08a.PNG)

**Comment by khouloudbelguith** [comment] 2019-11-27 09:56
@zoomietoon, The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rdy4ever** [comment] 2019-11-27 14:34
Hi @zoomietoon 
Your shop version is 1.7x, not 1.6. Please go to your shop root directory and edit `/config/defines.inc.php`. Edit this part:
```
/* Debug only */
if (!defined('_PS_MODE_DEV_')) {
    define('_PS_MODE_DEV_', false);
}
```
change `false` to `true`. Save file, then, go again to your admin and see what error message you get.
If you don't get any detailed error, please rename `.htaccess` to `.htaccess-old` and see if you can access your admin after that.

**Comment by zoomietoon** [comment] 2019-11-27 19:40
Thanks for your reply @rdy4ever 
How do I access my shop root directory? I'm a little lost at this point.

**Comment by rdy4ever** [comment] 2019-11-28 07:48
Hi @zoomietoon 
You can access it via ftp or in CPpanel, File manager

**Comment by zoomietoon** [comment] 2019-11-28 09:50
@rdy4ever Found it. I get the following error message, any ideas? 

![Capture2](https://user-images.githubusercontent.com/58252837/69795654-dc956400-11cc-11ea-9cb4-d7362b2a4866.PNG)

**Comment by khouloudbelguith** [comment] 2019-11-28 10:03
Hi @zoomietoon,

I think you are using PHP7.3, is it?
PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3
You need to downgrade your PHP version.

Thanks!

**Comment by rdy4ever** [comment] 2019-11-28 10:05
Yeap, I think you need to downgrade to PHP 7.2. Check with your host, they might have updated it to 7.3 and that's why your shop stopped working.

**Comment by zoomietoon** [comment] 2019-11-28 10:18
Thank you! PHP 7.2 didn't work, but 7.1 is working! Thanks!!

**Comment by khouloudbelguith** [comment] 2019-11-28 10:19
@zoomietoon, great!

Since it is ok, I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-28 10:19 UTC
Labels: Bug, BO, No change required
