### ISSUE TITLE
Carriers don't support duplicate name

### ISSUE THREAD

**Issue by sylwit** [PrestaShop/PrestaShop#17454] opened 2020-01-31 06:19 UTC
**Describe the bug**
If 2 carriers have the same name, only one is displayed in payment preferences so you can't enable the first ones 

**To Reproduce**
1. Go to shipping > carriers
2. Create 2 carriers with the name "Pick Up"
3. Go to payment > preferences > Carrier restrictions
4. You see only 1 carrier

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

The error is in the private function getCarrierChoicesForPaymentModules() located in src/PrestaShopBundle/Form/Admin/Improve/Payment/Preferences/PaymentModulePreferencesType.php
it returns an array
```

Array
(
    [0] => Array
        (
            [name] => ps_wirepayment
            [label] => Bank transfer
            [multiple] => 1
            [choices] => Array
                (
                    [UPS Standard US] => 27
                    [UPS Standard CA] => 28
                    [LTL Freight Delivery] => 5
                    [Pick-Up in Store FL] => 14
                    [Pick-Up in Store] => 15
                )

        )

    [1] => Array
        (
            [name] => paypal
            [label] => PayPal
            [multiple] => 1
            [choices] => Array
                (
                    [UPS Standard US] => 27
                    [UPS Standard CA] => 28
                    [LTL Freight Delivery] => 5
                    [Pick-Up in Store FL] => 14
                    [Pick-Up in Store] => 15
                )

        )

    [2] => Array
        (
            [name] => ps_checkpayment
            [label] => Payments by check
            [multiple] => 1
            [choices] => Array
                (
                    [UPS Standard US] => 27
                    [UPS Standard CA] => 28
                    [LTL Freight Delivery] => 5
                    [Pick-Up in Store FL] => 14
                    [Pick-Up in Store] => 15
                )

        )

)
```

We can see that choices are indexed by name instead of ID

**Comment by khouloudbelguith** [comment] 2020-01-31 07:46
Hi @sylwit,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/12379 to fix the issue.
It is fixed in the next major release PS1.7.7.0.
Your ticket is a duplicate of #16094
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-31 07:46
Duplicate of #16094

**Closed as completed by khouloudbelguith** 2020-01-31 07:46 UTC
Labels: Duplicate
