### ISSUE TITLE
Module message erreur site PrestaShop 1.7.7.5

### ISSUE THREAD

**Issue by Arkandias33** [PrestaShop/PrestaShop#30563] opened 2022-12-13 10:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [ ] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour, 

Le service client m'a redirigé vers ce module pour mettre un site PrestaShop 1.7.7.5 en  1.7.7.8
mais quand j'ai voulu mettre le zip un message d'erreur est apparue 

### Steps to reproduce

1. Télécharger le zip https://github.com/PrestaShop/autoupgrade
2. cliquer sur installer un module
3. Drag and Drop le module
4. Message d'erreur apparait 

### PrestaShop version(s) where the bug happened

1.7.7.5

### If your bug is related to a module, specify its name and its version

autoupgrade-dev

**Comment by AureRita** [comment] 2022-12-13 15:39
Hi @Arkandias33 

Thank you for your report. For information, the issues are treated in English to allow everyone to follow your outcome. I tested to reproduce your issue as you can see on this video : 

[Untitled_ Dec 13, 2022 4_36 PM.webm](https://user-images.githubusercontent.com/100699445/207377346-9bcaf656-d0e7-4f7d-9b4f-5736dc2f339c.webm)

But I can't reproduce it. Did I miss something ? Did you install the zip like I did ? 

Waiting for your feedback

**Comment by hibatallahAouadni** [comment] 2023-01-02 09:22
Hello @Arkandias33 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-01-02 09:22 UTC
Labels: Bug, BO, Autoupgrade, 1.7.7.5, Invalid, Module
