### ISSUE TITLE
Product variants do not show up , product can´t be saved #12522 - now the same issue while using PS 1.7.5.2 in combination with PHP 7.2

### ISSUE THREAD

**Issue by ogi99** [PrestaShop/PrestaShop#14368] opened 2019-06-25 18:00 UTC
Describe the bug
Product variants do not show up
A product with variants can´t be edited or saved

To Reproduce

Go to 'product with variants '
Click on 'variations`
no variants
See error
Bug History:
I always had the error "can´t be saved" while creating a product with variants.
But they did show up.
After the change from a supdomain to the maindomain the variants do not show up at all.
Fron-end works fine,
But i can not change any product with variants .. it will not save the changes

Screenshots
If applicable, add screenshots or screenrecords to help explain your problem.

Additionnal information
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-06-26 07:36
Hi @ogi99,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-26 06:08
Hi @ogi99,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks

**Closed as completed by khouloudbelguith** 2019-07-26 06:08 UTC
Labels: Bug, BO, Combinations, No change required, 1.7.5.2
