### ISSUE TITLE
[CART RULES] Free shipping in coupons doesn't work

### ISSUE THREAD

**Issue by galantematteo** [PrestaShop/PrestaShop#29485] opened 2022-08-30 19:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When there is a free shipping voucher, in the checkout page => cart details, the total line is incorrect cause include everytime the shipping (img ex. 131.99 - 45.5 = 86.49 <-- tax inc. - my shipment cost 12.50 --> 86.49 + 12.50 = 98.99)
### Expected behavior

What should be done is to stop adding shipping cost to the total

### Steps to reproduce

1. Create a voucher with "Free shipping" selected
2. Go on the store, add a product that satisfy voucher rules and use in checkout
3. Nothing changes in total price

![1bug](https://user-images.githubusercontent.com/87337971/187531138-c378fa78-16cd-4760-ab07-85f5a2e78242.jpg)
![2bug](https://user-images.githubusercontent.com/87337971/187531144-a1fc7480-cee8-46bf-a62f-e8ace172de96.jpg)

### PrestaShop version(s) where the bug happened

1.7.8.7 - 1.7.7.8

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment] 2022-08-31 12:55
Hi @galantematteo 

Thank you for your reporting, I reproduce your issue and I think it can be the same that this feature that already exist: https://github.com/PrestaShop/PrestaShop/issues/28287

Tell me if you are aggree with this.

If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you.  

Waiting for your feedback

**Comment by galantematteo** [comment] 2022-08-31 13:00
Yes, same problem!
Maybe an hyptetic release for this core bug?

Thx

**Comment by AureRita** [comment] 2022-08-31 13:54
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28287

**Closed as not planned by AureRita** 2022-08-31 13:54 UTC
Labels: Bug, FO, Duplicate, Catalog, Discounts, Cart rules, Invalid
