### ISSUE TITLE
CacheMemcached don't add server

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#10385] opened 2018-09-11 20:49 UTC
**The bug**
If I want to add a server Memcached, BO don't add server. HTTP Status: 400

**To Reproduce**
1. Go to 'prestation'
2. Inside 'Cache box'
3. Want to 'Add a server'

**Screenshots**
<img width="482" alt="cachememcached" src="https://user-images.githubusercontent.com/2458824/45386601-08521b80-b614-11e8-948b-0d3c08427f21.png">

<img width="1069" alt="info errors" src="https://user-images.githubusercontent.com/2458824/45386706-43ece580-b614-11e8-8dae-da42fef4d364.png">

<img width="1073" alt="deprecations" src="https://user-images.githubusercontent.com/2458824/45386710-494a3000-b614-11e8-84d5-02a9814b3235.png">

<img width="1072" alt="debug" src="https://user-images.githubusercontent.com/2458824/45386720-50713e00-b614-11e8-8d04-3a9b52443c86.png">

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.21

<img width="587" alt="info server" src="https://user-images.githubusercontent.com/2458824/45386654-24ee5380-b614-11e8-918e-44e53297f798.png">

<img width="589" alt="conf status" src="https://user-images.githubusercontent.com/2458824/45386669-2ae43480-b614-11e8-9c0e-cdea3d7dc6b2.png">

**Comment by MathiasReker** [comment] 2018-09-11 21:03
Do you have the same issue that is solved in this PR #9542 ?

**Comment by ghost** [comment] 2018-09-11 21:09
It seems similar..; what is the solution?

**Comment by MathiasReker** [comment] 2018-09-11 21:13
My bad, thought I sent you the link to the PR. Here you go https://github.com/PrestaShop/PrestaShop/pull/10201

**Comment by khouloudbelguith** [comment] 2018-09-12 09:49
Hi @dritancami,

This issue is fixed with this PR: #10201 just provided by @Mreker.
It is fixed in the next release 1.7.5.0
Your ticket is a duplicate of #9542
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-12 09:49
Duplicate of #9542

**Closed as completed by khouloudbelguith** 2018-09-12 09:49 UTC
