### ISSUE TITLE
Emails translations Save and stay problem

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#16546] opened 2019-11-26 11:32 UTC
When i translate email themes in my custom theme and click Save and stay page reload to Core (not theme selected) translation. Translation files save ok in theme/my_theme/mails.
When i try to translate Core (not theme selected) email it works well. File is saving ok and backend stay on correct translation.

**To Reproduce**
1. International -> Translations
2. Select: Email translations -> body -> custom theme (my is jms_onebuy) -> language
3. Change one from Core emails ex test.
4. Click Save and stay. When Successful update check test template.
5. I see content from Core (not theme selected).

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.23

**Comment by khouloudbelguith** [comment] 2019-11-26 11:36
Hi @simon12q,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14182
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-11-26 11:36
Duplicate of #14182

**Closed as completed by khouloudbelguith** 2019-11-26 11:36 UTC
Labels: Duplicate
