### ISSUE TITLE
Problème Dropdown employee in BO

### ISSUE THREAD

**Issue by Peterits** [PrestaShop/PrestaShop#11372] opened 2018-11-13 17:02 UTC
Hello the team !
Problème Dropdown employee in BO
In news pages symfony:

 - Orders: 
                - Invoices
                - Delivery Slips

 - Catalog: 
                 - Products
                 - Stock management

 - Modules: 
                   - Module manager
                   - Modules catalog

 - Design: 
                - Themes Catalog
                - Positions

 - Shipping: 
                  - Preferences

 - Payment: 
                   - Payment Methods
                   - Preferences

 - International: 
                  - Localization
                  - Geolocation
		  - Translation

 - Shop Parameters: 
                    - Général
		    - Order settings
		    - Product Settings
		    - Customers
		    
 - Traffic & SEO: 
                          - SEO & URLs
		  
 - Advanced Parameters: 
                        - Information
		        - Performance
			- Administration
			- E-mail
			- Import
			- Logs

**To Reproduce**
Go to the BO

**Screenshots**
![symfony-bo](https://user-images.githubusercontent.com/44966543/48429739-ff91d900-e76d-11e8-9a91-800fea6d7db4.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 beta
PHP version: 7.1.23

**Comment by khouloudbelguith** [comment] 2018-11-13 17:06
Hi @Peterits,

Here's the PR: #11104 to fix the issue.
Your ticket is a duplicate of #11042
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-13 17:06
Duplicate of #11042

**Closed as completed by khouloudbelguith** 2018-11-13 17:06 UTC
Labels: Duplicate
