### ISSUE TITLE
Print issue in back office

### ISSUE THREAD

**Issue by Studio3Points** [PrestaShop/PrestaShop#10272] opened 2018-09-04 13:33 UTC
**Describe the bug**
When you try to print something in the back office, exemple : in the order pane, click on print button or in the print function of the navigator. There are a bug in the print result. It print but it's show the left control panel (like php fonction or java text).

**To Reproduce**
1. Go to 'Order'
2. Click on a order and click on 'Print order'
3. On the left page it show (php function or something like script text)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![capture](https://user-images.githubusercontent.com/42969476/45034416-c1828580-b057-11e8-9160-17784538e31d.PNG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.21

**Comment by khouloudbelguith** [comment] 2018-09-04 13:39
Hi @Mathorix 

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10135 to solve the issue.
Your ticket is a duplicate of #9527
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-04 13:39
Duplicate of #9527

**Closed as completed by khouloudbelguith** 2018-09-04 13:39 UTC
Labels: Duplicate

**Comment by Studio3Points** [comment] 2018-09-04 13:59
Hi,

 

Ho sorry I didn't saw :-/

Thanks a lot for the support

 

Best regards, Mathias

 

De : khouloudbelguith <notifications@github.com> 
Envoyé : mardi, 4 septembre 2018 15:39
À : PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc : Mathorix <mathrix@bluewin.ch>; Author <author@noreply.github.com>
Objet : Re: [PrestaShop/PrestaShop] Print issue in back office (#10272)

 

Hi @

Here's the PR: #10135 <https://github.com/PrestaShop/PrestaShop/pull/10135>  to solve the issue.
Your ticket is a duplicate of #9527 <https://github.com/PrestaShop/PrestaShop/issues/9527> 
So, I close it.
Thanks!

Best regards, Khouloud
