### ISSUE TITLE
Css and JS are not loaded

### ISSUE THREAD

**Issue by jyothi0093** [PrestaShop/PrestaShop#18796] opened 2020-04-24 06:48 UTC
hi i'am able to install the project but, not able to load the assets(js and css),theme as make assets always fails.
and if i run docer compose up also i get the connectivity issue

**Comment by florine2623** [comment] 2020-04-24 07:46
Hi @jyothi0093 ,
What version are you using ?
Do you have a specific error ?

**Comment by jyothi0093** [comment] 2020-04-24 07:56
binding.target.mk:131: recipe for target
'Release/obj.target/binding/src/create_string.o' failed
make[1]: *** [Release/obj.target/binding/src/create_string.o] Error 1
make[1]: Leaving directory
'/opt/lampp/htdocs/PrestaShop/themes/classic/_dev/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/opt/lampp/htdocs/PrestaShop/themes/classic/_dev/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-96-generic
gyp ERR! command "/usr/local/bin/node"
"/opt/lampp/htdocs/PrestaShop/themes/classic/_dev/node_modules/node-gyp/bin/node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags="
"--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
/opt/lampp/htdocs/PrestaShop/themes/classic/_dev/node_modules/node-sass
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN prestashop-classic-dev-tools@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2
(node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current:
{"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codingmart/.npm/_logs/2020-04-24T07_54_43_271Z-debug.log
Makefile:7: recipe for target 'assets' failed
make: *** [assets] Error 1

im getting this error

**Comment by florine2623** [comment] 2020-04-24 08:12
Are you using docker ?

**Comment by jyothi0093** [comment] 2020-04-24 08:21
if i use docker i get this error
*Link to database cannot be established: SQLSTATE[HY000] [2002] No such
file or directory*

**Comment by florine2623** [comment] 2020-04-24 10:03
I'm asking that because in your first message you said "if i run docer compose".
So what is your preferred way of installing PrestaShop ? Docker ? Apache server ? Other ?

For that error : 
_Link to database cannot be established: SQLSTATE[HY000] [2002] No such
file or directory_
It means that you can't connect to your database, you need to verify the file /app/config/parameter.php and make sure the database info matches the database you created for your shop.
Please check that file.

**Comment by jyothi0093** [comment] 2020-04-24 10:06
Prefferee way is docker, my db credentials are correct even though im not
able to install

**Comment by florine2623** [comment] 2020-04-24 22:06
Have you made any specific development ?
I can't reproduce your issue.

**Comment by PierreRambaud** [comment] 2020-04-27 16:15
Hi @jyothi0093 
Do you follow our documentation for building assets: https://devdocs.prestashop.com/1.7/development/compile-assets/ ?

**Comment by jyothi0093** [comment] 2020-04-28 07:03
> Hi @jyothi0093
> Do you follow our documentation for building assets: https://devdocs.prestashop.com/1.7/development/compile-assets/ ?

yes but make assets always failed showing the above listed npm errors, only admin panel is accessable.

**Comment by PierreRambaud** [comment] 2020-04-28 07:42
@jyothi0093 What is your node version? Can you show us the exact stack trace?

**Comment by foga92** [comment] 2020-05-02 11:22
Same problem for me. 
Also try with different nodejs versione but same issue. 
And i confirm that only admin panel is visible

**Comment by PierreRambaud** [comment] 2020-05-04 10:09
@foga92 As I said above, we need the exact log trace to understand what happened

**Comment by florine2623** [comment] 2020-06-01 14:40
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-01 14:40 UTC
Labels: Bug, IN, No change required
