### ISSUE TITLE
Not possible to translate menu item Stocks in BO

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19584] opened 2020-06-04 21:49 UTC
Hello,
I use PS 1.7.6.5 and it is not possible to translate menu item in BO > Catalog > Stocks. The translation system is not able to find this text Stocks.

**Comment by florine2623** [comment] 2020-06-05 08:55
Hi @juraj1000 ,
What text are your talking about ?
Could you make a screenshot and highlight it so that it is clearer for me ?
Thanks

**Comment by juraj1000** [comment] 2020-06-05 09:40
Hello,
check menu item in BO, I use SK language in my user profile but there is not translated item Stocks, it is in EN language. I was not able to find this text in the translation tool.

![image](https://user-images.githubusercontent.com/33311857/83861682-2e411d00-a721-11ea-83a6-d0fe971719ae.png)

**Comment by florine2623** [comment] 2020-06-05 14:08
Hi @LouiseBonnard 👋 ,
Can the menu on the left be translated via International > Translations ?

Thank you :)

**Comment by LouiseBonnard** [comment] 2020-06-05 14:11
Hi there, this ticket is a duplicate of #9893 and will be fixed by #18082. I close this issue so that we can all focus on the original issue and the pull request linked to it, thanks!

**Closed as completed by LouiseBonnard** 2020-06-05 14:11 UTC
Labels: BO, Duplicate, Stocks, Translations
