### ISSUE TITLE
BO Product attributes MultiShop issue

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#19999] opened 2020-06-30 09:16 UTC
#### Describe the bug

Product attributes MultiShop issue

#### Expected behavior

The attributes should only be displayed in the correct shop

#### Steps to Reproduce

1. Make sure you are using multiShop
2. Create two attributes : Attribute1 associated to shop1 and Attribute2 associated to shop2
3. Go Shop1 > BO > Product > (Select a product with combinations)
4. See error ... You have Attribute2 in Shop1

**Screenshots**
![image](https://user-images.githubusercontent.com/16455155/86107442-1e1f2200-bac2-11ea-97c0-1f3566e16b49.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by matks** [comment] 2020-06-30 15:41
Not sure about this one 🤔 I think I remember @marionf telling me "a product, shared between 2 shops, cannot have different attributes". So this might be expected.

Can you tell us about it @marionf ?

**Comment by marionf** [comment] 2020-07-02 14:47
Hello @PululuK 

Your issue seems to be a duplicate of #9686 and a PR had been submited to fix this issue: #13217
Could you confirm if your issue is well a duplicate ?

@matks 

> "a product, shared between 2 shops, cannot have different attributes"

Yes you are right, but the problem is different here:
When you edit a product and select shop1 as context, you should see only the attributes associated to shop1 in the right column
When you edit a product and select shop2 as context, you should see only the attributes associated to shop2 in the right column
When you edit a product and select all shops as context, you should see the attributes associated to shop1 and shop2 in the right column

**Closed as completed** 2020-07-08 14:32 UTC
Labels: Bug, develop, Minor, BO, Duplicate, PR available
