### ISSUE TITLE
ps_socialfollow & ps_sharebuttons module - rename Twitter to X

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#37477] opened 2024-11-26 10:48 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Twitter was renamed to X two years ago. Now, it's time to update the name, icon and description to X in the [ps_socialfollow](https://github.com/PrestaShop/ps_socialfollow) and [ps_sharebuttons](https://github.com/PrestaShop/ps_sharebuttons) module as well. 

### Steps to reproduce

Remove the name 'Twitter' from everywhere.

### PrestaShop version(s) where the bug happened

8.2.0

### If your bug is related to a module, specify its name and its version

ps_sharebuttons, ps_socialfollow

**Comment by Hlavtox** [comment] 2024-11-26 10:57
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/35108, basically the first thing that comes up when searching "twitter".

**Comment by florine2623** [comment] 2024-11-26 13:52
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/35108

**Closed as completed by florine2623** 2024-11-26 13:52 UTC
Labels: Bug, Duplicate
