### ISSUE TITLE
BO - An exception is displayed in the product page V2 when importing a product without supplier

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28169] opened 2022-04-07 14:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I tried to import a product without a supplier, an exception is displayed
[product.csv](https://github.com/PrestaShop/PrestaShop/files/8443619/product.csv)
![image](https://user-images.githubusercontent.com/16067358/169081575-06eb5121-719d-4b30-bfa9-2680292fe90f.png)
before, I have this exception
![image](https://user-images.githubusercontent.com/16067358/162218310-7b0ae15c-61d3-43c8-8a90-b789a754e4c2.png)

### Steps to reproduce

1. Go to BO > Advanced Parameters > Import product csv without supplier
[product.csv](https://github.com/PrestaShop/PrestaShop/files/8443625/product.csv)
2. Go to BO > Catalog > Products V2
3. Edit the imported product

In the Product V1 => ok

### PrestaShop version(s) where the bug happened

8.x

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by MeKeyCool** [comment] 2022-05-18 15:04
It looks like the concerned code has been removed 8 days ago by a @jolelievre's PR : [Refacto combination suppliers #27353](https://github.com/PrestaShop/PrestaShop/pull/27353/files#diff-042ba91508474191c3fdd53097949caa387c210440d367931c675de594c790d7)

@khouloudbelguith , could you validate you still can reproduce the bug ?

**Comment by khouloudbelguith** [comment] 2022-05-18 15:27
Hi @MeKeyCool,

Yes, I still reproduce the issue with develop branch.
The exception is changed
![image](https://user-images.githubusercontent.com/16067358/169081382-91e7e649-92a4-4dea-b53b-59595a5f1ee3.png)

I attached a screen record

https://user-images.githubusercontent.com/16067358/169081186-09011e81-9585-464d-8524-42c00e10545c.mp4

Thanks!

**Comment by MeKeyCool** [comment] 2022-05-18 15:50
Thanks @khouloudbelguith ! In fact I missed a config in import form (your video helped a lot :D).
I can reproduce this issue now so if you can assign it to me, I'll start to look at it ^^

**Comment by MeKeyCool** [comment] 2022-05-19 14:55
@khouloudbelguith and/or @PrestaShop/product-team , could you confirm that `product type` and `supplier_id` are not mandatory fields ?

I found some code saying that they are mandatory but database and old behavior isn't consistent with those constraints.

**Comment by MeKeyCool** [comment] 2022-05-30 13:19
Thanks @matthieu-rolland for updating this issue ^^
@khouloudbelguith , for this issue, I think i'll need to have lots of dynamic discussions with you or product team member.
When you'll have time, let's decide how we will organize it :)

**Closed as completed** 2022-09-09 12:38 UTC
Labels: Bug, 8.0.x, Major, BO, Catalog, Import / Export, Suppliers, Regression, PR available, Verified
