### ISSUE TITLE
PS 1.7.4.2 No Api Geocoding Service Key in Backend 

### ISSUE THREAD

**Issue by tzak902** [PrestaShop/PrestaShop#12286] opened 2019-01-24 11:45 UTC
Hello,
From the backend, when I inspect the orders page, I'm seeing an error:

Geocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key
_.Jc @ js?v=3.exp:51
d @ geocoder.js:2
c @ common.js:67
(anonymous) @ VM480 GeocodeService.Search:1
util.js:220 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
nw.m @ util.js:220
(anonymous) @ js?v=3.exp:119
Promise.then (async)
(anonymous) @ js?v=3.exp:119
setTimeout (async)
Bh @ js?v=3.exp:119
google.maps.Load @ js?v=3.exp:18
(anonymous) @ js?v=3.exp:208
(anonymous) @ js?v=3.exp:208

![no-api-key](https://user-images.githubusercontent.com/39320435/51676079-8d2a4a00-1fa3-11e9-9a06-c01fb551e1a6.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-01-24 11:58
Hi @tzak902,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10393
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-24 11:58
Duplicate of #10393

**Closed as completed by khouloudbelguith** 2019-01-24 11:58 UTC
Labels: Duplicate

**Comment by colinegin** [comment] 2019-01-29 11:07
Hello and thanks for your feedback !

This needs to be discussed more in depth with the product team but here are a few comments/questions to start with : 
- where should the key field be located ?
- for those who have configured the option, it means they will "pay" for each order page they open. It might be expensive if they have many orders
- Regarding the feature itself (in the BO - order page), is it really necessary to have a map of the address location ? Shouldn't we just remove it ?

Do not hesitate to comment !

Have a nice day,

Coline
