### ISSUE TITLE
Bad displaying of the order status selectors and order status list in selector

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29045] opened 2022-07-12 09:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Screenshot from 2022-07-12 10-27-36](https://user-images.githubusercontent.com/90208051/178453672-41bcf8be-b216-4f40-9a58-61d3a76e8bcd.png)
![Screenshot from 2022-07-12 10-27-52](https://user-images.githubusercontent.com/90208051/178453674-7ee238d6-0198-48cf-97ff-64feefb7cac5.png)

See video:

https://user-images.githubusercontent.com/90208051/178453731-0695e258-0769-4bcc-bc25-8e27d0901010.mp4

### Expected behavior

As in previous versions
![Screenshot from 2022-07-12 11-20-13](https://user-images.githubusercontent.com/90208051/178456983-1dc4c4b9-f3ed-4811-a3ec-38fab16a93f7.png)

### Steps to reproduce

1. Open some order page in BO
2. Check order status selector 
3. Change order status 
4. Check list with statuses 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-07-12 18:37
Hello @szavadskiy 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28405. 
And it's already fixed, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/178569319-ef84d19e-b7b4-4396-b45c-5c9189888854.mp4

Thanks!

**Closed as completed by hibatallahAouadni** 2022-07-12 18:37 UTC
Labels: Bug, Duplicate, Invalid

**Comment by hibatallahAouadni** [comment] 2022-07-12 18:39
Duplicate of #28405
