### ISSUE TITLE
Can access categories

### ISSUE THREAD

**Issue by sotirisa** [PrestaShop/PrestaShop#17371] opened 2020-01-27 10:18 UTC
**Describe the bug**
After upgrade to 1.7.6.3 I create new categories and it says to me that I don't have access to them. The categories that exist before the upgrade are fine only the new ones.

**To Reproduce**
1. Go to categories and create new. 
2. After that go to www.yourdomain.com/number of new category-name of the category

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-01-27 10:34
Hi @sotirisa,

I did not manage to reproduce the issue with PS1.7.6.3 fresh install & PS1.7.6.3 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1.
https://drive.google.com/file/d/1m4pkiM4oujhlqKDYMpYwi18iJsdPGhp-/view
What is the exact version of the 1-click upgrade did you use?
Have you any errors during the upgrade?

Thanks!

**Comment by sotirisa** [comment] 2020-01-27 18:28
Hi and thank you for your reply. 

It is not a problem from the upgrade to 1.7.6.3 because this problem is also with 1.7.6.1. I did a rollback and I check it.
Now when I create a new category, if I'm going to this category, I get the message.
"You can not access this category."

Did you happen to know why this is happening?

**Comment by khouloudbelguith** [comment] 2020-01-28 08:02
@sotirisa, are you using an employee with a super admin profile or not?

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-27 07:56
Hi @sotirisa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-27 07:56 UTC
Labels: Bug, BO, Categories, Autoupgrade, No change required, 1.7.6.3
