### ISSUE TITLE
Installation => '1: Error sent by Addons. You may need to be logged.'

### ISSUE THREAD

**Issue by william-dandrea** [PrestaShop/PrestaShop#25144] opened 2021-06-28 13:18 UTC
I have this message error when I want to install prestashop on my localhost (with MAMP and I have the same probleme with docker) : '1: Error sent by Addons. You may need to be logged.'

I'm on MacOS last version. I found any response on internet and several peoples have the same problem.

(I try to install with the french version)
<img width="1004" alt="Capture d’écran 2021-06-28 à 15 18 16" src="https://user-images.githubusercontent.com/71140800/123642871-12288600-d824-11eb-9f96-4adb5cde2181.png">

**Comment by hibatallahAouadni** [comment] 2021-06-28 14:44
Hello @william-dandrea 

It seems your internet speed is very low. The issue is not related to PS Core.

I'm really sorry but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by hibatallahAouadni** 2021-06-28 14:44 UTC
Labels: No change required
