### ISSUE TITLE
HTTP empty response after product PUT

### ISSUE THREAD

**Issue by TomLorenzi** [PrestaShop/PrestaShop#31548] opened 2023-02-27 10:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When trying to add a product in Prestashop using the WebService PHP Library I'm getting a "HTTP emty response" error.

### Expected behavior

I should get the updated product.

### Steps to reproduce

1. Use the product route
2. Send a PUT Request
3. Get the error

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment] 2023-02-27 15:54
Hello @TomLorenzi 
Could you please provide us how you used the WebService PHP from a screen record or screenshots ? 

Thank you !

**Comment by TomLorenzi** [comment] 2023-02-28 08:28
Here's an ugly simplified way I'm using the webservice to reproduce the error

```php
$webService = new PrestaShopWebservice('https://example.com', 'apiKey', false);
$blankXml = new SimpleXMLElement($webService->get(['url' => "https://example.com/api/products?schema=blank"])->asXML());
$xmlProduct = $blankXml->children()->children();
unset($xmlProduct->id);
$xmlProduct->state = 1;
$xmlProduct->id_category_default = '1';
$xmlProduct->id_shop_default = '1';
$xmlProduct->reference = 'test';
foreach ($xmlProduct->name->language as $languageNode) {
    $languageNode[0] = 'test';
}
unset($xmlProduct->manufacturer_name, $xmlProduct->quantity, $xmlProduct->position_in_category);

$updatedXml = $webService->add([
    'resource' => 'products',
    'postXml' => $blankXml->saveXML(),
]);
```

Maybe it's POST instead of PUT then, I may have made a mistake in the issue name

**Comment by HanaRebaiQA** [comment] 2023-03-02 16:27
Hello @TomLorenzi 

Thanks for your report.
I was unable to reproduce your issue using the same steps to reproduce on PS8.0.1 with `POST` and `PUT` methods.

https://user-images.githubusercontent.com/92912932/222490473-6d0483ae-7926-4784-8f8b-90f746409281.mp4


Could you please check it again?

Thank You!

**Comment by TomLorenzi** [comment] 2023-03-03 08:13
@HanaRebaiQA do you have PHP notice enabled ?

**Comment by florine2623** [comment] 2023-03-03 13:59
Hello @TomLorenzi ,

I can't reproduce your issue.

https://user-images.githubusercontent.com/16019289/222738497-0b84658a-4c4b-42db-8c5f-3fd1238293dd.mov

I have the PHP notice enabled :
<img width="202" alt="Screenshot 2023-03-03 at 14 56 07" src="https://user-images.githubusercontent.com/16019289/222738392-b5adf9a8-4192-423a-a6c5-9f52a690320c.png">

Are you using PHP 7 ou PHP 8 ?

**Comment by TomLorenzi** [comment] 2023-03-03 15:26
PHP 7.4 as written in the issue description

**Comment by florine2623** [comment] 2023-03-03 15:48
I can't reproduce your issue on my end. Maybe there's something more about your config ?

Can you send a screenshot of your error ?

**Comment by florine2623** [comment] 2023-03-17 10:32
Hello @TomLorenzi ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2023-03-17 10:32 UTC
Labels: Bug, WS, Invalid, 8.0.0
