### ISSUE TITLE
Bug Link admin Module Controller

### ISSUE THREAD

**Issue by ethercreation** [PrestaShop/PrestaShop#15810] opened 2019-10-03 13:24 UTC
Hello,

Currently I am getting issue on my module's admin controller render list page in Prestashop V1.7.6.1 while my controller's render list has some data.
After research, I found that I am getting this issue because I am not using $this->identifier name similar to $this->table name on module's admin controller page.
For example, my table name is 'product_review' and here I am using primary key as 'id_review' So in this case, I will define $this->identifier = 'id_review' on module admin controller.

In previous prestashop version (below V1.7.6.1), I don't have any issue like this but on current prestashop V1.7.6.1, I am getting a error -
"Notice: Undefined index: id_product_review"

Check this screenshot - https://prnt.sc/ozmiwc

In Prestashop V1.7.6.1, you are always getting entity like - 'id_' . $table_name
So have you restrict it in current version 1.7.6.1 because you didn't mention anything like this before.

    Create a table in module i.e. table name 'product_review' and set primary key in this table as 'id_review'
    Create a module's admin controller and set
    $this->identifier = 'id_review'
    $this->table = 'product_review'

Now while you will add any data in your table and when you see render list of your admin controller then you will get issue like "Notice: Undefined index: id_product_review"
https://prnt.sc/ozmiwc

Here if I used my primary key as 'id_product_review' then I will get no error. So It looks like It is mandatory to set table primary key same table name.

Screenshots -

error

PrestaShop version: 1.7.6.1

**Comment by ethercreation** [comment] 2019-10-03 13:26
Correctif : 
/src/Adapter/Routing/LegacyHelperLinkBuilder.php

Before 👎 
    private function buildActionParameters($action, $entity, array $parameters)
    {
        unset($parameters['current_index']);
        $viewAction = $action . $entity;
        $entityId = 'id_' . $entity;
        $parameters = array_merge(
            $parameters,
            [$entityId => $parameters[$entityId], $viewAction => 1]
        );

        return $parameters;
    }


After 👍 
`    private function buildActionParameters($action, $entity, array $parameters)
    {
        unset($parameters['current_index']);
        unset($parameters['token']);
        $viewAction = $action . $entity;
        
        $parameters = array_merge(
            $parameters,
            [$viewAction => 1]
        );

        return $parameters;
    }`

**Comment by khouloudbelguith** [comment] 2019-10-03 13:29
Hi @ethercreation,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15382 to fix the issue.
It is fixed in the next patch 1.7.6.2.
Your ticket is a duplicate of #15333
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-03 13:29
Duplicate of #15333

**Closed as completed by khouloudbelguith** 2019-10-03 13:29 UTC
Labels: Duplicate
