### ISSUE TITLE
webservice json body

### ISSUE THREAD

**Issue by esfahanweb** [PrestaShop/PrestaShop#11100] opened 2018-10-22 04:56 UTC
hi,

is there any idea about your web service interact with JSON?
I know that we can get output data as JSON with output_format=JSON but seems that can't post body as JSON

best regards

**Comment by khouloudbelguith** [comment] 2018-10-22 13:43
Hi @esfahanweb,
So, this one can be closed
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-22 13:43
Duplicate of #11099

**Closed as completed by khouloudbelguith** 2018-10-22 13:43 UTC
Labels: Duplicate
