### ISSUE TITLE
Cannot setup DEV Mode from BO when a defines_custom.inc.php is defined

### ISSUE THREAD

**Issue by mehdi-ghezal** [PrestaShop/PrestaShop#11234] opened 2018-11-02 04:18 UTC
**Describe the bug**

When we have a custom configuration in defines_custom.inc.php ; if we don't put the _PS_MODE_DEV_  constant in the file, we cannot update DEV Mode from BO.

**To Reproduce**
Create a defines_custom.inc.php
Go to BO
Enable DEV Mode
You have a success message but the DEV Mode is not enabled

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2018-11-02 14:21
Hi @mehdi-ghezal,

You can create a file `config/defines_custom.inc.php` next to `config/defines.inc.php`. 
At startup Prestashop checks if this file exists. If it exists then it is included before the default one.

You can find the related code in config/config.inc.php :

```
$currentDir = dirname(__FILE__);

/* Custom defines made by users */
if (is_file($currentDir.'/defines_custom.inc.php')) {
    include_once($currentDir.'/defines_custom.inc.php');
}
require_once($currentDir.'/defines.inc.php');

```
This way you can for example set mode dev on without touching the default file:

```define('_PS_MODE_DEV_', true);```

And in the default file, this define will not occur:

```
if (!defined('_PS_MODE_DEV_')) {
    define('_PS_MODE_DEV_', false);
}
```

Thanks to check & feedback.

**Comment by mehdi-ghezal** [comment] 2018-11-06 03:05
Hi,

It's actually my setup, my shop is behind a reverse proxy so I add some custom settings in `config/defines_custom.inc.php` but I didn't add `define('_PS_MODE_DEV_', true);` as it out of the scope of my need.

As a result, when you change the Mode debug in backoffice of Prestashop it doesn't work. In my case, [this code is called (note the return)](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Debug/DebugMode.php#L176) and it lead to [this statement](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Debug/DebugMode.php#L150) that of course doens't match as I don't have set the constant `_PS_MODE_DEV_`.

And because of the return of my first quote, nothing else is done and the Mode debug cannot be update.

I hope it's more clear :)

Best regards

**Comment by khouloudbelguith** [comment] 2018-11-06 08:34
Hi @mehdi-ghezal,

Could you please provide your config/defines_custom.inc.php file to test with it.
Thanks!

**Comment by mehdi-ghezal** [comment] 2018-11-06 10:34
The content doesn't really matter as long as you don't put `define('_PS_MODE_DEV_', false)` in the file, the bug happen.

My configuration file

```
<?php

if (isset($_SERVER['HTTP_X_REAL_HOST']) && $_SERVER['HTTP_X_REAL_HOST']) {
    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_REAL_HOST'];
    $_SERVER['SERVER_NAME'] = $_SERVER['HTTP_X_REAL_HOST'];
}

if (isset($_SERVER['HTTP_X_REAL_REQUEST_URI']) && $_SERVER['HTTP_X_REAL_REQUEST_URI']) {
    $_SERVER['REQUEST_URI'] = $_SERVER['HTTP_X_REAL_REQUEST_URI'] . $_SERVER['REQUEST_URI'];
    $_SERVER['SCRIPT_NAME'] = $_SERVER['HTTP_X_REAL_REQUEST_URI'] . $_SERVER['SCRIPT_NAME'];
    $_SERVER['DOCUMENT_URI'] = $_SERVER['HTTP_X_REAL_REQUEST_URI'] . $_SERVER['DOCUMENT_URI'];
    $_SERVER['PHP_SELF'] = $_SERVER['HTTP_X_REAL_REQUEST_URI'] . $_SERVER['PHP_SELF'];
}

if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['REQUEST_SCHEME'] = 'https';
    $_SERVER['SERVER_PORT'] = 443;
    $_SERVER['HTTPS'] = 'on';
}
```

**Comment by khouloudbelguith** [comment] 2018-11-06 16:06
Hi @mehdi-ghezal,

Yes, When I created the file config/defines_custom.inc.php, I'm not able to disable the Debug mode.
https://drive.google.com/file/d/1oQAZ7cD-f0PpNW-z9JeLbrUlU9F1ykI7/view
@marionf, what do you think?
Thanks!

**Comment by marionf** [comment] 2018-11-06 16:26
No, idea we should ask to a dev @eternoendless

**Comment by dvitcompte** [comment] 2019-12-12 10:30
Hello everyone.

The issue is still there on PretaShop 1.7.6.2

I created a defines_custome.inc.php file, then I wanted to disable the debug mode in the BO, but it kept enabled...
Delete the file and the BO is working properly.

Any news regarding this strange issue ?

Best regards,

**Comment by PierreRambaud** [comment] 2020-10-12 13:12
I did not manage to reproduce the issue.
I create a `defines_custom.inc.php` with `define('_PS_MODE_DEV_', false);` and the debug mode is properly disable.

**Comment by khouloudbelguith** [comment] 2020-10-12 13:38
HI @PierreRambaud,

Thanks!
I did not manage to reproduce the issue with PS1.7.6.8 in my case also.
I close the issue since it is not reproduced.

**Closed as completed by khouloudbelguith** 2020-10-12 13:38 UTC
Labels: Bug, CO, Can't reproduce, Performance

**Comment by jf-viguier** [comment] 2024-12-12 16:37
> I create a defines_custom.inc.php with define('_PS_MODE_DEV_', false); and the debug mode is properly disable.

yes, read carrefully. The issue occurs when _PS_MODE_DEV_ is NOT in defines_custom.inc.php

Please reopen.

**Comment by PierreRambaud** [comment] 2024-12-13 08:12
> > I create a defines_custom.inc.php with define('_PS_MODE_DEV_', false); and the debug mode is properly disable.
> 
> yes, read carrefully. The issue occurs when _PS_MODE_DEV_ is NOT in defines_custom.inc.php
> 
> Please reopen.

Hi, you should open a new issue, this one is 4 years old 👀

**Comment by jf-viguier** [comment] 2024-12-13 10:22
why @PierreRambaud ? It's still relevant

**Comment by PierreRambaud** [comment] 2024-12-13 10:28
Because the 1.7 is maybe not maintained anymore, same for the php version. Sometimes it's better to create a new one with information related to the recent version instead of making an issue living for years

**Comment by jf-viguier** [comment] 2024-12-13 10:36
Ok Pierre, new issue created here https://github.com/PrestaShop/PrestaShop/issues/37660
