### ISSUE TITLE
Cannot add EAN for product

### ISSUE THREAD

**Issue by FabienPapet** [PrestaShop/PrestaShop#31396] opened 2023-02-16 11:14 UTC
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/31365

<div type='discussions-op-text'>

<sup>Originally posted by **minhcz** February 15, 2023</sup>
Hello,

During insert product to Prestashop i got problem is cannot add EAN for product. After insert and save successful, reopen product editor that EAN field empty. Anyone faced this bug?

Version 8.0.1 Multistore, php 8.1.2, cache off.

Thank you</div>

**Comment by florine2623** [comment] 2023-02-16 14:02
Hello @minhcz @FabienPapet ,

I couldn't reproduce the issue with the information provided.

I have a multistore with 2 shops.

Here's what I have :

https://user-images.githubusercontent.com/16019289/219385643-fdd53c14-82f6-4521-a14b-c12aad26c8cc.mov

Please check and feedback.
Thanks!

**Comment by minhcz** [comment] 2023-02-16 19:28
Hello @florine2623,

Have you tried edit product for all store by one time? (not by selected store and edit product)

Thank you.

**Comment by sallemiines** [comment] 2023-02-17 10:17
Hello @FabienPapet 

As @florine2623 mentionned,  I can't also reproduce the issue with ps 8.01
@minhcz could you please provide us a screenrecord / screenshot  ? 

Thank you !

**Comment by sallemiines** [comment] 2023-02-17 10:48
@FabienPapet 

Unfortunately, we're going to close this issue, you need to follow the template, and it shouldn't transfer the devs discussion .
Feel free to create a new issue , we will be glad to investigate it. 

Thank you

**Closed as completed by sallemiines** 2023-02-17 10:48 UTC
Labels: Bug, BO, Multistore, Invalid, 8.0.1

**Comment by minhcz** [comment] 2023-02-17 23:57
Hello,

i just made screen record.
https://user-images.githubusercontent.com/69456300/219818364-75293d2f-525a-4921-9519-e13669e1fdfd.mov
