### ISSUE TITLE
Error with cart gift message field with the following characters < > { }

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#34658] opened 2023-11-23 11:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If during the order phase in the cart you enter one of the following characters < > { } in the "gift message" field (If you'd like, you can add a note to the gift:), the system will give an error.

Instead for the order message field "If you would like to add a comment about your order, please write it in the field below." the system removes the < > characters but accepts the { } characters

I attach videos

https://github.com/PrestaShop/PrestaShop/assets/2463965/3552e10a-6c87-4c03-bae5-be8bb0273c36

https://github.com/PrestaShop/PrestaShop/assets/2463965/3d528a9e-27e5-4433-aae5-49a5ffc73d4d

### Steps to reproduce

1. In front-office create a cart
2. In the "Shipping Method" step, complete the "If you'd like, you can add a note to the gift:" field with one of the following characters < > { }
3. The system shows an error if debugging is active, otherwise it shows a generic 500 error.

### PrestaShop version(s) where the bug happened

1.7 / 8

### PHP version(s) where the bug happened

all

**Comment by Hlavtox** [comment] 2023-11-23 11:53
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9574

**Closed as completed by Hlavtox** 2023-11-23 11:53 UTC
Labels: Bug, Duplicate

**Comment by Codencode** [comment] 2023-11-23 12:04
> Duplicate of #9574

Ok thanks.
