### ISSUE TITLE
Backend Admin Cannot select "Stay Logged in"

### ISSUE THREAD

**Issue by burty1109** [PrestaShop/PrestaShop#27954] opened 2022-03-18 06:36 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Capture](https://user-images.githubusercontent.com/82091853/158949331-89f26db2-dd66-43a4-b60a-9cb04745b7dc.JPG)

Since upgrading to 1.7.8.4 - the login ADMIN page has broken and you cannot select the stay logged in option

PHP7.4

### Expected behavior

Be able to use as normal

### Steps to reproduce

1. GO to admin login page
2. you will see the broken page

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment] 2022-03-18 09:00
Hello @burty1109 

Thanks for your report.
This issue is the same of this one [#27835](https://github.com/PrestaShop/PrestaShop/issues/27835 ) which is fixed in this [PR](https://github.com/PrestaShop/PrestaShop/pull/27843).
So, it'll be fixed in the next released version.

Thank you.

**Comment by HanaRebaiQA** [comment] 2022-03-18 09:01
Duplicate of [#27835](https://github.com/PrestaShop/PrestaShop/issues/27835 )

**Closed as completed by HanaRebaiQA** 2022-03-18 09:01 UTC
Labels: Bug, Duplicate

**Comment by dolmenhir** [comment] 2022-03-18 12:04
While waiting for a fix, you can add these lines
`#login_form .form-group {
    position: relative;
}`
in "/[admin-folder]/themes/default/css/overrides.css"
