### ISSUE TITLE
add to cart button is disabled

### ISSUE THREAD

**Issue by web-centre** [PrestaShop/PrestaShop#10882] opened 2018-10-05 16:09 UTC
Hi, work on prestashop 1.7.4,
I recently noticed that on some (not all) products, the add to cart button is disabled even if the product is in stock.

for example from this link https://web-centre.it/negozi/buonprezzo/it/illuminazione-led/84139-proiettore-led-di-stelle-innovagoods-8435527811433.html

it is not possible to add the product to cart even though there are 10 products available

**Comment by khouloudbelguith** [comment] 2018-10-08 10:11
Hi @web-centre,

I did not manage to reproduce the issue with PS 1.7.4.2 / 1.7.4.3.
https://drive.google.com/file/d/1HtBdwJMBUnrAfBsSMF9r3onu67DMERSj/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by web-centre** [comment] 2018-10-08 10:21
Good morning.
My prestashop version is 1.7.2.4
php: 5.6

to recreate the erroe it is sufficient to go on this link
https://web-centre.it/negozi/buonprezzo/it/illuminazione-led/84139-proiettore-led-di-stelle-innovagoods-8435527811433.html
and click on "add to cart" you will notice that the button remains blogged even if there are enough products, also the same problem happens in other products

![errorlog](https://user-images.githubusercontent.com/43772147/46603756-63ccd780-caf4-11e8-8ca9-bc973e22e4f5.JPG)

**Comment by ghost** [comment] 2018-10-08 10:53
![bez-nazwy-2](https://user-images.githubusercontent.com/8243273/46605210-0a1adc00-caf9-11e8-80f7-4e633d41b620.jpg)
Looks like .js problem (Empty string passed to getElementById().)

**Comment by web-centre** [comment] 2018-10-08 11:30
and how do you solve it?

**Comment by khouloudbelguith** [comment] 2018-10-09 08:18
@web-centre, could you please try to enable debug mode and paste the error that you get

**Comment by web-centre** [comment] 2018-10-10 06:50
![debug1](https://user-images.githubusercontent.com/43772147/46717811-77e61580-cc69-11e8-8149-8953b27c1b02.JPG)

**Comment by khouloudbelguith** [comment] 2018-10-10 08:07
@web-centre, thanks to disable the ganalytics module, clear cache, check & feedback.

**Comment by web-centre** [comment] 2018-10-10 16:24
Resolved,
thank you

**Comment by khouloudbelguith** [comment] 2018-10-10 16:28
@web-centre, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

**Closed as completed by khouloudbelguith** 2018-10-10 16:28 UTC
Labels: Bug, FO, Fixed, 1.7.4.3
