### ISSUE TITLE
Database acces with SSL

### ISSUE THREAD

**Issue by NicolasSogeti** [PrestaShop/PrestaShop#14649] opened 2019-07-15 08:47 UTC
Hello,
i need to access to my database with SSL.
The only information i found about it is this ticket https://github.com/PrestaShop/PrestaShop/issues/10784 . But i don't like the answer, the only way seems to hack prestashop core.
This ticket was opened on October 2018, have you make some evolution on Prestashop to allow your community to configure SSL access ? Have you planned to do it ? Is there a good way to implements it on a Prestashop solution ?

**Comment by mariem-abid** [comment] 2019-07-15 09:37
Hi @NicolasSogeti,

Sorry, not yet.
Your ticket is a duplicate of #10784
So, I close it.
Thanks!

**Comment by mariem-abid** [comment] 2019-07-15 09:38
Duplicate of #10784

**Closed as completed by mariem-abid** 2019-07-15 09:37 UTC
Labels: Duplicate
