### ISSUE TITLE
Basket rule / send a gift with other discounts -> wrong amount

### ISSUE THREAD

**Issue by rricci34** [PrestaShop/PrestaShop#19900] opened 2020-06-22 17:12 UTC
I noticed a bug on a PS 1.7.6.5 (so blank test).

When creating a basket rule of the type "send a gift" (therefore a product) from a minimum order amount, the reduction amount becomes incorrect if we add a second (or more) basket rule an amount. However, the amount of the reduction is correct if it is the only one to be used.

For information :
I created a basket rule which is a gift product that I defined at 10 € (so that the calculations are simplified)
I created a second basket rule which is an amount of € 10 including tax

Here is what is happening: (I am enclosing screenshots that will be more telling)

The 2 basket rules:
![regles-paniers](https://user-images.githubusercontent.com/35037422/85315902-27a1fc00-b4bc-11ea-87ea-f50dbf9563bf.jpg)

If 1 rule amount of reduction OK
![1-regle-montant-ok](https://user-images.githubusercontent.com/35037422/85315944-35f01800-b4bc-11ea-8dbf-6d9d74ba4813.jpg)

But when I add a second rule the amount becomes wrong (besides I do not understand the latter which is not proportional to the amount of the reduction (after several tests):
![montant-reduction-erronee](https://user-images.githubusercontent.com/35037422/85315983-43a59d80-b4bc-11ea-8c64-cd7f93ce1319.jpg)a

**Comment by sarahdib** [comment] 2020-06-23 08:40
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.
<img width="1174" alt="Capture d’écran 2020-06-23 à 10 38 42" src="https://user-images.githubusercontent.com/3034677/85380939-c9b5f880-b53d-11ea-9fcd-6292ef437077.png">

What is your php version ? 
Could you send me a screenshot of the two cart rule created

Thank you!

**Comment by rricci34** [comment] 2020-06-23 08:57
Hello, is one of your discounts a gift product? (Pull imprimé colibris  for example) which is added automatically from a certain amount?
The 2nd reduction is a simple amount.
I enclose the screenshots.

1st rule which is a gift:
![2020-06-23_10h48_24](https://user-images.githubusercontent.com/35037422/85383250-0b47a300-b540-11ea-8da1-0cb322d9364c.jpg)
![2020-06-23_10h48_42](https://user-images.githubusercontent.com/35037422/85383273-113d8400-b540-11ea-8939-0cbc89324852.jpg)
![2020-06-23_10h49_16](https://user-images.githubusercontent.com/35037422/85383291-14d10b00-b540-11ea-83ed-6ed5fd695e92.jpg)

2nd rule which is an amount : 

![2020-06-23_10h47_25](https://user-images.githubusercontent.com/35037422/85383349-24505400-b540-11ea-9bfc-3f1356a372f9.jpg)
![2020-06-23_10h47_35](https://user-images.githubusercontent.com/35037422/85383360-274b4480-b540-11ea-9974-5d1563dcbb9e.jpg)
![2020-06-23_10h47_47](https://user-images.githubusercontent.com/35037422/85383375-29ad9e80-b540-11ea-9abc-d268a6dc6529.jpg)

I just did a new test look at the amount of the reduction is not good:
![panier-06-23](https://user-images.githubusercontent.com/35037422/85383473-4649d680-b540-11ea-8e09-625eecd07fbb.jpg)

I use for information PHP 7.2

**Comment by prestascott** [comment] 2020-06-24 12:31
Hello, i tried to reproduce the bug with the exact same rules that you created and unfortunately, i can't reproduce it:
- Free gift discount can't be applied because there is no code written in informations tab even if you don't normally have to write one for your case

When i enter a name of the code, here is what happen:
- 1st rule (free gift discount): it adds the same item but for free -> but you have to enter the code in your cart (FO)
- 2nd rule: 10€ discount -> works perfectly

Here is a screenshot:
![image](https://user-images.githubusercontent.com/54888056/85555961-b16dd880-b626-11ea-9421-982172abb60e.png)

**Comment by rricci34** [comment] 2020-06-24 12:59
Hello, this is crazy. I have this bug on a production site and also on this prestashop 1.7.6.5 in a blank room.

I am attaching a video that may be more meaningful and may allow you to see what is missing ...
TY

[20-06-24_bug-gift.zip](https://github.com/PrestaShop/PrestaShop/files/4825490/20-06-24_bug-gift.zip)

**Comment by prestascott** [comment] 2020-06-24 15:47
Do you have specific discounts on your product page?

Can you provide us screenshots about your product page configuration:
_Catalog > Products > Product page_
- Basic settings
- Quantities
- Shipping
- Pricing
- Options

**Comment by rricci34** [comment] 2020-06-25 07:12
Hello, however, I have not changed anything in the basic configuration of this new installation of PS 1.7.6.5. I leave everything by default, without additional module in order to precisely carry out my tests ...

**Comment by rricci34** [comment] 2020-06-25 07:29
I just did a test on 1.7.7 (beta) and it works correctly.
Do you test on PS 1.7.6.5?
Thank you

**Comment by rricci34** [comment] 2020-06-25 08:08
Well, I just did new tests on a fresh 1.7.6.5, and I no longer have this bug. I do not know why but the main thing is that he is no longer there.

Sorry for the delay :/

**Comment by prestascott** [comment] 2020-06-25 08:50
I'm glad that it works! 

Since you no longer have this bug, i can close this issue.

**Closed as completed** 2020-06-25 08:51 UTC
Labels: BO, Cart rules, No change required, 1.7.6.5
