### ISSUE TITLE
Email address in uppercase

### ISSUE THREAD

**Issue by rblaurin** [PrestaShop/PrestaShop#13386] opened 2019-04-12 12:55 UTC
**Describe the bug**
When a customer register his/her email address in uppercase, the confirmation email doesn't work as expected.

**To Reproduce**
1. Create a new account in front office, entering your email address in uppercase (i.e. KHOULOUDBELGHITH@PRESTASHOP.COM)
2. Go to your inbox and see the confirmation email. You will see something like HELLO {FIRSTNAME} {LASTNAME}

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-04-12 13:35
Hi @rblaurin,

I manage to reproduce the issue with PS:1.7.5.1 and PS:1.7.5.0
I attached a screenshot.
![1386](https://user-images.githubusercontent.com/16067358/56041232-290c5c00-5d30-11e9-99b1-0f14aab3459c.png)

With PS:1.7.4.4=>OK
This issue is added to our bug roadmap.

Thanks!

**Comment by marionf** [comment] 2019-04-12 15:06
It's also visible on 1.7.6.0 with new email templates

![capture d'écran_1382](https://user-images.githubusercontent.com/13449658/56047255-51eb1c00-5d45-11e9-90e7-d5cc4b7d6704.png)

**Comment by colinegin** [comment] 2019-10-14 08:14
Hello @khouloudbelguith ,

do you still reproduce this issue ? Is it related to #15889 ?

Thanks !

**Comment by khouloudbelguith** [comment] 2019-10-14 08:56
Hi @colinegin,

Yes, I manage to reproduce the issue with PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/66739468-0c80e600-ee71-11e9-9cb2-b869f75ddf9e.png)

No, it is different from https://github.com/PrestaShop/PrestaShop/issues/15889, because, this issue occurs in the emails & the other issue is about editing an email from the BO.

Thanks!

**Comment by GLSSoftware** [comment] 2019-11-01 19:29
I can confirm this bug with 1.7.6.1. 
To reproduce this behaviour it is suffucient that the mail addess starts with an uppercase e.g. "Volker.Mustermann@example.de". In Germany customers enter their email address very often using uppercase letters. This bug shows up in our live shop almost every week to at least one customer. Because of that the bug should not be marked as 'minor'.

**Comment by Allba** [comment] 2019-11-18 08:01
It have been several months now and still not a fix on a serious issue. This prestashop thing starts to sound like a joke, very disappointed.

**Comment by seisnet** [comment] 2019-11-25 10:35
i made this fix on classes/Mail.php and it works
row 318 from `$toPlugin = $to[0];` to `$toPlugin = self::toPunycode($to[0]);`
row 321 from `$toPlugin = $to;` to `$toPlugin = self::toPunycode($to);`

**Comment by colinegin** [comment] 2019-11-25 10:38
Hello @seisnet ,

thanks for this information, would you be willing to make a pull request with your fix ? 

Have a nice day,

Coline

**Comment by seisnet** [comment] 2019-11-25 10:40
No, i am not wiling sorry

**Comment by colinegin** [comment] 2019-11-25 15:52
Hello @seisnet ,

Thanks for your reply, is there any reason why you are not willing to do so ? Maybe we could help you ?

**Comment by seisnet** [comment] 2019-11-25 16:06
i have no time to do this. Sorry

**Comment by seisnet** [comment] 2019-11-27 13:32
> i made this fix on classes/Mail.php and it works
> row 318 from `$toPlugin = $to[0];` to `$toPlugin = self::toPunycode($to[0]);`
> row 321 from `$toPlugin = $to;` to `$toPlugin = self::toPunycode($to);`

i correct my solution. I pasted it wrong

**Closed as completed** 2019-11-27 13:37 UTC
Labels: Bug, Minor, Email, Regression, Fixed, 1.7.5.0, 1.7.5.1, 1.7.6.0, PR available

**Comment by skillfulconcept** [comment] 2020-04-07 11:00
Team, this issue has not been resolved in Prestashop 1.7.6.4. Please reopen this ticket

**Comment by khouloudbelguith** [comment] 2020-04-07 11:03
Hi @skillfulconcept 
This issue is fixed in the next major version PS1.7.7.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16550 to fix the issue.

Thanks!

**Comment by surffari** [comment] 2020-05-07 18:03
Yes, can confirm it's an issue in 1.7.6.4

**Comment by alessiomediacy** [comment] 2020-10-28 14:24
Hi, confirm issue in 1.7.6.7

**Comment by khouloudbelguith** [comment] 2020-10-28 14:31
Hi @surffari, @alessiomediacy,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16550 to fix the issue.
It is fixed in the next release PS1770.

Thanks!

**Comment by Betafer** [comment] 2021-02-10 14:34
Problem also present in prestashop 1.7.6.8 with php 7.2.34

<img width="607" alt="Schermata 2021-02-10 alle 15 33 30" src="https://user-images.githubusercontent.com/5024055/107523767-61dc1d00-6bb5-11eb-94e5-53f0de3fd517.png">

**Comment by ayushshrestha** [comment] 2024-05-15 07:00
Anyone here who can solve Problems?

While user/customer register and admin get emails,  In email Admin need Country Name, City and Gender too.
How can i solve this issue ?
