### ISSUE TITLE
Can't access Module Manager

### ISSUE THREAD

**Issue by gagah666** [PrestaShop/PrestaShop#15992] opened 2019-10-17 03:10 UTC
**Describe the bug**
Can't even access module manager for a while, not sure what went wrong

**To Reproduce**
Whenever i click on module manager, always appear like this

**Additional information**
PrestaShop version: 1.7

![Presta 1](https://user-images.githubusercontent.com/56664362/66974641-f1f37a80-f0c5-11e9-869c-b60a080914f5.JPG)

**Comment by khouloudbelguith** [comment] 2019-10-17 07:55
Hi @gagah666,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-18 07:36
Hi @gagah666,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

thanks!

**Closed as completed by khouloudbelguith** 2019-11-18 07:36 UTC
Labels: Bug, BO, No change required, Module manager
