### ISSUE TITLE
Modulo Analytics Prestashop

### ISSUE THREAD

**Issue by GiulioJulao** [PrestaShop/PrestaShop#31852] opened 2023-03-20 15:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

using the google analytics module in analytics the steps of the purchase process do not appear.
<img width="1153" alt="analytics" src="https://user-images.githubusercontent.com/128402173/226393194-92516f1d-86e4-4fa4-8c6f-8b2838e005e3.png">

### Expected behavior

I expected to see the purchase steps

### Steps to reproduce

go to analytics, 
convertion
ecommerce
buying behavior

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Google Analytics

**Comment by florine2623** [comment] 2023-03-24 09:33
Hello @GiulioJulao ,

What version of the module are you using ?

**Comment by GiulioJulao** [comment] 2023-03-24 10:09
Hi @florine2623 the version module is v4.2.1

**Comment by hibatallahAouadni** [comment] 2023-03-27 14:05
Hello @GiulioJulao 

Could you please provide clear and concise steps to reproduce the issue 🙏 
Waiting for your feedback. 

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-04-12 11:14
Hello @GiulioJulao 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-04-12 11:14 UTC
Labels: Bug, BO, Google Analytics, Invalid, Module, 1.7.8.7
