### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by BoutiquesInternet** [PrestaShop/PrestaShop#31345] opened 2023-02-14 10:15 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I recently upgraded my Prestashop 1.7.6.4 to 1.7.8.8.
And since this upgrade, after a certain amount of time, the back office show this error page.

![Capture d’écran 2023-02-08 à 18 47 22](https://user-images.githubusercontent.com/36631714/218704668-b8271fb1-4e97-4c59-a206-3d937fc39d67.png)

My host : IONOS
My config

![image](https://user-images.githubusercontent.com/36631714/218706024-a2317390-f86d-4a23-ab2b-c052026b5861.png)

### Steps to reproduce

1 Upgrade Prestashop 1.7.6.4 to 1.7.8.8
2 Wait few hours and get the error page

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3.27

**Comment by hibatallahAouadni** [comment] 2023-02-14 20:44
Hello @BoutiquesInternet 

Did you try to check this option before login? 

![image](https://user-images.githubusercontent.com/23308427/218858927-6a7bcb89-a801-4dc9-8719-df11b56dbf25.png)

Please check and feedback.

Thanks!

**Comment by BoutiquesInternet** [comment] 2023-02-15 09:04
Hi,

Yes I tried.
Is this a normal alert or a bug ?

**Comment by hibatallahAouadni** [comment] 2023-02-16 01:00
Hello @BoutiquesInternet 

Well, it's not a bug if the "after a certain amount of time" is a day for exemple or more than 12 hours.
This alert means that the Token has been expired 😉 
Closing the issue as it's not Core bug.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-02-16 01:00 UTC
Labels: Bug, BO, Invalid, Login, 1.7.8.8
