### ISSUE TITLE
Cannot enter BO->SEO & URLs  when multishopfeature is on

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#20464] opened 2020-08-05 09:41 UTC
#### Describe the bug

When multishop feature is on, trying to enter `admin-dev/configure/shop/seo-urls` ends up with error (screenshot1). This is caused because (technically) form has inputs only when following if statement is true `if (!$this->isHostMode && !$this->isShopFeatureActive && $this->doesMainShopUrlExist)`. You can see it in code ShopUrlType.php::74. (and screenshot2)
#### Expected behavior

Expect to see working page with SEO configuration forms etc.. I am not aware why shouldn't those inputs exist when multishop is on, there might be a reason for that. Anyway it must be decided if it can be shown and/or what should be shown instead if those inputs are missing.

#### Steps to Reproduce

1. Enable multistore
2. Go Configure -> Shop parameters -> Traffic & SEO
3. See the error

**Screenshots**

1.![Screenshot from 2020-08-05 12-32-17](https://user-images.githubusercontent.com/31609858/89396852-c191d100-d717-11ea-8942-48b8e16a57bc.png)
2.![Screenshot from 2020-08-05 12-38-05](https://user-images.githubusercontent.com/31609858/89397496-978cde80-d718-11ea-8359-7200e2dda506.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-08-05 10:07
Hi @zuk3975,

Same issue with develop branch.
![image](https://user-images.githubusercontent.com/16067358/89400409-264b2c80-d714-11ea-9e7e-4634c4d90b79.png)

I’ll add this to the debug roadmap.

Thanks!

**Comment by marionf** [comment] 2020-10-26 10:22
Duplicate of #20863

**Closed as completed by marionf** 2020-10-26 10:22 UTC
Labels: Bug, Major, BO, Duplicate, Multistore, SEO & URLs
