### ISSUE TITLE
New product page. Added product image don't display on FO, error in console 

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29065] opened 2022-07-13 11:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Screenshot from 2022-07-13 10-56-51](https://user-images.githubusercontent.com/90208051/178724127-1521b72c-0f04-4951-bbed-b91100c396a5.png)
![Screenshot from 2022-07-13 13-46-46](https://user-images.githubusercontent.com/90208051/178726506-7c6f0177-a643-4044-a385-6b5385ac8073.png)

Product image don't display on FO if this product was created with  "New product page"  
To display the image, I need to disable this option, see video: 

https://user-images.githubusercontent.com/90208051/178725318-963df00a-0ae4-4e9d-8047-5ec40e681709.mp4

### Expected behavior

Image displaying with all options for adding a product

### Steps to reproduce

1. Open New & Experimental Features page and enable "New product page - Single store"
2. Open Products page and click New product button
3. Add some name for product and add some image > Save
4. Check product page on FO

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2022-07-13 12:10
Hello @szavadskiy ,

I can't reproduce your issue with product page V2. The image is well displayed in BO and FO.

https://user-images.githubusercontent.com/16019289/178729964-ad0dc558-ff4b-4f05-a84f-c7781aa5f072.mov

Is there any specific config to your product or product settings ?
Thanks!

**Comment by szavadskiy** [comment] 2022-07-26 09:30
Hello @florine2623 that worries me, I haven't any specific config. I just now reinstall an environment and issue reproduced

**Comment by florine2623** [comment] 2022-07-26 12:01
Hi @szavadskiy ,

I have reproduced your issue on `develop` branch!  I'll add this to the backlog so it can be fixed.
On 8.0.x and 1.7.8.x it is OK.
<img width="1207" alt="Screenshot 2022-07-26 at 13 55 45" src="https://user-images.githubusercontent.com/16019289/181000180-9d6b7de5-24c2-425d-942f-2afab540adc3.png">
<img width="927" alt="Screenshot 2022-07-26 at 13 55 50" src="https://user-images.githubusercontent.com/16019289/181000190-7ec5c0df-ded0-4529-a28d-b1a768302868.png">

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by khouloudbelguith** [comment] 2022-07-26 13:48
Hi @florine2623, @szavadskiy,

I think this issue is duplicated of this issue: https://github.com/PrestaShop/PrestaShop/issues/28338.
What do you think?

Thanks!

**Comment by florine2623** [comment] 2022-07-27 08:00
Thanks @khouloudbelguith ,

It is indeed a duplicate ^^
I close this one !

**Comment by florine2623** [comment] 2022-07-27 08:00
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28338.

**Closed as not planned** 2022-07-27 09:35 UTC
Labels: Bug, 8.0.x, FO, Duplicate, Regression, Front-end, Invalid
