### ISSUE TITLE
With default Prestashop's modules it is not possible to translate the text of override tpl files

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#27655] opened 2022-02-12 14:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
with the translation system, like the one that handles translations for the module ps_wirepayment, if I want to change the html structure of ps_wirepayment_intro.tpl the new texts are not present in the translation page from back-office and the new texts remains in english.

bye

### Expected behavior

I need to see the new texts present in the override file, set in the theme folder, like for the theme translations.
if not it is not possible to override default module tpl in the theme

thanks

### Steps to reproduce

1) add to the classic theme in the modules folder, the folder attached here
2) then go to the translation page from the admin, and search about the new texts present in the override file

[ps_wirepayment.zip](https://github.com/PrestaShop/PrestaShop/files/8053642/ps_wirepayment.zip)

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_wirepayment v2.1.1

**Comment by hibatallahAouadni** [comment] 2022-02-14 12:51
Hello @maofree 

We are aware of this issue and unfortunately it will not be fixed. This issue is a duplicate of #17844. 
Please check this [comment](https://github.com/PrestaShop/PrestaShop/issues/17844#issuecomment-690957794), it may help you :pray: 

Thanks for your understanding :pray:

**Comment by hibatallahAouadni** [comment] 2022-02-14 12:51
Duplicate of #17844

**Closed as completed by hibatallahAouadni** 2022-02-14 12:51 UTC
Labels: Bug, Duplicate, Invalid
