### ISSUE TITLE
Multiple orders created for exclusive carriers

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#23084] opened 2021-02-01 17:33 UTC
#### Describe the bug

When having products with exclusive carriers (some products not shipped to some countries), Prestashop splits the order in two, making one of them without a carrier and a 0 shipping cost.

#### Expected behavior

Prestashop should not allow to place an order when a selected product can't be shipped to customer's country.

#### Steps to Reproduce

1. Create a carrier that ships only to some area (like Europe), and another carrier that ships to some other area (like Europe Non EU)
2. Create a product that has only the first carrier assigned and another product that has only the second carrier assigned. 
3. Put both products in the cart and proceed to the checkout, select some country (France for example).
4. See error - shipping cost is there and the order can be placed for both products, while one of them  is not available for shipping to France.

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-02-02 11:11
Hello @daresh 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9594. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-02 11:11
Duplicate of #9594

**Closed as completed by hibatallahAouadni** 2021-02-02 11:11 UTC
Labels: Duplicate
