### ISSUE TITLE
Getting timeout error when generate sitemap for huge web site 

### ISSUE THREAD

**Issue by acbr5** [PrestaShop/PrestaShop#32625] opened 2023-05-19 08:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am getting timeout error when trying to generate sitemap for huge web site (13K+ products).

### Expected behavior

When creating sitemap files, it is expected that a new sitemap file will be created and added to the index sitemap file  in the same time after the file size exceeds 3 MB .

### Steps to reproduce

1. Go to Admin Panel
2. Configure the Gsitemap module
3. Press create Sitemap button
4. You get the error after waiting for a short time

### PrestaShop version(s) where the bug happened

1.7.4.4

### PHP version(s) where the bug happened

7.4.3

**Comment by jlores** [comment] 2023-05-19 10:44
I hadn't noticed this, but with the gsitemap 4.3.0 module it happens

**Comment by AureRita** [comment] 2023-05-19 15:40
Hi @acbr5 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ May 19, 2023 5_38 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/aee11db5-c163-4ff3-aa5f-89152d8288b0)

But currently I can't, did I miss something ? 

Wich checkboxes did you check ? 

Waiting for your feedback

**Comment by jlores** [comment] 2023-05-19 15:50
Hello

In case it helps. The problem is that when done on remote hosting, it's not as instant as video, and it times out. clicking again adds to the end of the sitemap instead of creating a new one and increases the size of the file

I try on 8.0.4 and the error is the same.

**Comment by florine2623** [comment] 2023-06-07 15:37
Hello @acbr5 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-06-07 15:37 UTC
Labels: Bug, BO, Google sitemap, Invalid, Module
