### ISSUE TITLE
500 error on debug mode activation

### ISSUE THREAD

**Issue by tiroiretcoton** [PrestaShop/PrestaShop#29271] opened 2022-08-07 21:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I have a problem while activating the debug mode.
Indeed when i click the save button, i have a 500 error.
is it possible for you to check the logs of prestashop for my prestashop page ?

I need to understand what is going on when i click on the debug button.

Here is what i do on my page :

Opening of the screen of the performances to activate the debug mode :
![image](https://user-images.githubusercontent.com/105629313/179773290-791a2e9a-e9eb-4ef0-afff-9f5eebe53455.png)

Clic on the yes button of the debog property :
![image](https://user-images.githubusercontent.com/105629313/179773430-bce12cf0-551a-4f01-8996-b49961c55445.png)

Clic on the save button => 500 error
![image](https://user-images.githubusercontent.com/105629313/179773475-da5acfcb-0dc2-4a21-889d-8d6dd6e8a5b6.png)

Johan

### Expected behavior

The debug mode is activated and no error happens.

### Steps to reproduce

Here is what i do on my page :

Opening of the screen of the performances to activate the debug mode :
![image](https://user-images.githubusercontent.com/105629313/179773290-791a2e9a-e9eb-4ef0-afff-9f5eebe53455.png)

Clic on the yes button of the debog property :
![image](https://user-images.githubusercontent.com/105629313/179773430-bce12cf0-551a-4f01-8996-b49961c55445.png)

Clic on the save button => 500 error
![image](https://user-images.githubusercontent.com/105629313/179773475-da5acfcb-0dc2-4a21-889d-8d6dd6e8a5b6.png)

### PrestaShop version(s) where the bug happened

1.7.5.1

**Comment by hibatallahAouadni** [comment] 2022-08-08 08:28
Hello @tiroiretcoton 

As you can see this [comment](https://github.com/PrestaShop/PrestaShop/issues/12977#issuecomment-475289655), we were not able to reproduce the issue.

Closing the issue as we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Closed as completed by hibatallahAouadni** 2022-08-08 08:28 UTC
Labels: Bug, Invalid

**Comment by tiroiretcoton** [comment] 2022-08-08 18:47
I dont need you to reproduce the problem.

I need the technical logs of my prestashop account to understand what is the problem.

I will open a new ticket.

Thanks Johan
