### ISSUE TITLE
Cannot change between client adresses

### ISSUE THREAD

**Issue by jajarom** [PrestaShop/PrestaShop#20344] opened 2020-07-24 21:27 UTC
#### Describe the bug

Old bug, i want to fix it now. 
I can't switch between customer addresses

#### Expected behavior

No errors

#### Steps to Reproduce

1. Go to 'Any client'
2. Select another adress
3. Click change adress

Proprietatea OrderCarrier->id_order este goala.
at line 1003 in file classes/ObjectModel.php

998.             }
999. 
1000.             $message = $this->validateField($field, $this->$field);
1001.             if ($message !== true) {
1002.                 if ($die) {
1003.                     throw new PrestaShopException($message);
1004.                 }
1005. 
1006.                 return $error_return ? $message : false;
1007.             }
1008.         }

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by jajarom** [comment] 2020-07-24 21:48
![error-adress](https://user-images.githubusercontent.com/5030991/88438111-943c4d80-ce10-11ea-98df-0cbf83ec21e5.jpg)

**Comment by rdy4ever** [comment] 2020-07-25 15:18
Hi @jajarom 
My guess is the problem is in the overriden file `override/classes/Dispatcher.php`
Try to disable that override (and maybe the module that created this override) and see if the problem persists.

**Comment by khouloudbelguith** [comment] 2020-07-27 09:21
Hi @jajarom,

I did not manage to reproduce the issue with PS1.7.6.7.
If it is a virtual product, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17804 to fix the issue.
It is fixed in the new newt release PS1.7.7.0.

As commented by @rdy4ever, you have an override, this is the problem.
If this override is created by a custom module, you should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Closed as completed by khouloudbelguith** 2020-07-27 09:21 UTC
Labels: BO, Addresses, No change required
