### ISSUE TITLE
Languages webservice

### ISSUE THREAD

**Issue by sergiobm3** [PrestaShop/PrestaShop#25400] opened 2021-07-22 10:15 UTC
#### Describe the bug

If I add resources like product_option, product_option_values, product_features, product_feature_values sme adds the translation of the main language but when I update the Product resource the translations of the missing languages are not added, why? .

#### Expected behavior

In the products, the translations of the missing languages should also be added to the translation of the main language.

#### Steps to Reproduce

1. Have two different languages on PrestaSHop.

using web service :
2. Add an element to the product_feature resource with just one translation.
3. Check that the translation of the other language has been generated with the data of principal lenguage.
4. Add an element to the Product resource with just one translation.
5. Check that no translations have been generated.

**Request POST Product_feature** 

```
<?xml version="1.0" encoding="utf-8"?><prestashop>
<product_feature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <id>505</id>
  <position>504</position>
  <name>
    <language id="1">Soft</language>
    <language id="12">Metal</language>
  </name>
</product_feature></prestashop>
```

**Response** 
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
	<product_feature>
		<id><![CDATA[505]]></id>
		<position><![CDATA[504]]></position>
		<name>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[Soft]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2">
				<![CDATA[Soft]]>
			</language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"><![CDATA[Soft]]></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"><![CDATA[Soft]]></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"><![CDATA[Soft]]></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"><![CDATA[Soft]]></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"><![CDATA[Soft]]></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"><![CDATA[Soft]]></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"><![CDATA[Soft]]></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"><![CDATA[Soft]]></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"><![CDATA[Soft]]></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[Metal]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"><![CDATA[Soft]]></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"><![CDATA[Soft]]></language>
		</name>
	</product_feature>
</prestashop>
```

**Request POST Product**
```
<?xml version="1.0" encoding="utf-8"?><prestashop>
<product xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <meta_description>
    <language id="1">Tasty Concrete Pizza</language>
    <language id="12">Fantastic Concrete Cheese</language>
  </meta_description>
  <meta_keywords>
    <language id="1">payment; generating</language>
    <language id="12">Stream; data-warehouse</language>
  </meta_keywords>
  <meta_title>
    <language id="1">Rustic Metal Computer</language>
    <language id="12">Ergonomic Metal Soap</language>
  </meta_title>
  <link_rewrite>
    <language id="1">rustic-metal-computer</language>
    <language id="12">ergonomic-metal-soap</language>
  </link_rewrite>
  <name>
    <language id="1">Rustic Metal Computer</language>
    <language id="12">Ergonomic Metal Soap</language>
  </name>
  <description>
    <language id="1">Tasty Concrete Pizza</language>
    <language id="12">Fantastic Concrete Cheese</language>
  </description>
  <description_short>
    <language id="1">Tasty Concrete Pizza</language>
    <language id="12">Fantastic Concrete Cheese</language>
  </description_short>
  
</product></prestashop>
```

**Response**

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
	<product>
		<meta_description>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[Tasty Concrete Pizza]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2"></language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[Fantastic Concrete Cheese]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"></language>
		</meta_description>
		<meta_keywords>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[payment; generating]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2"></language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[Stream; data-warehouse]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"></language>
		</meta_keywords>
		<meta_title>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[Rustic Metal Computer]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2"></language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[Ergonomic Metal Soap]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"></language>
		</meta_title>
		<link_rewrite>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[rustic-metal-computer]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2"></language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[ergonomic-metal-soap]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"></language>
		</link_rewrite>
		<name>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[Rustic Metal Computer]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2"></language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[Ergonomic Metal Soap]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"></language>
		</name>
		<description>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[Tasty Concrete Pizza]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2"></language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[Fantastic Concrete Cheese]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"></language>
		</description>
		<description_short>
			<language id="1" xlink:href="http://localhost/prestashop/api/languages/1"><![CDATA[Tasty Concrete Pizza]]></language>
			<language id="2" xlink:href="http://localhost/prestashop/api/languages/2"></language>
			<language id="3" xlink:href="http://localhost/prestashop/api/languages/3"></language>
			<language id="4" xlink:href="http://localhost/prestashop/api/languages/4"></language>
			<language id="5" xlink:href="http://localhost/prestashop/api/languages/5"></language>
			<language id="6" xlink:href="http://localhost/prestashop/api/languages/6"></language>
			<language id="7" xlink:href="http://localhost/prestashop/api/languages/7"></language>
			<language id="8" xlink:href="http://localhost/prestashop/api/languages/8"></language>
			<language id="9" xlink:href="http://localhost/prestashop/api/languages/9"></language>
			<language id="10" xlink:href="http://localhost/prestashop/api/languages/10"></language>
			<language id="11" xlink:href="http://localhost/prestashop/api/languages/11"></language>
			<language id="12" xlink:href="http://localhost/prestashop/api/languages/12"><![CDATA[Fantastic Concrete Cheese]]></language>
			<language id="13" xlink:href="http://localhost/prestashop/api/languages/13"></language>
			<language id="14" xlink:href="http://localhost/prestashop/api/languages/14"></language>
		</description_short>
	</product>
</prestashop>

```
#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.2.33

**Comment by florine2623** [comment] 2021-07-22 10:25
Hello @sergiobm3 ,

Could you share the exact steps to reproduce the issue please ?

Thanks!

**Comment by sergiobm3** [comment] 2021-07-22 11:28
1. Have two different languages on PrestaSHop.

using web service :
2. Add an element to the product_feature resource with just one translation.
3. Check that the translation of the other language has been generated with the data of principal lenguage.
4. Add an element to the Product resource with just one translation.
5. Check that no translations have been generated.

**Comment by khouloudbelguith** [comment] 2022-04-14 14:58
Hi @sergiobm3,

Thanks for your report.
I tried with PS1785, I have the same result when adding product_feature & product via API
I used this script to add a `product_feature`
```xml
<prestashop>
	<product_feature>
		<position>3</position>
		<name required="true">
			<language id="1" xlink:href="http://test.tn/1785/api/languages/1">english</language>
		</name>
	</product_feature>
</prestashop>
```
I have this response
```xml
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <product_feature>
        <id>
            <![CDATA[5]]>
        </id>
        <position>
            <![CDATA[3]]>
        </position>
        <name>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[english]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </name>
    </product_feature>
</prestashop>
```

I tried to use this script to add a `product` via API
```xml
<prestashop>
<product xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <meta_description>
    <language id="1">Tasty Concrete Pizza</language>
  </meta_description>
  <meta_keywords>
    <language id="1">payment; generating</language>
  </meta_keywords>
  <meta_title>
    <language id="1">Rustic Metal Computer</language>
  </meta_title>
  <link_rewrite>
    <language id="1">rustic-metal-computer</language>
  </link_rewrite>
  <name>
    <language id="1">Rustic Metal Computer</language>
  </name>
  <description>
    <language id="1">Tasty Concrete Pizza</language>
  </description>
  <description_short>
    <language id="1">Tasty Concrete Pizza</language>
  </description_short>
  <price>10</price>
</product>
</prestashop>
```

I have this response
```xml
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <product>
        <id>
            <![CDATA[26]]>
        </id>
        <delivery_in_stock>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </delivery_in_stock>
        <delivery_out_stock>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </delivery_out_stock>
        <product_type>
            <![CDATA[]]>
        </product_type>
        <on_sale>
            <![CDATA[]]>
        </on_sale>
        <online_only>
            <![CDATA[]]>
        </online_only>
        <ecotax>
            <![CDATA[]]>
        </ecotax>
        <minimal_quantity>
            <![CDATA[]]>
        </minimal_quantity>
        <low_stock_threshold>
            <![CDATA[]]>
        </low_stock_threshold>
        <low_stock_alert>
            <![CDATA[]]>
        </low_stock_alert>
        <price>
            <![CDATA[10]]>
        </price>
        <wholesale_price>
            <![CDATA[]]>
        </wholesale_price>
        <unity>
            <![CDATA[]]>
        </unity>
        <unit_price_ratio>
            <![CDATA[]]>
        </unit_price_ratio>
        <additional_shipping_cost>
            <![CDATA[]]>
        </additional_shipping_cost>
        <customizable>
            <![CDATA[]]>
        </customizable>
        <text_fields>
            <![CDATA[]]>
        </text_fields>
        <uploadable_files>
            <![CDATA[]]>
        </uploadable_files>
        <active>
            <![CDATA[]]>
        </active>
        <redirect_type>
            <![CDATA[]]>
        </redirect_type>
        <id_type_redirected>
            <![CDATA[]]>
        </id_type_redirected>
        <available_for_order>
            <![CDATA[]]>
        </available_for_order>
        <available_date>
            <![CDATA[]]>
        </available_date>
        <show_condition>
            <![CDATA[]]>
        </show_condition>
        <condition>
            <![CDATA[new]]>
        </condition>
        <show_price>
            <![CDATA[]]>
        </show_price>
        <indexed>
            <![CDATA[]]>
        </indexed>
        <visibility>
            <![CDATA[both]]>
        </visibility>
        <advanced_stock_management>
            <![CDATA[]]>
        </advanced_stock_management>
        <date_add>
            <![CDATA[2022-04-14 16:50:51]]>
        </date_add>
        <date_upd>
            <![CDATA[2022-04-14 16:50:51]]>
        </date_upd>
        <pack_stock_type>
            <![CDATA[]]>
        </pack_stock_type>
        <meta_description>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[Tasty Concrete Pizza]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </meta_description>
        <meta_keywords>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[payment; generating]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </meta_keywords>
        <meta_title>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[Rustic Metal Computer]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </meta_title>
        <link_rewrite>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[rustic-metal-computer]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </link_rewrite>
        <name>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[Rustic Metal Computer]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </name>
        <description>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[Tasty Concrete Pizza]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </description>
        <description_short>
            <language id="1" xlink:href="http://test.tn/1785/api/languages/1">
                <![CDATA[Tasty Concrete Pizza]]>
            </language>
            <language id="2" xlink:href="http://test.tn/1785/api/languages/2">
                <![CDATA[]]>
            </language>
        </description_short>
        <available_now>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </available_now>
        <available_later>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </available_later>
        <associations>
            <categories nodeType="category" api="categories"/>
            <images nodeType="image" api="images"/>
            <combinations nodeType="combination" api="combinations"/>
            <product_option_values nodeType="product_option_value" api="product_option_values"/>
            <product_features nodeType="product_feature" api="product_features"/>
            <tags nodeType="tag" api="tags"/>
            <stock_availables nodeType="stock_available" api="stock_availables">
                <stock_available xlink:href="http://test.tn/1785/api/stock_availables/134">
                    <id>
                        <![CDATA[134]]>
                    </id>
                    <id_product_attribute>
                        <![CDATA[0]]>
                    </id_product_attribute>
                </stock_available>
            </stock_availables>
            <attachments nodeType="attachment" api="attachments"/>
            <accessories nodeType="product" api="products"/>
            <product_bundle nodeType="product" api="products"/>
        </associations>
    </product>
</prestashop>
```

I attached a screen record

https://user-images.githubusercontent.com/16067358/163417459-5a4e7ed3-667a-4334-b11d-076b382a1936.mp4

Thanks to check and feedback

**Comment by florine2623** [comment] 2022-05-03 12:06
Hello @sergiobm3 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2022-05-03 12:06 UTC
Labels: Bug, WS, Translations, Webservice, Languages, 1.7.7.5, Invalid
