### ISSUE TITLE
Adding payment with comma does not work anymore PS 1.7.7.x

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#24103] opened 2021-04-18 17:44 UTC
### Describe the bug

From PS 1.7.7.x and up it is not more possible to add a payment with a "," (comma) in the amount, for example: 20,90 €
This is not very usefull for german Prestashop users. 

### Expected behavior

It's possible to add a payment with a "," (comma) in the amount

Adds a type class that governs the numeric type fields, checks that the expected format.

**specs**

The numeric type fields can accept the different number formats and convert it to the format managed by the PS system directly in the field. All non-numeric characters are ignored, except for the last one which is converted to a decimal point symbol.
If a non-numeric character is used twice, and it's the only one that is used, consider this character is a thousand separator.

**When the user unfocuses (blurs) the field, PS will convert the field following the rules describes above.**
 
1.000,2 => 1000.2
1N000,2 => 1000.2
100,2 -> 100.2
1,000,2 -> 10002
100,002 -> 100.002

List of the inputs in the BO:

_Order View_

* Amont in the tab payment
* Add a product (tax inclus and exclu) 
* Edit a product (tax inclus and exclu) 
* Add a discount (percentage and amount)

_Add Order_

* Add a discount
* Add a product

_Product page_

* Basic Tab: price TTC and HT

  _Combinaisons_

* Impact on price on the list 

  _Bulkaction_

* Cost price
* Impact on price (tax incl)
* Impact on price (tax excl)

_Shipping_

* Shipping fee
* Width
* Height
* Depth
* Weight

_Pricing_

* Price (tax excl)
* Price (tax incl)
* Price per unit (tax excl) 
* Cost Price (tax excl)

_Specific Price_

* Product price (tax excl.)
* Apply a discount of

_Discounts_

* Amount (tax incl and excl)
* Percentage

_Carriers_

* Shipping cost Ranges
* Width
* Height
* Depth
* Weight

_Carrier preference_

* Handling charges
* Free shipping starts at

_Taxes_

* Tax rate create & edit

_Order settings_

* Minimum purchase total required in order to validate the order 
* Gift-wrapping price 

#### Steps to Reproduce

1. Go to BO
2. Click on Orders > edit Order with "Awaiting payment" as status
3. Scroll down to **Payment** block and add a payment with comma (for example: 20,90 €)

**Screenshots**

![image](https://user-images.githubusercontent.com/44971218/115155046-522df880-a07e-11eb-863c-a653efc6e30d.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by matks** [comment] 2021-04-19 07:05
Hi @didi-2018 I think you are reporting something very valuable :) but it will not be explored if it does not fit some of our templates
https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md
or
https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=2_feature_request.md

**Comment by hibatallahAouadni** [comment] 2021-04-19 08:05
Hello @didi-2018 

Could you please edit your issue **following the provided template to submit a complete bug report**. Please fill in all the blocks (steps to reproduce, PrestaShop version, PHP version, ...).

Please edit and notify me :wink: 

Thanks!

**Comment by didi-2018** [comment] 2021-04-19 09:09
@hibatallahAouadni 

as I wrote **PS 1.7.7.x and up** (<- Versions) was working until 1.7.6.9 and was removed from 1.7.7.x

**add a payment to an order with a comma in the amount** = 20,90 (<- step to reproduce) 

![image](https://user-images.githubusercontent.com/44971218/115211345-c492ed00-a0ff-11eb-9bb5-eab7f1c60422.png)


What is not clear in that? Let me know, please

**Comment by didi-2018** [comment] 2021-04-19 13:50
same with partial refund. Only "." is allowed and not more ",". Why was this removed with PS 1.7.7.x? I don´t understand that? Germans don´t use a dot in amounts, we use a comma 🤷‍♀️

And shippings cots are not refunded when they are added to the refund, only the item amount. But this I have to check with paypal module.

**Comment by matks** [comment] 2021-04-19 13:56
@didi-2018 Steps to reproduce must follow the structure

```
#### Steps to Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

> Why was this removed with PS 1.7.7.x? I don´t understand that? Germans don´t use a dot in amounts, we use a comma

It was not removed on purpose, this is a side-effect of reworking the Orders page. The previous page probably converted `,` into `.` but as there was no mention of this in any document, the reworking did not include this behavior. This is something that needs to be fixed.

The prices are however displayed correctly, using the comma, I think?

> And shippings cots are not refunded when they are added to the refund, only the item amount. But this I have to check with paypal module.

Same for refunds, there was no document explaining how compute and acknowledge the items of a refund, so it's possible the rework did not include that.

**Comment by hibatallahAouadni** [comment] 2021-04-19 15:26
Hello @didi-2018 

I just edit your issue :wink: 
We ask you to respect this template to help us reproducing the issue ASAP and try to fix it. So, at least help us by following the provided template.

I was able to reproduce the issue with PrestaShop version 1.7.7.3 and develop, so I can confirm that this behavior is indeed a bug. But with PS1.7.6.7, I notice that when we add a payemnt 10,50, it will be successfully added as 10.50.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by didi-2018** [comment] 2021-04-19 18:03
@matks and @hibatallahAouadni  Thank you very much 🙏! I have not expected that is needs more explanation 🙈. 

@hibatallahAouadni  and I edited it again cause you forgot the "not" for **Expected behavior** 😄

**Comment by hibatallahAouadni** [comment] 2021-04-20 10:03
Hello @didi-2018 

Well, the expected behavior supposed to be what do you want (add a payment with comma without any problem) 😉
So, it was correct and I just re-edit it.

Thanks!

**Comment by PierreRambaud** [comment] 2021-04-23 09:29
I put this issue in `Blocked/Need spec` section. I'm waiting for @MatShir 's feedback about what we have to do :)

**Comment by prestaforum** [comment] 2021-04-23 11:57
Hello @didi-2018 @hibatallahAouadni please see https://github.com/PrestaShop/PrestaShop/pull/24179 to fix

**Comment by hibatallahAouadni** [comment] 2021-04-26 09:33
Hello @prestaforum thanks for your PR :rocket:

**Comment by khouloudbelguith** [comment] 2021-07-12 08:32
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24339

**Closed as completed by khouloudbelguith** 2021-07-12 08:32 UTC
Labels: Bug, develop, Minor, BO, Order, Payment, Regression, Fixed, PR available, 1.7.7.x
