### ISSUE TITLE
Order: some articles are not taken into account -> sum is not correct

### ISSUE THREAD

**Issue by sugata94** [PrestaShop/PrestaShop#19263] opened 2020-05-22 09:07 UTC
Host: OVH
Prestashop 1.7.6
Database: MYSQL v.5.6
----------------------------------

Context: 
-----------
Do an order by adding some articles to the cart and pay (whatever the payment).

Expected:
------------
The order's total amount shall be the sum of the articles prices and the transport fees (computed according to the articles weight).

Result:
---------
When paying, not all of the articles are taken into account.
The transport fees are successfully updated according to the remaining considered products.

![Wrong_Sum](https://user-images.githubusercontent.com/12573812/82651406-696d2780-9c1c-11ea-84be-569cfac471f8.png)

**Comment by florine2623** [comment] 2020-05-22 09:20
Hi @sugata94 ,
I can't reproduce your issue.
What are the exact steps to reproduce your issue ?
Thanks!

**Comment by sugata94** [comment] 2020-05-22 09:51
Hi @florine2623 ,

Thanks for the quick answer!
Hereunder I will try to give you more details.

I go on the website: https://passion-sport.org
I do an order as a user (create your own account if needed!):
- Add "Veste - Taille : 170cm- Couleur : Rouge"
- Add "Short Sambo Adulte - Taille : XL (56-58)- Couleur : Rouge"
- Add "Chaussures sambo adulte - Taille : 44"
(Total amount is 109.00€ + transport fees 8.95€ for those 3 article).
- I pay with bank wire.
Note: The same issue can be reproduced when paying by card.

- In the cart, everything is fine: OK.
- In the email received by the customer, everything is fine: OK.
- In the order resume AFTER paying, there are wrong informations: NOK
- In the order in the back-office, there are wrong informations: NOK

Wrong informations:
1) a supplementary article has been added ("sac à dos")
2) Even if this add would have been legitimate (actually NOT), the price amount is not correct, neither the transport fees.

![Bill1](https://user-images.githubusercontent.com/12573812/82655229-2746e480-9c22-11ea-842a-12678c1e6445.png)

When I opened this bug, I had another behaviour, which was an article appearing but not taken into account... Pretty near except that the "sac à dos" is not wanted!

**Comment by sugata94** [comment] 2020-05-22 09:56
Note: The same issue can be reproduced when paying by card.

**Comment by sugata94** [comment] 2020-05-22 10:18
This behaviour is reproductible from the back-office:
- Create an order
- ....
- Pay

The received email for the customer is correct, but the created order in the back-office is not.

**Comment by florine2623** [comment] 2020-05-22 12:37
Thanks for the detailed steps.
I still can't manage to reproduce such issue.
I tried in my local shop in PS 1.7.6.5, everything works fine. I have the correct total price in BO and no added products.

Do you have any cart rules that might offer products to certain customer ? (even if YES, the total amount in the order should be correct :/ )
Are you using any overrides ?
If yes, disable them via FTP overrides becomes _overrides and try again.
If that does nothing, re-enable the overrides and enable debug mode on the BO order page.

Please check and let me know!

**Comment by sugata94** [comment] 2020-05-24 06:59
Thanks for your time.

Did you just create an order and validate it by paying?
I didn't put any rules. 
I will try to update to PS 1.7.6.5.

**Comment by florine2623** [comment] 2020-05-25 08:09
Yes I did.
Have you checked the overrides ?
Did you put debug mode ON ?

Thanks!

**Comment by sugata94** [comment] 2020-05-25 18:38
Yes I checked the cart rules. There was an old one for free shipping.
I migrated succesfuly to PS 1.7.6.5 but nothing changed!

I turned on debug mode.
I have an error when I create an order about missing email template ("new_order").
Nevertheless the order is completed: a complete mess!
The last command I got 9 articles listed, but I put only 3 articles in my cart.
BTW I looked in the cart after the order is completed and I see only 3 articles...

@florine2623 : I don't know where to look in the logs. You can probably help?!

**Comment by florine2623** [comment] 2020-05-28 09:10
Can you screenshot the error you have regarding the missing template ?
You can check in /var/logs/

I think it's best if you contact the support and provide them with all the info of BO and FTP, so it would be easier to find the root cause of your issue.
Thanks!

**Comment by sarahdib** [comment] 2020-06-16 12:17
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-06-16 12:17 UTC
Labels: BO, Order, No change required

**Comment by sugata94** [comment] 2020-06-27 09:57
The issue seemed to be very odd.
After migrating to PS 1.7.6.5 and rewrote the Database everything was fine.
Issue may be closed then.

Note: The logs are not in /var/logs in production...
