### ISSUE TITLE
ShopConstraint object value constructor is protected

### ISSUE THREAD

**Issue by GuillaumeVrill** [PrestaShop/PrestaShop#31491] opened 2023-02-22 13:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Writing a module for a client, i need to catch some specific configuration values using `Configuration::get('WATEVER', null, $shopConstraint)` code as indicated in the documentation here : https://devdocs.prestashop-project.org/1.7/development/multistore/shops-configuration/
But when i do `$shopConstraint = new ShopConstraint(1, 1);` as an example, i get a 500 error, telling me the construct method is protected.

### Expected behavior

Expected behavior is the one describe in documentation : be able to instantiate a ShopConstraint object when needed by having a public construct, or by modifying the documentation if another process is required now.

### Steps to reproduce

1. Try to instantiate a ShopConstraint object (do not forget the "use" statement, as this class uses namespace) in an override or module or whatever
2. Be sure to be in debug mode
3. See the 500 error coming at you

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment] 2023-02-22 16:26
Hi @GuillaumeVrill 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by hibatallahAouadni** [comment] 2023-09-01 07:57
Hello @GuillaumeVrill 

Do you still encounter the same issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-29 14:18
Hello @GuillaumeVrill 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-29 14:18 UTC
Labels: Bug, CO, Modules, Invalid, 8.1.x
