### ISSUE TITLE
Double payment created when order without invoice goes into "preparation"

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#18488] opened 2020-04-07 09:14 UTC
## Describe the bug

Double payment created when order without invoice goes into "preparation"

#### Expected behavior

Only 1 payment

#### Steps to Reproduce

1. Create an order
2. Complete it, pay it
3. Don't generate invoice
4. Change order state to Preparation (previously configured with paid = true, delivery = true, invoice = false)
5. Double payment is automatically created.

#### Additional information

* PrestaShop version: 1.7.6

Should be fixed by PR https://github.com/PrestaShop/PrestaShop/pull/18468

**Comment by matks** [comment] 2020-04-07 09:15
Reported by @erouvier29

**Comment by khouloudbelguith** [comment] 2020-04-07 09:50
Hi @matks, 

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12588
A similar previous reported in the forge: http://forge.prestashop.com/browse/BOOM-4196
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-07 09:50
Duplicate of #12588

**Closed as completed by khouloudbelguith** 2020-04-07 09:50 UTC
Labels: Duplicate
