### ISSUE TITLE
guest checkout address bug

### ISSUE THREAD

**Issue by junyisuu** [PrestaShop/PrestaShop#14262] opened 2019-06-18 03:58 UTC
**Describe the bug**
1.7.5.0 When I Enable guest checkout, the user use guest checkout but not order, now he has first guest account, then he use other browser to order the second time use the same email, and his address will add to his first guest account, but the second account not have the address. and the admin order list will not show his order because the address and real order not in one guest account.  or he fill the address in first time, but second time system not ask him fill address.
![20190618115201](https://user-images.githubusercontent.com/44254777/59652289-f886db00-9141-11e9-8fad-2163aa4f8588.png)
and i wonder if now the guest (bought) can register to customer account himself, thanks :)

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

**Comment by ghost** [comment] 2019-06-18 07:45
Hi.
Duplicate Your store and  upgrade to latest 1.7.5.2 stable version and also PHP version set to 7.2. Then check if problem still occour.

**Comment by khouloudbelguith** [comment] 2019-06-18 07:51
Hi @junyisuu, @PrestaShark,

The problem is that the guest account is not transformed into a customer account, it creates a second account => there is no alert => visitors can do multiple orders with the same mail address => this is the whole issue => it needs to be specified by our developers.

Your ticket is a duplicate of #10122
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-18 07:51
Duplicate of #10122

**Closed as completed by khouloudbelguith** 2019-06-18 07:51 UTC
Labels: Duplicate
