### ISSUE TITLE
SQL syntax error with MariaDB

### ISSUE THREAD

**Issue by valentin-harrang** [PrestaShop/PrestaShop#36041] opened 2024-04-28 21:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Some of my customers have a 500 error at the end of their order. I've tried to reproduce the problem, but I don't think it's for everyone, and I don't quite understand how it happens.

I use version 8.1.5 of Prestashop, my PHP version is 8.1 and I use version 10.5.21 of MariaDB.

Error log:

> *ERROR* 	v8.1.5	2024/04/28 - 22:53:49: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &#039;AND ccr.id_cart_rule = 40 AND o.id_order IS NULL LIMIT 1&#039; at line 5 at line 151 in file classes/db/DbPDO.php

I think it's the same problem as here: https://github.com/PrestaShop/PrestaShop/issues/33157#issue-1794895223 But the error occurs with a `SELECT` instead of a `DELETE`.

The error seems to be in this query from `classes/CartRule.php`:

```php
                $quantityUsed += (int) Db::getInstance()->getValue('
                    SELECT count(*)
                    FROM `' . _DB_PREFIX_ . 'cart_cart_rule` ccr
                    INNER JOIN `' . _DB_PREFIX_ . 'cart` c ON c.id_cart = ccr.id_cart
                    LEFT JOIN `' . _DB_PREFIX_ . 'orders` o ON o.id_cart = c.id_cart
                    WHERE c.id_customer = ' . $cart->id_customer . ' AND c.id_cart = ' . $cart->id . ' AND ccr.id_cart_rule = ' . (int) $this->id . ' AND o.id_order IS NULL
                ');
```

### Steps to reproduce

Making an order with Prestashop 8.1.5.

If you run this SQL command by hand, you won't get the syntax error:

```sql
SELECT count(*) FROM `hd9W_cart_cart_rule` ccr INNER JOIN `hd9W_cart` c ON c.id_cart = ccr.id_cart LEFT JOIN `hd9W_orders` o ON o.id_cart = c.id_cart WHERE c.id_customer = 58 AND c.id_cart = 127 AND ccr.id_cart_rule = 40 AND o.id_order IS NULL;
```

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

**Comment by valentin-harrang** [comment] 2024-04-28 21:35
I suggest to replace this code in CartRule.php :

```php
        if ($cart->id_customer) {
            $quantityUsed = Db::getInstance()->getValue('
			SELECT count(*)
			FROM `' . _DB_PREFIX_ . 'orders` o
			LEFT JOIN `' . _DB_PREFIX_ . 'order_cart_rule` ocr ON o.`id_order` = ocr.`id_order`
			WHERE o.`id_customer` = ' . $cart->id_customer . '
			AND ocr.`deleted` = 0
			AND ocr.`id_cart_rule` = ' . (int) $this->id . '
			AND ' . (int) Configuration::get('PS_OS_ERROR') . ' != o.`current_state`
			');

            if ($alreadyInCart) {
                // Sometimes a cart rule is already in a cart, but the cart is not yet attached to an order (when logging
                // in for example), these cart rules are not taken into account by the query above:
                // so we count cart rules that are already linked to the current cart but not attached to an order yet.

                $quantityUsed += (int) Db::getInstance()->getValue('
                    SELECT count(*)
                    FROM `' . _DB_PREFIX_ . 'cart_cart_rule` ccr
                    INNER JOIN `' . _DB_PREFIX_ . 'cart` c ON c.id_cart = ccr.id_cart
                    LEFT JOIN `' . _DB_PREFIX_ . 'orders` o ON o.id_cart = c.id_cart
                    WHERE c.id_customer = ' . $cart->id_customer . ' AND c.id_cart = ' . $cart->id . ' AND ccr.id_cart_rule = ' . (int) $this->id . ' AND o.id_order IS NULL
                ');
            } else {
                // When checking the cart rules present in that cart the request result is accurate
                // When we check if using the cart rule one more time is valid then we increment this value
                ++$quantityUsed;
            }
            if ($quantityUsed > $this->quantity_per_user) {
                return (!$display_error) ? false : $this->trans('You cannot use this voucher anymore (usage limit reached)', [], 'Shop.Notifications.Error');
            }
        }
```

By:

```php
        if ($cart->id_customer) {
            // Utilisation de la requête préparée pour éviter les injections SQL et les erreurs de syntaxe
            $query = 'SELECT count(*) FROM `' . _DB_PREFIX_ . 'orders` o
                      LEFT JOIN `' . _DB_PREFIX_ . 'order_cart_rule` ocr ON o.`id_order` = ocr.`id_order`
                      WHERE o.`id_customer` = ? AND ocr.`deleted` = 0 AND ocr.`id_cart_rule` = ? AND ? != o.`current_state`';
            $params = [
                $cart->id_customer,
                (int) $this->id,
                (int) Configuration::get('PS_OS_ERROR')
            ];
            $quantityUsed = Db::getInstance()->getValue($query, $params);

            if ($alreadyInCart) {
                $query = 'SELECT count(*)
                          FROM `' . _DB_PREFIX_ . 'cart_cart_rule` ccr
                          INNER JOIN `' . _DB_PREFIX_ . 'cart` c ON c.id_cart = ccr.id_cart
                          LEFT JOIN `' . _DB_PREFIX_ . 'orders` o ON o.id_cart = c.id_cart
                          WHERE c.id_customer = ? AND c.id_cart = ? AND ccr.id_cart_rule = ? AND o.id_order IS NULL';
                $params = [
                    $cart->id_customer,
                    $cart->id,
                    (int) $this->id
                ];
                $quantityUsed += (int) Db::getInstance()->getValue($query, $params);
            } else {
                ++$quantityUsed;
            }

            if ($quantityUsed > $this->quantity_per_user) {
                return (!$display_error) ? false : $this->trans('You cannot use this voucher anymore (usage limit reached)', [], 'Shop.Notifications.Error');
            }
        }
```

**Comment by cruftex** [comment] 2024-04-28 23:37
@valentin-harrang 
This is a different problem than #33157.

I can see that the error contains "LIMIT 1" but your test query below does not contain it.
Somehow something different is executed. Can you turn on full query logging and check what actually is send to the DB?

**Comment by valentin-harrang** [comment] 2024-04-29 07:40
@cruftex thank you for the answer.

I added `LIMIT 1` to the end of my query in PhpMyAdmin and it works fine.

```sql
SELECT count(*) FROM `hd9W_cart_cart_rule` ccr INNER JOIN `hd9W_cart` c ON c.id_cart = ccr.id_cart LEFT JOIN `hd9W_orders` o ON o.id_cart = c.id_cart WHERE c.id_customer = 58 AND c.id_cart = 127 AND ccr.id_cart_rule = 40 AND o.id_order IS NULL LIMIT 1;
```

I need to know the exact query, so I've added `error_log` in the `CartRule.php` file, but I can't reproduce the error, because when I place an order, it works fine on my end, but not for certain customers.

**Comment by ChillCode** [comment] 2024-04-29 14:43
Just to point If I'm not wrong that LIMIT 1 is added when we call `getRow()`, also MySQL would complain near LIMIT 1 instead of near AND.

I'd try to debug all commands between that method.

**Comment by cruftex** [comment] 2024-04-29 23:48
@valentin-harrang 
I recommend that you verify the actual query that the database receives. Maybe some database driver or database middleware is modifying things in between. Check and enable the error log and also the general log file. The general log file logs all queries, so do this temporarily in the less busy hour. See about the general query log here: https://mariadb.com/kb/en/general-query-log/

Best is you make a test order by yourself with a customer that is known to have problems. Just replace the password entry temporarily in the database. There are also modules that allow "Login as Customer" from the backoffice.

Try to reproduce the error in production by sending the query via the mysql client. Make sure you send the query exactly as the same user. The error messaged said, syntax error or **access violation**. Maybe there is nothing wrong with the syntax at all. Also double-check the configuration and look for differences with things interfering with queries, like query caching.

Good luck!

**Comment by paulnoelcholot** [comment] 2024-06-11 08:47
Hello @valentin-harrang ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-06-11 08:47 UTC
Labels: Bug, CO, Order, Invalid, 8.1.x

**Comment by ricmyra** [comment] 2024-08-06 04:46
Hi @valentin-harrang ,

I discovered that this is a BUG in the SQL statement, maybe it only occurs with some versions of the database, to solve it I corrected the SQL that is in the file Classes/CartRule.php line 733, you should replace it with the code below.
[code.txt](https://github.com/user-attachments/files/16505354/code.txt)

If you prefer, here is the complete file modified for version 8.1.4 of Prestashop.
[CartRule.zip](https://github.com/user-attachments/files/16505390/CartRule.zip)

                
I hope this helps others who may be having the same problem.

Good luck!
