### ISSUE TITLE
Database password save bug during installation

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#23304] opened 2021-02-19 09:48 UTC
#### Describe the bug

After a fresh installation (1.7.7.1), I was unable to access to front and admin. Doctrine connection error.
I discover that a character has been added to my DB password.
I think there is a bug with some mysql characters.

My pass : xxxxxxxxx%
Stored as : xxxxxxxxx%%

#### Expected behavior

Store the pass without changes

#### Steps to Reproduce

1. Install prestashop, with a DB pass ending with a %
2. Go on admin 
3. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.27

**Comment by florine2623** [comment] 2021-02-19 11:52
Hello @rflorent ,
This issue is fixed for PS 1.7.8
As you can see here : https://github.com/PrestaShop/PrestaShop/issues/12556

I'll close your issue as it is a duplicate.
Thanks

**Comment by florine2623** [comment] 2021-02-19 11:53
Duplicate of #12556

**Closed as completed by florine2623** 2021-02-19 11:53 UTC
Labels: Duplicate
