### ISSUE TITLE
Strange problem when adding an item to the shop cart from the backoffice

### ISSUE THREAD

**Issue by Aritz3d** [PrestaShop/PrestaShop#34743] opened 2023-12-01 09:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I modify anything in the order, for example when someone want to add or remove an item or change the colour of one item, the shipping cost increases the price because prestashop added the 21% VAT to the shipping cost, even if this customer does not taxes (he is not a EU citizen).
I attach them in one screenshot. The problem is even more strange because in the backoffice the shipping increses just the 21% VAT (from 19.50 to 23.60) but when the the system creates the invoice, none of that is happening, it just adds a tax of 4.10 EUR and the shipping cost remains the same
![Screenshot_19](https://github.com/PrestaShop/PrestaShop/assets/8033812/5721041a-3662-4691-8851-c52b9999ba4d)

### Expected behavior

It should keep the shipping cost unchanged since the total weight is the same and this customer does not have to pay VAT

### Steps to reproduce

In the backoffice, enter to an existing order, add an item

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.1

**Comment by florine2623** [comment] 2023-12-04 14:05
Hello @Aritz3d ,

Could you specify with more details all the steps to reproduce the issue ?

Price of the product, price of the product after editing the order, shipping price, type of customer (B2B or other), etc...

**Comment by paulnoelcholot** [comment] 2023-12-22 13:58
Hello @Aritz3d,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed** 2023-12-22 13:59 UTC
Labels: Bug, BO, Invoices, 1.7.6.0, Invalid
