### ISSUE TITLE
Prestashop 1.7.5 performance tab functionalities not saving data

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#12977] opened 2019-03-20 12:28 UTC
I am using prestashop 1.7.5 multistore. I have tried to enable the below options ,but these options are not saved into the database and they are still remaning as No.

Please check the attached video. Also when enabling the memcache thats also not saving in to the database

 Smart cache for CSS
Smart cache for JavaScript
Apache optimization

https://drive.google.com/file/d/1dGYn1IeLJn4Vn-M03Ws3u3Xwc0FMO77k/view

**Comment by khouloudbelguith** [comment] 2019-03-21 15:56
Hi @pks891618,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1N6s0WM861xSmNp1UuD4UCmJ9PyJt9mT4/view
For the `Debug mode` section:
Select "All shop" & enable all the options.
When you select a shop you can enable/disable options.
For the `Caching` section, to be enabled, you must have Memcached installed on your server.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-04-22 07:31
Hi @pks891618, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-22 07:31 UTC
Labels: BO, Performance, Multistore, No change required, 1.7.5.1
