### ISSUE TITLE
Ecotax is decreased when saving a product

### ISSUE THREAD

**Issue by sixfingers76** [PrestaShop/PrestaShop#14195] opened 2019-06-13 14:20 UTC
**Describe the bug**
When ecotax is active, and is specified any tax for the ecotax, everytime you save the product, the ecotax is decreased based on the tax specified for the ecotax.

Seems that when saving a product, the ecotax value is decreased in the "tax" percentage specified for the ecotax before storing it in the database, but the opposite operation (apply the tax to the ecotax) is not performed when showing the ecotax value for the product, so when you save the product again, the ecotax is decreased again before saving it in the database, and so on.

**To Reproduce**
1. Enable ecotax in the shop, and apply any tax to the ecotax
2. Show any product sheet and specify any amount for the ecotax (as you can see, the amount must include the tax)
3. Save the product several times
4. See that the amount for the ecotax is decreased automatically based on the tax specified for the ecotax

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-13 14:26
Hi @sixfingers76,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10026
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-13 14:26
Duplicate of #10026

**Closed as completed by khouloudbelguith** 2019-06-13 14:26 UTC
Labels: Duplicate
