### ISSUE TITLE
impossible to select combinations images

### ISSUE THREAD

**Issue by rancidio** [PrestaShop/PrestaShop#15280] opened 2019-08-27 18:24 UTC
Hi, i have update my prestashop version to 1.7.6.1 but today when insert new product with combination it does not let me select images for the combinations. In the combination menu i see the images but I can't select them

UPDATE!  The problem is with Chrome, I tried with Firefox and the problem does not occur
![Cattura](https://user-images.githubusercontent.com/54597701/63797576-a106a780-c908-11e9-8262-7a899df4576d.PNG)

**Comment by khouloudbelguith** [comment] 2019-08-28 08:06
Hi @rancidio,

I did not manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/1HFSRBfhV1ynu_VMcAg3WXQ5r6EogfNhH/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-30 08:29
Hi @rancidio,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-30 08:29 UTC
Labels: Bug, BO, Combinations, No change required
