### ISSUE TITLE
Quotes escaped into module name on Positions page

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#15097] opened 2019-08-13 15:02 UTC
**Describe the bug**
Quotes character is replaced by `&quot;` into module name on Positions page:

![Positions page](https://user-images.githubusercontent.com/7419525/62952167-7df9d500-bdeb-11e9-83c4-ff3de45db505.png)

When on Module listing page, module name is well displayed:

![Modules page](https://user-images.githubusercontent.com/7419525/62952461-ff516780-bdeb-11e9-881b-c64651863d5d.png)

**To Reproduce**
1. Rename an existing module with quotes in the name 
2. Go to Modules page to see displayed module name
3. Go to Positions page to see displayed module name

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by mariem-abid** [comment] 2019-08-13 15:19
Hi @Klemart3D,

I manage to reproduce the issue with the last version PS:1.7.6.0
I attached a screenshot.
![positions](https://user-images.githubusercontent.com/36841537/62953899-4a687c00-bde6-11e9-89ea-b10c9b2fd160.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2019-08-13 16:19
Hello @mariem-abid 

Can you try to reproduce it with PS 1.7.5.2 and tell us if it's a regression or not ?

**Comment by mariem-abid** [comment] 2019-08-14 08:42
Hi @mariem-abid,

I did not manage to reproduce the issue with PS 1.7.5.2.

**Comment by matks** [comment] 2019-08-14 16:22
I explored this issue and I can explain what's going on here.

### How I reproduce it

I use the Welcome native module and modify
`        $this->displayName = $this->trans('Welcome', array(), 'Modules.Welcome.Admin');
`
to
`        $this->displayName = $this->trans('Welcome "a', array(), 'Modules.Welcome.Admin');
`

So I can see the issue:
![Capture d’écran 2019-08-14 à 18 17 39](https://user-images.githubusercontent.com/3830050/63037677-d8646580-bebf-11e9-9774-cc85f234f0f5.png)

However if I modify it to
`this->displayName = 'Welcome "a';` (=> I do not translate the module display name), there is no bug.

So *the bug appears when a module uses a name with double quotes in it and makes it translatable*.

### Behind the curtain

It looks like the root cause of the issue is really deep in the stack. According to @eternoendless, when the module translation system is called, it attempts to find the translation according to the new rules, and if it fails, it fallbacks to the old transation system that performs a HTML character escape. This is what converts `"` to `&quot;` (see https://github.com/PrestaShop/PrestaShop/pull/13378)

Later, in the rendering of the page, this field is escaped again by Twig which converts `&` to `&amp;` and makes it un-renderable by the browser.

### How to solve it

Here's the good news: there is a big work going on to solve this issue which is linked to the translation system.
Here's the bad news: this work is massive and in progress, which means:
- it cannot be shipped in a patch version
- it will only be released later, for next minor version 1.7.7

So this issue cannot be fixed in the scope of PS 1.7.6.1, this is why I remove it from the 1.7.6.1 scope (ping @marionf)

**Comment by PierreRambaud** [comment] 2019-11-14 15:53
@eternoendless @matks Do we plan to remove the legacy system for the 1.7.7?

**Comment by matks** [comment] 2019-11-15 09:20
@PierreRambaud I think the idea was to stop using the legacy system and use the modern translation system.

The strange thing is that the new translation system for modules was actually released in 1.7.6 so I'm wondering why at this time I wrote that we had to wait for 1.7.7 🤔.

But even if it works, it means our answer would be "Eyh, if you want your module name to be able to be displayed with double quotes, you need to stop using legacy translation system and use the new one instead" => is this an acceptable answer ?

**Comment by PierreRambaud** [comment] 2019-11-15 14:54
I think it's more complicated than that.
For example `$this->trans('Welcome "a', array(), 'Modules.Welcome.Admin');` use the new system, and event if you want, if the string id is not found in the new system, it tries on the legacy one, and the legacy use htmlspecialchars (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Translate.php#L260) even if you don't need it.

**Comment by matks** [comment] 2019-11-18 09:40
> I think it's more complicated than that.
> For example `$this->trans('Welcome "a', array(), 'Modules.Welcome.Admin');` use the new system, and event if you want, if the string id is not found in the new system, it tries on the legacy one, and the legacy use htmlspecialchars (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Translate.php#L260) even if you don't need it.

By "use the new system" I meant to populate the translation database with the required strings so the system does not fallback on the legacy 😕 but it's not a great answer I'm afraid.

What about a crazy idea ? What about we disable the `htmlspecialchars` in legacy translation system when it's triggered as fallback (and it's default enabled when used directly) ?

**Comment by PierreRambaud** [comment] 2019-11-18 10:13
@matks Could be a solution yes :) wdyt @eternoendless ?

**Closed as completed** 2019-11-29 19:09 UTC
Labels: Bug, Trivial, BO, Modules, Positions, Regression, Fixed, 1.7.6.0
