### ISSUE TITLE
Clear filters button on Product combinations page not displaying right value PS 8.1.0

### ISSUE THREAD

**Issue by l-delin** [PrestaShop/PrestaShop#31768] opened 2023-03-13 16:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the new page product on PS 8.1.0, the `"Clear X filters"` button doesn't display any value on the `Products > Add new products > Combinations > Manage product combinations` tab. Instead, it displays  `Clear %filtersNb% filters` when it should display the indicated value. 

See:
 
**1 selected attribute in a filter (button works as intended):**
<img width="809" alt="image" src="https://user-images.githubusercontent.com/113511191/224757122-974e53eb-1505-47df-9b90-b1d66964d0bd.png">

**2 or more selected attributes in a filter (button breaks):**
<img width="809" alt="image" src="https://user-images.githubusercontent.com/113511191/224757343-5980b812-231d-4880-842d-4f64bbc7af10.png">

### Expected behavior

The selected number of products should be displayed instead of the variable `%filtersNb%`. (eg. `Clear 45 filters`)

### Steps to reproduce

1. Toggle the new product page in **New & Experimental features**
2. Go to the products page and **create a new product with combinations**
3. Select **all attributes for Size and Color**
4. Click on the **Generate X combinations** button
5. Select **more than two attributes** for any filter (eg. Size: M, L)
6. Look at the **Clear filter button.** (It should work fine with only one selected filter, but not when two or more attributes are selected.)

### PrestaShop version(s) where the bug happened

8.1.0

**Comment by AureRita** [comment] 2023-03-13 16:55
Hi @l-delin  ,

I reproduce the issue with PrestaShop version 8.1.0 and not with the version 8.0.1 as you can see : 

[Untitled_ Mar 13, 2023 5_51 PM.webm](https://user-images.githubusercontent.com/100699445/224771418-ba508225-ca88-42b2-ac23-ac293a2ff2ee.webm)


 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved.

Thank you

**Comment by jolelievre** [comment] 2023-03-13 18:14
I think it's a duplicate of https://github.com/PrestaShop/PrestaShop/issues/31417

**Closed as completed** 2023-03-20 15:01 UTC
Labels: Bug, Minor, BO, Regression, Ready, Verified, 8.1.x
