### ISSUE TITLE
Retail price per unit not calculating properly for combinations

### ISSUE THREAD

**Issue by Brig74** [PrestaShop/PrestaShop#36020] opened 2024-04-24 14:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When adding impact on unit price for a combination, the unit price showing on the product page is wrong.

The first combination has a retail price per unit of 38.95€/kg and 1 kg weight
The second combination weights only 600g, so the retail price per unit is 45.5€/kg. So I add 6.55 in the impact on retail price per unit field, and I get 33.85€/kg on the product page. The calculation is wrong.

### Expected behavior

![Screenshot 2024-04-24 154148](https://github.com/PrestaShop/PrestaShop/assets/165154299/8168f084-e553-40b5-8cb4-aa03d177dd4c)
![Screenshot 2024-04-24 154840](https://github.com/PrestaShop/PrestaShop/assets/165154299/7d13e195-22d3-4516-9be5-5c6766615fb7)
![Screenshot 2024-04-24 155957](https://github.com/PrestaShop/PrestaShop/assets/165154299/66dde8f2-b174-4ef0-8f11-7f71b3c96b38)
![Screenshot 2024-04-24 160053](https://github.com/PrestaShop/PrestaShop/assets/165154299/3f34b953-c1c0-426b-b634-0a1b56b21aee)

### Steps to reproduce

Go to BO > Products > Edit any product
Go to Pricing tab > add retail price per unit: 38.95€/kg
Create a new combination
Add 6.55 in the impact on retail price per unit
Check the retail price per unit showing on the product page for each combination
The retail price per unit should be 45.5€/kg instead of 33.95€/kg

### PrestaShop version(s) where the bug happened

1.7.8.2.

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment] 2024-04-24 15:24
Hello @Brig74 ,

Your issue is fixed on 8.1.x and is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9901

I'm using PS 8.1 with the updated product page. On my end it works correctly :
<img width="916" alt="Screenshot 2024-04-24 at 17 16 09" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/21d5787f-8341-4776-887e-820ea6580fa8">

<img width="655" alt="Screenshot 2024-04-24 at 17 17 38" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e944230e-51da-43f1-8607-4a1e83c27c10">

https://github.com/PrestaShop/PrestaShop/assets/16019289/834cf7fe-6771-4667-8471-1f8502b2ae08

I'm closing the issue as it has been fixed. You can update your shop to 8.1.x

Thanks!

**Closed as completed by florine2623** 2024-04-24 15:24 UTC
Labels: Bug, Fixed
