### ISSUE TITLE
Link List Not Accepting 'Tel:000000' addresses

### ISSUE THREAD

**Issue by elliottridown** [PrestaShop/PrestaShop#21683] opened 2020-10-30 10:31 UTC
#### Describe the bug

If I want to add a link to the 'Link List' module, I get a validation error to say a 'tel:' address is invalid, this is the same for 'mailto:'

#### Expected behavior

Should be able to enter 'tel:02380733042' as a link in to the Link List Module configuration.

#### Steps to Reproduce

1. Go to Modules
2. Click on Link List -> Configuration
3. Select a link list and click edit.
4. Try entering 'tel: 02380733042' as a custom link.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3.8

**Comment by SimonGrn** [comment] 2020-10-30 10:49
Hello @elliottridown 

PrestaShop 1.7.6.4 is not compatible with PHP 7.3 as you can see in the [documentation](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).

Please downgrade your PHP version and try again.

**Comment by elliottridown** [comment] 2020-10-30 10:50
> Hello @elliottridown
> 
> PrestaShop 1.7.6.4 is not compatible with PHP 7.3 as you can see in the [documentation](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart).
> 
> Please downgrade your PHP version and try again.

Have tried on lower versions of PHP.

**Comment by florine2623** [comment] 2020-10-30 13:06
Hi @elliottridown ,
The URL must be a URL and not a phone number :
![Capture d’écran 2020-10-30 à 14 05 37](https://user-images.githubusercontent.com/16019289/97708419-12b42580-1ab9-11eb-8a08-2e56b8328301.png)
Thanks!

**Comment by elliottridown** [comment] 2020-10-30 15:27
> Hi @elliottridown ,
> The URL must be a URL and not a phone number :
> ![Capture d’écran 2020-10-30 à 14 05 37](https://user-images.githubusercontent.com/16019289/97708419-12b42580-1ab9-11eb-8a08-2e56b8328301.png)
> Thanks!

You wrongly closed my issue there, putting 'tel:123456789' is a valid URL, please see here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

You should allow entering 'tel:12345678' or 'mailto:mail@mail.com' as these are both valid URLs.

**Comment by hibatallahAouadni** [comment] 2020-10-30 15:57
Hi @elliottridown 

That's the normal behavior of PS, so it's not a bug. But, we can consider it as an improvement.
Ping @PrestaShop/product-team what you think about it?

Thanks!

**Comment by LouiseBonnard** [comment] 2020-11-02 15:57
Hello @hibatallahAouadni and @elliottridown, thanks for this issue. Link List module is meant to display pages rather than contact information.

If you want to display a phone number in the footer, you can add it in the Shop Parameters > Contact > Stores section of the back office. It is not clickable for now but an issue has been raised to do so, cf. https://github.com/PrestaShop/PrestaShop/issues/18928 & https://github.com/PrestaShop/ps_contactinfo/pull/35. :-)

**Comment by SimonGrn** [comment] 2020-11-02 16:17
Thank you @LouiseBonnard !
I close this issue since it's a duplicate.

Thank you for your understanding.

**Comment by SimonGrn** [comment] 2020-11-02 16:17
Duplicate of #18928

**Closed as completed by SimonGrn** 2020-11-02 16:17 UTC
Labels: Improvement, BO, Duplicate, 1.7.6.x
