### ISSUE TITLE
Link Error in search category BO

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#17904] opened 2020-03-01 18:45 UTC
#### Describe the bug

Saerching a category in the BO by use the top search. Them click to the category to edit/view, you will always sent to root category and not in the right sub category, all child subcategory link send to root category 

#### Expected behavior

Go in the right category edit/view page

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.2 - 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-02 10:36
Hi @Gipielle,

Thanks for your report.
Is it the same issue with this issue: https://github.com/PrestaShop/PrestaShop/issues/17908? 
Is it the quick search?
![image](https://user-images.githubusercontent.com/16067358/75668402-93482b00-5c79-11ea-8b33-919ade0bc836.png)

Or similar to this issue?
https://github.com/PrestaShop/PrestaShop/issues/15588
![image](https://user-images.githubusercontent.com/16067358/75668706-0651a180-5c7a-11ea-896d-0ffb3609922f.png)


Thanks!

**Comment by Gipielle** [comment] 2020-03-02 11:37
No, this: https://github.com/PrestaShop/PrestaShop/issues/17908

found now ...

**Comment by khouloudbelguith** [comment] 2020-03-02 11:39
Hi @Gipielle,

Thanks for your feedback.
It is added to our debug roadmap.
Your ticket is a duplicate of #17908
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-02 11:39
Duplicate of #17908

**Closed as completed by khouloudbelguith** 2020-03-02 11:39 UTC
Labels: Bug, BO, Duplicate, Categories, 1.7.6.2, 1.7.6.3
