### ISSUE TITLE
SEO live previews don't work on Safari desktop

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/PrestaShop#17525] opened 2020-02-06 09:47 UTC
**Describe the bug**
SEO live previews don't work properly on Safari desktop.
Instead of displaying the meta-title, URL and meta-description,  it only displays the URL.

![Capture d’écran 2020-02-06 à 08 50 28](https://user-images.githubusercontent.com/25405887/73923763-ae6a8980-48cb-11ea-9593-9fe28eada676.png)

**To Reproduce**
1. Go to Design > Pages > Create a new page
2. Fill in the fields
3. See the preview not working and the text editor nor being displayed

**Expected behavior**
![Capture d’écran 2020-02-06 à 10 43 32 (2)](https://user-images.githubusercontent.com/25405887/73924988-9bf14f80-48cd-11ea-8170-6917f84546ea.png)

**Additional information**
PrestaShop version: 1.7.6.2
Safari version: 11.1.1
MacOS: 10.13.5

Couldn't reproduce with **Safari 13.0.5** on **MacOS 10.14.6** with **PS 1.7.6.2**

**Comment by khouloudbelguith** [comment] 2020-02-06 10:58
Hi @sam-pires,

I used os => OS+X => os_version=High+Sierra => browser=>Safari & browser_version=>11.1
>SEO live previews don't work properly on Safari desktop.

I have the same issue with PS1.7.6.0 & PS1.7.6.3 & Version 11.1.2 (13605.3.8)
With PS1.7.5.2, the SEO preview doesn't exit => so it is a regression.
![image](https://user-images.githubusercontent.com/16067358/73930773-681b2780-48d7-11ea-93d5-da387e946641.png)

>The TinyMCE text editor is not displayed either.

It is ok in my case with PS1.7.6.0 & PS1.7.6.3

![image](https://user-images.githubusercontent.com/16067358/73930694-4326b480-48d7-11ea-9a27-d7dcb22d71df.png)
![image](https://user-images.githubusercontent.com/16067358/73930804-75d0ad00-48d7-11ea-9de6-40f5956c1d9a.png)
But similar issue fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16535 as reported here: https://github.com/PrestaShop/PrestaShop/issues/15272

Thanks!

**Comment by sam-pires** [comment] 2020-02-06 12:58
Thank you @khouloudbelguith 🙂 

I'll update the title to not mention the TinyMCE issue anymore and focus on the SEO preview.

**Comment by sam-pires** [comment] 2020-02-10 13:24
Did some research, Safari 10 global coverage represents 0,02% according to caniuse.

![Capture d’écran 2020-02-10 à 14 22 01](https://user-images.githubusercontent.com/25405887/74153362-c0706300-4c10-11ea-9d9a-c808ff7be9c9.png)


Keep me posted on the source of the bug before trying to fix it please.

**Comment by sam-pires** [comment] 2020-02-18 10:25
Hello @NeOMakinG
Do you have some news on this one?

**Comment by PierreRambaud** [comment] 2020-02-18 10:29
@sam-pires Should we really fix this kind of issue when it targets only 0.02%  of the web :scream:

**Comment by sam-pires** [comment] 2020-02-18 10:32
No, but first I want to be sure the bug comes from an unsupported behavior in former Safari versions :)

**Comment by matks** [comment] 2020-02-18 10:35
> @sam-pires Should we really fix this kind of issue when it targets only 0.02% of the web 😱

If I wanted to play the devil's advocate :trollface: , I would say
- we dont care about the web, we care about prestashop users
- since 50% of web traffic is porn, it means it's actually 0.04% of real traffic

**Comment by NeOMakinG** [comment] 2020-02-18 14:05
Fixed it on 1.7.6.x , but I already fixed it on develop a while ago

**Comment by eternoendless** [comment] 2020-02-28 09:47
Fixed by #17711

**Closed as completed by eternoendless** 2020-02-28 09:47 UTC
Labels: Bug, Minor, BO, Pages, Regression, Fixed, 1.7.6.0, 1.7.6.3
