### ISSUE TITLE
new pruduct>drcounts<new arrived not working in RTL 

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17264] opened 2020-01-20 21:06 UTC
![image](https://user-images.githubusercontent.com/1392266/72757663-3ddc2100-3bd9-11ea-926e-56156bd23866.png)
![image](https://user-images.githubusercontent.com/1392266/72757736-6b28cf00-3bd9-11ea-9715-df0e8ad8dd3e.png)

![image](https://user-images.githubusercontent.com/1392266/72757683-4af91000-3bd9-11ea-8770-6a4b8039138e.png)
![image](https://user-images.githubusercontent.com/1392266/72757755-78de5480-3bd9-11ea-96f6-d9c88421632a.png)

**Comment by khouloudbelguith** [comment] 2020-01-21 09:24
Hi @khalidzuhd,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.2
I attached a screen record
https://drive.google.com/file/d/1qqR2k8Ea6fGr1KYjK3lU9ec3TWvR_vQr/view
When English is selected => New products page are well displayed?
What is the exact version of PS1.7 did you use?

Thanks!

**Comment by khalidzuhd** [comment] 2020-01-21 13:36
1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-01-21 14:06
@khalidzuhd,

1. When English is selected => New products page are well displayed?
2. In the Back office => Shop Parameters => Product Settings => what is the exact number of "Number of days for which the product is considered 'new'"
![image](https://user-images.githubusercontent.com/16067358/72809838-bcc66d80-3c5c-11ea-9951-2231c2afb4cf.png)
3. Do you have new products created less than "Number of days for which the product is considered 'new'"?

Thanks!

**Comment by khalidzuhd** [comment] 2020-01-21 14:17
![image](https://user-images.githubusercontent.com/1392266/72812001-6c094180-3c69-11ea-9a8e-7cabefd50e78.png)
![image](https://user-images.githubusercontent.com/1392266/72812076-8511f280-3c69-11ea-8dd7-e424d99d5f82.png)
english and arabic theme classic

**Comment by khouloudbelguith** [comment] 2020-01-21 14:22
@khalidzuhd, this is another issue reported here: https://github.com/PrestaShop/PrestaShop/issues/17261
It is different, in this ticket: we are working on your new products page issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-20 08:07
Hi @khalidzuhd,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-20 08:07 UTC
Labels: Bug, FO, International, No change required
