### ISSUE TITLE
Email template placeholders not being replaced

### ISSUE THREAD

**Issue by Jerir** [PrestaShop/PrestaShop#15336] opened 2019-08-30 14:14 UTC
**Describe the bug**
In versions 1.7.5 and 1.7.6 there is an issue where the placeholders specified in an email template are not always replaced with actual values.  

In Mail.php, $toPlugin is set to $to.  However $to is then potentially modified by the toPunycode() function before being added as the email's 'To' address.  If the toPunycode() function modifies the 'To' address, it will no longer match the key in the Replacements array sent to the SwiftMailer Decorator plugin and so the placeholder replacements will be ignored.

**To Reproduce**
1. Create a customer with an email address with upper and lower case characters in the 'domain' part.
2. The email sent to the customer will not have it's placeholders updated with actual values.

**Screenshots**

**Additional information**
PrestaShop version: 1.7.5 and 1.7.6
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-08-30 14:51
Hi @Jerir,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13386
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-30 14:51
Duplicate of #13386

**Closed as completed by khouloudbelguith** 2019-08-30 14:51 UTC
Labels: Duplicate
