### ISSUE TITLE
if i click quick access then a new product throws me to the home page

### ISSUE THREAD

**Issue by MSZXYZDEV** [PrestaShop/PrestaShop#17782] opened 2020-02-22 05:35 UTC
if i click quick access then a new product throws me to the home page

**Comment by khouloudbelguith** [comment] 2020-02-24 09:49
Hi @MSZXYZDEV,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-24 07:45
Hi @MSZXYZDEV,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-24 07:45 UTC
Labels: Bug, FO, No change required
