### ISSUE TITLE
Error during upgrade from 1.7.4.4 to 1.7.6.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15456] opened 2019-09-06 21:24 UTC
Hi
I have a problem with a site upgraded some months ago from 1.6.x to 1.7.4.4, now I cannot upgrade it to the successive versions, each time I get the same error

Error during database upgrade. You may need to restore your database.
Download of the language pack it failed. Pacchetto lingua non disponibile. http://i18n.prestashop.com/translations/1.7.6.1/it-IT/it-IT.zip

but from that alert all steps of database updates have been made

bye

**Screenshots**
![111](https://user-images.githubusercontent.com/653230/64461265-0757ab00-d0fd-11e9-9a9a-2a6f8744e5c3.png)

**Additional information**
PrestaShop version: 1.7.4.4
PHP version: 7.0
1-click upgrade module: 4.9.0

**Comment by Maofree** [comment] 2019-09-06 21:33
however it seems to have been updated correctly, without errors
all seems ok in back-office and front-office

**Comment by khouloudbelguith** [comment] 2019-09-09 11:08
Hi @maofree,

I did not manage to reproduce the issue with PS1.7.6.1 after an upgrade from PS1.7.4.4 using the 1-click upgrade v4.9.0.
I attached a screen record
https://drive.google.com/file/d/1mrsLaZgBRvF5pCtnR1qRNv83560jdCES/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-10-09 08:05
Hi @maofree,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-09 08:05 UTC
Labels: Bug, Autoupgrade, No change required, 1.7.6.1
