### ISSUE TITLE
Performance issues with ps_facetedsearch

### ISSUE THREAD

**Issue by xonsuns** [PrestaShop/PrestaShop#26159] opened 2021-10-08 11:52 UTC
#### Describe the bug

We found for some weeks a CPU usage % in our servers of 70%+ when we edit or create a product. Also it starts to take more and more time to do it (last time it was 35sec!). After talking with our hosting they sent us a x-ray php report with a 139ms query launched 205 times by the module. I delete the cache (both manually and auto), reindex product prices, delete price filters, ... no changes at all.

As soon as i disabled the module everything went back to normal (1/2sec saving a product)

QUERY

> SELECT product_shop.`price`,
> product_shop.`ecotax`, IFNULL(product_attribute
> _shop.id_product_attribute,0)
> id_product_attribute,
> product_attribute_shop.`price` AS attribute_price,
> product_attribute_shop.default_on FROM
> `ps_product` p INNER JOIN `ps_product_shop`
> `product_shop` ON
> (product_shop.id_product=p.id_product AND
> product_shop.id_shop = 1) LEFT JOIN
> `ps_product_attribute_shop`
> `product_attribute_shop` ON
> (product_attribute_shop.id_product = p.id_product
> AND product_attribute_shop.id_shop = 1)
> WHERE (p...

----------------
FILE

> pdo_query
> .../classes/db/DbPDO.php:165
> DbPDOCore->_query()
> .../classes/db/DbPDO.php:165
> DbCore->query()
> .../classes/db/Db.php:376
> DbCore->executeS()
> .../classes/db/Db.php:613
> ProductCore->priceCalculation()
> .../classes/Product.php:3453
> Ps_Facetedsearch->indexProductPrices()
> .../modules/ps_facetedsearch/ps_facetedsearch.php:457
> PrestaShop/Module/FacetedSearch/Hook/Product ->actionProductSave()
> .../modules/ps_facetedsearch/src/Hook/Product.php:40
> PrestaShop/Module/FacetedSearch/HookDispatcher->dispatch()
> .../modules/ps_facetedsearch/src/HookDispatcher.php:105
> Ps_Facetedsearch->__call()
> .../modules/ps_facetedsearch/ps_facetedsearch.php:1229
> HookCore->coreCallHook()
> .../classes/Hook.php:990
> HookCore->callHookOn()
> .../classes/Hook.php:414

----------
**CALLS: 205**
--------
Duration
139.125ms

#### Steps to Reproduce

Saving products with some filters created in the store (its multistore really). 
Module ps_facetedsearch v3.7.1

#### Additional information

* PrestaShop version: 1.7.7.5 and 1.7.7.8
* PHP version: 7.2.34
* mysqlnd 5.0.12-dev
* Apache 2.0
* ps_facetedsearch v3.7.1

**Comment by khouloudbelguith** [comment] 2021-10-08 12:01
Hi @xonsuns,

Thanks for your report.
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #19095
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-10-08 12:01
Duplicate of #19095

**Closed as completed by khouloudbelguith** 2021-10-08 12:01 UTC
Labels: Duplicate

**Comment by AlanReibel** [comment] 2022-08-31 10:07
I have similar problem, when saving BO product takes between 1 and 2 minutes.
Meanwhile I disabled the module but I wonder about what is the real problem here.
It is not the same issue than #19095
PS: 1.7.8.7
ps_facetedsearch 3.8.0
