### ISSUE TITLE
Duplicate product on multistore, issue with images PS8.1

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#34063] opened 2023-09-25 22:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When copying and existing product from one shop context, if you delete the images of the duplicated product, then you're no more able to upload new images.
This because product images are still present in the other shop context.
So to be able to upload images you have to delete images also from this shop context

### Steps to reproduce

1. Open back office and select shop context 1
2. Catalog >> Products >> click on the 3 dots next to a product >> Duplicate
3. Open the product, delete all the images
4. Upload one or more images, save the product and then reload the page
5. You'll will se no images uploaded

**To be able to upload the images correctly on that shop context you should:**
1. Change to shop context 2
2. Delete all the images and save the product
3. It is possible that to save the product to shop context 2 you should fill these 3 fields "Price > Tax excluded", "Minimum quantity for sale" and "Shipping fees > Additional shipping costs"
4. Go back to shop context 1

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-09-26 13:37
Hello @darkf3d3 ,

I can't reproduce your issue in PS 8.1.2 :

**Shop context 1**

https://github.com/PrestaShop/PrestaShop/assets/16019289/1bd1bff2-71dd-45f1-aa47-296925a43388


Am I missing something ?
Could you send a screen record of your case please ?

Waiting for your feedback.

**Comment by darkf3d3** [comment] 2023-09-26 13:45
That's strange, i noticed that when you duplicate the product the label say "Duplicate on current store" while on mine, when I duplicate a product from a shop context it simply say "Duplicate".
PS8.1.0
![image](https://github.com/PrestaShop/PrestaShop/assets/42684711/54613b5e-6aa8-41fa-bf18-544d44713f5c)

**Comment by florine2623** [comment] 2023-10-03 14:02
If you try on the branch 8.1.x, this is what you will find.

**Comment by florine2623** [comment] 2023-10-18 14:27
Hello ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-10-18 14:27 UTC
Labels: Bug, Multistore, 8.1.x, Products Page
