### ISSUE TITLE
Products without descr. and summary issue

### ISSUE THREAD

**Issue by MockoB** [PrestaShop/PrestaShop#33811] opened 2023-09-01 20:45 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I’m not using English in the store I’m working on. When creating a products I’m putting summary and description just in the language fields I’m using on my store. Like j said English is disabled in the front. When saved the product shows in the monitoring page like product without description and summary. If I put the same description for the English translation, the product disappears from the monitoring page.

### Expected behavior

I don’t want the monitoring page to be flooded because obviously all products will be there. And most important, I don’t want to waste time and put description for English also because it is disabled in the front.

### Steps to reproduce

1. Disable English language in your store.
2. Create a product with your native language.
3. Save it and check the monitoring page, if it is in the products list without description and summary.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1.2

**Comment by Hlavtox** [comment] 2023-09-03 12:31
Simmilar issue as here - https://github.com/PrestaShop/PrestaShop/issues/19777.
Another scenario in my comment - https://github.com/PrestaShop/PrestaShop/issues/19777#issuecomment-1131380006

**Comment by sallemiines** [comment] 2023-09-05 13:55
Hello @MockoB 

Thanks @Hlavtox for the tip :wink: 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19777.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by sallemiines** [comment] 2023-09-05 13:56
Duplicate of #19777

**Closed as completed by sallemiines** 2023-09-05 13:55 UTC
Labels: Bug, Duplicate, Invalid
