### ISSUE TITLE
Size limit of "recap" on product sheet

### ISSUE THREAD

**Issue by nicoladze** [PrestaShop/PrestaShop#16344] opened 2019-11-10 16:14 UTC
**Describe the bug**
The size limit of the recap section on a product sheet is reached at 400 characters while it is written under the recap window 800 characters allowed.

**To Reproduce**
1. Go to Catalogue -> Produits
2. Write on "Recapitulatif" more than 400 characters
3. Click on "Sauvegarder"
4. See error "Le champ description_short (Français (French)) est trop long : 400 caractères maximum (en compte actuellement 696)."

**Screenshots**
![screen](https://user-images.githubusercontent.com/47031957/68547021-08e36f00-03dd-11ea-9301-8b5405083391.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-11-11 10:36
Hi @nicoladze,

I did not manage to reproduce the issue with PS1.7.6.1.
The Max size of the short description by default is 800 characters.
You can change it in the BO => Shop Parameters => Product Settings page
![image](https://user-images.githubusercontent.com/16067358/68580588-f4ec4b80-0476-11ea-8920-94ebb8acf271.png)
I attached a screen record
https://drive.google.com/file/d/1mZ3AqVRSK7D7VVTticP5mDgtpXxzCIO2/view
The alert is different in my case.
Thanks to check & feedback.

**Comment by nicoladze** [comment] 2019-11-11 12:16
Hi @khouloudbelguith 

The max size of short description was "0", since I put "800", the problem is solved. 

Thank you

**Comment by khouloudbelguith** [comment] 2019-11-11 12:17
@nicoladze, thanks for your feedback.
Since it is fixed.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-11 12:17 UTC
Labels: Bug, BO, No change required, 1.7.6.1
