### ISSUE TITLE
Display unavailable product attributes on the product page

### ISSUE THREAD

**Issue by IranDec** [PrestaShop/PrestaShop#18926] opened 2020-04-30 22:01 UTC
Hi
in Shop Parameters> Product Settings
when this feature is on
Display unavailable product attributes on the product page

in front page if a product has 2 different type combination such as 1. size 2. color

the system automatically hiding that size are out of stock but can't do it that for the second combination then customers cant choose their own selection.

* PrestaShop version: 1.7.6.4 ( Persian panel )
* PHP version: 7.2

**Comment by Progi1984** [comment] 2020-05-04 14:40
We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #9948.

To be informed when it’s fixed, please subscribe to the issue above.

Thank you!

**Comment by florine2623** [comment] 2020-05-04 14:40
Hi @IranDec ,

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/16952 ?

Thanks!

**Comment by Progi1984** [comment] 2020-05-04 14:40
Duplicate of #9948.

**Comment by florine2623** [comment] 2020-06-25 10:02
Hi @IranDec ,
Sorry for the late answer.

I can't reproduce your issue.
Please check the screenshots below :
![Capture d’écran 2020-06-25 à 12 01 24](https://user-images.githubusercontent.com/16019289/85699254-a759e180-b6db-11ea-8258-a4d92bd91f06.png)
![Capture d’écran 2020-06-25 à 12 00 36](https://user-images.githubusercontent.com/16019289/85699272-ab85ff00-b6db-11ea-943b-1859c3ae8ff2.png)
![Capture d’écran 2020-06-25 à 12 01 01](https://user-images.githubusercontent.com/16019289/85699279-ade85900-b6db-11ea-9818-a0d6e41ad895.png)

**Comment by IranDec** [comment] 2020-06-25 11:26
@florine2623 
Hi
pls change your admin panel language to Persian then pls try to add more attributes like some of them with 0 qty and some of them with more than 1 qty so u will see the problem

**Comment by florine2623** [comment] 2020-06-25 13:54
There is indeed an issue with Persian language in the BO.
I reproduce the issue (in screen record) in both PS 1.7.6.5 and 1.7.7.0.

The stock won't save properly. But is is not like what you explained, but it seems related.
Could you send me a screen record of your issue ?
Can you check if your issue does not come from stocks that have disappeared ?

I want to compare it to mine :
https://drive.google.com/file/d/1WxFISDNHb-FEMvwXnczJgEMVL4t78YlK/view

In English there's no issue :
https://drive.google.com/file/d/1Z5WVNyeJZ7GQouO8GPiEaTphNYEllRr0/view

**Comment by IranDec** [comment] 2020-06-25 14:43
@florine2623 
Hi
that's the problem is one of my problems (your video). additionally pls check this video to understand my second problem too.
https://gofile.io/d/vUHfVq

I couldn't change attribute of my order after I enable that feature 
and also some of them was out of stock but the system was showing them

**Comment by florine2623** [comment] 2020-06-25 15:28
Regarding your video :
Have you checked if you couldn't add the product to your cart because the stock disappeared ?
>I couldn't change attribute of my order after I enable that feature

Let focus on one issue at a time please, or open a new issue if needed.

>and also some of them was out of stock but the system was showing them

I can't reproduce that issue

**Comment by prestascott** [comment] 2020-07-15 08:41
Hello @IranDec,

Since we had no news from you for 20 days, I'll close this ticket not to clutter up the backlog, but note that you can always create a new one if further information pops up.

Thank you!

**Comment by IranDec** [comment] 2021-05-21 17:57
Hi @prestascott 
today I update my Prestashop ver to 1.7.7.4 but the problem still exists.
is it possible to check my video? 
this is my main problem that cause i create this issue
"I couldn't change the attribute of my order after I enable that feature"
"Let focus on one issue at a time please, or open a new issue if needed."

Thank you

**Comment by prestascott** [comment] 2021-05-24 07:41
Hello @IranDec,

Can you send your video here please? The upload from your previous link doesn't exist anymore. 

Thanks :)

**Comment by hibatallahAouadni** [comment] 2021-11-15 09:23
Hello @IranDec 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-11-15 09:23 UTC
Labels: Bug, Product settings, Combinations, 1.7.6.4, Invalid
