### ISSUE TITLE
Product condition 'new' is missing in FO

### ISSUE THREAD

**Issue by dominiqueblanc** [PrestaShop/PrestaShop#32212] opened 2023-04-20 06:46 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,

According to the case #30916, fixed by the case #31148, there is a misunderstanding I guess.

'new' has different meanings in other countries, as a product 'just added' or 'now available' vs. new as a condition.

It has been decided to move 'new' from `Shop.Theme.Catalog` to `Admin.Global` to make it appears correctly in BO.

Now if 'new' is selected in BO, how to make it appears in FO ?

In 8.0.3 version, the condition 'new' in FO is showing what appears on the flag, 'new' as a new product 'just added' (=Nouveau).
Therefore, it shows 'Nouveau' as a condition and that's wrong.

The expected condition is 'Neuf', accordingly the selected condition in BO ('Neuf')
![image](https://user-images.githubusercontent.com/129511652/232204374-e9aaafac-da39-4af7-b6cc-49ea8f904af6.png)

Thank you in advance to fix this please.
Best regards

### Expected behavior
Product page, back office :

'New' in Admin.Catalog.Feature
'Used' in Admin.Catalog.Feature
'Refurbished' in Admin.Catalog.Feature

New label in the product listing, front office:
'New' in Shop.Theme.Global

New in the product page, front office (condition):

'New' in Shop.Theme.Catalog
'Used' in Shop.Theme.Catalog
'Refurbished' in Shop.Theme.Catalog

### Steps to reproduce

1. Goto BO -> Catalog -> Product -> demo_21 (or any) -> options -> condition
2. Active the condition case to be shown in FO -> select 'new' in french (=Neuf)
3. See the condition of the product in FO (=Nouveau) and not (=Neuf)

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0

**Comment by Hlavtox** [comment] 2023-04-20 09:56
Because the domain for `New` condition stayed the same in FO, so https://github.com/PrestaShop/PrestaShop/pull/31148 actually did not fix much.
 https://github.com/PrestaShop/PrestaShop/blob/b15b9700a51334bccca80f9f4213c6dff5f8dae9/src/Adapter/Presenter/Product/ProductLazyArray.php#L243

**Comment by Julievrz** [comment] 2023-04-20 10:11
Hello, 

In the back office, "New" means "Brand new" as opposed to "Used" and "Refurbished". 

In the front office (in the product listing), "New" means "New product/recently added"

But you're right, "New" is also used within the product page in the front office to indicate the product's condition. So, in this case, it means "brand new" again.

So maybe a solution could be:

**Product page, back office :** 

'New' in Admin.Catalog.Feature
'Used' in Admin.Catalog.Feature
'Refurbished' in Admin.Catalog.Feature

**New label in the product listing, front office:** 
'New' in Shop.Theme.Global

**New in the product page, front office (condition):**

'New' in Shop.Theme.Catalog
'Used' in Shop.Theme.Catalog
'Refurbished' in Shop.Theme.Catalog 

Wdyt?

**Comment by AureRita** [comment] 2023-04-20 11:08
Hi @DomShop 

I reproduce the issue with PrestaShop version 8.0.2 as you can see : 

[Untitled_ Apr 20, 2023 1_03 PM.webm](https://user-images.githubusercontent.com/100699445/233347954-5ba7499b-a92b-43ef-87d3-a1d793ceafbe.webm)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Closed as completed** 2023-08-10 09:54 UTC
Labels: Bug, Minor, FO, Translations, Regression, PR available, Verified, 8.0.2
