### ISSUE TITLE
Unable to delete item from cart when added from BO on existing paid order

### ISSUE THREAD

**Issue by Ludhiel** [PrestaShop/PrestaShop#23038] opened 2021-01-28 13:58 UTC
#### Describe the bug

When I add a product to an existing paid order, the customer have a cart with the product in it and cannot remove it

#### Expected behavior

No cart added to the customer, or at least be able to remove it

#### Steps to Reproduce

1. Create an order with a product  and pay it In FO with a registered account
2. Go to the BO, get the order and add a product with combination/variant
3. Go back to the FO with the customer account, the product added in BO is in the cart and cannot be remove and no error displayed

#### Additional information

* PrestaShop version: ~~1.7.6.9~~ 1.7.6.7 (edited)
* PHP version: N/A

The error is produced by AdminOrdersController.php when the product is added in the ajaxProcessAddProductOnOrder function
a cart is created and the product is added with  $cart->updateQty() and the combination/id_attribute id is added to the customization_id that in my case does not exist. So when the customer want to delete the product, the SQL request does not find a product with this customization_id (JOIN in SQL return nothing)

I have edited the function to partially correct the bug by removing the customization_id in the updateQty in  AdminOrdersController.php, but it create a cart (necessary to check cart rule) and attache it to the customer when the order is finished.

**Comment by hibatallahAouadni** [comment] 2021-01-28 16:03
Hello @Ludhiel 

How did you add the product to the Order, cause when I tried to add the product, I get an error :confused: 
See the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/106164768-a5cd2c00-618a-11eb-8a8f-7c3fba9ccb68.png)

Please check and feedback.
Thanks!

**Comment by Ludhiel** [comment] 2021-01-28 16:46
Hi,

After checking the prestashop version is 1.7.6.7

I have no error, in my test I used payment by wire and let it in wanting.

My problem come from this,  as the attribure_id is put to customization field too withotu creating a customization in the corresponding table (check the commented line).
![image](https://user-images.githubusercontent.com/32941352/106169487-b633d580-618f-11eb-9223-ae78f072d07f.png)
(AdminOrdersController.php)

As the deletion of product in cart (class cart.php) check with the customization_id to delete the customization before deleting the product.

My client add product to customer order for diverses reasons and never have an error, you can evn add a product which does not have stock

**Comment by hibatallahAouadni** [comment] 2021-02-01 20:47
Hello @Ludhiel 

> I have no error, in my test I used payment by wire and let it in wanting.

Could you please specify the order status? is it **Payment accepeted** or **Waiting for payment**.
Please check and feedback.

Thanks!

**Comment by Ludhiel** [comment] 2021-02-03 13:05
Hello @hibatallahAouadni 

The status is "En attente de virement bancaire" in french, so something like waiting for wire payment.

**Comment by hibatallahAouadni** [comment] 2021-02-03 14:37
Hello @Ludhiel 

Well I think you said it's **"on existing paid order"** but it seems your order is not paid.
Cause as I said before it's impossible to add a product to a paid order :wink: 
Now, I tried to follow these steps:

1. Login as Customer in FO
2. add a product in your cart 
3. Choose **Bank wire** as payment method
4. Validate your order
5. your order 's status is **Awaiting bank wire payment**
6. BO>SELL>Orders>Orders
7. edit the last order
8. Scroll down to Products block
9. Click on **Add a product** button
10. Add another product, click on **Add** button
11. Check you FO
12. There's no added product in the cart => OK

Please check my screen record below and feedback:

https://drive.google.com/file/d/1I7eNg0pu6Q7n7aonJ8eYW73o0SneaevN/view

Thanks!

**Comment by Ludhiel** [comment] 2021-02-03 14:57
Hi @hibatallahAouadni ,
Yes when I test i use a wire payment because its simplier. My customer says he has the problem on completed order. Probably some misunderstanding between him and me.

Your workflow is the correct one. But does the product you add in BO has a combination ?
Combination as:
` $combination = new Combination($product_informations['product_attribute_id']);`

Because that what is causing me problem when the updateQty method is used
` $update_quantity = $cart->updateQty(
            $product_informations['product_quantity'],
            $product->id,
            isset($product_informations['product_attribute_id']) ? $product_informations['product_attribute_id'] : null,
            isset($combination) ? $combination->id : null, // <== This is the problem
            'up',
            0,
            new Shop($cart->id_shop)
        );`

This line in AdminOrdersController.php add the combination in customization field, see the definition of updateQty() in cart.php
This now customization does not exist and you cannot delete the cart.

I did not find why the temporary cart is affected to the customer in FO. If the cart was not added to the customer there is no problem.

**Comment by hibatallahAouadni** [comment] 2021-02-03 15:08
Hello @Ludhiel 

See the attached screen record below, i just add a product with combination and update is quantity:

https://drive.google.com/file/d/1Fhctk81XpjWW5pMCMYDsUx8cGlSXLYC6/view

Please check and feedback.
Thanks!

**Comment by Ludhiel** [comment] 2021-02-03 15:11
Hello @hibatallahAouadni 

In your DB, the temporary cart that is used when you add the product in BO is present? Maybe my problem is that it is not deleted/added to the customer.

Thanks for your help

**Comment by hibatallahAouadni** [comment] 2021-02-03 15:37
Hello @Ludhiel 

Thanks for your feedback.
We are aware of this issue, it is already fixed with PS1.7.7.1. This issue is a duplicate of #21808.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-03 15:37
Duplicate of #21808

**Closed as completed by hibatallahAouadni** 2021-02-03 15:37 UTC
Labels: Bug, BO, Duplicate, Order, Shopping carts, 1.7.6.7
