### ISSUE TITLE
500 internal Server Error

### ISSUE THREAD

**Issue by Marwazeinoo88** [PrestaShop/PrestaShop#11188] opened 2018-10-30 10:54 UTC
**Describe the bug**
Hi, since this morning i can't log to my BO, it's loading and loading..Then i have this error : 
**Internal Server Error**
**The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Apache Server at monsite.fr Port 443**

**console log:**
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

**Screenshots**
![intenal server error](https://user-images.githubusercontent.com/43037924/47713286-37f7ca00-dc3a-11e8-8c5b-97e4839ec892.PNG)

**Additionnal information**
PrestaShop version: 1.7.3.0
PHP version: 7.1.20
version Apache/2.2.2

**Comment by khouloudbelguith** [comment] 2018-10-30 11:01
Hi @Marwazeinoo88,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Marwazeinoo88** [comment] 2018-10-30 11:51
**host**: phpnet
**Console log:**
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

**SERVEUR LOG ERROR:**
[Tue Oct 30 06:16:17 2018] [error] (9)Bad file descriptor: apr_socket_accept: (client socket)
**Error.log**
[Tue Oct 30 12:17:12 2018] [warn] [client 41.230.73.195] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server
[Tue Oct 30 12:17:12 2018] [error] [client 41.230.73.195] Premature end of script headers: index.php

INFORMATIONS : Informations sur votre serveur Linux #1 SMP Thu Jan 4 16:43:57 MSK 2018 x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.1.20
Limite de mémoire : 256M
Temps maximal d'exécution : 80
Taille max. pour envoi de fichiers : 200M
Version de PrestaShop : 1.7.3.0

**Comment by khouloudbelguith** [comment] 2018-10-30 12:58
Hi @Marwazeinoo88,

About this error[ [error] (9)Bad file descriptor: apr_socket_accept: (client socket)], it is a server issue, maybe you need to upgrade the apache package, you need to check your host.
About the Error.log, sometimes when migrating sites are switching between mod_php and FCGId permissions can get mangled which cause errors such as:
(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server
when running in FCGId mode.
Here's a solution to be ass follows.

1. Go to /home/sitename/fcgi-bin
2. Use the following command to reset the immutable flag chattr -i php5.fcgi
3. Then delete the /home/sitename/etc and /home/sitename/fcgi-bin directories (making sure that anything that's not php related in etc is saved)
4. Using virtualmin switch back to apache mod_php mode and then back to FCGId mode. The site should now work Don't forget to chown any files/directories in public_html that were apache to: Note that these are both usually the sitename.

PS: for more details about this issue, you need to check it with your host.

Thanks to check with the host provider & feedback.

**Comment by khouloudbelguith** [comment] 2018-11-30 13:55
Hi @Marwazeinoo88,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-30 13:55 UTC
Labels: Bug, BO, No change required
