### ISSUE TITLE
Error 403 on "translations/cldr/datas" files with nginx

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#12209] opened 2019-01-18 10:55 UTC
**Describe the bug**

On fresh install of PS 1.7.4.3 on nginx [with this config](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist) when I'm going to a product page I have some 403 errors into Symfony debugger (cf screenshot), and into my server logs:

> access forbidden by rule, client: 192.168.1.1, request: "GET /translations/cldr/datas/supplemental/plurals.json HTTP/1.1"
> access forbidden by rule, client: 192.168.1.1, request: "GET /translations/cldr/datas/supplemental/currencyData.json HTTP/1.1"
> access forbidden by rule, client: 192.168.1.1, request: "GET /translations/cldr/datas/supplemental/likelySubtags.json HTTP/1.1"
> access forbidden by rule, client: 192.168.1.1, request: "GET /translations/cldr/datas/fr-FR/currencies.json HTTP/1.1"
> access forbidden by rule, client: 192.168.1.1, request: "GET /translations/cldr/datas//main/fr-FR/numbers.json HTTP/1.1"

Similar issue was reported on forge but not resolved: [#BOOM-5489](http://forge.prestashop.com/browse/BOOM-5489). And not a duplicate of [#BOOM-3920](http://forge.prestashop.com/browse/BOOM-3920) that mentioned 500 errors, our are 403.

Not a duplicate of #11039 because this issue mentioned Apache.

**To Reproduce**

1. Install a fresh PrestaShop (v1.7.4.3) with nginx
2. Configure nginx [with this config](https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist)
3. Go to admin > catalogue > products
4. Choose a product and click
5. Look at Symfony debugger

_Disable Apache MultiViews_ set to NO
_Disable Apache mod_security_ set to NO

Issued with french language pack but [same in spanish](https://www.prestashop.com/forums/topic/909253-error-403-translationscldrdatas/)

**Screenshots**

![translation-403](https://user-images.githubusercontent.com/7419525/51382450-26c2a900-1b17-11e9-9c23-3bdacc5bcfb8.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 5.6.38
Nginx: 1.6.2
MariaDB: 10.0.36

**Comment by khouloudbelguith** [comment] 2019-01-18 11:19
Hi @Klemart3D,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1QNJFUh_cqvRzUHMCXnMe4tBCXpOn_M5b/view
here's my nginx configuration
```
server {
	listen   80; ## listen for ipv4; this line is default and implied
	listen   [::]:80 default ipv6only=on; ## listen for ipv6

	root /var/www/html;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name _;
	
	# Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
	sendfile off;

	# Add stdout logging
	# Add stdout logging
        error_log /var/log/nginx/error.log info;
        access_log /var/log/nginx/access.log;

        # Add option for x-forward-for (real ip when behind elb)
        #real_ip_header X-Forwarded-For;
        #set_real_ip_from 172.16.0.0/12;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
		try_files $uri $uri/ /1750/index.php?$args;
		# Images
                rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
                rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
                rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
                rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
		# AlphaImageLoader for IE and fancybox
        rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

        # Web service API
        rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

        # Installation sandbox
        rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
	}
	# Gzip Settings, convert all types.
        gzip on;
        gzip_vary on;
        gzip_proxied any;

        # Can be enhance to 5, but it can slow you server
        # gzip_comp_level    5;
        # gzip_min_length    256;

        gzip_types
            application/atom+xml
            application/javascript
            application/json
            application/ld+json
            application/manifest+json
            application/rss+xml
            application/vnd.geo+json
            application/vnd.ms-fontobject
            application/x-font-ttf
            application/x-web-app-manifest+json
            application/xhtml+xml
            application/xml
            font/opentype
            image/bmp
            image/svg+xml
            image/x-icon
            text/cache-manifest
            text/css
            text/plain
            text/vcard
            text/vnd.rim.location.xloc
            text/vtt
            text/x-component
            text/x-cross-domain-policy;

        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
	# Symfony controllers
        location /1750/admin-dev/ {                                  # [REQUIRED EDIT] the name of your admin directory
            if (!-e $request_filename) {
                rewrite ^/.*$ /1750/admin-dev/index.php last;   # [REQUIRED EDIT] the name of your admin directory
            }
        }

        # Cloudflare / Max CDN fix
        location ~* \.(eot|otf|ttf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin *;
        }

        # Do not save logs for these
        location = /1750/favicon.ico {
            log_not_found off;
            access_log off;
        }
        location = /1750/robots.txt {
            auth_basic off;
            allow all;
            log_not_found off;
            access_log off;
        }


	error_page 404 /1750/index.php?controller=404;

        location ^~ /sad.svg {
            alias /var/www/errors/sad.svg;
            access_log off;
        }
        location ^~ /twitter.svg {
            alias /var/www/errors/twitter.svg;
            access_log off;
        }
        location ^~ /gitlab.svg {
            alias /var/www/errors/gitlab.svg;
            access_log off;
        }

	# pass the PHP scripts to FastCGI server listening on socket
	#
	location ~ \.php$ {
                try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_index index.php;
		include fastcgi_params;
	}

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|tiff|ttf|svg)$ {
                expires           5d;
        }

	# deny access to . files, for security
	#
	location ~ /\. {
    		log_not_found off; 
    		deny all;
	}
        
	location ^~ /.well-known {
                allow all;
                auth_basic off;
        }

}

```
Thanks!

**Comment by Klemart3D** [comment] 2019-01-18 13:05
Hi @khouloudbelguith,
It seems you don't have the same [nginx config used in official repo for 1.7.5.x](https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/docs/server_config/nginx.conf.dist)
Can you add the part from line 137 to 140?
```
# Source code directories
location ~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor|var)/ {
    deny all;
}
```
In my case, if I remove "translations" directory from this previous rule, it works fine (no more 403 errors).

**Comment by khouloudbelguith** [comment] 2019-01-18 13:30
@Klemart3D, thanks for your feedback.
After adding those code line.
No errors are displayed.
https://drive.google.com/file/d/1mKpQpyPOBCydg9XFSgbKUtK_ShqPIIBU/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-18 08:17
Hi @Klemart3D,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-18 08:17 UTC
Labels: BO, No change required, 1.7.4.3
