### ISSUE TITLE
item quantity highlighted in an order

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26722] opened 2021-11-23 23:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![image](https://user-images.githubusercontent.com/62474824/143146527-7fd843d5-ca75-401a-adc7-723f7380fb53.png)
![image](https://user-images.githubusercontent.com/62474824/143146535-36aa23e9-fd84-41d1-8a85-2b6d1a9857a1.png)

when there is an individual quantity, the quantity is not marked
However, when there is more than 1 item, if it is remarked

I'm not sure it's a bug or a desired behavior

### Expected behavior

**I'm not sure it's a bug or a desired behavior**

### Steps to reproduce

see orders

### PrestaShop version(s) where the bug happened

1.7.7.3

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment] 2021-11-24 12:32
@alfonsolr09 That's 99% desired behavior and not a bug. And I think `{% if product.quantity > 0 %}` is always true no? :-)

**Comment by alfonsolr09** [comment] 2021-11-24 13:03
I know, but i dont know why it is not remarked ...

**Comment by Hlavtox** [comment] 2021-11-24 13:08
I think it was done so you see that you have more than 1 piece.

It happens, many times when customer orders more than 1 piece of product, people who pack orders just send 1 by mistake... 👍😄

**Comment by hibatallahAouadni** [comment] 2021-11-24 14:43
Hello @alfonsolr09 

That's indeed the expected behavior (the same as PS1.7.6.7 and older versions).
Close the issue as it's not a bug.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-11-24 14:43 UTC
Labels: Bug, PR available, Invalid

**Comment by alfonsolr09** [comment] 2021-11-24 14:46
> Hello @alfonsolr09 
> 
> That's indeed the expected behavior (the same as PS1.7.6.7 and older versions).
> Close the issue as it's not a bug.
> 
> Thanks!

why is it a desired behavior?

**Comment by hibatallahAouadni** [comment] 2021-11-24 16:03
Ping @alfonsolr09 check @Hlavtox comment:

> I think it was done so you see that you have more than 1 piece.
>
> It happens, many times when customer orders more than 1 piece of product, people who pack orders just send 1 by mistake
