### ISSUE TITLE
BO - Character Error in Order Page - Message from customer

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#15489] opened 2019-09-10 13:47 UTC
Version - 1.7.6
Language - PT

Text in Customer message is not correct

![Capturar](https://user-images.githubusercontent.com/54105234/64619335-d4056c80-d3d9-11e9-8854-ee7daa0f5f70.JPG)

**Comment by khouloudbelguith** [comment] 2019-09-10 13:52
Hi @Borgas,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9726
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-10 13:52
Duplicate of #9726

**Closed as completed by khouloudbelguith** 2019-09-10 13:52 UTC
Labels: Duplicate
