### ISSUE TITLE
Products not visible in BO, then deleted after a week

### ISSUE THREAD

**Issue by LucasVollebergh** [PrestaShop/PrestaShop#18378] opened 2020-03-31 08:43 UTC
Hi,

I use the newest version of Prestashop 1.7.6.4 and I'm facing a big issue:
Not sure this has to do with this problem but I upload and sync all my products with webservice.

When I upload all my products, they are visible in the store but not under products in the BO.
I am able to see them in under brands. 

But now a week after the products are uploaded all those products are gone...
I'm here to provide all information you need.

**Comment by khouloudbelguith** [comment] 2020-03-31 08:52
Hi @LucasVollebergh,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.4.
Here is an example of an xml sent to add a new product via WS
```
<prestashop>
<product>
  <id/>
  <state>1</state>
  <id_category_default>2</id_category_default>
  <active>1</active>
  <advanced_stock_management>1</advanced_stock_management>
  <associations>
    <categories>
      <category><id>2</id></category>
    </categories>
  </associations>
  <reference>boom</reference>
  <name>
  <language id="1">product_success_add</language></name>
  <price>100</price>
  <id_shop_default>1</id_shop_default>
  <low_stock_alert>0</low_stock_alert>
  <link_rewrite>abc</link_rewrite>
  <show_price>1</show_price>
  <minimal_quantity>1</minimal_quantity>
  <available_for_order>1</available_for_order>
</product>
</prestashop>
```
Also, you can follow our documentation: http://doc.prestashop.com/display/PS16/Using+the+PrestaShop+Web+Service
You can found some examples in our GitHub repository: https://github.com/PrestaShop/PrestaShop-webservice-lib
Thanks to check and feedback.

**Comment by LucasVollebergh** [comment] 2020-03-31 14:12
Hi,

Thanks for your quick reply.
It's really weird that we have this problem because it all works fine in 1.6, also, there is no product list available in the backend...
Here our steps:

First we load a blanco scheme to fill in: /api/products?schema=blank (rmGet) 
We get this:

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
       <id></id>
       <id_manufacturer></id_manufacturer>
       <id_supplier></id_supplier>
       <id_category_default></id_category_default>
       <new></new>
       <cache_default_attribute></cache_default_attribute>
       <id_default_image></id_default_image>
       <id_default_combination></id_default_combination>
       <id_tax_rules_group></id_tax_rules_group>
       <position_in_category></position_in_category>
       <type></type>
       <id_shop_default></id_shop_default>
       <reference></reference>
       <supplier_reference></supplier_reference>
       <location></location>
       <width></width>
       <height></height>
       <depth></depth>
       <weight></weight>
       <quantity_discount></quantity_discount>
       <ean13></ean13>
       <isbn></isbn>
       <upc></upc>
       <cache_is_pack></cache_is_pack>
       <cache_has_attachments></cache_has_attachments>
       <is_virtual></is_virtual>
       <state></state>
       <additional_delivery_times></additional_delivery_times>
       <delivery_in_stock><language id="1"></language></delivery_in_stock>
       <delivery_out_stock><language id="1"></language></delivery_out_stock>
       <on_sale></on_sale>
       <online_only></online_only>
       <ecotax></ecotax>
       <minimal_quantity></minimal_quantity>
       <low_stock_threshold></low_stock_threshold>
       <low_stock_alert></low_stock_alert>
       <price></price>
       <wholesale_price></wholesale_price>
       <unity></unity>
       <unit_price_ratio></unit_price_ratio>
       <additional_shipping_cost></additional_shipping_cost>
       <customizable></customizable>
       <text_fields></text_fields>
       <uploadable_files></uploadable_files>
       <active></active>
       <redirect_type></redirect_type>
       <id_type_redirected></id_type_redirected>
       <available_for_order></available_for_order>
       <available_date></available_date>
       <show_condition></show_condition>
       <condition></condition>
       <show_price></show_price>
       <indexed></indexed>
       <visibility></visibility>
       <advanced_stock_management></advanced_stock_management>
       <date_add></date_add>
       <date_upd></date_upd>
       <pack_stock_type></pack_stock_type>
       <meta_description><language id="1"></language></meta_description>
       <meta_keywords><language id="1"></language></meta_keywords>
       <meta_title><language id="1"></language></meta_title>
       <link_rewrite><language id="1"></language></link_rewrite>
       <name><language id="1"></language></name>
       <description><language id="1"></language></description>
       <description_short><language id="1"></language></description_short>
       <available_now><language id="1"></language></available_now>
       <available_later><language id="1"></language></available_later>
<associations>
<categories>
       <category>
       <id></id>
       </category>
</categories>
<images>
       <image>
       <id></id>
       </image>
</images>
<combinations>
       <combination>
       <id></id>
       </combination>
</combinations>
<product_option_values>
       <product_option_value>
       <id></id>
       </product_option_value>
</product_option_values>
<product_features>
       <product_feature>
       <id></id>
       <id_feature_value></id_feature_value>
       </product_feature>
</product_features>
<tags>
       <tag>
       <id></id>
       </tag>
</tags>
<stock_availables>
       <stock_available>
       <id></id>
       <id_product_attribute></id_product_attribute>
       </stock_available>
</stock_availables>
<accessories>
       <product>
       <id></id>
       </product>
</accessories>
<product_bundle>
       <product>
       <id></id>
       <id_product_attribute></id_product_attribute>
       <quantity></quantity>
       </product>
</product_bundle>
</associations>
</product>
</prestashop>

Then, we post the following:

<?xml version="1.0"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
<id></id>
<id_manufacturer>3</id_manufacturer>
<id_supplier/>
<id_category_default>17</id_category_default>
<new/>
<cache_default_attribute/>
<id_default_image/>
<id_default_combination/>
<id_tax_rules_group>1</id_tax_rules_group>
<position_in_category/>
<type/>
<id_shop_default/>
<reference>15651</reference>
<supplier_reference/>
<location/>
<width/>
<height/>
<depth/>
<weight/>
<quantity_discount/>
<ean13/>
<isbn/>
<upc/>
<cache_is_pack/>
<cache_has_attachments/>
<is_virtual/>
<state/>
<additional_delivery_times/>
<delivery_in_stock>
<language id="1"/>
</delivery_in_stock>
<delivery_out_stock>
<language id="1"/>
</delivery_out_stock>
<on_sale/>
<online_only/>
<ecotax/>
<minimal_quantity/>
<low_stock_threshold/>
<low_stock_alert/>
<price>82.6033</price>
<wholesale_price/>
<unity/>
<unit_price_ratio/>
<additional_shipping_cost/>
<customizable/>
<text_fields/>
<uploadable_files/>
<active>1</active>
<redirect_type/>
<id_type_redirected/>
<available_for_order>1</available_for_order>
<available_date/>
<show_condition/>
<condition/>
<show_price>1</show_price>
<indexed/>
<visibility/>
<advanced_stock_management/>
<date_add/>
<date_upd/>
<pack_stock_type/>
<meta_description>
<language id="1"/>
</meta_description>
<meta_keywords>
<language id="1"/>
</meta_keywords>
<meta_title>
<language id="1"/>
</meta_title>
<link_rewrite>
<language id="1">BullBoxer-NA_15651</language>
</link_rewrite>
<name>
<language id="1">BullBoxer N/A</language>
</name>
<description>
<language id="1"/>
</description>
<description_short>
<language id="1"/>
</description_short>
<available_now>
<language id="1"/>
</available_now>
<available_later>
<language id="1"/>
</available_later>
<associations>
<categories>
<category><id>16</id></category>
<category><id>17</id></category>
<category><id>18</id></category>
<category><id>2</id></category>
<category><id>24</id></category>
</categories>
<images>
<image>
<id/>
</image>
</images>
<combinations>
<combination>
<id/>
</combination>
</combinations>
<product_option_values>
<product_option_value>
<id/>
</product_option_value>
</product_option_values>
<product_features>
<product_feature>
<id>1</id>
<id_feature_value>1</id_feature_value>
</product_feature>
<product_feature>
<id>2</id>
<id_feature_value>109</id_feature_value>
</product_feature>
</product_features>
<tags>
<tag>
<id/>
</tag>
</tags>
<stock_availables>
<stock_available>
<id/>
<id_product_attribute/>
</stock_available>
</stock_availables>
<accessories>
<product>
<id/>
</product>
</accessories>
<product_bundle>
<product>
<id/>
<id_product_attribute/>
<quantity/>
</product>
</product_bundle>
</associations>
</product>
</prestashop>
```

Afterwards we get the Id back from Prestashop:

`<?xml version="1.0"?> <prestashop xmlns:xlink="http://www.w3.org/1999/xlink"><product><id><![CDATA[577]]></id><id_manufacturer xlink:href="https://www.hipsko.com/api/manufacturers/3"><![CDATA[3]]></id_manufacturer><id_supplier/><id_category_default xlink:href="https://www.hipsko.com/api/categories/17"><![CDATA[17]]></id_category_default><new/><cache_default_attribute/><id_default_image notFilterable="true"/><id_default_combination notFilterable="true"/><id_tax_rules_group xlink:href="https://www.hipsko.com/api/tax_rule_groups/1"><![CDATA[1]]></id_tax_rules_group><position_in_category notFilterable="true"><![CDATA[0]]></position_in_category><manufacturer_name notFilterable="true"><![CDATA[BullBoxer]]></manufacturer_name><quantity notFilterable="true"/><type notFilterable="true"><![CDATA[simple]]></type><id_shop_default><![CDATA[1]]></id_shop_default><reference><![CDATA[15651]]></reference><supplier_reference/><location/><width/><height/><depth/><weight/><quantity_discount/><ean13/><isbn/><upc/><cache_is_pack/><cache_has_attachments/><is_virtual/><state/><additional_delivery_times/><delivery_in_stock><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></delivery_in_stock><delivery_out_stock><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></delivery_out_stock><on_sale/><online_only/><ecotax/><minimal_quantity/><low_stock_threshold/><low_stock_alert/><price><![CDATA[82.6033]]></price><wholesale_price/><unity/><unit_price_ratio/><additional_shipping_cost/><customizable/><text_fields/><uploadable_files/><active><![CDATA[1]]></active><redirect_type/><id_type_redirected/><available_for_order><![CDATA[1]]></available_for_order><available_date/><show_condition/><condition><![CDATA[new]]></condition><show_price><![CDATA[1]]></show_price><indexed/><visibility><![CDATA[both]]></visibility><advanced_stock_management/><date_add><![CDATA[2020-03-31 14:49:28]]></date_add><date_upd><![CDATA[2020-03-31 14:49:28]]></date_upd><pack_stock_type/><meta_description><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></meta_description><meta_keywords><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></meta_keywords><meta_title><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></meta_title><link_rewrite><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[BullBoxer-NA_15651]]></language></link_rewrite><name><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[BullBoxer N/A]]></language></name><description><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></description><description_short><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></description_short><available_now><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></available_now><available_later><language id="1" xlink:href="https://www.hipsko.com/api/languages/1"><![CDATA[]]></language></available_later><associations><categories nodeType="category" api="categories"><category xlink:href="https://www.hipsko.com/api/categories/2"><id><![CDATA[2]]></id></category></categories><images nodeType="image" api="images"/><combinations nodeType="combination" api="combinations"/><product_option_values nodeType="product_option_value" api="product_option_values"/><product_features nodeType="product_feature" api="product_features"><product_feature xlink:href="https://www.hipsko.com/api/product_features/1"><id><![CDATA[1]]></id><id_feature_value xlink:href="https://www.hipsko.com/api/product_feature_values/1"><![CDATA[1]]></id_feature_value></product_feature><product_feature xlink:href="https://www.hipsko.com/api/product_features/2"><id><![CDATA[2]]></id><id_feature_value xlink:href="https://www.hipsko.com/api/product_feature_values/109"><![CDATA[109]]></id_feature_value></product_feature></product_features><tags nodeType="tag" api="tags"><tag xlink:href="https://www.hipsko.com/api/tags/0"><id><![CDATA[0]]></id></tag></tags><stock_availables nodeType="stock_available" api="stock_availables"><stock_available xlink:href="https://www.hipsko.com/api/stock_availables/16041"><id><![CDATA[16041]]></id><id_product_attribute><![CDATA[0]]></id_product_attribute></stock_available></stock_availables><accessories nodeType="product" api="products"/><product_bundle nodeType="product" api="products"/></associations></product></prestashop>`

And last our pictures and discounts, combinations, and stock is uploaded.
I don't se any difference between 1.6 and 1.7 so it should work.

Here an example of a product who is uploaded:

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
<id>
<![CDATA[ 576 ]]>
</id>
<id_manufacturer xlink:href="https://www.hipsko.com/api/manufacturers/58">
<![CDATA[ 58 ]]>
</id_manufacturer>
<id_supplier>
<![CDATA[ 0 ]]>
</id_supplier>
<id_category_default xlink:href="https://www.hipsko.com/api/categories/78">
<![CDATA[ 78 ]]>
</id_category_default>
<new/>
<cache_default_attribute>
<![CDATA[ 15553 ]]>
</cache_default_attribute>
<id_default_image xlink:href="https://www.hipsko.com/api/images/products/576/3504" notFilterable="true">
<![CDATA[ 3504 ]]>
</id_default_image>
<id_default_combination xlink:href="https://www.hipsko.com/api/combinations/15553" notFilterable="true">
<![CDATA[ 15553 ]]>
</id_default_combination>
<id_tax_rules_group xlink:href="https://www.hipsko.com/api/tax_rule_groups/1">
<![CDATA[ 1 ]]>
</id_tax_rules_group>
<position_in_category notFilterable="true">
<![CDATA[ 11 ]]>
</position_in_category>
<manufacturer_name notFilterable="true">
<![CDATA[ Woly ]]>
</manufacturer_name>
<quantity notFilterable="true">
<![CDATA[ 0 ]]>
</quantity>
<type notFilterable="true">
<![CDATA[ simple ]]>
</type>
<id_shop_default>
<![CDATA[ 1 ]]>
</id_shop_default>
<reference>
<![CDATA[ 19156 ]]>
</reference>
<supplier_reference/>
<location/>
<width>
<![CDATA[ 0.000000 ]]>
</width>
<height>
<![CDATA[ 0.000000 ]]>
</height>
<depth>
<![CDATA[ 0.000000 ]]>
</depth>
<weight>
<![CDATA[ 0.000000 ]]>
</weight>
<quantity_discount>
<![CDATA[ 0 ]]>
</quantity_discount>
<ean13/>
<isbn/>
<upc/>
<cache_is_pack>
<![CDATA[ 0 ]]>
</cache_is_pack>
<cache_has_attachments>
<![CDATA[ 0 ]]>
</cache_has_attachments>
<is_virtual>
<![CDATA[ 0 ]]>
</is_virtual>
<state>
<![CDATA[ 0 ]]>
</state>
<additional_delivery_times>
<![CDATA[ 0 ]]>
</additional_delivery_times>
<delivery_in_stock>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</delivery_in_stock>
<delivery_out_stock>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</delivery_out_stock>
<on_sale>
<![CDATA[ 0 ]]>
</on_sale>
<online_only>
<![CDATA[ 0 ]]>
</online_only>
<ecotax>
<![CDATA[ 0.000000 ]]>
</ecotax>
<minimal_quantity>
<![CDATA[ 0 ]]>
</minimal_quantity>
<low_stock_threshold>
<![CDATA[ 0 ]]>
</low_stock_threshold>
<low_stock_alert>
<![CDATA[ 0 ]]>
</low_stock_alert>
<price>
<![CDATA[ 4.917400 ]]>
</price>
<wholesale_price>
<![CDATA[ 0.000000 ]]>
</wholesale_price>
<unity/>
<unit_price_ratio>
<![CDATA[ 0.000000 ]]>
</unit_price_ratio>
<additional_shipping_cost>
<![CDATA[ 0.00 ]]>
</additional_shipping_cost>
<customizable>
<![CDATA[ 0 ]]>
</customizable>
<text_fields>
<![CDATA[ 0 ]]>
</text_fields>
<uploadable_files>
<![CDATA[ 0 ]]>
</uploadable_files>
<active>
<![CDATA[ 1 ]]>
</active>
<redirect_type/>
<id_type_redirected>
<![CDATA[ 0 ]]>
</id_type_redirected>
<available_for_order>
<![CDATA[ 1 ]]>
</available_for_order>
<available_date>
<![CDATA[ 0000-00-00 ]]>
</available_date>
<show_condition>
<![CDATA[ 0 ]]>
</show_condition>
<condition>
<![CDATA[ new ]]>
</condition>
<show_price>
<![CDATA[ 1 ]]>
</show_price>
<indexed>
<![CDATA[ 1 ]]>
</indexed>
<visibility>
<![CDATA[ both ]]>
</visibility>
<advanced_stock_management>
<![CDATA[ 0 ]]>
</advanced_stock_management>
<date_add>
<![CDATA[ 2020-03-27 12:11:59 ]]>
</date_add>
<date_upd>
<![CDATA[ 2020-03-31 10:28:42 ]]>
</date_upd>
<pack_stock_type>
<![CDATA[ 0 ]]>
</pack_stock_type>
<meta_description>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</meta_description>
<meta_keywords>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</meta_keywords>
<meta_title>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[
Woly | Inlegzolen | Woly Inlegzolen Onderhoudsproducten | 19156
]]>
</language>
</meta_title>
<link_rewrite>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ Woly-Inlegzolen-Onderhoudsproducten_19156 ]]>
</language>
</link_rewrite>
<name>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ Woly Inlegzolen Onderhoudsproducten ]]>
</language>
</name>
<description>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</description>
<description_short>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</description_short>
<available_now>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</available_now>
<available_later>
<language id="1" xlink:href="https://www.hipsko.com/api/languages/1">
<![CDATA[ ]]>
</language>
</available_later>
<associations>
<categories nodeType="category" api="categories">
<category xlink:href="https://www.hipsko.com/api/categories/2">
<id>
<![CDATA[ 2 ]]>
</id>
</category>
<category xlink:href="https://www.hipsko.com/api/categories/39">
<id>
<![CDATA[ 39 ]]>
</id>
</category>
<category xlink:href="https://www.hipsko.com/api/categories/74">
<id>
<![CDATA[ 74 ]]>
</id>
</category>
<category xlink:href="https://www.hipsko.com/api/categories/75">
<id>
<![CDATA[ 75 ]]>
</id>
</category>
<category xlink:href="https://www.hipsko.com/api/categories/78">
<id>
<![CDATA[ 78 ]]>
</id>
</category>
</categories>
<images nodeType="image" api="images">
<image xlink:href="https://www.hipsko.com/api/images/products/576/3504">
<id>
<![CDATA[ 3504 ]]>
</id>
</image>
</images>
<combinations nodeType="combination" api="combinations">
<combination xlink:href="https://www.hipsko.com/api/combinations/15553">
<id>
<![CDATA[ 15553 ]]>
</id>
</combination>
<combination xlink:href="https://www.hipsko.com/api/combinations/15554">
<id>
<![CDATA[ 15554 ]]>
</id>
</combination>
<combination xlink:href="https://www.hipsko.com/api/combinations/15555">
<id>
<![CDATA[ 15555 ]]>
</id>
</combination>
<combination xlink:href="https://www.hipsko.com/api/combinations/15556">
<id>
<![CDATA[ 15556 ]]>
</id>
</combination>
<combination xlink:href="https://www.hipsko.com/api/combinations/15557">
<id>
<![CDATA[ 15557 ]]>
</id>
</combination>
<combination xlink:href="https://www.hipsko.com/api/combinations/15558">
<id>
<![CDATA[ 15558 ]]>
</id>
</combination>
<combination xlink:href="https://www.hipsko.com/api/combinations/15559">
<id>
<![CDATA[ 15559 ]]>
</id>
</combination>
</combinations>
<product_option_values nodeType="product_option_value" api="product_option_values">
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/123">
<id>
<![CDATA[ 123 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/124">
<id>
<![CDATA[ 124 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/138">
<id>
<![CDATA[ 138 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/154">
<id>
<![CDATA[ 154 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/171">
<id>
<![CDATA[ 171 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/156">
<id>
<![CDATA[ 156 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/158">
<id>
<![CDATA[ 158 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/160">
<id>
<![CDATA[ 160 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/162">
<id>
<![CDATA[ 162 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/164">
<id>
<![CDATA[ 164 ]]>
</id>
</product_option_value>
<product_option_value xlink:href="https://www.hipsko.com/api/product_option_values/128">
<id>
<![CDATA[ 128 ]]>
</id>
</product_option_value>
</product_option_values>
<product_features nodeType="product_feature" api="product_features">
<product_feature xlink:href="https://www.hipsko.com/api/product_features/1">
<id>
<![CDATA[ 1 ]]>
</id>
<id_feature_value xlink:href="https://www.hipsko.com/api/product_feature_values/282">
<![CDATA[ 282 ]]>
</id_feature_value>
</product_feature>
<product_feature xlink:href="https://www.hipsko.com/api/product_features/2">
<id>
<![CDATA[ 2 ]]>
</id>
<id_feature_value xlink:href="https://www.hipsko.com/api/product_feature_values/354">
<![CDATA[ 354 ]]>
</id_feature_value>
</product_feature>
</product_features>
<tags nodeType="tag" api="tags">
<tag xlink:href="https://www.hipsko.com/api/tags/0">
<id>
<![CDATA[ 0 ]]>
</id>
</tag>
</tags>
<stock_availables nodeType="stock_available" api="stock_availables">
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15808">
<id>
<![CDATA[ 15808 ]]>
</id>
<id_product_attribute>
<![CDATA[ 0 ]]>
</id_product_attribute>
</stock_available>
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15809">
<id>
<![CDATA[ 15809 ]]>
</id>
<id_product_attribute>
<![CDATA[ 15553 ]]>
</id_product_attribute>
</stock_available>
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15810">
<id>
<![CDATA[ 15810 ]]>
</id>
<id_product_attribute>
<![CDATA[ 15554 ]]>
</id_product_attribute>
</stock_available>
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15811">
<id>
<![CDATA[ 15811 ]]>
</id>
<id_product_attribute>
<![CDATA[ 15555 ]]>
</id_product_attribute>
</stock_available>
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15812">
<id>
<![CDATA[ 15812 ]]>
</id>
<id_product_attribute>
<![CDATA[ 15556 ]]>
</id_product_attribute>
</stock_available>
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15813">
<id>
<![CDATA[ 15813 ]]>
</id>
<id_product_attribute>
<![CDATA[ 15557 ]]>
</id_product_attribute>
</stock_available>
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15814">
<id>
<![CDATA[ 15814 ]]>
</id>
<id_product_attribute>
<![CDATA[ 15558 ]]>
</id_product_attribute>
</stock_available>
<stock_available xlink:href="https://www.hipsko.com/api/stock_availables/15815">
<id>
<![CDATA[ 15815 ]]>
</id>
<id_product_attribute>
<![CDATA[ 15559 ]]>
</id_product_attribute>
</stock_available>
</stock_availables>
<accessories nodeType="product" api="products"/>
<product_bundle nodeType="product" api="products"/>
</associations>
</product>
</prestashop>

```

**Comment by khouloudbelguith** [comment] 2020-03-31 14:15
@LucasVollebergh,

Thanks to change the value of the ` <state>1</state>`, check and feedback.

**Comment by sarahdib** [comment] 2020-04-28 09:36
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed** 2020-04-28 10:00 UTC
Labels: Bug, WS, No change required, 1.7.6.4

**Comment by LucasVollebergh** [comment] 2020-04-28 10:21
> @LucasVollebergh,
> 
> Thanks to change the value of the ` <state>1</state>`, check and feedback.

Thanks, this worked!
