### ISSUE TITLE
Facetedsearch does not work properly

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#16957] opened 2019-12-30 10:45 UTC
**Describe the bug**
Faceted search does not hold down the chosen Brand.
When the Brand is chosen in the facetedsearch filter and I visit the product page and then return back I see the whole list of products whitout sorting by chosen before brand. But in the filter I can see that my Brand is still chosen in the check box.

![image](https://user-images.githubusercontent.com/50954519/71578140-a4e94700-2aff-11ea-9015-03d96cbc8cdb.png)

**Additional information**
PrestaShop version: 7.5.2
PHP version: 5.6.40-14+0~20191128.24+debian8~1.gbpa5b195

**Comment by khouloudbelguith** [comment] 2019-12-30 11:46
Duplicate of #16951

**Closed as completed by khouloudbelguith** 2019-12-30 11:46 UTC
Labels: Duplicate
