### ISSUE TITLE
BO - Language / Exception raised when trying to add svg files

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#19921] opened 2020-06-24 13:40 UTC
#### Describe the bug

In BO => Internationnal => Localisation => Language in the add new language form if we add an svg format file for the flag an exception is raised on save

#### Expected behavior

No exception should be raised ( maybe just a format error message )

#### Steps to Reproduce

1. Go to BO => Internationnal => Localisation => Language
2. Click on 'Add a new language
3. Fill correctly all the required field and in the flag section add svg format file
![capture d'écran_86](https://user-images.githubusercontent.com/40635814/85566684-8daf9000-b630-11ea-99aa-71cf3b9d0202.png)

4. Click on save
5. See error

![capture d'écran_85](https://user-images.githubusercontent.com/40635814/85566798-a4ee7d80-b630-11ea-85fc-1fde20118245.png)

#### Additional information

* PrestaShop version: develop ( but the behaviour is the same with 1.7.6.x and 1.7.7.x )
* PHP version: 7.2

**Comment by marionf** [comment] 2020-06-24 16:15
@SD1982 Your issue seems to be a duplicate of #10600
Can you confirm ?

**Comment by SD1982** [comment] 2020-06-25 07:19
Hi @marionf I don't know if we can consider it as a duplicate because the exception is different but this issue is related to the non-supported svg format too

**Comment by marionf** [comment] 2020-06-25 08:47
All right, I added your issue to the related [EPIC](https://github.com/PrestaShop/PrestaShop/issues/18518) and added labels

**Comment by florine2623** [comment] 2024-01-08 15:38
The issue is fixed in 8.1.3.

No more Exception is thrown, now we have an alert message like so :

`An error occurred while copying "No Picture" image to your product folder.`

<img width="1204" alt="Screenshot 2024-01-08 at 16 37 23" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c79bca1c-56ac-41a8-a856-8ac2a246208c">

I'm closing the issue as it is fixed.

**Closed as completed by florine2623** 2024-01-08 15:38 UTC
Labels: Bug, Minor, BO, Image, Languages, Fixed, 1.7.6.7, Verified
