### ISSUE TITLE
PSGDPR module JS issue (PS 8.0.0)

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#30159] opened 2022-10-29 10:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

PS GDPR module 1.4.2 doesn't working correctly on PrestaShop 8.0.0. 
There is probably any JavaScrip's issue preventing manage customer's personal data and display TinyMCE editor in textarea fields.

![psgdpr-issue](https://user-images.githubusercontent.com/2806752/198825999-4da6cd93-114d-4ec9-a393-bf868b1f1bf1.png)

![tinymce-psgdpr](https://user-images.githubusercontent.com/2806752/198826084-f7517b2c-5e35-4354-8b4d-74e078fe6240.png)

### Steps to reproduce

1. install PrestaShop 8.0.0
2. go to GDPR module settings
3. in the "Personal data management" tab you will see the issue
4. in the "Consent checkbox customization" tab missing TinyMCE editor in textarea fields

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.60

### If your bug is related to a module, specify its name and its version

psgdpr 1.4.2

**Comment by Hlavtox** [comment] 2022-10-29 15:46
Ping @NeOMakinG

**Comment by florine2623** [comment] 2022-10-31 10:00
Hello @Caleydon ,

I can't reproduce your issue 🤔 

https://user-images.githubusercontent.com/16019289/198982184-1c7cbda5-cf49-4a76-89bf-0fecee94b7fc.mov

@PrestaShop/qa-functional 
 Could one of you try this on your end ? ^^

**Comment by Caleydon** [comment] 2022-10-31 11:23
Whole installation process
https://vimeo.com/765660153/d33e387543

**Comment by sallemiines** [comment] 2022-11-01 15:29
Hello @Caleydon 

Thanks for reporting the issue .
I tried to reproduce your issue with Ps1787 & PS800

Following your steps , i didn't reproduce the issue, see the attached screen-record

https://user-images.githubusercontent.com/31663369/199271550-615b1df3-4396-4dc4-86e9-ced1ff9f4cb3.mp4

Please check & feedback ! 

Thank you !

**Comment by Caleydon** [comment] 2022-11-01 17:56
Here is output from browser console.

![psgdpr-issue](https://user-images.githubusercontent.com/2806752/199303261-5a09b473-3ed7-4476-967e-1be37f907881.jpg)

**Comment by AureRita** [comment] 2022-11-03 11:06
Hi @Caleydon, 

Despite our efforts, we were not able to reproduce your issue with the provided information as you can see with this video : 

[Untitled_ Nov 3, 2022 12_00 PM.webm](https://user-images.githubusercontent.com/100699445/199705182-f40274ca-234b-43c4-8e39-b725515d7b0d.webm)

I also tried to reproduce it by putting my shop region in slovakia. 

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

If you have more details about this bug that let us reproduce it, send us more details 

Thank you

**Closed as completed by AureRita** 2022-11-03 11:06 UTC
Labels: Bug, BO, GDPR, Invalid, Module, 8.0.0
