### ISSUE TITLE
backoffice image error

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18944] opened 2020-05-02 12:37 UTC
#### Describe the bug

on the home screen of the backoffice, most viewed the images shown are linked together

I deleted the tmp folder, the cache and regenerate the images and it is not fixed

#### Expected behavior

should show well

#### Steps to Reproduce

1. Go to starting screen
2. Click on most seen
3. Scroll down to see error on products

**Screenshots**

https://youtu.be/ccFd8LAjUKI

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29

**Comment by Progi1984** [comment] 2020-05-04 09:37
@alfonsolr09 Despite our several trials, we could not reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thank you!

**Comment by alfonsolr09** [comment] 2020-05-04 17:42
Is it possible that the error comes from when a product is modified?

**Comment by Progi1984** [comment] 2020-05-07 07:32
May be. Have you a test scenario for reproducing the error ?

**Comment by alfonsolr09** [comment] 2020-05-16 20:03
test scenario no, if you want I can give you access to my website so you can see the error

**Comment by Progi1984** [comment] 2020-05-18 07:34
Without being able to reproduce your bug, we cannot try to fix. Could you try to find the scenario in a local new installed PrestaShop ?

**Comment by florine2623** [comment] 2020-06-11 08:05
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-11 08:05 UTC
Labels: Bug, Dashproducts, No change required
