### ISSUE TITLE
he field name="form[step2][unity]" in BO -> product -> Tab Pricing it is not translatable

### ISSUE THREAD

**Issue by vnt** [PrestaShop/PrestaShop#15479] opened 2019-09-09 22:59 UTC
BO -> Product -> edit prodcut -> Tab Pricing

The field form[step2][unity] near Price per unit, it is not translatable. Can you make it translatable?

`<input type="text" id="form_step2_unity" name="form[step2][unity]" placeholder="Per kilo, per litre" class="form-control">`

Can you make [step2][unity] field visible in the frontend?

Tested in versions P.S. 1.7.5.1 and 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-09-10 07:26
Hi @vnt,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9824
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-10 07:26
Duplicate of #9824

**Closed as completed by khouloudbelguith** 2019-09-10 07:26 UTC
Labels: Duplicate
