### ISSUE TITLE
Module Contact Information Configure Settings Display Email Adress On/Off not working

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#22117] opened 2020-11-25 20:00 UTC
#### Describe the bug

PS 1.7.6.9 and Contact Information Module in Version 3.3.0 allows you to enable or disable the email adress showing on the website: I guess its hooked into the contact form, which has the contact information on the left, and to the footer box.

If you disable to show them, they still appear in both locations.

#### Expected behavior

- Clearly, a working switch. Or a better explanation where the email is now deactivated?

#### Steps to Reproduce

1. Install PS 1.7.6.9
2. Upgrade Contact Information Module to Version 3.3.0
3. Switch Show Email Off
4. See Frontend of Webshop

**Comment by hibatallahAouadni** [comment] 2020-11-26 11:26
Hello @6xthFNGR 

We are aware of this issue, it is already fixed with PS1.7.7.0-rc.1. This issue is a duplicate of #20294. 

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-26 11:27
Duplicate of #20294

**Closed as completed by hibatallahAouadni** 2020-11-26 11:26 UTC
Labels: Duplicate

**Comment by gbartosz83** [comment] 2021-02-12 14:42
how to repair this without presta upgrade?
I've tried upgrade from 1.7.6.7 to 1.7.7.1 and it failed
Also I tried to modify title of this module via translation, translation is changed but presta displays old title
