### ISSUE TITLE
Multistore. Product page in BO, can't select subcategory for product if was selected "Color" for shop in Multistore settings

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29159] opened 2022-07-25 14:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In multistore I can't select subcategory for new product or for existing products if I selected color for each shop in Multistore settings, 
![scrnli_7_25_2022_4-49-31 PM](https://user-images.githubusercontent.com/90208051/180806170-3ef141d7-b24d-4e0e-8b34-15c3e813041a.png)

![scrnli_7_25_2022_4-13-11 PM](https://user-images.githubusercontent.com/90208051/180799257-a97eeb2d-0a46-49dd-926e-ea124669df76.png)

see video: 

https://user-images.githubusercontent.com/90208051/180806211-2a9b3dee-c855-446f-bfbb-f6ec291e8da1.mp4

Also issue reproduced on PS 1.7.8.6

### Expected behavior

Subcategory can be selected

### Steps to reproduce

1. Enable multistore in BO 
2. Select some color for each shop 
3. Go to some product page in BO
4. Try to select subcategory for the product 

### PrestaShop version(s) where the bug happened

1.7.8.6 / 8.0.0 

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment] 2022-07-25 15:43
Hi @szavadskiy, 

Thank for your reporting and nice catch ! 
I reproduce the issue with PrestaShop version 1.7.8.6, It can't be reproduced on 1.7.7.8 because we can't change the color of our shop. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by MeKeyCool** [comment] 2022-08-02 08:45
From my first investigation the problem is not about the color but about default form data.
In fact when you change anything in shop configuration form, subcategories are not checked. So when you save, you can't access them in products anymore.

> :point_up:  If you change something for a shop and nothing for the other, when you go to product configuration page and change shop view, you will see that you can access subcategories or not depending on what shop you previously edited.

**Workaround** : go back to your shop configuration, re-check sub categories and save. Then subcategories appear again in products.

**Closed as completed** 2022-10-28 14:14 UTC
Labels: Bug, Major, BO, Multistore, PR available, Verified, 1.7.8.6
