### ISSUE TITLE
A solution to solved the problems with microdati on product pages - to show: stars rate, price and availability on organic searches

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#22835] opened 2021-01-14 16:46 UTC
Hi
you know me and you how I'm fixed with these microdata. My customer ask me how to show stars rate, price and availability on organic searches like other websites. I've tested with his website. After some tests I've found that the problem is due from the microdata presente in the other product blocks like those of product category module or crossing.
they add confusion in the product pages, because google doesn't understand which microdata use to show those informations on organic searches.
I it necessary to remove all microdata from
classic/templates/catalog/_partials/miniatures/product.tpl
also from some tpl files of productcomment module

that as example this page, after 7-10 days this page on organic searches show those infos
https://www.solariabio.it/integratori-alimentari-naturali-liquidi/504-viridian-epa-e-dha-liquiveg-30-ml.html

and before there weren't any infos on organic searches.

In the new 1.7.7.0 you use ItemList, and it is a nice solution to avoid problems like this one and to show in the page just one Product microdata, but ItemList has problems as I report on other tickets. probably it is better to remove all secondary Product microdata to avoid conflicts.

try to go in
https://search.google.com/structured-data/testing-tool
and set
https://www.solariabio.it/integratori-alimentari-naturali-liquidi/504-viridian-epa-e-dha-liquiveg-30-ml.html
only now the google's tool will show the PREVIEW button and you can see the stars, price and availability

it is necessary to fix this problem on prestashop it will add an important feature to the cms
I've studied many pages and this data will show only if there is only one product microdata in the page
it seems that magento uses this solution

bye

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/104619235-ec506000-568d-11eb-92b1-3988dd52e2bb.jpeg)

![2](https://user-images.githubusercontent.com/653230/104621137-0d19b500-5690-11eb-9fc2-b7265e5aad09.png)

![3](https://user-images.githubusercontent.com/653230/104621141-0ee37880-5690-11eb-8b07-62f8e32aa81d.png)

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: 7.2

**Comment by florine2623** [comment] 2021-01-15 09:14
Hello @maofree ,

Just to be sure, what you're saying is to remove all microdata from :
_classic/templates/catalog/_partials/miniatures/product.tpl
also from some tpl files of productcomment module_
in order to get Google to show the rate, price and availability on the organic search ?

Thanks!

**Comment by Maofree** [comment] 2021-01-15 10:19
Hi
It depends on your theme and its version, however it is necessary to use this tool to understand what is necessary to remove
https://search.google.com/structured-data/testing-tool
if the product page has many Product itemtype the theme you need to remove all microdata tags from product.tpl, normally in the extra themes there are some type of product.tpl like for carousels but it should be similar
![1](https://user-images.githubusercontent.com/653230/104711609-e015e280-5721-11eb-9d03-10ad56a12515.png)

for the productcomment module it is necessary to add a new folder inside your_theme/module/ to override 1 or 2 tpl files of that module. Also in this case depends from its version, the extra theme use old version of that module and you need to edit productcomments_reviews.tpl or productcomments-extra.tpl
doing the same operation. In the last version I need some time to do some tests, I'll do in the next days

to see the microdata tags open these files with an editor and search the word "item"

if the site use an extra feedback system like "recensioni verificate" or ekomi or others it is necessary to do the same thing with an override in the theme, however system is made in its own way. The best solution would be to use another type of microdata but I don't know if they exist because ItemList also doesn't work

bye

**Comment by Maofree** [comment] 2021-01-15 10:21
if you remove the micro tags inside product.tpl you will get errors because the productcomment the aggregator tags

**Comment by Maofree** [comment] 2021-01-15 11:55
the fact is that to make stars, availability and price appear, there is only one Product per page, so either you remove all the Products of secondary products or that they have a different type of microdata, the important thing is that it does not add errors as ItemList because microdata are now considered

**Comment by hibatallahAouadni** [comment] 2021-01-21 13:12
Hello @maofree 

What you suggest here is solution for your issue #22636, is that so?
If so, could you please make a PR :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-21 13:44
As discussed with you on Slack, this issue is duplicate of #22636
Thanks for your cooperation :rocket:

**Comment by hibatallahAouadni** [comment] 2021-01-21 13:45
Duplicate of #22636

**Closed as completed by hibatallahAouadni** 2021-01-21 13:44 UTC
Labels: Bug, 1.7.x, FO, Duplicate, Bug fix, Search engines
