### ISSUE TITLE
Strange issue with attributes and cache.

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#36702] opened 2024-08-13 04:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We're on Prestashop 8.1.7 and PHP 8.1.
We have few, several attributes on products. After we click on different color ( or any other attribute ). Its redirect us on other product.

Debug not showing anything. Console on shows this one:

![combination](https://github.com/user-attachments/assets/8e4ec456-ca6f-40e3-8622-0bddf499fe01)

Whats more strange, when we turn of cache. Its working fine. After cache enable, same issues. Its not hosting / server side issue.

Tried to google this console error, but didn't find any issue.

### Expected behavior

It should switch attributes instead switching to other products.

### Steps to reproduce

Create attributes i.e color.
Go to front page.
Switch attribute on product.
( make sure you have cache enabled ).

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2024-08-13 07:41
@GTriber Hi, this is a problem in your theme. 👍

**Comment by GTriber** [comment] 2024-08-13 07:48
Hosting saying its related to prestashop cache. Additional server logs they have sent shows issue with: "trackingClient.bundle.js:12". Cant find any info regarding whats that.

**Comment by paulnoelcholot** [comment] 2024-08-14 07:06
Hello @GTriber,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-08-14 07:06 UTC
Labels: Bug, Can't reproduce
