### ISSUE TITLE
Does not try to update the whole ObjectModel while using setFieldsToUpdate()

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#23339] opened 2021-02-22 08:44 UTC
#### Is your feature request related to a problem?

I'm always frustrated when I try to make an upgrade file using an ObjectModel that could change between version and that I can't just update a specific field to prevent a missing column further.

#### Describe the solution you'd like

While using setFieldsToUpdate(), I hope that the update query will be only set to this field.

#### Alternatives you've considered

Right now, not really another one. It's not the first time I'm face of this.

#### Additional context

n/d

**Comment by hibatallahAouadni** [comment] 2021-02-22 09:40
Hello @PrestaEdit 

Thanks for the suggestion, the Developer Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers  , I don't know if it's doable but I think it's quite useful to implement this suggestion, do you agree with me?

**Comment by PierreRambaud** [comment] 2021-02-22 16:08
If you use an upgrade script, you should be able to determine which version of PrestaShop you're using and what the ObjectModel contains :thinking:

**Comment by PrestaEdit** [comment] 2021-02-23 12:50
Hi @PierreRambaud,

No, no and no.
I was talking about an upgrade script inside a module, and also ObjectModel inside the module itself.

But even using PrestaShop ObjectModel, we could have this kind of issue.
A module editor could not update every upgrade file at each PrestaShop version cause the Product (for example) ObjectModel will have a newer column inside each version, isn't it ?

My best advice will be to use the setUpdateFields() and use it to make the partial update, I thought.

**Comment by matks** [comment] 2021-02-23 13:02
@PrestaEdit I am sorry but I fail to understand the issue. Could you dive a bit further into the details?

For example, you have a module PrestaModA v1.0.0 . Inside PrestaModA you have added a ObjectModel not part of PrestaShop Core, let's call it ModelA.

You want to release a v1.1.0 of PrestaModA. You want to do X (I fail to understand what X is: add a SQL column inside MySQL? update a SQL column content?) for ModelA in v1.1. What goes wrong?

**Comment by PrestaEdit** [comment] 2021-02-23 13:08
Imagine this.

V1.0: PrestaModA have an ObjectModel nammed ModelA with only a column: active. (Of course, it's have the id_model_a column, for the primary identifier in addition).

V1.1: You want to update() a ModelA createded before and set the active column to false. For that, you use the update() method given by the ObjectModel.

V1.2: You add a column to the ModelA, like "somethingnotusefullthere".

Now, imagine that you are an user of the v1.0. While making the update directly to the v1.2, your update() called inside the v1.1 upgrade script will be fail as you use the ModelA ObjectModel where it's definition have already the "somethingnotusefullthere" in it but the column is not existing yet.

You need to avoid the use of the ObjectModel and make a direct instance query.

My hope is to have something that we can use with the setFieldsToUpdate() method that existing in PrestaShop to avoid the full update (and so don't try to update a column that doesn't exists yet) as we have specificly say which fields to update, there.

**Comment by matks** [comment] 2021-02-23 13:16
@PrestaEdit OK I see it better now. We actually have similar issues on the upgrade process.

But we believe the root cause is elsewhere. If you think about it, the main issue in this scenario is that _in the upgrade script, you are using php functions that possibly change their behavior and signature during the upgrade._

So for example, when upgrading PrestaModA from v1.0 to v1.2, we are calling `$modelA->update()` although the php file `ModelA.php` is being replaced by the upgrade, from an old version to a newer version. When stated like that, doesn't it sound like a risky move ? 😄  Using code on a server while replacing this very same code in parallel on the disk. Not to mention all the issues with caching, which can result in your disk having the new version of the file but the cache serves the old version so you expected to call `$modelA->update()` with the new version of `update()` and instead are calling `$modelA->update()` with old version.

On PrestaShop Core upgrade, we believe we should actually completely isolate the upgrade process and scripts from the code being updated. That would mean `make a direct instance query` as you said. We think "the code being updated" and "the code in charge of the upgrade" should NOT overlap as this situation has bitten us multiple times in the past.

**Comment by hibatallahAouadni** [comment] 2021-03-16 17:08
Hello @PrestaEdit ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-16 17:08 UTC
Labels: Improvement, CO, No change required, Developer Feature, Back-end
