### ISSUE TITLE
[PrestaShop 1.7]Product images don't work if the shop uses Japanese or Chinese language

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#20869] opened 2020-09-06 23:41 UTC
#### Describe the bug

Product images don't work if the shop uses Japanese or Chinese language.

#### Steps to Reproduce

1. Add to your shop Japanese or Chinese language.

2. Create a new product with a Japanese name for example:
洽洽原味瓜子
and click the save button.

3. Add images to your product and save again.

4. For the English language the image is displayed correctly:
https://prnt.sc/ucoqoy

but for the Japanese language the image is not displayed:
https://prnt.sc/ucoqli

**Screenshots**

Product-list:
https://prnt.sc/ucorvk

Product page:
https://prnt.sc/ucoqli

Product page code - missing image name, alt and title for the Japanese language (for English language everything is ok):
https://prnt.sc/ucoskc

#### Additional information

* PrestaShop version: 1.7.6

**Comment by khouloudbelguith** [comment] 2020-09-07 08:16
Hi @Angar90,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1C1xB_sOhZmmtUFTTAvEiknXi3APgzOwR/view?usp=sharing
What is the exact language by default in your case?
What is the language of the employee did you use?

Thanks!

**Comment by Angar90** [comment] 2020-09-07 12:29
Hello @khouloudbelguith 

I use English as the default shop language and employee language.
I recorded a screen to show how to repeat this problem:
https://www.loom.com/share/2b4162fa16804cf48de647b9205aa899

At first, one of my customers reported this problem to me and I have reproduced this error in my test shop, so probably it isn't a local bug.

Regards

**Comment by khouloudbelguith** [comment] 2020-09-07 14:36
@Angar90, you are using Nginx.
It is a problem in your Nginx configuration, thanks to check this [link](https://github.com/PrestaShop/PrestaShop/blob/e51d7eaa0164118b88d8cdcddbbe60e64aff7c64/docs/server_config/nginx.conf.dist)
Recently, this file is updated to show how to use multishop and multilanguage as fixed [here](https://github.com/PrestaShop/PrestaShop/pull/12082/files).
Thanks to check and feedback.

**Comment by NoZTurn** [comment] 2020-09-07 14:58
I sometime also come accoss with this problem before, I check this myself, and find if your link-rewrite is empty, there problem will exist, and I guess, maybe because the link rewrite form's uses product name as default value(ignore ' ' will repleace to '-'), but when product name is chinese or japanese, we konw that chinese and japanese charactor can't be used in url, so the link rewrite form is empty becuase he can't use chinese and japanese charactors as its value. when link rewrite is empty, the images urls be afected.

You may be confused why khouloudbelguith can't reproduce the problem?
I guess the reason maybe because her defaut language is english and the english language is in front of other language(maybe the reason, I'm not quite sure), so when she add a product, all values of link rewite forms including chinese and japanese uses english product name as its default, so the link rewrite will not be empty, then the demo seems normal.

In a word, if the link rewrite form is empty, the problem accurs, if it is not empty, all normal.

**Comment by khouloudbelguith** [comment] 2020-09-07 15:11
@NoZTurn,

> konw that chinese and japanese charactor can't be used in url, so the link write form is empty

You need to enable `Accented URL`
![image](https://user-images.githubusercontent.com/16067358/92400260-f4225580-f12b-11ea-8bc6-2275091215db.png)

Thanks to check and feedback.

**Comment by Angar90** [comment] 2020-09-07 15:35
@khouloudbelguith @NoZTurn Thanks for the help, I enabled "Accented URL" and now everything is ok.

Regards

**Comment by khouloudbelguith** [comment] 2020-09-07 15:37
@Angar90,

Great!
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed** 2020-09-07 15:39 UTC
Labels: Bug, FO, International, No change required, 1.7.6.7

**Comment by NoZTurn** [comment] 2020-09-07 16:06
> @NoZTurn,
> 
> > konw that chinese and japanese charactor can't be used in url, so the link write form is empty
> 
> You need to enable `Accented URL`
> ![image](https://user-images.githubusercontent.com/16067358/92400260-f4225580-f12b-11ea-8bc6-2275091215db.png)
> 
> Thanks to check and feedback.

@khouloudbelguith Thanks for your infomation, and I will give a try. and also @Angar90 thanks for your report, I just know and remenber to to fill link rewrite form for chinese and japanese language, and after your issue and khouloudbelguith's tips, I have learned a trick.
