### ISSUE TITLE
Unable edit product attributes when editing an order from BO

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#10775] opened 2018-09-30 12:19 UTC
**Describe the bug**
If there is an order containing a product with attributes, such as t-shirt size L, it is not possible to edit the attribute from BO. The only option is to delete the product from the order and use "Add a product" button to insert the product again with the new attribute (such as t-shirt size XL).

**To Reproduce**
1. Go to 'back office -> orders -> select an order containing product with attribute'
2. Scroll down, click on 'PRODUCTS -> Edit'
3. There is no option to edit the attribute, you can only change price and Qty

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop vanilla version: 1.7.4.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-01 09:03
Hi @mrabsinthe,

Thanks for your report.
It is a normal behavior, it is not a bug.
Because when you try to edit the attribute of a product, it is different from the first one ordered which has other features ( quantity, price, reference, ..).
So you need to add a new product in your order.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-10-01 09:03 UTC
Labels: Order, No change required
