### ISSUE TITLE
Specific prices block disappearing frequently

### ISSUE THREAD

**Issue by nirav-nanda** [PrestaShop/PrestaShop#13627] opened 2019-05-02 05:29 UTC
we have set specific price rule for bulk purchase on some products.
while it work perfectly in cart, but in back office the block is keep disappearing very frequently, we have to refresh the page 2 to 3 time to display it on screen again.

here i have sending link of recorded video pls check it.
https://drive.google.com/file/d/1428H_85OgUsq3HK_aiq4rFjgh0QlOB1o/view?usp=sharing

**Comment by khouloudbelguith** [comment] 2019-05-02 08:13
Hi @nirav-nanda,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record
https://drive.google.com/file/d/19qrS2aHm8o_l_YRa0k7yCknANCFCNBh6/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by nirav-nanda** [comment] 2019-05-06 03:34
hello, @khouloudbelguith 
sorry for late reply
here is my site information

Server information Linux #1 SMP Thu Dec 6 05:11:00 EST 2018 x86_64
Server software version: Apache/2.4.39 (cPanel) OpenSSL/1.0.2r mod_bwlimited/1.4 Phusion_Passenger/5.3.7
PHP version: 7.1.27

MySQL version: 5.5.61-38.13-log
MySQL server: localhost
MySQL engine: InnoDB
MySQL driver: DbPDO

PrestaShop version: 1.7.5.0
Shop URL: [http://shreemahavir.in/](http://shreemahavir.in/)
Current theme in use: classic

**Comment by khouloudbelguith** [comment] 2019-05-08 08:03
Hi @nirav-nanda,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by nirav-nanda** [comment] 2019-05-11 05:24
no idea how to report error log , so i recorded it.
pls check - error log recording from debug mode
https://drive.google.com/file/d/1LSe5Lp_aumtSZgWmSmLPIQ6My3gezHG1/view?usp=sharing

no idea how to report error log , so i recorded it.

**Comment by khouloudbelguith** [comment] 2019-05-13 11:10
Hi @nirav-nanda,

Thanks for your feedback.
In your case, debug mode enabled but no exception displayed.
Could you please follow these steps:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. edit the product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab 

Thanks to provide me the exact error displayed.
Thanks!

**Comment by nirav-nanda** [comment] 2019-05-15 05:21
thank you @khouloudbelguith for your constant support and interest in this.
ma'am , i followed your steps
i can see error that saying 
An exception occured in driver: SQLSTATE[42000] [1203] User shopan76_demo (shopan76_demo is my database name) already has more than 'max_user_connections' active connections

detailed screen recording - https://drive.google.com/file/d/1WE--28KylWHL1A0-wkRscwr15WZvBOQr/view

and one more minor thing i would like to ask out of this topic that why my site show me page 403 Forbidden error every time when i exit from debug mode to normal mode. although it is a temporary error and automatically solved itself within 2 to 5 minutes - https://prntscr.com/nopjcm

thanks and regards
nirav nanda
www.shreemahavir.in

**Comment by khouloudbelguith** [comment] 2019-05-15 08:24
Hi @nirav-nanda,

>An exception occured in driver: SQLSTATE[42000] [1203] User shopan76_demo (shopan76_demo is my database name) already has more than 'max_user_connections' active connections

That means that the specific database user has already used up all the concurrent connections at that moment and more cannot be processed.

The only option to fix without doing any programming changes is to change the [max_user_connections](https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_max_user_connections) value in MySQL configuration

About the 403 error, it could be a permission access issue.
Your issue is not a PrestaShop's core bug but a server configuration.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-15 08:24 UTC
Labels: BO, Taxes and Prices, No change required, 1.7.5.0

**Comment by Matt75** [comment] 2019-05-15 11:27
This process is really heavy, creating specific price will execute a lot of queries in the database especially on a big shop with many products.

Moreover the cache (smarty etc...) will be cleared too.

When you create a lot of specific price, default behavior is not so good, it’s adapted to a small shop but not for a big.

Some years ago, on a shop with 10000+ products and more 50000+ customers, we have a merchant who create 10 specifics price in some minutes.

Server was going out due to concomitant IO on clearing smarty cache. Because wasn’t on maintenance mode and there were a lot of customer on the front office.

So some requests create cache, some others cleared cache, in the same time.

Total of IO cause a slowest server and cause errors due to max execution time, heavy queries on database and complex scripts to process in the same time.

So be careful when create specific price, use maintenance mode if needed.

I have remove the clear cache on specific price create/edit process and I clear it manually after create/edit all specific price needed.
