### ISSUE TITLE
Product page category creation fails

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#25081] opened 2021-06-22 13:14 UTC
#### Describe the bug

Strict types were declared in old code recently (probably mistaken, that command was introduced in experimental page) and now category creation fails in product page.

#### Expected behavior

Category should be created successfully

#### Steps to Reproduce

1. Go to Product page (old)
2. Add category
3. Nothing happens (see error in profiler)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![Screenshot from 2021-06-22 16-06-55](https://user-images.githubusercontent.com/31609858/122930256-7e167480-d374-11eb-8e6e-431641f99867.png)
![Screenshot from 2021-06-22 16-07-05](https://user-images.githubusercontent.com/31609858/122930262-7fe03800-d374-11eb-8b08-86cd7f930b60.png)

#### Additional information

* PrestaShop version: 1.7.8, develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-06-22 13:22
Hello @zuk3975 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22144. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-22 13:22
Duplicate of #22144

**Closed as completed by hibatallahAouadni** 2021-06-22 13:22 UTC
Labels: Duplicate, PR available

**Comment by matks** [comment] 2021-06-22 14:55
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25082
