### ISSUE TITLE
Specific prices do not allow select time

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#17939] opened 2020-03-03 11:23 UTC
#### Describe the bug

In previous versions of prestashop (before migrating product page) allow a specific price to start at a certain time.
Now you can only select date, not time.

It is not clear if it is included or excluded day (start of the day or end of the day).

Why not use the native selector or input type = date ?.

#### Expected behavior
Allow product specific prices to have date with time

#### Steps to Reproduce
Try to add a 3h product  discount through specific prices on the product edition page.

**Screenshots**

Catalog Rules allow TIME (catalog rule is also specific price)
![image](https://user-images.githubusercontent.com/194784/75769920-3dda4f80-5d47-11ea-9143-94768a423e73.png)

Migrated page, only DATE

![image](https://user-images.githubusercontent.com/194784/75770067-8abe2600-5d47-11ea-8abe-7f527d3e9fdd.png)

#### Additional information
* PrestaShop version: 1.7+
* PHP version: N/A Screenshots from http://demo.prestashop.com/

**Comment by khouloudbelguith** [comment] 2020-03-03 11:28
Hi @davidglezz,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11329
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-03 11:29
Duplicate of #11329

**Closed as completed by khouloudbelguith** 2020-03-03 11:28 UTC
Labels: Duplicate
