### ISSUE TITLE
Bug when changing addres in back office

### ISSUE THREAD

**Issue by pruault** [PrestaShop/PrestaShop#22816] opened 2021-01-13 16:18 UTC
When we change the delivery or billing address, all the prices of the products in the order go to zero

#### Expected behavior

When we change the shipping or billing address, all product prices must not change

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-13 17:02
Hello @pruault 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1o9EcEx26UyxnpsKZEBD4PeF_oSgv57qw/view

Please check and feedback.
Please provide clear and concise seps to reproduce your issue :wink: 

Thanks!

**Comment by mrl22** [comment] 2021-01-13 17:22
I was able to replicate this on a completely fresh 1.7.7.1 with test data.

I opened the test data order "FFATNOMMJ" edited the Invoice address and changed the country from United States to United Kingdom. On save, all totals went to zero.

See [screenshot here](https://cdn.discordapp.com/attachments/572912019221774362/798965014190358578/3.JPG)

**Comment by hibatallahAouadni** [comment] 2021-01-17 12:46
Hello @mrl22 

I followed your steps and yet I didn't manage to reproduce the issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1sVO35YT7rp1WbMgKniHmJppuE7pjZXWO/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-03 17:31
Hello @pruault ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-03 17:31 UTC
Labels: Bug, BO, Order, Addresses, No change required, 1.7.7.0
