### ISSUE TITLE
Wholesale price bug with variations

### ISSUE THREAD

**Issue by pukys** [PrestaShop/PrestaShop#14912] opened 2019-07-30 08:02 UTC
When you have a product with variations the float number of the wholesale price of the product variation cuts off when you change the base price of the product.

1) Go to a combination, edit its wholesale price, save (Wholesale price set to 1.11)
2) Reopen the product page, change the product price (with tax), save
3) Reopen the product page, go to the combination detail, the price has lost its decimal part. (Wholesale price was set to 1)

The important part is to reload the product page between steps.

It looks like the decimal part from the wholesale price is lost at step 3 when changing the product price with tax, and then saving. But this isn't visible until you reload the page.

PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-30 10:19
Hi @pukys,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9972
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-30 10:19
Duplicate of #9972

**Closed as completed by khouloudbelguith** 2019-07-30 10:19 UTC
Labels: Duplicate, Taxes and Prices, Combinations
