### ISSUE TITLE
Cart rule with percent discount and free shipping does not apply free shipping

### ISSUE THREAD

**Issue by davideapvd** [PrestaShop/PrestaShop#17489] opened 2020-02-04 08:37 UTC
**Describe the bug**
I've created a cart rule like the one that follows, basically enabling free shipping and a 50% discount on all products, only the 50% discount is applied but not the free shipping
![immagine](https://user-images.githubusercontent.com/21243907/73727497-e047e880-4731-11ea-9ac1-83cc541df6fd.png)

**To Reproduce**
1. Cart rule with free shipping and 50%
2. apply the rule on the cart, only 50% is applied, the free shipping not

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment] 2020-02-04 09:37
Hi @davideapvd,

I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1Zl6UiqJDvns0-I1Q09zea5XWKguxohk4/view
About the `Problem with cart rules to selected products and exclude products with a discount`
Here's the PR: #13704 to fix the issue.
It is fixed in the next version PS1.7.7.0.

Thanks to check & feedback.

**Comment by davideapvd** [comment] 2020-02-04 09:50
Hello @khouloudbelguith thank you for the answer, I saw that the final price is calculated correctly but both on the cart summary and the order detail in the admin page the shipping is listed as not free, even if the final price payed by the client was correct (no shipping) , should I try to upgrade to 1.7.6.3 or apply that PR to see that shipping as free in this case?
thanks

![immagine](https://user-images.githubusercontent.com/21243907/73733347-1be7b000-473c-11ea-938a-614283ca5ad7.png)

**Comment by davideapvd** [comment] 2020-02-04 09:58
@khouloudbelguith  can you try to set as default the carrier with a base price of >0€ and repeat the test? before applying the discount you should see a shipping price >0 , I think in this case the shipping price is not zeroed by the discount code.

**Comment by khouloudbelguith** [comment] 2020-02-04 10:03
@davideapvd, same behavior.
https://drive.google.com/file/d/1y6J9M8wX69Ju1cVY7jNCxNDHPsoymMub/view
Thanks!

**Comment by davideapvd** [comment] 2020-02-04 10:11
@khouloudbelguith but in your video I see the shipping price, even if in the first one that was as Free, can you confirm it even in the admin for that order the shipping is listed > 0 ?

**Comment by khouloudbelguith** [comment] 2020-02-04 10:13
@davideapvd, about this error `the shipping is listed as not free`, it is similar to this: https://github.com/PrestaShop/PrestaShop/issues/9586#issuecomment-571114824

Thanks!

**Comment by davideapvd** [comment] 2020-02-04 10:18
@khouloudbelguith sorry but I don't understand how I should proceed, in that issue I don't see a clear way to fix that issue if it is the same.

**Comment by khouloudbelguith** [comment] 2020-02-04 10:27
@davideapvd, no this issue is not fixed yet.
It is added to our bug roadmap.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-05 08:04
@davideapvd, can we close this issue as a duplicate of #9586?

**Comment by davideapvd** [comment] 2020-02-05 08:35
hello @khouloudbelguith if I understood correctly starting from https://github.com/PrestaShop/PrestaShop/issues/9586#issuecomment-570958876 then yes, feel free to close this one as duplicate, I'll subscribe to the other and test the fix for my scenario when it will be released. thanks

**Comment by khouloudbelguith** [comment] 2020-02-05 08:37
@davideapvd, thanks for your feedback.
I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-05 08:37
Duplicate of #9586

**Closed as completed by khouloudbelguith** 2020-02-05 08:37 UTC
Labels: Bug, FO, Duplicate, Discounts, Cart rules, 1.7.6.2
