### ISSUE TITLE
[BO] Cannot add a product when creating a new order

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#20642] opened 2020-08-19 13:43 UTC
#### Describe the bug
In back office I cannot add a new order. The product search is not working. The ajax sent during typing in product search doesn't include id_currency.

#### Expected behavior

Searching for products to add them to the order should display the searched products.

#### Steps to Reproduce

1. Go to Orders
2. Click on 'Add new order'
3. Search and select the customer.
4. Scroll down to "cart" section, and type some product name in the product search.

**Screenshots**
The ajax being made during product search returns server error 500
![image](https://user-images.githubusercontent.com/24461669/90641845-f7fc3f80-e231-11ea-8e0a-4b083b562dd2.png)
![image](https://user-images.githubusercontent.com/24461669/90642018-29750b00-e232-11ea-872f-0bfa5e7f7bdc.png)

Following advices online, I have added new currency, disabled the default one, then enabled it and removed the extra currency. Nothing works, in database, in ps_currency I have now only one row now:
![image](https://user-images.githubusercontent.com/24461669/90642381-95f00a00-e232-11ea-9c2a-51ccd9b1f688.png)

And in database ps_configuration:
![image](https://user-images.githubusercontent.com/24461669/90642479-b750f600-e232-11ea-9e94-9c5a77569a9b.png)

Also, when I search for the customer and click on "choose" then in JS console this error occurs:
![image](https://user-images.githubusercontent.com/24461669/90643181-9210b780-e233-11ea-84f0-2a27bc3a6d9b.png)

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2.18

**Comment by SimonGrn** [comment] 2020-08-19 14:28
Hello,

I'm not able to reproduce your issue : 
![image](https://user-images.githubusercontent.com/49909275/90647595-c470e380-e238-11ea-87f0-c4b44d20fdc7.png)

My installation is a fresh one, with these settings:
- country France
- language English

I can add a product without trouble : 
![image](https://user-images.githubusercontent.com/49909275/90647703-e2d6df00-e238-11ea-8740-bec392a3a242.png)

Your problem seems to be in your own configuration. do you have any module installed that could potentially break the currecny call ?

**Comment by grzegorzgit** [comment] 2020-08-19 14:40
Hi,
no I don't have any module that could play with the currency. And the currency problem doesn't exist elsewhere, just in that place.

**Comment by SimonGrn** [comment] 2020-08-19 14:45
Do you see any incompatibility in the "Advanced Parameters > Information" page ? Is this a fresh install or an upgrade ?
I see you're using a test environment, judging by your domain name.

Sadly, if we're not able to reproduce your problem, you might want to check in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by khouloudbelguith** [comment] 2020-09-08 11:23
Hi @grzegorzgit,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2020-09-08 11:23 UTC
Labels: BO, No change required, 1.7.6.x, 1.7.6.1
