### ISSUE TITLE
Translating child theme not possible

### ISSUE THREAD

**Issue by wouterlagauw** [PrestaShop/PrestaShop#16625] opened 2019-11-29 17:04 UTC
**Describe the bug**
Using 1.7.6.1 and 1.7.6.1. When you want to translate a child theme, the error '/var/cache/dev/themes/child_theme/translations/nl-NL directory does not exist.' appears. Copying a translations to another theme also doesn't work.

**To Reproduce**
1. Go to themes
2. Download child theme of classic theme
3. Activate child theme
4. Go to translations
5. Select child_classic and language
6. Error appears

**Additional information**
PrestaShop version: 1.7.6.1, 1.7.6.2

**Comment by khouloudbelguith** [comment] 2019-12-02 08:11
Hi @wouterlagauw,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15268
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-02 08:12
Duplicate of #15268

**Closed as completed by khouloudbelguith** 2019-12-02 08:11 UTC
Labels: Duplicate

**Comment by DeFault-1** [comment] 2021-01-21 19:04
The same old bug still exists in **PS 1.7.7.1**

![Directory not found](https://user-images.githubusercontent.com/22258621/105399413-2c977b80-5c56-11eb-9b1e-6fbf4512417d.jpg)
