### ISSUE TITLE
PS 1.7.6.0 - It is necessary to install Redis

### ISSUE THREAD

**Issue by escaware** [PrestaShop/PrestaShop#13815] opened 2019-05-16 11:11 UTC
este es el error al instalar prestashop 1.7.6.0
en escaware.com/prueba

Fatal error: Uncaught RedisException: Redis server went away in /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:47 Stack trace: #0 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php(47): Redis->setOption(1, 1) #1 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(203): Doctrine\Common\Cache\RedisCache->setRedis(Object(Redis)) #2 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(147): Doctrine\ORM\Tools\Setup::createCacheInstance(false, Object(Doctrine\Common\Cache\RedisCache)) #3 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(125): Doctrine\ORM\Tools\Setup::createCacheConfiguration(false, '/tmp', NULL) #4 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(71): Doctrine\ORM\Tools\Setup::createConfiguration(false, '/tmp in /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php on line 47

**Comment by khouloudbelguith** [comment] 2019-05-16 11:20
Hi @escaware,

Please, send your request in English.
English is the norm on this bug tracker. 
Thank you!

**Comment by escaware** [comment] 2019-05-16 11:34
hello

inn prestashop 1.7.6.0 is it necessary to install redis?

because i have problem whit this

my web on install prestashop 1.7.6.0

http://escaware.com/prueba

in my web gives this error.
Fatal error: Uncaught RedisException: Redis server went away in /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:47 Stack trace: #0 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php(47): Redis->setOption(1, 1) #1 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(203): Doctrine\Common\Cache\RedisCache->setRedis(Object(Redis)) #2 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(147): Doctrine\ORM\Tools\Setup::createCacheInstance(false, Object(Doctrine\Common\Cache\RedisCache)) #3 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(125): Doctrine\ORM\Tools\Setup::createCacheConfiguration(false, '/tmp', NULL) #4 /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(71): Doctrine\ORM\Tools\Setup::createConfiguration(false, '/tmp in /var/www/vhosts/escaware.com/httpdocs/prueba/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php on line 47



thanks

jose luis

**Comment by matks** [comment] 2019-05-16 12:11
Hi @escaware, no Redis is not necessary for PS 1.7.6.0.
Do you have "redis" php extension enabled ?

**Comment by khouloudbelguith** [comment] 2019-05-16 12:13
@escaware, in my case, I successfully PrestaShop 1.7.6.0, without installing Redis - PHP
Thanks!

**Comment by matks** [comment] 2019-05-16 12:14
I'm wondering if this the culprit...
https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Tools/Setup.php#L128

**Comment by jolelievre** [comment] 2019-05-16 12:31
@escaware by any chance do you have a longer stack trace for this error
I'm suspecting this call to be at the origin https://github.com/PrestaShop/PrestaShop/blob/3471afe722c4d7a335a991e8f76fe9fb07e79de2/src/Adapter/ContainerBuilder.php#L192

But I would like to be sure (even though in any cas we should change the call with an explicit cache)

**Comment by escaware** [comment] 2019-05-20 11:23
Hello

at the moment it works, I have removed the lines that comments

jolelievre

and it work

**Comment by colinegin** [comment] 2019-05-20 12:11
@khouloudbelguith and @jolelievre do you know if it is the same issue with PS 1.7.5.2 ?

**Comment by khouloudbelguith** [comment] 2019-05-20 12:20
@colinegin, this line https://github.com/PrestaShop/PrestaShop/blob/3471afe722c4d7a335a991e8f76fe9fb07e79de2/src/Adapter/ContainerBuilder.php#L192 is added to ps1.7.6.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/12564
in my case, I successfully installed ps 1.7.6.0, without installing Redis - PHP
@jolelievre What do you think?
Thanks!

**Comment by escaware** [comment] 2019-05-20 13:06
Hello
I made a clean installation of prestashop 1.7.6.0 test and that error arose,
jolelievre solution is correct, delete that line and it works, I do not have redis installed on the server and I ignore this installation failure, versions 1.7.5.2 works correctly
Thank you
Jose Luis

**Comment by jolelievre** [comment] 2019-05-21 07:20
Hell @colinegin I haven't heard of this problem with 1752, unless there is another issue
The problem is on 176 with doctrine initialization, if a similar problem occurs on 1752 then it comes from another wrong init that I don't know of

@escaware I **strongly discourage** you, or anyone, to comment/remove this line because it is used for new feature in PrestaShop to allow using Doctrine in modules, any module using Doctrine won't work on your shop if you remove this line (but at least it confirms our hunch that the problems comes from this call 😉)

I don't have redis extension on my environment so I couldn't test it yet, but I proposed a PR to fix this issue https://github.com/PrestaShop/PrestaShop/pull/13885
Instead of removing the line, which is needed, I force an `ArrayCache` so that Doctrine uses it right away instead of trying to init a non existent connection

Could you please try if this fixes your issue? Thank you

**Comment by jolelievre** [comment] 2019-05-22 08:34
Hello @escaware we have tested the PR with @PierreRambaud and it fixes the problem.
It will be merged soon.

**Comment by matks** [comment] 2019-05-22 14:24
Fixed by https://github.com/PrestaShop/PrestaShop/pull/13885

**Closed as completed by matks** 2019-05-22 14:24 UTC
Labels: Fixed, 1.7.6.0
