### ISSUE TITLE
Required fields not saved (Phone)

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#18139] opened 2020-03-13 12:23 UTC
On prestashop 1.7.6.3 going to customers address and adding phone to required fields
 it is not saved and in front office stay optional: here the video
https://drive.google.com/open?id=1L3qMoazQs02LOIV8Im5gQ98r-VDBmAu9

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by Betafer** [comment] 2020-03-13 12:37
i've tried also in a testing prestashop 1.7.6.3, preference is saved but in address page remains optional

<img width="1255" alt="Schermata 2020-03-13 alle 13 37 39" src="https://user-images.githubusercontent.com/5024055/76621517-d636b800-652f-11ea-9243-08d516e2adb2.png">
<img width="286" alt="Schermata 2020-03-13 alle 13 37 04" src="https://user-images.githubusercontent.com/5024055/76621523-d8991200-652f-11ea-8914-4a3061701db0.png">

**Comment by khouloudbelguith** [comment] 2020-03-16 11:56
Hi @Betafer,

I did not manage to reproduce the issue with PS1.7.6.4.
I attached a screen record
https://drive.google.com/file/d/1lDW7IrS_3bX82WZ-lluubpbKwHQ0FLF-/view
Did you a custom theme?
Have you tried to contact the theme author about this issue?

Thanks!

**Comment by Betafer** [comment] 2020-03-16 12:22
Hello, yes custom theme

**Comment by Betafer** [comment] 2020-03-16 13:05
Browser Google Chrome 80

**Comment by khouloudbelguith** [comment] 2020-03-16 13:06
@Betafer, As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them and feedback.

**Comment by Betafer** [comment] 2020-03-16 13:32
OK, thanks

**Comment by khouloudbelguith** [comment] 2020-03-16 14:12
@Betafer, thanks!
Waiting for your feedback.

**Comment by sarahdib** [comment] 2020-04-15 16:03
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-04-15 16:03 UTC
Labels: Bug, FO, Addresses, No change required, 1.7.6.3
