### ISSUE TITLE
BO - Order details - Payment block not refreshed after adding product

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#21293] opened 2020-10-05 09:08 UTC
#### Describe the bug

On BO, when adding/updating a product on an already paid order, the message in Payment block "Warning €XX paid instead of €XX" is not added/updated immediately. A refresh is needed (on Legacy refresh wasn't needed).

Please note that when a voucher is added, the Payment block is automatically updated without refresh.

#### Expected behavior

Payment block should be updated each time an update is made on the order.

#### Steps to Reproduce

0. Have a paid order
1. Go to BO > Orders > On the paid orders
2. Add or Edit a product on the order
3. The "Warning" message in payment block is not displayed
4. Refresh the page : Warning message is now displayed.

**Screenshots**

On screenrecord : I add a product, Payment block is not updated. I refresh : The "warning" message is now updated in Payment block.

https://drive.google.com/file/d/1A5gryu4jr0oSdI7B4Oy_UeulJeNVp39Z/view?usp=sharing

#### Additional information

* PrestaShop version: 1770rc1build1
* PHP version: N/A

**Comment by sowbiba** [comment] 2020-10-05 16:14
Fixing this issue means add a route to get order's payments. Too big to add it after RC1 release I think

@PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers WDYT ?

**Comment by jolelievre** [comment] 2020-10-05 17:15
Hi @Robin-Fischer-PS,

regarding your side note when a Voucher is added, it indeed works because adding a voucher performs a page request that redirects to the view page so everything is updated when the submit button is clicked.

However add/remove product manipulation happen via ajax calls and JS updates, which is why the Payment block is not updated. As @sowbiba noticed we have no JS code nor server side API to update this block dynamically for now. It would require to either create a JSON API and the js code that can interpret and replace it. Or a more simple "API" that simply returns the block html code This has been done in other refresh calls although it's far from ideal it has the advantage to be easy to implement and can withstand hooks and template overrides better.

We have a similar issue regarding the Carrier block https://github.com/PrestaShop/PrestaShop/issues/21267 when shipping is updated the Order details are updated but not the OrderCarrier ones.

To me it is indeed a regression from the previous behaviour, I'd be more in favor of fixing this for the next 177 version, even if it implies adding new endpoints in the OrderController. Though I don't know if it's considered a new feature (forbidden after code freeze) or a missing feature that should have been coded and could be added in the next patch version? @eternoendless what do you think?

**Comment by LouiseBonnard** [comment] 2020-10-07 09:11
For a patch version instead of 1.7.7.

**Comment by Progi1984** [comment] 2020-12-03 09:05
Fixed by #22059

**Closed as completed by Progi1984** 2020-12-03 09:05 UTC
Labels: Trivial, BO, Order, Regression, Fixed, migration, Nice-to-have, 1.7.7.x
