### ISSUE TITLE
Comment confirmation dialog not visible behind backdrop

### ISSUE THREAD

**Issue by LukasK13** [PrestaShop/PrestaShop#24516] opened 2021-05-16 18:36 UTC
#### Describe the bug

When submitting a new review, the confirmation dialog appears to be behind the backdrop. This is likely caused by a timing issue

#### Expected behavior

A visible confirmation dialog

#### Steps to Reproduce

1. Use PS productcomment v4.2.1
2. Go to a product page (logged in)
3. Write and submit a product comment
4. Don't see a confirmation dialog

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.24

**Comment by matks** [comment] 2021-05-16 19:00
Hello @LukasK13 we need some more accurate steps 😅 

Something similar to
1. Use PS with module productcomment version ...
1. I go to page A as a visitor (= not logged in)
1. I write a product comment, I submit the comment
3. I see ...

A screenshot would also be a great help 😉

**Comment by LukasK13** [comment] 2021-05-16 19:14
Well it's basically like you say:
1. Use PS productcomment v4.2.1
2. Go to a product page (logged in)
3. Write and submit a product comment
4. Don't see a confirmation dialog

I think a screenshot would not help as you can obviously see nothing but the product page itself...
Please excuse that I cannot go further into detail, as I fixed the issue about 5 months ago, submitted a pull request and moved on. So please try it yourself.

**Comment by hibatallahAouadni** [comment] 2021-05-17 07:41
Hello @LukasK13 

I didn't manage to reproduce your issue, could you please check the attached screen record below:

https://www.awesomescreenshot.com/video/3764486?key=d5c257cee48f4c250c823ca32c4e5810

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-07 14:59
Hello @LukasK13 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-07 14:59 UTC
Labels: Bug, FO, No change required, Productcomments, 1.7.7.0
