### ISSUE TITLE
Reference lookup by ps_product_attribute table and not by ps_product

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#28035] opened 2022-03-24 19:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

It would be nice if in the Stock administration, I could filter by combination reference. Currently it only allows you to filter by product reference. When a product has, for example, 40 combinations, many references are left out, which makes it difficult to search in the advanced stock management.

https://drive.google.com/file/d/1bQKQABg0eqorYP8gK77nZtl1iVU7hQXe/view?usp=sharing

### Describe the solution you'd like

It should allow searching by the combination reference, not just the general product reference.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment] 2022-03-25 09:27
Hello @ocio87 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9727. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-25 09:27
Duplicate of #9727

**Closed as completed by hibatallahAouadni** 2022-03-25 09:27 UTC
Labels: Feature, Duplicate, Invalid
