### ISSUE TITLE
BO - Emails Translations - The TXT version of the email is not updated

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22553] opened 2020-12-23 09:19 UTC
#### Describe the bug

In the BO > International > Translations > Core emails, the Txt version is not updated.

#### Steps to Reproduce

1. Go to BO > International > Translations page
2. Select Type of translation > Email translations
3. Select the type of email content "Body"
4. Select your theme Classic
5. Select your language French
6. Click on Modify
7. In the Core emails > try to modify the translations of the `order_conf` mail with HTML version
![image](https://user-images.githubusercontent.com/16067358/102980624-26539980-4508-11eb-9167-0916c3df96ca.png)
8. Click save
9. Try to check the TXT version of this order_conf email
10. See error => No translations updated
![image](https://user-images.githubusercontent.com/16067358/102980650-2d7aa780-4508-11eb-9aad-f1a5783c7329.png)

PS: this issue is reported by `Christophe Bernon` :slightly_smiling_face: 

#### Additional information

* PrestaShop version: 1769, 177x, develop(1780)
* PHP version: 7.1

**Comment by marionf** [comment] 2020-12-23 10:08
@khouloudbelguith 

This is the wanted behavior as html and txt are differents files and templates, you need to do your modifications in both of them
Modifications done in one are not supposed to be automatically done in the other

**Comment by LouiseBonnard** [comment] 2021-01-07 17:20
Since it is the expected behavior, I close this issue, thanks @khouloudbelguith & @marionf!

**Closed as completed by LouiseBonnard** 2021-01-07 17:20 UTC
Labels: Bug, develop, Minor, BO, Translations, Email, No change required, 1.7.7.x, 1.7.6.9
