### ISSUE TITLE
Catalog > Stock managment > stock vue doesn't load products stocks

### ISSUE THREAD

**Issue by COM1BOUTIK** [PrestaShop/PrestaShop#31973] opened 2023-03-30 08:59 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a multi-shop (2 shops) Prestashop with about 6000 products, 83 000 orders and 285 000 order_detail I'm facing an issue, since the upgrade from PS 1.7.7.4 to 1.7.8.8, it is no more possible to display Catalog > Stock management > stock vue. Page is loaded but product list is never displayed.

I can find that a query is running and never ends : 
UPDATE maisferr_ps_stock_available sa SET sa.reserved_quantity = ( SELECT SUM(od.product_quantity - od.product_quantity_refunded) FROM maisferr_ps_orders o INNER JOIN maisferr_ps_order_detail od ON od.id_order = o.id_order INNER JOIN maisferr_ps_order_state os ON os.id_order_state = o.current_state WHERE o.id_shop = 1 AND os.shipped != 1 AND ( o.valid = 1 OR ( os.id_order_state != 8 AND os.id_order_state != 6 ) ) AND sa.id_product = od.product_id AND sa.id_product_attribute = od.product_attribute_id GROUP BY od.product_id, od.product_attribute_id ) WHERE sa.id_shop = 1

This query comes from fonction updateReservedProductQuantity (line 134 in src/Adapter/StockManager.php)

From the PrestaShop forul I found this article : https://www.prestashop.com/forums/topic/1000108-table-stock_available-mis-%C3%A0-jour-%C3%A0-chaque-appel-de-bo-catalogue-stock-version-1760-1761/

And indeed the only way to be able to get Stocks was to desactivate the call to updatePhysicalProductQuantity in /src/PrestaShopBundle/Entity/Repository/StockRepository.php

### Expected behavior

To be able to manage stocks.

### Steps to reproduce

1. Go to Catalog > Stock management > Stock

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.30

### Your company or customer's name goes here (if applicable).

COM1BOUTIK

**Comment by Hlavtox** [comment] 2023-03-30 09:10
@COM1BOUTIK Hi Xavier, yeah this query is so terribly slow that it makes the whole shop completely unusable.

Do you think you could try this fix https://github.com/PrestaShop/PrestaShop/pull/28854/files and let me know the results?

Or there is yet another PR fixing the same subject - https://github.com/PrestaShop/PrestaShop/pull/31065, you could also try this.

**Comment by hibatallahAouadni** [comment] 2023-04-19 00:52
Hello @COM1BOUTIK 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-04-19 00:52 UTC
Labels: Bug, BO, Stocks, Multistore, Invalid, 1.7.8.8

**Comment by Hlavtox** [comment] 2023-04-19 05:46
@hibatallahAouadni The issue is still there and is quite major for bigger stores, I think it should not be closed…
