### ISSUE TITLE
Upgrade 1.6.1.23 -> 1.7.5.0 | 'database_password' => '_LEGACY******'

### ISSUE THREAD

**Issue by wlauvenberg** [PrestaShop/PrestaShop#12627] opened 2019-01-07 21:25 UTC
Upgrade 1.6.1.23 -> 1.7.5.0
debugging states db-credentials incorrect
checked **/app/config/parameters.php** and see **'database_password' => '_LEGACYxxxxxxxx'** where xxxxxxxx is my original password
changed back to original password > error:
(1/1) PrestaShopDatabaseExceptionTable 'xxxxxxx.ps_authorization_role' doesn't exist<pre>SELECT `slug`,`slug` LIKE "%CREATE" as "add",`slug` LIKE "%READ" as "view",`slug` LIKE "%UPDATE" as "edit",`slug` LIKE "%DELETE" as "delete"FROM `ps_authorization_role` aLEFT JOIN `ps_access` j ON j.id_authorization_role = a.id_authorization_roleWHERE j.`id_profile` = 0</pre>

**Comment by Quetzacoalt91** [comment] 2019-02-19 13:35
Moved from `autoupgrade` repository. The issue is caused by the method `PrestaShopBundle\Install\Upgrade::migrateSettingsFile()` present in the core.

**Comment by khouloudbelguith** [comment] 2019-02-19 13:44
Hi @wlauvenberg,

We are of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12413
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-19 13:44
Duplicate of #12413

**Closed as completed by khouloudbelguith** 2019-02-19 13:44 UTC
Labels: Duplicate
