### ISSUE TITLE
ERROR UPDATING PRESTASHOP

### ISSUE THREAD

**Issue by CreatePublicidad** [PrestaShop/PrestaShop#26922] opened 2021-12-08 14:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello everyone, I am new to this group, I have this problem with my store when updating, I do not know how I can solve it, thank you very much for the help

[PrestaShopDatabaseException]
Table 'createpu_pruebaonline.ps_connections' doesn't exist<br /><br /><pre>SELECT SQL_NO_CACHE `id_guest` FROM `ps_connections` WHERE `id_guest` = 0 AND `date_add` > '2021-12-08 09:10:00' AND id_shop IN (1) ORDER BY `date_add` DESC LIMIT 1</pre>
at line 769 in file classes/db/Db.php

764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }
DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
DbCore->query - [line 663 - classes/db/Db.php] - [1 Arguments]
DbCore->getRow - [line 154 - classes/Connection.php] - [2 Arguments]
ConnectionCore::setNewConnection - [line 97 - classes/Connection.php] - [1 Arguments]
ConnectionCore::setPageConnection - [line 111 - modules/statsdata/statsdata.php] - [1 Arguments]
statsdata->getScriptCustomerPagesViews - [line 69 - modules/statsdata/statsdata.php] - [1 Arguments]

### Expected behavior

Hello everyone, I am new to this group, I have this problem with my store when updating, I do not know how I can solve it, thank you very much for the help

### Steps to reproduce

![image](https://user-images.githubusercontent.com/95761861/145230489-8baa38a7-ece3-48be-9150-fa6fcc1e2cc3.png)

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by hibatallahAouadni** [comment] 2021-12-08 17:24
Hello @CreatePublicidad 

Could you please provide clear and concise steps to reproduce the issue and what was your older PS version before upgrade.
Please check and feedback.

Thanks!

**Comment by CreatePublicidad** [comment] 2021-12-09 03:35
Hello, how are you? I have version 1.7.8.1 and update to 1.7.8.2 and when I put in debugging I get that error, I do not know why it is due, thank you very much for the help

**Comment by CreatePublicidad** [comment] 2021-12-09 03:36
> Hello @CreatePublicidad
> 
> Could you please provide clear and concise steps to reproduce the issue and what was your older PS version before upgrade. Please check and feedback.
> 
> Thanks!

Hello, how are you? I have version 1.7.8.1 and update to 1.7.8.2 and when I put in debugging I get that error, I do not know why it is due, thank you very much for the help

**Comment by florine2623** [comment] 2021-12-09 09:49
Hello @CreatePublicidad ,

I upgraded my shop from 1.7.8.1 to 1.8.7.2, I did not encounter your error.
Do you still have access to your back-office ?
If yes, you could try to rollback to a previous version of your site.

Thanks

**Comment by hibatallahAouadni** [comment] 2021-12-29 11:11
Hello @CreatePublicidad 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-29 11:11 UTC
Labels: Bug, BO, Autoupgrade, Invalid, Module
