### ISSUE TITLE
Unable to delete free gift in cart 1.7.7.4

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#24831] opened 2021-06-07 06:57 UTC
#### Describe the bug

When a free gift is added to cart, we're unable to delete it, thus forcing a customer to accept it. This might be illegal in some countries. If the customer doesn't want the free gift, there is no option to refuse it.

#### Expected behavior

Legally correct behavior is to OFFER the free gift, not to add it to cart. Easy solution would be to display a link Congratulations, you can now "Add your free gift". The link should appear below the cart when minimum cart value that we set in cart rule is reached. 

#### Steps to Reproduce

1. create e free gift cart rule when purchase over certain limit
2. add products to cart
3. see cart and try to delete the free gift

**Screenshots**

![1 Cart Rules](https://user-images.githubusercontent.com/31688689/120972418-03433c00-c76e-11eb-9287-9104ae521194.png)

![2 Cart Rules](https://user-images.githubusercontent.com/31688689/120972442-0a6a4a00-c76e-11eb-869d-cec53d2dc109.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.28

**Comment by hibatallahAouadni** [comment] 2021-06-07 08:20
Hello @mrabsinthe 

When you create the cart rule, generate a code and enable the highlight option:

![image](https://user-images.githubusercontent.com/23308427/120983173-bd8c7080-c779-11eb-95ab-074d098ecc76.jpeg)

Then, the customer can remove the free gift by removing the cart rule.
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment] 2021-06-07 08:52
@mrabsinthe @hibatallahAouadni The problem is, that there shouldn't be the trash icon next to the gift. There is an issue open for this.

And why would anyone want to delete a gift? 👍

**Comment by hibatallahAouadni** [comment] 2021-06-07 09:44
> The problem is, that there shouldn't be the trash icon next to the gift. There is an issue open for this.

@Hlavtox you're talking about this issue #9757

**Comment by Hlavtox** [comment] 2021-06-07 09:46
@hibatallahAouadni Yes exactly. :-)
@mrabsinthe Use my temp fix from here - https://github.com/PrestaShop/PrestaShop/issues/9757#issuecomment-691047001

**Comment by mrabsinthe** [comment] 2021-06-07 10:41
@hibatallahAouadni you've missed my point completely and it makes me think, why bother reporting bugs? I'm very well aware of the fact that you can generate a code, but I was mentioning a bug when I DO NOT want to use a code. And if there is a trash icon that does nothing and you can recreate it (I'm sure you can), it is a bug, as simple as that. And as I already mentioned, customers MUST have an option to remove the gift.
@Hlavtox quite often, actually. Imagine you have several categories (glass, metal, wood) and since you cannot offer a gift per category (only per product), that gift might not appeal to those shopping for wood if the gift is a glass. If you look at some well established shops that do offer gifts, they ALWAYS let you choose the gift you want. And that is exactly what is missing here, the whole "free gift" idea needs modern, customer friendly approach. Something like this idea below...
![mockup cart](https://user-images.githubusercontent.com/31688689/121002367-92f7e300-c78c-11eb-8f5f-8f8162b7459d.png)

**Comment by matks** [comment] 2021-06-07 12:32
> @hibatallahAouadni you've missed my point completely and it makes me think, why bother reporting bugs?

Please remember we must all abide by the Code of Conduct https://github.com/PrestaShop/PrestaShop/blob/8a745499c50fce465e088d7cd49efe30aae6f779/CODE_OF_CONDUCT.md

> Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members

Misunderstandings and confusion happen, especially when writing and when using a language that is foreign for its users. The solution is to calmy re-explain, with sometimes other words, the thing. Carrying an idea, an information from a person to another person who are strangers to each other is not easy.

**Comment by hibatallahAouadni** [comment] 2021-06-15 16:48
Hello @mrabsinthe 

Could you please check https://github.com/PrestaShop/PrestaShop/issues/9757#issue-353047312 I just add the specs that @marionf has working on it and your issue is already mentioned it (to be fixed).
So, we are aware of this issue and it is already in our debug backlog. This issue is a duplicate of #9757. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-15 16:49
Duplicate of #9757

**Closed as completed by hibatallahAouadni** 2021-06-15 16:48 UTC
Labels: Bug, FO, Duplicate, Shopping carts FO, 1.7.7.4
