### ISSUE TITLE
Free shipping for orders above 75 CAD is not working

### ISSUE THREAD

**Issue by CArlvJ1N0N8** [PrestaShop/PrestaShop#10954] opened 2018-10-10 12:42 UTC
**Describe the bug**
We have defined in the preferences for the transport that orders are free of shipping costs when over 75 
 CAD, but it doesn't seem to be taken into account as you can see in the attached screenshot.

**To Reproduce**
1. Create a cart with products to get a cart value of over 75 CAD. 
2. It will tell you the shipping is for free as long as you have not provide your adress.
3. Create your customer account by registering yourself
4. See the new shipping cost in the cart, although you should have a free shipping since you have a cart value above 75 Cad. 

**Screenshots**

![free shipping as of 75 cad](https://user-images.githubusercontent.com/42921237/46736489-2a68a900-cc67-11e8-8fbd-371439c34ade.JPG)

![no more free shipping above 75 cad](https://user-images.githubusercontent.com/42921237/46736969-58022200-cc68-11e8-8766-2eed775d4a4a.JPG)
![panier not registered](https://user-images.githubusercontent.com/42921237/46736970-589ab880-cc68-11e8-9dd7-f3af05b9c942.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0.27-0+deb9u1

**Comment by khouloudbelguith** [comment] 2018-10-10 13:39
Hi @CArlvJ1N0N8,

Could you please navigate to the Localization / Currencies page & check the exchange rate.
Thanks to provide us with a screenshot.
Thanks!

**Comment by CArlvJ1N0N8** [comment] 2018-10-10 20:45
Canadian dollar is the default currency 

![echange](https://user-images.githubusercontent.com/42921237/46764976-e4820400-ccab-11e8-9e30-fd1f81bb7e88.JPG)

**Comment by khouloudbelguith** [comment] 2018-10-11 09:45
Hi @CArlvJ1N0N8,

I did not manage to reproduce the issue with PS 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1fZTHAluBaQH2c0Five4l2SXmWCOBVMRt/view
Have you tried to contact the theme author? thanks to check with them this issue & feedback.
Thanks!

**Comment by CArlvJ1N0N8** [comment] 2018-10-11 10:11
OK connecting to the theme author. 
But lacking reactivity on that side.

**Comment by khouloudbelguith** [comment] 2018-10-11 10:15
@CArlvJ1N0N8, As it's not the default theme, provided by Prestashop, we can't do anything with this before their feedback.
Thanks!

**Comment by CArlvJ1N0N8** [comment] 2018-10-11 10:18
I will do the test in my DEV site with the default theme provided by Prestashop, if result is the same, we can say it is not theme related.

**Comment by khouloudbelguith** [comment] 2018-10-11 10:21
@CArlvJ1N0N8, OK thanks!
Waiting for your feedback.

**Comment by CArlvJ1N0N8** [comment] 2018-10-11 11:19
Seems to be exactly the same issue, investigating further, but having same reactions...

**Comment by khouloudbelguith** [comment] 2018-10-11 11:33
Hi @CArlvJ1N0N8,

Could you please provide me the credentials of your shop (admin) to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by CArlvJ1N0N8** [comment] 2018-10-16 17:16
In order to have the free shipping option for orders above 75 $ i have used following instructions 

For free shipping, I recommend doing the following (taken from the module documentation, you can ignore "Canada" zone parts if you don't need to restrict it to just Canada):

1. Create a new zone called "Canada" (International > Locations > Zones menu).
2. Edit the country "Canada" and change its zone from "North America" to "Canada" (International > Locations > Countries menu). Zones are only used for Shipping, so update any other carriers with the new Zone if needed.
3. Create a new carrier called "Free Shipping" (or any other name).
4. Set its Billing to 'According to total price'.
5. Set its Out-of-range behavior to 'Disable Carrier.
6. Set its range to '>= 75' and '< 999999'.
7. Deselect all zones except Canada and set US to 0.00

This will display free shipping for Canada orders when the order total is above $75.00. To disable one or more carriers when free shipping is enabled, please do the following for each carrier.

1. Edit a Canada Post carrier.
2. Set its Billing to 'According to total price'.
3. Set its Out-of-range behavior to 'Disable Carrier'.
4. Set its range to '>= 0' and '< 75'.

This will disable that particular carrier when the order total is above $75.00. Repeat for each carrier you wish to disable.

This is helping right now, but there is still an issue, for example the 75 $ takes into account the taxes. 
So i have to change some other tpl for the carrier and the cart but it would put me in some troubles for the next Prestashop upgrade 

So it is a pity that the field free delivery in the transport does not work... 

Carl

**Comment by khouloudbelguith** [comment] 2018-10-17 14:35
Hi @CArlvJ1N0N8,

Yes, you are right, Price Ranges takes into account the taxes.
![image](https://user-images.githubusercontent.com/16067358/47093698-063e3680-d22a-11e8-9d2a-39314079b515.png)
![image](https://user-images.githubusercontent.com/16067358/47093987-98ded580-d22a-11e8-8e3f-92499f7d9de8.png)
@marion what do you think.
It could be an improvement issue.
Thanks!

**Comment by CArlvJ1N0N8** [comment] 2018-10-17 15:18
Please be aware that the second screenshot with Free shipping starts at 75  is not working on our side. 

That's the reason why we have added the ranges as shown in the first screenshot. 

There is a work around for the amount being tax included 
"I've encountered this before, please try the following (I've only tested this on previous versions of PS, so make backups of the two files before modifying and make sure to test it yourself):

Open the file /classes/Cart.php
Find the function "public function getPackageShippingCost"
Inside this function (between the open "{" and closing "}" curly braces underneath that function), you will find three places where the following function will appear: "$this->getOrderTotal(true ........)" (you can search for "getOrderTotal").
For all 3 places where "getOrderTotal" appears in the getPackageShippingCost function, change "true" to "false", example:


$order_total = $this->getOrderTotal(false, Cart::BOTH_WITHOUT_SHIPPING, $product_list);



In the same file /classes/Cart.php
Find the function "public function isCarrierInRange"
Do the same as before, change "getOrderTotal" to false, example:


$this->getOrderTotal(

false,

Cart::BOTH_WITHOUT_SHIPPING

)



In the file /classes/Carrier.php
Change getOrderTotal from true to false. It only appears once in this entire file, so this one is easier. Example:


$cart->getOrderTotal(false, Cart::BOTH_WITHOUT_SHIPPING)



What this modification does is forces the shipping cost ranges to be tax excluded instead of included. You will have to repeat this modification every time you upgrade your PS version. Please test it thoroughly and make sure to backup the files so you can rollback easily if there's any issues."

Unfortunately, i am not confident enough to do this change, also if i do this change on my side i will be required to do it again for every single upgrade i will be doing with Prestashop. 

Can you confirm if this is safe or if i missed anything? 

Thanks, 

Carl

**Comment by khouloudbelguith** [comment] 2018-10-17 16:32
Hi @CArlvJ1N0N8,

Below are different ways to help us to add this improvement:
- If you found a module that solves the issue, please add a comment with a link to it so it is possible to share this knowledge with other impacted users
- If this is critical for your business but you don't have developer skills, please consider hiring a freelancer or an agency
- If you are a developer, you can open a pull request on GitHub with your fix: https://github.com/PrestaShop/PrestaShop/tree/develop

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-05 10:19
Hello @CArlvJ1N0N8 

As a bug, we couldn't reproduce it :wink: 
As an improvement, I don't see it critical to add a label **Tax included** besides the input **Free shipping stars at**.
But let's ping the Product Team. Please stay tuned !

> Yes, you are right, Price Ranges takes into account the taxes.
![image](https://user-images.githubusercontent.com/16067358/47093698-063e3680-d22a-11e8-9d2a-39314079b515.png)

---
>![image](https://user-images.githubusercontent.com/16067358/47093987-98ded580-d22a-11e8-8e3f-92499f7d9de8.png)
@marion what do you think.
It could be an improvement issue.
Thanks!

Ping @PrestaShop/product-team I don't think this proposed improvements is necessary, but if you think not, I believe we need to change the issue description. So, shall we change this issue description or just close the issue?

**Comment by florine2623** [comment] 2022-07-01 12:37
Hello @CArlvJ1N0N8 ,

I couldn't reproduce your issue as per my screenrecord :

https://user-images.githubusercontent.com/16019289/176895856-830406aa-f4c8-4eef-9907-9d885bd82c4e.mov



Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2022-07-01 12:37 UTC
Labels: Bug, FO, Carriers, Shipping preferences, 1.7.4.3, Invalid
