### ISSUE TITLE
show href in bold

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23329] opened 2021-02-05 01:28 UTC
![image](https://user-images.githubusercontent.com/62474824/106976954-abfa7400-6759-11eb-8aff-45f60eaa7666.png)

I think the href should be shown in bold

**Comment by hibatallahAouadni** [comment] 2021-02-22 15:19
Hello @alfonsolr09 

Could you please provide clear steps to reproduce the issue, your PS store version and your GDPR module version.

![image](https://user-images.githubusercontent.com/23308427/108728549-ffc2d680-7529-11eb-8cd1-7b577ca7c990.png)

Thanks!

**Comment by alfonsolr09** [comment] 2021-02-22 15:37
you got it right but i think it should be in bold.
Please change the language to spanish and check it

**Comment by hibatallahAouadni** [comment] 2021-02-22 18:58
Hello @alfonsolr09 

I changed my language to Spanish, check my screenshot below:

![image](https://user-images.githubusercontent.com/23308427/108755718-e4ff5a80-7547-11eb-8fd5-194652b1a99b.png)

This part is in English cause I have missing translations :sweat_smile: 
I think it's related to your theme, could you please switch your theme to the default and check if you still encounter the issue.

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-14 21:53
Hello @alfonsolr09 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-14 21:53 UTC
Labels: Bug, 1.7.x, FO, GDPR, No change required
