### ISSUE TITLE
AdminCartRules allways uses price with tax

### ISSUE THREAD

**Issue by tiago-pinto** [PrestaShop/PrestaShop#12182] opened 2019-01-16 16:44 UTC
**Describe the bug**
I created a discount rule of 10% of the price of the cart products without tax included, but the discount applied does have that tax included.

Example:
Product price(without tax): 48,94€
Product price(with tax): 60,20€
Tax Percentage: 23%(Portugal)
Discount Percentage: 10%(Tax excluded)
Calculated discount:  6,02€ ( Based on price with tax)
Disered discount: 4,89€ (Based on price without tax)

(See screenshots at the bottom)

**To Reproduce**
1. Go to Catalog -> Discounts, create a rule of 10% discount on order without shipping
2. Make a order with any product, apply the discount code and the calculantion should be made

**Screenshots**
Cart page with the values above.
![image](https://user-images.githubusercontent.com/46755718/51263628-8c465680-19ac-11e9-85f7-ae1e86994a23.png)
Rule screenshots:
-Info:
![image](https://user-images.githubusercontent.com/46755718/51263819-ee06c080-19ac-11e9-9c94-b8afb145e556.png)

-Conditions:
![image](https://user-images.githubusercontent.com/46755718/51263786-df200e00-19ac-11e9-943b-35aa81638db9.png)

-Actions:
![image](https://user-images.githubusercontent.com/46755718/51263801-e6dfb280-19ac-11e9-8377-c6d63690d4d3.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-01-16 16:54
Hi @tiago-pinto,

Thanks for your report & for the fix.
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9856, please follow #9856
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-16 16:55
Duplicate of #9856

**Closed as completed by khouloudbelguith** 2019-01-16 16:54 UTC
Labels: Duplicate

**Comment by tiago-pinto** [comment] 2019-01-16 17:15
I did apply @urimarti fix as an override and I still get the same issue as I reported

New example(after the override was applied):
![image](https://user-images.githubusercontent.com/46755718/51266132-4a201380-19b2-11e9-99bb-3d576ee31a4c.png)

**Comment by khouloudbelguith** [comment] 2019-01-16 17:20
@tiago-pinto, the #9856 is added to our bug roadmap.
@urimarti has a just suggestion fix.

**Comment by urimarti** [comment] 2019-01-16 18:48
@tiago-pinto  First of all, i'm using Prestashop 1.6.1.23. Be ensure that SQL is working in new prestashop version.

```
SET @id_country = 6; -- put here your id_country default
SET @id_tax_group = 23; -- put here the id_tax_group you want to check
SELECT t.rate
FROM ps_tax_rules_group trg
INNER JOIN ps_tax_rule tr ON tr.id_tax_rules_group = trg.id_tax_rules_group AND tr.id_country = @id_country AND tr.id_state = 0
INNER JOIN ps_tax t ON t.id_tax = tr.id_tax
WHERE trg.id_tax_rules_group = @id_tax_group
GROUP BY 1;
```

It should give you only one number (in my case, 21). That is the 21% of taxes.

**Explaining the override:**
What you have to do is on function PriceCalculation() in class Product.php is to get your default shop tax and check the difference with the user's current tax.

```
$total_tax = Tax::getProductTaxRate($id_product); // We get current's tax
$prod = new Product($id_product); // we call the current product
/* we get default tax in our shop.
* How? We get the range from ps_tax with PS_COUNTRY_DEFAULT (in ps_configuration) and
* id_tax_rules_group from the product we called
*/
$default_tax = Db::getInstance()->getRow('
    SELECT t.rate
    FROM '._DB_PREFIX_.'tax_rules_group trg
    INNER JOIN '._DB_PREFIX_.'tax_rule tr ON tr.id_tax_rules_group = trg.id_tax_rules_group AND tr.id_country = '.(int)Configuration::get('PS_COUNTRY_DEFAULT').' AND tr.id_state = 0
    INNER JOIN '._DB_PREFIX_.'tax t ON t.id_tax = tr.id_tax
    WHERE trg.id_tax_rules_group = '.(int)$prod->id_tax_rules_group.'
    GROUP BY 1');
$default_tax = $default_tax['rate'];
$difference_tax = (float)$default_tax - (float)$total_tax; // we calculate the difference betwin both taxes
if($specific_price['reduction_tax'] == 1){
    $specific_price_reduction = $specific_price_reduction / (1+($difference_tax/100)); 
} else {
    $specific_price_reduction = $product_tax_calculator->addTaxes($specific_price_reduction);
}
```
