### ISSUE TITLE
Generate combinations shows Generate combinations for all stores but the shop is not multistore

### ISSUE THREAD

**Issue by pelechano** [PrestaShop/PrestaShop#31431] opened 2023-02-17 16:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Installed 8.1 beta version in the product page when generating combinations it shows a confusing checkobox

Generate combinations for all stores

![imagen](https://user-images.githubusercontent.com/29916491/219711213-7e1e9433-b091-428b-a594-514d502719ec.png)

### Expected behavior

Only show this message in a multistore installation

### Steps to reproduce

1 Enter to edit some product
2 In the Combinations tab press Generate combinations

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment] 2023-02-20 13:29
Hello @pelechano ,
After enabling the **New product page** in the  **New & Experimental Features** page 
 I reproduce your issue  : 

**PS810 NOK** 
![Capture-d’écran-du-2023-02-20-14-15-14-png-1486×751-](https://user-images.githubusercontent.com/31663369/220119567-b26cb282-a39e-4b1c-a85e-14626a608fd5.png)


**PS800/ PS801 OK**

![Capture-d’écran-du-2023-02-20-14-15-01-png-1694×791-](https://user-images.githubusercontent.com/31663369/220119448-9e6b69bb-0970-491e-ac42-49e25235ec0a.png)

So it's regression !

Could you please provide us if  you reproduce the isse with a PPV2 product ? 
Please check and feedback ! 

Thank you

**Comment by pelechano** [comment] 2023-02-20 14:52
Yes the PPV2 is enabled (by default)
![imagen](https://user-images.githubusercontent.com/29916491/220138923-c53e9b7b-a714-4e25-9a20-abd8e6c7fb2b.png)

**Comment by hibatallahAouadni** [comment] 2023-02-21 04:45
Hello @pelechano 

Thanks for your feedback!
It's a new feature in 8.1.0, you can check that option to generate the combination in all shops ☺️ 
Closing the issue as it's not a bug 😅 

Thanks for your understanding 🙏

**Closed as completed** 2023-03-16 16:04 UTC
Labels: Bug, Minor, BO, Regression, Combinations, Ready, PR available, Verified, 8.1.x
