### ISSUE TITLE
Error on the amount of total orders (total-order-amount)

### ISSUE THREAD

**Issue by richo8** [PrestaShop/PrestaShop#16221] opened 2019-10-30 23:19 UTC
**Describe the bug**
From Back office, I have a bug on the amount of the order. (Prestashop 1.7.6.1 with php7.1.3).
Go to Customers > Customers.
All amounts are wrong.
Going into the detail of the order we see this gap.

**To Reproduce**
1. On back office Go to Customers > Customers.
2. Click on the customer's "show buton"
3. Scroll down to the orders

**Screenshots**
Total paid: 12,10 € on one side and
Valid orders: 1 for a total amount of 13.76 € each other.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: php7.1.3
![error2](https://user-images.githubusercontent.com/57200303/67906142-fdd64680-fb73-11e9-8449-5c8f864c0cb1.jpg)
![error](https://user-images.githubusercontent.com/57200303/67906143-fdd64680-fb73-11e9-94d4-a96df3bad8da.jpg)

**Comment by khouloudbelguith** [comment] 2019-10-31 08:33
Hi @richo8,

I did not manage to reproduce the issue with PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/67931106-816a5480-fbc1-11e9-839a-de601a6af5ea.png)

I attached a screen record
https://drive.google.com/file/d/1DIPe3nRolMuxSkSnWsgBMAFn0wnIwHJv/view
In your case the total amount > total amount, 
The total amount is displayed with tax included & the total spent is displayed with tax excluded?
Could you please check the orders with ID=7 & ID=65?

Thanks!

**Comment by Cedricdelcroix** [comment] 2019-11-24 14:52
Hey I have similar issue

![image](https://user-images.githubusercontent.com/6152553/69496429-6940d900-0ed2-11ea-8894-2631152e8a86.png)

**Comment by khouloudbelguith** [comment] 2019-11-25 08:50
Hi @Cedricdelcroix,

I think that this is another problem.
your total is multiplied.
What is the exact version PS did you use?
did you use only the currency €?
This is the currency by default?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-24 07:49
Hi @richo8,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-24 07:49 UTC
Labels: Bug, BO, Customer, No change required, 1.7.6.1
