### ISSUE TITLE
Multistore -> imported products image issue

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#20220] opened 2020-07-18 02:07 UTC
On the imported products from another store, the PS does not erase the imported images on the backend but it does not show them on the frontend.

Steps:
-on a full functional store 1.7.6.7
-activate multistore
-create a new group
-create a new store on the new group
-import all from the first store to the new one
-go to product
-erase all the imported pictures from the previous store
-add new pictures
-clic on save or go to catalogue
-edit the same product and you will see the old and new pictures
-go to frontend search for the product
-you will see only the new pictures

workaround:
-go to the imported product
-duplicate the product
-edit, erase and add the new pictures
-done

**Comment by florine2623** [comment] 2020-07-23 15:10
Hi @msaustral ,
I need more detail about your issue.
When you state : erase all the imported pictures from the previous store
In which shop you I be in ? When you erase all picture, do you do it directly from the server ? 
Thanks

**Comment by msaustral** [comment] 2020-07-23 15:38
Hi, at the end in the new store I had to create new products, it was the only way to not showing the pictures of the products that were imported from the first store.

It seem that the image does not lose the link with the product from the first store

on the new store go to catalogue -> products -> open an imported product -> delete all imported images -> add new onece -> save

re open the same imported product -> there are the imported image again plus the new images

on the front -> only the new images are show

I hope this helps.

**Comment by florine2623** [comment] 2020-07-23 16:36
Ok, so in the 2 stores in your multishop environment, you wanted the products to have different images. I understand.

In the multistore env, you can chose directly what data you want to import. If you didn't need the images, you could have uncheck this option :
![Capture d’écran 2020-07-23 à 18 35 26](https://user-images.githubusercontent.com/16019289/88313128-56a5ca80-cd13-11ea-8cac-e963c7ad0ee6.png)

**Comment by msaustral** [comment] 2020-07-23 17:10
Hi ok, thank you for the info for future stores, but still the behavior of the new store with the imported images does not seam to be right.
 
Have a good day.

**Comment by florine2623** [comment] 2020-07-24 14:44
When you say :
>erase all the imported pictures from the previous store

Do you erase all images from server ? if yes, which folders do you delete ?

>add new pictures

Do you add the picture manually or another way ?

**Comment by msaustral** [comment] 2020-07-24 14:56
Hi
Do you erase all images from server ? if yes, which folders do you delete ? -> no because they are needed on the first store

Do you add the picture manually or another way ? -> yes manually as the process that I describe before:

on the new store go to catalogue -> products -> open an imported product -> delete all imported images -> add new onece -> save

re open the same imported product -> there are the imported image again plus the new images

on the front -> only the new images are show

**Comment by florine2623** [comment] 2020-07-24 15:15
Do you have normal products or combinations product ?
If you have combination products, you need to chose the right image for the right combination to show :
![Capture d’écran 2020-07-24 à 17 15 09](https://user-images.githubusercontent.com/16019289/88406648-405e4400-cdd1-11ea-977f-4e1934a115d9.png)

**Comment by msaustral** [comment] 2020-07-24 19:04
Hi, please try to reproduce the issue following the describe steps, I have not mention any combine product.

on the new store go to catalogue -> products -> open an imported product -> delete all imported images -> add new onece -> save

re open the same imported product -> there are the imported image again plus the new images

on the front -> only the new images are show

**Comment by khouloudbelguith** [comment] 2020-07-27 14:29
Hi @msaustral,

I manage to reproduce the issue with PS1.7.6.7.
But it is fixed in the next release 1770
https://drive.google.com/file/d/1A_9BhnO0MqYSUaZfEMXcbDBkYq6ODCd5/view?usp=sharing
It is fixed with this PR:https://github.com/PrestaShop/PrestaShop/pull/15909
Your ticket is a duplicate of #12061
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-27 14:29
Duplicate of #12061

**Closed as completed by khouloudbelguith** 2020-07-27 14:29 UTC
Labels: Duplicate, Image, Multistore, 1.7.6.7
