### ISSUE TITLE
[Checkout][FO] Fatal error when module hookDisplayPaymentEU returns another thing instead of array 

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#18229] opened 2020-03-19 16:13 UTC
#### Describe the bug

Fatal error when module `hookDisplayPaymentEU` returns another thing instead of array 

#### Expected behavior

Avoid fatal error when module `hookDisplayPaymentEU` returns another thing instead of array

#### Steps to Reproduce

1. Go to checkout page in FO
2. See this is Ok !
3. Now ... install this module  : [pululuk.zip](https://drive.google.com/open?id=1DeCGZWtkShyjJqIUvQNf9z_nXrV3_bQW) or in another module add : 
```php
public function install(){ 
      ... etc etc
      $this->registerHook('displayPaymentEU')
      ... etc etc
}
```

and 
```php
public function hookDisplayPaymentEU($params){
	return null;
} 
```
4. Return to checkout page in FO, See fatal error

**Screenshots**

https://drive.google.com/file/d/1cV4VzhN9NA9uYwTmTDj8RDjuGW1mBWZH/view
#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-03-19 16:51
Hi @PululuK,

I manage to reproduce the issue with PS1.7.6.4 and PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/77092484-26b78500-6a0a-11ea-91d2-86de71c60b1f.png)
I’ll add this to the debug roadmap.

Thanks!

**Comment by PierreRambaud** [comment] 2021-01-21 14:42
I'm more in favor of closing this issue and the associated pull request.
Hooks have types and predefined return values. If you intend to use a hook, you're responsible for doing something consistently. 
Otherwise, this means we have to decrease PrestaShop performance by controlling all hooks because modules are malformed :(

**Comment by matks** [comment] 2021-04-24 12:27
Hi @PierreRambaud @PululuK can we discuss again about this status ?

I kind of agree with @PierreRambaud that it's the module responsibility, not the Core responsibility, to deal with this. Also I see the PR has got stale since one year https://github.com/PrestaShop/PrestaShop/pull/18230

I am not against the PR https://github.com/PrestaShop/PrestaShop/pull/18230 but I find it strange to mark this issue as a `Major` bug

**Comment by fabienvallon** [comment] 2022-01-03 10:04
@matks / @PierreRambaud  : Can we close this bug ?

**Comment by PierreRambaud** [comment] 2022-01-04 09:26
Yes, I'm closing it, we are not responsible for the wrong usage of hooks.

**Closed as completed by PierreRambaud** 2022-01-04 09:26 UTC
Labels: Bug, Major, FO, Modules, No change required, 1.7.5.2, Checkout, PR available, 1.7.6.3, 1.7.6.4
