### ISSUE TITLE
Meta::getPages returns unexpected values

### ISSUE THREAD

**Issue by dev-innova** [PrestaShop/PrestaShop#26944] opened 2021-12-10 13:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The method getPages() from class Meta should return an associative array with php_self property on controllers. For example, in prestashop 1.6 the method returns the following piece of array:

["prices-drop"]=> "prices-drop"
["best-sales"]=> "best-sales"

But those controllers are on folder controllers/front/listing, so when the method try to get properties by reflection, the class name is not correctly get. 

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Meta.php#L100

$className = str_replace('.php', '', $file);
$reflection = class_exists($className) ? new ReflectionClass(str_replace('.php', '', $file)) : false;
$properties = $reflection ? $reflection->getDefaultProperties() : []; 

On those listing controllers, the name of the classes includes the **listing** folder:

string(28) "listing/PricesDropController"
string(32) "listing/PricesDropController.php"
string(27) "listing/BestSalesController"
string(31) "listing/BestSalesController.php"

and the returning piece of array is quite different:

["archivo pricesdrop (en directorio listing)"]=> "pricesdrop"
["archivo bestsales (en directorio listing)"]=> "bestsales"

### Expected behavior

It should return the same array as it returns on Prestashop 1.6

["prices-drop"]=> "prices-drop"
["best-sales"]=> "best-sales"

### Steps to reproduce

It happens on all prestashop 1.7 versions that has listing controllers, just calll Meta::getPages() and check results

### PrestaShop version(s) where the bug happened

1.7.6.8

**Comment by hibatallahAouadni** [comment] 2021-12-13 14:19
Hello @dev-innova 

Could you please provide clear and concise steps to reproduce :pray: 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-30 10:47
Hello @dev-innova 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-30 10:47 UTC
Labels: Bug, CO, Taxes and Prices, Best Sellers, 1.7.6.8, Invalid, Module
