### ISSUE TITLE
Autoupgrade not updating modules with 302 error

### ISSUE THREAD

**Issue by krasnycz** [PrestaShop/PrestaShop#12012] opened 2019-01-03 14:27 UTC
When I try upgrade PS 1.7.4.2 to 1.7.5.0 using autoupgrade all seems to go fine according to the log, but modules are not updated. I have same issue on multiple servers. I tried to disable overrides and also native modules.

Digital Ocean server with PHP 7.1.
Autoupgrade version 4.5.1

Attaching log file from autoupgrade. 

In the inspector it seems to generated the following error instead for upgrading the module. 

Request URL: https://dev.domain.cz/adminX/ajax.php?rand=1546524812367
Request Method: POST
Status Code: 302

I can see the following record in the apache_phpstack_access log:

1.2.3.4 - - [03/Jan/2019:14:13:32 +0000] "POST /adminX/ajax.php?rand=1546524812367 HTTP/1.0" 302 745 "https://dev.domain.cz/adminX/index.php?controller=AdminSelfUpgrade&token=29dbed71eb961bc8afbbfd6cbc381fff" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"

In the var/log the following errors are being generated:

[2019-01-03 15:12:14] console.ERROR: Error thrown while running command "doctrine:cache:clear-metadata --flush=1". Message: "Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI." {"exception":"[object] (LogicException(code: 0): Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI. at /home/123.cloudwaysapps.com/ABC/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php:89)","command":"doctrine:cache:clear-metadata --flush=1","message":"Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI."} []
[2019-01-03 15:12:14] console.DEBUG: Command "doctrine:cache:clear-metadata --flush=1" exited with code "1" {"command":"doctrine:cache:clear-metadata --flush=1","code":1} []
[2019-01-03 15:12:14] console.ERROR: Error thrown while running command "doctrine:cache:clear-query --flush=1". Message: "Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI." {"exception":"[object] (LogicException(code: 0): Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI. at /home/123.cloudwaysapps.com/ABC/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php:89)","command":"doctrine:cache:clear-query --flush=1","message":"Cannot clear APC Cache from Console, its shared in the Webserver memory and not accessible from the CLI."} []
[2019-01-03 15:12:14] console.DEBUG: Command "doctrine:cache:clear-query --flush=1" exited with code "1" {"command":"doctrine:cache:clear-query --flush=1","code":1} []

Any idea how to troubleshoot this issue? This installation has been previously autoupgraded multiple times without any issues. I tried different instance 1.7.2.2 -> 1.7.5.0 with same result. The DO instance is installed thru cloudways.

[log.txt](https://github.com/PrestaShop/PrestaShop/files/2724039/log.txt)

**Comment by khouloudbelguith** [comment] 2019-01-03 14:45
Hi @krasnycz,

So, the upgrade of your shop is done successfully, but your native modules are not updated?
After upgrading your shop, in the Modules => Modules & Services pages => Updates Tab, you can not upgrade your modules manually?
In your log files, I found some warnings about your `PrestaAdapter` module.
Thanks!

**Comment by krasnycz** [comment] 2019-01-03 14:49
Well I presume the autoupgrade module should work same way as it was before? After updating the database there is a phase to update modules X from Y. Or it was changed?

I reversed the staging to 1.7.4.2 and deleted all non-native modules. Prod.log now gives me

[2019-01-03 15:40:24] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /addons/login": Method Not Allowed (Allow: POST)" at /home/123.cloudwaysapps.com/ABC/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 143 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /addons/login\": Method Not Allowed (Allow: POST) at /home/123.cloudwaysapps.com/ABC/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:143, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/appProdProjectContainerUrlMatcher.php:1386)"} []

**Comment by krasnycz** [comment] 2019-01-03 14:53
After the upgrade performance is giving Error 500 as described in the #11784. The update process was obviously not completed as ajax update gave 302 error but wrote the log that all was done. The problem is poor logging.

**Comment by khouloudbelguith** [comment] 2019-01-03 14:54
@krasnycz, in my case, after the upgrade from PS1.7.4.4 to PS1.7.5.0, the upgrade is done successfully but there are no upgrade for the native module.
![image](https://user-images.githubusercontent.com/16067358/50643963-cf95d380-0f6f-11e9-9cba-c92e53f1b836.png)
ping @Quetzacoalt91 what do you think?
Thanks!

**Comment by krasnycz** [comment] 2019-01-03 15:02
When I enable debug mode in the config file I can access the performance page without any problem. I think this issue is related with permissions and autoupgrade.

**Comment by khouloudbelguith** [comment] 2019-01-03 15:04
@krasnycz, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by krasnycz** [comment] 2019-01-03 15:11
I did manually rm all files/foldes in cache. Also I can clean it when debug is enabled. I can access the performance after clearing the cache. However I still believe the update was not done correctly.

**Comment by krasnycz** [comment] 2019-01-03 15:25
![image](https://user-images.githubusercontent.com/15078106/50645507-04a42500-0f74-11e9-84e4-1cf8404cdb5c.png)

To ensure you understand the issue. This part of the autoupgrade process is completely skipped. No update of modules at all. Instead in the inspector only the error described above.

**Comment by krasnycz** [comment] 2019-01-03 15:28
Seems multiple person describing exactly same issues at the comments at http://build.prestashop.com/news/prestashop-1-7-5-0-available/

**Comment by khouloudbelguith** [comment] 2019-01-03 16:46
@krasnycz, I discussed with our developer & I checked that before launching the upgrade, you need to let the module recover the list of files to be modified, the modules to be upgraded etc..
You need to wait for this part to be ready before launching the upgrade.
![image](https://user-images.githubusercontent.com/16067358/50649874-45ee0200-0f7f-11e9-83d4-42a112f02d18.png)

Thanks to check & feedback!

**Comment by krasnycz** [comment] 2019-01-04 07:36
@khouloudbelguith This is not the case. I waited and checked the files before the update. Page was comletely loaded and no ajax was runing active job.

**Comment by khouloudbelguith** [comment] 2019-01-04 08:06
Hi @krasnycz,

I launched again a new upgrade from PS1.7.4.4 to PS1.7.5.0 using the 1-click upgrade v4.5.1 & it ok.
All the modules are upgraded in my log
```
Archive extracted
The files of module blockreassurance have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module contactform have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module cronjobs have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module dashactivity have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module dashgoals have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module dashproducts have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module dashtrends have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module gamification have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module graphnvd3 have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module gridhtml have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module gsitemap have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module pagesnotfound have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_banner have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_buybuttonlite have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_categorytree have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_checkpayment have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_contactinfo have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_currencyselector have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_customeraccountlinks have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_customersignin have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_customtext have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_emailsubscription have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_facetedsearch have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_faviconnotificationbo have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_featuredproducts have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_imageslider have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_languageselector have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_legalcompliance have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_linklist have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_mainmenu have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_searchbar have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_sharebuttons have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_shoppingcart have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_socialfollow have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_themecusto have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module ps_wirepayment have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module sekeywords have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsbestcategories have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsbestcustomers have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsbestmanufacturers have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsbestproducts have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsbestsuppliers have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsbestvouchers have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statscarrier have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statscatalog have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statscheckup have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsdata have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsequipment have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsforecast have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statslive have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsnewsletter have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsorigin have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statspersonalinfos have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsproduct have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsregistrations have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statssales have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statssearch have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsstock have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module statsvisits have been upgraded.
Using class ZipArchive...
Archive extracted
The files of module welcome have been upgraded.
```
But, when I tried to go to the BO => Modules & Services => Updates Tab, there are still native modules not upgrated => which is wrong.
![image](https://user-images.githubusercontent.com/16067358/50678215-edaa1500-0ffd-11e9-9554-8629613c1642.png)
All checked all those modules, I found that they are successfully upgraded.
https://drive.google.com/file/d/1rQSvYv7JFD3DKRBXWEkOycpuamNEJ4C5/view
Ping @Quetzacoalt91 
Thanks!

**Comment by krasnycz** [comment] 2019-01-04 08:18
@khouloudbelguith This is your standard answer for any issue reported. I do not contradict that the autoupgrade might work on some installations/servers however the purpose of this place is to resolve issues/bugs and obviously me and many other users facing similar issue. I just tried to show you that PS autoupgrade log shows the upgrade was done but it was not. The error reporting in the PS is very poor and there is almost no way to debug this problem.

I deleted all 3rd party modules before installa and disabled overrides. Result is same.

**Comment by khouloudbelguith** [comment] 2019-01-04 08:30
Hi @krasnycz,

I attached a video recording to show you that there is an issue which is the list of Updates module which is not correct.
Your issue cannot be reproduced on a clean 1.7.4.4 to 1.7.5.0 upgrade, so your issue may not be caused by Prestashop but by some server configuration or something else on your side, that's why I assigned your issue to our developers to understand how we can reproduce your issue.
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, we recommended not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
Thanks for your understanding!

**Comment by krasnycz** [comment] 2019-01-04 08:40
Well I unsed autoupgrade to update this installation multiple times without any issue. Same server and no core files modified. As I stated before I manually uninstalled all 3rd party modules but result is same. I will try clone the instance to different server and give it a try.

**Comment by khouloudbelguith** [comment] 2019-01-04 08:46
@krasnycz, ok.
Thanks!

**Comment by krasnycz** [comment] 2019-01-04 08:57
@khouloudbelguith Tried different server with PHP 7.0. Same results.

**Comment by khouloudbelguith** [comment] 2019-01-04 09:12
@krasnycz, thanks for your feedback.
Your issue is assigned to our developers to reproduce the issue.
Thanks!

**Comment by krasnycz** [comment] 2019-01-04 12:11
I forget to state that its multistore installation. I also tried to:

- switched to classic theme
- deleted old theme
- disabled and deleted all non-native module
- remove all overrides
-cleared cache
- ensured there is no CDN or any server side caching enabled

The problem persists.

**Comment by khouloudbelguith** [comment] 2019-01-04 15:39
@krasnycz, I tried again a new upgrade from PS1.7.4.2 to PS1.7.5.0 with the 1-click upgrade 4.5.1 (multistore is enabled)
Before launching the upgrade, I let the module recover the list of files to be modified, the modules to be upgraded.
The upgrade id sone successfully, all the native module are upgraded successfully, only one issue as described before: when I tried to go to the BO => Modules & Services => Updates Tab, there are still native modules not upgraded => which is wrong.
https://drive.google.com/file/d/1hyDupud2QcabaTD9UBn6zJPfqEsYMAJp/view
@marionf what do you think?
Thanks!

**Comment by krasnycz** [comment] 2019-01-04 16:22
And on my setups the module upgrade part is omitted. What could be reasons for it? I resolved the 302 error and everything so now the update completes like fine however modules update part is skipped.

[2019-01-04 17:12:14] Database upgraded. Now upgrading your Addons modules...
[2019-01-04 17:12:17] Addons modules files have been upgraded.

**Comment by krasnycz** [comment] 2019-01-07 14:00
I tried to upgrade 1.7.4.4 different instance and different server. Modules were updated however BO Catalog and Peformace tabs give Error 500. In the var/log there is same error as on the other instances.

[2019-01-07 14:56:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /improve/modules/addons/login": Method Not Allowed (Allow: POST)" at /home/123.cloudwaysapps.com/ABC/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 143 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /improve/modules/addons/login\": Method Not Allowed (Allow: POST) at /home/123.cloudwaysapps.com/ABC/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:143, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/appProdProjectContainerUrlMatcher.php:2611)"} []
[2019-01-07 14:56:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /improve/modules/addons/login": Method Not Allowed (Allow: POST)" at /home/123.cloudwaysapps.com/ABC/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 143 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /improve/modules/addons/login\": Method Not Allowed (Allow: POST) at /home/123.cloudwaysapps.com/ABC/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:143, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/appProdProjectContainerUrlMatcher.php:2611)"} []
[2019-01-07 14:56:24] request.INFO: Matched route "admin_performance". {"route":"admin_performance","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\PerformanceController::indexAction","_legacy_controller":"AdminPerformance","_legacy_link":"AdminPerformance","_route":"admin_performance"},"request_uri":"https://www.domain.eu/XXX/index.php/configure/advanced/performance/?_token=04Z7eO560mIEfuau3LB0RXIJbcoWqJqe75iAu-vlxPs","method":"GET"} []
[2019-01-07 14:56:24] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-01-07 14:56:24] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"xxx@xxx.tld"} []
[2019-01-07 14:56:25] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to PrestaShop\PrestaShop\Core\Search\SearchParameters::__construct() must be an instance of PrestaShopBundle\Entity\Repository\AdminFilterRepository, instance of Doctrine\ORM\EntityRepository given, called in /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/ContainerC3uks5e/getPrestashop_Core_Admin_SearchParametersService.php on line 8" at /home/123.cloudwaysapps.com/ABC/public_html/src/Core/Search/SearchParameters.php line 50 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to PrestaShop\\PrestaShop\\Core\\Search\\SearchParameters::__construct() must be an instance of PrestaShopBundle\\Entity\\Repository\\AdminFilterRepository, instance of Doctrine\\ORM\\EntityRepository given, called in /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/ContainerC3uks5e/getPrestashop_Core_Admin_SearchParametersService.php on line 8 at /home/123.cloudwaysapps.com/ABC/public_html/src/Core/Search/SearchParameters.php:50)"} []
[2019-01-07 14:56:25] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []

**Comment by khouloudbelguith** [comment] 2019-01-07 14:50
HI @krasnycz,

`Autoupgrade` not updating modules issue is not related to PrestaShop.
The issue of the list of the native modules which are not upgraded automatically it is a server issue because in a different instance and different server => modules were updated.
About your second issue, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) & during the upgrade do you have any errors displayed?
Thanks!

**Comment by krasnycz** [comment] 2019-01-07 15:35
@khouloudbelguith Well 

> `Autoupgrade` not updating modules issue is not related to PrestaShop.
> The issue of the list of the native modules which are not upgraded automatically it is a server issue because in a different instance and different server => modules were updated.

Well but still it's a PS issue :D. All previous updates were fine on the same setup.

> About your second issue, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev) & during the upgrade do you have any errors displayed?
> Thanks!

I tried to clear manually. Only error 500 in products and performance. No other errors.

Seems both issues are connected. Whenever modules are updated or not the results is same. I tried to move both instances to different server configuration with same results. Again the main problem is very poor PS debug&error reporting. No way to debug such issues. Always same story without resolution.

**Comment by khouloudbelguith** [comment] 2019-01-08 13:03
@krasnycz, to more understand how to reproduce your second issue, can you open a new one with more information about your configuration, because it is a different issue.
Thanks!

**Comment by krasnycz** [comment] 2019-01-08 14:48
@khouloudbelguith Well with help of cloudways support team we were able to identify the issue. It happens even on clean install when try upgrade. There is lot of reports on this in past 2 years and PS dev team is simply ignoring those reports. See the reports and temporary solution at

https://www.prestashop.com/forums/topic/568331-17-cant-access-product/

**Comment by krasnycz** [comment] 2019-01-10 14:05
I have this issue on 7 difference installs. Even clean install faces it.

Server OS: Debian 8.11

Even if you resolve related issues the core error of this issue persists and makes prestashop unsuable if dev mode if off causing the following error:

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to PrestaShop\PrestaShop\Core\Search\SearchParameters::__construct() must be an instance of PrestaShopBundle\Entity\Repository\AdminFilterRepository, instance of Doctrine\ORM\EntityRepository given, called in /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/ContainerEipuslj/getPrestashop_Core_Admin_SearchParametersService.php on line 8" at /home/123.cloudwaysapps.com/ABC/public_html/src/Core/Search/SearchParameters.php line 50 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to PrestaShop\\PrestaShop\\Core\\Search\\SearchParameters::__construct() must be an instance of PrestaShopBundle\\Entity\\Repository\\AdminFilterRepository, instance of Doctrine\\ORM\\EntityRepository given, called in /home/123.cloudwaysapps.com/ABC/public_html/var/cache/prod/ContainerEipuslj/getPrestashop_Core_Admin_SearchParametersService.php on line 8 at /home/123.cloudwaysapps.com/ABC/public_html/src/Core/Search/SearchParameters.php:50)"} []

**Comment by khouloudbelguith** [comment] 2019-01-10 14:26
Hi @krasnycz,

The performance page display the same exception with Fresh installation 1.7.5.0?
Thanks!

**Comment by krasnycz** [comment] 2019-01-10 14:55
Yes. I did 2 clean install of 1.7.4.4 on 2 different server provides via cloudways interface and reproduced the issue. It does even on clean install. Other 302 errors are permissions related as mentioned in the prestashop forum link I posted earlier.

The issue is basically same I previously reported at #11784 but was closed without resolution as related to 3rd party module but it's not. Clean install reproduces same problem.

**Comment by khouloudbelguith** [comment] 2019-01-10 15:00
@krasnycz, this issue is a different one, you don't need to comment here.
I will reopen #11784 to understand how can I reproduce your issue.
Thanks for your understanding!

**Comment by marionf** [comment] 2019-01-14 11:02
I just tried an upgrade from 1.7.4.4 to 1.7.5.0.
Modules are successfuly upgraded during the autoupgrade and I have only module to upgrade manually after the autoupgrade. I click on upgrade  for this module and it's done with success.

Before the upgrade: 

![capture d ecran_893](https://user-images.githubusercontent.com/13449658/51109005-2911c400-17f4-11e9-936b-0ceaf2457985.png)

During the upgrade:

![capture d ecran_894](https://user-images.githubusercontent.com/13449658/51109016-2dd67800-17f4-11e9-9d08-baecda9cd4f4.png)

After the upgrade:

![capture d ecran_895](https://user-images.githubusercontent.com/13449658/51109043-3d55c100-17f4-11e9-9f91-6f01ac1ec2ff.png)

**Comment by marionf** [comment] 2019-01-14 11:02
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.

**Closed as completed by marionf** 2019-01-14 11:02 UTC
Labels: Bug, Minor, Can't reproduce, Modules, Autoupgrade, 1.7.5.0
