### ISSUE TITLE
Gift-wrapping-message can not contain emoji

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33565] opened 2023-08-07 22:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I was testing Prestashop v. 8.1.0
and activated the gift-wrapping offer
and wrote a message in the gift-wrapping-message textarea: "Thank you for being you <3" (note the emoji "<3" which resembles a heart)

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/71103eb6-3676-4581-a09c-73860784f9af)

But this made Prestashop respond with a 500 response code when moving on to the next page:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/4e1d5c88-c86e-4118-a0e6-ff9289d53fda)

### Expected behavior

I would expect the platform to either be able to handle such an emoji OR at least remove it automatically, so that the customer wont see a 500-response in the checkout-flow (bad for business - especially as the customer isn't told what caused the error and therefore lead to believe that the shop is temporarily down).

### Steps to reproduce

1. Activate gift-wrapping feature
2. Go through the checkout-flow
3. Select the gift-wrapping addon for your order
4. Write "Thank you for providing a quick fix <3" in the gift-wrapping-message-textarea
5. Go to payment-page.

You should now be staring at a 500 response.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.33

**Comment by Hlavtox** [comment] 2023-08-08 09:13
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9574

**Comment by AureRita** [comment] 2023-08-08 09:13
Hi @LarsGMortensen 

Thank you for your report ! I reproduce the issue with PrestaShop version 8.1.0 as you can see : 

[Untitled_ Aug 8, 2023 11_12 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/dfc2017b-fc54-4a0a-951c-970c77cd383c)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by AureRita** [comment] 2023-08-08 09:20
HI @LarsGMortensen ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9574.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed by AureRita** 2023-08-08 09:20 UTC
Labels: Bug, Duplicate, Invalid
