### ISSUE TITLE
Problem Loading Modules

### ISSUE THREAD

**Issue by ADC1234** [PrestaShop/PrestaShop#10944] opened 2018-10-10 07:51 UTC
I have this error code in my models section and can't access many modules.
Anyone have any ideas of how to fix this? 
I don't use Ayden. Have tried uninstalling Ayden and re-installing with no luck.

4 errors 
[adyen] Error found in config file: CData section not finished NS8 Protect uses industry-leading techniques in be
[adyen] Error found in config file: Premature end of data in tag additional_description line 1
[adyen] Error found in config file: Premature end of data in tag module line 1
[adyen] Error found in config file: Premature end of data in tag modules line 1

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-10 08:01
Hi @ADC1234,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ADC1234** [comment] 2018-10-15 13:12
Hi,

Thanks for getting back to me. 
Amazingly after 4 vey frustrating days it just fixed it self.

All work ok now.

**Comment by khouloudbelguith** [comment] 2018-10-15 13:21
Hi @ADC1234,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-15 13:21 UTC
Labels: Bug, BO, Modules, Fixed
