### ISSUE TITLE
(1/1) ContextErrorException at checkout

### ISSUE THREAD

**Issue by Sewforth** [PrestaShop/PrestaShop#15989] opened 2019-10-16 18:36 UTC
At checkout, after Order with Obligation to Pay is clicked, a context error occurs.  Attached
![FireShot Capture 184 -  - mascogear](https://user-images.githubusercontent.com/56652025/66948141-21e94200-f022-11e9-819b-44a41b582b3b.png)
.
After analyzing it, it only occurs if I have a customized/personalized  product in my cart.

**Comment by khouloudbelguith** [comment] 2019-10-17 07:50
Hi @Sewforth,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-15 07:44
Hi @Sewforth,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-15 07:44 UTC
Labels: Bug, FO, No change required, Checkout
