### ISSUE TITLE
ps_imageslider - Editing a slide, click on button to add image don't work

### ISSUE THREAD

**Issue by andrea-buzz** [PrestaShop/PrestaShop#35873] opened 2024-04-09 07:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Click on button to choose file don't work beacause javascript error on sortable.min.js on module ps_imageslider

### Steps to reproduce

1. go to manage modules
2. select ps_imageslider
3. click on configure
4. edit or add a slide
5. click on button to choose file **not working**

### PrestaShop version(s) where the bug happened

1.7.8

### Your company or customer's name goes here (if applicable).

e-leva

**Comment by florine2623** [comment] 2024-04-09 07:50
Your issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/35713

I'm closing it as it has been fixed, and will out on the next release of image slider module.

**Closed as completed by florine2623** 2024-04-09 07:50 UTC
Labels: Bug

**Comment by andrea-buzz** [comment] 2024-04-09 09:21
this is not duplicate, this is a javascript error @florine2623

**Comment by SharakPL** [comment] 2024-04-10 08:26
It is a duplicate, although your PR is still valid and can help avoid further issues.
