### ISSUE TITLE
Stats Dashboard module does not work, 90% of data is missing

### ISSUE THREAD

**Issue by noblupl** [PrestaShop/PrestaShop#33840] opened 2023-09-05 09:43 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, some of the statistics is missing on our Stats Dashboard.

### Expected behavior

We expect statistics/analytics on presta to work according to real data. For reference - we have around 60-100 orders per month, and 3.5 - 4.5k visitors per month.

### Steps to reproduce

1. Go to "Stats" on the Presta, and try comparing real data with what stats give you. 
![image](https://github.com/PrestaShop/PrestaShop/assets/144114125/1d255175-258f-4ba5-b8ae-70742b2a7691)

For example - best selling products - empty. or sales and orders - it says 0. And I've marked a whole 2023 as a time range window.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

no idea what that means, sorry.

### If your bug is related to a module, specify its name and its version

Stats Dashboard Version v2.0.4

### Your company or customer's name goes here (if applicable).

NoBlue

**Comment by sallemiines** [comment] 2023-09-05 15:58
Hello @noblupl 

I didn't manage to reproduce the issue with 8.1.1, see the attached screen record below:

[issue_33840.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/01491329-0603-4db9-a281-23c145268d8a)

BTW, you need to wait 24 hours till the stats will be shown :wink: 
Please check and feedback.

Thanks!

**Comment by paulnoelcholot** [comment] 2023-09-27 15:48
Hello @noblupl,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2023-09-27 15:48 UTC
Labels: Bug, BO, Stats, Invalid, 8.1.x
