### ISSUE TITLE
Cart rules : huge ps_cart_rule_combination table

### ISSUE THREAD

**Issue by TheoAlloin** [PrestaShop/PrestaShop#23140] opened 2021-02-04 15:44 UTC
_Prestashop : 1.7.6.9_

Hi guys, 

I have an performance problem concerning the shopping cart rules on Prestashop : **having a lot of shopping cart rules + making them non-cumulative** with each other **overloads a lot the ps_cart_rule_combination table**.

Prestashop saves each excluded cart rule in this table which duplicates the data, and the size of the table becomes exponential.

_For example : yesterday I found this table which weighed 3.2GB and with about 48 million rows. After some optimizations I went back down to 26 million lines / 1.6GB. (I deleted unused cart_rules)._ 

But it remains HUGE and with so many rows, now with each recording in BO of the cart rules it fires a timeout because Prestashop try to compute each cart rules between them...

### The questions are the following :

- How can i reduce the size of the ps_cart_rule_combination table
- How can i define a non-cumulative rule by default without have a million line in ps_cart_rule_combination table 
- Have you ever seen this problem and how to solve it ? 

Thanks a lot for your help,
Best regards

**Comment by hibatallahAouadni** [comment] 2021-02-04 17:27
Hello @TheoAlloin 

Well, I think your issue is similar to this one #10003
Coudl you please check it and feedback.

Thanks!

**Comment by TheoAlloin** [comment] 2021-02-04 18:16
Hi @hibatallahAouadni ,

Thanks for your reply. 

Indeed, i have the same problem as this issue... 
Have we an update from Prestashop dev about that ? 

Regards

**Comment by hibatallahAouadni** [comment] 2021-02-04 19:09
Hello @TheoAlloin 

No, cause this issue need specifications. So, we need to wait till the Product Team finish the specs.
Sorry, but I have to close this issue cause it's a duplicate to #10003 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-04 19:09
Duplicate of #10003

**Closed as completed by hibatallahAouadni** 2021-02-04 19:09 UTC
Labels: Bug, CO, Duplicate, Performance, Cart rules, 1.7.6.9
