### ISSUE TITLE
Bug with color column

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#23638] opened 2021-03-14 23:27 UTC
#### Describe the bug

When you making fields_list in controller, you can to add property color, where the name of key in array. When you have key in array as "color", it is ok, but when you have seting other value, will be bug. 

1.  Make simple controller
2. Add to fields_list column with color, where value != color
3. Test it

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-03-15 16:54
Hello @dariusakafest 

Thanks for your issue and your PR!

Ping @PrestaShop/prestashop-core-developers could someone please help me to reproduce the issue :pray:

**Comment by PierreRambaud** [comment] 2021-03-15 18:08
> Hello @dariusakafest
> 
> Thanks for your issue and your PR!
> 
> Ping @PrestaShop/prestashop-core-developers could someone please help me to reproduce the issue

Hey, we are sorry but we will not take time to reproduce something like that.
People from the community must provide modules or code to help you to reproduce the issue, otherwise we will spend all our work time trying to reproduce issues.
If you can't reproduce it, please ask for more information, or a module to help you :wink:

**Comment by hibatallahAouadni** [comment] 2021-03-16 09:07
Hello @dariusakafest 

Could you please provide clearer steps to reproduce.
Thanks @PierreRambaud for your quick reply :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-04-06 13:29
Hello @dariusakafest ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-06 13:29 UTC
Labels: Bug, CO, No change required, 1.7.6.0, PR available, Hook
