### ISSUE TITLE
1 million comination frezzing prestsahop backend as well as frontend

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#30606] opened 2022-12-19 10:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When generating 1 million combination in Prestsashop 1.7.8.7 its freezing prestashop backend as well as frontend

### Expected behavior

Prestashop single product page with 1 million combinations should work and backend and frontend should work well for that perticular product

### Steps to reproduce

1. Login to prestashop backend
2. Create 7 attributes having 10 values
3. create single product and genrate combination for 7 attributes
4. after genrating it will freeze the product page
5. it will also freeze the specific product page

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

php 7.2

**Comment by prestaforum** [comment] 2022-12-19 10:56
> Prestashop single product page with 1 million combinations should work and backend and frontend should work well for that perticular product

I disagree with "Prestashop single product page with 1 million combinations should work"

this is not a normal usecase

1 million combination for 1 product is not for every merchant

it should be a need that is addressed by a specific Theme or Module

**Comment by pks891618** [comment] 2022-12-19 10:57
Ok please let me know what do you think what is normal case that can be achieved using Prestashop

**Comment by hibatallahAouadni** [comment] 2022-12-19 14:24
Hello @pks891618 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9809. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks @prestaforum for your quick reply 🚀 

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-12-19 14:24
Duplicate of #9809

**Closed as completed by hibatallahAouadni** 2022-12-19 14:24 UTC
Labels: Bug, Duplicate, Invalid
