### ISSUE TITLE
Search engine and customer group restrictions

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#19886] opened 2020-06-22 09:01 UTC
Hello,

The search functionality show products that the customer should not be able so see because of customer group restrictions.

1. Create a new category and assign some products to it.
2. Create a new customer group.
3. Restrict the category to newly created customer group only.
4. Make sure that indexation is ok
5. Search for restricted product reference or name

=> They are accessible 😔

Can you help?

* PrestaShop version: 1.7.3.2
* PHP version: 7.1.30

**Comment by PierreRambaud** [comment] 2020-06-22 09:22
Hi and thanks for your report.

@PrestaShop/prestashop-product-team I manage to reproduce the issue, but I don't know if it's the desired behaviour.
I'm also able to reach products (If I know the URL) that shouldn't be available with my group restrictions. 
Wdty?

Kind regards

**Comment by colinegin** [comment] 2020-06-25 15:53
IMO you shouldn't be able to see and access to the these products if you don't have the necessary conditions.
This means that when searching for a product, it shouldn't be in the results.
If you have the exact URL, you should get an error message (if possible).

Thanks

**Comment by PierreRambaud** [comment] 2020-06-25 20:57
> IMO you shouldn't be able to see and access to the these products if you don't have the necessary conditions.
> This means that when searching for a product, it shouldn't be in the results.
> If you have the exact URL, you should get an error message (if possible).
> 
> Thanks

Everything is possible you know :kissing: 
Should not be hard to fix :+1:

**Comment by PierreRambaud** [comment] 2020-06-26 09:16
I just made more tests and in fact, there is no bug :sweat_smile: 

You must be sure the product is not assigned to another category:
![image](https://user-images.githubusercontent.com/1462701/85841324-3c251380-b79e-11ea-851b-6acd8ff948c6.png)

In my case, my product was also assigned to `Home` category, I remove this one, and now, I must be connected to see it in Search and to reach it:
![image](https://user-images.githubusercontent.com/1462701/85841406-5fe85980-b79e-11ea-8175-e107f627ea22.png)

![image](https://user-images.githubusercontent.com/1462701/85841433-6a0a5800-b79e-11ea-890c-ffb4dff09254.png)

**Comment by MatShir** [comment] 2020-08-07 00:48
Since @PierreRambaud's comment, I will close the issue. Feel free to open it again if you encounter the bug again 😄

**Closed as completed by MatShir** 2020-08-07 00:48 UTC
Labels: Bug, PM ✔️, Customer groups, No change required, 1.7.6.5
