### ISSUE TITLE
Module manager page responsivity issue - checkbox collide with button

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#28312] opened 2022-04-23 11:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Module manager page responsivity issue - checkbox collide with button

Note: Please keep in mind also buttons translation in other languages. Because the width of button is not fixed and adapt to lengtht of the button label, in some languages this issue could occur and other not. So make the fix and test design and responsivity that will apply also for other languages.

![ps-module-manager](https://user-images.githubusercontent.com/2806752/164891711-bcc5f981-7a0b-42b8-8202-4f2d66784f00.png)

### Steps to reproduce

1. go into PrestaShop BO - Modules > Module Manager
2. change a web browser width on the desktop computer

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-04-25 10:07
Hello @Caleydon 

I reproduce the issue with PS1778, PS1785 and develop. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2022-04-28 18:54 UTC
Labels: Bug, BO, Fixed, Module manager, Front-end, PR available, Responsive, Verified
