### ISSUE TITLE
Cart is not updated properly when there is a change in voucher

### ISSUE THREAD

**Issue by TDC-Cyrille** [PrestaShop/PrestaShop#20009] opened 2020-07-01 03:10 UTC
#### Describe the bug
In FO, as a Customer I apply a voucher to my cart. Then in BO, I changed the expiration date of the voucher with its status is enabled. FO, I reload the page I can see that the voucher is still applied and that's wrong.

#### Expected behavior
When I reload the page, the voucher is no longer applied

#### Steps to reproduce

1. FO, add products to cart and apply a voucher
2. BO, edit the voucher date (valid to) to be expired
3. FO, refresh the page the voucher still applied => NOK
4. Delete the voucher, then you will see you can't apply it again => OK

#### Screenshots
https://drive.google.com/file/d/1SgVUMepMz-XsaUKgafB7aVv9LGnlAYLO/view

#### Additional informations

- Prestashop version: 1.7.7.0
- PHP version: 7.2

---
Hello team,

There seems to be an issue when a customer has an item into his/her cart and is eligible for a discount (cart rule). If the discount expires/is disabled before the user places an order, the cart will not be updated accordingly and the user will still see the discount in his/her cart. Upon placing the order, this will feed the incorrect information to the payment modules and the discount will still be applied. Additionally, the back-office order will display both the discount and the price without discount; making it so that the amount paid by the customer won't tally with the figures in the back-office.

You may find ways to reproduce the issue below (issue exists at least from PS 1.6.1.17 to 1.7.6.4):

1. Login to an user account and add items to your cart with a valid promotion:

![1](https://user-images.githubusercontent.com/47850156/86198947-66564700-bb8b-11ea-8936-62307e58ad4f.jpg)

2. Cancel/make expire the corresponding promotion in the back-office:

![2](https://user-images.githubusercontent.com/47850156/86198956-6b1afb00-bb8b-11ea-8714-aab9c779a640.jpg)

3. Reload the checkout page

The user will, in the end, be able to pay with an expired voucher.

**Comment by LouiseBonnard** [comment] 2020-07-01 12:17
Hi @TDC-Cyrille, thanks for your issue! It looks the same as #17290 which has been fixed by #17294 and will be available in the 1.7.8 version. You can check the fix and confirm, then I'll close this issue since it is fixed. :-)

**Comment by TDC-Cyrille** [comment] 2020-07-02 02:45
Dear Louise,

Thank you very much for your prompt reply!

Unfortunately I do not think that this is the same issue. To make it clearer:

With my above issue, the problem is that the amount passed to the payment modules is incorrect. For instance, if you have a customer eligible for a voucher at the last stage of the checkout and the voucher expires whilst that customer is still on the checkout page, the value returned by `$cart->getOrderTotal( true, Cart::BOTH )` will still include the voucher. The problem is that this is the method used by payment modules (such as Paypal) to bill the customers, so the customer will still have the voucher and pay for the order inclusive of the voucher even if the said voucher has expired.

The issue #17290 is about updating the DOM with the latest information, whereas this issue is about a wrong price being given to the payment modules, hence my concern.

To reproduce it (using PS1.7.6.4):

1. As a customer, login to your account and add a product that has a voucher to your cart.

2. Go to the last step of the checkout (Payment)
![2](https://user-images.githubusercontent.com/47850156/86310431-a7fcf580-bc50-11ea-9779-3753b3a61b2a.jpg)

3. In the back-office, disable the corresponding voucher
![3](https://user-images.githubusercontent.com/47850156/86310357-72f0a300-bc50-11ea-87f5-2c5646752d88.jpg)

4. Reload the checkout page, you will notice that the voucher is still there (sorry for the poor drawing skills)
![4](https://user-images.githubusercontent.com/47850156/86310468-bd721f80-bc50-11ea-8069-e05ed3412c47.jpg)

5. Try to pay using a payment module (for instance Paypal), it will include the voucher
![5](https://user-images.githubusercontent.com/47850156/86310391-8dc31780-bc50-11ea-9d78-17af9739200f.jpg)

I believe that this is linked to the cached cart object. Note that, based on my checkings, it doesn't seem to happen all the time but it does happen as we noticed this issue after a customer managed to order with an expired voucher.

**Comment by LouiseBonnard** [comment] 2020-07-02 08:46
Hi @TDC-Cyrille, thanks a lot for your explanation - and the great drawing skills, far better than mine! If it is a bug from the core, I'll add it to the debug roadmap. If it is related to third-party payment modules, I guess you'll have to contact them directly.

@PrestaShop/prestashop-core-developers, is this cached cart object be fixed in the code? It might be connected to this code line `$cart->getOrderTotal( true, Cart::BOTH )`.

**Comment by arouiadib** [comment] 2020-07-17 05:26
Hi guys, 

I think this is normal behaviour. By design, carts are cached because things may change after the cart creation, for instance: the expiration of a cart rule.

I think the customer is granted a cart voucher when he creates a cart, not when he places an order. He has the right to create carts and delay the day of real order. I don't think it is a good idea to remove the voucher for someone who already has seen in the past.

Please guys correct me if i am wrong.

**Comment by TDC-Cyrille** [comment] 2020-07-17 06:06
Hello Adib,

Thanks for your explanation on this. I get your point of view - and possibly the developers' point of view as well - however I feel that this should not be the case, or at least there should be an option to disable this. Indeed, this defeats the purpose of having an expiration date for the vouchers as some clients would still be able to enjoy them after the said date. When shopping online, most platforms will remove the voucher if it is past the expiration date (and having a message on why it happens can help guide the customer).

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-26 13:46
Hello @TDC-Cyrille 

Thanks for your issue, sorry for the late response.
I couldn't manage to reproduce your issue with PS1.7.7.0, the only issue is that I can reproduce is:

1. FO, add products to cart and apply a voucher
2. BO, edit the voucher date (valid to) to be expired
3. FO, refresh the page the voucher still applied => NOK
4. Delete the voucher, then you will see you can't apply it again => OK

Please see the attached screen record below:
https://drive.google.com/file/d/1SgVUMepMz-XsaUKgafB7aVv9LGnlAYLO/view

So, I'm going to edit the description issue :wink: I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by SebBareyre** [comment] 2021-03-30 15:57
I manage to reproduce this issue. The Cart::getCartRules method doesn't check the active state, the cart rule quantity and even the voucher date.

**Comment by Pitt1823** [comment] 2021-05-17 12:34
Is there any roadmap to fix this issue in the upcoming updates of PS?
This issue happens on several of my customer's websites and it is really annoying. Especially because most of my clients run a lot of voucher campaigns and the issue happens for a couple of users every time we run a discount campaign. It is very difficult to manage.

**Comment by Progi1984** [comment] 2021-05-17 12:59
@Pitt1823 Currently, the issue is not prioritized. But we are opened to contributions. If you don't have knowledge, you can hire a freelance which can send a PR.

**Comment by khouloudbelguith** [comment] 2021-05-24 15:38
Hi @hibatallahAouadni,

I think this issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/19393
What do you think?

Thank's

**Comment by hibatallahAouadni** [comment] 2021-05-25 09:49
Hello @khouloudbelguith 

Thanks for pointing to this issue :wink: 
Indeed it's a duplicate, we misunderstood the original issue #19393 cause the steps weren't very clear.
So, I edit the original issue to be clearer. Thanks again

As we are aware of this issue and it is already in our debug backlog. This issue is a duplicate of #19393. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-25 09:49
Duplicate of #19393

**Closed as completed by hibatallahAouadni** 2021-05-25 09:49 UTC
Labels: Bug, PM ✔️, FO, Duplicate, Discounts, Cart rules, Checkout, 1.7.7.0, 1.7.6.4
