### ISSUE TITLE
504 Timeout when trying to view SHIPPING Module??

### ISSUE THREAD

**Issue by sampsonzak** [PrestaShop/PrestaShop#12260] opened 2019-01-22 15:27 UTC
**Describe the bug**
When trying to view the default PS SHIPPING module / SHIPPING-Carriers, the page does not load and gives a 504 gateway timeout error.

I have NO other problems with any other modules. ONLY issue is with this Shipping module?? I have not modified it at all - and it is the default carrier!

What is wrong with this?? Please help!! It's urgent I change this, and I really do not want to move away from PrestaShop now.. but it's very frustrating!

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
 PrestaShop version: 1.7.2.4

Server information: Linux #1 SMP Wed Mar 28 14:22:08 EEST 2018 x86_64

Server software version: Apache

PHP version: 7.1.26

Memory limit: 768M

Max execution time: 120

Upload Max File size: 128M

**Comment by khouloudbelguith** [comment] 2019-01-22 15:31
Hi @sampsonzak,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by sampsonzak** [comment] 2019-01-22 16:14
Hi, I have had the following information back from my WebHost who looked into the issue:

I am hoping you know what is wrong with this possibly? And how I can fix this issue?

fcntl(7, F_SETFL, O_RDWR|O_NONBLOCK) = 0
connect(7, {sa_family=AF_FILE, path="/var/run/nscd/socket"}, 110) = 0
sendto(7, "\2\0\0\0\16\0\0\0\32\0\0\0api.addons.prestashop.com\0", 38, MSG_NOSIGNAL, NULL, 0) = 38
poll([{fd=7, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=7, revents=POLLIN|POLLHUP}])
fcntl(7, F_GETFL) = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(7, F_SETFL, O_RDWR) = 0
poll([{fd=7, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
fcntl(7, F_GETFL) = 0x2 (flags O_RDWR)
fcntl(7, F_SETFL, O_RDWR|O_NONBLOCK) = 0
read(7, 0x2a08943, 5) = -1 EAGAIN (Resource temporarily unavailable)

**Comment by sampsonzak** [comment] 2019-01-22 16:15
This is what happens when I try to click the 'SHIPPING' module, or SHIPPING->Carriers.

SHIPPING->Preferences works fine.

**Comment by khouloudbelguith** [comment] 2019-01-22 16:29
@sampsonzak, did you installed any custom carrier module?
Thanks!

**Comment by sampsonzak** [comment] 2019-01-22 16:32
@khouloudbelguith No I can't see any. There is a possibility I may of tried one months ago, but I have checked in my modules and there is nothing to do with shipping, so if I did I would have deleted it already!

**Comment by khouloudbelguith** [comment] 2019-01-22 16:38
@sampsonzak, could you please use this workaround to temporary disable API calls: http://bit.ly/2zIVejJ
Thanks to check & feedback.

**Comment by sampsonzak** [comment] 2019-01-22 16:51
Hi, that's worked. Thank you!!

With the API requests disabled am I still able to upload new modules, and upgrade existing ones?

I would rather keep this API thing disabled. As I have had downtime due to PrestaShop's API being down before!

What are the negatives of the changes I have made? What can I not do now? I will consider if it's worth enabling them again after I have set up my shipping rules!

Thank you for the super quick response.

**Comment by khouloudbelguith** [comment] 2019-01-22 17:19
@sampsonzak, will not be allowed to connect to Addons marketplace from your BO, upgrade module => you are not allowed, install a module from the BO provided by addons, but you can upload a module manually with a zip folder.
Thanks!,

**Comment by khouloudbelguith** [comment] 2019-02-21 08:02
Hi @sampsonzak,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-21 08:02 UTC
Labels: Bug, Shipping, 1.7.2.4, No change required
