### ISSUE TITLE
Module ps_shoppingcart don't work

### ISSUE THREAD

**Issue by JorgeNogueiraLFMPro** [PrestaShop/PrestaShop#19432] opened 2020-05-27 17:12 UTC
Hi,

I have a problem in my cart.
When I click the add to cart button, the units added to the cart do not appear at the top of the page. It only appears after refreshing the page or if we change the page.
In Module Shopping cart, Ajax option i have activated.

![image](https://user-images.githubusercontent.com/49063138/83051149-7dae8b80-a045-11ea-8aee-f0bcdfb93096.png)

Go to product page
Click on add cart
look to cart on top the page
Not update the units on cart

https://drive.google.com/file/d/1wBfO-8ChxdpzFN0SN6AtH_dUXGcWfpkM/view

PrestaShop version: 1.7.6.5
PHP version: 7.2.22

**Comment by arouiadib** [comment] 2020-05-27 21:14
Hi @JorgeNogueiraLFMPro ,
thank you for your time, could you please tell if it is similar to https://github.com/PrestaShop/PrestaShop/issues/16665?

the drive link doesn't work for  me :(
regards,

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 08:09
Hi, 

Not similar to #16665.

Look now the video.

https://drive.google.com/open?id=1Cr93h0JhQIcyPwfAc5ygHiCg6tXVjlQU

**Comment by florine2623** [comment] 2020-05-28 08:23
Hi @JorgeNogueiraLFMPro ,
Can you enable debug mode and add a product to cart ?
Let me know if there are any errors ?
Also, what theme are you using ?
Thanks!

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 08:39
Hi,
I enable the debug mode but when i click on the add to cart button nothing happens, it stays on the product page and shows no error. It's like the button doesn't have a defined path.

Theme: child_classic Version 1.0.0

**Comment by florine2623** [comment] 2020-05-28 08:41
Can you check the console of your browser also ?

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 08:43
Look the image.

![image](https://user-images.githubusercontent.com/49063138/83119441-a24b4780-a0c7-11ea-846b-6a045a9e5ae7.png)

**Comment by florine2623** [comment] 2020-05-28 10:37
Can you deactivate module nrt popup newsletter ? 
As well as deactivate your overrides. Folder `override` becomes `_override`.

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 11:28
I disabled the module and overrides. And the page stops working.

![image](https://user-images.githubusercontent.com/49063138/83136043-b51d4680-a0de-11ea-8827-29e3187f4890.png)

**Comment by florine2623** [comment] 2020-05-28 12:14
Can you enable debug mode ?
Advanced Parameters > Performance > Debug mode YES

Or in config/defines.inc.php 
`define('_PS_MODE_DEV_', false);`
becomes
`define('_PS_MODE_DEV_', true);`

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 12:27
Done!

**Comment by florine2623** [comment] 2020-05-28 12:56
Ok, do you have access to your page now ? What is the error shown ?

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 12:58
I can't acess to my page now.

![image](https://user-images.githubusercontent.com/49063138/83144437-3f6ba780-a0eb-11ea-9659-a0fb5dcedce7.png)

**Comment by florine2623** [comment] 2020-05-28 13:06
Can you go into your module folder and comment module psograph ?
`psographe` becomes `_psograph`

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 13:11
Done!

**Comment by florine2623** [comment] 2020-05-28 13:29
so ? How's the page ? is it working ?

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 13:30
Page it's working. But button no.

**Comment by florine2623** [comment] 2020-05-28 13:34
Did you do a migration or is it a fresh install ?

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 13:35
New installation.

**Comment by florine2623** [comment] 2020-05-28 13:57
If you have a module Group Inc, comment it.
![Capture d’écran 2020-05-28 à 15 56 45](https://user-images.githubusercontent.com/16019289/83150698-de989b00-a0fb-11ea-8613-e94ef1d3799f.png)

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 14:06
Yes i have this module.

**Comment by florine2623** [comment] 2020-05-28 14:13
Then comment it and go back to your page please

**Comment by JorgeNogueiraLFMPro** [comment] 2020-05-28 14:15
Look the errors

![image](https://user-images.githubusercontent.com/49063138/83152799-1ef51a80-a0f6-11ea-82ab-41e4df73c0aa.png)

**Comment by florine2623** [comment] 2020-05-28 15:16
Have you deactivate the module groupinc ? If no, please do it.

Also, this is a bug tracker platform, not a support platform. If you need personalized help, please contact the support here : https://addons.prestashop.com/en/388-support
Thanks!

**Comment by arouiadib** [comment] 2020-05-28 18:55
> Hi,
> 
> Not similar to #16665.
> 
> Look now the video.
> 
> https://drive.google.com/open?id=1Cr93h0JhQIcyPwfAc5ygHiCg6tXVjlQU

I see the problem now with your video. 

I have installed a fresh 1.7.6.5 and can't reproduce it. The top of the page is refreshed correctly via AJAX with the number of total units.

Thanks.

**Comment by florine2623** [comment] 2020-05-29 08:53
@arouiadib Thanks for your feedback !

@JorgeNogueiraLFMPro what bout you ? Did you deactivate module groupeinc ?Is it a possibility to fresh install a shop ?

**Comment by colinegin** [comment] 2020-06-17 14:44
Hello,

your issue seems to be a duplicate of #19733.
Can you confirm this is the same bug you're facing ?

**Comment by JorgeNogueiraLFMPro** [comment] 2020-06-17 15:45
> @arouiadib Thanks for your feedback !
> 
> @JorgeNogueiraLFMPro what bout you ? Did you deactivate module groupeinc ?Is it a possibility to fresh install a shop ?

I disabled the module and the cart still does not update.

I don't have to do a new installation right now.

**Comment by JorgeNogueiraLFMPro** [comment] 2020-06-17 15:46
> Hello,
> 
> your issue seems to be a duplicate of #19733.
> Can you confirm this is the same bug you're facing ?

Hi,

It's not the same bug.

**Comment by florine2623** [comment] 2020-06-18 09:57
@JorgeNogueiraLFMPro ,
Is there another error when you activate debug mode ?

**Comment by sarahdib** [comment] 2020-07-07 11:10
@JorgeNogueiraLFMPro 

The cart seems to be hooked in the wrong place.
<img width="1135" alt="Capture d’écran 2020-07-07 à 13 05 03" src="https://user-images.githubusercontent.com/3034677/86771757-12e46d00-c053-11ea-9ba7-a9da67637963.png">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!

**Closed as completed by sarahdib** 2020-07-07 11:10 UTC
Labels: FO, No change required, ps_shoppingcart
