### ISSUE TITLE
Module "Contact Information" translation is not updating

### ISSUE THREAD

**Issue by M4ketech** [PrestaShop/PrestaShop#23337] opened 2021-02-21 15:29 UTC
#### Describe the bug

 Hello,
I did solve this in last shop, but now i can not remember how to do this. So Title of "Contact Information" is not updating, even if i translate block title and text. It shows in database, but not in frontend.

"Store Information" on the footer shows up like this in frontend: 

![kuva](https://user-images.githubusercontent.com/8841448/108629660-a4c9aa80-7469-11eb-8f88-e670f632777a.png)

It shows up in database:
![kuva](https://user-images.githubusercontent.com/8841448/108629682-bca12e80-7469-11eb-8a2d-7176a0371554.png)

#### Expected behavior

Its tested with multiple themes, including default theme, it should show "Yhteystiedot".
![kuva](https://user-images.githubusercontent.com/8841448/108629698-d9d5fd00-7469-11eb-8bcd-474baf2ab003.png)

#### Steps to Reproduce

1. Go to 'International -> Translations'
2. Click on 'Installed modules translations -> Contact information -> Language: Suomi ( Finnish)'
3. Scroll down to ''Shop -> Store information and you see "valikko_määritykset", translate it and go to frontend".

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.27

**Comment by hibatallahAouadni** [comment] 2021-02-22 10:07
Hello @M4ketech 

I reproduced your issue with PS1.7.6.7 and PS1.7.7.1 and I tested with variety languages (French, English, Polski, Italian, ...) and it doesn't work :confounded: 

This issue is a duplicate of #19229. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-22 10:08
Duplicate of #19229

**Closed as completed by hibatallahAouadni** 2021-02-22 10:07 UTC
Labels: Duplicate
