### ISSUE TITLE
displayAdminOrderContentShip does not show the content in the right place

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11673] opened 2018-12-08 19:17 UTC
Hi
I want to use these two hooks
displayAdminOrderTabShip
displayAdminOrderContentShip

the first one is ok, its content will be shown inside the list
instead the content of displayAdminOrderContentShip will be shown in a wrong place

@khouloudbelguith I'll send you an email with the module zip to test this problem

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/49689714-6dd77a80-fb25-11e8-9b8c-f937bda06f3a.png)
![2](https://user-images.githubusercontent.com/653230/49689715-6dd77a80-fb25-11e8-8ecd-961ee59b22e3.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment] 2018-12-10 14:04
Hi @maofree,

Thanks for your report.
I tried with this module & it is OK
![image](https://user-images.githubusercontent.com/16067358/49737329-e1e06280-fc8c-11e8-862f-287d6a404693.png)
Thanks to check & feedback.
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/2663396/mymodule.zip)

**Comment by Maofree** [comment] 2018-12-10 15:25
ok

**Comment by khouloudbelguith** [comment] 2018-12-10 15:29
@maofree, can I close the issue?
Thanks!

**Comment by Maofree** [comment] 2018-12-10 15:47
yes you can close, in the future I'll do other tests to use these hooks
however if it works with your module it should work with mine

bye

**Comment by khouloudbelguith** [comment] 2018-12-10 15:49
Hi @maofree,

With my module, we could not reproduce your issue.
It seems that your issue is not a PrestaShop's core bug but a most likely custom module.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-10 15:49 UTC
Labels: BO, Can't reproduce, Modules
