### ISSUE TITLE
Changing order products randomly corrupts order prices & breaks editing

### ISSUE THREAD

**Issue by rmilecki** [PrestaShop/PrestaShop#17347] opened 2020-01-24 15:25 UTC
**Describe the bug**
PrestaShop allows editing order products. We use that if one of products is unavailable or customer made a mistake. **Sometimes** editing an order results in **database corruption**. Order prices get invalid and they don't match order products. Further order products modifications may also stop working.

**To Reproduce**
We **don't** know how to reproduce this. This bug definitely requires some very specific circumstances that remain unknown to us. That means we can't debug this issue properly.

I was only able to analyze one order case as I happened to have database snapshot before the corruption. I'm providing that case details in hope someone can conclude what has happened meanwhile.

**Case XHGOUAGRP before corruption**
Shop customer ordered 11 Lasagne LV products and 7 Tortilla RP products. We set 10% discount for that order. It was all good:
![before-good](https://user-images.githubusercontent.com/452972/73077386-5b063d80-3ec0-11ea-91bd-a476b958fc8f.png)
Result of `SELECT * FROM orders/order_detail/order_invoice WHERE id_order = 11077;`:
[before-good.txt](https://github.com/PrestaShop/PrestaShop/files/4109090/before-good.txt)

**Case XHGOUAGRP after corruption**
We decided to replace "Lasagne LV" product with "Lasagne SCH" due to unavailability of the first one. That has failed. We couldn't remove "Lasagne LV" and order prices got wrong:
![after-bad](https://user-images.githubusercontent.com/452972/73077385-5b063d80-3ec0-11ea-80fc-e67fe4930067.png)
Result of `SELECT * FROM orders/order_detail/order_invoice WHERE id_order = 11077;`:
[after-bad.txt](https://github.com/PrestaShop/PrestaShop/files/4109093/after-bad.txt)

If you look closely you'll see that new `order_detail` entry doesn't have `id_order_invoice` set. This causes further problems, e.g. trying to change quantity of "Lasagne SCH" products:
![after-edit](https://user-images.githubusercontent.com/452972/73079926-48dace00-3ec5-11ea-90d3-c7236c3006dd.png)
results in sending request to `AdminOrders` with following data:
```
ajax: 1
token: 3a88a4780bfca3c624a07585f40a487b
action: editProductOnOrder
id_order: 11077
product_id_order_detail: 131129
product_price_tax_excl: 14.14
product_price_tax_incl: 14.85
product_quantity: 9
product_invoice: 10548
```
but getting following reply:
```
<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
							Property OrderInvoice->id_order is empty.
					</div>
```

Another example is deleting "Lasagne LV":
![after-delete](https://user-images.githubusercontent.com/452972/73081376-c6074280-3ec7-11ea-95b5-da1857b03435.png)
it results in sending request to `AdminOrders` with following data:
```
ajax: 1
action: deleteProductLine
token: 3a88a4780bfca3c624a07585f40a487b
id_order_detail: 130597
id_order: 11077
```
but getting following reply:
```
<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
							Property Order->total_paid is not valid
					</div>
```
(same error reply when trying to set quantity to 5 or lower).

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: N/A

Another report: [backoffice order total showing wrong price, invoice showing correct price](https://www.prestashop.com/forums/topic/527017-backoffice-order-total-showing-wrong-price-invoice-showing-correct-price/)

**Comment by khouloudbelguith** [comment] 2020-01-24 15:58
Hi @rmilecki,

I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1FGt73fHJd43CJrO8GL1eZXgQKEaYMvJg/view

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-02-24 08:18
Hi @rmilecki,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-24 08:18 UTC
Labels: Bug, BO, Order, Discounts, Cart rules, Taxes and Prices, No change required, PR available, 1.7.6.2
