### ISSUE TITLE
BO - Products page - The currency symbol in Cost price field of a supplier is not updated when we change the currency

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29347] opened 2022-08-15 15:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27353#pullrequestreview-968285262 by @HanaRebaiQA 

Related to  https://github.com/PrestaShop/PrestaShop/issues/29346
The currency symbol in Cost price field of a supplier is not updated when we change the currency

### Steps to reproduce

Reproduced with 8.0.x: Product V1+ V2 / 1.7.8.7 / 1.7.7.8

1. BO > IMPROVE > International > Localization > Configure a new localization pack
2. In BO > Catalog > Products (experimental) > Edit a product V2
3. Use any product type
4. In Supplier references section > Change the currency
5. See error > The currency symbol in Cost price field is not updated 

![image](https://user-images.githubusercontent.com/92912932/165507380-d69293c0-3bd8-4cad-ae63-c68109736ba8.png)

https://user-images.githubusercontent.com/92912932/165508312-6aa4f731-d1c6-47cd-a0ff-01e318b514c8.mp4

### PrestaShop version(s) where the bug happened

8.0.x, 1.7.8.7, 1.7.7.8

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment] 2024-12-30 13:35
The issue is fixed in PS 9.0.0 : 

https://github.com/user-attachments/assets/422d0553-bfaa-4a96-b863-ca9467d8dbdf

**Closed as completed by florine2623** 2024-12-30 13:35 UTC
Labels: Bug, Minor, BO, Catalog, Suppliers, Currencies, 1.7.7.8, Verified
