### ISSUE TITLE
ItemList is wrong for products blocks of carousels and product list

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#22636] opened 2021-01-01 15:32 UTC
Hi
I've reported many times from more than one years by some bug reports that the decision to use the ItemList is wrong if there are more ItemList in a page, but now after the upgrade to 1.7.7.0 I can see other errors.
before to use a solution you should test it many time, I think it is not so difficult test it with
https://search.google.com/structured-data/testing-tool

to reproduce this error it is simple try to use the google tool on the 1.7.7.0 front pages

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/103441426-41cc4c00-4c4e-11eb-8420-70ae8cddfa00.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-01 16:42
Hello @maofree 

> I've reported many times

Yep, that's **TRUE** and here's the list of the reported issues:

#13737 - Solved - big problem about the canonical url in the category pages when there is pagination and multi languages 
#15554 - Errors with latest changes on itemList for products listing
#15764 - Some microdata are missing in the product page

And I believe that you created this ticket as freiendly reminder, is that so?
If so, these tickets are already in our debug backlog, and there's a PR in progress #21786

**Comment by Maofree** [comment] 2021-01-01 16:45
hi
I tell you the truth I opened this bug report because I was disappointed to see these errors after I had warned several times that the new solution on prestashop is not good and that microdata does not have much priority.
I don't understand why nothing has been done to block the addition of this new solution. With the previous solution there were only warnings while now errors are added and I don't know how they are considered by google

**Comment by hibatallahAouadni** [comment] 2021-01-01 16:48
Hello @maofree 

Yes, you're right :confused: 
I will remind the Developers and the QA team to test that PR in priority 
Sorry for the inconvenience.

Thanks!

**Comment by Maofree** [comment] 2021-01-01 16:50
thanks

**Comment by hibatallahAouadni** [comment] 2021-01-11 16:12
Hello @maofree 

Could you please check this issue #22416 
I think it's similar to yours :sweat_smile: 

Thanks!

**Comment by Maofree** [comment] 2021-01-11 16:44
Hi
I think it is a different thing

**Comment by hibatallahAouadni** [comment] 2021-01-11 16:55
@maofree well I see no difference when I test my shop:

https://search.google.com/structured-data/testing-tool

![image](https://user-images.githubusercontent.com/23308427/104212816-e95b3280-5435-11eb-9d17-9cff647b9b97.png)

https://search.google.com/test/rich-results

![image](https://user-images.githubusercontent.com/23308427/104212856-f37d3100-5435-11eb-967e-5cdd002364bd.png)

Both links display the same error and if you could check the attached screen reocrd below:

https://drive.google.com/file/d/1kerCmPxQkaJ-wuP6Hs-pMnLFTwVfYH9T/view

Please check and feedback.
Thanks!

**Comment by Maofree** [comment] 2021-01-11 17:55
look at the first image at the top, you can see that ItemList is not that of breadcrumlist but that of product category module

**Comment by Maofree** [comment] 2021-01-11 18:07
the #22416 is present in the homepage just for breadcrumlist
the other errors are present in many pages: homepage, categories, manufacturers, product pages if presente some carousels
the problem is present in
classic/templates/catalog/_partials/product.tpl
this file is used from modules from tpl of category, manufacturer .... tpl file
and the problem of ItemList is that it must be only one for each page, so if there are some carousels on the page like into the homepage this solution gives some errors

so this ticket doesn't report the same issue of #22416, this error is much more important and it is around ItemList of this line
<div itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
of classic/templates/catalog/_partials/product.tpl

bye

![1](https://user-images.githubusercontent.com/653230/104220895-72776700-5440-11eb-9025-7538db2d6800.png)
![2](https://user-images.githubusercontent.com/653230/104220034-37c0ff00-543f-11eb-8936-c7313444fdcf.png)
![3](https://user-images.githubusercontent.com/653230/104220037-38599580-543f-11eb-9752-da019888ad2d.png)

**Comment by hibatallahAouadni** [comment] 2021-01-20 13:35
Hello @maofree 

I see what do you mean :wink: 
But unfortunally, I get an error only with Breadcrumps, for the products I only had some warnings as I mentionned above.

Thanks!

**Comment by Maofree** [comment] 2021-01-20 13:38
give me the url of your demo site, so I can help to understand the motive

**Comment by hibatallahAouadni** [comment] 2021-01-20 14:40
Hello @maofree 

Yep! you're right, I just tried again and I manage to reproduce the issue, see the attached screen record below:

https://drive.google.com/file/d/11NiMrUQssrWv8WOei6KJb7xzR3TQ8Bsb/view

Thanks for your patience and clarifications :rocket: I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Maofree** [comment] 2021-01-20 17:57
ok good

**Comment by hibatallahAouadni** [comment] 2021-01-21 13:47
Hello everyone,

As discussed with @maofree on Slack, #22835 is the solution for this issue.
So, please check it out this issue #22835 first :wink: 

Thanks in advance.

**Comment by Progi1984** [comment] 2021-01-29 16:16
Fixed by #23024

**Closed as completed by Progi1984** 2021-01-29 16:16 UTC
Labels: Bug, Minor, FO, SEO & URLs, Regression, Fixed, 1.7.7.0

**Comment by alfonsolr09** [comment] 2021-02-05 00:34
if this PR is applied in 1.7.7.2, the other one in 1.7.8.0 cannot be applied
since in the change made for version 1.7.7.2, the PR foreseen for 1.7.8.0 had already been applied.
that is, this PR 1.7.7.2 #23024 already includes the other PR for 1.7.8.0 #22417

@Progi1984 I do not understand very well how github works, can you check if what I say is true?
