### ISSUE TITLE
Class 'Tools' is not found in classes/db/Db.php

### ISSUE THREAD

**Issue by danielkauffman** [PrestaShop/PrestaShop#21880] opened 2020-11-11 20:54 UTC
#### Describe the bug

PHP throws a fatal error: Class 'Tools' is not found in classes/db/Db.php:794.

Here is the stack trace:

```
2020/11/11 12:36:06 [error] 12073#12073: *38801 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Tools' not found in /opt/prestashop/classes/db/Db.php:794
Stack trace:
#0 /opt/prestashop/config/alias.php(47): DbCore->escape()
#1 /opt/prestashop/config/alias.php(52): pSQL()
#2 /opt/prestashop/classes/Configuration.php(155): bqSQL()
#3 /opt/prestashop/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()
#4 /opt/prestashop/classes/PrestaShopAutoload.php(171): ConfigurationCore::get()
#5 /opt/prestashop/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()
#6 [internal function]: PrestaShopAutoload->load()
#7 /opt/prestashop/config/config.inc.php(84): spl_autoload_call()
#8 /opt/prestashop/back-office/index.php(40): require('/opt/prestashop...')
#9 {main}
  thrown in /opt/prestashop/classes/db/Db.php on line 794 while reading response header from upstream
```

See also https://github.com/PrestaShop/PrestaShop/blob/f3dbe7bf9c3c8e5c64d196c1d92ef980f34886e0/classes/db/Db.php#L794

#### Expected behavior

Class 'Tools' should be found in classes/db/Db.php.

#### Additional information

* PrestaShop version: 1.7.7.0 RC 1

**Comment by matks** [comment] 2020-11-11 21:06
Hi @danielkauffman thanks for testing the Release Candidate !

Could you tell us how you encountered this issue ? On FO ? On BO ? Using PrestaShop in Command Line ?
Maybe you could also indicate what OS you run and php version ? 😄 

As far as I know class Tools is in the right location in 1.7.7.0 RC1 🤔 see https://github.com/PrestaShop/PrestaShop/blob/1.7.7.0-rc.1/classes/Tools.php but it could not be found if autoload cannot find it. But to understand why autoload does not find it, we need more details about your setup.

**Comment by danielkauffman** [comment] 2020-11-11 21:23
Hi @matks glad to help.

I'm able to trigger the issue from BO > Configure > Shop Parameters > Traffic & SEO > Schema of URLs > Save. At that point I see a 500 server error in the browser, and the above stack trace in my logs.

Tools is working in every other instance I've come across, including in my own modules. I haven't seen any other issues with auto-loading, only this one instance.

The issue persists even after disabling non PrestaShop modules and overrides in BO > Configure > Advanced Parameters > Performance > Debug mode.

I'm running PHP 7.4.12. The issue persists with PHP 7.3.24.

I've configured the entire PrestaShop hierarchy to be owned by the user and group that PHP is running as, and confirmed file ownership is as expected, and there don't seem to be any issues with access to the files.

I installed PrestaShop from the command line using `php install/index_cli.php` but I wouldn't expect there to be any differences between the web install and the CLI install.

**Comment by SimonGrn** [comment] 2020-11-11 21:31
Hello, thank you for your report. Just FYI, the 1.7.7.0 is not compatible with PHP 7.4 ([requirements here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/)).
(I saw you tested with PHP 7.3, it's just an information in case you planned to go with PHP 7.4 in production for example).

**Comment by danielkauffman** [comment] 2020-11-11 22:22
@SimonGrn thank you for the heads up, I had noticed that in the requirements as well. I've been developing using PrestaShop 1.7.7.0 + PHP 7.4 for several months now, and haven't seen any errors specifically from PHP 7.4, although debug mode produces a large number of notices in PHP 7.4. Any errors I've been finding, I've been able to confirm in PHP 7.3, and none of the errors I've found have been specific to PHP 7.4.

**Comment by hibatallahAouadni** [comment] 2020-11-12 12:46
Hello @danielkauffman 

Could you please provide other informations to reproduce this issue. Cause following these steps: 

`BO > Configure > Shop Parameters > Traffic & SEO > Schema of URLs > Save`

I couldn't manage to reproduce your issue. See the attached screen record below:

https://drive.google.com/file/d/1_8LJ5Cg5o5YT1J6PH_NpTzh44udUAJ-l/view

PS: I think you need to clear your cache folders as mentioned [here](https://www.prestashop.com/forums/topic/1000973-fatal-error-uncaught-error-class-tools-not-found-in-varwwwhtmlclassesdbdbphp/?tab=comments#comment-3262705)

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-12 13:29
Hi @danielkauffman 

> The issue persists even after disabling non PrestaShop modules and overrides 

These buttons doesn't work and we are aware of these issues, it is already in our debug backlog (See #9965 and #14596).

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-04 08:40
Hello @danielkauffman ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-04 08:40 UTC
Labels: Bug, CO, No change required, 1.7.7.0
