### ISSUE TITLE
[BO] Bad display of progress bar for bulk actions

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27386] opened 2022-01-18 13:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The progress bar percentage in bulk actions modal is empty.

![Screenshot from 2022-01-18 12-48-18](https://user-images.githubusercontent.com/85633460/149941981-da11bfc5-f0ed-4920-b348-0415e77100eb.png)

### Expected behavior

![Screenshot from 2022-01-18 12-52-02](https://user-images.githubusercontent.com/85633460/149942056-38e43775-3e0c-476b-a875-2c5914446f5d.png)

### Steps to reproduce

1. Go to BO > Catalog > Products
2. Select multiple products
3. Try to duplicate with bulk actions menu

### PrestaShop version(s) where the bug happened

8.0

**Comment by marwachelly** [comment] 2022-01-18 13:56
Hello,
Thank you for your report. I was able to reproduce the issue with PrestaShop version 1.7.8.0 and develop.
https://watch.screencastify.com/v/gQhdiUqHVUeKJ4M447rR
The issue is not reproducible with PS 1.7.7.8 it is a regression.
I'll add this to the debug backlog so that it's fixed. Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider hiring a specialist to help you.

If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks,

**Comment by Progi1984** [comment] 2022-01-29 12:13
Fixed by @mparvazi in #27389 and tested by @marwachelly

**Closed as completed by Progi1984** 2022-01-29 12:13 UTC
Labels: Bug, Trivial, BO, Regression, Fixed, PR available, 1.7.8.0, Verified
