### ISSUE TITLE
Cannot disable maintenance mode after update 1.7.4.3

### ISSUE THREAD

**Issue by WS-NL** [PrestaShop/PrestaShop#11274] opened 2018-11-06 06:45 UTC
After updating to 1.7.4.3 we cannot get our shop out of maintenance mode.
As well when debug is not enabled we cannot clear the cache, if debug is enabled we can clear cache, but see a warning in debug translated files are missing?

See attached errors and errors below

Uncaught Exception: Expected argument of type "object, array or empty", "string" given

Uncaught PHP Exception Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected argument of type "object, array or empty", "string" given" at /home/pp/domains/test.nl/public_html/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 41

![2](https://user-images.githubusercontent.com/44797407/48047196-93c0d680-e197-11e8-83ba-3a395a3ad1d9.jpg)
![111](https://user-images.githubusercontent.com/44797407/48047197-93c0d680-e197-11e8-80c3-f2c3d8e206be.jpg)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0 /7.1 /7.2
Used latest upgrade module

**Comment by khouloudbelguith** [comment] 2018-11-06 08:08
Hi @wgsol2018,

The issue has been fixed with the v4.0.0-beta.4 release of 1-click upgrade module.
Now, we have released a new version 4.4.1 of the 1-click upgrade module (https://github.com/PrestaShop/autoupgrade/releases).
If you are already upgraded, please follow the message of Peter Visser in this [comment](http://forge.prestashop.com/browse/BOOM-5982?focusedCommentId=171708&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171708)
Thanks to check & feedback.

**Comment by WS-NL** [comment] 2018-11-06 08:21
Thanks for your reply

If the issue is fixed in the 4.0.0 beta it should also have been added to 4.4.0 right?

We tried the fix from Peter Visser but is not working for us.

Will 4.1.1 fix this issue??

Please advise

**Comment by khouloudbelguith** [comment] 2018-11-06 08:26
@wgsol2018, I did not manage to reproduce your issue after upgrade from 1.7.2 to 1.7.4.3 using the 1-click upgrade 4.4.0.
Could you please try to replace the `ps_configuration_lang` table in the Database with the one from clean PS1.7.4.3 installation.
Thanks to check & feedback.

**Comment by WS-NL** [comment] 2018-11-06 08:34
Thanks for your fast reply

We will try your solution later today and give feedback.

**Comment by khouloudbelguith** [comment] 2018-11-06 08:42
@wgsol2018, thanks!
Waiting for your feedback.

**Comment by WS-NL** [comment] 2018-11-07 06:45
Thanks, 

After replacing ps_configuration_lang with the one from a clean PS1.7.4.3 installation the maintenance 
mode is working but our theme will stop working with some functionality. 

We also installed the theme on a clean test shop with PS 1.7.4.3 and installed all the languages needed, afterthat exported ps_configuration_lang again, imported in production shop but without succes, same problem with some functionality from current theme.

We can upgrade the live production webshop to 1.7.4.3 and enable maintenance mode true the database but this is not the correct way.

**Comment by khouloudbelguith** [comment] 2018-11-07 10:02
Hi @wgsol2018,

It could a problem of the compatibility of your theme & PS1.7.4.3.
Have you tried to contact the theme author about this issue?
Thanks!

**Comment by WS-NL** [comment] 2018-11-07 10:16
We contacted theme author today. 
We updated the theme for compatibility for 1.7.4.3 so it should not be the problem

**Comment by khouloudbelguith** [comment] 2018-11-07 11:12
@wgsol2018, but you said that after replacing ps_configuration_lang with the one from a clean PS1.7.4.3 installation the maintenance mode is working?

**Comment by WS-NL** [comment] 2018-11-07 12:24
Yes your right, but i think it should not be a problem right?
If we replace ps_configuration_lang from a clean PS1.7.4.3 some translations are messed up as well.
So this is not the fix how we can get it working for now

We contacted theme author today. Lets see if he have any solution

**Comment by khouloudbelguith** [comment] 2018-11-07 13:22
@wgsol2018, what are those translations?

**Comment by WS-NL** [comment] 2018-11-07 13:29
We use 5 languages on the shop
the translations from a few parts of the backoffice modules from our theme (warehouse theme) are then mixed up
As well the mega menu is not clickable anymore

Dutch - Default
English
France
German
Spain

**Comment by khouloudbelguith** [comment] 2018-11-07 13:33
@wgsol2018,

So it is all about your theme.
We can't do anything before the feedback of your theme author.
Thanks!

**Comment by WS-NL** [comment] 2018-11-07 13:39
This is only after we replace the ps_configuration_lang file. If we dont replace after updating everything works fine except disbale maintance mode which is in backoffice. Not front

Lets wait

**Comment by khouloudbelguith** [comment] 2018-11-07 13:40
@wgsol2018, ok thanks!
Waiting for your feedback.

**Comment by WS-NL** [comment] 2018-11-10 23:38
reply from Warehouse theme :

sorry but your issue is not related to template.

once you replaced ps configuration lang, then you lost entire configuration of your modules, not only the themes one

**Comment by khouloudbelguith** [comment] 2018-11-12 10:56
Hi @wgsol2018,

With your previous ps_configuration_lang (don't replace it), could you please try to enter this SQL query.
`INSERT INTO `ps_configuration_lang` (`id_configuration`, `id_lang`, `value`, `date_upd`) VALUES ('277', '1', 'maintenance', '2018-11-12 00:00:00');`
![image](https://user-images.githubusercontent.com/16067358/48343270-3aaee200-e672-11e8-86c2-a112f9fc7c4a.png)
Thanks to check & feedback.

**Comment by WS-NL** [comment] 2018-11-13 10:18
Thanks you very much. It is working now. Finally
One more thing is. when we clear cache, we get a white page,
when we enable debug and clear cache there is no white page, and cache is cleared

**Comment by khouloudbelguith** [comment] 2018-11-13 10:37
Hi @wgsol2018,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2018-11-13 10:40
@wgsol2018, if you click twice on the Clear cache button => Error 500, we are aware of this issue, it is added to our bug roadmap: https://github.com/PrestaShop/PrestaShop/issues/11105
Thanks!

**Comment by WS-NL** [comment] 2018-11-13 17:58
> 
> 
> Hi @wgsol2018,
> 
> Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
> Thanks to check and feedback.

This is not fixing the clear cache white page,
strange thing is when debug is enabled we can clear cache

**Comment by khouloudbelguith** [comment] 2018-11-14 09:44
Hi @wgsol2018,

Could you please try to regenerate the file .htaccess

- Rename the old file to .htaccess_old
- Disable friendly URL
- Enable friendly URL

and then turn off both caches and then try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

**Comment by WS-NL** [comment] 2018-11-15 08:11
Thanks, 

This is not working. 
same issue

**Comment by khouloudbelguith** [comment] 2018-11-15 08:45
Hi @wgsol2018,

In the Advanced Parameters => Performance page, "Disable all overrides" option is enabled or disabled?
If yes, is enabled, try to disable, check & feedback.
Thanks!

**Comment by WS-NL** [comment] 2018-11-15 11:35
We dont have this enabled
We know you have to disable this feature after update.

**Comment by khouloudbelguith** [comment] 2018-11-15 13:42
Hi @wgsol2018,

Are there any errors in your log file?
Thanks to past it here.

**Comment by khouloudbelguith** [comment] 2018-12-21 13:54
Hi @wgsol2018,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-21 13:54 UTC
Labels: Bug, BO, Maintenance, Autoupgrade, No change required, 1.7.4.3

**Comment by pollat** [comment] 2019-07-22 17:54
If you use Multishop, disable maintenence mode on "each shop" and not on "all shop": go to "shop setting" > "general" > "maintenence section" and switch on every singular shop before disable disable maintenece mode).
