### ISSUE TITLE
PS 1.7.6.7 + GDPR 1.2.1 = No more translations (redone)

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#22796] opened 2021-01-12 16:37 UTC
#### Describe the bug

I've updated to 1.2.1 version but i notice now that in My Account page customers see all the GDPR part in english only,

#### Expected behavior

Usually when customer change languafge also the gdpr menu language change.
All translations are present and correct, but the module psgdpr continue to show only the english languageeven if we have 2 language installed.

#### Steps to Reproduce

i simply updated the GDPR module to 1.2.1 version

**Screenshots**

![image](https://user-images.githubusercontent.com/16102074/104327672-5086ee80-54eb-11eb-914c-a132229c82de.png)

![image](https://user-images.githubusercontent.com/16102074/104343094-d317aa00-54fb-11eb-9437-94bc4040faec.png)

The GDPR modules come already with many translation:

![image](https://user-images.githubusercontent.com/16102074/104343689-897b8f00-54fc-11eb-8f58-cc8291023248.png)

the problem is the other language !=en are not loaded!

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-01-12 17:18
Hello @HartLarsson 

Why you didn't watch carefully the screen record that I attached in your closed issue :confused: 
I will redo the screen record more clearly and I will list step by step how you insert your traductions, so please pay attention :wink: 

1. **BO**>**IMPROVE**>**International**>**Translations**
2. In **Modify translations** block, select **Installed modules translations** as **Type of translations**
3. Then select **GDPR** module as **Select your module**
4. Choose your language
5. Click on Modify button
6. Enjoy doing tranduction :tada: 
7. Save
8. Check FO => everything works perfectly :tada: 

And here's the new screen record with 1.7.6.7 and an updating GDPR :wink: 

https://drive.google.com/file/d/1cQSTKE40dWuxm_CtTouB7vTjvIXD-mkV/view

Enjoy it :slightly_smiling_face: I'm not closing the issue :wink: 
Waiting for your feedback.

PS: originally posted #22789

Thanks!

**Comment by HartLarsson** [comment] 2021-01-12 17:32
hi @hibatallahAouadni 
i've done exactly the same of yours:


step 1
**
![image](https://user-images.githubusercontent.com/16102074/104350110-14ac5300-5504-11eb-917c-bdb49c29b39f.png)
**

click the button and this is what i get all traslated:

![image](https://user-images.githubusercontent.com/16102074/104350506-82f11580-5504-11eb-8e14-45f44ca2639e.png)

**Comment by HartLarsson** [comment] 2021-01-12 17:35
I did a second test changing my default profile language from Italian to english and now i see a different translation page.. why???
I choose exactly same parameters on the first step but with english backoffice language translations are now missing!
there is a bug somewhere.

**Comment by JBWModules** [comment] 2021-01-19 05:14
I can confirm this bug and think the root cause is some renaming of tranlations/template files - now the keys for this translations are not valid anymore and are not loaded.
![grafik](https://user-images.githubusercontent.com/47666330/104990744-89f4b800-5a1d-11eb-803c-ec2eafcb07b3.png)

**Comment by JBWModules** [comment] 2021-01-19 05:15
![grafik](https://user-images.githubusercontent.com/47666330/104990867-c88a7280-5a1d-11eb-8f75-1ac1867b3f71.png)

**Comment by hibatallahAouadni** [comment] 2021-01-19 08:56
@HartLarsson @JBWModules Thanks guys for the clarifications :wink: 
I need to reproduce the issue, I will work on it :slightly_smiling_face:

**Comment by hibatallahAouadni** [comment] 2021-01-25 00:07
Hello @HartLarsson 

Even when I changed my default language to Italian, I didn't manage to reproduce, see the attached screen record below:

https://drive.google.com/file/d/1F5PPd7iGHcig4MbXm1UEVFWOOZNnZMYI/view

Please check and feedback.
Thanks!

**Comment by HartLarsson** [comment] 2021-01-28 21:38
> Hello @HartLarsson
> 
> Even when I changed my default language to Italian, I didn't manage to reproduce, see the attached screen record below:
> 
> https://drive.google.com/file/d/1F5PPd7iGHcig4MbXm1UEVFWOOZNnZMYI/view
> 
> Please check and feedback.
> Thanks!

i think the problem is for the native language, mine is italian yours?
I've this problem sometimes and switch back to english let me fix translations.

**Comment by hibatallahAouadni** [comment] 2021-02-01 16:40
Hello @HartLarsson 

Sorry for the late response.

> i think the problem is for the native language, mine is italian yours?

You mean by native language, the language that you have chosen when you installed your store, is that so?
If so, mine is English.

Thanks!

**Comment by HartLarsson** [comment] 2021-02-09 21:50
yes for some reason in my default (1st install language) the translations problem happens

**Comment by hibatallahAouadni** [comment] 2021-02-09 22:04
@HartLarsson ok I will try to reproduce the issue after installing my shop with Italian as thedefault language :wink:

**Comment by hibatallahAouadni** [comment] 2021-02-26 13:37
Hello @HartLarsson 

I just installed a new shop with Italian language and yet I didn't manage to reproduce your issue :confused: 
See the attached screen record below:

https://drive.google.com/file/d/18Wj8oCAs5E1yrtQ5V8v4ah-ARTleBjZL/view

Please check and feedback.
Thanks!

**Comment by HartLarsson** [comment] 2021-03-16 19:34
Please add a second English language.
There are KEY problem as shown by @JBWModules  for translations

**Comment by hibatallahAouadni** [comment] 2021-03-17 09:05
Hello @HartLarsson 

> Please add a second English language.

As you can see in my screen record, I already have the English language installed.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-04-06 13:23
Hello @HartLarsson ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-06 13:23 UTC
Labels: Bug, FO, Translations, GDPR, No change required, 1.7.6.7
