### ISSUE TITLE
Specific prices appears without tax

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#14843] opened 2019-07-24 10:55 UTC
Specific prices are displayed without tax.
But the price and final price are good.
Example : https://www.beastybike.com/bagagerie/1351-11788-sac-a-dos-ortlieb-velocity-design-2019.html

Configuration of specific price :
![image](https://user-images.githubusercontent.com/44002621/61788284-06e7a700-ae12-11e9-9ba8-c454a0aa545e.png)

And tax applied is FR 20%.

PrestaShop version : 1.7.5.1
PHP version : 7

**Comment by khouloudbelguith** [comment] 2019-07-24 11:47
Hi @guigplt,

This issue should be fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/13684, it is fixed in the PS1.7.6.0.
Thanks to check & feedback.

**Comment by guigplt** [comment] 2019-07-24 14:32
Thanks for your answer, but is it the same case ?
Because my customer groups use taxes :

![image](https://user-images.githubusercontent.com/44002621/61802173-5210b280-ae30-11e9-8812-882c11522f8e.png)

**Comment by khouloudbelguith** [comment] 2019-07-24 14:59
@guigplt, seems that your issue is different.
In my case, with PS1.7.5.1, I did not manage to reproduce the issue.
I attached a screen record
https://drive.google.com/file/d/1WppccHe_nvoF5RuXiGZbAILdk_wMm9D2/view
Have you tried to contact the theme author about this issue?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-23 07:28
Hi @guigplt, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-23 07:28 UTC
Labels: Bug, FO, Discounts, Taxes and Prices, No change required, 1.7.5.1
