### ISSUE TITLE
VAT on Invoice are wrong if you use multiples products with distinct taxes and a free gift

### ISSUE THREAD

**Issue by MathildeJoli** [PrestaShop/PrestaShop#36650] opened 2024-07-31 20:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As you can see on this screenshot, on the bottom, the infos for the VAT at 10% and 20% are not OK. 
We can see that 10% of 10.05 is 0.92 which is totally wrong.

![image](https://github.com/user-attachments/assets/55f6b16e-2938-4de6-a9ef-51e1be02f88e)

### Expected behavior

I'd like to see a correct VAT taxes number.

The VAT rate is at 10%, the base product is at 10.05 euros so the VAT can't be at 0.92 euros. It shall be 1.01
Same for the VAT for the 20% rate.

Base product numbers seem to be coherent.

### Steps to reproduce

On a fresh install of prestashop : 
-  create a product with a VAT of 10%
- create a second one with a VAT of 20%
- create a third one with a VAT of 20%

Create a discount code with a free gift for the third product.

On the back office, create an order with the first product, the second product and add the discount code that give you the third product.

### PrestaShop version(s) where the bug happened

8.1.3 / 8.1.7

**Comment by cruftex** [comment] 2024-08-01 15:42
I think there are more details needed to reproduce this. Did you, setup the discount with "tax included" or "tax excluded"?

This issue looks quite similar:
https://github.com/PrestaShop/PrestaShop/issues/24122

**Comment by florine2623** [comment] 2024-08-09 13:02
Hello @MathildeJoli ,

It seems like your issue is the same as https://github.com/PrestaShop/PrestaShop/issues/34085.

Could you confirm ?

Thanks!

**Comment by Eolia** [comment] 2024-08-13 10:59
VAT calculation is wrong because based on actual prices (discount not deducted but product at 9€ completly deducted)
10% => 12.90 => 1.29
20% => 18.90 => 3.78
Total VAT 5.07

The real is 5.36

![image](https://github.com/user-attachments/assets/0acf2d56-37d7-4d92-8964-d3fbe4abb905)

**Comment by paulnoelcholot** [comment] 2024-08-29 08:28
Hello @MathildeJoli,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-08-29 08:28 UTC
Labels: Bug, Invoices, Cart rules, Invalid, 8.1.x
