### ISSUE TITLE
Archive "solrsearch" module?

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#22651] opened 2021-01-04 09:51 UTC
#### Describe the bug

There is a repository PrestaShop/solrsearch with an old module to use PrestaShop with the Solr technology. Is it still active? does it work with 1.7? if no and no, is it something to archive? Can someone from product team and core team have a look at it?

I created this issue so this task is tracked. The question has first been asked here:
https://github.com/PrestaShop/traces/pull/14

**Comment by hibatallahAouadni** [comment] 2021-01-04 10:07
Hello @ttoine 

Ping @PrestaShop/product-team could someone answer @ttoine question.

Thanks in advance.

**Comment by LouiseBonnard** [comment] 2021-01-04 17:34
Well, I've never heard of it before... As far as I can read [here](https://github.com/PrestaShop/solrsearch), it was designed for R&D but has not been updated since its creation in 2016. 🤔 

If someone from the @PrestaShop/prestashop-core-developers could investigate, it will help us know what to do with it - that being said, if no one knows about it, I'd conclude it is not used anymore and suggest to archive it. 😄

**Comment by matks** [comment] 2021-01-04 20:57
https://github.com/PrestaShop/solrsearch contains very few logic so I think it's far from complete

Moreover I dont know if Solr is really what people look for nowadays for search engine. Since 2016 there are new search tech that is more popular.

I suggest to archive it.

**Comment by ttoine** [comment] 2021-01-05 09:14
who can actually do it with the good admin rights? @matks you can?
if we do that, we must not forget to update Pablo's spreadsheet about repositories.

**Comment by PierreRambaud** [comment] 2021-01-05 10:45
I archive it, we don't use it, don't maintain it and it was a POC. :)
I'm closing this issue since the problem is resolved

**Closed as completed by PierreRambaud** 2021-01-05 10:45 UTC
Labels: PM ✔️, 1.7.x, CO, Modules, Fixed
