### ISSUE TITLE
Impossible to upload single file with form_fields in AdminController with HelperForm class

### ISSUE THREAD

**Issue by davemax** [PrestaShop/PrestaShop#27934] opened 2022-03-16 10:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After this commit:
https://github.com/PrestaShop/PrestaShop/commit/56028c3ec6dbb80dfb1f60e6a7656416582d93f3

[name] attribute for inputs can't be the same in a single form.

Faulty file: [admin-dev/themes/default/template/helpers/uploader/simple.tpl]

### Expected behavior

input type=file  should have different [name] attribiute than input for showing the filename

### Steps to reproduce

1. Try to setup a new module with custom fields form, for ex.:

```
 $this->fields_form = [
            'legend' => [
                'title' => $this->l('Import ' . $this->import_name),
                'icon' => 'icon-cog'
            ],
            'input' => [
                [
                    'type' => 'hidden',
                    'cast' => 'intval',
                    'validation' => 'isInt',
                    'name' => 'id_import_type',
                ],
                [
                    'type' => 'file',
                    'label' => $this->l('File'),
                    'desc' => $this->l('Upload import file'),
                    'name' => 'import_file',
                ],
            ],
```
            
2. It will generate faulty form with duplicated [name] attribute inputs

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-03-16 11:47
Hello @davemax 

Could you please provide a basic module contain this code, so I can reproduce the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by davemax** [comment] 2022-03-16 12:07
Hey @hibatallahAouadni ,
it may take  1-2 days, I'm currently occupied with alot of stuff. But will try to upload it soon.

Here is an extra screenshot of generated HTML from presta 1.7 BO. Its not valid to have same [name] for inputs in a single form. It will override one another. It all because of the orginal commit where $name variable is used
![image](https://user-images.githubusercontent.com/11661315/158586292-eaa0e7fd-62e3-4a5f-8835-5340f020dc81.png)

**Comment by hibatallahAouadni** [comment] 2022-03-16 13:23
Hello @davemax 

> it may take 1-2 days, I'm currently occupied with alot of stuff. But will try to upload it soon.

We will wait for your answer up to 20 days.
After 20 days, if we do not receive any response from you, we will close the issue.

Thanks!

**Comment by florine2623** [comment] 2022-04-05 12:25
Hello ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2022-04-05 12:25 UTC
Labels: Bug, 1.7.x, BO, Modules, Forms BO, Invalid
