### ISSUE TITLE
An error on the module ps_legalcompliance  v3.0.2 configuration with php7.4

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#30692] opened 2022-12-29 07:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On PS 1.7.8.x with DEBUG on, using the module a lot of errors appears while entering in configuration like:

```
Notice alla linea 1626 nel file /home2/userx/public_html/modules/ps_legalcompliance/ps_legalcompliance.php
[8] Trying to access array offset on value of type null
```

I saw the module is no longer maintained but thre is a future project to implement a new version for 1.7.8x and 8.x?

### Expected behavior

I expect that on ps 1.7.x during ocnfiguration no error will popup during debug.

### Steps to reproduce

1. Install the module from https://github.com/PrestaShop/ps_legalcompliance
2. enter in its configuration keeping DEBUG on
3. a popup will appear with errors

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_legalcompliance

**Comment by HanaRebaiQA** [comment] 2022-12-29 15:19
Hello @HartLarsson 

Thanks for your report.
I was able to reproduce your issue with PS1788 and PS800 **only with php7.4 and debug mode is ON**

**PS1788 with php 7.3 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/209973479-2568503d-cae3-4ec5-b287-e51d98554d40.png)

**PS1788 with php 7.4 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/209973443-600f5d5c-e027-4650-9aea-e0163728f075.png)

https://user-images.githubusercontent.com/92912932/209973492-c9341668-7b63-48de-b8af-80a81b0839cc.mp4


**PS800 with php 7.4 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/209973429-d82a7177-3000-4ef0-83d8-ef18844974d7.png)

https://user-images.githubusercontent.com/92912932/209973520-f22e3bc1-6c5a-47c4-90d1-c77b68e50de6.mp4


Indeed, it's a regression!

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank You!

**Comment by HanaRebaiQA** [comment] 2022-12-29 15:28
I have noticed that this module is archived 
![image](https://user-images.githubusercontent.com/92912932/209974441-a53f32c5-8db8-4d97-b81b-ff6129880b29.png)

ping @PrestaShop/product-team Can we accept this issue since the module is archived? What do you think ?

Thanks!

**Comment by MatShir** [comment] 2022-12-29 15:30
The module will remain archived until we find a serious maintainer. We don't have the enough resources to maintain it today

**Closed as not planned** 2022-12-29 15:30 UTC
Labels: Bug, Minor, BO, Regression, Module manager, php, Verified, Module, 1.7.8.8

**Comment by HartLarsson** [comment] 2023-01-05 11:49
the module is very important for EU ecommerce. I hope a maintainer will be found soon :)

**Comment by HartLarsson** [comment] 2023-08-18 22:17
without a module how we can determine witch page use for term and conditions and other things?

![image](https://github.com/PrestaShop/PrestaShop/assets/16102074/51eee694-4cc3-4f00-95f5-87e4568fa627)
