### ISSUE TITLE
Javascript console error in ps_facetedsearch on mobile devices

### ISSUE THREAD

**Issue by topfuel75** [PrestaShop/PrestaShop#31832] opened 2023-03-19 22:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After adding the BugSnag CDN code (https://docs.bugsnag.com/platforms/javascript/cdn-guide/) to track javascript console errors I receive the following error:
`undefined is not an object (evaluating 't.ui.mouse.prototype')`

It seems that it is this file that generate the error:
ps_facetedsearch/_dev/front/slider.js:117:6
ps_facetedsearch/_dev/front/slider.js:60:55 

It also seems that this error only appears for mobile devices.

The last error was from a device with the following specs:
browserName: Chrome Mobile iOS
browserVersion: 110.0.5481
osName: iOS 16.3
userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/110.0.5481.114 Mobile/15E148 Safari/604.1

Perhaps it is the outdated https://github.com/furf/jquery-ui-touch-punch that can't handle some mobile devices.
It might be better to switch to the updated fork at https://github.com/RWAP/jquery-ui-touch-punch

### Steps to reproduce

1. Visit a category page with a iOS mobile device. 

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.12.0

**Comment by AureRita** [comment] 2023-03-23 11:05
Hi @topfuel75 

Thank you for your report, I tried to reproduce your issue as you can see here : 

[Untitled_ Mar 23, 2023 11_49 AM.webm](https://user-images.githubusercontent.com/100699445/227183447-7ab46708-23ef-4488-9297-145825a3fea2.webm)

But currenntly I can't, did I miss something ? 

waiting for your feedback

**Comment by florine2623** [comment] 2023-04-06 13:12
Hello @topfuel75 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-04-06 13:12 UTC
Labels: Bug, FO, Faceted search, Module
