### ISSUE TITLE
product price shown zero on second language!

### ISSUE THREAD

**Issue by mikajaxxx** [PrestaShop/PrestaShop#33939] opened 2023-09-14 09:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
the price for product shown zero on editing product!
this happens on second language(persian) with any currency
if i change language to english the problem doesn't shown! so it just happens on second langauge (fa)

### Expected behavior

while editing product the price must shown correctly

### Steps to reproduce

1. create product & set price, the price shown correctly
2. save product 
3. edit product again
4. price shown zero and if i save product the zero price saved 
5. changed language to en
6. the issue not happans

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1 (open litespeed)

**Comment by MhiriFaten** [comment] 2023-09-14 10:52
Hello @mikajaxxx ,

I was not able to reproduce your issue with the provided information.

[Untitled_ Sep 14 2023 11_51 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/d73b9fce-71ab-4117-a978-e8de1aee7160)

Could you please provide us more information or a screenrecord?
Waiting for your feedback.

Thank you !

**Comment by Hlavtox** [comment] 2023-09-15 09:56
@MhiriFaten `this happens on second language(persian) with any currency`

**Comment by mikajaxxx** [comment] 2023-09-16 12:04
@MhiriFaten Could you please check this on persian language too? it seems just persian langauge have such problem!
update: Also some have the same problem in arabic lanague
https://github.com/PrestaShop/PrestaShop/issues/33871#issue-1885661628

**Comment by ghadazoubi** [comment] 2023-09-17 10:36
I have the same issue in Arabic language too

**Comment by florine2623** [comment] 2023-09-20 14:22
I'm closing your issue as it is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/33871

**Comment by Hlavtox** [comment] 2023-09-20 14:50
Misclick

**Closed as completed** 2023-09-20 14:49 UTC
Labels: Bug, BO, Duplicate, 8.1.x, Products Page
