### ISSUE TITLE
"Orders > Products" : Use UI Kit for Input Number 

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#16567] opened 2019-11-27 16:26 UTC
**Is your feature request related to a problem? Please describe.**
Create a component Input Number in UI Kit

**Comment by prestascott** [comment] 2020-06-03 08:27
@PrestaShop/prestashop-product-team

**Comment by prestascott** [comment] 2020-06-03 09:07
Epic: #16587

You can find the redesign of the input number in UI Kit here: [Link to InVision prototype](https://invis.io/S9UXGJA73B5)

**Comment by colinegin** [comment] 2020-06-03 15:37
Should it be part of the EPIC then ?

**Comment by prestascott** [comment] 2020-06-04 13:21
Yes, it's already part of the epic and has its own issue : #16599

**Comment by MatShir** [comment] 2020-08-05 15:21
@prestascott It seems the issue is done by https://github.com/PrestaShop/PrestaShop/issues/16599, can we close this issue ?

**Comment by prestascott** [comment] 2020-08-17 08:54
@MatShir Yes, issue is done by #16599 so we can close this issue.

**Closed as completed by prestascott** 2020-08-17 08:54 UTC
Labels: Improvement, Order
