### ISSUE TITLE
Unable to update settings Prestashop 1.7.5.0

### ISSUE THREAD

**Issue by Olmanuel** [PrestaShop/PrestaShop#12581] opened 2019-02-14 22:23 UTC
**Describe the bug**
I just installed prestashop 1.7.5.0 on my whogohost server, i tried uploading a product but it brings up a red alert saying "unable to upload settings"

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: im hosting it from my web whose, whogohost.

**Comment by khouloudbelguith** [comment] 2019-02-15 08:24
Hi @Olmanuel,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Olmanuel** [comment] 2019-02-19 06:59
Hy Khouloudbelguith,
host: whogohost
PrestaShop Version: 1.7.5.0

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
26?_token=EUSkXEVwKi5bDnff7Ci-emfSYLTZ-eaf2l3PMHlOBaE:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (form.js?1.7.5.0:687)
    at u (main.bundle.js:275)
    at Object.fireWith [as rejectWith] (main.bundle.js:275)
    at i (main.bundle.js:275)
    at XMLHttpRequest.<anonymous> (main.bundle.js:275)

my debug mode is also switched off.

**Comment by khouloudbelguith** [comment] 2019-02-19 08:13
@Olmanuel, your issue seems to be similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/12517#issuecomment-462280995
Can you please try to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by Olmanuel** [comment] 2019-02-20 10:47
@khouloudbelguith , this is the error i saw:

Attempt to call function "iconv_strlen" from namespace "PrestashopBundle\Form\Validator\Constraints"

**Comment by khouloudbelguith** [comment] 2019-02-20 10:52
Hi @Olmanuel,

Your iconv.so extension in /etc/php/php.ini is commented out/disabled for some reason.
You need to enable it.
We have already ticket: #10152 about this issue.
Thanks to enable it on your server, check & feedback.

**Comment by Olmanuel** [comment] 2019-02-20 11:12
@khouloudbelguith , How do i enable iconv.so?

**Comment by khouloudbelguith** [comment] 2019-02-20 11:14
@Olmanuel, in your /etc/php/php.ini file, you need to uncomment  `iconv.so`.
Also, you can check with your host.
Thanks!

**Comment by Olmanuel** [comment] 2019-02-20 11:46
@khouloudbelguith , i did not work with my local host and any point, only my host. where do you suggest i find this with my host? my host etc folder doesnot have a php folder

**Comment by khouloudbelguith** [comment] 2019-02-20 11:53
@Olmanuel, so, you need to check your host provider to enable the iconv.so extension.
Thanks!

**Comment by Olmanuel** [comment] 2019-02-20 15:08
@khouloudbelguith , i am having a bit of difficulty finding this file, is it meant to be on the host's cpanel?

**Comment by khouloudbelguith** [comment] 2019-02-20 15:22
@Olmanuel, yes it could be.
Thanks!

**Comment by papich06** [comment] 2019-02-22 15:40
i have the same problem
![capture d ecran 2019-02-22 a 10 26 43](https://user-images.githubusercontent.com/4650270/53252957-6e14fa00-36c0-11e9-8782-d165a2dfaef6.png)
![capture d ecran 2019-02-22 a 10 26 53](https://user-images.githubusercontent.com/4650270/53252978-7a00bc00-36c0-11e9-8f8c-0a55cef10d76.png)
![probleme-prestashop-1 7](https://user-images.githubusercontent.com/4650270/53253013-8c7af580-36c0-11e9-8f43-4713aa317b9b.jpg)

**Comment by khouloudbelguith** [comment] 2019-02-22 15:43
Hi @papich06,

If you enable the debug mode, what is the exact exception displayed?
Thanks!

**Comment by papich06** [comment] 2019-02-22 15:45
Hi @khouloudbelguith ,
i activate debug but where i watch bug?

**Comment by khouloudbelguith** [comment] 2019-02-22 15:48
@papich06, when you navigate to your BO => Products page & you try to update a product => any exception is displayed or not?
Thanks!

**Comment by papich06** [comment] 2019-02-22 15:53
where i check?
![capture d ecran 2019-02-22 a 16 52 46](https://user-images.githubusercontent.com/4650270/53253825-6b1b0900-36c2-11e9-8e2b-aab7d707e803.png)

**Comment by khouloudbelguith** [comment] 2019-02-22 15:55
@papich06,

You can debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. save product
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by papich06** [comment] 2019-02-22 16:00
@khouloudbelguith 
well i have this how to fix it please?
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Erreurs/JSON_bad_parse

![g](https://user-images.githubusercontent.com/4650270/53254287-5ee37b80-36c3-11e9-96ca-2b6f0576c552.jpg)

**Comment by khouloudbelguith** [comment] 2019-02-22 16:07
@papich06, in the BO => Product page, check the tab option, the tags of this product contain special characters?
Thanks!

**Comment by papich06** [comment] 2019-02-22 16:12
@khouloudbelguith  what do you means about special characters?
and if yes how to fix  it?

i have noting in tags but in title 
i have this charactères "è" and / in category

**Comment by khouloudbelguith** [comment] 2019-02-22 16:17
@papich06, for example, if tag contains a value with **"**, **°**
Thanks!

**Comment by papich06** [comment] 2019-02-22 16:19
@khouloudbelguith  no i don't have this

**Comment by khouloudbelguith** [comment] 2019-02-22 16:24
@papich06, your issue seems to be similar to this ticket:#12654
Thanks to follow this issue.

**Comment by khouloudbelguith** [comment] 2019-03-25 07:56
Hi @Olmanuel,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-25 07:56 UTC
Labels: BO, No change required, 1.7.5.0

**Comment by Prem-lmx** [comment] 2019-07-19 13:21
Hai,
im using the prestashop version1.7.5.2
i have the change product price after that save the but pop-up the error in unabe to update the setting error....
please support me...

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-19 13:26
@Prem-lmx, This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by Prem-lmx** [comment] 2019-07-22 08:08
Hai  @khouloudbelguith ,
but site is puplish,
 so any other choice the issue
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-22 08:46
@Prem-lmx, thanks to create a new issue on GitHub about your exact problem with more information about your configuration to reproduce your issue.

Thanks!

**Comment by Prem-lmx** [comment] 2019-08-19 05:51
Hai @khouloudbelguith <https://github.com/khouloudbelguith> ,

How to add new field in prestashop1.7

The   (catalog-->Products-->Price)
 In price path..

Thanks,
Prem
