### ISSUE TITLE
Free GIFT is not displayed correctly on cart 

### ISSUE THREAD

**Issue by SebBareyre** [PrestaShop/PrestaShop#14939] opened 2019-07-31 15:15 UTC
**Describe the bug**
Contrary to PrestaShop 1.6, in Prestashop 1.7, the display of gift are not clear in cart summary...

**To Reproduce**
1. In BO, create a cart rule that offers a product as gift
2. In the FO, add to cart a product
3. Go to the summary cart page
4. See the display inconsistency
 
**Screenshots**
Here a display proposition in PrestaShop 1.7:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/3274119/62223746-bcd46780-b3b5-11e9-9f7a-7896bc874bb2.png">

As a reminder, in PrestaShop 1.6 the display was correct:
![image](https://user-images.githubusercontent.com/3274119/62223468-40418900-b3b5-11e9-823d-f00583810751.png)

**Additional information**
PrestaShop version: 1.7.5 / 1.7.6

**Comment by jf-viguier** [comment] 2019-07-31 15:15
We and some of our merchants in 1.7 are concerned by this issue. Thanks Seb

**Comment by khouloudbelguith** [comment] 2019-07-31 15:23
Hi @SebBareyre,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9757
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-31 15:23
Duplicate of #9757

**Closed as completed by khouloudbelguith** 2019-07-31 15:23 UTC
Labels: Duplicate
