### ISSUE TITLE
After update  "Prestashop 1click upgrade" to 4.16.0 version, configuration page is blank when I enable maintenance page

### ISSUE THREAD

**Issue by CreativeTerry** [PrestaShop/PrestaShop#33277] opened 2023-07-17 08:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi I had upgraded the Prestashop 1click upgrade module to 4.16.0 version. Now when I open the module's configuration page and if the site is not under maintenance then it dsn't show the upgrade button and rest all of the options are shown on page and if I put site under maintenance then only blank page is displayed in config page of module..!! Also the blankl white page is not shown anywhere i.e. in Back-end or in Front-end.
I don't know what to do as I never had any problems with Prestashop native modules and I need to upgrade Prestashop to latest version.

![Prestashop issue](https://github.com/PrestaShop/PrestaShop/assets/137721013/a5bafdc7-ae2a-4699-b3bc-c8a6b5eb7407)
![Prestashop issue - 1](https://github.com/PrestaShop/PrestaShop/assets/137721013/023a561c-cb79-4efc-9328-a3727c917a7f)
![Prestashop issue - 2 ](https://github.com/PrestaShop/PrestaShop/assets/137721013/d128bf9f-a960-4ec8-a152-cc3b14836eed)

### Expected behavior

There should be an button with text Update should be there and upon clicking on it upgrade will start and there will no blank screen shown if site is put under maintenance. 

### Steps to reproduce

1. Open Module manager.
2. Click configure option for the 1 Click upgrade Module.
3. Don't put site under maintenance.
4. Now there is no button with a text of upgrade and its showing error of Requirement not met because Site is not under maintenance.
5. Now put site under maintenance and refresh the 1Click upgrade module page.
6. Now there is nothing shown on page except a blank page.

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

1click upgrade module to 4.16.0

**Comment by AureRita** [comment] 2023-07-17 13:01
HI @CreativeTerry 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ Jul 17, 2023 2_56 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/65835050-80bd-40f2-aa24-aee2a0f76f97)

but currently I can't, did I miss something ? 

Can you give us your php version, as you can see on the video, you can see it on BO>Advenced Parameters> Information 
Moreover, this is the expected behavior that the update need to put your shop in maintenance. 

Waiting for your update

**Comment by aniszr** [comment] 2023-08-09 07:24
Hello ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by aniszr** 2023-08-09 07:24 UTC
Labels: Bug, BO, Maintenance, Autoupgrade, Invalid, Module, 1.7.8.7

**Comment by CreativeTerry** [comment] 2023-09-22 11:19
Hi, Sorry for late reply. Actually messed up with google SEO issues.... 
But Problem in upgrade module still persists.

**Comment by CreativeTerry** [comment] 2023-09-22 12:21
Hi, The problem solved now in new version of module. :)
Thanks
