### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by anglesgirl** [PrestaShop/PrestaShop#15134] opened 2019-08-16 14:30 UTC
**Describe the bug**

从仪表盘，国际，翻译
进行翻译后，一些翻译不能被应用！

The translation part cannot be applied

![8769CE4F-6267-4C47-B97D-D4E5C1A7DB99](https://user-images.githubusercontent.com/17689356/63174832-587ffc00-c075-11e9-9645-f379177def4d.jpeg)
![A288930B-A12B-4338-A3F7-F528D312A28B](https://user-images.githubusercontent.com/17689356/63174833-587ffc00-c075-11e9-846a-4e7a1abf3f40.jpeg)
![CBB87A01-A638-42A3-B6D4-519FF97C5C4B](https://user-images.githubusercontent.com/17689356/63174834-59189280-c075-11e9-815b-f03f38617615.jpeg)

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.21

**Comment by mariem-abid** [comment] 2019-08-16 14:57
Hi @anglesgirl,

I manage to reproduce the issue with PS 1.7.5.2 and PS 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1gwBFbp2fad0USrB4spMR3iYhi1nXyJTO/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2019-08-16 16:33
@anglesgirl What is your language: Simplified Chinese or Traditional Chinese ?
I guess it's because these languages are not translated at 100% @LouiseBonnard wdyt ?

**Comment by anglesgirl** [comment] 2019-08-16 16:59
> @anglesgirl你的语言是什么：简体中文或繁体中文？
> 我想这是因为这些语言不是100％@ LouiseBonnard wdyt翻译的？

我已经手动进行了翻译，翻译完成后，没有被应用

**Comment by marionf** [comment] 2019-08-16 17:09
@anglesgirl 
Could you please send your comment in English ?

**Comment by anglesgirl** [comment] 2019-08-16 17:16
> @anglesgirl
> Could you please send your comment in English ?

I have completed the translation operation.。
The problem still exists.

**Comment by marionf** [comment] 2019-08-16 18:19
> I have completed the translation operation

I don't understand what do you mean  ?
What is your language: Simplified Chinese or Traditional Chinese ?

**Comment by anglesgirl** [comment] 2019-08-16 19:00
> > 我已完成翻译操作
> 
> 我不明白你是什么意思？
> 你的语言是什么：简体中文或繁体中文？

my language Simplified Chinese 

Dashboard/International/Translations/，Type of translation/back office Translations
Complete translation 100%，The problem still exists.

**Comment by anglesgirl** [comment] 2019-08-17 15:50
> > I have completed the translation operation
> 
> I don't understand what do you mean ?
> What is your language: Simplified Chinese or Traditional Chinese ?

hello

**Comment by LouiseBonnard** [comment] 2019-08-19 08:57
Hello there, I confirm! From a Crowdin point of view, the string (_Module Manager_) is both translated and validated. As a consequence, it should be written in Chinese in the Chinese version of PrestaShop.

**Comment by colinegin** [comment] 2019-11-25 16:26
Hello @marionf and @LouiseBonnard is there anything to do here on our side ?

**Comment by LouiseBonnard** [comment] 2019-11-25 17:29
Hey @colinegin, the issue is addressed [here](https://github.com/PrestaShop/PrestaShop/issues/12590), it is waiting for dev. I guess we can close this issue to avoid duplicates?

**Comment by colinegin** [comment] 2019-11-26 08:58
Yes exactly, we just need to note this as a duplicate. Thanks !

**Comment by LouiseBonnard** [comment] 2019-11-26 09:03
DUPLICATE OF #12590

**Closed as completed** 2019-11-26 09:03 UTC
Labels: Bug, Trivial, BO, Duplicate, Translations, 1.7.5.2, 1.7.6.0
