### ISSUE TITLE
Adding product in BackOffice order gets the price in default shop currency, and not the order currency. PS 1.7.4.2

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#13526] opened 2019-04-23 11:40 UTC
When trying to add a new product to an (not yet valid) order in PS backoffice default currency the price is added in the default currency instead of the currency selected for that order.

The price is shown correctly in the input fields before clicking "add", but after then this happens: Value is set in the default currency, while the currency symbol is set to order currency. 

**Example:** 
My shop has default currency NOK. I have an order with one pcs with "Jacket" priced to 25EUR, giving total order sum to 25 EUR. Since the order uses bankwire, and the customer needs to add a product, I want to add a T-shirt to this order. the t-shirt is priced to 100 NOK (dafault) or about 10 EUR.
When adding the product, I expect the price to be 10 EUR, but it's instead priced to 100 EUR.

Order sums is also going bananas showing the shop default currency symbol (NOK), instead of order currency (EUR),  but using the order currency value for the jacket and original value for the new product: 25NOK (should be 25 EUR) + 100 NOK (should be 10EUR) = 125 NOK.

![unnamed](https://user-images.githubusercontent.com/30602638/56578166-3d244900-65cd-11e9-9781-971551e9cf4f.png)
![unnamed](https://user-images.githubusercontent.com/30602638/56578177-40b7d000-65cd-11e9-9ed5-15090609b028.jpg)

**Comment by khouloudbelguith** [comment] 2019-04-23 13:18
Hi @onklmaps,

Is it the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/12521?
Thanks to check & feedback.

**Comment by madsoliver** [comment] 2019-04-24 12:14
> Hi @onklmaps,
> 
> Is it the same issue reported here: #12521?
> Thanks to check & feedback.

That issue was not as much described, but it looks like it, yes. When is this probably fixed?

**Comment by khouloudbelguith** [comment] 2019-04-24 13:18
@onklmaps, the issue is added to bug roadmap, so that will be fixed.
PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.
Your ticket is a duplicate of #12521
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-04-24 13:18 UTC
Labels: BO, Duplicate, Order, Currencies, 1.7.5.1
