### ISSUE TITLE
Error módulo carrito actualización 2.0.3

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18390] opened 2020-03-31 13:09 UTC
Antes de actualizar el módulo, cuando se despliega la ventana pequeña del carrito le dabas a eliminar producto y se eliminaba al instante.
Desde la última actualización le das a eliminar producto y hasta que no refrescas la página no se muestra el cambio.
https://prnt.sc/rq5p0x

Before updating the module, when the small window of the cart is displayed, you gave to eliminate product and it is eliminated instantly.
Since the last update, you delete the product and until the page is not updated, the change is not shown.
https://prnt.sc/rq5p0x

**Comment by khouloudbelguith** [comment] 2020-03-31 13:30
Hi @alfonsolr09,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by alfonsolr09** [comment] 2020-03-31 13:40
Before updating the module, when the small window of the cart is displayed, you gave to eliminate product and it is eliminated instantly.
Since the last update, you delete the product and until the page is not updated, the change is not shown.
https://prnt.sc/rq5p0x

**Comment by khouloudbelguith** [comment] 2020-03-31 13:54
Hi @alfonsolr09,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17633 to fix the issue.
it is fixed in the next version ps1.7.8.0
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/16665#issuecomment-561519780
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-31 13:54
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16665

**Closed as completed by khouloudbelguith** 2020-03-31 13:54 UTC
Labels: Duplicate

**Comment by alfonsolr09** [comment] 2020-03-31 14:04
> Hola @ alfonsolr09 ,
> 
> Aquí está el PR: [# 17633](https://github.com/PrestaShop/PrestaShop/pull/17633) para solucionar el problema.
> está arreglado en la próxima versión ps1.7.8.0
> Su boleto es un duplicado del [# 16665 (comentario)](https://github.com/PrestaShop/PrestaShop/issues/16665#issuecomment-561519780)
> Entonces, lo cierro.
> ¡Gracias!

¿cuando se lanzará esta versión ?

**Comment by alfonsolr09** [comment] 2020-03-31 14:04
¿no debería solucionarse en una actualización del módulo?

**Comment by khouloudbelguith** [comment] 2020-03-31 14:19
@alfonsolr09,

English is the norm on the GitHub
Thank you!

**Comment by alfonsolr09** [comment] 2020-03-31 14:30
Shouldn't it be resolved in a module update?

**Comment by khouloudbelguith** [comment] 2020-03-31 14:36
@alfonsolr09, this issue is fixed in the PrestaShop Core: https://github.com/PrestaShop/PrestaShop/pull/17633/files

Thanks!

**Comment by alfonsolr09** [comment] 2020-07-26 23:43
@klazer337
