### ISSUE TITLE
Returns nowhere to be found

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#10642] opened 2018-09-22 13:29 UTC
When I get returns for my orders they are not processed into the ps_order_detail table - although that contains fields for that purpose.

**Comment by khouloudbelguith** [comment] 2018-09-24 08:24
Hi @musicpanda,

Could you please add steps to reproduce the issue in a new comment.
We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)

Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-23 16:45
Hi @musicpanda 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-23 16:45 UTC
Labels: Order, No change required
