### ISSUE TITLE
Undefined method extractTheme in AdminThemesController.php

### ISSUE THREAD

**Issue by davidguestforce** [PrestaShop/PrestaShop#14158] opened 2019-06-11 16:17 UTC
**Describe the bug**
When trying to open Admin Panel -> Design -> Theme & Logo an Error 500 pops up. After enabling debugging the error shows that method _extractTheme_ is not defined. 

The one and only place where _extractTheme_ occurs is line 126 in \controllers\admin\AdminThemesController.php

I could not find definition of that method anywhere in PrestaShop files.

**To Reproduce**
1. Go to Admin Panel -> Design -> Theme & Logo

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.1.25

**Comment by khouloudbelguith** [comment] 2019-06-11 16:21
Hi @davidguestforce,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2.
I attached a video record.
https://drive.google.com/file/d/1REdj4IMgstBKhDqJKa15T7lyLERVXa_o/view
Thanks to check & feedback.

**Comment by davidguestforce** [comment] 2019-06-11 17:53
> Hi @davidguestforce,
> 
> I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2.
> I attached a video record.
> https://drive.google.com/file/d/1REdj4IMgstBKhDqJKa15T7lyLERVXa_o/view
> Thanks to check & feedback.

I have custom theme installed:
[https://addons.prestashop.com/en/home-garden-themes/24311-interior-furniture-store.html](url)

_extractTheme_ is called only from within _downloadAddonsThemes_ in AdminThemesController
Since I did not find definition of _extractTheme_ anywhere in PrestaShope I guess you did not get any error because _downloadAddonsThemes_ is not being called when you open Theme & Logo.
It is called from the same controller in method _renderOptions_ :
`if ($this->logged_on_addons) {`
`    $this->downloadAddonsThemes();`
`}`

**Comment by khouloudbelguith** [comment] 2019-06-12 07:54
Hi @davidguestforce,

Have you tried to contact the theme author about this issue?
I tried to use another Theme but, I did not manage to reproduce the issue.
![image](https://user-images.githubusercontent.com/16067358/59333107-99633980-8cef-11e9-9d87-ba2e1cc09ae7.png)

Thanks!

**Comment by davidguestforce** [comment] 2019-06-12 12:58
I do not think that theme author has anything to do with that. The method that is called and not defined is in **AdminThemesController** that extends **AdminController** which in turn extends **Controller**. It must be that my shop's configuration meets some criteria that must be met for this part of code to be executed and therefore triggers error.

The point is that this is PrestaShop's code and not theme author's code.

**Comment by khouloudbelguith** [comment] 2019-06-12 14:06
@davidguestforce,

Could you please provide me your theme to test it.
This is a public space.
You can provide me the theme by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-12 07:41
Hi @davidguestforce,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-12 07:41 UTC
Labels: Bug, BO, Theme & logo, No change required, 1.7.5.2
