### ISSUE TITLE
Unable to enter degrees that come after a name - lastname dot validation

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16780] opened 2019-12-11 20:37 UTC
**Describe the bug**
Customers are unable to enter their degree which is written after the last name.
Example - Ph.D.

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by rdy4ever** [comment] 2019-12-12 09:35
Yes, that's intended behaviour. Prestashop had (and unpached versions still have) big spam problems with boots using urls instead of names to register accounts. Like Firstname: "buyviagra.cz". So the decission was made to not validate any names that look like URLs. In your case, "Ph.D" looks like a URL. "Ph. D"  (mind the space) would work. But what kind of snob would use his academic title to register an account on a webshop, after all? (no offence). Is there a good reason your store needs that? Than you could use a module to add a custom field to the user registration form for this purpose only. But you should do it with predefined values, or else, be prepared for spam.

**Comment by khouloudbelguith** [comment] 2019-12-12 09:54
Hi @Hlavtox, @rdy4ever,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13599 to forbid URLs to be added in customer names
It fixes this issue: https://github.com/PrestaShop/PrestaShop/issues/13524

Thanks to check & feedback.

**Comment by Hlavtox** [comment] 2019-12-12 09:57
@rdy4ever Hi, yes, it was done to prevent these hundreds of bot registrations which put www.hshssgsj.js to their names.

I discovered this during migration from 1.6, when I was going through the log and doing/fixing some stuff manually.

Believe it or not, there are a few customers, that put PhD after their name, even when ordering stuff from internet. 😄 There are assholes that put stuff like “lawyer” before their name, when communicating with us or when returning stuff - to sound more important. 😂🙄

Couldn't we put some exceptions in there? A few common academic degrees?

**Comment by rdy4ever** [comment] 2019-12-12 10:02
> Couldn't we put some exceptions in there? A few common academic degrees?

If it were up to me, I would add a rule to automatically strip academic degrees and display a message like "We don't need that for your order. Thanks anyway."

**Comment by Hlavtox** [comment] 2019-12-12 10:02
@rdy4ever 😂😂😂

**Comment by rdy4ever** [comment] 2019-12-12 10:05
On a more serious note, there are no single letter TLDs, so I guess we could allow a dot before only one letter followed by a space.

**Comment by Hlavtox** [comment] 2019-12-12 10:08
@rdy4ever Hmmm, but in our country, it's written as “Ph.D.” 😬

**Comment by khouloudbelguith** [comment] 2019-12-12 10:23
@Hlavtox, here's the improvement added to PS1.7.7 about the customer creation:
https://github.com/PrestaShop/PrestaShop/issues/14157#issue-454770372

Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-13 08:04
Hi @Hlavtox,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-13 08:04 UTC
Labels: Bug, FO, Customer, No change required
