### ISSUE TITLE
ps 1.7.4.4 unable to re activate default module 

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#14788] opened 2019-07-20 09:21 UTC
**Describe the bug**
2019-07-20 09:17:34.511753 [NOTICE] [7667] [10.11.3.109:42528-5#www.mywebsite.com:lsapi] [STDERR] PHP Warning: require_once(/var/www/webroot/ps1744/modules/ps_imageslider/ps_imageslider.php): failed to open stream: No such file or directory in /var/www/webroot/nfs/www.mywebsite.com/src/Adapter/Module/Module.php on line 323
2019-07-20 09:17:34.511783 [NOTICE] [7667] [10.11.3.109:42528-5#www.mywebsite.com:lsapi] [STDERR] PHP Fatal error: require_once(): Failed opening required '/var/www/webroot/ps1744/modules/ps_imageslider/ps_imageslider.php' (include_path='/var/www/webroot/nfs/www.mywebsite.com/tools/htmlpurifier/standalone:/var/www/webroot/nfs/www.mywebsite.com/vendor/pear/pear_exception:/var/www/webroot/nfs/www.mywebsite.com/vendor/pear/console_getopt:/var/www/webroot/nfs/www.mywebsite.com/vendor/pear/pear-core-minimal/src:/var/www/webroot/nfs/www.mywebsite.com/vendor/pear/archive_tar:.:/usr/local/lsws/lsphp70/share/pear:/usr/local/lsws/lsphp70/share/php:/usr/share/pear:/usr/share/php') in /var/www/webroot/nfs/www.mywebsite.com/src/Adapter/Module/Module.php on line 323

**To Reproduce**
Install PS 1.7.4.4. Disable some module, try to re-enable 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.4.4
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-07-22 08:43
Hi @matteolavaggi,

I did not manage to reproduce the issue with PS1.7.4.4 & PS1.7.5.2 & PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1dWI43m3UumP5CULDJOTC_6UG5KE3krv1/view
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2019-08-21 07:47
Hi @matteolavaggi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-21 07:47 UTC
Labels: Bug, BO, Modules, No change required
