### ISSUE TITLE
Problem with PS Invoice Translation 1.7.7.3

### ISSUE THREAD

**Issue by 4ngeluxpunk** [PrestaShop/PrestaShop#24221] opened 2021-04-27 00:33 UTC
#### Describe the bug

Good afternoon everyone,

I have a problem with a store that when generating the Invoice it appears a field in English, I have translated the fields in the classic theme and cleared the cache but it is not reflected, I have even translated those fields from the invoice.total-tab.tpl file and the changes are not reflected when generating the invoice is something very strange happens to me in all the payment methods.

To have if someone can enlighten me. Greetings.

#### Steps to reproduce

**Screenshots**

![factura](https://user-images.githubusercontent.com/22511504/116167568-17534280-a6c6-11eb-867e-b43676996f2c.png)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.23

**Comment by hibatallahAouadni** [comment] 2021-04-27 07:06
Hello @4ngeluxpunk 

Could you please check this issue #10258 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by 4ngeluxpunk** [comment] 2021-04-27 15:30
Hello @hibatallahAouadni,

Thank you very much for your prompt response, but what I have said does not coincide in the least with my error. I only have one language, there is no more and that is why it seems strange to me that having a language and being translated does not reflect the changes; even changing from the .tpl it doesn't change anything to mention that I don't even have a cache plugin. Greetings.

**Comment by florine2623** [comment] 2021-04-30 13:12
Hello @4ngeluxpunk ,
What language do you have in your BO ?
I have only French, and my invoice shows in French.
![Capture d’écran 2021-04-30 à 15 11 49](https://user-images.githubusercontent.com/16019289/116699873-651dc280-a9c6-11eb-8505-94ea988a6969.png)

**Comment by 4ngeluxpunk** [comment] 2021-04-30 13:52
Hello @florine2623 ,

I only have the Spanish language for both BO and Frontend, so it is strange that only that section is not translated even by editing the file that contains it and clearing the cache.  Greetings.

**Comment by hibatallahAouadni** [comment] 2021-05-10 09:28
Hello @4ngeluxpunk 

Thanks for your patience :pray: 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem. Please check the attached screen record below:

https://drive.google.com/file/d/1v_Oz_i9l7-ZI0LCif279pqM6YTACbYDY/view

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-10 09:28 UTC
Labels: Bug, CO, Can't reproduce, Invoices, Translations, 1.7.7.3

**Comment by 4ngeluxpunk** [comment] 2021-05-10 14:40
Hello @hibatallahAouadni , I also thought the same but it is a clean, new installation.  and it is the only section that is not translated.  Greetings.

**Comment by hibatallahAouadni** [comment] 2021-05-10 18:46
Did you check your overrides?

**Comment by 4ngeluxpunk** [comment] 2021-05-10 18:49
Hi @hibatallahAouadni 

Where I review them, since it is a clean installation without modifications, and only that section of the invoice is not translated by the others without problem.

**Comment by hibatallahAouadni** [comment] 2021-05-10 18:52
Hello @4ngeluxpunk 

> since it is a clean installation without modifications

That's literally ODD :open_mouth: could you please try with another new install (don't install any other module, just basic install).
Please check and feedback.

Thanks!
