### ISSUE TITLE
some problems after enable Memcached 

### ISSUE THREAD

**Issue by IranDec** [PrestaShop/PrestaShop#18925] opened 2020-04-30 21:41 UTC
Hi
after enabling Memcached for caching system my panel got a lot of problems such as 
1) when I wanna clean cache from Advanced Parameters > Performance 
I will get this error :
Invalid token: direct access to this link may lead to a potential security breach. ( this error will be shown in most of my actions that I wanna do or make a change.

2) On the product page when I wanna add a new product I have several problems too, for example, I fill the name and price and category and save that product but when I refresh them they deleted and I have to fill them again.

3) in PHP 7.3 I have these errors in back-office :
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/****/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/****/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665

* PrestaShop version: 1.7.6.4 ( Persian lang )
* PHP version: 7.2 and 7.3
* Cpanel
* LiteSpeed cache enabled

**Comment by Progi1984** [comment] 2020-05-04 14:41
We are aware of this issue, it is already in our debug backlog.

This issue is a duplicate of #9948.

To be informed when it’s fixed, please subscribe to the issue above.

Thank you!

**Comment by sarahdib** [comment] 2020-05-05 15:20
Hello @IranDec 

Do you have those issue using php 7.3 and 7.2 or only with one of them ?

For your information PrestaShop 1.7.6 isn't compatible with php 7.3.

Thank you

**Comment by IranDec** [comment] 2020-05-05 15:41
Hi @sarahdib 
my default PHP ver is 7.2 when I saw I have a problem in PHP 7.2 just for a test I change PHP ver to 7.3

**Comment by florine2623** [comment] 2020-05-07 13:33
Hi @IranDec ,

1. Do you have SSL enabled ?
2. "they delete" -> do you mean the product does not exist on the BO ? Or the info in that product is empty ? Could you attach a screen record please ?
3. For PS1.7.6.4, keep PHP version 7.2.

Thanks!

**Comment by florine2623** [comment] 2020-06-04 08:14
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by IranDec** [comment] 2020-06-04 16:56
@florine2623 
Hi
1) yes
2)  info in that product is empty like u don't fill that ever
3) yes my PHP ver is 7.2 thanks for your advice 

I'm so sorry but it most possible to get a screen record
but I will try if my customer accept my ask.

Thanks

**Comment by florine2623** [comment] 2020-06-25 09:23
Ok, for now I will close this issue. Feel free to open a new one with all the details.

**Closed as completed by florine2623** 2020-06-25 09:23 UTC
Labels: BO, Performance, No change required, 1.7.6.4
