### ISSUE TITLE
Wording issue in 1.7.6.5 (regression?)

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#19603] opened 2020-06-05 13:54 UTC
#### Describe the bug

I updated a shop In 1.7.6.5, and now, when I add a new product, the tag "Neuf" is added to the thumbnail. It should be "Nouveau", in French, like it was in 1.7.6.4 and previous versions

#### Expected behavior

In this case, in french, it should be "Nouveau", not "Neuf". The context is not good.

#### Steps to Reproduce

1. Add a new product in the catalogue
2. Enable it
3. Browse the website (category, or product page)
4. What the "Neuf" tag in French on the front office, see screenshot

**Screenshots**

![Selection_818](https://user-images.githubusercontent.com/4619685/83883888-6574f580-a744-11ea-92c4-a7a445389a3e.png)

#### Question
Is there a way to fix this manually, while this is fixed in the next version?

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by matks** [comment] 2020-06-05 13:56
Related to https://github.com/PrestaShop/PrestaShop/issues/17455

**Comment by ttoine** [comment] 2020-06-05 14:02
fixed manually with the translation system
![Selection_819](https://user-images.githubusercontent.com/4619685/83884969-fdbfaa00-a745-11ea-9277-8aabc65f5ba6.png)

**Comment by florine2623** [comment] 2020-06-05 14:47
Hi @ttoine ,
We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #17455
So, I close it.

**Comment by florine2623** [comment] 2020-06-05 14:47
Duplicate of #17455

**Closed as completed by florine2623** 2020-06-05 14:47 UTC
Labels: Duplicate
