### ISSUE TITLE
Http 500 error when removing product from cart from order page

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#18537] opened 2020-04-09 07:47 UTC
#### Steps to Reproduce

1. Place more than 1 product in cart
2. Go to checkout and enter guest details and fill in address
3. Go to Shipping Method section, then in sidebar delete 1 product from cart.
4. Go through checkout process again.
4. See error before you reach 'Shipping Method' section again.

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-04-09 09:04
Hi @nrcjea001 ,
I could not reproduce your issue with the provided information.
In theme classic there's no possibility of deleting one product from the cart while doing the checkout process.
Please check if the error comes from your theme and let me know.
Thanks!

**Comment by sarahdib** [comment] 2020-05-05 15:40
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 15:40 UTC
Labels: FO, Checkout, 1.7.6.2
