### ISSUE TITLE
EU taxes aren't working since 1.7.4

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#10734] opened 2018-09-27 09:34 UTC
**Describe the bug**

EU VAT doesn't work as expected since v1.7.4+ (also tested on 1.7.5)
It works fine if vatnumber module is enabled on version < 1.7.4

If you make an order using a Spanish customer, on a French shop and using VAT number, you'll have to pay taxes but you should not.
In the invoice, we have the exempt text, but taxes table & amount are displayed.

**To Reproduce**
1. Install a fresh 1.7.4 version
2. Set default location to France
3. Add Spain via Localization and enable the country
4. Create a customer account with a Spanish address, fill company name and VAT number
5. Make an order

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-09-27 10:06
Hi @prestamodule,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9928
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-27 10:06
Duplicate of #9928

**Closed as completed by khouloudbelguith** 2018-09-27 10:06 UTC
Labels: Duplicate
