### ISSUE TITLE
bug with product images with combinations in the new version

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#24415] opened 2021-05-09 20:46 UTC
#### Describe the bug

https://youtu.be/vJC36vfO0OM

#### Additional information

* PrestaShop version: 1.7.6.4  OK
* PrestaShop version: 1.7.7.3  NOK
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-05-10 02:48
Hello @alfonsolr09 

Despite our efforts, we were not able to reproduce your issue with the PrestaShop version 1.7.7.3. 
Check the attached screen record below:

https://www.awesomescreenshot.com/video/3680440?key=e2e96b67c591884f889d8acc58f110a9

It seems that your issue is not a PrestaShop core bug but most likely a module problem.
We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-10 02:48 UTC
Labels: Can't reproduce

**Comment by alfonsolr09** [comment] 2021-05-10 07:05
PrestaShop version: 1.7.6.4 OK
PrestaShop version: 1.7.7.3 NOK

@hibatallahAouadni
