### ISSUE TITLE
Problems with the search engine by reference (using dots)

### ISSUE THREAD

**Issue by NerDifades** [PrestaShop/PrestaShop#17208] opened 2020-01-16 12:07 UTC
**Describe the bug**
Hello, we find out that you cannot search in frontoffice by reference if the reference has points.
For example:
We have a product with this reference: MJ.700. When you look for this product using the reference in the frontoffice, the product it is not shown. Eventhough, if you look for "700" it does appear.
We try any combination in section "Search" of Prestashop but nothing seems to work.
Any idea?

![search-in-frontoffice](https://user-images.githubusercontent.com/59920184/72523798-de8cb280-3860-11ea-8b29-e559e6e43327.jpg)

**Additional information**
PrestaShop version: 1.6.7.2
PHP version: 7.2.26

**Comment by khouloudbelguith** [comment] 2020-01-16 12:36
Hi @NerDifades,

I did not manage to reproduce the issue with PS1.7.6.2.
I attached a screen record
https://drive.google.com/file/d/1St5PAenGKKyFbtznJ9LcfwhaneB5BhN5/view
In fact, this issue is fixed in the PS1.7.5.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/9353 as reported previously
http://forge.prestashop.com/browse/BOOM-4148

Thanks to check & feedback.

**Comment by NerDifades** [comment] 2020-01-17 07:18
Hi @khouloudbelguith,
Thanks for the help! So it could be the theme? We are using Warehouse.
Maybe the issue is that all our products has similar references (always starting with MJ.)? It could be due to the fact that in our products we also use MJ in the titles?
I'll send you our website so that you can see it: https://mjcorse.com/

Thanks again!

**Comment by khouloudbelguith** [comment] 2020-01-17 09:00
@NerDifades, As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks to check with them & feedback.

**Comment by khouloudbelguith** [comment] 2020-02-17 07:46
Hi @NerDifades,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-17 07:46 UTC
Labels: Bug, FO, Search, No change required, 1.7.6.2
