### ISSUE TITLE
Hi, I can't intall on 1.7.6.4 ! I tried to unzip and zip again but dosen't work! please hepl.

### ISSUE THREAD

**Issue by mangiaparole** [PrestaShop/PrestaShop#18668] opened 2020-04-16 12:43 UTC
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-04-16 12:45
Hi @mangiaparole,

You cannot install a custom module?
which is this module?

Thanks!

**Comment by mangiaparole** [comment] 2020-04-16 12:55
ps email alerets!


[image: photo]
Marco Limiti
at Caffè Letterario Mangiaparole | Mangi e Leggi di Edizioni Progetto
Cultura 2003 Srl
A  Via Manlio Capitolino 7/9 | 00181| Roma
P  +390697841027  <+390697841027>
E  info@mangiaparole.it  <info@mangiaparole.it>
W  www.mangiaparole.it  <http://www.mangiaparole.it>
Metro Furio Camillo
Partita iva 07832781004

<http://www.facebook.com/pages/Mangiaparole-Libreria-Caff%C3%A8-letterario/123955360971599?ref=bookmarks>
<http://twitter.com/Mangiaparole>
<http://www.youtube.com/channel/UCoLCiyV4OGk2fYhfKJD9KVQ>
<http://www.google.it/maps/place/Libreria+Mangiaparole+%7C+mangi+%7C+leggi+%7C+studi/@41.875558,12.526414,17z/data=!3m1!4b1!4m2!3m1!1s0x132f61f70ee79f61:0x8a842cc73c7c5f56>
<http://www.mangiaparole.it/feed>
<http://info@mangiaparole.it> Iscriviti alla Newsletter
<http://info@mangiaparole.it>

Il giorno gio 16 apr 2020 alle ore 14:46 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2020-04-16 13:00
@mangiaparole, did you tried to install this module from BO => Modules => Module Catalog page?
![image](https://user-images.githubusercontent.com/16067358/79459099-0e2f9000-7ff3-11ea-8784-e937d547bc7a.png)

Thanks!

**Comment by mangiaparole** [comment] 2020-04-16 13:15
I can't find!? :-(


[image: photo]
Marco Limiti
at Caffè Letterario Mangiaparole | Mangi e Leggi di Edizioni Progetto
Cultura 2003 Srl
A  Via Manlio Capitolino 7/9 | 00181| Roma
P  +390697841027  <+390697841027>
E  info@mangiaparole.it  <info@mangiaparole.it>
W  www.mangiaparole.it  <http://www.mangiaparole.it>
Metro Furio Camillo
Partita iva 07832781004

<http://www.facebook.com/pages/Mangiaparole-Libreria-Caff%C3%A8-letterario/123955360971599?ref=bookmarks>
<http://twitter.com/Mangiaparole>
<http://www.youtube.com/channel/UCoLCiyV4OGk2fYhfKJD9KVQ>
<http://www.google.it/maps/place/Libreria+Mangiaparole+%7C+mangi+%7C+leggi+%7C+studi/@41.875558,12.526414,17z/data=!3m1!4b1!4m2!3m1!1s0x132f61f70ee79f61:0x8a842cc73c7c5f56>
<http://www.mangiaparole.it/feed>
<http://info@mangiaparole.it> Iscriviti alla Newsletter
<http://info@mangiaparole.it>

Il giorno gio 16 apr 2020 alle ore 15:01 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2020-04-16 13:18
@mangiaparole, is it displayed in the BO => Modules => Module Manager page?

Thanks!

**Comment by mangiaparole** [comment] 2020-04-16 13:42
No... Don't see there and neither on website

In data 16 Aprile 2020 3:19:07 PM khouloudbelguith 
<notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2020-04-16 13:48
@mangiaparole, I did not manage to reproduce the issue with PS1.7.6.4.
Could you please try with module
[ps_emailalerts.zip](https://github.com/PrestaShop/PrestaShop/files/4487491/ps_emailalerts.zip)
https://github.com/PrestaShop/ps_emailalerts

Thanks!

**Comment by mangiaparole** [comment] 2020-04-16 14:08
THank you very much!!!!!


[image: photo]
Marco Limiti
at Caffè Letterario Mangiaparole | Mangi e Leggi di Edizioni Progetto
Cultura 2003 Srl
A  Via Manlio Capitolino 7/9 | 00181| Roma
P  +390697841027  <+390697841027>
E  info@mangiaparole.it  <info@mangiaparole.it>
W  www.mangiaparole.it  <http://www.mangiaparole.it>
Metro Furio Camillo
Partita iva 07832781004

<http://www.facebook.com/pages/Mangiaparole-Libreria-Caff%C3%A8-letterario/123955360971599?ref=bookmarks>
<http://twitter.com/Mangiaparole>
<http://www.youtube.com/channel/UCoLCiyV4OGk2fYhfKJD9KVQ>
<http://www.google.it/maps/place/Libreria+Mangiaparole+%7C+mangi+%7C+leggi+%7C+studi/@41.875558,12.526414,17z/data=!3m1!4b1!4m2!3m1!1s0x132f61f70ee79f61:0x8a842cc73c7c5f56>
<http://www.mangiaparole.it/feed>
<http://info@mangiaparole.it> Iscriviti alla Newsletter
<http://info@mangiaparole.it>

Il giorno gio 16 apr 2020 alle ore 15:48 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2020-04-16 14:15
@mangiaparole, issue fixed?

THanks!

**Comment by mangiaparole** [comment] 2020-04-16 14:24
yes with your version!!!

can i ask
 somethig else about prestashop installation?!?


[image: photo]
Marco Limiti
at Caffè Letterario Mangiaparole | Mangi e Leggi di Edizioni Progetto
Cultura 2003 Srl
A  Via Manlio Capitolino 7/9 | 00181| Roma
P  +390697841027  <+390697841027>
E  info@mangiaparole.it  <info@mangiaparole.it>
W  www.mangiaparole.it  <http://www.mangiaparole.it>
Metro Furio Camillo
Partita iva 07832781004

<http://www.facebook.com/pages/Mangiaparole-Libreria-Caff%C3%A8-letterario/123955360971599?ref=bookmarks>
<http://twitter.com/Mangiaparole>
<http://www.youtube.com/channel/UCoLCiyV4OGk2fYhfKJD9KVQ>
<http://www.google.it/maps/place/Libreria+Mangiaparole+%7C+mangi+%7C+leggi+%7C+studi/@41.875558,12.526414,17z/data=!3m1!4b1!4m2!3m1!1s0x132f61f70ee79f61:0x8a842cc73c7c5f56>
<http://www.mangiaparole.it/feed>
<http://info@mangiaparole.it> Iscriviti alla Newsletter
<http://info@mangiaparole.it>

Il giorno gio 16 apr 2020 alle ore 16:15 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2020-04-16 14:28
@mangiaparole, great!
Since it is fixed, I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-16 14:28 UTC
Labels: Bug, BO, No change required, 1.7.6.4, ps_emailalerts

**Comment by mangiaparole** [comment] 2020-04-16 14:33
can i ask somethig else about how can change url?!?


[image: photo]
Marco Limiti
at Caffè Letterario Mangiaparole | Mangi e Leggi di Edizioni Progetto
Cultura 2003 Srl
A  Via Manlio Capitolino 7/9 | 00181| Roma
P  +390697841027  <+390697841027>
E  info@mangiaparole.it  <info@mangiaparole.it>
W  www.mangiaparole.it  <http://www.mangiaparole.it>
Metro Furio Camillo
Partita iva 07832781004

<http://www.facebook.com/pages/Mangiaparole-Libreria-Caff%C3%A8-letterario/123955360971599?ref=bookmarks>
<http://twitter.com/Mangiaparole>
<http://www.youtube.com/channel/UCoLCiyV4OGk2fYhfKJD9KVQ>
<http://www.google.it/maps/place/Libreria+Mangiaparole+%7C+mangi+%7C+leggi+%7C+studi/@41.875558,12.526414,17z/data=!3m1!4b1!4m2!3m1!1s0x132f61f70ee79f61:0x8a842cc73c7c5f56>
<http://www.mangiaparole.it/feed>
<http://info@mangiaparole.it> Iscriviti alla Newsletter
<http://info@mangiaparole.it>

Il giorno gio 16 apr 2020 alle ore 16:28 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2020-04-16 14:41
@mangiaparole,

>can i ask somethig else about how can change url?!?

Which URL?
Thanks!

**Comment by mangiaparole** [comment] 2020-04-16 14:55
The problem is I have 2 version oh Prestashop (1.3 works on
www.progettocultura.it) and 1.7 that works on
https://www.progettocultura.it/presta_1978_/
now i want the 1.7 on https://www.progettocultura.it and i want cancell
1.3...

All day long i tried to do that... can you help me?!



[image: photo]
Marco Limiti
at Caffè Letterario Mangiaparole | Mangi e Leggi di Edizioni Progetto
Cultura 2003 Srl
A  Via Manlio Capitolino 7/9 | 00181| Roma
P  +390697841027  <+390697841027>
E  info@mangiaparole.it  <info@mangiaparole.it>
W  www.mangiaparole.it  <http://www.mangiaparole.it>
Metro Furio Camillo
Partita iva 07832781004

<http://www.facebook.com/pages/Mangiaparole-Libreria-Caff%C3%A8-letterario/123955360971599?ref=bookmarks>
<http://twitter.com/Mangiaparole>
<http://www.youtube.com/channel/UCoLCiyV4OGk2fYhfKJD9KVQ>
<http://www.google.it/maps/place/Libreria+Mangiaparole+%7C+mangi+%7C+leggi+%7C+studi/@41.875558,12.526414,17z/data=!3m1!4b1!4m2!3m1!1s0x132f61f70ee79f61:0x8a842cc73c7c5f56>
<http://www.mangiaparole.it/feed>
<http://info@mangiaparole.it> Iscriviti alla Newsletter
<http://info@mangiaparole.it>

Il giorno gio 16 apr 2020 alle ore 16:41 khouloudbelguith <
notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2020-04-16 14:58
@mangiaparole,

I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
