### ISSUE TITLE
Product fields ar overriden from default shop in multishop environment

### ISSUE THREAD

**Issue by webdnes** [PrestaShop/PrestaShop#35010] opened 2024-01-09 15:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Field values for individual shops are overriden by default shop in product admin when saving in All shops environment.
This bug  has some similarity of https://github.com/PrestaShop/PrestaShop/pull/33151/files

### Expected behavior

Keep shop specific values

### Steps to reproduce

1) install PS in multishop mode with total of three shops in the same group
2) Assign different currency and language to each shop
3) Switch off experimental product features
4) Choose "All shops". Create a new product, fill name, description, code and price. Save.
5) Switch the admin to the context of the first (default) shop. Save name, description for the language one. Save
6) Go to the second shop context. Switch language to language two.  Fill name and description for language two only. Recalculate and set price. Save.
7) Repeat with third shop and language three.
8) Return to the all shop context, change  description and save.
9) Check price for shop two and three. Check language fields for shops two and three and the coresponding languages.   

I was able to hot fix this for a very unhappy customer:  in AdminOrdersController::processUpdate after  if (Shop::isFeatureActive() && Shop::getContext() != Shop::CONTEXT_SHOP) 
by checking if the name is already stored in ps_product_lang for language one and conditionally unsetting some variables. But this is not a real remedy.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-01-11 10:00
Hello @webdnes ,

I can't reproduce your issue following your steps.

Each shop has its own language/currency.

<img width="1169" alt="Screenshot 2024-01-11 at 10 59 31" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/57f112be-f925-435f-a529-108ec6a8fb0e">
<img width="1151" alt="Screenshot 2024-01-11 at 10 59 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b02b4f98-a830-4b0d-b037-1a63f7f8cf4a">
<img width="1160" alt="Screenshot 2024-01-11 at 10 59 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3b406b73-8527-47ab-b0bb-a56e537b4f71">

I'm closing the issue as it cannot be reproduce and you fixed it on your end ^^

**Closed as completed by florine2623** 2024-01-11 10:00 UTC
Labels: Bug
