### ISSUE TITLE
Prestashop 1.7.3.2 slow on edit, duplicate or delete products

### ISSUE THREAD

**Issue by CesarNatic** [PrestaShop/PrestaShop#10789] opened 2018-10-01 09:42 UTC
Hi everyone:

I have a big issue with Prestashop 1.7.3.2, when i try to edit, duplicate or delete a product, it takes a lot of time to finish. I tried a lot of things i found on the web and sometimes seems like it fixed the issue but days laters the issue come back. See the attachment of the network inspector, the 302 redirect take like 2 minutes to complete. I dont know if its because prestashop is working with the database or because Prestashop cant find the place to redirect correctly. I tried to regenerate the .htaccess to see if its because the Rewrite mod or some kind of redirection, but when i disable the multishop and reactivate it, the .htaccess dosent regenerate.
With the debug mode On, when i duplicate a product it says that the request of duplicate takes like 1 or 2 seconds, but the process takes like 2 minutes. Sometime 10 seconds, sometime 20, sometimes a minute, two,.... Its really weird.

PD: Its a multishop, of two shops.
![captura](https://user-images.githubusercontent.com/43744410/46281087-f954ee00-c56d-11e8-8843-9ce20b7c3c80.PNG)

Any help is appreciated.
Thanks, César.

**Comment by khouloudbelguith** [comment] 2018-10-01 09:48
Hi @CesarNatic,

To regenerate the file .htaccess you need: 

1. Rename the old file to .htaccess_old
2. Disable friendly URL
3. Enable friendly URL

Thanks to check and feedback

Best regards, Khouloud

**Comment by CesarNatic** [comment] 2018-10-01 09:58
Done it and it regenerated the same .htaccess.

> 
> 
> Hi @CesarNatic,
> 
> To regenerate the file .htaccess you need:
> 
>     1. Rename the old file to .htaccess_old
> 
>     2. Disable friendly URL
> 
>     3. Enable friendly URL
> 
> 
> Thanks to check and feedback
> 
> Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 10:15
Hi @CesarNatic,

In general, your issue is related to Prestashop performance which is too slow to return the result.
We are aware of this issue and we are working on it.
Your ticket is a duplicate of #9809
This issue is in progress & it is assigned to our developer.
So, I close it. Please, follow #9809.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 10:15
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2018-10-01 10:15 UTC
Labels: BO, Duplicate
