### ISSUE TITLE
The big image Page will not opened after changing the color combination - Chrome v76

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15178] opened 2019-08-21 00:14 UTC
Hi
I've checked many times on some themes of prestashop 1.7.6
at first I thought it was due from an error of a theme bought on Addons, but I've seen it is present on all theme bought on Addons and also on the Classic theme of prestashop.

https://www.alikebikini.com/it/home/98-222-home-costume-intero-trikini-roses.html
this is the first theme that I found the error, because it is simple to see that the zoom stop to work.

at the first loading page all is ok, everything work well, but if you change the default selections, like to select a different color or size or quantity (from 1 to 2 to 3) you can see that the modal popup will not appear anymore (in this theme instead happen to the zoom)

it is due from the ajax solution used in prestashop 1.7, because only some parts are loaded after a selection is changed

this problem is present wit firefox, chrome and with safari there is a big problem the page go away from the product page (look at the video inside the zip file)

this is a very big bug, it should be fixed in the next version in 1.7.6.1 and alerted all theme developer to fix it

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/63393066-aa988880-c3b9-11e9-9f85-014e8cd7f06a.png)

[WhatsApp Video 2019-08-21 at 00.54.20.zip](https://github.com/PrestaShop/PrestaShop/files/3523041/WhatsApp.Video.2019-08-21.at.00.54.20.zip)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0

**Comment by Maofree** [comment] 2019-08-21 07:08
hi
this problem happens only for products with combinations, without them increasing the quantity the problem doesn't appear

**Comment by matks** [comment] 2019-08-21 08:18
@maofree thanks for the great and reliable feedback (as always !) 😉 , we're going to explore this fast

**Comment by Maofree** [comment] 2019-08-21 08:38
with these themes I don't reproduce this error
https://allarmiwireless.net/shop/kit-videosorveglianza-ahd/225-67-kit-videosorveglianza-ahd-4-canali-1080p-4-telecamere-2mpx-ir-30-mt.html

https://www.conquest.it/accessori-da-calcio/196-512-palo-slalom-con-puntale-in-acciaio-giallo-o-rosso.html

https://shop.natur.it/essenze-floreali/3486-206-aspen.html

instead with this one yes
https://www.todoparatucoche.com/lubricantes-online/aceite-ester/11252-510-aceite-de-ester-xenum-x1-5w50.html

if you look at the change the image has a little flash because the content of the image is reloaded and  its code is changed

**Comment by khouloudbelguith** [comment] 2019-08-21 08:51
Hi @maofree,

I tried with PS1.7.6.0 & the default theme classic & it is OK
I attached a sreen record
https://drive.google.com/file/d/1braJLZ4eDChE694no5nxozmdlre1xikU/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-08-21 09:00
@maofree, I checked with the Luxury theme & it is OK
https://drive.google.com/file/d/1L1OvGFHIo4BOPOJsq4dKXeXL9uk0vCa1/view
Thanks!

**Comment by Maofree** [comment] 2019-08-21 09:09
Hi
the problem is not on the add to cart button but on the main product image
try to select a combination then push on the main image

**Comment by khouloudbelguith** [comment] 2019-08-21 09:22
@maofree, thanks for your feedback.
I followed these etps & it is OK
https://drive.google.com/file/d/1G8tqO6r8373jzzoMEcU7Y-Ms5ePDZCKo/view
Thanks to check & feedback.

**Comment by Maofree** [comment] 2019-08-21 09:38
Hi
now on the classic theme all seems ok (it is so strange, probably it was due from internet)
but I've found an error :)
https://drive.google.com/file/d/1eMqLk09Vf7MXTFQyy1kzzHAwuGpN-yXH

if you change something like the quantity, some content will be changed, then go fast to push on the main image, then the modal will be shown but the product image will be removed, look at the image

**Comment by Maofree** [comment] 2019-08-21 09:43
the problem that I have with the other theme is the same
https://www.todoparatucoche.com/lubricantes-online/aceite-ester/11252-509-aceite-de-ester-xenum-x1-5w50.html

after to have changed the attribute, I need to wait some seconds to get the possibility to push on the main image and see the modal popup. So the problem is this latency that can be present when the internet connection is not good or if the image has a big size or ram problems on the client pc or from the server

**Comment by Maofree** [comment] 2019-08-21 09:48
in fact now I'm uploading a 10GB file so the connection is slow in upload and it shows me these critical issues

**Comment by khouloudbelguith** [comment] 2019-08-21 09:50
@maofree,

>if you change something like the quantity, some content will be changed, then go fast to push on the main image, then the modal will be shown but the product image will be removed, look at the image

About this issue, I manage to reproduce it with PS1.7.6.0 & PS1.7.5.2.
https://drive.google.com/file/d/1XhTRhhQOc_Q_-XX-iBk8NLtSihHwCmQZ/view
Issue created here: https://github.com/PrestaShop/PrestaShop/issues/15181
It seems to be related to this https://github.com/PrestaShop/PrestaShop/issues/9634

**Comment by Maofree** [comment] 2019-08-21 09:56
hi
I think it is different because it is due from a latency necessary between the current image and the next image of the different combination

a part of problem can be solved removing the change of the image when the quantity are changed, it should change only the prices. But if you change the combination the current image is joined on the previuos combination, it is necessary only to change the image or try with another solution

**Comment by khouloudbelguith** [comment] 2019-08-21 10:01
@maofree, I tried in my case to click on the main image before other images are loaded & it is OK, the page is not frozen.
https://drive.google.com/file/d/1DBp3PQc1m99pS4z7jvvtw3XQfCrjqrvW/view
Thanks!

**Comment by Maofree** [comment] 2019-08-21 10:09
chane the quantity give also these problem on the productcomments vers. 4.0
![1](https://user-images.githubusercontent.com/653230/63423374-726e6580-c40c-11e9-915f-5a7b1d443569.png)
![2](https://user-images.githubusercontent.com/653230/63423376-7306fc00-c40c-11e9-9e97-c2fe3e9ec8f1.png)

**Comment by khouloudbelguith** [comment] 2019-08-21 10:31
@maofree, seems to be ok in y side
https://drive.google.com/file/d/1BuJqlo6PI-h8Ksh4BKwlnru_5FBrUdfj/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-21 10:36
@maofree, thanks for your feedback.
I have the same issue with PS1.7.6.0 & productcomments v4.0.0.
https://drive.google.com/file/d/1IcvdCrilAxegvFNL4SSNeA7_qv0M0nRE/view
But it seems different from your first issue.
@maofree, the issue created here: https://github.com/PrestaShop/PrestaShop/issues/15184
Thanks!

**Comment by Maofree** [comment] 2019-08-21 10:50
I think it is due from some hook, in some part of the product page the data is refreshed when something is changed like quantity in other parts this not happen

**Comment by khouloudbelguith** [comment] 2019-08-21 11:03
@maofree, thanks for these clarifications.
The Productscomment issue is different fro your first issue (main image issue), That's why I created a new ticket.

Thanks!

**Comment by Maofree** [comment] 2019-08-21 12:28
Hi
found the error in the classic theme give me some minutes to make the video, it is on the color selection

**Comment by khouloudbelguith** [comment] 2019-08-21 12:29
@maofree, waiting for your feedback.

Thanks!

**Comment by Maofree** [comment] 2019-08-21 12:42
on the select like for size the problem is not present as you report on some videos,
now after many tests I've seen that it is due on the color selection

https://drive.google.com/file/d/1lQLh1MejRGnK1MlWi7gLGGHdR9EDmD_s/view

select the second color and you will see that the big immage will not opened (I think because the box of the image is reloaded in ajax mode and the javascript of the modal popup is not updated to check it). Also the zoom icon is not shown over the image

**Comment by Maofree** [comment] 2019-08-21 12:51
in another theme with products with many colors the behavior is even stranger, if I push on the second color the modal doesn't work, if I push again on the first color and then return on the second the modal will work, but not always, the same for the rest of colors

**Comment by khouloudbelguith** [comment] 2019-08-21 13:10
@maofree, I tried with PS1.7.6.0 & the theme classic & it is OK
https://drive.google.com/file/d/1rUxvGCZEyBVoEg1RQ45sWIEODi0ZKHni/view

Thanks!

**Comment by Maofree** [comment] 2019-08-21 13:12
I'll try from other pc and S.O.
I get this problem from linux with chrome, I'll check better

**Comment by khouloudbelguith** [comment] 2019-08-21 13:15
@maofree, thanks!

Waiting for your feedback.

**Comment by Maofree** [comment] 2019-08-21 15:46
from windows all is ok
instead from linux I continue to have this problem even in incognito mode of chrome
from firefox on linux all is ok

so the problem is only on linux with chrome

**Comment by khouloudbelguith** [comment] 2019-08-21 16:21
@maofree, my server information is Server information Linux #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 => OK
https://drive.google.com/file/d/1rt75W5CGTls1wafA0J5y7qluPwRpPEBF/view

Thanks!

**Comment by Maofree** [comment] 2019-08-21 16:24
I use arch linux on my pc
the server sure normally is on linux debian or centos
I spoke of my pc the client

**Comment by khouloudbelguith** [comment] 2019-08-23 09:42
@maofree, could you please provide me the exact information of the server that you manage to reproduce the issue.
You can check it in your BO => Advanced Parameters => Information page.

Thanks!

**Comment by Maofree** [comment] 2019-08-23 09:45
hi
the problem is in the front-office so the server is not important
try to use in your pc Ubuntu or others linux (I'm using Arch Linux) client with chromium
if all is ok from windows and with firefox the problem is not in the server

![1](https://user-images.githubusercontent.com/653230/63583558-88f6f700-c59b-11e9-92c7-0e1459cac569.png)

**Comment by khouloudbelguith** [comment] 2019-08-23 10:21
@maofree, what is the exact version of the chrome did you use?
I think it is related to the chrome version & not the "Arch Linux".
I tried with the chrome browser Version 71.0.3578.98 (Build officiel) (64 bits) => OK
I tried with Chrome Version 76.0.3809.87 (Official Build) (64-bit) => NOK
https://drive.google.com/file/d/1AA8RsmmobSVH2rra2PO-_8etxDEoGDUH/view
Thanks to check & feedback.

**Comment by Maofree** [comment] 2019-08-23 10:22
my version is
76.0.3809.100 (Build ufficiale) Arch Linux (a 64 bit)
on linux there is Chromium is the open source version of chrome

you are using chrome from the mac

![1](https://user-images.githubusercontent.com/653230/63586079-d45fd400-c5a0-11e9-8e87-c41653648364.png)

**Comment by Maofree** [comment] 2019-08-23 10:26
so at this moment there is the same error on mac and linux systems with chrome and chromium

**Comment by khouloudbelguith** [comment] 2019-08-23 10:41
@maofree, I manage to reproduce the issue with PS1.7.5.1 & PS1.7.6.0 & Windows10 & browser_version=76.0https://drive.google.com/file/d/1ceFY9G_kELoijYKAF8N2oFK3ybZ4k2tR/view
PS: I can't click on the product image only at the first time
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by NeOMakinG** [comment] 2020-01-06 09:31
@khouloudbelguith do you manage to reproduce this now ? It looks like someone fixed it without seeing the issue, can't reproduce it at all

**Comment by khouloudbelguith** [comment] 2020-01-06 09:51
Hi @NeOMakinG,

Yes!
I did not manage to reproduce the issue with PS1.7.6.2 & Chrome browser version 76.0.3809.87 (Official Build) (64-bit)
https://drive.google.com/file/d/1MmPY3XusprksZGeUQl7P_uyGIu09YyjQ/view
@maofree, I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-06 09:51 UTC
Labels: Bug, Trivial, FO, Combinations, Fixed, 1.7.5.1, 1.7.6.0
