### ISSUE TITLE
Prestashop AutoUpgrade 4.11.0 SQL Error on Upgrading 1.7.5.1 to 1.7.7.1

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#23145] opened 2021-02-04 18:58 UTC
Hi,

I try to upgrade my store (version 1.7.5.1 to 1.7.7.1) with the AutoUpgrade 1-Click Module (v4.11.0) latest version and during th installation is ended with a SQL error.

    SQL 1.7.7.0 1071 in ALTER TABLE `ps_shop_url` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Specified key was too long; max key length is 1000 byte

Does we need to made the change manually or the store will still work with this error.

Thanks,

**Comment by florine2623** [comment] 2021-02-05 09:08
Hello @8ternity ,
Your issue is a duplicate of #21948.
It has been fixed by #21975.

So I'll close your issue.
Thanks!

**Closed as completed by florine2623** 2021-02-05 09:08 UTC
Labels: Duplicate, Autoupgrade

**Comment by hibatallahAouadni** [comment] 2021-02-05 19:32
Duplicate of #21948
