### ISSUE TITLE
Error: Translations not found in/webspace/siteapps/Prestashop.../var/cache/dev/translations

### ISSUE THREAD

**Issue by Arnaldo405** [PrestaShop/PrestaShop#14787] opened 2019-07-19 21:58 UTC
Hi,

Unfortunately I had to start with a clean install, so I did and updated the clean install version 1.7.4.2 to version 1.7.5.2 and added the German language. According to the back office Dutch as well as English were already available. 
When I wanted to translate German in International - Theme Classic - German I was not able to open the translation area. When I compare the backup of my previous store (which I had to delete) I see that in ..../var/cache/dev/translations only the files of the Dutch translation are available. English and German are not, In my previous shop they were present. In Symphony I receive the message that Translations are not found. 

I already updated the languages, which didn.t help. However I can enter the German language now. Also I cleared the cache in hard compilation. But translations are not visible in the front office. 

Do I have to install manually the translation files of English and German? Can I use the files of my previous shop (PrestaShop 1.7.4.4)? Or is another solution necessary? 

Please advice! Thanks in advance!

 
**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-07-22 08:30
Hi @Arnaldo405,

Thanks for your report.
Have you the same issue with this ticket: #14733?
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-07-22 08:32
Hi @Arnaldo405,

1. Go to International > Translations > Export a language and select a language.
![image](https://user-images.githubusercontent.com/16067358/61457800-00b08100-a961-11e9-9742-f1a95a9d5d28.png)


2. This will generate a file like “ShopMytheme.fr-FR.xlf” if you’ve chosen French, for example.
3. Copy the file into the translation file of your theme
If necessary, create a folder for the language.
![image](https://user-images.githubusercontent.com/16067358/61457844-1a51c880-a961-11e9-9485-e7585848befb.png)

Thanks to check & feedback.

**Comment by Arnaldo405** [comment] 2019-07-22 20:22
Hello miss @khouloudbelguith,

Thank you for your response.
I did install the languages directly after the clean install. Because I see issues in the front office I updated them. I think the problem is that they are not installed in the database, as you can see in the screenshot of Filezilla. In another screenshot you can see that I have the languages installed in PrestaShop and also that they are not visible in the front office. 
Does it solve the problem when they are installed in the database? And can I use the ones I have in a backup I made of the shop I had in PrestaShop 1.7.4.4, which I had to delete to do the clean install? 

Thanks for your advice.
![Filezilla - screenshot var cache dev translations](https://user-images.githubusercontent.com/53099784/61662695-3641cb00-accf-11e9-92e0-c02761b3e1d2.png)
![Front office not translated, present in back office](https://user-images.githubusercontent.com/53099784/61662696-3641cb00-accf-11e9-9656-c66206efc1db.png)
![Languages installed in Prestashop](https://user-images.githubusercontent.com/53099784/61662697-3641cb00-accf-11e9-82e0-c92a2af4e930.png)

**Comment by khouloudbelguith** [comment] 2019-07-23 10:59
Hi @Arnaldo405,

I tried with PS1.7.5.2 after upgrade from PS1.7.4.4 using the 1-click upgrade v4.9.0. & it is OK.
I tried to translate the classic theme in a Deutch language & it is OK.
I attached a screen record
[AwesomeScreenshot-2019-07-23T10-56-30-324Z.zip](https://github.com/PrestaShop/PrestaShop/files/3421681/AwesomeScreenshot-2019-07-23T10-56-30-324Z.zip)
Thanks to check & feedback.

**Comment by Arnaldo405** [comment] 2019-07-23 15:29
Hi @khouloudbelguith 

Thanks for your reply.

Besides all the other things I tried, I had already updated the version of 1-Clickupgrade, as you can see in the screenshot. 
Also I attached some screenshots of errors I received.
Can there be the solution of the problem?
Thanks in advance
![1_clickupgrade](https://user-images.githubusercontent.com/53099784/61725120-78224e00-ad6f-11e9-90e2-744255a8ad15.png)
![2019-07-20 Merken](https://user-images.githubusercontent.com/53099784/61725121-78224e00-ad6f-11e9-9209-a61c12a7f26f.png)
![error](https://user-images.githubusercontent.com/53099784/61725122-78224e00-ad6f-11e9-9506-a426529e29c7.png)
![error_2](https://user-images.githubusercontent.com/53099784/61725123-78bae480-ad6f-11e9-8bb9-e9aa96eb6c6d.png)

**Comment by khouloudbelguith** [comment] 2019-07-23 15:43
@Arnaldo405, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Also, you have permission denied on your server, you need to change the permission.

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 07:53
Hi @khouloudbelguith 
Thank you again.
I deleted the data in the cache (dev and prod). This does not solve the issue with the translations.

Attached you will find the file where I have to set permission. Can you please tell me where I need to change something and what it needs to become?
Thanks! 
[premission denied.txt](https://github.com/PrestaShop/PrestaShop/files/3425610/premission.denied.txt)

**Comment by khouloudbelguith** [comment] 2019-07-24 08:13
@Arnaldo405, you have some permissions denied as you can see in your screenshot.
![image](https://user-images.githubusercontent.com/16067358/61776583-3cc96300-adf3-11e9-8286-4b0717e5d455.png)

You need to check the permission issue with your host.

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 09:10
Hi @khouloudbelguith 

Thank you. I will do that!

Have you any other idea how to solve the translation issue? In the debug tool I also receive messages that the translations are not found. 

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-24 09:13
@Arnaldo405, try to copy the translations folder in your var/cache from your back up in your new Projet(after the upgrade) & check if you have the same issue.

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 09:25
@khouloudbelguith 
Do you mean the translation folder in the cache of my back up I made of my prestashop 1.7.4.4 or the back up of the var I just made? 
Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 09:29
@khouloudbelguith 
About the error you told me to contact my host. He checked and says that all permissions are on max. Do I need to ignore the message then?

**Comment by khouloudbelguith** [comment] 2019-07-24 09:39
@Arnaldo405, 
>Do I need to ignore the message then?

This red alert & it is displayed only if debug mode is enabled in your case.
>Do you mean the translation folder in the cache of my back up I made of my Prestashop 1.7.4.4 or the back up of the var I just made?

About the translation folder in the cache.

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 09:50
@khouloudbelguith 
It didn't work.
Also hereby a screenshot of Debug. Does this help?
[Translations not found errors in Debug.docx](https://github.com/PrestaShop/PrestaShop/files/3426085/Translations.not.found.errors.in.Debug.docx)

**Comment by khouloudbelguith** [comment] 2019-07-24 12:12
@Arnaldo405, no.
They are just warnings.

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 12:19
@khouloudbelguith 
Can you think of another solution? 
Would it be an idea to upgrade to 1.7.6? Would that solve the problem?
Thank you!

**Comment by khouloudbelguith** [comment] 2019-07-24 12:27
@Arnaldo405, did you use a custom theme or only the classic theme?

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 12:33
@khouloudbelguith 
I only use the classic theme at the moment. After installing the clean install + upgrade to 1.7.5.2 I first started to import the products and combinations (of course before the product import I imported the languages, created the categories, brands, combinations).
Thank you.

**Comment by khouloudbelguith** [comment] 2019-07-24 12:39
@Arnaldo405, thanks!
Because, with PS1.7.6.0, with other them, we have an issue with translation of the back office only.
Here's the exact issue: https://github.com/PrestaShop/PrestaShop/issues/14733, it should be fixed in a few days.

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 13:38
@khouloudbelguith 
Thank you. I shall follow issue #14733.

**Comment by khouloudbelguith** [comment] 2019-07-24 13:46
@Arnaldo405, thanks!
Can I close this issue?

Thanks!

**Comment by Arnaldo405** [comment] 2019-07-24 13:56
@khouloudbelguith 
Yes please. I shall follow the other issue and hopefully the solution will solve my problem. 
Thank you for your time and efforts.

**Comment by khouloudbelguith** [comment] 2019-07-24 14:21
@Arnaldo405, thanks!

**Closed as completed** 2019-07-24 14:22 UTC
Labels: Bug, BO, Duplicate, Translations, 1.7.5.2

**Comment by Arnaldo405** [comment] 2019-08-02 20:43
@khouloudbelguith 
Just a minute ago I wrote you under another issue. 
I solved the problem by deleting the var cache dev and prod. 
The 500 server error has gone and I can access my back office again. 
My apologies for bothering you.

**Comment by khouloudbelguith** [comment] 2020-10-08 09:45
Duplicate of #14733
