### ISSUE TITLE
clear cache - error 500

### ISSUE THREAD

**Issue by mangi-1** [PrestaShop/PrestaShop#22608] opened 2020-12-28 13:59 UTC
#### Screenshot
`[Mon Dec 28 15:49:35.798341 2020] [proxy_fcgi:error] [pid 1189:tid 140555607021312] [client 81.31.144.188:54705] AH01071: Got error 'PHP message: PHP Warning:  require(/home/xxxx/domains/xxxx/public_html/var/cache/prod/ContainerYsnrn19/getAnnotations_CacheService.php): failed to open stream: No such file or directory in /home/xxxx/domains/xxxx/public_html/var/cache/prod/ContainerYsnrn19/appProdProjectContainer.php on line 1649\nPHP message: PHP Warning:  require(/home/xxxx/domains/xxxx/public_html/var/cache/prod/ContainerYsnrn19/getAnnotations_CacheService.php): failed to open stream: No such file or directory in /home/xxxx/domains/xxxx/public_html/var/cache/prod/ContainerYsnrn19/appProdProjectContainer.php on line 1649\nPHP message: PHP Fatal error:  require(): Failed opening required '/home/xxxx/domains/xxxx/public_html/var/cache/prod/ContainerYsnrn19/getAnnotations_CacheService.php' (include_path='/home/xxxx/domains/xxxx/public_html/vendor/pear/pear_exception:/home/xxxx/domains/xxxx/public_html/vendor/pear/console_getopt:/home/xxxx/domains/xxxx/public_html/vendor/pear/pear-core-minimal/src:/home/xxxx/domains/xxxx/public_html/vendor/pear/archive_tar:.:/usr/local/php72/lib/php') in /home/xxxx/domains/xxxx/public_html/var/cache/prod/ContainerYsnrn19/appProdProjectContainer.php on line 1649\n', referer: https://xxxx/admin745rihjmq/index.php/configure/advanced/performance/?_token=7b8ZMteoqvQZT_8yrPZLlEllDGkGXkwLbpbsxB3LplI`

#### Additional informations

- Prestashop version: 1.7.6.5
- PHP version: 7.2.34

Any idea?

**Comment by hibatallahAouadni** [comment] 2020-12-28 16:19
Hello @mangi-1 

Could you please provide steps to reproduce the issue.
And please **follow the template to submit a complete bug report**.

PS: could please check your access rights on the Cache folder, cause it seems you have not the right to access/write/read on the folder 

Thanks!

**Comment by aded** [comment] 2021-01-12 11:56
Similar problem here, after clearing cache via-backoffice:

```
PHP Fatal error:  require(): Failed opening required '/var/www/html/var/cache/prod/ContainerDss2r3s/removed-ids.php' (include_path='/var/www/html/vendor/pear/pear_exception:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/archive_tar:.:/usr/local/lib/php') in /var/www/html/var/cache/prod/ContainerDss2r3s/appProdProjectContainer.php on line 1627
```

As suggested elsewhere (for example [here](https://www.prestashop.com/forums/topic/956372-white-page-in-prestashop/)), I had to rename ```var/cache``` folder.

**Comment by hibatallahAouadni** [comment] 2021-01-17 20:15
Hello @mangi-1 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: @aded glad to know that you solved your pb :tada: but you should check your access rights on the Cache folder too :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-17 20:15 UTC
Labels: Bug, CO, No change required, 1.7.6.5

**Comment by aded** [comment] 2021-01-20 11:08
@hibatallahAouadni thanks for your reply. Dir permissions/rights are ok on all PS folder/subfolders. :wink:
