### ISSUE TITLE
It's not possible to write in the following folders: var/cache

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#32468] opened 2023-05-06 11:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
When attempting a 1-click upgrade, it won't continue, saying it can't, It's not possible to write in the following folders
var/cache
 folder has the correct permissions. 755

![Screenshot 2023-05-06 123307](https://user-images.githubusercontent.com/11594433/236621570-5d3a58ed-c97c-4ba4-800d-560c9d9bc78f.png)

info_outline Server information
Server information: Linux #1 SMP Mon Feb 27 14:44:55 UTC 2023 x86_64
Server software version: LiteSpeed
PHP version: 7.4.33
Memory limit: 1G
Max execution time: 6360
Upload Max File size: 128M

PrestaShop version: 1.7.8.8

Check your configuration
Required parameters: Please fix the following error(s)
Set write permissions for the "cache" folder.
Optional parameters: OK

### Expected behavior

Upgrade the PS frrom 1.7.8.8 to 1.7.8.9

### Steps to reproduce

go to upgrade module

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by kpodemski** [comment] 2023-05-06 19:42
Hello @go-sudo 

Have you tried to change the permissions recursively for this directory?

**Comment by go-sudo** [comment] 2023-05-07 00:02
Hello @kpodemski 
I tried once to chmod the directory from 755 to 777, but idem
Regards

**Comment by hibatallahAouadni** [comment] 2023-05-09 06:37
Hello @go-sudo 

I didn't manage to reproduce the issue, I just change the permissions of cache directory to 777 and it works.
Could you please check that you gave the permissions to the right directory under the project that you work on it 😅 
Cause sometimes I mixed up with projects 😅 
Waiting for your feedback.

Thanks!

**Comment by go-sudo** [comment] 2023-05-09 11:36
Hello @hibatallahAouadni

I have one project on this server 
![image](https://github.com/PrestaShop/PrestaShop/assets/11594433/ba4d78c6-e3a0-4be4-a98f-01126cff5af9)

![image](https://github.com/PrestaShop/PrestaShop/assets/11594433/29e56ecd-ffd3-4729-9935-ca9e6a62de0c)

**Comment by florine2623** [comment] 2023-05-09 14:40
Hello @go-sudo ,

I can't reproduce your issue with PS 1.7.8.8 and configuration following https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/.
<img width="1177" alt="Screenshot 2023-05-09 at 16 40 32" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/69873125-f5ca-4bf8-890d-14fa7bb65cd8">


Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2023-05-09 14:40 UTC
Labels: Bug, BO, Autoupgrade, Module, 1.7.8.7

**Comment by go-sudo** [comment] 2023-05-09 14:45
Hi @florine2623 
My server config is ok
![image](https://github.com/PrestaShop/PrestaShop/assets/11594433/aff65773-4ae0-415b-81d0-86181445367a)
