### ISSUE TITLE
Autoupgrade might re-download all native modules although useless

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17496] opened 2020-02-04 14:51 UTC
**Describe the bug**
According to @jocel1, it seems autoupgrade module re-download all native modules although useless. Autoupgrade module should only download new module versions.

**To Reproduce**
1. Install a 1.7.6.1 shop
2. Check that, in modules folder, the following modules do not have a `vendor/composer` folder:
- ps_customersignin
- pagesnotfound
- statsforecast
3. Upgrade to 1.7.6.2
4. Check that, in modules folder, the following modules **now have** a `vendor/composer` folder:
- ps_customersignin
- pagesnotfound
- statsforecast

Can you confirm @jocel1 ?

**Comment by jocel1** [comment] 2020-02-04 14:54
Yes that's it :)
I'll double check by installing again a shop from scratch, just in case

**Comment by matks** [comment] 2020-02-04 14:58
> I'll double check by installing again a shop from scratch, just in case

If you find ClassLoader in modules folder after an install, we have a very serious issue 😅

**Comment by khouloudbelguith** [comment] 2020-02-04 15:24
Hi @matks, @jocel1,

I have the same issue with PS1.7.6.3 after an upgrade from PS1.7.6.1 using the 1-click upgrade v4.10.1.
https://drive.google.com/file/d/1TgRMmzJbTaHDzYlhdvw67qtref_Kke8b/view
I’ll add this to the debug roadmap.

Do you think, it is a major issue or minor?

Thanks!

**Comment by eternoendless** [comment] 2021-02-12 15:45
There's some thinking needed to account for the following cases:

- If the module version included with the core is higher than the one installed before the upgrade, then logically the module upgrade process should be triggered in order to ensure that the module is properly upgraded (this might already be the case).
- If the module version included with the core is LOWER than the one installed before the upgrade, then the module should be left untouched (and certainly not downgraded!)
- Modules pushed by API (GDPR, MBO...) should be installed during this process automatically, unless uninstalled previously. This would require storing which modules have been uninstalled so that they are not reinstalled during the update. Now that I think of it, this should be honored for native modules as well.

**Comment by hibatallahAouadni** [comment] 2021-03-25 16:28
This issue still persist with PS1.7.7.3_build1

**Comment by MatShir** [comment] 2021-08-09 12:36
@marionf @prestascott It is a use case that you should include in the module refacto.

**Comment by marionf** [comment] 2021-08-18 16:41
Duplicate of #14784

**Closed as completed by marionf** 2021-08-18 16:41 UTC
Labels: Bug, Minor, Duplicate, Modules, Autoupgrade, 1.7.6.3, 1.7.7.2
