### ISSUE TITLE
Social media share buttons v2.1.2 - by PrestaShop not showing Product images when shared to Facebook

### ISSUE THREAD

**Issue by dwayned46** [PrestaShop/PrestaShop#32171] opened 2023-04-14 16:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I go to a product page and click on the Facebook Icon to share to a Facebook Page, the image does not show. The description shows, but not the image. 

### Expected behavior

I expect the image details and image to show when share to Social Media as other share software does.

### Steps to reproduce

![Prestashop_Social_Media_ShareCapture](https://user-images.githubusercontent.com/565362/232108540-c5fada0b-9059-4a27-af61-8dea83cedb08.JPG)
![ShareButtonNotShowingImageCapture](https://user-images.githubusercontent.com/565362/232108542-71533e62-2131-4e86-9b10-dd5dd8321cdf.JPG)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Social media share buttons v2.1.2 - by PrestaShop

**Comment by hibatallahAouadni** [comment] 2023-04-18 08:44
Hello @dwayned46 

I didn't manage to reproduce the issue with the provided info, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/232723204-07549554-8364-4dda-b2d4-faa93fd317b8.png)

Please check and feedback.

Thanks!

**Comment by florine2623** [comment] 2023-05-03 08:50
Hello @dwayned46 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-05-03 08:50 UTC
Labels: Bug, FO, Socialsharing, Invalid, Module, 1.7.8.7
