### ISSUE TITLE
webservice add order do not call 'actionUpdateQuantity' 

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#13395] opened 2019-04-13 21:41 UTC
**Describe the bug**
When I do order with webservice, quantities of products are not updated

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

I think it was ok on 1.7.5.0, because, I've done a lot of tests.
I just see my stock do not decrease with webservice orders.

**Comment by khouloudbelguith** [comment] 2019-04-15 10:29
Hi @pppplus,

Could you please provide me your script to test with it.

Thanks!

**Comment by pppplus** [comment] 2019-04-15 21:02
Hi, yes it's possible.
But difficult to use for you I think, because the script is only for me.

Is it possible to send it privatly ?

**Comment by khouloudbelguith** [comment] 2019-04-16 09:54
Hi @pppplus,

My address mail: khouloud-belguith.ext@prestashop.com

Thanks!

**Comment by pppplus** [comment] 2019-04-17 08:59
Ok, I prepare the files, and send them in a few minutes.
Thanks

**Comment by khouloudbelguith** [comment] 2019-04-17 14:53
Hi @pppplus,

Thank you, we received your e-mail.
We will try to reproduce it and we will come back to you if we need more information.

**Comment by khouloudbelguith** [comment] 2019-04-18 15:26
Hi @pppplus,

When I tried with your file, I have these errors.
```
</ul><br/>TEST idPayment <br/>PHP Notice:  Undefined variable: public_key in /projet/php5/presta_test/1751/testMWSamazon.php on line 242
PHP Stack trace:
PHP   1. {main}() /projet/php5/presta_test/1751/testMWSamazon.php:0
PHP Notice:  Undefined variable: private_key in /projet/php5/presta_test/1751/testMWSamazon.php on line 242
PHP Stack trace:
PHP   1. {main}() /projet/php5/presta_test/1751/testMWSamazon.php:0
https://mws.amazonservices.fr/Orders/2013-09-01?AWSAccessKeyId=&Action=ListOrderItems&AmazonOrderId=408-4137542-8205953&SellerId=A3L7R8BEGV2OZE&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2019-04-18T15%3A23%3A20Z&Version=2013-09-01&Signature=U6GQLm5835W6DDpGKL%2BP11hGqUeWlKCk2YKnmVh351c%3DPHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /projet/php5/presta_test/1751/testMWSamazon.php:246
Stack trace:
#0 /projet/php5/presta_test/1751/testMWSamazon.php(246): SimpleXMLElement->__construct('')
#1 {main}
  thrown in /projet/php5/presta_test/1751/testMWSamazon.php on line 246
```
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-04-22 17:11
Hi @pppplus,

Now, I have this error 
```
</ul><br/>TEST idPayment <br/>PHP Warning:  Invalid argument supplied for foreach() in /projet/php5/presta_test/1751/testMWSamazon.php on line 336
PHP Stack trace:
PHP   1. {main}() /projet/php5/presta_test/1751/testMWSamazon.php:0
Panier VIDE, on sort de la boucle.<br/><hr/><br/><h2>Récapitulatif</h2><h3>ID produit Prestashop</h3><h3>Sku INVALIDES</h3>
```

I think because you use in your script you use `Amazon`, in my case no.
Thanks to check & feedback

**Comment by pppplus** [comment] 2019-04-27 19:14
Hi @khouloudbelguith 
Do you receive my last version, and do you reproduce the problem ?
I urgently need a solution now... my stock are not updated, and it's very hard to work !!

**Comment by khouloudbelguith** [comment] 2019-04-29 14:24
Hi @pppplus,

Yes, I just received your last version, but as I said, I have a new errors with your script.
```
</ul><br/>TEST idPayment <br/>PHP Warning:  Invalid argument supplied for foreach() in /projet/php5/presta_test/1751/testMWSamazon.php on line 336
PHP Stack trace:
PHP   1. {main}() /projet/php5/presta_test/1751/testMWSamazon.php:0
Panier VIDE, on sort de la boucle.<br/><hr/><br/><h2>Récapitulatif</h2><h3>ID produit Prestashop</h3><h3>Sku INVALIDES</h3>
```

Thanks to check & feedback.

**Comment by pppplus** [comment] 2019-04-29 14:47
Hi
That's not possible.
I check my script on a new website to be sure.
Do you create Products, as I describe in my email ?

**Comment by khouloudbelguith** [comment] 2019-04-29 15:12
@pppplus, Yes, I created the two products with the references described & after runing your file, I have
errors
![image](https://user-images.githubusercontent.com/16067358/56905763-22f0dc00-6aa1-11e9-9e06-aae58373ccc8.png)

```
lue in \AmazonSeller\testMWSamazon.php on li
ne 334

Warning: Creating default object from empty value in \AmazonSeller\testMWSamazon.php on line 334
PHP Warning:  Invalid argument supplied for foreach() in \AmazonSeller\testMWSamazon.php on line 336

Warning: Invalid argument supplied for foreach() in \AmazonSeller\testMWSamazon.php on line 336
Panier VIDE, on sort de la boucle.<br/><hr/><br/><ul>
            <li>BuyerEmail = xxx7z47dnmxrql7@marketplace.amazon.fr</li>
            <li>AmazonOrderId = 405-7456972-0653950</li>
            <li>SalesChannel = Amazon.fr</li>
            <li>BuyerName = GUERTHON</li>
            <li>OrderTotal = 10.99EUR</li>
            <li>ShippingAddress = <ul>
                <li>Phone = 0609233570</li>
                <li>City = Mont D Or</li>
                <li>StateOrRegion = </li>
                <li>CountryCode = FR</li>
                <li>PostalCode = 36270</li>
                <li>Name = BERTHON VALERIE</li>
                <li>AddressLine1 =20 rue Geroget</li>
                <li>AddressLine2 =</li>
            </ul></li>
            </ul>Bad auth keyPHP Warning:  Invalid argument supplied for foreach
() in \AmazonSeller\testMWSamazon.php on lin
e 336

Warning: Invalid argument supplied for foreach() in \AmazonSeller\testMWSamazon.php on line 336
Panier VIDE, on sort de la boucle.<br/><hr/><br/><h2>R├®capitulatif</h2><h3>ID p
roduit Prestashop</h3><h3>Sku INVALIDES</h3>

```
I sent you via email the exact script that I followed
Thanks to check & feedback

**Comment by pppplus** [comment] 2019-05-09 20:26
Hi
Do you try the last version I sent to you on 3rd of may ?

**Comment by khouloudbelguith** [comment] 2019-05-10 08:07
@pppplus, no sorry I did not receive your email yet.
Thanks to check & feedback.

**Comment by pppplus** [comment] 2019-05-10 08:26
Ok, I just sent it again.

**Comment by khouloudbelguith** [comment] 2019-05-10 12:31
@pppplus, Thanks a lot for your feedback.
I have this error now
![image](https://user-images.githubusercontent.com/16067358/57527498-c35bc180-7327-11e9-9119-188f00a44257.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-06-10 08:21
Hi @pppplus,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-10 08:21 UTC
Labels: WS, Duplicate, Order

**Comment by pppplus** [comment] 2019-06-16 12:39
Ok, after a lot of research... I have something to propose.

1st : actionUpdateQuantity is never called, when an order is done from webservice.
2nd : product quantities (of pack item) are not updated when a pack is ordered from webservice => that's a bug I suppose ??
3rd : the problem seems to be in /clsses/StockAvailable/StockAvailable.php


`    
public function updateWs()
    {
        if ($this->depends_on_stock) {
            return WebserviceRequest::getInstance()->setError(500, $this->trans('You cannot update the available stock when it depends on stock.', array(), 'Admin.Catalog.Notification'), 133);
        }
        return $this->update();
    }
`

function update() call function postSave()

And first action of postSave is to exit on id_product_attribute == 0
Why ? I don't know !


So, my suggestion, modify the function updateWs() like this : 
`    
public function updateWs()
    {
        if ($this->depends_on_stock) {
            return WebserviceRequest::getInstance()->setError(500, $this->trans('You cannot update the available stock when it depends on stock.', array(), 'Admin.Catalog.Notification'), 133);
        }
        
        //add this
        if ($this->id_product_attribute == 0) {
            $this->setQuantity($this->id_product, $this->id_product_attribute, $this->quantity, $this->id_shop);
        }
        //end modificatin

        return $this->update();
    }
`

function setQuantity() call the hook actionUpdateQuantity (so, modules with actionUpdateQuantity  can now work !!)

BUT, to be usefull :
1- update manually item quantities of the item in the pack (via webservice stock_availables)
2- update manually quantities of the pack (via webservice stock_availables)

**Comment by pppplus** [comment] 2019-06-16 13:47
I just hope function updateWs() is called only from Webservice !!

**Comment by khouloudbelguith** [comment] 2019-06-17 11:27
@pppplus, Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by pppplus** [comment] 2019-06-17 11:34
Hi

No, because I'm not sure it's the right method to do it.
It's just for me, a solution, to have the hook working.

But I'm not sure, there is no bad things after my changes.
I think someone has to review my method, to implement it.

**Comment by pppplus** [comment] 2019-09-08 21:36
In PS 1.7.6.1 always the same problems.

**Comment by pppplus** [comment] 2020-09-18 07:18
Always same problem in 1.7.6.7

**Comment by khouloudbelguith** [comment] 2020-09-25 08:46
Hi @pppplus,

Please follow this issue: https://github.com/PrestaShop/PrestaShop/issues/13006
Your ticket is a duplicate of #13006
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-25 08:46
Duplicate of #13006
