### ISSUE TITLE
Error on module when check update

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22837] opened 2021-01-14 17:20 UTC
#### Describe the bug

Error on module when check update

#### Steps to Reproduce

1. Go to module manager
2. Click on 'configure (any module with this button
3. Click on "check update"

**Screenshots**

https://drive.google.com/file/d/1bYf-HhtZcl-shaSh67LtOHJkegEBJk5p/view

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by PierreRambaud** [comment] 2021-04-20 14:24
I'm no more able to reproduce. 
It has been fixed in #23834 and it's a duplicate of #23642

**Comment by Robin-Fischer-PS** [comment] 2021-04-27 14:59
I cannot reproduce the bug either, it was indeed fixed by https://github.com/PrestaShop/PrestaShop/pull/23834.

**Closed as completed** 2021-04-27 14:59 UTC
Labels: Bug, develop, Minor, BO, Modules, Regression, Fixed
