### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'finally'

### ISSUE THREAD

**Issue by dannielhendrix** [PrestaShop/PrestaShop#13694] opened 2019-05-07 09:51 UTC
Hello,

Wondering if anyone can help me in the right direction.

until today everything worked ok... today suddenly I can not enter to the admin of my store

The problem seems to be: PHP Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /home/....................../public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 201

has anyone ever met this problem? how to solve it?

Daniel

**Comment by khouloudbelguith** [comment] 2019-05-07 09:55
Hi @dannielhendrix,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matks** [comment] 2019-05-07 09:59
Hi @dannielhendrix your php version seems to be outdated as this error happens on php with version lower than 5.5

**Comment by dannielhendrix** [comment] 2019-05-07 10:11
hello @matks ,
thank you for your response, my php version is 5.6! and as I said everything worked well until today, when suddenly this problem

**Comment by dannielhendrix** [comment] 2019-05-07 10:17
the store works well, I get orders from customers... just that I can not just that I can not see the dashboard because of that error

**Comment by dannielhendrix** [comment] 2019-05-07 10:27
Hi @khouloudbelguith 
Thank you for your response
Prestashop version is 1.7.5.0
PHP version is 5.6
The rest of the data I really do not know where to find them

**Comment by khouloudbelguith** [comment] 2019-05-07 10:28
@dannielhendrix, Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by dannielhendrix** [comment] 2019-05-07 11:31
@khouloudbelguith 
I was able to find where the problem was: the frontend of the store it was on the php version 5.6 but the admin folder was on version 5.4 of the php! I do not know how it is possible but updating the php version for admin file to 5.6 solved the problem

**Comment by khouloudbelguith** [comment] 2019-05-07 11:57
@dannielhendrix, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-07 11:57 UTC
Labels: Bug, No change required

**Comment by matks** [comment] 2019-05-07 12:13
> I do not know how it is possible but updating the php version for admin file to 5.6 solved the problem

Ask your hosting provider 😉 . You should do it in order to be sure there is no other "surprises" like this still unknown to you
