### ISSUE TITLE
forecast dashboard doesn't store the settings

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#30823] opened 2023-01-11 19:25 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The settings are always back to zero after save in the forecast dashboard 

### Expected behavior

should work like in demo mode

### Steps to reproduce

Go to dashboard
click on Configure in the forecast panel
Enter some numbers in each month and save
<img width="876" alt="Capture d’écran 2023-01-11 à 20 17 42" src="https://user-images.githubusercontent.com/32092528/211898966-ec934c8e-2883-4946-a1cb-99434fa9bf57.png">

First problem : the graphic is not updated with our numbers, flat curves
<img width="881" alt="Capture d’écran 2023-01-11 à 20 17 57" src="https://user-images.githubusercontent.com/32092528/211899002-766eb3a7-4114-4f94-9dab-90954eb4db3d.png">

Go back the Configure : the numbers are still there
Refresh the dashboard and clic on Configure : all numbers set to zero

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

statsforecast ?

**Comment by mack94** [comment] 2023-01-12 09:50
Exactly the same trouble in my store with PS 1.7.7.8.

**Comment by kpodemski** [comment] 2023-01-12 10:37
Here's a fix:

https://github.com/PrestaShop/PrestaShop/pull/29741

**Comment by AureRita** [comment] 2023-01-12 16:23
HI @elmanu13  ,

We are aware of this issue, it is already in our debug backlog and, as we can see thanks to Kpodemski, it's already corrected for future versions.  

This issue is considered as a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9662 .

Thank you

**Comment by AureRita** [comment] 2023-01-12 16:23
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9662

**Closed as not planned by AureRita** 2023-01-12 16:23 UTC
Labels: Bug, Duplicate, Invalid
