### ISSUE TITLE
Error en el transportistas, se borra los valores según el peso.

### ISSUE THREAD

**Issue by Interdeportes** [PrestaShop/PrestaShop#14472] opened 2019-07-03 17:25 UTC
El error consiste que cuando ingreso los valeres del transportista, en mi caso Envía, se guardan común mente, pero con el tiempo se borran los valores según el peso. Ya es molesto, pues me ha sucedido varias veces, necesito con urgencia pronta respuesta.

PrestaShop version: 1.7

**Comment by khouloudbelguith** [comment] 2019-07-04 07:46
Hi @Interdeportes,

Thanks for your report.
Please, send your request in English.
English is the norm on the GitHub 
Thank you!

**Comment by Interdeportes** [comment] 2019-07-04 15:42
The error consists in the moment in which the transport values ​​are, however, in the case of transport values. It is already annoying, because it has happened to me several times, I urgently need a quick response.

**Comment by khouloudbelguith** [comment] 2019-07-04 16:05
@Interdeportes, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-05 07:32
Hi @Interdeportes,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-05 07:32 UTC
Labels: Carriers, No change required
