### ISSUE TITLE
[BO] - PPV2 Combinations is not  well organized

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#30883] opened 2023-01-16 09:33 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Bo, with a multistore is enabled , when a user create a new  PPV2 combination, then he generate combinations   => the displayed page is not  well organized

![image-png-1591×834-](https://user-images.githubusercontent.com/31663369/212643165-7a396c67-2ba3-492c-8e8a-6f02757bbe95.png)

### Expected behavior

![Products-•-devprs (4)](https://user-images.githubusercontent.com/31663369/212644029-af45c463-a87c-4e67-a783-bee5dfc38bfe.png)

### Steps to reproduce

1. Enable Multistore and Create a new store
2. Go to BO > Advanced Parameters >New & Experimental Features
3. Enable New product page - Multi store
4. Go to BO >Catalog >Products >Product with combinations  
5. Go to combinations >Generate combination  

==> The displayed page  is not  well organized

### PrestaShop version(s) where the bug happened

8.0.x , 800 , 8.0.1

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment] 2023-01-16 15:36
Hi @sallemiines 

Thank you for your report. We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28934 .

Thank you

**Comment by AureRita** [comment] 2023-01-16 15:36
Duplicate of #28934

**Closed as not planned by AureRita** 2023-01-16 15:36 UTC
Labels: Bug, BO, Duplicate, Multistore, Combinations, Invalid
