### ISSUE TITLE
Many bugs on my products images

### ISSUE THREAD

**Issue by bijouxmexicains** [PrestaShop/PrestaShop#11788] opened 2018-12-16 10:33 UTC
Hi guyz

Since the moment I changed my domain name, I have errors and errors :(

Now on my site, image are not displayed on click.
And declination are not displayed on click neither

**To Reproduce**
1. Go to 
https://www.bijouxmexicains.fr/bracelet/88-110-bracelet-perles-et-plumeaux.html#/37-couleur-rose_saumon
the color you want
Nothing is happening

**Additionnal information**
PrestaShop version: 1.7.1.4
PHP version: N/A

**Comment by bijouxmexicains** [comment] 2018-12-16 10:49
Ok, it seems it works with Chrome.
What is the problem with Safari ? Can I fix this ?

**Comment by bijouxmexicains** [comment] 2018-12-16 17:10
Ok so I was wrong Chrome is not better than Safari
When I clik on the small color square of the declination, the relative picture is not displayed
It sucks

**Comment by khouloudbelguith** [comment] 2018-12-17 08:39
Hi @bijouxmexicains,

I tried with your shop, when I'm using Google Chrome Version 71.0, it is OK.
I tried with Safari v5.1, you have an error in your console `Can't find variable: GoogleAnalyticEnhancedECommerce`
Did you use the ps_googleanalytics module, if yes, what is the exact version did you use?
![image](https://user-images.githubusercontent.com/16067358/50075935-8fe59280-01e0-11e9-8c97-3488ca3667b1.png)
Thanks!

**Comment by rdy4ever** [comment] 2018-12-17 08:41
Hi @bijouxmexicains 
As far as I can see, there is something wrong with your website, as it doesn't load any kind of javascript on the product page. I would suggest to download a fresh copy of the [Classic theme](https://github.com/PrestaShop/PrestaShop/tree/1.7.4.x/themes/classic) and replace it. Also, could you attach your themes/calssic/config/theme.yml file to take a look on it?
First, you should try to turn off javascript cache from the Performance page and see if that works. 
![image](https://user-images.githubusercontent.com/12268701/50075572-02a63c00-01e8-11e9-8c22-11b7f5077263.png)

**Comment by GreatestShowman** [comment] 2018-12-17 21:51
Hi ! I add the same problem ! Only dislable "products in same categorie" and it will works !

**Comment by bijouxmexicains** [comment] 2018-12-18 06:07
> Hi @bijouxmexicains
> As far as I can see, there is something wrong with your website, as it doesn't load any kind of javascript on the product page. I would suggest to download a fresh copy of the [Classic theme](https://github.com/PrestaShop/PrestaShop/tree/1.7.4.x/themes/classic) and replace it. Also, could you attach your themes/calssic/config/theme.yml file to take a look on it?
> First, you should try to turn off javascript cache from the Performance page and see if that works.
> ![image](https://user-images.githubusercontent.com/12268701/50075572-02a63c00-01e8-11e9-8c22-11b7f5077263.png)

Thanks, I will try this as the final option, because Im not sure to know how to do this

**Comment by bijouxmexicains** [comment] 2018-12-18 06:29
> Hi ! I add the same problem ! Only dislable "products in same categorie" and it will works !

Hi indeed this module has issues too. I am not as lucky as you are, when I am disabling it, nothing improve.
However there are some products where it really displays the products of the same category and then believe it or not, the declination seem working.
When the products in the same category are not displayed (I don't know why because it should ALWAYS diplay this information), declination is not working

**Comment by khouloudbelguith** [comment] 2018-12-18 11:30
Hi all,

We have recently released a new version ps_categoryproducts in few days, it is the v1.0.4.
@bijouxmexicains we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by bijouxmexicains** [comment] 2018-12-18 19:26
> Hi all,
> 
> We have recently released a new version ps_categoryproducts in few days, it is the v1.0.4.
> @bijouxmexicains we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!

I have indeed the v.1.0.4, i am going to enable debug mode and reply once i have more info 

Thanks

**Comment by bijouxmexicains** [comment] 2018-12-18 19:38
[DEBUG MESSAGE.pdf](https://github.com/PrestaShop/PrestaShop/files/2691986/DEBUG.MESSAGE.pdf)

I have this type of debug report on all the pages of my products

And this "Details du produit" is never working neither : 

<img width="1284" alt="capture d ecran 2018-12-18 a 20 37 59" src="https://user-images.githubusercontent.com/45802556/50178479-e946e200-0304-11e9-85bb-e694e832267e.png">

**Comment by khouloudbelguith** [comment] 2018-12-19 08:32
Hi @bijouxmexicains,

In fact, the ps_viewedproduct have an issue with PrestaShop which have version < 1.7.4.4.
Here's a fix for this module to solve your issue
https://github.com/PrestaShop/PrestaShop/issues/11655#issuecomment-445549934
Thanks to upload this fix & feedback.

About your second issue Product details, we currently have another issue with this #11798
Thanks!

**Comment by bijouxmexicains** [comment] 2018-12-19 18:23
Hi Khouloud, I don't have the module ps_viewedproduct in my database

The other issue is from me :/

**Comment by bijouxmexicains** [comment] 2018-12-19 18:43
pretty sure now it's about safari
but why ?

**Comment by khouloudbelguith** [comment] 2018-12-20 09:18
@bijouxmexicains, you need to navigate to your BO => Modules => Modules & Services => Modules Tab => search for this ps_viewedproduct module, disbale it, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/50275797-8c504680-0440-11e9-8410-ae59f44a6959.png)
Thanks!

**Comment by bijouxmexicains** [comment] 2018-12-20 19:35
Hi Khouloud,

I have desactivated it indeed. So obviously I have no more issue with this
module.

However my issue with declination is still the same on Safari :/

Thx



Le jeu. 20 déc. 2018 à 10:18, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2018-12-21 09:42
Hi @bijouxmexicains,

I tried again but I did not manage to reproduce the issue with Chrome browser Safari browser.
@marionf what do you think?
Thanks!

**Comment by marionf** [comment] 2018-12-26 09:36
Hello @bijouxmexicains ,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.

**Closed as completed by marionf** 2018-12-26 09:36 UTC
Labels: Bug, FO, Can't reproduce, Combinations
