### ISSUE TITLE
statsvisits error on line 176

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#19508] opened 2020-06-01 17:10 UTC
#### Describe the bug

Seems that the 2.0.2 with PS 1.7.6.5 have some trouble to get visitors stats firing on error_log_php this type of error:

[01-Jun-2020 02:32:03 Europe/Rome] PHP Warning:  Invalid argument supplied for foreach() in /home/xxxxxxx/public_html/modules/statsvisits/statsvisits.php on line 176

the result is an empty statistical graph:
![image](https://user-images.githubusercontent.com/16102074/83434751-538d0d00-a43b-11ea-8918-1b3ac699cd2e.png)

#### Expected behavior

normally the module will collect informations from visitors.

#### Steps to Reproduce

1. enable the module
2. go to the Stats menu and see the grpah empty
**Screenshots**

![image](https://user-images.githubusercontent.com/16102074/83434783-656eb000-a43b-11ea-9c75-c3efda864a8b.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.31

**Comment by florine2623** [comment] 2020-06-02 14:02
Hi @HartLarsson ,
In my shop 1.7.6.5, I do have the same issue :
![Capture d’écran 2020-06-02 à 15 57 56](https://user-images.githubusercontent.com/16019289/83528852-e5535380-a4e9-11ea-804d-cac0b7bdbd04.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by HartLarsson** [comment] 2020-06-08 17:48
> Hi @HartLarsson ,
> In my shop 1.7.6.5, I do have the same issue :
> ![Capture d’écran 2020-06-02 à 15 57 56](https://user-images.githubusercontent.com/16019289/83528852-e5535380-a4e9-11ea-804d-cac0b7bdbd04.png)
> I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
> Thanks!

i will take alook to see if i can fix

**Comment by davidglezz** [comment] 2020-07-18 22:01
Fixed in https://github.com/PrestaShop/statsvisits/commit/bc31e5569c1d3ed7c03eb9db32b549f73d9fbb71 on 13 Dec 2018 😮 

It seems they forgot to release.

**Comment by LouiseBonnard** [comment] 2020-08-03 16:15
Oops... thanks @davidglezz, you're right, the latest release happened in January 2018! @PrestaShop/prestashop-core-developers, do you think that we could plan a release in the next few weeks?

**Comment by HartLarsson** [comment] 2020-08-06 15:21
> Fixed in [PrestaShop/statsvisits@bc31e55](https://github.com/PrestaShop/statsvisits/commit/bc31e5569c1d3ed7c03eb9db32b549f73d9fbb71) on 13 Dec 2018 😮
> 
> It seems they forgot to release.

That fix resolved the module problem!
Thanks

**Comment by Progi1984** [comment] 2020-08-06 15:26
@LouiseBonnard I Take

**Comment by WartoWiedziec** [comment] 2020-08-15 11:17
I have the same problem. After enabling PHP version: 7.1.33 statsvisits module does not work and in error.log I see information as below:
[15-Aug-2020 11:55:14 Europe / Warsaw] PHP Warning: Invalid argument supplied for foreach () in /modules/statsvisits/statsvisits.php on line 196
![statsvisits - PHP 7 1 33](https://user-images.githubusercontent.com/6594124/90311282-91a5b300-def9-11ea-8fa3-e6d4f9c61be2.png)
But, interestingly, when I turn on PHP version: 7.0.33 the module starts working.
![statsvisits - PHP 7 0 33](https://user-images.githubusercontent.com/6594124/90311285-98342a80-def9-11ea-90c6-bb321a8a3799.png)

**Comment by khouloudbelguith** [comment] 2020-08-17 10:45
Hi all!

Here's the PR: https://github.com/PrestaShop/statsvisits/pull/3 to fix the issue.
This ticket is a duplicate of #11758
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-17 10:45
Duplicate of #11758

**Closed as completed by khouloudbelguith** 2020-08-17 10:45 UTC
Labels: Bug, Trivial, BO, Stats, 1.7.6.5

**Comment by WartoWiedziec** [comment] 2020-08-17 22:12
Hi all,

 

Thank you, it’s working now 😊 

 

Pozdrawiam/ Best regards
BW
