### ISSUE TITLE
Payments preferences : No checkbox in Carrier Restriction Table

### ISSUE THREAD

**Issue by uprisingweb** [PrestaShop/PrestaShop#31556] opened 2023-02-27 16:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have no checkbox but just "--" in the Payment Preference "Carrier Restriction" table and I can't find why.
I have to set the value directly in database.
See the screenshot for more information.

![screen](https://user-images.githubusercontent.com/39047087/221622260-c9b640fc-72e0-4a62-a53e-ed159bf271b7.png)

### Expected behavior

I expect to have checkbox and not "--"

### Steps to reproduce

1. Go to Admin
2. Click on Payment, then Preferences
3. Scroll down to the last table "Carrier Restrictions"

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

 7.2.34

### If your bug is related to a module, specify its name and its version

core

**Comment by sallemiines** [comment] 2023-02-27 17:02
Hello @uprisingweb 
I didn't manage to reproduce your issue with PS 1787 , PS 1788 , PS 800 ! 


![Preferences-•-1787](https://user-images.githubusercontent.com/31663369/221625827-02afa866-8999-4b13-a735-a30228d9094e.png)

Could you please check and feedback ! 

Thank you !

**Comment by uprisingweb** [comment] 2023-02-28 08:19
Hi @sallemiines 
Unfortunately,  I don't know how to reproduce and that the problem.
Do you know where can I find the source code where this data are initialised ? I'd like to debug but know I didn't found where this data is set.

**Comment by hibatallahAouadni** [comment] 2023-03-01 16:48
Hello @uprisingweb 

I see that you're using a third module carrier. So you should to contact the module developers to help you with this issue.
Closing the issue cause it's not a bug related to the Core PS.

Thanks for your understanding :pray:

**Closed as completed by hibatallahAouadni** 2023-03-01 16:48 UTC
Labels: Bug, BO, Payment preferences, Invalid, 1.7.8.7
