### ISSUE TITLE
Shipping methods backoffice - cannot save changes

### ISSUE THREAD

**Issue by sebaj** [PrestaShop/PrestaShop#30079] opened 2022-10-20 12:19 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am trying to modify or create a new shipping method from Backoffice admin but the shipping forms do not show save or create buttons, there is a UI problem in the forms. 
https://snipboard.io/wBJhYq.jpg

### Expected behavior

Show in the shipping method form buttons/links to the next step and save/create

### Steps to reproduce

1- Install Prestashop with Spanish language and Argentina Country
2- Go to backoffice Shipping > Carriers
3- CLick on modify an existing Shipping or click on Add new carrier button

### PrestaShop version(s) where the bug happened

8.0.0 RC 1

### PHP version(s) where the bug happened

8.1.9

**Comment by HanaRebaiQA** [comment] 2022-10-20 15:53
Hello @sebaj 

I tried to reproduce your issue. But, I was unable to reproduce it.
I used **8.0.0RC** with both **php 8.0** and **php 8.1**

**8.0.0RC with php 8.0 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/196996200-af49e276-dfd7-4780-b8e6-0e049b8a6f9e.mp4


**8.0.0RC with php 8.1 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/196996304-16f8b141-8bd4-4bb5-a371-138603da2d24.mp4


Could you please check again ? Did I missed something?

Thank You!

**Comment by sebaj** [comment] 2022-10-20 15:57
Could you try using docker-compose with this YML I attached to you?
I installed Prestashop 8 based on Docker image, maybe the bug is related to Docker connection?

Regards!
 Sebastian

**Comment by hibatallahAouadni** [comment] 2022-10-25 17:43
Hello @sebaj 

> Could you try using docker-compose with this YML I attached to you?
I installed Prestashop 8 based on Docker image, maybe the bug is related to Docker connection?

Could you please reply on Github thread :pray: cause when you replied by mail, there's no attachment file visible on Github.
Waiting for your feedback.

Thanks!

**Comment by sebaj** [comment] 2022-10-25 18:38
Hello @hibatallahAouadni , sorry for that. Here is the attachment:

[docker-compose.zip](https://github.com/PrestaShop/PrestaShop/files/9863042/docker-compose.zip)

Thank you! :)

**Comment by hibatallahAouadni** [comment] 2022-10-28 16:01
Ping @PrestaShop/qa-functional can someone please help reproducing the issue :pray: 
Thanks in advance!

**Comment by hibatallahAouadni** [comment] 2022-11-02 09:20
Hello @sebaj 

I checked your file docker-composer.yml and there's no issue with it, I tried multiple times to reproduce the issue but I didn't encounter any problem following your steps, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/199451403-200b8851-a35d-4e67-bb43-1b6066bc3ea2.png)
![image](https://user-images.githubusercontent.com/23308427/199451427-acf5a3d0-1680-4bba-abd0-29b3a62c53d1.png)
![image](https://user-images.githubusercontent.com/23308427/199451473-3d7e89a8-1754-4821-9dbb-0a9b4eae9ed6.png)

Please check and feedback.

Thanks!

**Comment by sebaj** [comment] 2022-11-02 12:34
Hi @hibatallahAouadni !
Did you use the same YML without any update? It is weird because this install different PHP version to me than yours. Also the Shipping admin stills broken.
Everything goes well if I download Prestashop 8 from github and use my own docker image (with PHP 7.4).

![image](https://user-images.githubusercontent.com/3721155/199490761-772c698c-d2fe-4afe-8b56-d2a8ff243ec4.png)

**Comment by hibatallahAouadni** [comment] 2022-11-04 16:51
Hello @sebaj 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug.

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-11-04 16:51 UTC
Labels: Bug, 8.0.x, BO, Shipping, Carriers, Invalid
