### ISSUE TITLE
Issue with clients file

### ISSUE THREAD

**Issue by vegaconsultores** [PrestaShop/PrestaShop#36679] opened 2024-08-06 11:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello!

I have an issue with the clients file. Everytime I opne one, I have this error.

https://github.com/user-attachments/assets/c09e7205-bed2-4d00-9e4a-868ba733d4d0

And it also happens when I try to enter them from Clients.

https://github.com/user-attachments/assets/5193e2f9-b7d8-4ca1-838f-3ec7abc2ce39

![image](https://github.com/user-attachments/assets/b78ff456-b9f1-43fe-be2e-e3a6c344fe6e)

Thanks a lot, 

### Expected behavior

I should be able to edit the client file.

### Steps to reproduce

1. Go to clients
2. Try to access the file from the name of the client
3. Get the error

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.29

### Your company or customer's name goes here (if applicable).

Moare Manualidades

**Comment by paulnoelcholot** [comment] 2024-08-07 08:04
Hello @vegaconsultores,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://www.loom.com/share/c2f3a2940c4249c1af753d3840b35861?sid=ad2d43c5-718f-45fc-876d-14f1f1803f15

**Closed as completed by paulnoelcholot** 2024-08-07 08:04 UTC
Labels: Bug, Can't reproduce
