### ISSUE TITLE
Gift products discount (voucher) and fixed amount discount (voucher) dont work together. The discount value is Not OK

### ISSUE THREAD

**Issue by webstartconsulting** [PrestaShop/PrestaShop#20245] opened 2020-07-20 14:21 UTC
#### Describe the bug

When a coupon giving a gift product and a coupon offering a fixed amount discount are used in the cart, the value of the fixed amount coupon is incorrect. See attached screenshots.

1. Crete one or two gift product coupon
2. create a fixed amount coupon
3. use it in cart.

**Screenshots**

<img width="1680" alt="Screenshot 2020-07-16 09 01 10" src="https://user-images.githubusercontent.com/41392532/87948404-f01b7500-caa4-11ea-978d-09439f739e7c.png">
<img width="1678" alt="Screenshot 2020-07-16 09 01 33" src="https://user-images.githubusercontent.com/41392532/87948440-fc073700-caa4-11ea-8ec2-4d8c5017c0db.png">

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.1

**Comment by webstartconsulting** [comment] 2020-07-21 12:34
Hi!
Can anyone help me with exactly what files the cart and cart rules work with?
This mistake is quite important and it is a shame that it has not been good for months.
And no one dares to touch or help solve it.

**Comment by florine2623** [comment] 2020-10-22 13:50
Hi @webstartconsulting ,
What exactly is the issue ?
Could you be more specific about the discounts created ? I will try it on my end once I have some more info.
Thanks!

**Comment by barbosatrix** [comment] 2020-11-04 22:07
Tengo un problema cuando asigno un coupon con impuestos excluidos, calcula un valor erroneo.
Tengo un inconveniente similar.

1. Creo un bono de bienvenida con valor de $25000 pesos. Envío incluido, impuestos incluidos 
2. Tengo un transportista con envío gratis después de $100000
3. Cuando el importe lo dejo de 25000 impuestos incluidos aparece el valor correcto en el carro pero no deja realizar la compra 
  si es mayor a $100000, se devuelve a la pantalla home del      sitio.
4. Cuando el importe lo dejo de 25000 impuestos excluidos, aparece un valor distinto, superior a $25000, variable según el valor 
 de los impuestos
    ,y con un rango entre los $1500 a $2000 si hago compras de 100mil a 200 mil,
    Aunque de esta forma si me deja realizar el pago.
5. No entiendo porque sucede esto. La pagina es cmerka-qa.cclcloud.co 
Estas son las imagenes de las configuraciones:

https://prntscr.com/vcnzep
https://prntscr.com/vcnz5a
https://prntscr.com/vcnz0h
https://prntscr.com/vcnyba

**Comment by florine2623** [comment] 2020-11-06 14:27
Hi @barbosatrix ,
English is the norm on GitHub.
I can't reproduce the issue on my end.
 It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.
Thanks!

**Comment by florine2623** [comment] 2020-11-06 14:27
Hi @webstartconsulting ,
I'll close the issue as we have not received an answer from you. Do not hesitate to open a new one if you gather all information.
Thanks!

**Closed as completed by florine2623** 2020-11-06 14:27 UTC
Labels: FO, Cart rules, No change required, 1.7.6.7

**Comment by webstartconsulting** [comment] 2022-04-07 15:49
Show your prestash shop that it works well. Don't close the bug until then. This is an existing bug. Definitely not a server configuration error.

**Comment by kpodemski** [comment] 2022-04-07 21:02
@webstartconsulting 

You can provide us with a valid, reproducable test scenario on PrestaShop 1.7.8.5. If we can reproduce the issue, then we can add it to the things "To do" :)

**Comment by webstartconsulting** [comment] 2022-04-08 06:06
Sorry for the mistake, this is an old bug that may not be present in the latest versions.
