### ISSUE TITLE
Everytime I click on a link or button, it always brings me to the login page

### ISSUE THREAD

**Issue by ToyPerson** [PrestaShop/PrestaShop#13908] opened 2019-05-21 23:25 UTC
I was granted permissions to access the PrestaBlog only. However, every time I click any link, button, or feature in the dashboard, I am always prompted to the login page. So, it means I have to login every now and then.

How do I prevent this so I can work on the blog seamlessly?

**Comment by khouloudbelguith** [comment] 2019-05-22 07:28
Hi @ToyPerson,

Thanks for your report.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - The theme used by default classic or not?
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ToyPerson** [comment] 2019-05-22 23:28
Hi @khouloudbelguith

Thanks for the reply.

I am just an ordinary user. In fact, as mentioned in my original question, I was given limited access. I see the error from the point of view of the user.

Our devs will try whitelisting my IP address. If it works, I'll provide feedback.

Cheers!

**Comment by khouloudbelguith** [comment] 2019-05-23 08:35
@ToyPerson, thanks!

Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-06-24 07:29
Hi @ToyPerson,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-24 07:29 UTC
Labels: FO, No change required
