### ISSUE TITLE
Can't create db backup on Prestashop 1.7.5.0

### ISSUE THREAD

**Issue by chrome12312** [PrestaShop/PrestaShop#11963] opened 2018-12-31 12:46 UTC
500 Internal server error when creating db backup - php 7.2

**Comment by khouloudbelguith** [comment] 2018-12-31 13:13
Hi @chrome12312,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!
Khouloud

**Comment by khouloudbelguith** [comment] 2019-02-01 16:51
Hi @chrome12312,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-01 16:51 UTC
Labels: DB Backup, No change required
