### ISSUE TITLE
Bug reorganize product

### ISSUE THREAD

**Issue by willgo34** [PrestaShop/PrestaShop#20572] opened 2020-08-13 11:34 UTC
Hello, I found a bug  on 2 of my prestashop : 
If you try to reorganize products it doesn't work anymore. 
This video will show you the problem : https://www.loom.com/share/330da75251b14a319c7c4937953fa869
Do you have the same problem ?

**Comment by sarahdib** [comment] 2020-08-13 11:57
@willgo34 

Please don't delete the template when you are submitting an issue. 

I close this issue, feel free to open a new one using the original template.

Also this is a duplicate of : #15291

Thank you

**Closed as completed by sarahdib** 2020-08-13 11:57 UTC
Labels: Duplicate, No change required

**Comment by sarahdib** [comment] 2020-08-13 12:00
Duplicate of #15291
