### ISSUE TITLE
Credit Slips / Vouchers of missing products fails

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#19076] opened 2020-05-11 15:42 UTC
Prestashop cannot handle generating vouchers and credit slips it seems.
If I can't find a product and want to create a credit slip for a product I say generate voucher.
What happens? The products are restocked (while the tick box was not ticked), no voucher is created
If I set a specific amount the credit slip shows the original amount
And if I create a voucher and link it to an account it does not show up in the Front Office
Also it is quite horrible that you cannot change any credit slip you make, why can I not delete it?
There is no way to undo
It is quite dramatic. Really makes me think we should change platform.

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by atomiix** [comment] 2020-05-11 16:18
Hi @sickboards 

Thanks for your feedback. Could give us more information on how to reproduce precisely and on which version of PrestaShop/PHP you are facing this issue? Thanks

**Comment by florine2623** [comment] 2020-06-05 15:50
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-05 15:50 UTC
Labels: No change required

**Comment by sickboards** [comment] 2020-06-05 16:07
Sorry super busy here

Version 1.7.5.2, multi store
php 7.1

reproducing is simple just make an order check the stock, do a partial refund without stock update and see that the stock is updated.
