### ISSUE TITLE
Same translation with different cases cannot be translated

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15604] opened 2019-09-18 17:17 UTC
If two strings exist in a code, with a same text, but different cases, they cannot be translated.

**To Reproduce**
1. `Shipping Method` - Shop.Theme.Checkout already exists in a template.
2. Add `{l s='Shipping method' d='Shop.Theme.Checkout'}` to a code.
3. Go to translations, search for Shipping method.
4. Translate both, save it.
5. Only one translation gets updated, the second one is impossible to update.

**Additional information**
PrestaShop version: 1.7.6.0

**Comment by khouloudbelguith** [comment] 2019-09-19 07:38
Hi @Hlavtox,

Here's a PR: https://github.com/PrestaShop/PrestaShop/pull/15511 to fix the issue.
Your ticket is a duplicate of #10701
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-19 07:38
Duplicate of #10701

**Closed as completed by khouloudbelguith** 2019-09-19 07:38 UTC
Labels: Duplicate
