### ISSUE TITLE
1.7 zero decimals still not solved!

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#11062] opened 2018-10-18 12:15 UTC
Since 1.7, decimal places stopped working.

Even if you set decimal places to zero, Prestashop still uses 2 decimals everywhere. The only solution is to manually edit the CLDR file.

**To Reproduce**
- Go to Preferences > General
- Set Number of decimals to 0
- Go to front and still see 2 decimal places

**Additionnal information**
PrestaShop version: 1.7 and upper
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-10-18 13:03
Hi @Hlavtox,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10017
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-18 13:03 UTC
Labels: Duplicate
