### ISSUE TITLE
PrestaShop wrong calculation of prices and taxes

### ISSUE THREAD

**Issue by Tarraga** [PrestaShop/PrestaShop#21866] opened 2020-11-11 13:05 UTC
#### Describe the bug

PrestaShop is calculating wrong the prices and taxes when a product have a discount.
I have a total tax excl of 108.03€ and a tax rate of 21%.
Total should be 130.72€ but PrestaShop is eating a cent in his calculations.

#### Steps to Reproduce

Just add a product of 165.21€ tax excl., 21% tax and 50% off
Shipping of 25.42€

![a](https://user-images.githubusercontent.com/18283446/98815020-d1ac0180-2426-11eb-8db7-d7a36893621f.jpg)

As you can see, the total is 130.21€ with taxes included, but the operation to calculate tax should be total price tax excl * tax rate / 100. I'm using a 21% fee.

So, (82.61 + 25.42) * 21 / 100 = 22.6863 which rounded is 22.69€ while PrestaShop shows 22.68€

I think PrestaShop is not rounding the price calculation when it has a discount, product price with tax included is 99.95€ tax included when it should be 99.96€
165,21 * 50 / 100 = 82.605€ * 1.21 = 99.95€

Tools::ps_round(165,21 * 50 / 100, 2) = 82.61€ * 1.21 = 99.9581 ~ 99.96€

PS version: 1.7.6.8
PHP version: 7.1.32

**Comment by hibatallahAouadni** [comment] 2020-11-11 13:12
Hello @Tarraga 

Could you please add the PrestaShop version and the PHP version you used.

Thanks!

**Comment by Tarraga** [comment] 2020-11-11 13:39
@hibatallahAouadni added!

**Comment by hibatallahAouadni** [comment] 2020-11-11 14:43
Hello @Tarraga 

Could you please check if your issue is similar to this one #9779

Thanks!

**Comment by Tarraga** [comment] 2020-11-12 09:22
@hibatallahAouadni I don't think it's the same, it seems like a rounding problem when a lot of units is added to the cart.
I'm talking about a single product, I cannot understand how no one provides a solution to this serious error

**Comment by hibatallahAouadni** [comment] 2020-11-12 09:28
Hi @Tarraga 

We are aware of all rounding issues, it is already in our debug backlog. As you can see we already have an epic about these probelm #19445 
Could you please check it and feedback.

Thanks!

**Comment by Tarraga** [comment] 2020-11-12 09:43
I have figured out the fix is very easy. It only round the prices at sight, but the calculation takes all decimals

![Captura de pantalla 2020-11-12 a las 10 42 27](https://user-images.githubusercontent.com/18283446/98923345-d1b60b00-24d3-11eb-9103-50be8fd9eaa1.jpg)

It have to round the price with reduction before doing the calculation!

**Comment by hibatallahAouadni** [comment] 2020-11-12 09:49
Hello,

I see you have already fixed it on your end, could you please send us a pull request!

Thanks!

**Comment by Tarraga** [comment] 2020-11-12 09:50
I have figured out the fix but I don't really know where to change it in the code, if someone could help with this..

**Comment by hibatallahAouadni** [comment] 2020-11-12 09:52
Hi @Tarraga 

You can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by hibatallahAouadni** [comment] 2020-11-24 10:13
Hello @Tarraga 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17161 (related o Epic #19445)
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-24 10:13
Duplicate of #17161

**Closed as completed by hibatallahAouadni** 2020-11-24 10:13 UTC
Labels: Bug, FO, Duplicate, Order, Taxes and Prices
