### ISSUE TITLE
Getting error when try to to use discount voucher value more than cart value.

### ISSUE THREAD

**Issue by VipinNethues** [PrestaShop/PrestaShop#28176] opened 2022-04-08 06:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello there, I hope you guys are doing good.

I want to mention a issue  in **PS 1.7.8.0** . 

**Error:** 
Property Order->total_paid is not valid
at line 1046 in file classes/ObjectModel.php

**How to reproduce it:**
1.  Create a voucher of amount 20$ (in any currency)  - 
2. add products in you cart on front shop less then voucher amount, in our case its ₹19.85 (cart total must be less then voucher amount)
3. Apply that voucher now you will see  ->  Total (tax incl.)-₹0.01  on cart summery.
4. choose address and payment option and proceed.
Now you will get that error, check attached image. 
  
![Property-Order-total_paid-is-not-valid](https://user-images.githubusercontent.com/20845330/161262414-eb7ac7c9-26db-482e-ab78-77b7379ad06d.png)

https://user-images.githubusercontent.com/20845330/162379288-a3d52dd1-b925-4a81-8367-e82d71a3f0d5.mp4

Looking for solution, if its already fixed please provide PR link for that fix.

Thanks

### Expected behavior

Order must be placed successfully. 

### Steps to reproduce

**How to reproduce it:**
1.  Create a voucher of amount 20$ (in any currency)  - 
2. add products in you cart on front shop less then voucher amount, in our case its ₹19.85 (cart total must be less then voucher amount)
3. Apply that voucher now you will see  ->  Total (tax incl.)-₹0.01  on cart summery.
4. choose address and payment option and proceed.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.1

**Comment by Hlavtox** [comment] 2022-04-08 08:08
This seems like one of those errors that happened (maybe still happen) when editing order in backoffice. Due to some rounding, it resulted in negative order total and exactly this fatal error.

This seems pretty serious however. Ping @jolelievre @matthieu-rolland

**Comment by khouloudbelguith** [comment] 2022-04-08 10:19
Hi @VipinNethues,

I did not manage to reproduce the issue with PS1785.
I attached a screen record

https://user-images.githubusercontent.com/16067358/162416413-20659fb4-cc23-4a60-9f5f-ec541eb0d616.mp4

This issue is fixed here: https://github.com/PrestaShop/PrestaShop/pull/17877 as reported in this issue: https://github.com/PrestaShop/PrestaShop/issues/13809

Thanks to provide me a screenshot from BO > Shop Parameters > General page
![image](https://user-images.githubusercontent.com/16067358/162416891-11a645cd-c70f-4e93-9e39-2bef3aa4f20c.png)

Could you please check and feedback.

Thanks!

**Comment by VipinNethues** [comment] 2022-04-12 10:25
Hi @khouloudbelguith 
This issue is with  with PS1780.

Here is the screenshot from BO > Shop Parameters > General page
![2022-04-12_15-45](https://user-images.githubusercontent.com/20845330/162940130-2c91566d-7672-4694-83ad-7ebb0a9bce3e.png)


Thanks

**Comment by marwachelly** [comment] 2022-04-12 14:30
Hello @VipinNethues,

I didn't manage to reproduce your issue. I used PS1.7.8.0 and INR currency. 

https://user-images.githubusercontent.com/89604350/162985465-901c0f7b-d575-4b93-a7b4-f8e8d78fb33a.mp4

Did I miss some thing? 

Waiting for your feedback :blush: 

Thanks,

**Comment by florine2623** [comment] 2022-05-03 12:09
Hello @VipinNethues ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2022-05-03 12:09 UTC
Labels: Bug, FO, Order, Discounts, Cart rules, Checkout, 1.7.8.0, Invalid

**Comment by waflessnet** [comment] 2022-09-02 02:12
hello , idem problem  in ps 1.7.8.6 !
