### ISSUE TITLE
Admin Notifications Total Still Counting Disabled Notification Type

### ISSUE THREAD

**Issue by psydomin** [PrestaShop/PrestaShop#22394] opened 2020-12-13 02:43 UTC
#### Describe the bug

If you disable a type of notifications (New order/customer/message) on configure/advanced/administration the corresponding tab stops showing but the notification count on the notification icon still counts new notifications from the disabled types.

#### Expected behavior

Notifications from disabled notification types should not count towards the total new notifications count

#### Steps to Reproduce

1. Disable 1 or more notification type (New order, New customer or New Message) on configure/advanced/administration and save
2. Trigger a notification (By creating a new order, account or message)
3. There will still be a new notification (Although the notification itself wont be shown because the tab is disables, thus unabling us from clearing the notification)

**Screenshots**
![image](https://user-images.githubusercontent.com/12779551/102001682-c3365b80-3cec-11eb-9304-d3ee23b51515.png)
![image](https://user-images.githubusercontent.com/12779551/102001690-cd585a00-3cec-11eb-9246-c1d3dbf00e6f.png)
![image](https://user-images.githubusercontent.com/12779551/102001710-f678ea80-3cec-11eb-9d00-44e849360624.png)

#### Additional information

* PrestaShop version: 1.7.7.0

**Comment by hibatallahAouadni** [comment] 2020-12-15 09:18
Hello @psydomin 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1mWt5Vz2GT-7LukGYd8JWlozL3WigRb4c/view

Please check and feedback.

Thanks!

**Comment by psydomin** [comment] 2020-12-15 18:25
I believe you have misunderstood me. The problem is when you hide notifications for x (new customer for example) and then perform an action that triggers that same notification type (creating an account).
In your caso you did as follows:
Hide "new account" notifications > Create new order > Notification (for new order) shows <= This is OK, is as it should be.
The problem is when you do:
Hide "new account" notifications > Create new account > Notification(for the new account) shows <= This is KO, the notification should not show.

I've only tested with the new account notifications, I'm not sure it happens with the other types of notification (new order and new message).

I'm not talking about the notification on the pop up menu. I'm talking about the yellow circle with the "number of new notifications" on the bell icon. It counts and announces the notifications even when that type of notification is disabled.

**Comment by hibatallahAouadni** [comment] 2020-12-16 14:43
Hello @psydomin 

Thanks for the clarification :smile: I manage to reproduce the issue with PS1.7.6.9 and PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1h42H2g0fpJ359jD05JMW3hR_qat2H24H/view

> I've only tested with the new account notifications, I'm not sure it happens with the other types of notification (new order and new message).

I've tested all and unfortunately the same issue occurs with new Order and new Message :sweat: 

---

I'm really sorry but this issue is a duplicate of #10723. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-16 14:47
Duplicate of #10723

**Closed as completed by hibatallahAouadni** 2020-12-16 14:47 UTC
Labels: Bug, BO, Duplicate, Advanced parameters, Administration, 1.7.7.0, 1.7.6.9
