### ISSUE TITLE
Smarty template caching Module::isCached() faulty causes performance loss

### ISSUE THREAD

**Issue by lukaslau** [PrestaShop/PrestaShop#24235] opened 2021-04-27 12:19 UTC
#### Describe the bug

Prestashop class **Module** (`Prestashop /classes/module/Module.php`) has a function called **isCached** to check if tpl file is cached. This function fails to check and returns **false** while tpl is cached. 

Commit https://github.com/PrestaShop/PrestaShop/pull/13804

Person who made PR was fixing issue #9763 and modified Module's class function **fetch** adding this:

```
if ($compile_id === null) {
            $compile_id = Context::getContext()->shop->theme->getName();
        }
```
Because of this change when you call **fetch** function with **$compile_id = null** it generates smarty cache file under $compile_id directory which is theme name in this case (if $compile_id is null then $compile_id is set to theme name).

But when you try to check if template is cached with function **isCached** with **$compile_id = null** you always get **false** because code added in **fetch** function should be also added to **isCached** function.

Templates are fetched (cached) under compile_id which is theme name in most cases, but isCached function checks if template is cached with empty compile_id which causes false result.

**This bug causes a huge performance issues.** Many plugins check if tpl is cached and if not - they perform data aggregation and assignation for smarty to render tpl but actually is not needed. 

#### Steps to Reproduce

1. Turn on debug profiling;
2. Open Prestashop Front Office and check executed SQL queries count;
3. Add this code 

```
if ($compile_id === null) {
            $compile_id = Context::getContext()->shop->theme->getName();
        }
```

4. in the beggining of **Module** (`Prestashop /classes/module/Module.php`) class function **isCached**;
5. Open Prestashop Front Office in separate window and check SQL queries count;
6. Second time queries count should be lower;

#### Additional information

* PrestaShop version: From 1.7.7.0
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-04-27 12:47
Hello @lukaslau 

Could you please check this issue #22647 it seems similar to yours.
Please check and feedback.

PS: next time please respect and follow the provided template to submit a complete bug report.

Thanks!

**Comment by kpodemski** [comment] 2021-04-27 12:49
Hey @lukaslau 

It seems that you're right, it does improve performance and it does makes sense to add it to `isCached` too, would you like to create [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#pull-requests) on `develop` branch to fix this issue?

Edit: I think it's regression from 1.7.6, I wonder if we could fix it in 1.7.7.4 @PrestaShop/prestashop-core-developers ?

**Comment by matks** [comment] 2021-05-14 15:27
> Edit: I think it's regression from 1.7.6, I wonder if we could fix it in 1.7.7.5 @PrestaShop/prestashop-core-developers ?

Regressions between 1.7.6 and 1.7.7 can indeed be fixed in 1.7.7 patch versions 😊

**Comment by hibatallahAouadni** [comment] 2021-05-17 09:10
@matks so shall we change this issue status to **`To Do`**?

**Comment by matks** [comment] 2021-05-17 11:23
@hibatallahAouadni I think we can pass this as `To Do` for 1.7.7 patch versions. Can you confirm there is no bug in 1.7.6 ?

**Comment by hibatallahAouadni** [comment] 2021-05-17 13:05
@matks Well it's not a bug cause it's about performance (sorry I didn't notice that it was labeled as a bug, my fault) :wink:

**Comment by kpodemski** [comment] 2021-05-20 09:20
@hibatallahAouadni @matks 

wait a second, regression in performance because of wrong change... is not a regression? ;)

**Comment by eternoendless** [comment] 2021-07-22 15:01
A performance regression is a **bug**, not an improvement. A request to improve the existing (not degraded) performance would be a feature request.

**Comment by marionf** [comment] 2021-07-26 12:08
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25413

**Closed as completed** 2021-07-26 12:08 UTC
Labels: Bug, Critical, FO, Regression, Fixed, PR available, 1.7.7.0
