### ISSUE TITLE
Module: ps_facetedsearch. Only default category products is listed

### ISSUE THREAD

**Issue by gadnis** [PrestaShop/PrestaShop#17195] opened 2020-01-15 17:11 UTC
**Bug**
Only default category products is listed when using ps_facetedsearch module. Product must be listed in the category no matter it is its default category or not.

**To Reproduce**
1. Enable the module
2. Go to ps_facetedsearch module preferences. Set `Show products from subcategories` to NO
3. Go to Catalog > Products. Pick one product add it to two different categories. One category will be default category.
4. Go to default category on FOH. You will see the product is there.
5. Go to other product category on FOH. You will see product is missing

**Additional information**
ps_facetedsearch version: 3.4.1
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-01-16 08:22
Hi @gadnis,

We are awre manage to reproduce the issue, it should be specified by our product team.
Your ticket is a duplicate of #14003
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-01-16 08:22
Duplicate of #14003

**Closed as completed by khouloudbelguith** 2020-01-16 08:22 UTC
Labels: Duplicate, Faceted search
