### ISSUE TITLE
"Offers", "review" or "aggregateRating" must be specified- Google Search Console

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18692] opened 2020-04-17 14:17 UTC
#### Describe the bug

Hello, I receive this error from google, any ideas on how to fix it?

**Screenshots**

https://prnt.sc/s18oz8

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by BenTen** [comment] 2020-04-19 08:48
Did you read the ticket #12687 and/or install the native module https://github.com/PrestaShop/productcomments ?

**Comment by alfonsolr09** [comment] 2020-04-19 19:33
yes i just read it
 I don't use the classic theme, should I speak to the theme provider?

**Comment by vadrien1999** [comment] 2020-04-20 10:02
Hello, I looked at the previous tutorial page regarding google search console errors. But despite having modified the files, product.tpl, product-price.tpl, product-details.tpl, productlist.tpl, etc ...
I still have a problem with "brand", "name" and "extract of opinion" I am on prestashop 1.7.6.4

**Comment by matthieu-rolland** [comment] 2020-04-20 13:12
@alfonsolr09 hello, is this an SEO issue ?

**Comment by alfonsolr09** [comment] 2020-04-20 14:37
I don't know... I think yes

**Comment by matthieu-rolland** [comment] 2020-04-20 15:30
ping @PrestaShop/prestashop-product-team   should we do something about this issue?

**Comment by hibatallahAouadni** [comment] 2021-01-04 15:30
Hello,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- steps to reproduce
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by alfonsolr09** [comment] 2021-01-10 14:54
https://prnt.sc/wkatza

https://prnt.sc/wkau8m

**Comment by alfonsolr09** [comment] 2021-01-10 14:59
I attach many more errors
https://prnt.sc/wkaxiy

**Comment by hibatallahAouadni** [comment] 2021-01-11 10:19
Hello @alfonsolr09 

Could you please check if your issue is a duplicate to this one #22636

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-11 16:48
Hello @alfonsolr09 

I'm really sorry but I have to close your issue :wink: cause it's a duplicate of #22416
As you can see while reproducing the issue mentionned above, I manage to reproduce your issue, see the attached screen record below:

https://drive.google.com/file/d/1kerCmPxQkaJ-wuP6Hs-pMnLFTwVfYH9T/view

So please subscribe to the issue mentionned above to get notification when the problem is fixed.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-11 16:48
Duplicate of #22416

**Closed as completed by hibatallahAouadni** 2021-01-11 16:48 UTC
Labels: Bug, FO, Duplicate, SEO & URLs, 1.7.6.4

**Comment by alfonsolr09** [comment] 2021-01-11 23:03
#22416 is duplicate of my issue
@hibatallahAouadni
