### ISSUE TITLE
[FO] Form elements are misaligned in 1.7.x.x and inconsistent on different browsers

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26644] opened 2021-11-17 01:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This bug was there even in 1.7.7, but wasn't so visible.

Login form:

![obraz](https://user-images.githubusercontent.com/5007456/142091008-4c59a9de-aa71-43ab-8914-34b83faf5ed7.png)

Looks even worse when focused:

![obraz](https://user-images.githubusercontent.com/5007456/142091100-4c3d6997-9aaf-4333-b2ca-6603ba4e9182.png)

It's the same on account creation page and checkout page:

![obraz](https://user-images.githubusercontent.com/5007456/142091556-c3b0ed09-a19d-445c-83b5-e193aace3a66.png)

### Expected behavior

Form buttons should be aligned with inputs

### Steps to reproduce

1. Go to Sign in page
2. Go to Create account page
3. Go to Order page, 1st tab: Personal Information
4. Focus password input on each page

### PrestaShop version(s) where the bug happened

1.7.7x, 1.7.8.x

**Comment by hibatallahAouadni** [comment] 2021-11-17 14:19
Hello @SharakPL 

I didn't manage to reproduce the issue with PS1.7.8.1 and PS1.7.7.8, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/142217430-7ddfb286-e3da-4a2e-b07d-663acfbef4de.png)

Could you please provide your Browser name and version. 
Please check and feedback.

Thanks!

**Comment by SharakPL** [comment] 2021-11-17 14:54
@hibatallahAouadni you're right it's browser related. Chromium browsers show it slightly better, though still not ideal as input has 38px height and button 38.69px, so it's all fitted sloppy.

Firefox tries to be smart when styles have contradictions. There's `float: left;` on `.input-group .form-control` and later appears `display: table-cell;`. Apparently Firefox changes `display` values [when the element is floated](https://developer.mozilla.org/en-US/docs/Web/CSS/float) so it ignored `table-cell` and used `block` instead.

### Solution:
Pretty obvious! Forms and buttons should be rebuilt with Flex.
We have to get rid of floats and table-cells 😅

**Comment by hibatallahAouadni** [comment] 2021-11-17 16:34
Hello @SharakPL 

Indeed it's related to the browser:

### Firefox :x: 

![image](https://user-images.githubusercontent.com/23308427/142239226-6bcf394a-eaf6-433e-b789-430a65c5d562.png)

### Safari :x: 

![image](https://user-images.githubusercontent.com/23308427/142239196-5d0beb9d-f6ec-4b98-9e87-2f43e5d2f902.png)

### Opera :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/142240497-a507f7be-28b7-493d-bd1b-6ac0c1de321a.png)

### Edge :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/142241728-9098b26d-6801-4cdb-85f8-b2a227d9e710.png)

### Chrome :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/142241836-61dd66b2-27af-406a-a1c9-d7baf84b3af1.png)

So, we need to fix the issue in FireFox and Safari. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by SharakPL** [comment] 2021-11-17 17:18
It's not properly aligned on any of the browsers so I would put ❌ on all of them 😛

Chrome/Edge/Opera - zoomed in for better view:
![obraz](https://user-images.githubusercontent.com/5007456/142253634-70439a6c-2a3e-471b-b2b2-561f1d9a1715.png)

**Closed as completed** 2021-11-23 12:01 UTC
Labels: Bug, Trivial, FO, Fixed, Front-end, PR available, 1.7.7.8, Verified
