### ISSUE TITLE
Error updating Prestashop 1.7.5.2 to 1.7.6.4

### ISSUE THREAD

**Issue by rmasq** [PrestaShop/PrestaShop#18251] opened 2020-03-20 17:47 UTC
Hello,
I'm trying to update prestashop but when I update, at the end of the proccess with 1-Click Upgrade it show this error:

[INTERNAL] /var/www/vhosts/comercialpeluquerias.com/httpdocs/src/PrestaShopBundle/PrestaShopBundle.php line 64 - Error: Class 'PrestaShopBundle\DependencyInjection\Compiler\OverrideTwigServiceCompilerPass' not found #0 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(797): PrestaShopBundle\PrestaShopBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(636): Symfony\Component\HttpKernel\Kernel->buildContainer() #3 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #5 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #6 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #7 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /var/www/vhosts/comercialpeluquerias.com/httpdocs/admin192rbtqdy/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}

When entering the backend it returns an error:

(1/1) PrestaShopDatabaseException
Table 'comercial-pelu-new.ps_currency_lang' doesn't exist

SELECT *

FROM ps_currency_lang

WHERE id_currency = 1
in Db.php line 769
at DbCore->displayError('SELECT * FROM ps_currency_lang WHERE id_currency = 1')
in Db.php line 385
at DbCore->query('SELECT * FROM ps_currency_lang WHERE id_currency = 1')
in Db.php line 613
at DbCore->executeS('SELECT * FROM ps_currency_lang WHERE id_currency = 1')
in EntityMapper.php line 82
at EntityMapper->load('1', null, object(Currency), array('table' => 'currency', 'primary' => 'id_currency', 'multilang' => true, 'fields' => array('iso_code' => array('type' => 3, 'validate' => 'isLanguageIsoCode', 'required' => true, 'size' => 3), 'numeric_iso_code' => array('type' => 3, 'validate' => 'isNumericIsoCode', 'size' => 3), 'precision' => array('type' => 1, 'validate' => 'isInt'), 'conversion_rate' => array('type' => 4, 'validate' => 'isUnsignedFloat', 'required' => true, 'shop' => true), 'deleted' => array('type' => 2, 'validate' => 'isBool'), 'active' => array('type' => 2, 'validate' => 'isBool'), 'name' => array('type' => 3, 'lang' => true, 'validate' => 'isGenericName', 'size' => 255), 'symbol' => array('type' => 3, 'lang' => true, 'size' => 255)), 'classname' => 'Currency', 'associations' => array('l' => array('type' => 2, 'field' => 'id_currency', 'foreign_field' => 'id_currency'))), 1, true)
in ObjectModel.php line 264
at ObjectModelCore->__construct('1', null, null)
in Currency.php line 209
at CurrencyCore->__construct('1')
in AdminController.php line 2958
at AdminControllerCore->initShopContext()
in AdminController.php line 531
at AdminControllerCore->__construct()
in LegacyContext.php line 85
at LegacyContext->getContext()
in UserLocaleListener.php line 39
at UserLocaleListener->__construct(object(LegacyContext))
in appDevDebugProjectContainer.php line 2385
at appDevDebugProjectContainer->getPrestashop_UserLocale_ListenerService()
in appDevDebugProjectContainer.php line 2872
at appDevDebugProjectContainer->ContainerRvrxt5t{closure}()
in EventDispatcher.php line 229
at EventDispatcher->sortListeners('kernel.request')
in EventDispatcher.php line 61
at EventDispatcher->getListeners('kernel.request')
in ContainerAwareEventDispatcher.php line 128
at ContainerAwareEventDispatcher->getListeners('kernel.request')
in TraceableEventDispatcher.php line 262
at TraceableEventDispatcher->preProcess('kernel.request')
in TraceableEventDispatcher.php line 137
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)
in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)
in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)
in index.php line 86

Before updated prestashop I have updated all modules to latest version, and enable the "classic" theme.
Prestashop version 1.7.5.2
Php version: 7.3

Thanks in advance.

**Comment by rmasq** [comment] 2020-03-20 17:58
Hello,
I'm trying to update prestashop but when I update, at the end of the proccess with 1-Click Upgrade it show this error:

[INTERNAL] /var/www/vhosts/comercialpeluquerias.com/httpdocs/src/PrestaShopBundle/PrestaShopBundle.php line 64 - Error: Class 'PrestaShopBundle\DependencyInjection\Compiler\OverrideTwigServiceCompilerPass' not found #0 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(797): PrestaShopBundle\PrestaShopBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(636): Symfony\Component\HttpKernel\Kernel->buildContainer() #3 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #5 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #6 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #7 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /var/www/vhosts/comercialpeluquerias.com/httpdocs/admin192rbtqdy/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}

When entering the backend it returns an error:

> (1/1) PrestaShopDatabaseException
Table 'comercial-pelu-new.ps_currency_lang' doesn't exist<br /><br /><pre>SELECT *
FROM `ps_currency_lang`
WHERE `id_currency` = 1</pre>

in Db.php line 769
at DbCore->displayError('SELECT * FROM `ps_currency_lang` WHERE `id_currency` = 1')
in Db.php line 385
at DbCore->query('SELECT * FROM `ps_currency_lang` WHERE `id_currency` = 1')
in Db.php line 613
at DbCore->executeS('SELECT * FROM `ps_currency_lang` WHERE `id_currency` = 1')
in EntityMapper.php line 82
at EntityMapper->load('1', null, object(Currency), array('table' => 'currency', 'primary' => 'id_currency', 'multilang' => true, 'fields' => array('iso_code' => array('type' => 3, 'validate' => 'isLanguageIsoCode', 'required' => true, 'size' => 3), 'numeric_iso_code' => array('type' => 3, 'validate' => 'isNumericIsoCode', 'size' => 3), 'precision' => array('type' => 1, 'validate' => 'isInt'), 'conversion_rate' => array('type' => 4, 'validate' => 'isUnsignedFloat', 'required' => true, 'shop' => true), 'deleted' => array('type' => 2, 'validate' => 'isBool'), 'active' => array('type' => 2, 'validate' => 'isBool'), 'name' => array('type' => 3, 'lang' => true, 'validate' => 'isGenericName', 'size' => 255), 'symbol' => array('type' => 3, 'lang' => true, 'size' => 255)), 'classname' => 'Currency', 'associations' => array('l' => array('type' => 2, 'field' => 'id_currency', 'foreign_field' => 'id_currency'))), 1, true)
in ObjectModel.php line 264
at ObjectModelCore->__construct('1', null, null)
in Currency.php line 209
at CurrencyCore->__construct('1')
in AdminController.php line 2958
at AdminControllerCore->initShopContext()
in AdminController.php line 531
at AdminControllerCore->__construct()
in LegacyContext.php line 85
at LegacyContext->getContext()
in UserLocaleListener.php line 39
at UserLocaleListener->__construct(object(LegacyContext))
in appDevDebugProjectContainer.php line 2385
at appDevDebugProjectContainer->getPrestashop_UserLocale_ListenerService()
in appDevDebugProjectContainer.php line 2872
at appDevDebugProjectContainer->ContainerRvrxt5t\{closure}()
in EventDispatcher.php line 229
at EventDispatcher->sortListeners('kernel.request')
in EventDispatcher.php line 61
at EventDispatcher->getListeners('kernel.request')
in ContainerAwareEventDispatcher.php line 128
at ContainerAwareEventDispatcher->getListeners('kernel.request')
in TraceableEventDispatcher.php line 262
at TraceableEventDispatcher->preProcess('kernel.request')
in TraceableEventDispatcher.php line 137
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)
in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)
in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)
in index.php line 86


Before updated prestashop I have updated all modules to latest version, and enable the "classic" theme.
Prestashop version 1.7.5.2
Php version: 7.3 

Thanks in advance.

**Comment by Hlavtox** [comment] 2020-03-20 20:27
`Table 'comercial-pelu-new.ps_currency_lang' doesn't exist. `

Does it exist?

**Comment by JBWModules** [comment] 2020-03-23 07:40
Prestashop 1.7.5 is only compatible to PHP 7.2 (thats not causing your issue but will probaly cause others)

**Comment by rmasq** [comment] 2020-03-23 08:28
> `Table 'comercial-pelu-new.ps_currency_lang' doesn't exist. `
> 
> Does it exist?

@Hlavtox Hello,
I have checked it and it doesn't exist in the database. But without this table it works fine in the indicated version.

**Comment by rmasq** [comment] 2020-03-23 08:31
> Prestashop 1.7.5 is only compatible to PHP 7.2 (thats not causing your issue but will probaly cause others)

Hello @JBWModules,

Thanks for the warning.   I have already changed it and if I do not receive any more suggestions to my problem I will try to update with this version of php again to see if it works.

**Comment by khouloudbelguith** [comment] 2020-03-23 10:22
Hi @rmasq,

What is the exact version of the 1-click upgrade did you use?
Thanks!

**Comment by rmasq** [comment] 2020-03-23 13:01
Hi @khouloudbelguith,
I'm using the version v4.9.0 of 1-click upgrade.

Thanks for your interest.

**Comment by khouloudbelguith** [comment] 2020-03-23 13:06
@rmasq, this is an old version.
The last release is 1-click upgrade v4.10.1.
https://addons.prestashop.com/en/data-migration-backup/5496-1-click-upgrade.html

Thanks to upgrade your module, check, and feedback.

**Comment by rmasq** [comment] 2020-03-25 20:03
Hi @khouloudbelguith 

I had upgrade this module and the rest and I have the same error: This is the log: 

[INTERNAL] /var/www/vhosts/comercialpeluquerias.com/httpdocs/src/PrestaShopBundle/PrestaShopBundle.php line 64 - Error: Class 'PrestaShopBundle\DependencyInjection\Compiler\OverrideTwigServiceCompilerPass' not found #0 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(797): PrestaShopBundle\PrestaShopBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(636): Symfony\Component\HttpKernel\Kernel->buildContainer() #3 /var/www/vhosts/comercialpeluquerias.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #5 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #6 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #7 /var/www/vhosts/comercialpeluquerias.com/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /var/www/vhosts/comercialpeluquerias.com/httpdocs/admin192rbtqdy/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}

Thanks

**Comment by khouloudbelguith** [comment] 2020-03-26 08:20
Hi @rmasq,

I did not manage to reproduce the issue with PS1.7.6.4 after an upgrade from PS1.7.5.2 using the 1-click upgrade v4.10.1.
Could you please check the exact version of the autoupgrade module in the file [/Project_Folder/modules/autoupgrade/config.xml](https://github.com/PrestaShop/autoupgrade/blob/master/config.xml#L5)
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by rmasq** [comment] 2020-03-27 12:08
Hi @khouloudbelguith 
The exact version is:   version><![CDATA[4.10.1]]

I add the file log.txt
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4393379/log.txt)

Thank you very for your help

**Comment by khouloudbelguith** [comment] 2020-03-27 16:16
@rmasq, 
In the BO => 1-click upgrade configuration page => the "Disable non-native modules" option is enabled?
Thanks to disable it, check and feedback.

**Comment by sarahdib** [comment] 2020-04-28 08:23
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed** 2020-04-28 08:23 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.5.2, 1.7.6.4

**Comment by rmasq** [comment] 2020-04-29 06:23
Sorry for not answering before. I have checked the last proposed option of "Disable non-native modules" and it worked fine! Thank you very much @khouloudbelguith for your help
