### ISSUE TITLE
Translation : Object Email

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#20447] opened 2020-08-04 10:53 UTC
#### Describe the bug

I'm trying to translate the subject line of an email and I feel like it's not working and I have errors.

![image](https://user-images.githubusercontent.com/25744417/89285799-5087e600-d651-11ea-8a91-690d878b2c45.png)

Can you help me pls ? Thanks

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2020-08-04 11:08
Hi @ShaimyWinda,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9599
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-04 11:08
Duplicate of #9599

**Closed as completed by khouloudbelguith** 2020-08-04 11:08 UTC
Labels: Duplicate

**Comment by runningz** [comment] 2020-08-31 07:37
Hi! PS 1.7.6.7 same problem. Any fix to apply?
