### ISSUE TITLE
Upgrade complete, but warning notifications has been found => [WARNING] SQL 1.7.0.0 1062 in INSERT INTO, SQL 1.7.5.0 1071 in ALTER TABLE `ps_customer`, SQL 1.7.5.0 1071 in ALTER TABLE `ps_employee`...

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#14434] opened 2019-06-29 22:36 UTC
**Describe the bug**
Hi, at the end of the update from 1.6.1.24 to the 1.7.5 by 1-click upgrade I found this warning:

**To Reproduce**
I backup production site to the local virtual server
I change all directory into the config file, I change on the DB too
I disable custom theme and able default one
I disable all 3th part modules
I disable cache
I disable friendly url
I regenerate all img

then

Go to '1-click upgrade'
Click on 'latest release 1.7.X'
Click Update and wait until finish
Upgrade complete, but warning notifications has been found.

[WARNING] SQL 1.7.0.0 1062 in INSERT INTO `ps_hook` (`name`, `title`, `description`, `position`) VALUES ('actionValidateCustomerAddressForm', 'Customer address form validation', 'This hook is called when a customer submit its address form', '1'), ('displayAfterCarrier', 'After carriers list', 'This hook is displayed after the carrier list in Front Office', '1'), ('displayCarrierExtraContent', 'Display additional content for a carrier (e.g pickup points)', 'This hook calls only the module related to the carrier, in order to add options when needed.', '1'), ('validateCustomerFormFields', 'Customer registration form validation', 'This hook is called to a module when it has sent additional fields with additionalCustomerFormFields', '1'), ('displayProductExtraContent', 'Display extra content on the product page', 'This hook expects ProductExtraContent instances, which will be properly displayed by the template on the product page.', '1'), ('displayNavFullWidth', 'Navigation', 'This hook displays full width navigation menu at the top of your pages', '1'), ('displayAfterBodyOpeningTag', 'Very top of pages', 'Use this hook for advertisement or modals you want to load first.', '1'), ('displayBeforeBodyClosingTag', 'Very bottom of pages', 'Use this hook for your modals or any content you want to load at the very end.', '1'): Duplicate entry 'displayAfterBodyOpeningTag' for key 'hook_name'

SQL 1.7.5.0 1071 in ALTER TABLE `ps_customer` CHANGE `company` `company` VARCHAR(255), CHANGE `email` `email` VARCHAR(255) NOT NULL, CHANGE `passwd` `passwd` VARCHAR(255) NOT NULL: Specified key was too long; max key length is 1000 bytes

SQL 1.7.5.0 1071 in ALTER TABLE `ps_employee` CHANGE `firstname` `firstname` VARCHAR(255) NOT NULL, CHANGE `email` `email` VARCHAR(255) NOT NULL, CHANGE `passwd` `passwd` VARCHAR(255) NOT NULL, CHANGE `lastname` `lastname` VARCHAR(255) NOT NULL: Specified key was too long; max key length is 1000 bytes

**Screenshots**
![warning-after-update](https://user-images.githubusercontent.com/28685316/60390041-db50f580-9acd-11e9-80b0-868bab4e770c.png)
![warning-after-update-02](https://user-images.githubusercontent.com/28685316/60390068-46023100-9ace-11e9-8bf0-b23f13c5c860.png)

**Additionnal information**
PrestaShop version: from 1.6.1.24 to 1.7.5
PHP version: 7.1.19
Local server => MAMP PRO 5

Thanks for any reply

**Comment by ballashop** [comment] 2019-06-29 23:38
Hi,
some areas are forbidden access into the 1.7.5 BO:
Orders
Discounts --> Catalog Price Rules
Customers
Stat
Contact --> Stores
Customer Settings  --> Titles
Advanced Parameters --> E-mail
In team permission a lot of Notice:
Notice alla linea 199 nel file /Applications/MAMP/htdocs/SiteTest/controllers/admin/AdminAccessController.php
[8] Undefined index: name

Notice alla linea 691 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: name

Notice alla linea 696 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 703 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: configure

Notice alla linea 704 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 711 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: uninstall

Notice alla linea 712 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 691 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: name

Notice alla linea 696 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 704 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 712 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 691 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: name

Notice alla linea 696 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 704 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 712 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 691 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: name

Notice alla linea 695 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: view

Notice alla linea 696 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 703 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: configure

Notice alla linea 704 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 712 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 691 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: name

Notice alla linea 696 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 704 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 712 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 691 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: name

Notice alla linea 695 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: view

Notice alla linea 696 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 704 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 712 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 691 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: name

Notice alla linea 696 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 704 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION

Notice alla linea 712 nel file /Applications/MAMP/htdocs/SiteTest/var/cache/dev/smarty/compile/8c/00/e1/8c00e196eca943ee41f9a8fe6e990c9d6e6a082c_0.file.form.tpl.php
[8] Undefined index: GAMIFICATION



<img width="940" alt="order-access-denied" src="https://user-images.githubusercontent.com/28685316/60390358-536ee980-9ad5-11e9-8282-cbf8cf2c052e.png">

**Comment by khouloudbelguith** [comment] 2019-07-01 11:46
Hi @ballashop,

Thanks for your report.
The warnings are not a serious problem. but they are fixed in the PS1.7.5.1.
A fix is available in #11814
About the second issue: `access denied`: We are aware of this issue, To fix this issue you need to replace 'ps_access' table in DB with the one from clean PS1.7 installation.
You can, for example, install PrestaShop separately, copy & paste the table ps_access to your shop.
Or you can follow this solution in this comment to solve your issue https://github.com/PrestaShop/PrestaShop/issues/9513#issuecomment-415011961
Before any modification, you can make a backup of your old database.
Your ticket is a duplicate of https://github.com/PrestaShop/autoupgrade/issues/100
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-01 11:46
Duplicate of https://github.com/PrestaShop/autoupgrade/issues/100

**Closed as completed by khouloudbelguith** 2019-07-01 11:46 UTC
Labels: Duplicate, Autoupgrade

**Comment by ballashop** [comment] 2019-07-01 15:10
Hi @khouloudbelguith thanks to reply me, it was just a local test, can I repeat it with a new version  1.7.5.1 or is it better to follow the fix indicated me at the link?
I didn't understand well how I can I fix it --> in #11814.
I'll take a closer look.
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2019-07-01 15:19
@ballashop, yes, you van upgrade to the PS1.7.5.1.
Also, we have the last stable version PS1.7.5.2.
https://www.prestashop.com/en/previous-versions

Thanks!

**Comment by ballashop** [comment] 2019-07-01 15:36
Hi @khouloudbelguith, I saw the video I made of the update, unfortunately the error came out with the 1.7.5.2, here is the screenshot, so I think I will inevitably have to follow the fixed post #11814.
![version](https://user-images.githubusercontent.com/28685316/60448627-4ca3bc00-9c26-11e9-95e1-70c27b338d40.png)
As I have some time I dedicate myself to the solution you indicate me..
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2019-07-01 15:42
@ballashop, so, you have also some warnings after upgrade to PS1.7.5.2?

Thanks!

**Comment by ballashop** [comment] 2019-07-01 15:46
Hi @khouloudbelguith,
I wrote all the warning that were showed.
May I send you the log?
Thanks to replay me.

**Comment by khouloudbelguith** [comment] 2019-07-01 15:52
@ballashop, you can find the log of your upgrade in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by ballashop** [comment] 2019-07-01 15:53
Yes, but can I send it to you?
By email?
Thanks a lot.

**Comment by khouloudbelguith** [comment] 2019-07-01 15:54
@ballashop, yes of course.
This is a public space.
You can provide me the log by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by ballashop** [comment] 2019-07-01 15:58
Ho, I sent you, thanks a lot.

**Comment by khouloudbelguith** [comment] 2019-07-01 16:12
@ballashop, thanks!
Did you make an upgrade from PS1.6.1.24 to PS1.7.5.1?

Thanks!

**Comment by ballashop** [comment] 2019-07-01 16:15
Hi @khouloudbelguith,
yes.
Thanks.

**Comment by khouloudbelguith** [comment] 2019-07-02 12:32
@ballashop, thanks for your feedback.
I did not manage to reproduce the issue after upgrade from PS1.6.1.24 to PS1.7.5.1 using the 1-click upgrade v4.8.0.
Here's my log file
[log.txt](https://github.com/PrestaShop/PrestaShop/files/3350012/log.txt)

I tried also with the 1-click upgrade from PS1.6.1.24 to PS1.7.6.0.rc1 => OK => no warnings.

Thanks!

**Comment by ballashop** [comment] 2019-07-02 13:11
hi @khouloudbelguith 
I'll try again with PS 1.7.6.0.rc1 
I'll write back asap, thanks a lot.

**Comment by khouloudbelguith** [comment] 2019-07-02 13:14
@ballashop, thanks!
Waiting for your feedback.
You can use the channel "Local archive".

- install the autoupgrade module
- Download the zip of PrestaShop 1.7.6.0rc1
- Put it in the folder admin / autoupgrade / download
- in the configuration page of the module select "local archive" as a channel
- Specify the version to which we are upgrading (example: 1.7.6.0)
- Launch the upgrade

Thanks!
