### ISSUE TITLE
The Total in abandoned cart list is not correct in a multistore/multicurrency situation

### ISSUE THREAD

**Issue by gorkavidal** [PrestaShop/PrestaShop#15637] opened 2019-09-21 13:49 UTC
When you have a multistore with differents currencies, and you render the abandonded carts list, if you are in All shops context, the price is showed using the primary currency of the cart store, and the currency symbol is the currency used by the customer when he created the cart.

If you change the context to the store, then its ok.

**Comment by khouloudbelguith** [comment] 2019-09-23 10:22
Hi @gorkavidal,

I did not manage to reproduce the issue.
In the BO => Orders => Shopping carts => when All shops is selected 
The price displayed is correct => same in the FO calculated in the currency selected.
I attached a screen record
https://drive.google.com/file/d/10VlWcAGmou0Jc6u_5v8_0uI8vUFcJbjS/view
Thanks to check & feedback.

**Comment by gorkavidal** [comment] 2019-09-23 13:10
Hi @khouloudbelguith, 
You need to have two currencies in one of the shops. Then, make the cart in the secundary currency of the shop for example. I attached a screen record so you can see it

https://drive.google.com/file/d/1WE-Ktbc7iCJfH4I4unpfcCUIe6vmg_oi/view?usp=sharing

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-09-23 13:50
@gorkavidal, it is OK
https://drive.google.com/file/d/1nzbjOc2T0umlVcExNRAOxOiyQD-WCg7K/view
![image](https://user-images.githubusercontent.com/16067358/65431450-6ada1c00-de11-11e9-9ebd-2f8c0a43a7c3.png)
![image](https://user-images.githubusercontent.com/16067358/65431473-73325700-de11-11e9-8ac4-75a58fbbc0b5.png)

Thanks!

**Comment by gorkavidal** [comment] 2019-09-23 14:41
The primary currency in 1761 shop is TND? The issue is when the cart is not in the primary currency of the shop.

**Comment by khouloudbelguith** [comment] 2019-09-23 14:46
@gorkavidal, Yes!
It is TND.
The Eur is the default currency of the first shop & I tried with TND which is not the primary currency of the shop.
![image](https://user-images.githubusercontent.com/16067358/65435994-4f730f00-de19-11e9-9195-4126805faf58.png)

Thanks!

**Comment by gorkavidal** [comment] 2019-09-23 14:50
But in the 1761 shop, the primary currency has to be Euro, then do a cart in TND, and then there is the problem.

**Comment by khouloudbelguith** [comment] 2019-09-23 14:54
@gorkavidal, that's exactly what I have done.
![image](https://user-images.githubusercontent.com/16067358/65436709-767e1080-de1a-11e9-9e5e-a9a45135c90c.png)
But, there is no issue.

Thanks!

**Comment by gorkavidal** [comment] 2019-09-23 15:00
You place a new cart and is not issue? Ok thanks for all. I'll check why is happening.

**Comment by khouloudbelguith** [comment] 2019-09-23 15:02
@gorkavidal, yes!
It is OK.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-23 07:49
Hi @gorkavidal,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-23 07:49 UTC
Labels: Shopping carts, Multistore, Currencies, No change required
