### ISSUE TITLE
Category tree on product pages issue

### ISSUE THREAD

**Issue by Poutyty** [PrestaShop/PrestaShop#30527] opened 2022-12-07 18:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On product page the category tree always go back to home default tree

### Expected behavior

It is supposed to stay on the parent category of the product

### Steps to reproduce

1. Go to Category
2. click on one product

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

ps_categorytree

**Comment by paulnoelcholot** [comment] 2022-12-08 11:13
Hello @Poutyty,

I'm not sure I fully understand the problem, could you develop the step to reproduce? Does the problem concern the FO or the BO? On product page v1 or v2?

Thanks for your precisions.

**Comment by hibatallahAouadni** [comment] 2022-12-27 23:22
Hello @Poutyty 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-12-27 23:22 UTC
Labels: Bug, CO, Category tree, Invalid, Module, 1.7.8.7
