### ISSUE TITLE
Module manager list unorganized when connected to the addon marketplace

### ISSUE THREAD

**Issue by saradmi** [PrestaShop/PrestaShop#18909] opened 2020-04-30 10:39 UTC
#### Describe the bug

the modules in the "module manager" page are sorted by categories when I'm not connected to the addons marketplace, the moment i connect they become unsorted and are grouped in the categories "theme modules" and "other" only, every other category becomes empty, 3rd party and native modules,

#### Expected behavior

the module sorting shouldn't change when connected to the marketplace it didn't before,

#### Steps to Reproduce

1. Go to 'module manager'
2. Click on 'connect to the addon market place' next to install a module
3. Scroll down to the module list

**Screenshots**
when not connected
![when not connected](https://user-images.githubusercontent.com/63447753/80700468-1650fa80-8ade-11ea-8ac3-2bf1265efafc.png)

when connected no module in default categories
![connected empty category](https://user-images.githubusercontent.com/63447753/80700464-151fcd80-8ade-11ea-9720-95bce850fcfa.png)

when connected all modules go in those two categories
![connected new category sort](https://user-images.githubusercontent.com/63447753/80700467-1650fa80-8ade-11ea-89ef-0b2688c23bf8.png)

#### Additional information

* PrestaShop version:  1.7.6.5 /  1.7.6.4
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-04-30 11:48
Hi @saradmi , 
I managed to reproduce your issue on both 1.7.6.5 and 1.7.5.2.
Thanks for reporting the bug. I will let our team know !
Thanks !

**Comment by khouloudbelguith** [comment] 2021-07-09 16:12
Hi!

As discussed in Slack with Denis.
the steps to reproduce the issue:
1. In the BO > Modules > Module manager page > Try to connect to addons with an incorrect password
2. No error is displayed
3. Refresh the page => logged to addons: NOK

=> The connection "seems" OK, except that then when applying APIs Addons checked the password and since it is false => the API returns an error. And in this case, at the MBO level, it prevents me from making the other APIS calls. And suddenly nothing is displayed

We can't reproduce the issue with PS178 with this PR: https://github.com/PrestaShop/PrestaShop/pull/20774 as reported here: https://github.com/PrestaShop/PrestaShop/issues/9721

I will close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2021-07-09 16:12 UTC
Labels: Bug, Trivial, BO, Modules, Fixed, Module manager, 1.7.5.2, 1.7.6.5
