### ISSUE TITLE
Bug whit z index in mobile mode in backoffice

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#37201] opened 2024-10-21 08:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the last versions of prestashop, whit new installation and updates we get this problem whit the mobile menu, the z-index mark to 1999 instead of 1, attached video

https://github.com/user-attachments/assets/bbf3eeaa-7e09-4e33-aed4-62c16c4bc681

### Expected behavior

go back office click menu in mobile version and get a good menu, dont get the black screen instead

### Steps to reproduce

Go to back office
use for example the mobile mode of edge or a mobile
get black screen 

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-10-24 12:24
Hello @LinkOfLight ,

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/37081

I'm closing it to avoid clogging the backlog.

**Closed as completed by florine2623** 2024-10-24 12:24 UTC
Labels: Bug
