### ISSUE TITLE
Backoffice started loading very slow

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#26504] opened 2021-11-02 15:13 UTC
Hi,

I created a product with 38,416 (14 x 14 x 14 x 14) combinations in the back office.  After the creation, the back office takes more time to load each content. 

Is there a solution?

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

Regards,
Gaja

**Comment by florine2623** [comment] 2021-11-02 15:26
Hello @Gaja-A ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19123.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by florine2623** [comment] 2021-11-02 15:26
Duplicate of #19123

**Closed as completed by florine2623** 2021-11-02 15:26 UTC
Labels: Duplicate, Invalid
