### ISSUE TITLE
No "Most Searched" on dashproducts in the dashboard

### ISSUE THREAD

**Issue by psydomin** [PrestaShop/PrestaShop#11728] opened 2018-12-11 23:19 UTC
**Describe the bug**
On the BO I get no results on the tab for "Most Searched" on the dashproducts panel

**To Reproduce**
1. Go to the BO dashboard
2. Click on "Most Searched" on the dashproducts panel
3. The table is empty

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/12779551/49836415-7389c600-fd9a-11e8-8a0d-dc77dd6e51e7.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.30
No errors shown with debug mode
No errors on the error log that seem related

**Comment by khouloudbelguith** [comment] 2018-12-12 08:25
Hi @psydomin,

I did not manage to reproduce the issue with PS1.7.5.0rc1 & PS1.7.4.0.
Could you please try to uninstall the dashproducts module, remove the folder dashproducts into the path Project_Folder/modules/dashproducts, clear cache, and try to install it again.
![image](https://user-images.githubusercontent.com/16067358/49856355-df4a4e00-fdef-11e8-9fe8-0e20555e5133.png)
Thanks to check & feedback.

**Comment by psydomin** [comment] 2018-12-12 14:04
> Hi @psydomin,
> 
> I did not manage to reproduce the issue with PS1.7.5.0rc1 & PS1.7.4.0.
> Could you please try to uninstall the dashproducts module, remove the folder dashproducts into the path Project_Folder/modules/dashproducts, clear cache, and try to install it again.
> ![image](https://user-images.githubusercontent.com/16067358/49856355-df4a4e00-fdef-11e8-9fe8-0e20555e5133.png)
> Thanks to check & feedback.

Did as you said. Still no result show but now in the table there is an indication os "No results" which wasnt there previously:
![image](https://user-images.githubusercontent.com/12779551/49874510-91950c00-fe16-11e8-98e4-4a4908ac9818.png)

I did some searches on my website and even after that it shows "No results"

**Comment by khouloudbelguith** [comment] 2018-12-12 16:11
@psydomin, what is the exact version of the dashproducts module did you use?
Thanks!

**Comment by psydomin** [comment] 2018-12-12 16:27
@khouloudbelguith v2.0.4

**Comment by khouloudbelguith** [comment] 2018-12-12 16:51
@psydomin, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by psydomin** [comment] 2018-12-12 18:40
With debug mode on (or off, it still shows), the only error I get is this one:
![image](https://user-images.githubusercontent.com/12779551/49890447-fa42af80-fe3b-11e8-8449-b2c5a065951c.png)

I'm waiting for the host to send me the php error log because I dont have access to it.

error_log.log on root folder has nothing related, just a bunch of
`[12-Dec-2018 03:12:44 Europe/Lisbon] PHP Notice:  Undefined index: product in /home/vivumcom/public_html/var/cache/prod/smarty/compile/10/cf/4d/10cf4dc7e2850e11e202a7c38b754799ec195f28_2.file.header.tpl.php on line 71
[12-Dec-2018 03:12:44 Europe/Lisbon] PHP Notice:  Trying to get property of non-object in /home/vivumcom/public_html/var/cache/prod/smarty/compile/10/cf/4d/10cf4dc7e2850e11e202a7c38b754799ec195f28_2.file.header.tpl.php on line 71`
But they dont seem related because of the date

**Comment by psydomin** [comment] 2018-12-12 19:33
Problem solved. While reading the code I noticed a check for the "statsearch" module which wasnt instaled. After installing the module it works fine.

Perhaps there should be some kind of warning as this tab depends on another module (The Most viewed tab has this warning when the datamining module isnt installed)

**Comment by khouloudbelguith** [comment] 2018-12-13 07:56
Hi @psydomin,

Thanks for your feedback & for your fix.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-13 07:56 UTC
Labels: Bug, Minor, BO, Dashboard, Dashproducts, Fixed, 1.7.4.2
