### ISSUE TITLE
Problem adding new theme

### ISSUE THREAD

**Issue by mahdimedia** [PrestaShop/PrestaShop#14794] opened 2019-07-21 01:48 UTC
hello

after click on button "Add new theme"
i show msg 
"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."
![07KgWB](https://user-images.githubusercontent.com/2321818/61586008-c4ed0580-ab72-11e9-87f8-0b0f587fe49e.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-22 09:15
Hi @mahdimedia,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1_ti1q2hfDUROqgYymSTUf5UXmLM8yzDN/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-21 07:49
Hi @mahdimedia,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-21 07:49 UTC
Labels: Bug, BO, Theme & logo, No change required, 1.7.6.0
