### ISSUE TITLE
Arrows don't work for number types on firefox

### ISSUE THREAD

**Issue by JevgenijVisockij** [PrestaShop/PrestaShop#24515] opened 2021-05-16 13:02 UTC
#### Describe the bug

Can't click on arrows next to number type (for example "Display remaining quantities when the quantity is lower than" in product settings) in Firefox. IMO those arrows should not have padding on the right.
#### Expected behavior

You should be able to click on arrows next to number type fields on all supported browsers. The reason this doesn't work is because in Prestakit padding on both sides of all inputs ('`.form-control`) has been increased to 1 rem. And it seems on firefox the arrows stop working if there is too much padding on the right. So you need to lower padding on the right for `form-control[type="number"]` in order to make arrows work on firefox.

#### Steps to Reproduce

1. Go to Product Settings on firefox
2. Try to use arrows to increase "Display remaining quantities when the quantity is lower than" value.

**Screenshots**
![image](https://user-images.githubusercontent.com/47781757/118397974-3b6bc900-b65f-11eb-8e6d-fbd1c62583e3.png)
#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-05-17 09:27
Hello @JevgenijVisockij 

I didn't manage to reproduce your issue with develop on FireFox 78.8.0, see the attached screen record below:

https://www.awesomescreenshot.com/video/3765581?key=52a166daefef839ba20e6f2c99513299

Please check and feedback.
Thanks!

**Comment by JevgenijVisockij** [comment] 2021-05-17 10:02
Hmm tried to reproduce it on Firefox 78 as well and couldn't it. But I am still able to reproduce it on newest firefox(88). So maybe it's Firefox problem.

**Comment by hibatallahAouadni** [comment] 2021-05-17 10:29
Hello @JevgenijVisockij 

Yes indeed it seems to be Firefox problem (regression).
So, I close this issue as it's not a PS Core problem :wink: 

Thanks for your feedback!

**Closed as completed by hibatallahAouadni** 2021-05-17 10:29 UTC
Labels: Bug, develop, BO, Product settings, No change required, Front-end

**Comment by matks** [comment] 2021-05-17 11:14
> So, I close this issue as it's not a PS Core problem 😉

This is not sure 😅  if PrestaShop works with old versions of Firefox but not new versions of Firefox, that can be a big issue 😄  and Firefox is not going to modify something "so that it works for PrestaShop"

I think this issue needs to be explored. Maybe it's an issue of Firefox 88 and it will be fixed in higher versions of Firefox, but if does not, we have to do something.
