### ISSUE TITLE
address field "other" is not more shown in order PS 1.7.7.x

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#24169] opened 2021-04-22 18:36 UTC
#### Describe the bug

Have an order with an customer address with an entry in address field "other" and it is not more shown in the order in the addresses

#### Expected behavior

See entry from address field "other" in order at the addresses.

#### Steps to Reproduce

1. Have a customer address with an entry in the address field "other"
2. Have an order with this address
3. go to order and open it
4. See that field "other" is not more shown in address lines in order

#### Additional information

In my case the ebay module use this address field to identify ebay customers. So untill PS 1.7.6.9 I could see with one view that the order is made from a ebay customer. But this field is not more shown in orders from PS 1.7.7.x

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by florine2623** [comment] 2021-04-23 10:08
Hello @didi-2018 ,

Despite our efforts, we were not able to reproduce your issue with PS 1.7.7.X with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Please see my screenshots below :
![Capture d’écran 2021-04-23 à 12 07 09](https://user-images.githubusercontent.com/16019289/115856268-9299c780-a42c-11eb-875e-a7789581faaf.png)

![Capture d’écran 2021-04-23 à 12 07 45](https://user-images.githubusercontent.com/16019289/115856285-96c5e500-a42c-11eb-9e05-882718421497.png)

![Capture d’écran 2021-04-23 à 12 07 15](https://user-images.githubusercontent.com/16019289/115856277-94638b00-a42c-11eb-9776-acb7db6a5599.png)

We will close this issue.

**Closed as completed by florine2623** 2021-04-23 10:08 UTC
Labels: Can't reproduce

**Comment by didi-2018** [comment] 2021-04-23 18:49
@florine2623 your screenshot is not a screenshot from an order! Please check it in your order section in backoffice. I don´t know from where your screenshot comes? But is not from into the order. 

![image](https://user-images.githubusercontent.com/44971218/115916215-c8629e80-a474-11eb-9ac2-221fbe0ec010.png)

**THIS** is a screenshot out of an order from PS 1.7.7.x: 

![image](https://user-images.githubusercontent.com/44971218/115916592-49219a80-a475-11eb-9710-d218631117bb.png)


**Screenshot from 1.7.6.9**

![image](https://user-images.githubusercontent.com/44971218/115956454-086d6400-a4fd-11eb-8341-6117ac76d4bd.png)

**Comment by didi-2018** [comment] 2021-06-28 10:08
Hello @florine2623,

I beged you 2 month ago to check again, cause your Screenshot is not from one 1.7.7x version. Please check again. Thank you!
