### ISSUE TITLE
Strange values in ps_address vat_number column

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#25531] opened 2021-08-05 20:25 UTC
#### Describe the bug

From time to time some of the users stores in database inappropriate vat number values
The reason why it happens is unknown to me, but maybe there are people aware of that behaviour.

Example values are like "Not US, nor Canada citizen", or "--- chose ---" or other province name which are not vat numbers at all.

#### Expected behavior

The vat number should not be (I guess?) autofilled (?) from other source

I have already added `autocomplete="off"` on page load using JS, but this didnt help

#### Steps to Reproduce

Dunno, depends on end user and his browser history / cookies I guess.

Unknown

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by khouloudbelguith** [comment] 2021-08-06 08:53
Hi @ProteanCode,

Thanks for your report.
Isn't the same issue displayed here?
![image](https://user-images.githubusercontent.com/16067358/128484600-64783c6f-fd82-4fbb-9080-4790cc2576ad.png)


Thanks!

**Comment by ProteanCode** [comment] 2021-08-06 14:27
> Hi @ProteanCode,
> 
> Thanks for your report.
> Isn't the same issue displayed here?
> ![image](https://user-images.githubusercontent.com/16067358/128484600-64783c6f-fd82-4fbb-9080-4790cc2576ad.png)
> 
> Thanks!

No. The values I have looks like fetched from some dropdown list, but I do not understand how it is possible

**Comment by khouloudbelguith** [comment] 2021-08-06 15:27
@ProteanCode, could you please provide me a screenshot about your issue?

Thanks!

**Comment by ProteanCode** [comment] 2021-08-06 18:22
![vat_number](https://user-images.githubusercontent.com/43477801/128554523-7c42262d-b61e-4228-8a87-cb3ef477e6c5.png)

These values are not valid vat numbers, these are provinces of Poland. The "Wybierz" value is just a translation for "Choose"

No idea why. This somehow happens also on my other shops, but its far less common

**Comment by hibatallahAouadni** [comment] 2021-08-17 16:37
Hello @ProteanCode 

Could you please provide clear and consice steps to reproduce the issue :pray: 
Cause I didn't manage to reproduce the issue with provided infos.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-06 11:22
Hello @ProteanCode 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-09-06 11:22 UTC
Labels: Bug, FO, Addresses, No change required, 1.7.7.0
