### ISSUE TITLE
Thumbnails are not generated for image with wrong extension

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#21059] opened 2020-09-18 12:27 UTC
#### Describe the bug

- Our employee managed to create an image that is a PNG, but has JPG extension. I don't know which phone or software did it, does not matter.
- He uploaded them to a product.
- When you go to FO, the thumbnails are not generated and the thumbnail URLs throw 404.
- When I go to a directory with this image (/www/img/p/1/0/7/2/2/7), the **filetype** file contains **png**.
- When I delete the **filetype** file and go to FO again, the thumbnails regenerate automatically.

#### Test image
[https://www.trendo.cz/img/p/1/0/7/2/2/7/107227.jpg](https://www.trendo.cz/img/p/1/0/7/2/2/7/107227.jpg)
#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-09-18 12:49
Hi @Hlavtox ,
Following your steps and using the image provided, i couldn't reproduce the issue.
Am I forgetting something ?
![Capture d’écran 2020-09-18 à 14 45 26](https://user-images.githubusercontent.com/16019289/93598871-9c9ea800-f9bd-11ea-84c3-ce3d77a5874d.png)
![Capture d’écran 2020-09-18 à 14 44 36](https://user-images.githubusercontent.com/16019289/93598880-a0322f00-f9bd-11ea-874f-bc71d44df0ba.png)
The filetype is also png in my case.
Please let me know

**Comment by khouloudbelguith** [comment] 2020-10-12 11:57
Hi @Hlavtox,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-12 11:57 UTC
Labels: No change required, 1.7.6.2
