### ISSUE TITLE
Can't create webservice specific management classes for modules

### ISSUE THREAD

**Issue by elboletaire** [PrestaShop/PrestaShop#19182] opened 2020-05-18 13:11 UTC
#### Describe the bug

Thanks to the new hook added in #5531, we can now define custom webservice endpoints for our modules, but there's a caveat: if you want to use a custom management class for your service, you won't be able to place it in your module folder, [due to how this class is being called in `WebserviceRequest.php`](https://github.com/PrestaShop/PrestaShop/blob/849d82a2a8d7c206f1da3ac068326e772f2e733a/classes/webservice/WebserviceRequest.php#L608):

~~~php
<?php
// line ~ 608
// if the management is specific
$specificObjectName = 'WebserviceSpecificManagement' . ucfirst(Tools::toCamelCase($this->urlSegment[0]));
if (!class_exists($specificObjectName)) {
    $this->setError(501, sprintf('The specific management class is not implemented for the "%s" entity.', $this->urlSegment[0]), 124);
}
~~~

I may be missing something, but I've tried naming my class that way and placing it everywhere (even under overrides paths) with no result. 

#### Expected behavior

To be able to load our webservice modifiers from within our module's path.

#### Steps to Reproduce

1. Create a module and, in the install() method, ensure you register the `addWebserviceResources` hook.
2. Define `hookAddWebserviceResources` in your module setting `specific_management` to `true`.
3. Try to load your specific management class from within your module path (don't forget to `composer dumpautoload`).
4. Now make a call to your implemented method, you'll receive an error like so: `The specific management class is not implemented for the "your_webservice_resource"`.

#### Additional information

* PrestaShop version: >= 1.7
* PHP version: Doesn't matter.

#### Workaround a.k.a. possible fix.

I've fixed this by just modifying the above mentioned line searching for a `specific_management_class` field, where I define my namespaced management class:

~~~php
<?php
public function hookAddWebserviceResources($resources = [])
{
  return [
    'proper_api_login' => [
      'description' => 'Proper API Login',
      'specific_management' => true,
// definition of custom management class
      'specific_management_class' => 'ElBoletaire\ProperAPIAuth\Service\ProperApiLogin',
    ]
  ];
}
~~~

And just adding this to `WebserviceRequest.php`:

~~~diff
585a586,589
>                     if (isset($this->resourceList[$this->urlSegment[0]]['specific_management_class'])) {
>                         $specificObjectName = $this->resourceList[$this->urlSegment[0]]['specific_management_class'];
>                     }
> 
~~~

Please correct me if I'm wrong in any of these statements and, if there are no problems with them, I'll gladly make a PR to add these three new lines.

**Comment by sarahdib** [comment] 2020-05-19 08:25
@PrestaShop/prestashop-core-developers can you check this issue :) ?

**Comment by elboletaire** [comment] 2020-05-20 19:07
Now I'm realizing that, maybe, instead of the new param that I've added, the already existing `class` param could be used, as it's not being used as long as you define the `custom_management` to  `true`.

**Comment by smoucka** [comment] 2020-07-11 14:42
Was there any solution to this issue? I'm having the same problem when trying to extend the webservice using the WebserviceSpecificManagement functionality. This feature is clearly intended for this use case but I cannot figure out how to have PrestaShop recognize my class that manages this custom endpoint.

**Comment by elboletaire** [comment] 2020-07-11 14:45
@smoucka the way to make it work without touching the core code is by including (via `require_once`) your `WebserviceSpecificManagement` file in your plugin's main file.

**Comment by smoucka** [comment] 2020-07-11 14:54
@elboletaire Perfect, thank you.

**Comment by smoucka** [comment] 2020-07-11 15:39
@elboletaire Did this issue return for you? After including the WebserviceSpecificManagement file in my main module file I got some Fatal errors like:
```
Fatal error: Declaration of MyModule\Classes\Webservice\WebserviceSpecificManagementMyModule::
setObjectOutput(MyModule\Classes\Webservice\WebserviceOutputBuilderCore
$obj) must be compatible with WebserviceSpecificManagementInterface::
setObjectOutput(WebserviceOutputBuilderCore $obj) in
.../modules/mymodule/classes/webservice/WebserviceSpecificManagementMyModule.php on line 9
```

Took care of these errors by importing those two classes (WebserviceOutputBuilderCore and WebserviceRequestCore, I had these both type hinted in the method definitions) however now I get the same response from WebserviceRequest returning a 501 saying the management class is not implemented. Did you encounter something similar?

**Comment by smoucka** [comment] 2020-07-11 15:44
It was a namespacing issue. I removed the namespace from my WebserviceSpecificManagementMyModule file and this resolved the problem.

**Comment by elboletaire** [comment] 2020-07-27 18:48
When I did open this issue, I didn't know that the `overrides` folder in modules is managed during the module installation. So, I guess it should also work adding the class there (without any namespace at all, of course) and installing the module from the dashboard, as the installation should copy the `overrides/classes` from the module path to the root `overrides/classes`. 

Haven't tried it though.

**Comment by phuthoma** [comment] 2020-10-20 12:42
Clearing the cache (class_index.php) solved the issue in my case...

**Comment by PierreRambaud** [comment] 2020-11-24 14:13
Hi everyone,
COuld you provide us a module in order to reproduce the problem?

**Comment by elboletaire** [comment] 2020-11-24 16:19
I won't be able to do so during some weeks, but you can follow the steps described in the issue. Shouldn't be too hard.

**Comment by PierreRambaud** [comment] 2020-11-25 08:47
> I won't be able to do so during some weeks, but you can follow the steps described in the issue. Shouldn't be too hard.

It's not about complexity, but time, we have a lot of things to do, and can't create modules/themes each time someone had a bug, this is why we need a quick example to be able to reproduce easily and quickly :)

**Comment by hibatallahAouadni** [comment] 2020-12-16 15:17
Hello @elboletaire ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-16 15:17 UTC
Labels: Bug, WS, Webservice, No change required

**Comment by elboletaire** [comment] 2020-12-16 15:59
Good thing I warned about availability 🙄 

It's really disappointing to see you closing an issue which has been confirmed by other users because you "don't have the time to test it by yourself", having the issue perfectly described and a solution already coded in it.

**Comment by hibatallahAouadni** [comment] 2020-12-16 16:58
Hello @elboletaire 

>  we need a quick example to be able to reproduce easily and quickly

As @PierreRambaud mentionned above, we need your help to reproduce the issue, so we can fix it :wink:

> having the issue perfectly described and a solution already coded in it.

It will be nice if you can create a PR, but we need to reproduce the issue before :wink: 
So, we need your help. 
 
Thanks!

**Comment by elboletaire** [comment] 2020-12-17 11:11
Sincerely? I'm not gonna do shit, apart from unsubscribe of this issue.

It's a complete non-sense to close this issue, which is properly explained (and with a fix), when you have issues that have not been updated in more than 2 years.

But hey, this one is "cluttering up your backlog"...
