### ISSUE TITLE
Stock management : The attribute name is splitted if contains a dash

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#22786] opened 2021-01-12 10:53 UTC
#### Describe the bug

On the stock management page, the product attribute value is splitted when there is a dash in the attribute.
For example, it will display 82 instead of 82-95mm. It is probably because there is a split with the dash -
The issue is applying on both Attribute name and attribute value.

#### Expected behavior
Display the full attribute value

#### Steps to Reproduce

1. Add a product with combination and with a dash in the attribute name OR value
2. Click on Catalog -> Stock
3. See the wrong attribute name display

**Screenshots**

![image](https://user-images.githubusercontent.com/1193727/104304804-2540d700-54cc-11eb-9376-2956731021ad.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-01-12 17:00
Hello @arirangz 

Thanks for your issue. I managed to repdoruce your issue with PS1.7.6.9, PS1.7.7.0 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1pBpCmBI0n-3CWeB-oyhP_FOf77_FqYz8/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by kpodemski** [comment] 2021-06-04 18:25
I can't reproduce it on `develop`

cc @hibatallahAouadni

**Comment by hibatallahAouadni** [comment] 2021-06-04 23:53
Thanks @kpodemski  for checking it :rocket: 
Yes, it has been fixed on develop & on 1.7.8.x

![image](https://user-images.githubusercontent.com/23308427/120872763-e527e100-c59f-11eb-83d3-f4bf61c7d0e0.png)

So, I close the issue.

**Closed as completed by hibatallahAouadni** 2021-06-04 23:53 UTC
Labels: Bug, BO, Attributes, Stocks, Combinations, Fixed, 1.7.7.0, 1.7.6.9, 1.7.7.1
