### ISSUE TITLE
No product importation

### ISSUE THREAD

**Issue by Marquis7373** [PrestaShop/PrestaShop#28525] opened 2022-05-18 11:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I am trying to import 1 product with attached file. I matched the columns, the IDs shown for the categories, supplier, etc... do exist. When I launch the import everything works fine, I receive confirmation by email but in the catalog I don't see my new product created. No errors, nothing in the log.

When I try with a file with 1 column and 1 line (just product's name), nothing too.

Do you have an idea ?

Thank you 

### Expected behavior

I want to create product with file import.

### Steps to reproduce

1. Advanced setting > import 
2. select products type, french langage, ; and , separators, and "no" for all options without "notification by email"
3. upload this file [products_import 2(1)(1).csv](https://github.com/PrestaShop/PrestaShop/files/8715658/products_import.2.1.1.csv)
4. map the filed and column
5. click on Import

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.29

**Comment by hibatallahAouadni** [comment] 2022-05-18 17:48
Hello @Marquis7373 

I didn't manage to reproduce the issue with PS1786, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/169108843-91652cfd-2bf9-4242-9d1b-75021ba6461e.mp4

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-06-07 16:19
Hello @Marquis7373 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-06-07 16:19 UTC
Labels: Bug, BO, Import / Export, Invalid, 1.7.8.6
