### ISSUE TITLE
copy a product without images

### ISSUE THREAD

**Issue by shikotakcom** [PrestaShop/PrestaShop#20610] opened 2020-08-17 13:27 UTC
we had an option in Prestashop 1.6 that we can select copy a product without images. Please add this option to Prestashop 1.7 too.
Thank you

**Comment by khouloudbelguith** [comment] 2020-08-17 13:48
Hi @shikotakcom,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13397
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-17 13:48
Duplicate of #13397

**Closed as completed by khouloudbelguith** 2020-08-17 13:48 UTC
Labels: Duplicate
