### ISSUE TITLE
Payment Module fire postProcess twice (random)

### ISSUE THREAD

**Issue by Partenopeo83** [PrestaShop/PrestaShop#12073] opened 2019-01-08 16:38 UTC
Hi, 
i have a strange issue with my custom paymentmodule, i don't know if a problem of PS or my.
I have create for my PS 1.7.4.2 a paymentmodule same documentation specification. But random, i can't reproduce the issue, the order with this method are duplicate. Same customer, same products in the same time. Differences are id order and reference.
Apparently, the function postProcess() in payment module fire twice contemporary.

Someone had this same issue?

Thanks

PrestaShop version: 1.7.4.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-01-08 16:43
Hi @Partenopeo83,

Have the same issue with this ticket: #11487?
Thanks!

**Comment by Partenopeo83** [comment] 2019-01-08 16:58
Hi,
yes is the same thing but not with paypal but with my payment module. customer, product and cart is the same change only id and reference

**Comment by khouloudbelguith** [comment] 2019-01-08 17:04
@Partenopeo83, Could you please provide me your custom module to test with it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-09 11:20
Hi @Partenopeo83,

Thanks for the module.
I tried with PS1.7.5.0, but I have an error with your module in the order confirmation page.
I attached a video record.
https://drive.google.com/file/d/1GfdBVNsAhuaUhftEgEuD_l2MuJuXp1Xp/view
Thanks to check & feedback.

**Comment by DiegoCiccarelli** [comment] 2019-01-17 13:56
Hi @Partenopeo83,
I have the same error, you could
find the solution?
thanks

**Comment by khouloudbelguith** [comment] 2019-02-11 11:30
Hi @chicha78,

Did you use also a custom module?
What the exact name of this module?
Thanks!

**Comment by DiegoCiccarelli** [comment] 2019-02-11 12:05
Hi @khouloudbelguith I'm using the official module of Mercadopago V1.1.1 for Argentina, however I already solve the problem by limiting some forms of payment within the module, it's a module bug, they confirmed it from the support.

**Comment by khouloudbelguith** [comment] 2019-02-11 13:12
Hi @chicha78,

Thanks for your feedback.
I'll close the issue, since it is not a bug in the core PrestaShop.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-11 13:12 UTC
Labels: Payment methods, No change required, 1.7.4.2
