### ISSUE TITLE
Multistore - We cannot scroll in the modal "Add new product" to disable multistore

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#30201] opened 2022-11-03 12:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reported previously here
https://github.com/PrestaShop/PrestaShop/pull/30065#pullrequestreview-1160322870
Multistore - We cannot scroll in the modal "Add new product" to disable multistore

### Expected behavior

Ping @PrestaShop/product-team what do you think?

### Steps to reproduce

**Case1**
1. Go to BO > Shop Parameters > General page 
2. Enable multistore
3. Create a new shop & configure it
4. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Multi store
5. Select all shops in the header
6. Click on "Quick access" > Add a new product
7. An alert `"This page is only compatible in a single store context. To access the page, please select a store or "disable the multistore feature"` is displayed
![image](https://user-images.githubusercontent.com/16067358/198681949-bdc98e2e-9bdd-4b02-8f5d-a9a8300a0bfc.png)
8. Click on the "disable the multistore feature" link
9. See error the General page is displayed in the modal & we cannot scroll to disable multistore

I attached a screen record

https://user-images.githubusercontent.com/16067358/198682515-342ed412-7ab2-4d26-acba-907a356fc295.mp4
 => reproduced only with **develop** branch

**Case2**
1. Go to BO > Shop Parameters > General page 
2. Enable multistore
3. Create a new shop & configure it
4. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Multi store
5. Select all shops in the header
6. Go to BO > Catalog > Products page V2 and click on "Add a new product"
7. An alert `"This page is only compatible in a single store context. To access the page, please select a store or "disable the multistore feature"` is displayed
![image](https://user-images.githubusercontent.com/16067358/198681949-bdc98e2e-9bdd-4b02-8f5d-a9a8300a0bfc.png)
8. Click on the "disable the multistore feature" link
9. See error the General page is displayed in the modal & we cannot scroll to disable multistore

=> reproduced with 8.0.0 & develop branch

### PrestaShop version(s) where the bug happened

8.0.0, develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2022-11-07 16:26
Hello @khouloudbelguith ,

I tested on PS 8.0.x and PHP 7.4, I can't reproduce your issue:

https://user-images.githubusercontent.com/16019289/200362316-3836b39e-cd6b-4440-9503-0520e08f0bb5.mov

Is the issue only present when using PHP 8.1?

Thanks! ^^

**Comment by HanaRebaiQA** [comment] 2022-11-11 09:58
Hello @khouloudbelguith 

Thanks for your report.
I was able to reproduce your issue on **PS8.0.0** with **php 8.1**.

I'll add this to the debug backlog so that it's fixed.

![image](https://user-images.githubusercontent.com/92912932/201315811-8e3cec9e-15d3-4f4a-be88-95c38c93ef6c.png)

https://user-images.githubusercontent.com/92912932/201315633-e74dcce1-4769-4f56-9d67-0f92ca96a0ef.mp4

Thank You!

**Comment by matks** [comment] 2022-11-17 14:01
Fixed by https://github.com/PrestaShop/PrestaShop/pull/27712

**Closed as completed** 2022-11-17 14:00 UTC
Labels: Bug, Minor, BO, Multistore, Regression, PR available, Verified, 8.0.0
