### ISSUE TITLE
Currency sign wrong PS1.7.4.2

### ISSUE THREAD

**Issue by peranderssjostrom** [PrestaShop/PrestaShop#10235] opened 2018-09-02 08:44 UTC
In the drop down menu for currency select i have:

EUR €
USD $
SEK kr 

Why do I get SEK instead of kr?

If I choose EUR the the € is shown.

![5b881c5d8a78e_skrmavbild2018-08-30kl_18_25_33 png 5e6f8469ee454f76097853718037fc6f](https://user-images.githubusercontent.com/42907000/44954023-a7507800-ae9c-11e8-932c-c7de87221922.png)
![skarmavbild 2018-09-02 kl 10 41 20](https://user-images.githubusercontent.com/42907000/44954028-d49d2600-ae9c-11e8-848e-aee282bce8db.png)

In using the default theme.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.9
http://sjostromaudio.net

**Comment by khouloudbelguith** [comment] 2018-09-03 07:23
Hi @peranderssjostrom,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9714
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-03 07:23
Duplicate of #9714

**Closed as completed by khouloudbelguith** 2018-09-03 07:23 UTC
Labels: Duplicate
