### ISSUE TITLE
https bug

### ISSUE THREAD

**Issue by Noido** [PrestaShop/PrestaShop#14482] opened 2019-07-04 12:02 UTC
Hi i have a problem in http no problem but in https problem

I create a menu link https://mysite.com/connexion?back=my-account&type=seller
in navbar i got my menu with good link but when i click i am redirige to 
https://mysite.com/connexion?back=my-account

So its a problem But in http no problem he go to 

http://mysite.com/connexion?back=my-account&type=seller

Can you help me thanks

**Comment by khouloudbelguith** [comment] 2019-07-04 14:13
Hi @Noido,

I did not manage to reproduce the issue with PS1.7.6.0rc1.
I attached a screen record
https://drive.google.com/file/d/1LzR5uxoM10VcM2jZek7zHQxkaxMQcyMo/view
Thanks to check & feedback.

**Comment by Noido** [comment] 2019-07-04 14:17
Hi hum, i see, i m in 1.7.5.2 . It s a problem ?

**Comment by khouloudbelguith** [comment] 2019-07-04 15:28
@Noido, I tried with PS1.7.5.2 & it is OK.
I attached a screen record
https://drive.google.com/file/d/1sd86MSQSv9XvkLhWNjnSy_Td0uQbQWlG/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-08-05 07:27
Hi @Noido,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-05 07:27 UTC
Labels: Bug, FO, Mainmenu, No change required
