### ISSUE TITLE
Error uploading photos in products

### ISSUE THREAD

**Issue by AntonioManta** [PrestaShop/PrestaShop#12114] opened 2019-01-10 16:08 UTC
After upgrading to version 1.7.5 with autoupgrade, when I try to load an image in the product section: I get the error 500.

**Comment by khouloudbelguith** [comment] 2019-01-10 16:16
Hi @AntonioManta,

Isn't the same issue, reported here: #11939?
Thanks!

**Comment by AntonioManta** [comment] 2019-01-10 16:19
It is the same problem

**Comment by khouloudbelguith** [comment] 2019-01-10 16:22
@AntonioManta, Your ticket is a duplicate of #11939
So, I close it, you need to follow #11939
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-10 16:22
Duplicate of #11939

**Closed as completed by khouloudbelguith** 2019-01-10 16:22 UTC
Labels: BO, Duplicate, Image, 1.7.5.0

**Comment by AntonioManta** [comment] 2019-01-10 16:25
![1](https://user-images.githubusercontent.com/46569923/50982104-ba372100-14fc-11e9-945f-7b5a5a4ecbf3.jpg)
![2](https://user-images.githubusercontent.com/46569923/50982105-ba372100-14fc-11e9-8fb1-cf1e9ba4b8ca.jpg)
![3](https://user-images.githubusercontent.com/46569923/50982106-bacfb780-14fc-11e9-80b3-5bf9c18d96d7.jpg)
![4](https://user-images.githubusercontent.com/46569923/50982107-bacfb780-14fc-11e9-8a7d-37a9c4c5ebff.jpg)

**Comment by AntonioManta** [comment] 2019-01-10 16:27
But how can I solve the problem?
