### ISSUE TITLE
1.7.4.4 multistore individually associated store categories showing on all stores

### ISSUE THREAD

**Issue by Dan-Orchard** [PrestaShop/PrestaShop#11839] opened 2018-12-19 09:39 UTC
**Describe the bug**
When creating a multistore eg. 2 store (two seperate groups or two stores in one group - both are bugged) categories appear on both stores.

**To Reproduce**
Enable multistore
Create another group and store / or new store in same group - leave sharing details as default
Add a category and associate with one store
Go to url of category in associated store - Category will show as expected
Change url to other store (where category is not associated)
Category will show instead of "category not found" or something similar

**Additional information**
PrestaShop version: 1.7.4.4, 1.7.5
PHP version: 7.0, 7.2

**Comment by khouloudbelguith** [comment] 2018-12-19 09:53
Hi @Dan-Orchard,

Thanks for your report.
Have you the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9606
Thanks!

**Comment by Dan-Orchard** [comment] 2018-12-19 10:15
Hi @khouloudbelguith 

Yes, looks to be the same issue as #9606 

Do we have any update on the status of this bug? (Initial report was ~6 months ago)

Thanks

**Comment by khouloudbelguith** [comment] 2018-12-19 10:17
@Dan-Orchard,

Sorry, it is not fixed yet.
But it is added to our bug roadmap.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-19 10:17
Duplicate of #9606

**Closed as completed by khouloudbelguith** 2018-12-19 10:17 UTC
Labels: Duplicate, Categories, Multistore
