### ISSUE TITLE
Link::getModuleLink in a Multistore context

### ISSUE THREAD

**Issue by manfield** [PrestaShop/PrestaShop#24641] opened 2021-05-25 08:00 UTC
#### Describe the bug

In a multistore context, when using subfolder instead of subdomain to separate stores,
Link::getModuleLink
returns the module URL with the subfolder in path (and this is not mapped to the proper controller)

#### Expected behavior

If we have two stores with these urls:

https://example.com/store1/
https://example.com/store2/

I'd expect that Link::getModuleLink returns 

https://example.com/module/modulename 
https://example.com/module/modulename 

respectively.

Instead 

https://example.com/store1/module/modulename 
https://example.com/store2/module/modulename 

are returned.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: every suitable

**Comment by hibatallahAouadni** [comment] 2021-05-26 05:27
Hello @manfield 

Could you please provide steps to reproduce the issue.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-15 08:18
Hello @manfield 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-15 08:18 UTC
Labels: Bug, FO, Modules, Multistore, SEO & URLs, No change required, 1.7.7.1
