### ISSUE TITLE
bug module transport

### ISSUE THREAD

**Issue by JohnCasa** [PrestaShop/PrestaShop#15543] opened 2019-09-15 14:33 UTC
![Capture](https://user-images.githubusercontent.com/55353949/64923061-9720e780-d7d6-11e9-8271-b817807ac876.PNG)

hello, my delivery configuration to skip, when i try to configure it i have this error message. How can I handle this? Thank you

**Comment by mariem-abid** [comment] 2019-09-16 08:27
Hi @JohnCasa,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JohnCasa** [comment] 2019-10-07 14:21
Hello,
The host is OVH,
PHP Version: 7.0.33
 there is a bug on the carrier, it was deleted alone and I can not put it
back.
cordially

Le lun. 16 sept. 2019 à 10:28, Mariem ABID <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2019-10-07 14:23
Hi @JohnCasa,

What is the exact PrestaShop version did you use?

Thanks!

**Comment by JohnCasa** [comment] 2019-10-07 14:25
1.7.5.2

Le lun. 7 oct. 2019 à 16:23, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2019-10-07 14:26
@JohnCasa, this carrier is created manually or via a custom module?

Thanks!

**Comment by JohnCasa** [comment] 2019-10-07 14:27
manually

Le lun. 7 oct. 2019 à 16:26, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2019-10-07 15:17
@JohnCasa, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by JohnCasa** [comment] 2019-10-07 15:58
Steps to follow to reproduce:
Go to Transport> Transporters.

1 - The carrier is always off
2 - When we enter the carrier and modify it we get this error message:
Error thrown: object Object
Status text: parsererror
 THANK YOU!

Le lun. 7 oct. 2019 à 17:18, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2019-10-07 16:03
@JohnCasa, I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
So, we need the debug mode report & the PHP error log file to find what's wrong.

Thanks!

**Comment by JohnCasa** [comment] 2019-10-07 19:44
where can I find this debug mode report and the PHP error log file
please

Le lun. 7 oct. 2019 à 18:03, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2019-10-08 08:26
@JohnCasa, Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/ (`Try to enable the Debug Mode` section & `Try to add log files` section)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-06 07:40
Hi @JohnCasa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-06 07:40 UTC
Labels: Bug, BO, Shipping, Carriers, No change required, 1.7.5.2
