### ISSUE TITLE
Address assigned existing address to new customer when creating account, Opcache issue ?

### ISSUE THREAD

**Issue by nemesistech** [PrestaShop/PrestaShop#30007] opened 2022-10-14 08:00 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We identify a strange bug when created a new customer account ; the order page is automatically assigning a address of a existing customer (when opcache is enabled).

On left screenshot, when opcache is enabled. 
On right screeshot, when it's disabled.

![image](https://user-images.githubusercontent.com/30386687/195793134-94e68bb2-445e-4a46-8460-ad6b2d74df30.png)

Cloudflare : disabled.
Overrides : Nothing special about Customer or Addresses.php

Do you have any idea of what is happening?

Regards,

### Expected behavior

When adding the product to cart and click on Order button, we have to create a new customer.
Then, it should ask to create a new address. 

### Steps to reproduce

1. Enable opcache
2. Open a private navigation
3. Add a product to Cart
4. Click on "Order" button
5. Create a new customer account

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.32

**Comment by hibatallahAouadni** [comment] 2022-10-17 18:29
Hello @nemesistech 

I didn't manage to reproduce the issue with the provided infos.
Could you please switch to the Classic theme and try to reproduce the issue :pray: 
Cause it may related to your theme. Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-11-04 09:51
Hello @nemesistech 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-11-04 09:51 UTC
Labels: Bug, FO, Customer, Addresses, Checkout, Invalid, 1.7.8.6

**Comment by nemesistech** [comment] 2022-11-05 14:55
Hello, it's working well with classic theme.
But with the theme I bought, I do have the issue, that's strange.
Any ideas?

Regards,

**Comment by nemesistech** [comment] 2022-11-07 23:22
Hello, issue solved.

When the table ps_customer is truncate, we also checked the table ps_addresses (wasn't empty). So, when creating a new customer, was using the id_customer of old one in ps_addresses.

Regards,

**Comment by kpodemski** [comment] 2022-11-08 06:59
@nemesistech it seems like an issue on your side, these two tables are related, and if you want to delete customer data, you should delete related record from the address table 👍
