### ISSUE TITLE
Some fields impossible to translate

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#23186] opened 2021-02-09 08:52 UTC
#### Describe the bug

Hello,

I wanted to translate some fields into German but it doesn't register. And when I translate the same field into another language, for example into Spanish, it works fine.

Can you help me please ?

Watch the video to better understand

Thanks
**Screenshots**

https://drive.google.com/file/d/1IolIxaXtZpHdwkS6354J_yrP5-BSFEOf/view

#### Additional information

* PrestaShop version: 1.7.6.0
* PHP version: 5.6

**Comment by hibatallahAouadni** [comment] 2021-02-09 09:38
Hello @ShaimyWinda 

I didn't manage to reproduce your issue with PS1.7.6.1, PS1.7.5.2 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1EJqnWsXhkzcneegZcTlzZFsd4lpPPMKc/view

Please check and feedback.
Thanks!

**Comment by ShaimyWinda** [comment] 2021-02-09 09:44
Hi @hibatallahAouadni,

can you try with this sentence please ? {l s=" Un rideau Séparateur de pièces pour créer deux pièces distinctes. Il est réversible et atténue les bruits jusqu’à -9Db. Également thermique et 100% occultant." d='Shop.Theme.Catalog'}

Thanks

**Comment by hibatallahAouadni** [comment] 2021-02-09 10:13
Hello @ShaimyWinda 

It won't work cause "%" and we are aware of this issue, it is already in our debug backlog. 
This issue is a duplicate of #23149. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-09 10:13
Duplicate of #23149

**Closed as completed by hibatallahAouadni** 2021-02-09 10:13 UTC
Labels: Bug, BO, Duplicate, Translations, 1.7.6.0
