### ISSUE TITLE
id stock available not creating id for all store in multishop and not deleting info when deleting product

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#24942] opened 2021-06-13 20:33 UTC
#### Describe the bug / request

We have recently migrated from 1.7.6 to 1.7.7 and I noticed that during this migration that for our multistore not every products has an id stock available. This mostly is for products that we entered back in 2013 - 2020 in older PrestaShop version. 

My expectation was that if you are in All shops mode and save a product, that PrestaShop would automatically create a id_stock available for the stores that do not have one and update the existing once. This is not the case. Now I don't know if this intentionally, but from my point, if you have to go in to every store individual, press save to create an id, this is very time consuming.

Secondly, what if a new store is created, will you have to go all products again for this store to create a new id stock available?

#### Expected behaviour

That for multistore in ALL shops mode, this would be automatically checked, created and updated if a product is missing an id for that store.

#### Steps to Reproduce

1. You will need to have multistore activated and check the database table id stock available 
2. See if every product id is linked to a store, if yes good, if not try to save the product in All shops. Is a new id created? Or do you need to go in to that specific store and save to get the id?
3. One way I have found a solution, it is to duplicate a product and then Prestashop will create an id for all stores, but the question remains, what would happen if a new store was added? will you have to go over one by one again?

**Screenshots**

As you can see, product 399 only creates an id for store 1 and 16, while  the other product 168.. created an id for all stores.

![Screenshot 2021-06-14 at 23 52 20](https://user-images.githubusercontent.com/46492443/121958592-8535f500-cd6c-11eb-9747-385b6f6d2f85.png)

![Screenshot 2021-06-14 at 23 51 42](https://user-images.githubusercontent.com/46492443/121958595-85ce8b80-cd6c-11eb-817a-434ca6d8e901.png)

#### Additional information

* PrestaShop version: 1.7.7.5

**Comment by hibatallahAouadni** [comment] 2021-06-14 06:41
Hello @01park 

Thanks for your issue. 
**You must follow the template to submit a complete bug report**.
So please edit your issue description providing all the infos (steps to reproduce, screenshots, ...) and then notify me.

Thanks!

**Comment by 01park** [comment] 2021-06-14 21:05
I update the original

**Comment by florine2623** [comment] 2021-06-23 14:11
Hello @01park ,

Thanks for updating the issue.
I do not have the same issue. Please check my .sql file of ps_stock_available table.
[ps_stock_available.sql.zip](https://github.com/PrestaShop/PrestaShop/files/6702457/ps_stock_available.sql.zip)

**Comment by 01park** [comment] 2021-07-06 13:13
When you delete an item, does  all date in id_stock_available also delete?

By me not. Even when I create a new product. After i delete this, all data stays in the database.

**Comment by florine2623** [comment] 2021-07-07 08:34
Hello @01park ,

In my multistore, I do have every products linked to my stores, ps_stock_available :
<img width="817" alt="Screenshot 2021-07-07 at 10 23 28" src="https://user-images.githubusercontent.com/16019289/124725842-7ecf0f00-df0d-11eb-8e86-b8bc3428a2dd.png">
If I delete a product, the product is deleted from ps_stock_available :
<img width="632" alt="Screenshot 2021-07-07 at 10 26 52" src="https://user-images.githubusercontent.com/16019289/124726246-df5e4c00-df0d-11eb-9f16-433c990b0127.png">

I'm adding some stock for my product id 6 in my shop1 :
<img width="1208" alt="Screenshot 2021-07-07 at 10 27 55" src="https://user-images.githubusercontent.com/16019289/124726470-146a9e80-df0e-11eb-8f79-fcf6d594c55c.png">
I refresh my database :
<img width="624" alt="Screenshot 2021-07-07 at 10 28 40" src="https://user-images.githubusercontent.com/16019289/124726580-2ba98c00-df0e-11eb-8b7c-e49dfdfea36e.png">

I go in All Shop context and I delete my product id 6 :
<img width="1218" alt="Screenshot 2021-07-07 at 10 30 14" src="https://user-images.githubusercontent.com/16019289/124726938-8511bb00-df0e-11eb-994b-110ab4a64a74.png">

I refresh my database, in ps_stock_available, I still see product id 6 with stock :
<img width="633" alt="Screenshot 2021-07-07 at 10 32 15" src="https://user-images.githubusercontent.com/16019289/124727054-a4a8e380-df0e-11eb-8909-1cee59ad3f5a.png">

Is that your issue ?

**Comment by 01park** [comment] 2021-07-07 08:43
Hi,

Yes, I have the same issue, but I don't know if this is normal behavior. From a logic point of view, I would expect this data to be removed, once you remove the product. 

And the same issue when updating a product. I would expect PS to check if there is already a stock id for each product, for each store and if missing to create one.

Then I have a second question, maybe you know the answer. In same db table there is a Colum out-of-stock. In my case some items have 2 and some 0. What does this colum represent, is this maybe the amount where Prestashop gives a signal to retailer to let them know item is nearly out of stock?

**Comment by khouloudbelguith** [comment] 2021-07-09 10:27
Hi @01park,

I have the same behavior as @florine2623 with PS1.7.7.5.
 First issue: id stock available not creating id for all store in multishop
1. If I create a product in **All shops** => id_stock_available is created in all shops
2. If I create a product in a specific shop => id_stock_available is created in the specific shop
3. If I create a new shop with import all data => id_stock_available will be created for each product in the shop2

=> So, there is no bug.

About the second issue: not deleting info when deleting product
I manage to reproduce the issue with PS1.7.7.5.
I delete a product in all shops but id_stock_availbale is not removed in shop2.
I think it is similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/16753
Is it? If yes, I will update the other issue to add the ps_stock_available table and close this issue
What do you think?

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-29 08:34
Hello @01park 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-29 08:34 UTC
Labels: Bug, BO, Stocks, Multistore, No change required, 1.7.7.3
