### ISSUE TITLE
Can't translate "Link Widget" menu link in BO

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#18388] opened 2020-03-31 13:06 UTC
#### Describe the bug

The link "Link Widget" available in Design ("Apparence" in FR) menu in BO seems not translatable.

#### Expected behavior

Get translation registred for "Link Widget".

#### Steps to Reproduce

1. Fresh install of PS 1.7.6.4 in French only (or maybe any language other than English) 
2. In International, update default language (to be sure)
3. Check Translation > BO > French and search "Link Widget" (found translation "Gestion des liens")
4. Clear cache and check Design/Apparence menu: "Link Widget" entry is not translated

**Screenshots**

![Capture d’écran de 2020-03-31 14-52-22](https://user-images.githubusercontent.com/7419525/78029551-1768fd80-7361-11ea-8fbe-8ee978703741.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-03-31 14:26
Hi @Klemart3D,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9893
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-03-31 14:27
Duplicate of #9893

**Closed as completed by khouloudbelguith** 2020-03-31 14:26 UTC
Labels: Duplicate
