### ISSUE TITLE
Error 500 if phone is required in the adresse.

### ISSUE THREAD

**Issue by smarzougui** [PrestaShop/PrestaShop#29885] opened 2022-10-05 13:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Senario:

Back office: In adress, change the phone number as required field.
Front office: Connect with a user with an empty adress phone number.
Select a product and pass an order
==> Error 500.

### Expected behavior

Need to handle this case

### Steps to reproduce

Senario:

Back office: In adress, change the phone number as required field.
Front office: Connect with a user with an empty adress phone number.
Select a product and pass an order
==> Error 500.

### PrestaShop version(s) where the bug happened

1.7.2.1

### PHP version(s) where the bug happened

PHP 7.0.33-0ubuntu0.16.04.16 (cli) ( NTS )

**Comment by sallemiines** [comment] 2022-10-06 10:48
Hello @smarzougui 

Thanks for your report.
Following your steps, I couldn't reproduce your issue !

The issue is fixed in the PS version 1.7.3.0.
Here is a PR: [#8435](https://github.com/PrestaShop/PrestaShop/pull/8435)
[#7975](https://github.com/PrestaShop/PrestaShop/pull/7975)
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by sallemiines** 2022-10-06 10:48 UTC
Labels: Bug, FO, Can't reproduce, Addresses
