### ISSUE TITLE
Wrong shipping when changing order in BO

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#23810] opened 2021-03-29 19:37 UTC
#### Describe the bug
When changing the product quantity in an order in the backoffice, and changing back the quantity to the previsous value, the total should be the same. But the shipping calculation is wrong.

See video link:
https://www.loom.com/share/aaafebe4bb4c4421824f291c11069525

I tried to changed the shipping method and put back the same shipping method and the shipping price is correct again.

#### Expected behavior

Price calculation should be correct

#### Steps to Reproduce

1. Go to a backoffice order
2. Change the quantity of a product
3. Put back the original quantity
4. See the total shipping is wrong

**Screenshots**
https://www.loom.com/share/aaafebe4bb4c4421824f291c11069525

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-03-30 07:31
Hello @arirangz 

Could you please provide a screenshot of your selected carrier (Shipping locations and costs):

![image](https://user-images.githubusercontent.com/23308427/112950512-aa867000-913a-11eb-9d91-8c6eaf62ebff.png)

Please check and feedback.
Thanks!

**Comment by arirangz** [comment] 2021-04-02 09:44
Hello,

Please find below the screenshot.

I am using Chronopost module which ask to have 1 euro in the price and the module calculate the shipping on checkout.

![image](https://user-images.githubusercontent.com/1193727/113404640-c8590c80-93a8-11eb-8dbd-bb13d1092623.png)

Thanks for your help

**Comment by florine2623** [comment] 2021-04-02 14:28
Hello @arirangz ,

I can't reproduce your issue in PS 1.7.6 : https://drive.google.com/file/d/1tag-cbDCOrnT_KTOQds_oHr_SgAq6d0u/view

What is the weight of the product ?
Does the range of weight change  when adding changing the quantity of product in order ?

**Comment by florine2623** [comment] 2021-04-16 09:41
Hello @arirangz ,
Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-04-16 09:41 UTC
Labels: Bug, BO, Can't reproduce, Order, Shipping, 1.7.6.5
