### ISSUE TITLE
VAT validation fails with Spanish VAT numbers

### ISSUE THREAD

**Issue by eggfriedrice** [PrestaShop/PrestaShop#18481] opened 2020-04-06 16:31 UTC
#### Describe the bug

A Spanish customer found they couldn't submit their VAT number, the site kept returning "VAT validation service unavailable". I found a working solution in the forums that I think should be merged into the module.

#### Expected behavior

Validation should pass for Spanish VAT numbers.

#### Steps to Reproduce

1. Install https://github.com/PrestaShop/vatnumber
2. Checkout as a customer
3. Add a Spanish VAT number using format ESQnnnnnnnB (I can provide a valid one privately)
4. See "VAT validation service unavailable" error

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: N/A

#### Fix
Per this forum page: https://www.prestashop.com/forums/topic/635018-solved-free-vatnumber-module-fixed-for-ps-1700-1724/

The fix is simply to change the URL of the VAT service:
```// vatnumber.php - I changed this url for fix too spanish vat numbers validation in line 159
//$url = 'http://ec.europa.eu/taxation_customs/vies/viesquer.do? ms='.urlencode($prefix).'&iso='.urlencode($prefix).'&vat='.urlencode($vat);
// Spanish VAT numbers fixed. Fix error message: 'VAT number validation service unavailable'
$url = 'http://ec.europa.eu/taxation_customs/vies/vatResponse.html?locale=EN&memberStateCode='.urlencode($prefix).'&number='.$vat.'&traderName=';
```

**Comment by khouloudbelguith** [comment] 2020-04-06 16:36
Hi @eggfriedrice,

The VATNumber native module in 1.7 is not released because it doesn't work.
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9884
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-06 16:37
Duplicate of #9884

**Closed as completed by khouloudbelguith** 2020-04-06 16:36 UTC
Labels: Duplicate
