### ISSUE TITLE
 Upgrade 1.7.6.9 to 1.7.7.0, BO and site inaccessible - FileLoaderLoadException: Expected to find class A but it was not found

### ISSUE THREAD

**Issue by CJH297** [PrestaShop/PrestaShop#22264] opened 2020-12-05 13:07 UTC
#### Describe the bug
I have a situation. Upgrade from 1.7.6.9 to 1.7.7.0, modules current, 1-click reports everything green. Upgrade forced on me to comply with php by hosting ...

#### Expected behavior
No error thrown after the upgrade

#### Steps to reproduce

1. Your shop must be **1.7.6.9**
2. **BO**>**IMPROVE**>**Modules**>**Module Catalog**
3. Install **1-click upgrade** module v4.11.0
4. **BO**>**IMPROVE**>**Modules**>**Module Manager**
5. Click on **Configure** button of **1-click upgrade** module
6. Upgrade your shop to **1.7.7.0**
7. See error

After this, both back office and website show blank white pages. 
Deleting cache and var did not help. 
Unfortunately, a good backup (I am convinced absolutely that both backup and database are good) did not restore the site to working status. 
BO unattainable, website shows partial home page only, with no other pages and missing images. 
Something must be interfering with the restore (which was completed by ntbackup module that reported fully restored, but nothing runs). 
I don't know enough to do more with this so ideas are welcome. At present, it's screwed everything.

#### Screenshots
```
Upgrade completed with errors reported (elided with xxxxxxxxx for path):

[INTERNAL] /xxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/xxxxxxxxxxxx/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/xxxxxxxxxxxxxxxx/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /homepages/36/d27743760/xxxxxxxxxxxxx/app/config/config.yml (which is being imported from "/xxxxxxxxxxx/app/config/config_prod.yml"). #0 

/xxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/homepages/36/d...', NULL, false, '/homepages/36/d...') #1 

/xxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/homepages/36/d...') #2 

/xxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/homepages/36/d...') #3 

/xxxxxxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/homepages/36/d...', NULL) #4

 /xxxxxxxxxxxxxxxxx/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/homepages/36/d...') #5 

/xxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 

/xxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 

/xxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 

/xxxxxxxxxxxxx/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 

/xxxxxxxxxxxxxxxxxxxxxxx/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 

/xxxxxxxxxxxxxxxxx/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 

/xxxxxxxxxxxxxxxxx/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 

/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

```
#### Additional informations
PrestaShop version: 1.7.6.9
PHP version: 7.2

_Originally posted by @CJH297 in https://github.com/PrestaShop/PrestaShop/issues/22248#issuecomment-739243523_

**Comment by matks** [comment] 2020-12-05 13:26
Hi @CJH297 what version of the autoupgrade module have you used?

**Comment by CJH297** [comment] 2020-12-05 13:36
Latest version 4.11.0, all modules checked and all were current and up to date before the upgrade was attempted

**Comment by jajarom** [comment] 2020-12-05 14:11
Same here!

[INTERNAL] /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/home/dual34/public_html/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/home/dual34/public_html/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /home/dual34/public_html/app/config/config.yml (which is being imported from "/home/dual34/public_html/app/config/config_prod.yml"). #0 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/home/dual34/pu...', NULL, false, '/home/dual34/pu...') #1 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/home/dual34/pu...') #2 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/home/dual34/pu...') #3 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/dual34/pu...', NULL) #4 /home/dual34/public_html/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/home/dual34/pu...') #5 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /home/dual34/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 /home/dual34/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /home/dual34/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /home/dual34/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /home/dual34/public_html/admin094lidvz5/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

**Comment by CJH297** [comment] 2020-12-05 20:09
I have a partial solution to the restore failure on my site. 1-click attempted to update from 1.7.6.9 to 1.7.7.0, and failed with the reported errors. A full restore failed to function. I worked out that some files or data entries in the database must have remained and were interfering. I restored to an empty folder and a new database and it worked. So, I am still unable to update (a requirement by the isp to a new php), but have a working site again. Anyone else spotting this might try the same solution if they have the same sort of problem.

**Comment by atomiix** [comment] 2020-12-07 15:24
@CJH297 It seems that you have a file named `index.php` in `src/PrestaShopBundle/Controller/Admin/` that [shouldn't be there](https://github.com/PrestaShop/PrestaShop/tree/1.7.7.x/src/PrestaShopBundle/Controller/Admin/Sell).

**Comment by CJH297** [comment] 2020-12-07 15:49
Thanks for taking a look at the message. I just checked and there is no file named index.php in that folder. If something is looking for a file there, is that not the problem ... but I am already in way out of my depth (reporting a failure to upgrade, knowing nothing about code). There is an index.php in ../Controller however (it is 0kb and has no content), but there is nothing of that name in ../Controller/Admin

If it makes a difference, this is a site that was installed clean at 1.7.6.7, then updated to .8 and then to .9, all without a hitch.

**Comment by PierreRambaud** [comment] 2020-12-07 15:54
@CJH297 It's because of autowiring, you need to remove this index.php file in your directory, it fails because of this.

**Comment by CJH297** [comment] 2020-12-07 15:57
You mean remove the index.php file in ../Controller ... yes? But I see there is the same file in a totally different installation, of 1.6.4.4 - 0kb file in the same place. So this file is being created consistently and isn't a 'stray' - it's in more than one shop like this (sorry, 'autowiring' means nothing to me; I'm just a user). It also means that file was there during two prior upgrades

**Comment by atomiix** [comment] 2020-12-09 17:04
@CJH297 There is no version 1.6.4.4 of PrestaShop 🤔  and there is no file `index.php` in the folder `src/` and its subfolders when you just installed PrestaShop 1.7+. Maybe a third-party module or something else added those `index.php` files?

**Comment by CJH297** [comment] 2020-12-09 17:35
My mistake with typing - I meant 1.7.4.4.  Sorry ... not being careful enough as I type. Could be a module, okay. But the shop did update correctly from 1.7.7 to .8 to .9, with this file there.

I am confused though. From my limited understanding, the path the file was expected to be in is \Controller\Admin\Sell\index but there is no such file there (and shouldn't be from what you suggest). But there is an xml file directing something to look there. I have not yet had time to try removing the index.php file and trying the upgrade again (it took me a long time before to run the backup files and I am wary of another failure). Would it not be better to stop the xml file from looking for something that does not exist? The file you suggest removing is in /controller not in /sell.

Or should I edit the xml as well as remove the php?

Thank you again for your replies - I don't really know what I am doing here.

**Comment by CJH297** [comment] 2020-12-09 18:18
I try to update what I wrote and perhaps be clearer why I am confused.

The first error says:

`/xxxxxxxxxxxxxxxxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/xxxxxxxxxxxx/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/xxxxxxxxxxxxxxxx/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /homepages/36/d27743760/xxxxxxxxxxxxx/app/config/config.yml (which is being imported from "/xxxxxxxxxxx/app/config/config_prod.yml"). #0`

So I think, but I really don't understand, that something looked for an entry in index.php in admin/sell/index.php but it was not found. There is no file there to find, so that is correct. But an index.php is in /admin ... so this isn't the file in the error? 

But you think if should not be there. But then, the yml files both are involved. I have looked in both and searched for the word 'index' but it is not there. 
So the error says that something in config_prod.yml is telling config.yml to look for index.php, which isn't there. But neither yml file contains that file name and the file is indeed not there.

So I am confused what I should try ...

**Comment by jajarom** [comment] 2020-12-18 08:56
I try now with a module and i have some new info, maybe someone can fix this update issue:

**Results:** - appear several times
```
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File prod removed
Migrating old setting file...
parameters file already exists!
Finished...
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File prod removed
[INTERNAL] /home/dual34/public_html/classes/PrestaShopAutoload.php line 287 - file_get_contents(/home/dual34/public_html/classes/order/OrderCarrier.php): failed to open stream: No such file or directory
Migrating old setting file...
parameters file already exists!
Finished...
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[SKIP] directory "/cache/smarty/cache/" does not exist and cannot be emptied.
[SKIP] directory "/cache/smarty/compile/" does not exist and cannot be emptied.
[CLEANING CACHE] File prod removed
[INTERNAL] /home/dual34/public_html/classes/PrestaShopAutoload.php line 282 - scandir(/home/dual34/public_html/classes/): failed to open dir: No such file or directory
[INTERNAL] /home/dual34/public_html/classes/PrestaShopAutoload.php line 282 - scandir(): (errno 2): No such file or directory
[INTERNAL] /home/dual34/public_html/classes/PrestaShopAutoload.php line 282 - Invalid argument supplied for foreach()
Migrating old setting file...
parameters file already exists!
Finished...

```
**ERROR LOG** - appear several times
```
[INTERNAL] /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/home/dual34/public_html/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/home/dual34/public_html/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /home/dual34/public_html/app/config/config.yml (which is being imported from "/home/dual34/public_html/app/config/config_prod.yml").
#0 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/home/dual34/pu...', NULL, false, '/home/dual34/pu...')
#1 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/home/dual34/pu...')
#2 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/home/dual34/pu...')
#3 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/dual34/pu...', NULL)
#4 /home/dual34/public_html/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/home/dual34/pu...')
#5 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader))
#6 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer()
#7 /home/dual34/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#8 /home/dual34/public_html/modules/ets_upgrade/classes/UpgradeTools/SymfonyAdapter(69): Symfony\Component\HttpKernel\Kernel->boot()
#9 /home/dual34/public_html/modules/ets_upgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(52): PrestaShop\Module\EtsAutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel()
#10 /home/dual34/public_html/modules/ets_upgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(90): PrestaShop\Module\EtsAutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants()
#11 /home/dual34/public_html/modules/ets_upgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(40): PrestaShop\Module\EtsAutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#12 /home/dual34/public_html/admin094lidvz5/ets_upgrade/ajax-upgradetab.php(75): PrestaShop\Module\EtsAutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run()
#13 {main}

[INTERNAL] /home/dual34/public_html/override/classes/Tools.php line 22 - Class 'ToolsCore' not found
[INTERNAL] /home/dual34/public_html/override/classes/Tools.php line 22 - Class 'ToolsCore' not found
```

**Comment by hibatallahAouadni** [comment] 2020-12-25 12:34
Hello @CJH297 

I just edit your issue description, could please confirm all the details and infos :wink: 
Please next time **follow the template that we offer to submit a complete bug report**. We need these details to reproduce your issue.

@jajarom do you still have the same issue like @CJH297 ?

Thanks!

**Comment by jajarom** [comment] 2020-12-27 07:02
> 
> 
> Hello @CJH297
> 
> I just edit your issue description, could please confirm all the details and infos 😉
> Please next time **follow the template that we offer to submit a complete bug report**. We need these details to reproduce your issue.
> 
> @jajarom do you still have the same issue like @CJH297 ?
> 
> Thanks!

Hi,

Yes

**Comment by CJH297** [comment] 2020-12-27 10:51
Sorry for the slow reply. I'm not used to the system, apologies also for not using the template - I have no knowledge of the software or coding, just coming from someone using it.

Yes, your edit is correct. In case of confusion, the php was correct at 7.2 as stated for the old site (and would be for the upgrade if it had worked, before then being changed to 7.3). For me, this failure is moot in that I was forced to develop a new site from a clean install in 1.7.7.0, given the failed upgrade path.

**Comment by hibatallahAouadni** [comment] 2020-12-28 10:28
Hello @jajarom @CJH297 

Could you please attach your log file, you can find it under your admin folder of your PrestaShop project:

**`admin > autoupgrade > tmp > log.txt`**

We need this file to find out the source of the bug.
**PS: could you please check if your issue is similar to this** #20332

Thanks!

**Comment by CJH297** [comment] 2020-12-28 11:22
The issue seems similar, but I lack ability to state identical. I'm sorry, though, I cannot supply the log.txt.

I am running a live site in 1.7.4.4. In preparation for 1.7.7.0, I made a new clean site in 1.7.6.7, which upgraded without problem to .8 and then .9, all in maintenance mode. When 1.7.7.0 was released, I attempted the upgrade and this failed, effectively destroying the site. I restored from a backup and tried again, but the same happened. I was forced to abandon my work, and start over with a clean 1.7.7.0. I lacked space for yet another site, and had to delete the copy with the log file.

You mention using a template, a couple of mails ago. I have other bugs I have discovered but cannot find the template to report these. Could you help with a link please?

**Comment by hibatallahAouadni** [comment] 2020-12-29 09:13
Hello @CJH297 

Thanks for your feedback :slightly_smiling_face: 
This issue is similar and it's already in our debug backlog, we're working on it.
To be informed when it's fixed, please subscribe to the issue mentioned above.

If you encounter any other problem, search in the issue if there's similar one. Then, if you couldn't find similar one, create a new one followin the provided template to submit a complete bug report:

![image](https://user-images.githubusercontent.com/23308427/103272844-28ad6c00-49be-11eb-8a65-561b54e06d9c.png)

You need to fill all these blocks with your infos :wink: 
So, I close this issue cause it's a duplicate of #20332 . 

PS: don't panic closing the issue doesn't mean that the problem will be not resolved or we don't answer all question about this issue :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-29 09:14
Duplicate of #20332

**Closed as completed by hibatallahAouadni** 2020-12-29 09:13 UTC
Labels: Bug, IN, Duplicate, Autoupgrade, 1.7.7.0, 1.7.6.9
