### ISSUE TITLE
Smarty isset() Notice

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#12116] opened 2019-01-10 17:26 UTC
**Describe the bug**
Using Smarty's isset() test on an absent value causes a Notice to be displayed in Debug mode.
This seems to be about the latest versions of Smarty.
https://github.com/smarty-php/smarty/issues/499

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 5.6 - 7.x

**Comment by khouloudbelguith** [comment] 2019-01-11 09:54
Hi @jeckyl,

Thanks for your report.
Could you please add steps to reproduce the issue in a new comment.
Thanks!

**Comment by jeckyl** [comment] 2019-01-11 10:57
Personally I encounter this problem on a module or I test in smarty a variable of the kind:
{if isset($toto) && $toto}
{/if}

Before, if the $toto did not exist then the test was necessary, logical, without alert of any kind.

Now I have a Notice alert because $toto is not defined, hence the use of isset() to control this.

**Comment by khouloudbelguith** [comment] 2019-01-11 11:06
@jeckyl, could you please provide me with your custom module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-11 09:40
Hi @jeckyl,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-11 09:40 UTC
Labels: CO, No change required, 1.7.5.0

**Comment by tmcreativeltd** [comment] 2019-02-15 12:44
Was this ever resolved please? I'm getting the same errors. Do I need to revert back to earlier versions or turn debug off or is there a better solution? Thanks

**Comment by tmcreativeltd** [comment] 2019-02-15 12:50
Hi @jeckyl did you resolve this issue or was the only way to revert to an earlier version of Smarty? Thanks in advance!

**Comment by jeckyl** [comment] 2019-02-15 13:13
I had to work around the problem by restructuring my variables.
This was a beneficial obligation to obtain a maintainable code.
