### ISSUE TITLE
[Product V2]  :  labels of availability not updated 

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#30537] opened 2022-12-08 15:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we change the labels of availability and then save it, nothing is saved, the labels are empty.
SEE THE ATTACHED VIDEO
[Untitled_ Dec 8, 2022 1_26 PM.webm](https://user-images.githubusercontent.com/115152460/206497366-35509013-8adf-4e85-95e5-8c46b8fd7ab1.webm)

### Expected behavior

When we change labels of availability and then save it, it should be saved 

### Steps to reproduce

1. BO>configure>Advanced Parameters>Experimental Features
2. Enable the option of Experimental Product Page, then Save
3. BO>SELL>Catalog>Products
4. create a new product with combinations exp : 
combination n1: color pink/quantity 10 
 combination n2: color off white  / quantity -10 >save list 
5. when out of stock >use default behavior (deny orders) 
6. label when in stock exp: PRODUCT IS IN STOCK!
7. label when out of stock exp: PRODUCT IS NOT AVAILABLE IN STOCK!  
8. save: successful update > see the two labels are empty! 
9. Click on preview >
Click on color off white > see another message is there!
click on the color pink > there is not an availability message 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment] 2022-12-08 19:28
Hello @djoelleuch,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.
8.0.0 ==> OK
develop ==> NOK

https://watch.screencastify.com/v/34c02zdtJkSGso8Om3Fg

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by kpodemski** [comment] 2022-12-09 06:11
cc @Hlavtox - isn't it related to your changes? 🤔

**Comment by Hlavtox** [comment] 2022-12-09 11:40
Shouldn't affect anything. I suspect this PR - https://github.com/PrestaShop/PrestaShop/pull/30360 🤔

**Comment by kpodemski** [comment] 2022-12-09 11:46
I thought it was automatically tested 🤔 

cc @jolelievre @zuk3975

**Comment by zuk3975** [comment] 2022-12-13 15:58
probably a bug after my PR, will check

**Comment by jolelievre** [comment] 2022-12-13 16:18
@kpodemski the CQRS commands are behat tested, but we lack tests on integration and the controller itself so maybe this one skipped through our nets

**Comment by AureRita** [comment] 2022-12-16 15:15
Hello @djoelleuch 

I have a question about your issue, the real issue is :
You didn't have the label you saved on the FO 
or 
You can't save your label on the BO ? 

Waiting for your feedback

**Comment by djoelleuch** [comment] 2022-12-16 15:42
Hi @AureRita

**Comment by djoelleuch** [comment] 2022-12-16 15:43
HI @AureRita

**Comment by djoelleuch** [comment] 2022-12-16 15:52
Hi @AureRita 
well, this issue is about both!
the label that didn't save on BO and didn't see on the  FO.

**Comment by Hlavtox** [comment] 2022-12-16 15:59
@djoelleuch You did not see the labels because they were not configured in Prestashop settings, can you check now on develop branch? Everything works perfectly, I tested it.

**Comment by kpodemski** [comment] 2023-01-06 17:48
Ping @djoelleuch

**Comment by Hlavtox** [comment] 2023-01-06 17:52
It's working perfectly on develop branch, there is no issue now. @kpodemski

@djoelleuch If you find something, you can reopen. 👍

**Closed as completed by Hlavtox** 2023-01-06 17:52 UTC
Labels: Bug, develop, Minor, BO, Regression, Fixed, PR available, Verified, Experimental Features
