### ISSUE TITLE
Bug on displayed total discount value when there more than one free shipping voucher

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#16242] opened 2019-10-31 17:25 UTC
**DECRIPTION**
When there are two or more free shipping vouchers in use, the shipping cost is added each time to the total discount value displayed in the cart reduction summary.

**To Reproduce**
1. in BO, create two reduction vouchers with free shipping activated
2. In FO, add one or more product to your cart
3. See that "Réduction(s)" value has added free shipping cost's value for each voucher having a shipping cost

**Comment by khouloudbelguith** [comment] 2019-11-01 08:22
Hi @matthieu-rolland,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11722
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-01 08:23
Duplicate of #11722

**Closed as completed by khouloudbelguith** 2019-11-01 08:22 UTC
Labels: Duplicate
