### ISSUE TITLE
Modulo de estadisticas

### ISSUE THREAD

**Issue by guardabosques** [PrestaShop/PrestaShop#29721] opened 2022-09-22 12:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Me puedo descargar el módulo, pero da error al instalarlo, me dice:
¡Uy!... parece que ocurrió un error inesperado

Este archivo no es un módulo en formato ZIP válido.

[Exception 0]

### Expected behavior

Pues que se instalara

### Steps to reproduce

1. Descargo el módulo
2. Intento subirlo e instalarlo
3. Me da error

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

 dashactivity  v2.0.2

**Comment by AureRita** [comment] 2022-09-22 14:37
Ola @guardabosques 

Yo puedo hablar solo en Ingles 

I tried to reproduce your issue as you can see on this video : 

https://user-images.githubusercontent.com/100699445/191775554-f1234fda-759c-400f-b845-cf57a365ab29.mp4

Currently, I think we don't have enought details, can you give us more ? like : 

did you have the zip from this website : 
https://github.com/PrestaShop/dashactivity/releases/tag/v2.0.2

By clicking on this zip :
![image](https://user-images.githubusercontent.com/100699445/191776336-7fc5bc24-6c0c-4692-98b6-d1cfc36d7fab.png)

Can you give us a video to check if it's from you environment, from the zip or anything else ? 

Thank you

**Comment by guardabosques** [comment] 2022-09-22 15:03
Gracias, lo he instalado bien, pero sigo sin ver las visitas en linea

**Comment by AureRita** [comment] 2022-09-22 15:15
I think it's because the period of the view is anterior of today and this module didn't have the time to check the past. 

As we can see, your first issue is resolved. so I'll close it. 

if you need some help for the rest of the module, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Closed as completed by AureRita** 2022-09-22 15:15 UTC
Labels: Bug, BO, Dashactivity, Invalid, Module
