### ISSUE TITLE
Orders/Products export returns only the 1st page of results

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#28701] opened 2022-06-08 13:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When exporting the orders or products to CSV from the admin panel, the generated file contains only the 1st page of the table.

In others admin panels (like customers), the CSV contains the data from all pages.

### Expected behavior

The orders or products export should contains the data of all pages.

### Steps to reproduce

This needs to be tested on shop with at least 11 orders.

1. Open the orders panel
2. Show 10 results per page
3. Export the data (⚙️ icon at the top right of the table > Export)
4. See that the downloaded file contains only 10 results

Repeat the same with products

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-06-08 16:42
Hello @Seb33300 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19527. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-06-08 16:42
Duplicate of #19527

**Closed as completed by hibatallahAouadni** 2022-06-08 16:42 UTC
Labels: Bug, Duplicate, Invalid
