### ISSUE TITLE
Module listing buttons

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10761] opened 2018-09-29 00:14 UTC
**Is your feature request related to a problem? Please describe.**
I guess... why is the default button next to "Other" "Disable"? Shouldn't it be "Configure"? It's most common option to use  on module listing.
**Describe the solution you'd like**
Replace "Disable" with "Configure"

**Comment by Quetzacoalt91** [comment] 2018-10-01 07:25
This change has been reverted in https://github.com/PrestaShop/PrestaShop/pull/10726/commits/055c2c546d54cacdea24665e7e673b2bcd63ed1a.

It will be fine pour the stable release of 1.7.5.0. :)
Closing as duplicate of https://github.com/PrestaShop/PrestaShop/issues/10688

**Closed as completed by Quetzacoalt91** 2018-10-01 07:25 UTC
Labels: Duplicate
