### ISSUE TITLE
Not all icons from backoffice sidebar are visible

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#18407] opened 2020-04-01 07:37 UTC
#### Describe the bug

If window height is shorter than sidebar and sidebar is collapsed, you can not view all the icons. 

![image](https://user-images.githubusercontent.com/15104724/78110999-42545f80-73fc-11ea-9792-ffef2bc781c7.png)

Sidebar doesn't have a scroll when collapsed.

#### Additional information

* PrestaShop version: 1.7.6.3

**Comment by khouloudbelguith** [comment] 2020-04-01 08:57
Hi @idnovate,

I have the same issue with PS1.7.6.4 and PS1.7.5.2.
In the branch 1.7.7.x, we have a regression reported here: https://github.com/PrestaShop/PrestaShop/issues/18412

Ping @NeOMakinG, do you think, this issue `Not all icons from back-office sidebar are visible` could be fixed when fixing this [bug](https://github.com/PrestaShop/PrestaShop/issues/18412)?

I will try to reproduce the issue when https://github.com/PrestaShop/PrestaShop/issues/18412 is fixed.
Thanks!

**Comment by NeOMakinG** [comment] 2020-04-01 09:13
Hey @khouloudbelguith and @idnovate 

This issue has been fixed by @PierreRambaud on august 2019 on 1.7.7.x, and there are 2 patch on his work, one is merged, the other is WIP (doing it right now)

**Comment by khouloudbelguith** [comment] 2020-04-01 10:02
@NeOMakinG, thanks :smile: 
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14689  to fix the issue.
Your ticket is a duplicate of #9588
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-01 10:02
Duplicate of #9588

**Closed as completed by khouloudbelguith** 2020-04-01 10:02 UTC
Labels: Bug, Minor, BO, Duplicate, 1.7.5.2, 1.7.6.4

**Comment by NeOMakinG** [comment] 2020-04-01 10:34
Fixed by this on 1.7.7.x : https://github.com/PrestaShop/PrestaShop/pull/18416
