### ISSUE TITLE
No invoice on the main order page only in documents tab 

### ISSUE THREAD

**Issue by saradmi** [PrestaShop/PrestaShop#21904] opened 2020-11-13 12:06 UTC
#### The invoice doesn't appear on the order page
the option is grey with "no invoice",
but the invoice appears in the documents tab of the order page,
also the orders without an invoice don't seem to be counted in the statistic page

#### Steps to Reproduce

1. Go to "order"
![1](https://user-images.githubusercontent.com/63447753/99069340-77d64380-25ae-11eb-9e3e-f8b1a823b186.png)
2. Click on "order without invoice"
![1 (2)](https://user-images.githubusercontent.com/63447753/99069113-08605400-25ae-11eb-859f-928da11fd06e.png)
3. open "document" tab
4. see the invoice there 
![1 (1)](https://user-images.githubusercontent.com/63447753/99069126-0d250800-25ae-11eb-834f-18776966afd4.png)

#### Additional information

* PrestaShop version:  1.7.6.8
* PHP version: 7.2.34

**Comment by florine2623** [comment] 2020-11-13 12:30
Hi @saradmi ,
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
You can go to PrestaShop [forum](https://www.prestashop.com/forums/) to find some answers.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2020-11-13 12:30 UTC
Labels: No change required
