### ISSUE TITLE
Displays incorrect in backend

### ISSUE THREAD

**Issue by pjlarsson** [PrestaShop/PrestaShop#19345] opened 2020-05-26 07:18 UTC
#### Displayed incorrectly

The fields are cutted on the left side in the product settings.

#### Expected behavior

I want to see the whole row.

#### Steps to Reproduce

1. Go to Catalog/Products
2. Click on a product
3. Scroll down...

**Screenshots**

![Skjermdump_052620_090028_AM](https://user-images.githubusercontent.com/65942796/82871246-9037a080-9f31-11ea-94c7-507f4709559b.jpg)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.4.6

I have tried different browsers and presta is updated!

**Comment by sarahdib** [comment] 2020-05-26 13:32
Hello @pjlarsson 

PrestaShop 1.7.6.4 isn't compatible with php 7.3 and php 7.4 you should downgrade your php to 7.2.

I close this issue. If the problem is still there when you downgrade php feel free to open a new issue in order to try to reproduce.

Thank you

**Closed as completed by sarahdib** 2020-05-26 13:32 UTC
Labels: No change required

**Comment by pjlarsson** [comment] 2020-05-26 13:38
Thanks Sarah, It worked! :)
