### ISSUE TITLE
Duplicated orders from the same cart

### ISSUE THREAD

**Issue by soyes** [PrestaShop/PrestaShop#17266] opened 2020-01-21 07:37 UTC
We have found a bug which allows to create duplicated orders from the same cart. In order to check if the shop has this kind of problem, you can execute the following MySQL query:

SELECT 
	id_order,
	GROUP_CONCAT(id_order), 
	count(id_cart), 
	GROUP_CONCAT(reference),
	date_add
FROM ps_orders
GROUP BY id_cart
HAVING COUNT(id_cart) > 1
ORDER BY `ps_orders`.`id_order` DESC

In the following screenshoot you can see that two identical orders have been created at the same time:
http://soy.es/screenshots/issues_17266_01.jpg

If we look at the carts, we see that two different orders were created from the same cart:
http://soy.es/screenshots/issues_17266_02.jpg

When we revise the code, in order to find the error, we see that in the Cart.php class there is a function which checks if there is already an order for that cart. This function, orderExists(), has a cache:
http://soy.es/screenshots/issues_17266_03.jpg

It is quite likely that the bug comes from this cache. We belive that each time the shop checks if an order exists from a cart may be verified with the data base directly, not with a cache:
http://soy.es/screenshots/issues_17266_04.jpg

This function is called before creating an order in the validateOrder() function from the PaymentModule class:
http://soy.es/screenshots/issues_17266_05.jpg

**Comment by khouloudbelguith** [comment] 2020-01-21 08:01
Hi @soyes,

Thanks for your report.
What is the exact version of PrestaShop did you use?
Your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/11115#issuecomment-466335070? is it?

Thanks to check & feedback.

**Comment by soyes** [comment] 2020-01-21 08:17
Hi @khouloudbelguith ,

We have found the problem from 1.5.6.2 until 1.7.5.0. We haven't tested it in 1.7.6.X versions yet.
I think that it has many similarities with the ticket you link.

**Comment by khouloudbelguith** [comment] 2020-01-21 15:03
@soyes, thanks for your feedback.
Your ticket is a duplicate of #11115
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-21 15:03
Duplicate of #11115

**Closed as completed by khouloudbelguith** 2020-01-21 15:03 UTC
Labels: Bug, BO, Duplicate, Order

**Comment by mathieuhen** [comment] 2020-01-22 16:21
Hi. 
I have also dupplicate orders but not with the same reference. 
The orders are created at the same exact time. 
Orders created with ps_wirepayment module. 

But I can't reproduce always this issue. 

I enabled DEBUG_MODE in abstract class PaymentModuleCore. 
And I added a log to the front controller of the validation in the module ps_wirepayment. 

And there are logs below: 

![Capture](https://user-images.githubusercontent.com/43207184/72912133-772ca200-3d3b-11ea-8cd1-825788db3f6c.PNG)

Sometime the function postProcess() is called twice and sometime not. 
Why and how is it possible ?

**Comment by khouloudbelguith** [comment] 2020-01-22 16:24
Hi @mathieuhen,

Please follow this comment: https://github.com/PrestaShop/PrestaShop/issues/11115#issuecomment-466335070

Thanks!

**Comment by mathieuhen** [comment] 2020-01-22 16:29
Seriously ? This comment ?
I don’t understand !

**Comment by khouloudbelguith** [comment] 2020-01-22 16:32
@mathieuhen, this issue is closed as a duplicated of this issue: https://github.com/PrestaShop/PrestaShop/issues/11115, that's why this issue is closed.

Thanks for your understanding!

**Comment by mathieuhen** [comment] 2020-01-22 16:34
Hi, but it’s not the same issue.

I have not the same reference for duplicate orders.

I have just dupplicate orders.

**Comment by khouloudbelguith** [comment] 2020-01-22 16:38
@mathieuhen, this issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
