### ISSUE TITLE
ps_shoppingcart: ajax feature -> modal dialog backdrop

### ISSUE THREAD

**Issue by matteocostantini** [PrestaShop/PrestaShop#24350] opened 2021-05-05 09:53 UTC
#### Describe the bug

In standard Prestashop Installation (live demo), when click add-to-cart button (e.g. in product page), modal is open. Close by clicking in background greyed area is NOT CORRECT. Not page refresh. 

to better understand the problem, the quantity field could be initialized by every developer , as we did, with the available quantity. If we do not refresh the page, the quantity field is not updated with new max availability value.

#### Expected behavior

Cart Modal Closing only with "COntinue Shopping" or "Proceed to Checkout". This actions start a refresh (quantity input refreshed)

#### Steps to Reproduce

1. Go to a product page
2. Click on cart button, the modal cart is opened
3. Click on background area outsided modal area.
4. Quantity not refreshed.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-05-06 05:55
Hello @matteocostantini 

I  didn't manage to reproduce your isue with PS1.7.7.3, see the attached screen record below:

https://www.awesomescreenshot.com/video/3641572?key=28679f7bd4ee9542f37139a426554780

Please check and feedback.
Thanks!

**Comment by matteocostantini** [comment] 2021-05-06 07:03
Ok, the quantity in cart is correct. But the input quantity we initialize with stock availability in template code (product.tpl). Only with a page refresh show input quantity field (stock availability - cart quantity). We have constraint to press cart modal button for page refresh. Click outside cart modal not refresh… it’s compliant disable background click and keymap! Is possible a new parameter in mod_shoppingcart’s config for this!

**Comment by Hlavtox** [comment] 2021-05-06 17:58
In classic-rocket, @prestarocket did it in a different way. It's hooked on bootstrap modal close action, so it's working every time.

**Comment by Oksydan** [comment] 2021-05-06 19:22
IMO the best solution is to do it like this. 

```js
prestashop.on('updateCart', (event) => {
    if (prestashop.page.page_name == 'product' && event.reason.idProduct == $('#add-to-cart-or-refresh').find('[name="id_product"]').val()) {
      prestashop.emit('updateProduct', {
        event,
        resp: {},
        reason: {
          productUrl: prestashop.urls.pages.product || '',
        },
      });
    }
  });
  ```
If we trigger it always on modal close it will trigger `updateProduct` event on category page, home page etc. (Yes, I am not looking at classic theme at this moment). We are not forced to use modal to inform customer about add to cart action.

**Comment by hibatallahAouadni** [comment] 2021-05-17 20:16
Hello everyone,

Thanks for your patience and the details :relaxed: 
Even with all the infos provided, I still cannot reproduce the issue. Please check the screen record below:

https://drive.google.com/file/d/11Ls9gzxBMnsju0BRBtfNmnpvRDz954lk/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-07 15:02
Hello @matteocostantini 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-07 15:02 UTC
Labels: Bug, FO, No change required, Shopping carts FO, 1.7.7.0
