### ISSUE TITLE
Problem with the cache in 1.7.4.2

### ISSUE THREAD

**Issue by infinity-web-italy** [PrestaShop/PrestaShop#12451] opened 2018-09-18 08:23 UTC
Hello,
I noticed that the module does not work correctly when you activate the theme cache ..
As you can see from the image, the first product is seen correctly while the others do not. If you disable the theme cache this does not happen. This site, however, needs the active cache!
Any ideas on how I can fix this problem?
![2](https://user-images.githubusercontent.com/43369421/45674219-e3d2d380-bb2c-11e8-81e7-5e9354258b4f.JPG)

**Comment by khouloudbelguith** [comment] 2019-02-06 10:39
Hi @infinity-web-italy,

I did not manage to reproduce the issue with PS1.7.5.0 & ps_viewedproduct module v1.2.0.
I attached a video record.
 https://drive.google.com/file/d/1wcnQcmQj_G1GhKv3E1NYZlBEXRzTuKlr/view
What is the exact version of the ps_viewedproduct module did you use?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-08 08:13
Hi @infinity-web-italy,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-08 08:13 UTC
Labels: FO, Performance, Viewed products, No change required, 1.7.4.2

**Comment by SharmPRO** [comment] 2019-07-07 15:32
Hi i has the same issue as described above by @infinity-web-italy

[https://drive.google.com/file/d/1BQK8ddCBb5MXaKSchnSSXrBJfzEteyMr/view?usp=sharing](url)

PS 1.7.5.2
ps_viewedproduct 1.2.1
Warehouse theme 4.2.2
PHP 7.2.12
