### ISSUE TITLE
Checkbox Not Working

### ISSUE THREAD

**Issue by artizch** [PrestaShop/PrestaShop#23326] opened 2020-12-08 18:16 UTC
Hello,

Contact form is still sending even if the checkbox is unchecked.

PrestaShop ver 1.7.6.4
psgdpr 1.2.0

**Comment by hibatallahAouadni** [comment] 2021-02-26 12:23
Hello @artizch 

Could you please provide steps to reproduce and screenshots, please.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-26 18:25
Duplicate of #23319

**Closed as completed by hibatallahAouadni** 2021-02-26 18:25 UTC
Labels: Bug, FO, Duplicate, Modules, GDPR, 1.7.6.4
