### ISSUE TITLE
Backoffice load PDf error

### ISSUE THREAD

**Issue by mark-app** [PrestaShop/PrestaShop#26684] opened 2021-11-19 15:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After upgrading to PrestaShop 1.7.8.1 i can't load an pdf invoice anymore.

I got the error : 
Call to a member function assign() on null

[Symfony\Component\Debug\Exception\FatalThrowableError 0]

### Expected behavior

Pdf should be dowloaded for the invoice.

### Steps to reproduce

1) Go to orders
2) Click on Show invoice

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.2.34, 7.4.24

**Comment by mark-app** [comment] 2021-11-19 15:16
<img width="1150" alt="Schermafbeelding 2021-11-19 om 16 15 05" src="https://user-images.githubusercontent.com/6554157/142646267-43fc2622-9571-4ba1-811f-a8ae5f044243.png">

**Comment by khouloudbelguith** [comment] 2021-11-19 16:08
Hi @mark-app,

I did not manage to reproduce the issue with PS1781 after an upgrade from PS1778.
I attached a screen record
https://watch.screencastify.com/v/hitnHJqwUN5E117tO087

Thanks to check and feedback.

**Comment by florine2623** [comment] 2021-12-09 09:40
Hello @mark-app ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-12-09 09:40 UTC
Labels: Bug, Order, Invoices, Autoupgrade, Invalid
