### ISSUE TITLE
error displaying multiple images in one product 

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18968] opened 2020-05-04 17:44 UTC
#### Describe the bug

When a product has multiple images, a carousel is created with two arrows on the sides.
this carousel, in google chrome if you press the left arrow an error is created in which the images are passed infinitely

#### Expected behavior

same function as the right arrow

#### Steps to Reproduce

1. Go to a product
2. Click on left arrow ON GOOGLE CHROME!!
3. See error

**Screenshots**

https://youtu.be/regjYRyjWM8
https://youtu.be/sCV_RynDnDo

#### Additional information

* PrestaShop version: 1.7.6.4 - 1.7.7
* PHP version: 7.2.29

**Comment by alfonsolr09** [comment] 2020-05-04 17:45
@Progi1984 closed the previous thread

**Comment by alfonsolr09** [comment] 2020-05-04 17:46
important this error only happens in google chrome

**Comment by TristanLDD** [comment] 2020-05-06 10:50
Hi @alfonsolr09 

I did not manage to reproduce this issue with the last version PS 1.7.6.5 and last version Chrome 81.0.4044.129. 

Can you precise the version of Chrome you're using? 
Thanks!

**Comment by alfonsolr09** [comment] 2020-05-06 15:10
Versión 81.0.4044.129 (Build oficial) (64-bits)

but i have tried on a newly purchased computer and installed google chrome and cannot reproduce the error on that computer.  
but I have tested on 5 computers that have installed google Chrome for more than 8 months and if this error occurs.  
I have the latest version of Google Chrome on all computers

**Comment by Progi1984** [comment] 2020-05-07 07:10
It may be a cache problem. Could you clean your browser cache on these computers ? Thanks

**Comment by alfonsolr09** [comment] 2020-05-07 08:19
yes I tried it but it didn't work

**Comment by florine2623** [comment] 2020-05-07 11:37
Hi @alfonsolr09 ,
I tried adding the same amount of image (11) as you did in your screen record. I still can't reproduce your issue. Please check if you have any module that might be overriding this feature.
Thanks!

**Comment by alfonsolr09** [comment] 2020-05-16 19:59
apparently uninstalling google chrome and installing it again it solves

**Comment by Progi1984** [comment] 2020-05-18 07:45
@alfonsolr09 Thanks. So we can close this issue ?

**Comment by alfonsolr09** [comment] 2020-05-18 07:58
I think yes thanks

**Comment by Progi1984** [comment] 2020-05-18 08:00
Thanks ;)

**Closed as completed by Progi1984** 2020-05-18 08:00 UTC
Labels: Bug, FO, No change required
