### ISSUE TITLE
CategoryController, addToCategories error 500

### ISSUE THREAD

**Issue by AdrianStolarski1988** [PrestaShop/PrestaShop#13982] opened 2019-05-27 12:32 UTC
**Describe the bug**
While I have set default language different from English, I get error 500 in browser console, when I want create create a new category in Edit/Create new product 

**To Reproduce**
1. Go to 'International > Localization '
2. Set Default language as Polish
3. Go to Catalog > Products > New Product
4. Enter Product name and click save
5. In basic settings overlap create new category with name "NewCategory" and set Parent of the category as Home category
6. While I click "Create" button the category isn't create and in get Error 500 on POST method sell/catalog/products/categories/add/simple?id_product=32&_token=2ynDi1MXqI1P32zEtsfvYs0AIm8cMpToJDfKnGFuwSc

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/26248031/58419443-e8bc2f80-808a-11e9-9519-c6267f72dde6.png)
![image](https://user-images.githubusercontent.com/26248031/58419624-6d0eb280-808b-11e9-911a-a8a9dfa67310.png)
![image](https://user-images.githubusercontent.com/26248031/58419772-c840a500-808b-11e9-85be-9f0ea2cea69b.png)
![image](https://user-images.githubusercontent.com/26248031/58419780-cecf1c80-808b-11e9-8c5a-d9ab8a6c5624.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-05-27 12:47
Hi @AdrianStolarski1988,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9752
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-27 12:48
Duplicate of #9752

**Closed as completed by khouloudbelguith** 2019-05-27 12:47 UTC
Labels: Duplicate
