### ISSUE TITLE
Customers > Customers page in the back-end is very slow to load

### ISSUE THREAD

**Issue by ArteInfoRM** [PrestaShop/PrestaShop#35978] opened 2024-04-21 08:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In some installations of PrestaShop 8.1.3 and 8.1.4 the Customers page in the back-end takes a long time to load.  By enabling debug profiling, it takes a long time to load "config". 

### Steps to reproduce

The only thing that seems common where it occurs is when one or more customers have a large number of orders. However, it is not the query time that is causing the problem.

![Screenshot_3](https://github.com/PrestaShop/PrestaShop/assets/41371761/89bc02fc-dbb6-47df-b7ca-213b46e7015b)
![Screenshot_4](https://github.com/PrestaShop/PrestaShop/assets/41371761/2b0d4d78-3125-4e7d-8f24-09530be68bbb)

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-04-22 09:10
ping @elyesnaouar,

Could you take a look at this please ? :D

I can't reproduce your issue.

**Comment by Hlavtox** [comment] 2024-04-22 10:45
This is fixed on develop branch. Grid has been implemented so the performance issue has been resolved.

**Comment by ArteInfoRM** [comment] 2024-04-22 10:51
> This is fixed on develop branch. Grid has been implemented so the performance issue has been resolved.

From what version, did they fix it in 8.1.5?
Currently where the problem occurs is an 8.1.4.

**Comment by ArteInfoRM** [comment] 2024-04-22 10:55
> I can't reproduce your issue.

It only occurs in very rare cases, the only thing in common is the presence of one or more customers with many orders, but it may not depend on this.

**Comment by Hlavtox** [comment] 2024-04-22 12:18
@ArteInfoRM It's fixed on 9.0.0 that will be released sometime this year. 👍

**Comment by ArteInfoRM** [comment] 2024-04-22 13:30
> @ArteInfoRM It's fixed on 9.0.0 that will be released sometime this year. 👍

I was hoping it would be fixed with the upcoming 8.1.6. Is there anything that can be done where this problem occurs while waiting for version 9.

**Closed as completed** 2024-06-14 09:04 UTC
Labels: Bug, BO, Customer, Performance, Fixed, 8.1.x
