### ISSUE TITLE
Incorrect prices shown for customized products on the Order confirmation page

### ISSUE THREAD

**Issue by tvorgul** [PrestaShop/PrestaShop#20541] opened 2020-08-11 11:51 UTC
Description : 
If you have products with customizations in your order, their prices on order confirmation page are 0.

Expected behavior : 
Prices should be shown correctly for each product in the order.

Steps to Reproduce:

1. Add a customized product to the cart (ex Customizable mug in default PrestaShop)
2. Go to checkout and place a order
3. Check order details on the order confirmation page.
4. Check the price of the customized product

**Screenshots**
![image](https://user-images.githubusercontent.com/26280251/89893729-2d24e400-dbd9-11ea-85e4-e00ecdb988a9.png)

#### Additional information

* PrestaShop version: 1.7.6.x & 1.7.7.0
* PHP version: 7.2/7.3

**Comment by khouloudbelguith** [comment] 2020-08-11 12:39
Hi @tvorgul,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15171 to fix the issue.
Your ticket is a duplicate of #10912
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-11 12:39
Duplicate of #10912

**Closed as completed by khouloudbelguith** 2020-08-11 12:39 UTC
Labels: Duplicate, Product customization
