### ISSUE TITLE
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "product_comment_repository".

### ISSUE THREAD

**Issue by hekep** [PrestaShop/PrestaShop#34856] opened 2023-12-15 08:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We have set Prestashop 8.1 to debug mode. 

After that we got error message : 

 

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "product_comment_repository". in /folder/to/prestashop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:289 
Stack trace: 
#0 /folder/to/prestashop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(231): Symfony\Component\DependencyInjection\Container->make('product_comment...', 1) 
#1 /folder/to/prestashop/modules/productcomments/productcomments.php(1029): Symfony\Component\DependencyInjection\Container->get('product_comment...') 
#2 /folder/to/prestashop/modules/productcomments/productcomments.php(1049): ProductComments->getWidgetVariables('displayProductL...', Array) 
#3 /folder/to/prestashop/classes/Hook.php(1004): ProductComments->renderWidget('displayProductL...', Array) 
#4 /folder/to/prestashop/tools/profiling/Hook.php(64): HookCore::coreRenderWidget(Object(ProductComments), 'displayProductL...', Array) 
#5 /folder/to/prestashop/classes/Hook.php(948): Hook::coreRenderWidget(Object(ProductComments), 'displayProductL...', Array) 
#6 /folder/to/prestashop/config/smarty.config.inc.php(205): HookCore::exec('displayProductL...', Array, NULL) 
#7 /folder/to/prestashop/classes/Smarty/SmartyLazyRegister.php(81): smartyHook(Array, Object(SmartyDevTemplate)) 
#8 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/d9/f6/3a/d9f63a9eef01e6e8aefc815b488cef7516a2db57_2.file.product.tpl.cache.php(196): SmartyLazyRegister->__call('smartyHook', Array) 
#9 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_362279806657c04100cb126_19422279->callBlock(Object(SmartyDevTemplate)) #10 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_362279806657c04100cb126_19422279), Object(SmartyDevTemplate)) 
#11 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_362279806657c04100cb126_19422279)) 
#12 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/d9/f6/3a/d9f63a9eef01e6e8aefc815b488cef7516a2db57_2.file.product.tpl.cache.php(287): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_362279806...', 'product_reviews', 0) 
#13 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_670396815657c04100b3626_90206869->callBlock(Object(SmartyDevTemplate)) #14 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_670396815657c04100b3626_90206869), Object(SmartyDevTemplate)) 
#15 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_670396815657c04100b3626_90206869)) 
#16 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/d9/f6/3a/d9f63a9eef01e6e8aefc815b488cef7516a2db57_2.file.product.tpl.cache.php(29): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_670396815...', 'product_miniatu...') 
#17 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_657c04100cc2a0_15741833(Object(SmartyDevTemplate)) 
#18 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) 
#19 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(384): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) 
#20 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/3d/e2/fb/3de2fb917c69babe598ca8bc6a5d96952160b3d4_2.file.productlist.tpl.cache.php(42): Smarty_Internal_Template->_subTemplateRender('file:catalog/_p...', 'ps_featuredprod...', 'classic', 9999, 31536000, Array, 0, true) 
#21 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_657c041009d187_74148331(Object(SmartyDevTemplate)) 
#22 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) 
#23 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(384): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) 
#24 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/fa/6c/c3/fa6cc378d2942c8857b89d6bca728048c0caeedd_2.module.ps_featuredproductsviewstemplateshookps_featuredproducts.tpl.cache.php(32): Smarty_Internal_Template->_subTemplateRender('file:catalog/_p...', 'ps_featuredprod...', 'classic', 9999, 31536000, Array, 0, false) 
#25 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_657c041007eab9_79755881(Object(SmartyDevTemplate)) 
#26 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) 
#27 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_updatecache.php(38): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) 
#28 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_cached.php(143): Smarty_Internal_Runtime_UpdateCache->updateCache(Object(Smarty_Template_Cached), Object(SmartyDevTemplate), false) 
#29 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(212): Smarty_Template_Cached->render(Object(SmartyDevTemplate), false) 
#30 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0) 
#31 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(SmartyDevTemplate), NULL, NULL, NULL, 0) 
#32 /folder/to/prestashop/classes/Smarty/SmartyDevTemplate.php(55): Smarty_Internal_TemplateBase->fetch(NULL, NULL, NULL, NULL) 
#33 /folder/to/prestashop/classes/module/Module.php(2270): SmartyDevTemplateCore->fetch() #34 /folder/to/prestashop/modules/ps_featuredproducts/ps_featuredproducts.php(247): ModuleCore->fetch('module:ps_featu...', 'ps_featuredprod...') 
#35 /folder/to/prestashop/classes/Hook.php(1004): Ps_FeaturedProducts->renderWidget('displayHome', Array) #36 /folder/to/prestashop/tools/profiling/Hook.php(64): HookCore::coreRenderWidget(Object(Ps_FeaturedProducts), 'displayHome', Array) 
#37 /folder/to/prestashop/classes/Hook.php(948): Hook::coreRenderWidget(Object(Ps_FeaturedProducts), 'displayHome', Array) #38 /folder/to/prestashop/controllers/front/IndexController.php(40): HookCore::exec('displayHome') 
#39 /folder/to/prestashop/tools/profiling/Controller.php(60): IndexControllerCore->initContent() #40 /folder/to/prestashop/classes/Dispatcher.php(510): Controller->run() 
#41 /folder/to/prestashop/index.php(28): DispatcherCore->dispatch() #42 {main} Next PrestaShop\PrestaShop\Core\Exception\CoreException: You have requested a non-existent service "product_comment_repository". in /folder/to/prestashop/classes/Hook.php:1008 Stack trace: 
#0 /folder/to/prestashop/tools/profiling/Hook.php(64): HookCore::coreRenderWidget(Object(ProductComments), 'displayProductL...', Array) 
#1 /folder/to/prestashop/classes/Hook.php(948): Hook::coreRenderWidget(Object(ProductComments), 'displayProductL...', Array) 
#2 /folder/to/prestashop/config/smarty.config.inc.php(205): HookCore::exec('displayProductL...', Array, NULL) 
#3 /folder/to/prestashop/classes/Smarty/SmartyLazyRegister.php(81): smartyHook(Array, Object(SmartyDevTemplate)) 
#4 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/d9/f6/3a/d9f63a9eef01e6e8aefc815b488cef7516a2db57_2.file.product.tpl.cache.php(196): SmartyLazyRegister->__call('smartyHook', Array) 
#5 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_362279806657c04100cb126_19422279->callBlock(Object(SmartyDevTemplate)) 
#6 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_362279806657c04100cb126_19422279), Object(SmartyDevTemplate)) 
#7 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_362279806657c04100cb126_19422279)) 
#8 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/d9/f6/3a/d9f63a9eef01e6e8aefc815b488cef7516a2db57_2.file.product.tpl.cache.php(287): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_362279806...', 'product_reviews', 0) 
#9 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_670396815657c04100b3626_90206869->callBlock(Object(SmartyDevTemplate)) 
#10 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_670396815657c04100b3626_90206869), Object(SmartyDevTemplate)) 
#11 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_670396815657c04100b3626_90206869)) 
#12 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/d9/f6/3a/d9f63a9eef01e6e8aefc815b488cef7516a2db57_2.file.product.tpl.cache.php(29): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_670396815...', 'product_miniatu...') 
#13 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_657c04100cc2a0_15741833(Object(SmartyDevTemplate)) 
#14 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) 
#15 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(384): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) 
#16 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/3d/e2/fb/3de2fb917c69babe598ca8bc6a5d96952160b3d4_2.file.productlist.tpl.cache.php(42): Smarty_Internal_Template->_subTemplateRender('file:catalog/_p...', 'ps_featuredprod...', 'classic', 9999, 31536000, Array, 0, true) 
#17 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_657c041009d187_74148331(Object(SmartyDevTemplate)) 
#18 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) 
#19 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(384): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) 
#20 /folder/to/prestashop/var/cache/dev/smarty/compile/classic/fa/6c/c3/fa6cc378d2942c8857b89d6bca728048c0caeedd_2.module.ps_featuredproductsviewstemplateshookps_featuredproducts.tpl.cache.php(32): Smarty_Internal_Template->_subTemplateRender('file:catalog/_p...', 'ps_featuredprod...', 'classic', 9999, 31536000, Array, 0, false) 
#21 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_657c041007eab9_79755881(Object(SmartyDevTemplate)) 
#22 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) 
#23 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_updatecache.php(38): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) 
#24 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_template_cached.php(143): Smarty_Internal_Runtime_UpdateCache->updateCache(Object(Smarty_Template_Cached), Object(SmartyDevTemplate), false) 
#25 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(212): Smarty_Template_Cached->render(Object(SmartyDevTemplate), false) 
#26 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0) 
#27 /folder/to/prestashop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(SmartyDevTemplate), NULL, NULL, NULL, 0) 
#28 /folder/to/prestashop/classes/Smarty/SmartyDevTemplate.php(55): Smarty_Internal_TemplateBase->fetch(NULL, NULL, NULL, NULL) 
#29 /folder/to/prestashop/classes/module/Module.php(2270): SmartyDevTemplateCore->fetch() 
#30 /folder/to/prestashop/modules/ps_featuredproducts/ps_featuredproducts.php(247): ModuleCore->fetch('module:ps_featu...', 'ps_featuredprod...')
#31 /folder/to/prestashop/classes/Hook.php(1004): Ps_FeaturedProducts->renderWidget('displayHome', Array) #32 /folder/to/prestashop/tools/profiling/Hook.php(64): HookCore::coreRenderWidget(Object(Ps_FeaturedProducts), 'displayHome', Array) 
#33 /folder/to/prestashop/classes/Hook.php(948): Hook::coreRenderWidget(Object(Ps_FeaturedProducts), 'displayHome', Array) #34 /folder/to/prestashop/controllers/front/IndexController.php(40): HookCore::exec('displayHome') 
#35 /folder/to/prestashop/tools/profiling/Controller.php(60): IndexControllerCore->initContent() #36 /folder/to/prestashop/classes/Dispatcher.php(510): Controller->run() 
#37 /folder/to/prestashop/index.php(28): DispatcherCore->dispatch() #38 {main} Next PrestaShop\PrestaShop\Core\Exception\CoreException: You have requested a non-existent service "product_comment_repository". in /folder/to/prestashop/classes/Hook.php:1008 Stack trace: 
#0 /folder/to/prestashop/tools/profiling/Hook.php(64): HookCore::coreRenderWidget(Object(Ps_FeaturedProducts), 'displayHome', Array) 
#1 /folder/to/prestashop/classes/Hook.php(948): Hook::coreRenderWidget(Object(Ps_FeaturedProducts), 'displayHome', Array) 
#2 /folder/to/prestashop/controllers/front/IndexController.php(40): HookCore::exec('displayHome') 
#3 /folder/to/prestashop/tools/profiling/Controller.php(60): IndexControllerCore->initContent() 
#4 /folder/to/prestashop/classes/Dispatcher.php(510): Controller->run() 
#5 /folder/to/prestashop/index.php(28): DispatcherCore->dispatch() 
#6 {main} thrown in /folder/to/prestashop/classes/Hook.php on line 1008

We were able to remove the error message by  deleting all of the cache: 

Advanced Parameters -> Performance
  

### Expected behavior

No such error message, and cache automaticly erased, when going to debug mode.

### Steps to reproduce

Advanced Parameters -> Performance 

 Debug mode ->  Yes

Debug profiler ->  Yes

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

prestacomments 5.0.3

**Comment by florine2623** [comment] 2023-12-18 10:15
Hello @hekep ,

I can't reproduce your issue on PS 8.1.x and module products comments v6.0.2.

<img width="241" alt="Screenshot 2023-12-18 at 10 56 01" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1d46b5c2-ddde-4338-bcc3-9b825c198c71">

Please update your module and try again.

I'm closing your issue to avoid clogging the backlog.
Thanks!

**Closed as completed by florine2623** 2023-12-18 10:15 UTC
Labels: Bug, Invalid

**Comment by matks** [comment] 2023-12-18 20:58
Hello @hekep 
- you maybe could try using module productcomments v6.0.2 and not v6.0.0 => https://github.com/PrestaShop/productcomments/releases/tag/v6.0.2
- look at https://github.com/PrestaShop/PrestaShop/issues/24079
