### ISSUE TITLE
[BO] Invalid direction of checkbox marker in RTL

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#24925] opened 2021-06-11 14:15 UTC
Hello,

#### Describe the bug

Checkbox marker has invalid direction in BO with **RTL** Layout

#### Expected behavior

.../adminxxx/themes/new-theme/public/theme_rtl.css (Line: 521)
Need to change (border-left-style: none) to (border-right-style: none)

#### Steps to Reproduce

BO: Improve > international > localization

![Screenshot 2021-06-11 at 18-40-33 بومی سازی • NEO](https://user-images.githubusercontent.com/85633460/121699905-9b318480-cae4-11eb-8d56-61703176fb17.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by florine2623** [comment] 2021-06-11 14:50
Hello @mparvazi ,

I was able to reproduce the issue with PrestaShop version 1.7.8.x, so I can confirm that this behavior is indeed a bug.
<img width="432" alt="Screenshot 2021-06-11 at 16 50 12" src="https://user-images.githubusercontent.com/16019289/121705606-19862a80-cad5-11eb-8317-78e38d1a5dc6.png">

Same for the Payment Preference Page :
<img width="1080" alt="Screenshot 2021-06-11 at 16 51 04" src="https://user-images.githubusercontent.com/16019289/121705768-45a1ab80-cad5-11eb-98ce-2b68b5ffc1bb.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-06-16 14:42
Ping @NeOMakinG

**Comment by Progi1984** [comment] 2021-06-24 09:02
Fixed by @NeOMakinG in #25034

**Closed as completed by Progi1984** 2021-06-24 09:02 UTC
Labels: Bug, develop, Trivial, BO, Regression, Fixed, Front-end, PR available, 1.7.8.x
