### ISSUE TITLE
No funciona la pestaña Modulo Manager

### ISSUE THREAD

**Issue by dptelemetry** [PrestaShop/PrestaShop#16174] opened 2019-10-29 12:54 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-10-29 13:05
Hi @dptelemetry,

Please, send your request in English.
English is the norm on the GitHub 
Could you please provide us with more info? We need more details to understand how we can reproduce your issue
Thank you!

**Comment by khouloudbelguith** [comment] 2019-11-28 08:07
Hi @dptelemetry,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-28 08:07 UTC
Labels: Bug, No change required
