### ISSUE TITLE
Unable to login in backoffice

### ISSUE THREAD

**Issue by rufusmaika** [PrestaShop/PrestaShop#14607] opened 2019-07-12 08:21 UTC
Hi. 
I am trying to login in my backoffice and after inserting the credentials it disappears the credentials input window but does not go to the backoffice.

Error log in the server is showing the following:
++++++++++++++
2019-07-12 00:17:41.174864 [NOTICE] [19757] [96.44.172.43:59703:HTTP2-47] [STDERR] PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot use object of type Symfony\Component\HttpFoundation\ParameterBag as array in /var/www/vhosts/poleposition-pt.com/httpdocs/src/Adapter/Security/Admin.php:91
Stack trace:

0 /var/www/vhosts/poleposition-pt.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): PrestaShop\PrestaShop\Adapter\Security\Admin->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
1 /var/www/vhosts/poleposition-pt.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
2 /var/www/vhosts/poleposition-pt.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\Component\EventDispa in /var/www/vhosts/poleposition-pt.com/httpdocs/src/Adapter/Security/Admin.php on line 91
++++++++++++++++

Any sugestions what might be the issue ?

Thanks in advance.

**Comment by khouloudbelguith** [comment] 2019-07-12 08:30
Hi @rufusmaika,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by rufusmaika** [comment] 2019-07-12 11:06
Hi.

I have already did it and nothing looks outside of the normal or recommended.
Please check it yourself.

https://www.poleposition-pt.com/phppsinfo.php

**Comment by khouloudbelguith** [comment] 2019-07-12 11:09
@rufusmaika, yes, it seems OK.
Could you please try to restart your server, clear cache, check & feedback.

Thanks!

**Comment by MathiasReker** [comment] 2019-07-12 11:24
The problem is that you use PHP 7.3.7 :) Downgrade to 7.2.x

**Comment by MathiasReker** [comment] 2019-07-12 11:26
![php](https://user-images.githubusercontent.com/26626066/61124944-ad45bb00-a4a8-11e9-9108-a5b261cd9189.png)

**Comment by khouloudbelguith** [comment] 2019-07-12 11:29
@MathiasReker, thanks for your feedback.
@rufusmaika, yes, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your version PHP, check & feedback.

**Comment by rufusmaika** [comment] 2019-07-12 11:47
Hi @khouloudbelguith 
I have restarted the server, cleared the cache the cache manually on the prestashop and on my browser and tried a different browser. Issue remains.

@MathiasReker I have another shop and it is running 7.3.7 and runs goods. I have changed this shop to 7.2.20  but issue remains.

**Comment by khouloudbelguith** [comment] 2019-07-12 11:55
@rufusmaika, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rufusmaika** [comment] 2019-07-12 12:25
Hi @khouloudbelguith 

The error lof that i posted on post #1 is the server log.
I have enabled the debug mode but does not show any error.

[login.mov.zip](https://github.com/PrestaShop/PrestaShop/files/3386388/login.mov.zip)

**Comment by khouloudbelguith** [comment] 2019-07-12 13:40
@rufusmaika, did you installed any modules before this issue occurs?

Thanks!

**Comment by rufusmaika** [comment] 2019-07-12 13:55
@khouloudbelguith , no. Nothing.
I checked some orders by 12:39pm and managed to login.
This morning i was trying to login and this issue was happening.
No server updates were done or any modules installed.
This is strange. Nothing was done and this happens.

**Comment by khouloudbelguith** [comment] 2019-07-12 14:05
@rufusmaika, could you please change the Default page of your employee manually.
You need to edit your database, table `ps_employee`, change the value of the `default_tab` to 4.
>UPDATE `ps_employee` SET `default_tab` = '4' WHERE `ps_employee`.`id_employee` = 1;

PS: before any modification, thanks to make a backup of your database.
Thanks!

**Comment by rufusmaika** [comment] 2019-07-12 14:32
@khouloudbelguith 
I have restored the files from yesterday backup and managed to put it to work.
Although this is very strange stuff to happen.
Please close the ticket.

**Comment by khouloudbelguith** [comment] 2019-07-12 14:40
@rufusmaika, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-12 14:40 UTC
Labels: Bug, BO, No change required
