### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by b8fish** [PrestaShop/PrestaShop#11670] opened 2018-12-08 19:07 UTC
**Describe the bug**
If a Product has a Tag containing a single double quote("), a "Save" for the product fails silently reporting only "Settings Saved".

**To Reproduce**
1. In back-end, Go to 'catalog/products'
2. Click on any product
3. Make a change to Summary text (for instance); save, 
4. Verify that new Summary displays the change on the front-end product page.
5. In the back-end, click on Options. Add tag containing a single double quote (eg 1" wide tape); save
6. Make another change to Summary; verify on front-end.. change is not there.
7. In the back end, remove the new tag; save;
8 verify in front end change is now recorded.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: N/A

**Comment by b8fish** [comment] 2018-12-08 19:38
Further information.

Same silent failure to update product if a tag contains a '+' sign

**Comment by khouloudbelguith** [comment] 2018-12-10 09:04
Hi @b8fish,

Here's a PR: https://github.com/PrestaShop/PrestaShop/pull/10856 to fix the issue.
It is fixed in the next release 1.7.5.0
Your ticket is a duplicate of #10856
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-10 09:04 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2018-12-10 09:07
Duplicate of #10856
