### ISSUE TITLE
1 click update from 1.7.4.4 to 1.7.5.0 results in white page of BO and FO. [error500]

### ISSUE THREAD

**Issue by FabioReims** [PrestaShop/PrestaShop#12332] opened 2019-01-28 14:30 UTC
PrestaShop version: 1.7.4.4 (I updated all the way up from 1.7.3.4)
PHP version: 7.1
1-Click update version: 4.5.1

Once I update to 1.7.5.0 via the 1 click update, the update goes through. The only warnings I receive are as follows:

[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE `ps_supply_order_receipt_history` CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '', CHANGE `employee_lastname` `employee_firstname` VARCHAR(255) DEFAULT '': Duplicate column name 'employee_firstname'

[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE `ps_product` CHANGE `reference` `supplier_reference` varchar(64) DEFAULT NULL, CHANGE `supplier_reference` `supplier_reference` varchar(64) DEFAULT NULL: Duplicate column name 'supplier_reference'

[WARNING] SQL 1.7.5.0 1060 in ALTER TABLE `ps_stock_available` ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`: Duplicate column name 'location'

I've turned on debug mode, but I only receive a error 500 message: This page isn’t working domain.com is currently unable to handle this request. HTTP ERROR 500

On FO and BO.

**Comment by khouloudbelguith** [comment] 2019-01-28 14:31
Hi @Apury,

About those warnings, here's the PR: #11814 to fix the issue.
It is fixed in the next release 1.7.5.1.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by FabioReims** [comment] 2019-01-28 14:48
Deleting the cache didn't change anything. 

Which files are those PR's commited to? I can't find any install-dev/upgrade/ file path on my server. 

Furthermore, does that mean, once 1.7.5.1 is released, I skip updating from 1.7.4.4 to 1.7.5.0 and immediately upgrade to 1.7.5.1?

**Comment by khouloudbelguith** [comment] 2019-01-28 14:58
@Apury, in fact, you need to make some changes in your Database.
You need to run those requests SQL on your Database

ALTER TABLE `PREFIX_supply_order_receipt_history` CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '';

ALTER TABLE `PREFIX_supply_order_receipt_history` CHANGE `employee_lastname` `employee_lastname` VARCHAR(255) DEFAULT '';

ALTER TABLE `PREFIX_order_detail` CHANGE `product_supplier_reference` product_supplier_reference varchar(64) DEFAULT NULL;
![image](https://user-images.githubusercontent.com/16067358/50828388-8e237080-1341-11e9-940a-eac03ad7c9fb.png)

ALTER TABLE `PREFIX_product_attribute` CHANGE product_supplier_reference product_supplier_reference varchar(64) DEFAULT NULL;

ALTER TABLE `PREFIX_product` CHANGE `reference` `reference` varchar(64) DEFAULT NULL;

ALTER TABLE `PREFIX_product_lang` CHANGE `meta_description` `meta_description` varchar(512) DEFAULT NULL, CHANGE `meta_keywords` `meta_keywords` varchar(255) DEFAULT NULL;

PS: **PREFIX** is the prefix of your tables, t could be for example ps.
Or, you can change those types manually in your database "Structure" tab.
![image](https://user-images.githubusercontent.com/16067358/50828925-17877280-1343-11e9-8aa3-d86294e92abb.png)

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Because the 500 Internal Server Error can be very frustrating and it is such a vague error.
Thanks!

**Comment by FabioReims** [comment] 2019-01-28 15:38
Well, that seems to surpass my competencies. If I enter `ALTER TABLE PREFIX_supply_order_receipt_history CHANGE employee_firstname employee_firstname VARCHAR(255) DEFAULT '';` into the SQL query field as an update It gets transformed into `UPDATE `ps_supply_order_receipt_history` SET `id_supply_order_receipt_history`=[value-1],`id_supply_order_detail`=[value-2],`id_employee`=[value-3],`employee_lastname`=[value-4],`employee_firstname`=[value-5],`id_supply_order_state`=[value-6],`quantity`=[value-7],`date_add`=[value-8] WHERE 1` which results in Unexpected character. (near[) errors. 

On the contrary, if I use the structure -> change tab my window looks quite a bit different than yours. resulting in this error: 

>  Query error:
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UNSIGNED NOT NULL AUTO_INCREMENT' at line 1

https://imgur.com/a/NJUlJc9

I guess I'll just wait for a 1.5.1 release and update then. Thanks for the effort.

**Comment by khouloudbelguith** [comment] 2019-01-28 15:43
Duplicate of #11812

**Closed as completed by khouloudbelguith** 2019-01-28 15:43 UTC
Labels: Duplicate, Autoupgrade, 1.7.5.0
