### ISSUE TITLE
Faceted search 3.0.X

### ISSUE THREAD

**Issue by tjorgensborg** [PrestaShop/PrestaShop#14003] opened 2019-05-28 14:27 UTC
**Describe the bug**
If you have the function **show products from categories** disabled you will in FO get no products in category if you have subcategories. 
This apply if you have products in the main category, but none of the products in the category is default to the main category.

**To Reproduce**
Go BO
Disable the **show products from categories**
Add a rule and choose a main category with subcategories.
Add some products to the main category which are default to other categories. 
You will in FO get no producs in category
Take the same products and make them default to the main category and there are showing in the FO. 

This worked in faceted search 2.2.1

**Additionnal information**
Testet on Prestashop 1.7.4.2 and 1.7.5.1 with same result
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-28 14:50
Hi @tjorgensborg,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1 & ps_factedseach v3.0.2 => NOK
![image](https://user-images.githubusercontent.com/16067358/58487902-51c1a700-8160-11e9-9d59-150c98f80599.png)

with ps_facetedsearch v2.2.0 => OK
![image](https://user-images.githubusercontent.com/16067358/58487854-3c4c7d00-8160-11e9-9747-c2914d6b1c6f.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-28 15:00
Hi @tjorgensborg,

Thanks for your report.
Yes, I have the same behavior with PS1.7.6.0beta1 & ps_factedseach v3.0.2
![image](https://user-images.githubusercontent.com/16067358/58487902-51c1a700-8160-11e9-9d59-150c98f80599.png)

with ps_facetedsearch v2.2.0
![image](https://user-images.githubusercontent.com/16067358/58487854-3c4c7d00-8160-11e9-9747-c2914d6b1c6f.png)

@marionf, what do you think, this is bug fix from v2 or regression in the v3?
You can follow this comment https://github.com/PrestaShop/PrestaShop/issues/13949#issuecomment-496119757.

Thanks!

**Comment by marionf** [comment] 2019-05-28 15:31
Hi @tjorgensborg 

Take the example of "clothes" category, by default you have 2 products in this category:
- Hummingbird printed sweater, with women as main category
- Hummingbird printed t-shirt, with men as main category

If you disable "show products from **subcategories**" in ps_facetedsearch and display "Clothes" category in FO, it's normal to not see these products because they belong to Men and Women categories as main.

![capture d'écran_1614](https://user-images.githubusercontent.com/13449658/58490972-66a53700-816e-11e9-8fbc-10a38d83c28c.png)

If you display "Men" category you will see Hummingbird printed t-shirt and if you dislpay "Women" category you will see "Hummingbird printed sweater"

![capture d'écran_1613](https://user-images.githubusercontent.com/13449658/58490981-6a38be00-816e-11e9-9666-54e6936473e1.png)

![capture d'écran_1612](https://user-images.githubusercontent.com/13449658/58490989-6d33ae80-816e-11e9-8f77-2c5a71d383f3.png)

**Comment by tjorgensborg** [comment] 2019-05-28 16:10
Hello @marionf
Yes its true what you have testet, BUT if you try to add some products from Women to Clothes you still will not be able to see it if you dont make Clothes your default category. With version 2.2.1 you can have products that does not have cloths as default category and still see them. If you have disabled the show products from subcategories you cant even see products in main categories that are not using faceted search. I will give you some examples.
Here is example 1
No faceted search  filter in backend.
<img width="1204" alt="Skärmavbild 2019-05-28 kl  17 50 43" src="https://user-images.githubusercontent.com/50947207/58492480-4460e880-8171-11e9-9e83-494bff6c63a6.png">
Result
<img width="1184" alt="Skärmavbild 2019-05-28 kl  17 48 34" src="https://user-images.githubusercontent.com/50947207/58492523-59d61280-8171-11e9-8c65-bd7ccd678952.png">
Should have shown
<img width="1148" alt="Skärmavbild 2019-05-28 kl  17 53 24" src="https://user-images.githubusercontent.com/50947207/58492604-8722c080-8171-11e9-9f84-b6bf011c0e92.png">
Only way to make that happen is to disable the faceted search

Example 2.
Im creating a layer for facetet search displaying a main category with some subcat and I am only using the main category for faceted search in this example. And Show subcategory is still disabled.
Here you see only 2 products the reson is because they have "abc utstyr" as default category
<img width="1149" alt="Skärmavbild 2019-05-28 kl  18 01 31" src="https://user-images.githubusercontent.com/50947207/58493191-ae2dc200-8172-11e9-84d1-2300c000d1f2.png">

but in "abc utstryr" there is 6 products, again only way to show those six products is to disable the module OR use show products from subcategories set to enabled BUT then you show all products in all subcat (which its right)
<img width="1197" alt="Skärmavbild 2019-05-28 kl  18 00 47" src="https://user-images.githubusercontent.com/50947207/58493314-f64ce480-8172-11e9-8701-517b2ed70f66.png">

In faceted search 2.2.1 when show products from subcategories was disabled it show products in the category, it did not matter if it was default or not to that category. 

The bug is that its only showing default category products not all products in the specific category.

**Comment by venditdevs** [comment] 2019-05-29 09:40
We can confirm this is an issue since the update. If we choose to show a product in multiple categories( subcategories) then the faceted search doesn't need to interfere if the switch 'Show subcategory' is set to off.

**Comment by khouloudbelguith** [comment] 2019-05-29 09:47
Hi @marionf,

This issue is reproduced if:

- Hummingbird printed t-shirt: is selected to Home, Clothes, Men: Clothes is the main category

![image](https://user-images.githubusercontent.com/16067358/58547189-d7942f80-81fe-11e9-9e53-4cafd655c4bf.png)

In the FO with ps_factedsearch v3

In the "Clothes" category `Hummingbird printed t-shirt` is displayed => OK
In the "Men" category `Hummingbird printed t-shirt` is not displayed => it is not the same behavior with ps_factedsearch v2

Thanks!

**Comment by PierreRambaud** [comment] 2019-05-29 15:36
Yes, it's not the same, but it was a bug.
The button "Show products from subcategories" is here to only display products which are in the "Main category" not the latest one.
Otherwise where it should be displayed if you have this:
![image](https://user-images.githubusercontent.com/1462701/58570390-2dd19480-8238-11e9-8d30-98d955a13485.png)

**Comment by marionf** [comment] 2019-05-29 16:10
Yes, as @PierreRambaud said, I think there was an issue before and it's the correct behavior now

**Comment by chrisvanberg** [comment] 2019-05-30 08:37
Hello, I have the same problem on my shop after upgrading to ps_factedsearch v3..

@marionf could you explain how it is the correct behavior now ? If a product is selected in a category (other than the main category). The product should be visible in the FO even if the setting of ps_factedsearch v3 is "Show subcategory" is off ?

Thanks for the explanation :)

**Comment by tjorgensborg** [comment] 2019-05-30 08:55
Hello @marionf and @PierreRambaud 
I dont know how to explain it better but I will try. 
When **show products from subcategories** is enabled/Yes every thing is working the way its intended  to do, so we dont to put more time on that function, its OK.

This is only when **show products from subcategories** is disabled/off and I will try to give you some examples of the bug.

1. When you have a catalog like this called new products (Nye produkter) you have products taken from other categories to put there under a short time or it could be other reasons why not all products in a catalog is defaulted to this catalogue. In first example I DONT have any faceted search template att all. Only **show products from subcategories**
<img width="1288" alt="Skärmavbild 2019-05-30 kl  10 39 37" src="https://user-images.githubusercontent.com/50947207/58620670-f3173d00-82c7-11e9-8df3-7c0baa5ba390.png">
Not it should show this products.
<img width="1285" alt="Skärmavbild 2019-05-30 kl  10 39 00" src="https://user-images.githubusercontent.com/50947207/58620697-09bd9400-82c8-11e9-9936-b1557af07e83.png">
This is the result.
<img width="1103" alt="Skärmavbild 2019-05-30 kl  10 46 09" src="https://user-images.githubusercontent.com/50947207/58620759-2d80da00-82c8-11e9-9e33-ce6f5a5cc7fc.png">
Is only showing products defaulted to the category and not all products. In this case where I dont have a faceted search template it should not affect anything. 
This happen when I disable the faceted search
<img width="914" alt="Skärmavbild 2019-05-30 kl  10 49 07" src="https://user-images.githubusercontent.com/50947207/58621083-e34c2880-82c8-11e9-871f-0732d534a82c.png">
All the products from the cataloge shows. 
So only way to have normal prestashop function is to disable the faceted search. 

When you have disabled  **show products from subcategories**  it should show all products in the category not only the one defaulted to the category.

**Comment by PierreRambaud** [comment] 2019-05-31 08:36
I'm not able to reproduce your behavior:
![image](https://user-images.githubusercontent.com/1462701/58692862-cc243e00-838f-11e9-80db-5e81608360a0.png)

No product with main category in Clothes:
![image](https://user-images.githubusercontent.com/1462701/58692882-db0af080-838f-11e9-876c-a4e8c76c123e.png)
But I've one for Men:
![image](https://user-images.githubusercontent.com/1462701/58692897-e3632b80-838f-11e9-9f50-08dfe346df17.png)
And one for women:
![image](https://user-images.githubusercontent.com/1462701/58692916-ebbb6680-838f-11e9-9efc-a6172e1164e2.png)

Exactly like in the BO:
![image](https://user-images.githubusercontent.com/1462701/58692942-fb3aaf80-838f-11e9-86f1-49dee474a7c2.png)

**Comment by tjorgensborg** [comment] 2019-05-31 09:55
Hello @PierreRambaud 

If I understand correctly you are reproducing the error the error in this case is that is not showing the products in Clothes. In you example If I see right it should have shown Hummingbird sweater and printed T shirt. It should not ONLY taking the main category products like its doing now. It should show all products in Clothes. Only way to show all products in cloths (2 products in your case) is to disable the faceted search module. 

Faceted search should not  check after main category products in a category it should show all products in that category (main and other) like its done without the faceted search module installed. When you have **Show products from subcategories disabled** This is how it works in 2.2.1.

**Comment by Multipage** [comment] 2019-06-03 07:50
> Hello @PierreRambaud
> 
> If I understand correctly you are reproducing the error the error in this case is that is not showing the products in Clothes. In you example If I see right it should have shown Hummingbird sweater and printed T shirt. It should not ONLY taking the main category products like its doing now. It should show all products in Clothes. Only way to show all products in cloths (2 products in your case) is to disable the faceted search module.
> 
> Faceted search should not check after main category products in a category it should show all products in that category (main and other) like its done without the faceted search module installed. When you have **Show products from subcategories disabled** This is how it works in 2.2.1.

And should work in version 3.0.X. Somebody fixed something that wasn't broken. Undo this fix plz!

**Comment by chrisvanberg** [comment] 2019-06-03 07:57
Hello, I understand that the 3.0.X may work as intended, but since 2.2.1 worked in a certain way, the update broke two of my shops (Some plugins also need that the option "show products from subcategories" is disabled)

For example, after the update, one of my main categories went from "1260 products" to only four products. If I activate "show products from subcategories", they went back, but the plugin that I use to sort the product wasn't working anymore. So I had to recompile the 2.2.1 in order to fix my shop...

You should make a warning in the changelog that appear on the B.O.

Have a nice day

**Comment by colinegin** [comment] 2019-06-06 09:27
Hello all,

I can see there's a lot of interest with this topic ! :-)
Let me try to synthetise what you all said and what i understand : 
- the new faceted search version fixes something which we considered a bug but : 
1. some of you prefered the previous behaviour with the "show products from subcategories" option
2. some plugins are working according to the behaviour of the previous faceted search version, and with the new one, they no longer work.
3. For some of you, the new version brings important changes in the product results. 
- i feel that there is a misunderstanding of the difference between default / main category, subcategories, and parent / child categories.

My questions are : 
- you used to leave the option for subcategories disabled, but can't you just enable it in the new version? What does it change for you (except the issue with added plugins) ?
- isn't it possible to just change the default category of your products ? Does it have any impact for you ?

Thanks for your feedbacks !

Have a nice day,

Coline from Product team

**Comment by tjorgensborg** [comment] 2019-06-06 11:11
Hello @colinegin 
I will once again try to explain but first we need to add try to use same words every one, so I am trying to define some words here so will all use same syntax.
<img width="310" alt="cat" src="https://user-images.githubusercontent.com/50947207/59026034-d645b100-8855-11e9-8c55-ee18be32481e.png">

**Main category** is the category is the top category and can have subcategories but dosen´t need to have subcategories.
**Subcategories** is categories under main categories
**Default catalog** is the catalog if make a search from FO you will be redirected to or in other word home/default/main catalog for the spesific product. 

1. In faceted search when **show subcategories are enabled** everything works (can´t say anything about modules), so I dont think thats an issue.

2. In faceted search when **show subcategories are disabled** problem starts.

**Problem one.**
It will only show default catalog products so in the image I have subbmitted I would get  "error" no products in catalog, because all my products in that main catalog have other default categories.
Of course right way is to show all products in that category (default category products and non default categories product if they are pined to the catalog.

Example: If you create a catalog where you want to show cool products  and add products from other catalogs to cool products catalog.You will get no products in catalog in FO.

**Problem 2.**
If you dont want to use faceted search in above examples you still get "no products in catalog EVEN if faceted search is not applied. ONLY way too see the products in a specific catalog (default or not) is to disable faceted search module. Faceted search is overriding  prestashop core function even on catalogs you dont want to use faceted search.

**Solution**.
Make faceted search great again :-). 
When show subcategories disabled faceted search should not make a any diffrence on default category products and not default categories products only show products in that specfic catalog.

This function is in version 2.2.1

**To answer your question.**
_you used to leave the option for subcategories disabled, but can't you just enable it in the new version? What does it change for you (except the issue with added plugins) ?__
Yes that work work execpt I cant controll the layout of products meaning, I cant move products up and down to get the optimized result to promote what I want to promote. If you have subcategories, you cant controll how the products are displayed. 
Example. we are selling diving lights and we want to have spareparts in the bottom but now it using position from each sub cat to display I think it looks like this pos1 sub1, pos1 sub2 pos1 sub3, pos 2 sub 1 etc etc. here is a real live example
https://fue.no/dykkerutstyr/lykter/
This not the way we want to display the products

_isn't it possible to just change the default category of your products ? Does it have any impact for you ?_
No but its lot of work when you move products like in my example with a catalog with cool stuff. If like we have 3000 products it will take a looooot of time.

**Comment by PierreRambaud** [comment] 2019-06-06 12:14
![image](https://user-images.githubusercontent.com/1462701/59031604-70145a80-8864-11e9-9255-bb486e3fbd50.png)
As you can see on the top right corner, it's write `Main category` not `Default category`.

You're talking about how you manage your categories, with only one level of category
In my situation, and if I take your definitions.
- `Clothes` is the main category for `Women` but not for `Men` and is not a subcategory of `Home`
- `Men` is the `Main category` for `Awesome subcategory` and not a subcategory for `Men`
- `Women` is a subcategory for `Clothes`

it's really confusing :thinking:

**Comment by colinegin** [comment] 2019-06-07 14:08
With your definition, if I understand well, the "home" category should be the main category of ABC utstyr, right ?

To be able to take the right decision on this feature, we need more feedbacks from other types of usage. Once we agree on the best option behaviour, we will update the module. In the meantime, if the 2.2.1 version of the module suits your needs, we advise you to stay with it.

Thanks again for your feedback and your understanding !

**Comment by AndreaC71** [comment] 2019-09-22 19:31
I cannot update from v.2 to v.3 due to this problem, when will be solved?

**Comment by deadbloger** [comment] 2019-11-13 18:24
> 
> 
> I cannot update from v.2 to v.3 due to this problem, when will be solved?

Well, the main question will it be solved or not? 
I spent a day trying to understand what broke my shop. Backed to 2.2.1. It helped but it seems abnormal at PS 1.7.6.1 
![faceted](https://user-images.githubusercontent.com/29161107/68792164-e3b06400-065b-11ea-91a6-ea46311d9382.png)

**Comment by khouloudbelguith** [comment] 2019-11-14 08:30
Hi @deadbloger,

In my case, I did not manage to reproduce the issue with PS1.7.6.1 & ps_facetedsearch v3.4.0 using the theme by default.
I attached a screen record
https://drive.google.com/file/d/1m-i6czzZSg9QqHA7a-NaH46FJJ1PbuSu/view
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-26 14:27
Hi @colinegin, @marionf,

We need also to specify those cases: (reproduced with PS1.7.6.2 & ps_facetedsearch v3.4.0)

I have two products set in this way
![t-shirt](https://user-images.githubusercontent.com/59253436/71478102-1c606300-27ee-11ea-8351-2bb8d7ed5778.png)
![sweater](https://user-images.githubusercontent.com/59253436/71478101-1c606300-27ee-11ea-8f5b-4f01ac6cf09e.png)

I want to show "t-shirt" in both "men and clothes categories".
Instead, I want to show "sweater" only on the "women category".

Unfortunately "clothes" category shows both products
![Clothes](https://user-images.githubusercontent.com/59253436/71478099-1bc7cc80-27ee-11ea-80f8-511b547bcf45.png)

The second product shouldn't be displayed in the Clothes category because it is not selected for this product
https://github.com/PrestaShop/PrestaShop/issues/16925#issuecomment-569062534

Thanks!

**Comment by francct** [comment] 2019-12-26 14:50
Hi, @khouloudbelguith
I need to say a clarification.

It shows correctly both products, when "Show products from subcategories" is enabled.

The problem is when "Show products from subcategories" is disabled, because it doesn't show any product. In this specific case it should only show "t-shirt".
![clothes_2](https://user-images.githubusercontent.com/59253436/71479939-f25f6e80-27f6-11ea-9b8a-05ec5a331e4d.png)

**Comment by gadnis** [comment] 2020-01-16 16:28
@marionf @PierreRambaud 
So is it going to be fixed or it is not an issue?

**Comment by gadnis** [comment] 2020-02-22 17:46
Ok. No one wants to change this, so I did 😁

Here is pull request: [https://github.com/PrestaShop/ps_facetedsearch/pull/158](https://github.com/PrestaShop/ps_facetedsearch/pull/158)

I hope @marionf @PierreRambaud will approve it, cause other way I will always need to update it my self after new release 😁 

![Screen Shot 2020-02-22 at 19 45 49](https://user-images.githubusercontent.com/10948341/75096819-fbc54700-55ab-11ea-86b6-f287ff913e18.png)

**Comment by PierreRambaud** [comment] 2020-02-24 08:38
@gadnis This option is the same as `Show products from subcategories` only the wording differ :thinking:

**Comment by gadnis** [comment] 2020-02-24 08:40
@PierreRambaud are you talking about php code or just formulation of the switch button title?

**Comment by PierreRambaud** [comment] 2020-02-24 08:50
Talking about the behaviour

**Comment by gadnis** [comment] 2020-02-24 08:53
@PierreRambaud, behaviour is different. 
With my option on, merchant can add product to whatever category they want and the product will be shown in those categories only (not in all the tree with subcategories).

**Comment by marionf** [comment] 2020-02-24 10:51
Hello @gadnis 

Your option seems to do exactly the same thing as "show products from subacategories", only the wording is different

Display product from subcategories on yes:

![display product from subcat yes](https://user-images.githubusercontent.com/13449658/75146546-a435f100-56fb-11ea-9769-0c0ee1911555.png)

Display product from subcategories on no:

![display product from subcat no](https://user-images.githubusercontent.com/13449658/75146581-b31ca380-56fb-11ea-8eac-790ab2165ad7.png)

Show products only from default category on no:

![Show products only from default category no](https://user-images.githubusercontent.com/13449658/75146611-c16abf80-56fb-11ea-8c2e-03cd905bd3e3.png)

Show products only from default category on yes:

![Show products only from default category yes](https://user-images.githubusercontent.com/13449658/75146666-d8111680-56fb-11ea-88f3-7c30e046fe73.png)

**Comment by gadnis** [comment] 2020-02-24 11:17
@marionf 
I believe that you have none products in accessories category at all, only in the main category. Like the example here:
![Screen Shot 2020-02-24 at 13 08 56](https://user-images.githubusercontent.com/10948341/75147937-1fe96b00-5707-11ea-90ac-453e443fd347.png)

Try do this:
![Screen Shot 2020-02-24 at 13 09 07](https://user-images.githubusercontent.com/10948341/75147982-37c0ef00-5707-11ea-93ad-c9c5762afdf3.png)

And then with options:

- Show products only from default category on NO
- Display product from subcategories on NO

Go to category "Stationery" and than "Art". You will see there is that product inside both of categories. But none in subcategories (unless they checked).

**Comment by marionf** [comment] 2020-02-25 10:42
Ok @gadnis I get it, your option make sens but we have to make the 2 options work together
@PierreRambaud will have a look to adapt your PR

**Comment by marionf** [comment] 2020-02-26 17:30
Hello @tjorgensborg @venditdevs @Multipage @chrisvanberg @deadbloger @AndreaC71 @francct
Could you test the PR https://github.com/PrestaShop/ps_facetedsearch/pull/158 of @gadnis and tell us if it meets your needs ?
Thank you

**Comment by francct** [comment] 2020-02-27 11:49
Hi @marionf,
Unfortunately I'm new to git/github.

I've cloned locally prestashop dev, and i've already run composer.
Please, can you explain me how to "merge" the branch of this PR, and how to compile assets (i have node.js)?

Thank you.

**Comment by francct** [comment] 2020-02-27 21:33
Hi @marionf @gadnis,
I was able to do the test (I merged the PR with branch 1.7.7.x), and it works correctly.
There is just an issue, because I can easily force both the "show from subcategory" and "only from default category" status to YES, and of course it's a wrong condition.

![Screenshot (8)_LI](https://user-images.githubusercontent.com/59253436/75488650-09663c80-59b1-11ea-8480-1f5b465ce93b.jpg)

 As a merchant I can say it's an important feature, so thank you!

**Comment by gadnis** [comment] 2020-02-27 21:38
@francct you probably forgot to run terminal command: `npm run build` ? There is changes in js files made but you have to build assets manually

**Comment by francct** [comment] 2020-02-27 22:05
I'm sorry, I didn't know I had to compile assets. I've never used Webpack.
Please, can you explane me how to do? I've node.js installed. Which commands should I run and in which directory?

**Comment by francct** [comment] 2020-02-27 23:24
Hi @gadnis
I'm sorry, I initially forgot to run `npm run build`.
Now I have run `npm install` and `npm run build` inside `ps_facetedsearch` directory, but i can still set YES on both buttons.

Maybe I'm doing something wrong.

**Comment by gadnis** [comment] 2020-02-28 06:32
@francct you need to clear cache in performance section and clear browser cache. Maybe that’s the case

**Comment by francct** [comment] 2020-02-28 09:25
@gadnis I cleared the cache from the performance section and cleared the browser cache.
I attach the video [https://youtu.be/hStKB2blFZw](https://youtu.be/hStKB2blFZw)

**Comment by PierreRambaud** [comment] 2020-02-28 13:01
@francct You maybe need to read the notice under the Switch button :roll_eyes:

**Comment by francct** [comment] 2020-02-28 19:46
@PierreRambaud I underlined it in [this comment](https://github.com/PrestaShop/PrestaShop/issues/14003#issuecomment-592187616)
Anyway, the functionality is perfect! Thank you so much @gadnis!

**Comment by marionf** [comment] 2020-03-02 10:01
Thank you for your feedback @francct, it should be ok now
When "Show products only from default category" is on Yes then "Display products from subcategories" goes on No and becomes disabled

**Comment by Progi1984** [comment] 2020-03-13 13:21
Fixed by PrestaShop/ps_facetedsearch#158

**Closed as completed** 2020-03-13 13:21 UTC
Labels: Bug, FO, Faceted search, Fixed, 1.7.6.0
