### ISSUE TITLE
foreach() during checkout process Prestashop 1.7.6.4

### ISSUE THREAD

**Issue by davidhardik** [PrestaShop/PrestaShop#19770] opened 2020-06-16 05:01 UTC
#### Describe the bug

When I turn on the debug mode while checking out it shows me foreach() error in ProductLazyArray() in the function getAttachements(). And it is happening whenever I turn on the debug mode and go to checkout page. 

It is happening in default theme and default installation of prestashop also.

#### Expected behavior

It shouldn't give any error during checkout when debug mode is on.

#### Steps to Reproduce

1. Download Prestashop
2. Activate it
3. Put the products and make the URL friendly
4. Put SSL
5. Turn on Debug Mode
6. Try to go to order/checkout page
7. Error will occur

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

**Comment by florine2623** [comment] 2020-06-17 13:08
Hi @davidhardik ,
Could you use PHP 7.2 ?
Here are the system requirements of PrestaShop : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by colinegin** [comment] 2020-06-17 15:11
ping @PrestaShop/prestashop-core-developers could you please try to reproduce this issue ?

**Comment by sarahdib** [comment] 2020-07-07 12:00
Hi @davidhardik 

Like @florine says Could you use PHP 7.2 ?
Here are the system requirements of PrestaShop : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Closed as completed by sarahdib** 2020-07-07 12:00 UTC
Labels: No change required, 1.7.6.4
