### ISSUE TITLE
Product UnitPrice should be allowed to be Zero even when displayed

### ISSUE THREAD

**Issue by gregoire-jianda** [PrestaShop/PrestaShop#34418] opened 2023-10-30 09:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the new admin product form, when unit price display is enabled, the unit price field becomes mandatory and enforces a positive value : 
<img width="747" alt="Screenshot 2023-10-30 at 09 53 03" src="https://github.com/PrestaShop/PrestaShop/assets/2151352/d414a5e9-d7c0-430f-92ac-c2ae867ab7d1">

However, you can have a product with a unit price set to zero and various unit price impacts on its combination. This rule should not be enforced (and was not with to old product form).

### Expected behavior

The unit price field should only enforce a non blank positive **or zero** value

### Steps to reproduce

1. Edit a product in the admin
2. Go to the price tab
3. Enable unit price display
4. Set the unit price to 0
5. Save and publish

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.0

**Comment by Hlavtox** [comment] 2023-10-30 09:31
@gbelorgey Hi, this is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/34260, but I accepted your PR and I will put proper label on the other issue. :-)

**Comment by MatShir** [comment] 2023-10-31 09:13
duplicate of https://github.com/PrestaShop/PrestaShop/issues/34260

**Closed as completed by MatShir** 2023-10-31 09:13 UTC
Labels: Bug, Duplicate
