### ISSUE TITLE
Autoupgrade: the CLI action backupFiles or backupDb are not possible

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29305] opened 2022-08-10 19:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Use the CLI of autoupgrade module, you are able to execute specific actions.

Two of them is backupFiles and backUpDb. Two of them require the init of datas (backup names) but this action is only done while the step is upgradeNow.

### Expected behavior

Be able to use theses actions.

### Steps to reproduce

`php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --action=backupFiles`

### PrestaShop version(s) where the bug happened
8.0.0

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by HanaRebaiQA** [comment] 2022-08-11 13:48
Hello @PrestaEdit 

Could you please provide us more information about How to test this issue ? please give us more details about the steps to reproduce attached with a screen-record OR a screen-shot ?
Also, please specify the PrestaShop version !

Thank You!

**Comment by PrestaEdit** [comment] 2022-08-11 13:49
It's there : 

> Steps to reproduce
> 
> php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --action=backupFiles

You need to execute this on CLI.

**Comment by HanaRebaiQA** [comment] 2022-08-11 13:50
Which PrestaShop version did you used ?

Thanks!

**Comment by PrestaEdit** [comment] 2022-08-11 13:52
Every version but you can use the 8.0.0-beta.1 or the latest 1.7 version ; you need the autoupgrade module into it's latest version.

**Comment by HanaRebaiQA** [comment] 2022-08-11 16:51
Hello @PrestaEdit 

I have checked with **PS8.0.x** and **PS1778** and i have these warnings when execute this command 
`php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --action=backupFiles` with CLI when the `autoupgrade v4.14.2 ` module is installed

![image](https://user-images.githubusercontent.com/92912932/184189689-09b4454b-7754-43f4-bc41-9ebce8d82810.png)

**PS8.0.x** 

https://user-images.githubusercontent.com/92912932/184189895-17bfdc6c-880b-42b4-a29d-532bc308c115.mp4


**PS1778** 

https://user-images.githubusercontent.com/92912932/184189835-798751de-c743-4ef3-b945-613336f80da8.mp4



Do you confirm is this your reproduced issue ?

Thank You!

**Comment by PrestaEdit** [comment] 2022-08-11 17:29
You need the 4.13 at least of the autoupgrade module, it's seems to be good.
In my own case, it's the 4.14.0.

And this is the result of the CLI call :

> ➜ php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --action=backupFiles
> INFO - === Step backupFiles
> INFO - Error during backupFiles
> ERROR - [ERROR] backupFiles filename has not been set

**Comment by hibatallahAouadni** [comment] 2022-08-16 16:58
Ping @PrestaShop/prestashop-maintainers can someone please try to reproduce the issue :pray: 
I didn't manage to reproduce :disappointed: 

Thanks in advance!

**Comment by hibatallahAouadni** [comment] 2023-08-31 15:09
Hello @PrestaEdit 

Do you still encounter the issue with PS8.1.1? 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-18 07:53
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-09-18 07:53 UTC
Labels: Bug, CO, Autoupgrade, Invalid, Module, 8.1.x
