### ISSUE TITLE
Html code in the meta description preview admin site in prestashop 8.1.5

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#35803] opened 2024-04-02 16:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've seen that in the meta preview of SEO section appears the html code, if the meta description is not set

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/2e385686-8fd1-439b-bcdc-15fcfe1cd0d3)

bye

### Steps to reproduce

1. go to the product from the admin side
2. set some text in the short description
3. go in the SEO section
4. do not set any text in the meta description
5. look the meta preview

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment] 2024-04-03 05:28
Duplicate

**Comment by paulnoelcholot** [comment] 2024-04-03 09:18
Hello, @maofree

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #35676.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment] 2024-04-03 09:19
Duplicate of #35676

**Closed as completed by paulnoelcholot** 2024-04-03 09:19 UTC
Labels: Bug, Duplicate
