### ISSUE TITLE
Import via csv - image download in another location - folder permissions issue

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#36251] opened 2024-05-27 21:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Create a file csv, with image urls (my file the location of image is not local, is stored in another domain/server)

Upload file, and run.

The folders have a chmod 775 and if i change all folders to 777 the upload goes

The server log
<img width="476" alt="Captura de ecrã 2024-05-27 222207" src="https://github.com/PrestaShop/PrestaShop/assets/54105234/6651ea16-428b-4d37-a147-3740c49c2540">

### Expected behavior

Import sucess, with images located in server, with file/folder correct location

### Steps to reproduce

1 - Upload csv
2 - Id and URL (outside server location, didn´t test it with local images)
3 - See product list results (image alternate text instead) 

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment] 2024-05-30 14:49
Hi @Borgas 

Thank you for your report, Currently I tried to reproduce your issue but I can't as you can see : 

[recording(223).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/9824ddca-af9a-4c18-bbb7-eaefaf454a70)

Did I miss something ? 

Waiting for your feedback

**Comment by paulnoelcholot** [comment] 2024-06-24 14:27
Hello @Borgas,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-06-24 14:27 UTC
Labels: Bug, BO, Can't reproduce, Import / Export, 8.1.x
