### ISSUE TITLE
Emails for product returns not received

### ISSUE THREAD

**Issue by valentin-harrang** [PrestaShop/PrestaShop#34915] opened 2023-12-26 15:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I installed Mail Alerts module on Prestashop 1.8.9 and I receive emails about new orders and stock shortages but I don't receive emails about product returns when a customer enters their email address to request a product return.

My SMTP configuration is correct because all emails are sent except for product returns.

How can I correct this problem?

Thank you

### Steps to reproduce

1. Install Mail alerts module (v2.4.2 on Prestashop 1.7.8.9)
2. Go in Mail alerts module from back-office
3. Click on the "Returns" toggle to enable it
4. Fill "Send to" field by your email address
5. On the store front, go to the product page of the product that is out of stock, enter your email address and click on the button to be notified
6. Put the product in stock and check your emails

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts v2.4.2

**Comment by florine2623** [comment] 2023-12-27 10:32
Hello @valentin-harrang ,


- If you want to receive the emails for Out-of-stock product, you need to enable Out-of-stock notifications.
<img width="814" alt="Screenshot 2023-12-27 at 11 26 48" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5640ab3b-3146-47c0-8385-1704399f7f06">

You will receive this email when stock is added to the product.
<img width="581" alt="Screenshot 2023-12-27 at 11 28 41" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4c606f50-b20b-454f-b8ab-ffb4cb570cb3">

- If you want to receive the email for Returns, you need to enable the Merchandises return in Customer Service > Merchandise returns. When a customer wants to return a product, the merchant will receive this email :

<img width="886" alt="Screenshot 2023-12-27 at 11 30 24" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/89099b95-72df-4e24-8ce7-c479ee39cf4b">

I can't reproduce your issue. So I am closing it.

**Closed as completed by florine2623** 2023-12-27 10:32 UTC
Labels: Bug

**Comment by valentin-harrang** [comment] 2023-12-27 14:04
@florine2623 That's the problem. The "Out-of-stock" option is enabled but the emails are not received .. For the other enabled options, emails are received correctly
