### ISSUE TITLE
2 decimal on Prestashop 1.7.6

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#15263] opened 2019-08-26 14:30 UTC
Prestashop 1.7.6 on debian 9
despite my setting has always been with 2 decimals
https://nimb.ws/LBoM7f
in this new version often the product prices are displayed with 4/5 decimals
https://nimb.ws/ya3UI6

**Comment by khouloudbelguith** [comment] 2019-08-26 14:39
Hi @centoasa,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14664 to fix the issue
Your ticket is a duplicate of #14640
So, I close it.
For a quick fix, you can run this SQL command on your Database
UPDATE `ps_currency` SET `numeric_iso_code` = '978', `precision` = '2' WHERE `ps_currency`.`id_currency` = 2; 
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-26 14:40
Duplicate of #14640

**Closed as completed by khouloudbelguith** 2019-08-26 14:39 UTC
Labels: Duplicate

**Comment by centoasa** [comment] 2019-08-26 14:55
Mistake
Static analysis:

4 errors were found during the analysis.

Unexpected Token. (near "," at position 47)
Key word not recognized. (near "precision" at position 49)
Unexpected Token. (near "=" at position 59)
Unexpected Token. (near "'2'" at position 61)
SQL query:

UPDATE ps_currency SET numeric_iso_code = '978', precision = '2' WHERE ps_currency.id_currency = 2

MySQL message: Documentation

# 1064 - Syntax error in the SQL query near 'precision =' 2 'WHERE ps_currency.id_currency = 2' line 1

**Comment by centoasa** [comment] 2019-08-26 15:12
UPDATE `ps_currency` SET `numeric_iso_code` = '978', `precision` = '2' WHERE `ps_currency`.`id_currency` = 1
