### ISSUE TITLE
dynamic update of product and tax prices when editing order in the back office

### ISSUE THREAD

**Issue by psandmore** [PrestaShop/PrestaShop#16498] opened 2019-11-21 15:30 UTC
**Describe the bug**
After editing order in the back office the products price and tax not dynamically updated.

**To Reproduce**
1. Configure user group to display prices tax excluding.
2. Create and order with any product.
3. Before order shipped, edit the order in the back office. Change quantity or price.
4. Confirm update.
5. The changed total price appears correctly on the order page. However the products price and tax in the summary are incorrect.

**Additional information**
PrestaShop version: 1.7
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-11-21 15:44
Hi @psandmore,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15528
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-21 15:44
Duplicate of #15528

**Closed as completed by khouloudbelguith** 2019-11-21 15:44 UTC
Labels: Duplicate
