### ISSUE TITLE
FO - Button of file field in customization product has a smaller height rather than its field

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#30071] opened 2022-10-19 15:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In my customizable product, I have the file field to put an image. But the button "Choose file" has a smaller height rather than its field
Tested on 1.7.8.x/8.0.x branches and 1.7.7.8 version. No regression same bug on all versions

![customization-button-not-aligned-button-view](https://user-images.githubusercontent.com/2854834/196730288-5d611dce-e9a7-406c-a675-be1b670292cd.png)

- 1.7.7.8 ❌ 
![1778-customization-button-not-aligned-product-view](https://user-images.githubusercontent.com/2854834/196730327-9ca7f32e-d488-4c8c-b867-4ed130f0aa8d.png)

- 1.7.8.x ❌ 
![178x-customization-button-not-aligned-product-view](https://user-images.githubusercontent.com/2854834/196730373-d4727a63-1d43-42e1-b1e1-edbc117d08be.png)

- 8.0.x ❌ 
![80x-customization-button-not-aligned-product-view](https://user-images.githubusercontent.com/2854834/196730459-434ab523-454a-46f5-96d8-d7746e004344.png)

### Expected behavior

"Choose file" button should have the same height than its field

### Steps to reproduce

1. Go to BO > Catalog > Products > Edit "Customizable mug" product
2. Go to "Options" tab in product page V1 or "Specifications" tab in product page v2 > Go to "Customization" section
3. Click on "Add a customization field" button > Write a label and choose the "File" type, no need to be required
4. Click on "Save" button > Click on "Preview" button
5. On the FO tab just opened, see error

### PrestaShop version(s) where the bug happened

8.0.x / 1.7.8.x / 1.7.7.8

### PHP version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment] 2022-10-20 16:09
Hello @sLorenzini 

Thanks for your report. 
I was able to reproduce your issue with PS1787.

![image](https://user-images.githubusercontent.com/92912932/197001548-d201055a-d246-4533-be70-0ab0ba394df6.png)


I'll add this to the debug backlog so that it's fixed.

Thank You!

**Comment by Arpit-Gulgulia** [comment] 2022-10-27 16:06
Setting padding-bottom to the button `padding-bottom: 0.8rem;`  OR  `height: inherit;` will solve the issue.
Below is the snapshot.
![image](https://user-images.githubusercontent.com/48010798/198341505-a75e9cb1-b54f-4352-a728-7ca0afab773c.png)

Please let me know if I can push the changes.
Thanks!

**Comment by Arpit-Gulgulia** [comment] 2022-10-31 13:18
> Setting padding-bottom to the button `padding-bottom: 0.8rem;` OR `height: inherit;` will solve the issue. Below is the snapshot. ![image](https://user-images.githubusercontent.com/48010798/198341505-a75e9cb1-b54f-4352-a728-7ca0afab773c.png)
> 
> Please let me know if I can push the changes. Thanks!

@sLorenzini, @HanaRebaiQA is the issue open to working on? If yes, can I make a PR for the fix?

**Comment by HanaRebaiQA** [comment] 2022-10-31 13:27
Hello @Arpit-Gulgulia 

Yes! Of course. 
We are waiting for your PR. Good luck!

Thanks!

**Comment by Arpit-Gulgulia** [comment] 2022-10-31 20:10
HI @HanaRebaiQA, @jolelievre the issue is with the classic theme, so I created the PR for [PrestaShop/classic-theme](https://github.com/PrestaShop/classic-theme) repo.
Below is the PR link:-
[Fix:30071 Button of file field in customization product has a smaller height rather than its field](https://github.com/PrestaShop/classic-theme/pull/70)

Please review the changes and let me know if I missed something.
Thanks

**Comment by matks** [comment] 2022-12-20 13:55
Fixed in classic-theme 2.0.7 that should be embedded in PrestaShop 8.0.1

**Closed as completed** 2022-12-20 13:55 UTC
Labels: Bug, Trivial, FO, Product customization, Front-end, Good first issue, 1.7.7.8, Verified
