### ISSUE TITLE
Strange price round in BO Product List vs Product Edit

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#17704] opened 2020-02-17 17:52 UTC
Hi,

i still  loading some products in BO and specify a Price (tax included) of 5.0€
Automatically PS calculate the value without tax (see pic)

![image](https://user-images.githubusercontent.com/16102074/74676305-05b70680-51b6-11ea-968f-bb2aed4ce99b.png)

I save the product and in the product list i see correctly the 5.0€ price (see pic)

![image](https://user-images.githubusercontent.com/16102074/74676397-3b5bef80-51b6-11ea-8c0f-b54bdaceb4d1.png)

Now if you edit again the product the Final Price (tax included ) is changed like:

![image](https://user-images.githubusercontent.com/16102074/74676448-5a5a8180-51b6-11ea-8f8a-4673457e2341.png)

My round/decimal parameters are:

![image](https://user-images.githubusercontent.com/16102074/74676548-870e9900-51b6-11ea-966c-e913b7fb43e1.png)

That is a problem!
How is possible to solve that?

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2.26

**Comment by didi-2018** [comment] 2020-02-17 20:47
@HartLarsson  But in FO you will get 5.00 € right? What happens if you add an amount tax excluded 4.098360 ?

**Comment by SD1982** [comment] 2020-02-18 09:44
Ping @HartLarsson  We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of [ #12078](https://github.com/PrestaShop/PrestaShop/issues/12078)
So, I close it.

**Comment by SD1982** [comment] 2020-02-18 09:45
Duplicate of #12078

**Closed as completed by SD1982** 2020-02-18 09:44 UTC
Labels: Duplicate

**Comment by HartLarsson** [comment] 2020-02-18 21:08
seems to me but is not the same ticket #9910 
The other ticket is a problem about price and combinations.
In my case the product have ZERO combination and the price is changed after Save and re-enter the product edit.

the other ticket problem was about ising comma as decimal: 5,00
instead of 5.00

But this is not my case, seems that in BO the calculation is strange but in front office you continue to see 5.00€

**Comment by HartLarsson** [comment] 2020-02-18 21:11
@didi-2018

this is the result with your suggested no taxed ammount:

![image](https://user-images.githubusercontent.com/16102074/74778594-31142100-529c-11ea-8633-33a6ac506ea7.png)

as son as  you type: 4.098360 is converted to 4.098359

you can see a mini video here: 
[![Screenshot from Gyazo](https://gyazo.com/fa5f4d94ff21761e3255d443add50683/raw)](https://gyazo.com/fa5f4d94ff21761e3255d443add50683)

**Comment by khouloudbelguith** [comment] 2020-02-19 08:40
@HartLarsson, Sorry :slightly_smiling_face:  it is my fault.
It is a duplicate of #12078.

Thanks!
