### ISSUE TITLE
persian numbers in friendly URL (add new product)

### ISSUE THREAD

**Issue by alibt** [PrestaShop/PrestaShop#12142] opened 2019-01-14 09:46 UTC
**Describe the bug**

**can not add persian numbers in friendly URL**
using persian characters is ok
using persian character+english numbers is ok
but when i add persian numbers in this manner :

1. Go to products
2. Click on add a new product
3. enter name and add the picture
4. save

this error appears : 
    فیلد link_rewrite (پارسی (Persian)) نامعتبر است.
"link_rewrite field (persian) is not valid"

error and url screenshots  : 

![screenshot_2019-01-14 digirooz 2](https://user-images.githubusercontent.com/21152465/51105489-5bc0ba00-17fe-11e9-8e3b-14426616e959.png)
![screenshot_2019-01-14 digirooz 1](https://user-images.githubusercontent.com/21152465/51105499-5f544100-17fe-11e9-81ef-824c9575e39b.png)

additional info:
english language is disabled
profile language is persian
prestashop V1.7.5.0

PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2019-01-15 10:09
Hi @alibt,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
This issue occurs when `Accented URL` is enabled in the SEO & URLs page.
I attached a video record.
https://drive.google.com/file/d/1IX2GYT1yrdH7oHK0zOjXPEKzhUm3rm-N/view
We will see how to fix it.
With PS1.7.4.4, it is OK.
Thanks!

**Comment by samberrry** [comment] 2019-01-20 09:54
I had the same issue with accented URL.

**Comment by khouloudbelguith** [comment] 2019-01-21 09:33
Hi @vhessam,

The issue is added to our bug roadmap.
It will be fixed in the next release 1.7.5.1.
Thanks!

**Comment by jolelievre** [comment] 2019-01-22 07:19
Hello @khouloudbelguith 
I am trying to reproduce the bug without success, could you please copy me the text that causes the bug? With persian numbers?
Thank you

**Comment by khouloudbelguith** [comment] 2019-01-22 07:51
Hi @jolelievre,

I used this expression `آیفون ٨`  & this one `آیفون ٧` to reproduce the issue.
Thanks!

**Comment by PierreRambaud** [comment] 2019-01-24 09:46
Google tells me there is a space which is not allowed in link_rewrite. :thinking:

**Comment by khouloudbelguith** [comment] 2019-01-24 10:59
Hi @PierreRambaud, 

If I try with this expression `٧آفون` without space, I have the same issue.
![image](https://user-images.githubusercontent.com/16067358/51671131-8661fe00-1fc8-11e9-975f-30bf812667ca.png)
Thanks!

**Comment by PierreRambaud** [comment] 2019-01-24 12:59
I manage to reproduce with the number only :)

**Comment by matks** [comment] 2019-01-25 21:19
Fixed by https://github.com/PrestaShop/PrestaShop/pull/12292

**Closed as completed** 2019-01-25 21:20 UTC
Labels: Bug, Major, BO, International, Regression, Fixed, 1.7.5.0
