### ISSUE TITLE
Error in tax calculation due to ecotax

### ISSUE THREAD

**Issue by thm-meder** [PrestaShop/PrestaShop#32069] opened 2023-04-06 08:48 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hey all, 

First time asking for support here. While implementing the ecotax for a client, I stumbled upon a big problem. 

When youcome from a geographic zone that does not include taxes, the ecotax is not taken into account. On itself, it should not be a problem, as the tax column on the checkout page should be at 0. However, there is still a small fee (about 0.008/about 0.009€ by article) added to the shiping cart, which cause a big problem during billing by adding some euros to the bill.

### Expected behavior

**Actual Behavior :** 
A tax is added becuse of the ecotax, even if the ecotax is not considered as a tax.

**What should happen :**
The tax should be at 0.

### Steps to reproduce

You can reproduce this problem on a new prestashop install. It's even working on Prestashop 1.7.8.

1-Create a website with tax excluded. Disable it for your customers, for your carriers, everything.
2-Add an ecotax.
3-Enter an ecotax value on a product.
4-Add them to your cart
5-You will see a small tax which does not correspond to anything entered on the website.

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment] 2023-04-07 15:16
Hi @thm-meder 

Thank you for your report, I try to reproduce your issue on 1.7.8 as you said it, and I can't reproduce it, as you can see : 

[Untitled_ Apr 7, 2023 5_15 PM.webm](https://user-images.githubusercontent.com/100699445/230633108-25e69d45-f089-4efd-97f9-098bae5a71bc.webm)

I haven't any tax on it

Did I miss something ? 

Waiting for your feedback

**Comment by florine2623** [comment] 2023-04-25 13:46
Hello @thm-meder ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-04-25 13:46 UTC
Labels: Bug, FO, Taxes and Prices, 1.7.6.5
