### ISSUE TITLE
Total shipping different when delete product in an other tab

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#23631] opened 2021-03-13 16:35 UTC
Hello,

A customer report a (maybe) bug.

> I was ordering two products ITEM_1 and ITEM_2. I opened them in two tabs and I deleted ITEM_2 in the second tab and paid for both in the first tab.
> I was charged for both items and the order details email from the shop shows that it was only the ITEM_1.

#### Additional information

* PrestaShop version: 1.7.5
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-03-14 21:38
Hello @BenTen 

I didn't manage to reproduce the issue issue with PS1.7.7.2, PS1.7.5.2 and PS1.7.4.1, see the attached screen record below:

https://drive.google.com/file/d/1zhdXNNkHa1c6NNobVCdlCtAnOhhbirPs/view

> I was charged for both items and the order details email from the shop shows that it was only the ITEM_1

Could you please check his order in BO and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-04-05 17:17
Hello @BenTen ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-04-05 17:17 UTC
Labels: Bug, FO, No change required, 1.7.5.2, Shopping carts FO, Checkout
