### ISSUE TITLE
Create a new hook 'hookActionProductGridDefinitionModifier'

### ISSUE THREAD

**Issue by kratekk** [PrestaShop/PrestaShop#28239] opened 2022-04-12 10:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I am not really sure if is it the bug but this hook does not exist in newest Prestashop version 1.7.8.5
hookActionProductGridDefinitionModifier

I need it to develop my custom functions. Is that possible to add new items to bulk action list for Product list in admin?

Go to Product List in Admin -> add new custom bulk action

### Describe the solution you'd like

```
$this->registerHook('actionProductGridDefinitionModifier')

public function hookActionProductGridDefinitionModifier(array $params)
{
$gridDefinition = $params['definition'];

    $gridDefinition->getBulkActions()->add(
            (new SubmitBulkAction('relate_products'))
                ->setName('Relate products')
                ->setOptions([
                    'submit_route' => 'admin_relation_products_list',
                ]) 
        );
}
```

**Comment by marwachelly** [comment] 2022-04-12 11:23
Hello @kratekk,

I noticed that the hook **ActionProductGridDefinitionModifier** doesn't exist not only in 1.7.8.5 but also in all previous PS version and in the [List of hooks in PrestaShop 1.7](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/#full-list). Do you want to add a new  hook? 
Waiting for your feedback :blush: 

Thanks,

**Comment by kratekk** [comment] 2022-04-12 11:27
> 

Hi @marwachelly  do you mean if I registered new hook? Yes

`$this->registerHook('actionProductGridDefinitionModifier')`

```
public function hookActionProductGridDefinitionModifier(array $params)
	{
	    $gridDefinition = $params['definition'];

	    $gridDefinition->getBulkActions()->add(
	            (new SubmitBulkAction('relate_products'))
	                ->setName('Relate products')
	                ->setOptions([
	                    'submit_route' => 'admin_relation_products_list',
	                ]) 
	        );
	}
```

**Comment by marwachelly** [comment] 2022-04-12 11:33
Hi @kratekk ,
So your issue is a new feature not a bug. Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thanks,

**Comment by hibatallahAouadni** [comment] 2022-04-13 09:00
Ping @PrestaShop/prestashop-core-developers wdyt about creating a new hook to add new items to bulk action list for Product list in admin?
Thanks in advance :pray:

**Comment by matks** [comment] 2022-04-13 15:02
Hello @kratekk in 8.0 we'll have a full new product list page, and it has _as far as I know_ all the hooks you would need 😄 .

But your focus in on 1.7.8.5 . Unfortunately on 1.7.8.x versions we only deliver bug fixes and adding a hook would be a new feature. We only deliver bug fixes in order to keep the version as stable as possible so we will not add a hook in 1.7.8.6 .

However 8.0.0 should come in the summer so soon you should have all the hooks you need 👍 

I close this issue as
- for 8.x branch it's already OK (don't hesitate to check the new product page to see if you have all the hooks you want)
- for 1.7.8.x we cannot add new features

**Closed as completed by matks** 2022-04-13 15:02 UTC
Labels: Feature, BO, Modules, No change required, Hook, Invalid

**Comment by dnkhack** [comment] 2023-10-29 21:27
> Hello @kratekk in 8.0 we'll have a full new product list page, and it has _as far as I know_ all the hooks you would need 😄 .
> 
> But your focus in on 1.7.8.5 . Unfortunately on 1.7.8.x versions we only deliver bug fixes and adding a hook would be a new feature. We only deliver bug fixes in order to keep the version as stable as possible so we will not add a hook in 1.7.8.6 .
> 
> However 8.0.0 should come in the summer so soon you should have all the hooks you need 👍
> 
> I close this issue as
> 
> * for 8.x branch it's already OK (don't hesitate to check the new product page to see if you have all the hooks you want)
> * for 1.7.8.x we cannot add new features

@matks Hello. This hook still doesn't work. in 8.1.1!

**Comment by rflorent** [comment] 2024-01-09 15:48
Hello, working but you need to use the "new product page"
[https://docs.prestashop-project.org/v.8-documentation/user-guide/selling/managing-catalog/new-product-page-prestashop-8.1](url)
