### ISSUE TITLE
BO - Products - pack items do not display cover image if related to a combination

### ISSUE THREAD

**Issue by prestaalba** [PrestaShop/PrestaShop#25622] opened 2021-08-17 00:02 UTC
#### Describe the bug

In backoffice Products creation when you search an item for a pack, product cover image is not displayed properly if the item is a combination. Product cover image on the selected product pack items list is not displayed either.

#### Expected behavior

All pack items cover image must be displayed properly, regardless of whether the item is a product or combination.

#### Steps to Reproduce

1. Go to menu Catalog -> Products.
2. Create a new Stardard product with combinations.
3. Upload some product image.
3. Create some random combinations.
4. Save the product.
4. Create a new "Pack of products" product.
3. Search for the previously created product to add it as a pack item. Image is not displayed properly.
4. Add the item to the "List of products for this pack". Image is not displayed properly.

**Screenshots**

![1](https://user-images.githubusercontent.com/18466848/129643318-52d110eb-556c-405e-b17b-df9812d33e28.png)

![2](https://user-images.githubusercontent.com/18466848/129643324-92c25777-6f1b-43b2-ab23-64fd6b15c1b8.png)

#### Additional information

This is cause because before rendering the product combinations as pack items, PrestaShop search for the image associated to every combination. The problem is that a combination is not forced to have an associated image, so when this happen, even if the base product has some images, no cover image is found for the specific combination.

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-08-17 15:12
Hello @prestaalba 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20001. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-08-17 15:13
Duplicate of #20001

**Closed as completed by hibatallahAouadni** 2021-08-17 15:12 UTC
Labels: Duplicate
