### ISSUE TITLE
Jquery Issue after upgrading PS from 1.7.6.9 to 1.7.7.2

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#23770] opened 2021-03-25 02:33 UTC
Hello
i need you help please for this issue
I upgraded my prestashop from 1.7.6.9 to 1.7.7.2 using 1-Click Upgrade 4.11.0 and I disabled all thirdy modules but i can't switch the presta default theme because i get this error in screenshot also I get white page with codes when I disable modules

**Screenshots**
![image](https://user-images.githubusercontent.com/11594433/112409244-70bc0080-8d19-11eb-8528-a64a65773aad.png)

![image](https://user-images.githubusercontent.com/11594433/112409377-aa8d0700-8d19-11eb-84ce-5592383fdffa.png)

Version de PrestaShop : 1.7.7.2
Version du logiciel serveur : Apache
Version de PHP : 7.3.27
Limite de mémoire : 8090M
Temps maximal d'exécution : 3000
Taille max. pour envoi de fichiers : 900M
Version de MySQL : 10.3.27-MariaDB

Thank you for your help

Regards

**Comment by florine2623** [comment] 2021-03-25 09:45
Hello @go-sudo ,

I can't reproduce your issue.
I upgrade my store from PS 1.7.6.9 to 1.7.7.2 successfully :
![Capture d’écran 2021-03-25 à 10 41 25](https://user-images.githubusercontent.com/16019289/112452249-b64aee80-8d56-11eb-8466-f0d60e24bb0c.png)

In Appearance > Theme & Logo > Theme :
![Capture d’écran 2021-03-25 à 10 35 53](https://user-images.githubusercontent.com/16019289/112452122-91567b80-8d56-11eb-9dad-d772cd261914.png)

Also, I disabled one-click upgrade module to test and I didn't get the white page with codes :
![Capture d’écran 2021-03-25 à 10 44 14](https://user-images.githubusercontent.com/16019289/112452684-2b1e2880-8d57-11eb-9ccd-7565b90edb49.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thanks!

**Closed as completed by florine2623** 2021-03-25 09:45 UTC
Labels: Can't reproduce

**Comment by go-sudo** [comment] 2021-03-25 09:50
Hello @florine2623 

I appreciate your help , can I restore my previous backup and try again but what you suggest I do before upgrading again my PS

Regards
