### ISSUE TITLE
Error while uploading invalid image in Product : Missing Validation

### ISSUE THREAD

**Issue by shaluwebkul** [PrestaShop/PrestaShop#13156] opened 2019-04-03 09:18 UTC
**Describe the bug**
Error received while uploading invalid image in Product at BO.

**To Reproduce**

1. Go to BO -> 'Catalog' -> 'Products' tab
2. Click on 'Add Product' or 'Edit Product' button
3. Now, at 'Basic settings' tab -> 'Drop images here' section
   Upload any invalid image (with extensions like - .ico , .svg)
4. See error : in image upload section & also in console.
5. Now, click on 'Save' - 'Settings Updated' message display
   Instead, a validation must display : 'Unable to update settings.' OR 'Invalid image format.'

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/49226553/55467271-8a407b00-561e-11e9-9dd8-41a1f4a1fdd0.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7

**Comment by khouloudbelguith** [comment] 2019-04-03 10:08
Hi @shaluwebkul,

I manage to reproduce the issue with PS:1.7.5.1.
This issue is added to our bug roadmap.

Thanks!

**Comment by marionf** [comment] 2019-04-04 12:16
Duplicate of #10600

**Comment by marionf** [comment] 2019-04-04 12:17
Hello @shaluwebkul 

Your issue is a duplicate, please follow the issue mentionned above

**Closed as completed by marionf** 2019-04-04 12:17 UTC
Labels: Bug, Minor, BO, Duplicate, Image, 1.7.5.1
