### ISSUE TITLE
change tax rate and keep the sale-price incl. tax

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#19625] opened 2020-06-08 11:44 UTC
Hi, 

this is a feature request: 

We have in germany the problem that we have a reduced tax rate from 19 to 16 percent from 01.07.20 to 31.12.20. If I now change the tax in prestashop from 19% to 16% the shop pulls down the tax from the price incl. tax an adds the new tax 16% on the price without tax. At the end I will have new sale-prices calculated from the price without tax. 

So we need a feature to decide how the price incl. tax will calculated if you change the tax. from the price incl. tax away or from the price without tax on top. 

Thanks for having ideas and making thougts ♥

**Comment by florine2623** [comment] 2020-06-08 14:27
Hi @didi-2018 ,
Thanks for the recommandation, we have an open issue regarding that. You can follow it here : https://github.com/PrestaShop/PrestaShop/issues/19628

I'll close this issue as it is a duplicate !

**Comment by florine2623** [comment] 2020-06-08 14:27
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19628

**Closed as completed by florine2623** 2020-06-08 14:27 UTC
Labels: Duplicate
