### ISSUE TITLE
settings Test your email configuration

### ISSUE THREAD

**Issue by shivakadakol** [PrestaShop/PrestaShop#17576] opened 2020-02-09 11:33 UTC
![error](https://user-images.githubusercontent.com/25544349/74101232-a32e8c80-4b5d-11ea-8177-f2b01bc83089.png)

**Describe the bug**
i have configuring email to prestashop application but always i m getting error
Error: Please check your configuration

Connection could not be established with host mail.k5techno.com [Connection refused #111]
 
**To Reproduce**
1. Go to 'Menu -> Advance Parameter'
2. Click on 'Email'
3. Check "
Set my own SMTP parameters (for advanced users ONLY)"
4. Scroll down to 'Email -> settings Test your email configuration
'
5. See error
Error: Please check your configuration
Connection could not be established with host mail.k5techno.com [Connection refused #111]

**Screenshots**
attached screenshot
**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.3.7

**Comment by khouloudbelguith** [comment] 2020-02-10 08:20
Hi @shivakadakol,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Second, I did not manage to reproduce the issue with PS1.7.6.3
![image](https://user-images.githubusercontent.com/16067358/70325134-95911980-1831-11ea-85b7-c0cef3b3fe8e.png)
https://drive.google.com/file/d/1wC9yGT_j97H5D9kiHGal3G7VxXel2BMC/view
The information for these fields, SMTP, should be provided by your web host: mail domain name, SMTP server, SMTP user, etc. Make sure to transcribe exactly what your web host provides you with.

Thanks to check with your host & feedback.

**Comment by khouloudbelguith** [comment] 2020-03-10 07:46
Hi @shivakadakol,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-10 07:46 UTC
Labels: Bug, BO, Email, No change required, 1.7.6.3

**Comment by milaonline** [comment] 2020-11-02 20:52
Problem still appears with prestashop 1.7.6.5 and smtp.office365.com

**Comment by paulius-bulotas** [comment] 2024-03-22 15:54
> Problem still appears with prestashop 1.7.6.5 and smtp.office365.com

Hi, did you have solution to solve this problem ?
