### ISSUE TITLE
Wrong product image displayed in order page

### ISSUE THREAD

**Issue by Djangoum** [PrestaShop/PrestaShop#26710] opened 2021-11-23 08:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I see a diferent product image in orders page than in products page. 

Order page:
![image](https://user-images.githubusercontent.com/9842183/142991494-7d1c7001-a0d2-471d-9dba-d902db0edd0a.png)

Product page:
![image](https://user-images.githubusercontent.com/9842183/142991515-d7a2bf33-4c07-4431-a67b-06e43a664555.png)

### Expected behavior

I should see the same image in orders page than in product page

### Steps to reproduce

Go to order page and check all order products,

Select the not matching one and go to the product page

Observe that the image does not match and in product page is correct

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2021-11-23 09:35
Hello @Djangoum ,

I can't reproduce your issue on PS 1.7.8.1.
In my product page :
<img width="893" alt="Screenshot 2021-11-23 at 10 31 35" src="https://user-images.githubusercontent.com/16019289/143000681-49eb1242-14bb-43e6-940b-77f3be1e4957.png">
In my order :
<img width="793" alt="Screenshot 2021-11-23 at 10 32 47" src="https://user-images.githubusercontent.com/16019289/143000671-d6f6ca59-1081-4fea-a4d8-f0036b8e5f75.png">

Did you upgrade your shop ? change server ? did you change the product image after the order ?

Thanks!

**Comment by florine2623** [comment] 2021-12-13 09:15
Hello @Djangoum ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-12-13 09:15 UTC
Labels: Bug, BO, Order, Invalid
