### ISSUE TITLE
Class not found exception 

### ISSUE THREAD

**Issue by LokeshVarman** [PrestaShop/PrestaShop#19352] opened 2020-05-26 10:41 UTC
Sorry, Since i am new to this. Please help me .Thanks in advance

![image](https://user-images.githubusercontent.com/30750553/82891510-7ca92b80-9f6b-11ea-9c52-442847b5f6da.png)

**Comment by sarahdib** [comment] 2020-05-26 13:48
Hello @LokeshVarman 

Please could you explain the step to reproduce and your prestashop version ?

Thank you

**Comment by LokeshVarman** [comment] 2020-05-26 13:53
Prestashop 1.7.5.6

**Comment by florine2623** [comment] 2020-05-28 08:40
Hi @LokeshVarman ,
Please share the exact steps so we can reproduce the issue to help you.

If you need personalized help, please contact the support at PrestaShop : https://addons.prestashop.com/en/388-support
Thanks!

**Comment by florine2623** [comment] 2020-06-08 07:53
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-08 07:53 UTC
Labels: No change required
