### ISSUE TITLE
BO - Order page - Updating a product with a specific discount (gift)

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21506] opened 2020-10-19 13:11 UTC
Related to this [PR](https://github.com/PrestaShop/PrestaShop/pull/21447)

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Create a cart rule 
1.1 Informations: without code
1.2 Conditions: Product selection demo_6
1.3 Actions: Free shipping + discount amount = 1euro tax included + Free gift (demo_11)
2. Add a product demo_11 to the cart 
4. Continue checkout
5. Go to the BO > Order detail page
6. Try to add demo_6 to the order 
In this case, we have two behaviors

If the quantity of demo_11 = 1
=> the discount is well applied but quantity of demo_11 = 1 (not updated)
![image](https://user-images.githubusercontent.com/16067358/96455120-10caa680-121d-11eb-9379-163e2b69aeb7.png)

If the quantity of demo_11 > 1 (=2)
=> the discount is well applied and quantity of demo_11 = 2 (well updated)
![image](https://user-images.githubusercontent.com/16067358/96455273-47a0bc80-121d-11eb-8f1f-9df2019f7c5e.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-10-19 13:19
Ping @jolelievre @MatShir what do you think about the severity of this issue? is it minor or Major?

Thanks!

**Comment by MatShir** [comment] 2020-10-19 13:36
I would say Minor since it happens only when there is one product left.

**Comment by jolelievre** [comment] 2020-10-21 09:51
I'm not sure I understand the behaviour nor the expected result Which one is the gift?

Is it the gift that was previously added? And then you add a product that has an auto gift matching the present product? So the expected result is to increment the present product from 1?

If that's the scenario you are describing I think it should work if you refresh the page, but it is not updated by ajax right away.

**Comment by jolelievre** [comment] 2020-10-30 10:34
Ok I think I understand which bug it is, the problem is that when only 1 product is remaining it is not added automatically whereas it should since there is still a little stock available I think it's a stupid bug related to a strict comparison (`<` vs `<=`) that doesn't allow to use the last remaining product

**Comment by Progi1984** [comment] 2020-12-17 10:15
Fixed by #21795

**Closed as completed by Progi1984** 2020-12-17 10:15 UTC
Labels: Bug, Minor, BO, Order, Discounts, Cart rules, Regression, Fixed, PR available, Nice-to-have, 1.7.7.x
