### ISSUE TITLE
PS9 - Mobile. Product page in BO. product_footer_actions_dropdown button unavailable unless you starting editing the product 

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#34673] opened 2023-11-24 16:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

product_footer_actions_dropdown button  with New product, Delete, Duplicate, Preview buttons unavailable unless you starting editing the product 
![Screenshot from 2023-11-24 16-42-38](https://github.com/PrestaShop/PrestaShop/assets/90208051/059ca84e-d4fd-4cf0-97f4-eaebe03ee581)
If I press "dropdown" button, it presses "Go to catalog" button 

See video:

https://github.com/PrestaShop/PrestaShop/assets/90208051/65e3591d-a805-402d-bdf1-b508c0df50f2

### Expected behavior

Button must be available

### Steps to reproduce

1. open some product in mobile
2. scroll to the down
3. click on product_footer_actions_dropdown button 

### PrestaShop version(s) where the bug happened

9.0/8.x

### PHP version(s) where the bug happened

8.1 / 7.4

**Comment by AureRita** [comment] 2023-11-27 10:00
Hello @szavadskiy 

I tried to reproduce your issue but despite my effort, I can't reproduce it, as you can see : 

[Untitled_ Nov 27, 2023 10_54 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4570916d-e255-410e-a7d0-cfd83c5b2f7b)

Did I miss something ? 

Can you tell me, wich mobile did you use ? 

Waiting for your feedback

**Comment by szavadskiy** [comment] 2023-11-27 10:21
Hello @AureRita  thank for your answer
I'm reproducing issue with iPhone 13 Pro Max 14 Pro Max

**Comment by Arababer** [comment] 2023-11-27 14:04
Hello @szavadskiy 
I have reproduced the issue on develop only one time and never again. Sorry I don’t have a screen record.
This issue must be very specific.
I’ll add this to the backlog so it can be fixed.
Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you.
If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.
Thank you

**Comment by amine-O** [comment] 2024-06-27 09:44
@mattgoud could you please check if it's fixed on your last PR on Product page for Mobile ? 
https://github.com/PrestaShop/PrestaShop/pull/35775

**Comment by mattgoud** [comment] 2024-06-27 10:40
> @mattgoud could you please check if it's fixed on your last PR on Product page for Mobile ? #35775

I just tested and the dropdown appears well on my side

**Comment by florine2623** [comment] 2024-08-13 07:59
I'm closing the issue as it is fixed with develop branch.

**Closed as completed by florine2623** 2024-08-13 07:59 UTC
Labels: Bug, Trivial, BO, Ready, Fixed, Responsive, Verified, 9.0.x, Products Page
