### ISSUE TITLE
BO - The products of the new shop created are not displayed in the list when selecting All shops (multistore)

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26581] opened 2021-11-11 13:12 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After configuring Multistore, create new shop. So when selecting `All shops` category, the products that are created in the new shop, are not displayed in the list of products in BO.

See video : 
 https://www.awesomescreenshot.com/video/5975855?key=209fcfb4479ff833291727dbd93b0af3

### Expected behavior

All products of all shops are displayed in the list of products. Meaning, the products of the new shop created and the default one are all displayed in the list.

### Steps to reproduce

1. BO>Catalog>Products
2. Create products in the default shop
3. Configure multistore
4. Create new shop
3. Create products in the new shop
4. Select The default shop and see the products that are displayed in the list ==> OK (The products of the default shop are correctly created)
5. Select The new shop and see the products that are displayed in the list ==> OK (The products of the new shop are correctly created)
6. Select All shops and see the products that are displayed in the list ==> NOK (Only the products of the default shop are displayed)

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.0 & 1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment] 2022-02-03 13:13
Duplicate of #9613

**Closed as completed by khouloudbelguith** 2022-02-03 13:13 UTC
Labels: Bug, Minor, BO, Duplicate, Multistore, 1.7.7.8, Invalid
