### ISSUE TITLE
Bad image in relation to the declination

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#25426] opened 2021-07-26 11:04 UTC
#### Describe the bug

Hello,

I noticed that the cover image is always displayed first. When I have a variation of this product, the cover image should not appear. (see screen shot)

Can you help me ?

Thanks

![image](https://user-images.githubusercontent.com/25744417/126978893-bac59f7f-61db-432a-a0eb-e70abd21516d.png)

![image](https://user-images.githubusercontent.com/25744417/126978938-712ae76a-08ec-4eb2-871c-4334431ef7eb.png)
![image](https://user-images.githubusercontent.com/25744417/126978983-9db95c93-99e1-42f4-bab5-d03608339f48.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-07-26 14:30
Hello @ShaimyWinda 

Could you please specify in which version you encountred this issue. Cause I didn't manage to reproduce this issue with PS1775, see the attached screen record below:

https://drive.google.com/file/d/1DKq9tLLNgZDyGPq54KsPg2CK-zN0vAIU/view

Please check and feedback.
Thanks!

**Comment by ShaimyWinda** [comment] 2021-07-26 15:10
Hello @hibatallahAouadni 

My prestashop is 1.7.7.2

You can see my record 
https://drive.google.com/file/d/1CSIXTjB1Tdfya7FQSnOj6hY2hkNv2BYl/view

Thanks

**Comment by florine2623** [comment] 2021-07-27 14:02
Hello @ShaimyWinda ,

Using PS 1.7.7.2 and classic theme, I can't reproduce your issue :
https://drive.google.com/file/d/1q2Usblbfj3iQh67ZRtQQeH3_Fv3_7sub/view

I suggest contacting the developer of the template to fix this issue.
I'll close this issue as I can't reproduce it.
Thanks!

**Closed as completed by florine2623** 2021-07-27 14:02 UTC
Labels: Bug, FO, Can't reproduce, Combinations, 1.7.7.x
