### ISSUE TITLE
After payment is completed, HTTP error 50 appears in the return url.

### ISSUE THREAD

**Issue by P3ngfi** [PrestaShop/PrestaShop#36094] opened 2024-05-04 17:47 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Any payment method will return an error.
Third-party payment plug-in
Pay on collect,
wire transfer
But I can receive the order and pay successfully

Maintenance mode has been turned off
Any payment mode will report an error.

Thank you so much

Ubuntu 
Php version:  PHP-8.2.16 &  php 8.0.26 
prestashop version:  8.1.5 

### Steps to reproduce

1- Select any product and make payment
2- confirm payment
3- Return http 500 after successful payment

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.2.16

**Comment by P3ngfi** [comment] 2024-05-04 18:12
I turned on debug mode and he showed error
![image](https://github.com/PrestaShop/PrestaShop/assets/29498020/1045b50e-9a87-4585-92d8-ef1574560d10)
The administration backend also crashed. Inaccessible
![image](https://github.com/PrestaShop/PrestaShop/assets/29498020/2a4f710f-ee6c-479e-94e0-c5a6cd27d23b)

**Comment by jlores** [comment] 2024-05-04 18:45
Hello,

PrestaShop 8.1.x is only compatible with PHP 7.2 to 8.1. Php 8.2 not is compatible


Best regards

**Comment by P3ngfi** [comment] 2024-05-04 18:54
> Hello,
> 
> PrestaShop 8.1.x is only compatible with PHP 7.2 to 8.1. Php 8.2 not is compatible
> 
> Best regards



> 你好，
> 
> PrestaShop 8.1.x 仅与 PHP 7.2 至 8.1 兼容。 PHP 8.2 不兼容
> 
> 此致

I tested php 8.0.26 and got the same error.

**Comment by Hlavtox** [comment] 2024-05-04 20:58
Open vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php and put // before putenv(‚SHELL_VERBOSITY=3‘);

Then debug mode will work and show you the error

**Comment by P3ngfi** [comment] 2024-05-04 22:46
> 打开vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php并将//放在putenv(‚SHELL_VERBOSITY=3');之前
> 
> 然后调试模式将起作用并显示错误

Hello. thank you for your reply. I think it may be a compatibility issue with the php version.
I switched the version to php 7.4 and he had no problem. Error 500 no longer occurs.

In php 8 or above, I will disable proc_open and remove the erro 500 error. The error will disappear, but I will get a new 502 (502 Bad Gateway nginx)

The error in the background will disable the putenv function and remove it, and it will return to normal.

**Comment by Hlavtox** [comment] 2024-05-05 06:00
Prestashop 8.1 will work just fine on PHP 8.1. (…and it also works unofficially on 8.2 and 8.3 with just some minor deprecation notices…)

Debug mode will tell you what is wrong, either some crucial php method is disabled on your php versions OR some of your modules is incompatible with these php versions.

**Comment by P3ngfi** [comment] 2024-05-05 06:05
I compared php 7.4 and php 8.0.x versions
He disabled both the proc_open and putenv functions.
Version 7.4 runs normally, but php 8 or above will return an error.

Currently I am trying to change the running environment to Debian 12

> Prestashop 8.1 在 PHP 8.1 上运行得很好。 （……它也可以在 8.2 和 8.3 上非正式地运行，只是有一些小的弃用通知……）
> 
> 调试模式会告诉您出了什么问题，要么您的 php 版本上禁用了某些关键的 php 方法，要么您的某些模块与这些 php 版本不兼容。

I compared php 7.4 and php 8.0.x versions
He disabled both the proc_open and putenv functions.
Version 7.4 runs normally, but php 8 or above will return an error.

Currently I am trying to change the running environment to Debian 12

**Comment by P3ngfi** [comment] 2024-05-05 06:06
> Prestashop 8.1 will work just fine on PHP 8.1. (…and it also works unofficially on 8.2 and 8.3 with just some minor deprecation notices…)
> 
> Debug mode will tell you what is wrong, either some crucial php method is disabled on your php versions OR some of your modules is incompatible with these php versions.

I compared php 7.4 and php 8.0.x versions
He disabled both the proc_open and putenv functions.
Version 7.4 runs normally, but php 8 or above will return an error.

Currently I am trying to change the running environment to Debian 12

**Comment by paulnoelcholot** [comment] 2024-05-06 14:14
Hello @P3ngfi,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-05-06 14:14 UTC
Labels: Bug, Invalid
