### ISSUE TITLE
[Free delivery] After adding the tracking number the system adds the shipping cost

### ISSUE THREAD

**Issue by procent85** [PrestaShop/PrestaShop#18556] opened 2020-04-09 19:51 UTC
#### Describe the bug

Shop configuration: free delivery from 160 Polish Zloty. The customer places an order for 160 zloty and does not pay for shipping. In the Back Office I see a paid order for 160 zloty (with 0 zl for delivery - free courier delivery). It's OK, but...
After adding the tracking number on the order card, system adds the shipping cost of the selected courier to the order. The order was 160 PLN, but after adding the tracking number it is 160 zl + 16 zl courier cost. The order value changed from 160 zl to 176 zl. A red warning appeared.

#### Expected behavior
After adding the tracking number, the delivery cost should not be added because it is free from 160 zloty orders

#### Steps to Reproduce

1. Go to 'Back Office'
2. Click on Shipping -> Preferences
3. See "Free shipping starts at 160 zloty"
4. Go to: Shipping -> Carriers. 
5. Courier is configured as orders >160 zloty = 0 zloty delivery cost
6. Go to: Sell -> Orders
7. Select an order above 160 zloty
8. Click Edit in Shipping -> Tracking number and add the number
9. At the bottom of this page, in the summary, the delivery cost changes from 0 zloty to 16 zloty
10. Red warning appeared "Note 160.00 PLN instead of 176.00 PLN" (translated from Polish).

**Screenshots**
Example of an order over 160 zloty where the customer did not pay for shipping
https://i.imgur.com/ZIzCn3K.png

#### Additional information

* PrestaShop version: 1.7.6.4 (clean installation + migration via MigrationPro module from PS 1.6)
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-04-10 09:37
Hi @procent85 ,

I could not reproduce your issue in PS 1.7.6.4 with the same configuration you shared.
Please see screen record below : 
https://drive.google.com/file/d/1QBiT_TwOYrvu4ygg7atdZmh3iP8csW0r/view

Can I see the full configuration of the carrier please ?

Thanks !

**Comment by sarahdib** [comment] 2020-05-05 15:41
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by sarahdib** 2020-05-05 15:41 UTC
Labels: BO, Order, Shipping, No change required, 1.7.6.4
