### ISSUE TITLE
Customer reassurance module (version: 4.1.1): some bugs

### ISSUE THREAD

**Issue by jouino16** [PrestaShop/PrestaShop#16081] opened 2019-10-23 10:13 UTC
Once the module configuration page is open:

1. I get a warning about the permissions of the folder "img_perso" even if it has 755:
```
Your folder /XXXXXXX/modules/blockreassurance/views/img/img_perso is not readable or executable
This folder needs these rights so you can upload your own images for the reassurances blocks.
```
2. So I cannot upload a custom image: when I try to upload one, I get successful message but it is not updated.
3. I cannot add a fourth block (based on the fact that there are three by default): when I try to add one, I get successful message but it is not added.
4. Minor issue: duplicate icon in the predefined selection, so we have a missing carrier icon:
![duplicate](https://user-images.githubusercontent.com/12447492/67382834-6b8bdc80-f58e-11e9-8679-77245a01c7d0.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.18

**Comment by khouloudbelguith** [comment] 2019-10-23 10:59
Hi @jouino16,

Thanks for your report.
>I get a warning about the permissions of the folder "img_perso" even if it has 755

I did not manage to reproduce the issue with PS1.7.6.1 & the `blockreassurance` module v4.1.1.

>So I cannot upload a custom image: when I try to upload one, I get successful message but it is not updated.
>I cannot add a fourth block (based on the fact that there are three by default): when I try to add one, I get successful message but it is not added.

This is an SVG issue, we are aware of the issue, it is reported here: https://github.com/PrestaShop/PrestaShop/issues/15939

>Minor issue: duplicate icon in the predefined selection, so we have a missing carrier icon.

Yes, I manage to reproduce the issue with blockreassurance v4.1.1.

Thanks!

**Comment by jouino16** [comment] 2019-10-23 11:28
@khouloudbelguith 
Thank you for your quick reply.

Just in case it can help, I upload a couple of images for the folder permission issue. And for the record, I work on Windows:
![warning](https://user-images.githubusercontent.com/12447492/67388435-eb1ea900-f598-11e9-83af-5c3d935a6654.png)
![permissions](https://user-images.githubusercontent.com/12447492/67388449-f4a81100-f598-11e9-9fd2-c66d1870b3c8.png)

**Comment by khouloudbelguith** [comment] 2019-10-23 11:35
@jouino16, thanks for your feedback.

>Just in case it can help, I upload a couple of images for the folder permission issue.

I did not manage to reproduce the issue with the `blockreassurance` module v4.1.1.
I attached a screen record
https://drive.google.com/file/d/1mPckUca8LjYZhZcrQjh_S1yg83FP_Jln/view

Thanks to check & feedback.

**Comment by jouino16** [comment] 2019-10-23 14:31
@khouloudbelguith 
Thank you for the video and your effort. Unfortunately, it does not work for me, even if the folder has the right permissions. I used Git Bash (on windows) to perform the check and it has 755 as I showed in my previous post. I cannot figure out why it does not work for me.

**Comment by khouloudbelguith** [comment] 2019-10-23 15:20
@jouino16, about your last issue, I created a new issue https://github.com/PrestaShop/PrestaShop/issues/16091
It is added to our bug roadmap.
>Unfortunately, it does not work for me, even if the folder has the right permissions. I used Git Bash (on windows) to perform the check and it has 755 as I showed in my previous post. I cannot figure out why it does not work for me.

Could you please try to re-install the module & clear the cache.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-11-22 07:36
Hi @jouino16,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-22 07:36 UTC
Labels: Bug, BO, No change required, Blockreassurance, 1.7.6.1
