### ISSUE TITLE
Private note saved with escaping signs

### ISSUE THREAD

**Issue by kodarco** [PrestaShop/PrestaShop#15121] opened 2019-08-15 18:36 UTC
When I type and save the Private note on Order Page in BO and come back to the same order, I see the escaping characters like %20 for space etc. See the attached.
This happened after upgrade from PS 1.7.5.0 to PS 1.7.6.0

![S1](https://user-images.githubusercontent.com/43558067/63117486-36ff1180-bf9c-11e9-8abe-ec54613e3dc6.JPG)
![S2](https://user-images.githubusercontent.com/43558067/63117492-38c8d500-bf9c-11e9-8851-44f0db92d646.JPG)
![S3](https://user-images.githubusercontent.com/43558067/63117496-3a929880-bf9c-11e9-8b89-4fd2176b5885.JPG)

**Comment by kodarco** [comment] 2019-08-15 18:43
Just to add to this maybe related, a whole bunch of these entries showing in the Apache Error Log:

`[Thu Aug 15 14:39:56.035419 2019] [fcgid:warn] [pid 118985] [client 73.57.55.81:56289] mod_fcgid: stderr: #2 /home/pbm/public_html/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '17595'), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:39:56.035423 2019] [fcgid:warn] [pid 118985] [client 73.57.55.81:56289] mod_fcgid: stderr: #3 /home/pbm/public_html/admin292mqbbbp/ajax.php(125): NotificationCore->getLastElements(), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:39:56.035426 2019] [fcgid:warn] [pid 118985] [client 73.57.55.81:56289] mod_fcgid: stderr: #4 {main}, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:39:56.035430 2019] [fcgid:warn] [pid 118985] [client 73.57.55.81:56289] mod_fcgid: stderr:   thrown in /home/pbm/public_html/classes/Tools.php on line 801, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235456 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/pbm/public_html/classes/Tools.php:801, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235480 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr: Stack trace:, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235484 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr: #0 /home/pbm/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context)), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235488 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr: #1 /home/pbm/public_html/classes/Notification.php(133): ToolsCore::displayPrice(47.75, Object(Currency), false), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235498 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr: #2 /home/pbm/public_html/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '17595'), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235502 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr: #3 /home/pbm/public_html/admin292mqbbbp/ajax.php(125): NotificationCore->getLastElements(), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235506 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr: #4 {main}, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:05.235509 2019] [fcgid:warn] [pid 118901] [client 73.57.55.81:56300] mod_fcgid: stderr:   thrown in /home/pbm/public_html/classes/Tools.php on line 801, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&id_order=22548&vieworder&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903554 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/pbm/public_html/classes/Tools.php:801, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903613 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr: Stack trace:, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903623 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr: #0 /home/pbm/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context)), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903631 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr: #1 /home/pbm/public_html/classes/Notification.php(133): ToolsCore::displayPrice(47.75, Object(Currency), false), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903640 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr: #2 /home/pbm/public_html/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '17595'), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903649 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr: #3 /home/pbm/public_html/admin292mqbbbp/ajax.php(125): NotificationCore->getLastElements(), referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903657 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr: #4 {main}, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab
[Thu Aug 15 14:40:09.903665 2019] [fcgid:warn] [pid 119021] [client 73.57.55.81:56301] mod_fcgid: stderr:   thrown in /home/pbm/public_html/classes/Tools.php on line 801, referer: https://www.poppersbymail.com/admin292mqbbbp/index.php?controller=AdminOrders&token=e4d66d72ed29751e932c63e0899be9ab`

**Comment by marionf** [comment] 2019-08-16 07:43
Hello @kodarco 

Your issue is a duplicate of 14604 so I close it
This issue is already fixed by https://github.com/PrestaShop/PrestaShop/pull/14605

Regards

**Closed as completed by marionf** 2019-08-16 07:43 UTC
Labels: Duplicate

**Comment by khouloudbelguith** [comment] 2020-10-08 09:48
Duplicate of #14604
