### ISSUE TITLE
cache APCu

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#10163] opened 2018-08-28 06:32 UTC
Prestashop 1.7.4.2
debian 9 on VPS with php 7.2.9 4Gb ram
10.1.26-MariaDB-0+deb9u1
if I try to add APCu on cache, after some minutes of playing on backoffice, the system crash with an 500 error, and I've to restart the VPS to have my prestashop that works well.

**Comment by khouloudbelguith** [comment] 2018-08-28 08:25
Hi @centoasa,
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- debug mode report
- PHP error logs
- apache error log
- javascript console log
- screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-29 07:27
I can't reproduce in short time, because if I reproduce it, my website crash, and in this time I've some business to close. Now I've change my vps using nginx as proxy as I say on #10156

**Comment by khouloudbelguith** [comment] 2018-08-29 08:37
Hi @centoasa,

So can I close the ticket since you can't reproduce it?

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-29 09:55
Just tested: if I enable memcached, and insert as my server 127.0.0.1 11211 1
the script that prestashop generate (as search index, google sitemap etc) being egenrated in a large amount of time (15-20 mins);
instead if I enable APCu, see error log, and my site crash, on homepage I've the maintenance page.


[Documents.zip](https://github.com/PrestaShop/PrestaShop/files/2331682/Documents.zip)

**Comment by khouloudbelguith** [comment] 2018-08-29 09:58
Hi @centoasa,

Isn't the same issue described above: https://github.com/PrestaShop/PrestaShop/issues/9542?

Best regards, Khouloud

**Comment by centoasa** [comment] 2018-08-29 10:00
Yes @khouloudbelguith for memcached it's the same issue on #9542

**Comment by khouloudbelguith** [comment] 2018-08-29 10:01
Hi @centoasa,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of ##9542
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-08-29 10:01
Duplicate of #9542

**Closed as completed by khouloudbelguith** 2018-08-29 10:01 UTC
Labels: Bug, BO, Duplicate, Performance, 1.7.4.2
