### ISSUE TITLE
A story of Stock available, hook and webservice

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#17750] opened 2020-02-20 04:32 UTC
When we update the stock available by the webservice, the hook "actionUpdateQuantity" is not run.

Is there something more to do to run the hook when we update qty by API?

EDIT: @michjoh seems to request a pull for a solution but there is no review for his code...
https://github.com/PrestaShop/PrestaShop/pull/13213

EDIT2: We tested with a product with attribut, the hook "actionUpdateQuantity" is run.
But without attribut the hook is not run.

PS 1.7.5.2

**Comment by florine2623** [comment] 2020-02-20 10:40
Hi @BenTen ,
Thanks for your request, a similar issue already exists. I will close this issue.
You can find more info on that issue : https://github.com/PrestaShop/PrestaShop/issues/13006
Thanks

**Comment by florine2623** [comment] 2020-02-20 10:41
Duplicate of #13006

**Closed as completed by florine2623** 2020-02-20 10:40 UTC
Labels: Duplicate
