### ISSUE TITLE
nav-bar is a class in html, but marked as id in css

### ISSUE THREAD

**Issue by jachymb** [PrestaShop/PrestaShop#10885] opened 2018-10-06 09:04 UTC
**To Reproduce**
Symptom: When I click "Print order" in the admin section. There is rubbish from the sidebar in the printed page.

**Describe the bug**
I believe that the cause is following: This is in the html page:

    <nav class="nav-bar d-none d-md-block" role="navigation" id="nav-sidebar">

But there is 

            #header, #footer, #nav-bar, #nav-topbar, .hidden-print
                display: none !important

in `admin/themes/default/sass/partials/_print.sass`

So the solution probably is to change the `_print.sass` file to use either `.nav-bar` or `#nav-sidebar` instead of `#nav-bar`.

**Screenshots**
I'm lazy, but can provide if requested more explicitly.

**Comment by jachymb** [comment] 2018-10-06 09:25
Note: there is also mention of `#nav-bar` in the file `admin/themes/default/sass/partials/_rtl.sass`

**Comment by khouloudbelguith** [comment] 2018-10-08 11:01
Hi @jachymb,

This is the PR to fix the issue: #10135
The issue will be fixed on 1.7.5.0. I'm closing as this is a duplicate of #9527.

**Comment by khouloudbelguith** [comment] 2018-10-08 11:02
Duplicate of #9527

**Closed as completed by khouloudbelguith** 2018-10-08 11:01 UTC
Labels: Duplicate
