### ISSUE TITLE
activity review - errors in the visualization of information from statistical modules and google analytics

### ISSUE THREAD

**Issue by WartoWiedziec** [PrestaShop/PrestaShop#21754] opened 2020-11-04 16:42 UTC
#### Describe the bug
Since installing the new version of PS 1.7.6.7 and also after updating to 1.7.6.8, I have a problem with the correct reading of data in this module.
#### Expected behavior
The marked points show the places where errors are revealed:
- Online Visitors:
+ is: shows 30 a at the same time
+ should be: Stats is 16.
- Traffic source:
+ is: from the beginning it shows invariably one source and the number 3
+ should be: more sources
Tried wiping, uninstalling and reinstalling - it doesn't help.
In the previous version, 16 worked without a problem.
Where to find the cause?

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.30
![Inked2020-11-04 (3)_LI](https://user-images.githubusercontent.com/6594124/98139367-69a86900-1ec4-11eb-9140-43663b83f9cb.jpg)
![Inked2020-11-04 (5)_LI](https://user-images.githubusercontent.com/6594124/98139402-762cc180-1ec4-11eb-9ba4-a82b67a370dd.jpg)

**Comment by florine2623** [comment] 2020-11-05 08:15
Hi @WartoWiedziec ,
I can't reproduce the issue on my test shop. Make sure you don't not use the Demo mode :
![Capture d’écran 2020-11-05 à 09 13 49](https://user-images.githubusercontent.com/16019289/98214896-5e4a5180-1f47-11eb-8816-984e2c4cc7e2.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thank you

**Closed as completed by florine2623** 2020-11-05 08:15 UTC
Labels: No change required
