### ISSUE TITLE
Problem with subscribing to the newsletter in the Customer Panel

### ISSUE THREAD

**Issue by dzeek93** [PrestaShop/PrestaShop#25229] opened 2021-07-05 07:55 UTC
#### Describe the bug
Hello,
The problem occurs when logging in to the user account and subscribing to the newsletter from the Customer Panel. The problem does not arise when subscribing to the newsletter on the home page (in the footer). I noticed that the problem occurs when a voucher code is entered in the newsletter subscription module, which is to be sent to customers joining the "Newsletter". When the welcome code is removed in the module and the settings are saved, the error when joining the subscription does not occur. I also noticed that the error only shows up when debugging mode is enabled. When this mode is turned off, the problem does not occur. The "Newsletter subscription" module is in version 2.6.1. 
I would like to add that despite the fact that the error appears in the customer panel, the e-mail with the voucher is sent to the user's e-mail. When I refresh the page with an error, the settings are saved correctly.

#### Expected behavior
When subscribing to the newsletter via the Customer Panel, an e-mail with the voucher should be sent to the customer without errors displayed on the website.

#### Steps to Reproduce

1. Turn on debug mode
2. Go to 'Modules' and  search "Newsletter subscribtion"
3. Click on "Configure"
4. Turn on "Send a verification email for subscribing to the newsletter?"
5. Turn on "Send an e-mail confirming subscription to the newsletter?"
6. Enter a welcome discount voucher in blank space.
7. Save your settings.
8. Create an account on front page without subscribing to newsletter.
9. Log in to your new account
10. Go to "Informations"
11. Enter your password, and Check "Subscribe to the newsletter" and Accept the Terms of use, 
12. Click on "Save" button.

**Screenshots**
![error](https://user-images.githubusercontent.com/86950542/124437159-13533900-dd77-11eb-8466-088b8fe30b81.png)

#### Additional information
* PrestaShop version: 1.7.7.5
* PHP version: 7.3.21

**Comment by hibatallahAouadni** [comment] 2021-07-05 13:12
Hello @dzeek93 

I didn't manage to reproduce your issue with PS1775, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/124476622-562b0600-dda3-11eb-8de1-02cc817ecdbc.png)

![image](https://user-images.githubusercontent.com/23308427/124476566-44e1f980-dda3-11eb-903f-facdcab89564.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-26 14:44
Hello @dzeek93 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-26 14:44 UTC
Labels: Bug, FO, Customer, Blocknewsletter, No change required, 1.7.7.5
