### ISSUE TITLE
Problem with update product data - ecotax

### ISSUE THREAD

**Issue by dsamsoniuk** [PrestaShop/PrestaShop#26083] opened 2021-10-04 15:11 UTC
#### Description

Not fully updating product data. When i try 'save' changes of edited product I get an error 'Cannot update settings'.

This problem only appears when my profile account have set language 'Polish'. The reason of this fail is ecotax, in poland this tax not exists so i should have value '0.000' but it gets '0,000', they differe comma.

#### Solution

Place where appears error:
https://github.com/PrestaShop/PrestaShop/blob/14cb6a4c6e72c55c16a95cfbe4aeb8e44fe73ab5/src/Adapter/Product/AdminProductWrapper.php#L152

##### How to solve problem

```php
$ecoTaxFloat = floatval(str_replace(',', '.', $combinationValues['attribute_ecotax']));
$combinationValues['attribute_ecotax'] = Tools::ps_round(
    $ecoTaxFloat / (1 + Tax::getProductEcotaxRate() / 100),
    $computingPrecision
);
```
#### My system
* php7.2
* prestashop 1.7.7.8

**Comment by hibatallahAouadni** [comment] 2021-10-04 15:15
Hello @dsamsoniuk 

Could you please provide steps to reproduce the issue :pray: 
And could you please check this EPIC #14900 you may find your issue listed here.
Please check and feedback.

Thanks!

**Comment by dsamsoniuk** [comment] 2021-10-05 06:30
yes, sory about that. I did't found any similar problem.

### How to reproduce the issue

#### My config system
* ps 1.7.7.8
* mysql 15.1
* php 7.2
* installed polish language in transaltions

#### Steps
1. Change prestashop language to 'polish' on BO > My profile
2. Go to Catalog (Katalog) > Products (Produkty) > 'Chooce any product with **combination**' > Edit product
3. And simplie click 'Save' (Zapisz) - changes 

After this action will appear red toast on the right corner:


![Screenshot_2021-10-05_08-21-28](https://user-images.githubusercontent.com/138824/135971017-4d56de74-6089-4ec5-a235-5b70791602c2.png)

**Comment by florine2623** [comment] 2021-10-05 09:48
Hello @dsamsoniuk ,

I can't reproduce your issue in PS 1.7.7.8, please check my screen record :
https://watch.screencastify.com/v/P4hE8KetsW0Otd8Mgra9

I see you mentioned the ecotax, I also tried to modify the ecotax, but I still didn't encounter your issue :
<img width="1250" alt="Screenshot 2021-10-05 at 11 48 08" src="https://user-images.githubusercontent.com/16019289/136000534-ebe7cc62-0869-4951-b96a-2aa6065cc062.png">

**Comment by dsamsoniuk** [comment] 2021-10-05 10:26
To make sure that Im not wrong I have made full clean copy of ps 1.7.7.8 and i have the same issue.

From your screen i see 'eco tax' input number i don't have something like this. 
Also i don't have in role tax 'FR Taux standard (20%)'

On my copy i have only installed English and Polish language 

![error-ps](https://user-images.githubusercontent.com/138824/136005394-e809d27f-bf31-472c-9781-167d346d99ea.png)

**Comment by florine2623** [comment] 2021-10-05 12:47
Hello,

Is it possible that you reinstall your shop if you have not yet started selling ? I can see that you are not editing your product, but existing example products.

With the same config as you, I can't reproduce your issue (polish rate, no exotax) :
https://watch.screencastify.com/v/F5SxHI06qShc6BTbsXJz

**Comment by dsamsoniuk** [comment] 2021-10-07 13:07
Ok I found a reason, turn on DEBUG MODE
with version php 7.2 it will give error toast, but in php 7.3 this looks like is fixed and works fine with debugger and without.

**Comment by khouloudbelguith** [comment] 2021-10-08 15:51
Hi @dsamsoniuk,

We are awre of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #25797
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2021-10-08 15:51
Duplicate of #25797

**Closed as completed by khouloudbelguith** 2021-10-08 15:51 UTC
Labels: Bug, BO, Duplicate, Taxes and Prices, 1.7.7.8
