### ISSUE TITLE
PS 1.7.4.2 Error on Checkout:  ContextErrorException in smarty_internal_templatebase.php

### ISSUE THREAD

**Issue by tzak902** [PrestaShop/PrestaShop#12279] opened 2019-01-23 20:18 UTC
On Checkout, I get this error:

ContextErrorException in smarty_internal_templatebase.php(157) : eval()'d code line 64:
Notice: Undefined offset: 221

I put item in cart.
I checkout
I fill in the Payment information and submit it.

**Screenshots**

![smarty_internal_templatebase_issue](https://user-images.githubusercontent.com/39320435/51634347-084b1c00-1f22-11e9-8483-03aa3bd974a2.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-01-24 07:45
Hi @tzak902,

What is the exact payment method did you use?
Thanks!

**Comment by tzak902** [comment] 2019-01-24 11:40
Salam Khouloud,
It was Mangopay Gateway

**Comment by khouloudbelguith** [comment] 2019-01-24 11:42
@tzak902, if you try with another payment method, have you the same issue?
Thanks!

**Comment by tzak902** [comment] 2019-01-24 11:48
I can't use any other payment gateway other than Mangopay, as we have a contract with them, can you explain me what is that error related to?

**Comment by khouloudbelguith** [comment] 2019-01-24 11:53
@tzak902, have you tried to contact them?
You should contact the module author via your addons.prestashop.com account: https://addons.prestashop.com/en/contact-us?id_product=17675
Thanks to check the issue with them & feedback

**Comment by tzak902** [comment] 2019-01-24 12:12
How can you assume that it is a mangopay issue? I never had issue like this. I'm closing this issue as it is useless to seek help from people with no knowledge, it is just a waste of time.

**Comment by khouloudbelguith** [comment] 2019-01-24 13:10
Hi @tzak902,

With fresh install PS1.7.4.4 & PS1.7.5.0, I did not manage to reproduce the issue, I used a payment method provided by PrestaShop.
I attached a video record.
https://drive.google.com/file/d/1RLjZVjFkfgBcu8KKYVH4ftBkexS-MJm2/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-24 13:17
@tzak902, could you please provide me your module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-25 07:38
Hi @tzak902,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-02-25 07:38 UTC
Labels: Bug, FO, Payment methods, No change required, 1.7.4.2
