### ISSUE TITLE
1 click update from ps 1.7.5 to 1.7.6.2 not working

### ISSUE THREAD

**Issue by antoniopineapple** [PrestaShop/PrestaShop#15107] opened 2019-08-14 07:39 UTC
Hi when i clic  1 click update button, the system return an error 500 
php 7.2

error log
*ERROR* 	v1.7.5.0	2019/08/13 - 00:09:59: Invalid category vars at line 384 in file classes/Link.php

**Comment by mariem-abid** [comment] 2019-08-14 08:06
Hi @antoniopineapple,

Do you want to upgrade from PS 1.7.5 to the last version PS 1.7.6.0?

**Comment by antoniopineapple** [comment] 2019-08-14 08:10
Yes i tried to update it with 1 click update but its not working,

**Comment by mariem-abid** [comment] 2019-08-14 08:12
@antoniopineapple, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by antoniopineapple** [comment] 2019-08-14 08:41
can i send you the errors in private please?

**Comment by mariem-abid** [comment] 2019-08-15 15:57
Hi @antoniopineapple,

Could you please send them to this email address "khouloud-belguith.ext@prestashop.com"

**Comment by antoniopineapple** [comment] 2019-08-16 17:06
sent

**Comment by antoniopineapple** [comment] 2019-08-20 16:28
Hello there any update?

**Comment by khouloudbelguith** [comment] 2019-08-21 11:44
Hi @antoniopineapple,

Thanks for your email.
Yes, I checked your log file.
When debug mode enabled there is no exception displayed?
What is the exact version of the 1-click upgrade did you use?
In your log file, this error `ERROR v1.7.5.0	2019/08/13 - 00:09:59: Invalid category vars at line 384 in file classes/Link.php` is not displayed.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-22 09:44
@antoniopineapple, did you use a Memcached?

Thanks!

**Comment by antoniopineapple** [comment] 2019-08-22 10:16
What is it?

⁣Ottieni BlueMail per Android ​

Il giorno 22 Ago 2019, 11:45 AM, alle ore 11:45 AM, khouloudbelguith <notifications@github.com> ha scritto:

**Comment by antoniopineapple** [comment] 2019-08-22 10:34
Do you mean 
If i have active the cache? Like smart cache and the others kind? If so yes but i tried to reapeat the process turning off all the cache but the problem still remain

⁣Ottieni BlueMail per Android ​

Il giorno 22 Ago 2019, 11:45 AM, alle ore 11:45 AM, khouloudbelguith <notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2019-08-22 10:55
@antoniopineapple,
![memcached](https://user-images.githubusercontent.com/16067358/63509310-c1330280-c4d3-11e9-9457-783000ba4c47.png)
Thanks!

**Comment by antoniopineapple** [comment] 2019-08-22 11:25
Use cache is setted to no right now

⁣Ottieni BlueMail per Android ​

Il giorno 22 Ago 2019, 1:10 PM, alle ore 1:10 PM, khouloudbelguith <notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2019-08-22 11:33
@antoniopineapple, after disabling the cache, do you still have the same issue?

Thanks!

**Comment by antoniopineapple** [comment] 2019-08-22 12:12
Yes

⁣Ottieni BlueMail per Android ​

Il giorno 22 Ago 2019, 1:34 PM, alle ore 1:34 PM, khouloudbelguith <notifications@github.com> ha scritto:

**Comment by khouloudbelguith** [comment] 2019-08-22 12:26
@antoniopineapple, did you use the module Megamenu?

Thanks!

**Comment by antoniopineapple** [comment] 2019-08-23 15:10
Hi we are using z.one megamenu v 1.0 that comes with this theme
https://addons.prestashop.com/it/temi-elettronica-high-tech/26930-zone-supermarket-online-shop.html

**Comment by khouloudbelguith** [comment] 2019-08-23 15:43
@antoniopineapple, could you please try to disable this module temporarily & check the upgrade again.

Thanks!

**Comment by antoniopineapple** [comment] 2019-08-26 16:42
Hi there
i tried different stuff:
1) disable megamenu----->same problem
2)disable all no prestashop modules-------> same problem
3) activate classic theme and disable all non prestashop modules-----> same problem

**Comment by antoniopineapple** [comment] 2019-08-26 16:44
*ERROR* 	v1.7.5.0	2019/08/26 - 18:01:01: Link to database cannot be established: SQLSTATE[HY000] [1203] User g***********a already has more than 'max_user_connections' active connections at line 127 in file classes/db/DbPDO.php
*ERROR* 	v1.7.5.0	2019/08/26 - 18:01:31: Invalid category vars at line 384 in file classes/Link.php

**Comment by khouloudbelguith** [comment] 2019-08-27 09:57
@antoniopineapple,
>ERROR v1.7.5.0	2019/08/26 - 18:01:01: Link to database cannot be established: SQLSTATE[HY000] [1203] User g***********a already has more than 'max_user_connections' active connections at line 127 in file classes/db/DbPDO.php

That means that the specific database user has already used up all the concurrent connections at that moment and more cannot be processed.
The only option to fix without doing any programming changes is to change the max_user_connections value in MySQL configuration
You need to increase your `max_user_connections` (https://dev.mysql.com/doc/refman/8.0/en/user-resources.html)

**Comment by antoniopineapple** [comment] 2019-08-27 17:30
i set the connection to 200, and tried again deactivating the megamenu,
now i have a whitepage when i click to configure "one click upadate"
in the log i still have this error
*ERROR* 	v1.7.5.0	2019/08/27 - 19:26:10: Invalid category vars at line 384 in file classes/Link.php

**Comment by antoniopineapple** [comment] 2019-08-27 17:35
the line 384 on link.php says: throw new PrestaShopException('Invalid category vars');

**Comment by khouloudbelguith** [comment] 2019-08-28 08:49
@antoniopineapple, did you delete demo categories?
I think that there is a theme module that tries to catch default categories. 
Could you please try to switch to the classic theme and then back to the custom theme.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-30 08:30
Hi @antoniopineapple,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-30 08:30 UTC
Labels: Bug, Autoupgrade, No change required, 1.7.6.0
