### ISSUE TITLE
Missing product name in template "order_customer_comment"

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#27581] opened 2022-02-03 11:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In mail template "order_customer_comment" the {product_name} variable is not included in the content of the mail, while it's loaded by the controller. No way for the admin to know which product the customer is talking about.

Moreover, the mail say "Hello {firstname} {lastname}", but this email is sent to the admin of the shop and firstname and lastname are information about the customer... so it should just be "Hello"

### Expected behavior

Having the product name included in the content of the mail

### Steps to reproduce

1. from an order detail in front-end, choose a product and send a message about that product.
2. Check your mail as the shop administrator... the product name is not mentioned in that mail...

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-02-03 16:18
Related to #21296

**Comment by hibatallahAouadni** [comment] 2022-02-03 18:31
Hello @Prestaplugins 

I reproduce both issues:
1. the mail say "Hello {firstname} {lastname}" using the customer first/last name, while it should be the first/last name of the admin
![image](https://user-images.githubusercontent.com/23308427/152405857-49879218-98ea-49de-982b-16fde62bb9ea.png)

2. the product name is not mentioned in the email, only the order reference. But I think this issue is an improvement more than a bug

I’ll add this to the debug backlog so that it’s fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: ping @MatShir wdyt of the second issue, should we treat it as an improvement in different issue or as a bug?

Thank you

**Comment by Prestaplugins** [comment] 2022-02-03 19:34
Hello,

The 2nd point is more an issue than an improvement, because in the front-end the customer has to choose a product which is never mentioned to the admin, moreover the controller already set the product_name variable so it can be used into the mail... but it's not.
The only thing to modify to fix this problem is the mail template

Yann

**Comment by hibatallahAouadni** [comment] 2022-02-03 19:40
@Prestaplugins Thanks for your feedback!
Waiting for your PR :rocket:

**Comment by MatShir** [comment] 2022-02-09 10:46
It would be interesting to rearrange the content. The Hi "name" can be more generic, since many people can work on the admin side and put the name of the client next to the order ref. So the admin can see quickly the client name and the order ref. WDYT @Julievrz ?

**Comment by Julievrz** [comment] 2022-02-10 08:51
Here's my suggestion:

"Hello,

You have received a new message from **John Doe** (pub@prestashop.com) about the **AJHDYE** order."

**Comment by Julievrz** [comment] 2022-02-10 08:53
[Update: I've added the product information, so the 2nd suggestion seemed better and easier to scan for the merchant.] 

"Hello,

You have received a new message. 

Customer: **John Doe**
Order reference: **AJHDYE**
Product: **Hummingbird t-shirt**"

**Comment by MatShir** [comment] 2022-02-10 09:13
> [Update: I've added the product information, so the 2nd suggestion seemed better and easier to scan for the merchant.]
> 
> "Hello,
> 
> You have received a new message.
> 
> Customer: **John Doe** Order reference: **AJHDYE** Product: **Hummingbird t-shirt**"

What do you think @Prestaplugins ?  If it makes sense for you, could you include the wording into your PR ?

**Closed as completed** 2022-06-22 13:37 UTC
Labels: Bug, Minor, BO, Order messages, Fixed, Wording ✔️, Email theme, PR available, 1.7.7.8, Verified
