### ISSUE TITLE
Order message regitered on Checkout delivery step use to much php htmlentities and accents become not readable 

### ISSUE THREAD

**Issue by 123monsite-regis** [PrestaShop/PrestaShop#14852] opened 2019-07-25 09:51 UTC
**Describe the bug**
When customers fill the "delivery_message" on the checcout process, accents are converted to Html entities , 
this message is after converted to a customer Message on back Office and merchants are not able to read it correctly.

**To Reproduce**
- beggin a checkout process by adding any product you want,
-  on the delivery step fill "delivery_message"
![image](https://user-images.githubusercontent.com/3170104/61864715-352cbb80-aed2-11e9-9b9d-2ae32743ad15.png)

- if you go back , message accents are converted
![image](https://user-images.githubusercontent.com/3170104/61864767-4bd31280-aed2-11e9-8ba6-0aae948b0166.png)

- continue order, and pay (no matters the paiement means not the carrier)

- if you go  on Back office customer service, this message have whithout suprise lost accents :)

**Additional information**
PrestaShop version: 1.7.6 (but occurs since 1.7)

**Comment by 123monsite-regis** [comment] 2019-07-25 09:53
for the dev's,

this line is concerned : 
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/checkout/CheckoutSession.php#L89

```php
    public function setMessage($message)
    {
        $this->_updateMessage(Tools::safeOutput($message));
        return $this;
    }
```
but i does not know the right prestashop practice to be safe and keep accents.

regards

**Comment by khouloudbelguith** [comment] 2019-07-26 06:47
Hi @123monsite-regis,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9726
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-07-26 06:47 UTC
Labels: Duplicate
