### ISSUE TITLE
Decimal points - causing incorrect prices in cart and checkout page

### ISSUE THREAD

**Issue by aruneaskan** [PrestaShop/PrestaShop#22653] opened 2021-01-04 12:06 UTC
#### Describe the bug

I changed the currency decimals to 0.

For example - product price - Rs. 128.00 + tax 5% = Rs. 134.40 - it is showing like this Rs 134. (this is good). But in cart and checkout pricing are confusing. Refer to the below screenshot

![image](https://user-images.githubusercontent.com/39294418/103532932-2c575c00-4eb2-11eb-8af0-d723a1dce8dd.png)

* PrestaShop version: 1.7.7
* PHP version: 7.3

**Comment by Hlavtox** [comment] 2021-01-04 15:36
@aruneaskan Set your product price to 127,3/134 and let us know

**Comment by hibatallahAouadni** [comment] 2021-01-04 17:09
Hello @aruneaskan 

Could you please follow @Hlavtox instruction and feedback.

Thanks!

**Comment by aruneaskan** [comment] 2021-01-05 05:07
![image](https://user-images.githubusercontent.com/39294418/103608561-a4209780-4f41-11eb-8900-7d6a0c7666dc.png)
![image](https://user-images.githubusercontent.com/39294418/103608683-e3e77f00-4f41-11eb-9765-a9ac5f735c20.png)

As suggested I updated the price. Still not calculating the right price. Please refer to the above screenshots.

**Comment by hibatallahAouadni** [comment] 2021-01-05 16:34
Hello @aruneaskan 

Could you please add a clear and concise steps to reproduce the issue and expected behavior and edit your issue's description **following the template to submit a complete bug report**.

Thanks!

**Comment by aruneaskan** [comment] 2021-01-06 12:23
Hi @hibatallahAouadni 

Login to BO -> Catalog -> Products -> Edit any product -> Combinations -> Edit one of the combination product -> Original price Rs. 128.00  -> Tax 5% -> Rs. 134.4 (Tax included)

International -> Localization -> Currencies -> Edit respective currency -> Decimals -> Set to 0 -> Showing as Rs. 134

Now the product is added with 2 Qty in the cart-> Now the price calculating as 134.4*2 = 268.8 (Rounded to 269)
![image](https://user-images.githubusercontent.com/39294418/103768160-095eb080-5048-11eb-9ccc-7df74ed7b779.png)
 
Shop Parameters -> Customer Settings -> Groups -> Edit each group -> Price display method -> Choose Tax included

Please let me know if this helps

Thanks

**Comment by hibatallahAouadni** [comment] 2021-01-06 15:18
Hello @aruneaskan 

You just need to change your configuration: 

![image](https://user-images.githubusercontent.com/23308427/103784814-b0d4e680-503a-11eb-8188-72f296971328.png)

And you get this result:

![image](https://user-images.githubusercontent.com/23308427/103784880-c6e2a700-503a-11eb-8ef5-cfe19617a5ac.png)

I close this issue cause it's not a bug :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-06 15:18 UTC
Labels: Bug, FO, Taxes and Prices, No change required, 1.7.7.0
