### ISSUE TITLE
ISBN and EAN codes are not visible

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19685] opened 2020-06-10 09:01 UTC
#### Describe the bug
We use ISBN and EAN codes for product books. These codes are not visible in the product page also they are not visible in invoices, delivery slips...

#### Expected behavior
We expect that a bussiness user can see these codes if there are filled any values

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1.13

**Comment by florine2623** [comment] 2020-06-11 09:35
Hi @juraj1000 ,
The ISBN and EAN-13 codes are displayed in the product page :
![Capture d’écran 2020-06-11 à 11 28 14](https://user-images.githubusercontent.com/16019289/84369106-aa7ea900-abd6-11ea-8be0-73a24d356837.png)

**Comment by florine2623** [comment] 2020-06-11 09:37
Hi @PrestaShop/prestashop-product-team ,

The ISBN and EAN-13 codes are not displayed on invoices nor credit slips, should these elements be added on these documents ?

Thanks!

**Comment by matthieu-rolland** [comment] 2020-06-15 09:30
Hello @florine2623 , I reproduced this bug on 1.7.7, are you aware of a specific step that must be done in order for specific references to be displayed in FO product page ?

<img width="572" alt="Capture d’écran 2020-06-15 à 11 31 12" src="https://user-images.githubusercontent.com/1784781/84641812-e62db180-aefb-11ea-9c2d-55263deb02f4.png">

**Comment by florine2623** [comment] 2020-06-15 12:29
Hi @matthieu-rolland ,
Thank you, indeed I just tried IN PS 1.7.7.0, the bug appears.
There's nothing special to do in FO in order to get the info displayed.

**Comment by MatShir** [comment] 2020-06-22 09:27
@florine2623 or @matthieu-rolland  Could you confirm it is a regression?

**Comment by marionf** [comment] 2020-06-22 09:44
The issue is only for standard products, it's not a regression
ISBN & EAN are well displayed in FO for a product with combinations

**Comment by marionf** [comment] 2020-06-22 09:48
Duplicate of #15783

**Closed as completed by marionf** 2020-06-22 09:48 UTC
Labels: Bug, FO, Duplicate, 1.7.7.0, 1.7.6.5

**Comment by matthieu-rolland** [comment] 2020-06-22 12:59
thanx @marionf !
