### ISSUE TITLE
Duplication of article features by saving, until the article is rendered useless

### ISSUE THREAD

**Issue by JLSPORT** [PrestaShop/PrestaShop#22916] opened 2021-01-20 13:55 UTC
#### Description:

When we want to add manual feature information to a product, let's say, a Shirt is 90% cotton and 10% Elasthan, so you enter it in the manual value box on that article to the far right. If you don't select a feature and proceed to save, the value will still be saved and additionally recreate a second feature with the same description (90% cotton and 10% Elasthan)

#### Expected behavior:

If i enter a manual value for an article feature without selecting a feature value, it should just be ignored. Especially saving should remind you, that the feature is missing or still on "choose a feature".

#### Steps to Reproduce:

1. Go to any article and open up a new feature
2. Don't select a feature, leave it as "choose a feature"
3. Enter any value in the far right box "Test" for example. 
4. Now click "save"
5. Refresh the page using "control+R"
6. Repeat step 4 and 5 a few times and there you go, infinite feature windows

That way we were unable to use certain articles, since everytime someone saves, it multiplied until the article loaded so slow, that the browser crashed and we had to delete it.

First happened on our own Live shop, that on another new instance for a local shop that we just installed.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/77734740/105183719-cd8b1700-5b2e-11eb-994d-f51937e494d9.png)

#### Additional information

* PrestaShop version: 1.7.6.7 > 1.7.7.1
* PHP version: 7.2

If more information is needed i am free to explain.

**Comment by hibatallahAouadni** [comment] 2021-01-21 08:07
Hello @JLSPORT 

Thanks for your detailed report :clap: 
It seems your issue is similar to this one #16306 could you please check :wink: 

Please check and feedback.
Thanks!

**Comment by JLSPORT** [comment] 2021-01-21 08:27
Hello,

the issue seems to be the same.
Also the added info, that the so created feature lines can't be deleted.

Since it existed before and was neither fixed in 1.7.7.0 nor 1.7.7.1 it 
might take more time i presume.

Thanks for sorting it to the appropriate theme.

best regards,
Benjamin Smarsly.

**Comment by hibatallahAouadni** [comment] 2021-01-21 08:56
Hello @JLSPORT 

Thanks for your feedback :slightly_smiling_face: 
As you can see we are aware of this issue, and it is already in our debug backlog. This issue is a duplicate of #16306. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-21 08:56
Duplicate of #16306

**Closed as completed by hibatallahAouadni** 2021-01-21 08:56 UTC
Labels: Bug, BO, Duplicate, Features, 1.7.7.0, 1.7.6.7
