### ISSUE TITLE
src\Adapter\StockManager - getStockAvailableByProduct() -> Duplicate data on key : product_sqlstock

### ISSUE THREAD

**Issue by jul-m** [PrestaShop/PrestaShop#16240] opened 2019-10-31 16:43 UTC
**Describe the bug**
If the product does not exist in the "ps_stock_available" table, the "getStockAvailableByProduct" function in the "src/Adapter/StockManager" class creates the record. When the command is called by the function "checkProductStock" of the base class Prestashop "OrderDetail" (for example, this function is called in other classes and some modules), the problem occurs (tested on a blank Prestashop installation). This comes from the line "StockAvailable::getStockAvailableIdByProductId($id_product, $id_product_attribute, $id_shop);".

**To Reproduce**
1. Enable multi-store mode without sharing stocks.
2. Delete the record of a product in the ps_stock_available table.
3. Order this product twice in a row. At the 2nd order, an SQL error occurs : Duplicata du champ '1-1-0-0' pour la clef 'product_sqlstock'.

**Screenshots**
![bug_ps](https://user-images.githubusercontent.com/16786004/67966794-c499e700-fc04-11e9-86e9-c63583e3a3a9.JPG)

What happens if the product does not exist in the table "ps_stock_available" and there is not the argument "id_shop" filled in :
-> function "StockManager->getStockAvailableByProduct()" created the record for this product in DB with id_shop = 0.
-> When the product is reordered, the "StockManager->getStockAvailableByProduct()" function searches the stock for this product again, but determines the store id to the "classes\StockAvailable\addSqlShopRestriction()" function. So we have a "WHERE id_shop = 1" for example. It does not find the record already created with "id_shop = 0". It retents to record the same thing in DB, with id_shop = 0, and suddenly we have a duplicate.

Rather than modifying all the classes that call the StockManager->getStockAvailableByProduct() function to add the shop id as an argument, I changed the function as follows:

**File src/Adapter/StockManager.php** :
```php
//[...]

    public function getStockAvailableByProduct($product, $id_product_attribute = null, $id_shop = null)
    {
        $stockAvailable = $this->newStockAvailable($this->getStockAvailableIdByProductId($product->id, $id_product_attribute, $id_shop));

        if (!$stockAvailable->id)
        {
            $shopAdapter = new ShopAdapter();
            $stockAvailable->id_product = (int) $product->id;
            $stockAvailable->id_product_attribute = (int) $id_product_attribute;

            $outOfStock = $this->outOfStock((int) $product->id, $id_shop);
            $stockAvailable->out_of_stock = (int) $outOfStock;

            if ($id_shop === null)
            {
                $shop_group = $shopAdapter->getContextShopGroup();
            }
            else
            {
                $shop_group = $shopAdapter->ShopGroup((int) $shopAdapter->getGroupFromShop((int) $id_shop));
            }

            // if quantities are shared between shops of the group
            if ($shop_group->share_stock)
            {
                $stockAvailable->id_shop = 0;
                $stockAvailable->id_shop_group = (int) $shop_group->id;
            }
            else
            {
                // ADD FIX BUG duplicate product_sqlstock
                if ($id_shop === null)
                {
                    $id_shop = $shopAdapter->getContextShopID();
                }
                // END FIX
                
                $stockAvailable->id_shop = (int) $id_shop;
                $stockAvailable->id_shop_group = 0;
            }
            $stockAvailable->add();
        }

        return $stockAvailable;
    }

//[...]
```

Unfortunately we can not override the classes that are in src, so I should redo the change each update. It would be nice to integrate it into an update, or to find another solution if it is not suitable.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-11-01 08:06
Hi @jul-m,

Thanks for your bug report.
About your second step:
>Delete the record of a product in the ps_stock_available table.

How can I delete the record( manually from the database?)

Thanks!

**Comment by jul-m** [comment] 2019-11-02 01:40
> Hi @jul-m,
> 
> Thanks for your bug report.
> About your second step:
> 
> > Delete the record of a product in the ps_stock_available table.
> 
> How can I delete the record( manually from the database?)
> 
> Thanks!

Hi @khouloudbelguith,

To reproduce the bug, you must delete the record manually from the database.

In my shop, there were some products missing in this table, but I do not know why because normally it should all be there.

Thanks.

**Comment by khouloudbelguith** [comment] 2019-11-04 12:44
@jul-m, 

>To reproduce the bug, you must delete the record manually from the database.

I cannot delete records from the database manually => this is incorrect behavior.
From the BO => there is no option to delete the record of a product in the ps_stock_available table.

Deleting this record manually => this is an insecure way.

Thanks!

**Comment by jul-m** [comment] 2019-11-04 13:08
Hi @khouloudbelguith,

In my case, some records were missing from the "ps_stock_available" table. There is a problem with creating these records, or deleting them. I did not identify the source of this problem.

If I ask to delete directly in database, it is only to reproduce the state in which I found myself. There is obviously no question of doing this on a shop in production.

I am aware that the ideal would be that there is no missing product in this table, but the function getStockAvailableByProduct() checks if the product exists, and saves it even if it does not exist. It seems important to me that it does it correctly, which is not the case in multi-store mode without stock sharing.

**Comment by khouloudbelguith** [comment] 2019-11-04 13:33
@jul-m, 

>I did not identify the source of this problem.

I need to reproduce this problem.
Did you use a fresh install PS1.7.6.1 or an upgrade from a previous version?

Thanks!

**Comment by jul-m** [comment] 2019-11-04 13:47
There have been several updates since version 1.7.1, and many CSV imports.

Difficult to determine when these recordings were not made (or deleted).

That's why I focused my issue on the function getStockAvailableByProduct() which is anyway problematic, because I have no details to bring about the origin of the absence of products in the table " ps_stock_available ".

**Comment by khouloudbelguith** [comment] 2019-11-04 13:53
@jul-m, we need to reproduce the issue first.
If I manage to reproduce the issue without deleting the data from the database, I will add the issue to our bug roadmap.

The stock location field is displayed in your ps_stock_available table?
Is it?
![image](https://user-images.githubusercontent.com/16067358/68125885-e18b2e80-ff12-11e9-9142-3af435d39c07.png)

Thanks!

**Comment by jul-m** [comment] 2019-11-04 19:33
Yes
![Capture](https://user-images.githubusercontent.com/16786004/68151613-56299180-ff42-11e9-89b1-9eb71b0c99c9.JPG)

**Comment by khouloudbelguith** [comment] 2019-11-05 09:33
@jul-m , I tried to follow these steps:
1.Enable multi-store mode without sharing stocks.
2.Delete the record of a product in the ps_stock_available table of a product available in all shops
=> I deleted a record of the first shop => now I cannot order this product in the first shop => because => it is out of stock& it is not allowed to be ordered.
=> If I try to order this product in the second shop multiple times => Ok => no issues
I attached a screen record
https://drive.google.com/file/d/1CTcZkNEVZnF5lIya-qeiZ0WPQi1WYvkB/view

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-05 08:19
Hi @jul-m,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-05 08:19 UTC
Labels: Bug, Stocks, Multistore, No change required, 1.7.6.1
