### ISSUE TITLE
Error 504 Gateway Time-out

### ISSUE THREAD

**Issue by srn87** [PrestaShop/PrestaShop#19470] opened 2020-05-30 00:59 UTC
I am having problems when I try to run a script that what it does is import products from my provider and it does not finish running, I get a 504 ngnix error on the screen before it ends, the hosting provider tells me it has to do with the design of my web, what I do not explain is that I have uploaded the type of server with them and before I did not have that problem and now that I have better vps, I do not understand anything!

`[Sat May 30 02:29:08.664801 2020] [authz_core:error] [pid 18527:tid 140695075485440] [client 66.249.79.190:57802] AH01630: client denied by server configuration: /var/www/vhosts/myweb/web/img/p/1/8/0/3/7
[Sat May 30 02:30:34.534789 2020] [authz_core:error] [pid 17910:tid 140695192983296] [client 66.249.79.190:57816] AH01630: client denied by server configuration: /var/www/vhosts/myweb.es/myweb/img/p/1/6/4/0/0
[Sat May 30 02:35:25.910697 2020] [authz_core:error] [pid 17912:tid 140695083878144] [client 66.249.79.190:57896] AH01630: client denied by server configuration: /var/www/vhosts/myweb/web/img/p/1/6/3/4/8
[Sat May 30 02:38:43.406929 2020] [proxy_fcgi:error] [pid 18527:tid 140695033521920] [client 79.154.179.211:58010] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /var/www/vhosts/myweb.es/myweb/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177\n', referer: https://myweb/content/4-sobre-nosotros
[Sat May 30 02:38:48.210231 2020] [proxy_fcgi:error] [pid 17913:tid 140695100663552] [client 79.154.179.211:58038] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /var/www/vhosts/myweb.es/myweb/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177\n', referer: https://myweb/
[Sat May 30 02:40:33.719002 2020] [proxy_fcgi:error] [pid 18527:tid 140695288698624] [client 79.154.179.211:58238] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /var/www/vhosts/myweb.es/myweb/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177\n', referer: https://myweb.es/
[Sat May 30 02:46:41.643103 2020] [proxy_fcgi:error] [pid 17912:tid 140695142627072] (70007)The timeout specified has expired: [client 79.154.179.211:58344] AH01075: Error dispatching request to :, referer: https://myweb.es/admin35633/index.php?tab=AdminModules&configure=infortisa&token=e59752687b98758f4e8a8b3158554e55&action=import`

PD: i change "myweb" for my real web direction

![errorngnix](https://user-images.githubusercontent.com/66142800/83315613-2103ca00-a219-11ea-84ea-8569ceedf1ae.png)

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.31

**Comment by srn87** [comment] 2020-05-30 18:56
I am trying to solve the problem by looking over the internet for other cases that are similar.

Now appear this:

[Sat May 30 20: 47: 05.445674 2020] [proxy_fcgi: error] [pid 1585: tid 140529677313792] [client 79.154.179.211:42640] AH01071: Got error 'PHP message: PHP Warning: Invalid argument supplied for foreach () in /var/www/vhosts/mysite/mysite/modules/provider/myprovider.php on line 524 \ n ', referer: https: //mysite/index.php? tab = AdminModules & configure = myprovider & token = xxxxxxxxxxxxxxxxxxxxxxx

*PrestaShop version: 1.7.6.4
*PHP version: 7.2.31

**Comment by jolelievre** [comment] 2020-06-01 14:16
Hi @srn87 

If you get this Timeout error, it's probably because you try to import lots of products at a time, and the processing exceeds your Server time limit. You can try one of these solutions:
- import a smaller portion of products
- if your hosting solution allows it, increase your server max timeout

I'm not an expert of nginx thought but maybe something like that:
```
    proxy_send_timeout 180s;
    proxy_read_timeout 180s;
    fastcgi_send_timeout 180s;
    fastcgi_read_timeout 180s;
```

Regarding the warning you get in your logs, it seems related to your module `myprovider` I guess it is used to manage your import? Then maybe the data you are importing are lacking some values that the module is excepting (an empty list/array it would seem)

In any case both these issues seem to be related to either your server environment or an external module and are not related to the PrestaShop core code, so I'm gonna close this issue as we can't reproduce it.

**Closed as completed by jolelievre** 2020-06-01 14:16 UTC
Labels: No change required
