### ISSUE TITLE
$cart->orderExists() and duplicate orders

### ISSUE THREAD

**Issue by hekep** [PrestaShop/PrestaShop#16490] opened 2019-11-21 11:13 UTC
**Describe the bug**
in `AnyPaymentValidationModuleFrontController`  there is code `if($cart->orderExists())` which returns false, if cart  has no order.  Sometimes payment service provider calls two times the same  `AnyPaymentValidationModuleFrontController` url. The result is that  $cart will have 2 orders, which are dulicate,  created within 1 second.

 I suppose `Cart`  can have only one `Order`, right?

**To Reproduce**
Call  `AnyPaymentValidationModuleFrontController`   twice simultainously at the same same time.

**Solution**
Alter  `orders` table. Make `id_cart`  column unique.  One `AnyPaymentValidationModuleFrontController` query (  `PaymentModule->validateOrder()` )  will succeed. The other concurrent  `AnyPaymentValidationModuleFrontController` queries will fail. if  `PaymentModule->validateOrder()`  returns false or throws exception, then my  `AnyPaymentValidationModuleFrontController` has to check  `if($cart->orderExists())`  again.

Is this solution OK ?

**Solution 2**
Create  MySql trigger which suppose to prevent duplicate orders within 5 seconds. One `AnyPaymentValidationModuleFrontController` query (  `PaymentModule->validateOrder()` )  will succeed. The other concurrent  `AnyPaymentValidationModuleFrontController` queries will fail. if  `PaymentModule->validateOrder()`  returns false or throws exception, then  my  `AnyPaymentValidationModuleFrontController`   has to check  `if($cart->orderExists())`  again.

**Additional information**
PrestaShop version: 1.x 
PHP version:  any

**Comment by hekep** [comment] 2019-11-21 11:34
Releated: https://github.com/PrestaShop/PrestaShop/issues/16483

**Comment by khouloudbelguith** [comment] 2019-11-21 12:14
Hi @hekep,

Thanks for your report.
What is the exact version of PrestaShop did you use?
With PS1.7.6, we cannot click twice at the button of payment.
![image](https://user-images.githubusercontent.com/16067358/69334966-1958dc80-0c5c-11ea-8c83-73b55db15057.png)

>Call AnyPaymentValidationModuleFrontController twice simultainously at the same same time.

How can I reproduce the issue, did you use a custom module?
Previously, we have a bug when two customers check out concurrently for the same product.
But it is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/8752

Thanks!

**Comment by hekep** [comment] 2019-11-21 12:52
We were able to create this issue in production. `AdminCarts` shows "duplicate carts" , with the same ID number, and with different Order numbers.  This is becuase of `LEFT JOIN ...`  and no `GROUP BY` sql query.

It is PrestaShop version: 1.7.3.3. I think https://github.com/PrestaShop/PrestaShop/pull/8752 is not related to this particular issue.

Yes we do have custom payment module, which provides callback urls for payment service provider. Payment service provider calls those `AnyPaymentValidationModuleFrontController` -urls, when something order payment related happends.  2 Concurrent queries to `AnyPaymentValidationModuleFrontController` -url caused 2 orders for the same exact cart.

So we want  `id_cart`  column to be unique in `orders` table.

I do not think you are able to reproduce it via WEB UI, easily.  It has to be machine to machine query. 

Out of my experience sometimes with slow mobile connection on WEB UI  user may click many times the "yes confirm order" button because of waiting. Web queries may pile up and cause multiple queries at the same time on the server side resulting duplicate orders.  That is why I refer to `AnyPaymentValidationModuleFrontController` .

**Comment by hekep** [comment] 2019-11-21 12:55
Here is an export of  "duplicate carts" with different order ID:

![image](https://user-images.githubusercontent.com/1901788/69339831-e23ff680-0c6e-11ea-9cba-a6887784525b.png)

I modified names.

**Comment by khouloudbelguith** [comment] 2019-11-21 15:24
@hekep, 

>Out of my experience sometimes with slow mobile connection on WEB UI user may click many times the "yes confirm order" button because of waiting. Web queries may pile up and cause multiple queries at the same time on the server side resulting duplicate orders. That is why I refer to AnyPaymentValidationModuleFrontController .

in the PS 1.7.5.0 we fixed an issue of a double click on Payment button may be related https://github.com/PrestaShop/PrestaShop/pull/9373

What is the exact version PrestaShop did you use?

Thanks!

**Comment by hekep** [comment] 2019-11-22 06:20
PrestaShop version: 1.7.3.3

**Comment by hekep** [comment] 2019-11-22 06:27
What about machine to machine query?

1.  Customer goes to Payment Service provider page
2. Customer returns from Payment Service Provider to  `AnyPaymentValidationModuleFrontController ` with successful payment.
3. Multiple M2M queries can be done  at the same time customer returns to   `AnyPaymentValidationModuleFrontController ` with successful payment.

So we want `id_cart` column to be unique in `orders` table.

This is a bug from "battle test" and not easily reproducible.

**Comment by khouloudbelguith** [comment] 2019-11-22 08:33
@hekep, did you tried to reproduce the issue with PS1.7.6.1?

Because I have an exception & it is not possible to create two orders at the same time
https://drive.google.com/file/d/1eDypd7fbO7nm9FRLlR4LqxxFTtxfL0l-/view

Thanks to check & feedback.

**Comment by hekep** [comment] 2019-11-22 10:23
@khouloudbelguith I can't open the video.

We have not checked PS1.7.6.1.  https://github.com/PrestaShop/PrestaShop/pull/9373/files changes only javascript UI side, not database side. So  I assume in  PS1.7.6.1  it is still possible to create multiple orders. Especially if hacker  bypasses your javascript prevention script and floods Presta ecommerce with "yes confirm order"  queries ...

**Comment by khouloudbelguith** [comment] 2019-11-22 10:26
@hekep, I attached the screen record again
[Untitled_ Nov 22, 2019 9_32 AM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/3879054/Untitled_.Nov.22.2019.9_32.AM.webm.zip)

Thanks!

**Comment by hekep** [comment] 2019-11-22 15:10
As a solution we had to create `my_payment_module_validated_carts` table in DB, with  `id_cart` unique column.  First web-query INSERT SQL query is successful, the following  web-query  INSERT SQL query  fails, and this is how we prevent duplicate orders.

**Comment by khouloudbelguith** [comment] 2019-11-22 15:17
@hekep, did you tried with this fix: https://github.com/PrestaShop/PrestaShop/pull/9373/files?
have you the same after applying this patch?
did you reproduce the issue with PS1.7.6.1?, PS1.7.3.3 is an old version.

Thanks!

**Comment by hekep** [comment] 2019-11-22 15:56
No we have not reproduced the problem with any other version. As I said this is not easy to reproduce.

How ever we have created module, to remove duplicate orders form e-commerce.

https://github.com/AhcoOy/ahcoprestatools

**Comment by khouloudbelguith** [comment] 2019-11-22 16:23
Hi @hekep,

Thanks for your feedback.
but since I did not manage to reproduce the issue, we need to close the issue.

Thanks!

**Comment by ddtloan** [comment] 2019-11-25 08:31
Recently, I have the same issue. It split to 2 orders same reference. But user only create 1 order. Hard to reproduce it. But it still displays.

**Comment by khouloudbelguith** [comment] 2019-11-25 08:37
Hi @ddtloan,

Split order in two orders, it is another issue:
This issue of split orders.
In your case,
1. Do you have more than one carrier?
2. For product 1 which can be shipped to the customer's address => in the BO => Product details page => Shipping Tab => you have selected a specific Carrier?
3. For the product 2 which cannot be shipped to the customer's address => in the BO => Product details page => Shipping Tab => all carriers are available?
4. The product1 which has an order1 => the carrier select is carrier1?
5. The product2  which has an order2 => another carrier is selected?

Thanks!

**Comment by ddtloan** [comment] 2019-11-25 08:51
![image](https://user-images.githubusercontent.com/54904401/69525575-fd767300-0f9a-11ea-98b8-e406aa362cfd.png)
1. Yes, we have more than carrier. But in this time, we only use 1 carries and make it as default. Then we hide it on FO. So that, end user can not change / select carrier. 
2 & 3. I do not select a specific carrier. And with 2 order it also can be shipped to the customer's address.
4 & 5. Same carrier for order 1 and order 2. But some products have different supplier.

**Comment by hekep** [comment] 2019-11-25 09:22
No spliting carriers. Only ONE article row and only  one warehouse.  No advanced stock.

We have DUPLICATE ,   cloned orders, with the same id_cart, done in one second.  As I said before, cart has got 2 orders.  https://github.com/PrestaShop/PrestaShop/issues/16490#issuecomment-557072471  The cart 6756 has only one article row.  These duplicate orders have THE SAME carrier.

Now I see, why you do not want to  `id_cart` column to be unique in `orders` table. It is because of split orders, and multiple warehouses.

**Comment by khouloudbelguith** [comment] 2019-11-25 15:00
@ddtloan, did you delete your last comment?
>![image](https://user-images.githubusercontent.com/54904401/69525575-fd767300-0f9a-11ea-98b8-e406aa362cfd.png)
Prestashop version: 1.7.5.0
1/ Yes, we have more than carrier. But in this time, we only use 1 carrier and make it as default. Then we hide it on FO. So that, end user can not change / select carrier. 
2 & 3/ I do not select a specific carrier. And with 2 orders it also can be shipped to the customer's address.
4 & 5/ Same carrier for order 1 and order 2. But some products have different supplier. 

@hekep,
>Now I see, why you do not want to id_cart column to be unique in orders table. It is because of split orders, and multiple warehouses.

 so I think that your solution cannot be applied, is it?

Thanks!

**Comment by ddtloan** [comment] 2019-11-25 15:18
Hi, I repost it at here. 
Prestashop version: 1.7.5.0
1/ Yes, we have more than carrier. But in this time, we only use 1 carrier and make it as default. Then we hide it on FO. So that, end user can not change / select carrier.
2 & 3/ I do not select a specific carrier. And with 2 orders it also can be shipped to the customer's address.
4 & 5/ Same carrier for order 1 and order 2. But some products have different supplier.
![image](https://user-images.githubusercontent.com/54904401/69552665-6f69af00-0fd1-11ea-8256-b4611ded8500.png)

I have 13 duplicated order / 4415 orders.

**Comment by khouloudbelguith** [comment] 2019-11-25 16:49
@ddtloan, I think, your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/11115, is it?

Thanks!

**Comment by hekep** [comment] 2019-11-26 07:42
> As a solution we had to create `my_payment_module_validated_carts` table in DB, with `id_cart` unique column. First web-query INSERT SQL query is successful, the following web-query INSERT SQL query fails, and this is how we prevent duplicate orders.

This is not helping us. 

The duplicate orders have different references.

**Comment by khouloudbelguith** [comment] 2019-11-26 08:02
@hekep, no, it is not your issue, #11115 is similar to @ddtloan' s issue.

Thanks!

**Comment by ddtloan** [comment] 2019-11-26 08:11
Hi @khouloudbelguith ,
#11115 is not my issue. After check with client, they bought only 1 order with 6 products. With, in BO it show 3 products in first cart, and 3 products in another cart. I have tried to reproduce with same products, but cannot. So I think it is not relate to carrier (we only 1 default carrier and user cannot change / select). 

Bellow is another order related to duplicated reference:
![image](https://user-images.githubusercontent.com/54904401/69610598-b651b600-105e-11ea-9dc3-c4d89d930f99.png)

Under order, it shows "reference order"
![image](https://user-images.githubusercontent.com/54904401/69610897-4db70900-105f-11ea-96d7-626b2c02eb20.png)



----
Some order it slip to 2 parts. And some order it duplicates all contents.

**Comment by khouloudbelguith** [comment] 2019-11-26 09:08
@ddtloan, thanks for your feedback.
The payment method used in your case, is it the native module provided by PrestaShop or bought from our Addons Market place?
This issue occurs only when using this payment module?

Thanks!

**Comment by ddtloan** [comment] 2019-11-26 09:40
@khouloudbelguith 
Cash on delivery method is provided by PrestaShop. And currently, this issue only occurs with COD method.
![image](https://user-images.githubusercontent.com/54904401/69617871-7a711d80-106b-11ea-9059-de6ceb02d92f.png)

**Comment by khouloudbelguith** [comment] 2019-11-26 10:58
Hi @ddtloan,

I did not manage to reproduce the issue with PS1.7.6.1 & COD v1.0.6.
I attached a screen record
https://drive.google.com/file/d/14ku1fALe8AiEo3lphWsoC-XZn7EWx7CY/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by hekep** [comment] 2019-11-26 12:41
For some reason we have got 6 orders per 1 cart, which has only one row.

![image](https://user-images.githubusercontent.com/1901788/69634172-5bb65b00-105a-11ea-8084-6d4ccf79bd4b.png)

**Comment by khouloudbelguith** [comment] 2019-11-26 13:28
@hekep, did you use a specific payment module?
Your screenshot od from the shopping cart page.
Have you the same duplicated orders in the BO => Order page?
Did you use the Mailchimp module?

THanks!

**Comment by hekep** [comment] 2019-11-28 15:55
@khouloudbelguith  

-  Yes we are using our own payment module.
- I deleted real customer data from the screen shot
- Yes BO orders list page has duplicate orders , with different order references
- No, no mailchimp module.

We also think the problem is in the Cache.
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cart.php#L1642

2  concurrent "confirm order" queries create 2 orders.

**Comment by khouloudbelguith** [comment] 2019-11-28 16:21
@hekep, 2 concurrent "confirm order" queries create 2 orders.
The second-order cannot be validated because of this error "cart cannot be loaded"

https://drive.google.com/file/d/1ZkjajnqUGKKd1Shg17_jmgsb2sU1aHXq/view
-Same customer
-Same browser session
-Same order, click on the confirm at the same time.

Thanks!

**Comment by hekep** [comment] 2019-11-29 09:28
@khouloudbelguith  idk about  "cart cannot be loaded" or why it is  "cart cannot be loaded" , even if cart  has an order allready.

FYI , In our Payment module we depricated use of  `$cart->orderExists()`  because of cache ( use direct DB queries ) and created a extra table.    

On Black Fridays server can be easily overloaded and duplicates are easy to come. 

Happy Black Friday to Prestashop team!

**Comment by khouloudbelguith** [comment] 2019-11-29 09:40
@hekep, can you try to reproduce the issue using a native module provided by PrestaShop & not your own module.
Because as it's not provided by Prestashop, we can't do anything with this. 

Thanks!

**Comment by hekep** [comment] 2019-11-29 10:02
I tried with multiple  `jQuery.get('')`  on  `/module/ps_checkpayment/validation`  and I got error message with the second query 'This payment method is not available.'   Obviously I did not get not enough concurrent queries with  `jQuery.get('')` , so I was not successful. This is a matter of milliseconds concurrency.

This happened in production, FYI.

**Comment by khouloudbelguith** [comment] 2019-11-29 10:09
@hekep, so you tried to edit this file `/module/ps_checkpayment/controllers/front/validation.php` to have a lot of orders at the same time? but it cannot be reproduced?

Thanks!

**Comment by hekep** [comment] 2019-11-29 11:15
No, not editing. I tried to to multiple concurrent ajax calls with `jQuery.get('')` to `/module/ps_checkpayment/validation` url. I could not  reproduce the problem....  Error messages are misleading anyways. Why `Module::getPaymentModules()` did not  return 'ps_checkpayment' in `Ps_CheckpaymentValidationModuleFrontController` is not understandable.

In our payment module we have removed this code
`
$authorized = false;
        foreach (Module::getPaymentModules() as $module) {
            if ($module['name'] == 'ps_checkpayment') {
                $authorized = true;
                break;
            }
        }
`
`
        if (!$authorized) {
            die($this->trans('This payment method is not available.', array(), 'Modules.Checkpayment.Shop'));
        }
`

Because `Module::getPaymentModules()` is too hard coupled with session customer.  We have another pull request pending https://github.com/PrestaShop/PrestaShop/pull/16388 . Machine to Machine call does not have session `context->customer`, so it fails right there.

**Comment by khouloudbelguith** [comment] 2019-11-29 11:38
@hekep, Could you please provide me your custom module to test it.
This is a public space.
You can provide me the module by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-03 10:36
Hi @hekep,

As described in the email, the issue is solved in the module.
I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-03 10:36 UTC
Labels: Bug, Order, No change required

**Comment by jedi1983** [comment] 2020-12-02 17:14
@khouloudbelguith i have similar problem and i just noticed that this is a clear solution, i have PS with 1.7.4 could you help me with this problem?, thank you and sorry for bring this up.

**Comment by khouloudbelguith** [comment] 2020-12-03 08:17
Hi @jedi1983,

On this GitHub repository, there is no software support. This is an open-source project.

You can find help

1. on PrestaShop forums https://www.prestashop.com/forums/
2. or by purchasing software support plan from https://www.prestashop.com/en/support

thank you!

**Comment by ValL10** [comment] 2024-07-31 06:35
Hi, 
We've this issue in our customer website. The only payment module we've installed in the shop is Payplug. Any solution yet?

PS : v 1.7.8.3
payplug : v 4.82
