### ISSUE TITLE
Module ps_wirepayment

### ISSUE THREAD

**Issue by oroffini** [PrestaShop/PrestaShop#36943] opened 2024-09-17 15:50 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, on the ps_wirepayment module, during the order and transfer summary, the amount remains at 0.00 even though the amount is clearly displayed (see screen capture 2). Thank you for your help.

### Steps to reproduce

1. Go to Command and add a product
2. validate a cart and select Wirepayment
3.. Screen resume display a table with total amout at zero or my command cost 7,78€

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

PHP 8.1.29

### If your bug is related to a module, specify its name and its version

ps_wirepayment v2.1.3

### Your company or customer's name goes here (if applicable).

L&B SYNERGIE

**Comment by ingridusta** [comment] 2024-09-20 08:41
Hello @oroffini, 

I can not reproduce your ticket with PrestaShop v9.0.x & ps_wirepayment v2.2.0. 

![Capture d’écran 2024-09-20 à 10 39 48](https://github.com/user-attachments/assets/c4e3d87f-6acd-4fee-aab7-05d7a4e426dc)

But on your ticket, you are mentioning screen captures that, I guess, you forgot to upload. Can you add them in comments, please ? 

Thanks.

**Comment by florine2623** [comment] 2024-10-03 12:23
Hello @oroffini ,

Your issue might be about customized products https://github.com/PrestaShop/PrestaShop/issues/10912. The issue is fixed by https://github.com/PrestaShop/PrestaShop/pull/28502.

I have tested the issue with wire payment, I can't reproduce the issue as you can see :

https://github.com/user-attachments/assets/c099069e-3ad7-4da2-868c-98c7ace78d96


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2024-10-03 12:23 UTC
Labels: Bug, FO, Wire payment, Fixed, Module, 9.0.x
