### ISSUE TITLE
[Safari] Catalog price rule selects wrong brand

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#24147] opened 2021-04-21 13:58 UTC
#### Describe the bug

When creating a catalog price rule for a **brand** the JavaScript seems to select the very first available option in the select menu. Which means that if you choose whatever brand that is in the bottom of the select menu when creating the rule, it will be override the next time you edit that rule and forget to **reselect** the correct brand.

**In Safari (14.0.1) :I've tried it locally and 1.7.6.9 seems to work fine. 1.7.7.2 does not.**

#### Expected behavior

The chosen brand for a catalog price rule should remain the same.

#### Steps to Reproduce

1. Create a new catalog price rule
2. Add a brand as a condition group. In a default installation, choose "Studio Design".
3. Save.
4. Go back and edit the price rule.
5. Note that the brand has changed to "Graphic Corner" (or whatever is first in the select below)
6. If you save the price rule, it will change from "Studio Design", which was the intention, to "Graphic Corner", which is wrong.

**Screencast**

See attached screencast.

https://user-images.githubusercontent.com/5259451/115566199-56465a00-a2ba-11eb-8b2c-e38098511e63.mov

#### Additional information

* PrestaShop version: Sometime after 1.7.6.9

**Comment by florine2623** [comment] 2021-04-21 14:54
Hello @dennispw ,

I was able to reproduce the issue with PrestaShop version 1.7.7.3 and develop AND using Safari (Chrome or Firefox OK), so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-04-23 10:02
Hello @dennispw 

I didn't manage to reproduce the issue with PS1.7.6.5 on Safari 14, I only reproduce it with PS1.7.7.2 on Safari 14.
So, it's a regression :wink: 

FYI: When I create a catalog price rule with PS1.7.7.2 on Safari 14 and then I try to edit it, it display **Graphic Corner** :x: 

![image](https://user-images.githubusercontent.com/23308427/115855550-a7c22680-a42b-11eb-8924-d3710d3b0df4.png)

But, when I try to edit on Chrome, it display **Studio Design** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/115855313-6762a880-a42b-11eb-999f-48df24e5d208.png)

Yep, it sounds crazy :sweat_smile: 

Thanks!

**Comment by PierreRambaud** [comment] 2021-04-28 09:26
@NeOMakinG Could you have a check please? :heart:

**Comment by NeOMakinG** [comment] 2021-04-28 15:27
Going to check it asap

**Comment by NeOMakinG** [comment] 2021-04-29 14:05
Fixed here https://github.com/PrestaShop/PrestaShop/pull/24269

**Comment by Progi1984** [comment] 2021-05-05 06:41
Fixed by @NeOMakinG in #24269

**Closed as completed by Progi1984** 2021-05-05 06:41 UTC
Labels: Bug, develop, Minor, BO, Brands, Cart rules, Regression, Fixed, PR available, 1.7.7.2, 1.7.7.3
