### ISSUE TITLE
Password changes after installation is complete

### ISSUE THREAD

**Issue by DevSTG** [PrestaShop/PrestaShop#21615] opened 2020-10-26 14:53 UTC
Right after successfull installation of 1.7.6.8 version my shop was not working because of database connection error.
I found that a '%' in database password was changed to '%%' (database_password) in parameters.php file.

**Comment by SimonGrn** [comment] 2020-10-26 14:57
Hello @DevSTG 
please think about respecting the template. We use it to make sure we have all the informations.

We are aware of this issue, this is a duplicate of #12556, fixed in #19850.

You will be able to get the fix by upgrading to 1.7.8.0 when it will come out.

I close this one.

**Comment by SimonGrn** [comment] 2020-10-26 14:57
Duplicate of #12556

**Closed as completed by SimonGrn** 2020-10-26 14:57 UTC
Labels: Duplicate
