### ISSUE TITLE
Products not displayed in "All shops" context

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#14059] opened 2019-06-03 14:43 UTC
**Describe the bug**
All products created are not displayed when "All shops" context is selected

**To Reproduce**
1. Create a multistore
2. Select a store **other** than store with ID 1
3. Create a product
4. Return to product page
5. Select "All shops" context
6. Previous product is not displayed

**Additionnal information**
PrestaShop version: 1.7.5.2

**Comment by khouloudbelguith** [comment] 2019-06-04 09:23
Hi @idnovate,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9613
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-04 09:23
Duplicate of #9613

**Closed as completed by khouloudbelguith** 2019-06-04 09:23 UTC
Labels: Duplicate
