### ISSUE TITLE
New theme & logo page - Design fixes 

### ISSUE THREAD

**Issue by TristanLDD** [PrestaShop/PrestaShop#13467] opened 2019-04-18 09:01 UTC
- When uploading a PrestaShop theme that contains the theme configurator module, the bloc that links to the module doesn't display correctly :
![Capture d’écran 2019-04-17 à 16 40 56](https://user-images.githubusercontent.com/27484094/56347641-031a0800-61c5-11e9-92f3-28eb7fd53f98.png)
It looked like this in legacy : 
![Capture d’écran 2019-04-18 à 10 41 13](https://user-images.githubusercontent.com/27484094/56348350-8720bf80-61c6-11e9-816d-ebd5f4646dac.png)

- Favicon preview looks like an oval shape instead of a circle: 
![Capture d’écran 2019-04-18 à 10 43 19](https://user-images.githubusercontent.com/27484094/56348491-d666f000-61c6-11e9-97ce-5651e872190a.png)

- Style fixes in: Logo > Main logo / Invoice logo: 
![Capture d’écran 2019-04-18 à 10 55 07](https://user-images.githubusercontent.com/27484094/56349280-7f621a80-61c8-11e9-8c20-23c118c33874.png)

- Add spacing between buttons in "Configure your pages layouts" bloc:
![Capture d’écran 2019-04-18 à 10 56 02](https://user-images.githubusercontent.com/27484094/56349413-ccde8780-61c8-11e9-91ee-626881c85270.png)
Spacing is currently 4px, it should be 15px 

Thank you !

**Comment by tomas862** [comment] 2019-05-07 13:09
Hi @TristanLDD 

I can't really re-create the fist issue "When uploading a PrestaShop theme that contains the theme configurator module, the bloc that links to the module doesn't display correctly". Its mainly due to I need exact steps you did to reproduce it since that message which appears is quite tricky to find.

It would be great if you could provide the zip you tried to install the theme and got this message.

**Comment by TristanLDD** [comment] 2019-05-07 14:22
Hi @Thomas, 

I just sent you by email the zip file you need to reproduce this issue, it's related to the themes developed by PrestaShop. You'll see the message once installed. Sorry for the omission.

**Comment by matks** [comment] 2019-05-20 09:25
1st issue has been transferred to https://github.com/PrestaShop/PrestaShop/issues/13793

Other issues have been fixed in https://github.com/PrestaShop/PrestaShop/pull/13690

**Closed as completed by matks** 2019-05-20 09:25 UTC
Labels: Bug, Minor, Theme & logo, Regression, Fixed, 1.7.6.x
