### ISSUE TITLE
Can't upload product images

### ISSUE THREAD

**Issue by pedroideavity** [PrestaShop/PrestaShop#34595] opened 2023-11-16 12:49 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We're trying to upload a product image in the version 8.1.2 but we're getting a 404 error, the URL being called is 
https://<DOMAIN>/<ADMIN>/index.php/sell/catalog/products-v2/images/add?_token=<TOKEN>

in version 8.0.4 the upload is working find and the URL is:
https://<DOMAIN>/<ADMIN>/index.php/sell/catalog/products/image/upload/<PRODUCT_ID>?_token=<TOKEN>

It seems product ID is missing in the new version

### Expected behavior

Be possible to upload products

### Steps to reproduce

Create a new product and try to upload images

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.25

**Comment by florine2623** [comment] 2023-11-16 13:25
Hello @pedroideavity ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/1113d4e5-ea8b-4800-8547-e6ec510011d6

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing your issue.
Thank you

**Closed as completed by florine2623** 2023-11-16 13:25 UTC
Labels: Bug, Invalid

**Comment by pedroideavity** [comment] 2023-11-16 14:56
I have a multistore; could that be the reason for the error? Please try to create a product pack.
https://prnt.sc/NYj_353UAmPz

**Comment by pedroideavity** [comment] 2023-11-16 17:50
@florine2623
