### ISSUE TITLE
[BUG] SpecificPrice calculated for customer groups instead of default_group_id

### ISSUE THREAD

**Issue by madkot** [PrestaShop/PrestaShop#23219] opened 2021-02-10 19:18 UTC
#### Describe the bug

I'm not sure if it is a bug or just PS logic, but it is not clear at al.
Calculation of specific price rule uses customer default group, but (in my opinion) should use a list of assigned groups to customer instead.

#### Expected behavior

\SpecificPrice::getSpecificPrice should use id list of user assigned groups instead of $id_group (customer default group id).
SpecifixPriceRule should works when is created for an customer group and when the customer is assigned to this group, but this group is not his default group.

#### Steps to Reproduce

1. Assign Customer to two different groups, X - as default, Y - as another one (not default).
2. Go to AdminSpecificPriceRule and prepare rule for customers in created group Y
3. Check if the store has price reductions while logged in to the customer with group Y (Front office)
4. There will be no price reductions.
![obraz](https://user-images.githubusercontent.com/11571787/107562204-ca3ff400-6bdf-11eb-9867-620b3296fe72.png)

#### Additional information

* PrestaShop version: 1.7.* - any version has the same code.
* PHP version: 7.2 //but i think it does not matter

**Comment by madkot** [comment] 2021-02-10 19:45
Ok,  i need glasses :smile: .
Now i see soem explanation of default group

> This group will be the default user group. **The group guest only discount will be applied to that customer.**

In that case, I can only suggest an improvement in the form of adding an option to the store so that the specific prices can work for all groups assigned to the customer.

**Comment by hibatallahAouadni** [comment] 2021-02-11 09:23
Hello @madkot 

I didn't manage to reproduce your issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1zpIu9OZYGSxUwzrs8oQQclpmC78a7VNb/view

Please check and feedback.
Thanks!

**Comment by madkot** [comment] 2021-02-11 15:09
I mean Admin**SpecificPrice**Rule instead of AdminCartRules, and as you see in my last comment.. i know why it looks like below
![obraz](https://user-images.githubusercontent.com/11571787/107654171-aed9f500-6c82-11eb-9b4d-7c958022beef.png)
![obraz](https://user-images.githubusercontent.com/11571787/107654232-c2855b80-6c82-11eb-90be-9a8e728f4d63.png)
current result
![obraz](https://user-images.githubusercontent.com/11571787/107654283-cdd88700-6c82-11eb-8a38-e4e95e413df9.png)
expected result
![obraz](https://user-images.githubusercontent.com/11571787/107654330-dc26a300-6c82-11eb-9041-88522b2bcd4c.png)

this expected result i got after small change in SpecificPrice::getSpecificPrice
exacly i change in SELECT one statement for id_group from:
`id_group ' . self::formatIntInQuery(0, $id_group) . ' `
to
`id_group IN(' . $customerGroupsIn . ') `

where $customerGroupsIn  are ids from Customer::getGroupsStatic($customerId)

**Comment by hibatallahAouadni** [comment] 2021-02-11 16:16
@madkot you mean this page **BO**>**SELL**>**Catalog**>**Catalog Price Rules** ? 

![image](https://user-images.githubusercontent.com/23308427/107664495-c1592c00-6c8c-11eb-9819-fc64fe3f2b2b.png)

---
Edit: if so, could you please check this issue #9977 cause it seems similar to yours.

Thanks!

**Comment by madkot** [comment] 2021-02-24 16:13
@hibatallahAouadni yes, i exactly mean "Catalog Price Rules". Sorry for screenshot in other language.
Yes, issue that you linked is similar.

**Comment by hibatallahAouadni** [comment] 2021-02-24 16:48
Hello @madkot 

Thanks for your feedback.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9977. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-24 16:48
Duplicate of #9977

**Closed as completed by hibatallahAouadni** 2021-02-24 16:48 UTC
Labels: Bug, FO, Duplicate, Discounts, Catalog price rules, Customer groups, 1.7.7.1
