### ISSUE TITLE
Compile assets in Windows is quite impossible

### ISSUE THREAD

**Issue by marsaldev** [PrestaShop/PrestaShop#27875] opened 2022-03-10 10:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It's impossible to complete the compiling assets for developer version of PrestaShop on Windows. 
You have several roadblocks during the journey, first I've encountered is `make` not present by default (what a surprise)

Second critical one is the `NODE_ENV` var, used in the script to build the Classic assets, that is not recognized by `npm`
You can "by-pass" this one installing `win-node-env` module, but after that the compiling fail due `Tether`, specifically, on how `Tether` is imported in [theme.js](https://github.com/PrestaShop/PrestaShop/blob/1ee44a5708ccb4fe0fc29bdb730f6da399380f09/themes/classic/_dev/js/theme.js#L26) and 'exposed' to other components for compiling (I guess). 

![makeassetserror](https://user-images.githubusercontent.com/48283112/157642658-9282b85c-bfea-4078-a5e5-e77c80520773.jpg)

ping FYI @NeOMakinG 

### Expected behavior

Correct compiling? 😊

### Steps to reproduce

_composer_ (installed globally)
_npm v6.14.16_
_node v12.22.10_

Long way
1. Clone PrestaShop repository to your local machine (use 1.7.8.x branch)
2. Run `composer install`
3. Run `make assets ` (you can't if you not have `make` installed)
4. Install `make` or run `/tools/assets/build.sh` or compile assets individually https://devdocs.prestashop.com/1.7/development/compile-assets/#assets-that-need-to-be-compiled
5. When the script try to compile Classic assets you got the first error about `NODE_ENV` var not recognized in `npm`
6. Install `win-node-env` module for `npm` (https://www.npmjs.com/package/win-node-env)
7. Re-try and you get an error about `Tether` path, seems related to the path or how _theme.js_ wants to expose it in the environment (I guess)

"Short" way
1. Clone PrestaShop repository to your local machine (use 1.7.8.x branch)
2. Run `composer install`
3. Try to compile `Classic` assets (`npm run build`)
4. Install `win-node-env` module for `npm`(https://www.npmjs.com/package/win-node-env)
5. Try to compile `Classic` assets (`npm run build`)
6. Error about `Tether` path

### PrestaShop version(s) where the bug happened

develop 1.7.8

### PHP version(s) where the bug happened

7.2,7.3,7.4

**Comment by hibatallahAouadni** [comment] 2022-03-10 13:38
Hello @marsaldev 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27383. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-10 13:38
Duplicate of #27383

**Closed as completed by hibatallahAouadni** 2022-03-10 13:38 UTC
Labels: Bug, Duplicate, Invalid

**Comment by marsaldev** [comment] 2022-03-10 13:45
I don't think it's a real duplicate, I think the issue is similar, but in my case is the `Classic` theme assets that won't be compiled rather than the BO ones 😊

**Comment by NeOMakinG** [comment] 2022-03-10 15:00
@marsaldev At least we linked both issues, we will take care of it, thanks for these information 👍
