### ISSUE TITLE
No weight is displayed in Order summary with combination products

### ISSUE THREAD

**Issue by TaccCZ** [PrestaShop/PrestaShop#19533] opened 2020-06-02 15:22 UTC
#### Describe the bug

If the customer orders a product that has a combination, and it is listed with the increasing weight of the combination, then this weight will not be transferred to the order summary in the administration.

#### Steps to Reproduce

1. Make order with combination (must have weight as picture no.1)
2. Go to admin order, look on weight on order

**Screenshots**
**_Impact on weight:_** 
![image](https://user-images.githubusercontent.com/37780517/83537740-43396880-a4f5-11ea-952e-2e575f011c41.png)

_**No impact on weight: :(**_
![image](https://user-images.githubusercontent.com/37780517/83537838-649a5480-a4f5-11ea-9cf4-2bff33281d18.png)

#### Additional information
This solution not work: https://github.com/PrestaShop/PrestaShop/issues/9603

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-06-02 15:51
Hi @TaccCZ ,
I can't reproduce your issue on PS 1.7.6.5 :
![Capture d’écran 2020-06-02 à 17 47 55](https://user-images.githubusercontent.com/16019289/83540925-40407700-a4f9-11ea-8db4-1eff43b8be02.png)
![Capture d’écran 2020-06-02 à 17 47 32](https://user-images.githubusercontent.com/16019289/83540915-3dde1d00-a4f9-11ea-899f-4b369605efc7.png)

The issue you mentioned is not the same problem as yours.

Can you turn off the overrides ?
In FTP `override` becomes `_override`
Please check and let me know!

**Comment by TaccCZ** [comment] 2020-06-02 16:10
@florine2623 thank you.
I think I found a problem. it's Multistore. I have the weight filled in only in the first e-shop in which the order was made. In the second e-shop, the weight is not filled in combination, but the system took over this zero weight from the second shop, which is wrong.

**Comment by MatShir** [comment] 2020-06-03 13:03
@TaccCZ the order was made on which shop at the end?

**Comment by TaccCZ** [comment] 2020-06-03 14:57
@florine2623 The order was placed at the first e-shop, which had the weight filled for the combinations. But the order took over information from the second e-shop in which there were no weights.

**Comment by MatShir** [comment] 2020-06-04 05:47
@TaccCZ 
I couldn't reproduce, I try:
1. Activate Multistore
2. Create new shops with the same products
3. Add weight the product of the default shop
4. Order the product on the default shop
5. The product of the order has the right weight

Could you provide the more information (on which shop are you editing the product), a video, or more steps to reproduce your bug? 
Thank you

**Comment by TaccCZ** [comment] 2020-06-04 07:13
@MatShir 
Hi, here is video: 
https://www.loom.com/share/a5868127dc8f4f78a9afb325cf9bf024

As you can see, in the first e-shop I have the weight of the combination set to 0.5 kg and in this e-shop I made an order. In the second e-shop, I set the weight to 0.9 kg, and made an order again in the first e-shop. And the weight of 0.9 kg was transferred to the order ... that is, from the second e-shop.

**Comment by florine2623** [comment] 2020-06-05 13:50
@TaccCZ ,

With all the details, I can't reproduce the issue.

Steps I reproduce :
- Have multistore active with 2 shops
- In shop 1 - BO, in product test, add impact on weight for a combination (0.9)
- In shop 2 - BO, in product test, add a different impact on weight for combinations (0.5)
- In shop 1 - FO, place an order of that product
- In shop 1 - BO, check the order, weight is displayed
- Switch to shop 2 - BO, weight in order still is the same

Am I missing something ?

**Comment by TaccCZ** [comment] 2020-06-05 13:56
Thank you,
**at 5 step: In shop 1 - BO, check the order, weight in displayed**
what weight is at order in BO? I have weight from shop 2, (in your case 0.5, but I should have 0.8.)

**Comment by florine2623** [comment] 2020-06-05 15:16
**In Shop 1 :**
In product page :
![Capture d’écran 2020-06-05 à 17 11 27](https://user-images.githubusercontent.com/16019289/83893157-e4236000-a74f-11ea-910c-39291ba99cf5.png)
On order page :
![Capture d’écran 2020-06-05 à 17 12 29](https://user-images.githubusercontent.com/16019289/83893177-e980aa80-a74f-11ea-916f-0d0a33550189.png)
On order detail : 
![Capture d’écran 2020-06-05 à 17 11 22](https://user-images.githubusercontent.com/16019289/83893184-ed143180-a74f-11ea-8171-1a53fb124ff3.png)
**On shop 2 :** 
On product page :
![Capture d’écran 2020-06-05 à 17 14 49](https://user-images.githubusercontent.com/16019289/83893376-28166500-a750-11ea-94b4-16e10dae5c20.png)
No orders made :
![Capture d’écran 2020-06-05 à 17 15 10](https://user-images.githubusercontent.com/16019289/83893406-2ea4dc80-a750-11ea-8e66-80e0cc8293ff.png)

**Comment by florine2623** [comment] 2020-06-25 10:16
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-25 10:16 UTC
Labels: BO, Order, Combinations, No change required, 1.7.6.5
