### ISSUE TITLE
“Add to cart” button on product with attributes - this option doesn't change anything

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30446] opened 2022-11-29 16:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I enable this option `Display the “Add to cart” button when a product has attributes`, I see no impact on the FO.

<img width="398" alt="Screenshot 2022-11-29 at 15 29 16" src="https://user-images.githubusercontent.com/16019289/204584375-d773c1c1-d4d9-4d22-95dc-8a44254e7b2c.png">
<img width="569" alt="Screenshot 2022-11-29 at 15 29 22" src="https://user-images.githubusercontent.com/16019289/204584382-8853b00b-b82a-492e-a552-9361df3aa143.png">

According to the description, I should see a button "Add to cart" in any category page for product with attributes, but that's never the case.

### Expected behavior

The "Add to cart" should be displayed in category pages.
Maybe it is a new feature in Hummingbird theme ?

Or maybe the popin description should be changed

@PrestaShop/product-team do you have any info on this topic ?

As seen with @Progi1984 , it is used blockwishlist module via the variable `add_to_cart_url` and Configuration `PS_ATTRIBUTE_CATEGORY_DISPLAY`

### Steps to reproduce

1. Go to BO > Shop Parameters > Product Settings
2. Enable the option `Display the “Add to cart” button when a product has attributes`
3. Go to FO > In any category pages
4. See that the "Add to cart" button is not displayed on any product

### PrestaShop version(s) where the bug happened

1.7.8.7, 1.7.8.8, 8.0.0, develop

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment] 2022-11-30 10:25
This will have a meaning on hummingbird, we are bringing back the `Add to cart` button on product lists. 👍

Also, this button could already have a meaning on themes that support this, it doesn't do anything on classic only.

**Comment by Hlavtox** [comment] 2023-07-25 21:44
Closing as it's not a bug. This option is used by third party themes and by hummingbird.

**Closed as completed by Hlavtox** 2023-07-25 21:44 UTC
Labels: PM ✔️, Minor, BO, Needs Specs, Product settings, 1.7.7.8, Verified, Invalid
