### ISSUE TITLE
Upgrade from 1.7.7.1 to 1.7.7.2 Error during database upgrade

### ISSUE THREAD

**Issue by forkyboy** [PrestaShop/PrestaShop#23448] opened 2021-02-28 14:35 UTC
Hi

during the Upgrade from 1.7.7.1 to 1.7.7.2 using the 1 click upgrade version  4.12.0
MySQL version: 5.7.33
PHP version: 7.3.26-1

the file upgrade went well, 
but when updating the DB it failed and roll back, this happened on the live PS and the dev PS, i can't quite figure out what happend.

here is the log

`[2021-02-24 09:44:47] Updating database schema...
[2021-02-24 09:44:47] 09:44:47 ERROR     [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it." ["exception" => Doctrine\DBAL\DBALException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it."]
[2021-02-24 09:44:47] In AbstractPlatform.php line 434:
[2021-02-24 09:44:47]                                                                                
[2021-02-24 09:44:47]   Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL57Platfor  
[2021-02-24 09:44:47]   m may not support it.                                                        
[2021-02-24 09:44:47]                                                                                
[2021-02-24 09:44:47] prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] <command>
[2021-02-24 09:44:47] Error during database upgrade. You may need to restore your database.
[2021-02-24 09:44:47] Error upgrading Doctrine schema

im going to go ahead and search for the module creating this "bit"
`

**Comment by hibatallahAouadni** [comment] 2021-03-01 09:34
Hello @forkyboy 

**Please respect and follow the provided template to submit a complete bug report** and fill all the blocks :wink: 

I didn't manage to reproduce your issue with the module **1-Click Upgrade** while upgrading my shop 1.7.7.1 to 1.7.7.2 without any problems, see the attached screen record below:

https://drive.google.com/file/d/1mjcfCss2RoRQURoRu5PNkOfRdhm8BCHq/view

Please check and feedback.
Thanks!

**Comment by forkyboy** [comment] 2021-03-01 12:51
Hello @hibatallahAouadni hibatallahAouadni 


I found out the faulty 3rd party module and corrected the issue.

Question, I now need to redo the upgrade in order to upgrade the DB but now i cant because the files are already updated, 
can you let me know how to relaunch the upgrade from scratch or how to upgrade the DB ?

**Comment by hibatallahAouadni** [comment] 2021-03-01 15:02
Hello @forkyboy 

> how to relaunch the upgrade from scratch or how to upgrade the DB ?

Ping @PrestaShop/prestashop-core-developers could someone please answer @forkyboy questions :pray:

**Comment by atomiix** [comment] 2021-03-01 18:30
@forkyboy you need to rollback and do the upgrade again.

**Comment by hibatallahAouadni** [comment] 2021-03-01 19:18
Hello everyone,

Thanks @atomiix for your quick reply :rocket: 
@forkyboy could you please rollback and upgrade, then check if you still encounter any issue.
Please check and feedback.

Thanks!

**Comment by forkyboy** [comment] 2021-03-01 21:25
@atomiix  thx,

what if i wait for the next upgrade 1.7.7.3 ? will the DB will be upgraded ? or do i need to rollback to 1.7.7.1 before ?

**Comment by hibatallahAouadni** [comment] 2021-03-02 08:26
Hello @forkyboy 

I think @atomiix meant that you need to rollback and upgrade again to 1.7.7.2
@atomiix correct me if I'm wrong :wink: 

Thanks!

**Comment by forkyboy** [comment] 2021-03-02 08:30
the reason im asking is because a lot of work was done since the failled DB upgrade and i rather not rollback and loose all this work,

so if i could wait 1.7.7.3 and upgrade then, that will be good, i just need to know if it will update the DB properly.

**Comment by atomiix** [comment] 2021-03-02 08:36
@forkyboy if you wait for 1.7.7.3, the database upgrade will only migrate from 1.7.7.2 to 1.7.7.3, it won't migrate from 1.7.7.1

**Comment by forkyboy** [comment] 2021-03-02 08:42
@atomiix  thank you,

is there a way to achieve a rollback without loosing all work/order that were done after the failled DB upgrade ?

**Comment by atomiix** [comment] 2021-03-02 09:41
@forkyboy as the purpose of a rollback is to get back to state **before** the upgrade happened, I guess there is no easy way to do so.

**Comment by forkyboy** [comment] 2021-03-02 09:47
What about upgrading the DB manually ? @atomiix   i cant find the changes made with DB in the changelog, can you enlight me on that ?

**Comment by atomiix** [comment] 2021-03-02 10:25
You can see the SQL scripts in `install-dir/upgrade/sql/` but there's also a doctrine migration so you'd have to check if there has been changes in entities between 1.7.7.1 & 1.7.7.2.

**Comment by hibatallahAouadni** [comment] 2021-03-22 08:32
Hello @forkyboy ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-22 08:32 UTC
Labels: Bug, BO, Autoupgrade, No change required, 1.7.7.1
