### ISSUE TITLE
validateOrder() not saving cart carrier in the order

### ISSUE THREAD

**Issue by pxblx** [PrestaShop/PrestaShop#22560] opened 2020-12-23 10:17 UTC
#### Describe the bug

I'm trying to create orders with a script. Everything goes fine until I validate the order with **validateOrder()**. The carrier I assigned in the Cart object is not saving in the resultant order. I have verified that the carrier ID exists and also that it's saved correctly in the Cart object. When I validate the order, the **default carrier** is always assigned instead of the carrier of the cart object.

#### Expected behavior

Create the order with the carrier I assigned in the cart object.

#### Steps to Reproduce

This is the code I'm using:

```
$cart = new Cart();
$cart->id_customer = $customer->id;
$cart->id_address_delivery = $address->id;
$cart->id_address_invoice = $address->id;
$cart->id_lang = 1;
$cart->id_currency = $currency->id;
$cart->id_carrier = 167;
$cart->add();

$payment = Module::getInstanceByName('ps_wirepayment');
$payment->validateOrder($cart->id, 2, $cart->getOrderTotal(), 'Redsys');
```

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.1.32

**Comment by hibatallahAouadni** [comment] 2020-12-23 14:14
Hello @pxblx 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19906. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-23 14:15
Duplicate of #19906

**Closed as completed by hibatallahAouadni** 2020-12-23 14:14 UTC
Labels: Duplicate
