### ISSUE TITLE
Customers and Orders pages "access denied" after one-click upgrade from 1.6

### ISSUE THREAD

**Issue by homecsp** [PrestaShop/PrestaShop#10388] opened 2018-09-12 01:40 UTC
After using one-click upgrade module, everything appears normal in my shop, but I can't view the Customers or Orders pages (all others work fine). Below the "Getting Started..." frame it says "access denied."

Install PS 1.6.0.14 (this is what HostGator, my host provider, installs by default)
login as admin
Complete one-click upgrade module to upgrade to 1.7.4.2
Attempt to access Customers page or the "Orders" page
See "access denied" error

All other pages seem to work fine (addresses, products, invoices, etc).
Note that I can use phpAdmin to check the tables and everything looks fine to my eyes.

PrestaShop version: N/A
PHP version: 5.6

**Comment by dineshbadrukhiya** [comment] 2018-09-12 04:10
Hello @homecsp 
I suggest you to  restore 'ps_access' table from 'clean' DB.

**Comment by homecsp** [comment] 2018-09-12 04:36
Umm, I did this on a clean install. Looking at the 1.6 vs 1.7 ps_access table I see that the structure was drastically changed and 1.7 also now has over 200 more records.
So the adventure now changes to downloading and installing 1.7 manually so that I can get a "clean" v1.7 ps_access table and copy the data over to my target database? That sounds like a lot of work to workaround what should of been a simple upgrade - and it will be very disappointing if that doesn't solve the issue.

**Comment by dineshbadrukhiya** [comment] 2018-09-12 05:48
Run a query on ps_access table > SQL
`INSERT INTO ps_access (id_profile, 	id_authorization_role) SELECT 1, 	id_authorization_role FROM ps_authorization_role;`

**Comment by homecsp** [comment] 2018-09-12 09:02
Well I tried both approaches: I truncated the ps_access table then imported all the records from a new clean 1.7 install - that didn't change anything, so I again truncated the table and ran the insert query as suggested, but no change in behavior.

**Comment by khouloudbelguith** [comment] 2018-09-12 09:35
Hi @homecsp,

This issue is assigned to our developer.
You can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/9513#issuecomment-415011961
Your ticket is a duplicate of #9513, https://github.com/PrestaShop/autoupgrade/issues/100
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-12 09:35
Duplicate of #9513

**Closed as completed by khouloudbelguith** 2018-09-12 09:35 UTC
Labels: Duplicate

**Comment by dineshbadrukhiya** [comment] 2018-09-12 09:55
> 
> 
> Well I tried both approaches: I truncated the ps_access table then imported all the records from a new clean 1.7 install - that didn't change anything, so I again truncated the table and ran the insert query as suggested, but no change in behavior.

May be in ps_authorization_role below data missing, If missing add this fields and run same query again.

181 	        ROLE_MOD_TAB_ADMINORDERS_CREATE
184 	        ROLE_MOD_TAB_ADMINORDERS_DELETE
182 	        ROLE_MOD_TAB_ADMINORDERS_READ
183 	        ROLE_MOD_TAB_ADMINORDERS_UPDATE

73 		ROLE_MOD_TAB_ADMINCUSTOMERS_CREATE
76 		ROLE_MOD_TAB_ADMINCUSTOMERS_DELETE
74 		ROLE_MOD_TAB_ADMINCUSTOMERS_READ
75 		ROLE_MOD_TAB_ADMINCUSTOMERS_UPDATE

Hope it will help you.

**Comment by Claonilton** [comment] 2019-08-07 04:31
**Permission Administrator Full** 
`insert into access ( select 1, id_authorization_role from authorization_role where id_authorization_role not in (select id_authorization_role from access where id_profile=1) order by id_authorization_role )`
