### ISSUE TITLE
Ecotax is automaticaly decrease from 20% when i click on view product on front office 

### ISSUE THREAD

**Issue by Jerome08** [PrestaShop/PrestaShop#13770] opened 2019-05-13 12:26 UTC
**Describe the bug**
In catalog> products
If I edit a product, if I click on the "view" button the product is displayed in the front office, I close the page
and I fall back in the edition of the product but in the top right I see "setting updated" and the eco-participation decreases by 20% (amount of VAT)
While I did not touch the ecotax
As many times as I click on "visualize", as many times that the ecoparticipation will decrease by 20%

**To Reproduce**
1. Go to catalog> products
2. Click on "view"
3. Close the windows of the product (front office)
4. back the edition of this production, the price is modified

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-05-13 12:49
Hi @Jerome08,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/1iz8grIlG_upIPM-ozFcrnaIhYyN1scNR/view
Thanks to check & feedback.

**Comment by Jerome08** [comment] 2019-05-13 13:24
Hello
can you check this video of the problem
http://img.myprestamodules.com/img/screenshots/2019-05-13_11-37-27.mp4

Thanks

**Comment by khouloudbelguith** [comment] 2019-05-13 14:03
@Jerome08, thanks for your feedback.
It is OK in my case
https://drive.google.com/file/d/1vRcrShm_iBU4_Z8d2U6aovzTiYHeXMcI/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Jerome08** [comment] 2019-05-14 06:22
i don't know how to get logs, i found a folder on server called logs
here is some screenshot of it, is that these files?
![Screen Shot 05-14-19 at 08 09 AM](https://user-images.githubusercontent.com/50581985/57674722-50509480-7620-11e9-94d2-57f512789597.PNG)
![Screen Shot 05-14-19 at 08 10 AM](https://user-images.githubusercontent.com/50581985/57674741-58103900-7620-11e9-92d2-d907dd4d67e6.PNG)
![Screen Shot 05-14-19 at 08 13 AM](https://user-images.githubusercontent.com/50581985/57674752-5c3c5680-7620-11e9-8863-d33a46597409.PNG)
![Screen Shot 05-14-19 at 08 18 AM](https://user-images.githubusercontent.com/50581985/57675112-47ac8e00-7621-11e9-9a48-22e53421d75f.PNG)

and i get also this error
![Screen Shot 05-14-19 at 08 19 AM](https://user-images.githubusercontent.com/50581985/57675124-4da26f00-7621-11e9-9e7b-f23e6cb648fd.PNG)

is it usefull for u?
do u need full logs file?

thanks

**Comment by Jerome08** [comment] 2019-05-14 06:24
i realized when i set a price and save it, when i juste refresh my page, it does same, ecotax decrease from 20%
my price included tax also change ...
no need to click on "view" product, a refresh does same

**Comment by khouloudbelguith** [comment] 2019-05-14 07:13
Hi @Jerome08,

About the red alert, it is a different issue reported previously in this ticket: #10934.
Could you please provide me the credentials of your shop to test it.
This is a public space.
You can provide me by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by Jerome08** [comment] 2019-05-14 07:37
Thank you so much
i sent u a mail with all information to connect

Jerome

**Comment by khouloudbelguith** [comment] 2019-05-14 08:16
@Jerome08, thanks!
It is OK now.
I just made some tests on the Taxes page, The Ecotax should have "No tax"
![image](https://user-images.githubusercontent.com/16067358/57681520-c1e01100-7627-11e9-9b31-12180778ac1d.png)
https://drive.google.com/file/d/1Q-IAQHwKSKwRcDH_0vKow97L1TgN7uqz/view

>Issue 1: Multiboutique and ID, I changed the IDs of the shop to phpmyadmin database

You should not edit the database manually, because there are multiple tables related
>Issue 3: Activation of some non-operational taxes

When you use multistore context, you have a list of a checkbox, if you select one, it will be enabled, so you can change the status of the option, 

>if I check them and save them when I refresh the page, they have unchecked again

This is a normal behavior => this checkbox used to enable an option when a shop X is selected.

Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-14 08:16 UTC
Labels: BO, Taxes and Prices, No change required, 1.7.5.2

**Comment by Jerome08** [comment] 2019-05-14 08:45
i'm sorry but it doesn't seem to be different...

i try to change the price of one product, when i refresh the page, ecotax is still decreased
of if i leave the edition and go back to product edition, the price is changed anyway

I will send u video on ur mail

**Comment by khouloudbelguith** [comment] 2019-05-14 08:52
@Jerome08, as I said before, on the Taxes page, The Ecotax should have "No tax".
It is OK now, I just sent you a screen record by Email.
Thanks!

**Comment by Jerome08** [comment] 2019-05-14 09:06
thanks a lot
