### ISSUE TITLE
Module searching in back-office is broken...

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#10760] opened 2018-09-29 00:12 UTC
**Describe the bug**
Read below...

**To Reproduce**
1. Go to 'Module Manager' (and yet again we are confusing people by changing naming of the page and path to it...)
2. Try to search by typing "faceted". You'll not find any module but the thing is that we have ps_facetedsearch installed

You must first click "More" on the list of "Natif" (why not "Native"?) modules to make all modules searchable.

Other thing is that as we search, we should not see every single category of modules and force user to scroll down so much to look if we even have any positive results... 

either it should show us some information about the fact that we indeed have some positive results, or we should have simplier look of this listing after searching

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-01 09:15
Hi @kpodemski,

Thanks for your report.
Here's the PR: #10726 to solve the issue.
Your ticket is a duplicate of #10690
So, I close it.
Thanks !

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 09:15
Duplicate of #10690

**Closed as completed by khouloudbelguith** 2018-10-01 09:15 UTC
Labels: Duplicate
