### ISSUE TITLE
the tax did not appear at the time of the settlement. back office is half in French and English

### ISSUE THREAD

**Issue by startech-france** [PrestaShop/PrestaShop#10324] opened 2018-09-06 16:32 UTC
**Describe the bug**

![capture back office](https://user-images.githubusercontent.com/43042604/45171536-f1ba5780-b202-11e8-910c-94667bcf61e8.png)
![capture paiement](https://user-images.githubusercontent.com/43042604/45171537-f1ba5780-b202-11e8-951b-19897c27793c.PNG)
I want to solve a problem
on my website.

1- I am a professional supplier all my prices are to display free taxes on the site, my at the time of the payment the tax must be added, whereas in my case to me, it is displayed my does not add to the amount total. see the example below + screenshot attached.

Example:
the customer has to pay 272,03 €. the customer must pay the subtotal + delivery charges + taxes, while my site displays the tax but does not ask to pay it.

should display this.

Sub-total € 204.19
Shipping 27,00 €
Total (tax included) € 231.19
Taxes 40,84 €

Total (tax incl.) 272,03 € **<------ missing box.**
(see the capture situation in attachment "Capture payment").

2- click on the general conditions of sales does not appear when paying.
(see the capture situation attached "Capture payment")

3- My back office is half in English and the other half in French, after several attempts to translate it no solutions found. I would like him to be totally in French.
(see the capture situation in attachment "Capture back office").
**To Reproduce**
1. Go to https://www.startech-france.com/

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.31

**Comment by khouloudbelguith** [comment] 2018-09-06 16:41
Hi @startech-france,

Thanks for your report.

First issue:
You need to navigate to your BO => Shop Parameters => Customer settings => Groups Tab
Edit the Price display method for all the groups
![image](https://user-images.githubusercontent.com/16067358/45171965-2084fd80-b204-11e8-904e-038ca0fb8ae4.png)

For the second issue
You need to check the issue with the theme author


Third issue
 You need to navigate to the BO => International => Translations => Please select the language you want to add or update( french) => Click on the "Add or update a language" button


Best regards, Khouloud

**Comment by startech-france** [comment] 2018-09-06 17:22
Hello,
**1- First issue:**
Your solution and good for the payment, it is not good for the display of the product, I would like to display the prices of the product: "excl tax" and at the moment of paying it pays incl tax.
2- second issue:
I will check with the author of the theme (thanks)
3- Third issue
Thank you It's resolved.

Thanks for your help,

**Comment by khouloudbelguith** [comment] 2018-09-07 10:45
Hi @startech-france,

About the first issue, it should be fixed in this ticket: #10013 
It is added to our bug roadmap.
Please follow #10013 
Your ticket is a duplicate of #10013
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-07 10:46
Duplicate of #10013

**Closed as completed by khouloudbelguith** 2018-09-07 10:45 UTC
Labels: Duplicate, 1.7.4.2
