### ISSUE TITLE
Email sending blocked on a non utf8 error returned by swiftmailer on 1.7.7 beta 1

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#19711] opened 2020-06-11 09:33 UTC
#### Describe the bug

A non utf8 error returned by swiftmailer generate raise an exception on email sending that block all email sending.
"Malformed UTF-8 characters, possibly incorrectly encoded on swiftmailer error"
The exception should be catched an not block email sending. The issue is not there in 1.7.6

#### Steps to Reproduce

1.Go to email configuration
2. Choose smtp
3. Fillin a wrong smtp server
4. Send test mail
5. See error in ajax return

The error returned by swiftmailer is : 
errors' => array('Erreur : veuillez vérifier votre configuration', 'Connection could not be established with host smtp.free.frd [php_network_getaddresses: getaddrinfo failed: H�te inconnu. #0]')

The encoding issue is in " H�te inconnu",

Another same issue is there if you choose sending email with standard mail() function :
veuillez vérifier votre configuration', 'Process could not be started [Le chemin d\'acc�s sp�cifi� est introuvable. ]'

* PrestaShop version: 1.7.7 beta 1
* PHP version: 7.2
* Plateform : windows 10

**Comment by florine2623** [comment] 2020-06-11 12:44
Hi @jf-viguier ,
I couldn't reproduce your issue with the same error.
I have the following :
![Capture d’écran 2020-06-11 à 14 43 36](https://user-images.githubusercontent.com/16019289/84386628-f5f28080-abf1-11ea-85a6-269caa627cec.png)

Could you tell me what you put as smtp server ?
Thanks!

**Comment by jf-viguier** [comment] 2020-06-11 15:06
@florine2623 your error message is good but you have to use a french os to have an accentuated character in the error message.
I've used a dummy smtp : smtp.free.fre

**Comment by florine2623** [comment] 2020-06-11 16:00
My shop is in French in the BO :
![Capture d’écran 2020-06-11 à 17 55 41](https://user-images.githubusercontent.com/16019289/84408831-eaf91980-ac0c-11ea-8b65-1967aeda9e99.png)

You might need to take a look on your server side.

**Comment by jf-viguier** [comment] 2020-06-11 17:34
@florine2623 your web server has to be in french, not the backoffice nor your shop.
The error message is returned by the system.

**Comment by florine2623** [comment] 2020-06-19 13:14
Hi @PrestaShop/prestashop-core-developers  ,

I can't test @jf-viguier 's issue.
Could try to reproduce the encoding error ?

Thanks!

**Comment by jf-viguier** [comment] 2020-06-19 14:14
I don't understand, I've reproduced the encoding error : that's described in this issue.

**Comment by matks** [comment] 2020-06-19 14:55
> I don't understand, I've reproduced the encoding error : that's described in this issue.

Now we try to reproduce on our side 😄 because if we cant reproduce, how can we deliver a bugfix and test it indeed fixes the issue

@florine2623 maybe you wanted to ping @PrestaShop/prestashop-core-developers instead ?

**Comment by florine2623** [comment] 2020-06-19 15:39
@matks yes sorry, I misclicked !
As my server is in English, I don't have any accentuated letters to see the encoding error

**Comment by jf-viguier** [comment] 2020-06-23 10:12
Any news here ? Do you plan to fix this before the release ? 
Because this will block email sending for a lot of people.
I've been noticed this same bug on linux too by @nenes25

**Comment by nenes25** [comment] 2020-06-23 14:21
@jf-viguier on my new install i've no error with the config you provide ( use smtp )
But in my case with the php mail function it's not working whereas it was working on ps 1.7.6.5 too
![image](https://user-images.githubusercontent.com/7163132/85415324-7d82ac80-b56d-11ea-9980-d29964c93de2.png)

**Comment by atomiix** [comment] 2020-07-08 11:32
Hi @jf-viguier, despite the fact that there is a problem with non-utf8 symbols in the error message, I'd say that if the email configuration is not good, emails should not be sent. Am I missing something?

The other problem with the `mail()` function is related to the update of Swiftmailer we made for 1.7.7.x that, in fact, [doesn't use the `mail()` function anymore](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Mail.php#L359-L366) but `/usr/sbin/sendmail` which is not available on Windows. That's also what's causing the use of `proc_open` and led to the issue #19957. We'll make the change in the BO labels to better reflect the use of `/usr/sbin/sendmail` instead of `mail()`.

**Comment by jf-viguier** [comment] 2020-07-08 13:58
This ssue is about non-utf8 symbols in the error message.
Thanks for explanations about mail function not supported anymore, the bo should remove this option.
Can we consider that it's a regression ?

**Comment by atomiix** [comment] 2020-07-10 15:04
I've finally been able to reproduce this issue in a Windows environment **but**, unlike you, only in **1.7.6.x**.

In 1.7.7.x I can see the encoding issue "H�te inconnu" directly on the BO but no exception is raised :
<img width="1078" alt="Capture d’écran 2020-07-10 à 15 20 50" src="https://user-images.githubusercontent.com/2168836/87167488-53e7b600-c2cd-11ea-9beb-ecd28a925b1c.png">

Could you maybe do a second check in a fresh 1.7.7?

**Comment by jf-viguier** [comment] 2020-07-10 16:41
@atomiix it was a fresh install of beta1. Do you mean an install from sources 1.7.7 banch ?

**Comment by atomiix** [comment] 2020-07-13 11:24
@jf-viguier not specially, I was just thinking maybe something went wrong during the installation and trying to reinstall could fix the issue. On my side I've tried both 1.7.7.0 beta1 and the 1.7.7.x branch and I wasn't able to get the exception. Only happened on 1.7.6.x

**Comment by khouloudbelguith** [comment] 2020-07-28 10:35
Hi @jf-viguier,

I tried also with PrestaShop 1.7.7.0beta1 and it is ok in my case.
![image](https://user-images.githubusercontent.com/16067358/88655241-c7136980-d0ce-11ea-8314-fdcc90a7333e.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-17 08:26
Hi @jf-viguier,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-08-17 08:26 UTC
Labels: BO, Email, No change required, 1.7.7.0
