### ISSUE TITLE
Webservice offset limit doesn't work anymore

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#25032] opened 2021-06-18 13:45 UTC
#### Describe the bug

Webservice limit function doesn't work (offset is always 0)

#### Expected behavior

If i set limit=[10,5] I should have 5 results since line 10. Now I always have 5 results since line number 0.

#### Steps to Reproduce

1. Enable webservice
2. Try to get these stock_avalaible : api/stock_availables?display=[id,id_product,id_product_attribute]&sort=id_product_attribute_ASC&limit=[0,2]
3. Try to get these stock_avalaible : api/stock_availables?display=[id,id_product,id_product_attribute]&sort=id_product_attribute_ASC&limit=[2,2]
4. See the error, results are the same

#### Additional information

* PrestaShop version: 1.7.6.4, 1.7.8.0 beta1
* PHP version: N/A

**Comment by florine2623** [comment] 2021-06-18 16:14
Hello @Max84 ,

I was able to reproduce the issue with PrestaShop version 1.7.6.x, 1.7.7.x 1.7.8.x and develop, so I can confirm that this behavior is indeed a bug.
Tested with products :
<img width="612" alt="Screenshot 2021-06-18 at 18 13 42" src="https://user-images.githubusercontent.com/16019289/122589823-05a47080-d061-11eb-89cb-6d7b380ef02f.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-06-21 20:04
Hello @Max84 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22760. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-21 20:04
Duplicate of #22760

**Closed as completed by hibatallahAouadni** 2021-06-21 20:04 UTC
Labels: develop, WS, Duplicate, Webservice, 1.7.6.x, 1.7.7.x, 1.7.8.x

**Comment by Max84** [comment] 2021-07-08 14:38
Hi,

Sorry, but I'm not agree. This bug isn't fixed by these other PR. Please reopen it.
I found why. MySQL order by is inconsistent because id_product_attribute can be NULL.

In query, instead of do this "ORDER BY id_product_attribute ASC" you should use "ORDER BY ISNULL(id_product_attribute) ASC".

We'll write the PR.

**Comment by hibatallahAouadni** [comment] 2021-07-08 16:03
Hello @Max84 

> Sorry, but I'm not agree. This bug isn't fixed by these other PR. Please reopen it.

Did you try this fix #22969?

**Comment by Max84** [comment] 2021-07-09 06:42
Hello @hibatallahAouadni 

Yes I did. I think it's not enough because this fix was think for JSON output. XML output has been forgotten.
We'll test to do something equivalent for XML too.

**Comment by Max84** [comment] 2021-07-09 08:00
Just to help anybody who need this, in order to wait the PR.
This can be use as hotfix, with no guarantee. PR isn't done and QA doesn't check it ;)

Into classes/ObjectModel.php, function getWebserviceObjectList near line 1455.
Replace:
`' . ($sql_sort != '' ? $sql_sort : '') . '`
by:
`' . ($sql_sort != '' ? $sql_sort . ', main.`' . bqSQL($this->def['primary']) . '`' : '') . '`
