### ISSUE TITLE
Header's Search Field -- Front Office

### ISSUE THREAD

**Issue by diksha-cedcoss** [PrestaShop/PrestaShop#25133] opened 2021-06-26 10:28 UTC
#### Describe the bug

The search button at the header is not responsive on mobile view it's displaying in half area it should be spread completely at the header to cover the space

#### Expected behavior

The field should display in col-sm-12 to spread it completely at the top of the page (header)

#### Steps to Reproduce

1. Go to the 'PS 1.7.8 shop/website'
2. Click on 'Inspect' to enable mobile view
3. Set it to 'Surface Duo' at 100% fit

**Screenshots**

[
![front_header_search_field](https://user-images.githubusercontent.com/40261082/123510116-50446f00-d697-11eb-8828-2fcd65c11321.png)
](url)

#### Additional information

* PrestaShop version: 1.7.8.0 beta version
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-06-28 10:11
Hello @diksha-cedcoss 

Thanks for testing the 1.7.8.0 beta :tada: 
> Set it to 'Surface Duo' at 100% fit

What do you mean by this?
> The field should display in col-sm-12

You mean that every product should be with col-sm-12 or col-xs-12?
Please check and feedback.

Thanks!

**Comment by matks** [comment] 2021-06-28 12:42
@hibatallahAouadni I think @diksha-cedcoss would like the field to fill horizontally the screen. To almost touch the left and right borders of the screen.

> What do you mean by this?

You can use Google Chrome inspector to simulate how it renders on a Mobile phone. You can choose what phone to simulate.

**Comment by florine2623** [comment] 2021-06-29 09:32
Hello @diksha-cedcoss ,

I reproduced the issue.
<img width="616" alt="Screenshot 2021-06-29 at 11 32 05" src="https://user-images.githubusercontent.com/16019289/123774378-a4389900-d8cd-11eb-96ac-e743be5845b3.png">

Let's check with the UX team !
Please stay tuned.

**Comment by florine2623** [comment] 2021-06-29 09:34
Ping @PrestaShop/ux-team & @NeOMakinG ,
Is this the expected behavior or the field should display in col-sm-12 to spread it completely at the top of the page (header) ?

Thanks!

**Comment by NeOMakinG** [comment] 2021-06-29 09:37
let's wait for the UX advice, but I don't think it's a regression, I think it looks like this since years, could someone test this? :)

**Comment by hibatallahAouadni** [comment] 2021-06-29 10:36
Hello @NeOMakinG 

It's a regression, see the attached screenshot below with PS1.7.7.5 (the same with PS1.7.6.7):

![image](https://user-images.githubusercontent.com/23308427/123783369-93d8ec00-d8d6-11eb-9b40-b3271cbfa9f1.png)

Thanks!

**Comment by prestascott** [comment] 2021-06-29 12:34
Hi everyone,

Thank you @diksha-cedcoss for your request. 
@hibatallahAouadni is right, it's a regression! 

Otherwise, I agree with this. The search bar must be displayed in col-sm-12 to spread it completely at the top of the page :)

**Comment by diksha-cedcoss** [comment] 2021-07-19 13:26
Hello @hibatallahAouadni 

> It's a regression, see the attached screenshot below with PS1.7.7.5 (the same with PS1.7.6.7):

Yes, this is what I mean that CSS is wrongly set

Thank You

**Comment by Progi1984** [comment] 2021-08-25 07:11
Fixed by @NeOMakinG in #25192

**Closed as completed by Progi1984** 2021-08-25 07:11 UTC
Labels: Bug, UX ✔️, Trivial, FO, Regression, Fixed, Front-end, PR available, Responsive, 1.7.8.0
