### ISSUE TITLE
Fatal error when saving SEO & URLS settings in a form different from shop_urls one

### ISSUE THREAD

**Issue by filanico** [PrestaShop/PrestaShop#24543] opened 2021-05-18 10:04 UTC
#### Describe the bug

An exception is raised when saving settings different from shop_urls. 
The script, even if it's not sent the shop_urls form, tries to read those information from the $params parameter

Script and method: 
/modules/ps_accounts/ps_accounts.php/hookActionMetaPageSave($params)

#### Expected behavior

No exception expected during a simple settings saving operation.

#### Steps to Reproduce

1. Go to 'BO > Configuration > Shop Parameters > SEO & Traffic'
2. Click on 'Save button which form IS NOT entitled as "Set shop urls (or something like that) " '
3. See error

**Screenshots**

If
![error_hookActionMetaPageSave](https://user-images.githubusercontent.com/690803/118632897-2e6ee700-b7d1-11eb-81f1-49ad3f487e62.png)
 applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.4

**Comment by filanico** [comment] 2021-05-18 10:08
I solved this way: 
`
			$bodyHttp = [];
  			$bodyHttp['params'] = $params;
				foreach(['domain','domain_ssl'] as $key){
					try{
						$bodyHttp[$key] = params['form_data']['shop_urls'][$key];
					} catch (\Exception $e){
						$bodyHttp[$key] = current(
DB::getInstance()->ExecuteS("SELECT {$key} FROM "._DB_PREFIX_."shop_url")
)[$key];					
					}					
				}
`

**Comment by hibatallahAouadni** [comment] 2021-05-18 11:15
Hello @filanico 

> - PrestaShop version: 1.7.7.8

Really?? I think you mistook, which was your version?

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-18 11:19
Hello again,

In my side, with the newest version 1.7.7.4, I didn't manage to reproduce the issue, see the attached screen record below:

https://www.awesomescreenshot.com/video/3781590?key=9a9eebe1734069f6df9a57374906b6ff

Please check and feedback.
Thanks!

**Comment by filanico** [comment] 2021-05-18 14:34
Sorry i meant v.1.7.8.0

**Comment by hibatallahAouadni** [comment] 2021-05-18 15:17
on which branch you're working 1.7.8.x or develop?

**Comment by hibatallahAouadni** [comment] 2021-06-07 15:14
Hello @filanico ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-07 15:14 UTC
Labels: Bug, BO, Shop parameters, Traffic & SEO, No change required, 1.7.7.4
