### ISSUE TITLE
Prestashop exception

### ISSUE THREAD

**Issue by MarioGamboa** [PrestaShop/PrestaShop#17218] opened 2020-01-16 17:32 UTC
In our webpage, www.mayans.com , when a customer tries to sign in as a visitor to buy a hammock, when they proceed to checkout to order as a guest, they try to fill in all of their information, but when they get to "Addresses", after filling everything out, the click on continue and a "PrestaShop Exception" error page shows up. How can we fix it?

1. Go to www.mayans.com
2. Click on any product
3. Click on "Add to cart"
4. Click on "Proceed to checkout"
5. Click on "Checkout"
6. Fill the contact information for "Personal Information" in "Order as guest" (DO NOT CREATE ACCOUNT)
7. Click on "Continue"
8. Fill the "Addresses" info
9. Click "Continue"
10. See error

![Captura de Pantalla 2020-01-16 a la(s) 11 30 10](https://user-images.githubusercontent.com/59971672/72548116-aa5ec500-3853-11ea-9f89-c9b6a5042935.png)

Latest Prestashop version.

**Comment by khouloudbelguith** [comment] 2020-01-17 09:54
Hi @MarioGamboa,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9888
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-01-17 09:54
Duplicate of #16514

**Closed as completed by khouloudbelguith** 2020-01-17 09:54 UTC
Labels: Duplicate, Checkout

**Comment by khouloudbelguith** [comment] 2020-01-17 09:56
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9888
