### ISSUE TITLE
Proceed button is enabled when quantity of second product change

### ISSUE THREAD

**Issue by mVento3** [PrestaShop/PrestaShop#25662] opened 2021-08-20 07:08 UTC
#### Describe the bug

'Order more than on stock' must be enabled.
Order button is enabled if quantity of one product is bigger than available on stock and we add other product and then change its quantity. Of course after this, we can not proceed anyway, it is visual bug.

#### Expected behavior

After the quantity change of second, or any other product, the order button should be disabled/inactive if one or more products quantity is higher than available on stock.

#### Steps to Reproduce

1. Add one product to cart and change its quantity to higher than available on stock.
2. Add second product and change its quantity to any number, but it is must be available on stock.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/7684287/130193820-2233ba2c-96d3-4003-944e-4b7bd2a2187b.png)
![obraz](https://user-images.githubusercontent.com/7684287/130193855-3f9a70bb-9711-4775-896b-061d6bb59eed.png)

#### Additional information

Presta version: 1.7.7.6
PHP: 7.3.29-1+ubuntu20.04.1+deb.sury.org+1

**Comment by khouloudbelguith** [comment] 2021-08-20 08:59
Hi @mVento3,

We manage to reproduce the issue with PS1777, it is added to our debug roadmap.
Your ticket is a duplicate of #18958
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-08-20 08:59
Duplicate of #18958

**Closed as completed by khouloudbelguith** 2021-08-20 08:59 UTC
Labels: Duplicate
