### ISSUE TITLE
Bug Error in PrestaShopAutoload.php line 152

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#23000] opened 2021-01-26 14:46 UTC
Hello
I'm facing this issue on Prestashop version 1.7.7.1

#### Describe the bug
I imported an existing website to new domain and upgraded it to 1.7.7.1 from 1.7.6.5 and when I try to open Product page FO, I encounter this error **`HTTP ERROR 500`** 

#### Steps to reproduce

1. I imported an existing website to new domain and upgraded it to 1.7.7.1 from 1.7.6.5
2. .....
3. Go to Products page in Front Office
4. See error 500
5. enable debug mode
6. Go to Products page in Front Office
7. See error

**Screenshots**

```
(1/1) ContextErrorException
Warning: Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false)

in Cart.php
at ErrorHandler->handleError(2, 'Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false)', '/var/www/vhosts/xxxx.com/httpdocs/override/classes/Cart.php', 0, array('className' => 'Cart', 'classDir' => '/var/www/vhosts/xxxxx.com/httpdocs/'))
in PrestaShopAutoload.php line 152
at require_once()
in PrestaShopAutoload.php line 152
at PrestaShopAutoload->load('Cart')
in DebugClassLoader.php line 159
at DebugClassLoader->loadClass('Cart')
at spl_autoload_call('Cart')
in FrontController.php line 339
at FrontControllerCore->init()
in ProductController.php line 93
at ProductControllerCore->init()
in Controller.php line 287
at ControllerCore->run()
in Dispatcher.php line 518
at DispatcherCore->dispatch()
in index.php line 28
```

![image](https://user-images.githubusercontent.com/11594433/105860040-759c5680-5fed-11eb-9990-71d509598413.png)

#### Additionnal informations
- Version du logiciel serveur : Apache
- Version de PHP : 7.2.34
- Limite de mémoire : 80128M
- Temps maximal d'exécution : 3000
- Taille max. pour envoi de fichiers : 200M
- Version de PrestaShop : 1.7.7.1

any idea Please

Regards

**Comment by hibatallahAouadni** [comment] 2021-01-26 14:55
Hello @go-sudo 

Where did you encounter this isssue, could you please fill the block **steps to reproduce**.

Thanks!

**Comment by go-sudo** [comment] 2021-01-26 15:04
Hi @hibatallahAouadni 

when I enable the debug mode the website works fine but not he products page **index.php?id_product=32&rewrite=smartx&controller=product** i get this error `Impossible de traiter cette demande via ddddd.com à l'heure actuelle.`
HTTP ERROR 500
So I do enable the debug mode and all the website goes off with message on the previous topic I did disabled all the modules but still facing this issue
Thank you for you help
Regards

**Comment by JBWModules** [comment] 2021-01-26 15:25
You are using a override (override/classes/Cart.php) that seems not compatible with your Prestashop version. Check for the module that installed the override and contact it's developer to fix it

**Comment by hibatallahAouadni** [comment] 2021-01-26 15:27
Hello @go-sudo 

Yep! It seems like you upgraded lately your shop and something goes off like @JBWModules said.
Could you please check all your overrides and feedback.

Thanks!

**Comment by go-sudo** [comment] 2021-01-26 16:19
Hi @JBWModules @hibatallahAouadni 

I did disable all modules on my store one by one and even enabled the option "disable non prestashop module"
![image](https://user-images.githubusercontent.com/11594433/105872318-90c19300-5ffa-11eb-9992-3122a1373ed3.png)
should I remove all modules to see please
Regards

**Comment by JBWModules** [comment] 2021-01-26 16:29
@go-sudo  - This option does not work. You really have to find the modul or remove the override manually

**Comment by hibatallahAouadni** [comment] 2021-01-26 16:30
Hello @go-sudo 

Just fill the steps to reproduce in your issue description, for exemple:

1. upgrade my shop from 17.x.x to 1.7.7.1
2. .....
3. Go to Products page in BO
4. See error

And pelase don't forget any detail, cause those details help us to reproduce your issue :wink: 
@JBWModules thanks for helping :rocket: 

Thanks!

**Comment by go-sudo** [comment] 2021-01-26 17:27
Hello 



I imported an existing website to new domain and upgraded it to 1.7.7.1 from 1.7.6.5
.....
Go to Products page in Front Office 
See error 500 
enable debug mode 
Go to Products page in Front Office 
See error
```
(1/1) ContextErrorException
Warning: Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false)

in Cart.php
at ErrorHandler->handleError(2, 'Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false)', '/var/www/vhosts/xxccccom/httpdocs/override/classes/Cart.php', 0, array('className' => 'Cart', 'classDir' => '/var/www/vhosts/ccccccc.com/httpdocs/'))
in PrestaShopAutoload.php line 152
at require_once()
in PrestaShopAutoload.php line 152
at PrestaShopAutoload->load('Cart')
in DebugClassLoader.php line 159
at DebugClassLoader->loadClass('Cart')
at spl_autoload_call('Cart')
in FrontController.php line 339
at FrontControllerCore->init()
in ProductController.php line 93
at ProductControllerCore->init()
in Controller.php line 287
at ControllerCore->run()
in Dispatcher.php line 518
at DispatcherCore->dispatch()
in index.php line 28
```

**Comment by hibatallahAouadni** [comment] 2021-01-26 20:08
Hello @go-sudo 

Thanks for those details :wink: 
After importing your website to new domain (while it still 1.7.6.5) did you check if you had any problem before the upgrade?

Thanks!

**Comment by go-sudo** [comment] 2021-01-27 11:20
Hello @hibatallahAouadni 

No , because the old website works fine until now with this version 1.7.6.5 and it's a live 

regards

**Comment by hibatallahAouadni** [comment] 2021-01-27 11:34
Hello @go-sudo 

Before upgrading your shop, did you override this method `Cart::getProducts`?
Cause it seems this error has been thrown from this class `override/classes/Cart.php`

Please check and feedback.
Thanks!

**Comment by go-sudo** [comment] 2021-01-27 20:08
Hello @hibatallahAouadni 

No, i did not, do you sugget that i replace that file with a fresh one?
Regards

**Comment by hibatallahAouadni** [comment] 2021-01-28 10:36
Hello @go-sudo 

With fresh install, there's no `Cart.php` under `overrides/classes`.
It means if you don't do it, some module add this class :wink: 

@matks correct me if I'm wrong :sweat_smile: 

Thanks!

**Comment by go-sudo** [comment] 2021-01-28 10:44
Hi @hibatallahAouadni 
So you think I should install a fresh Prestashop and start over to avoid issues?

Regards

**Comment by matks** [comment] 2021-01-28 16:36
@go-sudo It is recommended to disable modules before an upgrade and then re-enable them. Sometimes the modifications applied by the modules on the shop might not be compatible with an upgrade or with the new version.

So one safe strategy would be:
1. Open shop (before upgrade)
2. Disable all modules, remove overrides in `override/classes/` if any
3. Perform the upgrade
4. Enable modules again, one by one (so you can see if one of them creates issues) and put back the overrides

**Comment by go-sudo** [comment] 2021-01-28 16:49
Hi @matks 
Thank you, I did disable the modules one by one but after the upgrade , I think that i will start the migration and follow your instructions
Regards

**Comment by hibatallahAouadni** [comment] 2021-01-28 17:35
Hello,

@matks Thanks for your reply :wink: 
@go-sudo don't forget to feedback :slightly_smiling_face: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:25
Hello @go-sudo ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-17 13:25 UTC
Labels: Bug, FO, No change required, Shopping carts FO, 1.7.7.1
