### ISSUE TITLE
ImageMagick Optimization Image

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#28849] opened 2022-06-24 15:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

automatic optimization of photos added to the store

### Describe the solution you'd like

Cooperation with ImageMagick, after adding each photo to the store is optimized to the set value.

### Additional context

PrestaShop should automatically optimize the added photos to small sizes, many sellers do not do this, which causes pages to load for a long time. In my opinion, such a function should be built into prestashop not with the help of an additional module. Unless a free module is like that.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment] 2022-06-24 15:21
Hello @eveneme ,

Your issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/21101
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by florine2623** [comment] 2022-06-24 15:21
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/21101

**Closed as completed** 2022-06-24 15:22 UTC
Labels: Feature, Duplicate
