### ISSUE TITLE
Missing languages selector over each textarea when there are only one language active

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#18213] opened 2020-03-19 09:31 UTC
hi
today I've found a new bug 
The languages selector over each textarea, present in items like manufacturers or categories or cms is missing when there are installed more than one languages but there is only one language enable.
instead for the selection of the text input fields are present
bye

**Screenshots**

![1](https://user-images.githubusercontent.com/653230/77051680-fd780400-69cb-11ea-944f-908e0f14ef6b.png)
![2](https://user-images.githubusercontent.com/653230/77051685-fe109a80-69cb-11ea-8a16-d8e60aaf702f.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-19 09:58
Hi @maofree,

Your ticket is a duplicate of #16626
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-19 09:58
Duplicate of #16626

**Closed as completed by khouloudbelguith** 2020-03-19 09:58 UTC
Labels: Duplicate
