### ISSUE TITLE
[1.7.6.1] Erreur 500: Panier avec adresse supprimée

### ISSUE THREAD

**Issue by webrdinfo** [PrestaShop/PrestaShop#16470] opened 2019-11-20 12:21 UTC
Prestashop 1.7.6.1

1. Créer un panier, avec une adresse enregistrée
2. Supprimer l'adresse de votre compte
3. Erreur 500 en BO sur la page des paniers, ainsi que sur la page d'édition du client en question

request.INFO: Matched route "admin_customers_view". {"route":"admin_customers_view","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\Sell\\Customer\\CustomerController::viewAction","_legacy_controller":"AdminCustomers","_legacy_link":"AdminCustomers:viewcustomer","_legacy_parameters":{"id_customer":"customerId"},"customerId":"175966","_route":"admin_customers_view"},"request_uri":"...index.php/sell/customers/175966/view?_token=tN6ajtBZU9Pz9xZNDVtHjj_IVupfO51aD92iCK1zMfE","method":"GET"} []

request.CRITICAL: Uncaught PHP Exception PrestaShopException: "Invalid address #331217" at ...classes/Address.php line 517 {"exception":"[object] (PrestaShopException(code: 0): Invalid address #331217 at /data/serveur/site/web-rd-info.fr/amgpro/prod/racine/dev/classes/Address.php:517)"} []

**Comment by khouloudbelguith** [comment] 2019-11-20 13:21
Hi @webrdinfo,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/1-qiZrC_14IoTMrklfP12XOZwIf4txhFk/view
This issue is fixed previously with this PR: https://github.com/PrestaShop/PrestaShop/pull/11416
as reported here: https://github.com/PrestaShop/PrestaShop/issues/9782

Thanks to check & feedback.

**Comment by webrdinfo** [comment] 2019-11-20 13:33
Je n'avais pas ce fix sur ma version: https://github.com/tomlev/PrestaShop/commit/3ab074071ab655a79785fd39446668d7ca44ce08#diff-9ce4b21a6757aaa5b15bb51742d096c4

J'ai corrigé, merci

**Comment by khouloudbelguith** [comment] 2019-12-20 07:51
Hi @webrdinfo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-20 07:51 UTC
Labels: Bug, BO, Shopping carts, No change required, 1.7.6.1
