### ISSUE TITLE
BO - An exception is displayed when doing a rollback 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27948] opened 2022-03-17 15:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed when doing the rollback
![image](https://user-images.githubusercontent.com/16067358/158831476-5a696e7f-d6ab-4ed7-80e3-1734a7734101.png)
Reproduced with those issues:
1. Rollback from 1785 to 1778
2. Rollback from 1785 to 1784
3. Rollback from 1778 to 1752
4. Rollback from 1785 to 1752

### Steps to reproduce

1. Install PS1752/PS1778/PS1784
2. Install this module 
[issuelogs.zip](https://github.com/PrestaShop/PrestaShop/files/8287428/issuelogs.zip): provided from this issue: https://github.com/PrestaShop/PrestaShop/issues/27887#issue-1166137545
3. Upgrade to Major version
4. Make a rollback
5. See error 

At this step: the shop is not working!

### PrestaShop version(s) where the bug happened

1.7.7.8

### If your bug is related to a module, specify its name and its version

1-click upgrade v4.14.0

**Comment by Quetzacoalt91** [comment] 2024-05-13 16:03
Unfortunately, I have been unable to reproduce the error.
Tried with these scenarios:
* 1.7.7.8 -> Upgrade -> 1.7.8.11 -> Upgrade -> 8.1.5 -> Rollback -> 1.7.7.8 (Default prefix)
* 1.7.7.8 -> Upgrade -> 1.7.8.11 -> Upgrade -> 8.1.5 -> Rollback -> 1.7.7.8 (Custom prefix)
* 1.7.5.1 -> Upgrade -> 1.7.8.11 -> Upgrade -> 8.1.5 -> Rollback -> 1.7.7.8 (Custom prefix)

@AureRita can you please try on your side?

**Comment by AureRita** [comment] 2024-07-15 09:57
Hi @Quetzacoalt91 

Currently I followed the issue : install 1.7.7.8, install the module, install autoupgrade, Upgrade with major channel (8.1.7) and rollback and didn't reproduce it. I think we can close it.

**Closed as completed by AureRita** 2024-07-15 09:57 UTC
Labels: Bug, Minor, BO, TBR, Modules, Autoupgrade, Verified, Module, 8.1.x, Backlog SUE
