### ISSUE TITLE
Loading Time Issue -Bug-

### ISSUE THREAD

**Issue by ramibak** [PrestaShop/PrestaShop#13775] opened 2019-05-13 13:25 UTC
Hello There , i have prestashop version 1.7.4.3 
im using a module for importing from aliexpress , and mywebsite is hosted by dedicated server which have a high storage and high memory , now after finishing importing from aliexpress , i try to refresh the products page to check that everything is okay , the loading time is more than 1 minutes sometimes , and other times it shows me 503 server temporary unavailable , i checked the server log it shows error 503 
My website has more than 400 category , and till now i have around 18000 products , 

Any Help Please 
@khouloudbelguith

**Comment by khouloudbelguith** [comment] 2019-05-13 13:42
Hi @ramibak,

In your php.ini file, Try to increase:
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit = 512M

Some issues related added to our bug roadmap: 

- https://github.com/PrestaShop/PrestaShop/issues/9809
- https://github.com/PrestaShop/PrestaShop/issues/13698

Thanks to check & feedback

**Comment by ramibak** [comment] 2019-05-13 14:00
thanks for your reply khouloud 
already did that , 2 weeks ago , and here is the picture of what i did , and still the same , you feel like the backoffice is too heavy when using the importer , even another user cant use it easily
@khouloudbelguith 


![kk1](https://user-images.githubusercontent.com/50453887/57627243-4dae5a80-75a0-11e9-8b97-2577896040e5.PNG)
![kk2](https://user-images.githubusercontent.com/50453887/57627245-4dae5a80-75a0-11e9-9908-d77fc7e48e58.PNG)
![kk3](https://user-images.githubusercontent.com/50453887/57627247-4dae5a80-75a0-11e9-90ea-88232f51f0e7.PNG)

**Comment by khouloudbelguith** [comment] 2019-05-13 14:06
@ramibak, for your information, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to downgrade your version PHP, check & feedback.

**Comment by ramibak** [comment] 2019-05-13 14:32
@khouloudbelguith  ,
i have this version installed on the server , already choosed it , and still the same issue , heavy backoffice and some 503 error shows sometime .
waiting for your reply ,
Thank you @khouloudbelguith  & Ramadanek mabrouk 

![kk4](https://user-images.githubusercontent.com/50453887/57629569-ac75d300-75a4-11e9-8016-e9abbf7819c2.PNG)

**Comment by khouloudbelguith** [comment] 2019-05-13 14:50
@ramibak, Thanks for your feedback.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ramibak** [comment] 2019-05-14 11:22
host : 1&1 IONOS Dedicated server
Server Sertup & configuration : here is some information 

Hostname | BCD3924.online-server.cloud
-- | --
IP address | 74.208.239.218
OS | ‪CentOS Linux 7.6.1810 (Core)‬
Product | Plesk Onyx Version 17.8.11 Update #53, last updated on May 12, 2019 07:32 PM


CPU | Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz (24 core(s))
-- | --
Version | Plesk Onyx v17.8.11_build1708180301.19 os_CentOS 7
OS | CentOS Linux 7.6.1810 (Core)


Server information Linux #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64

Server software version: Apache

PHP version: 7.2.18

Memory limit: 6000M

Max execution time: 600

Upload Max File size: 20M


info_outline Database information
MySQL version: 5.5.60-MariaDB

MySQL server: localhost

MySQL name: db759899424

MySQL user: dbo759899424

Tables prefix: lpp2_

MySQL engine: InnoDB

MySQL driver: DbPDO

****ALSO I TURNED DEBUG MODE AND IT GIVES ME THIS TYPES OF ERRORS ON THE MAIN PAGE****

(1/1) ContextErrorExceptionWarning: count(): Parameter must be an array or an object that implements Countable
--
in specialproductclass.php line 175
at SpecialProductClass->getSpecialProductList('30')in wtspecials.php line 248
at WtSpecials->callGetProductList()in wtspecials.php line 262
at WtSpecials->hookdisplayTopHome(array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 924
at HookCore::coreCallHook(object(WtSpecials), 'hookdisplayTopHome', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' =>object(Cart), 'altern' => 1))in Hook.php line 328
at HookCore::callHookOn(object(WtSpecials), 'displayTopHome', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' =>object(Cart), 'altern' => 1))in Hook.php line 860
at HookCore::exec('displayTopHome', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1), null)in smarty.config.inc.php line 165
at smartyHook(array('h' => 'displayTopHome'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayTopHome'), object(SmartyDevTemplate)))in 50c237d3f8d2047fbbaa477506d3848dd0557d09_2.file.header.tpl.php line 194
at Block_3192138735cdaa3fa43a699_60574062->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_3192138735cdaa3fa43a699_60574062), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_3192138735cdaa3fa43a699_60574062))in smarty_internal_runtime_inheritance.php line 157
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_3192138735cdaa3fa43a699_60574062', 'header_top')in 50c237d3f8d2047fbbaa477506d3848dd0557d09_2.file.header.tpl.php line 47
at content_5cdaa3fa442962_88860147(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('file:_partials/header.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 0, false)in fd20ef73a41edc9c4debb9704d0622fb29dfa7a4_2.file.layout-both-columns.tpl.php line 192
at Block_4869093765cdaa3fa3e9fc8_73582724->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_4869093765cdaa3fa3e9fc8_73582724), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_4869093765cdaa3fa3e9fc8_73582724))in smarty_internal_runtime_inheritance.php line 157
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_4869093765cdaa3fa3e9fc8_73582724', 'header')in fd20ef73a41edc9c4debb9704d0622fb29dfa7a4_2.file.layout-both-columns.tpl.php line 62
at content_5cdaa3fa3f7888_02461143(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in e3a20cad82c27d59ef1c5858cdf9e734a9bcf0a0_2.file.layout-full-width.tpl.php line 42
at content_5cdaa3fa3dea91_40501218(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in 0a64266c25867247003875134fc83c9bd172e4f8_2.file.page.tpl.php line 33
at content_5cdaa48056a471_43411139(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('page.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'page.tpl')in 11ca9c65a40fe0dc9f12f6cd375ea0a70b51819f_2.file.index.tpl.php line 33
at content_5cdaa48055bec0_92372866(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('index.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 41
at SmartyDev->fetch('index.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 679
at FrontControllerCore->smartyOutputContent('index.tpl')in FrontController.php line 663
at FrontControllerCore->display()in Controller.php line 275
at ControllerCore->run()in Dispatcher.php line 428
at DispatcherCore->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment] 2019-05-14 11:51
@ramibak, did you use any module named `SpecialProduct` or `wtspecials`?
These classes `specialproductclass.php` `wtspecials.php` are provided by which module?
Thanks!

**Comment by ramibak** [comment] 2019-05-14 11:56
@khouloudbelguith 
hello khouloud , yes its one of the modules theme , ihave just disabled it now , is there anyway to give you my server credentials , to check your self , because im already 2 hours looking for apache log and php log i didnt find them 
i found some file error log located in Home directory/logs
thank you so much for your support appreciate it :)

[error_log.zip](https://github.com/PrestaShop/PrestaShop/files/3177457/error_log.zip)

**Comment by ramibak** [comment] 2019-05-14 11:57
i tried to refresh my main page once again after disabling the WT_specials , i get this report now 


(1/1) ContextErrorExceptionWarning: count(): Parameter must be an array or an object that implements Countable
--
in 95feb60f69e9bec7678e4b0335e66fc750a08da2_2.module.wtcategoryfeatureviewstem.php line 50
at content_5cdaaced1e44d5_40943559(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 41
at SmartyDevTemplateCore->fetch()in Module.php line 2282
at ModuleCore->fetch('module:wtcategoryfeature/views/templates/hook/wtcategoryfeature.tpl')in wtcategoryfeature.php line 209
at WtCategoryFeature->renderWidget('displayBottomHome', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 929
at HookCore::coreRenderWidget(object(WtCategoryFeature), 'displayBottomHome', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 881
at HookCore::exec('displayBottomHome', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1), null)in smarty.config.inc.php line 165
at smartyHook(array('h' => 'displayBottomHome'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyHook', array(array('h' => 'displayBottomHome'), object(SmartyDevTemplate)))in 1a59646a86cc3f0e003834a91f4c2328e9aab504_2.file.footer.tpl.php line 28
at content_5cdaaced1921a3_14568770(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('file:_partials/footer.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 0, false)in fd20ef73a41edc9c4debb9704d0622fb29dfa7a4_2.file.layout-both-columns.tpl.php line 333
at Block_19289877905cdaaa8a03db95_02543185->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 247
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_19289877905cdaaa8a03db95_02543185), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 183
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_19289877905cdaaa8a03db95_02543185))in smarty_internal_runtime_inheritance.php line 157
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_19289877905cdaaa8a03db95_02543185', 'footer')in fd20ef73a41edc9c4debb9704d0622fb29dfa7a4_2.file.layout-both-columns.tpl.php line 104
at content_5cdaaa8a0410d5_34445807(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-both-columns.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-both-columns.tpl')in e3a20cad82c27d59ef1c5858cdf9e734a9bcf0a0_2.file.layout-full-width.tpl.php line 42
at content_5cdaaa8a028298_28899064(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('layouts/layout-full-width.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'layouts/layout-full-width.tpl')in 0a64266c25867247003875134fc83c9bd172e4f8_2.file.page.tpl.php line 33
at content_5cdaacebd59561_58385037(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
at Smarty_Internal_Template->_subTemplateRender('page.tpl', null, 'layouts/layout-full-width.tpl', 0, 31536000, array(), 2, false, null, null)in smarty_internal_runtime_inheritance.php line 127
at Smarty_Internal_Runtime_Inheritance->endChild(object(SmartyDevTemplate), 'page.tpl')in 11ca9c65a40fe0dc9f12f6cd375ea0a70b51819f_2.file.index.tpl.php line 33
at content_5cdaacebd48534_44545837(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('index.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 41
at SmartyDev->fetch('index.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 679
at FrontControllerCore->smartyOutputContent('index.tpl')in FrontController.php line 663
at FrontControllerCore->display()in Controller.php line 275
at ControllerCore->run()in Dispatcher.php line 428
at DispatcherCore->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment] 2019-05-14 11:59
@ramibak, you have also an issue with the `wtcategoryfeatureviewstem` module.
You should contact the module author about this issue they are the only ones to help you with it.
You have also, this error
`[Tue May 14 07:10:15.464801 2019] [fcgid:warn] [pid 326160:tid 139922551846656] [client 79.177.97.133:51928] mod_fcgid: stderr: PHP Warning:  include(/var/www/vhosts/gulfiz.com/httpdocs/Gulfiz/modules/aliexpressapi/config/config.inc.php): failed to open stream: No such file or directory in /var/www/vhosts/gulfiz.com/httpdocs/Gulfiz/modules/aliexpressapi/aliexpressapi.php on line 1284, referer: https://gulfiz.com/8jkvyhkfgnfsrjdl/index.php?controller=AdminModules&token=72ad4c2eadcb5ca5aa5bf61b228c2ab5&configure=aliexpressapi`, it is related to your module aliexpress, you need to contact the module author about this issue.
Thanks to check & feedback.

**Comment by ramibak** [comment] 2019-05-14 12:14
@khouloudbelguith  is these modules the reason of heavy loading time ?
it keeps giving me this sometimees not all the time , 3 users working on the website , so when other user is importing , and other try to navigate , probably will get 503 server unavailabe at the moment , 

the module author of ALIEXPRESS api , replied now , that its not error , its only a warning but there is no error in the module 
thank you @khouloudbelguith 
![503](https://user-images.githubusercontent.com/50453887/57696889-9f1b2000-765a-11e9-94fd-365bccae8f39.png)

**Comment by khouloudbelguith** [comment] 2019-05-14 12:16
@ramibak, Could you please provide me the credentials of your shop to test it.
This is a public space.
You can provide me by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by ramibak** [comment] 2019-05-14 12:27
sent to your email already , thanks alot @khouloudbelguith  for your help

**Comment by khouloudbelguith** [comment] 2019-05-14 12:29
@ramibak, I did not receive any mail yet.
Thanks to check & feedback.

**Comment by ramibak** [comment] 2019-05-14 12:30
@khouloudbelguith  
check in spams maybe , already sent it from ramibakfinadvisor@gmail.com thank you

**Comment by khouloudbelguith** [comment] 2019-05-14 12:37
@ramibak, I just sent you an email.
Thanks!

**Comment by ramibak** [comment] 2019-05-18 22:34
@khouloudbelguith  hello khouloud hope your fine ,

regarding the loading after importing products by the module , i got these problem in the server log 

"

Error | 79.177.97.133 |   | (32)Broken pipe: AH02550: Failed to flush CGI output to client, referer: https://gulfiz.com/8jkvyhkfgnfsrjdl/index.php/security/compromised?uri=https%253A%252F%252Fgulfiz.com%252F8jkvyhkfgnfsrjdl%252Findex.php%252Fproduct%252Fcatalog%253F&_token=N2NjsCZasAQUDXz3OAKp2cYl3zNl4QuIceeytURrwhk |   |   |   | Apache error
-- | -- | -- | -- | -- | -- | -- | --


"

after importing products and trying to refresh the products page it takes around 6 minutes , i tried to check by google chrome developer mode used network tab , there was in issue in this field "https://gulfiz.com/8jkvyhkfgnfsrjdl/index.php/product/catalog?_token=N2NjsCZasAQUDXz3OAKp2cYl3zNl4QuIceeytURrwhk" this field took 6 min to load !
waiting for your response , thank you so much :)

**Comment by khouloudbelguith** [comment] 2019-05-20 13:29
Hi @ramibak,

I checked your shop again.
It is the same issue as before
![image](https://user-images.githubusercontent.com/16067358/58025083-91a6df80-7b0b-11e9-888a-39f93659eb1d.png)
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-20 14:26
@ramibak,

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
the phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-27 10:25
Hi @ramibak,

as written in your last email, the issue is related to your module aliexpress.
So, the issue is not a PrestaShop's core bug.

I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-27 10:25 UTC
Labels: BO, No change required, 1.7.4.3
