### ISSUE TITLE
product.tpl fixing itemprop availability OutOfStock

### ISSUE THREAD

**Issue by jferran95** [PrestaShop/PrestaShop#13832] opened 2019-05-17 09:06 UTC
Through tool Google Search Console, errors are detected in file: product.tpl
The issue is field not found: itemprop="availability"
According to documentation: https://developers.google.com/search/docs/data-types/product
Field availability is mandatory.

The fix done in line:
https://github.com/PrestaShop/PrestaShop/blob/70d12a5ffbd9f1123e76cded1be8d2f78d5f015c/themes/default-bootstrap/product.tpl#L262

See before changes:
`{if $product->quantity > 0}<link itemprop="availability" href="https://schema.org/InStock"/>{/if}`

See after changes:
`{if $product->quantity > 0}<link itemprop="availability" href="https://schema.org/InStock"/>{else}<link itemprop="availability" href="https://schema.org/OutOfStock"/>{/if}`

Take into consideration this was fixed for version 1.6.1.x.
Similar fix might be applicable to other branches.

**Comment by khouloudbelguith** [comment] 2019-05-17 09:19
Hi @jferran95,

With PS1.7, we use another theme by default is classic.
According to the Google Search Console, we manage to reproduce another issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/12687
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-17 07:47
Hi @jferran95,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-17 07:47 UTC
Labels: No change required
