### ISSUE TITLE
PSAddons module throwing errors after a fresh install

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/PrestaShop#13675] opened 2019-05-06 08:39 UTC
**Describe the bug**
After a fresh install (country: FR, language: EN), the PSAddons module displays an error in the BO.
Full error message :
```
Notice on line 227 in file /var/www/html/prestashop/modules/psaddonsconnect/psaddonsconnect.php
[8] Undefined variable: advice

Notice on line 228 in file /var/www/html/prestashop/modules/psaddonsconnect/psaddonsconnect.php
[8] Undefined variable: link_advice
```

**To Reproduce**
1. Install PrestaShop 1.7.6.x (country: FR, language: EN)
2. Go to the BO
3. Close the Welcome module

**Screenshots**
![image](https://user-images.githubusercontent.com/49909275/57214603-ccc4f100-6fea-11e9-9431-57e9376840cd.png)

**Additional information**
PrestaShop version: 1.7.6.x
PHP version: 7.1

**Comment by marionf** [comment] 2019-05-06 15:13
@MatShir Do you think it's necessary to keep the two issues (this one and #13438) ? Or we can close one of the two ?

**Comment by MatShir** [comment] 2019-05-06 15:18
Edit: The issues isn't the same. We should keep them to be sur they are fixed.

**Comment by khouloudbelguith** [comment] 2019-05-07 07:48
Hi @marionf,

This issue is duplicate of https://github.com/PrestaShop/PrestaShop/issues/10934
Thanks!

**Closed as completed** 2019-05-07 08:01 UTC
Labels: Bug, Critical, BO, Duplicate, Modules, 1.7.5.1, 1.7.6.x, psaddonsconnect

**Comment by MouRadB8** [comment] 2023-04-15 11:49
i have a problem like this

**Comment by intraordinaire** [comment] 2023-04-26 08:44
Hello @MouRadB8 

Thanks for your message.

In order to help us investigate, can you provide us more information about your error ? 
Module version ? PrestaShop version ? Eventually, screenshots or logs ?
