### ISSUE TITLE
Wrong error message in logs

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27838] opened 2022-03-04 14:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The problem is the following error message:
`Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart`

The PHP test performed to display this message does not match this one.

### Expected behavior

Change the display condition of the message to better match the text

### Steps to reproduce

You will find below the steps to display the error messages in the backoffice.

1. Have 2 tabs open on the "shopping cart ?action=show" page (with items)
![image](https://user-images.githubusercontent.com/99792614/156778253-267f0871-9292-41bd-98eb-23dbdf60facf.png)

1. Launch and complete the order on one of the tabs
![image](https://user-images.githubusercontent.com/99792614/156778412-6695980c-ca90-4541-9580-6268b0ce3b3f.png)

1. Refresh the other tab still active on the old cart 

1. Go to the back-office in "Advanced settings --> Logs" and the following error message should appear 
![image](https://user-images.githubusercontent.com/99792614/156778610-89571d13-87a4-45d4-9dc9-2459b3dd43fa.png)

### PrestaShop version(s) where the bug happened

All

### PHP version(s) where the bug happened

All

**Comment by hibatallahAouadni** [comment] 2022-03-04 16:16
Hello @tlgsoledis 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9866. 
Thanks for your PR :rocket: Please subscribe and link your PR to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-03-04 16:16
Duplicate of #9866

**Closed as completed by hibatallahAouadni** 2022-03-04 16:16 UTC
Labels: Bug, Duplicate, PR available, Invalid
