### ISSUE TITLE
Errors ocurred: error while importing XLSX file

### ISSUE THREAD

**Issue by krodiak** [PrestaShop/PrestaShop#10329] opened 2018-09-07 01:43 UTC
I've been trying to import this file and it just stops saying an error ocurred: error.

I am linking thefile for reproducing the error.
http://endysis.com.mx/combs_upload_endysis.xlsx

SOmetimes it happens at the beginning and some times it just freezes.

**Comment by khouloudbelguith** [comment] 2018-09-07 08:43
Hi @krodiak,

The issue is about the "reference" column, it is too long, it should have 32 chars or less.
But it is an issue should be fixed.
I manage to reproduce the issue with the last version 1.7.4.2.
If we try to import a combination file which has a reference more than 32 chars => the import is corrupted without any information.
![image](https://user-images.githubusercontent.com/16067358/45208438-deeb6580-b28a-11e8-90c1-692dd1c7cc65.png)
We will see how to fix it.
Related to : #9955

Best regards, Khouloud

**Comment by marionf** [comment] 2019-05-15 12:35
@khouloudbelguith Could you try to reproduce it with 1.7.6.0 ?

**Comment by khouloudbelguith** [comment] 2019-05-15 12:43
Hi @marionf,

Yes, the issue is fixed in the PS1.7.6.beta1.
![image](https://user-images.githubusercontent.com/16067358/57776415-5aa18a00-7717-11e9-8428-55b3c84b8ff8.png)
I close the issue.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-15 12:43 UTC
Labels: Bug, Minor, BO, Import / Export, Fixed, 1.7.4.2
