### ISSUE TITLE
HelperList missing token in 1.7.7.x

### ISSUE THREAD

**Issue by javierinnova** [PrestaShop/PrestaShop#23801] opened 2021-03-29 06:37 UTC
#### Describe the bug

When creating a new HelperList, on any action (pagination, search, ...) the backoffice shows the invalid token page. It seems that on template helpers/list/list_footer.tpl the $token variable is empty, unless you specify on helper->tpl_vars

#### Expected behavior

The normal function on helperlist, as it works on any previous version of 1.7 and 1.6, without specifying the token twice

#### Steps to Reproduce

1. In a module getContent() method, create a sample helper list:
```
$helper = new HelperList();
...
return $helper->generateList($items, $fields_list);
```
2. On pagination, the backoffice shows the invalid token page
3. Add $helper->tpl_vars['token'] = $helper->token; before the return:
```
$helper = new HelperList();
...
$helper->tpl_vars['token'] = $helper->token;
return $helper->generateList($items, $fields_list);
```
4. On pagination, the backoffice works as regular.

**Screenshots**

Without $helper->tpl_vars['token']

![Desktop screensh](https://user-images.githubusercontent.com/81551288/112796186-ebfb1a80-9069-11eb-9bca-c2f2c9289610.png)

With $helper->tpl_vars['token']

![Desktop screensh (1)](https://user-images.githubusercontent.com/81551288/112796197-ef8ea180-9069-11eb-94f8-a4e4a012e032.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2021-03-29 16:33
Hello @javierinnova 

Could you please provide a module to test the issue or just name a module that I can apply the provided **steps to reproduce** on it.
Please attach a module and feedback.

Thanks!

**Comment by florine2623** [comment] 2021-04-16 09:22
Hello @javierinnova ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-04-16 09:22 UTC
Labels: Bug, CO, Modules, No change required, 1.7.7.0
