### ISSUE TITLE
Broken Notification Box for German Shop

### ISSUE THREAD

**Issue by david-colombo** [PrestaShop/PrestaShop#13160] opened 2019-04-03 10:59 UTC
My Prestashop system is in German and it seems like this broke one of the notification boxes.

It shows "Notice! Aktion Uninstall beim Modul psgdpr war ."
But it should show "Notice! Aktion Uninstall beim Modul psgdpr war erfolgreich."

(Also I'm not sure why it shows even  "Notice!" and "Uninstall" in this Notification or "disable mobile" on the module page if Prestashop is already translated 100% to German)

1. Set Language to German
2. Install/Remove any module
3. See error

![Screenshot from 2019-04-03 12-52-36](https://user-images.githubusercontent.com/32454162/55473681-85c09600-560f-11e9-80e6-0a31365662db.png)

PrestaShop version: 1.7.5.1
PHP version: 7

**Comment by khouloudbelguith** [comment] 2019-04-03 14:20
Hi @davidcolombogit,

I manage to reproduce the issue with PS:1.7.5.1.
This issue is added to our bug roadmap.

Thanks!

**Comment by colinegin** [comment] 2019-09-25 15:29
@LouiseBonnard do you think this is a translation issue ?

**Comment by LouiseBonnard** [comment] 2019-09-25 15:37
@colinegin, the string seems to be part of the GDPR module, therefore it is not foundable in Crowdin since the module comes with its own translations.

**Comment by colinegin** [comment] 2019-09-25 15:45
Thanks ! I've added it to the gdpr repo and close this issue :)

**Closed as completed by colinegin** 2019-09-25 15:45 UTC
Labels: Bug, Trivial, BO, Modules catalog, Languages, No change required, Module manager, 1.7.5.1, 1.7.6.0
