### ISSUE TITLE
error invoice  currency

### ISSUE THREAD

**Issue by pnshurba** [PrestaShop/PrestaShop#15394] opened 2019-09-03 18:18 UTC
after upgrading from 1.7.5.2 to 1.7.6.1, invoce does not display the currency instead of a question mark. More details on the screenshot. Please help solve the problem.
![Снимок экрана 2019-09-03 в 21 13 19](https://user-images.githubusercontent.com/39360984/64198164-64025e00-ce90-11e9-80be-92b37e684c8f.png)

**Comment by khouloudbelguith** [comment] 2019-09-04 07:17
Hi @pnshurba,

What is the exact language & currency did you used by the customer?
The invoice is generated from the BO or from the FO?
What is the exact language of your employee?

Thanks!

**Comment by pnshurba** [comment] 2019-09-04 07:27
@khouloudbelguith

I and users use Russian language 
Currency RUB ₽
BO
MY EMPLOYEE USE RUSSIAN language

**Comment by khouloudbelguith** [comment] 2019-09-04 08:33
@pnshurba, this issue occurs on the FO also?
What is the exact version of Internationalization support did you use?
![image](https://user-images.githubusercontent.com/16067358/64238508-757e5100-cef6-11e9-9b94-569e78ea9260.png)
Your issue is duplicate of https://github.com/PrestaShop/PrestaShop/issues/13814
You need to upgrade the intl version.

Thanks!

**Comment by pnshurba** [comment] 2019-09-04 08:56
@khouloudbelguith 

Problem only in pdf.
My version intl 52.1
Data 52.1
Tzdata 2013g
Unicode 6.3

**Comment by khouloudbelguith** [comment] 2019-09-04 10:31
Hi @pnshurba,

Thanks for your feedback.
As checked with @marionf, this issue occurs with PS1.7.6
![image](https://user-images.githubusercontent.com/16067358/64247763-6eac0a00-cf07-11e9-9973-76de3f7cc20f.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
In the meantime, we will check if it is regression or not.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-04 12:15
Hi @pnshurba,

Your ticket is a duplicate of #9817
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-04 12:15
Duplicate of #9817

**Closed as completed by khouloudbelguith** 2019-09-04 12:15 UTC
Labels: Bug, Minor, Duplicate, Invoices, Currencies, Autoupgrade, 1.7.6.1
