### ISSUE TITLE
Only certain clients have trouble getting past login

### ISSUE THREAD

**Issue by Gunit8989** [PrestaShop/PrestaShop#13883] opened 2019-05-20 19:47 UTC
Certain clients complain about not being able to login, whether they try to get passed the first step in cart as a host or registered client, they just cannot get through to the second step where they add their address etc.

It is not every client, only some. We tried to added their address in the back office, as we can see them once they enter the email address, but once we hit the save button, the adress wipes out again.

Can someone please advice?

**Comment by khouloudbelguith** [comment] 2019-05-21 09:01
Hi @Gunit8989,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - Apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matks** [comment] 2019-05-21 09:34
> Certain clients complain about not being able to login, whether they try to get passed the first step in cart as a host or registered client, they just cannot get through to the second step where they add their address etc.
> 
> It is not every client, only some. We tried to added their address in the back office, as we can see them once they enter the email address, but once we hit the save button, the adress wipes out again.
> 
> Can someone please advice?

Looks like a theme issue 🤔 are you using Classic Theme ?

**Comment by Gunit8989** [comment] 2019-05-22 21:25
> > Certain clients complain about not being able to login, whether they try to get passed the first step in cart as a host or registered client, they just cannot get through to the second step where they add their address etc.
> > It is not every client, only some. We tried to added their address in the back office, as we can see them once they enter the email address, but once we hit the save button, the adress wipes out again.
> > Can someone please advice?
> 
> Looks like a theme issue 🤔 are you using Classic Theme ?

Dear matks,

Thank you for your reply. We are using a paid theme called AVO. The prestashop version in use is 1.7.3.3 

Since I am not a developer, I got in touch with several developers as well as the developers of the theme themselves, but they have are not able to reproduce the issue.

**Comment by khouloudbelguith** [comment] 2019-05-23 08:44
Hi @Gunit8989,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-24 07:30
Hi @Gunit8989,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-24 07:30 UTC
Labels: FO, Customer, No change required
