### ISSUE TITLE
Symfony controller not found in Prestashop 8.0.4

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33509] opened 2023-07-31 15:36 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've spent over a couple of months developing a module for Prestashop 8.0.1 based on the demo-grid module Prestashop has developed.

Now it seems in Prestashop 8.0.4 and 8.1 it no longer works.

Even the demo-grid module does not work in Prestashop 8.0.4 + https://github.com/PrestaShop/example-modules/tree/master/demo_grid

### Expected behavior

Moudle should route to correct controller

### Steps to reproduce

Install the demo module from:
https://github.com/PrestaShop/example-modules/tree/master/demo_grid

Install into a plain Prestashop 8.0.4 + installation
Attempt to access the module.

Error is produced as follows:
The controller AdminDemoGrid is missing or invalid.

### PrestaShop version(s) where the bug happened

8.0.4, 8.1.0, 8.1.1

### PHP version(s) where the bug happened

8.1.8

**Comment by kpodemski** [comment] 2023-07-31 21:50
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/33510

**Closed as completed by kpodemski** 2023-07-31 21:50 UTC
Labels: Bug, Invalid

**Comment by musaffarpatel** [comment] 2023-07-31 21:57
Composer install works, thanks ! I was running autoload
