### ISSUE TITLE
Facetedsearch not filtering category in search page if nested category

### ISSUE THREAD

**Issue by Panniz** [PrestaShop/PrestaShop#33535] opened 2023-08-03 10:14 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When enabling search by category in search page and setting depth category filter to 0 (recursive), the search does not filter by the category given if this is a nested category.
I think the problem is in Filters\Converter::createFacetedSearchFiltersFromQuery() as if the request comes from the search page, default home category is used and  passed to Category::searchByNameAndParentCategoryId() as parent category, but being the chosen category a nested category it has a different parent so it returns null.

### Expected behavior

The search should filter every category, not just main categories.

### Steps to reproduce

1. Go to ps_facetedsearch config page
2. Set Category filter depth to 0 (no limits)
3. Go to default filter template and enable it in search page
4. Try filtering  search results by a nested category like Home Accessories for "mug" research.
5. Nothing happens

### PrestaShop version(s) where the bug happened

1.7.8.8, 8.10

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.13.0

**Comment by Hlavtox** [comment] 2023-08-03 10:20
Hi @Panniz, did you search the existing issues? This is one of the first ones that come up. 👍

Duplicate of https://github.com/PrestaShop/PrestaShop/issues/29727

**Closed as completed by Hlavtox** 2023-08-03 10:20 UTC
Labels: Bug, Duplicate

**Comment by Panniz** [comment] 2023-08-03 10:58
> Hi @Panniz, did you search the existing issues? This is one of the first ones that come up. 👍
> 
> Duplicate of https://github.com/PrestaShop/PrestaShop/issues/29727

Sorry, I searched for facetedsearch but found nothing. My fault.
