### ISSUE TITLE
Duplicated payments if invoicing after delivering

### ISSUE THREAD

**Issue by kermes** [PrestaShop/PrestaShop#15745] opened 2019-09-30 07:22 UTC
There are some situations where you may want to generate the invoice when the buyer has received their purchase and not before. For example with COD payments, you should invoice when you receive the money, not before, in case the customer rejects the package.

In order to do that you need to modify the available order states (or add new ones) that would reflect this workflow.
In this scenario, because Prestashop stores delivery slips in the invoice table, when your order changes from "delivered (unpaid)" to "received (paid COD)" Prestashop then adds the payment twice.

There are various ways to solve this:
- use a different way to store delivery slips (and not using an invoice for that)
if an invoice is needed before sending
- force payment methods statuses to always invoice.
- this PR : https://github.com/PrestaShop/PrestaShop/pull/5339

This  PR solves this issue and doesn't affect normal behaviour of orders where invoice is issued first. Here is why:
- the method `setDeliverySlip()` generates an invoice, set delivery date and set delivery number IF there are no invoices.
- This invoice generation doesn't check for previous payments, so a new payment is added.  And here is the problem.

The method `setInvoice($use_existing_payment)` generate an invoice and checks for previous payments, so no duplicate payment is generated, but doesn't add the delivery number and delivery date. It doesn't matter: later in the same function `changeIdOrderState` there is a call to `setDelivery()`, which does exactly those things.

Note: Looks like there is no other call `$order->setDeliverySlip()` in the whole project, so maybe this function might be removed from the code.

**Comment by khouloudbelguith** [comment] 2019-09-30 13:35
Hi @kermes,

Is it similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15513?

Thanks!

**Comment by kermes** [comment] 2019-10-01 07:04
No, sorry, it's different, and the suggested PR's for this and that issues don't solve the other one.

**Comment by khouloudbelguith** [comment] 2019-10-01 16:20
@kermes, could you please provide us the exact steps to reproduce the issue?
- Did you installed the COD module provided by PrestaShop?
![image](https://user-images.githubusercontent.com/16067358/65980713-9b543280-e46f-11e9-8838-c273535fb84b.png)
- Did you make an order from the BO or FO?
- The status generated by the COD module is Processing in progress, did you edit this status?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-31 07:36
Hi @kermes,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-31 07:36 UTC
Labels: No change required, PR available
