### ISSUE TITLE
Filtering by categories isn't working in catalog > product page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10257] opened 2018-09-03 13:38 UTC
**Describe the bug**
Filtering by categories isn't working in catalog > product page

**To Reproduce**
1. Go to Catalog > Products
2. Click on Filter by categories and select a category
3. The page is refreshed but you still see all products
4. If you click on Catalog > Products, you will see the products of the selected category

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by matks** [comment] 2018-09-10 15:32
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10365

**Comment by matks** [comment] 2018-09-10 15:59
I do see a bug but I do not reproduce the issue as described here:

1. Go to Catalog > Products
2. Click on Filter by categories and select category "Women"
3. The page is refreshed and I see 2 demo products:
![capture d ecran 2018-09-10 a 17 56 20](https://user-images.githubusercontent.com/3830050/45308917-d90fb180-b522-11e8-8fd4-86b713fab4f9.png)

**Although on the page** it is written "Category: Accueil" for the 1st product and "Category: Men" for the 2nd product, the search is actually right **because these products do belong to multiple categories**, including the "Women" category.

The issue might have been already fixed in `develop`.

**The bug I find is:**
4. click on the left BO navbar "Catalog" > "Products"  link, this should show me all products of my BO (this should reset the search), it does not work I still see the results of my previous search

**EDIT:** bug described in step 4. seems to be related to search filters persistence, this is another issue.

**Comment by matks** [comment] 2018-09-11 08:36
I think the issue is not a bug as explained in the previous comment.

The products found by the search are relevant: if you search all products for category "Accessories" you will get them, however in the "Category" column it might not be written "Accessories" but another Category name because the product belongs to multiple categories **including** Accessories.

What do you think ? @khouloudbelguith

**Comment by khouloudbelguith** [comment] 2018-09-12 16:56
Hi @matks,

Yes, if you search for the category "Accessories", you will get all the products associated to the "Accessories" category including other categories.
Also, I cannot find a specific documentation about filter by category in the product page.

Best regards, Khouloud

**Comment by jolelievre** [comment] 2018-09-28 13:27
Fixed by https://github.com/PrestaShop/PrestaShop/pull/10728

**Closed as completed** 2018-10-01 15:26 UTC
Labels: Bug, 1.7.5.x, Major, BO, Regression, Fixed
