### ISSUE TITLE
1-click-upgrade problem

### ISSUE THREAD

**Issue by skvaller** [PrestaShop/PrestaShop#30609] opened 2022-12-19 13:02 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am upgrading to Prestashop 1.7.8.8. I use the addon 1-click-upgrade. Had some error first and changed the chmod 755 to 777. It worked on the "auto upgrade" file.

So, all is working but then I start to read what the module or addon actually are backing up. -Its my entire server and I am a webhost! This can't be right? If I give access specifically to Prestashop modules auto-upgrade, how can it exceed the the main domain and start copying every other domain files then? 
My customers wordpress websites was copied and thousands of images?
First of all it feel unsafe knowing some dude have access to all my customers and my server, and second - why is it backing up my files. I needed specifically an Prestashop upgrade, not backup? That I manage myself.
What is this module really doing?

### Expected behavior

Just upgrade.

### Steps to reproduce

1. Click upgrade, no other alternative possible.
2. Starts reading server files...?
3. Got stuck, I changed auto upgrade to 777, just for the upgrade.
4. It worked.
5. It started to copy all files in all domains on my entire server.
6. I cancelled the upgrade.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-click-upgrade

**Comment by matks** [comment] 2022-12-19 15:58
@skvaller it is probably the same problem as https://github.com/PrestaShop/PrestaShop/issues/24351

**Comment by skvaller** [comment] 2022-12-19 17:41
Yeah, I don't know. It doesn't solve my problem. I've had a tonne of them with Prestashop. All shopping platforms has problems so it's not only Presta. A certain known spammer keep spamming my shop, my dashboard wont update and so on. I will try another platform, thank's for the reply though.

**Comment by hibatallahAouadni** [comment] 2022-12-20 10:22
Hello @skvaller 

Could you please specify which 1-click-upgrade module that you use from addons? is it free or no?
If it's the free one, so your issue is duplicate of #24351 as @matks mentioned above.
If not, you should contacted the module's developer 🙏 
Closing the issue and thanks for your understanding.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-12-20 10:22
Duplicate of #24351

**Closed as completed by hibatallahAouadni** 2022-12-20 10:22 UTC
Labels: Bug, Duplicate, Invalid
