### ISSUE TITLE
HomeStyle payment options hacked

### ISSUE THREAD

**Issue by zu7ik** [PrestaShop/PrestaShop#35265] opened 2024-02-05 15:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

we own our eshop on prestashop platform. we sold our products using three payment methods : Paysera, Bank Transfer and COD. approx around new years all our payment methods dissapeared, and new method appeared "pay via card" when you are looking through element ispection you can see that card option comes not even from our system, looks like external (virus, bug?!) as I understand that add on is leaking customers bank details!. When looking through backoffice - once again all payment methods - gone. (card is not even an option)

### Expected behavior

Since paysera is external module atleast help us to bring back bank transfer and COD options for now. 

### Steps to reproduce

currently shopping option is turned off so people wouldnt add their card details. Once you have a chance to look at our issue, please contact me via urte@homestylelt, so I could temporally turn on cart option 

### PrestaShop version(s) where the bug happened

1.7.6.8.

### Your company or customer's name goes here (if applicable).

homestyle.lt

**Comment by matks** [comment] 2024-02-05 16:53
Dear Sir, I understand your shop has been hacked and I am sorry. Unfortunately this place is not the right place to get help, it is a bug tracker, not a help center.

I can suggest you visit this page https://www.prestashop-project.org/support/ to find the right help. I think you need to get in touch with a reliable web agency who is experienced in this kind of situations and can help you.

I close this ticket as it is not a bug report.

**Closed as completed by matks** 2024-02-05 16:53 UTC
Labels: Bug
