### ISSUE TITLE
It is not possible to change iso-code: error 500 ThemeManagerBuilder :: __ construct ()

### ISSUE THREAD

**Issue by ArteInfoRM** [PrestaShop/PrestaShop#14268] opened 2019-06-18 12:52 UTC
When I try to change the iso code at admin menu localization->language by editing the language it results in an error 500. When nothing is changed and I press save, it will result in an update success.

FatalThrowableError HTTP 500 Internal Server Error
Type error: Argument 1 passed to PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManagerBuilder::__construct() must be an instance of Context, null given, called in /var/www/ps1750/classes/Language.php on line 163

PrestaShop versions: 1.7.5.0, 1.7.5.1 and 1.7.5.2

 
![page-3](https://user-images.githubusercontent.com/41371761/59683742-03d91580-91d9-11e9-92f1-785b4c155377.jpg)
![page-2](https://user-images.githubusercontent.com/41371761/59683743-03d91580-91d9-11e9-8c4a-760814a56d5e.jpg)
![page-1](https://user-images.githubusercontent.com/41371761/59683744-0471ac00-91d9-11e9-9134-57678c345881.jpg)

**Comment by khouloudbelguith** [comment] 2019-06-18 12:58
Hi @ArteInfoRM,

This issue is fixed in the release PS1.7.6.0.
In the PS1.7.6.0, the language page is migrated to Symfony, so the issue doesn't exist anymore.
https://drive.google.com/file/d/1sjTF7ZRMG2pZgm-eQiwUsRN3-xN7KDPD/view
Your ticket is a duplicate of #9719
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-18 12:58
Duplicate of #9719

**Closed as completed by khouloudbelguith** 2019-06-18 12:58 UTC
Labels: Duplicate
