### ISSUE TITLE
BO - "Add new product" V2 with quick access is always opened in the same page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#30200] opened 2022-11-03 12:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reported here https://github.com/PrestaShop/PrestaShop/pull/30065#pullrequestreview-1160322870 previously
In the quick access management, we can open the page in a new window, "Add new product" V2 with quick access is always opened in the same page

![image](https://user-images.githubusercontent.com/16067358/199717179-d4a0b122-040d-462f-b66f-bf148a52ca66.png)

PS: product page V1 => ok
### Expected behavior

It should be opened on another page

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Single store
2. Click on the "Quick access" > Manage your quick access
3. Enable "New window" for the "New product" 
![image](https://user-images.githubusercontent.com/16067358/198680007-1f4d3aa6-1c16-46b3-91b8-f581a4bfa3bc.png)
4. Click on "Quick access" > Add a new product
5. Click on "Add new product" button => the add new product page is displayed in the same page

https://user-images.githubusercontent.com/16067358/198686293-9c9cacc5-cff7-4500-a754-303fc7453b4d.mp4

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2022-11-07 14:56
Hello @khouloudbelguith ,

I reproduce the issue with PrestaShop on `develop`, I'll add this to the backlog so it can be fixed.
On `1.7.8.7` and `8.0.x`, it was fine.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment] 2022-12-30 08:45
Seems to be fixed ! :)

**Comment by florine2623** [comment] 2023-01-18 15:07
It is still not fixed on develop 😓 
There's not a new tab opening when creating a new product from Quick Access.

https://user-images.githubusercontent.com/16019289/213207091-217aba24-688d-4f4f-8b4f-5cca5244be7e.mov

**Closed as completed** 2023-03-16 15:03 UTC
Labels: Bug, develop, Minor, BO, Needs Specs, Regression, PR available, Verified
