### ISSUE TITLE
productcomments module : Customer anonymisation doesn't work with reviews coming from version 3

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#22481] opened 2020-12-17 17:09 UTC
#### Describe the bug

I've found a bug with customer anonymisation : if comments come from productcomments module before version 4.0, 

It's because customer_name values are not empty with registered customers, so last name anonymisation is not done.
In 4.x version, customer_name are not filled by registered customers, only by anonymous visitors.

#### Expected behavior

Last name should be anonymized i.e. John Doe should be displayed John D.

#### Steps to Reproduce

1. Install old 3.x productcomments module
2. Register as a customer
3. Add a comment 
4. Upgrade to 4.x productcomments module
5. Activate anonymisation
6. See that  full last name is displayed

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-12-18 14:57
Hello @jf-viguier ,
Thanks for the report and the PR !

Could you specify if you used module productcomments v3 on PS 1.7 or PS 1.6 ?

I can't seem to install and make productcomments v3 work on PS 1.7.7.0.

I managed to install productcomments v3.5.1 on PS 1.6.1.24, but anonymization was automatic :
![Capture d’écran 2020-12-18 à 15 56 40](https://user-images.githubusercontent.com/16019289/102628259-ae712200-4149-11eb-89a9-0911d349fe07.png)
![Capture d’écran 2020-12-18 à 15 56 33](https://user-images.githubusercontent.com/16019289/102628264-b16c1280-4149-11eb-84eb-8ebfdcc88499.png)

Waiting for your feedback!
Thanks!

**Comment by jf-viguier** [comment] 2020-12-18 17:16
@florine2623 
Yes my version 3 of the module come from a 1.6 version of prestashop.
anonymization works on v3.5 but if you migrate to 4.0 version, you will see the issue.

**Comment by hibatallahAouadni** [comment] 2020-12-25 17:01
Hello @jf-viguier 

Sorry for the late response. If I installl the **Product Comment** module v4.2.0 

![image](https://user-images.githubusercontent.com/23308427/103139268-c5c88600-46da-11eb-8403-ad730942b747.png)

And I enbled the **Anonymize the user's last name** option:

![image](https://user-images.githubusercontent.com/23308427/103139285-d973ec80-46da-11eb-908c-a21d094dbe52.png)

I got no issue, I can see clearly that the the user's last name is anonymize:

![image](https://user-images.githubusercontent.com/23308427/103139302-ff998c80-46da-11eb-92f7-3355d751f67d.png)

Do you mean that the issue is only encountred when you had old version of this module (ex: 3.5) and you upgarde it to 4.0?
Please check and feedback.

Thanks!

**Comment by jf-viguier** [comment] 2020-12-26 08:39
Yes

**Comment by hibatallahAouadni** [comment] 2020-12-29 16:24
Hello @jf-viguier 

With PS1.7.7.0 (or 1.7.6.9 or 1.7.5.2 or 1.7.4.1), I can not install ProductCommen v3.6 cause it's not compatible see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/103298256-3aad0000-49fa-11eb-9813-ca41a57023db.png)

I tried with PS1.6.1.20, like @florine2623 mentioned above the anonymization was automatic:

![image](https://user-images.githubusercontent.com/23308427/103298352-6f20bc00-49fa-11eb-8536-f08590f6dfa5.png)

If I try to upgrade the ProductComment module version to v4, I get this error:

![image](https://user-images.githubusercontent.com/23308427/103298388-8495e600-49fa-11eb-89a4-a38ed16fde9a.png)

So, could please tell how did you manage to reproduce the issue.

Thanks!

**Comment by jf-viguier** [comment] 2020-12-29 19:37
@hibatallahAouadni the issue is on comments posted with 3.x module, not on comments posted in 4.x module.
I've migrated prestashop from 1.6 to 1.7.6 in order to migration module to 4.x version.

The error on the module installation is certainly a version issue.
Here is a more precise howto :
- Install old 3.x productcomments module in prestashop 1.6
- Register as a customer
- Add a comment
- Upgrade prestashop to 1.7.x and upgrade module productcomments to 4.x productcomments 
- Activate anonymisation
- See that full last name is displayed

**Comment by hibatallahAouadni** [comment] 2021-01-01 14:23
Hello @jf-viguier 

I couldn't manage to reproduce your issue :confused:  I installed 1.6.1.20 and tried to install the ProductComment 3.6.1 module but I got an error, see the attached screen record below: 

https://drive.google.com/file/d/1vHPM5e-DNf3seQ9aNAglTbPkBI3KlYif/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-21 07:49
Hello ,

I'm really sorry :confused: but since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by jf-viguier** [comment] 2021-01-21 11:06
@hibatallahAouadni you close the issue but I've made a PR and an explanation on how to reproduce the bug.
The installation error you have is not related to my issue nor my pr : it's another issue. Please reopen it.

**Comment by jf-viguier** [comment] 2021-01-21 11:15
In my user case, I've copied module tables from 1.6 to 1.7 that'd why I've not the upgrade bug you have.

**Comment by hibatallahAouadni** [comment] 2021-01-21 11:19
As discussed with you in Slack, I'm going to re-open the issue but we need the Developer Team opinion :wink: 

Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers I didn't manage to reproduce the issue cause I encountred other issue :confused: could someone please check it out :pray: 

Thanks in advance.

**Comment by jf-viguier** [comment] 2021-01-21 11:21
Dev team can confirm that this 3 lines of code are ok with no regression.

**Comment by PierreRambaud** [comment] 2021-01-21 14:09
Pr already in waiting for QA statement :+1:

**Closed as completed** 2022-01-20 14:03 UTC
Labels: Bug, 1.7.x, Minor, FO, Fixed, Productcomments, PR available, 1.7.7.0, Module
