### ISSUE TITLE
Order as a guest > register with same email > order lost and cannot be tracked

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15605] opened 2019-09-18 21:14 UTC
**How to reproduce**
1. Order something as a guest with a single email address.
2. Register yourself in the store as a customer with this email adress.
3. Log out.
4. Go to guest tracking and try to track the order you made with the guest customer.
5. Does not work and says "Log in to your customer account to track your order".
6. You log in. Order is not there.
7. The order cannot be tracked.

**My personal thoughts on solution**
- If I order something two or more times as a guest, with the same email adress, the order should be assigned to the same original guest customer id.
- If I register my account, it should scan customer database for guest with the same email address and if found, it should convert that guest customer instead of creating a customer with duplicate address.

If solutions above are not possible, at least it should allow the guest to track the order, even if customer account is made.

**Additional information**
PrestaShop version: 1.7.6.0

**Comment by khouloudbelguith** [comment] 2019-09-19 08:06
Hi @Hlavtox,

Thanks for your report.
We are aware of these issues.
In fact, the Guest account is not transformed into a customer account, it creates a second account
Issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/10122
Also, guest tracking issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/9650#issuecomment-415055890
Thanks to check & feedback.

**Comment by Hlavtox** [comment] 2019-09-19 11:50
Hi @khouloudbelguith 

Yes, you are right. Sorry for duplicate post.
So, either close it or maybe leave it open for discussion. I think it states the problem in a "cleaner way".

**Comment by khouloudbelguith** [comment] 2019-09-19 12:27
@Hlavtox,

Sorry, since it is a duplicate, we need to close it.
Your ticket is a duplicate of #10122 &  #9650.
So, I close it.
>After edition

it is **not duplicate of** other issues. 
Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-21 10:39
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16872

**Closed as completed** 2020-04-21 11:17 UTC
Labels: Customer, Fixed, 1.7.6.0
