### ISSUE TITLE
You cannot translate a string, if there are two simmilar strings with different capital letters

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18258] opened 2020-03-22 13:43 UTC
#### Describe the bug

If there are two strings, with simmilar text, but different cases, you cannot translate them.

If there is
_{l s='more information' d='Shop.Theme.Catalog'}
{l s='More information' d='Shop.Theme.Catalog'}_
in the template, it cannot be translated.

It get's shown in Translations, it seems to translate OK, but after page refresh, the original untranslated string remains.

**Screenshots**

![translations](https://user-images.githubusercontent.com/6097524/77250915-5903f500-6c4b-11ea-9caf-64629d743bba.JPG)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

ping translation master @eternoendless 😄

**Comment by khouloudbelguith** [comment] 2020-03-23 09:15
Hi @Hlavtox,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15511 to fix the issue.
It is fixed in the PS1.7.7.0.
Your ticket is a duplicate of #10701
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-23 09:15
Duplicate of #10701

**Comment by Hlavtox** [comment] 2020-03-23 09:16
@khouloudbelguith Nice!

**Closed as completed by khouloudbelguith** 2020-03-23 09:15 UTC
Labels: Duplicate
