### ISSUE TITLE
Abandoned cart with no order

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#13895] opened 2019-05-21 10:27 UTC
Hello

I would like to understand what it means when the cart is abandoned and yet nothing appears to be added to cart. How can someone abandon a cart with nothing in it?

Please refer to image below.

![unt](https://user-images.githubusercontent.com/26452178/58088759-620fda00-7bd4-11e9-828b-337366857e9d.png)

As you can see, customer abandoned the cart but no order was created. How can this be?

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-21 11:45
Hi @nrcjea001,

When a customer signs in, an empty cart of 0€ is created.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9589
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-21 11:46
Duplicate of #9589

**Closed as completed by khouloudbelguith** 2019-05-21 11:45 UTC
Labels: Duplicate
