### ISSUE TITLE
spam ip is on the site every time

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#18418] opened 2020-04-01 10:53 UTC
Hello!
The Ip 178.159.37.139 appeared on my site https://te.com.ua and attack it every time. I added this IP to .htaccess but it still on my site. My provider said that it does not enter from Apach . May be it wrote themself in module...
Here https://dnschecker.org/ip-blacklist-checker.php this IP detected as spam

![image](https://user-images.githubusercontent.com/50954519/78129283-03d09c00-7420-11ea-848a-6a8f08090cd3.png)

Please help me found and ban it
--

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-04-01 11:06
Hi @photinia73,

Spams on 1.7 are caused by the `contactform,` here are the PRs resolving this issue:

`contactform` module:
https://github.com/PrestaShop/contactform/pull/19 => fixed in the `contactform` module v4.0.0.

ps_emailgenerator:
https://github.com/PrestaShop/ps_emailgenerator/pull/17 => fixed in the last release of `ps_emailgenerator`
 
PrestaShop:
https://github.com/PrestaShop/PrestaShop/pull/8873 fixed in the PS1.7.3.1.

You can follow this link:
http://build.prestashop.com/news/fighting-against-spamming-again/

The very best protection against such spam is a reCAPTCHA.
ReCAPTCHA was designed to stop bots from submitting any form. It's the exact solution to use for this specific use-case.

Using, for example, this module: https://addons.prestashop.com/en/website-security-access/18478-re-captcha-anti-spam-recaptcha.html, you no longer need to place a line of code on your templates. Everything is automatic for Prestashop.

Thanks to check and feedback.

**Comment by photinia73** [comment] 2020-04-01 11:42
My PS is 1.7.6.2
Concactform.php has enother code like in the ref PrestaShop/contactform#19 => fixed in the contactform module v4.0.0.
I have not module ps_emailgenerator:
And I use reCaptcha
![image](https://user-images.githubusercontent.com/50954519/78133345-eeab3b80-7426-11ea-8cdc-2f052aa43ebd.png)
So there is the problem in something else ((

**Comment by photinia73** [comment] 2020-04-01 11:48
O! The Contactform does not work ((
The same problem was after upade to 1.7.2 and now again ((

**Comment by matks** [comment] 2020-04-01 12:02
> Hello!
> The Ip 178.159.37.139 appeared on my site https://te.com.ua and attack it every time. I added this IP to .htaccess but it still on my site. My provider said that it does not enter from Apach . May be it wrote themself in module...

I dont think a module is capable of bypassing the htaccess file.

In your traffic logs, could you see if you can see what URls this IP use ? This should tell you where he is entering.

If there is no trace of this IP in traffic logs, then indeed he does not reach your website from Apache. Is there another web-server running on your server ? nginx maybe ?
On server you should be able to check the list of open ports and what service is listening to these ports.

**Comment by khouloudbelguith** [comment] 2020-04-01 12:05
@photinia73,

>The Contactform does not work ((

What is the exact problem?

Thanks!

**Comment by photinia73** [comment] 2020-04-01 12:26
> @photinia73,
> 
> > The Contactform does not work ((
> 
> What is the exact problem?
> 
> Thanks!

After I re-wrote the contactform.tpl to my custom Theme it started work. (send the letter). BUT. Have a tarrible view https://te.com.ua/ru/contact-us. And this not a biggest problem. The reCaptcha have not power (not nessary) I can not check it and the letter will send.  In the previous variant the reCaptcha was placed here
![image](https://user-images.githubusercontent.com/50954519/78136961-24ebb980-742d-11ea-9094-03194a4b080d.png)

**Comment by khouloudbelguith** [comment] 2020-04-01 13:52
@photinia73,

>The reCaptcha have not power (not nessary) I can not check it and the letter will send. In the previous variant the reCaptcha was placed here

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by photinia73** [comment] 2020-04-01 14:29
All Ok! I jast forrgot that I changed a few rows in the contactform.php for reCaptcha controll. Sorry. After contactform`s reCaptcha update it look like the boiring IP disappeared ))

**Comment by khouloudbelguith** [comment] 2020-04-01 14:41
@photinia73, Great!

Since it is OK, I will close the issue.
Feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-01 14:41 UTC
Labels: No change required
