### ISSUE TITLE
Issue after install 1.7.4.2 to 1.7.5.0

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11387] opened 2018-11-14 14:24 UTC
From 1.7.4.2, I tried to install 1.7.5.0 with the archive [beta 1 of github](https://github.com/PrestaShop/PrestaShop/releases).
I put in the folder admin/autoupgrade/download/

I choose local archive in the upgrade module and selected the archive.

After install, the module told me it was impossible to upgrade the database.

When  I return to my shop, I was in 1.7.4.4 and Debug mode Deactivate.
I check the FO, everything seems ok, the BO seems ok too. (Some "can't reproduce" [bug](https://github.com/PrestaShop/ps_linklist/issues/49) fixed too...)

Anyway, when I activated Debug Mode, I got an error.

```
(1/1) ServiceNotFoundException
The  service "prestashop.module.link_block.grid.data_factory" has a  dependency on a non-existent service "prestashop.core.hook.dispatcher".
--
in CheckExceptionOnInvalidReferenceBehaviorPass.php line 31
at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(object(Reference), false)
in AbstractRecursivePass.php line 60

at AbstractRecursivePass->processValue(array('$gridQueryBuilder' => object(Reference), '$hookDispatcher' => object(Reference), '$queryParser' => object(Reference), '$gridId' => 'link_block'), false)
in CheckExceptionOnInvalidReferenceBehaviorPass.php line 28

at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(array('$gridQueryBuilder' => object(Reference), '$hookDispatcher' => object(Reference), '$queryParser' => object(Reference), '$gridId' => 'link_block'))
in AbstractRecursivePass.php line 67

at AbstractRecursivePass->processValue(object(Definition), true)
in CheckExceptionOnInvalidReferenceBehaviorPass.php line 28

at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(object(Definition), true)
in AbstractRecursivePass.php line 60
```

**Comment by khouloudbelguith** [comment] 2018-11-14 14:29
Hi @BenTen,

We have some issues when upgrading to the PS1.7.5.0beta1.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11142
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-14 14:29
Duplicate of #11142

**Closed as completed by khouloudbelguith** 2018-11-14 14:29 UTC
