### ISSUE TITLE
Stats not working

### ISSUE THREAD

**Issue by silviu25** [PrestaShop/PrestaShop#14164] opened 2019-06-12 10:16 UTC
**Describe the bug**
Stats Dashboard Not Working in Admin Area
In all tabs and fields there are 0 for all values. no matter what settings I use,from date range to module settings. always looks 0. Online visitors 0, Active Shopping Carts 0, Orders 0 everything is 0.

`VERSION COMPARISON
PrestaShop Original version:
 40 file modifications have been detected, including 2 from core and native modules: See or hide the list

CORE FILE(S) (2)
img/favicon.ico
modules/ps_themecusto/views/fonts/fontawesome-webfont.svg

MAIL FILE(S) (38)
mails/en/contact_form.txt
mails/en/credit_slip.txt
mails/en/voucher_new.txt
mails/en/productoutofstock.txt
mails/en/bankwire.txt
mails/en/order_merchant_comment.txt
mails/en/order_return_state.txt
mails/en/in_transit.txt
mails/en/account.txt
mails/en/cheque.txt
mails/en/payment.txt
mails/en/contact.txt
mails/en/employee_password.txt
mails/en/in_transit.html
mails/en/payment_error.txt
mails/en/guest_to_customer.txt
mails/en/refund.txt
mails/en/newsletter.txt
mails/en/import.txt
mails/en/log_alert.txt
mails/en/order_canceled.txt
mails/en/reply_msg.txt
mails/en/order_conf.txt
mails/en/order_changed.txt
mails/en/preparation.txt
mails/en/forward_msg.txt
mails/en/order_customer_comment.txt
mails/en/backoffice_order.txt
mails/en/download_product.txt
mails/en/bankwire.html
mails/en/outofstock.txt
mails/en/test.txt
mails/en/password_query.txt
mails/en/productoutofstock.html
mails/en/password.txt
mails/en/shipped.txt
mails/en/order_customer_comment.html
mails/en/voucher.txt

Differences between versions:
 0 files will be modified, 0 files will be deleted (if they are found). See or hide the list`

`Server
Server Linux #1 SMP Thu Jan 4 13:30:50 EST 2018 x86_64

Server software version: LiteSpeed

PHP version: 7.2.19

Memory limit: 512M

Max execution time: 120

Upload Max File size: 128M`

`Database information
MySQL version: 5.7.26

MySQL server: 127.0.0.1

MySQL name: xxx

MySQL user: xxx

Tables prefix: ps_

MySQL engine: InnoDB

MySQL driver: DbPDO`

`Check your configuration
Required parameters: OK

Optional parameters: OK`

**Screenshots**
https://imgur.com/ikr5DQ7
**Additionnal information**
PrestaShop version: 1.7.5.2

Any idea how to fix it?

**Comment by khouloudbelguith** [comment] 2019-06-12 10:22
Hi @silviu25,

I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/59343667-4647b180-8d04-11e9-8554-27b9297ff565.png)
Did you tried to change the delay "From" "To"?

Thanks!

**Comment by silviu25** [comment] 2019-06-12 10:24
yes I changed but no luck

**Comment by khouloudbelguith** [comment] 2019-06-12 10:28
@silviu25, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by silviu25** [comment] 2019-06-12 11:40
Here is the PHP error log
[error_log.txt](https://github.com/PrestaShop/PrestaShop/files/3281092/error_log.txt)

I activated debug mode but I'm not shure how to get the report from debug mode. 
I cleared cache in prestashop and browser and there is no errors displayed

**Comment by khouloudbelguith** [comment] 2019-06-12 12:11
@silviu25, in your log file, you have this error

`PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/home/my-site/my-site.com/modules/lgcookieslaw/views/templates/hook/cookieslaw.tpl" `

Have you tried to contact the module author about this issue?
Thanks to check with them & feedback.

**Comment by silviu25** [comment] 2019-06-12 12:43
I just disabled that module but still nothing on stats menu

**Comment by khouloudbelguith** [comment] 2019-06-12 13:01
@silviu25, could you please try to reset the `statsforecast` module, clear cache, check & feedback.
Thanks!

**Comment by silviu25** [comment] 2019-06-12 13:06
Done but same issue. 
Another strange thing is when I click on Link with your Google Analytics is sending me to modules page. I have Google Analytics v3.1.3 installed and configured. In my Analytics I can see how many are online... everything is fine

**Comment by khouloudbelguith** [comment] 2019-06-12 14:22
@silviu25, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Could you please try to re-install the `statsforecast` module (remove the folder) after clearing the cache, check & feedback.

>Another strange thing is when I click on Link with your Google Analytics is sending me to the modules page

I have the same issue with PS1.7.6.0beta1 & PS1.7.5.2

THanks!

**Comment by silviu25** [comment] 2019-06-12 17:11
I deleted all modules named with stats* , I deleted all folders from  var/cache prod and dev , I reinstalled all modules previously deleted, I cleaned chache from Advanced > Performance >clear cache, I cleaned cache from LiteSpeed Cache module and the problem still persists.
Could be something wrong with host? (I use Chemicloud Turbo plan) or PHP version (7.2.19)
or maybe is missing some mandatory plugin or module?

**Comment by hacchus** [comment] 2019-06-13 10:01
@silviu25 Hello, do you have invoices enabled? (Orders -> Invoices -> Invoice Options)

**Comment by khouloudbelguith** [comment] 2019-06-13 10:07
@silviu25, PS1.7.5 is compatible with PHP7.2.
There is only an issue related to the `statsforecast` module in your case.
The problem has no relation to other modules.

@hacchus, if invoices are disabled, stats are ok too.
https://drive.google.com/file/d/1eDBY9xZ0ki9819wAi9FMWLa3_wP8RCLB/view

Thanks!

**Comment by silviu25** [comment] 2019-06-13 10:10
invoices are enabled in my case

**Comment by hacchus** [comment] 2019-06-13 10:13
@khouloudbelguith I have a 1.7.4.4 that does not show stats either. Maybe its a different issue. In "ps_orders" table the "invoice_date" column is used to generate stats. If there is no date (ie 0000-00-00 00:00:00) there then you get no stats. I will have to investigate further and let you know, because that shop has many customizations.

@silviu25 So it might be a different issue.

**Comment by khouloudbelguith** [comment] 2019-06-13 10:18
@hacchus, this is a different issue as described in this ticket: #12027
@silviu25,  in your BO => Installed modules page, thanks to check if the Sales and orders module is installed in your shop.

Thanks!

**Comment by silviu25** [comment] 2019-06-13 10:25
@khouloudbelguith yes I have Sales and orders module installed.
the thing is that even online visitors are not displayed or what were yesterday for example. Could be something from template? maybe a tracking code or something...?

**Comment by khouloudbelguith** [comment] 2019-06-13 10:27
@silviu25, did you use a different theme from Classic?
Thanks!

**Comment by silviu25** [comment] 2019-06-13 10:29
yes, I use this one: https://www.leotheme.com/prestashop/themes/779-leo-zurich-gifts-and-souvenirs-prestashop-theme.html

**Comment by khouloudbelguith** [comment] 2019-06-13 10:30
@silviu25, have you tried to contact them?
Thanks to check with them & feedback.

**Comment by mariem-abid** [comment] 2019-07-15 07:17
Hi @silviu25,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by mariem-abid** 2019-07-15 07:17 UTC
Labels: Bug, BO, Can't reproduce, Stats, 1.7.5.2

**Comment by silviu25** [comment] 2019-08-14 07:14
I;m coming with news
I installed a fresh new PS 1.7.6.0 on a subfolder (ex: www.mysite.com/2 )
I installed and configured a new theme, then I checked and everything was fine, including stats.
I moved entire PS 1.7.6.0 from subfolder to root (ex: www.mysite.com) and everything is fine except stats.
