### ISSUE TITLE
Smarty variable set in hookActionProductSearchAfter not accessible in minature product template on pages with pagination

### ISSUE THREAD

**Issue by DevSTG** [PrestaShop/PrestaShop#22025] opened 2020-11-20 10:28 UTC
#### Describe the bug

If I set a Smarty variable in hookActionProductSearchAfter it is accessible in `themes/classic/templates/catalog/_partials/miniatures/product.tpl` template (or extending templates in child theme) only on first page of category product list, on subsequent pages need to refresh page (F5). Pagination issue?

#### Expected behavior

Smarty variable accessible on all pages of category product list

#### Steps to Reproduce

1. Create module using hook 'actionProductSearchAfter' and set smarty variable in method: hookActionProductSearchAfter()
```
class Stgtestsearchfilter extends Module {
...
    public function hookActionProductSearchAfter($searchVariables) {
	$this->context->smarty->assign('hookActionProductSearchAfterTest', 1);
    }
}
```
2. Add code: `{if isset($hookActionProductSearchAfterTest)}TEST OK!{/if}` in `themes/classic/templates/catalog/_partials/miniatures/product.tpl`

3. Go to a category with >1 pages
4. See 'TEST OK!' on 1st page, and don't see it on pages >1 unless refreshing with F5
5. If you refreshed on page >1 go to page 1 (using pagination control at bottom) and don't see test text - it seems like it works only on one of paginated results

If you try to get list of products `$searchVariables['products']` in `hookActionProductSearchAfter($searchVariables)` on pages>1 you will see that the list contains products from 1st page of category, unless refreshed at page >1 then on pages other than refreshed you will have list of products from that refreshed page only - maybe that is a hint to solve the problem.

You may visit: https://sukcesgroup.pl/sklepnowy/pl/2-strona-glowna to see how it works

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 5.6.38

**Comment by florine2623** [comment] 2020-11-20 10:50
Hello @DevSTG ,

Is it possible to provide the module that you created ?

Thanks!

**Comment by DevSTG** [comment] 2020-11-20 11:24
Yes, it's really simple module it only registers a hook and sets Smarty variable - there is only 1 file: `stgtestsearchfilter.php`
```
<?php
if (!defined('_PS_VERSION_'))
    exit;

class Stgtestsearchfilter extends Module {

    public function __construct() {
        $this->name = 'stgtestsearchfilter';
        $this->tab = 'front_office_features';
        $this->version = '1';
        $this->author = 'Marek';
        $this->need_instance = 0;

        parent::__construct();

        $this->displayName = 'STG SearchFilterTest';
        $this->description = 'SearchFilterTest';
    }

    public function install() {
        if (parent::install() == false
                || $this->registerHook('actionProductSearchAfter') == false
                )
            return false;
        return true;
    }

    public function uninstall() {
        return parent::uninstall();
    }
    
    public function isUsingNewTranslationSystem() { return true; }
    
    public function hookActionProductSearchAfter($searchVariables) {
	$this->context->smarty->assign('hookActionProductSearchAfterTest', 1);
    }
}
```
Please remember you need to add code: `{if isset($hookActionProductSearchAfterTest)}TEST OK!{/if}` in your `themes/classic/templates/catalog/_partials/miniatures/product.tpl` file

I just noticed that my Smarty variable is not accessible in `themes/classic/templates/catalog/_partials/products.tpl` and it's sub-view templates if accessed inside `<div id="js-product-list">...</div>`. If I try to access my variable outside this `div` it is accessible.

**Comment by hibatallahAouadni** [comment] 2020-11-24 12:15
Hello @DevSTG 

Sorry for the late response. But, we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #18109.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-24 12:15
Duplicate of #18109

**Closed as completed by hibatallahAouadni** 2020-11-24 12:15 UTC
Labels: FO, Duplicate, Hook, 1.7.6.8
