### ISSUE TITLE
Supported php 8.2

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#30560] opened 2022-12-12 22:59 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Supported php 8.2

### Describe the solution you'd like

Supported php 8.2

### Alternatives you've considered

Supported php 8.2

### Additional context

Supported php 8.2

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by kpodemski** [comment] 2022-12-12 23:20
Duplicate of #30335

**Closed as completed** 2022-12-12 23:20 UTC
Labels: Feature, Duplicate, Invalid
