### ISSUE TITLE
 "Invoices"-Link results in HTTP 500 Internal Server Error not solved with #12314

### ISSUE THREAD

**Issue by decom-media** [PrestaShop/PrestaShop#12812] opened 2019-03-06 22:27 UTC
after checking your suggestion with the solution #12314 - it is not working for me - first quiery is not working because the subquery is returning more than just one result, so i tried the second one, which did return 0, but, then the insert did return also "not possible because the subquery did return more than just one result", so it seems there is still another problem in my installation

**Comment by khouloudbelguith** [comment] 2019-03-07 07:50
Hi @tom75,

First, could you please provide us with more info:

 - server setup and configuration
 - debug mode report: thanks to provide me the exact exception displayed
 - PHP error logs
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 14:44
I close this issue, solution to fix in this comment: https://github.com/PrestaShop/PrestaShop/issues/12737#issuecomment-470550425
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 14:44
Duplicate of #12737

**Closed as completed by khouloudbelguith** 2019-03-07 14:44 UTC
Labels: Bug, BO, Duplicate, Invoices
