### ISSUE TITLE
Error to calculate shipping fee.

### ISSUE THREAD

**Issue by evsport** [PrestaShop/PrestaShop#15095] opened 2019-08-13 12:59 UTC
Hi
I have an issue with the cart.
I offer free shipping for order more than 100$.
If the customer is buying a products that cost 110$ and add a coupon of 15% the price will be less than 100$ but the system doesn't add the shipping fee.
Do you know if this bus is fixed?

Prestashop version:1.7.4.2

I will appreciate your help.
Thank you

**Comment by mariem-abid** [comment] 2019-08-14 14:42
Hi @evsport,

I did not manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record
https://drive.google.com/file/d/1TGSHc_AbXsieYe7XAe4L8arBdKzYkQT_/view

Thanks for check and feedback.

**Comment by evsport** [comment] 2019-08-14 15:24
Hi
thank you for your reply.
I have setup a carrier for a free shipping over 100$ tax and shipping excluded.
You have to add products that the amount is more than 100$ and after you have to add the code.
Could you check please?
Thank you so much.

**Comment by mariem-abid** [comment] 2019-08-14 15:29
@evsport, did you make 2 carts rules?

**Comment by evsport** [comment] 2019-08-14 15:39
No
I create the carrier for free shipping and I created 3 different cart rules based on the discount.
To fix this I excluded the free shipping carrier from the carrier selection.
I have to update ps from 1.7.4.2 to 1.6, will I have to take care of samething?
There are any bug into the new release that are not fixed yet?
Thank you

**Comment by mariem-abid** [comment] 2019-08-15 15:19
Hi @evsport,

Your Prestashop version is 1.7 or 1.6?

**Comment by evsport** [comment] 2019-08-15 15:21
I have 1.7.4.2

**Comment by mariem-abid** [comment] 2019-08-15 15:37
@evsport, Could you please add steps or a video record to reproduce your the issue in a new comment.

**Comment by khouloudbelguith** [comment] 2019-09-23 07:34
Hi @evsport,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-23 07:34 UTC
Labels: Bug, Shipping, Cart rules, No change required, 1.7.4.2
