### ISSUE TITLE
On backorder (paid) --> lost

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11060] opened 2018-10-18 09:31 UTC
Prestashop 1.7.4.3
I've upgrade my prestashop from 1.6.x release, and I've on order status 2 similar "On backorder" so I've delete 1 of 2 (id=13)
Now I've working id=9 of "On backorder (paid) "
Sometimes, when customer place an order and product is out of stock, prestashop doesn't add automatically the status "On backorder (paid) ": why?
How can I restore "On backorder (paid) " when a new order have out of stock products?

**Comment by khouloudbelguith** [comment] 2018-10-18 09:35
Hi @centoasa,

How did you delete the order? manually from the database?
Thanks!

**Comment by centoasa** [comment] 2018-10-18 10:30
manually from database (because was a duplicate)

**Comment by khouloudbelguith** [comment] 2018-10-18 10:48
Hi @centoasa,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by centoasa** [comment] 2018-10-18 10:52
This is quite impossible, because this happens only for some orders!
My question is: it's possible restore/apply default behaviour when customer place an order and product is out of stock, so the order have the status "On backorder" ?

**Comment by khouloudbelguith** [comment] 2018-10-18 10:56
Hi @centoasa,

I upgrade from 1.6.1.22 to 1.7.4.3 with 1-click upgrade v4.2.0, but I did not manage to reproduce the issue.
It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.4.
The solution is to add the missing columns to your database schema.
You can find the full schema for 1.7.4.3 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.3/install-dev/data/db_structure.sql
Thanks to check & feedback.

**Comment by centoasa** [comment] 2018-10-18 11:03
ok, but I think there's a call from some script that teach prestashop to change status to id=??? when order have some product out of stock

**Comment by khouloudbelguith** [comment] 2018-10-18 11:08
Hi @centoasa,

You can follow this link: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.3/classes/PaymentModule.php#L741
Thanks!

**Comment by centoasa** [comment] 2018-10-18 12:42
@khouloudbelguith thank you so much for your very useful suggestions and faster reply!
restored on db id=12 on order_state table and made right translation in italian to "In attesa di rifornimento (non pagato)"

**Comment by khouloudbelguith** [comment] 2018-10-18 13:00
@centoasa, so the issue is fixed?

**Comment by centoasa** [comment] 2018-10-18 13:06
@khouloudbelguith yes, fixed! You can close this.

**Comment by khouloudbelguith** [comment] 2018-10-18 13:08
@centoasa, thanks for your feedback.
I close the issue, feel free to open, a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-18 13:08 UTC
Labels: Bug, BO, Order, Order statuses, Fixed, 1.7.4.3
