### ISSUE TITLE
I want to change how the price shows in my website

### ISSUE THREAD

**Issue by jayp03** [PrestaShop/PrestaShop#12176] opened 2019-01-16 12:45 UTC
Good day ! I need your help guys this is how the price of a product looks my in my website 3500,00 Fcfa but I want to it to show 3500 Fcfa without this ,00

AS you can see i the screenshot i want to change it 

Can you help me please 

https://snag.gy/4sxg7e.jpg

**Comment by khouloudbelguith** [comment] 2019-01-16 13:11
HI @jayp03,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #10017
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-16 13:11
Duplicate of #10017

**Closed as completed by khouloudbelguith** 2019-01-16 13:11 UTC
Labels: Duplicate
