### ISSUE TITLE
Product base price updating itself after manual change

### ISSUE THREAD

**Issue by futurehousestore** [PrestaShop/PrestaShop#12545] opened 2019-02-12 20:03 UTC
**Describe the bug**
Product base price updating itself with a weird amount after changing it in manual order

**To Reproduce**
1. In BO go to orders -> add new order
2. Choose a customer and add products to the order
3. Change/adjust the product price 
4. See how price changing itself to a different value (see the attached video for a better explanation) 

**Screenshots**
https://drive.google.com/open?id=1QcJyb1FFVUVmwTu2nZtyMR4_iaKRlk2A

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-02-13 08:22
Hi @futurehousestore,

In your case, the Currency "British Pound Sterling" is the default one defined in the localization page?
If no, the price will be automatically converted to the default currency.
Thanks to check & feedback.

**Comment by futurehousestore** [comment] 2019-02-13 17:44
Hi, @khouloudbelguith, yes the British Pound Sterling is set as my default currency.
![localization](https://user-images.githubusercontent.com/28427270/52731442-a4ae8e80-2fb5-11e9-9c66-270700e99aaf.JPG)
![currency](https://user-images.githubusercontent.com/28427270/52731958-f0156c80-2fb6-11e9-96cb-7aca06d04ddc.JPG)
![lang](https://user-images.githubusercontent.com/28427270/52731965-f4da2080-2fb6-11e9-8bb3-3bed14299282.JPG)
I have a similar problem with prices when setting up a specific price. Please see the attached video
https://drive.google.com/open?id=15MRe5AZ4J6ig-fPqU_erUyxxxodsw88_

**Comment by khouloudbelguith** [comment] 2019-02-13 17:53
@futurehousestore, I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1kZCU7b27uf6pNXq51Ic4AeRfeSvM-mWK/view
Thanks to check & feedback.

PS: about your video record is not available.
Thanks!

**Comment by futurehousestore** [comment] 2019-02-13 18:22
Thanks @khouloudbelguith for checking it.
When I adjust the price manually for order in BO I get an error in my DirectAdmin Web Control Panel
[Wed Feb 13 19:13:31.942155 2019] [:error] [pid 1530] [client 81.105.86.182:54903] PHP Warning:  Cannot modify header information - headers already sent by (output started at .../public_html/controllers/admin2/AdminCartsController.php:859) in .../public_html/classes/controller/AdminController.php on line 1877, referer: .../admin/index.php?controller=AdminOrders&addorder&token=9f23a9b2753363d86ae2c72699e431d2
Regarding the video record being not available I did copy the url whilst the video was still processing. Here is the working link https://drive.google.com/open?id=15MRe5AZ4J6ig-fPqU_erUyxxxodsw88_

**Comment by khouloudbelguith** [comment] 2019-02-14 09:58
@futurehousestore, thanks for your feedback.
In fact, I imported the United Kingdom pack, I defined the British Pound Sterling as the default currency.
In FO, It is OK.
I attached a video record.
https://drive.google.com/file/d/1Mcm5_EYDDHa9jPnrkQqjFznGl2v61TVk/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-18 07:27
Hi @futurehousestore, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-18 07:27 UTC
Labels: BO, Order, Currencies, Taxes and Prices, No change required
