### ISSUE TITLE
Product With Combinations Duplication Bug

### ISSUE THREAD

**Issue by JK-Products** [PrestaShop/PrestaShop#28969] opened 2022-07-05 19:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you duplicate a product that has combinations associated with it, you can duplicate the product and change the reference, but the reference is never properly updated. You can see the mismatch in the picture. It shows the updated reference in the back end but the original reference is still stored for the product and can't be updated.
![temp](https://user-images.githubusercontent.com/108761749/177400908-590c18a8-785a-4bd1-a5fe-2381185d574d.jpg)
 

### Expected behavior

You should be albe to update the reference when dupicating a product that has combinations.

### Steps to reproduce

1. Create a product with combinations.
2. Duplicate this product.
3. Change the reference number 
4. When you order the part on the front end, the reference number remains the original from which you duplicated, not the edited version you changed and saved.

### PrestaShop version(s) where the bug happened

1.7.6.8

**Comment by HanaRebaiQA** [comment] 2022-07-06 10:30
Hello @JK-Products 

Thanks for your report.
I tried to reproduce your issue with 8.0.x with both the legacy product page (V1) and the new one (Product page V2)
Also, i tried with PS1786 in product page V1. But, I was unable to reproduce it.


Here is a screen-record : **8.0.x with product V1 and V2**

https://user-images.githubusercontent.com/92912932/177530394-683f7c7a-a03e-46ae-9a43-dd65dc0d8965.mp4

Here is a screen-record : **PS1786 with product V1**

https://user-images.githubusercontent.com/92912932/177530513-a9746d8e-8545-4ebf-98f0-302d3081886e.mp4


Could you please check again?

Thank You!

**Comment by florine2623** [comment] 2022-07-26 08:52
Hello @JK-Products ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2022-07-26 08:52 UTC
Labels: Bug, BO, Combinations, 1.7.6.8, Invalid
