### ISSUE TITLE
Wrong product special prices in multistore setup

### ISSUE THREAD

**Issue by mlemanczyk** [PrestaShop/PrestaShop#20780] opened 2020-08-28 17:22 UTC
## Describe the bug
In multistore setup, it's very tricky for me to get the final price for a product in a given store. Product->getFinalPrice() doesn't respect the shop ID the product was loaded with. It provides a value calculated based on special price defined for another shop.

When executed in a context of the website, Product::getPriceStatic() always requires cart ID, yet still provides wrong results, based on special price rule defined for another store.

Product::priceCalculation() doesn't include tax defined for the product.

#### Expected behavior
When a product is loaded with shop ID passed to the constructor, `Product->getFinalPrice()` must respect it and calculate final price for the store it was loaded.

`Product::getPriceStatic()` shouldn't require cart_id, even if it's used in the context of the website. It should return correct price, for the current shop, excluding special prices defined for another store. We have a PHP script that is called with AJAX call on the product page, after user clicks a button. It loads the product and gets the prices. Even that the context is within website, it's unrelated to cart and cart ID shouldn't be required. Currently it raises error that a cart ID must be specified. Even if you specify cart ID, it calculates the price applying special price rule defined in the product for another store.

`Product::priceCalculation()`, when $useTax == 1 should always return the price with tax, if tax ID was defined for a product, regardless if address is known, or not. At the time when a customer visits the store, we may not know his address. This part of the code seems to fail:
```
$tax_manager = TaxManagerFactory::getManager($address, Product::getIdTaxRulesGroupByIdProduct((int) $id_product, $context));

        if(isset($_COOKIE['product-' . $id_product])){
            $tax_manager = TaxManagerFactory::getManager($address, (int)$_COOKIE['product-' . $id_product]);
        }

        $product_tax_calculator = $tax_manager->getTaxCalculator();

        // Add Tax
        if ($use_tax) {
            $price = $product_tax_calculator->addTaxes($price);
        }
```

Because `Product::priceCalculation` was failing to calculate correctly, I've copied it to my PHP script (without COOKIE case) and tried to use directly. When I passed "null" as the address an exception was raised. When I passed "empty" instance of Address (created with `new Address()`) the tax is not added, too.

#### Steps to Reproduce

1. Define 2 shops. Let's assume `id_shop1 `& `id_shop2`
2. Create a product available in both shops. Let's assume id_product
3. Set price for the product, the same for both shops
4. Define special price rule that applies only to `id_shop2`. My special rule was based on percentage, but it also defined original price.
5. Load product using `$product = new Product(id_product, false, null, id_shop1`
6. From your product.tpl in `id_shop1`  make an AJAX call to a PHP script, that calls `$product->getFinalPrice()` - returned price includes discount from `id_shop2`
7. From your product.tpl in `id_shop1  `make an AJAX call to a PHP script, that calls `Product::getPriceStatic()` passing null as `id_cart` - exception raised
8. From your product.tpl in `id_shop1` make an AJAX call to a PHP script, that calls `Product::getPriceStatic()` passing `Context::getContext()->cart->id` as `id_cart` parameter - returned price includes discount from `id_shop2`
9. From your product.tpl in `id_shop1` make an AJAX call to a PHP script, that calls `Product::priceCalculation()` passing `true` as `$useTax` parameter - price doesn't include tax.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.32

**Comment by khouloudbelguith** [comment] 2020-08-31 09:51
Hi @mlemanczyk,

Thanks for your report.
>From your product.tpl in id_shop1 make an AJAX call to a PHP script, that calls $product->getFinalPrice() - returned price includes discount from id_shop2

Could you please provide us the exact modification that you made in the `product.tpl` file.
A copy-paste of the file could help us to reproduce the issue.

Thanks!

**Comment by sarahdib** [comment] 2020-09-21 09:49
Hello

Since we had no news from you, I'll close this ticket. Feel free to open another one if you can provide more details.

Thank you!

**Closed as completed by sarahdib** 2020-09-21 09:49 UTC
Labels: Bug, Multistore, Taxes and Prices, No change required, 1.7.6.4
