### ISSUE TITLE
[IMPROVEMENT] Add hooks to cart modal - crosseling and promotion

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#17709] opened 2020-02-18 10:53 UTC
Hi, it would be nice if you would add a two useful hooks to the cart modal.

**Cart modal extra information - e.g. displayCartModalExtra**
Hook inside the cart modal, to show information like promotions. For example, it could be used to display a messages like: ORDER FOR 20 EUR MORE AND GET FREE SHIPPING!
![shipping](https://user-images.githubusercontent.com/6097524/74728500-2d07e500-5243-11ea-85eb-0b9769f50549.JPG)

**Cart modal crosseling (this hook was present in 1.6 - e.g. displayCartModalCrossselling**
Hook for displaying cross selling in product cart modal, so the user sees it right away. Currently, only crosseliing hook is on cart page.
![cross-selling-manual-related-product-with-add-to-cart](https://user-images.githubusercontent.com/6097524/74729429-c08de580-5244-11ea-95b4-b43a026e6002.jpg)

**Comment by khouloudbelguith** [comment] 2020-02-18 11:07
Hi @Hlavtox,

Thanks for your report.
![image](https://user-images.githubusercontent.com/16067358/74730782-12376f80-5247-11ea-9ba9-04efc9780894.png)
Ping @PrestaShop/prestashop-product-team @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by matks** [comment] 2020-02-18 14:12
Looks like it used to be a todo-item in https://github.com/PrestaShop/ps_shoppingcart/

See https://github.com/PrestaShop/ps_shoppingcart/pull/47/files : I found some very old `@todo`

On tech side, no issue to add these hooks. Just need a go from Product team

**Comment by colinegin** [comment] 2020-02-19 08:44
Let's do it ! :)

**Comment by colinegin** [comment] 2020-06-17 14:40
The issue #16969 is a duplicate of this one.

Specs :

If https://github.com/PrestaShop/ps_crossselling is installed too, then we can display the "Customers who bought this product also bought..." block into the shopping cart modal into https://github.com/PrestaShop/ps_shoppingcart/blob/master/modal.tpl#L4

**Closed as completed** 2020-10-13 14:10 UTC
Labels: Improvement, PM ✔️, CO, Cross selling, Fixed, ps_shoppingcart
