### ISSUE TITLE
False product stock value after updating the Cart in backoffice

### ISSUE THREAD

**Issue by michael-ritsch** [PrestaShop/PrestaShop#28669] opened 2022-06-03 08:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1. Go to an Order in Backoffice
2. In the order add a product(stock=10) to the cart, then stock is 9.
3. delete the product from the cart, then stock is still 9 instead of the previous value 10
4. you need to reload the page manually to see the right stock value

There should be a JS function that updates that value without an reload.

### Expected behavior

1. Go to an Order in Backoffice
2. In the order add a product(stock=10) to the cart, then stock is 9.
3. delete the product from the cart, then stock has its previous value 10, without a manually reload

### Steps to reproduce

1. Go to an Order in Backoffice
2. In the order add a product(stock=10) to the cart, then stock is 9.
3. delete the product from the cart, then stock is still 9 instead of the previous value 10
4. you need to reload the page manually to see the right stock value

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.29

**Comment by hibatallahAouadni** [comment] 2022-06-03 17:38
Hello @michael-ritsch 

I didn't manage to reproduce the issue with the provided infos, could you please provide screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by michael-ritsch** [comment] 2022-06-08 05:48
Hi, here are some Screenshots that show how to reproduce this behaviour:

![Bildschirmfoto 2022-06-08 um 07 44 23](https://user-images.githubusercontent.com/55855825/172541049-32acb2b3-b02b-44d0-b6d0-e74b59bdfdbd.png)
![Bildschirmfoto 2022-06-08 um 07 46 00](https://user-images.githubusercontent.com/55855825/172541120-334cb94f-862a-4253-8739-13714d9ee9c0.png)
![Bildschirmfoto 2022-06-08 um 07 46 19](https://user-images.githubusercontent.com/55855825/172541129-8b67d298-fe5b-4b7b-a282-7d8b353731d8.png)
![Bildschirmfoto 2022-06-08 um 07 46 39](https://user-images.githubusercontent.com/55855825/172541142-dd038273-86a5-4dae-80e4-8f16763e4a0b.png)
![Bildschirmfoto 2022-06-08 um 07 46 54](https://user-images.githubusercontent.com/55855825/172541152-8753db97-b19e-4c3f-b859-deca8c3e3e52.png)

**Comment by hibatallahAouadni** [comment] 2022-06-08 17:05
Hello @michael-ritsch 

Thanks for the screenshots :pray: 
I see what you mean, I think we may encountered this issue, could you please check this issue #19454 it seems related to yours.
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-06-28 15:42
Hello @michael-ritsch 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-06-28 15:42 UTC
Labels: Bug, BO, Order, Stocks, Invalid
