### ISSUE TITLE
ps_facetedsearch v3.2.0: out of stock combinations are still shown

### ISSUE THREAD

**Issue by Twabi2** [PrestaShop/PrestaShop#15220] opened 2019-08-22 13:36 UTC
**Describe the bug**
When applying a filter using faceted search, products that match the filter are always shown, even if that specific combination is out of stock / unavailable to order. For example, searching for a product in size M and color red shows all products that have the features M and red, even if that specific combination is out of stock.

**To Reproduce**
I have tested this using a clean installation of PS 1.7.6.0, using the demo products already there.
1. Go to products in BO 
2. Click on product "Hummingbird printed shirt"
3. Go to "Combinations" tab
4. Set quantity for the first 2 combinations ("Size - S, Color - White" and "Size - S, Color - Black") to 0
5. Click Save
6. In the FO, go to the Men's category
7. On the left, apply filter for size S
8. Despite having no stock available in size S, the product is still shown

**Screenshots**
For example, this product has combinations with sizes XS and M, but only XS is still available, and should thus not be shown after filtering on size M
![image](https://user-images.githubusercontent.com/52446146/63518091-930feb80-c4f0-11e9-962e-0c6b18d954a5.png)

**Additional information**
PrestaShop version: 1.7.6.0
ps_facetedsearch version: 3.2.0
PHP version: 7.2.17

**Comment by khouloudbelguith** [comment] 2019-08-22 13:50
Hi @Twabi2,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15056
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-08-22 13:50
Duplicate of #15056

**Closed as completed by khouloudbelguith** 2019-08-22 13:50 UTC
Labels: Duplicate
