### ISSUE TITLE
BO - Category - SEO preview for Friendly URL doesn't update for Home category

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31356] opened 2023-02-14 15:03 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The friendly URL is "undefined" it should be updated with "hellohome" in my case.
The error occurs only on category Home, for the other categories, it works as expected.

<img width="894" alt="Screenshot 2023-02-14 at 15 53 28" src="https://user-images.githubusercontent.com/16019289/218775102-08bb965c-6425-474f-bb17-eed36949d9d5.png">

This is not a regression, the same issue happens on 1.7.8.8.

### Expected behavior

It should be updated with whatever the merchant put in the field.

In the FO, the URL is correct.

### Steps to reproduce

1. Go to BO > Catalog > Categories > Edit Home Category
2. See SEO Preview - 2-undefined :x:
3. Edit  Friendly URL
4. See SEO Preview - 2-undefined is not updated :x:

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment] 2023-02-16 02:30
Hello @florine2623 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15420. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-02-16 02:30
Duplicate of #15420

**Closed as completed by hibatallahAouadni** 2023-02-16 02:30 UTC
Labels: Bug, BO, Duplicate, Categories, Invalid, 8.1.x
