### ISSUE TITLE
Backoffice order list and edit broken after upgrade from 1.7.x.x to 1.7.7.1

### ISSUE THREAD

**Issue by ComonSoft** [PrestaShop/PrestaShop#23254] opened 2021-02-13 22:29 UTC
After upgrading Prestashop 1.7.4.5 upgrade to 1.7.6.4 and upgrade to 1.7.7.1 with autoupgrade, orders backoffice screens are broken (status selector, tabs...) see screenshots . Same issue after clearing Prestashop and browser cache.

1. autoupgrade from 1.7.x.x to 1.7.7.1
2. connect to backoffice
3. clear cache
4. Goto orders
5. Edit order

Capture orders list KO
![Capture-KO](https://user-images.githubusercontent.com/13507563/107885564-5f522e00-6efb-11eb-8af4-45a2fa388658.JPG)
Should be capture orders list OK
![Capture-OK](https://user-images.githubusercontent.com/13507563/107885582-75f88500-6efb-11eb-8723-24b364c298ff.JPG)
Bad order edit
![Capture1](https://user-images.githubusercontent.com/13507563/107863250-f1eac280-6e52-11eb-94f9-d646d6fdc408.JPG)

* PrestaShop version: 1.7.7.1
* PHP version: 7.2.1

**Cause :** after upgrade, the file /js/admin/orders.js is not deleted (not present in a fresh install).
**Solution:** add deletion of this file in upgrade module. Manualy delete the file solve the issue.

The file /js/admin/orders.js was present in previous version as you can see https://github.com/PrestaShop/PrestaShop/tree/1.7.4.x/js/admin and should be delete in autoupgrade module.

**Comment by ComonSoft** [comment] 2021-02-14 09:14
Forget it, it was a non Prestashop module, that cause the issue. Sorry.

**Comment by hibatallahAouadni** [comment] 2021-02-16 10:06
Hello @ComonSoft 

Sorry for the late response.
Regarding the first issue, I couldn't reproduce :confused: did you override some CSS files? are there any JS errors thrown?
About the second issue, try to clear cache and refresh the page several times.

Please check and feedback.
Thanks!

**Comment by ComonSoft** [comment] 2021-02-16 11:06
Hi, in fact it was a Prestashop 1.7.4.5 migrate to 1.7.6.4 and migrate to 1.7.7.1, so the /js/admin/orders.js was present in previous version as you can see https://github.com/PrestaShop/PrestaShop/tree/1.7.4.x/js/admin 

Regards

**Comment by hibatallahAouadni** [comment] 2021-02-16 11:28
Hello @ComonSoft 

>  are there any JS errors thrown?

I meant, please open your navigator console and check if is there any error thrown.

> try to clear cache and refresh the page several times.

Did you try it? do you still encounter the second issue?

Please check and feedback.
Thanks!

**Comment by ComonSoft** [comment] 2021-02-16 13:29
No js errors, test in a private navigation . Just a side js effect, due to this old js file concatened.

**Comment by hibatallahAouadni** [comment] 2021-02-17 11:00
Hello @ComonSoft 

Thanks for the feedback!
About the second issue, did you try to clear cache and refresh the page several times, has the issue been resolved?
Please check and feedback.

Thanks!

**Comment by ComonSoft** [comment] 2021-02-17 11:07
Of course! The only solution is to delete the file, because Prestashop backoffice loader concatenate all js files present in /js/admin/ in one file.
Regards

**Comment by hibatallahAouadni** [comment] 2021-02-17 13:09
Hello @ComonSoft 

So, the first issue I couldn't reproduce and the second issue is resolved.
Well, if you could provide more information to help me reproduce the first issue.
Otherwise, I have to close the issue :wink: 

Thanks!

**Comment by ComonSoft** [comment] 2021-02-17 18:02
I change the 1rst issue, beacause it only one, I change the context.

**Comment by hibatallahAouadni** [comment] 2021-02-18 11:21
Hello @ComonSoft 

I manage to reproduce your issue with My shop 1.7.6.9 upgraded to PS1.7.7.1 but after several refresh, the issue is gone.
See the attached screen record below (from 2:45):

https://drive.google.com/file/d/1qfGEzcGyHP_grAg24Slleq4uJSZVygGm/view

Please check and feedback.
Thanks!

**Comment by ComonSoft** [comment] 2021-02-18 14:01
Hum, as explained we migrate from 1.7.4.5 not from the latest 1.7.6.9 ;-)

**Comment by hibatallahAouadni** [comment] 2021-02-22 08:17
Hello @ComonSoft 

Do you mean 1.7.4.4? cause there's no 1.7.4.5 (see the attached screenshot below)

![image](https://user-images.githubusercontent.com/23308427/108680934-c456e680-74ee-11eb-943a-b30ca9681903.png)

Please check and feedback.
Thanks!

**Comment by ComonSoft** [comment] 2021-02-22 09:56
Yes you right, it was 1.7.4.4 ;-)

**Comment by hibatallahAouadni** [comment] 2021-02-23 10:43
@ComonSoft just to confirm, you upgraded your shop from 1.7.4.4 to 1.7.7.1? or to another version?

**Comment by ComonSoft** [comment] 2021-02-23 10:46
From 1.7.4.4 to 1.7.6.9 and then to 1.7.7.1

**Comment by hibatallahAouadni** [comment] 2021-02-23 19:42
Hello @ComonSoft 

I install a new shop 1.7.4.4, I upgrade it to 1.7.6.9 and then upgrade it again to 1.7.7.1:

https://drive.google.com/file/d/1E5lf_YMvMdPrENXhGLKV4Y-rkEshpT1y/view

As you can see in the attached screen record above, I did encounter your issue but when I refresh my page, it's all set :wink: 
Please check and feedback.

Thanks!

**Comment by ComonSoft** [comment] 2021-02-24 09:10
OK @hibatallahAouadni forget it if you can't reproduce.

**Comment by hibatallahAouadni** [comment] 2021-02-24 09:15
Hello @ComonSoft 

I'm really sorry I tried my best to reproduce the issue but ...
Well, I have to close the issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-02-24 09:15 UTC
Labels: Bug, BO, Can't reproduce, Order, Back-end, 1.7.7.1
