### ISSUE TITLE
Ps 1.7.6.0 not saving category position

### ISSUE THREAD

**Issue by CaseOnline** [PrestaShop/PrestaShop#15208] opened 2019-08-21 18:31 UTC
Problem with drag and shop category position. Ps says save but not changing category order...

Don't know if this is a bug or some settings but it's impossible to change.

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-08-22 07:50
Hi @CaseOnline,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14529 to fix the issue.
It is fixed in the PS1.7.7.
Your ticket is a duplicate of #14504
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-22 07:50
Duplicate of #14504

**Closed as completed by khouloudbelguith** 2019-08-22 07:50 UTC
Labels: Duplicate
