### ISSUE TITLE
Can't disable or uninstall modules in Module Manager after upgrade PS from 1.7.6.9 to 1.7.7.0

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#22485] opened 2020-12-17 20:45 UTC
After upgrade from PS 1.7.6.9 with one clik upgrade, the update module panel and module installation stop working.

Error:

->modules -> update any module pending to be updated or try to install a new module (it does not work)

This PS is not a fresh installation, we upgrade from 1.7.6.4 -> 1.7.6.5 -> 1.7.6.7 -> 1.7.6.9 -> 1.7.7.0

There is no error on PHP logs

There is this error on PS logs:
{"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Cannot redeclare sendRequest() (previously declared in /var/www/vhosts/xxxxx/xxxxx/modules/emarketing/upgrade/Upgrade-2.2.0.php:51) at /var/www/vhosts/xxxxxxx/xxxxxxx/modules/emarketing/upgrade/Upgrade-2.2.1.php:78)"} []

After finish upgrading the PS we had this error:

SQL 1.7.7.0 1146 in ALTER TABLE `ps_pagenotfound` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'xxxxxxxxx.ps_pagenotfound' doesn't exist

---
#### Describe the bug
I upgrade my shop from 1.7.6.9 to 1.7.7.0 without problems. But, everytime I try to disable or to uninstall any module, an error is displayed

_**PS: I can install, upgrade and configure any module in the list but I can't disable or uninstall**_ 

#### Expected the behavior
I can uninstall and disable any module after upgrading my shop without any problem

#### Steps to reproduce
1. Fresh install **PS1.7.6.9** 
2. Upgrade the shop to **PS1.7.7.0** with **1-click upgrade** module
3. **BO**>**IMPROVE**>**Module Manager**
4. Try to disable or unistall any module in the list
5. **An error is displayed**

#### Screenshots
https://drive.google.com/file/d/1P_zr_oqzbMMYi6x0-_bUTYfZ96TEHp41/view

#### Additional informations

- PrestaShop version: 1.7.7.0
- PHP version: 7.2 (we try 7.3 same issue)

**Comment by PululuK** [comment] 2020-12-17 22:25
Hi @msaustral 

Fixed here I think : https://github.com/PrestaShop/PrestaShop/pull/21975

Can you check please ?

**Comment by msaustral** [comment] 2020-12-17 22:37
Hi @PululuK that fix is already done on the 1.7.7.0 stable .zip can you confirm if it is the same .zip that uses 1 click update module?

**Comment by florine2623** [comment] 2020-12-18 12:53
Hello @msaustral ,
The zip used by 1-click upgrade is the zip of 1.7.7.0 stable version.
Thanks

**Comment by msaustral** [comment] 2020-12-18 14:02
Hi Florine, thank you, please help, we do have a issue https://github.com/PrestaShop/PrestaShop/issues/9932 with a customer, the address duplicate as costumer click more than one time on continue and a no carrier message appear.

This is solve on the 1.7.7.0 but we can not upgrade!, any idea?

**Comment by hibatallahAouadni** [comment] 2020-12-22 16:23
Hello @msaustral 

> Hi Florine, thank you, please help, we do have a issue https://github.com/PrestaShop/PrestaShop/issues/9932 with a customer, the address duplicate as costumer click more than one time on continue and a no carrier message appear.

To fix that problem without upgrading your shop, use the fix in this PR #15399
Hope it helps.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-22 16:25
Hello @msaustral 

Do you confirm that your issue is a duplicate of #21948?

**Comment by msaustral** [comment] 2020-12-22 16:59
Hi @hibatallahAouadni 
- this fix https://github.com/PrestaShop/PrestaShop/issues/9932 does not solve the issue 
- on this link #15399 only say that will be fix on the 1.7.7.0 with no details on how to fix it
- the #21948 case refers to an issue during installation with alter table, when we try to install we got an error of ps_pagenotfound not exist, but it does not have to affect any manager module functionalities

-  this case is an issue with the module manager after upgrade to the 1.7.7.0, it stop working, you can not install or update any module.

**Comment by hibatallahAouadni** [comment] 2020-12-23 11:02
Hello @msaustral 

In this issue, you post two problems:

- upgrade issue 
- address issue

This is not acceptable, you shouldn't conflict us with multiple issues.

First, you need to update your issue description **following our template to submit a complete bug report**.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

> on this link #15399 only say that will be fix on the 1.7.7.0 with no details on how to fix it

Second, it seems that you misunderstood me. In the attached PR above, you can find the changes made in **Files changed** tab and to adopt this fix you need to override the changed file and add the fix.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one
of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by msaustral** [comment] 2020-12-23 18:59
Hi @hibatallahAouadni please forget about the alter table error, please help us to solve the module manager issue.

It stop working after upgrade.

**Comment by hibatallahAouadni** [comment] 2020-12-23 19:23
Hello @msaustral 

Could you please provide some screenshots or screen record about the issue.

When you said the module manager issue, do you mean that the whole page doesn't work or just the 1-click upgrade module doesn't work?

Thanks!

**Comment by msaustral** [comment] 2020-12-23 19:26
hi @hibatallahAouadni as we describe on the description, the whole module manager does not work:

->modules -> update any module pending to be updated or try to install a new module (it does not work)

you can not install or update any module.

There is no error on PHP logs

There is this error on PS logs:
{"exception":"[object] (Symfony\Component\Debug\Exception\FatalErrorException(code: 0): Compile Error: Cannot redeclare sendRequest() (previously declared in /var/www/vhosts/xxxxx/xxxxx/modules/emarketing/upgrade/Upgrade-2.2.0.php:51) at /var/www/vhosts/xxxxxxx/xxxxxxx/modules/emarketing/upgrade/Upgrade-2.2.1.php:78)"} []

there is no error, just it does not work

**Comment by hibatallahAouadni** [comment] 2020-12-24 13:41
Hello @msaustral 

I managed to reproduce your issue, I upgrade my shop from 1.7.6.9 to 1.7.7.0 without problems. But, everytime I try to disable or to uninstall any module, an error is displayed :confounded: 

1. Fresh install PS1.7.6.9 
2. Upgrade the shop to PS1.7.7.0 with 1-click upgrade module
3. BO>IMPROVE>Module Manager
4. Try to disable or unistall any module in the list => **An error is displayed**

See the attached screen record below:
https://drive.google.com/file/d/1P_zr_oqzbMMYi6x0-_bUTYfZ96TEHp41/view

_**PS: I can install and configure any module in the list but I can't disable or uninstall**_ 

@msaustral Thanks for your clarifications, I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by msaustral** [comment] 2020-12-24 13:53
Hi @hibatallahAouadni nice, in our installation does not display any error, we try to install a new module, the window to upload the file pop up but it does not work.

**Comment by hibatallahAouadni** [comment] 2020-12-24 14:04
Hello @msaustral 

In my case, I can install and configure, see the attached screen record below:

https://drive.google.com/file/d/14fXiuatvYPlvn7TtB7sf1G38DTjwV7Rl/view

Thanks!

**Comment by msaustral** [comment] 2020-12-24 14:11
Hi @hibatallahAouadni is there a private way to give you access to our customer test ev so you can see the issue?

**Comment by hibatallahAouadni** [comment] 2020-12-24 14:15
Hello @msaustral 

Sorry but I'm not allowed to offer Support.
If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Thank you

**Comment by msaustral** [comment] 2020-12-24 14:31
Hi @hibatallahAouadni we do not ask for support, we just want to show you the issue so you can fix it in next ver

**Comment by hibatallahAouadni** [comment] 2020-12-24 15:09
Hello @msaustral 

Just make a screen record and share it here :wink:

Thanks!

**Comment by ArtGee** [comment] 2020-12-28 14:17
I have the same issue. The problem is that the same method sendRequest is declared multiple times in different files (in my case in Upgrade-2.0.0.php, Upgrade-2.2.0.php, Upgrade-2.2.1.php) inside the folder modules/emarketing/upgrade. I assume that these files are included by the Prestashop Upgrader and thus throw this exception. The possible solution could be encapsulating the source inside a class or renaming the method sendRequest for each of the versions.

**Comment by hibatallahAouadni** [comment] 2020-12-29 09:04
Hello @ArtGee 

Thanks for your proposition! This issue is already in our debug backlog and we're working on it.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by LouiseBonnard** [comment] 2021-01-04 13:18
Hi @hibatallahAouadni, can you confirm it is related to the PrestaShop Ads (emarketing as technical name) module? Our partnership is supposed to have ended.

**Comment by hibatallahAouadni** [comment] 2021-01-04 13:43
Hello @LouiseBonnard 

> Try to disable or unistall any module in the list => An error is displayed
It's not related to PrestaShop Ads, I already tried to disable or uninstall any module, see the attached screen record below:

https://drive.google.com/file/d/1ki3Uzi0iZyE4ssN-ZUE4d-goaBWd2Wb5/view

I tried to disable Best Categories module, the system display an error.
That's with PS1.7.5.2 -> upgraded to PS1.7.7.0

---
I tried with PS1.7.5.2 => upgraded to PS1.7.7.1 (first build)
I had no issue :tada: See screen record below:

https://drive.google.com/file/d/1j6IaRJPfOxay0xP3yThVmEIp7NQ4YNXt/view

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-05 10:51
Hello @msaustral 

I close this issue cause it's fixed with our next patch release 1.7.7.1 :tada: 
Stay tuned for it :wink: 

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-05 10:51 UTC
Labels: Bug, Minor, BO, Autoupgrade, Fixed, Module manager, 1.7.7.0

**Comment by agnesdennetiere** [comment] 2021-07-08 09:54
Hello,

is there a way to add a patch to a previous version of Prestashop without upgrading completely?
Is there a commit which fixes this?
Thank you

**Comment by msaustral** [comment] 2021-07-08 15:44
Hi @agnesdennetiere you can do it by creating a folder, place all file of the previus ver. then point a subdomain to that folder.

Remember to change the domain on the DB, clear cache and change access to the new Data Base
