### ISSUE TITLE
Some admin functions are suddenly timing out - 504

### ISSUE THREAD

**Issue by Henrik41** [PrestaShop/PrestaShop#17058] opened 2020-01-08 03:12 UTC
Everything was working great until some backend function start giving me an upstream timeout.
i.e: Changing the status of orders in bulk result in an upstream timeout. Same thing when I create an order from the backend I get a timeout (504).

Using 
Prestashop 1.7.6.0
php 7.2
Nginx/php-fmp

I am pretty sure my php-fmp and Nginx are configure correctly and I never had an issue.

If I increase my fastcgi_read_timeout 1200;
I get into an infinie loop and I wait for ages.

The only significant I got was the error log:

2020/01/07 21:39:57 [error] 13323#13323: *18 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xx.xx.xx.xx, server: xxx.com, request: "POST /adminxxxxx/index.php?controller=AdminOrders&submitBulkupdateOrderStatusorder&token=e834cef82644903a0c24c345136a35e HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "xxxxx.com", referrer: "https://xxxx.com/adminxxxxx/index.php?controller=AdminOrders&submitBulkupdateOrderStatusorder&token=e834cef82644903a0c24c345136a35e"

**Comment by khouloudbelguith** [comment] 2020-01-08 09:51
Hi @Henrik41,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2.
Here's my Nginx conf
```
#user  nobody;
worker_processes auto;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout 2;
	client_max_body_size 100m;

    server_tokens off;
    #gzip  on;
    fastcgi_read_timeout 600;
    include /etc/nginx/sites-enabled/*;
}
#daemon off;
```
I attached a screen record
https://drive.google.com/file/d/1h8KSmGhbU5xtSIuSdlrNAFs0opg5oAeX/view
In your php.ini file, Try to increase:

```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```
Thanks to check & feedback

**Comment by Henrik41** [comment] 2020-01-08 11:35
Hi Khouloudvelguith,
  Thank you for looking this up. I found that the cupid was actually that Prestashop was unable to send emails from my Postfix. After disabling the emails the 504 disappeared.

  Than you again for your patience and great feedback.

**Comment by khouloudbelguith** [comment] 2020-01-08 12:52
@Henrik41, thanks for your feedback.
Since it is fixed, I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-08 12:52 UTC
Labels: Bug, BO, Order, No change required, 1.7.6.0
