### ISSUE TITLE
Faceted search doesn't work properly

### ISSUE THREAD

**Issue by damianobertuna** [PrestaShop/PrestaShop#12575] opened 2019-02-14 16:49 UTC
**Describe the bug**
It happens that if I select a filter and then I select another filter the first one disappear (it is not active anymore).

**To Reproduce**
1. Go to a category
2. Click on one filter and wait for products reload
3. Scroll down to filter and try to select another filter
4. After products reload only the second filter il active, the first is not active anymore. After this, if I choose again the first filter, it remains properly.
![faceted_search_error_1](https://user-images.githubusercontent.com/9989581/52802704-c4f74f80-3080-11e9-9247-5495bddad17d.PNG)
![faceted_search_error_2](https://user-images.githubusercontent.com/9989581/52802705-c4f74f80-3080-11e9-814e-581a4bc48d30.PNG)
![faceted_search_error_3](https://user-images.githubusercontent.com/9989581/52802706-c58fe600-3080-11e9-894c-532056f42087.PNG)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-02-14 17:04
Hi @damianobertuna,

I did not manage to reproduce the issue with PS1.7.5.0, default theme, & the ps_facetedsearch v2.2.0 - by PrestaShop.
I attached a video record.
https://drive.google.com/file/d/1UUaznto5zDTxKOV1uyvAQjd6jKyEtnv9/view
Thanks to check & feedback.

**Comment by sonosergio** [comment] 2019-02-15 08:45
Hi @khouloudbelguith 
can you try the "drop down menu" option?
![cattura_1](https://user-images.githubusercontent.com/5682550/52845033-5eb51000-3106-11e9-8d9d-0af67b294d35.PNG)

**Comment by khouloudbelguith** [comment] 2019-02-15 10:17
Hi @sonosergio,

Thanks a lot for your feedback.
In the ps_facetedsearch configuration page, I edited to "Filter style:" to "Drop-down list" 
![image](https://user-images.githubusercontent.com/16067358/52849788-27e4f700-3112-11e9-88ac-e8b4201d8f6b.png)
In the FO, when I try to use more than two filters, the first filter is not active anymore, only the second filter.
Which not the same case, when I use "Filter style" => "checkbox" for the first filter selected.
https://drive.google.com/file/d/16b1WNMLmyvLsqPLGQqEM-w-uDQMQRjvj/view
Ping @marionf what do you think?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-15 10:23
I have the same issue with PS1.7.4.4 & the ps_facetedsearch module v2.2.1.
Thanks!

**Comment by marionf** [comment] 2019-02-20 11:26
@khouloudbelguith it seems a duplicate of #9647 ?

**Comment by khouloudbelguith** [comment] 2019-02-20 11:36
@marionf, thanks, yes it is a duplicate.
More details in this comment: https://github.com/PrestaShop/PrestaShop/issues/9647#issuecomment-415055253

@damianobertuna, the issue is added to our debug roadmap.
Your ticket is a duplicate of #9647
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-20 11:37
Duplicate of #9647

**Closed as completed by khouloudbelguith** 2019-02-20 11:36 UTC
Labels: Bug, Minor, FO, Duplicate, Faceted search, 1.7.5.0
