### ISSUE TITLE
Reorder Product from previous order when not available

### ISSUE THREAD

**Issue by NereoEgeo** [PrestaShop/PrestaShop#17339] opened 2020-01-24 10:09 UTC
Hello,

in the 1.7.6.1 PS version, when I was trying to reorder a product from a previous order in my account menu, if the product was not more available (Behavior when out of stock Deny orders), Prestashop showed the available products in the cart and for that one not more available you would get a notice.
Now, in the 1.7.6.2 if I try to do the same, Prestashop sends you directly in the home page, without any further notice and with an empty cart.
I tryed with a new default prestashop installation without any customizations and the behavior is the same.

Set a product quantity in admin to 1 with Behavior when out of stock Deny orders
Simulate a purchase of this product
Go to My account - Order History and Details 
Click on Reorder
Redirect in home page with a empty cart and no notice

PrestaShop version: 1.7.6.2
PHP version: 7.2.26
Versione MySQL: 5.7.27-30-log

**Comment by khouloudbelguith** [comment] 2020-01-24 10:17
Hi @NereoEgeo,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9660
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-01-24 10:18
Duplicate of #9660

**Closed as completed by khouloudbelguith** 2020-01-24 10:17 UTC
Labels: Duplicate

**Comment by NereoEgeo** [comment] 2020-01-24 10:50
thank you and sorry for the duplicate
