### ISSUE TITLE
Access denied for Catalogue -> Stock Manager for a non Admin user

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#19079] opened 2020-05-11 18:43 UTC
Hi, when you add any non super admin profile to an employee user, then give full access to Stocks manager, it give an access denied error when you log in with that employee user and try to access Stocks section.

1.- create a new user
2.- place ir on a not super admin profile
3.- enable all permission for Catalogue -> stocks
4.- access the back office with that user employee`s
5.- click on Catalogue -> stocks

There is a work around, to avoid to get the access denied error, the translation section must have at least view permition.
   
* PrestaShop version: 1.7.6.5

![ps-1](https://user-images.githubusercontent.com/46203943/81598236-f995ac00-9394-11ea-99a6-e143ee64d25a.png)

![ps-2](https://user-images.githubusercontent.com/46203943/81598244-fd293300-9394-11ea-978b-4bea3efb56ca.png)

![ps-3](https://user-images.githubusercontent.com/46203943/81598253-01555080-9395-11ea-98bc-58a90cb8e642.png)

![ps-4](https://user-images.githubusercontent.com/46203943/81598268-04e8d780-9395-11ea-9c8b-66d5c9d2fd20.png)

**Comment by PululuK** [comment] 2020-05-11 18:51
Maybe related to that : https://github.com/PrestaShop/PrestaShop/issues/19077

**Comment by msaustral** [comment] 2020-05-11 19:05
Hi PululuK, in this case it only the stocks section and to show it no need to have permitios to user profiles.

**Comment by florine2623** [comment] 2020-05-12 14:42
Hi @msaustral ,
I managed to reproduce your issue in both PS 1.7.6.5. and PS 1.7.7.
I will let our dev team know about this.

Thanks!

**Comment by colinegin** [comment] 2020-06-11 15:07
ping @florine2623 could you test if this is a regression of 1.7.6 ?
Thanks !

**Comment by colinegin** [comment] 2020-06-15 09:47
Thanks @msaustral for warning us !
As this issue is a duplicate of #19713 , I will close it so that we can all focus on the same issue and follow its fix. You can now follow #19713 
Thanks !

**Closed as completed by colinegin** 2020-06-15 09:47 UTC
Labels: Bug, Major, BO, Duplicate, Employees, Permissions, 1.7.7.0, 1.7.6.5
