### ISSUE TITLE
The feedback form don`t work

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#15464] opened 2019-09-07 21:51 UTC
**Describe the bug**
There is the form of feedback to webmaster or tech support in the shop. It configure in the Settings->Contacts
This form doesn`t work (not send the letters)
![image](https://user-images.githubusercontent.com/50954519/64480562-9256a500-d1d2-11e9-822a-a043f3cc3a0a.png)

The error is When you send an error has occurred. Try again.
The letters with orders are come OK

PS 1.7.5.2

In the debud mode the next errors

at FrontControllerCore->initContent()in ContactController.php line 38
--
at ContactControllerCore->initContent()in Controller.php line 281

In the BO->Modules->Contacts-> both buttons are turn ON
![image](https://user-images.githubusercontent.com/50954519/64487581-f7e37980-d244-11e9-807c-2ea8910ffbf4.png)

**Comment by khouloudbelguith** [comment] 2019-09-09 08:43
Hi @photinia73,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9566
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-09 08:43
Duplicate of #9566

**Closed as completed by khouloudbelguith** 2019-09-09 08:43 UTC
Labels: Duplicate

**Comment by photinia73** [comment] 2019-09-09 10:41
I find this night such desition 
} elseif (
            // $url !== ''
            empty($serverToken)
            // || $clientToken !== $serverToken
            // || $clientTokenTTL < time()
        ) {﻿

BUT. If everyone know that the version 4.1.1 does not work, why nobody decide this problem? Where is update with fixed error?

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: понедельник, 9 сентября 2019 г. в 11:43
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] The feedback form don`t work (#15464)

Duplicate of #9566

**Comment by khouloudbelguith** [comment] 2019-09-09 11:43
@photinia73, this issue is randomly reproduced & it is added to our bug roadmap.

Thanks for your understanding!

**Comment by photinia73** [comment] 2019-09-09 12:14
Ok, thank you

З повагою
Кричмарівська Світлана

От: khouloudbelguith
Отправлено: понедельник, 9 сентября 2019 г. в 14:43
Кому: PrestaShop/PrestaShop
Копия: photinia73; Mention
Тема: Re: [PrestaShop/PrestaShop] The feedback form don`t work (#15464)

@photinia73, this issue is randomly reproduced & it is added to our bug roadmap.
Thanks for your understanding!
