### ISSUE TITLE
View my shop

### ISSUE THREAD

**Issue by Fossil68** [PrestaShop/PrestaShop#23172] opened 2021-02-08 08:21 UTC
Version 1.7.7.1 functionality issue with top right hand screen (View my shop) does not permit a user to view the shop layout. Browser being utilised Safari 14.0.2 (16610.3.7.1.9) Returns the following error Safari Can't Open the Page. To many redirects occurring trying to open "thhshop.eu/en/". This might occur if you open a page that is redirected to open another page, which then is redirected to open the original page.

If there is anyone who would be able to facilitate I would be appreciated.

**Comment by hibatallahAouadni** [comment] 2021-02-08 12:34
Hello @Fossil68 

I didn't manage to reproduce your issue with PS1.7.7.1 and Safari 14, see the attached screen record below:

https://drive.google.com/file/d/1cMtjjAuWjWSSLmDnR7aox3IbfD4XPKql/view

Is this issue occured after you upgrade your Safari?
Please check and feedback.

Thanks!

**Comment by Fossil68** [comment] 2021-02-09 08:17
Hello 

I found out what the issue was

By default the system is made that the website automatically forwards to https:// when the lets encrypt certificate is installed, however this SSL redirect must be removed for PrestaShop sites as this is not a compatible service.

Thank you for your assistance

**Comment by hibatallahAouadni** [comment] 2021-02-09 12:34
Hello @Fossil68 

It seems your issue is similar to this one #12253
Could you please check it and feedback.

Thanks!

**Comment by Fossil68** [comment] 2021-02-09 12:44
It seems to be related, I had to remove the redirect to eliminate it creating a type of circular reference preventing displaying the shop front end. Once this was done the front ent displayed correctly.

**Comment by hibatallahAouadni** [comment] 2021-02-09 15:48
Hello @Fossil68 

So, your issue is not related to the type of browser, is that so?

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-01 11:49
Hello @Fossil68 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-01 11:49 UTC
Labels: Bug, FO, SEO & URLs, No change required, 1.7.7.1
