### ISSUE TITLE
Germany not available

### ISSUE THREAD

**Issue by oliverfuss** [PrestaShop/PrestaShop#15110] opened 2019-08-14 09:51 UTC
under the address view, there is no german country selection available

![Screen Shot 2019-08-14 at 11 51 02](https://user-images.githubusercontent.com/54102257/63012063-d67faf80-be89-11e9-9093-c969a93a7ac5.png)

**Comment by matks** [comment] 2019-08-14 09:58
@oliverfuss it looks like a very old PS version 🤔 which version of prestashop are you using ?

**Comment by mariem-abid** [comment] 2019-08-14 12:24
Hi @oliverfuss,

What is the exact version of Prestashop did you installed? 
Thanks to adding steps to reproduce your issue in a new comment.

**Comment by khouloudbelguith** [comment] 2019-09-13 08:45
Hi @oliverfuss,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-13 08:45 UTC
Labels: Addresses, No change required
