### ISSUE TITLE
Missing State select on Update address in Your account

### ISSUE THREAD

**Issue by mxmus** [PrestaShop/PrestaShop#35691] opened 2024-03-20 09:52 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

State select is missing in Your account when we update existing address for country with states.
![Screenshot_30](https://github.com/PrestaShop/PrestaShop/assets/10479502/706a35d6-5169-49d5-b37b-8b23d64c5e17)

### Expected behavior

State select should be presented in Your account when we update existing address for country with states.
![Screenshot_31](https://github.com/PrestaShop/PrestaShop/assets/10479502/34d0412c-8377-4c95-99fc-28a2d040755a)

### Steps to reproduce

1. Front office, default theme (https://demo.prestashop.com/#/en/front)
2. Go to Your account
3. Go to Addresses
4. Create new address (or use existing one)
5. Fill the required fields and select United States in Country select
6. Click Save button
7. Click Update on existing address with United States
8. Try to find State select box - it missing
9. Change Country to France
10. Change Country back to United States - State select box appears

### PrestaShop version(s) where the bug happened

8.1.0, 8.1.4

### PHP version(s) where the bug happened

8.1.19, 7.4.20

**Comment by AureRita** [comment] 2024-03-20 11:09
Hi @mxmus 

Thank you for your report, Currently this issue is already reported here : https://github.com/PrestaShop/PrestaShop/issues/35690

and it's also corrected on 8.1.5 with this PR : https://github.com/PrestaShop/PrestaShop/pull/35021 

I'll close the issue, 

Thank you

**Comment by AureRita** [comment] 2024-03-20 11:10
Duplicate of #35690

**Closed as completed by AureRita** 2024-03-20 11:10 UTC
Labels: Bug, Invalid
