### ISSUE TITLE
% symbol should be prohibited from db settings

### ISSUE THREAD

**Issue by xiropot** [PrestaShop/PrestaShop#15215] opened 2019-08-22 10:07 UTC
**Describe the bug**
% symbol creates an error asking for a parameter that does not exist.

**To Reproduce**
1. Make fresh install with two % symbols in the db password and a few characters between.
2. Open config/defines.inc.php.
3. Turn errors on and save.
4. Browses to either BO or FO and see the error.

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.2.21

**Comment by khouloudbelguith** [comment] 2019-08-22 10:43
Hi @tapandagr,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12556
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-08-22 10:44
Duplicate of #12556

**Closed as completed by khouloudbelguith** 2019-08-22 10:43 UTC
Labels: Duplicate
