### ISSUE TITLE
The default combination is not saved

### ISSUE THREAD

**Issue by Mreco83** [PrestaShop/PrestaShop#23294] opened 2021-02-18 08:03 UTC
Hello. I'm having a problem with saving the default combination in the store.

1. In the back office, I go to a product that has several combinations / sizes, for example S, M, L

2. I change the default combination from size S to M

3. Saves the product

4. I go to the product being changed and see no changes. Still the default size is S.

I cleared the cache and forced template compilations, but it doesn't do anything. An example product is https://yourobsession.pl/bodystocking-erotne/wzorzyste-bodystocking-sakura-cofashion

* PrestaShop version: 1.7.5.2
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment] 2021-02-18 08:13
Hello @Mreco83 

I didn't manage to reproduce your issue with PS1.7.5.2 and PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/10AAMBAJfqmjWMdTv9DZlq5L9INnqg0gW/view

Please check and feedback.
Thanks!

**Comment by Mreco83** [comment] 2021-02-18 08:17
Ok, please check the product from the front office after saving the changes. Please also change the size, but in the same color of the product. If you change the size from S to M, please change it for the product in white.

**Comment by hibatallahAouadni** [comment] 2021-02-18 08:24
Hello @Mreco83 

Following all your steps and yet I didn't reproduce it:

https://drive.google.com/file/d/1Rfm9pY7pR9TZX5VTqgKOmL7zuL6XM72D/view

Please check and feedback.
Thanks!

**Comment by Mreco83** [comment] 2021-02-18 08:28
What could be the cause of such an error? Everything seems fine and yet I can't change the default combination.

**Comment by hibatallahAouadni** [comment] 2021-02-18 16:37
Hello @Mreco83 

Sorry it's not related to PS Core, it may due to some third-module or some overrides. 
I have to close this issue, cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one
of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by hibatallahAouadni** 2021-02-18 16:37 UTC
Labels: Bug, BO, Can't reproduce, Combinations, 1.7.5.2, 1.7.7.1

**Comment by Mat-o** [comment] 2021-02-18 19:41
Did you double-check that the new default combination is properly saved in the back-end ? (by navigating elsewhere and coming back to the product page)
If not, it could be that the max_input_vars php variable is only at 1000, where it should be at least at 7000 (if many parameters are set and the descriptions are very long).

**Comment by Mreco83** [comment] 2021-02-18 20:07
Yes, I checked. The product doesn't have any description so it shouldn't matter.

**Comment by Mat-o** [comment] 2021-02-18 20:16
Your clicking on Save doesn't seem to have any effect (other than the green validation). Can you change other parameters, or values ?

**Comment by Mreco83** [comment] 2021-02-18 20:28
Yes, I can change everything, but it doesn't react to changes, only the default attribute.
Now I sent a message to my hosting provider to increase the values:
max_input_vars = up to 7000
max_execution_time = up to 300

**Comment by Mreco83** [comment] 2021-02-18 20:37
Unfortunately, the changes did not help. Still no changes visible from the front of the store.

**Comment by Mat-o** [comment] 2021-02-18 20:58
It just looks like the database is not updated.
Just after save, I would check these parameters with phpmyadmin :
- ps_product.cache_default_attribute
- ps_product_shop.cache_default_attribute
- ps_product_attribute.default_on
- ps_product_attribute_shop.default_on
to see if anyone of them has changed.
