### ISSUE TITLE
productcomments module the stars disappуared

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#26826] opened 2021-12-01 20:54 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The stars disappered in the module Product comments
![image](https://user-images.githubusercontent.com/50954519/144311521-d90cebe7-9d04-4da3-8213-6c70d950c356.png)

### Expected behavior

It will be good to see the stars again

### Steps to reproduce

Go to the page with comment
https://te.com.ua/uk/av-resiveri-procesori/529-2-yamaha-rx-v385.html#/11-kolir-chornij
Also go to the category page with product with comment
https://te.com.ua/uk/56-av-resiveri-procesori?q=%D0%91%D1%80%D0%B5%D0%BD%D0%B4-Yamaha
You can see figure 2 but no stars near
![image](https://user-images.githubusercontent.com/50954519/144312062-a1bc88ca-6624-4344-af94-2e35e9012bd0.png)
I can`t understant what happened

### PrestaShop version(s) where the bug happened

1.7.7.8 and 1.7.8.1

### PHP version(s) where the bug happened

7.1.33-37

### If your bug is related to a module, specify its name and its version

productcomments v5.0.0

**Comment by hibatallahAouadni** [comment] 2021-12-02 11:26
Hello @photinia73 

I reproduce the issue with ProductComment v5.0.0, it's a regression on ProductComment, cause I didn't reproduce the issue with ProductComment v4.2.2:

### BO
![image](https://user-images.githubusercontent.com/23308427/144413386-25364b14-4105-419b-be82-d46cba58b63c.png)

### FO
![image](https://user-images.githubusercontent.com/23308427/144413401-ac8ae675-cae0-47fb-a4cd-effcdff1f822.png)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2021-12-02 11:30
Hello @photinia73 again, 

It seems that's not only the issue with ProductComment v5.0.0.
Not just the stars are displayed, even the comment is not displayed too.
So, I close your issue as a duplicate to this one #26834 as it covers both issues.

Thanks for understanding :pray:

**Comment by hibatallahAouadni** [comment] 2021-12-02 11:31
Duplicate of #26834

**Closed as completed by hibatallahAouadni** 2021-12-02 11:30 UTC
Labels: Bug, Duplicate, Invalid

**Comment by photinia73** [comment] 2021-12-02 13:59
I can see the comments, only the stars disappered
look at this page
https://te.com.ua/uk/av-resiveri-procesori/529-2-yamaha-rx-v385.html#/11-kolir-chornij
