### ISSUE TITLE
Dashboard Goals Module doesn't work in presta 1.7.7.2

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#23715] opened 2021-03-21 00:00 UTC
#### Describe the bug

In a clean instalation of prestashop 1.7.7.2 when configure the module in the main page of BO this don't show any info.

#### Steps to Reproduce

1. Install prestashop
2. Config the module dashboard goals
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/16818257/111888871-438cec80-89bf-11eb-8f70-41a7887f0d18.png)
![image](https://user-images.githubusercontent.com/16818257/111888876-54d5f900-89bf-11eb-95d8-345f37e82f39.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-03-22 10:00
Hello @TecnoHands 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9662. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-22 10:00 UTC
Labels: Duplicate
