### ISSUE TITLE
Weird translation for "Orders" tab for United Kingdom English pack

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#21304] opened 2020-10-05 13:51 UTC
#### Describe the bug

When I download "United Kingdom" localization pack and I change my BO language to "English GB (English)" my Orders BO page has title "Order settings" (see screenshots)

#### Expected behavior

I think the title should be "Orders" not "Order settings"

#### Steps to Reproduce

1. Install PrestaShop using `1.7.7.x` branch, use French language
2. Open Back Office
3. Download "United Kingdom" localization pack
4. Go in "My profile" BO page and change BO language to "English GB (English)"
5. See weird translation as in screenshot

**Screenshots**

<img width="227" alt="Capture d’écran 2020-10-05 à 15 47 06" src="https://user-images.githubusercontent.com/3830050/95087820-73eb1200-0722-11eb-9e62-3b4a0918c17d.png">

#### Additional information

* PrestaShop version: 1.7.7.x

**Comment by khouloudbelguith** [comment] 2020-10-05 14:00
Hi @matks,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/18082 to fix the issue.
Your ticket is a duplicate of #9762
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-10-05 14:00
Duplicate of #9762

**Closed as completed by khouloudbelguith** 2020-10-05 14:00 UTC
Labels: Duplicate
