### ISSUE TITLE
Create order from back office issue 1.7.7.1 to 1.7.7.3

### ISSUE THREAD

**Issue by hasager1** [PrestaShop/PrestaShop#24175] opened 2021-04-23 06:07 UTC
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on 'Add a new order from the Back office and select a customer'
3. Scroll down to 'The section where you can sent payment link or go to checkout page'
4. When you click on the link go to check out page, you will be redirected to the check out page and the customer information will pre-filled. But in version below 1.7.7 you will be signed in as the customer and can confirm the order. I version 1.7.7.1, 1.7.7.2 and 1.7.7.3 you are not getting signed in as the customer and can therefor not complete the order.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A
<img width="1676" alt="Screen Shot 2564-04-23 at 13 03 32" src="https://user-images.githubusercontent.com/83056772/115825964-641fea80-a434-11eb-8d4c-fe4204336aa7.png">

**Comment by florine2623** [comment] 2021-04-23 07:39
Hello @hasager1 ,

Please check this issue https://github.com/PrestaShop/PrestaShop/issues/22464
and this comment : https://github.com/PrestaShop/PrestaShop/issues/22464#issuecomment-747308409

To be informed when it's fixed, please subscribe to the issue mentioned above.
Thank you

**Comment by florine2623** [comment] 2021-04-23 07:39
Duplicate of #22464

**Closed as completed by florine2623** 2021-04-23 07:39 UTC
Labels: Duplicate
