### ISSUE TITLE
impossible to edit or create cms page

### ISSUE THREAD

**Issue by seiyar26** [PrestaShop/PrestaShop#10709] opened 2018-09-25 18:28 UTC
Hi i'm on prestashop 1.7.4.2 and impossible to edit or create cms page it load and nothing happens

best regards

**Comment by khouloudbelguith** [comment] 2018-09-26 07:38
Hi @seiyar26,

I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record.
https://drive.google.com/file/d/1ogBpwPMhLlhMLh-pjP0YTrtAD5lffNcK/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by seiyar26** [comment] 2018-09-26 07:42
Hi thanks for your reply I can’t access to cms page I have error 500

 BEst regards

**Comment by khouloudbelguith** [comment] 2018-09-26 08:51
Hi @seiyar26,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-25 11:19
Hi @seiyar26,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-25 11:19 UTC
Labels: BO, Pages, No change required, 1.7.4.2
