### ISSUE TITLE
Back office on Safari 17.6 browser doesn't display correctly

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#37217] opened 2024-10-22 12:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The PrestaShop 8.2 back office doesn't display correctly on **Safari 17.6** running on **macOS Monterey 12.7.6**.

### Steps to reproduce

One of my clients reported this issue to me. He is using an older Mac computer that does not allow him to upgrade to the latest version of Safari. Of course, he can use a different web browser instead of Safari 17.6. But for compatibility with PrestaShop's back office, can you check and fix the issue?

![Safari issue mov_20241022_140107 153](https://github.com/user-attachments/assets/85007ffd-cf98-46dd-aaee-7b4efceab2d5)

https://vimeo.com/1022083326/8a6c9d8bcc

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-10-30 15:41
Hello,

I can't reproduce this issue with Safari, so I will close it.

**Closed as completed by florine2623** 2024-10-30 15:41 UTC
Labels: Bug
