### ISSUE TITLE
Product on category page display out of stock instead of availlable on order

### ISSUE THREAD

**Issue by Rizzen59** [PrestaShop/PrestaShop#25137] opened 2021-06-26 14:15 UTC
Hello, i have a stenage behavior on category page. 

Thanks for your help. And i have local dev environment, if test is needed

#### Describe the bug

On catagory page i have product display as out of stock even if availlable for order. 
But if I go to the product page, status is ok and product can be added on cart.
More, when I add the product to cart, the status on category page change for the good status until the product are removed from the cart.

No all product are affected. I searched in code and the problem come from the out_of_sotck parameter to define if you can order product out of stock. For some product the value of out_of_stock is empty on category page instead of 0,1 ot 2. In this case it should be 1. (Product.php line 4907 :  $row['allow_oosp'] = Product::isAvailableWhenOutOfStock($row['out_of_stock']);)

Problem is only on category page. 
Home page, product page, search page are ok. 

#### Expected behavior

When product product are availlable for order eveni if stock equal 0, display on demand on category page.

#### Steps to Reproduce

1. Define product witch capability to be order even if stock are equal to 0
2. Define stock to 0
3. Show product on category page
4. Flag is out of stock instead of On-demand

**Screenshots**

![image](https://user-images.githubusercontent.com/25029253/123515579-3fe0c400-d698-11eb-885c-77ece1205fcc.png)
![image](https://user-images.githubusercontent.com/25029253/123515636-7b7b8e00-d698-11eb-853f-76c3ce5b1a0c.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version:  7.3.28
* MySQL : 10.4.18-MariaDB-1:10.4.18+maria~stretch-log
* No cache
* Multishop activated (1 group for 2 shop)
* Customer share : no
* Quantity of product share : yes
* Order share : no

To avoid loosing customer i disable message on category page

**Comment by hibatallahAouadni** [comment] 2021-06-28 16:22
Hello @Rizzen59 

I didn't manage to reproduce the issue with PS1.7.7.4, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/123670725-ce427a80-d83d-11eb-8d9a-349b7c2786fa.png)

![image](https://user-images.githubusercontent.com/23308427/123670747-d4d0f200-d83d-11eb-8d19-2f261217e0eb.png)

Did you try to clear the cache?
Please check and feedback.

Thanks!

**Comment by Rizzen59** [comment] 2021-07-12 07:41
Hello,

Cache are cleared (more than once)  but no effect. 
It seems to me that it arrived when I activated the multistore option with shared stock between store.

When i tried to display the product property "allow_oosp" in template, this value equal 0, but in extension arround the main page this value is well populated.

Thanks

**Comment by hibatallahAouadni** [comment] 2021-07-12 09:14
Hello @Rizzen59 

Even when I enabled the multistore option, I still can not manage to reproduce the issue, see the attached screen record below:

https://drive.google.com/file/d/1jj_If4bpbM2wPNkG7IGFQPcB4f6oS4wS/view

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-08-01 08:44
Hello @Rizzen59 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-08-01 08:44 UTC
Labels: Bug, FO, No change required, 1.7.7.4
