### ISSUE TITLE
bug in "Positions" Prestashop 1.7.5.1 after updating

### ISSUE THREAD

**Issue by RicRey1988** [PrestaShop/PrestaShop#13028] opened 2019-03-24 00:55 UTC
**Describe the bug**
After updating prestashop from 1.7.3.0 to 1.7.5.1 I found a flaw in the "Positions" tab, the button for "Inserts Module" is totally misplaced and it looks terrible, I can not find a way to fix it.

**Screenshots**

![bug](https://user-images.githubusercontent.com/44790517/54873507-966a4400-4da5-11e9-8b5b-0515ee40ac29.jpg)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-03-25 09:18
Hi @RicRey1988,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Try to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by RicRey1988** [comment] 2019-03-25 14:49
I have removed all folders and files from
/ var / cache / dev
/ var / cache / prod

delete the content of these folders and files will not affect something else?

now the menu looks good.

![normal](https://user-images.githubusercontent.com/44790517/54929175-28c43200-4ee3-11e9-81aa-3091adef8df0.jpg)

**Comment by khouloudbelguith** [comment] 2019-03-25 14:55
@RicRey1988, thanks for your feedback.
I  close the issue, feel free to open a new one when needed.
Thanks!

**Comment by RicRey1988** [comment] 2019-03-30 17:57
I commented that although I deleted that folder the next day I realized that the button was again the same.

**Comment by kpodemski** [comment] 2019-03-30 18:04
@RicRey1988 this is in browser cache, make sure that you refresh your browser few times, ctrl + f5 / cmd + f5

**Comment by RicRey1988** [comment] 2019-03-30 18:06
I commented that I deleted the entire cache, I even tried it on a new computer that had never entered my store, and the same thing happens.

**Comment by khouloudbelguith** [comment] 2019-04-01 14:37
Hi @RicRey1988,

I did not manage to reproduce the issue after updating version 1.7.3.0 to 1.7.5.1.
@marionf, could you please try to reproduce the issue.

**Comment by marionf** [comment] 2019-04-03 13:06
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.

Best regards.

**Closed as completed** 2019-04-03 13:06 UTC
Labels: BO, Can't reproduce, Positions, 1.7.5.1
