### ISSUE TITLE
Run cron script with PHP CLI

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#22515] opened 2020-12-21 10:51 UTC
Prestashop provide several cron script to run every day for instance:

- Reindex search: 
`https://www.domain.com/admin/index.php?controller=AdminSearch&action=searchCron&ajax=1&full=1&token=xxx`

- Reindex prices (facet search): 
`https://www.domain.com/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=xxx`

- Reindex attributes (facet search): 
`https://www.domain.com/modules/ps_facetedsearch/ps_facetedsearch-attribute-indexer.php?token=xxx`

Prestashop only provide an URL to call. 
But is there a way to run cron using PHP CLI - which is the most common way to run cron script - without using `wget` command?

**Comment by PierreRambaud** [comment] 2020-12-21 10:56
Hi,

There is no easy way to do it because files are using GET parameters instead of `$argv`
Using `wget` or `curl` is currently the best way to call these files.

Kind regards

**Comment by hibatallahAouadni** [comment] 2020-12-21 13:47
Hello @Seb33300 

I close this issue cause it's not a bug or an improvement of PrestaShop Core.
Keep in mind that you can always ask @PierreRambaud any other question related to this topic even when the issue is closed :wink: 

Please feel free to open a new one if you have any issue with PrestaShop Core, we will gladly investigate it.
@PierreRambaud Thanks for your quick reply :1st_place_medal: 

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-21 13:47 UTC
Labels: No change required
