### ISSUE TITLE
Issue with product combinations with and without in stock

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/PrestaShop#11890] opened 2018-12-21 11:00 UTC
Unfortunately the BUG was not fixed with the update from 1. 7. 4. 4 to 1. 7. 5. 
Known from #9667

A product with combinations with and without in stpck.
- Combination with stock 0 - cannot be ordered. The selection jumps to an available combination. 

The issue is only with a upgraded shop - mine is 1.7.4.4 to 1.7.5. 
A new clean installation PS 1.7.5 works without problems. 

Please also solve this BUG with a upgrade with the one

**Comment by pdkey** [comment] 2018-12-21 11:05
The BO for the product combinations you see the total number of combinations, but the complete list is missing.

**Comment by khouloudbelguith** [comment] 2018-12-21 11:13
Hi @pdkey,

Thanks for your report.
The issue #9664 is not fixed yet, it added to our bug roadmap.
In your case what your exact issue?
Could you please add steps to reproduce it.
THanks!

**Comment by pdkey** [comment] 2018-12-21 11:42
Hi @khouloudbelguith 
i made a misake with the number its #9667 
BOOM-6113 and #9390

the way of reproduce stills the same.

**Comment by khouloudbelguith** [comment] 2018-12-21 12:08
@pdkey,

thanks this clarification.
I tried a fresh installation 1.7.5.0 => OK.
I tried with PS1.7.5.0 after upgrade from 1.7.4.4 with the 1-click upgrade v4.5.1 => OK.
Did you occure any errors during the upgrade?
Thanks!

**Comment by pdkey** [comment] 2018-12-21 16:46
Hi @khouloudbelguith 

Yes, during the upgrade we got 3 errors.
maybe helps. This error is very important for many companies to eliminate.

And during this time we wish you a Merry Christmas and a healthy slide into the new year 2019.

![screenshot_2018-12-21 1-click upgrade 1-click upgrade hoosa](https://user-images.githubusercontent.com/46047238/50353270-fd2e5600-0547-11e9-99d5-e64f5c333248.png)
![screenshot_2018-12-21 1-click upgrade 1-click upgrade hoosa 1](https://user-images.githubusercontent.com/46047238/50353276-028ba080-0548-11e9-812e-1163ff0ba15d.png)

**Comment by khouloudbelguith** [comment] 2018-12-21 16:52
Hi @pdkey, 

Yes, we are aware of this issue, here's a fix https://github.com/PrestaShop/PrestaShop/pull/11814 for this warnings.
But all these warnings have no effect on your issue.
I have an upgrade from 1.7.4.4 to PS1.7.5.0 with those warnings but the issue is fixed.
Thanks!

Wish you a Merry Christmas and Happy new year 2019!

**Comment by pdkey** [comment] 2019-01-06 12:53
Hi @khouloudbelguith a happy and successful new year. Again, thank you very much for your help. After a long search, I found my mistake. Although the setting "allow purchase for products out of stock was enabled, but also enabled for don't display. A little confusing. Now everything works even after upgrading to PS 1.7.5. Thank you very much again.

**Comment by khouloudbelguith** [comment] 2019-01-07 08:12
Hi @pdkey,

Thanks for your feedback & Happy New Year, wish you all the best.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-07 08:12 UTC
Labels: Combinations, No change required, 1.7.5.0
