### ISSUE TITLE
Mail Alerts module in Prestashop 1.7.8.7

### ISSUE THREAD

**Issue by marloru** [PrestaShop/PrestaShop#33211] opened 2023-07-11 14:38 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good afternoon,

The module Mail Alerts v2.4.1 in Prestashop v 1.7.8 doesn't work.

Example: https://testayla.com/bancos/11669-banco-madera-jardin-67x150-180808010.html

This product is out of stock

In Product Configuration we have selected:

Product availability --> YES (Offers the customer the option to receive a notification when an out-of-stock product is available again)

But the option to request that the customer be notified when the product is back in stock is not displayed in the front office.

Could you please help us with this matter?

### Expected behavior

We expect that the customer can make an alert to be notified when the product is back in stock, like in Prestashop v1.6 

https://suinplas.com/bancos/11669-banco-madera-jardin-67x150-180808010-180808010.html?_adin=11734293023

### Steps to reproduce

1. Go to Prestashop 1.7 product page: https://testayla.com/bancos/11669-banco-madera-jardin-67x150-180808010.html
This product is out of stock
2. the option to request that the customer be notified when the product is back in stock is not displayed in the front office.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Mail Alerts v2.4.1

### Your company or customer's name goes here (if applicable).

Ayla Diseño y Tecnología

**Comment by florine2623** [comment] 2023-07-12 14:10
Hello @marloru ,

I can't reproduce your issue :
<img width="1241" alt="Screenshot 2023-07-12 at 16 08 17" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/37ccd065-10d1-4a1f-b59f-595b06d9bdc3">

Please make sure the hooks are well hooked (`displayCustomerAccount`, `displayMyAccountBlock`, `displayProductAdditionalInfo`)

Also, make sure that your theme is compatible with this module.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing this issue as it couldn't be reproduced.

Thank you

**Closed as completed by florine2623** 2023-07-12 14:10 UTC
Labels: Bug, Invalid
