### ISSUE TITLE
Combination reference don't save / product page v1

### ISSUE THREAD

**Issue by serwin35** [PrestaShop/PrestaShop#29427] opened 2022-08-23 17:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Edit profile:
After adding a reference, ean, mpn to a combination and saving it is not added to the database

### Expected behavior

The references after pressing the save button are saved and available after the reload of the product page.

### Steps to reproduce

1. Edit Products
2. Combinations
3. edit combination 
4. add index (reference), ean, mpn 
5. save 
6. when refresh site reference is blank 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by serwin35** [comment] 2022-08-23 18:46
![image](https://user-images.githubusercontent.com/4369427/186235963-51d9c48a-91f7-46b4-8bc1-99ba28841d8a.png)

**Comment by AureRita** [comment] 2022-08-24 09:16
Hi @serwin35 

Thank you for your reporting, I tried to reproduce your issue as you can see on this video : 

https://user-images.githubusercontent.com/100699445/186378709-b5caf949-11c2-49be-80d0-14a8c5f9744f.mp4

You can see that the Meta-title changed. 

is this issue that you wanted to show us ? or I didn't do all things to reproduce your issue ? 

Waiting for your feedback

**Comment by kpodemski** [comment] 2022-08-24 09:23
Hi @AureRita 

I think you made a mistake and didn't follow "How to test". Maybe it's about a different issue?

> Edit Products
> Combinations
> edit combination
> add index (reference), ean, mpn
> save

**Comment by serwin35** [comment] 2022-08-24 09:26
no no this is not the same problem, adding a reference or other value of type ean for a combination simply does not save it to the database

see this:
[video](https://www.awesomescreenshot.com/video/10676250?key=960cebfdbef485a712397593fcc7e837)

**Comment by AureRita** [comment] 2022-08-24 09:43
Thank you for your quick answer, 

Indeed, this is another problem that I reproduced with PrestaShop version 8.0.0 and not with the version 1.7.8.7. Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment] 2022-09-06 15:08
PR https://github.com/PrestaShop/PrestaShop/pull/29523

**Comment by hibatallahAouadni** [comment] 2022-09-07 16:48
Hello @serwin35 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28981. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-09-07 16:48
Duplicate of #28981

**Closed as completed by hibatallahAouadni** 2022-09-07 16:48 UTC
Labels: Bug, 8.0.x, BO, Duplicate, Combinations, Invalid
