### ISSUE TITLE
No alt attributes for SVG from blockreassurance

### ISSUE THREAD

**Issue by Tomi1444** [PrestaShop/PrestaShop#30275] opened 2022-11-12 21:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello

When I run PageSpeed Inights, it says I have no alt description for SVG icon images from blockreassurance.
I have only one error for SEO from PageSpeed Insights - no alt for SVGs

### Expected behavior

How to add alt text for SVG?

### Steps to reproduce

In shop:

Go to any product in your shop.
Right click or any block reassurance icons
Inspect

It should look: 

```
<span class="item-product">
<img src="/modules/blockreassurance/views/img/img_perso/gwarancja.svg">
</span>
```

There is no alt description.

Or you can check in PageSpeed Insights:

Take any link from your shop products
Go to: https://pagespeed.web.dev/
Paste link

Check results.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4 and 7.2

### If your bug is related to a module, specify its name and its version

blockreassurance

**Comment by hibatallahAouadni** [comment] 2022-11-14 14:18
Hello @Tomi1444 


We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24133. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-11-14 14:19
Duplicate of #24133

**Closed as not planned** 2022-11-14 14:19 UTC
Labels: Bug, Duplicate, Invalid
