### ISSUE TITLE
JQMIGRATE is deprecated in console appears multiple times

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#20574] opened 2020-08-13 12:14 UTC
#### Describe the bug

When I navigate on the FO with an open console, I can see multiple JQMIGRATE is deprecated mentions 

#### Expected behavior

Update the Jquery functions related 

#### Steps to Reproduce

1. On the FO, open your console and go throug the website
==> The mentions of JQMIGRATE appears 

**Screenshots**

![Capture d’écran 2020-08-13 à 13 53 43](https://user-images.githubusercontent.com/69145330/90132829-c2a5ac80-dd6e-11ea-9ca7-96ccde0e036a.png)

#### Additional information

* PrestaShop version: develop, 1.7.7.x
* PHP version: 7.2

**Comment by NeOMakinG** [comment] 2020-08-26 14:52
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/15943

Closing, thanks!

**Closed as completed by NeOMakinG** 2020-08-26 14:52 UTC
Labels: Bug, develop, Trivial, FO, Duplicate, Good first issue, 1.7.7.0
