### ISSUE TITLE
Upgrade from 8.04 to 8.1.2 Error upgrading Doctrine schema

### ISSUE THREAD

**Issue by xga91** [PrestaShop/PrestaShop#34280] opened 2023-10-14 14:19 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Here is the log file, problem on updating the database.
And get this message "Error upgrading Doctrine schema"

I tried Php 7.4 and 8.1 same problem.

MariaDB 10.4 & 10.6 tested, do you think it can be related to MariaDb version ?

[2023-10-14 06:08:23] All files upgraded. Now upgrading database...
[2023-10-14 06:08:23] Cleaning file cache
[2023-10-14 06:08:23] [SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[2023-10-14 06:08:23] [CLEANING CACHE] File pagecache removed
[2023-10-14 06:08:24] [CLEANING CACHE] File prod removed
[2023-10-14 06:08:24] Running opcache_reset
[2023-10-14 06:08:26] API keys not present in parameters, generating
[2023-10-14 06:08:26] Keys generated using openssl_pkey_new, exporting private and public keys
[2023-10-14 06:08:26] Updating parameters file
[2023-10-14 06:08:26] Invalidating opcache for parameters file
[2023-10-14 06:08:26] Parameters file updated
[2023-10-14 06:08:26] Initializing required environment constants
[2023-10-14 06:08:30] Checking version validity
[2023-10-14 06:08:30] Checking connection to database
[2023-10-14 06:08:30] Keeping non native modules enabled
[2023-10-14 06:08:30] Updating database data and structure
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 SET SESSION sql_mode=''</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 SET NAMES 'utf8mb4'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 UPDATE `ps_configuration` SET `value` = 'US/Pacific' WHERE `name` = 'PS_TIMEZONE' AND `value` = 'US/Pacific-New' LIMIT 1</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 DELETE FROM `ps_timezone` WHERE `name` = 'US/Pacific-New'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 INSERT IGNORE INTO `ps_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES
  (NULL, 'actionModifyFrontendSitemap', 'Add or remove links on sitemap page', 'This hook allows to modify links on sitemap page of your shop. Useful to improve indexation of your modules.', '1'),
  (NULL, 'displayAddressSelectorBottom', 'After address selection on checkout page', 'This hook is displayed after the address selection in checkout step.', '1'),
  (NULL, 'actionGenerateDocumentReference', 'Modify document reference', 'This hook allows modules to return custom document references', '1'),
  (NULL, 'actionLoggerLogMessage', 'Allows to make extra action while a log is triggered', 'This hook allows to make an extra action while an exception is thrown and the logger logs it', '1'),
  (NULL, 'actionProductPriceCalculation', 'Product Price Calculation', 'This hook is called into the priceCalculation method to be able to override the price calculation', '1')</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 INSERT IGNORE INTO `ps_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES
  (NULL, 'actionAdminMenuTabsModifier', 'Modify back office menu', 'This hook allows modifying back office menu tabs', '1')</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 /* Default configuration for backorder, in order to keep behavior */
INSERT INTO `ps_configuration` (`name`, `value`, `date_add`, `date_upd`) VALUES
  ('PS_ENABLE_BACKORDER_STATUS', '1', NOW(), NOW())</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 /* Keep sending e-mails with prefixed subject to avoid behaviour change */
INSERT INTO `ps_configuration` (`name`, `value`, `date_add`, `date_upd`) VALUES
  ('PS_MAIL_SUBJECT_PREFIX', '1', NOW(), NOW())</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[DROP] SQL `ps_product_attribute_lang` table has been dropped.</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 /* Add new product_attribute_lang table and fill it with data */
CREATE TABLE `ps_product_attribute_lang` (
  `id_product_attribute` int(10) unsigned NOT NULL,
  `id_lang` int(10) unsigned NOT NULL,
  `available_now` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `available_later` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id_product_attribute`, `id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 INSERT INTO `ps_product_attribute_lang`
(id_product_attribute, id_lang, available_now, available_later)
SELECT pa.id_product_attribute, l.id_lang, '', ''
FROM `ps_product_attribute` pa CROSS JOIN `ps_lang` l</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 /* Add default redirect configuration */
INSERT INTO `ps_configuration` (`name`, `value`, `date_add`, `date_upd`) VALUES
  ('PS_PRODUCT_REDIRECTION_DEFAULT', '404', NOW(), NOW()),
  ('PS_MAINTENANCE_ALLOW_ADMINS', 1, NOW(), NOW()),
  ('PS_AVIF_QUALITY', '90', NOW(), NOW()),
  ('PS_IMAGE_FORMAT', 'jpg', NOW(), NOW())</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 /* Update ENUM values in both tables*/
ALTER TABLE `ps_product` MODIFY COLUMN `redirect_type` ENUM(
  '','404','410','301-product','302-product','301-category','302-category','200-displayed','404-displayed','410-displayed','default'
) NOT NULL DEFAULT 'default'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 ALTER TABLE `ps_product_shop` MODIFY COLUMN `redirect_type` ENUM(
  '','404','410','301-product','302-product','301-category','302-category','200-displayed','404-displayed','410-displayed','default'
) NOT NULL DEFAULT 'default'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 /* and change all '404' to 'default' */
UPDATE `ps_product` SET `redirect_type` = 'default' WHERE `redirect_type` = '404' OR `redirect_type` = '' OR `redirect_type` IS NULL</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 UPDATE `ps_product_shop` SET `redirect_type` = 'default' WHERE `redirect_type` = '404' OR `redirect_type` = '' OR `redirect_type` IS NULL</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] PHP 8.1.0 : /* Update feature flags */
/* PHP:ps_810_update_product_page_feature_flags(); */</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 /* add new feature flag for multiple image formats */
INSERT INTO `ps_feature_flag` (`name`, `state`, `label_wording`, `label_domain`, `description_wording`, `description_domain`, `stability`)
VALUES
    ('multiple_image_format', 0, 'Multiple image formats', 'Admin.Advparameters.Feature', 'Enable / Disable having more than one image format (jpg, webp, avif, png...)', 'Admin.Advparameters.Help', 'stable')</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 ALTER TABLE `ps_stock_mvt` CHANGE `employee_lastname` `employee_lastname` VARCHAR(255) DEFAULT NULL, CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT NULL</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 ALTER TABLE `ps_stock_mvt` CHANGE `physical_quantity` `physical_quantity` INT(11) UNSIGNED NOT NULL</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] PHP 8.1.0 : /* PHP:add_hook('actionAdminBreadcrumbModifier', 'Modify back office breadcrumb', 'This hook allows modifying back office breadcrumb'); */</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.0 ALTER TABLE `ps_order_payment` ADD `id_employee` INT NULL AFTER `date_add`</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.1 SET SESSION sql_mode=''</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.1 SET NAMES 'utf8mb4'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] PHP 8.1.1 : /* We forgot to update redirect_type in 8.1.0. This updates it, if it's not done already */
/* PHP:ps_811_update_redirect_type(); */</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.2 SET SESSION sql_mode=''</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.2 SET NAMES 'utf8mb4'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.2 /*
Security section tabs were correctly added (ps_800_add_security_tab.php) for people coming from 1.7.8,
but had missing wordings on new 8.0.0-8.1.1 installs.
We fixed it for people installing fresh 8.1.2, but we also need to fix it for people that started on 8.0.0-8.1.1 versions.
*/
UPDATE `ps_tab` SET wording_domain = 'Admin.Navigation.Menu', wording = 'Security' WHERE class_name = 'AdminParentSecurity'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.2 UPDATE `ps_tab` SET wording_domain = 'Admin.Navigation.Menu', wording = 'Employee Sessions' WHERE class_name = 'AdminSecuritySessionEmployee'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.2 UPDATE `ps_tab` SET wording_domain = 'Admin.Navigation.Menu', wording = 'Customer Sessions' WHERE class_name = 'AdminSecuritySessionCustomer'</div>
[2023-10-14 06:08:30] <div class="upgradeDbOk">[OK] SQL 8.1.2 INSERT IGNORE INTO `ps_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES
  (NULL, 'actionLanguageLinkParameters', 'Add parameters to language link', 'Allows modules to provide proper parameters for links in other languages.', '1'),
  (NULL, 'actionAfterLoadRoutes', 'Triggers after loading routes', 'Allow modules to modify routes in any way or add their own multilanguage routes.', '1')</div>
[2023-10-14 06:08:32] Updating database schema...
[2023-10-14 06:08:32] Executing: CREATE TABLE ps_authorized_application (id_authorized_application INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_475B9BA55E237E06 (name), PRIMARY KEY(id_authorized_application)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
[2023-10-14 06:08:32] Executing: CREATE TABLE ps_api_access (id_api_access INT UNSIGNED AUTO_INCREMENT NOT NULL, id_authorized_application INT UNSIGNED NOT NULL, client_id VARCHAR(255) NOT NULL, client_secret VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, scopes LONGTEXT NOT NULL COMMENT '(DC2Type:array)', INDEX IDX_6E064442D8BFF738 (id_authorized_application), PRIMARY KEY(id_api_access)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
[2023-10-14 06:08:32] Executing: ALTER TABLE ps_feature_flag CHANGE state state TINYINT(1) DEFAULT '0', CHANGE  description_wording description_wording VARCHAR(512) DEFAULT '' NOT NULL
[2023-10-14 06:08:32] Executing: ALTER TABLE ps_translation CHANGE `key` `key` TEXT NOT NULL COLLATE `utf8_bin`
[2023-10-14 06:08:32] Executing: ALTER TABLE ps_psgdpr_consent MODIFY id_gdpr_consent INT UNSIGNED NOT NULL
[2023-10-14 06:08:32] Executing: ALTER TABLE ps_psgdpr_consent DROP PRIMARY KEY
[2023-10-14 06:08:32] Executing: ALTER TABLE ps_psgdpr_consent CHANGE id_gdpr_consent id_gdpr_consent INT AUTO_INCREMENT NOT NULL, CHANGE id_module id_module INT NOT NULL, CHANGE active active TINYINT(1) NOT NULL, CHANGE error error TINYINT(1) NOT NULL, CHANGE error_message error_message VARCHAR(255) NOT NULL
[2023-10-14 06:08:32] 06:08:32 CRITICAL  [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "There is no active transaction" ["exception" => PDOException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => "There is no active transaction"]
[2023-10-14 06:08:32] In Connection.php line 1854:
[2023-10-14 06:08:32]                                   
[2023-10-14 06:08:32]   There is no active transaction  
[2023-10-14 06:08:32]                                   
[2023-10-14 06:08:32] prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] <command>
[2023-10-14 06:08:32] Error during database upgrade. You may need to restore your database.
[2023-10-14 06:08:32] Error upgrading Doctrine schema

### Steps to reproduce

just using latest autoupgrade version.

### PrestaShop version(s) where the bug happened

8.0.4 8.1.2

### PHP version(s) where the bug happened

7.4 and 8.1

**Comment by xga91** [comment] 2023-10-14 14:21
I tried Php 7.4 and 8.1 same problem.

MariaDB 10.4 & 10.6 tested, do you think it can be related to MariaDb version ?

<img width="1270" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/12119811-9d11-4676-b73e-96a96fcae128">
<img width="1283" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/e78af31c-b081-4285-915d-9cca278e3b1d">

**Comment by AureRita** [comment] 2023-10-16 10:06
Hi @xga91 

Thank you for your report, I tried to reproduce your issue but currently I can't reproduce it as you can see : 

[Untitled_ Oct 16, 2023 12_02 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/017c5a45-faf1-40bb-874c-bfc9d3be9f04)

Can you give us more details about your step to reproduce, currently I don't know if you do a major release, a release candidate, if you give a file to the update or anything else. 

Can you give us a video to see your issue correctly ? 

Waiting for your feedback

**Comment by ChillCode** [comment] 2023-10-16 11:04
Hi

I guess the last commands you see in the log are related to psgdpr module and throw key errors, but who knows.

PrestaShop is changing the way this is done so hope the next releases those commands will not be inside a transaction since have no sense:
 
> The statements listed in this section (and any synonyms for them) implicitly end any transaction active in the current session, as if you had done a [COMMIT](https://dev.mysql.com/doc/refman/8.0/en/commit.html) before executing the statement.

https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

You can try to disable/uninstall psgdpr and try again, then install thru module manager again.

**Comment by florine2623** [comment] 2023-11-03 13:53
Hello ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-11-03 13:53 UTC
Labels: Bug, BO, Autoupgrade, Invalid, Module, 8.0.4
