### ISSUE TITLE
Can't load Stocks page from backoffice. Error 500 with php 8.1. PrestaShop 8.0.1

### ISSUE THREAD

**Issue by tajriba** [PrestaShop/PrestaShop#31859] opened 2023-03-21 08:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When loading the /sell/stocks/ page in backoffice. We get no results. Error 500:
This is only on php 8/8.1.

On php 7.4 it works fine.
<img width="1063" alt="Scherm­afbeelding 2023-03-21 om 09 34 48" src="https://user-images.githubusercontent.com/68469531/226554083-3b700b14-b962-490c-93ee-6af2529e8edb.png">
<img width="1218" alt="Scherm­afbeelding 2023-03-21 om 09 34 41" src="https://user-images.githubusercontent.com/68469531/226554099-765067a1-594a-42f5-9625-380b5d42c1e0.png">
<img width="1311" alt="Scherm­afbeelding 2023-03-21 om 09 33 14" src="https://user-images.githubusercontent.com/68469531/226554111-0f342496-0421-41fb-a678-fadb5d2877e3.png">

### Expected behavior

Loading and a working Stocks page.

### Steps to reproduce

1. Go To Catalog > stocks

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

php 8.0 and 8.1

**Comment by florine2623** [comment] 2023-03-21 10:43
Hello @tajriba ,

Please check this issue and follow the steps to fix it : https://github.com/PrestaShop/PrestaShop/issues/19589

Waiting for your feedback.
Thanks

**Comment by kpodemski** [comment] 2023-03-21 11:14
Hi @florine2623 

We should treat it as a valid bug report if it happens and there's work required to be done in the core :-)

**Comment by tajriba** [comment] 2023-03-21 13:54
I can confirm the CORE changes works suggested in #19589 . But this is not the correct way for bugfixes haha

**Comment by florine2623** [comment] 2023-03-24 17:25
I can't reproduce the issue on my side 😅 
I tested with Dutch language and PHP 8.1 :
<img width="1438" alt="Screenshot 2023-03-24 at 18 25 00" src="https://user-images.githubusercontent.com/16019289/227597358-ee1d0c5e-fc7b-4690-97f1-9535b2393f0b.png">

If it is fixed, I will close it as I can't reproduce it !

Thanks!

**Closed as completed by florine2623** 2023-03-24 17:25 UTC
Labels: Bug, BO, Stocks, Fixed, 8.0.1

**Comment by tajriba** [comment] 2023-03-24 17:40
Hi @florine2623 ,
But do you also have order detail data? We had more than 4000 products and 22.000 orders.

**Comment by nicolasricci** [comment] 2024-09-27 11:15
Hello all,

I had the same issue and confirm the solution provided in https://github.com/PrestaShop/PrestaShop/issues/19589 helped to resolve it.

How come this has not been integrated in Prestashop latest releases?

Thanks
