### ISSUE TITLE
[BO] Email Theme preview page has overflow in mobile screen

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27031] opened 2021-12-20 11:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The grid table in email theme preview page has overflow in mobile screen.

### Expected behavior

The grid table in email theme preview page must be inside a responsive table.

### Steps to reproduce

1. Go to BO > Design > Email Theme
2. Select a theme for preview
3. Try to see in a page with 415 px width

<img src="https://user-images.githubusercontent.com/85633460/146761027-8a7fbc52-631e-488e-a061-193724bf8e4e.png" width="400">

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment] 2021-12-20 13:49
Hello @mparvazi 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26634. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-20 13:49
Duplicate of #26634

**Closed as completed by hibatallahAouadni** 2021-12-20 13:49 UTC
Labels: Bug, Duplicate
