### ISSUE TITLE
Product page V2 - Modal has a card inside, it should not

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30149] opened 2022-10-28 12:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A card is present in the modal:

<img width="1431" alt="Screenshot 2022-10-28 at 14 19 48" src="https://user-images.githubusercontent.com/16019289/198587328-44235fda-377a-40aa-ae34-012f04b20274.png">

### Expected behavior

It should look like this modal:
https://github.com/PrestaShop/PrestaShop/issues/28162

<img width="860" alt="160617023-8e4e1786-8df4-469b-a7bb-f9d4f931b4f9" src="https://user-images.githubusercontent.com/16019289/198587712-eaf46761-b7fa-43c4-884d-fcd67ec6527b.png">

### Steps to reproduce

1. Enable product page V2
2. Go to Product > Edit a product
3. Go to Details tab > Click Add new file
4. See modal with card inside

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-10-28 16:48
Hello @florine2623 

It seems your issue has been fixed with this PR https://github.com/PrestaShop/prestashop-ui-kit/pull/195, it's just the v1.2.6 hasn't been released yet.
Closing the issue as a duplicate fo this one #28162

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-10-28 16:49
Duplicate of #28162

**Closed as completed by hibatallahAouadni** 2022-10-28 16:48 UTC
Labels: Bug, 8.0.x, BO, Duplicate, Front-end, Invalid
