### ISSUE TITLE
Color attributes can be created without a swatch or a texture applied - causes Product:getAttributesColorList() to fail

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/PrestaShop#25136] opened 2021-06-26 13:00 UTC
#### Describe the bug

Prestashop allows you to create product attributes of attribute type: _Color or texture_ without setting a colour hex code on them.

If this is done the function `getAttributesColorList(array $products, $have_stock = true)` located in `/classes/Product.php` will not return this attribute when set on a product combination. 

This effects function `getMainVariants()` located in `/src/Adapter/Presenter/Product/ProductLazyArray.php` which will not return variants if the attributes related to them do not use a colour with a hex colour set.

I believe it is due to the following  part of the SQL query in the function `getAttributesColorList`

`IF(color = "", a.id_attribute, color)`

This query should probably be looking at the database field: `attribute_group.is_color_group` sql rather than the `attribute.color` field when determining if an attribute is a color

#### Expected behavior

Either:

1. When creating a color attribute the user should be required to set a default swatch colour or it should default to say white or black

2. Function `getAttributesColorList` should return colours even if they don't have a colour set

3. Both of the above

#### Steps to Reproduce

Create a blank shop, create a few colour attributes without setting the color hex value and then use a module or custom bit of code that requires using Product->getAttributesColorList.

I haven't tested this but I think the default theme can show swatches on product list page views? So you could test it this way.

#### Additional information

I did not check if this error is still present if a texture is set but not a hex value. But looking at the code I would say that setting a texture would not help.

In some ways this might be default behaviour as maybe the front end does not want to be presented with a colour that doesn't have a swatch set against it. However I don't believe you should be able to create an attribute that is sort of half a color because it belongs to an attribute group that has the `is_color` flag set to 1 but then not really a colour to other parts of the system because it's attribute `color` field is blank. Is the absence of color still a color, who can say?

* PrestaShop version: 1.7.7.5

**Comment by hibatallahAouadni** [comment] 2021-06-28 16:01
Helo @haveyougotanypets 

Could you please provide a screenshot or a screen record :pray: 
Cause the seps to reproduce aren't very clear :sweat_smile: 

Thanks!

**Comment by haveyougotanypets** [comment] 2021-06-28 17:18
HI @hibatallahAouadni 

1. Login to Prestashop's back office. 
2. In the menu: Catalouge > Attributes & Features > Add new attribute
3. Create the attribute making sure to select **Attribute Type**: **Color or texture**.
4. Create an attribute value that belongs to this attribute
5. For this attribute value do not set the **color** field, (the one with the colour picker) leave it blank. 
6. The UI will save this with no value set.

I am not saying doing this is a bug in itself. It might be what you want the system to do. 

However if you do not set this value then the color attribute array object belonging to this attribute will not be returned by the function `getAttributesColorList(array $products, $have_stock = true)` located in `/classes/Product.php`.

This is a bug. This function should return all colour attributes objects belonging to a product irrespective of whether or not a colour hex value is set on that attribute. What defines a color attribute value is not if it has a colour hex value set or not. It is if belongs to a color attribute.

I can not show you a screen shot because it is the internal function that is the problem here. I can suggest the following:

1. Add the following to the end of the `getAttributesColorList` function on line 4016 of `/classes/Product.php`

```
print_r($colors);
exit();
```
2. Go to a product list (category) page in the front end using the classic theme. 
3. The code above will give you a print out showing you all the colours that are tagged on the first product on this product list page. (make sure that category page has a product in it with a colour attribute set)
4. Go to Back Office > Catalogue > Attributes & Features. Find the first attribute colour that is first show on the above page (say white) Remove the colour hex value form this color but setting this field blank. Save 
5. Refresh the category page. This color will vanish from the list. It should not. 

**Note**: I would be careful how you fix this. If you do start returning all values then it might break some themes because they are going to expect all colour attribute values to have either a color hex value or a texture. 

I think the best solution might be to fix and also validate on creation of colour attribute values and return an error if neither a swatch or a colour hex value is set. 

This still might break some existing themes. But at least they won't be failing to display colour silently as they are currently doing.

**Comment by florine2623** [comment] 2021-06-29 09:28
Hello @haveyougotanypets ,

Here's what I got :
<img width="916" alt="Screenshot 2021-06-29 at 11 27 17" src="https://user-images.githubusercontent.com/16019289/123773556-08a72880-d8cd-11eb-8827-765594a509b1.png">

Am I missing something ?

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-19 07:12
Hello @haveyougotanypets 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-19 07:12 UTC
Labels: Bug, BO, Attributes, No change required, 1.7.7.5
