### ISSUE TITLE
Prestashop several product images appeared in differnt Colour Tone in mobile devices only

### ISSUE THREAD

**Issue by giasemis** [PrestaShop/PrestaShop#24907] opened 2021-06-10 12:30 UTC
#### Describe the bug

Customer noticed that the products images appeared in a different color tones when you browse in the product pages from a mobile devices.
I then upload the same image in a default theme  prestashop version 1.7 installation and the same issue appeared.  

#### Expected behavior
We expect products  images to be appeared in the correct color tone regardless the device your use to browse the website

#### Steps to Reproduce

1. Go to  https://grecianjewelry.eu/el/Smalto/33-Filigkran-Cheiropoiitos-Kuklikos-Stauros-me-Smalto-chrusos-18k.html
2. double click on product image and go to the 3rd image.  When browse from desktop the image has the correct gold tone.
3. If you use a mobile device and browse to the same web address then the image appeared much more yellow that the correct
color.

4. I upload the same image in web address https://wehost.gr/presta17/stationery/24-this-is-a-a-tessf-p.html
this is an prestashop installation using the default prestashop theme.
Here the actually same behaviour is occured. When browse from desktop the image has the correct color tone but when your browse from mobile the same image appeared much more yellow.
Attached the image
![Filigkran-Cheiropoiitos-Kuklikos-Stauros-me-Smalto-chrusos-18k](https://user-images.githubusercontent.com/5931332/121525197-b925b900-ca00-11eb-956f-09bcc39f1984.jpg)
 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by lmeyer1** [comment] 2021-06-10 12:47
This is probably related to the color profile saved in the picture and the way different navigators interpret it. 

The display of the color nuances of the images are not related to Prestashop, but to the format of the image.

**Comment by Hlavtox** [comment] 2021-06-10 12:48
@giasemis The third image is just more yellow, I see it perfectly fine on my desktop. Buy a better display 😄

**Comment by giasemis** [comment] 2021-06-10 12:53
> @giasemis The third image is just more yellow, I see it perfectly fine on my desktop. Buy a better display 😄

the question is why this image is more yellow when browse from mobile than in desktop. We have try several mobiles.   I just notice now that the same applies if you browse it here in github from a mobile device,  so definetely not a prestashop issues. But anyway how can I have the same color tone for this image in the mobile device as in desktop

**Comment by lmeyer1** [comment] 2021-06-10 12:57
I recommend you to seek counsel with a graphic designer. As I said, it is related to the image format, either the color channels, the gamma setting or the color profiles. I'm not a specialist in these, but I know, that different configurations of those may lead to different display depending on navigator and device.

**Comment by Hlavtox** [comment] 2021-06-10 12:57
@giasemis Every display is different, every display can be configured differently. You open the same image on 3 displays and see completely different colors on each of them.

**Comment by hibatallahAouadni** [comment] 2021-06-10 15:59
Hello @giasemis 

Could you please specify your PrestaShop version :pray: 
I didn't manage to reproduce the issue, see the atatched screenshots below:

Desktop - 1st link:

![image](https://user-images.githubusercontent.com/23308427/121557268-e7ad8f00-ca14-11eb-9ebc-e4ac6c225fe3.png)

Desktop - 2nd link: 

![image](https://user-images.githubusercontent.com/23308427/121557321-f3995100-ca14-11eb-8961-85cbecde1e27.png)

Mobile - 1st link:

![image](https://user-images.githubusercontent.com/23308427/121557663-39eeb000-ca15-11eb-94d3-e1d59f85a585.png)

Mobile - 2nd link:

![image](https://user-images.githubusercontent.com/23308427/121557701-4246eb00-ca15-11eb-8d5c-8828b507016f.png)

@Hlavtox @lmeyer1 wdyt? is it more yellow than desktop?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-06-30 16:05
Hello @giasemis 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-06-30 16:05 UTC
Labels: Bug, 1.7.x, FO, Image, No change required
