### ISSUE TITLE
Prestashop 1.7.8 update problem

### ISSUE THREAD

**Issue by Alexandre67200** [PrestaShop/PrestaShop#35783] opened 2024-03-30 16:29 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Following the update of my prestashop with the new version 1.7.8 which did not work I had to reinstall my previous version

Current PrestaShop version: 1.7.2.4

Current PHP version: 7.1.33

And since:

In the back office, it is impossible to update the products, it is impossible to save. On the page of my site it is impossible for customers to access their account.
And I no longer had the module page but my host (Planethooster) managed to make this page reappear by modifying the parameters.php file

For the login file it is completely empty.

In debug mode when I try to connect as a customer to my buyer account this is the page I get: see attachment 
![screen 1](https://github.com/PrestaShop/PrestaShop/assets/94760712/200fd839-9269-40c8-9670-c0c56cbfe63d)
![screen 2](https://github.com/PrestaShop/PrestaShop/assets/94760712/16cc46c8-3342-4342-901e-909d39e86b8d)
![screen 3](https://github.com/PrestaShop/PrestaShop/assets/94760712/0fd2d37f-e941-4821-b322-680a13a1bf38)
![screen 4](https://github.com/PrestaShop/PrestaShop/assets/94760712/29095e5a-5599-46d7-9f10-fa16d41002d4)
![screen 5](https://github.com/PrestaShop/PrestaShop/assets/94760712/887c1b05-06e9-4538-8fe3-c54ead24fadf)
![screen 7](https://github.com/PrestaShop/PrestaShop/assets/94760712/32308707-c4d0-453d-af1f-4a5fc4de9f11)
![screen 9](https://github.com/PrestaShop/PrestaShop/assets/94760712/272ca9ba-2802-4240-beda-cf057fa46df2)
![screen6](https://github.com/PrestaShop/PrestaShop/assets/94760712/dba9aa1d-9bbe-4f41-a22a-1594bcbd2469)
![screen8](https://github.com/PrestaShop/PrestaShop/assets/94760712/f18b78e2-92fc-4051-82da-586274d4f60b)

### Steps to reproduce

Following the update of my prestashop with the new version 1.7.8 which did not work I had to reinstall my previous version

Current PrestaShop version: 1.7.2.4

Current PHP version: 7.1.33

And since:

In the back office, it is impossible to update the products, it is impossible to save. On the page of my site it is impossible for customers to access their account.
And I no longer had the module page but my host (Planethooster) managed to make this page reappear by modifying the parameters.php file

For the login file it is completely empty.

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.1.33

### Your company or customer's name goes here (if applicable).

www.fightandshop.com

**Comment by paulnoelcholot** [comment] 2024-04-03 12:46
FYI @AureRita

**Comment by AureRita** [comment] 2024-04-03 14:39
Hi @Alexandre67200 

Thank you for your report, Despite my effort I can't reproduce your issue as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/dd4639f5-8a35-4208-8a90-ae17df91ce51)

[recording(175).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4c101f3b-6868-4fd3-b073-6a5b44089286)

Did I miss something ? 

If you check my video, you can see that I do many upgrade from 1.7.2.4. Did you use our module 1-Click-Upgrade ? 

Are you using the last version of Autoupgrade ? 

Waiting for feedback

**Comment by florine2623** [comment] 2024-04-22 09:34
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2024-04-22 09:34 UTC
Labels: Bug, Waiting for author, BO, 1.7.2.4, Autoupgrade
