### ISSUE TITLE
Products issues detected on Google Search Console

### ISSUE THREAD

**Issue by gyan111** [PrestaShop/PrestaShop#22648] opened 2021-01-04 04:32 UTC
#### Describe the bug

Using Prestashop default theme. Got the issue from google search console

Top Errors

Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:

Missing field "ratingValue"

Either "ratingCount" or "reviewCount" should be specified

Top Warnings

Warnings are suggestions for improvement. Some warnings can affect your appearance on Search; some might be reclassified as errors in the future. The following warnings were found on your site:

Missing field "sku"

Missing field "brand"

Missing field "priceValidUntil"

No global identifier provided (e.g., gtin, mpn, isbn)

Missing field "url"

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

#### Expected behavior

There should be no Google Search Console Error

**Screenshots**
![image](https://user-images.githubusercontent.com/4457406/103501295-cb109800-4e73-11eb-8654-c16bcf5aa7dd.png)

There is another issue as well.

![image](https://user-images.githubusercontent.com/4457406/103501304-cea41f00-4e73-11eb-859a-46384fb396ff.png)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2
* Shop URL: https://unionshirtsupply.com

**Comment by Hlavtox** [comment] 2021-01-04 09:17
@gyan111 These are easily fixable. I recommend you to switch to https://github.com/prestarocket-agence/classic-rocket template, it will fix most of the errors.

Missing SKU, global identifier and brand errors will go away after you fill these fields for all your products.

**Comment by hibatallahAouadni** [comment] 2021-01-04 15:33
Hello @gyan111 

Could you please check if your issue is a duplicate to this one #18692

PS: Thanks @Hlavtox for your proposition :rocket: 

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-22 11:56
Hello @gyan111 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22416. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-22 11:56
Duplicate of #22416

**Closed as completed by hibatallahAouadni** 2021-01-22 11:56 UTC
Labels: Bug, FO, Duplicate, SEO & URLs, 1.7.7.0
