### ISSUE TITLE
verification.php in ps_emailsubscription is outdated

### ISSUE THREAD

**Issue by bpato** [PrestaShop/PrestaShop#19474] opened 2020-05-30 19:59 UTC
I don't know if it's still in use but verification.php in ps_emailsubscription is outdated and if you call it directly it throws a 500 error on server.

https://github.com/PrestaShop/ps_emailsubscription/blob/master/verification.php

**Comment by jolelievre** [comment] 2020-06-01 15:04
Hi @bpato 

could you detail a bit more how you get this error? IS the endpoint always returning a 500 error? or just when you call it manually without any parameter?

I can see that the script is expecting a `token` variable so maybe that's the problem, the script is not supposed to be called without it.

Also what do you mean by outdated? Do you mean compared to other modules that are more recent and manage your expected behaviour?

We would need more information and a detailed scenario to reproduce the bug (step by step actions to reproduce the problem).

Thank you for this feedback, and you additional details.

**Comment by jolelievre** [comment] 2020-06-01 15:18
Also when I check at the module it would appear this file is marked has ben `deprecated` 6 years ago (it is already deprecated in original commit in the Github repository).

I don't think you are supposed to use this endpoint any more (it should have been removed a long ago maybe). The verification process seems to handled by this controller now
https://github.com/PrestaShop/ps_emailsubscription/blob/master/controllers/front/verification.php

So you definitely shouldn't use the endpoint you mentioned directly. But rather the module controller, you can get its url with somehting like:

```php
$verif_url = Context::getContext()->link->getModuleLink(
            'ps_emailsubscription', 'verification', array(
                'token' => $token,
            )
        );
```

But since this is managed in the controller itself you should check how to generate the token correctly.

Anyway since your bug is about a deprecated endpoint I'm gonna close this issue.

Thank you for your feedback though.

**Closed as completed by jolelievre** 2020-06-01 15:18 UTC
Labels: No change required

**Comment by bpato** [comment] 2020-06-01 15:43
Hi @jolelievre, thanks for the reply i agree with you, but the thing is that this file comes with the last release of prestashop.

yeah, is when you call it manually, the module class expects a parameter and throws the error.

**Comment by jolelievre** [comment] 2020-06-01 17:06
Yes I know it's still in the release but it probably shouldn't so we won't fix an endpoint that's not supposed to be used (at best we will remove it)

As I said prefer using the front controller, but if you don't provide the expected parameters (especially the token) you will end up with the same problem anyway The token is required for security purpose, or anyone could validate any email and spam users
