### ISSUE TITLE
Methods addCSS / addJS not working on migrated controller when used in displayBackOfficeHeader or actionAdminControllerSetMedia hooks

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#36376] opened 2024-06-17 15:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

We noticed that when we are using `displayBackOfficeHeader` or `actionAdminControllerSetMedia` hooks, the classic `addCSS` & `addJS` functions aren't working as expected.

To be exact, they are properly called from the `LegacyControllerContext` but aren't transferred to the `LegacyControllerContextProxy*` instance where `js_files` & `css_files` attributes are left empty.

### Expected behavior

`js_files` & `css_files` attributes should be filled in the `LegacyControllerContextProxy*` instance

### Steps to reproduce

1. Install any module that uses `displayBackOfficeHeader` or `actionAdminControllerSetMedia` hooks like ps_faviconnotificationbo
2. Notice that JS assets aren't loaded at all => favico.js and ps_faviconnotificationbo.js
3. Go to any non-migrated controller, like "AdminSearchConf", notice that the assets are loaded.

### PrestaShop version(s) where the bug happened

9.0.0-alpha1

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

PrestaModule

**Comment by hadjedjvincent** [comment] 2024-06-17 15:55
Possible fix would be to use `$this->context->getContext()->controller` instead of `$this->legacyControllerContext` into the `src/PrestaShopBundle/Twig/Component/HeadTag.php` file (like `getJsDef` method)

```php
public function getCssFiles(): array
{
    return $this->context->getContext()->controller->css_files;
}

public function getJsFiles(): array
{
    return $this->context->getContext()->controller->js_files;
}
```

**Comment by jolelievre** [comment] 2024-06-18 13:20
Thanks @hadjedjvincent I think there's a problem indeed around these two pieces of code, but we need to look into it more to understand why the "proxy" object is not up to date Because it was added for this purpose precisely

**Comment by jolelievre** [comment] 2024-06-18 13:21
Just to be sure does the problem happen on migrated/symfony page? or legacy page? or both?

**Comment by hadjedjvincent** [comment] 2024-06-18 13:31
> Just to be sure does the problem happen on migrated/symfony page? or legacy page? or both?

Legacy behaviour did not changed => works fine ✅
Migrated/symfony pages => not working ❌

Related issue : https://github.com/PrestaShop/PrestaShop/issues/36351 (because `actionAdminControllerSetMedia` is used here)

> Thanks @hadjedjvincent I think there's a problem indeed around these two pieces of code, but we need to look into it more to understand why the "proxy" object is not up to date Because it was added for this purpose precisely

@jolelievre  Yup, this is what we noticed on our side! But we also noticed that `getJsDef` is not using this instance anyway.

**Comment by jolelievre** [comment] 2024-06-27 07:51
@hadjedjvincent I proposed a PR to fix addCss/addJs (under review right now) it should fix these two methods, thanks for the analysis by the way Indeed the Symfony service was not used everywhere so two different instances were used resulting in this bug

I didn't look into `getJsDef` because it's not a method of the controller, it's used via the static method `Media::addJsDef` so it should already work as expected, let us know if you detected some issue about this but it seemed to work fine in my tests

**Comment by hadjedjvincent** [comment] 2024-06-27 08:52
Thx @jolelievre the PR is working, hope this is going to be merged before the beta ;)

**Comment by paulnoelcholot** [comment] 2024-06-28 07:17
Hello @prestamodule 

I reproduce the issue with PrestaShop version 9.0.0, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Closed as completed** 2024-06-28 07:40 UTC
Labels: Bug, Minor, IN, Verified, Module, 9.0.x
