### ISSUE TITLE
product-variants not change

### ISSUE THREAD

**Issue by aalonzi** [PrestaShop/PrestaShop#17538] opened 2020-02-07 06:53 UTC
**Describe the bug**
If product has different combinations of variants, eg:
Size S Color Red
Size S Color Green
Size M Color Green
Size M Color Black

when you change from Size S to Size M, on frontend, the Color variant menù not change.

**To Reproduce**
1. Create product with two attributes (eg Size and Color) and some different variants
2. Go on frontend and see Size S/M and Color Red/Green
3. Change one attribute (es on Size M)
4. The linked attribute (eg Color) does not change, still show Red/Green

**To solve**
A comma is missing in the themes/core.js file, row 237, col ,1640.
<img width="957" alt="Schermata 2020-02-07 alle 07 48 30" src="https://user-images.githubusercontent.com/1537212/74007299-4cb72780-497e-11ea-9678-22338a5e1e2c.png">

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-02-07 08:04
Hi @aalonzi,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17457 to fix the issue.
It will be available in the next patch PS1.7.6.4.
Your ticket is a duplicate of #17437
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-07 08:05
Duplicate of #17437

**Closed as completed by khouloudbelguith** 2020-02-07 08:04 UTC
Labels: Duplicate
