### ISSUE TITLE
PS 1.7.6.7 + GDPR 1.2.1 = No more translations

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#23327] opened 2021-01-08 09:18 UTC
I've updated to 1.2.1 version but i notice now that in My Account page customers see all the GDPR part in english only,

![image](https://user-images.githubusercontent.com/16102074/103996853-b21d2500-519a-11eb-8b01-b2a0a06bea87.png)

All translations are present and correct, but the module psgdpr continue to show only the english default one even if we have 2 language installed.

There is a way to check why?

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-22 17:59
Duplicate of #22796

**Closed as completed by hibatallahAouadni** 2021-02-22 17:59 UTC
Labels: Duplicate, GDPR
