### ISSUE TITLE
Faceted search : Availability filter

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#15675] opened 2019-09-24 15:31 UTC
Hi,
When I select "In stock" in Availability filter, out of stock products (with allow order configuration) are also displayed.
They should not be displayed, or better, add another value "On order" when stock = 0 and allowed order.

PrestaShop version: 1.7.5.1
PHP version: 7

Regards.

**Comment by khouloudbelguith** [comment] 2019-09-24 15:34
Hi @guigplt,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14518
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-24 15:35
Duplicate of #14518

**Closed as completed by khouloudbelguith** 2019-09-24 15:34 UTC
Labels: Duplicate
