### ISSUE TITLE
Order_history record to state id=2 not created (sometimes)

### ISSUE THREAD

**Issue by phanie44** [PrestaShop/PrestaShop#21502] opened 2020-10-19 13:00 UTC
#### Describe the bug

After customer payment process, the order is created and its status is good (attribute "current_state" in the table "orders" is setting to "2") --> this update is done each time

And **sometimes**, the record in the table "order_history" with the state to 2 is not created.

In the logs, the line "change status oder id : 9999 01" is not created

#### Expected behavior

The record would be created each time after the payment confirmation.

#### Steps to Reproduce

Unfortunatelly, I can't reproduce it. I check the logs, but I didn't find any error 500 to the db connection, or anything else.
As it's a random error, even if I set the debug mode, I wasn't success to reproduce.

**Screenshots**

<img width="1441" alt="compare-logs-and-orders-status" src="https://user-images.githubusercontent.com/73114616/96454154-c137ab00-121b-11eb-84e8-611a3760a503.png">

#### Additional information

* PrestaShop version: 1.7.5.0.
* PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2020-10-19 13:47
Hi @phanie44,

Thanks for your report.
So your issue is related to the `ps_order_history` table? is it?
In this table, the `id_order_state` is not correct? is it? but is the BO > Order detail page => ok?

Thanks!

**Comment by phanie44** [comment] 2020-10-19 14:02
Hi,
Here are my answer

So your issue is related to the ps_order_history table? --> YES

In this table, the id_order_state is not correct? --> In fact, there is NO record created in the "ps_order_history" (and that's the problem)  (the "current_state" attribute in the table "ps_orders" is updated fine) - 

but is the BO > Order detail page => NO, as you can see in the screen, the state is to 0 (instead of 1, when it works well), and the state is not hightlight in green color)

**Comment by khouloudbelguith** [comment] 2020-10-19 14:16
@phanie44, did you check if you have any override related to this?

THanks!

**Comment by phanie44** [comment] 2020-10-19 15:02
I don't think so.
Can you tell me what is php file which could be overridden ?

**Comment by khouloudbelguith** [comment] 2020-10-19 15:14
@phanie44, for example in this path [/PrestaShop_folder/override/](https://github.com/PrestaShop/PrestaShop/tree/develop/override/), you can find overrided files.

Thanks!

**Comment by phanie44** [comment] 2020-10-19 15:53
Yes I have a few, but I think they don't work on these table, and more of all, the issue occurs random way

**Comment by khouloudbelguith** [comment] 2020-10-19 16:00
@phanie44, how can I reproduce the issue?
I need all the steps to reproduce it.

Thanks!

**Comment by phanie44** [comment] 2020-10-20 09:32
I understand, but for the moment I didn't succeed to see the difference between the order which the "ps_order_history" is created of not.

After credit card payment, then the order is created and the status is assigned to "2 - payment accepted", and the order_history is created.

I'm going to investigate more, but if on yourside you have a process to recommand me to test, it could be great

Thanks
Regards.

**Comment by khouloudbelguith** [comment] 2020-10-20 09:37
@phanie44,

>After credit card payment

Have you tried to contact the module developer?
Did you use only this payment module when the issue occurs?

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-09 09:37
Hello @phanie44 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-09 09:37 UTC
Labels: Bug, BO, Can't reproduce, Order, 1.7.5.0

**Comment by phanie44** [comment] 2021-01-21 11:23
Hi.
After searching again, yes it seems the issue came from the payment module.
Thanks a lot for all your answer.
Regards.

**Comment by hibatallahAouadni** [comment] 2021-01-21 11:50
@phanie44 glad to know :tada:
