### ISSUE TITLE
DELETE attribute BO error 404

### ISSUE THREAD

**Issue by dev-studio** [PrestaShop/PrestaShop#26585] opened 2021-11-12 08:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In PS version 1.7.7.7, a 404 error occurs when deleting attributes:
DELETE | /admin/index.php/sell/catalog/products/attributes/1990 |  [HTTP/1.1 404 Not Found 950ms]
How to deal with it?

### Steps to reproduce

1. Go to edit product with attribute
2. Go to tab attributes
3. Delete one of attribute from list

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.2.34

**Comment by hibatallahAouadni** [comment] 2021-11-12 08:23
Hello @dev-studio 

I think you mean a combination, is that so?
If so, I didn't manage to reproduce the issue with PS1777, PS1778 and PS1780, see the attached screen record below:

https://watch.screencastify.com/v/uye9wHM0oQ0hW74J0B9P

Please check and feedback.
Thanks!

**Comment by dev-studio** [comment] 2021-11-12 10:05
Hi, yes it's about the combination tab.
Here is a screen record:
https://drive.google.com/file/d/1n-OzoCxUXLEUc-FnLCxTkaM6an5drG2V/view

**Comment by florine2623** [comment] 2021-11-15 11:21
Hello @dev-studio ,

I also tried on my end, but I can't reproduce your issue.
How did you create the combination ? Through the BO directly ?
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-02 08:30
Hello @dev-studio 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-02 08:30 UTC
Labels: Bug, BO, Attributes, Combinations, Invalid
