### ISSUE TITLE
BO product edit can't see and edit description and short description PS ver 1.7.8.0 - html boxes dissapear

### ISSUE THREAD

**Issue by TrzniCentar9402** [PrestaShop/PrestaShop#26498] opened 2021-11-01 23:00 UTC
When I go to admin panel to edit (change description) my product , I can't see my text in section description and short description. This is a problem when I upgrade from 1.7.4.0 to 1.7.8.0. My previous version works excellent. This version 1.7.8.0 
have a lots of bugs. There is also bug in email template, I can't edit html in translate option, but I can edit txt version of email template (order_confirm). My shop is on Serbian language only.

In front office I see description of products but in back office not

In Previous version 1.7.4.0 everything was ok.
What to do?

![PS problem](https://user-images.githubusercontent.com/93556828/139753064-770542e4-4426-4d23-87a1-e9e514247033.png)

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by NeOMakinG** [comment] 2021-11-02 08:40
Hey @TrzniCentar9402, looks like an assets issue going wrong on upgrade, wdyt @atomiix ?

**Comment by TrzniCentar9402** [comment] 2021-11-02 08:49
Thanks @atomix for your reply. Yes, the problem start after I upgrade my PS on 1.7.8.0. 
I made backup on October 30th, but I do a lot of work on October 31st. I did not backup my work after that and before I upgrade new version of PS. So I have 2 options. To restore my backup and lose my work, or to do something in new version to work (but I dont know what).

**Comment by BullyBlue** [comment] 2021-11-02 09:08
Not an expert here - but had the same issue.

was solved after performing:
→ delete cache manually
→ do all required translations
in some cases i had to wait overnight - might be some cache problem
→ debug mode might as well help

Maybe it helps :)

**Comment by TrzniCentar9402** [comment] 2021-11-02 09:13
Thanks @BullyBlue , but if I delete my translate I think I will have big problem, because my PS shop is only on Serbian (BO and FO). English language is closed (not deleted, only closed). I clean the cache, and I don't use Cache option.

**Comment by florine2623** [comment] 2021-11-02 11:08
Hello @TrzniCentar9402 ,

I did the following steps :
- Installed shop in 1.7.4.0
- Installed Serbian pack
- Only activate Serbian language via BO
- Installed 1-click upgrade v4.13.0
- Upgraded my shop to 1.7.8.0 :
<img width="1197" alt="Screenshot 2021-11-02 at 12 01 08" src="https://user-images.githubusercontent.com/16019289/139835053-fcc86e6d-62ab-4728-bfb3-999285d17fa3.png">

- Go to BO > Catalog > Product page :

<img width="1204" alt="Screenshot 2021-11-02 at 12 06 14" src="https://user-images.githubusercontent.com/16019289/139835470-f2925a6a-371e-4651-ba8e-6c9d386a83f3.png">
No error, display is normal.

Can you make sure your system requirements are compliant with your version of PrestaShop :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

If you have any overrides, please check if there is a conflict with this newer version of PS.
Thanks!

**Comment by TrzniCentar9402** [comment] 2021-11-02 12:15
Thanks @florine2623  I do the same.
- I check phppsinfo its ok
- I upgrade Serbian pack
- I have latest version of 1-click and PS
- but still description and short description are disabled (they show me for a second and then dissapear).

**Comment by florine2623** [comment] 2021-11-02 12:55
Ok, noted.

What about the following elements ?
> Can you make sure your system requirements are compliant with your version of PrestaShop :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

> If you have any overrides, please check if there is a conflict with this newer version of PS.

**Comment by TrzniCentar9402** [comment] 2021-11-02 12:56
@florine2623  requirements are ok. Checked.
My previous version PS 1.7.4 was work excellent, now 1.7.8.0 bugs everywhere (products description in BO, email template is ruined. So I think to restore my backup and all work gone :(

**Comment by florine2623** [comment] 2021-11-02 13:15
I can't reproduce your case sorry. Let me know how the restoration of backup works. 

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by TrzniCentar9402** [comment] 2021-11-04 01:27
Restoring from backup was disaster. Only if I have the new version 1.7.8.0 BO and FO are ok with the same problem. When I enable debug mode, my FO gone "wild". I inspect this html place for description and I see some information that something not work, but I don't understand how to fix that. Here is a screenshots.

This problem I have in html table to write description. The sam problem I have when I try to edit html email templates
![4000](https://user-images.githubusercontent.com/93556828/140241702-4527fab4-616e-4af3-b629-fcefee05458d.png)

This is inspect this html sector for description product
![3000](https://user-images.githubusercontent.com/93556828/140241795-6d009832-17fd-4b53-901b-5fd1bb928b90.png)

This is FO when is debuging enabled
![Front office after star bug debugger](https://user-images.githubusercontent.com/93556828/140241864-2c79898d-6e06-4bf2-867d-5ee6f93633f0.png)

SOMEONE CAN HELP?

**Comment by TrzniCentar9402** [comment] 2021-11-04 01:42
I am very dissapointed after a years of using prestashop. I send message to PS support and they aks me to pay for support. So, you sirs made this upgrade, make a mess and than you want to charge to solve your mess? Its a shame.

**Comment by Oksydan** [comment] 2021-11-04 08:16
@TrzniCentar9402 
1. Turn off every module that isn't made by prestashop and overrides. You can do it via BO.
2. Check if problem persists. 
3. If problem still exist. Hire prestashop dev to investiagate./ If problem is solved. One of third party module is breaking some stuff. You have to figure it out by yourself or hire someone to do it for you.

**Comment by TrzniCentar9402** [comment] 2021-11-04 11:36
Thanks @Oksydan 
I turn off every single module that isn't made by prestashop. Problem persist. 

I see every text blok with html option (product, description of index page, email templates ... is blank like not exist, but it 's exist. What to do next? Do you have some idea?

**Comment by Oksydan** [comment] 2021-11-04 11:48
@TrzniCentar9402 hire someone to fix your problem. 
We can help you here if problem exists on every prestashop installation but this case is only related to your installation. 
Remember if you are upgrading shop do it first with copy, not in production.

**Comment by TrzniCentar9402** [comment] 2021-11-04 11:54
@Oksydan  I made backup of files and database before I upgrade, but when I restore from my backup, the BO was disaster (full of command instead normal text). The similar things was happened before couple of years and as I remember I was cleaned complete and install fresh version like first time, but now to do that with so many product will like "kill me". 

The problem is html box dissapear every where. How to fix that html boxes?

**Comment by TrzniCentar9402** [comment] 2021-11-04 12:00
@Oksydan when I inspect this html I found some command "style=visibility: hidden;" How to change that? what 
command is opposite for "hidden"?

I round this command
![5000](https://user-images.githubusercontent.com/93556828/140310121-cc0079ed-70ac-4731-885b-18ed56d75942.png)

**Comment by TrzniCentar9402** [comment] 2021-11-04 12:25
@Oksydan my friend, when I desable my serbian language, and enable english, and set english as language of shop, I see html. 

Do yo know how t o fix this for serbian language?

Thanks

**Comment by TrzniCentar9402** [comment] 2021-11-04 12:36
FINALLY SOLVED BY MYSELF 

THANKS TO ALL WHO TRY TO HELP ME :)

**Comment by hibatallahAouadni** [comment] 2021-11-04 16:42
Hello @TrzniCentar9402 

Could you please share how did you fix the issue :pray: (to help other people who may face the same issue).
Glad to hear that you solved it :tada: 

Closing the issue :wink:

**Closed as completed by hibatallahAouadni** 2021-11-04 16:42 UTC
Labels: Bug, BO, International, Autoupgrade, 1.7.8.0, Invalid

**Comment by TrzniCentar9402** [comment] 2021-11-04 19:02
Oh I was thinking everything is ok, but now it's a problem oin front office in upper right corner where is "login" and cart. Instead "Korpa" (cart on serbian) staying command promt "Shopping_cart" and under that I see "Korpa" Now I working to slove this problem.

I will no longer problem with html boxes, but thi is new one. When I fix that I will explain. If someone know how to fix this problem with cart, please write. Thanks.

**Comment by Krismm** [comment] 2021-11-04 19:44
Hello
I have the same problem after upgrading from 1.7.7.3 to 1.7.8.0
@TrzniCentar9402 how did you solve your problem?

**Comment by TrzniCentar9402** [comment] 2021-11-04 20:00
@Krismm 
I've done a lot of different attempts. I will skip all (maybe) irrelevant steps.
- First I turned off (disabled, did not delete and did not uninstall) all modules that are not prestashop.
- Then I went to Localization -> languages turned on English and turned off Serbian
- set english as default instead of Serbian.
- refreshed the page with the edited product and an htm box with English language appeared
- then I returned to the Language and included the Serbian language
- refreshed the page with the edited product again and there was an html box
- then I went to Prevode and updated the Serbian language
- then I returned to languages and switched off English and Serbian remained active
- I refreshed the page with the edited product with ctr-F5 and an html box appeared in Serbian

I no longer have a problem in BO lli I had a problem in FO that there are no icons for cart, login and language selection. Now I'm trying to solve that problem.

**Comment by TrzniCentar9402** [comment] 2021-11-04 20:01
@Krismm "Prevode" is "Translate"

**Comment by TrzniCentar9402** [comment] 2021-11-04 20:04
@Krismm All module outside Prestashop developers I set active again as before the update and BO works normal (I still have html boxes). Only this icons in FO is still problem (new problem)

**Comment by TrzniCentar9402** [comment] 2021-11-04 20:07
@Krismm  And php is 7.4

**Comment by TrzniCentar9402** [comment] 2021-11-04 21:20
And I stuck. This icons are empty
"displayNav2":["ps_languageselector","ps_currencyselector","ps_customersignin","ps_shoppingcart"]
"displayFooterBefore":["ps_emailsubscription","ps_socialfollow"],

Anyone can help?

**Comment by TrzniCentar9402** [comment] 2021-11-05 17:00
Solved by me.

**Comment by wfpaisa** [comment] 2021-12-21 22:52
I have the same problem, after a long time, I solve just clear data:
![image](https://user-images.githubusercontent.com/1735752/147007842-43ea330a-cfb0-46c4-aec9-4709ca79b91e.png)
