### ISSUE TITLE
Product Module configuration page backoffice issue

### ISSUE THREAD

**Issue by kaydm** [PrestaShop/PrestaShop#12542] opened 2019-02-12 13:17 UTC
If there's a "." (dot) in the SEO Meta Description fo the product you cannot access any product module configuration page.

**Comment by khouloudbelguith** [comment] 2019-02-12 13:28
HI @kaydm,

Have you the same issue described in this ticket: #11911?
Thanks!

**Comment by kaydm** [comment] 2019-02-12 14:22
Hi @khouloudbelguith, that is correct. Thanks.

**Comment by khouloudbelguith** [comment] 2019-02-12 14:24
@kaydm, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11923 to fix the issue.
It is fixed in the next release PS1.7.5.1.
Your ticket is a duplicate of #11911
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-12 14:24
Duplicate of #11911

**Closed as completed by khouloudbelguith** 2019-02-12 14:24 UTC
Labels: BO, Duplicate

**Comment by kaydm** [comment] 2019-02-12 14:31
> @kaydm, here's the PR: #11923 to fix the issue.
> It is fixed in the next release PS1.7.5.1.
> Your ticket is a duplicate of #11911
> So, I close it.
> Thanks!

Thanks, alredy fixed it in my 1.7.5 store.
