### ISSUE TITLE
Error executing product save on PHP 7.2.3

### ISSUE THREAD

**Issue by xonox** [PrestaShop/PrestaShop#10479] opened 2018-09-18 15:09 UTC
**Bug**

Error validating if product is a pack.

classes/Pack.php line 84

Cannot declare self-referencing constant 'Pack::STOCK_DEFAULT_TYPE'

**Reproduce**
Execute a method call :

$product = new Product($id);
$product->save();

**Screenshots**
![error1](https://user-images.githubusercontent.com/1177758/45696688-07f9d900-bb5c-11e8-9958-9c628f05af86.png)
![error2](https://user-images.githubusercontent.com/1177758/45696692-0af4c980-bb5c-11e8-8c21-2985c38b6cd9.png)
![error3](https://user-images.githubusercontent.com/1177758/45696694-0cbe8d00-bb5c-11e8-8a70-06a366ba73dd.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2.3

**Comment by khouloudbelguith** [comment] 2018-09-18 15:16
Hi @xonox,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9654
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-18 15:16
Duplicate of #9654

**Closed as completed by khouloudbelguith** 2018-09-18 15:16 UTC
Labels: Duplicate

**Comment by xonox** [comment] 2020-06-19 13:18
Sorry again,


This problem seems a bit weird.

But I stumble upon this problem every time.

The problem seems to be on around line 241 (prestahop 1.7.5.6)

public $pack_stock_type = Pack::STOCK_TYPE_DEFAULT;


Error: Cannot declare self-referencing constant 'Pack::STOCK_TYPE_DEFAULT'


Because Pack is a subclass of Product.

And in the super class Product it seems not be possible reference a subclass Pack constant.

I makes some sense.


Not sure what is causing this issue.

But this issue is very common to me. Happens every time in every host I try.

If in the Product class I replace public $pack_stock_type = Pack::STOCK_TYPE_DEFAULT; with public $pack_stock_type = 3; the error goes away.


I develop a Prestashop extension.

This happens when I try to update the stock.

But now I tested in a docker container and the error happens even if I call the product save method.

It might be the new prestashop version makes use of this constant before.

It seems this is getting more problematic in new versions.


Could this be fixed and simply replace the constant reference with the literal value of 3?

**Comment by pouzarm** [comment] 2020-08-24 10:33
Error still note resolved... 1.7.3.0 is ok .. but at least 1.7.5.0 and higher version (including 1.7.7.0 beta) still not working... (doesn't matter what PHP used)

Changing value to 3 is still only fix.

**Comment by dylan-ramos** [comment] 2021-09-17 19:38
Hello,

On my side, this error appears when the "ProductCore" class is called in the classes of my module which inherits from "ObjectModel".

Ex:
`use ProductCore as Product;`
or
`$product = new ProductCore($id_product, false, $id_lang, $id_shop, $context);`

The problem is solved by replacing "ProductCore" with "Product".

--

Bonjour,

De mon côté, cette erreur apparaît lorsque la classe « ProductCore » est appelée dans les classes de mon module qui hérite de « ObjectModel ».

Ex :
`use ProductCore as Product;`
où
`$product = new ProductCore($id_product, false, $id_lang, $id_shop, $context);`

Le problème est résolu en remplaçant « ProductCore » par « Product ».
