### ISSUE TITLE
Online Visitors doesn't count users

### ISSUE THREAD

**Issue by testforshopify** [PrestaShop/PrestaShop#15937] opened 2019-10-14 14:50 UTC
**Describe the bug**
Online Visitors option doesn't calculate visitors. Cart count works properly. Tried to visit a website from various pc and IPs. tried to reinstall and reset plugins, enabled Save page views for each customer" option in the "Data mining for statistics" 

**Screenshots**
http://prntscr.com/pj4bm4

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-10-14 16:48
Hi @testforshopify,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0.
https://drive.google.com/file/d/13S1iDrzuDPDuoyFd1A_lBP9Hw208h04U/view
![image](https://user-images.githubusercontent.com/16067358/66768477-f562e800-eeb2-11e9-8d73-2654478e1e61.png)
Thanks to reset your module `dashactivity`, check & feedback.

**Comment by khouloudbelguith** [comment] 2019-11-13 07:46
Hi @testforshopify,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-13 07:46 UTC
Labels: Bug, BO, Dashboard, No change required, 1.7.6.0, Dashactivity
