### ISSUE TITLE
CHECK-OUT ISSUE

### ISSUE THREAD

**Issue by iservng** [PrestaShop/PrestaShop#12671] opened 2019-02-22 11:34 UTC
Hello
i installed prestashop version 1.7 on an xampp-server and the check-out process will proceed successfully, and show that the transaction is confirmed. Then i installed prestashop on Hostagator live-server and when you select a product, the check-out process will start by taking your name, address, ... when it gets to payment, and you select the payment-type, then it will show an error page that says that the page is not working. please i need help

I also installed the version 1.6 on Hostagator live-server then when i select pay-by-cheque, it will sent another error message to say that the email has some issues please i need serious help. thank you

the domain is resorts.iservng.com

**To Reproduce**
1. Go to 'resorts.iservng.com'
2. Click on product.'
3. Folowing the check-out

**Screenshots**
https://snag.gy/dfLlor.jpg

**Additionnal information**
PrestaShop version: 1.7 
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-02-22 13:25
Hi @iservng, 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by iservng** [comment] 2019-02-22 19:17
Hello
To reproduce this particular issues please do the following
1. Go to www.resorts.iservng.com
2. Select a room of your choice
3. Follow the check-out process

Bellow is a snapshot off the last-step of the check-out process.
(a). i have select pay by check
(b) i have selected the ORDER WITH AN OBLIGATION TO PAY check -box

[image: image.png]

(c) So when you click on that button that says "ORDER WITH AN OBLIGATION TO
PAY" you will get the below snapshot

https://snag.gy/dfLlor.jpg

//////////////////////////////////////////////////////////////////////////////////////////////////////////

The information you asked for are as follows

   - host                                          =      Hostgator
   - Apache version                        =      2.4.38
   - laptop OS                                =      Windows
   - server OS                                =      LINUX
   - server setup and configuration
   - PrestaShop version (source)   =    version 1.7 (the latest version)
   - debug mode report
   - PHP error logs
   - apache error log
   - javascript console log
   - screenshots
   - mysql                                   =      5.6.41-84.1

**Comment by khouloudbelguith** [comment] 2019-02-25 15:17
Hi @iservng,

A blank page & the error 500 cannot help us to reproduce the issue.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Also, I tried to access to your link, I have this
![image](https://user-images.githubusercontent.com/16067358/53347156-cd6d4700-3918-11e9-86df-c1e72af2b82d.png)
Thanks!

**Comment by iservng** [comment] 2019-02-26 02:39
Hello
I want to thank you for reaching out to me. i hosted my prestashop site
with HOSTGATOR and found their service to be very poor, so i cancelled. Now
i have checked prestashop site and found they have an official hosting
partners called 1&1 HOSTING, so am going to host with them to have improved
services. WHAT IS YOUR KIND OPINION SIR ?

**Comment by khouloudbelguith** [comment] 2019-02-26 07:33
Hi @iservng, to understand your issue we need more details, we need to retrieve the PHP error log and the debug mode report.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-29 08:41
Hi @iservng,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-29 08:41 UTC
Labels: Bug, FO, No change required
