### ISSUE TITLE
The shop is broken after Upgrading from local archive extracted from develop branch (9.0.0)

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#33610] opened 2023-08-12 12:37 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The upgarde is done with success.
But, the shop is not accessible ❌ 😞 please check the screen record below:

[Upgrade_613.webm](https://github.com/PrestaShop/autoupgrade/assets/23308427/1ea0247a-1047-4a4c-b06f-9c2fc0b1b53e)

Even when I tried to enable the debug mode, no success ❌ 

![image](https://github.com/PrestaShop/autoupgrade/assets/23308427/d44a93a5-e1a2-4dba-a828-3df62815cb87)

### Expected behavior

The shop should be accessible as usual

### Steps to reproduce

1. git clone https://github.com/PrestaShop/PrestaShop.git
2. cd PrestaShop
3. composer install
4. make install OR make assets
5. Install your shop by access to PrestaShop/install-dev
6. then under PrestaShop, execute this command : `php tools/build/CreateRelease.php --version="9.0.0"` to create an archive
7. Install a new shop with stable version 8.0.5 or 8.1.1
8. BO>Module Manager
9. Install the latest version of `1-Click autoupgrade` module: 4.16.2
10. Copy the generated zip and xml file from PrestaShop (develop branch), you can find it under **tools>build>releases>9.0.0_date**
11. and paste it under **admin-dev>autoupgrade>download**
12. Back to BO>1-Click autoupgrade module
13. Choose Local archive as Channel
14. Select your zip and xml file, put 9.0.0 as number of version
15. Save
16. Upgrade
17. Success
18. Try to access BO > See error > the shop is broken with 500 error

### PrestaShop version(s) where the bug happened

8.0.5 or 8.1.1

### PHP version(s) where the bug happened

7.4 & 8.1 

### If your bug is related to a module, specify its name and its version

1-Click autoupgrade v4.16.2

**Comment by Hlavtox** [comment] 2023-08-12 12:42
It says on the video that you are running PHP 7.4. You can't upgrade to Prestashop 9.0 if you are not running PHP 8.1.
Can you provide another video with the correct PHP version? What is the issue after upgrading?

> Even when I tried to enable the debug mode, no success ❌

You did not enable debug mode if we see that message, go to config/defines.inc and enable it, then you will see the full callstack. But the issue is probably simple, just a missing feature flag in the database. However, it should not crash on it. Ping @jolelievre

**Comment by Hlavtox** [comment] 2023-08-13 08:03
@hibatallahAouadni aaaand I don't think inability to upgrade to develop branch is a critical issue 😛

**Comment by MatShir** [comment] 2023-08-25 09:46
I agree. The issue will be tackle probably around the feature freeze even tho we should do PR on the auto upgrade when we can

**Comment by MatShir** [comment] 2023-08-25 09:48
I added the milsetone and I'm going to lower the severity

**Comment by florine2623** [comment] 2024-01-18 16:45
Hello all,

I did an upgrade from 8.0.5 to 9.0.0 using the CreateRelease.php command, and with latest version of autoupgrade v5.0.0.
I'm using PHP 8.1.13.

But I encountered an error during the upgrade :

<img width="1440" alt="Screenshot 2024-01-18 at 17 40 42" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1a5e511d-d768-4a54-a075-912f8a04f6fa">

**Comment by Quetzacoalt91** [comment] 2024-05-07 09:47
There are several problems in this issue:
* The issue with the feature flag has been fixed in: https://github.com/PrestaShop/autoupgrade/pull/681 (Coming soon with the next release)
* The issue about composer will be fixed with a planned improvement that allow the proper channel to be selected depending on the running PHP version, preventing merchants to upgrade to a version where PHP is not compliant (Duplicates https://github.com/PrestaShop/PrestaShop/issues/32745)
* The issue about AppKernel has been solved with https://github.com/PrestaShop/autoupgrade/pull/679 (Coming soon with the next release)

Thanks

**Closed as completed by Quetzacoalt91** 2024-05-07 09:47 UTC
Labels: Bug, Minor, BO, Autoupgrade, Verified, Module, 9.0.x, Backlog SUE
