### ISSUE TITLE
Fresh app gives 500 error on admin page when different language used other than English

### ISSUE THREAD

**Issue by burakertr** [PrestaShop/PrestaShop#35870] opened 2024-04-08 22:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am trying to solve this problem but could not be able to do it. I have installed fresh by using Turkish language, all goes well until I try to go to admin panel. If I choose Turkish language on installition, admin page gives Invalid "it-IT" locale error. The error occurs on only admin page where profile language is Turkish. 

If I fresh install with english language all goes well and I am able to login to admin panel. 

What could be the reason for it? I think it is a bug.
![Ekran Görüntüsü - 2024-04-09 01-50-08](https://github.com/PrestaShop/PrestaShop/assets/38433154/22b0790b-5f4e-43bc-a69d-8e46b004101c)

### Steps to reproduce

1. Install prestashop with language Turkish,
2. Try to enter admin page after installition

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.2.7

**Comment by florine2623** [comment] 2024-04-09 07:40
Hello @burakertr ,

Please change your PHP version to 8.1.
https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

I have installed PS 8.1.5 with Turkish language. BO and FO are working as expected.

<img width="997" alt="Screenshot 2024-04-09 at 09 38 38" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9f54c33b-a343-4086-a30a-9dd77d9dc84e">

<img width="1138" alt="Screenshot 2024-04-09 at 09 40 23" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1fc712ad-76e4-40a6-8345-f0cbc1524171">

<img width="1433" alt="Screenshot 2024-04-09 at 09 40 28" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/241e7b5d-2d64-445b-9d70-501107a0ed5c">

I'm closing your issue as I can't reproduce it.

**Closed as completed by florine2623** 2024-04-09 07:40 UTC
Labels: Bug
