### ISSUE TITLE
Etat de commande

### ISSUE THREAD

**Issue by Lolamycompanero** [PrestaShop/PrestaShop#17244] opened 2020-01-20 11:36 UTC
Unable to update order status.

**Describe the bug**
A clear and concise description of what the bug is: ****When for example we want to change the status of the order to cancel it ect .. no updates do this.****

**To Reproduce**
1. Go to '...**orders**'
2. Click on '
**update status**....'
3. Scroll down to '**change state**....'
4. See error, **no update**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: **1.7.6.1**

PHP version: N/A

**Comment by sarahdib** [comment] 2020-01-21 08:08
Hello @Lolamycompanero 

I didn't reproduce the issue using PrestaShop 1.7.6.1 : 
https://drive.google.com/file/d/1nM1xOW_tUHFwz931UBwif5LS-1lB4nVW/view

Do you have an error ?
The debug mode is activate ? 

Thank you

**Comment by khouloudbelguith** [comment] 2020-02-24 08:18
Hi @Lolamycompanero,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-24 08:18 UTC
Labels: Bug, BO, Order, No change required, 1.7.6.1
