### ISSUE TITLE
Photo gallery scroll down broken after change attribute

### ISSUE THREAD

**Issue by dgtn-va** [PrestaShop/PrestaShop#12218] opened 2019-01-18 14:42 UTC
For product with more than 5-6 pictures, the scroll down of photo gallery doesn't work after change an attribute.

How to reproduce?

Create or edit an product and:

1. Add 6 pictures or more
2. Generate some combinaisons/declinaisons

Go to the product page:

1. Display photo gallery
2. Scroll down with bottom arrow
3. Change an or many product attributes
4. Display photo gallery again
5. Try to scroll down with bottom arrow... Nothing.
6. Close photo gallery
7. Try to scroll down with bottom arrow again... Nothing.
8. Simple refresh the page (F5).
9. Display photo gallery again
10. Try to scroll down with bottom arrow... That's works now.

Screenshots:
https://i.imgur.com/7cfYQnU.jpg
https://i.imgur.com/G3OZnX5.jpg
https://i.imgur.com/GXcZyAV.jpg

PrestaShop version: 1.7.3.x, 1.7.4.x, 1.7.5.x
PHP version: 7.1, 7.2

**Comment by khouloudbelguith** [comment] 2019-01-18 14:46
Hi @fujitsuDev,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12064
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2019-01-18 14:46
Duplicate of #12064

**Closed as completed by khouloudbelguith** 2019-01-18 14:46 UTC
Labels: Duplicate
