### ISSUE TITLE
When writing a private note strange characters are adding in the text

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14604] opened 2019-07-12 07:12 UTC
I just upgrade to the 1.7.6 version and now when I write a private note; for example before saving. After saving it adds strange characters to the text

![Screenshot 2019-07-11 at 19 13 16](https://user-images.githubusercontent.com/46492443/61074629-0b728f80-a410-11e9-8074-820151496806.png)

![Screenshot 2019-07-11 at 19 13 34](https://user-images.githubusercontent.com/46492443/61074638-10cfda00-a410-11e9-9a3c-e12fd51c9b39.png)

_Originally posted by @01park in https://github.com/PrestaShop/PrestaShop/issues/13428#issuecomment-510596168_

**Comment by khouloudbelguith** [comment] 2019-07-12 07:43
@marionf, I have the same issue with PS1.7.6.0 fresh installation
![image](https://user-images.githubusercontent.com/16067358/61111287-24675900-a481-11e9-8e70-8cc91d97354c.png)

Thanks!

**Comment by PierreRambaud** [comment] 2019-07-12 08:09
Done with https://github.com/PrestaShop/PrestaShop/pull/14605 Don't forget to clear your browser cache because of javascript files

**Comment by 01park** [comment] 2019-07-12 09:29
Thank you, this worked

**Comment by 01park** [comment] 2019-07-15 09:46
Sorry, bring this back up. But the problem is not 100% solved.

When I first update the private note. Everything is saved and looks fine, but when I change the order status to  shipped, then all notes get mixed up again and it shows strange characters again.

**Comment by matks** [comment] 2019-07-17 12:29
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14605

**Closed as completed by matks** 2019-07-17 12:29 UTC
Labels: Bug, Trivial, BO, Order, Regression, Fixed, 1.7.6.0
