### ISSUE TITLE
Duplicate minus sign on discount value in cart

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#23644] opened 2021-03-15 09:20 UTC
#### Describe the bug

There is a duplicate minus (-) sign in front of value in cart.
The value of discount changes.

#### Expected behavior

There should be just one: - $10.99 instead of --$10.99

#### Steps to Reproduce

Create discount coupon, enter in cart.

**Screenshots**

![duplicate sign](https://user-images.githubusercontent.com/31688689/111130777-e553aa00-8577-11eb-94e9-3738eb911b4e.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-03-15 11:18
Hello @mrabsinthe 

I didn't manage to reproduce the issue with PS1.7.7.0, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/111145440-89455180-8588-11eb-8da2-3c84fd8336e3.png)

Please check and feedback.
Thanks!

**Comment by mrabsinthe** [comment] 2021-03-15 12:25
Thank you, I have been also able to see it working correctly - in Chrome. The issue with duplicate minus sign seems to be in Firefox, Edge and also Samsung mobile browser. I tested in private mode and discovered another glitch. When I first enter code for 10% discount (order without shipping), the price is displayed correctly, ie. -£3.48. As soon as I enter another coupon for free shipping, the discount changes from 3.48 to 2.76 and the duplicate appears.
The discount should still be the same - it is 10% off order without shipping. This is in all browsers, incl. Chrome, Edge, Firefox, and mobile browsers.
The duplicate minus sign should not be there. This duplicate appears in Firefox, Edge, and Samsung mobile browser.
See the below screen recording please:

https://user-images.githubusercontent.com/31688689/111152178-bf86cf00-8590-11eb-83fb-4ed0fcde631c.mp4

I'm sure that you can replicate now.

**Comment by hibatallahAouadni** [comment] 2021-03-17 15:33
Hello @mrabsinthe 

That's totally odd! even when I followed your steps, I didn't manage to reproduce the issue on FireFox:

![image](https://user-images.githubusercontent.com/23308427/111494137-83916c80-873e-11eb-9515-f611886d5832.png)

Please check and feedback.
Thanks!

**Comment by mrabsinthe** [comment] 2021-03-17 17:34
How exactly did you create that discount? Is it value of £15.43 or is it some percentage? Because if the voucher is in specific amount (Actions->Apply a discount->Amount), all is OK. The issue is when the discount is in percentage as mentioned. Create new cart rule and select Apply a discount - Percent (%) and type 10 in Value box. See below:
![Screenshot_2021-03-17 Cart Rules Edit Test Discount % • Absinthe Test Store](https://user-images.githubusercontent.com/31688689/111511507-1c2fe880-874f-11eb-9620-16f6b011ced6.png)
Now you can duplicate the issue, when this code is on its own, all is OK but as soon as you add another one for free shipping:
![Screenshot_2021-03-17 Cart Rules Edit Test Free Shipping • Absinthe Test Store](https://user-images.githubusercontent.com/31688689/111511640-3c5fa780-874f-11eb-91b2-c94df4f3b3d9.png)
You can see that the discount value will change and double minus sign will appear.
Also, why is price of your product £29.84 and mine £34.80 in vanilla?

**Comment by florine2623** [comment] 2021-03-18 11:18
Hi @mrabsinthe ,

_why is price of your product £29.84 and mine £34.80 in vanilla?_
-> the currency is different

I create my cart rules like you showed in your message.
I can't reproduce the issue in neither Chrome, Safari, nor Firefox.

![Capture d’écran 2021-03-18 à 12 12 58](https://user-images.githubusercontent.com/16019289/111617776-da04b680-87e3-11eb-9010-cf1b0fd06611.png)

Minus sign is only displayed once.

despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thanks!

**Closed as completed** 2021-03-18 11:19 UTC
Labels: Bug, FO, Can't reproduce, Discounts, Cart rules, Shopping carts FO, 1.7.7.0

**Comment by mrabsinthe** [comment] 2021-03-18 11:51
@florine2623 Jumped to soon may I ask? I would expect that you would be more interested to find out why you cannot duplicate this bug...? I did mention it's a vanilla install so no possible customization. If you notice in my video, free shipping has a higher priority, it is ABOVE the 10% discount. Now, please change priorities of your cart rules so the free shipping will be ABOVE the 10% discount. Perhaps we'll be on the same side than... and I hope that you re-open this ticket and I'll not have to create same ticket again.

**Comment by mrabsinthe** [comment] 2021-03-23 12:04
@florine2623 @hibatallahAouadni will this remain closed so I have to create a new ticket?

**Comment by hibatallahAouadni** [comment] 2021-03-23 13:34
Hello @mrabsinthe 

Could you please provide more clearer steps to reproduce the issue, cause with these steps neither @florine2623 nor me could reproduce the issue.
If I reproduce the issue, I will reopen it :wink: 

Thanks!

**Comment by mrabsinthe** [comment] 2021-03-31 18:27
@hibatallahAouadni  @florine2623  Sorry for my late reply, I wanted to test this issue on 1.7.7.3
I wasn't able to replicate the issue with double minus sign in 1.7.7.3 however I'm still able to replicate the issue with a wrong discount calculation.
1a/ create cart rule free shipping - priority 1
1b/ create cart rule 10% discount Order (without shipping) - priority 2
2/ leave just one carrier and increase price for shipping to €25 for example
3a/ add product to cart, you get something like this:
![Cart I](https://user-images.githubusercontent.com/31688689/113192478-182bbc80-925f-11eb-8849-0da6f83909b5.png)

3b/ apply 10% discount code (notice my discount of -€1.34 very bottom line):
![Cart II](https://user-images.githubusercontent.com/31688689/113192416-02b69280-925f-11eb-9f63-d8eb99828571.png)

3c/ now apply also shipping code (notice the very bottom line will change in my case to -€0.18)
![Cart III](https://user-images.githubusercontent.com/31688689/113192344-ec103b80-925e-11eb-9239-ad73ddadd9d4.png)

The discount at the bottom should stay the same, because we created rule 10% off order (without shipping) so why is it changing?

If you change the priority for free shipping to 3, you'll get the correct discount information:
![Cart IV](https://user-images.githubusercontent.com/31688689/113192730-6d67ce00-925f-11eb-9f9f-ebeeb563ba5f.png)
