### ISSUE TITLE
Error 500 with to much combinations

### ISSUE THREAD

**Issue by Kingbera** [PrestaShop/PrestaShop#10396] opened 2018-09-12 09:10 UTC
**Describe the bug**
In my prestashop site when a product has more than hundreds combinations in backoffice I can't access to product from back office. I have just error 500. 
I had combinations by import a csv file.

**To Reproduce**
1. Go to a product with more than 200 combinations and try to open in back office to modify.
2. Error  500

**Additionnal information**
PrestaShop version: 1.7.3.3
PHP version: 5.6.33-0+deb8u1 
![screenshot 32 _li](https://user-images.githubusercontent.com/43202455/45414730-5569d800-b67c-11e8-8228-64aab9f6b194.jpg)

**Comment by khouloudbelguith** [comment] 2018-09-12 09:16
Hi @Kingbera,

We are aware of this issue, it is still in progress.
Your ticket is a duplicate of #9809
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-12 09:16
Duplicate of #9809

**Closed as completed by khouloudbelguith** 2018-09-12 09:16 UTC
Labels: Duplicate
