### ISSUE TITLE
Wrong breadcrumb path in Category and Product views

### ISSUE THREAD

**Issue by georgelouk** [PrestaShop/PrestaShop#21759] opened 2020-11-04 18:45 UTC
#### Describe the bug

I am creating a new category which has a parent category, but at FO when i view the category the breadcrumb has an extra subcategory that never was added by me.

For example i have category structure :

Bride 
with subcategories T-Shirts and Dresses
I create a new subcategory Bags under Bride

The breadcrumb is not Home / Bride / Bags as expected but Home / Bride / T-Shirts / Bags

Same issue is happening also at product view of "Bags" products.

#### Expected behavior

The expected behavior is the breadcrumb to display the correct path at category and product views.

#### Steps to Reproduce

1. Create a Category
2. Create 2-3 subcategories
3. Check at the front end the category views of those subcategories

**Screenshots**

![Screenshot 2020-11-04 at 8 42 52 PM](https://user-images.githubusercontent.com/388961/98155205-88b3f480-1ede-11eb-83e0-0475b4050583.png)
![Screenshot 2020-11-04 at 8 43 05 PM](https://user-images.githubusercontent.com/388961/98155215-8b164e80-1ede-11eb-8674-ea4aee11bd2d.png)
![Screenshot 2020-11-04 at 8 42 21 PM](https://user-images.githubusercontent.com/388961/98155229-8fdb0280-1ede-11eb-95b1-b12cf35375e2.png)

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version:  7.0.33

**Comment by florine2623** [comment] 2020-11-05 08:08
Hi @georgelouk ,
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

If you need support do not hesitate to contact the [support-team](https://addons.prestashop.com/en/388-support).

Thank you

**Closed as completed by florine2623** 2020-11-05 08:08 UTC
Labels: No change required
