### ISSUE TITLE
var/cache/prod/appParameters.php recreated with 000 permissions

### ISSUE THREAD

**Issue by jpyrat** [PrestaShop/PrestaShop#10998] opened 2018-10-13 10:31 UTC
**Describe the bug**
var/cache/prod/appParameters.php or var/cache/dev/appParameters.php are always generated with chmod 000 permissions (instead of 644 or 666)

**To Reproduce**
1. Go to 'Paramètres avancés'/'Performances'
2. Click on 'Mode Debug' and save
3. See error

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0 on Debian 9

**Comment by jpyrat** [comment] 2018-10-13 11:48
The reason of this behavior is explained here : https://symfony.com/doc/3.4/setup/file_permissions.html

**Comment by jpyrat** [comment] 2018-10-13 13:06
If I add this line to config/bootstrap.php : 
`$filesystem->chmod($cachedParameters, 0660);`
Here : 
```
    if (!$lastParametersCacheModificationTime || $lastParametersCacheModificationTime < $lastParametersModificationTime) {
        // When parameters file is available, update its cache if it is stale.
        if (file_exists($phpParametersFilepath)) {
            $config = require($phpParametersFilepath);
            $exportPhpConfigFile($config, $cachedParameters);
        } elseif (file_exists($yamlParametersFilepath)) {
            $config = Yaml::parse($yamlParametersFilepath);
            $exportPhpConfigFile($config, $cachedParameters);
        }
		$filesystem->chmod($cachedParameters, 0660);
    }

```

It's ok for me (except I have to refresh the page until it's not blanck)

**Comment by khouloudbelguith** [comment] 2018-10-15 09:38
Hi @jpyrat,

Thanks for your report.
After enabling dev mode, the var/cache/prod/appParameters.php is generated with chmod 666 permissions.
I attached a screenshot.
![image](https://user-images.githubusercontent.com/16067358/46942981-d860c280-d06e-11e8-8114-3cf8b1354725.png)
Thanks to check & feedback.

**Comment by jpyrat** [comment] 2018-10-20 16:28
Hi,

Found the source of the problem : opcache config.
With .user.ini, I've put : 
```
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.fast_shutdown = 0
```

And it works ! (at last)

**Comment by macavelli** [comment] 2018-10-22 01:02
Thanks jpyrat! Works fine in my case, too. In fact I found some other post with opcache settings, but it did not work. Yours work perfect!

**Comment by khouloudbelguith** [comment] 2018-10-22 08:09
HI @jpyrat,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-22 08:09
HI @jpyrat,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-22 08:09 UTC
Labels: CO, Performance, Fixed, 1.7.4.3

**Comment by seedsgallery** [comment] 2019-03-25 20:21
Hello jpyrat , i have same problem like you. Can you please describe exactly fix for:
Found the source of the problem : opcache config.
With .user.ini, I've put :

opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.fast_shutdown = 0

And it works ! (at last)

Kind Regards
Igor

**Comment by fmipsylone** [comment] 2019-11-27 14:21
After @khouloudbelguith recommendation on #13913, this seems to work for me too.

I'm under PHP 7.2, just notice that `opcache.fast_shutdown` has been deleted start from [PHP 7.2](https://www.php.net/manual/fr/opcache.configuration.php#ini.opcache.fast-shutdown), so the remaining settings I use are:
```
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
```
Best Regards

**Comment by jocel1** [comment] 2020-02-17 12:33
@PierreRambaud why not calling opcache_reset() to avoid forcing the revalidate_freq = 0 / validate_timestamp ?

**Comment by Nerque** [comment] 2020-02-22 09:44
I have the same doubt as @PierreRambaud.
Forcing the revalidation frequency to 0, in my opinion, is not an acceptable solution.

**Comment by PierreRambaud** [comment] 2020-02-24 08:47
Because we use `opcache.validate_timestamps=1` in the docker file, which is a bad idea for production mode and symfony. Also, calling `opcache_reset` can be an idea, but when? where? we mustn't add an ugly `if opcache then clear` anywhere :/
Feel free to improve the configuration and create a pull request if you find a better solution :)

**Comment by Nerque** [comment] 2020-02-28 19:23
First, Prestashop says that using opcache is a good performance improvement, but then it uses values for parameters that limit the technology's possibilities, until it seems that it is almost not being used.
When, and where, are clear, when the Prestashop cache is cleared, and when a module is removed
There may be other scenarios, but this is better than nothing.
I would try to make the changes myself, but I don't have the necessary knowledge about Prestashop programming yet. That doesn't mean that my development skills on other platforms don't allow me to see that analyzing the situation and applying a solution, even a partial one, is not very difficult for someone who knows the platform.

**Comment by arthurguiot** [comment] 2021-01-06 14:55
> Hello jpyrat , i have same problem like you. Can you please describe exactly fix for:
> Found the source of the problem : opcache config.
> With .user.ini, I've put :
> 
> opcache.revalidate_freq = 0
> opcache.validate_timestamps = 1
> opcache.revalidate_freq = 0
> opcache.fast_shutdown = 0
> 
> And it works ! (at last)
> 
> Kind Regards
> Igor

Solved on my side - 2021. It means Prestashop team haven't looked at this problem yet...

**Comment by arafatx** [comment] 2021-11-17 01:20
> > Hello jpyrat , i have same problem like you. Can you please describe exactly fix for:
> > Found the source of the problem : opcache config.
> > With .user.ini, I've put :
> > opcache.revalidate_freq = 0
> > opcache.validate_timestamps = 1
> > opcache.revalidate_freq = 0
> > opcache.fast_shutdown = 0
> > And it works ! (at last)
> > Kind Regards
> > Igor
> 
> Solved on my side - 2021. It means Prestashop team haven't looked at this problem yet...

I'm wondering why people use double statement **opcache.revalidate_freq = 0**. That seems duplicated.

**Comment by ProteanCode** [comment] 2022-02-26 00:32
The problem is still present in 1.7.8.3

**Comment by Vasilx** [comment] 2022-11-24 21:07
Why is this issue closed?

**Comment by galantematteo** [comment] 2023-10-16 20:51
Still present in 1.7.8.8.

**Comment by dangelion** [comment] 2024-07-14 07:32
Prestashop 8.1.3, July 2024: so what's the solution?
