### ISSUE TITLE
When product is removed, it disappears from "my orders" in customer account

### ISSUE THREAD

**Issue by josiasdx** [PrestaShop/PrestaShop#21712] opened 2020-11-02 15:55 UTC
When product is removed from the backoffice, it dissapears from "my orders"->"order detail" in customer account

You can reproduce deleting the product from backoffice, but also following this steps:

1) Log in as customer and place an order
2) Go to "my account"->"my orders"->"order detail". You will see product have purchased is appearing
3) In prestashop database, go to order_details table and found the ordered product. Change the "id_product" to "1" (or another product_id don't exist)
4) When you go to "my account"->"my orders"->"order detail" this product will not appear.

This was not happening in Prestashop 1.6

Prestashop 1.7.6.2

**Comment by SimonGrn** [comment] 2020-11-02 17:13
Hello @josiasdx 
please follow the template when creating an issue. This is mandatory.

Are you saying that when you remove the reference to a product in an order directly in the database (which is something very dangerous and not recommended) it...doesn't work anymore ?
What were you expecting exactly ?

It seems perfectly normal to me.

**Comment by matks** [comment] 2020-11-02 17:16
Hi @josiasdx,

When you do this
```
In prestashop database, go to order_details table and found the ordered product. Change the "id_product" to "1" (or another product_id don't exist)
```

You are inserting an inconsistency in your database. The OrderDetail record enters an inconsistent state as it references a product that does not exist.

I think at this moment the software has 2 possible ways that are acceptable to behave
1. display an error message to customer - to indicate there is an issue and have it fixed as soon as possible
2. dont show the corrupted data as it's impossible to know if this is done on purpose or a mistake

Looks like PS 1.7 uses the solution 2. Good! 😄 

So I see no issue here. I dont know what PS 1.6 did but PS 1.7 behavior seems quite acceptable : "if the data is not correct or corrupted, dont show it"

If you have suggestions to improve this behavior, you can write them 😉

**Comment by kpodemski** [comment] 2020-11-02 18:02
Hello everyone,

In order history we should see, a product details from `order_details` table, even if product is deleted we should be able to see its name and details as this table has all needed informations like `product_name` etc. This is why PrestaShop is using a lot of product details in this table.

I can reproduce this issue on 1.7.6.8, but on 1.7.7 there's everything all right, I can delete product from back-office and it's still visible in back-office and front-office

**Comment by kpodemski** [comment] 2020-11-02 18:22
This behavior has been fixed here:
https://github.com/PrestaShop/PrestaShop/commit/36c3e90771d69a717d6c0b74cbdd5115ed99362e#diff-4fa7845b8deb947f25f193448c0f02a6d15a2bcf3652ecb5c80fa0db8be90580

**Comment by matks** [comment] 2020-11-02 20:40
@kpodemski Aaaaah OK I get it now 😄 I did not understand it this way.

However this still looks like a bad idea to me 🤔 

> In prestashop database, go to order_details table and found the ordered product. Change the "id_product" to "1" (or another product_id don't exist)

If a sysadmin has put a foreign key between order_details and product for optimization this will crash

**Comment by kpodemski** [comment] 2020-11-02 20:47
This `id_product` from `order_details` is not really used for anything serious from what I know, it's ok for `order_detail` to have wrong `id_product` because in entire system you'll see `product_name` and other "hardocded" data from the day you purchased this product :)

So, main reason is historical data, this is why having foreign key here would be bad idea

**Comment by josiasdx** [comment] 2020-11-02 21:01
> This behavior has been fixed here:
> [36c3e90#diff-4fa7845b8deb947f25f193448c0f02a6d15a2bcf3652ecb5c80fa0db8be90580](https://github.com/PrestaShop/PrestaShop/commit/36c3e90771d69a717d6c0b74cbdd5115ed99362e#diff-4fa7845b8deb947f25f193448c0f02a6d15a2bcf3652ecb5c80fa0db8be90580)

Thank you!

**Comment by hibatallahAouadni** [comment] 2020-11-03 07:38
Hi @josiasdx 

It seems your problem has been fixed.
So, I close this ticket.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-03 07:38 UTC
Labels: BO, FO, Order, Fixed, 1.7.6.x

**Comment by josiasdx** [comment] 2020-11-03 07:44
Thank you
