### ISSUE TITLE
Problems with making an Order in my homepage when it is a new costumer

### ISSUE THREAD

**Issue by Avalon1617** [PrestaShop/PrestaShop#12621] opened 2019-02-19 09:48 UTC
Hi there, 

i tried to make an order with a new account in my Shop. I use the Version prestashop 1.7.5. 
If i create an account and then i put something in the shopping cart.
Then i go to check out .
When i try to put an adress in the adress fields, it beginns to load and throws me out of the order page, back to the shopping cart overview and then there stands "No Products in the shopping cart" ... 
But there were Products in the shopping cart.
I hope you understand my issue.

So a costumer cant make any orders.

Can anybody help me please ? 

Kind regards

Alex

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-02-19 10:26
Hi @Avalon1617,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1U7ackG-iKWeGHLGTY2l-wWjfm3OC9UBb/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-21 07:52
Hi @Avalon1617,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-21 07:52 UTC
Labels: Bug, FO, Shopping carts, No change required, 1.7.5.0
