### ISSUE TITLE
Call to a member function formatPrice() on null

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#30240] opened 2022-11-08 10:36 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In a custom module, under backoffice when a try to call something which use convertAndFormatPrice(), drops that error.
Searched and found the same problem under: https://github.com/PrestaShop/PrestaShop/pull/16071

So I've looked at Product.php under classes, and when i change under convertAndFormatPrice() from:

return $context->getCurrentLocale()->formatPrice(Tools::convertPrice($price, $currency), $currency->iso_code);

to

return Tools::getContextLocale(Context::getContext())->formatPrice(Tools::convertPrice($price, $currency), $currency->iso_code);

___
So what I only made, looked for #16071 fix, and used here too. So I guess it was simply not implemented in this function too.

### Steps to reproduce

In a custom module a new type of controller class (FrameworkBundleAdminController), when we try to call product::convertAndFormatPrice(), drops that error.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

**Comment by sallemiines** [comment] 2022-11-08 14:31
Hello @SNor42 ,

Unfortunately your steps  are not clear enough to reproduce the issue ! Could you please provide us the module to test it ,   clear and concise steps to reproduce the issue .

Thank you !

**Comment by sallemiines** [comment] 2022-11-28 08:52
Hello @SNor42 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by sallemiines** 2022-11-28 08:52 UTC
Labels: Bug, BO, Can't reproduce, Modules, Invalid, 1.7.8.7
