### ISSUE TITLE
Followup module cron.php wrong link

### ISSUE THREAD

**Issue by Czaro112112** [PrestaShop/PrestaShop#21888] opened 2020-11-12 12:27 UTC
#### Describe the bug

When you're at Followup module configuration tab there's invalid link on Information heading.
Entering link or starting CRON on server returns 404 error.
Files that needs to be executed are located in /modules/ps_reminder instead of /modules/followup.

#### Expected behavior

Link activation should run cron.php file to send emails.

#### Steps to Reproduce

1. Go to 'Modules > Modules Manager'
2. Click on 'Followup > Configure'
3. Scroll down to 'Info header'
4. See error in link (aqua background default)

**Screenshots**

![image](https://user-images.githubusercontent.com/71033845/98939816-4ac05d00-24ea-11eb-9a42-b366b76d9a18.png)

#### Additional information

* Followup Module version: 2.0.0
* PrestaShop version: 1.7.6.2
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment] 2020-11-12 13:05
Hello @Czaro112112 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9799. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-12 13:05
Duplicate of #9799

**Closed as completed by hibatallahAouadni** 2020-11-12 13:05 UTC
Labels: Duplicate
