### ISSUE TITLE
Weird behavior on BO Parameters > Search > Edit Alias

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#24374] opened 2021-05-06 13:35 UTC
As seen with @MatShir , issue created from a return of this PR https://github.com/PrestaShop/PrestaShop/pull/24352 

#### Describe the bug

**In BO > Shop Parameters > Search, the "Edit alias" functionality has a weird behavior and can give 3 different results depending on what's modified in the form.**

- **Case 1 :** 

I edit only the "Result" field : In this case, it's indeed only an update of the alias, no new alias is created.
In the DB, the alias is updated too.

Edit page : 
![pr 24352 result mod 1](https://user-images.githubusercontent.com/55688534/117246118-4c853080-ae3c-11eb-84c8-e265d797ae97.png)

Result : 
![pr 24352 result mod 2](https://user-images.githubusercontent.com/55688534/117246121-4f802100-ae3c-11eb-9694-75f545a469fa.png)

- **Case 2 :** 

I edit both "Alias" and "Result" field : In this case, a new alias is created in addition to the original one. 
In DB, a new alias is indeed created and the original one is not modified.

Edit page : 
![pr 24352 alias result mod 1](https://user-images.githubusercontent.com/55688534/117246644-49d70b00-ae3d-11eb-9113-229ea557709c.png)

Result : 
![pr 24352 alias result mod 2](https://user-images.githubusercontent.com/55688534/117246666-522f4600-ae3d-11eb-8dd4-50dd1747ae43.png)

- **Case 3 :** 

I edit only the "Alias" field : In this case, a new alias is created in addition to the original one, but if I edit the same alias again, both aliases are displayed in the "Alias" field.

Edit page : 
![pr 24352 alias mod 1](https://user-images.githubusercontent.com/55688534/117246892-aafede80-ae3d-11eb-9416-31a5deab2310.png)

Result : 
![pr 24352 alias mod 2](https://user-images.githubusercontent.com/55688534/117246907-afc39280-ae3d-11eb-8d87-0ada533b0b4f.png)

Both aliases in one edit page :
![pr 24352 alias mod 3](https://user-images.githubusercontent.com/55688534/117246942-bbaf5480-ae3d-11eb-9e92-833d9b0e9485.png)

#### Expected behavior

I don't know what should be the exact behavior, but the actual behavior quite unclear. Maybe there is a reason why it's so complicated, but it can be improved.

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Search
2. Add some alias
3. Edit the alias in the 3 different ways

**Screenshots**

I made a screenrecord of these 3 cases : 

https://drive.google.com/file/d/1GYGQw6sCNiFH7ZThWw6xRklJxi7yc1Eu/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7, 1.7.8...
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-05-06 13:45
Hello @Robin-Fischer-PS 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #21884. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: Sorry :stuck_out_tongue: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-06 13:45
Duplicate of #21884

**Closed as completed by hibatallahAouadni** 2021-05-06 13:45 UTC
Labels: Bug, BO, Duplicate, Search, 1.7.6.x, 1.7.7.x, 1.7.8.x
