### ISSUE TITLE
Filter not work properly on module admin controller override (legacy)

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#29326] opened 2022-08-14 23:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Filter not work properly on module admin controller override (legacy).

### Expected behavior

When overloading the admin controller of a module, the filters must work correctly, and have the same behavior as on the original controller.

### Steps to reproduce

1 - Override an module with a legacy admin controller using a native listing system.

`/override/modules/mymodule/controllers/admin/AdminMyModule.php`

```php

<?php
class AdminMyModuleControllerOverride extends AdminMyModuleController{}
```

2 - Go to BO  and try to filter and see the following errors  :

- the current filter is not selected
- if you use the pagination the current filter is lost

### PrestaShop version(s) where the bug happened

N/A

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

**Comment by hibatallahAouadni** [comment] 2022-08-15 10:23
Hello @PululuK 

Could you please provide a test module to help me reproducing the issue.
Please provide PS version and PHP version :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-09-05 08:48
Hello @PululuK 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by PululuK** [comment] 2022-09-05 09:33
Hi @hibatallahAouadni 

See the section **Steps to reproduce** please :)

**Comment by kpodemski** [comment] 2022-11-11 11:26
@hibatallahAouadni you only need to create this file that @PululuK mentioned if I understand correctly :)

**Comment by AureRita** [comment] 2022-11-15 13:51
Hi @PululuK, 

I tried to reproduce your issue with your details and I've got this : 

[Untitled_ Nov 15, 2022 2_48 PM.webm](https://user-images.githubusercontent.com/100699445/201936011-74905117-22e3-4071-81aa-05a005517c2e.webm)

Is this your issue ? because this seems to be a writting issue 

waiting for your feedback

**Comment by kpodemski** [comment] 2022-11-15 13:53
@PululuK I think it'll be easier if you could provide a tiny example module :)

**Comment by sallemiines** [comment] 2022-12-07 08:45
Hello @PululuK 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by sallemiines** 2022-12-07 08:45 UTC
Labels: Bug, 1.7.x, BO, Modules, PR available, Invalid
