### ISSUE TITLE
Problem with url rewrite PS 1.7.6.3 Reset URL

### ISSUE THREAD

**Issue by Gipielle** [PrestaShop/PrestaShop#18727] opened 2020-04-20 17:42 UTC
Hello,

this problem is still present from old version of prestashop

url rewrite Reset url button generate urls without removing characters not allowed
here an example, i got the title from google translate:

Carrinho de ferramentas com 3 módulos empilháveis ​​- Beta C43

![index2](https://user-images.githubusercontent.com/53569015/79782091-ca17f480-833e-11ea-91c6-a5fe82dadb0c.jpg)
![index](https://user-images.githubusercontent.com/53569015/79782100-cdab7b80-833e-11ea-9dce-2cfc748819f0.jpg)
<img width="1870" alt="Schermata 2020-04-20 alle 19 31 57" src="https://user-images.githubusercontent.com/53569015/79782113-d439f300-833e-11ea-8a4c-d83def4ebfa8.png">

the ascii caracters should be one of this... Ã¢Â€Â‹Ã¢Â€Â‹

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by sarahdib** [comment] 2020-04-21 12:51
Hello @Gipielle 

You need to disable URL with accent in order to change this behavior  in shop parameter -> traffic & SEO.

If you enable accent in the url when a product is add with accent the rewriting url will have accent. If you disable this option the product will not have accent.

With accent in URL disable : 
<img width="779" alt="Capture d’écran 2020-04-21 à 14 20 16" src="https://user-images.githubusercontent.com/3034677/79867918-67c30080-83df-11ea-8839-7a1a1aeb28ed.png">

Since this is not a bug I close this issue.

**Closed as completed** 2020-04-21 12:51 UTC
Labels: No change required

**Comment by Gipielle** [comment] 2020-04-21 20:41
Hello, the problem are not accents ... as you can see:
https://www.betafer.it/fr/chariot-porte-outils-beta/43000003-chariot-%C3%A0-outils-avec-3-modules-empilables-beta-c43.html

url work perfect i removed this strange part of this... Ã¢Â€Â‹Ã¢Â€Â‹ in the product name that is hidden, so when a name with strange caracters was passed in the url with the reset url button 
that caracters ar not removed correctly and it gives the error (URL not valid)

**Comment by sarahdib** [comment] 2020-04-22 07:49
I copy paste "Carrinho de ferramentas com 3 módulos empilháveis ​​- Beta C43" as you can see in the screenshot there was no problem.

**Comment by Gipielle** [comment] 2020-04-22 09:07
yes because, the forum removes bad caracters .....

**Comment by Gipielle** [comment] 2020-04-23 19:20
also if in title there is a ( ” ) it is reported in url with the reset url button

Try this as title:
Gépi dugókulcs 3/4” mama standard foszfátozott - Beta 728AS - Betafer

you got the error.

**Comment by Gipielle** [comment] 2020-05-01 16:42
Hi @sarahdib have you check ?

**Comment by Gipielle** [comment] 2023-01-31 14:26
The problem is still present in Prestashop 1.7.8.8
