### ISSUE TITLE
Prestashop 1.7.8.11 - product - tab Prices

### ISSUE THREAD

**Issue by Frits1969** [PrestaShop/PrestaShop#35194] opened 2024-01-27 21:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have a problem in Prestashop 1.7.8.11
I am in the Back Office editing or creating a product. To be precise, in the rates tab.
There is the field "Sales price per piece (excl. VAT)".
For the unit name, I enter it in Dutch and then in English. But when I look in Dutch again, it is English. If I correct this again, the English version is in Dutch.
As a result, the name in the store is in Dutch or English, but for both languages.

The attached images are screenshots (my Back Office is Dutch, sorry about this)
![Schermafbeelding 2024-01-18 170829](https://github.com/PrestaShop/PrestaShop/assets/28409740/562b62ce-d252-4ba2-a35e-d5a3c443be4c)
![Schermafbeelding 2024-01-18 170633](https://github.com/PrestaShop/PrestaShop/assets/28409740/bb9764e5-eac5-4ca1-837e-25729470a653)

How do I fix this? Or can someone help to fix it?

Kind regards,
Frits van Leeuwen

### Steps to reproduce

1 Back Office  of Prestashop 1.7.8.11
2 in the menu on the left under sales, click on Catalog
3 click on Products
4 enter a product
5 go to the Rates tab
6 Under the heading "Sale price per piece (excl. VAT)", select the right field.
7 fill in something there
8 change language
9 fill in the translation for that language
If you switch languages again, you will see that this contains the last entered information.

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

Geschenkenlaantje

**Comment by paulnoelcholot** [comment] 2024-01-29 12:58
Hello @Frits1969,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #35125.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment] 2024-01-29 12:59
Duplicate of #35125

**Closed as completed by paulnoelcholot** 2024-01-29 12:58 UTC
Labels: Bug, Duplicate

**Comment by Frits1969** [comment] 2024-01-29 13:05
I'm so sorry, I did not find that one. Thanks for telling me.
