### ISSUE TITLE
New themes Twig Symfony

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#25540] opened 2021-08-06 22:33 UTC
new template compatible with the latest standards 
Many templates are based on an outdated default template. The default template should be rewritten. in accordance with the latest standards. 
HTML 5.1
CSS3 Grid / Flexbox
Twig
This would add a new dimension to prestashop. Because the current template is outdated.

**Comment by eveneme** [comment] 2021-08-06 22:34
https://twig.symfony.com

**Comment by eveneme** [comment] 2021-08-06 22:38
Many templates are based on an outdated default template. The default template should be rewritten. in accordance with the latest standards.

**Comment by matks** [comment] 2021-08-07 06:29
Hi @eveneme thanks for your suggestion but unfortunately it's not that simple.

You can find the details in https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-2-pain-points

> Here’s another example. Early 2016, during the development of the Classic theme (the default theme for PrestaShop 1.7), the team chose to use Bootstrap 4, even though it was still in alpha stages at the time. To my best understanding, they were hoping that the final version would be released in time for 1.7.0.
>
> As Murphy’s Law dictates, this turned out to work out wrong. Not only Bootstrap 4 didn’t ship in time for 1.7.0 (which forced the Classic theme to be released based on Boostrap 4 alpha 5), but the Bootstrap team also decided to introduce major layout changes in alpha 6, after PrestaShop 1.7.0 was released. This effectively blocked the team from upgrading Bootstrap on the Classic theme, because that would break all their child themes (and there are lots of them)… so Classic is now stuck with an obsolete dependency that cannot be upgraded.

To make it short, we could not do this as any important change would break hundred of children themes being used.

Your suggestion is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/14533 so I close it 😉 as it's easier to keep one issue

**Closed as completed by matks** 2021-08-07 06:29 UTC
Labels: Duplicate

**Comment by hibatallahAouadni** [comment] 2021-08-07 18:22
Duplicate of #14533
