### ISSUE TITLE
Cart discount applied to reduced items (although disabled) if there are other items in the cart

### ISSUE THREAD

**Issue by zzzZZZzzz9** [PrestaShop/PrestaShop#22007] opened 2020-11-19 10:33 UTC
#### Describe the bug

Cart discount for category X is applied to reduced items - although this is disabled - as soon as other items are in the cart.
1) Only reduced item from category X in the cart -> discount is not applied with error message that it is not valid.
2) Reduced item from X and normal item from X in the cart -> discount is applied to both items
3) Reduced item from X and normal item from other category in the cart -> discount is applied to reduced item

#### Expected behavior

In case 2), discount should only apply to normal item from X.
In case 3), no discount should be applied.

#### Steps to Reproduce

1. Create 20% discount code with condition: "item from category X", applicable to selected items, reduced items excluded
2. Put reduced item from category X in the cart, along with any other item from X or other category.
3. Apply discount code.

**Screenshots**

As expected:
![image](https://user-images.githubusercontent.com/49036578/99654661-eefe5280-2a5a-11eb-838b-9c75a03b461b.png)

Not intended:
![image](https://user-images.githubusercontent.com/49036578/99654603-dbeb8280-2a5a-11eb-9963-5ef7d56af800.png)

#### Additional information

PS 1.7.6.7 | Classic Theme | PHP 7.2 | MySQL 5.7

**Comment by hibatallahAouadni** [comment] 2020-11-19 11:08
Hello @zzzZZZzzz9 

I didn't manage to reproduce your issue with PS1.7.6.7, see the attached screen record below:

https://drive.google.com/file/d/14gK8UgEEXQRRYcNKJ1rEQAFP5L_lD1GL/view

Please check and feedback.

Thanks!

**Comment by zzzZZZzzz9** [comment] 2020-11-19 11:12
Hi @hibatallahAouadni 

Thanks for checking. Pease apply a discount to the mug and exclude discounted items from the voucher. Then check with 1) only mug in the cart (voucher rightfully denied for discounted item, see my first screenshot) and 2) with mug and additional item in the cart (voucher wrongfully applied to discounted item, see my screenshot 2).

**Comment by hibatallahAouadni** [comment] 2020-11-19 16:34
Hello @zzzZZZzzz9 

Thanks for the clarification, I manage to reproduce the issue with PS1.7.6.7 and PS1.7.7.0-rc.1+build.4 but it seems been fixed on develop, see the attached screen record below:

https://drive.google.com/file/d/1QCFNZniyGGqpIzTgsSA7AZrQijHPAPtX/view

Please check and feedback.

Thanks!

**Comment by zzzZZZzzz9** [comment] 2020-11-20 08:28
That looks about right in the final stage.

In your second step (reduced mug plus poster) the discount should not be applicable either (and not come out as 0), right?

**Comment by hibatallahAouadni** [comment] 2020-11-20 10:30
@zzzZZZzzz9 yes I believe so!

Let's ask the product team, ping @PrestaShop/product-team this issue has been fixed on develop as you can see in my screen record, but the problem is not fully resolved like @zzzZZZzzz9 mentioned above.

Could you please check, should I open a new issue about this behavior?

Thanks!

**Comment by marionf** [comment] 2020-11-20 16:13
@hibatallahAouadni Yes, please create a new issue to explain exactly what is not working and close this one if it's partially fixed.

**Comment by hibatallahAouadni** [comment] 2020-11-23 13:42
Hello @zzzZZZzzz9 

Your issue is solved, so I'm closing this issue.
@marionf I open a new issue for the other bug #22057

Thanks @zzzZZZzzz9 for reporting this bug to us!

**Closed as completed by hibatallahAouadni** 2020-11-23 13:42 UTC
Labels: Bug, FO, Duplicate, Discounts, 1.7.6.7

**Comment by khouloudbelguith** [comment] 2020-11-23 13:45
Duplicate of #19090
