### ISSUE TITLE
1-click upgrade goes faulty

### ISSUE THREAD

**Issue by ALTSAT** [PrestaShop/PrestaShop#10141] opened 2018-08-25 09:26 UTC
I have Prestashop V1.6.1.20
I did an update of the 1-Click Upgrade to v4.1.0
I want to config but have following bug log:

Notice op lijn 510 in bestand /data/sites/web/altsatbe/www/classes/Tab.php
[8] Undefined index: id_parent

Notice op lijn 568 in bestand /data/sites/web/altsatbe/www/classes/controller/AdminController.php
[8] Undefined index: name

Notice op lijn 569 in bestand /data/sites/web/altsatbe/www/classes/controller/AdminController.php
[8] Undefined index: name

Notice op lijn 570 in bestand /data/sites/web/altsatbe/www/classes/controller/AdminController.php
[8] Undefined index: class_name

Notice op lijn 572 in bestand /data/sites/web/altsatbe/www/classes/controller/AdminController.php
[8] Undefined index: class_name

Notice op lijn 618 in bestand /data/sites/web/altsatbe/www/classes/controller/AdminController.php
[8] Undefined index: name

**Comment by novanova77** [comment] 2018-08-27 08:56
I have had the same sort of problem and now I can't access the Prestashop backend. I asked them for help and they just sent me here. Isn't it their module that is faulty?
Here's what I said to them:
  Hello,
About 2 hours ago there was one module to update on my Presta website backend. It was the "1 Click Upgrade".
Unfortunately there must have been something wrong with the module as during the update it came up with a white error screen (something like error 117 or the like) and the backend got stuck.
Now I cannot login to the website backend/administration. It says:
This page isn’t working
crystals.co.nz is currently unable to handle this request.
HTTP ERROR 500"

The actual front website still works. It is the backend I can't log into.
There was something wrong with that module as I have upgraded it in the past (along with many others) without problem.
I have no current website backup. Can you help me with accessing the website backend please.
I am stuck.
The login address: https://crystals.co.nz/presta/admin1231
The frontend is www.crystals.co.nz/presta

Kind regards,
Tony Novis
Crystals Ltd.

**Comment by khouloudbelguith** [comment] 2018-08-27 09:41
Hi @ALTSAT, @novanova77,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Best regards, Khouloud

**Comment by ALTSAT** [comment] 2018-08-27 11:31
Hi @Khouloud

The log.txt is blanc.
But I get also a HTTP 500-Fault when I click to config the module.

I can send you a login, if you want.

Kind regards, Luc

**Comment by khouloudbelguith** [comment] 2018-08-27 14:10
Hi @ALTSAT ,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by ALTSAT** [comment] 2018-08-27 15:23
Hi @khouloud

PHP ERROR LOG

[Mon Aug 27 16:18:03.527221 2018] [error] [pid 3986] apache2_util.c(271): [client 176.9.4.106:60282] [client 176.9.4.106] ModSecurity: Access denied with code 403 (phase 2). Pattern match "(?i:(?:c(?:o(?:n(?:t(?:entsmartz|actbot/)|cealed defense|veracrawler)|mpatible(?: ;(?: msie|\\\\.)|-)|py(?:rightcheck|guard)|re-project/1.0)|h(?:ina(?: local browse 2\\\\.|claw)|e(?:rrypicker|esebot))|rescent internet toolpak)|w(?:e(?:b(?: (?:downloader|by ..." at REQUEST_HEADERS:User-Agent. [file "/usr/local/httpd/conf/modsecurity-crs/activated-rules/modsecurity_crs_35_bad_robots.conf"] [line "27"] [id "990012"] [rev "2"] [msg "Rogue web site crawler"] [data "BLEXBot"] [severity "WARNING"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/AUTOMATION/MALICIOUS"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "altsat.be"] [uri "/robots.txt"] [unique_id "W4QIG7OIhnnEiHs4CYAusgAAAK4"]
[Mon Aug 27 16:42:30.005278 2018] [error] [pid 21569] mod_proxy_fcgi.c(848): [client 91.181.58.245:52303] AH01071: Got error 'PHP message: PHP Fatal error:  Call to undefined method ConfigurationTest::test_curl() in /data/sites/web/altsatbe/www/modules/autoupgrade/classes/UpgradeSelfCheck.php on line 111\n'
[Mon Aug 27 16:42:49.785181 2018] [error] [pid 23391] mod_proxy_fcgi.c(848): [client 91.181.58.245:52306] AH01071: Got error 'PHP message: PHP Strict Standards:  Declaration of Advancedeucompliance::disable() should be compatible with ModuleCore::disable($force_all = false) in /data/sites/web/altsatbe/www/modules/advancedeucompliance/advancedeucompliance.php on line 0\n'
[Mon Aug 27 16:42:55.203020 2018] [error] [pid 23391] mod_proxy_fcgi.c(848): [client 91.181.58.245:52306] AH01071: Got error 'PHP message: PHP Fatal error:  Call to undefined method ConfigurationTest::test_curl() in /data/sites/web/altsatbe/www/modules/autoupgrade/classes/UpgradeSelfCheck.php on line 111\n'
[Mon Aug 27 16:43:01.211249 2018] [error] [pid 21569] mod_proxy_fcgi.c(848): [client 91.181.58.245:52311] AH01071: Got error 'PHP message: PHP Strict Standards:  Declaration of Advancedeucompliance::disable() should be compatible with ModuleCore::disable($force_all = false) in /data/sites/web/altsatbe/www/modules/advancedeucompliance/advancedeucompliance.php on line 0\n'
[Mon Aug 27 16:43:06.607101 2018] [error] [pid 21569] mod_proxy_fcgi.c(848): [client 91.181.58.245:52317] AH01071: Got error 'PHP message: PHP Strict Standards:  Declaration of Advancedeucompliance::disable() should be compatible with ModuleCore::disable($force_all = false) in /data/sites/web/altsatbe/www/modules/advancedeucompliance/advancedeucompliance.php on line 0\n'
[Mon Aug 27 16:43:14.873959 2018] [error] [pid 23391] mod_proxy_fcgi.c(848): [client 91.181.58.245:52316] AH01071: Got error 'PHP message: PHP Strict Standards:  Declaration of Advancedeucompliance::disable() should be compatible with ModuleCore::disable($force_all = false) in /data/sites/web/altsatbe/www/modules/advancedeucompliance/advancedeucompliance.php on line 0\n'


DEBUG

Fatal error: Call to undefined method ConfigurationTest::test_curl() in /data/sites/web/altsatbe/www/modules/autoupgrade/classes/UpgradeSelfCheck.php on line 111

Unknown error op lijn 0 in bestand /data/sites/web/altsatbe/www/modules/advancedeucompliance/advancedeucompliance.php
[2048] Declaration of Advancedeucompliance::disable() should be compatible with ModuleCore::disable($force_all = false)

**Comment by khouloudbelguith** [comment] 2018-08-27 15:33
Hi @ALTSAT 

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9553
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-08-27 15:34
Duplicate of #9553

**Closed as completed by khouloudbelguith** 2018-08-27 15:33 UTC
Labels: Bug, Duplicate, Autoupgrade

**Comment by ALTSAT** [comment] 2018-09-06 15:40
Yesterday I did the new update to version v4.1.1 but the same problem remains.

**Comment by khouloudbelguith** [comment] 2018-09-06 15:42
Hi @ALTSAT,

It is not fixed yet.
It is added to our bug roadmap.

Thanks & best regards, Khouloud
