### ISSUE TITLE
Vat calculation on credit slip is wrong if the order has a discount (freeshipping)

### ISSUE THREAD

**Issue by Prestaplugins** [PrestaShop/PrestaShop#24244] opened 2021-04-28 09:24 UTC
#### Describe the bug

If you have an order with a voucher applied giving freeshipping, and you make a partial refund for a product, then the credit slip PDF has wrong number for the VAT.

#### Expected behavior

Have the good calculation for the VAT.

#### Steps to Reproduce

1. Create a voucher without any code, giving freeshipping.
2. Make a purchase with 2 products and check that the freeshipping voucher is correctly applied
3. In admin, create a partial refund on that order, refund a product with the amount you want, check that you want a credit slip, not a discount.
4. Check the PDF invoice. At the bottom right, the VAT for product is OK... but in the VAT table the product VAT is wrong.

**Screenshots**

![image](https://user-images.githubusercontent.com/3033446/116380337-2a742880-a814-11eb-8929-9088e481d978.png)

#### Additional information

* PrestaShop version: at least from 1.7.5.1 to 1.7.7.3
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-04-28 10:22
Hello @Prestaplugins 

Thanks for your issue!
Could you please check this issue #18319 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Prestaplugins** [comment] 2021-04-28 12:02
It's related to refund and voucher problems, so it's probably the same kind of issue and maybe the same code which is responsible, but mine is due to vouchers offering free shipping.
I can't tell you if it exactly the same...

**Comment by hibatallahAouadni** [comment] 2021-04-29 00:22
Hello @Prestaplugins 

Thanks for your feedback!
It's the same cause it doesn't matter if the voucher is a **free shipping** or just a **discount**, the bug always persists 😖 


So as we are aware of this issue and it is already in our debug backlog. This issue is a duplicate of #18319. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Closed as completed** 2021-04-29 00:22 UTC
Labels: Bug, CO, Duplicate, Credit notes, Discounts, 1.7.5.1, 1.7.7.3

**Comment by hibatallahAouadni** [comment] 2021-04-29 00:23
Duplicate of #18319
