### ISSUE TITLE
Order message display/saving problem in BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14638] opened 2019-07-14 13:57 UTC
**Describe the bug**
Order message is badly displayed in order admin - with encoded characters. Example: `Testovac&iacute; pozn&aacute;mka`

**Cause**
In 1.7.6, message is saved to database like `Testovac&iacute; pozn&aacute;mka`.
In 1.6.1, it's saved without encoding `Testovací poznámka`.

I think it's the only field, that's saved like that. Will you fix the saving or the display? :-)

**Possible solution**
Change {$message['message']|escape:'html':'UTF-8'|nl2br} to {$message['message']} in order/helpers/view.tpl.

**Additional information**
PrestaShop version: 1.7.6

**Comment by mariem-abid** [comment] 2019-07-15 09:32
Hi @Hlavtox,

I manage to reproduce the issue with PS:1.7.6.0
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by marionf** [comment] 2019-07-15 15:01
Hello @Hlavtox 
Your issue seems to be a duplicate of #9726
Could you please take a look at this issue ?

**Comment by Hlavtox** [comment] 2019-07-16 10:34
@marionf Yes, it's the same issue. Do you think it can be fixed after year and a half? :-)

**Comment by khouloudbelguith** [comment] 2019-07-16 10:37
Hi @Hlavtox,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9726
So, I close it.

PS:
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-16 10:37
Duplicate of #9726

**Closed as completed by khouloudbelguith** 2019-07-16 10:37 UTC
Labels: Bug, Minor, BO, Duplicate, Order messages, 1.7.6.0
