### ISSUE TITLE
Problem with cart rules to selected products and exclude products with discount on Paypal

### ISSUE THREAD

**Issue by websgalicia** [PrestaShop/PrestaShop#15876] opened 2019-10-09 08:48 UTC
**Describe the bug - _Sorry for me English_**

When I create a discount rule for products of a category and mark the option "Excluding discounted products", the cart does well, but when paying with Paypal, the discount is generated for all products and does not exclude products with discount.

**To Reproduce**

1. Create a cart rule and restric to some categories
2. Asign a discount and check "Exclude discounted products"
3. Add products to the selected categories to cart. 1 product with discount and one without discount.
4. Checkout with PayPal

**Screenshots**
![1](https://user-images.githubusercontent.com/6552216/66465995-39548800-ea82-11e9-9428-8ffc1c16afb6.JPG)
![2](https://user-images.githubusercontent.com/6552216/66465996-39548800-ea82-11e9-9341-2af9d2059839.JPG)
![3](https://user-images.githubusercontent.com/6552216/66465997-39548800-ea82-11e9-9569-122cccc4aa40.JPG)
![4](https://user-images.githubusercontent.com/6552216/66465998-39ed1e80-ea82-11e9-8462-4e5bdc4068d4.JPG)

**Additional information**
PrestaShop version: 1.7.5.2

**Comment by khouloudbelguith** [comment] 2019-10-09 09:10
Hi @websgalicia,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13704 to fix the issue.
It is fixed in the next version PS1.7.7.0.
Your ticket is a duplicate of #10300
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-09 09:10
Duplicate of #10300

**Closed as completed by khouloudbelguith** 2019-10-09 09:10 UTC
Labels: Duplicate
