### ISSUE TITLE
Simplified Chinese bug

### ISSUE THREAD

**Issue by anglesgirl** [PrestaShop/PrestaShop#15108] opened 2019-08-14 08:34 UTC
**Describe the bug**
Dashboard Home Page ，calendar.js Error loading，Limit only Simplified Chinese，

I am not good at English. I can record a video demo if you need it.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.3.7

**Comment by mariem-abid** [comment] 2019-08-14 08:48
Hi @anglesgirl,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrading your version PHP, check & feedback.

**Comment by matks** [comment] 2019-08-14 09:08
@mariem-abid this is not related to PHP, this is a JS error 😉 

@anglesgirl can you please record a video ? I have tried to download the China language pack, I configured my back-office to Simplified Chinese and I have browsed the Dashboard, I see no issue.

> I am not good at English. I can record a video demo if you need it.

Looks fine to me 😄 congratulations on writing an issue in English !

**Comment by anglesgirl** [comment] 2019-08-14 09:15
> @mariem-abid this is not related to PHP, this is a JS error 😉
> 
> @anglesgirl can you please record a video ? I have tried to download the China language pack, I configured my back-office to Simplified Chinese and I have browsed the Dashboard, I see no issue.
> 
> > I am not good at English. I can record a video demo if you need it.
> 
> Looks fine to me 😄 congratulations on writing an issue in English !



The problem only appears in simplified Chinese,！
traditional Chinese and French is OK.

**Comment by anglesgirl** [comment] 2019-08-14 09:18
> @mariem-abid this is not related to PHP, this is a JS error 😉
> 
> @anglesgirl can you please record a video ? I have tried to download the China language pack, I configured my back-office to Simplified Chinese and I have browsed the Dashboard, I see no issue.
> 
> > I am not good at English. I can record a video demo if you need it.
> 
> Looks fine to me 😄 congratulations on writing an issue in English !

1.7.5.2 is OK

**Comment by anglesgirl** [comment] 2019-08-14 09:22
> Hi @anglesgirl,
> 
> PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 are compatible with PHP 7.2.
> For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
> Next Major release PS1.7.7 will be compatible with PHP7.3.
> Thanks to downgrading your version PHP, check & feedback.

php 7.2.21
PrestaShop 1.7.6.0
Simplified Chinese 
The problem remains

PrestaShop 1.7.5.2 All languages is ok

**Comment by mariem-abid** [comment] 2019-08-14 09:44
@anglesgirl, I did not manage to reproduce the issue with the last version PS 1.7.6.0.
I attached a video record.
https://drive.google.com/file/d/1oMn9axNbIm28FH03izMMjayD_gAFDKnv/view
Could you please record a video?

**Comment by anglesgirl** [comment] 2019-08-14 09:49
> @anglesgirl, I did not manage to reproduce the issue with the last version PS 1.7.6.0.
> I attached a video record.
> https://drive.google.com/file/d/1oMn9axNbIm28FH03izMMjayD_gAFDKnv/view
> Could you please record a video?

Traditional Chinese is ok
Simplified Chinese is bad

**Comment by anglesgirl** [comment] 2019-08-14 09:52
> @anglesgirl, I did not manage to reproduce the issue with the last version PS 1.7.6.0.
> I attached a video record.
> https://drive.google.com/file/d/1oMn9axNbIm28FH03izMMjayD_gAFDKnv/view
> Could you please record a video?

I can give you my webmaster account

**Comment by mariem-abid** [comment] 2019-08-14 09:57
@anglesgirl, with the Simplified Chinese, is OK.
I attached a video record.
https://drive.google.com/file/d/1A9eJGBzRmeCOjm1aGH1xq6r1ZGgi5Agx/view

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by anglesgirl** [comment] 2019-08-14 10:00
> @anglesgirl，简体中文，没问题。
> 我附上了一段视频记录。
> https://drive.google.com/file/d/1A9eJGBzRmeCOjm1aGH1xq6r1ZGgi5Agx/view
> 
> 能否请您提供更多信息？我们需要更多详细信息，以了解我们如何重现您的问题：
> 
> * 主办
> * 调试模式报告
> * PHP错误日志
> * apache错误日志
> * JavaScript控制台日志
> * 截图
> 
> 你不知道如何获得这些信息吗？请阅读以下文章：[http](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/)：
> [//build.prestashop.com/howtos/misc/how-to-create-bug-report/](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/)
> 
> 谢谢！

Thank you for your patience and help. I'm going to reinstall the program.

**Comment by mariem-abid** [comment] 2019-08-14 10:06
@anglesgirl, waiting for your feedback.

**Comment by anglesgirl** [comment] 2019-08-14 11:36
> @anglesgirl，等待你的反馈。

1. Remove Simplified Chinese 
2, add Simplified Chinese 
3, all OK！

How to Get 100% Simplified Chinese Translation

**Comment by mariem-abid** [comment] 2019-08-14 12:54
@anglesgirl, navigate to BO=> International=> Localization=> Languages => Delete the Traditional Chinese.
Thanks for chack and feedback.

**Comment by anglesgirl** [comment] 2019-08-14 13:35
> @anglesgirl，导航到BO =>国际=>本地化=>语言=>删除繁体中文。
> 感谢chack和反馈。
Did you notice that Sunday, Monday, is mo su?

**Comment by mariem-abid** [comment] 2019-08-14 14:33
@anglesgirl, I manage to reproduce that Sunday and Monday, are mo su with the last version PS 1.7.6.0 and the Language is Simplified  Chinese.
I attached a screenshot.
![cal](https://user-images.githubusercontent.com/36841537/63029630-cd520b00-bea8-11e9-9ab6-e4754a941cb1.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2019-08-14 15:46
@mariem-abid Do you have the same issue with PS 1.7.5.2 ?

**Comment by mariem-abid** [comment] 2019-08-14 15:49
@marionf, yes, the same issue.

**Comment by NeOMakinG** [comment] 2020-08-25 13:47
It looks like I can't reproduce it on develop :

![image](https://user-images.githubusercontent.com/14963751/91182284-443ff780-e6ea-11ea-9c4f-3ac83a3182fe.png)

wdyt @marionf  ?

**Comment by marionf** [comment] 2020-08-25 14:11
Same, I can't reproduce on 1.7.7.x

![capture d'écran_2778](https://user-images.githubusercontent.com/13449658/91184997-8fa7d500-e6ed-11ea-94c3-217e77566709.png)

I close the issue as we can't reproduce it

**Closed as completed by marionf** 2020-08-25 14:11 UTC
Labels: Bug, Trivial, BO, Can't reproduce, Dashboard, Front-end, 1.7.5.2, 1.7.6.0
