### ISSUE TITLE
Faceted search at manufacurer page or search

### ISSUE THREAD

**Issue by Oliwer-Budnik** [PrestaShop/PrestaShop#36600] opened 2024-07-24 06:35 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hey, 

I have found a checkbox at newer version of this module, that helps to add filters to another page like manufacturers ( brands ), or search etc. All pages like Category, New Products etc works, but search and brands not.

Is it possible, that I have to add code to page view, to add left column or something?

I have tried at prestashop 1.7.6.6 and 1.7.8.10. Not work at all.

### Expected behavior

Filters should be avaible at Brands page.
![image](https://github.com/user-attachments/assets/8aad1250-60ab-40a7-af82-4443db6bdcc4)

### Steps to reproduce

1. Change module options at configuration
![image](https://github.com/user-attachments/assets/2d8b9202-a73c-44f1-b73b-054674be3569)

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.16

**Comment by florine2623** [comment] 2024-07-24 08:29
Hello @Oliwer-Budnik ,

You need to change the layout of your Brands page.

https://github.com/user-attachments/assets/1bb97b15-725a-4bbe-8a09-1b119bdc333c

I'm closing your issue as it is not a bug ^^

**Closed as completed by florine2623** 2024-07-24 08:29 UTC
Labels: Bug
