### ISSUE TITLE
Catalog Product: Switching between "SEO" tab and "basic settings" display visual issues

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/PrestaShop#12261] opened 2019-01-22 15:40 UTC
**Describe the bug**
On his BO when a user click on basic settings description, SEO tab and return back to settings description tab, he can see something ugly (informations completely messed up)

**To Reproduce**
1. Go to 'Catalog>Products' and click on 'description' subtab
2. Click on 'SEO' tab
3. Click on 'Basic settings' tab

**Screenshots**
![image](https://user-images.githubusercontent.com/29543279/51546368-50a40480-1e64-11e9-96bf-22122150c01e.png)

**Additionnal information**
PrestaShop version: Develop branch
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-01-22 15:49
Duplicate of #9668

**Closed as completed by khouloudbelguith** 2019-01-22 15:49 UTC
Labels: Duplicate
