### ISSUE TITLE
Smarty cache - force compilation

### ISSUE THREAD

**Issue by pswaab** [PrestaShop/PrestaShop#11318] opened 2018-11-08 11:57 UTC
Hello,

I'm trying to set up a multi store with 3 shops. One of the problem, before many others, is the cache for modules used in different themes.

For example, shop1 use theme1 with module ps_searchbar and shop2 use theme2 with the same module ps_searchbar. After clearing the cache, shop1 searchbar module shows good but after accessing shop2, the shop1 footer uses the tpl of the theme2 until I clear the cache again, and so on.

I tried all cache setting, on and off, with multistore optimisation and without.
But the only thing that helps is force compilation of smarty

Could anyone help me with this problem, or tell me where to find in the code, to solve the issue.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2018-11-08 12:00
Hi @pswaab,

Your ticket is a duplicate of #9905
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-11-08 12:01
Duplicate of #9905

**Closed as completed by khouloudbelguith** 2018-11-08 12:01 UTC
Labels: Duplicate

**Comment by pswaab** [comment] 2018-11-08 12:04
I am sorry!
But can you point me in the direction where I should search fixing this issue?
Looks like it is sharing smarty cached templates and does not look from which theme.
Thanks

**Comment by khouloudbelguith** [comment] 2018-11-08 12:10
@pswaab, you should debug the issue to find the exact problem.
Thanks!
