### ISSUE TITLE
Customer Reassurance Not Displaying Correctly in Footer Position

### ISSUE THREAD

**Issue by antonchik777** [PrestaShop/PrestaShop#27519] opened 2022-01-28 16:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

Module Icons(Customer Reassurance v5.0.0) Not Displaying Correctly in Footer Position On All Pages - Above footer(Classic Theme)
<img width="1280" alt="Снимок экрана 2022-01-28 в 19 36 57" src="https://user-images.githubusercontent.com/35896021/151587889-d11d596c-8537-4144-a7b0-826e84ce510f.png">

Sorry if I'm duplicating an existing topic or if you can't reproduce it on your own.

Thank you!

Regars
Anton

### Steps to reproduce

1. Set module display to position in settings to Footer Position On All Pages - Above footer
2. Scroll down the site and see the incorrect display of module icons

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Customer Reassurance v5.0.0

**Comment by khouloudbelguith** [comment] 2022-01-28 17:06
Hi @antonchik777,

I did not manage to reproduce the issue with PS1783
![image](https://user-images.githubusercontent.com/16067358/151590352-ef8a78f1-6516-4c4f-8cd2-dbb824f90d03.png)
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/26887 to fix the issue.
Your ticket is a duplicate of #26846
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2022-01-28 17:06
Duplicate of #26846

**Closed as completed by khouloudbelguith** 2022-01-28 17:06 UTC
Labels: Bug, Duplicate, Invalid
