### ISSUE TITLE
error while sending message Ps 1.7.4.2

### ISSUE THREAD

**Issue by Medaliskr24** [PrestaShop/PrestaShop#10196] opened 2018-08-29 13:14 UTC
Hello 
In my PrestaShop in Advanced Parameters E-mail e send tests messages with success.

But in my contact page email form when I send a email I receive a message

**an error occurred while sending the message, please try again.**

i'm using ps 1.7.4.2.
contactform V4.1.1

**Comment by khouloudbelguith** [comment] 2018-08-29 13:19
Hi @Medaliskr24,

Thanks for your report.
The issue is added to our debug roadmap.
Your ticket is a duplicate of #9566
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-08-29 13:19
Duplicate of #9566

**Closed as completed by khouloudbelguith** 2018-08-29 13:19 UTC
Labels: Duplicate

**Comment by Medaliskr24** [comment] 2018-08-29 13:29
Thanks A lot !!
