### ISSUE TITLE
Module manager page bugs

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18948] opened 2020-05-02 22:23 UTC
#### Error when clicking "Enable/Disable" too fast

- Have like 4 or more disabled modules. 
- Click Enable on all of them. (Do not wait for the previous action to finish.)
- See red error message on the right, that the action could not be finished.

#### Display error after module uninstall

- Have enough modules in "Other" category, that the "show more" link is shown in the bottom.
- Uninstall a module
- Module disappears
- Click on "show more"
- Module appears again with a checkbox and no action available
- Refresh the page, module is hidden for good

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by marionf** [comment] 2021-12-10 10:49
This issue seems to be in part a duplicate of https://github.com/PrestaShop/PrestaShop/issues/26144

About the first one: Error when clicking "Enable/Disable"
I can't reproduce it on develop branch: https://drive.google.com/file/d/1ywMe6pmu4f1RVLKEXS14iBlaP7OtUqZ7/view?usp=sharing

About the second one: Display error after module uninstall
I can't reproduce it on develop branch: https://drive.google.com/file/d/1Q81cvGfDcOuBiQj78TgAP-xVlydM8a25/view?usp=sharing

@hibatallahAouadni Could you confirm if it's well fixed please ?

**Comment by hibatallahAouadni** [comment] 2021-12-14 08:44
Hello @marionf 

**Error when clicking "Enable/Disable" too fast**
I reproduce the issue with develop and I encountered another issue with the modal when I tried to disable a module:

https://www.awesomescreenshot.com/video/6430908?key=fe8f0b7c059bfc102a5ec5adac76f4c3

**Display error after module uninstall**
I didn't reproduce the issue with develop, it seems to be fixed:

https://www.awesomescreenshot.com/video/6430966?key=f6314493b511be627213fa2d74243a87

Thanks!

**Comment by Hlavtox** [comment] 2022-04-08 10:26
@hibatallahAouadni Can you retest this? Maybe it's fixed on current develop, as the page has been greatly improved!

**Comment by HanaRebaiQA** [comment] 2022-04-15 13:20
Hello @Hlavtox 

I was able to reproduce your first issue on a new develop

**Error when clicking "Enable/Disable" too fast : NOK** 

https://user-images.githubusercontent.com/92912932/163574823-15a73ed6-7a78-492d-96c7-eea995125f05.mp4


For the second one, i was not able to reproduce it

**Display error after module uninstall : OK**

https://user-images.githubusercontent.com/92912932/163574201-6e162974-f000-4b53-b0fd-87761ff174bb.mp4

I'll add this to the debug backlog so that it's fixed. 
We are waiting for your PR.

Thank you!

**Closed as completed** 2024-04-11 05:43 UTC
Labels: Bug, Minor, BO, Module manager, 1.7.6.0, Verified
