### ISSUE TITLE
Faceted Search template edition not working with more than 25.000 categories

### ISSUE THREAD

**Issue by CallejaMotos** [PrestaShop/PrestaShop#17227] opened 2020-01-17 14:01 UTC
**Describe the bug**
Unable to save all categories in faceted search filters.
Number of categories: more than 25.000 (auto parts website)

**To Reproduce**
1. Go to Modules / Module Manager
2. Click on faceted search **Configure** button (v3.4.1)
3. Click on **Edit** (from template)
4. Check All
5. Save => (not work, doesn't save none category)

Note 1: if I do it manually (checking the check boxes) it works. 
Note 2: even with a js script from console that check every check box category, doesn't work.

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-01-17 15:02
Hi @CallejaMotos,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16652
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-17 15:03
Duplicate of #16652

**Closed as completed by khouloudbelguith** 2020-01-17 15:02 UTC
Labels: Duplicate, Categories, Faceted search

**Comment by felipeseo** [comment] 2024-05-28 09:48
I ran into the same problem, and with this [module ](https://www.sunnytoo.com/product/easy-filter-module-for-prestashop1-7/?wpam_id=17)I managed to solve it.
