### ISSUE TITLE
Core.js Uncaught TypeError

### ISSUE THREAD

**Issue by DanielNemanic** [PrestaShop/PrestaShop#31176] opened 2023-02-03 06:59 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Complete new Installation from the release with all modules: https://github.com/PrestaShop/PrestaShop/releases/download/8.0.1/prestashop_8.0.1.zip

I have my own theme. 
The theme.js and custom.js is empty at the moment, to reproduce the error.
There are no js errors in 1.7.8.

![Prestashop 8 0 1 BE Information](https://user-images.githubusercontent.com/10723243/216532528-a5acc535-90d6-4dac-8855-d01783154fc1.png)
![Prestashop 8 0 1](https://user-images.githubusercontent.com/10723243/216532532-2105a5fd-83dc-4c57-aea0-a556f938777d.png)

### Steps to reproduce

1. Clean install
2. Activated own theme
3. Open FrontEnd and DevTools

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

**Comment by sallemiines** [comment] 2023-02-03 10:38
Hello @DanielNemanic 

The theme.js shouldn't be empty! Indeed you will encounter an issue when you empty it. Closing the issue as it's not a bug but it's malpractice.

Thank you !

**Closed as completed by sallemiines** 2023-02-03 10:38 UTC
Labels: Bug, Invalid

**Comment by DanielNemanic** [comment] 2023-02-03 10:41
The theme.js has no content. Just:
/**/

The theme is loaded normal through the backend.
