### ISSUE TITLE
BO - Multistore -URL-BO doesn't exist anymore after creating new shop with invalid URL

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26014] opened 2021-09-28 07:44 UTC
#### Describe the bug

BO doesn't exist anymore after creating new shop with invalid URL

#### Expected behavior

Red alert when entering an invalid URL.

#### Steps to Reproduce

1. Go to shop parameters > General> Enable multistore> yes.
2. Click on advanced > parameters> Multistore>Add new shop
3. Set an  invalid URL for this shop for exemple (set the Virtual URL to éé((èè/ )
4. save => BO doesn't exist anymore after creating new shop with invalid URL as shown in the attached screen shot

![image](https://user-images.githubusercontent.com/89604350/135047682-204572a5-d2ad-420c-aa64-4366a1e2f432.png)

* PrestaShop version: develop, 1.7.8.0 , 1.7.6.3
* PHP version: 7.3

**Comment by Prestaworks** [comment] 2022-02-25 09:51
I can't reproduce this on
1.7.8.3 Tested with PHP 7.4.9 and 7.3.19
following virtual url was used
éé
and
éé/´/
seems to work fine in both BO and FO.
is it a regression for develop?

**Comment by khouloudbelguith** [comment] 2022-02-25 10:27
Hi @Prestaworks,

I manage to reproduce the issue with PS1783 in my case also
![image](https://user-images.githubusercontent.com/16067358/155699163-f0d0966c-ddfc-4ee3-834d-70f25fa90e62.png)

at this step: Set an invalid virtual URL for this shop for example (set the Virtual URL to `éé((èè/ )` and I save
All the shop is NOK

Thanks!

**Comment by Prestaworks** [comment] 2022-02-25 10:29
That's odd, It works well for me in my local enviroment. 
Have you any other settings that could cause issues? does the frontend work?

**Comment by khouloudbelguith** [comment] 2022-02-25 10:55
@Prestaworks, my information

![image](https://user-images.githubusercontent.com/16067358/155702912-5f1c1e80-22ee-48ff-b602-d40891c9030e.png)
I attached a screen record

https://user-images.githubusercontent.com/16067358/155703297-3d84ae9f-bb03-4e7b-b5f1-355646201d23.mp4

Thanks!

**Comment by Prestaworks** [comment] 2022-02-25 11:06
Got it, it's not the éé that breaks it, it was the (( ) and - and due to these being written into the htaccess file. Thanks @khouloudbelguith now I can recreate the issue.

**Comment by Prestaworks** [comment] 2022-02-25 12:40
It will work if the chars are properly escaped in the htaccess file. `\( instead of (`
Solution here is either to block invalid chars from being saved or to escape them properly in the htaccess file.
I am not sure what solution is prefered, I see pros and cons on both.

**Comment by florine2623** [comment] 2024-12-23 16:08
Fixed in PS 9.0.0

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/924de7ee-de70-4734-9392-5be51cb8d5d4" />

Closing to issue to avoid clogging the backlog

**Closed as completed by florine2623** 2024-12-23 16:08 UTC
Labels: Bug, Major, BO, Multistore, Fixed, 1.7.6.3, Verified
