### ISSUE TITLE
ps_linklist: Incorrect category display if the shop contains categories with identical names

### ISSUE THREAD

**Issue by aeyoll** [PrestaShop/PrestaShop#35895] opened 2024-04-11 09:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If categories and cms categories got the same names, they are only displayed once in the ps_linkkist configuration.

### Expected behavior

Categories and cms categories should be all displayed, even if they have the same names.

### Steps to reproduce

- In a shop, create the follow category structure

```
- T-shirt
  - Men
  - Women
- Shoes
  - Men
  - Women
```

Bug: In ps_linklist configuration, "Men" and "Women" are only present once.

### PrestaShop version(s) where the bug happened

8.1.5

### If your bug is related to a module, specify its name and its version

ps_linklist v6.0.7

**Comment by florine2623** [comment] 2024-04-12 07:28
Hello @aeyoll ,

I can't reproduce your issue using ps_linklist v6.0.7.

Here's my category structure :
<img width="172" alt="Screenshot 2024-04-12 at 09 24 57" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a723c62b-23f9-46b4-bf8e-9ea69ef6e475">

Here's the categories displayed on link list module. I have 3 because I have the 2 you suggest creating and the on that is automatically created when you create a shop.
<img width="391" alt="Screenshot 2024-04-12 at 09 25 17" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7ff97dbf-970b-45b4-8752-d8e4b3ac2e1b">

On the FO all the links to the categories are well displayed.
<img width="141" alt="Screenshot 2024-04-12 at 09 28 31" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/af544639-0ad6-4640-b929-b00ece0b8e04">

Closing your issue as it cannot be reproduced.

**Closed as completed by florine2623** 2024-04-12 07:28 UTC
Labels: Bug

**Comment by SharakPL** [comment] 2024-08-08 21:56
@aeyoll I also didn't find anything wrong here. All categories are displayed properly on module's configuration page shows everything. The only problem here is that categories lack proper structure. It's definitely needed

![obraz](https://github.com/user-attachments/assets/9f0c7e12-2ca8-444c-88d1-c43f3d8d0938)

You also didn't explain what CMS categories have to  do with it
> If **categories and cms categories got the same names**, they are only displayed once in the ps_linkkist configuration.

I tried the same names there and it's all good. You actually can't add whole **categories** to the list of links. Only the **pages** in those categories.
