### ISSUE TITLE
Delivery template - Wrong date

### ISSUE THREAD

**Issue by thalassa-web** [PrestaShop/PrestaShop#27867] opened 2022-03-09 16:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the delivery PDF template the date displayed in the header is the invoice date and not the delivery date.
Exemple : 
My customer create an order the third of march (2022-03-03) the paiement is OK so there is an order invoice created at the same date.
The order is prepared by the service the fourth of march (2022-03-04), so the status order is «Preparation in progress» and the order invoic is updated to set the delivery_date at 2022-03-04.
At this point, the order was created the third, the invoice date is the third and the delivery date is the fourth.

When I download the delivery slip pdf, the header date is not the delivery date but the invoice date.

### Expected behavior

The date in the delivery slip PDF has to be the date of the delivery slip and not of the invoice slip …
The template should use the delivery_date on the OrderInvoic object instead of the creation date.

### Steps to reproduce

1 - Create an order with teh status «Accepted paiment»
2 - Wait until the next day
3 - Change the order status to generate a delivery slip
4 - Download the delivery slip.
5 - The date (in the top right) is the invoice date not the delivery slip date …

### PrestaShop version(s) where the bug happened

1.7.6.8 - 1.7.8.2

### PHP version(s) where the bug happened

7.1 - 7.3

**Comment by hibatallahAouadni** [comment] 2022-03-10 14:11
Hello @thalassa-web 

I reproduce the issue with PS1778 and PS 1784, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/157678658-df1af957-9bb0-4566-86b5-7c01cf4e6403.png)

The order has been paid on `31-01-2022`, but it was delivered on `10-03-2022`:

![image](https://user-images.githubusercontent.com/23308427/157678793-d4a3d7ff-3c5d-4fda-a923-9e0b1ceef22f.png)

Yet, we find the invoice date on the delivery slip. I’ll add this to the debug backlog so that it’s fixed.
Thanks for your PR :rocket: 

Thank you

**Comment by hibatallahAouadni** [comment] 2022-03-10 14:14
@thalassa-web I think it's related/duplicate of #12929
Could you please check it :pray:

**Comment by thalassa-web** [comment] 2022-03-10 14:25
@hibatallahAouadni I'm not sure ! The issue is not very clear …
If I read the title, it is not. In my issue I talk about the date in the generated PDF.
In the #12929, it seems it is about the date in the B.O.
Furthermore, the screenshot files are no longer available.
Please ask to @SylvainPayet who opened the #12929

**Comment by thalassa-web** [comment] 2022-03-14 07:48
I proposed a fix for this issue. (https://github.com/PrestaShop/PrestaShop/pull/27868)
It was approved by 2 reviewers !
Why is the fix not allowed to be merged ?

**Comment by matks** [comment] 2022-03-14 08:16
@thalassa-web The code has been approved but it does not mean it is valid. The PR has been labelled "Waiting for QA". QA team will now explore it and verify whether it not only fixes the issue but also it does not introduce unwanted bugs 😉 this is for quality. I'm sure you want PrestaShop software to be done with quality right ? 😄 It can only happen if each PR is slowly explored and analyzed to make sure it works as expected in all situations

**Closed as completed** 2022-03-16 09:15 UTC
Labels: Bug, Minor, CO, Delivery slip, Fixed, PR available, 1.7.6.8, Verified

**Comment by thalassa-web** [comment] 2022-03-16 09:53
@Progi1984 , @matks 
Guys, if I want to fix this bug in the next 1.7 version, is it possible to merge the fix or have I to make another PR ?

**Comment by matks** [comment] 2022-03-16 10:00
@thalassa-web Unfortunately, in order to preserve 1.7.8.x branch from unwanted side-effects, we only merge **regression** bug fixes inside 1.7.8.x

That means that bugs fixed inside 1.7.8.x are bugs that were introduced in 1.7.8.0, 1.7.8.1, 1.7.8.2, 1.7.8.3 or 1.7.8.4

If this bug #27867 was introduced in 1.7.6.8 it is not a 1.7.8;x regression so we will not merge it into 1.7.8.x . This is because each code change can bring another bug, so we try to keep the scope of bugfixes very narrow. 

That being said people who experience this bug can always apply your changes on their shop :)
