### ISSUE TITLE
Form rest errors styling differs and child form errors are not shown at all

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#14844] opened 2019-07-24 12:09 UTC
**Describe the bug**
We add form_rest() in each form on migrated pages to open the forms for module extensions, but those fields rendered by form_rest are displaying different style error messages. Also when form type has child, those errors aren't displayed at all. Worth mentioning that defining form_errors() has no impact, because errors are already rendered in form_rest. In addition, if the field which is being rendered by form_rest has child types (like TranslatableType) these errors won't show up at all. Modifying general form_rest rendering layout should help.

**To Reproduce**
1. Go to any migrated page with form for example Improve > Design > Pages > Add new page
2. Now in code (CmsPageType.php) you have to add any test field form, that has constraints. But do not render it in view (to imitate how module would extend it).
3. Go back to BO Add new Page form and submit it with invalid data to see the errors. You can compare how the error is rendered when its defined in template and how when taken care by form_rest (screenshot)

**Screenshots**
![Screenshot from 2019-07-24 14-06-55](https://user-images.githubusercontent.com/31609858/61791957-2c7dac00-ae24-11e9-8323-7aaad5dc0532.png)

**Additional information**
PrestaShop version: 1.7.6, develop
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-07-24 12:15
FYI @matks

**Comment by zuk3975** [comment] 2019-07-24 12:29
Also I find this the right place to mention the issue with options forms. It is currently "hidden" because most options forms doesn't have any constraints. 
So the issue is that if we add constraint to options form, it is ignored because errors are lost after redirect of processOptions -> index.
One suggestion to solve that is to forward controller instead of redirecting. (example in this commit 4fc128d1978fc595fbe41dbeec4f98eef54a53cb)

**Comment by eternoendless** [comment] 2019-08-06 11:08
IMO the form theme should be fixed so that all forms are rendered using `form_widget()`

**Comment by eternoendless** [comment] 2020-01-16 10:13
Closing this as duplicate of #16482

**Closed as completed by eternoendless** 2020-01-16 10:13 UTC
Labels: Bug, develop, Duplicate, migration, 1.7.6.0
