### ISSUE TITLE
The association PrestaShopBundle\Entity\Tab#tabLangs refers to the owning side field PrestaShopBundle\Entity\TabLang#tab which does not exist.

### ISSUE THREAD

**Issue by gbartosz83** [PrestaShop/PrestaShop#20855] opened 2020-09-04 09:39 UTC
#### Describe the bug

Backoffice works only in dev mode true - otherwise there is an error 500

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

I have turned on SSL on backend, and added www. to the domain name

**Screenshots**

PrestaShopBundle\Entity\Tab | The association PrestaShopBundle\Entity\Tab#tabLangs refers to the owning side field PrestaShopBundle\Entity\TabLang#tab which does not exist.
PrestaShopBundle\Entity\TabLang | The mappings PrestaShopBundle\Entity\TabLang#id and PrestaShopBundle\Entity\Tab#tabLangs are inconsistent with each other.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-09-04 10:01
Hi @gbartosz83 ,

There are multiple things you can do to see where the error comes from :
- check error log in /var/log
- delete cache manually from FTP in /var/cache/dev & /var/cache/prod and from BO
- disable all overrides
- disable external modules
Or contact the support team here : https://addons.prestashop.com/en/388-support

As i can't reproduce the issue on my test shop PS 1.7.6.7, I'll close the issue.
Thanks!

**Closed as completed by florine2623** 2020-09-04 10:01 UTC
Labels: No change required

**Comment by gbartosz83** [comment] 2020-09-04 10:10
why did you close the issue?
I have cleared cache few times it did not help.
I have disabled all overrides and all external modules - it did not change anything
