### ISSUE TITLE
javascript error prevents upload of images

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#31980] opened 2023-03-30 14:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When editing a image slide in ps_imageslides module, a JS error occurs
Uncaught Sortable: `el` must be an HTMLElement, not [object Undefined]
This prevents the select a file button to be used.

### Expected behavior

It should be possible to edit images in the slide.

### Steps to reproduce

1. install ps_imageslides module
2. go to configure for the module
3. edit one of the existing images
4. click on upload image button.
5. nothing happens.

### PrestaShop version(s) where the bug happened

1.7.4.4

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_imageslides v3.1.2

### Your company or customer's name goes here (if applicable).

Prestaworks AB

**Comment by florine2623** [comment] 2023-03-30 14:44
Hello @Prestaworks ,

I tried to reproduce your issue on 1.7.8.8 with Image slider v3.1.2. I can't 😓 

https://user-images.githubusercontent.com/16019289/228873501-1750ef0c-ab18-488f-a0db-cfc4592f1a61.mov

Is the issue only happening in PS 1.7.4.4 ?

Waiting for your feedback !
Thanks!

**Comment by Prestaworks** [comment] 2023-03-30 14:55
I get the same JS error in 1.7.7.5 and 8.0.2, but the button works there.
You can check in the console in the browser.
The JS error is not present in version 3.1.0 of the module, so it's probobly from the upgrade of the sortable script.

**Comment by florine2623** [comment] 2023-03-30 15:39
I have semi reproduced your issue with ps_imageslides v3.1.2 .

The JS error is present, but there's no impact in the BO nor the FO.

<img width="1436" alt="Screenshot 2023-03-30 at 17 33 36" src="https://user-images.githubusercontent.com/16019289/228889082-e9eca4f0-96f9-4041-afea-a400180f9f89.png">

It is a trivial bug then, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Prestaworks** [comment] 2023-03-31 06:16
I already made a PR for it
https://github.com/PrestaShop/ps_imageslider/pull/84

**Comment by Hlavtox** [comment] 2023-04-17 12:05
I have exactly the same error. Can't upload any image because the file selector when editing slide doesn't work at all due to JS error.

Prestashop 1.7.6.9 and https://github.com/PrestaShop/ps_imageslider/releases/tag/v3.1.2

**Comment by AaronTajriba** [comment] 2023-04-25 12:50
@Hlavtox the pull request from @kpodemski works for me with 1.7.6.9

**Closed as completed** 2023-05-17 08:46 UTC
Labels: Bug, Trivial, BO, Imageslider, Verified, Module

**Comment by samilmarekrygula** [comment] 2023-05-19 13:48
Still there is a problem with adding new slider. I have added this condition also Tools::getIsset('addSlide') and now it works

**Comment by ipaelo** [comment] 2024-05-07 09:20
Hi,

In the version 3.1.4 this line is missing and the module fails to load images in a new slider.

Regards

**Comment by kpodemski** [comment] 2024-05-08 11:29
@ipaelo could you be more specific? I've just tried to add a new image using Slider in version 3.1.4 and I hadn't had any issues
