### ISSUE TITLE
Private Note Orders

### ISSUE THREAD

**Issue by JavierEB** [PrestaShop/PrestaShop#18860] opened 2020-04-28 08:27 UTC
#### Describe the bug

Prestashop always, in the private note of customer orders, is not associated with the order itself ... it is associated with the customer. With which it would be a good option to associate only that private note within the orders only to them. For example: a customer has multiple orders, but only one needs xx $ and that note may be only for that order, not for the customer itself ... I don't know if you understand me ... Attached photos of the orders, to all those of the same client are associated with the same "test note"
I think that is a problem. Thank you

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to 'Ordes'
2. Click on 'Private Note'

**Screenshots**
![Screenshot_2020-04-26 Orders Order FFATNOMMJ from John DOE • Prueba1764](https://user-images.githubusercontent.com/5004396/80305774-4ab37680-87bf-11ea-9b5f-3c0487b1ec4e.png)
![Screenshot_2020-04-26 Orders Order KHWLILZLL from John DOE • Prueba1764](https://user-images.githubusercontent.com/5004396/80305775-4be4a380-87bf-11ea-8ca2-87dbf6121ebe.png)
![Screenshot_2020-04-26 Information about customer J DOE • Prueba1764](https://user-images.githubusercontent.com/5004396/80305776-4c7d3a00-87bf-11ea-8537-d8d401163f63.png)
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
This is a problem that comes from behind I think ...
Because the private note of the orders is actually saved in the table ps_costumers> Column "Note" with which it is associated with all the orders of that customer, not just one.

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by sarahdib** [comment] 2020-04-28 09:23
Hello @JavierEB 

Thank you for this feedback.

@PrestaShop/prestashop-product-team what do you think about this improvement ?

**Comment by JavierEB** [comment] 2020-04-28 09:33
> 
> 
> Hello @JavierEB
> 
> Thank you for this feedback.
> 
> @PrestaShop/prestashop-product-team what do you think about this improvement ?

hello @sarahdib  the link does not work ... Error 404

**Comment by Hlavtox** [comment] 2020-04-28 09:35
https://github.com/PrestaShop/PrestaShop/issues/14753

**Comment by marionf** [comment] 2020-04-28 09:36
Thank you @Hlavtox 
@JavierEB your issue is a duplicate of #14753, please follow and comment on this issue if needed

**Comment by marionf** [comment] 2020-04-28 09:37
Duplicate of #14753

**Closed as completed by marionf** 2020-04-28 09:37 UTC
Labels: Improvement, BO, Duplicate, Order

**Comment by MatShir** [comment] 2020-04-28 09:40
Hi @JavierEB,
There are 2 needs here:
- One where we want to have a concise description of the customer (for big client, save customer behavior)
- One where we want to have a concise description of the order management

Instead of editing the feature of customer note, I suggest to add new input for this
