### ISSUE TITLE
How can set priority on multi Catalog Prices Rules?

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#25269] opened 2021-07-06 23:10 UTC
Hi

#### Describe the bug

on a site there are 2 catalog prices rules, one is with the condition on category and one with the condition on brand.
the condition on brand seems to have a higher priority than that of the category.

is it possible to set a custom priority? because in some cases it is necessary a different priority

#### Expected behavior

in this case the shopkeeper wants to set a higher priority on the rule with category condition and set 40% instead to have 27% of the other rule

#### Steps to Reproduce

the configurations are shown in the images

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/124676473-e611a280-debe-11eb-91a6-b65a1ec5e9be.png)
![2](https://user-images.githubusercontent.com/653230/124676474-e742cf80-debe-11eb-963b-a1a696fcc3d1.png)
![3](https://user-images.githubusercontent.com/653230/124676476-e7db6600-debe-11eb-9052-4466659e8bf3.png)
![4](https://user-images.githubusercontent.com/653230/124676478-e873fc80-debe-11eb-8fb6-6dfd275b364a.png)
![6](https://user-images.githubusercontent.com/653230/124676636-31c44c00-debf-11eb-9dca-b4c16d38148d.png)

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

bye

**Comment by hibatallahAouadni** [comment] 2021-07-07 09:13
Hello @maofree 

I reproduce the issue with PS1767 and PS1775, cause there's no priority management in catalog price rules.
When you apply 2 different catalog price rules to the same products with the same minimum quantity.
Only the oldest rule will apply to the product. Other rules will have no effect on the product.

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20185. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-07 09:13
Duplicate of #20185

**Closed as completed by hibatallahAouadni** 2021-07-07 09:13 UTC
Labels: Duplicate
