### ISSUE TITLE
Error 500 while changing the status in an order

### ISSUE THREAD

**Issue by ur-ishoxs** [PrestaShop/PrestaShop#11007] opened 2018-10-15 08:27 UTC
**Describe the bug**
I get an error 500 when I change the status of an order to "order canceled" for example. This issue comes since update to 1.7.4.3.

**To Reproduce**
1. Go to 'orders' and chosse one
2. Click on 'update status'
3. Scroll down to 'order canceled'
![screen](https://user-images.githubusercontent.com/44157898/46938500-42c03580-d064-11e8-999c-42cafa17a202.jpg)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-10-15 09:02
Hi @ur-ishoxs,

I did not manage to reproduce the issue with PS 1.7.4.3 after upgrade from 1.7.4.2.
I used the last version of the 1-click upgrade module.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ur-ishoxs** [comment] 2018-10-16 14:49
Hi,

here are the informations you need:

host
it is a hosting contingent at 1&1

Server Setup and Configuration
See attached phpinfo.html

Debug mode report
See attached Screenshots

Apache error log
I don’t know how I get this

Javascript console log
I don’t know how I get this

Hope this helps

Thanks

Best Regards
Uwe


Von: khouloudbelguith [mailto:notifications@github.com]
Gesendet: Montag, 15. Oktober 2018 11:05
An: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc: Rinkens, Uwe <uwe.rinkens@ishoxs.com>; Mention <mention@noreply.github.com>
Betreff: Re: [PrestaShop/PrestaShop] Error 500 while changing the status in an order (#11007)


Hi @ur-ishoxs<https://github.com/ur-ishoxs>,

I did not manage to reproduce the issue with PS 1.7.4.3 after upgrade from 1.7.4.2.
I used the last version of the 1-click upgrade module.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

  *   host
  *   server setup and configuration
  *   debug mode report
  *   PHP error logs
  *   apache error log
  *   javascript console log
  *   screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-16 14:53
@ur-ishoxs, there is no screenshot attached, you need to connect to the GitHub & upload the screenshot.
Thanks!

**Comment by ur-ishoxs** [comment] 2018-10-16 15:16
![screen_debug-mode_backend_open-order-1](https://user-images.githubusercontent.com/44157898/47027175-3f61a280-d167-11e8-965f-af7d4dcc8cb6.jpg)
![screen_debug-mode_backend_open-order-2](https://user-images.githubusercontent.com/44157898/47027176-3ffa3900-d167-11e8-95c7-0f08c6d6ac8b.jpg)
![screen_debug-mode_backend_open-order-3](https://user-images.githubusercontent.com/44157898/47027178-3ffa3900-d167-11e8-9652-287a9bcb4b40.jpg)
![screen_debug-mode_frontend](https://user-images.githubusercontent.com/44157898/47027180-3ffa3900-d167-11e8-881c-c3a579a4cedc.jpg)

**Comment by khouloudbelguith** [comment] 2018-10-16 15:29
@ur-ishoxs, you have an error in the Override of the class `Cart.php`.
Did you create this file by a developer/ yourself?
![image](https://user-images.githubusercontent.com/16067358/47028105-f3aff880-d168-11e8-9d24-f6b821f6a488.png)
Thanks!

**Comment by ur-ishoxs** [comment] 2018-10-17 06:51
Yes, you are right. This is an override from a third party module.
I’ve deactivated this module and now the debug mode works correct.
I'll send you screenshots of the problem I have, if I want to change the status of an order.

Thanks.
Uwe

Von: khouloudbelguith [mailto:notifications@github.com]
Gesendet: Dienstag, 16. Oktober 2018 17:30
An: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc: Rinkens, Uwe <uwe.rinkens@ishoxs.com>; Mention <mention@noreply.github.com>
Betreff: Re: [PrestaShop/PrestaShop] Error 500 while changing the status in an order (#11007)


@ur-ishoxs<https://github.com/ur-ishoxs>, you have an error in the Override of the class Cart.php.
Did you create this file by a developer/ yourself?
[image]<https://user-images.githubusercontent.com/16067358/47028105-f3aff880-d168-11e8-9d24-f6b821f6a488.png>
Thanks!

**Comment by ur-ishoxs** [comment] 2018-10-17 06:51
![screen_debug-mode_backend_change-order-status-1](https://user-images.githubusercontent.com/44157898/47067496-dc651f80-d1e9-11e8-91be-8353ff146037.jpg)
![screen_debug-mode_backend_change-order-status-2](https://user-images.githubusercontent.com/44157898/47067497-dc651f80-d1e9-11e8-81c0-8ddd68833fa5.jpg)
![screen_debug-mode_backend_change-order-status-3](https://user-images.githubusercontent.com/44157898/47067498-dcfdb600-d1e9-11e8-817e-0ad05d983b7d.jpg)

**Comment by khouloudbelguith** [comment] 2018-10-17 08:08
Hi @ur-ishoxs,
Thanks for your feedback.
Could you please disable the PayPal module, clear cache, check & feedback.
Thanks!

**Comment by ur-ishoxs** [comment] 2018-10-17 08:31
Hi,

wow – this solve the problem.
I have done manual update for the Paypal module, hope it works now correctly.

Thank you very much.
Ticket can be closed.

Best regards,
Uwe

Von: khouloudbelguith [mailto:notifications@github.com]
Gesendet: Mittwoch, 17. Oktober 2018 10:09
An: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc: Rinkens, Uwe <uwe.rinkens@ishoxs.com>; Mention <mention@noreply.github.com>
Betreff: Re: [PrestaShop/PrestaShop] Error 500 while changing the status in an order (#11007)


Hi @ur-ishoxs<https://github.com/ur-ishoxs>,
Thanks for your feedback.
Could you please disable the PayPal module, clear cache, check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-17 08:44
Hi @ur-ishoxs,

You are welcome!
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-17 08:44 UTC
Labels: Bug, BO, Order, Autoupgrade, Fixed, 1.7.4.3

**Comment by gnujeremie** [comment] 2018-11-01 15:25
I have the same error when I try to cancel an order I created in the BO, and assigned paypal payment method. Prestashop/Paypal tries to load the transaction, but there is not transaction ID so it fails and crash.
Do you want me to open a new ticket ?

PS: prestashop version 1.7.4.2

**Comment by khouloudbelguith** [comment] 2018-11-01 15:48
Hi @gnujeremie,

The Paypal module isn't developed by PrestaShop, but by one of our partner.
You can contact them here: https://support.202-ecommerce.com/fr/support/home
They are only can help you to solve this problem.
Thanks!

**Comment by gnujeremie** [comment] 2018-11-01 16:28
Thanks, I thought you where in charge too, because of this partnership. I'll see with them then !

Le 1 novembre 2018 17:03:54 GMT+01:00, khouloudbelguith <notifications@github.com> a écrit :
>Hi @gnujeremie,
>
>The Paypal module isn't developed by PrestaShop, but by one of our
>partner.
>You can contact them here:
>https://support.202-ecommerce.com/fr/support/home
>They are only can help you to solve this problem.
>Thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PrestaShop/PrestaShop/issues/11007#issuecomment-435085434

-- 
Jérémie
