### ISSUE TITLE
The problem of counting the full set.

### ISSUE THREAD

**Issue by tartubasti** [PrestaShop/PrestaShop#11025] opened 2018-10-16 09:51 UTC
**Describe the bug**
I have three products, one with combinations, the second simple and the third set of products. The first has two combinations in the presence of 5 and 10 pieces. The second in the presence of 80 pieces. The third consists of the first combination of the first commodity and the second commodity. The site shows in stock 15 pieces. Must show 5 complete sets, as it consists of two goods 5 and 80 pieces.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.20

**Comment by khouloudbelguith** [comment] 2018-10-16 09:56
Hi @tartubasti,

Could you please try to navigate to the BO => Shop Parameters => Product Settings => check the `Default pack stock management` option & try to select the "Decrement both" option, check & feedback.
Thanks!

**Comment by tartubasti** [comment] 2018-10-16 10:04
Reduce the goods in the set will not work?

**Comment by khouloudbelguith** [comment] 2018-10-16 10:07
@tartubasti, No, it will work.
But you need to check if "Decrement both" option solves your issue.
THanks!

**Comment by tartubasti** [comment] 2018-10-16 10:13
If the customer buys the product included in the kit separately, not the pack itself, will have to manually change the quantity of the pack?

**Comment by khouloudbelguith** [comment] 2018-10-16 10:21
@tartubasti,

If "Decrement both" option is selected.
1- you have the Product A
2- you have a pack with this product A
3- if customer buys the product included in the kit separately, the quantity of the pack will be automatically reduced.
Thanks!

**Comment by tartubasti** [comment] 2018-10-16 10:25
Thank you so much for helping and taking your time.

**Comment by khouloudbelguith** [comment] 2018-10-16 10:29
@tartubasti, so your issue is solved?

**Comment by tartubasti** [comment] 2018-10-16 10:33
Not completely.

**Comment by khouloudbelguith** [comment] 2018-10-16 10:40
@tartubasti, could you please describe in a new comment steps to reproduce your issue, one by one.

**Comment by tartubasti** [comment] 2018-10-16 10:43
The problem is that when creating pack does not automatically count the number of complete pack.

**Comment by khouloudbelguith** [comment] 2018-10-16 10:56
@tartubasti, thanks for this clarifications.
We are aware of this issue, it added to our bug roadmap.
Your ticket is a duplicate of #9728
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-16 10:57
Duplicate of #9728

**Closed as completed by khouloudbelguith** 2018-10-16 10:57 UTC
Labels: Duplicate, Pack, 1.7.4.2
