### ISSUE TITLE
Combinations page uses Language ID 1

### ISSUE THREAD

**Issue by adamongithub** [PrestaShop/PrestaShop#12305] opened 2019-01-25 11:28 UTC
The combinations page displays attributes for langid 1, despite my default language being langid2. 

**To Reproduce**
1. Change your default language to one other than language id 1.
2. Delete language id 1 (this may be a contributing factor)
3. Goto the attributes page and add a new size attribute, or rename one.
4. Goto the combinations page for a product and note whether the change is reflected.

**Screenshots**
![selection_079](https://user-images.githubusercontent.com/16188789/51743372-5c760d80-2094-11e9-9470-5b7cdeaf8f26.png)
![selection_077](https://user-images.githubusercontent.com/16188789/51743373-5c760d80-2094-11e9-8e8d-f6948edaac9c.png)
![selection_078](https://user-images.githubusercontent.com/16188789/51743375-5c760d80-2094-11e9-91e1-3c71beab4595.png)

**Additionnal information**
PrestaShop version: 1.7.5 (issue present since installing 1.7.2)
PHP version: 5.6
Server Type: Apache 2.4

**Comment by khouloudbelguith** [comment] 2019-01-25 11:33
Hi @adamongithub,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10924 to fix the issue.
It is fixed in the next release PS1.7.6.
Your ticket is a duplicate of #9627
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-25 11:33
Duplicate of #9627

**Closed as completed by khouloudbelguith** 2019-01-25 11:33 UTC
Labels: Duplicate
