### ISSUE TITLE
[minor] Extra templates vars missing in call of validateOrder from BO

### ISSUE THREAD

**Issue by herverenault** [PrestaShop/PrestaShop#23772] opened 2021-03-25 08:11 UTC
#### Describe the bug

Parameter $extra_vars is an empty array. As a result, in the mail sent to customer, the placeholders check_name and check_address_html are left as is.

#### Expected behavior

I have no idea how to fix, at the moment, sorry.

#### Steps to Reproduce

1. Go to BO>SELL>Order>Order
2. Create an order
3. Assign **cheque payment** as a **payment method**
4. Choose **Waiting for cheque payment** as **State**
5. See error

**Screenshots**

https://github.com/PrestaShop/PrestaShop/blob/89fc1396b8a972b718146b9b253805de904a91e6/src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php#L118

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by florine2623** [comment] 2021-03-25 08:58
Hello @herverenault ,

Which version of PrestaShop is affected ?

Thanks!

**Comment by herverenault** [comment] 2021-03-25 09:00
Oops, forgot to mention I'm running 1.7.7.1

**Comment by hibatallahAouadni** [comment] 2021-03-25 09:33
Hello @herverenault 

Please next time **respect and follow the provided template to submit a complete bug report**.
I just edit your issue, so please fill the blanks and specify the error that you encountered and the expected behavior.
Please check and feedback.

Thanks!

**Comment by florine2623** [comment] 2021-04-14 13:17
Hello @herverenault ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-04-14 13:17 UTC
Labels: Bug, BO, Order, Email, No change required, 1.7.7.1
