### ISSUE TITLE
Module Visit origin doesn't work Presta 1.7.7.2

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#23769] opened 2021-03-24 22:38 UTC
#### Describe the bug

The module say doesn't configuration needed but I simulate a visit from the facebook shared link and don't count it

#### Expected behavior
Count the page referenced 

#### Steps to Reproduce

1. Install clean prestashop 1.7.7.2
2. Share a link to another web
3. Clic in the link

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-03-25 13:46
Hello @TecnoHands ,

I can't reproduce your issue on my test shop :
![Capture d’écran 2021-03-25 à 14 43 52](https://user-images.githubusercontent.com/16019289/112482839-c1167b00-8d78-11eb-9a28-a0766513de42.png)


Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Thank you

**Closed as completed by florine2623** 2021-03-25 13:46 UTC
Labels: Can't reproduce, Stats, 1.7.7.2

**Comment by TecnoHands** [comment] 2021-03-26 23:08
@florine2623 This module need active any configuration of Data mining for statistics or it's how writed in the description and only it's needed activate the module?
Very thanks
