### ISSUE TITLE
ps_categoryproducts issue when cache is enabled

### ISSUE THREAD

**Issue by zell9999** [PrestaShop/PrestaShop#14967] opened 2019-08-02 10:11 UTC
**Describe the bug**
Only first item of ps_categoryproducts show the price when cache is enabled.
1.0.4 version of the module. Re-installed many times with the same result.
Caché cleared many times and same result.
Maybe the problem is in PHP version? (I use 7.0.33)
The cache system type: File system
With cache disabled works perfect...
In prestashop Spanish forum there are many people with the same issue.
https://www.prestashop.com/forums/topic/937533-problema-m%C3%B3dulo-productos-de-la-misma-categor%C3%ADa/

**To Reproduce**
1. Install last version of ps_categoryproducts (1.0.4) on Prestashop 1.7.6
2. Enable cache (Type: File system)

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/36448511/62362989-7a7a6a00-b51e-11e9-9ebc-3630336aa87b.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/36448511/62363340-73a02700-b51f-11e9-825f-e22f54ce7944.jpg)
![imagen](https://user-images.githubusercontent.com/36448511/62363434-9f231180-b51f-11e9-8370-fd8de023c9d0.png)
![imagen](https://user-images.githubusercontent.com/36448511/62363588-f0cb9c00-b51f-11e9-92b1-d7349f14b559.png)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-08-02 10:27
Hi @zell9999,

I did not manage to reproduce the issue with PS1.7.6.0 & the ps_categoryproducts module v1.0.4
https://drive.google.com/file/d/1ktkwAIXhH1Ij4D6quR87cKLsIatuHCWQ/view
This issue is fixed with this PR: https://github.com/PrestaShop/ps_categoryproducts/pull/6
Your ticket is a duplicate of #9652
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-02 10:27
Duplicate of #9652

**Closed as completed by khouloudbelguith** 2019-08-02 10:27 UTC
Labels: Duplicate, Category products

**Comment by zell9999** [comment] 2019-08-02 11:06
> 
> 
> Hi @zell9999,
> 
> I did not manage to reproduce the issue with PS1.7.6.0 & the ps_categoryproducts module v1.0.4
> https://drive.google.com/file/d/1ktkwAIXhH1Ij4D6quR87cKLsIatuHCWQ/view
> This issue is fixed with this PR: [PrestaShop/ps_categoryproducts#6](https://github.com/PrestaShop/ps_categoryproducts/pull/6)
> Your ticket is a duplicate of #9652
> So, I close it.
> Thanks!

that you are not able to reproduce the error does not mean that this module works well...
Which PHP version do you use?
Can you attempt to reproduce the issue using a child theme?

By the way,

In ticket #9652 says replace
`$cache_id = 'ps_categoryproducts|'.$id_product.'|'.$id_category;`
By
`$cache_id = $this->getCacheId('ps_categoryproducts|'.$id_product.'|'.$id_category);`
in /modules/ps_categoryproducts/ps_categoryproducts.php but v1.0.4 of module has a different code...and besides, that solution doesn't work in 1.0.4

**Please reopen ticket...**

**Comment by khouloudbelguith** [comment] 2019-08-02 12:56
@zell9999, I tried with different shops on different servers: PHP Version 7.2.13 & PHP Version 7.0.33.
I tried also with child theme => OK
[mythem.zip](https://github.com/PrestaShop/PrestaShop/files/3461278/mythem.zip)
https://drive.google.com/file/d/1kEGqkyDf-6B2a4hAmBz3c2DPKj1UMU5I/view
Thanks!

**Comment by HartLarsson** [comment] 2020-08-30 14:47
PS 1.7.6.7
php 7.2
module 1.0.4

Works only on Classic Theme, for example with a very popular Warehouse i have the same problem both in Product of same Category then Viewed products.

![image](https://user-images.githubusercontent.com/16102074/91662419-91550c80-eae2-11ea-84e5-8ccd93b2bcc1.png)

There is a fix (brutal) to fixing the product in the same category: https://www.prestashop.com/forums/topic/937533-solucionado-problema-m%C3%B3dulo-productos-de-la-misma-categor%C3%ADa/?tab=comments#comment-3149639

**Comment by sonosergio** [comment] 2021-11-18 15:32
The problem is inside template
remove every {block ...} {/block} (only smarty code) from /themes/warehouse/templates/catalog/_partials/miniatures/_partials/product-miniature-thumb.tpl and works

**Comment by HartLarsson** [comment] 2023-07-13 10:59
> {block

can you explain better?

i found a solution to exclude this and anothe rmodule from cache.
https://www.prestashop.com/forums/topic/1011098-products-in-the-same-category-not-displaying-correctly/

possible there is not a right fix to avoid that?
