### ISSUE TITLE
Deleted modules cause undefined index in AdminAccess

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#20871] opened 2020-09-07 06:43 UTC
**Bug:**
In debug mode you will get undefined index `id_module`, `name` etc.
Also, there will be some blank lines in the module list of AdminAccess

**How to reproduce**
Delete some modules (possibly I did outside of PrestaShop by just deleting the files (no uninstall), but I'm not sure. Both uninstall+delete and _hard delete without uninstalling_ first should be tested.
Turn on debug mode and open AdminAccess

**Root cause**
`Module::getModulesAccessesByIdProfile($profile['id_profile']);` returns modules that are not longer in the modules directory, and therefore does not contain enough information to be displayed correctly in the list.
I tried a rather hacky way to remove the issue, and that worked:
   
```
foreach($modules as $id_profile => $profile_modules) {
            foreach($profile_modules as $index_profile_module => $profile_module) {
                if(!isset($profile_module['id_module'])) {
                    unset($modules[$id_profile][$index_profile_module]);
                }
            }
 }
```

But I guess doing something like that in the `Module::getModulesAccessesByIdProfile($profile['id_profile']);` method is better.

PS 1.7.6.7

**Comment by khouloudbelguith** [comment] 2020-09-07 09:20
Hi @onklmaps,

I did not manage to reproduce the issue with PS1.7.6.7.
I checked two options:
1. delete a module from the folder manually => ok
2. uninstall a module & then delete it from the module folder manually => ok

I attached a screen record
https://www.awesomescreenshot.com/video/876372?key=343a0f079b5c03470d9fc89825e167fd
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-09-28 12:01
Hi @onklmaps,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

THanks!

**Closed as completed by khouloudbelguith** 2020-09-28 12:01 UTC
Labels: Bug, BO, Modules, Team, Permissions, No change required
