### ISSUE TITLE
Save & refresh don(t work in products p- prestashop 1.7.8.10

### ISSUE THREAD

**Issue by max06200** [PrestaShop/PrestaShop#33992] opened 2023-09-20 14:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we want change the position of the Products, and we want save the change...when we clic in "Save & refresh", nothing happen

### Steps to reproduce

1.catalogue
2.products
3.select category
4.clic. reorder (position)
5.clic Save & refresh (position)

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

Direct cartouche

**Comment by florine2623** [comment] 2023-09-20 14:42
Hello @max06200 ,

I can't reproduce your issue on PS 1.7.8.10.

https://github.com/PrestaShop/PrestaShop/assets/16019289/c0bc4992-20a0-4612-abed-a08cb07ce867




Can you send a screen record please ?

**Comment by florine2623** [comment] 2023-10-03 15:37
I'm closing the issue as we have not received an answer

**Closed as completed** 2023-10-03 15:37 UTC
Labels: Bug, Catalog, 1.7.8.x
