### ISSUE TITLE
Translations: Priority to apply module translations files in theme

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/PrestaShop#14570] opened 2019-07-10 10:23 UTC
**Describe the bug**
When we translate modules in theme, translations is not applied because modules translations replace module translations are in theme.

**To Reproduce**
1. Copy modules/marketplace/translations/fr.php in themes/classic/modules/marketplace/translations/fr.php
2. Edit translations
3. Translations are not applied

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

The problem is in classes/Translate.php, function getModuleTranslation, variable $filesByPriority that takes themes directory translations before translations of modules directory, so themes translations are replaced :
`$filesByPriority = array(
                // Translations in theme
                _PS_THEME_DIR_ . 'modules/' . $name . '/translations/' . $iso . '.php',
                _PS_THEME_DIR_ . 'modules/' . $name . '/' . $iso . '.php',
                // PrestaShop 1.5 translations
                _PS_MODULE_DIR_ . $name . '/translations/' . $iso . '.php',
                // PrestaShop 1.4 translations
                _PS_MODULE_DIR_ . $name . '/' . $iso . '.php',
            );`

We fix like this:

`$filesByPriority = array(
                // PrestaShop 1.5 translations
                _PS_MODULE_DIR_ . $name . '/translations/' . $iso . '.php',
                // PrestaShop 1.4 translations
                _PS_MODULE_DIR_ . $name . '/' . $iso . '.php',
                // Translations in theme
                _PS_THEME_DIR_ . 'modules/' . $name . '/translations/' . $iso . '.php',
                _PS_THEME_DIR_ . 'modules/' . $name . '/' . $iso . '.php',
            );`

What do you think about this fix?

**Comment by khouloudbelguith** [comment] 2019-07-10 10:26
Hi @bm-services,

Thanks for your report.
Isn't the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/14470.
It is fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/14507
Thanks to check & feedback.

**Comment by bm-services** [comment] 2019-07-10 12:17
I don't think that is the same problem because our problem is in back office in an admin controller of a bought module.
Can my fix agree?

**Comment by khouloudbelguith** [comment] 2019-07-10 14:02
@bm-services, thanks for your feedback.
In my case, I did not manage to reproduce the issue with PS1.7.6.0rc2.
I tried with the `contacform` module.
I copied `/modules/contactform/translations/fr.php` to `/themes/classic//modules/contactform/translations/fr.php`
In the BO => Translations page => when I select the module `contacform` to translate it.
The translation is successfully applied.
https://drive.google.com/file/d/1wN4v-bjvDEwEkUID8fTgnXko05IswxQY/view
I also tried with this module & it is OK.
[translationbug.zip](https://github.com/PrestaShop/PrestaShop/files/3377856/translationbug.zip)

Thanks to check & feedback

PS: we have an Epic issue about the translation: https://github.com/PrestaShop/PrestaShop/issues/13863

**Comment by bm-services** [comment] 2019-07-10 14:08
This problem not occurs when I translate by back office interface because back office interface replace file in www/modules/my_module/translations/fr.php so the problem doesn't exist.
My problem exists when I want to create a translation file in: www/themes/classic/modules/my_module/translations/fr.php
This way allows to override translations to avoid erasement when I upgrade modules.

**Comment by khouloudbelguith** [comment] 2019-07-10 14:22
@bm-services, thanks for these clarifications.
ping @eternoendless, @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by eternoendless** [comment] 2019-07-11 20:03
@bm-services If I understand right:

1. You want to customize a module's translation
2. You want to distribute that translation with your theme

And the problem is that the core gives precedence to the module's translations over the theme's, so you you want this to be the other way around: make the theme's translation have precedence over the module's. Is that so?

It makes sense to me, because themes usually override modules. 

It would seem that this is a regression from this Pull Request: https://github.com/PrestaShop/PrestaShop/pull/8252

**Comment by bm-services** [comment] 2019-07-12 07:09
Hello @eternoendless,
Yes, we want to override modules translations in theme.
For me, change priority in classes/Translate.php can be made like this:
Replace this:
            $filesByPriority = array(
                // Translations in theme
                _PS_THEME_DIR_ . 'modules/' . $name . '/translations/' . $iso . '.php',
                _PS_THEME_DIR_ . 'modules/' . $name . '/' . $iso . '.php',
                // PrestaShop 1.5 translations
                _PS_MODULE_DIR_ . $name . '/translations/' . $iso . '.php',
                // PrestaShop 1.4 translations
                _PS_MODULE_DIR_ . $name . '/' . $iso . '.php',
            );

By this:
$filesByPriority = array(
                // PrestaShop 1.5 translations
                _PS_MODULE_DIR_ . $name . '/translations/' . $iso . '.php',
                // PrestaShop 1.4 translations
                _PS_MODULE_DIR_ . $name . '/' . $iso . '.php',
                // Translations in theme
                _PS_THEME_DIR_ . 'modules/' . $name . '/translations/' . $iso . '.php',
                _PS_THEME_DIR_ . 'modules/' . $name . '/' . $iso . '.php',
            );

**Closed as completed** 2019-09-05 15:28 UTC
Labels: Bug, Translations, Modules & Themes, Fixed, 1.7.5.2
