### ISSUE TITLE
Prestashop 1.7.6.1 Back Office Error

### ISSUE THREAD

**Issue by jvolta-1976** [PrestaShop/PrestaShop#15841] opened 2019-10-04 16:14 UTC
**Describe the bug**
In my back office of prestashop 1.7.6.1 when i go to Order Settings > Shopping Cart to view Active Shopping Carts i'm getting this error http://prntscr.com/pex2zk
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

The rest of my store works fine
Any Ideas?

**Comment by khouloudbelguith** [comment] 2019-10-07 08:00
Hi @jvolta-1976,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-05 07:38
Hi @jvolta-1976,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-05 07:38 UTC
Labels: Bug, BO, Shopping carts, No change required, 1.7.6.1
