### ISSUE TITLE
Prestashop 1.7.6 WS Operations: After Order State Change Email is Not Sent 

### ISSUE THREAD

**Issue by cemalarik** [PrestaShop/PrestaShop#15147] opened 2019-08-18 11:25 UTC
Hello,

I am planning to upgrade my platform to 1.7.6 from 1.6.1.24. Before that, I am trying to be sure that everything works fine  with this new version in my test enviroment.

All is fine, except one:

I manage my orders within another order management platform, and this software is integrated to my shop. After each order status change, it uses web service to my shop to update  it properly.
And the most critical part is informing my customers via auto emails.

In this new version, status updates are done, but emails are not sent to the customer.

Here is an example (raw data);
`POST http://localhost:8080/api/order_histories?ws_key=xxxx&sendmail=1&schema=blank HTTP/1.1`

`Accept-Encoding: gzip,deflate`
`Content-Type: application/xml`
`Content-Length: 278`
`Host: localhost:8080`
`Connection: Keep-Alive`
`User-Agent: Apache-HttpClient/4.1.1 (java 1.5)`

`<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">\n  `
     `<order_history>\n   `
        `<id_employee>1</id_employee>\n  `
        `<id_order_state>2</id_order_state>\n  ` 
            `<id_order>10744</id_order>\n `
       `</order_history>\n`
`</prestashop>`

Response:

`<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">`
   `<order_history>`
      `<id>50410</id>`
      `<id_employee xlink:href="http://localhost:8080/api/employees/1">1</id_employee>`
      `<id_order_state xlink:href="http://localhost:8080/api/order_states/2">2</id_order_state>`
      `<id_order xlink:href="http://localhost:8080/api/orders/10744">10744</id_order>`
      `<date_add>2019-08-18 14:08:39</date_add>`
   `</order_history>`
`</prestashop>`

This operation works just fine with the current version and email is sent. It also updates order status in new version. But no email is sent.

Not: I also tested this on 1.7.2.5. Status is updated and still no email is sent.

Thanks for your help and comments.

**Comment by khouloudbelguith** [comment] 2019-08-19 10:13
Hi @cemalarik,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14953 to fix the issue.
It is added to the 1.7.6.1 milestone.
Your ticket is a duplicate of #14842
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-19 10:13
Duplicate of #14842

**Closed as completed by khouloudbelguith** 2019-08-19 10:13 UTC
Labels: Duplicate
