### ISSUE TITLE
Mail Alert plugin on Prestashop 1.7.6 have some php errors and cause some other plugin errors

### ISSUE THREAD

**Issue by pollat** [PrestaShop/PrestaShop#15339] opened 2019-08-30 16:56 UTC
I updated prestashop to 1.7.6 version, but the "Mail alert" plug-in reports the following php errors:

#1 /home/tn382c5o/public_html/modules/ps_emailalerts/ps_emailalerts.php(330): ToolsCore::displayPrice(49.99, Object(Currency), false)

#2 /home/tn382c5o/public_html/classes/Hook.php(970): Ps_EmailAlerts-&gt;hookActionValidateOrder(Array)

#3 /home/tn382c5o/public_html/classes/Hook.php(355): HookCore::coreCallHook(Object(Ps_EmailAlerts), 'hookactionValid...', Array)

#4 /home/tn382c5o/public_html/classes/Hook.php(907): HookCore::callHookOn(Object(Ps_EmailAlerts), 'actionValidateO...', Array)﻿

Also, these php errors cause some errors on other plugin. 
How could I solve it?
Is a "Mail alert" update available?

**Comment by arouiadib** [comment] 2019-09-01 00:01
@pollat What is the exact error message?

Could you please send a screen shot of the Symfony profiler (under debug mode)?

**Comment by khouloudbelguith** [comment] 2019-09-02 07:48
Hi @pollat,

I did not manage to reproduce the issue with PS1.7.6.1 & ps_emailalerts module v2.1.1 & PHP7.2.13
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-02 07:53
Hi @pollat,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-02 07:53 UTC
Labels: Bug, No change required, ps_emailalerts
