### ISSUE TITLE
Does not translate some phrases 1.7.8.8

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#31578] opened 2023-03-01 05:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have the following lines in the file: /templates/checkout/_partials/cart-detailed.tpl

`{l s='Qty' d='Shop.Theme.Checkout'}`
`{l s='Total' d='Shop.Theme.Checkout'}`

Qty - Does not translate
Total - Translates

![image](https://user-images.githubusercontent.com/6318282/222050763-0352ca5f-da17-4a8a-bc92-2d082a881f85.png)

### Steps to reproduce

1. Go to Translate my template
2. Shop.Theme.Checkout
3. And search Qty
4. translate
5. 
![image](https://user-images.githubusercontent.com/6318282/222051017-6141ac03-c677-43e4-ad7d-8b59a920a5c5.png)

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.2

**Comment by HanaRebaiQA** [comment] 2023-03-02 10:52
Hello @TemKaSD 

Thanks for your report.
I was unable to reproduce your issue when using the same steps to reproduce on my **PS1788** shop. 
In the checkout phase, I have the quantity column and when changing the translation for it it's well changed.

![image](https://user-images.githubusercontent.com/92912932/222408321-a65a2549-90ae-4ca1-8f34-b0b77989cb69.png)

See this screen-record : 

https://user-images.githubusercontent.com/92912932/222408174-5c340eff-8210-4d7a-af94-2bd67847fb2a.mp4


I'll close this issue cause it's maybe related to your theme. 
Feel free to open new tickets when needed!

Thank You!

**Closed as completed by HanaRebaiQA** 2023-03-02 10:52 UTC
Labels: Bug, FO, Translations, Checkout, Invalid, 1.7.8.8
