### ISSUE TITLE
I can't save the modified categories

### ISSUE THREAD

**Issue by albertoamuedo** [PrestaShop/PrestaShop#20915] opened 2020-09-09 09:15 UTC
![Categorías • Barroso hostelería 2020-09-07 11-46-04](https://user-images.githubusercontent.com/71008052/92579647-bdfce700-f28d-11ea-88d5-2de7eed6c758.png)

After changing the order of the categories I can't save them, the save button is missing.

Thank you

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-09-09 09:29
Hi @albertoamuedo,

The template is missing some information.
In the next time, you need to follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 
Is it your issue similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/14504?
When you try to drag & drop between categories => the new modification is not saved?
It is fixed in the next release 1770.
I attached a screen record
https://drive.google.com/file/d/1NfwYjycBReCgFRsrIUSo9-sASPAwUUw8/view?usp=sharing
Thanks to check and feedback.

Thank you

**Comment by albertoamuedo** [comment] 2020-09-09 09:36
thanks for your answer, as i update to 1770?

**Comment by khouloudbelguith** [comment] 2020-09-09 09:42
@albertoamuedo, the 1770 stable version is not released yet.
You can follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/18647 to get news about the PS1770 release.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14529 to fix the issue.
Your ticket is a duplicate of #14504
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-09-09 09:42
Duplicate of #14504

**Closed as completed by khouloudbelguith** 2020-09-09 09:42 UTC
Labels: Bug, BO, Duplicate, Categories, 1.7.6.3
