### ISSUE TITLE
French translation error for Shop > Theme > Catalog

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#25695] opened 2021-08-24 16:56 UTC
#### Describe the bug

When you add a new product, the "new" label is added on the picture of the product for 20 days (by default)
In french, you can see "NEUF" that means "unused", not new

#### Expected behavior

Real translation is "NOUVEAU" : have to be changed in the installation files

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-08-25 07:51
Hello @elmanu13 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17455. 
This issue has been fixed with the new patch release PS1.7.8.0.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-08-25 07:51
Duplicate of #17455

**Closed as completed by hibatallahAouadni** 2021-08-25 07:51 UTC
Labels: Duplicate
