### ISSUE TITLE
Webservice JSON body

### ISSUE THREAD

**Issue by esfahanweb** [PrestaShop/PrestaShop#11099] opened 2018-10-22 04:53 UTC
hi,

is there any idea about your web service interact with JSON?
I know that we can get output data as JSON with output_format=JSON but seems that can't post body as JSON

best regards

**Comment by khouloudbelguith** [comment] 2018-10-22 10:58
Hi @esfahanweb,

Could you please confirm this steps to reproduce the issue?

- `api/product_options/?display=full&output_format=XML&depth=1 `: will generate the good XML, with a list of product_options and the association data filled.
- `api/product_options/?display=full&output_format=JSON&depth=1`: will generate a weird thing: seems like the array of product_options is full of empty elements, and there is an array of product_option_values at the root, containing an aggregation of all the association data for the different supposed-to-be elements.

Thanks!

**Comment by esfahanweb** [comment] 2018-10-22 11:25
the problem is about posting data to web service as JSON ie update a customer.

**Comment by khouloudbelguith** [comment] 2018-10-22 12:34
@esfahanweb, could you please add steps to reproduce the issue in a new comment.
Thanks!

**Comment by esfahanweb** [comment] 2018-10-23 04:09
look at this, please
https://www.prestashop.com/forums/topic/602449-aporte-webservice-prestashop-16-json-request-post-y-put/

**Comment by khouloudbelguith** [comment] 2018-10-23 14:23
Hi @esfahanweb,

I applied the changes provided by Victor.
I attached a video record.
https://drive.google.com/file/d/1ZZqhgmQET3kyxlW7HbsWfcrojOgrwsXD/view
In the database, I have all my customers
![image](https://user-images.githubusercontent.com/16067358/47367740-98d64e00-d6e0-11e8-8816-64b6759ceb9d.png)

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2018-11-27 16:40
Hi @esfahanweb,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-27 16:40 UTC
Labels: Webservice, No change required
