### ISSUE TITLE
PS1.7.5 - psgdpr in Multishop - URL in Text from main Domain

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/PrestaShop#12449] opened 2019-02-06 10:11 UTC
We have noticed that the links in the texts in the PSGDPR module for the contact form and other modules always show the main domain. Changes for the subdomain in multishop wont be accepted. Only texts for the customer account creation and in the customer account are correct. 
The text for the contact form, Wishlist and CMS module are displayed twice.

This issue is very similar in the ps_legalcompliance. 
this link to the shipping costs "<span class="aeuc_shipping_label">" shows in all subdomains the main Domain.

For both modules i try to rest it, delete and a new installation didn't bring any improvement.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2.14

**Comment by khouloudbelguith** [comment] 2019-02-06 11:23
Hi @pdkey,

Is it the same issue reported in this ticket: https://github.com/PrestaShop/psgdpr/issues/50?
Thanks!

**Comment by pdkey** [comment] 2019-02-06 14:34
Hi @khouloudbelguith 
yes the same issue - BUT to reproduce the issue:
- 2 Shops in 2 different groups. than you can see the duplicated compliant modules.
and the issue with the URLs of the Subdomain.

My way:
1. clean installation PS 1.7.4.2
a) install modules psgdpr, ps_legalcompliance and 1-step upgrade
b) full modules it with informations.
3. upgtade to PS 1.7.4.4
a) update all modules
4. upgrade to PS 1.7.5
a) create Shop Group
b) create New base category for new Shop
c) create new shop with own URL
d) check links of both modules
e) ps_legalcompliance - for 2 Shop try to change url in correct, after save it. still its the url of the main shop.

Do you need screens?

best regards

**Comment by khouloudbelguith** [comment] 2019-02-07 10:05
Hi @pdkey,

Thanks for this clarifications.
About the ps_legalcompliance, issue reproduced.
About the `psgdpr` module, in addition to the duplicated content what is the exact incorrect link?, 
I edited the content message for the Account creation
![image](https://user-images.githubusercontent.com/16067358/52403906-183d3100-2ac8-11e9-8306-3de4bf2507b2.png)
And it is well displayed in the different shops.
![image](https://user-images.githubusercontent.com/16067358/52403963-3145e200-2ac8-11e9-8e12-6b5306ad7e72.png)
Thanks!

**Comment by pdkey** [comment] 2019-02-07 10:41
Hi @khouloudbelguith 
1. Text for Account Create and in Account works correct! - everything is fine.
This is in Module list in psgdpr - "PrestaShop Data"

2. ISSUES - In Module list
- Dublicates - Contact form and Newsletter
![psgdpr module list](https://user-images.githubusercontent.com/46047238/52405915-c2b75300-2acc-11e9-9a61-46b85740a165.jpg)

3. dublicate fields
![psgdpr module infos](https://user-images.githubusercontent.com/46047238/52406073-1cb81880-2acd-11e9-9351-50d091da5f99.jpg)

4. Edit text fields
- Main shop works - edit correct
- Subdomain 2. shop in own group have a issue. the shop takes informations from the main shop. try to edit and save without success-

**Comment by pdkey** [comment] 2019-02-07 10:48
@khouloudbelguith both issues (#12449 & #12450) are very important to work with prestashop according to important legal requirements.

This is currently a high risk of penalties. Especially in Germany this can be very expensive for Prestashop users.

**Comment by khouloudbelguith** [comment] 2019-02-07 11:26
Hi @pdkey,

Thanks for your feedback.
About `2.issues - In Module list` `3. dublicate fields`, we are aware of these issues, your ticket is a duplicate of https://github.com/PrestaShop/psgdpr/issues/50 so I will close it because it is a duplicated issue, you need to follow this issue https://github.com/PrestaShop/psgdpr/issues/50
I edited [this issue](https://github.com/PrestaShop/psgdpr/issues/50) to add the information provided.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-07 11:27
Duplicate of https://github.com/PrestaShop/psgdpr/issues/50

**Closed as completed by khouloudbelguith** 2019-02-07 11:27 UTC
Labels: Duplicate, Multistore, GDPR

**Comment by mayesterday** [comment] 2019-05-10 10:01
Welcome to 
<a href="https://www.ufa4live.com/"> UFABET </a>
<a href="https://www.ufa4live.com/%E0%B8%AA%E0%B8%A1%E0%B8%B1%E0%B8%84%E0%B8%A3-ufabet/"> สมัคร UFABET </a>
<a href="https://www.ufa4live.com/%E0%B8%AA%E0%B8%A5%E0%B9%87%E0%B8%AD%E0%B8%95%E0%B8%AD%E0%B8%AD%E0%B8%99%E0%B9%84%E0%B8%A5%E0%B8%99%E0%B9%8C-ufabet/"> สล็อตออนไลน์ UFABET </a>
<a href="https://www.ufa4live.com/%E0%B8%84%E0%B8%B2%E0%B8%AA%E0%B8%B4%E0%B9%82%E0%B8%99%E0%B8%AD%E0%B8%AD%E0%B8%99%E0%B9%84%E0%B8%A5%E0%B8%99%E0%B9%8C-ufabet/"> คาสิโนออนไลน์ UFABET </a>
