### ISSUE TITLE
The "Enter" key on the keyboard does not work with 8.1.3 in the product html space

### ISSUE THREAD

**Issue by EmmaPal** [PrestaShop/PrestaShop#34984] opened 2024-01-05 17:20 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you want to write directly in the html space, the Keybord key "Enter" is not funtionning on both product description and short description.

### Expected behavior

We must be able to write our codes directly in the HTML space with the possibility of organizing the work in each line by "Enter" key.

### Steps to reproduce

1- Try to create a new product, or change an existant product. 
2- Go to the html icon to type your html code
3- Type anything
4- Clic The Keybord key "Enter" 
= > you will find that's impossible

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment] 2024-01-08 09:32
Hello @EmmaPal ,

I can't reproduce your issue. on PS 8.1.3.

https://github.com/PrestaShop/PrestaShop/assets/16019289/3a90159a-ee82-42a8-9d4f-d320359e3d55

So I'm closing it.

**Closed as completed by florine2623** 2024-01-08 09:32 UTC
Labels: Bug

**Comment by EmmaPal** [comment] 2024-01-08 09:54
@florine2623 I can give you my backoffice to see it your self

**Comment by EmmaPal** [comment] 2024-01-08 10:02
I'm trying to help you to make prestashop better. Your video is with "**New experimental product page**".
Try to reproduce the issue with **disabling the new experimental product page**
