### ISSUE TITLE
develop - New & Experimental Features > Attributes group enabled, but migrated page is not displayed 

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35799] opened 2024-04-02 13:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I enabled the new & Experimental Feature for Attribute group, I still have the old page displayed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/31635d69-b807-45c5-afc4-661d5fdcb74e

### Expected behavior

When I enabled the New & Experimental Feature for Attribute group, I should have the migrated page displayed.

<img width="1428" alt="Screenshot 2024-04-02 at 15 42 14" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/191a02e1-fd30-4aec-9c13-11f35d5b2e80">

### Steps to reproduce

1. Install branch develop 
2. Go to BO > New & Experimental Features
3. Enable Attribute group > Save
4. Go to Catalog > Attributes & Features
5. See the old page is still displayed

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by nicosomb** [comment] 2024-04-02 14:19
I can't reproduce the bug on a fresh install.

**Comment by paulnoelcholot** [comment] 2024-04-03 12:41
Hello @florine2623,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://www.loom.com/share/e655f53eaf0f471ebe779fecee3bb5d7?sid=b4a9e722-2dd6-4c39-85a0-5e1029179129

**Closed as completed by paulnoelcholot** 2024-04-03 12:41 UTC
Labels: Bug, Can't reproduce
