### ISSUE TITLE
Add new Image Type CTA button vanishes, new Save CTA button appears

### ISSUE THREAD

**Issue by SimonasB88** [PrestaShop/PrestaShop#26552] opened 2021-11-08 15:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Steps to reproduce in video of screen capture:

https://user-images.githubusercontent.com/29095235/140772516-ad1bf836-68d7-4491-9a4f-d2b644f1ef46.mp4

### Expected behavior

After saving the Image Generation options, the user is unable to add new Image Type. Instead, a new Save icon appears in the top-right of the Image Type table. However, the icon is linked to the simple #.
If the user navigates back to Image Settings via menu panel, the CTA button appears again.
Nothing wrong appears in frontend or backend logs during this reproduction.

### Steps to reproduce

1. Go to Design > Image Settings 
2. Save valid custom Image generation data to the form

### PrestaShop version(s) where the bug happened

1.7.8.0 Multistore

### PHP version(s) where the bug happened

7.1

**Comment by florine2623** [comment] 2021-11-09 10:38
Hello @SimonasB88 ,

I was able to reproduce the issue with PrestaShop version 1.7.8.0 and develop branch (Multistore and single store), so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment] 2022-02-03 19:02
Ping @florine2623 & @SimonasB88 did you reproduce the issue with an older version or you only encounter this issue on 1.7.8.0?

**Comment by SimonasB88** [comment] 2022-02-07 10:11
@hibatallahAouadni Seems like this bug is left in all the PS1.7.x versions, also in PS1.6.1.10 PHP 5.6 - Add new Image plus icon vanishes, but the mini Save icon doesn't appear.

**Comment by florine2623** [comment] 2024-11-27 08:55
The issue is fixed on the migrated Symfony page on PS 9.0.0:

https://github.com/user-attachments/assets/82eee261-fd63-4c7c-ada8-5a6a03dd4655

Closing this issue ^^
Thanks!

**Closed as completed by florine2623** 2024-11-27 08:55 UTC
Labels: Bug, Minor, BO, Design, Image, Fixed, 1.7.7.8, Verified
