### ISSUE TITLE
Install an invalid carrier module from the Carriers page - mbo installed 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12123] opened 2019-01-11 15:01 UTC
**Describe the bug**
When the `mbo` module is installed, in the BO => Shipping => Carriers page, we try to install an invalid module (module with issues), we are redirected to Module Catalog Page.
We should have a red alert that this module has an error during the installation despite of the redirection to Catalog Page.

**To Reproduce**
mbo module must be installed.
1. Go to BO => Shipping => Carriers page
2. Try to install "Chronopost" module
3. You are redirected to Module Catalog Page 
4. If you try to install it, a red alert is displayed "Error!
Cannot install module chronopost. Unfortunately, the module did not return additional details."

**Screenshots**
https://drive.google.com/file/d/1rbyLNih7qI3egAgFoGMjEUV6tinYLDRX/view

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1
mbo version: 1.1.1

**Comment by khouloudbelguith** [comment] 2019-01-11 15:02
Ping @YosraAk

**Comment by marionf** [comment] 2019-01-11 16:04
Duplicate of #11388

**Closed as completed by marionf** 2019-01-11 16:04 UTC
Labels: Bug, Minor, BO, Duplicate, Carriers, 1.7.5.0, MBO
