### ISSUE TITLE
Category import produce error

### ISSUE THREAD

**Issue by renatox57** [PrestaShop/PrestaShop#12998] opened 2019-03-21 15:56 UTC
When we try to import categories, we obtain this error : 
[2019-XX-XX 16:36:59] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to load template 'file:layout-ajax.tpl'")." at /XXX/XXX/XXX/XXX/XXX/www/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig line 34 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to load template 'file:layout-ajax.tpl'\"). at /XXX/XXX/XXX/XXX/XXX/www/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig:34, SmartyException(code: 0): Unable to load template 'file:layout-ajax.tpl' at /XXX/XXX/XXX/XXX/XXX/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:195)"} []

Can you help on this please ?

**Comment by khouloudbelguith** [comment] 2019-03-21 16:03
Hi @renatox57,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1C4AMPfJGM-oWr5JHO8US-tnBcPU3hRTn/view
Could you please provide me the exact file did you used to import categories.
Thanks!

**Comment by renatox57** [comment] 2019-03-22 10:52
Hi @khouloudbelguith,
thank you for your quick answer.
Here is the exact fil : https://filetransfer.io/data-package/kMb9TLKj
Renato

**Comment by khouloudbelguith** [comment] 2019-03-22 13:51
Hi @renatox57,

Your file contains errors.
Thanks to cheek and feedback.

**Comment by renatox57** [comment] 2019-03-27 10:19
Hello khouloudbelguith,
thank you for your answers. I have rebuild completly the import file and now it work.

I have a new problem about tax rule group ID. When importing products I have this error : 
"Some errors were detected. Please check the details:
id_tax_rules_group (ID 9) Unknown tax rule group ID. You need to create a group with this ID first."

Is there a way to import the taxes ?

Thank you in advance for your help,

Renato

**Comment by khouloudbelguith** [comment] 2019-03-27 10:58
Hi @renatox57,

Is your new problem related to the old?

**Comment by khouloudbelguith** [comment] 2019-04-26 07:50
Hi @renatox57,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by webmak** [comment] 2019-07-09 07:16
Confirm same issue

**Comment by webmak** [comment] 2019-07-09 08:06
@khouloudbelguith problem is that in new admin theme missing laytouts

**Comment by khouloudbelguith** [comment] 2019-07-09 08:10
Hi @webmak,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/1ZWA1oSnC31B5vVA67rDDXZZF0_5toOqp/view
Thanks!

**Comment by webmak** [comment] 2019-07-09 08:51
@khouloudbelguith  because you are using correct import file))
if not correct then this code in category throw exceptions
`public function calcLevelDepth()
    {
        /* Root category */
        if (!$this->id_parent) {
            return 0;
        }

        $parentCategory = new Category((int) $this->id_parent);
        if (!Validate::isLoadedObject($parentCategory)) {
            if (is_array($this->name)) {
                $name = $this->name[Context::getContext()->language->id];
            } else {
                $name = $this->name;
            }
            throw new PrestaShopException('Parent category ' . $this->id_parent .
                ' does not exist. Current category: ' . $name);
        }

        return (int) $parentCategory->level_depth + 1;
    }`
And it redirect to not correct with not correct layout instead show errors.

I've this error Parent category 34 does not exist. Current category if modify 

`public static function redirectAdmin($url)
    {
        var_dump(Context::getContext()->controller->errors);
        exit;
        throw  new Exception('test');
        header('Location: ' . $url);
        exit;
    }`


To fix fast im my case I've wrap 
`try {
                $this->categoryImportOne(
                    $info,
                    $default_language_id,
                    $id_lang,
                    $force_ids,
                    $regenerate,
                    $shop_is_feature_active,
                    $cat_moved, // by ref
                    $validateOnly
                );
            } catch (Exception $exc) {
                $this->errors[] = $exc->getMessage();
            }`

**Comment by webmak** [comment] 2019-07-09 09:04
@khouloudbelguith here is my pull request to fix it https://github.com/PrestaShop/PrestaShop/pull/14540 but you should consider more globaly you exeptions hanlder politic

**Comment by khouloudbelguith** [comment] 2019-07-09 09:39
@webmak, I tried to import an incorrect file, but I don't have any exception.
![image](https://user-images.githubusercontent.com/16067358/60877422-b1b66d80-a235-11e9-8f3b-c873a9ae01fb.png)

Thanks!

**Comment by webmak** [comment] 2019-07-09 09:41
@khouloudbelguith you can try to import category with id rewrite and set parent id to not existed category and it should reproduce. Or you can modify cod to throw some exeption inside categoryImportOne method and you'll get this bug

**Comment by khouloudbelguith** [comment] 2019-07-09 09:44
@renatox57, yes, I tried to import a csv file with incorrect id for the Parent category.
I used this file.
[categories_import.csv.txt](https://github.com/PrestaShop/PrestaShop/files/3372349/categories_import.csv.txt)

Thanks!

**Comment by PierreRambaud** [comment] 2019-07-12 15:48
Since the pull request is not closed, I reopen the issue (https://github.com/PrestaShop/PrestaShop/pull/14540)
Are you still unable to reproduce @khouloudbelguith ?

**Comment by khouloudbelguith** [comment] 2019-07-16 16:04
Hi @PierreRambaud,

Before checking the PR, when we import a CSV file with incorrect data (incorrect Parent category), I have a red alert without exceptions.
https://drive.google.com/file/d/1fGitfaIXBMkL0XizauTInjSDJSHLEoWC/view
![image](https://user-images.githubusercontent.com/16067358/61309819-df2d8900-a7ea-11e9-93c3-71df169a8574.png)
After testing this PR: https://github.com/PrestaShop/PrestaShop/pull/14540
The error is more clear
![image](https://user-images.githubusercontent.com/16067358/61310170-ab069800-a7eb-11e9-8c9e-e3cc0e5c7c28.png)
https://drive.google.com/file/d/1lAEhED2RvJO6mPZwhnTB055gbUPAjUS3/view

Thanks!

**Comment by matks** [comment] 2019-07-17 12:34
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14540

**Closed as completed by matks** 2019-07-17 12:34 UTC
Labels: BO, Import / Export, Fixed, 1.7.5.1
