### ISSUE TITLE
ZIP code in address checked wrong don't display the error

### ISSUE THREAD

**Issue by polaije** [PrestaShop/PrestaShop#11252] opened 2018-11-03 10:51 UTC
**Describe the bug**
When a customer enter a new address, or modify it, and the zip code is not corresponding to the format for the country (see admin), the address is not saved and no error is displayed, the address page is relaoded.

**To Reproduce**
1. Go to address in order page
2. Enter a not correct zip code, like 4680 for Holland (correct is 4680NA), the format check must be enabled in admin country.
3. Click on continue...
4. No message, must be 'wrong format' on zip code

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 5.6.38

This bug occurs after changing the code in the theme (not the default) according to the boom-2227 (changing country in address you exit the order tunnel).

**Comment by khouloudbelguith** [comment] 2018-11-05 08:21
Hi @polaije,

I did not manage to reproduce the issue with the last version 1.7.4.3.
I attached a video record.
https://drive.google.com/file/d/1m0v-4Vh1h6eniqtSY_8OpMXUATZcUMI_/view
Did you installed any pack of Holland from the International => Localisation page?
Thanks!

**Comment by polaije** [comment] 2018-11-05 08:49
Yes, I have installed the international pack Holland.

**Comment by khouloudbelguith** [comment] 2018-11-05 08:52
@polaije, could you please provide me a screenshot about your issue.
Thanks!

**Comment by polaije** [comment] 2018-11-05 17:51
I can only provide a video because no error appears, only address is not saved.
I have done some testing and with the plugin litespeed cache desintalled I can have the message wrong format in zip code. 
This is a cache problem but it is diffficult to isolate the issue, sometimes it is ok, sometime not.

**Comment by khouloudbelguith** [comment] 2018-11-06 08:54
Hi @polaije,

Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2018-12-11 16:17
Hi @polaije,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-11 16:17 UTC
Labels: BO, Order, Addresses, No change required, 1.7.4.3
