### ISSUE TITLE
BO - Invoice / Product taxes detail is not displayed on the invoice depending on where the invoice is called

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#20452] opened 2020-08-04 13:46 UTC
#### Describe the bug

For the same order, depending on where the invoice is called ; the products taxes details is not displayed / printed on the invoice 😱 

#### Expected behavior

The product taxes details should be printed / displayed on the invoice no matter where the invoice is called from.

#### Steps to Reproduce

1. Go to FO and create an order
2. Go to the BO => go to the detail of the previously created order
3. Generate the invoice for this order
4. Consult the invoice => the product taxes detail is on the invoice
5. Go back to the order list
6. Click on the quick view to see the freshly generated invoice
7. See error => the product taxes detail is not on the invoice

**Screenshots**

**Invoice from the order detail**
![Screenshot at 15-43-32](https://user-images.githubusercontent.com/40635814/89301010-5c7fa200-d669-11ea-8ef9-a5e0ac482a0e.png)

**Invoice from the orders list**
![Screenshot at 15-43-59](https://user-images.githubusercontent.com/40635814/89301024-62758300-d669-11ea-83bd-8ea7e8ff1e49.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1

**Comment by matks** [comment] 2020-08-04 16:38
OK, I did some debugging on this one this evening.

The 2 different results come from the fact that the 2 "get invoice" buttons do not target the same controller
- in "view an order" page it targets legacy "get a PDF" endpoint
- in "order list" page, inside quickview it targets new "get Invoice" Symfony endpoint

So basically legacy endpoint and new endpoints provider different results although it should be identical 😄 

## In legacy endpoint

`AdminPdfController::generateInvoicePDFByIdOrderInvoice()` is called and the final call is
```
$pdf = new PDF($object, $template, Context::getContext()->smarty);
```
where `$object` is an Invoice ObjectModel instance

## In Symfony endpoint

PDF generation happen in service OrderInvoicePdfGenerator that call
```
        $pdf = new PDF($order_invoice_list, PDF::TEMPLATE_INVOICE, Context::getContext()->smarty);
```
where `$order_invoice_list` is a PrestaShopCollection object that come from `Order::getInvoicesCollection()` . It seems the idea is that it handles multiple invoices, contrarily to legacy endpoint.

So the root cause seem to be that `$object` and `$order_invoice_list` objects are built differently, hence the difference in output.

Possible easy fixes:
- use legacy endpoint in "view an order page" (to be later replaced by Symfony endpoint)
- use OrderInvoice object instead of PrestaShopCollection (but then I'm not sure multi-invoices are supported)

**Comment by matks** [comment] 2020-08-11 15:15
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20477

**Closed as completed by matks** 2020-08-11 15:15 UTC
Labels: Bug, Critical, BO, Order, Invoices, Regression, Fixed, PR available, Must-have, 1.7.7.x
