### ISSUE TITLE
Cannot update from v.1.7.5.0 to 1.7.6.0

### ISSUE THREAD

**Issue by vallka** [PrestaShop/PrestaShop#14811] opened 2019-07-22 14:22 UTC
After failing to update with 1-Click update tried manual update. Copied the files. Got this error when ran 

    vallka
    Members
    0
    2 posts

    Report post 

Posted July 15 (edited)

$ php install/upgrade/upgrade.php

PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "prestashop.core.localization.cldr.locale_repository". Did you mean one of these: "prestashop.core.localization.pack.import.importer", "prestashop.core.localization.pack.loader.local", "prestashop.core.localization.pack.loader.remote"? in /mnt/d/Users/Valentine/Documents/GitLab/gellifique/gellifique-webshop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:348
Stack trace:
#0 /mnt/d/Users/Valentine/Documents/GitLab/gellifique/gellifique-webshop/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php(55): Symfony\Component\DependencyInjection\Container->get('prestashop.core...')
#1 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang()
#2 /mnt/d/Users/Valentine/Documents/GitLab/gellifique/gellifique-webshop/src/PrestaShopBundle/Install/Upgrade.php(483): call_user_func_array('ps_1760_copy_da...', Array)
#3 /mnt/d/Users/Valenti in /mnt/d/Users/Valentine/Documents/GitLab/gellifique/gellifique-webshop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php on line 348 

**Additional information**
PrestaShop version: 1,7.5.0 => 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-22 14:46
Related to: #14812

**Comment by khouloudbelguith** [comment] 2019-07-22 14:47
Hi @vallka,

What is the exact version of the 1-click upgrade module did you use?

Thanks!

**Comment by vallka** [comment] 2019-07-22 15:39
1-Click Upgrade
v4.9.0 - by PrestaShop



------ Original Message ------

**Comment by MKV-Rob** [comment] 2019-07-22 17:08
**Hello,**

I am having same issue. I have tried Autoupgrading on different servers with "Presta-friendly" configurations without success - PHP 5.6.24/5.6.40-8/7.3.1.

I've tried with 1-Click upgrade module v4.7.0 and v4.9.0.

With PHP 5.x.x I am getting longer error text but the core of the problem is always the same: 
_ps_1760_copy_data_from_currency_to_currency_lang.php(55)_

The shop I am trying to upgrade is running with only Czech language and CZK/EUR currencies.

EDIT: I am trying to upgrade from 1.7.5.2.

**Comment by khouloudbelguith** [comment] 2019-07-23 09:21
Hi @vallka, @MKV-Rob,

We are aware of this issue, it is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/14620 which fixes those issues: https://github.com/PrestaShop/PrestaShop/issues/14617 similar to your problem @vallka & this issue https://github.com/PrestaShop/PrestaShop/issues/14591 similar to your problem @MKV-Rob.

Your ticket is a duplicate of #14617
So, I close it.
Thanks!

**Closed as completed by khouloudbelguith** 2019-07-23 09:21 UTC
Labels: Bug, BO, Duplicate, Autoupgrade, 1.7.5.0

**Comment by vallka** [comment] 2019-07-23 10:28
Ok, you closed it, it's fine for you.

But what I am supposed to do? Migrate to X-cart I suppose..... How can I 
upgrade my Prestashop to the latest version?

------ Original Message ------

**Comment by khouloudbelguith** [comment] 2019-07-23 10:31
@vallka, PS1.7.6.1 will be released soon, this issue is fixed in the PS1.7.6.1.
I just tested the upgrade from PS1.7.5.2 to PS1.7.6.1(where this PR is included) & it is OK.

Thanks!

**Comment by MKV-Rob** [comment] 2019-07-23 15:19
@khouloudbelguith - that's good news - thanks for it. Any ETA for 1.7.6.1?

**Comment by copyact** [comment] 2019-10-16 07:16
Hello, today I tried to update 1.7.5.1 to 1.7.6.1 with 1ClickUpgrade and I got the same error:
autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Call to a member function get() on null

I thought that in 1.7.6.1 it was corrected. What should I do to update?

**Comment by khouloudbelguith** [comment] 2019-10-16 09:09
@copyact, the issue created here: https://github.com/PrestaShop/PrestaShop/issues/15972
