### ISSUE TITLE
Reference number of product is incorrect in Shopping Carts

### ISSUE THREAD

**Issue by Kerami82** [PrestaShop/PrestaShop#22854] opened 2021-01-15 13:54 UTC
When I check Shopping Carts (NOT orders) the reference of products in all shopping carts are wrong (there is product name instead reference). This problem is also in official demo of prestashop 1.7.7.1. 
In orders this problem don`t exists. Only shopping carts are affected.

To check this go to https://demo.prestashop.com/#/en/back, then Orders > Shopping Carts. Check cart and list off products in it. All reference are wrong.

**Comment by Kerami82** [comment] 2021-01-15 14:03
<img width="956" alt="reference" src="https://user-images.githubusercontent.com/37613614/104736172-de104b80-5742-11eb-95c7-0f9d835e8613.png">

**Comment by florine2623** [comment] 2021-01-15 14:06
Hello @Kerami82 ,

I was able to reproduce the issue with PrestaShop version 1.7.7.1. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

In shopping cart, the product reference is the name of the product instead of the product reference.

![Capture d’écran 2021-01-15 à 15 02 24](https://user-images.githubusercontent.com/16019289/104736157-d781d400-5742-11eb-89b8-2c7aac32bc3a.png)
![Capture d’écran 2021-01-15 à 15 02 15](https://user-images.githubusercontent.com/16019289/104736167-d9e42e00-5742-11eb-9967-1c4a0831b488.png)

Thank you

**Comment by marionf** [comment] 2021-01-18 09:37
@florine2623 It seems to be a regression of the 1.7.7

![capture d'écran_2925](https://user-images.githubusercontent.com/13449658/104897996-5fe9ba00-5979-11eb-9b1d-58cc121799e4.png)

![capture d'écran_2926](https://user-images.githubusercontent.com/13449658/104898006-61b37d80-5979-11eb-86d2-9530a9f05a3c.png)

**Comment by Progi1984** [comment] 2021-01-20 10:27
Fixed by #22863

**Closed as completed by Progi1984** 2021-01-20 10:27 UTC
Labels: Bug, Minor, BO, Shopping carts, Regression, Fixed, PR available, 1.7.7.1
