### ISSUE TITLE
Product Comments : Page refresh after click

### ISSUE THREAD

**Issue by acidlavaa** [PrestaShop/PrestaShop#34649] opened 2023-11-22 10:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

On a product with reviews, when clicking on "Read user reviews" (linked to an anchor by the module), the page refresh quicky after.

Any idea on how to fix this issue ? Thanks.

<img width="503" alt="Capture d’écran 2023-11-22 à 11 28 49" src="https://github.com/PrestaShop/PrestaShop/assets/151734296/d215f491-137f-4ef9-ba97-4ce40de6ef11">
<img width="377" alt="Capture d’écran 2023-11-22 à 11 28 46" src="https://github.com/PrestaShop/PrestaShop/assets/151734296/8f611bc5-b5af-48c8-baae-1bd0f6bedf96">

### Expected behavior

Should stay to the comments list without refreshing the page.

### Steps to reproduce

Click to "Read user reviews" on a product with reviews.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

Product Comments

**Comment by paulnoelcholot** [comment] 2023-11-22 13:47
Hello @acidlavaa,

Despite our efforts, we were not able to reproduce your issue. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

[Hummingbird notebook.webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/be1e9b86-26e8-48dd-b370-926a483539a2)

**Closed as completed by paulnoelcholot** 2023-11-22 13:47 UTC
Labels: Bug, FO, Can't reproduce, Productcomments, 8.1.x
