### ISSUE TITLE
Unpossible to change style in the pages (non-shop)

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#17758] opened 2020-02-20 13:11 UTC
Hello!
In the Design->Pages I try all possible css style to change text layout in the table row.
But any formatting do not have result. I want my text lay in the middle of the row 
<td align="center" style="vertical-align: bottom; background-color: #e9e6e6;">
<h3 id="components">Компоненты умного дома</h3>
</td>
But in the browser the text is top of the row

![image](https://user-images.githubusercontent.com/50954519/74936619-228c4d80-53f3-11ea-9f07-5f788e2d4da4.png)

What`s wrong?

**Comment by florine2623** [comment] 2020-02-20 13:43
Hello @photinia73,
I can't reproduce the error on PS 1.7.6.3. Here's the result :
![Capture d’écran 2020-02-20 à 14 40 26](https://user-images.githubusercontent.com/16019289/74938778-f66ecd80-53ee-11ea-8114-0e8cbe0a57bc.png)
I used the following element in table HTML:
```
<table border="1" width="465" style="height: 99px; width: 465px; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align: center;">Компоненты умного дома</td>
<td style="text-align: center;">Компоненты умного дома</td>
</tr>
</tbody>
</table>
```
Please check and give me feedback!

**Comment by photinia73** [comment] 2020-02-20 13:58
Unfortunately I have PS 1.7.5.2 You code don`t help ((Just the width of the table changed, but not vertical align (( З повагоюКричмарівська Світлана От: florine2623Отправлено: четверг, 20 февраля 2020 г. в 15:43Кому: PrestaShop/PrestaShopКопия: photinia73; MentionТема: Re: [PrestaShop/PrestaShop] Unpossible to change style in the pages (non-shop) (#17758) Hello @photinia73,I can't reproduce the error on PS 1.7.6.3. Here's the result :I used the following element in table HTML:<table border="1" width="465" style="height: 99px; width: 465px; margin-left: auto; margin-right: auto;"> <tbody> <tr> <td style="text-align: center;">Компоненты умного дома</td> <td style="text-align: center;">Компоненты умного дома</td> </tr> </tbody> </table> Please check and give me feedback!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by photinia73** [comment] 2020-02-20 14:05
Unfortunately I have PS 1.7.5.2 
You code don`t help ((
Just the width of the table changed, but not vertical align ((
I tried style="vertical-align=...." all variants but any changes. 

![image](https://user-images.githubusercontent.com/50954519/74940927-df35dd00-53fa-11ea-89ab-c07c46555e75.png)

**Comment by photinia73** [comment] 2020-02-20 14:07
The PS 1.6.3 is stable?

**Comment by khouloudbelguith** [comment] 2020-02-20 14:23
Hi @photinia73, I tried in my case also with PS1.7.6.3
I used this Source code

```php
<table border="1" width="465" style="height: 222px; width: 506px; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td bgcolor="#00FF00" style="text-align: center;">Компоненты умного дома</td>
<td style="text-align: center;">Компоненты умного дома</td>
</tr>
<tr>
<td style="text-align: center;">text1</td>
<td style="text-align: center;">text2</td>
</tr>
<tr>
<td style="text-align: center;">text3</td>
<td style="text-align: center;">text4</td>
</tr>
<tr>
<td style="text-align: center;">text5</td>
<td style="text-align: center;">text6</td>
</tr>
</tbody>
</table>
```
It is well displayed
![image](https://user-images.githubusercontent.com/16067358/74942270-66cc1d80-53f4-11ea-8715-bbd690171470.png)

FO:
![image](https://user-images.githubusercontent.com/16067358/74942523-751a3980-53f4-11ea-9219-8cb16dab6332.png)

ps1.7.6.3, it is the last version PrestaShop stable.

I tried with PS1.7.5.2 and it is ok also
https://drive.google.com/file/d/1BGW8aRGoe7aHlCTuaQU3B8yOZ7Xbq0gC/view

Thanks!

**Comment by photinia73** [comment] 2020-02-20 15:04
Yes, it work without tag  H3 (( 
With this tag it looking
![image](https://user-images.githubusercontent.com/50954519/74947114-0d1f1f80-5403-11ea-971e-c5366bb01771.png)

**Comment by photinia73** [comment] 2020-02-20 15:08
But it look good enough with TH instead TD
Thank you, find the problem. Will try the 1.7.6.3 ))

**Comment by khouloudbelguith** [comment] 2020-02-20 15:21
@photinia73, since it is fixed.

I will close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2020-02-20 15:21 UTC
Labels: Bug, FO, Pages, No change required
