### ISSUE TITLE
Product Pack calculating stocks wrong

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [PrestaShop/PrestaShop#25450] opened 2021-07-28 11:31 UTC
#### Describe the bug

When Pack contains a combination of a product, and its quantity is lower than needed to buy a Pack , it is still possible to buy a Pack if rest of combinations of this product combined have requied quantity

#### Expected behavior

Pack shouldn't be able to purasche if that certain combination does not match the requied quantity in Pack

#### Steps to Reproduce

1. Create Pack with 2 products
2. One of added products need to have at least 2 combinations (in my case i have my own attribute called "Cache"
3. Make Pack decrement only products after purasche
4. Set quantity of one combination(that one which is assigned to Pack) to less that amount requied to buy a Pack and second to higer than requied in Pack
5. Then you should have warning which says there are not enough items in stock to buy the Pack, but instead you are able to buy it

**Screenshots**

https://i.imgur.com/ZS0mDNX.png
https://i.imgur.com/wb351fb.png

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.1.32

**Comment by hibatallahAouadni** [comment] 2021-07-28 13:58
Hello @Maciej-Wilkosz 

I didn't manage to reproduce your issue with PS1775, see the attached screenshots below:

**BO**
![image](https://user-images.githubusercontent.com/23308427/127335036-3d273f95-0954-47d6-8a50-3afd5dc9be93.png)

**FO**
![image](https://user-images.githubusercontent.com/23308427/127335065-68457d14-3780-440d-a1c6-0d006c9516d3.png)

> instead you are able to buy it

I'm not able to buy it cause the button is disabled :wink: 
Please check and feedback.

Thanks!

**Comment by Maciej-Wilkosz** [comment] 2021-07-29 07:23
Hi , thanks for answer :)

I still have the issue, i recorded a GIF showing the problem step by step:
https://i.imgur.com/NraNVT8.gif

Also that may be the issue i adding Pack using WebService, and maybe i inserting wrong values. But for now it looks like a bug for me

EDIT: I tested it on default product pack, and same problem, so it's not the issue with WebService

**Comment by khouloudbelguith** [comment] 2021-07-30 10:17
Hi @Maciej-Wilkosz,

Thanks for your feedback.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/23742 to fix the issue.
It is fixed in the PS1780.
Your ticket is a duplicate of #13769
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-07-30 10:17
Duplicate of #13769

**Closed as completed by khouloudbelguith** 2021-07-30 10:17 UTC
Labels: Bug, FO, Duplicate, Combinations, Pack, 1.7.7.5
