### ISSUE TITLE
Import Combinations not take effect in product page

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#18816] opened 2020-04-24 21:47 UTC
Import products with unique id - OK
Import combinations with same id at product combinations - OK

![1](https://user-images.githubusercontent.com/54105234/80259149-d83a7d80-867c-11ea-84ac-c3cec7e1d32c.JPG)
![2](https://user-images.githubusercontent.com/54105234/80259353-4c752100-867d-11ea-97d6-c6a92505f0d1.JPG)

#### Expected behavior
Product page only have first combination
Images created
Features and atributes with values created 
![3](https://user-images.githubusercontent.com/54105234/80259466-8f36f900-867d-11ea-8bad-b4dbce99d64a.JPG)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by PierreRambaud** [comment] 2020-04-27 14:40
Hi @Borgas and thanks for your feedback. Could you provide us a CSV to reproduce the same behaviour as you have please?

Kind regards

**Comment by Borgas** [comment] 2020-04-27 17:34
@PierreRambaud 
Here it is...
This struture worked in 1.7.6.0
It only creates the first combination in first ID found with product combination

I don´t know if you are responsable for the import feature, but another bug found is with prices
I now have to have a field with price with and without vat. Even if you have the field for ID VAT

Here is a sample of products and combinations
Remember to change to UTF-8 :)

[Book1.xlsx](https://github.com/PrestaShop/PrestaShop/files/4541188/Book1.xlsx)

**Comment by florine2623** [comment] 2020-05-18 15:45
Hi @Borgas ,
Sorry for taking so long to answer.
I managed to successfully import products with combinations in my test shop.
On your file, you are using one product ID by combination. That is not right, you should have something similar to this doc :
[combinations_import.xlsx](https://github.com/PrestaShop/PrestaShop/files/4645156/combinations_import.xlsx)

Please check and let me know.

**Comment by Borgas** [comment] 2020-05-20 13:44
Hi @florine2623 
Products with combination are in same ID
This is a "complex" excel that i have.
Maybe "cleaning" the products in file, that don´t have combinations?
This construction worked in 1.7.6.0
![Capturar](https://user-images.githubusercontent.com/54105234/82453425-69e4b180-9aa8-11ea-90ee-168909515539.JPG)

**Comment by florine2623** [comment] 2020-05-20 17:00
I've tried with a piece of your CSV file, it works well :
![Capture d’écran 2020-05-20 à 18 57 54](https://user-images.githubusercontent.com/16019289/82474817-e5a42580-9acb-11ea-80ba-282fb3d5c50e.png)
The file I used : 
[22.xlsx](https://github.com/PrestaShop/PrestaShop/files/4658257/22.xlsx)
I did it for your product 6066, i just changed it with my own ID 22.

Please try again and let me know!

**Comment by florine2623** [comment] 2020-06-11 08:05
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-11 08:05 UTC
Labels: Bug, Import / Export, Product customization, No change required, 1.7.6.5
