### ISSUE TITLE
Product combination quantity

### ISSUE THREAD

**Issue by 1Presta-czsk** [PrestaShop/PrestaShop#29455] opened 2022-08-26 14:22 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Editing product with combinations, setting quantity in combinations tab. When is negative value set (-10), combination is saved and shows -10, but after refresh changes to 10

### Expected behavior

Standard product quantity set to -10 works and shows -10 after refresh. Also in 1.7 negative quantity is possible

### Steps to reproduce

Go to backoffice, edit product with combinations
Click combinations tab
Set negative value
Update
Refresh browser

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-08-26 15:50
Hello @1Presta-czsk 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25545. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2022-08-26 15:50
Duplicate of #25545

**Closed as completed by hibatallahAouadni** 2022-08-26 15:50 UTC
Labels: Bug, Duplicate, Invalid
