### ISSUE TITLE
The detail of the page is an Error 505 that arose after the cache was emptied from the store administrator.

### ISSUE THREAD

**Issue by aromadebebe** [PrestaShop/PrestaShop#17630] opened 2020-02-12 18:23 UTC
El detalle de la página es un Error 505 que surgió a partir de que se vació el caché desde el administrador de la tienda. Solicité ayuda a soporte técnico del servicio de hosting y sólo me orientaron para hacer el archivo error_log.php para identificar dónde estaba sucediendo dicho error.

La chica que me atendió me mandó estos enlaces:
https://www.hostinger.es/como/estoy-recibiendo-el-error-internal-server-error-500
http://forge.prestashop.com/browse/BOOM-5922

Hice tal cual todo el proceso y esto fue lo que me arrojó:

 
![image](https://user-images.githubusercontent.com/60982492/74364802-78794980-4d92-11ea-9074-d94a847fdaf7.png)

Los de soporte no me supieron solucionar y se limitaron a decirme que debo buscar en Google la solución de acuerdo al error que me marca. Revisé el documento en cuestión y vi las líneas de código pero es una programación PHP a la cual no quise moverle hasta que alguien que supiera de esto me orientara.

Durante lo que me estuvo guiando me sugirió vaciar el caché del servidor, cambiar la versión de PHP de 7.2 a 7.0, detectar la fuente del error en el error_log y nada funcionó. Ésta es la línea de código que dice que hay que cambiar pero desconozco lo que se tenga que agregar o quitar:

 

Al hacer un cambio de plantilla en el administrador de la tienda, se corrige el error. Quito la plantilla que compramos y dejo la de default, pero al activa de nuevo la plantilla vuelve a aparecer el error 505. Por ahora dejé activa la de default pero necesitamos trabajar con la plantilla que se compró.

**Comment by khouloudbelguith** [comment] 2020-02-13 08:08
Hi @aromadebebe,

Please, send your request in English.
English is the norm on the GitHub 
Thank you!

**Comment by aromadebebe** [comment] 2020-02-13 19:28
The detail of the page is an Error 505 that arose after the cache was emptied from the store administrator. I requested help from the technical support of the hosting service and they only guided me to make the error_log.php file to identify where this error was happening.

The girl who attended me sent me these links:
https://www.hostinger.es/como/estoy-recibiendo-el-error-internal-server-error-500
http://forge.prestashop.com/browse/BOOM-5922

I did the whole process as it was and this was what threw me:
![image](https://user-images.githubusercontent.com/60982492/74470651-8f886c00-4e64-11ea-9fec-37e5bfe80cb5.png)
The support did not know how to solve me and they just told me that I should search Google for the solution according to the error that marks me. I reviewed the document in question and saw the lines of code but it is a PHP programming that I didn't want to move until someone who knew about this guided me.

During what he was guiding me he suggested clearing the server cache, changing the PHP version from 7.2 to 7.0, detecting the source of the error in the error_log and nothing worked. This is the line of code that says you have to change but I don't know what needs to be added or removed:

When making a template change in the store manager, the error is corrected. I remove the template that we bought and leave the default one, but when you activate the template again, error 505 reappears. For now I left the default one active but we need to work with the template that was purchased.

**Comment by khouloudbelguith** [comment] 2020-02-14 11:28
Hi @aromadebebe,

What is the exact page is displayed with error?
Is it in the Back office or Front office?

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-16 08:17
Hi @aromadebebe,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-16 08:17 UTC
Labels: Bug, No change required
