### ISSUE TITLE
Can't edit shipping to add tracking number

### ISSUE THREAD

**Issue by jnvgi** [PrestaShop/PrestaShop#13805] opened 2019-05-15 16:59 UTC
Hello,

I'm having an issue in my back-office. When i want to edit the shipping of one order, I click on the Edit button but all I get is a scroll to the top of the page.
The link on the button is a #, which make sense then.

I can't choose carrier or add tracking number. Could this come from a misconfiguration on my carriers ? 

PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-05-16 08:38
Hi @jnvgi,

I manage to reproduce the issue with PS1.7.5.2.
https://drive.google.com/file/d/1ruTwdgvlRTuoj883lfnXOrWLQ1vteSp1/view
But it is fixed in the PS1.7.6.0beta1
https://drive.google.com/file/d/156wL2kuzlumBRIsAorf25mWAFjlGF04X/view
Since it is fixed, I close the issue
Feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-05-16 08:38 UTC
Labels: Bug, Minor, BO, Order, Carriers, Fixed, 1.7.5.1, 1.7.5.2
