### ISSUE TITLE
Price problem with multishop

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#11947] opened 2018-12-28 17:46 UTC
**Describe the bug**
If you modify something in a product (weight for example), the price of this product is changed for the same price for all shops.

**To Reproduce**
1 : select "shop 1" in the shop list 
2 : Go to catalog, product : open a product
3 : set the price to 10, save and go back to catalog
4 : select shop 2 
5 : open the product and set the price to 20
At this point, you can check that everything is ok : price of the product is 10 in shop 1, 20 in shop 2
6 : select "all shops" in the shop list
7 open the product and modify the weight 
Go back and check : price of the product is 10 in both shops.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-12-31 10:16
Hi @elmanu13,

We manage to reproduce the issue.
Your ticket is a duplicate of #9833
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-02 08:13
Duplicate of #9833

**Closed as completed** 2019-01-02 08:30 UTC
Labels: Duplicate, Multistore, Taxes and Prices
