### ISSUE TITLE
Child theme upload not working

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#18047] opened 2020-03-09 09:36 UTC
## Describe the bug
The child theme uploading doesn't work

#### Expected behavior

The child theme should be uploaded
![upload child theme expected result](https://user-images.githubusercontent.com/40635814/76200022-2e4c8200-61f1-11ea-9719-0c31ec6cd35d.png)

#### Steps to Reproduce

1. Go to BO => design => theme and logo => advanced customization
2. Click on "upload child" theme
3. try to drop a zip file ( no effect ) or select a file manualy (no effect )

https://drive.google.com/file/d/1uPwcrD1-_it7iL30XBbx4BOYcJ7JcTU4/view

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-03-09 09:53
Hi @SD1982,

Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/16511
Here's the PR: https://github.com/PrestaShop/ps_themecusto/pull/19 to fix the issue.
A new release of the module ps_themecusto is not released yet.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-09 10:03
Duplicate of #16511

**Closed as completed by khouloudbelguith** 2020-03-09 10:03 UTC
Labels: Bug, BO, Duplicate, Design, Regression, Modules & Themes, 1.7.7.x
