### ISSUE TITLE
"An error occurred while processing your request" When you change combinations of a product

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18589] opened 2020-04-11 12:50 UTC
#### Describe the bug

when you change combinations of a product on a screen less than 991px, it shows me the error.
attached video: https://www.youtube.com/watch?v=9c-ib3ew-UQ

also an error is shown in the chrome console: https://imgur.com/a/m9e1JEj

#### Expected behavior

no error should be displayed

#### Steps to Reproduce

991px smaller screen
1. Go to go to a product with combinations
2. Click on a different combination than the default
3. See error

**Screenshots**

Video: https://www.youtube.com/watch?v=9c-ib3ew-UQ
Console: https://imgur.com/a/m9e1JEj

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29
Información del servidor Linux #1 SMP Wed May 23 10:04:13 MSK 2018 x86_64
Versión del software del servidor: Apache

**Comment by sarahdib** [comment] 2020-04-14 14:06
Hello @alfonsolr09 

I didn't reproduce using the classic theme : https://drive.google.com/file/d/1W4faC7_HSZ9sHqnTlF_tmicIWSpr-WUL/view

Can you try to contact the theme developer in order to check what is wrong and feedback us ?

Thank you

**Comment by alfonsolr09** [comment] 2020-04-14 16:35
in the end it's for my template.
when on the page of a product I have activated the left column and a module of the template that I bought, this error occurs. The solution that the vendor gave me by prestashop addons is to deactivate the module ... a solution that doesn't seem right to me since I wanted to show that module there

**Comment by sarahdib** [comment] 2020-04-15 16:29
@alfonsolr09 

I'm sorry we can not reproduce the problem since is related to a third part module. You need to contact PrestaShop addons team.

 I'll close this issue.

**Closed as completed by sarahdib** 2020-04-15 16:29 UTC
Labels: FO, Can't reproduce, Combinations
