### ISSUE TITLE
Bug by Category rule discount  saved to home category instead of chosen category

### ISSUE THREAD

**Issue by nossanhendel** [PrestaShop/PrestaShop#24928] opened 2021-06-11 14:42 UTC
#### Describe the bug**

when i make a discount of 2 different categories and save them it works well. But if I open the rule of the discount instead of the categories I chose the role change to the home category that this is the first one in the list, and when I save again it really makes a discount on the whole store that on home category. 
by brand CONDITIONS is the same problem
#### Expected behavior

to have stay save the same categories I choose to have the discount on.

#### Steps to Reproduce

1. **Go to**  'Discounts >  Catalog Price Rules.'
2. **Click on** Add new catalog price rule
3. Scroll down to CONDITIONS
4. See error on any CONDITIONS I choose it will not stay my choice it will be the first one in the list 

**Screenshots**

http://somup.com/cr1oFUqptM 

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.27

**Comment by florine2623** [comment] 2021-06-11 15:09
Hello @nossanhendel ,

Could you follow the Bug template and share the steps to reproduce your bug please ?

Thanks!

**Comment by nossanhendel** [comment] 2021-06-11 16:04
Catalog > Discounts >  Catalog Price Rules > CONDITION GROUP 
Any category I will choose will be saved and will work.
But when I will open it again to edit all conditions category will be home and if I save it all site will get the discount.
I have akira theme

**Comment by hibatallahAouadni** [comment] 2021-06-15 14:34
Hello @nossanhendel 

Could you please edit your issue following the provided template:

![image](https://user-images.githubusercontent.com/23308427/122071905-6c265600-cdf7-11eb-82e3-bd0f4ccd9810.png)

We provide this template and these blocks cause we need it to reproduce the issue.
So please edit your issue description and notify me :pray: 

Thanks!

**Comment by nossanhendel** [comment] 2021-06-15 18:30
**#### Describe the bug**

when i make a discount of 2 different categories and save them it works well. But if I open the rule of the discount instead of the categories I chose the role change to the home category that this is the first one in the list, and when I save again it really makes a discount on the whole store that on home category. 
by brand CONDITIONS is the same problem
#### Expected behavior

to have stay save the same categories I choose to have the discount on.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. **Go to**  'Discounts >  Catalog Price Rules.'
2. **Click on** Add new catalog price rule
3. Scroll down to CONDITIONS
4. See error on any CONDITIONS I choose it will not stay my choice it will be the first one in the list 

**Screenshots**

http://somup.com/cr1oFUqptM 

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.27

**Comment by florine2623** [comment] 2021-06-22 13:15
Hello @nossanhendel ,

I can't reproduce your issue in PS 1.7.7.X.
Please check my screen record :
https://drive.google.com/file/d/1UJtsrcrpvstzzbFgMPfOp8c5FoyJiQKM/view

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-12 08:27
Hello @nossanhendel 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-07-12 08:27 UTC
Labels: Bug, BO, Discounts, Catalog price rules, No change required, 1.7.7.4
