### ISSUE TITLE
How to resend a new order notification to the seller? (ps_emailalerts module)

### ISSUE THREAD

**Issue by kerstar** [PrestaShop/PrestaShop#19479] opened 2020-05-31 12:47 UTC
Hello,

I have a minor problem.

Due to a failure on the mail server side, notifications of new orders could not be sent.
The mail server crash has been fixed and I thought that I would simply be able to manually resend the seller about new orders, but I don't see this option anywhere.

How do I resend a new order notification to the seller?

Can anyone tell me what code and where to add, so as to add a button on the order card to resend the notification to the seller for a given order?

Regards,

#### Additional information

* PrestaShop version: 1.7.6.5
*ps_emailalerts v2.1.1

**Comment by jolelievre** [comment] 2020-06-01 15:34
Hello @kerstar 

Thank you for this feedback, I would need a bit more details:

When you talk about the "seller" do you mean the merchant admin (whose emails are defined in the module configuration?).

Regarding your question the mail alert is sent when the payment is validated, so if the email was not sent at this point there is no system to resend them in the module. These are mail "alerts" so mail are sent on the fly when an action occurs, there is no queue nor retry system.

There is another alert that you might take advantage of, when an order is updated an email is sent so if you edit an order an email will be sent. Although the content won't be the same since the information is only that the order has changed.

About your question regarding the code used to send that validation order you can inspire from the module's code itself: https://github.com/PrestaShop/ps_emailalerts/blob/dadce9e048d0be19a6097dc74fb4b7b3393ce159/ps_emailalerts.php#L256

I hope these informations will help you. The feature you request is implemented by the module today, I don't know if it should since it's not strictly the scope of this module. This should be discussed with the @PrestaShop/prestashop-product-team to see if the feature could/should be added to the module.

**Comment by kerstar** [comment] 2020-06-01 20:27
Hello @jolelievre 

Thank you for your answer to my problem.

Yes, by "seller" I meant emails that are defined in the module settings.

My problem is that in the settings of this module an email is given to a person who does not log in to Prestashop, but supports the processing of new orders that came in the email.

At woocomerce it is so that if the person who carries out the order did not receive an e-mail about a new order (due to a breakdown or other factors), then as a store administrator I check the store once a day and if I see an e-mail about a new order did not reach the person who supports the execution of orders, I can click the "Resend information about a new order" button and this person receives information by e-mail about the new order.

Here at Prestashop in this module, if there is any failure in the way of email communication, I can not send an email again to the person who supports the implementation of new orders.

Do you understand what I mean?

It seems that I have to go to the "Orders" tab, enter a new order, click the "Print order" button, print to a PDF file, and then manually send this PDF file with the order details by email to the person who supports the implementation new orders.

Do you understand what I mean?

In the "Orders" tab, after clicking on an order there is a "Resend Email" button - this function is a standard feature in Prestashop that allows you to resend an email to the customer.

Unfortunately, it is not possible (as you mentioned) to resend the message to the "seller" (the person whose email address is assigned in the settings of the ps_emailalerts module).

Adding such a function manually is a complex matter?
Just put the "hookActionValidateOrder" function from the ps_emailalerts.php file somewhere in the "Orders" tab? If this is not complicated, could you please suggest a few lines of code together with information on where exactly to put it?

By the way, I noticed another problem regarding the email template informing the seller (the person who the email is set in the ps_emailalerts module) about the new order:

I edited two files:
/modules/ps_emailalerts/mails/pl/new_order.html

and

/themes/my_theme/mails/modules/ps_emailalerts/mails/pl/new_order.html

and then clicked "Generate emails" in Prestashop, where I provided the name of the template used and the language.
I cleared the cache, but emails with the old template still come in, and the files I edited were:

/modules/ps_emailalerts/mails/pl/new_order.html
and
/themes/my_theme/mails/modules/ps_emailalerts/mails/pl/new_order.html

were overwritten with an old template.

Do you know the solution to my two problems?

**Comment by florine2623** [comment] 2020-06-05 13:13
HI @kerstar ,

You would like to see a new feature in the module email-alert that allows you to resend emails to yourself, is that right ?
For example, a new button would be added here, so that you can resend emails to yourself + any contact that you add in the "email addresses" section, is that right ?
![Capture d’écran 2020-06-05 à 15 11 04](https://user-images.githubusercontent.com/16019289/83880131-052f8500-a73f-11ea-9d82-0f916f35d458.png)

**Comment by kerstar** [comment] 2020-06-06 14:10
Hi @florine2623 

It is worth adding a feature that allows you to resend messages to people whose emails are defined in the ps_emailalerts module configuration.

You mentioned this function in the "ps_emailalerts" module settings.
Just how do you send a notification for a specific order instead of all orders?
There would have to be a field in which you must enter the id order number and then the "Resend new order e-mail" button.
That would be a perfect solution!

Can you help me with this?

**Comment by florine2623** [comment] 2020-06-08 11:50
Hi @PrestaShop/prestashop-product-team ,

The user would like to see 2 new feature in the module ps_emailalerts :

"As a merchant, I would like to be able to use module ps_emailalerts to resend emails as I wish.
There are 2 features that I would like to see :
1) Have a button "Resend email" in the "New order" section
2) Have a field where I can choose the exact order so that the email is sent again for that order specifically."

Do you think this is relevant ?
Thanks!

**Comment by Hlavtox** [comment] 2021-02-17 15:45
@florine2623 @jolelievre @kerstar 

Hi guys, we already started a topic, can you merge it? :-)

Also, @kerstar, you can use my code to resend your order confirmation. 🍺 https://github.com/PrestaShop/PrestaShop/issues/14754#issuecomment-623364507

**Comment by hibatallahAouadni** [comment] 2021-03-24 11:34
Hello @kerstar 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #14754. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: Thanks @Hlavtox for the tip :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-24 11:34
Duplicate of #14754

**Closed as completed by hibatallahAouadni** 2021-03-24 11:34 UTC
Labels: Improvement, BO, Duplicate, Order, ps_emailalerts
