### ISSUE TITLE
Multistore selection dropdown hidden in product screen (symfony pages I expect)

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#12028] opened 2019-01-04 13:59 UTC
**Describe the bug**
When multistore enabled, store selection downdown is hidden by navigation bar in new symfony product screen.

**To Reproduce**
1. Configure multistore
2. Open product page
3. Try to select the all store context
4. It be hidden

There's some css voodoo going on here, changing the z-index of the multistore dropdown doesn't seem to change anything.  It seems to be an issue between the 'fixed' nav bar, and the 'absolute' multistore dropdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/19314911/50691474-ce5fb780-0ffe-11e9-9865-deba9c3ece32.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-01-04 14:17
Hi @roja45,
This issue occurs previously in the PS1.7.5.0Beta1, but it is fixed in the last stable release PS1.7.5.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11486 to solve the issue.
Your ticket is a duplicate of #11042
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-04 14:17
Duplicate of #11042

**Closed as completed by khouloudbelguith** 2019-01-04 14:17 UTC
Labels: Duplicate

**Comment by roja45** [comment] 2019-01-04 16:04
Except that I am using the last stable release of 1.7.5.0?

**Comment by khouloudbelguith** [comment] 2019-01-04 16:13
@roja45, I did not manage to reproduce the issue with PS1.7.5. stable version.
![image](https://user-images.githubusercontent.com/16067358/50697958-03dac400-1044-11e9-90c9-6acb11b01d84.png)
Did you download your PrestaShop Project from which link?
Thanks!

**Comment by roja45** [comment] 2019-01-04 16:46
it was an upgrade from 1.7.4.x, not a fresh install

**Comment by khouloudbelguith** [comment] 2019-01-04 16:53
Hi @roja45,

In my case, it is OK after upgrade from PS1.7.4 to PS1.7.5.0.
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You need also to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
