### ISSUE TITLE
In payment preferences, not all carriers are displayed

### ISSUE THREAD

**Issue by Jeremy-VERNET** [PrestaShop/PrestaShop#21634] opened 2020-10-27 11:24 UTC
#### Describe the bug

If you add two carriers with the same name, only one of the two will be displayed in the carrier payment preferences.

This causes problems in the display of payment options. For exemple, I had two carriers : FedEx (International Priority noted in delay field) and FedEx (International Economy noted in delay field). I noticed that foreign customers for whom the first carrier should be displayed did not see the payment module at all.

#### Expected behavior

Activated carriers should display by ID and not by Unique Name.

Otherwise, it should not allow the addition of a carrier if another with the same name exists. Or, at least, it should display a warning.

#### Steps to Reproduce

1. Add two carriers with the same name.
2. Go to Preferences -> Payment
3. At the bottom of the page, you will notice that only one in two carriers is displayed.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.1

**Comment by SimonGrn** [comment] 2020-10-27 12:49
Hello @Jeremy-VERNET 
Thank you for your issue. This is a duplicate of #16094.
This is fixed in the next version of PrestaShop to come. You'll be able to upgrade when it comes out in a few weeks.

I close this issue.

Thank you

**Comment by SimonGrn** [comment] 2020-10-27 12:49
Duplicate of #16094

**Closed as completed by SimonGrn** 2020-10-27 12:49 UTC
Labels: Duplicate
