### ISSUE TITLE
Wrong shipping cost in order details

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#29448] opened 2022-08-26 07:55 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Order details have two tables where shipping cost is shown. One is showing a correct shipping cost, the other one is showinng incorrect shipping cost (tax excluded while it should be tax included and vice versa).
![2022-08-26 09_53_18-1 7 8 Dev — Firefox Developer Edition](https://user-images.githubusercontent.com/5658940/186852007-fac4dac2-49bb-4565-8bd3-75d13cbb5ad7.png)
![2022-08-26 09_53_32-1 7 8 Dev — Firefox Developer Edition](https://user-images.githubusercontent.com/5658940/186852018-adb67dff-355e-4653-b355-27afde1745c0.png)

### Expected behavior

Shipping cost should be the same in both places

### Steps to reproduce

1. Go to order details for any order having a non-free shipping cost
2. Compare values displayed in both tables.

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by hibatallahAouadni** [comment] 2022-08-26 16:51
Hello @daresh 

It's not a bug! that's the wanted behavior:

![image](https://user-images.githubusercontent.com/23308427/186954076-b5dca652-4fef-4a06-b57f-f2be4b42f4d8.png)

Closing the issue!

Thanks!

**Closed as completed by hibatallahAouadni** 2022-08-26 16:51 UTC
Labels: Bug, Duplicate, Invalid

**Comment by daresh** [comment] 2022-08-26 18:28
@hibatallahAouadni are you kidding me? In what country end customers want to see shipping cost without tax?

**Comment by kpodemski** [comment] 2022-08-26 19:50
Are you sure @hibatallahAouadni? It really looks like a bug. There's no tax label, there's no indication which price is which.

**Comment by hibatallahAouadni** [comment] 2022-08-29 09:13
Duplicate of #19132
