### ISSUE TITLE
Bug on Mininum Order

### ISSUE THREAD

**Issue by Felkio** [PrestaShop/PrestaShop#10773] opened 2018-09-29 13:11 UTC
**The bug and how to reproduce**
I set to 10 the "Mininum Quantity for selling" for a product. When I add that product in the cart the standard quantity is 10, and it's fine, but if I click on the left arrow to decrease the quantity I can see that it become "9" and then return to "10", but actually the quantity is decreased to 9. If I complete the check-out I pay for 9 products and not 10.

**Screenshots**
![cattura3](https://user-images.githubusercontent.com/26347731/46246186-c5f15280-c3f9-11e8-9337-738dd7c6a47e.PNG)
![cattura](https://user-images.githubusercontent.com/26347731/46246187-c5f15280-c3f9-11e8-9d27-397f701a4e51.PNG)
![cattura2](https://user-images.githubusercontent.com/26347731/46246185-c5f15280-c3f9-11e8-8725-a600ea7ded9c.PNG)

**Additionnal information**
PrestaShop version: 1.7.3.2
PHP version: 7.0.31

**Comment by khouloudbelguith** [comment] 2018-10-01 09:08
Hi @Felkio,

We manage to reproduce the issue.
Here's the PR: #10279 to solve the issue
Your ticket is a duplicate of #10162
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 09:08
Duplicate of #10162

**Closed as completed by khouloudbelguith** 2018-10-01 09:08 UTC
Labels: Duplicate
