### ISSUE TITLE
Bad SQL query when ordering stores alphabetically

### ISSUE THREAD

**Issue by hellodracon** [PrestaShop/PrestaShop#10755] opened 2018-09-28 17:27 UTC
**Describe the bug**
I got this message when trying to order stores in contact by alphabetical order : 
_Bad SQL query - Unknown column 'a.name' in 'order clause'_

**To Reproduce**
1. Go to Shop parameters > Contact > Click on Store tab
2. Click on an arrow to order the stores by alphabetical order
3. See error

**Screenshots**
<img width="1224" alt="par defaut 2018-09-28 a 13 21 52" src="https://user-images.githubusercontent.com/5995162/46223648-ed74ec00-c321-11e8-8907-f9e25ff763ee.png">

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.30

**Comment by khouloudbelguith** [comment] 2018-10-01 07:40
Hi @hellodracon,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9704
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-10-01 07:40
Duplicate of #9704

**Closed as completed by khouloudbelguith** 2018-10-01 07:40 UTC
Labels: Duplicate

**Comment by cld00clr** [comment] 2020-10-08 11:47
Hello.  I have this same problem.  Yesterday, Oct. 7, 2020 I tried to order my stores by name and I received this same error:
Bad SQL query
Unknown column 'a.name' in 'order clause

I am using Prestashop Version 1.7.4
Now I can no longer access my list of stores in order to edit them in the back office.  Could you please let me know what I need to do in order to access them?
Thank you

**Comment by kpodemski** [comment] 2020-10-08 11:49
You can try to clear your cookies @cld00clr

**Comment by cld00clr** [comment] 2020-10-08 11:55
🙂  Yes, thank you.  That was exactly it.  Thank you for your quick response and for being patient with my silly question.

sincerely,
Christa

________________________________
