### ISSUE TITLE
CartRule Still Work after  has expired or been deactivated

### ISSUE THREAD

**Issue by openpresta** [PrestaShop/PrestaShop#35391] opened 2024-02-16 14:58 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The CartRule still functions even after it has expired or been deactivated.

When a customer adds a coupon to their cart, if it is deactivated by the admin or has expired, the discount code continues to work seamlessly in the front office.

### Steps to reproduce

Create a coupon using CartRule, named XXX.
From the front end, a customer creates an account, adds items to their cart, and applies the coupon XXX.
From the admin panel, deactivate the CartRule associated with the coupon XXX, or allow its expiration date to pass.
Return to the front end, and observe that the CartRule associated with the coupon XXX still functions properly, applying the discount as expected.

### PrestaShop version(s) where the bug happened

8.1.3 

### PHP version(s) where the bug happened

8.2

**Comment by Hlavtox** [comment] 2024-02-19 08:58
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19393, https://github.com/PrestaShop/PrestaShop/issues/32303 https://github.com/PrestaShop/PrestaShop/issues/23933 and others.

**Closed as completed by Hlavtox** 2024-02-19 08:58 UTC
Labels: Bug, Duplicate, Invalid
