### ISSUE TITLE
PS 1.7 BO Product-list show final price

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#14493] opened 2019-07-04 16:54 UTC
Hi, after upgrading from 1.6 to 1.7, in BO -> Product-list, I only have 1 price column which shows the value "form_step2_price". I'd like instead to have the final public price that customers can see in the FO with all possible discounts included.
In short, employees must be able to see the final price in the product-list page. Right now they must open product page, copy the FO url of the product and open it in another tab so they can see the final price in order to communicate it to a customer.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-05 07:39
Hi @omar2886,

This improvement is added to PS1.7.6.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11484 to add this feature.
Your ticket is a duplicate of #11479
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-05 07:39
Duplicate of #11479

**Closed as completed by khouloudbelguith** 2019-07-05 07:39 UTC
Labels: Duplicate

**Comment by omar2886** [comment] 2019-07-06 10:35
Sorry I still didn't get it, I followed steps as far as I could understand here #11484,, so I:
- changed src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/list.html.twig
- Added 59-61 lines on src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/products_table.html.twig
Don't really know how to modify the other part and also don't get the sens of doing so
- The third file I just don't find that path.
With only these modifications I did I don't nee any changes in BO. It's my first time on GitHub, everything seem to me very difficult at this moment, I still don't get how this platform works, sorry

**Comment by khouloudbelguith** [comment] 2019-07-08 12:40
@omar2886, the third file is an E2E test file, you don't need to fix it.
We use those test files to run an automated test on PrestaShop to detect bugs.
Thanks!

**Comment by omar2886** [comment] 2019-07-08 12:56
I added these lines to this file: src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/list.html.twig
`        <td class="text-center">
            <a href="{{ product.url|default('') }}#tab-step2">{{ product.price_final|default('N/A'|trans({}, 'Admin.Global')) }}</a>
        </td>`

I added these lines to this file:
src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/products_table.html.twig
`          <th scope="col" class="text-center" style="width: 9%">
            {{ ps.sortable_column_header("Price (tax incl.)"|trans({}, 'Admin.Catalog.Feature'), 'price', orderBy, sortOrder) }}
          </th>

          {% if 'PS_STOCK_MANAGEMENT'|configuration %}
          <th scope="col" class="text-center" style="width: 9%">
@@ -129,7 +132,7 @@
              'value': filter_column_price,
            } %}
          </th>

          <th class="text-center"></th>`

But there were no changes in BO product-list, I still have just 1 column price (not the one I want).

Thanks for the help!

**Comment by khouloudbelguith** [comment] 2019-07-08 15:53
Hi @omar2886,

In my case, I edited those files https://github.com/PrestaShop/PrestaShop/pull/11484/files & the price tax included is well displayed.
![image](https://user-images.githubusercontent.com/16067358/60824052-d6acd100-a1a0-11e9-8ba6-a6b5a5e30d31.png)
Try to replace your files by this:
[files.zip](https://github.com/PrestaShop/PrestaShop/files/3369182/files.zip)

Thanks!

**Comment by omar2886** [comment] 2019-07-08 16:04
I replaced them with yours and nothing happened as well. Could it be a cache issue? normally not if I'm not mistaken.
Sorry for all this questions, you seem to be the only one answering and actually being so reactive, thanks!

**Comment by khouloudbelguith** [comment] 2019-07-09 08:12
@omar2886, you are welcome!
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Try to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

Thanks!

**Comment by omar2886** [comment] 2019-07-09 09:46
Thanks @khouloudbelguith it was indeed a cache thing!!

**Comment by Raply** [comment] 2019-08-14 20:53
The price column with tax included is shown but not including discounts

**Comment by omar2886** [comment] 2019-08-15 09:54
@Raply not for me, it appears with discount included. maybe the discount you have in that product has expired
