### ISSUE TITLE
WYSIWYG text editor changing code after save

### ISSUE THREAD

**Issue by naps1saps** [PrestaShop/PrestaShop#12322] opened 2019-01-27 07:42 UTC
v1.7.4.0
In Design>Pages customization
If I add a YouTube video iframe in the format given by YouTube which includes customization options, the options get stripped from the code after saving.  As such it is impossible to get the YouTube video to go full screen because the option gets stripped from the code.

Maintenance mode editor
If I try adding a link, the link code gets stripped and the visible text added to the paragraph brackets.

I feel like these things are done on purpose.  Please fix.  It is very very annoying and I see no purposeful reason for it.

**Comment by khouloudbelguith** [comment] 2019-01-28 10:46
Hi @naps1saps,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1j1pzIDqKWiCiVHBuqy_3yarvzfKWMMAp/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-02-27 07:13
Hi @naps1saps,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-02-27 07:13 UTC
Labels: BO, 1.7.4.0, Pages, No change required
