### ISSUE TITLE
Prestashop 1.7.6.1 clear cache button not clean var/cache/prod/translations/ folder

### ISSUE THREAD

**Issue by tarasklymets** [PrestaShop/PrestaShop#19978] opened 2020-06-29 07:12 UTC
#### Describe the bug

I found that clear cache button not clean folder var/cache/prod/translations/
Its not permission error.

Also file messages.ru-RU.xlf some how override module translations.
I have module amazzingfilter with text: {l s='Filter by' mod='amazzingfilter'} But translation dont work, this code from messages.ru-RU.xlf override module translation:

  <file original="admin-dev/themes/default/template/controllers/modules/filters.tpl" source-language="en" target-language="ru" datatype="plaintext">
    <body>
      <trans-unit id="1f0e9c979b965d24aa3c2c4b832c3ba1" approved="yes">
        <source>Filter by</source>
        <target state="translated">Фильтр:</target>
        <note>Line: 31</note>
      </trans-unit>
</body>
</file>

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.2.31

**Comment by Progi1984** [comment] 2020-06-29 07:58
Hi @tarasklymets 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).Thank you!

**Comment by florine2623** [comment] 2020-07-23 10:17
Hi @tarasklymets ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2020-07-23 10:17 UTC
Labels: No change required, 1.7.6.1
