### ISSUE TITLE
Bug translation system. Non-translatable strings in Bankwire module.

### ISSUE THREAD

**Issue by jesusruiz** [PrestaShop/PrestaShop#10490] opened 2018-09-19 13:53 UTC
**Describe the bug**
**In the Spanish language**: When making a payment by bank transfer, and the client receives on the screen the details of the transfer, these details are shown in English.

I think there is an error in the translation system that affects the strings that are in the file: **ps_wirepayment\views\templates\hook\payment_return.tpl**

I have also verified that these strings aren't translatable using the _ps_livetranslation_ module

**To Reproduce**
Make a purchase and pay by bank transfer.

**Screenshots**
![translation-bug-wirepayment](https://user-images.githubusercontent.com/1318254/45757599-13183c00-bc24-11e8-9250-87006e3ef13e.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.9

**Comment by khouloudbelguith** [comment] 2018-09-19 14:01
Hi @jesusruiz,

This issue should be fixed in this ticket: #9697
Some strings in some module don't exist.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-19 14:01
Duplicate of #9697

**Closed as completed by khouloudbelguith** 2018-09-19 14:01 UTC
Labels: Duplicate
