### ISSUE TITLE
Email Templates Manager error 500

### ISSUE THREAD

**Issue by JeromeOnyx** [PrestaShop/PrestaShop#33896] opened 2023-09-10 17:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I'm contacting you today because I have a bug in the Email Template Manager module. 
When I click on it, I get an error code of 500.

### Expected behavior

Je souhaitais pouvoir configurer les templates des mails envoyés

### Steps to reproduce

1 go to modules 
2 choose module manager 
3 search for Email Template Manager 
4 click on configure

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.23

### If your bug is related to a module, specify its name and its version

Email Templates Manager

**Comment by sallemiines** [comment] 2023-09-11 10:23
Hello @JeromeOnyx

It seems that your issue is not a PrestaShop core bug.
If your module is Email Templates Manager Official, please contact support team on Addons.

We will close this issue.

Thank you

**Comment by sallemiines** [comment] 2023-09-11 10:23
Duplicate of #33884

**Closed as completed by sallemiines** 2023-09-11 10:23 UTC
Labels: Bug, Duplicate
