### ISSUE TITLE
Problem with carrier group

### ISSUE THREAD

**Issue by caro43** [PrestaShop/PrestaShop#23185] opened 2021-02-09 08:20 UTC
Hello,

#### Describe the bug

I encounter an error, I have a product with a "Client" group transport and a product with a "Pro" group transport in my cart, when choosing the delivery, only one choice available without a title, and the carrier's price of the product group "Client"

#### Expected behavior

I should not have any carrier available because the products in the cart are not compatible

#### Steps to Reproduce

1. Create a group "Pro"
2. Create a carrier "My carrier" with group "Client"
3. Create a carrier "TFE" with group "Pro"
4. Create an account "Customer" - Login
5. Create a product "product A" with carrier "My Carrier"
6. Create a product "product B" with carrier "TFE"
7. Add products "product A" and "product B" to cart with account customer
8. Go to Cart in carrier choice
9. See error : Carrier "My carrier" appear

Step 2
![image](https://user-images.githubusercontent.com/47216082/107369855-8ca97100-6ae2-11eb-8fb2-0e660b890198.png)

Step 3
![image](https://user-images.githubusercontent.com/47216082/107369921-9d59e700-6ae2-11eb-9801-c92bac1f4382.png)

Step 9
![image](https://user-images.githubusercontent.com/47216082/107369738-6e437580-6ae2-11eb-8fe6-276f9665d039.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-09 08:46
Hello @caro43 ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- steps to reproduce
- PHP version
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by caro43** [comment] 2021-02-09 09:22
PHP 7.2

Add a product with all transport (transport group "Customer" and group "Pro")
Add a product with transport group "Pro"

![image](https://user-images.githubusercontent.com/47216082/107342544-9d48ef80-6ac0-11eb-8427-70f28cef9ab8.png)

**Comment by hibatallahAouadni** [comment] 2021-02-09 11:37
Hello @caro43 

It seems this issue is your first issue. So, when you clicked on the button **new issue** we already provided a **template to submit a complete bug report**, you should respect and fill the blocks (steps to reproduce, expected behavior, describe the bug, additional infos, ...).

When I asked from these infos, you should edit your issue description and not just add some infos in comment :wink: 

> Add a product with all transport (transport group "Customer" and group "Pro")
Add a product with transport group "Pro"

You should explain more, for exemple group "Pro": you need to mention that I have to create a new group customer named Pro with certain parameters (and you should mention these parameters).

For the screenshot, you should circle around where the issue is displayed, and please explain what's the problem.

Thanks!

**Comment by caro43** [comment] 2021-02-09 13:29
ok sorry @hibatallahAouadni , i modified my issue

**Comment by hibatallahAouadni** [comment] 2021-02-11 08:28
Hello @caro43 

Could you please check this issue #15369 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-03 15:17
Hello @caro43 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-03 15:17 UTC
Labels: Bug, FO, Carriers, Customer groups, No change required, Checkout, 1.7.6.7
