### ISSUE TITLE
ContextErrorException in PrestaShop 1.7.6.0 when signing up for a new Customer account

### ISSUE THREAD

**Issue by ekomot** [PrestaShop/PrestaShop#15633] opened 2019-09-20 14:08 UTC
Hello,
Currently building up www.ekomot.ro based on the PrestaShop 1.7.6.0 platform. Just noticed that when a customer tries to create a new account, after completeting and submitting the sign up form the customer receives an error screen (ContextErrorException) despite the fact the account is actually created. 

**To Reproduce**
1. Go to 'www.ekomot.ro'
2. Click on 'https://ekomot.ro/index.php?controller=authentication&create_account=1'
3. Introduce your credential to create an account and submit

**Screenshots**
![image](https://user-images.githubusercontent.com/55546136/65333030-6838b600-dbc8-11e9-8324-c23686230324.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0.33
PrestaShop version: 1.7.6.0

Shop URL: https://ekomot.ro/

Shop path: /home/ekomot/public_html

**Comment by matks** [comment] 2019-09-20 14:12
@ekomot The error `escapeshellcmd() has been disabled for security reasons` is due to your local PHP config, not PrestaShop.

Functions can be disabled for any reason, security being a common one. escapeshellcmd has a number of serious potential issues, so it looks like it's been turned off for you, causing this error. 

See https://github.com/PHPMailer/PHPMailer/issues/966 for workarounds

**Comment by ekomot** [comment] 2019-09-20 15:40
Thank you Mathieu. I have discussed with our hosting provider who had confirmed the escapeshellcmd is indeed disabled. He also has enabled it for us and then tried to create an account on ekomot.ro. The site has returned the following error, even with escapeshellcmd active:

(1/1) ContextErrorException

Warning: escapeshellcmd() has been disabled for security reasons

 

in MailTransport.php line 259

at Swift_Transport_MailTransport->_isShellSafe('office@motounelte.ro')

in MailTransport.php line 288

at Swift_Transport_MailTransport->_formatExtraParams('-f%s', 'office@motounelte.ro')

in MailTransport.php line 176

at Swift_Transport_MailTransport->send(object(Swift_Message), array())

in Mailer.php line 85

at Swift_Mailer->send(object(Swift_Message))

in Mail.php line 593

at MailCore::send(2, 'account', '[Ekomot] Bine ai venit!', array('{firstname}' => 'Costelo', '{lastname}' => 'Costicar', '{email}' => 'asistenta@clausweb.ro', '{shop_logo}' => 'cid:092d3ae031c2791ae88eaff0331442bc@ekomot.ro', '{shop_name}' => 'Ekomot', '{shop_url}' => 'https://ekomot.ro/index.php', '{my_account_url}' => 'https://ekomot.ro/index.php?controller=my-account', '{guest_tracking_url}' => 'https://ekomot.ro/index.php?controller=guest-tracking', '{history_url}' => 'https://ekomot.ro/index.php?controller=history', '{color}' => '#db3484'), 'asistenta@clausweb.ro', 'Costelo Costicar')

in CustomerPersister.php line 229

at CustomerPersisterCore->sendConfirmationMail(object(Customer))

in CustomerPersister.php line 200

at CustomerPersisterCore->create(object(Customer), 'dasdssdae21321321')

in CustomerPersister.php line 59

at CustomerPersisterCore->save(object(Customer), 'dasdssdae21321321', null, true)

in CustomerForm.php line 196

at CustomerFormCore->submit()

in AuthController.php line 60

at AuthControllerCore->initContent()

in Controller.php line 291

at ControllerCore->run()

in Dispatcher.php line 515

at DispatcherCore->dispatch()

in index.php line 28

 

After going through “See PHPMailer/PHPMailer#966 <https://github.com/PHPMailer/PHPMailer/issues/966>  for workarounds” topic I changed in the site’s email settings from using php to using smtp and the error has disappeared and the site is now sending emails.

Many thanks,

mugur

**Comment by khouloudbelguith** [comment] 2019-09-20 15:45
Hi @ekomot,

I tried with your shop & it is OK now
https://drive.google.com/file/d/1fSVfNtOt66_-ZXYErHuo_B35aOko0cF1/view

Thanks to check & feedback.

**Comment by ekomot** [comment] 2019-09-20 17:35
Hi,
Indeed it is working as I changed the email settings from php to smtp. Using php was generating the error even after the hosting provider has changed the security settings.
Many thanks

**Comment by matks** [comment] 2019-09-20 19:50
> Using php was generating the error even after the hosting provider has changed the security settings. Many thanks

I'm happy to see it's now solved, but it's really strange that the hosting provider has changed it ... but php is still generating this error 😅you might want to double-check that. To err is human, the hosting provider might have changed the wrong configuration file 😉or maybe he need to restart the server after the modification, to make sure changes are acknowledged.

Anyway, I think we can close this issue now as the issue is solved. Have a nice day !

**Closed as completed by matks** 2019-09-20 19:50 UTC
Labels: FO, Customer, No change required, 1.7.6.0

**Comment by ekomot** [comment] 2019-09-21 04:04
Good morning,
Will check again for sure. What was strange was also the fact that whilst generating the error on the sign up page with the command shel disabled the site was sending emails ok from the orders menu, like changing the status of an order the info email to the consumer was sent ok. Anyway...now I noticed another problem...on mobile the site is not listing any product like the categories would be empty :) Now struggling with this one 
Best,
mugur

**Comment by khouloudbelguith** [comment] 2019-09-23 10:45
@ekomot, This issue is currently closed & different, can you open a new one with more information about your configuration
