### ISSUE TITLE
BO product combination list has different order of attributes

### ISSUE THREAD

**Issue by wzzly** [PrestaShop/PrestaShop#25027] opened 2021-06-18 12:33 UTC
#### Describe the bug

When visiting BO product page. Go to combinations tab. When you have different combinations with multiple attributes, the combination name contains the attributes in a different order. When working with multiple combinations with multiple attributes (but all combinations use the same attributes), this is very anoying for readability. 

#### Expected behavior

Combination name should use the same order for all attributes, defined by the order of the attributes on the attributes page.
So in example, should always be: Breedte, Uitzetting, Lengte

**Screenshots**

![image](https://user-images.githubusercontent.com/35727938/122561446-28735c80-d042-11eb-80e5-ce17c4672cf5.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-06-18 16:25
Hello @wzzly ,

That is already the case :
<img width="1410" alt="Screenshot 2021-06-18 at 18 23 24" src="https://user-images.githubusercontent.com/16019289/122590882-71d3a400-d062-11eb-8c70-3b553d766309.png">

I generated all the combination at one. Maybe you did it differently ?

Please check and feedback.
Thanks!

**Comment by wzzly** [comment] 2021-06-18 20:20
@florine2623 that's a coincidence I think, because when I did it with my attributes, it didn't have the good order and the order changed after some combinations. Could you try to make some more combinations (not only with size S)

**Comment by florine2623** [comment] 2021-06-22 12:26
Hello @wzzly ,
Please check my screen record :
https://drive.google.com/file/d/1vE0TTANp3f5EkHmuLqE2Fn0FdlnwHckz/view

I couldn't reproduce your issue.
Thanks!

**Comment by wzzly** [comment] 2021-06-22 13:36
@florine2623 I don't know how it is supposed to work, but please check my screen record:

https://user-images.githubusercontent.com/35727938/122934199-9d5ed300-d36f-11eb-9a59-8539f29e637d.mp4

**Comment by wzzly** [comment] 2021-06-22 13:46
@florine2623 I still think it's coincidence because check my screen record:

https://user-images.githubusercontent.com/35727938/122935876-fbd88100-d370-11eb-98d9-1cbf3bdfae1f.mp4

**Comment by florine2623** [comment] 2021-06-22 16:27
Hello @wzzly ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2021-06-22 16:27 UTC
Labels: Bug, BO, Can't reproduce, Combinations, 1.7.7.4

**Comment by wzzly** [comment] 2021-06-23 07:57
@florine2623 @hibatallahAouadni  

I know what the problem is and it is definitly a bug.

I checked the ID's of all the attributes on the attributes BO page.
The order of the attributes in the combination name are based on the ID's of the attributes.
For example in my case we added multiple attribute values to different attributes along the way. So the attributes values ID's are not in order.

Uitzetting - 10mm **(ID 1664)**, Breedte - 10mm **(ID 1669)**, Lengte - 12,5 meter **(ID 1673)**

and

Breedte - 15mm **(ID1661)**, Uitzetting - 10mm **(ID 1664)**, Lengte - 12,5 meter **(ID 1673)**

As you can see, the order is based on the ID-number, not on the order in the BO attributes page or BO attribues values page. Which in most cases isn't a problem when you add the attributes and values in the correct order, but when you add some values later on, this (ID)ordering is messed up.

So... it would be way more logical to use the order that you can set on the BO attributes page and BO attribute values page and NOT based on the ID-numbers itself.
So would you re-open please?
