### ISSUE TITLE
Declaration of Cart

### ISSUE THREAD

**Issue by shikotakcom** [PrestaShop/PrestaShop#25231] opened 2021-07-05 10:24 UTC
I upgrade the Prestashop some days ago and I got strange problems.
I change nothing but suddenly I got this error on back office and front office.

Declaration of Cart::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true) should be compatible with CartCore::getProducts($refresh = false, $id_product = false, $id_country = NULL, $fullInfos = true, bool $keepOrderPrices = false) in /home/shik/public_html/override/classes/Cart.php on line 0

I can not disable any module.
* PrestaShop version: 1.7.7.5
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-07-05 11:07
Hello @shikotakcom 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20332. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-07-05 11:07
Duplicate of #20332

**Closed as completed by hibatallahAouadni** 2021-07-05 11:07 UTC
Labels: Duplicate
