### ISSUE TITLE
email alert not working

### ISSUE THREAD

**Issue by djsmoye** [PrestaShop/PrestaShop#31649] opened 2023-03-04 21:11 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

despite the activation of an e-mail address intended to receive notifications of new orders, no message arrives. All status notifications work for clients but no administrator receives a message

![222714559-4402c4cb-114e-42e6-af86-d601696ed44d](https://user-images.githubusercontent.com/126320937/222928819-7ec67a16-e558-49d5-9da4-8656b8e01067.png)
![221540934-46659940-e27f-44cd-9db8-d3a32b5f4606](https://user-images.githubusercontent.com/126320937/222928821-21c97cde-22d6-43bb-9e9f-0b8d88089cc7.png)

### Expected behavior

Correct operation for a native module

### Steps to reproduce

Make a order
Admin wait for notification
Wait and wait...

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_emailalert 2.4.0

**Comment by Hlavtox** [comment] 2023-03-04 22:30
@djsmoye Hi, some questions:

- If you make an order in FO, do you receive the confirmation email?
- Do you have the mail logged in the E-mail section?
- If other emails work, can you try sending the notification to other mailbox from a different provider? Maybe gmail blocks it because you are on some spam list, no DKIM setup etc.

**Comment by djsmoye** [comment] 2023-03-05 08:36
Hi Daniel,

1: yes
2: yes after point 1
3: yes i have tested 5 other account 

Maybe a problem with leotheme?

**Comment by Hlavtox** [comment] 2023-03-05 18:58
@djsmoye Hi, thanks for the info. Regarding the point , do you have both `order_conf` (order confirmation to customer) and `new_order` (mailalerts notification to you) in your email logs?
One more thing - is there something suspicious in PHP error logs?

**Comment by djsmoye** [comment] 2023-03-05 21:03
Yes I have this tow logs but in php any error.
[image: Capture d’écran 2023-03-05 à 22.00.42.png]

Le dim. 5 mars 2023 à 19:58, Daniel Hlavacek ***@***.***> a
écrit :

**Comment by AureRita** [comment] 2023-03-06 17:07
Hi @djsmoye 

Thank you for your issue ! I tried to reproduce it and as you can see, I can't reproduce it 

[Untitled_ Mar 6, 2023 6_05 PM.webm](https://user-images.githubusercontent.com/100699445/223180641-1395b4d9-cfb4-44bb-acf9-2df8d0077dbb.webm)

Did I miss something ? 

Did your issue is on classic theme or in another theme ? 

Can you check on the email section if the mail is correctly send ( like me at the end of the video ? ) 

Waiting for your feedback

**Comment by djsmoye** [comment] 2023-03-06 17:23
Hi,

I use Leotheme and any mail are send to admin. Only to customer.

**Comment by djoelleuch** [comment] 2023-03-07 14:22
Hello @djsmoye 

Your issue is related to your custom theme , switch to your to classic theme , and you will not encounter the issue.
Closing the issue as it's not related to the Core.

Thanks!

**Closed as completed by djoelleuch** 2023-03-07 14:22 UTC
Labels: Bug, Front-end, ps_emailalerts, Invalid, Module, 1.7.8.8

**Comment by Hlavtox** [comment] 2023-03-08 09:24
@djoelleuch Theme has nothing to do with email alerts module, you should not be closing the issue.

@djsmoye Last thing I could think of - could you check the modules/ps_emailalerts/mails if you have the email templates for new_order for all languages you are using? They disappeared somehow on one of my stores once.

**Comment by djsmoye** [comment] 2023-03-08 09:30
Hi Daniel,

I thought this morning that it might be the missing models. I will check
and try to put those of the original template.

Michel

Le mer. 8 mars 2023 à 10:24, Daniel Hlavacek ***@***.***> a
écrit :
