### ISSUE TITLE
BO - A bad display of the email template of the classic theme using RTL language

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27665] opened 2022-02-14 14:39 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A bad display of the email template of the **classic theme** using **RTL** language. 
The whole template is displayed in the right.

1783 :x:
![image](https://user-images.githubusercontent.com/92912932/153883580-1a5c6c8e-2b1d-461d-a748-b28227f335b8.png)

https://user-images.githubusercontent.com/92912932/153883370-ffdcec1a-8213-48ac-8fcc-e53125a9d1f6.mp4

178x :x:
**Gmail**
![image](https://user-images.githubusercontent.com/92912932/153879389-7d74ceba-b649-4882-a2d8-9b329b23267d.png)
**Outlook**
![image](https://user-images.githubusercontent.com/92912932/153892217-19a05bf2-e54d-46d6-9e7b-1a4d3308b74c.png)

1780 :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/92912932/153884645-7e4a691b-02ad-480a-a9ba-d44fddbfde6f.png)

1778 :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/92912932/153877368-07744476-bbcd-4cab-8ce8-6a8ede00c0eb.png)

https://user-images.githubusercontent.com/92912932/153883184-12ecfe82-bcc0-451c-aa11-54e2e24cab88.mp4

### Expected behavior

Only the text of the email template should be diplayed from right to left with RTL lnaguage.

### Steps to reproduce

1. BO > IMPROVE > Localization > Import Arabic Language
2. Change the employee's language to RTL
3. BO >  CONFIGURE > Advanced Parameters > E-mail
4. Configure for a `Gmail` , `Outlook` server mail
3. BO > Design > Email Theme
4. Choose `classic` for preview
5. Select these configurations 
 ```
email theme: classic
Select your language: Arabic
Select the theme you want to overwrite: Core
Overwrite templates: Yes
```
6. Click On Generate emails
7. Click on  the `classic` theme loop configuration
8. Click on `Send a test email `for any classic layout
9. check the mailbox
10. See error > The template is in the right 

### PrestaShop version(s) where the bug happened

1.7.8.x & 1.7.8.3

### PHP version(s) where the bug happened

7.3

**Comment by MatShir** [comment] 2022-02-28 14:41
@mparvazi what do you think about this issue ? ;)

**Comment by mparvazi** [comment] 2022-02-28 14:49
> @mparvazi what do you think about this issue ? ;)

The classic-email uses a css file for RTL overrides, but currently most of the email services dismiss using external css files.
Even you add RTL css rules in template file (inside style tag), then there is no guarantee all the css rules to be used by email services.

**Comment by mparvazi** [comment] 2022-02-28 15:07
@MatShir 

Need to fix RTL problems for classic email theme? modern-email currently is RTL adopted.

If you want to fix this problem for RTL, a refacto will be needed for classic-email (using smarty variables instead of hard-coded alignments).

**Comment by MeKeyCool** [comment] 2022-08-02 12:46
Hi @tegbessou , I see you are assigned to this issue since March. I would like to test if I can find the problem.
Let me know if you had find any hint ;)

**Comment by MeKeyCool** [comment] 2022-08-02 16:12
@HanaRebaiQA , as we discussed earlier, I tested with a gmail SMTP server and client using a 1.7.8.3 Prestashop and I can't reproduce.

![Capture d’écran du 2022-08-02 18-08-51](https://user-images.githubusercontent.com/1133504/182422047-51364b40-124d-4b6d-b5a0-963086dc8bcb.png)
![Capture d’écran du 2022-08-02 18-09-57](https://user-images.githubusercontent.com/1133504/182422052-163da604-36f3-496a-a6d3-4444c5527cab.png)

Could you help me please ?
:pray: :cat2:

**Comment by MeKeyCool** [comment] 2022-08-03 09:23
Seen with @HanaRebaiQA , 

In my screenshots we can see that I had some translations mistakes due to cache (fixed with International > Translations > Add / Update a language). But even updating language properly, I can't reproduce.

Waiting for some analysis from QA ^^ 

> :point_up:  @jolelievre added some information, some recent PR may have solved the problem (to check if more investigation required) : 
> - https://github.com/PrestaShop/mjml-theme-converter/pull/20
> - https://github.com/PrestaShop/PrestaShop/pull/27614
> - https://github.com/PrestaShop/PrestaShop/pull/29068

**Comment by FabienPapet** [comment] 2022-08-24 11:50
@PrestaShop/qa-team friendly reminder as this ticket has been waiting for QA for a while.

**Comment by AureRita** [comment] 2022-08-24 14:21
Hello @FabienPapet and @MeKeyCool 

Currently, me and @HanaRebaiQA   tried to reproduce this issue to see if it's corrected but because of this one : 
https://github.com/PrestaShop/PrestaShop/issues/28014 

we can't reproduce this issue, it's blocked until we correct the other one

**Comment by MeKeyCool** [comment] 2022-08-24 23:17
> Hello @FabienPapet and @MeKeyCool
> 
> Currently, me and @HanaRebaiQA tried to reproduce this issue to see if it's corrected but because of this one : #28014
> 
> we can't reproduce this issue, it's blocked until we correct the other one

I don't understand why this issue is blocking :thinking:
Was testing with 2FA authentication a part of the current issue ?

Maybe the command line I used for SMTP configuration may help :thinking: 
```sh
mysql -u prestashop_admin --password=prestashop_admin -D prestashop -e "UPDATE `ps_configuration` SET `value` = "2" WHERE `name` = "PS_MAIL_METHOD"
mysql -u prestashop_admin --password=prestashop_admin -D prestashop -e "UPDATE `ps_configuration` SET `value` = "${SMTP_SRV_HOST}" WHERE `name` = "PS_MAIL_SERVER";
mysql -u prestashop_admin --password=prestashop_admin -D prestashop -e "UPDATE `ps_configuration` SET `value` = "${SMTP_SRV_ENCRYPTION}" WHERE `name` = "PS_MAIL_SMTP_ENCRYPTION";
mysql -u prestashop_admin --password=prestashop_admin -D prestashop -e "UPDATE `ps_configuration` SET `value` = "${SMTP_SRV_PORT}" WHERE `name` = "PS_MAIL_SMTP_PORT";
mysql -u prestashop_admin --password=prestashop_admin -D prestashop -e "UPDATE `ps_configuration` SET `value` = "${SMTP_SRV_USR}" WHERE `name` = "PS_MAIL_USER";
mysql -u prestashop_admin --password=prestashop_admin -D prestashop -e "UPDATE `ps_configuration` SET `value` = "${SMTP_SRV_PWD}" WHERE `name` = "PS_MAIL_PASSWD";
```

**Comment by atomiix** [comment] 2022-09-05 13:12
@AureRita I agree with @MeKeyCool, I don't see why this issue is blocked because of #28014, can you have another look or explain a bit more why it's blocked? Thanks!

**Comment by MeKeyCool** [comment] 2022-09-19 07:08
Friendly reminder @PrestaShop/qa-team :relaxed:

**Comment by AureRita** [comment] 2022-09-19 07:58
Hi @atomiix and @MeKeyCool, 

this issue #28014 block us to test it with gmail or outlook, we can only use a email catcher like maildev, so we can't see if it's corrected with this two different mail. Indeed the email generation done by prestashop didn't give us all the details. If you :

8. Click on Send a test email for any classic layout

you'll not have the mail and when you will test your email if you can use it, you'll have this red notice : 
![image](https://user-images.githubusercontent.com/100699445/190973549-9fb44ae0-5851-4778-ad88-fd6e3d4fd342.png)

Thank you

**Comment by MeKeyCool** [comment] 2022-09-19 08:18
> Hi @atomiix and @MeKeyCool,
> 
> this issue #28014 block us to test it with gmail or outlook, we can only use a email catcher like maildev, so we can't see if it's corrected with this two different mail. Indeed the email generation done by prestashop didn't give us all the details. If you :
> 
>     8. Click on Send a test email for any classic layout
> 
> 
> you'll not have the mail and when you will test your email if you can use it, you'll have this red notice : ![image](https://user-images.githubusercontent.com/100699445/190973549-9fb44ae0-5851-4778-ad88-fd6e3d4fd342.png)
> 
> Thank you

Maybe I don't understand your testing environment then :thinking: 
You don't have any command line access, do you ?

**Comment by atomiix** [comment] 2022-09-19 12:33
@AureRita Why not just use sendmail? It will probably go in your junk mail but you'll be able to see it.
Otherwise, you can still use maildev with [those options](https://maildev.github.io/maildev/#usage):
![Capture d’écran 2022-09-19 à 14 32 04](https://user-images.githubusercontent.com/2168836/191017899-aaef2603-9a39-4f81-b0e4-0a3feed0ca74.png)

Like so, emails will be forwarded using an external SMTP (if it's not possible with PrestaShop directly)

**Comment by hibatallahAouadni** [comment] 2022-09-19 13:59
Hello @MeKeyCool & @atomiix 

It seems the issue is not blocked in your side :slightly_smiling_face: 
So could you please reproduce the issue and chnage the labels (delete `TBR` and `Waiting for Dev`, add `NeedsSpecs` and `Verified`).
Waiting for your feedback.

Thanks!

**Comment by atomiix** [comment] 2022-09-19 15:44
I wasn't able to reproduce the issue:
![Capture d’écran 2022-09-19 à 17 42 15](https://user-images.githubusercontent.com/2168836/191058107-7811aa16-95fa-4946-b04a-16f4dc98e08d.png)
![Capture d’écran 2022-09-19 à 17 44 04](https://user-images.githubusercontent.com/2168836/191058117-26728393-c790-411b-a34a-4a750c2aa33d.png)

**Comment by MatShir** [comment] 2022-09-26 08:23
Shall we close this issue then @hibatallahAouadni?

**Comment by matks** [comment] 2022-10-16 19:27
> Shall we close this issue then @hibatallahAouadni?

Dear @PrestaShop/issue-managers following latest messages it seems this issue can be closed, wdyt ? 😄

**Closed as completed** 2022-10-18 16:12 UTC
Labels: Bug, Trivial, BO, Regression, Front-end, Email theme, Invalid, 1.7.8.3
