### ISSUE TITLE
Access denied into /admin123/index.php?controller=AdminTabs&token=xxx… #17501

### ISSUE THREAD

**Issue by HamzaElghanoui** [PrestaShop/PrestaShop#17508] opened 2020-02-05 13:07 UTC
**Describe the bug**
Menu tab not exists And then Access direct to the link get error access denied

**To Reproduce**
1. See error
![image](https://user-images.githubusercontent.com/50219389/73844096-2a0efc80-4820-11ea-9a70-4dfe0b1dcaae.png)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.3
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-02-05 13:13
Hi @HamzaElghanoui,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15048

Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-05 13:13
Duplicate of #15048

**Closed as completed** 2020-02-05 13:12 UTC
Labels: Duplicate
