### ISSUE TITLE
Wrong language in order messages.

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#22482] opened 2020-12-17 17:23 UTC
#### Expected behavior

In my case in the previous version the backoffice was English and the customer had placed an order from Greece.
All my order messages are in English and Greek and when i was scrolling the message list for a customer from Greece the messages were all showing up in Greece. If the customer had placed an order from the Englsh frontoffice the messages were showing in English.

#### Steps to Reproduce

1. Go to an order 
2. Click on 'order messages and for a customer that has a different language that the one the admin is in.
3. Scroll the list of messages
4. If the problem is there you will see the messages in the language the admin is in and not according to customers origin.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3.38

**Comment by florine2623** [comment] 2020-12-18 08:43
Hi @Stampa-Stampa ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

My BO is in French, my customer used English, I'm checking his messages but there's no issue :
![Capture d’écran 2020-12-18 à 09 42 54](https://user-images.githubusercontent.com/16019289/102593649-6b955700-4115-11eb-9ac5-64b0e4258fab.png)

I will close this issue.

Thank you

**Closed as completed by florine2623** 2020-12-18 08:43 UTC
Labels: No change required

**Comment by kmorgen** [comment] 2021-06-23 08:34
We are now experiencing the same lately both on PS 1.7.7.4 and 1.7.7.5. Not sure if there is a newer/open post for this?

The pre-made customer messages are no longer in the customer/order language, but in the shop default/admin language. It used to work in earlier versions (introduced around 1.7.7.2-1.7.7.4 i guess). Tested on both a Live and a Dev site.

(when checking the actual e-mails, the subject is actually in the customer/order language, but content is not. In BO the subject is not in the order/customer language either)
