### ISSUE TITLE
Unable to load theme's translation form in Back Office

### ISSUE THREAD

**Issue by ma0dubois** [PrestaShop/PrestaShop#12295] opened 2019-01-24 16:43 UTC
**Describe the bug**

Unable to load theme's translation form in Back Office

We do not encounter the problem with the classic theme, but we do encouter it with child themes and themes built upon StarterTheme

---

**To Reproduce**

1. Try to translate a theme <details><summary>URL</summary>`BaseUrl/myadmindir/index.php/international/translations?lang=fr&type=themes&selected=mytheme&locale=fr-FR&_token=mytoken`</details>

2. Eveything seems good, an ajax request starts to fetch the translations <details><summary>AJAX URL</summary>`BaseUrl/myadmindir/index.php/api/translation/tree/fr/themes/mytheme?_token=mytoken`</details>

3. But here is what we get as response :

	```json
	{"error":"Warning: Invalid argument supplied for foreach()"}
	```

4. Obviously, we are unable to translate anything.

5. Upon further investigation we manage to catch this exception : 

```php
"Syntax error in template "\themes\mytheme\modules\bankwire\views\templates\front\payment_execution.tpl"  
on line 27 
"<a href="{$link->getPageLink('order', true, NULL, "step=3")|escape:'html':'UTF-8'}" title="{l s='Go back to the Checkout' mod='bankwire'}">{l s='Checkout' mod='bankwire'}</a>
<span class="navigation-pipe">{$navigationPipe}</span>{l s='Bank-wire payment' mod='bankwire'}" 
unknown tag 'l'
```

Note : 
 - It's a BackOffice ONLY problem as already existing translations are being used in the FrontOffice.
 - Removing the bankwire module just moves the exception to the next module.

For further investigation see **Investigating** below.

---

**Question :**

Are we missing a file or is our configuration missing a parameter somewhere ?

If not, how can we go about solving the issue ?

Thanks,

---

**Additionnal information**

PrestaShop version: 1.7.4.3

PHP version: 7.1.24 (64 bits)

Smarty version : 3.1.33 (12.09.2018)

<details><summary> Investigating : </summary>

AJAX URL :
```
BaseUrl/myadmindir/index.php/api/translation/tree/fr/themes/mytheme?_token=mytoken
```
Dispatches to :

```php
File :
src/PrestaShopBundle/Controller/Api/TranslationController.php
Line :
109
Function :
listTreeAction
```
Leads to :
```php
File :
src/PrestaShopBundle/Controller/Api/TranslationController.php
Line :
299
Function :
getNormalTree
```
Leads to :
```php
File :
src/PrestaShopBundle/Service/TranslationService.php
Line :
106
Function :
getTranslationsCatalogue

/!\ :
If $selected is !== from 'classic'
Else use src/PrestaShopBundle/Translation/Factory/TranslationsFactory.php
```
Leads to :
```php
File :
src/PrestaShopBundle/Translation/Factory/ThemeTranslationsFactory.php
Line :
66
Function :
createTranslationsArray
```
Leads to :
```php
File :
src/PrestaShopBundle/Translation/Provider/ThemeProvider.php
Line :
195
Function :
synchronizeTheme
```
Leads to :
```php
File :
src/PrestaShopBundle/Translation/Extractor/ThemeExtractor.php
Line :
67
Function :
extract
```
Leads to :
```php
File :
vendor/prestashop/translationtools-bundle/Translation/Extractor/SmartyExtractor.php
Line :
57
Function :
extract
```
Leads to :
```php
File :
vendor/prestashop/translationtools-bundle/Translation/Extractor/SmartyExtractor.php
Line :
72
Function :
extractFromFile
```
Leads to :
```php
File :
vendor/prestashop/translationtools-bundle/Translation/Compiler/Smarty/TranslationTemplateCompiler.php
Line :
76
Function : 
getTranslationTags
```
Leads to :
```php
File :
vendor/smarty/smarty/libs/sysplugins/smarty_internal_templapteparser.php
Line : 
3447
Function : 
doParse
```
Leads to :
```php
File :
vendor/smarty/smarty/libs/sysplugins/smarty_internal_templapteparser.php
Line : 
3367
Function : 
yy_reduce
```
Leads to :
```php
File :
vendor/smarty/smarty/libs/sysplugins/smarty_internal_templapteparser.php
Line : 
2258
Function : 
yy_r25
```
Leads to :
```php
File :
vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php
Line :
561
Function :
compileTag
```
Leads to :
```php
File :
vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php
Line :
1465
Function :
compileTag2
```
Leads to :
```php
File :
vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php
Line :
1085
Function :
trigger_template_error
```
Throws :
```php
"Syntax error in template "\themes\mytheme\modules\bankwire\views\templates\front\payment_execution.tpl"  
on line 27 
"<a href="{$link->getPageLink('order', true, NULL, "step=3")|escape:'html':'UTF-8'}" title="{l s='Go back to the Checkout' mod='bankwire'}">{l s='Checkout' mod='bankwire'}</a>
<span class="navigation-pipe">{$navigationPipe}</span>{l s='Bank-wire payment' mod='bankwire'}" 
unknown tag 'l'
```

</details>

**Comment by khouloudbelguith** [comment] 2019-01-24 17:17
Hi @ma0dubois,

Have you the same issue with this issue?
![image](https://user-images.githubusercontent.com/16067358/51695789-330da100-2004-11e9-83c5-0d53510dcf29.png)
If yes, we need to Export the language from the translation page, Copy the file the file generated into the translation file of your theme according to this documentation: http://build.prestashop.com/howtos/translation/how-to-translate-your-theme/#case-2:-you-are-creating-new-strings-in-files-that-already-exist-in-the-default-theme.

Thanks to check & feedback.

**Comment by ma0dubois** [comment] 2019-01-25 09:18
Thanks for the links,

If we understoof we are in case #2, #3 and #4.

Here is what we tried :

Exporting 'classic' theme translation :

- Didn't work, got this error

![exportclassictranslation](https://user-images.githubusercontent.com/17147012/51736509-8fb39f00-208a-11e9-8121-27beb81c0516.PNG)

In our theme/modules :

- Changed all {l s='...' mod ='...'} to {l s='...' d='Shop.Theme'}
    - Didn't work

- Changed all {l s='...' mod ='...'} to {l s='...' d='Shop.Theme.Modulename'}
    - Didn't work

- Changed all {l s='...' mod ='...'} to {l s='...' d='Shop.Themename'}
    - Didn't work

- Changed all {l s='...' mod ='...'} to {l s='...' d='Shop.Themename.Modulename'}
    - Didn't work

Here are screenshots of the errors we get (always the same) :

Form **MODIFY TRANSLATIONS** 

![translationerror1](https://user-images.githubusercontent.com/17147012/51736487-84607380-208a-11e9-9756-d8c020a94918.PNG)

Form **EXPORT A LANGUAGE**

![exportthemetranslation](https://user-images.githubusercontent.com/17147012/51736500-8aeeeb00-208a-11e9-8bca-400d82a47098.PNG)

**Comment by khouloudbelguith** [comment] 2019-01-25 10:22
Hi @ma0dubois,

I tried to export a 'classic' theme translation with PS1.7.4.4 & PS1.7.5.0 & I did not manage to reproduce the issue.
I attached a video record
https://drive.google.com/file/d/1VN5Ke1sYKzT5INCFxP9cxUY_9dPrpQVj/view
Thanks to check & feedback.

**Comment by ma0dubois** [comment] 2019-01-28 15:56
Hi @khouloudbelguith,

We upgraded to 1.7.5.0 and tried what you did.

I believe we have a lang pack problem, we tried what you did in the video and here is the error we got :

![errorexport](https://user-images.githubusercontent.com/17147012/51848322-a9b8e000-231d-11e9-943f-1a0b3e68aa01.PNG)

**Comment by khouloudbelguith** [comment] 2019-01-28 16:18
Hi @ma0dubois, 

During the upgrade, have you any errors occurred?
In my case, I tried also after upgrade from 1.7.4.4 to 1.7.5.0 & the "Export language" function works correctly.
Thanks!

**Comment by ma0dubois** [comment] 2019-01-28 16:28
> Hi @ma0dubois,
> 
> During the upgrade, have you any errors occurred?
> In my case, I tried also after upgrade from 1.7.4.4 to 1.7.5.0 & the "Export language" function works correctly.
> Thanks!

Hi,

No  :/

**Comment by khouloudbelguith** [comment] 2019-01-28 16:52
Hi @ma0dubois,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt
Thanks!

**Comment by ma0dubois** [comment] 2019-01-29 07:30
> Hi @ma0dubois,
> 
> Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in /autoupgrade/tmp/log.txt
> Thanks!

We perform the update manually.
So it is impossible for us to send you these logs.

Thanks !

**EDIT**

After checking our database, it appears the `locale` field in `ps_lang` was empty and `language_code` was not set at the right value.

(Database migrated from 1.6 to 1.7 using your scripts manually as we can not use the autoupgrade module)

We can now succesfuly export classic theme's traductions, on the other hand we still have this error upon trying to export/translate our theme (migrated from 1.6 to 1.7) :

![error](https://user-images.githubusercontent.com/17147012/51900523-d4567780-23b5-11e9-9de5-aa05662f9cf2.PNG)

For more info on how we get to this error see the "Investigating" section of our first post.

**Comment by khouloudbelguith** [comment] 2019-01-29 11:40
Hi @ma0dubois,

Have you tried to follow this documentation https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/ during the upgrade?
It could be a problem if you have missed a file?
or something went wrong with your update and don't have some of the database columns that were added for 1.7.5.0
You can find the full schema for 1.7.5.0 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/data/db_structure.sql
Thanks!

**Comment by ma0dubois** [comment] 2019-02-08 15:16
Hi,

We found the problem.

It was coming from the `sprintf` tag in the translation function.
After removing all the `sprintf` tag, we have no issues translating.

> NOTE: Understand that using 1.7 `sprintf` syntax did not work 
(Like  `sprintf=['%order%' => $order_name]`

**Comment by khouloudbelguith** [comment] 2019-02-08 16:12
@ma0dubois, since it is fixed, I close the issue.
Feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2019-02-08 16:12 UTC
Labels: BO, Translations, No change required, 1.7.4.3

**Comment by tiptopnet** [comment] 2019-08-09 12:02
Hi @ma0dubois 
I have the same problem 
Can you tell me please where you removed sprintf ? (folder/file) 
Thanks for your help
