### ISSUE TITLE
Order creation on the backoffice with free shipping: "Error: Call to a member function addOrderPayment() on null"

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#14957] opened 2019-08-01 14:38 UTC
When I validate the creation of an order created on the backoffice, and that there are free shipping from a cart rule, I've the following error:

![image](https://user-images.githubusercontent.com/22885898/62302085-09817680-b47a-11e9-9e79-b94eb7f5d080.png)

And, another issue, but surely associated: when I create an order on the back-office and I check "free shipping" (on the "Shipping" panel), all carriers disappear and the following message is displayed: "Aucun transporteur ne peut être appliqué à cette commande".

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.19

**Comment by khouloudbelguith** [comment] 2019-08-01 14:57
Hi @yannicka,

I did not manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2.
I attached a screen record
https://drive.google.com/file/d/1yydxQpPFrL4L5pcclbAFBZ1D2y1gljIh/view
Thanks to check & feedback.

**Comment by yannicka** [comment] 2019-08-02 07:23
Thanks. Here is a link to download a video of the issue: https://framadrop.org/r/f6jzE5W1Kw#QpQYP0lwpYtmu+DuV3JKaeiBUh041u0UHXpQ6DQm0Fc=

**Comment by khouloudbelguith** [comment] 2019-08-02 09:51
@yannicka, could you please try to change the `SHIPPING` method with another delivery option, created manually, for example, check & feedback.
![image](https://user-images.githubusercontent.com/16067358/62361709-6e3cdf80-b513-11e9-85d1-018f21c3ae21.png)
Thanks!

**Comment by yannicka** [comment] 2019-08-02 12:11
I have try to create a delivery option, and I have the same issue.

**Comment by khouloudbelguith** [comment] 2019-08-02 12:45
@yannicka, this issue occurs with all customers & all products added to this order?

Thanks!

**Comment by yannicka** [comment] 2019-08-02 14:31
Yes, the issue seems to occurs with all customers & all products.

**Comment by khouloudbelguith** [comment] 2019-08-02 15:01
@yannicka, could you please check if you have an override of the Class `PaymentModule.php`.

Thanks!

**Comment by yannicka** [comment] 2019-08-05 06:30
There is no override of the class `PaymentModule.php`.

**Comment by khouloudbelguith** [comment] 2019-08-05 09:41
@yannicka, Could you please provide me access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by yannicka** [comment] 2019-08-09 16:01
For the moment I can't. Maybe later, I'll keep you informed.

**Comment by khouloudbelguith** [comment] 2019-08-09 16:03
@yannicka, Thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-09-09 07:49
Hi @yannicka,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-09 07:49 UTC
Labels: Bug, BO, Order, Topwatchers, No change required, 1.7.5.1

**Comment by beforcom** [comment] 2020-02-08 18:26
Hi, i have the same problem on 1.7.4.2 with an overide on validateOrder function on PaymentModule.php

Have you got an idea please ?

**Comment by khouloudbelguith** [comment] 2020-02-10 11:36
Hi @beforcom,

>overide on validateOrder function on PaymentModule.php

You need to check this override is provided by which module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by tameroski** [comment] 2020-02-10 16:00
I've got the exact same issue as @yannicka on a 1.7.5.1 / PHP7.2.24
No override on PaymentModule.php
Occurs only when checking "Free shipping" on an order placed through the backoffice.

![Capture d’écran 2020-02-10 à 17 26 04](https://user-images.githubusercontent.com/338432/74168862-a80d4200-4c2a-11ea-9829-1b739607e557.png)

I noticed that this error occurs when chosing Bank Transfer payment only.
When the payment method is Check, i got a different error in the form of an alert (and the order is not created) : 

![Capture d’écran 2020-02-10 à 17 32 00](https://user-images.githubusercontent.com/338432/74169261-544f2880-4c2b-11ea-9e7a-71311e3a8794.png)

And some other errors with 3rd party modules like Paypal etc.

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "update" of class "stdClass"." at /var/www/mysite/modules/paypal/paypal.php line 1191 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"update\" of class \"stdClass\". at /var/www/mysite/modules/paypal/paypal.php:1191)"} []`

**Comment by tameroski** [comment] 2020-02-11 11:27
Just an important update : this is also happening in the shop if a Free shipping voucher is used by a customer.
The customer goes through the payment process, but the order is not placed ! I just got a customer that was billed, and there's no corresponding order in the backoffice.
Here's the error in the logs : 

```
PHP Notice:  Undefined variable: order in /var/www/mysite/classes/PaymentModule.php on line 457
PHP Fatal error:  Uncaught Error: Call to a member function addOrderPayment() on null in /var/www/mysite/classes/PaymentModule.php:457\nStack trace:\n#0 /var/www/mysite/modules/systempay/systempay.php(1306): PaymentModuleCore->validateOrder(11759, 2, 356.4, 'Paiement par ca...', NULL, Array, 1, true, 'e3a072e4ba2d71c...')\n#1 /var/www/mysite/modules/systempay/validation.php(134): Systempay->saveOrder(Object(Cart), 2, Object(SystempayResponse))\n#2 {main}\n  thrown in /var/www/mysite/classes/PaymentModule.php on line 457
```

As far as i remember, it used to work just fine. And i'm not able to reproduce this on a fresh local install :(

**Comment by tameroski** [comment] 2020-02-12 09:26
For the record : the issue still exists after disabling all overrides and all non-prestashop modules in the Performances parameters.

@yannicka : did you finally manage to fix this issue ? I'd be curious to find out how, if you don't mind. Thanks.

**Comment by khouloudbelguith** [comment] 2020-02-12 09:29
@tameroski,

>the issue still exists after disabling all overrides and all non-prestashop modules in the performance options.

The options do not work in the PS1.7.6
as reported here:
#14596
#9965

Thanks!

**Comment by tameroski** [comment] 2020-02-12 14:50
After banging my head several times against my desk, i came to the conclusion that this problem is linked to [that other one](https://github.com/PrestaShop/PrestaShop/issues/10903#issuecomment-438573882).
After disabling a cart rule having a minimum amount and shipping included, everything went back to normal in my shop.
Thanks Khouloud for your help in here btw.

**Comment by khouloudbelguith** [comment] 2020-02-12 14:55
@tameroski, #10903 is added to our bug roadmap.

Thanks!

**Comment by aloisejulian** [comment] 2020-03-31 18:17
I'm having this problem in Prestashop 1.7.6.2

**Comment by adriacobo** [comment] 2020-04-01 11:23
This error still happens on 1.7.6.4, 
To reproduce:
- Create a cupon with code, minimum amount and free shiping (assign code is important)
- Do a purchase on Front
- Apply the coupon on last step
- Pay via WireTransfer 
And whops... FatalThrowableError                                                                  
Call to a member function addOrderPayment() on null
-- in PaymentModule.php line 373

As I far I debug all this variables on file are empty, then the Object $order is never created.
$delivery_option_list = $this->context->cart->getDeliveryOptionList();
$package_list = $this->context->cart->getPackageList();
$cart_delivery_option = $this->context->cart->getDeliveryOption();

I hope get some help with this.
Thanks!

**Comment by jeremLF** [comment] 2020-05-06 15:27
Hello,
I'm having this problem too...
I'm on Ps 1.7.6.1

When i'm creating an order directly on the BO and if i set the free shipping option on, i'll get the critical error "Call to a member function addOrderPayment() on null"

Is there any new on how to fix this ? I guess this ticket shoudnt be "closed"...

Thanks !

-- 

Edit : I've got a cart rule who offer the shipping when the cart is above 80€, when i create an order > 80€ in the BO, the rule is well activated and i don't get any error this way

**Comment by msaustral** [comment] 2020-08-31 23:46
Hi, we did have the same issue, this happen when you create a coupon with only free shipping without any amount to discount.

**Comment by imaging04** [comment] 2020-11-28 19:27
This issue still on Prestashop 1.7.6.8

**Comment by kpodemski** [comment] 2020-11-28 22:41
Hello,

I suggest you to test it on 1.7.7 where there's a new order page .

**Comment by msaustral** [comment] 2020-12-13 00:39
Hi on 1.7.6.9 it is corrected

**Comment by Kreysh** [comment] 2022-07-09 19:36
> Hi on 1.7.6.9 it is corrected

Still have the issue in 1.7.6.9
