### ISSUE TITLE
FO - Featured product not well displayed with responsive

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25283] opened 2021-07-08 11:30 UTC
#### Describe the bug

- Go to homepage, reduce screen size and see featured products overflow into each other.

#### Expected behavior

It should be well displayed as in PS1769
![image](https://user-images.githubusercontent.com/16067358/127674541-53828dd4-c660-402c-87b5-096b02de3cc7.png)

#### Steps to Reproduce

1. Go to FO > home page
2. Resize the window

1.7.7.5 => NOK
![image](https://user-images.githubusercontent.com/16067358/127674638-d3090e2e-4b5f-4d82-ae55-daf46c03f9d1.png)

1.7.8.X => NOK
![image](https://user-images.githubusercontent.com/16067358/127674676-1a12e713-4b79-4b58-ad1d-fdf9855a73ac.png)

#### Additional information

* PrestaShop version: 1.7.7.5, 1.7.8.0
* PHP version: 7.2

**Comment by kpodemski** [comment] 2021-07-08 11:33
Hey @Hlavtox 

Could you please create separate issues with a proper template? 🙏

**Comment by Hlavtox** [comment] 2021-07-08 11:35
@kpodemski I was too lazy, but OKKKK 😄

**Comment by hibatallahAouadni** [comment] 2021-07-08 15:45
Hello @Hlavtox 

> Go to any 404 page or bestsellers page. Search bar overflows the container and is not aligned to center due to float: right. I think we can stop using float to position elements in flex times.

If you're talking about the (1) search bar is already fix it with this PR #25192 and your issue is a duplicate of #25133
if (2), I didn't manage to reproduce your issue, please check the attached screenshot below:

**Mobile:**
![image](https://user-images.githubusercontent.com/23308427/124936867-3136cd00-e007-11eb-8efc-3e01040dd4ed.png)

**Desktop:**
![image](https://user-images.githubusercontent.com/23308427/124950872-18341900-e013-11eb-9859-60fd77ed1108.png)

> Go to homepage, reduce screen size and see featured products overflow into each other.

The featured products are well displayed, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/124940422-43663a80-e00a-11eb-812b-ff87df17c3e0.png)

> Go to any category, see that content is not aligned with the container on both sides by 15px due to missing .row element that should be wrapping **left-column** and **content-wrapper**.

I reproduce the issue with PS178x and PS1775, but I think it's the wanted behavior :thinking: 

![image](https://user-images.githubusercontent.com/23308427/124952005-2afb1d80-e014-11eb-97e6-ac3f78666592.png)

PS: you really need to stop being lazy :wink: 
Thanks!

**Comment by Hlavtox** [comment] 2021-07-10 18:57
@hibatallahAouadni 

> I reproduce the issue with PS178x and PS1775, but I think it's the wanted behavior 🤔

If it's a wanted behavior, it should be done by properly spacing the container, not omitting proper markup ;-). In 1.7.6, no extra space was present, by a hack though.
![css](https://user-images.githubusercontent.com/6097524/125173578-5ae72400-e1c0-11eb-98f5-0e117742ec91.JPG)

_____________________

> The featured products are well displayed, see the attached screenshot below:

Try other resolutions:
![Výstřižek](https://user-images.githubusercontent.com/6097524/125173600-65a1b900-e1c0-11eb-9e25-392717605a85.JPG)

**Comment by hibatallahAouadni** [comment] 2021-07-12 13:22
Hello @Hlavtox 

Thanks for your feedback!
## Featured products display
With PS177x, the featured products are badly displayed, see the attached screenshot below (screen size < 1200px):

![image](https://user-images.githubusercontent.com/23308427/125268403-f7680e00-e307-11eb-98a2-c26232f6a643.png)

With PS178x, I encounter similar issues, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/125269004-91c85180-e308-11eb-9a2e-c191f8625a27.png)

While with PS1767, the products use to be well organized and spaced, just the container is not centred:

![image](https://user-images.githubusercontent.com/23308427/125269549-187d2e80-e309-11eb-8af3-f49e6685a715.png)

Yet, the 176x is better displayed than 177x and 178x => **`Regression`** **`To Do`**

## Searchbar
Could you please answer my question about this part:
> If you're talking about the (1) search bar is already fix it with this PR #25192 and your issue is a duplicate of #25133
if (2), I didn't manage to reproduce your issue, please check the attached screenshot below:

## Product display in the Category page

> If it's a wanted behavior, it should be done by properly spacing the container, not omitting proper markup ;-). In 1.7.6, no extra space was present, by a hack though.

It's the same thing in 176x, check the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/125294837-eb3e7980-e324-11eb-8b5b-63caf07b7a86.png)

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment] 2021-07-29 08:54
@hibatallahAouadni 
**Search bar** - OK, didn't check current branch, if you say it's fixed, good.
**Product layout** - Reproduced, OK!
**Page layout** - You can see that it's happening only on pages with left column. If you check full width page (CMS or homepage), they are full width. **Boostrap columns without row are not valid code.**

**Comment by khouloudbelguith** [comment] 2021-07-30 13:59
Hi @Hlavtox,

About the last issue
`Go to any category, see that content is not aligned with the container on both sides by 15px due to missing .row element that should be wrapping left-column and content-wrapper.`

Isn't the same issue reported here: https://github.com/PrestaShop/PrestaShop/issues/25467?

Thanks to check and feedback.

**Comment by Hlavtox** [comment] 2021-07-30 15:02
@khouloudbelguith Yes I made a separate issue, so we can properly merge the PR. :-) 

Consider this a notebook to be deleted 😂

**Comment by khouloudbelguith** [comment] 2021-07-30 15:16
Hi @Hlavtox,

I will update the first comment, I'll add this to the debug backlog so that it's fixed.
It is a regression PS177 as mentioned by @hibatallahAouadni in this [comment](https://github.com/PrestaShop/PrestaShop/issues/25283#issuecomment-878275396)
Thanks!

**Comment by Progi1984** [comment] 2021-08-05 14:11
Ping @NeOMakinG

**Closed as completed** 2021-09-20 09:10 UTC
Labels: Bug, Minor, FO, Regression, Fixed, Front-end, PR available, Featured products, Responsive, 1.7.8.0, 1.7.8.x, 1.7.7.5
