### ISSUE TITLE
Search big many result when reference contains minus

### ISSUE THREAD

**Issue by RomanXT** [PrestaShop/PrestaShop#11326] opened 2018-11-08 17:38 UTC
Hello,
If the product SKU contains a minus, then the search by FO gives you hundreds of results, and the product is one with such an SKU
Exmaple:
Search im my shop one product SKU: PKA-KDS-4040-SET show 175 results
"-" he takes for spaces, then search PKA, KDS, 4040 and SET
I would like to show only product with this SKU
There was no problem with prestashop 1.5

Prestashop 1.6.1.20

**Comment by khouloudbelguith** [comment] 2018-11-09 08:36
Hi @RomanXT,

This issue is fixed in the last version 1.7.5.0, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9336 to solve the issue.
In the PS1.6, here's the same issue: http://forge.prestashop.com/browse/PSCSX-8965
It is not necessary to create another one.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-09 08:36
Duplicate of #9336

**Closed as completed by khouloudbelguith** 2018-11-09 08:36 UTC
Labels: Duplicate
