### ISSUE TITLE
Error 500 trackingfront module

### ISSUE THREAD

**Issue by YanisseZ** [PrestaShop/PrestaShop#18007] opened 2020-03-05 17:27 UTC
#### Describe the bug

When i go on https://www.mawallbox.fr/modules/trackingfront/stats.php
I have a error 500

**Error with debug mode**

[Screenshot](https://image.noelshack.com/fichiers/2020/10/4/1583429220-capture.png)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-03-06 08:07
Hi @YanisseZ,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9780
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-06 08:07
Duplicate of #9780

**Closed as completed by khouloudbelguith** 2020-03-06 08:07 UTC
Labels: Duplicate

**Comment by healthguru2020** [comment] 2020-09-21 11:47
yes it is in the issue list for 5 years, are you going to fix it?
