### ISSUE TITLE
Dashboard activity doesn't work!

### ISSUE THREAD

**Issue by eliapresta** [PrestaShop/PrestaShop#34202] opened 2023-10-07 13:56 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

my dashboard activity does not display the data correctly. 

I have already tried several times to uninstall the module and reactivate it! But nothing, the problem persists. I have asked prestashop for support but nothing. 
![Schermata 2023-10-07 alle 15 45 37](https://github.com/PrestaShop/PrestaShop/assets/147257268/aab2a8f8-2aa8-4d51-8711-703ab121c971)

### Expected behavior

I expect to see data like this.

![Schermata 2023-10-07 alle 15 54 36](https://github.com/PrestaShop/PrestaShop/assets/147257268/8c9ab83c-b790-4c63-81e7-8bb45638e410)

### Steps to reproduce

.

### PrestaShop version(s) where the bug happened

8.01

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

v2.1.0-dashactivity

**Comment by florine2623** [comment] 2023-10-09 09:37
Hello @eliapresta ,

I can't reproduce your issue in PS 8.0.x :
<img width="1437" alt="Screenshot 2023-10-09 at 11 37 02" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/96eb1107-17da-4f65-8ed9-4af96de5c271">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing it to avoid clogging the backlog.

Thank you

**Closed as completed by florine2623** 2023-10-09 09:37 UTC
Labels: Bug, Invalid

**Comment by ZaDarkSide** [comment] 2024-03-20 23:32
I don't know the exact error but I was able to fix it by doing a reset on Product Comments module. I hope this will be useful for someone facing a similar issue.
