### ISSUE TITLE
Add product to existing order in BO

### ISSUE THREAD

**Issue by AdrianMoise** [PrestaShop/PrestaShop#26605] opened 2021-11-15 11:13 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i try to add a product to an existing order in BO, i get a red notice with the text "[InvalidArgumentException code 0]".
Also i get the follow error in the browser console web tool: prestashop-ui-kit.js:1 POST https://dev.nvboutique.gr/nvbadmin/index.php/sell/orders/3403/products?_token=DxcZ0ILfjJiCOd-3Y8lkyWt9HTO9yGzhgatBAuVfOmM 400 (Bad Request)
After testing the issue, i have found that if i refresh the page the product that i requested it is added.
The same error and behavior(after refresh) happens when i try to delete a product from the order.
When i open the debug, i have the follow warnings:
JQMIGRATE: jQuery.parseJSON is deprecated; use JSON.parse   prestashop-ui-kit.js:1

Bellow i attached the printscreens for the 2 errors
![jquery-parsejson-deprecated](https://user-images.githubusercontent.com/92859941/141771574-c7932e76-346a-4d2a-80f0-8251a63c4ea1.PNG)
![request-error](https://user-images.githubusercontent.com/92859941/141771576-2efb70e4-dacf-47b8-baa4-5da4062e87e1.PNG)

Prestashop Version 1.7.8.0
PHP Version 7.3.32

### Steps to reproduce

1. Go to "BO: Orders-->Select an existing order"
2. Click on "Add product to order"

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3.32

**Comment by florine2623** [comment] 2021-11-15 13:24
Hello @AdrianMoise ,

I can't reproduce your issue on PS 1.7.8.0, please check my screen record :
https://watch.screencastify.com/v/C8ealCzDS2RFvI3XDsyy

Can you give me more details about this issue so I can reproduce the issue on my end ?
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-06 17:08
Hello @AdrianMoise 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-12-06 17:08 UTC
Labels: Bug, BO, Order, 1.7.8.0, Invalid
