### ISSUE TITLE
Big problem taxes and reduction (french)

### ISSUE THREAD

**Issue by Esh-network** [PrestaShop/PrestaShop#24073] opened 2021-04-15 13:02 UTC
#### Describe the bug

Here is a tax error which is present on prestashop that I have just discovered and put together several times I think without any corrections to date: /.
Here are two examples of invoices with the same amount but the taxes are different (check the attached invoices below)

the invoice 1 the prices are set without the promotions on the products (specific price)
invoice 2 the rates are set with specific prices.
the sums are the same on the two invoices because I wanted to show the bug on the taxes.

Indeed the calculation of taxes is not done correctly on the two invoices because:
119.72 + 20% = 23.94 (rounded off 24) and in both cases the amount is not correct
** invoice 1 ** 24.34 which approaches the correct result (rounded off 24) for the accounting ok.
** Invoice 2: ** 22.34 (rounded off 22) which is therefore not correct.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. The taxes used are 20% on the products.
2. Product sheet configure with specific price
3. Set Product 1 like below: ![image](https://cdn.esh-dev.fr/upload/chrome_QnLd9QxAJj.png)
4. Set Product 2 like below: ![image](https://cdn.esh-dev.fr/upload/chrome_rfvc5QeCg1.png)
5. ......
6. ......
7. See error ......

test run on a demo store:

- https://demopresta.esh-demo.fr/admin027v2jqcg
- user : demo@demo.fr
- password : demodemo

**Screenshots**
invoice 1: 
![image](https://cdn.esh-dev.fr/upload/chrome_1UNfLs0Eh4.png)

invoice 2:
![image](https://cdn.esh-dev.fr/upload/chrome_WJMD3YNuAM.png)

#### Additional information

* PrestaShop version: 1.7.x.x test for 1.7.7.3 and 1.7.6.9
* PHP version: 5.6 -> 7.4

**Comment by florine2623** [comment] 2021-04-16 09:58
Hello @Esh-network ,

Please make sure you are compliant with PrestaShop System Requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
You must downgrade to PHP 7.3 for PS 1.7.7.3.

Please check https://github.com/PrestaShop/PrestaShop/issues/14646 and feedback.
Thanks!

**Comment by Esh-network** [comment] 2021-04-16 10:50
Hello @florine2623  I am used to prestashop the subject of php has nothing to do with the concern of taxes it is a problem in the heart of prestashop.

I put all the prestashop versions of 1.7 because the bug is present on the 1.7 and the php version to use regardless of the bug is also present ^^.

I am thinking of poor code formatting for taxes and even worse when it comes to product with% promos.

The concern must therefore be globally I think.


Cordially.

**Comment by florine2623** [comment] 2021-04-16 15:03
Yes of course, I agree with you, it is just to make sure that you have full compatibility with the system requirements !

Can you check #14646 and feedback.

**Comment by Esh-network** [comment] 2021-04-16 15:08
Issue # 14646 is pretty much similar but not quite that yet.

No fix my bug: s.

**Comment by florine2623** [comment] 2021-04-23 13:46
Hello @Esh-network ,
Could you send me the steps to reproduce the issue so i can test on my end ?

Thanks!

**Comment by Esh-network** [comment] 2021-04-23 14:32
Hello,

very well I make you 2 video

In the first video it is the problem I have with the invoices with two different management because 1 invoice with specific price on the products and the other invoice not.

in the video the left invoice = without specific price and right invoice with specific price.
video 1: https://cdn.esh-dev.fr/upload/Produits%20%E2%80%A2%20demo%20presta%20-%20Google%20Chrome%202021-04-23%2016-19-19.mp4

In video two I made an example with two products with and without specific price

left without specific price and right with specific price on invoices.

However the behavior on the left invoice in the second video no problem but if several products are wandering.

video 2 https://cdn.esh-dev.fr/upload/ESH%20-%20Admin%20-%20Google%20Chrome%202021-04-07%2020-47-21.mp4

**Comment by hibatallahAouadni** [comment] 2021-04-26 08:18
Hello @Esh-network 

Please edit your comment and use English. English is the norm on GitHub.
Add your steps to reproduce the bug in your issue's description :wink: and then notify me.

Thank you

**Comment by Esh-network** [comment] 2021-04-26 09:33
@hibatallahAouadni Watch my video for the steps

video 1: https://cdn.esh-dev.fr/upload/Produits%20%E2%80%A2%20demo%20presta%20-%20Google%20Chrome%202021-04-23%2016-19-19.mp4

video 2 https://cdn.esh-dev.fr/upload/ESH%20-%20Admin%20-%20Google%20Chrome%202021-04-07%2020-47-21.mp4

**Comment by hibatallahAouadni** [comment] 2021-04-27 14:58
Hello @Esh-network 

Thanks for your feedback!

- First video: **404 Not Found** :confused: I couldn't access to it
- Second video: it shows that you have some problem with your invoices list, is that so?

I just edit your issue description, so please please list the steps to reproduce the issue and describe the bug :pray: :pray: :pray: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-17 07:52
Hello @Esh-network ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-17 07:52 UTC
Labels: Bug, BO, Order, Invoices, Tax rules, No change required, 1.7.6.9, 1.7.7.3

**Comment by Esh-network** [comment] 2021-05-17 11:43
Hello,

watch video 2 if video 1 does not work it is not essential to the bug.

Cordially.
