### ISSUE TITLE
"New"-label suddenly not translated in PS 8.1.1

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33877] opened 2023-09-07 23:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PrestaShop v 8.1.0 (with Danish language), the "New"-label (flag on new products) was translated to Danish:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/5ae30b93-7f34-4dee-a011-13c5ca145f0a)

But in PrestaShop v 8.1.1 it is suddenly shown in English:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/af9a9cad-83bb-4605-bd21-cb2b4c0f5308)

And as far as I can see, it is still translated correctly in the translations:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/57584044-e810-4e51-b9e4-4d3e2bac6187)

And I also checked the .xlf files where it also seems to be translated correctly:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/213b62a4-b12b-4b60-8087-09f061824ea0)

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/9f768b76-c39b-4262-a9c6-a08616eade06)

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/e4e5ddd4-26e9-40f5-b4b4-5bc479745259)

### Steps to reproduce

I dont really know how to "reproduce" this one... other than:

1: Upgrade PS 8.1.0 with Danish as the only language to PS 8.1.1

2: Check new products

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by hibatallahAouadni** [comment] 2023-09-08 07:53
Hello @LarsGMortensen 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #33780. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-09-08 07:53
Duplicate of #33780

**Closed as completed by hibatallahAouadni** 2023-09-08 07:53 UTC
Labels: Bug, Duplicate, Invalid

**Comment by LarsGMortensen** [comment] 2023-09-08 12:39
Hi @hibatallahAouadni  Sorry about this duplicate. I actually did see if I could find the issue among those already created, but didn't find it. Sorry. But thank you for the update :)
