### ISSUE TITLE
Notice: Undefined offset 0 when generating PDF invoice for order with customized data

### ISSUE THREAD

**Issue by rvalery** [PrestaShop/PrestaShop#15358] opened 2019-09-02 12:13 UTC
**Describe the bug**
When you try to generate PDF invoices by date, a PHP notice is displayed if an order contains a product with a text customization field, but no file customization field. (I assume it will also fail if product contains a file customization field but no text customization field).

The PHP notice is "Notice: Undefined offset: 0" (see screenshot below)

**To Reproduce**
Steps to reproduce the behavior: Install last prestashop version and enable debug mode. Then :
1. In front-office : select the customizable mug example product, customize the text, add it to the cart
<img width="1137" alt="Capture d’écran 2019-09-02 à 13 52 34" src="https://user-images.githubusercontent.com/222965/64113291-2ddab680-cd8a-11e9-95c6-9120f68f921a.png">

2. Proceed with order.
<img width="1123" alt="Capture d’écran 2019-09-02 à 13 48 02" src="https://user-images.githubusercontent.com/222965/64113304-3632f180-cd8a-11e9-86d4-6a9dea48ef98.png">

3. In Back-office : go to order page, and set the newly created order as delivered.
<img width="634" alt="Capture d’écran 2019-09-02 à 13 48 38" src="https://user-images.githubusercontent.com/222965/64113314-3cc16900-cd8a-11e9-8589-a9aa7cc106be.png">

4. Go to invoice page, generate invoices by date.
<img width="924" alt="Capture d’écran 2019-09-02 à 13 49 06" src="https://user-images.githubusercontent.com/222965/64113357-64b0cc80-cd8a-11e9-8e25-4de3d1dc01fc.png">

5. Notice is displayed if in debug mode (if not in debug mode, invoice is generated properly, and notice is only logged into php error log).
<img width="1051" alt="Capture d’écran 2019-09-02 à 13 43 53" src="https://user-images.githubusercontent.com/222965/64112590-24e8e580-cd88-11e9-8c5a-426256fad971.png">

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.6.30

The problem comes from the file pdf/invoice.product-tab.tpl, line 121 :
`{if isset($customization.datas[$smarty.const._CUSTOMIZE_FILE_]) && count($customization.datas[$smarty.const._CUSTOMIZE_FILE_]) > 0}`

When compiled by smarty, it is translated to :
`<?php if ((($_smarty_tpl->tpl_vars['customization']->value['datas'][@constant('_CUSTOMIZE_FILE_')] !== null )) && count($_smarty_tpl->tpl_vars['customization']->value['datas'][@constant('_CUSTOMIZE_FILE_')]) > 0) {?>`

Instead of isset, smarty uses a check against null value (!==null). Contrary to isset, this check raise the above mentionned notice. I have tested this on a prestashop 1.6 install (version 1.6.1.18), and the problem is not present. The compiled template is using a proper isset test :
`<?php if (isset($_smarty_tpl->tpl_vars['customization']->value['datas'][@constant('_CUSTOMIZE_FILE_')])&&count($_smarty_tpl->tpl_vars['customization']->value['datas'][@constant('_CUSTOMIZE_FILE_')])>0) {?>`

**Comment by khouloudbelguith** [comment] 2019-09-02 12:56
Hi @rvalery,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 / PS1.7.6.0 & PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/64116129-5c0bc680-cd89-11e9-877c-3c083c5d1f4d.png)
Mode debug should be enabled
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by rvalery** [comment] 2019-09-02 14:02
Thanks for your reply.
Unfortunately I have not yet found a way to correct this. I don't know if the problem is from Smarty itself (changing the isset into "!==null" check), or if it comes from a Prestashop configuration, or something in the way Prestashop uses smarty to compile templates. I will try to dig further in the code if I can find the time this week.

**Comment by wxiaoguang** [comment] 2020-05-26 04:16
It is a smarty bug, please upgrade the smarty to the latest one:

https://github.com/smarty-php/smarty/blob/master/CHANGELOG.md

[3.1.35] - 2020-04-14

* fix errors that occured where isset was replaced with null check such as https://github.com/smarty-php/smarty/issues/453

**Comment by khouloudbelguith** [comment] 2020-08-12 09:56
Hi @rvalery,

It is fixed in the 1.7.7.x branch.
I attached a screen record
https://drive.google.com/file/d/1EYXmI4-AMWXEzU02LQamVqJIn6AVuBMi/view?usp=sharing
Your ticket is a duplicate of #18837
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-12 09:57
Duplicate of #18837

**Closed as completed by khouloudbelguith** 2020-08-12 09:56 UTC
Labels: BO, Duplicate, Invoices, Product customization, 1.7.5.2, 1.7.6.0, 1.7.6.1, PR available

**Comment by rvalery** [comment] 2020-08-12 10:19
That is a good news, I will update to 1.7.7.x to test it.
Thanks !
