### ISSUE TITLE
PS 1.7.6.1 breaks module admin controllers list buttons

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#15638] opened 2019-09-21 14:53 UTC
This code is new in 1.7.6.1, used to build the parameters for controller list buttons.

It is assuming the table id, is the table name with id_ in front of it.  This is not enforced in the controller, or in the object model classes, where you specify what the table id is.

So this code generates a PHP Notice should your table id be different to table name, and if debug mode is enabled, this cuases symfony to bail out rendering the page.

```
/**
     * @param string $action
     * @param string $entity
     * @param array $parameters
     *
     * @return array
     */
    private function buildActionParameters($action, $entity, array $parameters)
    {
        unset($parameters['current_index']);
        $viewAction = $action . $entity;
        $entityId = 'id_' . $entity;
        $parameters = array_merge(
            $parameters,
            [$entityId => $parameters[$entityId], $viewAction => 1]
        );

        return $parameters;
    }
```

Basically, I don't think you should be assuming that you know what the table id is.  Especially when you specifically allow it to be set in the controller to whatever you want it to be.

Any complaints if the code is changed to this:

```
private function buildActionParameters($action, $entity, array $parameters)
    {
        unset($parameters['current_index']);
        $viewAction = $action . $entity;
        $entityId = 'id_' . $entity;
        $parameters = array_merge(
            $parameters,
            isset($parameters[$entityId]) ? [$entityId => $parameters[$entityId], $viewAction => 1] : [$viewAction => 1]
        );

        return $parameters;
    }
```

This at least removes the PHP Notice.  Though why why why do you introduce new code & features on minor point releases, should be for bug fixes only.

This will affect any admin controller in any module, that is setting the table identifier in the controller.

**To Reproduce**
You'll need a controller with a db table where the table primary id is different to the table name.

**Screenshots**
![image](https://user-images.githubusercontent.com/19314911/65374909-af6c8880-dc54-11e9-8b96-1d45a79706f4.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-09-23 08:39
Hi @roja45,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15382 to fix the issue.
Your ticket is a duplicate of #15333
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-23 08:39
Duplicate of #15333

**Closed as completed by khouloudbelguith** 2019-09-23 08:39 UTC
Labels: Duplicate
