### ISSUE TITLE
IF "Use WebP for all images" AND "Generate high resolution images" are both settled I get Gateway timeout

### ISSUE THREAD

**Issue by amazingballzs** [PrestaShop/PrestaShop#32173] opened 2023-04-15 02:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I settled "Use WebP for all images" and "Generate high resolution images". I Imported a set of products, then tested the front office. at first try went fine for the homepage, then I tried to open a product page and got gateway timeout.
Tried to use the back office and got gateway timeout too.
Checked server load and noticed that the use had 100% CPU usage and alternating very high IO load.
After a while the process ended and the website became functional again, however trying again to open a product page the same happened, gateway timeout on front and back office until process cease.
The website was practically totally unusable.
I switched off "Generate high resolution images" and everything begun to work as expected. fast and smooth.

### Expected behavior

I expected normal functioning of the website, I got instead gatweway timeouts and unusable website.

### Steps to reproduce

1. Activate "Use WebP for all images"
2. Activate "Generate high resolution images"
3. Navigate in the front office shop
4. The website becomes unresponsive and a gateway timeout is thrown
5. Navigating the back office ends up too in gateway timeout
6. Check the server load and see how the CPU and IO are overloaded
7. Once the process end everything seems normal until a category or product page is hit

### PrestaShop version(s) where the bug happened

I tested this behaviour on PS 8.0.2 and 8.0.3

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

no

**Comment by AureRita** [comment] 2023-04-19 13:45
Hi @amazingballzs 

Thank you for your report, I tried to reproduce your issue but I can't, as you can see in this video : 

[Untitled_ Apr 19, 2023 3_25 PM.webm](https://user-images.githubusercontent.com/100699445/233090111-51bd77d6-2e1b-417b-b344-f15ea3126bcc.webm)

Did I miss something ? 

Waiting for your feedback

**Comment by ChillCode** [comment] 2023-04-19 22:31
Hi @amazingballzs 

That is the normal behavior of PrestaShop when you modify Image Settings.

If you don't want that PrestaShop generates the HR image when visiting a product you can generate them in Image Settings:

![regenerate](https://user-images.githubusercontent.com/9787055/233213657-b0c8a814-08ff-4c0c-93b4-d89d77e9d824.png)

**Comment by amazingballzs** [comment] 2023-04-29 16:11
Hello
The server I use for this website nominally is a VPS with 24GB RAM, SSD, Octacore Xeon(R) CPU @ 2.20GHz on Centos 7
Being a virtual thing let's assume that of course it does not truly have the full power that is nominally declared, but, in general, I do not think that it is a "barely able" or substancially weak virtual machine.
This server is not overloaded of websites and concurrent active processes, I checked loads during these event and simply the machine was cluttered right when the HR images generation was requested.
Might be something in the configuration of the server about generating Webp images?
If it is the server having problems at handling webp format, why this issue happens only when I settle it to generate the HR version?
I have to further investigate about this issue.
Thank you for the information and the hints so far

**Comment by ChillCode** [comment] 2023-05-03 09:13
Hi

This is just my opinion and can be wrong.

PHP is pretty bad at high performance tasks like image processing and binary file manipulation compared to system/command line, so you can have 24GB but PHP library (GD) will allocate what is configured on memory_limit.

To make you're own findings you can isolate `ImageManager::resize()` (classes\ImageManager.php) and benchmark it and then compare to system `convert` command and will see the differences.

If you're familiar with PrestaShop code you can easily override `ImageManager::resize()` and use system libraries instead of GD2.

Also PrestaShop can be improved a lot for users that do not use Shared Hostings and have access to the system.

For example when I needed to convert a xlsx file to csv I used the vendor library that comes with PrestaShop and always got memory errors and timeouts (4CPU and 8GB) even editing the main class to use less resources, then I replaced it with `system(xlsx2csv)` and it took seconds to complete the task.

Hope this clarifis how PHP (also Python) are not good for theses tasks.

**Comment by AureRita** [comment] 2023-05-04 15:31
Hi @amazingballzs 

Did your issue is resolved by using the regenerate thumbnails in the option ? 

waiting for your feedback

**Comment by hibatallahAouadni** [comment] 2023-05-23 15:02
Hello @amazingballzs 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-05-23 15:02 UTC
Labels: Bug, BO, Design, Image, Invalid, 8.0.2
