### ISSUE TITLE
Can't add a new product

### ISSUE THREAD

**Issue by BasilDiouf** [PrestaShop/PrestaShop#35340] opened 2024-02-13 14:24 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop version : 8.1.2
PHP version : 8.2.14
My Email : basil.diouf@gmail.com

Hi, it's impossible for me to add a new product in my prestashop. When i click on "new product", i'm stuck on the next window. I can't confirm my choice and continue.
![Screenshot 2024-02-13 143201](https://github.com/PrestaShop/PrestaShop/assets/134514622/d91d870d-ae03-48eb-be53-272f7e8e3ba6)
Someone from the technical support tell me to ask my question here, he was speaking about do core.
Thanks for your help ! 

### Expected behavior

I want to confirm my selection and add a new product.

### Steps to reproduce

Go to "product" and "new product".
Click on the "type of product" you want.
See the problem.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.2.14

**Comment by paulnoelcholot** [comment] 2024-02-13 15:01
Hello @BasilDiouf,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/2b7305cb-6d15-4ce0-bd92-76df77fedd03)

**Closed as completed by paulnoelcholot** 2024-02-13 15:01 UTC
Labels: Bug, Can't reproduce
