### ISSUE TITLE
Avis Clients / No comments appears

### ISSUE THREAD

**Issue by patricecarrier** [PrestaShop/PrestaShop#23705] opened 2021-03-19 16:16 UTC
#### Describe the bug

• CommentProduct module configured and no comments appears on my product page.
• When i click on "write recommandations" and i submit form, it show me modal error instead of modal ok. 
• Recommandations are effective in administration.
• the link on read comments (#product-comments-list-header id) doesn't work

#### Steps to Reproduce

https://lepetitfreshy.fr/la-boutique/24-le-petit-freshy.html

**Screenshots**

<img width="2048" alt="Capture d’écran 2021-03-19 à 17 14 02" src="https://user-images.githubusercontent.com/80974055/111810708-9b035d80-88d6-11eb-87a6-92e858525411.png">

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.3.27

**Comment by florine2623** [comment] 2021-03-19 16:25
Hi @patricecarrier ,

You need to downgrade your version of PHP to 7.2 :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Are you using product comment module from PrestaShop or from your template ?
https://addons.prestashop.com/en/undownloadable/9144-product-comments.html

Thanks!

**Comment by patricecarrier** [comment] 2021-03-19 16:33
Hello,

The module is prestashop module.

Ive changed version Php in 7.2 but nothing change.

Thanks for your return (quickly as soon as possible)

**Comment by hibatallahAouadni** [comment] 2021-03-20 20:11
Hello @patricecarrier 

Did you upgrade your shop lately? If so, could you please check this issue #23218 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by patricecarrier** [comment] 2021-03-21 12:52
Hey,

Thx hibatallahAouadni for your response.

I take the project after other developper and i don't know when the upgrade has been maked.

**For information:**
Prestashop version : 1.7.6.8
PHP : 7.2
Module comment product version : 4.2.1

I don't find an answer clearly. For the moment issue are not closed.

**To help prestashop Team to resolve this error:**
• It's clearly a conflict between core.js and commentproduct.
• Error console appear only on page where commentproduct are present.
• informations are viewed on page product but all action (link to comments list, comment, ...) doesn't work

**Screenshots added:**
![Capture d’écran 2021-03-21 à 13 50 23](https://user-images.githubusercontent.com/80974055/111905547-8052f500-8a4c-11eb-9fe9-fc953dcb047d.png)
![Capture d’écran 2021-03-21 à 13 50 10](https://user-images.githubusercontent.com/80974055/111905555-85b03f80-8a4c-11eb-9a9b-c5895a7fe9f7.png)
![Capture d’écran 2021-03-21 à 13 50 03](https://user-images.githubusercontent.com/80974055/111905557-86e16c80-8a4c-11eb-9ba4-af9c159acf31.png)

How have another version of commentproduct (module undownlable) on prestashop Market Place ?

Thx all.

**Comment by hibatallahAouadni** [comment] 2021-03-23 15:03
Hello @patricecarrier 

It's the same error in this [comment](https://github.com/PrestaShop/PrestaShop/issues/23383#issuecomment-785063659) 
And it's already a duplicate of #23218 
So, your shop version was 1.6 and it was upgraded to 1.7.6.8

> How have another version of commentproduct (module undownlable) on prestashop Market Place ?

Well, you won't find it in the Market Place cause it's a native module.
So you need to: 
1. Clone the project https://github.com/PrestaShop/productcomments
```
git clone https://github.com/PrestaShop/productcomments.git
cd productcomments/
```

2. Choose the version that you want install : https://github.com/PrestaShop/productcomments/tags
For exemple:

```
git checkout tags/v3.6.0
npm install
```

3. Compress the **productcomments** folder
4. BO>IMPROVE>Modules>Module Manager
5. Click on Upload a module button
6. Upload the compressed folder
7. Enjoy it :wink: 

So this issue is a duplicate and I need to close it.

---
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23218. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-03-23 15:03
Duplicate of #23218

**Closed as completed by hibatallahAouadni** 2021-03-23 15:03 UTC
Labels: Bug, FO, Duplicate, Productcomments, 1.7.6.8
