### ISSUE TITLE
Special Characters on Private Notes and Order Messages - 1.7.6.0

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#14988] opened 2019-08-05 12:06 UTC
Upgraded to 1.7.6.0 and at the backoffice special characters like á, é, ç, ê, ã won't show correctly.

This happens on Private Notes and Order Messages

Did not happen on 1.7.5.x

**Comment by khouloudbelguith** [comment] 2019-08-05 12:23
Hi @seederp2p,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9726
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-05 12:23
Duplicate of #9726

**Closed as completed by khouloudbelguith** 2019-08-05 12:23 UTC
Labels: Duplicate

**Comment by seederp2p** [comment] 2019-08-05 12:36
Please note that this also happens on private messages which is not refered on the existing tickets...

**Comment by seederp2p** [comment] 2019-08-05 12:41
Please re-open this to have the private messages problem fixed...

**Comment by khouloudbelguith** [comment] 2019-08-05 14:09
Hi @seederp2p,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14605 to fix this issue.
It is fixed in the next version PS1.7.6.1.
Thanks!
