### ISSUE TITLE
PS 1.7.5.1 does not install properly using unix sockets. Doctrine threws an SQLSTATE[HY000]

### ISSUE THREAD

**Issue by amtriorix** [PrestaShop/PrestaShop#12930] opened 2019-03-14 22:39 UTC
Clean install of prestashop 1.7.5.1.

Use sockets, like:
1) unix:/tmp/mysql.sock

Test connection to database works.
Proceeding in install threws an error due to wrong $DSN format.

Problem is found in: src/PrestaShopBundle/Install/Install.php

L: 127 public function generateSettingsFile(

Creates a wrong app/config/parameter.php file.

Patched solutionfor file: src/PrestaShopBundle/Install/Install.php

// patch start
        /* old code
        $database_port = null;
 
        $splits = preg_split('#:#', $database_host);
        $nbSplits = count($splits);
 
        if ($nbSplits >= 2) {
            // $database_port = array_pop($splits);
            // $database_host = implode(':', $splits);
               $database_port = ""
               $database_host = ":"
        }
        new code follows */

        $splits = preg_split('#:#', $database_host);
        if (count($splits) != 2) {
                // no socket or port defined, expect this is host only or wrong format
                $database_port = null;
                $database_host = $splits[0];
        } else {
            if (is_numeric($splits[1])) {
                // ip with port
                $database_port = $splits[1];
                $database_host = $splits[0];
            } else {
                // unix_socket
                // $database_port = null;
                // $database_host = "unix:". $splits[1];
                   $database_host = "localhost";    // strange, but ok, it seems to be the only way
                   $database_port = "unix:". $splits[1]; // using standard format
            }
        }
        // patch end

**Comment by khouloudbelguith** [comment] 2019-03-15 07:37
Hi @amtriorix,

Could you please provide us the exact error displayed in your case. 
Thanks!

**Comment by amtriorix** [comment] 2019-03-16 01:25
ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". 

Message: "An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: hostname nor servname provided, or not known" ["exception" => Doctrine\DBAL\Exception\ConnectionException { …},"command" => "prestashop:schema:update-without-foreign","message" => "An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: hostname nor servname provided, or not known"]

**Comment by khouloudbelguith** [comment] 2019-03-18 14:58
Hi @amtriorix,

Thanks for these clarifications.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1yFkorBA2EnTyVn8aJH4yF_ciiJW0YUvH/view
Thanks to check & feedback.

**Comment by amtriorix** [comment] 2019-03-18 15:04
Hello,

This is normal because you do not use in your settings,
the socket in your database
settings but the host:port of your mysql server.

You need to use the unix socket at /tmp/mysql.sock

Best regards,

Jurgen

DEBO Jurgen
T: +32 (0)9
M: +32 (0) 4 9191 9999

________________________________

**Comment by khouloudbelguith** [comment] 2019-03-18 16:12
@amtriorix, thanks for your feedback.
So, in step 5: System configuration: in the Database server address, I should not use the host:port of my mysql server?
I should set `unix:/tmp/mysql.sock`?
Thanks to provide me the exact configuration.
Thanks!

**Comment by amtriorix** [comment] 2019-03-18 16:18
Hello,


Yes, when using sockets it is standard unix:/tmp/mysql.sock in Your setup.
In your php.ini You only set the default socket, but PS takes of course the settings You
fill in. When You use host:port, you do not connect through sockets but through IP.

Best regards,


Jurgen

________________________________

**Comment by khouloudbelguith** [comment] 2019-03-18 16:25
@amtriorix, thanks for these clarifications.
I tried with it but, the connection test doesn't work
![image](https://user-images.githubusercontent.com/16067358/54545826-badbb000-49a2-11e9-8fdb-916f65324873.png)
![image](https://user-images.githubusercontent.com/16067358/54545854-c9c26280-49a2-11e9-9a4e-209dc0bc6114.png)
I tried with this command: `mysql -h 127.0.0.1 -P 3306 -u root -p` & it is ok.

![image](https://user-images.githubusercontent.com/16067358/54546121-5ec55b80-49a3-11e9-84d4-d6a8f3ec1294.png)

Thanks to check & feedback.

**Comment by amtriorix** [comment] 2019-03-18 16:49
Hello,

Most likely your mysql server is not setup to use sockets.

You need to check if there is a socket.

Please verify the conf settings of your mysql server (like my.cnf):
See /etc, /usr/local/etc, /usr/local/etc/mysql or /var/db/mysql/ for 
this file

So here you comment out the IP and PORT where the server is listening
and you enable a socket to listen.

[mysqld]
#bind-address           = 127.0.0.1
#port                   = 3306
socket                 = /tmp/mysql.sock

After reboot the server there should be a file /tmp/mysql.sock

Test connection in CLI with:
#mysql --socket=/tmp/mysql.sock

Best regards,

Jurgen

**Comment by khouloudbelguith** [comment] 2019-03-18 17:00
@amtriorix, thanks for these clarifications.
I tried with this `mysql --socket=/tmp/mysql.sock` & I have this error `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`
In my file /etc/mysql/my.cnf, I edited these lines
```
[mysqld]
#bind-address=10.1.37.2
#skip-networking
socket = /tmp/mysql.sock
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/
```
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-19 16:52
Hi @amtriorix,

I solved the issue with this command `mysql --socket=/tmp/mysql.sock`, now it is OK.
![image](https://user-images.githubusercontent.com/16067358/54625287-47ec3b00-4a6f-11e9-83a2-3a87f5375861.png)
But when I try to test the database connection, I always have the same issue
![image](https://user-images.githubusercontent.com/16067358/54625483-ad402c00-4a6f-11e9-9d8f-03b5dc5af913.png)
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-04-18 15:53
Hi @amtriorix,

Any news about your issue?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-20 07:25
Hi @amtriorix,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Bugfunder** [comment] 2019-08-06 06:54
> Hi @amtriorix,
> 
> I solved the issue with this command `mysql --socket=/tmp/mysql.sock`, now it is OK.
> ![image](https://user-images.githubusercontent.com/16067358/54625287-47ec3b00-4a6f-11e9-83a2-3a87f5375861.png)
> But when I try to test the database connection, I always have the same issue
> ![image](https://user-images.githubusercontent.com/16067358/54625483-ad402c00-4a6f-11e9-9d8f-03b5dc5af913.png)
> Thanks to check & feedback.

This is because this form assumes you use TCP host/port to connect to the DB server, not the unix sockets (which are much faster). Please check what this form does, and add the possibility of using unix sockets to this form.

**Comment by khouloudbelguith** [comment] 2019-08-06 09:31
Hi @Bugfunder,

Thank you for your feedback.
We'll first try to reproduce it and we'll come back to you if we need more information.

Thanks!

**Closed as completed** 2019-08-06 09:32 UTC
Labels: Bug, IN, 1.7.5.1

**Comment by khouloudbelguith** [comment] 2019-08-06 09:34
Related to #14998.
