### ISSUE TITLE
Employee Permission not working

### ISSUE THREAD

**Issue by davidhardik** [PrestaShop/PrestaShop#19769] opened 2020-06-16 04:53 UTC
#### Describe the bug

I was trying to give the permission of certain module to the employee but all the modules are visible to all the employee even I remove their permissions. 

I created the profile, employee and tried setting up the permissions and when I do that I found that it gives me an error message: "Access denied" or " You don't have permission to access the module"

#### Expected behavior

It should show only those modules whose permission is given to that particular employee.

#### Steps to Reproduce

1. Go to Advanced -> Team
2. Create a profile 
3. Set its permission. Give permission on the right hand side of the module and set it to only few of them. View, Configure, etc.
4. Give permission to Module Manager on the left for it be accessed.
5. Try open the employee profile for whom you have provided the permission and you will find out that all the modules existing are visible to him as well.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

**Comment by sarahdib** [comment] 2020-06-16 14:46
duplicate of #9874

**Comment by sarahdib** [comment] 2020-06-16 14:47
Hello @davidhardik 

Your issue is a duplicate of #9874 you can follow this issue

**Closed as completed by sarahdib** 2020-06-16 14:47 UTC
Labels: Duplicate, Permissions
