### ISSUE TITLE
PrestaShop 1.7.8.2 Panel login error

### ISSUE THREAD

**Issue by CyberScoper** [PrestaShop/PrestaShop#35337] opened 2024-02-13 09:27 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After logging into the admin panel, I see something like this.
<img width="524" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/129629526/0563b7ab-1b18-4ddc-b78c-386325522f7f">
That's what I see in the debug menu.
<img width="697" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/129629526/b9b26916-22e8-4e5a-bc3c-a9c77abb261c">

### Steps to reproduce

1. I enter the data into the data in the admin panel.

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by paulnoelcholot** [comment] 2024-02-13 11:25
Hello @grandechuvash,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-02-13 11:25 UTC
Labels: Bug, Can't reproduce
