### ISSUE TITLE
Guest tracking page not working

### ISSUE THREAD

**Issue by 900i** [PrestaShop/PrestaShop#16737] opened 2019-12-08 23:10 UTC
Hi,
I have the same problem with the guest tracking page. After I insert the order number and the email address and I press send, it goes to the home page. Even if I don’t fill out the email and the order number and I press send it has the same behavior.

Does anyone knows which is the problem?

Thanks!

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-12-09 10:14
Hi @900i,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9650#issuecomment-415056057
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-12-09 10:14
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9650

**Closed as completed by khouloudbelguith** 2019-12-09 10:14 UTC
Labels: Duplicate
