### ISSUE TITLE
Incorrect characters in pdf output

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#20342] opened 2020-07-24 20:48 UTC
#### Describe the bug
There are incorrect characters in pdf output if there are used specific characters, e.g. instead of character "č" is displayed "?". This issue occurs if there is used language "English GB" in user profile, it works correctly if there is used language "English".

#### Expected behavior
Special characters should be always displayed correctly because we use code page utf-8.

#### Steps to Reproduce
1. Logon to BO
2. Select language "English" in user profile
3. Change address of the e-shop > append the character č to the end of the street 
4. Select language "English GB" in user profile
5. Go to Orders
6. Display any pdf invoice and at the end of the e-shop street is character ?, there should be displayed the character č

#### Additional information
* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-07-27 07:57
Hi @juraj1000,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12308
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-07-27 07:57
Duplicate of #12308

**Closed as completed by khouloudbelguith** 2020-07-27 07:57 UTC
Labels: Duplicate
