### ISSUE TITLE
Undefined index with ps_legalcompliance

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10277] opened 2018-09-04 15:16 UTC
**Describe the bug**

**To Reproduce**
1. Go to Modules > Modules Catalog
2. Install ps_legalcompliance
3. Fill the field "Additional information about delivery time" and save
4. Go to Front office & click on a product
5. See error

**Screenshots**
![capture d ecran_249](https://user-images.githubusercontent.com/13449658/45040388-35c42580-b066-11e8-9e45-55ed24b9d483.png)

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-09-04 15:19
Hi @marionf,

Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9587

Best regards, Khouloud

**Closed as completed** 2018-09-04 15:22 UTC
Labels: Bug, Major, FO, Duplicate
