### ISSUE TITLE
product combinations do not work 

### ISSUE THREAD

**Issue by klinki-m** [PrestaShop/PrestaShop#20785] opened 2020-08-29 22:23 UTC
Hi All,

recently I wanted to make some changes in the details of product combinations. 
1. The details side does not show up.
2. I realiszed that multiple radio buttons can be choosen for the default view
3. when I try to delete a product combination it ends up in a http 405 error
4. it is still possible to generate a new product combination though (positive)
5. when I create a new product and click the  "product with combinations" the "combinations" tab does not appear

 

I am not aware of any changes which I made recently 
Already cleared the cache and used various browsers with an empty cache. Nothing helps.
I am really desperate. Could it be an issue with the provider?

I also attached the logfiles:
![combinations_details_radiobutton_delete](https://user-images.githubusercontent.com/54170135/91647105-f531f380-ea56-11ea-9198-d7c245e40d2c.jpg)
![combinations_tab](https://user-images.githubusercontent.com/54170135/91647106-f6632080-ea56-11ea-9610-5e7458d7a063.jpg)
![invalid_token](https://user-images.githubusercontent.com/54170135/91647108-f6632080-ea56-11ea-8092-398caa47075e.jpg)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/5146047/prod.log)
[20200820_exception.log](https://github.com/PrestaShop/PrestaShop/files/5146048/20200820_exception.log)
[prod.log](https://github.com/PrestaShop/PrestaShop/files/5146049/prod.log)
[20200820_exception.log](https://github.com/PrestaShop/PrestaShop/files/5146050/20200820_exception.log)

```
[2020-08-20 10:44:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error:..............
[2020-08-20 12:02:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /sell/catalog/products/attributes/31": Method Not Allowed (Allow: DELETE)
```

any idea?

Please help.

Thank you
Klinki

 

Server software version: Apache
PHP version: 7.2.33
Memory limit: -1
Max execution time: 50000
Upload Max File size: 64M

info_outline Database information
MySQL version: 5.5.60-0+deb7u1-log
MySQL driver: DbPDO

info_outline Store information
PrestaShop version: 1.7.5.2

Shop URL: http://bombahair.ch/

**Comment by SimonGrn** [comment] 2020-08-30 16:26
Hello @klinki-m,

I was not able to reproduce your issue in the latest version (1.7.6.7). I however found something very similar in [this ticket](https://github.com/PrestaShop/PrestaShop/issues/10198#issuecomment-459264788), that I encourage you to check.

Please use the template when you submit an issue, since it really helps us working on your problem faster.

Thank you for your understanding.

**Comment by SimonGrn** [comment] 2020-08-30 16:26
Duplicate of #10198

**Closed as completed by SimonGrn** 2020-08-30 16:26 UTC
Labels: Duplicate, 1.7.5.2
