### ISSUE TITLE
TinyMCE broken after upgrade to 1.7.8.2

### ISSUE THREAD

**Issue by groupecomplus** [PrestaShop/PrestaShop#27147] opened 2021-12-30 09:41 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In order to migrate a website to a PHP 7.4 host, I upgraded PrestaShop to 1.7.8.2 using the **1-Click Upgrade** module.
Update process was smooth, but now all TinyMCE fields are broken.

![image](https://user-images.githubusercontent.com/92367435/147739466-1802bdd6-1de3-46ca-bc56-e56fa8bec4a7.png)

Browser's console shows:

```
10:33:47.213 Uncaught Error: Could not find control by type: button
    create https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    t https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    jt https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    t https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    t https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    a https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    renderUI https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    _w https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    Aw https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    Ow https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    u https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    jt https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    u https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    n https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    onload https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
53:2:358886
    create https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    t https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    jt https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    t https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    t https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    a https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    renderUI https://example.com/js/tiny_mce/themes/modern/theme.min.js:1
    _w https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    Aw https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    Ow https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    u https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    jt https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    u https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    n https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2
    onload https://example.com/administration/index.php/sell/catalog/products/53?_token=e5RMxkfMLGqlHr3v161hR3NhOngeYKDiyHfnWY9q3eA#tab-step1 line 253 > injectedScript:2

```

I used a [solution posted on the forum](https://www.prestashop.com/forums/topic/1055811-unable-to-edit-page-content-product-titles-product-summary-etc-after-upgrading-from-1760-to-1780/), but it's just a workaround that forces the usage of the mobile theme instead of the modern theme.

### Expected behavior

TinyMCE fields should work correctly

### Steps to reproduce

1. Update PrestaShop to 1.7.8.2
2. Create a new product
3. All fields that use TinyMCE will be broken
4. Check browser console for JS errors related to js/tiny_mce/tinymce.min.js

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by groupecomplus** [comment] 2021-12-30 09:57
Found a better workaround that restores the original functions. Replaced tinymce.min.js with the modified version found in a previous release: https://raw.githubusercontent.com/PrestaShop/PrestaShop/1.7.7.8/js/tiny_mce/tinymce.min.js
Won't close for now because the release is broken.

**Comment by hibatallahAouadni** [comment] 2021-12-30 10:45
Hello @groupecomplus 

Please configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation, and clear the cache. Also, try to open your shop in an incognito browser.
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.

I didn't manage to reproduce the issue after an upgrade from PS1778 to PS1782 using the 1-click upgrade v4.13.0, see the  attached screen record below:

https://watch.screencastify.com/v/4fcqMPLVodx83dTMgbjt


This issue is a cache problem and it's duplicate of #26543
Closing this issue.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-30 10:45
Duplicate of #26543

**Closed as completed by hibatallahAouadni** 2021-12-30 10:45 UTC
Labels: Bug, Duplicate, Invalid
