### ISSUE TITLE
combination->setAttributes not working with multiple attributes

### ISSUE THREAD

**Issue by c4chale** [PrestaShop/PrestaShop#19398] opened 2020-05-26 16:51 UTC
### Describe the bug

I am creating a combination using the new Combination() method and adding the attributes with `setAttributes($attributes_id);`

When I set `$attributes_id` with an id only it works as aspected yet I am trying to combine 2 attributes and the, as shown in the screenshot 1, it only shows one (the first one inputted).

### Expected behaviour

The combination should have both attributes, the same as doing `generate` from the combination page (screenshot 2, screenshot 3).

### Steps to Reproduce
```Php
$attributes_id = array($attribute_size_id, $attribute_color_id);

$comb = new Combination();

$comb->id_product = $product_id;
$comb->reference = $id;
$comb->ean13 = $barcode;
$comb->quantity = $quantity;
$comb->add();
$comb->setAttributes($attributes_id);
```

#### Screenshots
<img width="883" alt="Screenshot 2020-05-26 at 18 45 26" src="https://user-images.githubusercontent.com/32636582/82927500-162f0800-9f81-11ea-8f6e-753cb3c218ea.png">

_screenshot 1_

<img width="889" alt="Screenshot 2020-05-26 at 18 48 10" src="https://user-images.githubusercontent.com/32636582/82927964-c270ee80-9f81-11ea-9c1f-d106a1a81b3f.png">

_screenshot 2_

<img width="890" alt="Screenshot 2020-05-26 at 18 48 25" src="https://user-images.githubusercontent.com/32636582/82928013-d9afdc00-9f81-11ea-96c7-fad848399d87.png">

_screenshot 3_

### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.30-1
* System: Ubuntu server 20.04.1

**Comment by marionf** [comment] 2020-05-27 12:20
Hello @PrestaShop/prestashop-core-developers Could you try to reproduce this issue ?

**Comment by hibatallahAouadni** [comment] 2021-11-15 09:26
Hello @chale96 

Thanks for your patience :pray: 
Do you still reproduce the issue? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-30 09:04
Hello @chale96 

Since we had no news from you for days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-11-30 09:04 UTC
Labels: Bug, CO, Combinations, 1.7.6.5, Invalid
