### ISSUE TITLE
Phone number should be clickable

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#25068] opened 2021-06-21 17:12 UTC
#### Is your feature request related to a problem?

I would like to have my phone app open when i click on the phone number on the top.

#### Describe the solution you'd like

Convert the number to a link.

#### Alternatives you've considered
No alternative.

**Comment by florine2623** [comment] 2021-06-22 07:27
Hello @e-gaulue ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by henri9813** [comment] 2021-06-22 07:41
@florine2623 I already make a PR

**Comment by hibatallahAouadni** [comment] 2021-06-24 00:07
Hello @henri9813 

Thanks for your PR 🎉
Could you please check this issue #18928 it seems similar to yours.
If it's a duplicate then you should reference your PR to the issue #18928 and close this issue as a duplicate 😉

Please check and feedback.
Thanks!

**Comment by henri9813** [comment] 2021-06-29 11:28
Hello,

Indeed, it's a duplicate, but the other issue should be splitted not ?

**Comment by florine2623** [comment] 2021-06-29 12:53
Hello @henri9813 ,

The PR is already linked to #18928, so I'll close it to avoid any duplicate.

Thanks!

**Comment by florine2623** [comment] 2021-06-29 12:53
Duplicate of #18928

**Closed as completed by florine2623** 2021-06-29 12:53 UTC
Labels: Improvement, FO, Duplicate, PR available, Contactinfo

**Comment by henri9813** [comment] 2021-06-29 13:07
Hello,

Your PR is open since may 2020, one year ago.

My issue has a PR which is about to be merged.

Not close this issue, this issue gonna be close automatically.

Thank
