### ISSUE TITLE
Product comments: Comments not being displayed

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26829] opened 2021-12-02 01:01 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the page of a product that has at least one comment, there are no visible comments. The number of them is shown:
![grafik](https://user-images.githubusercontent.com/92299973/144338045-6e8d5461-213b-4629-8fc6-2c20eea01605.png)
The comments that have been posted and approved before the update to module version 5.0.0 as well as those after the update are affected.
The issue is browser and device independent with regards to the client. There was no issue with the previous module version (4.2.2). The cache has already been cleared to force regeneration.

### Expected behavior

The product comments should appear.

### Steps to reproduce

1. Go to any product page that should have at least one product at [...] (For example: [...] )
2. Scroll down to the bottom of the page.
3. See the number of comments and the " No customer reviews for the moment. " text.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3.31

### If your bug is related to a module, specify its name and its version

productcomments v5.0.0

**Comment by hibatallahAouadni** [comment] 2021-12-02 11:27
Hello @awarszewski 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26834. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-12-02 11:27
Duplicate of #26834

**Closed as completed by hibatallahAouadni** 2021-12-02 11:27 UTC
Labels: Bug, Duplicate, Invalid
