### ISSUE TITLE
dashproduct module bug

### ISSUE THREAD

**Issue by darkstudio** [PrestaShop/PrestaShop#20995] opened 2020-09-15 15:33 UTC
#### Describe the bug

dashproduct prestashop module 2.1.0 doesn't work on dashboard. 2.0.4 version work well.

#### Expected behavior

error 500 for some ressource when load dashboard. everythings work but dashproduct module is empty and we can see an error 500 on dev tools.

#### Steps to Reproduce

Install 2.1.0 version of dashproduct module
Goto dashboard and check dashproduct dashboard

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.1.32

**Comment by khouloudbelguith** [comment] 2020-09-15 15:50
Hi @darkstudio,

Thanks for your report.
I did not manage to reproduce the issue with PS1767.
I attached a screen record
https://drive.google.com/file/d/1j4GATaycm9yJ1IKYn0kENtZ_1ocTO1Qp/view?usp=sharing
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-10-05 09:38
Hi @darkstudio,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-10-05 09:38 UTC
Labels: Bug, Dashboard, Dashproducts, No change required, 1.7.5.2
