### ISSUE TITLE
Search's cron doesn't work

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/PrestaShop#15979] opened 2019-10-16 12:18 UTC
**Describe the bug**
Search's cron is configured on our server with URL given in back office but it redirects on admin login page, so it isn't executed.

**To Reproduce**
1. Configure search's cron on server with URL given in back office
2. Lets turn it
3. Cron gives a "302 Found" header and it is redirected on admin login page so it isn't executed

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: PHP 7.2

**Comment by khouloudbelguith** [comment] 2019-10-16 12:34
Hi @bm-services,

Here's the PR: #15855 to fix the issue.
It is fixed in the newt patch PS1.7.6.2.
Your ticket is a duplicate of #15725
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-16 12:34
Duplicate of #15725

**Closed as completed by khouloudbelguith** 2019-10-16 12:34 UTC
Labels: Duplicate

**Comment by bm-services** [comment] 2019-10-16 12:44
Sorry for the duplication. I don't find the other ticket with github search.
Thanks !
