### ISSUE TITLE
ps_emailsmanager throw an exception

### ISSUE THREAD

**Issue by mariem-abid** [PrestaShop/PrestaShop#26974] opened 2021-12-14 09:03 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we click on the "save" button, an error appears.

### Steps to reproduce

1- install the ps_emailmanager module
2- select your template zip
3- click on the "Use this template"
4- click on the "Save" button
=> an error appears
![ps_emailsmanager](https://user-images.githubusercontent.com/36841537/145966184-b849af60-db65-4899-b1f3-1c83ba71fc11.png)
s

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.26

### If your bug is related to a module, specify its name and its version

ps_emailsmanager v1.2.1

**Comment by florine2623** [comment] 2021-12-14 09:22
Hello @mariem-abid ,

I can't reproduce your issue. I followed these steps :
- Install ps_emailsmanager v1.2.1
- Download Template [Boxy](https://addons.prestashop.com/fr/templates-email-prestashop/25942-boxy-template-d-emails-by-prestashop.html)
- Import template
- <img width="310" alt="Screenshot 2021-12-14 at 10 16 24" src="https://user-images.githubusercontent.com/16019289/145969764-cfbf31fe-2f6d-48d3-a6f2-837c37c763b5.png">
- Available template are displayed : 
- <img width="628" alt="Screenshot 2021-12-14 at 10 16 30" src="https://user-images.githubusercontent.com/16019289/145969741-cca465cf-98ff-4870-97f2-b6374123f60d.png">
- Use this template
- <img width="314" alt="Screenshot 2021-12-14 at 10 16 49" src="https://user-images.githubusercontent.com/16019289/145969710-b212b95b-9862-4d86-ba80-477e9ab7d723.png">

I don't have any error.
If you disable debug mode do you have an error as well ?
Thanks!

**Comment by mariem-abid** [comment] 2021-12-14 09:27
Please enable the debug mode.
I reproduce this issue only with php 7.4 
with php 7.3 => OK
It is a compatibility issue with PHP7.4

**Comment by florine2623** [comment] 2021-12-14 09:51
I have enabled debug mode in PS 1.7.8.x, PHP version is 7.4.2. I can't reproduce the issue :
<img width="1432" alt="Screenshot 2021-12-14 at 10 48 44" src="https://user-images.githubusercontent.com/16019289/145974573-ca3663c7-195d-4128-a345-c962e718cecd.png">
<img width="140" alt="Screenshot 2021-12-14 at 10 49 39" src="https://user-images.githubusercontent.com/16019289/145974625-fc9f8850-89a0-4038-8bd3-10a0f1acf706.png">

With PHP 7.3.9, it works well too :
https://watch.screencastify.com/v/EaE2dSXZBvVUyVFVl5Bo

**Comment by florine2623** [comment] 2021-12-14 14:23
This issue has been transferred to PrestaShop Corp.
I will close the issue.

**Closed as completed by florine2623** 2021-12-14 14:23 UTC
Labels: Bug, BO, Email theme, Invalid
