### ISSUE TITLE
ps_facetedsearch: hide products that are not in stock 

### ISSUE THREAD

**Issue by Spir** [PrestaShop/PrestaShop#22056] opened 2020-11-23 13:26 UTC
#### Describe the bug

**Faceted search should not return unavailable products by default.** 
Once a user change the filters the results displayed shows some product that are no longer available. There is the possibility to add a filter option to hide unavailable product but most of the time customer don't see it. Customers are complaining. Also they have to go to the product page to see it's not available. It's pretty frustrating for them.

#### Expected behavior

When applying the filter the product that are not available for selling should not be displayed. Maybe an option should be available in the module's backend to still show unavailable products. But displaying unavailable product is nonsense. 

#### Steps to Reproduce

1. Go to a category
2. Click on a filter
3. Scroll down to a product that is not available for that filter
4. The product should not be visible.

#### Additional information

* PrestaShop version:  1.7.6.8
* PHP version: 7.3
* ps_facetedsearch version: v3.6.0

See users complaining about this here on the forum:
https://www.prestashop.com/forums/topic/439255-only-display-attributes-available-in-stock-on-filter-blocklayered/

**Comment by matks** [comment] 2020-11-23 13:32
Hi @Spir it is probably not related to your bug report but be careful: PS 1.7.6.8 is not 100% compatible with php7.3 😉  you might want to downgrade your PHP version

**Comment by Spir** [comment] 2020-11-23 13:38
> Hi @Spir it is probably not related to your bug report but be careful: PS 1.7.6.8 is not 100% compatible with php7.3 wink you might want to downgrade your PHP version

Yes you are right I should downgrade. I tought I had the last version when checking the requirement.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by hibatallahAouadni** [comment] 2020-11-23 14:14
Hello @Spir 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16952. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-11-23 14:15
Duplicate of #16952

**Closed as completed by hibatallahAouadni** 2020-11-23 14:14 UTC
Labels: Duplicate
