### ISSUE TITLE
Autoupgrade - BO - A page not found error related to the controller is missing or invalid in different pages after an upgrade from 1.7 to 8.0

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29699] opened 2022-09-20 09:08 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is reported here in this [comment](https://github.com/PrestaShop/autoupgrade/pull/504#pullrequestreview-1107809323) (Issue2).

An error related to the controller is missing or invalid in these pages after an upgrade from 1.7.7.8, 1.7.8.7 to 8.0.0 and 1.7.7.8 to 1.7.8.7

When delete modules **with uninstalling them from BO > Module manager** : 

**Only on the Merchant Expertise page** : NOK :x: 

![image](https://user-images.githubusercontent.com/92912932/192316931-fa1b7300-4b23-4459-97fb-054cf41ce853.png)

https://user-images.githubusercontent.com/92912932/192319749-1e1cfd43-057f-4815-8459-466fa73dbae1.mp4

https://user-images.githubusercontent.com/92912932/192319869-f742e410-dc5a-4590-a78b-f2ddd22943c5.mp4

When delete modules **without uninstalling** them from BO > Module manager : 

https://user-images.githubusercontent.com/92912932/192321210-8bc2b6a9-e253-4859-abd9-feed7f88841c.mp4

**Merchant Expertise : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/191212749-d97c354e-a433-4499-b8f7-336735a20408.png)

Upgrade from 1.7.7.8 to 1.7.8.7
![image](https://user-images.githubusercontent.com/92912932/191213062-8347c085-9174-4435-9a10-c823fda9e658.png)

Upgrade from 1.7.7.8 to 8.0.0
![image](https://user-images.githubusercontent.com/92912932/191215122-be822777-9e48-4822-9cf2-053034e27bca.png)

### Expected behavior

The merchant Expertise should be OK

### Steps to reproduce

1. Install PS1778 OR PS1787
2. Uninstall merchant expertise module when uninstalling them from BO > Module manager
3. Install the autoupgrade v4.15 module from dev branch
4. Install a new 8.0.x branch
5. Create a release from 8.0.0
6. Configure the autoupgrade module
7. Upgrade to 8.0.0 branch
8. Check the 8.0.0 is well upgraded
9. GO to BO > CONFIGURE > Shop parameters > Merchant Expertise
10. See error ==> related to the controller is missing or invalid of  Merchant Expertise

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Autoupgrade v4.15.0 from dev branch

**Comment by hibatallahAouadni** [comment] 2022-09-26 19:16
Hello @HanaRebaiQA 

I reproduce the issue after upgrading 1.7.7.8 to 8.0.0 with 1-Click upgrade module v4.15.0 (dev branch), see the attached screen record below:

https://user-images.githubusercontent.com/23308427/192360832-510246a5-7ea3-410a-91be-80515afa7947.mp4

Thanks for reporting the regression, I will add to the backlog to be fixed.

PS: you may notice that I tried to reproduce all the reported regressions by you in the same record :sweat_smile: 

Thanks!

**Comment by HanaRebaiQA** [comment] 2022-09-30 12:21
Hello, 

When testing with 8.0.0 RC build1, i was able to reproduce the errors in theses pages (As mentioned previously in the description): 

BO > SELL > Stats pgae 
BO > SELL > Stats > PrestaShop Metrics 
BO > Advanced parameters > Merchant expertise 

1. Enable the Disable non-native module option
2. Do not uninstall the problematic modules
3. Use the release of autoupgrade.zip (v4.15)
4. Upgrade from PS1778 to PS8.0.0
5. Check the pages 
6. BO > SELL > Stats pgae : NOK
7. BO > SELL > Stats > PrestaShop Metrics : NOK
8. BO > Advanced parameters > Merchant expertise : NOK


https://user-images.githubusercontent.com/92912932/193267977-28806cb8-b7ac-4627-88ef-a2fcb768bb75.mp4

Thank You!

**Comment by HanaRebaiQA** [comment] 2023-03-03 16:05
Hello again, 

I still reproduce the issue following the upgrade from PS1788 to PS8.0.2 on : 

- Stats (Stats and prestaShop Metrics) pages  
- Merchant Expertise page


https://user-images.githubusercontent.com/92912932/222768823-a317f24c-97ab-44f4-a4ee-7de9508f528c.mp4


![image](https://user-images.githubusercontent.com/92912932/222771812-a74f9c81-cc98-4e6c-998c-cd261e626499.png)

Thank You!

**Comment by ga-devfront** [comment] 2024-05-20 14:53
I tried to reproduce the issue starting from 1.7.8.8 to the latest version 8.1.6 and I cannot reproduce it. Request for a QA test to determine whether to continue investigating this ticket or close it.

**Comment by ga-devfront** [comment] 2024-07-31 16:00
The issue cannot be reproduced on the latest version of the module.

**Closed as completed by ga-devfront** 2024-07-31 16:00 UTC
Labels: Bug, 8.0.x, Trivial, BO, Needs Specs, Stats, Shop parameters, Merchant expertise, Regression, Autoupgrade, Verified, Module, Backlog SUE
