### ISSUE TITLE
Cannot generate Invoices

### ISSUE THREAD

**Issue by jaweewo** [PrestaShop/PrestaShop#25811] opened 2021-09-08 07:53 UTC
#### Describe the bug

Since i upgraded to prestashop 1.7, i can't generate the invoices, it returns me "Invalid $number parameter: "" cannot be interpreted as a number

[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]" 

I Found out its problem of Formatter.php. but cannot fix the problem.

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on 'Invoice'
3. Generate Invoice

**Screenshots**
![image](https://user-images.githubusercontent.com/35831933/132469217-c39842e9-19ab-4ced-a675-259b2bf0cf8d.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.5
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment] 2021-09-08 08:45
Hello @jaweewo 

I didn't manage to reproduce the issue, please check these similar issues #23724 & #22108
Please check and feedback.

Thanks!

**Comment by jaweewo** [comment] 2021-09-08 09:06
> Hello @jaweewo
> 
> I didn't manage to reproduce the issue, please check these similar issues #23724 & #22108
> Please check and feedback.
> 
> Thanks!

I check them out but none of them are my case, i have no special products or special prices.

I was on prestashop 1.6.13, i did export my Database tables to a new prestashop 1.7.5, i can see the products without problems and people can buy but i cannot gen or see the invoice.
as extra, i paste here an invoice example when printing, look the description: 
![image](https://user-images.githubusercontent.com/35831933/132480355-5064a59e-5fa7-43f2-9d1c-b2082f074dc6.png)
The php function in that line is this:
    public function format($number, NumberSpecification $specification)
    {
        $this->numberSpecification = $specification;

        try {
            $decimalNumber = $this->prepareNumber($number);
        } catch (SPLInvalidArgumentException $e) {
            throw new LocalizationException('Invalid $number parameter: ' . $e->getMessage(), 0, $e);
        }

**Comment by hibatallahAouadni** [comment] 2021-09-08 17:28
Hello @jaweewo 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12626. 
And it's already fixed with this PR #12666

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-08 17:28
Duplicate of #12626

**Closed as completed by hibatallahAouadni** 2021-09-08 17:28 UTC
Labels: Bug, 1.7.5.x, BO, Duplicate, Order, Invoices
