### ISSUE TITLE
Faceted search | Keep selected filters on top of product list, if no products

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14742] opened 2019-07-18 12:56 UTC
**Describe the bug**
Active filters disappear from the top of the product list, if no products are found for current filters.

https://drive.google.com/file/d/1sZ3FnoIsaRXGjGM706bv7XzfyQ4Tzs23/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.6
Faceted search: 3.1.0

**Comment by khouloudbelguith** [comment] 2019-07-18 13:36
Hi @Hlavtox,

I did not manage to reproduce the issue with PS1.7.6.0 & The ps_facetedsearch v3.1.0.
I attached a screen record
https://drive.google.com/file/d/1-LySj8-WngM4TON7PWB2kg_zOVsDELjb/view

Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-19 07:45
Hi @Hlavtox,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-19 07:45 UTC
Labels: Bug, FO, Faceted search, No change required, 1.7.6.0
