### ISSUE TITLE
Prestashop 1.7.6.1 Validation Error on Using Voucher in Cart

### ISSUE THREAD

**Issue by cma93** [PrestaShop/PrestaShop#15742] opened 2019-09-29 19:51 UTC
When add the voucher code in Cart and checkout using Bankwire (don't have any other payment method yet). It gives me an error on shopaddress/module/ps_wirepayment/validation

La proprietà CartRule->quantity_per_user non è valida

The CartRule-> quantity_per_user property is not valid

Thanks.

**Comment by khouloudbelguith** [comment] 2019-09-30 10:48
Hi @cma93,

I did not manage to reproduce the issue with PS1.7.6.1 & ps_wirepayment v2.0.4.
What is the exact version of the module ps_wirepayment did you use?
In the Cart rule page => Condition Tab => what is the exact value of `Total available` & `Total available for each user`?
![image](https://user-images.githubusercontent.com/16067358/65872300-2ce07900-e378-11e9-8c82-a898139ce823.png)

Thanks!

**Comment by cma93** [comment] 2019-09-30 10:54
Thanks for your reply.
Prestashop 1.7.6.1
Module 2.0.4
![Screenshot (5)](https://user-images.githubusercontent.com/34143433/65872704-db40ea00-e389-11e9-8f51-9bba76d42b01.png)

**Comment by cma93** [comment] 2019-09-30 10:58
I tired to change this as well. but same response.

**Comment by cma93** [comment] 2019-09-30 11:30
![WhatsApp Image 2019-09-29 at 5 29 44 PM (1)](https://user-images.githubusercontent.com/34143433/65874677-cb77d480-e38e-11e9-80d0-d117898ea247.jpeg)

here's the error that I receive.

**Comment by cma93** [comment] 2019-09-30 12:25
I just checked. Order is being placed but I get "500 internal server error" (Debug mode is off).

Any idea what's wrong here?
Thanks.

**Comment by khouloudbelguith** [comment] 2019-09-30 12:56
@cma93, it is Ok in my case.
https://drive.google.com/file/d/19ie8cWURLGsL8tSOFz7YjCC_q-sgArDH/view
Could you please try to re-install the ps_wirepayment module by removing it during the uninstall & clearing the cache.

Thanks!

**Comment by cma93** [comment] 2019-09-30 13:12
same error here
![Screenshot (6)](https://user-images.githubusercontent.com/34143433/65882025-fff28d00-e39c-11e9-8627-64d4412ed7e6.png)

would you like to checkout my environment?

**Comment by cma93** [comment] 2019-09-30 13:13
I have changed the default location settings as well (if that may cause any problem).

**Comment by khouloudbelguith** [comment] 2019-09-30 13:16
@cma93, what is the exact action provided by this cart rule (Discount amount, free shipping, gift,...)?

Thanks!

**Comment by cma93** [comment] 2019-09-30 13:19
![Screenshot (7)](https://user-images.githubusercontent.com/34143433/65882611-08979300-e39e-11e9-8d16-3a79ca98f522.png)

Here you go

**Comment by khouloudbelguith** [comment] 2019-09-30 14:22
@cma93, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by cma93** [comment] 2019-09-30 14:39
Sent

**Comment by khouloudbelguith** [comment] 2019-09-30 14:41
@cma93, I just received the email.
I will check & feedback.

**Comment by khouloudbelguith** [comment] 2019-09-30 15:17
@cma93, In the BO => An alert, is displayed when I try to disable a cart rule
![image](https://user-images.githubusercontent.com/16067358/65892131-aa6ab000-e39d-11e9-94e7-bf7d557b8ee0.png)
Have you any custom module related to the cart rules?
Thanks!

**Comment by cma93** [comment] 2019-09-30 15:18
I don't think so

**Comment by cma93** [comment] 2019-09-30 15:19
I don't think so. you can check

**Comment by khouloudbelguith** [comment] 2019-09-30 15:22
@cma93, the first cart rule with ID=1 is created manually?

Thanks!

**Comment by cma93** [comment] 2019-09-30 15:23
Actually I don't remember

**Comment by khouloudbelguith** [comment] 2019-09-30 15:25
@cma93, can I deleted it & re-create the same cart rule manually?

Thanks!

**Comment by cma93** [comment] 2019-09-30 15:26
Do as you please! Thank you for looking out my problem

**Comment by khouloudbelguith** [comment] 2019-09-30 15:48
@cma93, I found the whole issue.
The quantity in your case is invalid
![image](https://user-images.githubusercontent.com/16067358/65894463-bfe1d900-e3a1-11e9-85cc-79dd4fce3a2c.png)
As you can see in this screenshot, the quantity is displayed with decimals which is incorrect.
![image](https://user-images.githubusercontent.com/16067358/65894637-fc153980-e3a1-11e9-9424-65a41008d5b7.png)
Thanks to change the Type of your quantity from your database, it should be like this
![image](https://user-images.githubusercontent.com/16067358/65894715-21a24300-e3a2-11e9-93d4-6ae44e72ad01.png)
Thanks to check & feedback.

**Comment by cma93** [comment] 2019-09-30 16:09
Thanks. I changed it and it worked. 

I have a question: I didn't alter anything in the DB then why it had decimal, do you have any idea?

Thanks again! You're a Pro

**Comment by khouloudbelguith** [comment] 2019-10-01 16:03
@cma93, Thanks!
You are welcome!
Sorry, I don't know the exact issue.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-01 16:03 UTC
Labels: Bug, FO, Discounts, Cart rules, Bankwire, No change required, 1.7.6.1
