### ISSUE TITLE
Edit a product image result in an error: function(){return r&&o(s,r),(e.migrateIsPatchEnabled(s)?i:a||e.noop).apply(this,arguments)}

### ISSUE THREAD

**Issue by mcrielaard** [PrestaShop/PrestaShop#34724] opened 2023-11-29 07:42 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you change the text of a product image and press save, an error message will be displayed: function(){return r&&o(s,r),(e.migrateIsPatchEnabled(s)?i:a||e.noop) .apply(this,arguments)}

### Expected behavior

No error :-)
![error](https://github.com/PrestaShop/PrestaShop/assets/2943804/4c74a58c-4cb0-49b0-9fcb-14e5ea63a10a)

### Steps to reproduce

1 Go to product and open the images.
2 Change some text and press save
3 error is shown

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

Martin Crielaard

**Comment by florine2623** [comment] 2023-11-29 08:56
Hello @mcrielaard ,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

<img width="705" alt="Screenshot 2023-11-28 at 16 25 54" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b8af02d1-94d8-4e58-b7a6-895a316f9492">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by jix31** [comment] 2023-11-29 09:46
@florine2623  you reproduce this error mentioned by @mcrielaard , but this is the same error that I talk about in #34646, and you close my #34646 because you can't reproduce it ... it's strange  

So I hope you will reconsider your decision and re-open my case ?

**Comment by mcrielaard** [comment] 2023-11-29 10:07
I'm sorry @jix31 didn't noticed your bug report. Stange that it is closed. It's obviously a bug.

**Comment by jix31** [comment] 2023-11-29 10:14
@mcrielaard there is now 4 items about this bug , but no first steps to correct it

yes it's strange that it is closed

**Comment by AdrienPlx** [comment] 2023-12-06 16:28
Same bug for me !

**Comment by jix31** [comment] 2023-12-07 07:04
at least  5 reports of this bug on github now

**Comment by mcrielaard** [comment] 2023-12-07 07:54
I hope it will be fixed soon because this right now it is a show stopper for me.

**Comment by AdrienPlx** [comment] 2023-12-07 08:41
Hi all, to quick fix this you can go back to the product form V1 in Advanced parameters > New functionnalities to disable the "new product page" feature : 
![image](https://github.com/PrestaShop/PrestaShop/assets/43446598/08bcd825-95be-40b1-aed6-372a147e0784)

**Comment by hannes01** [comment] 2024-02-17 08:45
Hello,

yes, same for me too (in 8.1.3 production site and  also in 8.0.4 Presta demo site). There are several reports regarding this in Github and also found one in Presta forum.

New product page was the main reason I upgraded to 8.1

Kindly asking to fix this, thanks.

**EDIT: was able to "fix this" by changing the Nginx profile.**

**Comment by TamasFelix** [comment] 2024-03-07 20:00
I encountered a similar issue on the website [www.fashionland.ro](url)
function(){return r&&o(s,r),(e.migrateIsPatchEnabled(s)?i:a||e.noop).apply(this,arguments)}
The problem occurred when I edited or added another image to the representative image. I re-uploaded the images to re-establish the connection and activated the old version of product editing.

One of the major issues is that the modified or deleted images in the database (DB) persist in the table.

The problem originates from the new core version; the links are not properly established.

**Comment by mathieustankiewicz** [comment] 2024-03-15 09:11
The problem is related to the fact that the new product page uses a PATCH type request, generally disabled on Apache/Nginx, when modifying images.

Allowing PATCH requests at the web server level resolves the issue.

It's strange, however, that such an important feature of the new product page relies on a method that is generally disabled by default by hosts.

**Closed as completed** 2024-03-26 08:48 UTC
Labels: Bug, Minor, BO, Topwatchers, Verified, 8.1.x, Products Page
