### ISSUE TITLE
Cannot save product information in back office

### ISSUE THREAD

**Issue by Falataya** [PrestaShop/PrestaShop#10902] opened 2018-10-08 10:03 UTC
I cannot save porduct information in the back office. When I edit/add information on a product and click Save and stay I'm redirected to the product list and the information is not saved. I need to repeat the adding/editing and saving up to 10 times before it is finally saved. The worst section appears to be editing combinations of attributes (e.g. choosing which picture goes with a certain combination). 

I have a good internet connection and the website (the front office) works fine.

1. Go to Products
2. Select a product
3. Click Combinations --> edit a combination
4. Change something
5. Save and stay
-> The change is not saved.

PrestaShop version: 1.6.1.1.

Thank you for your help!

**Comment by khouloudbelguith** [comment] 2018-10-08 10:18
Hi @Falataya,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- debug mode report
- PHP error logs
- apache error log
- javascript console log

Don't you know how to get this information? Please read the following article:

**Adding logs**
Sometimes you just don’t know what’s wrong: something’s not happening, that’s all.

That’s where log data can be helpful. They keep track of what is happening and allows to trace back to the moment when the issue happens.

There are several different log data that you can add as a file to your ticket:

**Server log:**
Apache: /var/log/apache/apache_error.log
Nginx: /var/log/nginx/nginx_error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles
**PHP error log:**
Apache: /var/log/apache/php_error.log
Nginx: /var/log/php-fpm/default/error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles
**Console log:**
Firefox and Chrome: press Ctrl+Shit+J or Cmd+Shift+J.
Internet Explorer and Edge: press F12 then go to the Console tab.
Copy the content relevant to your issue (or to the time the issue appeared), and paste it into the ticket (or in a text file attached to the ticket).

Enabling Debug Mode + cache
PrestaShop has a debug mode, which can be used to see the non-obvious errors in your shop. For instance, in these situations:

The browser displays a blank page.
The browser displays a 500 Internal Server Error.
You cannot log into your dashboard, or access certain pages of the back office.
To turn on the Debug mode on PrestaShop, follow these steps using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

define('PS_MODE_DEV', false);

… and change it to:

define('PS_MODE_DEV', true);

Finally, emptying the cache of PrestaShop can also be useful, because it ensures that your browser only displays newly-generated files instead of old cached ones. In PrestaShop, you can empty the cache here:

Go to Advanced Parameters > Performance.
Click on the “Clear Cache” button at the top right.

Thanks!

**Comment by Falataya** [comment] 2018-10-09 20:27
For now I switched to Firefox and it appears that there is no problem there. 
I will try to get the additional information that you require once I have more time so that you can take a look at what's going on.

Thank you!

**Comment by khouloudbelguith** [comment] 2018-10-10 08:15
@Falataya, Thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2018-11-13 11:34
@Falataya, any news?
Thanks!

**Comment by khouloudbelguith** [comment] 2018-12-14 17:19
Hi @Falataya,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-14 17:19 UTC
Labels: Bug, BO, No change required
