### ISSUE TITLE
Error when generating credit invoices

### ISSUE THREAD

**Issue by PalomaDiPierro** [PrestaShop/PrestaShop#30910] opened 2023-01-17 12:51 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
When I generate a return invoice and add the shipping I get an error in the percentage.

I enclose invoice and return invoice

### Expected behavior

generate correct returns invoices

### Steps to reproduce

credit invoices
![error factura abono buckerbook-01](https://user-images.githubusercontent.com/112171310/212903146-06c19a26-0bef-4701-9276-da5ffddcab89.jpg)
![error factura abono buckerbook-02](https://user-images.githubusercontent.com/112171310/212903151-c3486357-8a9c-4dfc-b4b1-56d0ab8a4ebd.jpg)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3.33

**Comment by sallemiines** [comment] 2023-01-17 16:13
Hello @PalomaDiPierro 

Thanx for reporting the issue.

Please provide clear and concise steps to reproduce the issue ! 

Thank you !

**Comment by hibatallahAouadni** [comment] 2023-02-05 22:31
Hello @PalomaDiPierro 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2023-02-05 22:31 UTC
Labels: Bug, BO, Invoices, Invalid, 1.7.8.7
