### ISSUE TITLE
If set only one non EUR currency, still EUR appears on some places in BO

### ISSUE THREAD

**Issue by JirkaDeLucina** [PrestaShop/PrestaShop#11018] opened 2018-10-15 20:41 UTC
I have only one currency in BO: International - Localization - Currency
CZK / 203

On same places in BO is shown EUR:
Orders - detail of any Order - in Payment section
Catalog - Products - detail of any Product - tab Price - in Special prices - add Special price - in selector are % and also EUR

**Screenshots**
![image](https://user-images.githubusercontent.com/43830505/46976501-f1e32800-d0c9-11e8-8842-ecb658e2b101.png)

![image](https://user-images.githubusercontent.com/43830505/46976615-45557600-d0ca-11e8-98f3-844c062f86ca.png)

![image](https://user-images.githubusercontent.com/43830505/46977006-433fe700-d0cb-11e8-956d-d5f8fa9d3f85.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2018-10-16 08:13
Hi @JirkaDeLucina,

We aware of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9876
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-16 08:13
Duplicate of #9876

**Closed as completed by khouloudbelguith** 2018-10-16 08:13 UTC
Labels: Duplicate
