### ISSUE TITLE
Incompatibility of the tax rule area with prestashop multishop

### ISSUE THREAD

**Issue by pollat** [PrestaShop/PrestaShop#36057] opened 2024-04-30 08:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I verified taht tax rules area of PrestaShop is not compatible with the multi-shop: on a prestashop multishop, if I modify a tax rule on a specific shop (for example insering some countries or setting specific tax for some countries), the modification is trsmitted on all shops and not just on the selected shop. This is a big problem because we cannot menage products catalogue on all shop mode if shops need different tax. 

### Expected behavior

I expected that on multishop, if I set a specific shop in the tax rules area, the change will only apply to the shop I selected and not be transmitted to all shops.

### Steps to reproduce

1) create a multishop with 2 shops;
2) go to tax rules area and create a specific tax rule
3) try to modified the new tax rules, selecting a specific shop (so not on "All shop" mode)
4) the editing you made, is trasmitted on all shop and not only on the specific shop you selected

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.3

**Comment by pollat** [comment] 2024-05-08 09:25
???

**Comment by florine2623** [comment] 2024-05-14 10:01
Hello @pollat 

I can't reproduce your issue as you can see :

https://github.com/PrestaShop/PrestaShop/assets/16019289/ac6c2703-122b-45a9-bb4a-7574ebac3a04

You need to check what you want in each shop.

i'm closing the issue as it cannot be reproduced.

**Closed as completed by florine2623** 2024-05-14 10:01 UTC
Labels: Bug

**Comment by pollat** [comment] 2024-05-28 08:43
> Hello @pollat
> 
> I can't reproduce your issue as you can see :
> 
>  Screen.Recording.2024-05-14.at.11.59.27.mov 
> You need to check what you want in each shop.
> 
> i'm closing the issue as it cannot be reproduced.

Easy steps to reproduce this bug:
1) create a multishop with 2 shops;
2) go to tax rules area and create a tax rule
3) modified the new tax rule created selecting a specific shop (so doesn't select "All shop" mode) 
4) the editing you made, is trasmitted on all shop and not only on the specific shop you selected
