### ISSUE TITLE
Multishop Default combinations not reassigned if you delete it 

### ISSUE THREAD

**Issue by giuliopowa** [PrestaShop/PrestaShop#12244] opened 2019-01-21 15:14 UTC
Multishop Default combinations not reassigned if you delete it 

Preparation:

- Fresh installation of prestashop (for example version 1.7.5.0) ( the problem persists from version 1.6.x.x)
- MultiShop with minimum 2 shops (example "Hello1" and "Hello2)

Execution:

- Go to the Back Office, select a product (for example the product with reference "demo_5")
- In the Back Office select one of the shop ( for example "hello1" ) and go to the paragraph combinations
- Delete the default combination and save, and you will see that no other default combination is re-assigned
- Now if you want to assign another default combination you can not do it anymore

Additional information:

- If you delete the default combination in "All shop" mode, then the default combination is automatically re-assigned

**Comment by khouloudbelguith** [comment] 2019-01-21 16:10
Hi @giuliopowa,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
https://drive.google.com/file/d/1nkNF5z4PLm_CyzPAaHs-OM6Z5JcYaplD/view
We will see how to fix it.
Thanks!

**Comment by MatShir** [comment] 2023-07-04 16:21
It seems to be fixed on the new product page on PS 8.1 :)

**Closed as completed by MatShir** 2023-07-04 16:21 UTC
Labels: Bug, Minor, BO, Multistore, Combinations, 1.7.5.0, Verified
