### ISSUE TITLE
ps_facetedsearch keeps out of stock products with attributes

### ISSUE THREAD

**Issue by JustasBelevicius** [PrestaShop/PrestaShop#15117] opened 2019-08-14 18:10 UTC
**Describe the bug**
If a product has a variant that matches the filter, but that exact variant is out of stock, the filter shows the product in the category listing (Front Office)

**Expected behaviour**
example: If product has sizes and quantities S-0 / M-5 / L-5, filtering that products categorie to size S shouldn't show the product with empty stock of size S

**To Reproduce**
1. Create a product with two or more variants
2. Set quantity field of one variant to 0 and rest to any number
3. Turn on filtering by the attribute which the variant is using
4. Go to front office, to the category of the product, filter products by the attribute by selecting the option which is out of stock.
5. See that the product appears in the listing 

**Additional information**
PrestaShop version: 1.7.6

**Comment by mariem-abid** [comment] 2019-08-15 08:48
Hi @JustasBelevicius,

I manage to reproduce the issue with the last version PS 1.7.6.0 and the module ps_facetedsearch v3.2.0.
I attached a video record.
https://drive.google.com/file/d/1Y9OxQZIDrmvtaiB3P1ck1bsyktMshgMC/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by JustasBelevicius** [comment] 2019-08-15 10:03
Thanks for a swift response. I did not manage to fix it myself, hence I logged this issue.
When can I expect a faceted search module update?

**Comment by mariem-abid** [comment] 2019-08-15 10:29
@JustasBelevicius, it will be soon.

**Comment by marionf** [comment] 2019-08-16 07:39
Hello @JustasBelevicius 

Your issue is a duplicate of #15056 so I close it.
Please follow the other issue

Regards

**Closed as completed by marionf** 2019-08-16 07:39 UTC
Labels: Bug, Major, Duplicate, Faceted search, Combinations, 1.7.6.0
