### ISSUE TITLE
After Upgrade from PS1.7.4 to 1.7.5  hookDisplayAdminProductsExtra Modules not loading for old Articles

### ISSUE THREAD

**Issue by IAmWebSA** [PrestaShop/PrestaShop#12576] opened 2019-02-14 17:27 UTC
Hello,

 

I have a issue with a customers Shop where my Module is used.

The customer did a upgrade to 1.7.5 and now the Module (which is hooked to hookDisplayAdminProductsExtra shown in the Article at Modules Section). Does not load anymore.

The only response I can see is "Settings successfully updated", but the module Tab did not open or anything else.

Same happens to other modules which are hooked to hookDisplayAdminProductsExtra. 

**The interesting part is that the customer did a upgrade and afterwards the alread existing Articels did not work anymore with the Modules.
BUT, by adding a new article the Modules Section works for the newly added articels.**

**Comment by khouloudbelguith** [comment] 2019-02-15 07:35
Hi @IAmWebSA, 

Have you the same issue with this ticket: #11911? 
If yes, here's the PR: #11923 to fix the issue.
It is fixed in the next release PS1.7.5.1.
Thanks to check & feedback.

**Comment by IAmWebSA** [comment] 2019-02-19 11:39
Hello,

no that is not the same issue. The issue appears only for old products, it calls ajax after Configure button is pressed and instead of switching to the modules section it just states a notification with "Settings successfully updated".

**Comment by khouloudbelguith** [comment] 2019-02-19 12:13
Hi @IAmWebSA,

Could you please provide me with a screen recording of your issue, it will help us to understand the exactly problem. 
Thanks!

**Comment by IAmWebSA** [comment] 2019-02-19 18:33
@khouloudbelguith . I have attached the captures with working and not working example. Both captures are from the same shop.
[Captures.zip](https://github.com/PrestaShop/PrestaShop/files/2881447/Captures.zip)

**Comment by IAmWebSA** [comment] 2019-02-19 18:56
After a closer look to the  Firefox  Debug I saw the following:
`Error: Syntax error, unrecognized expression: 
### ▷ ✓ Top-Marken ✓ Top-Produkte ✓ Top-Service ✓ Fair und preiswert bei ✓   
main.bundle.js:275:78873
error https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    tokenize https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    select https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    t https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    find https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    init https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    De https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    i https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    value https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    e https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    <anonym> https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:419
    u https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
    c https://www.shop.de/adminXXXXX/themes/new-theme/public/main.bundle.js:275
`


After pulling the theme "new-theme" from github, the issue still appears and fails with Settings could not be updated (red notification)


**I also double checked the articles and if I add the SEO to the previous working article it also stops working:**

"▷ A| B| C◁ ✓ Top-Marken ✓ Top-Produkte ✓ Top-Service ✓ Fair und preiswert bei ✓"

**Comment by khouloudbelguith** [comment] 2019-02-20 10:26
Hi @IAmWebSA,

Thanks for your feedback.
In fact, your issue is the same reported here; https://github.com/PrestaShop/PrestaShop/issues/11911#issuecomment-449714318
In the Tab module, if we click on configure => nothing happens for old products only.
About your console log, it is the same error provided by le in this comment: https://github.com/PrestaShop/PrestaShop/issues/11911#issuecomment-449714318
here's the PR: #11923 to fix the issue.
It is fixed in the last release PS1.7.5.1.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-02-20 10:26
Duplicate of #11911

**Closed as completed by khouloudbelguith** 2019-02-20 10:26 UTC
Labels: BO, Duplicate, 1.7.5.0

**Comment by IAmWebSA** [comment] 2019-02-20 10:36
@khouloudbelguith  You say it is fixed by #11923, but if I use the "new-theme" from github mainline the error still exists. As I see the fix was already merged to Mainline.

So why does it still not work? any other changes needed ?

**Comment by khouloudbelguith** [comment] 2019-02-20 10:42
@IAmWebSA, did make an upgrade to PS1.7.5.1? or did you applied the patch in your code?
Thanks!

**Comment by IAmWebSA** [comment] 2019-02-20 10:51
@khouloudbelguith I had replaced the complete folder of the "new-theme" with the one from the github.
So no upgrade to 1.7.5.1 just added new theme

**Comment by khouloudbelguith** [comment] 2019-02-20 10:54
@IAmWebSA, did you copied this folder https://github.com/PrestaShop/PrestaShop/tree/1.7.5.1/admin-dev/themes/new-theme from the PS1.7.5.1 tag?
Thanks!

**Comment by IAmWebSA** [comment] 2019-02-20 11:40
@khouloudbelguith I used the version from the develop branch.

**Comment by khouloudbelguith** [comment] 2019-02-20 11:42
@IAmWebSA, the fix exists in the PS1.7.5.1 version.
You should use this one.
Or you can download the Stable version PS1.7.5.1 from our official link & copy paste the folder.
Thanks!

**Comment by IAmWebSA** [comment] 2019-02-21 14:34
@khouloudbelguith  THnaks for the Link, now it seems to work as I can see.
My mistake I thoguht the dev branch has also the same fixes like the sub branches.

=> CLOSE and verified with theme from 1.7.5.1
