### ISSUE TITLE
Order page 500 error "FastCGI: incomplete headers (0 bytes) received from server"

### ISSUE THREAD

**Issue by willy2m** [PrestaShop/PrestaShop#10423] opened 2018-09-13 13:46 UTC
Error 500 "internal server error" when the user gets to ckeckout, next step after filling adress details. (page salesdeplata.com/order)
No matter what user, identified or not, it gets to the 500 error.

WEB log gives me this error: "FastCGI: incomplete headers (0 bytes) received from server "/fcgi-bin-php56-fpm-ssl-salesdeplata.com"

PrestaShop version: 1.7.2.5
PHP version: 5.6.32

**Comment by khouloudbelguith** [comment] 2018-09-13 13:48
Hi @willy2m,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-13 14:02
HI

Server setup annd config

**PHP INFO**
Host info: Linux #1 SMP Debian 3.2.82-1 x86_64
Host Sofware: Apache
PHP Version: 5.6.32
Memory limit: 320M
Max. execution time: 40
Max. file upload size: 30M

**SHOP INFO**
Prestashop version: 1.7.2.5
Shop URL: http://salesdeplata.com/
Theme: alysum

**MYSQL Info**
Versión de MySQL: 5.5.57-0+deb7u1-log
Host MySQL: localhost
Database MySQL: ps-sales
User MySQL: mysalesdep
Prefix: ps_
Motor MySQL: InnoDB
Controler MySQL: DbPDO

Doesn't matter the browser and os, tried it on different computer but i get the same error.

**I have the debug mode enabled but I dont get any report when I get to the error message/page. Just error 500 in "salesdeplata.com/order" page.**

**Web error log** from the server gives me this two errors:
[Thu Sep 13 16:00:25 2018] [error] [client 77.231.7.84] (104)Connection reset by peer: FastCGI: comm with server "/fcgi-bin-php56-fpm-ssl-salesdeplata.com" aborted: read failed
[Thu Sep 13 16:00:25 2018] [error] [client 77.231.7.84] FastCGI: incomplete headers (0 bytes) received from server "/fcgi-bin-php56-fpm-ssl-salesdeplata.com"

No PHP errors

Thanks !

**Comment by khouloudbelguith** [comment] 2018-09-13 14:05
Hi @willy2m,

This error, in particular, is generally caused by an idle_timeout (30 seconds by default) or max children processes limit. It can also be caused by someone starting a long-running script and closing their browser/connection before the script completes.
Have you tried to contact the host provider?

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-13 14:09
Hi @khouloudbelguith 
I will try to solve the problem with the host provider. But, should I change the max execution time value to 30 ?

Thanks

**Comment by khouloudbelguith** [comment] 2018-09-13 14:29
Hi @willy2m,

No, it is by default: 30.

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-13 14:42
Hello @khouloudbelguith 
I contacted the host provider and we fixed the debug error. Now the order page gives me this error:
<img width="1003" alt="captura de pantalla 2018-09-13 a las 16 40 41" src="https://user-images.githubusercontent.com/43242372/45495639-eec7e580-b773-11e8-8cc9-9905ca583998.png">

Thanks

**Comment by khouloudbelguith** [comment] 2018-09-13 14:45
Hi @willy2m,

Could you please try to clear cache manually by deleting all the folder into app/cache (prod & dev).
Thanks to check and feedback.

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-13 15:02
Hi @khouloudbelguith 

I have deleted the prod & dev folders in app/cache
Same error:
<img width="996" alt="captura de pantalla 2018-09-13 a las 17 00 45" src="https://user-images.githubusercontent.com/43242372/45496867-ae1d9b80-b776-11e8-8e48-00e32a1f2965.png">

**Comment by khouloudbelguith** [comment] 2018-09-13 15:20
Hi @willy2m,

Did you delete any addresses from the Database?

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-13 15:24
Hi @khouloudbelguith 
I had a DHL Express module, wich i uninstalled yesterday, deleting allso al the databases that started "ps_dhl..."
This is the only thinng I deleted in the database.

**Comment by khouloudbelguith** [comment] 2018-09-13 15:27
Hi @willy2m,

After deleting those tables, this issue occurs?

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-13 15:39
Hi @khouloudbelguith 
Nope, i deleted them because I thought the error was caused by the module. I was having the error before

**Comment by khouloudbelguith** [comment] 2018-09-13 16:00
Hi @willy2m,

Have you tried to contact the theme author?

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-13 17:57
Hi @khouloudbelguith 

I am in conntact with him, the error seems to be in the templates, doesnt it ?

I will keep this updated with the details

Thanks

**Comment by khouloudbelguith** [comment] 2018-09-14 07:58
Hi @willy2m,

As it comes from a theme not provided by PrestaShop, I don't think we can do something before their feedback.

Best regards, Khouloud

**Comment by willy2m** [comment] 2018-09-14 10:24
Hi @khouloudbelguith ,

I just want to thank you for all the guiding, it was a problem with the theme. I would have gotten crazy without your help 

:D

**Comment by khouloudbelguith** [comment] 2018-09-14 10:28
Hi @willy2m,

You are welcome.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-09-14 10:28 UTC
Labels: FO, No change required

**Comment by davideapvd** [comment] 2018-11-09 14:15
> Hi @khouloudbelguith ,
> 
> I just want to thank you for all the guiding, it was a problem with the theme. I would have gotten crazy without your help
> 
> :D

@willy2m can you please describe what you do to fix this error? we have a similar error with the same dhlexpress module.
from what I understand the module interates upon product['quantity'] from $cart->getProducts() but when we are in the /order page ['quantity'] contains the product quantities in the warehouse (and we have a lot here). So probably the module should always iterate upon ['cart_quantity'] is this correct?

   /modules/dhlexpress/dhlexpress.php

```
public function getCartPieces($products, $withQuantities = true)
    {
        $productsParam = array();
        foreach ($products as $product) {
            $i = 0;
    -         $qty = $product['quantity'];
    +         $qty = $product['cart_quantity'];
              if ($withQuantities) {
                    while ($i < $qty) {
```
