### ISSUE TITLE
ps_facetedsearch: filtering features

### ISSUE THREAD

**Issue by manfield** [PrestaShop/PrestaShop#13443] opened 2019-04-16 21:42 UTC
**Describe the bug**
_Feature_ type filters don't appear on frontend.

**To Reproduce**
1. Configure one or more product assigning features to it (you may use demo products)
2. Create a filter template on the ps_facetedsearch module using _feature_ as filter type for some category (or all, or one...it does not change the result)
![Module Manager • Ipertiles 2019-04-16 23-41-42](https://user-images.githubusercontent.com/397671/56246049-36fc0d00-60a1-11e9-96b5-173bd4208e95.jpg)
3. Go to frontend on product listing page for the category associated to the filter
4. No filters are shown for _feature_ filter type

**Additionnal information**
PrestaShop version: 1.7.5.1
Ps Faceted Search: 2.2.0, 2.2.1

The issue seems to be related to the way the query to extract products having _feature_ type is built.
The bug should be hidden between rows 1876 and 1896 or 1949 ad 2026 of ps_facetedsearch.php.

This query, as example result of those row never returns records.

```SELECT fl.name feature_name, fp.id_feature, fv.id_feature_value, fvl.value, COUNT(DISTINCT p.id_product) nbr, lifl.url_name name_url_name, lifl.meta_title name_meta_title, lifvl.url_name value_url_name, lifvl.meta_title value_meta_title FROM ps_feature_product fp INNER JOIN (SELECT DISTINCT cp.id_product, p.id_manufacturer, product_shop.condition, p.weight FROM ps_category c STRAIGHT_JOIN ps_category_product cp ON (c.id_category = cp.id_category AND c.nleft >= 3 AND c.nright <= 8 AND c.active = 1) STRAIGHT_JOIN ps_product_shop product_shop ON (product_shop.id_product = cp.id_product AND product_shop.id_shop = 1) STRAIGHT_JOIN ps_product p ON (p.id_product=cp.id_product) WHERE product_shop.`active` = 1 AND product_shop.`visibility` IN ("both", "catalog")) p ON p.id_product = fp.id_product LEFT JOIN ps_feature_lang fl ON (fl.id_feature = fp.id_feature AND fl.id_lang = 1) INNER JOIN ps_feature_value fv ON (fv.id_feature_value = fp.id_feature_value AND (fv.custom IS NULL OR fv.custom = 0)) LEFT JOIN ps_feature_value_lang fvl ON (fvl.id_feature_value = fp.id_feature_value AND fvl.id_lang = 1) LEFT JOIN ps_layered_indexable_feature_lang_value lifl ON (lifl.id_feature = fp.id_feature AND lifl.id_lang = 1) LEFT JOIN ps_layered_indexable_feature_value_lang_value lifvl ON (lifvl.id_feature_value = fp.id_feature_value AND lifvl.id_lang = 1) WHERE fp.id_feature = 3 GROUP BY fv.id_feature_value ```

**Comment by khouloudbelguith** [comment] 2019-04-17 09:46
Hi @manfield,

Your ticket is a duplicate of #9736
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-17 09:47
Duplicate of #9736

**Closed as completed by khouloudbelguith** 2019-04-17 09:46 UTC
Labels: Duplicate

**Comment by manfield** [comment] 2019-04-17 10:15
Hi, it is not exactly the same issue, but if you meant that the module needs a deep rework that will solve also this issue, ok.
The issue you mentioned as original of this duplicate takes in consideration other filter types actually.
Cheers!
M

**Comment by khouloudbelguith** [comment] 2019-04-17 10:30
@manfield, sorry it's a duplicate of #9736.

**Comment by manfield** [comment] 2019-04-17 11:33
Hi, sorry. The issue you mentioned is still not pertinent to mine.
Thanks
M

**Comment by khouloudbelguith** [comment] 2019-04-17 13:17
Hi @manfield, with the steps you gave me I got this result (see screenshot).
![Capture du 2019 04 17 14 15 02](https://user-images.githubusercontent.com/16067358/56290658-854df200-611b-11e9-9995-ebe7fa22c2a7.png)

**Comment by manfield** [comment] 2019-04-17 13:22
Sure, the effect is that you don't have _feature_ filters, as well you don't have attribute group filter in some circumstances or other filter type. (Different bugs, same aspects but not necessarily the same meaning).
Though the issue is related to _feature_ filter and my description gives a hint more to developers that will fix this issue. 
If you think the number of issues opened on ps_facetedsearch are enough to make developers review the entire module I'm ok with that.
On the other hand if they will fix any single issue, my hints may be helpful for this specific case.

**Comment by khouloudbelguith** [comment] 2019-04-17 13:55
@manfield, in #9684: all of these issues related to the pending facetedsearch are added to our bug roadmap.
Thanks for your understanding!

**Comment by manfield** [comment] 2019-04-17 14:15
Thank you @khouloudbelguith , no problem at all
