### ISSUE TITLE
Prestashop REORDERING not WORKING

### ISSUE THREAD

**Issue by clemkake** [PrestaShop/PrestaShop#14797] opened 2019-07-22 04:26 UTC
Hello Team, 

were you guys able to fix this issue?

it's been more than a year and people are still facing the same problem:

I was able to reproduce the error and I think those who were able to didnt really look at the product 

category, the problem seem to be coming from there. 

Let's say you have 10 product in a category A and 5 of them have their default category set to B, 

when you try reordering the product in this case, the bug comes out. 

CAN ANYONE PLEASE TRY SOMETHING?

this is the link
https://drive.google.com/file/d/1_hmxGAJnape7dh6ljUKSv94fuW7x04T8/view

**Comment by khouloudbelguith** [comment] 2019-07-22 10:06
Hi @clemkake,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14616
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-22 10:06
Duplicate of #14616

**Closed as completed by khouloudbelguith** 2019-07-22 10:06 UTC
Labels: Duplicate
