### ISSUE TITLE
Link List module, v. 3.0.4, created blocks are missing on the "block list" page

### ISSUE THREAD

**Issue by globox91** [PrestaShop/PrestaShop#16434] opened 2019-11-15 15:27 UTC
**Describe the bug**

Actually, this bug is really similar to [16400](https://github.com/PrestaShop/PrestaShop/issues/16400).

I have 2 languages installed. One of them is inactive, because I don't need it on my FO. It's just my BO language.
When I create new block, it is inserted into the DB with the active languages only, because in module's "services.yml" there is a query, that searches only for active languages.

So after creation I get redirected to the "block list" page. There is a section for the new created module's hook, but it is empty :)
And I need to change my BO language to any active language to be able to see and edit new created block.

**To Reproduce**

1. Install two or more languages
2. Deactivate one of them (e.g. "lang 2")
3. Go to your admin profile and set your language to "lang 2"
4. Create new block (e.g. for a "displayAdminAfterHeader" hook)
5. See that no blocks are displayed on the "block list" page in that hook's section

**Screenshots**
![изображение](https://user-images.githubusercontent.com/56883311/68954102-61977b00-07d4-11ea-9915-6ba8e5e29759.png)
![изображение](https://user-images.githubusercontent.com/56883311/68954475-22b5f500-07d5-11ea-893b-2565993bf7c0.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.6
Module version: 3.0.4

**Comment by khouloudbelguith** [comment] 2019-11-15 15:57
Hi @globox91,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & ps_linklist v3.0.4 
![image](https://user-images.githubusercontent.com/16067358/68956656-d5338b00-07c8-11ea-9f58-050901b21073.png)
& ps_linklist v2.1.5.
https://drive.google.com/file/d/1AiVGjESJjXr7Qgje7jmYOnfkTDEVUnah/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-15 15:58
Related to #16400.

**Comment by alinchirilaa** [comment] 2020-06-22 13:59
Just set ur backoffice language same as your default site language. After that you can change back to english.
Eg. default site language FR and backoffice ENG u will not see the blocks. Change backoffice to FR and u will see that links. 
Worked on ps 1.7.6 and ps_linklist v3.1.0

**Comment by fire2** [comment] 2022-01-31 00:15
February 2022, bug is still not fixed...

**Comment by kpodemski** [comment] 2022-01-31 06:18
@fire2 

Hi there,

Not having an issue fixed immediately (or in a fixed timeframe) does not mean that it won't be fixed, or that we don't care. It doesn't mean that the issue is NOT important either. It just means that other issues have been considered, for whatever reason, _more_ important, so they were (or are being) tackled first. There's an immense amount of work to be done, and tasks take time.

Developer time is limited, so if the amount of issues opened in a certain timeframe exceeds the amount of issues that can be processed using the available developer time, tasks will simply pile up. This is common to ALL projects. Due to the number of pending issues, sometimes they may get lost in the pile and be forgotten about, so it's not a bad idea to ping us there from time to time to remind us about it, even if it's been a long while.

But here's the upside: PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

**Closed as completed** 2022-02-01 10:44 UTC
Labels: Bug, Minor, BO, Link widget, 1.7.5.0, 1.7.5.2, 1.7.6.1
