### ISSUE TITLE
Allignment of tax amount in order confirmation not correct

### ISSUE THREAD

**Issue by Marko-fin** [PrestaShop/PrestaShop#14760] opened 2019-07-18 23:58 UTC
**Describe the bug**
Allignment of tax information / amount not correct in order confirmation page

**To Reproduce**
1. Add items to cart
2. proceed to checkout
3. finalize order

**Screenshots**
![prestashop-1-7-6-1](https://user-images.githubusercontent.com/52843932/61499847-f924c280-a9c8-11e9-9d7d-156f3ce1d8bc.jpg)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version:  5.6.40-0+deb8u4

**Comment by khouloudbelguith** [comment] 2019-07-19 07:41
Hi @Marko-fin,

In my case, I did not manage to reproduce the issue with PS1.7.6.0.
![image](https://user-images.githubusercontent.com/16067358/61518041-9f3fef00-aa00-11e9-8dc0-8e02b093fa5a.png)

It is well displayed as you can see in my screenshot.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-08-19 07:47
Hi @Marko-fin,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-08-19 07:47 UTC
Labels: Bug, FO, Order, No change required, 1.7.6.0
