### ISSUE TITLE
Context's cart needs "id_carrier" to be pre-set with the current carrier

### ISSUE THREAD

**Issue by rmilecki** [PrestaShop/PrestaShop#22391] opened 2020-12-12 18:53 UTC
#### Describe the bug

PS allows setting default carrier (`PS_CARRIER_DEFAULT`) which then is selected by default in the "3 Shipping Method" checkout step. The problem is that `$context->cart->id_carrier` is set to `0` as the same time.

That inconsistency results e.g. in the `You must choose a carrier before applying this voucher to your order` user checkout error.

#### Expected behavior

It seems important to have `id_carrier` always set to the current carrier.

#### Steps to Reproduce

1. [BO] Make `My carrier` the default carrier
2. [BO] Add a new discount with some code, with "Carrier selection" set and `My carrier` selected
3. [FO] Try to use discount code **right** after entering "3 Shipping Method" checkout step

Workaround: switch to another carrier and then back to the `My carrier`.

**Screenshots**

Described bug causes e.g. the `You must choose a carrier before applying this voucher to your order` error:
![step-3](https://user-images.githubusercontent.com/452972/101992110-21dde400-3cb1-11eb-966c-61d7b6288cdc.png)
You can see that:
1. User sees `My carrier` selected by default (it's because `$delivery_option` is set to `2,`)
2. `CartRule::checkValidity` uses `$context->cart->id_carrier` which is `0` and returns an error

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.23

**Comment by hibatallahAouadni** [comment] 2020-12-14 16:50
Hello @rmilecki 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9688. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-12-14 16:50 UTC
Labels: Duplicate
