### ISSUE TITLE
Quick links to "New Products" and "Installed modules" are wrong

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#11174] opened 2018-10-29 11:30 UTC
**Describe the bug**
Quick links doesn't let you go to the desired page, as the links are wrong inside the install XML.

**To Reproduce**
1. Install your Shop
2. Click on one of theses quick links.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-10-29 11:38
Hi @prestamodule,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/10736 to solve the issue.
It is fixed in the release 1.7.5.0.
It is working in the 1.7.5.0.build1.beta2.
Your ticket is a duplicate of #10480
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-29 11:38
Duplicate of #10480

**Closed as completed by khouloudbelguith** 2018-10-29 11:38 UTC
Labels: Duplicate
