### ISSUE TITLE
Modern e-mail themes missed PL translations

### ISSUE THREAD

**Issue by jameshellfire** [PrestaShop/PrestaShop#14680] opened 2019-07-16 11:56 UTC
Not completed transaltions for modern e-mail templates, for example in PL (Polish).
![image](https://user-images.githubusercontent.com/16944636/61291986-530e6800-a7d0-11e9-8b66-40d30823a84c.png)
![image](https://user-images.githubusercontent.com/16944636/61292459-84d3fe80-a7d1-11e9-8964-f986ef955b99.png)
etc...

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-07-16 12:04
Hi @jameshellfire,

Your ticket is a duplicate of #14633
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-07-16 12:04
Duplicate of #14633

**Closed as completed by khouloudbelguith** 2019-07-16 12:04 UTC
