### ISSUE TITLE
Back Office Customer - View timeout with lots of orders

### ISSUE THREAD

**Issue by davidcylke** [PrestaShop/PrestaShop#26719] opened 2021-11-23 17:53 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When customer has lots of orders (like our b2b clients) its not possible to view this page. Lots of queries are sent since there is lots of data do display - all orders, all carts, all recently viewed products. Pagination should be added there so not so much data is needed to display at once.

### Expected behavior

Page should display faster, with not all of clients orders, carts and viewed products at once.

### Steps to reproduce

Have customer with lots of orders (50+)
Go to Customers - View (3 dots menu) - cry

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment] 2021-11-23 18:07
Open src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
Find private function getCustomerCarts and replace it with this one. Should be fast. :-)

```
    private function getCustomerCarts(Customer $customer)
    {
        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
        SELECT c.id_cart, c.date_add, ca.name as carrier_name, c.id_currency, cu.iso_code as currency_iso_code
        FROM ' . _DB_PREFIX_ . 'cart c
        LEFT JOIN ' . _DB_PREFIX_ . 'carrier ca ON ca.id_carrier = c.id_carrier
        LEFT JOIN ' . _DB_PREFIX_ . 'currency cu ON cu.id_currency = c.id_currency
        WHERE c.`id_customer` = ' . (int) $customer->id . '
        ORDER BY c.`date_add` DESC');

        $customerCarts = [];
        foreach ($result as $row) {
            $customerCarts[] = new CartInformation(
                sprintf('%06d', $row['id_cart']),
                Tools::displayDate($row['date_add'], null, true),
                '',
                $row['carrier_name']
            );
        }

        return $customerCarts;
    }
```

**Comment by davidcylke** [comment] 2021-11-23 18:13
@Hlavtox I saw your commit elsewhere. Could you help me remove recently viewed products and remove displayed carts?

**Comment by alfonsolr09** [comment] 2021-11-23 23:44
> Abra src / Adapter / Customer / QueryHandler / GetCustomerForViewingHandler.php Busque la función privada getCustomerCarts y reemplácela por esta. Debería ser rápido. :-)
> 
> ```
>     private function getCustomerCarts(Customer $customer)
>     {
>         $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
>         SELECT c.id_cart, c.date_add, ca.name as carrier_name, c.id_currency, cu.iso_code as currency_iso_code
>         FROM ' . _DB_PREFIX_ . 'cart c
>         LEFT JOIN ' . _DB_PREFIX_ . 'carrier ca ON ca.id_carrier = c.id_carrier
>         LEFT JOIN ' . _DB_PREFIX_ . 'currency cu ON cu.id_currency = c.id_currency
>         WHERE c.`id_customer` = ' . (int) $customer->id . '
>         ORDER BY c.`date_add` DESC');
> 
>         $customerCarts = [];
>         foreach ($result as $row) {
>             $customerCarts[] = new CartInformation(
>                 sprintf('%06d', $row['id_cart']),
>                 Tools::displayDate($row['date_add'], null, true),
>                 '',
>                 $row['carrier_name']
>             );
>         }
> 
>         return $customerCarts;
>     }
> ```

Wdyt about create a PR to solve this problem? 😊

**Comment by Hlavtox** [comment] 2021-11-24 07:30
@alfonsolr09 @davidcylke It's already fixed when editing the customer, available in v8.

On listing, I improved it by 25% here - https://github.com/PrestaShop/PrestaShop/pull/26689, but still slow. The calculation of cart amount is what totally kills the performance. :( So when you remove it, the page is absolutely instant even with a looot of orders and carts.

- We can optimize the cart calculation - not easy
- We can cache last cart amount
- We can show 10 carts and do pagination
- We can show 10 carts and put a button with link to "Shopping cart" page - easy
- We can remove the cart amount from the list

**Comment by hibatallahAouadni** [comment] 2021-11-24 10:01
Hello @davidcylke 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25683. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: And as always, Mr. @Hlavtox impresses us with his quick answers and solutions :superhero: Thanks :pray: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-11-24 10:01
Duplicate of #25683

**Closed by hibatallahAouadni** 2021-11-24 10:01 UTC
Labels: Bug

**Comment by DiMiTriFrog** [comment] 2023-10-24 21:29
> Open src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php Find private function getCustomerCarts and replace it with this one. Should be fast. :-)
> 
> ```
>     private function getCustomerCarts(Customer $customer)
>     {
>         $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
>         SELECT c.id_cart, c.date_add, ca.name as carrier_name, c.id_currency, cu.iso_code as currency_iso_code
>         FROM ' . _DB_PREFIX_ . 'cart c
>         LEFT JOIN ' . _DB_PREFIX_ . 'carrier ca ON ca.id_carrier = c.id_carrier
>         LEFT JOIN ' . _DB_PREFIX_ . 'currency cu ON cu.id_currency = c.id_currency
>         WHERE c.`id_customer` = ' . (int) $customer->id . '
>         ORDER BY c.`date_add` DESC');
> 
>         $customerCarts = [];
>         foreach ($result as $row) {
>             $customerCarts[] = new CartInformation(
>                 sprintf('%06d', $row['id_cart']),
>                 Tools::displayDate($row['date_add'], null, true),
>                 '',
>                 $row['carrier_name']
>             );
>         }
> 
>         return $customerCarts;
>     }
> ```

You the f*** boss, it's working for me. It's ultra fast again!!!
