### ISSUE TITLE
Firefox - horizontal scrollbar on homepage under 991px

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25459] opened 2021-07-29 09:00 UTC
#### Describe the bug
There is a horizontal scrollbar on homepage of 1.7.8 beta under 991px. Caused by styling of the carusel, which overflows the content.

Not an uncommon issue, it must be done in a different way - https://www.google.com/search?q=100vw+overflow

Does anybody even check it when coding it? This must be immediately reproduced on first opening of inspector. 🤔

#### Expected behavior
There should be no scrollbar.

#### Screenshots
![responsive](https://user-images.githubusercontent.com/6097524/127463408-ec6d520a-73c3-417b-afd8-9e0d97292f8d.JPG)

#### Additional information
* PrestaShop version: 1.7.8 beta
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-07-29 10:03
Hello @Hlavtox 

I didn't manage to reproduce the issue with PS178x, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/127473085-a55d1c8a-7abb-4abe-bf34-528d9e500d81.png)

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment] 2021-07-29 10:25
@hibatallahAouadni Reproduced on latest Firefox
![firefox](https://user-images.githubusercontent.com/6097524/127476104-c8482e67-0709-4e23-92ec-8bee08d28b34.JPG)

**Comment by Hlavtox** [comment] 2021-07-29 10:27
@hibatallahAouadni It's common issue - https://www.google.com/search?q=100vw+overflow

**Comment by khouloudbelguith** [comment] 2021-07-30 12:03
Hi @Hlavtox,

Thanks for these clarifications.
I manage to reproduce the issue with branch 1.7.8.x, PS1775 and the branch 1.7.7.x using Firefox v90 and V78.5.0esr (64 bits)
![image](https://user-images.githubusercontent.com/16067358/127650043-4dfb0f87-d358-4601-ab2e-e98ba37d255b.png)

It is ok with PS1769 => regression from PS177.
![image](https://user-images.githubusercontent.com/16067358/127650110-220cbb23-7c25-408f-b5c9-73f6ff7df7df.png)

I tried with Chrome v92 => ok

I will add to the bug roadmap.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 
If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by Progi1984** [comment] 2021-08-23 07:55
Fixed by @NeOMakinG in #25569

**Closed as completed by Progi1984** 2021-08-23 07:55 UTC
Labels: Bug, Trivial, FO, Regression, Fixed, Front-end, PR available, 1.7.7.x, Responsive, 1.7.8.x, 1.7.7.5
