### ISSUE TITLE
Module 1-Click Upgrade v.4.15.0 fails from v.1.7.8.8 to 8.0.1

### ISSUE THREAD

**Issue by madibashop** [PrestaShop/PrestaShop#31505] opened 2023-02-23 10:31 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I try to upgrade from v 1.7.8.8 to 8.0.1 with 1-Click Upgrade v.4.15.0.
Theme: CLASSIC ver. 1.0.0

PHP version is 7.4.33
MySQL version is 5.7.38
Hosting: IONOS

I deactivate non native modules, overviews and cache.
Shop offline.
Upgrade process result in some errors:

ERRORS

[INTERNAL] 
/homepages/43/***/htdocs/***/PrestaShop/***/src/Core/Addon/Theme/ThemeManager.php line 384 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details. #0 
/homepages/43/***/htdocs/***/PrestaShop/***/src/Core/Addon/Theme/ThemeManager.php(245): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #1 
/homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(113): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #2 
/homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #3 
/homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(662): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #4 
/homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(119): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #5 
/homepages/43/***/htdocs/***/PrestaShop/***/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #6 
/homepages/43/***/htdocs/****/PrestaShop/***/***/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #7 {main}

After this errors the web page fails in some situations:

**Back office: It's not possible to navigate from root category to subcategories: 500 Error.
Front office: Main menu only opens root category. The rest of the menu only shows white pages.**

AFTER SOME FAILED UPGRADES I TRY:
- I copy new files over old files.
- I change database with database created from 1-click upgrade.
Result: NOT RUN.

### Expected behavior

I expected upgrade without errors.

### Steps to reproduce

1 - Go to advanced parameters - perfomance: cache off and clear cache.
2 - Go to shop - configuration - maintenance: offline.
3 - Go to 1-Click Upgrade v.4.15.0 deactivate non native modules and overviews. Only mail templates on.
4 - Run upgrade.

Result: errors commented before:
- **ERRORS**
- **Back office: It's not possible to navigate from root category to subcategories: 500 Error.**
- **Front office: Main menu only opens root category. The rest of the menu only shows white pages.**

AFTER SOME FAILED UPGRADES I TRY:
- I copy new files over old files.
- I change database with database created from 1-click upgrade.
Result: NOT RUN.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v.4.15.0.

**Comment by madibashop** [comment] 2023-02-23 10:39
ERRORS: After the 8 upgrrade errors:

Result in Categories:

Category
![imatge](https://user-images.githubusercontent.com/125015630/220883058-7d4ed1f0-e0db-4ee4-9280-722d86b3c7d1.png)

and cliking in "Productos"
Error_500
![imatge](https://user-images.githubusercontent.com/125015630/220883213-7e9e6807-8021-4599-a4f0-b4e87b5ee4e7.png)

It is not possible to go to subcategories !

**Comment by HanaRebaiQA** [comment] 2023-02-23 15:10
Hello @madibashop 

Thanks for your report.
We are aware of your first report of this issue #31433 
Thanks for all your provided details. If you can update the description of the first issue.
I'll close this one as it's a duplicate.

Thank You!

**Comment by HanaRebaiQA** [comment] 2023-02-23 15:10
Duplicate of #31433

**Closed as completed by HanaRebaiQA** 2023-02-23 15:10 UTC
Labels: Bug, Duplicate, Autoupgrade, Invalid, Module, 1.7.8.8

**Comment by madibashop** [comment] 2023-02-24 16:48
The problem continues ...
Do not close it
