### ISSUE TITLE
upload a new module on 8.0 error

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28915] opened 2022-06-29 21:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

can't search a file in my pc
I can't upload a module by dragging a file either

https://watch.screencastify.com/v/G35zUxC1Ge0dQhq3qBq1

### Expected behavior

Module is uploading successfully 

### Steps to reproduce

1. BO > Modules > Module Manager
2. Click on "Upload a module" button
3. Modal is displayed
4. Try to click on the link 
5. See error > nothing work

### PrestaShop version(s) where the bug happened

8.0

**Comment by alfonsolr09** [comment] 2022-06-29 21:36
I can't upload a module by dragging a file either

**Comment by alfonsolr09** [comment] 2022-06-29 21:38
another error
https://watch.screencastify.com/v/rP4S1SHVNyFXUu6TlNPC

**Comment by sLorenzini** [comment] 2022-06-30 09:53
Hello @alfonsolr09,

I coudn't reproduce your issues on 8.0.0 version.
- Select a file via the link:

https://user-images.githubusercontent.com/2854834/176648112-76e2fdba-3903-4a34-915d-1da68e02edfc.mp4

- The dragging file is working too
- The filter by category is working

https://user-images.githubusercontent.com/2854834/176648151-0464fd21-27f4-4bfd-a19d-989e39e4de75.mp4

Could you activate the debug mode please to see if an error is displayed?

Waiting for your feedback

Thank you

**Comment by hibatallahAouadni** [comment] 2022-07-19 16:24
Hello @alfonsolr09 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-07-19 16:24 UTC
Labels: Bug, 8.0.x, BO, Module manager, Invalid

**Comment by alfonsolr09** [comment] 2022-08-09 22:09
still not working on a fresh install on xampp

**Comment by alfonsolr09** [comment] 2022-08-09 22:11
https://watch.screencastify.com/v/F4OY8h3PWrkG0gDcalYM
@sLorenzini
