### ISSUE TITLE
Can not access different shop sections after Upgrade 1.7.5.1 -> 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#17310] opened 2020-01-22 20:16 UTC
Hi, 

I upgraded from 1.7.5.1 to 1.7.6.3 and I can not access the following shop sections:

catalog -> categories
catalog -> brands & suppliers
customers -> customers
design -> sites
international -> localisation -> language
international -> localisation -> currencies

I get 500 ERROR. 

This I found in   advanced settings -> informations:
missing files (33):
vendor/composer/installers/src/Composer/Installers/UserFrostingInstaller.php
vendor/composer/installers/src/Composer/Installers/ExpressionEngineInstaller.php
vendor/composer/installers/src/Composer/Installers/KodiCMSInstaller.php
vendor/composer/installers/src/Composer/Installers/OsclassInstaller.php
vendor/composer/installers/src/Composer/Installers/MayaInstaller.php
vendor/composer/installers/src/Composer/Installers/EzPlatformInstaller.php
vendor/composer/installers/src/Composer/Installers/VanillaInstaller.php
vendor/composer/installers/src/Composer/Installers/ReIndexInstaller.php
vendor/composer/installers/src/Composer/Installers/ImageCMSInstaller.php
vendor/composer/installers/src/Composer/Installers/PlentymarketsInstaller.php
vendor/composer/installers/src/Composer/Installers/PxcmsInstaller.php
vendor/composer/installers/src/Composer/Installers/VgmcpInstaller.php
vendor/composer/installers/src/Composer/Installers/PortoInstaller.php
vendor/composer/installers/src/Composer/Installers/PhiftyInstaller.php
vendor/composer/installers/src/Composer/Installers/AttogramInstaller.php
vendor/composer/installers/src/Composer/Installers/LavaLiteInstaller.php
vendor/composer/installers/src/Composer/Installers/LanManagementSystemInstaller.php
vendor/composer/installers/src/Composer/Installers/EliasisInstaller.php
vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
vendor/composer/installers/src/Composer/Installers/ItopInstaller.php
vendor/composer/installers/src/Composer/Installers/YawikInstaller.php
vendor/composer/installers/src/Composer/Installers/Plugin.php
vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
vendor/composer/installers/src/Composer/Installers/BonefishInstaller.php
vendor/composer/installers/src/Composer/Installers/CiviCrmInstaller.php
vendor/composer/installers/src/Composer/Installers/KanboardInstaller.php
vendor/composer/installers/src/Composer/Installers/MajimaInstaller.php
vendor/composer/installers/src/Composer/Installers/ModxInstaller.php
vendor/composer/installers/src/Composer/Installers/SiteDirectInstaller.php
vendor/composer/installers/src/Composer/Installers/OntoWikiInstaller.php
vendor/composer/installers/src/Composer/Installers/RadPHPInstaller.php
vendor/composer/installers/src/Composer/Installers/DecibelInstaller.php

updated files (19):
admin573dqkovw/autoupgrade/index.php
admin573dqkovw/autoupgrade/backup/index.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/DrupalInstaller.php
vendor/composer/installers/src/Composer/Installers/BitrixInstaller.php
vendor/composer/installers/src/Composer/Installers/CraftInstaller.php
vendor/composer/installers/src/Composer/Installers/Concrete5Installer.php
vendor/composer/installers/src/Composer/Installers/AsgardInstaller.php
vendor/composer/installers/src/Composer/Installers/KirbyInstaller.php
vendor/composer/installers/src/Composer/Installers/ShopwareInstaller.php
vendor/composer/installers/src/Composer/Installers/SilverStripeInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/TYPO3CmsInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/WordPressInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MediaWikiInstaller.php

This I get with debug mode:

![image](https://user-images.githubusercontent.com/44971218/72929587-6c353a00-3d5a-11ea-85f5-53f5771d5ab5.png)
![image](https://user-images.githubusercontent.com/44971218/72929628-82db9100-3d5a-11ea-8122-af8fa28fe8db.png)
![image](https://user-images.githubusercontent.com/44971218/72929675-9c7cd880-3d5a-11ea-9d07-728c9c4c814e.png)
![image](https://user-images.githubusercontent.com/44971218/72929722-ae5e7b80-3d5a-11ea-9f5e-7668c4e97be0.png)
![image](https://user-images.githubusercontent.com/44971218/72929856-f382ad80-3d5a-11ea-972c-2fa5d4486fd8.png)
![image](https://user-images.githubusercontent.com/44971218/72929892-06957d80-3d5b-11ea-8d54-fdb4c6263fd4.png)
![image](https://user-images.githubusercontent.com/44971218/72929965-2af15a00-3d5b-11ea-8abc-0d5c5445141c.png)

InvalidFieldNameException
--
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM i79e_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1' with params [1, 1, "category"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.filter_id' in 'field list'    at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71   at Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception occurred while executing \'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM i79e_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1\' with params [1, 1, &quot;category&quot;]:SQLSTATE[42S22]: Column not found: 1054 Unknown column \'t0.filter_id\' in \'field list\'', object(PDOException))      (vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128)   at Doctrine\DBAL\DBALException::driverExceptionDuringQuery(object(Driver), object(PDOException), 'SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM i79e_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1', array(1, 1, 'category'))      (vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855)   at Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM i79e_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1', array(1, 1, 'category'), array('integer', 'integer', 'string'))      (vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:712)   at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(array('employee' => 1, 'shop' => 1, 'filterId' => 'category'), null, null, array(), null, 1, null)      (vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:196)   at Doctrine\ORM\EntityRepository->findOneBy(array('employee' => 1, 'shop' => 1, 'filterId' => 'category'))      (src/PrestaShopBundle/Entity/Repository/AdminFilterRepository.php:69)   at PrestaShopBundle\Entity\Repository\AdminFilterRepository->findByEmployeeAndFilterId(1, 1, 'category')      (src/Core/Search/Builder/RepositoryFiltersBuilder.php:76)   at PrestaShop\PrestaShop\Core\Search\Builder\RepositoryFiltersBuilder->getParametersFromRepository('category')      (src/Core/Search/Builder/RepositoryFiltersBuilder.php:49)   at PrestaShop\PrestaShop\Core\Search\Builder\RepositoryFiltersBuilder->buildFilters(object(CategoryFilters))      (src/Core/Search/Builder/ChainedFiltersBuilder.php:80)   at PrestaShop\PrestaShop\Core\Search\Builder\ChainedFiltersBuilder->buildFilters()      (src/PrestaShopBundle/Controller/ArgumentResolver/FiltersBuilderResolver.php:70)   at PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver->resolve(object(Request), object(ArgumentMetadata))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php:62)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(object(Request), array(object(CategoryController), 'indexAction'))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableArgumentResolver.php:38)   at Symfony\Component\HttpKernel\Controller\TraceableArgumentResolver->getArguments(object(Request), array(object(CategoryController), 'indexAction'))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:143)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)      (admin573dqkovw/index.php:86)

PDOException
--
Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.filter_id' in 'field list'    at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107   at Doctrine\DBAL\Driver\PDOStatement->execute()      (vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:847)   at Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM i79e_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1', array(1, 1, 'category'), array('integer', 'integer', 'string'))      (vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:712)   at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(array('employee' => 1, 'shop' => 1, 'filterId' => 'category'), null, null, array(), null, 1, null)      (vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:196)   at Doctrine\ORM\EntityRepository->findOneBy(array('employee' => 1, 'shop' => 1, 'filterId' => 'category'))      (src/PrestaShopBundle/Entity/Repository/AdminFilterRepository.php:69)   at PrestaShopBundle\Entity\Repository\AdminFilterRepository->findByEmployeeAndFilterId(1, 1, 'category')      (src/Core/Search/Builder/RepositoryFiltersBuilder.php:76)   at PrestaShop\PrestaShop\Core\Search\Builder\RepositoryFiltersBuilder->getParametersFromRepository('category')      (src/Core/Search/Builder/RepositoryFiltersBuilder.php:49)   at PrestaShop\PrestaShop\Core\Search\Builder\RepositoryFiltersBuilder->buildFilters(object(CategoryFilters))      (src/Core/Search/Builder/ChainedFiltersBuilder.php:80)   at PrestaShop\PrestaShop\Core\Search\Builder\ChainedFiltersBuilder->buildFilters()      (src/PrestaShopBundle/Controller/ArgumentResolver/FiltersBuilderResolver.php:70)   at PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver->resolve(object(Request), object(ArgumentMetadata))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php:62)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(object(Request), array(object(CategoryController), 'indexAction'))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableArgumentResolver.php:38)   at Symfony\Component\HttpKernel\Controller\TraceableArgumentResolver->getArguments(object(Request), array(object(CategoryController), 'indexAction'))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:143)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)      (admin573dqkovw/index.php:86)

PDOException
--
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.filter_id' in 'field list'    at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105   at PDOStatement->execute(null)      (vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)   at Doctrine\DBAL\Driver\PDOStatement->execute()      (vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:847)   at Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM i79e_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1', array(1, 1, 'category'), array('integer', 'integer', 'string'))      (vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:712)   at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(array('employee' => 1, 'shop' => 1, 'filterId' => 'category'), null, null, array(), null, 1, null)      (vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:196)   at Doctrine\ORM\EntityRepository->findOneBy(array('employee' => 1, 'shop' => 1, 'filterId' => 'category'))      (src/PrestaShopBundle/Entity/Repository/AdminFilterRepository.php:69)   at PrestaShopBundle\Entity\Repository\AdminFilterRepository->findByEmployeeAndFilterId(1, 1, 'category')      (src/Core/Search/Builder/RepositoryFiltersBuilder.php:76)   at PrestaShop\PrestaShop\Core\Search\Builder\RepositoryFiltersBuilder->getParametersFromRepository('category')      (src/Core/Search/Builder/RepositoryFiltersBuilder.php:49)   at PrestaShop\PrestaShop\Core\Search\Builder\RepositoryFiltersBuilder->buildFilters(object(CategoryFilters))      (src/Core/Search/Builder/ChainedFiltersBuilder.php:80)   at PrestaShop\PrestaShop\Core\Search\Builder\ChainedFiltersBuilder->buildFilters()      (src/PrestaShopBundle/Controller/ArgumentResolver/FiltersBuilderResolver.php:70)   at PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver->resolve(object(Request), object(ArgumentMetadata))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php:62)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(object(Request), array(object(CategoryController), 'indexAction'))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableArgumentResolver.php:38)   at Symfony\Component\HttpKernel\Controller\TraceableArgumentResolver->getArguments(object(Request), array(object(CategoryController), 'indexAction'))      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:143)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)      (admin573dqkovw/index.php:86)

[prod.log.txt](https://github.com/PrestaShop/PrestaShop/files/4099735/prod.log.txt)
[log.txt](https://github.com/PrestaShop/PrestaShop/files/4099767/log.txt)

Presta cache and browser cache was deleted a few times. Also  /var/cache/  a few times. It does not help. All Presta chaches are disabled. 

Hope these informations help!

**Comment by khouloudbelguith** [comment] 2020-01-23 08:36
Hi @didi-2018,

Thanks for your report.
What is the exact version of the 1-click upgrade did you use?
This issue was fixed in the last version PS1.7.6.1 with this PR: https://github.com/PrestaShop/PrestaShop/pull/14620 as reported here: https://github.com/PrestaShop/PrestaShop/issues/14617
Here's a provisional solution:

`ALTER TABLE `ps_admin_filter` ADD `filter_id` INT NOT NULL ;`

Thanks to check & feedback.

**Comment by didi-2018** [comment] 2020-01-23 11:09
@khouloudbelguith  thanks for your answer. I used Version 4.10.1 
![image](https://user-images.githubusercontent.com/44971218/72979439-9cbbb900-3dd8-11ea-9d8e-3d82328e8e65.png)

I insert column "filter_id" but now I get the following issue:

![image](https://user-images.githubusercontent.com/44971218/72979626-09cf4e80-3dd9-11ea-8d6c-a8a521662ebb.png)
![image](https://user-images.githubusercontent.com/44971218/72979684-279cb380-3dd9-11ea-952d-8dcf9f5a06ae.png)

**Comment by khouloudbelguith** [comment] 2020-01-23 11:16
@didi-2018, you have an override causing this issue
![image](https://user-images.githubusercontent.com/16067358/72980091-186a3580-3dda-11ea-9ac4-6c9b9ade710b.png)

It is not a PrestaShop issue, please contact the module author which installs this override.

Thanks to check & feedback.

**Comment by didi-2018** [comment] 2020-01-23 11:18
![image](https://user-images.githubusercontent.com/44971218/72980073-1011fa80-3dda-11ea-89a3-0c3aa813bd5e.png)
![image](https://user-images.githubusercontent.com/44971218/72980115-2c159c00-3dda-11ea-8510-dfc76a76d31f.png)

![image](https://user-images.githubusercontent.com/44971218/72980158-523b3c00-3dda-11ea-93a4-acf4228bdbd4.png)
![image](https://user-images.githubusercontent.com/44971218/72980216-6d0db080-3dda-11ea-82b3-3f99c449d607.png)

**Comment by didi-2018** [comment] 2020-01-23 11:21
> @didi-2018, you have an override causing this issue
> ![image](https://user-images.githubusercontent.com/16067358/72980091-186a3580-3dda-11ea-9ac4-6c9b9ade710b.png)
> 
> It is not a PrestaShop issue, please contact the module author which installs this override.
> 
> Thanks to check & feedback.

I added this mail.php a long time ago. This is a tipp from prestashop forum to get all mails as a copy.

**Comment by khouloudbelguith** [comment] 2020-01-23 11:21
@didi-2018, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

PS: in my case, I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.7.5.1 using the 1-click upgrade v4.10.1.
https://drive.google.com/file/d/1JutVHUjSHft-WUuqW4ZOTuSFzok3lE9l/view

>I added this mail.php a long time ago. This is a tipp from prestashop forum to get all mails as a copy.
You need to edit this file, it is causes issues with PS1.7.6.3.

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 11:23
@khouloudbelguith  you will find the log in my first message called "log.txt"

**Comment by khouloudbelguith** [comment] 2020-01-23 11:34
@didi-2018,  thanks to provide a screenshot from the table ps_cuurency & ps_currency_lang.

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 11:44
@khouloudbelguith 
![image](https://user-images.githubusercontent.com/44971218/72981801-f83c7580-3ddd-11ea-8916-2a694aa53766.png)

![image](https://user-images.githubusercontent.com/44971218/72981842-0ab6af00-3dde-11ea-87fd-43b807bbfa7c.png)

**Comment by khouloudbelguith** [comment] 2020-01-23 11:48
@didi-2018, as you can see in this screenshot
![image](https://user-images.githubusercontent.com/16067358/72982027-6ed97300-3dde-11ea-9b88-9e02ae2bbae9.png)
symbols & names of all currencies are missing in the first language (id_lang=1).
Thanks to edit this table `ps_currency_lang` & edit those missings.

Thanks to check & feedback.

**Comment by didi-2018** [comment] 2020-01-23 11:57
@khouloudbelguith  nothing happens.
![image](https://user-images.githubusercontent.com/44971218/72982684-ee1b7680-3ddf-11ea-832b-a10e13805b85.png)


categories:
![image](https://user-images.githubusercontent.com/44971218/72982412-4c942500-3ddf-11ea-99ab-5113f9be817c.png)

brands & suppliers:
![image](https://user-images.githubusercontent.com/44971218/72982442-62094f00-3ddf-11ea-8009-5fc0911e8d3b.png)

design -> sites:
![image](https://user-images.githubusercontent.com/44971218/72982490-7e0cf080-3ddf-11ea-94eb-e5fcaebdf223.png)

international -> localisation -> languages:
![image](https://user-images.githubusercontent.com/44971218/72982548-9ed54600-3ddf-11ea-8974-0e079b6b6d4f.png)

international -> localisation -> currencies:
![image](https://user-images.githubusercontent.com/44971218/72982613-be6c6e80-3ddf-11ea-94d7-3e71f9ce4e48.png)

**Comment by didi-2018** [comment] 2020-01-23 12:06
@khouloudbelguith  this I found in table admin_filter:

![image](https://user-images.githubusercontent.com/44971218/72983241-1c4d8600-3de1-11ea-9dd1-5f5701a4755d.png)

**Comment by khouloudbelguith** [comment] 2020-01-23 12:08
@didi-2018, thanks to navigate to the BO => International => Translations => update all your languges.
![image](https://user-images.githubusercontent.com/16067358/72983375-6c2c4d00-3de1-11ea-860c-c2bb38e716ca.png)

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by didi-2018** [comment] 2020-01-23 12:22
@khouloudbelguith  languages are updated and var/cache/prod and var/cache/dev are deleted but nothing happens. still no access

**Comment by didi-2018** [comment] 2020-01-23 12:46
@khouloudbelguith  what do you think should I do a new update and deinstall autoupgrade module first and install new before upgrade?

**Comment by khouloudbelguith** [comment] 2020-01-23 13:46
@didi-2018, As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 13:52
@khouloudbelguith  so you do not have any idea what causes the errors? I always make updates on a fresh shopcopy. 

I have just done a new upgrade with deinstall autoupgrade and install fresh and upgrade stopped at upgrading presta modules and logged me out. After login the same problems as before. No column "filter_id" insert and all the rest

**Comment by khouloudbelguith** [comment] 2020-01-23 13:56
@didi-2018, in my case, I did not manage to reproduce the issue, but it could be the problem related to some overrides added in your case or some custom module.

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 14:49
@khouloudbelguith  all not-presta-modules are disabled before update, all overrides are disabled, Mail.php is deleted. 

Now "id_log" is not found

![image](https://user-images.githubusercontent.com/44971218/72994635-bcaea500-3df7-11ea-99ad-0ce427fc3667.png)

**Comment by khouloudbelguith** [comment] 2020-01-23 15:03
@didi-2018,

>all not-presta-modules are disabled before update, all overrides are disabled

Those options are disabled from the BO => Advanced Parameters => Performance page?
![image](https://user-images.githubusercontent.com/16067358/72995854-e963bc00-3df9-11ea-9e34-ccf1561544e1.png)

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 15:04
@khouloudbelguith  YES excactly!

**Comment by khouloudbelguith** [comment] 2020-01-23 15:12
@didi-2018, The options do not work in the PS1.7.6
as reported here:
https://github.com/PrestaShop/PrestaShop/issues/14596
https://github.com/PrestaShop/PrestaShop/issues/9965
So, please check if you have any override manually in all folders: https://github.com/PrestaShop/PrestaShop/tree/develop/override

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 15:28
@khouloudbelguith  all override files removed and all third party modules manually deactiveted and still the same. 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_log' in 'order clause'
 what does it mean?

**Comment by didi-2018** [comment] 2020-01-23 15:36
@khouloudbelguith what I saw before a few days is there are no more numbers shown for modules that should be updated. notification_counter does not work anymore in my 1.7.5.1 and after update a module there appears everytime the presta notice:

![image](https://user-images.githubusercontent.com/44971218/72998544-4c575200-3dfe-11ea-97d7-71ad15089902.png)

but module are updated. This a have since a few days, maybe a week. And my favicon is gone too in module section where are modules updates are.

**Comment by khouloudbelguith** [comment] 2020-01-23 15:40
@didi-2018, your upgrade was stopped when upgrading PrestaShop modules.
It could be related to this issue.
>And my favicon is gone too in module section where are modules updates are.

Did you make any changes before this? did you install any modules? 

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 15:49
@khouloudbelguith in the mean time a maked new update and it does not stop. 

I installed a module for a video tab in FO and one for alt tags. But if I disable them, the problem is still there. And I always do a lot in my shop. I can not say it happened with installing something. One day it was like now is.

**Comment by khouloudbelguith** [comment] 2020-01-23 16:03
@didi-2018, did you delete any currency before?
Your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/17185

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 16:12
@khouloudbelguith  no I did not delete any currency. You can look at the database screenshot I have sent you today. Only three currencies and all are active.

**Comment by khouloudbelguith** [comment] 2020-01-23 16:15
@didi-2018, multistore is enabled?

Thanks!

**Comment by didi-2018** [comment] 2020-01-23 16:36
@khouloudbelguith no I do not use multistore

**Comment by khouloudbelguith** [comment] 2020-01-23 16:42
@didi-2018, Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Closed as completed by khouloudbelguith** 2020-01-23 16:42 UTC
Labels: Bug, BO, Can't reproduce, Autoupgrade, 1.7.6.3

**Comment by didi-2018** [comment] 2020-01-24 14:24
@khouloudbelguith  I could find out that prestashop makes wrong entries in database "admin_filter". The filters are wrong! For example: "orderBy : "id_log" in category search.   Deleting that wrong database entries fixed my problems and I have access to the section I could not access before.

**Comment by didi-2018** [comment] 2020-01-24 14:49
@khouloudbelguith 

for example:
catalog -> categories  prestashop make an entry in database "admin_filter":

{"limit":50,"orderBy":"id_lang","sortOrder":"ASC","filters":{"id_category_parent":"2"}}

there is no filter "id_lang" and access is not possible. 
![image](https://user-images.githubusercontent.com/44971218/73076670-d9fa7680-3ebe-11ea-9cf0-f66117147f77.png)
and set no "controller" and "action". So how should the shop now know for what the filter is? 
![image](https://user-images.githubusercontent.com/44971218/73076750-07dfbb00-3ebf-11ea-9d2f-4d47b8f01489.png)

deleting that filter from database and refresh the page, the page works.
