### ISSUE TITLE
Add to cart not working 

### ISSUE THREAD

**Issue by banobazaar** [PrestaShop/PrestaShop#18814] opened 2020-04-24 17:33 UTC
Add to cart option is not working in FO when I click on any product and then i press "add to cart", it shows not addition in cart as per attached screenshot

![image](https://user-images.githubusercontent.com/52763446/80240590-8c3b0900-867b-11ea-83c4-1427d4e89a46.png)

* PrestaShop version: 1.7
* PHP version: N/A

**Comment by banobazaar** [comment] 2020-04-25 13:31
response from this forum is very poor

**Comment by PierreRambaud** [comment] 2020-04-27 09:31
Hi @banobazaar 
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
 ...

You don't know how to get this information? Please read the following article:

http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thank you!

**Comment by abdu355** [comment] 2020-04-30 14:29
Facing the same issue right after updating to 1.7.6.5 on April 28,2020.

* site: https://www.800cakes.com
* aws ec2 t2-medium
* default setup Bitnami stack &  default theme - Single store
* 1.7.6.5 (stable)
* Debug log + reports:
[dev.log](https://github.com/PrestaShop/PrestaShop/files/4558842/dev.log)
[screencapture-800cakes-administration-index-php-profiler-b56d23-2020-04-30-18_16_12.pdf](https://github.com/PrestaShop/PrestaShop/files/4558846/screencapture-800cakes-administration-index-php-profiler-b56d23-2020-04-30-18_16_12.pdf)
[screencapture-800cakes-administration-index-php-profiler-b56d23-2020-04-30-18_16_07.pdf](https://github.com/PrestaShop/PrestaShop/files/4558847/screencapture-800cakes-administration-index-php-profiler-b56d23-2020-04-30-18_16_07.pdf)
[screencapture-800cakes-administration-index-php-profiler-b56d23-2020-04-30-18_16_28.pdf](https://github.com/PrestaShop/PrestaShop/files/4558848/screencapture-800cakes-administration-index-php-profiler-b56d23-2020-04-30-18_16_28.pdf)
* Apache error log:
[error.log](https://github.com/PrestaShop/PrestaShop/files/4558881/error.log)
* JS console reports no errors or verbose.
![4](https://user-images.githubusercontent.com/12097274/80721834-bf641900-8b0f-11ea-8abc-58a4f9de60f8.jpg)

* Screenshots: 
![2](https://user-images.githubusercontent.com/12097274/80720341-d1dd5300-8b0d-11ea-854d-2be94980207b.jpg)
![1](https://user-images.githubusercontent.com/12097274/80720351-d30e8000-8b0d-11ea-8bbd-1d8ad47d0a02.jpg)
![3](https://user-images.githubusercontent.com/12097274/80720491-06e9a580-8b0e-11ea-9c82-58077ea19fa2.jpg)

**Comment by PierreRambaud** [comment] 2020-05-04 12:01
@abdu355 Are you sure you provide us all php and apache logs. I didn't see any errors in it :thinking: 
Do you use custom modules?

**Comment by florine2623** [comment] 2020-06-01 14:40
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

**Closed as completed by florine2623** 2020-06-01 14:40 UTC
Labels: Bug, FO, No change required
