### ISSUE TITLE
import with error

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#13679] opened 2019-05-06 10:16 UTC
Prestashop 1.7.5.2 on php 7.2.17
If I try to import a xls/csv and smarty cache is active, at the end of import process I'll have: https://nimb.ws/akJTjR
Sometimes my server goes down after this.
Try again after some minutes, all goes well

**Comment by khouloudbelguith** [comment] 2019-05-07 11:46
Hi @centoasa,

I did not manage to reproduce the issue with PS1.7.5.2.
I attached a video record
https://drive.google.com/file/d/13LASmXksKc6TVsSqXW1NdI2szzgL1dJk/view
Could you please provide me the exact file you tried to import it.
Thanks!

**Comment by centoasa** [comment] 2019-05-07 13:04
in the previous error session, I had "recompile template ..."
Now I have tried like you with the "never compile" and does not generate any errors. We do further tests with all the smarty cache variants

**Comment by khouloudbelguith** [comment] 2019-05-07 13:33
@centoasa, I tried with this option & it is OK
https://drive.google.com/file/d/1WOPkbm0D21mM-ZdnRm_xwwZyAxtJ09n7/view
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by centoasa** [comment] 2019-05-08 07:05
file for import attached
[tele-test1.xlsx](https://github.com/PrestaShop/PrestaShop/files/3155931/tele-test1.xlsx)
the issue happens always on first istance, after first all goes well.
But I've to clear cache manually whenever import session?

**Comment by khouloudbelguith** [comment] 2019-05-08 07:59
Hi @centoasa,

I just imported your file for the first time successfully.
https://drive.google.com/file/d/1WGEMiKn2-qImCUMdKp5bqU7p5m2tIbvf/view
NO, you don't need to clear cache manually whenever import session.
But you can configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2019-06-07 07:25
Hi @centoasa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-06-07 07:25 UTC
Labels: BO, Can't reproduce, Import / Export, 1.7.5.2

**Comment by centoasa** [comment] 2019-06-07 07:27
To have better result, without error, it's better disable cache first of import session, and after re-index search.
