### ISSUE TITLE
 You can add products to your cart that you do not have in stock.

### ISSUE THREAD

**Issue by 4itsoft** [PrestaShop/PrestaShop#13946] opened 2019-05-23 16:11 UTC
**Describe the bug**
You can add products that you do not have in stock by double-clicking.

**To Reproduce**
1. Go to BO and set 1 quantity available.
2. Double-Click on 'Add to cart'
3. See error: In the cart you will have 2 pieces, although there is only one piece in stock.

**Screenshots**
![image](https://user-images.githubusercontent.com/50216024/58268638-74357800-7d8e-11e9-976e-2309e3d442a9.png)
![image](https://user-images.githubusercontent.com/50216024/58268796-cd9da700-7d8e-11e9-8771-7b3f0d0d2104.png)
![image](https://user-images.githubusercontent.com/50216024/58268671-84e5ee00-7d8e-11e9-81c2-9f9528eb0620.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2019-05-24 07:33
Hi @4itsoft,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #11631
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-24 07:33
Duplicate of #11631

**Comment by francoispeyret** [comment] 2019-05-24 08:58
it's not exactly the same bug

@khouloudbelguith  it's just two request to cart controller too close ?

**Comment by khouloudbelguith** [comment] 2019-05-24 09:44
@4itsoft, I tried with PS1.7.5.2 & PS1.7.6.0beta1 => it is OK
I attached a video record
https://drive.google.com/file/d/1SdTjaVO-YWJJp6gztpOlRE4z72YoNDL9/view
Thanks to check & feedback

**Comment by marionf** [comment] 2019-06-03 14:29
@khouloudbelguith 
Duplicate of #9974

**Closed as completed by marionf** 2019-06-03 14:29 UTC
Labels: FO, Duplicate, 1.7.5.2
