### ISSUE TITLE
Customer's group is not displayed anywhere

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23116] opened 2021-02-03 07:58 UTC
#### Describe the bug

Merchant is unable to determine customer's group, unless he edits that customer.
It's very important for determining prices, discounts and communication with the customer.

#### Expected behavior

Customer group should be displayed on order screen and on customer's detail.
On order page, we can display it the same as we display "Guest" under customers name.
On customer detail page, it can be simply displayed in the information table.

**Screenshots**
How it can be done
![customer](https://user-images.githubusercontent.com/6097524/106715708-bacc1400-65fd-11eb-9787-ef3e43a8a1a7.JPG)

How guest is displayed
![guest](https://user-images.githubusercontent.com/6097524/106715711-bb64aa80-65fd-11eb-921b-b9f1410eee04.JPG)

Where it can be displayed on customer page
![customer screen](https://user-images.githubusercontent.com/6097524/106715718-be5f9b00-65fd-11eb-8222-7680f22bb0c7.JPG)

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-03 10:38
Hello @Hlavtox 

Related to #22643
I think what you suggest is not a bug it's an improvement, cause like you mentioned above when a guest made an order:

![image](https://user-images.githubusercontent.com/23308427/106734800-bad70e80-6613-11eb-93a4-757ac1033579.png)

But when a customer made an order:

![image](https://user-images.githubusercontent.com/23308427/106734981-f376e800-6613-11eb-8e28-bb72091c0449.png)

Well, I see is not necessary cause if it's not mentioned as Guest, so ofc it's a customer and we don't have another Customer Group that can make an order besides those two Groups (Customer, Guest). wdyt?

**PS: thanks for testing the whole Order page** :clap: :wink: 

Thanks!

**Comment by Hlavtox** [comment] 2021-02-03 11:21
@hibatallahAouadni It's more targeted to other groups. Usually merchants create other groups for business customers. So, I thought it would be good to see which group the customer is in. :)

**Comment by hibatallahAouadni** [comment] 2021-02-03 15:10
@Hlavtox you're right :wink: 

Ping @PrestaShop/product-team I think it's a good idea to add the **Customer Group** name to the Order like **Guest**, do you think it's doable?

**Comment by Hlavtox** [comment] 2021-06-22 19:58
@hibatallahAouadni 
Order view page - https://github.com/PrestaShop/PrestaShop/pull/25080
Order create page - https://github.com/PrestaShop/PrestaShop/pull/25091
Customer detail page - TODO

**Comment by MatShir** [comment] 2021-06-23 09:14
It is a great idea ! The layout is need to challenged by the @PrestaShop/ux-team, but it looks promising :)
Customer can link to multiples user groups, so we need to anticipate the display for example for 3 user groups.

**Comment by Progi1984** [comment] 2021-07-20 08:25
@PrestaShop/ux-team @TristanLDD Some news ?

**Comment by prestascott** [comment] 2021-07-20 14:34
Hello everyone,

Thanks @Hlavtox for this improvement! 

**Order view page**

Instead of just putting the text as you did, I would change it into a tag component. It will allow users to identify easier which customer group(s) the customer is linked to. 

Here are my design propositions:

_Order view page - a single customer group_
![Frame 7 (1)](https://user-images.githubusercontent.com/54888056/126342379-04c1a689-f1ca-4058-ab82-bcc93b2707e2.png)

_Order view page - many customer groups_
![Frame 6 (1)](https://user-images.githubusercontent.com/54888056/126342284-0145837b-9c1a-4a06-b2de-08cdc69f1ea6.png)

**Order create page**

I won't change anything in your design except adding the label of the content. It's important for users to understand what the content is about. Wdyt @Julievrz ?

_Order create page - many customer groups_
![Group 1 (2)](https://user-images.githubusercontent.com/54888056/126343025-8b1b4ec4-73b6-44da-91dd-2aa69c1f7d69.png)

Wdyt? :)

**Comment by Hlavtox** [comment] 2021-07-20 15:59
@prestascott Looks good, but if there are more groups than 1, the default group should be suffixed by **- default**.

And I think we can omit the labels. If a merchant does not know that **johndoe@gmail.com** is an email, he shouldn't be employed in ecommerce... 😄

**Comment by Julievrz** [comment] 2021-07-27 10:09
I agree that the "email" label might not be necessary here, but maybe a label "Groups:" could be useful?

However, is the ID of the group really necessary? Isn't the name of the group sufficient? I find the # everywhere confusing, especially since there is already a # in the top right-hand corner that has a different purpose. 

+ Yes, we should mention which group is the default one.

**Comment by Hlavtox** [comment] 2021-07-27 10:12
@Julievrz @prestascott I would also ditch the ID, not needed IMHO, they should not have duplicate names... 👍

Yeah, but I would do only **Group: Customer** or **Groups: Customer, VIP customer**, we will save a bit of space.

**Comment by Julievrz** [comment] 2021-07-30 08:22
Yes, I agree that we should not display the group IDs next to their names (too many #, it's confusing). 

Only keep "Group:" or "Groups:" (That would be two strings, and the good one would display depending on the number of groups). 

For the default group, we can display "(Default)" next to the group's name.

**Comment by hibatallahAouadni** [comment] 2021-07-30 09:09
@MatShir @prestascott @Julievrz @Hlavtox 
Thanks guys for your hard working and your approvals :tada: 
We have a GO :rocket:

**Comment by hibatallahAouadni** [comment] 2021-12-01 10:22
@Hlavtox should I reopen the issue? cause it seems there's another related PR not merged yet.

**Comment by Hlavtox** [comment] 2021-12-01 14:13
@hibatallahAouadni You can, I want to also add it to customer detail page, so we can see it immediately :-)

**Comment by hibatallahAouadni** [comment] 2021-12-01 14:21
@Hlavtox done :slightly_smiling_face:

**Closed as completed** 2022-01-06 12:58 UTC
Labels: PM ✔️, UX ✔️, Feature, BO, Order, Customer groups, Fixed, Wording ✔️, PR available, 1.7.7.1
