### ISSUE TITLE
Remove meta keywords from Prestashop

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19114] opened 2020-05-13 13:50 UTC
I think having meta keywords field everywhere is not needed, because they are not used for **more than 10 years**.

They have absolutely no effect for SEO and search engines ignore them. No point of keeping this ancient relict in the UI. 😄

**Comment by colinegin** [comment] 2020-05-13 14:28
Hello @Hlavtox ,

Thanks for your feedback.

your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/11144.
I close this issue, so that we can keep working on the other issue.

Do not hesitate to consult the EPIC related to all SEO improvements : #18402 

Thanks !

**Comment by colinegin** [comment] 2020-05-13 14:29
Duplicate of #11144

**Closed as completed by colinegin** 2020-05-13 14:28 UTC
Labels: Duplicate
