### ISSUE TITLE
Prestashop Multistore random cookie ID

### ISSUE THREAD

**Issue by Myrjam** [PrestaShop/PrestaShop#15804] opened 2019-10-03 07:51 UTC
So this is the first time I report something, please be patient should I be doing this wrong.

I was notified that in multistore the cookie ID's of the store is handed out randomly and not fixed. This causes all kinds of problems for example that the EU law cookie notification keeps appearing.

Thanks Myrjam

**Comment by khouloudbelguith** [comment] 2019-10-03 10:30
Hi @Myrjam,

Thanks for your report.
Could you please add steps to reproduce the issue in a new comment.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - screenshots

Thanks!

**Comment by Myrjam** [comment] 2019-10-04 07:42
I don't have much more information. I've had a module that didn't work as it was supposed to. The developer of the module said this was the cause of the problem.
I noticed myself that every time I visit the front of my store (after restarting my PC for example) I get a notification that I should only get once.
Prestashop version is 1.7.6.1

**Comment by khouloudbelguith** [comment] 2019-10-04 08:01
@Myrjam, so the issue occurs due to this module? is it?

Thanks!

**Comment by Myrjam** [comment] 2019-10-04 08:18
It is the other way around, the module experiences problems due to the fact that prestashop hands outs random cookie ID's in multistore.

**Comment by khouloudbelguith** [comment] 2019-10-04 08:45
@Myrjam, could you please add this line
`var_dump(Context::getContext()->cookie);` to your file `index.php` & check if there are random cookies.
In the meantime, you can find this document about cookies
[250518_COOKIE_POLICY_FR (1).pdf](https://github.com/PrestaShop/PrestaShop/files/3689691/250518_COOKIE_POLICY_FR.1.pdf)

Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-04 07:52
Hi @Myrjam,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-11-04 07:52 UTC
Labels: Multistore, No change required
