### ISSUE TITLE
invalid date_to field DISCOUNT ERROR

### ISSUE THREAD

**Issue by Jaimetonala** [PrestaShop/PrestaShop#24974] opened 2021-06-15 15:42 UTC
#### Describe the bug

I can't change a period for discounts in Cart Rules and Catalog Price Rules

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1.	Go to BO > Catalog > Discounts
2.	Create or edit a Cart Rule or Catalog Price Rule
3.	Change the validity period of the rule by clicking on the date calendar
4.	Save
5.	See error : "The date_to field is invalid.

#### Additional information

* PrestaShop version: 1.7.6.8

![error al modificar fecha](https://user-images.githubusercontent.com/85950869/122083238-faeba080-ce00-11eb-8b21-f5f83eca714f.JPG)

**Comment by hibatallahAouadni** [comment] 2021-06-15 16:33
Hello @Jaimetonala 

I have seen your comment in the other issue :wink: 
Well the issue is caused by your browser calendar or some third module calendar, as you can see, the updated date has not the same pattern as the old date, and that caused the problem.
So, you need to find the module whose implement a different JS calendar than the default one and disable it.
Please check and feedback.

Thanks!

**Comment by florine2623** [comment] 2021-07-06 07:53
Hello @Jaimetonala ,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2021-07-06 07:53 UTC
Labels: Bug, BO, Discounts, Catalog price rules, No change required, 1.7.6.8
