### ISSUE TITLE
Multishop Logo bug

### ISSUE THREAD

**Issue by MichaMa** [PrestaShop/PrestaShop#34745] opened 2023-12-01 11:05 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a Mainstore (Teambro) and a Multishop Store (DSC Volley). I uploaded the Logos via Design > Template & Logo for the mainstore - head, invoice and favicon.
Than, I uploaded the Logos for Multishop "DSC Volley".
And now, the Invoice Logo from Multishop store displays in mainstore.

The exact same error has existed since Prestashop 1.6.

![multishop](https://github.com/PrestaShop/PrestaShop/assets/44434227/15fa810c-4786-4a36-acce-a050d4e854df)

### Steps to reproduce

1. Select the Main Store
2. go to Design > Template & Logo
3. Upload Logos and Favicon
4. Change the Shop to a Multishop
5. Upload Logos and Favicon
6. Change the Shop to Main Store and see the wrong Logo

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-12-04 11:13
Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/32708

I'm closing it to avoid clogging the backlog

**Closed as completed by florine2623** 2023-12-04 11:13 UTC
Labels: Bug, Duplicate
