### ISSUE TITLE
Cant add order from back office.

### ISSUE THREAD

**Issue by sewingau** [PrestaShop/PrestaShop#15269] opened 2019-08-27 04:36 UTC
I'm not very tech savvy but when i add to cart into a selected customers 'new order' it does not work... I never had any problems before. its been broken for at least 2 weeks.
im in Australia. using 1.7.5. Netorigin is my domain host.

**Comment by khouloudbelguith** [comment] 2019-08-27 07:56
Hi @sewingau,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-26 07:33
Hi @sewingau,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-09-26 07:33 UTC
Labels: Bug, BO, Order, No change required, 1.7.5.2
