### ISSUE TITLE
The product-list on the checkout does not work with custom themes

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#25221] opened 2021-07-03 14:47 UTC
#### Describe the bug

This fix https://github.com/PrestaShop/PrestaShop/issues/9634 breaks the "Add to cart" buttons in the product-list in all custom themes.

Short movie:
https://www.loom.com/share/1ed22057f0964fee84eaaf9bcc73a3c9

Fix https://github.com/PrestaShop/PrestaShop/issues/9634 adds to core.js this code to disable the "Add to cart" button:
$('[data-button-action="add-to-cart"]').prop('disabled', true);

The problem is that all custom themes use this code:
data-button-action="add-to-cart"
to add the "Add to cart" button in the product-list, which means that after an update to 1.7.8.x all shops with custom themes will have this problem and it is difficult to fix it directly in the theme.

You can go here:
https://addons.prestashop.com/en/3-templates-prestashop
open any theme and check the source code of the "Add to cart" button in the product-list to see that all themes use in the product-list that code:
data-button-action="add-to-cart"

#### Expected behavior

The "Add to cart" button should be disabled only on the product page in the form:
form#add-to-cart-or-refresh

In means that this code in the core.js:
$('[data-button-action="add-to-cart"]').prop('disabled', true);

should be replaced with something as this:
$('form#add-to-cart-or-refresh [data-button-action="add-to-cart"]').prop('disabled', true);

or this code should be removed from core.js and added to /themes/classic/assets/js/theme.js

#### Steps to Reproduce

1.Install a custom theme with the "Add to cart" button in the product-list.

2.Click the "Add to cart" button in the product-list.

3.After the popup is closed, all other buttons will be disabled.

**Screenshots**
Before clicking the "Add to cart" button:
https://prnt.sc/18a24cm

after closing the popup, all buttons are disabled:
https://prnt.sc/18a1zux

Short movie:
https://www.loom.com/share/1ed22057f0964fee84eaaf9bcc73a3c9

#### Additional information

* PrestaShop version: 1.7.8.0

**Comment by kpodemski** [comment] 2021-07-03 14:52
Hello @Angar90, and thank you for your report. You're completely right. We even talked about this with @Oksydan, who reported this a while ago. Thank you for the reminder :)

I'll look into this as soon as possible to fix this regression before the 1.7.8 release.

**Comment by hibatallahAouadni** [comment] 2021-07-05 10:56
Hello @Angar90 

I was able to reproduce the issue with PrestaShop version 1.7.8.x. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-07-21 14:20
Fixed in #25316 by @kpodemski

**Closed as completed by Progi1984** 2021-07-21 14:20 UTC
Labels: Bug, Major, FO, Regression, Fixed, Shopping carts FO, PR available, 1.7.8.0, 1.7.8.x
