### ISSUE TITLE
BO - Experimental Feature - The help modal cannot be opened

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23996] opened 2021-04-12 09:00 UTC
#### Describe the bug

If this PR: https://github.com/PrestaShop/PrestaShop/pull/23703 is merged, a new BO page Experimental Feature is displayed, in this page, the help modal cannot be opened.
As discussed with @matks,` it makes sense! this is a new BO page, so there is no related help page on help.prestashop.com`

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Experimental Feature page
2. Click on 'Help'
![image](https://user-images.githubusercontent.com/16067358/114368989-3b6b3b80-9b7e-11eb-8c8e-6768ba069f18.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by matks** [comment] 2021-04-30 12:44
@Julievrz We have 2 options
1. We create a new Help page for "Experimental Features" page - this must be done by you
2. I improve the code that controls this window, so that we have issues on the page even if there is no Help page for "Experimental Features" page - this I can do

If we chose strategy 2, I can
a. hide the "help" button
or
b. when we open the window I display an error message "no help page for this BO page 😭 "

**Comment by Julievrz** [comment] 2021-05-03 07:33
Hi @matks 
I think this page should be documented. But my problem is: where should this documentation page be created? On Confluence or on GitBook? 
No page is supposed to be added on Confluence now that we have GitBook...
@MatShir What do you think?

**Comment by Julievrz** [comment] 2021-05-07 15:11
Hi @matks, I sent you the URL so you can add it. :)

**Comment by matks** [comment] 2021-05-10 07:38
@Julievrz looks like it was not enough 😅 

The new page does not seem available yet on help.prestashop.com . I think something must be done on help.prestashop.com to acknowledge the new documentation page, and make it available for the Back Office.

No idea what must be done though 🤷‍♂️

**Comment by matks** [comment] 2021-05-13 13:34
For your information, ~I found the root cause of the bug~ (this was found false later as you can read in https://github.com/PrestaShop/PrestaShop/issues/23996#issuecomment-864452139)

The help sidebar content is loaded using jQuery `load()` https://api.jquery.com/load/

When help.prestashop.com returns a 404 response, the Access Origin headers of the response are not accepted by `load()` which introduces the CORS error. On 200 responses no issue.

By adding the new Feature Flag Help page on help.prestashop.com we will have a 200 response instead of 404 and the issue should be gone.

**Comment by matks** [comment] 2021-06-14 15:46
FYI I am now able to deploy help.prestashop.com so I can carry on

**Comment by MatShir** [comment] 2021-06-14 17:07
At the end of the week, I will provide a bit of content for the user doc page so we can test it :)

**Comment by Julievrz** [comment] 2021-06-14 17:16
> At the end of the week, I will provide a bit of content for the user doc page so we can test it :)

Thanks! Don't hesitate to ask me if you need help to review it. ☺️

**Comment by matks** [comment] 2021-06-17 13:39
help.prestashop.com has been deployed to provide the needed content although it is very minimal for now https://help.prestashop.com/en/doc/AdminFeatureFlag?version=1.7.8.0 and https://help.prestashop.com/fr/doc/AdminFeatureFlag?version=1.7.8.0

**Comment by matks** [comment] 2021-06-17 13:42
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/25004

**Comment by Progi1984** [comment] 2021-06-19 17:35
Fixed by @matks in #25004

**Closed as completed by Progi1984** 2021-06-19 17:35 UTC
Labels: Bug, develop, Minor, BO, Regression, Fixed, PR available

**Comment by matks** [comment] 2021-06-19 19:17
> For your information, I found the root cause of the bug
> 
> The help sidebar content is loaded using jQuery `load()` https://api.jquery.com/load/
> 
> When help.prestashop.com returns a 404 response, the Access Origin headers of the response are not accepted by `load()` which introduces the CORS error. On 200 responses no issue.
> 
> By adding the new Feature Flag Help page on help.prestashop.com we will have a 200 response instead of 404 and the issue should be gone.

For your information this was false. 🟠 

I was loading the wrong data using `load()` : I was loading the direct content of `https://help.prestashop.com/en/doc/AdminFeatureFlag?version=1.7.8.0` but what other BO pages actually do is that they load the content of the page `/admin-dev/index.php/common/sidebar/{encodedDocLink}` (`{encodedDocLink}` is `https://help.prestashop.com/en/doc/AdminFeatureFlag?version=1.7.8.0` ... encoded) which is a link computed by `FrameworkBundleAdminController:: generateSidebarLink()`.

The link when hit performs a server-side download of the content of `https://help.prestashop.com/en/doc/AdminFeatureFlag?version=1.7.8.0` so CORS do not apply on it.

I fixed this in https://github.com/PrestaShop/PrestaShop/pull/25004/
