### ISSUE TITLE
An error occurred while processing your request for products with RELATED PRODUCTS

### ISSUE THREAD

**Issue by AlexCrete** [PrestaShop/PrestaShop#13874] opened 2019-05-20 11:44 UTC
Hello,

I have this error only if a product has some RELATED PRODUCTS, as here: https://www.luzibiza.com/dressesjumpsuits/144-258-trapeze-dress.html#/1-sizes_for_clothes-s

But everything is all right if there is no related product as, for example here: https://www.luzibiza.com/dressesjumpsuits/83-227-rio-dress.html#/1-sizes_for_clothes-s

Could you, please, have a look at this problem?
I've tried the solution you described up here but nothing chandged - it seems my case has nothing to do with nginx.

I use PrestaShop version: 1.7.5.1

Server information Linux #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
Server software version: LiteSpeed
PHP version: 5.6.40
MySQL version: 10.1.24-MariaDB-cll-lve

Your web browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:60.0) Gecko/20100101 Firefox/60.0

Missing files (3)
	•	INSTALL.txt
	•	package-lock.json
	•	docker-compose.yml

Thank you in advance

**Comment by khouloudbelguith** [comment] 2019-05-20 11:54
Hi @AlexCrete,

Thanks for your report.
In the BO => Shop Parameters => Traffic & Seo page, if you disable the friendly URL, the issue happens again?
Thanks!

**Comment by AlexCrete** [comment] 2019-05-20 12:23
yes
![Screen Shot 2019-05-20 at 14 22 12](https://user-images.githubusercontent.com/50266769/58021281-c4040d00-7b0a-11e9-9b21-bb070bd4c056.png)

**Comment by AlexCrete** [comment] 2019-05-20 12:25
yes
![Screen Shot 2019-05-20 at 14 22 12](https://user-images.githubusercontent.com/50266769/58021417-1e9d6900-7b0b-11e9-91b7-7282e23d4459.png)

**Comment by khouloudbelguith** [comment] 2019-05-20 12:55
@AlexCrete, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.5.1.
https://drive.google.com/file/d/10sNh77Q43-lBDrv0jkf2VCfAwePdfwI8/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by AlexCrete** [comment] 2019-05-20 14:32
>   debug mode report 
- is it it?

Notice on line 227 in file /home/luzi2018/domains/luzibiza.com/public_html/modules/psaddonsconnect/psaddonsconnect.php
[8] Undefined variable: advice

Notice on line 228 in file /home/luzi2018/domains/luzibiza.com/public_html/modules/psaddonsconnect/psaddonsconnect.php
[8] Undefined variable: link_advice

>    PHP error logs
- ufortunately I have no access to PHP error log - or, maybe I can find it somewhere in Symfony 
profiler?

>    apache error log:

#2 /home/luzi2018/domains/luzibiza.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'luzi2018_pr1', 'G[O*Rkd@EukNjun...', Array)
#3 /home/luzi2018/domains/luzibiza.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL in /home/luzi2018/domains/luzibiza.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
2019-05-20 14:21:30.346696 [INFO] [185.75.37.71:53204:HTTP2-181] File not found [/home/luzi2018/domains/luzibiza.com/private_html/undefined] 
2019-05-20 14:21:30.783718 [INFO] [185.75.37.71:53204:HTTP2-181:lsapi] Abort request processing by PID:2336903, kill: 1, begin time: 0, sent time: 0, req processed: 0
2019-05-20 14:21:34.416733 [INFO] [185.75.37.71:53204:HTTP2-191] Abort request processing by PID:2337066, kill: 1, begin time: 0, sent time: 0, req processed: 1
2019-05-20 14:21:35.147215 [INFO] [185.75.37.71:53204:HTTP2-205] Pending AIO operation, recycle later...
2019-05-20 14:21:35.333998 [INFO] [185.75.37.71:53204:HTTP2-209] File not found [/home/luzi2018/domains/luzibiza.com/private_html/undefined] 
2019-05-20 14:21:40.096328 [INFO] [185.75.37.71:53204:HTTP2-253] File not found [/home/luzi2018/domains/luzibiza.com/private_html/undefined] 
2019-05-20 14:28:07.437942 [INFO] [54.36.148.159:38940] File not found [/home/luzi2018/domains/luzibiza.com/private_html/5-topsshirts] 
2019-05-20 15:07:25.880186 [INFO] [54.36.148.214:42668] File not found [/home/luzi2018/domains/luzibiza.com/private_html/14-trousers]

**Comment by AlexCrete** [comment] 2019-05-20 14:39
> debug mode report   

- is it it? 

  Notice on line 227 in file /../../../luzibiza.com/public_html/modules/psaddonsconnect/psaddonsconnect.php [8] Undefined variable: advice 
Notice on line 228 in file /../../../luzibiza.com/public_html/modules/psaddonsconnect/psaddonsconnect.php [8] Undefined variable: link_advice

>  PHP error logs   

- ufortunately I have no access to PHP error log - or, maybe I can find it somewhere in Symfony profiler?   

> apache error log:  

#2 /../../../luzibiza.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'luzi2018_pr1', 'G[O*Rkd@EukNjun...', Array)
#3 /../../../luzibiza.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL in /home/luzi2018/domains/luzibiza.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
2019-05-20 14:21:30.346696 [INFO] [185.75.37.71:53204:HTTP2-181] File not found [/../../../luzibiza.com/private_html/undefined] 
2019-05-20 14:21:30.783718 [INFO] [185.75.37.71:53204:HTTP2-181:lsapi] Abort request processing by PID:2336903, kill: 1, begin time: 0, sent time: 0, req processed: 0
2019-05-20 14:21:34.416733 [INFO] [185.75.37.71:53204:HTTP2-191] Abort request processing by PID:2337066, kill: 1, begin time: 0, sent time: 0, req processed: 1
2019-05-20 14:21:35.147215 [INFO] [185.75.37.71:53204:HTTP2-205] Pending AIO operation, recycle later...
2019-05-20 14:21:35.333998 [INFO] [185.75.37.71:53204:HTTP2-209] File not found [/../../../luzibiza.com/private_html/undefined] 
2019-05-20 14:21:40.096328 [INFO] [185.75.37.71:53204:HTTP2-253] File not found [/../../../luzibiza.com/private_html/undefined] 
2019-05-20 14:28:07.437942 [INFO] [54.36.148.159:38940] File not found [/../../../luzibiza.com/private_html/5-topsshirts] 
2019-05-20 15:07:25.880186 [INFO] [54.36.148.214:42668] File not found [/../../../luzibiza.com/private_html/14-trousers] 
--

javascript console log
 Powered by AMP ⚡ HTML – Version 1905091827220 "https://stackoverflow.com/questions/4539253/what-is-console-log" amp4ads-v0.js:576:73
JQMIGRATE: Migrate is installed, version 1.4.1  jquery-migrate.min.js:2:542
The service[0] (//freegeoip.net/json/?callback={callback}) responded with the following error <unavailable>  cookieconsent.min.js:1:18311
The service[1] (//ipinfo.io) responded with the following error <unavailable>  cookieconsent.min.js:1:18311
The service[2] (//js.maxmind.com/js/apis/geoip2/v2.1/geoip2.js) responded with the following error <unavailable>  cookieconsent.min.js:1:18

**Comment by khouloudbelguith** [comment] 2019-05-20 15:16
@AlexCrete,

I access to your Shop FO, I have this exception
![image](https://user-images.githubusercontent.com/16067358/58032453-86a77b80-7b1a-11e9-9ae5-3a0dcd6ac73e.png)
Do you have any override in your core files of any class?
It could be not compatible.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-20 15:18
@AlexCrete, also, you have this error
https://drive.google.com/file/d/1iGGtcvazjrwM2ekVo1jk-LEy4Xo5XUF4/view
Thanks!

**Comment by AlexCrete** [comment] 2019-05-22 22:46
Hello, thank you for your reply, I tried to make any use of it but failed - it's not my level. So, I went back to my PS 1.7.4.4 version, - it is without any changes in classes or core. but the problem is still there - if a "Main" product has a Related Product the error ocuring - and more!
If I order product but don't go after that for checking or to basket - I got an image of a Related Product on a "main" product page. Just image. The description doesn't change. Weird.  I tried the solution from here: https://www.prestashop.com/forums/topic/973271-fix-an-error-occurred-while-processing-your-request-nginx-multilingual-shop/
It does not work - maybe because our shop is not multiligual?

**Comment by AlexCrete** [comment] 2019-05-22 22:54
As a matter of fact the shop doesn't even pay attantion if there is or there is no such a file as "nginx.conf.dist" - it works in the same way without "nginx.conf.dist" at all.

**Comment by khouloudbelguith** [comment] 2019-05-23 14:35
Hi @AlexCrete,

The nginx.conf.dist file is the configuration for your Nginx server, 
> it works in the same way without "nginx.conf.dist" at all.

How is it possible?

Thanks!

**Comment by andersgk** [comment] 2019-05-24 12:57
I have the same problem with Litespeed as my webserver.
While add more quantity to order, i can error 500 in my console.
When enable Debug mode i got this error while manual go to the link: [Debug] This page has moved
Prestashop 1.7.5.1
Webserver: Litespeed
PHP: 7.1

**Comment by khouloudbelguith** [comment] 2019-05-24 13:09
@andersgk, did you use the nginx server also?
Thanks!

**Comment by andersgk** [comment] 2019-05-24 13:17
@khouloudbelguith no, im using Litespeed as the topic creator does.

**Comment by khouloudbelguith** [comment] 2019-05-24 13:19
@andersgk, this issue occurs with a friendly URL is enabled or disabled?

Thanks!

**Comment by andersgk** [comment] 2019-05-24 13:21
@khouloudbelguith it is with friendly URL enabled.

**Comment by khouloudbelguith** [comment] 2019-05-24 13:25
@AlexCrete, when friendly URL is disabled => No issue occurs?
THanks!

**Comment by AlexCrete** [comment] 2019-05-24 13:34
as a matter of fact I don't use nginx server, just Apache (sorry for stupidity) - and have no possibility to configurate it. It'a a dedicated server. Any solution for this case maybe?

**Comment by khouloudbelguith** [comment] 2019-05-24 13:42
@AlexCrete, could you please navigate to your BO => Shop Parameters =>  `Set up URLs` section & provide me a screenshot
![image](https://user-images.githubusercontent.com/16067358/58331968-3427d100-7e32-11e9-9f43-5b30ca283628.png)

Thanks!

**Comment by AlexCrete** [comment] 2019-05-24 13:47
yes, here it is:
![Screen Shot 2019-05-24 at 15 44 51](https://user-images.githubusercontent.com/50266769/58332287-32aed680-7e3b-11e9-867b-fd233904be89.png)

**Comment by khouloudbelguith** [comment] 2019-05-24 13:48
@AlexCrete, thanks!
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thank you!

**Comment by AlexCrete** [comment] 2019-05-24 14:21
thank you for reply, 
in "defines.inc.php" I turned 
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', true);
}
but cannot see any php errors.
Can you?

**Comment by khouloudbelguith** [comment] 2019-05-24 14:39
@AlexCrete,
You need to enable debug mode in your store and debug request which is sent for product save in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. change the combination
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by AlexCrete** [comment] 2019-05-24 14:51
is it it?

[PrestaShopObjectNotFoundException]

Can not retrieve the id_product_attribute
at line 6143 in file classes/Product.php

6138.                 );
6139.             }
6140.         }
6141. 
6142.         
if (empty($idProductAttribute)) {
6143.             throw new PrestaShopObjectNotFoundException('Can not retrieve the id_product_attribute');
6144.         }
6145. 
6146.         return $idProductAttribute;
6147.     }
6148. 
ProductCore::getIdProductAttributeByIdAttributes - [line 6155 - classes/Product.php] - [3 Arguments]
ProductCore::getIdProductAttributesByIdAttributes - [line 956 - controllers/front/ProductController.php] - [2 Arguments]
ProductControllerCore->getIdProductAttribute - [line 992 - controllers/front/ProductController.php] - [1 Arguments]
ProductControllerCore->getTemplateVarProduct - [line 330 - controllers/front/ProductController.php]
ProductControllerCore->initContent - [line 255 - classes/controller/Controller.php]
ControllerCore->run - [line 428 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

**Comment by AlexCrete** [comment] 2019-05-24 15:00
Is it it?

[PrestaShopObjectNotFoundException]

Can not retrieve the id_product_attribute
at line 6143 in file classes/Product.php


6138.                 );
6139.             }
6140.         }
6141. 
6142.         if (empty($idProductAttribute)) {
6143.             throw new PrestaShopObjectNotFoundException('Can not retrieve the id_product_attribute');
6144.         }
6145. 
6146.         return $idProductAttribute;
6147.     }
6148. 


ProductCore::getIdProductAttributeByIdAttributes - [line 6155 - classes/Product.php] - [3 Arguments]
ProductCore::getIdProductAttributesByIdAttributes - [line 956 - controllers/front/ProductController.php] - [2 Arguments]
ProductControllerCore->getIdProductAttribute - [line 992 - controllers/front/ProductController.php] - [1 Arguments]
ProductControllerCore->getTemplateVarProduct - [line 330 - controllers/front/ProductController.php]
ProductControllerCore->initContent - [line 255 - classes/controller/Controller.php]
ControllerCore->run - [line 428 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

**Comment by AlexCrete** [comment] 2019-05-24 15:01
6138.                 );6139.             }6140.         }6141. 6142.         if (empty($idProductAttribute)) {6143.             throw new PrestaShopObjectNotFoundException('Can not retrieve the id_product_attribute');6144.         }6145. 6146.         return $idProductAttribute;6147.     }6148.

**Comment by khouloudbelguith** [comment] 2019-05-24 15:16
@AlexCrete, you have an issue in this line: https://github.com/PrestaShop/PrestaShop/blob/b7ace3922022bcac57dfc8aed34331eacaed19f8/classes/Product.php#L6407

Could you please display this return using `print_r` or `var_dump`?

Thanks!

**Comment by AlexCrete** [comment] 2019-05-24 16:26
hi,
I am no sure that I did it correct, please, don't laugh at me.
So i did it: 
    public static function getIdProductAttributesByIdAttributes($id_product, $id_attributes, $find_best = false)
    {
        
        $a = $id_product;
        $b = $id_attributes;
        $c = true;
var_dump($a, $b, $c);

        return self::getIdProductAttributeByIdAttributes($id_product, $id_attributes, $find_best);
    

    }

and got in console

int(172)array(1) { [7]=> string(2) "37"}bool(true)

Is it any good?

**Comment by AlexCrete** [comment] 2019-05-24 17:17
return self::getIdProductAttributeByIdAttributes($id_product, $id_attributes, $find_best);
   
        $a = $id_product;
        $b = $id_attributes;
        $c = $find_best;
        $d = true;
var_dump($a, $b, $c, $d);  

Can not retrieve the id_product_attribute
at line 6143 in file classes/Product.php

**Comment by khouloudbelguith** [comment] 2019-05-27 12:52
Hi @AlexCrete,

In your case, this error `Can not retrieve the id_product_attribute` is displayed only if `idProductAttribute` is empty.

You can check that in your database `ps_product_attribute_combination` table.

Thanks!

**Comment by AlexCrete** [comment] 2019-05-28 20:04
Hi khouloudbelguith,
I checked. Not a single position in id_product_attribute is empty, as on screenshot:
![Screen Shot 2019-05-28 at 21 58 47](https://user-images.githubusercontent.com/50266769/58508519-7fc0de80-8194-11e9-9a11-59471002618e.png)

**Comment by khouloudbelguith** [comment] 2019-05-29 09:32
@AlexCrete, could you please provide me the exact result of this SQL command

`Select * from ps_product_attribute_combination where id_attribute = 37;`

Thanks!

**Comment by AlexCrete** [comment] 2019-05-29 11:59
Thank you for your reply,
here it is:

-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: May 29, 2019 at 01:55 PM
-- Server version: 10.1.24-MariaDB-cll-lve
-- PHP Version: 5.6.38

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `xxxxxxxx`
--

-- --------------------------------------------------------

--
-- Table structure for table `ps_product_attribute_combination`
--

CREATE TABLE `ps_product_attribute_combination` (
  `id_attribute` int(10) UNSIGNED NOT NULL,
  `id_product_attribute` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ps_product_attribute_combination`
--

INSERT INTO `ps_product_attribute_combination` (`id_attribute`, `id_product_attribute`) VALUES
(37, 263),
(37, 269),
(37, 271),
(37, 276),
(37, 278),
(37, 281),
(37, 286),
(37, 288),
(37, 290),
(37, 293),
(37, 296),
(37, 299),
(37, 302),
(37, 305),
(37, 309),
(37, 314),
(37, 319),
(37, 322),
(37, 326),
(37, 328),
(37, 332),
(37, 333),
(37, 337),
(37, 340),
(37, 344),
(37, 345),
(37, 346),
(37, 347),
(37, 348),
(37, 351),
(37, 352),
(37, 353),
(37, 355),
(37, 357),
(37, 360),
(37, 363),
(37, 365),
(37, 370),
(37, 378),
(37, 381),
(37, 384);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ps_product_attribute_combination`
--
ALTER TABLE `ps_product_attribute_combination`
  ADD PRIMARY KEY (`id_attribute`,`id_product_attribute`),
  ADD KEY `id_product_attribute` (`id_product_attribute`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by khouloudbelguith** [comment] 2019-05-29 12:32
@AlexCrete, I think, your issue is similar to this https://github.com/PrestaShop/PrestaShop/issues/9919#issuecomment-490441708

Thanks to check & feedback

**Comment by AlexCrete** [comment] 2019-05-29 12:56
Yes, I think it is similar. Is there any solution?

**Comment by khouloudbelguith** [comment] 2019-05-29 13:03
@AlexCrete, we are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9919, please follow #9919
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-29 13:03
Duplicate of #9919

**Closed as completed by khouloudbelguith** 2019-05-29 13:03 UTC
Labels: Bug, FO, Duplicate, Combinations, 1.7.5.1
