### ISSUE TITLE
Wrong Vat-Display

### ISSUE THREAD

**Issue by SunOne20** [PrestaShop/PrestaShop#36147] opened 2024-05-14 09:18 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

we use Prestashop 1.7.4.1

A few weeks ago I noticed that the sales tax was being calculated incorrectly for certain net prices and this also affects the final total in the invoice. Since Prestashop cuts off the last 4 decimal places, we end up missing 1 cent per item each time and we have a difference between the online order and our merchandise management invoice.

If I enter the price of an item:
Net 5.90 +20% VAT = 7.08 (correct)
Net 6.90 +20% VAT = 8.279999 (wrong – correct would be 8.28)
Net 7.90 +20% VAT = 9.48 (correct)

So, as soon as I change the price to 6.90, the calculation is incorrect no matter which item.
Interesting: the same thing happens even with a multiple of 6.90, e.g. 13.80.

This is a program error! Are there any other insights into this? Is an update planned for this BUG?

### Expected behavior

a correct representation of the sales tax for all prices that are net divisible by 6.90 (6.90/13.80/20.70/27.60.....etc)

### Steps to reproduce

1. go to article
2. change the net price to 6,90
3. an now check the price including tax = it shall be 8,28 but it shows 8,2799999

### PrestaShop version(s) where the bug happened

1.7.4.1

### PHP version(s) where the bug happened

7.1

### Your company or customer's name goes here (if applicable).

Sanon Handels GmbH

**Comment by florine2623** [comment] 2024-05-14 09:25
Hello @SunOne20 ,

Please change your admin folder name for security reasons.
This is a public space.

I can't reproduce your issue on the new product page. I suggest upgrading to a newer version of PrestaShop.
<img width="1440" alt="Screenshot 2024-05-14 at 11 24 05" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0fa0239f-8f44-4cd6-ad3f-334e9662c814">

Closing the issue as I cannot reproduce it.
Thanks!

**Closed as completed by florine2623** 2024-05-14 09:25 UTC
Labels: Bug
