### ISSUE TITLE
Bug with features in product page

### ISSUE THREAD

**Issue by MaMouT514** [PrestaShop/PrestaShop#17524] opened 2020-02-06 09:12 UTC
Hi,
I've found a bug the in admin product page edition, in features section :
_If you don't choose a feature but you put something in the "customized value", that will create a ghost feature.
After that, on each save (automatic or not), you will have another ghost and it's impossible to remove them.
There is no alert on creation/edition with empty feature with customized value._

Have a good day

![bug_presta](https://user-images.githubusercontent.com/1770663/73922140-f5a34b00-48c8-11ea-9dd3-5677293a554e.png)

**Comment by khouloudbelguith** [comment] 2020-02-06 09:14
Hi @MaMouT514,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9680
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-02-06 09:15
Duplicate of #9680

**Closed as completed by khouloudbelguith** 2020-02-06 09:14 UTC
Labels: Duplicate, Features

**Comment by MaMouT514** [comment] 2020-02-06 09:18
Oops ... I checked before but it looks like I haven't been good.
