### ISSUE TITLE
Bad image when filtering

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#25529] opened 2021-08-05 17:38 UTC
#### Describe the bug

Hello,

When I put a different image on the cover for a variation, you can see it on the product sheet when you change the size.

However, when I filter the size in the category, the image does not change

Can you please help me?

Thank you

**Screenshots**

https://drive.google.com/file/d/1O9b2NcHCNyomK-KuOM0kwEUU5205qptN/view

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2021-08-06 07:02
Hi @ShaimyWinda,

We are aware of the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12501
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-08-06 07:02
Duplicate of #12501

**Closed as completed by khouloudbelguith** 2021-08-06 07:02 UTC
Labels: Duplicate
