### ISSUE TITLE
TinyMCE - No scrollbar issue on Prestashop 1.7.5.0

### ISSUE THREAD

**Issue by lilyrose78** [PrestaShop/PrestaShop#12469] opened 2019-02-06 16:41 UTC
I have the same bug than this closed ticket : https://github.com/PrestaShop/PrestaShop/pull/7790
On my Prestashop 1.7.5.0, product description is hard to edit because there is no scrollbar on tinymce editor and the height is really small.

I checked the bug fix on the last ticket and the fix seem to be on my files version, but the problem is still there.

**To Reproduce**
1. Go to Admin > Edit product
2. Try to edit / add a long text
3. Try to scroll, there is no scroll, we can only use the keyboad arrows

**Screenshots**
![screenshot-www cageauxtrolls com-2019 02 06-11-40-20](https://user-images.githubusercontent.com/47394113/52357373-10b45400-2a04-11e9-9073-6768fc9ff22a.png)

** Video **
https://drive.google.com/file/d/1NDoZJeuwJGxiWPsJPiqslpp8oZ70j55z/view

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment] 2019-02-06 16:52
Hi @lilyrose78,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1WTm4d183sL7eNoS2mHde85styNPE5R0h/view
THanks to check & feedback.

**Comment by lilyrose78** [comment] 2019-02-06 17:24
Hi @khouloudbelguith 

I try on Chrome and Firefox, same problem. 
I made a video record too : https://drive.google.com/file/d/1NDoZJeuwJGxiWPsJPiqslpp8oZ70j55z/view

**Comment by thbl** [comment] 2019-02-06 18:40
@lilyrose78  is this a clean install ? maby you have a modul that interfere with the tinymce css

**Comment by khouloudbelguith** [comment] 2019-02-07 07:54
@lilyrose78, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-08 08:17
Hi @lilyrose78,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-08 08:17 UTC
Labels: BO, No change required, 1.7.5.0
