### ISSUE TITLE
Email Subject is not translated

### ISSUE THREAD

**Issue by norbertlaza** [PrestaShop/PrestaShop#19091] opened 2020-05-12 11:00 UTC
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Open  'ps_reminders.php'
`Mail::Send(
                    (int)$email['id_lang'],
                    'followup_1',
                    Mail::l(
                        'Your cart and your discount',
                        (int)$email['id_lang']
                    ),`
Line 238 'Your cart and your discount', must be translated, this is added to email subject.

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment] 2020-05-12 12:56
Hi @norbertlaza ,
Thanks for the recommandation. Please stay tuned !

**Comment by florine2623** [comment] 2020-05-12 12:57
Hello @PrestaShop/prestashop-core-developers ,

In both PS 1.7.6.5 and 1.7.7, I could not manager to translate the title of the emails of ps_reminder :
![Capture d’écran 2020-05-12 à 14 50 56](https://user-images.githubusercontent.com/16019289/81693814-c3256300-9460-11ea-9ad2-42245c05a8ad.png)
Can this feature be implemented ?

Thanks !

**Comment by khouloudbelguith** [comment] 2020-08-04 11:20
Hi @florine2623, @norbertlaza,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9599
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-08-04 11:20
Duplicate of #9599

**Closed as completed by khouloudbelguith** 2020-08-04 11:20 UTC
Labels: BO, Duplicate, Translations, Customer reminder, 1.7.7.0, 1.7.6.5
