### ISSUE TITLE
Error "You have requested a non-existent service" while decorating OrderController

### ISSUE THREAD

**Issue by adviva** [PrestaShop/PrestaShop#29286] opened 2022-08-09 13:44 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is about OrderController decorate in a custom Symfony module. 

This decorate works in ps 1.7.8 while we get the error in ps version 8.0 beta-1.
It looks like OrderController is not a public service.

<img width="1428" alt="Schermata 2022-08-09 alle 09 32 14" src="https://user-images.githubusercontent.com/26090185/183630908-33ab4cc1-39e5-4c1a-8106-1051018973ad.png">

The OrderController seems to be available debugging the container, the same in version 1.7.8

<img width="1423" alt="Schermata 2022-08-09 alle 12 56 37" src="https://user-images.githubusercontent.com/26090185/183638515-dcb21466-3ed0-42c5-a140-3cdb55bc97a4.png">

Cache of services and routes is not clear automatically after module installation

To test better the issue you can install this test module:
[pcomtest.zip](https://github.com/PrestaShop/PrestaShop/files/9290586/pcomtest.zip)

### Expected behavior

1. installation process have finished succesfully
2. cache is clear automatically
3. the decorated controller is called properly. You can see that inside Symfony’s debug bar (screenshot underneath)”

<img width="1425" alt="Schermata 2022-08-09 alle 13 22 51" src="https://user-images.githubusercontent.com/26090185/183651299-73748836-d0e6-45ab-952d-5e983b7d5df7.png">

### Steps to reproduce

1. install module test 
2. go to module folder and run composer install
3. clear cache (i remember this was processed automatically after install)
4. go to B.O page
5. see the error

### PrestaShop version(s) where the bug happened

8.0 beta-1

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-08-09 17:36
Hello @adviva 

I didn't manage to reproduce the issue, see the attached screenshot and screen record below:

![image](https://user-images.githubusercontent.com/23308427/183721944-a980ebf2-12e0-430d-9579-4fc61f555d36.png)

https://user-images.githubusercontent.com/23308427/183721828-b4533d48-3123-4498-bfd2-367a16b141d5.mp4

Please check and feedback.

Thanks!

**Comment by adviva** [comment] 2022-08-10 07:53
Hi @hibatallahAouadni,  seems the decorate is not working in your video.  
See the controller name inside Symfony’s debug bar (screenshot underneath)

<img width="1440" alt="Schermata 2022-08-10 alle 09 31 20" src="https://user-images.githubusercontent.com/26090185/183843621-b4963d72-82a4-4b75-abc3-c0b48fd344cb.png">

I would expect like this screenshot

<img width="1428" alt="Schermata 2022-08-10 alle 09 50 12" src="https://user-images.githubusercontent.com/26090185/183845595-8ff708be-61b8-47af-9bf3-ae6a45227755.png">


Please can you clear PrestaShop cache manually and check again?

I have seen that cache of services and routes is not clear automatically after a module installation (point 3 of steps to reproduce)

Thanks, let me know

**Comment by jolelievre** [comment] 2022-08-10 14:01
Hi @hibatallahAouadni and @adviva 

I tested your module and I confirmed the two issues:
- the symfony cache is not correctly cleared, seems like the clear action is started but probably fails in between because I can see a `_de` temporary folder, maybe because if the following error about missing service
<img width="284" alt="Capture d’écran 2022-08-10 à 15 58 48" src="https://user-images.githubusercontent.com/13801017/183920755-f97d3550-095a-4f91-888f-aad0c5dec769.png">

- after removing the cache manually I can see the same error
<img width="1082" alt="Capture d’écran 2022-08-10 à 16 01 32" src="https://user-images.githubusercontent.com/13801017/183920843-ceab4980-8c91-4904-a65b-3bcf0fa23017.png">

**Comment by matks** [comment] 2022-09-09 16:29
See analysis https://github.com/PrestaShop/PrestaShop/pull/29322#issuecomment-1242195961

**Comment by matks** [comment] 2022-09-12 15:08
@atomiix is looking at it too ;)

**Comment by matks** [comment] 2022-09-15 15:58
@adviva Fixed by https://github.com/PrestaShop/PrestaShop/pull/29322

**Closed as completed by matks** 2022-09-15 15:58 UTC
Labels: Bug, 8.0.x, Major, BO, Order, Modules, Regression, Fixed, PR available, Verified, Prerelease
