### ISSUE TITLE
ps_facetedsearch does not filter if attribute value starts with a hypens '-'

### ISSUE THREAD

**Issue by davideapvd** [PrestaShop/PrestaShop#16585] opened 2019-11-28 11:25 UTC
**Describe the bug**
I have an attribute value like '-20° a +5°' , clicking it nothing is filtered, probably because the generated url contains '-' in a starting position and it is seen as separator

**To Reproduce**
1. Go to category page with a filter value like '-20° a +5°'
2. Click on that filter
3. No product is filtered and the checkbox is not memorized

**Comment by khouloudbelguith** [comment] 2019-11-28 11:32
Hi @davideapvd,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16320
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-11-28 11:32
Duplicate of #16320

**Closed as completed by khouloudbelguith** 2019-11-28 11:32 UTC
Labels: Duplicate
