### ISSUE TITLE
Add "preview" icon and "duplicate" option for CMS pages

### ISSUE THREAD

**Issue by bullmade** [PrestaShop/PrestaShop#29674] opened 2022-09-18 00:04 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

A UX "issue".

### Describe the solution you'd like

Pretty nobrainer if you ask me.
A preview icon that opens the page in a new tab, and then a duplicate button.

![image](https://user-images.githubusercontent.com/16975198/190880115-80bbd342-f252-4a19-83bd-25b17b703ae6.png)

A preview button inside the cms page would be helpful aswell
![image](https://user-images.githubusercontent.com/16975198/190880127-d6c9d627-9d7c-4bc0-91f0-12aa79c0d04e.png)

Also - "Save and preview" button is pointless. It should be called "Save and stay", and then the preview" button should be offered.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment] 2022-09-18 17:46
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/28079

**Comment by paulnoelcholot** [comment] 2022-09-19 08:31
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28079.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Closed as completed by paulnoelcholot** 2022-09-19 08:31 UTC
Labels: Feature, Duplicate, PR available, Invalid

**Comment by paulnoelcholot** [comment] 2022-09-19 08:32
Duplicate of #28079

**Comment by bullmade** [comment] 2022-09-19 08:32
What about the duplicate feature?

**Comment by paulnoelcholot** [comment] 2022-09-19 08:42
Hello @bullmade 

In this issue, you're asking us to add a `preview` button and a `duplicate` button in the **Pages list** and a `preview` button in **Edit Page**.
And as you can see in this feature #28079 @Hlavtox already created a PR where he add these two buttons:

- a `preview` button in the **Pages list**
- a `preview` button in **Edit Page**

So, we can ask @Hlavtox to add a new `duplicate` button in the **Pages list** proposed by you in the same issue and the same PR :wink: 

Thanks!

**Comment by bullmade** [comment] 2022-09-19 08:44
Would be great!
