### ISSUE TITLE
Error 500 when selecting 'shipped' on order status. 1.7.5.1

### ISSUE THREAD

**Issue by sewingau** [PrestaShop/PrestaShop#12923] opened 2019-03-14 13:53 UTC
**Describe the bug**
after updating to 1.7.5.1,,,,,,,,,updating order status (shipped, )takes me to an error 500 screen.
The task is completed when I go back to orders. If I select bulk actions, I go to error 500 screen and only 1 action has been performed when I get back to orders.

**To Reproduce**
1. Go to '..orders.'
2. Click on '.select order box or open single order...'
3. Scroll down to '.update order status. change it and update order status...'

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-03-14 13:56
Hi @sewingau,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-12 15:37
Hi @sewingau,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-12 15:37 UTC
Labels: Bug, BO, Order, No change required, 1.7.5.1
