### ISSUE TITLE
Duplicated submit add to cart Button

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#12274] opened 2019-01-23 12:39 UTC
**Describe the bug**
Bug is tested on clean Prestashop 1.7.4 and 1.7.5. When you click twice or more than once the "Add to cart" button and the popup "Product successfully added to your shopping cart" appears, the button "Continue Shopping" stops to work and "Proceed to checkout" still works. If button is clicked 2 times, the cart will add the product 2 qty.
**To Reproduce**
1. Go to product page
2. Click on "Add to cart" rapidly before "Product successfully added to your shopping cart" appears
3. Popup appears
4. Clicking on "Continue shopping" won't work

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: 7.x

Thanks

**Comment by khouloudbelguith** [comment] 2019-01-23 13:34
Hi @ChineseNorris,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9634
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-23 13:34
Duplicate of #9634

**Closed as completed by khouloudbelguith** 2019-01-23 13:34 UTC
Labels: Duplicate
