### ISSUE TITLE
Wrong link after uninstalling mbo

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#24341] opened 2021-05-04 15:14 UTC
#### Describe the bug

When I uninstall `ps_mbo`, the Module Catalog link doesn't work anymore. It sends you to `/admin-dev/index.php?controller=AdminParentModulesCatalog` instead of `/admin-dev/index.php?controller=AdminModulesCatalog`, resulting in a page not found error:

![localhost_ps17x_admin-dev_index php_controller=AdminParentModulesCatalog token=8be9769ac0444d2ac8a7f96685e004b3](https://user-images.githubusercontent.com/1009343/117019469-b646f280-acf5-11eb-9dde-a9dd575770ec.png)

#### Expected behavior

You should be redirected to `AdminModulesCatalog` instead. Changing the URL in the address to the appropriate controller sends you to the right page:

![localhost_ps17x_admin-dev_index php_improve_modules_catalog_token=8be9769ac0444d2ac8a7f96685e004b3 _token=KM_uL2o3SIdWr96oS4LvSpVNyGvxGzx7l0L4CSPJY9Y](https://user-images.githubusercontent.com/1009343/117019762-045bf600-acf6-11eb-8bef-977a847cc44e.png)

> Note: there's a weird error when capturing screenshots on this page using Chrome's screenshot feature, the menu disappears but only when taking the screenshot.

#### Steps to Reproduce

1. Install shop
2. Uninstall or disable the ps_mbo module
3. Refresh the page
4. Click on Modules > Module Catalogue

#### Additional information

* PrestaShop version: 1.7.7.3 (1.7.7.x branch)
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-05-04 23:12
Hello @eternoendless 

This issue has not full fixed (see my [comment](https://github.com/PrestaShop/PrestaShop/issues/11264#issuecomment-756759597))
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22740. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

**_PS: Sorry_** :grin: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-05-04 23:12
Duplicate of #22740

**Closed as completed by hibatallahAouadni** 2021-05-04 23:12 UTC
Labels: Duplicate
