### ISSUE TITLE
Show wrong quantities in BO product list

### ISSUE THREAD

**Issue by RomanXT** [PrestaShop/PrestaShop#11325] opened 2018-11-08 17:27 UTC
Hello,
There is a problem with the show correct quantity of products showing in BO
It was at prestashop 1.5 and it is still in 1.6
I do not know why it writes two entries in the database, it takes data only where the attributete is 0

![2018-11-06_122040](https://user-images.githubusercontent.com/43031929/48215632-f75b2780-e382-11e8-9762-d9dfca937303.png)
![2018-11-08_181730](https://user-images.githubusercontent.com/43031929/48215635-f75b2780-e382-11e8-9e36-a7d5a8d7c6a5.png)
![2018-11-08_181835](https://user-images.githubusercontent.com/43031929/48215637-f75b2780-e382-11e8-9b91-70537e8feb64.png)
![2018-11-08_182420](https://user-images.githubusercontent.com/43031929/48215935-b0216680-e383-11e8-8cfe-a86b664a938f.png)
![2018-11-08_182451](https://user-images.githubusercontent.com/43031929/48215936-b0216680-e383-11e8-9825-53bb223eec67.png)

Then he gives me false information about the deficiencies on desktop

Prestashop 1.6.1.20
Enable Adwanced Warehouse

**Comment by khouloudbelguith** [comment] 2018-11-09 08:55
Hi @RomanXT,

I did not manage to reproduce the issue with PS 1.6.1.23.
For those products, have you created any attributes?
Also, if you enable the debug mode, is there any exception displayed?
You can enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`

… and change it to:

`define('_PS_MODE_DEV_', true);`

Thanks!

Best regards, Khouloud

**Comment by RomanXT** [comment] 2018-11-09 10:13
Debug mode shows nothing, all amounts are wrong in products where there are variations.
This is not a new problem, we had the same thing at the Prestashop 1.5
Exmaple:
https://www.prestashop.com/forums/topic/253613-wrong-quantities-in-bo-product-list-catalogue/

![2018-11-09_110820](https://user-images.githubusercontent.com/43031929/48256474-020fce00-e410-11e8-9e81-57c817de49b6.png)
![2018-11-09_111300](https://user-images.githubusercontent.com/43031929/48256639-7f3b4300-e410-11e8-836f-344548a5afb9.png)

I can delete both entries but after saving again, two appear and take the number where attribute is 0

**Comment by khouloudbelguith** [comment] 2018-11-09 10:51
Hi @RomanXT,

I did not manage to reproduce the issue, it is OK.
![image](https://user-images.githubusercontent.com/16067358/48258584-b19b6f00-e415-11e8-929f-48bc335f5d24.png)
Thanks!

**Comment by Rolige** [comment] 2018-11-13 01:36
Hi @RomanXT,

I have used PS 1.6 in at least 25+ production stores and I can tell you that the stock works perfectly in a clean store, so the problem must be due to...
- a core modification
- third-party modules
- override file
- or some cron script changing the stock

Try to review these points and you will probably find the problem in your store.

Regards!

**Comment by khouloudbelguith** [comment] 2018-12-14 15:28
Hi @RomanXT,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-12-14 15:28 UTC
Labels: BO, Can't reproduce
