### ISSUE TITLE
When I activate the invoice and create one for a previous order, it generates a double invoice

### ISSUE THREAD

**Issue by jordiweblidera** [PrestaShop/PrestaShop#20719] opened 2020-08-26 07:34 UTC
#### Describe the bug

When I activate the invoice and create one for a previous order, it generates a double invoice

#### Expected behavior

Only one invoice per order

#### Steps to Reproduce

1. Disable invoice
2. Create an order
3. Change order state to Payment accepted
4. Enable invoice
5. Go to order and generate invoice
6. Press download invoice, it generates [invoices.pdf](https://github.com/PrestaShop/PrestaShop/files/5128254/invoices.pdf)
 for two invoices #FA000000 and #FA000003

**Screenshots**

![imagen](https://user-images.githubusercontent.com/49748656/91274304-c4b03800-e77e-11ea-872b-68e0131f84af.png)
![imagen](https://user-images.githubusercontent.com/49748656/91274396-ead5d800-e77e-11ea-9542-09444f9e8eca.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33

**Comment by sarahdib** [comment] 2020-08-26 11:12
Hello @jordiweblidera 

Despite our efforts, we were not able to reproduce your issue with the provided information.
[IN000021 (1).pdf](https://github.com/PrestaShop/PrestaShop/files/5129422/IN000021.1.pdf)
![image (1)](https://user-images.githubusercontent.com/3034677/91296895-a574d300-e79d-11ea-9473-417ce6546ac6.png)
![image (2)](https://user-images.githubusercontent.com/3034677/91296899-a73e9680-e79d-11ea-829b-0fdc78b1df0e.png)

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
I close this issue, feel free to open a new one with more information if you reproduce this again.

Thank you!

**Closed as completed by sarahdib** 2020-08-26 11:12 UTC
Labels: No change required

**Comment by jordiweblidera** [comment] 2020-08-26 12:31
Hi @sarahdib,

I've opened another issue #20728

Regards,
Jordi
