### ISSUE TITLE
Cannot save an old address after making the DNI mandatory for that country

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#22503] opened 2020-12-18 17:03 UTC
#### Cannot save an old address after making the DNI mandatory for that country and the address duplicate

If you try to update (adding the DNI) or delete an address that has been previously used in an order and at the time of creation of the addess the dni was not required but now the dni is required for that country there will be an error and the address cant be updated or deleted and even worse a new address copy of the original will be created every time you attempt to update or delete the address.

#### Expected behavior

The address con be edited and deleted by the customer without error.

#### Steps to Reproduce

1. Install a fresh instance of prestashop 1.7.x.
2. In the front office create a new customer account, insert a test address WITHOUT the dni (using a country that have dni _not_ mandatory _ex:France_) and complete an order. 
2. After the order is completed go in the back office in the section "International->Locations" and select the tab "Countries".
3. Find the country of the address you use on the order in point 1) ex:France and click "Edit"
4. At the bottom of the page on "Do you need a tax identification number?" select "YES" and the save the changes.
5. ![image](https://user-images.githubusercontent.com/9608268/102510665-2b3bc780-4088-11eb-812d-4f23da7221c3.png)
6. In the front office go to the "Home  Your account" section and enter in the "ADDRESSES" page.
7. ![image](https://user-images.githubusercontent.com/9608268/102511102-ac935a00-4088-11eb-9fa3-54b018f4f627.png)
8. Select the address you use for the order at point 1) and click "Update".
9. Insert a DNI and click "Save"
10. Now you get an Error "_address->dni is empty_"
11. 
![image](https://user-images.githubusercontent.com/9608268/102640571-f9476580-415a-11eb-8e97-3dbd152967bb.png)

11. If you return to the address list you will find a new address that has been created. Every time the error at point 10) happen a new address will be created.
12. The error happen also if you try to delete the original address without dni instead of edit it.

I've find the cause in `CustomerAddressPersister` in `function save(Address $address, $token)`.
If an address is used in an order it is not update or deleted but instead a new address is created and the old address is deleted. But  if the old address has been used previously in and order the old address is not deleted from the database but is flagged as "deleted" and so updated using `update()` function of `ObjectModel`. But as the old address has no DNI, because the dni was not required and mandatory at the time of the creation, the operation of update fail.

I've have modified the code of `function delete()` of the class `AddressCore` like in the image:
![image](https://user-images.githubusercontent.com/9608268/102514034-48729500-408c-11eb-9720-4b6d5b728418.png)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.x (i've tried 1.7.6 and 1.7.8)
* PHP version: 7.1

I've have done a pull request to fix this issue here https://github.com/PrestaShop/PrestaShop/pull/22483.

**Comment by florine2623** [comment] 2020-12-18 17:36
Hi @abramofranchetti ,
Thanks for the report.

I've tried on PS 1.7.7.0 and PS 1.7.8.0 and I can't reproduce your issue following your steps.

- After creating a customer account and placing an order on the FO
- I enabled tax identification number on the order's country 
![Capture d’écran 2020-12-18 à 18 31 09](https://user-images.githubusercontent.com/16019289/102643449-960c0200-415f-11eb-921b-fb78df8eff06.png)
- I went back to my customer account
- updated my address and added a VAT identification number
Here's the result :
In BO
![Capture d’écran 2020-12-18 à 18 31 29](https://user-images.githubusercontent.com/16019289/102643472-a15f2d80-415f-11eb-8fa1-7a08ab2ad672.png)
In FO - customer's account 
PS 1.7.7.0
![Capture d’écran 2020-12-18 à 18 30 58](https://user-images.githubusercontent.com/16019289/102643509-ae7c1c80-415f-11eb-95d2-773853b562d6.png)
In PS 1.7.8.0
![Capture d’écran 2020-12-18 à 18 40 19](https://user-images.githubusercontent.com/16019289/102644126-95c03680-4160-11eb-8c99-c55daa659213.png)


Am I missing something ?
Thanks

**Comment by abramofranchetti** [comment] 2020-12-20 15:22
Hi @florine2623 and thank you for investigating the issue.
Try this one:
replicate steps from 1 to 6. **But instead of edit the address from the "address" section of the customer account, try to place another order** and then, in the checkout where you have to select your invoice and shipping address, try to edit the address adding the DNI. **OR try to delete the address**.
![image](https://user-images.githubusercontent.com/9608268/102716882-dfcf2680-42de-11eb-982f-311538bdac9e.png)
![image](https://user-images.githubusercontent.com/9608268/102716957-73085c00-42df-11eb-88b8-e02a394e7118.png)

Thank you again.

**Comment by hibatallahAouadni** [comment] 2020-12-26 11:19
Hello @abramofranchetti 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen records below:

**1. Following your steps from the issue description:**
https://drive.google.com/file/d/1vnXuhWPvryI5wdbrcZI8ybl-ZNacv1ZT/view
**2. Following your steps from your comment:**
https://drive.google.com/file/d/1mpo_RaKu7S1w5ibjFDW3O2-zZexPcYxv/view

Please check and feedback.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-12-29 10:41
Hi @hibatallahAouadni,

This issue is fixed with this PR: #11726 in the PS1.7.6.0, it fixes this issue: #9891

Thanks!

**Comment by hibatallahAouadni** [comment] 2020-12-30 15:16
Hello @abramofranchetti 

Could you please specify what your PrestaShop version?

Thanks!

**Comment by abramofranchetti** [comment] 2021-01-07 09:27
Hi @hibatallahAouadni 
i've done a video using a fresh installation of prestashop 1.7.6.9
you can see the address duplicate but there is no the error. so maybe the error is already fixed here PR: #11726 in the PS1.7.6.0, it fixes this issue: #9891 as you said.

https://user-images.githubusercontent.com/9608268/103874949-17591380-50d2-11eb-8ed1-23c7b12b66d6.mov

**Comment by hibatallahAouadni** [comment] 2021-01-07 11:04
Hello @abramofranchetti 

I followed your steps (step by step as you did in your screen record above) and I didn't manage to reproduce it with PS1.7.7.0.
See my attached screen record below:

https://drive.google.com/file/d/1LUYgQUzB0YniAQtll1jeF2fSEVA3DSbb/view

The only difference between my shop and yours is the Theme :confused: 
Could you please check if your Theme override something and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-27 16:47
Hello @abramofranchetti ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-27 16:47 UTC
Labels: Bug, FO, Locations, Countries, No change required, PR available, 1.7.7.0, 1.7.8.0
