### ISSUE TITLE
carussel de imgen en prestashop 8

### ISSUE THREAD

**Issue by KAYAKBCN** [PrestaShop/PrestaShop#31246] opened 2023-02-07 09:59 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

En la nueva version de presta shop 8 , al intentar actualizar el carrusel de imagenes para realizar algun cambio  me da siempre un error
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

alguna solucion 

### Steps to reproduce

1 diseño
2 tema y logos
3 pagina configuracion
4 silder
5 carussel de imagen
6 configurar 
7 modificar
8 guardar

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment] 2023-02-07 10:12
Hello @KAYAKBCN ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by florine2623** 2023-02-07 10:12 UTC
Labels: Bug, Invalid
