### ISSUE TITLE
Strange behavior when we are moving the mouse under the "Status" label

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12068] opened 2019-01-08 15:08 UTC
**Describe the bug**
The window size 1270px * 899px, in the BO => Product list page => when we are moving the mouse under the status "label" a strange behavior is displayed.

**To Reproduce**
Steps to reproduce the behavior: window size 1270px * 899px
1. Go to BO => Products page
2. Move with the mouse under the label "Status"
3. See error

**Screenshots**
https://drive.google.com/file/d/17NzbfxZz4CfEYDQFD72z8pzV4XVuUpsH/view

**Additionnal information**
PrestaShop version: develop
Server information Linux #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64
Server software version: Apache/2.4.10 (Debian)
PHP version: 7.1.13
Memory limit: 128M
Max execution time: 30
Upload Max File size: 2M
Browser: Google Chrome Version 69.0.3497.81 (Build officiel) (64 bits)

**Comment by marionf** [comment] 2019-01-08 17:22
@khouloudbelguith 

I can't reproduce this issue 

https://drive.google.com/file/d/1d6LzwP_B0ObTkTxwo1ev1NxhxVUVRCxB/view?usp=sharing

**Comment by khouloudbelguith** [comment] 2019-01-09 08:42
Hi @marionf,

What is the exact version Chrome did you use?
Thanks!

**Comment by marionf** [comment] 2019-01-09 09:02
Version 71.0.3578.98 (Build officiel) (64 bits)

**Comment by khouloudbelguith** [comment] 2019-01-09 09:12
@marionf, could you please try to use Google Chrome Version 69.0 to reproduce the issue.
Thanks!

**Comment by marionf** [comment] 2019-01-14 11:15
@khouloudbelguith I have the last version, I will not downgrade.
Can you try to upgrade you Chrome to the last version and tell me if you still have the issue ?

**Comment by khouloudbelguith** [comment] 2019-01-16 09:52
Hi @marionf,

I will try to upgrade Chrome to the last version to reproduce the issue and I will come back to you.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-16 14:56
Hi @marionf,

I tried with Chrome v71.0.3578.98, in the product after filtering with quantity, we have a strange issue with status, when we filter by status, we have a strange issue with the quantity.
I attached a video record.
[Jan 16, 2019 3_51 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/2764616/Jan.16.2019.3_51.PM.webm.zip)
Thanks!

**Comment by marionf** [comment] 2019-01-16 15:24
@khouloudbelguith What is your screen size ?

**Comment by khouloudbelguith** [comment] 2019-01-16 15:31
@marionf, the window size is 1270px * 899px.
Thanks!

**Comment by marionf** [comment] 2019-02-15 08:41
@khouloudbelguith 

I tried again but can't reproduce this

**Comment by khouloudbelguith** [comment] 2019-02-15 09:39
Hi @marionf,

Yes, I still have the same issue with develop branch.
In the BO => Product list page, if you sort by quantity & I move the mouse under the "Status" label, a strange behavior happens.
I attached a new video record.
https://drive.google.com/file/d/1wPzcSiAdmFu9vM6QjBNeKycKz8y6KxCX/view
Thanks!

**Comment by marionf** [comment] 2019-02-15 13:22
I just managed to reproduce it

**Comment by marionf** [comment] 2019-02-15 13:23
Do you have it also with 1.7.5.0 ?

**Comment by khouloudbelguith** [comment] 2019-02-15 14:29
@marionf, no, I did not manage to reproduce the issue with PS1.7.5.0, in fact with the PS1.7.5.0, the column `Price (Tax incl.)` is not added, But in the develop branch, it is displayed.
![image](https://user-images.githubusercontent.com/16067358/52862569-d8182700-3135-11e9-913e-aa49379d5117.png)
![image](https://user-images.githubusercontent.com/16067358/52862823-76a48800-3136-11e9-9e92-76e49fb5c0c4.png)

Thanks!

**Comment by eternoendless** [comment] 2019-04-08 12:34
This should be fixed by making the table scroll horizontally

**Comment by TristanLDD** [comment] 2019-04-23 16:37
The horizontal scroll for tables is not very recommended as people don't actually see that it's scrollable and miss the lasts items. 

When the window size is too small for proper display, the best thing to do is to adapt to the screen by displaying less content. So my recommendation would be to display only 'Price (tax excl.)' when the window is less than 1270px. 

The smallest the screen gets, the more essential are the informations ;)

**Comment by colinegin** [comment] 2019-05-22 09:32
This issue has been fixed by adding horizontal scroll.

**Closed as completed by colinegin** 2019-05-22 09:32 UTC
Labels: Bug, UX ✔️, develop, Trivial, BO, Catalog, Regression, Fixed
