### ISSUE TITLE
Error at cart checkout on upgraded shop from 1.6.1.21 to 1.7.4.2

### ISSUE THREAD

**Issue by damiafrau** [PrestaShop/PrestaShop#11170] opened 2018-10-27 15:23 UTC
**Describe the bug**
I upgraded my Prestashop from 1.6.1.21 to 1.7.2.4 and finally to 1.7.4.2. When somebody adds a product to the shopping cart without stay logged in, it works. But when the customer log in, then a message is shown on cart page: The product NAME OF PRODUCT in your cart, have no longer availability. Can't proceed with checkout until you adjust the quantity. (May the text be different as I am translating from Spanish).

I checked that there is enough quantity of the product, it happens with different customers, and browsers. If I uncheck Stock administration, the error doesn't show, but there is no control over orders and customers can order items without stock.

**To Reproduce**
1. Create an account into activeliving.es
2. Log off.
3. Add a product to the shopping cart
4. Go to checkout
5. Log in with your user

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2018-10-29 08:29
Hi @damiafrau,

I did not manage to reproduce the issue.
I attached a video record.
https://drive.google.com/file/d/1fiamLaAZpHHGg8VNYmvJr_fAOqZIfEZW/view
Thanks to check it & feedback.
Thanks!

**Comment by damiafrau** [comment] 2018-10-29 17:10
Hi,

Thank you for your message. It happens with customers who had previous sessions in PS 1.6. New customers who registered with PS 1.7 are fine.

How can I send you via PM an existing user to make a new test?

**Comment by khouloudbelguith** [comment] 2018-10-29 17:17
Hi @damiafrau,

This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-30 08:40
Hi @damiafrau,

I added to the cart another product. When I log in with the user that you provided me, I don't manage to reproduce the issue.
I attached a video record.
https://drive.google.com/file/d/1NVbwrOBUzWwTsIDRMLq0aZlRrOxOEOfj/view
Thanks to check & feedback.

**Comment by damiafrau** [comment] 2018-11-08 07:51
Hi,

It happened me again, and after making some different tests, I found the solution. The problem is related to products. If a product has `advanced_stock_management` = 1 in tables ps_product and ps_product_shop, then it can be added to cart, but at time of checkout, PS 1.7 tells you there aren’t enough stock to complete the order.

To solve the problem:

SELECT <https://activeliving.es:2083/cpsess0572150533/3rdparty/phpMyAdmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/select.html> DISTINCT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME IN <https://activeliving.es:2083/cpsess0572150533/3rdparty/phpMyAdmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/comparison-operators.html#function_in> ('advanced_stock_management') AND <https://activeliving.es:2083/cpsess0572150533/3rdparty/phpMyAdmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/logical-operators.html#operator_and> TABLE_SCHEMA=‘your_database_name_here’;

UPDATE `ps_product` SET `advanced_stock_management`= 0;

UPDATE `ps_product_shop` SET `advanced_stock_management`= 0;


After that, I’m able to make the order.

Thanks for trying to help me.


Damia

**Comment by khouloudbelguith** [comment] 2018-11-08 07:54
Hi @damiafrau,

Thanks for the feedback & for your fix suggestion.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-08 07:54 UTC
Labels: FO, Autoupgrade, Fixed, 1.7.4.2
