### ISSUE TITLE
Shipping cost not displayed / not calculated

### ISSUE THREAD

**Issue by Sting55** [PrestaShop/PrestaShop#24526] opened 2021-05-17 14:04 UTC
#### Describe the bug

- on order summary page shipping cost isn't appear and summary price is wrong (see screenshot "order-summary.png")
- on order confirmation page (payment page)shipping cost appear and summary price is right (see screenshot "order-confirmation.png")

#### Expected behavior

The shipping cost should appear and add up to the cost of the products in order summary page.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.0

**Comment by hibatallahAouadni** [comment] 2021-05-17 15:59
Hello @Sting55 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem. See the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/118519554-8528e200-b739-11eb-847c-a966a32a4252.png)

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-17 15:59 UTC
Labels: Can't reproduce
