### ISSUE TITLE
Incorrect discount label for specific price

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#33716] opened 2023-08-24 10:30 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The discount label for specific prices in the checkout are not displayed correctly when the specific prices applied to different combinations from the same product.

### Steps to reproduce

1- Check that quantity discounts are based on `Products`
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/9ec8368d-0712-426d-b469-970294f7ffce)

2- Create 2 specific prices for 2 and 4 units
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/5aa3656e-b827-4026-9b0b-57a318708b86)

3- Add 1 unit of 2 different combinations. The price is discounted with 10%, but the discount label is not displayed:
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/c8d6e0b6-95a9-4a2e-ab10-b3607415259a)
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/33235b21-fbca-4a56-a3be-59359b2b4f96)

4- Add 2 units for each combination. The price is discounted with 20% but the 10% discount is displayed, instead of 20%:
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/04a869aa-7778-4de5-849e-8bb95201b35c)

### PrestaShop version(s) where the bug happened

8.1.0

### Your company or customer's name goes here (if applicable).

idnovate.com

**Comment by sallemiines** [comment] 2023-08-25 09:32
Hello @idnovate 

Thanks for reporting this issue !
Following your steps I didn't reproduce the same issue as you !   
step 3 / 4 are  OK in my side  , but I find that in the cart page , it's always the` 10% discount` which is displayed ( even the 20% is aplicated ) 
you can see the attached screen recorder 

https://github.com/PrestaShop/PrestaShop/assets/31663369/013979e2-850c-4c69-ae2b-d2eb63d8e21f

is this the same probleme as yours ? 
did I miss smthng ? 
Please check and feedback ! 

Thank you

**Comment by idnovate** [comment] 2023-08-25 10:01
Probably I didn't explain myself correctly.

If you base the quantity discount in `Products`, not in `Combinations`, and you set a specific price for 4 units, I understand that 2 units from combination A and 2 units from combination B should be OK for the discount.

Regarding my example, 1 + 1 units should apply 10% discount for 2 units and 2 + 2 (or 3 + 1) should apply 20% discount for 4 units.

The discount, the final price, is correct, but the discount label (10% or 20%) isn't. The discount label only considers the amount per combination, not the sum of all the combinations of the product.

So in this case it should display the "10%" discount label:
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/30c6b720-9743-4a34-b27f-4ffce4459f1b)


And in this one, the "20%":
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/40615783-11e6-44de-8d24-288e4670b3ba)

If you check the price, you will see that the discount is applied correctly and doesn't match the label.

**Comment by hibatallahAouadni** [comment] 2023-08-29 10:57
Hello @idnovate 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27226. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-08-29 10:57
Duplicate of #27226

**Closed as completed by hibatallahAouadni** 2023-08-29 10:57 UTC
Labels: Bug, FO, Duplicate, Shopping carts, Discounts, Invalid, 8.1.x
