### ISSUE TITLE
Requête AJAX - Erreur 403 Impossible de mettre à jour les déclinaisons

### ISSUE THREAD

**Issue by SebastienLi** [PrestaShop/PrestaShop#10198] opened 2018-08-29 13:42 UTC
Impossible to delete combinations of a product.

I see that others people have the same issue.

My version is PS 1.7.2.4

You can see what my browser shows:
![erreur_403](https://user-images.githubusercontent.com/42807682/44790802-76bcc580-aba0-11e8-96fc-f20f143f71d5.jpg)

When I go to this URL :  https://www.monsite/admin/index.php/attribute/6

I got this;

![capture d ecran 2018-08-29 a 15 27 14](https://user-images.githubusercontent.com/42807682/44790932-c602f600-aba0-11e8-9e7e-26137821b697.png)

![capture d ecran 2018-08-29 a 15 27 04](https://user-images.githubusercontent.com/42807682/44790942-cc916d80-aba0-11e8-994b-9b3ab5ce1994.png)

Thanks in advance!

Sébastien

**Comment by khouloudbelguith** [comment] 2018-08-29 13:50
Hi @SebastienLi,

Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to clear cache manually => Thanks to delete the folder into var/cache and feedback.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by SebastienLi** [comment] 2018-08-29 15:23
Hi Khouloud,

Thanks for your response!

Unfornutalely, it doesn't work:(

Sébastien

**Comment by khouloudbelguith** [comment] 2018-08-29 15:31
Hi @SebastienLi,

Have you installed a customized module related to the product combinations?

Best regards, Khouloud

**Comment by SebastienLi** [comment] 2018-08-29 15:53
Hi,

No. I even tried with the Prestashop StartTheme and I have the same issue...  Failed to load... the server responded with a statut of 403()

I asked to my provider if PUT and DELETE method'PHP was installed on the server and it's the case so...

Perhaps the issue comes from Url rewriting... I don't understand.

Sébastien

**Comment by khouloudbelguith** [comment] 2018-08-29 16:04
Hi @SebastienLi,

The error 403 on servers where authentication is required, this usually means that authentication has been accepted but access rights do not allow the client to access the resource.
So, it could be a permission issue on your server.
Thanks to check the issue with your host and feedback.

Best regards, Khouloud

**Comment by SebastienLi** [comment] 2018-08-29 16:43
Hi,

I will check again but I already changed permission and my provider says that the issue get from Prestashop:)

Thanks for your help

Sébastien

**Comment by SebastienLi** [comment] 2018-08-29 17:10
Hi,

Finally, I fixed the issue.  PUT and DELETE method'PHP were disabled on my .htaccess:)

Thanks

Sébastien

**Comment by khouloudbelguith** [comment] 2018-08-30 08:02
Hi @SebastienLi,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-08-30 08:02 UTC
Labels: Bug, 1.7.2.4, Combinations, Fixed

**Comment by SharakPL** [comment] 2019-01-31 08:51
@SebastienLi @khouloudbelguith was there PR for that? It keeps happening in 1.7.5.0. I think it would be very much helpful if prestashop admin had some checks on Advanced -> Information page to test these small configuration glitches.

Adding this to .htaccess is suppose to be the solution (I confirm it works):
```
<RequireAny>
    Require method DELETE GET POST PUT OPTIONS
</RequireAny>

<Limit GET POST PUT DELETE HEAD OPTIONS>
    Order allow,deny
    Allow from all
</Limit>
<LimitExcept GET POST PUT DELETE HEAD OPTIONS>
    Order deny,allow
    Deny from all
</LimitExcept>
```
as stated here https://www.prestashop.com/forums/topic/945641-cant-delete-product-combinations-on-1743/?do=findComment&comment=3032818

**Comment by khouloudbelguith** [comment] 2019-01-31 10:31
@SharakPL, with fresh install 1.7.5.0, I did not manage to reproduce the issue. (I did not edit my .htacess file)
[htaccess.zip](https://github.com/PrestaShop/PrestaShop/files/2816738/htaccess.zip)
I attached a video record.
https://drive.google.com/file/d/1XrQGRmNhMY4LDUwQvzWOobg21Wp-JYue/view
Thanks!

**Comment by SharakPL** [comment] 2019-01-31 12:38
@khouloudbelguith because it's all related to specific server configuration. I also didn't experience it on localhost or 2 other servers. But the configurations may differ and the problem is prestashop doesn't inform that something is wrong. Simply nothing happens if I try to delete a combination and debug mode just shows 40x error as response but nothing about what's causing it. It would be much better if there was a feature in admin panel to test if all the required methods like DELETE, PUT or proper db connection encoding are available on the server. Problem occurs when you need to move your store to other server with slightly different configuration.

**Comment by loetje88** [comment] 2020-08-30 10:50
Still same problem on 1.7.5.

No error or anything, combinations simply will not disappear when deleting them.

Force compilation is on, cache is off, cleared cache manually many times, edit the code to .htacces file - nothing works.

Save buttons becomes grey as well while processing until i do a refresh of the page (does not finish processing as well)  but eventually wont delete any combinations.

Very annoying that this still happends after releasing many previous versions, and even the new ones, but old problems cannot be solved.

I have several domains at same hoster, with exact same configuration, this problems only happends with presta 1.7 installations.

**Comment by loetje88** [comment] 2020-12-25 20:29
Tried the .htacces solution on fresh install of ps 1.7.7 and - even after all these updates - this still does not work.
Force compilation is on, cache is off and emptied.
Just same old problem : click on delete combination, screen / save button will freeze on loading and that's it.

When using ctrl+f5 to get things working again, combination is still there.

Good old thirtybees and ps 1.6 for me it is  :) 
Its a shame they refuse to fix this.
