### ISSUE TITLE
'map-delivery-canvas' in order details page is not shown - missing API key for Google Maps 1.7.6.3

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#18066] opened 2020-03-09 17:22 UTC
Hi everybody, 

on order details page at the customer address (delivery and invoice) the Google Map is not shown cause of missing Google Maps API key:

![image](https://user-images.githubusercontent.com/44971218/76239890-97a0b500-6232-11ea-9580-a966c265cf86.png)

thanks for checking and feedback ☺

PS 1.7.6.3
php 7.2.1
nginx/1.14.0

**Comment by khouloudbelguith** [comment] 2020-03-09 17:26
Hi @didi-2018,

Your ticket is a duplicate of #10393
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-09 17:26
Duplicate of #10393

**Closed as completed by khouloudbelguith** 2020-03-09 17:26 UTC
Labels: Duplicate
