### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by k2165** [PrestaShop/PrestaShop#10895] opened 2018-10-08 02:09 UTC
Describe the bug
500 Internal Server Error 

To Reproduce

Login background
Click on Modules & Services menu
![image 6](https://user-images.githubusercontent.com/43941963/46589895-70940000-cae1-11e8-8505-a8a7e727e50c.png)

wait a minute
then show error
![image 8](https://user-images.githubusercontent.com/43941963/46589938-f87a0a00-cae1-11e8-9514-0a8abc0973b5.png)

Additionnal information
PrestaShop version: 1.6.1.4
PHP version: 5.5.38

**Comment by khouloudbelguith** [comment] 2018-10-08 08:08
Hi @k2165,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- debug mode report
- PHP error logs
- apache error log
- javascript console log

Don't you know how to get this information? Please read the following article:

**Adding logs**
Sometimes you just don’t know what’s wrong: something’s not happening, that’s all.

That’s where log data can be helpful. They keep track of what is happening and allows to trace back to the moment when the issue happens.

There are several different log data that you can add as a file to your ticket:

**Server log:**
Apache: /var/log/apache/apache_error.log
Nginx: /var/log/nginx/nginx_error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles
**PHP error log:**
Apache: /var/log/apache/php_error.log
Nginx: /var/log/php-fpm/default/error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles
**Console log:**
Firefox and Chrome: press Ctrl+Shit+J or Cmd+Shift+J.
Internet Explorer and Edge: press F12 then go to the Console tab.
Copy the content relevant to your issue (or to the time the issue appeared), and paste it into the ticket (or in a text file attached to the ticket).

Enabling Debug Mode + cache
PrestaShop has a debug mode, which can be used to see the non-obvious errors in your shop. For instance, in these situations:

The browser displays a blank page.
The browser displays a 500 Internal Server Error.
You cannot log into your dashboard, or access certain pages of the back office.
To turn on the Debug mode on PrestaShop, follow these steps using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

define('PS_MODE_DEV', false);

… and change it to:

define('PS_MODE_DEV', true);

Finally, emptying the cache of PrestaShop can also be useful, because it ensures that your browser only displays newly-generated files instead of old cached ones. In PrestaShop, you can empty the cache here:

Go to Advanced Parameters > Performance.
Click on the “Clear Cache” button at the top right.

Thanks!

**Comment by k2165** [comment] 2018-10-08 11:38
Hi khouloudbelguith :
I press Ctrl + Shit + J when I Click on Modules & Services menu.
Here is snapshot.
![error](https://user-images.githubusercontent.com/43941963/46606977-c1334980-cb31-11e8-9702-0e37b5d2f5d2.png)

**Comment by idnovate** [comment] 2018-10-08 13:03
Enable debug mode and paste the error that you get

**Comment by khouloudbelguith** [comment] 2018-10-08 14:20
Hi @k2165,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache from your shop & your browser.
Thanks to check and feedback.

**Comment by idnovate** [comment] 2018-10-08 14:25
> Hi khouloudbelguith :
> I press Ctrl + Shit + J when I Click on Modules & Services menu.
> Here is snapshot.
> ![error](https://user-images.githubusercontent.com/43941963/46606977-c1334980-cb31-11e8-9702-0e37b5d2f5d2.png)

@k2165 
This JS error is not related with the other error. This is an error throwed by a moduel from @Dh42

**Comment by Dh42** [comment] 2018-10-08 14:34
Unhook the module from the header, that will solve the javascript error. That is our advertising block it is trying to load.

**Comment by khouloudbelguith** [comment] 2018-10-08 16:00
@k2165,

As it's not the module provided by Prestashop, we can't do anything with this. 
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by Dh42** [comment] 2018-10-08 16:04
The 500 error is not caused by our module, it just loads a javascript snippet. There would be no javascript snippet in the source of the 500 error page. This is a prestashop issue.

**Comment by khouloudbelguith** [comment] 2018-10-08 16:24
@Dh42 thanks!
@k2165 we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

**Comment by k2165** [comment] 2018-10-09 01:58
> @Dh42 thanks!
> @k2165 we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Hi khouloudbelguith:
Is this PHP error log  ?
![image 11](https://user-images.githubusercontent.com/43941963/46642447-d77cec00-cba9-11e8-9dcb-beea490b912b.png)

And after I Enable Debug Mode then click on  Modules & Services menu.
The following screen pops up:
![image 7](https://user-images.githubusercontent.com/43941963/46642776-68a09280-cbab-11e8-91eb-86c744d0d004.png)

**Comment by Dh42** [comment] 2018-10-09 02:08
FTP into your site, and go to the modules directory, find the module named newsletterpro and rename it with an underscore in front of the name, like _newsletterpro.

**Comment by k2165** [comment] 2018-10-09 02:16
> FTP into your site, and go to the modules directory, find the module named newsletterpro and rename it with an underscore in front of the name, like _newsletterpro.

Hi Dh42:
I can find and rename it .
And the next ?Try again?

thanks !

**Comment by Dh42** [comment] 2018-10-09 02:18
Yeah, try to load the modules page again and see if you get the 500 error.

**Comment by k2165** [comment] 2018-10-09 02:44
> Yeah, try to load the modules page again and see if you get the 500 error.

Hi Dh42:

Actually, it didn’t appear 500 error  in the morning.
So I am not sure if it is related to this change.
But it still appears this image:

![](https://user-images.githubusercontent.com/43941963/46642776-68a09280-cbab-11e8-91eb-86c744d0d004.png)
And I am afraid that it will be good or bad.
I want to know the cause or the root problem.

thanks a lot.

**Comment by Dh42** [comment] 2018-10-09 03:01
The cause of the problem is the person that wrote the opay module has some undefined variables and a couple other things. Nothing major, turn debug mode off and move on.

**Comment by khouloudbelguith** [comment] 2018-10-09 08:22
@k2165, yes the error is caused because of the opay module, for a quick fix you need to connect to your FTP, in the PROJECT_FOLDER/modules search for the opay folder, rename it.
You should contact the module author via your addons.prestashop.com account.
Thanks!

**Comment by k2165** [comment] 2018-10-09 08:39
> The cause of the problem is the person that wrote the opay module has some undefined variables and a couple other things. Nothing major, turn debug mode off and move on.

Hi Dh42:

OK!Thanks.

And thank you, every respondent.

**Comment by k2165** [comment] 2018-10-09 08:44
> @k2165, yes the error is caused because of the opay module, for a quick fix you need to connect to your FTP, in the PROJECT_FOLDER/modules search for the opay folder, rename it.
> You should contact the module author via your addons.prestashop.com account.
> Thanks!

Hi khouloudbelguith .

Ok thank you 

And Thank you,every respondent.

**Comment by khouloudbelguith** [comment] 2018-10-09 08:44
@k2165, the issue is solved?

**Comment by k2165** [comment] 2018-10-09 09:14
> @k2165, the issue is solved?

Hi khouloudbelguith:

Yes, thanks a lot.

**Comment by khouloudbelguith** [comment] 2018-10-09 09:19
@k2165 thanks for your feedback.
I close the issue, feel free to open a new one when needed.
Thanks!

**Closed as completed by khouloudbelguith** 2018-10-09 09:19 UTC
Labels: BO, Modules, Fixed

**Comment by k2165** [comment] 2018-10-12 09:16
Hi 
I'm back again .
Today 500 Internal Server Error appear again.
This is the once error text in my exception.log:
*ERROR* 	2018/10/12 - 17:07:17: Unknown column 'everywhere' in 'where clause'<br /><br /><pre>SELECT * FROM `ps_ppbp_block` WHERE block_position=1 AND active=1 AND (product ="210" OR global_cat=1 OR global_man=1 OR global_prod=1 OR global_features=1 OR everywhere=1) AND shop="1" ORDER BY position</pre> at line 791 in file classes/db/Db.php

And this time I also Enble Debug Mode.
But it didn't appear any messages.
thanks

**Comment by idnovate** [comment] 2018-10-12 10:06
This is a problem with a module and you should not report it here. It seems it's a problem with Related Products Pro module, could be?

**Comment by khouloudbelguith** [comment] 2018-10-12 11:42
@k2165, you need to disable the Products Pro module.
Thanks!

**Comment by k2165** [comment] 2018-10-15 02:17
> @k2165, you need to disable the Products Pro module.
> Thanks!

How can I disable the Products Pro module?

**Comment by khouloudbelguith** [comment] 2018-10-15 10:12
@k2165, you need to navigate to BO => Modules and Services => search for this module in the list module & disable it.
Thanks!

**Comment by k2165** [comment] 2018-10-15 10:32
> @k2165, you need to navigate to BO => Modules and Services => search for this module in the list module & disable it.
> Thanks!

I just can't enter Modules and Services .
So, is there any other way?

thanks

**Comment by khouloudbelguith** [comment] 2018-10-15 10:42
Hi @k2165,

So, in your project folder, in the PROJECT_FOLDER/modules/, you need to rename the folder of this product pro module, it should be displayed with teck name.

**Comment by k2165** [comment] 2018-10-16 01:18
> Hi @k2165,
> 
> So, in your project folder, in the PROJECT_FOLDER/modules/, you need to rename the folder of this product pro module, it should be displayed with teck name.

I don't have product pro folder.
But there are many folders that about the product. 
![image](https://user-images.githubusercontent.com/43941963/46986919-6cd92c80-d124-11e8-9b62-72fbc3e15d01.png)
thanks

**Comment by khouloudbelguith** [comment] 2018-10-16 11:00
@k2165, you need to rename one by one, clear cache & check.
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.

**Comment by idnovate** [comment] 2018-10-16 11:10
Maybe the folder is called "relatedproductpro"

**Comment by k2165** [comment] 2018-10-18 03:25
> @k2165, you need to rename one by one, clear cache & check.
> As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.

Hi @khouloudbelguith :
I want to ask the cache is in browser or website?
But,I have tried both of them.  
And  it's no change in results.

thanks!

**Comment by k2165** [comment] 2018-10-18 03:37
> Maybe the folder is called "relatedproductpro"

Hi @idnovate : 
I find a folder name relatedproduct and rename it.
I can successfully click on the Modules & Services test for the first time.
But the second time is fail.

thanks !

**Comment by k2165** [comment] 2018-10-18 04:00
It's the log in error log.

[15-Oct-2018 10:44:02 Asia/Taipei] PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'smush' not found in /projectname/modules/prestaspeed/smushit.inc.php on line 72
[18-Oct-2018 09:22:40 Asia/Taipei] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /project/modules/cronjobs/cronjobs.php on line 287

And it's the message in debug mode.
![image](https://user-images.githubusercontent.com/43941963/47130684-4c98a180-d2cd-11e8-801e-7ce4ae917de0.png)

**Comment by khouloudbelguith** [comment] 2018-10-18 07:37
Hi @k2165,

You need to disable also the ppb module.
You can rename the ppb folder into the folder Project_folder/modules/
Thanks!

**Comment by k2165** [comment] 2018-10-18 10:06
> Hi @k2165,
> 
> You need to disable also the ppb module.
> You can rename the ppb folder into the folder Project_folder/modules/
> Thanks!

Hi @khouloudbelguith : 
I rename it and it appear this error:
*ERROR* 	2018/10/18 - 18:04:23: Table 'kaohomsm_ps4.ps_extratabsproextracontents' doesn't exist<br /><br /><pre>SELECT id_extracontents FROM `ps_extratabsproextracontents` AS tab WHERE (tab.`id_product` = 2364 AND tab.`id_tab` = 1)</pre> at line 791 in file classes/db/Db.php

**Comment by khouloudbelguith** [comment] 2018-10-18 10:14
@k2165, it is a problem from a custom module "extratabsproextracontents".
You need to disable it.
Thanks!

**Comment by k2165** [comment] 2018-10-18 10:26
Hi @khouloudbelguith : 
I just have extratabspro module ,and I disable.
But that makes me unable to use debug mode..
thanks!

**Comment by khouloudbelguith** [comment] 2018-10-18 10:42
Hi @k2165,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by k2165** [comment] 2018-10-18 10:48
> Hi @k2165,
> 
> As it's not a module provided by Prestashop, we can't do anything with this.
> You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
> Thanks!

Hi @khouloudbelguith : 
Ok! I will try it.
thank you for your response.
