### ISSUE TITLE
use the standards for each currency and not the language standards, which are the decimal and group symbols

### ISSUE THREAD

**Issue by theGera** [PrestaShop/PrestaShop#34516] opened 2023-11-10 10:57 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Regardless of the language we use, we would have to use the correct currency format.
On my PrestaSho site we use es_ES as the default for several countries Mexico, Spain, United States, Colombia, Chile
The currency format is different for each country, whether for cents or thousands.
Example
Mexico and the United States is #,##0.00
Colombia, Chile, Euro is #.##0,00

For our site it is configured in Spanish, but unfortunately the currency format is based on the language and not the currency.
There is a table that is ps_currency_lang and however the logistics in the pattern column are not respected
always try to use the es_ES language in your format

I will set my exchange rate to 1 so that it does not have an exchange rate.

€ 2.699,90 Correct, but only because of the language it uses, which is es_ES
USD 2.699,90 Incorrect (that is not the Format)
MXN 2.699,90 Incorrect (that is not the Format)

and the table uses pattern column no working #.##0,00 or #,##0.00
![image](https://github.com/PrestaShop/PrestaShop/assets/47211666/82b06c64-6c5e-4e3c-87df-c07805d7bfab)

### Steps to reproduce

in all home page Front-Page

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment] 2023-11-13 10:11
Hello @TheGera ,

Could you specify the steps to reproduce your issue ?

I can't reproduce it.
<img width="681" alt="Screenshot 2023-11-13 at 11 10 43" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/30cc3fab-a43c-4fb7-a102-64fe71a46e5b">

In the FO, the prices are displayed as configured in the BO.

**Comment by florine2623** [comment] 2023-11-29 15:33
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by florine2623** 2023-11-29 15:33 UTC
Labels: Bug, FO, International, Currencies, 8.1.x
