### ISSUE TITLE
"ps_facetedsearch" Module dont check avaibility combination 

### ISSUE THREAD

**Issue by toar86** [PrestaShop/PrestaShop#15350] opened 2019-09-01 18:16 UTC
When user select product attributes (not features), then avaibility always display product, not selected combination.

Eg. I selling rugs, i have rug X which have product combinations (size and shape):
Circle - 120x120 cm - avaible: 2 items
Circle - 140x140 cm - not avaible
Rectangle - 120x180 cm - not avaible
Rectangle - 200x220 cm - not avaible.

when i select on filters size 140x140 cm, i always get "Rug X" on list, but this combination isin't avaible, when i select shape rectangle, then "rug X" is displayed on list, but i have only avaible rug X with shape - circle, not rectangle

This product should be displayed only when i dont have selected "size" atribute, or have selected attribute size 120x120 on filters, or have selected attribute shape = "circle"

I created path here:
https://github.com/PrestaShop/ps_facetedsearch/pull/108/files

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2019-09-02 07:29
Hi @toar86,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15056
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-02 07:29
Duplicate of #15056

**Closed as completed by khouloudbelguith** 2019-09-02 07:29 UTC
Labels: Duplicate, Faceted search, Combinations
