### ISSUE TITLE
ContextErrorException in ImageRetriever.php

### ISSUE THREAD

**Issue by 5-digits** [PrestaShop/PrestaShop#17539] opened 2020-02-07 08:06 UTC
**Steps**
--
1. Install the prestashop project . 
2. Choose [ fr ] language 
3. finish installing without any problem 
4. by moving to the home page, i got this error  

Something went wrong,  in ImageRetriever.php line 274
--

ContextErrorException
Notice: Undefined offset: 0
in ImageRetriever.php line 274
at ImageRetriever->getNoPictureImage(object(Language))in FrontController.php line 1518
at FrontControllerCore->getTemplateVarUrls()in FrontController.php line 490
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 549
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 292
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

**Screenshots**
![prest_01](https://user-images.githubusercontent.com/6322848/74011712-c81dd680-4988-11ea-8b2c-a282031988c9.PNG)

**Additional information**
PrestaShop version: latest version 
PHP version: 7.3.12

**Comment by khouloudbelguith** [comment] 2020-02-07 08:09
Hi @5-digits,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2020-03-09 07:44
Hi @5-digits,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-03-09 07:44 UTC
Labels: Bug, FO, Duplicate, Topwatchers, 1.7.6.3

**Comment by 5-digits** [comment] 2020-03-12 15:48
You must install the stable version with PHP-7.2, after that you can use any php version.

>  For me i tried {PHP-5.640 , PHP-7.0.33, PHP-7.1.13, PHP-7.2.27, PHP-7.3.12, PHP-7.4.0 } and the website works fine 

- So i think the problem exist when trying to do installation

**Comment by khouloudbelguith** [comment] 2020-03-12 16:09
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/17725

**Comment by khalidumarr** [comment] 2020-04-19 19:58
Running below SQL fixed the issue for me:

```
INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
VALUES
	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);

```

**Comment by juan-jose2000** [comment] 2020-05-10 00:36
Could you solve the problem ?, I have the exact same error

Help me

**Comment by lrodriguez37** [comment] 2020-06-03 15:10
> Running below SQL fixed the issue for me:
> 
> ```
> INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
> VALUES
> 	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
> 	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
> 	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
> 	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
> 	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
> 	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
> 	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
> 	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);
> ```

Thank you. This fix the issue.

**Comment by 5-digits** [comment] 2020-06-03 23:29
Thanks @khalidumarr it works for me also

**Comment by bmihm** [comment] 2020-06-09 11:15
Hi. 
this issue is work for me also and is in the 1.7.8.0 again.

**Comment by Safin85** [comment] 2021-02-18 23:27
> Running below SQL fixed the issue for me:
> 
> ```
> INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
> VALUES
> 	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
> 	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
> 	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
> 	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
> 	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
> 	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
> 	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
> 	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);
> ```

helped me too with PrestaShop 1.7.7.2 and php 7.3

**Comment by arouiadib** [comment] 2021-03-24 06:25
One workaround to make the FO accessible (for people who can't resolve the issue using SQL):

BO is still accessible with this bug, so under Design > Image Settings , create an image type with name "home_default" and save.

**Comment by vahidalvandi** [comment] 2021-10-06 12:09
> > Running below SQL fixed the issue for me:
> > ```
> > INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
> > VALUES
> > 	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
> > 	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
> > 	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
> > 	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
> > 	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
> > 	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
> > 	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
> > 	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);
> > ```
> 
> Thank you. This fix the issue.

solved for me but have issue in correct display page and load css

**Comment by Manasdedieu** [comment] 2022-06-20 13:10
> Running below SQL fixed the issue for me:
> 
> ```
> INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
> VALUES
> 	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
> 	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
> 	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
> 	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
> 	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
> 	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
> 	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
> 	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);
> ```

Thanks !
