### ISSUE TITLE
Can not delete the message in the customer service SAV prestashop 1.7.3

### ISSUE THREAD

**Issue by KHATERSAID** [PrestaShop/PrestaShop#14380] opened 2019-06-26 12:40 UTC
Hello I would like to delete the message of a customer in the customer service of my back office impossible it regenerates each time a new id

can you help me
![2](https://user-images.githubusercontent.com/39734318/60180414-45dd0980-9820-11e9-8ffb-9c0952bcb3bf.png)
![1](https://user-images.githubusercontent.com/39734318/60180415-4675a000-9820-11e9-9113-b718c22764b0.png)

**Comment by khouloudbelguith** [comment] 2019-06-26 13:11
Hi @Herboristeenligne,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
I attached a screen record
https://drive.google.com/file/d/1TmkkEdh3_Nw7syUDeg-z7l8fFQ_S37mQ/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by KHATERSAID** [comment] 2019-06-26 13:23
![informations](https://user-images.githubusercontent.com/39734318/60183270-411b5400-9826-11e9-8fb2-761871e1b639.png)
[error php.txt](https://github.com/PrestaShop/PrestaShop/files/3330169/error.php.txt)

**Comment by khouloudbelguith** [comment] 2019-06-26 13:35
@Herboristeenligne, in the BO => Advanced Parameters => Performance page, could you please try to disable this option "Disable all overrides", clear cache, check & feedback.

**Comment by KHATERSAID** [comment] 2019-06-27 09:52
Thanks for your help
the problem is solved I clear the cache  app/cache/prod

**Comment by khouloudbelguith** [comment] 2019-06-27 09:54
Hi @KHATERSAID,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-27 09:54 UTC
Labels: Bug, BO, Customer service, No change required
