### ISSUE TITLE
"product.show_price" doesn't work when disable price for groups

### ISSUE THREAD

**Issue by jorgevrgs** [PrestaShop/PrestaShop#12972] opened 2019-03-19 22:10 UTC
**Describe the bug**
When I select catalog mode or hide prices in guest group, products continue showing prices.

**To Reproduce**
1. Go to Shop Parameters -> Product settings
2. Click on Catalog mode On.
3. Open your shop.
4. See product prices. That happen when you get Group Feature disabled on performance settings.

**Screenshots**
** If applicable, add screenshots or screenrecords to help explain your problem. **

**Additionnal information**
PrestaShop version: 1.7.4 and newer
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment] 2019-03-21 11:26
Hi @jorgevrgs,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1cVjHYzL05g1b8Fja2LnxPutwu5YrzXNQ/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-04-22 07:28
Hi @jorgevrgs, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-22 07:28 UTC
Labels: Bug, FO, Product settings, Customer groups, No change required, 1.7.5.1
