### ISSUE TITLE
SQL error in dashproducts

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#31200] opened 2023-02-03 16:36 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Best sales are not showing:
![Immagine 2023-02-03 172417](https://user-images.githubusercontent.com/7520695/216654776-d56d9daa-4208-42f1-a6ff-a990d02a8403.png)

There is an SQL error on line https://github.com/PrestaShop/dashproducts/blob/53876b20957e7257fefdd866cfeadc10fbfe6085/dashproducts.php#L201

```
BIGINT UNSIGNED value is out of range in '(((`db_ps_test1`.`od`.`product_quantity` - `db_ps_test1`.`od`.`product_quantity_refunded`) - `db_ps_test1`.`od`.`product_quantity_return`) - `db_ps_test1`.`od`.`product_quantity_reinjected`)'<br /><br /><pre>
					SELECT
						product_id,
						product_name,
						SUM(product_quantity-product_quantity_refunded-product_quantity_return-product_quantity_reinjected) as total,
						p.price as price,
						pa.price as price_attribute,
						SUM(total_price_tax_excl / conversion_rate) as sales,
						SUM(product_quantity * purchase_supplier_price / conversion_rate) as expenses
					FROM `ps_orders` o
		LEFT JOIN `ps_order_detail` od ON o.id_order = od.id_order
		LEFT JOIN `ps_product` p ON p.id_product = product_id
		LEFT JOIN `ps_product_attribute` pa ON pa.id_product_attribute = od.product_attribute_id
		WHERE `invoice_date` BETWEEN "2022-12-01 00:00:00" AND "2022-12-31 23:59:59"
		AND valid = 1
		 AND o.id_shop IN ( ... ) 
		GROUP BY product_id, product_attribute_id
		ORDER BY total DESC
		LIMIT 10</pre>
```

Digging deeper: the table `PREFIX_order_detail` has 4 quantity columns defined as `unsigned int`, and one as `signed int`:
https://github.com/PrestaShop/PrestaShop/blob/0c2949b33dd3f57d49164d7988edc7926f0de13a/install-dev/data/db_structure.sql#L1330

``` 
  `product_quantity` int(10) unsigned NOT NULL DEFAULT '0',
  `product_quantity_in_stock` int(10) NOT NULL DEFAULT '0',
  `product_quantity_refunded` int(10) unsigned NOT NULL DEFAULT '0',
  `product_quantity_return` int(10) unsigned NOT NULL DEFAULT '0',
  `product_quantity_reinjected` int(10) unsigned NOT NULL DEFAULT '0',
```

I have an order detail line with these quantities:
![Immagine 2023-02-03 173221](https://user-images.githubusercontent.com/7520695/216656511-f9d88d6a-dc2f-468d-8000-c9670afb22a5.png)

`product_quantity-product_quantity_refunded-product_quantity_return-product_quantity_reinjected` becomes negative for this line.

### Expected behavior

No SQL error, of course...

### Steps to reproduce

1. Refund an article in an order
2. Make sure, the quantities on the line in `ps_order_detail` are as above. If they aren't, help you out with phpmyadmin.
3. Go to the dashboard and notice the empty best sales.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

dashproducts 2.1.2

**Comment by hibatallahAouadni** [comment] 2023-02-06 09:37
Hello @lmeyer1 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28431. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment] 2023-02-06 09:37
Duplicate of #28431

**Closed as completed by hibatallahAouadni** 2023-02-06 09:37 UTC
Labels: Bug, Duplicate, Invalid
