### ISSUE TITLE
The controller AdminPsMboModule is missing or invalid

### ISSUE THREAD

**Issue by bartoll** [PrestaShop/PrestaShop#23653] opened 2021-03-15 15:00 UTC
#### Describe the bug

I got an error in admin panel when I clicked on menu Improve -> Modules -> Modules Catalog

> The controller AdminPsMboModule is missing or invalid.

#### Expected behavior

I think that correct page here should be prestashop marketplace.

#### Steps to Reproduce

1. Prestashop is installed in version 1.7.7.1
2. Try to update Prestashop to 1.7.7.2 version according to this steps https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#manual-upgrade--process-details
- the only one difference I made is "File copy" section
- I took new version folder and copy here "img/" and "override/" folders from older version
3. I deleted cache folder "var/cache".
4. I signed-in to admin panel and I clicked on menu Improve -> Modules -> Modules Catalog
5. I got an error as below

**Screenshots**

![image](https://user-images.githubusercontent.com/1619173/111174066-6c6c4680-85a7-11eb-8564-a062db875d23.png)

#### Additional information

* PrestaShop version: 1.7.7.1 -> 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment] 2021-03-15 16:44
Hello @bartoll 

Could you please provide your MBO module version.
And it seems your issue is a duplicate of this one #11264 could you please check it and feedback.

Thanks!

**Comment by bartoll** [comment] 2021-03-15 22:07
@hibatallahAouadni 

There is no "ps_mbo" module version in new Prestashop 1.7.7.2 (downloaded zip from github release).
In my older version I can see "2.0.1" version of "ps_mbo" module.

I can't find any relation with #11264 because I don't know what update script really does (php install/upgrade/upgrade.php).
I have just upgrade Prestashop and met this error.

**Comment by bartoll** [comment] 2021-03-15 22:09
Pay attention for my not standard step number 2.
I assume that this path was not tested.

**Comment by hibatallahAouadni** [comment] 2021-03-17 16:28
Hello @bartoll 

Could you please check the **ps_mbo** module is installed or not on your shop, and I bet that it's not installed.
And that's what cause your issue :wink: 
This issue is not related to upgrade (whether is manual or auto). About the issue #11264 is not fully fixed, cause the part of redirection is still not fixed yet (see the issue #22740).
Please check and feedback.

Thanks!

**Comment by pelleringa** [comment] 2021-03-21 16:16
@bartoll . Is this module a Prestashop's native module? (I don't recognize it by this name).
The error says the Controller doesn't exist, but in database there is an entry for this Controller to be loaded. If before the upgrade was working, it is possible that you had this controller in override/controllers/admin?

**Comment by matks** [comment] 2021-03-21 17:21
@pelleringa it's a PrestaShop module that is installed during shop setup

https://github.com/prestashopcorp/ps_mbo

**Comment by florine2623** [comment] 2021-04-07 08:13
Hello,
since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.
Thanks!

**Closed as completed by florine2623** 2021-04-07 08:13 UTC
Labels: Bug, BO, Modules catalog, No change required, MBO, 1.7.7.2
