### ISSUE TITLE
Wrong discount label in shopping cart

### ISSUE THREAD

**Issue by mowcixo** [PrestaShop/PrestaShop#14387] opened 2019-06-26 19:38 UTC
**Describe the bug**
The cart would take the first discount in specific_prices instead the corresponding based on cart quantity.

**To Reproduce**
1. Create a article with a 10% discount per 1 unity.
2. Then add another specific price with a 32% discount per 5 unities.
3. Add 5 or more unities to cart in the FO.
4. You will see that the 32% of discount is applied but the label is printing 10% of discount.

**Screenshots**

![image](https://user-images.githubusercontent.com/47653/60209218-75106c80-985a-11e9-9ed8-a021c1224e70.png)

![image](https://user-images.githubusercontent.com/47653/60209175-62963300-985a-11e9-97ba-cc5becb7f492.png)

![image](https://user-images.githubusercontent.com/47653/60209255-8c4f5a00-985a-11e9-897b-cdabe52f508e.png)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2019-06-27 07:54
Hi @mowcixo,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/60247858-61e0b980-98b9-11e9-9380-eedd6a6a6e75.png)


It is OK with PS1.7.6.0rc1
![image](https://user-images.githubusercontent.com/16067358/60247834-52fa0700-98b9-11e9-9d6b-ea5db9c99cdf.png)
It is fixed

Thanks to check & feedback.

**Comment by mowcixo** [comment] 2019-06-27 08:04
So the fix will be released with 1.7.6.0 right?

**Comment by khouloudbelguith** [comment] 2019-06-27 08:04
@mowcixo, yes!
Since it is fixed, I will close the issue.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-27 08:04 UTC
Labels: Bug, FO, Duplicate, Discounts, 1.7.5.2, Shopping carts FO

**Comment by khouloudbelguith** [comment] 2019-06-27 08:06
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11656 to fix the issue.

Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-27 08:06
Duplicate of #9892
