### ISSUE TITLE
It's not possible to disable category in multi-store

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#14963] opened 2019-08-01 21:36 UTC
We want to disable Category (3-clothes) from first of your stores.

1. Enable multi-store, add one more store to PrestaShop.
2. Make sure that you're in the context of your first store.
3. Go to Categories page.
4. Edit category ID 3 (3-clothes), try to uncheck first of your stores from Shop association tree.

Result? You can't.

Go to your second store, do the same thing, edit Category, disable from first store, result? Category is disabled.

But now... go to yourdomain.com/3-clothes, category which is not enabled in first store is not available in the menu, but you can access it directly.

So:

1. you can't properly edit shop assoc in multi-store context
2. category is not visible in the menu but accessible directly, even if you manage to turn it off

**Additional information**
PrestaShop version: 1.7.6
PHP version: 5.6-7.2, doesn't matter

**Comment by khouloudbelguith** [comment] 2019-08-02 08:05
Hi @kpodemski,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9859 & #9821.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-02 08:06
Duplicate of #9859

**Closed as completed by khouloudbelguith** 2019-08-02 08:05 UTC
Labels: Duplicate
