### ISSUE TITLE
PS 8.0.1 - I cannot add any image to the Image Slider Error 500

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#31441] opened 2023-02-18 18:03 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I wanted to add a new slide to the built-in Image Slider. I have Error 500 after selecting an image and click on Save button. Replacing an image in an existing slide also does not work. I have installed a third-party image slider and have the same error. I have a freshly installed PS 8.0.1, PHP version: 8.1.13.

EDIT
It looks like the problem appears only when the PHP version is 8.0 or higher. I have changed the PHP ersion to 7.4 and I was able to add and edit photo in the slides. The problem only appears in PHP 8.0 and PHP 8.1.

![image](https://user-images.githubusercontent.com/48493952/219881146-14940bbd-afd4-4cee-b135-d19dd2d07bb3.png)

![image](https://user-images.githubusercontent.com/48493952/219881194-f9284d01-92a3-4534-80df-45fe02a6b0f0.png)

Here are my full specs

Server information: Linux https://github.com/PrestaShop/PrestaShop/pull/1 SMP Mon Dec 12 07:06:14 EST 2022 x86_64
Server software version: Apache
PHP version: 8.1.13
Memory limit: 512M
Max execution time: 120
Upload Max File size: 200M
MySQL version: 10.4.27-MariaDB-cll-lve
PrestaShop version: 8.0.1

### Expected behavior

Image slider working again

### Steps to reproduce

1. Install fresh PS 8.0.1
2. Go to the back office and open Modules -> Image Slider
3. Add an image to a new slide or replace an image in an existing slide

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.13

### If your bug is related to a module, specify its name and its version

PS Image slider v3.1.1

**Comment by sallemiines** [comment] 2023-02-20 13:00
Hello @banan44 

I reproduce your issue with **PS801 NOK** 


https://user-images.githubusercontent.com/31663369/220114411-292fc797-f6df-407c-8be2-2a237aefc9ce.mp4

With **PS 1788 / PS 800  and develop OK** 


https://user-images.githubusercontent.com/31663369/220114636-811983d4-1998-4daa-a020-c262a2c9d0fc.mp4

Thank you

**Comment by sallemiines** [comment] 2023-02-20 13:02
Duplicate of #[31194](https://github.com/PrestaShop/PrestaShop/issues/31194)

**Closed as completed by sallemiines** 2023-02-20 13:02 UTC
Labels: Bug, Duplicate, Invalid

**Comment by sallemiines** [comment] 2023-02-20 13:04
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #[31194.](https://github.com/PrestaShop/PrestaShop/issues/31194)
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you
