### ISSUE TITLE
BO - Help Button - Help button in max size 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#29887] opened 2022-10-05 14:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you are disconnected from the BO, when you clic in another tab, the BO will ask if you "understand the risk" to change the tab, if you do this with the help button, you will have the help button in max size as you can see in this video : 

https://user-images.githubusercontent.com/100699445/194079693-f876eb59-6aa5-40a6-b5b1-aa0739fd8a9f.mp4

### Expected behavior

I think we didn't have to be logged to see the help button so we don't have to ask this question 

### Steps to reproduce

1. Wait until you're disconnected from the BO 
2. Clic on help button in any pages
3. Clic on "I accepted the risk"
4. See Error 

### PrestaShop version(s) where the bug happened

1.7.7.8 - 8.0.0 

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment] 2022-10-05 15:30
Hello @AureRita 

I didn't manage to reproduce the issue with PS1778 and PS800.
Could you please create a fresh shop and try to reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by AureRita** [comment] 2022-10-13 07:44
Hi @hibatallahAouadni, 

I tried to reproduce the issue and I do it with version 1.7.8.7 and 8.0.x as you can see : 

[Untitled_ Oct 13, 2022 9_42 AM.webm](https://user-images.githubusercontent.com/100699445/195533650-e77ac03a-83bc-4411-b1b4-fe4cde12b5fb.webm)

You really need to wait for the timeout connection to test it, take a shop on and let this on the background, at the end of the day, check the help button, you'll probably have the bug

**Comment by hibatallahAouadni** [comment] 2022-10-17 13:12
Hello @AureRita 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration problem.

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-10-17 13:12 UTC
Labels: Bug, BO, 1.7.7.8, Invalid
