### ISSUE TITLE
Duplicated SQL queries and low performance

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20034] opened 2020-07-02 14:22 UTC
Hi to everyone, 

I think we should put some effort to speeding PrestaShop a bit. It's too long 1 second time to first byte. Very hard to squeeze into Google's rules that are getting tighter and tighter. :(

Take a look on my example category with profling enabled. I have nothing in cart, few cart rules active and it takes 615 queries and to display a category.
https://eshop-franke.cz/516-odpadkove-kose?profiling

If you take a look on doubled queries, I have this EXACT SAME query, which is repeated 31 times.
```
SELECT DISTINCT f.id_feature, f.*, fl.*
FROM `ps_feature` f
INNER JOIN ps_feature_shop feature_shop
ON (feature_shop.id_feature = f.id_feature AND feature_shop.id_shop = 1)
LEFT JOIN `ps_feature_lang` fl ON (f.`id_feature` = fl.`id_feature` AND fl.`id_lang` = 1)
ORDER BY f.`position` ASC
```

Then the second one 30 times
```
SELECT *
FROM `ps_feature` a
LEFT JOIN `ps_feature_lang` `b` ON a.`id_feature` = b.`id_feature` AND b.`id_lang` = 1
LEFT JOIN `ps_feature_shop` `c` ON a.`id_feature` = c.`id_feature` AND c.`id_shop` = 1
WHERE (a.`id_feature` = XX) LIMIT 1
```
Couldn't it just fetch the data once without the where conditon?

**In total, there are 17x 24 times duplicated queries. This is 408 queries which could be just 17.** From my experience, it's the mysql roundtrips that take the most processing time. The contact page that does not need so much queries gets loaded in 500 ms.

#### Steps to reproduce

1. Make some products
2. Make 20-30 features and assign them to some products.
3. Enable them in faceted search.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment] 2020-07-02 15:00
Hi @Hlavtox ,
Thanks for the report, I will ping our dev team on your topic !
Please stay tuned.

**Comment by florine2623** [comment] 2020-07-02 15:01
Hi @PrestaShop/prestashop-core-developers ,
@Hlavtox noticed some repeating SQL queries that slow down PrestaShop, could you take a look into it ?
Thanks!

**Comment by sowbiba** [comment] 2020-09-04 10:54
Hello @Hlavtox Thanks for the issue report

I tested with PS1.7.6.2
I have the first given query only 2 times when displaying a category. DO I miss something ?

![Capture d’écran de 2020-09-04 10-52-38](https://user-images.githubusercontent.com/7426640/92231890-0e92cf80-ee9d-11ea-8128-7a6aabd71f21.png)

**Comment by Hlavtox** [comment] 2020-09-04 10:57
@sowbiba I have 30 features and most of them are used in faceted search.
- Make some products
- Make 20-30 features and assign them to some products.
- Enable them in faceted search.

Then you should have the same amount.

**Comment by letwang** [comment] 2020-09-05 00:22
> @sowbiba I have 30 features and most of them are used in faceted search.
> 
> * Make some products
> * Make 20-30 features and assign them to some products.
> * Enable them in faceted search.
> 
> Then you should have the same amount.

Hi friends
Your findings are correct. I also found this performance bottleneck and provided a solution to the prestashop official. I hope they will adopt it.

https://github.com/PrestaShop/PrestaShop/issues/20836

**Comment by khouloudbelguith** [comment] 2020-09-07 08:37
Hi @sowbiba, @PrestaShop/prestashop-core-developers 

@letwang find a solution as described here:
>>To solve a large number of duplicate SQL solutions, it is recommended to use PHP static caching solutions, for example, can refer to:https://github.com/drupal/drupal/blob/9.1.x/core/includes/bootstrap.inc#L582

```
/**
 * Provides central static variable storage.
 *
 * All functions requiring a static variable to persist or cache data within
 * a single page request are encouraged to use this function unless it is
 * absolutely certain that the static variable will not need to be reset during
 * the page request. By centralizing static variable storage through this
 * function, other functions can rely on a consistent API for resetting any
 * other function's static variables.
 *
 * Example:
 * @code
 * function example_list($field = 'default') {
 *   $examples = &drupal_static(__FUNCTION__);
 *   if (!isset($examples)) {
 *     // If this function is being called for the first time after a reset,
 *     // query the database and execute any other code needed to retrieve
 *     // information.
 *     ...
 *   }
 *   if (!isset($examples[$field])) {
 *     // If this function is being called for the first time for a particular
 *     // index field, then execute code needed to index the information already
 *     // available in $examples by the desired field.
 *     ...
 *   }
 *   // Subsequent invocations of this function for a particular index field
 *   // skip the above two code blocks and quickly return the already indexed
 *   // information.
 *   return $examples[$field];
 * }
 * function examples_admin_overview() {
 *   // When building the content for the overview page, make sure to get
 *   // completely fresh information.
 *   drupal_static_reset('example_list');
 *   ...
 * }
 * @endcode
 *
 * In a few cases, a function can have certainty that there is no legitimate
 * use-case for resetting that function's static variable. This is rare,
 * because when writing a function, it's hard to forecast all the situations in
 * which it will be used. A guideline is that if a function's static variable
 * does not depend on any information outside of the function that might change
 * during a single page request, then it's ok to use the "static" keyword
 * instead of the drupal_static() function.
 *
 * Example:
 * @code
 * function mymodule_log_stream_handle($new_handle = NULL) {
 *   static $handle;
 *   if (isset($new_handle)) {
 *     $handle = $new_handle;
 *   }
 *   return $handle;
 * }
 * @endcode
 *
 * In a few cases, a function needs a resettable static variable, but the
 * function is called many times (100+) during a single page request, so
 * every microsecond of execution time that can be removed from the function
 * counts. These functions can use a more cumbersome, but faster variant of
 * calling drupal_static(). It works by storing the reference returned by
 * drupal_static() in the calling function's own static variable, thereby
 * removing the need to call drupal_static() for each iteration of the function.
 * Conceptually, it replaces:
 * @code
 * $foo = &drupal_static(__FUNCTION__);
 * @endcode
 * with:
 * @code
 * // Unfortunately, this does not work.
 * static $foo = &drupal_static(__FUNCTION__);
 * @endcode
 * However, the above line of code does not work, because PHP only allows static
 * variables to be initialized by literal values, and does not allow static
 * variables to be assigned to references.
 * - http://php.net/manual/language.variables.scope.php#language.variables.scope.static
 * - http://php.net/manual/language.variables.scope.php#language.variables.scope.references
 * The example below shows the syntax needed to work around both limitations.
 * For benchmarks and more information, see https://www.drupal.org/node/619666.
 *
 * Example:
 * @code
 * function example_default_format_type() {
 *   // Use the advanced drupal_static() pattern, since this is called very often.
 *   static $drupal_static_fast;
 *   if (!isset($drupal_static_fast)) {
 *     $drupal_static_fast['format_type'] = &drupal_static(__FUNCTION__);
 *   }
 *   $format_type = &$drupal_static_fast['format_type'];
 *   ...
 * }
 * @endcode
 *
 * @param $name
 *   Globally unique name for the variable. For a function with only one static,
 *   variable, the function name (e.g. via the PHP magic __FUNCTION__ constant)
 *   is recommended. For a function with multiple static variables add a
 *   distinguishing suffix to the function name for each one.
 * @param $default_value
 *   Optional default value.
 * @param $reset
 *   TRUE to reset one or all variables(s). This parameter is only used
 *   internally and should not be passed in; use drupal_static_reset() instead.
 *   (This function's return value should not be used when TRUE is passed in.)
 *
 * @return mixed
 *   Returns a variable by reference.
 *
 * @see drupal_static_reset()
 */
function &drupal_static($name, $default_value = NULL, $reset = FALSE) {
  static $data = [], $default = [];
  // First check if dealing with a previously defined static variable.
  if (isset($data[$name]) || array_key_exists($name, $data)) {
    // Non-NULL $name and both $data[$name] and $default[$name] statics exist.
    if ($reset) {
      // Reset pre-existing static variable to its default value.
      $data[$name] = $default[$name];
    }
    return $data[$name];
  }
  // Neither $data[$name] nor $default[$name] static variables exist.
  if (isset($name)) {
    if ($reset) {
      // Reset was called before a default is set and yet a variable must be
      // returned.
      return $data;
    }
    // First call with new non-NULL $name. Initialize a new static variable.
    $default[$name] = $data[$name] = $default_value;
    return $data[$name];
  }
  // Reset all: ($name == NULL). This needs to be done one at a time so that
  // references returned by earlier invocations of drupal_static() also get
  // reset.
  foreach ($default as $name => $value) {
    $data[$name] = $value;
  }
  // As the function returns a reference, the return should always be a
  // variable.
  return $data;
}

/**
 * Resets one or all centrally stored static variable(s).
 *
 * @param $name
 *   Name of the static variable to reset. Omit to reset all variables.
 *   Resetting all variables should only be used, for example, for running
 *   unit tests with a clean environment.
 */
function drupal_static_reset($name = NULL) {
  drupal_static($name, NULL, TRUE);
}

```
Thanks!

**Comment by PierreRambaud** [comment] 2020-09-07 09:26
There is already a cache system in the Db class to improve performance when a request has already been executed.

**Comment by letwang** [comment] 2020-09-09 01:50
> There is already a cache system in the Db class to improve performance when a request has already been executed.

What if it is not based on caching?
Even if there is a cache, the cache repeats the same operation multiple times. . .

**Comment by PierreRambaud** [comment] 2020-09-09 08:29
> > There is already a cache system in the Db class to improve performance when a request has already been executed.
> 
> What if it is not based on caching?
> Even if there is a cache, the cache repeats the same operation multiple times. . .

I agree the cache operation is duplicated, unfortunately the whole part needs to be refactored to make something relevant and performant :disappointed:

**Comment by hibatallahAouadni** [comment] 2021-01-26 11:45
Hello @PierreRambaud 

> I agree the cache operation is duplicated, unfortunately the whole part needs to be refactored to make something relevant and performant

It seems this issue need a lot of work. So, if you agree I will change the label to **`To Do`**.
Right now, I'm putting **`TBS`** till you agree :wink: 

Thanks!

**Comment by PierreRambaud** [comment] 2021-02-17 14:08
I'm more in favor of closing this issue and rework dedicated parts as soon as possible.
If we keep this issue we encounter problems:
- What we have to optimize?
- What we have to refactor?
- When the issue is fixed?

We are also able to use the [Boy Scout rule](https://biratkirat.medium.com/step-8-the-boy-scout-rule-robert-c-martin-uncle-bob-9ac839778385) in our PR to fix it.

**Closed as completed by PierreRambaud** 2021-02-17 14:08 UTC
Labels: Bug, CO, Won't fix, Performance, 1.7.6.2

**Comment by Hlavtox** [comment] 2021-02-17 15:35
@PierreRambaud Ok!! But just add it to some general todo, please, so it's not forgotten. :-)

**Comment by ChineseNorris** [comment] 2023-02-15 20:41
@Hlavtox  I wouldn't say this is a small issue, just try to add a few more items to the cart and the performance degrades exponentially, queries are duplicated every time you add more products on the cart.
As user experience is really normal to add a lot of stuff in the cart and then delete products from the cart because users simply tend to compare and remove products that are not interested in before checkout.
I know it's very painful to fix this issue but I think we can solve this issue if we walkaround in some more efficient way to retrieve products on the cart.
