### ISSUE TITLE
Can not create $0 products

### ISSUE THREAD

**Issue by baskettcase** [PrestaShop/PrestaShop#18924] opened 2020-04-30 21:25 UTC
#### Describe the bug

When I edit a product that has no cost, I get an SQL error since price_min and price_max are then empty.

#### Expected behavior

It would save the product

#### Steps to Reproduce

1. Create a product that costs $0
2. If that succeeded, then try editing that product.
3. If that worked, then try setting it to a combo and then save

**Screenshots**

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' , 21) ON D' at line 5

INSERT INTO `layered_price_index` (id_product, id_currency, id_shop, price_min, price_max, id_country)
                     VALUES (99,
                        2,
                        1,
                        ,
                        ,
                        21)
                     ON DUPLICATE KEY UPDATE id_product = id_product

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

I edited modules/ps_facetedsearch/ps_facetedsearch.php line 564 and 565 and set $minPriceValue and $maxPriceValue to (float) and now everything works just fine.

**Comment by florine2623** [comment] 2020-05-04 14:24
Hi @baskettcase ,

I followed your steps, but can't reproduce your issue on PS 1.7.6.5.

_I edited modules/ps_facetedsearch/ps_facetedsearch.php line 564 and 565 and set $minPriceValue and $maxPriceValue to (float) and now everything works just fine._
-> Do you mean your issue is fixed and can be closed ?

Thanks!

**Comment by baskettcase** [comment] 2020-05-04 19:51
I edited core to fix it, but no if I removed my changes it wouldn't be fixed. Strange, Ill have to install a clean copy and see if it works there. it's definitely not working for me.

**Comment by florine2623** [comment] 2020-05-07 09:35
Ok if it fixed for you, I'll close this issue!
Thanks!

**Closed as completed by florine2623** 2020-05-07 09:35 UTC
Labels: Bug, BO, FO, Product settings, No change required
