### ISSUE TITLE
PS9 Small issue, Shop version overlaid on the "Quick Access" button on dashboard page for iPad Pro

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#34707] opened 2023-11-28 09:26 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Screenshot from 2023-11-28 09-11-51](https://github.com/PrestaShop/PrestaShop/assets/90208051/ac6f6c89-ae4a-40f5-bf51-1c0f4eaf7228)

Reproducing with iPad Pro

### Expected behavior

![Screenshot from 2023-11-28 10-18-15](https://github.com/PrestaShop/PrestaShop/assets/90208051/96df67e1-9c57-4a4f-ac0d-49c6e3f011da)

### Steps to reproduce

1. open dashboard page in iPad Pro 
2. check shop version on the top

### PrestaShop version(s) where the bug happened

9.0/8.x

### PHP version(s) where the bug happened

8.1 / 7.4

**Comment by florine2623** [comment] 2023-11-29 09:34
ping @PrestaShop/qa-functional 

I can't reproduce the issue, can someone check ? ^^

**Comment by szavadskiy** [comment] 2023-11-29 10:08
hello @florine2623 
try it with Debug mode

**Comment by florine2623** [comment] 2023-11-29 15:27
Debug mode is already enabled :
<img width="833" alt="Screenshot 2023-11-29 at 16 27 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c37399e9-ac65-412f-8ccf-6ac8cfb079f5">

**Comment by paulnoelcholot** [comment] 2023-12-01 09:16
Hello @szavadskiy,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/8dd75b18-ec13-4a42-9d69-5a1414c1d74a)

**Closed as completed by paulnoelcholot** 2023-12-01 09:16 UTC
Labels: Bug, BO, Can't reproduce, Front-end, Responsive, Invalid, 9.0.x

**Comment by ChillCode** [comment] 2023-12-02 08:40
This issue have been always there, but I usually don't report those since for me are less than trivial, but since you did I'll try so guide.

Hi @florine2623 & @paulnoelcholot 

You both have the menu so the orientation is different, to see the issue just click the rotate icon next to throttling settings.

Also it's always better to use zoom set to 100% when testing.

**Comment by florine2623** [comment] 2023-12-04 09:12
I still can't reproduce the issue.
I tried with different orientations, zoom set to 100%, with debug mode.


https://github.com/PrestaShop/PrestaShop/assets/16019289/6bf3bc4c-7c00-4989-9888-f2f0b5dcb669
