### ISSUE TITLE
PS 1.7.5.2 - Problems trying to edit products

### ISSUE THREAD

**Issue by WebmasterXeral** [PrestaShop/PrestaShop#14211] opened 2019-06-14 11:20 UTC
I'm having some issues every time I try to edit a product in backoffice on PS 1.7.5.2.

At first, I couldn't edit any product due to a memory limit in PHP, so I increased it from 512M to 1024M and it worked... until now. Every time I try to edit a product it throws the following errors in the server log:

AH01071: Got error 'PHP message: PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vhosts/myshopurl/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 122\n
PHP message: PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32768 bytes) in /var/www/vhosts/myshopurl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php on line 1\n
PHP message: PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 180224 bytes) in Unknown on line 0\n', referer: https://myshopurl/backoffice/index.php/sell/catalog/products?_token=hOQGGRT0FrYd5xSr1eMhxCZo-2wneV0gjcgIfObX-cM

If I increase the memory up to 2048M, these errors disappear, but then clicking on edit a product takes up to 2 minutes to show the product edit page.

**To Reproduce**
Case 1: PHP memory_limit set to 1024M
1. Go to Backoffice->Products
2. Click to Edit any product
3. Blank page showing Error 500
4. PHP Fatal errors in server log

Case 2: PHP memory_limit set to 2048M
1. Go to Backoffice->Products
2. Click to Edit any product
4. Wait 2 minutes
5. Product page opens to edit

**Additionnal information**
Prestashop version: 1.7.5.2
PHP version: 7.2.19
memory_limit: 1024M / 2048M
max_execution_time: 300
max_input_time: 300

**Comment by khouloudbelguith** [comment] 2019-06-14 11:24
Hi @WebmasterXeral,

Thanks for your report.
Do you have a large number of categories & subcategories?

Thanks!

**Comment by WebmasterXeral** [comment] 2019-06-14 11:39
Hi @khouloudbelguith 

There are 43 categories that depend on the main category, and 11 of them have 2/3 subcategories.

**Comment by khouloudbelguith** [comment] 2019-06-14 11:53
@WebmasterXeral, In your php.ini file, Try to increase:
```
max_execution_time = 30 (by default is 30, try to increase it)
max_input_time = you need to increase it
memory_limit
```

Some issues related added to our bug roadmap: 

- https://github.com/PrestaShop/PrestaShop/issues/9809
- https://github.com/PrestaShop/PrestaShop/issues/13698

Thanks to check & feedback

**Comment by WebmasterXeral** [comment] 2019-06-14 15:15
max_execution_time and max_input_time are one of the problems when memory_limit value is enough. max_execution_time and max_input_time are both set to 300, any other value less than 300 causes an error.

In case the value of memory_limit is enough, it takes 2 minutes since you click edit until you see the individual product page.

The delay time is disturbing, but my main concern is that opening a product for editing is getting more and more memory demanding. Now memory_limit is set to 2048M and it seems to be not enough:

AH01071: Got error 'PHP message: PHP Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in /var/www/vhosts/myshopurl/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105\n
PHP message: PHP Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32768 bytes) in /var/www/vhosts/myshopurl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php on line 1\n
PHP message: PHP Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 180224 bytes) in Unknown on line 0\n', referer: https://myshopurl/adminxeral/index.php/sell/catalog/products?_token=H9YPFmBFBqX32EuH2sDadcYMSGs9VXi8ev9VWzNaKCQ

**Comment by khouloudbelguith** [comment] 2019-06-14 15:35
@WebmasterXeral,

>In case the value of memory_limit is enough, it takes 2 minutes since you click edit until you see the individual product page.

Could you please enable the profiling mode to understand what could be the cause of this time.

Thanks!

**Comment by OneDotIT** [comment] 2019-06-16 09:47
Hello,
Do you have enough storage space ?
`~$ df -h`

**Comment by WebmasterXeral** [comment] 2019-06-17 10:48
@khouloudbelguith 
I've enable profiling mode, but it looks a little bit messy and I'm not sure what to look at.
![profiler](https://user-images.githubusercontent.com/51820431/59598125-c2266d00-90fb-11e9-8a44-624ae236300b.png)

Hi @OneDotIT 
I've checked and there is plenty storage space left.

In addition, I have been doing some tests today and the process to open the page to edit a product seems insatiable. If it doesn't fail because of a memory problem, it fails due to timeout. 
Here are the current values that are still not enough:
memory_limit = 3072M
max_execution_time = 800
max_input_time = 800

There are other Prestashop installations on the same server and they are working fine. Do you think that requesting a restart of the entire server could be useful in this case?

**Comment by OneDotIT** [comment] 2019-06-17 11:06
@WebmasterXeral 
I don't see how restating the server would help, unless for some cause you have slow storage (running from a laptop, in such case restarting the server = Freeing the RAM), or there is some hostname that would be updated / refreshed.

I actually started to suspect the relation to the Database.

**Comment by khouloudbelguith** [comment] 2019-06-17 11:26
@WebmasterXeral, The tool of profiling is very useful since it offers once activated a complete summary of the performances of the loading in the back office and in the front office. Perfect to optimize speed and correct errors your shop faster!

In your screenshot, for example, the query from ps_product has a time 19.2, in your case 19.2 ms

Thanks!

**Comment by WebmasterXeral** [comment] 2019-06-18 15:39
As @OneDotIT suspected, it's a database related problem.

The following query fills the database temporary folder due to the large number of attribute values generated by a product import module:

An exception occurred while executing 'SELECT p0_.id_attribute AS id_attribute_0, p0_.color AS color_1, p0_.position AS position_2, p1_.id_attribute_group AS id_attribute_group_3, p1_.position AS position_4, p2_.name AS name_5, p2_.public_name AS public_name_6, p0_.id_attribute AS id_attribute_7, p0_.color AS color_8, p0_.position AS position_9, p3_.name AS name_10 FROM prstshp_attribute p0_ INNER JOIN prstshp_attribute_group p1_ ON p0_.id_attribute_group = p1_.id_attribute_group INNER JOIN prstshp_attribute_shop p5_ ON p0_.id_attribute = p5_.id_attribute INNER JOIN prstshp_shop p4_ ON p4_.id_shop = p5_.id_shop INNER JOIN prstshp_attribute_lang p3_ ON p0_.id_attribute = p3_.id_attribute INNER JOIN prstshp_attribute_group_lang p2_ ON p1_.id_attribute_group = p2_.id_attribute_group WHERE p3_.id_lang = ? AND p2_.id_lang = ? AND p4_.id_shop = ? ORDER BY position_9 ASC, position_4 ASC' with params [1, 1, 1]:
SQLSTATE[HY000]: General error: 1114 The table '/DBDATA/rdbng/tmp/#sql_4e2d_0' is full

@khouloudbelguith @OneDotIT, thank you very much for your help!

**Comment by khouloudbelguith** [comment] 2019-06-18 15:41
@WebmasterXeral, thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Thanks!

**Closed as completed by khouloudbelguith** 2019-06-18 15:41 UTC
Labels: Bug, BO, No change required, 1.7.5.2

**Comment by ldecoker** [comment] 2019-08-17 16:12
@WebmasterXeral,

How did you fix your problem? Looks like I have the same issue.

Thx!
