### ISSUE TITLE
Autoupgrade - 1.7.1.0 to 1.7.8.11 rollback to 1.7.1.0 have some issue on it 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35968] opened 2024-04-18 15:17 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you do an upgrade from 1.7.1.0 to 1.7.8.11 and do a rollback just after that, you have some issue about modules 

On the dahsboard : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/94716d23-95f9-49db-9c5a-174becfbbb79)

On the module catalog/manager : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/1c687e18-293e-47ab-9256-c9569e2d2901)

### Expected behavior

I wish I have the same shop than before 

### Steps to reproduce

1. Install Prestashop 1.7.1.0 
2. Install autoupgrade dev version (#690 for exemple) 
3. Do a minor release (to 1.7.8.11) 
4. Do a rollback to 1.7.1.0 

### PrestaShop version(s) where the bug happened

1.7.1.0

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade dev (like #690)

### Your company or customer's name goes here (if applicable).

PS

**Comment by paulnoelcholot** [comment] 2024-06-10 14:42
Hello @AureRita,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-06-10 14:42 UTC
Labels: Bug, 1.7.x, BO, Can't reproduce, Autoupgrade, Module, Backlog SUE
