### ISSUE TITLE
Discount percentage shows incorrectly on product page

### ISSUE THREAD

**Issue by miramar-gareth-parker** [PrestaShop/PrestaShop#27302] opened 2022-01-11 13:32 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If a product's discount percentage is more than 83.33% of the original price then the 'Save Amount' value of '$product.discount_to_display' displays 100% instead of the correct percentage in the product-prices.tpl file. The version shown on top of the product image is however correct
<img width="675" alt="Screenshot 2022-01-11 at 13 28 33" src="https://user-images.githubusercontent.com/35772205/148951138-bb4dcc1d-78ba-40c7-b9d5-0d9f68d025a9.png">
<img width="1176" alt="Screenshot 2022-01-11 at 13 28 39" src="https://user-images.githubusercontent.com/35772205/148951877-4d46650d-05a3-46fe-a067-ed188c124d03.png">

### Expected behavior

Discount value should be correct and match the value placed over the image

### Steps to reproduce

1. Add a specific price to a product that has a discount value of over 83.33% of the original cost (tax included)
2. View the product

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3.9

**Comment by florine2623** [comment] 2022-01-11 13:44
Hello @miramar-gareth-parker ,

I can't reproduce your issue in PS 1.7.8.2 :
<img width="1134" alt="Screenshot 2022-01-11 at 14 42 55" src="https://user-images.githubusercontent.com/16019289/148953608-e51beb0f-62e7-42ce-82a0-c85b27d6e20a.png">
<img width="1172" alt="Screenshot 2022-01-11 at 14 43 00" src="https://user-images.githubusercontent.com/16019289/148953624-e5812f60-9f6a-49c9-ac87-e3aa427e15b4.png">

I tried to add a discount with a percentage, it works correctly.
Is there anything else to your configuration that I can try ?
Thanks!

**Comment by hibatallahAouadni** [comment] 2022-01-31 14:02
Hello @miramar-gareth-parker 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2022-01-31 14:02 UTC
Labels: Bug, FO, Discounts, Invalid
