### ISSUE TITLE
'InvalidArgumentException' with message 'Invalid type - expected string, but got (double) "0.4"' in.....

### ISSUE THREAD

**Issue by fre2004** [PrestaShop/PrestaShop#11091] opened 2018-10-20 09:38 UTC
Hello everyone,
when a user in a customer group with price reduction (eg. - 40%),
browse the shop online, he gets a blank page.

In erro_log i see:

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Invalid type - expected string, but got (double) "0.4"' in /home/.........

The file involved is: /vendor/prestashop/decimal/src/Number.php at line 66.
Here some server info:

Prestashop: 1.7.4.2
-- 

server Linux #1 SMP Wed Jul 11 13:51:30 MSK 2018 x86_64

server: Apache

PHP: 5.6.38

memory limit: 512M

mac exe.. time: 300

--

**Comment by khouloudbelguith** [comment] 2018-10-22 08:52
Hi @fre2004,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2018-11-22 15:11
Hi @fre2004,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2018-11-22 15:11 UTC
Labels: Bug, FO, No change required, 1.7.4.2
