### ISSUE TITLE
Set carrier restrictions when creating a new shop

### ISSUE THREAD

**Issue by Morerice** [PrestaShop/PrestaShop#25183] opened 2021-06-30 14:22 UTC
#### Describe the bug

Currently, when a new shop is created from the multistore page, the merchant is offered the option to import data from an already existing shop. If everything is selected and the new shop is created, the carrier restrictions linked to already existing plugins, on the old shop, are not copied over to the new shop.

#### Expected behavior
The carriers linked to already existing plugins should also be set on the new store. (Set in the `ps_module_carrier` table.)

#### Steps to Reproduce

1. Set some carrier restrictions on a payment plugin from the **Payment** > **Preferences** screen.
2. Create a new store by importing data from the old one, by using the functionality found in **Advanced Parameters** > **Multistore**.
3. Go to the **Payment** > **Preferences** screen on the newly created store and scroll down to the **Carrier Restrictions** section.
4. No restrictions are selected.

#### Additional information

The solution to this issue (shown below) is adding the `module_carrier` table to the `$asso_tables` array, found in `Shop.php`.

```
            'module' => ['type' => 'shop'],
            'module_currency' => ['type' => 'fk_shop'],
            'module_country' => ['type' => 'fk_shop'],
            'module_carrier' => ['type' => 'fk_shop'],
            'module_group' => ['type' => 'fk_shop'],
```

**PrestaShop version**: 1.7.7.1

**Comment by hibatallahAouadni** [comment] 2021-06-30 15:10
Hello @Morerice 

I think you forget to mention your PrestaShop version :sweat_smile: 
Please check and feedback.

Thanks!

**Comment by Morerice** [comment] 2021-07-02 06:28
Hi @hibatallahAouadni 

Apologies for my mistake. I've updated the description with the PrestaShop version.

Best regards,
Jean
Adyen

**Comment by khouloudbelguith** [comment] 2021-07-02 11:02
Hi @Morerice,

I manage to reproduce the issue with PS1775 and PS1765, it is added to our debug roadmap.
Your ticket is a duplicate of #17621
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-07-02 11:02
Duplicate of #17621

**Closed as completed by khouloudbelguith** 2021-07-02 11:02 UTC
Labels: Bug, BO, Duplicate, Carriers, Payment preferences, Multistore, 1.7.7.1
