### ISSUE TITLE
Reorder products dont work properly

### ISSUE THREAD

**Issue by fernandoherlo** [PrestaShop/PrestaShop#15143] opened 2019-08-17 16:42 UTC
**Describe the bug**
Sometimes when reorder the products, the order no save correctly

**To Reproduce**
1. Go to http://demo.prestashop.com/#/en/back -> Catalog -> Products
2. Click on Filter by category -> Accesories
3. Click Reorder -> drag and drop products

**Additional information**
PrestaShop version: 1.7.6

**Comment by fernandoherlo** [comment] 2019-08-18 10:52
I have tested it more, the error occurs only with Chrome, not in Firefox, Safari.

**Comment by matks** [comment] 2019-08-19 08:20
> I have tested it more, the error occurs only with Chrome, not in Firefox, Safari.

🤔 interesting, thanks for the extensive feedback

Chrome, why are you doing again ? 😄

**Comment by khouloudbelguith** [comment] 2019-08-19 10:23
Hi @fernandoherlo,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #14616
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-19 10:23
Duplicate of #14616

**Closed as completed by khouloudbelguith** 2019-08-19 10:23 UTC
Labels: Duplicate

**Comment by fernandoherlo** [comment] 2019-09-04 05:43
Thanks
