### ISSUE TITLE
Error BO - Modules section

### ISSUE THREAD

**Issue by Shark34** [PrestaShop/PrestaShop#12681] opened 2019-02-22 22:45 UTC
Hi !

There is a bug in Module section of PS 1.4.
Many modules are impacted but the first one in my PS is "followup" : see the screenshot attached.
No updates or modifications : it came like that...

Is there a problem from Prestashop directly ?

**To Reproduce**
1. Go to "Module" section
2. See the error
![screenshot_2019-02-22](https://user-images.githubusercontent.com/47904704/53275528-b69dd900-36fb-11e9-92f5-233fd87c13a9.png)

EDIT : 1 : If i delete followup/config.xml it show the same error with the next module. If i reload "Modules" section in BO the error come back for "followup" because config.xml is recreated.

**Additionnal information**
PrestaShop version: 1.4.7.0

**Comment by khouloudbelguith** [comment] 2019-02-25 08:14
Hi @Shark34,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1 & ps_reminder v2.0.0.
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6): the maintenance of PrestaShop 1.6 is extended to June 2019 for security and critical bugs.
So, the maintenance of PS1.4 is also stopped.
Since I cannot reproduce the issue with the latest version, I will close the issue.
Thanks for your understanding!

**Closed as completed by khouloudbelguith** 2019-02-25 08:14 UTC
Labels: No change required

**Comment by Shark34** [comment] 2019-02-25 09:14
Thanks for reply. I can see there is no "config.xml" files in each module folder now.

But as i understand it's a problem with Prestashop (parse XML) not my shop. Someone has changed this function (Prestashop team) and it's very disappoiting because many native modules doesn't work anymore...

Anyway, i've found another way.
