### ISSUE TITLE
BO Module page - Show state of every module (enabled / disabled)

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#37044] opened 2024-09-29 08:07 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Modules page showing modules but not their state (enabled / disabled), custom don't know, what module is enabled/disable. Most specific use case is, when customer find module via input search, where he wrote for example "slider" and he don't know, if module is enabled/disabled. He must use filter or click on "dropdown". It's not intuitive and it will result in many errors (configuring disabled module, etc.)

![Untitled](https://github.com/user-attachments/assets/b88b9bff-8465-4473-92d1-199561ec0822)

### Expected behavior

Customer must get known about module state. For example using red dot (diabled) / green dot (enabled) next to the name of module or something similar. There must be module state visible on modules page list, without any other clicking on dropdown menu or using filter.
Example:
![image](https://github.com/user-attachments/assets/8e9d353a-6899-4204-9e7e-1263157d102a)

### Steps to reproduce

1) go to modules section
2) disable any module
3) now you are not able to get know, what module is disabled / enabled

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

**Comment by Caleydon** [comment] 2024-09-29 15:44
+1

A visual indication of the module's state is definitely needed. Perhaps uninstalled modules should have a different background color for the entire row. Personally, I use a small modification that displays a red right border for Disabled and Uninstalled modules.

![module-indication](https://github.com/user-attachments/assets/720a4366-d67d-48a2-a1f5-04f3de83f831)

**Comment by Hlavtox** [comment] 2024-09-29 22:03
Duplicate of https://github.com/PrestaShop/PrestaShop/discussions/33462

**Comment by ShaiMagal** [comment] 2024-09-30 15:31
@Hlavtox OK, I didn't found this via search...
Closing this issue #37044 to prevent this duplicate with #33562

**Closed as completed** 2024-09-30 15:32 UTC
Labels: Bug
