### ISSUE TITLE
TinyMCE broken after upgrade to 1.7.8.2

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/PrestaShop#27453] opened 2022-01-24 22:05 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

#26543, #27147 and #26543 are closed issues that talk about this same issue. To me, it seems the problem still exist. It will highly be appreciated to get more feedback about it.

The problem: Text fields with tinyMCE doesn't appear. They appear in incognito mode as indicated in discussions.

Can someone help me understand how can the incognito mode affects a text field TinyMCE?

### Expected behavior

Text editors (TinyMCE) should appear for text fields in product/ category/modules...

### Steps to reproduce

1. Go to Product and try to edit the product.
2. Scroll down to the description field

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment] 2022-01-25 07:52
Hello @arouiadib 

This issue is a navigator cache problem, even after upgrade the navigator still use the old JS files.
So you need to clear your navigator cache and your shop cache to load the new JS files and that's the only way to not encounter this issue.

Closing the issue as it's not a Core bug but a navigator cache issue.

Thanks for your understanding 🙏

**Comment by hibatallahAouadni** [comment] 2022-01-25 07:52
Duplicate of #26543

**Closed as completed** 2022-01-25 07:52 UTC
Labels: Bug, Duplicate, Invalid

**Comment by arouiadib** [comment] 2022-01-25 16:26
@hibatallahAouadni . I don't know why CTRL+ F5 didn't work last time, but now It is working :sweat_smile: 
This is a stupid issue and sorry for wasting your time.

Thanks a lot for your usual guidance and help.
