### ISSUE TITLE
Cant delete product combinations prestashop 1.7.7.8

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#30733] opened 2023-01-04 11:28 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cant delete product combinations prestashop 1.7.7.8

### Expected behavior

Delete combinations

### Steps to reproduce

Go to BO > SELL > Catalog > Products
Click on Edit Product with combinations
Select combinations to delete and click "delete combinations"
Screen will freeze, save button, copy, go to catalog, add new product buttons turn grey (not clickable) and nothing happens anymore.
When refreshing, all cobinations are there again.

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.4.33

**Comment by paulnoelcholot** [comment] 2023-01-04 15:23
Hello @loetje88,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://watch.screencastify.com/v/ZWlieefcqCPjv4sE2TIO

**Closed as completed by paulnoelcholot** 2023-01-04 15:23 UTC
Labels: Bug, Can't reproduce
