### ISSUE TITLE
PrestaShop 1.7.6.x - Impossible the edit "Themes translations" for custom themes + missing expressions

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#17953] opened 2020-03-03 15:29 UTC
#### Describe the bug

Issue 1. It is impossible to edit translations for custom themes (PrestaShop 1.7.6.x)
Issue 2. Missing expressions (all PrestaShop 1.7 versions)

#### Expected behavior

If I use the default "classic" theme I can see all translations and edit all 1065 expressions in the tab International->Translations:
https://prnt.sc/rayi7r
https://prnt.sc/rayj24

If I use the custom theme, I see missing translations and only 365 expressions are available:
https://prnt.sc/raykcb

#### Steps to Reproduce

1.Use the default "classic" `theme.`

2. Go to tab International->Translations, select "Theme translations", "classic" and language:
https://prnt.sc/rayi7r

3. You can see that everything is fine:
https://prnt.sc/rayj24

4. Now create a copy of the "classic" theme for example "classic2" or use any other custom theme.

5.Go to translations:
https://prnt.sc/rayo8j

6.You can see missing translations and missing expressions:
https://prnt.sc/rayj24

**Screenshots**

Classic theme:
https://prnt.sc/rayj24

Classic2 (or any other custom theme):
https://prnt.sc/rayj24

#### Additional information

* PrestaShop version: missing translations - PrestaShop 1.7.6.x, missing expressions (only 365 of 1065 are displayed) - all PrestaShop 1.7 versions

* Fix - I see that I can edit the file:
\src\PrestaShopBundle\Service\TranslationService.php 
and change here "classic" to "classic2" (or another theme name) and all default translations and expressions are displayed, but after this custom theme translations in the tab Shop->Theme->Mytheme are not available.

**Comment by khouloudbelguith** [comment] 2020-03-04 08:09
Hi @Angar90,

We are awre of this issue.
Your ticket is a duplicate of #9818
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-03-04 08:09
Duplicate of #9818

**Closed as completed by khouloudbelguith** 2020-03-04 08:09 UTC
Labels: Duplicate, Translations, Modules & Themes
