### ISSUE TITLE
Error when saving Schema of URLs 

### ISSUE THREAD

**Issue by Rubben1985** [PrestaShop/PrestaShop#30354] opened 2022-11-19 13:06 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It seems it is not longer possible to modify my URL link format (Schema of URLs ) because it always shows the error:

Keyword "{id}" required for route "layered_rule" (rule: "disablethisrule-62d291255d504")
Keyword "{selected_filters}" required for route "layered_rule" (rule: "disablethisrule-62d291255d504")

However as you can see there is not missing any of those parameters
![image](https://user-images.githubusercontent.com/52702489/202851877-e2486b63-d5cc-4709-b094-f88041f3371d.png)

The thing is that it all actually works, and even it provokes an error not changing anything in the URL format but simply saving in the section save button in its actual state.

The problems are two
1- Error when saving, even in the actual working configuration
2-Can not modify the actual configuration because it is not saved.

### Expected behavior

Save if all mandatory parameters are included

### Steps to reproduce

1-go to shop parameters->traffic&SEO -> Schema of URLs section
2-Click save button of Schema of URLs section (other save buttons of the page are working but not saving that section)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by PrestaEdit** [comment] 2022-11-21 07:21
Hi @Rubben1985 ,

To avoid QA to reproduce this cause it's not related to PrestaShop but to a third party module, let me answer you.

When you have the Faceted Search and the third party module Advanced Search (4 or 5), the layered rule is disabled with this "disablethisrule" prefix.
To fix that, you need to : disable/uninstall the Faceted Search module as its not work together the other module or disable the third party module.

**Comment by AureRita** [comment] 2022-11-21 17:26
Hi @Rubben1985 

Thank for your report, Unfortunately, I can't reproduce your issue, as you can see on this video : 

[Untitled_ Nov 21, 2022 6_24 PM.webm](https://user-images.githubusercontent.com/100699445/203120836-618497fe-a08b-4887-9f44-237f7995664a.webm)

Can you check what prestaEdit send to you to see if it's related to this or not ? 

Waiting for your feedback

**Comment by Rubben1985** [comment] 2022-11-21 18:10
@PrestaEdit 
Indeed I had that module installed before but it is not installed anymore. Following your suggestion, I even try uninstalling also the PS faceted module, so right now I do not have any of them. I even removed the tables in the database (at least those obvious to me that started with pm_advanced...)
The problem still persists. Any idea if the module leaves something "behinds" that I should manually modify/delete?

**Comment by hibatallahAouadni** [comment] 2022-11-22 16:19
Hello @Rubben1985 

It seems that your issue is not a PrestaShop core bug.
If your module is Advanced Search Official, please contact support team on Addons.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

We will close this issue.

PS: thanks @PrestaEdit for your quick reply :rocket: :pray: 

Thanks!

**Closed as completed by hibatallahAouadni** 2022-11-22 16:19 UTC
Labels: Bug, BO, FO, SEO & URLs, Invalid, 1.7.8.7
