### ISSUE TITLE
can not delete product images

### ISSUE THREAD

**Issue by shikotakcom** [PrestaShop/PrestaShop#20609] opened 2020-08-17 13:24 UTC
![product image](https://user-images.githubusercontent.com/48174981/90401131-c3ae4500-e0b2-11ea-9ec8-ccf17f431881.jpg)
When I copy a product I can not delete the previous product image. 
At first it seems that images delete but when I back the new product, the images of both product has been show.

* PrestaShop version: 1.7.5.0
* PHP version: 7.1

**Comment by khouloudbelguith** [comment] 2020-08-17 13:43
Hi @shikotakcom,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1y9-naklYvG43D_RphRThmheFV5-j4ijG/view?usp=sharing
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2020-08-17 13:44
@shikotakcom, please in the next time follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thanks for your understanding!

Thank you

**Comment by khouloudbelguith** [comment] 2020-09-07 08:29
Hi @shikotakcom,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-09-07 08:29 UTC
Labels: Bug, BO, No change required, 1.7.5.0
