### ISSUE TITLE
Problem with new order email alerts Prestashop 1.7.5.1

### ISSUE THREAD

**Issue by Tomskor** [PrestaShop/PrestaShop#13001] opened 2019-03-22 07:11 UTC
**Describe the bug**

We have problem with email alerts from presta 1.7.4.2 I think, we don't recive any of alerts so we configure SMTP and it worked fine for now. But now we have only some part of notification with new orders. How to fix it? 

![maile](https://user-images.githubusercontent.com/42567245/54806243-b866a800-4c79-11e9-89c5-19cbf62d2edc.png)

PrestaShop version: 1.7.5.1
PHP version: 7.2.13

**Comment by khouloudbelguith** [comment] 2019-03-22 07:58
Hi @Tomskor,

What is the exact version of the mailalert did you installed?

Thanks!

**Comment by Tomskor** [comment] 2019-03-22 08:03
@khouloudbelguith  Email alerts 2.1.1.

**Comment by khouloudbelguith** [comment] 2019-03-22 14:18
Hi @Tomskor,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-22 07:38
Hi @Tomskor, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-22 07:38 UTC
Labels: No change required, ps_emailalerts

**Comment by Tomskor** [comment] 2019-04-23 12:18
Hi @khouloudbelguith 

I just can't do all stuff from the list. That's hard to look at specific bug on the living main store, when it's just happend occasionally. We can't impede our customers using our shop, and we havn't enough time to clone everything and trying to find this bug. I just hope maybe in some update you will fix this.

**Comment by banobazaar** [comment] 2019-07-10 22:19
Hi khouloudbelguith
I am facing similar issue.

I am going through an issue and tried too many solution available over the internet and the forum but nothing is working. 
When ever order is created, email do not works. rather its gives 500 internal error. when I disable the email option, order works fine but auto email don't. 
Test email works fine and received as well. 
I am hosting @Go Daddy  
domain name: banobazaar.com 
email: order@banobazaar.com 
Need urgent support please. 

Debug

(1/1) UndefinedFunctionException 
Attempted to call function "idn_to_ascii" from the global namespace. 
in Mail.php line 893 
at MailCore::toPunycode('order@banobazaar.com')in Mail.php line 317 
at MailCore::send(1, 'new_order', 'New order : #61 - URVVZIJQU', array('{firstname}' => 'Adnan', '{lastname}' => 'Qaiser', '{email}' => 'adnan@abc.com', '{delivery_block_txt}' => 'Adnan Qaiser121 abc society54400 LahorePakistan+923218181010', '{invoice_block_txt}' => 'Adnan Qaiser121 abc society54400 LahorePakistan+923218181010', '{delivery_block_html}' => '<span style="color:#db3484; font-weight:bold;">Adnan</span> <span style="color:#db3484; font-weight:bold;">Qaiser</span><br />121 abc society<br />54400 Lahore<br />Pakistan<br />+923218181010', '{invoice_block_html}' => '<span style="color:#db3484; font-weight:bold;">Adnan</span> <span style="color:#db3484; font-weight:bold;">Qaiser</span><br />121 abc society<br />54400 Lahore<br />Pakistan<br />+923218181010', '{delivery_company}' => '', '{delivery_firstname}' => 'Adnan', '{delivery_lastname}' => 'Qaiser', '{delivery_address1}' => '121 abc society', '{delivery_address2}' => '', '{delivery_city}' => 'Lahore', '{delivery_postal_code}' => '54400', '{delivery_country}' => 'Pakistan', '{delivery_state}' => '', '{delivery_phone}' => '+923218181010', '{delivery_other}' => '', '{invoice_company}' => '', '{invoice_firstname}' => 'Adnan', '{invoice_lastname}' => 'Qaiser', '{invoice_address2}' => '', '{invoice_address1}' => '121 abc society', '{invoice_city}' => 'Lahore', '{invoice_postal_code}' => '54400', '{invoice_country}' => 'Pakistan', '{invoice_state}' => '', '{invoice_phone}' => '+923218181010', '{invoice_other}' => '', '{order_name}' => 'URVVZIJQU', '{order_status}' => 'Processing in progress', '{shop_name}' => 'Online Shopping Stores - Bano Bazaar', '{date}' => '07/09/2019', '{carrier}' => 'Cash On Delivery (BB-CoD)', '{payment}' => 'Cash on delivery (COD)', '{items}' => '<tr style="background-color:#EBECEE;"> <td style="padding:0.6em 0.4em;"></td> <td style="padding:0.6em 0.4em;"> <strong><a href="http://banobazaar.com/en/women/41-tops-.html">Tops</a></strong> </td> <td style="padding:0.6em 0.4em; text-align:right;">PKR500.00</td> <td style="padding:0.6em 0.4em; text-align:center;">2</td> <td style="padding:0.6em 0.4em; text-align:right;">PKR1,000.00</td> </tr>', '{total_paid}' => 'PKR1,000.00', '{total_products}' => 'PKR1,000.00', '{total_discounts}' => 'PKR0.00', '{total_shipping}' => 'PKR0.00', '{total_tax_paid}' => 'PKR0.00', '{total_wrapping}' => 'PKR0.00', '{currency}' => 'Rs', '{gift}' => false, '{gift_message}' => '', '{message}' => 'No message'), 'order@banobazaar.com', '', 'order@banobazaar.com', 'Online Shopping Stores - Bano Bazaar', null, null, '/home/banonmjc/public_html/modules/ps_emailalerts/mails/', null, 1)in ps_emailalerts.php line 471 
at Ps_EmailAlerts->hookActionValidateOrder(array('cart' => object(Cart), 'order' => object(Order), 'customer' => object(Customer), 'currency' => object(Currency), 'orderStatus' => object(OrderState), 'cookie' => object(Cookie), 'altern' => 2))in Hook.php line 966 
at HookCore::coreCallHook(object(Ps_EmailAlerts), 'hookactionValidateOrder', array('cart' => object(Cart), 'order' => object(Order), 'customer' => object(Customer), 'currency' => object(Currency), 'orderStatus' => object(OrderState), 'cookie' => object(Cookie), 'altern' => 2))in Hook.php line 351 
at HookCore::callHookOn(object(Ps_EmailAlerts), 'actionValidateOrder', array('cart' => object(Cart), 'order' => object(Order), 'customer' => object(Customer), 'currency' => object(Currency), 'orderStatus' => object(OrderState), 'cookie' => object(Cookie), 'altern' => 2))in Hook.php line 903 
at HookCore::exec('actionValidateOrder', array('cart' => object(Cart), 'order' => object(Order), 'customer' => object(Customer), 'currency' => object(Currency), 'orderStatus' => object(OrderState), 'cookie' => object(Cookie), 'altern' => 2))in PaymentModule.php line 730 
at PaymentModuleCore->validateOrder(63, '3', 1000.0, 'Cash on delivery (COD)', null, array(), null, false, 'daf647d11495eb7f66b5933aa509bbcd')in validation.php line 57 
at Ps_CashondeliveryValidationModuleFrontController->postProcess()in Controller.php line 270 
at ControllerCore->run()in Dispatcher.php line 511 
at DispatcherCore->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment] 2019-07-11 08:29
@banobazaar, issue created here: #14582.
