### ISSUE TITLE
'Classic" theme PrestaShop  1.7.4.2 on Safari IPhones 4 and 5 CSS problem

### ISSUE THREAD

**Issue by MisteryPresta** [PrestaShop/PrestaShop#10349] opened 2018-09-07 20:19 UTC
On browser Safari (IPhone) All the product images  are not displaying  vertically but horizontally,  going out of the screen,  you have to scroll from left to right, looks unresponsive, Ugly.
You have to verify this bug with the real Iphone not online simulation.
See screenshot.

![img_3477](https://user-images.githubusercontent.com/43077925/45241240-ee4ecb00-b2eb-11e8-87f0-74441c1d43e5.PNG)

**Comment by khouloudbelguith** [comment] 2018-09-10 10:04
Hi @MisteryPresta,

I tried with an iPhone 8 Safari browser & it is OK.
I attached a screenshot.
![image](https://user-images.githubusercontent.com/16067358/45291106-8a95ef00-b4f1-11e8-82c0-d4ab75eab7a2.png)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by MisteryPresta** [comment] 2018-09-10 10:15
Can you check it on real phone please?
We are few people with the same problem:
https://www.prestashop.com/forums/topic/637070-prestashop-17-classic-bug-on-safari/?tab=comments#comment-2967045

**Comment by khouloudbelguith** [comment] 2018-09-10 10:33
Hi @MisteryPresta,

It seems to be OK, I checked the last version 1.7.4.2 (after an upgrade) on the iPhone SE.
![image](https://user-images.githubusercontent.com/16067358/45292460-92f02900-b4f5-11e8-93ea-fa0014e63bf0.png)

Best regards, Khouloud

**Comment by MisteryPresta** [comment] 2018-09-10 12:25
I can not see the image of the second product on your phone,
in my phone screen-shot it is clear that the second 
product is going out of the screen to the right, instead 
it should be going down:
![img_3490](https://user-images.githubusercontent.com/43077925/45297271-241acc00-b505-11e8-9562-9fd00f27a3f1.PNG)

**Comment by khouloudbelguith** [comment] 2018-09-10 13:16
Hi @MisteryPresta,

What is the exact iPhone did you use?

Best regards, Khouloud

**Comment by MisteryPresta** [comment] 2018-09-10 15:53
Iphone 4S

**Comment by khouloudbelguith** [comment] 2018-09-10 16:01
Hi @MisteryPresta,

Yes, you are right with iPhone 5s safari browser, I manage to reproduce this issue.
![image](https://user-images.githubusercontent.com/16067358/45309212-8387d480-b523-11e8-899b-a456ce1bbf48.png)
We will see how to fix it.

Best regards, Khouloud

**Comment by MisteryPresta** [comment] 2018-09-10 16:17
Thank you !
This is very important for my Shop because  most of my clients use Iphone 5 and sometimes 4.

**Comment by rdy4ever** [comment] 2018-09-10 17:09
Hi @khouloudbelguith 
Could you please tell me what tool do you use to test mobile rendering? Crome dev tools do not show this layout problem.

**Comment by MisteryPresta** [comment] 2018-09-11 17:39
You need a real Iphone 5 or 4 and a Mac computer to connect to in development mode.

**Comment by MisteryPresta** [comment] 2018-09-14 16:12
Problem with CSS file solved:
https://www.prestashop.com/forums/topic/637071-classic-theme-ps1742-and-safari

**Comment by khouloudbelguith** [comment] 2018-09-14 16:15
Hi @MisteryPresta,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

Best regards, Khouloud

**Comment by ghost** [comment] 2019-04-17 15:24
Hi everyone,

Is this issue still relevant?
We need more info

Thanks

**Comment by MisteryPresta** [comment] 2019-04-17 16:01
Yes It is solved by modification of CSS file
https://www.prestashop.com/forums/topic/637071-classic-theme-ps1742-and-safari/

**Comment by ghost** [comment] 2019-04-18 14:05
Hello,

We decided to close this issue.

* A fix has already been done before, it seems that the problem only happens on some old Safari versions.
But we don't know which ones and we can't reproduce it.

* We checked the numbers, iPhones 4 and 5 only represent 4% of the iPhone market shares (Statista 2018) this percentage is even lower if we only count the ones still using old Safari versions.

If you have any news or info about the issue or Safari let us know 👍 

Thanks

**Closed as completed** 2019-04-18 14:06 UTC
Labels: Minor, FO, Can't reproduce, 1.7.4.2, Front-end
