### ISSUE TITLE
Bad management of categories images

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#23874] opened 2021-04-02 12:06 UTC
#### Describe the bug

While creating a category, you can add three images:

1. Cover
2. Thumbnail
3. Menu (Thumbnail)

The first one is used everywhere, but the thumbnails are never used and are not usable.
Classic theme take also the cover in order to show thumbnail in subcategories listing.

Also, deleting the cover image delete the two others ones and adding a new cover change the thumbnail.

#### Expected behavior

Allow us to set an image an be able to use it.
Right now, we need the cover to have "id_image" set and also there is nothing related to thumbnail of the category in code.

#### Steps to Reproduce

1. Go to a category edition
2. Add different images
3. See that it's deleted/changed regarding the image you add

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: N/A

**Comment by florine2623** [comment] 2021-04-02 13:07
Hello @PrestaEdit ,

Cover image is used in the category page :
![Capture d’écran 2021-04-02 à 15 02 58](https://user-images.githubusercontent.com/16019289/113417840-9b1a5780-93c4-11eb-808f-0645d5aa6ced.png)
After I deleted the image, it's been deleted correctly and not shown on category page :
![Capture d’écran 2021-04-02 à 15 05 25](https://user-images.githubusercontent.com/16019289/113418009-e9c7f180-93c4-11eb-80c8-1eac5dc0a67c.png)
![Capture d’écran 2021-04-02 à 15 05 14](https://user-images.githubusercontent.com/16019289/113418019-ecc2e200-93c4-11eb-9e03-01c95a0febf3.png)

I can't reproduce your issue.
Am I missing something ?

**Comment by PrestaEdit** [comment] 2021-04-02 13:12
Yes,

You don't test to add only a thumbnail and/or to use different images on the three fields.

**Comment by florine2623** [comment] 2021-04-02 13:34
Please check my screen record : https://drive.google.com/file/d/11cZCqq0pjjBiNdDMqpX_AKbBiP3GJ1ag/view

**Comment by PrestaEdit** [comment] 2021-04-02 13:38
Nice cat.

But, don't delete the cover, check that while you have change the first cover (1. Cover to cat image), see that the two others image was changed too.
And theses images have nothing in PrestaShop code to be used with.
So, it's two fields for nothing or not well handled.

**Comment by florine2623** [comment] 2021-04-23 12:51
Hello @PrestaEdit,

Sorry for the response delay.

After deleting the cat image, I noticed that not only the cat image was deleted, but also the second picture for category thumbnail.

These images can be useful depending on the template you use for your shop.

**Comment by hibatallahAouadni** [comment] 2021-05-12 10:49
Hello @PrestaEdit ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-05-12 10:49 UTC
Labels: Bug, BO, Categories, Image, No change required, 1.7.7.3
