### ISSUE TITLE
Prestashop 8.1.2 - show different images  when turn ON webp images

### ISSUE THREAD

**Issue by JanSam880** [PrestaShop/PrestaShop#34920] opened 2023-12-27 10:21 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After turning ON webp images, some goods will start to display different images than they should. When I turn OFF webp and only JPG images remain on, everything is fine.
It does not do this for all images, max 7% of all!  I still haven't found the reason why I do this with some pictures. When I turn off webp, everything is fine. Tested on about 3000 products.
Tested on the basic template.

### Steps to reproduce

1. turn off webp
2. go to web site and load products on products lists with images
3. turn ON webp
4. open next window  and load products on products lists with images
5. compare both products lists
6. some products  have different pictures than they should have

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.0

**Comment by AureRita** [comment] 2023-12-28 14:47
Hi @JanSam880 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see 

[recording(26).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/720d4317-4211-4af7-834a-d0ec66cef06c)


Did I miss something ? 
Did you use this version of image setting or the other ? 

Can you give us a video for exemple ? 

Waiting for your feedback

**Comment by paulnoelcholot** [comment] 2024-01-16 08:13
Hello @JanSam880

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Closed as completed by paulnoelcholot** 2024-01-16 08:13 UTC
Labels: Bug, FO, Can't reproduce, Image, 8.1.x
