### ISSUE TITLE
Can't drag & drop categories to change the view order

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#23198] opened 2021-02-09 21:45 UTC
#### Describe the bug

Usually there is a draggable handle in the start of the category line but for some reason not appear anymore.

#### Expected behavior

Usually with a blue dotted handle is possible to change the order of the Catogories and subcategories

#### Steps to Reproduce

1. Go to Catalog > Categories
2. try to find the draggable handle but is not present

**Screenshots**

![image](https://user-images.githubusercontent.com/16102074/107432171-d8323e00-6b27-11eb-806d-38adeb8a0181.png)

Looking inside the HTML there is missing the draggable cell:

![image](https://user-images.githubusercontent.com/16102074/107432399-30694000-6b28-11eb-8df8-a5e96f99d6e9.png)

in another installation PS1.7.6.5 there is the draggable part:

![image](https://user-images.githubusercontent.com/16102074/107432478-51319580-6b28-11eb-9796-c428c800e396.png)

I don't know if is a strange Bo configuration parameter i still not found or simply a bug.

Thank you

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment] 2021-02-10 09:58
Hello @HartLarsson 

Could you please check if you had **Position** column, if so click on it: 

![image](https://user-images.githubusercontent.com/23308427/107494277-e23b5780-6b8e-11eb-80d7-e5fe5376fb8c.png)

If the **Position** column is not displayed, it means that you use **All shops**, so choose a store and the column will be displayed.

So, I close the issue cause it's not a bug :wink: 

Thanks!

**Closed as completed** 2021-02-10 09:59 UTC
Labels: No change required

**Comment by HartLarsson** [comment] 2021-02-10 10:06
Please don't close before i can answer!

1) Is not a multistore
2) the column as i saw in my screenshot is not displayed
3) the part of html code is totally missed, that means is not rendered or enabled for some reason

Is a bug or a problem somewhere

**Comment by hibatallahAouadni** [comment] 2021-02-10 10:08
@HartLarsson could you please provide a screenshot on the whole page BO>SELL>Category>Categories. Thanks!

**Comment by HartLarsson** [comment] 2021-02-10 10:11
ERRATA CORRIGE: i found was a strange JS problem in console. I find the problem and now is working again!

Thank you

**Comment by hibatallahAouadni** [comment] 2021-02-10 10:12
@HartLarsson you're welcome :slightly_smiling_face:

**Comment by soubheek** [comment] 2024-01-26 07:37
> Hello @HartLarsson
> 
> Could you please check if you had **Position** column, if so click on it:
> 
> ![image](https://user-images.githubusercontent.com/23308427/107494277-e23b5780-6b8e-11eb-80d7-e5fe5376fb8c.png)
> 
> If the **Position** column is not displayed, it means that you use **All shops**, so choose a store and the column will be displayed.
> 
> So, I close the issue cause it's not a bug 😉
> 
> Thanks!

Just amazing solutions. Thanks

**Comment by soubheek** [comment] 2024-01-26 08:32
> Hello @HartLarsson
> 
> Could you please check if you had **Position** column, if so click on it:
> 
> ![image](https://user-images.githubusercontent.com/23308427/107494277-e23b5780-6b8e-11eb-80d7-e5fe5376fb8c.png)
> 
> If the **Position** column is not displayed, it means that you use **All shops**, so choose a store and the column will be displayed.
> 
> So, I close the issue cause it's not a bug 😉
> 
> Thanks!

Just amazing solution. Thanks
