### ISSUE TITLE
Mail body preview isn't translated

### ISSUE THREAD

**Issue by MultiTech-MS** [PrestaShop/PrestaShop#20959] opened 2020-09-11 14:38 UTC
#### Describe the bug

Our shop is in French. Translations are made but there's some inconsistance when it comes to emails translations.
Some mails received by our shop have this model (see snapshot): 
-> **Mail Subject** = Translation OK _(in French)_,
-> **Preview** of body = in english ,
-> **Mail Body** = Translation OK _(in French)_,

We're using the "modern" version of email theme.

#### Expected behavior

If the subject and the body of the mail are well translated, the french and not the english version of the body 
should be displayed in the preview. I'm using Gmail

#### Steps to Reproduce

1. Configure a shop in French,
2. Have a gmail account _(I don't know if other webmail providers have the same issue)_,
3. Add / Download french translations package
4. Send you some mail in Email Theme -> Email Theme -> choose modern ->Send you some mails.
5. Subject and boyd translations should be fine, 
and the preview stays in the original language of the email template files = english

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
![Screenshot_mail-preview-translations-Gmail](https://user-images.githubusercontent.com/51752454/92938673-280fba80-f44d-11ea-9d88-cf2bb9523276.jpg)

* PrestaShop version: 1.7.6.3
* PHP version:  7.2

**Comment by florine2623** [comment] 2020-09-11 15:19
Hi @MultiTech-MS ,
I can't reproduce the issue in 1.7.6.7.
Is your back-office in French too ? Or do you have other languages (activated or deactivated) ?

Thanks!

**Comment by MultiTech-MS** [comment] 2020-09-11 15:38
Hi Florine,

Yes, the back-office is in french. It's the only language installed :

![Capture-mail-trad-2](https://user-images.githubusercontent.com/51752454/92945462-96587b00-f455-11ea-8968-5c9df9d11772.PNG)
![Capture-mail-trad](https://user-images.githubusercontent.com/51752454/92945464-96f11180-f455-11ea-98df-7561df75a408.PNG)

**Comment by khouloudbelguith** [comment] 2020-09-14 14:21
Hi @MultiTech-MS,

I did not manage to reproduce the issue with PS1767.
I attached a screen record
https://drive.google.com/file/d/1o8wPL4a-dAULUsIItGCoIxOt91aY5ryX/view?usp=sharing
Thanks to check and feedback.

**Comment by daghb** [comment] 2020-09-14 16:37
I had the same issue in 1.7.6 and was told this was fixed in 1.7.7

**Comment by MultiTech-MS** [comment] 2020-09-15 08:37
Hi @khouloudbelguith ,

Unfortunately, "rewriting email templates" option doesn't seem to work for me in 1.7.6.3 :
- "Subject" in french,
- Preview of the mail content : english,
- Mail body : french

Between our version ands yours (1.7.6.7), I only see that line in the 1.7.6.4 changelog that could have maybe fixed it : 
- #17608: Email subject doesn't support html entities (by @Progi1984)

Hello @daghb, thanks for your feedback. It's good to know, it's not a big issue but Gmail should previewed the mail's body in 
the shop language. I see in 1.7.7.0 beta those lines : 
- #17009: Functional tests - add test 'Preview Email Themes' (by @boubkerbribri)
- #17201: Functional Tests - Fix "emailThemes/01_previewEmailThemes" test (by @nesrineabdmouleh)
- #18504: Fix wording in classic guest mail template (by @jolelievre) _(even though I'm using the modern template in this case)_
- #14545: Remove english emails since they are generated now (by @jolelievre)

**Closed as completed** 2020-09-15 08:39 UTC
Labels: Translations, No change required, Email theme

**Comment by MultiTech-MS** [comment] 2020-09-15 08:41
It worked for me by "rewriting email templates", not on the 'Core independant from themes", but on the theme I was using. 
Thank you. Hope this ticket will help.
