### ISSUE TITLE
Tax/totals rounding issues (on the invoice)

### ISSUE THREAD

**Issue by mortenhartvig** [PrestaShop/PrestaShop#10815] opened 2018-10-02 15:12 UTC
**Describe the bug**

On my site, i have a product with a regular price of 4999
It has a general 20% discount applied via some rule for the category. Therefore the 20% discount sets the sale price for 3999.20, rounded down to 3999, due to my rounding settings (round every item, zero decimals, std. rounding up from half)

(the customer pays 3999 on the website, which is fine)

**Prestashop gives me the following on the invoice generated:**

(orderline) Product basic price 3999.20, Item price: 3199.36, Line total 3199 (all excluding taxes)

(25% tax rate in this example)

Total excluding tax: 3199,00 
(if the paid amount is 3999, then this is wrong. It has to be 75% of the total, which is 3199,20)

Taxes: 800 DKK 
(if the paid amount is 3999, then this is wrong. It has to be 25% of the total, which is 799,80)

Total: 3999 DKK (correct)

**The problem**
- In our accounting software. If you take the total excluding tax, and apply 25% tax, the total is 3998,75. 
- Our accounting software expects a payment for 3998.75, and our tax calculations are off (the tax we have to pay to our local government)

Why are my totals rounded?
**Additionnal information**
PrestaShop version: 1.7.2.2
PHP version: 7

**Comment by khouloudbelguith** [comment] 2018-10-02 15:29
Hi @mortenhartvig,

Have you the same issue with this ticket:  Rounding Problem: #9779?

**Comment by mortenhartvig** [comment] 2018-10-12 11:19
@khouloudbelguith - Im not sure, although they look similar. 

My focus was on, that when rounding the items (the every item setting), the total should be left untouched in terms of rounding. Using a basic calculator, you should be able to check/verify the numbers in the totals (because the main purpose of accounting software, is checking the numbers)

(even when rounding items to zero decimals ie. whole numbers. Decimal numbers should still be on the invoice, because the tax calculation has to contain decimals. 

(e.g. the number 1 multiplied by 0.8 (when removing 25% tax) is neither supposed to be 1 nor 0, its 0.8).

**Comment by khouloudbelguith** [comment] 2018-10-12 13:27
Hi @mortenhartvig,

Thanks for your feedback.
In fact, we have a different rounding problem, it is an issue should be specified & fixed by our developers.
We are aware of this issue.
Your ticket is a duplicate of #9779
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-12 13:27
Duplicate of #9779

**Closed as completed by khouloudbelguith** 2018-10-12 13:27 UTC
Labels: Bug, Duplicate, Invoices
