### ISSUE TITLE
Problem in the price window of a product

### ISSUE THREAD

**Issue by Alex-sp-es** [PrestaShop/PrestaShop#18039] opened 2020-03-08 10:04 UTC
When you want to adjust a price in the PRICES tab, the left bar of Prestashop is above the content, even hiding it, do not allow access to the price box. Verified in different browsers.

**Comment by khouloudbelguith** [comment] 2020-03-09 12:02
Hi @Alex-sp-es,

Could you please add steps to reproduce the issue in a new comment.

Thanks!

**Comment by khouloudbelguith** [comment] 2020-04-07 07:49
Hi @Alex-sp-es,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2020-04-07 07:49 UTC
Labels: Bug, FO, Taxes and Prices, No change required
