### ISSUE TITLE
Prestashop language selector not switching to default language

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#12943] opened 2019-03-15 18:56 UTC
I am using prestashop 1.7.5 in multistore. 

For one store i have enabled french and nl language. 

nl is the default language.

When first time access the website  .nl automatically loaded .And after selecting the fr the store switched to the fr language. Now if again i am trying to the nl then its not working.

**Comment by khouloudbelguith** [comment] 2019-03-18 08:48
Hi @pks891618,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1muMAyPzOzmFnnzJFhufay9Q06NZRZiEl/view
Thanks to check & feedback.

**Comment by pks891618** [comment] 2019-03-20 12:17
@khouloudbelguith  thanks for your response.

Please check the below recorded video

https://drive.google.com/file/d/1FgeKJ5gwclrf6zj8-XPRX-tT1F3JZaxO/view

Thanks

**Comment by khouloudbelguith** [comment] 2019-03-21 16:42
@pks891618, I tried to make a shop similar
https://drive.google.com/file/d/1fJ3MSweqwtPCRsCburc4YYp62wlP2Hl0/view
But it is OK.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment] 2019-04-22 07:33
Hi @pks891618, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-04-22 07:33 UTC
Labels: FO, International, Multistore, Languages, No change required, 1.7.5.1
