### ISSUE TITLE
[FO] Header's searchbox on tablets is too big and off to the right

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26643] opened 2021-11-17 00:40 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Header's searchbox on tablets is even bigger than on desktops. Also it leaks on the right.

![obraz](https://user-images.githubusercontent.com/5007456/142088571-14487390-d9e1-42fa-ab31-a62308288821.png)

On bigger screens it's ok:

![obraz](https://user-images.githubusercontent.com/5007456/142088260-cdffc15b-56c4-44b4-97fc-405659bce300.png)

### Steps to reproduce

1. Open homepage on 768-991 px screen width.
2. Compare with other screen sizes

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by hibatallahAouadni** [comment] 2021-11-17 15:08
Hello @SharakPL 

Thanks for reporting the issue!
Indeed it's a regression on 1.7.8.0, with PS1.7.7.8 the searchbar move below to menu when menu-items are longer:

![image](https://user-images.githubusercontent.com/23308427/142222224-924f71c6-e51d-4c38-bbef-87881f94e1bd.png)

![image](https://user-images.githubusercontent.com/23308427/142226253-b9bfcb22-ea3a-4b22-847e-40e2cc8fd069.png)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment] 2021-12-27 13:13
Fixed in #26706 by @NeOMakinG & Tested by @HanaRebaiQA

**Closed as completed by Progi1984** 2021-12-27 13:13 UTC
Labels: Bug, Trivial, FO, Regression, Mainmenu, Fixed, Front-end, PR available, Responsive, 1.7.8.0
