### ISSUE TITLE
Category's "Menu thumbnails" missing after images are regenerated

### ISSUE THREAD

**Issue by pmysiak** [PrestaShop/PrestaShop#18169] opened 2020-03-16 21:01 UTC
When images are regenerated in menu Design -> Image settings -> REGENERATE THUMBNAILS, category's property "Menu thumbnails" is empty.

#### Expected behavior

I expected that images would exist.

#### Steps to Reproduce

1. Add images for a category (set field "Menu thumbnails")
2. Go to Design -> Image settings -> REGENERATE THUMBNAILS
3. Regenerate categories for all formats
4. Edit the category, there would be empty field "Menu thumbnails"

* PrestaShop version: 1.7.1.2 & 1.7.6.0
* PHP version: 5.6

**Comment by khouloudbelguith** [comment] 2020-03-17 08:39
Hi @pmysiak,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.4 and PS1.7.5.2.
~~https://drive.google.com/file/d/1_vcZ4BjSCr5oNqd8NZuxbukPCYbMIMjG/view?usp=sharing~~

[undefined.webm](https://user-images.githubusercontent.com/1533248/203002185-6d8293f8-7e5b-46d4-9875-fd0d413087d3.webm)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Just for information, the thumbnail is not used in the classic template.
In fact, we will offer a category thumbnail feature, we will enable merchants to choose to have different cover image and thumbnail as reported here: #12760

Thanks!

**Comment by davidglezz** [comment] 2020-03-17 09:14
I can't view https://drive.google.com/file/d/1_vcZ4BjSCr5oNqd8NZuxbukPCYbMIMjG/view
@khouloudbelguith  I don't have permissions

**Comment by khouloudbelguith** [comment] 2020-03-17 09:22
@davidglezz, I updated permissions :slightly_smiling_face: 
https://drive.google.com/file/d/1_vcZ4BjSCr5oNqd8NZuxbukPCYbMIMjG/view?usp=sharing

Thanks!

**Comment by MatShir** [comment] 2022-12-07 11:59
close in favor of https://github.com/PrestaShop/PrestaShop/issues/30520
Don't hesitate to check the issue ! 
Duplicate of #30520

**Closed as completed by MatShir** 2022-12-07 11:59 UTC
Labels: Bug, Minor, BO, Duplicate, Categories, Image, Good first issue, Verified
