### ISSUE TITLE
[BO] The Employee page is broken when adding Arabic language - Bad display

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#32070] opened 2023-04-06 09:02 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After adding the Arabic language, a sidebar is displayed in the middle of the page.

[Untitled_ Apr 6, 2023 10_40 AM.webm](https://user-images.githubusercontent.com/111756615/230323914-21cc2e97-f300-4bc0-896e-df0e2adb4df2.webm)

--

![image](https://user-images.githubusercontent.com/111756615/230325846-40748d0b-e599-4b0d-8902-a6a16ce4db04.png)

In second step : The Prestashop version becomes misplaced

![image](https://user-images.githubusercontent.com/111756615/230327383-c601f7b5-9331-4c72-9177-d3f515d3778a.png)

### Steps to reproduce

1. Go to BO> International> Localization
2. Go to Import a localization pack> Localization pack you want to import
3. Choose Algeria and click on **`Import`** button
4. Go to Your profile>Employee
5. Choose Arabic language 
:warning: **See Error :** _bad display of a sidebar_
6. Go back to Dashbord
:warning: **See Error :** _the PS version is not well displayed_

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2023-04-06 12:25
Hello @MhiriFaten ,

I can't reproduce your issue using PrestaShop 8.1.0 and PHP 8.1.

https://user-images.githubusercontent.com/16019289/230377894-f2d5cacb-b662-4071-8bc6-a050debcecde.mov

---
@PrestaShop/qa-functional can someone try to reproduce it ?
Thanks!

**Comment by djoelleuch** [comment] 2023-04-06 13:38
Hello @florine2623 ,

I was able to reproduce the issue with **develop branch** - **PHP 8.1** / **PHP 7.4**

[Untitled_ Apr 6 2023 3_33 PM.webm](https://user-images.githubusercontent.com/115152460/230394149-9e04d601-f3b5-4738-a959-3595aac878bc.webm)

Thanks.

**Comment by florine2623** [comment] 2023-04-06 14:16
I have reproduced the issue with 8.1.0 ! It is a regression !

The white block seems to be displayed only on migrated pages.

https://user-images.githubusercontent.com/16019289/230404217-1b6ea85d-415a-4021-8807-002fbba519a0.mov

<img width="1430" alt="Screenshot 2023-04-06 at 16 14 59" src="https://user-images.githubusercontent.com/16019289/230404626-df26f6ed-f550-43e1-b228-1f3fae00150f.png">

**Comment by matks** [comment] 2023-05-03 08:02
Fixed by @M0rgan01 in https://github.com/PrestaShop/PrestaShop/pull/32403

**Closed as completed** 2023-05-03 08:02 UTC
Labels: Bug, Minor, BO, International, Employees, Regression, Fixed, PR available, Verified, 8.1.x
