### ISSUE TITLE
Specific price excluding taxes (tax excl.)

### ISSUE THREAD

**Issue by MultiTech-MS** [PrestaShop/PrestaShop#14264] opened 2019-06-18 09:47 UTC
Hi,

I have a shop  in B2B mode, user groups with display prices excluding taxes mode. I still activate taxes in tax options (international> taxes) for billing.

When I create a specific price (amount) of 5 € tax excl, on the product page, I have the reduction that applies (for example on a product 100 € tax excl I have a final price of 95 € tax excl), but the discount amount displayed is 6 €  tax incl ( 5 € tax excl becomes 6 € tax incl).

Moreover in the cart page I have 

- an initial price tax incl (120 €) 
- a price discounted tax excl (95 €) 
- and this famous reduction to 6 € tax incl.

I would like this reduction to be displayed in tax excl (so 5 € tax excl) and that the cart gives me the initial price of the product also in tax excl (100 € tax excl).

Please help.

**Screenshots**
![1-prixSpécifique](https://user-images.githubusercontent.com/51752454/59667723-776a2b00-91b7-11e9-9fee-69a10fda4e28.JPG)
![2-ficheProduit](https://user-images.githubusercontent.com/51752454/59667724-7802c180-91b7-11e9-8c67-55e51f53737b.JPG)
![3-panier](https://user-images.githubusercontent.com/51752454/59667725-7802c180-91b7-11e9-9d9f-7a871c17f317.JPG)

Development on a shared webserver (linux)
PrestaShop version: 1.7.5.1
PHP version: 7.2
MYSQL v.5.6
Theme : classic

**Comment by khouloudbelguith** [comment] 2019-06-18 09:54
Hi @MultiTech-MS,

Thanks for your report.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/11103 to fix the issue.
It is fixed in the PS1.7.6.0.
Your ticket is a duplicate of #9696
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-06-18 09:55
Duplicate of #9696

**Closed as completed by khouloudbelguith** 2019-06-18 09:54 UTC
Labels: Duplicate
