### ISSUE TITLE
For extra themes is not possible to change the translations of Shop - Forms - Labels, it is possible only with classic theme

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15599] opened 2019-09-18 10:28 UTC
Hi
a my customer needs to change some translations of the labels on address form like for company field from "Azienda" to "Società ed aziende" but it is possible only for the classic theme from the translation page going to Shop - Forms - Labels
because this field is managed from the file CustomerAddressFormatter.php
return $this->translator->trans('Company', [], 'Shop.Forms.Labels');
I've checked from other sites that use different themes and they have the same problem, those translations are not possible to change from the admin page because they are not present
the labels of CustomerAddressFormatter.php are imported from the templates/customer/_partials/address-form.tpl
so the theme cannot manage them

in the second image I show you that those texts are present for classic theme, instead in the third image for extra theme those fields are not present

can you fix it giving the possibility to modify those translations also from the control panel for extra themes?

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/65140302-85c22000-da0e-11e9-9d48-14b5e4506796.png)
![2](https://user-images.githubusercontent.com/653230/65141153-58767180-da10-11e9-8f56-6f296ffa0f8c.png)
![3](https://user-images.githubusercontent.com/653230/65141154-58767180-da10-11e9-9ab4-f11efb50c462.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by Maofree** [comment] 2019-09-18 11:26
hi
We have found that if those translations are changed in the classic theme these changes will be present also in the theme bought from addons (just in the front-office not in the translation page)

**Comment by khouloudbelguith** [comment] 2019-09-18 11:30
Hi @maofree,

Is it the same issue reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/15075?

Thanks!

**Comment by Maofree** [comment] 2019-09-18 11:35
hi
I think no, because they solved that issue cleaning the cache, in this case the translations are about address fields present into CustomerAddressFormatter.php so they are not present in the themes.
these translations are only inside the translation page of classic theme, but if we edit them from there they will be visible with other themes. This because are inside that php file

so we can change that translations but from the classic theme that it is not the used theme for the front-office

try to do a test

**Comment by khouloudbelguith** [comment] 2019-09-18 14:32
@maofree,
>I think no, because they solved that issue cleaning the cache,

After updating the translations manually in the database.
For example, I tried to translate those labels => OK
![image](https://user-images.githubusercontent.com/16067358/65157700-10177d80-da29-11e9-80f6-2031757cfe2f.png)
![image](https://user-images.githubusercontent.com/16067358/65157765-28879800-da29-11e9-805d-14b1ca8ff43a.png)
I tried to search for the company field in the translation theme page but I couldn't find it as reported here: https://github.com/PrestaShop/PrestaShop/issues/15075#issue-479618833
![image](https://user-images.githubusercontent.com/16067358/65157925-697fac80-da29-11e9-9e83-aa2db3a6a716.png)
![image](https://user-images.githubusercontent.com/16067358/65157959-73091480-da29-11e9-8f0e-1b319feaaff7.png)


Thanks!

**Comment by Maofree** [comment] 2019-09-18 15:10
hi
the problems is only around the labels of those present into CustomerAddressFormatter.php like Company, first name, lasta name, vat number ...
at this moment it is possible to solve this problem translating them from the classic theme also if it is not the current theme

**Comment by khouloudbelguith** [comment] 2019-09-18 15:13
@maofree,  In fact, the whole issue is that the Translations inherited (not physically present) in a theme aren't translatable for that theme.
This issue will be fixed in this ticket: https://github.com/PrestaShop/PrestaShop/issues/15075

Thanks!

**Comment by Hlavtox** [comment] 2019-09-18 21:01
@khouloudbelguith The same problem as in my case. Duplicate.

**Comment by khouloudbelguith** [comment] 2019-09-19 08:49
Hi @maofree,

Your ticket is a duplicate of #15075
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-09-19 08:49
Duplicate of #15075

**Closed as completed by khouloudbelguith** 2019-09-19 08:49 UTC
Labels: Duplicate, Theme & logo, Translations
