### ISSUE TITLE
Cannot setup DEBUG nor profiling Mode from BO when a defines_custom.inc.php is there defined

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#37660] opened 2024-12-13 10:36 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we have a custom configuration in defines_custom.inc.php ; if we don't put the _PS_MODE_DEV_ and _PS_DEBUG_PROFILING_ constant in the file, we cannot update debug Mode from BO nor profiler

### Expected behavior

BO should works the same with or without  defines_custom.inc.php

### Steps to reproduce

- Create a defines_custom.inc.php (without constants in it)
- Go to BO
- Enable Debug mode
- You have an error message on access right

### PrestaShop version(s) where the bug happened

1.7, 8. 9

### PHP version(s) where the bug happened

all

### Your company or customer's name goes here (if applicable).

Creabilis.com

**Comment by kpodemski** [comment] 2024-12-15 15:07
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/36487

**Closed as duplicate by kpodemski** 2024-12-15 15:07 UTC
Labels: Bug, Duplicate
