### ISSUE TITLE
The proposal for duplicating phrases

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#15476] opened 2019-09-09 14:39 UTC
Hello. While translating the template I came across some duplicate phrases in the system. Tell me, does it make sense to notify you about them to make changes to the code to combine these phrases into one?

Example: Your package must be returned to us within %number% days of receiving your order.
3 times repeated.

**Comment by khouloudbelguith** [comment] 2019-09-10 10:39
Hi @TemKaSD,

I did not manage to reproduce the issue with PS1.7.6.1 & the Classic theme.
https://drive.google.com/file/d/1nCIwvD9Yvncm79uHenvGUE20bbFEx_v4/view
![image](https://user-images.githubusercontent.com/16067358/64607092-b1665a00-d3bf-11e9-9517-f6008751bc14.png)

Are you using a custom theme?

Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-10 07:46
Hi @TemKaSD,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-10 07:47 UTC
Labels: BO, Translations, No change required
