### ISSUE TITLE
attribute_ecotax : Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#25761] opened 2021-09-01 17:56 UTC
#### Describe the bug

After update from 1.7.6.4 to 1.7.7.7, with debug mode enabled, editing a product show an error : Notice: A non well formed numeric value encountered
This come from the attribute_ecotax calculation on line 152 , class PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper

`            $combinationValues['attribute_ecotax'] = Tools::ps_round(
                $combinationValues['attribute_ecotax'] / (1 + Tax::getProductEcotaxRate() / 100),
                $computingPrecision
            );
`
Dirty fix : @Tools::ps_round

#### Expected behavior

No errors

#### Steps to Reproduce

1. Go to admin products and edit a product with combinations
2. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: N/A

**Comment by rflorent** [comment] 2021-09-01 17:58
Ecotax disabled for informations.

**Comment by khouloudbelguith** [comment] 2021-09-03 10:12
Hi @rflorent,

Thanks for your report.
>After update from 1.7.6.4 to 1.7.7.7

Did you use the 1-click upgrade module?
If yes, what is the exact version did you use?

Before the upgrade, could you please provide me the exact steps to create this product?
After the upgrade, have you had the same issue with a new product created?

In my case, I did not manage to reproduce the issue with fresh install PS1.7.7.7.

Thank you!

**Comment by SebBareyre** [comment] 2021-09-08 06:33
Hi @rflorent 
Could you try this fix : https://github.com/PrestaShop/PrestaShop/pull/25807

**Comment by khouloudbelguith** [comment] 2021-09-17 16:17
Hi @SebBareyre,

Thanks for the fix :slightly_smiling_face: 
@rflorent , your ticket is a duplicate of #25797
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2021-09-17 16:17
Duplicate of #25797

**Closed as completed by khouloudbelguith** 2021-09-17 16:17 UTC
Labels: Bug, BO, Duplicate, Combinations
