### ISSUE TITLE
Order message get's HTML entity encoded and stays that way

### ISSUE THREAD

**Issue by DBBlueDeath** [PrestaShop/PrestaShop#12822] opened 2019-03-07 12:58 UTC
**Describe the bug**
Special characters are saved in their html entity encoded form and they are not decoded when viewing the message in Backoffice or from the Order object (when exporting for a shipping carrier).
For example: `Árvíztűrő tükörfúrógép` turns into `&Aacute;rv&iacute;ztűrő t&uuml;k&ouml;rf&uacute;r&oacute;g&eacute;p`

**To Reproduce**
1. Place a new order, enter anything with special characters into the message field (carrier selection tab). Example: `Árvíztűrő tükörfúrógép`
2. After placing the order, go view it in Backoffice and you'll see the now unreadable message.

**Screenshots**
Backoffice order view malformed message example:
<img width="544" alt="ps1" src="https://user-images.githubusercontent.com/3076436/53958252-d0b6be80-40e0-11e9-968b-a86abb51388a.PNG">

**Additionnal information**
PrestaShop versions tested that have the issue: 1.6 - 1.7.5 (Basically ALL)
PHP version: irrelevant

**Comment by khouloudbelguith** [comment] 2019-03-07 13:11
Hi @DBBlueDeath,

We are aware of this issue.
Your ticket is a duplicate of #9726
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-03-07 13:11
Duplicate of #9726

**Closed as completed by khouloudbelguith** 2019-03-07 13:11 UTC
Labels: Duplicate

**Comment by DBBlueDeath** [comment] 2019-03-07 13:16
Yeah okay, I did not follow it back to the old forge, the description here lost it's meaning.
Glad to hear it's finally fixed. Thanks!
