### ISSUE TITLE
Product details is not displayed

### ISSUE THREAD

**Issue by bijouxmexicains** [PrestaShop/PrestaShop#11798] opened 2018-12-18 06:34 UTC
Hi
In many products the product details are not displayed when click on this section

**To Reproduce**
https://www.bijouxmexicains.fr/boucles-d-oreilles/95-136-boucles-d-oreilles-perles.html#product-details
Details du produit

Not working

**Additionnal information**
PrestaShop version: 1.7.1.2
PHP version: N/A

**Comment by khouloudbelguith** [comment] 2018-12-18 07:52
Hi @bijouxmexicains,

Did you make any changes in the core of PrestaShop before this issue occurs?
If no, thanks to provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by bijouxmexicains** [comment] 2018-12-18 19:23
Hi Khouloud

Please find here the information I was able to find :

*Serveur :* Linux #1 SMP Thu Aug 23 15:15:40 CEST 2018 x86_64

*Version du logiciel serveur :* Apache

*Version de PHP :* 7.0.32

*Version de MySQL :* 5.6.39-log

I am adding a log file i have found in my ftp, don't know if it will help

Thank you for your support and patience



Le mar. 18 déc. 2018 à 08:52, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment] 2018-12-19 08:26
@bijouxmexicains,

Thanks for your feedback.
There is no log file attached.
You need to connect to GitHub & upload the file here.
Thanks!

**Comment by bijouxmexicains** [comment] 2018-12-19 18:34
here is my error log : 
[error log.pdf](https://github.com/PrestaShop/PrestaShop/files/2696112/error.log.pdf)

**Comment by khouloudbelguith** [comment] 2018-12-20 09:03
@bijouxmexicains, thanks for your feedback.
In your log file, you have this error
 ```
[error] [client
92.184.101.129] [host www.bijouxmexicains.fr] End of
script output before headers: ajax-upgradetab.php,
referer: https://www.bijouxmexicains.fr/admin9716/
index.php?
```
Could you please try to disable any type of caching extensions (like apc, opcache, memcache etc...)
And try to verify that there's enough RAM on your server
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-25 17:20
Hi @bijouxmexicains,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by khouloudbelguith** 2019-01-25 17:20 UTC
Labels: Bug, FO, No change required
