### ISSUE TITLE
Cart Controller and MultiStore issue when dealing with combinations

### ISSUE THREAD

**Issue by emanborg** [PrestaShop/PrestaShop#22598] opened 2020-12-26 23:04 UTC
#### Describe the bug

When a product is on multiple stores and has the same combination groups are present on id_shop 1 and id_shop 2 for example, CartController.php does not identify which id_shop its currently doing the request for and does not join the tables properly because it omits the id_shop in its queries.

#### Expected behavior

Errors such as: 
Quantitiy not available, not able to switch attributes in product page etc.

#### Steps to Reproduce

Create a product with combinations on id_shop 1 
Create the same combinations on id_shop 2
Try to add the item to the cart and you get an error message and does not allow you to add to cart on id_shop1

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3

**Comment by emanborg** [comment] 2020-12-26 23:08
Note: Deleting the combinations matching the same group from the table ps_product_attribute and ps_product_attribute_shop makes it work

**Comment by emanborg** [comment] 2020-12-27 00:14
I used the below SQL statement to delete all product attributes on other shops as a test and everything works well on id_shop 1
delete from ps_product_attribute where id_product_attribute in (select id_product_attribute from ps_product_attribute_shop where id_shop<>1);
---

Further to my findings issue may be releated also to the template not passing the correct parameters to the shopping cart controller.

**Comment by hibatallahAouadni** [comment] 2020-12-28 09:24
Hello @emanborg 

I didn't manage to reproduce your issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1mmemqG-Z8jhj3Ty6WAn9foocZlxmULdv/view

As you can see in the video, I created the same product with the same combinations in 2 shops:
Shop 1: Presta1770 => Combination quantity = 50
Shop 2: PrestaDemo => Combination quantity = 0
Then, FO>Shop1 (Presta1770), I successfully added my product with these two combination to my cart.

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment] 2021-01-17 13:09
Hello @emanborg ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-17 13:09 UTC
Labels: Bug, FO, Multistore, Combinations, No change required, Shopping carts FO, 1.7.7.0
