### ISSUE TITLE
Sorting in linklist not working

### ISSUE THREAD

**Issue by mark-app** [PrestaShop/PrestaShop#29197] opened 2022-07-29 07:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the default pages section it's posible to sort the pages in position but the functionality does not work in the linklist module.

### Expected behavior

Sorting pages. 
In the linklist output see the pages in the sorted position.

### Steps to reproduce

1. Sort your pages in the pages functionality in the PrestaShop Backoffice
2. Create a linklist block in the linklist module en add your sorted pages.
3. Checkout the linklist block in the footer in the front office.

### PrestaShop version(s) where the bug happened

1.7.8.7 - 1.7.8.6 - 1.7.7.8 - 1.7.6.5 

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_linklist

**Comment by mark-app** [comment] 2022-07-29 07:16
I have created a fix for that.

In the file ps_linklist/src/Presenter/LinkBlockPresenter.php add between line 142 and 143

`'position' => $cms->position,`

Replace line 147:

`return $cmsLinks;`

For :

`return $this->array_sort($cmsLinks, 'position', SORT_ASC);`

Add after the function makeCmsLinks on line 150 this function:

`function array_sort($array, $on, $order=SORT_ASC)
    {
        $new_array = array();
        $sortable_array = array();
        if (count($array) > 0) {
            foreach ($array as $k => $v) {
                if (is_array($v)) {
                    foreach ($v as $k2 => $v2) {
                        if ($k2 == $on) {
                            $sortable_array[$k] = $v2;
                        }
                    }
                } else {
                    $sortable_array[$k] = $v;
                }
            }
            switch ($order) {
                case SORT_ASC:
                    asort($sortable_array);
                    break;
                case SORT_DESC:
                    arsort($sortable_array);
                    break;
            }
            foreach ($sortable_array as $k => $v) {
                $new_array[$k] = $array[$k];
            }
        }
        return $new_array;
    }`


So the changes are:
<img width="1491" alt="Schermafbeelding 2022-07-29 om 09 19 30" src="https://user-images.githubusercontent.com/6554157/181704929-35566e81-4707-40fa-8421-02f019ececee.png">

**Comment by hibatallahAouadni** [comment] 2022-07-29 15:53
Hello @mark-app 

Thanks for reporting the issue and the proposed solution :rocket: 
Could you please create a Pull Request with your proposed solution :pray: 

Btw, I didn't manage to reproduce the issue, could you please check my screen record:

https://user-images.githubusercontent.com/23308427/181797323-4df6145c-49c4-4cd2-bebd-2a26ed325fd3.mp4

It seems like I'm missing something :sweat: Could you please provide a screen record :pray: 
Please check and feedback.

Thanks!

**Comment by mark-app** [comment] 2022-08-02 15:31
Hi @hibatallahAouadni, 

You missed number 3.

3. Checkout the linklist block in the footer in the front office.

**Comment by AureRita** [comment] 2022-08-03 15:32
Hi @mark-app 

Thanks for reporting the issue.  I didn't manage to reproduce the issue, could you please check my screen record:

https://user-images.githubusercontent.com/100699445/182647787-394974d1-cefe-4dee-8f86-b7628c5e1cf5.mp4

I think I do all your request ? so can you tell me if I need to do anything else to have your issue ? 

Can you give us screenshot or screen record to see your issue ? 

Waiting for your feedback

**Comment by mark-app** [comment] 2022-08-04 07:25
Hi @AureRita ,

I mean the pages themselves


https://user-images.githubusercontent.com/6554157/182789632-669852a5-2494-4b18-9349-569c48358233.mp4


.

**Comment by mark-app** [comment] 2022-08-04 07:27
<img width="1306" alt="Schermafbeelding 2022-08-04 om 09 26 01" src="https://user-images.githubusercontent.com/6554157/182788961-3cdb27b1-94f7-4c4e-94dd-cdfd0eb6e063.png">
<img width="1514" alt="Schermafbeelding 2022-08-04 om 09 26 22" src="https://user-images.githubusercontent.com/6554157/182788969-488a530a-1a47-4aed-8de9-4c2f8525e381.png">

**Comment by AureRita** [comment] 2022-08-04 13:54
Hi @mark-app 

Yes Indeed, good catch, I reproduced the issue as we can see : 

https://user-images.githubusercontent.com/100699445/182863092-988e1a2b-a2f0-4b7e-89c1-d6481da2f7ef.mp4

so the issue isn't really related to link list ? Currently I can "solve" the problem by : 
1. Go to linklist 
2. Edit Our company
3. Uncheck all the content page and Save it 
4. Edit again Our company 
5. Check all the content page and Save it 

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Thank for the proposed solution
Could you please create a Pull Request with your proposed solution 

Thank you

**Comment by AureRita** [comment] 2022-08-04 14:00
for me this issue is similar to : #16134

can you tell me if you're agree ? 

Waiting for your feedback

**Comment by mark-app** [comment] 2022-08-04 14:05
Yes the bug seems the same. Maybe you can add my solution too it?

**Comment by AureRita** [comment] 2022-08-04 14:16
Unfortunately, I've to close your issue because it's a dupplicate, 
For your solution, could [you please create a Pull Request with your proposed solution](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/)

**Comment by AureRita** [comment] 2022-08-04 14:17
Duplicate of #16134

**Closed as completed by AureRita** 2022-08-04 14:17 UTC
Labels: Bug, BO, Duplicate, Pages, 1.7.6.5, Linklist, Invalid, Module
