### ISSUE TITLE
redirect http to https

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#17358] opened 2020-01-25 22:45 UTC
hello, i notice on openspeed prestashop is not redirecting to https when ssl and https forced,

so i had to apply a rule like 👍 
rewriteCond %{HTTPS} !on
rewriteCond %{HTTP:X-Forwarded-Proto} !https
rewriteRule ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]

can you recheck

**Comment by khouloudbelguith** [comment] 2020-01-27 08:39
Hi @demeldoo,

Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/12253? or this https://github.com/PrestaShop/PrestaShop/issues/17095?

Thanks to check & feedback.

**Comment by demeldoo** [comment] 2020-01-27 09:05
hi, no

i have enabled fully https, and works pretty fine, but when you visit http, then you get a 500 error... so i have made a forward with the rules i sent...

**Comment by khouloudbelguith** [comment] 2020-01-27 11:19
@demeldoo,

>but when you visit http

Do you visit it from the history browser or a search from google or from the Back office of PrestaShop?

Thanks!

**Comment by demeldoo** [comment] 2020-01-27 11:27
i used a browser, also incognito mode, to call http, www and non-www, but also got some error reports when i used some tools to test website like nibbler or pingdom,


this is on openspeed server, litespeed

**Comment by khouloudbelguith** [comment] 2020-01-27 12:11
@demeldoo, I did not manage to reproduce the issue with PS1.7.6.3.
There is always a redirection from `http` to `https` automatically.

I attached a screen record
https://drive.google.com/file/d/10VV6_ezp-4s9qczbri2WOURTmRPCnjZ_/view
In the BO => Shop Parameters => SEO & URLs page => I have this configuration
![image](https://user-images.githubusercontent.com/16067358/73173790-75c9f380-4106-11ea-9667-06ccc782845d.png)

Thanks to check & feedback.

**Comment by florine2623** [comment] 2020-02-26 09:39
Hello @demeldoo 
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Closed as completed by florine2623** 2020-02-26 09:39 UTC
Labels: BO, General, SEO & URLs, No change required
