### ISSUE TITLE
Mail notifications - Order confirmation

### ISSUE THREAD

**Issue by Klixa-Web** [PrestaShop/PrestaShop#10174] opened 2018-08-29 07:05 UTC
Hi
How to set mail notification in PS 1.7.4.2? The shopholder want's to get a copy of the mail order confirmation like he always got in PS 1.4.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-08-29 07:27
Hi @Klixa-Web,

First, you need to navigate to the BO => CONFIGURE => Advanced Parameters => E-mail to configure PrestaShop to send emails to your customers. We strongly advise you that you consult your web host to determine which settings to use for this feature.
Also, you can install  [the mail alert module](https://github.com/PrestaShop/mailalerts) to send e-mail notifications to customers and merchants.
Thanks to check & feedback.

Best regards, Khouloud

**Comment by Klixa-Web** [comment] 2018-08-29 07:36
Hi Khouloud
Thank you for your fast reply. Modul installation by BO fails. What should I do?
Best regards, Sandra

**Comment by Klixa-Web** [comment] 2018-08-29 07:38
P.S. Shop has Wallee Modul integrated. Theme: Warehouse 1.4.9

**Comment by khouloudbelguith** [comment] 2018-08-29 08:42
Hi @Klixa-Web,

Here's the zip folder's module that I cloned: 
[mailalerts.zip](https://github.com/PrestaShop/PrestaShop/files/2331412/mailalerts.zip)
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Klixa-Web** [comment] 2018-08-29 09:04
Thank you, I could install it. But when I go back to Frontpage I get HTTP ERROR 500.

**Comment by khouloudbelguith** [comment] 2018-08-29 09:09
Hi @Klixa-Web,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
 http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Klixa-Web** [comment] 2018-08-30 12:01
Hi Khouloud

Mail notification problem is solved. **But I have big problems with BO above all with editing categories. Please help me!** Here are the Details:

Host: ftp.klixa.ch

**Serverdaten** Linux #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 
**Version der Server-Software** Apache/2.4.18 (Ubuntu) 
**PHP-Version** 7.0.30-0ubuntu0.16.04.1 
**Speichergrenze** 1024M 
**max_execution_time:** 3000 
**Upload (max. Dateigröße)** 512M 
**PrestaShop-Version 1.7.4.2** 
**Shop-URL** **https://www.geburtstagskarte.ch/** 
**Template:** warehousechild 

**MySQL-Version** 5.7.23-0ubuntu0.16.04.1 
**MySQL-Server** localhost 
**MySQL-Name** 3350BH_www_geburtstagskarte_ch 
**MySQL-Anwender** 3350BH_www_geb 
**Tabellen-Präfix:** ps_ 
**MySQL-Engine** InnoDB 
**MySQL-Treiber** DbPDO 

I get error from backoffice.js in the console while saving changes made to a category.

**Comment by khouloudbelguith** [comment] 2018-08-30 12:16
Hi @Klixa-Web,

Since this issue is fixed, I will close the issue.
For the second problem, you need to create another issue because they are two different problems.
Thanks for your understanding.
I close the ticket, feel free to open a new one when needed.

Best regards, Khouloud

**Closed as completed by khouloudbelguith** 2018-08-30 12:16 UTC
Labels: Advanced parameters, Email, No change required, 1.7.4.2

**Comment by storygram** [comment] 2019-12-04 10:55
HI,

I have the same problem on prestashop 1.7, the client does not receive confirmation email after placing orders

info_outline Informatii despre configuratie
Aceste informatii trebuie furnizate daca vei raporta vreo problema in modulul nostru de erori sau pe forum.

info_outline Informatii despre server
Informatii despre server Linux #1 SMP Thu Jun 20 11:00:35 EDT 2019 x86_64

Versiunea de software a serverului: LiteSpeed

Versiunea de PHP: 7.2.24

Limita de memorie: 512M

Timpul maxim de executie: 300

Limita maxima la incarcare de fisier: 256M

info_outline Informatii despre baza de date
Versiunea de MySQL: 10.2.27-MariaDB-cll-lve

Server MySQL: localhost

Baza de date MySQL: r67409ambi_pr144

Utilizator MySQL: r67409ambi_pr144

Prefix tabele: ps3o_

Motor MySQL: InnoDB

Driver MySQL: DbPDO

info_outline Informatiile magazinului
Versiunea de Prestashop: 1.7.6.2

URL magazin: http://www.ambientdecor.ro/

Calea magazinului: /home2/r67409ambi/public_html

Tema folosita acum: interior_th

info_outline Configurare e-mail
Metoda de e-mail: Folosesti functia PHP mail().

info_outline Informatiile tele
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

info_outline Verifica-ti configurarea
Parametri obligatorii: Da

Parametri optionali: Da

**Comment by khouloudbelguith** [comment] 2019-12-04 11:33
Hi @storygram,

Issue created here: https://github.com/PrestaShop/PrestaShop/issues/16676

Thanks!
