### ISSUE TITLE
Payment callback error due to locale doesn't validate the order in backoffice

### ISSUE THREAD

**Issue by mamoot64** [PrestaShop/PrestaShop#19743] opened 2020-06-15 06:58 UTC
#### Describe the bug

After a successful payment with Paypal or Stripe (in my case), order isn't confirmed in the backoffice.

#### Expected behavior

Oder must be confirmed and mails automatically sent.

#### Details

Paypal write in this log:
```
Order validation error : The locale 2 is invalid; File: /APP_ROOT/classes/Language.php; Line: 810;
```
The getIsoByLocale($locale) method of Language class try to "Validate" the $locale provided.

An exception is thrown because validation failed :
```
        if (!Validate::isLanguageCode($locale)) {
            throw new Exception('The locale ' . $locale . ' is invalid');
        }
```
isLanguageCode try to validate a string like "fr-FR", not an int.

So, order can't be confirmed in the back office.

I don't know if it's the cause or the consequence and if the problem is about Prestashop or payment modules.

#### Additional information

* PrestaShop version:  1.7.6.5
* Paypal: 5.1.3

**Comment by mamoot64** [comment] 2020-06-15 11:34
Seems to be a change of Prestashop API ?
I also have the error on delivery :
```
[14-Jun-2020 23:38:41 UTC] PHP Fatal error:  Uncaught Exception: The locale 2 is invalid in /ROOT_APP/classes/Language.php:810
Stack trace:
#0 /ROOT_APP/classes/Translate.php(193): LanguageCore::getIsoByLocale(2)
#1 /ROOT_APP/module/Module.php(1975): TranslateCore::getModuleTranslation(Object(MondialRelay), 'New order', 'mondialrelay', NULL, false, 2)
#2 /ROOT_APP/modules/mondialrelay/mondialrelay.php(436): ModuleCore->l('New order', false, 2)
#3 /ROOT_APP/classes/Hook.php(970): MondialRelay->hookNewOrder(Array)
#4 /ROOT_APP/modules/ets_superspeed/classes/ext/ets_hook(509): HookCore::coreCallHook(Object(MondialRelay), 'hooknewOrder', Array)
#5 /ROOT_APP/classes/Language.php on line 810
```

**Comment by sarahdib** [comment] 2020-06-16 16:09
@PrestaShop/prestashop-core-developers could you check this ?

**Comment by mamoot64** [comment] 2020-08-11 09:48
any update on this ?

**Comment by mamoot64** [comment] 2020-10-05 09:51
Problem is still here.

Prestashop: 1.7.6.8
Stripe: 2.2.0
Paypal: 5.2.0

Order confirmation is fully broken. Customer don't receive emails and order status isn't confirmed.

**Comment by hibatallahAouadni** [comment] 2021-02-19 08:06
Hello @mamoot64 

Did you check with your payment module developer if the issue is not in the module side?
Please check and feedback.

Ping @PrestaShop/prestashop-core-developers I think this issue is not related to PS Core but to the payment module, could someone please confirm it?

Thanks in advance!

**Comment by PierreRambaud** [comment] 2021-02-22 16:30
As far as I know, the problem comes from the module itself which is not using a string for the locale :thinking:

**Comment by hibatallahAouadni** [comment] 2021-03-14 21:51
Hello @mamoot64 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-03-14 21:51 UTC
Labels: Bug, BO, Order, Payment methods, No change required, 1.7.6.5, 1.7.6.8
