### ISSUE TITLE
Combinations not displayed in BO

### ISSUE THREAD

**Issue by shirokoweb** [PrestaShop/PrestaShop#12062] opened 2019-01-08 11:23 UTC
**Describe the bug**
We had an issue with variable products in 1.7.4.4, when selecting an attribute on FO, an error was thrown :
```
Errors occurred:
Property AttributeGroup->position is not valid
Property Attribute->id_attribute_group is empty.
```
We tried fixes and patches suggested on #9390 but no luck.
Upgraded to 1.7.5 as it was supposed to solve the known bug.
1.7.5 solved the FO issue (**but made combinations selection very slow**), now the issue is on BO : combinations do not show.

**To Reproduce**

1. Add a product
2. Set product as variable
3. Go to combinations tab and generate some combinations
4. Combinations generated but not showing

**Screenshots**
Combinations not displayed in BO (althought says there is 17):

![image](https://user-images.githubusercontent.com/6638982/50827157-ff612480-133d-11e9-9825-7cfa72b2fd44.png)

Cleared caches ? YES

**Additionnal information**
PrestaShop version: 1.7.5.0
Site language : French FR_fr (only language installed / used)
Currency : EUR (only currency installed / used)

** Server info**
Informations sur votre serveur Linux #1 SMP Thu Jan 4 14:26:00 EST 2018 x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.0.33
Limite de mémoire : 512M
Temps maximal d'exécution : 360
Taille max. pour envoi de fichiers : 512M

**DB info**
Version de MySQL : 10.0.37-MariaDB
Serveur MySQL : localhost
Préfixe des tables : psbl_
Moteur MySQL : InnoDB
Connecteur MySQL : DbPDO

**Comment by khouloudbelguith** [comment] 2019-01-08 11:40
Hi @shirokoweb,

Could you please run those requests SQL on your Database & feedback.

ALTER TABLE `PREFIX_supply_order_receipt_history` CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '';

ALTER TABLE `PREFIX_supply_order_receipt_history` CHANGE `employee_lastname` `employee_lastname` VARCHAR(255) DEFAULT '';

ALTER TABLE `PREFIX_order_detail` CHANGE `product_supplier_reference` product_supplier_reference varchar(64) DEFAULT NULL;
![image](https://user-images.githubusercontent.com/16067358/50828388-8e237080-1341-11e9-940a-eac03ad7c9fb.png)

ALTER TABLE `PREFIX_product_attribute` CHANGE product_supplier_reference product_supplier_reference varchar(64) DEFAULT NULL;

ALTER TABLE `PREFIX_product` CHANGE `reference` `reference` varchar(64) DEFAULT NULL;

ALTER TABLE `PREFIX_product_lang` CHANGE `meta_description` `meta_description` varchar(512) DEFAULT NULL, CHANGE `meta_keywords` `meta_keywords` varchar(255) DEFAULT NULL;

PS: **PREFIX** is the prefix of your tables, t could be for example ps.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-01-08 11:44
@shirokoweb, you can change those types manually in your database "Structure" tab.
![image](https://user-images.githubusercontent.com/16067358/50828925-17877280-1343-11e9-8aa3-d86294e92abb.png)

**Comment by khouloudbelguith** [comment] 2019-01-08 11:45
Duplicate of #11825

**Closed as completed by khouloudbelguith** 2019-01-08 11:45 UTC
Labels: Duplicate
