### ISSUE TITLE
Discount field is calculated greater than the voucher field shows

### ISSUE THREAD

**Issue by kodarco** [PrestaShop/PrestaShop#15061] opened 2019-08-09 16:20 UTC
On the order confirmation email and in BO discount field shows $5.20 and voucher field shows $3.20. One of the item is on sale and voucher is set to exclude discounted products, so voucher field show the correct amount but, below the discount field shows the incorrect amount as if the voucher is also applied to the product on sale.
![s1](https://user-images.githubusercontent.com/43558067/62793155-27318a00-bad1-11e9-8154-385effd5b218.JPG)
![s2](https://user-images.githubusercontent.com/43558067/62793160-2a2c7a80-bad1-11e9-9c84-f4cbb8911262.JPG)

This is on PS 1.7.5.0
Payment module is standard Payment by check by Prestashop V2.0.4

 Product that shouldn't have a discount is marked "On Sale" and has a special pricing 37% off.
![s4](https://user-images.githubusercontent.com/43558067/62793640-51377c00-bad2-11e9-983f-16176baa8296.JPG)

Discount is set like this:
![s5](https://user-images.githubusercontent.com/43558067/62793663-601e2e80-bad2-11e9-8c7a-4485028bdff5.JPG)

Other info as follows:
![s3](https://user-images.githubusercontent.com/43558067/62793299-8b544e00-bad1-11e9-8c8c-c7177f7aa36e.JPG)

**Comment by mariem-abid** [comment] 2019-08-13 13:54
Hi @kodarco,

I did not manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record and a screenshot.
https://drive.google.com/file/d/1UMVUCDsZB1x_LZgvZq3W5zI2Z1k_tjUz/view
![13-08-19](https://user-images.githubusercontent.com/36841537/62947320-3a4a9f80-bdda-11e9-93c2-114367f94add.png)

Thanks for check and feedback.

**Comment by kodarco** [comment] 2019-08-14 15:30
I did the upgrade to 1.7.6.0 but it didn't work. It works if you have only one discounted item in the cart, it doesn't let you apply the discount, but when you add a second item that isn't discounted, it applies the discount to both items. Please try it in your store.

Watch the video: https://drive.google.com/file/d/1fZvGLONqPGpanUm3WuVy13mvF3xjUgMc/view?usp=sharing

![screen1](https://user-images.githubusercontent.com/43558067/63033821-8b30c580-beb8-11e9-8975-8f6eb7c09439.JPG)

**Comment by mariem-abid** [comment] 2019-08-16 10:36
Hi @kodarco,

I manage to reproduce the issue with the last version PS 1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1AAmOVyZdkh5_QDx3i5kE0_lzEkCg1j_4/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment] 2019-08-16 11:46
@mariem-abid 

Could you try to reproduce it with 1.7.5.2 ?

**Comment by mariem-abid** [comment] 2019-08-16 12:08
@marionf, yes, the same issue

**Comment by marionf** [comment] 2019-08-16 12:46
Hello @kodarco 

Your issue is a duplicate of #10300 so I close it.
Please follow issue #10300

Regards

**Comment by kodarco** [comment] 2019-08-16 15:00
No, tried the fix mention at #10300  for  src/Core/Cart/CartRuleCalculator.php
It didn't fix it.

**Comment by marionf** [comment] 2019-08-16 15:42
The fix will be available in 1.7.7 version

**Closed as completed** 2019-10-25 09:10 UTC
Labels: Bug, Major, BO, Duplicate, Discounts, 1.7.5.2, 1.7.6.0
