### ISSUE TITLE
Default supplier prevents unit pricing from being assigned.

### ISSUE THREAD

**Issue by SlashedAsteroid** [PrestaShop/PrestaShop#15724] opened 2019-09-27 08:41 UTC
**Describe the bug**
During product configuration if a default supplier has been selected (radio buttons on product options) the item is no longer available for search and unit pricing can not be set leading to no pricing information on the product page.

It does appear to trigger two SQL statements when doing this, one assigning the unit_price_ratio to the required value, immediately followed by a 2nd statement that sets it back to 0.

**Steps to reproduce the behaviour: **

1. Go to edit/create a product.
2. Select supplier and assign default using radio buttons.
3. Go to 'Pricing tab'/'step-2' enter a unit price.
4. Save.
5. Refresh/Re-enter product configuration.
6. Unit pricing has visible been reset to 0.

**Steps to work around the behaviour:**

1) Set a invalid/non-required supplier as default supplier.
2) Remove supplier from list leaving no "default supplier" radio button selected.
3) You will now be able to enter Unit Pricing.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.22

**Comment by SlashedAsteroid** [comment] 2019-09-27 09:00
![2019-09-27_09-28-49](https://user-images.githubusercontent.com/12980961/65756726-8ee97600-e10d-11e9-9c15-786044a46f57.png)
![2019-09-27_09-29-33](https://user-images.githubusercontent.com/12980961/65756734-93159380-e10d-11e9-9348-991ab30713f4.png)
![2019-09-27_09-29-36](https://user-images.githubusercontent.com/12980961/65756739-9741b100-e10d-11e9-81bb-ed4ecbd68e70.png)

**Comment by SlashedAsteroid** [comment] 2019-09-27 15:13
After some testing the issue seems to occur when the following controller method is invoked.

Controller: controllers/admin/AdminProductController.php
Method: processSuppliers

From Line: 2542

The product wholesale_price is updated and unit_price_ratio is reset to 0 when $product->update() is called.

**Comment by khouloudbelguith** [comment] 2019-09-30 09:47
Hi @SlashedAsteroid,

Thanks for your report.
In your case during this step "Go to 'Pricing tab'/'step-2' enter a unit price." did you enter the unity?
![image](https://user-images.githubusercontent.com/16067358/65868178-b8094100-e36f-11e9-8376-b5a97a6371c5.png)

Related to https://github.com/PrestaShop/PrestaShop/issues/10792

**Comment by SlashedAsteroid** [comment] 2019-09-30 10:05
Hi @khouloudbelguith,

Yes, the unity field was complete and saving correctly. 
I did attempt this with that field both empty and complete to the same result.

**Comment by khouloudbelguith** [comment] 2019-09-30 13:15
@SlashedAsteroid, I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1296grjYsCLvKahY8574XGt_chiuaK3Ms/view
Thanks to check & feedback.

**Comment by SlashedAsteroid** [comment] 2019-10-01 08:22
May I ask what environment you were running on? I've reproduced this behaviour twice with a clean install from git using the docker compose provided and once on a live site hosted on Apache 2.4 with MariaDB 10.2 & PHP 7.2.22.

**Comment by khouloudbelguith** [comment] 2019-10-01 09:45
@SlashedAsteroid, In my case also, I'm using an environment with docker.
Here's my Server configuration:
![image](https://user-images.githubusercontent.com/16067358/65951726-8f994980-e438-11e9-876b-cfdc8fe9beee.png)

Thanks!

**Comment by SlashedAsteroid** [comment] 2019-10-01 09:54
@khouloudbelguith Thanks for sending that, I'll make sure my environment is comparable and try again.

Thanks for looking into it.

**Comment by khouloudbelguith** [comment] 2019-10-01 16:40
@SlashedAsteroid, Thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment] 2019-10-31 07:37
Hi @SlashedAsteroid,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-31 07:37 UTC
Labels: BO, Suppliers, Taxes and Prices, No change required, 1.7.6.1

**Comment by nicoladze** [comment] 2019-11-18 12:52
@khouloudbelguith 

There is a another error than the one stipulated here.

The purchasing price on "Price" part is also set to the supplier price fulfilled in "Options" part when a default supplier is selected.
