### ISSUE TITLE
[BUG] Country name  translation

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#26008] opened 2021-09-27 12:13 UTC
#### Describe the bug

Since the latest versions of PrestaShop, the country names are in english, even if you install the store in another language

#### Expected behavior

The names of the countries must be translated into the languages ​​concerned

#### Steps to Reproduce

1. Install PS 1.7.7.7 (in FR)
2. Go to `BO > International >  Zones > Countries`
3. Edit a country (Ex.: ID 43 )

**Screenshots**

![image](https://user-images.githubusercontent.com/16455155/134905380-d35169f4-f036-4c41-a7ec-a10e111b8f70.png)

#### Additional information

* PrestaShop version: >= 1.7.7.x
* PHP version: N/A

**Comment by hibatallahAouadni** [comment] 2021-09-27 16:17
Hello @PululuK 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12168. 
This issue has been fixed with PS1780_rc1, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/134946684-8046e278-9aea-4bf8-9b0f-0901eb745cfc.png)

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-09-27 16:17
Duplicate of #12168

**Closed as completed by hibatallahAouadni** 2021-09-27 16:17 UTC
Labels: Duplicate

**Comment by PululuK** [comment] 2021-09-28 07:52
Thank you @hibatallahAouadni !

**Comment by alema9** [comment] 2021-09-29 07:00
Great work
