### ISSUE TITLE
Translates are not working for 1.7.6

### ISSUE THREAD

**Issue by WooXu** [PrestaShop/PrestaShop#16002] opened 2019-10-17 11:14 UTC
When i translate strings for my teheme or modules, it saves it but it does not show on front end. I have tryed everything basicly, tryed several themes both the standard theme for prestashop and other themes. My main theme im running is tv_electronic_electron_1_7_v1, it should be compatible with the prestashop version and i take the basic theme following prestashop should aswell..

I do see the translation strings in database, but also i see some strange appearing in my backend under translate (theme) option. theres a da-D option for me to select but it turns out to an error if i select it for translate. (translate error no file for translate) see screenshot attached.

![translating error](https://user-images.githubusercontent.com/51786330/67004043-ae0d6f00-f0df-11e9-89a2-773bf4a05cc0.png)

**Comment by khouloudbelguith** [comment] 2019-10-17 11:29
Hi @WooXu,

What is the exact version PS1.7.6 did you use? PS1.7.6.1 or PS1.7.6.0?

Thanks!

**Comment by WooXu** [comment] 2019-10-17 11:34
its 1.7.6.1

**Comment by WooXu** [comment] 2019-10-17 12:00
Also its not just the frontend btw. the backend translation doesnt work eather

**Comment by khouloudbelguith** [comment] 2019-10-17 12:55
@WooXu, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by WooXu** [comment] 2019-10-17 17:33
Hi again

Well basicly i would love to, i think theres some permission issues with the symfony framework tho.

**Comment by WooXu** [comment] 2019-10-17 17:37
Heres after activating debug mode

[debug report.txt](https://github.com/PrestaShop/PrestaShop/files/3740597/debug.report.txt)

**Comment by khouloudbelguith** [comment] 2019-10-18 08:28
@WooXu, thanks for your feedback.
>Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php72) failed: Permission denied (13)

Yes, you have a permission issue on your server.
You need to check this issue with your host & feedback.

Thanks!

**Comment by WooXu** [comment] 2019-10-20 12:41
Hi there, the permissions was not the issue, i think both the default admin theme and the front end theme i found was not properly coded for the new translations. it used  mod='modname' for translation. i crated new strings in the modules with custom domain d='something'  and translated thoose strings and it works.   Tho i still cant seems to get the admin theme to translate 1 string properly (in admin area under attributes and features grps)  the attribute and feature uses the same translation (features one).

**Comment by khouloudbelguith** [comment] 2019-10-21 09:51
Hi @WooXu,

I did not manage to reproduce the issue with PS1.7.6.1.
I used three different themes & they are all ok.
I attached a screen record
https://drive.google.com/file/d/1Hb2D6zOH7TmUY9-xPstUPETrHYioBE3_/view
We have some issues with translations, you can follow this link: https://github.com/PrestaShop/PrestaShop/issues/13863 for more details.

Thanks to check & feedback.

**Comment by procent85** [comment] 2019-10-30 18:21
Hello @khouloudbelguith  

I have the same problem as @WooXu but I'm using Warehouse 4.3.2 theme.
I'm using PS 1.7.6.1 with PHP 7.2.22 and translations do not work. I.e. official psgdpr module.
I'm translated it to Polish but in Front Office I see only English.

BO looks like:
![BO](https://user-images.githubusercontent.com/57193052/67886577-fbf78d80-fb49-11e9-9836-f53dbeb3da5e.PNG)

FO looks like:
![FO](https://user-images.githubusercontent.com/57193052/67886585-fe59e780-fb49-11e9-8585-803e5e4e03f1.PNG)

server setup and configuration: Linux #2 SMP Sun Mar 17 20:00:31 CET 2019 x86_64
debug mode report: no errors

**Comment by khouloudbelguith** [comment] 2019-10-31 09:15
Hi @procent85,

I did not manage to reproduce the issue with PS1.7.6.1 & a new theme minimal.
![image](https://user-images.githubusercontent.com/16067358/67934101-74506400-fbc7-11e9-956d-b1048cb1c2cb.png)

I attached a screen record
https://drive.google.com/file/d/1kkWMxO51Ty28V-Guvh6GvzfXAtH7oxoe/view
This issue is fixed in the PS1.7.6.1 with this PR: https://github.com/PrestaShop/PrestaShop/pull/15139 as reported here: https://github.com/PrestaShop/PrestaShop/issues/15133
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-12-02 08:01
Hi @WooXu,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-12-02 08:01 UTC
Labels: Bug, Translations, No change required
