### ISSUE TITLE
psgdpr1: Unable to install module "psgdpr", Tab-> name property is 70 characters long. Must be between 0 and 64 char.

### ISSUE THREAD

**Issue by fest73** [PrestaShop/PrestaShop#23322] opened 2020-08-26 14:18 UTC
psgdpr1: Unable to install module "psgdpr", Tab-> name property is 70 characters long. Must be between 0 and 64 char.

**Comment by hibatallahAouadni** [comment] 2021-02-26 19:59
Hello @dariusakafest 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20519. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: Thanks @evgenij-sobolev :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment] 2021-02-26 20:00
Duplicate of #20519

**Closed as completed by hibatallahAouadni** 2021-02-26 19:59 UTC
Labels: Duplicate, GDPR
