### ISSUE TITLE
Updating available quantities of a product - method PATCH

### ISSUE THREAD

**Issue by dreyes-dev** [PrestaShop/PrestaShop#37109] opened 2024-10-08 17:34 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello.
I am trying to update the available quantities of a product using the stock_available operation through the API using the PATCH method, but it is automatically redirected to another method and the query is executed with the GET method.

Fragment of the documentation used:
You can update the available quantities by sending a PATCH request to /api/stock_availables/{{id}} (with {{id}} the previously retrieved stock_available entity id).
In this example, the returned stock_available entity id was: 67.
`<?xml version="1.0" encoding="UTF-8"?>`
`<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">`
`    <stock_available>`
`        <id><![CDATA[67]]></id>`
`        <quantity><![CDATA[10]]></quantity>`
`    </stock_available>`
`</prestashop>`

Postman query:
http://*****.com/prestashop/api/stock_availables/67
`<?xml version="1.0" encoding="UTF-8"?>`
`<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">`
 `   <stock_available>`
 `       <id><![CDATA[67]]></id>`
`        <quantity><![CDATA[10]]></quantity>`
`    </stock_available>`
`</prestashop>`

Thanks in advance. (editado)

### Expected behavior

El resultado esperado era una respuesta exitosa evidenciando la correcta actualización de la cantidad disponible del producto

### Steps to reproduce

Steps.

1. Two products are created, 1 simple and the other with combinations..
![paso 1](https://github.com/user-attachments/assets/1571a10c-6da5-4fde-b114-160fc61fd29f)

2.  The update of available quantities is executed with the PATCH method.
![paso 2](https://github.com/user-attachments/assets/bfd736b9-afc7-494e-9aa0-abb6f0dce2d1)

In the response.
It is evident that at the time of executing the PATCH method, it is automatically redirected to a GET query.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment] 2024-10-21 14:49
Hello @dreyes-dev ,

I can't reproduce your issue on PS 8.2.x.

When I send a PATCH query, in the console only the PATCH query is launched when I change the quantity in stock_available. 

https://github.com/user-attachments/assets/1a8668a0-09e2-4939-ab60-51c030e1cb5f

I'm closing your issue as it cannot be reproduced.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Closed as completed by florine2623** 2024-10-21 14:49 UTC
Labels: Bug
