### ISSUE TITLE
Webservice customer api dont check if account with email already exist

### ISSUE THREAD

**Issue by Mch0** [PrestaShop/PrestaShop#14946] opened 2019-08-01 08:00 UTC
**Describe the bug**
When you want push a customer with Prestashop API, there is no check on data we send for checking if account already exist, so we can create multiple accounts with the same email.
Or when you want create an account by Frontoffice there is a check on the email field to find out if it already exist .

**To Reproduce**
Send several times via api call the same data (email)

**Additional information**
PrestaShop version: 1.7.4
PHP version: 7.2

**Solution**
Make a check on email field, to find out existing account, if exist just update it, if not exist create it

**Comment by khouloudbelguith** [comment] 2019-08-01 08:36
Hi @Mch0,

We are aware of this issue, it is added to our bg roadmap.
Your ticket is a duplicate of #12844
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-08-01 08:36
Duplicate of #12844

**Closed as completed by khouloudbelguith** 2019-08-01 08:36 UTC
Labels: Duplicate
