### ISSUE TITLE
Missing translation in french for template compilation

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#17308] opened 2020-01-22 16:44 UTC
**Describe the bug**
It missing some translations in French.

**To Reproduce**

1. Install last Prestashop (1.7.6.3) in french
2. Go to "International" > "Traductions" and update french language
3. Clear cache
4. Go to "Paramètres avancés" > "Performances" and see "Compilation des templates" values not translated.

Symfony profiler says missing this translations (screenshot below).

So I checked on [Crowdin](https://crowdin.com/translate/prestashop-official/33262/en-fr) and the right translation exists in file Admin > Advparameters >Feature.xlf.

So I checked `app/Resources/translations/fr-FR/AdminAdvparametersFeature.fr-FR.xlf` file and the translation isn't here. Why ?

**Screenshots**

![Missing-translation-FR](https://user-images.githubusercontent.com/7419525/72914205-a1cc2a00-3d3e-11ea-91b3-da21612c2e3c.png)

![Symfony-profiler](https://user-images.githubusercontent.com/7419525/72914206-a1cc2a00-3d3e-11ea-8ecc-1d24588cbc86.png)

![Crowdin](https://user-images.githubusercontent.com/7419525/72914173-97119500-3d3e-11ea-900e-77da16646bfa.png)

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment] 2020-01-22 16:52
Hi @Klemart3D,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.6.2 & PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/72915006-e0aeaf80-3d3f-11ea-8164-a6fd3acfac01.png)
I’ll add this to the debug roadmap so that it’s fixed.
Ping @LouiseBonnard, it could be fixed in the Crowdin?

Thanks!

**Comment by LouiseBonnard** [comment] 2020-01-22 17:02
Hi @khouloudbelguith, @Klemart3D, I've just checked and it looks like the string disappeared from the translation catalog after version 1.7.2. It is only included in the 1.7.2 catalog, cf. the following screenshot, while it should also appear in all later translation branches.  It is a bug, ping @PrestaShop/prestashop-core-developers.

<img width="598" alt="Capture d’écran 2020-01-22 à 17 56 53" src="https://user-images.githubusercontent.com/32565890/72915774-1c964480-3d41-11ea-8077-9b511e385391.png">

**Comment by eternoendless** [comment] 2020-02-14 13:28
Visibly the wording wasn't detected by TranslationToolsBundle when the catalogue was last extracted. It should be fixed by this commit (which has been cherry-picked in 1.7.7x): https://github.com/PrestaShop/PrestaShop/commit/93dc224abd69b0e7310d7d5c78bba60cf3b22cc6

For more info: https://devdocs.prestashop.com/1.7/development/internationalization/translation/translation-tips/#form-choicetypes

The wording should make its way to the catalogue once its extracted for 1.7.7.0.

**Comment by matthieu-rolland** [comment] 2020-02-14 13:53
edit: nothing to add :)

**Comment by colinegin** [comment] 2020-02-14 16:49
Alright so if I understood clearly, it should be fixed in 177 ?

**Comment by matthieu-rolland** [comment] 2020-02-14 16:51
@colinegin yes

**Comment by eternoendless** [comment] 2020-02-20 15:41
Wordings have been extracted successfully

Fixed by #17763 (see https://github.com/PrestaShop/PrestaShop/pull/17763/files#diff-6b8ed13d2d0db06f5c207633065e8f48R1178)

**Closed as completed** 2020-03-02 09:37 UTC
Labels: Bug, Minor, BO, Translations, Performance, Fixed, 1.7.5.2, 1.7.6.2, 1.7.6.3
