### ISSUE TITLE
Orders with products with different carriers give strange shipping

### ISSUE THREAD

**Issue by PaccoRobin** [PrestaShop/PrestaShop#35435] opened 2024-02-21 09:10 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have 2 products:

1. "Dorade heel" with carriers "Delivery NL" and "Delivery local"
2. "Doradefilet" with carrier "Delivery BE"

You would expect that no carrier is available as both products have complete different carriers and there is no overlap. Instead you get strange carrier(s).

![shipping](https://github.com/PrestaShop/PrestaShop/assets/30149569/cae5dbfe-3372-46d6-b8c4-99720779977c)

### Expected behavior

You would expect that no carrier is available as both products have complete different carriers and there is no overlap.

### Steps to reproduce

1. Go to products and select different carriers for 2 products.
2. Order both products.
3. Go to checkout.
4. See result on shipping page.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1.27

**Comment by paulnoelcholot** [comment] 2024-02-21 13:35
Hello @PaccoRobin,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9998
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment] 2024-02-21 13:35
Duplicate of #9998

**Closed as completed by paulnoelcholot** 2024-02-21 13:35 UTC
Labels: Bug, FO, Duplicate, Checkout, 8.1.x

**Comment by PaccoRobin** [comment] 2024-02-21 13:38
Thank you! I will subscribe.
