### ISSUE TITLE
Regenerate thumbnails does not finish operation then the server show error 500

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#21915] opened 2020-11-13 17:59 UTC
#### Describe the bug

Dear staff, we have tried to regeneration thumbnails but the operation does not end.
We contacted our dedicated server support, they set all the necessary parameters for the script to work. But it wasn't enough.
they set up the max_execution_time value (also in fastcgi) of 900 seconds (15 minutes), but the process is already terminated at 7 -8 minutes, after an always equal number of images processed.
In testing they also tried to disable nginx and leave only apache, but with the same result.
We have thousands of images over the course of 3 years of production.
The server support ask to us how to get the debug about this process to understand which other parameters need to be modified on the server. 

#### Steps to Reproduce

1. Go to Design and then to Image settings
2. Click on Select an image
3. Scroll down to Product
4. Click Select a format
5. Scroll down on cart_default
6. Erase previous images (yer or not) we tried both
7. Click on the Regenerate thumbnails button

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34

![Schermata-2020-11-13-alle-18 54 53](https://user-images.githubusercontent.com/28685316/99104894-e680c480-25e1-11eb-9d19-241b33e3f641.png)
<img width="1578" alt="Schermata 2020-11-08 alle 23 32 27" src="https://user-images.githubusercontent.com/28685316/99104998-0dd79180-25e2-11eb-974d-fd5b64fc4620.png">

Thanks for any reply.
Balla

**Comment by hibatallahAouadni** [comment] 2020-11-16 07:53
Hello @ballashop 

I didnt' manage to reproduce your issue with PS1.7.6.8, see screen record below:

https://drive.google.com/file/d/1G-joBlS7EItBL4LaZbbYfnjaiBNNvi-l/view

But, could you please increase your **Upload Max File Size** to **512M** like in the screenshot below:

![image](https://user-images.githubusercontent.com/23308427/99225897-1b129d00-27e9-11eb-9992-b7896006e082.png)

Please check and feedback.

Thanks!

**Comment by ballashop** [comment] 2020-11-16 14:11
<img width="359" alt="Schermata 2020-11-16 alle 14 59 42" src="https://user-images.githubusercontent.com/28685316/99263290-47e1a700-281f-11eb-8c72-fcb2823cabf2.png">
Hi @hibatallahAouadni 
thanks for replying me, unfortunately it didn't work, the server technicians support ask us for more specifications, what does PrestaShop need to complete the execution?
The error is shown before the server time completes.
Where can we find the error? In which log?
Thanks a lot for any reply.
Balla

**Comment by hibatallahAouadni** [comment] 2020-11-16 14:23
Hello @ballashop ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- **debug mode report** (activate the debug mode)
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report]
(http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by ballashop** [comment] 2020-11-16 14:25
Dear @hibatallahAouadni 
thanks for your replying, I'll send all your request to the server support, I'll let you know asap.
Balla

**Comment by ballashop** [comment] 2020-11-16 15:48
Hi @hibatallahAouadni 

**Host:** --> PowerEdge R440 - processor Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz - RAM 32gb.
**Server config:** --> Centos 7 + nginx 1.18 + Apache 2.4.6. - php in fcgi mode.
**debug mode report (activate the debug mode)** --> no errors reported
**server error log** 
![error-apache](https://user-images.githubusercontent.com/28685316/99272359-00134d80-2828-11eb-8a81-9f3fd5f66a34.jpg)
I'm waiting your kind response.
Thanks a lot.
Balla

**Comment by hibatallahAouadni** [comment] 2020-11-16 15:59
Hello @ballashop 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server or a module problem.

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We will close this issue.

Thanks!

**Closed as completed by hibatallahAouadni** 2020-11-16 15:59 UTC
Labels: Bug, BO, Can't reproduce, Image, 1.7.6.8

**Comment by ballashop** [comment] 2020-11-16 16:33
Ok, thanks a lot for your support.
Balla
