### ISSUE TITLE
[SF Migration] Allows a module to add a field to a form, customize the rendering, choose where it appears, all of this easily

### ISSUE THREAD

**Issue by tomas862** [PrestaShop/PrestaShop#13876] opened 2019-05-20 13:32 UTC
Using the module hooks in identifiable object and option forms allow to add new form element in any place

**Problem**
Im currently working on https://github.com/PrestaShop/PrestaShop/pull/13875 which is in short: extending any form from module using `form_rest`.

It actually works but what if I could as a module developer not even extend a form but to put elements in desired order.

**Example**

```html
<div class="card-text">
    {{ ps.form_group_row(customerForm.gender_id, {}, {
    'label': 'Social title'|trans({}, 'Admin.Global')
    }) }}

    {{ ps.form_group_row(customerForm.first_name, {}, {
    'label': 'First name'|trans({}, 'Admin.Global'),
    'help': '%s %s'|format('Invalid characters:'|trans({}, 'Admin.Notifications.Info'), allowedNameChars)
    }) }}

    {% block customer_form_rest %}
    {{ form_rest(customerForm) }}
    {% endblock %}
</div>
```

so this is being rendered to html grouped like this:

```html
<div class="card-text">
    <div class="form-grouo row">social title content</div>
    <div class="form-grouo row">first name</div>
    <div class="form-grouo row">content from hook</div>
</div>
```

**Solution 1**

```css
.card-text {
display: flex;
flex-direction: column;
}
```

```html
<div class="card-text">
    <div class="form-grouo row" style="order:2">social title content</div>
    <div class="form-grouo row" style="order:3">first name</div>
    <div class="form-grouo row" style="order:1">content from hook</div>
</div>
```
Note - all elements should have order style attribute.

the result will be rendered depending on order style attribute - so in this case it will actually be rendered like:

```html
<div class="card-text">
   <div class="form-grouo row" style="order:1">content from hook</div>
    <div class="form-grouo row" style="order:2">social title content</div>
    <div class="form-grouo row" style="order:3">first name</div>
</div>
```

the disadvantage here is ofcourse that we use styles directly in html.

another solution would be apply auto generated classes using SASS loops:

```scss
      @for $i from 1 through 100 {
         .form-group-row-order-{i} {
             order: {i};
         }
      }
```
and use them without adding style attributes directly.

the problem is that ofcourse in loop we need to set limit, we will generate a lot of unused classes etc...

Can't think of right now of any interesting ideas. @eternoendless , @matks what do you think about the idea? Maybe this can be ofcourse achieved differently.

**Comment by matks** [comment] 2019-05-20 13:41
The aim is that, once this issue is fixed, dev modules should be able, on a migrated page to:
- easily add a form field
- easily choose how it should be rendered
- easily choose its rendering position
- all of this WITHOUT overriding the template, this should only be done for massive customization

@tomas862  suggestion above targets to solve the position issue

@eternoendless suggested that we might allow dev modules to *bind* a form field with a specific template block in order to tell the view "do not use the default rendering but this one instead" WITHOUT overriding the template

**Comment by eternoendless** [comment] 2019-07-24 15:13
Be aware that changing the field order using CSS does not change the order for screen readers.

**Comment by eternoendless** [comment] 2019-08-12 14:18
Why not use `form_widget(form)` to render the whole form? Modules could just edit the form builder to add their fields anywhere.

**Comment by matks** [comment] 2021-08-02 15:54
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16482, will be solved when https://github.com/PrestaShop/PrestaShop/issues/16482 is complete

**Closed as completed by matks** 2021-08-02 15:54 UTC
Labels: Improvement, migration
