### ISSUE TITLE
Translation page has error

### ISSUE THREAD

**Issue by protorp** [PrestaShop/PrestaShop#12536] opened 2019-02-12 07:21 UTC
**Describe the bug**
When open translation page, that has error. Need import ps macros on start file 
**in**
src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/Blocks/copy_language.html.twig
**add**
{% import '@PrestaShop/Admin/macros.html.twig' as ps %}

**To Reproduce**
1. Go to 'admin/improve/international/translations/settings'
2. See error

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment] 2019-02-12 07:35
Hi @protorp,

I did not manage to reproduce the issue with PS1.7.5.0.
I attached a video record.
https://drive.google.com/file/d/1SrQCgBTVT0Tvkqk7MG9CpFNBD7ux_Aph/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-03-14 07:32
Hi @protorp, 

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-03-14 07:32 UTC
Labels: Bug, BO, International, Translations, No change required, 1.7.5.0
