### ISSUE TITLE
PHP 7.4: Notice: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#19464] opened 2020-05-29 20:01 UTC
Bug: https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/category-header.tpl#L33

$category.image == NULL

for fix

{if $category.image != NULL && $category.image.large.url}

**Comment by jolelievre** [comment] 2020-06-01 09:59
Hi @TemKaSD 

As I explained in this comment https://github.com/PrestaShop/PrestaShop/issues/19463#issuecomment-636715107 The compatibility with PHP 7.4 is planned for PrestaShop 1.7.8 version.

I tried to reproduce your bug however but encountered many blocking issues related to PHP 7.4, so I guess you already fixed some of them to reproduce this issue? Could you detail the bug a little more because I'm not sure if it's purely related to PHP 7.4 or it's a "side effect" bug.

Thank you

**Comment by jolelievre** [comment] 2020-06-01 10:03
Also could you detail how this bug can be reproduced by a tester with detailed process.

Like:
- go on Front Office
- try to go on category page
- ...

**Comment by TemKaSD** [comment] 2020-06-01 19:30
@jolelievre Sorry.

PrestaShop v 1.7.7.0 Beta 1 && PHP 7.4.6.

1. Install PrestaShop
2. Advanced Parametrs > Performance
- Template compilation: Force
- Cache: No
- Debug mode: On
3. Catalog > Categories > Clothes > Edit > Delete Category cover image.
4. Go to /index.php?id_category=3&controller=category
![image](https://user-images.githubusercontent.com/6318282/83446460-0b4d0980-a492-11ea-91a3-5f4f962989cb.png)

P.S.: For Fix Main Page:
Disable module Contact information. It also has a bug that the developers ignore: https://github.com/PrestaShop/ps_contactinfo/pull/14 
![image](https://user-images.githubusercontent.com/6318282/83446049-69c5b800-a491-11ea-8c43-56c0f5ffa0fd.png)

**Comment by PierreRambaud** [comment] 2020-06-03 09:31
Duplicate of #16477

**Closed as completed by PierreRambaud** 2020-06-03 09:31 UTC
Labels: FO, Duplicate, No change required

**Comment by geimsdin** [comment] 2022-12-19 14:59
The problem is still present in 1.7.8.5 trying to interrogate the webservice.
location of the error: /classes/webservice/WebserviceOutputBuilder.php, line 716
