### ISSUE TITLE
Access to BO is slow even from the same local network

### ISSUE THREAD

**Issue by TomHsiung** [PrestaShop/PrestaShop#13622] opened 2019-04-30 16:24 UTC
Hello,

Access to BO is very slow even from I am from a same local network.

Tom

**Comment by khouloudbelguith** [comment] 2019-04-30 16:29
Hi @TomHsiung,

Tanks for your report.
We need more details to understand how we can reproduce your issue:
 - PrestaShop version, fresh install 1.7.5.1 or an upgrade from a previous version?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - Have you a lot of data?

Thanks!

**Comment by danirios93** [comment] 2019-05-02 07:24
Disable gamification module and you will be set :P At least it worked for me, seems it uses lots of resources of the BO

**Comment by khouloudbelguith** [comment] 2019-05-02 08:33
Hi @TomHsiung,

What is the exact version of the module `gamification `did you use?
Thanks!

**Comment by khouloudbelguith** [comment] 2019-05-31 08:22
Hi @TomHsiung,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-31 08:22 UTC
Labels: BO, Performance, No change required, 1.7.5.1
