### ISSUE TITLE
Cart refresh not automatic

### ISSUE THREAD

**Issue by klazer337** [PrestaShop/PrestaShop#20346] opened 2020-07-25 15:00 UTC
Hello, 

I have a problem with Shopping module cart or Prestashop 1.7.6.7. 

When I add an item into the cart, I have to refresh the page manually. It is not automatic. 

You can see the problem at https://ktd-supplies.com

![image](https://user-images.githubusercontent.com/43007697/88461825-43c3ff00-cea7-11ea-98f5-d418b911e6b5.png)

Best Regards, 

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by alfonsolr09** [comment] 2020-07-26 23:38
it is a bug that produced the module version 2.0.3
Below I attach the previous version of the module where it works well. don't update that module

https://wetransfer.com/downloads/6843ce10d47b714726894c2900d49dda20200726233706/f8906b1082f926c17d45331d15645e0320200726233720/071356?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email

**Comment by alfonsolr09** [comment] 2020-07-26 23:41
Duplicate of #18390

**Comment by alfonsolr09** [comment] 2020-07-26 23:42
khouloudbelguith commented on 31 Mar
Hi @alfonsolr09,

Here's the PR: #17633 to fix the issue.
it is fixed in the next version ps1.7.8.0
Your ticket is a duplicate of #16665 (comment)
So, I close it.
Thanks!

**Comment by alfonsolr09** [comment] 2020-07-26 23:44
With the version that I have attached with wetransfer you will not have any problem, I am the one I currently use.
just make sure not to update this module until prestashop 1.7.8 comes out

**Comment by khouloudbelguith** [comment] 2020-07-27 08:14
Hi @klazer337,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/17633 to fix the issue.
it is fixed in the next version ps1.7.8.0.
Your ticket is a duplicate of #16665
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment] 2020-07-27 08:14
Duplicate of #16665

**Closed as completed by khouloudbelguith** 2020-07-27 08:14 UTC
Labels: Duplicate

**Comment by klazer337** [comment] 2020-07-27 11:46
> it is a bug that produced the module version 2.0.3
> Below I attach the previous version of the module where it works well. don't update that module
> 
> https://wetransfer.com/downloads/6843ce10d47b714726894c2900d49dda20200726233706/f8906b1082f926c17d45331d15645e0320200726233720/071356?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email

I'm sorry but the problem isn't fixed. The refresh of the cart is ok but the page stay grey. I have to refresh manually the page to have access on the website and the modal confirmation doesn't appear : 

![image](https://user-images.githubusercontent.com/43007697/88538351-843e8c80-d00f-11ea-83cc-84c52cbd0dea.png)

**Comment by khouloudbelguith** [comment] 2020-07-27 11:59
@klazer337, this issue is fixed in the next release 1.7.8.0
You can use this patch
https://github.com/PrestaShop/PrestaShop/pull/17633/files

Thanks!

**Comment by jungwirbtgut** [comment] 2020-07-30 07:00
I have same issue, I use another theme and its not working with the older version. Very annoying -.- 
You can check here: https://bit.ly/33eDtbb

Any other idea how to fix?
