### ISSUE TITLE
Order view page discounts list not updating when adding product with free shipping

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#18025] opened 2020-03-06 13:51 UTC
#### Describe the bug

In order view page when I add product with new invoice and free shipping, there is a discount of free shipping generated, but its not visible in list unless i refresh the page.

[Orders _ Order MBGDKASMT from khououd belguith • 1752ps.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/24a903f8-d1c2-4491-8f9f-92d234cd6960)

#### Expected behavior

The list should be refreshed asynchronously and show the generated discount right after i add the product.

#### Steps to Reproduce

**NOTE**
It is only reproducable after this bug #18020 is fixed.

1. Go to `admin-dev/sell/orders/orders/{orderId}/view
2. Make sure order status is not "delivered" and you can add products.
3. Make sure your order has invoice. (to generate one, click `generate invoice` in Documents tab
4. Click `Add product`, search and select the product.
5. In right side of the screen you should see select box with invoices, select option `create new invoice`
6. Check "free shipping" in new invoice information block which should have just appeared.
7. Click `add`, see that no discounts are added to discounts list
8. Refresh the page and see that discount appears in list.

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by khouloudbelguith** [comment] 2020-03-06 17:02
Hi @zuk3975,

I have the same issue with PS1.7.5.2 and PS1.7.6.4 and branch 1.7.7.x.
https://drive.google.com/file/d/1IzCzDxE-x1PakzH5cWBpw71H5NVpQY_5/view
In the New Order page migrated to Symfony page "Shipping block missing in the Add a product block".
As reported here: https://github.com/PrestaShop/PrestaShop/issues/18020
I’ll add this to the debug roadmap.
Ping @matks @MatShir 

Thanks!

**Comment by marsaldev** [comment] 2022-04-29 09:33
Hi @zuk3975, 
I'm not able to reproduce this behaviour in the 1.7.7.0 and 8.0.0

https://user-images.githubusercontent.com/48283112/165919541-704e1599-7197-4f12-ae07-8790bb86c9ee.mp4

Maybe it has been already solved, do you think we can close this issue?
@MatShir @matks

**Comment by hibatallahAouadni** [comment] 2023-09-22 16:26
Indeed it's fixed with the new migrated Order Page :tada: thanks @marsaldev

**Closed as completed by hibatallahAouadni** 2023-09-22 16:26 UTC
Labels: Bug, Minor, Order, Fixed, 1.7.7.x, Verified
