### ISSUE TITLE
Debug issue on ps_legalcompliance PS 1.7.5.1

### ISSUE THREAD

**Issue by softweb-dev** [PrestaShop/PrestaShop#13245] opened 2019-04-08 16:35 UTC

**Comment by khouloudbelguith** [comment] 2019-04-09 07:16
Hi @softweb-dev,

Thanks to adding a short description of your issue and add steps to reproduce it in a new comment.

**Comment by khouloudbelguith** [comment] 2019-05-08 07:29
Hi @softweb-dev,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-05-08 07:29 UTC
Labels: No change required
