### ISSUE TITLE
DB exception when switching theme. 

### ISSUE THREAD

**Issue by ihulsbus** [PrestaShop/PrestaShop#30226] opened 2022-11-06 17:23 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When switching theme, I get a php error "The hook id #0 does not exist in database". 

Looking at the ps_hook table, the hook_id column has an auto_increment setting active. Even when recreating the table, auto_increment starts at 0 and the issue persists.
![Screenshot 2022-11-06 at 18 18 50](https://user-images.githubusercontent.com/11390889/200185219-8b8a1229-8aa8-4501-a305-12f0b57652f5.png)
![Screenshot 2022-11-06 at 18 18 45](https://user-images.githubusercontent.com/11390889/200185224-cc88acff-fa18-46f1-897c-4e5f2375f306.png)
![Screenshot 2022-11-06 at 18 19 13](https://user-images.githubusercontent.com/11390889/200185227-99447837-59d5-4192-9dc2-b26c8dc523ec.png)

### Expected behavior

I expect the system to know there cannot be a hook with id 0 and continue activating the theme. 

### Steps to reproduce

1. In the backoffice, go to design & logo
2. Switch to a different theme
3. Wait till the error occurs

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Unsure

**Comment by florine2623** [comment] 2022-11-07 10:13
Hello @ihulsbus ,

I can't reproduce your issue on PS 1.7.8.7.

https://user-images.githubusercontent.com/16019289/200284596-49e88d72-6177-4cd1-b6ff-ac985517f876.mov

Here's my ps_hook table:
<img width="773" alt="Screenshot 2022-11-07 at 11 11 55" src="https://user-images.githubusercontent.com/16019289/200284629-f2ce6e0b-a13a-40bd-875c-c769ab062130.png">

Have you tried with another template?
Is your template compatible with your version of PrestaShop ?

Waiting for your feedback.
Thanks!

**Comment by ihulsbus** [comment] 2022-11-07 21:06
Hi, I've tried with various themes all claiming 1.7 compatibility, but I keep running into the same error. The error also does not make sense as ID 0 does not seem to be possible in the ps_hook table due to the auto increment...

**Comment by sallemiines** [comment] 2022-11-08 14:56
Hello @ihulsbus 

Despite our efforts, we were not able to reproduce your issue with the provided information. 

We will close this issue.

Thank you

**Closed as completed by sallemiines** 2022-11-08 14:56 UTC
Labels: Bug, BO, Theme & logo, Invalid, 1.7.8.7
