### ISSUE TITLE
PS 1.7.2 customer cant access return order page

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#14078] opened 2019-06-05 08:06 UTC
**Describe the bug**
Login like customer, try to go on account > returns, you see a message "you dont have the permission for return product"

**To Reproduce**
Login like customer, try to go on account > returns, you see a message "you dont have the permission for return product"

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.2
PHP version: 7

**Comment by mariem-abid** [comment] 2019-06-07 13:06
Hi @matteolavaggi,

I did not manage to reproduce the issue with PS:1.7.5.2 and PS:1.7.6.0beta1
I attached a video record.
https://drive.google.com/file/d/1zsFW9xeDemyFq1GsRxQhorFlLy4AJUng/view
Thanks to check and feedback.

**Comment by khouloudbelguith** [comment] 2019-07-08 07:45
Hi @matteolavaggi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-07-08 07:45 UTC
Labels: FO, Merchandise returns, No change required
