### ISSUE TITLE
CORS troubles appeared just after upgrading Prestashop V 1.7.6.8 to 1.7.7

### ISSUE THREAD

**Issue by josepbbs** [PrestaShop/PrestaShop#22642] opened 2021-01-03 23:24 UTC
hello there

just upgrading prestashop version 1.7.6.8 to 1.7.7.0 its just started to appear CORS troubles messages in the browser Firefox console, some resources from a CDN that our prestashop site is trying to acces, are not accesible

I followed all instrutions here to fix that issue
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin
but nothing worked for me

Does anybody have experienced the same trouble and have solved this?

**Comment by hibatallahAouadni** [comment] 2021-01-04 14:43
Hello @josepbbs 

Please next time **follow the template to submit a complete bug report**.

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20528. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Closed as completed by hibatallahAouadni** 2021-01-04 14:43 UTC
Labels: Duplicate

**Comment by josepbbs** [comment] 2021-01-04 16:45
Oh sorry, I will do for tyhe next time, just I am new in this forum

I will be following this subscribe to this thread

thanks
