### ISSUE TITLE
If trying to edit a product, it keeps loading a lot because of categories

### ISSUE THREAD

**Issue by darylstone** [PrestaShop/PrestaShop#16164] opened 2019-10-28 19:28 UTC
**Describe the bug**
If you have many categories added to store and try to edit a product, it will be loading for a long time and after it is loaded, the categories on the right are all visible, which almost meanst endless scroll and a lot of time to wait.

**To Reproduce**
1. Add Many categories in my example 6547 Categories
2. Go to edit a product, it will unfold all categories on the right
---
1. If you click on "hide" and "show" again, it will mess up the categories and you need to reload the page.

**Screenshots**
![categories-2](https://user-images.githubusercontent.com/33138271/67711040-7052f500-f9c1-11e9-9412-4803ec25d999.jpg)
![categories-3](https://user-images.githubusercontent.com/33138271/67711557-844b2680-f9c2-11e9-848a-0dc594c0ea05.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.10

**Comment by khouloudbelguith** [comment] 2019-10-29 09:58
Hi @darylstone,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #13698
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-10-29 09:58
Duplicate of #13698

**Closed as completed by khouloudbelguith** 2019-10-29 09:58 UTC
Labels: Duplicate

**Comment by darylstone** [comment] 2019-11-11 18:32
Hi Khoul! Thanks for your reply. 

I just checked the report with the id #13698 but actually it is not the same bug. In my case it loads for a while (maybe a 1-2 min.) but it does not crash at all. Just the way how the categories are displayed and expanded makes it difficult to almost not possible to select the categories I want to. Look at the scrollbar on the right. You can scroll almost endless and the page is too long.

Remember Prestashop 1.6:

Only those categories which are already selected were expanded. Otherwise all other categories were not expanded, which made it easier to find the category seeking for.

**Comment by khouloudbelguith** [comment] 2019-11-12 08:12
Hi @darylstone,

You can follow my comment.
https://github.com/PrestaShop/PrestaShop/issues/13698#issuecomment-491289614

Thanks!
