### ISSUE TITLE
Mail Alerts : New order email is wrong if custom fields

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#23872] opened 2021-04-02 09:59 UTC
#### Describe the bug

When an order contains more than one item of the same product with custom fields, all custom field of all products are displayed in each line

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Order twice the same product with different information in custom text field
2. See the new order email contains all the custom fields of all products on each line

**Screenshots**

![image](https://user-images.githubusercontent.com/1193727/113405761-9f397b80-93aa-11eb-9efb-7cf9728a950a.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by florine2623** [comment] 2021-04-02 12:46
Hello @arirangz ,

Thanks for the report.
This is a duplicated of https://github.com/PrestaShop/PrestaShop/issues/16551

So I close your issue.

**Comment by florine2623** [comment] 2021-04-02 12:46
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16551

**Closed as completed by florine2623** 2021-04-02 12:46 UTC
Labels: Bug, Duplicate, Order, Product customization, 1.7.7.x, ps_emailalerts
