### ISSUE TITLE
Newsletter subscription button doesn't work

### ISSUE THREAD

**Issue by webstudio99** [PrestaShop/PrestaShop#35600] opened 2024-03-11 10:16 UTC
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, I installed the module "Newsletter subscription" in my theme but it doesn't work, when I press the subscribe button nothing happens... 

![YXmzl2X](https://github.com/PrestaShop/PrestaShop/assets/162980211/311f035e-5e1e-4e1c-85d7-a0de50b70b13)

### Steps to reproduce

Go to 'https://themedev.vitastrong.it/en/'
Scrool to the footer
Enter valid email
Checked the checkbox
Click the button 'Subscribe'

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Newsletter subscription - Version 2.8.2

**Comment by paulnoelcholot** [comment] 2024-03-11 15:54
Hello @webstudio99

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Closed as completed by paulnoelcholot** 2024-03-11 15:54 UTC
Labels: Bug, Invalid
