### ISSUE TITLE
ps_facetedsearch - In template creation, filters counter in BO is not correct

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#37587] opened 2024-12-05 16:00 UTC
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I create a new filters template, the total filters counter is not correct.

in my case, I have Total filters: 12, but when I check all of them, I have 13.

### Expected behavior

The Total filters: 12 and the actual number of filters should be the same.

![Image](https://github.com/user-attachments/assets/7e964116-2678-4c33-950a-30921e2d852e)

### Steps to reproduce

1. Go to BO > Modules > Configure ps_facetedsearch
2. Click Add new template
3. In Filters, enable all of them. You will see 13.
4. But in the Total filters, you will see 12 :x:

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v4.0.0

**Comment by paulnoelcholot** [comment] 2024-12-10 11:45
Hello @florine2623,

I reproduce the issue with PrestaShop version 9.0.0, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![Image](https://github.com/user-attachments/assets/e9a0a8d6-67cd-409a-80f2-92b3313096a5)

**Comment by Codencode** [comment] 2024-12-19 10:31
The problem is that the fixed filters are 7 and not 6:

1. Sub-categories filter
2. Product stock filter
3. Product extras filter
4. Product condition filter
5. Product brand filter
6. Product weight filter (slider)
7. Product price filter (slider)


The problem lies here:
https://github.com/Codencode/ps_facetedsearch/blob/edb3292ebb699e1067845a50c5a554a28ca3c523/ps_facetedsearch.php#L869-L880

Now I'll create a PR.

**Comment by Codencode** [comment] 2024-12-19 10:36
PR: https://github.com/PrestaShop/ps_facetedsearch/pull/1117

**Closed as completed** 2024-12-19 12:39 UTC
Labels: Bug, BO, Modules, Faceted search, Verified, Module, 9.0.x
