### ISSUE TITLE
translation not working in my shop

### ISSUE THREAD

**Issue by kubiak85** [PrestaShop/PrestaShop#15443] opened 2019-09-06 11:16 UTC
Hi everyone,
My shop (Prestashop 1.7.5.2)not loading translation of administrator panel. I download my language pack from (Add / Update language). I set the default language to Czech and I have disabled all other languages. I still don't see Czech translations. Could someone give me folders where there are translations besides /themes/[my layout]/translation/....  ?

**Comment by khouloudbelguith** [comment] 2019-09-06 11:24
Hi @kubiak85,

the zip files are downloaded in the `folder/translations`, and then they are extracted and the XLF files they contain are exported to `app / Resources / translations`.

Thanks to check & feedback.

**Comment by kubiak85** [comment] 2019-09-06 11:27
@khouloudbelguith but my shop not loading my choosen language. could you tell me the reason?

**Comment by khouloudbelguith** [comment] 2019-09-06 11:28
@kubiak85, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by kubiak85** [comment] 2019-09-06 12:16
@khouloudbelguith Can you tell me why when I click save the translation it still doesn't work? and old unchanged is displayed?

**Comment by kubiak85** [comment] 2019-09-06 12:25
@khouloudbelguith https://drive.google.com/file/d/1qu15A1gpB3qx38Yw_07ziPmglYSLjL6N/view?usp=sharing

**Comment by kubiak85** [comment] 2019-09-06 12:27
Can you name which php files are adapted for this or apply some solution to this record. JavaScriptci console shows nothing

**Comment by khouloudbelguith** [comment] 2019-09-06 14:50
@kubiak85, I did not manage to reproduce the issue with PS1.7.6.1/PS1.7.5.2 & a custom theme.
I attached a screen record
https://drive.google.com/file/d/1nqmPxT5MQUhbrRuLRpUgdblG9proNl3B/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment] 2019-10-07 07:58
Hi @kubiak85,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Closed as completed by khouloudbelguith** 2019-10-07 07:58 UTC
Labels: Bug, BO, Translations, No change required, 1.7.5.2
